### PR TITLE
Ensure UserSecretsIdAttribute is added to assembly

### PR DESCRIPTION
**Pull request by eerhardt**
When Microsoft.Extensions.Configuration.UserSecrets is referenced transitively, for example through Extensions.Hosting, the UserSecretsIdAttribute isn't getting added to the built assembly. This is because the logic is contained in a `build` folder which is excluded by the dependency from Extensions.Hosting.

The fix is to move the logic to `buildTransitive`, so it gets picked up by NuGet. One wrinkle is that the logic now conflicts with the netstandard compatibility logic added by the library infrastructure. In order to make progress, disable that logic for this package and rely on its dependencies to raise the compat error.

Contributes to #63246

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]
LGTM. The only thing I hope @ericstj may confirm, disabling the NETStandard Compat target wouldn't have any side effect we didn't think about. The mentioned mitigation makes sense to me though.

**Review by safern — APPROVED** [review]

**Comment by danmoseley** [comment]
Is it feasible to have a test? (given this was significant enough to service for) But perhaps that would have to be in the SDK repo since it involves restoring packages?

**Comment by eerhardt** [comment]
> Is it feasible to have a test? (given this was significant enough to service for) But perhaps that would have to be in the SDK repo since it involves restoring packages?

I can add a test, but as you said, it will have to be in a different repo since this is a packaging issue. We don't currently have packaging tests in this repo.

**Comment by danmoseley** [comment]
Your call, just curious. LMK if you would like me to merge.

**Comment by eerhardt** [comment]
> LMK if you would like me to merge.

This one is `main`. I have permission to merge. https://github.com/dotnet/runtime/pull/63423 is the 6.0 backport.

**Comment by ericstj** [comment]
> disabling the NETStandard Compat target wouldn't have any side effect we didn't think about. 

I talked with @eerhardt and am OK with this.

**Pull request merged**
