### PR TITLE
[mono][wasm] Fix an issue with the passing of small vtypes.

### PR DESCRIPTION
**Pull request by vargaz**
Fixes an issue introduced by 915ee6db9cb871bb2ef32698015bca0f2c895ce8.

### CODE REVIEW

**Comment by vargaz** [comment]
https://github.com/dotnet/runtime/issues/62362

**Comment by radical** [comment]
Which of [these tests](https://github.com/dotnet/runtime/blob/main/src/libraries/tests.proj#L25) can be re-enabled?

**Comment by vargaz** [comment]
Either this PR or
https://github.com/dotnet/runtime/pull/62380
will fix the issue.

**Comment by radical** [comment]
All the AOT jobs are green! 👍

**Review by lambdageek — APPROVED** [review]

**Pull request merged**
