### PR TITLE
Fix in-process decoding of DateTime in EventSource

### LINKED ISSUE #61563: WriteEventCore with DateTime has changed behavior in .Net 6.0
### Description

When updating to .NET 6.0, we encountered issues with DateTimes within events containing an incorrect year. It appears that the optimization in pull request #52092 changed the behavior so that it's no longer decoded from a FileTime and is instead decoded using the full tick value.

### Reproduction Steps

Write an event using WriteEventCore like the example below

```
            [Event(1)]
            public unsafe void DateTimeEvent(DateTime dateTime)
            {
                if (this.IsEnabled())
                {
                    var fileTimeVal = dateTime.Year < 1601 ? 0 : dateTime.ToFileTimeUtc();
                    EventSource.EventData* descrs = stackalloc EventSource.EventData[1];
                    descrs[0].DataPointer = (IntPtr)(&fileTimeVal);
                    descrs[0].Size = sizeof(long);
                    WriteEventCore(1, 1, descrs);
                }
            }
```

### Expected behavior

EventWrittenEventArgs payload from an EventTraceListener contains the DateTime matching the input.

### Actual behavior

EventWrittenEventArgs payload from an EventTraceListener contains the DateTime, but the year is off by 1600 as it appears to be decoding from ticks rather than file time ticks.

### Other information

This appears to be a breaking change from NetCore3.1 and Net 5.0 so seeking guidance on whether this is an expected change in behavior or if this is a bug. Thanks!

### PR DESCRIPTION
**Pull request by josalem**
Fixes https://github.com/dotnet/runtime/issues/61563

Will require backporting to release/6.0 since this is a regression from 5.0.

@MihaZupan root caused this issue succinctly in this comment: https://github.com/dotnet/runtime/issues/61563#issuecomment-1040146346

> @tommcdon it is a bug introduced by #52092 in .NET 6.0, but only affects in-process `EventListener`s.
>
> The difference is in how the serialized value (`long`) is de-serialized by `DecodeObjects`:
> - In 5.0, the `DateTime` would be [converted from a `long` back to a `DateTime` via `DateTime.FromFileTimeUtc`](https://github.com/dotnet/runtime/blob/2705fc02018f16cef2e99101cf8a58e16d26b692/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L1832-L1836)
> - In 6.0, the value is [interpreted as a `DateTime` directly](https://github.com/dotnet/runtime/blob/6dd808ff7ae62512330d2f111eb1f60f1ae40125/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L1840-L1843) (i.e. exact number of ticks)
> 
> Sadly this was not caught by tests since none of them uses `DateTime` with `WriteEventCore` - we are only testing the `varargs` overload.
>
> The fix here would be to change
https://github.com/dotnet/runtime/blob/a25aa6641b605f1ad28c75cddcfa204f8153abe3/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L1844
> to
> ```c#
> decoded = DateTime.FromFileTimeUtc(*(long*)dataPointer);
> ```
>
> -- MihaZupan

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]

**Review by noahfalk — APPROVED** [review]
LGTM

**Comment by danmoseley** [comment]
> Sadly this was not caught by tests 

Is such a test feasible?

**Comment by josalem** [comment]
> > Sadly this was not caught by tests
> 
> Is such a test feasible?

Let me take a look and add one if so.

**Review by MihaZupan — APPROVED** [review]

**Comment by josalem** [comment]
Test added!

**Comment by josalem** [comment]
The test failures are https://github.com/dotnet/runtime/issues/67878.

The macOS NativeAOT job timed out, so I'll rerun it.

**Comment by josalem** [comment]
Tests all seem to pass but the Build Analysis check fails with test failures that aren't shown elsewhere. Folks okay with merging anyway?

**Comment by noahfalk** [comment]
I'd merge it : )

**Pull request merged**
