### PR TITLE
ARM64-SVE: Use `emitIns_R_R_Imm` to handle large immediates correctly

### LINKED ISSUE #105954: JIT: Assertion failed `!"Instruction cannot be encoded: IF_DI_2A"`
Hit by Antigen on ARM64. Repro is quite large: [gist](https://gist.github.com/amanasifkhalid/85090e1f144000c6e5a19dbfd980552b).

On a few SVE-specific paths, we call `emitIns_R_R_I` directly to emit an `add` instruction, instead of `emitIns_R_R_Imm`, which handles immediates too large to fit in the `R_R_I` variant of `add`. Should be easy to find and fix these cases.

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Fixes #105954. cc @dotnet/arm64-contrib

### CODE REVIEW

**Review by jakobbotsch — APPROVED** [review]

**Review by a74nh — APPROVED** [review]
Nit: Add test case for the failing cases.

**Comment by amanasifkhalid** [comment]
> Nit: Add test case for the failing cases.

The [repro](https://gist.github.com/amanasifkhalid/85090e1f144000c6e5a19dbfd980552b) for the initial failure is quite large, and I haven't had much luck in pruning it while maintaining the repro. Are we ok with checking in a regression test this big?

**Comment by jakobbotsch** [comment]
Yeah, I would skip the regression test when it's that large.

The immediate may be the local's stack offset, so to prune it you may need to replace some locals with large stack locals that take up a lot of stack space. Hmm, perhaps a stress mode would be in order...

**Comment by amanasifkhalid** [comment]
/ba-g blocked by dead-lettering tests from Azure outage

**Pull request merged**
