### PR TITLE
Fix issue 45183

### LINKED ISSUE #45183: ilasm doesn't preserve "where T : struct", instead produces "where T : ValueType"
### Description

I'm observing in source-build that our 5.0.0 `ilasm` has a regression when given this IL method signature:

```
.method /*06000757*/ public hidebysig static 
        int32  Compare<valuetype .ctor (System.ValueType/*020000C7*/) T>(
          valuetype System.Nullable`1/*02000089*/<!!T> n1,
          valuetype System.Nullable`1/*02000089*/<!!T> n2) cil managed
```

Viewing the result in ILSpy shows me these IL results. Red is "bad", with 5.0.0 `ilasm`. Green is "good", with old 3.1 `ilasm`.

```diff
 	.method public hidebysig static 
-		int32 Compare<(System.ValueType) T> (
+		int32 Compare<valuetype .ctor (System.ValueType) T> (
 			valuetype System.Nullable`1<!!T> n1,
 			valuetype System.Nullable`1<!!T> n2
 		) cil managed 
```

**This issue looks to me like it's blocking the source-build 5.0.0 GA release.**

The FSharp compiler seems to rely on the signature being correct, or else the build fails. With the C# decompilation result, it's easier to see why (for me 😄):

```diff
-		public static int Compare<T>(T? n1, T? n2) where T : ValueType
+		public static int Compare<T>(T? n1, T? n2) where T : struct
```

More details and more examples at https://github.com/dotnet/source-build/pull/1920#discussion_r530093550.

Full original IL file that may be able to repro: https://raw.githubusercontent.com/dotnet/source-build-reference-packages/ddfd9f5918bdaefc0d02db8ea1ae8a8b1ff11b23/src/targetPacks/ILsrc/netstandard.library/2.0.3/build/netstandard2.0/ref/netstandard.il (signature at line 28420)

(Edited to add in context:) Self-contained repro to run on `linux-x64`: https://github.com/dagood/repro/tree/ilasm-struct-vs-valuetype

@JulieLeeMSFT @briansull can you help with this?

/cc @dleeapho @dseefeld 

### Regression?

Seems like a regression from 3.1.0-ish `ilasm` to a 5.0.0 `ilasm`. This happened when we upgraded from 3.1.0 to 5.0.0 in dotnet/source-build-reference-packages: https://github.com/dotnet/source-build-reference-packages/compare/fe6afa24c69cc135200bbe1f12a90a11a450dcb0...c52443b2ff14d485043d322bbc4c3dc4b592b3cd.

The 5.0.0 `ilasm` includes the recent patch to fix a different regression: https://github.com/dotnet/runtime/pull/44850.

### PR DESCRIPTION
**Pull request by briansull**
Preserve the paramAttrs when calling `SetGenericParamProps`

### CODE REVIEW

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by briansull** [comment]
@BruceForstall PTAL

**Comment by BruceForstall** [comment]
Fixes #45183

**Review by BruceForstall — APPROVED** [review]
Please trigger ilasm round-trip job (https://dev.azure.com/dnceng/public/_build?definitionId=870)

**Comment by briansull** [comment]
Manual Run for #20201130.1 Fix issue 45183 (#45307)
https://dev.azure.com/dnceng/public/_build/results?buildId=903772&view=results

**Pull request merged**
