### PR TITLE
Update to the 22.04 debpkg image so we're on a newer ubuntu version.

### PR DESCRIPTION
**Pull request by jkoritzinsky**

### CODE REVIEW

**Review by sbomer — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
Blocked on dotnet/arcade#13730

**Comment by jkoritzinsky** [comment]
Blocked on https://github.com/dotnet/runtime/pull/87522

**Comment by jkoritzinsky** [comment]
Failures are all unrelated. The changes in this PR are not invoked on any build leg that failed.

**Pull request merged**
