### PR TITLE
Fix build for FreeBSD arm64 w/NativeAOT

### PR DESCRIPTION
**Pull request by sec**
Based on https://github.com/dotnet/runtime/commit/70e1072edc6c1a399f77a4de7de84045193f1409 this PR adds same things for arm64 host.
With those changes runtime is able to build fine under FreeBSD arm64 host (there is some manual patching required with ObjWriter and UseHardlinksIfPossible property set to false on two targets and BinPlaceUseHardlinksIfPossible=false).

I was using `clang14` and needed to pass extra `-z nostart-stop-gc` to make the build pass for crossgen2 (reading https://lld.llvm.org/ELF/start-stop-gc looks like that change was done starting from 13) - if this should be handled in diffrent way, let me know.

@Thefrank @janvorli @am11

### CODE REVIEW

**Comment by Thefrank** [comment]
Freebsd x64 exhibits the same issue under LLVM/Clang15
```
ld : error : undefined symbol: __start___modules [/root/runtime/src/coreclr/tools/aot/crossgen2/crossgen2.csproj]
##vso[task.logissue type=error;sourcepath=ld;linenumber=0;columnnumber=0;code=;](NETCORE_ENGINEERING_TELEMETRY=Build) undefined symbol: __start___modules
  >>> referenced by main.cpp:182 (/root/runtime/src/coreclr/nativeaot/Bootstrap/main.cpp:182)
  >>>               main.cpp.o:(main) in archive /root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/aotsdk/libbootstrapper.a
  >>> the encapsulation symbol needs to be retained under --gc-sections properly; consider -z nostart-stop-gc (see https://lld.llvm.org/ELF/start-stop-gc)
  
ld : error : undefined symbol: __stop___modules [/root/runtime/src/coreclr/tools/aot/crossgen2/crossgen2.csproj]
##vso[task.logissue type=error;sourcepath=ld;linenumber=0;columnnumber=0;code=;](NETCORE_ENGINEERING_TELEMETRY=Build) undefined symbol: __stop___modules
  >>> referenced by main.cpp:182 (/root/runtime/src/coreclr/nativeaot/Bootstrap/main.cpp:182)
  >>>               main.cpp.o:(main) in archive /root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/aotsdk/libbootstrapper.a
clang-15 : error : linker command failed with exit code 1 (use -v to see invocation) [/root/runtime/src/coreclr/tools/aot/crossgen2/crossgen2.csproj]
##vso[task.logissue type=error;sourcepath=clang-15;linenumber=0;columnnumber=0;code=;](NETCORE_ENGINEERING_TELEMETRY=Build) linker command failed with exit code 1 (use -v to see invocation)
/root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/build/Microsoft.NETCore.Native.targets(331,5): error MSB3073: The command ""/usr/local/bin/clang15" "/root/runtime/artifacts/obj/coreclr/crossgen2/x64/Release/native/crossgen2.o" -o "/root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/crossgen2/native/crossgen2" /root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/aotsdk/libbootstrapper.a /root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/aotsdk/libRuntime.ServerGC.a /root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/aotsdk/libstdc++compat.a /root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/aotsdk/libnumasupportdynamic.a /root/runtime/artifacts/bin/microsoft.netcore.app.runtime.freebsd-x64/Release/runtimes/freebsd-x64/native/libSystem.Native.a /root/runtime/artifacts/bin/microsoft.netcore.app.runtime.freebsd-x64/Release/runtimes/freebsd-x64/native/libSystem.Globalization.Native.a /root/runtime/artifacts/bin/microsoft.netcore.app.runtime.freebsd-x64/Release/runtimes/freebsd-x64/native/libSystem.IO.Compression.Native.a /root/runtime/artifacts/bin/microsoft.netcore.app.runtime.freebsd-x64/Release/runtimes/freebsd-x64/native/libSystem.Net.Security.Native.a /root/runtime/artifacts/bin/microsoft.netcore.app.runtime.freebsd-x64/Release/runtimes/freebsd-x64/native/libSystem.Security.Cryptography.Native.OpenSsl.a -g -Wl,-rpath,'$ORIGIN' -Wl,--build-id=sha1 -Wl,--as-needed -pthread -ldl -lz -lrt -lm -pie -Wl,-z,relro -Wl,-z,now -L/usr/local/lib -lgssapi_krb5 -L/usr/local/lib -linotify -Wl,--discard-all -Wl,--gc-sections" exited with code 1. [/root/runtime/src/coreclr/tools/aot/crossgen2/crossgen2.csproj]
##vso[task.logissue type=error;sourcepath=/root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/build/Microsoft.NETCore.Native.targets;linenumber=331;columnnumber=5;code=MSB3073;](NETCORE_ENGINEERING_TELEMETRY=Build) The command ""/usr/local/bin/clang15" "/root/runtime/artifacts/obj/coreclr/crossgen2/x64/Release/native/crossgen2.o" -o "/root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/crossgen2/native/crossgen2" /root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/aotsdk/libbootstrapper.a /root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/aotsdk/libRuntime.ServerGC.a /root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/aotsdk/libstdc++compat.a /root/runtime/artifacts/bin/coreclr/freebsd.x64.Release/aotsdk/libnumasupportdynamic.a /root/runtime/artifacts/bin/microsoft.netcore.app.runtime.freebsd-x64/Release/runtimes/freebsd-x64/native/libSystem.Native.a /root/runtime/artifacts/bin/microsoft.netcore.app.runtime.freebsd-x64/Release/runtimes/freebsd-x64/native/libSystem.Globalization.Native.a /root/runtime/artifacts/bin/microsoft.netcore.app.runtime.freebsd-x64/Release/runtimes/freebsd-x64/native/libSystem.IO.Compression.Native.a /root/runtime/artifacts/bin/microsoft.netcore.app.runtime.freebsd-x64/Release/runtimes/freebsd-x64/native/libSystem.Net.Security.Native.a /root/runtime/artifacts/bin/microsoft.netcore.app.runtime.freebsd-x64/Release/runtimes/freebsd-x64/native/libSystem.Security.Cryptography.Native.OpenSsl.a -g -Wl,-rpath,'$ORIGIN' -Wl,--build-id=sha1 -Wl,--as-needed -pthread -ldl -lz -lrt -lm -pie -Wl,-z,relro -Wl,-z,now -L/usr/local/lib -lgssapi_krb5 -L/usr/local/lib -linotify -Wl,--discard-all -Wl,--gc-sections" exited with code 1.
```

**Comment by am11** [comment]
We added `UseLlvmLinker` to remedy exactly this error on linux. `-p:UseLlvmLinker=true` on command-line or `<UseLlvmLinker>true</UseLlvmLinker>` in csrpoj.

**Comment by am11** [comment]
https://github.com/dotnet/runtime/pull/80613#discussion_r1069498088

**Comment by sec** [comment]
> We added `UseLlvmLinker` to remedy exactly this error on linux. `-p:UseLlvmLinker=true` on command-line or `<UseLlvmLinker>true</UseLlvmLinker>` in csrpoj.

Thanks - adding this seems to work fine with the build. does this PR makes sense to merge, as it's adding some RIDs for arm64 same way x64 was added then?

**Comment by am11** [comment]
@sec, I think it would be fine to change the defaults for FreeBSD with:

`<UseLlvmLinker Condition="'$(UseLlvmLinker)' == '' and '$(TargetOS)' == 'freebsd'">true</UseLlvmLinker>`

in `Microsoft.NETCore.Native.Unix.targets` top properties block. This way the user on FreeBSD will not need to set it (if someone is intentionally experimenting with gcc-toolchain on FreeBSD, they will still be able to do so with override properties: `-p:UseLlvmLinker=false -p:CppCompilerAndLinker=gcc` etc.).

**Review by jkotas — APPROVED** [review]
LGTM. Thanks!

**Comment by jkotas** [comment]
> change the defaults for FreeBSD

I think it is a good idea. It can be done as a new PR.

**Pull request merged**
