### PR TITLE
[wasm][debugger] Apply changes on wasm using sdb protocol.

### PR DESCRIPTION
**Pull request by thaystg**
DotnetDebugger.applyUpdates is the message that should be called to apply updates.

I'm receiving the same parameters that are being passed currently from aspnetcore:
https://github.com/dotnet/sdk/blob/05db7bd25f0d1132333a0f72fe94c9adb611a3ed/src/BuiltInTools/DotNetDeltaApplier/HotReloadAgent.cs#L188

Implemented the same tests that we had using C# API, now using SdbProtocol.

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Review by lewing — APPROVED** [review]
lgtm if this is the plan

**Comment by lambdageek** [comment]
> lgtm if this is the plan

It's worthwhile to have the option to do it this way, I think.

**Comment by thaystg** [comment]
@lewing , can I merge then? Or we should wait for the plan?

**Comment by lewing** [comment]
you can merge it

**Pull request merged**
