### PR TITLE
JIT: don't allow negative edge weights

### PR DESCRIPTION
**Pull request by AndyAyersMS**
If the solver wants to set the edge weight below zero, set it to
zero if within slop, or disallow if not.

Addresses assert seen in ~~#52864~~ #52785.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib @trylek 

I will add more assertion/post-phase checking for edge weights in a follow-up PR.

**Review by BruceForstall — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Failures were from #49585, which was reverted at #52885.

**Comment by EgorBo** [comment]
> Addresses assert seen in #52864.

um.. isn't it supposed to be https://github.com/dotnet/runtime/issues/52785 ?

**Comment by AndyAyersMS** [comment]
> um.. isn't it supposed to be #52785 ?

Indeed. Thanks.

**Pull request merged**
