### PR TITLE
Improve tracing of HTTP/2 PINGs

### PR DESCRIPTION
**Pull request by antonfirsov**
#57617 can be a worrying reliability issue. In case there will be other reports, it is very important to have the ability to collect traces that can help hunting down a potential bug in HttpClient or Kestrel. Currently we are not logging received PING content at all, which prevents investigation based on customer data.

This is a minimal-risk (log only) addition to #54755, which I believe we should backport to 6.0 (including RC2, and maybe RC1 if it meets the bar).

Contributes to #57617.

### CODE REVIEW

**Review by ManickaP — APPROVED** [review]

**Review by karelz — APPROVED** [review]

**Comment by karelz** [comment]
@antonfirsov for 6.0 backport, can we somehow easily check that when the logging is enabled, nothing bad happens and/or that we get what we need? (e.g. with induced error)

**Comment by karelz** [comment]
CI failures: System.Threading.Tasks.Tests - known problem #57331, re-running tests

**Comment by antonfirsov** [comment]
I pushed a test improvement to make sure both failure cases (`ThrowProtocolError()` calls) are covered.

Did a local run of all flow control tests having an EventListener attached, and everything worked as expected.

**Review by MihaZupan — APPROVED** [review]

**Comment by antonfirsov** [comment]
Outerloop test failures are unrelated and likely external outages: #46439 #41381

**Pull request merged**
