### PR TITLE
Remove synchronization from Http2Connection.ExtendWindow

### PR DESCRIPTION
**Pull request by antonfirsov**
There is an opportunity for simplification: `_pendingWindowUpdate` is the only state the `ExtendWindow` method touches under the lock. There is no other code that reads or writes `_pendingWindowUpdate` after the creation of the connection object. Originating from `ProcessIncomingFramesAsync`, calls to `ExtendWindow` are sequential, and never expected to happen concurrently.

### CODE REVIEW

**Review by MihaZupan — APPROVED** [review]
Nice. LGTM

**Review by wfurt — APPROVED** [review]
LGTM

**Pull request merged**
