### PR TITLE
Fix/31527 invalid currentculture applying

### LINKED ISSUE #31527: Bug in DateTimeConverter when time has been specified
When converting DateTime, with a specified time, to string the wrong format is used.
Source: System.ComponentModel.TypeConverter/src/System/ComponentModel/DateTimeConverter.cs (line dotnet/corefx#120)

The following line (line number 120)
return dt.ToString(format, CultureInfo.CurrentCulture);

should be replaced with
return dt.ToString(format, culture);

### PR DESCRIPTION
**Pull request by Maximys**
Fix #31527  .
Be carefully, because it has some breaking changes, which was described by @ericstj [here](https://github.com/dotnet/runtime/issues/31527#issuecomment-1517907902)

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]

**Comment by tarekgh** [comment]
@Maximys is it possible you can help with the request in the comment https://github.com/dotnet/runtime/pull/85297#issuecomment-1521745650 too? I appreciate your help fixing the issue.

**Comment by Maximys** [comment]
@tarekgh , yes. I plan to create a PR on the weekend.

**Comment by tarekgh** [comment]
@Maximys thanks again for your help. Let's keep this PR open till we open the breaking change PR and then we merge it.

**Comment by Maximys** [comment]
@tarekgh , I had just created [required PR](https://github.com/dotnet/docs/issues/35201) about current breaking change and send letter to dotnetbcn@microsoft.com

**Pull request merged**
