### PR TITLE
Merge #91634 into release/8.0-staging

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Testing to see If I can merge #91634 into release/8.0 without breaking CI...

This is the first of multiple merges to transition the release/8.0 branch over to official 1ES templates.

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
cc @jkoritzinsky @agocke @eduardo-vp -- I ran an official build with this change in dotnet-runtime-official, and it seems to have passed. Let me know if you'd like me to share the link to the build offline. Thanks!

**Comment by jkoritzinsky** [comment]
@amanasifkhalid you can share the official build links in the PR.

Also, Can you re-target to `release/8.0-staging`? It's very rare for us to merge into the release branches directly (permissions to merge into them are extremely locked down).

**Comment by amanasifkhalid** [comment]
> you can share the official build links in the PR.

Thanks for letting me know! Here's the [build link.](https://dev.azure.com/dnceng/internal/_build/results?buildId=2432717&view=results).

> Also, Can you re-target to release/8.0-staging? It's very rare for us to merge into the release branches directly (permissions to merge into them are extremely locked down).

Sure thing; done.

**Review by jkoritzinsky — APPROVED** [review]
Official build looks good to me!

**Review by agocke — APPROVED** [review]
LGTM, thanks!

**Comment by amanasifkhalid** [comment]
@agocke @jkoritzinsky thank you for the reviews! Is there someone I need to ping to get servicing approval?

**Review by jeffschwMSFT — APPROVED** [review]
approved.  we will take this as tell mode (infra only change)

cc @ericstj

**Pull request merged**
