### PR TITLE
[System.Drawing.Common] In test, dispose of Metafile after Graphics

### LINKED ISSUE #37838: Mono SIGABRT in System.Drawing.Common affecting some test runs
Affects clean test runs in https://github.com/dotnet/runtime/pull/37536
AzDO run: https://dev.azure.com/dnceng/public/_build/results?buildId=681708&view=logs&j=c6f8dc49-92a1-5760-c098-ba97b8142bfb&t=22b0078b-0469-5ba6-8725-2121fdbae049&l=42
Test log: https://helix.dot.net/api/2019-06-17/jobs/73f57a06-eec2-4676-8076-302ccabec52f/workitems/System.Drawing.Common.Tests/console

```txt
===========================================================================================================
/private/tmp/helix/working/A83A0976/w/A92E096B/e /private/tmp/helix/working/A83A0976/w/A92E096B/e
  Discovering: System.Drawing.Common.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Drawing.Common.Tests (found 1565 of 1967 test cases)
  Starting:    System.Drawing.Common.Tests (parallel test collections = on, max threads = 4)
    System.Drawing.Drawing2D.Tests.BlendTests.Ctor_LargeCount_ThrowsOutOfMemoryException [SKIP]
      Condition(s) not met: "IsNotIntMaxValueArrayIndexSupported"
    System.Drawing.Printing.Tests.PrintControllerTests.OnStartPage_InvokeWithPrint_ReturnsNull [SKIP]
      Condition(s) not met: "IsAnyInstalledPrinters"

=================================================================
	Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10305ca56 - /private/tmp/helix/working/A83A0976/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_dump_native_crash_info
	0x102ffeae5 - /private/tmp/helix/working/A83A0976/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_handle_native_crash
	0x1030574c3 - /private/tmp/helix/working/A83A0976/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : altstack_handle_and_restore
	0x7fff5d81d916 - /usr/lib/system/libsystem_c.dylib : fclose
	0x10771e7c0 - /usr/local/lib/libgdiplus.dylib : gdip_metafile_stop_recording
	0x10770ab5e - /usr/local/lib/libgdiplus.dylib : GdipDeleteGraphics
	0x108df9d35 - Unknown
	0x108ad8c91 - Unknown
	0x102f61f7e - /private/tmp/helix/working/A83A0976/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_jit_runtime_invoke
	0x10313acf8 - /private/tmp/helix/working/A83A0976/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_runtime_invoke_checked
	0x10314288c - /private/tmp/helix/working/A83A0976/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : mono_runtime_try_invoke_array
	0x1030ec3e4 - /private/tmp/helix/working/A83A0976/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : ves_icall_InternalInvoke
	0x1030f8484 - /private/tmp/helix/working/A83A0976/p/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.dylib : ves_icall_InternalInvoke_raw

<snip>

----- end Wed Jun 10 17:22:30 PDT 2020 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
```

Possibly related: https://github.com/dotnet/runtime/issues/32827, https://github.com/dotnet/runtime/issues/23784, but this issue appears to have a different termination code.

<!-- runfo report start -->
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[839551](https://dev.azure.com/dnceng/public/_build/results?buildId=839551)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.81.Amd64.Open|||||
|[839551](https://dev.azure.com/dnceng/public/_build/results?buildId=839551)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.10.Amd64.Server19H1.ES.Open|||||
|[839551](https://dev.azure.com/dnceng/public/_build/results?buildId=839551)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.81.Amd64.Open|||||
|[839551](https://dev.azure.com/dnceng/public/_build/results?buildId=839551)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.10.Amd64.Server19H1.ES.Open|||||
|[836799](https://dev.azure.com/dnceng/public/_build/results?buildId=836799)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.81.Amd64.Open|||||
|[836799](https://dev.azure.com/dnceng/public/_build/results?buildId=836799)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.10.Amd64.Server19H1.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-7c630d366baa45db89/System.Drawing.Common.Tests/console.f6ea26ec.log?%3F%253F%25253Fsv%25253D2019-07-07%252526se%25253D2020-10-20T16%25253A28%25253A31Z%252526sr%25253Dc%252526sp%25253Drl%252526sig%25253Dextkuw8yomd2iVmVEtx2eNCt6sQWpNxXStqS83PqNoo%25253D)|[core dump]()|||
|[836302](https://dev.azure.com/dnceng/public/_build/results?buildId=836302)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.81.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-6d936d623b604fe6ac/System.Drawing.Common.Tests/console.777780f2.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-20T04%253A00%253A32Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DbuMj3DkNC1fcaUoMZZKb%252FZos1tNepAae%252FX7E7wbNpg0%253D)|[core dump]()|||
|[836302](https://dev.azure.com/dnceng/public/_build/results?buildId=836302)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.10.Amd64.Server19H1.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-c38d7f3330304c139f/System.Drawing.Common.Tests/console.395501a8.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-20T04%253A00%253A33Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D34m26nXsqiXF384PfPpnJxownjMtftZyEc4oxXJVpwA%253D)|[core dump]()|||
|[836287](https://dev.azure.com/dnceng/public/_build/results?buildId=836287)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 40691](https://github.com/dotnet/runtime/pull/40691)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.81.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-40691-merge-01a0fab890634e42ab/System.Drawing.Common.Tests/console.c889b8ac.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-20T03%253A51%253A12Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DoJtC8ozGtxwir0DTcaJhLi7BEnuJgwJNnfjzaskHJdA%253D)|[core dump]()||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-40691-merge-01a0fab890634e42ab/System.Drawing.Common.Tests/d528517c-c7b0-4ceb-97b9-4fc9da703c82.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-20T03%25253A51%25253A12Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DoJtC8ozGtxwir0DTcaJhLi7BEnuJgwJNnfjzaskHJdA%25253D)|
|[836178](https://dev.azure.com/dnceng/public/_build/results?buildId=836178)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42875](https://github.com/dotnet/runtime/pull/42875)|net5.0-OSX-Debug-x64-Mono_release-OSX.1015.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42875-merge-46e4259a32e74ce8b1/System.Drawing.Common.Tests/console.0a9d6832.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-20T00%253A43%253A30Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DWyLoFxASNOUWvcJnAEKDGJxeTcoFL34j0239FcI5oe0%253D)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42875-merge-46e4259a32e74ce8b1/System.Drawing.Common.Tests/b3cdf1aa-cfda-4c7e-8849-0ad34ef45216.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-20T00%25253A43%25253A30Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DWyLoFxASNOUWvcJnAEKDGJxeTcoFL34j0239FcI5oe0%25253D)|
|[835874](https://dev.azure.com/dnceng/public/_build/results?buildId=835874)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 40435](https://github.com/dotnet/runtime/pull/40435)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.81.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-40435-merge-2486b0317b7d4eab8d/System.Drawing.Common.Tests/console.a04ac4cf.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-19T21%253A59%253A34Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DEGvlaZyTfIjYAO8F00MVtGj3my1V8ZiHC6rTvPi7Gi8%253D)|[core dump]()|[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-40435-merge-2486b0317b7d4eab8d/System.Drawing.Common.Tests/testResults.xml?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-19T21%253A59%253A34Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DEGvlaZyTfIjYAO8F00MVtGj3my1V8ZiHC6rTvPi7Gi8%253D)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-40435-merge-2486b0317b7d4eab8d/System.Drawing.Common.Tests/d615ecd7-aab7-43b4-bb45-936565195aca.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-19T21%25253A59%25253A34Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DEGvlaZyTfIjYAO8F00MVtGj3my1V8ZiHC6rTvPi7Gi8%25253D)|
|[835820](https://dev.azure.com/dnceng/public/_build/results?buildId=835820)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.81.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-051f545621d94d42b9/System.Drawing.Common.Tests/console.9e3794a7.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-19T21%253A12%253A48Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dw9w3FQlHHWUhPsMXoXMM%252FAI6tmsEO4ZlB2RvZTrAteA%253D)|[core dump]()|||
|[835820](https://dev.azure.com/dnceng/public/_build/results?buildId=835820)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.10.Amd64.Server19H1.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-4cc3d751a98643db88/System.Drawing.Common.Tests/console.757c6aff.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-19T21%253A12%253A49Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D44st5xKA%252FrBP4SpXXpxT2CtPC7etJKzHEcS4JxKMzBI%253D)|[core dump]()|||
|[835053](https://dev.azure.com/dnceng/public/_build/results?buildId=835053)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 39923](https://github.com/dotnet/runtime/pull/39923)|net5.0-OSX-Debug-x64-Mono_release-OSX.1014.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-39923-merge-0050f2225fee464eb0/System.Drawing.Common.Tests/console.9364cf28.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-19T10%253A54%253A54Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DRvy0fICocUcCcdgMg8INVq%252BA%252FSWZzQVb6C4B%252BIjPMps%253D)||||
|[835053](https://dev.azure.com/dnceng/public/_build/results?buildId=835053)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 39923](https://github.com/dotnet/runtime/pull/39923)|net5.0-OSX-Debug-x64-Mono_release-OSX.1015.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-39923-merge-2fd4adf7b77c40aca3/System.Drawing.Common.Tests/console.ba478d58.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-19T10%253A54%253A55Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DpzqX0tTINfUpE%252FtVxAukdmQtJUPH9FN%252BdquneEv%252FCgo%253D)||||
|[834855](https://dev.azure.com/dnceng/public/_build/results?buildId=834855)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.81.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-998f371ec4de40f487/System.Drawing.Common.Tests/console.139e2f55.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-19T06%253A26%253A05Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DjME0LwU4tiT09uyZFXbPFyqjAOUyZlI9aLgkohqHaWc%253D)|[core dump]()|||
|[834855](https://dev.azure.com/dnceng/public/_build/results?buildId=834855)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.10.Amd64.Server19H1.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-7e88320c389c4ac281/System.Drawing.Common.Tests/console.67a1a5fe.log?%3F%253Fsv%253D2019-07-07%2526se%253D2020-10-19T06%253A26%253A06Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DxRc5eYpwftGoqZbjhBUZHJIgFni0ftatGNeCRH9sAVg%253D)|[core dump]()|||
|[834366](https://dev.azure.com/dnceng/public/_build/results?buildId=834366)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.81.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-9ea4ea076e5b4e4fac/System.Drawing.Common.Tests/console.f074b290.log?%3Fsv%3D2019-07-07%26se%3D2020-10-18T23%3A03%3A51Z%26sr%3Dc%26sp%3Drl%26sig%3DJE4I4Rr8ChykyLAdb18esYgPRAdnJSQfUu6zWbngirQ%3D)|[core dump]()|||
|[834366](https://dev.azure.com/dnceng/public/_build/results?buildId=834366)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.10.Amd64.Server19H1.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-5bd4797df98240f582/System.Drawing.Common.Tests/console.92a98699.log?%3Fsv%3D2019-07-07%26se%3D2020-10-18T23%3A03%3A53Z%26sr%3Dc%26sp%3Drl%26sig%3D03yBATcmlsQKBwfUGEDpHtEkMTN1N65ddJXcKfndbcU%3D)|[core dump]()|||
|[834366](https://dev.azure.com/dnceng/public/_build/results?buildId=834366)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.81.Amd64.Open|||||
|[833333](https://dev.azure.com/dnceng/public/_build/results?buildId=833333)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.81.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-194faacfec6b4606b5/System.Drawing.Common.Tests/console.f09e1544.log?%3Fsv%3D2019-07-07%26se%3D2020-10-17T23%3A29%3A38Z%26sr%3Dc%26sp%3Drl%26sig%3Dh%2FR0%2F55Kt%2B8QkmIObzVzSoTJJGMON5zlPMemO6gaowA%3D)|[core dump]()|||
|[833333](https://dev.azure.com/dnceng/public/_build/results?buildId=833333)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.10.Amd64.Server19H1.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-fd4ec37765af4df5af/System.Drawing.Common.Tests/console.dd58a0c2.log?%3Fsv%3D2019-07-07%26se%3D2020-10-17T23%3A29%3A40Z%26sr%3Dc%26sp%3Drl%26sig%3Dc%2FWblRm5e8zneaR6PVl3bwzT%2BBPC%2BEjH3uGs7kykL%2BU%3D)|[core dump]()|||
|[831886](https://dev.azure.com/dnceng/public/_build/results?buildId=831886)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.81.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-6e89cc14b845474f85/System.Drawing.Common.Tests/console.581df403.log?%3Fsv%3D2019-07-07%26se%3D2020-10-15T23%3A18%3A59Z%26sr%3Dc%26sp%3Drl%26sig%3DdXMMvI0COzz7SNSJ88WcNN5W44la%2FONgGT5QaQrhwtc%3D)|[core dump]()||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-6e89cc14b845474f85/System.Drawing.Common.Tests/677ba8b4-c03f-438a-bddf-12947aa3bc70.log?%3Fsv%3D2019-07-07%26se%3D2020-10-15T23%253A18%253A59Z%26sr%3Dc%26sp%3Drl%26sig%3DdXMMvI0COzz7SNSJ88WcNN5W44la%252FONgGT5QaQrhwtc%253D)|
|[831886](https://dev.azure.com/dnceng/public/_build/results?buildId=831886)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42759](https://github.com/dotnet/runtime/pull/42759)|net5.0-Windows_NT-Debug-x64-Mono_release-Windows.10.Amd64.Server19H1.ES.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42759-merge-41c994a7049b4fcabe/System.Drawing.Common.Tests/console.09da3f22.log?%3Fsv%3D2019-07-07%26se%3D2020-10-15T23%3A19%3A02Z%26sr%3Dc%26sp%3Drl%26sig%3DLfZnLnKNvOF3%2B5pPugcpS2TDcjtF4nH%2FxgUEqlLL6rQ%3D)|[core dump]()|||
|[829731](https://dev.azure.com/dnceng/public/_build/results?buildId=829731)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 42119](https://github.com/dotnet/runtime/pull/42119)|net5.0-Linux-Debug-arm64-Mono_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-bfcd90a-20200127194925|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-42119-merge-6e26c6d9d8ef4d4a9c/System.Drawing.Common.Tests/console.3f87594f.log?%3Fsv%3D2019-07-07%26se%3D2020-10-14T22%3A41%3A23Z%26sr%3Dc%26sp%3Drl%26sig%3D%2BlupEi2XUPruaxcnCKOV02xnAuYS%2Fkwg91vZi4V3OgU%3D)||||
|[828477](https://dev.azure.com/dnceng/public/_build/results?buildId=828477)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 41808](https://github.com/dotnet/runtime/pull/41808)|net5.0-OSX-Debug-x64-Mono_release-OSX.1014.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-41808-merge-31ef3aac530e4dcab8/System.Drawing.Common.Tests/console.3247807d.log?%3Fsv%3D2019-07-07%26se%3D2020-10-14T01%3A55%3A44Z%26sr%3Dc%26sp%3Drl%26sig%3DuIqiyeqUJ2VNpEqpQIuFK1Opj2W1gPKZo6oDAz%2ByX3Y%3D)|[core dump](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-41808-merge-31ef3aac530e4dcab8/System.Drawing.Common.Tests/core.64460?%3Fsv%3D2019-07-07%26se%3D2020-10-14T01%3A55%3A44Z%26sr%3Dc%26sp%3Drl%26sig%3DuIqiyeqUJ2VNpEqpQIuFK1Opj2W1gPKZo6oDAz%2ByX3Y%3D)||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-41808-merge-31ef3aac530e4dcab8/System.Drawing.Common.Tests/069c4897-0bb8-4940-ac4c-2417877b47fd.log?%3Fsv%3D2019-07-07%26se%3D2020-10-14T01%253A55%253A44Z%26sr%3Dc%26sp%3Drl%26sig%3DuIqiyeqUJ2VNpEqpQIuFK1Opj2W1gPKZo6oDAz%252ByX3Y%253D)|



Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|1|14|

<!-- runfo report end -->

### PR DESCRIPTION
**Pull request by lambdageek**
Fixes https://github.com/dotnet/runtime/issues/37838

Verified using libgdiplus built with
https://github.com/mono/libgdiplus/pull/671

### CODE REVIEW

**Comment by lambdageek** [comment]
The changes to `libgdiplus` aren't necessary for the fix - they just make the crash due to incorrect use more visible and deterministic

**Review by safern — APPROVED** [review]
Thanks, @lambdageek

**Comment by stephentoub** [comment]
I'm a little confused here. It sounds like the test is doing the wrong thing, but even if the test is buggy, it shouldn't be able to crash the runtime like this.  Doesn't this suggest there's also a bug in either System.Drawing.Common, libgdiplus, or mono?

**Comment by stephentoub** [comment]
Oh, I see, the fix for the issue is this for the test + https://github.com/mono/libgdiplus/pull/671 for the actual bug?

**Comment by stephentoub** [comment]
> The changes to libgdiplus aren't necessary for the fix - they just make the crash due to incorrect use more visible and deterministic

Now I'm back to being confused ;-)

**Comment by lambdageek** [comment]
Is it a big in libgdiplus if it's being used incorrectly? I'm not sure.

The change in libgdiplus is effectively an assertion so that you _definitely_ crash if you use the API incorrectly.  The current behavior is that you overwrite some freed memory - so you get a crash if you get unlucky.

**Comment by lambdageek** [comment]
> even if the test is buggy, it shouldn't be able to crash the runtime like this

it's P/Invoking a native library that is writing over freed memory.  why would we expect something other than a crash in that situation?

**Comment by stephentoub** [comment]
The test is P/Invoking? Where?

**Comment by lambdageek** [comment]
Now I'm confused.  

Are there two problems here?

1. Do we agree that the test is definitely wrong? it shouldn't dispose of the `Metafile` instance in the scope of a `Graphics` that's using it?  If so then this is the PR that fixes that.
2. The next question is - if it's possible for libgdiplus to detect that it's being used incorrectly, should we assert or return some error code?  (I see that `Image.Dispose` is prepared to deal with error statuses, so
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Drawing.Common/src/System/Drawing/Image.Unix.cs#L448)

If there's a bug to be fixed in libgdiplus, I think that's a separate issue, no?

**Comment by stephentoub** [comment]
> Do we agree that the test is definitely wrong?

Not sure.  There are plenty of situations where one disposable type wrapping another disposable type doesn't do anything in its Dispose except call Dispose on the wrapped instance, and Dispose is idempotent, so it's acceptable use.  There are also cases where objects are ref counted, e.g. with SafeHandle, and the wrapper would have taken a ref on the wrapped thing such that disposing the wrapped thing wouldn't have actually closed the wrapped thing until after everything was disposed and released ref counts.  I don't know what category these fall into nor what guarantees we've made in docs... but it seems like this works on Windows?

> if it's possible for libgdiplus to detect that it's being used incorrectly

My confusion is that the APIs being used here are managed.  Misuse of a managed API shouldn't cause a seg fault / crash.  If it's actually misuse, worst case it should throw an exception.  e.g. if I misuse FileStream, it shouldn't crash the process, worst case a use-after-dispose would produce an ObjectDisposedException.  So I'm trying to understand what makes this special; it's possible there some aspect of this I'm just missing that makes it different :)

**Comment by lambdageek** [comment]
Thanks @stephentoub.  Going to look for another approach (leaning toward refcounting)

**Comment by stephentoub** [comment]
Thanks, @lambdageek.  Just to be clear, I wasn't trying to demand a different direction, simply trying to understand and highlight differences I see in other APIs, ask questions to better understand, etc.

**Comment by stephentoub** [comment]
(Also, if this is causing problems in CI or for devs running tests locally, we can of course disable the test until it's resolved.  We can also change the test as you suggested if we believe that's more represented of typical usage; I just want to make sure we don't then lose sight of the underlying issue being worked around.)

**Pull request closed without merging**
