### PR TITLE
Update riscv64 CI image

### PR DESCRIPTION
**Pull request by am11**
host: Azure Linux 3.0 amd64 (llvm 18)
rootfs: Ubuntu 24.04 riscv64 (llvm 18, gcc 13)

### CODE REVIEW

**Comment by am11** [comment]
mono: https://github.com/dotnet/runtime/pull/103616/checks?check_run_id=26348530488
coreclr: https://github.com/dotnet/runtime/pull/103616/checks?check_run_id=26348520143

failures are unrelated error.

cc @clamp03 @akoeplinger

**Comment by am11** [comment]
mono: https://github.com/dotnet/runtime/pull/103616/checks?check_run_id=26348530488
coreclr: https://github.com/dotnet/runtime/pull/103616/checks?check_run_id=26348520143

failures are unrelated.

cc @clamp03 @akoeplinger

**Comment by clamp03** [comment]
@am11 Thank you!
@dotnet/samsung Could you please check and update if you are using the CI image?

**Review by akoeplinger — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
The previous run had a failure that isn't yet tracked:

> D:\a\_work\1\s\.packages\microsoft.dotnet.build.tasks.targetframework\9.0.0-beta.24311.10\build\BinPlace.targets(38,5): error MSB3030: Could not copy the file "D:\a\_work\1\s\artifacts\bin\win-x64.Release\corehost\hostfxr.dll.pdb" because it was not found. [D:\a\_work\1\s\src\libraries\externals.csproj]
##[error].packages\microsoft.dotnet.build.tasks.targetframework\9.0.0-beta.24311.10\build\BinPlace.targets(38,5): error MSB3030: (NETCORE_ENGINEERING_TELEMETRY=Build) Could not copy the file "D:\a\_work\1\s\artifacts\bin\win-x64.Release\corehost\hostfxr.dll.pdb" because it was not found.

I retried to see if this is flakiness. We should file an issue for that.

**Comment by akoeplinger** [comment]
Ok. That job ran on Windows so it can't be related to the PR.

**Comment by am11** [comment]
It also failed here: https://dev.azure.com/dnceng-public/public/_build/results?buildId=710913&view=results. Seems like it is failing for some time. @elinor-fung @lambdageek is hostfxr pdb not available in mono minijit which the package is expecting?

**Comment by jkotas** [comment]
> Ok. That job ran on Windows so it can't be related to the PR.

Yes, we still want to have it tracked. "failures are unrelated" is not a valid justification for ba-g.

**Comment by steveisok** [comment]
My bad - sorry. Fix is in https://github.com/dotnet/runtime/pull/103641

**Pull request merged**
