### PR TITLE
[release/8.0][mono][HybridGlobalization] Fix ShortDatePattern year format to be "yyyy" 

### PR DESCRIPTION
**Pull request by matouskozak**
## Customer Impact

- [X] Customer reported
- [ ] Found internally

When using Hybrid Globalization mode on Apple mobile platforms with .NET 8, we are returning `ShortDatePattern` in ICU-like format instead of .NET-like format. This PR fixes this by normalizing the short date format returned from Apple ICU and converting "yy" year format to the expected "yyyy"

Hybrid Globalization mode in .NET 8 is off by default, so this only affects applications where the developer explicitly opted into using this mode.

NOTE: This is a .NET 8 version of https://github.com/dotnet/runtime/pull/99908.

## Regression
- [x] Yes - only when user opts into hybrid globalization
- [ ] No

## Testing
We added a small set of tests to verify the correct functionality of the fix.

## Risk
Low, only affects scenarios where Hybrid Globalization mode on Apple mobile platforms is enabled.

---

fyi: @vitek-karas @mkhamoyan @ilonatommy @akoeplinger @steveisok

### CODE REVIEW

**Review by ilonatommy — APPROVED** [review]

**Review by mkhamoyan — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
lgtm.  we will take for consideration in 8.0.x

**Comment by jeffschwMSFT** [comment]
@vitek-karas can you take a look at the CI failures?

**Comment by matouskozak** [comment]
Failures are known as the same tests can be found failing on a combination of https://dev.azure.com/dnceng-public/public/_build/results?buildId=642490&view=results, https://dev.azure.com/dnceng-public/public/_build/results?buildId=641494&view=logs&j=12cf7a0b-4da0-5b17-37e7-24aa7cbf9869, or https://dev.azure.com/dnceng-public/public/_build/results?buildId=638193

One exception is `Microsoft.Bcl.Cryptography.Tests` failing on `tvos-arm64 Release AllSubsets_Mono` that I didn't find failing anywhere else on `release/staging-8.0`. However, the error doesn't seem to be related to this PR. I will re-run the tests to confirm.

**Comment by matouskozak** [comment]
> Failures are known as the same tests can be found failing on a combination of https://dev.azure.com/dnceng-public/public/_build/results?buildId=642490&view=results, https://dev.azure.com/dnceng-public/public/_build/results?buildId=641494&view=logs&j=12cf7a0b-4da0-5b17-37e7-24aa7cbf9869, or https://dev.azure.com/dnceng-public/public/_build/results?buildId=638193
> 
> One exception is `Microsoft.Bcl.Cryptography.Tests` failing on `tvos-arm64 Release AllSubsets_Mono` that I didn't find failing anywhere else on `release/staging-8.0`. However, the error doesn't seem to be related to this PR. I will re-run the tests to confirm.

Took a second look after re-run and all failing tests seem unrelated and are already failing on the `release/8.0-staging` branch.

**Pull request merged**
