### PR TITLE
Update the assert to include Vector64/Vector128 CreateScalar

### LINKED ISSUE #91336: Assertion failed '(node->GetHWIntrinsicId() == NI_Vector64_Create) || (node->GetHWIntrinsicId() == NI_Vector128_Create) || (node->GetHWIntrinsicId() == NI_Vector64_CreateScalarUnsafe) || (node->GetHWIntrinsicId() == NI_Vector128_CreateScalarUnsafe) || (node->GetHWIntrinsicId() == NI_AdvSimd_DuplicateToVector64) || (node->GetHWIntrinsicId() == NI_AdvSimd_DuplicateToVector128) || (node->GetHWIntrinsicId() == NI_AdvSimd_Arm64_DuplicateToVector64) || (node->GetHWIntrinsicId() == NI_AdvSimd_Arm64_DuplicateToVector128)' during 'Lowering nodeinfo'
Repro: https://gist.github.com/kunalspathak/0839543ce2f125c8e6363c7049e4984d

### PR DESCRIPTION
**Pull request by kunalspathak**
The assert was missing `CreateScalar` intrinsic entries.

Fixes: #91336

### CODE REVIEW

**Comment by kunalspathak** [comment]
superpmi-* jobs are failing because the collection is not available for the guid. I have kicked off another superpmi collection run.

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by kunalspathak** [comment]
can someone review this? should be quick.

**Review by jakobbotsch — APPROVED** [review]

**Comment by kunalspathak** [comment]
Failures seems to be known repository issue. https://github.com/dotnet/runtime/pull/91504/checks?check_run_id=16584913496

**Pull request merged**
