### PR TITLE
Merging small assemblies (part 2/N)

### PR DESCRIPTION
**Pull request by jkotas**
Contributes to #2138

### CODE REVIEW

**Comment by jkotas** [comment]
Resolved conflicts. @ericstj Could you please take look?

**Comment by ericstj** [comment]
Do you think we need TypeForwardedFrom attribute on any other types?  Any of those `Enum`s part of the closure of a serializeable type?

**Review by ericstj — APPROVED** [review]
LGTM modulo enum concern (and merge conflicts)

**Comment by jkotas** [comment]
> Do you think we need TypeForwardedFrom attribute on any other types? 

I do not see any such type in the list. (As always, there is some small chance that somebody may be depending on the assembly identity of one of these types, but that is impossible to predict.)

**Pull request merged**
