### PR TITLE
Workaround EventSource counters race condition in networking tests

### LINKED ISSUE #106268: [Test Failure] EventSource_SendingRequest_PathAndQueryRedaction_LogsStartStop
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=768382
Build error leg or test failing: System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_SendingRequest_PathAndQueryRedaction_LogsStartStop
Pull request:

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": ["System.Net.Http.Functional.Tests.TelemetryTest.ValidateEventCounters", "Assert.Contains() Failure: Filter not matched in collection"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Example failure

```
System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_SendingRequest_PathAndQueryRedaction_LogsStartStop(uriTail: "/test/path?q1=a&q2=b", disableRedaction: True) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:

        Child exception:
          Xunit.Sdk.ContainsException: Assert.Contains() Failure: Filter not matched in collection
        Collection: [0, 0, 0, 0, 0, ···]
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs(666,0): at System.Net.Http.Functional.Tests.TelemetryTest.ValidateEventCounters(ConcurrentQueue`1 events, Int32 requestCount, Boolean shouldHaveFailures, Int32 versionMajor, Boolean requestLeftQueue)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs(479,0): at System.Net.Http.Functional.Tests.TelemetryTest.<>c.<<EventSource_SendingRequest_PathAndQueryRedaction_LogsStartStop>b__7_0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs(65,0): at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)

        Child process:
          System.Net.Http.Functional.Tests, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SendingRequest_PathAndQueryRedaction_LogsStartStop>b__7_0(System.String, System.String, System.String)

        Child arguments:
          1.1, /test/path?q1=a&q2=b, /test/path?q1=a&q2=b
```

### PR DESCRIPTION
**Pull request by MihaZupan**
Fixes #106268
See https://github.com/dotnet/runtime/issues/106268#issuecomment-2284626183

Since some `IncrementingPollingCounter` data may be dropped from the first reported increment, this change ensures that the background timer thread is running before executing the actual test code.

Updated our Http and Security tests as those are the only ones using an `IncrementingPollingCounter`.

### CODE REVIEW

**Review by antonfirsov — APPROVED** [review]
LGTM

**Review by rzikm — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
