### PR TITLE
[mono] Enable callconv and classloader runtime tests

### PR DESCRIPTION
**Pull request by kotlarmilos**
This PR enables callconv and classloader runtime tests in AOT mode.

Fixes https://github.com/dotnet/runtime/pull/90280#issuecomment-1675187419

### CODE REVIEW

**Review by ivanpovazan — APPROVED** [review]

**Comment by SamMonoRT** [comment]
Please verify the logs to ensure enabled tests are running/passing without known failures.

**Review by SamMonoRT — APPROVED** [review]

**Review by LeVladIonescu — APPROVED** [review]
Tests successfully ran, failures look unrelated.

**Comment by kotlarmilos** [comment]
The `JIT/Directed` testing group is a merged testing group which is optimized for Helix execution but isn't compatible with apple mobile targets. I've attempted to enable merged testing groups in this PR, but we may encounter more issues (waiting for the CI).

**Comment by kotlarmilos** [comment]
@LeVladIonescu The runtime tests are using interpreter, so we can't confirm if the tests were executed successfully. I reopened the issue, which should be confirmed using apple mobile pipeline (once switched to full AOT mode) or full AOT linux pipeline. 

This PR improves test coverage for apple mobile platforms and will be merged.

**Pull request merged**
