### PR TITLE
Add a new wrapper `runtime-wasm.yml` to be used from azdo

### PR DESCRIPTION
**Pull request by radical**
Currently, we have `runtime-wasm` in azdo pointing to
`runtime-extra-platforms.yml`, which has some scheduled triggers
defined. azdo seems to use these for running `runtime-wasm` too.

Instead, in azdo use a new `runtime-wasm.yml` for `runtime-wasm` pipeline, so
we can explicitly avoid the scheduled triggers. This yml just uses the
existing `runtime-extra-platforms-wasm.yml`.

### CODE REVIEW

**Review by safern — APPROVED** [review]
LGTM

**Comment by radical** [comment]
@safern do we need to wait for the builds to complete before merging this one?

**Comment by safern** [comment]
It seems like `runtime-wasm` skipped all legs: https://dev.azure.com/dnceng/public/_build/results?buildId=1601074&view=results it seems like the evaluate paths step wasn't inserted for some reason.

**Comment by safern** [comment]
Ah, you need to import the variables template 😄

**Comment by radical** [comment]
Failures are unrelated.

**Pull request merged**
