### PR TITLE
[release/5.0] Use substitute SHA-1 implementation in wasm (#44982)

### PR DESCRIPTION
**Pull request by omajid**
This is a port of #44982 to the `release/5.0` branch, to fix the license issue there too. I made no changes, it's just `git format-patch -1 a61b05410466e8e489c09e22a79190adc3a1ecaa && git am`.

cc @GrabYourPitchforks @stephentoub @steveisok @akoeplinger

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]

**Comment by danmosemsft** [comment]
@dleeapho @omajid this doesn't have to get into 5.0.3 right? It's already patched in the source build repo. 

I mean it's fine if it does but we wouldn't spin new builds for it, yes?

**Comment by danmosemsft** [comment]
cc @Anipik

**Comment by omajid** [comment]
> @dleeapho @omajid this doesn't have to get into 5.0.3 right?
>
> I mean it's fine if it does but we wouldn't spin new builds for it, yes?

Speaking for myself, there's no urgency here: it's fine if it gets into 5.0.4 or even 5.0.5. It's not urgent enough to hold back any releases that are in progress.

>  It's already patched in the source build repo.

source-build has the original source (with a non-free copyright) as well as patches to fix it. I think we want to get rid of the original source as soon as possible: I am scared of shipping the original non-free source and what the implications might be, even if there's a patch that later overwrites it.

**Comment by danmosemsft** [comment]
I see. The key thing in my mind is that RedHat consumes and builds the "fixed" sources -- it sounds like they're consuming the "non fixed" sources and then patching them.

@Anipik is this too late for 5.0.3? We shouldn't do anything unnatural.

**Comment by omajid** [comment]
> I see. The key thing in my mind is that RedHat consumes and builds the "fixed" sources -- it sounds like they're consuming the "non fixed" sources and then patching them.

Exactly! As a workaround, when I create the source-tarball, [I delete this file and the patch and replace it manually with the fixed up copy](https://pagure.io/dotnet-sig/dotnet5.0/blob/master/f/build-dotnet-tarball#_166). That avoids shipping the original file and the patch. We end up shipping just the fixed copy. It's not a good idea for long term maintenance, but it's not a blocker right now.

**Comment by Anipik** [comment]
> @Anipik is this too late for 5.0.3? We shouldn't do anything unnatural.

yes this one is late for 5.0.3

**Comment by dleeapho** [comment]
Agree there is no urgency for 5.0.3

**Review by Anipik — APPROVED** [review]

**Pull request merged**
