### PR TITLE
[release/6.0] Manually backporting #74599 to 6.0

### PR DESCRIPTION
**Pull request by StephenMolloy**
Backporting #75366 which was a backport of #74599 to 7.0 for RC2 from 8.0.

## Customer Impact
DataContractSerializer has not been properly accounting for big-or-little endian-ness when writing a few types "to the wire." This has not previously been an issue, since to my knowledge there have not been any commonly used big-endian platforms with .Net. DCS writes little-endian on the wire, so not accounting for endian-ness has simply worked because little-endian platforms write little-endian on the wire as expected. IBM helped bring .Net to their big-endian s360 platform in 6.0 however, causing failures when serializing between different platforms.

## Testing

Tests were added to check the correct little-endian output for affected types and arrays of types.

## Regression

No... but kind of yes. Strictly speaking, the code has always missed this -endian handling for these types and was not regressed. But the introduction of big-endian implementations of dotnet in 6.0 has exposed this issue. So in a sense, DCS was fine in 5.0 and now is not correct on some platforms in 6.0 and later.

## Risk

Low. The change is faithful to current execution for little-endian platforms and only does different things on a big-endian platform... which is currently broken without this fix.

### CODE REVIEW

**Comment by carlossanlop** [comment]
When this is ready, please send an email to Tactics requesting approval, add the `servicing-consider` label, and request a code review sign-off from an area owner. Monday 14th is the deadline for merging fixes that should go into the December release.

**Comment by StephenMolloy** [comment]
@mconnew and @HongGit - this is just #75648 reincarnated to force rebasing onto a more compliant point of release/6.0. Tests are passing without boatloads of noise now. :)

**Comment by carlossanlop** [comment]
@StephenMolloy today is the deadline for merging backports that should go into December release. Please get an M2 sign-off, then send an email to Tactics to request backport approval, and add the `servicing-consider` label.

**Review by HongGit — APPROVED** [review]

**Comment by carlossanlop** [comment]
Approved by Tactics via email.

**Comment by carlossanlop** [comment]
Approved by Tactics (6.0.14).
Signed off by area owner.
No OOB changes needed for the involved csproj files (No `IsPackable=true`).
CI green.
Ready to merge. :shipit:

**Pull request merged**
