### PR TITLE
Detect read-only Oid at runtime.

### LINKED ISSUE #40984: OID copying in S.S.C.Pkcs may not be sufficient
Since `Oid` is "init-once" in .NET 5, The S.S.C.Pkcs library was changed (by me) to remove defensive `Oid` copies in #38387. Since this package targets other frameworks, it has a helper function intended to continue to copy where applicable.

https://github.com/dotnet/runtime/blob/38aa0b76a6423b902cc4b6c310cad9c49ba675b6/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/PkcsHelpers.cs#L696-L704

However, it looks like the Pkcs project has a target specifically for netcoreapp3.0:

https://github.com/dotnet/runtime/blob/38aa0b76a6423b902cc4b6c310cad9c49ba675b6/src/libraries/System.Security.Cryptography.Pkcs/src/System.Security.Cryptography.Pkcs.csproj#L8

That would mean that 5.0 versions of this package do not create the Oid copies when targeting netcoreapp3.0, but the init-once behavior of Oid is only in net5.0.

I think then the conditional needs to be:

```c#
#if NETCOREAPP && !NETCOREAPP3_0
             return oid; 
 #else 
             return oid is null ? null : new Oid(oid); 
 #endif
```

### PR DESCRIPTION
**Pull request by vcsjones**
Since S.S.C.Pkcs ships configurations other than the current .NET version, we should detect if the current runtime requires defensive Oid copies.

Fixes #40984

### CODE REVIEW

**Review by bartonjs — APPROVED** [review]

**Comment by jeffhandley** [comment]
Assuming we need to take this in 5.0, then once this is merged in to `master`, we'll need to create a PR that cherry-picks the commit from this PR into the `release/5.0` branch, with the following information filled out in the PR description:

#### Customer Impact
#### Testing
#### Risk

@bartonjs please let me know when that PR is created and I'll request approval to merge it in.

**Comment by vcsjones** [comment]
> Assuming we need to take this in 5.0

Would be a good idea, I think.

Looks similar to what I've done for 3.0 stuff like https://github.com/dotnet/corefx/pull/42942 minus the regression section. Happy to do the 🍒 ⛏️, too.

**Comment by bartonjs** [comment]
Just to confirm (while the tests are being slow to finish): We have tests for this, but they didn't trip because they'd need the new assembly/package to be executed on a 2.1 or 3.1 runtime (where Oid was not init-only)... and we don't test that configuration for this package?

**Comment by bartonjs** [comment]
Also, we apparently have a backport bot now, so I'll try it out after the merge :)

**Comment by vcsjones** [comment]
> We have tests for this, but they didn't trip because they'd need the new assembly/package to be executed on a 2.1 or 3.1 runtime

Right, the tests are net48 and NetCoreAppCurrent only.

https://github.com/dotnet/runtime/blob/60eff3f3766631bd4e7ee256ca17619fec90e9e6/src/libraries/System.Security.Cryptography.Pkcs/tests/System.Security.Cryptography.Pkcs.Tests.csproj#L4

**Comment by vcsjones** [comment]
_Fancy_.

**Pull request merged**
