### PR TITLE
Add 2 more areas to area-owners

### PR DESCRIPTION
**Pull request by danmoseley**
@jeffschwMSFT there are several issues with area-ILVerification. Are these the correct owners? 

@marek-safar who are owners/lead for area-Interop-mono

### CODE REVIEW

**Comment by jeffschwMSFT** [comment]
@JulieLeeMSFT for ilverification

**Comment by marek-safar** [comment]
@danmosemsft added

**Comment by danmosemsft** [comment]
@JulieLeeMSFT ?

**Comment by danmosemsft** [comment]
How amusing, now I've done the bad rebase trick.

**Comment by danmosemsft** [comment]
@jeffschwMSFT was that a question for Julie, or just a comment - assuming the latter can you please signoff :)

**Review by jeffschwMSFT — APPROVED** [review]

**Pull request merged**
