### PR TITLE
Add stress mode for arm/arm64 function fragment splitting

### PR DESCRIPTION
**Pull request by BruceForstall**
Set JitSplitFunctionSize to either 4 or 200 under new STRESS_UNWIND mode.

### CODE REVIEW

**Comment by BruceForstall** [comment]
Out of disk space errors. Try again.

**Comment by BruceForstall** [comment]
jitstress failure is in Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.sh: https://github.com/dotnet/runtime/issues/92236

replay failure looks like infra (and in any case not arm/arm64)?
```
C:\h\w\A5450979\w\9B6908B2\e>C:\python3\python.exe C:\h\w\A5450979\p\superpmi_replay.py -jit_directory C:\h\w\A5450979\p -arch x64 -platform linux -partition 3 -partition_count 3 -log_directory C:\h\w\A5450979\w\9B6908B2\uploads 
['linux-x64-3' END OF WORK ITEM LOG: Command timed out, and was killed]
```

**Comment by BruceForstall** [comment]
@kunalspathak PTAL
cc @dotnet/jit-contrib

**Review by kunalspathak — APPROVED** [review]
I am assuming this is added to catch issues that usually was just showing up in Antigen? Also, don't think we need to update any pipeline with this new stress mode, right? It gets enabled automatically.

**Comment by BruceForstall** [comment]
> I am assuming this is added to catch issues that usually was just showing up in Antigen? Also, don't think we need to update any pipeline with this new stress mode, right? It gets enabled automatically.

Yes in both cases.

I had intended to add this stress mode many years ago when fragments were introduced, but never did. (There might be an issue somewhere but I couldn't find it.)

**Pull request merged**
