### PR TITLE
Fix instrumentation

### PR DESCRIPTION
**Pull request by clamp03**
- MPGO is not working because of invalid firstSchemaIndex.
- Make ScratchFirstBB by EnsureFirstBBisScratch
  Build FirstBB for valid schema index.
  Then Add helperCallNode to the ScratchFirstBB.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@clamp03 is the issue you're seeing is that prejit instrumentation fails when the first bb is scratch?

If so, I would suggest a different fix.

During the block instrumentation step we should simply remember the schema index for the block at IL offset 0, and then use that index during entry instrumentation. I can code this up if you like.

**Comment by clamp03** [comment]
@AndyAyersMS 
I have two problems.
One is what you commented. "Prejit Insturmentation fails when the first bb is scratch"
The other is an assertion in below fgDebugCheckBBlist. In my guess, it is because helperCallNode is added to non-scratchfirstbb.
https://github.com/dotnet/runtime/blob/c641d977aef70382cbf967ca648f57cc5ea38c0e/src/coreclr/jit/fgdiagnostic.cpp#L1993-L1996
<br>
Actually, I have another patch that fixes a build error in PREJIT.
If you don't mind, could you please update both? I will push my build error fix soon in this PR.
Thank you.

**Comment by AndyAyersMS** [comment]
> If you don't mind, could you please update both? 

Yes, we should fix this. Are you going to rework your fix for the first issue or do you want me to work on it?

The second fix is simple, just change the last line of `BlockCountInstrumentor::InstrumentMethodEntry` to be
```C++
    m_comp->fgInsertStmtAtEnd(m_comp->fgFirstBB, stmt);
```

**Comment by clamp03** [comment]
@AndyAyersMS Could you work on it?

**Comment by AndyAyersMS** [comment]
> Could you work on it?

Sure. 

I am not sure I understand the extent of the problems you are seeing. It sounds like you are trying to use crossgen1 instrumentation and it is not working. 

Maybe you can open an issue describing the what is going on and we can figure out the right fixes from there?

**Comment by clamp03** [comment]
@AndyAyersMS Thanks. I opened an issue and wrote a comment related to this patch. https://github.com/dotnet/runtime/issues/49108#issuecomment-790422367

**Pull request closed without merging**
