### PR TITLE
Update ActivityUserGuide.md

### PR DESCRIPTION
**Pull request by noahfalk**
Refer activity guide to the official docs

https://github.com/dotnet/docs/pull/23313 is bringing more enhancements shortly

### CODE REVIEW

**Comment by noahfalk** [comment]
cc @tarekgh @sywhang

**Comment by stephentoub** [comment]
> dotnet/docs#23313 is bringing more enhancements shortly

Once that's merged we'll delete this document?

Assuming it'll actually be merged shortly, we could just delete this doc now, no?

**Comment by tarekgh** [comment]
I would suggest deleting this doc and move any missing information to the new document. Keeping that with the new comment in the top will force the reader read this doc while they may don't need to. Also, having one place for the doc would be easier pointing users to.

**Comment by noahfalk** [comment]
> I would suggest deleting this doc and move any missing information to the new document

@tarekgh - Are you volunteering to do the work? : )

**Comment by tarekgh** [comment]
> (Also I still wouldn't propose deleting the doc entirely, but deleting everything other than the link to the new doc would be fine once all useful info had been moved. I didn't volunteer to do that refactoring because I suspect it will take non-trivial effort to do it well and I don't have more time to spend on this task at the moment)

That is fine to keep the doc for now till we move the needed contents to the other place. 

> Are you volunteering to do the work? : )

Not in the current time but I wouldn't mind help in that in the future. I am simply curious why we need to keep the usage of DiagnosticSource with Activity? We need to discourage users from that and move to ActivitySource I guess. 

I am approving this PR and we can look at refactoring in other time.

**Review by tarekgh — APPROVED** [review]

**Review by sywhang — APPROVED** [review]
LGTM

**Comment by noahfalk** [comment]
> I am simply curious why we need to keep the usage of DiagnosticSource with Activity?

While I wouldn't encourage most users to do it, there are still some scenarios that can't be accomplished any other way. We also haven't yet replicated every relevant piece of useful guidance onto the official docs for the people who aren't using DiagnosticSource with Activity. I am making a bet (and perhaps it is a bad bet) that the people who find this doc and choose to keep reading it after seeing the obsoletion warning at best will learn something useful and at worst they'll decide it was a waste of their time to read and forget what they read in it.

**Pull request merged**
