### PR TITLE
Move macOS remote unwinding to libunwind directory

### PR DESCRIPTION
**Pull request by am11**
We were duplicating headers between Windows and macOS remote unwind code. This PR applies upstream patch from https://github.com/libunwind/libunwind/pull/365 and adjusts our local cmake configs to deduplicate the code.

### CODE REVIEW

**Comment by am11** [comment]
cc @janvorli, @AaronRobinsonMSFT, @jkotas
The missing functions on Windows for remote unwind were added to libunwind in https://github.com/libunwind/libunwind/commit/693f30a7c3c4092228de1430e005b435aa7656ce, this PR moves macOS missing functions on the same plan and align file naming.

**Comment by am11** [comment]
wasm failure is unrelated. (#69806?)
@janvorli, PTAL.

**Comment by AaronRobinsonMSFT** [comment]
@am11 I think we are just waiting to see if the upstream changes get taken. I like the clean-up for sure. Any concerns about upstream acceptance?

**Comment by am11** [comment]
@AaronRobinsonMSFT, in the past, we have upstreamed in parallel like this. It is totally reasonable to hold this PR until upstream one is reviewed/merged. There is no rush.

I am planning on upstreaming two remaining items after this:

1. JanV's https://github.com/dotnet/runtime/commit/1b5719c2e3dde393531eaeb5b5cde05dabeef5b8
2. Revive https://github.com/libunwind/libunwind/pull/187 by molding it into pattern used by https://github.com/libunwind/libunwind/pull/299 (manpage, basic test and build options). That will cleanup `src/native/external/libunwind_extras/oop` from our side (among few adjustments for "use system libunwind" case; run-time / version-based check to consume this new API).

**Comment by AaronRobinsonMSFT** [comment]
> It is totally reasonable to hold this PR until upstream one is reviewed/merged

Glad we are on the same page. That is really the only reason I haven't merged this in.

**Review by janvorli — APPROVED** [review]
LGTM, thank you! I am sorry for the big delay, my github account somehow decided that my email is no longer valid and stopped sending me notifications on comments / PR requests and I've missed this one.

**Comment by AaronRobinsonMSFT** [comment]
@am11 Seems like the libunwind changes were merged into main. Let's make sure this is still green and then get it in.

**Comment by am11** [comment]
The changes made in upstream directory `src/native/external/libunwind` in main has no upstream PR/commit at all,  has no mention in `libunwind-version.txt` entry and they are unnecessary changes (do not contribute in build in runtime repo at all). We should revert them to keep things synchronized..

**Comment by am11** [comment]
@AaronRobinsonMSFT, upstream PR is merged now.

**Pull request merged**
