### PR TITLE
Remove the HTTP2 and HTTP3 implementations on browser-wasm.

### PR DESCRIPTION
**Pull request by eerhardt**
This allows for HPackEncoder and QPackEncoder to be trimmed in browser wasm.

Contributes to #44534

.br size of `dotnet new blazorwasm` app:

* **Before**: 2,645,237 bytes
* **After**: 2,644,568 bytes

### CODE REVIEW

**Comment by JamesNK** [comment]
Some of this code is shared with aspnetcore? Will the changes require a reaction in aspnetcore?

**Comment by eerhardt** [comment]
> Will the changes require a reaction in aspnetcore?

I think the only change would be to include the new files in whatever .csproj uses them. For example: `H2StaticTable.Http2.cs`

**Review by marek-safar — APPROVED** [review]

**Review by ManickaP — APPROVED** [review]

**Comment by MattGal** [comment]
> @dotnet/dnceng - can anyone tell what the problem was with the Linux x64 Debug leg? From the log:
> 
> azure.devops.exceptions.AzureDevOpsClientRequestError: Operation returned an invalid status code of 503.
> 
> 2021-05-07 02:39:59,300: INFO: 140378837313344: run(114): main: Main thread exiting
> + export _uploaderExitCode=57

Sure, I can talk to this. You've now taken the changes from https://github.com/dotnet/arcade/pull/7310 , which means that when test results can't be reported to Azure Devops, the work item fails.  The HTTP 503 would, prior to this change, have resulted in incomplete or non-reporting to AzDO , while leaving the work item's exit code as 0 (Since we now coerce both 1 (failed some tests) and 0 (passed all tests) to 0. 

Previously, we were suppressing this problem; when it happens, it enables a change that breaks a test, if it gets lucky while Azure DevOps is having a bad day, to "pass".  This came because before, we'd exit with the same exit code XUnit did when tests failed, but once it was decided by folks that we would turn all the 1s to 0s, this became necessary to prevent ignoring failure.  My preference would be to not coerce the exit codes, but there was some reason this particular behavior was needed for the developer workflow.

**Comment by eerhardt** [comment]
Thanks for the explanation @MattGal. So in summary - we can treat these failures as "flaky infrastructure"?

**Comment by MattGal** [comment]
> Thanks for the explanation @MattGal. So in summary - we can treat these failures as "flaky infrastructure"?

Sure, as long as we're counting this particular flakiness as ADO's :)

**Pull request merged**
