### PR TITLE
Move more pipelines to scheduled rather than rolling

### PR DESCRIPTION
**Pull request by safern**
Follow up for: https://github.com/dotnet/runtime/pull/59884

Setting scheduled for the linker-tests, runtime-staging and coreclr outerloop.

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Review by BruceForstall — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]

**Review by eerhardt — APPROVED** [review]

**Review by lewing — APPROVED** [review]

**Review by danmoseley — APPROVED** [review]
LGTM (if ok with @BruceForstall )

**Comment by steveisok** [comment]
> @steveisok the build stage of 'Build iOS arm Release AllSubsets_Mono' was still running after 2 hours. Looking at the log it just seems generally super slow, but there were some particularly slow parts eg
> 
> ```
> 2021-10-07T00:12:46.9144650Z   [ 98%] Building C object mono/mini/CMakeFiles/monosgen-objects.dir/__/__/version.c.o
> 2021-10-07T00:30:28.7707950Z   [ 98%] Built target monosgen-objects
> ```
> 
> ^^ this took 45 mins.

I suspect when we get a slow mac, all parts become super slow.  I don't believe there's anything that part of the build is doing to cause such a slowdown.

@akoeplinger @directhex what you guys think?

**Comment by danmoseley** [comment]
that's great - thanks @MattGal for all that work! Just curious, do we now have better telemetry or other data source to detect unusually slow machines (not sure how this would be defined/detected given workloads vary). IIRC that made it harder to investigate initially.

**Comment by MattGal** [comment]
> Yeah, all I can think of is "% of times the build times out". Since clearly it's not supposed to. Of course, sometimes that's the compiler hanging or whatnot.
> 
> anyway sounds good.

I think we're on the same page here, but that metric can't work for lots of reasons.  For our stuff, though I assume other companies have similar problems, your builds depend on something external (in this case, on-prem Helix test machines) and may be timing out or just taking longer than normal due to how many other runs are going, an outage in our services, a regression in a test causing all work to hang, AzDO package feeds just being extremely slow/tar-pitted, or many other reasons. 

As such it took a lot of twiddling to even get to the stage where it was clear the "noisy neighbor" issue was causing the problem and not  one of these other reasons.  I do think though that if they could track specific tasks on these pools (say, how long the same repo takes to clone) it could catch this since a machine with a noisy neighbor often has 50+% longer clone times, but this data isn't in the same place as the machines' telemetry.

**Pull request merged**
