### PR TITLE
P/Invoke function returning SafeSocketHandle throws MissingMethodException

### LINKED ISSUE #45633: P/Invoke function returning SafeSocketHandle throws "System.MissingMethodException: .ctor"
### Description

On .NET 5, P/Invoke function returning `SafeSocketHandle` throws "System.MissingMethodException: .ctor". See [MissingSafeSocketHandleCtor.zip](https://github.com/dotnet/runtime/files/5646646/MissingSafeSocketHandleCtor.zip) for a full repro project.

```c#
    public static class Program
    {
        private const int AF_INET = 2;
        private const int SOCK_STREAM = 1;

        public static void Main()
        {
            // System.MissingMethodException: '.ctor'
            // (This returns -1 because we have not initialized WinSock2; that does not matter, though.)
            var sock = socket(AF_INET, SOCK_STREAM, 0);
            sock.Dispose();
        }

        [DllImport("Ws2_32.dll")]
        public static extern SafeSocketHandle socket(int af, int type, int protocol);
    }
```

### Configuration

- .NET SDK 5.0.100
- Windows 10 Pro x64 (20H2, 19042.630)

### Regression?

Yes. Worked on 3.1.404.

### Other information

[The SafeHandle doc](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.safehandle?view=net-5.0#notes-to-implementers) says "You should also provide a parameterless constructor".

A parameterless ctor is defined in the `SafeSocketHandle` [source file](https://github.com/dotnet/runtime/blob/v5.0.0-rtm.20519.4/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SafeSocketHandle.cs#L41) but missing from the released assembly at "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0\System.Net.Sockets.dll".

I do not think this is an intended behavior. I do now know the root cause, though.

Stack traces:

```
Unhandled exception. System.MissingMethodException: .ctor
   at ConsoleAppSafeSocketHandle.WinSock2.socket(Int32 af, Int32 type, Int32 protocol)
   at ConsoleAppSafeSocketHandle.Program.Main()
```

### PR DESCRIPTION
**Pull request by eerhardt**
The ILLinker is trimming the private default constructors of SafeHandle classes if they are not used by the library. Adding an XML descriptor file to preserve the private constructors of these SafeHandles so they can be used in P/Invokes in external code.

Fix #45633

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thank you!

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Review by marek-safar — APPROVED** [review]

**Comment by eerhardt** [comment]
Failure is https://github.com/dotnet/runtime/issues/44657

**Review by stephentoub — COMMENTED** [review]
Thanks.

**Pull request merged**
