### PR TITLE
Cleanup NETCOREAPP ifdef usage in System.Runtime.Tests

### LINKED ISSUE #21827: Clean up if netcoreapp usage in System.Runtime.Tests.
First, this define should also be on for uapaot builds.

Second, it's mostly used now to guard access to the "Enum's with funny backing type" statics (s_boolEnumType and friends.) These should be replaced with something that gates on PlatformDetection.IsReflectionEmitSupported.

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #21827

### CODE REVIEW

**Comment by jkotas** [comment]
I will fix this up to be compatible with platforms that have PNSE reflection.emit.

**Review by safern — APPROVED** [review]

**Comment by jkotas** [comment]
Test failure due to #2209

**Comment by safern** [comment]
I see another failure in some System.Net.Tests
https://helix.dot.net/api/2019-06-17/jobs/bcfc4fd7-5e1f-42fb-9345-c19c1543f48f/workitems/System.Net.Security.Tests/console

**Comment by jkotas** [comment]
Yeah, there is a assorted variety of crashes on both CoreCLR and Mono. I do not see how this PR could have caused it. It is only updating System.Runtime tests...

I think a bad PR got merged sometime today. I am trying to find it...

**Pull request merged**
