### PR TITLE
Remove ProjectGuids from libs projects and update slngen

### PR DESCRIPTION
**Pull request by ViktorHofer**
Based on this comment: https://github.com/dotnet/project-system/issues/6830#issuecomment-782591566

1. First commit removes the ProjectGuids from some libs projecsts
2. Second commit updates slngen as it now produces "more VS compatible" sln files.
3. Third commit invokes src/libraries/slngen.proj which adds NuGet.config files where needed.

### CODE REVIEW

**Review by eiriktsarpalis — APPROVED** [review]
Does this mean my VS will stop modifying .sln files?

:shipit:

**Comment by ViktorHofer** [comment]
> Does this mean my VS will stop modifying .sln files?

Unfortunately not, see this comment: https://github.com/dotnet/project-system/issues/6830#issuecomment-782632945

Also it seems like slngen isn't able to deterministically update solution files as GUIDs are changing. @jeffkl is that intentional?

**Review by Anipik — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Comment by stephentoub** [comment]
@ViktorHofer, can this be merged?

**Comment by ViktorHofer** [comment]
The PR is now ready.

**Pull request merged**
