### PR TITLE
JIT: Always assign edge likelihoods in fgIncorporateProfileData

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Part of #93020. Currently, if profile data isn't available or reliable, the JIT won't assign edge likelihoods. We have the ability to come up with reasonable edge likelihoods using a block's number of successors in profile synthesis, so do so when incorporating profile data.

(This change had a lot of churn locally, and I think we can do this heuristic-driven likelihoods fixup more cheaply, i.e. skip the DFS computation if we can tolerate more naive likelihood guesses, don't compute block weights, etc.).

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
@AndyAyersMS running profile synthesis as-is to set edge likelihoods was prohibitively expensive, so I tweaked `AssignLikelihoods` to only set likelihoods (i.e. skip block weight computations), and to skip the loop edge heuristic for setting `BBJ_COND` likelihoods (as that requires finding loops first). Ignoring `coreclr_tests`, this still seems expensive. We could save a bit more TP by using completely naive edge likelihoods (like `1/NumSucc()`), though I'm not sure how big a difference that would make. With these TP costs in mind, do you think it's worth initializing all edge likelihoods, regardless of the presence or quality of profile data?

**Comment by amanasifkhalid** [comment]
> I think you can do this more cheaply by checking for the AssignLikelihoodsOnly option first and running it and exiting before we build DFS/loops.

I tried that in the last commit, albeit somewhat sloppily: I moved the DFS/loop logic to below the switch statement, and commented out the loop-aware heuristics in `AssignLikelihoodCond` so that we don't need loop info at all to assign likelihoods. This still proves to be a bit expensive for MinOpts TP, though only for a few collections.

By the way, do you know if there's a way to view which contexts in a collection had the largest TP diffs, kind of like what we can do with asmdiffs? I wonder if the largest TP regressions in MinOpts are driven by just a few outliers, considering the relatively low impact in other collections.

**Comment by AndyAyersMS** [comment]
Likely the cost is in all those calls to `fgGetPredForBlock` -- for each block B it needs to search each successor block pred list for the edges from B. And some successor blocks can have a lot of pred edges.

Unfortunately, our edge info representation is currently biased in favor of edge targets and not edge sources. The ultimate fix for this is something like
* double-thread `FlowEdge`s so successor edges can be directly enumerated, 
* (more radical) have the successor blocks be described only by their `FlowEdges` (so a BBJ_COND block, say has two FlowEdges, not two BasicBlocks, to describe what happens next).

**Comment by amanasifkhalid** [comment]
I see... I'm tempted to try out your second option. For that, I'm guessing we'd need to add a new member to `FlowEdge` for the destination block, and then replace `BasicBlock::bbTarget` et al with the successor `FlowEdge*`. Then `BasicBlock::GetTarget()` can return `bbTargetEdge->getDestinationBlock()` (or something like that).

In the meantime, to avoid the `fgGetPredForBlock` overhead, we could try initializing edge likelihoods with these heuristic values when we first create the edges in `fgMakeBasicBlocks`. Let me see if that fixes the TP issue.

**Comment by AndyAyersMS** [comment]
Using `FlowEdge` would be a big change, but feel free to give it a go and see how big.

**Comment by AndyAyersMS** [comment]
Thinking about this some more, if you want to drive it from the target side, then I suppose the simple equally-likely projection is better than nothing.

So say in `fgAddRefPred` when `initializingPreds` is true, you could set the likelihood to something like (1/#source block successors) * flDupCount as a "better than nothing" value.

**Comment by amanasifkhalid** [comment]
Sorry for the pings -- my branch got messed up locally. Gonna close this in lieu of a new PR.

**Comment by jakobbotsch** [comment]
> By the way, do you know if there's a way to view which contexts in a collection had the largest TP diffs, kind of like what we can do with asmdiffs? I wonder if the largest TP regressions in MinOpts are driven by just a few outliers, considering the relatively low impact in other collections.

Currently this requires a somewhat manual process (#85755 is about automatically including examples in the generated report).

To do it manually you can pass `--skip_cleanup` to your `superpmi.py tpdiff` invocation. After that you can look at the .csv file that is saved in the temp folder (look for `Temp Location:` in the SPMI run log file). You can open that in Excel and find the outliers based on the "Base instructions"/"Diff instructions" columns.

**Comment by amanasifkhalid** [comment]
> To do it manually you can pass --skip_cleanup to your superpmi.py tpdiff invocation. After that you can look at the .csv file that is saved in the temp folder (look for Temp Location: in the SPMI run log file). You can open that in Excel and find the outliers based on the "Base instructions"/"Diff instructions" columns.

Thanks for this!

**Pull request closed without merging**
