### PR TITLE
Use 127.0.0.1 instead of localhost in Socks proxy tests

### LINKED ISSUE #51942: System.Net.Http innerloop tests have gotten much slower
These used to take ~15s on my machine; now it's >100s.

### PR DESCRIPTION
**Pull request by MihaZupan**
Fixes #51942

### CODE REVIEW

**Comment by wfurt** [comment]
I would think this does not matter unless name resolution is badly broken. Note that on some systems "localhost" would also resolve to `::1` and there could be timeout connecting to IPv6.

**Comment by MihaZupan** [comment]
I assume it's because the loopback server is listening on `InterNetwork` - we could alternatively change the loopback to a dual-mode socket.

**Comment by MihaZupan** [comment]
Essentially #31085

**Comment by wfurt** [comment]
I'm find with the change as I would think it does not change the actual behavior. It may be _nice_ to keep _some_ spots with  DnsEndPoint to make sure we cover it as well. Passing IP literal string may be actually sufficient.

**Comment by geoffkizer** [comment]
Thanks for figuring this out!

**Review by geoffkizer — APPROVED** [review]

**Pull request merged**
