### PR TITLE
Update life of data node for simd12

### LINKED ISSUE #85899: Test failure JIT\\SIMD\\Matrix4x4_ro\\Matrix4x4_ro.cmd
**Failed in:** [runtime-coreclr jitstress-isas-x86 20230506.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=264782&view=ms.vss-test-web.build-test-results-tab&runId=5208054&resultId=111759&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitstress_isas_nohwintrinsic @ Windows.10.Amd64.Open
    - JIT\\SIMD\\Matrix4x4_ro\\Matrix4x4_ro.cmd
    - JIT\\SIMD\\Matrix4x4_r\\Matrix4x4_r.cmd
coreclr windows x86 Checked jitstress_isas_x86_nohwintrinsic @ Windows.10.Amd64.Open
    - JIT\\SIMD\\Matrix4x4_r\\Matrix4x4_r.cmd
    - JIT\\SIMD\\Matrix4x4_ro\\Matrix4x4_ro.cmd
coreclr windows x86 Checked jitstress_isas_x86_nosse2 @ Windows.10.Amd64.Open
    - JIT\\SIMD\\Matrix4x4_r\\Matrix4x4_r.cmd
    - JIT\\SIMD\\Matrix4x4_ro\\Matrix4x4_ro.cmd
coreclr windows x86 Checked jitstress_isas_x86_nosse @ Windows.10.Amd64.Open
    - JIT\\SIMD\\Matrix4x4_r\\Matrix4x4_r.cmd
    - JIT\\SIMD\\Matrix4x4_ro\\Matrix4x4_ro.cmd
```

**Error message:**
```
 
Assert failure(PID 8620 [0x000021ac], Thread: 7072 [0x1ba0]): Assertion failed &#39;!&quot;Found mismatched live reg var(s) after block&quot;&#39; in &#39;System.Numerics.Matrix4x4:CreateTranslation(System.Numerics.Vector3):System.Numerics.Matrix4x4&#39; during &#39;Generate code&#39; (IL size 21; hash 0x2ed04f7c; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\codegenlinear.cpp Line: 595
    Image: C:\h\w\B1770933\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\B1770933\w\B9C10A3E\uploads\Reports\JIT.SIMD\Matrix4x4_ro\Matrix4x4_ro.output.txt
Raw output:
BEGIN EXECUTION
 &quot;C:\h\w\B1770933\p\corerun.exe&quot; -p &quot;System.Reflection.Metadata.MetadataUpdater.IsSupported=false&quot; -p &quot;System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true&quot;  Matrix4x4_ro.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 5/6/2023 9:31:22 PM
Processing C:\cores\corerun.exe.8620.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c &quot;$&lt;C:\h\w\B1770933\t\tmpsuvtw4.tmp&quot; -z &quot;C:\cores\corerun.exe.8620.dmp&quot;
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.8620.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\B1770933\p\PDB
Symbol search path is: C:\h\w\B1770933\p\PDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.5125 (rs1_release.220429-1732)
Machine Name:
Debug session time: Sat May  6 21:31:29.000 2023 (UTC + 0:00)
System Uptime: 0 days 1:32:47.883
Process Uptime: 0 days 0:00:07.000
............................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(21ac.1ba0): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
eax=02d79208 ebx=00000000 ecx=00000000 edx=00000000 esi=02d791b8 edi=02d79208
eip=7078bd6e esp=02d794ec ebp=02d7a584 iopl=0         nv up ei pl nz ac pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000216
coreclr!FailFastOnAssert+0x21:
7078bd6e 5e              pop     esi
0:000&gt; cdb: Reading initial command &#39;$&lt;C:\h\w\B1770933\t\tmpsuvtw4.tmp&#39;
0:000&gt; .load C:\Users\runner\.dotnet\sos\sos.dll
0:000&gt; ~*k

.  0  Id: 21ac.1ba0 Suspend: 0 Teb: 02bbd000 Unfrozen
ChildEBP RetAddr  
02d794f8 7078ca52 coreclr!FailFastOnAssert+0x21
02d7a584 703771d8 coreclr!_DbgBreakCheck+0x331
*** WARNING: Unable to verify checksum for clrjit.dll
02d7a5ec 6ef97d6a coreclr!CEEInfo::doAssert+0x68
02d7c61c 6ef7c6e4 clrjit!assertAbort+0xd8
02d7c714 6ef76805 clrjit!CodeGen::genCodeForBBlist+0xb75
02d7c728 6ef71ad4 clrjit!CodeGen::genGenerateMachineCode+0x365
02d7c734 6f07d608 clrjit!CodeGenPhase::DoPhase+0x14
02d7c768 6ef76441 clrjit!Phase::Run+0x38
(Inline) -------- clrjit!DoPhase+0x3d
02d7c794 6ef83fac clrjit!CodeGen::genGenerateCode+0x71
02d7c9c8 6ef8546f clrjit!Compiler::compCompile+0xa01
02d7ca34 6ef84870 clrjit!Compiler::compCompileHelper+0x6bd
(Inline) -------- clrjit!Compiler::compCompile::__l170::__Body::Run+0x15
02d7cb18 6ef82ca5 clrjit!Compiler::compCompile+0x6df
```

**Stack trace:**
```
    at JIT_SIMD._Matrix4x4_ro_Matrix4x4_ro_._Matrix4x4_ro_Matrix4x4_ro_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by kunalspathak**
I see that for simd12 node, `[000174]` (addr node) is marked as contained, but when we generate code for it, we do not update the life of `[000030]`. Today, we do that only if `addr` is not contained.

```
N105 (  3,  2) [000030] ----------z                   t30 =    LCL_VAR   simd12<System.Numerics.Vector3> V01 arg0         u:1 mm5 (last use) REG mm5 $c0
N107 (  3,  3) [000174] -c---------                  t174 =    LCL_ADDR  byref  V16 tmp13        [+0] NA REG NA $200
                                                            /--*  t174   byref  
                                                            +--*  t30    simd12 
N109 ( 10,  8) [000195] nA--G------                         *  STOREIND  simd12 (copy) REG NA $VN.Void
```

Fixes: https://github.com/dotnet/runtime/issues/85899

### CODE REVIEW

**Comment by kunalspathak** [comment]
@SingleAccretion - can you review this to make sure I didn't miss anything?

**Comment by SingleAccretion** [comment]
I think we should rather move the call to 'genConsumeReg' that's below to before the 'if'.

**Comment by kunalspathak** [comment]
> I think we should rather move the call to 'genConsumeReg' that's below to before the 'if'.

I thought about that, but was not sure if that is valid (to consume the reg) given the `addr` is contained.

**Comment by SingleAccretion** [comment]
I do not see any issues with that, given that the data itself is not contained.

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Review by SingleAccretion — APPROVED** [review]

**Review by jakobbotsch — APPROVED** [review]

**Comment by tannergooding** [comment]
Not sure this is the "right" fix. Wouldn't the correct change be to update `genEmitStoreLclTypeSimd12` to have `genConsumeReg(data)`?

Otherwise any other callers could also be doing things incorrectly.

**Comment by tannergooding** [comment]
If not, then we should probably have a comment in `genEmitStoreclTypeSimd12` covering that that the caller is expected to call `genConsumeReg`, `genProduceReg`, `genUpdateLife`, etc

**Comment by kunalspathak** [comment]
> Not sure this is the "right" fix. Wouldn't the correct change be to update `genEmitStoreLclTypeSimd12` to have `genConsumeReg(data)`?
> 
> Otherwise any other callers could also be doing things incorrectly.

Currently all the liveness updates happens outside of this method and probably e can consider fixing it, but not in this PR. 

> then we should probably have a comment in

I can do it in my different PR to skip running CI for the comment?

**Review by tannergooding — APPROVED** [review]

**Comment by kunalspathak** [comment]
> I can do it in my different PR to skip running CI for the comment?

https://github.com/dotnet/runtime/pull/86016

**Pull request merged**
