### PR TITLE
update data annotation error message

### LINKED ISSUE #83642: The data annotation error message not in the same style
For example, some are `the {0} field` while some are `the field {0}`

image

Maybe it's better to align the style?

### PR DESCRIPTION
**Pull request by WeihanLi**
fixes #83642

### CODE REVIEW

**Review by eiriktsarpalis — COMMENTED** [review]
LGTM, thanks.

**Review by eiriktsarpalis — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
The tests failures are real.  There are apparently tests validating the exact error message that was there before, e.g.
```
      Did not find: DataAnnotation validation failed for 'AnnotatedOptions' members: 'Required' with the error: 'The Required field is required.'.
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/OptionsBuilderTest.cs(402,0): at Microsoft.Extensions.Options.Tests.OptionsBuilderTest.ValidateFailure[AnnotatedOptions](OptionsValidationException e, String name, Int32 count, String[] errorsToMatch)
        /_/src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/OptionsBuilderTest.cs(744,0): at Microsoft.Extensions.Options.Tests.OptionsBuilderTest.ValidateOnStart_CallValidateOnStartFirst_ValidatesFailuresCorrectly()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(30,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(59,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by WeihanLi** [comment]
Seemed some error messages in the test case are hard-coded

https://github.com/dotnet/runtime/blob/2d90e251f9f6c4509de6641a6bc39ac7a35cc032/src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/OptionsBuilderTest.cs#L635

https://github.com/dotnet/runtime/blob/2d90e251f9f6c4509de6641a6bc39ac7a35cc032/src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/OptionsBuilderTest.cs#L661

https://github.com/dotnet/runtime/blob/2d90e251f9f6c4509de6641a6bc39ac7a35cc032/src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/OptionsBuilderTest.cs#L688

https://github.com/dotnet/runtime/blob/2d90e251f9f6c4509de6641a6bc39ac7a35cc032/src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/OptionsBuilderTest.cs#L716

https://github.com/dotnet/runtime/blob/2d90e251f9f6c4509de6641a6bc39ac7a35cc032/src/libraries/Microsoft.Extensions.Options/tests/Microsoft.Extensions.Options.Tests/OptionsBuilderTest.cs#L745

Should I also update the test message or update the test case to use the message format from the data annotation?

**Comment by eiriktsarpalis** [comment]
We can always update the tests, but at this point I'm concerned we could break users who rely on the current message format. @jeffhandley do you think the change is worth the added risk?

**Comment by stephentoub** [comment]
(FWIW, we haven't previously considered changing exception message text to be a breaking change.)

**Comment by eiriktsarpalis** [comment]
Given that the motivation for making the change is consistency (and not fixing obvious grammatical errors), I'm not sure it's worth 1) the cost of documenting this as a breaking change and 2) the risk of breaking users that unfortunately depend on the current formatting.

**Comment by ajcvickers** [comment]
@jeffhandley I think the value of this change is low, since people who really care what the message says should not just be exposing the default message to users. With regards the break, I think from a principled perspective, this kind of change should be fine. From a pragmatic perspective, I suspect it will at least break customer tests, just like it did ours. It may even break tests in other repos we have--for example, ASP.NET Core. I think it's less likely to break real customer experiences, but there will always be someone how there parsing it...

**Comment by danmoseley** [comment]
> FWIW, we haven't previously considered

Indeed... are these messages particularly likely to be breaking if changed? Or are we establishing precedent that changing arbitrary exception messages needs a sufficiently good reason? We've generally fixed tests where they depended on the exact string (for example to make them look for a value within it) so this would be a change of policy. Perhaps validation messages are different but that's not clear to me.

**Comment by jeffhandley** [comment]
Validation messages _are_ different because they're the rare (only?) end-user-facing messages we produce.

I appreciate @ajcvickers' comment about the value being low and the potential cost/effect being high. @WeihanLi, I agree with your action of closing the PR without merging it. Thank you for the contribution here nonetheless though; it's helpful that we explored this and decided _not_ to make the change.

**Comment by danmoseley** [comment]
> Validation messages are different because they're the rare (only?) end-user-facing messages we produce.

ah - gotcha. I hope we can retain the freedom to improve the others.

**Pull request closed without merging**
