### PR TITLE
[QUIC] - Initial managed implementation in C#

### PR DESCRIPTION
**Pull request by rzikm**
This PR adds initial version of almost C#-only QUIC implementation as an alternative to MsQuic based implementation. The work originated as my Master Thesis.

## Supported QUIC Protocol Features

This implementation is highly in WIP state. The features are at the draft-27 version. The goal was to obtain a minimal working
implementation able to reliably transmit data between client and server. This can be used to evaluate the viability of purely C# implementation for production releases. Most transport-unrelated features are
left unimplemented.

Currently implemented:

- Basic connection establishment
- Encryption
- TLS integration backed by [modified OpenSSL](https://github.com/openssl/openssl/pull/8797)
- Sending data, flow control, loss recovery, congestion control
- Stream/Connection termination
- Coalescing packets into a single UDP datagram

## Unsupported QUIC Protocol Features

A list of highlights of unimplemented protocol features follows:

- Connection migration
- Stateless reset
- 0-RTT data
- Server Preferred Address
- Version Negotiation
- Address Validation
- Encryption key updates

## OpenSSL integration

To function correctly, the implementation requires a custom branch of OpenSSL from Akamai
https://github.com/akamai/openssl/tree/OpenSSL_1_1_1g-quic. The implementation tries to detect that
a QUIC-supporting OpenSSL is present in the path. If not, then a mock implementation is used instead.

The mock implementation can be used for trying the implementation locally, but interoperation with other
QUIC implementations is, of course, possible only with the OpenSSL-based TLS. If you want to make sure your
implementation runs with OpenSSL, define the `DOTNETQUIC_OPENSSL` environment variable. This will
cause the implementation to throw if proper OpenSSL version cannot be loaded.

## Tracing and qvis

The implementation can produce traces that can be consumed by https://qvis.edm.uhasselt.be
visualizer. To collect traces, define `DOTNETQUIC_TRACE` environment variable to something nonempty. The traces will be
saved in the working directory in a file named _[timestamp]-[server|client].qvis_.

## Disabling encryption

Regardless of TLS used, you can circumvent encryption by defining the `DOTNETQUIC_NOENCRYPT` environment variable to something nonempty.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43948) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43948) before we can accept your contribution.<br/><br/>:x: rzikm [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43948)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=43948) it.</sub>

**Comment by rzikm** [comment]
Tagging @karelz and @geoffkizer. Please tag anyone else who may find this PR of interest

**Comment by wfurt** [comment]
This may be candidate for https://github.com/dotnet/runtimelab if it feels too green.

**Comment by geoffkizer** [comment]
Per discussion, let's get this into runtimelabs first.

@rzikm Can you post this PR to https://github.com/dotnet/runtimelab/tree/feature/ManagedQuic?

**Comment by rzikm** [comment]
rebased and created separate PR to runtimelabs. I couldn't reuse this PR so I had to create new one.

https://github.com/dotnet/runtimelab/pull/293

Closing this one.

**Pull request closed without merging**
