### PR TITLE
[release/6.0] Add missing Oracle RIDs

### PR DESCRIPTION
**Pull request by Mr-Tao**
This change adds previously missing RIDs for OL releases 7, 8 and 9 and respective RHEL counterparts.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=66684) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=66684) before we can accept your contribution.<br/><br/>:x: Mr-Tao [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=66684)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=66684) it.</sub>

**Comment by agocke** [comment]
This would need to go through `main`. Also, what's the justification for adding more RIDs?

**Comment by Mr-Tao** [comment]
> This would need to go through `main`.

Sure can do. Did I miss any docs? How is this different from, e.g.  #65392, #64304 or #66225?

> Also, what's the justification for adding more RIDs?

There already are RIDs for OL 7 and 8 in the graph. This update is just adding current versions. Not to mention the addition of new RIDs is happening all the time: see #61304 or #62184, to list a few.

**Comment by akoeplinger** [comment]
@carlossanlop do you know what the status of this one is?

**Comment by wfurt** [comment]
we should resolve https://github.com/dotnet/runtime/pull/66783 first IMHO @akoeplinger e.g. get it in main and than we can worry about back port.

**Comment by carlossanlop** [comment]
The `main` PR had to be closed due to inactivity. We can reopen this after the `main` one gets reopened and merged. https://github.com/dotnet/runtime/pull/66783

**Pull request closed without merging**
