### PR TITLE
add AcceptAsync cancellation overloads

### LINKED ISSUE #40289: WaitForConnectionAsync does not respond to cancellation
The [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.pipes.namedpipeserverstream.waitforconnectionasync?view=netcore-3.1#System_IO_Pipes_NamedPipeServerStream_WaitForConnectionAsync_System_Threading_CancellationToken_) for `NamedPipeServerStream.WaitForConnectionAsync(CancellationToken)` claims the following:

> Cancellation requests using the cancellation token will only work if the NamedPipeServerStream object was created with a pipe option value of PipeOptions.Asynchronous or if the cancellation occurs before the WaitForConnectionAsync method is called.

This does not appear to be true though when .NET Core is run in Unix environments. The following code snippet will hang waiting for the `WaitForConnectionAsync` method to complete on Unix. It does not seem to respect the cancellation request. The same code running on Windows though will properly cancel the `WaitForConnectionAsync`. 

```cs
using System;
using System.IO.Pipes;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static async Task Main(string[] args)
    {
        using var mre = new ManualResetEvent(initialState: false);
        var pipeName = Guid.NewGuid().ToString();
        var cts = new CancellationTokenSource();
        var task = Task.Run(async () =>
        {
            try
            {
                using var server = new NamedPipeServerStream(
                    pipeName,
                    PipeDirection.InOut,
                    maxNumberOfServerInstances: 10,
                    PipeTransmissionMode.Byte,
                    PipeOptions.Asynchronous);
                var waitTask = server.WaitForConnectionAsync(cts.Token);

                // The sync portion of WaitForConnectionAsync is the only part that 
                // considers the CancellationToken on Unix. Signal other thread that
                // it's time to cancel.
                mre.Set();
                await waitTask;
                Console.WriteLine($"After await waitTask");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception thrown {ex.Message}");
            }
        });

        mre.WaitOne();
        cts.Cancel();
        Console.WriteLine("Token cancelled");
        await task;
        Console.WriteLine("await task complete");
    }
}
```

Looking at the `WaitForConnectionAsync` [implementation ](https://github.com/dotnet/runtime/blob/master/src/libraries/System.IO.Pipes/src/System/IO/Pipes/NamedPipeServerStream.Unix.cs#L68) on Unix it seems that the cancellation is simply not considered after a quick check at the start of the method. 

```cs
        public Task WaitForConnectionAsync(CancellationToken cancellationToken)
        {
            CheckConnectOperationsServer();
            if (State == PipeState.Connected)
            {
                throw new InvalidOperationException(SR.InvalidOperation_PipeAlreadyConnected);
            }

            return cancellationToken.IsCancellationRequested ?
                Task.FromCanceled(cancellationToken) :
                WaitForConnectionAsyncCore();

            async Task WaitForConnectionAsyncCore() =>
               HandleAcceptedSocket(await _instance!.ListeningSocket.AcceptAsync().ConfigureAwait(false));
        }
```

Is the documentation simply out of date here and should be using **and** not **or**?

### PR DESCRIPTION
**Pull request by geoffkizer**
Contributes to #33418 
Fixes #40289

Add overloads to Socket.AcceptAsync that take a CancellationToken, and wire up support for cancellation.

AcceptAsync now uses the ValueTask-based mapping to SocketAsyncEventArgs (it previously used the Task-based mapping).

Optimize AcceptAsync for synchronous completion by deferring pinning of the accept buffer.

Minor SendFileAsync test cleanup from recent SendFileAsync PR.

Add similar overloads for TcpListener.

Fix the Unix implementation of named pipe servers to wire up cancellation via this new overload.

### CODE REVIEW

**Review by stephentoub — COMMENTED** [review]
Nice.  Generally looks good.

I was going to ask that you also fix https://github.com/dotnet/runtime/issues/40289, but I see that CI flagged it anyway due to there now being a CancellationToken-based overload, and our analyzer that flags not correctly passing the token around kicking in.

**Comment by geoffkizer** [comment]
#40289 is now fixed, including enabling the relevant test on Unix.

I also added the corresponding TcpListener overloads.

PTAL.

**Review by stephentoub — APPROVED** [review]
Assuming the test failures are all unrelated, LGTM.

**Pull request merged**
