### PR TITLE
[mono][interp] Fix short branches

### LINKED ISSUE #57363: [interp] Short branch offset can overflow with very large methods
The interpreter makes assumptions in some cases that a particular branch is short, when in reality the target basic block can be at an offset greater than the 32k limit. The code generation for branches should be refactored so there is no reference of short/long branches during initial compilation and, during actual generation of the compacted code we emit either long or short branches depending on the real native offset.

This issue is reproducible with System.CodeDom.Tests suite

### PR DESCRIPTION
**Pull request by BrzVlad**
In interp, long branches have 4 byte signed offset while short branches have a 2 byte signed offset. Ideally we would want to always emit short branches if possible due to improved performance. The problem is that we emit a short or long branch early in the codegen process, there is no way to know whether a branch is long or short at that time and no further computations were done later to determine whether the branch is really long or short.  Before this commit we arbitrarily decided that all branches in methods with IL size of less than 25000 are short and, in some cases, completely ignored that long branches actually happen in practice.

This commit makes it such that we always emit long opcodes at the beginning of the codegen process, also serving as a simplification since optimizations operating on IR code don't need to care about both short and long versions of branches. Later on, we will end up converting all these long branches to short branches when emitting the final method code. We achieve this by doing a quick preliminary code iteration and computing conservative native offsets (assuming all branches are long). Since the final code will be equal in size or smaller, we have the guarantee that if a branch is short between the conservative offsets, it will surely be short also in the final code. With this approach we guarantee correctness and we can fail to shorten only a negligible amount of branches.

Since the super instruction pass generates some branching instructions that are supported only for the short version, we need to run a computation of conservative offsets beforehand. These iterations can later be optimized out, by prioritizing general compilation time over marginal improvements in code quality for very rare gigantic methods.

Fixes https://github.com/dotnet/runtime/issues/57363

### CODE REVIEW

**Comment by marek-safar** [comment]
@vargaz plese review

**Comment by BrzVlad** [comment]
wasm failures are fixed by https://github.com/dotnet/runtime/pull/59225

**Review by vargaz — APPROVED** [review]

**Comment by thaystg** [comment]
@BrzVlad Can we backport to .net6 this PR? We have this issue related to it: https://github.com/dotnet/runtime/issues/63581

**Pull request merged**
