### PR TITLE
Revert "[mono] Fix a few corner case overflow operations"

### PR DESCRIPTION
**Pull request by SamMonoRT**
Reverts dotnet/runtime#57407

### CODE REVIEW

**Comment by SamMonoRT** [comment]
@lewing @lambdageek - can you approve this -- Vlad's original PR exposed a wasm issue

**Review by lambdageek — APPROVED** [review]

**Review by imhameed — APPROVED** [review]

**Review by lewing — APPROVED** [review]
What is the emscripten bug we are hitting?

**Comment by SamMonoRT** [comment]
> What is the emscripten bug we are hitting?

Vlad has more details, and he was going to send email. He is on vacation this week, so possibly not going to happen until next week.

**Comment by BrzVlad** [comment]
Both in that PR and in parts of mono we rely on some undefined behavior when converting float to int. On wasm that undefined behavior resulted in some counter intuitive side effects, which turns out are allowed to happen. I will just refactor the code instead, so we don't run into undefined behavior at all in the first place.

**Pull request merged**
