### PR TITLE
Add Ubuntu 22.10 kinetic kudu RIDs for .NET 6

### PR DESCRIPTION
**Pull request by dviererbe**
Related to https://github.com/dotnet/runtime/issues/84974

### CODE REVIEW

**Comment by dviererbe** [comment]
@dotnet-policy-service agree company="Canonical"

**Review by carlossanlop — CHANGES_REQUESTED** [review]
@dviererbe friendly reminder that we only accept servicing fixes in the release/6.0-staging and release/7.0-staging. The release/6.0 and release/7.0 branches are reserved/restricted. I retargeted your PR to the correct branch.

As indicated in the 7.0 PR comments, we need this change merged to main first. Can you please create it so that we can accept this one and the 7.0? cc @wfurt

**Review by carlossanlop — APPROVED** [review]
Thanks for submitting the main change.

**Comment by carlossanlop** [comment]
@dviererbe FYI I added a missing change in the Microsoft.NETCore.Platforms.csproj file that ensures it gets built for servicing.

**Review by wfurt — APPROVED** [review]
LGTM

**Pull request merged**
