### PR TITLE
Write error events for service errors

### PR DESCRIPTION
**Pull request by nxtn**
Matches the .NET FX behavior.

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
I'm surprised this bug existed for so long, but I think yo'ure correct.

Suggestion: ideally callers don't pass a bare boolean, as it's harder to read. Consider updating the callers to name the parameter, eg.,

`WriteLogEntry(SR.Format(SR.StartFailed, new Win32Exception().Message), error: true);`

**Comment by danmosemsft** [comment]
@billwert @DrewScoggins the perf job failed on Windows:
```
2020/07/22 09:41:12][INFO] Downloading https://dot.net/v1/dotnet-install.ps1
Traceback (most recent call last):
  File "C:\python3.7.0\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\python3.7.0\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\python3.7.0\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\python3.7.0\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\python3.7.0\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\python3.7.0\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\python3.7.0\lib\http\client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "C:\python3.7.0\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\python3.7.0\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "C:\python3.7.0\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\h\w\A0B308C9\p\performance\scripts\benchmarks_ci.py", line 264, in <module>
    __main(sys.argv[1:])
  File "C:\h\w\A0B308C9\p\performance\scripts\benchmarks_ci.py", line 208, in __main
    verbose=verbose
  File "C:\h\w\A0B308C9\p\performance\scripts\benchmarks_ci.py", line 75, in init_tools
    verbose=verbose,
  File "C:\h\w\A0B308C9\p\performance\scripts\dotnet.py", line 686, in install
    urlretrieve(dotnetInstallScriptUrl, dotnetInstallScriptPath)
  File "C:\python3.7.0\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\python3.7.0\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\python3.7.0\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\python3.7.0\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\python3.7.0\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\python3.7.0\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\python3.7.0\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

**Comment by danmosemsft** [comment]
@dsplaisted who owns https://dot.net/v1/dotnet-install.ps1? It's dead.

**Comment by danmosemsft** [comment]
> Unrelated: I think it still makes sense to add an exception filter since it also throws ArgumentException.

Can you clarify?

**Comment by DrewScoggins** [comment]
Looks like a transient download error somewhere we don't have a retry. I filed https://github.com/dotnet/performance/issues/1405 to track fixing this.

**Comment by dsplaisted** [comment]
> @dsplaisted who owns https://dot.net/v1/dotnet-install.ps1? It's dead.

@donJoseLuis

**Comment by NextTurn** [comment]
> Consider updating the callers to name the parameter

Or simply specify `EventLogEntryType` as the parameter?

**Comment by danmosemsft** [comment]
> Or simply specify an EventLogEntryType as the parameter

Yes that works

**Comment by NextTurn** [comment]
> 
> 
> > Unrelated: I think it still makes sense to add an exception filter since it also throws ArgumentException.
> 
> Can you clarify?

Never mind. I think it's OK.

**Review by danmoseley — APPROVED** [review]

**Comment by danmosemsft** [comment]
CI is green, there's a known bug the badges didn't update.

**Pull request merged**
