### PR TITLE
Disable 2 FSW tests failing only on macOS 12

### PR DESCRIPTION
**Pull request by danmoseley**
Relates to https://github.com/dotnet/runtime/issues/70164

### CODE REVIEW

**Comment by danmoseley** [comment]
I don't have a mac, so I can't verify that Version.Major = 12 for Monterey, but one would assume so.

**Review by jozkee — APPROVED** [review]

**Comment by Jozkee** [comment]
> I don't have a mac, so I can't verify that Version.Major = 12 for Monterey, but one would assume so.

I can see `Environment.OSVersion.Version` on my macbook printing 12.4.0.

**Comment by danmoseley** [comment]
Hmm, I thought this would count as a skip not a failure
```
    System.IO.Tests.Directory_Move_Tests.Directory_Move_Multiple_From_Watched_To_Unwatched_Mac(filesCount: 1) [FAIL]
      Microsoft.DotNet.XUnitExtensions.SkipTestException : Unreliable on Monterey
      Stack Trace:
        /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.Directory.Move.cs(37,0): at System.IO.Tests.Directory_Move_Tests.Directory_Move_Multiple_From_Watched_To_Unwatched_Mac(Int32 filesCount)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(69,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by danmoseley** [comment]
@dotnet/dnceng  trying to view the artifacts of the failing lane gives "
404 Unable to process request"

**Comment by andriipatsula** [comment]
Hello @danmoseley . I opened `Checks`\"Non-Deterministic Test Failures Detected"\"Artifacts" and it opens. Could you please clarify more details?

**Pull request merged**
