### PR TITLE
Update linux musl arm32 helix image to Alpine 3.17

### PR DESCRIPTION
**Pull request by lbussell**
Alpine 3.16 builds are failing in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/966 and there is not a known/easy solution. This PR updates to Alpine 3.17 so that we can just delete the older Alpine images.

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]
Since .NET 9 will not support Alpine 3.16 at release time, LGTM!

**Review by epananth — COMMENTED** [review]
LGTM

**Review by epananth — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]
We might still have to service those for 8.0 and below. It ends support in May though so we might just get away with it.

**Review by mthalman — APPROVED** [review]

**Review by wfurt — APPROVED** [review]

**Comment by hoyosjs** [comment]
I don't have a good grasp of this one at the moment, I see a crash within libmsquic but not sure why (cc: @wfurt )

**Comment by CarnaViire** [comment]
@lbussell @hoyosjs I've put up a PR to disable QUIC tests as we can't use the workaround on 3.17 (https://github.com/dotnet/runtime/pull/99020); hopefully that should unblock you once it's merged.

cc @ManickaP @wfurt

**Pull request merged**
