### PR TITLE
Fix GDI handle leak in Icon.DrawImage

### LINKED ISSUE #46789: [NET 5.0] GDI resource leak in Graphics.DrawIcon method
* .NET Core Version: 
NET 5.0.1

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
Hello, 
I've encountered the GDI resource leak in my WinForms application after I targeted it to NET 5.0.
I've found in debugger the leak is in the method Graphics.DrawIcon.
After maximum GDI objects count is reached, the application crashes with System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
I use the method Graphics.DrawIcon in DataGridView.CellPainting, therefore my users get the GDI+ exception very soon, as they scroll my DataGridView.

**Expected behavior:**
There is no memory/GDI resource leak if the application is targeted to NET Core 3.1 or net472. 

**Minimal repro:**
I've added the file with solution WindowsFormsApp1GdiLeak.zip, which you can use to reproduce the bug easily.
1. Open Windows Task Manager
2. Go to Details Tab
3. Open context menu on Headers an click Select columns
4. Add "GDI objects" column
5. Open solution WindowsFormsAppWeb1.sln
6. Set the break point on the loop 
for (int i = 0; i < 5000; i++)
            {
                g.DrawIcon(icon, 100, 100); // GDI leak here
            }
7. Run the application and check GDI objects in Task Manager before and after the loop.
8. Re-target the project to NET Core 3.1, run again and check GDI objects again.

[WindowsFormsApp1GdiLeak.zip](https://github.com/dotnet/winforms/files/5791375/WindowsFormsApp1GdiLeak.zip)

### PR DESCRIPTION
**Pull request by safern**
Fixes: https://github.com/dotnet/runtime/issues/46789

This was a regression from 3.1 -> 5.0 caused in: https://github.com/dotnet/corefx/commit/f807df691a3007cea9c7aa169f18be4cd9540758

I will need to port this to 5.0 as this is affecting winforms costumers directly and apps could just die if we exceed the GDI+ handle limit.

### CODE REVIEW

**Comment by ericstj** [comment]
Could we test for this and maybe other leaks?

**Comment by safern** [comment]
> Could we test for this and maybe other leaks?

Let me think on some ideas with @JeremyKuhne how we can test this.

**Comment by JeremyKuhne** [comment]
[GetGuiResources](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getguiresources) should let you check on handle usage. You'd have to not run the regression test concurrently or kick it off out-of-proc. I haven't used this API myself yet, but given this regression I'm now committing some thought to it.

For 6.0 it might be worth considering introducing disposables to help ensure closure of handles. I call them ["scopes" in WinForms](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.RegionScope.cs#L48), and I flip between disposable ref structs in release and finalizable classes in debug to help shake out where we didn't use them right (didn't put in a using). I found that the majority of usages in WinForms could be scoped to the stack with not much refactoring.

In rolling scopes out in WinForms I found a number of leaks, particularly in cases where we were trying to juggle more than one resource. It also fixed some ordering issues in those cases- ensuring we release in the reverse order of when they were acquired.

**Review by JeremyKuhne — APPROVED** [review]

**Comment by safern** [comment]
Maybe we can add a test for `Icon.DrawIcon` and then open a 6.0 issue to investigate if there are more memory leaks and probably do a small rewrite on places that we need to delete handles to use scopes as you did on winforms.

**Comment by safern** [comment]
I added a test for this specific scenario. Validated that without the fix the test fails. PTAL.

**Comment by safern** [comment]
Hmmm interesting that `finalHandles` is returning `0` when running on mono.

**Comment by ericstj** [comment]
> Hmmm interesting that finalHandles is returning 0 when running on mono.

Is it possible that the GC kicked in before that assertion and cleaned up all your unreferenced drawing types since they are no longer used in the rest of the method body?  Maybe try adding GC.KeepAlive on the them after the assertion.

**Comment by safern** [comment]
> Maybe try adding GC.KeepAlive on the them after the assertion.

I'll try that and see if that's it.

**Comment by safern** [comment]
Interesting, it was not the GC. It was an error on the native call to get the handle count as I was caching the current process handle and reusing it. Calling `Process.GetCurrentProcess().Handle` each time fixed the issue.

**Review by JeremyKuhne — APPROVED** [review]

**Comment by ericstj** [comment]
> It was an error on the native call to get the handle count as I was caching the current process handle and reusing it. Calling Process.GetCurrentProcess().Handle each time fixed the issue.

Sounds like just another type of GC problem.  Process itself is disposable, you captured the IntPtr handle but didn't keep Process rooted.  So Process was finalized which closed the handle.  This makes more sense, the GC hat plenty of time to run while you were looping.  A better fix would be to add a using for the Process.

**Comment by safern** [comment]
Makes sense.

**Review by ericstj — APPROVED** [review]

**Comment by ericstj** [comment]
Not sure why Helix thinks these tests failed.  I see all tests passing and runner returning 0.
https://dev.azure.com/dnceng/public/_build/results?buildId=983602&view=ms.vss-test-web.build-test-results-tab&runId=30817358&resultId=175855&paneView=attachments
https://dev.azure.com/dnceng/public/_build/results?buildId=983602&view=ms.vss-test-web.build-test-results-tab&runId=30817202&resultId=183737&paneView=attachments

Is something going on with Helix on OSX?  cc @MattGal

**Comment by MattGal** [comment]
@ericstj yes these are the same two strange timeouts @safern showed me.  Given the symptoms, it's most likely network flakiness in the lab where these macs are hosted while communicating with Event Hub (in such a way that it never returns).  If it happens more than twice (or, say, on the same machines repeatedly) we can open up an issue on dotnet/core-eng to have DDFUN investigate the hardware.

One possible thing you could do quickly would be to stop using XUnit reporter by [setting EnableXunitReporter=false](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets#L22), since the main workflow seems to look at test failures in AzDO anyways.   This of course depends on whether folks still use this mode of test result analysis.

**Comment by safern** [comment]
> This of course depends on whether folks still use this mode of test result analysis.

Would disabling that, stop pushing results to Kusto? Cause we do use Kusto still for some things.

**Pull request merged**
