### PR TITLE
[RISC-V][LoongArch64] Pass structs containing empty struct arrays according to integer calling convention

### PR DESCRIPTION
**Pull request by tomeksowi**
A note from RISC-V Hardware Floating-point Calling Convention:
> One exceptional case for the flattening rule is an array of empty structs or unions;
> C treats it as an empty field, but C++ treats it as a non-empty field since C++ defines
> the size of an empty struct or union as 1. i.e. for struct { struct {} e[1]; float f;
> } as the first argument, C will treat it like struct { float f; } and pass f in fa0 as
> described below, whereas C++ will pass the pass the entire aggregate in a0 (XLEN =
> 64) or a0 and a1 (XLEN = 32), as described in the integer calling convention. Zerolength
> arrays of empty structs or union will be ignored for both C and C++. i.e. For
> struct { struct {} e[0]; float f; };, as the first argument, C and C++ will treat it
> like struct { float f; } and pass f in fa0 as described below.

@LuckyXu-HF @shushanhf LoongArch ABI doesn't seem to mention it but from what I could discern [GCC behaves the same way](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXLnwEEAqgGdMABQAenAAy8AVhNK0mDUMgCkAJgBCZ86UX1kBPAMqN0AYVS0Ariwa6XAGTwGTAA5bwAjTGIJAA5SAAdUeUJHBncvH11E5IcBQOCwlkjorjjbTHtUoQImYgJ0718pcsqBatqCfNCIqNibGrqGzOaBzqDuot7SgEobVE9iZHYOeQJiT3sAagBBYmImAE8AeSpsFniHTHljdW3jAHZLW5uATlX1%2BwfLe4ARTcxjABWcxcIE/YwAZied1%2BkOhN227w2BB2e0OJzOFzwVwAYrRUEwCD95uF6AivuT1C9dvtjqdzpd5KjaRiGdj5Oo4ZSXlR8YTNniCQROVDuegSfRNsTPKTMCL4bDRc9bjT0fSsbi%2BUSJZhNthkAhUAB9VV0zGMwWE6Wyo0AJTw8mQADUIEEUUx1KRNryhd6PaRuabWRr5JbtTLJUwuEamKZpuTHtziJgCAsGJsozHTFznrDbhxZrROIDeL5uLxUJxXFYrJt5PNFrqzBCeKQCBoC7MEJgmFhohBZgBrECmAAsADoIRCXgA2e6j0cvQEvMeAvScUeljukSscXjyECe9scTSzOCwJBoc50KLkShX%2BI36LEABuM9HAFpkPpDKUuJ6aFoAgogPCBwm3cIglqA5OFbSDmGIY5wi0Cpj1bK82EEI4GFoGCT14LBwk8YBXDEWgD3LUgsBYAxgHEfCqLwZNKhfK5t0wFQKk8YDYN4N1MCLBjaDwcJ9kQ9wsG3NY8BYXjSFY4hwiSTAfkwGjDGEwwO1mXkmGAeQnWxAB3I54kYOT%2BEEEQxHYSRpEEBRlDUBidCkH8jBrCw9BEg9IFmVAsQECiPyOAAvCsFOIPAsF8gcbAE1DUmcBg3A8Ro/BSrpCmKLIkhSAQhiaBI8tyBgsp6Ep4rsUr2kGNLhiqxK2lGcrJkq1YOkK3QOrqVqcq4WZ6wWJYJELYstwY3dNltABJIRXA/J1Nlfd9gGQTZv1ozZSnHLhx3UTYIFwQgSE2ZsBt4Y9TyHEdTHHGcZ3/e4Z1MQFRxiUwXsBGd1w4TdSDLTQd04fdDzbbTSHPRAUFQa96DICgIAfJ8QBWz81uQLhR3/Pg6GA4hQPAhj4OguSScQo5kNQuSMMYAhsNw7dCOI0jaHIuTqNo%2BigfwZiHFYiigY4rieMo/jBKB4TROgiTliB6TZMohSlMUVT1LooJQHwnT9H0wzMBMsyy1bSzhFEcQ7NNxzVG3HQIT0WiUE86wpdi/zAoYYKwoiqIopi%2BBBoS1pfAgFwuq4F5SACcZst6H7snytJ6qaSOE9Kvq48a4PavqZOJEjloapamOKpAH6etzjIU/6DoM%2BiGdBobEaBt%2BksAe3KbZvmxbDvfD9IIIeRpk2DHtonPaDqO/AiGIM7TBbaZLu0rsez7SgbtMe5x0BZ7sZiKkIXUUoZxiOJBP%2BwGKxBmwwaugtIZgaHkfhu8kdhx94ZAfEBGAWoDVWrGONAL40JhBKCiEybgKQihewNNYaYXpjhPCPNMBERImRCirZOYaTlgRJiiUBbsU4sgbiyxWzi23FLMSBxZZSSiorVsytlJqy5prCGuk9bGVMuZSiptrIWykFbRQNsXIjgdlpEwFgrDeXCG7HcHsvbhR3JFaKbE/JZ1KslVKVcMroDrrlHIqRw7FUMXkEubVupByLp1POzQrFVGLgUUuIwbE6Jcb1cx/VG7DVsmNDgbdL7Aw4Jsb%2Bhg/4IHfCPZA60sa7X2odY6M854LyXtrDegJxyjlMKYGILYuDfXnuoQEgIz4bgmkDXcoMjzL1%2BqYcpV89zgzSfJECSVRxAA%3D) so I left it in for LA as well.

Plus, some fixes to the EmptyStructs test code.

Stems from #101796, part of #84834, cc @dotnet/samsung

### CODE REVIEW

**Comment by risc-vv** [comment]
<details><summary>67142cf8 is being scheduled for building and testing</summary>

GIT: `67142cf81e2dbdd37ea1fe33999266a918521472`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by risc-vv** [comment]
<details><summary>67142cf8 is being scheduled for building and testing</summary>

GIT: `67142cf81e2dbdd37ea1fe33999266a918521472`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by tomeksowi** [comment]
@MichalStrehovsky @jkotas Can anyone review please?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky @jkotas Can anyone review please?

@shushanhf could you have a look please? Cc @dotnet/jit-contrib

**Comment by jkotas** [comment]
> C treats it as an empty field, but C++ treats it as a non-empty field since C++ defines the size of an empty struct or union as 1. 

Are you implementing the C treatment or C++ treatment in this PR?

**Comment by tomeksowi** [comment]
> Are you implementing the C treatment or C++ treatment in this PR?

C++. That matches empty structs in .NET which are also sized 1 byte.

**Comment by jkotas** [comment]
The managed/unmanaged interop should follow C ABI. There are number of differences between C and C++ ABIs, for example https://github.com/dotnet/runtime/issues/106471.

The managed/managed calling convention does not need to follow C ABI. Managed/unmanaged should either follow the C ABI or we should throw PlatformNotSupportedException if it is hard to implement.

**Comment by tomeksowi** [comment]
> The managed/unmanaged interop should follow C ABI. There are number of differences between C and C++ ABIs, for example #106471.
>
> The managed/managed calling convention does not need to follow C ABI.

So it's ok for managed/managed calling convention to follow C++ ABI wrt empty structs?

> Managed/unmanaged should either follow the C ABI or we should throw PlatformNotSupportedException if it is hard to implement.

Given empty structs are undefined in C (it's a GCC extension to define them as 0 bytes) and they are defined in .NET as 1 byte like in C++, shouldn't .NET throw PlatformNotSupportedException for anything with an empty struct field in a managed/unmanaged signature? (not just on RISC-V but on any architecture)

I'm ok with that, but in that case how to check that managed/managed follows C++ ABI wrt empty structs? Currently I'm using the EmptyStructs test for confronting it against native compilers.

**Comment by jkotas** [comment]
cc @dotnet/interop-contrib for opinions about interop for empty structs.

> shouldn't .NET throw PlatformNotSupportedException for anything with an empty struct field in a managed/unmanaged signature? (not just on RISC-V but on any architecture)

It would be best, but it would be a breaking change. I am not sure whether we would want to make this breaking change.

> how to check that managed/managed follows C++ ABI wrt empty structs?

The managed/managed calling convention has several differences from the managed/unmanaged calling convention. We do not have an explicit for the specific managed/managed calling convention details. We just have a tests that validate that all parts of the system agree on the details.

I guess it may be ok to keep the test that you have added, but it should have a comment that it is testing undefined behavior.

**Comment by risc-vv** [comment]
<details><summary>798cb129 is being scheduled for building and testing</summary>

GIT: `798cb12987f2177a86ba175795394c48e738c8ed`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by tomeksowi** [comment]
> The managed/managed calling convention has several differences from the managed/unmanaged calling convention. We do not have an explicit for the specific managed/managed calling convention details. We just have a tests that validate that all parts of the system agree on the details.

What are the reasons for these differences? I'm wondering if they are avoidable as long as the arguments can be represented the same way in .NET and on the native side.

One of the reasons I've been pushing in recent PRs for closer compliance with the RISC-V calling convention also for managed/managed is to avoid maintaining separate code paths for the managed/unmanaged calling convention, which we have to support anyway and is well documented.

Another reason (for supporting for custom field offsets in FP structs) is of course that custom field padding may also appear without empty structs, e.g. when the struct argument is packed, so it would be valid for interop calls. Empty structs just allow for different (oversized) padding cases that couldn't be achieved with StructLayoutAttribute.Pack, whose effects cannot exceed the default alignment for a type.

> I guess it may be ok to keep the test that you have added, but it should have a comment that it is testing undefined behavior.

Added comment.

**Comment by jkotas** [comment]
> What are the reasons for these differences?

- Code quality, e.g. https://github.com/dotnet/runtime/pull/106312#issuecomment-2287201346
- Non-implemented features: e.g. https://github.com/dotnet/runtime/pull/73601 (we block types like Vector or Int128 in interop since we know they are not passed correctly)

**Comment by tannergooding** [comment]
> cc @dotnet/interop-contrib for opinions about interop for empty structs.

I think it'd be best/easiest to treat empty structs as 1-byte. This ensures that there isn't any "weirdness" when doing `[DisableRuntimeMarshalling]` and considerations like `sizeof(T)` or `Unsafe.SizeOf<T>()`, matches the .NET and C++ requirements and is within the allowance of C (where it is undefined).

I would expect we are already treating it as 1-byte on Windows x86/x64/Arm64 due to the need for COM interop (which is typically C++ oriented) and that it likely required less work to make function. If we do have some differing back-compat requirement that treats it differently, however, then I'd expect we just preserve that everywhere for consistency.

**Comment by AaronRobinsonMSFT** [comment]
> I think it'd be best/easiest to treat empty structs as 1-byte. This ensures that there isn't any "weirdness" when doing [DisableRuntimeMarshalling] or using APIs like sizeof(T)/Unsafe.SizeOf<T>(), matches the .NET and C++ requirements and is within the allowance of C (where it is undefined).

Agree. I know that @jkoritzinsky did some work in this are and it caused a great deal of grief trying to get it right. I'll defer to him, but if I recall correctly, we came down on empty structs were 1-byte.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
