### PR TITLE
[wasm][http] Make content stream unseekable

### PR DESCRIPTION
**Pull request by lewing**
fix for https://github.com/dotnet/runtime/issues/54159

### CODE REVIEW

**Comment by pavelsavara** [comment]
Let's merge https://github.com/dotnet/runtime/pull/54289 first, so that we could see the tests pass

**Comment by stephentoub** [comment]
I think arguably the test is being too strict here, and shouldn't require that the response stream be unseekable.  That happens to be the case for SocketsHttpHandler here, but there's no fundamental reason it needs to be true. @geoffkizer?

**Comment by geoffkizer** [comment]
> That happens to be the case for SocketsHttpHandler here, but there's no fundamental reason it needs to be true.

I agree; if the resulting response Stream is seekable by default, then there's no reason to disallow this.

**Comment by pavelsavara** [comment]
Closing in favor of https://github.com/dotnet/runtime/pull/54603

**Pull request closed without merging**
