### PR TITLE
[browser][Wasm.Build.Tests] Use trimmer friendly JSON serialization

### PR DESCRIPTION
**Pull request by maraf**
- Use `JsonSerializer.Serialize` overload with `JsonSerializerContext`
- Remove `SuppressTrimAnalysisWarnings=true` from test project

### CODE REVIEW

**Comment by radical** [comment]
@maraf I pushed a change - `CI: trigger only WBT on testasset changes`

**Comment by maraf** [comment]
The has failed, but Helix marked the test as passed https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-94034-merge-f01587ce73c24c259e/Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests/1/xharness-output/testResults.xml?helixlogtype=result

**Comment by radical** [comment]
> The test has failed, but Helix marked the test as passed [helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-94034-merge-f01587ce73c24c259e/Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests/1/xharness-output/testResults.xml?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-94034-merge-f01587ce73c24c259e/Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests/1/xharness-output/testResults.xml?helixlogtype=result)

That results file has:
`<test name="Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests.FailOnMissingLazyAssembly" type="Wasm.Build.Tests.TestAppScenarios.LazyLoadingTests" method="FailOnMissingLazyAssembly" time="79.3860332" result="Pass">`

.. so xunit marked the test as `Pass`. Also, the output has:
```
[error] MONO_WASM:    at LazyLoadingTest.__Wrapper_Run_251373279(JSMarshalerArgument* __arguments_buffer) in C:\helix\work\workitem\e\wbt\LazyLoadingTests_ktk5k3bn_km0\Microsoft.Interop.JavaScript.JSImportGenerator\Microsoft.Inter>
Error: Could not load file or assembly 'System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
    at Qn (http://127.0.0.1:49204/_framework/dotnet.runtime.9.0.0-ci.svs40qok5n.js:3:32554)
    at uo (http://127.0.0.1:49204/_framework/dotnet.runtime.9.0.0-ci.svs40qok5n.js:3:63537)
    at Object.<anonymous> (http://127.0.0.1:49204/_framework/dotnet.runtime.9.0.0-ci.svs40qok5n.js:3:182394)
    at http://127.0.0.1:49204/main.js:84:37
[info] WASM EXIT 1
```
.. which seems to be message expected from the failed run.

All that sounds correct. What am I missing?

**Comment by radical** [comment]
In a follow PR I'll move `testassets` to be under WBT folder, as it is used only for that.

**Comment by maraf** [comment]
> All that sounds correct. What am I missing?

Sorry, my bad. It is expected for that test.

**Review by radical — APPROVED** [review]

**Comment by lewing** [comment]
was I missing the attribute before?

**Review by lewing — APPROVED** [review]

**Comment by maraf** [comment]
> was I missing the attribute before? or did I misread the failure too...

The test is expected to fail and exit code is exptected to be 1.

**Pull request merged**
