### PR TITLE
Add package readmes (continued)

### PR DESCRIPTION
**Pull request by ViktorHofer**
Continuation of https://github.com/dotnet/runtime/pull/91210

One of the top customer problems that package consumers are facing is lack of documentation. As such, we are driving an effort to increase the adoption and quality of NuGet package READMEs.

### Ask

To lead by example and ensure that our packages have the maximum impact, we would greatly appreciate your support in increasing the adoption and quality of NuGet package READMEs.

### Why

The README file is an essential part of your package as it provides important information to users and helps them understand what the package is and what it does quickly. Also, README is the first things for users when they view your package on NuGet.org and soon other tooling, it is crucial for package authors to write and include high-quality READMEs for their packages.

### How

This PR initializes READMEs for all the below listed packages. Please directly push to this branch and also use this PR by your POD area team to review changes. For a great example, please see [`System.Text.Json`'s package README](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/PACKAGE.md). Expect to spend ~30min of your time per README. Please try to keep documentation as minimal as possible to avoid duplicating information that is already available on docs.microsoft.com.
 
## Packages
_This list is sorted alphabetically._

| Package | | Status |
| :--- | :---: | :---: |
| Microsoft.Bcl.Cryptography | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Bcl.Cryptography/src/PACKAGE.md) | ✅ |
| Microsoft.Extensions.Caching.Abstractions | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/PACKAGE.md) | ✅ |
| Microsoft.Extensions.DependencyInjection.Specification.Tests | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Extensions.DependencyInjection.Specification.Tests/src/PACKAGE.md) | |
| Microsoft.Extensions.FileProviders.Abstractions | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Extensions.FileProviders.Abstractions/src/PACKAGE.md) | ✅ |
| Microsoft.Extensions.FileProviders.Composite | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Extensions.FileProviders.Composite/src/PACKAGE.md) | |
| Microsoft.Extensions.FileProviders.Physical | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PACKAGE.md) | ✅ |
| Microsoft.Extensions.FileSystemGlobbing | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/PACKAGE.md) | ✅ |
| Microsoft.Extensions.Hosting.Systemd | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Extensions.Hosting.Systemd/src/PACKAGE.md) | ✅ |
| Microsoft.Extensions.Logging.Configuration | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Extensions.Logging.Configuration/src/PACKAGE.md) | |
| Microsoft.Extensions.Logging.EventSource | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Extensions.Logging.EventSource/src/PACKAGE.md) | |
| Microsoft.Extensions.Logging.TraceSource | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Extensions.Logging.TraceSource/src/PACKAGE.md) | :white_check_mark: |
| Microsoft.Extensions.Options.DataAnnotations | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Extensions.Options.DataAnnotations/src/PACKAGE.md) | ✅ |
| Microsoft.NET.WebAssembly.Threading | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.NET.WebAssembly.Threading/src/PACKAGE.md) | |
| Microsoft.Win32.Registry.AccessControl | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Win32.Registry.AccessControl/src/PACKAGE.md) | ✅ |
| Microsoft.Win32.SystemEvents | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.Win32.SystemEvents/src/PACKAGE.md) | ✅ |
| Microsoft.XmlSerializer.Generator | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/Microsoft.XmlSerializer.Generator/src/PACKAGE.md) | |
| System.CodeDom | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.CodeDom/src/PACKAGE.md) | |
| System.ComponentModel.Composition | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.ComponentModel.Composition/src/PACKAGE.md) | |
| System.ComponentModel.Composition.Registration | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.ComponentModel.Composition.Registration/src/PACKAGE.md) | |
| System.Composition | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Composition/src/PACKAGE.md) | |
| System.Composition.AttributedModel | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Composition.AttributedModel/src/PACKAGE.md) | |
| System.Composition.Convention | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Composition.Convention/src/PACKAGE.md) | |
| System.Composition.Hosting | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Composition.Hosting/src/PACKAGE.md) | |
| System.Composition.Runtime | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Composition.Runtime/src/PACKAGE.md) | |
| System.Composition.TypedParts | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Composition.TypedParts/src/PACKAGE.md) | |
| System.Diagnostics.DiagnosticSource | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Diagnostics.DiagnosticSource/src/PACKAGE.md) | |
| System.DirectoryServices.Protocols | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.DirectoryServices.Protocols/src/PACKAGE.md) | ✅ |
| System.Formats.Cbor | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Formats.Cbor/src/PACKAGE.md) | ✅ |
| System.IO.Hashing | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.IO.Hashing/src/PACKAGE.md) | ✅ |
| System.IO.Packaging | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.IO.Packaging/src/PACKAGE.md) | |
| System.IO.Pipelines | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.IO.Pipelines/src/PACKAGE.md) | |
| System.Memory.Data | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Memory.Data/src/PACKAGE.md) | ✅ |
| System.Numerics.Tensors | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Numerics.Tensors/src/PACKAGE.md) | ✅ |
| System.Reflection.Context | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Reflection.Context/src/PACKAGE.md) | |
| System.Resources.Extensions | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Resources.Extensions/src/PACKAGE.md) | |
| System.Runtime.Serialization.Schema | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Runtime.Serialization.Schema/src/PACKAGE.md) | |
| System.Security.Cryptography.Cose | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Security.Cryptography.Cose/src/PACKAGE.md) | |
| System.Security.Cryptography.Pkcs | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Security.Cryptography.Pkcs/src/PACKAGE.md) | |
| System.Security.Cryptography.ProtectedData | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Security.Cryptography.ProtectedData/src/PACKAGE.md) | |
| System.Security.Cryptography.Xml | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Security.Cryptography.Xml/src/PACKAGE.md) | |
| System.Security.Permissions | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Security.Permissions/src/PACKAGE.md) | |
| System.ServiceModel.Syndication | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.ServiceModel.Syndication/src/PACKAGE.md) | ✅ |
| System.Text.Encodings.Web | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Text.Encodings.Web/src/PACKAGE.md) | ✅ |
| System.Threading.AccessControl | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Threading.AccessControl/src/PACKAGE.md) | ✅ |
| System.Threading.RateLimiting | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Threading.RateLimiting/src/PACKAGE.md) | ✅ |
| System.Threading.Tasks.Dataflow | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Threading.Tasks.Dataflow/src/PACKAGE.md) | |
| System.Windows.Extensions | [Edit](https://github.com/dotnet/runtime/edit/PackageReadmesContinued/src/libraries/System.Windows.Extensions/src/PACKAGE.md) | |

:white_check_mark: (`:white_check_mark:`) -> reviewed & approved

:clock130: (`:clock130:`) -> under review

cc @lyndaidaii @ericstj @jeffhandley @artl93 @MSDN-WhiteKnight

### CODE REVIEW

**Comment by danmoseley** [comment]
Presumably we'd be happy to accept community help here? They'd have to share a link to a branch or gist given no perms to push to this

**Comment by ViktorHofer** [comment]
> Presumably we'd be happy to accept community help here? They'd have to share a link to a branch or gist given no perms to push to this

Yes, absolutely. Good idea. I just added the label. We could ask the community to submit a PR against this branch.

**Comment by eNeRGy164** [comment]
@ViktorHofer Should the table be updated to prevent people from starting to work on a package that is already in progress/done?

**Comment by eNeRGy164** [comment]
I learn a lot on APIs I never had a reason to use. 😝

**Review by ericstj — APPROVED** [review]
LGTM - @ViktorHofer let me know this is an aggregate of already reviewed content.

**Review by tarekgh — APPROVED** [review]

**Pull request merged**
