### PR TITLE
Fix flaky FSW test

### LINKED ISSUE #103753: [Test Failure] System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=713266
Build error leg or test failing: System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize
Pull request: https://github.com/dotnet/runtime.git/pull/103720

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize", "Did not observe an error event within 500ms and 3 attempts."] ,
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=713266
**Error message validated:** `[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize Did not observe an error event within 500ms and 3 attempts.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/20/2024 11:08:40 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[718424](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718424)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718424&view=ms.vss-test-web.build-test-results-tab&runId=18005060&resultId=118878)|dotnet/runtime#101865|
|[718455](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718455)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718455&view=ms.vss-test-web.build-test-results-tab&runId=18005100&resultId=139639)|dotnet/runtime#100194|
|[718427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718427)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718427&view=ms.vss-test-web.build-test-results-tab&runId=18004984&resultId=134872)|dotnet/runtime#103567|
|[718354](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718354)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718354&view=ms.vss-test-web.build-test-results-tab&runId=18003866&resultId=136757)|dotnet/runtime#103902|
|[718303](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718303)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718303&view=ms.vss-test-web.build-test-results-tab&runId=18001986&resultId=116222)|dotnet/runtime#103037|
|[718258](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718258)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718258&view=ms.vss-test-web.build-test-results-tab&runId=18001038&resultId=127644)|dotnet/runtime#103900|
|[716128](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716128)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716128&view=ms.vss-test-web.build-test-results-tab&runId=17996312&resultId=138506)|dotnet/runtime#103835|
|[717972](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717972)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717972&view=ms.vss-test-web.build-test-results-tab&runId=17994714&resultId=138307)|dotnet/runtime#100745|
|[717912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717912)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717912&view=ms.vss-test-web.build-test-results-tab&runId=17990262&resultId=130225)|dotnet/runtime#103714|
|[717829](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717829)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717829&view=ms.vss-test-web.build-test-results-tab&runId=17986260&resultId=116171)|dotnet/runtime#103883|
|[717617](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717617)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717617&view=ms.vss-test-web.build-test-results-tab&runId=17975928&resultId=121159)|dotnet/runtime#103510|
|[717603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717603)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717603&view=ms.vss-test-web.build-test-results-tab&runId=17975410&resultId=137635)|dotnet/runtime#103837|
|[717479](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717479)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717479&view=ms.vss-test-web.build-test-results-tab&runId=17971376&resultId=137490)|dotnet/runtime#103852|
|[717385](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717385)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717385&view=ms.vss-test-web.build-test-results-tab&runId=17968498&resultId=112992)|dotnet/runtime#103574|
|[717274](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717274)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717274&view=ms.vss-test-web.build-test-results-tab&runId=17967204&resultId=135792)|dotnet/runtime#103412|
|[717204](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717204)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717204&view=ms.vss-test-web.build-test-results-tab&runId=17961064&resultId=108121)|dotnet/runtime#103861|
|[717186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717186)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717186&view=ms.vss-test-web.build-test-results-tab&runId=17960062&resultId=132514)|dotnet/runtime#103852|
|[717011](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717011)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717011&view=ms.vss-test-web.build-test-results-tab&runId=17954492&resultId=108022)||
|[717021](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717021)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717021&view=ms.vss-test-web.build-test-results-tab&runId=17954974&resultId=129823)|dotnet/runtime#103836|
|[716966](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716966)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716966&view=ms.vss-test-web.build-test-results-tab&runId=17951542&resultId=108116)|dotnet/runtime#103216|
|[716922](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716922)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716922&view=ms.vss-test-web.build-test-results-tab&runId=17950526&resultId=113707)|dotnet/runtime#103778|
|[716917](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716917)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716917&view=ms.vss-test-web.build-test-results-tab&runId=17950202&resultId=130957)|dotnet/runtime#102144|
|[716905](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716905)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716905&view=ms.vss-test-web.build-test-results-tab&runId=17949966&resultId=137273)|dotnet/runtime#103852|
|[716617](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716617)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716617&view=ms.vss-test-web.build-test-results-tab&runId=17939946&resultId=118847)|dotnet/runtime#103847|
|[716624](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716624)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716624&view=ms.vss-test-web.build-test-results-tab&runId=17939972&resultId=124738)|dotnet/runtime#103851|
|[716206](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716206)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716206&view=ms.vss-test-web.build-test-results-tab&runId=17929422&resultId=137632)|dotnet/runtime#103769|
|[716194](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716194)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716194&view=ms.vss-test-web.build-test-results-tab&runId=17929006&resultId=138586)||
|[716102](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716102)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=716102&view=ms.vss-test-web.build-test-results-tab&runId=17926848&resultId=137531)|dotnet/runtime#103833|
|[715981](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715981)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715981&view=ms.vss-test-web.build-test-results-tab&runId=17923120&resultId=134318)|dotnet/runtime#103681|
|[715984](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715984)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715984&view=ms.vss-test-web.build-test-results-tab&runId=17923302&resultId=139388)|dotnet/runtime#103706|
|[715926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715926)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715926&view=ms.vss-test-web.build-test-results-tab&runId=17919318&resultId=134911)|dotnet/runtime#103826|
|[715906](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715906)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715906&view=ms.vss-test-web.build-test-results-tab&runId=17917804&resultId=137063)|dotnet/runtime#100379|
|[715744](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715744)|dotnet/runtime|[System.IO.Tests.Directory_NotifyFilter_Tests.FileSystemWatcher_Directory_NotifyFilter_Attributes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715744&view=ms.vss-test-web.build-test-results-tab&runId=17913538&resultId=137341)|dotnet/runtime#103673|
|[715843](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715843)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715843&view=ms.vss-test-web.build-test-results-tab&runId=17916198&resultId=137850)|dotnet/runtime#103804|
|[715812](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715812)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715812&view=ms.vss-test-web.build-test-results-tab&runId=17914868&resultId=112008)|dotnet/runtime#103701|
|[715736](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715736)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715736&view=ms.vss-test-web.build-test-results-tab&runId=17913354&resultId=137296)|dotnet/runtime#103765|
|[715561](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715561)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715561&view=ms.vss-test-web.build-test-results-tab&runId=17908322&resultId=137594)|dotnet/runtime#103412|
|[715449](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715449)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715449&view=ms.vss-test-web.build-test-results-tab&runId=17903750&resultId=117094)|dotnet/runtime#103804|
|[715438](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715438)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715438&view=ms.vss-test-web.build-test-results-tab&runId=17902628&resultId=130566)|dotnet/runtime#103806|
|[715345](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715345)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715345&view=ms.vss-test-web.build-test-results-tab&runId=17900782&resultId=137648)|dotnet/runtime#102167|
|[715298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715298)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715298&view=ms.vss-test-web.build-test-results-tab&runId=17898156&resultId=137615)|dotnet/runtime#103681|
|[715268](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715268)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715268&view=ms.vss-test-web.build-test-results-tab&runId=17897308&resultId=111051)|dotnet/runtime#103617|
|[715203](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715203)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715203&view=ms.vss-test-web.build-test-results-tab&runId=17894622&resultId=137310)|dotnet/runtime#103794|
|[715199](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715199)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715199&view=ms.vss-test-web.build-test-results-tab&runId=17894568&resultId=137753)|dotnet/runtime#103793|
|[715173](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715173)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715173&view=ms.vss-test-web.build-test-results-tab&runId=17893328&resultId=137449)|dotnet/runtime#103681|
|[714201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714201)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714201&view=ms.vss-test-web.build-test-results-tab&runId=17891532&resultId=128078)|dotnet/runtime#103764|
|[714999](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714999)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714999&view=ms.vss-test-web.build-test-results-tab&runId=17889368&resultId=136353)|dotnet/runtime#102167|
|[714603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714603)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714603&view=ms.vss-test-web.build-test-results-tab&runId=17888696&resultId=137111)|dotnet/runtime#103372|
|[714868](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714868)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714868&view=ms.vss-test-web.build-test-results-tab&runId=17884842&resultId=138384)|dotnet/runtime#103769|
|[714490](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714490)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714490&view=ms.vss-test-web.build-test-results-tab&runId=17874146&resultId=127528)|dotnet/runtime#103655|
|[714509](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714509)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714509&view=ms.vss-test-web.build-test-results-tab&runId=17875004&resultId=137282)|dotnet/runtime#103244|
|[714408](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714408)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714408&view=ms.vss-test-web.build-test-results-tab&runId=17872420&resultId=120450)|dotnet/runtime#103681|
|[714339](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714339)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714339&view=ms.vss-test-web.build-test-results-tab&runId=17871282&resultId=137060)|dotnet/runtime#103769|
|[714245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714245)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=714245&view=ms.vss-test-web.build-test-results-tab&runId=17867866&resultId=137605)|dotnet/runtime#103705|
|[713848](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713848)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713848&view=ms.vss-test-web.build-test-results-tab&runId=17856872&resultId=136464)||
|[713687](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713687)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713687&view=ms.vss-test-web.build-test-results-tab&runId=17852456&resultId=120799)|dotnet/runtime#103728|
|[713594](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713594)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize_SynchronizingObject](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713594&view=ms.vss-test-web.build-test-results-tab&runId=17849852&resultId=118548)|dotnet/runtime#103737|
|[713266](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713266)|dotnet/runtime|[System.IO.Tests.InternalBufferSizeTests.FileSystemWatcher_InternalBufferSize](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713266&view=ms.vss-test-web.build-test-results-tab&runId=17838908&resultId=122803)|dotnet/runtime#103720|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|13|58|58|

### PR DESCRIPTION
**Pull request by danmoseley**
Fix https://github.com/dotnet/runtime/issues/103753

Test does not fail for me locally; making assumption that firing even more events will this will help avoid it failing elsewhere. 

1. Fix the calculation of the size of FILE_NOTIFY_INFORMATION, although this is likely not material.
1. Fire 250x the number of events that will fill the buffer, instead of 100x. Takes the 3 tests from 3 seconds total to 28 seconds for me. Guessing this is hitting some kind of IO parallelism threshold.
1. Speed up some by moving file system operations to threadpool. Takes tests to 20 seconds.
1. Halve size of buffer, also reduce to 200x. Tests are 9 seconds.
1. It's still slow so move to outerloop.

### CODE REVIEW

**Comment by danmoseley** [comment]
BTW error case of too small InternalBufferSize is not being tested Linux (which may have different error behavior/limits)

**Comment by danmoseley** [comment]
Comment says "where filePath is the path to changed file relative to the path passed into ReadDirectoryChanges." .. but the math does not use the relative path. Small beans; will cause over estimate, increasing events.

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you for providing the fix @danmoseley !

**Comment by danmoseley** [comment]
Can we run outer loop on this PR? It's just speculation that this will fix the test

**Comment by Jozkee** [comment]
https://github.com/dotnet/runtime/issues/103753 also mentions `FileSystemWatcher_Directory_NotifyFilter_Attributes` so it won't completely fix it.

**Comment by danmoseley** [comment]
Right, not really evidence that's related. Eg., it didn't start on the same day, it only happened once.

**Comment by danmoseley** [comment]
OK, Build Analysis is recognizing all failures, so this is good to merge if you're OK with that @Jozkee

**Review by jozkee — APPROVED** [review]

**Pull request merged**
