### PR TITLE
Add arg aliases for runtimeConfiguration and librariesConfiguration

### LINKED ISSUE #2172: -runtimeConfiguration breaks -r as a shortcut for restore on build.ps1
```
PS E:\source\runtime [master ≡] > .\build.cmd -r
E:\source\runtime\eng\build.ps1 : Missing an argument for parameter 'runtimeConfiguration'. Specify a parameter of type 'System.String' and try again.
    + CategoryInfo          : InvalidArgument: (:) [build.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingArgument,build.ps1
```

This previously would run restore. Passing -restore works fine. Trivial fix is to just clean up the help text.

### PR DESCRIPTION
**Pull request by safern**
I feel like people type a lot just to pass in either runtimeConfiguration or librariesConfiguration to the build scripts.

This also fixes the help text as -r is not supported in powershell for restore as powershell takes it as the runtimeConfiguration because it matches substrings on parameters.

Fixes: https://github.com/dotnet/runtime/issues/2172

cc: @stephentoub @jkotas @dotnet/runtime-infrastructure

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jkotas** [comment]
On Windows, the shortcuts work already, as long as they are non-ambiguous - Powershell feature. So the following works on Windows today, even without this change:

`build -su clr+libs -ru checked -c Release`

Should we just use the shortcuts that you naturally get on Windows for Unix as well?

**Comment by safern** [comment]
> Should we just use the shortcuts that you naturally get on Windows for Unix as well?

Yeah that Powershell feature is handy, however, the reason why I chose adding -rc and -lc, is because it is more natural, usually short form of script arguments are the initials of the works that compose the full name and when reading a command it is easier for the reader to relate -rc to runtimeConfiguration than -ru as -ru the only relation it has, is that is the first two letters of the script.

Also, adding a short form for -subset in Unix does makes a lot of sense.

**Comment by safern** [comment]
@jkotas do you agree on merging this as is?

**Review by jkotas — APPROVED** [review]
Looks fine to me. It would be nice to have `-s` shortcut for subsets.

**Comment by safern** [comment]
> It would be nice to have -s shortcut for subsets.

Yeah. I'll update before merging.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
