### PR TITLE
Experiment: Skip PRECODE for direct Tier1 targets

### PR DESCRIPTION
**Pull request by EgorBo**
Use direct call for managed-to-managed if target is already Tier1.

### CODE REVIEW

**Comment by EgorBo** [comment]
@sebastienros `crank` fails for me this morning with:
```
[cbase1/4] [01:01:27.614] Submitted job: http://asp-citrine-load:5001/jobs/211
[cbase1/4] [01:01:29.215] 'load' has been selected by the server ...
[cbase1/4] [01:01:29.608] 'load' is now building ... http://asp-citrine-load:5001/jobs/211/buildlog
[cbase1/4] [01:01:31.204] 'load' failed on agent, stopping...
[cbase1/4] Job failed at runtime with exit code 134:
[cbase1/4] WRK Client
[cbase1/4] args: -c 256 http://10.0.0.102:5000/mvc/plaintext --latency -d 15s -w 15s -t 32 --header Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7 --header Connection: keep-alive -s scripts/pipeline.lua -- 16
[cbase1/4] [STDERR] Unhandled exception. System.Net.Http.HttpRequestException: Connection refused
[cbase1/4] [STDERR]  ---> System.Net.Sockets.SocketException (111): Connection refused
[cbase1/4] [STDERR]    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
[cbase1/4] [STDERR]    --- End of inner exception stack trace ---
[cbase1/4] [STDERR]    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
[cbase1/4] [STDERR]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
[cbase1/4] [STDERR]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[cbase1/4] [STDERR]    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[cbase1/4] [STDERR]    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
[cbase1/4] [STDERR]    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[cbase1/4] [STDERR]    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
[cbase1/4] [STDERR]    at Microsoft.Crank.Wrk.WrkProcess.MeasureFirstRequest(String[] args) in /tmp/benchmarks-agent/benchmarks-server-1/wrk/crank/src/Microsoft.Crank.Jobs.Wrk/WrkProcess.cs:line 48
[cbase1/4] [STDERR]    at Microsoft.Crank.Wrk.Program.Main(String[] args) in /tmp/benchmarks-agent/benchmarks-server-1/wrk/crank/src/Microsoft.Crank.Jobs.Wrk/Program.cs:line 26
[cbase1/4] [STDERR]    at Microsoft.Crank.Wrk.Program.<Main>(String[] args)
[cbase1/4] [01:01:31.602] Stopping job 'load' ...
[cbase1/4] Job failed at runtime with exit code 134:
```
perhaps some maintenance is happening now?

**Comment by jakobbotsch** [comment]
> it most likely will call it through a hidden intermediate method PRECODE

Are you sure? If I read the code right, `getFunctionEntryPoint` will ask the JIT to call it by indirection through the precode's slot -- which should store direct tier 1 address. So it is `call [tier_1_address_slot]` instead of `call precode_address`. The precode is what we get via `getFunctionFixedEntryPoint`, used e.g. for delegates.

**Comment by EgorBo** [comment]
> > it most likely will call it through a hidden intermediate method PRECODE
> 
> Are you sure? If I read the code right, `getFunctionEntryPoint` will ask the JIT to call it by indirection through the precode's slot -- which should store direct tier 1 address. So it is `call [tier_1_address_slot]` instead of `call precode_address`. The precode is what we get via `getFunctionFixedEntryPoint`, used e.g. for delegates.

just pushed a commit - doesn't it ask JIT to emit a call to a direct address (which will be reloc'd)?

**Comment by jakobbotsch** [comment]
> just pushed a commit - doesn't it ask JIT to emit a call to a direct address (which will be reloc'd) without indirects?

Yes. I think as an experiment this looks more interesting now, though I don't know if it is ok even if a profiler is not attached right now.

**Comment by EgorBo** [comment]
> > just pushed a commit - doesn't it ask JIT to emit a call to a direct address (which will be reloc'd) without indirects?
> 
> Yes. I think as an experiment this looks more interesting now, though I don't know if it is ok even if a profiler is not attached right now.

Right, I just wonder how much we pay for that theoretical possibility on e.g. ARM where precodes use memory loads

**Comment by EgorBo** [comment]
I wasn't able to detect any perf difference on both linux-x64 and linux-arm64 for TE and small microbenchmarks so I am closing this

**Comment by AndyAyersMS** [comment]
Seeing what may be a related issue in https://github.com/dotnet/runtime/issues/67176#issuecomment-1171435043.

**Comment by EgorBo** [comment]
It turns out my PR https://github.com/dotnet/runtime/pull/70988 doesn't need `&& ftn->HasNativeCodeSlot()` check. With it being removed I now see this codegen diff: https://www.diffchecker.com/nKMTF7nE for https://github.com/dotnet/runtime/issues/67176

**Pull request closed without merging**
