### PR TITLE
Enable R2R for NarrowUtf16ToAscii / WidentAsciiToUtf16

### PR DESCRIPTION
**Pull request by stephentoub**
Currently both of these methods on System.Text.Ascii are on the startup path and are being JIT'd:
```
   1: JIT compiled System.Runtime.CompilerServices.CastHelpers:StelemRef(System.Array,long,System.Object) [Tier1, IL size=88, code size=93]
   2: JIT compiled System.Runtime.CompilerServices.CastHelpers:LdelemaRef(System.Array,long,ulong) [Tier1, IL size=44, code size=44]
   3: JIT compiled System.Guid:FormatGuidVector128Utf8(System.Guid,bool) [Tier0, IL size=322, code size=584]
   4: JIT compiled System.HexConverter:AsciiToHexVector128(System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte]) [Tier0, IL size=78, code size=359]
   5: JIT compiled System.Runtime.Intrinsics.Vector128:ShuffleUnsafe(System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte]) [Tier0, IL size=41, code size=50]
   6: JIT compiled System.Text.Unicode.Utf16Utility:GetPointerToFirstInvalidChar(ulong,int,byref,byref) [Instrumented Tier0, IL size=994, code size=1292]
   7: JIT compiled System.Text.Ascii:NarrowUtf16ToAscii(ulong,ulong,ulong) [Instrumented Tier0, IL size=558, code size=1327]
   8: JIT compiled System.RuntimeType+RuntimeTypeCache+MemberInfoCache`1[System.__Canon]:AddMethod(System.RuntimeType,long,int) [Instrumented Tier0, IL size=354, code size=1672]
   9: JIT compiled System.Text.Ascii:WidenAsciiToUtf16(ulong,ulong,ulong) [Instrumented Tier0, IL size=738, code size=1741]
```

They're not using R2R because of use of `Vector<T>`. But the `Vector<T>` block will only be used if either on big-endian or if Vector128 isn't accelerated. If Vector128 isn't accelerated, then given the current state of our target platforms and backends, `Vector<T>` won't be used, either, which means the `Vector<T>` block is only for big endian. By adding a guard clause for big endian, then, R2R starts being used for these methods:
```
   1: JIT compiled System.Runtime.CompilerServices.CastHelpers:StelemRef(System.Array,long,System.Object) [Tier1, IL size=88, code size=93]
   2: JIT compiled System.Runtime.CompilerServices.CastHelpers:LdelemaRef(System.Array,long,ulong) [Tier1, IL size=44, code size=44]
   3: JIT compiled System.Guid:FormatGuidVector128Utf8(System.Guid,bool) [Tier0, IL size=322, code size=584]
   4: JIT compiled System.HexConverter:AsciiToHexVector128(System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte]) [Tier0, IL size=78, code size=359]
   5: JIT compiled System.Runtime.Intrinsics.Vector128:ShuffleUnsafe(System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte]) [Tier0, IL size=41, code size=50]
   6: JIT compiled System.Text.Unicode.Utf16Utility:GetPointerToFirstInvalidChar(ulong,int,byref,byref) [Instrumented Tier0, IL size=994, code size=1292]
   7: JIT compiled System.RuntimeType+RuntimeTypeCache+MemberInfoCache`1[System.__Canon]:AddMethod(System.RuntimeType,long,int) [Instrumented Tier0, IL size=354, code size=1672]
```

@EgorBo, I am curious why they were showing up as "Instrumented Tier0" without another "Tier0" entry for them first. What causes a non-instrumented tier0 to be skipped?

### CODE REVIEW

**Comment by jkotas** [comment]
>given the current state of our target platforms and backends, Vector<T> won't be used, either, which means the Vector<T> block is only for big endian

s390x that is only big endian arch does not support Vector<T> acceleration. Is the Vector<T> block effectively dead code given the state of our platforms and backends?

**Comment by stephentoub** [comment]
> s390x that is only big endian arch does not support Vector acceleration.

In that case, yes, I believe these paths are dead. I'll delete 'em instead.

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by EgorBo** [comment]
> @EgorBo, I am curious why they were showing up as "Instrumented Tier0" without another "Tier0" entry for them first. What causes a non-instrumented tier0 to be skipped?

Methods with loops bypass Tier0 (but not R2R) and go straight to Tier0-instrumented - it's done to avoid cases when a cold method with a hot loop won't benefit from PGO as we can't have two OSR versions

**Comment by EgorBo** [comment]
>  By adding a guard clause for big endian, then, R2R starts being used for these methods:

```
   1: JIT compiled System.Runtime.CompilerServices.CastHelpers:StelemRef(System.Array,long,System.Object) [Tier1, IL size=88, code size=93]
   2: JIT compiled System.Runtime.CompilerServices.CastHelpers:LdelemaRef(System.Array,long,ulong) [Tier1, IL size=44, code size=44]
   3: JIT compiled System.Guid:FormatGuidVector128Utf8(System.Guid,bool) [Tier0, IL size=322, code size=584]
   4: JIT compiled System.HexConverter:AsciiToHexVector128(System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte]) [Tier0, IL size=78, code size=359]
   5: JIT compiled System.Runtime.Intrinsics.Vector128:ShuffleUnsafe(System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte]) [Tier0, IL size=41, code size=50]
   6: JIT compiled System.Text.Unicode.Utf16Utility:GetPointerToFirstInvalidChar(ulong,int,byref,byref) [Instrumented Tier0, IL size=994, code size=1292]
   7: JIT compiled System.RuntimeType+RuntimeTypeCache+MemberInfoCache`1[System.__Canon]:AddMethod(System.RuntimeType,long,int) [Instrumented Tier0, IL size=354, code size=1672]
```
https://github.com/dotnet/runtime/pull/90326 fixes 3,4,5,6 methods. 7 method is weird, cg throws an exception when I try to prejit it 😐

**Comment by SamMonoRT** [comment]
@LeVladIonescu - can you run a before/after on the Mono Interpreter config to make sure this is not a cause of the regressions seen in https://github.com/dotnet/perf-autofiling-issues/issues/20737.

**Pull request merged**
