### PR TITLE
Update SDK used in global.json.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Updates the SDK we use to build dotnet/runtime to get a version with #2354 to unblock #2115

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Review by Anipik — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
The coreroot_determinism test is failing on OSX since we don't produce an apphost on Mac due to Catalina. In any case, this case currently silently fails because there's not a .NET Runtime installed that the apphost can run against in CI (and the local one that we build against isn't deployed to Helix unless we opt-in to do that).

cc: @dotnet/crossgen-contrib since you own this test, can someone from your group suggest a course of action here? Maybe @trylek?

**Comment by nattress** [comment]
That test was written to compile the CoreRoot folder's assemblies and validate they're deterministic when AOT compiled. If the apphost is not present on Mac CI, can we just %core_root%/corerun ReadyToRun.SuperIlc instead? Or is all of %core_root% missing on Mac CI Helix?

I'll fix up the test to properly fail if it can't run SuperIlc in the meantime.

**Comment by jkoritzinsky** [comment]
I tried that locally and the ReadyToRun.SuperIlc process started successfully, but then I hit the silent failure where it failed during the run and the test still passed.

**Comment by nattress** [comment]
Ok, sounds like the test just doesn't pass on Mac and we never noticed due to the silent failure. I'll have a look on my Mac tomorrow and see if it's something we can quickly fix, or if we need to disable the test on Mac.

**Pull request merged**
