### PR TITLE
Disable flaky DNS cancellation tests during jitstress

### PR DESCRIPTION
**Pull request by rzikm**
Related to #69993.

Original fix (#70044), while removing the flakyness, made the test effectively useless (see https://github.com/dotnet/runtime/pull/70044#discussion_r886866234). Based on the discussion we decided that it is better to disable the test during jitstress.

This PR also reverts #70009, as the implementation of async name resolution on *nix platforms was reverted in https://github.com/dotnet/runtime/pull/48666

### CODE REVIEW

**Review by antonfirsov — APPROVED** [review]
LGTM, thanks for your patience cleaning this up!

**Comment by jakobbotsch** [comment]
This test does not only fail in jitstress runs. As I have tried to point out in the original issue, jitstress just runs a lot of configurations and therefore runs tests a lot of times, so if they are flaky it is often exposed under jitstress.

[There are at least 3 failures of this test in the `runtime` pipeline in the past 2 days, i.e. without any jitstress.](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E2+definition%3Aruntime+name%3A%22system.net.nameresolution.tests.gethostaddressestest_cancellation.dnsgethostaddresses_postcancelledtoken_throws%22)

**Comment by rzikm** [comment]
> This test does not only fail in jitstress runs. As I have tried to point out in the original issue, jitstress just runs a lot of configurations and therefore runs tests a lot of times, so if they are flaky it is often exposed under jitstress.
> 
> [There are at least 3 failures of this test in the `runtime` pipeline in the past 2 days, i.e. without any jitstress.](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E2+definition%3Aruntime+name%3A%22system.net.nameresolution.tests.gethostaddressestest_cancellation.dnsgethostaddresses_postcancelledtoken_throws%22)

Those failures are on linux, I mistakenly thought that async name resolution has been implemented on Linux in https://github.com/dotnet/runtime/pull/34633, so I enabled the test on UNIX platforms (it was disabled before). I did not notice that the PR was later reverted (the issue mentioned in the ActiveIssue attribute was still marked as closed). This PR again disables the tests on UNIX so those failures will not repeat.

There are no recent failures of this test on Windows.

**Comment by rzikm** [comment]
The test failure seems unrelated.

**Comment by jakobbotsch** [comment]
> Those failures are on linux, I mistakenly thought that async name resolution has been implemented on Linux in #34633, so I enabled the test on UNIX platforms (it was disabled before). I did not notice that the PR was later reverted (the issue mentioned in the ActiveIssue attribute was still marked as closed). This PR again disables the tests on UNIX so those failures will not repeat.

Got it, but this still just seems like a short-term fix. Any future change, test mode, or even just regular background processes can affect timings in the test execution and has the potential of hitting the same problem. For example, if we wanted to run libraries tests under GCStress (which has been discussed before) that would also affect timings significantly.

With that said, I am more assured now given that the Linux failures were something else.

**Comment by antonfirsov** [comment]
@jakobbotsch unfortunately there are many networking features which can not be tested at all in a manner that is not dependent on timing. We can choose to not test them at all, or to respect the fact that they need better isolation in the test infra. I'm very much for the former, since I believe we should not leave features untested, even if it comes with a price.

> For example, if we wanted to run libraries tests under GCStress (which has been discussed before) that would also affect timings significantly.

Then we will have to exclude timing-dependent networking tests from `GCStress`.

A long term solution could be to create some sort of marker attribute so these tests can be auto-excluded from runs where isolation is not possible.

**Comment by jakobbotsch** [comment]
> We can choose to not test them at all, or to respect the fact that they need better isolation in the test infra.

This does not sound like the only possibilities to me. Other possibilities could be test stubs or a test DNS server that the test controls where timings can be deterministically controlled (I realize this is a lot of work).

**Comment by wfurt** [comment]
we _should_ control the Helix environment. Part of the problem is that some networking test are time dependent e.g. they test that something does happen in given time frame. While there is always potential for improvements it is not trivial too make the 100% reliable. It is also possible that the failures in jitsress are real bugs instead of just timing differences. But the investigation is not easy and there are more important tasks for the release.

**Comment by antonfirsov** [comment]
> a test DNS server

This can solve the DNS issues but not other cases where networking code may become racy.

> test stubs

This is definitely a lot of work for DNS or Sockets, not convinced it's worth it. Having a mindful approach to Helix seems easier to me.

**Pull request merged**
