### PR TITLE
Implement parity for RAF and RDC attributes in NativeAOT

### PR DESCRIPTION
**Pull request by vitek-karas**
The `RequiresUnreferencedCode` (RDC), `RequiresAssemblyFiles` (RAF) and `RequiresDynamicCode` (RDC) attributes should behave the same way in NativeAOT compiler. This change implements the necessary bits to make them almost 100% the same.
The only difference left is type hierarchy marking doesn't produce RAF/RDC related warnings - this is for now intentional, as it would probably produce unnecessary noise and the need for this seems to be really small.

Test changes are to basically fill in the missing expected warnings. We already have solid tests for pretty much all scenarios, they just didn't baseline these warnings since no tool produced them (illink doesn't produce RAF/RDC warnings, analyzer only produces them on direct access, not on reflection access).

This doesn't yet implement the IL3000 and IL3001 warnings in NativeAOT - that will be done in a subsequent change.

### CODE REVIEW

**Review by sbomer — APPROVED** [review]

**Comment by vitek-karas** [comment]
This hits an interesting problem in System.Text.Json. Specifically this:
https://github.com/dotnet/runtime/blob/6c836e84131f5f4d44bb5384e6a812571c528ddd/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptionsUpdateHandler.cs#L10

The `MetadataUpdateHandler` .ctor will mark the `JsonSerializerOptionsUpdateHandler.ClearCache` method which has RDC on it, so the compiler warns (as it should).

The part which is problematic is the `ReflectionEmitCachingMemberAccessor` which heavily relies on ref.emit and thus is not supported in AOT.

So I think it should be OK to wrap the call to that with condition for dynamic code support - as it's only necessary for non-AOT, in AOT the cache should always be empty, as it's not AOT compatible and thus should never be called from AOTed app. And if it is called, then it should already produce a warning somewhere else.

@sbomer, @MichalStrehovsky @agocke  - thoughts?

**Comment by vitek-karas** [comment]
I pushed the potential fix into this PR:
https://github.com/dotnet/runtime/pull/83085/commits/5a7f2bb2b285c13374bc3c710d9d260680088af5

@dotnet/area-system-text-json could somebody please take a look at this change as well as it's inside System.Text.Json. See https://github.com/dotnet/runtime/pull/83085#issuecomment-1460048627 for the details of the problem.

**Review by eiriktsarpalis — APPROVED** [review]
The STJ change looks good to me 👍

**Comment by vitek-karas** [comment]
The CI is failing on known issues - with the exception of two timeouts in browser based Mono tests.

**Pull request merged**
