### PR TITLE
[release/5.0] Move Editor Attribute to S.CM.Primitives and apply to types that had it in netfx 

### PR DESCRIPTION
**Pull request by safern**
Master PR: #41145 

This is needed by Winforms.

## Description

The winforms designer depends on these attributes to be added to types in order to  display the information correctly on the designer.

## Customer Impact

Properties and metadata will not be displayed correctly where as in Full Framework it does.

## Regression?

 From Full Framework, when we ported the types.
 
## Risk 

low. This only adds attributes and moves `EditorAttribute` from `System.ComponentModel.TypeConverters` to `System.ComponentModel.Primitives`.
 
## Test changes in this PR

Tests for the attributes are still running.

cc: @danmosemsft @RussKie

### CODE REVIEW

**Comment by danmosemsft** [comment]
Can you please add a quick template?

@DustinCampbell @RussKie this was done in master. Can you confirm that a port to 5.0 is important to Winforms? The relevant bar would be " Blocking key partner scenarios or blocking adoption "

**Comment by safern** [comment]
> Can you please add a quick template?

Sure.

**Comment by safern** [comment]
Updated the description with the template. This PR is a continuation of:
https://github.com/dotnet/runtime/pull/41066

**Comment by danmosemsft** [comment]
OK approved to merge when green/reviewed. Meets bar "·  Blocking key partner scenarios or blocking adoption "

**Review by RussKie — COMMENTED** [review]
🚀

**Comment by RussKie** [comment]
@dotnet/dotnet-winforms for visibility

**Review by eerhardt — APPROVED** [review]

**Review by ericstj — APPROVED** [review]

**Comment by safern** [comment]
Failure is Windows7 known issue.

**Comment by danmosemsft** [comment]
@RussKie if there's a way for you to test with binaries from our repo without waiting for codeflow that would be a bonus, since the bar is about to go up for any changes to this or additional similar changes.

**Pull request merged**
