### PR TITLE
Update Android RID graph to inherit from Unix

### PR DESCRIPTION
**Pull request by marek-safar**
The previous Linux parent is incorrect as Linux libs won't work on Android

### CODE REVIEW

**Comment by marek-safar** [comment]
@ericstj

**Comment by ericstj** [comment]
This is a breaking change over 3.1. 

> previous Linux parent is incorrect as Linux libs won't work on Android

By this do you mean that they have a different binary format?  What makes them not work?  Can you imagine a lib built a particular way that would work?

**Comment by lpereira** [comment]
It's the same binary format, but Android uses (by default) the Bionic libc instead of musl/glibc, and it's not the most standards-compliant CRT.  (There have been bugs, such as `memset()` ignoring the byte to fill the buffer and always writing `\0`, and stuff like this.)

**Comment by jkotas** [comment]
Using the same argument, `linux-musl` should not be child of `linux`.

**Comment by jkotas** [comment]
> Can you imagine a lib built a particular way that would work?

No.

**Comment by ericstj** [comment]
What about IL that PInvokes to platform API?  Would a single build work for Linux and Android or do people always need to special case.

Remember: any reuse makes the heirarchy useful. You can always target both in the non-reuse case regardless of heirarchy.

**Comment by jkotas** [comment]
> What about IL that PInvokes to platform API? Would a single build work for Linux and Android 

Yes, you can definitely imagine a single managed binary with PInvokes that works for both Linux and Android.

**Comment by marek-safar** [comment]
I think people have to always a special case to make it clear. Using the opposite argument you are saying that packages like https://www.nuget.org/packages/Microsoft.AspNetCore.App.Runtime.linux-arm64/ should just work on Android?

/cc @pjcollins

**Comment by am11** [comment]
See: https://github.com/dotnet/runtime/issues/3075#issuecomment-377328964

In the early days of linux-musl, thinking of RID as strictly measure of binary compatibility was considered narrow from the perspective of "constituents of an RID-specific nuget package". If the nuget package contain asset which does not depend on CRT and yet Linux specific, that needs to be accommodated by nuget as well.

It is another discussion that RIDs are not scalable: https://github.com/NuGet/Home/issues/5862.

**Comment by eerhardt** [comment]
I think we are just rehashing the arguments in the conversation starting here:

https://github.com/dotnet/runtime/issues/3075#issuecomment-377328964

That is the conversation that changed `android` to be parented under `linux` instead of `unix`. 

> Using the same argument, linux-musl should not be child of linux.

100% agreed. And since `linux-musl` is a child of `linux`, the same reasoning made `android` be a child of `linux`.

**Comment by marek-safar** [comment]
> > Using the same argument, linux-musl should not be child of Linux.

> 100% agreed. And since linux-musl is a child of linux, the same reasoning made android be a child of linux.

They should both point to Linux parent if it was better understood by the tooling. Right now `linux` in RID graph does not mean any Linux but a specific kernel version with very specific userland libraries. That's not the problem of the graph but the fact we provide no good guidance on what for example `linux-x86` RID actually specifies.

What is the correct fix?

Do we have to scan all nuggets and create issues for them to create fake "android-*` packages?

**Comment by ericstj** [comment]
> Right now linux in RID graph does not mean any Linux but a specific kernel version with very specific userland libraries

What makes you say this?  Because of the way that one package decides to use RIDs?  That's not what defines the RID.

**Comment by eerhardt** [comment]
> Because of the way that one package decides to use RIDs? That's not what defines the RID. The RID is just a tool. You decide how you want to use it in each package / system that makes use of it.

One problem that I see is our current [guidance](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids) saying `dotnet publish -r linux-x64` is the "Portable" way to publish an application. This does seem to indicate in our ecosystem that `linux-x64` == `linux-glibc-x64` and `linux-arm` == `linux-glibc-arm`. And I think this is the main reason people (including myself) think the `linux` RID literally equates to `linux-glibc`. It isn't just because "one package" decides to use the RID this way. (Although that "one package" is pretty important, since it is the root of everything .NET Core 😉.)

**Comment by steveisok** [comment]
@ericstj @eerhardt I think I understand enough of the points you're making.  What's weird to me, and it does seem expected, is that for the android RID we are pulling in the Microsoft.AspNetCore runtime pack.

**Comment by eerhardt** [comment]
> is that for the android RID we are pulling in the Microsoft.AspNetCore runtime pack.

Why are you referencing AspNetCore at all?

**Comment by steveisok** [comment]
We aren't.  Both NETCore.App and AspNet runtime packs are being downloaded if you have a `<RuntimeIdentifier>` of `android-arm64`, for example.  That's what seems weird to me.

**Comment by jkotas** [comment]
Yes, that's an annoying shortcut in the SDK. E.g. If you publish self-contained console app on Windows, the SDK will download all runtime packs it knows about (ie both aspnetcore and windowsdesktop) for you even though they are guaranteed to be not used. There is an issue about it somewhere explaining why it was done this way.

**Comment by eerhardt** [comment]
> If you publish self-contained console app on Windows, the SDK will download all runtime packs it knows about

I had an offline conversation with Nick Guerrera on the same issue a few months back, and his response was:

> We don't know if you'll have a transitive ref to asp.net when we download. We have to decide what to restore before we can know that. So it downloads all runtime packs.
We talked about ways to optimize it. If we get any more rutnimes, we will probably have to solve it.

cc @dsplaisted @wli3 - FYI

**Comment by dsplaisted** [comment]
I've filed the following issue to track figuring out how to handle the AspNetCore runtime pack for iOS and Android: https://github.com/dotnet/sdk/issues/11289

**Comment by stephentoub** [comment]
@marek-safar, is this still relevant / are you still working on it?  Thanks.

**Comment by marek-safar** [comment]
I'm not working on this but it's still relevant. If there is enough support to split `linux` RID to `linux-glibc` and `linux-bionic` I can do that.

**Comment by danmosemsft** [comment]
My suggestion if this isn't being actively worked on is to open an issue and close this PR. It can be reopened later. It's hard to deal with so many active PR's.

**Pull request closed without merging**
