### PR TITLE
Add System.Formats.Nrbf to the windowsdesktop transport package

### PR DESCRIPTION
**Pull request by ViktorHofer**
Unblocks the windowsdesktop dependency flow. See https://github.com/dotnet/windowsdesktop/pull/4459#issuecomment-2175892292

### CODE REVIEW

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!

**Comment by ViktorHofer** [comment]
@carlossanlop FYI, this change needs to go in before we snap

**Review by ericstj — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Is it expected for CI to run more than 4 hours in runtime PRs?

**Comment by lewing** [comment]
> CI taking more than 4 hours. That's problematic when trying to get changes like this one in.

you will end up waiting even longer for an official build :(

**Comment by am11** [comment]
browser-wasm leg stuck at `  Determining projects to restore...` (for 55 mins)

unlucky build 🥲

**Comment by ViktorHofer** [comment]
/ba-g we waited long enough and the remaining legs time out for other reasons

**Pull request merged**
