### PR TITLE
Update reflection area names

### PR DESCRIPTION
**Pull request by steveharter**
Per offline discussion we added the "System.Reflection-mono" area but also changed "System.Reflection" to "System.Reflection-coreclr" as there are other similar areas with just "-mono" and "-coreclr". However, there was some discussion on whether this is what we should do or not, or whether we should keep "System.Reflection" for general purpose issues, API discussions and shared "library" code.

Option 1 (this PR)
- System.Reflection-coreclr (general + coreclr specific issues)
- System.Reflection-mono

Option 2 (keep "Reflection")
- System.Reflection (general + coreclr specific issues)
- System.Reflection-mono

Option 3 (all 3)
- System.Reflection
- System.Reflection-coreclr
- System.Reflection-mono

Also note that there is also "Reflection-emit" area but no "Reflection-emit-mono" with the assumption that emit-specific issues for mono will just go into "Reflection-mono"

### CODE REVIEW

**Comment by jkotas** [comment]
I think we should keep `area-System.Reflection`.

Technology-wise, large amount of System.Reflection code is shared between the runtimes and we should work on making this even better. `area-System.Reflection` aligns with this direction.

Organization-wise, we want to be building stronger connections between CoreCLR and Mono sides of the house, ie. having reflection team with CoreCLR and Mono representatives vs. CoreCLR Reflection team and Mono Reflection team. 

We have the same problem for number of other areas. For example, we have `area-System.Runtime.InteropServices` that is the runtime neutral area, and `area-Interop-coreclr` and `area-Interop-mono` for the runtime specific interop issues.

**Comment by steveharter** [comment]
Based on @jkotas I'll assume option 3 for now.

The "-coreclr" may not be widely used, but for consistency and symmetry it's nice to have.

**Comment by danmosemsft** [comment]
> The "-coreclr" may not be widely used, but for consistency and symmetry it's nice to have.

I have no opinion on the proposals, but note that if a label is not used often, and is not consistently applied manually either (eg many issues in the general label are in fact CoreCLr specific), it is likely to have low confidence predictions, which may mean the bot doesn't label it.

**Comment by steveharter** [comment]
Per option 3, I'll rename "System.Reflection-coreclr" back to "System.Reflection" (to keep existing issues in the "general" area) and then add a new "System.Reflection-coreclr" label. Then let @maryamariyan know about the new label so we can re-train the auto labeler.

**Comment by jkotas** [comment]
Is there an existing open issue that would be candidate for `area-System.Reflection-coreclr` ?

The runtime-specific reflection issues often require fixes in the core runtime and need to be done by the people with the right expertise. I am wondering whether it would be better to just use `area-CoreLib-mono`, `area-VM-meta-mono` or `area-VM-coreclr` labels for them.

**Comment by steveharter** [comment]
Leaving as-is (option 2); rename "area-System.Reflection-coreclr" to "area-System.Reflection"

**Pull request closed without merging**
