### PR TITLE
Revert "Enable inlining P/Invokes into try blocks with no catch or fi…

### PR DESCRIPTION
**Pull request by noahfalk**
…lter clauses (#73032)"

This reverts commit 4c07f3dbe5a439e5c6ac66fd14c4fed51aa819ce. We believe it is causing recent CI failures.
See #73247

### CODE REVIEW

**Comment by noahfalk** [comment]
@janvorli @jkotas @am11

**Comment by noahfalk** [comment]
cc @karelz

**Comment by jkoritzinsky** [comment]
@hoyosjs was investigating another PR for the same failure IIRC. Let’s make sure we’re on the same page before merging this.

**Comment by hoyosjs** [comment]
@jkoritzinsky I only disabled the test since it was blocking PRs. The theorized fix was unrelated. I'm looking more a bit at the raw data.

**Review by jkoritzinsky — APPROVED** [review]
If we think this is the cause, we can revert this for now. I actually made the tracking issue for the failures based on the already existing failures of the test in main before merging in the original PR, so your triage seems accurate.

**Comment by filipnavara** [comment]
You should run `runtime-extra-platforms` on the PR.

**Comment by noahfalk** [comment]
We did not validate extra platforms when the original change was checked in so I don't see a reason why we should validate it when the change is being reverted. There are a lot of PR failures happening so I don't think we should hold this up on more validation.

**Comment by filipnavara** [comment]
> We did not validate extra platforms when the original change was checked in so I don't see a reason why we should validate it when the change is being reverted. There are a lot of PR failures happening so I don't think we should hold this up on more validation.

Because some of the linked issues seemed to be related to arm32 builds (unless I misread all the discussion) which started spiking with failures in the same timeframe. Linux ARM32 is part of the extra platforms.

**Comment by noahfalk** [comment]
> Linux ARM32 is part of the extra platforms

It isn't only in extra platforms. This Linux arm32 test for GetGCMemoryInfo has been failing 100+ PRs in runtime pipeline (example https://runfo.azurewebsites.net/view/build/?number=1928987). It may also be causing problems in runtime-extra, but that doesn't seem necessary to hit this.

**Comment by filipnavara** [comment]
The reason I asked for running the extra checks was not necessarily to block the merge on it. I saw it is listed as linux/arm32 on runtime pipeline in the linked issue. I'm a bit puzzles on what actually runs as part of the main checks and what runs only on the extras. For example, I had issue in my Kerberos tests recently that only happened on the arm32 pipelines in the extra runs which leads me to believe that there is only subset of tests run in the runtime pipeline.

Anyway, the reason I asked for the explicit extra run is mainly to see whether the other issues that cropped up in the similar time frame and that are only(?) happening on the extra pipelines disappear with the revert or not.

**Comment by am11** [comment]
All arm32 legs have passed https://github.com/dotnet/runtime/runs/7731954937 (other `extra-platforms` pipeline legs are still running but arm32 legs are green).

**Comment by filipnavara** [comment]
@am11 It appears "Libraries Test Run release coreclr Linux arm Release" didn't run due to some condition not being met. 😞

**Comment by am11** [comment]
The original test `GetGCMemoryInfo` was failing in `coreclr Pri0 Runtime Tests Run Linux arm checked`. That test was disabled in  https://github.com/dotnet/runtime/pull/73477, we should re-enable that test.

**Comment by noahfalk** [comment]
I am re-enabling the test in #73595. I also queued extra-platforms to run in that PR so we can get a complete view of what the current failures look like with both Jeremy's change removed + the GetGCMemoryInfo test re-enabled.

**Pull request merged**
