### PR TITLE
Fix for changed host behaviour on app crash

### LINKED ISSUE #34093: App crashes now crash differently
Apps when they throw from main now terminate in ucrtbase.dll instead of kernelbase.dll.
The problem is that the urctbase exception can't be handled by `__try {} __except(...){}` when manually invoking `hostfxr_run_app` in native code. Which causes problems with InProcess IIS now crashing instead of handling the app failure.

We've narrowed the change to https://github.com/dotnet/runtime/compare/97d1f9698cfa20054a2909ad2e4e9c4ee20a7520..b0351370ccd132d95c97b75312fc36adaacc2664

And the most likely commit to affect anything relevant is dotnet/runtime@b035137

Simple repro with newer hostpolicy.dll vs old hostpolicy.dll:

* `dotnet new console`
* `throw new Exception();` in Main
* Observe event viewer showing fault in ucrtbase instead of kernelbase

Before:
```
Faulting application name: tmp.exe, version: 1.0.0.0, time stamp: 0x5e71cf46
Faulting module name: KERNELBASE.dll, version: 10.0.18362.719, time stamp: 0xb31987d3
Exception code: 0xe0434352
```

After:
```
Faulting application name: tmp.exe, version: 1.0.0.0, time stamp: 0xdb637d68
Faulting module name: ucrtbase.dll, version: 10.0.18362.387, time stamp: 0x4361b720
Exception code: 0xc0000409
```

### PR DESCRIPTION
**Pull request by elinor-fung**
Switch back to only handling synchronous exceptions in host components.
Add native hosting tests for components with unhandled exceptions.

Fix #34093

### CODE REVIEW

**Comment by jkotas** [comment]
cc @am11

**Comment by jkotas** [comment]
Should we delete the central default from https://github.com/dotnet/runtime/blob/master/eng/native/configurecompiler.cmake#L425 and make it CoreCLR specific? `/EHa` does not sound right the right universal default.

**Comment by jkoritzinsky** [comment]
I agree with making it CoreCLR-specific.

**Comment by jkotas** [comment]
You can also delete `/d2Zi+` https://github.com/dotnet/runtime/blob/master/eng/native/configurecompiler.cmake#L416 . It is implied by `/Zi` for quite a while.

**Review by vitek-karas — APPROVED** [review]

**Review by sdmaclea — APPROVED** [review]

**Pull request merged**
