### PR TITLE
[iOS] Reenable skipped StructureToPtr tests

### PR DESCRIPTION
**Pull request by steveisok**
As a result of https://github.com/dotnet/runtime/pull/73013 landing, the skipped StructureToPtr tests can be enabled.

Contributes to https://github.com/dotnet/runtime/issues/73008

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Review by mkhamoyan — APPROVED** [review]

**Comment by steveisok** [comment]
@vargaz These are still failing because it's trying to JIT:

https://github.com/dotnet/runtime/blob/aac729ff906a31f327823587748687c0308a4043/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/Marshal/PtrToStructureTests.cs#L153-L160

https://github.com/dotnet/runtime/blob/aac729ff906a31f327823587748687c0308a4043/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/Marshal/PtrToStructureTests.cs#L164-L171

https://github.com/dotnet/runtime/blob/aac729ff906a31f327823587748687c0308a4043/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/Marshal/StructureToPtrTests.cs#L261-L282

**Comment by steveisok** [comment]
@vargaz `StructureToPtr_Flat_And_Nested_NonBlittableStructure_Success` is still failing.  I'm going to skip that test and move this PR forward.

**Pull request merged**
