### PR TITLE
Ensure side effects get spilled for the various hwintrinsic and simdashwintrinsic nodes

### LINKED ISSUE #54956: Some hardware intrinsic nodes can reorder side effects
Reproduction:

```cs
using System.Numerics;

SideEffects(null, new Vector<int>[] { });

[MethodImpl(MethodImplOptions.NoInlining)]
static Vector<int> SideEffects(Vector<int>* a, Vector<int>[] b)
{
    var v = Vector.AndNot(*a, b[0]);

    return v;
}
```
Actual result:
```scala
> dotnet run
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
```
Expected result:
```scala
> dotnet run
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
```

This happens because of this code:
https://github.com/dotnet/runtime/blob/e823eb65de31ddec41f6452f701ca97d8d8eff35/src/coreclr/jit/simdashwintrinsic.cpp#L320-L323

Which does not account for side effects. Important note: since the importation code does not propagate the side effect flags properly (yet), they cannot be relied on when determining whether it is safe to swap at that point.

Possible solutions:
1) Aggressively spill to temps - bad from CQ & TP standpoints.
2) Use `GTF_REVERSE_OPS` - bad from the standpoint that this flag should be removed.
3) Fix the operands up in LIR, where the tree walk no longer determines the execution order - probably cleanest but also most complex solution.

Note: the problematic code will become less centralized after #53450 is merged. See my review notes over there.

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #54956

### CODE REVIEW

**Comment by tannergooding** [comment]
@fanyang-mono, could you point me to where Mono makes decisions about side effects?

It looks like it has the same issue where its incorrectly re-ordering parameters for some intrinsics.

**Comment by fanyang-mono** [comment]
> @fanyang-mono, could you point me to where Mono makes decisions about side effects?
> 
> It looks like it has the same issue where its incorrectly re-ordering parameters for some intrinsics.

I was able to reproduce the issue locally with fullaot. I need some time to investigate and will get back to you tmr.

**Comment by vargaz** [comment]
This will fix the mono failure:
https://github.com/dotnet/runtime/pull/70308

**Comment by SamMonoRT** [comment]
https://github.com/dotnet/runtime/pull/70308 has merged, we should try re-running failing mono lanes

**Review by fanyang-mono — APPROVED** [review]

**Comment by tannergooding** [comment]
> They need to be dealt with in some way, as it is very surprising (-- prone to creating subtle bugs) for a gtNewXYZ function to potentially silently reorder operands (at a minimum, it needs to assert that it can do that safely, with gtCanSwapOrder(op1, op2)).

I agree, I'll log a new issue to track them since they are impacted a different way and will require different handling.

> Additionally, it would be nice to add tests for all affected intrinsics (not just AndNot).

I'll work on adding these.

**Comment by tannergooding** [comment]
CC. @dotnet/jit-contrib

**Comment by tannergooding** [comment]
Ping @dotnet/jit-contrib 

Would be good to get this in for 7 to help ensure code works as users expect without accidental side effect re-ordering.

**Review by AndyAyersMS — COMMENTED** [review]
Seems risky to selectively spill like this. If you have a bigger tree of intrinsics where many leaf operands can throw it seems like you could still reorder exceptions between operands at different levels.

**Comment by tannergooding** [comment]
@AndyAyersMS do you have an example? Shouldn't `impSpillSideEffect` detect when a nested node also has side effects considering we rely on it for other phases of import?

**Comment by AndyAyersMS** [comment]
We don't generally rely on it elsewhere; it is mainly called from `impSpillSideEffects` which is typically called with either NONE or ALL.

Test case would be something along these lines (might need to fiddle a bit to get it right). Call with `d == 0`.
```C#
    [MethodImpl(MethodImplOptions.NoInlining)]
    static Vector128<int> SideEffectsTree_Sse2_ShiftLeftLogical(Vector128<int>[] left, byte* right, int d)
    {
        if (Sse2.IsSupported)
        {
            return Sse2.ShiftLeftLogical(Sse2.ShiftLeftLogical(left[0], *right), 5 / d));
```

**Comment by tannergooding** [comment]
@AndyAyersMS, not sure I understand.

`impSpillSideEffects` effectively just does `impSpillSideEffect` for each stack argument from `0` (bottom) to `chkLevel` (which is frequently `CHECK_SPILL_ALL`).

So for `CHECK_SPILL_ALL` with `2` operands, it will spill `op1`, then `op2`; and only spill if that stack entry is marked as `GTF_GLOB_EFFECT` or `GTF_SIDE_EFFECT` -or- we're spilling global effects and its an address exposed local.

--------------------

For most of these intrinsics we have a binary case where we need to swap operand 1 and 2. So we only check if `op1` needs to be spilled. We shouldn't also need to check if `op2` needs to be spilled because it will be evaluated after `op1` if `op1` is spilled first.

`impSpillSideEffects` itself wouldn't catch anything else since it doesn't do any additional checks on top outside `impSpillSpecialSideEff()` which we should never have since that only applies to exception objects. It would only potentially spill `op2` when its unnecessary since it will always be the "next" operand in the evaluation order.

**Comment by tannergooding** [comment]
Hmmm. I guess, if the stack had 3 operands and the unrelated operand had side effects that could be problematic. In which case we'd want `impSpillSideEffects(true, verCurrentState.esStackDepth - 2, "Reason")`....

Is that a concern here? The stack should normally be balanced, right?

**Comment by AndyAyersMS** [comment]
Looking at it some more I think what you have will be ok, if there are more levels to the tree, you'll just accumulate more op1 spills along the way.

Eg if abstractly there is some tree like `(% (% a b) c)` where the expansion of `%` wants to reverse operand order (call this `%r`), you'll emit
```
t0  = a;
t1  = (%r b, t0);
... = (%r c, t1);

**Review by AndyAyersMS — APPROVED** [review]

**Pull request merged**
