### PR TITLE
Rename CLR_CMAKE_PLATFORM* CLR_CMAKE_HOST*

### PR DESCRIPTION
**Pull request by sdmaclea**
The term platform was ambiguous. Migrate to using common terminology for
cross compilation.

Host is the platfrom which will execute the code
Target is the platform which will be debugged or for which code will be generated.

In most cases HOST == TARGET.  The exceptions are the cross component crossgen
tools and the future cross DAC.

This patch is a simple rename of CLR_CMAKE_PLATFORM* to CLR_CMAKE_HOST*.  Future patches will switch some CLR_CMAKE_HOST references to CLR_CMAKE_TARGET as needed for the cross DAC work.

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Review by jkotas — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]
Looks good. Looking we also have `PAL_CMAKE_PLATFORM_ARCH_*`. Should this also be `PAL_CMAKE_HOST_ARCH*`

**Comment by sdmaclea** [comment]
@hoyosjs I saw the same thing.  I'll create a separate PR.

**Comment by jkotas** [comment]
> Should this also be PAL_CMAKE_HOST_ARCH*

Or just `CMAKE_HOST_ARCH*`. I do not see a good reason for having a separate name for PAL.

**Comment by sdmaclea** [comment]
> Or just CMAKE_HOST_ARCH*

This _might_ conflict with a CMAKE define.  The `CLR_` prefix guarantees uniqueness.  It doesn't make a lot of sense for the PAL though if we are using the PAL outside of the runtime.

I created the PAL patch it currently affects two files....

**Comment by jkotas** [comment]
We are not using the PAL outside of the runtime. The PAL is for CoreCLR only.

**Comment by sdmaclea** [comment]
OK....  I thought it used to be mirrored somewhere....  CoreRT?

**Comment by jkotas** [comment]
CoreRT has its PAL. There are folks who copied some of it for their Windows->Unix ports (e.g. https://github.com/microsoft/ChakraCore/tree/master/pal/src), but those copies are not automatically mirrored. Everybody maintains their own with their own custom tweaks.

**Pull request merged**
