### PR TITLE
JIT: Fix Swift multireg stores in presence of `GT_RELOAD`

### PR DESCRIPTION
**Pull request by jakobbotsch**
I accidentally merged #99704 before the jitstressregs jobs I had kicked off were actually done running. This fixes an issue caught by those pipelines.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @amanasifkhalid

**Review by amanasifkhalid — APPROVED** [review]
LGTM if CI passes. Thanks!

**Comment by jakobbotsch** [comment]
There is another failure, but it looks LSRA related and unrelated to the specifics of Swift handling. Going to open a separate issue for it.

**Pull request merged**
