### PR TITLE
Add Nick to fabric-bot config

### PR DESCRIPTION
**Pull request by ericstj**

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]
Do we need to do anything for pod-owner name? today we use eric-maryam-tarek. or this is automatically handled by this addition?

**Review by eerhardt — APPROVED** [review]

**Comment by ericstj** [comment]
I believe this should make issuesof.net update as well @terrajobst?

**Comment by terrajobst** [comment]
I don't think so, @jeffhandley uses `area-owner.json`:

https://cs.github.com/terrajobst/issuesof.net/blob/938a19ed7e29994fe96ec7694013888ddd9be094/src/IssueDb/Crawling/CrawledAreaOwnerFile.cs#L38

**Review by Nick-Stanton — APPROVED** [review]

**Review by joperezr — APPROVED** [review]

**Comment by ericstj** [comment]
> I don't think so, @jeffhandley uses [area-owners.json](https://github.com/dotnet/runtime/blob/main/docs/area-owners.json):

I see, I'll update that JSON file as well.

**Pull request merged**
