### PR TITLE
JIT: add PGO random stress testing support

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Enable the previously added RandomGDV for various PGO CI pipelines.

Add a new `JitRandomEdgeCount` mode to provide random but plausible
PGO data for edge counters. Because of the way sparse edge counting works
this data will most ofen end up providing a consistent set of block counts.

Enable this mode in PGO pipelines, and also a mode that randomzies both
counts and GDV selections.

### CODE REVIEW

**Review by BruceForstall — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Looks like a couple of asserts in libraries tests so far.

The runtime tests don't seem to be using the new modes, there are only the existing 4 modes per isa/os. Not sure what's up there.

**Comment by AndyAyersMS** [comment]
Non-pgo failures look like known issues. I will open issues for the new pgo mode failures.

**Pull request merged**
