### PR TITLE
Harden native gate thread against affinity mask growth

### PR DESCRIPTION
**Pull request by kouvel**
Hardened ThreadpoolMgr::GateThreadStart against the possibility that the observed group-local affinity mask contains set bits at positions higher than the total group-local CPU count that was captured during earlier initialization.

This fixes customer-reported crashes which have occurred on multi-group machines with heterogenous CPU counts across groups (but the same crash can probably also occur on single-group VMs if CPUs are hot-added and are then manually added to the process affinity mask).

### CODE REVIEW

**Review by ChrisAhna — APPROVED** [review]
:shipit:

**Comment by kouvel** [comment]
For some reason it still says an approving review is required even though @ChrisAhna has approved it. @mangod9 could you also approve?

**Review by mangod9 — APPROVED** [review]

**Comment by mangod9** [comment]
yeah that is weird, I do see @ChrisAhna is a member of .net platform.

**Comment by kouvel** [comment]
Thanks, that worked

**Pull request merged**
