### PR TITLE
[JIT/ARM64] Fix few SP-based instruction encoding issues

### PR DESCRIPTION
**Pull request by filipnavara**
- `INS_lea` encoded as `add reg1, reg2, rsvdReg` used wrong instruction format when `reg2` is SP. It ended up encoding the instruction as using `xzr` instead.
- `emitIns_R_R_S_S` was converting SP register with `encodingSPtoZR` too early, which caused assert in the `useRegForAdr` code path.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@kunalspathak maybe you can review?

**Comment by kunalspathak** [comment]
The changes looks good, but wondering how you discovered this problem? Is there a test case you can add?

**Comment by filipnavara** [comment]
> The changes looks good, but wondering how you discovered this problem? Is there a test case you can add?

I don't think there's a way to trigger it with current code in the JIT, at least not a trivial one.

It was discovered in test runs of https://github.com/dotnet/runtime/pull/107617. I don't remember what code hit the assert. Some tests in System.Runtime.Tests end up hitting the `xzr`/`sp` mistake. The trigger is the following change: https://github.com/dotnet/runtime/compare/main...filipnavara:arm64-compact-unwind-3?expand=1#diff-30076431057df5c991b5e11659842a02ece8bb0669754fd1f42131272305bcc0R2810-R2819 (along with forcing FP/LR on top of frame which is currently mostly done only in stress tests).

**Review by kunalspathak — APPROVED** [review]
LGTM

**Pull request merged**
