### PR TITLE
Improve loop cloning throughput

### LINKED ISSUE #52480: Loop cloning recomputes reachability / dominators too much
`optCloneLoop` calls `fgUpdateChangedFlowGraph` for each loop cloned, which recomputes reachability and dominators sets. Is this necessary? Can we defer doing this recomputation until after all the loops are cloned?

### PR DESCRIPTION
**Pull request by BruceForstall**
1. Cloning was rebuilding reachability and dominators after every
cloned loop. This is unnecessary; only rebuild it once, after all
the loops in the function are cloned.
2. Early out if we don't detect any clonable loops.

No asm diffs

Fixes #52480

### CODE REVIEW

**Comment by BruceForstall** [comment]
@AndyAyersMS @dotnet/jit-contrib PTAL

**Review by AndyAyersMS — APPROVED** [review]
LGTM.

**Pull request merged**
