### PR TITLE
Update the sdk versions to get the latest arcade changes

### PR DESCRIPTION
**Pull request by Anipik**

### CODE REVIEW

**Review by ericstj — APPROVED** [review]

**Comment by ViktorHofer** [comment]
just curious, is there a specific change that you want to consume?

**Review by ViktorHofer — APPROVED** [review]

**Comment by Anipik** [comment]
> just curious, is there a specific change that you want to consume?

CompileDesignTimeChange and merge conflict was not resolved properly for the arcade where we end up using the wrong versions. Hence the restore is still removing the platform.

**Comment by ViktorHofer** [comment]
Ready to merge?

**Comment by ViktorHofer** [comment]
I requested a rerun on the allconfigurations leg.

**Comment by Anipik** [comment]
> I requested a rerun on the allconfigurations leg.

The ci is broken until https://github.com/dotnet/runtime/pull/44373/

**Comment by ViktorHofer** [comment]
Which of the changes in this PR are the cause for the CI to be broken? Or are you saying CI is completely broken in all PRs?

**Pull request merged**
