### PR TITLE
OnBeforeBuild delegate to invoke actions just before building the ServiceProvider

### PR DESCRIPTION
**Pull request by thomhurst**
OnBeforeBuild delegate to invoke actions just before building the ServiceProvider. This would enable more advanced orchestration of service registrations, such as Decorators, without having to add them in a particular order.

### CODE REVIEW

**Comment by Wraith2** [comment]
Is there an approved api review for this?

**Comment by thomhurst** [comment]
> Is there an approved api review for this?

Nope. This is me suggesting the change.

**Comment by Wraith2** [comment]
You will need to follow the api review process and get approval before your api can be added. https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md

**Comment by davidfowl** [comment]
Right. There’s an entire process to follow to add new  features and APIs. Also describing scenarios in the issue so we can see if there’s any overlap with other issues.

**Pull request closed without merging**
