### PR TITLE
Remove AD0001 NoWarn from Microsoft.Extensions.Logging.Abstractions project

### LINKED ISSUE #90357: ProvideCorrectArgumentsToFormattingMethodsAnalyzer throws IndexOutOfRangeException when building Microsoft.Extensions.Logging.Abstractions
### Description

When building Microsoft.Extensions.Logging.Abstractions I see the diagnostic
```
error AD0001: Analyzer 'Microsoft.NetCore.Analyzers.Runtime.ProvideCorrectArgumentsToFormattingMethodsAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'
```

I'll suppress this when enabling AD0001 as warning. This issue will track fixing that analyzer and removing the warning suppression

### Reproduction Steps

Remove AD0001 from Microsoft.Extensions.Logging.Abstractions.csproj and build it.

### Expected behavior

Builds without warning.

### Actual behavior

Warning as above

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by buyaa-n**
The analyzer bug that was causing https://github.com/dotnet/runtime/issues/90357 fixed and the changes flowed to the runtime

Fixes https://github.com/dotnet/runtime/issues/90357

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]

**Comment by tarekgh** [comment]
@buyaa-n I assume we'll need to backport this to rc2, right? 

CC @jeffhandley

**Comment by buyaa-n** [comment]
> I assume we'll need to backport this to rc2, right?

The analyzer fix backported to rc2, not sure if we need to backport this change

**Comment by tarekgh** [comment]
> The analyzer fix backported to rc2, not sure if we need to backport this change

I prefer to backport this one too. Note, 8.0 is LTS and expects some servicing fixes on such projects. Keep disabling such warning is risky when we fix anything in that project. At the same time, the fix here is safe as we are not touching any product code.

**Comment by buyaa-n** [comment]
Sounds good to me, I guess we can run the porting bot after merge

**Comment by tarekgh** [comment]
> Sounds good to me, I guess we can run the porting bot after merge

Just ensure the analyzer fix is already flow to the 8/0 release branch. otherwise, this will fail there.

**Review by jeffhandley — APPROVED** [review]
Thanks for seeing this through. I was on the fence regarding the net8 backport, but @tarekgh's reasoning sounds good to me. Once the backport PR is ready, let me know and I'll approve it.

**Comment by carlossanlop** [comment]
No, not blocked, but the CI keeps getting restarted because more commits get added. I can merge it now.

**Pull request merged**
