### PR TITLE
Rebaseline llvm-libunwind tree

### PR DESCRIPTION
**Pull request by am11**
The purpose of this PR is to extract all the changes we have on top of upstream/original copy: https://github.com/llvm/llvm-project/tree/llvmorg-9.0.0/libunwind in a separate commit. This will make it possible bring llvm-libunwind to the same plan as other external dependencies trees under `src/native/external` directory in a followup PR.

<ins>Please merge it without squashing the commits, otherwise it will defeat its purpose.</ins>

* first commit deletes the directory
* second commit extracts the upstream version:

    ```sh
    # bash on Ubuntu
    $ pushd src/coreclr/nativeaot
    $ curl -sSL https://github.com/llvm/llvm-project/archive/llvmorg-9.0.0.tar.gz |\
        tar xzf - llvm-project-llvmorg-9.0.0/libunwind --strip-components=1
    $ popd
    ```
* third commit is a copy over of current version of `src/coreclr/nativeaot/libunwind`, which contain all the changes transipred since the initial bringup in https://github.com/dotnet/corert/pull/2293. It includes commits listed in:
   * https://github.com/dotnet/corert/commits/2dfab60ad1c3d0fe0241b5e2503fb3f8d33e4c22/src/Native/libunwind
   * https://github.com/dotnet/runtimelab/commits/9a766d3ae49e332bdc6c6545f5d2f02570cf97e2/src/coreclr/src/nativeaot/libunwind
   * https://github.com/dotnet/runtimelab/commits/9a766d3ae49e332bdc6c6545f5d2f02570cf97e2/src/coreclr/nativeaot/libunwind
   * https://github.com/dotnet/runtime/commits/aafa91036e1efd3d4dcb67eeb261cb6d8f774685/src/coreclr/nativeaot/libunwind

I have listed all those commits in description of third commit.

Contributes to #72344

### CODE REVIEW

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!

**Comment by jkotas** [comment]
cc @VSadov 

@am11 Should this be merged as `rebase and merge` ?

**Comment by am11** [comment]
> @am11 Should this be merged as `rebase and merge` ?

Yes please. We just need a reference to the third commit from main branch, for bookkeeping additional modifications in version file. In next PR, I'll move this directory under src\native\external and add the version file.

**Comment by VSadov** [comment]
@am11 - very nice! Thanks!

BTW, https://github.com/dotnet/runtime/pull/71187 has some libunwind fixes, but I think the  llvm-libunwind already has similar fixes, so it may not have any impact here.

**Comment by VSadov** [comment]
`rebase and merge` is "Not enabled for this branch". I assume someone has the necessary permissions?

**Review by VSadov — APPROVED** [review]

**Pull request merged**
