### PR TITLE
Update System.Drawing.Common index to get latest package for harvesting

### PR DESCRIPTION
**Pull request by safern**
All configurations libraries build is failing with error:

```
F:\workspace\_work\1\s\src\libraries\pkg\test\testPackages.proj(215,5): error : Validation Failed: System.Drawing.Common is harvesting assets from package version 4.6.1 which is not the latest for that package release. Latest package version from that release is 4.6.2. In order to fix this, run `dotnet msbuild System.Drawing.Common.pkgproj /t:UpdatePackageIndex /p:UpdateStablePackageInfo=true`
```

This fixes that issue by updating the package index to list the latest stable drawing packages.

### CODE REVIEW

**Review by joperezr — APPROVED** [review]
LGTM, Thanks for fixing. As an FYI we should think about porting this change to release branches as it may be pertinent in those too.

**Comment by safern** [comment]
> As an FYI we should think about porting this change to release branches as it may be pertinent in those too.

That's right. I'll open a PR to those. In release/2.1 we don't harvest any assets for System.Drawing.Common so I think it would only make sense for release/3.0 and release/3.1

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Thanks, what about the error when executing the task in the error message that you mentioned in the standup?

**Comment by safern** [comment]
> Thanks, what about the error when executing the task in the error message that you mentioned in the standup?

I was missing to build the package itself. @joperezr is going to put up a fix to add a new target that hooks up build as a first step to update harvesting.

**Comment by safern** [comment]
Libraries all configuration leg is green. Will merge to unblock other PRs.

**Pull request merged**
