### PR TITLE
Small tweak for branch optimizer

### PR DESCRIPTION
**Pull request by EgorBo**
A couple of diffs are expected

### CODE REVIEW

**Comment by EgorBo** [comment]
@dotnet/jit-contrib PTAL, simple change wit [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=491936&view=ms.vss-build-web.run-extensions-tab) (a few CSE/bound check elimination regressions due to IsUnsigned change I have an idea to mitigate in VN separately, but should be overall more improvements than regressions.

**Comment by EgorBo** [comment]
@dotnet/jit-contrib In case if anyone is still alive 🙂 trivial change with [nice diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=505408&view=ms.vss-build-web.run-extensions-tab), almost no regressions

**Review by amanasifkhalid — APPROVED** [review]
Nice diffs, indeed! LGTM, but you may want to wait for feedback from others, too.

**Review by BruceForstall — APPROVED** [review]

**Comment by cincuranet** [comment]
Some regressions:
- https://github.com/dotnet/perf-autofiling-issues/issues/26481

cc @EgorBo

**Pull request merged**
