### PR TITLE
[wasm] Fix Vector128 SIMD fmin and fmax

### LINKED ISSUE #92885: [browser] TensorPrimitivesTests.ConvertToHalf_SpecialValues `-Infinity`
### Error Blob

```json
{
  "ErrorMessage": "[FAIL] System.Numerics.Tensors.Tests.TensorPrimitivesTests.ConvertToHalf_SpecialValues",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=424283&view=results

### Reproduction Steps

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-92871-merge-34417cc5806d46a084/normal-System.Numerics.Tensors.Tests/1/console.c43b761f.log?helixlogtype=result)

```
fail: [FAIL] System.Numerics.Tensors.Tests.TensorPrimitivesTests.ConvertToHalf_SpecialValues(tensorLength: 15)
info: Assert.Equal() Failure
info: Expected: NaN
info: Actual:   -Infinity
info:    at System.Numerics.Tensors.Tests.TensorPrimitivesTests.ConvertToHalf_SpecialValues(Int32 tensorLength)
info:    at System.Object.InvokeStub_TensorPrimitivesTests.ConvertToHalf_SpecialValues(Object , Span`1 )
info:    at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object , BindingFlags , Binder , Object[] , CultureInfo )
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=424283
**Error message validated:** `[FAIL] System.Numerics.Tensors.Tests.TensorPrimitivesTests.ConvertToHalf_SpecialValues`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/2/2023 12:36:04 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[425496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425496)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425496&view=ms.vss-test-web.build-test-results-tab&runId=9373512&resultId=162338)||
|[425041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425041)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425041&view=ms.vss-test-web.build-test-results-tab&runId=9351792&resultId=162338)||
|[424643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424643)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424643&view=ms.vss-test-web.build-test-results-tab&runId=9340484&resultId=162338)|dotnet/runtime#92226|
|[424283](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424283)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424283&view=ms.vss-test-web.build-test-results-tab&runId=9331020&resultId=162338)|dotnet/runtime#92871|
|[424272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424272)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424272&view=ms.vss-test-web.build-test-results-tab&runId=9330908&resultId=162338)||
|[423892](https://dev.azure.com/dnceng-public/public/_build/results?buildId=423892)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=423892&view=ms.vss-test-web.build-test-results-tab&runId=9322378&resultId=162338)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|6|

### PR DESCRIPTION
**Pull request by radekdoulik**
Fix https://github.com/dotnet/runtime/issues/92885

Min and max now use NaN propagating SIMD instructions, `f32x4.min`, `f64x2.min`, `f32x4.max` and `f64x2.max`.

Example emitted code:

    ...
    f32x4.min    [SIMD]
    v128.store    [SIMD]

for

    return Vector128.Min(/* Vector128<float> */ v1, v2);

### CODE REVIEW

**Comment by radekdoulik** [comment]
I think we can try to unify all the platforms to use llvm.[maximum|minimum].[v4f32|v2f64] intrinsics for v128. Lets keep it simple for this PR so that it is easier to backport to NET8.

**Comment by lewing** [comment]
@radical @ilonatommy are the hybrid globalization tests failing in main?

**Review by vargaz — APPROVED** [review]

**Comment by radekdoulik** [comment]
Failed tests are hybrid globalization, the ` runtime (Build browser-wasm linux Release AllSubsets_Mono_RuntimeTests monointerpreter) In progress — This check has started...` is:
```
##[error]
,##[warning]Agent  was purged, cancelling the pipeline.
,##[warning]Received request to deprovision: The request was cancelled by the remote provider.
Agent: NetCore-Public 140
Started: Yesterday at 6:11 PM
Duration: 1h 42m 59s
```

**Pull request merged**
