### PR TITLE
Fix missing version info in host binaries on Unix

### LINKED ISSUE #34505: libhostpolicy.so and libhostfxr.so are missing build hash string
I was looking into an issue and tried to get commit hashes from these two libraries using strings command piped to `grep "@(#)"`. It didn't display anything for these two.
These were from `shared/Microsoft.NETCore.App/5.0.0-preview.4.20202.18` folder.

### PR DESCRIPTION
**Pull request by elinor-fung**
Fix #34505 

With this:
```
> strings artifacts/bin/linux-x64.Release/corehost/*.so | grep '@(#'
@(#)Version 42.42.42.42424 @Commit: 805cd002a7e5dd4647efae50a6b5d16f713da23e
@(#)Version 42.42.42.42424 @Commit: 805cd002a7e5dd4647efae50a6b5d16f713da23e
@(#)Version 42.42.42.42424 @Commit: 805cd002a7e5dd4647efae50a6b5d16f713da23e
```
The three occurrences are `libhostfxr`, `libhostpolicy`, and `libnethost`. `dotnet` also has the version as expected and `apphost` does not have the version as expected.

### CODE REVIEW

**Review by vitek-karas — APPROVED** [review]

**Review by lpereira — APPROVED** [review]
LGTM, although it might be a good idea to use [CMake's SOVERSION](https://cmake.org/cmake/help/v3.6/prop_tgt/SOVERSION.html) property in shared libraries, too.

**Comment by elinor-fung** [comment]
Hm, yeah, looks like we don't use `SOVERSION` / `VERSION` right now. Just read a bit about it - probably worth looking into. Not sure how that plays with the current versioning through resources we do on Windows though.

**Comment by janvorli** [comment]
@lpereira so you are suggesting that we should consider adding version to the filename of the libraries?

**Comment by lpereira** [comment]
On Unix, it's customary to have the ABI version in the library name (e.g. `libc.so.6` for ABI version 6). 

It's not easy to change now because that's a published interface, but it would have been easier to, for instance, look for `libhostfxr.so.2` and assume it has the new-style interface rather than opening `libhostfxr.so` and probing for symbols.

Symbolic links can be used to point to the latest version, too.  So we probably don't even need `hostfxr` to locate `hostpolicy`, we can just link -- and not even look ourselves for it with `dlopen()` and friends -- with `libhostpolicy.so.5`, and let the dynamic loader do the work of finding the latest version of that. (For instance, that could be `/usr/lib64/dotnet/libhostpolicy.so.5` -> `/usr/lib64/dotnet/libhostpolicy.so.5.0.0`, if we used the SOVERSION and VERSION to match the .NET version.)

These changes would make .NET look less alien in Unix, IMHO.

**Pull request merged**
