### PR TITLE
Simple sideloaded profile guided optimization support

### PR DESCRIPTION
**Pull request by AndyAyersMS**
1. Add code so the runtime can read profile data from a text file and then
make this data available to the jit, so it will be easier to test the jit's
behavior when profile data is available.
2. Add code so the runtime can create profile text files by telling the jit
to insert probes into jitted code that write into a persistent buffer, which
is saved to text at shutdown. This is mainly intended to make creation of the
sideloaded profile data files easier, since their internal structure must
exactly match artifacts from jitted methods.
3. Add a mode where jit-instrumented Tier0 code can feed counts into Tier1
jitting. This is an experiment to see what benefit, if any, might accrue from
having  profile data available for Tier1 jitting.

External format is text so it can be edited by hand or checked into the repo
alongside tests. Binary format would be more compact but opaque.

In all cases the jit internally sees a profile buffer identical to the one it
sees with IBC; the only minor changes in the jit are to initialize the count
field of each probe entry to zero and to only emit the entry helper call for
prejitted IBC.

Only root methods are instrumented, and only root method blocks are given
profile weights. Broadening to handle inlinees is future work, facilitated by
the new capabilities added here.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Revised version of #36317.

cc @dotnet/jit-contrib @davidwrighton

**Comment by AndyAyersMS** [comment]
Arm failure is unrelated; seems to be dup of #36850.
```
    GC/API/GC/AddThresholdTest/AddThresholdTest.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/GC/API/Reports/GC.API/GC/AddThresholdTest/AddThresholdTest.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun AddThresholdTest.dll ''
      Warning: newly-allocated dummy ended up in gen 1
      Warning: newly-allocated dummy ended up in gen 1
      Warning: newly-allocated dummy ended up in gen 1
      Warning: newly-allocated dummy ended up in gen 1
      2 2
      ThresholdTest Failed
      
      Test Failed
      Expected: 100
      Actual: 1
```

**Review by BruceForstall — APPROVED** [review]
LGTM

**Comment by AndyAyersMS** [comment]
@davidwrighton take a look when you can

**Review by davidwrighton — APPROVED** [review]
This looks great!

**Comment by AndyAyersMS** [comment]
Experimental leg fails on superpmicollect. Will look into this separately. Mono failure is some kind of infrastructure glitch when cloning a repo, will ignore.

```
+ git clone /__w/1/Checkout_bundle/Checkout.bundle .
error: inflate: data stream error (incorrect data check)
error: index-pack died
fatal: update_ref failed for ref 'HEAD': cannot update ref 'HEAD': trying to write ref 'HEAD' with nonexistent object ***
```

**Pull request merged**
