### PR TITLE
Simplify connection usability logic 

### PR DESCRIPTION
**Pull request by geoffkizer**
Factor some duplicated logic into a shared routine, IsUsableHttp11Connection.

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by stephentoub** [comment]
I didn't see this PR.  I have a few concerns.

We explicitly had this duplicated logic to do different things when checking for connection usability when we were about to use a connection vs when just checking the status of connections in the pool.  We explicitly avoided doing read-aheads in the latter case for two reasons:
1. Having the pending read on the connection makes it much more likely we'll incur an exception if we close that connection; if we instead just poll.  Not using read-ahead was actually a bug fix several releases ago, which this appears to regress.
2. Issuing the read-ahead for all connections in the pool means we end up pinning the read buffer for every connection in the pool.  That's potentially a lot of large pinned buffers that lead to heap fragmentation.

**Comment by stephentoub** [comment]
Nevermind; I missed that IsUsable was passing in false for async.  Looks good.

**Comment by geoffkizer** [comment]
Yeah, to be clear, I think when we added the async = false path, the rationale for having these be separate went away.

**Pull request merged**
