### PR TITLE
[workloads] Mark the windows runtime packs workload as abstract

### PR DESCRIPTION
**Pull request by lewing**
I'm not sure this is correct but opening for comment

### CODE REVIEW

**Comment by steveisok** [comment]
@marcpopMSFT is this even needed anymore?  This was primarily for VS, right?

**Comment by lewing** [comment]
was it just to make sure we had runtim packs when we were less targeted with the same version setting?  If so they can probably be removed completely but can definitely be abstract

**Comment by marcpopMSFT** [comment]
The runtime pack workloads were created so that we'd have the windows runtime packs in VS for maui when inserting prerelease versions (so folks didn't need the secure feeds).

They were made abstract so they wouldn't show up in the dotnet workload search because I don't think we meant for them to be installable via the CLI.  @joeloff VS setup will still install abstract workloads, correct?

**Comment by joeloff** [comment]
Correct. Abstract workloads are simply converted to component groups in VS to hide them from the IC tab, similar to how we'd hide abstract workloads on the CLI from `search` and `install`. Something though has to depend or extend the abstract workload.

**Comment by marcpopMSFT** [comment]
There's an explicit dependency in the netcrossplat workloads in VS on runtimes.windows which is how it gets pulled in (it's for preview channel only since this shouldn't be needed once the runtime packs ship.

**Comment by lewing** [comment]
so then I assume marking them as abstract is ok?  if we don't they show up as installable from the command line

**Review by steveisok — APPROVED** [review]

**Comment by steveisok** [comment]
> so then I assume marking them as abstract is ok? if we don't they show up as installable from the command line

Yeah, I think so.

**Pull request merged**
