### PR TITLE
[mono][interp] Fix GetType called on ptr constrained to Nullable`

### LINKED ISSUE #61007: .NET 6.0 blazor wasm project reports an incorrect type
### Describe the bug
Blazor wasm .NET 6.0 project reports an incorrect variable type. The type is correctly reported for blazor server (.NET 5.0 and .NET 6.0) as well as blazor wasm .NET 5.0 apps, but not for blazor wasm .NET 6.0 project.

### To Reproduce

A repository that reproduces the issue can be found at:
https://github.com/Stamo-Gochev/blazor-type-issue

It contains a [component](https://github.com/Stamo-Gochev/blazor-type-issue/blob/master/BlazorTypeIssue/RazorClassLibrary1/Component1.razor.cs) in a [razor class library](https://github.com/Stamo-Gochev/blazor-type-issue/tree/master/BlazorTypeIssue/RazorClassLibrary1) that is used by all project types to compare the output. 

The component uses a [generic argument](https://github.com/Stamo-Gochev/blazor-type-issue/blob/master/BlazorTypeIssue/RazorClassLibrary1/Component1.razor.cs#L16-L23) for its `Data` parameter and checks if the type of it is contained in a [list of predefined types](https://github.com/Stamo-Gochev/blazor-type-issue/blob/master/BlazorTypeIssue/RazorClassLibrary1/Component1.razor.cs#L25-L41) and renders the [result](https://github.com/Stamo-Gochev/blazor-type-issue/blob/4654c39b67a84b6457c872dc4a63659892328f58/BlazorTypeIssue/RazorClassLibrary1/Component1.razor#L13).

Steps to reproduce:
1. Clone the repo
2. Run the [BlazorWasmAppNet60](https://github.com/Stamo-Gochev/blazor-type-issue/tree/master/BlazorTypeIssue/BlazorWasmAppNet60) project
3. Open the [Index.razor](https://github.com/Stamo-Gochev/blazor-type-issue/blob/master/BlazorTypeIssue/BlazorWasmAppNet60/Client/Pages/Index.razor#L5) page and observe its output.

> **Note:** The repo also contains [tests projects](https://github.com/Stamo-Gochev/blazor-type-issue/tree/master/BlazorTypeIssue) for blazor server .NET 5.0 and .NET 6.0 apps as well as a blazor wasm .NET 5.0 app. You can use them to compare the output by looking at their `/Pages/Index.razor` file. 

### Expected behavior
The [Index.razor](https://github.com/Stamo-Gochev/blazor-type-issue/blob/master/BlazorTypeIssue/BlazorWasmAppNet60/Client/Pages/Index.razor) page is expected to print:

> BlazorWasmAppNet60
item has predefined type: True

This is also the output for **all** other project types - blazor server .NET 5.0, blazor server .NET 6.0 and blazor wasm .NET 5.0.

> BlazorServerAppNet50
item has predefined type: True

> BlazorServerAppNet60
item has predefined type: True

> BlazorWasmAppNet50
item has predefined type: True

### Actual behavior
The [Index.razor](https://github.com/Stamo-Gochev/blazor-type-issue/blob/master/BlazorTypeIssue/BlazorWasmAppNet60/Client/Pages/Index.razor) page returns:

> BlazorWasmAppNet60
item has predefined type: False <- this should be True as in all other projects

### Further technical details
- ASP.NET Core version - .NET 6.0 RC 2
- Visual Studio 2022 Preview 7
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files (x86)\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files (x86)\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

</details>

### PR DESCRIPTION
**Pull request by BrzVlad**
We were statically optimizing this call to return the actual constrained class type, which is incorrect for nullables, because boxing of a nullable (as part of the constrained call) actually creates an object with the type of the nullable's value (or null if there is no value).

Fixes https://github.com/dotnet/runtime/issues/61007

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by radical** [comment]
This needs a test.

**Comment by BrzVlad** [comment]
@radical Any recommendation where ? In the runtime tests ?

**Comment by radical** [comment]
> @radical Any recommendation where ? In the runtime tests ?

Adding in runtime tests makes sense.

**Comment by BrzVlad** [comment]
1. Added a test case. Set the priority to 0 for now so it gets to run on this PR on all configurations. I think I should leave it with priority 1, although I have no idea what are the guidelines around test priorities.
2. Changed the fix so it is a bit more reasonable. With the previous fix we were hitting some confusing code paths. Also this fix prevents addition of a `cknull` and some redundant inlining.

**Review by lambdageek — APPROVED** [review]

**Pull request merged**
