### PR TITLE
[mono] Enabled tests failing previously on fullaot

### PR DESCRIPTION
**Pull request by LeVladIonescu**
Related to https://github.com/dotnet/runtime/issues/57350 and https://github.com/dotnet/runtime/issues/70492.

### CODE REVIEW

**Review by kotlarmilos — COMMENTED** [review]
Looks good! Let us know when you get the green CI. Also, make sure to close related issues when this PR is merged, if they are fully resolved.

**Comment by kotlarmilos** [comment]
The enabled tests have passed on apple mobile platforms according to the CI status and logs. There are failed library tests which shouldn't be related.

**Comment by SamMonoRT** [comment]
Should close https://github.com/dotnet/runtime/issues/70492 and https://github.com/dotnet/runtime/issues/57350 when this PR is merged. Want to make sure fullaot passes too once https://github.com/dotnet/runtime/issues/86324 is fixed. Likely we will not backport a fix to that failing lane in RC1, so should be good to go ahead.

**Review by kotlarmilos — APPROVED** [review]

**Comment by ivanpovazan** [comment]
@LeVladIonescu @kotlarmilos could you please double check if the tests reported in https://github.com/dotnet/runtime/issues/70492 have been enabled? 

As I noted in the description of the issue, to enabling building the tests it was also required to adapt the: `src/tests/JIT/Directed/callconv/Directory.Build.props` file in order to enable building the tests for Mono. 

I am asking this as this PR does not include such change: https://github.com/LeVladIonescu/runtime_fork/blob/7cd6d011ac679dbdec44268a5571ecbfd7f864b2/src/tests/JIT/Directed/callconv/Directory.Build.props#L5

**Comment by kotlarmilos** [comment]
That is right. These tests haven't been executed on a device, so I will try to enable them.

**Pull request merged**
