### PR TITLE
threads.h: Fix up grammar/spelling in vm/threads.h

### PR DESCRIPTION
**Pull request by bchavez**
Studying some internal CLR native NT thread handling related to https://github.com/DataDog/dd-trace-dotnet/issues/6172 and came across this `threads.h` code comment that needed some grammar/spelling fix ups.

Thanks,  
Brian

### CODE REVIEW

**Comment by am11** [comment]
I think most, if not all, instances reported by the following query can be updated:

`git grep -i insur ':!src/native/external'`
<sub>(i.e. search for case-insensitive 'insur' excluding everything under `src/native/external` directory)</sub>

**Comment by am11** [comment]
I was on macOS zsh where single-quotes work (same as bash,powershell etc.).  For command prompt, it needs double-quotes would work `git grep -i insur ":!src/native/external"` (or no quotes since there is no space in that path segment)

Thanks for the update, LGTM!

**Comment by jkotas** [comment]
/ba-g Know issue https://github.com/dotnet/runtime/issues/110008, Format jit codebase

**Review by jkotas — APPROVED** [review]

**Comment by jkotas** [comment]
Thank you!

**Pull request merged**
