### PR TITLE
Use SIMD for block inits with GC fields

### LINKED ISSUE #83297: Suboptimal struct zeroing in case of gc pointers
```csharp
public struct MyStruct
{
    public long a;
    public long b;
    public long c;
    public long d;
    public long e;
    public long f;
    public long g;
    public long h;
    public long i;
    public long j;
    public long k;
    public long l;
    public long m;
    public long n;
    public long o;
    public string s;
}

public MyStruct Foo()
{
    MyStruct s = default;
    return s;
}
```
```asm
; Method Program:Foo():Program+MyStruct:this
       33C0                 xor      eax, eax
       488902               mov      qword ptr [rdx], rax
       48894208             mov      qword ptr [rdx+08H], rax
       48894210             mov      qword ptr [rdx+10H], rax
       48894218             mov      qword ptr [rdx+18H], rax
       48894220             mov      qword ptr [rdx+20H], rax
       48894228             mov      qword ptr [rdx+28H], rax
       48894230             mov      qword ptr [rdx+30H], rax
       48894238             mov      qword ptr [rdx+38H], rax
       48894240             mov      qword ptr [rdx+40H], rax
       48894248             mov      qword ptr [rdx+48H], rax
       48894250             mov      qword ptr [rdx+50H], rax
       48894258             mov      qword ptr [rdx+58H], rax
       48894260             mov      qword ptr [rdx+60H], rax
       48894268             mov      qword ptr [rdx+68H], rax
       48894270             mov      qword ptr [rdx+70H], rax
       48894278             mov      qword ptr [rdx+78H], rax
       488BC2               mov      rax, rdx
       C3                   ret      
; Total bytes of code: 69
```
JIT gives up on SIMDs because of gc pointers in a struct while it could use SIMD only for unmanaged part

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/83297

Currently, we conservatively give up on using SIMDs for structs (blocks) with GC references since SIMD (on x86/64 arch) has certain requirements to provide atomicity guarantees (data needs to be 16 byte aligned, CPU must support AVX2 and we must use aligned store instructions). Let's at least use SIMD for continuous non-GC parts of such structs, example:

```cs
struct MyStruct
{
    string gc1;
    long a;
    long b;
    long c;
    long d;
    long e;
    long f;
    long g;
    long h;
}

MyStruct Test() => new();
```
Codegen diff:
```diff
; Method Bench:Test():Bench+MyStruct:this (FullOpts)
       xor      eax, eax
       mov      qword ptr [rdx], rax ;; <-- GC slot
-      mov      qword ptr [rdx+0x08], rax
-      mov      qword ptr [rdx+0x10], rax
-      mov      qword ptr [rdx+0x18], rax
-      mov      qword ptr [rdx+0x20], rax
-      mov      qword ptr [rdx+0x28], rax
-      mov      qword ptr [rdx+0x30], rax
-      mov      qword ptr [rdx+0x38], rax
-      mov      qword ptr [rdx+0x40], rax
+      vxorps   xmm0, xmm0, xmm0
+      vmovdqu32 zmmword ptr [rdx+0x08], zmm0
       mov      rax, rdx
       ret      
-; Total bytes of code: 41
+; Total bytes of code: 23
```

### CODE REVIEW

**Comment by EgorBo** [comment]
@EgorBot
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Bench
{
    static void Main(string[] args) => 
        BenchmarkSwitcher.FromAssembly(typeof(Bench).Assembly).Run(args);

    public struct MyStruct
    {
        long a; long b; long c;
        long d; long e; long f;
        long g; long h; string gc1;
    }

    [Benchmark] public MyStruct Test() => new();
}
```

**Comment by EgorBo** [comment]
@EgorBot
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Bench
{
    static void Main(string[] args) => 
        BenchmarkSwitcher.FromAssembly(typeof(Bench).Assembly).Run(args);

    public struct MyStruct
    {
        long a; long b; long c;
        long d; long e; long f;
        long g; long h; string gc1;
    }

    [Benchmark] public MyStruct Test() => new();
}
```

**Comment by EgorBo** [comment]
@EgorBot
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Bench
{
    static void Main(string[] args) => 
        BenchmarkSwitcher.FromAssembly(typeof(Bench).Assembly).Run(args);

    public struct MyStruct
    {
        long a; long b; long c;
        long d; long e; long f;
        long g; long h; string gc1;
    }

    [Benchmark] public MyStruct Test() => new();
}
```

**Comment by EgorBo** [comment]
@EgorBot
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Bench
{
    static void Main(string[] args) => 
        BenchmarkSwitcher.FromAssembly(typeof(Bench).Assembly).Run(args);

    public struct MyStruct
    {
        long a; long b; long c;
        long d; long e; long f;
        long g; long h; string gc1;
    }

    [Benchmark] public MyStruct Test() => new();
}
```

**Comment by EgorBo** [comment]
@EgorBot
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Bench
{
    static void Main(string[] args) => 
        BenchmarkSwitcher.FromAssembly(typeof(Bench).Assembly).Run(args);

    public struct MyStruct
    {
        long a; long b; long c;
        long d; long e; long f;
        long g; long h; string gc1;
    }

    [Benchmark] public MyStruct Test() => new();
}
```

**Comment by EgorBo** [comment]
@EgorBot
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkRunner.Run<Bench>(args: args);

public class Bench
{
    public struct MyStructWithGC
    {
        object gc;
        long a; long b; long c; long d; 
        long e; long f; long g; long h; 
    }

    [Benchmark] 
    public MyStructWithGC StructZeroing() => new(); // struct zeroing
}
```

**Comment by EgorBo** [comment]
@EgorBot
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkRunner.Run<Bench>(args: args);

public class Bench
{
    public struct MyStructWithGC
    {
        object gc;
        long a; long b; long c; long d; 
        long e; long f; long g; long h; 
    }

    [Benchmark] 
    public MyStructWithGC StructZeroing() => new(); // struct zeroing
}
```

**Comment by EgorBo** [comment]
@EgorBot
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkRunner.Run<Bench>(args: args);

public class Bench
{
    public struct MyStructWithGC
    {
        object gc;
        long a; long b; long c; long d; 
        long e; long f; long g; long h; 
    }

    [Benchmark] 
    public MyStructWithGC StructZeroing() => new(); // struct zeroing
}
```

**Comment by EgorBo** [comment]
@EgorBot
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkRunner.Run<Bench>(args: args);

public class Bench
{
    public struct MyStructWithGC
    {
        object gc;
        long a; long b; long c; long d; 
        long e; long f; long g; long h; 
    }

    MyStructWithGC _fld1;
    MyStructWithGC _fld2;

    [Benchmark]
    void Zeroing()
    {
        _fld1 = default;
        _fld2 = default;
    }
}
```

**Comment by EgorBo** [comment]
@jakobbotsch @kunalspathak @dotnet/jit-contrib PTAL, [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=673121&view=ms.vss-build-web.run-extensions-tab) aren't too big

**Comment by EgorBo** [comment]
Ping @jakobbotsch @kunalspathak @dotnet/jit-contrib 🙂 https://github.com/dotnet/runtime/pull/102209 depends on it (for simpler diffs)

**Review by jakobbotsch — APPROVED** [review]

**Comment by jakobbotsch** [comment]
It would be nice to support it for copies as well (I think that would fix #90196)

**Review by kunalspathak — APPROVED** [review]
LGTM

**Pull request merged**
