### PR TITLE
[QUIC] Disable test for arm Ubuntu 18.04

### PR DESCRIPTION
**Pull request by ManickaP**
Contributes to #82055

### CODE REVIEW

**Review by CarnaViire — APPROVED** [review]
LGTM

**Review by wfurt — COMMENTED** [review]
LGTM. 
There is no conceptual reason why this would not work with jet stress, right?

**Review by wfurt — APPROVED** [review]

**Comment by ManickaP** [comment]
> LGTM. There is no conceptual reason why this would not work with jet stress, right?

I think we're just missing msquic in that particular image. Unless there's an inherent problem with arm 32.

**Comment by ManickaP** [comment]
No failing System.Net.Quic tests in all those pipelines.

**Comment by BruceForstall** [comment]
> I tried to find all runtime pipeline which had that test failing, seems like only libraries + jitstress + Ubuntu 18.04 arm 32 was affected. @BruceForstall does that cover your experience from #82055?

That's all I saw, but I admit I didn't look at other platforms or configurations where it might have been run.

**Pull request merged**
