### PR TITLE
Initialize gtUseNum before use

### LINKED ISSUE #56953: operand->gtUseNum == -1 during 'Generate code'
```c#
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
//
// This file is auto-generated.
// Seed: -1
//
using System;
using System.Runtime.CompilerServices;
public class TestClass13
{
    public struct S1
    {
        public byte byte_1;
    }
    public struct S2
    {
    }
    public struct S3
    {
    }
    public struct S5
    {
        public struct S5_D1_F2
        {
            public S1 s1_1;
            public ushort uint16_2;
        }
    }
    static ushort s_uint16_11 = 19036;
    static S2 s_s2_15 = new S2();
    static S3 s_s3_16 = new S3();
    static S5.S5_D1_F2 s_s5_s5_d1_f2_18 = new S5.S5_D1_F2();
    static S5 s_s5_19 = new S5();
    static int s_loopInvariant = 1;
    [MethodImpl(MethodImplOptions.NoInlining)]
    public ushort LeafMethod11()
    {
        unchecked
        {
            return s_s5_s5_d1_f2_18.uint16_2  <<= 15|4; 
        }
    }
    public S3 Method4(ref S2 p_s2_0, S5.S5_D1_F2 p_s5_s5_d1_f2_1, S5.S5_D1_F2 p_s5_s5_d1_f2_2, ushort p_uint16_3, ref S5 p_s5_4, S5.S5_D1_F2 p_s5_s5_d1_f2_5, short p_int16_6)
    {
        unchecked
        {
            {
            } 
            return s_s3_16 ; 
        }
    }
    public void Method0()
    {
        unchecked
        {
            if ((s_uint16_11  %= s_s5_s5_d1_f2_18.uint16_2  <<= 15|4)< 15+4- LeafMethod11())
{}            else
{}{}            s_s3_16  = Method4(ref s_s2_15 , s_s5_s5_d1_f2_18 , s_s5_s5_d1_f2_18 , LeafMethod11(), ref s_s5_19 , s_s5_s5_d1_f2_18 , 11592 ); 
            return; 
        }
    }
    public static void Main(string[] args)
    {
        TestClass13 objTestClass13 = new TestClass13();
        objTestClass13.Method0();
    }
}
/*
Got output diff:
--------- Baseline ---------  

Environment:

COMPlus_JITMinOpts=1
COMPlus_TieredCompilation=1


--------- Test ---------  

Environment:

COMPlus_TieredCompilation=0
COMPlus_JitOptRepeat=*
COMPlus_JitNoUnroll=1


Assert failure(PID 29844 [0x00007494], Thread: 31760 [0x7c10]): Assertion failed 'operand->gtUseNum == -1' in 'TestClass13:Method0():this' during 'Generate code' (IL size 92)

    File: D:\git\runtime\src\coreclr\jit\codegenlinear.cpp Line: 1319
    Image: D:\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe


*/

```

### PR DESCRIPTION
**Pull request by kunalspathak**
`gtUseNum` remained uninitialized until the use.

Fixes: https://github.com/dotnet/runtime/issues/56953

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Review by AndyAyersMS — APPROVED** [review]

**Review by jakobbotsch — APPROVED** [review]

**Comment by kunalspathak** [comment]
linux arm failure is related to https://github.com/dotnet/runtime/issues/55441

**Comment by kunalspathak** [comment]
I am seeing a new issue on OSX/arm64 that was discovered by the test I added.

```
Assert failure(PID 92709 [0x00016a25], Thread: 75045132 [0x479190c]): Assertion failed 'false && "it's not expected to be hit at the moment, but can be allowed."' in 'System.Runtime.CompilerServices.CastHelpers:ChkCastClassSpecial(long,System.Object):System.Object' during 'Do value numbering' (IL size 100)
```

**Review by briansull — APPROVED** [review]
Looks Good

**Comment by briansull** [comment]
@kunalspathak - That assert was added by EgorBo on Mar 22 with PR #50000

https://github.com/dotnet/runtime/pull/50000/files#r598977718

**Comment by kunalspathak** [comment]
Thanks @briansull . @EgorBo - any thoughts?

**Comment by EgorBo** [comment]
@kunalspathak I think it should be safe to change this line https://github.com/dotnet/runtime/blob/60d9b98938a9003d937efdaa53dfe6f0033de9bb/src/coreclr/jit/valuenum.cpp#L8411

to be

`f (addr->gtEffectiveVal()->IsCnsIntOrI())`

**Comment by briansull** [comment]
> @kunalspathak I think it should be safe to change this line
> to be
> `f (addr->gtEffectiveVal()->IsCnsIntOrI())`

The gtEffectiveVal call will just pull out the CSE LclVar that gets assigned to be the constant.
Then IsCnsIntOrI will still be false.

**Comment by EgorBo** [comment]
> > @kunalspathak I think it should be safe to change this line
> > to be
> > `f (addr->gtEffectiveVal()->IsCnsIntOrI())`
> 
> The gtEffectiveVal call will just pull out the CSE LclVar that gets assigned to be the constant.
> Then IsCnsIntOrI will still be false.

Ah, indeed, then it's `->gtCommaAssignVal()`

**Comment by EgorBo** [comment]
As the assert states: it can be just removed - there should not be a case where GT_IND has GTF_IND_NONNULL but the address was changed to something that can be null...

**Comment by briansull** [comment]
You could assert that there is no exception set on the gtEffectiveVal, (which requires a new call to unpack)
and/or check to see if the gtEffectVal ValueNumber is a constant.

**Comment by kunalspathak** [comment]
> You could assert that there is no exception set on the gtEffectiveVal, (which requires a new call to unpack)
> and/or check to see if the gtEffectiveVal ValueNumber is still a constant.

Did I get it correct?

```c++
assert(addr->gtEffectiveVal()->IsCnsIntOrI() || addr->gtEffectiveVal()->gtVNPair.GetLiberal() == ValueNumStore::VNForEmptyExcSet());
```

**Comment by briansull** [comment]
> ```c++
> addr->gtEffectiveVal()->gtVNPair.GetLiberal()
> ```

No, an unpack operation is necessary, you can't do it without introducing new DEBUG only variables.
Example:
```
            // Unpack, Norm,Exc for 'rhsVNPair'
            ValueNum vnRhsLibNorm;
            vnStore->VNUnpackExc(rhsVNPair.GetLiberal(), &vnRhsLibNorm, &vnExcSet);
```

Also the changes for this PR  doesn't include any changes to ValueNumber.cpp
So I am not seeing your code changes (other than in the comment above)

**Comment by kunalspathak** [comment]
> Also the changes for this PR doesn't include any changes to ValueNumber.cpp

Right, I wanted to make sure that I get it right. So what you are recommending is:

```c++
#ifdef DEBUG

                            ValueNum effectiveVnExcSet;
                            ValueNum effectiveValueNum;
                            vnStore->VNUnpackExc(addr->gtEffectiveVal()->gtVNPair.GetLiberal(), &effectiveValueNum,
                                                 &effectiveVnExcSet);
                            assert(addr->gtEffectiveVal()->IsCnsIntOrI() ||
                                   effectiveVnExcSet == ValueNumStore::VNForEmptyExcSet());

#endif
                            tree->gtVNPair = vnStore->VNPWithExc(tree->gtVNPair, addrXvnp);
```

**Comment by SingleAccretion** [comment]
> No, an unpack operation is necessary

Hmm, I though you could also use the `VNHasExc` helper method in such situations. Is that not true?

**Comment by EgorBo** [comment]
> Also the changes for this PR doesn't include any changes to ValueNumber.cpp
So I am not seeing your code changes (other than in the comment above)

From my understanding that assert can be hit in Main when you enable CSE for constants (string literal handle in this case).

So my suggestion is to rewrite it like this: https://www.diffchecker.com/n2HaLLdk

**Comment by kunalspathak** [comment]
I have opened #57515 and disabled the test for Arm64 for now.

**Comment by kunalspathak** [comment]
The failure is related to #57452.

**Comment by kunalspathak** [comment]
Failures are unrelated.

**Pull request merged**
