### PR TITLE
Update llvm-libunwind to v16.0.2

### PR DESCRIPTION
**Pull request by am11**
Points to https://github.com/llvm/llvm-project/releases/tag/llvmorg-16.0.2 + our local patches (in a separate commit).

### CODE REVIEW

**Comment by am11** [comment]
If possible, please merge this without squashing as version file has the commit reference to second commit (makes it easier to apply during the update).

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by am11** [comment]
@jkotas, @MichalStrehovsky, if you could create `objwriter/16.x` (or precise  `objwriter/16.0.2`) version branch in https://github.com/dotnet/llvm-project, I can prepare a PR against it. It will bring improvements made in MC area since 12.x and also enable folks to experiment with new architectures (loongarch64, riscv64) that are not present in 12.x.

(I have a local wip branch which merges objwriter/12.x -> <kbd>llvmorg-16.0.x</kbd> tag)

**Comment by jkotas** [comment]
We build objwriter in main branch, on top of LLVM 14: https://github.com/dotnet/llvm-project/pull/287. objwriter/12.x is used for .NET 7 servicing only.

@agocke @akoeplinger @directhex Do we have any plans for updating https://github.com/dotnet/llvm-project/ to LLVM 16?

**Comment by directhex** [comment]
“maybe”

We currently build LLVM with an older version of Clang for Linux-ABI-is-hard reasons, and I’ll need to take some time to reassess how much we’re able to change that now CentOS 7 isn’t our baseline, Ubuntu 16.04 is.

LLVM 16 does not compile with Clang 9, so there’s a problem there.

**Comment by agocke** [comment]
Note that we actually build with the latest clang in the new container -- we just compile against the old libs and header files.

**Comment by directhex** [comment]
Notably also with the old *includes*, so no language features newer than gcc 5.4 (eg C++17) can be used with the crossrootfs approach of the new Mariner based images

**Comment by am11** [comment]
> We build objwriter in main branch, on top of LLVM 14: https://github.com/dotnet/llvm-project/pull/287. objwriter/12.x is used for .NET 7 servicing only.

I did not notice that PR but I was able to apply all the patches in my branch. I don't know the motivation of merging to `main`. IMO, it is not the best move given now it is not possible to upgrade objwriter interdependently without caring for unrelated components. All objwriter needs is MC/assembler APIs and that part of llvm repo does not normally use/need newest language features.

**Comment by MichalStrehovsky** [comment]
> > We build objwriter in main branch, on top of LLVM 14: [dotnet/llvm-project#287](https://github.com/dotnet/llvm-project/pull/287). objwriter/12.x is used for .NET 7 servicing only.
> 
> I did not notice that PR but I was able to apply all the patches in my branch. I don't know the motivation of merging to `main`. IMO, it is not the best move given now it is not possible to upgrade objwriter interdependently without caring for unrelated components. All objwriter needs is MC/assembler APIs and that part of llvm repo does not normally use/need newest language features.

It is a compromise between that and having an extra branch to maintain on the engineering side, keeping it up with all the build infrastructure changes, flow, creation and maintenance of servicing branches etc.

Cc @markples

**Pull request merged**
