### PR TITLE
Fix linux-armel build

### LINKED ISSUE #110517: linux-armel checked CoreCLR_NonPortable build failing in CI
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=889548&view=logs&j=2eda3965-9146-55d1-4226-c3d3f8432d8f
Build error leg or test failing: Build / linux-armel checked CoreCLR_NonPortable / Build product
Pull request: https://github.com/dotnet/runtime/pull/110515

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "ld.lld: error: cannot open crtbeginS.o: No such file or directory",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=889548
**Error message validated:** `[ld.lld: error: cannot open crtbeginS.o: No such file or directory`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 12/9/2024 6:19:26 AM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[889597](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889597)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/889597/logs/183)|dotnet/runtime#110518|
|[889586](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889586)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/889586/logs/183)|dotnet/runtime#110516|
|[889581](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889581)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/889581/logs/183)|dotnet/runtime#110501|
|[889548](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889548)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/889548/logs/368)|dotnet/runtime#110515|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|4|4|

### PR DESCRIPTION
**Pull request by am11**
This syncs the gcc version in toolchian file with what's in the newest container build.

Fixes #110517

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
cc: @dotnet/samsung for review

**Review by gbalykov — APPROVED** [review]

**Comment by gbalykov** [comment]
@am11 should this go to arcade first?

**Comment by am11** [comment]
@gbalykov another approach was to make it dynamic for all of these:

```
eng/common/cross/toolchain.cmake:    set(TIZEN_TOOLCHAIN "armv7hl-tizen-linux-gnueabihf/9.2.0")
eng/common/cross/toolchain.cmake:      set(TIZEN_TOOLCHAIN "aarch64-tizen-linux-gnu/9.2.0")
eng/common/cross/toolchain.cmake:    set(TIZEN_TOOLCHAIN "armv7l-tizen-linux-gnueabi/9.2.0")
eng/common/cross/toolchain.cmake:      set(TIZEN_TOOLCHAIN "riscv64-tizen-linux-gnu/13.1.0")
eng/common/cross/toolchain.cmake:      set(TIZEN_TOOLCHAIN "x86_64-tizen-linux-gnu/9.2.0")
eng/common/cross/toolchain.cmake:    set(TIZEN_TOOLCHAIN "i586-tizen-linux-gnu/9.2.0")
```

For other platforms, we don't have version at that location. In Tizen containers, there is always a single versioned directory there. So we can pick up using cmake GLOB_DIRECTORY. WDYT?

**Comment by am11** [comment]
@gbalykov another approach is to make it dynamic for all of these:

```
eng/common/cross/toolchain.cmake:    set(TIZEN_TOOLCHAIN "armv7hl-tizen-linux-gnueabihf/9.2.0")
eng/common/cross/toolchain.cmake:      set(TIZEN_TOOLCHAIN "aarch64-tizen-linux-gnu/9.2.0")
eng/common/cross/toolchain.cmake:    set(TIZEN_TOOLCHAIN "armv7l-tizen-linux-gnueabi/9.2.0")
eng/common/cross/toolchain.cmake:      set(TIZEN_TOOLCHAIN "riscv64-tizen-linux-gnu/13.1.0")
eng/common/cross/toolchain.cmake:      set(TIZEN_TOOLCHAIN "x86_64-tizen-linux-gnu/9.2.0")
eng/common/cross/toolchain.cmake:    set(TIZEN_TOOLCHAIN "i586-tizen-linux-gnu/9.2.0")
```

For other platforms, we don't have version at that location. In Tizen containers, there is always a single versioned directory there. So we can search it using cmake's GLOB_DIRECTORY. WDYT?

**Review by sirntar — APPROVED** [review]
LGTM

**Review by t-mustafin — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
Thank you!

**Review by gbalykov — COMMENTED** [review]
LGTM

**Pull request merged**
