### PR TITLE
Fix output for user strings in R2RDump

### PR DESCRIPTION
**Pull request by AntonLapounov**
R2RDump would crash dumping strings with unpaired surrogates in diff mode due to using a `UTF8Encoding` with the `throwOnInvalidBytes` flag set on.  Moreover, control characters in strings, such as `'\0'` or `'\n'`, would be output without escaping.

I am changing the code to use the same `UTF8Encoding` for both diff and non-diff modes and output user strings as C# string literals employing the same logic as in Roslyn .NET Compiler.  An example of the output:
```
    TableIndex 5, Offset 016D: "\0\0\n\0\u0002\u0004\u0005\u0003\u0001\u0006\t\u0013\0" (STRING_HANDLE)
```

### CODE REVIEW

**Review by trylek — APPROVED** [review]
Looks great, thanks for fixing. One nit: one other place where a similar conversion should be taking place is here:

https://github.com/dotnet/runtime/blob/f6903fc2d37b3aa1588291d084e8dab63683cbbe/src/coreclr/src/tools/r2rdump/TextDumper.cs#L456

Would there be a chance to put AppendCSharpStringLiteral in some general place so that it can be used from the other place too?

**Review by trylek — APPROVED** [review]
Thank you!

**Comment by AntonLapounov** [comment]
@trylek The code you mentioned would throw an `ArgumentException`: 'The output char buffer is too small...' due to using `section.Size` instead of  `section.Size - 1`, so I had to fix it.

**Comment by AntonLapounov** [comment]
I renamed `AppendCSharpString` to `AppendEscapedString` since there is no C# specific: this escaping works with C/C++ as well.

**Pull request merged**
