### PR TITLE
Delete DOTNET_CLI_DO_NOT_USE_MSBUILD_SERVER workarounds

### PR DESCRIPTION
**Pull request by jkotas**
This workaround is no longer needed with .NET SDK 7 GA

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]
LGTM except for the one file under eng/common. Please also submit a patch in arcade for that.

**Comment by jkotas** [comment]
Arcade PR: https://github.com/dotnet/arcade/pull/11766

**Review by akoeplinger — APPROVED** [review]

**Comment by radical** [comment]
> #78034 moved us to building with .NET 7 GA. @radical Are there any other places where we still depend on .NET 7 previews?

oops, no, I'm slow!

**Comment by jkotas** [comment]
Known failures according to the build analysis

**Pull request merged**
