### PR TITLE
[System.Net.Quic]Release configuration resource.

### PR DESCRIPTION
**Pull request by shuxinqin**
Release configuration resource to prevent memory leaks.

### CODE REVIEW

**Comment by ManickaP** [comment]
Hi @shuxinqin,

Thank you for the contribution!

This needs to be locally tested with msquic before merging since we don't have a CI set up for it yet. Do you think that's something you could do? I assume you were able to [build msquic](https://github.com/microsoft/msquic/blob/main/docs/BUILD.md) and use it with runtime. Or is this something you'd rather leave to us?

**Comment by shuxinqin** [comment]
I downloaded the source code(System.Net.Quic) and change some codes to make it run in unity(netstandard2.0). If the resource is not released correctly when Application quiting, the unity editor will be stuck. So i have to release configuration resource when MsQuicConnection.Dispose() called, then the problem was solved.
ps: My changes depend on msquic1.3.0.

**Comment by wfurt** [comment]
I did some test runs with the change @ManickaP and it looks ok to me e.g. I did not see any side effects. I will need to figure out how to integrate with #52800.

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by shuxinqin** [comment]
@ManickaP @wfurt 
Feedback:
Hi, thanks for accept my pr. 
I did not see any code which release the MsQuicApi.Registration(https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/MsQuicApi.cs#L12) resource in System.Net.Quic project. I'm not sure if there will be a memory leak after the program exits.
In fact, to prevent the unity editor will be not stuck, i release configuration resource when MsQuicConnection was disposed, in addition i release MsQuicApi.Registration resource when Application quitting as follows:
```csharp
public static class MsQuicInterop
{
    /// <summary>
    /// Releases Registration.
    /// </summary>
    public static void Free()
    {
        if (MsQuicApi.Api == null)
            return;

        if (MsQuicApi.Api.Registration == null)
            return;

        if (!MsQuicApi.Api.Registration.IsClosed)
        {
            MsQuicApi.Api.Registration.Close();
        }

        MsQuicApi.Api?.Registration?.Dispose();
    }
}
```
Calls `Free()` method when application quitting:
```cssharp
Application.quitting += () =>
{
    Debug.Log("MsQuicInterop.Free...");
    MsQuicInterop.Free(); //Unity editor will be stuck if `Free()` method is not called.
};
```

**Comment by ManickaP** [comment]
Thanks for bringing this up.
If the process ends, all the resource will get released by the OS, there's no need to do that manually if you know the app will finish soon. And since we hold `MsQuicApi` as a singleton, living through the whole process lifetime, we do not need to dispose the registration (it needs to be kept alive while all its configurations and connections are still alive).

I don't think we have (or at least I'm not aware of) any plans to change the lifetime management of `MsQuicApi`. Any thoughts @scalablecory @geoffkizer ?

**Comment by shuxinqin** [comment]
I think it should be unity editor problem, thanks!

**Comment by scalablecory** [comment]
> Thanks for bringing this up.
> 
> If the process ends, all the resource will get released by the OS, there's no need to do that manually if you know the app will finish soon. And since we hold `MsQuicApi` as a singleton, living through the whole process lifetime, we do not need to dispose the registration (it needs to be kept alive while all its configurations and connections are still alive).
> 
> 
> 
> I don't think we have (or at least I'm not aware of) any plans to change the lifetime management of `MsQuicApi`. Any thoughts @scalablecory @geoffkizer ?

@jeffschwMSFT is it possible to load/unload .NET from a process? This is the only danger I see.

**Comment by jeffschwMSFT** [comment]
> @jeffschwMSFT is it possible to load/unload .NET from a process? This is the only danger I see.

.NET is not unloaded from a process.

**Pull request merged**
