### PR TITLE
[ppc64le] Bug fixes

### PR DESCRIPTION
**Pull request by alhad-deshpande**
This PR is a manual backport for PR [74746](https://github.com/dotnet/runtime/pull/74746) for release/7.0 branch. Please merge it as the original PR has already been merged in main.

### CODE REVIEW

**Comment by alhad-deshpande** [comment]
@akoeplinger 
This PR is a manual backport for PR https://github.com/dotnet/runtime/pull/74746 for release/7.0 branch. Please merge it as the original PR has already been merged in main.

**Comment by stephentoub** [comment]
Are we supporting ppc64le in .NET 7? I'm wondering why such fixes need to be in the release branch.

**Comment by akoeplinger** [comment]
@stephentoub not from Microsoft's side, the port is maintained by IBM. This helps them carrying fewer patches.

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
@steveisok please approve

**Review by steveisok — APPROVED** [review]

**Comment by carlossanlop** [comment]
@akoeplinger can you please confirm the CI failures aren't related?

**Comment by steveisok** [comment]
The failures appear to be infra related as each one says it couldn't upload artifacts.

**Comment by akoeplinger** [comment]
This is only touching PPC64 code so it is impossible to be related to failures on ARM64 jobs. I think this is good to be merged.

**Comment by carlossanlop** [comment]
CI failures verified as unrelated. The re-run showed cancellations/artifacts not uploaded, but no actual test failures.
Approved and signed off.
Ready to merge. :shipit:

**Pull request merged**
