### PR TITLE
Migrating EsrpCodeSigning Task From Version 4 to Version 5

### PR DESCRIPTION
**Pull request by davfost**
Migrating EsrpCodeSigning Task From Version 4 to Version 5

### CODE REVIEW

**Review by hoyosjs — APPROVED** [review]
Any test runs? Thought there's macOS issues with MI. If a test works, lgtm

**Comment by hoyosjs** [comment]
Also, how does this work given that we can't guarantee cleanup of macOS agents

**Review by dkurepa — CHANGES_REQUESTED** [review]
Please see my comments at https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/40049

**Comment by davfost** [comment]
> Any test runs? Thought there's macOS issues with MI. If a test works, lgtm

Sorry I don't know what the acronyms in this comment stand for (MI or Igtm). So I am not 100% sure what is being asked here.

In terms of general testing I setup a minimal file sign test using another internal branch which was not running a mac OS, and that process worked. Other teams have already integrated this changed into their pipeline, but I don't think those teams are running mac OSs either. 

To be clear this is the only solution offered by ESRP so plan was to get it out to the 2 locations that are using this process and have them tested with real data. I don't know how to do that before checking in the changes so the plan of record was to make this PR and then request the branch owners to test it with real data. If failure occur we need to escalate back to ESRP as quickly as possible.

**Comment by dkurepa** [comment]
This was tested here: https://dev.azure.com/dnceng/internal/_build/results?buildId=2480932&view=logs&j=98961004-82ec-556e-3483-7d3b15a14ba2&t=852e9ee6-1ee7-5d12-0c4f-e88603a7f1fa

**Review by dkurepa — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]

**Review by mmitche — APPROVED** [review]

**Pull request merged**
