### PR TITLE
Simplify `fgMorphMultiregStructArg`

### LINKED ISSUE #68645: `fgMorphMultiregStructArg` should only use the ABI information
Reproduction for the first issue:
```cs
[MethodImpl(MethodImplOptions.NoInlining)]
static unsafe void Problem(HfaStruct a)
{
    CallForFloatHfaStruct(*(FloatHfaStruct*)&a);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void CallForFloatHfaStruct(FloatHfaStruct value) { }

struct HfaStruct
{
    public double FirstDblValue;
    public double SecondDblValue;
}

struct FloatHfaStruct
{
    public float FirstFltValue;
    public float SecondFltValue;
    public float ThirdFltValue;
    public float FourthFltValue;
}
```
Compile with CG2 and a checked Jit: `--targetos:windows targetarch:arm64`.

Expected result: things compile fine.
Actual result: `noway_assert(elemType == varDsc->GetHfaType());` inside `fgMorphMultiregStructArg` is hit.

Reproduction for the second issue:
```cs
[MethodImpl(MethodImplOptions.NoInlining)]
static unsafe void Problem(MultiRegStruct a)
{
    CallForHfaStruct(*(HfaStruct*)&a);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void CallForHfaStruct(HfaStruct value) { }

struct HfaStruct
{
    public double FirstDblValue;
    public double SecondDblValue;
}

struct MultiRegStruct
{
    public long FirstLngValue;
    public long SecondLngValue;
}
```
Compile with CG2 and a checked Jit: `--targetos:windows targetarch:arm64`.

Expected result: things compile fine.
Actual result: `assert((allRegs(theInterval->registerType) & mask) != 0);` inside LSRA is hit because we create a `FIELD_LIST` of `long`s instead of `double`s.

### PR DESCRIPTION
**Pull request by SingleAccretion**
Two goals with this change:

1) Reduce code duplication and the amount of `#ifdef`s.
2) Fix #68645.

Fixes #68645.

[No diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1756092&view=ms.vss-build-web.run-extensions-tab) as expected.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
`Installer Build and Test coreclr OSX_x64 Release` failure is a network timeout:
```
/Users/runner/work/1/s/.dotnet/sdk/6.0.100/NuGet.targets(130,5): error : Failed to retrieve information about 'Microsoft.NETCore.App.Ref' from remote source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/e31c6eea-0277-49f3-8194-142be67a9f72/nuget/v3/flat2/microsoft.netcore.app.ref/index.json'. [/Users/runner/work/1/s/src/installer/tests/Assets/TestProjects/AppWithCustomEntryPoints/AppWithCustomEntryPoints.csproj]
/Users/runner/work/1/s/.dotnet/sdk/6.0.100/NuGet.targets(130,5): error :   The HTTP request to 'GET https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/e31c6eea-0277-49f3-8194-142be67a9f72/nuget/v3/flat2/microsoft.netcore.app.ref/index.json' has timed out after 100000ms. [/Users/runner/work/1/s/src/installer/tests/Assets/TestProjects/AppWithCustomEntryPoints/AppWithCustomEntryPoints.csproj]
```

@dotnet/jit-contrib

**Review by jakobbotsch — APPROVED** [review]
This looks great to me. I started some stress runs.

Also cc @shushanhf due to the LA64 changes.

**Comment by SingleAccretion** [comment]
Stress failures are #68690.

Libraries stress failures are #69154 and #68513 plus two unidentified GC-hole-like issues on x86 (which this change does not affect).

**Pull request merged**
