### PR TITLE
[mono][aot] Initialize beforefieldinit classes when AOT methods are l…

### PR DESCRIPTION
**Pull request by vargaz**
…oaded to avoid having to generate inline init code.

### CODE REVIEW

**Comment by lateralusX** [comment]
Will eliminate redundant checks in function that uses classes with static cctors and marked with beforefieldinit, like Math class for example.

Should we see if we could move the logic to add to the list into emit_class_init, so we can capture more cases where we currently emit a load/cmp/branch on the vtable init flag?

**Comment by lateralusX** [comment]
Will take it for a ride during the day on a sample that currently is affected by these redundant checks.

**Comment by lateralusX** [comment]
Maybe we should limit the impact of this when we move it out of draft mode, whitelist assemblies that will initially get the beforefieldinit behavior, so it won't break code that might be marked with beforefieldinit (added by compiler in for some scenarios) but still depending on initialization order.

**Comment by lateralusX** [comment]
@vargaz, looks like we hit a recursion:

```
 	RaiseException()	Unknown
 	mono_log_write_logfile(const char * log_domain, GLogLevelFlags level, int hdr, const char * message) Line 147	C
 	monoeg_g_logv_nofree(const char * log_domain, GLogLevelFlags log_level, const char * format, char * args) Line 176	C
 	monoeg_assertion_message(const char * format, ...) Line 219	C
 	mini_init_method_rgctx(MonoMethodRuntimeGenericContext * mrgctx, MonoGSharedMethodInfo * info) Line 1683	C
 	corlib_System_Buffers_ArrayPool_1_T_CHAR__cctor()	Unknown
 	mono_aot_corlibjit_code_start()	Unknown
 	mono_jit_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoErrorInternal * error) Line 3536	C
 	do_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoErrorInternal * error) Line 2418	C
 	mono_runtime_class_init_full(MonoVTable * vtable, _MonoErrorInternal * error) Line 534	C
 	init_method(MonoAotModule * amodule, void * info, unsigned int method_index, _MonoMethod * method, _MonoClass * init_class, _MonoErrorInternal * error) Line 4717	C
 	mini_llvm_init_method(MonoAotFileInfo * info, void * aot_module, void * method_info, MonoVTable * vtable) Line 943	C
 	mono_aot_corlib_init_method_gshared_mrgctx()	Unknown
	corlib_System_Buffers_ArrayPool_1_T_CHAR__cctor()	Unknown
 	mono_aot_corlibjit_code_start()	Unknown
 	mono_jit_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoErrorInternal * error) Line 3536	C
 	do_runtime_invoke(_MonoMethod * method, void * obj, void * * params, _MonoObject * * exc, _MonoErrorInternal * error) Line 2418	C
 	mono_runtime_class_init_full(MonoVTable * vtable, _MonoErrorInternal * error) Line 534	C
 	mono_resolve_patch_target_ext(_MonoMemoryManager * mem_manager, _MonoMethod * method, unsigned char * code, MonoJumpInfo * patch_info, int run_cctors, _MonoErrorInternal * error) Line 1591	C
 	init_method(MonoAotModule * amodule, void * info, unsigned int method_index, _MonoMethod * method, _MonoClass * init_class, _MonoErrorInternal * error) Line 4664	C
 	mini_llvm_init_method(MonoAotFileInfo * info, void * aot_module, void * method_info, MonoVTable * vtable) Line 943	C
 	mono_aot_corlib_init_method()	Unknown
 	corlib_System_Environment_GetEnvironmentVariableCore_string()	Unknown
....
```

**Comment by jkotas** [comment]
The unpredictable beforefieldinit timing was always a bug farm where a library was tested with one timing of the beforefieldinit static constructor, the next runtime updated changed it and broke the library

For .NET Core, we have standardized on triggering beforefield constructors right before the static field access, and did not have to deal with these problems ever since. It is likely you will find number of places in the dotnet/runtime libraries that will break with the less predictable beforefieldinit behavior.

**Comment by vargaz** [comment]
Do calls to static methods trigger initialization for beforefieldinit types, the same way for non-beforefieldinit types, or only field accesses trigger it ?

**Comment by jkotas** [comment]
only field accesses trigger it

**Comment by vargaz** [comment]
Closing in favor of:
https://github.com/dotnet/runtime/pull/76335

**Pull request closed without merging**
