### PR TITLE
Fix linux musl arm64 testing

### PR DESCRIPTION
**Pull request by jashook**
/cc @trylek @jkoritzinsky

### CODE REVIEW

**Comment by jashook** [comment]
Yay for muscle memory. Started https://dev.azure.com/dnceng/public/_build/results?buildId=446548

**Comment by jashook** [comment]
I believe this will give us a clean coreclr outerloop run (finally)

**Review by trylek — APPROVED** [review]
LGTM, thanks for fixing this!

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jashook** [comment]
Libraries testing seems unrelated.

**Comment by ViktorHofer** [comment]
Why do the timeouts need to be increased?

**Pull request merged**
