### PR TITLE
Add test for profiler inlining

### PR DESCRIPTION
**Pull request by davmason**
We found out recently (#59741) that we have no coverage for whether the runtime respects the profiler's request to prevent or allow inlining. This adds some basic tests

### CODE REVIEW

**Review by tommcdon — APPROVED** [review]
LGTM, one minor comment for your review

**Review by noahfalk — APPROVED** [review]
LGTM!
Are you able to run this test against any .NET 6 build without your recent fixes and confirm the test fails?

**Comment by davmason** [comment]
> Are you able to run this test against any .NET 6 build without your recent fixes and confirm the test fails?

I can now confirm that it fails when targeting 6.0-rc1

```
BEGIN EXECUTION
 "C:\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" inlining.dll
Profiler path: C:\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\profiler\unittest\inlining\Profiler.dll
Disabling tiered compilation, jitstress, and minopts.
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Inlining, x=604021970
BlockInlining, x=159477398
Saw Inlinee as a real method call instead of inlined.
NoResponse, x=1597929155
Profiler.dll!Profiler::Shutdown
TEST FAILED _failures=1_sawInlineeCall=1

Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
   at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error) in C:\git\runtime\src\tests\profiler\common\ProfilerTestRunner.cs:line 190
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
   at Profiler.Tests.InliningTest.Main(String[] args) in C:\git\runtime\src\tests\profiler\unittest\inlining.cs:line 60
Expected: 100
Actual: -532462766
```

**Comment by am11** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=1412218&view=logs&jobId=02b1a53f-5433-5236-da02-5fc377976c89&j=74429423-07be-5ff6-a774-8747bd8019a1

added trigger in #60738

**Pull request merged**
