### PR TITLE
Delete dead IFileFormatReader code in System.IO.Compression

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by stephentoub** [comment]
@carlossanlop or @ericstj, would one of you mind taking a quick look?

**Comment by stephentoub** [comment]
No one's reviewed this in two weeks, and all checks have passed.  I'm going to take that to mean no one has issues with this and merge it.

**Comment by ericstj** [comment]
@adamsitnik @Jozkee @carlossanlop

**Review by adamsitnik — COMMENTED** [review]
> No one's reviewed this in two weeks, and all checks have passed. I'm going to take that to mean no one has issues with this. Another PR is blocked on this, so I'm going to merge it

Apologies for the lack of review, I am going to sign up for notifications for my new areas.

**Pull request merged**
