### PR TITLE
Remove AspNetCore Testing Infra that isn't used

### LINKED ISSUE #38878: Cleanup remaining usages of FrameworkSkipCondition
It looks like an artifact from the tests ported from aspnetcore and should be replaced with SkipOnTargetFramework from arcade.

Also the usages where it's skipping tests on Mono can be removed since those were meant for the .NET Framework-based Mono, not the one we have in dotnet/runtime.

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/runtime/issues/38878

- ExceptionAssert -> AssertExtensions
- ThreadReplacer -> ThreadCultureChange
- TaskTimeoutExtensions -> TaskExtensions
- etc...

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@JunTaoLuo @maryamariyan @ericstj kindly asking for a review. This deletes all the aspnetcore infra that we ported over as well as it isn't used and replaced the few callers that used some of the features with runtime helpers.

**Comment by ericstj** [comment]
@maryamariyan and @JunTaoLuo will need to review this one.  I thought we had eliminated all dead code, so removing this might be removing something they need.

**Review by maryamariyan — APPROVED** [review]

**Comment by maryamariyan** [comment]
> I thought we had eliminated all dead code, so removing this might be removing something they need.

@ericstj this work item is tracked in issue https://github.com/dotnet/runtime/issues/37821#issue-637946617, second item under code cleanup.

**Comment by ViktorHofer** [comment]
That was all dead code, so no worries.

**Comment by JunTaoLuo** [comment]
Yea we were sort of expecting some of the Testing Infra to be unused. Some of the functionality have analogous counterparts in dotnet/runtime and some of the infra was created to support AspNetCore builds. I took a brief look and the removed code looks reasonable.

**Pull request merged**
