### PR TITLE
Make `jithashtable::SetKind` debug only argument.

### PR DESCRIPTION
**Pull request by sandreenko**
PTAL @dotnet/jit-contrib

### CODE REVIEW

**Comment by mikedn** [comment]
Doesn't the native compiler optimize the arg away?

And anyway, it would probably make more sense to have an `Add` function rather than a parameter on the `Set` function... Not to mention that the JIT is lacking a set and use the hashtable as a workaround.

**Comment by sandreenko** [comment]
> Doesn't the native compiler optimize the arg away?

It does, so I do not put PIN data here. The change is for convenience only, I do not like when debug only args are getting in the way.

> And anyway, it would probably make more sense to have an Add function rather than a parameter on the Set function... 

What would be the difference between Set and Add?

> Not to mention that the JIT is lacking a set and use the hashtable as a workaround.

I need set for my optCopyPropogation TP optimization, so I implemented a simple one, but don't know where I find time to finish it, it is very deep in my priority list right now :-(

**Comment by mikedn** [comment]
> What would be the difference between Set and Add?

Something like:
* `Add` does not add if the key exists and asserts.
* `Set` does add if the key does not exist and does not assert.
It's more similar to what other hashtables do (e.g. .NET's own `Dictionary` and C++'s `std::map`)

This `SetKind` thing just adds noise to the code, is unusual and not intuitive - the default is `None` so it asserts if the key exists, I've never seen a hashtable with "set" functionality that does this.

**Comment by sandreenko** [comment]
> Add does not add if the key exists and asserts.

I do not see that [Add ](https://docs.microsoft.com/en-us/dotnet/api/system.collections.idictionary?view=netframework-4.8)assert in this case. So maybe such behavior without an additional argument is more confusing.

**Comment by mikedn** [comment]
> I do not see that Add assert in this case. So maybe such behavior without an additional argument is more confusing.

The interface does not have any specific requirements in this regard. The commonly used implementation does throw on duplicates - https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.add?view=netframework-4.8
> ArgumentException 
An element with the same key already exists in the Dictionary<TKey,TValue>.

Anyway, the point was that the typical practice is to have separate functions for different behaviors, not a single function with extra parameters.

That said, I've been looking through the JIT code and it seems that there are far more "add" cases than "set" cases so fixing this "properly" would require more work and analysis. Likely not worth the trouble at this point.

**Pull request closed without merging**
