### PR TITLE
Add wasm for browser RID

### PR DESCRIPTION
**Pull request by marek-safar**
Implements #33327

/cc @lewing @vargaz

### CODE REVIEW

**Comment by ViktorHofer** [comment]
cc @ericstj

**Comment by ericstj** [comment]
This looks opposite of what was listed in the issue (`browser-wasm` rather than `wasm-browser`), not saying I disagree, just pointing that out.  Seems reasonable to treat `wasm` as the architecture.

Is `browser` specific enough?  Win different browsers expose a different platform?  Do we need to have things like gecko/webkit/blink/edge?

**Comment by marek-safar** [comment]
> Is browser specific enough?

It could be a good compromise, in reality, this will be more like `javascript-wasm` RID but that's perhaps even more confusing. We could define later more concrete browsers RIDs deriving from this one if needed. Without trying to predict the future the most likely next addition will be `browser-wasm2` deriving from `browser-wasm` though.

**Comment by safern** [comment]
Should we also align the way we build the runtime repo for wasm to the RID? Currently I believe we pass down -arch wasm and -os WebAssembly? https://github.com/dotnet/runtime/blob/master/src/libraries/Directory.Build.props#L37
https://github.com/dotnet/runtime/blob/master/src/libraries/Native/build-native.sh#L50

**Comment by marek-safar** [comment]
Yes, we'll fix that as soon as we get into producing runtime packs

**Review by jkotas — APPROVED** [review]

**Comment by marek-safar** [comment]
@ericstj any objections?

**Review by terrajobst — APPROVED** [review]

**Comment by ericstj** [comment]
> @ericstj any objections?

Be sure that you've ironed out all spec details on this (eg: concensus on actual names like `browser` and `wasm`).  They seem reasonable enough to me.

@eerhardt I presume the RID discovery API you're working on can handle this new RID since it will be plumbed through the host?

> Should we also align the way we build the runtime repo for wasm to the RID? Currently I believe we pass down -arch wasm and -os WebAssembly?

@safern my understanding of this PR is that `browser` is going to be a new TargetOS that will require a different set of library configurations.  `WebAssembly` today is actually largely using the `Unix` library configurations since it derives from `Unix`.

**Review by ericstj — APPROVED** [review]

**Comment by marek-safar** [comment]
> Be sure that you've ironed out all spec details on this (eg: concensus on actual names like browser and wasm). They seem reasonable enough to me.

It was discussed on design review with @terrajobst and approved (don't think we need another round just for rid)

**Review by eerhardt — APPROVED** [review]
This aligns with `OSPlatform.Browser` and `Architecture.Wasm` APIs that were recently added in #34781.

> I presume the RID discovery API you're working on can handle this new RID since it will be plumbed through the host?

Correct. The `RuntimeInformation.RuntimeIdentifier` API just returns the `RUNTIME_IDENTIFIER` AppContext value. So as long as the blazor/wasm host is setting that AppContext value, the new API will reflect that.

**Pull request merged**
