### PR TITLE
[LoongArch64] Rewrite the definition of struct REGDISPLAY in NativeAOT.

### PR DESCRIPTION
**Pull request by sunlijun-610**
This PR changes the order of variables in the `struct REGDISPLAY` in NativeAOT, putting `SP` at the end of general registers.

### CODE REVIEW

**Comment by am11** [comment]
@sunlijun-610, I saw your commit in riscv64 nativeaot branch. Thank you!
If these changes are relevant to riscv64, please apply them there as well when you get a chance. Hoping to see that arch build. :)

**Comment by jkotas** [comment]
Why is it necessary for SP to be at the end?

**Comment by sunlijun-610** [comment]
> Why is it necessary for SP to be at the end?

This modification is to be consistent with other architectures. Maybe it's unnecessary, but I think it's because the definition of SP is different from other registers.
If it's no need to modify, I'll close this PR. Thanks for your advice!

**Comment by jkotas** [comment]
> Maybe it's unnecessary,

I do not think it is unnecessary and makes the code a bit more complicated. Nothing in native AOT runtime depends on IP and SP field to be next to each other in the REGDISPLAY.

**Pull request closed without merging**
