### PR TITLE
Use reader/writer lock instead of mutex for `ComWrappers` RCW cache

### LINKED ISSUE #90964: ComWrappers.GetOrCreateObjectForComInstance becomes expensive during the Get cached RCW scenario when called from multiple threads
### Description

From multiple different threads, do calls to `ComWrappers.GetOrCreateObjectForComInstance` to get the RCW for the same existing native object which has already been cached.  Observe that the amount of time this takes can be pretty high due to the mutex in `ExtObjCxtCache` which causes it to become a one at a time operation to do the cached RCW lookup.

https://github.com/dotnet/runtime/blob/7cffd46ec956fbbb0c1e4b0fbe0a3a1b335ef006/src/coreclr/vm/interoplibinterface_comwrappers.cpp#L828

### Configuration

.NET 6

### Regression?

No

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Switching to a reader/writer lock improves throughput for faster RCW look up by 4x. This was observed in a private repro associated with https://github.com/dotnet/runtime/issues/90964.

Fixes https://github.com/dotnet/runtime/issues/90964

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Comment by jkotas** [comment]
Would it be possible to extract a repro into a microbenchmark in https://github.com/dotnet/performance?

Also, it would be good to check how native AOT does on this microbenchmark.

**Comment by AaronRobinsonMSFT** [comment]
> Would it be possible to extract a repro into a microbenchmark in https://github.com/dotnet/performance?

I will need to construct one. The repro was using C#/WinRT and would be non-trivial to recreate. I will see what I can do.

> Also, it would be good to check how native AOT does on this microbenchmark.

The data structure being used in AOT is the [`ConditionalWeakTable`](https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2). I don't think this has the same mutex issues that we had in CoreCLR.

**Comment by manodasanW** [comment]
> > Also, it would be good to check how native AOT does on this microbenchmark.
> 
> The data structure being used in AOT is the [`ConditionalWeakTable`](https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2). I don't think this has the same mutex issues that we had in CoreCLR.

For AOT, thoughts on the [lock here](https://github.com/dotnet/runtime/blob/704beaa5b427fd5c47e537ff7c3deee7de28378c/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs#L981C1-L982C1) for rcwCache.

**Comment by AaronRobinsonMSFT** [comment]
> > > Also, it would be good to check how native AOT does on this microbenchmark.
> > 
> > 
> > The data structure being used in AOT is the [`ConditionalWeakTable`](https://learn.microsoft.com/dotnet/api/system.runtime.compilerservices.conditionalweaktable-2). I don't think this has the same mutex issues that we had in CoreCLR.
> 
> For AOT, thoughts on the [lock here](https://github.com/dotnet/runtime/blob/704beaa5b427fd5c47e537ff7c3deee7de28378c/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs#L981C1-L982C1) for rcwCache.

I was misinformed. Sad. Okay, that needs to change.

**Comment by AaronRobinsonMSFT** [comment]
> Would it be possible to extract a repro into a microbenchmark in https://github.com/dotnet/performance?
> 
> Also, it would be good to check how native AOT does on this microbenchmark.

@jkotas and @manodasanW I'm genuinely shocked at this, but converting NAOT to use a reader/writer lock makes NAOT slower for a microbenchmark. I was able to see the expected speed in the microbenchmark with CoreCLR and the reader/writer lock so it is capturing the scenario, but there is nothing to do here for NAOT.

I will work on pushing the benchmark into https://github.com/dotnet/performance.

**Comment by AaronRobinsonMSFT** [comment]
NAOT
> native_baseline\Perf.exe
> Parallel.ForEach: 409 ms.
> native\Perf.exe
> Parallel.ForEach: 520 ms.

CoreCLR
> Perf_baseline.cmd
> Parallel.ForEach: 2060 ms.
> Perf.cmd
> Parallel.ForEach: 428 ms.

**Comment by AaronRobinsonMSFT** [comment]
Benchmark PR - https://github.com/dotnet/performance/pull/3298

**Pull request merged**
