### PR TITLE
Arm64: Make Float-to-Integer conversions compatible with x86

### PR DESCRIPTION
**Pull request by EgorBo**
CI test

### CODE REVIEW

**Comment by jkotas** [comment]
Do we really want this compatibility mode in .NET Core? I understand that we may want to have it in .NET Framework, but it does not sound right to me to introduce it in .NET Core.

**Comment by EgorBo** [comment]
> Do we really want this compatibility mode in .NET Core? I understand that we have historically had compatibility modes like this one in .NET Framework, but it does not sound right to me to introduce it in .NET Core.

This is need for a different project (cc @davidwrighton), I just decided to test it on CI using David's implementation

**Comment by tannergooding** [comment]
Could @pgovind and I get tagged on these floating-point related changes, so we can stay up to date with the JIT behaviors for the library types we own?

**Comment by tannergooding** [comment]
These changes can also be impactful when comparing the software fallback vs the accelerated path for things like Vector<T> and Vector2/3/4, so we may need to account for changes there.

**Comment by EgorBo** [comment]
> Could @pgovind and I get tagged on these floating-point related changes, so we can stay up to date with the JIT behaviors for the library types we own?

Don't worry, it's not going to check in, was just testing something 🙂

**Pull request closed without merging**
