### PR TITLE
Ensure floating-point types write the exponent/significand as little-endian

### PR DESCRIPTION
**Pull request by tannergooding**
Discovered by @uweigand in https://github.com/dotnet/runtime/pull/68141#issuecomment-1105272469

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Review by dakersnar — COMMENTED** [review]
Looks good. Are there existing unit tests that catch this bug, at least before you fixed it?

**Comment by tannergooding** [comment]
Yes. The problem is that we don't run any CI legs that cover `big endian` machines.

This was caught in the outer loop on some jobs running against an s390x on Mono.

**Comment by uweigand** [comment]
The CI is running the full runtime test suite on s390x (this is the dotnet runtime using the Mono JIT):
https://dev.azure.com/dnceng/public/_build?definitionId=1052

But this is just running twice a day and not as part of the PR checks, so big endian breakages are usually not detected pre-commit unfortunately.

**Comment by uweigand** [comment]
Thank, @tannergooding!  This fixes the binary floating-point tests, but there's still a failure in a decimal floating-point test:
```
    System.Tests.DecimalTests_GenericMath.TryWriteSignificandLittleEndianTest [FAIL]
      Assert.Equal() Failure
                 ↓ (pos 0)
      Expected: [10, 0, 0, 0, 0, ...]
      Actual:   [0, 0, 0, 0, 0, ...]
                 ↑ (pos 0)
      Stack Trace:
        /_/src/libraries/System.Runtime/tests/System/DecimalTests.GenericMath.cs(1063,0): at System.Tests.DecimalTests_GenericMath.TryWriteSignificandLittleEndianTest()
```

Looks like this place also needs to be updated:
https://github.com/dotnet/runtime/blob/a9d25b6324708127c0aada0244e7a76af390b56d/src/libraries/System.Private.CoreLib/src/System/Decimal.cs#L1194-L1195

**Pull request merged**
