### PR TITLE
Update to use Mariner 2.0 as the build image

### PR DESCRIPTION
**Pull request by mmitche**
Context: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/615

TODO task list:
- [ ] Upgrade to clang12 in other docker images. Alpine images need upgrade. Currently have older versions of node too which may cause problems upon upgrade.
- [ ] Compiler crash in in clang12 for mono needs investigation. (@vargaz will take a look initially)
- [ ] Re-specify clang12 as required in build scripts
- [ ] Determine what to do about libc version. Probably need to not use what's on the box and instead link against a specific version/
- [ ] Verify official build
- [ ] Verify PR builds

### CODE REVIEW

**Comment by richlander** [comment]
@mmitche kicked off this build and an official (internal) build concurrently. The official build broke in several places. We'll be looking into that next.

**Comment by mmitche** [comment]
> Note that this run just a small fraction of the validation. The main "runtime" pipeline did not run at all. Looks like the changes broke it.

I had a typo in the YAML, fixed.

**Comment by jkoritzinsky** [comment]
Are we sure that this image will still target the right libc version, or do we need to set up cross targeting with a centos rootfs?

**Comment by richlander** [comment]
https://github.com/orgs/dotnet/teams/distro-maintainers/discussions/2?from_comment=4#discussion-2-comment-4

**Comment by mmitche** [comment]
TODO task list:
- [ ] Upgrade to clang12 in other docker images. Alpine images need upgrade. Currently have older versions of node too which may cause problems upon upgrade.
- [ ] Compiler crash in in clang12 for mono needs investigation.
- [ ] Re-specify clang12 as required in build scripts
- [ ] Determine what to do about libc version. Probably need to not use what's on the box and instead link against a specific version/

**Comment by richlander** [comment]
@mmitche -- Can you delete your comment (and this one, too) and put your todo list in the overall issue comment at the top (so it doesn't get lost in the middle)?

**Comment by akoeplinger** [comment]
it looks like the `mono llvmaot Pri0 Runtime Tests Run Linux x64` leg has a bunch of failures due to
```
/datadisks/disk1/work/AF8B097E/p/corerun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /datadisks/disk1/work/AF8B097E/p/corerun)
/datadisks/disk1/work/AF8B097E/p/corerun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /datadisks/disk1/work/AF8B097E/p/corerun)
/datadisks/disk1/work/AF8B097E/p/corerun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /datadisks/disk1/work/AF8B097E/p/corerun)
/datadisks/disk1/work/AF8B097E/p/corerun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /datadisks/disk1/work/AF8B097E/p/corerun)
```

which is kinda expected when we have libc version mismatches, I think we need to solve those first before we can continue.

**Comment by richlander** [comment]
Can you elaborate on that @akoeplinger? Is the issue that the Mono build is brining along or intending to link to a different libc that clang supports?

**Comment by akoeplinger** [comment]
No it means that we're building against a newer libc and then try to run on systems with an earlier libc. You can see the same issue on e.g. the `coreclr Pri0 Runtime Tests Run Linux x64 checked` leg which also run on `ubuntu.1804.amd64.open`

**Comment by richlander** [comment]
Oh, I see. That.

We knew that we'd have to sort that out pretty soon. That's now, apparently. I general thinking has been to adopt the rootfs approach. We'll talk about that next week.

**Comment by danmoseley** [comment]
Does this need to happen for .NET 7 ? @mmitche

**Comment by mmitche** [comment]
> Does this need to happen for .NET 7 ? @mmitche

I don't think so, @richlander may have a different opinion though.

**Comment by agocke** [comment]
Moving this to draft PR since it looks like it's a WIP.

**Comment by richlander** [comment]
Right. Not .NET 7. We'll return to this soon-ish, particularly once `main` moves to .NET 8.

**Pull request closed without merging**
