### PR TITLE
Prevent nullptr dereference in GenTree::IsLclVarUpdateTree

### PR DESCRIPTION
**Pull request by saucecontrol**
As explained by @mikedn in https://github.com/dotnet/coreclr/issues/27937#issuecomment-558157580, some binary gentrees are actually other types, so not all actually have 2 operands.  This change prevents a nullptr dereference when a non-binary binary gentree appears on the rhs in `IsLclVarUpdateTree`.

Fixes https://github.com/dotnet/coreclr/issues/27937

### CODE REVIEW

**Comment by saucecontrol** [comment]
cc @dotnet/jit-contrib 

Really hoping to get this fixed for 3.1 release.  I've run into it twice now, and each time because I was working on unsafe HWIntrinsics code, my first instinct was naturally to blame my own pointer math for the AV.  Hopefully we can save some other devs from the same pain and wasted time.

**Review by swaroop-sridhar — APPROVED** [review]
Please add a comment in that certain operators like HWINTRINSIC are declared as a binary operator, but actually may not have two operands.

**Comment by tannergooding** [comment]
Could you please add a regression test for this scenario? These typically go under https://github.com/dotnet/runtime/tree/master/src/coreclr/tests/src/Regressions/coreclr.

I'm not sure if we want to keep the `GitHub_#####` schema or if using `GitHub_Runtime_#####` would be better (or some other alternative).

**Comment by saucecontrol** [comment]
Comment and test added.

Did `GitHub_27937` for now since the issue was opened in coreclr.

**Review by CarolEidt — APPROVED** [review]
LGTM thanks!

**Comment by saucecontrol** [comment]
Any chance this makes the bar for backporting to 3.1?  It's not terribly difficult to work around, but diagnosing the problem can be difficult before one gets to that point.

**Pull request merged**
