### PR TITLE
Validate hardcoded offsets to PROFILE_PLATFORM_SPECIFIC_DATA struct

### PR DESCRIPTION
**Pull request by tomeksowi**
These offsets are now in asmconstants.h validated against the C struct with static asserts.

This refactoring is a follow-up to [discussion](https://github.com/dotnet/runtime/pull/91313#discussion_r1312507740) under PR #91313.

Note: I didn't define offset constants for i386 because its asm profile stubs are based on a sequence of `push`es rather than field offsets so they wouldn't use them.

Part of #84834
cc @wscho77 @HJLeee @JongHeonChoi @t-mustafin @alpencolt @gbalykov @clamp03

### CODE REVIEW

**Comment by tomeksowi** [comment]
@davmason Can you have a look please?
\+ @jkotas @shushanhf

**Review by clamp03 — APPROVED** [review]

**Comment by shushanhf** [comment]
> @davmason Can you have a look please? + @jkotas @shushanhf

Thanks
I will upload the LA's patch.

**Comment by shushanhf** [comment]
> > @davmason Can you have a look please? + @jkotas @shushanhf
> 
> Thanks I will upload the LA's patch.

I think I need some time to refactor some function to fix some errors for LoongArch. Maybe tomorrow is ok.

**Review by alpencolt — APPROVED** [review]

**Comment by tomeksowi** [comment]
cc @yurai007 @simtar

**Review by jkotas — APPROVED** [review]

**Review by wscho77 — APPROVED** [review]

**Review by davmason — APPROVED** [review]

**Comment by jkotas** [comment]
Thank you!

**Pull request merged**
