### PR TITLE
Check more patterns for retBuffer.

### LINKED ISSUE #36681: Test failure: JIT\\Regression\\JitBlue\\GitHub_27924\\GitHub_27924\\GitHub_27924.cmd
failed in job: [runtime-coreclr jitstress 20200517.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=649313&view=ms.vss-test-web.build-test-results-tab&runId=20146270&resultId=108409&paneView=debug)

Error message
~~~
Assert failure(PID 5488 [0x00001570], Thread: 11524 [0x2d04]): _safePointDecoder.IsSafePoint(curOffs)

<no module>! <no symbol> + 0x0 (0x00000000)
 File: F:\workspace\_work\1\s\src\coreclr\src\vm\eetwain.cpp Line: 5044
 Image: D:\h\w\AAF5093E\p\CoreRun.exe


Return code: 1
Raw output file: D:\h\w\AAF5093E\w\B29D099C\e\JIT\Regression\Reports\JIT.Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.output.txt
Raw output:
BEGIN EXECUTION
 "D:\h\w\AAF5093E\p\corerun.exe" GitHub_27924.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\AAF5093E\p
> D:\h\w\AAF5093E\w\B29D099C\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.cmd
Expected: True
Actual: False


Stack trace
   at JIT_Regression._JitBlue_GitHub_27924_GitHub_27924_GitHub_27924_._JitBlue_GitHub_27924_GitHub_27924_GitHub_27924_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm.Checked\TestWrappers\JIT.Regression\JIT.Regression.XUnitWrapper.cs:line 122360
~~~

category:correctness
theme:gc-stress
skill-level:expert
cost:large

### LINKED ISSUE #39947: SuperPMI checked/release failures
Run SuperPMI in asm diff mode using Checked and Release JIT (Windows x64), on the full frameworks + tests collection, e.g.:
```
f:\gh\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\superpmi.exe -p -f fail.mcl -a -jitoption force AltJit= -jitoption force AltJitNgen= f:\gh\runtime\artifacts\bin\coreclr\Windows_NT.x64.Checked\clrjit.dll f:\gh\runtime\artifact
s\bin\coreclr\Windows_NT.x64.Release\clrjit.dll f:\spmi\runtime_collection\collections\tests.pmi.Windows_NT.x64.Release.mch
```

I see 926 of:
```
ERROR: Exception thrown: SuperPMI assertion 'IsStructRequiringStackAllocRetBuf != nullptr' failed ("Found a null IsStructRequiringStackAllocRetBuf.  Probably missing a fatTrigger for 00007FFD79C3C920.")
```
and 1:
```
ERROR: Exception thrown: SuperPMI assertion 'IsStructRequiringStackAllocRetBuf->GetIndex((DWORDLONG)cls) != -1' failed ("Didn't find 00007FFD79BEED58")
```

I would expect there not to be any errors. The collection was done using a Windows x64 Checked JIT. A Release JIT shouldn't ask any different questions, so the Checked collection should be usable.

Related? https://github.com/dotnet/runtime/issues/39908

category:correctness
theme:testing
skill-level:intermediate
cost:medium

### PR DESCRIPTION
**Pull request by sandreenko**
We force return buffers containing GC pointers to be on the stack and before we make a copy we check if the return buffer is already on the stack. Fix the check by adding `LCL_VAR_ADDR`, `ADD(LCL_VAR_ADDR, CNST)` patterns.

Fixes https://github.com/dotnet/runtime/issues/39947, however, the issue happens because of the several factors:
1. `EnableExtraSuperPmiQueries` is a debug only variable that is set during collection;
2. debug only `makeExtraStructQueries` is called in checked and it could find a SIMD type when SIMD intrinsics are not used, it would call  `setUsesSIMDTypes(true) {_usesSIMDTypes = true; }` in compiler;
3. based on the value of `_usesSIMDTypes` struct promotion could make different decisions, for example, promote `struct A {simd16 a; }`;
4. lclmorph doesn't replace `ADDR(LCL_VAR)` as `LCL_VAR_ADDR` if the lclVar is promoted;
5. `LCL_VAR_ADDR` was not recognized by the function changed in this PR and it led to additional VM questions that were failing during release replay.

This PR fixes only the 5th. We could fix the first by:
1. disable `EnableExtraSuperPmiQueries` until we need it again;
2. don't record `EnableExtraSuperPmiQueries` value during collection (hack `void MethodContext::recGetIntConfigValue(const WCHAR* name, int defaultValue, int result)`);
3. pass `-jitoption force EnableExtraSuperPmiQueries=0 -jit2option force EnableExtraSuperPmiQueries=0` during SPMI replay;
4. do less in `makeExtraStructQueries`.

The rest SPMI chk/rel diffs are covered by https://github.com/dotnet/runtime/issues/39908

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @CarolEidt @BruceForstall @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
> LCL_VAR_ADDR was not recognized by the function changed in that PR

What PR are you referring to?

Regarding how to deal with `EnableExtraSuperPmiQueries`, I'd prefer option 3: pass `-jitoption force EnableExtraSuperPmiQueries=0 -jit2option force EnableExtraSuperPmiQueries=0` during SPMI replay for checked/release diffs. But I'm flexible.

**Review by CarolEidt — APPROVED** [review]
LGTM

**Comment by sandreenko** [comment]
> > LCL_VAR_ADDR was not recognized by the function changed in that PR

> 
> What PR are you referring to?

This one, typo, sorry for the confusion.

> Regarding how to deal with EnableExtraSuperPmiQueries, I'd prefer option 3: pass -jitoption force EnableExtraSuperPmiQueries=0 -jit2option force EnableExtraSuperPmiQueries=0 during SPMI replay for checked/release diffs. But I'm flexible.

Agree, I think it is safe and easy. Maybe we will lose some methods during SPMI cleaning phase but the result `*.mch` files should not show any diffs between chk/rel because of `EnableExtraSuperPmiQueries`. I will push the change to this PR.

**Comment by BruceForstall** [comment]
While forcing `-jitoption force EnableExtraSuperPmiQueries=0 -jit2option force EnableExtraSuperPmiQueries=0` during replay seems expedient, it's also unsettling that enabling extra SuperPMI queries during collection can actually affect codegen. Presumably it could also cause the subsequent questions in the normal codegen to differ, leading to missing questions/answers on replay when NOT setting it.

I wonder if it would be possible to move the "extra" calls to the very end of JITing such that any potential side effects couldn't affect the already-generated code? That is, assuming these calls could even legally be made at that time.

**Review by BruceForstall — APPROVED** [review]

**Comment by sandreenko** [comment]
> Presumably it could also cause the subsequent questions in the normal codegen to differ, leading to missing questions/answers on replay when NOT setting it.

Yeah, as I said with this approach we could have some new failures during a cleaning stage and we will have fewer methods in the final mch.

**Pull request merged**
