### PR TITLE
Relax argument checks on pinned GCHandles

### LINKED ISSUE #68686: Unable to pin arrays of unmanaged structs
Repro:
```csharp
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

[assembly: DisableRuntimeMarshallingAttribute]

object o = new MyStruct[10];
GCHandle h = GCHandle.Alloc(o, GCHandleType.Pinned);

struct MyStruct
{
    char c;
}
```
Actual result: System.ArgumentException: Object contains non-primitive or non-blittable data.
Expected result: No exceptions

### PR DESCRIPTION
**Pull request by jkotas**
Relax argument checks on pinned GCHandles to allow any objects without references for consistency with DisableRuntimeMarshalling.

Fixes #68686

### CODE REVIEW

**Comment by vargaz** [comment]
The mono changes look ok to me.

**Review by AaronRobinsonMSFT — COMMENTED** [review]
It seems NativeAOT already has this similar definition and only checks for `null` or if the type has pointers. I think at this point there is really no argument against adding support in all cases.

https://github.com/dotnet/runtime/blob/86565188c0e6edbc79a89ef3ebae40ca2551ae2b/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/InteropExtensions.cs#L15-L32

What about the following that mark `char` and `bool` as non-blittable? I think Crossgen or NativeAOT might trigger off of that in some manner.

https://github.com/dotnet/runtime/blob/86565188c0e6edbc79a89ef3ebae40ca2551ae2b/src/coreclr/tools/Common/TypeSystem/Interop/IL/MarshalHelpers.cs#L273-L312

**Review by lambdageek — COMMENTED** [review]
Pinnable if it _doesn't_ have references?

**Comment by jkotas** [comment]
> What about the following that mark char and bool as non-blittable? I

I do not see a problem here. The marshaling without `DisableRuntimeMarshaling` needs work like it always did.

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Pull request merged**
