### PR TITLE
enable Proxy_UseEnvironmentVariableToSetSystemProxy_RequestGoesThruProxy test

### PR DESCRIPTION
**Pull request by aik-jahoda**
The test is not failing I run it in the loop. Enabling it again.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
Please run outerloop tests.  If CI is green, LGTM. Thanks.

**Review by davidsh — APPROVED** [review]

**Comment by aik-jahoda** [comment]
The outer loop test fails: 
The `via: HTTP/1.1 LoopbackProxyServer` header is missing.
It works properly on my local machine and not on CI. It seems the `http_proxy` env variable is ignored on CI machine. 

I need to investigate more about what is going on.

**Comment by davidsh** [comment]
>It works properly on my local machine and not on CI. It seems the http_proxy env variable is ignored on CI machine.
I need to investigate more about what is going on.

It could be due to mitigation of https://httpoxy.org/.  Typically, many CGI and other server environments explicitly filter out the 'http_proxy' environment variable. That could thus interfere with this test case.

**Comment by aik-jahoda** [comment]
@davidsh, can you please review the final fix? The issue was that the failing test was in the WinHttpHandler test which doesn't support testing functionality.

All failing tests are failing on different tests not the test related to this PR

**Comment by davidsh** [comment]
>@davidsh David Shulman FTE, can you please review the final fix?

Can you review my question [here](https://github.com/dotnet/runtime/pull/34444#commitcomment-38564646) ?

**Comment by aik-jahoda** [comment]
Thanks for the sugestion @davidsh, running the outer-loop to final verification

**Comment by davidsh** [comment]
LGTM

**Pull request merged**
