### PR TITLE
update mariner Linux image to 2.0

### LINKED ISSUE #81901: [QUIC] Missing `libmsquic` on tested platforms
Tested out via running `MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue` on all Linuxes. Tests ran on `runtime`, `runtime-extra-platforms` and `outerloop` pipelines:
- https://dev.azure.com/dnceng-public/public/_build/results?buildId=165462&view=results
- https://dev.azure.com/dnceng-public/public/_build/results?buildId=165466&view=results
- https://dev.azure.com/dnceng-public/public/_build/results?buildId=165467&view=results
Original PR: https://github.com/dotnet/runtime/pull/81481.

These distributions / versions failed:
- [ ] `centos VersionId=7.0` :  
  - (ubuntu.1804.amd64.open.rt) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-helix
- [ ] `mariner VersionId=1.0`
  - (ubuntu.1804.amd64.open.rt) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-1.0-helix
- [ ] `alpine VersionId=3.13.12`
  - (ubuntu.1804.amd64.open.rt) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.13-helix-amd64

Different issue occurred on Alpine 3.14:

- [ ] `alpine VersionId=3.14.8`
  - (ubuntu.1804.amd64.open.rt) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64
  - we're getting error meaning that libmsquic.so is present but doesn't work:
```
System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsquic_IsSupportedIsTrue [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicPlatformDetectionTests.cs(45,0): at System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsquic_IsSupportedIsTrue()
        --- End of stack trace from previous location ---
      Output:
        Using unknown
        /usr/lib/libmsquic.so.2
```
This should be resolved by https://github.com/microsoft/msquic/pull/3394 and get into our repo with the next docker image rollout.

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=174946
Build error leg or test failing: System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue
Pull request: https://github.com/dotnet/runtime/pull/82235

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[175935](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175935)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175935/logs/2089)|dotnet/runtime#82305|
|[175925](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175925)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175925/logs/2268)|dotnet/runtime#82304|
|[175752](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175752)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/175752/logs/1540)|dotnet/runtime#81615|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[176284](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176284)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176284&view=ms.vss-test-web.build-test-results-tab&runId=3495168&resultId=148225)|dotnet/runtime#82200|
|[176593](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176593)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176593&view=ms.vss-test-web.build-test-results-tab&runId=3494727&resultId=143921)|dotnet/runtime#82331|
|[176601](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176601)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176601&view=ms.vss-test-web.build-test-results-tab&runId=3494612&resultId=149987)|dotnet/runtime#82332|
|[176688](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176688)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176688&view=ms.vss-test-web.build-test-results-tab&runId=3492087&resultId=156540)||
|[176374](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176374)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176374&view=ms.vss-test-web.build-test-results-tab&runId=3491580&resultId=147612)|dotnet/runtime#82276|
|[176576](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176576)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176576&view=ms.vss-test-web.build-test-results-tab&runId=3491309&resultId=149209)|dotnet/runtime#82330|
|[176565](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176565)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176565&view=ms.vss-test-web.build-test-results-tab&runId=3491287&resultId=156850)|dotnet/runtime#79169|
|[176489](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176489)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176489&view=ms.vss-test-web.build-test-results-tab&runId=3491132&resultId=142916)|dotnet/runtime#82325|
|[176553](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176553)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176553&view=ms.vss-test-web.build-test-results-tab&runId=3491060&resultId=146034)|dotnet/runtime#82329|
|[176516](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176516)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176516&view=ms.vss-test-web.build-test-results-tab&runId=3490988&resultId=150607)|dotnet/runtime#82328|
|[176493](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176493)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176493&view=ms.vss-test-web.build-test-results-tab&runId=3490766&resultId=149281)|dotnet/runtime#81518|
|[176475](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176475)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176475&view=ms.vss-test-web.build-test-results-tab&runId=3490565&resultId=157356)|dotnet/runtime#80960|
|[176418](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176418)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176418&view=ms.vss-test-web.build-test-results-tab&runId=3490109&resultId=150849)|dotnet/runtime#82250|
|[176354](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176354)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176354&view=ms.vss-test-web.build-test-results-tab&runId=3489657&resultId=148910)|dotnet/runtime#82317|
|[176247](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176247)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176247&view=ms.vss-test-web.build-test-results-tab&runId=3488129&resultId=153436)|dotnet/runtime#82255|
|[176220](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176220)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176220&view=ms.vss-test-web.build-test-results-tab&runId=3487494&resultId=151071)|dotnet/runtime#82310|
|[176018](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176018)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176018&view=ms.vss-test-web.build-test-results-tab&runId=3487474&resultId=145951)|dotnet/runtime#80987|
|[175879](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175879)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175879&view=ms.vss-test-web.build-test-results-tab&runId=3487013&resultId=149709)|dotnet/runtime#82190|
|[176178](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176178)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176178&view=ms.vss-test-web.build-test-results-tab&runId=3486972&resultId=150399)|dotnet/runtime#79169|
|[176173](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176173)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176173&view=ms.vss-test-web.build-test-results-tab&runId=3486968&resultId=150399)|dotnet/runtime#82250|
|[176169](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176169)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176169&view=ms.vss-test-web.build-test-results-tab&runId=3486611&resultId=159071)||
|[176158](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176158)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176158&view=ms.vss-test-web.build-test-results-tab&runId=3486548&resultId=155743)|dotnet/runtime#81518|
|[176096](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176096)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176096&view=ms.vss-test-web.build-test-results-tab&runId=3486072&resultId=153940)|dotnet/runtime#82313|
|[176052](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176052)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176052&view=ms.vss-test-web.build-test-results-tab&runId=3485663&resultId=150238)|dotnet/runtime#82310|
|[175978](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175978)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175978&view=ms.vss-test-web.build-test-results-tab&runId=3484660&resultId=163094)|dotnet/runtime#79169|
|[175939](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175939)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175939&view=ms.vss-test-web.build-test-results-tab&runId=3484198&resultId=150288)|dotnet/runtime#82249|
|[175929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175929)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175929&view=ms.vss-test-web.build-test-results-tab&runId=3484014&resultId=153061)|dotnet/runtime#82304|
|[175908](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175908)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175908&view=ms.vss-test-web.build-test-results-tab&runId=3483669&resultId=151937)|dotnet/runtime#82303|
|[175898](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175898)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175898&view=ms.vss-test-web.build-test-results-tab&runId=3483604&resultId=149143)|dotnet/runtime#79790|
|[175889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175889)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175889&view=ms.vss-test-web.build-test-results-tab&runId=3483359&resultId=153621)|dotnet/runtime#82302|
|[175854](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175854)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175854&view=ms.vss-test-web.build-test-results-tab&runId=3483098&resultId=145018)|dotnet/runtime#82300|
|[175804](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175804)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175804&view=ms.vss-test-web.build-test-results-tab&runId=3482460&resultId=155518)|dotnet/runtime#82295|
|[175796](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175796)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175796&view=ms.vss-test-web.build-test-results-tab&runId=3482255&resultId=191983)|dotnet/runtime#82206|
|[175734](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175734)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175734&view=ms.vss-test-web.build-test-results-tab&runId=3481148&resultId=155379)|dotnet/runtime#82292|
|[175707](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175707)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175707&view=ms.vss-test-web.build-test-results-tab&runId=3481036&resultId=167862)|dotnet/runtime#82249|
|[175646](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175646)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175646&view=ms.vss-test-web.build-test-results-tab&runId=3480365&resultId=154198)|dotnet/runtime#82086|
|[175567](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175567)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175567&view=ms.vss-test-web.build-test-results-tab&runId=3479051&resultId=153771)||
|[174946](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174946)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174946&view=ms.vss-test-web.build-test-results-tab&runId=3478944&resultId=144821)|dotnet/runtime#82235|
|[175490](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175490)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175490&view=ms.vss-test-web.build-test-results-tab&runId=3477689&resultId=155347)|dotnet/runtime#82181|
|[175483](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175483)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175483&view=ms.vss-test-web.build-test-results-tab&runId=3477620&resultId=135077)|dotnet/runtime#80960|
|[175420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175420)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175420&view=ms.vss-test-web.build-test-results-tab&runId=3477262&resultId=148839)|dotnet/runtime#82222|
|[175314](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175314)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175314&view=ms.vss-test-web.build-test-results-tab&runId=3476078&resultId=144446)|dotnet/runtime#82263|
|[175318](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175318)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175318&view=ms.vss-test-web.build-test-results-tab&runId=3475777&resultId=147412)|dotnet/runtime#82276|
|[175251](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175251)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175251&view=ms.vss-test-web.build-test-results-tab&runId=3475509&resultId=146444)|dotnet/runtime#82255|
|[175172](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175172)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175172&view=ms.vss-test-web.build-test-results-tab&runId=3474244&resultId=151254)|dotnet/runtime#81867|
|[175193](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175193)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175193&view=ms.vss-test-web.build-test-results-tab&runId=3474234&resultId=146125)|dotnet/runtime#81518|
|[175165](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175165)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175165&view=ms.vss-test-web.build-test-results-tab&runId=3474007&resultId=154310)|dotnet/runtime#82270|
|[175060](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175060)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175060&view=ms.vss-test-web.build-test-results-tab&runId=3472066&resultId=148939)|dotnet/runtime#80539|
|[175037](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175037)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=175037&view=ms.vss-test-web.build-test-results-tab&runId=3471164&resultId=148647)|dotnet/runtime#82206|
|[174980](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174980)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174980&view=ms.vss-test-web.build-test-results-tab&runId=3470537&resultId=168963)|dotnet/runtime#80960|
|[174906](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174906)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174906&view=ms.vss-test-web.build-test-results-tab&runId=3469964&resultId=154592)||
|[174879](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174879)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174879&view=ms.vss-test-web.build-test-results-tab&runId=3469884&resultId=164008)|dotnet/runtime#81518|
|[174826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174826)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174826&view=ms.vss-test-web.build-test-results-tab&runId=3469555&resultId=150661)|dotnet/runtime#80635|
|[174767](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174767)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174767&view=ms.vss-test-web.build-test-results-tab&runId=3468681&resultId=149211)|dotnet/runtime#82245|
|[174732](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174732)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174732&view=ms.vss-test-web.build-test-results-tab&runId=3468474&resultId=153840)|dotnet/runtime#80960|
|[174742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174742)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=174742&view=ms.vss-test-web.build-test-results-tab&runId=3468414&resultId=152510)|dotnet/runtime#82250|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|59|59|

### PR DESCRIPTION
**Pull request by wfurt**
MsQuic now works on Centos 7 & Mariner 2.0 
(fix for https://github.com/microsoft/msquic/issues/3422 rolled into 2.1.8) 

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-81973-merge-808ab19800c3444c99/System.Net.Quic.Functional.Tests/1/console.0eaba122.log

```
Console log: 'System.Net.Quic.Functional.Tests' from job 808ab198-00c3-444c-9983-c24f3929b683 (ubuntu.1804.amd64.open.rt) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-helix-amd64 on a00A27U


----- start Fri Mar 17 18:44:21 UTC 2023 =============== To repro directly: =====================================================
pushd .
/root/helix/work/correlation/dotnet exec --runtimeconfig System.Net.Quic.Functional.Tests.runtimeconfig.json --depsfile System.Net.Quic.Functional.Tests.deps.json xunit.console.dll System.Net.Quic.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 113 of 122 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.UnsupportedPlatforms_ThrowsPlatformNotSupportedException [SKIP]
      Condition(s) not met: "IsQuicUnsupported"
  Finished:    System.Net.Quic.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Quic.Functional.Tests  Total: 337, Errors: 0, Failed: 0, Skipped: 1, Time: 89.975s
/root/helix/work/workitem/e
```

fixes #81901

### CODE REVIEW

**Comment by carlossanlop** [comment]
@wfurt Friendly reminder that all RID changes that we want to include in the March Servicing Release need to be backported to 6.0 and 7.0 by tomorrow, which is the Code Complete day.

cc @mmitche @rbhanda

**Review by CarnaViire — APPROVED** [review]
LGTM, thanks! :shipit:

**Comment by wfurt** [comment]
Xml test failures are unrelated.

**Pull request merged**
