### PR TITLE
Fix GCStress timeouts in JIT/jit64

### LINKED ISSUE #85590: Test Failure - `jit64_do.0.1`
[Link](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257442&view=logs&j=6dfec640-5b96-5d95-2a5b-7c236ea2d5c5&t=caa3e910-40a5-5f97-2688-844d50a74012)

runtime-coreclr gcstress0x3-gcstress0xc

```
18:35:36.365 Running test: JIT/jit64/regress/ddb/87766/ddb87766/ddb87766.cmd
App Exit Code: 259
Expected: 100
Actual: 259
END EXECUTION - FAILED
FAILED
```

### PR DESCRIPTION
**Pull request by markples**
This includes several changes that seem to help with the timeouts. It might be overkill but seems like a good direction as this has been broken for a while.
- Change the test wrapper logic to only put one test in a TestExecutor so that the callstacks are much simpler.
- Factor the test wrapper logic into some helpers to simplify the main method. I also tried to make the "Full" and "XHarness" code generation very similar but didn't try to factor/unify them.
- Mark several tests as RequiresProcessIsolation so that their gcstress is kept separate from the rest of the tests.  Disables a large test under gcstress.
- Add gcstress striping to some merged groups.

Should fix #85590

### CODE REVIEW

**Comment by markples** [comment]
PTAL @kunalspathak (and this should help with the weekend gcstress failure)

**Review by kunalspathak — DISMISSED** [review]

**Comment by markples** [comment]
@trylek @davidwrighton We've been having gcstress timeouts occur every time we add merged test groups. The behavior has indicated some degradation over time within a gcstress process (probably the original motivation for striping). However, we've also seen individual tests take much longer, even when first or early in a merged test group run. My new theory is that the extra stack frames have a prohibitively high cost (and like it's just the test executor methods with the N try/catch blocks).

The current iteration of this PR is (overly) aggressive at simplifying the stack. It also still marks several tests as RequiresProcessIsolation as leftover from my initial experiments. Before I go further, I was hoping to get some feedback on the area. My thought is to just go to one test per TestExecutor (and therefore simplify the logic there), make XHarnessTestRunner match it for consistency, and keep the RPIs in order to get gcstress testing unblocked. They can be removed in the future, though this is low priority since individual tests don't hurt test throughput too much.

**Comment by markples** [comment]
fyi - I'm now looking at using BuildAsStandalone in gcstress builds to completely avoid merged test groups for now.  See #85284 though it will probably take a few rounds for me to get the yaml right.

**Comment by trylek** [comment]
@markples - Do you think we might be able to reduce some of these costs by emitting calls to the individual test entrypoints through helper methods so that each such helper method would have just the one try-catch block?

**Comment by markples** [comment]
@trylek This PR currently does that (it was easy by setting the grouping value to 1). I think that it helped but still hit a problem (though it's been long enough that I don't remember the details), which is why I had shelved this and was trying the BuildAsStandalone thing. However, that has hit an issue that (at least) one of the HardwareIntrinsics projects is big enough to time out (test merging can stripe -within- a project since it is dealing with individual tests).

**Comment by markples** [comment]
fyi - this is close but I'm waiting for test results

**Comment by markples** [comment]
@trylek I propose that we move forward with these fixes for now. They might be overkill, and we might change things again in the future, but this gets jit64 gcstress under control and lets us move forward. A few JIT\Regression legs are still slow but working.

(also resetting @kunalspathak 's review since much has changed since then)

**Review by trylek — APPROVED** [review]
Looks great to me, thanks Mark!

**Review by trylek — APPROVED** [review]
Looks great to me, thanks Mark!

**Comment by markples** [comment]
MemorySsa is failing elsewhere.

**Comment by markples** [comment]
running gcstress yet again because my other change restructued the groups

**Comment by markples** [comment]
Previous test run might have passed.. but the devops machine flaked out.  JIT/jit64 and JIT/opt appear to be ok.

**Comment by markples** [comment]
Some of the gc stress legs are still quite slow, suggesting more striping would be desirable.  Hopefully this current run is sufficient to unblock testing and that striping can be handled separately, but osx arm64 continues to be stubborn with this.

**Comment by markples** [comment]
Build analysis is showing a failure from a previous run of `runtime-coreclr gcstress0x3-gcstress0xc`.  (perhaps of interest to @JulieLeeMSFT @trylek @ivdiazsa ?)

Failure was in https://dev.azure.com/dnceng-public/public/_build/results?buildId=277134&view=results
Current run is https://dev.azure.com/dnceng-public/public/_build/results?buildId=277895&view=results

**Pull request merged**
