### PR TITLE
Fix IJW when managed tests are built on OSX

### LINKED ISSUE #36404: Triage tests regressing by building managed tests on OSX
The following test started regressing (currently in the `dev/infrastructure branch) as a result of the #36253 change to start building all managed test assemblies on OSX.

They will be disabled (in the `dev/infrastructure branch) as part of #36351

```xml
<!-- Fixed by #36482
-->
<ExcludeList Include="$(XunitTestBinBase)/readytorun/tests/mainv**/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/COM/ComWrappers/GlobalInstance/GlobalInstanceMarshallingTests/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/COM/ComWrappers/GlobalInstance/GlobalInstanceTrackerSupportTests/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/COM/NativeClients/DefaultInterfaces/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/COM/NativeClients/Dispatch/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/COM/NativeClients/Events/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/COM/NativeClients/Licensing/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/COM/NativeClients/Primitives/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/COM/NETClients/ConsumeNETServer/ConsumeNETServer/*"/>
<!-- Regressions apparently caused by building all tests on OSX/Linux
        Oddly these pass when the helix payload is downloaded and the test is run locally
-->
<ExcludeList Include="$(XunitTestBinBase)/Interop/IJW/CopyConstructorMarshaler/CopyConstructorMarshaler/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/IJW/FixupCallsHostWhenLoaded/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/IJW/LoadIjwFromModuleHandle/LoadIjwFromModuleHandle/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/IJW/ManagedCallingNative/ManagedCallingNative/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/IJW/NativeCallingManaged/NativeCallingManaged/*"/>
<ExcludeList Include="$(XunitTestBinBase)/Interop/IJW/NativeVarargs/NativeVarargsTest/*"/>
```
Could someone take a look?
/cc @jkoritzinsky @sbomer @AaronRobinsonMSFT

### PR DESCRIPTION
**Pull request by sdmaclea**
Fixes #36404

### CODE REVIEW

**Review by jkoritzinsky — CHANGES_REQUESTED** [review]
Why is the target defined multiple times in separate targets files instead of still in the `Interop.settings.targets` file?

**Comment by sdmaclea** [comment]
I needed it to be included late so that the `ResolveCmakeNativeProjectReference` is defined.

Including targets directly from `*.csproj` happens before any non-standard targets are defined.

I could change the csproj files to not include `Interop.setting.targets`, and move the includes to `*.csproj.targets` if you prefer.

If there is a better way to trigger the new targets during `CopyAllNativeProjectReferenceBinaries`, let me know.

**Comment by jkoritzinsky** [comment]
One option would be to change `Interop.settings.targets` to be a `Directory.Build.targets` file that's auto-imported and have it import the `Directory.Build.targets` up the directory tree and define the target after importing the higher-up `Directory.Build.targets`.

Also, I'd prefer if we could make the target depend on `CopyAllNativeProjectReferenceBinaries` if possible for style reasons.

**Comment by sdmaclea** [comment]
I assume you are OK with your proposal.  I am generally.  

My only concern would be whether the following property should go somewhere else.

```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Properties for all Interop managed test assets -->
  <PropertyGroup>
    <InteropCommonDir>$(MSBuildThisFileDirectory)common/</InteropCommonDir>
  </PropertyGroup>
```

**Comment by jkoritzinsky** [comment]
Maybe move that into a `Directory.Build.props` file?

**Comment by jkoritzinsky** [comment]
And yes, I am OK with my proposal. I was actually planning on doing my proposal in the future anyway. I just hadn't gotten around to it.

**Comment by sdmaclea** [comment]
And update `ReadMe.md`

**Comment by sdmaclea** [comment]
@jkoritzinsky That should be close to what you want

**Review by jkoritzinsky — APPROVED** [review]
Thanks!

**Pull request merged**
