### PR TITLE
LogicalName added for EmbeddedResource

### LINKED ISSUE #13703: Test failed: Regressions/coreclr/GitHub_22888/test22888
Fails everywhere with the following output

```
    Regressions/coreclr/GitHub_22888/test22888/test22888.sh [FAIL]
      
      Return code:      1
      Raw output file:      /private/tmp/helix/working/f2427664-a026-4dba-b8a1-dd6373c6197d/Work/14ef7c0b-d5e4-47dd-ba97-b7a66d40a8bd/Exec/Regressions/coreclr/Reports/Regressions.coreclr/GitHub_22888/test22888/test22888.output.txt
      Raw output:
      BEGIN EXECUTION
      /tmp/helix/working/f2427664-a026-4dba-b8a1-dd6373c6197d/Payload/corerun test22888.dll ''
      Failed to get resource stream from the test assembly
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/tmp/helix/working/f2427664-a026-4dba-b8a1-dd6373c6197d/Payload
      > /private/tmp/helix/working/f2427664-a026-4dba-b8a1-dd6373c6197d/Work/14ef7c0b-d5e4-47dd-ba97-b7a66d40a8bd/Exec/Regressions/coreclr/GitHub_22888/test22888/test22888.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /Users/runner/runners/2.159.2/work/1/s/bin/tests/OSX.x64.Checked/TestWrappers/Regressions.coreclr/Regressions.coreclr.XUnitWrapper.cs(1983,0): at Regressions_coreclr._GitHub_22888_test22888_test22888_._GitHub_22888_test22888_test22888_sh()
      Output:
        
        Return code:      1
        Raw output file:      /private/tmp/helix/working/f2427664-a026-4dba-b8a1-dd6373c6197d/Work/14ef7c0b-d5e4-47dd-ba97-b7a66d40a8bd/Exec/Regressions/coreclr/Reports/Regressions.coreclr/GitHub_22888/test22888/test22888.output.txt
        Raw output:
        BEGIN EXECUTION
        /tmp/helix/working/f2427664-a026-4dba-b8a1-dd6373c6197d/Payload/corerun test22888.dll ''
        Failed to get resource stream from the test assembly
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/tmp/helix/working/f2427664-a026-4dba-b8a1-dd6373c6197d/Payload
```

category:testing
theme:testing
skill-level:beginner
cost:small

### PR DESCRIPTION
**Pull request by rzsc**
The test is trying to get a manifest named "test22888resources.test22888.resources" but according to the rule from https://learn.microsoft.com/en-us/dotnet/core/resources/manifest-file-names:

_"If the resource file is colocated with a source file (.cs or .vb) of the same root file name, the full name of the first type that's defined in the source file is used for the manifest file name."_

The resource file "test22888.resx" colocated with a C# source file "test22888.cs" so the manifest gets name after the first type defined in the C# source file (TestAssemblyLoadContext.resources).

Here is the next paragraph from the aforementioned web page:

_"If a resource file is explicitly included in the project file as an EmbeddedResource item with LogicalName metadata, the LogicalName value is used as the manifest name. LogicalName takes precedence over any other metadata or setting."_

To solve the problem LogicalName="test22888resources.test22888.resources" attribute has been added to EmbeddedResource item in "test22888resources.csproj" project file to make the manifest name to be as the test expects it.

The test has been removed from the tests exclusion file "./src/tests/issues.targets".

Part of #84834, cc @dotnet/samsung

Fixes #13703

### CODE REVIEW

**Comment by jkotas** [comment]
Test introduced by https://github.com/dotnet/coreclr/pull/22925/

**Comment by clamp03** [comment]
Related Issue: https://github.com/dotnet/runtime/issues/13703

**Comment by jkotas** [comment]
The re-enabled test is failing on Mono:
```
/tmp/helix/working/A93108F6/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true test22888.dll ''
Failed to unload the test assembly
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   101
   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[Int32](Int32 expected, Int32 actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 90
   at __GeneratedMainWrapper.Main()
```
Mono does not support collectible assemblies that this test is exercising. Could you please keep the test disabled on Mono against https://github.com/dotnet/runtime/issues/34072 ? (Look for this issue number in issues.targets to find the right place where it should be disabled.

**Comment by rzsc** [comment]
> Mono does not support collectible assemblies that this test is exercising. Could you please keep the test disabled on Mono against #34072 ? (Look for this issue number in issues.targets to find the right place where it should be disabled.

Understood. I'm on it. Thanks!

**Comment by jkotas** [comment]
Is this ready for review?

**Review by clamp03 — APPROVED** [review]

**Review by tomeksowi — APPROVED** [review]

**Review by Bajtazar — APPROVED** [review]

**Review by sirntar — APPROVED** [review]

**Comment by clamp03** [comment]
> Is this ready for review?

@jkotas I think it is ready for review. Could you review it? Thank you.

**Comment by rzsc** [comment]
@jkotas, I can see that some checks were not successful...
Are these failures related to my changes?
I cannot deduce it from error messages...
I can see some warnings related to the test22888, the one I have modified and enabled. Shall I fix these warnings?
Thank you for all your help!

**Review by jkotas — APPROVED** [review]
Thanks

**Pull request merged**
