### PR TITLE
[mono][interp] Fix handing of native types

### LINKED ISSUE #61153: [Bug] MAUI templates crashing on iOS (Foundation.NSMutableData:AppendBytes)
### Description
Application is failing to start
```
=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSend_IntPtr_UIntPtr <0x0006e>
	  at Foundation.NSMutableData:AppendBytes <0x0004a>
	  at Foundation.NSData:FromStream <0x000dc>
	  at Microsoft.Maui.EmbeddedFontLoader:LoadFont <0x0006a>
	  at Microsoft.Maui.FontRegistrar:LoadEmbeddedFont <0x000a0>
	  at Microsoft.Maui.FontRegistrar:LoadNativeAppFont <0x0003a>
	  at Microsoft.Maui.FontRegistrar:GetFont <0x0011a>
	  at Microsoft.Maui.FontManager:CleanseFontName <0x00022>
	  at Microsoft.Maui.FontManager:CreateFont <0x0015e>
	  at System.Collections.Concurrent.ConcurrentDictionary`2:GetOrAdd <0x000e2>
	  at Microsoft.Maui.FontManager:GetFont <0x00074>
	  at Microsoft.Maui.FontManager:GetFont <0x00032>
	  at Microsoft.Maui.LabelExtensions:UpdateFont <0x0002a>
	  at Microsoft.Maui.LabelExtensions:UpdateFont <0x0001c>
	  at Microsoft.Maui.Handlers.LabelHandler:MapFont <0x0003e>
	  at Microsoft.Maui.Controls.Label:MapFont <0x0002e>
	  at <>c__DisplayClass5_0:<Add>b__0 <0x00048>
	  at Microsoft.Maui.PropertyMapper:UpdatePropertyCore <0x00036>
	  at Microsoft.Maui.PropertyMapper:UpdateProperties <0x0005e>
```
### Steps to Reproduce
- Install the latest main bits https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md

```
dotnet workload install maui `
   --from-rollback-file https://aka.ms/dotnet/maui/preview.10.json `
   --source https://aka.ms/dotnet6/nuget/index.json `
   --source https://api.nuget.org/v3/index.json
```

- dotnet new maui
- launch the iOS app

### Expected Behavior
doesn't crash

### Actual Behavior
crashes

### Basic Information

- Version with issue: main
- Last known good version: p10

This is acting like an issue with the iOS workloads.  If you change the version of MAUI to be p.10 but still use the p.11 iOS workloads the app still crashes.

### PR DESCRIPTION
**Pull request by BrzVlad**
Fixes https://github.com/dotnet/runtime/issues/61153

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by rolfbjarne** [comment]
@BrzVlad we'll need the support for our `nfloat` type going forward, but not for `nint` and `nuint`.

There are some tests here, not sure if those could apply to this scenario:

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/mono/mono/mini/builtin-types.cs

**Comment by SamMonoRT** [comment]
@masafa - this will need to be backported to 6.0.x at some point.

**Comment by BrzVlad** [comment]
Wasn't able to test this on 32bit so I just submitted this change to mono/mono for some additional test running : https://github.com/mono/mono/pull/21317

**Comment by SamMonoRT** [comment]
@BrzVlad please correct me if I'm wrong here --- but all validation is complete now. the change was ported to mono\mono locally to run a few more tests, and it's all green.
@steveisok @Redth @rolfbjarne - this is ready to be merged to main now and to be backported to the 6.0-maui (or whatever final name we settled on). @steveisok can you kick off whatever backport command needs to be done. At this point we don't think we need this in 6.0.x servicing.

**Pull request merged**
