### PR TITLE
fixing building of projects in VS

### LINKED ISSUE #34925: Not Building Referenced projects while BuildingInsideVisualStudio
After doing a pass of a vertical build if i build an individual project for a /p:BuildTargetFramework=netcoreapp5.0-unix config from the command line as ResolveProjectReferences builds all the projectReferences for this tfm.

This is not the case while building the project from building inside the VS eg 
```
stem.Utf8String.Experimental.dll

Build FAILED.

C:\Users\anagniho\.nuget\packages\microsoft.dotnet.genfacades\5.0.0-beta.20201.2\build\Microsoft.DotNet.GenPartialFacadeSource.targets(30,5): error : Could not find a part of the path 'C:\git\runtime\artifacts\bin\System.Runtime\netcoreapp5.0-Unix-Debug\System.Runtime.dll'. [C:\git\runtime\src\libraries\System.Utf8String.Experimental\src\System.Utf8String.Experimental.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:07.31
``` 
This is bcoz sdk assumes the project references are already build by the IDE and doesnt run the msbuild task during project references https://github.com/microsoft/msbuild/blob/64c8e4a18e7cf7f064fbad304ea7ed877cdaa0a1/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1812

By default we are building for all netcoreapp5.0-{TargetOS} inside the VS, we should either fix the msbuild or remove edit the default VS behavior

cc @ericstj @ViktorHofer @safern

### PR DESCRIPTION
**Pull request by Anipik**
Fixes https://github.com/dotnet/runtime/issues/34925

### CODE REVIEW

**Comment by safern** [comment]
How are we going to ensure SLN's are up to date if/when people add a new reference to these projects?

**Comment by Anipik** [comment]
> How are we going to ensure SLN's are up to date if/when people add a new reference to these projects?

Its difficult to catch using the build process. we can write a post build task than can be run on manually or automatically to catch this.

**Comment by ViktorHofer** [comment]
> Its difficult to catch using the build process. we can write a post build task than can be run on manually or automatically to catch this.

I think a better approach would be to have a central sln which contains all the ref, src and tests projects and replace the sln files in the project leafs with slnf (https://docs.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2019) files that reference the root sln. That keeps all the projects in a central place and the slnf ones can still be invoked via `dotnet build`, `dotnet restore` and any other target just like sln files.

cc @ericstj for opinions.

**Comment by ViktorHofer** [comment]
@Anipik what process did you follow to find the necessary P2Ps? I only see 21 slns updated even though we have many more, ie `Microsoft.Win32.Registry` is hitting the same issue during the design time build of its ref.

**Review by ViktorHofer — APPROVED** [review]

**Comment by Anipik** [comment]
> what process did you follow to find the necessary P2Ps? I only see 21 slns updated even though we have many more, ie Microsoft.Win32.Registry is hitting the same issue during the design time build of its ref.

I currently just did for the projects in the libraries src folder. i searched using regex.
I also skipped the projects having project references but targeting only ns.

**Comment by Anipik** [comment]
> Microsoft.Win32.Registry is hitting the same issue during the design time build of its ref.

are you doing  a ref pass before opening the project in the VS ?

**Pull request merged**
