### PR TITLE
ARM64: Recognize more STP patterns

### PR DESCRIPTION
**Pull request by EgorBo**
When `LowerStoreIndirCoalescing` fails to merge two stores it should at least make the stores STP-friendly (when it's legal). Example:
```cs
static void Test(ref Vector128<byte> g)
{
    Unsafe.Add(ref g, 0) = default;
    Unsafe.Add(ref g, 1) = default;
}
```
Codegen diff (on arm64):
```diff
; Method Bench:Test(byref) (FullOpts)
            stp     fp, lr, [sp, #-0x10]!
            mov     fp, sp
            movi    v16.4s, #0
-           str     q16, [x0]
-           movi    v16.4s, #0
-           str     q16, [x0, #0x10]
+           movi    v17.4s, #0
+           stp     q16, q17, [x0]
            ldp     fp, lr, [sp], #0x10
            ret     lr
-; Total bytes of code: 32
+; Total bytes of code: 28
```

+ remove quirk from assertprop.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Have you looked into generalizing `TryMakeIndirsAdjacent`? I think it would be a fair bit more general than this.

**Comment by EgorBo** [comment]
> Have you looked into generalizing `TryMakeIndirsAdjacent`? I think it would be a fair bit more general than this.

I have, but that was just a lot more work while here it's a few lines of code for -30kb diff, I guess this hack can be removed once `OptimizeForLdp` learns how to make code STP friendly

**Comment by jakobbotsch** [comment]
Hmm, let me give it a quick try. I think the only hard part is extending the smarter interference check, but perhaps that's not necessary to get most cases.

**Comment by EgorBo** [comment]
> Hmm, let me give it a quick try. I think the only hard part is extending the smarter interference check, but perhaps that's not necessary to get most cases.

Sure, go ahead 🙂

**Comment by jakobbotsch** [comment]
It took a bit of finesse (and let's see what CI says), but #102133 has a prototype

**Comment by EgorBo** [comment]
> It took a bit of finesse (and let's see what CI says), but #102133 has a prototype

Hoping to see https://dev.azure.com/dnceng-public/public/_build/results?buildId=672905&view=ms.vss-build-web.run-extensions-tab diffs there as well 😉

**Pull request closed without merging**
