### PR TITLE
JIT: Fix profiler enter callback init reg trash logic

### PR DESCRIPTION
**Pull request by jakobbotsch**
During prolog generation we sometimes generate code to call the profiler enter callback. This may trash the "initReg" that we expect to keep zeroed during the prolog. The logic to check if the initReg was being trashed was wrong in a couple of cases:
- Most backends did not take into account that the logic also trashes the registers used for arguments to the enter callback
- SysV x64 thought that the enter callback trashed the parameter registers, but it does not

This generally did not cause issues because `genFnPrologCalleeRegArgs` is unnecessarily conservative around whether or not it trashes `initReg`, and it comes after the profiler callback in the prolog. However, with the rewrite of the homing function that is not going to be the case anymore.

Fixes an issue I noticed by inspection over in #100572

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @BruceForstall

**Comment by BruceForstall** [comment]
[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=630260&view=ms.vss-build-web.run-extensions-tab) -- so no test coverage?

**Review by BruceForstall — APPROVED** [review]

**Comment by jakobbotsch** [comment]
> [No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=630260&view=ms.vss-build-web.run-extensions-tab) -- so no test coverage?

We have test coverage in stress due to `STRESS_PROFILER_CALLBACKS`. I hit the problem over in #100572. There it wasn't a problem in the baseline because `genFnPrologCalleeRegArgs` mistakenly was marking the initReg as clobbered (even though it didn't actually end up using it for anything).

**Pull request merged**
