### PR TITLE
[release/9.0] BinaryFormatter tests improvements

### PR DESCRIPTION
**Pull request by adamsitnik**
With what we have right now in `release/9.0`, most of the `BinaryFormatter` tests are skipped.

Backporting the following PRs is going to fix that:
- https://github.com/dotnet/runtime/pull/106737 (it touched more than just the BF, but those changes seem to be an improvement)
- https://github.com/dotnet/runtime/pull/106858
- https://github.com/dotnet/runtime/pull/106967
- https://github.com/dotnet/runtime/pull/107408
- https://github.com/dotnet/runtime/pull/107549

### CODE REVIEW

**Comment by ericstj** [comment]
I agree we want better coverage of these in 9.0.  If the fixes are test/infra only then we can treat as `tell` mode.

> I am going to mark it as a DRAFT because https://github.com/dotnet/runtime/issues/107534 tells me that we need to fix it first.

Yeah, that's my biggest concern here - is that we batch up all the related test or infra changes necessary. Once ready, make sure you run the optional pipelines that broke before.

**Review by ericstj — APPROVED** [review]

**Review by carlossanlop — APPROVED** [review]
Approving as tell-mode.

**Comment by carlossanlop** [comment]
@adamsitnik unfortunately the CI just finished with failures in tvos and ios arm64 that seem related to this change:

```
/private/tmp/helix/working/AAB50990/w/B50D0974/e/publish/ProxyProjectForAOTOnHelix.proj(116,5): error MSB3030: Could not copy the file "/tmp/helix/working/AAB50990/p/build/microsoft.netcore.app.runtime.tvos-arm64/runtimes/tvos-arm64/native/System.Runtime.Serialization.Formatters.xml" because it was not found.
```

Can you please address the failure and retarget this PR to the `release/9.0-rc2` branch? We can still treat this as tell-mode when retargeted (no Tactics involvement needed).

**Review by carlossanlop — CHANGES_REQUESTED** [review]
Related CI failure.

**Comment by ericstj** [comment]
This is this issue:
```
/private/tmp/helix/working/AAB50990/w/B50D0974/e/publish/ProxyProjectForAOTOnHelix.proj(116,5): error MSB3030: Could not copy the file "/tmp/helix/working/AAB50990/p/build/microsoft.netcore.app.runtime.tvos-arm64/runtimes/tvos-arm64/native/System.Runtime.Serialization.Formatters.xml" because it was not found.
/private/tmp/helix/working/AAB50990/w/B50D0974/e/publish/ProxyProjectForAOTOnHelix.proj(116,5): error MSB3030: Could not copy the file "/tmp/helix/working/AAB50990/p/build/microsoft.netcore.app.runtime.tvos-arm64/runtimes/tvos-arm64/native/System.Runtime.Serialization.Formatters.pdb" because it was not found.
```

I think we need more fixes for this, let me find them.

**Comment by ericstj** [comment]
We need 
https://github.com/dotnet/runtime/pull/107079
https://github.com/dotnet/runtime/pull/107348

cc @ivanpovazan

I will add those to this PR.

**Comment by adamsitnik** [comment]
> Related CI failure.

Great catch, apologies for missing it.

> I will add those to this PR.

Thanks a lot @ericstj !

**Review by ivanpovazan — APPROVED** [review]
LGTM!

Maybe just for reference included the needed mono CI changes in the PR description for clarity (so it is not lost in the comments)

**Review by carlossanlop — APPROVED** [review]
Thanks @ericstj ! :shipit:

**Pull request merged**
