### PR TITLE
Update DacTableGen.csproj to escape a path in a command-line

### PR DESCRIPTION
**Pull request by logiclrd**
This fixed a build error for me. My user profile path contains a space.

### CODE REVIEW

**Comment by hoyosjs** [comment]
Hey @logiclrd, thanks for the contribution. Sorry, but there is another PR open for this case: #44913. That PR had a failure I was investigating so I couldn't merge it.

**Comment by logiclrd** [comment]
Looks like that PR has fallen out-of-date, though, and is modifying a path that doesn't exist any more. It also works by changing the value of the variable upstream of the command, which means it could potentially impact things other than the command itself.

**Comment by logiclrd** [comment]
Actually I expanded hidden parts and see now that the definition of `VSWherePath` is scoped to the target whose only purpose is the `Exec`, so I guess that's not an issue. :-)

**Comment by hoyosjs** [comment]
> Looks like that PR has fallen out-of-date, though, and is modifying a path that doesn't exist any more. It also works by changing the value of the variable upstream of the command, which means it could potentially impact things other than the command itself.

This is the only file/target that uses said property, and is slightly more readable than the escaped version.

**Comment by hoyosjs** [comment]
> Actually I expanded hidden parts and see now that the definition of `VSWherePath` is scoped to the target whose only purpose is the `Exec`, so I guess that's not an issue. :-)

Beat me to it :) If the other contributor doesn't respond with an update or permission to update his branch, I'll merge this one. I feel bad, I should've been more expedient with the reviews, but it's been a long time triaging issues that are coming in after the 5.0 release. Apologies.

**Comment by logiclrd** [comment]
You're right that it's easier to read, I feel like it'd be better that way regardless of which branch is merged. I'll update mine to match.

**Comment by logiclrd** [comment]
I'm not hung up on which PR ultimately gets merged :-) As long as my builds stop bumping into this :-D

**Comment by hoyosjs** [comment]
The owner of the other PR responded. I'll close this one. Thanks for this nonetheless.

**Pull request closed without merging**
