### PR TITLE
Added DEBUG switches for roundtrip ILASM

### LINKED ISSUE #72127: ILASM roundtrip fails on `poison.sh`
ILASM roundtrip fails on the test `JIT/Directed/debugging/poisoning/poison/poison.sh`

```
BEGIN EXECUTION
/datadisks/disk1/work/AA48093E/p/ildasm -raweh -unicode -out=poison.dasm.il poison.dll
/datadisks/disk1/work/AA48093E/p/ilasm -output=poison.asm.dll poison.dasm.il

Microsoft (R) .NET IL Assembler.  Version 7.0.0-ci
C
Assembling 'poison.dasm.il'  to EXE --> 'poison.asm.dll'
Source file is UNICODE

Assembled method Program::Main
Assembled method Program::VerifyPoison
Assembled method Program::VerifyZero
Assembled method Program::AllEq
Assembled method Program::.ctor
Creating PE file

Emitting classes:
Class 1:Program
Class 2:Program�GCRef
Class 3:Program�WithoutGCRef
Class 4:Program�Massive
Class 5:Program�Massive�<Bytes>e__FixedBuffer

Emitting fields and methods:
Global
Class 1Methods: 5;
Class 2Fields: 1;
Class 3Fields: 3;
Class 4Fields: 1;
Class 5Fields: 1;
Resolving local member refs: 9 -> 9 defs, 0 refs, 0 unresolved

Emitting events and properties:
Global
Class 1
Class 2
Class 3
Class 4
Class 5
Resolving local member refs: 0 -> 0 defs, 0 refs, 0 unresolved
Writing PE file
Operation completed successfully
/datadisks/disk1/work/AA48093E/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false poison.asm.dll ''
END EXECUTION OF IL{D}ASM BINARY - FAILED 101 vs 100
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/datadisks/disk1/work/AA48093E/p
/datadisks/disk1/work/AA48093E/w/B8F7099E/e/JIT/Directed/debugging/poisoning/poison/poison.sh
Expected: True
Actual:   False
```

### PR DESCRIPTION
**Pull request by TIHan**
**Description**

Should resolve: https://github.com/dotnet/runtime/issues/72127 - this was failing because `ilasm.exe` was not being invoked with the `/DEBUG` flag when the corresponding project was.

**Acceptance Criteria**

- [x] ILASM Roundtrip CI does not have a failure on `poison.sh`
- [x] No additional ILASM roundtrip failures

### CODE REVIEW

**Comment by TIHan** [comment]
Triggered manually: https://dev.azure.com/dnceng/public/_build/results?buildId=1888007&view=results

**Comment by TIHan** [comment]
@dotnet/jit-contrib This is ready. I'm running the ilasm roundtrip tests in CI, there are known failures, but we should not see the poison in the list. I tested this manually and adding the `<_IlasmSwitches>$(_IlasmSwitches) -DEBUG</_IlasmSwitches>` fixes the roundtrip test.

**Comment by TIHan** [comment]
Pinging @dotnet/jit-contrib again - should be a quick review

**Review by BruceForstall — CHANGES_REQUESTED** [review]
This change doesn't seem quite right; it's not general.

Why is this specific to the poison test?

There is already code that uses the various project file configurations to set the correct ilasm flags. Is this not getting used somehow? See:

https://github.com/dotnet/runtime/blob/1f0582e1ee1e6bf05df41aa4cf0d246584c280c8/src/coreclr/.nuget/Microsoft.NET.Sdk.IL/targets/Microsoft.NET.Sdk.IL.targets#L126-L133

**Comment by TIHan** [comment]
@BruceForstall - I did see those targets, but I believe the build uses this if you are compiling an `.ilproj` right? I think that is the case which is why it never picks up those flags for `_IlasmSwitches`. Our test targets just happen to use the same name `_IlasmSwitches`.

> Why is this specific to the poison test?

In order to get the correct poisoned value, `0xCD`, the assembly must be marked as debuggable, otherwise the runtime will not output the poisoned value, `0xCD`, which is why the roundtrip test was failing.

Here is the code in the runtime that checks to poison the variable:
```cpp
    // Returns true if address-exposed user variables should be poisoned with a recognizable value
    bool compShouldPoisonFrame()
    {
#ifdef FEATURE_ON_STACK_REPLACEMENT
        if (opts.IsOSR())
            return false;
#endif
        return !info.compInitMem && opts.compDbgCode;
    }
```

`opts.compDbgCode` would return false if we did not compile the `.il` with the `-DEBUG` flag.

> it's not general

Before, I did try to generalize this in the test targets if we notice the `DebugType` as `PdbOnly`/`Full`/etc., - see this commit: https://github.com/dotnet/runtime/pull/72128/commits/564dbfdbbbcfaff7bdb9dc36c09a6959405f3967#diff-7a4e5f3ff147c4363c6363eb39d726682c301afae8ab8e71518eba2dba1bb505R38
But it was not working; the conditions never returned true. So, I went for setting the switches directly in the specific project and that worked. I think it's ok that we set it like this for this one specific test.

**Comment by BruceForstall** [comment]
> I did see those targets, but I believe the build uses this if you are compiling an `.ilproj` right?

I believe that's right; I realized that last night, too. So the .csproj round-trip testing wouldn't see it.

> I did try to generalize this in the test targets if we notice the DebugType as PdbOnly/Full/etc., - see this commit: https://github.com/dotnet/runtime/commit/564dbfdbbbcfaff7bdb9dc36c09a6959405f3967#diff-7a4e5f3ff147c4363c6363eb39d726682c301afae8ab8e71518eba2dba1bb505R38

That's the fix I was thinking. I tried a slight variant, https://github.com/dotnet/runtime/compare/main...BruceForstall:TryFixIlasmRoundTripDebugFlag, and it seemed to work. I assumed for .ilproj it would add the switches twice, but that doesn't seem to be true (and I don't know why).

Anyway, I'll go ahead and approve.

**Review by BruceForstall — APPROVED** [review]

**Comment by TIHan** [comment]
I'll update this with your variant. I bet mine didn't work because I didn't put it in a property group...

**Comment by TIHan** [comment]
CI failure is not related, merging.

**Pull request merged**
