### PR TITLE
[RISC-V] Increase timeouts in CustomConverterTests

### PR DESCRIPTION
**Pull request by yurai007**
This patch fixes System.Text.Json.Serialization.Tests.CustomConverterTests on Debug build.

Part of https://github.com/dotnet/runtime/issues/84834
cc @dotnet/samsung

### CODE REVIEW

**Comment by risc-vv** [comment]
<details><summary>71892ea0 is being scheduled for building and testing</summary>

GIT: `71892ea0cf288b5ab11937ac5c2fdc31010168ff`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by risc-vv** [comment]
<details><summary>cef4dbac is being scheduled for building and testing</summary>

GIT: `cef4dbac8939a44def6ba29c9effe534fecd8e1d`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Review by Bajtazar — APPROVED** [review]

**Review by tomeksowi — APPROVED** [review]

**Review by sirntar — APPROVED** [review]

**Comment by risc-vv** [comment]
<details><summary>d9ff79b7 is being scheduled for building and testing</summary>

GIT: `d9ff79b778978486fd042f8897c9c7e0bcf6fe21`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by yurai007** [comment]
@jkotas: Could you please take a look on this PR?

**Review by eiriktsarpalis — APPROVED** [review]

**Comment by jkotas** [comment]
What makes this test too slow? The test does very little

**Comment by jkotas** [comment]
Can we also delete `[ActiveIssue("https://github.com/dotnet/runtime/issues/66371", typeof(PlatformDetection), nameof(PlatformDetection.IsMonoInterpreter))]` that was working around the test being too slow?

**Comment by yurai007** [comment]
> What makes this test too slow? The test does very little

If I remember correctly it's about _JsonSerializer.Serialize_ call that consume lot of cycles on Debug build. I can provide much more details on Wednesday (I'm off tomorrow) if you want.

**Comment by jkotas** [comment]
> execution time is dominated by RemoteExecutor.Invoke that takes ~30s. 

Yes, it looks like every that uses RemoteExecutor has problems with timeouts in RiscV test environment based on the fixes that you are submitting (e.g. #108702 cc @sirntar). Would it be better to make a central fix in RemoteExecutor instead of trying to fix RemoteExecutor tests one at a time? There are a lot of RemoteExecutor tests in the repo.

**Comment by sirntar** [comment]
> Would it be better to make a central fix in RemoteExecutor instead of trying to fix RemoteExecutor tests one at a time? There are a lot of RemoteExecutor tests in the repo.

What do you mean by central fix? Should we directly change [RemoteExecutor.cs#L21C7-L21C66](https://github.com/dotnet/arcade/blob/e4df2888e714255352a6afa2ec1246e70ac21a49/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs#L21C7-L21C66), or should we create one PR with all the time increases needed for rv64?

**Comment by jkotas** [comment]
> Should we directly change [RemoteExecutor.cs#L21C7-L21C66](https://github.com/dotnet/arcade/blob/e4df2888e714255352a6afa2ec1246e70ac21a49/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs#L21C7-L21C66), or should we create one PR with all the time increases needed for rv64?

@ViktorHofer @dotnet/area-infrastructure-libraries Do you have a preference?

The problem is that RemoteExecutor needs much higher timeout in RiscV test environment. Here are a few options:

(1) Change the implementation of RemoteExecutor to read a timeout multiplier from env. variable that will be set in the RiscV test environment. This is my personal preference.
or
(2) Change the implementation of RemoteExecutor to use a different timeout default for RiscV.
or 
(3) Change every instance of RemoteExecutor in this repo to go through a RemoteExecutor factory in TestUtils that will adjust RemoteExecutor timeout for RiscV.

**Comment by yurai007** [comment]
> Yes, reading from a new env var in RemoteExecutor makes most sense and is the easiest option. Just make sure that the env var is respected in both CI (helix) and locally (xunit.console & vstest).

@ViktorHofer: 

I think https://github.com/dotnet/arcade/pull/15215 works fine locally but I'm not very familiar with rest of what you suggested. Could you please give me some tips what actually should be done for helix and vstest?

**Comment by ViktorHofer** [comment]
For VSTest, set the env var here: https://github.com/dotnet/runtime/blob/2bb4bb7ef9435c58adaf079dc9c07b2b77e79843/eng/testing/.runsettings#L21

If you need to pass a non static value in, use the `$$` approach same with the other settings and overwrite that marker in runsettings.targets: https://github.com/dotnet/runtime/blob/2bb4bb7ef9435c58adaf079dc9c07b2b77e79843/eng/testing/runsettings.targets#L39

---

For xunit.console (which is invoked via the RunTests.cmd/sh script), you want to add `SetScriptCommands` msbuild items, similar as this one: https://github.com/dotnet/runtime/blob/2bb4bb7ef9435c58adaf079dc9c07b2b77e79843/eng/testing/tests.targets#L73-L74

They then get encoded into the RunTests script. You can find that script in the output directory of a test app.

---

Helix invokes the test via the RunTests script so this should automatically work with the above work. Double check that test console log on AzDO in the PR contains the set/export line. Just to make sure that this works.

**Comment by jkotas** [comment]
@ViktorHofer This is not going to be used by Helix or vstest currently. It is only going to be only used by Samsung when running risc-v tests under qemu or on risc-v boards. I would expect that they can just set this in the environment.

**Comment by yurai007** [comment]
Closing after https://github.com/dotnet/arcade/pull/15215 merge.

**Pull request closed without merging**
