### PR TITLE
Transform local indirections off of `TYP_BLK` locals; support numbering exposed LCL_FLDs

### PR DESCRIPTION
**Pull request by SingleAccretion**
The two changes help to fix the CQ gap that exists today between `LCL_FLD` and `IND(LCL_ADDR)` forms of access to address-exposed locals.

Positive [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=114919&view=results), with some regressions due to the usual reasons associated with more CSEing (e. g. the large x86 test regressions are actually PerfScore improvements). A bit of a TP regression due to more VNing, will be payed for with #79722.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
This will unblock #79722.

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
The failures look like they might be related?

**Comment by SingleAccretion** [comment]
Taking a look...

**Review by jakobbotsch — APPROVED** [review]
LGTM!

**Pull request merged**
