### PR TITLE
Implement MIPS64 RID

### PR DESCRIPTION
**Pull request by xiangzhai**
https://github.com/gsvm/loongson-dotnet/issues/6

\cc @jkotas @am11

Thanks,
Leslie Zhai

### CODE REVIEW

**Comment by am11** [comment]
[this can be done separately]
Do we also need the distro support for MIPS architecture? Note that with distros support, we get (an additional) ability to target distro-specific packages or configurations; as in, it will not affect the ability to build the portable product for `linux-mips64`, it will only help support the scenarios which care about distros (e.g. NuGet packages sometimes target special version of package for particular distro and RID resolver knows how to find the best match, based on these graphs).

cc @ericstj

**Comment by xiangzhai** [comment]
> Do we also need the distro support for MIPS architecture?

\cc @theaoqi

**Comment by xiangzhai** [comment]
> runtime Failing after 190m — Build #20200914.3 failed

False positive?

**Comment by jkotas** [comment]
Related to #38069

**Review by ericstj — APPROVED** [review]

**Pull request merged**
