### PR TITLE
CI: Fix helix test results reporting

### LINKED ISSUE #74699: Helix test results are not getting uploaded for a lot of jobs
For `runtime` pipeline, with rolling [builds](https://dev.azure.com/dnceng/public/_build/results?buildId=1970276&view=results).

[Working case in wasm/runtime-tests](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ddf74c289d6e4e02bb/JIT.CodeGenBringUpTests/1/console.39732105.log?helixlogtype=result):

```
   JIT.CodeGenBringUpTests.XUnitWrapper  Total: 29, Errors: 0, Failed: 0, Skipped: 0, Time: 30.775s
+ export _commandExitCode=0
+ /usr/bin/python3 -u /datadisks/disk1/work/BB7B0A43/w/A9DB096A/u/xharness-event-processor.py
/usr/bin/python3: can't open file '/datadisks/disk1/work/BB7B0A43/w/A9DB096A/u/xharness-event-processor.py': [Errno 2] No such file or directory
+ /usr/bin/python3 /datadisks/disk1/work/BB7B0A43/p/reporter/run.py https://dev.azure.com/dnceng/ public 50501656 eyJ0eXAiOiJKV1 ....
2022-08-26T21:27:53.422Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2022-08-26T21:27:53.422Z	INFO   	run.py	__init__(42)	read_results	Searching '/datadisks/disk1/work/BB7B0A43/w/A9DB096A/e' for test results files
2022-08-26T21:27:53.422Z	INFO   	run.py	__init__(48)	read_results	Found results file /datadisks/disk1/work/BB7B0A43/w/A9DB096A/e/testResults.xml with format xunit
2022-08-26T21:27:53.427Z	INFO   	run.py	__init__(42)	read_results	Searching '/datadisks/disk1/work/BB7B0A43/w/A9DB096A/uploads' for test results files
2022-08-26T21:27:53.428Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 29 test reports to '/datadisks/disk1/work/BB7B0A43/w/A9DB096A/e/__test_report.json'
2022-08-26T21:27:53.428Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 7735 bytes
```

### Broken cases

1. [Wasm/AOT/windows](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7fe0006661664ba3a5/WasmTestOnBrowser-System.Runtime.Tests/1/console.d21a3b3a.log?helixlogtype=result):

```
XHarness exit code: 0

C:\helix\work\workitem\e\wasm_build\AppBundle>set EXIT_CODE=0 
----- end Fri 08/26/2022 21:54:44.42 ----- exit code 0 ----------------------------------------------------------
XHarness artifacts: C:\helix\work\workitem\uploads\xharness-output
python: can't open file 'C:\helix\work\workitem\u\xharness-event-processor.py': [Errno 2] No such file or directory
ERROR: The process "corerun.exe" not found.

[END EXECUTION]
Exit Code:0
```

2. [Wasm/linux](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5d06d13627bf4dabaf/normal-Microsoft.CSharp.Tests/1/console.9a024754.log?helixlogtype=result):

```
XHarness exit code: 0
/datadisks/disk1/work/B24B0983/w/A9D4099F/e /datadisks/disk1/work/B24B0983/w/A9D4099F/e
----- end Fri Aug 26 21:08:51 UTC 2022 ----- exit code 0 ----------------------------------------------------------
XHarness artifacts: /datadisks/disk1/work/B24B0983/w/A9D4099F/uploads/xharness-output
+ export _commandExitCode=0
+ /usr/bin/python3 -u /datadisks/disk1/work/B24B0983/w/A9D4099F/u/xharness-event-processor.py
/usr/bin/python3: can't open file '/datadisks/disk1/work/B24B0983/w/A9D4099F/u/xharness-event-processor.py': [Errno 2] No such file or directory
+ exit 0
['normal-Microsoft.CSharp.Tests' END OF WORK ITEM LOG: Command exited with 0]
```

- The above 2 cases are not running `reporter/run.py`. The test results can't be seen via kusto.
- It seems to be working with [this](https://dev.azure.com/dnceng/public/_build/results?buildId=1966033&view=results), but failing on the [next rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1967489&view=results). And the changes between those - https://github.com/dotnet/runtime/compare/7b0227d5...8755447e .

- This is for wasm, rolling builds, and each column represents a different CI job:

Screen Shot 2022-08-27 at 5 23 12 AM

Note: the `xharness-event-processor.py` error can be ignored.

cc @lewing @steveisok @akoeplinger @ViktorHofer @premun

### PR DESCRIPTION
**Pull request by radical**
PR #73060 broke uploading of helix test results. This was caused by the
change:

```xml
      <HelixPostCommands>@(HelixPostCommand)</HelixPostCommands>
```

This is overwriting the existing value of `$(HelixPostCommands)`, which
gets set to have the upload script invocation in https://github.com/dotnet/arcade/blob/34dff939b4a91e4693f78a856e0e055c1a3f3fba/src/Microsoft.DotNet.Helix/Sdk/tools/azure-pipelines/AzurePipelines.MonoQueue.targets#L8-L15 at evaluation time.

Fix by *appending* to the property.

Thanks to ChadNedzlek for finding the cause!

Fixes https://github.com/dotnet/runtime/issues/74699 .

### CODE REVIEW

**Review by ChadNedzlek — APPROVED** [review]
Make sure the test count in the PR build comes back up to 3 millionish, and this should be good.

**Review by hoyosjs — APPROVED** [review]

**Comment by akoeplinger** [comment]
Looks like we had a new failing test sneak in while this was broken, disabled it (see https://github.com/dotnet/runtime/issues/74781)

**Review by lewing — APPROVED** [review]

**Comment by radical** [comment]
Does this need to wait for these jobs that we are re-running?

**Comment by steveisok** [comment]
> Does this need to wait for these jobs that we are re-running?

I think it's ok to merge because it's high impact.

**Pull request merged**
