### PR TITLE
Remove unused code from old IJW path

### PR DESCRIPTION
**Pull request by elinor-fung**
These look like leftovers from how Framework did IJW.

cc @AaronRobinsonMSFT @jkoritzinsky

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
@dotnet/dotnet-diag-contrib for `debug/` changes.

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by hoyosjs** [comment]
@dotnet/dotnet-diag

**Review by noahfalk — APPROVED** [review]
As far as I know nidump is dead code itself, so all good : )

**Comment by elinor-fung** [comment]
> nidump is dead code itself

Wait, what - as in we could actually delete `NativeImageDumper` and have `DumpNativeImages` just not do anything / be not impl?

**Comment by AaronRobinsonMSFT** [comment]
>As far as I know nidump is dead code itself, so all good : )

@noahfalk Heads up, you've told the interop team there is dead code... there is going to be a race to delete it.

**Comment by sdmaclea** [comment]
@AaronRobinsonMSFT We discussed lasted night that all fragile ngen specific code was dead since 3.1.  We were wondering why it wasn't deleted.

**Comment by jkoritzinsky** [comment]
Last I heard, Samsung was continuing to use it in 3.1 after we disabled it. @gbalykov is Tizen still using fragile NGen, or has Tizen moved to large version bubble crossgen2?

**Comment by gbalykov** [comment]
cc @alpencolt

**Comment by davmason** [comment]
@jkotas @davidwrighton is there a reason we haven't deleted everything under `FEATURE_PREJIT`? I did a quick grep of src\coreclr and don't find anything that defines it any more.

**Comment by hoyosjs** [comment]
I asked Jan earlier today to see if fragile was supported as a customer scenario - even if the framework doesn't ship this way, some customers might use it. However, the answer is no. This is just bits waiting to rot. Prejit will eventually go. Starting with the DAC doesn't sound like a bad idea as it has size impact on singlefile.

**Comment by alpencolt** [comment]
We work to bring .NET 6 with R2R Large Version Bubble for Tizen but it still has lower performance comparing to FNV. At the same time there were works to reanimate fragile mode in .NET 6 internally as backup plan.
If we'll choose second way we'll share sources, but would be good if current FNV code will not be deleted until .NET 6 release.

**Pull request merged**
