### PR TITLE
Update debug dump template after runfo update to include dumps

### PR DESCRIPTION
**Pull request by safern**

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
Can you have the script fix `<path-to-dump>` and `<path-to-dmp>` so they are the actual path to the dump now? The ideal is I can just copy paste the commands

**Comment by safern** [comment]
The reason why I didn't do that was because there could be multiple dumps produced in a test run. However I could try emitting a command per dump I find when writing the md file or just grab the first dump and use that as the dump name to calculate the path?

**Comment by danmoseley** [comment]
One command for each dump sounds good? Anything we can do to make it possible to just copy paste and get debugging. Even for someone who never contributed to the repo before.

**Comment by safern** [comment]
@danmoseley I added a dump command per dump found on the helix machine. Here is an example of how it would look like if there are multiple dumps: https://gist.github.com/safern/393de39fd8b759441a769d4ae0274e0a

Let me know if you like that of if you have more suggestions to make it an easier/better experience.

**Comment by danmoseley** [comment]
Looking good. Maybe worth you doing a quick test that it also works for the "core" naming pattern not just ".dmp"

I guess we don't know which are managed dumps -- native dumps won't do anything useful if you pass them to dotnet dump analyze. That seems like a problem we don't need to solve today.

**Comment by danmoseley** [comment]
> Open WinDbg and open the dump with File>Open Dump.

Perhaps here we can have the template be something like

> Open WinDbg, and open one of the dumps listed below with File>Open Dump.
> <win-path-to-dump>

We can't give the path to Windbg - I guess most folks will open it from the start menu - but we can list the dumps there so they don't have to look down the page.

**Review by danmoseley — APPROVED** [review]
thank you for doing this

**Comment by danmoseley** [comment]
I'm looking forward to trying this out!!

**Comment by safern** [comment]
> Open WinDbg, and open one of the dumps listed below with File>Open Dump.
<win-path-to-dump>

Good idea. Added that.

There are more things that I'd like to do, like, having sections that are Linux specific with some marker and nuking those out when the script is running on a Windows workitem for example, the commands that point to `lldb`.

> Looking good. Maybe worth you doing a quick test that it also works for the "core" naming pattern not just ".dmp"

Done, everything seems working just fine.

**Pull request merged**
