### PR TITLE
Re-enable Windows 7 and Windows8.1 helix queues

### LINKED ISSUE #32231: All test work items are failing for Windows x86 on CI frequently
https://dnceng.visualstudio.com/public/_build/results?buildId=519192&view=ms.vss-test-web.build-test-results-tab&runId=16414696&paneView=debug

Configuration: `netcoreapp5.0-Windows_NT-Release-x86-CoreCLR_release-Windows.7.Amd64.Open`

```
console.645a205c.log:
  https://helix.dot.net/api/2019-06-17/jobs/f6a05845-5714-48e5-ba97-d561c749dc3b/workitems/Common.Tests/files/console.645a205c.log

dotnet.exe.2392.dmp:
  https://helix.dot.net/api/2019-06-17/jobs/f6a05845-5714-48e5-ba97-d561c749dc3b/workitems/Common.Tests/files/dotnet.exe.2392.dmp
```

cc @jkotas @safern

### PR DESCRIPTION
**Pull request by safern**
Fixes: https://github.com/dotnet/runtime/issues/32231

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]
Assuming that they are now green and that the core reduction doesn't hinder us here.

**Comment by safern** [comment]
@MattGal will core reduction impact us on this?

**Comment by MattGal** [comment]
> @MattGal will core reduction impact us on this?

Hard to say... I'd guess "mostly not"?  The queues have been reduced to 15 and 16 D2_v3 VMs apiece... which under regular loads is actually probably enough. 

Seeing as the core reduction stuff isn't exactly optional, I think if you want this coverage (and indeed you really do on Win7, what with its windows apis predating the modern type) and it's timing out you simply need to up the timeout on the leg waiting for the tests to execute.  16 machines doing a single runtime run is pretty fast

**Comment by safern** [comment]
I believe the timeout is 2 and a half hours which should be enough.

**Comment by safern** [comment]
Builds are green but will re-run just for additional testing.

**Pull request merged**
