### PR TITLE
Initial work to enable native events in EventPipe

### PR DESCRIPTION
**Pull request by LakshanF**
Initial support for native event support to `EventPipe`, with GC events seen with the RuntimeProvider, that matches the existing `EtwProvider` support in `NativeAOT`.

Similar to the existing `EtwProvider` work in `NativeAOT`, the `EventPipeProvider` code is checked in, as opposed to using the python generated code. Unlike the `EtwProvider`, the code is in the opt-in `EventPipe` library (`eventpipe-enabled.lib`). There is corresponding minimal implementation in the disabled default `EventPipe` (`eventpipe-disabled.lib`).

Both managed and native events can be seen with tools like `PerfView` or dotnet-trace (collect option) by enabling the providers (in the native case, with `Microsoft-Windows-DotNETRuntime` for dotnet-trace and by selecting GC options in `PerfView`).

There will be a future effort to enhance the existing GC events with the right set of native events for `NativeAOT`.

### CODE REVIEW

**Review by davidwrighton — APPROVED** [review]
Looks ok, but I'd like to see a signoff from someone actively working on NativeAOT as well.

**Review by VSadov — APPROVED** [review]
LGTM Thanks!!

**Pull request merged**
