### PR TITLE
[release/6.0.1] add support for macOS 12

### PR DESCRIPTION
**Pull request by wfurt**
## Customer Impact

macOS 12.0 Monterey was released this week, support for it missed the 6.0 release train. 
without RID and fixes to determine OS version packaging may not work correctly. 

## Testing

I mentally verified that `dotnet --info' returns expect value. (e.g. does not fall-back to basic osx-x64)

## Regression

no. new OS support.

## Risk

small. Should not impact other platform. 5.x and 3.1 will need separate changes.

### CODE REVIEW

**Comment by wfurt** [comment]
BTW I'm not sure if we need usual packaging changes for platform @Anipik  and how that fits with current 6.0 process. For now, I did not put them in.

**Review by vitek-karas — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  We should take for consideration in 6.0.x

**Review by agocke — APPROVED** [review]

**Comment by Anipik** [comment]
We will need to add the packaging changes here. here are the guidelines https://github.com/dotnet/runtime/blob/release/6.0/docs/project/library-servicing.md

**Comment by wfurt** [comment]
Thanks @Anipik for the update. I'm swamped with servicing and I did not find time to work on this again.

**Comment by Anipik** [comment]
> Thanks @Anipik for the update. I'm swamped with servicing and I did not find time to work on this again.

welcome :)

**Pull request merged**
