### PR TITLE
Remove unnecessary ! (null-forgiving) operator used within an if (not null) block

### PR DESCRIPTION
**Pull request by ahsonkhan**

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@layomia Is this test failure a known issue (its only failing on `Libraries Test Run release mono Linux x64 Debug`), or am I missing something in my change that is uncovering the test failure?
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-47054-merge-58ff9fd4737e4e94a0/System.Text.Json.Tests/console.25869946.log?sv=2019-07-07&se=2021-02-04T19%3A57%3A23Z&sr=c&sp=rl&sig=3GoEcVFVwkTeCMFcsHkr9pZ9iv90fbHjEVnmaqWChR0%3D
```text
ystem.Text.Json.Serialization.Tests.ConstructorTests_Span.MultipleThreads [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/Serialization/TestClasses/TestClasses.Constructor.cs(1085,0): at System.Text.Json.Serialization.Tests.ClassWithConstructor_SimpleAndComplexParameters.Verify()
        /_/src/libraries/System.Text.Json/tests/Serialization/TestClasses/TestClasses.Constructor.cs(1984,0): at System.Text.Json.Serialization.Tests.Parameterized_Class_With_ComplexTuple.Verify()
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(33,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectAsync|13_0(String json, Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(46,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectFlippedAsync|13_2(Type type, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(81,0): at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__RunTestAsync|13_5(Type type)
        /_/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs(86,0): at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreads()
        --- End of stack trace from previous location ---
  Finished:    System.Text.Json.Tests
```

https://dev.azure.com/dnceng/public/_build/results?buildId=953250&view=logs&j=b4344b0d-0f92-5d69-ccaf-e0b24fbf14a2&t=65a58faa-a542-5344-b5c8-897139f242cd

https://github.com/dotnet/runtime/blob/87c3cb7674dcf43fe582df720fd8bf68c82de924/src/libraries/System.Text.Json/tests/Serialization/ConstructorTests/ConstructorTests.Cache.cs#L24-L34

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
> or am I missing something in my change that is uncovering the test failure

Your change has zero impact on the compiled IL.

**Comment by layomia** [comment]
@ahsonkhan thanks for the question - I'll look into this bug.

**Comment by layomia** [comment]
> @ahsonkhan thanks for the question. This failure is not known. I'll look into this bug.

Per https://github.com/dotnet/runtime/issues/46106#issuecomment-745702002, I'll consider this a dup of https://github.com/dotnet/runtime/issues/46100 for now.

> This is very likely duplicate of #46100

**Pull request merged**
