### PR TITLE
Fix warnings in IJW tests

### PR DESCRIPTION
**Pull request by kant2002**

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
Now that we’re using a minimum compiler version with support for `/clr:netcore` there’s more cleanup we can do. Can you set the `COMMON_LANGUAGE_RUNTIME` property to `netcore`? Once you do that, you can rename the mscoree project in ijwhostmock to ijwhost.

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky and @kant2002 I'd also like to see these tests enabled for ARM64. The latest version of VS we are using should have this supported.

https://github.com/dotnet/runtime/blob/227a992b9c71154f3e40b143a825e4563030432c/src/tests/Interop/CMakeLists.txt#L86-L93

**Comment by kant2002** [comment]
@AaronRobinsonMSFT do you want ARM64 only on Win32, or any ARM64?

**Comment by AaronRobinsonMSFT** [comment]
@kant2002 IJW is only supported on the Windows platform. Your changes are what I would have expected to work. We may need to loop in @tgani-msft or @jkoritzinsky to fill us in on why this is failing in the build.

```
2021-03-22T04:58:11.7328513Z D:\workspace\_work\1\s\src\tests\Interop\IJW\IjwNativeCallingManagedDll\IjwNativeCallingManagedDll.cpp : fatal error C1107: could not find assembly 'mscorlib.dll': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\workspace\_work\1\s\artifacts\tests\coreclr\obj\windows.arm64.Checked\Native\Interop\IJW\IjwNativeCallingManagedDll\IjwNativeCallingManagedDll.vcxproj]

2021-03-22T04:58:12.8731334Z D:\workspace\_work\1\s\src\tests\Interop\IJW\IjwNativeDll\IjwNativeDll.cpp : fatal error C1107: could not find assembly 'mscorlib.dll': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [D:\workspace\_work\1\s\artifacts\tests\coreclr\obj\windows.arm64.Checked\Native\Interop\IJW\IjwNativeDll\IjwNativeDll.vcxproj]
```

**Comment by jkoritzinsky** [comment]
I think we need to point the build at the ref-assemblies in the pulled down sdk. Since we're building /clr:netcore without any SDK support, we need to point at the assemblies to reference.

**Comment by kant2002** [comment]
@jkoritzinsky My understanding what should be done following.
I have to ensure that /AI switch is set or LIBPATH env set inside CMake when run `src\tests\build.cmd`
Path which I should set in my understanding is `$env:DOTNET_INSTALL_DIR\sdk\$dotnetSdkVersion\ref`
Problem is that `$dotnetSdkVersion` never exposed as environment variables, and  I do not see a easy way how I can read that value from global.json within cmd file.

Am I understand problem properly, and what I can done to move this forward.

**Comment by jkoritzinsky** [comment]
So we'll want to use the local sdk drop if it was pulled down, so we'll want to use a mechanism similar to the dotnet.cmd file at the root of the repo.

And I think we can hard-code the version or parse it from the root global.json.

**Comment by jkoritzinsky** [comment]
You might also want to pass in the value as a CMake define and have it be calculated from a helper project (like how the optdata location is handled) to ensure that we can accurately calculate the ref pack version instead of having to guess it.

**Comment by jkoritzinsky** [comment]
Also, according to the docs, this CMake target property is only respected on the VS generator (see https://cmake.org/cmake/help/latest/prop_tgt/COMMON_LANGUAGE_RUNTIME.html). As we're moving to Ninja as the default generator, we might want to stick with manually specifying the flag.

**Comment by kant2002** [comment]
So the actual change should be just changing flag to /clr:netcore and still passing proper path to mscorlib.dll
I slightly busy with life, but I will comeback very soon to finish this.

**Comment by kant2002** [comment]
@jkoritzinsky local SDK ref-assemblies does not working since project now complains about `System.Rutime.dll` missing. This file does not exists in `ref` folder of .NET SDK

**Comment by kant2002** [comment]
@jkoritzinsky can you take a look again at questions which I previously post?

**Comment by kant2002** [comment]
@jkoritzinsky what should I do to finish this?

**Comment by jkoritzinsky** [comment]
@kant2002 you need to point the ref path to `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\<ref pack version>\ref\net6.0`. You can get the ref pack version by calling into MSBuild.

You can look at this branch on CoreCLR when I experimented with this: https://github.com/jkoritzinsky/coreclr/tree/ijw-clr-netcore.

In particular, this commit shows the MSBuild property that you want to read and how to write it to a file which you then read into the batch script to send to CMake: https://github.com/jkoritzinsky/coreclr/commit/9809fb917e7d0ab78b7429eb95a53dd72b76daf2

**Comment by jkoritzinsky** [comment]
@kant2002 are you still working on this PR?

**Comment by jkoritzinsky** [comment]
@kant2002 ping?

Unless you're still working on this, I'll close this PR at the end of the day.

**Comment by kant2002** [comment]
@jkoritzinsky I do not work right now. if that would be needed, I can recreate again based on your suggestions. Apologize for delay.

**Pull request closed without merging**
