### PR TITLE
Add dispose() to Bitmap obj

### PR DESCRIPTION
**Pull request by AlexPodrezov**
Add dispose() to Bitmap objects

Found by Linux Verification Center (linuxtesting.org) with SVACE:
1) HANDLE_LEAK.HAS_FINALIZER new Bitmap(1, 1) becomes out of scope and is not disposed
2) HANDLE_LEAK.HAS_FINALIZER Graphics.FromImage(bmp) becomes out of scope and is not disposed
3) HANDLE_LEAK.HAS_FINALIZER new Bitmap(1, 1) becomes out of scope and is not disposed
4) HANDLE_LEAK.HAS_FINALIZER Graphics.FromImage(bmp) becomes out of scope and is not disposed

### CODE REVIEW

**Comment by filipnavara** [comment]
Firstly, the PR is targeted against a wrong branch. Secondly, this code is long gone. The non-Windows implementation of System.Drawing was deprecated in .NET 6. All previous .NET versions are already out of support period.

**Comment by vcsjones** [comment]
There appears to be a significant amount of changes in this pull request unrelated for the description of the pull request. Can you please fix the pull request to only contain the intended changes?

**Comment by huoyaoyuan** [comment]
Strictly speaking, the changed code is still in a supported branch: https://github.com/dotnet/runtime/blob/release/6.0-staging/src/libraries/System.Drawing.Common/src/System/Drawing/Graphics.Unix.cs

However, there's only 3 months before 6.0 EOL. This is not a fatal fix and unlikely to meet the bar for 6.0.

**Comment by akoeplinger** [comment]
Thanks for the PR but I agree with @filipnavara and @huoyaoyuan that this doesn't meet the bar for fixing in 6.0 since the code doesn't even run unless you opt-in with the runtimeconfig switch.

**Pull request closed without merging**
