### PR TITLE
Add GitHub Action for backporting PRs to branches

### PR DESCRIPTION
**Pull request by akoeplinger**
This adds an action that can be triggered with a special comment on a PR: `/backport to <some branch>`.
The action then creates a new PR to the target branch with the commits from the source PR applied.

Example PR: https://github.com/akoeplinger/runtime/pull/10
Corresponding backport: https://github.com/akoeplinger/runtime/pull/11

### CODE REVIEW

**Comment by danmosemsft** [comment]
cc @mmitche @merriemcgaw @marcpopMSFT @Pilchie in case they want something like this iin their own repos. I know some folks prefer to port the other way.

**Review by mmitche — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Comment by Pilchie** [comment]
Tagging @javiercn to discuss with @dotnet/aspdoi and @dotnet/aspnet-build.

**Review by safern — COMMENTED** [review]
Can this action be added into arcade as a common action and then just reference a template from this entrypoint?

**Comment by akoeplinger** [comment]
@safern I did a quick look and it seems possible with https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#referencing-actions-in-your-workflow

We'll probably want to use the `Referencing an action in the same repository where a workflow file uses the action` and then put the action code somewhere in eng/common.

**Comment by akoeplinger** [comment]
> I know some folks prefer to port the other way.

@danmosemsft just to make sure there's no misunderstanding: the action doesn't care which way you port as long as the git patch applies cleanly, i.e. porting from `release/5.0` -> `master` should work fine.

**Comment by steveisok** [comment]
@akoeplinger @danmosemsft had a good suggestion in that we add a template to the backport PR.  Something like:

## Customer Impact
 
## Testing
 
## Risk

Is that workable?

**Comment by merriemcgaw** [comment]
FYI @RussKie , @AdamYoblick

**Comment by RussKie** [comment]
@akoeplinger looks pretty cool! Is the action restricted to those with write access?

**Comment by akoeplinger** [comment]
@RussKie no, but GitHub will only run the action from the `master` branch so someone can't just open a PR to change the action. It means that somebody could trigger a backport PR though, but they can already do that manually by opening a PR themselves.

If there's concern about that it should be easy to add a check for whether a user has write permissions.

**Comment by marcpopMSFT** [comment]
@wli3 for visibility.

**Comment by akoeplinger** [comment]
I ported the action to javascript since that's a requirement for referencing the action from inside the repo.

I currently put it into eng/actions so we can try it out in the runtime repo and once we're happy we can move it to eng/common in arcade and have it flow from there to all the repos.

**Review by steveisok — APPROVED** [review]

**Comment by ericstj** [comment]
Is this creating branches in the `dotnet/runtime` fork or some other user's fork?  Typically we don't like to clutter `dotnet/runtime` with PR branches.

**Comment by akoeplinger** [comment]
@ericstj they are created it in the dotnet/runtime repo since github actions is an "app" so it doesn't have a fork.

The branches are created under the `backport/` slug and since the expectation is that you only do a backport if it's really necessary I assume they will be pretty short-lived.

Besides that, there are already plenty of merged branches that could be cleaned up: https://github.com/dotnet/runtime/branches/all 😄

**Comment by steveisok** [comment]
@ericstj Unless you object, I would like to move this forward.  We can always revisit if the branches get out of hand / a better way comes about.

**Comment by ericstj** [comment]
Ok, let's just be diligent about cleaning these up.

**Comment by am11** [comment]
> Ok, let's just be diligent about cleaning these up.

It is possible to automate this by running a workflow, when a `backport/`-prefixed PR is closed (merged or abandoned) which just does:
`git push -d origin backport/<name>`

**Pull request merged**
