### PR TITLE
Gather 'Tellurium' team issues in team project

### PR DESCRIPTION
**Pull request by StephenMolloy**
Move Issues and PR's for the 'Tellurium' team (area-Serialization, area-System.Runtime.Caching, area-System.ServiceModel.Syndication, area-System.Transactions) to our project board.

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
The project board automation configuration is generated via the https://github.com/dotnet/fabricbot-config repo. Recommend filing a PR there first so that your changes don't get overwritten once we regenerate config.

**Comment by StephenMolloy** [comment]
@eiriktsarpalis, I was trying to follow the direction given by https://github.com/dotnet/runtime/blob/main/docs/infra/automation.md which suggest using the Fabric Bot portal to build new rules. And then what to do after that is unclear... but for external folks with simpler edits, it was suggested to just submit a PR here for this file.

It looked to me like the source of truth was recently moved here and not kept in the fabricbot-config repo... but I'm not the bot expert of course, so I must have been mistaken. Which file am I supposed to edit in the fabricbot-config repo to correspond to this file? Would I still keep this PR as well, or would going through the fabricbot-config repo supersede this PR?

**Comment by ericstj** [comment]
> The project board automation configuration is generated via the https://github.com/dotnet/fabricbot-config repo. Recommend filing a PR there first so that your changes don't get overwritten once we regenerate config.

@jeffhandley mentioned to me that the fabricbot-config should play nicely with manually authored fabricbot rules since it `taskSource` to comment the items it adds.

 @jeffhandley can you have a look at the rules that @StephenMolloy is adding and help decide if they should be treated as manual authoring in the runtime repo or if they should be represented by the scripts in frabricbot-config?

**Review by jeffhandley — APPROVED** [review]
Doing this directly in the runtime repo looks good to me, since the project board doesn't fully match the board structures used by the libraries area pods.

And it is correct that this will not conflict with the fabricbot-config generated tasks.

It does look like some unrelated whitespace changes were included though. If you could revert those chunks, that would help for the next round of changes to those portions of the file.

**Comment by danmoseley** [comment]
@StephenMolloy can you resolve the conflict and merge this PR? (going through old PR's in area-meta)

**Comment by jeffhandley** [comment]
@StephenMolloy I rebased and resolved the conflicts before merging. This automation is now active.

**Pull request merged**
