### PR TITLE
Proposed set of norms and best practices for issue and pull request management

### PR DESCRIPTION
**Pull request by jeffschwMSFT**
The dotnet/runtime consolidated repository is a consolidation of the code, infrastructure, and community/team norms and practices.  This document represents the collective decision making of a working group of engineers from each of the repositories that are being consolidated.

### CODE REVIEW

**Review by stephentoub — COMMENTED** [review]
Thanks for putting this together.

**Comment by BruceForstall** [comment]
@jeffschwMSFT When an issue is opened, a bot adds the "untriaged" label. If an issue is closed with this label still attached, can the bot remote the label? Doesn't seem useful to keep the label in this case until someone manually triages it (and it seems annoying to have to query for non-closed issues).

**Comment by jeffschwMSFT** [comment]
> When an issue is opened, a bot adds the "untriaged" label. If an issue is closed with this label still attached, can the bot remote the label? Doesn't seem useful to keep the label in this case until someone manually triages it (and it seems annoying to have to query for non-closed issues).

@maryamariyan?

**Comment by maryamariyan** [comment]
@jeffschwMSFT @BruceForstall the bot could be updated to remove untriaged label when an issue gets closed.

**Pull request merged**
