### PR TITLE
Add reporting of JIT assertions for SuperPMI replay

### PR DESCRIPTION
**Pull request by BruceForstall**
If there are compilation failures during a replay that are from JIT assertions, collect all the assertion instances, and report each unique assertion together with its set of instances sorted by increasing IL size. The idea is that it is often preferable to repro an assertion using the smallest function first.

Assertions are first reported for each MCH file individually, as the replay happens (so they can be acted upon before the replay completes, especially if the replay is interrupted). Then, summarize all the assertions combined across all MCH files at the end.

E.g., a sample per-MCH file output:
```
[14:10:35] ============================== Assertions:
[14:10:35] !"Jump into middle of try region" (C:\gh\runtime4\src\coreclr\jit\fgdiagnostic.cpp:2810)
[14:10:35]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries.pmi.windows.x86.checked.mch # 288644 : IL size 245
[14:10:35] this->Next()->KindIs(BBJ_CALLFINALLYRET) (C:\gh\runtime4\src\coreclr\jit\block.cpp:1623)
[14:10:35]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries.pmi.windows.x86.checked.mch # 51563 : IL size 136
[14:10:35]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries.pmi.windows.x86.checked.mch # 150548 : IL size 149
```

And a sample all-MCH file summary (looks the same, but contains data from multiple MCH files) is:
```
[14:11:44] ============================== Assertions:
[14:11:44] !"Jump into middle of try region" (C:\gh\runtime4\src\coreclr\jit\fgdiagnostic.cpp:2810)
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\coreclr_tests.run.windows.x86.checked.mch # 242532 : IL size 35
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\coreclr_tests.run.windows.x86.checked.mch # 494526 : IL size 35
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries_tests_no_tiered_compilation.run.windows.x86.Release.mch # 224364 : IL size 169
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries_tests_no_tiered_compilation.run.windows.x86.Release.mch # 227436 : IL size 169
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries.crossgen2.windows.x86.checked.mch # 190170 : IL size 245
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries.pmi.windows.x86.checked.mch # 288644 : IL size 245
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries_tests.run.windows.x86.Release.mch # 496033 : IL size 245
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries_tests_no_tiered_compilation.run.windows.x86.Release.mch # 237928 : IL size 245
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\coreclr_tests.run.windows.x86.checked.mch # 237897 : IL size 251
[14:11:44] this->Prev()->KindIs(BBJ_CALLFINALLY) (C:\gh\runtime4\src\coreclr\jit\block.cpp:1651)
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\coreclr_tests.run.windows.x86.checked.mch # 487629 : IL size 103
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\coreclr_tests.run.windows.x86.checked.mch # 237816 : IL size 103
[14:11:44] this->Next()->KindIs(BBJ_CALLFINALLYRET) (C:\gh\runtime4\src\coreclr\jit\block.cpp:1623)
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries.crossgen2.windows.x86.checked.mch # 49093 : IL size 136
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries.pmi.windows.x86.checked.mch # 51563 : IL size 136
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\realworld.run.windows.x86.checked.mch # 19757 : IL size 136
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries.pmi.windows.x86.checked.mch # 150548 : IL size 149
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\coreclr_tests.run.windows.x86.checked.mch # 193790 : IL size 205
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries.crossgen2.windows.x86.checked.mch # 16877 : IL size 205
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\libraries_tests.run.windows.x86.Release.mch # 296583 : IL size 205
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\realworld.run.windows.x86.checked.mch # 19393 : IL size 205
[14:11:44]   c:\spmi\mch\e15e62ce-d9c6-418a-a5a7-26ad17fcf4bf.windows.x86\realworld.run.windows.x86.checked.mch # 35122 : IL size 258
```

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib PTAL

**Comment by AndyAyersMS** [comment]
This looks super useful, especially for those of us who break things all the time.

**Comment by kunalspathak** [comment]
can we have them available in "Extensions" markdown page as well?

**Review by AndyAyersMS — APPROVED** [review]

**Comment by BruceForstall** [comment]
> can we have them available in "Extensions" markdown page as well?

I'm not opposed to that, but it would be separate work.

**Pull request merged**
