### PR TITLE
Fixed the problem that Environment Variable configuration provider doesn't work if the prefix has 2 underscores

### PR DESCRIPTION
**Pull request by MakerDev**
Proposal for fixing dotnet/runtime#40911.

The original problem was that loading a key-value pair _["TEST__TEST1__TEST2" : "42"]_  with _prefix "TEST__"results in null because after Normalizing the Key "TEST_TEST1_TEST2" , it becomes "TEST:TEST1:TEST2" so the key no longer starts with intended prefix "TEST__".

As this problem occured because NormalizeKey is executed without any consideration of local variable _prefix which is provided via constructor. I changed AzureEnvToAppEnv to check if the prefix ends with "__" before Normalizing.

Now loading _["TEST__TEST1__TEST2" : "42"]_  with _prefix "TEST__"_ results in _env["TEST1:TEST2] == "42"_.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=41092) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=41092) before we can accept your contribution.<br/><br/>:x: MakerDev [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=41092)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=41092) it.</sub>

**Comment by Emzi0767** [comment]
This PR doesn't fully resolve this issue as far as I can tell. Try a prefix of `TEST__TEST__`.

**Comment by Emzi0767** [comment]
As an addendum: the fix should reverse the operation order, i.e. prefix stripping should occur before normalisation.

**Comment by MakerDev** [comment]
> As an addendum: the fix should reverse the operation order, i.e. prefix stripping should occur before normalisation.

Thank you for reviewing! I'll try to improve this and fully resolve the issue.

**Comment by maryamariyan** [comment]
closing in favor of PR https://github.com/dotnet/runtime/pull/42932

**Pull request closed without merging**
