### PR TITLE
Simplify CEEInfo::getTypeForPrimitiveValueClass

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
Simplified per https://github.com/dotnet/runtime/pull/71633#discussion_r913777181

**Comment by jkotas** [comment]
cc @MichalPetryka

**Review by jakobbotsch — APPROVED** [review]
Sorry about that, I missed that there was still unaddressed feedback in that PR.

**Review by MichalPetryka — APPROVED** [review]

**Comment by jkotas** [comment]
Test failure is https://github.com/dotnet/runtime/issues/71684

**Pull request merged**
