### PR TITLE
Add tizen-arm64 RIDs

### PR DESCRIPTION
**Pull request by WonyoungChoi**
Since tizen 6.0.0, arm64 will be supported.

### CODE REVIEW

**Review by swift-kim — APPROVED** [review]

**Comment by safern** [comment]
cc: @ericstj -- since tizen5.5.0 doesn't define arm64 RID, is the best to just suppress the errors?

**Comment by ericstj** [comment]
I believe you can fix the error by only listing the version in a single runtimegroup, as was done with rhel.

So instead of 
```xml
    <RuntimeGroup Include="tizen">
      <Parent>linux</Parent>
      <Architectures>x86;armel</Architectures>
      <Versions>4.0.0;5.0.0;5.5.0;6.0.0</Versions>
    </RuntimeGroup>
    <RuntimeGroup Include="tizen">
      <Parent>linux</Parent>
      <Architectures>arm64</Architectures>
      <Versions>6.0.0</Versions>
    </RuntimeGroup>
```

Do 
```xml
    <RuntimeGroup Include="tizen">
      <Parent>linux</Parent>
      <Architectures>x86;armel</Architectures>
      <Versions>4.0.0;5.0.0;5.5.0</Versions>
    </RuntimeGroup>
    <RuntimeGroup Include="tizen">
      <Parent>linux</Parent>
      <Architectures>x86;armel;arm64</Architectures>
      <Versions>6.0.0</Versions>
    </RuntimeGroup>
```

**Comment by WonyoungChoi** [comment]
@ericstj If version 6.0.0 is separated, the version will not be able to include the lower versions. So I just added `arm64` to all tizen versions. I don't want to limit some possibilities.

**Comment by ericstj** [comment]
I see.  It looks like this is the same way we handled it with `win`.  This is probably the best way for now.  If you want to create a better way to deal with this you could  make a change here https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateRuntimeGraph.cs.

**Comment by WonyoungChoi** [comment]
@ericstj  Thanks for the advice.  As of now, I want to open the possibility of `arm64` support in lower `tizen` versions.

**Review by ericstj — APPROVED** [review]

**Pull request merged**
