### PR TITLE
[LinuxBionic] Disable RemoteExecutor during test runs

### LINKED ISSUE #76140: 3 System.Diagnostics tests failing - System.FormatException : The input is not a valid Base-64
Affected tests:
- **ProcessStartInfoEnvironmentDoesNotThrowForCaseSensitiveDuplicates** - `System.Diagnostics.Tests.ProcessStartInfoTests.ProcessStartInfoEnvironmentDoesNotThrowForCaseSensitiveDuplicates`
- **ProcessStartInfoEnvironmentVariablesDoesNotThrowForCaseSensitiveDuplicates** - `System.Diagnostics.Tests.ProcessStartInfoTests.ProcessStartInfoEnvironmentVariablesDoesNotThrowForCaseSensitiveDuplicates`
- **EnvironmentGetEnvironmentVariablesIsCaseSensitive** - `System.Diagnostics.Tests.ProcessStartInfoTests.EnvironmentGetEnvironmentVariablesIsCaseSensitive`

Regression on 9/21 - first occurrence in PR [25181](https://runfo.azurewebsites.net/view/build/?number=25181)

Runfo queries:
- ProcessStartInfoEnvironmentDoesNotThrowForCaseSensitiveDuplicates - [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.diagnostics.tests.processstartinfotests.processstartinfoenvironmentdoesnotthrowforcasesensitiveduplicates%22)
- ProcessStartInfoEnvironmentVariablesDoesNotThrowForCaseSensitiveDuplicates - [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A~30+definition%3Aruntime-extra-platforms+name%3A%22system.diagnostics.tests.processstartinfotests.processstartinfoenvironmentvariablesdoesnotthrowforcasesensitiveduplicates%22)
- EnvironmentGetEnvironmentVariablesIsCaseSensitive - [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.diagnostics.tests.processstartinfotests.environmentgetenvironmentvariablesiscasesensitive%22)

As of 9/24 there are 10 hits on the same builds in each test:

Day | Run | Logs
-- | -- | --
9/23 | Rolling run [28538](https://runfo.azurewebsites.net/view/build/?number=28538) (7.0) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-a988ea84eb46494894/System.Diagnostics.Process.Tests/1/console.07adf68a.log?%3Fhelixlogtype%3Dresult)
9/23 | Rolling run [28539](https://runfo.azurewebsites.net/view/build/?number=28539) (release/5 - ???) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-5-c689650c01414a9bad/System.Diagnostics.Process.Tests/1/console.0f7c6a50.log?%3Fhelixlogtype%3Dresult)
9/23 | PR [28221](https://runfo.azurewebsites.net/view/build/?number=28221) (7.0) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76052-merge-6772b9cdcd464bd8ba/System.Diagnostics.Process.Tests/1/console.903ca50b.log?%3Fhelixlogtype%3Dresult)
9/23 | PR [27908](https://runfo.azurewebsites.net/view/build/?number=27908) (main) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75612-merge-e93451d286614532a8/System.Diagnostics.Process.Tests/1/console.a643c4fb.log?%3Fhelixlogtype%3Dresult)
9/22 | Rolling run [27273](https://runfo.azurewebsites.net/view/build/?number=27273) (release/5 - ???) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-5-9cd780087f674bf798/System.Diagnostics.Process.Tests/1/console.06f15d4f.log?%3Fhelixlogtype%3Dresult)
9/22 | Rolling run [27269](https://runfo.azurewebsites.net/view/build/?number=27269) (7.0) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-f1537a3ca14e4a3883/System.Diagnostics.Process.Tests/1/console.5d1fa961.log?%3Fhelixlogtype%3Dresult)
9/22 | Rolling run [26575](https://runfo.azurewebsites.net/view/build/?number=26575) (7.0-rc2) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-rc2-d34aa0dbad8c45ff8f/System.Diagnostics.Process.Tests/1/console.f5ea6025.log?%3Fhelixlogtype%3Dresult)
9/22 | PR [25945](https://runfo.azurewebsites.net/view/build/?number=25945) (main) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76000-merge-cbf972e573f349e584/System.Diagnostics.Process.Tests/1/console.7f5caf76.log?%3Fhelixlogtype%3Dresult)
9/21 | Rolling run [25911](https://runfo.azurewebsites.net/view/build/?number=25911) (7.0) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-07f685fcf37a43c5bc/System.Diagnostics.Process.Tests/1/console.1a32ff1a.log?%3Fhelixlogtype%3Dresult)
9/21 | PR [25181](https://runfo.azurewebsites.net/view/build/?number=25181) (main) | [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75730-merge-9f8608e565d3469aba/System.Diagnostics.Process.Tests/1/console.cc1da050.log?%3Fhelixlogtype%3Dresult)

### PR DESCRIPTION
**Pull request by steveisok**
Fixes https://github.com/dotnet/runtime/issues/76140

### CODE REVIEW

**Comment by jkotas** [comment]
Is there a reason why Linux Bionic does not support remote executor? I would expect that remote executor should work on Linux Bionic just fine. Linux Bionic is basically plain vanilla Linux. It does not come with the same limitations as Android apps.

**Comment by jkotas** [comment]
Also, we have a ton of RemoteExecutor tests and they seem to be all running on Linux Bionic today. Why are we seeing the failure on just 3 tests? It suggests that the problem is specific to the 3 tests that are failing.

**Comment by akoeplinger** [comment]
I agree with Jan, if possible we should just disable the failing tests

**Comment by directhex** [comment]
We’re restricted to using Google Android images in CI, because our internal partner hasn’t provided images of anything closer to their final production environment to run on. So technically we don’t have issues doing things on Bionic in general, in practice there are certain constraints in our CI environment which are beyond our team’s ability to work around (e.g. Google’s SELinux configuration blocks creation of domain sockets in /data/local/tmp, which is the only directory we can write our tests to without trying to invoke the whole APK infrastructure, whose functionality on the target devices isn’t clear)

**Pull request closed without merging**
