### PR TITLE
Delete some dead code`

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
Leftover from https://github.com/dotnet/runtime/pull/89548

**Comment by VSadov** [comment]
As I remember `fClassMustBeRestored` was removed in the big change (and that part was not causing any issues), but later was undone together with all JIT changes.

**Comment by jkotas** [comment]
Right

**Review by VSadov — APPROVED** [review]
LGTM!

**Pull request merged**
