### PR TITLE
Fix running tests with process isolation under naot

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
We don't currently run any RequiresProcessIsolation tests under native AOT because we hit the "not an applicable OS" early out here:

https://github.com/dotnet/runtime/blob/765ca4e9f2dddca2005ffdb45863b7980247a886/src/tests/Common/CoreCLRTestLibrary/OutOfProcessTest.cs#L75-L79

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
This fixes things locally. It doesn't fix them in Helix. The reason is that we don't pack the necessary tests into the helix workitem payload (it only has the EXE that is supposed to look for .sh/.cmd files to execute, but there's no .sh/.cmd and the relevant EXEs). This will take a while to untangle.

**Comment by agocke** [comment]
@jkoritzinsky  for review

**Review by jkoritzinsky — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
/ba-g mac leg timed out but it's not relevant to what I'm doing here

**Pull request merged**
