### PR TITLE
Fix for the elusive suspension hang on Win7 WOW64

### PR DESCRIPTION
**Pull request by VSadov**
x86 Win7 would not consider `CONTEXT_EXCEPTION_REQUEST` a valid flag when passed to `InitializeContext` and few other APIs that validate against `X86_CONTEXT_VALID`

`CONTEXT_EXCEPTION_REQUEST` is really just a directive to `GetThreadContext` to report back if the thread was stopped in the kernel or something similar. It could be ignored by other APIs like `InitializeContext`, but somehow Win7+x86 makes it a failure.
`CONTEXT_EXCEPTION_REQUEST` is included in `X86_CONTEXT_VALID` on later OS-es and in similar mask used on 64bit. The issue is strictly Win7+x86 specific.

Historically, we keep `CONTEXT_EXCEPTION_REQUEST` flag set on redirection contexts from the very beginning and keep it set throughout various uses. 

Once we pass that to `InitializeContext` on Win7+x86, it fails and as a result we cannot get a context buffer to use in thread redirection. We tolerate the failure assuming it is caused by low memory or some other transient condition. The API reserves the right to fail for "other" reasons per documentation.
Once that fails, a lot of things would still work, since there are other mechanisms through which we can suspend threads, but we can't use redirection.

In the repro case a test runs producer-consumer benchmark where producer thread is already suspended and consumer is stuck while running a tight `TryPop` loop. The loop is fully interruptible and we could easily redirect and suspend the thread, but we keep failing and retrying forever, since we are unable to allocate storage for the thread context.

Anyways, we should only set `CONTEXT_EXCEPTION_REQUEST` when making a call to `GetThreadContext`. This way we would not need to worry how this flag could be interpreted by other APIs.

Fixes:https://github.com/dotnet/runtime/issues/67559

### CODE REVIEW

**Review by adamsitnik — COMMENTED** [review]
@VSadov have you considered using the [benchmark code](https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Collections/Concurrent/AddRemoveFromDifferentThreads.cs) and adding it as a unit test? It's not the first time this particular benchmark has identified a runtime bug.

**Comment by VSadov** [comment]
@adamsitnik I am thinking about making a test for this. Making a test that is both quick and effective could be a challenge though. Suspensions are relatively rare events. We certainly have producer-consumer unit tests already. They just not as long running as the per tests, thus do not catch this kind of issues. 

Perhaps artificially forcing lots of suspensions in a few existing tests (or copies) would be a way to add coverage.

**Comment by VSadov** [comment]
@adamsitnik - BTW, suspension latency can be measured. There are calls that suspend EE indirectly without causing GC. For example `GC.GetTotalAllocatedBytes` - it basically suspends EE, reads a few fields and resumes. The cost of this API is completely dominated by how long it takes to suspend. 
Measuring this call is the same as measuring suspension latency. With a caveat that the context matters - if nothing else happens in the app, suspending will be super fast, but if there are many active threads running code, there will be more work.

See some examples in https://github.com/dotnet/runtime/pull/34666#issuecomment-707211772
If you run the sample you would see that we improved in 7.0 quite a bit. (at least on my machine :-)

I wonder, since we care about this, maybe we should add couple perf tests. This could be somewhat noisy metric, but the trend over time and unexpected gaps should be measurable and actionable.

**Review by jkotas — APPROVED** [review]

**Comment by VSadov** [comment]
Thanks!!!

**Pull request merged**
