### PR TITLE
[release/6.0] Drop 6.0.200 workload manifests

### PR DESCRIPTION
**Pull request by lewing**
goes along with https://github.com/dotnet/emsdk/pull/195

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by carlossanlop** [comment]
@lewing this is still a draft. Please mark it as `servicing consider` when ready to review.

**Comment by carlossanlop** [comment]
Actually... this is infra, so maybe the label is not needed. But ping me when it's not a draft anymore.

**Review by joeloff — APPROVED** [review]

**Comment by carlossanlop** [comment]
Ah, if I'm understanding the change correctly, this is blocked by https://github.com/dotnet/emsdk/pull/195

**Comment by lewing** [comment]
not strictly blocked but they go together

**Comment by lewing** [comment]
this can be merged now (and should be as emsdk flows)

**Comment by carlossanlop** [comment]
Thanks for the ping. I see https://github.com/dotnet/emsdk/pull/195 has been merged. Merging this one now.

**Pull request merged**
