### PR TITLE
TypeLoadException thrown from MetadataLoadContext should expose TypeName

### LINKED ISSUE #86923: TypeLoadException thrown from MetadataLoadContext should expose TypeName
### Description

When an instance of `TypeLoadException` is thrown from the custom reflection items formed by `MetadataLoadContext`, its `TypeName` property is an empty string (`""`). It would be expected for this property to work in a similar way as when the exception is thrown from normal assembly loading, as is shown in the [examples](https://learn.microsoft.com/en-us/dotnet/api/system.typeloadexception.typename?view=net-7.0#examples) for this property. Such a thing would be useful in situations where only the type name is required (for example when loading attributes on a member and comparing them by name) and so it does not matter that the full `Type` instance could not be provided, if the name was passed through `TypeLoadException.TypeName`.

### Reproduction Steps

```cs
var context = new MetadataLoadContext(new PathAssemblyResolver(new[] { typeof(object).Assembly.Location }), typeof(object).Assembly.GetName().FullName);
try{
    context.CoreAssembly.GetType("NonExistentType", true);
}catch(TypeLoadException tle)
{
    Console.WriteLine(tle.TypeName);
}
```

### Expected behavior

`NonExistentType` should be written, akin to the example for the property.

### Actual behavior

The code writes an empty line.

### Regression?

Seems to have been this way as early as 4.6.

### Known Workarounds

The name could be parsed from the exception message, but that is not optimal.

### Configuration

Version 8.0.0-preview.4.23259.5 of `System.Reflection.MetadataLoadContext`; .NET 7.0.

### Other information

The issue is probably somewhere [here](https://github.com/dotnet/runtime/blob/f2f3b092cbeb46eb5c50eebc1b29a7c7107c3482/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Modules/Ecma/EcmaModule.GetTypeCore.cs#L62), where only the message is given to `TypeLoadException`.

### PR DESCRIPTION
**Pull request by pedrobsaila**
Fixes #86923

### CODE REVIEW

**Comment by steveharter** [comment]
Thanks for the PR - can you update the corresponding issue to add the new public method and mark it "API - ready for review".

Also this late in the release the contribution bar has increased; this will likely have to go into v9.

**Comment by pedrobsaila** [comment]
I added the new constructor for internal use only, check [System.Private.CoreLib.ExtraApis.txt](https://github.com/dotnet/runtime/pull/90268/files#diff-51cd61f5098ea4d2a474f3cf3fb46a51ab5faefb35a576d03a1c06e3f92ed9b9) It should not be visible to the users

**Comment by steveharter** [comment]
> I added the new constructor for internal use only

I see.

I believe you also need to update https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/ref/System.Private.CoreLib.ExtraApis.cs and undo the change to `System.Runtime.cs`. Also check if you still need the suppression that was added.

**Comment by pedrobsaila** [comment]
> I believe you also need to update https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/ref/System.Private.CoreLib.ExtraApis.cs and undo the change to System.Runtime.cs. Also check if you still need the suppression that was added.

The lib System.Reflection.MetadataLoadContext depends on System.Runtime not System.Private.Corlib. It fails to see the new constructor if I move it around. For the suppression, I need it because I get build errors without it

**Comment by steveharter** [comment]
I believe the "extra apis" can only be consumed from code that ships in System.Private.CoreLib - it just creates public types or members so code compiles fine, but which are then not exposed in the various library's .ref files or System.Runtime.

So for this to work with MetadataLoadContext, which is not in System.Private.CoreLib, we need the new constructor to a standard public member which means API review.

@ViktorHofer are you familiar with this?

**Comment by steveharter** [comment]
Closing this PR; it looks like we need to add a new API for v9 (we can re-open if not the case).

**Comment by steveharter** [comment]
Thanks @pedrobsaila

**Pull request closed without merging**
