### PR TITLE
Add RequiresProcessIsolation in testcase Runtime_100437

### LINKED ISSUE #100576: TestNonCollectibleType times out under GCStress
The test added in #100444 times out under GCStress on linux-x64 and osx-arm64. Example pipeline run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=627621&view=results

### PR DESCRIPTION
**Pull request by VSadov**
Test-only change. 

Fixes: https://github.com/dotnet/runtime/issues/100576

### CODE REVIEW

**Comment by VSadov** [comment]
CC: @jakobbotsch @markples

**Review by markples — APPROVED** [review]

**Comment by VSadov** [comment]
Wow!!. a green stress run!!!

**Comment by jakobbotsch** [comment]
Why is this workaround needed? It's not clear to me why merged tests would not allow use of `WairForPendingFinalizers`. Is there a dead lock in gcstress related to finalizers?

**Comment by markples** [comment]
See https://github.com/dotnet/runtime/issues/97334#issuecomment-1945079354 and discussion in #100576

**Comment by jakobbotsch** [comment]
Thanks, looks like my notifications would have eventually gotten me there :-)

**Pull request merged**
