### PR TITLE
fix resolveVirtualMethodHelper

### LINKED ISSUE #59668: JIT: libraries PGO runtime assert
Windows x86; may also happen for other os/arch combos.
```
COMPlus_TC_QuickJitForLoops=1
COMPlus_TieredCompilation=1
COMPlus_TieredPGO=1

dotnet.exe exec --runtimeconfig System.Text.RegularExpressions.Tests.runtimeconfig.json --depsfile System.Text.RegularExpressions.Tests.deps.json xunit.console.dll System.Text.RegularExpressions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Text.RegularExpressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.RegularExpressions.Tests (found 199 of 221 test cases)
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 1864 [0x00000748], Thread: 1976 [0x07b8]): Precondition failure: FAILED: IsArray() || ImplementsEquivalentInterface(ownerType.GetMethodTable()) || ownerType.GetMethodTable()->HasVariance()

CORECLR! GetCLRRuntimeHost + 0x49D0DD (0x725ffcad)
CORECLR! GetCLRRuntimeHost + 0xD18BC (0x7223448c)
CORECLR! GetCLRRuntimeHost + 0xA030C (0x72202edc)
CORECLR! GetCLRRuntimeHost + 0x9FF73 (0x72202b43)
CLRJIT! jitStartup + 0x51BC3 (0x713bfde3)
CLRJIT! jitStartup + 0x5D8E0 (0x713cbb00)
CLRJIT! jitStartup + 0x582BD (0x713c64dd)
CLRJIT! jitStartup + 0x4E189 (0x713bc3a9)
CLRJIT! jitStartup + 0x53D39 (0x713c1f59)
CLRJIT! jitStartup + 0x53683 (0x713c18a3)
    File: D:\workspace\_work\1\s\src\coreclr\vm\methodtable.cpp Line: 2053
```

### PR DESCRIPTION
**Pull request by EgorBo**
fixes https://github.com/dotnet/runtime/issues/59668 but I'm not sure in this fix

I was not able to extract a simple repro from the original issue.

### CODE REVIEW

**Comment by EgorBo** [comment]
PTAL @AndyAyersMS and someone from runtime side please (@davidwrighton).
The test doesn't need PGO to reproduce the issue.

**Comment by EgorBo** [comment]
azp run runtime-coreclr outerloop

**Comment by AndyAyersMS** [comment]
Thanks for extracting a simple repro.

The fix looks reasonable to me, but this aspect of devirt has always been tricky to reason about.

What do diffs look like? Do you need new SPMI collections? (eg asp.net?)

**Comment by EgorBo** [comment]
> Thanks for extracting a simple repro.
> 
> The fix looks reasonable to me, but this aspect of devirt has always been tricky to reason about.
> 
> What do diffs look like? Do you need new SPMI collections? (eg asp.net?)

I tried jit-diff (pmi) via two runs (in order to pick correct coreclr.dll) and superpmi - both reported empty diffs.

**Comment by davidwrighton** [comment]
@EgorBo I'm going to need some time tomorrow to look into this. Your change seems reasonable, but it feels like it may open up holes where we fail to devirtualize in the presence of a canonical context, but I need to dig into if that's a thing that happens anymore.

**Review by davidwrighton — APPROVED** [review]
This looks good, but I do not think it should be ported to the 6.0 branch. While the assert is annoying, it appears to be benign, and every change we take to this part of the codebase has historically had a high chance of regression.

**Pull request merged**
