### PR TITLE
Adds back Enum constraint to Enum.GetNames<TEnum>()

### PR DESCRIPTION
**Pull request by terrajobst**
This partially addresses #100843

### CODE REVIEW

**Comment by stephentoub** [comment]
When was this removed? Was that recently / accidentally as part of Jan's reformat of the ref?

**Review by stephentoub — APPROVED** [review]

**Comment by ericstj** [comment]
Yeah.  https://github.com/dotnet/runtime/issues/100843.
Also https://github.com/dotnet/sdk/issues/39659

**Comment by stephentoub** [comment]
I assume we double checked to ensure nothing else was accidentally changed?

**Comment by ericstj** [comment]
I did another pass of Jan's PR.  I couldn't find any more diffs.  I did one full pass of all the code, then another pass looking at all generic constraints.

In general we can trust APICompat to keep us safe - but it has a gap here with generic constraints.

**Comment by stephentoub** [comment]
Thanks

**Comment by terrajobst** [comment]
What's the verdict on the test failures? They seem unrelated (timeout on the WASM test side).

**Review by jkotas — APPROVED** [review]
Thank you!

**Pull request merged**
