### PR TITLE
[mono][tests] Disable System.Reflection and System.Threading.Tasks.Parallel tests 

### PR DESCRIPTION
**Pull request by kotlarmilos**
## Description

This PR disables failing library tests on Apple mobile platforms. Additionally, it increases the timeout to run the `System.Security.Cryptography` tests. More details available at https://github.com/dotnet/runtime/issues/93852.

### CODE REVIEW

**Comment by kotlarmilos** [comment]
@vargaz When conducting local tests, it has been noticed that the `MONO_TYPE_FNPTR` cases are missing when utilizing the mini backend for arm64. Please take a look and suggest if additional changes are needed.

**Comment by steveisok** [comment]
I'll be. tvOS is all green!

**Review by steveisok — APPROVED** [review]

**Pull request merged**
