### PR TITLE
Try re-enabling failing test

### LINKED ISSUE #30003: TestCheckChildProcessUserAndGroupIdsElevated failed in CI
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38817~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190624.2/workItem/System.Diagnostics.Process.Tests/wilogs
```
    System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIdsElevated(useRootGroups: True) [FAIL]
      Assert.NotNull() Failure
      Stack Trace:
        /_/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs(640,0): at System.Diagnostics.Tests.ProcessTests.GetCurrentRealUserName()
        /_/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs(615,0): at System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIdsElevated(Boolean useRootGroups)

    System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIdsElevated(useRootGroups: False) [FAIL]
        /_/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs(640,0): at System.Diagnostics.Tests.ProcessTests.GetCurrentRealUserName()
        /_/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs(615,0): at System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIdsElevated(Boolean useRootGroups)
```
cc: @tmds

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Fixes #30003.

### CODE REVIEW

**Comment by stephentoub** [comment]
If CI passes, LGTM.  If it doesn't, it doesn't :wink:

**Comment by eiriktsarpalis** [comment]
Tests seem to be passing, although I could search for the particular test or any others in the [pipeline tests view](https://dev.azure.com/dnceng/public/_build/results?buildId=700188&view=ms.vss-test-web.build-test-results-tab).

I think we could merge this, the question is whether this particular failure is nondeterministic/triggered on specific machines?

**Comment by eiriktsarpalis** [comment]
Test is green in all environments. I think we can merge this.

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @eiriktsarpalis 

The outer loop CI legs are red due to failures in `System.Net.Http.Functional.Tests`, not this particular test.

**Pull request merged**
