### PR TITLE
[mono] Fix r8->i conversion on amd64.

### LINKED ISSUE #64386: Mono incorrectly handles conversion of negative doubles to nint
https://github.com/dotnet/runtime/pull/64234/ appears to surface a bug in Mono where it incorrectly handles `double->nint` but not `float->nint` conversions.

The test is in the form:
```csharp
[Theory]
[InlineData(-4567.0f)]
public void NFloatToIntPtr(float value)
{
    nint result = (nint)new NFloat(value);
    Assert.Equal((nint)value, result);
}
```

Where NFloat is roughly defined as:
```csharp
public readonly struct NFloat
{
    private readonly double _value;

    public NFloat(double value)
    {
        _value = value;
    }

    public static explicit operator nint(NFloat value) => (nint)(value._value);
}
```

This resulted in https://dev.azure.com/dnceng/public/_build/results?buildId=1574581&view=ms.vss-test-web.build-test-results-tab&runId=44208602&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=164309

Where the exact failure is:
```
    System.Runtime.InteropServices.Tests.NFloatTests.NFloatToIntPtr(value: -4567) [FAIL]
      Assert.Equal() Failure
      Expected: -4567
      Actual:   4294962729
      Stack Trace:
        /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs(483,0): at System.Runtime.InteropServices.Tests.NFloatTests.NFloatToIntPtr(Single value)
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs(386,0): at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
    System.Runtime.InteropServices.Tests.NFloatTests.NFloatToIntPtr(value: -4567.89111) [FAIL]
      Assert.Equal() Failure
      Expected: -4567
      Actual:   4294962729
      Stack Trace:
        /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs(483,0): at System.Runtime.InteropServices.Tests.NFloatTests.NFloatToIntPtr(Single value)
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs(386,0): at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
```

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/dotnet/runtime/issues/64386.

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
@vargaz  same problem on arm64 I think

https://github.com/dotnet/runtime/blob/c7adf5598f27e59644030ddae4e382cbda74e41e/src/mono/mono/mini/mini-arm64.c#L4228-L4236

Can we add a test?

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
@vargaz should we backport this to 6.0?

**Comment by vargaz** [comment]
We should

**Comment by am11** [comment]
@vargaz, is this failure related https://helix.dot.net/api/2019-06-17/jobs/a5963b9d-9f2a-495e-8451-7569cebe9bd4/workitems/System.Runtime.InteropServices.Tests/console:
```
    System.Runtime.InteropServices.Tests.NFloatTests.NFloatToIntPtr(value: 0) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   4393751543808
      Stack Trace:
        /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs(483,0): at System.Runtime.InteropServices.Tests.NFloatTests.NFloatToIntPtr(Single value)
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs(386,0): at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
    System.Runtime.InteropServices.Tests.NFloatTests.NFloatToIntPtr(value: 4567) [FAIL]
```

**Pull request merged**
