### PR TITLE
Add info to templates about area-, os-, arch- labels

### PR DESCRIPTION
**Pull request by danmoseley**
This may help reduce the number of guesses that the bot has to make.

### CODE REVIEW

**Comment by stephentoub** [comment]
Adding labels requires more permissions today than most folks have.

**Comment by danmosemsft** [comment]
My bad, I thought it could be done when opening.

**Comment by danmosemsft** [comment]
Actually, I see someone without commit permissions opening an issue with a label: see https://github.com/dotnet/runtime/issues/39560

@hughbe when you open an issue in this repo (or maybe winforms, say), are you able to add a label, did you notice ?

**Comment by hughbe** [comment]
I don't think i can actually:

Contrast dotnet/winforms
image

With hughbe/excel-mapper
image

Notice that the little gear next to the label list is missing

**Comment by danmosemsft** [comment]
Right, you can't after the issue is open, without commit rights. But I'm wondering whther you can in the new issue form, before the issue is actually opened.

**Comment by KalleOlaviNiemitalo** [comment]
> Actually, I see someone without commit permissions opening an issue with a label: see #39560

FWIW, I am not able to select labels to add when opening an issue in this repo.

I think GitHub copied the "api-suggestion" label to <https://github.com/dotnet/runtime/issues/39560> from the issue template: <https://github.com/dotnet/runtime/blob/f4e9146d1d2ba7cf48ab59022658619fc9dbaec3/.github/ISSUE_TEMPLATE/02_api_proposal.md#L5>.

**Comment by danmosemsft** [comment]
@KalleOlaviNiemitalo ah of course - that makes sense. Thanks.

**Pull request closed without merging**
