### PR TITLE
update Helix arm64 images

### PR DESCRIPTION
**Pull request by wfurt**
allows to run Quic tests on Linux ARM64 (Debian/Ubuntu)

### CODE REVIEW

**Comment by wfurt** [comment]
Tests passing on ARM64

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73963-merge-d4ad1b5c13c14fcc8e/System.Net.Quic.Functional.Tests/1/console.2d920604.log?helixlogtype=result

```
Console log: 'System.Net.Quic.Functional.Tests' from job d4ad1b5c-13c1-4fcc-8ee1-c46f97387a4c (ubuntu.1804.armarch.open) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-arm64v8-20220820185253-06f234f on ddvsotx2l195


/root/helix/work/correlation/dotnet exec --runtimeconfig System.Net.Quic.Functional.Tests.runtimeconfig.json --depsfile System.Net.Quic.Functional.Tests.deps.json xunit.console.dll System.Net.Quic.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 104 of 110 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 6)
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.UnsupportedPlatforms_ThrowsPlatformNotSupportedException [SKIP]
      Condition(s) not met: "IsQuicUnsupported"
  Finished:    System.Net.Quic.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Quic.Functional.Tests  Total: 324, Errors: 0, Failed: 0, Skipped: 1, Time: 121.848s

```

**Comment by wfurt** [comment]
(containers build binaries from  [dotnet/msquic](https://github.com/dotnet/msquic) `main`  branch)

**Review by rzikm — APPROVED** [review]

**Comment by wfurt** [comment]
finished on Ubuntu22

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73963-merge-1a42391e4e8140b7a4/System.Net.Quic.Functional.Tests/1/console.7143a945.log?helixlogtype=result

```
Console log: 'System.Net.Quic.Functional.Tests' from job 1a42391e-4e81-40b7-a411-8cc646f76590 (ubuntu.1804.armarch.open) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-helix-arm64v8-20220824230626-06f234f on ddvsotx2l198

/root/helix/work/correlation/dotnet exec --runtimeconfig System.Net.Quic.Functional.Tests.runtimeconfig.json --depsfile System.Net.Quic.Functional.Tests.deps.json xunit.console.dll System.Net.Quic.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 104 of 110 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 4)
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.UnsupportedPlatforms_ThrowsPlatformNotSupportedException [SKIP]
      Condition(s) not met: "IsQuicUnsupported"
  Finished:    System.Net.Quic.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Quic.Functional.Tests  Total: 324, Errors: 0, Failed: 0, Skipped: 1, Time: 156.056s

```

**Pull request merged**
