### PR TITLE
Adding vectorized implementations of Log to Vector64/128/256/512

### PR DESCRIPTION
**Pull request by tannergooding**
This makes progress towards #93513

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @stephentoub, @michaelgsharp for review.

Will likely put up separate PRs for a few others over the weekend, like `Exp` and the rest of the ones already accelerated for `float` in `TensorPrimitives`

May also finish up several of the trig ones (`Cos`, `Sin`, `Tan`, etc)

**Comment by stephentoub** [comment]
I assume structurally this is a carbon-copy of https://github.com/dotnet/runtime/issues/93513?

**Comment by tannergooding** [comment]
> I assume structurally this is a carbon-copy of https://github.com/dotnet/runtime/issues/93513?

Yes, same general setup/considerations. Just for the Log method now instead of Log2

**Review by stephentoub — APPROVED** [review]

**Comment by tannergooding** [comment]
Test failures are known and tracked.

**Pull request merged**
