### PR TITLE
Pipeline performance tweaks (follow-up)

### PR DESCRIPTION
**Pull request by tkp1n**
This is a follow-up to #36815 by @benaadams:

- Remove explicit null check based on the facts that `sizeHint` is guaranteed to be non-negative and `maxSize == -1` if `_pool is null`.
- Apply tweaks from Pipe to duplicated code in StreamPipeWriter

### CODE REVIEW

**Comment by stephentoub** [comment]
@tkp1n, are you still working on this?  @halter73, @davidfowl, what are the next steps here?  Thanks.

**Comment by halter73** [comment]
Thanks for pinging me @stephentoub. This fell off my radar. I think we should merge this. It's just removing an unnecessary `_pool != null` check.

We could run our [PipeThroughputBenchmark](https://github.com/dotnet/aspnetcore/blob/bc56ee1e3c869d4c725290ddec6295cabc17efb8/src/Servers/Kestrel/perf/Kestrel.Performance/PipeThroughputBenchmark.cs) to see if it even makes a difference in that microbenchmark. My guess is that removing a single comparison won't have a measurable impact. But even so, setting `_maxPooledBufferSize` to `-1` when a pool isn't provided makes sense to me.

**Review by halter73 — APPROVED** [review]

**Comment by danmosemsft** [comment]
@halter73 can this be merged now? this PR is over 6 months old. 😃

**Comment by halter73** [comment]
Merged. Thanks @tkp1n! Sorry for the delay.

**Pull request merged**
