### PR TITLE
[workloads] Upstream workload fixes from 7.0

### PR DESCRIPTION
**Pull request by steveisok**
From https://github.com/dotnet/runtime/pull/75486

- The updated task now provides metadata that will allow us to split the VSDROP generation into two separate archives. One which only contains workload packs (needed to share DROPs across VS versions to support multi-targeting) and another that only contains the manifest installers and workload components.
- The ZIP archive names have been updated to disambiguate its contents and support automatic drop creation during staging.

Most of the changes are in `eng` due to the Arcade update to obtain the latest copy of the workload build tasks. Those changes are unrelated to the workload fix, but appears to be necessary.

### CODE REVIEW

**Comment by steveisok** [comment]
Official build run https://dev.azure.com/dnceng/internal/_build/results?buildId=2113072&view=results

**Comment by joeloff** [comment]
LGTM. We should double check that the versioning fixes we made in 7.0 are in as well. When I looked at the preview.1 VS components, they were versioned as 8.0.0 instead of using the AssemblyFileVersion value that would include build data to support upgrading the workload components in VS. We'd need to verify that using an official build and can probably do that once this is merged.

**Comment by joeloff** [comment]
Looks like the official build failed with a missing package error.

**Comment by steveisok** [comment]
> Looks like the official build failed with a missing package error.

Has something to do with arm64 packs. I'm not sure why.

` Unable to find package Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.browser-wasm.Msi.arm64`

**Comment by steveisok** [comment]
@joeloff trying the official build again.  I'm not sure why it was not finding the arm64 msi pack. Any ideas?

https://dev.azure.com/dnceng/internal/_build/results?buildId=2121737&view=results

**Comment by joeloff** [comment]
> @joeloff trying the official build again. I'm not sure why it was not finding the arm64 msi pack. Any ideas?
> 
> https://dev.azure.com/dnceng/internal/_build/results?buildId=2121737&view=results

No idea, all the packs should have been built, unless there's maybe a typo and the arm64 pack is different than what the manifest specifies. If this build fails again I'll go over the logs in more detail and compare with the artifacts.

**Comment by steveisok** [comment]
Up to date official build https://dev.azure.com/dnceng/internal/_build/results?buildId=2124909&view=results

**Comment by steveisok** [comment]
@joeloff since the official build is good, can you approve?

**Review by joeloff — APPROVED** [review]
I confirmed the creation of the separate drop zips for packs and components on the official build.

**Pull request merged**
