### PR TITLE
Update Microsoft.DotNet.Build.Tasks.SharedFramework.Sdk.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Unblocks #36715

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
@chcosta I'm seeing failures here with uptaking https://github.com/dotnet/arcade/pull/5442 and/or https://github.com/dotnet/arcade/pull/5473

**Comment by jkoritzinsky** [comment]
Any chance you can take a look?

**Comment by jkoritzinsky** [comment]
It looks like the SharedFramework SDK doesn't gracefully fall back when `EnableCreateLightCommandPackageDrop` isn't set to `true`.

**Comment by chcosta** [comment]
Yikes, sorry about that. @jcagme, can you take a look?

**Comment by jcagme** [comment]
> Yikes, sorry about that. @jcagme, can you take a look?

I have a rest of the day packed with meetings but I will take a look when I can for sure! @jkoritzinsky looks like setting `EnableCreateLightCommandPackageDrop` to true unblocked you?

**Comment by jkoritzinsky** [comment]
Yep! Setting it to true fixed the build thankfully. This bug will likely break uptake into dotnet/windowsdesktop as well.

**Comment by jcagme** [comment]
Could you please point me to the logs/errors you see when it is set to `false`?

**Comment by jkoritzinsky** [comment]
It’s not set by default anywhere that I could find. You need to explicitly set it to true currently.

**Comment by jcagme** [comment]
Yeah what I meant is that if you could share logs where this failed before enabled it.

**Comment by jkoritzinsky** [comment]
I've sent you a binlog in email.

**Comment by jkoritzinsky** [comment]
It looks like CI is failing, so we might not be out of the woods here yet.

**Comment by jkoritzinsky** [comment]
There's an additional race around creating the NonShipping packages folder. The LightCommandPackages paths assume that it already exists, which it might or might not depending on project build order.

**Comment by jkoritzinsky** [comment]
This is now blocked on an SDK update in dotnet/arcade#5552, which fixes the SDK issues found in this PR. If we can get that reviewed and merged in quickly, I'd highly appreciate it.

**Pull request merged**
