### PR TITLE
Delete UsePublishedCrossgen2 property

### PR DESCRIPTION
**Pull request by jkotas**
It should not be necessary after #107772

### CODE REVIEW

**Review by ivdiazsa — APPROVED** [review]
Thank you so much for fixing this Jan! Are these errors related to these changes?

`* You intended to execute a .NET program, but dotnet-/__w/1/s/artifacts/bin/coreclr/linux.x64.Release/crossgen2/crossgen2.dll does not exist.`

We can merge once we get these ones resolved or confirmed to be unrelated.

**Comment by jkotas** [comment]
> Are these errors related to these changes?

Yes, these errors are related. I need to fix those before this can be merged.

**Pull request merged**
