### PR TITLE
Add two readonlys to IcuLocaleData.cs

### PR DESCRIPTION
**Pull request by stephentoub**
Follow-up to https://github.com/dotnet/runtime/pull/45296
cc: @marek-safar

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]

**Review by marek-safar — APPROVED** [review]

**Comment by marek-safar** [comment]
Is there analyzer we could enable to catch this?

**Comment by stephentoub** [comment]
> Is there analyzer we could enable to catch this?

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0044
https://github.com/dotnet/runtime/blob/296f4de3c0e0c3c9854407089eb63e5be33ef3bf/eng/CodeAnalysis.ruleset#L446

**Comment by marek-safar** [comment]
> It's not ideal for Corelib, though, given how many fields end up being used from native.

What do you mean, it should kick in only for the inline assigned fields. Do we do that for such fields?

**Comment by stephentoub** [comment]
> it should kick in only for the inline assigned fields

It warns about any fields for which there aren't any assignments outside of ctors / declarations.  That means any fields which are set by the EE end up getting flagged.  Just change that one line from Hidden to Warning, build corelib, and you'll see what I mean.

**Pull request merged**
