### PR TITLE
[mono] Disable UnitTest_GVM_TypeLoadException for fullAOT jobs

### PR DESCRIPTION
**Pull request by matouskozak**
The test was disabled in https://github.com/dotnet/runtime/pull/106716 at
https://github.com/dotnet/runtime/blob/c4792a228ea36792b90f87ddf7fce2477e827822/src/tests/issues.targets#L1136C107-L1136C137 for NativeAOT. 

The tests are failing on fullAOT-[mini/llvm] jobs with `Attempting to JIT compile method 'void CMain:RunInvalidTest1 ()' while running in aot-only mode.`

### CODE REVIEW

**Comment by matouskozak** [comment]
@davidwrighton is the test expected to fail on fullAOT or should we investigate instead of disabeling it?

**Review by davidwrighton — APPROVED** [review]

**Pull request merged**
