### PR TITLE
Improve morphing of bit comparisons to constant 0/1

### LINKED ISSUE #72986: JIT: Recognize 'bt' bit test idiom
### Description

I've been recently developing a chess engine in C# (.NET Core 6), [StockNemo](https://github.com/TheBlackPlague/StockNemo), where when I analyzed the code, RyuJIT was generating assembly far more complex than one would assume it should be. So, I decided to compare it with C++'s GCC compiler (with the `-O3` flag to ensure proper optimization, I imagine the equivalent to dotnet's `Release` configuration) and turns out I was right. 

Consider the following code: 
```cs
readonly ulong Internal = 0x003;

bool GetSetBit(int i) => (Internal >> i & 1UL) == 1UL;
```

**RyuJIT** generates the following assembly for the method `GetSetBit` in release configuration:
```asm
       mov      rax, qword ptr [rdi+8]
       mov      ecx, esi
       shr      rax, cl
       test     al, 1
       setne    al
       movzx    rax, al
       ret      
```

The similar code in C++ looks like this:
```cpp
unsigned long long internal = 0x003;

bool get_set_bit(int i)
{
    return (internal >> i & 1ULL) == 1ULL;
}
```

**GCC 12.1 x86-64** generates the following assembly for the method `get_set_bit` with the `-O3` argument:
```asm
        mov     rax, QWORD PTR internal[rip]
        bt      rax, rdi
        setc    al
        ret
```

As one can see, the GCC-generated assembly is better. There is a way to get the same or nearly as simple and fast assembly as C++,
and that's by arranging the method like so, with its C++ counterpart below:
```cs
bool GetSetBit(int i) 
{
    byte value = (byte)(Internal >> i & 1UL);
    return Unsafe.As<byte, bool>(ref value);
}
```
```cpp
typedef int boolean;
#define true 1
#define false 0

boolean get_set_bit(int i)
{
    return internal >> i & 1ULL;
}
```

The generated assembly for this by RyuJIT is:
```asm
       mov      rax, qword ptr [rdi+8]
       mov      ecx, esi
       shr      rax, cl
       and      eax, 1
       ret      
```
...and by GCC:
```asm
        mov     rax, QWORD PTR internal[rip]
        mov     ecx, edi
        shr     rax, cl
        and     eax, 1
        ret
```

This is just one of many functions that have much more complicated assemblies when generated by RyuJIT (compared to GCC). When micro-optimization is necessary (in chess engines, it is), the generated assemblies are to be as performant. This is not the case by default here; one had to repurpose the code to get the exact same thing. Many times, due to missing language features, this just isn't possible.

I'm not trying to shame or undermine the work done for RyuJIT but requesting better code understanding and generation. I love the C# language (which is why I chose to do the project in C# while knowing C++), and I wish that the code be as fast (or, if possible, faster) as C++.

### PR DESCRIPTION
**Pull request by dubiousconst282**
This PR does the following:
- Allow morphing `((x >> CNS(y)) & 1) EQ/NE 0/1` -> `(x & CNS(1 << y)) EQ/NE 0` with non-constant `y`, but only in some cases (if it's comparing the result to non-zero, or if the node is being used by a branch). This allows the lowering pass to create BT nodes for the latter pattern.
- ~Lower `EQ(AND(x, 1), 1)` into `AND(x, 1)` by checking for TEST_NE instead of EQ/NE nodes. This should remove the need to identify variations such as `(x & 1) != 0`, while also avoiding interferences with later transforms based on EQ/NE nodes.~
- Lower `NE/EQ(AND(x, 1), 0/1)` into `AND(x, 1)`

I wasn't able to get the morph heuristic to work with `(x >> y & 1) != 1`, because the IR looks like `EQ(EQ(..., 1), 0)`, but there are no diffs in this case.

Fixes https://github.com/dotnet/runtime/issues/72986.

<details>
<summary>Diffs</summary>

```cs
    public static string BitTest_If_Ne0(int x, int y) => (x >> y & 1) != 0 ? "X" : " ";
    public static bool BitTest_Eq0(int x, int y) => (x >> y & 1) == 0;
    public static bool BitTest_Eq1(int x, int y) => (x >> y & 1) == 1;
    public static bool BitTest_Ne0(int x, int y) => (x >> y & 1) != 0;
    public static bool BitTest_Ne1(int x, int y) => (x >> y & 1) != 1;
    public static bool And1_Eq0(int x) => (x & 1) == 0;
    public static bool And1_Eq1(int x) => (x & 1) == 1;
    public static bool And1_Ne0(int x) => (x & 1) != 0;
    public static bool And1_Ne1(int x) => (x & 1) != 1;
```
```diff
 ; Assembly listing for method Program:BitTest_If_Ne0(int,int):System.String
-       sarx     eax, ecx, edx
-       test     al, 1
-       jne      SHORT G_M39616_IG05
+       bt       ecx, edx
+       jb       SHORT G_M39616_IG05
        mov      rax, 0xD1FFAB1E      ; " "
        mov      rax, gword ptr [rax]
        ret
        mov      rax, 0xD1FFAB1E      ; "X"
        mov      rax, gword ptr [rax]
        ret
 ; Assembly listing for method Program:BitTest_Eq0(int,int):bool
-       sarx     eax, ecx, edx
-       test     al, 1
-       sete     al
+       bt       ecx, edx
+       setae    al
        movzx    rax, al
        ret
 ; Assembly listing for method Program:BitTest_Eq1(int,int):bool
        sarx     eax, ecx, edx
        and      eax, 1
        ret
 ; Assembly listing for method Program:BitTest_Ne0(int,int):bool
        sarx     eax, ecx, edx
-       test     al, 1
-       setne    al
-       movzx    rax, al
+       and      eax, 1
        ret
 ; Assembly listing for method Program:BitTest_Ne1(int,int):bool
        sarx     eax, ecx, edx
        test     al, 1
        sete     al
        movzx    rax, al
        ret
 ; Assembly listing for method Program:And1_Eq0(int):bool
        xor      eax, eax
        test     cl, 1
        sete     al
        ret
 ; Assembly listing for method Program:And1_Eq1(int):bool
        mov      eax, ecx
        and      eax, 1
        ret
 ; Assembly listing for method Program:And1_Ne0(int):bool
-       xor      eax, eax
-       test     cl, 1
-       setne    al
+       mov      eax, ecx
+       and      eax, 1
        ret
 ; Assembly listing for method Program:And1_Ne1(int):bool
        xor      eax, eax
        test     cl, 1
        sete     al
        ret
```
</details>

[SPMI diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1972033&view=results)

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=73120) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=73120) before we can accept your contribution.<br/><br/>:x: dubiousconst282 [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=73120)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=73120) it.</sub>

**Review by AndyAyersMS — APPROVED** [review]
Changes LGTM. Thanks!

We will hold off on merging until the 7.0 release branches off from `main` (see #72297 for schedule).

**Comment by jakobbotsch** [comment]
The Fuzzlyn failures look like the ones fixed by #73146. I'm not really sure what happened here, normally jobs triggered via the bot run on a merge of the PR head commit and current main, but in this case it ran directly on the head commit 991ff69d that does not have c4ea81d8ef85afded5ddbc236841aed88cde91c0.

I would retrigger it but since this is still a draft I'll wait.

**Comment by dubiousconst282** [comment]
Thanks! I was holding on draft to investigate regressions from the CI diffs, but there aren't many. I think it's ready now.

**Comment by AndyAyersMS** [comment]
@dubiousconst282 we are ready to take in new changes once more.

Can you fix the merge conflicts?

**Comment by dubiousconst282** [comment]
@AndyAyersMS Done

**Comment by AndyAyersMS** [comment]
Interesting and almost certainly unrelated Fuzzlyn failure. No core dump so not sure this is actionable.

FYI @janvorli in case we start seeing this more often.
```
OSX arm64 checked

Assert failure(PID 24175 [0x00005e6f], Thread: 2129739 [0x207f4b]): !"Unable to commit a loaderheap code page"
    File: /Users/runner/work/1/s/src/coreclr/utilcode/loaderheap.cpp Line: 1173
    Image: /private/tmp/helix/working/A4B6094A/p/CoreRoot/corerun
```

**Comment by AndyAyersMS** [comment]
@dubiousconst282 thank you for your contribution!

**Pull request merged**
