### PR TITLE
For large allocation tests, check for available memory on Windows too

### LINKED ISSUE #13551: Test failed: GC\LargeMemory\Allocation\largeexceptiontest\largeexceptiontest.cmd
**Job:**
[coreclr-outerloop #20191008.1 Run Test Pri1 Windows_NT x64 checked](https://dev.azure.com/dnceng/public/_build/results?buildId=381461)

**Detail:**
https://helix.dot.net/api/2019-06-17/jobs/868a4360-6dc3-4ebd-b432-87b6a96fe7b0/workitems/PayloadGroup0/console

**OS & Arch:**
windows x64

**Mode:**
COMPlus_TieredCompilation=0

**Note:**
This failure **doesn't repro** on our windows x64 machine.

**Log:**
```
GC\LargeMemory\Allocation\largeexceptiontest\largeexceptiontest.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\dotnetbuild\work\868a4360-6dc3-4ebd-b432-87b6a96fe7b0\Work\246a3912-c5e0-4477-b8bf-ccf70caaff41\Exec\GC\LargeMemory\Reports\GC.LargeMemory\Allocation\largeexceptiontest\largeexceptiontest.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\dotnetbuild\work\868a4360-6dc3-4ebd-b432-87b6a96fe7b0\Payload\corerun.exe" largeexceptiontest.dll 2048 
      Large Memory Machine required
      Test failed
      Expected: 100
      Actual: 0
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
```

### PR DESCRIPTION
**Pull request by ghost**
Previously, we had logic to get the physical memory on non-Windows,
but nothing on Windows.
This means that on windows machines with low memory, we would allocate
too much and the test would fail.
This PR logic to get physical memory on Windows too.

On Windows, it invokes the systeminfo command.
It shares parsing logic with the non-windows case, since they both need
to look for a line with a particular start and end.

Tested this change by manually increasing the allocation size in
largeexceptiontest.cmd and seeing that it allocated 300MB instead.
Also did the same test on Ubuntu since non-Windows code was affected too.

Fix #13551

### CODE REVIEW

**Comment by jashook** [comment]
This should run outerloop

**Comment by stephentoub** [comment]
@andy-ms, are you still working on this?  Should it be closed?

**Comment by stephentoub** [comment]
@maonis, could you either fix/merge this or close it? Thanks!

**Comment by Maoni0** [comment]
sorry for the delay, @stephentoub. I have talked to Andrew about this and will assign this to him.

**Comment by cshung** [comment]
Closed as obsolete, the work is continued on https://github.com/dotnet/runtime/pull/32545

**Pull request closed without merging**
