### PR TITLE
Enable limited Apple Silicon GCStress testing

### PR DESCRIPTION
**Pull request by sdmaclea**

### CODE REVIEW

**Comment by sdmaclea** [comment]
I am surprised there are no azp gcstress triggers.

Manually scheduled 

https://dev.azure.com/dnceng/public/_build/results?buildId=1052922
https://dev.azure.com/dnceng/public/_build/results?buildId=1052931

**Review by BruceForstall — APPROVED** [review]
I think the only think you're not getting by doing this instead of adding OSX_arm64 to platformGroup gcstress (by amending common\platform-matrix.yml) is r2r-extra. Note that the libraries-gcstress* jobs are disabled currently.

Before you merge this, make sure there are no OSX_arm64 gcstress failures (at least, no unique-to-OSX_arm64 failures). Unfortunately, there are existing, un-investigated failures in these gcstress jobs. But we don't need to add more.

**Comment by sdmaclea** [comment]
- `gc-simulator` and `gc-longrunning` are controlled by the gcstress group too.  Since Apple Silicon is so unstable and the M1 queues are a limited resource, I didn't want to enable these yet.
- there are crossgen gcstress pipelines too.  I didn't want to enable those yet as crossgen2 is still broken for Apple Silicon.

**Pull request merged**
