### PR TITLE
Minor QUIC API changes

### PR DESCRIPTION
**Pull request by geoffkizer**
Remove `ShutdownWriteCompleted()`
Rename `Shutdown()` to `CompleteWrites()`

### CODE REVIEW

**Comment by JamesNK** [comment]
While you're changing API, could you add Async suffic to the async methods? e.g. ShutdownCompleted -> ShutdownCompletedAsync.

**Comment by wfurt** [comment]
Shutdown has pretty standard meaning but we may do something different here. SslStream has `ShutdownAsync`.

The check and azp seems busted ;(

**Comment by geoffkizer** [comment]
> The check and azp seems busted ;( 

And what a perfect time for it, too :)

**Comment by geoffkizer** [comment]
> ShutdownCompleted -> ShutdownCompletedAsync.

We are still discussing whether ShutdownCompleted will go away entirely and be replaced by CloseAsync.

If it doesn't, we can certainly look at renaming this.

**Comment by karelz** [comment]
I thought we decided to push QUIC APIs updates to .NET 7, unless they are must-have for our functional and reliability goals in .NET 6.
@geoffkizer is this one necessary?

We need to keep in mind that while renames are good clean up, it has affect on ASP.NET side as they need to react. Given where we are in the release (almost past platform complete as of today), that may be problematic.
Let's talk about it in today's meeting more ...

**Comment by karelz** [comment]
Triage: We are fine with removing the dead code.
The renames are not complete and we will need more in .NET 7, let's wait with them all for .NET 7.

**Comment by geoffkizer** [comment]
> We need to keep in mind that while renames are good clean up, it has affect on ASP.NET side as they need to react. Given where we are in the release (almost past platform complete as of today), that may be problematic.

I discussed this previously with @jamesnk and he said it was fine to do. In fact as you can see, he's asking for more API renames above :)

**Comment by geoffkizer** [comment]
Okay, I punted the Shutdown rename and reposted this PR here: https://github.com/dotnet/runtime/pull/55981

**Pull request closed without merging**
