### PR TITLE
[release/5.0] Update to latest .NET 5 SDK

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@danmoseley @jeffschwMSFT Required to unblock 5.0 builds.

**Comment by mmitche** [comment]
@jeffschwMSFT Interesting test failures?

**Comment by jeffschwMSFT** [comment]
It is 1 test failure that is failing consistently across these runs.  @agocke / @mateoatr can y'all take a look at this 5.0 test failure?

      [3:55:32 PM] Running SatelliteAssembly_CultureSubdirectory...
      Test SatelliteAssembly_CultureSubdirectory failed: System.IO.FileNotFoundException: Could not load file or assembly 'AssemblyToLoad_Subdirectory.resources, Culture=fr-FR, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'AssemblyToLoad_Subdirectory.resources, Culture=fr-FR, PublicKeyToken=null'
         at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
         at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
         at BinderTracingTests.BinderTracingTest.SatelliteAssembly_CultureSubdirectory() in /Users/runner/work/1/s/src/tests/Loader/binding/tracing/BinderTracingTest.DefaultProbing.cs:line 160
         at BinderTracingTests.BinderTracingTest.RunSingleTest(MethodInfo method) in /Users/runner/work/1/s/src/tests/Loader/binding/tracing/BinderTracingTest.cs:line 171
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED

**Comment by agocke** [comment]
Looking -- unfortunately it seems to have passed locally for me, so I'll need to investigate more

**Comment by mmitche** [comment]
@agocke Should I merge this to unblock 5.0 or is this worrying enough to warrant holding off 5.0 for?

**Comment by mateoatr** [comment]
I can repro and I'm looking why this started happening; not seeing anything obvious. Based on the [csproj](https://github.com/dotnet/runtime/blob/release/5.0/src/tests/Loader/binding/tracing/BinderTracingTest.Basic.csproj) of the failing test, it looks like the assemblies are not being put in the expected location.

**Comment by mmitche** [comment]
> I can repro and I'm looking why this started happening; not seeing anything obvious. Based on the [csproj](https://github.com/dotnet/runtime/blob/release/5.0/src/tests/Loader/binding/tracing/BinderTracingTest.Basic.csproj) of the failing test, it looks like the assemblies are not being put in the expected location.

So this looks like a test issue?

**Comment by jeffschwMSFT** [comment]
Building on Matt's comment.  If we feel this is a regression, what is the likely impact?  Since this is the SDK to build the product, do we have this pattern and this is a guard against a later/subtle failure.

If we feel this has a low impact, we can disable and unblock this dependency flow and continue to investigate.

**Comment by agocke** [comment]
It also looks like it only happens in checked builds. We could probably disable the test for now while we investigate

**Pull request merged**
