### PR TITLE
Fix constant folding for PopCount on 32 bit targets

### LINKED ISSUE #48504: Assertion failed 'gtOper == GT_CNS_INT' in 'System.Numerics.Tests.BitOperationsTests:BitOps_PopCount_Constant()' during 'Importation'
Seeing lot of `runtime-coreclr libraries-jitstressregs` failures in Linux arm and Windows x86 . It started happening between 1/21 and 1/24.

Run from 1/21: https://dev.azure.com/dnceng/public/_build/results?buildId=961156&view=results
Run from 1/24: https://dev.azure.com/dnceng/public/_build/results?buildId=963693&view=results

The only related change that went in was https://github.com/dotnet/runtime/pull/47133

### PR DESCRIPTION
**Pull request by SingleAccretion**
`IconValue` can only represent `CNS_INT` constants. Use `IntegralValue`, which can represent any integer constant, including `CNS_LNG`. This is technically less efficient on 32 bit, but the presumption is this path is hit rarely enough for that to not matter.

I have verified locally (via the altjit) that the [original reproduction](https://gist.github.com/SingleAccretion/414b32b23ca0f76c2d1410f29cc9a09a) now compiles to the following for `x86`:
```asm
G_M28557_IG01:
       push     ebp
       mov      ebp, esp
G_M28557_IG02:
       pop      ebp
       ret
```

Fixes #48504.

cc @AndyAyersMS

### CODE REVIEW

**Comment by EgorBo** [comment]
So I assume your foldConstExpr uncovered an issue in https://github.com/dotnet/runtime/pull/37836

**Review by EgorBo — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
If the failure was only seen in stress regs it would be a good idea to add an explicit test.

**Comment by SingleAccretion** [comment]
I find it rather curious how the following incredibly simple reproduction detects this issue while the `Xunit.Assert.Equal` method did not.
```CS
using System;
using System.Numerics;

Console.WriteLine(64 == BitOperations.PopCount(18446744073709551615UL));
```
```
dotnet run -r win-x86 -c Release
False
dotnet run -r win-x64 -c Release
True
```
I will need some more time to investigate this.

**Comment by SingleAccretion** [comment]
Of course... `COMPlus_TieredCompilation` was the missing piece of the puzzle. We do not fold when compiling Tier0, thus the original test wasn't actually testing what it was meant to test. I will move the test to `tests/JIT` then and mark it with `AggressiveOptimization`.

It is a bit scary to recognize the fact that libraries tests aren't actually testing optimized code a lot of the time.

**Comment by AndyAyersMS** [comment]
Agree that CI test coverage of Tier1 is a concern.

We should be running libraries tests with TC disabled as a proxy. Not quite the same codegen as Tier1, but for now, close enough. @dotnet/jit-contrib anyone know if this is the case?

**Comment by BruceForstall** [comment]
> We should be running libraries tests with TC disabled as a proxy. Not quite the same codegen as Tier1, but for now, close enough. @dotnet/jit-contrib anyone know if this is the case?

All the libraries jitstress/jitstressregs jobs disable TC, the same as the coreclr stress jobs.

**Comment by echesakovMSFT** [comment]
> 
> 
> > We should be running libraries tests with TC disabled as a proxy. Not quite the same codegen as Tier1, but for now, close enough. @dotnet/jit-contrib anyone know if this is the case?
> 
> All the libraries jitstress/jitstressregs jobs disable TC, the same as the coreclr stress jobs.

@BruceForstall Shouldn't this also true for "runtime-libraries-coreclr outerloop" pipeline? I couldn't find any mentions of TC set to 0 in the corresponding Helix jobs output logs. For example, I checked [runtime-libraries-coreclr outerloop #20210222.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1005742)

**Comment by AndyAyersMS** [comment]
Right, I was thinking we should have a non-stress run of libraries with TC disabled.

**Comment by BruceForstall** [comment]
The `runtime-coreclr libraries-jitstress` pipeline does a `no_tiered_compilation` leg. e.g., https://dev.azure.com/dnceng/public/_build/results?buildId=1005546&view=ms.vss-test-web.build-test-results-tab&runId=31391074&resultId=168525&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by AndyAyersMS** [comment]
Ah, I see it now. Thanks Bruce.

I wonder if we should run these in outerloop instead of bundling them in with stress.

```
COMPlus_TieredCompilation=0

C:\h\w\B5DD0A31\w\B08709ED\e>call RunTests.cmd --runtime-path C:\h\w\B5DD0A31\p 
----- start Sun 02/21/2021  7:49:05.92 ===============  To repro directly: ===================================================== 
pushd C:\h\w\B5DD0A31\w\B08709ED\e\
"C:\h\w\B5DD0A31\p\dotnet.exe" exec --runtimeconfig System.Runtime.Extensions.Tests.runtimeconfig.json --depsfile System.Runtime.Extensions.Tests.deps.json xunit.console.dll System.Runtime.Extensions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\B5DD0A31\w\B08709ED\e>"C:\h\w\B5DD0A31\p\dotnet.exe" exec --runtimeconfig System.Runtime.Extensions.Tests.runtimeconfig.json --depsfile System.Runtime.Extensions.Tests.deps.json xunit.console.dll System.Runtime.Extensions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Runtime.Extensions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Extensions.Tests (found 914 of 965 test cases)
  Starting:    System.Runtime.Extensions.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 4264 [0x000010a8], Thread: 2468 [0x09a4]): Assertion failed 'gtOper == GT_CNS_INT' in 'System.Numerics.Tests.BitOperationsTests:BitOps_PopCount_Constant()' during 'Importation' (IL size 223)

    File: D:\workspace\_work\1\s\src\coreclr\jit\gentree.h Line: 3114
    Image: C:\h\w\B5DD0A31\p\dotnet.exe
```

**Comment by BruceForstall** [comment]
coreclr libraries jitstress is specially handled, so I wouldn't really want to "bundle" with "normal" runs. See eng\pipelines\libraries\run-test-job.yml.

This pipeline runs 4 times a week. It appears it is very broken right now, which means our vendor team is probably missing some of the unique failures buried within.

**Comment by SingleAccretion** [comment]
@AndyAyersMS based on the above, is it still desirable to effectively promote the test to a Pri0 one? It seems like the real issue is somewhere else, and this code path is rarely hit.

**Comment by AndyAyersMS** [comment]
> is it still desirable to effectively promote the test to a Pri0 one

I think so, yes. Either Pri0 or Pri1.

**Comment by kunalspathak** [comment]
Thanks @SingleAccretion for fixing this.

**Comment by SingleAccretion** [comment]
CI failures look unrelated so rerunning...

**Comment by AndyAyersMS** [comment]
Failure was on `DDARM64-181`, known issue #48820. Will ignore.
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

**Comment by AndyAyersMS** [comment]
@tannergooding would you prefer we leave the libraries tests as is?

**Comment by tannergooding** [comment]
> would you prefer we leave the libraries tests as is?

I don't have a preference on where the test is added provided we have it and it is being run in a way that will catch failures like these (ideally before we ship next time 😄).
It sounds like the leg that normally would have caught this is very noisy right now and that is potentially masking actual failures like this?

Is there something we can do in `GenTreeIntCon` to help catch misuses like this in the future?
Have we looked at having a single `GenTreeIntCon` type and using `TYP_INT` vs `TYP_LONG` to determine if we should access the result as 32-bits or 64-bits?
* AFAIK, we have to account for these differences on 64-bit already and on 32-bit we need to check for `GenTreeIntCon` and `GenTreeLngCon`, so I'd expect we'd just be shuffling some checks around to centralize on a single type.

**Review by tannergooding — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
> Have we looked at having a single GenTreeIntCon type and using TYP_INT vs TYP_LONG

Not that I know of. @BruceForstall or @briansull may have more context on why things are the way they are.

**Comment by AndyAyersMS** [comment]
@SingleAccretion thank you for following up on this.

**Comment by BruceForstall** [comment]
> Not that I know of. @BruceForstall or @briansull may have more context on why things are the way they are.

It's somewhat historical; the JIT started as 32-bit only. But we don't want to be storing and using 64-bit ints on a 32-bit platform if we don't need the full 64 bits. Note that `IntegralValue()` is very rarely used (just for return value merging, before this change).

**Comment by tannergooding** [comment]
> But we don't want to be storing and using 64-bit ints on a 32-bit platform if we don't need the full 64 bits. Note that IntegralValue() is very rarely used (just for return value merging, before this change).

@BruceForstall, right. But nodes are either large or small, correct so storing 64-bits wouldn't actually increase the node size, it would just increase operation cost on 32-bit since it isn't "native".

However given that, is there any reason why we can't store a union (both 32-bits and 64-bits) and only access whichever field is appropriate based on the node type?

We already have to check for `IntCon` or `LngCon` on 32-bit, so it would seem that the union approach would translate over fairly well, but with the ability to assert that a `64-bit` constant isn't passed in with say `TYP_INT` (what happened here for `popcount`).

It would also give us a single node for integer constants that works for both 32-bit and 64-bit (rather than the current world with two separate concepts).

**Comment by BruceForstall** [comment]
> But nodes are either large or small, correct? So storing 64-bits wouldn't actually increase the node size, it would just increase operation cost on 32-bit since it isn't "native".

true

> However given that, is there any reason why we can't store a union (both 32-bits and 64-bits) and only access whichever field is appropriate based on the node type (that is TYP_INT vs TYP_LONG)?

It's *kind of* that way: there are lots of comments about gtIconVal being at the same place in both GenTreeIntCon and GenTreeLngCon. Not sure why. But I think most users either know they are dealing with a GT_CNS_INT (not long) when asking what value to grab.

It's possible (probable) this could be simplified. There's even this (now ancient) comment in GenTreeIntCon: "In the future when we retarget the JIT for x86 we should consider eliminating GT_CNS_LNG", apparently written before RyuJIT was ported to target x86.

**Pull request merged**
