### PR TITLE
Always build ref pack even in servicing releases

### PR DESCRIPTION
**Pull request by safern**
This was already done in release/6.0 branch, this is just making sure we have it in main so that in future servicing branches this is already taken care of.

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]
If similar work has been completed in dotnet/windowsdesktop, we should consider removing the `ProjectServicingConfiguration` feature from the SharedFramework SDK as there will be no users of it.

**Comment by RussKie** [comment]
Yes, addressed in https://github.com/dotnet/windowsdesktop/pull/2571.

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
> If similar work has been completed in dotnet/windowsdesktop, we should consider removing the `ProjectServicingConfiguration` feature from the SharedFramework SDK as there will be no users of it.

@jkoritzinsky it looks like it is still used by https://github.com/dotnet/deployment-tools/blob/097b01d7091fdf281144b4e22a5ff6245ea7cf04/eng/Versions.props#L46-L50

**Comment by jkoritzinsky** [comment]
That looks like it was copied straight from the old dotnet/core-setup repo and might be dead, but I’ll make sure before doing anything.

**Pull request merged**
