### PR TITLE
Fixing opts.setSupportedISAs to use the computed instructionSetFlags value

### LINKED ISSUE #34135: COMPlus_EnableISA=0 variables no longer effect the IsSupported checks
As per the title, the `COMPlus_EnableISA=0` variables are no longer functioning. For example, setting `COMPlus_EnableAVX=0` has no effect and `Avx.IsSupported` still returns true.

It does look to still impact parts of the system, such as the size of `Vector<T>`.

### PR DESCRIPTION
**Pull request by tannergooding**
This should resolve https://github.com/dotnet/runtime/issues/34135

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @CarolEidt, @davidwrighton 

The computed `instructionSetFlags` wasn't otherwise being used, so this looks to be the correct fix.

**Review by CarolEidt — APPROVED** [review]
LGTM - thanks for finding & fixing this!

**Review by davidwrighton — APPROVED** [review]
Sorry about that, I noticed it yesterday and didn't quite fix it all up yet.

**Comment by tannergooding** [comment]
@ViktorHofer, @safern; looks like an issue downloading the .NET SDK: https://dev.azure.com/dnceng/public/_build/results?buildId=574765&view=logs&j=9faa8814-1e1d-5dcb-3dbf-1c9ea62fd5f0&t=378c0a8c-7d34-5361-96eb-73148a466769

It looks like we are just trying to grab latest master so maybe a publishing issue where not everything is available at once?

**Comment by safern** [comment]
It seems like it is trying to grab an SDK from a dev test branch:  https://dev.azure.com/dnceng/internal/_build/results?buildId=575129

https://github.com/dotnet/installer/issues/6572#issuecomment-591594035

We're scaling this to get it fixed. cc: @mmitche

**Comment by MattGal** [comment]
> It seems like it is trying to grab an SDK from a dev test branch: https://dev.azure.com/dnceng/internal/_build/results?buildId=575129
> 
> [dotnet/installer#6572 (comment)](https://github.com/dotnet/installer/issues/6572#issuecomment-591594035)
> 
> We're scaling this to get it fixed. cc: @mmitche

To close the loop this was an issue with how channel-based publishing works and people spinning private branches on the offical build def;  should be over now.

**Pull request merged**
