### PR TITLE
[mono] Disable partial generic sharing for gparams with non-enum constraints.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Review by imhameed — APPROVED** [review]

**Comment by lewing** [comment]
@vargaz failures look potentially related

**Comment by vargaz** [comment]
There are no more failures, either they got fixed, or the failing lane was disabled:
runtime (Mono llvmfullaot Pri0 Runtime Tests Run Linux arm64 release)

**Comment by lewing** [comment]
cc @steveisok for test data

**Comment by steveisok** [comment]
We should merge and let the runtime tests run on the rolling build.

**Review by steveisok — APPROVED** [review]

**Comment by am11** [comment]
> There are no more failures, either they got fixed, or the failing lane was disabled

This is because tests are disabled, opened: https://github.com/dotnet/runtime/pull/61564. :)

**Pull request merged**
