### PR TITLE
Discard casts when storing normalize-on-load locals

### PR DESCRIPTION
**Pull request by jakobbotsch**
I noticed this when looking at some regressions when promoting more locals. Turning `ASG(IND(ADDR(LCL_VAR)), CAST(...))` into `ASG(LCL_VAR, CAST(...))` would regress some cases.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
[Small set of diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1714821&view=ms.vss-build-web.run-extensions-tab).

cc @dotnet/jit-contrib PTAL @BruceForstall

**Review by BruceForstall — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Test failure was #67878 and the Fuzzlyn failures had issues opened for them/are known.

**Pull request merged**
