### PR TITLE
Fix broken callstacks in interpreter on MonoVM.

### PR DESCRIPTION
**Pull request by lateralusX**
Running sample profiler on MonoVM interpreter sometimes hits broken callstacks, getting unknown frames in sampled callstacks, or callstacks missing chunks of methods, leading to incorrect display of callstacks in tools like SpeedScope, PerfView and Visual Studio. This is not a problem running under JIT or AOT, only interpreter.

Analysed and tracked down the missing chunks of methods in callstacks to interpreter not pushing LMF for several scenarios where we call into runtime code, meaning that the unwinder will jump pass interpreter methods until previous pushed LMF when sampled by sample profiler. Fixing this is a little tedious since we would need to audit interpreter code and make sure we push LMF when calling a MonoVM runtime method that might hit a safe point, blocking on coop locks, switching to GC safe etc. This PR fixes a couple of paths where I have seen broken callstacks, and also a couple of additional paths currently not in hot paths (mainly error cases or guarded by branches unlikely to happen). I have also marked several other paths that would need to be fixed at some point, but since they are currently in hot paths, or have not showed up in traces so far, I have just comment the code for potential future fix.

Tracked down the unknown frames to happen since we don't always add the ip to the frame when we push the LMF record (`frame->state.ip`). This issue became more visible when more code paths push LMF records as part of this PR.

With changes in this PR, running a couple of samples previously triggered both broken callstacks as well as callstacks with unknown frames, are now correctly displayed in tooling.

### CODE REVIEW

**Comment by vargaz** [comment]
Might be easier to save the state when entering/exiting an interp method if profiling is enabled.

**Comment by SamMonoRT** [comment]
@BrzVlad @lateralusX - any update on this ?

**Comment by lateralusX** [comment]
The PR are still fine I guess, solving most of the scenarios I encountered, so its mainly boils down to if we would like to handle this problem this way or some other way. If @BrzVlad is fine with this approach, then I believe I can polish it up and merge it.

**Comment by BrzVlad** [comment]
@lateralusX This change looks fine to me

**Comment by lateralusX** [comment]
Then I polish it up during the week.

**Comment by lateralusX** [comment]
Rebased and re-validated scenario on master, running sample profiler on Windows using interpreter. @BrzVlad guess PR is ready for review now. @lambdageek, this PR removes use of safepoint_frame since we now push a LMF frame we doing safepoints. I know this is used by hot reload, do we have tests validating that scenario?

**Review by BrzVlad — APPROVED** [review]

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
> Rebased and re-validated scenario on master, running sample profiler on Windows using interpreter. @BrzVlad guess PR is ready for review now. @lambdageek, this PR removes use of `safepoint_frame` since we now push a LMF frame we doing safepoints. I know this is used by hot reload, do we have tests validating that scenario?

@lateralusX There's nothing in CI, but the sample in src/mono/samples/mbr/console is multi-threaded and should validate that we're getting a correct LMF at a safepoint.  I ran it locally and it seems to be working as expected.

**Pull request merged**
