### PR TITLE
Update SuperPMI artifact logging

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fix suggested at https://github.com/dotnet/arcade/issues/11447

/cc @michellemcdaniel @riarenas

### CODE REVIEW

**Comment by BruceForstall** [comment]
If the System.JobAttempt works, then there is no need for "continueOnError: true" (because if we can't upload an artifact then it really is an error). Note that in the SuperPMI pipelines, this error isn't fatal (but is reported in the UI as an error).

However, the documentation for `System.JobAttempt` says that it is not available in templates:

https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

and this YAML is in a template. So does it work?


Also, the other SuperPMI pipelines have the same issue, not just this one.

Finally, every other pipeline that uses "PublishPipelineArtifact@1" (which is all of them?) simply sets "continueOnError: true" which means they fail to upload artifacts for 2nd and subsequent runs, and ignore those failures. They could also benefit from a change like this that properly uploads artifacts, if it works.

**Comment by riarenas** [comment]
>However, the documentation for System.JobAttempt says that it is not available in templates:

That usually means the variable is not available at template evaluation time, like to resolve conditionals on whether certain parts of YAML should execute.

The source-build template follows the approach of using the attempt just like this suggested change: https://github.com/dotnet/runtime/blob/a29912464638643845a5bbce9b3d8c734bfcd090/eng/common/templates/steps/source-build.yml#L112

That template uploads its logs as:
image

**Comment by riarenas** [comment]
> Note that in the SuperPMI pipelines, this error isn't fatal (but is reported in the UI as an error).

That doesn't seem to be the case for this pipeline, so I would check others for the same bug. https://dev.azure.com/dnceng-public/public/_build/results?buildId=65930&view=results's only failures were log upload failures, and they caused the build to fail.

**Comment by BruceForstall** [comment]
> That doesn't seem to be the case for this pipeline, so I would check others for the same bug. https://dev.azure.com/dnceng-public/public/_build/results?buildId=65930&view=results 's only failures were log upload failures, and they caused the build to fail.

Ok, my definition of "fail" here is a little different: the "real work" of the pipeline completes, and subsequent steps all get run, but the job still reports as failure.

> That usually means the variable is not available at template evaluation time, like to resolve conditionals on whether certain parts of YAML should execute.

That makes sense.

But we should actually test it with (1) a successful run where the log file name is now different, and (2) a failing run where we force a retry and see two log files.

Then, we should change all SuperPMI pipelines (and other pipelines) to the same system.

**Comment by AaronRobinsonMSFT** [comment]
I am going to change all uses of `PublishPipelineArtifact@1` in the SuperPMI pipelines to append the `_Attempt$(System.JobAttempt` and mark them as `continueOnError: true`.

Any other changes? I'd prefer to avoid continually kicking the CI, so let's iterate on expectations before I submit an update.

**Comment by BruceForstall** [comment]
The changes LGTM as-is.

I don't think the `continueOnError: true` is necessary, but since everybody else uses it for `PublishPipelineArtifact@1` I guess it's fine. If included, it means that any failure to upload a log file will not show up as a job failure. Maybe that's ok, or maybe it will hide problems that should be investigated. Given that the upload failure shouldn't happen, it seems like it should be investigated. At least to make sure that we're generating the correct file name that we expect to upload. (If there's some transient network issue on upload, that's out of our control.)

**Comment by AaronRobinsonMSFT** [comment]
Thanks @BruceForstall.

Can I get a sign off from someone?

**Comment by BruceForstall** [comment]
> Can I get a sign off from someone?

I'm happy to sign off after it is tested.

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall Whats the best way to make SuperPMI fail?

**Comment by BruceForstall** [comment]
> @BruceForstall Whats the best way to make SuperPMI fail?

I think you first want to test the success case. Note that the `runtime-coreclr superpmi-diffs` pipeline and `runtime-coreclr superpmi-replay` pipelines did not run on this PR because they only run if a file in the JIT directory changes. You probably want to trigger them manually (`azp run` might not work).

As for failure, this will cause it for superpmi replays:

https://github.com/dotnet/runtime/compare/main...BruceForstall:FailSpmi?expand=1

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall Can you help me trigger this? I am signed into AzDO, but am not being shown anything that allows me to trigger this run.

**Comment by BruceForstall** [comment]
I triggered superpmi-replay manually by going to https://dev.azure.com/dnceng-public/public/_build?definitionId=150&_a=summary, hitting "Run Pipeline", then using "refs/pull/77685/head" as the "Branch".

There's no need, IMO, to run the others: it would be the same testing, and there's no need to burn all those cycles.

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall Yep. Seems to work as expected - https://dev.azure.com/dnceng-public/public/_build/results?buildId=68877&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by AaronRobinsonMSFT** [comment]
I will revert my breaking trigger.

**Review by BruceForstall — APPROVED** [review]
Thanks for doing the testing.

**Pull request merged**
