### PR TITLE
Set vtable offset as contained

### PR DESCRIPTION
**Pull request by clamp03**
- Can remove a machine instruction which adds vtable offset

### CODE REVIEW

**Comment by clamp03** [comment]
A minor fix for virtual vtable call.

**Comment by sandreenko** [comment]
Hi Dong-Heon, thanks for submitting that PR.
How did you find that? Was it a particular scenario on a particular arch?

I see that `LowerVirtualVtableCall` is called by `LowerCall` and `LowerCall` calls `ContainCheckRange(controlExprRange);` that I supposed does the same analysis, I am wondering when it doesn't work.

PTAL @dotnet/jit-contrib

**Comment by clamp03** [comment]
@sandreenko Thanks for your comment.
I checked your comment.
I found that it cannot be handled in ContainCheckRange(controlExprRange).
Because the tmpTree node is not included in controlExprRange.
*. tmpTree node is included in range2 (LowerVirtualVtableCall)

```
range in LowerVirtualVtableCall
N001 (  3,  2) [001707] -------------     t1707 =    LCL_VAR   ref    V61 rat0
                                                   /--*  t1707  ref
N002 (  4,  3) [001708] -------------     t1708 = *  LEA(b+0)  byref
                                                   /--*  t1708  byref
N003 (  7,  5) [001709] -------------     t1709 = *  IND       int
                                                   /--*  t1709  int
N004 (  8,  6) [001711] DA-----------             *  STORE_LCL_VAR int    V62 rat1
$1 = void

range2 in LowerVirtualVtableCall
N001 (  3,  2) [001716] -------------     t1716 =    LCL_VAR   int    V62 rat1
N002 (  1,  1) [001715] -------------     t1715 =    CNS_INT   int    92
                                                   /--*  t1716  int
                                                   +--*  t1715  int
N003 (  5,  4) [001717] -------------     t1717 = *  ADD       int
N004 (  3,  2) [001712] -------------     t1712 =    LCL_VAR   int    V62 rat1
                                                   /--*  t1712  int
N005 (  4,  3) [001713] -------------     t1713 = *  LEA(b+68) int
                                                   /--*  t1713  int
N006 (  7,  5) [001714] -------------     t1714 = *  IND       int
                                                   /--*  t1717  int
                                                   +--*  t1714  int
N007 ( 13, 10) [001718] -------------     t1718 = *  LEA(b+(i*1)+0) int
                                                   /--*  t1718  int
N008 ( 14, 11) [001720] DA-----------             *  STORE_LCL_VAR int    V63 rat2

controlExprRange
N001 (  3,  2) [001721] -------------     t1721 =    LCL_VAR   int    V63 rat2         
                                                   /--*  t1721  int    
N002 (  6,  4) [001722] -------------     t1722 = *  IND       int   
N003 (  3,  2) [001723] -------------     t1723 =    LCL_VAR   int    V63 rat2         
                                                   /--*  t1722  int    
                                                   +--*  t1723  int    
N004 ( 10,  7) [001724] -------------     t1724 = *  ADD       int   
```

**Comment by sandreenko** [comment]
> How did you find that? Was it a particular scenario on a particular arch?

I have run `jit-diff.bat` for framework libraries (crossgen and pmi) for x64 Windows and it did not show any diffs from that change.
What platforms/tests does it affect?

**Comment by clamp03** [comment]
This is my experiment environment.
- Linux arm32 (Tizen) with -DFEATURE_NGEN_RELOCS_OPTIMIZATIONS=true build option
- Generate native code using FNV for Xamarin.Forms.Platform.Tizen (https://github.com/xamarin/Xamarin.Forms/blob/dcbf6ea454a012f59639d8a6cde82c1ecaa5b2f7/Xamarin.Forms.Platform.Tizen/Renderers/CarouselPageRenderer.cs#L45)
```
BEFORE
IN0137: 000376  2B      ldr     r0, [r7+44]
IN0138: 000378  2B      movs    r1, 2
IN0139: 00037A  2B      mov     r3, r0
IN013a: 00037C  2B      ldr     r3, [r3]
IN013b: 00037E  2B      movs    r2, 92
IN013c: 000380  2B      adds    r2, r3, r2
IN013d: 000382  2B      adds    r3, 68
IN013e: 000384  2B      ldr     r3, [r3]
IN013f: 000386  2B      adds    r3, r2, r3
IN0140: 000388  2B      ldr     r2, [r3]
IN0141: 00038A  2B      adds    r3, r2, r3
IN0142: 00038C  2B      blx     r3      // ElmSharp.Scroller:set_HorizontalScrollBarVisiblePolicy(int):this

AFTER (WITH the PATCH)
IN0137: 000376  2B      ldr     r0, [r7+44]
IN0138: 000378  2B      movs    r1, 2
IN0139: 00037A  2B      mov     r3, r0
IN013a: 00037C  2B      ldr     r3, [r3]
IN013b: 00037E  2B      movs    r2, 92
IN013c: 000380  2B      adds    r2, r3, r2
IN013d: 000382  2B      ldr     r3, [r3+68]
IN013e: 000384  2B      adds    r3, r2, r3
IN013f: 000386  2B      ldr     r2, [r3]
IN0140: 000388  2B      adds    r3, r2, r3
IN0141: 00038A  2B      blx     r3      // ElmSharp.Scroller:set_HorizontalScrollBarVisiblePolicy(int):this

```

**Comment by CarolEidt** [comment]
Thanks @sandreenko for looking into this.

> I see that LowerVirtualVtableCall is called by LowerCall and LowerCall calls ContainCheckRange(controlExprRange); that I supposed does the same analysis, I am wondering when it doesn't work.

I believe the issue is that `LowerVirtualVtableCall()` introduces new trees into the IR that are not contained in the range of the `controlExpr` (i.e. they are setup operations that aren't actually part of that tree). I think that handling them at the point they are introduced is the right thing to do, and is generally the approach taken when new IR is added in `Lowering`.

**Comment by sandreenko** [comment]
Finally, I was able to get the diffs:
```
"jit-dasm-pmi --platform F:\git\runtime\artifacts\tests\coreclr\Windows_NT.x86.Checked\Tests\Core_Root --altjit protononjit.dll --corerun F:\git\runtime\artifacts\tests\coreclr\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe --jit F:\git\runtime\artifacts\tests\coreclr\Windows_NT.x86.Checked\Tests\Core_Root_diff\protononjit.dll --nocopy --output F:\diffs\dasmset_23\diff F:\git\runtime\artifacts\tests\coreclr\Windows_NT.x86.Checked\Tests\Core_Root\System.Private.CoreLib.dll" returned with 1 failures
\ Finished 129/129 Base 129/129 Diff [2242.8 sec]
Found 4 files with textual diffs.
PMI CodeSize Diffs for System.Private.CoreLib.dll, framework assemblies for  protononjit.dll
Summary of Code Size diffs:
(Lower is better)
Total bytes of diff: -8 (-0.00% of base)
    diff is an improvement.
Top file improvements (bytes):
          -8 : Microsoft.Diagnostics.Tracing.TraceEvent.dasm (-0.00% of base)
1 total files with Code Size differences (1 improved, 0 regressed), 128 unchanged.
```

so I thought we have a test case for it as Carol asked, but then I looked at the actual diff:
before:
```
            mov     r1, r4
            movw    r4, 0xd1ff
            movt    r4, 0xd1ff
            movw    r2, 0xd1ff
            movw    lr, 0xd1ff
            movt    lr, 0xd1ff
            ldr     lr, [lr]
```
after:
```
            mov     r1, r4
            mov     r4, 0x7f8000                              
            movw    r2, 0xd1ff
            mov     lr, 0x7f8000                              
            ldr     lr, [lr]
```
and it looks more like a PMI diff infra issue rather than an improvement caused by this change.

I will check JitDump for that methods to undrstand that diff and will try to run tests on arm32 to see if we have cases there.

**Review by sandreenko — APPROVED** [review]
@CarolEidt I have not found test cases where we see diffs from that change (or run that code path). among checked PMU FX libraries and arm32 pri0 tests.

However, I think we will see examples in CoreFX tests for that and the change doesn't look risky, so I think we can merge it as it.

**Comment by CarolEidt** [comment]
@sandreenko - thanks for following up!

**Review by CarolEidt — APPROVED** [review]

**Comment by clamp03** [comment]
@sandreenko @CarolEidt Thank you.

**Pull request merged**
