### PR TITLE
[release/8.0] Bump Microsoft.Private.IntelliSense package version

### PR DESCRIPTION
**Pull request by carlossanlop**
This is the package for RC2.

Generated from https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=386331&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=11e7ea89-affe-5194-cdc6-0171c3394706

Manually pushed to dotnet8-transport: https://dnceng.visualstudio.com/public/_artifacts/feed/dotnet8-transport/NuGet/Microsoft.Private.Intellisense/overview/8.0.0-preview-20230918.1

### CODE REVIEW

**Comment by carlossanlop** [comment]
@mthalman heads-up: I'll manually update source-build-reference-packages with this new version like we did in https://github.com/dotnet/source-build-reference-packages/pull/774

**Review by ericstj — APPROVED** [review]

**Comment by ViktorHofer** [comment]
**Do not merge before the source-build-reference-packages PR is merged and the update PR merged into dotnet/runtime. Otherwise the CI will break.**

**Comment by carlossanlop** [comment]
> **Do not merge before the source-build-reference-packages PR is merged and the update PR merged into dotnet/runtime. Otherwise the CI will break.**

Do we need to trigger a dependency flow to release/8.0 manually, @mthalman?

**Comment by mthalman** [comment]
> > **Do not merge before the source-build-reference-packages PR is merged and the update PR merged into dotnet/runtime. Otherwise the CI will break.**
> 
> Do we need to trigger a dependency flow to release/8.0 manually, @mthalman?

First, the change needs to be ported to 8.0 branch in SBRP: https://github.com/dotnet/source-build-reference-packages/pull/787#issuecomment-1725467639. Then the dependency will flow to release/8.0 in runtime repo. Looks like the darc subscription triggers once a day for that. So it'll need to be manually triggered to get it sooner.

**Comment by carlossanlop** [comment]
The SBRP deps flow PR needs to be merged before we merge this: https://github.com/dotnet/runtime/pull/92143

**Comment by mthalman** [comment]
> The SBRP deps flow PR needs to be merged before we merge this: #92143

They're dependent on each other so they'll need to be combined. #92143 causes source-build prebuilts that are resolved by this PR.

**Comment by carlossanlop** [comment]
> so they'll need to be combined

Is it ok if I just merge one after the other instead? I don't want to reset the CI again, as we are already behind with the RC2 snap.

**Comment by mthalman** [comment]
> > so they'll need to be combined
> 
> Is it ok if I just merge one after the other instead? I don't want to reset the CI again, as we are already behind with the RC2 snap.

That's fine. As long as source-build continues to work in the branch, I'm happy.

**Pull request merged**
