### PR TITLE
JIT: Remove bbFallsThrough check in optFindLoopCompactionInsertionPoint

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Calling `bbFallsThrough` isn't all that helpful here, as it doesn't consider `BBJ_ALWAYS` blocks to the next block, `BBJ_COND` blocks that don't fall through for the false path, etc. I'm planning on getting rid of `bbFallsThrough` everywhere except in `fgReorderBlocks` (that removal will hopefully come when we replace our block layout algorithm altogether), but to still be able to short-circuit `optFindLoopCompactionInsertionPoint`, I added some manual checks for blocks that can "fall through."

cc @dotnet/jit-contrib, @jakobbotsch PTAL. The diffs weren't that big locally, but I'm open to different/more radical approaches here. Thanks!

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=604926&view=ms.vss-build-web.run-extensions-tab)

**Comment by AndyAyersMS** [comment]
The more radical thing would be to stop doing loop compaction entirely. Now that we have a flow-based approach to finding loops, it should not matter what other blocks might appear between the lexically first and lexically last loop blocks.

Whether we can "fix" this later though is likely the big question. Once we get to layout we will want to make loop bodies compact.

**Comment by amanasifkhalid** [comment]
> The more radical thing would be to stop doing loop compaction entirely.

I tried this locally out of curiosity, and the size/PerfScore regressions suggest our current layout algorithm doesn't handle uncompacted loops all that well. I've added a note to #93020 to consider skipping loop compaction once have a new layout algorithm, assuming the new algorithm does a decent job of placing loop bodies' blocks contiguously -- if we start with a RPO traversal, I guess that would negate the need for compaction?

**Comment by AndyAyersMS** [comment]
> if we start with a RPO traversal, I guess that would negate the need for compaction?

I believe that's the case, yes.

**Comment by jakobbotsch** [comment]
I don't think RPO will guarantee compactness of natural loops -- for example, the RPO can have outside-loop successors of the exiting blocks between the header and its inside-loop successors.

**Review by jakobbotsch — APPROVED** [review]
Seems fine to me. I hope long term we remove the compaction entirely in favor of the block layout in the backend.

**Pull request merged**
