### PR TITLE
Use `Unsafe.WriteUnaligned` in `BitConverter.GetBytes`

### PR DESCRIPTION
**Pull request by xtqqczze**
[sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoQgBgAJDSA6AJQFcA7DbAWxiYDCEHgAc8MKAGUJAN2xgYAZwDcVWg2bsuvfgEkuEiCOlQ5ClVTUBmBsToC6Abyp1XDG4yR1gATwwwAbQBdOgBxGAwAIT8lAH0AEWwAMySACiTcCABDDDoZLNw2GABKFzdnSjcq7xjgmv9FOgBeOg4YAHd6wMVsAC8YCDSM7IxioNVK6tcAVQ5FLKT+AHUobH9ZguwAczaAE1TYJLoAWRgeaB9jrKhFAAsCpnCMAEEoKCyfeJyslhhF2A4ClSvgaxTQeQKRWKEymrkIAHYuhZJq4AL5lOEeUheEGBEJPaINWJPV7vT7fX7/GCAmDpTI5CGFEoYpwsqq4uq4xotNqdDk9fqDOkjMYw2GzeaLJjPRQAHlx4OGOQAfAc/iczhcrjd7rhHhFSR8vhgfn8JNSgVzisVmoyimKpgikQ66KjqizCFicbV8RFCXFIllFLSlbl8kzSijWVH2T6kbbeV0AgKBkN6aNxmy3BKFvwZfKYor06rDkiAjQgjaWuH7Vm4YiuS70ZRUUA==)

Added `AggressiveInlining` to prevent regressions from from failure to inline.

### CODE REVIEW

**Comment by xtqqczze** [comment]
Similar changes should also be made in #91299.

**Comment by xtqqczze** [comment]
@MihuBot

**Comment by xtqqczze** [comment]
`jit-diffs` show regressions due to failure to inline and no improvements.

**Comment by stephentoub** [comment]
I appreciate the effort, but what is the concrete benefit of this change? A total of 20 bytes of IL and 0 impact on the resulting asm?  If that's all this buys, I don't think it's worth the churn.

**Comment by xtqqczze** [comment]
> I appreciate the effort, but what is the concrete benefit of this change? A total of 20 bytes of IL and 0 impact on the resulting asm? If that's all this buys, I don't think it's worth the churn.

The motivation was to avoid depending an implementation alignment assumption, i.e. the array data is 8-byte aligned.

I was hoping the reduced IL size might bring a benefit from improved inlining, but `jit-diffs` show the opposite, see the description for an example.

**Comment by xtqqczze** [comment]
@EgorBo I was surprised that the misses inlining a 19-byte method consisting of an allocation and two intrinsics.

**Comment by huoyaoyuan** [comment]
> i.e. the array data is 8-byte aligned.

https://github.com/dotnet/runtime/pull/91176#discussion_r1307186945
There can be some places depending on the fact. Is this clarified in any spec?

**Comment by MichalPetryka** [comment]
> Is this clarified in any spec?

AFAIR it's just an implementation detail of CoreCLR.

**Comment by jkotas** [comment]
> the array data is 8-byte aligned.

The array data is not 8-byte aligned on 32-bit platforms, and there is a risk of alignment fault on arm. We seem to be lucky that the JIT does not generate code that would hit the alignment fault - https://github.com/dotnet/runtime/issues/20729 has some discussion about it. It is a fragile assumption - it may be possible to trick the JIT into generating code that would hit the alignment fault on Arm32.

**Comment by MichalPetryka** [comment]
> I was hoping the reduced IL size

Does adding a call reduce the size here? `ref bytes[0]` should be smaller and should perform the same here.

**Comment by jkotas** [comment]
> Does adding a call reduce the size here? 

It does reduce IL size by one byte. It is not something we care about.

**Comment by xtqqczze** [comment]
@MihuBot

**Comment by xtqqczze** [comment]
@MihuBot

**Comment by xtqqczze** [comment]
@MihuBot

**Comment by xtqqczze** [comment]
The `System.Data.Common.ObjectStorage:Set` diffs may improve as a result of  #91945.

**Pull request closed without merging**
