### PR TITLE
[release/5.0] Fix Socket.ReceiveFrom regression on Unix

### PR DESCRIPTION
**Pull request by antonfirsov**
Backport of #46151 to release/5.0

Fixes: #45651

## Customer Impact

Reported by customer.
On Unix, when using blocking overloads of `Socket.ReceiveFrom` (typically used in UDP scenarios) after an asynchronous call to the same socket, the call may return wrong remote EndPoint (`remoteEP`).
A DNS server project hit this incompatibility (see #46151). We expect more UDP scenarios to hit it (typically on the server-side).

## Regression?

Yes. The behavior is correct on 3.1, it's a regression introduced in 5.0.

## Testing

New targeted test case included in the PR.

## Risk

Low. The bug was a small overlook in perf refactoring in the space during 5.0. The fix is minimal, and impacts only the affected sync-over-async `ReceiveFrom` path.

### CODE REVIEW

**Review by geoffkizer — APPROVED** [review]

**Comment by antonfirsov** [comment]
Unrelated test failure is #43981.

**Comment by karelz** [comment]
@danmosemsft this is ready for 5.0 servicing ...

**Pull request merged**
