### PR TITLE
Mono - Add error on warnings

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Contributes to https://github.com/dotnet/runtime/issues/66154

/cc @lambdageek @vargaz @lateralusX

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@lambdageek Yay for green!

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
@lateralusX we should really build with clang with [`-Wshorten-64-to-32`](https://clang.llvm.org/docs/DiagnosticsReference.html#wshorten-64-to-32) so that folks on OSX can get similar warnings that the Windows builds now enforce.  Otherwise warnings-as-errors-on-Windows is going to lead to a lot of frustration.

**Comment by lateralusX** [comment]
> @lateralusX we should really build with clang with [`-Wshorten-64-to-32`](https://clang.llvm.org/docs/DiagnosticsReference.html#wshorten-64-to-32) so that folks on OSX can get similar warnings that the Windows builds now enforce. Otherwise warnings-as-errors-on-Windows is going to lead to a lot of frustration.

Yes, that was one of the reasons I didn't enable the warnings as errors in my previous bump to W4 on Windows, so I would have suggested that we added it to this PR, but looks like it already got merged.

**Comment by lateralusX** [comment]
@AaronRobinsonMSFT we should also have dropped the section where we bump some warnings to errors in config.h.in, but I can do a PR during the day that take care of that as well as looking at doing some more warnings on OSX (the once that currently make sense, since we have still not enabled all needed warnings on Windows).

**Comment by AaronRobinsonMSFT** [comment]
@lateralusX Apologies in aggressively merging in the changes. Let me know how I can help move this forward to satisfy https://github.com/dotnet/runtime/issues/66154. I really want to get the inner dev loop in a good state so no more violations crop up. Warnings C4018 and C4244 are very common and will take some time to address. Hopefully we can avoid adding more of them.

**Pull request merged**
