### PR TITLE
Escape lower-cased type names

### PR DESCRIPTION
**Pull request by jcouv**
A warnlevel 7 warning is being added in VS 17.1 / SDK 6.0.200 to warn about lower-cased ascii type names. (See [PR](https://github.com/dotnet/roslyn/pull/56905)).

### CODE REVIEW

**Comment by jaredpar** [comment]
Interesting. Most seem to be testing types in the DLR / CSharp dynamic binder code which effectively we own. Looks like a handful of other types hit this but it is more common than I would've expected.

**Comment by danmoseley** [comment]
Can we just fix the casing? I assume they're all internal and we wouldn't write new code this way. Unless you want to dog food your warning.

**Comment by jcouv** [comment]
> Can we just fix the casing?

That's an option too, but is a bit more work. So you tell me what you'd like ;-)
How about upper-casing the ones in the product code, but leaving the tests merely escaped?

**Comment by danmoseley** [comment]
I'd prefer to upper case them all, but if that's a hassle this change is OK to me.

**Comment by jcouv** [comment]
Thanks for letting me know. I'll take a stab.

**Comment by jcouv** [comment]
How should `rtmsg`, `nlmsgerr` and `nlmsghdr` be capitalized?

**Comment by stephentoub** [comment]
> How should rtmsg, nlmsgerr and nlmsghdr be capitalized?

I'd prefer to leave these lower-cased.  We have a policy that types/functions declared in C# for interop should mirror the native naming, as if we were able to simply reference a .h file.  On Unix, that invariably means lower-cased names.

**Comment by jcouv** [comment]
Then `hostent`, `cgroups`, `procfs` should be left lower-cased too?

**Comment by stephentoub** [comment]
> Then hostent, cgroups, procfs should be left lower-cased too?

Similarly my preference is for those to remain lower-cased as well.

**Review by danmoseley — APPROVED** [review]
Thanks

**Comment by kasperk81** [comment]
merged with libraries builds failing, affecting everyone else

**Pull request merged**
