### PR TITLE
Fix Hosting tests in runtime-staging runs

### PR DESCRIPTION
**Pull request by eerhardt**
- Fix HostFactoryResolverTests to work with EnableAggressiveTrimming
- Disable new hosting tests on Windows running on mono

cc @radical @lewing

### CODE REVIEW

**Review by lewing — APPROVED** [review]
This should fix the test.  Is there a reason you went with attributes over a descriptor?

**Comment by eerhardt** [comment]
> Is there a reason you went with attributes over a descriptor?

In these cases, it makes more sense for the test to declare what it is depending on.

Using the attributes better documents why something is needed to be preserved. For example, if a test would get removed, who would know to go update the descriptor?

**Comment by lewing** [comment]
@radical see the failure here

**Comment by lewing** [comment]
AOT hitting https://github.com/dotnet/runtime/issues/52029

**Pull request merged**
