### PR TITLE
Changing compression level validation to allow any valid value

### PR DESCRIPTION
**Pull request by davemanton**
Compression level was validating to restrict to values represented in the compression level enum

However there are other values which are appropriate and users may want to use

This PR enables the usage of any compression level lieing between the defined minimum and maximum and throws the existing exception if the value set sits outside the valid range

### CODE REVIEW

**Comment by davemanton** [comment]
@dotnet-policy-service agree

**Comment by stephentoub** [comment]
Thank you, but this validation is by design:
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/brotlistream-ctor
There are open issues I hope will be addressed in .NET 9 to add more knobs here, but in the meantime you can use BrotliEncoder directly.

**Comment by davemanton** [comment]
@stephentoub

Thank you for providing the documentation.  Respectfully, I believe this PR is inline with the expectations of the design

The documentation suggests that allowing an arbitrary level to the underlying library could result in inconsistent and unexpected behaviour, this PR is designed to avoid that and allow values within a defined valid range

For us this is a blocker to progressing to dotnet 8 because we've chosen a valid compression level - 5 which for us provides the correct trade off between speed and payload size.  A larger payload would affect our mobile users experience and payload is something we pay close attention to

We are a very large e-commerce retailer in the UK but for us writing our own custom compression middleware isn't something I want our devs to get involved with when they don't have knowledge or experience of that area.  The existing middleware is great, I don't really understand why we can't pass it a valid (not arbitrary) value

As a listed company we try to avoid versions of dotnet which aren't LTS, so you're effectively asking us to wait 2 years to get our payload size back to where it should be, or write an encoder middleware when there's a perfectly good one available and we're not really qualified to do it

**Comment by stephentoub** [comment]
Thanks, I understand the concerns. Ideally the bug fix around validation would have happened at the same time as adding additional ctors, but alas, they were split from each other, one happened, one didn't. cc: @jeffhandley 

If level 4 instead of 5 would meet your needs, you can choose Optimal. Or you can write a custom Stream for when you need this specific encoding level.

The problem with allowing arbitrary values through isn't about the min/max but about the numbers not always meaning what the caller thinks they might mean, eg if you pass 0, you don't get level 0, if you pass 3 you don't get 3, etc. This ctor works in terms of a specific mapping; that at one point it accidentally interpreted the input differently was a bug and one we don't want to reintroduce.

I'm not arguing there isn't a need for additional support here, I agree there is, just that this ctor is not the answer.

**Comment by davemanton** [comment]
I remember reading the issue at the time when we chose our level and we ran foul of optimal not meaning optimal when the Quality_Default was set at maximum compression - https://github.com/dotnet/runtime/issues/26097

The changes that have been made since then much better describe optimal and meet the requirements of the enum describing min/max and fastest through applicable values

Please could you clarify why an integer value doesn't give you the level you're asking for on a sliding scale?  I appreciate this is a lack of knowledge on my part but I'm unclear why that would be the case

**Comment by stephentoub** [comment]
> Please could you clarify why an integer value doesn't give you the level you're asking for on a sliding scale? I appreciate this is a lack of knowledge on my part but I'm unclear why that would be the case

If it actually took an int, it'd be fine, and that's what a future ctor would accept. But it doesn't, it accepts a CompressionLevel, which the implementation then interprets and maps to an integer value. There's no way for the implementation to distinguish, for example, between `CompressionLevel.SmallestSize` and `(CompressionLevel)3`; at the IL level, those are identical. And as such, if you specify 3, you actually get 11, because that's what SmallestSize maps to.

**Comment by davemanton** [comment]
Okay, understood because of the CompressionLevel enum having those values predefined and therefore it getting mapped there even when you pass through an integer

I think to be fair to most users who set an integer value themselves they're probably going to experiment and realise there's a problem.  Removing the ability to set an arbitrary value to stop 0-3 from used incorrectly when there's the majority of the scale left is a bit much

I understand that Microsoft doesn't necessarily want the issues raising that it doesn't do what's expected with an integer level, but not using the enum is not using it as described so a user shouldn't expect it to be an exact correlation and the enum is easy enough to view to understand why

Blocking this functionality effectively for 2 years is really bad for users like us.  If you count from dotnet 7 -> the next LTS at dotnet 10, it's 3 years.  Surely we're better off allowing users to put in a valid value provided it falls within the correct range rather than stopping them having the compression level they want/need for so long

**Comment by davemanton** [comment]
@stephentoub 

I'd like to offer an alternative through this PR which enables an integer specific constructor https://github.com/dotnet/runtime/pull/95467

This way I can use this to create a compression provider which more closely matches the original brotli provider without needing a lot of knowledge of compression - https://github.com/dotnet/aspnetcore/blob/474d2944dba601440987b328d7044155023c3c14/src/Middleware/ResponseCompression/src/BrotliCompressionProvider.cs

**Comment by stephentoub** [comment]
> an integer specific constructor #95467
> 
> This way I can use this to create a compression provider which more closely matches the original brotli provider without needing a lot of knowledge of compression - https://github.com/dotnet/aspnetcore/blob/474d2944dba601440987b328d7044155023c3c14/src/Middleware/ResponseCompression/src/BrotliCompressionProvider.cs

Thanks. That is the planned approach:
https://github.com/dotnet/runtime/issues/42820
The actual shape of the APIs still needs to be agreed upon before we can accept a PR for it.

**Comment by davemanton** [comment]
No problem, thanks for your help today

**Pull request closed without merging**
