### PR TITLE
Fix physical promotion scenario name and a couple of bugs

### LINKED ISSUE #85403: [jitstress] Assertion failed 'replacements[firstIndex].Overlaps(offs, size)' during 'Physical promotion'
Widespread failures in jitstress.

Example: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85343-merge-11de8e74407345efb8/System.Text.RegularExpressions.Unit.Tests/1/console.d7f7f30f.log?helixlogtype=result

```scala
Assert failure(PID 2344 [0x00000928], Thread: 3780 [0x0ec4]): Assertion failed 'replacements[firstIndex].Overlaps(offs, size)' in 'System.Text.RegularExpressions.RegexParser:.ctor(System.String,int,System.Globalization.CultureInfo,System.Collections.Hashtable,int,System.Collections.Hashtable,System.Span`1[int]):this' during 'Physical promotion' (IL size 157; hash 0x855eb51e; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\promotion.cpp Line: 1317
    Image: C:\h\w\A7A6097A\p\dotnet.exe
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
This was renamed but I forgot to update these occurrences. The result is that runtime-jit-experimental is not actually running with physical promotion enabled (but the stress jobs do).

cc @dotnet/jit-contrib PTAL @AndyAyersMS 

Fix #85403

### CODE REVIEW

**Review by BruceForstall — APPROVED** [review]
Seems like testenvironment.proj should loudly fail if the scenario name isn't found

**Review by tannergooding — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
> Seems like testenvironment.proj should loudly fail if the scenario name isn't found

One possible solution for this would be to change `testenvironment.proj` to use pre-written .env files instead of generating environment scripts on the fly. That way we'd be able to be able to easily tell when a scenario isn't known as there wouldn't be a file on disk for the scenario.

**Comment by jakobbotsch** [comment]
Failures look known according to build analysis.

**Comment by jakobbotsch** [comment]
runtime-jit-experimental and recent jitstress runs seem to be hitting some problems I fixed in #85323, so I I ported a couple of fixes from there to this PR.

**Comment by jakobbotsch** [comment]
The remaining stress failures should have been fixed with #85396, but not sure what is going on with the OSX runs.

**Comment by MichalPetryka** [comment]
> but not sure what is going on with the OSX runs.

OSX runner seems to be having issues right now, it timed out on my PR.

**Review by BruceForstall — APPROVED** [review]

**Comment by jakobbotsch** [comment]
It looks like there's still some libraries-jitstress failures; opened #85426 for it (doesn't look related to physical promotion).

**Pull request merged**
