### PR TITLE
Disable win-arm64 runtime tests on PRs for CoreCLR

### PR DESCRIPTION
**Pull request by hoyosjs**
See https://github.com/dotnet/runtime/issues/68626

Disable tests in PR builds for CoreCLR windows arm64 while we have decreased capacity.

### CODE REVIEW

**Review by agocke — APPROVED** [review]
LGTM

**Comment by agocke** [comment]
Is this ready to go? I think we're clear to merge.

**Comment by hoyosjs** [comment]
cc: @dotnet/jit-contrib and @dotnet/crossgen-contrib as this disproportionately affects y'alls workflows.

**Comment by BruceForstall** [comment]
Just to be clear since it's not clear from the PR title: it's not just PRs; win-arm64 testing has been disabled for many JIT, GC, and R2R "outerloop" pipelines.

**Pull request merged**
