### PR TITLE
[mono][aot] Emit native-to-managed wrappers for [UnmanagedCallersOnly…

### PR DESCRIPTION
**Pull request by vargaz**
…] methods in non-full aot mode as well.

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
Is there an issue that this is fixing?  Seems like the sort of thing a customer would have hit.  Maybe someone on Android?

If it's customer-reported we should backport to net7

**Comment by vargaz** [comment]
@lateralusX

**Comment by lewing** [comment]
I assume it is part of https://github.com/dotnet/runtime/issues/79377 ?

**Comment by vargaz** [comment]
Yes, its needed to export UnmanagedCallersOnly methods from the aot image even in normal aot mode.
@lateralusX

**Comment by lewing** [comment]
The failure looks like it is a test for invalid il around unmanaged callers

**Comment by lateralusX** [comment]
There is also this failure:

 Mono Ahead of Time compiler - compiling assembly /__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest/InvalidCSharp.dll
  AOTID 23051251-E77F-2E41-2CE8-99B43CD56EDD
  * Assertion at /__w/1/s/src/mono/mono/mini/aot-compiler.c:5269, condition `is_ok (error)' not met, function:add_native_to_managed_wrappers, method InvalidCSharp.Callbacks:CallbackMethodGeneric<T> (T) with UnmanagedCallersOnlyAttribute is generic assembly:<unknown assembly> type:<unknown type> member:(null)

**Comment by lateralusX** [comment]
> Yes, its needed to export UnmanagedCallersOnly methods from the aot image even in normal aot mode. @lateralusX

Yes, we would like to run Android library build in same way as we run XA (hybrid AOT mode), but since unmanagedcallersonly attribute will be exported out of shared library as native methods, we need to generate native->managed wrappers and don't want to be force using full AOT.

**Comment by vargaz** [comment]
The failure is:
```
2023-01-23T10:51:55.7797188Z   AOT restriction: Method 'InvalidCSharp.Callbacks:CallbackNonStatic (int)' must be static since it is decorated with [UnmanagedCallers].
2023-01-23T10:51:55.7817897Z   Unable to generate native entry point 'int InvalidCSharp.Callbacks:CallbackMethodGeneric<T> (T)' due to 'method InvalidCSharp.Callbacks:CallbackMethodGeneric<T> (T) with UnmanagedCallersOnlyAttribute is generic assembly:<unknown assembly> type:<unknown type> member:(null)'.
2023-01-23T10:51:55.7868196Z /__w/1/s/src/mono/msbuild/aot-compile.proj(19,9): error MSB3073: The command "/__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Tests/Core_Root/corerun /__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest/InvalidCSharp.dll" exited with code 1.
```

**Comment by lateralusX** [comment]
> The failure is:
> 
> ```
> 2023-01-23T10:51:55.7797188Z   AOT restriction: Method 'InvalidCSharp.Callbacks:CallbackNonStatic (int)' must be static since it is decorated with [UnmanagedCallers].
> 2023-01-23T10:51:55.7817897Z   Unable to generate native entry point 'int InvalidCSharp.Callbacks:CallbackMethodGeneric<T> (T)' due to 'method InvalidCSharp.Callbacks:CallbackMethodGeneric<T> (T) with UnmanagedCallersOnlyAttribute is generic assembly:<unknown assembly> type:<unknown type> member:(null)'.
> 2023-01-23T10:51:55.7868196Z /__w/1/s/src/mono/msbuild/aot-compile.proj(19,9): error MSB3073: The command "/__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Tests/Core_Root/corerun /__w/1/s/artifacts/tests/coreclr/linux.x64.Release/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest/InvalidCSharp.dll" exited with code 1.
> ```

Should we not be as strict if we are not running full AOT and generate the wrappers? In that mode these wrappers can still be generated by JIT at runtime.

**Comment by vargaz** [comment]
Changed that error to a warning in non-full-aot mode.

**Comment by lateralusX** [comment]
@vargaz Are failures related or is this ready to get merged?

**Comment by vargaz** [comment]
Some failures still appear related.

**Comment by vargaz** [comment]
So it looks like in AOT mode, pinvokes which are not resolvable cause the app to abort (in mono_resolve_patch_target ()), which causes these tests to fail.

**Comment by lateralusX** [comment]
> So it looks like in AOT mode, pinvokes which are not resolvable cause the app to abort (in mono_resolve_patch_target ()), which causes these tests to fail.

Seems to related to the resolver functionality when loading native libraries, do we end up with a native->managed wrapper for that as well, https://github.com/dotnet/runtime/blob/7d1191e32208702899eec55aa622b6aff99986e1/src/tests/Interop/NativeLibrary/Callback/CallbackStressTest.cs#L44 ?

**Comment by vargaz** [comment]
Those were caused by a bug in the PR, we were adding managed-to-native wrappers as well by mistake.

**Review by lateralusX — APPROVED** [review]
LGTM!

**Pull request merged**
