### PR TITLE
Simple GT_NEG optimization for #13837

### LINKED ISSUE #13837: JIT: Optimize simple arithmetic with GT_NEG
I was surprised it's not handled in `morph`, e.g. `-a + b` => `b - a`.
```csharp
int M1(int a, int b) => -a +  b; // optimize to  "b - a"
int M2(int a, int b) =>  a + -b; // optimize to  "a - b"
int M3(int a, int b) =>  a - -b; // optimize to  "a + b"
int M4(int a, int b) => -a - -b; // optimize to  "b - a"
```
Current codegen:
```asm
; Method CC:M1(int,int):int:this
G_M48868_IG02:
       mov      eax, edx
       neg      eax
       add      eax, r8d

; Method CC:M2(int,int):int:this
G_M15271_IG02:
       mov      eax, r8d
       neg      eax
       add      eax, edx

; Method CC:M3(int,int):int:this
G_M13857_IG02:
       mov      eax, r8d
       neg      eax
       sub      edx, eax
       mov      eax, edx

; Method CC:M4(int,int):int:this
G_M28384_IG02:
       mov      eax, edx
       neg      eax
       mov      edx, r8d
       neg      edx
       sub      eax, edx
```
Expected codegen: https://godbolt.org/z/nmZxv8

Also:
```csharp

int M5(int a) =>  -a / 10;  // optimize to  "a / -10"
int M6(int a) => -(a / 10); // optimize to  "a / -10"
int M7(int a) =>  -a * 10;  // optimize to  "a * -10"
int M8(int a) => -(a * 10); // optimize to  "a * -10"
```

category:cq
theme:basic-cq
skill-level:beginner
cost:small

### PR DESCRIPTION
**Pull request by JulieLeeMSFT**
Fixes #13837

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43148) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43148) before we can accept your contribution.<br/><br/>:x: JulieLeeMSFT [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43148)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=43148) it.</sub>

**Comment by AndyAyersMS** [comment]
@JulieLeeMSFT there are some test failures here, eg
```
;; JIT\Regression\JitBlue\DevDiv_545500

Assertion failed 'vnWx != NoVN' in 'DevDiv_545500:Test(float,int,long):ubyte' 
   during 'Optimize Valnum CSEs' (IL size 174)
```
Also it's customary to either run `jit-diff` to show this pattern is firing in code that we regularly test and/or add new test cases.

**Comment by EgorBo** [comment]
I guess `!optValnumCSE_phase` should help or maybe
`SetOper(oper)` -> `SetOper(oper, GenTree::PRESERVE_VN)` since `SetOper` clears VN by default.

**Comment by JulieLeeMSFT** [comment]
Replaced by #43921

**Comment by JulieLeeMSFT** [comment]
> @JulieLeeMSFT there are some test failures here, eg
> 
> ```
> ;; JIT\Regression\JitBlue\DevDiv_545500
> 
> Assertion failed 'vnWx != NoVN' in 'DevDiv_545500:Test(float,int,long):ubyte' 
>    during 'Optimize Valnum CSEs' (IL size 174)
> ```
> 
> Also it's customary to either run `jit-diff` to show this pattern is firing in code that we regularly test and/or add new test cases.

Will check if there still exists assertion with the fix in #43921.

**Pull request closed without merging**
