### PR TITLE
Reduce binary size by moving data definitions out of headers.

### PR DESCRIPTION
**Pull request by AustinWise**
Contributes to #39599

### CODE REVIEW

**Comment by AustinWise** [comment]
On Windows X64 release, this reduces coreclr.dll by 186kb and clrjit by 10kb.

**Comment by jkotas** [comment]
@janvorli Is there anything left in this change that you have not addressed already?

**Comment by AustinWise** [comment]
@jkotas It looks like @janvorli got almost everything. The only remaining item is `-constexpr mdToken g_tkCorEncodeToken[4] ={mdtTypeDef, mdtTypeRef, mdtTypeSpec, mdtBaseType};` in `cor.h`. The other thing my change does is move the `DbgIPCEventTypeNames` array to a .cpp file. @janvorli said he attempted this and it was "ugly and problematic". Perhaps there is something I'm overlooking in my solution.

The `g_tkCorEncodeToken` change contributes a tiny amount of size reduction (something like less than 1kb). So at this point this PR is more about the esthetics of moving the `const` data to a .cpp file. Given that `DbgIPCEventTypeNames` was the vast majority of the size regression, it may be worthwhile to move it.

I have rebased.

**Comment by janvorli** [comment]
Great, I have missed the fact that we already have a shared .cpp file between the debug/ee and debug/di, using the trick of #including a .cpp file to solve the problem.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by k15tfu** [comment]
Hi! We use some subset of coreclr headers for Profiling API decls (discussed here https://github.com/dotnet/runtime/issues/11397), but after moving `g_tkCorEncodeToken` to .cpp we get undefined references when using `CorSigCompressToken`.

Are there any other options to keep cor.h independent of other internals? @janvorli @jkotas

I checked that this way works fine and that symbols didn't get duplicated on Linux:
```
FORCEINLINE const mdToken (&g_tkCorEncodeTokenFn())[4] {
    static const mdToken g_tkCorEncodeToken[4] = {mdtTypeDef, mdtTypeRef, mdtTypeSpec, mdtBaseType};
    return g_tkCorEncodeToken;
}
```

**Pull request merged**
