### PR TITLE
Reenable SocketsHttpHandlerTest_Http3_MsQuic.ClientSettingsReceived_Success test

### PR DESCRIPTION
**Pull request by rzikm**
Test if the test passes on CI

### CODE REVIEW

**Comment by ManickaP** [comment]
Make sure it runs and is not skipped.
Also you can run the test locally in a tight loop to try to get it failed, @wfurt has been doing that a lot to reproduce the failures locally.

**Comment by rzikm** [comment]
I have run this test few hundred times in a loop on a VM similar to what is used on the CI and observed no failures of this test.

**Comment by rzikm** [comment]
CI Failure is https://github.com/dotnet/runtime/issues/67712

**Review by ManickaP — APPROVED** [review]
If it passes then LGTM, thanks!

**Pull request merged**
