### PR TITLE
Use Utf8.IsValid to optimize ManagedWebSocket.TryValidateUtf8

### PR DESCRIPTION
**Pull request by stephentoub**
| Method      | Mean        |
|------------ |------------:|
| Existing    | 1,279.55 ns |
| Utf8IsValid |    65.23 ns |

```C#
private Utf8MessageState _state = new();
private byte[] _utf8Data = """
    Shall I compare thee to a summer’s day?
    Thou art more lovely and more temperate:
    Rough winds do shake the darling buds of May,
    And summer’s lease hath all too short a date:
    Sometime too hot the eye of heaven shines,
    And often is his gold complexion dimm’d;
    And every fair from fair sometime declines,
    By chance or nature’s changing course untrimm’d;
    But thy eternal summer shall not fade
    Nor lose possession of that fair thou owest;
    Nor shall Death brag thou wander’st in his shade,
    When in eternal lines to time thou growest:
    So long as men can breathe or eyes can see,
    So long lives this and this gives life to thee.
    """u8.ToArray();

[Benchmark]
public bool Existing() => TryValidateUtf8(_utf8Data, true, _state);

[Benchmark]
public bool Utf8IsValid() => Utf8.IsValid(_utf8Data);
```

### CODE REVIEW

**Comment by EgorBo** [comment]
Does such a big difference imply that the currently used algorithm is suboptimal? (for non-complete data)

**Comment by stephentoub** [comment]
> Does such a big difference imply that the currently used algorithm is suboptimal? (for non-complete data)

There's no vectorization or ASCII fast path, but rather multiple operations per byte.

**Review by CarnaViire — COMMENTED** [review]
LGTM, thanks!

But it seems like we (historically) don't have any tests for this method (because they were left in https://github.com/aspnet/WebSockets/blob/aa63e27fce2e9202698053620679a9a1059b501e/test/Microsoft.AspNetCore.WebSockets.Protocol.Test/Utf8ValidationTests.cs)

Can you please bring them in? And see if they also cover the changed (ascii skip) part? Thanks!

**Comment by stephentoub** [comment]
> Can you please bring them in? And see if they also cover the changed (ascii skip) part? Thanks!

Done. Thanks.

**Review by CarnaViire — APPROVED** [review]
:shipit:

**Pull request merged**
