### PR TITLE
Backport workload changes from rc1

### PR DESCRIPTION
**Pull request by lewing**
I think I got all the non version related changes but review is welcome

### CODE REVIEW

**Comment by hoyosjs** [comment]
The branch should be automatically mirrored, doing this might end up with conflicts.

**Comment by lewing** [comment]
> The branch should be automatically mirrored, doing this might end up with conflicts.

I haven't seen a mirror run recently?

**Comment by hoyosjs** [comment]
Yeah, I raised in FR - the rest call is failing with auth issues

**Review by radical — APPROVED** [review]
Approved, assuming the tests pass.

**Comment by lewing** [comment]
> Yeah, I raised in FR - the rest call is failing with auth issues

happy to wait a bit for that to resolve

**Comment by lewing** [comment]
bot got its auth fixed https://github.com/dotnet/runtime/pull/74539 and this doesn't include the installer changes

**Comment by carlossanlop** [comment]
> bot got its auth fixed #74539 and this doesn't include the installer changes

Which installer changes?

**Pull request closed without merging**
