### PR TITLE
Fix g_TrapReturningThreads to be accessed as 32-bit in asm and JIT code on arm64

### LINKED ISSUE #39054: load/store memory unaligned for type LONG and type long
### Description

runtime/src/coreclr/src/pal/inc/pal_mstypes.h        Line:241
<pre>
typedef int LONG;       // NOTE: diff from windows.h, for LP64 compat 
typedef unsigned int ULONG; // NOTE: diff from windows.h, for LP64 compat
</pre>
Why defining LONG as int ?

runtime/src/coreclr/src/vm/vars.cpp     Line:31
<pre>
Volatile < LONG >       g_TrapReturningThreads;               <-------------here is int
</pre>

runtime/src/coreclr/src/vm/arm64/asmhelpers.S
<pre>
 777     PREPARE_EXTERNAL_VAR g_TrapReturningThreads, x2
 778     ldr x3, [x2]                                <---------------------here loading is long, the addr is not aligned
</pre>

runtime/src/coreclr/src/vm/amd64/pinvokestubs.S
<pre>
200         // Check return trap
201         PREPARE_EXTERNAL_VAR g_TrapReturningThreads, rax
202         cmp             dword ptr [rax], 0                               <---------------------here loading is long, the addr is not aligned
</pre>

while in the JIT comiler loading the g_TrapReturningThreads is also unaligned.
The JIT see it as long type.

for example, mips64-CoreCLR
<pre>
   0xff7c8df5a8:    lui a0,0xff
   0xff7c8df5ac:    ori a0,a0,0xf7a0
   0xff7c8df5b0:    dsll    a0,a0,0x10
   0xff7c8df5b4:    ori a0,a0,0xeb7c           <-------this is not 8-byte aligned.
=> 0xff7c8df5b8:    ld  a0,0(a0)
</pre>

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #39054

### CODE REVIEW

**Comment by jkotas** [comment]
cc @shushanhf

**Review by sandreenko — APPROVED** [review]
LGTM

**Comment by jkotas** [comment]
@dotnet/jit-contrib Is `python.exe' failed with exit code 4294967295` a known problem with the formatting job on Windows?

**Comment by sandreenko** [comment]
> @dotnet/jit-contrib Is python.exe' failed with exit code 4294967295 a known problem with the formatting job on Windows?

The actual error seems to be:
```
Downloading formatting tools
Invoke-WebRequest : Unable to read data from the transport connection: An existing connection was forcibly closed by 
the remote host.
At line:1 char:1
+ Invoke-WebRequest -Uri https://clrjit.blob.core.windows.net/clang-too ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 
ERROR: failed to download clang-tidy.
```
so probably it is network noise.

**Pull request merged**
