### PR TITLE
[workloads] Work around main still targeting net7.0

### PR DESCRIPTION
**Pull request by lewing**
Until we can target net8 properly use the local runtime build for net7 in addition to net8

### CODE REVIEW

**Review by jeffhandley — APPROVED** [review]
Thanks for putting this workaround in place.

**Review by radekdoulik — APPROVED** [review]

**Comment by lewing** [comment]
unfortunately @radical writes exhaustive tests, I'll have to do this slightly differently

**Review by radical — APPROVED** [review]

**Comment by lewing** [comment]
failures are the finalization breakage

**Pull request merged**
