### PR TITLE
Optimize JIT_ClassProfile32

### PR DESCRIPTION
**Pull request by EgorBo**
I'm still seeing `JIT_ClassProfile32` being top5 hottest functions in the TE traces + was surprised to see it for Paint.NET's traces (forced to stay in tier0-instrumented). 

image

#### New codegen:

image

This PR does:
1) optimizes `classProfile->Count++` operation. `volatile` seems unnecessary here
2) force inline `CheckSample` into `JIT_ClassProfile32`
3) Little massage to produce better codegen on MSVC (other compilers do a better job as is)
4) Replaces `pMT->GetLoaderAllocator()->IsCollectible()` with `pMT->Collectible()`

(mostly written by @jakobbotsch)

### Open questions
1) It seems like we need to collect Native PGO with `DOTNET_TieredPGO=1` to produce a better NPGO coverage.

### CODE REVIEW

**Review by jakobbotsch — APPROVED** [review]
LGTM! BTW, when I looked at it the `FORCEINLINE` was not required for MSVC to inline `CheckSample`, but still seems fine to me to have it given that we know it's very hot.

Would also like to know what the intention of the volatile increment was since that is being removed (cc @AndyAyersMS)

**Comment by AndyAyersMS** [comment]
We might also look at implementing something closer to the true reservoir sampling via `if ((x % count) >= S)` or if you don't want that unknown value modulus, at least decreasing the probability of an update once `count` is large.

> Would also like to know what the intention of the volatile increment was since that is being removed (cc @AndyAyersMS)

Doesn't look like it is needed. I don't remember why I had it that way.

**Comment by EgorBo** [comment]
> @EgorBo did you collect any data for this one?

I did, the improvement was quite small, I assume, mostly because the main issue is in `classProfile->Count++` cache contention

**Comment by EgorBo** [comment]
Failure is https://github.com/dotnet/runtime/issues/82275

**Pull request merged**
