### PR TITLE
Enable parallel test execution for QUIC and HTTP/3 and enable some disabled http3 tests

### LINKED ISSUE #56000: [HTTP/3] SendStreamLimitRequestsConcurrently_Succeeds times out
```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.SendStreamLimitRequestsConcurrently_Succeeds(streamLimit: 10) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(49,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(163,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendStreamLimitRequestsConcurrently_Succeeds(Int32 streamLimit)
        --- End of stack trace from previous location ---
```
log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54845-merge-b3a250ac333f4a61ad/System.Net.Http.Functional.Tests/console.fb7bf6d4.log?sv=2019-07-07&se=2021-08-09T14%3A21%3A02Z&sr=c&sp=rl&sig=CXj3eKgQpJ%2B6oxAsRdMe0xpZUHxHXuGHya1lGnOEa7s%3D
build: https://dev.azure.com/dnceng/public/_build/results?buildId=1246649&view=logs&j=d883cc86-ff08-5389-6fca-0d01451458f6&t=5fca1690-df52-529b-9100-c473a9350efd&l=151

Failures 5/20-7/20 (incl. PRs):

Day | Failures
-- | --
7/19 | 2x Official run (1x Mock) + 8x PR
7/20 | 2x Official run + 17x PR (2x Mock)

### LINKED ISSUE #91017: Retry Counts are high in Http3 Tests
There are Http3 tests that pass on retries.

Some test examples are:
- System.Net.Http.Functional.Tests.HttpMetricsTest_Http30.RequestDuration_EnrichmentHandler_Success_Recorded
- System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerSendsTrailingHeaders_Success
- System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http3.RequestSent_HandlerDisposed_RequestIsUnaffected

### LINKED ISSUE #101015: System.Net.Http.Functional.Tests.HttpClientHandler_MaxResponseHeadersLength_Test.SetAfterUse_Throws fails
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=642123
Build error leg or test failing: Build / Libraries Test Run release coreclr windows x64 Debug / Send to Helix
Pull request: https://github.com/dotnet/runtime.git/pull/101007

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "ClientHandler_MaxResponseHeadersLength_(?:Test|Http3)",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=642123
**Error message validated:** `[ClientHandler_MaxResponseHeadersLength_(?:Test|Http3)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/16/2024 11:17:09 AM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[695292](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695292)|dotnet/runtime|Send to Helix|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/695292/logs/909)|dotnet/runtime#102699|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[688895](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688895)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688895&view=ms.vss-test-web.build-test-results-tab&runId=17113138&resultId=219023)|dotnet/runtime#102699|
|[687577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687577)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687577&view=ms.vss-test-web.build-test-results-tab&runId=17073526&resultId=220449)|dotnet/runtime#100951|
|[682021](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682021)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocksProxyTest_Http2.TestLoopbackAsync](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682021&view=ms.vss-test-web.build-test-results-tab&runId=16931180&resultId=213392)||
|[681987](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681987)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Http11_Cancellation_Test.GetAsync_CancelDuringResponseHeadersReceived_TaskCanceledQuickly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681987&view=ms.vss-test-web.build-test-results-tab&runId=16928002&resultId=213537)||
|[681186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681186)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681186&view=ms.vss-test-web.build-test-results-tab&runId=16905374&resultId=216284)|dotnet/runtime#100951|
|[679966](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679966)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocksProxyTest_Http2.TestLoopbackAsync](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679966&view=ms.vss-test-web.build-test-results-tab&runId=16862634&resultId=213752)||
|[679420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679420)|dotnet/runtime|[System.Net.Http.Functional.Tests.Http1MultiChunkResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679420&view=ms.vss-test-web.build-test-results-tab&runId=16846488&resultId=212322)||
|[678355](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678355)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocksProxyTest_Http1_Async.TestLoopbackAsync](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678355&view=ms.vss-test-web.build-test-results-tab&runId=16816166&resultId=209929)||
|[675315](https://dev.azure.com/dnceng-public/public/_build/results?buildId=675315)|dotnet/runtime|[System.Net.Http.Functional.Tests.Http1MultiChunkResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=675315&view=ms.vss-test-web.build-test-results-tab&runId=16743704&resultId=219556)|dotnet/runtime#102181|
|[667272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=667272)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=667272&view=ms.vss-test-web.build-test-results-tab&runId=16551250&resultId=217017)|dotnet/runtime#101939|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|11|

### LINKED ISSUE #101376: [Test Failure] SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=649077
Build error leg or test failing: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success
Pull request: https://github.com/dotnet/runtime/pull/101250

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.AltSvc.cs(130,0): at System.Net.Http.Functional.Tests.HttpClientHandler_AltSvc_Test.AltSvc_Upgrade_Success(GenericLoopbackServer firstServer, Http3LoopbackServer secondServer, HttpClient client)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.AltSvc.cs(96,0): at System.Net.Http.Functional.Tests.HttpClientHandler_AltSvc_Test.AltSvc_ConnectionFrame_UpgradeFrom20_Success()
        --- End of stack trace from previous location ---
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream(chunked: null, enableWasmStreaming: False, slowChunks: False) [FAIL]
      System.Net.Http.HttpRequestException : An error occurred while sending the request.
      ---- System.Net.Quic.QuicException : The connection timed out from inactivity.
      Stack Trace:
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(310,0): at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(324,0): at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs(236,0): at System.Net.Http.Http3Connection.SendAsync(HttpRequestMessage request, Int64 queueStartingTimestamp, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs(250,0): at System.Net.Http.Http3Connection.SendAsync(HttpRequestMessage request, Int64 queueStartingTimestamp, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.Http3.cs(87,0): at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.cs(430,0): at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(30,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs(1027,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass28_0.<<ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs(44,0): at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass6_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackServer.cs(116,0): at System.Net.Test.Common.Http3LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout, GenericLoopbackOptions options)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs(1013,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream(Nullable`1 chunked, Boolean enableWasmStreaming, Boolean slowChunks)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(177,0): at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(237,0): at System.Net.Quic.ResettableValueTaskSource.TrySetException(Exception exception, Boolean final)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(640,0): at System.Net.Quic.QuicStream.HandleEventShutdownComplete(_SHUTDOWN_COMPLETE_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(663,0): at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(692,0): at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* stream, Void* context, QUIC_STREAM_EVENT* streamEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(251,0): at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(333,0): at System.Net.Quic.QuicStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(803,0): at System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(339,0): at System.Net.Http.Http3RequestStream.ReadResponseAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(206,0): at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=649077
**Error message validated:** `[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success [FAIL]`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/22/2024 12:32:28 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[688006](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688006)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688006&view=ms.vss-test-web.build-test-results-tab&runId=17085834&resultId=220556)|dotnet/runtime#100951|
|[687577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687577)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687577&view=ms.vss-test-web.build-test-results-tab&runId=17073526&resultId=220449)|dotnet/runtime#100951|
|[687479](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687479)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687479&view=ms.vss-test-web.build-test-results-tab&runId=17070990&resultId=220556)|dotnet/runtime#100951|
|[687411](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687411)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687411&view=ms.vss-test-web.build-test-results-tab&runId=17066842&resultId=220556)|dotnet/runtime#100951|
|[681186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681186)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681186&view=ms.vss-test-web.build-test-results-tab&runId=16905416&resultId=219571)|dotnet/runtime#100951|
|[678721](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678721)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http3.SendAsync_Expires_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678721&view=ms.vss-test-web.build-test-results-tab&runId=16826568&resultId=218810)||
|[678603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678603)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678603&view=ms.vss-test-web.build-test-results-tab&runId=16824506&resultId=206582)|dotnet/runtime#102357|
|[678427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678427)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678427&view=ms.vss-test-web.build-test-results-tab&runId=16820686&resultId=217954)|dotnet/runtime#102351|
|[674799](https://dev.azure.com/dnceng-public/public/_build/results?buildId=674799)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=674799&view=ms.vss-test-web.build-test-results-tab&runId=16730022&resultId=219034)|dotnet/runtime#100951|
|[674647](https://dev.azure.com/dnceng-public/public/_build/results?buildId=674647)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=674647&view=ms.vss-test-web.build-test-results-tab&runId=16724952&resultId=220316)|dotnet/runtime#100951|
|[666506](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666506)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666506&view=ms.vss-test-web.build-test-results-tab&runId=16533188&resultId=215755)|dotnet/runtime#100951|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|11|

### LINKED ISSUE #101377: [Test Failure] SocketsHttpHandlerTest_Cookies_Http3.GetAsync_SetCookieContainerAndCookieHeader_BothCookiesSent
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=649077
Build error leg or test failing: System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_SetCookieContainerAndCookieHeader_BothCookiesSent
Pull request: https://github.com/dotnet/runtime/pull/101250

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": [ "System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_SetCookieContainerAndCookieHeader_BothCookiesSent [FAIL]", "---- System.Net.Quic.QuicException : The connection timed out from inactivity." ],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_SetCookieContainerAndCookieHeader_BothCookiesSent [FAIL]
      System.Net.Http.HttpRequestException : An error occurred while sending the request.
      ---- System.Net.Quic.QuicException : The connection timed out from inactivity.
      Stack Trace:
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(310,0): at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(324,0): at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs(236,0): at System.Net.Http.Http3Connection.SendAsync(HttpRequestMessage request, Int64 queueStartingTimestamp, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs(250,0): at System.Net.Http.Http3Connection.SendAsync(HttpRequestMessage request, Int64 queueStartingTimestamp, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.Http3.cs(87,0): at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.cs(430,0): at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(30,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(530,0): at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(550,0): at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cookies.cs(235,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Cookies.<GetAsync_SetCookieContainerAndCookieHeader_BothCookiesSent>b__15_0(GenericLoopbackServer server, Uri url)
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackServer.cs(116,0): at System.Net.Test.Common.Http3LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout, GenericLoopbackOptions options)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cookies.cs(223,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Cookies.GetAsync_SetCookieContainerAndCookieHeader_BothCookiesSent()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(177,0): at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(237,0): at System.Net.Quic.ResettableValueTaskSource.TrySetException(Exception exception, Boolean final)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(640,0): at System.Net.Quic.QuicStream.HandleEventShutdownComplete(_SHUTDOWN_COMPLETE_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(663,0): at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(692,0): at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* stream, Void* context, QUIC_STREAM_EVENT* streamEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(251,0): at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(333,0): at System.Net.Quic.QuicStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(803,0): at System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(339,0): at System.Net.Http.Http3RequestStream.ReadResponseAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(206,0): at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=649077
**Error message validated:** `[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_SetCookieContainerAndCookieHeader_BothCookiesSent [FAIL] ---- System.Net.Quic.QuicException : The connection timed out from inactivity.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/24/2024 11:37:46 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[678685](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678685)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http3.SendAsync_Expires_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678685&view=ms.vss-test-web.build-test-results-tab&runId=16826066&resultId=218726)|dotnet/runtime#102362|
|[678603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678603)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678603&view=ms.vss-test-web.build-test-results-tab&runId=16824506&resultId=206582)|dotnet/runtime#102357|
|[678427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678427)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678427&view=ms.vss-test-web.build-test-results-tab&runId=16820686&resultId=217954)|dotnet/runtime#102351|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|3|

### PR DESCRIPTION
**Pull request by liveans**
Fixes #101377
Fixes #101376
Fixes #101015 
Fixes #91017 
Fixes #56000

As #102699 merged, we believe that we can re-enable some H/3 tests and parallel test execution, because root cause should've been fixed by that PR.

### CODE REVIEW

**Comment by ManickaP** [comment]
> Fixes #101015 Fixes #91017 Fixes #56000

I think you're missing some other issues as well. At least I see some deleted `if`s with `ActiveIssue` inside.

**Comment by liveans** [comment]
> > Fixes #101015 Fixes #91017 Fixes #56000
> 
> I think you're missing some other issues as well. At least I see some deleted `if`s with `ActiveIssue` inside.

I think we should keep #91757 open, because of ARM32 specific timeout problem which should be fixed by v2.4

**Review by ManickaP — APPROVED** [review]
:shipit: Thanks!

**Pull request merged**
