### PR TITLE
chore (Badge) : Add .NET foundation badge

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
1. Found the .NET foundation badge at https://img.shields.io/badge/.NET%20Foundation-blueviolet.svg
2. Add to badge collection.

### CODE REVIEW

**Comment by stephentoub** [comment]
What is the benefit of this change?  The rest of the badges are dynamic, showing up-to-date information; this is just a static image.

**Comment by ShreyasJejurkar** [comment]
Hi @stephentoub, Yes it's a static .NET foundation badge. Represents that the given project is part of the .NET foundation.

**Comment by stephentoub** [comment]
There's a whole section on the readme about .NET Foundation. We don't need an additional image for that in the badges section.  But thanks.

**Comment by ShreyasJejurkar** [comment]
Why I opened PR, because recently I found the same badge on some .NET foundation project (example https://github.com/reaqtive/reaqtor) which I did not saw on runtime repo, so I opened PR!

**Pull request closed without merging**
