### PR TITLE
Fix System.Net.Http build break

### PR DESCRIPTION
**Pull request by stephentoub**
https://github.com/dotnet/runtime/pull/34948 broke the build.  It conflicted with https://github.com/dotnet/runtime/pull/37619 which was merged yesterday.

cc: @ManickaP, @davidsh

### CODE REVIEW

**Comment by ManickaP** [comment]
I'm looking at it right now.

**Review by ManickaP — APPROVED** [review]
Thanks for the fix.

**Comment by davidsh** [comment]
>It conflicted with #37619 which was merged yesterday.

Sorry for the conflict. Thanks for fixing it so fast! :)

**Comment by stephentoub** [comment]
> Thanks for fixing it so fast! :)

Self-serving ;-)

**Pull request merged**
