### PR TITLE
Add catch for ConnectionAborted in Http3

### LINKED ISSUE #92359: ServerClosesConnection_ThrowsHttpProtocolException test failed with wrong exception type
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=413034
Build error leg or test failing: System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerClosesConnection_ThrowsHttpProtocolException
Pull request: https://github.com/dotnet/runtime/pull/92310

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "ServerClosesConnection_ThrowsHttpProtocolException",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
Failing Configuration
net9.0-windows-Debug-x64-CoreCLR_release-Windows.11.Amd64.Client.Open
Exception Message
Assert.IsType() Failure
Expected: System.Net.Http.HttpProtocolException
Actual:   System.Net.Quic.QuicException
CallStack
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.AssertProtocolErrorAsync(Int64 errorCode, Func`1 task) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 39
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass9_0.<<ServerClosesConnection_ThrowsHttpProtocolException>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 341
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 90
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerClosesConnection_ThrowsHttpProtocolException() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 344
--- End of stack trace from previous location ---
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=413034
**Error message validated:** `ServerClosesConnection_ThrowsHttpProtocolException`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/20/2023 5:28:50 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[428083](https://dev.azure.com/dnceng-public/public/_build/results?buildId=428083)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Http11_Cancellation_Test.GetAsync_CancelDuringResponseHeadersReceived_TaskCanceledQuickly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=428083&view=ms.vss-test-web.build-test-results-tab&runId=9443562&resultId=212671)|dotnet/runtime#92855|
|[418439](https://dev.azure.com/dnceng-public/public/_build/results?buildId=418439)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerClosesConnection_ThrowsHttpProtocolException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=418439&view=ms.vss-test-web.build-test-results-tab&runId=9178012&resultId=159917)||
|[418385](https://dev.azure.com/dnceng-public/public/_build/results?buildId=418385)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http30.RequestDuration_EnrichmentHandler_Success_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=418385&view=ms.vss-test-web.build-test-results-tab&runId=9175760&resultId=212733)||
|[415260](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415260)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415260&view=ms.vss-test-web.build-test-results-tab&runId=9072182&resultId=212926)||
|[415139](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415139)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendStreamLimitRequestsConcurrently_Succeeds](https://dev.azure.com/dnceng-public/public/_build/results?buildId=415139&view=ms.vss-test-web.build-test-results-tab&runId=9070110&resultId=212846)|dotnet/runtime#92187|
|[414357](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414357)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_RequestContentLengthMismatchTest_Http3.ContentLength_DoesNotMatchRequestContentLength_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414357&view=ms.vss-test-web.build-test-results-tab&runId=9046968&resultId=212367)|dotnet/runtime#92405|
|[414188](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414188)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerClosesConnection_ThrowsHttpProtocolException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=414188&view=ms.vss-test-web.build-test-results-tab&runId=9042158&resultId=205395)||
|[413034](https://dev.azure.com/dnceng-public/public/_build/results?buildId=413034)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendStreamLimitRequestsConcurrently_Succeeds](https://dev.azure.com/dnceng-public/public/_build/results?buildId=413034&view=ms.vss-test-web.build-test-results-tab&runId=9010912&resultId=212846)|dotnet/runtime#92310|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|8|

### PR DESCRIPTION
**Pull request by liveans**
It wasn't actually a race between, closing, etc. Since we're keeping the first exception in _abortException, we're returning that and in some cases, we weren't actually wrapping `ConnectionAbort` with `HttpProtocolException`, and it was resulting in throwing a `QuicException`.

Fixes #92359

### CODE REVIEW

**Comment by ManickaP** [comment]
> it feels like abort due to dispose and close was racing.

Could you expand on that a bit more so I can fully understand the sequence of events that could cause this?

**Comment by liveans** [comment]
> > it feels like abort due to dispose and close was racing.
> 
> Could you expand on that a bit more so I can fully understand the sequence of events that could cause this?

AFAIU, when we finished the task `Http3Connection` was disposing faster than before we sent `Close`, so it caused `QuicConnection` to dispose of, and disposing of `QuicConnection` was causing `connection aborted by peer`.

**Comment by ManickaP** [comment]
> Http3Connection was disposing faster than before we sent Close

CloseAsync is awaited, so we're waiting for the SHUTDOWN_COMPLETE event for the connection

> disposing of QuicConnection was causing connection aborted by peer.

Dispose won't do anything if close was already called, if not, it will do the same thing as CloseAsync called with default connection close error code. Also "connection aborted by peer" is what you will get when you call CloseAsync so that should be expected:
https://github.com/dotnet/runtime/blob/ffa4ef75ec135a64a30e14df5c2afca340ee1203/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs#L445-L451

So I think your premise is not correct and there's more to it.

**Review by ManickaP — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
