### PR TITLE
Add support for storing method handle histograms in profiles

### PR DESCRIPTION
**Pull request by jakobbotsch**
Allow method handle histograms in .mibc files and in the PGO text format.

Contributes to #44610.

@davidwrighton would this in theory need a R2R version bump? I suppose we can wait with such a bump until we actually start producing profiles with this data (at which point we should also add an equivalent of `GetLikelyClass`)?

cc @dotnet/jit-contrib

### CODE REVIEW

**Review by AndyAyersMS — COMMENTED** [review]
Jit and SPMI changes look good.

WIll defer to David or Michal for the remainder of the changes.

**Comment by BruceForstall** [comment]
Do you need to change the JIT-EE GUID?

**Comment by jakobbotsch** [comment]
> Do you need to change the JIT-EE GUID?

I have some follow-up changes that will actually start producing and using the new kind of PGO data. I think we can delay updating the JIT-EE GUID to that as just adding new PGO schema kinds should be binary compatible (and my future changes will probably also need another JIT-EE GUID update).

**Comment by davidwrighton** [comment]
@jakobbotsch Have you verified that with these changes the dotnet-pgo tool continues to work with .NET 6 runtimes?

**Comment by jakobbotsch** [comment]
> @jakobbotsch Yes, this requires a bump in the R2R minor version.

Is it ok to wait until future changes that actually start producing and consuming these? At that point I will add something similar to `GetLikelyClass` for methods which will require another R2R version bump.

> @jakobbotsch Have you verified that with these changes the dotnet-pgo tool continues to work with .NET 6 runtimes?

Yes, it produced a .mibc with the same hash as dotnet-pgo from current main in my test.

**Comment by davidwrighton** [comment]
When in doubt, bump the version. If there is no chance that new data could be produced, you don't need to, but bumping the R2R version is pretty cheap, and doesn't come with significant costs as old R2R code should not be broken.

**Comment by jakobbotsch** [comment]
@davidwrighton I've bumped the R2R minor version and also the JIT-EE GUID to be safe, please take another look.
I plan to wait with merging this until after the snap in any case.

**Comment by jakobbotsch** [comment]
ping @davidwrighton, anything else you think I should do here?

**Review by AndyAyersMS — APPROVED** [review]
Just looked at JIT / SPMI in depth.

**Comment by jakobbotsch** [comment]
Ping @davidwrighton, my follow-up depends on this one.

**Review by davidwrighton — APPROVED** [review]

**Pull request merged**
