### PR TITLE
Compile Microsoft.Extensions.HostFactoryResolver test file

### LINKED ISSUE #52118: [iOS][tvOS] Microsoft.Extensions.HostFactoryResolver.Tests No Test Cases Found on iOS tvOS
```
default	13:15:22.157862-0400	Microsoft.Extensions.HostFactoryResolver.Tests	No test cases discovered
info	13:15:22.168461-0400	Microsoft.Extensions.HostFactoryResolver.Tests	assembly_preload_hook: System.Xml.ReaderWriter  /Users/mdhwang/Library/Developer/CoreSimulator/Devices/71D00C72-A1BD-4EF7-87EA-B22842EC1650/data/Containers/Bundle/Application/7E00DBF5-783E-40EA-9C84-A915B102591D/Microsoft.Extensions.HostFactoryResolver.Tests.app
default	13:15:22.218782-0400	Microsoft.Extensions.HostFactoryResolver.Tests	Xml file was written to the provided writer.
default	13:15:22.219031-0400	Microsoft.Extensions.HostFactoryResolver.Tests	Tests run: 0 Passed: 0 Inconclusive: 0 Failed: 0 Ignored: 0
default	13:15:22.219175-0400	Microsoft.Extensions.HostFactoryResolver.Tests	[TerminateWithSuccess]
default	13:15:22.219753-0400	Microsoft.Extensions.HostFactoryResolver.Tests	----- Done -----
info	13:15:22.220879-0400	Microsoft.Extensions.HostFactoryResolver.Tests	Exit code: 0.
```

### PR DESCRIPTION
**Pull request by eerhardt**
Fix #52118

### CODE REVIEW

**Review by maryamariyan — APPROVED** [review]

**Comment by lewing** [comment]
@eerhardt this seems to have broken a lot of the staging builds.

**Comment by eerhardt** [comment]
@lewing - which ones?  All the runtime checks passed on this PR.

**Comment by lewing** [comment]
runtime-staging doesn't fail in a clear way https://dev.azure.com/dnceng/public/_build/results?buildId=1118930&view=results

**Comment by eerhardt** [comment]
The first one I looked into has:

```
    Microsoft.Extensions.Hosting.Tests.HostBuilderTests.HostBuilderConfigureDefaultsInterleavesMissingConfigValues [FAIL]
      System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandle.PlatformNotSupported.cs(24,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
        /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Win32.cs(76,0): at System.IO.FileSystemWatcher.StartRaisingEvents()
        /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs(638,0): at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
        /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs(151,0): at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
        /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs(398,0): at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
        /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs(143,0): at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
        /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFileProvider.cs(345,0): at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
        /_/src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/FileConfigurationProvider.cs(33,0): at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
        /_/src/libraries/Microsoft.Extensions.Primitives/src/ChangeToken.cs(71,0): at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1[[System.Action, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, Action state)
        /_/src/libraries/Microsoft.Extensions.Primitives/src/ChangeToken.cs(32,0): at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
        /_/src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/FileConfigurationProvider.cs(32,0): at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
        /_/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationProvider.cs(20,0): at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
        /_/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationSource.cs(21,0): at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
        /_/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationBuilder.cs(51,0): at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
        /_/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs(201,0): at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
        /_/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs(133,0): at Microsoft.Extensions.Hosting.HostBuilder.Build()
        /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostBuilderTests.cs(628,0): at Microsoft.Extensions.Hosting.Tests.HostBuilderTests.HostBuilderConfigureDefaultsInterleavesMissingConfigValues()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
````

which looks like it should be https://github.com/dotnet/runtime/issues/34582. All of the "host" tests are marked with this active issue:

https://github.com/dotnet/runtime/blob/fa409aa66dc45a2e3a15056d1f81f40640da62dd/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs#L36

**Comment by eerhardt** [comment]
The Android and TvOS runs of that build appear to be unrelated/not the new tests failing.

The 2 browser-wasm legs appear to be failing for a different reason than Windows above:

```
[17:50:19] info: console.info: Initializing.....
[17:50:19] info: Discovering: Microsoft.Extensions.HostFactoryResolver.Tests.dll (method display = ClassAndMethod, method display options = None)
[17:50:19] info: Discovered:  Microsoft.Extensions.HostFactoryResolver.Tests.dll (found 12 of 12 test cases)
[17:50:19] info: Starting:    Microsoft.Extensions.HostFactoryResolver.Tests.dll
[17:50:19] fail: [FAIL] Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.CreateHostBuilderPattern_CanFindHostBuilder
[17:50:19] info: Assert.NotNull() Failure
[17:50:19] info:    at Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.CreateHostBuilderPattern_CanFindHostBuilder()
[17:50:19] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[17:50:19] fail: [FAIL] Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.BuildWebHostPattern_CanFindWebHost
[17:50:19] info: Assert.NotNull() Failure
[17:50:19] info:    at Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.BuildWebHostPattern_CanFindWebHost()
[17:50:19] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[17:50:19] fail: [FAIL] Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.CreateHostBuilderPattern_CanFindServiceProvider
[17:50:19] info: Assert.NotNull() Failure
[17:50:19] info:    at Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.CreateHostBuilderPattern_CanFindServiceProvider()
[17:50:19] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[17:50:19] fail: [FAIL] Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.CreateWebHostBuilderPattern_CanFindServiceProvider
[17:50:19] info: Assert.NotNull() Failure
[17:50:19] info:    at Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.CreateWebHostBuilderPattern_CanFindServiceProvider()
[17:50:19] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[17:50:19] fail: [FAIL] Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.BuildWebHostPattern_CanFindServiceProvider
[17:50:19] info: Assert.NotNull() Failure
[17:50:19] info:    at Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.BuildWebHostPattern_CanFindServiceProvider()
[17:50:19] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[17:50:19] fail: [FAIL] Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.CreateWebHostBuilderPattern_CanFindWebHostBuilder
[17:50:19] info: Assert.NotNull() Failure
[17:50:19] info:    at Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.CreateWebHostBuilderPattern_CanFindWebHostBuilder()
[17:50:19] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[17:50:19] fail: [FAIL] Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.CreateWebHostBuilderPattern__InvalidReturnType_CanFindServiceProvider
[17:50:19] info: Assert.NotNull() Failure
[17:50:19] info:    at Microsoft.Extensions.Hosting.Tests.HostFactoryResolverTests.CreateWebHostBuilderPattern__InvalidReturnType_CanFindServiceProvider()
[17:50:19] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[17:50:19] info: Finished:    Microsoft.Extensions.HostFactoryResolver.Tests.dll
[17:50:19] info: 
[17:50:19] info: === TEST EXECUTION SUMMARY ===
[17:50:19] info: Total: 12, Errors: 0, Failed: 7, Skipped: 0, Time: 0.190903s
```

Is there an easy way to debug into this configuration?

**Comment by lewing** [comment]
It is definitely more than this PR, I think my information may have been wrong.

**Comment by lewing** [comment]
Given the two new browser lanes that failed (EAT, AOT) I suspect they are aggressive trimming related.

**Pull request merged**
