### PR TITLE
[libs][mono] Enable diagnostics_tracing runtime component in Android build

### LINKED ISSUE #50926: System.Diagnostics.Tracing.Tests Fails on Android
System.Diagnostics.Tracing.Tests
BasicEventSourceTests.FuzzyTests.Test_Write_Fuzzy
BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_NamedEventSource
BasicEventSourceTests.TestsManifestNegative.Test_GenerateManifest_InvalidEventSources
BasicEventSourceTests.TestsTraits.Test_EventSource_Traits_Dynamic
BasicEventSourceTests.TestsTraits.Test_EventSource_Traits_Contract
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_NoAttribute
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_SelfDescribing_EventListener
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ComplexData_SelfDescribing_EventListener
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_Manifest_EventListener_UseEvents
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ByteArray_Manifest_EventListener
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ByteArray_SelfDescribing_EventListener
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ByteArray_Manifest_EventListener_UseEvents
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_Manifest_EventListener
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_SelfDescribing_EventListener_UseEvents
BasicEventSourceTests.TestsWriteEventToListener.Test_EventSourceCreatedEvents_BeforeListener
BasicEventSourceTests.TestsWriteEventToListener.Test_WriteEvent_ArgsBasicTypes
BasicEventSourceTests.TestsWriteEventToListener.Test_WriteEvent_InvalidCalls
BasicEventSourceTests.TestsWriteEventToListener.Test_EventSourceCreatedEvents_AfterListener
BasicEventSourceTests.TestsWriteEventToListener.Test_WriteEvent_ArgsCornerCases
BasicEventSourceTests.TestsWriteEventToListener.Test_WriteEvent_ZeroKwds
BasicEventSourceTests.TestsWrite.Test_Write_T_EventListener
BasicEventSourceTests.TestsWrite.Test_Write_T_EventListener_UseEvents
BasicEventSourceTests.TestsUserErrors.Test_BadTypes_Manifest_UserClass
BasicEventSourceTests.TestsUserErrors.Test_BadEventSource_MismatchedIds

```
System.Diagnostics.Tracing.Tests.dll   Failed: 24

Test collection for System.Diagnostics.Tracing.Tests.dll
BasicEventSourceTests.FuzzyTests.Test_Write_Fuzzy
    BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\n************* EXCEPTION INFO ***************\nSystem.InvalidOperationException: EventSource not enabled after 5 seconds\n   at BasicEventSourceTests.Listener.WaitForEnable(EventSource logger) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 43\n   at BasicEventSourceTests.Listener.EventSourceSynchronousEnable(EventSource eventSource, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 35\n   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 119\n*********** END EXCEPTION INFO *************\nVersion of Runtime 6.0.0\nVersion of OS Unix 4.14.112.0\n**********************************************\n\n---- System.InvalidOperationException : EventSource not enabled after 5 seconds
BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_NamedEventSource
    System.NullReferenceException : Object reference not set to an instance of an object
BasicEventSourceTests.TestsManifestNegative.Test_GenerateManifest_InvalidEventSources
    Assert.NotNull() Failure
BasicEventSourceTests.TestsTraits.Test_EventSource_Traits_Dynamic
    Assert.Equal() Failure\nExpected: EtwSelfDescribingEventFormat\nActual:   Default
BasicEventSourceTests.TestsTraits.Test_EventSource_Traits_Contract
    Assert.Equal() Failure\nExpected: EtwSelfDescribingEventFormat\nActual:   Default
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_NoAttribute
    BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\n************* EXCEPTION INFO ***************\nSystem.InvalidOperationException: EventSource not enabled after 5 seconds\n   at BasicEventSourceTests.Listener.WaitForEnable(EventSource logger) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 43\n   at BasicEventSourceTests.Listener.EventSourceSynchronousEnable(EventSource eventSource, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 35\n   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 119\n*********** END EXCEPTION INFO *************\nVersion of Runtime 6.0.0\nVersion of OS Unix 4.14.112.0\n**********************************************\n\n---- System.InvalidOperationException : EventSource not enabled after 5 seconds
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_SelfDescribing_EventListener
    BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\n************* EXCEPTION INFO ***************\nSystem.InvalidOperationException: EventSource not enabled after 5 seconds\n   at BasicEventSourceTests.Listener.WaitForEnable(EventSource logger) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 43\n   at BasicEventSourceTests.Listener.EventSourceSynchronousEnable(EventSource eventSource, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 35\n   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 119\n*********** END EXCEPTION INFO *************\nVersion of Runtime 6.0.0\nVersion of OS Unix 4.14.112.0\n**********************************************\n\n---- System.InvalidOperationException : EventSource not enabled after 5 seconds
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ComplexData_SelfDescribing_EventListener
    BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\n************* EXCEPTION INFO ***************\nSystem.InvalidOperationException: EventSource not enabled after 5 seconds\n   at BasicEventSourceTests.Listener.WaitForEnable(EventSource logger) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 43\n   at BasicEventSourceTests.Listener.EventSourceSynchronousEnable(EventSource eventSource, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 35\n   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 119\n*********** END EXCEPTION INFO *************\nVersion of Runtime 6.0.0\nVersion of OS Unix 4.14.112.0\n**********************************************\n\n---- System.InvalidOperationException : EventSource not enabled after 5 seconds
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_Manifest_EventListener_UseEvents
    BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\n************* EXCEPTION INFO ***************\nSystem.InvalidOperationException: EventSource not enabled after 5 seconds\n   at BasicEventSourceTests.Listener.WaitForEnable(EventSource logger) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 43\n   at BasicEventSourceTests.Listener.EventSourceSynchronousEnable(EventSource eventSource, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 35\n   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 119\n*********** END EXCEPTION INFO *************\nVersion of Runtime 6.0.0\nVersion of OS Unix 4.14.112.0\n**********************************************\n\n---- System.InvalidOperationException : EventSource not enabled after 5 seconds
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ByteArray_Manifest_EventListener
    BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\n************* EXCEPTION INFO ***************\nSystem.InvalidOperationException: EventSource not enabled after 5 seconds\n   at BasicEventSourceTests.Listener.WaitForEnable(EventSource logger) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 43\n   at BasicEventSourceTests.Listener.EventSourceSynchronousEnable(EventSource eventSource, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 35\n   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 119\n*********** END EXCEPTION INFO *************\nVersion of Runtime 6.0.0\nVersion of OS Unix 4.14.112.0\n**********************************************\n\n---- System.InvalidOperationException : EventSource not enabled after 5 seconds
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ByteArray_SelfDescribing_EventListener
    BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\n************* EXCEPTION INFO ***************\nSystem.InvalidOperationException: EventSource not enabled after 5 seconds\n   at BasicEventSourceTests.Listener.WaitForEnable(EventSource logger) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 43\n   at BasicEventSourceTests.Listener.EventSourceSynchronousEnable(EventSource eventSource, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 35\n   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 119\n*********** END EXCEPTION INFO *************\nVersion of Runtime 6.0.0\nVersion of OS Unix 4.14.112.0\n**********************************************\n\n---- System.InvalidOperationException : EventSource not enabled after 5 seconds
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_ByteArray_Manifest_EventListener_UseEvents
    BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\n************* EXCEPTION INFO ***************\nSystem.InvalidOperationException: EventSource not enabled after 5 seconds\n   at BasicEventSourceTests.Listener.WaitForEnable(EventSource logger) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 43\n   at BasicEventSourceTests.Listener.EventSourceSynchronousEnable(EventSource eventSource, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 35\n   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 119\n*********** END EXCEPTION INFO *************\nVersion of Runtime 6.0.0\nVersion of OS Unix 4.14.112.0\n**********************************************\n\n---- System.InvalidOperationException : EventSource not enabled after 5 seconds
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_Manifest_EventListener
    BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\n************* EXCEPTION INFO ***************\nSystem.InvalidOperationException: EventSource not enabled after 5 seconds\n   at BasicEventSourceTests.Listener.WaitForEnable(EventSource logger) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 43\n   at BasicEventSourceTests.Listener.EventSourceSynchronousEnable(EventSource eventSource, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 35\n   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 119\n*********** END EXCEPTION INFO *************\nVersion of Runtime 6.0.0\nVersion of OS Unix 4.14.112.0\n**********************************************\n\n---- System.InvalidOperationException : EventSource not enabled after 5 seconds
BasicEventSourceTests.TestsWriteEvent.Test_WriteEvent_SelfDescribing_EventListener_UseEvents
    BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\n************* EXCEPTION INFO ***************\nSystem.InvalidOperationException: EventSource not enabled after 5 seconds\n   at BasicEventSourceTests.Listener.WaitForEnable(EventSource logger) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 43\n   at BasicEventSourceTests.Listener.EventSourceSynchronousEnable(EventSource eventSource, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 35\n   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 119\n*********** END EXCEPTION INFO *************\nVersion of Runtime 6.0.0\nVersion of OS Unix 4.14.112.0\n**********************************************\n\n---- System.InvalidOperationException : EventSource not enabled after 5 seconds
BasicEventSourceTests.TestsWriteEventToListener.Test_EventSourceCreatedEvents_BeforeListener
    Assert.True() Failure\nExpected: True\nActual:   False
BasicEventSourceTests.TestsWriteEventToListener.Test_WriteEvent_ArgsBasicTypes
    Assert.Contains() Failure\nNot found: EventSource_ToString, , 00000000-0000-0000-0000-000000000000\nIn value:  EventSource[] []
BasicEventSourceTests.TestsWriteEventToListener.Test_WriteEvent_InvalidCalls
    System.NullReferenceException : Object reference not set to an instance of an object
BasicEventSourceTests.TestsWriteEventToListener.Test_EventSourceCreatedEvents_AfterListener
    Assert.True() Failure\nExpected: True\nActual:   False
BasicEventSourceTests.TestsWriteEventToListener.Test_WriteEvent_ArgsCornerCases
    System.NullReferenceException : Object reference not set to an instance of an object
BasicEventSourceTests.TestsWriteEventToListener.Test_WriteEvent_ZeroKwds
    Assert.NotNull() Failure
BasicEventSourceTests.TestsWrite.Test_Write_T_EventListener
    BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\n************* EXCEPTION INFO ***************\nSystem.InvalidOperationException: EventSource not enabled after 5 seconds\n   at BasicEventSourceTests.Listener.WaitForEnable(EventSource logger) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 43\n   at BasicEventSourceTests.Listener.EventSourceSynchronousEnable(EventSource eventSource, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 35\n   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 119\n*********** END EXCEPTION INFO *************\nVersion of Runtime 6.0.0\nVersion of OS Unix 4.14.112.0\n**********************************************\n\n---- System.InvalidOperationException : EventSource not enabled after 5 seconds
BasicEventSourceTests.TestsWrite.Test_Write_T_EventListener_UseEvents
    BasicEventSourceTests.EventTestHarness+EventTestHarnessException : Error Detected in EventTestHarness.RunTest\n************* EXCEPTION INFO ***************\nSystem.InvalidOperationException: EventSource not enabled after 5 seconds\n   at BasicEventSourceTests.Listener.WaitForEnable(EventSource logger) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 43\n   at BasicEventSourceTests.Listener.EventSourceSynchronousEnable(EventSource eventSource, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/Listeners.cs:line 35\n   at BasicEventSourceTests.EventTestHarness.RunTests(List`1 tests, Listener listener, EventSource source, FilteringOptions options) in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EventTestHarness.cs:line 119\n*********** END EXCEPTION INFO *************\nVersion of Runtime 6.0.0\nVersion of OS Unix 4.14.112.0\n**********************************************\n\n---- System.InvalidOperationException : EventSource not enabled after 5 seconds
BasicEventSourceTests.TestsUserErrors.Test_BadTypes_Manifest_UserClass
    Assert.Equal() Failure\nExpected: 1\nActual:   0
BasicEventSourceTests.TestsUserErrors.Test_BadEventSource_MismatchedIds
    Assert.Equal() Failure\nExpected: BadEventSource_MismatchedIds\nActual:   (null)

### PR DESCRIPTION
**Pull request by mdh1418**
Fixes https://github.com/dotnet/runtime/issues/50926

### CODE REVIEW

**Comment by mdh1418** [comment]
This will cause merge conflicts with https://github.com/dotnet/runtime/pull/72394 due to both touching tests.mobile.targets, but if desired, we could block this until that PR is merged and only remove the test skip and extend the diagnostics_tracing condition.

**Review by steveisok — APPROVED** [review]
You can go first.  It'll be easier to merge

**Comment by mdh1418** [comment]
The failures are unrelated for non-Android lanes. The android specific failures on runtime-extra-platforms have been disabled by https://github.com/dotnet/runtime/pull/72948

**Pull request merged**
