### PR TITLE
Replace "corefx" with "libraries" in System.Net tests

### PR DESCRIPTION
**Pull request by eanova**
This PR addresses #347 
This is a first commit of self contained changes to PowerShell scripts found in the Deployment directory.

Also want to double check that the usage of the term "corefx repo", should be changed to "runtime repo".

### CODE REVIEW

**Comment by davidsh** [comment]
Thanks for the PR!

**Review by davidsh — APPROVED** [review]

**Comment by eanova** [comment]
Thanks for the review!  I stashed the rest of the changes for now since those changes would involve environmental variables for the Cloud Service configuration.

**Comment by davidsh** [comment]
>since those changes would involve environment variables for the Cloud Service configuration.

Are you talking the files here?
https://github.com/dotnet/runtime/tree/master/src/libraries/Common/tests/System/Net/Prerequisites/Servers/CoreFxNetCloudService

We've deprecated this CloudService. We no longer use it in production. The files here are obsolete and we will be deleting them from the repo soon.

**Comment by eanova** [comment]
Yes that's the service.  My changes will be deleted too,  but at least this area is resolved.

**Pull request merged**
