### PR TITLE
[tests] Re-enable some explicit layout tests on Mono

### LINKED ISSUE #62567: classloader NestedStructs case 03, 04, and 05 failing in mono full AOT

### PR DESCRIPTION
**Pull request by lambdageek**
These were fixed by https://github.com/dotnet/runtime/pull/61467

During full AOT compilation we try to load all of these problematic types, so AOT compilation will fail.  As a result these tests are all expected to fail the llvmfullaot lanes.

Related to https://github.com/dotnet/runtime/issues/36112

Fixes https://github.com/dotnet/runtime/issues/62567

### CODE REVIEW

**Comment by lambdageek** [comment]
Need to disable most of these on llvmfullaot.  I think it's expected that they wouldn't compile (since the AOT compiler will do layout at AOT time)

**Comment by lambdageek** [comment]
The runtime-manual failures aren't related

**Review by simonrozsival — APPROVED** [review]

**Pull request merged**
