### PR TITLE
Make Crossgen2 a self-contained package

### PR DESCRIPTION
**Pull request by fadimounir**
We had a discussion about it in our team meeting today and we'll go with a self-contained package for crossgen2 in dotnet5.0

cc @dotnet/crossgen-contrib

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Cc @jkoritzinsky

**Comment by jkoritzinsky** [comment]
This conflicts with the work in https://github.com/dotnet/runtime/pull/31701 to move crossgen2 into Arcade along with the rest of the managed components in coreclr. Arcade doesn't support publishing as part of a build as far as I can tell, so that moves crossgen2 to just use the framework-dependent build.

**Comment by jkoritzinsky** [comment]
Also, do we want to publish it as self-contained with the runtime from the sdk we build dotnet/runtime with, or the runtime built as part of the build of dotnet/runtime?

This PR currently uses the runtime from the sdk we build dotnet/runtime with. As a result, when building a shipping product, the crossgen2 product would ship with a non-shipping runtime.

If we move the packaging steps for crossgen2 up to the installer subset, then we would have enough of the runtime constructed to create a self-contained crossgen2 package using the just-built runtime. This would enable the release package of crossgen2 to ship with a release runtime.

**Comment by fadimounir** [comment]
> This conflicts with the work in #31701 

How do you suggest we fix that? We want to ship crossgen2 as a self-contained package. 

> Also, do we want to publish it as self-contained with the runtime from the sdk we build dotnet/runtime with, or the runtime built as part of the build of dotnet/runtime?

> If we move the packaging steps for crossgen2 up to the installer subset, then we would have enough of the runtime constructed to create a self-contained crossgen2 package using the just-built runtime

We want it to ship using the 5.0 runtime that we'll ship eventually. Sounds like this should move to the installer subset then?

**Comment by fadimounir** [comment]
@jkoritzinsky and I discussed it in person:
1) We can delete the crossgen2 packaging project from the coreclr sub-repo, since we're shipping the one from the installer sub-repo
2) We'll merge this PR for now (after deleting the project in coreclr), to unblock SDK work
3) @jkoritzinsky Will work on making the crossgen2 package a self-contained one from Arcade instead of dotnet/runtime, and dotnet/runtime will build a temporary FD package instead.

**Comment by jkoritzinsky** [comment]
To clarify item 3:

I'll make the crossgen2 assembly build as framework-dependent, and make the Microsoft.NETCore.App.Crossgen2 package project assemble a self-contained crossgen2 manually with live bits when creating the package.

**Review by jkoritzinsky — APPROVED** [review]

**Pull request merged**
