### PR TITLE
Fix CNG persisted symmetric key operations

### LINKED ISSUE #31092: 6 crypto cng tests are failing consistently in outerloop Windows
Example build: https://dev.azure.com/dnceng/public/_build/results?buildId=378973&view=ms.vss-test-web.build-test-results-tab

```
System.Security.Cryptography.Cng.Tests.AesCngTests.VerifyPersistedKey
System.Security.Cryptography.Cng.Tests.TripleDESCngTests.VerifyPersistedKey
System.Security.Cryptography.Cng.Tests.TripleDESCngTests.SetKey_DetachesFromPersistedKey
System.Security.Cryptography.Cng.Tests.AesCngTests.SetKey_DetachesFromPersistedKey
System.Security.Cryptography.Cng.Tests.AesCngTests.VerifyMachineKey
System.Security.Cryptography.Cng.Tests.TripleDESCngTests.VerifyMachineKey

Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : The parameter is incorrect.

at System.Security.Cryptography.CngKey.SetProperty(CngProperty property) in /_/src/System.Security.Cryptography.Cng/src/System/Security/Cryptography/CngKey.Properties.cs:line 71
   at Internal.Cryptography.BasicSymmetricCipherNCrypt..ctor(Func`1 cngKeyFactory, CipherMode cipherMode, Int32 blockSizeInBytes, Byte[] iv, Boolean encrypting) in /_/src/System.Security.Cryptography.Cng/src/Internal/Cryptography/BasicSymmetricCipherNCrypt.cs:line 36
   at Internal.Cryptography.CngSymmetricAlgorithmCore.CreatePersistedCryptoTransformCore(Func`1 cngKeyFactory, Byte[] iv, Boolean encrypting) in /_/src/System.Security.Cryptography.Cng/src/Internal/Cryptography/CngSymmetricAlgorithmCore.cs:line 181
   at Internal.Cryptography.CngSymmetricAlgorithmCore.CreateCryptoTransform(Boolean encrypting) in /_/src/System.Security.Cryptography.Cng/src/Internal/Cryptography/CngSymmetricAlgorithmCore.cs:line 130
   at Internal.Cryptography.CngSymmetricAlgorithmCore.CreateEncryptor() in /_/src/System.Security.Cryptography.Cng/src/Internal/Cryptography/CngSymmetricAlgorithmCore.cs:line 105
   at System.Security.Cryptography.TripleDESCng.CreateEncryptor() in /_/src/System.Security.Cryptography.Cng/src/System/Security/Cryptography/TripleDESCng.cs:line 79
   at System.Security.Cryptography.Cng.Tests.SymmetricCngTestHelpers.SetKey_DetachesFromPersistedKey(CngAlgorithm algorithm, Func`2 persistedFunc) in /_/src/System.Security.Cryptography.Cng/tests/SymmetricCngTestHelpers.cs:line 159
   at System.Security.Cryptography.Cng.Tests.TripleDESCngTests.SetKey_DetachesFromPersistedKey() in /_/src/System.Security.Cryptography.Cng/tests/TripleDESCngTests.cs:line 53
```

cc @bartonjs @krwq @GrabYourPitchforks

### PR DESCRIPTION
**Pull request by bartonjs**
During a code cleanup the encoding changed from UTF-16LE
to UTF-8, which is not valid for the P/Invoke.

Fixes #31092.

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
I checked the test results but couldn't locate the impacted tests. LGTM other than that.

**Review by eiriktsarpalis — APPROVED** [review]

**Comment by bartonjs** [comment]
> I checked the test results but couldn't locate the impacted tests.

Yeah, the default view only shows failed things.  So if you type (e.g.) VerifyPersistedKey into the filter, then go over to the outcome tab and clear the filter, you'll see it ran on 4 legs (two of which had failures) and while two of those legs saw failures, none had failures in that test.

It makes sense given the default action is to investigate failures, but it's somewhat annoying when it gets in the way :smile:.

**Comment by eiriktsarpalis** [comment]
> Yeah, the default view only shows failed things

Yeah, it didn't show up even when I added passed tests in the filter. Not
sure why.

**Pull request merged**
