### PR TITLE
Move UseSystemZlib into SetupOSSpecificProps

### LINKED ISSUE #106566: Native AOT Binaries still depend on libz.so
### Description

Based on https://github.com/dotnet/dotnet-docker/discussions/5792, libz.so has been removed from the runtime-deps image for .NET 9, however, when trying to run an application AOT compiled for ARM64 and containerized, an error is thrown:
```
/app/HwoodiwissHelper: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file
```

Which indicates that the build is still dependant on zlib as a shared library, rather than statically linked/included in the output executable as indicated by the [discussion](https://github.com/dotnet/dotnet-docker/issues/5687) linked in the announcement.

### Reproduction Steps

1. Create a project with `<PublishAot>true</PublishAot>` and `<EnableSdkContainerSupport>true</EnableSdkContainerSupport>`
2. Publish the container image with `dotnet publish ./src/HwoodiwissHelper/HwoodiwissHelper.csproj --os linux --arch arm64 /t:PublishContainer`
3. Pull and attempt to run the container

Edit - 
Mentioned in @jkotas comment, the containerization doesn't make a difference, I would guess it just provides a sterile enough environment for this issue to show itself.

### Expected behavior

The container should start and run the native compiled binary

### Actual behavior

App startup fails, with error message `/app/HwoodiwissHelper: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file`

### Regression?

_No response_

### Known Workarounds

Manually add `<UseSystemZlib>false</UseSystemZlib>` to your projects properties, to force libz.a to be statically linked.

#### ARM64
.NET Version: .NET 9.0.0-preview.7.24405.7, 9.0.100-rc.1.24452.12
Container base image: mcr.microsoft.com/dotnet/nightly/runtime-deps:9.0.0-preview.7-noble-chiseled-aot (automatically pulled by SDK container publish on 2024-08-16), running on containerd on Debian GNU/Linux 12 (bookworm) (Raspberry Pi)

#### AMD64
.NET Version: .NET 9.0.0-preview.7.24405.7, 9.0.100-rc.1.24452.12
Tested on Docker (WSL) on Windows

### Other information

_No response_

### PR DESCRIPTION
**Pull request by hwoodiwiss**
I have a hunch that the line I've moved is being evaluated before SetupProperties, as it's not currenlty in any target.
It relies on SetupProperties for IlcSdkPath to have a value, so this would cause it to set UseSystemZlib=true in all cases.

My hope is that moving it into SetupOSSpecificProps will fix this ordering issue, as SetupProperties is part of IlcDynamicBuildPropertyDependencies

Hopefully, fixes #106566

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thank you for submitting the fix! I have confirmed that it is fixing the problem. @carlossanlop Could you please check that it is fixing the problem as well?

**Comment by carlossanlop** [comment]
That was quick! Truly appreciated. Thank you! I'll take a look tomorrow as soon as I get a chance.

**Review by am11 — COMMENTED** [review]
@hwoodiwiss, is it so that before:

```sh
$ dotnet new console -n foo
$ cd foo
$ dotnet publish -p:PublishAot=true -o dist
$ ldd dist/foo
```

is showing libz and this PR is going to remove it? It doesn't seems to repro with current RC2 daily build (`dotnet --version` -> `9.0.100-rc.2.24460.28`). MSBuild should propagate properties to all context and there are more properties propagated from global contexts which affect publishing. Perhaps the fix didn't made it in preview7, could you please try with daily build to confirm the issue persists in your environment?

**Comment by hwoodiwiss** [comment]
I'll give it a try with the daily build, based on the binlogs, I can see that it's definitely using the version of this file that was backported in https://github.com/dotnet/runtime/pull/106673

**Comment by am11** [comment]
Yup, some fixes went in ratehr recently, so it would be good to confirm it with latest .NET9 build.
Also, if you haven't already, delete obj/ dir before publishing.

**Comment by hwoodiwiss** [comment]
My test builds have been in [github actions](https://github.com/hwoodiwiss/HwoodiwissHelper/actions/runs/10802310959), so existing intermediate files shouldn't be an issue.

**Comment by martincostello** [comment]
With version `9.0.100-rc.2.24461.4` of the SDK, I can still repro the issue in Azure App Service:

```console
2024-09-11T10:40:31.830250750Z /app/Website: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```

**Comment by am11** [comment]
@martincostello could you share the output of `ldd /app/Website`?

**Comment by martincostello** [comment]
Not easily, no. It was built from this commit if you want to build the image locally and inspect it: https://github.com/martincostello/website/pull/1786/commits/41e4bb409be7170f888dff4624c2323c0b51571d

**Comment by hwoodiwiss** [comment]
Here's the output of `ldd HwoodiwissHelper`
```
        linux-vdso.so.1 (0x00007ffff04b9000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff089b00000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff089a10000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff0897e0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff095baa000)
```

**Comment by am11** [comment]
Thanks for validating the change and taking additional steps. I'd love to understand why it is not reproducible with `console`, `webapi` and `webapiaot` template apps published with PublishAot=true, I think it might be something pulling it up or some interaction in container app model which is pulling it up.

> as I didn't have an arm device to hand

It is enough for testing I think, but as a tip for future, there are multiple ways to go about it, two of which are:

1. install arch-specific binutils for your target (e.g. `apt install binutils-aarch64-linux-gnu`) and then use `aarch64-linux-gnu-readelf -a path/to/app | grep "Shared library:"`
2. install multi-arch llvm (`apt install llvm`), then use `llvm-readelf --needed-libs path/to/app`

**Comment by am11** [comment]
Thanks for validating the change and taking additional steps. I'd love to understand why it is not reproducible with `console`, `webapi` and `webapiaot` template apps published with PublishAot=true, I think it might be something pulling it up in container app model.

> as I didn't have an arm device to hand

It is enough for testing I think, but as a tip for future, there are multiple ways to go about it, two of which are:

1. install arch-specific binutils for your target (e.g. `apt install binutils-aarch64-linux-gnu`) and then use `aarch64-linux-gnu-readelf -a path/to/app | grep "Shared library:"`
2. install multi-arch llvm (`apt install llvm`), then use `llvm-readelf --needed-libs path/to/app`

**Comment by hwoodiwiss** [comment]
> I'd love to understand why it is not reproducible with console, webapi and webapiaot template apps

I had a hunch on this too, they're not using any compression, so `System.Io.Compression` gets trimmed

Here's an example without usage - https://github.com/hwoodiwiss/ZlibDependencyTest/actions/runs/10819324810/job/30016934658#step:7:20

Example from a PR that adds usage -
https://github.com/hwoodiwiss/ZlibDependencyTest/actions/runs/10819331997/job/30016956732#step:7:21

**Comment by jkotas** [comment]
> [Merge branch 'main' into hwoodiwiss-106566](https://github.com/dotnet/runtime/pull/107666/commits/28ebd179df1b445a49c9fcdf0c19677ed72997fd)

@hwoodiwiss You do not have to be doing this. The repo maintainers will do it as necessary once the PR is ready to merge.

**Comment by MichalStrehovsky** [comment]
> Thanks for validating the change and taking additional steps. I'd love to understand why it is not reproducible with `console`, `webapi` and `webapiaot` template apps published with PublishAot=true, I think it might be something pulling it up in container app model.

Last time I was looking at it, webapi/webapiaot didn't use libz. Console doesn't use it for sure.

**Comment by am11** [comment]
Ah, didn't knew that linker optimization is this thorough that it will drop the the entire dependency. :)

Changing it to `no-as-needed` persists the libz dependency:
https://github.com/dotnet/runtime/blob/4930e1b44027484e13a29c7f3230e1f0bb397e7c/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets#L219

```
	/lib/ld-musl-aarch64.so.1 (0xffffa794c000)
	libz.so.1 => /lib/libz.so.1 (0xffffa791b000)
	libc.musl-aarch64.so.1 => /lib/ld-musl-aarch64.so.1 (0xffffa794c000)
```

> MSBuild should propagate properties to all context and there are more properties propagated from global contexts which affect publishing.

`!Exists('$(IlcSdkPath)libz.a')` was always failing due to `IlcSdkPath` being empty at global prop evaluation because it is assigned in `SetupProperties` targets the first time.

**Review by am11 — APPROVED** [review]
👍

**Review by carlossanlop — APPROVED** [review]
I tested this and I can confirm the issue is fixed. Here's what I did:

- OS: Ubuntu 24.04 x64
- Uninstall system zlib: `sudo apt remove zlib1g-dev`
- Install RC2 nightly: `./dotnet-install.sh -v 9.0.100-rc.2.24462.22`
- Confirm I'm using the correct version of dotnet: 
  ```
  dotnet --list-sdks
  9.0.100-rc.2.24462.22 [/home/carlos/.dotnet/sdk]
  ```
- Create console app: `dotnet new console -o naot`
- Added `<PublishAot>true</PublishAot>` to the csproj
- Ran the publish command using: `dotnet publish naot.csproj`

I got the expected error:

```
$ dotnet publish

Restore complete (0.9s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  naot failed with 2 error(s) (2.9s) → bin/Release/net9.0/linux-x64/naot.dll
    clang : error : linker command failed with exit code 1 (use -v to see invocation)
    /home/carlos/.nuget/packages/microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/build/Microsoft.NETCore.Native.targets(376,5): error MSB3073: The command ""clang" "obj/Release/net9.0/linux-x64/native/naot.o" -o "bin/Release/net9.0/linux-x64/native/naot" -Wl,--version-script=obj/Release/net9.0/linux-x64/native/naot.exports -Wl,--export-dynamic -gz=zlib -fuse-ld=bfd /home/carlos/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/sdk/libbootstrapper.o /home/carlos/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/sdk/libRuntime.WorkstationGC.a /home/carlos/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/sdk/libeventpipe-disabled.a /home/carlos/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/sdk/libRuntime.VxsortEnabled.a /home/carlos/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/sdk/libstandalonegc-disabled.a /home/carlos/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/sdk/libstdc++compat.a /home/carlos/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/framework/libSystem.Native.a /home/carlos/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/framework/libSystem.Globalization.Native.a /home/carlos/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/framework/libSystem.IO.Compression.Native.a /home/carlos/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/framework/libSystem.Net.Security.Native.a /home/carlos/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/framework/libSystem.Security.Cryptography.Native.OpenSsl.a -g -Wl,-rpath,'$ORIGIN' -Wl,--build-id=sha1 -Wl,--as-needed -pthread -ldl -lz -lrt -lm -pie -Wl,-pie -Wl,-z,relro -Wl,-z,now -Wl,--eh-frame-hdr -Wl,--discard-all -Wl,--gc-sections" exited with code 1.

Build failed with 2 error(s) in 4.0s
```

- I edited this file: `/home/carlos/.nuget/packages/microsoft.dotnet.ilcompiler/9.0.0-rc.2.24459.11/build/Microsoft.NETCore.Native.Unix.targets`
- Deleted the `obj/` and `bin/` folders.
- Ran `dotnet publish naot.csproj` again.
- Success!
  ```
  $ dotnet publish
  Restore complete (0.8s)
  You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
    naot succeeded (3.4s) → bin/Release/net9.0/linux-x64/publish/

  Build succeeded in 4.4s
  ```

Thanks, @hwoodiwiss !

**Comment by carlossanlop** [comment]
/ba-g The `runtime-dev-innerloop (Build linux-x64 debug Libraries_AllConfigurations) ` CI leg is stuck. It has this error in the log:
```
##[error]Agent failed with exception: The machine running request a5063779-f4ce-42b5-999d-94d58c5cdd68 restarted. Azure DevOps can't recover from restarts.
,##[warning]Received request to deprovision: The request was cancelled by the remote provider.
```

**Pull request merged**
