### PR TITLE
[DllImportGenerator] Don't generate a full stub body when the body does nothing

### LINKED ISSUE #60596: [DllImportGenerator] Improve handling of blittable signatures in source generator
Detect blittable signatures and generate partial extern p/invokes.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Generate the partial function as a DllImport when a full-body generated stub would be a no-op wrapper around an inner DllImport.

Fixes #60596

### CODE REVIEW

**Review by AaronRobinsonMSFT — APPROVED** [review]
This is great. I need this for the "unsupported framework" fallback. I have it all set up except the forwarder to `DllImport` logic.

**Comment by am11** [comment]
Crossgen2 considers Boolean and Char as billitable types: https://github.com/dotnet/runtime/blob/ba01c5953581441b2737b54732a517af30a41e22/src/coreclr/tools/aot/ILCompiler.TypeSystem.ReadyToRun.Tests/MarshalUtilsTests.cs#L25-L56 but TypeSymbolExtensions doesn't: https://github.com/dotnet/runtime/blob/b201a16e1a642f9532c8ea4e42d23af8f4484a36/src/libraries/System.Runtime.InteropServices/gen/Microsoft.Interop.SourceGeneration/TypeSymbolExtensions.cs#L54-L69
should they match?

**Comment by am11** [comment]
Ah right. The test was added as part of addressing https://github.com/dotnet/runtime/pull/46653#issuecomment-755944742, which suggests crossgen2 case is different (`crossgen2 is not involved in Marshal.SizeOf`).

**Comment by jkoritzinsky** [comment]
We definitely would definitely see bugs if this was broken in real scenarios. I was very confused about how it was broken.

**Review by elinor-fung — APPROVED** [review]

**Pull request merged**
