### PR TITLE
Move GenTreeVecCon and GenTreeMskCon under the respective FEATURE_* defines

### PR DESCRIPTION
**Pull request by tannergooding**
Follow up from https://github.com/dotnet/runtime/pull/104875

### CODE REVIEW

**Comment by tannergooding** [comment]
This represents just general cleanup and can be delayed until .NET 10

**Comment by tannergooding** [comment]
CC. @kunalspathak, this should be ready for review.

Just represents the general cleanup we had talked about around the constants and ensuring they're under the right `#define`

**Comment by tannergooding** [comment]
> Don't our most important targets have these defined?

Yes, at least for `FEATURE_SIMD`. For our official targets I believe just `UNIX_X86` and `ARM32` don't support it. There's more that don't when you factor in community targets.

> I would personally like if we moved toward fewer conditionally defined nodes/opers rather than more of them, except if there are some really tangible benefits.

I don't disagree.

`SIMD` is really a fundamental part of the ABI. `HW_INTRINSICS` (and `MASKED_HW_INTRINSICS`) are then built on top of the `SIMD` feature, and its something that's so integral to perf in the BCL that not having it is a huge detriment to the user experience.

We somewhat have the split due to historical reasons and it would be nice if we merged them together into a single feature, but it won't remove most of the `ifdef` soup while we have targets without SIMD support. 

With this PR, we're not really introducing any new ifdef soup and it actually simplifies it in other cases. The places it remains soupy are mainly the places we have to do different things for `SIMD` vs `no SIMD`.

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by tannergooding** [comment]
@jakobbotsch do you have any other input on this one?

My preference would be to take this, given it makes our build given existing defines more correct. Then to separately look at (and come to a shared decision with the JIT team) as to how we want to simplify it, if at all.

There's a couple of older issues that allude to such a cleanup: https://github.com/dotnet/runtime/issues/9473 and https://github.com/dotnet/runtime/issues/11701, but we've never actually determined what should actually be done. Such a cleanup (when/if it happens) will likely be quite a bit more involved

**Pull request merged**
