### PR TITLE
JIT: defer creating throw helper code until we know it's needed

### LINKED ISSUE #104658: JIT: Unnecessary prolog frame setup in .NET 9
See https://github.com/dotnet/runtime/issues/104655#issuecomment-2219992097 -- .NET 9 has an unnecessary stack allocation for the locals 

The example is:
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
private static int Sum(int[] arr)
{
    int sum = 0;
    for (int i = 0; i < arr.Length; i++)
    {
        sum += arr[i];
    }

    return sum;
}
```
and the codegen diff showing the prolog is:
```diff
Method Program:Sum(int[]):int (FullOpts)
 ; Emitting BLENDED_CODE for X64 with AVX - Windows
 ; FullOpts code
@@ -7,8 +166,9 @@
 ; No PGO data
 
 G_M000_IG01:                ;; offset=0x0000
+       sub      rsp, 40
  
-G_M000_IG02:                ;; offset=0x0000
+G_M000_IG02:                ;; offset=0x0004
        xor      eax, eax
        xor      edx, edx
        mov      r8d, dword ptr [rcx+0x08]
@@ -16,15 +176,16 @@ G_M000_IG02:                ;; offset=0x0000
        jle      SHORT G_M000_IG04
        align    [0 bytes for IG03]
  
-G_M000_IG03:                ;; offset=0x000D
+G_M000_IG03:                ;; offset=0x0011
-       mov      r10d, edx
-       add      eax, dword ptr [rcx+4*r10+0x10]
+       add      eax, dword ptr [rcx+4*rdx+0x10]
        inc      edx
        cmp      r8d, edx
        jg       SHORT G_M000_IG03
  
 G_M000_IG04:                ;; offset=0x001C
+       add      rsp, 40
        ret      
  
-; Total bytes of code 29
+; Total bytes of code 33
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Defer creation of throw helper code until the stack level setter analysis has determined the throw helper is needed. Defer finalizing the outgoing arg size as well.

The throw helper support now goes through the steps:
* early on phases can request that a throw helper block get created
* we create the blocks (but not the code) before final block layout so they get proper placement
* lowering adds references to throw helpers that are actually needed
* stack level setter then materializes code for the needed helpers, and removes the blocks for the unneeded ones
* we can then finalize the outgoing arg space size

Closes #104658.

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=739624&view=ms.vss-build-web.run-extensions-tab)

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

Some size improvements, no regressions. Oddly, some perf score regressions.

**Review by jakobbotsch — APPROVED** [review]
LGTM.

Any idea how hard it would be to delay creating the `BasicBlock` itself as well? We would need to fill in some liveness, but I wonder if there are any other problems with it.

**Comment by AndyAyersMS** [comment]
> LGTM.
> 
> Any idea how hard it would be to delay creating the `BasicBlock` itself as well? We would need to fill in some liveness, but I wonder if there are any other problems with it.

We'd have to do some custom placement instead of relying on the main block layout algorithm. Or defer layout until later.

**Comment by jakobbotsch** [comment]
> We'd have to do some custom placement instead of relying on the main block layout algorithm. Or defer layout until later.

I see, I didn't know we run the layout algorithm before lowering.

I suppose the important part there is `fgMoveColdBlocks`, since the RPO part of the layout algorithm is not going to do much for the throw helpers considering that they aren't modelled in the flow graph.

**Comment by amanasifkhalid** [comment]
If the throw helper's block is assumed cold, then it should be pretty trivial to emulate `fgMoveColdBlocks`'s behavior by just inserting the new throw block at the end of whatever region you're in, right? It wouldn't necessarily respect the relative RPO ordering within each cold section like `fgMoveColdBlocks` does, but that seems fine.

**Comment by AndyAyersMS** [comment]
> it should be pretty trivial to emulate `fgMoveColdBlocks`'s behavior

My preference would be to have just one place that does all the layout logic. In particular once we start splitting, and if we're ever able to split EH regions, this stuff will get more involved.

**Comment by amanasifkhalid** [comment]
> My preference would be to have just one place that does all the layout logic.

Got it, I still plan on exploring moving layout (and `fgDetermineFirstColdBlock`) further back, so it's probably best to not introduce more localized layout changes.

> In particular once we start splitting

I appreciate the commitment your usage of "once" implies

**Pull request merged**
