### PR TITLE
Fix regex-redux tests to consistently remove newlines

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Need to check for \r\n as well as \n.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
PTAL @sandreenko 
CC @dotnet/jit-contrib 

Suspect this is a result of #43736. Not sure why the current version is passing in CI, perhaps we are enabling old behavior there still?

**Comment by stephentoub** [comment]
> Suspect this is a result of #43736

It shouldn't be, as regex uses ordinal by default.

**Comment by stephentoub** [comment]
> Not sure why the current version is passing in CI, perhaps we are enabling old behavior there still?

Maybe when the data files got checked out locally, they got rewritten with \r\n?

**Comment by AndyAyersMS** [comment]
> Maybe when the data files got checked out locally, they got rewritten with \r\n?

Maybe, though this is new behavior and I don't recall changing any config settings.

**Comment by danmosemsft** [comment]
Presumably the test is failing without your change?

**Comment by AndyAyersMS** [comment]
Locally, yes...
```
agggtaaa|tttaccct 1
[cgt]gggtaaa|tttaccc[acg] 0
a[act]ggtaaa|tttacc[agt]t 0
ag[act]gtaaa|tttac[agt]ct 0
agg[act]taaa|ttta[agt]cct 0
aggg[acg]aaa|ttt[cgt]ccct 1
agggt[cgt]aa|tt[acg]accct 0
agggta[cgt]a|t[acg]taccct 0
agggtaa[cgt]|[acg]ttaccct 0

342
256
157
ERRORLEVEL=-1
```
That last `157` is a string length, it should be `152`. There are 5 newlines in the input file...

**Comment by BruceForstall** [comment]
fwiw, I see the same failure as Andy. And the .txt files all have \r\n on my file system.

Did something change in the moving of the test tree? #38058

E.g., were the files previously marked binary?

Presumably Andy's change allows the tests to work no matter what the newline format is, so is general goodness?

**Review by sandreenko — APPROVED** [review]
The change LGTM, but I agree with Bruce it would be useful to understand what has changed and why it is passing in CI.

> Maybe when the data files got checked out locally, they got rewritten with \r\n?

These files had `/r/n` from the beginning according to my Notepad++, do not know if it is possible to show it on GitHub.

**Comment by stephentoub** [comment]
> These files had /r/n from the beginning according to my Notepad++, not if it is possible to show it on GitHub.

Not in the git repo:
```C#
using System;
using System.Net.Http;

Console.WriteLine(new HttpClient().GetStringAsync("https://raw.githubusercontent.com/dotnet/runtime/master/src/tests/JIT/Performance/CodeQuality/BenchmarksGame/regex-redux/regexdna-input25.txt").Result.IndexOf('\r'));
Console.WriteLine(new HttpClient().GetStringAsync("https://raw.githubusercontent.com/dotnet/runtime/master/src/tests/JIT/Performance/CodeQuality/BenchmarksGame/regex-redux/regexdna-input25000.txt").Result.IndexOf('\r'));
```
outputs:
```
-1
-1
```

**Comment by BruceForstall** [comment]
I think I found the problem: .gitattributes didn't get updated when the tests moved -- they still point at the old files:
```
# CLR specific
src/coreclr/src/pal/tests/palsuite/paltestlist.txt text eol=lf
src/coreclr/src/pal/tests/palsuite/paltestlist_to_be_reviewed.txt text eol=lf
src/coreclr/tests/src/JIT/Performance/CodeQuality/BenchmarksGame/regexdna/regexdna-input25.txt text eol=lf
src/coreclr/tests/src/JIT/Performance/CodeQuality/BenchmarksGame/regexdna/regexdna-input25000.txt text eol=lf
src/coreclr/tests/src/JIT/Performance/CodeQuality/BenchmarksGame/regex-redux/regexdna-input25.txt text eol=lf
src/coreclr/tests/src/JIT/Performance/CodeQuality/BenchmarksGame/regex-redux/regexdna-input25000.txt text eol=lf
src/coreclr/tests/src/JIT/Performance/CodeQuality/BenchmarksGame/reverse-complement/revcomp-input25.txt text eol=lf
src/coreclr/tests/src/JIT/Performance/CodeQuality/BenchmarksGame/reverse-complement/revcomp-input25000.txt text eol=lf
src/coreclr/tests/src/JIT/Performance/CodeQuality/BenchmarksGame/k-nucleotide/knucleotide-input.txt text eol=lf
src/coreclr/tests/src/JIT/Performance/CodeQuality/BenchmarksGame/k-nucleotide/knucleotide-input-big.txt text eol=lf
src/coreclr/tests/src/performance/Scenario/JitBench/Resources/word2vecnet.patch text eol=lf
```

cc @trylek

**Comment by sandreenko** [comment]
the version before the move https://raw.githubusercontent.com/dotnet/runtime/9bb997bfa110b98d17a0ed7fe5a9f163072f36a3/src/coreclr/tests/src/JIT/Performance/CodeQuality/BenchmarksGame/regex-redux/regexdna-input25.txt .

**Comment by stephentoub** [comment]
> the version before the move

No '\r's in that one either :smile:

**Comment by stephentoub** [comment]
> It's unfortunate that the tests are dependent on the specific line endings

My only hesitancy in changing them is it moves away from how regex redux is defined:
https://benchmarksgame-team.pages.debian.net/benchmarksgame/description/regexredux.html#regexredux
"use the same simple regex pattern match-replace to remove FASTA sequence descriptions and all linefeed characters"
and the same ">.*\n|\n" pattern that all the submissions use.

If the goal of having the test here is to match that, we should be wary of changing it.  If the goal of having the test here is just to have a meaty regex test, then changing it is fine.

**Comment by trylek** [comment]
My apologies about the missing .gitattributes path renames, I'll send out a PR to fix these.

**Comment by BruceForstall** [comment]
For simplicity, we should probably keep these as close to possible as the "official" code, so we'll just need to live with the config to force LF line endings for the test input.

**Comment by AndyAyersMS** [comment]
Ah, I remember creating those gitattributes, long ago. Updating them makes sense, so I think we can abandon this PR.

Still not clear how the tests are passing in CI. Any explanation for that? I suppose we are shipping files around so perhaps we're building on one OS and running on another?

**Comment by BruceForstall** [comment]
In the CI we always (?) build tests on Mac, so its `git` doesn't do line ending translation.

**Comment by trylek** [comment]
Correct - well, in fact I recently switched that over to Linux as the lab Macs have become much slower but your argument still holds.

**Pull request closed without merging**
