### PR TITLE
LSG: removing unnecessary null forgiven operators and refactor other minor nullability issues

### PR DESCRIPTION
**Pull request by allantargino**
- `GetBestTypeByMetadataName` returns a nullable type, so I just make it explicit in code (we were already checking if the instance was null).
- There is a `Debug.Assert(logMethodSymbol != null`, so I removed the next null checks (besides, we are retrieving the related Symbol from the SemanticalModel using the related SyntaxNode, so there shouldn't be any problems).
- Cleaning null forgiving from `paramTypeSymbol`, which is guaranteed to be not null at that point.
- Cleaning other minor parts

### CODE REVIEW

**Comment by tarekgh** [comment]
> There is a Debug.Assert(logMethodSymbol != null, so I removed the next null checks

What happen in the release (non-debug) builds?

**Comment by allantargino** [comment]
Currently there is no other null check in release builds - should I explicit check for nulls instead of the `Debug.Assert`? And if it is null (meaning, the `MethodDeclarationSyntax` node was present, but not its `IMethodSymbol`), what should we return? Isn't this a critical compilation error?

**Comment by tarekgh** [comment]
If we are sure `logMethodSymbol` never be `null` then don't declare it as nullable. 

```C#
IMethodSymbol logMethodSymbol = sm.GetDeclaredSymbol(method, _cancellationToken)!;
```

**Comment by allantargino** [comment]
Thanks. Besides that change, I just added a new one regarding how we were instantiating the semantical model. Currently, we do a null check every time to see if the variable was not null inside the `foreach`, but we can do it just once before the loop.
> This is exactly how `System.Text.Json` does to instantiate it just once: https://github.com/dotnet/runtime/blob/2ca02292c29a77fc50d678463c5ebee772f37334/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs#L264-L265

**Review by tarekgh — APPROVED** [review]

**Comment by tarekgh** [comment]
Thanks @allantargino!

**Pull request merged**
