### PR TITLE
[llvm] Fix the IR generated for returning small valuetypes by value.

### PR DESCRIPTION
**Pull request by vargaz**
We were generating loads larger than the size of the alloca holding the valuetype.

### CODE REVIEW

**Comment by jandupej** [comment]
Can we optimize this by using zero-extension for valuetypes with nice sizes (1,2,4 B) and falling back to this memory-based approach with other sizes?

**Comment by lateralusX** [comment]
Moving the alloca into the entry_bb made wonders to the generated code, we now get the following assembler for the case where argument is null:

```
00007FF6BD348A70  test        rdx,rdx  
00007FF6BD348A73  je           07FF6BD348AC0h
...
00007FF6BD348AC0  xor         eax,eax  
00007FF6BD348AC2  add         rsp,28h  
00007FF6BD348AC6  ret
```

**Review by lateralusX — APPROVED** [review]
LGTM!

**Comment by vargaz** [comment]
Does this need a backport ?

**Comment by lateralusX** [comment]
I would say yes, we have repros so it can be hit, and if hit, side effects are hard to understand and track and can cause crashes since it can return uninitialized memory.

**Pull request merged**
