### PR TITLE
[release/6.0] Use CLOCK_BOOTTIME to calculate BootTime on linux (#67589)

### LINKED ISSUE #83816: System.Diagnostics.Process.BootTime doesn't work on Android
```
[DOTNET]   Error: Failure getting precise App startup time.
[DOTNET] System.UnauthorizedAccessException: Access to the path '/proc/stat' is denied.
[DOTNET]  ---> System.IO.IOException: Permission denied
[DOTNET]    --- End of inner exception stack trace ---
[DOTNET]    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
[DOTNET]    at Interop.CheckIo(Error error, String path, Boolean isDirError)
[DOTNET]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)
[DOTNET]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
[DOTNET]    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode, Func`4 createOpenException)
[DOTNET]    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
[DOTNET]    at System.IO.Strategies.UnixFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
[DOTNET]    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
[DOTNET]    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
[DOTNET]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
[DOTNET]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
[DOTNET]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
[DOTNET]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
[DOTNET]    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
[DOTNET]    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
[DOTNET]    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
[DOTNET]    at System.IO.File.ReadAllText(String path, Encoding encoding)
[DOTNET]    at System.IO.File.ReadAllText(String path)
[DOTNET]    at System.Diagnostics.Process.get_BootTime()
[DOTNET]    at System.Diagnostics.Process.BootTimeToDateTime(TimeSpan timespanAfterBoot)
[DOTNET]    at System.Diagnostics.Process.get_StartTimeCore()
[DOTNET]    at System.Diagnostics.Process.get_StartTime()
```

### PR DESCRIPTION
**Pull request by simonrozsival**
Backport of https://github.com/dotnet/runtime/pull/67589 to release/6.0

/cc @am11 @adamsitnik

# Customer impact
A customer reported that they can't use the `Process.StartTime` API in their Android app (#83816). The problem is that recent Android versions don't allow reading the `/proc/stat` file anymore. Instead, we use the `clock_gettime` libc function.

This bug as already been fixed in .NET 8 but we didn't backport it to .NET 6.0 at that time. The .NET 6.0 MAUI support lasts until the end of May 2023 so we should backport this bugfix.

Fixes #83816

# Testing
Manual testing and unit tests.

# Risk
Low. The fix is well tested.

### CODE REVIEW

**Comment by carlossanlop** [comment]
I'm retargeting this PR to the new `release/6.0-staging` branch, which is the one that we will use from now on for servicing fixes. 

Repo maintainers will now be allowed to merge their own servicing PR as long as it meets the requirements:

- It is approved by Tactics (signaled by adding the `Servicing-approved` label).
- It's signed-off by an area owner.
- The CI is green, or the failures are investigated as unrelated.
- And if the PR touches an OOB package, the necessary OOB authoring changes are added.

The new process is described here: [runtime/docs/project/library-servicing.md](https://github.com/dotnet/runtime/blob/release/6.0-staging/docs/project/library-servicing.md).

The infra team will be actively monitoring servicing PRs to ensure all requirements are met and to help with any issues.

Let me know if you have any questions.

**Comment by simonrozsival** [comment]
Thanks, @carlossanlop. The PR now has changes to NuGet.config, eng/Version.Details.xml, and eng/Versions.props though. I think I'll have to change the PR manually so that it doesn't bring these unnecessary changes to the staging branch.

**Comment by carlossanlop** [comment]
@simonrozsival you are free to merge into the staging branches anytime, as soon as you meet the requirements:
- [ ] Sign-off by area owner.
- [X] No OOB changes needed for the involved assemblies. System.Diagnostics.Process does not have IsPackable set to true.
- [X] Approved by Tactics. Mandatory `Servicing-approved` label applied.
- [X] CI is green.

The Code-complete date for the May 2023 Release is April 10th.

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @simonrozsival !

**Pull request merged**
