### PR TITLE
Fix analyzer warning that is breaking the build

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Currently failing with error:
```
error CA1868: Do not guard 'HashSet.Add(string)' with 'HashSet.Contains(string)' (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1868)
```

### CODE REVIEW

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you for fixing the build @eiriktsarpalis 

BTW it would be great to understand why the build got broken (I imagine that enabling new analyzers should require a new PR that should simply fail and require a fix before being merged)

Edit: https://github.com/dotnet/runtime/pull/89869 most likely run the CI checks before the new analyzer got enabled

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Fast merge to unblock CI.

**Comment by adamsitnik** [comment]
> Fast merge to unblock CI.

image

Jokes aside I am very supportive of that!

**Comment by eiriktsarpalis** [comment]
I also want that badge now 🤣

**Pull request merged**
