### PR TITLE
JIT: refactor arm64 epilog generation

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Instead of rederiving the frame type for epilog generation, use the
frame type we derived during prolog generation.

This is done in anticpation of creating OSR epilogs, where we will
need aspects of epilog sequences for both the OSR method and the Tier0
method, and they may have different frame types.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib PTAL

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib ping

**Comment by AndyAyersMS** [comment]
(no diffs)

**Review by echesakov — APPROVED** [review]

**Review by BruceForstall — COMMENTED** [review]
I like saving and re-using this data. Something like this is done for funclet prologs/epilogs: see `CodeGen::genCaptureFuncletPrologEpilogInfo()` and `FuncletFrameInfoDsc`. I wonder if something similar should be done for the main prolog/epilog? (I.e., create a struct, save more than just frame type)

It seems a little odd to put this in the `info` struct; I always thought of that as (mostly?) for "incoming" data about the function being compiled.

**Comment by AndyAyersMS** [comment]
Happy to generalize this to remove the need for re-computing things that are "known".

I put it on `info` because I need it to be accessible from the `compiler` object-- for OSR some subset (hopefully just frame type) will be stored in the patchpoint info.

**Comment by BruceForstall** [comment]
> I put it on `info` because I need it to be accessible from the `compiler` object

Sure, makes sense to have it on the `compiler` object, just not (IMO) in the `info` struct.

**Review by BruceForstall — APPROVED** [review]
That looks great

**Pull request merged**
