### PR TITLE
Update branding for 5.0.13

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by Anipik** [comment]
@safern can you take a look at drawing.common.tests failures here ?

**Comment by safern** [comment]
@Anipik we need to disable those tests. Those started failing because the OS was updated. I still need to figure out why and if it is a GDI+ bug that needs to get fixed. Do you want me to push disabling of them to this PR?

**Comment by Anipik** [comment]
> @Anipik we need to disable those tests. Those started failing because the OS was updated. I still need to figure out why and if it is a GDI+ bug that needs to get fixed. Do you want me to push disabling of them to this PR?

yes can you push it to the pr

**Comment by safern** [comment]
It seems like I don't have permissions to push to @vseanreesermsft fork. I'll create a separate PR.

**Pull request merged**
