### PR TITLE
Bump main PreReleaseVersionIteration to 3

### PR DESCRIPTION
**Pull request by carlossanlop**
The snap of preview2 has been done. Now main represents preview3.

### CODE REVIEW

**Review by radical — APPROVED** [review]

**Review by smasher164 — APPROVED** [review]

**Comment by carlossanlop** [comment]
@lewing @steveisok @radical I tagged you in case you need to also include additional wasm or mono changes related to branding.

**Comment by carlossanlop** [comment]
@radical @lewing @steveisok any chance this error could be related to this PR, or can I ignore it and create a new issue to track it?
```
eng/testing/workloads-testing.targets(191,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Could not install manifest Microsoft.NET.Workload.Emscripten.Current/8.0.0-preview.2.23113.1. This can be ignored if the workload wasm-tools doesn't depend on it.
```

**Comment by radical** [comment]
Looking at it now

**Comment by radical** [comment]
> @radical is this the sdk version override getting confused?

For future reference, the Emscripten dependencies needed to be updated because the string `previewN` is in manifest name now.

**Comment by radical** [comment]
This is green now. A corresponding Emscripten update in https://github.com/dotnet/installer/blob/2e73c9d439e3d48efbd557619d1de0475176b881/eng/Version.Details.xml#L168-L180  will be needed too.

**Pull request merged**
