### PR TITLE
Speed up KeyAnalyzer for substring based frozen collections

### PR DESCRIPTION
**Pull request by IDisposable**
Building on PR #89689, I tried making everything as explicitly inline-able and sealed to get the JIT to eliminate any conditional jumps in the hot loop by teasing out the various comparator options into trait-like classes to mix in to get `sealed` classes where all the logic in conditional-free (down to the internals of the `String.AsSpan()` methods themselves.

This required making some complex extractions. The essence is that now we construct an equality comparer and hash set for the from-the-left attempt, and then [lazily construct another comparer and matching `HashSet<string>`](https://github.com/dotnet/runtime/pull/89863/files#diff-8dfef3756fbf6ca0aab7668e6abf54ae6c416c60cb1b3bd86455204942f7dbefR56) only if we need one for from-the-right attempt. Since in the vast number of cases, we're going to spend the bulk of the execution time iterating through the `uniqueStrings` we're presented with, the overhead of having another comparer/collection is pretty low in comparison.

To ensure we don't bloat memory, we now `.Clear()` the set just before we `return false;` from `HasSufficientUniquenessFactor` since we know that we're going to get called again for a different index/count... this means that both `HashSet<string>`s spend their lifetimes empty except in mid-check (we could clear them on success, as well, but the old code didn't bother).

The resulting `SubstringEqualityComparer` classes could be useful elsewhere, but are currently just internal to the `System.Collections.Immutable` assembly. We could easily extend them to also support the `InvariantCulture` and `CurrentCulture` options, but not sure when we would want to use either (it wouldn't make much sense for a FrozenDictionary/FrozenSet, but there could be other use-cases).

Hoisted the [calculation of the maximum offset](https://github.com/dotnet/runtime/pull/89863/files#diff-8dfef3756fbf6ca0aab7668e6abf54ae6c416c60cb1b3bd86455204942f7dbefR56) per-pass up to the top of the count (length loop), because that calculation applies to both left-justified and right-justified, and also doesn't change during the inner loops.

The comparers expose an interface that internally manipulates the starting-index and count in such a way that it gets in-lined completely. Basically you tell it where to `Start()` when you change the count (width) of the slice, such that when doing a pass of _count_ width in a from-the-left pass, you [start with index of zero](https://github.com/dotnet/runtime/pull/89863/files#diff-8dfef3756fbf6ca0aab7668e6abf54ae6c416c60cb1b3bd86455204942f7dbefR57). When doing a from-the-right pass, you start with the [**negative** count](https://github.com/dotnet/runtime/pull/89863/files#diff-8dfef3756fbf6ca0aab7668e6abf54ae6c416c60cb1b3bd86455204942f7dbefR85) offset (e.g. as far right as will accommodate the slice width) . Once you start, you can [`GoLeft()`](https://github.com/dotnet/runtime/pull/89863/files#diff-8dfef3756fbf6ca0aab7668e6abf54ae6c416c60cb1b3bd86455204942f7dbefR96) or [`GoRight()`](https://github.com/dotnet/runtime/pull/89863/files#diff-8dfef3756fbf6ca0aab7668e6abf54ae6c416c60cb1b3bd86455204942f7dbefR68) to bump the index appropriately (without field/property calls).

The implementation uses:
* Static "mix-in"  `Slicer` methods for `LeftSlice` and `RightSlice` to extract the slice's `ReadOnlySpan<char>`
* Static "mix-in" `OrdinalEquality` for `Equals` and `GetHashCode` operations to use when implementing `IEqualityComparer<string>` in an ordinal _case-sensitive_ way
* Static "mix-in" `OrdinalInsensitiveEquality` for `Equals` and `GetHashCode` operations to use when implementing `IEqualityComparer<string>` in an ordinal _case-**in**sensitive_ way
* Sealed concrete encapsulations of the mix-ins for `LeftSubstringOrdinalComparer`, `RightSubstringOrdinalComparer`, `LeftSubstringCaseInsensitiveComparer`, and `RightSubstringCaseInsensitiveComparer`
* Sealed concrete `FullStringComparer` for use when we decide that we aren't going to use substrings at all.
* Use of the [`IGenericSpecializedWrapper`](https://github.com/dotnet/runtime/pull/89863/files#diff-79b65d5bcad7e08df16f62da5a89991951cd19c28818fcc15ed2328f0855ac23R112-R118) / [`GSW`](https://github.com/dotnet/runtime/pull/89863/files#diff-79b65d5bcad7e08df16f62da5a89991951cd19c28818fcc15ed2328f0855ac23R112-R118) pattern to ["pass in"](https://github.com/dotnet/runtime/pull/89863/files#diff-79b65d5bcad7e08df16f62da5a89991951cd19c28818fcc15ed2328f0855ac23R61-R71) the specialization to eliminate all `virtcall`s and can be completely inlined
* Aggressive inline of the slicers/comparers via liberal application of `[MethodImpl(MethodImplOptions.AggressiveInlining)]`

I suspect we could pass the chosen slicer out in the `AnalysisResults` as it encapsulates the offset, length, and ignore/honor case for use in the resulting `Frozen` collection constructions, but that would be another pass.

I also added some more tests to the *KeyAnalyserTests* for `ContainsAnyLetters` and `HasSufficientUniquenessFactor` to verify newly exposed behavior and also added some testing based on the known instances of freezable data that is being used in the *FrozenFromKnownValuesTests*.

The other changes imported from PR  #88516 here are:

* Eliminate the the inner `TryUseSubstring` because we can just early return the calculated results as we build them
* Hoist the calculation of `acceptableNonUniqueCount` out to the top level since it never changes (which means we pass that into the `HasSufficientUniquenessFactor` method for it to "use up" internally (passed by value, so unchanged at call-site)
* Eliminated the delegate `ReadOnlySpan<char> GetSpan` and use, which helps reduce dynamic dispatch overhead in the `CreateAnalysisResults` method
* Eliminated the `IsLeft` field of the `SubstringComparer` since we can tell by the Index being negative that we're doing right-justified slicing (and documented that on the class)
* Changed the logic managing the `Index` and `Count` on the comparer for right-justified substrings.
Added `[MethodImpl(MethodImplOptions.AggressiveInlining)]` to the `Equals` and `GetHashCode` overrides.

### CODE REVIEW

**Comment by IDisposable** [comment]
This should supersede both PR #89689 and PR #88516

**Comment by IDisposable** [comment]
SharpLab with all the classes combined so you can see the resulting IL/JIT [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwGIA7AV11wENhcYACGY62gWACgB6DugGWzEYBnGABM6GCOIAW9AHQA5AKIAVOgDEIpYiMoZsEYnS0iYUOgfrQ6AW2j1KAc1gxrjDINnsudZTLoKVdU1tXX1DXH4hGEFpbBiAMzx6CToAT00jbVNpegBZAElVCIFiYU82dgABAAY6SoBGFABuKtqG2QARbEdiCEE9MEEWthq6+tkAJS09V1kAYQhrAAckqABlUwA3SKH2diZXQSXKATH5iAoYMD0DDzUoCAAvRnYAb3Y6T6/P7GIMUyYuDov3+UHiJ3o+TWpGADWqigAjqRKBEMKkFstKLAzCA6PlEcjUejFsdsQAeOEAPg+X3ebG+3y43DJglI1msWNS1PpDM+TJ8fl+JgQdF0dAA7lJ+FJxJJgDAHL9YjFBMUYDTefyyRxWezOdzeXzvGTYByoABrQSUgDy8XiwgwdHiD2sOTotHijsE2BMdAAFNh4nRng9zGYln1sHpNjAAJRhuhQbAOKRen30ANB4gK0Ix2Pa01Yy0Gw2VADMwL+eKyItedAcMAwTToAF89jzNcbdWauRqGfzfPQTN7YGJaMQHBgZfErFP6KrIv6YAgwLhSN68+VDXQtTq2T2S7zy5XHQtpnQ6w2m6329utd39X3Gd5chAYzE53R+li9BPK8LzGzWU3Q9R0/RMMBTTcQRYyfL4tULC0rQAdRkQxxRgAByWA6BECBfgcd0YE9OAACt1z0RJRC/YoCLQN1xU0XAxFsGM3W/KBf0IiMQToVc+myFIQwgejJReDt+28DDsKHfC/yTFMMDIijA2waiFzAOjlRsN9on/ZdRXFShUidF1g1MESv0kCQjKgMRP3lRViGIAjzCDOc4KNbg4X9SgYiFZdqOdRY3QU1Mv3TWNZALFwiytTyd2NPc9SgXsJO+Y9qH6KATkdSoUDoABxCAeGIjA/VjYYEvvfdH3S+CX10j8/A4rj9JFCxgM/MKwN+SCXGg2D6q8ugTVipDKVQxgJSwnC8Nc0DlP6VT1Noid6M/RjyBY3T2IwH9XJ4qtKCMkzgtdYTRLQ6qpNm2TXJ6pbKLUsQNK0qc4h0992tlWyxEuqzfqxey/EYMQIHcmQbu8+paj9Pz2qCszuuTcLvRMKKYrNYtodG5KDwSzLgGy3K6gK4qJlR8rKtvQ0apStK728DZ3CMJYnSsGAoxkMxQITHq6HI5aqNetbCIh0UxmqXHtQfVLD0k5lSUoV0DhgABeAAiAKEE1ylBy/fbONcnWObMN71uBINhITJwYF0UwNrQ7TPsoIiSKF57VsXc7cc/Vq3LdX4llIPLYdkPEg1oQRmumgG50MD7/JiN3Hs9lbRZ95HQe0QOPOGxLuGD0OpeijhlesBXnyVrEVboNWtcgaY9YNshrHlMwJbAKRa+uUwP0kPq119JV/bVMuK6rhrmUQ4tlFSFYwBRd2lPTkWaJ2CUmLEY4Y9GivYCzFWNe1mtNY4SlA+EiP58X5e05UkXcY0vStuYuhd5iMkD+I+vj61nW59L6bBRKQZIPdHSfU/NmBwDsxAgLXJYSG9Bv612sIfP+rhG7BAwEAviODn7WQgexNUW9tp0HlCBPyXpGyB27r3UEggsZxSnp8ImJNrhkzoGsI25VeI63orxJufwaYVALvTAm4jvBzFgA7FO9cYDikTPbPCxBcAmSOJQQwukzCfgjMbAwec/BGyvKXGW+M6pMxrjlVW/9NaCBbsYrEpi4QTzQawwuo1lwCCWDcQw/V4hawAIJQAcGyNw8hyC4EUCuGAviwh61QTYjBDd7F4M+mQCgZdvFxL8R4rUOT4mGICcE0J4S/jWlDraCYWiGwxJ8X4vWuNfAPHFOhZ2/slhXAzj9KwwjIExF6JAwwOUJwwC3HTJKhS8mEwrFlDAOVOETBUdaNRqQ1jHGIGSehUBL5rDVH6HyMFhjfDbGI74ABtNYPcoBLB4NQSY0xsCzAAFJRkKowUw/A/Roi6RDP0pVPTQlhLDa0dlfgogxKSUwshCprGQrGWMaAnzXKxHch5Uw/jPPGW8jAHzsxJjAD8heMB/mU0UsCuEYKRAQtwFCrEMK4UIqRSim56LgCPKxa895nzCXEr+fEAFZVKWwzmH5GA+RShCCjNgGM9LsSwvhYi5F6VUW3PuRyzFMwcU8oJd835pLBXktTCK6oYrhCSuEKUGVcqSQMqgIq5lKqGRqvZZy7VshcX4q+USg1/y1BRJ4UmCcBIURRmJJiBVTLEUAF0+wggBMveZiy8oACZuEwjhKGok8rTAACFxVkmUL4OIyEcpLC6bsuguIoSZthtm8NuaoB9jEjhYtUpBBlsoBW7IuJsqkGuPRU1Da0RNoLcIItJbO3lsrZSWQ+RvWEo2d0sNzwRBdp7c2iSdIrGjTllyIJEoZ3ZCxMEEGUDiGMGYHpE4Ag94pGefo/aVZXDt37hKbmmhHQcnNK5bYnFCR8RRLgDwstarywSksJMID/jKMoKo9RPgp0bsrXQAA+knKqBcoMQH+H3MQw6kRhtHXa7E46YAVQSju7cXwMMdroOrXCxFKDkCbAlb4dG4iyB4XYH5HbRHbjOZBh4eH/hiF4mhnWJzDQ4dE9RCT/SsO7rJL8HmUY8JgB3B448vFJUAUvLQ9Wl9JM1mbGc5TqmvkYA01p2ZJ46BnirAZx0Rn0OKZvOcyZzJLNJmsxATTF87P5SKiVMqFUGPGZ1nAOASmvOjR8+p/ztmC7HmCxTKm4XXMmeFAAahy7Fzs3niBqb8wF7TFZgs8J/AGKsAj7P9KGtuajNH0Om0Y1J9jtH+kMfwdMaTvIhNSKKyVmzgWC4XNyI2KQEARD5GWLgP0k2pwzbm0sXA1oimlFkEEhwdsY6yolWo34BFYxxpSxWZZ8HVnqI2Vo7ZNy9kHKOfGLLSduMHOObTQr8XitWdGx4ibU2VvzcW0D2b82Nt+I8DtvbG5DsRBchOU7dngAQAuHQbNghDmwwAPx0AQPROEePUgveM29zHfoCdpFETLBLpXkvbkB8t8Ha3QfM9W+tzb0PduwH2zGSVCOTtne3DpqsHyMAAAk/JSAWCYbHtQYIRfQ298XUvBAy5mxRz7nnvssnA1yAAqsIeykgr00HoA2PVmmjgroiI8UIhjxTc2UfEUwjBTgGtAxYiDQ3Rqz3ir75QkhKDBftt3IxAlKxgFIFAYNhF/0YEAzSzRGBw8pE/CYaD1EDVOyHF8mMIg/YkroD3bQMQ8JtMlv2zh4pj26KkA8UgKYJRSnD8BoDFAU44UrTOKArgRARwFJ9YA4rcaVHTeuPSU4xSW59YbKAA7HS1+7ahlINvNKrvsLnEwcAE+EmwM8CZuuOD+48QmqAgITymHBKcBdvL+DLo33b0QKHTBUc62wgqPHYB+lrSC+ERGOapG2QlQlQScAmLWdQF2Kyayt2WyOyj2kQ8uX4EBLWx4qO6OFORO+OhOuO1O/WNGoujoqu0usuFGz2BBpyfY5mXw8afwiaQIDQSAdQ6a+ykQUAggfYzWDITO02LOC2S2fBHOkOYQ3OsOB2Aux2SOwupYFW9QzBl2Ig126ymy92WIl8gKGAbBAgyBgggitWNY+hjoDWSu0OggcBNWwo9EDWBWPBghwOrO9h/BIhtw22PO0QcOkhiODgyO52YwChMBN2qhCBdAxqWhT2sMX4Rh7U0RJhrmZhFhHgpUE4U4dAOWMRvWIiBBg23w5+l+TBLBdA1KtKI6qQXBCUvBDhAhYOwhXObh4h/OR23hvhIuchzBGBQIFOihyhcBahVaVO3RsBwRD21OSuCA3GMASI7uMA2afoJOthlyThHObOQhEOdRMOvOnhTRQuQW8h9mJB6uZBfogxQRd2IRiurmauUoE4sKjYVxZBxRgIfo2uVBOuV+F+y8BR4+RR4KgIlq0q0YMxgB4a5R42SxIO4Ja2LhW2GxHhEh2x0hux7RaOnRgBWOJxKhZxIxAxgRmJ8BIxJOYxsgFOqQQ6CyBE8qcQBgsgjxKI+QDgvQsA5qcYCxXwlR/BKxVR0JYhmx8JguiJfhBRvEBxGucuGJvR5xpOdAVxBEtxkupBmutJuA9JjJMAzJzxqBHmfYWodOGmY2uR9BHxQIwgKI1E3xmhpqSpTa1aGa/+pRY6haFpda1QVpwBDqTKCs3BBpoIl+1exB8KNpd+Vuj+3Qz+66de7+Bc3wUGsqDsvAwqzprpka2QnGuwUZXwqWX+EgP+f+WawJJGyZZgoB4BSuqZPWQqQKiZvxkKbpsYxZHarJvI7JyxkJnOUO9RvJjR/JPhMhaB0BV2QxWJ6h3CERCuUp2h/csgFpH29EqZ86hhyuHa5w0wmpjOrZnJzh6x7hfO8OUhPZH+UBFCKJGOaJ8ueOVO2BhJrmSppRxJp5E5lOAAhEiiOUgakM+auYaM2RCTUWse2bCTuV4TsemWwhWMKXcQqXLs9krjefmakHKfcZrn6A+TBJ+Z8DQehV9p4ipr9r5nqQrHkcvCabQGIN8WEZadWXSm6TaYRvvgWdClAORmSORVWTSoCE2o6p6QlIRcaQsovkVAGTWoug/l0k/gfi/hGQXF6TJtBnGSxf/kmQxYuXEJQbIVwt/hRrmfWnBdafWXEFKWWYxscVTBRWxTWYWXWWAQ2VhWub+Y4XZW2aIR2XCV2XuS0ZAceOKcMcOQ+dBa5hORwZMCZTOcpR4HpsuLOW9o5hgGhXYQ5RubUf+duVsd2e5X2UeZgaedgReXgVeZfLBXRfBRTg+QgM+UOgcu+YiqpU2eua2dyc5YBQifuSBYeeBfKYcUhX5flZRbeSKUcShVVQlBhVqRJDqbhYlmAPqV8DxV+PbCRYUU6f/syf8daoCdabiLRcRhGgxUxYtXCMtVKqtQdhxR6aCduDNX6QJchIGcJWACGZvuGSvm/lJQeTGTBvQHtaKuKitd6GtdRamdVQyJmdwtmZpZtUAYWXUFZfpaWUnOWZ9Wat9Ydb9cdbWXpWmQed+fZezn+U5QBSlW5b2YQf2UoYOfiT5aOSgUrgFUkcKiFXOeFVTnOdFbFYsfFXVVuQ0buc0UTa0RlaiYSFjtlbgdUMTlKUqT9TakCYVXeYLchQcqVS+Q+ZVazWybVQ5fVfjXyYTQeUQUVBBR1VBZERcd1WZcqcjVLb1QbaKRRgNbFcNTkdNYab6XNWaemvJftUjVaijbapDRtc6faW6UxR7V9RahbX9YWZxWdYaBdXxZwkyjdffndaJaGeJY9ZupGZAR/LJbBiHYjWHd7VLdaQDbrRVlmbxlpQAYVbpdDSbaFeWXnQdYXRHQxZZZhjZV+erTjVCZzZ2dzcBVnZ5biRKSMb5cbeOWqIFeRfTW9ozZFUuSzYDWzd3dUSvZrcldrTzaXfzSeXLcLVLGLTBZRZLYCbecVQrWVa+ToSrUvWrezRrb3S5f3QKYPWBWLtbUcV1T8WbSfQdlbe1TbfLUgahYDQ7VhRda7aRemgGhQEGgRIHX7baXmdXUHYWjA7gHAyGjpW6VHdunZug5gw4AgwxZRi9S1dlgZIxtULfZ8Ght1lQ6Ax3T8M7URXHf6ddUJUnfdWGa/luk1tvZVqDb/uDY2tRejY1pAdJS1t4HDZ1HhNEMQJhI6HhBvJpJbIIJIL0Eek9Z3ObPtP8AeY7S1ljavasT3UlVzUBS/R5STT0d5VWmPWOaYdtuYZshVDQ3QCYwlbja4Vra5VvS1egceVgXgTlaLaMa5q4hTlTvMZjV3WY45b4xvf4wPTY/sR/Z1ePc431UhfbdQX2NxSw4wXsd8QANIwCpBBKAipAhjR2677r5LeA8Bo7mhmwzQUBwDmi9CV7HAYA+kxAYRAbaLxLWDiVtNKhuwOiBw0rXBhCcgJhTPmgVMeDmINMyyn7NKCgmBuw8z0BQKSCJC5z+zTacTRBejOmqP2CQR9ApwUBBzEAhxhzVADOt4ygND1DyJTMQxj6wwvPSiig4QcgIDPLAYmRaDYBTE3x+AQAjNEWkIXrTQr4RDZ6DzECQCjN/hwgxDyiuQ9zq4ou4w97QCugzN+Kcg6i0K4AtOkBLAeB0DlNxKuRjybwIyCAch3MIwRj7bm42DHajPPCxz1xsgdx0I3K5T9y4y/CbAXAF6Vgl7S5aQ26iCuQ0sMTTa0DZ3+YeFH6Ky4yoRiiDMqO7PAgxBQaNhogRTzbjJ0DIT0BUswvmAxj157MPMlxYv0T2u/p/i97sQnP/D9CXMfqpFuwOBo6F6+6MCaDN7gtTHZh7w37ZkRy2vugtOiiOjt6fhYtHmpGLRrwvSii5wPzCz5sIxw1AvPLiWcG+6fgwtPrgt6BT4HNCiZAQtgKXN6EMDr6hmIajx+BLzCCBwcjEAmRZtO6pH+zHzZ3ETYAdTmykB2gzs6vVy4ySot4OxOuBuDNgxsxBtSCCJBgZt9tit9wcGVjSu4Cyu9vzikIMp0BBJrBzD5D5AFtiDSRzRySET9vwC/DN0Ha4wwumAO6lC57oT0BLyGDCC0CcJaJ3sPtPtwBduJCaZftwA/sAkHb4KQ2Sj/PvMJDULZA6Lt5Et95aICBLvTx4wbOCl7FVMoipDeiCDLKsi4Csy0fqLPB+gHleV3ZUgttTGEMdsdHAgMl2DMnREYvJGTh7v2ZAuSdTgSO8hSMMgdAwDABN4uPCCcR+iPkxtgICfzqCCKDLBog04tWBj+gSeMBSd0CXzVAKc0ZKfbiQClDDKOi5CUAICmpydSB8CjMuZ0AAAczY3gWIwAUYOUqUX47LuAqH6u7oFbGAsgSXUYmEgyuGW8nEMon4fUsiA7EzuAobvmUgozyHJItAwLFrKQWidHzwKbYyc7/+VbWd3pfHen5JE4gg3nPWunMA+n3njZNGzM87SHakVYPXcbeH1wVgEsAAnAAKwACkJr9YYbDAvQTeUg5H0j3Alq/w8GgcQgMeTLxC83S3EsOg+0y3obM2ok84Eg7MYkoHdAXTEASi0+6bjotA1CdAi3y3I+A+B5LXt6uS168gBgBuLkUx0V3XkPbXcenXVnqR3Aqa1DTDNGldxD9qK81p7WInTJ4qdAeO2YSiCNTd6HvtJD8YuIxP8ZlZCllFTa7jgPXwVxLMFIsMl8oELMPW7nSzrPjYfoPXAn3nHrZUTapnzXDUM07olAjweAGiKwhgqrKMikmHys2ZLzjAHA5n2YogogzPnwGP2DhZeOPUOPQrFAHj3w/PGA7P1QlIpvJlhmFvuAA3TMQQZgYeMorI/+REKRm3SXZrrusex384frZzfv1n73mr2ww4BviUa3UbMo43Hh8fvEQLXniPMojG7nU4sguQvwfoln/v9E7nnnzp3nvnUYqtvIPrNWxhOCPW9QzY3WZIjGGfFfWfLfOCeW9nWdjnkB6fHnto9ozvxf1ncAmRbGLV24oEHFVWWn1Q1hOCEvkvkkHvDAJwMoEMo/GA9EpibsKf8buUVgPrn4ubj8+bPvWLW3zX3g+QB7w7y31Au0mg9evO6rIgt3MkuEFgt/WddfXiDvymYMM3Iu/UaO32H52gHQzYYAY2F77x9vgA/SXuZz9Bq5oQC7TSG4Ah6ttPkMcNQCfygB+guejYeiEL3a4OAO2wPXxKD3B6w81SK/PvmvyQGICPKAAdgcyyJ/gbHejnECY6sYsc5A+HoIjx5qlxU9EcflOAkEecRe2PWslb0gJGNmBDIOfjg3SyKQmeM/Q0EoOYHeBBwOEDCDhC0YX9i26kZ0jEAlhw1xw1nSgCAjwDXp/+kBe/gezuaWC/AWbW9m4PnCTtrBUgnIIYE9h8QZAYAL1oRBMHPQl4fiZbqyEwGjdEurAo0HQDzQlxzOWiEdr8wBZIJcIgYYPm4Ej5TgO2CcGaJhDuamIaUdoN3MdAiAMlXAfwBIFYHCEZwEhCfTYDECLZexXo5g+iFoleiSBBmKIDRkEKuCtN2hqkSIWEEcEtZUBkgmUI+UgEIBvOTAyXsgOa6oCze1FDJFEiWHKCVhzA9YZDVx6qlmShPBREokbpe1yeDAwsuFmp6KJQiJlVirSkZ419lBPUbnjn0oB89pcLMQXvQOF5Z96I+w1ugoJaw6DlBiQx7sUJwhwC+mrkc6KFCpj0RDuBgu6GmyIjfdwQnvdbimGaHPhTIIUFXuFGj6DMe4bEbrDsnFantbBlAeweblxFfAgR9qbjLwj9BwB+ky/Fcm7zX7eANAnvLfmAIdD79aEh/egRNydCEC2mhI1eJfzMGNdJhd/Hbo/xMiuxUcbEN/tIA/4XAv+UI2SNmHlEACrA9fAUc72obGjHQbfGwFAN36wDoB8AnLNsOYG7C1+qA9AcN34BxCcBsbDwgQKm5EC3hjYR8mQL+EUCqBYABpLQOICeiwELNB0eCIvD0i0CHAmRPbG4HVMGO/AljoIODHCDhORw8Qby2ICyDZOAIxMFTHF4gjmuYIuMQyLLFqDQsnoTQdWNeLVjhqWdVsdoLR54izw78IZE6GbaTMLmOsDgL4Ky7EIjIMQa7mIEjYbcyBA7T8G4GwA4RXEutJMVwJgA8D0x0QAQb8NwECcRBeY4QBIN+BFiZBJYmngQwoGY9sQFUPJm8WjI516ABRG3nb0vi88YANvI0SOPoj4hjeDFF8Wr3tTbCVhlQDgTT2fFUhOObAQgOZyUDKAkAaGaoGhmtATA0MhUCYIoCCTKBFAEwZoV+PYCEAwYgYZoei2BFDU0eb1OMgUQ3F8CtxmYzgSmPXFpiaJzHdwJBKzrcctkvHIQQREE7HlkwB4mAOJ2PElih+CwksUbxQaQ0SJgEzOk4O4AL9HQO/ChCZD8i6hXI7eDwThHvaPt8gB5ITsBiCSCBNI2AB/iqVE4E9GMfFGAFyMSEP8dRQGYQAh0uGCJlGEABRko0tF9Nsg5nTNhkNvbaSn2CYIZPKO8DJDIEQYN9mB3FSodw6B2W7kMy/Bjs08wecUf0GyDSTsQVsUUHc3zhZ1vA1/PyVpLg75B6IgwwZt3GGGb9u48o1AfxPMnCBYxnwJ0YkIDSZdHYWUz8AFOfYFTnmv/RRg3z+A0jDAaQoiF5I4Igdpe4HePiF2uCEhEMxHV0J+AylUlhpMQFDr+zYgwAYwhgczihzQ5HUYw007gOOOURTE0p2o0trs1S71xcM1xQiMSO3gAScIkxOaSZHTwtRnSR08wHOHrwwd/Yg49wDAFwDxB9RXwITuBzWBJSpAZk/HsICDzMkNgB0+gJZIXzWTOxhoXvF739BHI5W3Ejro1IZDNT1+4udiJsklEfT/8oM3kBxL6KXwepPWDKTCgGo2TBuio9iIOMED9TYOOk+iCPjwDmAS4KQECaFFonuAqZDIVAY+XyCCAgkFAQycZOeLOlEUzQomduAMlGTsAJk+IDDLEEDtGM4IEDGjK0EtYIZUMnWcyXhnipEZPtZGeKMNkVjtwwAWROaAdlfAqxCou9ncx6kqgDmWITIYbDwBAgupgEdRIPjsmyMgIznfaD+wLYmQupzQ7wLQDGkdtsY0gA1lFK5mCAoZwEdaZcPFm5EgwfoU2VGG7jmzxUls4QNbKlp0AAAZDXIcwGBo5pQKpqkFKjJzFZ/+ZWcbMJkJihmkMkudDNEEWyIACMy4T1gNnCBXZmFbue7Pd52TypMHLOQPJznRSNpgk3/lZHFmoDi5qeQeQJIrm9dLhBMlgd3NyJDyLJdsyefH3bEDZ0ZiQ5ZIngvxuhqu6iBjsohYkrNAmoEu4dRMY6iyscdU2GevPVnGTTJ58w8U9JhRz1IFDqaKkeMLEljix/vW8YUx9KfE9iWgQQJQFdw71pZss3APLM1nHFh69jOmUBPwkwSVAAXBCUhJQloSMJWEnCV/LODKBlwiXQhdgAM4AA1MNCIA1LDACJhsg8okAQDUQi5NyAAFRfgoAmmRjDBAPJEzSAIIKRb4igAG5JUGAMsOmiMpKK/gEi2MIIBkUVjeII4nrLTX94szvg2HDVsQKz42dGMKAY+bSGaGSz8FcwG5IIElTqK/gWikJOuI1nYA/Qqi7xZotTQXJqgMaOgPgA/gLIQlWii5PUBjRdzqxqs0sBwInlGyWxd8mjMEo0VaK0ijGVNFPPyEyg4ADiisbPMNA7IVFCydxX7KMrVLYwuSnxUUvj7WKMwI46LDZzoB2d4+qSz4DsiCE9YJFqiupVADyzFLt5MoSkFQwQABdelp85xYsqPDpKBhmSuMTfJoybLXiK48QKjJZleMOaFjPulY2aqD09iQnNxR4q8V5LU0fijhYL14gIIwEUpP0M8voD1yAAftUAQDVBqgbAtQAhP+UBoXsDDfCYRPiBkSxE0EoMLBOoWITkJqE9CZhOwnCZYysGAorIgQwmQNgWIbuDwsQRMJziaGPyMZLbmMIesuKmRVIAJVgIPAyYh2H6E1hBI80cwDoIoDUCFQJc+QF5KUx4C5B5A1oAAAoABFCYGsGUAG4uFyEAABoABNAAFrUAwAJgeICmGwCkRzQuAawL0CWAIgOCieTYOKAQA1NNYoiAidoCIkFwZqBRITgsEGk/sW55K/uMQoHKnFyaVaeRWQyzoqc1ODgDTqYHKh4K5ZASjUqZxhV0A4VNCxFfQpRVMLB6HA+lY3KGkyzh2zxElQEudUcFzVQM4QMIrsD8jxFfszTEqC9X994+vq9ToZM07lRNMFon5WwPiAvCC5/oR5SIj9BFyolPShACj3jCT9MIlATCPGAtFtqYqfoTCI8Ewh0B+1g65JWv36V1AOBVkipYY12UZKBFEKqFagoYL+Ed6ro2IdgNFHejCBaA74Y2H/GCjQiJCnjhz1a69cQx0RagftHNxg9Ix9AlmrJJayYzC1OMpUHjMoEEyiZksh0NthEB8LFcdc6dXACfURioxDA88GSB6VOKmpzQkDXMC+5EDm1aSy+essl7bK3Z2S4Wcuq3XWqimcGbFfPn4q/yMx7gT9cTTvZMS/5H8v0EJ0AW6z15+kkNaAu1ngL15vEPFtDIXL8aFS0wISQgpL4ydTxyChRfHzLl6zcx9U3Dc13wUcKwFAknrCAs1lqbFNFYq4ozR6wCbGaumkTVWEYwCboqFYgvi5GsBsguu7fYSRYvj5l9nktmrPl0DtA9YkFE/Asf11XV3i1KQnOTfQGcxmZt6lyrjVpp43qaQtHmV+vZj001gLw9YRsKFsCZv1HQiFc8DFvw2gV7MVmlzdYC67Zbt6vEZzTZsK1uachSWq8KlrC3HlTUMpP8JcRM2Og5hPSjxkE3RxhEXkMokQKaiVwJaAIiG1HgXDAZvEOAEiiRRwD7CpYSm6aRrQ4DqZxUV63jcxk5TB6nK0qQNNoukwAYPFKKrq0mu6tplU06wwsmpNoEWDcYbkogBQGwueLhKklqW2yitqOXraIAm23mhmR21tVEKJgCWrxsO12Mhynq+MGdo4EXa8I1ga7QygHzyB7tggBJU9ti0Ea2AZyIAA===)

**Comment by IDisposable** [comment]
@adamsitnik, just to level-set... this is likely barely worth all the changes _if_ we're only trying to speed up _KeyAnalyzer_ itself... but if this is a gateway toward eventually exposing the higher-performance slicing comparers (based on `ReadOnlySpan<char>`) then it might be worth landing. It does seem to net a 1-3% improvement against baseline for non-trivial sets, and the JITted code is very compact despite all the in-lining and is branchless beyond null-checks and array bounds length checks that are part of the inlined `String.AsSpan()` code.

If desired, I can tease out the unit tests that I added (which are higher value) and the more subtle changes I made along the way to make a simpler version of this.

Additionally, I think it might be worth discussing _in a distinct issue_ the idea of making the `String.AsSpan(start, length)` understand negative offsets internally to eliminate a ton of this code, but that's a public API change as right now passing negative values will throw.

**Comment by IDisposable** [comment]
Thanks @stephentoub! 

Regarding the other points:

> If desired, I can tease out the unit tests that I added (which are higher value) and the more subtle changes I made along the way to make a simpler version of this.

This would be limited to the smaller changes like hoisting the constant calculations and _possibly_ going back to my [original attempt](https://github.com/IDisposable/dotnet-runtime/blob/c1dd5d975e3895b1769fb91308c3c2ac60ed623c/src/libraries/System.Collections.Immutable/src/System/Collections/Frozen/String/KeyAnalyzer.cs)

>Additionally, I think it might be worth discussing in a distinct issue the idea of making the `String.AsSpan(start, length)` understand negative offsets internally to eliminate a ton of this code, but that's a public API change as right now passing negative values will throw.

Any idea if this would be something folks would like to see done? It would be nice to not have to put in conditionals in the first place and leverage the internal knowledge. The current AsSpan merely throws when confronted with negative start index, so it would be a "light breaking" change. The concept would be that `"foo".AsSpan(-2, 2)` would return a `ReadOnlySpan<char>` pointing at the last two characters from the string (e.g. the `['o','o']`), and `"zot".AsSpan(-3,1)` -> a `ReadOnlySpan<char>` pointing at `['z']`. This would be tweaking code for [MemoryExtensions](https://github.com/dotnet/runtime/blob/943af3a6fe4300d1722d9ad6c9b371c568bc9fe4/src/libraries/System.Private.CoreLib/src/System/MemoryExtensions.cs#L106-L212) and the  [`ReadOnlySpan<T>` constructor](https://github.com/dotnet/runtime/blob/943af3a6fe4300d1722d9ad6c9b371c568bc9fe4/src/libraries/System.Private.CoreLib/src/System/ReadOnlySpan.cs#L73-L82)

**Comment by eiriktsarpalis** [comment]
Let's revisit this in .NET 9. We're very close to concluding .NET 8 development and making performance sensitive changes can be risky at this stage.

**Comment by IDisposable** [comment]
Makes perfect sense! I will put up a PR for just the additional unit tests as that would be nice :)

**Comment by IDisposable** [comment]
Extracted _just_ the unit test changes and a couple calculation hoists into PR https://github.com/dotnet/runtime/pull/90301

**Comment by IDisposable** [comment]
Sure!

**Pull request closed without merging**
