### PR TITLE
Fix incremental build R2R of System.Private.CoreLib

### PR DESCRIPTION
**Pull request by davidwrighton**
- Add dependency on newly compiled crossgen2 binaries
- Will force recompile of S.P.C if the ready to run compiler changes in addition to recompiling if S.P.C changes

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/crossgen-contrib

**Review by trylek — APPROVED** [review]
LGTM even though I must admit I'm still not clear on why we need the two variants for <code>CrossGen2DllFiles</code>, shouldn't they just gracefully collapse when <code>CrossDir</code> is empty?

**Comment by davidwrighton** [comment]
@trylek, I have little trust for msbuild and double slashes and whatnot. This is clear, explicit and I know exactly what its going to do.

**Review by trylek — APPROVED** [review]
Sure, fine with me, hitting issues like this all the time.

**Pull request merged**
