### PR TITLE
Issue 50442

### PR DESCRIPTION
**Pull request by WhiteBlackGoose**
`hDac` and `hDbi` to be freed at the end of the function

Fix #50442

### CODE REVIEW

**Comment by Happypig375** [comment]
@tommcdon Quack

**Comment by JulieLeeMSFT** [comment]
@sandreenko PTAL.

**Comment by sandreenko** [comment]
I am not an expert here, @tommcdon  could you please assign somebody from your team to review?

**Review by tommcdon — APPROVED** [review]

**Comment by tommcdon** [comment]
@hoyosjs

**Review by hoyosjs — CHANGES_REQUESTED** [review]
I am currently inclined to not take these changes. The problem is that - even though it's the right thing to free libraries - external tools could provide libraries in this method through the `ProvideLibrary` call on the passed in interface. If the calling tool keeps track of the handle and frees it, this change will break them with a double free. The contract was never explicit and as such we need to maintain this behavior compatibility. Particularly since this is more about the correctness, but we haven't gotten any feedback about this causing any particularly bad undesired behavior.

**Comment by hoyosjs** [comment]
cc: @dotnet/dotnet-diag

**Comment by WhiteBlackGoose** [comment]
@hoyosjs I see that sometimes these libraries are opened via `LoadLibraryW` and sometimes via the custom provider. Am I right that for the first case, we can safely free the library? If so, I'll just add a bool responsible for that, and `if (we_loaded_lib && hDac != NULL) ...`. What do you think?

**Comment by hoyosjs** [comment]
If you want to add the couple boolean checks, I'd say that's a contribution we could gladly accept as low risk :) I'd just use `BOOL` to be consistent wit the rest of the shim. Thanks @WhiteBlackGoose

**Comment by WhiteBlackGoose** [comment]
@hoyosjs could you check it now?

**Comment by WhiteBlackGoose** [comment]
@hoyosjs could you review?

**Comment by WhiteBlackGoose** [comment]
nobody wants to review a 17loc pr 😭

**Comment by hoyosjs** [comment]
Sorry @WhiteBlackGoose. I looked at this. This PR still has a bug as it's using the Free Library that doesn't match the LoadLibrary that gets retrieved from another library. Additionally, I need to verify that other paths don't cache the module handles. I am sorry, but right now I haven't gotten the time to do that, as there's been other pressing issues popping on my plate.

**Comment by WhiteBlackGoose** [comment]
Ohhh, right. I assume, you mean here
https://github.com/dotnet/runtime/blob/42489b8a7d626c07cc0e64672f05795dff8b3d56/src/coreclr/debug/shim/debugshim.cpp#L244-L254

Okay, I'll think how to free them for Unix

**Comment by tommcdon** [comment]
@WhiteBlackGoose  Thank you for working on this issue.  However, since we are working on fixing higher priority issues for .NET 6.0, I am closing this PR.  We will revisit this code change once we open the tree for .NET 7.

**Pull request closed without merging**
