### PR TITLE
Remove dead code in `System.Linq.Expressions`

### LINKED ISSUE #15440: Expression interpreter - Remove dead code
There's some unused code in a variety of places of the expression interpreter that can be removed to reduce code size.

### PR DESCRIPTION
**Pull request by deeprobin**
Closes #15440

I have tried my best to remove dead code.

There are of course still unnecessary casts but these do not change the size of the binary.
In my opinion you should refactor the whole code (but style changes are not welcome in the runtime, so I only removed the methods for now).

According to static code analysis tools (ReSharper), that was all the dead code.

/cc @bartdesmet

### CODE REVIEW

**Comment by cston** [comment]
@deeprobin, thanks for the contribution.

Unfortunately, we are only taking changes to this library that address significant bugs or regressions, or changes needed to continue shipping (see [README.md](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/README.md)).

I apologize, I should have closed https://github.com/dotnet/runtime/issues/15440 previously.

**Comment by deeprobin** [comment]
@cston 
Oh I thought this is one of the rare cases that something can be changed on System.Linq.Expressions.

I also noticed a typo there last time. Before I create an issue I'll ask you first.
Is this a change that would be made?

https://github.com/dotnet/runtime/blob/9047692595c6bef787e93883e92603388339c1c1/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/LabelTarget.cs#L35-L38

**Comment by cston** [comment]
Thanks for catching the typo @deeprobin.

If there is a scenario that is broken because of the label string typo, we'd considering fixing it. Otherwise, we'll probably leave the string as-is, since there may be existing code that depends on the current value.

**Comment by deeprobin** [comment]
I guess not (is it worth to create an issue anyway?).

I will close this PR. If we decide to dearchive `System.Linq.Expressions` later on, we can consider this PR again.

**Comment by cston** [comment]
> is it worth to create an issue anyway?

Perhaps wait until we have a scenario that is affected.

**Pull request closed without merging**
