### PR TITLE
Fix SendToRecvFrom_Datagram_UDP, organize SendReceive tests

### LINKED ISSUE #1712: Test: System.Net.Sockets.Tests.SendReceiveEap.SendToRecvFrom_Datagram_UDP(loopbackAddress: ::1) failed in CI
Failed test: System.Net.Sockets.Tests.SendReceiveEap.SendToRecvFrom_Datagram_UDP(loopbackAddress: ::1)
Configuration: OuterLoop_CentOS7.1_debug ([build#123](https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_centos7.1_debug/123/testReport/))

Message:
~~~
System.Net.Sockets.Tests.SendReceiveEap.SendToRecvFrom_Datagram_UDP(loopbackAddress: ::1) [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
~~~

Stack Trace:
~~~
/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_debug/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs(148,0): at System.Net.Sockets.Tests.SendReceive.<SendToRecvFrom_Datagram_UDP>d__17.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_centos7.1_debug/123/consoleText

### PR DESCRIPTION
**Pull request by antonfirsov**
1. Fix #1712 by moving those tests to the `NoParallelTests` collection. +also move them back to Inner Loop
2. Organize SendReceive tests into explicit semantical groups, by using nested classes. If it does not get accepted, I will redo 1. with the old naming scheme, but I believe it will hurt readability and maintainability a lot, since the total number of classes is now doubled because of `SendReceive_Socket_NonParallel<T>` and derived classes.

### CODE REVIEW

**Comment by antonfirsov** [comment]
This is how it looks in VS test explorer, the logic is immediately obvious IMO:
image

**Review by wfurt — APPROVED** [review]
LGTM.

**Comment by scalablecory** [comment]
marking no-merge as we're waiting for discussion

**Comment by scalablecory** [comment]
I don't know if there's enough organizational benefit versus using underscores here. I don't like the increased indent it adds to everything as you get deeper in the hierarchy.

**Comment by stephentoub** [comment]
@antonfirsov, based on offline discussions, should this be closed?  Seems like part (1) of the change is still relevant?

**Comment by antonfirsov** [comment]
I will reopen a new PR for (1) when I'll have the time.

**Pull request closed without merging**
