### PR TITLE
Share init-compiler with arcade

### PR DESCRIPTION
**Pull request by am11**
Upstream PR: https://github.com/dotnet/arcade/pull/7886.

### CODE REVIEW

**Comment by am11** [comment]
cc @jkoritzinsky, @akoeplinger, @janvorli, @lambdageek

**Comment by am11** [comment]
Failures are unrelated.
`Mono minijit Pri0 Runtime Tests Run OSX x64 release` xunit concurrency: #11063
`Libraries Test Run release coreclr windows x64 Debug` TLS1.3 on Windows: https://github.com/dotnet/runtime/issues/58927
`Build tvOSSimulator x64 Release AllSubsets_Mono` timeout while running tests: #58549
`CoreCLR Product Build OSX arm64 release` interrupted in the middle of the build: #34647 / #34472

**Comment by ViktorHofer** [comment]
@MattGal is the deprovisioning of the `"CoreCLR Product Build OSX arm64 release" leg the slow macOS machine issue? https://dev.azure.com/dnceng/public/_build/results?buildId=1358353&view=logs&jobId=a3584aa7-f6a0-5e90-05ca-4edce1db7c76&j=eb4db7b6-55d4-5d5f-e2fd-7706dfacdc48

**Review by jkoritzinsky — APPROVED** [review]

**Comment by MattGal** [comment]
> @MattGal is the deprovisioning of the `"CoreCLR Product Build OSX arm64 release" leg the slow macOS machine issue? https://dev.azure.com/dnceng/public/_build/results?buildId=1358353&view=logs&jobId=a3584aa7-f6a0-5e90-05ca-4edce1db7c76&j=eb4db7b6-55d4-5d5f-e2fd-7706dfacdc48

I don't think so, this is just the previous MacOS problem where sometimes the machine management has a bad day.  Anywhere you see cloning take a normal-ish amount of time and `"##[warning]Received request to deprovision: The request was cancelled by the remote provider."` that won't be the "slow mac" issue rather the classic "disconnected mac" issue.

**Comment by ViktorHofer** [comment]
> I don't think so, this is just the previous MacOS problem where sometimes the machine management has a bad day. Anywhere you see cloning take a normal-ish amount of time and "##[warning]Received request to deprovision: The request was cancelled by the remote provider." that won't be the "slow mac" issue rather the classic "disconnected mac" issue.

Thanks that matches my assumption. Do we have an open IcM for the deprovisioning issue? I remember that this issue plagued us in the past and as I have been seeing a few legs failing in the last two weeks but not any in the last months I wonder if this regressed again?

**Comment by MattGal** [comment]
> Thanks that matches my assumption. Do we have an open IcM for the deprovisioning issue? I remember that this issue plagued us in the past and as I have been seeing a few legs failing in the last two weeks but not any in the last months I wonder if this regressed again?

The problem never went away, and will always exist.  These are real macOS machines running in VMs on real physical hardware that occasionally loses its connection.  The problem just dropped to a percentage low enough that we stopped opening IcMs about it (by your own description, 1.5 times per week doesn't sound like much).  

If you feel this is important enough to bring up with the Mac Cloud team (I've forwarded this along to some folks from the team via email), reach out on the First responders channel with some examples and we can start the conversation.

**Comment by am11** [comment]
@jkoritzinsky, could you merge this? causing conflict with arcade PR.

**Pull request merged**
