### PR TITLE
[EventPipe] Fix reverse connection socket leaking to child processes.

### PR DESCRIPTION
**Pull request by hoyosjs**
Sockets were getting leaked upon accepting connections. This meant that child processes could cause fully terminated tracing sessions and other IPC connections alive, causing clients to wait for input indefinitely. This sets the CLOEXEC bits on the socket atomically upon accepting if the OS provides the capability, falling back to a best effort `fcntl` on systems like macOS and x866 Android emulators.

### CODE REVIEW

**Comment by am11** [comment]
@hoyosjs, current approach is that callers of eventpipe's cmake script (in coreclr and mono) provide the introspection-driven definitions. Should `accept4` check also live in the callers' configs?

**Comment by hoyosjs** [comment]
> @hoyosjs, current approach is that callers of eventpipe's cmake script (in coreclr and mono) provide the introspection-driven definitions. Should `accept4` check also live in the callers' configs?

I am somewhat torn. `src/coreclr`, `src/mono`, and `src/native/libs` always do the checks + configure_file in the same configure.cmake file. I left it that way and have the shared configure file as this makes it easy to find where it is and in this case they are properly shared in between the two runtimes. I don't know if moving the HAVE_ACCEPT4 check to `src/mono/cmake/configure.cmake` and a similar one for CoreCLR or creating separate ones for event pipe + doing the configure in tree would help much with discovery. @janvorli @akoeplinger any words of idiomatic CMake advice here?

**Comment by janvorli** [comment]
I would actually prefer having this local configure.cmake like @hoyosjs has done here and stop including the global configured header. It seems better to keep the detection close to the component that uses it. Unless I'm missing something, there is only `HAVE_INTTYPES_H` being used in the whole eventpipe stuff, so I'd copy the detection to the configure.cmake that was added here.

**Comment by hoyosjs** [comment]
@janvorli I saw that too, but I couldn't find anything that checks and sets `HAVE_INTTYPES_H`, so I ignored for now as this is intended for servicing.

**Comment by janvorli** [comment]
Ah, right, it is not checked for anywhere by cmake :-) It seems it is something that was inherited from autoconf.

**Comment by am11** [comment]
OK. One check requiring two new files, so I thought it can be pulled up in the existing config files.

> Unless I'm missing something, there is only `HAVE_INTTYPES_H` being used in the whole eventpipe stuff

I was actually looking at FEATURE_ flags used extensively in eventpipe, which we define in coreclr and mono configs. Secondly, eventpipe is not self-dependent component at all, changing the order of headers (what is included before the ep_ header on consumer side) can break the compilation.

**Review by noahfalk — APPROVED** [review]
LGTM

**Review by akoeplinger — APPROVED** [review]

**Review by lateralusX — APPROVED** [review]
I think the `HAVE_INTTYPES_H` can probably be removed, at least on the Mono side since we already include inttypes.h without guard in glib.h that will be included on all platforms, but that change could be done in a separate PR in main after this has merged.

Mono already include most of similar HAVE_XXX checks in https://github.com/dotnet/runtime/blob/main/src/mono/cmake/config.h.in and https://github.com/dotnet/runtime/blob/main/src/mono/cmake/configure.cmake, but if we want to add a new shared EventPipe config header instead of putting this into the same place as we currently have all other platform checks, I'm fine with that too.

**Pull request merged**
