### PR TITLE
Try again to get rid of checkout bundle for PRs

### PR DESCRIPTION
**Pull request by safern**
Now that the helix build agents were upgraded to 2.30 git version, checkout by commit ID should work. Let's try again to remove the checkout bundle. 

Note, this is a pure revert of: https://github.com/dotnet/runtime/commit/604660b37a0d416155a97cbd09c1edc101a1a1cb

@MattGal given the rollout was yesterday, is it OK to rely on it yet, or are queues still cleaning up old agents?

### CODE REVIEW

**Comment by safern** [comment]
I waited for some builds to start and now I committed: https://github.com/dotnet/runtime/commit/db1311e3547d0312f75cef1978364f21012f7784 and will see what the next builds checkout to.

**Review by trylek — APPROVED** [review]
Looking forward to finding out where it crashes next.

**Comment by MattGal** [comment]
> @MattGal given the rollout was yesterday, is it OK to rely on it yet, or are queues still cleaning up old agents? 

You're good to go; I've been working with the Autoscaler folks to make sure scale in brings down older machines first and everything we have right now was created long after the rollout.   I share Tomas' skepticism but fingers crossed either way.

**Comment by safern** [comment]
So far this looks promising. I looked at some of the checkouts. The build that actually started before I made the documentation change was, `CoreCLR Product Build Windows x64 Checked`. Here is the comparison of checkout commits in between different legs that started way later. You can look at the timestamps.

CoreCLR Product Build Windows x64 Checked
2021-01-14T19:25:06.0385225Z HEAD is now at 353d5e9ca Merge c30c3fc15b22f7714126160ccfb06c02cf7def8c into d8de9db79c2128153f680a5ab0e90b128b83455a

CoreCLR Product Build Linux x64 Release
2021-01-14T19:41:15.8667715Z HEAD is now at 353d5e9ca Merge c30c3fc15b22f7714126160ccfb06c02cf7def8c into d8de9db79c2128153f680a5ab0e90b128b83455a

CoreCLR Pri0 Common Tests
2021-01-14T20:29:58.0746816Z HEAD is now at 353d5e9ca Merge c30c3fc15b22f7714126160ccfb06c02cf7def8c into d8de9db79c2128153f680a5ab0e90b128b83455a

CoreCLR Pri0 Windows x64 Checked Tests: 2021-01-14T21:07:49.0944800Z HEAD is now at 353d5e9ca Merge c30c3fc15b22f7714126160ccfb06c02cf7def8c into d8de9db79c2128153f680a5ab0e90b128b83455a

It might be good if someone else takes a peek and agrees that we're good to merge.

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
