### PR TITLE
make sure socket is intialized before connecting TCPClient

### LINKED ISSUE #69493: TcpClient.Connect throws NRE if the Socket is cleared
After #67951, the [`Connect_DnsEndPoint_Success(mode: 1)`](https://github.com/dotnet/runtime/blob/a598ebb67973f03b1d6b3fd6c50f75bae3fe1c51/src/libraries/System.Net.Sockets/tests/FunctionalTests/TcpClientTest.cs#L221-L222) TcpClient outerloop test is failing with an NRE.
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs:line 130
   at System.Net.Sockets.Tests.TcpClientTest.Connect_DnsEndPoint_Success(Int32 mode) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TcpClientTest.cs:line 222
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.RuntimeMethodInfo.InvokeNonEmitUnsafe(Object obj, IntPtr* arguments, Span`1 argsForTemporaryMonoSupport, BindingFlags invokeAttr) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.CoreCLR.cs:line 387
```

The `_clientSocket` is only initialized during the ctor, so the `Connect` ends up failing if the user clears the `Client` socket manually.

cc: @wfurt

### PR DESCRIPTION
**Pull request by wfurt**
fixes #69493 
Socket can be explicitly set to `null` after created in constructor.

### CODE REVIEW

**Review by rzikm — APPROVED** [review]

**Comment by MihaZupan** [comment]
It looks like all `Connect(Async)` overloads suffer from the same issue. The test was just only doing this for one of the overloads.

**Comment by wfurt** [comment]
> It looks like all `Connect(Async)` overloads suffer from the same issue. The test was just only doing this for one of the overloads.
> For some reason, only one of the overloads supported this before your change?

yes, it seems like. 
I guess in most use cases people don't expect `Connect` to work after the `Socket` is explicitly removed. I think this would be easy to fix as well.

**Comment by MihaZupan** [comment]
Technically this makes it so you can never observe `TcpClient.Client` being null, even after you set it.
But that's probably a good thing - I don't see any value in carrying around an empty `TcpClient`.

**Review by MihaZupan — APPROVED** [review]

**Pull request merged**
