### PR TITLE
[manual] Merge release/7.0-staging into release/7.0

### PR DESCRIPTION
**Pull request by carlossanlop**
Merge commit.

### CODE REVIEW

**Comment by carlossanlop** [comment]
There are some CI failures in WASM and Mono that I am seeing for the first time. @lewing, @steveisok, @radical, @akoeplinger do they look familiar to you?:

---
Affected queues:
- Build Browser wasm Linux Release LibraryTests_EAT
- Build Browser wasm Linux Release LibraryTests_AOT
- Build Browser wasm windows Release LibraryTests_AOT

Failures:
```
##[error]resource ILLink.Substitutions.xml in FSharp.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a(5,6): error IL2040: (NETCORE_ENGINEERING_TELEMETRY=Build) FSharp.Core: Could not find embedded resource 'FSharpSignatureCompressedData.FSharp.Core' to remove in assembly 'FSharp.Core'.
```

```
##[error].packages/microsoft.net.illink.tasks/7.0.100-1.23211.1/build/Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: (NETCORE_ENGINEERING_TELEMETRY=Build) Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
```

---
Affected queues:
- Build windows x64 Release AllSubsets_Mono

Failure:
```
Failed to load app-local ICU: icuuc68.2.0.9.dll
    System.Globalization.Tests.IcuAppLocalTests.TestIcuAppLocal [FAIL]
      Exit code was -1073740791 but it should have been 42
```

---

Affected queues:
- Build Linux_bionic arm64 Release AllSubsets_Mono

Failure:
```
                   Starting:    System.Diagnostics.Process.Tests (parallel test collections = on, max threads = 8)
                       System.FormatException : The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
                       Stack Trace:
                         /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2906,0): at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
                         /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2836,0): at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
                         /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2643,0): at System.Convert.FromBase64String(String s)
                         /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(373,0): at System.Diagnostics.Tests.ProcessStartInfoTests.<>c.<ExecuteProcessAndReturnParsedOutput>b__9_0(String s)
                         /_/src/libraries/System.Linq/src/System/Linq/Select.SpeedOpt.cs(83,0): at System.Linq.Enumerable.SelectArrayIterator`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray()
                         /_/src/libraries/System.Linq/src/System/Linq/ToCollection.cs(17,0): at System.Linq.Enumerable.ToArray[String](IEnumerable`1 source)
                         /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(373,0): at System.Diagnostics.Tests.ProcessStartInfoTests.ExecuteProcessAndReturnParsedOutput(Dictionary`2 envVars, Func`1 processWork)
                         /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(289,0): at System.Diagnostics.Tests.ProcessStartInfoTests.EnvironmentGetEnvironmentVariablesIsCaseSensitive()
                         /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

----
Note: This failure in all-configurations is expected until we push to nuget the OOB packages generated last month:

```
artifacts\bin\testPackages\projects\Microsoft.Extensions.Hosting.WindowsServices\project.csproj(0,0): error NU1103: (NETCORE_ENGINEERING_TELEMETRY=Build) Unable to find a stable package Microsoft.Extensions.Logging.Abstractions with version (>= 7.0.1)
  - Found 1562 version(s) in dotnet7 [ Nearest version: 7.0.0-rtm.22511.4 ]
  - Found 112 version(s) in dotnet-public [ Nearest version: 8.0.0-preview.1.23110.8 ]
  - Found 1 version(s) in dotnet7-transport [ Nearest version: 7.0.0-rc.1.22426.10 ]
  - Found 0 version(s) in D:\a\_work\1\s\artifacts\packages\Debug\
  - Found 0 version(s) in richnav
  - Found 0 version(s) in darc-pub-dotnet-emsdk-b3cf128
  - Found 0 version(s) in dotnet-eng
  - Found 0 version(s) in dotnet-libraries
  - Found 0 version(s) in dotnet-tools
```

**Review by ViktorHofer — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Comment by lewing** [comment]
> There are some CI failures in WASM and Mono that I am seeing for the first time. @lewing, @steveisok, @radical, @akoeplinger do they look familiar to you?:
> 
> Affected queues:
> 
> * Build Browser wasm Linux Release LibraryTests_EAT
> * Build Browser wasm Linux Release LibraryTests_AOT
> * Build Browser wasm windows Release LibraryTests_AOT
> 
> Failures:
> 
> ```
> ##[error]resource ILLink.Substitutions.xml in FSharp.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a(5,6): error IL2040: (NETCORE_ENGINEERING_TELEMETRY=Build) FSharp.Core: Could not find embedded resource 'FSharpSignatureCompressedData.FSharp.Core' to remove in assembly 'FSharp.Core'.
> ```
> 
> ```
> ##[error].packages/microsoft.net.illink.tasks/7.0.100-1.23211.1/build/Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: (NETCORE_ENGINEERING_TELEMETRY=Build) Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.
> ```
> 
> Affected queues:
> 
> * Build windows x64 Release AllSubsets_Mono
> 
> Failure:
> 
> ```
> Failed to load app-local ICU: icuuc68.2.0.9.dll
>     System.Globalization.Tests.IcuAppLocalTests.TestIcuAppLocal [FAIL]
>       Exit code was -1073740791 but it should have been 42
> ```
> 
> Affected queues:
> 
> * Build Linux_bionic arm64 Release AllSubsets_Mono
> 
> Failure:
> 
> ```
>                    Starting:    System.Diagnostics.Process.Tests (parallel test collections = on, max threads = 8)
>                        System.FormatException : The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
>                        Stack Trace:
>                          /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2906,0): at System.Convert.FromBase64_ComputeResultLength(Char* inputPtr, Int32 inputLength)
>                          /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2836,0): at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
>                          /_/src/libraries/System.Private.CoreLib/src/System/Convert.cs(2643,0): at System.Convert.FromBase64String(String s)
>                          /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(373,0): at System.Diagnostics.Tests.ProcessStartInfoTests.<>c.<ExecuteProcessAndReturnParsedOutput>b__9_0(String s)
>                          /_/src/libraries/System.Linq/src/System/Linq/Select.SpeedOpt.cs(83,0): at System.Linq.Enumerable.SelectArrayIterator`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray()
>                          /_/src/libraries/System.Linq/src/System/Linq/ToCollection.cs(17,0): at System.Linq.Enumerable.ToArray[String](IEnumerable`1 source)
>                          /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(373,0): at System.Diagnostics.Tests.ProcessStartInfoTests.ExecuteProcessAndReturnParsedOutput(Dictionary`2 envVars, Func`1 processWork)
>                          /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(289,0): at System.Diagnostics.Tests.ProcessStartInfoTests.EnvironmentGetEnvironmentVariablesIsCaseSensitive()
>                          /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodInvoker.Mono.cs(33,0): at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
> ```
> 
> Note: This failure in all-configurations is expected until we push to nuget the OOB packages generated last month:
> 
> ```
> artifacts\bin\testPackages\projects\Microsoft.Extensions.Hosting.WindowsServices\project.csproj(0,0): error NU1103: (NETCORE_ENGINEERING_TELEMETRY=Build) Unable to find a stable package Microsoft.Extensions.Logging.Abstractions with version (>= 7.0.1)
>   - Found 1562 version(s) in dotnet7 [ Nearest version: 7.0.0-rtm.22511.4 ]
>   - Found 112 version(s) in dotnet-public [ Nearest version: 8.0.0-preview.1.23110.8 ]
>   - Found 1 version(s) in dotnet7-transport [ Nearest version: 7.0.0-rc.1.22426.10 ]
>   - Found 0 version(s) in D:\a\_work\1\s\artifacts\packages\Debug\
>   - Found 0 version(s) in richnav
>   - Found 0 version(s) in darc-pub-dotnet-emsdk-b3cf128
>   - Found 0 version(s) in dotnet-eng
>   - Found 0 version(s) in dotnet-libraries
>   - Found 0 version(s) in dotnet-tools
> ```

The wasm failures look trimming related and like something @sbomer or @vitek-karas  was aware of?

**Comment by mmitche** [comment]
> Note: This failure in all-configurations is expected until we push to nuget the OOB packages generated last month:

That will not happen till June.

**Comment by ViktorHofer** [comment]
@carlossanlop you can disable the failing validation meanwhile by adding the packages here: https://github.com/dotnet/runtime/blob/f0de0007ff590a3aa29ac58bd8b5a9327cfcd41f/src/libraries/testPackages/testPackages.proj#L31

**Comment by ViktorHofer** [comment]
Why does this error suddenly show up the merge PR?

**Comment by carlossanlop** [comment]
> Why does this error show up in the merge PR only?

All those errors showed up in the runtime-extra-platforms CI legs, which got executed automatically in this PR. I had not seen these legs being executed manually or automatically in any servicing PR from the past month.

**Comment by carlossanlop** [comment]
Failures in the latest run are known. I think it's good to merge.

  - https://github.com/dotnet/runtime/issues/80619
  - Some firefox wasm tests unexpectedly killed.

**Pull request merged**
