### PR TITLE
Rename long folder with instructions to fix long paths for git

### PR DESCRIPTION
**Pull request by carlossanlop**
I had to close [the original PR](https://github.com/dotnet/runtime/pull/221) because the branch had been created in the fork that got detached from the main repo after it became public.

Adding the same people from the other PR for review.

Fixes #173

Some notes:

- Windows does not allow `/`, `\` or `:` in file names (reserved characters), hence the way I had to word the message in the folder name.

- The maximum length of a folder or file name in Windows is 260 characters, unless the user is on Windows 10, on a version older than 1607, and manually enabled long path support, which allows 32,767 characters (documented [here](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later)). But since users need to opt in, the folder name will have to remain below 260 characters.

### CODE REVIEW

**Comment by carlossanlop** [comment]
@swaroop-sridhar - It would be great if you could address this separately by applying either one of these suggestions from the other PR:

- @stephentoub wrote:
> _Do we actually need this long path checked in? Or could whatever test needs it generate it?_

**Comment by jkotas** [comment]
> Do we actually need this long path checked in? Or could whatever test needs it generate it?

+1

**Review by swaroop-sridhar — CHANGES_REQUESTED** [review]
The test `installer/test/Assets/TestProjects/AppWithSubDirs/Program.cs`  needs to be updated with the new path.

**Comment by swaroop-sridhar** [comment]
> @swaroop-sridhar - It would be great if you could address this separately by applying either one of these suggestions from the other PR:

> > Do we actually need this long path checked in? Or could whatever test needs it generate it?
> 
> +1

I've put out PR https://github.com/dotnet/runtime/pull/373 to remove the long-name file from the repo, and generate it during test-run instead.

**Comment by swaroop-sridhar** [comment]
Thanks @carlossanlop

**Pull request closed without merging**
