### PR TITLE
Optimize loops in mini-llvm-cpp by splitting into two loops.

### PR DESCRIPTION
**Pull request by ghost**
This is a much better option than the original code, for the existence of "call" does not change as the loop iterates, which means by splitting into two loops, we can avoid having to check for "call" every iteration.

### CODE REVIEW

**Comment by jaykrell** [comment]
Is this really "much" better? It seems marginal.
If you change your mind, consider using the ternary operator to condense the prior form.

**Comment by pi1024e** [comment]
Indeed it is, because call is not expected to become null or non-null between iterations of the loop.

Not only that, but to the programmer, it makes sense too.

An if statement checks for a condition, but to the programmer, it also implies that WHENEVER this statement is reached, there is a possibility for a condition to be true and a possibility for it to NOT be true.

However, we already checked for call once already, and knowing it will not change, splitting into two loops reflects that better.

I understand programmers are extremely talented and smart. However, that doesn't mean they should have to figure out for themselves whether to expect call to change when getArgOperand is called between iterations before making any future changes, should the time come.

**Comment by pi1024e** [comment]
How do I know this? 

Because I had to do 30 minutes of research into LLVM to find out if it modifies the call variable or not to better understand its behavior. Nothing wrong with the people who wrote the original code; it can just be better.

**Comment by jaykrell** [comment]
The code ends up larger and larger is often slower (more to page in) and more to maintain.

This seems like a minor change and not clearly for the better (granted, you could say that about some of mine).

As well, the compiler can often hoist loop invariants.

As well, the processor is good at branch prediction -- these branches go the same way each time through the loop after the first.
Anyway, others can weigh in.

**Comment by pi1024e** [comment]
Good idea.

**Review by vargaz — APPROVED** [review]

**Comment by jaykrell** [comment]
This feels like not worthwhile source code bloat to me.

**Comment by lambdageek** [comment]
This is worse from a maintenance point of view: it now looks like 2 copy/pasted loops that need to be maintaned.  And as @jaykrell pointed out, the compiler and the CPU can probably do a pretty good job understanding that `call != nullptr` will resolve the same way on each iteration, so there's no performance benefit to manually hoisting the check out.  (And moreover it's unclear that this is perf-sensitive code).

I'm going to close the PR.  @pi1024e please feel free to comment if you disagree strongly and would like to discuss more.

**Pull request closed without merging**
