### PR TITLE
Update to latest System.CommandLine package

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Review by trylek — APPROVED** [review]
LGTM, thank you!

**Comment by am11** [comment]
@jkotas, now the performance has improved, should we revert 4731fdb6830141fb94fa8f3dbf81c437daa56ba9?

**Comment by trylek** [comment]
Considering we've been churning this bit for the last two and a half years, should we at least wait until System.CommandLine proceeds from the "beta" phase to some real shipping version?

**Comment by jkotas** [comment]
The System.CommandLine APIs have changed since 4731fdb6830141fb94fa8f3dbf81c437daa56ba9 so it would not be a simple revert.

It would nice to give it a try and measure the performance, give feedback to System.CommandLine team if it is still slowing down crossgen2 too much.

**Pull request merged**
