### PR TITLE
Add linker flags to add fixup data to PDBs (#58417)

### PR DESCRIPTION
**Pull request by agocke**
Fixup data can assist native debugging tools in providing more accurate data

(cherry picked from commit 4c814fa006c7178eaf4549fada27ec4a6f7d42dd)

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]

**Comment by carlossanlop** [comment]
@agocke please backport to 7.0-staging.

**Comment by carlossanlop** [comment]
BTW the bot ignored your ninja edit from 7.0 to release/7.0 😄

**Pull request merged**
