### PR TITLE
[release/6.0] Update a few dependencies

### PR DESCRIPTION
**Pull request by akoeplinger**
Fixes Component Governance warnings.

This is a backport of https://github.com/dotnet/runtime/pull/78710 with one twist: since we can't depend on Microsoft.Build v17.3 in release/6.0 we instead upgrade the transitive System.Drawing.Common version in all projects that reference Microsoft.Build directly.

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by akoeplinger** [comment]
@carlossanlop this is an infra-only change, the MacCatalyst CI failures are unrelated, it is good to be merged :)

**Comment by carlossanlop** [comment]
@mmitche any objections on getting this merged to the 6.0 branch?

**Comment by mmitche** [comment]
Wait for 6.0.14

**Comment by carlossanlop** [comment]
Branding has been done, so the branch is open to merge for 6.0.14.

**Pull request merged**
