### PR TITLE
[release/8.0-staging] [browser] Fix debugger support

### PR DESCRIPTION
**Pull request by maraf**
Migration of https://github.com/dotnet/runtime/pull/97213 (also https://github.com/dotnet/runtime/pull/100675 and partially https://github.com/dotnet/runtime/pull/104361)
Fixes https://github.com/dotnet/runtime/issues/102307

## Customer Impact
Fixes several customer reported issues regarding custom configuration name and ability to debug application. 
Regression from unification of Blazor SDK and former runtime Wasm SDK from .NET 8 cycle.

## Testing
Automated tests for all scenarios (build, publish, implicit and explicit values)

## Risk
Low

### CODE REVIEW

**Comment by maraf** [comment]
The WBT doesn't override `Microsoft.NET.Sdk.WebAssembly.Pack`, it uses `8.0.3` version

**Comment by maraf** [comment]
@radical Do you know if WBT should be working correctly on 8.0-staging branch? I see it's using workload from `8.0.3`. Example https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-98494-merge-1c96aa5beb9a48d38e/Workloads-NoWebcil-Wasm.Build.Tests.TestAppScenarios.DebugLevelTests/1/xharness-output/logs/DebugLevelTests_BuildWithDefaultLevel_Release_pipyiu2j_d0g/DebugLevelTests_BuildWithDefaultLevel_Release_pipyiu2j_d0g-build.binlog?helixlogtype=result

```
/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.3/Sdk/WasmApp.targets
```

**Comment by carlossanlop** [comment]
Friendly reminder that Monday March 11th is the Code Complete date for the April Release. If you want this change to be included in that release, please make sure to mark it as ready for review, get a code review sign-off, get a green CI (or confirm the issues are unrelated), and send an email to Tactics requesting approval. Otherwise, it will have to wait until the May Release. @maraf

**Comment by carlossanlop** [comment]
@maraf friendly reminder that code complete for the August Release is July 15th. If you want this fix to be included in that release, please merge this PR before that date.

**Comment by carlossanlop** [comment]
Friendly reminder that Monday July 15th is Code Complete day, that's the deadline to get this included in the August Release.

**Review by akoeplinger — APPROVED** [review]

**Comment by maraf** [comment]
@guardrex Since 8.0.9 the original behavior from .NET 7 will be restored, can you please update the docs for .NET 8

**Pull request merged**
