### PR TITLE
Use Type.GetProperty/GetField instead of GetMember.

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Following up from the discussion of https://github.com/dotnet/aspnetcore/issues/56139. This PR replaces `Type.GetMember` for `MemberInfo` resolution with `Type.GetField`/`GetProperty`.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
rt-sz doesn't report any improvement from this (https://github.com/MichalStrehovsky/rt-sz/issues/30), but also it doesn't test with the TodosApi app so I don't know if it would help there. rt-sz saw a small regression with the PR that added this: https://github.com/MichalStrehovsky/rt-sz/issues/28 but the regression was much smaller than what we saw with todosapi so I don't know :/

**Comment by MichalStrehovsky** [comment]
> rt-sz doesn't report any improvement from this ([MichalStrehovsky/rt-sz#30](https://github.com/MichalStrehovsky/rt-sz/issues/30)), but also it doesn't test with the TodosApi app so I don't know if it would help there. rt-sz saw a small regression with the PR that added this: [MichalStrehovsky/rt-sz#28](https://github.com/MichalStrehovsky/rt-sz/issues/28) but the regression was much smaller than what we saw with todosapi so I don't know :/

Ah, rt-sz wouldn't really capture improvements in changes like this. It doesn't pick up the new source generator. So a zero diff result is expected. We don't have a good way to measure impact of this in automation.

**Comment by eiriktsarpalis** [comment]
I wouldn't expect it to create a lot of impact size-wise. The main issue I would think is finding a good way to make the `AttributeProviderFactory` delegate trimmable if it isn't being invoked. Any suggestions?

**Comment by MichalStrehovsky** [comment]
> I wouldn't expect it to create a lot of impact size-wise. The main issue I would think is finding a good way to make the `AttributeProviderFactory` delegate trimmable if it isn't being invoked. Any suggestions?

Is the public surface are immutable (i.e. we cannot unseal `JsonPropertyInfoValues<T>` and change how `AttributeProviderFactory` property is implemented)?

**Comment by eiriktsarpalis** [comment]
You mean have the source generator override a virtual method? Would that make it more amenable to trimming?

**Comment by eiriktsarpalis** [comment]
The lambda is there so that attribute provider resolution can be done lazily. By making it eager we'd end up penalizing startup in all uses of the source generator.

**Comment by eiriktsarpalis** [comment]
@MichalStrehovsky I'm thinking we should merge this change regardless, given that it has first-class support from the linker.

**Review by MichalStrehovsky — APPROVED** [review]
This is an improvement from trimming perspective because we no longer root all members on the type (GetMembers is not intrinsically recognized by trimming and will root all members on the typeof). GetProperty/GetField will only root that single field/property.

**Pull request merged**
