### PR TITLE
Disable GetGCMemoryInfo on arm

### PR DESCRIPTION
**Pull request by hoyosjs**
Disables test blocking CI https://github.com/dotnet/runtime/issues/73247

### CODE REVIEW

**Review by mangod9 — APPROVED** [review]

**Comment by cshung** [comment]
@hoyosjs, Can we test this fix instead? https://github.com/dotnet/runtime/issues/73247

**Comment by hoyosjs** [comment]
Seems like a reasonable workaround - is it OK to not have accounting on win-x86?

**Comment by hoyosjs** [comment]
I'll leave this open and merge later if the other PR is not merged by the time CI is done. We can easily add the revert to your PR, but this issue is hitting at a high rate.

**Comment by cshung** [comment]
> Seems like a reasonable workaround - is it OK to not have accounting on win-x86?

Yes - `heap_hard_limit` is supported on 64 bit platforms only

**Comment by hoyosjs** [comment]
Ah, that'd be a proper fix altogether then.

**Comment by mangod9** [comment]
what in that change was causing the ArgumentOutOfRange exception though?

**Comment by cshung** [comment]
> what in that change was causing the ArgumentOutOfRange exception though?

The test case itself did it - and that was not a problem at all.

**Pull request merged**
