### PR TITLE
[wasm] Enable wasm relinking by default for Release config

### LINKED ISSUE #48349: Document wasm relinking functionality
Once https://github.com/dotnet/runtime/issues/43689 is resolved we should be able to relink a project for even greater size reductions savings, most notably linking out ICU. We should document this and probably stand up a test.

- [ ] public properties, items
- [ ] default settings

### PR DESCRIPTION
**Pull request by radical**
Set default value for `$(WasmBuildNative)` based on:

- If `$(WasmBuildNative)` is already set (eg. by user project) to `true`, then error if `EMSDK_PATH` is unset

- if unset, and`$(PublishTrimmed) == false`, then set to false
- if unset, and `$(Configuration) == "Release"`, then set to true

- If it is `$(WasmBuildNative) == true` after above steps, and emsdk is missing
   => then emit a warning, and set it to `false`

Fixes: https://github.com/dotnet/runtime/issues/48349

### CODE REVIEW

**Comment by radical** [comment]
Test can be added once https://github.com/dotnet/runtime/pull/47683 is merged.

**Comment by lewing** [comment]
A couple of thoughts.

- There is little reason to run this step if PublishTrimmed isn't true.
- If EMSDK isn't installed
  - Error in anything other than interpreter only mode
  - Warning in interpreter mode
  - Error in a couple of other cases

**Comment by vargaz** [comment]
Also, native linking is very slow, so making it the default will hurt user experience.

**Comment by lewing** [comment]
In interpreter mode we don't require it unless the default icall/pinvoke tables are missing symbols (extra symbols are fine) and that will only happen if we've added references to native assets in which case we'll need to relink to include them and add to the tables.  And ideally we we only do that if the native assets change.

**Comment by marek-safar** [comment]
I don't think there is much concern for the release/deploy configuration to be slow because it runs more optimizations.

**Comment by radical** [comment]
> * There is little reason to run this step if PublishTrimmed isn't true.
👍 

> * If EMSDK isn't installed
>   
>   * Error in anything other than interpreter only mode
>   * Warning in interpreter mode

What do you mean by "interpreter mode"? `$(AOTMode)`?

>   * Error in a couple of other cases

Could you enumerate those, or at least the ones that we definitely want in this PR?

**Review by lewing — COMMENTED** [review]
Needs to be false by default if emsdk is not present

**Comment by radical** [comment]
> Needs to be false by default if emsdk is not present

1. If `$(WasmBuildNative)` is already set to `true`, then error if no emsdk?
2. If not set at all, and we want to set it to `true` based on other conditions
    => then set to false if emsdk is not present, and a warning?

Something like this? I'm guessing that we would want to avoid silently skipping relinking, because `EMSDK_PATH` wasn't set, but maybe was expected.

**Comment by lewing** [comment]
yes

**Review by lewing — APPROVED** [review]
The logic looks good and I'm ok with landing this as is to let packages flow to aspnetcore but let's not close #48349 yet.  The messages need some work and we will need a follow up that abstracts the conditional logic in a slightly different way.

**Comment by radical** [comment]
> The logic looks good and I'm ok with landing this as is to let packages flow to aspnetcore but let's not close #48349 yet. The messages need some work and we will need a follow up that abstracts the conditional logic in a slightly different way.

Yeah, the conditional logic will get simplified, but there are bunch of PRs in flight right now, after which it should be sorted out.

re:messages, yes!!

**Comment by trylek** [comment]
@radical - I think your change has broken the <code>dotnet-linker-tests</code> pipeline,

https://dev.azure.com/dnceng/public/_build?definitionId=861

All jobs after your check-in now show:

<pre>
Job build_Browser_wasm_release_Runtime_Release depends on unknown job mono_browser_offsets.
</pre>

Could you please take a look?

Cc @directhex who is still the test cop AFAIK, otherwise he'll forward as appropriate.

Cc @dotnet/runtime-infrastructure

**Comment by radical** [comment]
@trylek working on a fix now, in https://github.com/dotnet/runtime/pull/49774

**Pull request merged**
