### PR TITLE
Delete dotnet-deb-tool.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Once dotnet/installer#9631 is merged, no one will be using dotnet-deb-tool. So, we can delete it from dotnet/runtime.

### CODE REVIEW

**Review by trylek — APPROVED** [review]
LGTM, thank you!

**Comment by trylek** [comment]
Hmm, what is the "markdownlint / lint" leg about? This is the first time I'm seeing it :-). I don't recall noticing its introduction as part of your change.

**Comment by jkoritzinsky** [comment]
That looks like it just got enabled. It's unrelated to my change. I started a thread on the Infrastructure teams channel about it.

**Comment by ViktorHofer** [comment]
@danmosemsft @Anipik seems like the mardownlint leg is failing because of a conflict when the PR was merged (library-servicing.md)

**Review by ViktorHofer — APPROVED** [review]
🎉🎉🎉

**Review by stephentoub — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@Anipik @dotnet/dnceng the iOS and Android queues were timing out.

**Comment by jkoritzinsky** [comment]
This was supposed to wait for the installer PR to merge, but I think it's fine. (That one is supposed to be merged today.)

**Comment by chcosta** [comment]
@ilyas1974 , is the timeout Viktor referred to a known / tracked issue?

**Comment by ilyas1974** [comment]
We started noticing a backup in the Android queue yesterday. It has to do with the volume of work being sent to the on premise resources (which are finite). We do have additional Android devices on order but no current ETA on when they will arrive. You can follow the status of that work in https://github.com/dotnet/core-eng/issues/11781.

**Pull request merged**
