### PR TITLE
[ObjWriter/Mach-O] Mark non-global symbols as .private_extern to match ELF

### PR DESCRIPTION
**Pull request by filipnavara**
Extracted from #106224

`.private_extern` is the logical equivalent of `.hidden`+`.global` in ELF. We already emit those flags in ELF, so do it in Mach-O too.

Documentation for `.private_extern`:
> It's used to mark symbols with limited visibility. When the file is fed to the static linker, it clears the N_EXT bit for each symbol with the N_PEXT bit set. The ld option -keep_private_externs turns off this behavior.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Cc @ivanpovazan @dotnet/jit-contrib @dotnet/ilc-contrib for Apple-specific ObjWriter change. Looks reasonable to me but don't know much about Apple stuff.

**Review by jkotas — APPROVED** [review]
LGTM

@filipnavara I assume that we do not need to backport this fix to .NET 9. Correct?

**Comment by filipnavara** [comment]
> I assume that we do not need to backport this fix to .NET 9. Correct?

Correct. I don't see a need to backport it at this point.

**Review by ivanpovazan — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
