### PR TITLE
Use jitstd::sort instead of qsort in jit and gcinfo

### PR DESCRIPTION
**Pull request by davidwrighton**
Current use of qsort interferes with cross compilation.

The qsort algorithm is quite different between Windows and Linux, thus causing cross compilation failures
This replaces qsort with the use of jitstd::sort which provides a sort which is consistent between all platforms. (Particularly in Windows where CFG has costs for function pointer usage.) With a homegrown sort performance test, there is about 15-30% performance win with this sort over qsort. (However as these tests do not resemble the behavior of these sorts in the JIT I do not believe they are spectacularly relevant.)

There is a size cost of about 4KB-6KB for the templatized routines. I was unable to measure a performance difference for the JIT itself. (Crossgen is very slightly faster in my testing with the change, but I do not believe the difference is statistically meaningful.)

This PR is an alternative to #43847

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
I see that the text of this PR is almost copy-paste with the alternative PR. Did you re-measure the perf, and it came out the same as the alternative?

**Comment by davidwrighton** [comment]
@BruceForstall, yes, I measured it again, and the performance difference was still negligible. It does look like the size of the jitstd::sort based implementation is slightly larger, but not by much.

**Review by BruceForstall — APPROVED** [review]
LGTM.

I think I prefer this versus the drop-in qsort replacement alternative, simply because it uses a sort we're already using, and fixing on one seems like a good idea.

**Review by AndyAyersMS — APPROVED** [review]
Consolidating on one sort is good. Thanks.

I think the only sort that matters for jit TP is the lcl var table one, which was already using `jitstd::sort`.

**Pull request merged**
