### PR TITLE
Bump main pre-release version iteration to preview4

### PR DESCRIPTION
**Pull request by carlossanlop**
Must only merge after the snap is done. **Edit**: The snap has been done: [release/8.0-preview3](https://github.com/dotnet/runtime/commits/release/8.0-preview3)

cc @radical @lewing @steveisok in case we see any unexpected wasm/mono issues due to version bumping.

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by steveisok** [comment]
the WBT failure is:

```
Wasm.Build.NativeRebuild.Tests.FlagsChangeRebuildTests.ExtraEmccFlagsSetButNoRealChange(buildArgs: BuildArgs { ProjectName = placeholder, Config = Release, AOT = False, ProjectFileContents = placeholder, ExtraBuildArgs =  }, extraCFlags: "/p:EmccExtraCFlags=-g", extraLDFlags: "", host: Chrome, id: "xzggs025.tve") [FAIL]
      System.AggregateException : One or more errors occurred. (One or more errors occurred. (A task was canceled.)) (The process cannot access the file '\\?\C:\helix\work\workitem\e\wbt\xzggs025.tve' because it is being used by another process.)
      ---- System.AggregateException : One or more errors occurred. (A task was canceled.)
      -------- System.Threading.Tasks.TaskCanceledException : A task was canceled.
      ---- System.IO.IOException : The process cannot access the file '\\?\C:\helix\work\workitem\e\wbt\xzggs025.tve' because it is being used by another process.
```
@lewing @radical any ideas?

**Comment by carlossanlop** [comment]
@steveisok is that a new failure? If you think it is not related to this change, I can open an issue to track it separately, so I can unblock this PR.

**Comment by steveisok** [comment]
> @steveisok is that a new failure? If you think it is not related to this change, I can open an issue to track it separately, so I can unblock this PR. (From that error message you shared, it does not look very related to this change).

I'm not sure if it's a new failure. I don't think the version bump is causing this, so can you make a known issue out of it?

**Comment by carlossanlop** [comment]
CI failures:
- Existing: https://github.com/dotnet/runtime/issues/73961
- Execution timeout. Affected queues:
  - `browser-wasm windows Release LibraryTests_AOT`
  - `browser-wasm windows Release Mono_DebuggerTests_chrome`
  - I'll open an issue if I see this happen more often.
- I also opened: https://github.com/dotnet/runtime/issues/83752

**Pull request merged**
