### PR TITLE
Improve regex tests for offset start cases

### PR DESCRIPTION
**Pull request by danmoseley**
Fill some test holes suggested by https://github.com/dotnet/runtime/issues/69949#issuecomment-1140388943.

### CODE REVIEW

**Comment by stephentoub** [comment]
> Fill some test holes

What wasn't being tested?

**Comment by danmoseley** [comment]
Several of the cases I added apparently don't exist; the rest for completeness.

For the `\G` cases: start offset from the start of the string, but before the match start; such that both the (string, int) and(string, int int) methods are exercised. 

For the other anchor cases, similar, using different kinds of anchors, showing the different behaviors of the two methods, and with added asserts to eg verify the index returned on the match in these cases.

I don't believe we hold regex tests to the bar "demonstrably exercising unique code paths" as that's rather hard to demonstrate and less useful when refactoring, but something more like "not self evidently equivalent to an existing case in any plausible implementation and/or demonstrates completeness to the reader"

**Comment by stephentoub** [comment]
> I don't believe we hold regex tests to the bar "demonstrably exercising unique code paths" as that's rather hard to demonstrate and less useful when refactoring, but something more like "not self evidently equivalent to an existing case across all plausible implementations and/or demonstrates completeness to the reader"

I'm not arguing about adding tests. You said "test hole", which means a demonstrable gap in what's being tested, and you linked to a comment suggesting some things clearly missing tests but without saying exactly what, so I asked what that gap was.

**Comment by danmoseley** [comment]
> I'm not arguing about adding tests. You said "test hole", which means a demonstrable gap in what's being tested, and you linked to a comment suggesting some things clearly missing tests but without saying exactly what, so I asked what that gap was.

Gotcha, my apologies if this appeared argumentative, I only intended to be philosophical 🙂

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
