### PR TITLE
add missing analyzers to the Microsoft.extensions.Logging.Abstractions.

### LINKED ISSUE #55296: Latest Microsoft.Extensions.Logging.Abstractions package do not contain source generators
Found in 6.0.0-preview.7.21352.11. The logging abstractions package is missing the analyzers folder. The bug was likely introduced between these commits: https://github.com/dotnet/runtime/compare/c1e5fcc33e65080c027ca6f7fceebcbd473b4654...e8572d3e5d23e624dac4f3744c745885a6d3addb

### PR DESCRIPTION
**Pull request by Anipik**
Fixes https://github.com/dotnet/runtime/issues/55296

### CODE REVIEW

**Comment by Anipik** [comment]
Screen Shot 2021-07-07 at 5 30 44 PM

**Review by eerhardt — APPROVED** [review]
Thanks for the quick turnaround!

is there any way we can add package validation to ensure this doesn’t happen again?

**Comment by Anipik** [comment]
> is there any way we can add package validation to ensure this doesn’t happen again?

we can write a small target to verify the packageFiles contain the analyzer files if we have gen folder in the project. I think that should be good enough.

**Comment by pranavkm** [comment]
> we can write a small target to verify the packageFiles contain the analyzer files

For this particular case, we would find out as soon as there's an arcade build that updates AspNetCore. Not saying you have to use it as a validation tool, but if packaging changes are rare, it might be ok not to spend too much time trying to validate this.

**Comment by ericstj** [comment]
This was previously included with https://github.com/dotnet/runtime/blob/f57b6e7308e9db32e63488aa5e8f938934f54cf0/src/libraries/Directory.Build.targets#L286, did you find why that broke?

**Comment by Anipik** [comment]
```BeforePack``` is not hooked into ```dotnet pack```, i kept it for old pkgproj support. we can hook the old support to ```packDependsOn``` and we can remove one of the occurrences.

**Comment by ericstj** [comment]
> `BeforePack` is not hooked into `dotnet pack`

It should be hooked into dotnet pack:
https://github.com/NuGet/NuGet.Client/blob/e0e66a44e8b0aacb8e3a88fd0d1f991fb8475d3c/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L42

**Pull request merged**
