### PR TITLE
Microsoft.NETCore.Platforms: fix graph not being updated on pack.

### LINKED ISSUE #82125: generation of RID graph no longer works
I was trying add new RID (ubuntu 23.04). I added entry to `runtimeGroups.props` in `Microsoft.NETCore.Platforms` and run `dotnet.sh pack  /p:UpdateRuntimeFiles=true` as usually. 
But no updates were made to `runtime.json` and `runtime.compatibility.json`
Release/6.0 branch still works but I experienced same issue with release/7.0.

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/dotnet/runtime/issues/82125.

Regressed in https://github.com/dotnet/runtime/pull/76068.

@ViktorHofer @wfurt ptal.

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]
Thanks for the quick fix

**Comment by ViktorHofer** [comment]
Can you please check is 6.0 and 7.0 are also impacted?

**Comment by tmds** [comment]
Yes, the issue is also on the 7.0 branch. This change can be backported to it.

I need to take a closer look at what happens on the 6.0 branch, some changes were made as well.
In the issue @wfurt mentioned the update works.

**Pull request merged**
