### PR TITLE
Assert if we find undefined use during interval validation

### LINKED ISSUE #45238: Investigate the encounters of "undefined use at" in register allocator
In JITDump, I occasionally see "LocalVar V09: undefined use at 1281" printed that comes from [this line](https://github.com/dotnet/runtime/blob/f48c8d581b584495079fa5f2b2789ef48546edd9/src/coreclr/src/jit/lsrabuild.cpp#L2637). Investigate what is causing it. I am not sure if it happens only for EHWriteThru or not but ideally, we should `assert()` for such cases.

Here is a repro:

```
set COMPlus_JitDump=Drive
set COMPlus_EnableEHWriteThru=1
set COMPlus_TieredCompilation=0

CoreRun.exe D:\git\jitutils\bin\pmi.dll DRIVEALL-QUIET %CORE_ROOT%\System.Text.Encoding.Extensions.dll

```

### PR DESCRIPTION
**Pull request by kunalspathak**
During `validateIntervals()`, we keep track of definition and lastuse of RefPositions. After we encounter `lastUse` RefPosition, we do not expect to see any other `RefPosition` with "use". If we see it, we were simply logging it under JitDump. The only scenario in which this can happen is the "use" RefPosition is 

Earlier, whenever we find a "use" refposition without definition, we were simply logging it under JitDump. It should only happen if the "use" refposition is in a [different block](https://github.com/dotnet/runtime/blob/598c2dae8843a523e2f73271b268aaab58360a2e/src/coreclr/jit/lsrabuild.cpp#L461-L464) then the previous "lastuse" refposition. I fixed it and enabled an assert when this doesn't happen.

Fixes: https://github.com/dotnet/runtime/issues/45238

### CODE REVIEW

**Comment by kunalspathak** [comment]
coreclr-jitstressregs failures are related to https://github.com/dotnet/runtime/issues/30724 
libraries-jitstressregs failures are related to https://github.com/dotnet/runtime/issues/56237

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]

**Comment by JulieLeeMSFT** [comment]
@kunalspathak does this closes #56237 ?

**Comment by kunalspathak** [comment]
> @kunalspathak does this close #56237 ?

No @JulieLeeMSFT - This PR is unrelated to #56237.

**Pull request merged**
