### PR TITLE
Improve perf of CredentialCache.GetCredential

### LINKED ISSUE #101991: [Perf] Linux/x64: 1 Regression on 4/30/2024 10:57:18 AM
### Run Information

Name | Value
-- | --
Architecture | x64
OS | ubuntu 22.04
Queue | TigerUbuntu
Baseline | [aab8803eac4111a711b6eb65242ee8a5b14fa411](https://github.com/dotnet/runtime/commit/aab8803eac4111a711b6eb65242ee8a5b14fa411)
Compare | [017593d90781d797df8b2241f6d1f83c236c442b](https://github.com/dotnet/runtime/commit/017593d90781d797df8b2241f6d1f83c236c442b)
Diff | [Diff](https://github.com/dotnet/runtime/compare/aab8803eac4111a711b6eb65242ee8a5b14fa411...017593d90781d797df8b2241f6d1f83c236c442b)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Net.Primitives.Tests.CredentialCacheTests

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[GetCredential_Uri - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 22.04/System.Net.Primitives.Tests.CredentialCacheTests.GetCredential_Uri(uriString%3a%20%22http%3a%2f%2fname5%22%2c%20uriCount%3a%2010).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Net.Primitives/CredentialCacheTests.cs#L32-#L41>)</li><li>[ADX - Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACo1UXW/TMBR9R+I/WHtJAlkb2rKhSkF0ZYwBnUpXnhCa3OSuuSi2o+ubrpkQvx07nbovCeUlso/POff46jozkLYmUKDZvvgjbgogECc1lvkCKiPSVAS5YQ3cp1ozKgges05I6qxoeQTXtl+AzG1fSdRPiBPKCmTI2FUTqEUYbI9GQSwCScotoj17CZYvpALv+SG4bCyD6l0A9+aEChk3YHueY3tTgtzlRllOZVbADjwDvsevfhCGNeElE+r1WBwUzNW439fO/+1BLNzR1Lh7jcWbJLoPvKj11OhrXNckGY22P4OpURWW7W5mcgh+ifSvCBgdPQ9e/k/poK+o8zuFwozMAwFaUBU34TPhxHDUgXZu7Ldyo9oWd+F/sad6jRq6cL1xF97MaNMxrqeeawaqCNy3i2S+Nsum6hR4XjQWM1nOySjjka7Cz82KMD8rzUqWeNtiXWSLwaJrhdNtBW5+3Vj62X487e0IAi1Ndbd6/HKWTnbJUlXivcglg3+F4SAZjA6T4WFyvEzejZOj8WDUGwyGw9Hx6HWSjJPEl7C1UpLwFoSk9ZWS27A19Ali8SoSq+ZJhXj/+mI/yt9rqMH5VGR+u5f7jLwAW5eckkudhw9ussMnGyC5dk7DKBatlTdOPxGCzstmj/hmtRsfmdwZkPB3zApJLG6QCxFa1zyw6V4Ti21mylrp9GmmZofbdBfCERm5hDT46Frn/jfN3dZLRKht5DFblcip3IKN/gFeNw7jEQUAAA==>)</li></ul> | 308.46 ns | 358.40 ns | 1.16 | 0.02 | False | | |

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_07_2024/refs/heads/main_x64_ubuntu%2022.04_Regression/System.Net.Primitives.Tests.CredentialCacheTests.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Net.Primitives.Tests.CredentialCacheTests*'
```

<details>

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### LINKED ISSUE #102281: [Perf] Linux/arm64: 2 Regressions on 4/30/2024 1:50:24 PM
### Run Information

Name | Value
-- | --
Architecture | arm64
OS | ubuntu 22.04
Queue | AmpereUbuntu
Baseline | [f9207e6c85bb6aebd9e7af7504fd3db28b32d058](https://github.com/dotnet/runtime/commit/f9207e6c85bb6aebd9e7af7504fd3db28b32d058)
Compare | [017593d90781d797df8b2241f6d1f83c236c442b](https://github.com/dotnet/runtime/commit/017593d90781d797df8b2241f6d1f83c236c442b)
Diff | [Diff](https://github.com/dotnet/runtime/compare/f9207e6c85bb6aebd9e7af7504fd3db28b32d058...017593d90781d797df8b2241f6d1f83c236c442b)
Configs | CompilationMode:tiered, LLVM:true, MonoAOT:true, MonoInterpreter:false, RunKind:micro_mono

### Regressions in System.Net.Primitives.Tests.CredentialCacheTests

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio
-- | -- | -- | -- | -- | -- | -- | -- | --
|<ul><li>[GetCredential_Uri - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 22.04_LLVM=true_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono/System.Net.Primitives.Tests.CredentialCacheTests.GetCredential_Uri(uriString%3a%20%22http%3a%2f%2fname5%22%2c%20uriCount%3a%2010).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Net.Primitives/CredentialCacheTests.cs#L32-#L41>)</li><li>[ADX - Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACpVUXW/TQBB8R+I/nPpiB9zETZtSIhmRhlIKTSlp4AWh6mpv40W+O2tv3cYV4rdz54T0Syrmxbobz8zOnXc9AWkrAgWa7bNf4joHArFfYZFNoTQiSUSQGdbAPao0o4LgPmufpE7zhkdwaXs5yMz2lET9gDiiNEeGlF01gVqEwWJ3J4hEIEm5RWfNnoHlE6nAe74NzmrLoLonwN1TQoWMV2C7nmO7Y4LM5UZZjGWawxI8BL7Fz78ShhXhGRPq+VBs5MzlsNfTzn+wEQn3amzcuYZiK+7cBp5Wemz0Jc4rkoxG2+/B2KgSi2Y3MRkEP0TyWwSMjp4Fz59SHh9/m/ylUwVPkydGm9Hn2X/xjzQDlQTuudJdysL+Q+igT6izlUBhSuZcObM7KrSgSq7DR+qR4U4L2pGxx8WVar5+G/5He6DnqKEN93RuZnXZjprXFlNZnJJRxiNthR/qC8LssDAXssCbBmsjm/anbSscLEpwTe161Tf8/RFo+hJoZsrV6v44zZzsjKUqxRuRSQY/mmE/7u9sxtub8atZ/HoY7w0H/e7WYHd3sLP3Mo6HcexL2EopSXgDQtL8XMlF2Bj6BJF40REX9YMK0XokI99JXyqowPmUZH66cX5EnoKtCk7Ipc7COydZ4qMrIDl3TtudSDRW3jh5Twg6K+o14i+r2fjI5N4BCX/GNJfE4ho5F6F1lwc2WWsisUhNUSmdPMxUL3GbLEM4IiMXkATv3NW5n1C92nqJCLXteMyWBXIiF2A7fwBlo4HUJgUAAA==>)</li></ul> | 1.72 μs | 1.80 μs | 1.05 | 0.09 | False | | |
|<ul><li>[GetCredential_Uri - Duration of single invocation](<https://pvscmdupload.z22.web.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 22.04_LLVM=true_MonoAOT=true_MonoInterpreter=false_RunKind=micro_mono/System.Net.Primitives.Tests.CredentialCacheTests.GetCredential_Uri(uriString%3a%20%22http%3a%2f%2fnotfound%22%2c%20uriCount%3a%2010).html>)</li><li>📝 - [Benchmark Source](<https://github.com/dotnet/performance/blob/main/src/benchmarks/micro/libraries/System.Net.Primitives/CredentialCacheTests.cs#L32-#L41>)</li><li>[ADX - Test Multi Config Graph](<https://dataexplorer.azure.com/clusters/dotnetperf.westus/databases/PerformanceData?query=H4sIAAAAAAAACpWUb2/TMBDG3yPxHay9SQpZG7rCWKUgujLGYB2jK7xBaPKSa3MotqPzZWsmxGfHTkv3TxrhTWQ//j13Z+suE5C2IlCg2T75Ja5yIBD7FRbZFEojkkQEmWEN3KNKMyoI7lL7JHWaNxzB3PZykJntKYn6HjiiNEeGlF02gVqEwfLVIIhEIEm5RWdDz8DyiVTgY74NzmrLoLonwN1TQoWMl2C7nrHdMUHm6kZZjGWaw0o8BL7Rz78ShhXhGRPqxVBs5czlsNfThuem0tlWJNzp2C15KF7EnZuap5UeGz3HRUWS0Wj7PRgbVWLR7CYmg+CHSH6LgNHhWfD0Mefx8bfJX5wqeByeGG1Gn2f/xR9pBioJ3Hftm8vC/sPopE+os7VBYUrmXLlgt1xoQZVchw/cI8OdFtiRscfFpWoaoA3/0R7oBWpow54uzKwu26F5bTGVxSkZZbzS1vihviDMDgtzIQu8brQ2tml/2jbDwbIE19euXX3P352Cpi+BZqZcr+5O1MzZzliqUrwRmWTw0xn24/5gO97Zjndn8d4wfj182e/29waDwW78PI6HcexT2EopSXgNQtLiXMll2AT0FUTiWUdc1PcyRJupjHwnfamgAhenJPPTTfQDeAq2KjghP2LhrZus9NElkFy4SDudSDShfODkPSHorKg3in+sZuNLJncGJPwd01wSiyvkXITWPR7YZOOJxDI1RaV0cr+meqXbZFWEAxm5gCR4557O/Yfq9dZbRKhtx2u2LJATuQTb+QPoxea2KQUAAA==>)</li></ul> | 1.41 μs | 1.51 μs | 1.07 | 0.05 | False | | |

graph
graph
[Test Report](<https://pvscmdupload.z22.web.core.windows.net/autofilereport/autofilereports/05_07_2024/refs/heads/main_arm64_ubuntu%2022.04_LLVM%3Dtrue_MonoAOT%3Dtrue_MonoInterpreter%3Dfalse_RunKind%3Dmicro_mono_Regression/System.Net.Primitives.Tests.CredentialCacheTests.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

<details>
   <summary>Repro Steps</summary>

#### Prerequisites (Files either built locally (with build.(sh/cmd) or downloaded from payload above (if same system setup) (in this order))
- Libraries build extracted to `runtime/artifacts` or build instructions: [Libraries README](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/libraries/README.md) args: `-subset libs+libs.tests -rc release -configuration Release -arch $RunArch -framework net8.0`
- CoreCLR product build extracted to `runtime/artifacts/bin/coreclr/$RunOS.$RunArch.Release`, build instructions: [CoreCLR README](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/coreclr/README.md) args: `-subset clr+libs -rc release -configuration Release -arch $RunArch -framework net8.0`
- AOT MONO build extracted to `runtime/artifacts/bin/mono/$RunOS.$RunArch.Release`, build instructions: [MONO README](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/mono/README.md) args: `-arch $RunArch -os $RunOS -s mono+libs+host+packs -c Release /p:CrossBuild=false /p:MonoLLVMUseCxx11Abi=false`
- Dotnet SDK installed for dotnet commands
- Running commands from the runtime folder

Linux
```cmd
# Set $RunDir to the runtime directory
RunDir=`pwd`

# Set the OS, arch, and OSId
RunOS='linux'
RunOSId='linux'
RunArch='x64'

# Create aot directory 
mkdir -p $RunDir/artifacts/bin/aot/sgen
mkdir -p $RunDir/artifacts/bin/aot/pack
cp -r $RunDir/artifacts/obj/mono/$RunOS.$RunArch.Release/mono/* $RunDir/artifacts/bin/aot/sgen
cp -r $RunDir/artifacts/bin/microsoft.netcore.app.runtime.$RunOS-$RunArch/Release/* $RunDir/artifacts/bin/aot/pack

# Create Core Root
$RunDir/src/tests/build.sh release $RunArch generatelayoutonly /p:LibrariesConfiguration=Release

# Clone performance 
git clone --branch main --depth 1 --quiet https://github.com/dotnet/performance.git $RunDir/performance

# One line run:
python3 $RunDir/performance/scripts/benchmarks_ci.py --csproj $RunDir/performance/src/benchmarks/micro/MicroBenchmarks.csproj --incremental no --architecture $RunArch -f net8.0 --filter 'System.Net.Primitives.Tests.CredentialCacheTests*' --bdn-artifacts $RunDir/artifacts/BenchmarkDotNet.Artifacts --bdn-arguments="--anyCategories Libraries Runtime  --category-exclusion-filter NoAOT NoWASM --runtimes monoaotllvm --aotcompilerpath $RunDir/artifacts/bin/aot/sgen/mini/mono-sgen --customruntimepack $RunDir/artifacts/bin/aot/pack --aotcompilermode llvm --logBuildOutput --generateBinLog"

# Individual Commands:
# Restore 
dotnet restore $RunDir/performance/src/benchmarks/micro/MicroBenchmarks.csproj --packages $RunDir/performance/artifacts/packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1

# Build
dotnet build $RunDir/performance/src/benchmarks/micro/MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore /p:NuGetPackageRoot=$RunDir/performance/artifacts/packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1

# Run
dotnet run --project $RunDir/performance/src/benchmarks/micro/MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore --no-build -- --filter System.Net.Primitives.Tests.CredentialCacheTests* --anyCategories Libraries Runtime " --category-exclusion-filter NoAOT NoWASM --runtimes monoaotllvm --aotcompilerpath $RunDir/artifacts/bin/aot/sgen/mini/mono-sgen --customruntimepack $RunDir/artifacts/bin/aot/pack --aotcompilermode llvm --logBuildOutput --generateBinLog " --artifacts $RunDir/artifacts/BenchmarkDotNet.Artifacts --packages $RunDir/performance/artifacts/packages --buildTimeout 1200
```

Windows
```cmd
# Set $RunDir to the runtime directory
$RunDir="FullPathHere"

# Set the OS, arch, and OSId
RunOS='windows'
RunOSId='win'
RunArch='x64'

# Create aot directory
mkdir $RunDir\artifacts\bin\aot\sgen
mkdir $RunDir\artifacts\bin\aot\pack
xcopy $RunDir\artifacts\obj\mono\$RunOS.$RunArch.Release\mono $RunDir\artifacts\bin\aot\sgen\ /e /y
xcopy $RunDir\artifacts\bin\microsoft.netcore.app.runtime.$RunOSId-$RunArch\Release $RunDir\artifacts\bin\aot\pack\ /e /y

# Create Core Root
$RunDir\src\tests\build.cmd release $RunArch generatelayoutonly /p:LibrariesConfiguration=Release

# Clone performance 
git clone --branch main --depth 1 --quiet https://github.com/dotnet/performance.git $RunDir\performance

# One line run:
python3 $RunDir\performance\scripts\benchmarks_ci.py --csproj $RunDir\performance\src\benchmarks\micro\MicroBenchmarks.csproj --incremental no --architecture $RunArch -f net8.0 --filter 'System.Net.Primitives.Tests.CredentialCacheTests*' --bdn-artifacts $RunDir\artifacts\BenchmarkDotNet.Artifacts --bdn-arguments="--anyCategories Libraries Runtime  --category-exclusion-filter NoAOT NoWASM --runtimes monoaotllvm --aotcompilerpath $RunDir\artifacts\bin\aot\sgen\mini\mono-sgen.exe --customruntimepack $RunDir\artifacts\bin\aot\pack --aotcompilermode llvm --logBuildOutput --generateBinLog"

# Individual Commands:
# Restore 
dotnet restore $RunDir\performance\src\benchmarks\micro\MicroBenchmarks.csproj --packages $RunDir\performance\artifacts\packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1

# Build
dotnet build $RunDir\performance\src\benchmarks\micro\MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore /p:NuGetPackageRoot=$RunDir\performance\artifacts\packages /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1

# Run
dotnet run --project $RunDir\performance\src\benchmarks\micro\MicroBenchmarks.csproj --configuration Release --framework net8.0 --no-restore --no-build -- --filter System.Net.Primitives.Tests.CredentialCacheTests* --anyCategories Libraries Runtime " --category-exclusion-filter NoAOT NoWASM --runtimes monoaotllvm --aotcompilerpath $RunDir\artifacts\bin\aot\sgen\mini\mono-sgen.exe --customruntimepack $RunDir\artifacts\bin\aot\pack -aotcompilermode llvm --logBuildOutput --generateBinLog " --artifacts $RunDir\artifacts\BenchmarkDotNet.Artifacts --packages $RunDir\performance\artifacts\packages --buildTimeout 1200
```

</details>

<details>

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by rzikm**
Fixes #101991.
Fixes #102281.

Not sure what introduced the original regression, but we can save some time by first checking if candidate credential can have longer prefix match before we start comparing auth schemes and uri, and we can stop early if we find exact match.

### CODE REVIEW

**Comment by rzikm** [comment]
/benchmark micro aspnet-perf-lin libs --variable filter=GetCredential_Uri

**Comment by MihaZupan** [comment]
@EgorBot
```c#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;
using System.Collections.Generic;
using System.Net;

public class CredentialCacheTests
{
    private const string UriPrefix = "http://name";
    private const string HostPrefix = "name";
    private const int Port = 80;
    private const string AuthenticationType = "authType";

    private static readonly NetworkCredential s_credential = new NetworkCredential();

    private readonly Dictionary<(int uriCount, int hostPortCount), CredentialCache> _caches = new()
    {
        { (0, 0), CreateCredentialCache(0, 0) },
        { (0, 10), CreateCredentialCache(0, 10) },
        { (10, 0), CreateCredentialCache(10, 0) },
        { (10, 10), CreateCredentialCache(10, 10) }
    };

    [Benchmark]
    [Arguments("http://notfound", 0)]
    [Arguments("http://notfound", 10)]
    [Arguments("http://name5", 10)]
    public NetworkCredential GetCredential_Uri(string uriString, int uriCount)
    {
        CredentialCache cc = _caches[(uriCount: uriCount, hostPortCount: 0)];

        return cc.GetCredential(new Uri(uriString), AuthenticationType);
    }

    private static CredentialCache CreateCredentialCache(int uriCount, int hostPortCount)
    {
        var cc = new CredentialCache();

        for (int i = 0; i < uriCount; i++)
        {
            Uri uri = new Uri(UriPrefix + i.ToString());
            cc.Add(uri, AuthenticationType, s_credential);
        }

        for (int i = 0; i < hostPortCount; i++)
        {
            string host = HostPrefix + i.ToString();
            cc.Add(host, Port, AuthenticationType, s_credential);
        }

        return cc;
    }
}
```

**Comment by rzikm** [comment]
I took a look at why we regressed the one scenario, and it seems that that particular benchmark is measuring a corner case. I locally editted the benchmarks so that the creds in the cache on the same host, but different prefix (`http://name/prefix{i}/`) and added couple more test cases and the changes actually improve common scenario. Numbers below are this PR compared to main before introducing the regression.

```
BenchmarkDotNet v0.13.13-nightly.20240311.145, Windows 11 (10.0.22631.3737/23H2/2023Update/SunValley3)
Intel Core i9-10900K CPU 3.70GHz, 1 CPU, 20 logical and 10 physical cores
.NET SDK 9.0.100-preview.5.24307.3
  [Host]     : .NET 9.0.0 (9.0.24.30607), X64 RyuJIT AVX2
  Job-WTZYSK : .NET 9.0.0 (42.42.42.42424), X64 RyuJIT AVX2
  Job-CDIHKU : .NET 9.0.0 (42.42.42.42424), X64 RyuJIT AVX2

PowerPlanMode=00000000-0000-0000-0000-000000000000  IterationTime=250ms  MaxIterationCount=20
MinIterationCount=15  WarmupCount=1

| Method            | Job        | Toolchain          | uriString                        | uriCount | Mean      | Error    | StdDev   | Median    | Min       | Max       | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|------------------ |----------- |------------------- |--------------------------------- |--------- |----------:|---------:|---------:|----------:|----------:|----------:|------:|--------:|-------:|----------:|------------:|
| GetCredential_Uri | Job-WTZYSK | \9.0.0\corerun.exe | http://differentHost             | 10       | 273.23 ns | 4.014 ns | 3.755 ns | 273.96 ns | 265.50 ns | 276.82 ns |  1.21 |    0.02 | 0.0248 |     264 B |        1.43 |
| GetCredential_Uri | Job-CDIHKU | \main\corerun.exe  | http://differentHost             | 10       | 225.99 ns | 3.684 ns | 3.266 ns | 225.76 ns | 221.59 ns | 232.48 ns |  1.00 |    0.02 | 0.0171 |     184 B |        1.00 |
|                   |            |                    |                                  |          |           |          |          |           |           |           |       |         |        |           |             |
| GetCredential_Uri | Job-WTZYSK | \9.0.0\corerun.exe | http://name/diff/path            | 10       | 317.86 ns | 5.780 ns | 5.124 ns | 317.80 ns | 308.61 ns | 326.92 ns |  0.90 |    0.02 | 0.0259 |     272 B |        1.00 |
| GetCredential_Uri | Job-CDIHKU | \main\corerun.exe  | http://name/diff/path            | 10       | 352.02 ns | 6.018 ns | 5.629 ns | 349.61 ns | 346.69 ns | 365.42 ns |  1.00 |    0.02 | 0.0258 |     272 B |        1.00 |
|                   |            |                    |                                  |          |           |          |          |           |           |           |       |         |        |           |             |
| GetCredential_Uri | Job-WTZYSK | \9.0.0\corerun.exe | http://name/differentPrefix/path | 10       | 456.69 ns | 8.940 ns | 8.363 ns | 454.95 ns | 445.83 ns | 470.55 ns |  0.99 |    0.02 | 0.0270 |     288 B |        1.00 |
| GetCredential_Uri | Job-CDIHKU | \main\corerun.exe  | http://name/differentPrefix/path | 10       | 459.11 ns | 7.361 ns | 6.885 ns | 457.80 ns | 448.95 ns | 474.82 ns |  1.00 |    0.02 | 0.0263 |     288 B |        1.00 |
|                   |            |                    |                                  |          |           |          |          |           |           |           |       |         |        |           |             |
| GetCredential_Uri | Job-WTZYSK | \9.0.0\corerun.exe | http://name/prefix5/path         | 10       | 381.24 ns | 7.080 ns | 6.623 ns | 380.00 ns | 372.30 ns | 392.75 ns |  0.81 |    0.02 | 0.0258 |     272 B |        1.00 |
| GetCredential_Uri | Job-CDIHKU | \main\corerun.exe  | http://name/prefix5/path         | 10       | 469.81 ns | 5.792 ns | 5.418 ns | 469.72 ns | 460.92 ns | 478.05 ns |  1.00 |    0.02 | 0.0246 |     272 B |        1.00 |
|                   |            |                    |                                  |          |           |          |          |           |           |           |       |         |        |           |             |
| GetCredential_Uri | Job-WTZYSK | \9.0.0\corerun.exe | http://notfound                  | 0        |  59.25 ns | 1.229 ns | 1.150 ns |  58.77 ns |  57.81 ns |  61.34 ns |  0.98 |    0.02 | 0.0051 |      56 B |        1.00 |
| GetCredential_Uri | Job-CDIHKU | \main\corerun.exe  | http://notfound                  | 0        |  60.65 ns | 0.773 ns | 0.723 ns |  60.47 ns |  59.68 ns |  62.08 ns |  1.00 |    0.02 | 0.0052 |      56 B |        1.00 |
```

**Comment by rzikm** [comment]
@EgorBot 

```cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Collections.Generic;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Engines;
using MicroBenchmarks;

    public class CredentialCacheTests
    {
        private const string UriPrefix = "http://name/prefix";
        private const string HostPrefix = "name";
        private const int Port = 80;
        private const string AuthenticationType = "authType";

        private static readonly NetworkCredential s_credential = new NetworkCredential();

        private readonly Dictionary<(int uriCount, int hostPortCount), CredentialCache> _caches =
            new Dictionary<(int uriCount, int hostPortCount), CredentialCache>
            {
                { (0, 0), CreateCredentialCache(0, 0) },
                { (0, 10), CreateCredentialCache(0, 10) },
                { (10, 0), CreateCredentialCache(10, 0) },
                { (10, 10), CreateCredentialCache(10, 10) }
        };

        [Benchmark]
        [Arguments("http://notfound", 0)]
        [Arguments("http://differentHost", 10)]
        [Arguments("http://name/prefix5/path", 10)]
        [Arguments("http://name/differentPrefix/path", 10)]
        [Arguments("http://name/diff/path", 10)]
        public NetworkCredential GetCredential_Uri(string uriString, int uriCount)
        {
            CredentialCache cc = _caches[(uriCount: uriCount, hostPortCount: 0)];

            return cc.GetCredential(new Uri(uriString), AuthenticationType);
        }

        private static CredentialCache CreateCredentialCache(int uriCount, int hostPortCount)
        {
            var cc = new CredentialCache();

            for (int i = 0; i < uriCount; i++)
            {
                Uri uri = new Uri(UriPrefix + i.ToString() + "/");
                cc.Add(uri, AuthenticationType, s_credential);
            }

            for (int i = 0; i < hostPortCount; i++)
            {
                string host = HostPrefix + i.ToString();
                cc.Add(host, Port, AuthenticationType, s_credential);
            }

            return cc;
        }
    }

```

**Comment by rzikm** [comment]
@EgorBot 

```cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;
using System.Collections.Generic;
using System.Net;

    public class CredentialCacheTests
    {
        private const string UriPrefix = "http://name/prefix";
        private const string HostPrefix = "name";
        private const int Port = 80;
        private const string AuthenticationType = "authType";

        private static readonly NetworkCredential s_credential = new NetworkCredential();

        private readonly Dictionary<(int uriCount, int hostPortCount), CredentialCache> _caches =
            new Dictionary<(int uriCount, int hostPortCount), CredentialCache>
            {
                { (0, 0), CreateCredentialCache(0, 0) },
                { (0, 10), CreateCredentialCache(0, 10) },
                { (10, 0), CreateCredentialCache(10, 0) },
                { (10, 10), CreateCredentialCache(10, 10) }
        };

        [Benchmark]
        [Arguments("http://notfound", 0)]
        [Arguments("http://differentHost", 10)]
        [Arguments("http://name/prefix5/path", 10)]
        [Arguments("http://name/differentPrefix/path", 10)]
        [Arguments("http://name/diff/path", 10)]
        public NetworkCredential GetCredential_Uri(string uriString, int uriCount)
        {
            CredentialCache cc = _caches[(uriCount: uriCount, hostPortCount: 0)];

            return cc.GetCredential(new Uri(uriString), AuthenticationType);
        }

        private static CredentialCache CreateCredentialCache(int uriCount, int hostPortCount)
        {
            var cc = new CredentialCache();

            for (int i = 0; i < uriCount; i++)
            {
                Uri uri = new Uri(UriPrefix + i.ToString() + "/");
                cc.Add(uri, AuthenticationType, s_credential);
            }

            for (int i = 0; i < hostPortCount; i++)
            {
                string host = HostPrefix + i.ToString();
                cc.Add(host, Port, AuthenticationType, s_credential);
            }

            return cc;
        }
    }

```

**Comment by rzikm** [comment]
@dotnet/ncl Can I get a review?

**Review by wfurt — APPROVED** [review]
LGTM. This can still be noise compared to actual TLS.

**Pull request merged**
