### PR TITLE
Cache allregs to avoid checking the type repeatedly

### PR DESCRIPTION
**Pull request by kunalspathak**
Cache the `availableRegs` in a table that we can look-up and return instead of comparing the type every single time in `allRegs()` method. Gives a nice TP:

image

### CODE REVIEW

**Review by jakobbotsch — APPROVED** [review]

**Review by BruceForstall — APPROVED** [review]

**Comment by SingleAccretion** [comment]
What's up with the regressions on x86?

**Comment by kunalspathak** [comment]
> What's up with the regressions on x86?

I will have to double check, but the regression is on Linux/arm MinOpts only.

image

**Comment by jakobbotsch** [comment]
I guess the interesting ones are benchmarks.run.windows.x86.checked.mch and benchmarks.run.windows.x64.checked.mch:

image

image

(The libraries.crossgen2 collections have respectively 16 and 14 MinOpts contexts, so I don't think you can really read much from those)

**Comment by SingleAccretion** [comment]
> Linux/arm MinOpts only.

Note it is present in Windows x86/MinOpts benchmarks / CG collections as well.

**Comment by kunalspathak** [comment]
> I guess the interesting ones are benchmarks.run.windows.x86.checked.mch and benchmarks.run.windows.x64.checked.mch:

Ok, yeah I am still learning that I have to expand those details :)

Tried inlining the `availableIntRegs` directly at places where `allRegs(TYP_INT)` were present but it doesn't help much. Will disassemble and see what is different.

**Comment by kunalspathak** [comment]
Still need to do the TP regression analysis for MinOpts.

**Comment by kunalspathak** [comment]
Ping to myself.

**Comment by kunalspathak** [comment]
Hoping to review the TP analysis soon.

**Comment by kunalspathak** [comment]
The biggest diffs in MinOpts for benchmarks on windows/x64 are these. I will investigate more.

```diff
-22555               : ??$varTypeIsSIMD@W4var_types@@@@YA_NW4var_types@@@Z
+193049              : ??$varTypeIsSIMD@W4var_types@@@@YA_NW4var_types@@@Z
-460532              : ??0LinearScan@@QEAA@PEAVCompiler@@@Z
+942354              : ??0LinearScan@@QEAA@PEAVCompiler@@@Z
```

**Comment by kunalspathak** [comment]
I tried running locally and don't see any regression (at least on windows/x64):

image

**Comment by kunalspathak** [comment]
The latest run doesn't have any benchmarks regression. It just has TP regression on crossgen2 and I tried to eliminate some of that by eliminating the call to `varTypeIsSIMD()`.

Here is the latest and I don't think there is anything much that can be done:

```
Base: 1801740, Diff: 1802793, +0.0584%

??0LinearScan@@QEAA@PEAVCompiler@@@Z                                             : 5430  : +104.62% : 54.91% : +0.3014%
??$varTypeIsSIMD@W4var_types@@@@YA_NW4var_types@@@Z                              : 21    : +7.95%   : 0.21%  : +0.0012%
memset                                                                           : 16    : +0.17%   : 0.16%  : +0.0009%
?LowerStoreLocCommon@Lowering@@AEAAXPEAUGenTreeLclVarCommon@@@Z                  : -30   : -0.90%   : 0.30%  : -0.0017%
?identifyCandidates@LinearScan@@AEAAXXZ                                          : -33   : -1.66%   : 0.33%  : -0.0018%
?BuildCall@LinearScan@@AEAAHPEAUGenTreeCall@@@Z                                  : -103  : -0.34%   : 1.04%  : -0.0057%
?genFnPrologCalleeRegArgs@CodeGen@@IEAAXW4_regNumber_enum@@PEA_NPEAURegState@@@Z : -189  : -2.42%   : 1.91%  : -0.0105%
?BuildUse@LinearScan@@AEAAPEAVRefPosition@@PEAUGenTree@@IH@Z                     : -526  : -2.45%   : 5.32%  : -0.0292%
?BuildDef@LinearScan@@AEAAPEAVRefPosition@@PEAUGenTree@@IH@Z                     : -634  : -3.62%   : 6.41%  : -0.0352%
?allRegs@LinearScan@@AEAAIW4var_types@@@Z                                        : -1246 : -100.00% : 12.60% : -0.0692%
?BuildNode@LinearScan@@AEAAHPEAUGenTree@@@Z                                      : -1657 : -4.58%   : 16.76% : -0.0920%
```

**Comment by jakobbotsch** [comment]
@kunalspathak What if you change the initialization of the table to:

```cpp
for (unsigned int i = 0; i < TYP_COUNT; i++)
{
  availableRegs[i] = &availableIntRegs;
}

availableRegs[TYP_FLOAT] = &availableFloatRegs;
availableRegs[TYP_DOUBLE] = &availableDoubleRegs;
availableRegs[TYP_SIMD8] = &availableDoubleRegs;
availableRegs[TYP_SIMD12] = &availableDoubleRegs;
availableRegs[TYP_SIMD16] = &availableDoubleRegs;
availableRegs[TYP_SIMD32] = &availableDoubleRegs;
```

In any case it still looks minor to me.

**Review by jakobbotsch — APPROVED** [review]

**Comment by kunalspathak** [comment]
> @kunalspathak What if you change the initialization of the table to:

That's a reasonable approach, but as I mentioned earlier, this is `LinearScan` ctor which just gets invoked once per compilation. With the latest changes, the TP regression dropped, so I will go ahead and merge it. 

image

This  was a good exercise for me to learn how to analyze TP regression locally.

**Pull request merged**
