### PR TITLE
Fix the condition in assert

### LINKED ISSUE #38791: "Mutual exclusion over || is always a non-zero constant" in optimizer.cpp
In line 2321:
https://github.com/dotnet/runtime/blob/312c758edc524ef941bce5cebd289a628f0182cf/src/coreclr/src/jit/optimizer.cpp#L2321-L2322
`BBjumpKinds` is not a flag enum, so comparing `block->bbJumpKind` for inequality with `BBJ_COND` or `BBJ_ALWAYS` will always result in `true` as `bbJumpKind` can't be `BBJ_COND` and `BBJ_ALWAYS` at the same time.
image

### PR DESCRIPTION
**Pull request by kunalspathak**
Fix a condition inside an assert.

Fixes: https://github.com/dotnet/runtime/issues/38791

### CODE REVIEW

**Comment by kunalspathak** [comment]
@BruceForstall

**Review by BruceForstall — APPROVED** [review]
LGTM.

Just for completeness, you should trigger the JitStress job

**Comment by kunalspathak** [comment]
Yes, I already [triggered one](https://dev.azure.com/dnceng/public/_build/results?buildId=721803&view=results) yesterday but looks like some of the legs timed out. I have [triggered another one](https://dev.azure.com/dnceng/public/_build/results?buildId=722783&view=results).

**Comment by kunalspathak** [comment]
Looks like jitstress is passing.

**Pull request merged**
