### PR TITLE
ARM64-SVE: Fix gather tests

### PR DESCRIPTION
**Pull request by a74nh**
Fixes bad casting added during the Gather Extend implementation.

Partial fix for https://github.com/dotnet/runtime/issues/103854

### CODE REVIEW

**Review by kunalspathak — APPROVED** [review]
LGTM. Can you please confirm if there are no other stress failures for `GatherVector*`?

**Comment by a74nh** [comment]
> LGTM. Can you please confirm if there are no other stress failures for `GatherVector*`?

Looks like we still have some stress issues. [Partial log](https://gist.github.com/a74nh/5288b36790eda61f70e2b77e178b588c).

I suggest this PR goes in as-is to fix the non-stress issues.

**Comment by a74nh** [comment]
Failing test under stress: 
```
❯ env | grep DOTNET
DOTNET_JitStress=1
DOTNET_TieredCompilation=0
DOTNET_JitDisasm=RunBasicScenario_UnsafeRead
❯ $CORE_ROOT/corerun ./artifacts/tests/coreclr/linux.arm64.Checked/JIT/HardwareIntrinsics/HardwareIntrinsics_Arm_ro/HardwareIntrinsics_Arm_ro.dll Sve_GatherVector_Indices_uint_int
16:23:21.260 Running test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_GatherVector_Indices_uint_int()
Supported ISAs:
  AdvSimd:   True
  Aes:       True
  ArmBase:   True
  Crc32:     True
  Dp:        True
  Rdm:       True
  Sha1:      True
  Sha256:    True
  Sve:       True

; Assembly listing for method JIT.HardwareIntrinsics.Arm._Sve.SveGatherVectorIndices__Sve_GatherVector_Indices_uint_int:RunBasicScenario_UnsafeRead():this (FullOpts)
; Emitting BLENDED_CODE for generic ARM64 - Unix
; FullOpts code
; optimized code
; fp based frame
; partially interruptible
; No PGO data
; 0 inlinees with PGO data; 5 single block inlinees; 0 inlinees without PGO data
; Final local variable assignments
;
;  V00 this         [V00,T00] ( 12, 12   )     ref  ->  x19         this class-hnd single-def <JIT.HardwareIntrinsics.Arm._Sve.SveGatherVectorIndices__Sve_GatherVector_Indices_uint_int>
;  V01 loc0         [V01,T11] (  2,  2   )  simd16  ->   d8         HFA(simd16)  <System.Numerics.Vector`1[uint]>
;# V02 OutArgs      [V02    ] (  1,  1   )  struct ( 0) [sp+0x00]  do-not-enreg[XS] addr-exposed "OutgoingArgSpace"
;* V03 tmp1         [V03    ] (  0,  0   )  simd16  ->  zero-ref    "impAppendStmt"
;* V04 tmp2         [V04    ] (  0,  0   )    long  ->  zero-ref    "impAppendStmt"
;  V05 tmp3         [V05,T05] (  2,  4   )    long  ->  x20         "impAppendStmt"
;  V06 tmp4         [V06,T06] (  2,  4   )    long  ->  x22         "impAppendStmt"
;  V07 tmp5         [V07,T07] (  2,  4   )    long  ->  x23         "impAppendStmt"
;  V08 tmp6         [V08,T01] (  3,  6   )   byref  ->  x20         single-def "Inlining Arg"
;* V09 tmp7         [V09    ] (  0,  0   )    long  ->  zero-ref    ld-addr-op "Inline stloc first use temp"
;  V10 tmp8         [V10,T08] (  2,  4   )    long  ->   x0         "Inlining Arg"
;  V11 tmp9         [V11,T02] (  3,  6   )    long  ->   x1         "Inlining Arg"
;  V12 tmp10        [V12,T04] (  2,  4   )   byref  ->  x24         single-def "Inlining Arg"
;  V13 tmp11        [V13    ] (  2,  2   )    long  ->  [fp+0x18]  do-not-enreg[X] addr-exposed ld-addr-op "Inline stloc first use temp"
;  V14 tmp12        [V14,T09] (  2,  4   )    long  ->   x0         "Inlining Arg"
;  V15 tmp13        [V15,T03] (  3,  6   )    long  ->   x4         "Inlining Arg"
;  V16 cse0         [V16,T10] (  3,  3   )   byref  ->  x21         "CSE #02"
;
; Lcl frame size = 16

G_M24438_IG01:  ;; offset=0x0000
            stp     fp, lr, [sp, #-0x60]!
            stp     d8, d9, [sp, #0x20]
            stp     x19, x20, [sp, #0x30]
            stp     x21, x22, [sp, #0x40]
            stp     x23, x24, [sp, #0x50]
            mov     fp, sp
            mov     x19, x0
						;; size=28 bbWeight=1 PerfScore 6.00
G_M24438_IG02:  ;; offset=0x001C
            movz    x0, #0x2190
            movk    x0, #0x8C12 LSL #16
            movk    x0, #0xFFFF LSL #32
            movz    x1, #0xDC68      // code for TestLibrary.TestFramework:BeginScenario(System.String)
            movk    x1, #0x4277 LSL #16
            movk    x1, #0xFFFF LSL #32
            ldr     x1, [x1]
            blr     x1
            ldrsb   wzr, [x19]
            add     x0, x19, #88
            movz    x1, #0x4A38      // code for JIT.HardwareIntrinsics.Arm._Sve.SveGatherVectorIndices__Sve_GatherVector_Indices_uint_int+DataTable:get_inArray1Ptr():ulong:this
            movk    x1, #0x4456 LSL #16
            movk    x1, #0xFFFF LSL #32
            ldr     x1, [x1]
            blr     x1
            ldr     q16, [x0]
            ptrue   p0.s
            cmpne   p0.s, p0/z, z16.s, #0
            add     x0, x19, #88
            movz    x1, #0x4A50      // code for JIT.HardwareIntrinsics.Arm._Sve.SveGatherVectorIndices__Sve_GatherVector_Indices_uint_int+DataTable:get_inArray2Ptr():ulong:this
            movk    x1, #0x4456 LSL #16
            movk    x1, #0xFFFF LSL #32
            ldr     x1, [x1]
            blr     x1
            mov     x20, x0
            add     x0, x19, #88
            movz    x1, #0x4A68      // code for JIT.HardwareIntrinsics.Arm._Sve.SveGatherVectorIndices__Sve_GatherVector_Indices_uint_int+DataTable:get_inArray3Ptr():ulong:this
            movk    x1, #0x4456 LSL #16
            movk    x1, #0xFFFF LSL #32
            ldr     x1, [x1]
            blr     x1
            ldr     q16, [x0]
            ld1w    { z8.s }, p0/z, [x20, z16.s, sxtw #2]
            add     x20, x19, #88
            add     x21, x20, #64
            mov     x0, x21
            movz    x1, #0xDFB0      // code for System.Runtime.InteropServices.GCHandle:AddrOfPinnedObject():long:this
            movk    x1, #0x41C4 LSL #16
            movk    x1, #0xFFFF LSL #32
            ldr     x1, [x1]
            mov     v9.d[0], v8.d[1]
            blr     x1
            ldr     x1, [x20, #0x20]
            sub     x2, x1, #1
            add     x0, x1, x0
            sub     x0, x0, #1
            bic     x0, x0, x2
            mov     v8.d[1], v9.d[0]
            str     q8, [x0]
            add     x0, x19, #88
            movz    x1, #0x4A38      // code for JIT.HardwareIntrinsics.Arm._Sve.SveGatherVectorIndices__Sve_GatherVector_Indices_uint_int+DataTable:get_inArray1Ptr():ulong:this
            movk    x1, #0x4456 LSL #16
            movk    x1, #0xFFFF LSL #32
            ldr     x1, [x1]
            blr     x1
            mov     x20, x0
            add     x0, x19, #88
            movz    x1, #0x4A50      // code for JIT.HardwareIntrinsics.Arm._Sve.SveGatherVectorIndices__Sve_GatherVector_Indices_uint_int+DataTable:get_inArray2Ptr():ulong:this
            movk    x1, #0x4456 LSL #16
            movk    x1, #0xFFFF LSL #32
            ldr     x1, [x1]
            blr     x1
            mov     x22, x0
            add     x0, x19, #88
            movz    x1, #0x4A68      // code for JIT.HardwareIntrinsics.Arm._Sve.SveGatherVectorIndices__Sve_GatherVector_Indices_uint_int+DataTable:get_inArray3Ptr():ulong:this
            movk    x1, #0x4456 LSL #16
            movk    x1, #0xFFFF LSL #32
            ldr     x1, [x1]
            blr     x1
            mov     x23, x0
            add     x24, x19, #88
            mov     x0, x21
            movz    x1, #0xDFB0      // code for System.Runtime.InteropServices.GCHandle:AddrOfPinnedObject():long:this
            movk    x1, #0x41C4 LSL #16
            movk    x1, #0xFFFF LSL #32
            ldr     x1, [x1]
            blr     x1
            str     x0, [fp, #0x18]	// [V13 tmp11]
            add     x0, fp, #24	// [V13 tmp11]
            movz    x1, #0xE790      // code for System.IntPtr:ToPointer():ulong:this
            movk    x1, #0x4180 LSL #16
            movk    x1, #0xFFFF LSL #32
            ldr     x1, [x1]
            blr     x1
            ldr     x4, [x24, #0x20]
            sub     x1, x4, #1
            add     x4, x4, x0
            sub     x4, x4, #1
            bic     x4, x4, x1
            mov     x0, x19
            mov     x1, x20
            mov     x2, x22
            mov     x3, x23
            movz    x5, #0x2190
            movk    x5, #0x8C12 LSL #16
            movk    x5, #0xFFFF LSL #32
            movz    x6, #0x4C78      // code for JIT.HardwareIntrinsics.Arm._Sve.SveGatherVectorIndices__Sve_GatherVector_Indices_uint_int:ValidateResult(ulong,ulong,ulong,ulong,System.String):this
            movk    x6, #0x4456 LSL #16
            movk    x6, #0xFFFF LSL #32
            ldr     x6, [x6]
            blr     x6
						;; size=404 bbWeight=1 PerfScore 109.50
G_M24438_IG03:  ;; offset=0x01B0
            ldp     x23, x24, [sp, #0x50]
            ldp     x21, x22, [sp, #0x40]
            ldp     x19, x20, [sp, #0x30]
            ldp     d8, d9, [sp, #0x20]
            ldp     fp, lr, [sp], #0x60
            ret     lr
						;; size=24 bbWeight=1 PerfScore 6.00

; Total bytes of code 456, prolog size 24, PerfScore 121.50, instruction count 114, allocated bytes for code 456 (MethodHash=959ca089) for method JIT.HardwareIntrinsics.Arm._Sve.SveGatherVectorIndices__Sve_GatherVector_Indices_uint_int:RunBasicScenario_UnsafeRead():this (FullOpts)
; ============================================================

Beginning scenario: RunBasicScenario_UnsafeRead
Sve.GatherVector<UInt32>(UInt32, UInt32, Int32): RunBasicScenario_UnsafeRead failed:
  firstOp: (1, 1, 1, 0)
  secondOp: (44443, 898747, 434033, 376822, 988392, 588735, 589009, 65400, 32733, 970598, 81631, 512437, 196058, 110177, 917503, 726499, 256186, 563060, 98281, 905292, 903997, 393012, 393085, 470950, 64504, 177656, 1013676, 524090, 237309, 982776, 497106, 128719, 915188, 913392, 458409, 389100, 646516, 326879, 523251, 458621, 227054, 522058, 847093, 117875, 294677, 909002, 56856, 630355, 749546, 1044345, 884112, 360437, 620542, 1044879, 458107, 503214, 911352, 360410, 979069, 90075, 1015016, 40786, 783836, 557050, 51191, 892734, 23420, 432694, 192501, 113276, 1048315, 913305, 966232, 524156, 917475, 1043375, 360279, 393205, 275895, 319483, 407387, 972995, 554992, 524230, 1039776, 196530, 262102, 112061, 1037437, 236798, 1047541, 212988, 523747, 424569, 488948, 978684, 114427, 327678, 829136, 767947, 785673, 53154, 1007557, 1046010, 851686, 124783, 32495, 523999, 196030, 196592, 645576, 327667, 481270, 719805, 130558, 811005, 638930, 325105, 104812, 380634, 237304, 1023416, 589697, 325631, 663033, 1048038, 114109, 849533, 769535, 454867, 129507, 765884, 188234, 1048562, 130044, 491512, 685573, 552916, 704447, 65278, 699320, 303101, 101046, 835483, 177889, 187827, 392055, 294781, 778053, 393130, 89471, 882650, 59126, 243437, 336626, 241607, 195190, 298868, 636893, 65513, 783989, 654512, 187389, 499672, 913383, 65018, 970550, 972795, 40187, 505816, 1015418, 1048426, 978925, 849388, 445427, 61368, 704407, 1032191, 457580, 981778, 325556, 94974, 372215, 781301, 703673, 1027670, 49086, 851857, 374999, 556026, 897016, 522141, 172027, 802658, 259007, 456314, 636907, 122866, 65490, 318802, 196599, 114343, 443572, 61371, 514420, 458685, 711781, 475022, 65392, 622459, 193531, 393083, 65532, 360316, 98102, 260058, 654780, 815100, 450551, 325837, 662914, 712539, 325586, 1045627, 847612, 176599, 851924, 245247, 819065, 1046067, 715763, 589303, 708605, 372696, 1046007, 65400, 817627, 196606, 421371, 785872, 685040, 385784, 441948, 747443, 851453, 119718, 321441, 98262, 686060, 769413, 810210, 90065, 383994, 1015064, 322973, 828414, 1044055, 229208, 907183, 981501, 520055, 48542, 744348, 241597, 676844, 917345, 141057, 162737, 587456, 710562, 194451, 650675, 1047390, 30713, 454561, 72611, 193531, 647014, 840162, 589182, 188407, 966111, 454643, 884443, 393141, 884727, 1048575, 298828, 653780, 187573, 194038, 735778, 749409, 641501, 377822, 206577, 453885, 57244, 523508, 327654, 251441, 130405, 780276, 737266, 720880, 111472, 220849, 323068, 720816, 1038549, 104429, 192510, 147443, 876400, 131069, 48883, 652286, 900985, 352232, 842491, 323198, 519160, 938739, 1045456, 588530, 618352, 890363, 712143, 374752, 260852, 528353, 327484, 503096, 97193, 368608, 1047039, 516061, 622521, 905015, 896757, 256890, 671609, 524275, 846960, 1043951, 679924, 457455, 490484, 784226, 57169, 226815, 251573, 638975, 819177, 130791, 898743, 720882, 909293, 392188, 720797, 911099, 96821, 521065, 322545, 487376, 257656, 499644, 483315, 890871, 225196, 830962, 171986, 950002, 105458, 960466, 548677, 843612, 1023412, 677867, 129711, 484450, 506583, 128989, 1045086, 847286, 14333, 126968, 913109, 588787, 357332, 786300, 130869, 903140, 169470, 440088, 432126, 850898, 325629, 376816, 917111, 319349, 154078, 654590, 547819, 849780, 302205, 914749, 848895, 832428, 783861, 160509, 645473, 782300, 719866, 654581, 759639, 491453, 917204, 154485, 878455, 1030889, 786417, 261440, 833906, 491504, 325419, 833473, 327677, 989908, 325298, 901117, 262139, 957926, 747957, 850616, 915350, 320988, 257527, 150478, 154353, 458654, 899037, 158713, 523547, 880625, 552657, 437141, 510971, 1030884, 51125, 641659, 524077, 385460, 163188, 392630, 842418, 979965, 643010, 490999, 440292, 916476, 522005, 933086, 1046961, 1011180, 351908, 65528, 130747, 942071, 107379, 875219, 94195, 1011665, 587771, 655332, 311198, 715986, 670923, 573424, 229311, 260006, 589253, 32749, 849546, 63227, 819190, 256976, 351681, 753104, 65444, 632567, 442110, 129012, 182008, 1036214, 173531, 455643, 524277, 434020, 548854, 942078, 369535, 647027, 915428, 176121, 118773, 423421, 180083, 899964, 654279, 324596, 717690, 703866, 716458, 737270, 130346, 196540, 845284, 425981, 1044189, 131068, 244981, 589675, 253395, 259953, 310842, 373759, 259314, 319413, 946140, 622521, 589780, 169590, 393163, 642940, 552444, 573214, 900854, 61948, 884185, 965328, 655321, 388605, 56827, 327136, 770039, 712431, 442121, 652722, 589042, 196213, 753535, 310750, 514007, 655351, 1027518, 850937, 573346, 633595, 753377, 58738, 587227, 391929, 818670, 671422, 388311, 321782, 845737, 54973, 571240, 438206, 980922, 56702, 194550, 585714, 323060, 360412, 720889, 909264, 73446, 950263, 653039, 184175, 286200, 358371, 582002, 881907, 1031099, 720858, 684639, 720755, 628721, 909281, 458101, 891803, 220858, 831475, 392948, 1012650, 491262, 907103, 375799, 113655, 685910, 196600, 406348, 495604, 89949, 1048215, 442080, 621282, 237552, 262096, 18273, 194007, 507808, 1047798, 1048570, 651050, 392928, 262119, 782048, 195507, 438251, 769908, 196561, 716793, 1034230, 683408, 128507, 981989, 450398, 520172, 583088, 687600, 653304, 980980, 190965, 192054, 912334, 1045439, 883542, 89810, 786424, 817077, 587733, 760935, 122877, 393050, 835573, 393205, 915441, 262141, 653017, 573413, 192255, 781911, 643045, 458741, 584365, 975840, 257491, 942073, 973823, 618477, 785878, 655337, 1027409, 54732, 425810, 65277, 376752, 524284, 917405, 654258, 910315, 1032146, 191991, 847341, 359917, 368126, 522645, 126907, 703925, 196606, 1047549, 997877, 487410, 718578, 264165, 114580, 1048049, 507639, 325631, 29537, 46899, 972589, 1047520, 550639, 448498, 488690, 195446, 193392, 843442, 883111, 434131, 323575, 258037, 261986, 454595, 255205, 115964, 621822, 1048444, 913051, 1027572, 632826, 604074, 319459, 28376, 965373, 323027, 325615, 60140, 458553, 229110, 959324, 972646, 456670, 851955, 653690, 387801, 1011608, 49145, 786222, 651732, 113977, 196392, 948476, 651742, 490418, 636229, 810965, 441957, 47601, 54713, 652018, 389096, 983003, 191976, 643065, 775165, 245373, 701036, 833533, 749560, 916982, 437620, 258039, 894965, 834299, 515961, 392077, 130980, 114584, 432876, 456081, 520025, 851771, 90038, 753636, 1048424, 187371, 982952, 860880, 238462, 983003, 786334, 781808, 449527, 220734, 802781, 573237, 109523, 448497, 288745, 171005, 589043, 950141, 243689, 360191, 585705, 712656, 980695, 327624, 59349, 114643, 917235, 178936, 60414, 786302, 581603, 630227, 782266, 982466, 655217, 129957, 1033953, 155508, 908260, 28607, 584627, 908972, 638108, 884479, 114298, 408671, 564473, 1021946, 499644, 1041347, 645848, 982772, 913369, 848250, 589684, 950005, 688115, 61311, 131039, 916982, 303082, 514552, 326642, 392218, 384510, 522232, 835583, 968700, 237552, 778048, 982432, 966384, 569343, 786274, 131069, 717715, 644828, 488958, 121701, 1042864, 327669, 137195, 1015803, 897968, 507864, 311261, 229073, 712697, 620531, 896232, 130991, 718813, 990171, 516093, 112876, 277422, 589748, 846005, 539514, 1023802, 31985, 449778, 126969, 253394, 716730, 816114, 588018, 490220, 130747, 196594, 781667, 521299, 651171, 712662, 654745, 278513, 252215, 481279, 51800, 1005552, 585303, 261105, 587180, 449532, 953272, 237555, 435566, 775281, 743731, 442096, 769019, 523252, 47672, 580061, 587172, 453371, 49084, 307197, 191128, 309246, 596895, 521654, 289630, 192385, 391539, 425833, 128506, 429993, 707895, 190454, 310772, 232095, 917500, 572974, 691164, 65278, 916925, 452457, 617972, 1045745, 589795, 517932, 179051, 634854, 780287, 126709, 476090, 1007091, 589819, 567148, 194552, 458625, 395833, 260982, 716118, 751590, 773560, 908796, 1045836, 1048535, 882686, 518359, 851956, 311284, 957950, 393075, 319350, 435832, 1048549, 823292, 161783, 772604, 622261, 783201, 1043426, 40883, 719613, 466873, 458363, 516041, 707281, 909306, 1014254, 40894, 520145, 111461, 523480, 917206, 290811, 677147, 325087, 452603, 384177, 646906, 256386, 24180, 576316, 393197, 182106, 573299, 524270, 783474, 325631, 715187, 958386, 498936, 425848, 552659, 180203, 974693, 505072, 686077, 331389, 192045, 554962, 454498, 15603, 490870, 379863, 654312, 654320, 185336, 288145, 704442, 655330, 654525, 1005562, 52189, 199645, 975723, 6908, 797684, 935643)
  thirdOp: (996, 208, 648, 583)
   result: (0, 0, 0, 0)

Beginning scenario: RunBasicScenario_Load
Beginning scenario: RunBasicScenario_FalseMask
Beginning scenario: RunBasicScenario_NonFaulting
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario
Beginning scenario: ConditionalSelect_ZeroOp
Beginning scenario: ConditionalSelect_ZeroOp_zero
Beginning scenario: ConditionalSelect_ZeroOp_all
System.Exception: One or more scenarios did not complete as expected.
   at JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_GatherVector_Indices_uint_int() in /home/alahay01/dotnet/runtime_base/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/Sve.GatherVector.Indices.uint.int.cs:line 82
   at Program.<<Main>$>g__TestExecutor2909|0_2910(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&) in /home/alahay01/dotnet/runtime_base/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/HardwareIntrinsics_Arm_ro/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs:line 73499
16:23:21.989 Failed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve.Program.Sve_GatherVector_Indices_uint_int()
```

**Comment by kunalspathak** [comment]
> I suggest this PR goes in as-is to fix the non-stress issues.

sure, I will keep the https://github.com/dotnet/runtime/issues/103854 open.

**Pull request merged**
