### PR TITLE
[mono] catch the case of updated methods in mono_debug_lookup_source_location

### PR DESCRIPTION
**Pull request by lambdageek**
If a newly added method is in a stack trace, look it up in the EnC debug information, if available.

Related to #93860

### CODE REVIEW

**Comment by lambdageek** [comment]
I think I also need to update `mono_debug_lookup_source_location_by_il`, and figure out how to make a test get in there

**Review by vargaz — APPROVED** [review]

**Comment by lambdageek** [comment]
Actually I think `mono_debug_lookup_source_location_by_il` doesn't need an update (or at least it's not obvious to me that it is useful).

It's called from 3 places:

1. From `mono_get_frame_info` if `il_offset != -1` - but as far as I can tell `il_offset` is never set to anything else.  That branch is dead code.
2. From `mono_emit_jit_dump` but that's support for profiling, which isn't something we support with hot reload.

**Pull request merged**
