### PR TITLE
[wasm] Move EnableAggressiveTrimming build to `runtime` pipeline

### PR DESCRIPTION
**Pull request by radical**
.. from `runtime-staging`, so any changes that break that can be caught,
and fixed. Any test failures in `runtime-staging` don't fail the job
itself, so it gets missed.

### CODE REVIEW

**Comment by radical** [comment]
This will need a fix for https://github.com/dotnet/runtime/pull/52194#issuecomment-831648083 which @eerhardt is looking at, to get a green build.

**Comment by steveisok** [comment]
The work items on this leg have had a > 90% pass rate for at least the last 14 days.

**Review by steveisok — APPROVED** [review]

**Comment by lewing** [comment]
based on the new lanes failing in https://github.com/dotnet/runtime/pull/52194#issuecomment-831648083 that is probably trimming related?

**Comment by ViktorHofer** [comment]
Is this just about building or also testing on helix? If the former then there's no need to move it over from runtime-staging as in case of build errors, the legs turns red and marks the PR as failed. Only test failures in the runtime-staging leg are ignored in the PR's success mark.

**Comment by radical** [comment]
Tests are built for AOT (in `runtime-staging`), and those have to use `EnableAggressiveTrimming`(EAT). To make sure that the AOT test run doesn't fail because of EAT failures, we use a separate job for just *building* tests with EAT. This is that job.

We need to keep this job green, and since it can break with any library change, we want it to be in `runtime`, so it can get caught+fixed at the time of the change.

**Comment by radical** [comment]
Err.. sorry, I misspoke. For the EAT job, we do build *and* run the tests. This ensures that the tests pass with trimming.

And the AOT job in `runtime-staging` runs the same set of tests as above.

**Comment by ViktorHofer** [comment]
Cool. What's the current pass rate of these tests in runtime-staging? We usually move stuff over when they reach 80-90% pass rate.

**Comment by radical** [comment]
[According to @steveisok](https://github.com/dotnet/runtime/pull/52252#issuecomment-832090612):

> The work items on this leg have had a > 90% pass rate for at least the last 14 days.

**Comment by ViktorHofer** [comment]
Great 👍 thanks a lot

**Review by ViktorHofer — APPROVED** [review]

**Comment by eerhardt** [comment]
> This will need a fix for #52194 (comment) which @eerhardt is looking at, to get a green build.

https://github.com/dotnet/runtime/pull/52265 should address the wasm EAT test failures in `Microsoft.Extensions.HostFactoryResolver.Tests`.

**Comment by lewing** [comment]
runtime (Build Browser wasm Release AllSubsets_Mono) failure is https://github.com/dotnet/runtime/issues/51131

**Pull request merged**
