### PR TITLE
Consolidate NativeRuntimeEventSource and PortableThreadPoolEventSource

### PR DESCRIPTION
**Pull request by benaadams**
To avoid double ETW registration of the event source `Microsoft-Windows-DotNETRuntime` on Windows

Contributes to https://github.com/dotnet/runtime/issues/38763

/cc @kouvel currently checking if this resolves the EventSource startup up perf issues I was seeing

### CODE REVIEW

**Comment by benaadams** [comment]
Looks to stop the startup manifest generation and shave quite a bit off startup on Windows

From

image


To

image

**Comment by josalem** [comment]
CC @sywhang

**Comment by sywhang** [comment]
This will cause ThreadPool events being fired from PortableThreadPool to not work on ETW. ETW works with GUID and currently NativeRuntimeEventSource has a different GUID from Microsoft-Windows-DotNETRuntime which breaks tools like PerfView to correctly enable them.

**Comment by benaadams** [comment]
>  ETW works with GUID and currently NativeRuntimeEventSource has a different GUID from Microsoft-Windows-DotNETRuntime

How does it work currently when not using `PortableThreadPoolEventSource` as all the regular thread pool events go via `NativeRuntimeEventSource` e.g. the only extra one is `ThreadPoolWorkerThreadAdjustmentAdjustment`; the consolidation was mostly moving all of `PortableThreadPoolEventSource`'s current events to a new `NativeRuntimeEventSource` in the mono side of CoreLib as all the events were already there in the CoreClr `NativeRuntimeEventSource`

**Comment by kouvel** [comment]
> How does it work currently when not using `PortableThreadPoolEventSource` as all the regular thread pool events go via `NativeRuntimeEventSource`

When the portable thread pool is disabled, I believe the events are fired to ETW directly from the native side (with the correct GUID), and events are somehow forwarded to any `EventListeners` registered with `NativeRuntimeEventSource`, so `NativeRuntimeEventSource` would not actually be firing the events to ETW, only dispatches to registered listeners. When the portable thread pool is enabled, many of the thread pool events are triggered from the managed side, so then `PortableThreadPoolEventSource` (or `NativeRuntimeEventSource` after the consolidation) would need to fire those events to ETW (with the same GUID as the runtime provider GUID) and dispatch to registered listeners.

**Comment by benaadams** [comment]
> I believe the events are fired to ETW directly from the native side (with the correct GUID), and events are somehow forwarded

Ah, I see it now and it has its own pre-done manifest https://github.com/dotnet/runtime/blob/8c863fe9163aa8ce64d9f4cc62b38feeb7e453b4/src/coreclr/vm/ClrEtwAll.man#L8-L10

Looks more complicated to resolve as @sywhang and you point out.

Can't see an alternative way of fixing the double register either without moving `PortableThreadPoolEventSource` to a different name/guid; but then would bifurcate the threadpool events which would be unhelpful

**Comment by benaadams** [comment]
Will close this and raised issue for double registration https://github.com/dotnet/runtime/issues/46007

**Comment by benaadams** [comment]
Unless...

**Pull request closed without merging**
