### PR TITLE
Add switches for more general altjit and cross-target commands

### PR DESCRIPTION
**Pull request by BruceForstall**
Add `-mch_arch` to specify which architecture to use when downloading
MCH files from Azure Storage. The idea is that you can specify to
download, say, arm64 MCH files and then run them on x64 by also
specifying an arm64 cross-targeting JIT. Defaults to `-target_arch`
(which itself defaults to the host architecture).

Add `-jit` to allow specifying the JIT name to use. Do this instead of
`-altjit`.

Change `-altjit` to `--altjit`. It no longer takes a JIT name; use `-jit`
instead for that purpose. Now, `--altjit` just sets the altjit
variables.

Add `-target_arch` and `-target_os` to specify the cross-target of the JIT.
The `-target_arch`, in particular, is used to pass the `-target` argument
to SuperPMI, which it needs to know which disassembler to use.

So, for example, to run SuperPMI asm diffs with a Windows arm64 cross-JIT
on Windows x64, you might use:
```
py superpmi.py asmdiffs -jit clrjit_win_arm64_x64.dll -target_arch arm64
```

Unfortunately, these cross-JIT scenarios have other problems right now,
but this scripting is a start.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
ping. Can someone sign off?

**Review by sandreenko — APPROVED** [review]
LGTM, one question in which scenarios do we need --altjit after this change?

**Review by echesakov — APPROVED** [review]

**Comment by BruceForstall** [comment]
> one question in which scenarios do we need --altjit after this change?

I believe you need it if you are running against a non-native collection, e.g., running clrjit_win_arm_x86.dll (x86 hosted arm32-targeting cross-JIT) against an x86 collection MCH file. But I'm still not 100% clear on if even that needs the altjit variables set.

**Pull request merged**
