### PR TITLE
Add Win11 RIDs

### PR DESCRIPTION
**Pull request by vitek-karas**
In reaction to #58125

### CODE REVIEW

**Comment by vitek-karas** [comment]
/cc @agocke 

We will probably want to backport this to 6 I assume?

(I'm looking for Win11 VM to test this on)

**Comment by agocke** [comment]
Yup, we'll want to backport

**Comment by jkotas** [comment]
Windows 11 reported its OS version as 10 when I checked last time. Is it still the case or does it report 11 now?

**Comment by wfurt** [comment]
`Environment.OSVersion` reports `Microsoft Windows NT 10.0.22000.0`.
While this may be technically right OS presents itself to user as 
image

I'm wondering if OS plays some mapping trick like Apple did for macOS 11.

**Comment by jkotas** [comment]
I think it is better to think about this as core OS version (kernel version in Linux world) vs. OS distro name and version.

Windows 11 in the dialog you have shared is like a distro name and version. If Windows Server 2022 had this dialog, I think it would present itself as `Windows Server 2022` (no mention of either 10 or 11). Both Windows 11 and Windows Server 2022 distros still use Windows 10.X core OS. I agree that it is very confusing.

**Comment by jkotas** [comment]
This may have also interplay with `TargetFramework` and `TargetPlatformMinVersion` https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance#supporting-multiple-windows-os-versions . If we introduce win11 RID even though everything else considers it to be Windows 10 core OS, we may need mapping in between the two in the SDK in some places.

**Comment by vitek-karas** [comment]
I tried on a much later Win11 build than @wfurt (thanks for looking into it) and it's still the same: 10.0.22488. Which means that the code we have to detect current RID would still pick win10. Actually I tested it with the updated RID graph and it does still say win10 everywhere.

I assume this means we don't want to introduce the win11 RIDs. Might cause slight confusion for users, but I agree that the impact to SDK and such is probably not worth it (especially since the OS also treats itself as win10 in other areas as well).

**Pull request closed without merging**
