### PR TITLE
Fix gtGetClassHandle for static fields (R2R only)

### LINKED ISSUE #74000: [NativeAot] Devirtualization opportunity around field loads
Notice the first interface call is not devirtualized, only the second, after storing to a local.

```csharp
using System;
using System.Runtime.CompilerServices;

interface IFoo
{
    void Frob();
}

class Program : IFoo
{
    static IFoo theFoo = new Program();

    public void Frob() => Console.WriteLine("Hello");

    [MethodImpl(MethodImplOptions.NoInlining)]
    static void Main()
    {
        theFoo.Frob();
        IFoo i = theFoo;
        i.Frob();
    }
}
```

```fasm
00007FF796607C10 56                   push        rsi  
00007FF796607C11 48 83 EC 20          sub         rsp,20h  
00007FF796607C15 E8 8B A8 D4 FF       call        __GetGCStaticBase_repro_Program (07FF7963524A5h)  
00007FF796607C1A 48 8B F0             mov         rsi,rax  
00007FF796607C1D 48 8B 4E 08          mov         rcx,qword ptr [rsi+8]  
00007FF796607C21 4C 8D 15 A8 EC 27 00 lea         r10,[__InterfaceDispatchCell_repro_IFoo__Frob_repro_Program__Main (07FF7968868D0h)]  
00007FF796607C28 41 FF 12             call        qword ptr [r10]  
00007FF796607C2B 48 8B 4E 08          mov         rcx,qword ptr [rsi+8]  
00007FF796607C2F 38 09                cmp         byte ptr [rcx],cl  
00007FF796607C31 48 8D 0D 30 47 26 00 lea         rcx,[__Str_Hello (07FF79686C368h)]  
00007FF796607C38 E8 13 26 00 00       call        System_Console_System_Console__WriteLine_12 (07FF79660A250h)  
00007FF796607C3D 90                   nop  
00007FF796607C3E 48 83 C4 20          add         rsp,20h  
00007FF796607C42 5E                   pop         rsi  
00007FF796607C43 C3                   ret  
```

Cc @EgorBo

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/74000

It turns out `gtGetClassHandle` used to always return nullptr for such static field loads in R2R ([here](https://github.com/dotnet/runtime/blob/25e50853699d34144dedc91c234c804281169367/src/coreclr/jit/gentree.cpp#L17729-L17731))

Codegen diff for sample in https://github.com/dotnet/runtime/issues/74000: https://www.diffchecker.com/AjNP6YTx

### CODE REVIEW

**Review by AndyAyersMS — COMMENTED** [review]
Is the comment you deleted no longer true?

If so, there may be other assumptions like this in the jit code.

**Comment by EgorBo** [comment]
> Is the comment you deleted no longer true?
> 
> If so, there may be other assumptions like this in the jit code.

Looks like `gtIsStaticGCBaseHelperCall` is only used in one place (was added by you in https://github.com/dotnet/coreclr/pull/20447) - no idea what exactly changed, maybe some refactoring or something like that but for that static field
```csharp
    static IFoo theFoo = new Program();
```
it looks like
```
IND
  ADD
    CALL CORINFO_HELP_READYTORUN_STATIC_BASE
    8 [FldSeq]
```   
so it's not really opaque and returns nullptr for gtGetClassHandle. Maybe it's NativeAOT specific?

For this PR I am waiting for SPMI to fix itself to re-run and see if there any diffs

**Comment by SingleAccretion** [comment]
FWIW, the shape of access to static fields hasn't changed for a very long time (one exception being the attachment of field sequences to outer addresses for boxed statics, which are not relevant here).

Also, I believe the "is static base" check can be simply deleted if there's not a correctness (versioning resilience?) reason we cannot look at declared types of statics under R2R. The field sequence check should be sufficient.

**Comment by AndyAyersMS** [comment]
Odd, what you have now is more or less the way I wrote it initially, long ago, but then revised it. But I can't find any notes from back then so I don't recall why I changed things. 

Nothing else calls `gtIsStaticGCBaseHelperCall` so perhaps it can be removed.

**Comment by EgorBo** [comment]
Oh, forgot about this one, will address the feedback tomorrow

**Comment by EgorBo** [comment]
@AndyAyersMS PTAL, a small clean up, diffs (in crossgen2 collections): https://dev.azure.com/dnceng-public/public/_build/results?buildId=38038&view=ms.vss-build-web.run-extensions-tab

**Review by jakobbotsch — APPROVED** [review]

**Pull request merged**
