### PR TITLE
Don't reset stack level when it is already set to the required value.

### LINKED ISSUE #12305: Setting the stack level to 0 when generating code for each BasicBlock
After [setting the stack level to 0 on genInitialize ](https://github.com/BrianBohe/coreclr/blob/1ee36b6a373fb194799989a8dd0cdfbca9172879/src/jit/codegenlinear.cpp#L117-L119), it seems we don't need to [keep setting it to 0](https://github.com/dotnet/coreclr/blob/master/src/jit/codegenlinear.cpp#L345-L349) for each of the BasicBlocks.

cc @sandreenko 

category:implementation
theme:jit-coding-style
skill-level:beginner
cost:small

### PR DESCRIPTION
**Pull request by sandreenko**
Closes #12305

### CODE REVIEW

**Comment by sandreenko** [comment]
@hoyosjs I have restarted the failed jobs after your email but they are still failing with the same errors:
https://dev.azure.com/dnceng/public/_build/results?buildId=1133075&view=logs&jobId=ec89210f-f03d-506c-f6b4-340afdb2b826&j=46b74d6c-7c41-5389-12e7-c390e5e0d8f9
Started: Today at 5:43 PM

**Comment by hoyosjs** [comment]
Taking a look.

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib, 1 line change to close an issue.

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
I presume there's no x86 asserts with this change?

**Comment by sandreenko** [comment]
> I presume there's no x86 asserts with this change?

I have not seen any in SuperPMI replay and in CI testing.

**Pull request merged**
