### PR TITLE
[release/6.0] Update Ubuntu 16.04 amd64 queues to 22.04

### PR DESCRIPTION
**Pull request by carlossanlop**
Also use the queues with the *.svc suffix

### CODE REVIEW

**Comment by agocke** [comment]
Am I reading this right that this is only the docker host container that's changing?

**Comment by carlossanlop** [comment]
@agocke According to the email, the ask is to only bump the 1604 ones. Did I miss something?

**Review by dougbu — APPROVED** [review]
I like it :grin:

should have mentioned in #92796 as well: using `.svc` queues makes sense across the board. but @ilyas1974 probably won't get too annoyed if some are left behind.

similarly, you should be able to use ubuntu.2204.* queues everywhere you're testing in a Docker container. but we're not currently asking for everyone to stop using ubuntu.1804.*.

**Comment by carlossanlop** [comment]
Ah! Good to know, @dougbu. I suspect that's what @agocke was going to say next. 😄 

I can do that in a separate PR. For now I only wanted to address the main request.

**Comment by agocke** [comment]
What I was asking is: I read `(Alpine.314.Amd64.Open)ubuntu.2204.amd64.open.svc@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64` as saying, "run an alpine docker image on top of an ubuntu.22.04" host OS. So, the actual code running in this test is still seeing the same Alpine image as before, and it's just a question of which OS the kick-off code sees.

Is that right?

**Comment by dougbu** [comment]
> Is that right?

Yes.

**Review by jkoritzinsky — APPROVED** [review]

**Review by agocke — APPROVED** [review]
Great! LGTM

**Pull request merged**
