### PR TITLE
Use CCKeyDerivationPBKDF on iOS

### LINKED ISSUE #76684: Why is `CCKeyDerivationPBKDF` not used in non-macOS Apple platforms?
In iOS, tvOS and Mac Catalyst we use [the managed implementation of PBKDF2](https://github.com/dotnet/runtime/blob/0c9bd9bef97d0ff618541cc068aec01d93c66596/src/libraries/System.Security.Cryptography/src/System.Security.Cryptography.csproj#L1329) for some reason. Why don't we use the native `CCKeyDerivationPBKDF` function, as we do on macOS? [BitWarden has been using it on iOS without problems.](https://github.com/bitwarden/mobile/blob/1e5eab057476295184a97102696a765a2b4387e6/src/iOS.Core/Services/CryptoPrimitiveService.cs)

c.c. @vcsjones who originally wrote the native code.

### PR DESCRIPTION
**Pull request by vcsjones**
This allows the PBKDF2 one-shot to use the platform native `CCKeyDerivationPBKDF` on iOS and tvOS.

According to [Apple's headers](https://github.com/apple-oss-distributions/CommonCrypto/blob/06c4e37bc508d502031035d8606ade275d6c0d82/include/CommonKeyDerivation.h#L96-L100), the API is available on iOS starting in 5.0. 

Closes https://github.com/dotnet/runtime/issues/76684

### CODE REVIEW

**Review by filipnavara — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
FYI we now have `/azp run runtime-ioslike` pipeline that allows triggering just iOS/tvOS instead of the whole runtime-extra-platform ones.

Though I just noticed for some reason the iOS arm64 job only ran four test suites so something is broken (it only ran the smoke tests subset which doesn't include crypto).

**Comment by vcsjones** [comment]
> Though I just noticed for some reason the iOS arm64 job only ran four test suites so something is broken

@akoeplinger should this PR be held until that is fixed so we can validate the changes?

**Comment by steveisok** [comment]
Once https://github.com/dotnet/runtime/pull/76715 lands, merge with main and you can trigger `/azp run runtime-ioslike` to get full coverage.

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
@filipnavara pointed out that iOS support implies some amount of tvOS support. I confirmed I was able to build a tvOS project using this API without availability errors, so I enabled this for tvOS as well.

**Review by filipnavara — APPROVED** [review]

**Comment by steveisok** [comment]
@vcsjones https://github.com/dotnet/runtime/pull/76715 was merged, so if you sync with main you can run the full iOS/tvOS tests

**Review by bartonjs — APPROVED** [review]

**Comment by steveisok** [comment]
looks like tvOS failures are unrelated.  I think this is good to go.

**Pull request merged**
