### PR TITLE
Make some p/invokes blittable

### PR DESCRIPTION
**Pull request by elinor-fung**
Some more p/invokes could easily be made blittable (inlinable during JIT) - found while prototyping a `DllImport` source generator.

cc @AaronRobinsonMSFT @jkoritzinsky

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Comment by GrabYourPitchforks** [comment]
Is there any concern that switching between _ref_ / _out_ and raw pointers might confuse callers as to which variables they're required to zero-init and which variables the callee will zero-init?

**Comment by AaronRobinsonMSFT** [comment]
> Is there any concern that switching between ref / out and raw pointers might confuse callers as to which variables they're required to zero-init and which variables the callee will zero-init?

@GrabYourPitchforks Aren't all locals zero-init right now? I didn't see any uses of the [`SkipLocalsInitAttribute`](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.skiplocalsinitattribute).

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by GrabYourPitchforks** [comment]
@AaronRobinsonMSFT Nearly all libraries auto-compile with `SkipLocalsInit` injected by the build process.

https://github.com/dotnet/runtime/blob/663c40dbc4ccedf82e38e96391c28695da0e418f/src/libraries/Directory.Build.targets#L279-L295

**Comment by jkotas** [comment]
`SkipLocalsInitAttribute` is set globally for the whole repo.

I am not particularly worried about the changes in this PR. THe blast radius is minimal (just affect immediate wrappers that deal with other interop intricacies), and some of the changes look like a geneneral improvement:
- `NtCreateFile` had a mix of raw pointers and out/ref already. It makes sense to use all raw pointers for consitency.
- `out` annotation was not quite correct on GetWindowThreadProcessId due to https://github.com/dotnet/runtime/pull/54370/files#diff-62e7105b6afe4f31872e90f2a84671553525312b7cf8e7a6d83b74556bff624aR53

**Comment by AaronRobinsonMSFT** [comment]
>Nearly all libraries auto-compile with SkipLocalsInit injected by the build process.

Didn't know that - thanks.

**Pull request merged**
