### PR TITLE
Reload UserSecrets on changed for host

### LINKED ISSUE #40020: UserSecrets should reload on changed
Today the host will reload appsettings.json if it changes.
https://github.com/dotnet/runtime/blob/4b8c5fe2b4757f77f5699d49a072fcb123d2e33b/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L74-L77

However, it does not reload the user secrets file.
https://github.com/dotnet/runtime/blob/4b8c5fe2b4757f77f5699d49a072fcb123d2e33b/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L84
See
https://github.com/dotnet/runtime/blob/4b8c5fe2b4757f77f5699d49a072fcb123d2e33b/src/libraries/Microsoft.Extensions.Configuration.UserSecrets/src/UserSecretsConfigurationExtensions.cs#L119

These are similar resources and should have similar functionality.

### PR DESCRIPTION
**Pull request by Marusyk**
Just added `reloadOnChange`  to `AddUserSecrets`
It's draft because researching how to write tests for it (is it possible for UserSecrets )

Fixes #40020

Please review
Thank you in advance

### CODE REVIEW

**Comment by Marusyk** [comment]
I tried to add some tests but cannot build it locally:

> C:\Users\rmarusyk\source\runtime\eng\python.targets(8,5): error MSB3073: The command "py -3 -c "import sys; sys.stdout.write(sys.executable)" 2> nul || python3 -c "import sys; sys.stdout.write(sys.executable)" 2> nul || python -c "import sys; sys.stdout.write(sys.executable)" 2> nul" exited with code 9009. [C:\Users\rmarusyk\source\runtime\src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:37.06
> Build failed.

**Comment by eerhardt** [comment]
I think it would be good to add a unit test here.

https://github.com/dotnet/runtime/tree/master/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests

**Comment by Marusyk** [comment]
Yeah, exactly. But I can't build anything to check if my test work

**Comment by eerhardt** [comment]
> But I can't build anything to check if my test work

Have you checked out the machine requirements? https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md.

Also, with recent changes in the repo, you should be able to just open the https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Hosting/Microsoft.Extensions.Hosting.sln in VS 2019 and build/test from there.

**Comment by Marusyk** [comment]
error MSB3073: The command ""C:\Users\rmarusyk\source\runtime\src\libraries\Native\build-native.cmd" x64 Debug outconfig net5.0-Windows_NT-Debug-x64 -os Windows_NT" exited with code 1.

**Comment by maryamariyan** [comment]
Here's a walkthrough of the steps you would generally need to take while working locally on the runtime repo:

1) Check [build requirements](https://github.com/dotnet/runtime/tree/master/docs/workflow/requirements).
2) Check the  [quick start](https://github.com/dotnet/runtime/tree/master/docs/workflow/building/libraries) on how to build the runtime repo libraries.
3) Then you could follow instructions for [running tests](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing.md), or just create a sample console/web application project and [add a reference](https://gist.github.com/maryamariyan/fc54328792abe339b3c08e9fa008dea8) to the Extensions library dll you built, in your case Microsoft.Extensions.Hosting and check behavior locally.

Note to takeaway here: If you're having a problem with building locally it is likely that one of the build requirements explained in step 1 above is missing for you.

**Comment by Marusyk** [comment]
I'm going to close this PR. I can't build a unit test for Microsoft.Extensions.Hosting project in VS. For other libraries everything is ok, but Microsoft.Extensions.Hosting:
image

I also tried
`.\build.cmd -projects src\libraries\*\Microsoft.Extensions.Hosting.TestApp.sln -f net5 -c Debug`

Before the start, I run .\build.cmd with the successful build. So, I can't add any unit tests without debugging.

**Comment by eerhardt** [comment]
@ViktorHofer @safern - any thoughts on the above? Have you seen these errors before?

**Comment by safern** [comment]
doing `build.cmd` won't restore the test projects. So, IIRC, you would need to run `dotnet restore` or `dotnet build` on the test csproj before opening on VS. @Marusyk, did you try that?

**Comment by ViktorHofer** [comment]
Jep you likely missed restore. You can use the `-vs` switch which a) uses the repo locally acquired SDK and b) implicitly restores the solution.

.\build.cmd -vs src\libraries\*\Microsoft.Extensions.Hosting.TestApp.sln

**Comment by Marusyk** [comment]
I've tried it too. 
I'm not only used `build.cmd` and as you can see I run it in VS with restore- the same errors.

**Comment by ViktorHofer** [comment]
Restore inside VS doesn't work well for some projects (ones which multi-target for different rids). That's why I suggest to do a CLI restore.

**Pull request closed without merging**
