### PR TITLE
Console.Unix: fix missing terminal configuration on SIGINT/SIGQUIT/SGCONT.

### LINKED ISSUE #64166: Console.ReadLine on Ubuntu in WSL disables echo of characters when cancelled with Ctrl-C
### Description

After exiting a program with ctrl-c, that was waiting for input via Console.ReadLine leaves the command line in bad state. 

### Reproduction Steps

```
mkdir tmp && cd tmp && dotnet new console
echo 'Console.WriteLine("press ctrl-c"); Console.ReadLine();' > Program.cs
dotnet run
```

Press ctrl-c as the program asks for. Now you are back on the command line.  Try to type anything, you will not see the characters typed.

### Expected behavior

Terminal behaves normally as if the program was never run.

### Actual behavior

You will not see the characters you type. Another thing I recognized that when executing `echo x` it does not print a newline anymore but overwrites part of the prompt.

### Regression?

_No response_

### Known Workarounds

Execute `tput reset` in bash.

### Configuration

```
dotnet --version
6.0.101

uname -srvpio
Linux 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 GNU/Linux

cat /etc/os-release
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute

wsl --status
Default Distribution: Ubuntu-CommPrev
Default Version: 2

Windows Subsystem for Linux was last updated on 09.10.2021
WSL automatic updates are on.

Kernel version: 5.10.60.1
```

And also tested on Ubuntu 20.04 LTS on WSL2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tmds**
The introduction of the managed API for signal handling (PosixSignal)
inadvertently caused terminal configuration to no longer be performed
when no managed handlers are registered.

This adds back the unconditional registration for SIGINT/SIGQUIT/SIGCONT.

The missing registrations can cause the terminal to stop echoing when an
application terminates on Ctrl-C.

Regressed in https://github.com/dotnet/runtime/pull/54136.
Fixes https://github.com/dotnet/runtime/issues/64166.

cc @stephentoub @adamsitnik @danielbisar

### CODE REVIEW

**Review by stephentoub — COMMENTED** [review]
Thanks.  Is there any reasonable way to add a test for this?

**Comment by tmds** [comment]
>  Is there any reasonable way to add a test for this?

I thought about it, and it's not easy to write an automated test for this. A good test would have something other than .NET as a parent because .NET changes terminal settings also as child processes are created/reaped.

**Comment by danielbisar** [comment]
I don't know the code in detail but in theory you could at least test that the right methods using an interface and mocking. Standard software development... I guess the actual changes to the terminal must be tested manually. Another way would be to replace STDOUT with a mock so you could check if the correct escape sequences are received...

**Comment by tmds** [comment]
@stephentoub @adamsitnik is this good to be merged?

After it sat on `main` for a while, can we backport it to 6.0?

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
Thanks, Tom.

**Comment by adamsitnik** [comment]
@tmds  thanks for the fix! I am going to start the backport procedure now, as I expect that it will take us few weeks to get it merged

/backport to release/6.0

**Comment by danmoseley** [comment]
I closed the backport PR as stale. cc @dotnet/area-system-console since @tmds is requesting we backport this. One of them would have to champion it, add the template, etc.

**Pull request merged**
