### PR TITLE
Superpmi collect asyncio fix

### PR DESCRIPTION
**Pull request by TIHan**
https://github.com/dotnet/runtime/issues/89618

`get_running_loop` doesn't exist on older versions of Python below 3.7 - so use `get_event_loop` for those versions.

### CODE REVIEW

**Comment by TIHan** [comment]
@dotnet/jit-contrib this is ready @BruceForstall

**Comment by BruceForstall** [comment]
We already require Python >= 3.7. From `main`:
```
    # await/async requires python >= 3.7
    if sys.version_info.major < 3 and sys.version_info.minor < 7:
        print("Error, language features require the latest python version.")
        print("Please install python 3.7 or greater")
```

Although that logic is busted and should be:
```
    if (sys.version_info.major < 3) or ((sys.version_info.major == 3) and (sys.version_info.minor < 7)):
```

**Comment by BruceForstall** [comment]
What version of Python is running on the CI machines?

**Comment by markples** [comment]
I believe the pythonic way to express that is
```
assert sys.version_info >= (3, 7), "Please install python 3.7 or greater"
```
(tuple comparison is done lexicographically, but beware that this continues with an implicit zero, so `version <= (3,6)` and `version < (3,7)` are not the same)

**Comment by TIHan** [comment]
> What version of Python is running on the CI machines?

Had one of the docker images and it is using 3.6.9.

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
