### PR TITLE
[release/9.0-staging][wasm] Workaround incorrect mono restore when building WBT

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Comment by carlossanlop** [comment]
Is staging correct? We don't want it to go straight to base?

**Comment by lewing** [comment]
test infrastructure only change

**Comment by carlossanlop** [comment]
Tell mode: infra only. Approved.

**Comment by lewing** [comment]
> Is staging correct? We don't want it to go straight to base?

I'm happy to retarget?

**Review by carlossanlop — APPROVED** [review]

**Comment by carlossanlop** [comment]
If not, staging is fine and we can monitor the builds to see if it worked or not.

**Comment by lewing** [comment]
> If not, staging is fine and we can monitor the builds to see if it worked or not.

it should make the tests green but it isn't required for the product

**Comment by carlossanlop** [comment]
Oh I missed that it was for tests, sorry. Carry on then. Staging it is.

**Review by maraf — APPROVED** [review]

**Comment by lewing** [comment]
> There's a different failure now though:
> 
> > dotnet_install: Error: Could not find `.NET Core SDK` with version = 9.0.102

I think the failure is a result of https://github.com/dotnet/runtime/pull/109304 updating to an unreleased sdk

**Pull request merged**
