### PR TITLE
Cleanup unneeded codes regarding `unsafe`

### PR DESCRIPTION
**Pull request by Gnbrkm41**
The `unsafe` keywords/blocks removed in this code are unnecessary and they compile fine without one. I'm not sure why they are added... but they're unnecessary and introduces extra indentations.

In addition, there are comments regarding the inline eligibility of certain `unsafe` methods in `XmlCharType`; From what I see they seem to get inlined just fine. (See [SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgBEBLbAcwDsJcGDmFwBuGvSasAkgHlxtRsxYAVABaxsAEw69uCycoAa+ADYKJAZiakGAYQYBvGg1dNrwCBFMMAsgAoAShc3Z2o3CKYAdgYTUzs1bCgVAE8ABxgWaV5BbF4wTOlcAHU1DgwYAGU07AL/AHJsesCFCIBfGg7qGgB6HoYAGWEYHJgtBgwICbUYBhYAOQBRFQYAMQgAV14tbCEIXgYtrRgoBn3Z6AZ8aFmeWBh8EYxcFl7+9VmF5bXN7d2OfYMUzDUa4aYcMEAMw4plmkwYKU2h22J2ms180hWwIKo1e1D6DEqMDhM0G0jsi3mlUWDGhsIYujRDDSUAgACsYGAMAxWRBuZDLtdYAzeAKoPh/vs8TReNhHrgagUpCw4jQwhE+v0ADy4Db4CVQFIAPhCrk1rg+sTMCSSqQyNgZYI2uDGtMuAEcNsIANYMMCJKC1CqnDDpWawSB8coA3imhjmhgAdzK/sdZzSQnwHAAXq6xUzoVBBAxyKQYngwBwOH6A0GTi84+atT1dfqksa47pg7KfFtcNhIbNBFANlyrfEA3aYHH1ZEzf1KhsoKzuLtZpAchg8s84xEuyce379sWu4SlwAJDjcNSVLdQbkAXgYdAQWgAHHQ6KINf1yOQ6OQJYvggu5uPuUCHhuJ68Nyi5QJe16LNsDBPi+WjAJCkKtHOIrdtgPhQdyp5wQMECJreSSPs+r5gJ+35uASf4ASW5AICB4Q4eBkHHkRMFnlApGJkh4yoa+mFYaBrhcfhR6brh/G+HgvqiZCtFfj+LF/ixbE0JJ8b9DagZcvWDDHNCvCuoyGCkkYvgDCWLCMOsS7WQwiw6HssYcXOBKlOUMAKrU64BmCcBwISnKeQwpAsNYADalgALp6QSAwwBgwaheFACCaQZNsHAIAwABCDBxW+KDJd5kQEhR966NwDDzHY8xysFSR1kWDBhRFXIxtFsVlQArIlDD+HVQh6E1bU1h1xldYm5RqJs3L1CAzQpf0zWtY8s1GZl3XhUSfWAjF8WVThbj+Dt7X7SZi3WStDBrRt1UaYZnWmbs2B7Z1WW9VFMW2HFpBVZdBIAAobMAHBaIZDAgCAT4MAAxAgpCMIQqMIGwDBY2j2V42V2BwNm2VwAAWnQcAAJyjVjcVwPUQQANRoCwPRIwA/KIACEABUKPEMQAAkAD6ACko3HYDg0QJCDAKpyenSQRPHyZCfkVIFSpPuQ2FzqrsnQfyaUZaiT6kAbkRG4RGvNRNN2VA4T4oNbe4wQeMl26ekLbW1zsoQwb7u2BnsQd76u+4ZbDfUH5BIKHUnh9xcm+/7jxxCgsxPpYVsqynkdp3xkIqDACBUagSe4V7avF/y2UZVAABq+EbDnJakCHulvQx/QwxgEppG6pzENY0i4/6c0HeFgED8yqJT3dpwvow4Uvh+378L980MEa1EfmmP0QwAqsVAzkgwE97XpLIcAAbmuxvcswjC4GLUPANi0haMV5RD0HAARAAHQ2KQFAn5QGfkgRsTCwBgCgIHJhUB4lISgLfFEZBsDMIwCgZgyEgCLC93nIrHMFwFZxEMlOCY2Av7TmIcyKAD8n52y9HxQyENWQZHqgFSoZCg7+DYRgQIS8WCKQQK3Uw7cGAsxLEQ8G/RmBICBBAMAvp8yUMnGGGwt8mGPwqFIZREBgAcjHO/Uiaj5E4Tvvo2YSizgmMioSLcQgwAWO9HpWcl1XDcHSnpCIXjvF7gVv4cxqjlJPl4BsUwphggMMuoEoJc5jGmO5FMSJMBEwONSUEauSSr7h1MOEsYLA7AQHwDUWAiwEBTz0DALUKTIpGn8LABWYS1FoDOJ0qJMSWj+Jwl0fJERiAxHad6PJbhBkDJ7pdGxT97H328P8ekwAUgVH5orMWHCuEnCEAFauRtVnrL2pwiA3C9liF0cwgx9jiAoAKeUbIuR8gwCCJ4/prgilqLGhRVx7i4n5MSUkjgIT37bLObsjgAUGC80idE2JHzIhAqGdECZc4uiIoiCfXgEpZS+K0L4B40AUi3k0PgK4DxSUwDlAI7FuKeBjEJUKElGAyWBFDBkeW/g4jFCYcGQILBsq4BdPgL+KQWAAHF0qKV4CCgKGAABKAVNhQAKFSuU/hAGaNtGGFgMNeCAL6fEnCbAYDAA2NwQVwrdn+EePgdV+AWBpT0K5B8T5wXnKhbgPhuYjWYrcEcmAGz/SnLSGCJ8dqHUsAhgIaM+wY3gTRZEdQmgtBiKJYaYqSQmEnFySQ9YpxEzUt9Ha4lVwIDHFMGCfw0hsqoABSizZHrIXQqfCGrhlzjWuCmeimZ1i9FP21ckMM/hA3BoDKGltuAG1zmRZEU15rLVCpdPeUJWyJ07J4WCWFDAemxKTdZCELAl6Tq3UHE9m6LnVwxQwsehjxxUO0U8rcLz3ldoYL4jAiK52XRBWNMFG6IVnrdbu+FM6hk/qSdkR5m48h1CNY2hgPahkjN3Zkh9WiMhrubVuhDSTkPtD7T5LasgVCLBAAwdQEIKWPXGItGJu6+QMGALMXQwILLjFHZybAzpWPcl42CMdJzL1evA8MjwXgfBFC1lURUryl41jE6ERFqH/AXqAxcuK/pRoADJaQyZ1jAQIMLULXqIzVEjZGKNUbBI8WjSYYQ+H4NyFjIp2Oui42AHjLoGT8ZdIJtZQbhMadE3pO9nhvBX1wBnKoDVYSGTUwGRTb78mqfU56gKWm1C6dpDF52xmd1fj0jehRTVSPkco2UWz6Vlp0cc4xlzrHeDuc4yxrzvHfOHH88xwL46kinouUp1w4XJNRcdi1AOcWYAJYU/6IbTgVMxES/1kTmXtMMD037OwjsA52AK6Z4r5nxPMdG0UJ2U2ZtJbmylpJqGzsTceHwvQ8WAyJeM4QLGqYQMvTM90BhBJ5jles1VmjtWHMMec8xprLWxpte83xrr0KhPpanfNkbkWigx2+st0412GGQeG0tlHW6ss5chFjrc+3ny/c2mVcgSUGCf1hvDRGyM0YYyJmjXG+MECEwZiTMmlNqZ0yJozZmgQ2Yc25nzQWwtxZSwBv1M6Zw2kZDAGFiTGPcBM7hq92bah5sE4ZCE1MWoxpL0CBvOg82An+sJ/+j+0Nv6/3/tgNIWW977wunp/wgEtRm8Sxt6iqxAih5M9TxFBGcKochPhF0NP/vvHLhgeG7qAyxy3N1Jw1FsqdJfGwTp9QtT1ELzpkvz1Er1CQ7TwHVnKvUbs2D+jTmmOubY7oDzcOOvlERwF45xPBsFzwj4CLUncBlwrpdpIyX8eLfN4BjLuBSdB9LsnqnRWGElZwgSRurLJHt1T/YdPcdwqOBz3nnGF+aaF+L4Xo05f6hl8L8A+oD/AFV6jyQ2vFWbOg4reDlvRrNzDvVrbjbvPzJHXrYLRfebQ5U7XAXfJhc1CoffabPXK7A3G7IJNLBfKdZfTbRA1A9fBPUrWyeyVgJyFVVydyONA4MyXQWg3ATaGvIHevarezZvBrKHYAjjWHMAnzHvATHrfvXA3DDXE7LXM2YMHHGfBJOfHHAbL1fA2kKQk4Ygw7P7Urb/YHBvGrf/TgyHNvZrEAvg9rAQiAvvILAfULRPNgv/cYIQ6yWYMghgFAVyMYWg3dGaJeT6QMOpJg29TXMfGLQyLOeTDAw3eQ6wtbbLFfGLMI9QzfI7PuOwxvf/RwmyOyVw9wjyfqWUXaHw3ePw3xAIy6dHMfcbG6UIswbOGQvHOQ99O7XAVQqAN7PGT7NQFCJ8eoMWeoEg7fd4EHNIhw7rJw2ILItwzojwqKfI26XwvIEo8Q0fKLKogMMIuozA2fRomIe7VYpIdYubdomsLo56dafo4jBgTgbgHvYY0o6PawexZYooK48oDYyI7YgpBVBY8Ii/SwOgX4mmPDXtTQgY/iFcJ+W4ofWue9J43ABCG8JccEiofwU8eonCI3O7XgL4upRLTpOCeEiaPEi8K8NQYSIEyILfQ2QuHwR4+AwSOCJE15VEzYho1LHYrE743E/ieku8DAIkgSMiMk84m2akmE+AhkiAVcZE5k94tkz4zk/0fkgk3k/kwSIUjQqEiOGkhOeSMpUVDvCUqUtApIFEviIpRMQyTpU8Moa8QyWU27Jbc0+GI6JcHkyid7MafwG0tQZ0/iZU90hgf3ICYzWRF8f8aBYUj2Yfe9O5QkNIYEDAQ0tcBLVE8pfVMYS0s4DYbkBTJ0gMTpJ6BTb0u0rA7xU8e+c9NMkA30sM6BDffJPM6fJ8HHQIcaV0siCaGRBgCsiWICcBcky6YspLZsi3Ns+CEkzs2RCs38OgfsyMsOaM2E2QZrFIAzOTfwV+RWVle07AnY3AZc0wVcsobWOTYoJaGNXAUJbck4uAfWDU2wj6Xef0Tkb0BqM4A4V+O4qk6M08IoA8o8/yQzM86yC8jc/8LcqAHcss0FVlcPPdG3ZTd9CIfMU0oiIOdSasM3YcJ1EYbgayb8DgFmFmBC2dO3G2EJBQ1bJfYcOKDgRKMnNcoKYzEDa3Mi23JCh0hkJNS6T/bxXiwjD428+c5OH8viP8lcinbAMCt+bc0s39GC04HdeC79MilC08asUzBkQMiCnCl1NQAioikipFNisCCi6I6i1lWi+ilfSS5i1CIy1kxDTiEJasWRQCI0J8bC51PCzoj7GFbla0TDQoOEicxEyUtcK8qAKy4zHTPTIdKcLIZojssKo0yK2irs8gRKUPBypJI3RDVDDgbi/DEyucGAKtehJy9EkqssoioqoJfi4qji7tSPOfIS+839UU2krXf8l454aSiCq0viXIe8C8wa7kWEXgKCy6BdC1K1FdDASKuCsDJNGapda1VdYajAC8rsiawMzy1lXSnygck1M1Wa5dG1Ta7arUfaqAQ66yP1d9NSviDSrcyiC8gi7Sy6gQHakYAy4ilSpq43MaXmZ4q8V4miui0PMivK6PGIWPcquq6vd9Bq+3VlduYSmuLU+SIoT+Z3fq4cKa5y/9WCpSsDAGxDJ6tCzSzCnS7y/ChkQy6G6qv9fwEG7XaGZnV7CGrKnK0iwGsomIQq6qlGiklqwSu8pIkEi43/YYiYeVMEZMGrVEH6R+KRVjMERkH6a4++EYHkb4hzVyNkZ0NJCyOWwQb8TahgPIcYEYcYXAZaaJcYVzQibcL8yIOZG5HUp4jknE8stuGAMa16+8QO22wmucVauai63kvahgUOpNVTIRVs1W6RcKTa4za6saRO/wW2rPNOhPFGP9Mguwc8bKBVFQAATQhkWDFglUpDFgVUWEqFkBPgVQpGYIfIrVmHzF8QskDEmkanit1X1RoToStuQnflxuEB/j/kHjd3btK3NRhHGEgDbGQncwoz9FwDAAwx1QyGPTBB6C0BACLpLrLsrurtrvmHrsbubtbsWHnvuJjPuUUl0H8CkDoDilGiSG4DBGMyN1ZRSAW0BugwwGfTg1eQesQwJB7pOCfknrAB/mY1dzSDIudGWnvE/qQdnuHgySyTQegAwDiit091cMSkRspq0ups+sdy/inrYDuv0q0pZktj/uqoobZCDgnqdzoass6VMDwCoi4doYQbYHSrcrIYYA4Yzv4fNskcMqAcqrnAHiHjig4aNC93pmbPwfvFbL9wDw4b0xfBD2OpRRFoErIrKRyG8EyF5X8k1Q9vXHVk3KEedxnoASfGAUAUNXIcuFQsoepy0rN2UbdwYb+tYf5rcEsdwGsZYFseRJAVAUcDoBAAQBQDaEAU6WCfd0hsRrMbcGYBpk1U8dEG8bIoKdyWSOwPArpBgBugEStqgB/oYZOMYGMy5gYC1UCt3syH1UAQRgaZ/qIbIYsePBibideQ6bibfMHvtEKODEYRC2hXhCSbaBYDWYydpBhFqZmkgcbVWC2YdVpHDTQyyX2dhAdTfpqZuk6TOZgF8E7tKU0AMRMe8RQvkheowu0pwwuR9RgA+uYdcLoBpmUXCcUaOdib5QmYAxW0WdwCtM6QgWBYYBeZ4tUpeDsCKRdAqcBvKY6a0HOBYD6ZRcmURS8wwFTDfuqQKAzH6lmFBcbXKeJbnFxcASpZgBpf2AoxWY2cyEJWFQZWRaTV4q6BRltpBTjC6C6CAA))

### CODE REVIEW

**Comment by Gnbrkm41** [comment]
https://github.com/dotnet/runtime/blob/0647ec314948904319da5eb15e9931f7c85ed1e2/src/libraries/System.Private.Xml/src/System/Xml/XmlConvert.cs#L1429

Do we still compile for SilverLight...?

**Comment by Gnbrkm41** [comment]
https://github.com/dotnet/runtime/blob/0647ec314948904319da5eb15e9931f7c85ed1e2/src/libraries/System.Private.Xml/src/System/Xml/Xsl/Runtime/XslNumber.cs#L337

Remove the `else` block? I'm not sure why it's left like this.

**Review by jkotas — APPROVED** [review]

**Comment by jkotas** [comment]
> Do we still compile for SilverLight...?

We do not. The whole method can be removed. This cleanup can be done in a follow up PR. This change looks good as is.

**Comment by jkotas** [comment]
Thank you!

**Pull request merged**
