### PR TITLE
Turn unreachable basic blocks into an infinite loop

### LINKED ISSUE #81339: Investigate removing nops from substitutions
https://github.com/dotnet/runtime/pull/80896#discussion_r1088731902

SR.GetResourceString is not getting inlined because the original method body was pretty big. What we're left with after rewriting is just a simple `mov rcx, rax`.

We'd need to basically redo how substitutions are processed.

I'm putting this in the future milestone. Ideally we should not have this code - we should use RyuJIT to do IL scanning and introduce ability to feed it substitutions. RyuJIT is much better at constant propagation than anything we would write in C#. No point maintaining two codebases. Just filing this for tracking.

### LINKED ISSUE #97758: [NativeAOT] Assert in ILC when compiling System.Data.DataSetExtensions.Tests in Debug build
```
"/home/navara/runtime/artifacts/bin/coreclr/linux.arm.Debug/x64/ilc/ilc" @"/home/navara/runtime/artifacts/obj/System.Data.DataSetExtensions.Tests/Debug/net9.0/native/System.Data.DataSetExtensions.Tests.ilc.rsp"
Process terminated. Assertion failed.
   at ILCompiler.Dataflow.MethodBodyScanner.InterproceduralScan(MethodIL startingMethodBody) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/MethodBodyScanner.cs:line 332
   at ILCompiler.Dataflow.ReflectionMethodBodyScanner.InterproceduralScan(MethodIL methodBody) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs:line 103
   at ILCompiler.Dataflow.ReflectionMethodBodyScanner.ScanAndProcessReturnValue(NodeFactory factory, FlowAnnotations annotations, Logger logger, MethodIL methodBody) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs:line 128
   at ILCompiler.DependencyAnalysis.DataflowAnalyzedMethodNode.GetStaticDependencies(NodeFactory factory) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/DataflowAnalyzedMethodNode.cs:line 35
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1 node) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 182
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1 node) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 222
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 257
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 308
   at ILCompiler.RyuJitCompilation.CompileInternal(String outputFile, ObjectDumper dumper) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.RyuJit/Compiler/RyuJitCompilation.cs:line 96
   at ILCompiler.Compilation.ILCompiler.ICompilation.Compile(String outputFile, ObjectDumper dumper) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/Compilation.cs:line 528
   at ILCompiler.Program.Run() in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler/Program.cs:line 585
   at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass236_0.<.ctor>b__0(ParseResult result) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler/ILCompilerRootCommand.cs:line 292
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at ILCompiler.Program.Main(String[] args) in /home/navara/runtime/src/coreclr/tools/aot/ILCompiler/Program.cs:line 753
```

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #97758.
Fixes #81339.

Instead of padding unreachable basic blocks with nops followed by `br $-2`, we now turn unreachable basic blocks into _just_ `br $-2`, no nops (and matching basic block size) needed. This means offsets within the method body can shuffle around and we fix them up.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by jkotas** [comment]
Is it worth it to add a test?

**Comment by MichalStrehovsky** [comment]
> Is it worth it to add a test?

The regression test is quite non-sensical on it's own, but added anyway.

**Comment by MichalStrehovsky** [comment]
Hm, there's a test that ends up having this IL:

```
// [repro]FeatureCheckCombinations.MeetFeaturesEmptyIntersection(bool)
.method void MeetFeaturesEmptyIntersection(bool) cil managed
{
  // Code size: 53
  .maxstack 2
  .locals init (bool V_0,
      bool V_1,
      bool V_2)

  IL_0000:  nop
  IL_0001:  ldarg.0
  IL_0002:  stloc.0
  IL_0003:  ldloc.0
  IL_0004:  brfalse.s   IL_0018
  IL_0006:  nop
  IL_0007:  call        bool [System.Private.CoreLib]System.Runtime.CompilerServices.RuntimeFeature::get_IsDynamicCodeSupported()
  IL_000C:  ldc.i4.0
  IL_000D:  ceq
  IL_000F:  stloc.1
  IL_0010:  ldloc.1
  IL_0011:  brfalse.s   IL_0015
  IL_0013:  ldnull
  IL_0014:  throw
  IL_0015:  nop
  IL_0016:  br.s        IL_0028
  IL_0018:  nop
  IL_0019:  call        bool [System.Private.CoreLib]System.Runtime.CompilerServices.RuntimeFeature::get_IsDynamicCodeSupported()
  IL_001E:  ldc.i4.0
  IL_001F:  ceq
  IL_0021:  stloc.2
  IL_0022:  ldloc.2
  IL_0023:  brfalse.s   IL_0027
  IL_0025:  ldnull
  IL_0026:  throw
  IL_0027:  nop
  IL_0028:  call        void FeatureCheckCombinations::RequiresUnreferencedCode()
  IL_002D:  nop
  IL_002E:  call        void FeatureCheckCombinations::RequiresDynamicCode()
  IL_0033:  nop
  IL_0034:  ret
}
```

We now fail eliminating the part from IL_0027 because 0027 is a branch target and 0028 is a branch target and this logic ends up marking 0027 because it's too short.

The test has a point.

This substitution code is probably too garbage to fix this. It needs to be rewritten.

**Comment by MichalStrehovsky** [comment]
I made a different fix that still avoids doing a rewrite.

Instead of padding unreachable basic blocks with nops followed by `br $-2`, we now turn unreachable basic blocks into _just_ `br $-2`, no nops (and matching basic block size) needed. This means offsets within the method body can shuffle around and we fix them up.

This now also fixes #81339.

**Review by jkotas — APPROVED** [review]
This looks better

**Pull request merged**
