### PR TITLE
Fix loop hoisting float var profitability calculation

### LINKED ISSUE #82351: JIT: hoisting float var profitability mis-categorizes SIMD types
`lvaFloatVars` is set using `varTypeIsFloating()`, which doesn't include SIMD register types. The count of these registers is used in `Compiler::optIsProfitableToHoistTree()` to determine hoisting profitability of a tree, also using `varTypeIsFloating()`. The effect is probably that SIMD type trees are treated as using integer registers for hoisting profitability calculations.

`varTypeUsesFloatReg()` should probably be used instead.

### PR DESCRIPTION
**Pull request by BruceForstall**
Treat SIMD as float vars.

Fixes https://github.com/dotnet/runtime/issues/82351

### CODE REVIEW

**Comment by BruceForstall** [comment]
Depends on https://github.com/dotnet/runtime/pull/82331

**Comment by BruceForstall** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=176944&view=ms.vss-build-web.run-extensions-tab)

**Comment by BruceForstall** [comment]
(Modest) diffs show better hoisting: both hoisting int-reg expressions in loops with lots of SIMD, as well as SIMD expressions in loops with lots of int-regs.

**Comment by BruceForstall** [comment]
@AndyAyersMS PTAL
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Odd, there are asserts in JitStressRegs=8:
```
[20:59:47] Invoking: C:\h\w\AB4909BC\p\superpmi.exe -v ewmi -r C:\h\w\AB4909BC\t\tmpc3utju9i\repro -p -jitoption JitStressRegs=8 -f C:\h\w\AB4909BC\t\tmpc3utju9i\libraries.pmi.windows.x64.checked.mch_fail.mcl -metricsSummary C:\h\w\AB4909BC\t\tmpc3utju9i\libraries.pmi.windows.x64.checked.mch_metrics.csv C:\h\w\AB4909BC\p\clrjit_win_x64_x64.dll C:\h\w\AB4909BC\p\artifacts\spmi\mch\b0e1ce41-2339-491d-ab72-736a8d233ea1.windows.x64\libraries.pmi.windows.x64.checked.mch

[21:01:47] ERROR: Exception thrown: DebugBreak or AV Exception 123

[21:01:47] ERROR: Method 13421 of size 9 failed to load and compile correctly (C:\h\w\AB4909BC\p\clrjit_win_x64_x64.dll).

[21:01:47] ERROR: Exception thrown: DebugBreak or AV Exception 123

[21:01:47] ERROR: Method 13429 of size 9 failed to load and compile correctly (C:\h\w\AB4909BC\p\clrjit_win_x64_x64.dll).

[21:01:47] ERROR: Exception thrown: DebugBreak or AV Exception 123

[21:01:47] ERROR: Method 13422 of size 9 failed to load and compile correctly (C:\h\w\AB4909BC\p\clrjit_win_x64_x64.dll).

[21:01:47] ERROR: Exception thrown: DebugBreak or AV Exception 123

[21:01:47] ERROR: Method 13423 of size 9 failed to load and compile correctly (C:\h\w\AB4909BC\p\clrjit_win_x64_x64.dll).

[21:01:47] ERROR: Exception thrown: DebugBreak or AV Exception 123

[21:01:47] ERROR: Method 13420 of size 9 failed to load and compile correctly (C:\h\w\AB4909BC\p\clrjit_win_x64_x64.dll).

[21:01:47] ERROR: Exception thrown: DebugBreak or AV Exception 123

[21:01:47] ERROR: Method 13428 of size 9 failed to load and compile correctly (C:\h\w\AB4909BC\p\clrjit_win_x64_x64.dll).

[21:01:47] ISSUE: <ASSERT> #13421 D:\a\_work\1\s\src\coreclr\jit\gentree.h (8125) - Assertion failed 'unreached' in 'System.Runtime.Intrinsics.X86.X86Base:DivRem(uint,int,int):System.ValueTuple`2[int,int]' during 'LSRA allocate' (IL size 9; hash 0xa7aea283; FullOpts)

[21:01:47] ISSUE: <ASSERT> #13429 D:\a\_work\1\s\src\coreclr\jit\gentree.h (8125) - Assertion failed 'unreached' in 'System.Runtime.Intrinsics.X86.X86Base+X64:DivRem(ulong,long,long):System.ValueTuple`2[long,long]' during 'LSRA allocate' (IL size 9; hash 0x7ec6deeb; FullOpts)

[21:01:47] ISSUE: <ASSERT> #13422 D:\a\_work\1\s\src\coreclr\jit\gentree.h (8125) - Assertion failed 'unreached' in 'System.Runtime.Intrinsics.X86.X86Base:DivRem(ulong,ulong,ulong):System.ValueTuple`2[ulong,ulong]' during 'LSRA allocate' (IL size 9; hash 0x5e7e955a; FullOpts)

[21:01:47] ISSUE: <ASSERT> #13423 D:\a\_work\1\s\src\coreclr\jit\gentree.h (8125) - Assertion failed 'unreached' in 'System.Runtime.Intrinsics.X86.X86Base:DivRem(ulong,long,long):System.ValueTuple`2[long,long]' during 'LSRA allocate' (IL size 9; hash 0x74788cda; FullOpts)

[21:01:47] ISSUE: <ASSERT> #13420 D:\a\_work\1\s\src\coreclr\jit\gentree.h (8125) - Assertion failed 'unreached' in 'System.Runtime.Intrinsics.X86.X86Base:DivRem(uint,uint,uint):System.ValueTuple`2[uint,uint]' during 'LSRA allocate' (IL size 9; hash 0xf27d1303; FullOpts)

[21:01:47] ISSUE: <ASSERT> #13428 D:\a\_work\1\s\src\coreclr\jit\gentree.h (8125) - Assertion failed 'unreached' in 'System.Runtime.Intrinsics.X86.X86Base+X64:DivRem(ulong,ulong,ulong):System.ValueTuple`2[ulong,ulong]' during 'LSRA allocate' (IL size 9; hash 0xb3ae736b; FullOpts)

[21:01:47] Compilation failures
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=177667&view=logs&jobId=83516c17-6666-5250-abde-63983ce72a49&j=83516c17-6666-5250-abde-63983ce72a49&t=2694d93b-a574-5310-1876-2e252085b877

**Comment by tannergooding** [comment]
Cc. @kunalspathak looks related to the new divrem support

**Comment by EgorBo** [comment]
Filed https://github.com/dotnet/runtime/issues/82397 for the assert so we can reference that issue on merge with CI failures

**Review by AndyAyersMS — APPROVED** [review]

**Pull request merged**
