### PR TITLE
[HTTP] Unobserved exceptions report in stress

### PR DESCRIPTION
**Pull request by ManickaP**
Same as with Quic tests, listen to and report unobserved exception.

Trying out with unobserved exceptions causing a failed run to see if it makes sense or not.

### CODE REVIEW

**Comment by ManickaP** [comment]
`Unobserved exceptions of 105 different types: `
:see_no_evil:

**Comment by ManickaP** [comment]
Stress is pretty borked rn, putting this on hold for now.

**Comment by MihaZupan** [comment]
>  Stress is pretty borked rn, putting this on hold for now.

Should we revive this one now? Looks like stress has been doing better.
I'm wondering if it could help with tracking down #110951.

**Pull request closed without merging**
