### PR TITLE
Add LA64 targetingpacks

### PR DESCRIPTION
**Pull request by am11**

### CODE REVIEW

**Comment by am11** [comment]
cc @LuckyXu-HF

**Comment by am11** [comment]
The other part is https://github.com/dotnet/runtime/pull/103273. (together, they will hopefully resolve https://github.com/dotnet/sdk/pull/41515#issuecomment-2159953085)

**Review by ViktorHofer — APPROVED** [review]

**Comment by LuckyXu-HF** [comment]
> The other part is #103273. (together, they will hopefully resolve [dotnet/sdk#41515 (comment)](https://github.com/dotnet/sdk/pull/41515#issuecomment-2159953085))

Thanks, based on PR #103273 we can execute `./build.sh clr -rc {release|debug}` and build the whole `clr` successfully for LA64.

**Comment by am11** [comment]
@ViktorHofer feel free to merge this. :)

**Comment by am11** [comment]
Build Analysis is green meaning CI failures are known.

**Pull request merged**
