### PR TITLE
[mono][jit] Fix float to int/uint casting behavior

### PR DESCRIPTION
**Pull request by jandupej**
Modifies `f32` to `i32` and `u32` casting behavior on arm64 so that overflow cases saturate. 16-bit and 8-bit integers retain previous casting model. Addresses https://github.com/dotnet/runtime/issues/85316. Enables SIMD f->i casting tests.

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by danmoseley** [comment]
Does this need breaking change doc label?

**Comment by jandupej** [comment]
> Does this need breaking change doc label?

I'm not sure. AFAIK the overflow behavior of these casts is not standardized in .NET. The purpose of this change is to move the casting behavior closer to what CoreCLR does and to unify it with the SIMD case.

**Comment by jkotas** [comment]
The overflow behavior of float to int/uint conversion has been documented as unspecified (see e.g. https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/numeric-conversions).

I do not think that this needs breaking change notification. It is changing behavior on one specific runtime flavor to make it more similar to other runtime flavors. Both old and new behavior is valid according to the docs.

**Comment by jandupej** [comment]
Thanks for confirming. CI only shows known errors. Merging.

**Pull request merged**
