### PR TITLE
Fix WinHttpHandler outerloop tests for deflate

### LINKED ISSUE #43292: Test failure: System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Decompression_Tests.GetAsync_SetAutomaticDecompression_ContentDecompressed(uri: \"https://httpbin.org/deflate\", expectedContent: \"\\\"deflated\\\": true\")
failed in job: [runtime-libraries-coreclr outerloop 20201011.1](https://dev.azure.com/dnceng/public/_build/results?buildId=848350&view=ms.vss-test-web.build-test-results-tab&runId=27028932&resultId=102195&paneView=debug)

net6.0-Windows_NT-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

Error message
~~~
System.IO.InvalidDataException : The archive entry was compressed using an unsupported compression method.

Stack trace
   at System.IO.Compression.Inflater.Inflate(FlushCode flushCode) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs:line 301
   at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs:line 267
   at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs:line 122
   at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs:line 92
   at System.IO.Compression.DeflateStream.CopyToStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs:line 995
   at System.Net.Http.WinHttpResponseStream.CopyToAsyncCore(Stream destination, Byte[] buffer, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseStream.cs:line 150
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestinationAsync() in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs:line 931
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 199
   at System.Net.Http.Functional.Tests.HttpClientHandler_Decompression_Test.GetAsync_SetAutomaticDecompression_ContentDecompressed(String uri, String expectedContent) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Decompression.cs:line 216
--- End of stack trace from previous location ---
~~~

### LINKED ISSUE #43293: Test failure: System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Decompression_Http2_Tests.GetAsync_SetAutomaticDecompression_ContentDecompressed(uri: \"https://httpbin.org/deflate\", expectedContent: \"\\\"deflated\\\": true\")
failed in job: [runtime-libraries-coreclr outerloop 20201011.1](https://dev.azure.com/dnceng/public/_build/results?buildId=848350&view=ms.vss-test-web.build-test-results-tab&runId=27028936&resultId=102943&paneView=debug)

failed tests:
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Decompression_Tests.GetAsync_SetAutomaticDecompression_ContentDecompressed(uri: \"https://httpbin.org/deflate\", expectedContent: \"\\\"deflated\\\": true\")
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Decompression_Http2_Tests.GetAsync_SetAutomaticDecompression_ContentDecompressed(uri: \"https://httpbin.org/deflate\", expectedContent: \"\\\"deflated\\\": true\")

net6.0-Windows_NT-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open

Error message
~~~
System.Net.Http.HttpRequestException : Error while copying content to a stream.
---- System.IO.IOException : The read operation failed, see inner exception.
-------- System.Net.Http.WinHttpException : Error -2147467260 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'Operation aborted'.

Stack trace
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 203
   at System.Net.Http.Functional.Tests.HttpClientHandler_Decompression_Test.GetAsync_SetAutomaticDecompression_ContentDecompressed(String uri, String expectedContent) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Decompression.cs:line 216
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 63
   at System.Net.Http.WinHttpResponseStream.CopyToAsyncCore(Stream destination, Byte[] buffer, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseStream.cs:line 126
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 199
----- Inner Stack Trace -----
~~~

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/43293
Fixes https://github.com/dotnet/runtime/issues/43292

### CODE REVIEW

**Comment by geoffkizer** [comment]
> WinHttpHandler targets netstandard2.0 and still erroneously uses DeflateStream rather than ZlibStream for deflate.

This is in our code in WinHttpHandler, right? Not in winhttp proper?

**Comment by stephentoub** [comment]
> This is in our code in WinHttpHandler, right? Not in winhttp proper?

Correct.
https://github.com/dotnet/runtime/blob/98eee0587dfd0752c030fe49b3fd9b45f4b2e5c5/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpResponseParser.cs#L83-L88

This didn't seem like a good enough reason to start shipping a new asset.

**Review by geoffkizer — APPROVED** [review]

**Comment by stephentoub** [comment]
> This didn't seem like a good enough reason to start shipping a new asset.

Though,  we could use reflection...

**Pull request merged**
