### PR TITLE
Test: simplify gc memmove

### PR DESCRIPTION
**Pull request by EgorBo**

### CODE REVIEW

**Comment by EgorBo** [comment]
@EgorBot -intel -arm64 -profiler -nonativepgo

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Bench).Assembly).Run(args);

[GcServer(true)]
public class Bench
{
    static object[] Src0 = Enumerable.Range(0, 2).Select(i => (object)i).ToArray();
    static object[] Src1 = Enumerable.Range(0, 10).Select(i => (object)i).ToArray();
    static object[] Src2 = Enumerable.Range(0, 128).Select(i => (object)i).ToArray();
    static object[] Dst = new object[128];

    [Benchmark]public void CopyObjects2() => Src0.AsSpan().CopyTo(Dst);
    [Benchmark]public void CopyObjects10() => Src1.AsSpan().CopyTo(Dst);
    [Benchmark]public void CopyObjects128() => Src2.AsSpan().CopyTo(Dst);
}
```

**Comment by EgorBo** [comment]
@EgorBot -intel -arm64 -profiler -nonativepgo

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Bench).Assembly).Run(args);

[GcServer(true)]
public class Bench
{
    static object[] Src0 = Enumerable.Range(0, 2).Select(i => (object)i).ToArray();
    static object[] Src1 = Enumerable.Range(0, 10).Select(i => (object)i).ToArray();
    static object[] Src2 = Enumerable.Range(0, 128).Select(i => (object)i).ToArray();
    static object[] Dst = new object[128];

    [Benchmark]public void CopyObjects2() => Src0.AsSpan().CopyTo(Dst);
    [Benchmark]public void CopyObjects10() => Src1.AsSpan().CopyTo(Dst);
    [Benchmark]public void CopyObjects128() => Src2.AsSpan().CopyTo(Dst);
}
```

**Comment by huoyaoyuan** [comment]
Is auto-vectorization by C++ compiler expected to kick in?

**Comment by EgorBo** [comment]
> Is auto-vectorization by C++ compiler expected to kick in?

I am just curious about the impact of the logic we have here.

1) It seems that the current logic it's not 100% safe as it uses SIMD on x64. SIMD demands 16 byte alignment for both src and dest, but we only align dest.
2) I've observed a lot of "Load with an additional latency due to misalignment" PMU counters pointing to this function on arm64 with `perf`

**Comment by huoyaoyuan** [comment]
How about the numbers at
https://github.com/dotnet/runtime/issues/101699#issuecomment-2088089516 ? I was basically doing the same thing for NoSSE.

**Comment by EgorBo** [comment]
@EgorBot -arm64 -profiler -nonativepgo -perf_events ld_align_lat

```cs
using BenchmarkDotNet.Attributes;

public class Bench
{
    static object[] Src = Enumerable.Range(0, 10).Select(i => (object)i).ToArray();
    static object[] Dst = new object[128];

    [Benchmark]public void CopyObjects10() => Src.AsSpan().CopyTo(Dst);
}
```

**Comment by EgorBo** [comment]
> How about the numbers at [#101699 (comment)](https://github.com/dotnet/runtime/issues/101699#issuecomment-2088089516) ? I was basically doing the same thing for NoSSE.

do you mean AVX numbers? I guess the atomicity concern still stands

**Comment by EgorBo** [comment]
@EgorBot -intel -arm64 -profiler -nonativepgo

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Bench).Assembly).Run(args);

[GcServer(true)]
public class Bench
{
    static object[] Src0 = Enumerable.Range(0, 2).Select(i => (object)i).ToArray();
    static object[] Src1 = Enumerable.Range(0, 10).Select(i => (object)i).ToArray();
    static object[] Src2 = Enumerable.Range(0, 128).Select(i => (object)i).ToArray();
    static object[] Dst = new object[128];

    [Benchmark]public void CopyObjects2() => Src0.AsSpan().CopyTo(Dst);
    [Benchmark]public void CopyObjects10() => Src1.AsSpan().CopyTo(Dst);
    [Benchmark]public void CopyObjects128() => Src2.AsSpan().CopyTo(Dst);
}
```

**Comment by EgorBo** [comment]
With `volatile` it's obviosly a regression on large inputs, but the PMU counters for unaligned loads look happy:

Main:
```
 563591328      ld_align_lat
         0      st_align_lat
2801225037      unaligned_ld_spec
2780268499      unaligned_st_spec
```

PR:
```
     19048      ld_align_lat
         9      st_align_lat
         0      unaligned_ld_spec
         0      unaligned_st_spec
```

**Pull request closed without merging**
