### PR TITLE
[release/8.0] Adjust System.Net metrics for OTel conformance and consistency

### LINKED ISSUE #92837: `dns.lookup.duration` should report `error.type`
### Description

Currently `dns.lookup.duration` only reports duration of he successful lookups, but failed lookups are quite interesting as well (count, rate, duration, failure reason). 

Having `error.type` attribute on the `dns.lookup.duration` metric and reporting it when DNS lookup fails would provide all the details.

Adding an attribute later is considered a breaking change on OTel, since it increases the number of time series in the metric and breaks alerts and dashboards (so creating it as a bug).

### Reproduction Steps

N/A 

https://github.com/dotnet/runtime/blob/e89daba754e84dba3a86c92e8c2a714a75a2f0d0/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionMetrics.cs#L24

### Expected behavior

The metric should have `error.type` attribute nad report duration of both, failed and successfully lookups.

### Actual behavior

Metric only reports successful lookups

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### LINKED ISSUE #92917: Rename `dns.lookupS.duration` to `dns.lookup.duration`
The name implemented in #89813 is result of a misunderstanding. https://github.com/lmolkova/semantic-conventions/blob/dotnet8-metrics/docs/dotnet/dotnet-dns-metrics.md#metric-dnslookupsduration has a typo in the title, but lower in the table it's correctly spelled as `dns.lookup.duration` which is a name that aligns with OTel conventions.

### LINKED ISSUE #92956: [HTTP Metrics] Rename `server.socket.address` to `network.peer.address`
https://github.com/open-telemetry/semantic-conventions/pull/342 is introducing changes to the OTel standard that will effect the conformance of our `http.client.open_connections` and `http.client.connection.duration` metrics. The PR is expected to be merged very soon giving us an opportunity to adjust our metrics for 8.0 GA and avoid breaking changes in 9.0.

- We should rename `server.socket.address` to `network.peer.address` in both metrics
- Given that [it's recommended to set `network.peer.port` when `network.peer.address` is set](https://github.com/open-telemetry/semantic-conventions/blob/d714318c7a29be094cc0152b347b6c4c290a115c/docs/http/http-spans.md#http-client), we should introduce that attribute. The implementation should be trivial, since we are flowing down the peer's `IPEndPoint` to `HttpConnectionBase`.

https://github.com/dotnet/runtime/blob/3452a99cc11fef73ffc34d43c86410d451e33d39/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionBase.cs#L53-L59

### LINKED ISSUE #93302: [Metrics] `error.type` doesn't report `Exception.FullName`
`http.client.request.duration`'s `error.type` contains `Exception.Name` for cases which do not map to `HttpRequestError` values, which is inconsistent with aspnet's implementation that reports `Exception.FullName` -- see https://github.com/dotnet/aspnetcore/pull/51084.

The [wording of the .NET Metrics spec](https://github.com/lmolkova/semantic-conventions/blob/dotnet8-metrics/docs/dotnet/dotnet-http-metrics.md#metric-httpclientrequestduration), is somewhat ambivalent:

> When error.type attribute is reported, it contains one of [HTTP Request errors](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpRequestError.cs), a full exception type, or a string representation of received status code.

As https://github.com/dotnet/runtime/pull/93254#discussion_r1352865229 pointed out, this could also mean to *"use HttpRequestException instead of just 'Http' or 'HttpException'"*. Moreover, reporting the full name doesn't bring any value, the set of exceptions we can see here is limited, collisions are not expected. 

I assume this is not the case with aspnet, where exceptions may come from an arbitrarily large set. My recommendation would be to leave and document the current behaviors as-is.

@JamesNK @noahfalk we should make a decision ASAP.

### PR DESCRIPTION
**Pull request by antonfirsov**
Fixes #92956, fixes #92917, fixes #92837, fixes #93302

Backport of PRs #93255, #93254, #93322

## Customer Impact

OpenTelemetry metrics is a new feature in .NET 8.0.
There are minor semantic aspects which are either not conforming to the OpenTelemetry standard (#92956, #92917), inconsistent with ASP.NET (#93302) or highly undesirable (#92837). Fixing these problems in .NET 9.0 would be a breaking change against 8.0, while implementing them in 8.0 GA has a much lower negative impact on customers.

## Testing

Target test cases were added.

## Risk

Low. It is new feature in 8.0, therefore only early adopters of the new feature may be broken - we expect they will prefer conformance to standard.

### CODE REVIEW

**Review by MihaZupan — APPROVED** [review]

**Review by karelz — APPROVED** [review]

**Comment by carlossanlop** [comment]
Approved by Tactics via email.

**Comment by carlossanlop** [comment]
The CI failures are unrelated.

**Pull request merged**
