### PR TITLE
Fix Ordinal Ignore Case string compare

### LINKED ISSUE #71018: `StringComparison.OrdinalIgnoreCase` compares `"¡a"` and `"¡B"` incorrectly
### Description

In `net5.0` and `net48` on Windows, `string.Compare("¡a", "¡B", StringComparison.OrdinalIgnoreCase)` returns a value < 0 (specifically -1).

But In `net6.0` and `net7.0`, that expression returns a value > 0 (specifically, 31).

The `net5.0` result fulfills the meaning of `StringComparison.OrdinalIgnoreCase`; the `net6.0` result does not.

Setting `$env:DOTNET_SYSTEM_GLOBALIZATION_USENLS='true'` restores the `net5.0` behaviour, which indicates that this may be related to https://github.com/dotnet/runtime/issues/30960?

(Even if this is the actual result returned by ICU for the comparison--and I'm not sure if that's true or not--it doesn't match this programmer's expectations for what `StringComparison.OrdinalIgnoreCase` means.)

### Reproduction Steps

Program.cs:

```csharp
using System;

// prints -1 for prefix <= U+007F, 31 for prefix >= U+0080
string prefix = "\u00A1";
Console.WriteLine(string.Compare($"{prefix}a", $"{prefix}B", StringComparison.OrdinalIgnoreCase));
```

Compare.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net48;net5.0;net6.0;net7.0</TargetFrameworks>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>

</Project>
```

### Expected behavior

Per https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings#ordinal-string-operations:

> Case-insensitive ordinal comparisons are the next most conservative approach. These comparisons ignore most casing; for example, "windows" matches "Windows". When dealing with ASCII characters, this policy is equivalent to [StringComparison.Ordinal](https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparison#system-stringcomparison-ordinal), except that it ignores the usual ASCII casing. Therefore, any character in [A, Z] (\u0041-\u005A) matches the corresponding character in [a,z] (\u0061-\007A). Casing outside the ASCII range uses the invariant culture's tables.

Thus, it is expected that `¡` will be considered equal in both strings, then `a` will be compared to `B` and the first string will sort first by an case-insensitive ordinal comparison. That is, `"¡a"` sorts before `"¡B"` using a case-insensitive ordinal comparison.

### Actual behavior

`"¡a"` sorts after `"¡B"` using a case-insensitive ordinal comparison.

### Regression?

Yes. This worked correctly in `net48` and `net5.0` on Windows and Linux; I have not tested `net5.0` and earlier on macOS.

### Known Workarounds

Use `StringComparison.InvariantCultureIgnoreCase`. 
Set the `DOTNET_SYSTEM_GLOBALIZATION_USENLS` environment variable to `true`.

### Configuration

SDKs: 6.0.301; 7.0.100-preview.5.22307.18
Windows 10 19044.1766 x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/71018

### CODE REVIEW

**Review by GrabYourPitchforks — APPROVED** [review]
Thanks Tarek!

**Review by stephentoub — APPROVED** [review]

**Comment by danmoseley** [comment]
should we propose backport? we may only have one report, but it's fairly fundamental so may be causing problems customers have not yet discovered.

**Comment by tarekgh** [comment]
@danmoseley 

> should we propose backport? we may only have one report, but it's fairly fundamental so may be causing problems customers have not yet discovered.

I was discussing that with @GrabYourPitchforks. Considering .NET 6.0 has been out for a while now and this is the first time it gets reported; I think we can wait to see if we get more reports. But I am not opposing to back port it if you support that :-). The fix is trivial, safe, and unlikely to cause any trouble.

**Comment by danmoseley** [comment]
I think your reasoning makes sense - we can wait to see whether there are more reports.

**Comment by EgorBo** [comment]
It feels like this change slightly improved perf on arm64: https://github.com/dotnet/perf-autofiling-issues/issues/6341

**Comment by tarekgh** [comment]
> It feels like this change slightly improved perf on arm64: https://github.com/dotnet/perf-autofiling-issues/issues/6341

:open_mouth:

Interesting. looks arm64 is very sensitive to changes like that. Thanks @EgorBo for sharing that.

**Pull request merged**
