### PR TITLE
Update to preview branding

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Review by Anipik — APPROVED** [review]

**Comment by jaredpar** [comment]
@dagood 

Looks like one of the hosting tests are failing here and this is just a branding change: `Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.Comhost.ActivateClass`. I searched through our CI logs and don't see this failing in any other runs. Is this a real failure or possibly a flaky test?

**Comment by dagood** [comment]
@jaredpar looks like a repro of https://github.com/dotnet/runtime/issues/2320.

Full text of this instance: https://gist.github.com/dagood/936cfbe21fe15498c483e080c298258e

**Comment by jaredpar** [comment]
@dagood yeah that looks like it. Seems like it's been failing a couple other times recently

### Builds
|Build|Test Failure Count|
| --- | --- |
|[#507224](https://dev.azure.com/dnceng/public/_build/results?buildId=507224)|1|
|[#507225](https://dev.azure.com/dnceng/public/_build/results?buildId=507225)|1|

Looks like @elinor-fung has a fix for it out though.

**Comment by mmitche** [comment]
@jaredpar Any progress on the failures here? This needs to be done pretty soon.

**Comment by jaredpar** [comment]
@mmitche believe the test failures are fixed by https://github.com/dotnet/runtime/pull/32153.

We should re-queue to check.

**Comment by jaredpar** [comment]
Failures in this PR are covered in #32179. Merging.

**Pull request merged**
