### PR TITLE
Use OptimizeForSize condition in SPC only on Browser

### PR DESCRIPTION
**Pull request by akoeplinger**
The size impact doesn't matter for tvOS.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
See #49372 for some of the rationale for this.

**Comment by akoeplinger** [comment]
From @jkotas' comment on that PR:

> Both Android and iOS phones are higher-end hardware. I would expect we want to keep the vectorized implementations for those.

I don't know what the size penalty is but we should definitely be consistent between iOS and tvOS, so maybe we'll need the size optimized version only for Browser.

**Comment by SingleAccretion** [comment]
> I don't know what the size penalty is

I think it was 2KB compressed and 6KB raw. See https://github.com/dotnet/runtime/issues/48006#issuecomment-796188666.

**Comment by akoeplinger** [comment]
Ok thanks, I think that's negligible for mobile so I switched the condition to only apply to Browser.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
