### PR TITLE
illumos: set default timezone info path

### PR DESCRIPTION
**Pull request by AustinWise**
Empirically, this is where these files live on OpenIndiana and SmartOS (global zone and Joyent-branded zones). This also the documented location for [illumos](https://www.illumos.org/man/5/timezone) and [Solaris](https://docs.oracle.com/cd/E88353_01/html/E37852/timezone-5.html). (Thanks for the pointers to man pages Tarek!)

This makes this test pass:

```bash
dotnet xunit.console.dll System.Runtime.Tests.dll -method "Tests.System.TimeProviderTests.TestSystemProviderWithTimeZone"
```

If you don't have the fix in this PR, you can also make this test pass by setting the `TZDIR` environmental variable to `/usr/share/lib/zoneinfo/` .

Contributes to #34944

### CODE REVIEW

**Comment by tarekgh** [comment]
I have confirmed that both Solaris and Illumos used the `/usr/share/lib/zoneinfo/` for the time zone files.

https://www.illumos.org/man/5/timezone and https://support.oracle.com/knowledge/Sun%20Microsystems/1011541_1.html#aref_section23

So, the change looks good here. 

I am wondering, would it make sense instead of ifdef that for different system to introduce a fallback path to the time zones folder? I mean let [`GetTimeZoneDirectory`](https://github.com/dotnet/runtime/blob/041375910885f3a30ccf0bb8b751566dae7043f4/src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.Unix.NonAndroid.cs#L82) return the time zones path in addition to fallback path too. Then pass these two paths to the methods reading the time zones like `ReadAllBytesFromSeekableNonZeroSizeFile`?

I am suggesting that as I am not sure if we build the browser or WASM for Solaris or Illumos and use the embedded files which can point at wrong path at that time? 

CC @lewing if he can advise regarding the WASM cases. 

@am11 do you have any feedback about this PR?

**Comment by am11** [comment]
I wasn't able to run it myself as I'm currently on osx-arm64 (where x64 VMs are quite slow). I trust what @AustinWise has found. However, I would like to test it in Global Zone vs. non- Global Zone. Sometimes these system paths and properties vary in a virtualized zone vs. GZ. (not to be confused with timezones; zones in sunos are like containers in linux and jails in freebsd, virtualized sandbox environment)

> I mean let [`GetTimeZoneDirectory`](https://github.com/dotnet/runtime/blob/041375910885f3a30ccf0bb8b751566dae7043f4/src/libraries/System.Private.CoreLib/src/System/TimeZoneInfo.Unix.NonAndroid.cs#L82) return the time zones path in addition to fallback path too. Then pass these two paths to the methods reading the time zones like `ReadAllBytesFromSeekableNonZeroSizeFile`?

Sounds like a good idea. It can probably return two strings for now, something like:

```diff
-        private static string GetTimeZoneDirectory()
+        private static (string knownPath, string fallbackPath) GetTimeZoneDirectory()
```

**Comment by tarekgh** [comment]
@AustinWise thanks for your effort. The current change is ok. I am wondering if there is any other Linux based system using `/usr/share/lib/zoneinfo/` and we are not aware of. The fallback can just make it work without any further changes. But I am ok to proceed with the current change for now and watch out if we see the issue again, we can consider the fallback at that time. 

I'll wait for @am11 if he has any more comments and then we can merge the change.

**Review by tarekgh — APPROVED** [review]

**Comment by am11** [comment]
>  I have not tried other distributions or zone brands.

GZ is not recommended to be used for development purposes and using non-GZ zones is a common practice. In SmartOS, GZ doesn't even persists data and config by default and even if you alter the RO-ness, it has resource limitations. OmniOS made it simpler for the cloud but we are targeting generic SunOS. To get result from a neutral zone, you can create a `base-64-lts` zone, e.g. https://gist.github.com/am11/5f1702de2ce5474670da4e4604856891 (I pieced it together from an old stash).

**Comment by am11** [comment]
> Are there other distributions or zone brands I should try?

I think having tested on generic 64-bit base is fine. When linux distros running in a zone, we don't expect dotnet(1) to run cross OS (each OS has a separate ELF binary). Thanks for testing. Looks good to me!

ps - if you could keep a zone on OpenIndiana or SmartOS for future testing, that would be great to rule out any doubts.

**Review by am11 — APPROVED** [review]

**Comment by tarekgh** [comment]
Thanks @AustinWise, this is very helpful!

**Pull request merged**
