### PR TITLE
Apple Silicon coreclr runtime tests

### PR DESCRIPTION
**Pull request by sdmaclea**
Create SetPathVars_coreclr_AppleSilicon for enabling limited PR runtime testing

Enable coreclr runtime tests on Apple Silicon for isFullMatrix & SetPathVars_coreclr_AppleSilicon.containsChange

- I think the tests are pretty stable, I have disable a lot of unstable tests >1000 after collecting all the failures for 100 runs.
- I am hoping we have enough Apple Silicon capacity for this limited set of paths.  
  - We are not saturating these queues as only rolling and scheduled builds are enabled.
  - There were about 30 PRs to these paths in the last 10 days
  - Assuming 10 runs per PR, seems like we may have sufficient capacity
  - I will watch the queues once this merges.

### CODE REVIEW

**Comment by sdmaclea** [comment]
I triggered this full matrix run.

https://dev.azure.com/dnceng/public/_build/results?buildId=1032099

**Review by trylek — APPROVED** [review]
Looks great to me, thank you!

**Comment by sdmaclea** [comment]
Retiggered FullMatrix with new commits. https://dev.azure.com/dnceng/public/_build/results?buildId=1032957

**Comment by sdmaclea** [comment]
The build succeeded.  I plan to merge this today.  Any concerns @safern @ViktorHofer?

**Review by ViktorHofer — APPROVED** [review]

**Review by safern — COMMENTED** [review]
LGTM. Fyi, for the subsets if only included paths are specified you don't need to star the excluded paths. When you want to include excluded into the subsets is if you want to exclude a path that is a child from the included paths.

**Pull request merged**
