### PR TITLE
Dev/anscoggi/activate live builds

### PR DESCRIPTION
**Pull request by DrewScoggins**
These are the changes that we need to make to get the perf pipeline back up and running.

### CODE REVIEW

**Comment by trylek** [comment]
Hmm, this looks pretty similar to https://github.com/dotnet/runtime/pull/1049, can you please expand on the delta?

**Review by trylek — APPROVED** [review]
Of course, that's what needs to be happening

**Comment by DrewScoggins** [comment]
Looks like we are getting results through the whole pipeline now. I am re-running the failed tests, as I am not sure why my change would affect them. If they work, I am going to go ahead and check this in.

**Comment by trylek** [comment]
Thank you!

**Pull request merged**
