### PR TITLE
pick Debian10 over Debian9 for PR validation

### PR DESCRIPTION
**Pull request by wfurt**
It seems like Debian 10 is on the edge of pushing security and we had few instances recently where tests would only fail on Debian 10. We still also have fair amount cases where Debian10 is special-cased in tests.  

It seems like it would make sense to get test coverage for PRs. 
I purposely left ARM platform untouched while pushing x64 to 10 to get tests on latest and (maybe?) greatest Debian version. 

While looking at this, it seems like runs on Centos7 and RedHat 7 would not yield that much benefit as being generally same. It may be worth of considering either dropping one or moving one to version 8 or add different distribution.

### CODE REVIEW

**Comment by danmosemsft** [comment]
Maybe official build can use 9 and CI/PR can use 10?

**Comment by wfurt** [comment]
I think we get all that with isFullMatrix=true (section above)

**Comment by wfurt** [comment]
OSXish test failures seems #41006

**Review by safern — APPROVED** [review]

**Comment by safern** [comment]
> I think we get all that with isFullMatrix=true (section above)

Yeah CI is isFullMatrix=true PR =false.

**Pull request merged**
