### PR TITLE
Add runtime detection for CovariantReturnsOfClasses

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Was missed in #37276.

### CODE REVIEW

**Review by janvorli — APPROVED** [review]
LGTM, thank you for spotting it.

**Comment by jkotas** [comment]
Add a test?

**Comment by MichalStrehovsky** [comment]
> Add a test?

Sure. Added one that will fail next time someone misses this.

**Review by jkotas — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
The mono failure is a networking test. I'm going to go with "unrelated".

**Pull request merged**
