### PR TITLE
Adding a default IEnumerable.GetEnumerator implementation to IEnumerable<T>

### PR DESCRIPTION
**Pull request by masonwheeler**
Minor QOL improvement for .NET developers.  I'm honestly surprised that this was not literally the very first thing anyone ever did with the Default Interface Implementation feature.

### CODE REVIEW

**Comment by alexrp** [comment]
> I'm honestly surprised that this was not literally the very first thing anyone ever did with the Default Interface Implementation feature.

Maybe they considered it and opted for caution. 🤔

**Comment by huoyaoyuan** [comment]
Thank you for your interest of contribution. However, this change has **HUGE impact** of the whole ecosystem due to being fundamental.

#31001 and #95830 are doing the similar thing for read-only collection interfaces. However, the change gets reverted since it breaks C++/CLI in some way. The exact change in this PR has been proposed for multiple times, but the team hasn't get a concrete plan for this. I believe they will get #31001 resolved first.

**Comment by teo-tsirpanis** [comment]
This change would require opening an API proposal and having it be approved.

**Comment by jkotas** [comment]
Similar idea discussed yesterday in https://github.com/dotnet/runtime/pull/102795#discussion_r1620735659

**Comment by hamarb123** [comment]
Isn't it a breaking change to add a default implementation to an existing interface method? (due to diamond inheritance problem)

**Comment by huoyaoyuan** [comment]
> Isn't it a breaking change to add a default implementation to an existing interface method? (due to diamond inheritance problem)

If anyone inherits from non-generic `IEnumerable`, doesn't inherit `IEnumerable<T>`, and also provides DIM in the descant interface. It's also discussed at #31001

**Comment by stephentoub** [comment]
Thanks. Closing per https://github.com/dotnet/runtime/pull/102954#issuecomment-2143506758.

**Pull request closed without merging**
