### PR TITLE
Add the interop tags to the "add to the AppModel project" automation

### PR DESCRIPTION
**Pull request by jkoritzinsky**
We're going to track the interop issues as part of the AppModel project under a different filtered table view.

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
@jeffhandley do we have any tooling to add issues to a project that match recently added rules, or do we need to add them manually?

**Comment by jkoritzinsky** [comment]
Alternatively, since the AppModel project is not a "classic" Project, we can use the AppModel project as the test project for using a GitHub Action to add issues to projects.

**Comment by jeffhandley** [comment]
We do not yet have any automation in place for adding cards to non-classic projects, and the expected path forward on that will be to use GitHub Actions to achieve it. If you folks wanted to prototype that, it would help us determine how viable and scalable that will be for us. @sharwell has some experience and insight here too and might be a good consultant.

**Comment by jkoritzinsky** [comment]
@jeffhandley it looks like we don't have a solution to the "where do we put a PAT" problem, so I'm going to revert this change to just use FabricBot until we come up with a generalized solution in the .NET 9 timeframe.

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Review by jtschuster — APPROVED** [review]

**Pull request merged**
