### PR TITLE
Fix failure with `reimportSpillClique=true`. 

### LINKED ISSUE #47308: jit asserts in crossgen2 job.
Looks like the outerloop is red for a while: https://dev.azure.com/dnceng/public/_build?definitionId=701&_a=summary

example failure:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-09989cbb72234094aa/JIT.Regression/console.86ce84a6.log?sv=2019-07-07&se=2021-02-08T09%3A01%3A25Z&sr=c&sp=rl&sig=nY7VQrL5d%2Bve1Gnjqtw2LOlJHqFLFcibkGpc1NDPy7E%3D

`      Assertion failed '(varDsc->lvType != TYP_UNDEF) && (varDsc->lvType != TYP_VOID) && (varDsc->lvType != TYP_UNKNOWN)' in 'FullProof:Test():int' during 'Mark local vars' (IL size 1446)`

I can look at it next week but if somebody wants to get a crossgen2 debugging experience feel free to take, @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by sandreenko**
The optimization added in https://github.com/dotnet/runtime/pull/31677 could cause a failure in tricky conditions.

The test reproduces the failure without crossgen2, it fails on 5.0.

We needed:
- `<DebugType>Full</DebugType>`;
- `reimportSpillClique = true`, by creating blocks like:
```
A: leave r4 on the stack;
B: leave r8 on the stack;
C: merge block for A, B, sees one incoming as r4, another as r8, sets reimportSpillClique = true.
```
- a CEE_POP that triggers optimization bashToNop from 31677;
- another stack entry after the poped one to force another spill stack call.

when all the conditions were met we were creating a tree like:
```
ASG(LCL_VAR void, NOP void)
```
and failing with assert during local visitor phase, with a noway assert in codegen, then with invalid program exception (in 5.0 release).

The stack when we `bashToNop`:
```
dump EE stacks:
depth: 3
               [000044] ------------              *  LCL_VAR   long   V07 tmp7
               [000045] ------------              *  LCL_VAR   long   V08 tmp8
               [000046] ------------              *  LCL_VAR   float  V09 tmp9 <- we would pop it from the current and bash to nop.

block number: 2, depth: 4
               [000044] ------------              *  LCL_VAR   long   V07 tmp7
               [000045] ------------              *  LCL_VAR   long   V08 tmp8
               [000046] ------------              *  LCL_VAR   float  V09 tmp9 <- this is reference saved in `block->bbEntryState`, it will become invalid.
               [000047] ------------              *  LCL_VAR   float  V10 tmp10
```
so during reimportation, we will try to use the invalid reference during `impSpillStackEntry`.

Fixes https://github.com/dotnet/runtime/issues/47308.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib 

I don't think it meets the bar for 5.0 back-port, what do you think?

**Comment by sandreenko** [comment]
@JulieLeeMSFT it is not an issue, it is a pr. Do we want to move PRs to the project and assigned authors to them?

**Comment by sandreenko** [comment]
The failures are unrelated, opened https://github.com/dotnet/runtime/issues/48204

**Review by AndyAyersMS — APPROVED** [review]
LGTM

**Comment by AndyAyersMS** [comment]
> I don't think it meets the bar for 5.0 back-port, what do you think?

I don't think it does (if it were customer reported, then maybe).

**Pull request merged**
