### PR TITLE
Stop passing StandardOptimizationData.mibc to crossgen2 multiple times for SPC

### PR DESCRIPTION
**Pull request by jakobbotsch**
When invoking crossgen2 we are currently passing the mibc file 4 times, once for each scenario we have PGO data for. It means that the counts the JIT sees for SPC are inflated by 4x.

Note that we are using raw counts in the JIT that might be affected by this change:
https://github.com/dotnet/runtime/blob/063d08018602291f8dbd9d9b6055b8e1af874cb8/src/coreclr/jit/fgprofile.cpp#L50-L73
However it is not right to multiply this value by 0.25x either as I believe for other framework DLLs we are passing StandardOptimizationData.mibc just once. So I am hoping to see if this has ill effects on SPC from the perf legs. @EgorBo's original PR #55096 already has data showing that most hot methods have more than 5000 counts, so hopefully we will not see anything too bad.

cc @dotnet/jit-contrib @davidwrighton

### CODE REVIEW

**Review by EgorBo — APPROVED** [review]

**Comment by EgorBo** [comment]
I've checked locally this reduces R2R'd corelib size from `10.887 Mb` to `10.852 Mb` in `--Ot` mode which means it inlines slightly less now but it's expected and looks fine to me

**Comment by jakobbotsch** [comment]
The build failure seems to be because the .mibc file does not exist there, and the build previously did not have any files in `OptimizationMibcFiles`. @davidwrighton do you know if it is expected that we are currently not passing any .mibc file when crossgenning SPC in the "Build Linux x64 release SourceBuild" pipeline? E.g. the invocation for a previous passing build of the pipeline is:
```
    /__w/1/s/artifacts/source-build/self/src/dotnet.sh /__w/1/s/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/crossgen2/crossgen2.dll -o:/__w/1/s/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/System.Private.CoreLib.dll -r:/__w/1/s/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/*.dll --targetarch:x64  --embed-pgo-data -O /__w/1/s/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/System.Private.CoreLib.dll --perfmap-format-version:1 --perfmap --perfmap-path:/__w/1/s/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/
```

**Comment by jakobbotsch** [comment]
Also cc @dotnet/source-build-contrib, is it expected that we are not passing PGO data in the SourceBuild pipeline?

**Comment by crummel** [comment]
Yes, the PGO data is considered a prebuilt binary that isn't allowed to be used in the open-source builds.  We've talked about ways around this but haven't had the resources to really fix it yet.

**Review by crummel — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Failure is #58927

**Pull request merged**
