### PR TITLE
Fix GC liveness check in ByRefLocals test

### LINKED ISSUE #40751: Test failure: Loader/CollectibleAssemblies/ByRefLocals/ByRefLocals/ByRefLocals.sh
failed in job: [runtime-coreclr jitstress 20200811.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=766498&view=ms.vss-test-web.build-test-results-tab&runId=23829828&resultId=109456&paneView=debug)

failed test:
Loader/CollectibleAssemblies/ByRefLocals/ByRefLocals/ByRefLocals.sh
Loader\\CollectibleAssemblies\\ByRefLocals\\ByRefLocals\\ByRefLocals.cmd

Error message
~~~
Return code:      1
Raw output file:      /root/helix/work/workitem/Loader/CollectibleAssemblies/Reports/Loader.CollectibleAssemblies/ByRefLocals/ByRefLocals/ByRefLocals.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun ByRefLocals.dll ''
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
Expected: 100
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/Loader/CollectibleAssemblies/ByRefLocals/ByRefLocals/ByRefLocals.sh
Expected: True
Actual:   False


Stack trace
   at Loader_CollectibleAssemblies._ByRefLocals_ByRefLocals_ByRefLocals_._ByRefLocals_ByRefLocals_ByRefLocals_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm64.Checked/TestWrappers/Loader.CollectibleAssemblies/Loader.CollectibleAssemblies.XUnitWrapper.cs:line 140
~~~

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #40751

### CODE REVIEW

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib @davidwrighton PTAL
The two test failures are unrelated to the changed test.

**Comment by CarolEidt** [comment]
ping @dotnet/jit-contrib @davidwrighton

**Review by davidwrighton — APPROVED** [review]
LGTM

**Pull request merged**
