### PR TITLE
Fix __SOFTFP__ case for arm getcontext

### PR DESCRIPTION
**Pull request by am11**
Upstream PR: https://github.com/libunwind/libunwind/pull/400.

### CODE REVIEW

**Comment by am11** [comment]
`Linux arm checked` failure is https://github.com/dotnet/runtime/issues/73247. I have double checked that the leg is actually building with hard fp support (and `#ifdef __SOFT__` is false).

We use `__SOFTFP__` macro in debugger support e.g. https://github.com/dotnet/runtime/blob/73cf30dd4a00a1ee7b12a82a2cff99b1870a3c4e/src/coreclr/debug/createdump/dumpwriterelf.cpp#L410 so it is a known macro for both clang and gcc arm soft float toolchains.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
@am11 Any concerns with waiting until upstream takes this?

**Comment by am11** [comment]
No concerns (with a but) :)
Just wanted to note that it might be useful for .NET 7 as `linux-armv6` is new platform in 7.0 and `CLR_CMAKE_HOST_ARCH_ARMV6` is used in libunwind.cmake; as corehost requires coreclr-pal (even for RuntimeFlavor=mono). Though I am not sure if we support (or have CI coverage for) softfp variant with armv6 as the compilation should had failed in the CI. `git grep '\-mfpu='` we don't but in places without `-mfpu` option set, it defaults to toolchain's baseline, so it is unclear if we actually support softfp/-mfpu=none.

**Comment by am11** [comment]
Upstream PR is merged.

**Comment by AaronRobinsonMSFT** [comment]
Issues are https://github.com/dotnet/runtime/issues/73247 and https://github.com/dotnet/runtime/issues/73474.

**Pull request merged**
