### PR TITLE
[wasm] Implicit NodeJS version on Helix

### PR DESCRIPTION
**Pull request by maraf**
Instead of hardcod NodeJS version in `sendtohelix-wasm.targets`, read it from directory name in file system.

### CODE REVIEW

**Review by pavelsavara — APPROVED** [review]

**Comment by pavelsavara** [comment]
Do we need the same thing for Windows ?

**Comment by maraf** [comment]
Yes, we do and it's already there.

**Review by lewing — APPROVED** [review]

**Pull request merged**
