### PR TITLE
Revert "Handle casts done via helpers and fold overflow operations value numbering (#50450)"

### LINKED ISSUE #51380: Test failure: JIT\\Methodical\\Overflow\\FloatOvfToInt2_do\\FloatOvfToInt2_do.cmd
Also, JIT\\Methodical\\Overflow\\FloatOvfToInt2_ro\\FloatOvfToInt2_ro.cmd

This is failing in many test runs, for Windows x86:

https://dev.azure.com/dnceng/public/_build/results?buildId=1092298&view=ms.vss-test-web.build-test-results-tab
https://dev.azure.com/dnceng/public/_build/results?buildId=1092164&view=ms.vss-test-web.build-test-results-tab
https://dev.azure.com/dnceng/public/_build/results?buildId=1092177&view=ms.vss-test-web.build-test-results-tab

### LINKED ISSUE #51381: Test failure: ManagedTests.DynamicCSharp.Conformance.dynamic.dynamicType.conversions.numeric002.numeric002.Program.DynamicCSharpRunTest
Fails in many configurations.

https://dev.azure.com/dnceng/public/_build/results?buildId=1092269&view=ms.vss-test-web.build-test-results-tab&runId=33463320&resultId=180640&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
----- start Fri 04/16/2021  8:31:07.07 ===============  To repro directly: ===================================================== 
pushd C:\h\w\B49409DF\w\BC6D0999\e\
"C:\h\w\B49409DF\p\dotnet.exe" exec --runtimeconfig System.Dynamic.Runtime.Tests.runtimeconfig.json --depsfile System.Dynamic.Runtime.Tests.deps.json xunit.console.dll System.Dynamic.Runtime.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\B49409DF\w\BC6D0999\e>"C:\h\w\B49409DF\p\dotnet.exe" exec --runtimeconfig System.Dynamic.Runtime.Tests.runtimeconfig.json --depsfile System.Dynamic.Runtime.Tests.deps.json xunit.console.dll System.Dynamic.Runtime.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Dynamic.Runtime.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Dynamic.Runtime.Tests (found 2901 test cases)
  Starting:    System.Dynamic.Runtime.Tests (parallel test collections = on, max threads = 2)
    ManagedTests.DynamicCSharp.Conformance.dynamic.dynamicType.conversions.numeric002.numeric002.Program.DynamicCSharpRunTest [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   1
      Stack Trace:
        /_/src/libraries/System.Dynamic.Runtime/tests/Dynamic.DynamicType/Conformance.dynamic.dynamicType.conversions.cs(5161,0): at ManagedTests.DynamicCSharp.Conformance.dynamic.dynamicType.conversions.numeric002.numeric002.Program.DynamicCSharpRunTest()
  Finished:    System.Dynamic.Runtime.Tests
=== TEST EXECUTION SUMMARY ===
   System.Dynamic.Runtime.Tests  Total: 2901, Errors: 0, Failed: 1, Skipped: 0, Time: 423.388s
```

### PR DESCRIPTION
**Pull request by SingleAccretion**
This is causing too many failures for me to investigate in time (#51381, #51380), so reverting the change wholesale.

I am planning to revisit this with the approach of not folding UB casts.

Note that UB means Undefined Behavior

cc @BruceForstall, @tannergooding

### CODE REVIEW

**Comment by tannergooding** [comment]
This LGTM. However, is there a smaller change we can make to just block the new folding rather than reverting the entire PR?

If not, that's fine.

**Comment by SingleAccretion** [comment]
I think so, yes, there is a small change that I could make here (block folding for all UB casts, not just checked ones, in `gtFoldExprConst`, and the same in VN), but it does require me to make sure all the failing tests pass, and I am afraid I will not be able to make sure that is the case in time.

Note on the formatting failure:
> ERROR: failed to download clang-tidy.

this is the second time I am seeing this...

**Review by briansull — APPROVED** [review]
I approve this revert

**Comment by briansull** [comment]
The jit-format on windows x64 failed due to an infrastructure glitch:

```
2021-04-16T16:55:44.9456599Z Invoke-WebRequest : Unable to read data from the transport connection: An existing connection was forcibly closed by 
2021-04-16T16:55:44.9463469Z the remote host.
2021-04-16T16:55:44.9464753Z At line:1 char:1
2021-04-16T16:55:44.9466317Z + Invoke-WebRequest -Uri https://clrjit.blob.core.windows.net/clang-too ...
2021-04-16T16:55:44.9468097Z + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-04-16T16:55:44.9470134Z     + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], IOException
2021-04-16T16:55:44.9471879Z     + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
2021-04-16T16:55:44.9473964Z  
2021-04-16T16:55:44.9810889Z ERROR: failed to download clang-tidy.
```

**Comment by briansull** [comment]
I asked that the Formatting x64 task be re-run, and it acknowledges it but I didn't see it start the re-run.

**Comment by briansull** [comment]
The Linux release failures issue this message:

`##[error]Path does not exist: /datadisks/disk1/workspace/_work/1/a/BuildLogs`

**Pull request merged**
