### PR TITLE
Fix GCC warnings in test build

### PR DESCRIPTION
**Pull request by davmason**

### CODE REVIEW

**Comment by davmason** [comment]
@hoyosjs or @am11, how do I trigger the failing GCC leg on this PR?

**Review by am11 — COMMENTED** [review]
gcc leg is green here, I'll go ahead and close #60738. Thanks. :+1:

**Review by BruceForstall — APPROVED** [review]
LGTM

**Review by jkoritzinsky — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]

**Review by safern — APPROVED** [review]
LGTM

**Comment by davmason** [comment]
I don't see how the failing libraries leg can be related, since this is fixing another failing leg I'm going to merge now

**Pull request merged**
