### PR TITLE
[wasm][debugger] Missing test files

### PR DESCRIPTION
**Pull request by thaystg**
Adding test files that were not added on release 6.0 by mistake.

### CODE REVIEW

**Comment by thaystg** [comment]
@marek-safar Do I need to send an email to tactics for it?

**Comment by marek-safar** [comment]
@thaystg yes but you can reply to the original approval

**Comment by lambdageek** [comment]
This is the project needed for this test https://github.com/dotnet/runtime/blob/release/6.0/src/mono/wasm/debugger/DebuggerTestSuite/Tests.cs#L864 `InspectLocalsUsingClassFromLibraryUsingDebugTypeFull` ?

**Review by lambdageek — APPROVED** [review]

**Comment by thaystg** [comment]
> This is the project needed for this test https://github.com/dotnet/runtime/blob/release/6.0/src/mono/wasm/debugger/DebuggerTestSuite/Tests.cs#L864 `InspectLocalsUsingClassFromLibraryUsingDebugTypeFull` ?

Yes

**Pull request merged**
