### PR TITLE
Adding httpclient extensions with addHeader method

### PR DESCRIPTION
**Pull request by BehtashShirzad**
I have added httpclienExtensions with a method named AddHeader for adding header with dictionary.

### CODE REVIEW

**Comment by MDshirzad** [comment]
@dotnet-policy-service agree

**Comment by MDshirzad** [comment]
> @MDshirzad please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

**Comment by MDshirzad** [comment]
@dotnet-policy-service agree

**Comment by martincostello** [comment]
Thanks for contributing - new additions to the public surface should address an approved API Suggestion. Changes like this won't be merged without one, and would also need appropriate tests to accompany it.

See here to create a new API Suggestion issue: https://github.com/dotnet/runtime/issues/new/choose

**Comment by MihaZupan** [comment]
Thank you for looking to contribute. Closing as per the above comment until there's agreement on the API changes.

**Pull request closed without merging**
