### PR TITLE
remove LangVersion workarounds

### PR DESCRIPTION
**Pull request by kasperk81**

### CODE REVIEW

**Comment by kasperk81** [comment]
@ViktorHofer this is removing https://github.com/dotnet/roslyn/pull/55866 workaround

**Comment by ViktorHofer** [comment]
Asking @joperezr to take a look. I don't think that we want to remove this code as the out-of-band source generators still target Roslyn 3.11, Roslyn 4.0 and now also Roslyn 4.4.

**Comment by ViktorHofer** [comment]
And our source generator tests don't target Roslyn3.11? I thought we had a test project for each Roslyn version. cc @eerhardt

**Comment by kasperk81** [comment]
> And our source generator tests don't target Roslyn3.11?

this lang=preview workaround was added for roslyn >= 4, not 3

**Review by eerhardt — APPROVED** [review]
This LGTM.

Before https://github.com/dotnet/roslyn/pull/55866, projects using SGs that were using the "Incremental Generator" APIs (introduced in 4.0) needed to have `LangVersion=Preview` set.

Roslyn 3.11 SGs don't use the "Incremental Generator" APIs because they didn't exist in 3.11. So this change doesn't affect them.

For both Roslyn 4.0 and 4.4 SGs, we can test without `LangVersion=Preview` now because this is no longer a requirement with the Roslyn we are using to test.

**Comment by ViktorHofer** [comment]
Great, thanks for the explanation Eric @kasperk81

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
