### PR TITLE
Collect all `MethodDesc` fields in one place

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Clarify the purpose of a field by renaming.

### CODE REVIEW

**Comment by davidwrighton** [comment]
Why are you renaming the flags field to the classification field? It still has things that are not part of the classification of the `MethodDesc`.

**Comment by AaronRobinsonMSFT** [comment]
> Why are you renaming the flags field to the classification field? It still has things that are not part of the classification of the MethodDesc.

All values seem to come from the `MethodDescClassification` enum. Did I miss one that isn't from the enum?

**Comment by jkotas** [comment]
> All values seem to come from the MethodDescClassification enum. Did I miss one that isn't from the enum?

The enum is poorly named. It has classification and a bunch of other stuff.

**Comment by AaronRobinsonMSFT** [comment]
> > All values seem to come from the MethodDescClassification enum. Did I miss one that isn't from the enum?
> 
> The enum is poorly named. It has classification and a bunch of other stuff.

Yep. @davidwrighton and I spoke offline. I'm going to rename the enum and change the field name back.

**Review by davidwrighton — APPROVED** [review]
This looks good.

**Pull request merged**
