### PR TITLE
add a null pointer guard around a usage of comp->vnStore

### PR DESCRIPTION
**Pull request by RobertHenry6bev**

### CODE REVIEW

**Comment by JulieLeeMSFT** [comment]
@RobertHenry6bev, .NET 7 RC1 snap is today, so I put this to .NET 8. If you think it should be serviced to .NET 7, please let me know.

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib, please review this PR. If it is done today, we will merge to .NET 7.

**Comment by RobertHenry6bev** [comment]
I do not know if this fix in this PR will specifically fix the issue I have
in https://github.com/dotnet/runtime/issues/72645

It might fix it, but is might not.  This is a simple change

**Comment by RobertHenry6bev** [comment]
I don't think you should assign my change to me :)

**Comment by danmoseley** [comment]
> I don't think you should assign my change to me :)

this sets the owner, not the reviewer. The bot normally does this. Although, I cannot say actually why..

**Comment by AntonLapounov** [comment]
Under what circumstances `comp->vnStore` is `null` at that line?

**Comment by jakobbotsch** [comment]
> Under what circumstances `comp->vnStore` is `null` at that line?

This function is used both before and after value numbering and it is going to be null when used before. However, `IsVNConstant` is going to early out because the VN will be `ValueNumStore::NoVN` in that case, so we haven't run into any problems because of it.

**Review by jakobbotsch — APPROVED** [review]

**Pull request merged**
