### PR TITLE
Build runtime.native.System.IO.Ports on linux-s390x

### PR DESCRIPTION
**Pull request by uweigand**
* Add RID to runtime.native.System.IO.Ports/netcoreapp.rids.props

* Update runtime.native.System.IO.Ports.pkgproj file.

### CODE REVIEW

**Review by adamsitnik — APPROVED** [review]
LGTM, the CI failures are unrelated (#56459)

**Comment by adamsitnik** [comment]
@ViktorHofer it seems that the license check got stuck: 

obraz

is there any way I could re-run it?

**Comment by ViktorHofer** [comment]
Hmm that I don't know. Closing and reopening the PR (after waiting a minute or so) should retrigger all checks.

**Comment by adamsitnik** [comment]
> Closing and reopening the PR (after waiting a minute or so) should retrigger all checks.

That did the trick, thanks!

**Comment by lewing** [comment]
This appears to be blocking code flow on https://github.com/dotnet/runtime/pull/56719 and probably needs to be reverted

cc @jeffhandley

**Comment by jeffhandley** [comment]
Thanks, @lewing! 👀

**Comment by ViktorHofer** [comment]
@uweigand unfortunately we need to revert this change as it's causing the restore the meta package runtime.native.System.IO.Ports.nupkg to fail.

Reason for that is the meta package (by design) references all runtime specific packages. With your PR the runtime.linux-s390x.runtime.native.System.IO.Ports.nupkg is now referenced by the meta package but that runtime specific package isn't built in our official builds and hence missing from the package feed.

We should discuss if there's a better design i.e. avoiding the meta package. Meanwhile as said I will revert the change as part of https://github.com/dotnet/runtime/pull/56899

**Comment by uweigand** [comment]
Sorry for the breakage, I wasn't aware the patch would have this effect.

When this is reverted, the package simply won't be built again on s390x, which means the feature set enabled by this native library will not be available, right?  This seems to be mostly about support for serial ports, modems, etc., so it may not actually be a showstopper if this isn't available.  However, just for completeness, it would be preferable to support the same feature set as on Intel and Arm ...

There is another set of "meta" packages (DotNetHost*), where it seems possible to add a RID even if it isn't part of the official builds.  See https://github.com/dotnet/runtime/pull/56423 (which hasn't been reviewed yet).   Would it be possible to use that mechanism also for the System.IO.Ports package?

**Pull request merged**
