### PR TITLE
Fix Windows HttpStress runs on pipelines

### LINKED ISSUE #106694: [HttpStress] Stress builds are broken on windows
https://dev.azure.com/dnceng-public/public/_build/results?buildId=772226&view=logs&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589&t=17686723-e01f-55c9-b447-aba4418d28eb

> 'docker-compose' is not recognized as the name of a cmdlet, function, script file, or operable program.

Looks like `docker-compose` is no longer available in the image. Weirdly, SslStress is not affected even though both are using `1es-windows-2022-open`.

### PR DESCRIPTION
**Pull request by rzikm**
Fixes #106694

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM.
Is the problem that `docker-compose` is not on the PATH?

**Comment by antonfirsov** [comment]
> Is the problem that `docker-compose` is not on the PATH?

The wrong docker-compose is in PATH:

https://github.com/dotnet/runtime/blob/505f0faf5804732348fbfc123d805f2c47c4abd4/eng/pipelines/libraries/stress/ssl.yml#L65-L68

The build is still failing :(

**Comment by rzikm** [comment]
Stress is running.

**Review by antonfirsov — APPROVED** [review]
Awesome, thanks a lot!

**Comment by rzikm** [comment]
/ba-g test failures are unrelated (no product code changes in this PR)

**Pull request merged**
