### PR TITLE
JIT: Follow related intervals for single-reg LIR temp intervals

### PR DESCRIPTION
**Pull request by jakobbotsch**
Not sure why the code stops following related intervals for LIR temp intervals preferenced to a single register... this removes that restriction.

I hit some regressions in #86388 due to this difference between intervals for locals and intervals for LIR temps.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @kunalspathak 

Small number of mostly positive [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=283227&view=ms.vss-build-web.run-extensions-tab). Sometimes this introduces a new spill; I checked, and that happens because we do not preference LIR edges crossing calls to callee-saved registers. I can try to reopen #81242 after to deal with that.

**Comment by kunalspathak** [comment]
> related intervals for LIR temp intervals

How do we know that this only affects for LIR temp intervals?

**Comment by jakobbotsch** [comment]
> How do we know that this only affects for LIR temp intervals?

All the cases I looked at were LIR temp intervals. Are you worried about some other type of intervals? This loop is going through related intervals and only looking for definitions in those intervals, so I'm not sure it would look at any kinds of intervals (but in any case, shouldn't the preferencing here work the same regardless?)

**Comment by kunalspathak** [comment]
> Are you worried about some other type of intervals

Exactly. We also create `relatedIntervals` for other cases like vector save/restore. I am not entirely sure of why we had `isLocalVar` check to begin with, and so wanted to see if the only come from LIR temp intervals. Regardless, I think this is safe to do.

**Review by kunalspathak — APPROVED** [review]

**Pull request merged**
