### PR TITLE
Add Mono run of CoreCLR Pri0 tests

### LINKED ISSUE #33255: Running CoreCLR tests on Mono : Investigate and hook up running the with PRs/CI, making sure any change in CoreCLR or Mono triggers these test run on Mono
Referring to comments in PR : https://github.com/dotnet/runtime/pull/33176
Investigate and hook up running the CoreCLR tests during PRs/CI, making sure any change in CoreCLR or Mono triggers these test run on Mono

### PR DESCRIPTION
**Pull request by directhex**
Closes: https://github.com/dotnet/runtime/issues/33255

### CODE REVIEW

**Comment by SamMonoRT** [comment]
@directhex @naricc - we should make sure to run these on mono-jit only first, till we can update the issues.target file for others like the interpreter or llvm etc. Also Nathan's runs were only on Mac so far when he created the exclusion list, so we want to make sure the failures from this draft pr runs are accounted for in the issues.target files.

**Comment by naricc** [comment]
So looking at the current failures, in the CI on this PR, I don't see failed tests, just things like:

```
/__w/_temp/42150bdc-e23d-4ccd-a40d-9e7cd319ec53.sh: line 1: crossArg: command not found
/__w/_temp/42150bdc-e23d-4ccd-a40d-9e7cd319ec53.sh: line 1: priorityArg: command not found
/__w/_temp/42150bdc-e23d-4ccd-a40d-9e7cd319ec53.sh: line 1: build-test.sh: command not found
```

I don't see actual test failures I can add to the exclude list.

**Comment by directhex** [comment]
Yeah, not at that stage yet. The YAML is done, but it's not building/running the right thing yet (i.e. the YAML is trying to run a .sh to build the tests which is in src/coreclr but not src/mono, and an equivalent to run the tests)

**Comment by directhex** [comment]
Closing - superseded by https://github.com/dotnet/runtime/pull/34054

**Pull request closed without merging**
