### PR TITLE
Renamed pInitRegZeroed to pInitRegModified, initRegZeroed to initRegM…

### LINKED ISSUE #12815: Follow-up on renaming suggestions in #24371
This issue is about `pInitRegZeroed` parameter used across many functions in CodeGen

> This method is not zero-ing initReg so it sounds strange to me that an out-parameter is named pInitRegZeroed. It also doesn't know or check that it holds zero on input. IMO, it would be clearer to name the argument pInitRegUsed and set it to true if initReg is used for setting the cookie.

_Originally posted by @erozenfeld in https://github.com/dotnet/coreclr/pull/24371_

> I agree that it's confusing. I might rename it `pInitRegModified`. Theoretically it wouldn't have to set it to false if it had actually zero'd the register, but that doesn't actually happen anywhere. It might be worth a comment here in the header to note that the caller is passing in the `initReg` that it uses in the prolog and therefore it needs to know whether it has been set to a non-zero value (or something to that effect).

_Originally posted by @CarolEidt in https://github.com/dotnet/coreclr/pull/24371_

> While I don't disagree about it being potentially confusing, note that `pInitRegZeroed` is the name used in many functions that do the same thing.

_Originally posted by @BruceForstall in https://github.com/dotnet/coreclr/pull/24371_

category:implementation
theme:jit-coding-style
skill-level:beginner
cost:small

### PR DESCRIPTION
**Pull request by skill-bit**
Contributes to #12815.
Description: Renamed pInitRegZeroed to pInitRegModified, initRegZeroed to initRegModified. Updated assignments to reflect name change. (12815)

Fixes #12815

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@ivanbuha Thanks for porting this over to dotnet/runtime.

I can take a look at this next week or if maybe someone in @dotnet/jit-contrib can do it today?

**Review by echesakov — APPROVED** [review]
Looks Good. Thank you for the contribution

**Comment by echesakovMSFT** [comment]
Not related to this change but I feel that initReg and pInitRegModified should a part of CodeGen class state instead of threading through dozen of functions as their arguments. 

@BruceForstall Would you have any concerns with such change?

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
Seems like maybe we should have named this "initRegIsZero" or "initRegDefinitelyZero".

> Not related to this change but I feel that initReg and pInitRegModified should be a part of CodeGen class state instead of threading through dozen of functions as their arguments.

It might be simpler, but it also feel like programming with global variables, which is not great.

**Comment by echesakovMSFT** [comment]
> It might be simpler, but it also feel like programming with global variables, which is not great. 

Well, I agree with the fact that globals are evil in general, but CodeGen class is already stateful. I don't see how this would be different from using CodeGen::prologSize, CodeGen::epilogSize.

We can have a separate nested class that holds the state of initReg.

```c++
struct InitReg
{
  regNumber name;
  bool isModified;
  public void MarkAsModified();
}
```

and have InitReg initReg as a member of CodeGen but this looks like overkill.

Anyway, just a random thought.

**Pull request merged**
