### PR TITLE
Test against iOS 16 and MacOS Ventura

### PR DESCRIPTION
**Pull request by steveisok**

### CODE REVIEW

**Comment by steveisok** [comment]
Tests are failing due to needing xcode 14 beta on the helix machines.

Filed https://github.com/dotnet/arcade/issues/10664

**Comment by danmoseley** [comment]
@dotnet/dnceng when Ventura releases, will this queue be renamed from 'scouting' to  OSX.1300.ARM64.Open ? or should we do that now? otherwise it may be confusing...

**Comment by danmoseley** [comment]
It will be interesting to find out whether https://github.com/dotnet/arcade/issues/10500 worked and we get the "real" version in the logs now.

**Comment by danmoseley** [comment]
should we include coreclr tests also?

**Comment by steveisok** [comment]
> should we include coreclr tests also?

I want to see if the osx scouting queue doesn't timeout on one leg first.

**Comment by premun** [comment]
> @dotnet/dnceng when Ventura releases, will this queue be renamed from 'scouting' to OSX.1300.ARM64.Open ?

My understanding is that we support N, N-1 and N-2 versions (same as Azure DevOps). I guess this means that 10.15 will be upgraded/renamed to 13.00 when 13.00 is out. We will do that gradually so that we can migrate the runtime CI without downtime.

The scouting queues (**osx.amd64.scouting.(iphone/appletv).open**) don't have the version in the name any longer so we don't have a problem there.

However, the scouting queues have very limited capacity (2 machines usually) so there's no way we can run the whole CoreCLR suite there. BCL might be possible (but only one of iOS or tvOS simulators leg as each is about 3 hours of compute time I think?)

**Comment by ilyas1974** [comment]
The systems within this queue will be "updated" to the RTM version of Ventura once it is released. We chose to forgo "scouting" in the name for the newest OS as it would have been a "waste" to create a temporary queue. There is no need to change anything after RTM.

**Pull request closed without merging**
