### PR TITLE
Ensure we account for intrinsics which have gtType=TYP_SIMD16 but gtSIMDSize=32

### LINKED ISSUE #35877: Test failure: Assertion failed '(jitIntrinsic->gtSIMDSize == 12) || (jitIntrinsic->gtSIMDSize == 16)'
Windows x86 JITMinOpts=1 (as well as the JitStress=1/2 tiered legs)

https://dev.azure.com/dnceng/public/_build/results?buildId=631203&view=ms.vss-test-web.build-test-results-tab&runId=19687584&resultId=102867&paneView=debug

tests:
```
JIT\\HardwareIntrinsics\\General\\NotSupported\\NotSupported_ro\\NotSupported_ro.cmd
JIT\\HardwareIntrinsics\\General\\NotSupported\\NotSupported_r\\NotSupported_r.cmd
```

`\r\nAssert failure(PID 5984 [0x00001760], Thread: 5864 [0x16e8]): Assertion failed '(jitIntrinsic->gtSIMDSize == 12) || (jitIntrinsic->gtSIMDSize == 16)' in 'System.Runtime.Intrinsics.Vector256:GetUpper(System.Runtime.Intrinsics.Vector2561[Boolean]):System.Runtime.Intrinsics.Vector1281[Boolean]' during 'Lowering nodeinfo' (IL size 116)\r\n\r\n File: F:\workspace\_work\1\s\src\coreclr\src\jit\lower.cpp Line: 1337\r\n Image: C:\h\w\B03309A7\p\CoreRun.exe\r\n\r\n\r\nReturn code: 1\r\nRaw output file: C:\h\w\B03309A7\w\A5C80920\e\JIT\HardwareIntrinsics\Reports\JIT.HardwareIntrinsics\General\NotSupported\NotSupported_ro\NotSupported_ro.output.txt\r\nRaw output:\r\nBEGIN EXECUTION\r\n "C:\h\w\B03309A7\p\corerun.exe" NotSupported_ro.dll \r\nBeginning test case Vector64Zero at 5/5/2020 6:48:16 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64AllBitsSet at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64BooleanAsGeneric_Boolean at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64ByteAsGeneric_Boolean at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64DoubleAsGeneric_Boolean at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64Int16AsGeneric_Boolean at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64Int32AsGeneric_Boolean at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64Int64AsGeneric_Boolean at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64SByteAsGeneric_Boolean at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64SingleAsGeneric_Boolean at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64UInt16AsGeneric_Boolean at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64UInt32AsGeneric_Boolean at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64UInt64AsGeneric_Boolean at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64BooleanAsGeneric_Byte at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBeginning test case Vector64BooleanAsGeneric_Double at 5/5/2020 6:48:17 AM\r\nRandom seed: 20010415; set environment variable CORECLR_SEED to this value to repro\r\n\r\n\r\nEnding test case at 5/5/2020 6:48:17 AM\r\nBe`

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/35877

### CODE REVIEW

**Review by CarolEidt — APPROVED** [review]
LGTM - thanks!

**Comment by tannergooding** [comment]
`runtime (Libraries Test Run checked coreclr Windows_NT x64 Debug) ` is an unrelated crypto failure

**Comment by safern** [comment]
@bartonjs it seems like this is that cryptic error from the OS that happens once in million runs? 

```
    System.Security.Cryptography.Csp.Tests.RSACryptoServiceProviderTests.PublicOnly_DefaultKey [FAIL]
      Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : An internal error occurred.
      Stack Trace:
        /_/src/libraries/System.Security.Cryptography.Csp/src/System/Security/Cryptography/CapiHelper.Windows.cs(486,0): at Internal.NativeCrypto.CapiHelper.GenerateKey(SafeProvHandle safeProvHandle, Int32 algID, Int32 flags, UInt32 keySize, SafeKeyHandle& safeKeyHandle)
        /_/src/libraries/System.Security.Cryptography.Csp/src/System/Security/Cryptography/CapiHelper.Windows.cs(746,0): at Internal.NativeCrypto.CapiHelper.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Int32 keySize, SafeProvHandle safeProvHandle)
        /_/src/libraries/System.Security.Cryptography.Csp/src/System/Security/Cryptography/RSACryptoServiceProvider.Windows.cs(136,0): at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeKeyHandle()
        /_/src/libraries/System.Security.Cryptography.Csp/src/System/Security/Cryptography/RSACryptoServiceProvider.Windows.cs(235,0): at System.Security.Cryptography.RSACryptoServiceProvider.get_PublicOnly()
        /_/src/libraries/System.Security.Cryptography.Csp/tests/RSACryptoServiceProviderTests.cs(31,0): at System.Security.Cryptography.Csp.Tests.RSACryptoServiceProviderTests.PublicOnly_DefaultKey()
```

It seems like this is the only instance in 200 runs.

**Comment by bartonjs** [comment]
> it seems like this is that cryptic error from the OS that happens once in million runs?

Yep. I've tried getting OS support from it, they say it's unique to the abuse that test machines have and real callers never see problems like that.  Makes it hard to do anything other than let the OS error leak out.

**Comment by danmosemsft** [comment]
@jaredpar another example where we have an unavoidable test failure that we need to be resilient around.

**Comment by tannergooding** [comment]
jitstress failure on is also a separate issue: #35798 (comment)

**Pull request merged**
