### PR TITLE
Fix Vector2/4 Lerp methods

### LINKED ISSUE #35529: Vector2/4.Lerp do not always return value2 when amount is 1
`Vector2.Lerp(value1, value2, amount)` and `Vector4.Lerp(value1, value2, amount)` are currently implemented as `value1 + (value2 - value1) * amount`. However, due to floating-point rounding error this will not always return `value2` when `amount == 1.0f`.

These should be updated to use the same algorithm as `Vector3.Lerp(value1, value2, amount)` which is `(value1 * (1.0f - amount)) + (value2 * amount)`. This algorithm correctly accounts for the rounding error and also allows the algorithm to be freely optimized using `FusedMultiplyAdd` when available.

### PR DESCRIPTION
**Pull request by john-h-k**
* Added 2 new tests, which failed on the old lerp methods
* Added +/-inf tests to Vector3/4 for consistency with Vector2 (where +/-inf tests were already present)

Fixes #35529

### CODE REVIEW

**Comment by john-h-k** [comment]
I see there are 3 unrelated commits but I do not know how to get rid of them, and they were merged in a different PR and produce no diff

**Comment by tannergooding** [comment]
> I see there are 3 unrelated commits but I do not know how to get rid of them, and they were merged in a different PR and produce no diff

Helped John over in Discord, it's down to the 2 commits now 😄

**Comment by tannergooding** [comment]
CC. @pgovind

**Comment by tannergooding** [comment]
Breaking change doc was logged here: https://github.com/dotnet/docs/issues/18937

**Review by tannergooding — APPROVED** [review]

**Pull request merged**
