### PR TITLE
Fix packaging for the browser

### PR DESCRIPTION
**Pull request by Anipik**
Master PR https://github.com/dotnet/runtime/pull/40814
Related Issue #40813

@ericstj i think we dont require an approval for this one as it fixes the broken packaging ?

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by ericstj** [comment]
> @ericstj i think we dont require an approval for this one as it fixes the broken packaging ?

It's just in M2 approval mode now, so we just need support of me and @danmosemsft.  I support this change for RC.  

The only product-visible portion of this change is that it adds a PNSE to System.Drawing.Common for browser.  Previously if you used this package on browser, you'd compile against a 5.0.0.0 versioned ref, but then get a 4.0.0.1 lib at runtime.  Typically our packaging testing infra would have caught this, but it looks like we arent testing for browser.  It might make sense to add browser to the set of RIDs we validate for.

**Comment by ericstj** [comment]
I opened a PR to run package tests on browser-wasm here which should catch if we have any other instances of this: https://github.com/dotnet/runtime/pull/41041

**Comment by danmosemsft** [comment]
pasting from @Anipik 

Description
The System.Drawing.Package is missing a ridless configuration, which results in runtime error while consuming the package on a platform which doesnt derive from windows or unix eg browser
Customer Impact
 The package will work correctly for browser and non windows now unix platforms.
Regression?
 No
 
Risk 
low. This change only affects non-windows non-unix platforms.
 
Test changes in this PR
Package contains the netcoreapp3.0 configuration. @Eric St. John is adding this scenario to package testing as well.

**Comment by danmosemsft** [comment]
Approved for 5.0

**Pull request merged**
