### PR TITLE
Disable the GetTotalPauseDuration test

### PR DESCRIPTION
**Pull request by cshung**
Temporarily disabling the test for #74631

### CODE REVIEW

**Comment by mangod9** [comment]
technically its only failing on arm64? This disables it for all platforms correct?

**Comment by cshung** [comment]
> technically its only failing on arm64? This disables it for all platforms correct?

Yes, this will disables it for all platforms. Is it possible to disable it for arm64 windows only? How?

**Comment by mangod9** [comment]
you could do it in issues.targets: https://github.com/dotnet/runtime/blob/2a747212d2bf60b633a567b8992b06ceab3bb85f/src/tests/issues.targets#L198

**Comment by mangod9** [comment]
> you could do it in issues.targets:
> 
> https://github.com/dotnet/runtime/blob/2a747212d2bf60b633a567b8992b06ceab3bb85f/src/tests/issues.targets#L198

And if win-arm64 only: https://github.com/dotnet/runtime/blob/2a747212d2bf60b633a567b8992b06ceab3bb85f/src/tests/issues.targets#L542

**Comment by cshung** [comment]
> > you could do it in issues.targets:
> > https://github.com/dotnet/runtime/blob/2a747212d2bf60b633a567b8992b06ceab3bb85f/src/tests/issues.targets#L198
> 
> And if win-arm64 only:
> 
> https://github.com/dotnet/runtime/blob/2a747212d2bf60b633a567b8992b06ceab3bb85f/src/tests/issues.targets#L542

Thanks, once the test is disabled using issues.target, will it be run at all?
Since the test don't fail locally, I'd love to see what happened when it fail with [this](https://github.com/dotnet/runtime/pull/74959) PR.

**Review by mangod9 — APPROVED** [review]

**Pull request merged**
