### PR TITLE
[wasm] Don't fail the CI job if Firefox tests fail in `runtime-wasm`

### PR DESCRIPTION
**Pull request by radical**
Debugger tests running on Firefox are known to be unstable right now. So, they can fail on unrelated PRs.
When they are run on `runtime-staging`, the test failures don't mark the whole job as failed.
But when they run on `runtime-wasm`, they do. And this shows up as failed in GitHub checks view, which is not helpful.

### CODE REVIEW

**Review by thaystg — APPROVED** [review]

**Comment by radical** [comment]
The unrelated AOT build failure is likely https://github.com/dotnet/runtime/issues/69653 .
I cancelled the manual pipelines, once I confirmed that the fix still works.

**Review by akoeplinger — APPROVED** [review]

**Comment by radical** [comment]
I'm looking at that right now. If I don't figure out a solution soon, then I'll revert it.

**Pull request merged**
