### PR TITLE
Catch UnicodeEncodeErrors during printing superpmi logs

### PR DESCRIPTION
**Pull request by kunalspathak**
One of the option to simplify the fix is to just replace the encode/decode errors if any with a text. There might be better ways to address this, but this one looks quickest and simplest.

### CODE REVIEW

**Comment by danmoseley** [comment]
They've had issues with this in the perf repo, eg., https://github.com/dotnet/performance/issues/2207.  Seems that `errors='namereplace'` might give a bit more info (if you care)

**Comment by kunalspathak** [comment]
Thanks Dan. We are actually seeing these errors while printing the output from BDN. I think for our case, we don't care about the benchmark names. All the information that we need is already collected in superpmi collectionsl

**Comment by kunalspathak** [comment]
BTW, I tried `errors='namereplace'` and it doesn't fix the problem for me.

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
I kicked off a superpmi collection with this:

https://dev.azure.com/dnceng/internal/_build/results?buildId=1570249&view=results

**Comment by kunalspathak** [comment]
All the collections failed with error:

```
D:\a\_work\1\s\src\coreclr\scripts\superpmi-collect.proj(47,25): error MSB4184: The expression "[System.IO.Directory]::GetDirectories(%HELIX_CORRELATION_PAYLOAD%\superpmi)" cannot be evaluated. Could not find a part of the path 'D:\a\_work\1\s\%HELIX_CORRELATION_PAYLOAD%\superpmi'.
```

@safern or @MattGal - did anything change in helix? 

As seen in [logs](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/1570249/logs/873), we do set the `CorrelationPayloadDirectory -> D:\a\_work\1\s\payload` and it used to work [until Sunday](https://dev.azure.com/dnceng/internal/_build/results?buildId=1567645&view=results).

**Comment by MattGal** [comment]
> @safern or @MattGal - did anything change in helix?

I don't think it's possible for us to accidentally break how environment variables works, but this tracks with what would happen if a process was intentionally started in a special context outside the work item's command.

I'll take a quick peek but a simple "set" command in your work item can help you evaluate this.

**Comment by MattGal** [comment]
@kunalspathak it's very confusing because you're setting your own environment variable named HELIX_CORRELATION_PAYLOAD but you're doing it not on a Helix machine and not as part of a Helix work item.  This would have behaved entirely differently when using the dnceng pool providers, but you seem to have broken after already moving there.

My best guess here is that your version of the `HELIX_CORRELATION_PAYLOAD` needs to be explicitly added to the environment from the pipeline variable you're setting so it can be consumed by later stages.  On an old `buildpool.*` machine, this would have "just worked" but was never an appropriate thing for a build task to know about.

**Comment by BruceForstall** [comment]
But why did this break?

It looks like we picked up an arcade change:

-    <Dependency Name="Microsoft.DotNet.Arcade.Sdk" Version="7.0.0-beta.22068.3">
+    <Dependency Name="Microsoft.DotNet.Arcade.Sdk" Version="7.0.0-beta.22071.6">

**Comment by MattGal** [comment]
> But why did this break?
> 
> It looks like we picked up an arcade change:
> 
> ```
> -    <Dependency Name="Microsoft.DotNet.Arcade.Sdk" Version="7.0.0-beta.22068.3">
> +    <Dependency Name="Microsoft.DotNet.Arcade.Sdk" Version="7.0.0-beta.22071.6">
> ```

I was looking for this... specifically I expected to find you being migrated from dncenginternal pool to 1ES Hosted pool, but I didn't see that.  Note that you're naming your own environment variable like a Helix one, this error is not in a Helix work item.

**Comment by BruceForstall** [comment]
I'm confused: where are we setting HELIX_CORRELATION_PAYLOAD? We are using it, but I don't see us setting it anywhere.

The failure I see is:
```
2022-01-25T07:01:06.1462514Z D:\a\_work\1\s\.dotnet\sdk\6.0.100\MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:D:\a\_work\1\s/artifacts/log/checked/SendToHelix.binlog /clp:Summary /logger:D:\a\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.22071.6\tools\netcoreapp3.1\Microsoft.DotNet.ArcadeLogging.dll /nr:False /p:ContinuousIntegrationBuild=True /p:TreatWarningsAsErrors=true /restore /t:Test /warnaserror D:\a\_work\1\s/src/coreclr/scripts/superpmi-collect.proj
2022-01-25T07:01:07.8706001Z D:\a\_work\1\s\src\coreclr\scripts\superpmi-collect.proj(47,25): error MSB4184: The expression "[System.IO.Directory]::GetDirectories(%HELIX_CORRELATION_PAYLOAD%\superpmi)" cannot be evaluated. Could not find a part of the path 'D:\a\_work\1\s\%HELIX_CORRELATION_PAYLOAD%\superpmi'.
2022-01-25T07:01:07.8833108Z ##[error]src\coreclr\scripts\superpmi-collect.proj(47,25): error MSB4184: The expression "[System.IO.Directory]::GetDirectories(%HELIX_CORRELATION_PAYLOAD%\superpmi)" cannot be evaluated. Could not find a part of the path 'D:\a\_work\1\s\%HELIX_CORRELATION_PAYLOAD%\superpmi'.
```
(https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/1570249/logs/881)

It looks like this is a result of @echesakovMSFT 's https://github.com/dotnet/runtime/pull/64119, which added that call. Maybe the change to the machine pools changed it?

@echesakovMSFT It looks like you're computing the set of PMIPATH directories on the "build" machine, but that's not the set of paths/directories that will exist on the Helix machine, where the command will execute. So:
```
PmiPathDirectories Include="$([System.IO.Directory]::GetDirectories($(SuperPMIDirectory)))" />
```
is invalid.

**Comment by MattGal** [comment]
> I'm confused: where are we setting HELIX_CORRELATION_PAYLOAD? We are using it, but I don't see us setting it anywhere.

if @echesakovMSFT's previous work was on a buildpool.* machine the variable would be set but should not have been used.  I didn't see evidence of such, though.  Sounds like you've found your problem though.

**Comment by BruceForstall** [comment]
@echesakovMSFT Instead of:
```
<WorkItemCommand>$(SuperPMIDirectory)\superpmi.py collect -log_level DEBUG --$(CollectionType) -pmi_location $(SuperPMIDirectory)\pmi.dll -pmi_path @(PmiPathDirectories->'%(FullPath)', ' ')</WorkItemCommand> 
```
and doing the directory finding logic in msbuild (ick), maybe add a `-pmi_path_recursive` argument that takes a root dir and adds all the subdirs to PMIPATH -- so all the logic can be done in Python. Then set:
```
<WorkItemCommand>$(SuperPMIDirectory)\superpmi.py collect -log_level DEBUG --$(CollectionType) -pmi_location $(SuperPMIDirectory)\pmi.dll -pmi_path_recursive $(SuperPMIDirectory)</WorkItemCommand> 
```
?

**Comment by echesakovMSFT** [comment]
>  It looks like you're computing the set of PMIPATH directories on the "build" machine, but that's not the set of paths/directories that will exist on the Helix machine, where the command will execute. 

Right, let me fix this. 

I think I will go an easier path and explicitly specify 3-4 subdirectories for `WorkItemCommand`.

**Pull request merged**
