### PR TITLE
Propagate LibrariesConfiguration to LibraryImportGenerator project reference

### PR DESCRIPTION
**Pull request by elinor-fung**
The LibraryImportGenerator was referenced by tasks both directly and transitively. Since tasks always build in Debug, the generator was being built in both Release and Debug when building libraries in Release, resulting in bin clashes and the potential for use to accidentally ship a debug version of the generator.

- Mark tasks as non-source projects (such that the generator is no longer automatically enabled and directly referenced)
- Propagate LibrariesConfiguration to LibraryImportGenerator project reference such that it will always build matching the libraries configuration when used

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Review by jkoritzinsky — APPROVED** [review]

**Comment by elinor-fung** [comment]
Still missing something for actual test run - seems like task assemblies aren't ending up in the correlation payload. I'll work on sorting it out after the revert goes in.
```
        MSBuild version 17.6.0-preview-23108-10+51df47643 for .NET
          AppDir: /root/helix/work/workitem/e/baseservices/mono/runningmono/WasmApp/
          TestBinDir: /root/helix/work/workitem/e/baseservices/mono/runningmono
          ArtifactsBinDir: 
        /root/helix/work/correlation/build/WasmApp.targets(441,5): error MSB4062: The "Microsoft.WebAssembly.Build.Tasks.WasmLoadAssembliesAndReferences" task could not be loaded from the assembly /root/helix/work/correlation/WasmAppBuilder/WasmAppBuilder.dll. Could not load file or assembly '/root/helix/work/correlation/WasmAppBuilder/WasmAppBuilder.dll'. The system cannot find the file specified. [/root/helix/work/correlation/wasm-test-runner/WasmTestRunner.proj]
        /root/helix/work/correlation/build/WasmApp.targets(441,5): error MSB4062:  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [/root/helix/work/correlation/wasm-test-runner/WasmTestRunner.proj]
```

**Comment by ViktorHofer** [comment]
Sorry for my late contribution to this discussion but I was out for the last two weeks and just saw this change and the underlying issue.

The combination of the subset system (libs, tasks, host, clr, mono, ...) plus the configuration matrix per components (libraries-configuration, coreclr-configuration, mono-configuration, runtime-configuration, host-configuration and the hardcoded tasks Debug configuration) makes it hard to reference components between subsets without overbuilding.

In this particular case, overbuilding of the source generator projects result in bin-clashes as the `artifacts/bin/microsoft.netcore.app.ref` targeting pack folder doesn't encode the `Configuration` in its path. IIRC we chose to not encode the `Configuration` value in the targeting pack path for inner-loop efficiency. The notion of Debug vs Release isn't important when it comes to reference assemblies. Source generators might be different in that regard but there was no strong reason to change the targeting pack's artifacts layout with the addition of source generators.

If we would now decide to change that and encode the `Configuration` value in the targeting pack directory, we would avoid bin-clashes but still overbuild source generator assemblies as they are referenced from different subsets: `libs` and `tasks`.

While we don't have many cross subset live dependencies today, [we want to define more in the future](https://github.com/dotnet/runtime/issues/43110). I want to encourage us to come up with a long-term solution.

Did we consider not flowing the parent configuration to the child project when they aren't part of the same subset? I.e. `Crossgen2Tasks.csproj` should not flow its configuration to `Microsoft.Interop.LibraryImportGenerator.csproj`. The former project's configuration should be whatever `$(TasksConfiguration)` is while the latter project's configuration is `$(LibrariesConfiguration)`. I see two possible solutions:
1. Flow the `LibrariesConfiguration` explicitly in [generators.targets](https://github.com/dotnet/runtime/blob/e7ed417c2bf4a24a0694a387f33ba843a2318fdc/eng/generators.targets#L48-L51). This is probably the right option for this PR to avoid overbuilding when referencing generator projects (which happens implicitly in generators.targets) from a subset other than `libs`.
2. Make sure that projects know and respect their respective subset configuration (i.e. everything under `src/libraries` should use `$(LibrariesConfiguration)`). Today, this is only enforced in Subsets.props which doesn't handle project-to-project references between different subsets.

**Review by ViktorHofer — CHANGES_REQUESTED** [review]
Marking as "Request changes" to make sure that we first resolve the design discussion before merging the change in.

**Comment by elinor-fung** [comment]
> If we would now decide to change that and encode the Configuration value in the targeting pack directory, we would avoid bin-clashes but still overbuild source generator assemblies as they are referenced from different subsets: libs and tasks.

Just want to add one note that it is not just source generators. This change removes the direct reference to the source generator from the tasks, but the source generator is pulled in because one of the tasks reference a (non-source generator) libraries project, which references the source generator.

I don't think that materially changes anything you said - it all still applies. It seems like we would want both (1) and (2), since (1) would handle the source generator, but we have the same overbuilding problem for other cross-subset references (like the libraries project currently referenced by tasks) and would need something like (2).

What configuration the tasks should build in is maybe orthogonal to all that. To me, it seems odd to always use Debug, since they are being used as build utilities, so I'd assume we'd want the fastest execution / least resource usage in CI. That said, I can also understand the view of 'always Debug because it is simpler'.

**Comment by elinor-fung** [comment]
For the purposes of this PR and fixing the possibility of shipping debug bits, I changed this to just mark tasks as non-source and do (1) - flow the `LibrariesConfiguration` to the project reference in generators.targets.

**Comment by elinor-fung** [comment]
Superseded by https://github.com/dotnet/runtime/pull/84931

**Pull request closed without merging**
