### PR TITLE
Enable isolates storage tests on maccatalyst

### LINKED ISSUE #87485: IsolatedStorage tests failing on CI on maccatalyst
### Description

After reenabling tests on CI on maccatalyst by #84930 IsolatedStorage tests are failing on CI.

### Reproduction Steps

Was not able to reproduce locally.
For CI run 
/azp run runtime-maccatalyst

### Expected behavior

System.IO.IsolatedStorage.Tests should pass on maccatalyst.

### Actual behavior

Several test cases are failing from System.IO.IsolatedStorage.Tests on maccatalyst on CI.

### Regression?

_No response_

### Known Workarounds

Currently tests are skipped on maccatalyst.

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mkhamoyan**
Enable isolated storage tests on maccatalyst.

Fix https://github.com/dotnet/runtime/issues/87485

### CODE REVIEW

**Comment by mkhamoyan** [comment]
Isolated storage tests are passing on maccatalyst. Failures are not related to PR.

**Review by mdh1418 — APPROVED** [review]

**Pull request merged**
