### PR TITLE
[NO MERGE] Expriments with QuicStream sending

### PR DESCRIPTION
**Pull request by ManickaP**
WIP

### CODE REVIEW

**Comment by ManickaP** [comment]
/benchmark httpclient-kestrel-configured aspnet-perf-win libs --variable httpVersion="3.0"

**Comment by CarnaViire** [comment]
@sebastienros Can you plz take a look - Bot finished both base&PR runs and printed the table in the logs, but failed to post a comment...

@ManickaP you can check the results in the logs here https://dev.azure.com/dnceng/internal/_build/results?buildId=2212734&view=logs&j=75d9e29f-0f2e-5603-71e1-b4ced6dfbff3&t=ccba0c24-ff75-569c-b1fb-989a3e917eea&l=3649

**Comment by ManickaP** [comment]
/benchmark httpclient-kestrel-configured aspnet-perf-win libs --variable httpVersion="3.0" --variable responseSize=4194304

**Comment by ManickaP** [comment]
/benchmark httpclient-kestrel-configured aspnet-perf-win libs --variable scenario="post" --variable httpVersion="3.0" --variable responseSize=0 --variable requestContentSize=4194304

**Comment by ManickaP** [comment]
/benchmark httpclient-kestrel-configured aspnet-perf-win libs --variable scenario="post" --variable httpVersion="3.0"  --variable responseSize=0 --variable requestContentSize=8192

**Comment by ManickaP** [comment]
/benchmark httpclient-kestrel-configured aspnet-perf-win libs --variable scenario="post" --variable httpVersion="3.0" --variable responseSize=0 --variable requestContentSize=8192 --variable requestContentWriteSize=512

**Comment by ManickaP** [comment]
/benchmark httpclient-kestrel-configured aspnet-perf-win libs --variable scenario="post" --variable httpVersion="3.0" --variable responseSize=0 --variable requestContentSize=8192 --variable requestContentWriteSize=1024

**Pull request closed without merging**
