### PR TITLE
Remove performance runs from CI

### PR DESCRIPTION
**Pull request by DrewScoggins**

### CODE REVIEW

**Comment by DrewScoggins** [comment]
@danmosemsft

**Comment by DrewScoggins** [comment]
To address https://github.com/dotnet/runtime/issues/38138

**Review by billwert — APPROVED** [review]

**Comment by danmosemsft** [comment]
Thanks. Can you help me undestand the chagne? I don't think I see any place node reuse is disabled.

BTW, I think it's still a hypothesis that disabling node reuse would help  (probably a good one nevertheless). What for sure would help is a single proc build, but I'm assuming that would be unnacceptably slow.

**Comment by DrewScoggins** [comment]
Sorry, I just changed the PR title to accurately reflect what the PR is actually doing now. Given the level of investment to be part of the CI and the value that we had received from running the perf runs as part of CI (very low in our estimation) we have just decided to disable the pr runs.

**Comment by danmosemsft** [comment]
Sounds good, it makes sense to balance {machine scarcity, job unreliability) vs. (actual value we see it providing).

**Comment by danmosemsft** [comment]
I can't read yaml well enough yet to review, @safern can you take a quick look?

**Review by jkoritzinsky — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Pull request merged**
