### PR TITLE
Flow binder gen diag locations correctly & pick up more bind input patterns

### LINKED ISSUE #86653: ConfigurationBindingGenerator does not work unless Microsoft.Extensions.DependencyInjection.Abstractions is referenced
### Description

Reported in https://github.com/dotnet/runtime/issues/86557

When creating an app that only references Microsoft.Extensions.Configuration.Binder, the source generator for configuration will not run unless Microsoft.Extensions.Hosting is also referenced.

This appears to be due to a check for `IServiceCollection` here:
https://github.com/dotnet/runtime/blob/8f19f4ebd511994be27a2e1f4c88424a26f91e7c/src/libraries/Microsoft.Extensions.Configuration.Binder/gen/ConfigurationBindingGenerator.Parser.cs#L45-L48

The binder can be used without DI, so we shouldn't require this type definition to be present.

### Reproduction Steps

Project:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-preview.5.23273.2" />
    <!-- <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0-preview.5.23273.2" /> -->
  </ItemGroup>

</Project>
```

Nuget.Config:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

Source code:
```c#
var c = new ConfigurationBuilder().Build();
var x = c.GetSection("Anything").Get<TimeSpan?>((_) =>  {} );
Console.WriteLine(x.GetValueOrDefault());
```

Repro project: [testConfig.zip](https://github.com/dotnet/runtime/files/11547534/testConfig.zip) (remove DI.Abstractions reference to repro)

### Expected behavior

Build succeeds and uses generator.

### Actual behavior

Generator is not triggered, uncomment `Microsoft.Extensions.DependencyInjection.Abstractions` to make generator run.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### LINKED ISSUE #88865: Audit how we surface diagnostics from the config binding generator and how users might suppress them
Initial discussion - https://github.com/dotnet/runtime/pull/88067#discussion_r1261589052.

### LINKED ISSUE #89273: Configuration binding source generator doesn't handle generics correctly
When trying to use the configuration binder source generator with an expression that uses a closed-generic type, I'm getting a warning saying it isn't supported.

However, since the expression is a closed-generic type, the type is able to be understood. In this case, the type is `OidcProviderOptions`.

We have this case in ASP.NET Auth. Specifically the Blazor WASM project templates use this exact pattern.

https://github.com/dotnet/aspnetcore/blob/24bbfb6d8398684091cc970bd342df185c8f9421/src/ProjectTemplates/Web.ProjectTemplates/content/ComponentsWebAssembly-CSharp/Program.cs#L15C1-L21

### Repro steps

`dotnet build` the following app.

```C#
using Microsoft.Extensions.Configuration;

var config = new ConfigurationBuilder().Build();

AddOidcAuthentication(options =>
{
    config.Bind("Local", options.ProviderOptions);  // warning HERE
});

static void AddOidcAuthentication(Action<RemoteAuthenticationOptions<OidcProviderOptions>> configure)
{
    configure(new());
}

public class RemoteAuthenticationOptions<TRemoteAuthenticationProviderOptions> where TRemoteAuthenticationProviderOptions : new()
{
    public TRemoteAuthenticationProviderOptions ProviderOptions { get; } = new TRemoteAuthenticationProviderOptions();
}

public class OidcProviderOptions
{
    public string? Authority { get; set; }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0-preview.7.23370.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-preview.7.23370.3" />
  </ItemGroup>

</Project>
```

### Expected results

The above app should build successfully with no warnings or errors.

### Actual results

```
Program.cs(7,5): warning SYSLIB1104: Binding logic was not generated for a binder call. Unsupported input patterns include generic calls and passing boxed objects.
```

### LINKED ISSUE #89732: Configuration-binding source generator: Binding logic was not generated for a binder call
### Description

I'm trying to use the new configuration-binding source generator in my console application, but it's not working for my use case and I'm not sure why.
I'm getting: `warning SYSLIB1104: Binding logic was not generated for a binder call. Unsupported input patterns include generic calls and passing boxed objects.`

-----

Context: this same code, if compiled with `/p:PublishTrimmed=true` stops working as expected and reading the values from the configuration files/env variables.
That's why I'm looking to move to the source generator asap.
Any workaround until it works properly is also welcome, of course 😊

### Reproduction Steps

Given:

```csharp
public static class Configuration
{
    public static GeneralSettings GeneralSettings { get; set; } = new GeneralSettings();
}

public sealed class GeneralSettings
{
    public bool DisableLogging { get; set; } = false;
}
```

This bind call isn't behaving as expected:
```csharp
var environmentName = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Production";
var config = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
    .AddJsonFile($"appsettings.{environmentName}.json", optional: true, reloadOnChange: true)
    .AddEnvironmentVariables()
    .Build();

config.GetRequiredSection(nameof(GeneralSettings)).Bind(Configuration.GeneralSettings); // <-----------------
```

### Expected behavior

Source generator is used

### Actual behavior

Source generator isn't used and warning is triggered, therefore can't trim the app properly and load the configuration from file/env variable.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

```log
.NET SDK:
 Version:   8.0.100-preview.6.23330.14
 Commit:    ba97796b8f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
```

### Other information

Same error as in https://github.com/dotnet/runtime/issues/89273, but no generics involved here.

### PR DESCRIPTION
**Pull request by layomia**
Fixes https://github.com/dotnet/runtime/issues/88865.
Fixes https://github.com/dotnet/runtime/issues/89273.
Fixes https://github.com/dotnet/runtime/issues/89732.
Closes https://github.com/dotnet/runtime/issues/86653 (adds test).

### CODE REVIEW

**Comment by layomia** [comment]
Still iterating on the approach to take here. Per offline discussion with @ericstj  we could tie each diagnostic to the binding invocation that specifies an input graph that contains types that we'd issue diagnostics for. Will push another commit.

Unsure what the issue with `System.Diagnostics.Tracing` is, but it could be that Roslyn is providing some phantom members in the graph of `JsonWriterOptions`/`JsonEncoder` on some platforms. Might need to change the test type to avoid that.

**Comment by ericstj** [comment]
Trace switch issue appears to be related to https://github.com/dotnet/runtime/commit/d4d0812e3b882e0d844e1877eb62b893cd26bbff - pull the latest from main to your branch to see a local repro.

**Comment by layomia** [comment]
> Still iterating on the approach to take here. Per offline discussion with @ericstj we could tie each diagnostic to the binding invocation that specifies an input graph that contains types that we'd issue diagnostics for. Will push another commit.

Refreshed the PR to take this approach, rather than tie diagnostics to the locations of unsupported type or property definitions.

**Comment by layomia** [comment]
cc @eduherminio I verified that this PR fixes your repro https://github.com/dotnet/runtime/issues/89732#issuecomment-1658920237.

**Review by tarekgh — APPROVED** [review]

**Comment by layomia** [comment]
Failure looks unrelated https://github.com/dotnet/runtime/issues/89806, thanks @ericstj.

**Pull request merged**
