### PR TITLE
JIT: ensure bbflags get treated as 64 bit literals

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Expressions like `~(BBF_KEEP_BBJ_ALWAYS)` were being evaluated as 32 bit signed
quantities, leading to mask value `00000000_7FFFFFFFF` instead of the desired
`FFFFFFFF_7FFFFFFFF`, causing inadvertent clearing of flags with higher value.

SPMI diffs showed the only flag loss that impacted codegen was `BBF_HAS_CALL`,
which feeds into the CSE heuristics. So no known correctness issue, but it is
certainly possible to also lose `BBF_DOMINATED_BY_EXCEPTIONAL_ENTRY` or
`BBF_HAS_SUPPRESSGC_CALL` and that may be more serious.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib 

SPMI diff summary: 32 total methods with Code Size differences (21 improved, 11 regressed), 1 unchanged.

All these diffs are changes in CSE behavior.

**Review by BruceForstall — APPROVED** [review]
This LGTM. However, I wonder if we should change these to code like the following, to make it easier to read and ensure we're not missing slots or overlapping:

```
#define MAKE_BBFLAG(bit) (1ULL << (bit))

#define BBF_VISITED             MAKE_BBFLAG(0) // BB visited during optimizations
#define BBF_MARKED              MAKE_BBFLAG(1) // BB marked  during optimizations
#define BBF_CHANGED             MAKE_BBFLAG(2) // input/output of this block has changed
```

etc.

**Comment by AndyAyersMS** [comment]
Sure, makes sense.

**Comment by AndyAyersMS** [comment]
Looks like the small number of OSR tests we run in innerloop CI are failing on linux/osr. Note `BBF_PATCHPOINT` used by OSR is also in the potentially implicated group of flags. Will investigate.

**Comment by AndyAyersMS** [comment]
PMI shows a slightly wider set of diffs:
```
Total bytes of delta: -998 (-0.00% of base)
    diff is an improvement.

Top file regressions (bytes):
          23 : System.Data.OleDb.dasm (0.01% of base)
          12 : Microsoft.Diagnostics.Tracing.TraceEvent.dasm (0.00% of base)
           5 : System.Net.WebClient.dasm (0.01% of base)
           4 : System.Memory.dasm (0.00% of base)
           3 : Microsoft.CodeAnalysis.dasm (0.00% of base)
           3 : System.Linq.Expressions.dasm (0.00% of base)
           3 : System.Linq.Queryable.dasm (0.00% of base)
           3 : System.Net.Mail.dasm (0.00% of base)
           2 : Newtonsoft.Json.Bson.dasm (0.00% of base)
           2 : System.ComponentModel.Composition.dasm (0.00% of base)
           2 : xunit.execution.dotnet.dasm (0.00% of base)

Top file improvements (bytes):
        -462 : System.Private.CoreLib.dasm (-0.01% of base)
        -106 : FSharp.Core.dasm (-0.00% of base)
        -105 : System.Linq.dasm (-0.01% of base)
         -65 : System.Collections.dasm (-0.01% of base)
         -54 : System.Collections.Immutable.dasm (-0.00% of base)
         -47 : System.Configuration.ConfigurationManager.dasm (-0.01% of base)
         -39 : Microsoft.CodeAnalysis.VisualBasic.dasm (-0.00% of base)
         -38 : Microsoft.CodeAnalysis.CSharp.dasm (-0.00% of base)
         -26 : System.Numerics.Tensors.dasm (-0.01% of base)
         -24 : System.Net.Http.dasm (-0.00% of base)
         -20 : System.Linq.Parallel.dasm (-0.00% of base)
         -17 : Microsoft.Diagnostics.FastSerialization.dasm (-0.02% of base)
         -11 : System.Private.Xml.dasm (-0.00% of base)
          -9 : System.Threading.Channels.dasm (-0.01% of base)
          -8 : CommandLine.dasm (-0.00% of base)
          -8 : System.Data.Common.dasm (-0.00% of base)
          -8 : System.Threading.Tasks.Dataflow.dasm (-0.00% of base)
          -5 : Newtonsoft.Json.dasm (-0.00% of base)
          -4 : Microsoft.Extensions.Logging.Abstractions.dasm (-0.01% of base)
          -2 : System.ComponentModel.TypeConverter.dasm (-0.00% of base)

32 total files with Code Size differences (21 improved, 11 regressed), 236 unchanged.

Top method regressions (bytes):
          23 ( 1.15% of base) : System.Data.OleDb.dasm - OleDbMetaDataFactory:PrepareCollection(String,ref,DbConnection):DataTable:this
          12 ( 0.64% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - <EnumerateEventHeaders>d__19:MoveNext():bool:this
          11 ( 1.01% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Binder:BindFinalImplicitSelectClause(BoundQueryClauseBase,DiagnosticBag):BoundQueryClause:this
           7 ( 0.08% of base) : CommandLine.dasm - <RenderParsingErrorsTextAsLines>d__53`1:MoveNext():bool:this (7 methods)
           6 ( 0.57% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - ConstraintsHelper:GetAllConstraints(TypeParameterSymbol,ArrayBuilder`1,Nullable`1)
           5 ( 0.17% of base) : System.Net.WebClient.dasm - <DownloadBitsAsync>d__150:MoveNext():this
           4 ( 0.08% of base) : System.Memory.dasm - ReadOnlySequence`1:Slice(long,SequencePosition):ReadOnlySequence`1:this (7 methods)
           3 ( 0.12% of base) : Microsoft.CodeAnalysis.dasm - ImmutableArrayExtensions:Distinct(ImmutableArray`1,IEqualityComparer`1):ImmutableArray`1 (7 methods)
           3 ( 0.48% of base) : System.Collections.Immutable.dasm - Node:AddRange(IEnumerable`1):Node:this (7 methods)
           3 ( 0.22% of base) : System.Collections.Immutable.dasm - Node:MutateLeft(Node):Node:this (7 methods)
           3 ( 0.22% of base) : System.Collections.Immutable.dasm - Node:MutateRight(Node):Node:this (7 methods)
           3 ( 0.82% of base) : System.Collections.Immutable.dasm - Node:Search(__Canon,IComparer`1):Node:this (2 methods)
           3 ( 1.29% of base) : System.Collections.Immutable.dasm - Node:IndexOf(__Canon,IComparer`1):int:this
           3 ( 2.59% of base) : System.Net.Mail.dasm - MultiAsyncResult:End(IAsyncResult):Object
           3 ( 1.26% of base) : System.Threading.Tasks.Dataflow.dasm - ImmutableArray`1:Remove(__Canon):ImmutableArray`1:this
           2 ( 0.20% of base) : Microsoft.CodeAnalysis.dasm - EnumerableExtensions:ToSet(IEnumerable`1):ISet`1 (7 methods)
           2 ( 0.32% of base) : Newtonsoft.Json.Bson.dasm - CollectionUtils:ArrayEmpty():ref (7 methods)
           2 ( 0.32% of base) : Newtonsoft.Json.dasm - CollectionUtils:ArrayEmpty():ref (7 methods)
           2 ( 0.39% of base) : System.Collections.Immutable.dasm - ImmutableExtensions:GetCount(byref):int (7 methods)
           2 ( 1.53% of base) : System.Linq.Expressions.dasm - HybridReferenceDictionary`2:TryGetValue(__Canon,byref):bool:this

Top method improvements (bytes):
        -222 (-5.66% of base) : System.Private.CoreLib.dasm - EventProvider:WriteEvent(byref,long,long,long,ref):bool:this
         -47 (-1.82% of base) : System.Configuration.ConfigurationManager.dasm - MgmtConfigurationRecord:GetConfigDeclarationUpdates(int):SectionUpdates:this
         -26 (-2.96% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - MemberSemanticModel:InAnonymousTypeInitializerInterior(VisualBasicSyntaxNode,int,byref):bool:this
         -26 (-1.21% of base) : System.Private.CoreLib.dasm - Dictionary`2:TryInsert(__Canon,long,ubyte):bool:this (2 methods)
         -25 (-0.71% of base) : System.Private.CoreLib.dasm - ArraySortHelper`2:DownHeap(Span`1,Span`1,int,int,int,IComparer`1) (7 methods)
         -22 (-1.42% of base) : Microsoft.CodeAnalysis.CSharp.dasm - Binder:BindNonGenericSimpleNamespaceOrTypeOrAliasSymbol(IdentifierNameSyntax,DiagnosticBag,ConsList`1,bool,NamespaceOrTypeSymbol,bool,ArrayBuilder`1):Symbol:this
         -19 (-1.26% of base) : System.Collections.dasm - <Reverse>d__84:MoveNext():bool:this (7 methods)
         -18 (-1.81% of base) : System.Private.CoreLib.dasm - MemoryExtensions:AsMemory(ArraySegment`1,int,int):Memory`1 (7 methods)
         -18 (-1.75% of base) : System.Private.CoreLib.dasm - ContinuationResultTaskFromTask`1:InnerInvoke():this (7 methods)
         -18 (-1.82% of base) : System.Private.CoreLib.dasm - ContinuationTaskFromResultTask`1:InnerInvoke():this (7 methods)
         -18 (-1.79% of base) : System.Private.CoreLib.dasm - ContinuationResultTaskFromResultTask`2:InnerInvoke():this (7 methods)
         -17 (-0.37% of base) : Microsoft.Diagnostics.FastSerialization.dasm - SegmentedList`1:QuickSort(int,int,IComparer`1):this (7 methods)
         -15 (-1.24% of base) : System.Collections.Immutable.dasm - ValuesCollectionAccessor`2:Contains(long):bool:this (7 methods)
         -15 (-1.03% of base) : System.Private.CoreLib.dasm - HashSet`1:IsSubsetOf(IEnumerable`1):bool:this (7 methods)
         -14 (-0.38% of base) : System.Collections.dasm - SortedSet`1:CopyTo(ref,int,int):this (7 methods)
         -14 (-0.26% of base) : System.Collections.Immutable.dasm - Node:ConvertAll(Func`2):Node:this (49 methods)
         -14 (-1.73% of base) : System.Private.CoreLib.dasm - Task`1:InnerInvoke():this (7 methods)
         -13 (-0.16% of base) : CommandLine.dasm - ResultExtensions:Flatten(Result`2):Result`2 (7 methods)
         -13 (-0.73% of base) : FSharp.Core.dasm - EnumeratorWrappingLazyGenerator`1:System.Collections.IEnumerator.MoveNext():bool:this (7 methods)
         -13 (-7.18% of base) : System.Linq.dasm - ListPartition`1:TryGetElementAt(int,byref):__Canon:this

Top method regressions (percentages):
           3 ( 2.59% of base) : System.Net.Mail.dasm - MultiAsyncResult:End(IAsyncResult):Object
           2 ( 1.65% of base) : System.Linq.Expressions.dasm - HybridReferenceDictionary`2:Remove(__Canon):this
           2 ( 1.53% of base) : System.Linq.Expressions.dasm - HybridReferenceDictionary`2:TryGetValue(__Canon,byref):bool:this
           3 ( 1.29% of base) : System.Collections.Immutable.dasm - Node:IndexOf(__Canon,IComparer`1):int:this
           3 ( 1.26% of base) : System.Threading.Tasks.Dataflow.dasm - ImmutableArray`1:Remove(__Canon):ImmutableArray`1:this
          23 ( 1.15% of base) : System.Data.OleDb.dasm - OleDbMetaDataFactory:PrepareCollection(String,ref,DbConnection):DataTable:this
          11 ( 1.01% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - Binder:BindFinalImplicitSelectClause(BoundQueryClauseBase,DiagnosticBag):BoundQueryClause:this
           3 ( 0.82% of base) : System.Collections.Immutable.dasm - Node:Search(__Canon,IComparer`1):Node:this (2 methods)
           1 ( 0.74% of base) : CommandLine.dasm - SpecificationPropertyRules:ContainsIfNotEmpty(IEnumerable`1,__Canon):bool
          12 ( 0.64% of base) : Microsoft.Diagnostics.Tracing.TraceEvent.dasm - <EnumerateEventHeaders>d__19:MoveNext():bool:this
           1 ( 0.61% of base) : System.Private.CoreLib.dasm - ThreadHelper:ThreadStart_Context(Object)
           6 ( 0.57% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - ConstraintsHelper:GetAllConstraints(TypeParameterSymbol,ArrayBuilder`1,Nullable`1)
           1 ( 0.57% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - SyntaxNormalizer:VisitMethodStatement(MethodStatementSyntax):SyntaxNode:this
           1 ( 0.50% of base) : System.Private.CoreLib.dasm - Boolean:CompareTo(Object):int:this
           1 ( 0.48% of base) : System.Linq.dasm - Enumerable:Append(IEnumerable`1,__Canon):IEnumerable`1
           1 ( 0.48% of base) : System.Linq.dasm - Enumerable:Prepend(IEnumerable`1,__Canon):IEnumerable`1
           3 ( 0.48% of base) : System.Collections.Immutable.dasm - Node:AddRange(IEnumerable`1):Node:this (7 methods)
           1 ( 0.45% of base) : System.Collections.dasm - SortedDictionary`2:set_Item(__Canon,long):this
           1 ( 0.41% of base) : System.Data.Common.dasm - XPathNodePointer:MoveToFirstNamespace(int):bool:this
           2 ( 0.39% of base) : System.Collections.Immutable.dasm - ImmutableExtensions:GetCount(byref):int (7 methods)

Top method improvements (percentages):
         -13 (-7.18% of base) : System.Linq.dasm - ListPartition`1:TryGetElementAt(int,byref):__Canon:this
         -11 (-6.15% of base) : FSharp.Core.dasm - NonStructural@43-2:System.Collections.Generic.IComparer<'T>.Compare(__Canon,__Canon):int:this
          -9 (-5.73% of base) : System.Linq.dasm - ListPartition`1:TryGetFirst(byref):__Canon:this
        -222 (-5.66% of base) : System.Private.CoreLib.dasm - EventProvider:WriteEvent(byref,long,long,long,ref):bool:this
          -9 (-5.56% of base) : System.Linq.Parallel.dasm - Lookup`2:Contains(__Canon):bool:this
         -11 (-5.47% of base) : FSharp.Core.dasm - NonStructural@43-3:System.Collections.Generic.IComparer<'T>.Compare(__Canon,__Canon):int:this
         -11 (-5.00% of base) : System.Net.Http.dasm - ObjectCollection`1:Contains(__Canon):bool:this
         -13 (-4.96% of base) : System.Linq.Parallel.dasm - Lookup`2:get_Item(__Canon):IEnumerable`1:this
         -11 (-3.94% of base) : System.Net.Http.dasm - ObjectCollection`1:Remove(__Canon):bool:this
          -9 (-3.32% of base) : System.Collections.Immutable.dasm - HashBucket:TryGetValue(__Canon,Comparers,byref):bool:this
         -12 (-3.11% of base) : FSharp.Core.dasm - ValueOption:Flatten(FSharpValueOption`1):FSharpValueOption`1 (7 methods)
          -9 (-3.09% of base) : System.Collections.Immutable.dasm - HashBucket:TryGetKey(__Canon,Comparers,byref):bool:this
         -26 (-2.96% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - MemberSemanticModel:InAnonymousTypeInitializerInterior(VisualBasicSyntaxNode,int,byref):bool:this
          -2 (-2.17% of base) : System.Linq.Expressions.dasm - LambdaCompiler:EmitDefaultExpression(Expression):this
          -2 (-2.11% of base) : Microsoft.CodeAnalysis.dasm - OneOrMany`1:get_Item(int):__Canon:this
          -4 (-2.08% of base) : FSharp.Core.dasm - NonStructuralComparison:Compare$W(FSharpFunc`2,FSharpFunc`2,__Canon,__Canon):int
         -47 (-1.82% of base) : System.Configuration.ConfigurationManager.dasm - MgmtConfigurationRecord:GetConfigDeclarationUpdates(int):SectionUpdates:this
         -18 (-1.82% of base) : System.Private.CoreLib.dasm - ContinuationTaskFromResultTask`1:InnerInvoke():this (7 methods)
         -18 (-1.81% of base) : System.Private.CoreLib.dasm - MemoryExtensions:AsMemory(ArraySegment`1,int,int):Memory`1 (7 methods)
         -18 (-1.79% of base) : System.Private.CoreLib.dasm - ContinuationResultTaskFromResultTask`2:InnerInvoke():this (7 methods)

176 total methods with Code Size differences (125 improved, 51 regressed), 258682 unchanged.
```

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
