### PR TITLE
Support PortableThreadPool native event sinks on Mono.

### PR DESCRIPTION
**Pull request by lateralusX**
https://github.com/dotnet/runtime/pull/47829 added support to write portable thread pool events directly to native runtime event sinks instead of going through managed event pipe interop since that cause a couple of unwanted side effects. The original PR only hooked up this infrastructure for CoreCLR and this PR implements the same abilities on MonoVM.

### CODE REVIEW

**Comment by lateralusX** [comment]
//CC @josalem, @sywhang

**Review by josalem — COMMENTED** [review]
I can't speak to the Mono changes, but the CoreCLR changes look good to me.

**Comment by lateralusX** [comment]
@lambdageek, OK?

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
@lateralusX lgtm.  I made an issue https://github.com/dotnet/runtime/issues/53607 for us to think about providing components a simple mechanism to register qcalls. Because the boilerplate to add a couple of icalls is a bit ridiculous.

**Pull request merged**
