### PR TITLE
Track last index in parameter marshalling

### PR DESCRIPTION
**Pull request by jtschuster**
Tracks the last index marshalled in the interop generators to ensure we don't cleanup any unmarshalled elements.

To determine if the `lastElementMarshalled` variable is used, we need to generate the cleanup stage, which can be expensive. We also could generate `_ = __param_lastIndexMarshalled` if there is no cleanup so that there is no warning for an unused variable, but we don't need to generate the cleanup stage twice.

We'll need more testing around the ComInterfaceGenerator, but I would like to get this into preview 6 for LibraryImportGenerator.

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]
As long as we don't generate invalid code for GeneratedComInterface, I'm supportive of getting this in for P6

**Comment by jkoritzinsky** [comment]
It looks like the unit tests all timed out in CI, but only for the LibraryImportGenerator unit tests. Very odd.

**Comment by jtschuster** [comment]
Looks like this probably does hurt perf significantly enough to cause some timeouts. I made https://github.com/dotnet/runtime/pull/88060 as an alternative.

**Comment by jtschuster** [comment]
https://github.com/dotnet/runtime/pull/88060 was accepted instead of this one

**Pull request closed without merging**
