### PR TITLE
Revert "Use llvm-objcopy on Linux x64 (#48444)"

### PR DESCRIPTION
**Pull request by jkotas**
This reverts commit ba50840433578d97de4ad8bb9d2a2b45e7455b30.

### CODE REVIEW

**Review by mangod9 — APPROVED** [review]

**Comment by sebastienros** [comment]
Would there be any doubt and someone can build the impacted files for me then I can verify the change.

**Comment by jkotas** [comment]
I will check the build artifacts once the build is green.

**Comment by jkotas** [comment]
cc @am11

**Comment by am11** [comment]
It is one of those things, you can't verify locally. e.g. before and after my commit, as well as the master branch, the size of libcoreclr.so on linux-x64 is 6.8M.

My guess is that we need to check the dotnet/installer build if we are really using llvm v9x or higher there for linux-x64.

**Comment by jkotas** [comment]
> It is one of those things, you can't verify locally. e.g. before and after my commit, as well as the master branch, the size of libcoreclr.so on linux-x64 is 6.8M.

You should be able to use the docker image used by the CI to exactly replicate what the build does:

mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-20201227183837-5fe0e50

I do not think that the problem is in dotnet/installer. I see that the dotnet/runtime build is not stripping the .so as before. Let me know if you have are not able to replicate the problem using the docker image above.

**Comment by jkotas** [comment]
I have built current main and this PR on mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-20201227183837-5fe0e50 docker image locally to verify that the problem can be reproduced:

Current main:
```
[root@3ffd9021d6f4 runtime]# cd /runtime/artifacts/bin/coreclr/Linux.x64.Release
[root@3ffd9021d6f4 Linux.x64.Release]# ls -la libcoreclr*
-rwxr-xr-x 1 root root  99492216 Mar  3 23:36 libcoreclr.so
-rw-r--r-- 1 root root 101239976 Mar  3 23:36 libcoreclr.so.dbg
```

With this revert:
```
[root@53b120e70d17 Linux.x64.Release]# ls -la libcoreclr*
-rwxr-xr-x 1 root root  7183624 Mar  3 23:38 libcoreclr.so
-rw-r--r-- 1 root root 94112016 Mar  3 23:38 libcoreclr.so.dbg
```

**Comment by am11** [comment]
I haven't tried on that centos docker. I used Ubuntu 20.04 VM for my findings.
```sh
$ du -b artifacts/bin/coreclr/Linux.x64.Release/libcoreclr.so
7046336 artifacts/bin/coreclr/Linux.x64.Release/libcoreclr.so
```

**Comment by jkotas** [comment]
@am11 Could you please take a look and re-submit the change with the fix for the size regression? Thank you!

**Pull request merged**
