### PR TITLE
Activate Quic Alpn Narrowing Test

### LINKED ISSUE #86701: QUIC Listener ConnectionOptionsCallback ALPN Narrowing Down Failure with Wrong Error Code
This is a tracking issue for `msquic` next release to activate `Listener_AlpnNarrowingDown_Failure` test inside of `QuicListenerTests`.

**Description:**
While we're narrowing down ALPN negotiation list with `ConnectionOptionsCallback`, Quic is renegotiating ALPN with the Client.
```c#
                ApplicationProtocols = new List<SslApplicationProtocol>()
                {
                    new SslApplicationProtocol("foo"),
                    new SslApplicationProtocol("bar"),
                    new SslApplicationProtocol("test"),
                },
                ConnectionOptionsCallback = (_, _, _) =>
                {
                    // Narrowing down alpn list to more specific.
                    var options = CreateQuicServerOptions();
                    options.ServerAuthenticationOptions.ApplicationProtocols = new()
                    {
                        new SslApplicationProtocol("bar"),
                        new SslApplicationProtocol("test"),
                    };
                    return ValueTask.FromResult(options);
                }
```

In that case, if Quic can't find any matching ALPN between the client and server, the connection is failing with `QUIC_STATUS_INTERNAL_ERROR` instead of `QUIC_STATUS_ALPN_NEG_FAILURE`.

This is coming from `msquic` and has already been fixed in both the `main` and `release/2.2` branches. (https://github.com/microsoft/msquic/pull/3647 and https://github.com/microsoft/msquic/pull/3649)

### PR DESCRIPTION
**Pull request by liveans**
Fixes #86701

Looks like `QuicListener.AcceptConnectionAsync` doesn't throw `AuthenticationException` when the client's alpn is not present on the initial alpn list.

### CODE REVIEW

**Comment by wfurt** [comment]
> Fixes #86701
> 
> Looks like `QuicListener.AcceptConnectionAsync` doesn't throw `AuthenticationException` when the client's alpn is not present on the initial alpn list.

Should it? Perhaps we should get feedback from @manickap

**Comment by ManickaP** [comment]
@liveans, `AcceptConnectionAsync` never returns in this case, doesn't it? NEW_CONNECTION event never comes for this connection, right? If so, then it makes sense, as MsQuic refuses the connection underneath and never gives it to us. This also happens with refused connections due to server overload.
In that case, this is fine as it is.

**Comment by liveans** [comment]
> @liveans Ahmet Ibrahim Aksoy FTE, `AcceptConnectionAsync` never returns in this case, doesn't it? NEW_CONNECTION event never comes for this connection, right? If so, then it makes sense, as MsQuic refuses the connection underneath and never gives it to us. This also happens with refused connections due to server overload. In that case, this is fine as it is.

Yes, that's the case. `AcceptConnectionAsync` never returns in that case.

**Review by ManickaP — APPROVED** [review]
Small suggestion, otherwise LGTM, thanks!

**Comment by liveans** [comment]
CI failures unrelated

**Pull request merged**
