### PR TITLE
Fold typeof(vt) relop typeof(_Canon)

### PR DESCRIPTION
**Pull request by EgorBo**
Testing PR to close https://github.com/dotnet/runtime/issues/79081

```csharp
public static bool Test<T>()
{
    Type k = typeof(T);
    return k == typeof(sbyte) || k == typeof(byte);
}
```
Was:
```asm
G_M37465_IG01:              ;; offset=0000H
       4883EC28             sub      rsp, 40
       48894C2420           mov      qword ptr [rsp+20H], rcx
G_M37465_IG02:              ;; offset=0009H
       488B4938             mov      rcx, qword ptr [rcx+38H]
       488B09               mov      rcx, qword ptr [rcx]
       E8AB49505F           call     CORINFO_HELP_TYPEHANDLE_TO_RUNTIMETYPE
       48BA205359CFE3010000 mov      rdx, 0x1E3CF595320      ; 'System.SByte'
       483BC2               cmp      rax, rdx
       7418                 je       SHORT G_M37465_IG05
G_M37465_IG03:              ;; offset=0024H
       48BAE00059CFE3010000 mov      rdx, 0x1E3CF5900E0      ; 'System.Byte'
       483BC2               cmp      rax, rdx
       0F94C0               sete     al
       0FB6C0               movzx    rax, al
G_M37465_IG04:              ;; offset=0037H
       4883C428             add      rsp, 40
       C3                   ret      
G_M37465_IG05:              ;; offset=003CH
       B801000000           mov      eax, 1
G_M37465_IG06:              ;; offset=0041H
       4883C428             add      rsp, 40
       C3                   ret      
; Total bytes of code 70
```
Now:
```asm
G_M58438_IG01:              ;; offset=0000H
       4883EC28             sub      rsp, 40
G_M58438_IG02:              ;; offset=0004H
       33C0                 xor      eax, eax
G_M58438_IG03:              ;; offset=0006H
       4883C428             add      rsp, 40
       C3                   ret      
; Total bytes of code 11
```

### CODE REVIEW

**Comment by EgorBo** [comment]
Almost no diffs - three methods affected across the BCL 😞 so not sure it worth the effort

**Comment by am11** [comment]
I was thinking it would be a small change in importer somewhere around these conditions https://github.com/dotnet/runtime/pull/71778/files#diff-af8a9db9bb28767adad71c804c3a62d35b4e34ffbc64362b7138ab703ef964cc from `op1 is typeof call` to `op1 is typeof or op1 is a variable to typeof call`. Didn't knew that it will require a runtime change to achieve that.

**Comment by EgorBo** [comment]
> I was thinking it would be a small change in importer somewhere around these conditions https://github.com/dotnet/runtime/pull/71778/files#diff-af8a9db9bb28767adad71c804c3a62d35b4e34ffbc64362b7138ab703ef964cc from `op1 is typeof call` to `op1 is typeof call || op1 is a variable to typeof call`. Didn't knew that it will require a runtime change to achieve that.

it's not that easy when it comes to variables unfortunately, most optimizations in importer/morph only work with direct patterns so when you spill something to a local you have less chances to detect anything there. So here I decided to handle more general case in VN phase.

**Comment by am11** [comment]
Ah, I see. We had a similar issue with vectors (https://github.com/dotnet/runtime/issues/64879) which was fixed with fwdsub. Is this something fwdsub can handle in generalized manner too?

> Almost no diffs - three methods affected across the BCL

In BCL, we are using `typeof(X) == typeof(Y)` pattern, but roslyn sometimes stores LHS in a variable when compiling switch expressions. e.g. in this  [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGADAAQY4B0ASgK4B2ALgJYC2MlAwhKwA7MAbGFADKwgG7MwMAM4BuQoQDE9WgIEBDYENIATZjK1DCGAMzkspToQDehUg9IB6J6QBUpADKyZAFQAWGvQ4pEG6Xj4BQZaB4jCkABQaAqwQMowAlKTMujBMUsmkAJKe9o4ujmGkvFAQurTS2bn5YIWQuQDmeZRlDhUe3jJ+gfTmVYPDQSiksfFJKWmZTXksrQLFnokwCNK8jKQAZtCkjP4wvc6uDsAQHbQypKrqYGdgANbZ9BFDUfQoWVUanUGvEcisCut2jAuvQADQXfrfSb0ACsMw0D1O8XozAOjAAnqQZPimBoELDDhABG8HhA4lATmdPoxhPQYIwHrBIKx2PRwsxGAirnpaPFGBBshyiQI2GyhhT8ez0ZimQB3aAyeJQmGKAiOUgAbQAsuz/HUinwBAkTadzZaAPJ7ZgQegySgAQQ6HVgQ2YcSK9BlOPoHQyAF0LmZyDgkKQblSkb8cAAeXwAaRg+IAfAl05nSEI8RS84SoMwOv5Mhc7Hr9Y5cYkCbwYBADrmM/isgBeLsnfHN1sJYD4lkZLIYADsiWHo4SEGAACsYGBMoX9snpyOYBk54vl5kyxXGApa3XsgdG/2W22S93e03rwkZDPt+Op0+Xzv50uVxk16QNw/Lcvz3X9D0rE8zwcBsEgfQdb1IHs+wHNt7jNKBMjfRI0OgTJdx/VcYDxADsJkdC8O/fcMnA48Ln1GC4JvDs72Qx8yNwsdyHfdiMJAgi/yI9dEh4ijQIPcsILo+sL1gq94OYxD7zk1DmCYTjJ2w1TRP4/9ANoLS+KomjIKghjlPbTMWMYhIDKwmy1PwqjdMSAzHLAiTaNPOszJQizO0U1jBzUF1Qzs4KQ0M39nIScLQzc8SjxMs8fMfBCkOsgQQvU99Moi+KBOIwDcriyj3MSqSHA0g5kk1JLSAAX11fVjVNO1eCtG0zV0C12sdFgXTdT1vR8P0YADINVNDCMvKjChY3jdYJl+LBUw7HMSwLQTiw7UgaIyCrEKzQKmMsolVQFF4DprKC6wAfVIVUzi+ay0qU3zP0OzdZ1KwjCq+7d8po+EvJu+7HryY6/Ks8zn2Az6gO+sSCqEhGAZ+6iPOBm79TBp7IdeyGcN4+Gie0pzBJImKRMihLKyx7GHFxiGXoU9KYfI7sjqfDn8ui6nAcxg6cYevGWdOtnfP0tSSdc9HoqlsmyrpoXHCZ57zIJ6yDPh2Wkei3X+KBlXGZF5mNdZt7H1iznsOKmnkcp62BaPemGbV/GLchu34bt3mKaKrLneVkGoPursjuqgRNQO+qTwuFrbW6y1rVapPeqdAaPS9H0ZFG8bVMm8NI3MOa4wgBMlpGUxVszdadrXbb8z26sDt8K9SA+S35Msur6Jkzuu7bT87M/P2/qHYCg88m6YIHyHYdHOyF7RvX/eE0f0eMg7Z4C6zSey0ieblteqaPpGt5D6D+939mOKXs+dJP/nN483vpMSOe99srjNIc4/x4VvbC+M9r4S0fN/DS9lFa/RRgbIyr9t6gMHjFO2YVfb/xRk7F+5VL7ng/jfXyqCf4JHQavcepDDYINwVVGqMA6qNQIPHTqbUOqpx6gIPqzpXRZ2Gr6f0gYC4RWmvqWaMYy4V0iCMFANdsx+U2kWUgG1m64PDh7U6MhzqMEurg66DNFHt32ODZ6BDHwfVURPRGj9x4b3PoLXB+o27NhOKbYxYDBzLxtqje2fMbGUJdsbfRTjDGiwCoTamJNn5kMwZEvxwc9GBLFC45xbi2zhPMTE8m48MlK0YK7bGjjElGOScgwBMs/5RMdnAnJeSboFOcUU/YKSoGeKqTAymrSMb+PsY4OpwTmYmKCt7cxWCKl6QofArp8TelJMacgoZXNxlRRPos2muSAlhwjrQmOccvIJy6uwlOid2GcMzkNHOecBHBimsXaM81y6LUkUEFEMi675gboonayibqqNyNVNQjAoZnQuv4K6ASXzw18ZklGkLqkBOXvDDxY8UaIuwXEvRpMIkPyhY7bJqyalQREgirFSysnErxQEhWZToEOz0h0o23ToJMB1uUqxsCWUTLRQzWKJMVk0ttoHVFayGUFhCj7AVozEi8vpfEjZhwtm4NjoQeqQA) sample, `LessThan4` (which is equivalent to `LessThan3`) and `LessThan5` are missed by optimization due to local. We are not using C# pattern matching too extensively in the BCL, so it's not a surprise we don't find more differences in this particular data set.

**Pull request closed without merging**
