### PR TITLE
Re-enable tests on mono interpreter

### PR DESCRIPTION
**Pull request by BrzVlad**

### CODE REVIEW

**Comment by BrzVlad** [comment]
https://github.com/dotnet/runtime/issues/48929. Not getting any failures locally.

**Review by stephentoub — APPROVED** [review]

**Comment by eerhardt** [comment]
`Build Browser wasm Release AllSubsets_Mono` leg seems to be failing.

https://helix.dot.net/api/2019-06-17/jobs/40537448-8ced-480b-905c-65499826aff2/workitems/Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests/console

```
[14:59:14] fail: [FAIL] Microsoft.Extensions.DependencyInjection.Specification.LamarDependencyInjectionSpecificationTests.SafelyDisposeNestedProviderReferences
[14:59:14] info: System.PlatformNotSupportedException : Cannot wait on monitors on this runtime.
[14:59:14] info:    at System.Threading.Monitor.ObjWait(Int32 millisecondsTimeout, Object obj)
[14:59:14] info:    at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
[14:59:14] info:    at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[14:59:14] info:    at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[14:59:14] info:    at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[14:59:14] info:    at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[14:59:14] info:    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[14:59:14] info:    at System.Threading.Tasks.Task.Wait()
[14:59:14] info:    at System.Threading.Tasks.TaskReplicator.Replica.Wait()
[14:59:14] info:    at System.Threading.Tasks.TaskReplicator.Run[RangeWorker](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
[14:59:14] info:    at System.Threading.Tasks.Parallel.ForWorker[Object](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
[14:59:14] info:    at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
[14:59:14] info:    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, DiagnosticBag diagnostics, CancellationToken cancellationToken)
[14:59:14] info:    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
[14:59:14] info:    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileMethods(CommonPEModuleBuilder moduleBuilder, Boolean emittingPdb, Boolean emitMetadataOnly, Boolean emitTestCoverageData, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
[14:59:14] info:    at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream metadataPEStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, CompilationTestData testData, CancellationToken cancellationToken)
[14:59:14] info:    at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, Stream sourceLinkStream, IEnumerable`1 embeddedTexts, Stream metadataPEStream, CancellationToken cancellationToken)
[14:59:14] info:    at LamarCompiler.AssemblyGenerator.Generate(String code)
[14:59:14] info:    at LamarCompiler.GeneratedAssembly.CompileAll(IServiceVariableSource services)
[14:59:14] info:    at Lamar.IoC.Instances.GeneratedInstance.buildResolver(Scope scope)
[14:59:14] info:    at Lamar.IoC.Instances.GeneratedInstance.ToResolver(Scope topScope)
[14:59:14] info:    at Lamar.IoC.Instances.ConstructorInstance.ToResolver(Scope topScope)
[14:59:14] info:    at Lamar.ServiceGraph.FindResolver(Type serviceType)
[14:59:14] info:    at Lamar.IoC.Scope.TryGetInstance(Type serviceType)
[14:59:14] info:    at Lamar.IoC.Scope.GetService(Type serviceType)
[14:59:14] info:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[ClassWithNestedReferencesToProvider](IServiceProvider provider)
[14:59:14] info:    at Microsoft.Extensions.DependencyInjection.Specification.DependencyInjectionSpecificationTests.SafelyDisposeNestedProviderReferences()
[14:59:14] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by BrzVlad** [comment]
`
15:02:45] info: === TEST EXECUTION SUMMARY ===
[15:02:45] info: Total: 664, Errors: 0, Failed: 41, Skipped: 0, Time: 4.91835s
`

@lewing All these tests fail on browser with cannot wait on monitors error. Therefore I just disabled the entire suite on wasm. Is this ok  ?

**Review by lewing — APPROVED** [review]
I'd rather do it this way but looks fine

**Pull request merged**
