### PR TITLE
Disable System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_async test on Browser wasm

### LINKED ISSUE #40886: wasm test failure: System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_async
Filed on mono/wasm (`net5.0-Browser-Release-wasm-Mono_Release-Ubuntu.1804.Amd64.Open`)  in #40841:
https://dev.azure.com/dnceng/public/_build/results?buildId=772623&view=ms.vss-test-web.build-test-results-tab&runId=24126412&paneView=debug

With `PlatformNotSupportedException: Cannot wait on monitors on this runtime.`

Currently I'm rerunning the tests, but since FileSystem and System.Private.Corelib doesn't have a dependency on System.Net.Primitives, I don't think it can be related to my PR.

### PR DESCRIPTION
**Pull request by MaximLipnin**
The `System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_async` test sometimes (flaky?) fails in CI on browser wasm (according to https://github.com/dotnet/runtime/issues/40886) with `PlatformNotSupportedException: Cannot wait on monitors on this runtime.`
In this case we are used to marking the failing test with platform detection for the threading feature.

Closes https://github.com/dotnet/runtime/issues/40886

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by steveisok** [comment]
Do we have a sense of why it's flaky?

**Comment by MaximLipnin** [comment]
> Do we have a sense of why it's flaky?

Tried to found out in which conditions it could fail but I got it only once - it was during the first run on clean build. Other times I didn't manage to reproduce it.

**Comment by MaximLipnin** [comment]
OSX/iOS lanes fail with https://github.com/dotnet/runtime/issues/41006

**Comment by danmosemsft** [comment]
Merging as this is sufficiently validated and is breaking other PR validation jobs right now.

**Pull request merged**
