### PR TITLE
[HTTP/3] Revert msquic hack in stress tests

### PR DESCRIPTION
**Pull request by ManickaP**
Revert #84793

cc @antonfirsov

### CODE REVIEW

**Review by antonfirsov — APPROVED** [review]
Thanks!

To me it looks like the timeouts in the PR are very similar to the ones we see with the hack:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=311116&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=a923b061-8445-5c16-cd6e-848990587cb0

We also have #87938 which appeared recently. No idea whether it's related to the hack, I guess we'll know soon.

**Review by wfurt — APPROVED** [review]

**Comment by ManickaP** [comment]
This will probably get closed as this is not the culprit. Working on https://github.com/dotnet/runtime/issues/87957 instead.

**Comment by ManickaP** [comment]
Closing in favor of #87971

**Pull request closed without merging**
