### PR TITLE
JIT: Generalize `optSetPreheaderWeight`

### PR DESCRIPTION
**Pull request by jakobbotsch**
Old loop finding only recognized loops with one entering block, so the old logic here was based on there only being one entering edge to the newly added preheader. Also, it was assumed that block was a `BBJ_COND`.

Generalize the logic by summing up the contributions to the weight from all entering blocks. Avoid unnecessary checks on `BBJ_COND` by switching to use the general successor visitors instead.

We only consider the preheader to have a profile weight if the following conditions are true:
* The loop header has a profile weight
* All entering blocks have a profile weight
* The successors of all entering blocks have a profile weight (so that we can trust the computed taken/not taken ratio)

This also changes the calculation when there are no profile weights: the existing code inherited the weight from the previous entering block directly, which does not make much sense if that block has multiple successors. With this change we assume that the `prevEntering -> preheader` edge is taken with 1/N probability instead, where N is the number of successors of `prevEntering`.

Diffs expected as usual when profile weights are changed.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Example where I am seeing nonsensical preheader weights (in my case, leading to very odd perf score changes).

```
-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight   IBC  [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1      6 [000..009)-> BB03 ( cond )                     i IBC
BB02 [0006]  1       BB01                  0      0 [008..009)-> BB03 (always)                     i IBC rare hascall gcsafe q
BB03 [0007]  3       BB01,BB02,BB05        1      6 [008..038)-> BB05 ( cond )                     i IBC nullcheck bwd
BB04 [0002]  1       BB03                  1      6 [038..039)        (return)                     i IBC
BB05 [0003]  1       BB03                  0      0 [039..043)-> BB03 (always)                     i IBC rare hascall gcsafe bwd bwd-src
-----------------------------------------------------------------------------------------------------------------------------------------

***************  Natural loop graph
L00 header: BB03
  Members (2): [BB03..BB05]
  Entry: BB01 -> BB03; BB02 -> BB03
  Exit: BB03 -> BB04
  Back: BB05 -> BB03

New Basic Block BB06 [0009] created.
Created new preheader BB06 for L00
Setting edge weights for BB06 -> BB03 to [0 .. 6]
Entry edge BB01 -> BB03 becomes BB01 -> BB06
Setting edge weights for BB01 -> BB06 to [0 .. 6]
Entry edge BB02 -> BB03 becomes BB02 -> BB06
Setting edge weights for BB02 -> BB06 to [0 .. 0]
Identifying loops in DFS tree with following reverse post order:
RPO -> BB [pre, post]
00 -> BB01[0, 5]
01 -> BB02[1, 4]
02 -> BB06[2, 3]
03 -> BB03[3, 2]
04 -> BB04[5, 1]
05 -> BB05[4, 0]

BB05 -> BB03 is a backedge
BB03 is the header of a DFS loop with 1 back edges
Loop has 2 blocks
BB03 -> BB04 is an exit edge
BB06 -> BB03 is an entry edge
Added loop L00 with header BB03

Found 1 loops

***************  Natural loop graph
L00 header: BB03
  Members (2): [BB03..BB05]
  Entry: BB06 -> BB03
  Exit: BB03 -> BB04
  Back: BB05 -> BB03

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight   IBC  [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1      6 [000..009)-> BB06 ( cond )                     i IBC
BB02 [0006]  1       BB01                  0      0 [008..009)-> BB06 (always)                     i IBC rare hascall gcsafe q
BB06 [0009]  2       BB01,BB02            16.67     [008..???)-> BB03 (always)                     internal preheader q
BB03 [0007]  2       BB05,BB06             1      6 [008..038)-> BB04 ( cond )                     i IBC loophead nullcheck bwd
BB05 [0003]  1       BB03                  0      0 [039..043)-> BB03 (always)                     i IBC rare hascall gcsafe bwd bwd-src
BB04 [0002]  1       BB03                  1      6 [038..039)        (return)                     i IBC
-----------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by jakobbotsch** [comment]
Let me try to push a bit more on this PR. There were some somewhat large diffs, but seems like it's churn we need to take on principle.

**Comment by jakobbotsch** [comment]
With this PR the result looks more reasonable:
```diff
 ----------------------------------------------------------------------------------------------------------------------------------------------
 BBnum BBid ref try hnd preds           weight   IBC [IL range]   [jump]              [EH region]        [flags]
 ----------------------------------------------------------------------------------------------------------------------------------------------
 BB01 [0000]  1                             1      6 [000..009)-> BB06,BB02 ( cond )                     i IBC
 BB02 [0006]  1       BB01                  0      0 [008..009)-> BB06      (always)                     i IBC rare hascall gcsafe q
-BB06 [0009]  2       BB01,BB02            16.67     [008..???)-> BB03      (always)                     internal q
+BB06 [0009]  2       BB01,BB02             1      6 [008..???)-> BB03      (always)                     IBC internal q
 BB03 [0007]  2       BB05,BB06             1      6 [008..038)-> BB04,BB05 ( cond )                     i IBC loophead nullcheck bwd
 BB05 [0003]  1       BB03                  0      0 [039..043)-> BB03      (always)                     i IBC rare hascall gcsafe bwd bwd-src
 BB04 [0002]  1       BB03                  1      6 [038..039)             (return)                     i IBC
 ----------------------------------------------------------------------------------------------------------------------------------------------

```

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS 

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=544658&view=ms.vss-build-web.run-extensions-tab)

**Comment by jakobbotsch** [comment]
Ping @AndyAyersMS

**Review by AndyAyersMS — APPROVED** [review]
This will get a lot more straightforward with likelihoods.

**Pull request merged**
