### PR TITLE
Copy OpenSSL binaries when creating Android apps

### PR DESCRIPTION
**Pull request by fanyang-mono**
This PR could resolve some failures mentioned in https://github.com/dotnet/runtime/issues/44306

### CODE REVIEW

**Review by EgorBo — APPROVED** [review]

**Comment by akoeplinger** [comment]
None of the runtime tests hit the Crypto APIs so this shouldn't be needed.

**Comment by EgorBo** [comment]
> None of the runtime tests hit the Crypto APIs so this shouldn't be needed.

For some reasons some of them actually tried judging by logs.

**Comment by akoeplinger** [comment]
@EgorBo that would need to be a recent change then since the runtime tests were passing before and without openssl that would not be possible right?

I'm fine with getting this in btw if we understand that it's necessary.

**Comment by fanyang-mono** [comment]
> @EgorBo that would need to be a recent change then since the runtime tests were passing before and without openssl that would not be possible right?
> 
> I'm fine with getting this in btw if we understand that it's necessary.

@akoeplinger I had the same question. Why they used to pass without this change. But want to give it a try with this change to see if it would fix anything.

**Pull request merged**
