### PR TITLE
`explosed` -> `exposed`

### PR DESCRIPTION
**Pull request by ghost**
change(s) made include:

1. rectified the *word* `explosed` to `exposed`.

incentive: I hope no API *exploses* >~< (oui, oui!).

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
Thanks

**Comment by ophura** [comment]
I understand this is little/insignificant as a contribution...

however! it is an important step for me!
as I'd love to become an active contributor of the `dotnet/runtime` repository!
it's just a matter of lack of essential programming knowledge... but you'll see more from me!

keep an eye, and you'll see (I mean, I don't know if one can see without eyes lulz xd).

**Comment by danmoseley** [comment]
@ophura  you're welcome here. Maybe look at issues labeled good first issue.

**Comment by ophura** [comment]
arigato! >~<

**Review by danmoseley — APPROVED** [review]

**Comment by danmoseley** [comment]
@stephentoub  what's the process nowadays when there's validation failures that are unrelated?

**Comment by stephentoub** [comment]
> @stephentoub what's the process nowadays when there's validation failures that are unrelated?

If the build analysis leg is green, you can merge.

**Comment by danmoseley** [comment]
That's easy

**Comment by ophura** [comment]
yahooo! I made it in folks! xd
things are getting serious!

today I changed a letter, tomorrow however!
I just might revamp the whole thing xd

thankies for appreciation <3

**Pull request merged**
