### PR TITLE
Fix PAL_JitWriteProtect export on Linux

### PR DESCRIPTION
**Pull request by janvorli**
I have not realized that we actually export that symbol on Linux too and
that mscordac then have the dummy function missing. That breaks managed
debugging and SOS.

This change fixes the problem.

### CODE REVIEW

**Review by mikem8361 — APPROVED** [review]

**Comment by jkotas** [comment]
> that mscordac then have the dummy function missing.

Would it be better to define a dummy method for the DAC instead?

**Comment by mikem8361** [comment]
So unless I understand what you mean by dummy function that is what this change is doing. Making the an empty PAL_JitWriteProtect function for the non-MacOS arm64 platforms so the DAC export is always defined. This is for DBI which uses the PAL functions in the DAC.

**Comment by jkotas** [comment]
I meant to get rid of this function from src\coreclr\dlls\mscordac\mscordac_unixexports.src .

**Comment by jkotas** [comment]
This function is used in only 2 places now and both of those places have ifdef around them already. Can we add `&& !defined(DACCESS_COMPILE)` to those ifdefs?

**Comment by mikem8361** [comment]
So you are saying that neither the DAC or DBI use the ExecutableWriterHolder class that this function is called from? It seems like that is true now that I look.

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by janvorli** [comment]
With this change, mscordbi on is now missing the symbol - see the two OSX arm64 legs failing now:
```
2021-06-15T05:20:23.9841730Z [ 96%] Linking CXX shared library libmscordbi.dylib
2021-06-15T05:20:24.1970710Z Undefined symbols for architecture arm64:
2021-06-15T05:20:24.2050410Z   "_PAL_JitWriteProtect", referenced from:
2021-06-15T05:20:24.2152570Z       CordbProcess::AdjustBuffer(unsigned long, unsigned long, unsigned char*, unsigned char**, CordbProcess::AB_MODE, int*) in libcordbdi.a(process.cpp.o)
2021-06-15T05:20:24.2192220Z ld: symbol(s) not found for architecture arm64
2021-06-15T05:20:24.2294840Z clang: error: linker command failed with exit code 1 (use -v to see invocation)
2021-06-15T05:20:24.2396740Z make[2]: *** [dlls/mscordbi/libmscordbi.dylib] Error 1
2021-06-15T05:20:24.2498490Z make[1]: *** [dlls/mscordbi/CMakeFiles/mscordbi.dir/all] Error 2
```

**Comment by jkotas** [comment]
mscordbi is the out-of-proc debugger component. Does it actually need to flip the write protect permissions or is it just an accident that it calls it?

**Comment by janvorli** [comment]
I had to add it to fix failing managed debugger tests. Otherwise it fails in the call to `CORDbgInsertBreakpoint` from here:
https://github.com/dotnet/runtime/blob/9414d571355001d796e11c74588389dd7387d836/src/coreclr/debug/ee/controller.cpp#L1385
Here is the call stack at the failure:
```
  * frame #0: 0x000000010141c93c libcoreclr.dylib`DebuggerController::ApplyPatch(DebuggerControllerPatch*) [inlined] CORDbgSetInstruction(address=<unavailable>, instruction=-734134272) at primitives.h:152:12 [opt]
    frame #1: 0x000000010141c93c libcoreclr.dylib`DebuggerController::ApplyPatch(DebuggerControllerPatch*) [inlined] CORDbgInsertBreakpoint(address=<unavailable>) at arm_primitives.h:56 [opt]
    frame #2: 0x000000010141c93c libcoreclr.dylib`DebuggerController::ApplyPatch(patch=0x000000016000dca0) at controller.cpp:1385 [opt]
    frame #3: 0x000000010141cd64 libcoreclr.dylib`DebuggerController::ActivatePatch(patch=<unavailable>) at controller.cpp:1738:9 [opt] [artificial]
    frame #4: 0x000000010141d188 libcoreclr.dylib`DebuggerController::AddBindAndActivatePatchForMethodDesc(this=0x0000000157708230, fd=0x0000000280dd01b8, dji=0x000000015770c970, nativeOffset=0, kind=PATCH_KIND_IL_SLAVE, fp=(m_sp = 0x0000000000000000), pAppDomain=0x0000000000000000) at controller.cpp:2112:9 [opt]
    frame #5: 0x000000010141cf44 libcoreclr.dylib`DebuggerController::AddBindAndActivateILSlavePatch(this=0x0000000157708230, master=<unavailable>, dji=0x000000015770c970) at controller.cpp:1869:13 [opt]
    frame #6: 0x0000000101428c84 libcoreclr.dylib`Debugger::MapAndBindFunctionPatches(DebuggerJitInfo*, MethodDesc*, unsigned char const*) [inlined] Debugger::MapPatchToDJI(this=<unavailable>, dcp=0x000000016000dc00, djiTo=0x000000015770c970) at debugger.cpp:5035:34 [opt]
    frame #7: 0x0000000101428c14 libcoreclr.dylib`Debugger::MapAndBindFunctionPatches(this=<unavailable>, djiNew=0x000000015770c970, fd=<unavailable>, addrOfCode="\xfd{\xbb\xa9\xf3S\U00000001\xa9\xf5[\U00000002\xa9\xf7c\U00000003\xa9\xf9k\U00000004\xa9\xfd\U00000003") at debugger.cpp:4943 [opt]
    frame #8: 0x0000000101428724 libcoreclr.dylib`Debugger::JITComplete(this=0x0000000157706e90, nativeCodeVersion=NativeCodeVersion @ 0x000000016f02e180, newAddress=10751396304) at debugger.cpp:2527:14 [opt]
    frame #9: 0x00000001011daaa0 libcoreclr.dylib`UnsafeJitFunction(config=0x000000016f02e7f0, ILHeader=0x000000016f02e500, flags=CORJIT_FLAGS @ 0x000000016f02e4a0, pSizeOfCode=0x000000016f02e62c) at jitinterface.cpp:13299:44 [opt]
    frame #10: 0x000000010120cf78 libcoreclr.dylib`MethodDesc::JitCompileCodeLocked(this=0x0000000280dd01b8, pConfig=0x000000016f02e7f0, pEntry=0x000000015770cfd0, pSizeOfCode=0x000000016f02e62c, pFlags=0x000000016f02e618) at prestub.cpp:1045:17 [opt]
    frame #11: 0x000000010120cc18 libcoreclr.dylib`MethodDesc::JitCompileCodeLockedEventWrapper(this=0x0000000280dd01b8, pConfig=0x000000016f02e7f0, pEntry=0x000000015770cfd0) at prestub.cpp:914:17 [opt]
    frame #12: 0x000000010120c2f8 libcoreclr.dylib`MethodDesc::JitCompileCode(this=0x0000000280dd01b8, pConfig=0x000000016f02e7f0) at prestub.cpp:854:20 [opt]
    frame #13: 0x000000010120bd3c libcoreclr.dylib`MethodDesc::PrepareILBasedCode(this=0x0000000280dd01b8, pConfig=0x000000016f02e7f0) at prestub.cpp:433:17 [opt]
    frame #14: 0x000000010118ee58 libcoreclr.dylib`CodeVersionManager::PublishVersionableCodeIfNecessary(this=0x000000016000c5f8, pMethodDesc=0x0000000280dd01b8, callerGCMode=Coop, doBackpatchRef=0x000000016f02e8e8, doFullBackpatchRef=<unavailable>) at codeversion.cpp:1701:34 [opt]
    frame #15: 0x000000010120eafc libcoreclr.dylib`MethodDesc::DoPrestub(this=0x0000000280dd01b8, pDispatchingMT=0x0000000000000000, callerGCMode=Coop) at prestub.cpp:2207:42 [opt]
    frame #16: 0x000000010120e5e0 libcoreclr.dylib`::PreStubWorker(pTransitionBlock=<unavailable>, pMD=0x0000000280dd01b8) at prestub.cpp:2033:29 [opt]
    frame #17: 0x00000001013e7f90 libcoreclr.dylib`ThePreStub + 80
    frame #18: 0x00000001013e8a88 libcoreclr.dylib`CallDescrWorkerInternal + 132
    frame #19: 0x0000000101267920 libcoreclr.dylib`MethodDescCallSite::CallTargetWorker(unsigned long const*, unsigned long*, int) at callhelpers.cpp:67:5 [opt]
    frame #20: 0x00000001012678d0 libcoreclr.dylib`MethodDescCallSite::CallTargetWorker(this=0x000000016f02ee60, pArguments=0x000000016f02ef88, pReturnValue=0x0000000000000000, cbReturnValue=0) at callhelpers.cpp:543 [opt]
    frame #21: 0x0000000101192598 libcoreclr.dylib`CorHost2::CreateAppDomainWithManager(char16_t const*, unsigned int, char16_t const*, char16_t const*, int, char16_t const**, char16_t const**, unsigned int*) [inlined] MethodDescCallSite::Call(this=<unavailable>, pArguments=<unavailable>) at callhelpers.h:458:9 [opt]
    frame #22: 0x0000000101192584 libcoreclr.dylib`CorHost2::CreateAppDomainWithManager(this=0x0000000157614150, wszFriendlyName=<unavailable>, dwFlags=<unavailable>, wszAppDomainManagerAssemblyName=<unavailable>, wszAppDomainManagerTypeName=<unavailable>, nProperties=4, pPropertyNames=0x0000000157612550, pPropertyValues=0x00000001576125b0, pAppDomainID=0x0000000100de0268) at corhost.cpp:627 [opt]
    frame #23: 0x000000010114dfec libcoreclr.dylib`::coreclr_initialize(exePath="/Users/janvorli/git/dotnet-diagnostictests/bin/OSX.arm64.Debug/runtimes/coreclr/corerun", appDomainFriendlyName=<unavailable>, propertyCount=<unavailable>, propertyKeys=<unavailable>, propertyValues=<unavailable>, hostHandle=0x0000000100de0270, domainId=<unavailable>) at unixinterface.cpp:254:16 [opt]
    frame #24: 0x0000000100dd7794 corerun`main + 7868
    frame #25: 0x0000000196f89450 libdyld.dylib`start + 4
```

**Comment by janvorli** [comment]
So we either have to exclude that holder (and similar one for the other architectures) for the mscordbi build or we have to create a clone of this method for the out-of-mscordbi usage and remove the holder from the one used by the mscordbi.

**Comment by janvorli** [comment]
Or stop including primitives.h from the dbi files - which seems to work, I am just testing it now.

**Comment by janvorli** [comment]
It seems that the simplest solution would be to add a dummy PAL_JitWriteProtect implementation to the mscordbi or introduce a new define to indicate mscordbi compilation (e.g. `DBI_COMPILE`). Forking the CORDbgInsertBreakpoint / CORDbgSetInstruction or would seem to be an ugly solution.

@jkotas, @mikem8361 please let me know which of the two solutions you'd prefer.

**Comment by janvorli** [comment]
FYI, the only thing that pulls that in in the mscordbi are the `CORDbgSetInstructionEx` and `CORDbgInsertBreakpointEx` calls below:
https://github.com/dotnet/runtime/blob/9414d571355001d796e11c74588389dd7387d836/src/coreclr/debug/di/process.cpp#L6750-L6763

**Comment by jkotas** [comment]
> new define to indicate mscordbi compilation (e.g. DBI_COMPILE)

This would be my choice

**Review by jkotas — APPROVED** [review]

**Pull request merged**
