### PR TITLE
Fix Create/StartActivity parentId nullability

### PR DESCRIPTION
**Pull request by halter73**
I assume this is okay given https://github.com/dotnet/aspnetcore/pull/41568/files#diff-f4b6e9bc19da99141d4427d88673ed12fdf3474082f571b027a583cb6959ca99R340.

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]
Do you mind submitting a doc PR or issue to track fixing the docs? Thanks for fixing it!

**Comment by halter73** [comment]
> Do you mind submitting a doc PR or issue to track fixing the docs?

@tarekgh Are you referring to https://github.com/dotnet/dotnet-api-docs/blob/bb1dba0405e7efcab3c07411966892a774e7027f/xml/System.Diagnostics/ActivitySource.xml#L157-L199 and the `StartActivity` equivalent? Or something else? I though the API docs were generated by a tool from the code and inline doc comments.

**Comment by carlossanlop** [comment]
> After the docs get ported the first time from the source, I am not sure if we are updating the docs with every change we make in the source.

That is correct, the automatic porting process is only done once, when the docs don't yet exist in MS Docs. After that, any further modifications need to be manually done directly in the dotnet-api-docs repo and in the triple slash comments. @halter73 @tarekgh

**Comment by halter73** [comment]
@carlossanlop That seems super likely to get out of sync and error-prone. Is there a plan to automate this in the future?

For now, is there at least a way to run the tool manually so I don't mess this up? The docs in the dotnet-api-docs are a lot more intricate than normal inline doc comments.

**Pull request merged**
