### PR TITLE
JIT: remove fallthrough limitations from redundant branch optimizer

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Now that `BBJ_COND` no longer has fallthrough semantics, remove a bunch of code that would limit redundant branch jump threading when one of the predecessors was fallthrough.

Contributes to #93020.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@amanasifkhalid PTAL
cc @dotnet/jit-contrib

**Comment by amanasifkhalid** [comment]
Ah, my email didn't refresh automatically, and I just opened #97724 to do the same thing. I'll close that PR in favor of yours.

**Review by amanasifkhalid — APPROVED** [review]
Since you're here, in `Compiler::optRedundantBranches()`, could you please rename the `bbNext` and `bbJump` locals? Maybe something like `bbFalse` and `bbTrue`...

Otherwise LGTM, thanks!

**Comment by AndyAyersMS** [comment]
> Since you're here, in `Compiler::optRedundantBranches()`, could you please rename the `bbNext` and `bbJump` locals? Maybe something like `bbFalse` and `bbTrue`...
> 
> Otherwise LGTM, thanks!

Done.

**Comment by AndyAyersMS** [comment]
TP impact on benchmarks_pgo is oddly high (0.15%ish) compared to everything else. Will have to dig in.

**Comment by AndyAyersMS** [comment]
Looking at TP impact, I'm puzzled.

runtime1 is my changes, merge-base at a102e88d3c3b8b9b71e8f4b529372f0a0431790d, runtime2 is at the merge-base.

Main TP script and lab show:
```
[19:11:52] Running throughput diff of d:\spmi\mch\b8a05f18-503e-47e4-9193-931c50b151d1.windows.x64\benchmarks.run_pgo.windows.x64.checked.mch
[19:13:08] Total instructions executed by base: 120166191724
[19:13:08] Total instructions executed by diff: 120391609407
[19:13:08] Total instructions executed delta: 225417683 (0.19% of base)
```
but running locally in detail mode, via
```
d:\spmi\pintools\1.0\windows\pin.exe -t c:\tools\single_inscount.dll -m c:\repos\runtime1\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\clrjit.dll -trace -- c:\repos\runtime1\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\superpmi.exe c:\repos\runtime1\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\clrjit.dll d:\spmi\mch\b8a05f18-503e-47e4-9193-931c50b151d1.windows.x64\benchmarks.run_pgo.windows.x64.checked.mch 2> tp_diff.txt

d:\spmi\pintools\1.0\windows\pin.exe -t c:\tools\single_inscount.dll -m c:\repos\runtime2\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\clrjit.dll -trace -- c:\repos\runtime2\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\superpmi.exe c:\repos\runtime2\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\clrjit.dll d:\spmi\mch\b8a05f18-503e-47e4-9193-931c50b151d1.windows.x64\benchmarks.run_pgo.windows.x64.checked.mch 2> tp_base.txt
```
and then
```
dotnet run --project c:\repos\jitutils\src\jit-tp-analyze\jit-tp-analyze.csproj -b tp_base.txt -d tp_diff.txt > tp_compare.txt
```
gives a different picture:
```
Base: 120621811972, Diff: 120661330905, +0.0328%

With extra cycles where you'd expect

?GetRelatedRelop@ValueNumStore@@QEAAIIW4VN_RELATION_KIND@1@@Z                       : 25271176 : +2.78%  : 6.11%  : +0.0210%
?VNForFunc@ValueNumStore@@QEAAIW4var_types@@W4VNFunc@@II@Z                          : 22472587 : +1.77%  : 5.43%  : +0.0186%
?optRelopImpliesRelop@Compiler@@QEAAXPEAURelopImplicationInfo@@@Z                   : 16986701 : +2.91%  : 4.10%  : +0.0141%
?optGlobalAssertionIsEqualOrNotEqualZero@Compiler@@QEAAGAEBQEA_KPEAUGenTree@@@Z     : 16634693 : +14.00% : 4.02%  : +0.0138%
```
@dotnet/jit-contrib anyone ever seen things like this? Am tempted to write this off and just merge.

**Comment by jakobbotsch** [comment]
The asm diff shows 79 misses in benchmarks.run_pgo in the diff. The way you are running the detailed TP measurement on the base and diff means that the diff is naturally going to execute fewer instructions since those 79 contexts won't be fully accounted for. I think @SingleAccretion has some scripts to create a proper .mcl with the non-missing contexts. You can also try the -details arg to the superpmi.exe invocation under pin. It will produce a .csv that can tell what the most diverging contexts are, so running the detailed pin tool on some of those only might be insightful.

**Comment by AndyAyersMS** [comment]
> The asm diff shows 79 misses in benchmarks.run_pgo in the diff. The way you are running the detailed TP measurement on the base and diff means that the diff is naturally going to execute fewer instructions since those 79 contexts won't be fully accounted for.

Thanks, that makes sense. Let me try stripping those.

**Comment by AndyAyersMS** [comment]
Looks like that was indeed the issue; would not have expected 79/104,000 or so would matter that much.
```
Base: 120164431596, Diff: 120390010019, +0.1877%

?GetRelatedRelop@ValueNumStore@@QEAAIIW4VN_RELATION_KIND@1@@Z                     : 25267332 : +2.79%  : 9.40%  : +0.0210%
?VNForFunc@ValueNumStore@@QEAAIW4var_types@@W4VNFunc@@II@Z                        : 22469239 : +1.78%  : 8.36%  : +0.0187%
?optRelopImpliesRelop@Compiler@@QEAAXPEAURelopImplicationInfo@@@Z                 : 16983564 : +2.92%  : 6.32%  : +0.0141%
?optGlobalAssertionIsEqualOrNotEqualZero@Compiler@@QEAAGAEBQEA_KPEAUGenTree@@@Z   : 16885426 : +14.29% : 6.28%  : +0.0141%
?PerBlockAnalysis@LiveVarAnalysis@@AEAA_NPEAUBasicBlock@@_N1@Z                    : 11381389 : +0.58%  : 4.24%  : +0.0095%
`Compiler::optReachable'::`12'::<lambda_1>::operator()                            : 10323087 : +5.69%  : 3.84%  : +0.0086%
?optAddAssertion@Compiler@@QEAAGPEAUAssertionDsc@1@@Z                             : 10315855 : +1.70%  : 3.84%  : +0.0086%
BasicBlock::VisitAllSuccs<`Compiler::optReachable'::`12'::<lambda_1> >            : 9676270  : +5.80%  : 3.60%  : +0.0081%
```
Will look into the most afflicted contexts, could be there are some outliers.

**Comment by AndyAyersMS** [comment]
Since jump threading now happens more often, we see more cases where a BBJ_COND loses all its predecessors. The main driver loop was retrying RBO on any BBJ_COND where we changed flow, but if we've removed all preds, this is pointless.

There is a bit more TP to be had by actually deleting (or perhaps just nuking the IR) in these blocks. I recall deleting blocks in RBO lead to problems but it might be worth revisiting. I see Assertion Prop at least spending some cycles looking at trees in dead blocks and possibly polluting the assertion table with irrelevant stuff. But I will probably save that for a follow-up.

**Comment by AndyAyersMS** [comment]
OSX build hosts unable to access runtime repo.

**Comment by AndyAyersMS** [comment]
Looked a bit into some of the bigger size regressions since I generally wouldn't expect to see them with more RBO. It appears it is a late flow opt deciding to duplicate more branches (again likely from fewer joints). We might need to revisit this heuristic too.

**Comment by AndyAyersMS** [comment]
> Since jump threading now happens more often, we see more cases where a BBJ_COND loses all its predecessors. The main driver loop was retrying RBO on any BBJ_COND where we changed flow, but if we've removed all preds, this is pointless.

That cut worst-case TP roughly in half. Going to call this good.

**Pull request merged**
