### PR TITLE
Mitigation for a GC Stress race after an inline pinvoke

### LINKED ISSUE #37236: Test failure: Interop\\COM\\NativeClients\\Events\\Events.cmd
failed in job: [runtime-coreclr gcstress0x3-gcstress0xc 20200531.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=665656&view=ms.vss-test-web.build-test-results-tab&runId=20632370&resultId=103507&paneView=debug)

Error message
~~~

Return code: 1
Raw output file: C:\h\w\A7A808D4\w\AD6E08F2\e\Interop\COM\Reports\Interop.COM\NativeClients\Events\Events.output.txt
Raw output:
BEGIN EXECUTION
Copying 'C:\h\w\A7A808D4\p\CoreShim.dll'...
 1 file(s) copied.
 "C:\h\w\A7A808D4\p\corerun.exe" Events.dll 
Searching for exe to launch in C:\h\w\A7A808D4\w\AD6E08F2\e\Interop\COM\NativeClients\Events...
Launching 'C:\h\w\A7A808D4\w\AD6E08F2\e\Interop\COM\NativeClients\Events\COMClientEvents.exe'...

Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A7A808D4\p
> C:\h\w\A7A808D4\w\AD6E08F2\e\Interop\COM\NativeClients\Events\Events.cmd
Expected: True
Actual: False


Stack trace
   at Interop_COM._NativeClients_Events_Events_._NativeClients_Events_Events_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\Interop.COM\Interop.COM.XUnitWrapper.cs:line 916
~~~

### PR DESCRIPTION
**Pull request by AndyAyersMS**
In the post-call part of a pinvoke inline call frame, it's not safe
to start a stress mode GC in the window between checking
`g_TrapReturningThreads` and the call to `CORINFO_HELP_STOP_FOR_GC`.

The call instruction is already getting special treatement, but there may
be other instructions between the check and call. Instead of trying
to pattern match them all, suppress GC stress if `g_TrapReturningThreads`
is true, the thread is in cooperative mode, and there's an active inline
call frame.

Closes #37236.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jkotas PTAL

With this change, the test case from #37236 has now run ~5000 times without a failure; without the fix I was able to repro after less than 1000 tries. Will keep it going a bit further.

**Comment by AndyAyersMS** [comment]
GC count looks comparable before/after fix:
```
;; Before
GC Counts: Gen0=16546, Gen1=16557, Gen2=1367
GC Counts: Gen0=16389, Gen1=16400, Gen2=1459
GC Counts: Gen0=16477, Gen1=16488, Gen2=1764

;; After
GC Counts: Gen0=16564, Gen1=16575, Gen2=1329
GC Counts: Gen0=16505, Gen1=16516, Gen2=1238
GC Counts: Gen0=16455, Gen1=16466, Gen2=1678
```

**Comment by jkotas** [comment]
You can try to delete all special-casing of `JIT_RareDisableHelper` from gccover.cpp. This check should be able to handle all situations that the special-casing was for. If we find situations that this check is not able to handle, it means the fix is incomplete.

**Review by jkotas — APPROVED** [review]

**Comment by jkotas** [comment]
Thank you!

**Comment by AndyAyersMS** [comment]
> You can try to delete all special-casing of JIT_RareDisableHelper

I was thinking the same thing. Will try it as a follow-up.

**Pull request merged**
