### PR TITLE
Fix incremental XxHash32/XxHash64

### LINKED ISSUE #69184: XxHash incremental versions not processing stripe when filling holdback exactly.
### Description

When using the incremental Append() version of XxHash32 or XxHash64, if there's already data in the holdback and the new data fills the stripe exactly it won't be processed.

https://github.com/dotnet/runtime/blob/5b5bd46c03c86f8545f2c4c8628ac25d875210fe/src/libraries/System.IO.Hashing/src/System/IO/Hashing/XxHash32.cs#L76

Needs to be `>=` and the same thing for XxHash64. (A similar issue in the one-shot implementation was fixed in #61881).

### Reproduction Steps

```using System;
using System.IO.Hashing;
using System.Text;
using System.Linq;

var hasher32 = new XxHash32();

hasher32.Append(Encoding.ASCII.GetBytes("01234567"));
hasher32.Append(Encoding.ASCII.GetBytes("01234567"));

var incremental32 = hasher32.GetHashAndReset();
var oneShot32 = XxHash32.Hash(Encoding.ASCII.GetBytes("0123456701234567"));

if(incremental32.SequenceEqual(oneShot32))
	Console.WriteLine($"Incremental: {Convert.ToHexString(incremental32)} and one-shot: {Convert.ToHexString(oneShot32)} are the same");
else
	Console.WriteLine($"Incremental: {Convert.ToHexString(incremental32)} and one-shot: {Convert.ToHexString(oneShot32)} are NOT the same");

var hasher64 = new XxHash64();

hasher64.Append(Encoding.ASCII.GetBytes("0123456789ABCDEF"));
hasher64.Append(Encoding.ASCII.GetBytes("0123456789ABCDEF"));

var incremental64 = hasher64.GetHashAndReset();
var oneShot64 = XxHash64.Hash(Encoding.ASCII.GetBytes("0123456789ABCDEF0123456789ABCDEF"));

if(incremental64.SequenceEqual(oneShot64))
	Console.WriteLine($"Incremental: {Convert.ToHexString(incremental64)} and one-shot: {Convert.ToHexString(oneShot64)} are the same");
else
	Console.WriteLine($"Incremental: {Convert.ToHexString(incremental64)} and one-shot: {Convert.ToHexString(oneShot64)} are NOT the same");
```

### Expected behavior

Incremental: 69A61AA0 and one-shot: 69A61AA0 are the same
Incremental: 51ACEF020CD423B1 and one-shot: 51ACEF020CD423B1 are the same

### Actual behavior

Incremental: A27EE241 and one-shot: 69A61AA0 are NOT the same
Incremental: ADD172CD28DDE0EB and one-shot: 51ACEF020CD423B1 are NOT the same

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

I'll make a PR.

### PR DESCRIPTION
**Pull request by froce**
Fix #69184

### CODE REVIEW

**Comment by TYoungSL** [comment]
👍

**Comment by bartonjs** [comment]
Certainly when I wrote this I felt like I had hit all of the boundary cases, but clearly missed at least two.

Do we feel like this is the last one?

**Comment by froce** [comment]
There also appears to be an issue with _length overflow, when incrementally hashing >= 2GB of input.
For XxHash32 results will still match the spec, while having negative _length internally.
XxHash64 should incorporate the full 64-bit length, so for total input length >= 2^32 the results are wrong.

**Review by stephentoub — APPROVED** [review]

**Comment by GrabYourPitchforks** [comment]
I'll send a followup PR with the fixed 64-bit logic.

**Pull request merged**
