### PR TITLE
Add NativeAOT checked leg

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
This is the same as the release leg, but checked runtime and on fewer queues (only Win x64 and Linux arm64).

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
If I'm reading this right, we're taking a codepath on Windows Nano that we should not be taking on Nano.

Going to debug this in the CI since I have no clue how to easily get a Nano environment.

```
Unhandled Exception: System.Diagnostics.DebugProvider+DebugAssertException: SetEnvironmentVariable failed: 0
   at System.Diagnostics.DebugProvider.Fail(String, String) + 0x36
   at System.Diagnostics.Debug.Fail(String, String) + 0x21
   at System.Environment.SetEnvironmentVariableFromRegistry(String variable, String value, Boolean fromMachine) + 0x184
   at System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target) + 0x6c
   at System.Tests.GetEnvironmentVariable.EnumerateEnvironmentVariables(EnvironmentVariableTarget target) + 0x148
```

**Pull request merged**
