### PR TITLE
[LoongArch64] Synchronize with PR#102592.

### PR DESCRIPTION
**Pull request by LuckyXu-HF**
[LoongArch64] Synchronize with PR#102592.
* Fix the build error for LA64.

### CODE REVIEW

**Comment by LuckyXu-HF** [comment]
Synchronize with [PR#102592](https://github.com/dotnet/runtime/pull/102592) to fix the build error for LA64.

@shushanhf @kunalspathak  could you please review this PR? Thank you.

**Review by shushanhf — APPROVED** [review]
LGTM
Thanks

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by kunalspathak** [comment]
/ba-g failure is related to https://github.com/dotnet/runtime/issues/102719 which is already fixed.

**Pull request merged**
