### PR TITLE
[release/7.0] Fix encoding problem when publishing

### PR DESCRIPTION
**Pull request by ilonatommy**
Backport of #82833 to release/7.0

Fixes https://github.com/dotnet/runtime/issues/78953.

## Customer Impact

Customers had a problem with publishing applications that were located in a path with Unicode chars. It was because Windows’s scripts do not support UTF-8 by default. Now we added that feature + tests.

## Testing

The PR introduced changes in WasmBuildTests and they are passing.

## Risk

Low, it broadens the accepted range of codes for Windows to `UTF-8`.

### CODE REVIEW

**Comment by thaystg** [comment]
The failures on CI are not connected.

**Review by maraf — APPROVED** [review]

**Comment by carlossanlop** [comment]
I'm retargeting this PR to the new `release/7.0-staging` branch, which is the one that we will use from now on for servicing fixes. 

Repo maintainers will now be allowed to merge their own servicing PR as long as it meets the requirements:

- It is approved by Tactics (signaled by adding the `Servicing-approved` label).
- It's signed-off by an area owner.
- The CI is green, or the failures are investigated as unrelated.
- And if the PR touches an OOB package, the necessary OOB authoring changes are added.

The new process is described here: [runtime/docs/project/library-servicing.md](https://github.com/dotnet/runtime/blob/release/7.0-staging/docs/project/library-servicing.md).

The infra team will be actively monitoring servicing PRs to ensure all requirements are met and to help with any issues.

Let me know if you have any questions.

**Comment by carlossanlop** [comment]
Reminder: April 10th is the last day to merge backport PRs to ensure they get included in the May Release. PR owners are now in charge of merging their own PRs.

**Comment by ilonatommy** [comment]
Timezones failures on ios are not connected. Merging.

**Pull request merged**
