### PR TITLE
Fix a couple of Windows createdump issues

### PR DESCRIPTION
**Pull request by mikem8361**
Fix createdump crash triggering on x86 runtime

The new crash triggering code in excep.cpp was in a #ifndef CROSSGEN_COMPILE
block that isn't defined on the x86 Windows build. Move the code out that
conditional block.

Fix ERROR_PARTIAL_COPY retry. MiniDumpWriteDump sets the last error to the HRESULT instead of win32 error code

### CODE REVIEW

**Comment by jkotas** [comment]
> The new crash triggering code in excep.cpp was in a #ifndef CROSSGEN_COMPILE
block that isn't defined on the x86 Windows build. Move the code out that
conditional block.

Are you doing this to enable the dump support for crossgen.exe too? I do not see why this was needed.

**Comment by mikem8361** [comment]
No, not for crossgen.exe but the Windows x86 coreclr.dll didn't have my crash dump code in it.  It only worked if I moved it out of the that block.

**Comment by mikem8361** [comment]
CROSSGEN_COMPILE seems to be defined for x86 builds and not for x64 builds of coreclr.dll.

**Comment by jkotas** [comment]
Do you expect the dump support to be enabled for crossgen.exe ? 

You have moved the initialization from out of `#ifndef CROSSGEN_COMPILE` here: https://github.com/dotnet/runtime/pull/35820/files#diff-ad28a73dc6492a177af41d2a3b6e7e6fR647 . The initialization was under `#ifndef CROSSGEN_COMPILE` before.

I do not see a problem with it enabled for crossgen.exe, but it would be useful to validate that it does what it supposed to do for crossgen.exe.

**Comment by jkotas** [comment]
> CROSSGEN_COMPILE seems to be defined for x86 builds and not for x64 builds of coreclr.dll.

I do not think that's correct. `CROSSGEN_COMPILE` is never defined when building coreclr.dll.

Note that the same files are built with `CROSSGEN_COMPILE` defined when building crossgen.exe.

**Comment by mikem8361** [comment]
I not sure what I was thinking. The x86 problem was just where I initialized the my code. I backed out most of the changes except the initialization.

**Review by jkotas — APPROVED** [review]

**Review by noahfalk — COMMENTED** [review]
Its already merged, but looks fine to me too : )

**Pull request merged**
