### PR TITLE
catch DirectoryOperationException to check Negotiate as for LdapExcep…

### LINKED ISSUE #51222: PrincipalContext, ValidateCredentials
### Description

We were authenticate to our domain via simple:
`new PrincipalContext(ContextType.Domain).ValidateCredentials(name, password);`

But since probably a domain configuration/security harden, this is not working anymore, instead a `DirectoryOperationException` occure with errorcode 0x80131500.
english error text is: The server cannot handle directory requests.
german error text is: Der Server kann Verzeichnisanforderungen nicht verarbeiten.

After looking into code I found that in class `CredentialValidator` in method `Validate` for `SimpleBind` only the `LdapException` has been catched. Changing the internal member via debugger from `Simple` to `Negotiate`, let the `ValidateDomainCredentials` run through without issue.

### Solution

Catch additional to `LdapException` also `DirectoryOperationException` in `CredentialValidator` in method `Validate`.

### Question
In case this is here is fixed, where can I find a nuget package which works with .NET Framework 4.8, since the regular package have not build for it inside.

### PR DESCRIPTION
**Pull request by trivalik**
resolves https://github.com/dotnet/runtime/issues/51222

### CODE REVIEW

**Comment by jeffhandley** [comment]
@dotnet/area-system-directoryservices It looks like @joperezr showed support for this change in the backing issue (#51222), so I'm not sure what is needed to approve this.

@trivalik Can you share how you tested this?

**Comment by trivalik** [comment]
I tested it against our domain. I am not aware what domain settings was required to break it. Since nobody here could really help me with this issue.

My workaround right now was to catch the exception by myself and force it by providing the Negotiate parameter.

So I guess some simple encryption was disabled in domain.

**Comment by jeffhandley** [comment]
Thanks, @trivalik!

@dotnet/area-system-directoryservices I'm inclined to approved this and merge it in for Preview 6 (after ensuring the build failures are unrelated); any objections?

**Review by jeffhandley — APPROVED** [review]

**Comment by jeffhandley** [comment]
I can't think of how the new build errors could be related to this change, but I'm reluctant to hit the merge button since I can't find any outstanding issues with the error.

> ##[error]eng/testing/tests.mobile.targets(175,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Precompiling failed for /Users/runner/work/1/s/artifacts/bin/iOS.Simulator.Aot.Test/net6.0-Release/iossimulator-x64/publish/System.Private.CoreLib.dll: Error: Process returned non-zero exit code:

**Comment by jeffhandley** [comment]
Ah, I might have found the corresponding issue, and the details there indicate that the error messages are not reproducible.

https://github.com/dotnet/runtime/issues/53735

**Review by buyaa-n — COMMENTED** [review]
LGTM

**Pull request merged**
