### PR TITLE
Stop running runtime tests on Android arm64 in main build

### PR DESCRIPTION
**Pull request by fanyang-mono**
Temporarily disable runtime tests running on Android arm64. Will re-enable once https://github.com/dotnet/xharness/issues/663 is resolved.

cc: @greenEkatherine @premun

### CODE REVIEW

**Comment by krwq** [comment]
@fanyang-mono can you please point to the issuein dotnet/runtime related to this PR? We need that to track re-enabling the test once the external issue gets fixed

**Comment by SamMonoRT** [comment]
fyi - @premun @greenEkatherine

**Review by SamMonoRT — APPROVED** [review]
Create a tracking issue in dotnet\runtime as a reminder to enable the tests again once external issue is fixed

**Comment by premun** [comment]
We are looking in the code and there's no installation timeouts. Furthermore it seems to be happening in the same set of apps such as `baseservices.mono` (for some it happens more, for some less). I also pulled Kusto logs and it is not tied to a specific machine - there's no set of machines that would cause this.

What's happening that we know about is that the Xunit runner calls XHarness to install the app, that finishes immediately. Then, after 3 hours, Xunit runner calls XHarness to run the app which starts running and then the Helix work item times out and the process is killed. We don't know yet what happens in those 3 hours.

I am not convinced this is actually infrastructural issue but there's no "external issue" that is being worked on that would fix this at the moment. Might be in the way Xunit runner calls things, might be somewhere in the Helix SDK but I think it needs active investigation. We will dig more with @fanyang-mono.

**Pull request merged**
