### PR TITLE
Remove enable drawing on unix switch

### PR DESCRIPTION
**Pull request by safern**
As we announced on: https://github.com/dotnet/designs/blob/f9d006073b7a019bd2021e99c66516447f7fb1a6/accepted/2021/system-drawing-win-only/system-drawing-win-only.md this is removing support for the runtime config switch to use System.Drawing.Common on non Windows platforms.

I didn't remove the code due to time constraints as we need this in Preview 1 and the code removal is a big refactor and change, so I rather have this like that to meet the goal of removing support on P1 and then remove the code on a subsequent PR.

This will cause a PlatformNotSupportedException when Libicups or Libgdiplus are needed, same as in .NET 6 but without the config switch to disable it.

### CODE REVIEW

**Comment by danmoseley** [comment]
If you want the minimal change why not just force EnableUnixSupport to off?

**Comment by safern** [comment]
That'd be an option. I was just trying to refactor that piece of code which was simple enough and meanwhile kept the change small.

I don't mind going that route though.

**Comment by danmoseley** [comment]
@safern that's what I'd recommend given it's incredibly easy to verify it's correct and you presumably want to merge today. But I've no objection to this (if perhaps someone else reviews)

**Comment by safern** [comment]
Thanks, @danmoseley, I've updated it to the minimal possible changes 😄

**Review by danmoseley — APPROVED** [review]
lgtm!

**Comment by safern** [comment]
Test failure is: https://github.com/dotnet/runtime/issues/64117

**Comment by teo-tsirpanis** [comment]
We should close [all issues with `area-System.Drawing` and either `os-linux` or `os-mac-os-x`](https://github.com/dotnet/runtime/issues?q=is%3Aopen+label%3Aarea-System.Drawing+label%3Aos-linux%2Cos-mac-os-x).

**Comment by safern** [comment]
Thanks, @teo-tsirpanis for raising that. I didn't mention it on the PR, it was on my plans after removing the code, which I see you are working on, and thank you for that.

**Comment by ericstj** [comment]
Breaking change doc is https://github.com/dotnet/docs/issues/33653

**Pull request merged**
