### PR TITLE
Importer forward substitution

### PR DESCRIPTION
**Pull request by MichalPetryka**
Adds a simple, single-def only, substitution for locals for Importer intrinsics.

TP and memory impact will be the most important things to check with this.

Currently only enabled for `typeof` checking intrinsic to test codegen and TP.

Codegen for:
```cs
        public static bool Test()
        {
            Type t = typeof(int);
            Helpers.NoInline();
            return t.IsValueType;
        }
```

Before:
```asm
G_M000_IG01:                ;; offset=0x0000
       4883EC28             sub      rsp, 40
 
G_M000_IG02:                ;; offset=0x0004
       FF150E131D00         call     [DisasmoPlayground.Helpers:NoInline()]
       48B90809C6245D010000 mov      rcx, 0x15D24C60908
       3909                 cmp      dword ptr [rcx], ecx
 
G_M000_IG03:                ;; offset=0x0016
       4883C428             add      rsp, 40
       FF25B070EEFF         tail.jmp [System.RuntimeType:IsValueTypeImpl():bool:this]
```

After:
```asm
G_M46022_IG01:  ;; offset=0x0000
       4883EC28             sub      rsp, 40
						;; size=4 bbWeight=1 PerfScore 0.25
G_M46022_IG02:  ;; offset=0x0004
       FF15DE307E00         call     [DisasmoPlayground.Helpers:NoInline()]
       B801000000           mov      eax, 1
						;; size=11 bbWeight=1 PerfScore 3.25
G_M46022_IG03:  ;; offset=0x000F
       4883C428             add      rsp, 40
       C3                   ret      
						;; size=5 bbWeight=1 PerfScore 1.25
```

Part of a 2nd attempt at #85197.

### CODE REVIEW

**Comment by MichalPetryka** [comment]
@MihuBot

**Comment by AndyAyersMS** [comment]
You will still need to prove that the use(s) happen after the def, which may not be easy in the importer.

Generally the importer works in a kind of reverse postorder, so it's likely that you would see defs before uses, but when there are cycles this may not work out.

You could perhaps build the dfs tree and ask if the def is a dfs ancestor of the use (and so happens before). But I am not 100% confident the dfs query will be accurate before EH canons, which happen later So you might need to limit this to defs and uses that are not in handler or filter regions.

Also you may need to watch out for reimportation; this are rare but can happen. For instance if the def block is reimported but the use is not, then the tree referred to in your cache will be the wrong one.

The other option is to try and enhance normal forward sub to be somewhat more aggressive for single-def locals with easily substitutable values (eg invariants like constants) -- currently we are cautions for two reasons:
1. we have to search for the uses which can be costly
2. we have to run interference checks which can be costly

For invariant nodes (2) is no longer a concern as the cannot interfere or be interfered with. You might be able to leave breadcrumbs so that (1) is only done when we have an invariant node, and then run forward sub in RPO and keep a map like you keep now so as we run across the uses we can check if the def is available and substitute it.

Note morph running in RPO effectively does this already (via cross-block AP) so I'm also curious what phase ordering issues you are solving here... we will get this eventually and perhaps the fix is to just replay some of the importer opts in morph once we've done this propagation there.

**Comment by MichalPetryka** [comment]
> You will still need to prove that the use(s) happen after the def, which may not be easy in the importer.

Are statements not imported in order of execution in a single basic block? The current code relies on that being the case (and is restricted to assignments in the same BB cause of that). I know that basic blocks aren't imported in order but I assumed statements are.

> Also you may need to watch out for reimportation; this are rare but can happen. For instance if the def block is reimported but the use is not, then the tree referred to in your cache will be the wrong one.

Does that also affect code limited to a single BB like here?

> The other option is to try and enhance normal forward sub to be somewhat more aggressive

Like I said, this was originally a part of the ftn ptr/delegate non PGO inlining and since inlining can't be done after importer, I need to handle it here for that. For why that needs it: Roslyn is really annoying and decides to spill ftn ptrs and delegates to locals before calling them in a lot of cases, without such substitution the inlining would catch almost nothing, at least they should all happen to be in the same BB.

**Comment by AndyAyersMS** [comment]
> Does that also affect code limited to a single BB like here?

Ah, this restriction wasn't obvious to me from the code, I guess I see how you're accomplishing that now. I think you could make this clearer, the name "local version" doesn't indicate to me that this is tied to a specific block somehow.

I'm still concerned that it may be possible to get things wrong; it isn't obvious to me that the importer will always create stores and load trees in execution order, so that when creating a load it knows the most recently created store will provide the value.

> Like I said, this was originally a part of the ftn ptr/delegate non PGO inlining and since inlining can't be done after importer, I need to handle it here for that.

There are quite few phases that run after importation and before inlining, so ths transformation doesn't have to happen during importation. Perhaps it would be better to simply detect this opportunity during importation (setting a flag on call, block, or globally as needed) and then during inlining if the flag is set walk back a little ways searching for a recent def. Or if the flag is set, run a custom forward sub pass (that does not rely on liveness) before inlining.

**Pull request closed without merging**
