### PR TITLE
Make it possible to eliminate branches guarded by IsEnum

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
We use this check in CoreLib and currently it includes some unreachable code with a big closure.

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Comment by MichalPetryka** [comment]
Does handling the internal `IsActualEnum` here too make sense?

**Comment by MichalStrehovsky** [comment]
> Does handling the internal `IsActualEnum` here too make sense?

This only helps things like `typeof(T).IsEnum`. It doesn't do anything for when we have a System.Type from who-knows-where. If we use IsActualEnum on `typeof(T)` anywhere, we should just switch it to IsEnum.

**Comment by Sergio0694** [comment]
Wondering if this could also give us some size savings in CsWinRT. Eg. we have a few branches on this there ([example](https://github.com/microsoft/CsWinRT/blob/1ed334cce33fd04ab56babb80c27494823d722ab/src/WinRT.Runtime/Marshalers.cs#L2134-L2147)):

image

**Comment by MichalStrehovsky** [comment]
> Wondering if this could also give us some size savings in CsWinRT. Eg. we have a few branches on this there ([example](https://github.com/microsoft/CsWinRT/blob/1ed334cce33fd04ab56babb80c27494823d722ab/src/WinRT.Runtime/Marshalers.cs#L2134-L2147)):

Yes, that would probably help here.

I'll merge this then. I wasn't fully convinced we really want this without the rest. Despite the impression I'm giving here, I don't particularly like we do this IL rewriting.

# Size statistics

Pull request dotnet/runtime#100399

| Project | Size before | Size after | Difference |
|---------|-------------|------------|------------|
| avalonia.app-linux | [ 24496560 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474400003) | [ 24492464 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474399735) | -4096 |
| avalonia.app-windows | [ 22036480 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474400741) | [ 22031360 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474401598) | -5120 |
| hello-linux | [ 1377040 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474399257) | [ 1348240 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474399000) | -28800 |
| hello-minimal-linux | [ 1110696 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474398891) | [ 1085992 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474398968) | -24704 |
| hello-minimal-windows | [ 885248 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474399785) | [ 864256 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474400252) | -20992 |
| hello-windows | [ 1133056 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474400096) | [ 1109504 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474400171) | -23552 |
| kestrel-minimal-linux | [ 5772000 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474399234) | [ 5767904 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474399149) | -4096 |
| kestrel-minimal-windows | [ 5072384 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474400138) | [ 5070848 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474400345) | -1536 |
| reflection-linux | [ 2294656 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474399158) | [ 2294656 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474398987) | 0 |
| reflection-windows | [ 1944576 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474400036) | [ 1944064 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474400380) | -512 |
| webapiaot-linux | [ 10249144 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474399429) | [ 10228632 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474399282) | -20512 |
| webapiaot-windows | [ 9206272 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474400447) | [ 9188352 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/8958727410/artifacts/1474400658) | -17920 |

**Pull request merged**
