### PR TITLE
[release/9.0] Treat -rtm as stable sdk version band

### PR DESCRIPTION
**Pull request by lewing**
See https://github.com/dotnet/sdk/pull/43554

### CODE REVIEW

**Comment by lewing** [comment]
There may be more changes needed to fix wbt here

**Comment by carlossanlop** [comment]
The CI failures seem related.

**Review by carlossanlop — APPROVED** [review]
CI failures are gone. Tell-mode, adding servicing-approved.

Feel free to also wait for an area expert sign-off - @akoeplinger or @steveisok .

**Comment by lewing** [comment]
the remaining failures appear to be because https://github.com/dotnet/emsdk/pull/940 needs to merge first

**Comment by lewing** [comment]
> the remaining failures appear to be because [dotnet/emsdk#940](https://github.com/dotnet/emsdk/pull/940) needs to merge first

The flow is here, waiting for the build to complete.

**Comment by lewing** [comment]
Fixing this is required to unblock runtime flow into the sdk at https://github.com/dotnet/sdk/pull/43554

**Pull request merged**
