### PR TITLE
JIT: properly update trees in optOptimizeBoolsGcStress

### LINKED ISSUE #75944: Test failure baseservices\\exceptions\\unittests\\RecursiveThrowNew\\RecursiveThrowNew.cmd
Run: [runtime-coreclr jitstress 20220919.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=23120&view=ms.vss-test-web.build-test-results-tab&runId=468774&resultId=106563&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked jitstress2_tiered @ Windows.10.Arm64v8.Open
- baseservices\\exceptions\\unittests\\RecursiveThrowNew\\RecursiveThrowNew.cmd
...
coreclr OSX x64 Checked jitstress1 @ OSX.1200.Amd64.Open
- JIT/jit64/opt/cg/cgstress/CgStress1_do/CgStress1_do.sh
... 
coreclr OSX x64 Checked jitstress2 @ OSX.1200.Amd64.Open
- JIT/PGO/ProfileCastClassAndIsInst/ProfileCastClassAndIsInst/ProfileCastClassAndIsInst.sh
...
coreclr OSX x64 Checked jitstress1_tiered @ OSX.1200.Amd64.Open
- JIT/HardwareIntrinsics/X86/Sse2/AlignVector128_r/AlignVector128_r.sh
...
coreclr OSX arm64 Checked jitstress1_tiered @ OSX.1200.ARM64.Open
- JIT/HardwareIntrinsics/Arm/AdvSimd.Arm64/AdvSimd.Arm64_Part6_ro/AdvSimd.Arm64_Part6_ro.sh
...
coreclr OSX x64 Checked jitstress2_tiered @ OSX.1200.Amd64.Open
- JIT/HardwareIntrinsics/X86/Bmi2/Bmi2_r/Bmi2_r.sh
...
coreclr OSX arm64 Checked jitstress2_tiered @ OSX.1200.ARM64.Open
- baseservices/threading/generics/TimerCallback/thread14/thread14.sh
...
coreclr Linux x64 Checked zapdisable @ Ubuntu.1804.Amd64.Open
- JIT/opt/OSR/largefuncletframe/largefuncletframe.sh
...
coreclr Linux x64 Checked jitstress2_tiered @ Ubuntu.1804.Amd64.Open
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh
...
coreclr windows arm64 Checked jitstress2 @ Windows.10.Arm64v8.Open
- JIT\\Regression\\VS-ia64-JIT\\V1.2-M02\\b28158\\b28158\\b28158.cmd
...
coreclr Linux x64 Checked jitstress2 @ Ubuntu.1804.Amd64.Open
- JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.sh
...
coreclr Linux x64 Checked jitstress1_tiered @ Ubuntu.1804.Amd64.Open
- JIT/jit64/opt/cse/HugeField1/HugeField1.sh
...
coreclr windows x64 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
...
coreclr Linux x64 Checked jitstress1 @ Ubuntu.1804.Amd64.Open
- JIT/Performance/CodeQuality/Bytemark/Bytemark/Bytemark.sh
...
coreclr windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
- JIT/Performance/CodeQuality/Bytemark/Bytemark/Bytemark.sh
...
coreclr windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
- JIT\\Directed\\nullabletypes\\Desktop\\nullcomparaison_do\\nullcomparaison_do.cmd
...
coreclr windows x64 Checked jitstress2 @ Windows.10.Amd64.Open
- baseservices\\threading\\generics\\WaitCallback\\thread16\\thread16.cmd
...
coreclr OSX arm64 Checked jitstress1 @ OSX.1200.ARM64.Open
- JIT/CodeGenBringUpTests/Swap_do/Swap_do.sh
...
coreclr windows arm64 Checked jitstress1_tiered @ Windows.10.Arm64v8.Open
- JIT\\jit64\\hfa\\main\\testC\\hfa_nf2C_d\\hfa_nf2C_d.cmd
...
coreclr windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT\\Regression\\CLR-x86-JIT\\V1-M09.5-PDC\\b10894\\b10894\\b10894.cmd
...
coreclr Linux arm64 Checked zapdisable @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/opt/OSR/largefuncletframe/largefuncletframe.sh
...
coreclr Linux arm Checked zapdisable @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/opt/OSR/largefuncletframe/largefuncletframe.sh
...
coreclr windows x86 Checked zapdisable @ Windows.10.Amd64.Open
- JIT\\opt\\OSR\\largefuncletframe\\largefuncletframe.cmd
...
coreclr Linux arm64 Checked jitstress1_tiered @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh
...
coreclr Linux arm64 Checked jitstress1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh
...
coreclr windows arm64 Checked jitstress1 @ Windows.10.Arm64v8.Open
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
...
coreclr Linux arm64 Checked jitstress2_tiered @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/jit64/opt/cse/hugeexpr1/hugeexpr1.sh
...
coreclr Linux arm Checked jitstress1_tiered @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh
...
coreclr Linux arm64 Checked jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/jit64/opt/cse/hugeexpr1/hugeexpr1.sh
...
coreclr windows x64 Checked jitstress1_tiered @ Windows.10.Amd64.Open
- JIT\\Regression\\CLR-x86-JIT\\V1-M12-Beta2\\b84916\\b84916\\b84916.cmd
...
coreclr Linux arm Checked jitstress1 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh
...
coreclr OSX arm64 Checked jitstress2 @ OSX.1200.ARM64.Open
- Loader/classloader/generics/Instantiation/Recursion/Struct_ImplementMscorlibGenInterface/Struct_ImplementMscorlibGenInterface.sh
...
coreclr Linux arm Checked jitstress2_tiered @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/jit64/opt/cse/HugeField2/HugeField2.sh
...
coreclr Linux arm Checked jitstress2 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/b28158/b28158.sh
...
coreclr windows x64 Checked jitstress2_tiered @ Windows.10.Amd64.Open
- JIT\\HardwareIntrinsics\\X86\\Avx1\\Avx_r\\Avx_r.cmd
...
coreclr windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open
- JIT\\HardwareIntrinsics\\X86\\Sse3\\Sse3_ro\\Sse3_ro.cmd
...
```
**Error message:**
```
Assert failure(PID 16272 [0x00003f90], Thread: 7324 [0x1c9c]): Assertion failed 'false && "found use of a node that is not in the LIR sequence"' in 'System.AppContext:TryGetSwitch(System.String,byref):bool' during 'Rationalize IR' (IL size 97; hash 0x1d5a13fc; Tier1)

File: D:\a\_work\1\s\src\coreclr\jit\lir.cpp Line: 1622
Image: D:\h\w\AC3C097A\p\corerun.exe
Return code:      1
Raw output file:      D:\h\w\AC3C097A\w\A51409FF\uploads\Reports\baseservices.exceptions\unittests\RecursiveThrowNew\RecursiveThrowNew.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\AC3C097A\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  RecursiveThrowNew.dll
RecursiveThrowNew
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\AC3C097A\p
D:\h\w\AC3C097A\w\A51409FF\e\baseservices\exceptions\unittests\RecursiveThrowNew\RecursiveThrowNew.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._unittests_RecursiveThrowNew_RecursiveThrowNew_._unittests_RecursiveThrowNew_RecursiveThrowNew_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Under jit stress, `optOptimizeBoolsGcStress` will modify trees. Since this now happens in a phase that runs after `fgSetBlockOrder`, it must also recost and rethread the trees.

Fixes #75944.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

Likely also fixes #75942 and #75941.

**Comment by AndyAyersMS** [comment]
Still seeing some failures so will need to revise this.

**Comment by AndyAyersMS** [comment]
We are ending up with out of order threading, despite calling `fgSetStmtSeq`. Seems like we are recosting part of the tree after this call, which leads to operand swapping after threading. Since OOB runs later now than it once did, there is no need to recost.

**Comment by AndyAyersMS** [comment]
Not the first time I've been surprised by `gtPrepareCost`'s operand swapping, and probably not the last.

**Comment by AndyAyersMS** [comment]
Another segfault from msbuild during restore:
```
/__w/1/s/.dotnet/sdk/7.0.100-preview.7.22377.5/MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:/__w/1/s/artifacts/log/Checked/ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /nr:false /p:TreatWarningsAsErrors=true /p:ContinuousIntegrationBuild=true /p:__ToolsetLocationOutputFile=/__w/1/s/artifacts/toolset/8.0.0-beta.22469.1.txt /t:__WriteToolsetLocation /warnaserror /__w/1/s/artifacts/toolset/restore.proj
/__w/1/s/eng/common/tools.sh: line 474:   503 Segmentation fault      (core dumped) "$_InitializeBuildTool" "$@"
```

**Comment by AndyAyersMS** [comment]
Arm64 SPMI is lack of MCH, perhaps I'm too close to a GUID update or collections are broken?
```
No Azure Storage MCH files to download from 11b4ea58-c400-4c3d-995e-4e2f0676f6e8/linux/arm64/
```

**Comment by AndyAyersMS** [comment]
x86 failure is in `CriticalFinalizer` which is supposedly fixed by #75952.

**Comment by AndyAyersMS** [comment]
More critical finalizer failures in the jitstress legs. So far, no other failures there.

**Review by jakobbotsch — APPROVED** [review]

**Pull request merged**
