### PR TITLE
Fix CoreCLR stress pipelines that run libraries tests only

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes failures in runtime-coreclr libraries-* pipelines

### CODE REVIEW

**Review by jkoritzinsky — COMMENTED** [review]
/azp run runtime-coreclr libraries-jitstress

**Comment by jkotas** [comment]
I have seen "You must specify at least one target queue to send a job to helix. Use the HelixTargetQueues property or HelixTargetQueue items." error in some jobs, e.g. https://github.com/dotnet/runtime/pull/98858/checks?check_run_id=22732088742

Is this related?

**Comment by jkoritzinsky** [comment]
Looking at the error, that looks like more of a problem with specifying helix target queues. That would be more indicitive of a missing `helixQueuesTemplate:` argument to the platform-matrix template than the issue that this PR is fixing.

**Review by BruceForstall — APPROVED** [review]
LGTM

**Comment by jkoritzinsky** [comment]
Fixed the extra-platforms as well

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
@jkoritzinsky Looks like there's still a problem with the Helix correlation payload:

```
C:\h\w\9782089C\w\97C508A0\e>"C:\h\w\9782089C\p\dotnet.exe" exec --runtimeconfig Common.Tests.runtimeconfig.json --depsfile Common.Tests.deps.json xunit.console.dll Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
'"C:\h\w\9782089C\p\dotnet.exe"' is not recognized as an internal or external command,
operable program or batch file.
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=605856&view=results

(Not sure why the jobs aren't showing up in the "Checks" list above)

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
