### PR TITLE
Reenable poisoning test in non R2R jobs

### LINKED ISSUE #55062: a new poison test is failing in ci
Examples https://dev.azure.com/dnceng/public/_build/results?buildId=1216832&view=ms.vss-test-web.build-test-results-tab
added in https://github.com/dotnet/runtime/pull/54685

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fix #55062

### CODE REVIEW

**Comment by jakobbotsch** [comment]
This is disabled in R2R jobs due to #56148.

**Comment by jakobbotsch** [comment]
Tests looks like infra failures.

**Comment by sandreenko** [comment]
> This is disabled in R2R jobs due to #56148.

Was #56148 fixed?

**Comment by jakobbotsch** [comment]
> Was #56148 fixed?

No, that's why this PR keeps the test disabled in R2R jobs.

**Review by sandreenko — APPROVED** [review]

**Pull request merged**
