### PR TITLE
JIT: Always look for SIMD fields during promotion

### LINKED ISSUE #83749: Inefficient codegen with struct consisting of 2 SIMD vectors.
### Description

CoreCLR emits inefficient codegen when working with structs consisting of 2 SIMD vectors, for example custom structs with 2xVector128 or Vector512 on platforms without AVX512.

If you compare the codegen for methods A and B in the reproduction, you can notice the JIT spilling the custom structs instead of promoting them in B. The goal here would be to have B emit the same codegen as A does.
If you look at Memmove there, you'll notice that the JIT does not spill them, but introduces a lot of redundant adds and leas in the codegen.

[Reproduction](https://gist.github.com/MichalPetryka/ce7052f1f57832aa307bf1037278624b)

### Configuration

Windows x64 .Net 8 preview 2

### Regression?

Probably not, checked just stack spilling and it occurs on .Net 7

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fix #83749

### CODE REVIEW

**Review by tannergooding — APPROVED** [review]

**Comment by tannergooding** [comment]
@jakobbotsch, was there something blocking or preventing this from being merged?

**Comment by jakobbotsch** [comment]
@tannergooding There were some failures that I needed to figure out if were related or not.

**Comment by jakobbotsch** [comment]
The failing case is with `JitStressRegs=2`:
```scala
[11:07:52] ISSUE: <ASSERT> #411709 D:\a\_work\1\s\src\coreclr\jit\emit.h (1171) - Assertion failed 'reg == _idReg1' in 'JIT.HardwareIntrinsics.Arm._AdvSimd.SimpleTernaryOpTest__AbsoluteDifferenceAdd_Vector128_UInt32+TestStruct:Create():JIT.HardwareIntrinsics.Arm._AdvSimd.SimpleTernaryOpTest__AbsoluteDifferenceAdd_Vector128_UInt32+TestStruct' during 'Generate code' (IL size 208; hash 0xa860f440; FullOpts)
```

We have the following multireg tree that needs to be unspilled before a return:
```scala
N447 (  9,  6) [000090] m------N--z                   t90 =    LCL_VAR   struct<JIT.HardwareIntrinsics.Arm._AdvSimd.SimpleTernaryOpTest__AbsoluteDifferenceWideningUpperAndAdd_Vector128_UInt32+TestStruct, 48>(P) V00 loc0          NA
                                                            ▌    simd16 field V00._fld1 (fldOffset=0x0) -> V14 tmp10         (last use)
                                                            ▌    simd16 field V00._fld2 (fldOffset=0x10) -> V15 tmp11         (last use)
                                                            ▌    simd16 field V00._fld3 (fldOffset=0x20) -> V16 tmp12         d2 (last use) REG NA,d1,d2 $540
                                                            ┌──▌  t90    struct 
N449 ( 10,  7) [000091] -----------                         ▌  RETURN    struct REG NA $VN.Void
```
The local is marked as `GTF_SPILLED` (z) flag, and the spill flags indicate that the first field needs to be unspilled. But the first field has no register assignment to unspill into.

**Comment by jakobbotsch** [comment]
#88380 should fix the above issue.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib 

Failures are known according to build analysis.

Some very minor [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=327998&view=ms.vss-build-web.run-extensions-tab) outside tests. arm64 has a handful in libraries.pmi. Diffs are for the normal reasons when promotion is enabled/disabled... Generally more precise liveness means some field writes/reads can sometimes be removed, while sometimes struct copies require larger code. And of course fields can be kept in registers over long ranges.

**Review by tannergooding — APPROVED** [review]
Overall I think this is a net improvement and makes sense for typical usages of the vector types.

**Pull request merged**
