### PR TITLE
Handle contained BITCAST for STORE_LCL_FLD

### LINKED ISSUE #55141: Assertion failed 'src->IsCnsIntOrI()' with contained bitcast in field store
```csharp
// Generated by Fuzzlyn v1.2 on 2021-07-04 08:29:16
// Seed: 17631008191350222877
// Reduced from 8.2 KiB to 0.3 KiB in 00:00:11
// Debug: Outputs 0
// Release: Outputs 4217311480
struct S0
{
    public ulong F0;
    public ulong F1;
    public long F2;
    public uint F4;
    public uint F6;
}

public class Program
{
    public static void Main()
    {
        S0 vr1 = default(S0);
        vr1.F6 = (uint)vr1.F2-- / 254;
        System.Console.WriteLine(vr1.F6);
    }
}
```
On checked builds we get
```
Assert failure(PID 28800 [0x00007080], Thread: 25004 [0x61ac]): Assertion failed 'src->IsCnsIntOrI()' in 'Program:Main()' during 'Generate code' (IL size 50)

    File: D:\dev\dotnet\runtime\src\coreclr\jit\emitxarch.cpp Line: 3358
    Image: D:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\corerun.exe
```

We end up with a BITCAST node feeding into STORE_LCL_FLD:
```
                                                  /--*  t40    long   
N003 ( 22,  8) [000026] -c----------        t26 = *  BITCAST   int   
                                                  /--*  t26    int    
N005 ( 26, 13) [000028] UA--G-------              *  STORE_LCL_FLD int    V00 loc0         [+28] Fseq[F6]
```
The bitcast is marked as contained here: https://github.com/dotnet/runtime/blob/607f98c888b31566c773712c3153236c7cec05d2/src/coreclr/jit/lowerxarch.cpp#L4845-L4856
But `CodeGen::genCodeForStoreLclFld` is not prepared to handle that.

### PR DESCRIPTION
**Pull request by kunalspathak**
`UDIV` is lowered to the `MULHI/BITCAST` nodes and are stored in field using `STORE_LCL_FLD`. `BITCAST` is marked as contained so the value to be stored can be used directly from `MULHI`. However, having `BITCAST` as contained is not supported in codegen for `STORE_LCL_FLD` nodes.

The fix is to  handle the contained `BITCAST` scenario in `genCodeForStoreLclFld()` similar to the way we do in [genCodeForStoreLclVar()](https://github.com/dotnet/runtime/blob/e983168f871dcba090ff6ec08c0d2c7d4353fb8e/src/coreclr/jit/codegenxarch.cpp#L4505-L4516). 

There is a separate question on why we choose to `BITCAST` for xarch and `CAST` for armarch. I have asked it in https://github.com/dotnet/runtime/pull/52893#issuecomment-881680701.

Thanks @sandreenko for helping me investigate.

Fixes: https://github.com/dotnet/runtime/issues/55141

### CODE REVIEW

**Comment by SingleAccretion** [comment]
So I look at the IR in #55141:
```scala
                                                  /--*  t40    long   
N003 ( 22,  8) [000026] -c----------        t26 = *  BITCAST   int   
                                                  /--*  t26    int    
N005 ( 26, 13) [000028] UA--G-------              *  STORE_LCL_FLD int    V00 loc0         [+28] Fseq[F6]
```
And it doesn't make sense to me - aren't `BITCAST`s supposed to be used for register type mismatches only...?

Separately, the linked code for `GT_CAST` is using no-op constructs though that's not a big issue.

**Comment by kunalspathak** [comment]
> Edit: it looks to me that both armarch and xarch should be using "simple" (😄) `GT_CAST`s in this case.

That seems to be correct, but I want to understand the reasoning behind the original code before I change it. Also, regardless, we need to make sure that contained `BITCAST` is handled consistently for both `STORE_LCL_FLD` and `STORE_LCL_VAR`.

**Review by sandreenko — APPROVED** [review]
LGTM

could you please another issue to track bitcast/cast question?

**Comment by kunalspathak** [comment]
> could you please another issue to track bitcast/cast question?

#56053

**Comment by jakobbotsch** [comment]
This seems to handle incorrectly the following case:
```csharp
// Generated by Fuzzlyn v1.2 on 2021-07-22 13:45:33
// Seed: 7718323254176193466
// Reduced from 89.3 KiB to 0.4 KiB in 00:00:46
// Debug: Outputs 1
// Release: Outputs 0
struct S2
{
    public uint F0;
    public long F1;
    public uint F2;
    public short F3;
    public bool F4;
    public S2(uint f0, uint f2): this()
    {
        F0 = f0;
        F2 = f2;
    }
}

public class Program
{
    static int s_1;
    public static void Main()
    {
        int vr23 = s_1;
        S2 vr29 = new S2(1, (uint)vr23 / 40319);
        System.Console.WriteLine(vr29.F0);
    }
}
```

The codegen we get is:
```asm
; Assembly listing for method Program:Main()
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; No PGO data
; 0 inlinees with PGO data; 1 single block inlinees; 0 inlinees without PGO data
; Final local variable assignments
;
;  V00 loc0         [V00,T01] (  2,  2   )     int  ->  rcx         single-def
;  V01 OutArgs      [V01    ] (  1,  1   )  lclBlk (32) [rsp+00H]   "OutgoingArgSpace"
;  V02 tmp1         [V02,T00] (  4,  8   )  struct (24) [rsp+20H]   do-not-enreg[SFB] "NewObj constructor temp"
;* V03 tmp2         [V03    ] (  0,  0   )     int  ->  zero-ref    "Inlining Arg"
;
; Lcl frame size = 56

G_M27646_IG01:              ;; offset=0000H
       4883EC38             sub      rsp, 56
       C5F877               vzeroupper
                                                ;; bbWeight=1    PerfScore 1.25
G_M27646_IG02:              ;; offset=0007H
       8B0DFFD92A00         mov      ecx, dword ptr [reloc classVar[0x8cdfe320]]
       33C0                 xor      eax, eax
       C5F857C0             vxorps   xmm0, xmm0
       C5FA7F442420         vmovdqu  xmmword ptr [rsp+20H], xmm0
       4889442430           mov      qword ptr [rsp+30H], rax
       C744242001000000     mov      dword ptr [rsp+20H], 1
       B8FD520ED0           mov      eax, 0xD00E52FD
       8BC9                 mov      ecx, ecx
       480FAFC8             imul     rcx, rax
       48C1E92F             shr      rcx, 47
       894C2420             mov      dword ptr [rsp+20H], ecx
       8B4C2420             mov      ecx, dword ptr [rsp+20H]
       E88EFCFFFF           call     System.Console:WriteLine(int)
       90                   nop
                                                ;; bbWeight=1    PerfScore 10.83
G_M27646_IG03:              ;; offset=0043H
       4883C438             add      rsp, 56
       C3                   ret
                                                ;; bbWeight=1    PerfScore 1.25

; Total bytes of code 72, prolog size 7, PerfScore 20.73, instruction count 18, allocated bytes for code 74 (MethodHash=cb019401) for method Program:Main()
```
As you can see, the result of the division is stored at `rsp+0x20` which is wrong. The `STORE_LCL_FLD` node looks like
```scala
Generating: N035 ( 28, 14) [000031] UA----------              ▌  STORE_LCL_FLD int    V02 tmp1         ud:3->0[+16] Fseq[F2] NA REG NA
IN000b:        mov      dword ptr [V02 rsp+20H], ecx
```

**Pull request merged**
