### PR TITLE
Disable adaptive loop alignment for known hot methods

### PR DESCRIPTION
**Pull request by EgorBo**
Should fix perf problems like https://github.com/dotnet/runtime/issues/82442#issuecomment-1444073181

So for methods with sufficient PGO samples (currently it's 1000 invocations with static PGO) we might want to ignore size-aware heuristics and apply large paddings (e.g. 30 bytes) for loops. Let's see if this hits any diffs

### CODE REVIEW

**Comment by EgorBo** [comment]
No hits

**Comment by EgorBo** [comment]
Ah, no hits because SPMI disables loop alignment

**Comment by tannergooding** [comment]
> That will be a lot more padding and sometimes more than the loop code itself

It is definitely the case that small/hot loops may end up with more padding, but it can also equally be that it makes a significant difference on the throughput of the method.

We should likely balance it to not "waste padding" for things like crossgen, but to also be more forgiving on "padding" when we're compiling a known hot method via rejit.

If we can skip the "large padding" with an unconditional jump, that's even better.

**Comment by kunalspathak** [comment]
> it makes a significant difference on the throughput of the method.

That would be a good exercise to do on 100s of benchmarks and see how they are impacted before we merge this change. That's how we fine-tuned the heuristics for loop alignment when we first added the support for it.

**Comment by EgorBo** [comment]
Yeah I just wanted to see the diffs on CI (couldn't run them locally)

**Comment by kunalspathak** [comment]
> good exercise to do on 100s of benchmarks

Just to clarify - By executing the benchmarks and measuring the impact.

**Comment by EgorBo** [comment]
Ah, still no hits in SPMI. Presumably becuase `fgHaveSufficientProfileWeights` is too conservative - it expects 1000 calls + static profile. Also, our Static PGO is stale and doesn't include my changes for HexConverter

**Comment by kunalspathak** [comment]
And you are not able to run this locally to get the data?

**Comment by EgorBo** [comment]
> And you are not able to run this locally to get the data?

Do you mean to collect PGO? Yes, but we need to update it anyway (it's currently based on some November version of runtime) so I'll just wait till it's propagated

**Pull request closed without merging**
