### PR TITLE
Update steps to rebuild System.Runtime ref source

### LINKED ISSUE #37966: Updating reference sources for System.Runtime don't work
https://github.com/dotnet/runtime/blob/1692e34e4161fa8ee9d3f92ba0abb2aae93a8b1a/docs/coding-guidelines/updating-ref-source.md

After following these instructions I would expect the generated ref assembly to have the extra attributes added in #37704 but it doesn't.

It doesn't look too surprising since GenApi is invoked with a single input: the single input is the ref assembly that I want to update in the first place. It's not clear to me how this is supposed to work (replacing the ref with the impl assembly and specifying a libpath produces and empty file instead).

```
"C:\git\runtime\.dotnet\dotnet.exe" "C:\Users\michals\.nuget\packages\microsoft.dotnet.genapi\5.0.0-beta.20309.1\build\\..\tools\netcoreapp2.1\Microsoft.DotNet.GenAPI.dll" "C:\git\runtime\artifacts\obj\System.Runtime\ref\net5.0-Release\System.Runtime.dll" --lib-path "" --out "C:\git\runtime\src\libraries\System.Runtime\ref\System.Runtime.cs"  --exclude-attributes-list "C:\git\runtime\eng\DefaultGenApiDocIds.txt" --header-file "C:\git\runtime\eng\LicenseHeader.txt" --lang-version "preview" (TaskId:17)
```

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #37966.

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thanks!

**Comment by safern** [comment]
Thanks! LGTM

**Comment by ViktorHofer** [comment]
@MichalStrehovsky just curious, why did you add the `--no-incremental` flag to the invocation?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky just curious, why did you add the `--no-incremental` flag to the invocation?

Mindlessly copypasted from https://github.com/dotnet/runtime/issues/37966#issuecomment-644861021.

**Pull request merged**
