### PR TITLE
Remove BOM from CoreCLR files

### PR DESCRIPTION
**Pull request by nxtn**
As stated in https://github.com/dotnet/runtime/pull/31907#issuecomment-583470145.

~Do not squash-merge. Authors are overridden.~

### CODE REVIEW

**Comment by danmosemsft** [comment]
> Do not squash-merge. Authors are overridden.

Sorry squash is the policy of this repo.

**Comment by jkotas** [comment]
Regressions\coreclr\20616\UnicodeBug\UnicodeBug.cmd test is failing:

```
Unhandled exception. System.TypeLoadException: Could not load type '?' from assembly 'UnicodeBug, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
 at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
 at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
 at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
 at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) at main()
Return code: 1
Raw output file: C:\h\w\B80D0A4F\w\B6FB09A1\e\Regressions\coreclr\Reports\Regressions.coreclr\20616\UnicodeBug\UnicodeBug.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B80D0A4F\p\corerun.exe" UnicodeBug.dll 
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
```

**Comment by GrabYourPitchforks** [comment]
I think some of our .cs / .txt files have actual UTF-8 data in them. I'm currently writing a tool to confirm this.

**Comment by GrabYourPitchforks** [comment]
The following files are touched by this PR and contain non-ASCII data:

```txt
src/coreclr/src/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs
src/coreclr/src/tools/Common/TypeSystem/Common/MetadataVirtualMethodAlgorithm.cs
src/coreclr/src/tools/GCLogParser/Properties/AssemblyInfo.cs
src/coreclr/src/tools/GCLogParser/parse-hb-log.cs
src/coreclr/tests/src/Interop/COM/NETClients/Primitives/StringTests.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/AFF_PFF/AFF_PFF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/AFF_PFT/AFF_PFT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/AFF_PTF/AFF_PTF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/AFF_PTT/AFF_PTT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/AFT_PFF/AFT_PFF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/AFT_PFT/AFT_PFT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/AFT_PTF/AFT_PTF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/AFT_PTT/AFT_PTT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/ATF_PFF/ATF_PFF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/ATF_PFT/ATF_PFT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/ATF_PTF/ATF_PTF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/ATF_PTT/ATF_PTT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/ATT_PFF/ATT_PFF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/ATT_PFT/ATT_PFT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/ATT_PTF/ATT_PTF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/ATT_PTT/ATT_PTT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/Assembly_False_False/Assembly_False_False.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/Assembly_False_True/Assembly_False_True.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/Assembly_True_False/Assembly_True_False.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/Assembly_True_True/Assembly_True_True.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/Pinvoke_False_False/Pinvoke_False_False.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/Pinvoke_False_True/Pinvoke_False_True.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/Pinvoke_True_False/Pinvoke_True_False.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/Char/Pinvoke_True_True/Pinvoke_True_True.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/AFF_PFF/AFF_PFF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/AFF_PFT/AFF_PFT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/AFF_PTF/AFF_PTF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/AFF_PTT/AFF_PTT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/AFT_PFF/AFT_PFF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/AFT_PFT/AFT_PFT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/AFT_PTF/AFT_PTF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/AFT_PTT/AFT_PTT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/ATF_PFF/ATF_PFF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/ATF_PFT/ATF_PFT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/ATF_PTF/ATF_PTF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/ATF_PTT/ATF_PTT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/ATT_PFF/ATT_PFF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/ATT_PFT/ATT_PFT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/ATT_PTF/ATT_PTF.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/ATT_PTT/ATT_PTT.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/Assembly_False_False/Assembly_False_False.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/Assembly_False_True/Assembly_False_True.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/Assembly_True_False/Assembly_True_False.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/Assembly_True_True/Assembly_True_True.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/Pinvoke_False_False/Pinvoke_False_False.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/Pinvoke_False_True/Pinvoke_False_True.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/Pinvoke_True_False/Pinvoke_True_False.cs
src/coreclr/tests/src/Interop/PInvoke/BestFitMapping/LPStr/Pinvoke_True_True/Pinvoke_True_True.cs
src/coreclr/tests/src/Interop/SizeConst/SizeConstTest.cs
src/coreclr/tests/src/Regressions/coreclr/20616/UnicodeBug.il
```

**Comment by NextTurn** [comment]
> Regressions\coreclr\20616\UnicodeBug\UnicodeBug.cmd test is failing:

Is it a known issue that ILAsm doesn't recognize UTF8 files without BOM?

**Comment by jkotas** [comment]
> Is it a known issue that ILAsm doesn't recognize UTF8 files without BOM?

This is how it is implemented - it uses CP_ACP by default: https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/coreclr/src/ilasm/grammar_after.cpp#L1521

**Comment by jkotas** [comment]
> The following files are touched by this PR and contain non-ASCII data:

Could you please exclude this list from this PR? They can be fixed a separate PR by using the proper escape sequences, etc.

**Review by jkotas — APPROVED** [review]
Thanks!

**Pull request merged**
