### PR TITLE
Make SocketsHttpHandler's content encoding comparison case-insensitive

### LINKED ISSUE #98236: Decompression handler is case-sensitive
### Description

Reference to [RFC](https://www.rfc-editor.org/rfc/rfc2616#section-3.5) All content-coding values are case-insensitive, although [DecompressionHandler](https://github.com/dotnet/runtime/blob/bb2376cf22172196bcac715d2f26ddfcb1b991cf/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs#L81) is case-sensitive

It seems this issue exist in .NET Framework 4.6.2 project

### Reproduction Steps

Provide "Gzip" instead of "gzip" in the header

### Expected behavior

handle both "Gzip" and "gzip"

### Actual behavior

Did not handle "Gzip"

private const string Gzip = "gzip";

 

if (GZipEnabled && last == Gzip)
{
    response.Content = new GZipDecompressedContent(response.Content);
}

### Regression?

_No response_

### Known Workarounds

Provide "gzip"

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/98236

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM.
However, it does not make the comparisons case insensitive, right?  
e.g. It just handles another variant we did not before but I'm not sure if that covers spirit of the RFC.

**Comment by wfurt** [comment]
(and does not address  the `Did not handle "Gzip"`)

**Comment by stephentoub** [comment]
> However, it does not make the comparisons case insensitive, right?

It does.

Are you looking at the test for maybe?

**Comment by stephentoub** [comment]
> and does not address the Did not handle "Gzip"

It does, it's now using StringComparison.OrdinalIgnoreCase.

**Comment by wfurt** [comment]
> Are you looking at the test file maybe?

yes. actually I did. never mind.

**Review by ManickaP — APPROVED** [review]
Thanks!

**Pull request merged**
