### PR TITLE
Split the HttpConnectionPool into multiple files

### PR DESCRIPTION
**Pull request by MihaZupan**
___There should be 0 behavioral changes from this PR.___

@dotnet/ncl This aims to make contributing and reviewing changes to the connection pool easier in the future. The current file has grown to 2800 lines with H1/H2/H3-specific logic scattered throughout.
The expectation is that changes commonly only deal with a specific version / shared code, so we shouldn't see many PRs touching more than 1 or 2 of the new files at a time.

I would greatly appreciate feedback here as I'd prefer we don't make such changes too often to minimize messing with history.

---

This PR splits the `HttpConnectionPool.cs` file into more manageable pieces:
- `HttpConnectionWaiter.cs` - the customized cancellable TCS with a few helpers
- `RequestQueue.cs` - the custom `Queue<T>` implementation that needn't be in the same class
- `HttpConnectionPool.cs` - shared logic such as the `ctor`, transport establishment, core SendAsync with retry method
- `HttpConnectionPool.Http1.cs` - state and methods specific to handling H1 connections & requests
- `HttpConnectionPool.Http2.cs` - same but for H2 + logic for H2 => H1 downgrade
- `HttpConnectionPool.Http3.cs` - same but for H3

Most changes are just moving fields and methods between the new files.
`HttpConnectionPool*.cs` are all `partial class HttpConnectionPool`. It may be possible to fully extract more logic in the future  (or even make it generic across HTTP versions), but that is a more complex endeavor that we can attempt in the future.

---

Methods moved onto different classes:
- `HttpConnectionPool.TrySignalWaiter(Waiter)` => `HttpConnectionWaiter.TrySignal`
- `HttpConnectionPool.CancelIfNecessary(Waiter)` => `HttpConnectionWaiter.CancelIfNecessary`
- `HttpConnectionPool.IsUsableConnection(Connection)` => `HttpConnectionBase.IsUsable`

---

Renamed methods (to make it less confusing given the existence of other methods like `AddNewHttp11Connection`, `CreateHttp11ConnectionAsync`, `RecycleHttp11Connection`):
- `AddHttp11ConnectionAsync` => `InjectNewHttp11ConnectionAsync` (called from `CheckForHttp11ConnectionInjection`)
- `AddHttp2ConnectionAsync` => `InjectNewHttp2ConnectionAsync`

---

I reordered methods within the files to better match between different HTTP versions.
For H1 and H2, it currently looks like this (top to bottom):

| HTTP/1.1                            | HTTP/2                             |
| ----------------------------------- | ---------------------------------- |
| `TryGetPooledHttp11Connection`      | `TryGetPooledHttp2Connection`      |
| `ProcessHttp11RequestQueue`         |                                    |
| `CheckForHttp11ConnectionInjection` | `CheckForHttp2ConnectionInjection` |
| `InjectNewHttp11ConnectionAsync`    | `InjectNewHttp2ConnectionAsync`    |
| `CreateHttp11ConnectionAsync`       |                                    |
| `ConstructHttp11ConnectionAsync`    | `ConstructHttp2ConnectionAsync`    |
| `HandleHttp11ConnectionFailure`     | `HandleHttp2ConnectionFailure`     |
|                                     | `HandleHttp11Downgrade`            |
| `RecycleHttp11Connection`           | `ReturnHttp2Connection`            |
| `AddNewHttp11Connection`            |                                    |
| `ReturnHttp11Connection`            |                                    |
|                                     | `DisableHttp2Connection`           |
| `InvalidateHttp11Connection`        | `InvalidateHttp2Connection`        |
|                                     | `HeartBeat`                        |
| `ScavengeHttp11ConnectionStack`     | `ScavengeHttp2ConnectionList`      |

---

image

### CODE REVIEW

**Review by ManickaP — APPROVED** [review]
LGTM :shipit:

**Review by CarnaViire — APPROVED** [review]
LGTM

**Review by antonfirsov — APPROVED** [review]
This is great! I also dislike the idea of working with very long files, which is the primary reason I isolated `Http2Connection.StreamWindowManager` and `Http2Connection.RttEstimator` into separate private types, but this is an unusual practice in the BCL, and maybe we don't like the type load cost or possible other side effects this creates? If yes it might be better to follow a similar practice there and move the members out while keeping them in separate files.

**Comment by MihaZupan** [comment]
IMO if the implementation is not trivial and can reasonably be separated out logically, we should look into making it a separate type (e.g. `RttEstimator`).
Extra costs for e.g. type loading should be negligible (I'd hope), so I'd say we should ignore it in favor of whatever we feel is easier to maintain.

Whether it's a private type in a partial class vs. a new top-level type, I don't care that much.
Personally, I'd lean towards extracting it if it doesn't need access to internals (e.g. `RequestQueue`).

**Pull request merged**
