### PR TITLE
Switch to non-incremental servicing and update ApiCompatNetCoreAppBaselineVersion to 9.0.0

### LINKED ISSUE #106598: Update PackageValidation (APICompat) baseline version to 9.0.0 in November (.NET 9 GA)
https://github.com/dotnet/runtime/blob/d3da7a2c823245534e557f97013136d06a98e731/Directory.Build.props#L125

This line should be updated to 9.0.0 when .NET 9 is generally available. This should happen in both main and release/9.0.

### PR DESCRIPTION
**Pull request by carlossanlop**
Fixes https://github.com/dotnet/runtime/issues/106598

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by carlossanlop** [comment]
I see ApiCompat failures @ViktorHofer

**Comment by ViktorHofer** [comment]
The failures will go away when we forward port https://github.com/dotnet/runtime/pull/109316/ into main

**Comment by carlossanlop** [comment]
> The failures will go away when we forward port #109316 into main (or into this PR).

In that case, I'll reset your sign-off and will bring those changes into this PR. There was a conflict when attempting the automatic backport.

**Comment by carlossanlop** [comment]
@ericstj @ViktorHofer after bringing the 9.0 changes to switch to non-incremental servicing, I hit some api-compat failures in my local machine. I am not confident on what to do about them, they seem very similar to the ones that already exist in ApiCompatBaseline.NetCoreAppLatestStable.xml, but with different left and right values. Also, running the allconfigurations command with `/p:ApiCompatGenerateSuppresionFile=true` is creating _new_ files with completely unrelated suppressions for coreclr and mono, not the ones reported in the errors.

I pushed the changes so the ApiCompat failure shows up in the CI.

**Comment by ViktorHofer** [comment]
You need to update ApiCompat.proj's suppression files. That's a manual task:

`.\dotnet.cmd build src/libraries/apicompat/ApiCompat.proj /p:ApiCompatGenerateSuppressionFile=true`

**Comment by carlossanlop** [comment]
@ViktorHofer I pushed a commit with the result of running that command.

**Comment by carlossanlop** [comment]
> Hmm those files aren't what I was expecting to get produced by that command. https://github.com/dotnet/runtime/blob/main/src/libraries/apicompat/ApiCompatBaseline.NetCoreAppLatestStable.xml should have get updated.
> 
> Isn't that the case?

That's exactly what I meant in my previous comment. There were no updates to ApiCompatBaseline.NetCoerAppLatestStable.xml, which is what I was expecting:

> running the allconfigurations command with /p:ApiCompatGenerateSuppresionFile=true is creating new files with completely unrelated suppressions for coreclr and mono, not the ones reported in the errors.

The command you provided updated fewer files actually. The allconfigurations command updated mono files too.

**Comment by ViktorHofer** [comment]
Very weird. Something is wrong. Let me debug offline.

**Comment by ViktorHofer** [comment]
I only get the netstandard2.0 and the netstandard2.1 suppression files printed onto the console but not the `ApiCompatBaseline.NetCoreAppLatestStable.xml` one. That's weird indeed.

```
C:\git\runtime4> dotnet.cmd build src\libraries\apicompat\ApiCompat.proj --no-restore --no-dependencies /p:ApiCompatGenerateSuppressionFile=true /bl

  ApiCompat -> Comparing net10.0 reference assemblies against .NETStandard 2.x and .NETCoreApp 9.0.0...
  Successfully wrote compatibility suppressions to 'C:\git\runtime4\src\libraries\apicompat\ApiCompatBaseline.netstanda
  rd2.1.xml'.
  Successfully wrote compatibility suppressions to 'C:\git\runtime4\src\libraries\apicompat\ApiCompatBaseline.netstanda
  rd2.0.xml'.
```

**Comment by ViktorHofer** [comment]
The net9.0 <-> net10.0 step runs successfully but doesn't re-generate the suppression file:

image

But the other two subsequent steps (netstandard2.0 and netstandard2.1) do re-generate the suppression file correctly:

image

No idea why. I would need to debug with APICompat.

**Pull request merged**
