### PR TITLE
Update HttpStress to net5.0

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @eiriktsarpalis, @alnikola

### CODE REVIEW

**Review by eiriktsarpalis — DISMISSED** [review]
LGTM. Would probably make sense to use `$(NetCoreAppCurrent)` in the future, but I realize that will need slightly more work.

**Review by eiriktsarpalis — COMMENTED** [review]
Actually it looks like the change breaks the stress pipelines. It looks like the docker base images will need to be updated for this to work

https://dev.azure.com/dnceng/public/_build/results?buildId=646892&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=45b31e99-b18c-506f-46cf-7d3a4d5140a9&l=36

**Comment by stephentoub** [comment]
I'll just continue updating it locally then until we're ready to move those to 5.0.

**Pull request closed without merging**
