### PR TITLE
Use artifacts layout in place of bin dir

### PR DESCRIPTION
**Pull request by jashook**

### CODE REVIEW

**Review by trylek — APPROVED** [review]
LGTM

**Review by jkoritzinsky — DISMISSED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]
:shipit:

**Review by jkoritzinsky — COMMENTED** [review]
Arcade uses `log` instead of `logs` for the logs directory under `artifacts`.

Also, is this going to output to the `artifacts` directory in the root or an `artifacts` directory under `src/coreclr`?

**Review by sbomer — COMMENTED** [review]
I took another look, and pointed out most of the incorrect paths I noticed (other than docs). Some of the scripts assume a particular path to coreclr and will need to be updated anyway, so it may not be worth trying to get them all right in this change - take whichever suggestions you think make sense.

**Pull request merged**
