### PR TITLE
Resolve ILLink warnings in System.Diagnostics.TraceSource

### PR DESCRIPTION
**Pull request by eerhardt**
Contributes to #45623

### CODE REVIEW

**Comment by tarekgh** [comment]
The changes LGTM. I'll let @noahfalk and @sywhang sign off as the owners of this library.

**Comment by noahfalk** [comment]
The changes look reasonable based on what I am guessing the attributes mean. Is there a document somewhere that describes the different attributes and their meanings to help folks like me give a more accurate review? Thanks!

**Comment by eerhardt** [comment]
> Is there a document somewhere that describes the different attributes and their meanings to help folks like me give a more accurate review?

Yes, you can check out https://github.com/dotnet/designs/blob/main/accepted/2020/linking-libraries.md.

**Comment by eerhardt** [comment]
Test failures are #47374.

**Comment by eerhardt** [comment]
@noahfalk @sywhang thoughts on this? I can merge it if I get an approval.

**Review by noahfalk — APPROVED** [review]
LGTM

**Review by sywhang — APPROVED** [review]

**Pull request merged**
