### PR TITLE
Update solution files after projects changes

### PR DESCRIPTION
**Pull request by radekdoulik**
The project files have now different dependencies after changes in #97052

### CODE REVIEW

**Comment by radekdoulik** [comment]
@ViktorHofer I used the slngen.proj to update these solution files. I noticed you updated solution files in the past too, do you know if that is the preferred way to do it?

@pavelsavara does the build work for you with these changes?

**Review by ViktorHofer — APPROVED** [review]

**Comment by pavelsavara** [comment]
It's better/different problem now.

```
$env:WasmEnableThreads="true"
.\build.cmd -bl -os browser -subset mono+libs -c Debug
.\build.cmd -vs c:\Dev\runtime\src\libraries\System.Runtime.InteropServices.JavaScript\System.Runtime.InteropServices.JavaScript.sln
```

Build will pass.
Will open VS but would not work. 
VS is somehow confused about it.

image

**Comment by radekdoulik** [comment]
> > I used the slngen.proj to update these solution files. I noticed you updated solution files in the past too, do you know if that is the preferred way to do it?
> 
> Yes. `dotnet.cmd build src\libraries\slngen.proj`. Did you invoke that command?

Yes, from different folder, so my cmd line was `../../../dotnet.sh build -t:UpdateSolutionFile ../slngen.proj` and I used the `UpdateSolutionFile` target directly.

Then I picked only the solution files affected by the previous PR changes.

**Comment by ViktorHofer** [comment]
> Then I picked only the solution files affected by the previous PR changes.

We usually update all solution files but we can do that in a separate PR.

**Comment by akoeplinger** [comment]
> @akoeplinger do we already have an established pattern to link to the Mono's Private.CoreLib inside VS?

I'm not sure anyone tried, but setting RuntimeFlavor sounds like worth a try.

Though thinking about it, shouldn't VS compile against the ref SPC, not the implementation?

**Comment by radekdoulik** [comment]
> Though thinking about it, shouldn't VS compile against the ref SPC, not the implementation?

In this case we need the implementation, as it uses the `ThrowOnBlockingWaitOnJSInteropThread` field, which is not in the ref assembly.

**Comment by ViktorHofer** [comment]
> Though thinking about it, shouldn't VS compile against the ref SPC, not the implementation?

Projects compile against ref/CoreLib but they (correctly) reference the src/CoreLib project which then references the ref/CoreLib.

> I'm not sure anyone tried, but setting RuntimeFlavor sounds like worth a try.

We could respect that switch in build.ps1. I will send a PR.

**Comment by pavelsavara** [comment]
> $env:RuntimeFlavor=Mono

This helped with the `ThrowOnBlockingWaitOnJSInteropThread` but the problem with `CombineLinkerXmlFiles` from CoreCLR is still there

**Comment by pavelsavara** [comment]
image

Actually, not really.

**Comment by ViktorHofer** [comment]
I would hold off with merging this. I see the following on my VS when following the above steps:

image

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
I reran slngen locally, opened the produced slns and the failure from the picture above is now gone. No idea what is different but I updated your branch with the file updates.

**Comment by pavelsavara** [comment]
I'm good now, passing `RuntimeFlavor` and `TargetOS` is now necessary, kind of logical.

```
.\build.cmd /p:RuntimeFlavor="Mono" /p:TargetOS="browser" -vs c:\Dev\runtime\src\libraries\System.Runtime.InteropServices.JavaScript\System.Runtime.InteropServices.JavaScript.sln
```

**Review by pavelsavara — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Merging as slns aren't exercised in CI anyway.

**Comment by ViktorHofer** [comment]
Follow-ups.

Filed https://github.com/dotnet/runtime/issues/97984 to track Platform not being passed in correctly to System.Private.CoreLib's build.

Submitted https://github.com/dotnet/runtime/pull/97982 to respect the -os and -arch build properties for the VS invocation.

Submitted https://github.com/dotnet/runtime/pull/97974 to not cause task locks and to not trigger the illink tasks for CoreLib's build when opening VS and doing a design time build.

**Pull request merged**
