### PR TITLE
[wasm][aot] Blazor - fix handling satellite assemblies

### LINKED ISSUE #53431: [wasm] AOT build doesn't handle satellite assemblies correctly
I'm trying to AOT compile a [project](https://github.com/lbargaoanu/RoslynInBlazor/blob/master/RoslynInBlazor/RoslynInBlazor.csproj) that references Roslyn.
It says it cannot find some assemblies. I'm guessing it should find them by itself. But I can help with [that](https://github.com/lbargaoanu/RoslynInBlazor/blob/744e6dc846ff2b4f67390219ca530ddd475f1362/RoslynInBlazor/RoslynInBlazor.csproj#L12).
After explictly adding that package, I get "Bug: Number of aot assemblies doesn't match the number of generated bitcode files. BitcodeFiles: 100 vs Assemblies: 172".
Ideally, the compile would succeed just with the Roslyn package.

### PR DESCRIPTION
**Pull request by radical**
- Blazor passes a list of assemblies to the wasm targets for AOT, which
includes the satellite assemblies.

- We pass all of these to `MonoAOTCompiler`, which emits .bc files for
  each of them
  - but for satellite assemblies like `fr/foo.resources.dll`, and
    `cs/foo.resources.dll`
    - we get a single `foo.resources.dll.bc`
    - this causes the total number of input assemblies to not match the
      total number of .bc files produced!

Fix:

- remove the extra check (we'll add better ways for doing that in an
  upcoming change)
- And don't include the satellite assemblies for the AOT process

Fixes https://github.com/dotnet/runtime/issues/53431

### CODE REVIEW

**Comment by lewing** [comment]
Is this really the proper fix or just a workaround for that failure?

**Comment by radical** [comment]
> Is this really the proper fix or just a workaround for that failure?

It's a partial fix, but fixes the blazor case. It would break if user had non-satellite assemblies with names ending in `.resources.dll`, which usually shouldn't happen!

The proper fix would be:

1. correctly identify the satellite assemblies (get the list of satellite assemblies from ResolveAssemblyReferences task, or if identifying from an arbitrary list then extract+validate the culture name)
2. ensure that they skip the aot process
3. and (for non-blazor case) correctly add these to `mono-config.js`

**Comment by marek-safar** [comment]
I think we'll need to "correct" fix for 6 too (please make an issue if you are not working on it)

**Comment by radical** [comment]
> I think we'll need to "correct" fix for 6 too (please make an issue if you are not working on it)

I have a wip PR for that - https://github.com/dotnet/runtime/pull/53656

**Comment by radical** [comment]
Closing in favor of https://github.com/dotnet/runtime/pull/53656

**Pull request closed without merging**
