### PR TITLE
JIT: generalize checking for valid IR after a tail call

### LINKED ISSUE #51898: crossgen2 determinism fails with tiered pgo
Failed in [weekend testing](https://dev.azure.com/dnceng/public/_build/results?buildId=1106980&view=ms.vss-test-web.build-test-results-tab):
```
        1 / 1 (100%, 1 failed): failed in 21301 msecs, exit code -1073740286 = 0xC0000602, expected 0: corerun.exe C:\h\w\B106099F\p\crossgen2\crossgen2.dll @C:\h\w\B106099F\w\A02C0898\e\readytorun\coreroot_determinism\coreroot_determinism\seed1\CPAOT-ret.out\System.Private.CoreLib.dll.rsp
        !! Assert failure(PID 11800 [0x00002e18], Thread: 11760 [0x2df0]): Assertion failed 'OperIs(GT_LCL_VAR, GT_LCL_FLD, GT_PHI_ARG, GT_STORE_LCL_VAR, GT_STORE_LCL_FLD, GT_LCL_VAR_ADDR, GT_LCL_FLD_ADDR)' in 'ILCompiler.Compilation:IsEffectivelySealed(Internal.TypeSystem.MethodDesc):bool:this' during 'Morph - Global' (IL size 13)
        !!     File: D:\workspace\_work\1\s\src\coreclr\jit\gtstructs.h Line: 63
        !!     Image: C:\h\w\B106099F\p\corerun.exe
```
Looks like the problem is that the "exit sequence" after a tail call has a more complex structure than #50806 is prepared to sanction. In particular there are assignments with casts, and a nop.

I have a fix in progress.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Allow NOPs and assignments with non-overflowing casts, in addition
to the assignments we already allowed.

Closes #51898.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL
cc @dotnet/jit-contrib

**Review by EgorBo — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Is this valid in the view of this comment in the importer?
https://github.com/dotnet/runtime/blob/9a318320ca245bef064a5d9a540ff75e00ac096f/src/coreclr/jit/importer.cpp#L7762-L7768

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib anyone else want to weigh in? 

Do we normalize small return types in callee or caller? I vaguely recalled we changed our approach sometime back...

**Comment by sandreenko** [comment]
> Do we normalize small return types in callee or caller? I vaguely recalled we changed our approach sometime back...

Do you mean if we have `short Test(int v) { return (short)v; }` who is cleaning the upper bytes of the return value?
The `Test` is responsible for clearing the upper bits for short integer types, for structs they can be left in an undefined state.

So the caller of the `Test` can use the register as an int knowing that the upper bits are empty:
```
IN0002: 000009 call     C:Test(int):short
IN0003: 00000E mov      ecx, eax
IN0004: 000010 call     System.Console:WriteLine(int)
IN0005: 000015 mov      eax, 100
```

**Comment by AndyAyersMS** [comment]
So yes it seems like it is a stale comment.

@jakobbotsch perhaps you can look into what happens if we remove that check?

**Comment by jakobbotsch** [comment]
Sure, opened #51957 for it.

**Pull request merged**
