### PR TITLE
Bump coverlet version

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
Update coverlet .net tool version

cc: @ViktorHofer @safern

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]
Are you fixing something by updating the version in the runtime repo or is this just general goodness? Did you test if coverage measurement still works with 1.7.0?

**Comment by MarcoRossignoli** [comment]
> Are you fixing something by updating the version in the runtime repo or is this just general goodness? Did you test if coverage measurement still works with 1.7.0?

We have some code-coverage bug fix
ChangeLog https://github.com/tonerdo/coverlet/blob/master/Documentation/Changelog.md#release-date-2020-01-03

Now we've also integration testing for all coverlet drivers
Integration test https://github.com/tonerdo/coverlet/tree/master/test/coverlet.integration.tests
Specific .Net tool test https://github.com/tonerdo/coverlet/blob/master/test/coverlet.integration.tests/DotnetTool.cs#L18

Since last two version we've also rigorous coverage testing(real one) one sample https://github.com/tonerdo/coverlet/blob/master/test/coverlet.core.tests/Coverage/CoverageTests.cs#L160
No more manual testing.

Nothing changed on .NET Tool command line, as you know the engine is the same of vstest integration and msbuild(we're talking about shutdown msbuild and invest only on vstest integration, I saw on arcade that you're close to use `dotnet test` with collectors, right?).
For coverlet should be very useful if this repo use last release, you help us to catch error asap and open issue on our side, feel free to check the quality of tests on coverlet.
If you don't trust this upgrade no prob at all feel free to reject I'm not a touchy person :smile:, I was building repo and saw old version and thought to update as a coverlet co-maintainer is an instinct 😃

**Comment by ViktorHofer** [comment]
Great to hear that coverlet is constantly improving. Can you please verify that coverage measurement is still working in the runtime repo with the updated version? Just to prevent people complaining as we don't run it in CI currently.

**Comment by MarcoRossignoli** [comment]
> Can you please verify that coverage measurement is still working in the runtime repo with the updated version? 

Sure

> Just to prevent people complaining as we don't run it in CI currently.

We could add a simple test with simple check coverage for a project to understand if future upgrade break something, let me know if you like the idea and point me to right project where I can add it.

**Review by safern — APPROVED** [review]

**Comment by MarcoRossignoli** [comment]
Attached two logs, a small difference in percentage ~1-2% in line with some updates(for instance we skip to instrument some autogenerated code because sometimes lead to false negative, i.e. IsCompleted inside MoveNext() async machine state)

[1.7.0.txt](https://github.com/dotnet/runtime/files/4067403/1.7.0.txt)
[1.6.0.txt](https://github.com/dotnet/runtime/files/4067404/1.6.0.txt)

I noticed that guide need to updated(new path) and also that specific sample fail on my local https://github.com/dotnet/runtime/blob/9900dfb4b2e32cf02ca846adaf11e93211629ede/docs/workflow/building/libraries/code-coverage.md#local-code-coverage-runs

```
D:\git\runtime\src\libraries\System.Diagnostics.Debug\tests (master -> origin)
λ dotnet msbuild /t:BuildAndTest /p:Coverage=true
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  CoreFx.Private.TestUtilities -> D:\git\runtime\artifacts\bin\CoreFx.Private.TestUtilities\netcoreapp5.0-Debug\CoreFx.Private.TestUtilities.dll
D:\git\runtime\eng\liveBuilds.targets(37,5): error : The CoreCLR artifacts path does not exist 'D:\git\runtime\artifacts\bin\coreclr\Windows_NT.x64.Debug\'. The CoreCLR subset category must be built before building this project. [D:\git\runtime\src\libraries\System.Diagnostics.Debug\tests\System.Diagnostics.Debug.Tests.csproj]
```

**Comment by ViktorHofer** [comment]
Thanks a lot Marco. You are right we need to update most of our docs.

**Comment by MarcoRossignoli** [comment]
If you've some concern about https://github.com/tonerdo/coverlet/issues/683 mainly on possible breaking on coverlet tool verbs(the idea is to add `run`(current behaviour) and `merge/thresholds` etc...feel free to comment.
I'm trying to understand if there is a way for vstest(collectors) to know when all tests ends to be more friendly and avoid external command.

**Pull request merged**
