### PR TITLE
[release/6.0] Use new buildpools

### PR DESCRIPTION
**Pull request by hoyosjs**

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Review by carlossanlop — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
approved.  we should treat this as tell mode.

cc @carlossanlop

**Comment by carlossanlop** [comment]
@hoyosjs can you please check the CI results? There are 431 errors.

**Comment by hoyosjs** [comment]
@lewing @steveisok do these look like real failures?

**Comment by carlossanlop** [comment]
Confirmed with Juan that this is ready to merge. :shipit:

**Pull request merged**
