### PR TITLE
use TestDisableParallelization property to disable parallel test execution

### PR DESCRIPTION
**Pull request by adamsitnik**
It's defined in:

https://github.com/dotnet/runtime/blob/c66fa996b5cc32d94b2e6a8dfeb7c3d3a3098694/eng/testing/runsettings.targets#L30-L42

and I've tested that it works as expected.

### CODE REVIEW

**Review by carlossanlop — APPROVED** [review]

**Comment by jkotas** [comment]
> I've tested that it works as expected.

Does it work as expected when running tests from command line or in the CI? The .runsettings file seems to be VS specific.

**Comment by adamsitnik** [comment]
> Does it work as expected when running tests from command line or in the CI? 

I was running it using the `dotnet.cmd` script:

```cmd
.\dotnet.cmd build /t:Test .\src\libraries\System.IO.FileSystem.DriveInfo\tests\System.IO.FileSystem.DriveInfo.Tests.csproj  /p:Configuration=Release
```

Which I assume is used by the CI? I am going to run it using a global SDK and get back to you.

**Comment by adamsitnik** [comment]
It work both when using `dotnet.cmd` and a `dotnet.exe` from $PATH

**Comment by jkotas** [comment]
Ah ok, it is passed to XUnit on command line here: https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/eng/testing/xunit/xunit.console.targets#L18

**Comment by jkotas** [comment]
But it is not obvious to me that the extra argument will be passed all the way through for mobile test targets (iOS/Android/browser) that encapsulate the test in an app.

I think the existing solution where the test spec is fully encapsulated in the test .dll is better.

**Comment by stephentoub** [comment]
> I think the existing solution where the test spec is fully encapsulated in the test .dll is better.

+1.  The less msbuild magic that might subtly be missed in various configurations, the better.

**Comment by adamsitnik** [comment]
@jkotas @stephentoub Thank you for your feedback. I am going to close the PR and just move `src/libraries/System.Private.Xml/tests/Writers/XmlWriterApi/DisableParallelization.cs ` to some common folder and re-use it for `System.IO.FileSystem.DriveInfo` tests (https://github.com/dotnet/runtime/pull/62134)

**Pull request closed without merging**
