### PR TITLE
[wasm][debugger] Fix some racy tests

### LINKED ISSUE #62666: [wasm] `DebuggerTests.ExceptionTests.ExceptionTestAllWithReload` failing on CI
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62431-merge-ea9aef66794e4e4480/DebuggerTests.ExceptionTests/1/console.17087dd6.log?sv=2019-07-07&se=2021-12-31T00%3A26%3A03Z&sr=c&sp=rl&sig=AoX3SrDJoDN9NpH4Ro2%2B8UlqG2%2F2D0%2Fly6rKKJcLTdo%3D)

```
[00:32:07] info: Microsoft.WebAssembly.Diagnostics.TestHarnessProxy[0] New test request
  Failed DebuggerTests.ExceptionTests.ExceptionTestAllWithReload(entry_method_name: "[debugger-test] DebuggerTests.ExceptionTestsClassD"..., class_name: "System.Exception", line_number: 76) [1 s]
  Error Message:
   SendCommand for Debugger.resume failed with {
  "code": -32000,
  "message": "Can only perform operation while paused."
}
Expected: True
Actual:   False
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.SendCommandAndCheck(JObject args, String method, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, String waitForEvent) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 494
   at DebuggerTests.ExceptionTests.WaitForManagedException(JObject pause_location) in /_/src/mono/wasm/debugger/DebuggerTestSuite/ExceptionTests.cs:line 317
   at DebuggerTests.ExceptionTests.ExceptionTestAllWithReload(String entry_method_name, String class_name, Int32 line_number) in /_/src/mono/wasm/debugger/DebuggerTestSuite/ExceptionTests.cs:line 266
--- End of stack trace from previous location ---
```

### LINKED ISSUE #62667: [wasm][debugger] `DebuggerTests.MiscTests.DebugLazyLoadedAssemblyWithEmbeddedPdb` timing out on CI
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1507755&view=logs&jobId=fed58b4c-9287-5c27-b2fe-d4f5c6327616&j=fed58b4c-9287-5c27-b2fe-d4f5c6327616&t=07af5ef8-9d49-537b-698e-dadb508ad7b4), and [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62431-merge-ea9aef66794e4e4480/DebuggerTests.MiscTests/1/console.43f9d0ab.log?sv=2019-07-07&se=2021-12-31T00%3A26%3A03Z&sr=c&sp=rl&sig=AoX3SrDJoDN9NpH4Ro2%2B8UlqG2%2F2D0%2Fly6rKKJcLTdo%3D)

```
[xUnit.net 00:01:54.39]     DebuggerTests.MiscTests.DebugLazyLoadedAssemblyWithEmbeddedPdb [FAIL]
  Failed DebuggerTests.MiscTests.DebugLazyLoadedAssemblyWithEmbeddedPdb [59 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : Test timed out (elapsed time: 59.9993753)
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.SendCommandAndCheck(JObject args, String method, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, String waitForEvent) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 497
   at DebuggerTests.DebuggerTestBase.EvaluateAndCheck(String expression, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 481
   at DebuggerTests.MiscTests.DebugLazyLoadedAssemblyWithEmbeddedPdb() in /_/src/mono/wasm/debugger/DebuggerTestSuite/MiscTests.cs:line 770
--- End of stack trace from previous location ---
```

### LINKED ISSUE #62823: [wasm][debugger] `DebuggerTests.BreakpointTests.BreakpointInAssemblyUsingTypeFromAnotherAssembly_BothDynamicallyLoaded` timing out
[Build](https://github.com/dotnet/runtime/pull/62431/checks?check_run_id=4527411563), and [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62431-merge-d61be6d13266455ca9/DebuggerTests.BreakpointTests/1/console.d2dd1122.log?sv=2019-07-07&se=2022-01-03T22%3A53%3A07Z&sr=c&sp=rl&sig=0OSrbutytnGR0KLioz4BUukQEBgsqDQK%2FX74x%2B8WWLE%3D). This is failing on both Linux, and Windows.

PR that enables debugger tests on CI: https://github.com/dotnet/runtime/pull/62431

```
  Failed DebuggerTests.BreakpointTests.BreakpointInAssemblyUsingTypeFromAnotherAssembly_BothDynamicallyLoaded [59 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : Test timed out (elapsed time: 59.9967627)
[23:08:16] dbug: Microsoft.WebAssembly.Diagnostics.InspectorClient[0] connecting to ws://localhost:9400/launch-chrome-and-connect
  Stack Trace:
     at DebuggerTests.DebuggerTestBase.SendCommandAndCheck(JObject args, String method, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn, String waitForEvent) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 497
   at DebuggerTests.DebuggerTestBase.EvaluateAndCheck(String expression, String script_loc, Int32 line, Int32 column, String function_name, Func`2 wait_for_event_fn, Func`2 locals_fn) in /_/src/mono/wasm/debugger/DebuggerTestSuite/DebuggerTestBase.cs:line 481
   at DebuggerTests.BreakpointTests.BreakpointInAssemblyUsingTypeFromAnotherAssembly_BothDynamicallyLoaded() in /_/src/mono/wasm/debugger/DebuggerTestSuite/BreakpointTests.cs:line 311
--- End of stack trace from previous location ---
```

### PR DESCRIPTION
**Pull request by radical**
- tests that use late loaded assemblies
`DebuggerTests.MiscTests.DebugLazyLoadedAssemblyWithEmbeddedPdb`
`DebuggerTests.BreakpointTests.BreakpointInAssemblyUsingTypeFromAnotherAssembly_BothDynamicallyLoaded`

- `ExceptionTestAllWithReload`

Fixes https://github.com/dotnet/runtime/issues/62666
Fixes https://github.com/dotnet/runtime/issues/62823
Fixes https://github.com/dotnet/runtime/issues/62667

### CODE REVIEW

**Review by thaystg — APPROVED** [review]

**Review by lewing — APPROVED** [review]
Looks good, should we add an explicit timeout option?

**Comment by radical** [comment]
> should we add an explicit timeout option?

There is a per test timeout. Is that the one you meant?

**Comment by radical** [comment]
.. and I did test the case where the breakpoint is never hit, and the test fails with a timeout.

**Comment by radical** [comment]
Wasm (unrelated) test failures are because of https://github.com/dotnet/runtime/issues/64769 .

The (unrelated) `Mono minijit Pri0 Runtime Tests Run OSX x64 release`, and `Mono monointerpreter Pri0 Runtime Tests Run OSX x64 release` are due to missing OSX helix queues.

**Pull request merged**
