### PR TITLE
Fix #46123 - make the subProtocol nullable for HttpListenerContext::AcceptWebSocketAsync 

### LINKED ISSUE #46123: HttpListenerContext::AcceptWebSocketAsync should have a nullable annotation for the subProtocol
## Background and Motivation

The method [`AcceptWebSocketAsync`](https://github.com/dotnet/runtime/blob/86224fd11c943ebe111c602358f8b8d3c3fb7494/src/libraries/System.Net.HttpListener/src/System/Net/HttpListenerContext.cs#L36) on the `HttpListenerContext` class currently takes a `string subProtocol`. When using `#nullable enable`, the compiler warns about passing null to this parameter, but doing so is totally valid behaviour and indicates no sub-protocol should be used.

Note that passing an empty string (`string.Empty`) is **not** valid and causes an exception to be thrown during validation.

The code eventually gets in to [`HttpWebSocket::ValidateOptions()`](https://github.com/dotnet/runtime/blob/86224fd11c943ebe111c602358f8b8d3c3fb7494/src/libraries/System.Net.HttpListener/src/System/Net/WebSockets/HttpWebSocket.cs#L79) which has an explicit check for `subProtocol` begin null, but the parameter is also not marked as nullable there.

Note that currently to ignore the compiler warning you can call the method as follwos:

```C#
await ctx.AcceptWebSocketAsync(null!);
```

## Proposed API

**UPDATE** by @antonfirsov: included all 4 overloads.

```diff
public class HttpListenerContext
{
-   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string subProtocol);
+   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string? subProtocol);
-   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string subProtocol, int receiveBufferSize, TimeSpan keepAliveInterval);
+   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string? subProtocol, int receiveBufferSize, TimeSpan keepAliveInterval);
-   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string subProtocol, int receiveBufferSize, TimeSpan keepAliveInterval, ArraySegment<byte> internalBuffer);
+   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string? subProtocol, int receiveBufferSize, TimeSpan keepAliveInterval, ArraySegment<byte> internalBuffer);
-   public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string subProtocol, TimeSpan keepAliveInterval);
+    public Task<HttpListenerWebSocketContext> AcceptWebSocketAsync(string? subProtocol, TimeSpan keepAliveInterval);
}
```

_Note: There are several overloads of this method, and it ends up calling these overloads and other methods to validate options - these will also need alterations._

## Usage Examples

``` C#
WebSocketContext webSocketCtx = await httpContext.AcceptWebSocketAsync(null);
```

## Alternative Designs

N/A

## Risks

N/A

### PR DESCRIPTION
**Pull request by euantorano**
Fixes #46123. This makes the `subProtocol` nullable when accepting web sockets.

A null subProtocol is valid and means no subprotocol, whereas an empty string is not valid so there needs to be a distinction between them.

I hope I've covered everything that needs doing here, but as this is my first contribution please let me know if there's anything I've missed.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47402) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47402) before we can accept your contribution.<br/><br/>:x: euantorano [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47402)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=47402) it.</sub>

**Comment by antonfirsov** [comment]
Looks like we even have the tests in [HttpListenerContextTests.cs](https://github.com/dotnet/runtime/blob/8c1b48a2f9a3ec3b1dae45b3bb8deda6640b3ae2/src/libraries/System.Net.HttpListener/tests/HttpListenerContextTests.cs) to cover the `subProtocol=null` cases, it's just the test project has not been updated to use nullable references.

Should be good to merge if #46123 gets the API approval.

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
@jeffhandley, I don't remember how/where you wanted to track nullability changes...

**Comment by jeffhandley** [comment]
> @jeffhandley, I don't remember how/where you wanted to track nullability changes...

Here's the running issue: https://github.com/dotnet/docs/issues/21202
Thanks!

**Pull request merged**
