### PR TITLE
Update Android to r23b image

### PR DESCRIPTION
**Pull request by directhex**
Let's give this a full CI run, see if anything broke

### CODE REVIEW

**Comment by directhex** [comment]
Yes, everything broke, GNU `as` is gone

**Review by steveisok — APPROVED** [review]
Android build looks good

**Comment by steveisok** [comment]
> Details

All look like known issues to me.  The ping one in particular was fixed in main yesterday.

**Comment by directhex** [comment]
I think Android failures are a bad CI machine. I've pinged first responders on Teams

**Pull request merged**
