### PR TITLE
Fix runtime pack aliasing

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Review by radical — APPROVED** [review]

**Comment by radical** [comment]
fyi, we don't need to see the result of all the jobs in `runtime-wasm`, just `WasmBuildTests` on linux, and windows.

**Review by hoyosjs — APPROVED** [review]

**Comment by hoyosjs** [comment]
@radical That pipeline is broken when targeting 6.0 looks like. Is there any coverage in the pipeline for this?

**Comment by radical** [comment]
> @radical That pipeline is broken when targeting 6.0 looks like. Is there any coverage in the pipeline for the aliasing? Or can this be merged to unblock the build?

We can merge this. I confirmed that the relevant tests ran on `runtime`.

**Pull request merged**
