### PR TITLE
Do not retype small locals in `FIELD_LIST`s on x86

### LINKED ISSUE #73951: JIT: Bad codegen on x86 for a function in collectible ALC
```csharp
// Generated by Fuzzlyn v1.5 on 2022-08-15 13:32:00
// Run on X86 Windows
// Seed: 9809551563097583633
// Reduced from 536.2 KiB to 1.8 KiB in 00:20:04
// Debug: Outputs 0
// Release: Outputs 61952
public struct S0
{
    public uint F1;
    public int F2;
    public byte F3;
}

public class C0
{
    public ushort F1;
    public C0(ushort f1)
    {
        F1 = f1;
    }
}

public class C1
{
    public C1(uint f0, uint f1)
    {
    }
}

public class C2
{
    public C2(C1 f0, uint f2, ulong f3, bool f5, int f6)
    {
    }
}

public struct S1
{
    public C2 F0;
    public S0 F1;
    public S1(C2 f0): this()
    {
        F0 = f0;
    }

    public S1 M105(S0 arg0)
    {
        Program.s_10.F0 = new C2(new C1(521025157U, 1254134592U), 2911867824U, 0, false, 0);
        return this;
    }
}

public class Program
{
    public static IRuntime s_rt;
    public static S1 s_10;
    public static S1 s_17;
    public static void Main()
    {
        CollectibleALC alc = new CollectibleALC();
        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
        System.Reflection.MethodInfo mi = asm.GetType(typeof(Program).FullName).GetMethod(nameof(MainInner));
        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
        mi.Invoke(null, new object[]{System.Activator.CreateInstance(runtimeTy)});
    }

    public static void MainInner(IRuntime rt)
    {
        s_rt = rt;
        S0 vr21 = s_17.F1;
        new S1(new C2(new C1(0, 0), 0, 0, false, 0)).M105(vr21);
        var vr22 = new C0(vr21.F3);
        s_rt.WriteLine("c_1839", vr22.F1);
    }
}

public interface IRuntime
{
    void WriteLine<T>(string site, T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(string site, T value) => System.Console.WriteLine(value);
}

public class CollectibleALC : System.Runtime.Loader.AssemblyLoadContext
{
    public CollectibleALC(): base(true)
    {
    }
}
```

### LINKED ISSUE #74562: JIT: Assertion failed 'genTypeSize(fieldNode) == TARGET_POINTER_SIZE' during 'Generate code'
```csharp
// Generated by Fuzzlyn v1.5 on 2022-08-21 16:52:30
// Run on X86 Windows
// Seed: 4378749738790679738
// Reduced from 49.3 KiB to 1.2 KiB in 00:01:12
// Hits JIT assert in Release:
// Assertion failed 'genTypeSize(fieldNode) == TARGET_POINTER_SIZE' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Generate code' (IL size 29; hash 0xade6b36b; FullOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\codegenxarch.cpp Line: 7969
// 
public class Program
{
    public static byte s_11;
    public static uint[] s_21;
    public static void Main()
    {
        CollectibleALC alc = new CollectibleALC();
        System.Reflection.Assembly asm = alc.LoadFromAssemblyPath(System.Reflection.Assembly.GetExecutingAssembly().Location);
        System.Reflection.MethodInfo mi = asm.GetType(typeof(Program).FullName).GetMethod(nameof(MainInner));
        System.Type runtimeTy = asm.GetType(typeof(Runtime).FullName);
        mi.Invoke(null, new object[]{System.Activator.CreateInstance(runtimeTy)});
    }

    public static void MainInner(IRuntime rt)
    {
        var vr6 = new int[]{0};
        M25(vr6, (s_11 + (0 & s_21[0])));
    }

    public static byte M25(int[] arg0, long arg2)
    {
        int var0 = arg0[0]++;
        long vr14 = default(long);
        return (byte)vr14;
    }
}

public interface IRuntime
{
    void WriteLine<T>(string site, T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(string site, T value) => System.Console.WriteLine(value);
}

public class CollectibleALC : System.Runtime.Loader.AssemblyLoadContext
{
    public CollectibleALC(): base(true)
    {
    }
}
```

### PR DESCRIPTION
**Pull request by SingleAccretion**
This is not correct for normalize-on-load register candidates.

Fixes #73951.
Fixes #74562.

A tiny [regression](https://dev.azure.com/dnceng/public/_build/results?buildId=1951172&view=ms.vss-build-web.run-extensions-tab) on x86, due to using extending moves in more cases.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
SPMI failures look pre-existing.

@dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
@SingleAccretion When I run the new unit test locally, it passes even without your fix. I'm on 676a6bb4de26e34945b9170870f4712906fa834d

Also, I notice when building the test locally I get a warning:
```
Program.cs(11,28): warning CS8618: Non-nullable field 's_rt' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
```
I don't see this in the CI build, but maybe they suppress all warnings?

**Comment by SingleAccretion** [comment]
Hmm, that is very strange. I don't see any nullability warnings locally:
```
C:\Users\Accretion\source\dotnet\runtime\src\tests\JIT\Regression\JitBlue\Runtime_73951> dotnet build

MSBuild version 17.4.0-preview-22378-04+827c1bf9c for .NET
  Determining projects to restore...
  Restored C:\Users\Accretion\source\dotnet\runtime\src\tests\JIT\Regression\JitBlue\Runtime_73951\Runtime_73951.csproj (in 219 ms).
  Restored C:\Users\Accretion\source\dotnet\runtime\src\tests\Common\XUnitWrapperGenerator\XUnitWrapperGenerator.csproj (in 235 ms).
C:\Users\Accretion\source\dotnet\runtime\artifacts\tests\coreclr\packages\JIT\Regression\JitBlue\Runtime_73951\Runtime_73951\Runtime_73951.csproj.nuget.g.props(17,5): warning MSB4011: "C
:\Users\Accretion\.nuget\packages\microsoft.net.illink.tasks\7.0.100-1.22415.4\build\Microsoft.NET.ILLink.Tasks.props" cannot be imported again. It was already imported at "C:\Users\Accr
etion\source\dotnet\runtime\artifacts\tests\coreclr\packages\Common\test_dependencies\test_dependencies\test_dependencies.csproj.nuget.g.props (16,5)". This is most likely a build author
ing error. This subsequent import will be ignored. [C:\Users\Accretion\source\dotnet\runtime\src\tests\JIT\Regression\JitBlue\Runtime_73951\Runtime_73951.csproj]
C:\Users\Accretion\source\dotnet\runtime\artifacts\tests\coreclr\packages\JIT\Regression\JitBlue\Runtime_73951\Runtime_73951\Runtime_73951.csproj.nuget.g.props(18,5): warning MSB4011: "C
:\Users\Accretion\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-2.22412.11\build\Microsoft.Net.Compilers.Toolset.props" cannot be imported again. It was already imported at "C:\U
sers\Accretion\source\dotnet\runtime\artifacts\tests\coreclr\packages\Common\test_dependencies\test_dependencies\test_dependencies.csproj.nuget.g.props (17,5)". This is most likely a bui
ld authoring error. This subsequent import will be ignored. [C:\Users\Accretion\source\dotnet\runtime\src\tests\JIT\Regression\JitBlue\Runtime_73951\Runtime_73951.csproj]
  XUnitWrapperGenerator -> C:\Users\Accretion\source\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Common\XUnitWrapperGenerator\XUnitWrapperGenerator\XUnitWrapperGenerator.dll
  Runtime_73951 -> C:\Users\Accretion\source\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Regression\JitBlue\Runtime_73951\Runtime_73951\Runtime_73951.dll

Build succeeded.

C:\Users\Accretion\source\dotnet\runtime\artifacts\tests\coreclr\packages\JIT\Regression\JitBlue\Runtime_73951\Runtime_73951\Runtime_73951.csproj.nuget.g.props(17,5): warning MSB4011: "C
:\Users\Accretion\.nuget\packages\microsoft.net.illink.tasks\7.0.100-1.22415.4\build\Microsoft.NET.ILLink.Tasks.props" cannot be imported again. It was already imported at "C:\Users\Accr
etion\source\dotnet\runtime\artifacts\tests\coreclr\packages\Common\test_dependencies\test_dependencies\test_dependencies.csproj.nuget.g.props (16,5)". This is most likely a build author
ing error. This subsequent import will be ignored. [C:\Users\Accretion\source\dotnet\runtime\src\tests\JIT\Regression\JitBlue\Runtime_73951\Runtime_73951.csproj]
C:\Users\Accretion\source\dotnet\runtime\artifacts\tests\coreclr\packages\JIT\Regression\JitBlue\Runtime_73951\Runtime_73951\Runtime_73951.csproj.nuget.g.props(18,5): warning MSB4011: "C
:\Users\Accretion\.nuget\packages\microsoft.net.compilers.toolset\4.4.0-2.22412.11\build\Microsoft.Net.Compilers.Toolset.props" cannot be imported again. It was already imported at "C:\U
sers\Accretion\source\dotnet\runtime\artifacts\tests\coreclr\packages\Common\test_dependencies\test_dependencies\test_dependencies.csproj.nuget.g.props (17,5)". This is most likely a bui
ld authoring error. This subsequent import will be ignored. [C:\Users\Accretion\source\dotnet\runtime\src\tests\JIT\Regression\JitBlue\Runtime_73951\Runtime_73951.csproj]
    2 Warning(s)
    0 Error(s)

Time Elapsed 00:00:10.44
```
And the test does fail without and pass with the fix:
```
C:\Users\Accretion\source\dotnet\runtime\src\tests\JIT\Regression\JitBlue\Runtime_73951> set-test-env -a x86 -b
CORE_ROOT: C:\Users\Accretion\source\dotnet\runtime-base\artifacts\tests\coreclr\windows.x86.Checked\Tests\Core_Root
DOTNET_TieredCompilation: 0

PS C:\Users\Accretion\source\dotnet\runtime\src\tests\JIT\Regression\JitBlue\Runtime_73951> C:\Users\Accretion\source\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Regression\JitBlue\Runtime_73951\Runtime_73951\Runtime_73951.cmd
BEGIN EXECUTION
 "C:\Users\Accretion\source\dotnet\runtime-base\artifacts\tests\coreclr\windows.x86.Checked\Tests\Core_Root\corerun.exe"   Runtime_73951.dll
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED

PS C:\Users\Accretion\source\dotnet\runtime\src\tests\JIT\Regression\JitBlue\Runtime_73951> set-test-env -a x86
CORE_ROOT: C:\Users\Accretion\source\dotnet\build\CustomCoreRoot_x86
DOTNET_TieredCompilation: 0

PS C:\Users\Accretion\source\dotnet\runtime\src\tests\JIT\Regression\JitBlue\Runtime_73951> C:\Users\Accretion\source\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Debug\JIT\Regression\JitBlue\Runtime_73951\Runtime_73951\Runtime_73951.cmd
BEGIN EXECUTION
 "C:\Users\Accretion\source\dotnet\build\CustomCoreRoot_x86\corerun.exe"   Runtime_73951.dll
Expected: 100
Actual: 100
END EXECUTION - PASSED
PASSED
```
There is a detail in the test (the original Fuzzlyn code from which it was adapted also has this property) that to fail it needs to read some random bits from the stack, so perhaps it could be influenced by the environment...?

(But it does fail for me consistently, FWIW)

**Comment by JulieLeeMSFT** [comment]
@BruceForstall please backport this to 7.0 once all tests pass.

**Review by JulieLeeMSFT — APPROVED** [review]

**Comment by BruceForstall** [comment]
I was able to (finally) reproduce the baseline failure and diff code non-failure.

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
