### PR TITLE
removing more crossgen code from being built.

### PR DESCRIPTION
**Pull request by mangod9**
Should improve build times further.

### CODE REVIEW

**Comment by mangod9** [comment]
cc @dotnet/crossgen-contrib . This should remove about ~80 files from compiling.

**Comment by mangod9** [comment]
win-arm64 failures are due to overall helix arm64 flakiness.

**Review by davidwrighton — APPROVED** [review]
LGTM, but you can probably remove more. In a future PR, I would see if you can remove all the files in src/coreclr/jit/crossgen, as well as the cmakelists.txt in src/coreclr/zap

**Review by hoyosjs — APPROVED** [review]
We should give a heads up to Samsung in crossgen cleanup. I believe they were still using this. Linking https://github.com/dotnet/runtime/issues/54129

cc: @alpencolt @gbalykov @clamp03

**Comment by mangod9** [comment]
Yeah will link to #54129 once merged.

**Comment by mangod9** [comment]
> LGTM, but you can probably remove more. In a future PR, I would see if you can remove all the files in src/coreclr/jit/crossgen, as well as the cmakelists.txt in src/coreclr/zap

yeah will remove more cmakelists in subsequent PRs, but dont believe they are being exercised so wouldnt affect build times.

**Comment by clamp03** [comment]
@hoyosjs @mangod9 Thank you for your consideration.

**Comment by alpencolt** [comment]
> We should give a heads up to Samsung in crossgen cleanup. I believe they were still using this. Linking #54129
> 
> cc: @alpencolt @gbalykov @clamp03

We haven't decided what will use in .net6, but according to to #54129 crossge1 will be removed in .net7, am I right? If so it's ok.

**Comment by mangod9** [comment]
Hey @alpencolt, crossgen has been removed from building in the runtime repo, and we might start removing (the now defunct) code post .net preview7, but could defer till start of .net 7 if that helps.

**Pull request merged**
