### PR TITLE
Make it clear the subset flag can be omitted

### PR DESCRIPTION
**Pull request by SingleAccretion**
It is not necessary to explicitly specify the subset flag when building.

### CODE REVIEW

**Comment by joperezr** [comment]
Hello @SingleAccretion, while I agree that the subset is implicit, this is only the case when it is the first argument so I believe it is intentional that our docs are in the verbose format. If anything, I think we should only mention in the subset parameter that if it is the first item, you can omit it (which we might already have this mention). @ViktorHofer thoughts?

**Comment by SingleAccretion** [comment]
I suspected as much, yes. I agree that it would probably be better to just point out that the flag can be omitted, and this is indeed mentioned in various places (notably, all examples in `./build -h` use the short form).

What lead me to do it this way is the fact that, having pointed a person new to `dotnet/runtime` to this document (and the directory in general), they did not discover this fact. Not only that, but one of the developers of `dotnet/runtime` did not know it either, which lead me to believe this knowledge is not as pervasive as I've assumed, which in turn lead to this PR.

**Review by ViktorHofer — COMMENTED** [review]
I'm fine with either merging this or not but FWIW I would prefer a consistent style in our docs. I doubt that coreclr's README.md is the only place that uses the explicit subset style.

**Comment by SingleAccretion** [comment]
Other docs use the explicit style. I will revert the changes and just mention the flag can be omitted.

**Comment by ViktorHofer** [comment]
FWIW I think the implicit style makes more sense as I don't see a reason why the subset wouldn't be the first param.

**Review by joperezr — APPROVED** [review]

**Comment by joperezr** [comment]
Thanks for the contribution @SingleAccretion !

**Pull request merged**
