### PR TITLE
NativeAOT: Removed LLVM ObjWriter and LLVM dependency

### PR DESCRIPTION
**Pull request by TIHan**
Now that C# ObjWriter has had a few months to bake, it's time to get rid of the LLVM ObjWriter completely. Briefly talked to @filipnavara about removing the LLVM ObjWriter and he is feeling confident with the C# implementation. 

This totally removes the LLVM ObjWriter from the repo. This includes removing the package dependencies and any mention of LLVM ObjWriter in the docs. NativeAOT will not rely on LLVM anymore, with the exception of using `coredistools` for dev work.

### CODE REVIEW

**Comment by TIHan** [comment]
cc @agocke @MichalStrehovsky @jkotas @filipnavara

**Comment by MichalPetryka** [comment]
Does this also remove the dependency of `StripSymbols` on LLVM?

**Comment by TIHan** [comment]
> Does this also remove the dependency of StripSymbols on LLVM?

It only removes the LLVM ObjWriter dependency. What is `StripSymbols` in this context? I saw there is `iOSStripSymbols` - are we using LLVM for this?

**Review by jkotas — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
Resolves #74505
Resolves #75636

> Does this also remove the dependency of `StripSymbols` on LLVM?

StripSymbols doesn't depends on LLVM. It depends on _some_ stripping tool, be it from binutils or LLVM. This doesn't affect that. The binary we're stripping is produced by the native linker, not object writer, and we still run the native linker and have no plans to replace that.

**Comment by MichalStrehovsky** [comment]
What's the plan for the object writer in the LLVM repo? Do we need to delete it, or will it be dropped next time LLVM is upgraded?

**Review by MichalStrehovsky — APPROVED** [review]
🎈🎈 🥳

**Review by filipnavara — APPROVED** [review]

**Comment by am11** [comment]
Congrats! Huge kudos to @filipnavara. 🎉

cc @shushanhf, @clamp03, @gbalykov, new platforms can skip the llvm objwriter and directly implement it in C#.

**Comment by shushanhf** [comment]
> Congrats! Huge kudos to @filipnavara. 🎉
> 
> cc @shushanhf, @clamp03, @gbalykov, new platforms can skip the llvm objwriter and directly implement it in C#.

@am11 Thanks very much.
We had an initial version Native-AOT for LoongArch64 within our local runtime.

**Comment by filipnavara** [comment]
> @am11 Thanks very much. We had an initial version Native-AOT for LoongArch64 within our local runtime.

Would be something nice to share. I already looked into RV64 support and how more code sharing can be achieved between platforms and NativeAOT/CoreCLR.

**Comment by shushanhf** [comment]
> > @am11 Thanks very much. We had an initial version Native-AOT for LoongArch64 within our local runtime.
> 
> Would be something nice to share. I already looked into RV64 support and how more code sharing can be achieved between platforms and NativeAOT/CoreCLR.

I plan to push a PR at half year as waiting LLVM amending some LA64's features and we also amend the Native-AOT.

**Comment by TIHan** [comment]
> What's the plan for the object writer in the LLVM repo? Do we need to delete it, or will it be dropped next time LLVM is upgraded?

We should keep the branch, but not update it any further.

**Comment by am11** [comment]
> We should keep the branch

It was merged to dotnet/llvm-project's main. Even if we delete it from main, it will stay in git history forever. imo, it's better to clean it up and remove the associated packaging infra from that repo's main to avoid confusions.

**Comment by TIHan** [comment]
> It was merged to dotnet/llvm-project's main.

Oh, interesting. That's kind of a bummer. I guess we will remove it.

**Comment by TIHan** [comment]
Failures are https://github.com/dotnet/runtime/issues/99725 and unrelated to this PR. Merging.

Thank you again everyone, especially @filipnavara for putting so much effort and thought into this work!

**Pull request merged**
