### PR TITLE
Handle different SIMD moves in peephole optimization

### PR DESCRIPTION
**Pull request by MichalPetryka**
Handles different SIMD move instructions in move removing peephole.

CC @tannergooding

### CODE REVIEW

**Comment by TIHan** [comment]
Been recently making changes in `IsRedundantMov` for https://github.com/dotnet/runtime/pull/85780. The changes here should work well with it though, so no conflicts that I can see.

**Comment by tannergooding** [comment]
Can you add a test that hits this scenario?

Since we've moved to normalizing most loads to `GT_IND`, we are generally consistent around emitting `movups` now. However, there are still some scenarios (and will be more in the future when `VectorMask` is added) where we can't use `GT_IND` and will emit an alternative instruction instead, so this support is likely still worthwhile

**Comment by tannergooding** [comment]
Ping @MichalPetryka, just wanting to make sure you saw the request for the test.

**Comment by MichalPetryka** [comment]
> Ping @MichalPetryka, just wanting to make sure you saw the request for the test.

I'll get to it in a few days, sorry for the delay.

**Comment by JulieLeeMSFT** [comment]
@MichalPetryka, please check the question from EgorBo and reply to it. FYI, with Needs-author-action label, it will be automatically closed if no activity for 3-4 weeks.

**Comment by JulieLeeMSFT** [comment]
@MichalPetryka, there is no diff from this PR, so we'd like to know the motivation of this PR and benefit of this PR.

**Pull request closed without merging**
