### PR TITLE
CI matrix update: add Ubuntu 21.04 - second attempt

### PR DESCRIPTION
**Pull request by aik-jahoda**
The original CI matrix change was reverted (#60040) because of a failing CI.

part of #57947

original PR: #59578

### CODE REVIEW

**Comment by karelz** [comment]
@safern @ericstj can you please review the PR? Then we can merge (and backport to .NET 6.0). Thanks!

**Review by karelz — APPROVED** [review]

**Comment by ericstj** [comment]
I believe there is an open question from reviewers above which requires attention:

> Does this added queue only run as part of a rolling build? If so, can you please queue up a build with your changes to make sure that the changes work as expected?

> As it stands now - it would only run in a rolling build

@aik-jahoda Can you share the results of the rolling build which tests your changes?

**Comment by aik-jahoda** [comment]
Test result: https://dnceng.visualstudio.com/public/_build/results?buildId=1493975&view=logs&j=b9b7de4d-2126-5581-6453-1576f9aaac5f&t=db048d48-40e8-5399-9b14-d587763f33ff&l=38

**Comment by aik-jahoda** [comment]
@safern, @ericstj , can you please take a look?

**Review by ericstj — APPROVED** [review]
This looks good to me.  @safern do you agree?

**Comment by ericstj** [comment]
Actually, I'm not entirely certain how to interpret all these failures in the other legs.  I see the linked log shows at least one pass on the new queues.  Do you understand the other failures?

**Review by safern — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
