### PR TITLE
[wasm] Fix long branches in jiterpreter

### PR DESCRIPTION
**Pull request by kg**
https://github.com/dotnet/runtime/issues/106028

### CODE REVIEW

**Comment by kg** [comment]
This change is correct but doesn't fix it, unfortunately. Will have to dig in further.

**Comment by kg** [comment]
OK, the root cause was that an enum didn't get updated. But I cleaned up some code related to branches while I was in here, which should make it easier to debug in the future.

**Review by BrzVlad — APPROVED** [review]

**Comment by pavelsavara** [comment]
Could you please add flag that would make call `loaderHelpers.mono_exit(1, err);`, instead of just log warning ?
And then turn on that flag in `test-main.js` for all unit tests.

similar to `withExitOnUnhandledError` or `withDumpThreadsOnNonZeroExit`

Thanks

**Comment by kg** [comment]
> Could you please add flag that would make call `loaderHelpers.mono_exit(1, err);`, instead of just log warning ? And then turn on that flag in `test-main.js` for all unit tests.
> 
> similar to `withExitOnUnhandledError` or `withDumpThreadsOnNonZeroExit`
> 
> Thanks

Will do a follow up PR for this.

**Pull request merged**
