### PR TITLE
Remove GT_STORE_DYN_BLK

### PR DESCRIPTION
**Pull request by EgorBo**
`GT_STORE_DYN_BLK ` seems to be rarely used (only used for `cpblk/initblk` when size is not constant) - so we can remove ~500 LOC and replace it early in importer with a call to memset/memcpy directly (we can make it `GT_INTRINSIC` then and remove `GT_STORE_BLK` too?)

### CODE REVIEW

**Comment by EgorBo** [comment]
Oh, VM doesn't implement `CORINFO_HELP_MEMSET` and `CORINFO_HELP_MEMCPY` for X86 (because jit never needed it and used `rep`).

**Comment by EgorBo** [comment]
@jkotas X86 is missing https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/amd64/CrtHelpers.asm (NAOT and R2R are fine) - I am just wondering, can these two wrappers be implemented in C++ JIT_MemSet/JIT_MemCpy portable helpers instead? Presumably the nullcheck can be done via volatile load?

**Comment by jkotas** [comment]
> I am just wondering, can these two wrappers be implemented in C++ JIT_MemSet/JIT_MemCpy portable helpers instead?
> Presumably the nullcheck can be done via volatile load? 

It is not possible to catch and handle segfaults in C++ code. The null check would need to be done via an explicit check and explicit call of a throw helper.

If you would like to reduce amount of assembly code, I think the way to do is to rewrite these helpers in C#; or by making JIT responsible for the null checks (it would allow JIT to skip the null check when it is not needed).

**Comment by EgorBo** [comment]
> or by making JIT responsible for the null checks (it would allow JIT to skip the null check when it is not needed).

This sounds interesting. What about zero length check that we have in the asm helpers? E.g. https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/amd64/CrtHelpers.asm#L34-L35

**Comment by MichalPetryka** [comment]
> Hopefully, memset/memcpy should not do anything illegal for zero length

`Where an argument declared as size_t n specifies the length of the array for a function, n can have the value zero on a call to that function. Unless explicitly stated otherwise in the description of a particular function in this subclause, pointer arguments on such a call shall still have valid values, as described in 7.1.4. On such a call, a function that locates a character finds no occurrence, a function that compares two character sequences returns zero, and a function that copies characters copies zero characters.`

**Comment by jkotas** [comment]
Yes, the JIT would need to inline the check for zero length when the length is not a constant.

Regular memset/memcpy works fine for zero length and null pointer, but the sanitizer and similar variants of the methods trip on it.

**Comment by EgorBo** [comment]
Will try to do this iteratively

**Pull request closed without merging**
