### PR TITLE
[LoongArch64] Fix some bugs in the test sets 'System.Runtime.Tests' and 'System.Linq.Expressions.Tests' for loongarch64.

### PR DESCRIPTION
**Pull request by LuckyXu-HF**
This PR is part of the issue https://github.com/dotnet/runtime/issues/69705 to amend the LA's port.

Fix some bugs in the test sets 'System.Runtime.Tests' and 'System.Linq.Expressions.Tests' for loongarch64：

* fix the error of the Truncate/Saturate convert from Float/Double NAN to UINT32/UINTPTR.

* fix some random failed testcases in System.Runtime.Tests.

* fix the RangeCheck bug of the TYP_INT case in CodeGen::genRangeCheck().

### CODE REVIEW

**Comment by LuckyXu-HF** [comment]
Based on this commit, the libraries test set "System.Runtime.Tests" has been all passed on loongarch64.

<pre>
----- start 2023年 05月 18日 星期四 20:13:42 CST =============== To repro directly: =====================================================
pushd ./libs-testcase-release-v8.0.0-preview.4.23259.5/System.Runtime.Tests/Release/net8.0-unix
/home/xuliangyu/libs-8-tests/net8.0-linux-Release-LA64-v8.0.0-preview.4.23259.5/dotnet exec --runtimeconfig System.Runtime.Tests.runtimeconfig.json --depsfile System.Runtime.Tests.deps.json xunit.console.dll System.Runtime.Tests.dll -xml testResults.xml -nologo -notrait category=AdditionalTimezoneChecks -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
~/libs-8-tests/libs-testcase-release-v8.0.0-preview.4.23259.5/System.Runtime.Tests/Release/net8.0-unix ~/libs-8-tests
  Discovering: System.Runtime.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Tests (found 9163 of 9210 test cases)
  Starting:    System.Runtime.Tests (parallel test collections = on, max threads = 4)
    System.Tests.DateTimeOffsetTests.ToLocalTime_MinValue [SKIP]
      Condition(s) not met: "IsMinValueNegativeLocalOffset"
    System.Tests.StringTests.IndexOf_SingleLetter(s: "Hello", target: '\0', startIndex: 0, count: 5, expected: -1) [SKIP]
      Target \0 is not supported in ICU
    System.Tests.DateTimeOffsetTests.ToLocalTime_Ambiguous [SKIP]
      Condition(s) not met: "IsPacificTime"
    System.Tests.StringTests.LastIndexOf_NullInStrings [SKIP]
      Condition(s) not met: "IsNlsGlobalization"
    System.Tests.StringTests.IndexOf_NullInStrings [SKIP]
      Condition(s) not met: "IsNlsGlobalization"
    System.Tests.StringTests.EndsWith_NullInStrings_NonOrdinal [SKIP]
      Condition(s) not met: "IsNlsGlobalization"
    System.Tests.StringTests.StartsWith_NullInStrings_NonOrdinal [SKIP]
      Condition(s) not met: "IsNlsGlobalization"
    System.Tests.StringTests.EndsWith_NullInStrings [SKIP]
      Condition(s) not met: "IsNlsGlobalization"
    System.Tests.StringTests.StartsWith_NullInStrings [SKIP]
      Condition(s) not met: "IsNlsGlobalization"
    System.Tests.ArgIteratorTests.ArgIterator_GetNextArgType [SKIP]
      Condition(s) not met: "IsArgIteratorSupported"
    System.Tests.ArgIteratorTests.ArgIterator_GetRemainingCount_GetNextArg [SKIP]
      Condition(s) not met: "IsArgIteratorSupported"
    System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest [SKIP]
      Condition(s) not met: "DoesNotSupportIanaNamesConversion"
    System.Runtime.Tests.JitInfoTests.JitInfoIsNotPopulated [SKIP]
      Condition(s) not met: "IsMonoAOT"
  Finished:    System.Runtime.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Tests  Total: 58145, Errors: 0, Failed: 0, Skipped: 13, Time: 42.250s
~/libs-8-tests
----- end 2023年 05月 18日 星期四 20:14:28 CST ----- exit code 0 ----------------------------------------------------------
exit code 0 means Exited Successfully
</pre>

**Comment by LuckyXu-HF** [comment]
> @LuckyXu-HF please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

**Comment by LuckyXu-HF** [comment]
Based on this commit, the libraries test set "System.Runtime.Tests" has been all passed on loongarch64.

<pre>
----- start 2023年 05月 18日 星期四 20:13:42 CST =============== To repro directly: =====================================================
pushd ./libs-testcase-release-v8.0.0-preview.4.23259.5/System.Runtime.Tests/Release/net8.0-unix
/home/xuliangyu/libs-8-tests/net8.0-linux-Release-LA64-v8.0.0-preview.4.23259.5/dotnet exec --runtimeconfig System.Runtime.Tests.runtimeconfig.json --depsfile System.Runtime.Tests.deps.json xunit.console.dll System.Runtime.Tests.dll -xml testResults.xml -nologo -notrait category=AdditionalTimezoneChecks -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
~/libs-8-tests/libs-testcase-release-v8.0.0-preview.4.23259.5/System.Runtime.Tests/Release/net8.0-unix ~/libs-8-tests
  Discovering: System.Runtime.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Tests (found 9163 of 9210 test cases)
  Starting:    System.Runtime.Tests (parallel test collections = on, max threads = 4)
    System.Tests.DateTimeOffsetTests.ToLocalTime_MinValue [SKIP]
      Condition(s) not met: "IsMinValueNegativeLocalOffset"
    System.Tests.StringTests.IndexOf_SingleLetter(s: "Hello", target: '\0', startIndex: 0, count: 5, expected: -1) [SKIP]
      Target \0 is not supported in ICU
    System.Tests.DateTimeOffsetTests.ToLocalTime_Ambiguous [SKIP]
      Condition(s) not met: "IsPacificTime"
    System.Tests.StringTests.LastIndexOf_NullInStrings [SKIP]
      Condition(s) not met: "IsNlsGlobalization"
    System.Tests.StringTests.IndexOf_NullInStrings [SKIP]
      Condition(s) not met: "IsNlsGlobalization"
    System.Tests.StringTests.EndsWith_NullInStrings_NonOrdinal [SKIP]
      Condition(s) not met: "IsNlsGlobalization"
    System.Tests.StringTests.StartsWith_NullInStrings_NonOrdinal [SKIP]
      Condition(s) not met: "IsNlsGlobalization"
    System.Tests.StringTests.EndsWith_NullInStrings [SKIP]
      Condition(s) not met: "IsNlsGlobalization"
    System.Tests.StringTests.StartsWith_NullInStrings [SKIP]
      Condition(s) not met: "IsNlsGlobalization"
    System.Tests.ArgIteratorTests.ArgIterator_GetNextArgType [SKIP]
      Condition(s) not met: "IsArgIteratorSupported"
    System.Tests.ArgIteratorTests.ArgIterator_GetRemainingCount_GetNextArg [SKIP]
      Condition(s) not met: "IsArgIteratorSupported"
    System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest [SKIP]
      Condition(s) not met: "DoesNotSupportIanaNamesConversion"
    System.Runtime.Tests.JitInfoTests.JitInfoIsNotPopulated [SKIP]
      Condition(s) not met: "IsMonoAOT"
  Finished:    System.Runtime.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Tests  Total: 58145, Errors: 0, Failed: 0, Skipped: 13, Time: 42.250s
~/libs-8-tests
----- end 2023年 05月 18日 星期四 20:14:28 CST ----- exit code 0 ----------------------------------------------------------
exit code 0 means Exited Successfully
</pre>


> 

@dotnet-policy-service agree company="loongson"

**Review by shushanhf — APPROVED** [review]
Hi, @jakobbotsch 
Could you please review this PR?

**Comment by LuckyXu-HF** [comment]
Hi, @jakobbotsch 
This PR is mainly fix some bugs in the test set 'System.Runtime.Tests' and 'System.Linq.Expressions.Tests' for LA64.
Could you please review this PR?
Thanks.

**Review by jakobbotsch — APPROVED** [review]

**Pull request merged**
