### PR TITLE
Remove net5 feeds

### LINKED ISSUE #41593: Remove dotnet5* feeds from NuGet.config in master
The dotnet5* feeds should be removed as soon as all dependencies are available in the dotnet6* feeds. If that's already the case, it should be done now.

cc @dotnet/runtime-infrastructure

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/runtime/issues/41593
Depends on https://github.com/dotnet/runtime/pull/43304

List of not flowing packages in the dotnet* feeds (in-complete):
- [x] microsoft.private.intellisense
- [x] optimization.*

cc @mmitche

### CODE REVIEW

**Comment by danmosemsft** [comment]
@ViktorHofer is this good to merge?

**Comment by ViktorHofer** [comment]
Nope... Need to work with @mmitche to get the non-flowing packages into the net6 feeds. Hasn't been a priority yet.

**Comment by ViktorHofer** [comment]
> netstandard.library

@ericstj I don't think we want to continue using a netstandard 2.2 prerelease package. Should we downgrade our usage to the latest 2.1 released package?

**Comment by ericstj** [comment]
> latest 2.1 released package

So long as that works with source build.  @dseefeld

**Comment by dseefeld** [comment]
> > latest 2.1 released package
> 
> So long as that works with source build. @dseefeld Dan Seefeldt FTE

This should work for source-build.  netstandard.library.ref 2.1.0 is built in source-build-reference-packages.

**Comment by ViktorHofer** [comment]
@dotnet/runtime-infrastructure who knows which component pushes the optimization data to the dotnet5 feed? We need to update that to the dotnet6 feed.

afaik microsoft.private.intellisense is published manually into our feed, so we want to manually publish the latest version into dotnet6 know as well and update guidance.

**Comment by jkoritzinsky** [comment]
The internal dotnet-optimization repo produces the optimization data.

**Comment by ViktorHofer** [comment]
> The internal dotnet-optimization repo produces the optimization data.

That pipeline has been failing since 9/29: https://dev.azure.com/dnceng/internal/_build?definitionId=237. Who ones that repo/infra?

**Comment by jkoritzinsky** [comment]
@agocke is working now on getting it back online.

**Comment by ViktorHofer** [comment]
> @agocke is working now on getting it back online.

Do we need to track this as part of the CI Council dashboard? I assume it's @mmitche or @Anipik who did the default channel remapping from dotnet5 to dotnet6.

**Comment by agocke** [comment]
I can probably route as appropriate

**Comment by ViktorHofer** [comment]
> I can probably route as appropriate

Thanks a lot @agocke. Do you have an ETA when the repo will be unblocked?

I will speak with @Chrisboh to include the optimization pipeline to the internal dashboard to track it going forward.

**Comment by agocke** [comment]
Hoping to get it done this week, just getting up to speed.

**Comment by ViktorHofer** [comment]
I'd like to avoid adding the existing optimization packages to the dotnet6-transport feed, hence I added the "blocking" label until these packages are available.

**Comment by agocke** [comment]
Update on dotnet-optimization: I've fixed multiple issues, but this is tending to reveal more in further stages. Right now the problem seems to be that the runtime is not producing pgc files properly -- haven't yet figured out why that is.

**Comment by ViktorHofer** [comment]
@agocke any update on the optimization internal repo?

**Comment by agocke** [comment]
I've made several fixes and have now run into a runtime crash that's blocking. Stack looks like:

```C#
coreclr.dll!ClrFree(void * p) Line 302 C++
coreclr.dll!operator delete[](void * p) Line 410 C++
coreclr.dll!MulticoreJitRecorder::WriteOutput(IStream * pStream) Line 557 C++
coreclr.dll!MulticoreJitRecorder::WriteOutput() Line 155 C++
coreclr.dll!MulticoreJitRecorder::StopProfile(bool) Line 951 C++
coreclr.dll!MulticoreJitRecorder::WriteMulticoreJitProfiler(_TP_CALLBACK_INSTANCE * pInstance, void * pvContext, _TP_TIMER * pTimer) Line 810 C++
```

I'm working to try to get a time-travel debugging repro, but I'm unfamiliar with the system so it may take a bit.

**Comment by agocke** [comment]
This is now blocked on https://github.com/dotnet/runtime/issues/46778

**Comment by ViktorHofer** [comment]
@agocke looks like the related issue was fixed yesterday. I'm unsure how the optimization repo consumes new builds but I assume you are now unblocked?

**Comment by agocke** [comment]
I hope so, testing today

**Comment by agocke** [comment]
optimization should be unblocked and completing builds now

**Comment by ViktorHofer** [comment]
I manually pushed the latest optimization packages to the dotnet6-transport feed as bits are still not flowing from the optimization repo.

**Comment by ViktorHofer** [comment]
@dotnet/runtime-infrastructure this PR should be ready now. Would be great if you could approve. Thanks

We now know that the only dependencies that don't flow automatically are the optimization.* and the intellisense packages. Hopefully we can get the optimization ones hooked up onto dependency flow properly and intellisense one afaik should go away.

**Review by akoeplinger — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Failure is https://github.com/dotnet/runtime/issues/32805

**Pull request merged**
