### PR TITLE
JIT: Make sure static ctor flag check uses a volatile load

### LINKED ISSUE #105441: Test failure: NullReferenceException in Internal.JitInterface.CorInfoImpl._beginInlining
**Failed in:** [runtime-coreclr outerloop 20240724.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=753860&view=ms.vss-test-web.build-test-results-tab&runId=19108382&resultId=115545&paneView=debug)

**Failed tests:**
```
R2R-CG2 linux arm64 Checked @ (Alpine.317.Arm64.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm64v8
    - Regressions/coreclr/GitHub_87879/test87879/test87879.cmd
```

**Error message:**
```
 /root/helix/work/workitem/e/Regressions/Regressions/../coreclr/GitHub_87879/test87879/test87879.sh: line 315: -r:/root/helix/work/workitem/e/Regressions/coreclr/GitHub_87879/test87879/IL-CG2/*.dll: No such file or directory
Unhandled exception. ILCompiler.CodeGenerationFailedException: Code generation failed for method '[test87879]__GeneratedMainWrapper..ctor()'
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Internal.JitInterface.CorInfoImpl._beginInlining(IntPtr thisHandle, IntPtr* ppException, CORINFO_METHOD_STRUCT_* inlinerHnd, CORINFO_METHOD_STRUCT_* inlineeHnd) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl_generated.cs:line 154
   --- End of inner exception stack trace ---
   at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 381
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 810
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 898
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32 compilationThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 833
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(Object objThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 811
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'array')
   at System.Array.Clear(Array array, Int32 index, Int32 length)
   at Internal.JitInterface.CorInfoImpl.CompileMethodCleanup() in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 700
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 826
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 898
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32 compilationThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 833
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(Object objThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 811
/root/helix/work/workitem/e/Regressions/Regressions/../coreclr/GitHub_87879/test87879/test87879.sh: line 254:  4711 Aborted                 (core dumped) $__Command

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/coreclr/GitHub_87879/test87879/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/Regressions/coreclr/GitHub_87879/test87879/IL-CG2/test87879.dll
19:50:09
Response file: /root/helix/work/workitem/e/Regressions/coreclr/GitHub_87879/test87879/test87879.dll.rsp
/root/helix/work/workitem/e/Regressions/coreclr/GitHub_87879/test87879/IL-CG2/test87879.dll
-o:/root/helix/work/workitem/e/Regressions/coreclr/GitHub_87879/test87879/test87879.dll
-r:/root/helix/work/correlation/System.*.dll
-r:/root/helix/work/correlation/Microsoft.*.
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor74|0_75(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["NullReferenceException","_beginInlining"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=753860
**Error message validated:** `[NullReferenceException _beginInlining`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/27/2024 1:53:56 AM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[2582592](https://dev.azure.com/dnceng/internal/_build/results?buildId=2582592)|dotnet-runtime|Build managed CoreCLR and host components, all libraries, and packs|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2582592/logs/1995)||
|[2580533](https://dev.azure.com/dnceng/internal/_build/results?buildId=2580533)|dotnet-runtime|Build managed CoreCLR and host components, all libraries, and packs|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2580533/logs/2072)||
|[2578580](https://dev.azure.com/dnceng/internal/_build/results?buildId=2578580)|dotnet-runtime|Build managed CoreCLR and host components, all libraries, and packs|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2578580/logs/2336)||
|[2575423](https://dev.azure.com/dnceng/internal/_build/results?buildId=2575423)|dotnet-runtime|Build managed CoreCLR and host components, all libraries, and packs|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2575423/logs/2273)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|4|

### PR DESCRIPTION
**Pull request by jakobbotsch**
Otherwise the hardware is allowed to reorder loads of its static fields to happen before the initialization check.

Fixes https://github.com/dotnet/runtime/issues/105441#issuecomment-2263537879

### CODE REVIEW

**Review by EgorBo — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
The test build hit that msbuild error, I don't seem to be able to restart it for some reason.

**Comment by AndyAyersMS** [comment]
This is getting a similar looking failure as in https://github.com/dotnet/runtime/issues/105441 -- not surprising since the bug is in the 9p6 runtime jit.

We will need to modify the test script for crossgen2 to run against live runtime. May not be simple if crossgen2 really needs the capabilities of a full runtime host, though I believe it will run ok with corerun as host.
```
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/JIT/opt/JIT.opt/switchWithSideEffects.dll.rsp  
Unhandled exception. ILCompiler.CodeGenerationFailedException: Code generation failed for method '[switchWithSideEffects]SwitchWithSideEffects.Method12(S2&,float32&,S2&,uint32,S1,int64&,int64&,S1,S2&)'
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Internal.JitInterface.CorInfoImpl._beginInlining(IntPtr thisHandle, IntPtr* ppException, CORINFO_METHOD_STRUCT_* inlinerHnd, CORINFO_METHOD_STRUCT_* inlineeHnd) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl_generated.cs:line 154
   --- End of inner exception stack trace -
```

**Comment by EgorBo** [comment]
> We will need to modify the test script for crossgen2 to run against live runtime. May not be simple if crossgen2 really needs the capabilities of a full runtime host, though I believe it will run ok with corerun as host.

I think it should be simple enough for it to be built with live NativeAOT, perhaps @MichalStrehovsky @jkotas know how?

**Comment by jkotas** [comment]
> I think it should be simple enough for it to be built with live NativeAOT, perhaps @MichalStrehovsky @jkotas know how?

The shipping crossgen2 binary is built with live built native AOT. Switching crossgen2 tests to use that would require a bunch of yaml and test script changes. It may also require some extra work to mitigate the throughput impact - checked crossgen2 running on release runtime may be a lot faster than checked crossgen2 runtime on checked live-built runtime.

**Comment by jkotas** [comment]
There is a good chance that the bug does not repro in native AOT version of crossgen2. The act of switching to native AOT can make the bug to go away and we would not be able to tell whether the bug is fixed by running crossgen2.

If we are just looking for workarounds, the easiest workaround may be enabled tiered compilation for crossgen2.

**Comment by jakobbotsch** [comment]
> This is getting a similar looking failure as in #105441 -- not surprising since the bug is in the 9p6 runtime jit.

Right...

I was definitely hoping for a simple way to validate that this fixes the problem, but looks like that may be hard. I'll see if I can repro the bug on my M1 with a decently high frequency and validate it manually.

**Comment by jakobbotsch** [comment]
Haven't been able to validate the fix on my M1 -- I haven't seen a repro of the original problem on it.

Anyway, the dumps over in #105827 definitely show that the array field is null right after initialization, so it seems very likely for this to be the issue, and for now we can probably take it on faith that it solves the original problem.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

**Review by AndyAyersMS — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
> > We will need to modify the test script for crossgen2 to run against live runtime. May not be simple if crossgen2 really needs the capabilities of a full runtime host, though I believe it will run ok with corerun as host.
> 
> I think it should be simple enough for it to be built with live NativeAOT, perhaps @MichalStrehovsky @jkotas know how?

If you want to use the same nativeAOT-compiled crossgen2 in testing that we ship in nugets, that's a hard fix, https://github.com/dotnet/runtime/pull/80154 has been trying to do that for a long time.

**Pull request merged**
