### PR TITLE
Consolidate .netcoreapp.cs test files in System.Diagnostics.*

### PR DESCRIPTION
**Pull request by Marusyk**
Contributes dotnet/corefx#41821

Please review
Thank you in advance

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by Marusyk** [comment]
How to fix CI?

**Comment by jkotas** [comment]
`CoreCLR Pri0 Test Run Windows_NT arm checked` failure is known issue https://github.com/dotnet/runtime/issues/1097

**Pull request merged**
