### PR TITLE
Use x64 `msbuild` executable

### PR DESCRIPTION
**Pull request by dougbu**
- do not merge unless we know this is coming in an Arcade update

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Hey @dougbu, what is this about? We aren't using the global msbuild much except for the runtime and the native libraries.

**Comment by tannergooding** [comment]
I believe this will also be problematic for ARM64 devices where they can largely build using the x86 emulation layer which is 32-bit only

**Comment by dougbu** [comment]
This was an experiment.

@rainersigwald suggested the x64 copy of `msbuild` might avoid OOM errors we've seen in dotnet/aspnetcore and I looked to see if it would cause problems if applied everywhere. My experiment in dotnet/aspnetcore#22019 went well, including Windows ARM and ARM64 builds but we set `$(TargetArchitecture)` instead of running on ARM or ARM64 machines (except in Helix runs). The runs I did here only indicate flakiness on non-Windows platforms and a weird timeout while downloading artifacts in the second run.

Given the pushback here and only If this turned into anything real, it would be behind an Arcade opt-in switch.

**Pull request closed without merging**
