### PR TITLE
Remove getFieldAddress

### PR DESCRIPTION
**Pull request by EgorBo**
Reverts part of the https://github.com/dotnet/runtime/pull/78296 to drop `getFieldAddress` API

### CODE REVIEW

**Comment by EgorBo** [comment]
@jkotas can you please review the VM side? I've extracted only the part where we delete `getFieldAddress` API that doesn't throw any NRE (I had 4 runs of CI here without it + local runs). I'll investigate the NRE + Frozen statics separately. This PR should also unblock NativeAOT work for static fields.

**Review by jkotas — APPROVED** [review]
LGTM

**Review by SingleAccretion — APPROVED** [review]
Jit changes still look good.

**Comment by EgorBo** [comment]
Failures are:
Runtime_76194 - https://github.com/dotnet/runtime/issues/78758
Runtime_31615 - filed https://github.com/dotnet/runtime/issues/79170
jitstress is pretty broken - https://github.com/dotnet/runtime/issues/79132#issuecomment-1335574228

**Pull request merged**
