### PR TITLE
Fold primitive-typed access to promoted structs in local morph and forbid mismatched struct assignments

### PR DESCRIPTION
**Pull request by SingleAccretion**
Two changes:
1) Do not create invalid IR in the form of `ASG(struct, primitive)` in `fgMorphStructField`. This leads to some improvements (as well as regressions) due to us now being able to forward-substitute more things. It also decouples the replacement logic from `lvFieldHnd`, making it unnecessary. This shrinks the size of `LclVarDsc` from 104 to 96 bytes on x64, resulting in `~0.35%` memory consumption reduction (for optimized code), and a TP loss because more instructions are used by MSVC to perform pointer arithmetic on `LclVarDsc*`s.
2) Allow folding access to promoted locals in local morph. This results in a few regressions that were fixed by teaching `fgMorphStructField` to work with `IND`-based access. The alternative of moving the whole logic to post-order was explored, but ultimately discarded due to it being more complex.

As of this change, it will be the case that the two sides of a struct assignment will always agree on types, for which a special assert has been added. This will render most of `fgMorphBlockOperand` unnecessary, but deleting will have to wait till #76745 is in.

We are expecting overall good diffs, most of the regressions are associated with more substitutions. There are also two cases in test code where the new logic is more conservative for `RETURN`s, but it does not seem worth the code to fix them (by propagating the quirked `RETURN` handling into local morph).

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
@jakobbotsch can you take a look at this one?

**Review by jakobbotsch — APPROVED** [review]
LGTM. Will rerun the CI.

**Comment by jakobbotsch** [comment]
Nice cleanup, thanks again!

**Pull request merged**
