### PR TITLE
Delete typeof caches from CoreCLR CoreLib

### PR DESCRIPTION
**Pull request by jkotas**
Caching typeof is a de-optimization with frozen runtime types

### CODE REVIEW

**Comment by EgorBo** [comment]
> de-optimization

Technically, should not be any difference I assume (well, for fully initialized code), should it? - it used to be but I fixed that in my PR

**Review by EgorBo — APPROVED** [review]

**Comment by EgorBo** [comment]
Example:
```csharp
class Program
{
    static void Main(string[] args)
    {
        for (int i = 0; i < 100; i++)
        {
            Foo(typeof(bool));
            Thread.Sleep(16);
        }
    }

    static readonly Type BooleanType = typeof(bool);

    [MethodImpl(MethodImplOptions.NoInlining)]
    static bool Foo(Type type) => type == BooleanType;
}
```
Tier1 codegen for `Foo`:
```asm
; Assembly listing for method ConsoleApp1.Program:Foo(System.Type):bool
; Tier-1 compilation
G_M31357_IG01:              ;; offset=0000H
G_M31357_IG02:              ;; offset=0000H
       48B89017170AFE010000 mov      rax, 0x1FE0A171790      ; 'System.Boolean'
       483BC8               cmp      rcx, rax
       0F94C0               sete     al
       0FB6C0               movzx    rax, al
G_M31357_IG03:              ;; offset=0013H
       C3                   ret  
```

**Comment by jkotas** [comment]
> Technically, should not be any difference I assume (well, for fully initialized code), should it?

Right, it does not make any difference for the Tier1 code, but the fields still take space in the image, need to be inflated by the type loader, etc.

**Comment by jkotas** [comment]
All Known test errors according to the Build Analysis.

**Pull request merged**
