### PR TITLE
Support `PUTARG_STK(STRUCT LCL_VAR/LCL_FLD)` on ARM/64

### PR DESCRIPTION
**Pull request by SingleAccretion**
For now, transform `OBJ`s of the corresponding shape in lowering. This is not the place to do that, but that is the price we have to pay for rolling out support incrementally.

Small positive diffs on ARM due to supporting `LCL_FLD` as well as `LCL_VAR`, also a couple regressions from what looks like larger encodings. Also some small TP win on XARCH because we no longer enumerate the args separately for `LowerPutArgStk`.

[Diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1807811&view=ms.vss-build-web.run-extensions-tab).

Contributes to #11057.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Why are the arm64 diffs zero size? Is there a GC info diff?

**Comment by SingleAccretion** [comment]
> Why are the arm64 diffs zero size?

Good question. I believe it is simply because the scenario where we are expect diffs (local struct fields put on stack) is rare on ARM64 because:
1) Struct fields themselves are not especially common.
2) On ARM64 we have a large number of argument registers.
3) We only pass 9-16 byte structs using `PUTARG_STK`.

On ARM we have both fewer (+smaller) argument registers and all structs are passed by value, so we see more diffs.

> Is there a GC info diff?

Yep. In the (only) ARM64 case we no longer report a local address as byref (which I believe is what we want to happen):
```diff
-            add     x1, fp, #20
-            ; byrRegs +[x1]
-            ldp     x2, x3, [x1]
-            stp     x2, x3, [sp,#24]
+            add     xip1, fp, #20 // Using the reserved register for the address
+            ldp     x1, x2, [xip1]
+            stp     x1, x2, [sp,#24]
             mov     w1, #1
-            ; byrRegs -[x1]
```

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
