### PR TITLE
Add more optimizations for (https://github.com/dotnet/runtime/issues/61412)

### LINKED ISSUE #61412: JIT: Optimize "X & 1 == 0" to "X & 1"
```csharp
static bool Test(int x) => (x & 1) == 0;
```
Just a good first issue for anyone interested in contributing to CLR JIT.

Current codegen:
```asm
test     cl, 1
sete     al
movzx    rax, al
ret
```
Expected codegen:
```asm
mov      eax, ecx
and      eax, 1
ret
```
I noticed it when I was trying to implement a faster IsNegative for floats:
```csharp
static bool IsNegative(double x) => 
    (Sse2.MoveMask(Vector128.CreateScalarUnsafe(x)) & 1) != 0;
```

### PR DESCRIPTION
**Pull request by En3Tho**
Closes https://github.com/dotnet/runtime/issues/61412
Enhances https://github.com/dotnet/runtime/pull/73120 with (X & 1) == 0 to ((NOT X) & 1) in addition to (X & 1) != 0 to (X & 1)

Cases of == 1 and != 1 are supported too, https://github.com/dotnet/runtime/pull/73120 transforms them to 0 comparisons

Please correct me as I'm a newbie.

### CODE REVIEW

**Comment by En3Tho** [comment]
I guess https://github.com/dotnet/runtime/pull/73120 already covers this

**Comment by En3Tho** [comment]
Build failures look more like a ci problem

**Comment by En3Tho** [comment]
Merged main.
This enhances https://github.com/dotnet/runtime/pull/73120 with (X & 1) == 0 to ((NOT X) & 1) in addition to (X & 1) != 0 to (X & 1)

**Comment by En3Tho** [comment]
@jit-contrib Sorry to ping but can someone review this?

**Review by EgorBo — APPROVED** [review]
LGTM, the optimization seems to be quite conservatives around surroundings but it was like that before your changes.

**Comment by AndyAyersMS** [comment]
Any idea why we don't see arm64 diffs? Is this handled already there?

**Comment by En3Tho** [comment]
I guess because of this check? Can't say for sure

``` cpp
GenTree* Lowering::OptimizeConstCompare(GenTree* cmp)
{
    assert(cmp->gtGetOp2()->IsIntegralConst());

#if defined(TARGET_XARCH) || defined(TARGET_ARM64)
    GenTree*       op1      = cmp->gtGetOp1();
    GenTreeIntCon* op2      = cmp->gtGetOp2()->AsIntCon();
    ssize_t        op2Value = op2->IconValue();

#ifdef TARGET_ARM64
    // Do not optimise further if op1 has a contained chain.
    if (op1->OperIs(GT_AND) &&
        (op1->gtGetOp1()->isContainedAndNotIntOrIImmed() || op1->gtGetOp2()->isContainedAndNotIntOrIImmed()))
    {
        return cmp;
    }
#endif
///...
```

**Comment by EgorBo** [comment]
@En3Tho oh, interesting, if you want you can remove that ifdef so we can see SPMI diffs on Ci as part of this PR

**Comment by En3Tho** [comment]
@EgorBo Sure. Let's see what will break :D

**Comment by En3Tho** [comment]
Failure is https://github.com/dotnet/runtime/issues/76041 . I'm not sure what those Push work item to Helix failures mean. Is that a pure ci problem?

**Comment by EgorBo** [comment]
@En3Tho thanks!

**Pull request merged**
