### PR TITLE
Add cecil as a dependency of the runtime

### PR DESCRIPTION
**Pull request by tlakollo**
Add cecil as a dependency of the runtime
Enables the subscription

### CODE REVIEW

**Review by jkoritzinsky — COMMENTED** [review]
I think you might need to run `darc update-dependencies --source-repo https://github.com/dotnet/cecil` to get the version info in here.

Also, can you put the info in Versions.props into the super large `<PropertyGroup>` at the bottom next to the `<StaticCsVersion>` item with a comment above it stating which repo it's from (the extra line ends up significantly reducing merge conflicts)?

**Comment by kasperk81** [comment]
why is cecil needed when there is a managed typesystem with dependency analysis available for production use?

**Review by jkoritzinsky — APPROVED** [review]

**Review by agocke — APPROVED** [review]
LGTM

**Comment by ericstj** [comment]
Why add a dependency that is not consumed anywhere?  All this does is create a property that's not used and can get out of sync, and potential churn to the repo in PRs to update that property.  Can you wait to make this change until you consume that property?

**Comment by tlakollo** [comment]
> Why add a dependency that is not consumed anywhere? All this does is create a property that's not used and can get out of sync, and churns the repo in PRs to update that property. Can you wait to make this change until you consume that property?

Yes, so far Im prototyping how this would work with consuming the cecil package in https://github.com/dotnet/runtime/pull/77149. Not sure if just mark it as NO-MERGE or just close this PR

**Comment by joperezr** [comment]
It's usually best to keep the PR as a draft PR and to have the no-review and no-merge labels if we are not intending to merge this. Otherwise, people might come to the PR, see that it is approved and green, and might just merge it.

**Comment by tlakollo** [comment]
Closing this since https://github.com/dotnet/runtime/pull/78077 got merged

**Pull request closed without merging**
