### PR TITLE
Call SetupNuGetSources for installer jobs

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Review by hoyosjs — APPROVED** [review]

**Comment by carlossanlop** [comment]
@mmitche did you intend to send this to release/8.0 (RC2) instead of release/8.0-rc1? Do we want it in the RC1 branch too or not?

**Comment by mmitche** [comment]
This is the rc1 branch.  I did that one first just to unblock us faster.

**Comment by carlossanlop** [comment]
You're right, my apologies, I got confused. Too many tabs open.

**Pull request merged**
