### PR TITLE
[release/6.0] ComponentModel threading fixes

### PR DESCRIPTION
**Pull request by steveharter**
Backport of #104407 and #103835 to release/6.0.

See also https://github.com/dotnet/runtime/pull/107353 for the 8.0 port.

## Customer Impact
Fixes various threading issues with TypeDescriptor and PropertyDescriptor.

## Regression
Yes; a [previous servicing fix](https://github.com/dotnet/runtime/pull/101306) caused concurrency issues with:
- Dictionary\hashtable concurrency issues reported in https://github.com/dotnet/runtime/issues/104221 and https://github.com/dotnet/runtime/issues/103823 and this port addresses those by using `ConcurrentDictionary`.
- A rare deadlock could occur as reported in https://github.com/dotnet/runtime/issues/103265.

## Testing
The 9.0 tests that were added are ported here.

## Risk
Low; the fixes have been in 9.0 for several months with no reported regressions.

### CODE REVIEW

**Comment by carlossanlop** [comment]
Friendly reminder that Code Complete for the October Release is September 9. If we want this fix to be included in that release, please merge this PR _before_ that date.

**Review by buyaa-n — APPROVED** [review]

**Review by buyaa-n — APPROVED** [review]

**Comment by carlossanlop** [comment]
There were many unknown/new failures in this PR. are any of them known? Maybe re-run could clean them up?

**Comment by steveharter** [comment]
> There were many unknown/new failures in this PR. are any of them known? Maybe re-run could clean them up?

A re-run didn't help. The bulk are linux. Also, this other PR has more or less the same failures: https://github.com/dotnet/runtime/pull/106220

**Pull request merged**
