### PR TITLE
[zlib] Bump to upstream 1.2.12

### PR DESCRIPTION
**Pull request by lambdageek**
Also cherrypick madler/zlib@ec3df00 to restore pre-1.2.12 behavior:

> The previous releases of zlib were not sensitive to incorrect CRC
> inputs with bits set above the low 32. This commit restores that
> behavior, so that applications with such bugs will continue to
> operate as before.

Also bump zlib-intel to https://github.com/jtkukunas/zlib/tree/v1.2.12_jtk and cherrypick vanilla zlib crc32 fix (above) tozlib-intel.

### CODE REVIEW

**Comment by lambdageek** [comment]
Do we have a way of keeping track of patches we apply to zlib?

Should we just wait for 1.2.12.1?

**Comment by jkotas** [comment]
> Do we have a way of keeping track of patches we apply to zlib?

Looks for the .txt files under https://github.com/dotnet/runtime/tree/main/src/native/external

**Comment by am11** [comment]
Thanks! Yes the -version.txt files helps during such upgrades.

The build errors are upstream issue: https://github.com/madler/zlib/issues/633. We can workaround it (by explicitly adding prototypes in zlib.h) or wait until it is properly fixed in upstream.

Note that in libraries, we use this zlib on Windows arm{64} and zlib-intel on Windows x{86,64}. Could you please try to collect some numbers from https://github.com/dotnet/performance/pull/2152 on Windows arm64 system?

ps - I think plan is to try to replace both implementations with a single copy of nextgen https://github.com/zlib-ng/zlib-ng (which apparently captures optimizations from other two variants and add SIMD sauce on top), validate the performance impact on supported platforms and then switch all platforms to that (currently on Unix `libSystem.IO.Compression.Native` is linked with system libz; in contrast, brotli is compiled with in-tree sources).

**Comment by lambdageek** [comment]
> The build errors are upstream issue: https://github.com/madler/zlib/issues/633. We can workaround it (by explicitly adding prototypes in zlib.h) or wait until it is properly fixed in upstream.

I think I'd prefer waiting until it's fixed properly.   1.2.12 seems not fully ready, to be honest. I think a 1.2.12.1 release is probably imminent.

**Comment by lambdageek** [comment]
Turned off warnings as errors for `-Wstrict-prototypes` for the zlib sources.

Bumped zlib-intel to v1.2.12_jtk  and also cherrypicked the vanilla zlib crc32 fix to zlib-intel (it applied cleanly).

**Comment by lambdageek** [comment]
32-bit Windows builds are unhappy because of https://github.com/madler/zlib/issues/631#issuecomment-1097019261

**Comment by cmoaciopm** [comment]
Latest dotnet runtime 6 is 6.0.5 currently. Can I expect to get zlib bumped to 1.2.12 in coming 6.0.6 release?

**Comment by AraHaan** [comment]
So, zlib 1.2.12 was recently tagged in madler/zlib and might have other changes as well,

Also it would be nice if System.IO.Compression.Native exported all of the symbols that the regular zlib library exports as well because technically I have manual code that needs it and trying to figure out making a nuget package for the native zlib myself for:

- win-x86
- win-x64
- win-arm64
- linux-x64
- linux-arm
- linux-arm64
- all of linux-musl and linux-rhel's that .NET supports
- osx-x64
- osx-arm64

While it might be possible, it is more of a pain than what it is worth and I feel simply adding all the exports that zlib.def (and the other export files from madler/zlib would be the best option. Yeah it might add exports not used by dotnet/runtime but it allows code outside of dotnet/runtime to P/Invoke those to get the best performant options of:

- crc32
- adler32
- etc.

Those exports could be renamed to ``[export symbol]_zlib`` for the original exports that would normally be exported from ``zlib.dll`` (or ``zlibwapi.dll`` or ``zlib1.dll``), ``libzlib.so``, or even ``libzlib.dylib``. It would be better for a lot of developers this way as well too.

**Pull request closed without merging**
