### PR TITLE
Update missing runtime/framework install URL to use host RID

### LINKED ISSUE #88223: missing runtime link using old RIDs
RID doesn't match for `dotnet --info` and the install link. They should.

```bash
$ dotnet --info | head -n 10
.NET SDK:
 Version:   8.0.100-preview.5.23303.2
 Commit:    3fe444af72

Runtime Environment:
 OS Name:     debian
 OS Version:  12
 OS Platform: Linux
 RID:         linux-arm64
 Base Path:   /usr/share/dotnet/sdk/8.0.100-preview.5.23303.2/
$ bin/Debug/netcoreapp3.1/dotnet-runtimeinfo
You must install or update .NET to run this application.

App: /app/bin/Debug/netcoreapp3.1/dotnet-runtimeinfo
Architecture: arm64
Framework: 'Microsoft.NETCore.App', version '3.1.0' (arm64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  8.0.0-preview.5.23280.8 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn more:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=arm64&rid=debian.12-arm64
```

Ideally, this link would be like this:

```
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=arm64&rid=linux-arm64&os=debian.12
```

That way, we could: 

- For the general case, link to: https://learn.microsoft.com/en-us/dotnet/core/install/linux
- For specific distros, link to (for example): https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian

@elinor-fung

### PR DESCRIPTION
**Pull request by elinor-fung**
Update the install URL to use the host RID instead of the computed current RID.

Examples:
```
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=linux-x64&os=ubuntu.22.04&apphost_version=8.0.0-dev
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win-x64&os=win10&apphost_version=8.0.0-dev

https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=linux-x64&os=ubuntu.22.04
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=7.0.0&arch=x64&rid=win-x64&os=win10
```

cc @richlander

Fixes https://github.com/dotnet/runtime/issues/88223

### CODE REVIEW

**Comment by richlander** [comment]
Thanks! That looks really nice!

@mairaw

**Comment by richlander** [comment]
It also occurs to me that we could use this opportunity to simplify the link. How about:

https://aka.ms/dotnet/download

That link already exists and we can just further specialize its behavior.

**Comment by elinor-fung** [comment]
> It also occurs to me that we could use this opportunity to simplify the link. How about:
> 
> https://aka.ms/dotnet/download
> 
> That link already exists and we can just further specialize its behavior.

I'll defer to you and @mairaw on what a simpler base link should be. My only concerns are:
1. We don't regress the current behaviour - so we have the redirection/specialization working for the link before making the host use the different URL.
2. Do we care about differentiating an app launch failure directing someone to download versus a 'normal' aka.ms/dotnet/download? I was under the impression that was part of the reason for having a different URL for app launch.

**Comment by richlander** [comment]
Notice that these two links end up at the same place:

- https://aka.ms/dotnet-core-applaunch
- https://aka.ms/dotnet/download

I can easily point the latter link to point to the same place as the former. I own both links.

If we make this change, we should also change this link to match.

```bash
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
```

We could change that to:

https://aka.ms/dotnet/app/failed

I have two goals here:

- Switch to more memorable and human-centric terms.
- Switch to slashes, which we use elsewhere and are more natural for URLs.

**Review by vitek-karas — APPROVED** [review]

**Comment by elinor-fung** [comment]
> It also occurs to me that we could use this opportunity to simplify the link. How about:
> 
> https://aka.ms/dotnet/download
> 
> That link already exists and we can just further specialize its behavior.

Separated that out as:
- https://github.com/dotnet/runtime/issues/89034

**Pull request merged**
