### PR TITLE
Reduce CoreCLR PAL

### PR DESCRIPTION
**Pull request by janvorli**
I have discovered some unused functions in the coreclr PAL. So I have removed it from the PAL and also removed some unused stuf from the coreclr that I have found along the way.
I have also replace the `DeleteFile` by standard `remove` function.
The `CreatePipe` is not used by any code using the PAL except for the PAL tests. But I had to keep it to 
preserve `CreateProcess` tests without refactoring. So I have at least removed it from the pal.h to prevent future usage.
I have also modified couple of PAL tests to get rid of `SetEndOfFile` API usage that was removed for tests where it made sense to preserve them.

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thanks!

**Review by AaronRobinsonMSFT — APPROVED** [review]
:shipit:

**Comment by jkotas** [comment]
This introduced a build break in Mono:
```
2022-10-11T04:38:50.1127810Z   [ 87%] Building CXX object dlls/mscordbi/utilcode/CMakeFiles/utilcode_obj.dir/clrhost_nodependencies.cpp.o
2022-10-11T04:38:50.1205136Z   /__w/1/s/src/mono/dlls/dbgshim/dbgshim.cpp:122:9: error: use of undeclared identifier '_putenv'
2022-10-11T04:38:50.1207257Z           putenv("MONO_ENV_OPTIONS='--debugger-agent=transport=dt_socket,address=127.0.0.1:pid_based,server=n,suspend=y,loglevel=10,timeout=100000'");
2022-10-11T04:38:50.1208250Z           ^
2022-10-11T04:38:50.1341137Z   /__w/1/s/src/mono/dlls/dbgshim/dbgshim.cpp:19:16: note: expanded from macro 'putenv'
2022-10-11T04:38:50.1346925Z   #define putenv _putenv
2022-10-11T04:38:50.1358557Z                  ^
```
I am going to revert this PR.

**Comment by vargaz** [comment]
Why didn't CI pick up the build breakage ?

**Comment by am11** [comment]
@vargaz, the change path evaluation (responsible for triggering CI legs) is missing `src/coreclr/pal` and `src/coreclr/utilcode` from: https://github.com/dotnet/runtime/blob/3435b39194137676d9b2da12c8ebd21d69cd06b9/eng/pipelines/common/evaluate-default-paths.yml#L61-L62

Since mono desktop depend on coreclr PAL (for corehost), I think we should add those paths in the list which affects mono.

Docs:
https://github.com/dotnet/runtime/blob/3435b39194137676d9b2da12c8ebd21d69cd06b9/eng/pipelines/evaluate-changed-paths.sh#L1-L18

cc @akoeplinger

**Comment by janvorli** [comment]
Ouch, I had no idea that anything in mono uses coreclr PAL.

**Comment by AaronRobinsonMSFT** [comment]
> Ouch, I had no idea that anything in mono uses coreclr PAL.

Agreed. That seems wrong. Shared code really needs to be moved up to `src/native`.

@jkotas Was it just `putenv` or did you find others?

**Comment by jkotas** [comment]
> That seems wrong. Shared code really needs to be moved up to src/native.

I think there is larger problem with how the ICorDebug Mono implementation is factored. The first questions to ask would be where it is used and how it is tested and where we want to move it going forward, and only then worry about mechanics.

> Was it just putenv or did you find others?

The build break error was just about putenv, but I do not know whether there is more hiding behind it.

**Comment by janvorli** [comment]
I'll try to build Mono and see if anything else breaks. The `_putenv` is cheap to put back for now as it is just a thin wrapper around `EnvironPutenv` that is used at few other places.

**Comment by akoeplinger** [comment]
@janvorli you need to build the `mono.mscordbi` subset.

**Comment by janvorli** [comment]
@akoeplinger I have tried that too before and it succeeded. However, it seems it doesn't build anything native. I've even tried a clean build.

**Pull request merged**
