### PR TITLE
Exclude tests for Apple platforms on hybrid mode

### PR DESCRIPTION
**Pull request by mkhamoyan**
After https://github.com/dotnet/runtime/pull/97299 , ICU specific tests started to fail on Apple platforms for HybridGlobalization.

- `IgnoreSymbols` is not supported in `HybridGlobalization` for Apple platforms , exclude this test case.
- Mark as ActiveIssue https://github.com/dotnet/runtime/issues/95338 `HashCode` related failures.

### CODE REVIEW

**Review by ilonatommy — APPROVED** [review]
`IgnoreSymbols` is not a supported option on iOS, approving

**Comment by mkhamoyan** [comment]
Failures are not related.

**Pull request merged**
