### PR TITLE
Try getting a crashdump for #70010

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Hangs don't produce crashdumps in Helix.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Wat?

```
[SKIP] System.Tests.EnumTests.IsDefined_InvokeBoolEnum_ReturnsExpected
/root/helix/work/workitem/e
----- end Fri Jun 24 02:39:37 UTC 2022 ----- exit code 124 ----------------------------------------------------------
Waiting a few seconds for any dump to be written..
cat /proc/sys/kernel/core_pattern: /home/helixbot/dotnetbuild/dumps/core.%u.%p
cat /proc/sys/kernel/core_uses_pid: 0
cat: /proc/sys/kernel/coredump_filter: No such file or directory
cat /proc/sys/kernel/coredump_filter:
Looking around for any Linux dump..
... found no dump in /root/helix/work/workitem/e
```

**Comment by MichalStrehovsky** [comment]
@dotnet/runtime-infrastructure anyone knows if there was a change in how we collect coredumps in Helix?

The CI run for a3731bb failed but no crashdump was found by the RunnerTemplate.sh script and no crashdump is attached to the test result either:

https://dev.azure.com/dnceng/public/_build/results?buildId=1842929&view=ms.vss-test-web.build-test-results-tab&runId=48641322&resultId=109560&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

I then made a hacky change in RunnerTemplate.sh (last 3 commits) to look for crashdumps in one more location and changed things up to reliably crash. The test results now have a crashdump attached in the latest run.

Looks like Helix decided to place crashdumps where we don't expect them?

**Comment by hoyosjs** [comment]
There's a dump file: 

```log
2022-06-24T02:40:21.393Z	INFO   	executor(767)	_dump_file_upload	Dump files created in /home/helixbot/dotnetbuild/dumps are ready to be uploaded
2022-06-24T02:40:21.395Z	INFO   	executor(780)	_dump_file_upload	Dump file: /home/helixbot/dotnetbuild/dumps/core.1001.26, size: 16384
2022-06-24T02:40:21.396Z	INFO   	executor(802)	_dump_file_upload	Copying...
2022-06-24T02:40:21.397Z	INFO   	executor(805)	_dump_file_upload	Copy successful.
```

The upload should happen as long as it's in the helix crashdump dir, and as far as I know, the filter, the ulimit, and the pattern are all set to point to the right place. Not sure why they didn't get correlated - I saw this:

```
20042527	a57bb04e-656d-4a0f-b8b1-62cbad26c824	992768133	f41c866a-7934-4a15-b51d-c92be056f055	System.Runtime.Tests	1	16179137951	https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71177-merge-a57bb04e656d4a0fb8/System.Runtime.Tests/1/core.1001.26?helixlogtype=result	core.1001.26	47	203829248	1	2022-06-24T06:25:10.066Z	203829248
```

@dotnet/dnceng, any ideas why the dump wasn't correlated to the workitem?

**Comment by alexperovich** [comment]
If you look a bit farther in the logs it shows this:
```
2022-06-24T02:40:21.400Z	INFO   	executor(963)	_upload_files	Uploading file core.1001.26...
2022-06-24T02:40:21.401Z	WARNING	executor(908)	_upload_single_file	File core.1001.26 is empty, skipping upload
2022-06-24T02:40:21.401Z	INFO   	executor(963)	_upload_files	Uploading file how-to-debug-dump.md...
2022-06-24T02:40:21.402Z	INFO   	executor(920)	_upload_single_file	Uploading the file how-to-debug-dump.md
```

It skipped upload of that file because it appeared to be empty. This is strange though as it had a size higher up. I will check things.

**Comment by alexperovich** [comment]
Ahh yes, I know what happened here. That dump file is actually a 0 byte file. The log about the dump file shows its size as `16384` because we force files smaller than that number to be that number for our file discovery code. That helps make our network timeout code not be overly aggressive. Otherwise we would give 100 2 byte files a very small amount of upload time, which would cause timeouts due to network overhead. In this case the actual file was 0 bytes, and os.path.getsize returned 0.

**Comment by hoyosjs** [comment]
Oh, the dump I shared seems to be from this PR but a different run and ironically with the same pids. Entirely possible then, thanks alex.

**Comment by MichalStrehovsky** [comment]
It's odd seeing a 0 byte dump.

What I was working with is this code in RunnerTemplate.sh:

https://github.com/dotnet/runtime/blob/c9f80fdde29c71ac87971383c77a1a5e665fadb9/eng/testing/RunnerTemplate.sh#L213-L228

It's looking for coredumps in current directory.

But per the output of the script:

```
cat /proc/sys/kernel/core_pattern: /home/helixbot/dotnetbuild/dumps/core.%u.%p
```

Coredumps are now placed somewhere under `helixbot/dotnetbuild`.

Once I "fixed" it by hardcoding that, the crasdump was "magically" uploaded.

**Pull request closed without merging**
