### PR TITLE
Remove jit helpers for writing IBC log data

### PR DESCRIPTION
**Pull request by davidwrighton**
We haven't supported IBC data for quite some time now, and these helpers are dead code.

- CORINFO_HELP_BBT_FCN_ENTER
- CORINFO_HELP_RUNTIMEHANDLE_METHOD_LOG
- CORINFO_HELP_RUNTIMEHANDLE_CLASS_LOG

### CODE REVIEW

**Comment by davidwrighton** [comment]
@AaronRobinsonMSFT, could you review the VM side of this change... @BruceForstall could you take a look at the JIT side? I'm pretty sure I cleaned it all up, but I'd prefer someone with more JIT experience to agree.

**Review by AaronRobinsonMSFT — APPROVED** [review]
:shipit:

**Comment by JulieLeeMSFT** [comment]
@AndyAyersMS, PTAL.

**Review by AndyAyersMS — APPROVED** [review]
JIT changes look good.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
