### PR TITLE
[mono] Allow missing assemblies in llvmonly+interp mode.

### PR DESCRIPTION
**Pull request by vargaz**
Part of the fix for https://github.com/dotnet/runtime/issues/51961.

### CODE REVIEW

**Comment by vargaz** [comment]
A downside of this is that it would also ignore issues when there is a mismatch between assemblies and AOT images.

**Comment by directhex** [comment]
Do we want a different approach without that downside? A way to encode a permitted list of missing assemblies, as opposed to just being more chill about them in general?

**Comment by lambdageek** [comment]
> A downside of this is that it would also ignore issues when there is a mismatch between assemblies and AOT images.

Can we raise the log level from these two trace calls to a warning?

https://github.com/dotnet/runtime/blob/33940e671a16ca558cc9d145369e16fd0ae2132e/src/mono/mono/mini/aot-runtime.c#L327-L337

**Comment by vargaz** [comment]
An alternative would be to emit the aot image, but don't actually emit any code in it.

**Review by lewing — APPROVED** [review]
I'm fine with this for now, if there are objections lets discuss them.

**Pull request merged**
