### PR TITLE
Move runtime-coreclr macOS x64 test jobs to 10.14 Helix queue

### PR DESCRIPTION
**Pull request by echesakov**
Move runtime-coreclr macOS x64 test jobs to 10.14 Helix queue (10.13 causes 'No space left on device' issues since their work catalog is mounted to a small disk).

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
@echesakovMSFT can you hold off on the structural changes to helix-queues-setup.yml? I have a change for that that I've been working on stabilizing for the outerloop pipeline in https://github.com/dotnet/runtime/pull/57068

**Comment by echesakovMSFT** [comment]
@jkoritzinsky Sure, I wish I knew about your work 10 minutes ago:)

**Review by jkoritzinsky — APPROVED** [review]

**Pull request merged**
