### PR TITLE
Improves handling of env prefixes containing __

### LINKED ISSUE #65756: Confusing environment variable configuration prefix behaviour reintroduced in 6.0.2
### Description

https://github.com/dotnet/runtime/pull/62819 was merged into 6.0.2 to revert a breaking change in 6.0.0, but the reversion caused a breaking change compared to 6.0.0/6.0.1, by reverting the (good) part of https://github.com/dotnet/runtime/pull/62819.

The current implementation of the `EnvironmentVariablesConfigurationProvider` has undocumented, and in my opinion, rather confusing, behaviour with respect to prefixes containing the string `__`. I would expect for a variable `Prefix__Setting=value` to match against prefix `Prefix__`, and be equivalent to providing `Setting=value`, but this is not the case. At present (6.0.2+), the user must replace `__` with `:` in the prefix in order to match.

For reference, the [current configuration documentation is here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-6.0#environment-variables).

This issue was originally flagged in my comment here: https://github.com/dotnet/runtime/issues/61577#issuecomment-1044959384 - and there have been a few related issues, worth bearing in mind for context:
* https://github.com/dotnet/runtime/issues/40911
* https://github.com/dotnet/runtime/issues/61577

It should be noted that these issues are caused by regressions against existing matches. I believe this issue can be fixed without causing previous matches to fail.

### Reproduction Steps

Using 6.0.2+, the following fails:
```
Environment.SetEnvironmentVariable("MY_PREFIX__ConfigKey, "myFooValue");
var configuration = new ConfigurationBuilder()
    .AddEnvironmentVariables("MY_PREFIX__")
    .Build();

var loadedValue = configuration.GetValue<string?>("ConfigKey", null);

Assert.Equals("myFooValue", loadedValue); // FAILS in 6.0.2 as loadedConfig is null. The prefix of `MY_PREFIX:` needs to be specified instead now
```

### Expected behavior

I would expect that an environment variable `MY_PREFIX__ConfigKey` would match the prefix `MY_PREFIX__`.

The `__` is represented as an entirely safe alternative to `:` in the docs, for the purposes of matching environment variables in an OS-independent manner. I would expect any normalization to `:` for the purpose of matching the prefix to be hidden in the class implementation and not leak into user-facing space.

### Actual behavior

See reproduction steps.

### Regression?

Yes. It worked on 6.0.0 and 6.0.1. Upgrading to 6.0.2 caused the break.

### Known Workarounds

Replace all `__` in the provided prefix with `:` - eg `new ConfigurationBuilder().AddEnvironmentVariables("MY_PREFIX__").Build();` would become `new ConfigurationBuilder().AddEnvironmentVariables("MY_PREFIX:").Build();` 

### Configuration

.NET 6.0.2+, OS: Problem confirmed on MacOS and Linux (various distros).

### Other information

_No response_

### PR DESCRIPTION
**Pull request by dhedey**
This PR is intended to fix #65756.

## Key changes:

* By comparing normalized prefixes to normalized keys, both the un-altered and colon-normalized prefixes match environment variables in either the __ or colon formats.
* There is a change of behaviour that some environment variables which theoretically didn't match the filter before may now match the filter, but I don't expect this to be an issue in practice (I very much doubt anyone configures variables with both a `:` and `__` prefix, and relies on the fact that these don't match)
* I was very careful to ensure other existing behaviour is maintained, to avoid any potential issues such as https://github.com/dotnet/runtime/issues/61577 or any changes of behaviour with the special case connection string matching.

The change includes minor refactors to the EnvironmentVariablesConfigurationProvider to make the code easier to follow and reduce the likelihood of future regressions. Test naming has been made clearer, and a comprehensive test has been added.

If approved for merge into 6.0.x, this would fix the breaking change in 6.0.2 documented in #65756.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=65757) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=65757) before we can accept your contribution.<br/><br/>:x: dhedey [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=65757)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=65757) it.</sub>

**Comment by maryamariyan** [comment]
Thanks for the PR @dhedey.

Does the PR also have a test to cover the regression use case and showing that is not broken with the current PR fix?

**Comment by dhedey** [comment]
Hi @maryamariyan - thanks for taking a look for me :)

Yes, as it happens, this is already covered by the test that was written as part of https://github.com/dotnet/runtime/pull/62819 - in particular `AddEnvironmentVariables_Bind_PrefixShouldNormalize` from this PR has been renamed to [AddEnvironmentVariablesUsingNormalizedPrefix_Bind_PrefixMatches](https://github.com/dhedey/runtime/blob/b8cde5994e981e4f9d87d34d6b34ee5649fc6887/src/libraries/Microsoft.Extensions.Configuration.EnvironmentVariables/tests/EnvironmentVariablesTest.cs#L245) - but the test body is identical:


```
                Environment.SetEnvironmentVariable(EnvironmentVariable, "myFooValue"); // EnvironmentVariable is "Microsoft__Extensions__Configuration__EnvironmentVariables__Test__Foo"
                var configuration = new ConfigurationBuilder()
                    .AddEnvironmentVariables("Microsoft:Extensions:Configuration:EnvironmentVariables:Test:")
                    .Build();

                var settingsWithFoo = new SettingsWithFoo();
                configuration.Bind(settingsWithFoo);

                Assert.Equal("myFooValue", settingsWithFoo.Foo);
```

This checks that an environment variable written in "Linux" mode with `__` can still match a prefix defined in "Windows / normalized" mode with ":", which captures exactly the source of the original regression raised in https://github.com/dotnet/runtime/issues/61577

**Review by halter73 — APPROVED** [review]

**Review by maryamariyan — APPROVED** [review]

**Comment by maryamariyan** [comment]
Thanks @dhedey for the contribution! This should make it to preview 4.
One note of observation for next time, the PR review could be easier if the rename/refactors were separated into their own commit. :)

**Comment by dhedey** [comment]
> Thanks @dhedey for the contribution! This should make it to preview 4. One note of observation for next time, the PR review could be easier if the rename/refactors were separated into their own commit. :)

Many thanks @maryamariyan. Understood - will be sure to separate my commits better next time!

**Comment by ericstj** [comment]
@maryamariyan did you create a breaking change document for this?

**Comment by gewarren** [comment]
@ericstj Yes she did - https://github.com/dotnet/docs/issues/31490.

**Comment by maryamariyan** [comment]
Done. Thanks.

**Pull request merged**
