### PR TITLE
Fixes the comparison to be correct when both numbers are negative

### LINKED ISSUE #49983: Issue : CompareTo of Half type when parameters are negative value
Environment : dotnet core 5.0

Problem is `CompareTo` of Half type when parameters are negative value.
I expect below example result.
```
Half half1 = (Half)(-180f);
Half half2 = (Half)(-180f);

var a1 = half1.Equals(half2); // true
var a2 = half1 == half2; // true
var a3 = half1.CompareTo(half2); // not 0, but -1
```
Why `a3` value is -1? not 0 ?

I follow dotnet core code and find out some strange code.
`Half operator <` that called in `CompareTo` is right   ?
```
public static bool operator <(Half left, Half right)
{
    if (IsNaN(left) || IsNaN(right))
    {
        // IEEE defines that NaN is unordered with respect to everything, including itself.
        return false;
    }

    bool leftIsNegative = IsNegative(left);

    if (leftIsNegative != IsNegative(right))
    {
        // When the signs of left and right differ, we know that left is less than right if it is
        // the negative value. The exception to this is if both values are zero, in which case IEEE
        // says they should be equal, even if the signs differ.
        return leftIsNegative && !AreZero(left, right);
    }
    return (left._value < right._value) ^ leftIsNegative;
}
```
When both left and right is same value of negative, `<` make `-1` to return value.

Thanks to read this issue. Somebody help me :cry:

### PR DESCRIPTION
**Pull request by Marusyk**
Fixes #49983

Still in work

### CODE REVIEW

**Comment by danmoseley** [comment]
Can you please add tests (that fail before the change and pass after)

**Comment by Marusyk** [comment]
I'm sorry, I cannot build the test on my machine. Working on the issue

**Comment by Marusyk** [comment]
No success with building test. I'm going to close the PR

**Comment by danmoseley** [comment]
What issue did you have @Marusyk ? Did the commands in the docs end in an error?

**Comment by pgovind** [comment]
@Marusyk : +1 on telling us the issues you're encountering. For this PR, you should look at the System.Runtime library and add/build the tests under System.Runtime/tests.

**Comment by danmoseley** [comment]
The command I used to build everything from the root is `build clr+libs+libs.tests -rc release -lc checked`. if that doesn't work - my first action is usually to clean everything and rebase on main. It takes 20 mins to build again, but that can be easier than root causing.

Then I go to the ...\tests folder and do `dotnet build /t:buildandtest` and iterate on tests that way. Personally I don't build/test from VS.

This should all be in docs, and I know there's other ways.

**Comment by Marusyk** [comment]
Thank you for your advice. 
It used to be work (a month ago). I followed this guide: https://github.com/dotnet/runtime/blob/main/docs/workflow/building/libraries/README.md

Result of build (not sure that it's helpful):
image

**Comment by pgovind** [comment]
>  it os not only System.Runtime, the Half is in System.Private.CoreLib

Indeed. But the tests for S.P.CoreLib are in System.Runtime. That is what I intended to say. Maybe I should've been more clear :)

I wonder if you are having issues because you don't have `Ninja` installed? Can you check https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/windows-requirements.md#ninja?

**Comment by pgovind** [comment]
OTOH, if this is taking too long to diagnose and you want to get unblocked, you could also consider opening a PR that only adds new Half tests to System.Runtime. You can show that CI is failing currently with those new tests. Then, rebase this PR on top of those tests and show that CI is green?

**Comment by danmoseley** [comment]
You can just use this PR, reopen it and force-push the change you want.

**Comment by Marusyk** [comment]
No, thanks. It is closed. That means I'm not working on this.

**Pull request closed without merging**
