### PR TITLE
[mono] Add direct pinvoke module variations

### PR DESCRIPTION
**Pull request by mdh1418**
Follow up to https://github.com/dotnet/runtime/pull/79721

When specifying `DirectPInvokes`/`DirectPInvokeLists` and `DllImport` modules in the Mono aot compiler, there are no strict limitations on what values can be passed in. Any exact mismatch between `module(!entrypoint)` values passed into `DirectPInvokes`/`DirectPInvokeLists` in the `.csproj` and module/entrypoint values specified in `DllImport` declarations on the managed side will result in undesired behavior.

### MATCH
```
<ItemGroup>
    <DirectPInvokes Include="module!entrypoint" />
</ItemGroup>
--------
[DllImport("module")]
public static extern <ret> entrypoint (<args>);
```

### NO MATCH
```
<ItemGroup>
    <DirectPInvokes Include="libmodule.so!entrypoint" />
</ItemGroup>
--------
[DllImport("module")]
public static extern <ret> entrypoint (<args>);
```

Currently, the mono aot compiler views the above as a mismatch, because the literal values are not equal even though its understood that the module of `libmodule.so` is `module`.

Across all supported platforms and architectures, the shared library prefixes and suffixes vary greatly, leading to a situation where the managed side `DllImport` invocation would need to vary for different platform/architecture.

--------

This PR looks to expand the module/entrypoint pairs added to the aot compiler's [known `direct_pinvokes` hashtable ](https://github.com/dotnet/runtime/blob/ddba2aafec61e780d795775d2bfc0e545964c208/src/mono/mono/mini/aot-compiler.c#L312) that is responsible for filtering which direct pinvokes to generate direct calls for.
More specifically:
- modules passed into `DirectPInvokes` and `DirectPInvokeLists` will be stripped of known shared library prefixes/suffixes, and both the `module/entrypoint` and `stripped module/entrypoint` (if different) will be added to the hashtable for matching.
- modules passed into `DllImport` will no longer by stripped of extensions

Specific cases that may cause problems:
libc.so, libz.so

### CODE REVIEW

**Comment by lateralusX** [comment]
@mdh1418 So thinking some more about this, I'm not sure this is the right approach. What we really would like to handle is the case where unix have dllimport of libMyLibrary and on windows it would be MyLibrary and avoid having to handle duplicate entries in the configurations to support both, but still give the user the power to do soif needed. Maybe a better way would be to support a very basic regexp in module names, like (lib)?MyLibrary ,that would add both libMyLibrary and MyLibrary to the hash table. If user have collisions with two libraries named libMyLibrary and MyLibrary, then he would specify them out like libMyLibrary and not use regexp meaning user is in more control compared to if we added the logic into the AOT compiler.

When we check if a module is part of the direct pinvoke hash table, we should first start using the literal from dllimport, without path (like we currently do) but with any prefix/suffix, if that is not a match, then we strip the suffix and make a search again, if that is not a match, the module is not defined and the dllimport should not be direct pinvoked.

**Comment by lambdageek** [comment]
What does NativeAOT do?

**Comment by lateralusX** [comment]
I had asked the same question to @mdh1418 offline, he will take a look to see. Right now I feel that we could stick to what we have for now and improve if needed later.

**Comment by mdh1418** [comment]
> What does NativeAOT do?

Just looking now at https://github.com/dotnet/runtime/blob/47071da67320985a10f4b70f50f894ab411f4994/src/coreclr/tools/aot/ILCompiler/ConfigurablePInvokePolicy.cs#L81-L133, it looks like they strip the module suffix when generating their map/table of known `module/entrypoint` pairs. Doesn't seem like they do anything to check the prefix atleast from the side of building known map/table of module/etnrypoints. Maybe they have something before building the map/table, I'll have to keep looking, and I'm not exactly sure what they do from the perspective of compiling the managed code's `[DllImport(module)]` side yet, I'll need to find out where that is done for NativeAOT

They also have some sort of Entrypoint variation that we dont have. Is this something we need to implement as well? I'm not familiar with the entrypoint variations.

**Comment by lateralusX** [comment]
> > What does NativeAOT do?
> 
> Just looking now at
> 
> https://github.com/dotnet/runtime/blob/47071da67320985a10f4b70f50f894ab411f4994/src/coreclr/tools/aot/ILCompiler/ConfigurablePInvokePolicy.cs#L81-L133
> 
> , it looks like they strip the module suffix when generating their map/table of known `module/entrypoint` pairs. Doesn't seem like they do anything to check the prefix atleast from the side of building known map/table of module/etnrypoints. Maybe they have something before building the map/table, I'll have to keep looking, and I'm not exactly sure what they do from the perspective of compiling the managed code's `[DllImport(module)]` side yet, I'll need to find out where that is done for NativeAOT
> They also have some sort of Entrypoint variation that we dont have. Is this something we need to implement as well? I'm not familiar with the entrypoint variations.

That is for windows where you can have A or W depending on char set. I think we can add that later, right now we target android/ios, so that is no variations happening there. The module variation seems to match what we currently implemented.

**Pull request closed without merging**
