### PR TITLE
[mono] Add a --path command line argument as an alternative to MONO_P…

### PR DESCRIPTION
**Pull request by vargaz**
…ATH.

Can be specified multiple times.

### CODE REVIEW

**Comment by vargaz** [comment]
An alternative to:
https://github.com/dotnet/runtime/pull/90526

**Review by SamMonoRT — APPROVED** [review]

**Review by kotlarmilos — APPROVED** [review]

**Review by lambdageek — APPROVED** [review]

**Review by rolfbjarne — APPROVED** [review]

**Comment by SamMonoRT** [comment]
Are the failures relevant ?

Can we issue a backport command to 8.0\Rc1 ?

**Comment by kotlarmilos** [comment]
Merged after sync with Zoltan. Next step is to update the Xamarin build. @rolfbjarne Should this be backported to 8.0\rc1?

**Comment by rolfbjarne** [comment]
> Merged after sync with Zoltan. Next step is to update the Xamarin build. @rolfbjarne Should this be backported to 8.0\rc1?

Yes, please!

**Pull request merged**
