### PR TITLE
RID for Exherbo linux

### PR DESCRIPTION
**Pull request by s0dyy**
Hello ;)

I'm the maintainer of dotnet/source-build for the Exherbo linux distribution. I would like to have the RID in Runtime if possible.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47232) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47232) before we can accept your contribution.<br/><br/>:x: s0dyy [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47232)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=47232) it.</sub>

**Comment by s0dyy** [comment]
Any news on this?

**Review by safern — APPROVED** [review]
Changes make sense. 

cc: @ericstj @wfurt

**Comment by wfurt** [comment]
x64 only? https://exherbo.org/docs/multiarch-pr.html

**Comment by s0dyy** [comment]
Yes only x64. I don't think other platforms will be supported in the future.

Thx ;)

**Review by wfurt — APPROVED** [review]
LGTM

**Pull request merged**
