### PR TITLE
Fix SuperFileCheck from failing outerloop

### LINKED ISSUE #88622: CHECK: expected string not found in input
https://dev.azure.com/dnceng-public/public/_build/results?buildId=333311&view=ms.vss-test-web.build-test-results-tab

Numerous failures like the following:
```
07:38:01.038 Running test: JIT/opt/Add/IntAdd/IntAdd.cmd
__tmp0_IntAdd.cs:12:11: error: CHECK: expected string not found in input
// CHECK: Lcl frame size =
          ^
__jit_disasm.out:1:86: note: scanning from here
; Assembly listing for method CodeGenTests.IntAdd:Int8_Add(byte,byte):byte (FullOpts)
                                                                                     ^
__jit_disasm.out:5:9: note: possible intended match here
; rsp based frame
        ^

Input file: __jit_disasm.out
Check file: __tmp0_IntAdd.cs

-dump-input=help explains the following input dump.

Input was:
<<<<<<
            1: ; Assembly listing for method CodeGenTests.IntAdd:Int8_Add(byte,byte):byte (FullOpts) 
check:12'0                                                                                          X error: no match found
            2: ; Emitting BLENDED_CODE for X64 with AVX512 - Windows 
check:12'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            3: ; FullOpts code 
check:12'0     ~~~~~~~~~~~~~~~~
            4: ; optimized code 
check:12'0     ~~~~~~~~~~~~~~~~~
            5: ; rsp based frame 
check:12'0     ~~~~~~~~~~~~~~~~~~
check:12'1             ?          possible intended match
            6: ; partially interruptible 
check:12'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~
            7: ; No PGO data 
check:12'0     ~~~~~~~~~~~~~~
            8:  
check:12'0     ~
            9: G_M000_IG01: ;; offset=0000H 
check:12'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by TIHan**
Resolves: https://github.com/dotnet/runtime/issues/88622

Will need to run outerloop to double check.

### CODE REVIEW

**Comment by TIHan** [comment]
@dotnet/jit-contrib this is ready. The release-outerloop-nightly is failing due to an access-token so I can't be sure it fixes that pipeline.

**Review by markples — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
@TIHan I am seeing odd errors now from file-check tests, might it be this change?

[https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-88749-merge-f99c6104f5a341dc9c/JIT.opt/1/console.c1083330.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-88749-merge-f99c6104f5a341dc9c/JIT.opt/1/console.c1083330.log?helixlogtype=result)

shows the `add` bit is now matching in the symbol table part of the dump:

```C#
        [MethodImpl(MethodImplOptions.NoInlining)]
        static sbyte Int8_Add(sbyte x, sbyte y)
        {
            // X64-NOT: movsx

            // X64:      add
            // X64-NEXT: movsx

            return (sbyte)(x + y);
        }
```

```
__tmp0_IntAdd.cs:18:15: error: X64-NEXT: is not on the line after the previous match
 // X64-NEXT: movsx
              ^
__jit_disasm.out:20:2: note: 'next' match was here
 movsx rax, cl
 ^
__jit_disasm.out:12:74: note: previous match ended here
;# V02 OutArgs [V02 ] ( 1, 1 ) struct ( 0) [rsp+00H] do-not-enreg[XS] addr-exposed "OutgoingArgSpace"
                                                                         ^
__jit_disasm.out:13:1: note: non-matching line after previous match is here
;
^
```

**Comment by markples** [comment]
Yes, this analysis is correct.  By checking for "Lcl frame size" we skip past the preamble.  It turns out that "add" is a fragile pattern.  Maybe something like add .*,.* (with the appropriate filecheck regex wrapping) would suffice.  Better would be a register pattern (looks like the test is trying to not hardcode a specific register), but of course those are annoying to write.  When I played with the large-scale diffing, I introduced a notion of shortcuts so that one could put "reg" in the pattern and have it expanded by the tool to something more complicated.  Theoretically, superfilecheck could do this, but it's kind of a pain and would increase our distance of standard filecheck.

**Comment by markples** [comment]
It looks like the test failure here got lost in all of the other failures.

**Comment by markples** [comment]
I'm on a different schedule and won't be able to see this through until much later, but if there isn't an immediate fix then this should be reverted because it impacts CI itself.  Or maybe a known build error but it seems like it should be fixed rather than labeled.

**Pull request merged**
