### PR TITLE
Fix rethrow to retain stack

### PR DESCRIPTION
**Pull request by JeremyKuhne**
When resolving types we were re-throwing after attempting to get implicit types. Switching to a parameter-less re-throw to ensure that we keep the original stack.

Add a test for roll-forward behavior.

Add a few tests for settings events.

Re-enabling test that appeared to have failed when rerunning under an older framework.

Minor code style fixes.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by JeremyKuhne** [comment]
https://github.com/dotnet/runtime/issues/28833 is the test that is re-enabled.

**Review by maryamariyan — APPROVED** [review]

**Comment by stephentoub** [comment]
@JeremyKuhne, can you rebase to resolve the conflicts?

**Comment by stephentoub** [comment]
@JeremyKuhne, are you planning to finish this?

**Comment by JeremyKuhne** [comment]
@stephentoub Afaik, this is just pending a run that doesn't fall over. If there are actual test failures from my change I'll happily fix them.

**Comment by stephentoub** [comment]
@JeremyKuhne, there are failures here in confguration, e.g
```
  Discovering: System.Configuration.ConfigurationManager.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Configuration.ConfigurationManager.Tests (found 499 of 502 test cases)
  Starting:    System.Configuration.ConfigurationManager.Tests (parallel test collections = on, max threads = 1)
    System.ConfigurationTests.TypeUtilTests.GetType_ConfigurationManagerTypes(typeString: "System.Configuration.UserSettingsGroup, System.Con"..., expectedType: null) [FAIL]
      Assert.Equal() Failure
      Expected: (null)
      Actual:   typeof(System.Configuration.UserSettingsGroup)
      Stack Trace:
        /_/src/libraries/System.Configuration.ConfigurationManager/tests/System/Configuration/TypeUtilTests.cs(59,0): at System.ConfigurationTests.TypeUtilTests.GetType_ConfigurationManagerTypes(String typeString, Type expectedType)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  Finished:    System.Configuration.ConfigurationManager.Tests
```

**Comment by JeremyKuhne** [comment]
> there are failures here in confguration, e.g

Odd. Ok, I'm on it.

**Comment by stephentoub** [comment]
Thanks :)

**Comment by JeremyKuhne** [comment]
A type roll-forward test I added for configuration manager types was failing on Mono. Mono always resolves the type, even if we ask for a future version. I've skipped for Mono for the test for now.

@lambdageek Is this type behavior expected, or do you know who would know? The test ultimately does a `Type.GetType` for `"System.Configuration.UserSettingsGroup, System.Configuration.ConfigurationManager, Version=255.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"`.

**Comment by lambdageek** [comment]
Took me a while to notice this and to understand what goes wrong.  It's because when the test runs it tries to load the assembly twice - once with an older version - which succeeds, and subsequently with a newer version.  Evidently Mono isn't doing a version check when the assembly has already been loaded.  I filed an issue https://github.com/dotnet/runtime/issues/38351

> A type roll-forward test I added for configuration manager types was failing on Mono. Mono always resolves the type, even if we ask for a future version. I've skipped for Mono for the test for now.
> 
> @lambdageek Is this type behavior expected, or do you know who would know? The test ultimately does a `Type.GetType` for `"System.Configuration.UserSettingsGroup, System.Configuration.ConfigurationManager, Version=255.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"`.

**Pull request merged**
