### PR TITLE
Fix nested Multipart when generating MailMessage

### LINKED ISSUE #47379: System.Net.Mail.MailMessage is recreating a Mixed MimeMultiPart where it shouldn't
### Description

I was currently working on a project where I have to create a `MailMessage` with the following structure :

 - Mixed
    - Alternative
       - HTML
       - ICS
    - Attachment 1
    - Attachment 2

But the current implementation of the method `SetContent(bool)` in the class `System.Net.Mail.MailMessage` is resolving the structure the following way:

 - Mixed
    - Alternative
       - HTML
       - ICS
    - Mixed
       - Attachment 1
       - Attachment 2

_Effect of the issue on real mail clients :_ This behavior prevents Outlook clients to handle the ICS invitation properly, and they simply drop it (thus not displaying the calendar invitation if any attachment is added). Gmail, on the other hand, is able to handle the nested Mixed structure.

### Configuration

 - Dotnet Core 5.0.102 / Runtime 5.0.2
 - Reproduced on Windows and Linux
 - Tested on x64 only

### Other information

This behavior can probably be fixed with the following modification of the method. If you switch this block :

```cs
if (Attachments.Count > 0)
{
    part = new MimeMultiPart(MimeMultiPartType.Mixed);
    part.Parts.Add(viewsPart);

    MimeMultiPart attachmentsPart = new MimeMultiPart(MimeMultiPartType.Mixed);
    foreach (Attachment attachment in Attachments)
    {
        if (attachment != null)
        {
            attachment.PrepareForSending(allowUnicode);
            attachmentsPart.Parts.Add(attachment.MimePart);
        }
    }
    part.Parts.Add(attachmentsPart);
    _message.Content = part;
}
```

to this block :

```cs
if (Attachments.Count > 0)
{
    part = new MimeMultiPart(MimeMultiPartType.Mixed);
    part.Parts.Add(viewsPart);

    foreach (Attachment attachment in Attachments)
    {
        if (attachment != null)
        {
            attachment.PrepareForSending(allowUnicode);
            part.Parts.Add(attachment.MimePart);
        }
    }
    _message.Content = part;
}
```

It will flatten the nested mixed structure and would probably fix this issue, making the output Outlook-friendly.

### PR DESCRIPTION
**Pull request by ghost**
When sending a mail with alternate views and attachments, attachments were nested a second time. Doing so made the generated mail unintelligible for some clients (Like Outlook).

Fix dotnet#47379

### CODE REVIEW

**Review by filipnavara — APPROVED** [review]

**Review by karelz — APPROVED** [review]

**Comment by wfurt** [comment]
should we add some test?

**Comment by karelz** [comment]
@Elyhaka would you be able to add a test as @wfurt suggested above?

**Comment by karelz** [comment]
@Elyhaka ping?

**Comment by karelz** [comment]
@MihaZupan did you get chance to take a look at feasibility of adding tests here?

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47403) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47403) before we can accept your contribution.<br/><br/>:x: Elyhaka [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47403)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=47403) it.</sub>

**Comment by Elyhaka** [comment]
Hello, sorry for the delay, I was quite busy recently. I see that the tests have been integrated, do you still need me to check something ? :). I've just signed the CLA.

**Comment by MihaZupan** [comment]
Given that everything is okay with the added test, there shouldn't be anything else needed here. Thanks!

**Pull request merged**
