### PR TITLE
Add 3.1 to package index / validation

### PR DESCRIPTION
**Pull request by ericstj**
Replaces https://github.com/dotnet/runtime/pull/49781

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by GrabYourPitchforks** [comment]
I am totally underqualified to review this PR. :)

But out of curiosity, I wonder if it would make sense to start performing cleanup of this as RIDs drop off. For instance, _netcoreapp2.0_ and _netcoreapp3.0_ are out of support, _netcoreapp2.1_ will be out of support by the time this wave ships, and so on. It doesn't affect this PR in any way, but it makes me wonder if we should do a grand pass of this and all of our ref\\\*.csproj and src\\\*.csproj files.

**Comment by ViktorHofer** [comment]
> It doesn't affect this PR in any way, but it makes me wonder if we should do a grand pass of this and all of our ref\*.csproj and src\*.csproj files.

- https://github.com/dotnet/runtime/issues/46400
- Haven't filed an issue for upgrading anything to net461 yet but it's planned as well.

After removing harvested assets, this would be the next iteration of trimming out package assets that aren't applicable to modern workloads anymore.

**Comment by GrabYourPitchforks** [comment]
I kicked the staging step again, but CI looked green otherwise.

**Comment by ericstj** [comment]
> But out of curiosity, I wonder if it would make sense to start performing cleanup

This whole validation process should be wholesale replaced with the shipping functionality that @safern and @anpik are working on.  PackageIndex, SupportedFramework, etc will go away 🤞

**Comment by GrabYourPitchforks** [comment]
@ericstj @safern Is there any other signoff or validation we're waiting for?

**Comment by ericstj** [comment]
Nope, this looks good.

**Pull request merged**
