### PR TITLE
[release/5.0-preview4] Revert processing bundles in framework

### PR DESCRIPTION
**Pull request by swaroop-sridhar**
## Customer Scenario

Publishing apps as a self-contained single-file doesn't work as expected.

* Publish needs to generate hostpolicy and hostfxr separate from the single file bundle
* Cross-platform publishing is incorrect

## Problem

Since Static-apphost is not yet ready, processing bundle content in hostpolicy means that  hostpolicy and hostfxr DLLs need to be separate from the bundle. This causes self-contained single-file apps to not be a "single file" temporarily. 

The change also requires supporting changes from the SDK, to publish hostfxr and hostpolicy as separate files, and to invoke HostModel library with arguments that facilitate cross-platform publishing.

## Solution

To solve these, problem, this change reverts:

Revert "Single-File: Process bundles in the framework (#34274)" commit 78b303df8fbb242985d049a277d0d199cafd51b5.

and a dependent test-only change:

Revert "Single-File Bundler: Add a FileSize test (#35149)" commit 779588a509b81d909ac5d496c172949ec1f1ddcc.

## Risk

Medium
The change is contained to only host components: apphost, hostpolicy, and hostfxr.
However, the change is big, and needs testing in runtime and SDK repos.

## Testing

Manually tested the SDK by inserting apphost, hostfxr, hostpolicy, and hostmodel library from this build into the `dotnet/packs` preview-4 SDK from https://github.com/dotnet/sdk/pull/11518 build.

Verified that:
* Singlefile apps can be published and run OK for  { Windows, Linux, Osx } x {netcoreapp3.0, netcoreapp3.1, netcoreapp5.0} 
* Cross-targeting builds of single-file apps build and run OK (ex: built on Windos, run on Mac).

### CODE REVIEW

**Comment by swaroop-sridhar** [comment]
I am testing this change locally with the Preview 4 SDK, will update the description once this is complete,

**Review by jeffschwMSFT — APPROVED** [review]
lgtm

**Comment by swaroop-sridhar** [comment]
I've completed the manual testing of this change locally, details are added to the description.

**Comment by jeffschwMSFT** [comment]
@swaroop-sridhar we got approval yesterday to merge.  Please merge once we are done with validation.  
cc @mmitche @richaverma1

**Pull request merged**
