### PR TITLE
Use wider look-up table while searching chars on Arm64

### PR DESCRIPTION
**Pull request by SwapnilGaikwad**
Contributes towards the issue #84328

### CODE REVIEW

**Comment by SwapnilGaikwad** [comment]
@kunalspathak @EgorBo, this patch combines two shuffle instructions into one on Arm64. This should improve the code quality but currently it does not (thus the draft).

Assembly sequences-

<details>
<summary>Without the patch</summary>
<br>

```
   ; Assembly listing for method System.Text.Tests.Demo:IndexOfAnyLookup(System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte]):System.Runtime.Intrinsics.Vector128`1[ubyte]
; Emitting BLENDED_CODE for generic ARM64 - Unix
; optimized code
; fp based frame
; partially interruptible
; No PGO data
; 0 inlinees with PGO data; 0 single block inlinees; 3 inlinees without PGO data
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  4,  4   )  simd16  ->   d0         HFA(simd16)  single-def
;  V01 arg1         [V01,T01] (  3,  3   )  simd16  ->   d1         HFA(simd16)  single-def
;  V02 arg2         [V02,T02] (  3,  3   )  simd16  ->   d2         HFA(simd16)  single-def
;  V03 loc0         [V03,T03] (  3,  3   )  simd16  ->  d17         HFA(simd16)
;  V04 loc1         [V04,T04] (  3,  3   )  simd16  ->   d0         HFA(simd16)
;  V05 loc2         [V05,T07] (  2,  2   )  simd16  ->  d16         HFA(simd16)
;  V06 loc3         [V06,T08] (  2,  2   )  simd16  ->  d17         HFA(simd16)
;  V07 loc4         [V07,T05] (  3,  3   )  simd16  ->  d18         HFA(simd16)
;# V08 OutArgs      [V08    ] (  1,  1   )  struct ( 0) [sp+00H]   do-not-enreg[XS] addr-exposed "OutgoingArgSpace"
;* V09 tmp1         [V09    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)  "Inline return value spill temp"
;* V10 tmp2         [V10    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)  "Inline return value spill temp"
;* V11 tmp3         [V11    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)  "Inline return value spill temp"
;  V12 cse0         [V12,T06] (  3,  3   )  simd16  ->  d16         "CSE - aggressive"
;
; Lcl frame size = 0

G_M45512_IG01:
            stp     fp, lr, [sp, #-0x10]!
            mov     fp, sp
						;; size=8 bbWeight=1 PerfScore 1.50
G_M45512_IG02:
            ldr     q16, [@RWD00]
            and     v17.16b, v0.16b, v16.16b
            ushr    v0.4s, v0.4s, #4
            and     v0.16b, v0.16b, v16.16b
            tbl     v16.16b, {v1.16b}, v17.16b
            tbl     v17.16b, {v2.16b}, v17.16b
            ldr     q18, [@RWD16]
            tbl     v18.16b, {v18.16b}, v0.16b
            ldr     q19, [@RWD32]
            cmgt    v0.16b, v0.16b, v19.16b
            bsl     v0.16b, v17.16b, v16.16b
            and     v0.16b, v0.16b, v18.16b
            cmeq    v0.16b, v0.16b, v18.16b
						;; size=52 bbWeight=1 PerfScore 12.50
G_M45512_IG03:
            ldp     fp, lr, [sp], #0x10
            ret     lr
						;; size=8 bbWeight=1 PerfScore 2.00
RWD00  	dq	0F0F0F0F0F0F0F0Fh, 0F0F0F0F0F0F0F0Fh
RWD16  	dq	8040201008040201h, 8040201008040201h
RWD32  	dq	0707070707070707h, 0707070707070707


; Total bytes of code 68, prolog size 8, PerfScore 22.80, instruction count 17, allocated bytes for code 68 (MethodHash=c1384e37) for method System.Text.Tests.Demo:IndexOfAnyLookup(System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte]):System.Runtime.Intrinsics.Vector128`1[ubyte]

```
</details>


<details>
<summary>With Patch</summary>
<br>

```
; Assembly listing for method System.Text.Tests.Demo:IndexOfAnyLookupCombined(System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte]):System.Runtime.Intrinsics.Vector128`1[ubyte]
; Emitting BLENDED_CODE for generic ARM64 - Unix
; optimized code
; fp based frame
; partially interruptible
; No PGO data
; 1 inlinees with PGO data; 0 single block inlinees; 1 inlinees without PGO data
; Final local variable assignments
;
;  V00 arg0         [V00,T01] (  4,  4   )  simd16  ->   d0         HFA(simd16)  single-def
;  V01 arg1         [V01,T02] (  3,  3   )  simd16  ->   d1         HFA(simd16)  single-def
;  V02 arg2         [V02,T03] (  3,  3   )  simd16  ->   d2         HFA(simd16)  single-def
;  V03 loc0         [V03,T07] (  2,  2   )  simd16  ->  d17         HFA(simd16)
;  V04 loc1         [V04,T04] (  3,  3   )  simd16  ->   d0         HFA(simd16)
;  V05 loc2         [V05,T08] (  2,  2   )  simd16  ->  d16         HFA(simd16)
;  V06 loc3         [V06,T05] (  3,  3   )  simd16  ->   d0         HFA(simd16)
;  V07 loc4         [V07,T09] (  2,  2   )  simd16  ->  d16         HFA(simd16)
;* V08 loc5         [V08    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)
;* V09 loc6         [V09    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)
;# V10 OutArgs      [V10    ] (  1,  1   )  struct ( 0) [sp+00H]   do-not-enreg[XS] addr-exposed "OutgoingArgSpace"
;  V11 tmp1         [V11,T00] (  5, 10   )  struct (32) [fp+10H]   HFA(simd16)  do-not-enreg[SF] ld-addr-op "NewObj constructor temp"
;* V12 tmp2         [V12    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)  "Inline return value spill temp"
;  V13 cse0         [V13,T06] (  3,  3   )  simd16  ->  d16         "CSE - aggressive"
;
; Lcl frame size = 32

G_M8077_IG01:
            stp     fp, lr, [sp, #-0x30]!
            mov     fp, sp
						;; size=8 bbWeight=1 PerfScore 1.50
G_M8077_IG02:
            ldr     q16, [@RWD00]
            and     v17.16b, v0.16b, v16.16b
            ushr    v0.4s, v0.4s, #4
            and     v0.16b, v0.16b, v16.16b
            ldr     q16, [@RWD16]
            and     v16.16b, v0.16b, v16.16b
            orr     v16.16b, v16.16b, v17.16b
            stp     xzr, xzr, [fp, #0x10]
            stp     xzr, xzr, [fp, #0x20]
            stp     q1, q2, [fp, #0x10]	// [V11 tmp1], [V11 tmp1+0x10]
            ldp     q17, q18, [fp, #0x10]	// [V11 tmp1], [V11 tmp1+0x10]
            tbl     v16.16b, {v17.16b, v18.16b}, v16.16b
            ldr     q17, [@RWD32]
            tbl     v0.16b, {v17.16b}, v0.16b
            and     v16.16b, v16.16b, v0.16b
            cmeq    v0.16b, v16.16b, v0.16b
						;; size=64 bbWeight=1 PerfScore 17.00
G_M8077_IG03:
            ldp     fp, lr, [sp], #0x30
            ret     lr
						;; size=8 bbWeight=1 PerfScore 2.00
RWD00  	dq	0F0F0F0F0F0F0F0Fh, 0F0F0F0F0F0F0F0Fh
RWD16  	dq	0808080808080808h, 0808080808080808h
RWD32  	dq	8040201008040201h, 8040201008040201h


; Total bytes of code 80, prolog size 8, PerfScore 28.50, instruction count 20, allocated bytes for code 80 (MethodHash=2430e072) for method System.Text.Tests.Demo:IndexOfAnyLookupCombined(System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte]):System.Runtime.Intrinsics.Vector128`1[ubyte]
; ============================================================
```
</details>

The reason for suboptimal sequence is the following operation using the Vector128 API.

```
Vector128<byte> index = highNibbles & Vector128.Create(0x08080808).AsByte() | lowNibbles
```

Intermediate values while computing the AND/OR operations are lowered to load/store to stack. Thus, we got
```
...
stp     xzr, xzr, [fp, #0x10]
stp     xzr, xzr, [fp, #0x20]
stp     q1, q2, [fp, #0x10]	// [V11 tmp1], [V11 tmp1+0x10]
ldp     q17, q18, [fp, #0x10]	// [V11 tmp1], [V11 tmp1+0x10]
tbl     v16.16b, {v17.16b, v18.16b}, v16.16b
...
```
instead of

```
...
tbl     v16.16b, {v1.16b, v2.16b}, v16.16b
...
```

I'm marking this PR as a draft because it may cause regression as of now. If we can avoid the unnecessary operations then we can take this further. Any thoughts?







Test details to reproduce the issue.

<details>
<summary>Test C# example</summary>
<br>

```C#
private static Vector128<byte> IndexOfAnyLookup(Vector128<byte> source, Vector128<byte> bitmapLookup0, Vector128<byte> bitmapLookup1)
{
    Vector128<byte> lowNibbles = source & Vector128.Create((byte)0xF);
    Vector128<byte> highNibbles = Vector128.ShiftRightLogical(source.AsInt32(), 4).AsByte() & Vector128.Create((byte)0xF);

    Vector128<byte> row0 = ShuffleUnsafe(bitmapLookup0, lowNibbles);
    Vector128<byte> row1 = ShuffleUnsafe(bitmapLookup1, lowNibbles);
    Vector128<byte> mask = Vector128.GreaterThan(highNibbles.AsSByte(), Vector128.Create((sbyte)0x7)).AsByte();
    Vector128<byte> bitsets = Vector128.ConditionalSelect(mask, row1, row0);

    Vector128<byte> bitmask = ShuffleUnsafe(Vector128.Create(0x8040201008040201).AsByte(), highNibbles);
    Vector128<byte> result = Vector128.Equals(bitsets & bitmask, bitmask);

    return result;
}

private static Vector128<byte> IndexOfAnyLookupCombined(Vector128<byte> source, Vector128<byte> bitmapLookup0, Vector128<byte> bitmapLookup1)
{
    Vector128<byte> lowNibbles = source & Vector128.Create((byte)0xF);
    Vector128<byte> highNibbles = Vector128.ShiftRightLogical(source.AsInt32(), 4).AsByte() & Vector128.Create((byte)0xF);

    Vector128<byte> index = highNibbles & Vector128.Create(0x08080808).AsByte() | lowNibbles;
    Vector128<byte> bitsets = AdvSimd.Arm64.VectorTableLookup((bitmapLookup0, bitmapLookup1), index);

    Vector128<byte> bitmask = ShuffleUnsafe(Vector128.Create(0x8040201008040201).AsByte(), highNibbles);
    Vector128<byte> result = Vector128.Equals(bitsets & bitmask, bitmask);

    return result;
}

```
</details>

 [Full JIT Dump](https://gist.github.com/SwapnilGaikwad/59fdd97b612583fdc956ca5252a560d0) of the method

**Comment by EgorBo** [comment]
CI failures seem related?

**Comment by SwapnilGaikwad** [comment]
> CI failures seem related?

Yup, I'll check. 👍

**Comment by kunalspathak** [comment]
Do you have preliminary performance numbers for this?

**Comment by jakobbotsch** [comment]
@SwapnilGaikwad Can you check if either #88090 or #88130 helps to get rid of these stack stores?

**Comment by SwapnilGaikwad** [comment]
> Do you have preliminary performance numbers for this?

Not really. I didn't as it emitted a suboptimal sequence. To gauge the benefits we may extract the assembly and benchmark it through a C wrapper. 

> Can you check if either #88090 or #88130 helps to get rid of these stack stores?

Sure, I'll give it go.

**Comment by kunalspathak** [comment]
> Intermediate values while computing the AND/OR operations are lowered to load/store to stack. Thus, we got
> ...
stp     xzr, xzr, [fp, #0x10]
stp     xzr, xzr, [fp, #0x20]
stp     q1, q2, [fp, #0x10]	// [V11 tmp1], [V11 tmp1+0x10]
ldp     q17, q18, [fp, #0x10]	// [V11 tmp1], [V11 tmp1+0x10]
tbl     v16.16b, {v17.16b, v18.16b}, v16.16b
...
instead of
>
>...
tbl     v16.16b, {v1.16b, v2.16b}, v16.16b
...

Below pattern is very common to see because of the consecutive register requirements. We don't have (at least currently) a way to come up with allocation such that we will satisfy the need of consecutive register without having to do this kind of reloading. ld2~ld4, might come to the rescue to some extent.

```asm
stp q1, q2, [fp, #0x10] // [V11 tmp1], [V11 tmp1+0x10]
ldp q17, q18, [fp, #0x10] // [V11 tmp1], [V11 tmp1+0x10]
```

> Not really. I didn't as it emitted a suboptimal sequence. To gauge the benefits we may extract the assembly and benchmark it through a C wrapper.

I think we should still get the measurements for code it generates today to see how much slowness we get.

**Comment by SwapnilGaikwad** [comment]
After rebasing the additiona load/stores from/to stack are gone.
The updated assembly looks as expected.

<details>
<summary>Without the patch</summary>
<br>


```
; Assembly listing for method System.Text.Tests.Demo:IndexOfAnyLookupCombined(System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte]):System.Runtime.Intrinsics.Vector128`1[ubyte] (FullOpts)
; Emitting BLENDED_CODE for generic ARM64 - Unix
; FullOpts code
; optimized code
; fp based frame
; partially interruptible
; No PGO data
; 1 inlinees with PGO data; 0 single block inlinees; 1 inlinees without PGO data
; Final local variable assignments
;
;  V00 arg0         [V00,T00] (  4,  4   )  simd16  ->   d0         HFA(simd16)  single-def
;  V01 arg1         [V01,T01] (  3,  3   )  simd16  ->   d1         HFA(simd16)  single-def
;  V02 arg2         [V02,T02] (  3,  3   )  simd16  ->   d2         HFA(simd16)  single-def
;  V03 loc0         [V03,T06] (  2,  2   )  simd16  ->  d17         HFA(simd16)
;  V04 loc1         [V04,T03] (  3,  3   )  simd16  ->   d0         HFA(simd16)
;  V05 loc2         [V05,T07] (  2,  2   )  simd16  ->  d16         HFA(simd16)
;  V06 loc3         [V06,T04] (  3,  3   )  simd16  ->   d0         HFA(simd16)
;  V07 loc4         [V07,T08] (  2,  2   )  simd16  ->  d16         HFA(simd16)
;* V08 loc5         [V08    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)
;* V09 loc6         [V09    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)
;# V10 OutArgs      [V10    ] (  1,  1   )  struct ( 0) [sp+00H]   do-not-enreg[XS] addr-exposed "OutgoingArgSpace"
;* V11 tmp1         [V11    ] (  0,  0   )  struct (32) zero-ref    HFA(simd16)  do-not-enreg[SF] ld-addr-op "NewObj constructor temp"
;* V12 tmp2         [V12    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)  "Inline return value spill temp"
;* V13 tmp3         [V13    ] (  0,  0   )  simd16  ->  zero-ref    "V11.[000..016)"
;* V14 tmp4         [V14    ] (  0,  0   )  simd16  ->  zero-ref    "V11.[016..032)"
;  V15 cse0         [V15,T05] (  3,  3   )  simd16  ->  d16         "CSE - aggressive"
;
; Lcl frame size = 0

G_M8077_IG01:
            stp     fp, lr, [sp, #-0x10]!
            mov     fp, sp
						;; size=8 bbWeight=1 PerfScore 1.50
G_M8077_IG02:
            ldr     q16, [@RWD00]
            and     v17.16b, v0.16b, v16.16b
            ushr    v0.4s, v0.4s, #4
            and     v0.16b, v0.16b, v16.16b
            ldr     q16, [@RWD16]
            and     v16.4s, v0.4s, v16.4s
            shl     v16.4s, v16.4s, #1
            orr     v16.16b, v16.16b, v17.16b
            tbl     v16.16b, {v1.16b, v2.16b}, v16.16b
            ldr     q17, [@RWD32]
            tbl     v0.16b, {v17.16b}, v0.16b
            and     v16.16b, v16.16b, v0.16b
            cmeq    v0.16b, v16.16b, v0.16b
						;; size=52 bbWeight=1 PerfScore 13.00
G_M8077_IG03:
            ldp     fp, lr, [sp], #0x10
            ret     lr
						;; size=8 bbWeight=1 PerfScore 2.00
RWD00  	dq	0F0F0F0F0F0F0F0Fh, 0F0F0F0F0F0F0F0Fh
RWD16  	dq	0808080808080808h, 0808080808080808h
RWD32  	dq	8040201008040201h, 8040201008040201h


; Total bytes of code 68, prolog size 8, PerfScore 23.30, instruction count 17, allocated bytes for code 68 (MethodHash=2430e072) for method System.Text.Tests.Demo:IndexOfAnyLookupCombined(System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte],System.Runtime.Intrinsics.Vector128`1[ubyte]):System.Runtime.Intrinsics.Vector128`1[ubyte] (FullOpts)
```
</details>


Unfortunately, I couldn't get the benchmarking numbers. I'm using the dotnet performance repo for benchmarking.
How can I force a benchmark to use the new version of system libraries? Seems the `--corerun` flag does not pick the libraries from the specified dirs.

I'm using the following benchmark with the setup steps from [here](https://gist.githubusercontent.com/MihaZupan/62a1c61370d8d6f72c92b38bd7b8b5c8/raw/f91b52ecc54c833cf4bcc2b136d5f3d02e5b072b/IndexOfAnyBenchmarks.cs).

```C#
...
[Benchmark] public int LastIndexOfAnyBench() => ByteBuffer.LastIndexOfAny(SearchValues.Create(needleValues));
...
```
Do you have any suggestions to use the built libraries for performance runs? Using `corerun` from `Core_Root` was sufficient for individual test programs to use the modified libraries.

**Comment by kunalspathak** [comment]
> How can I force a benchmark to use the new version of system libraries?

IIRC, didn't it work in the past when we updated just the libraries portion and benchmarked them. Ideally the `corerun` should work, but probably @adamsitnik might know a better way.

**Comment by jakobbotsch** [comment]
> After rebasing the additiona load/stores from/to stack are gone.

Good to hear and see that. Interesting coincidence, #88090, #88130 and #88238 are all PRs that solves the exact problem causing the missing promotion here in 3 different ways.

**Comment by adamsitnik** [comment]
> Unfortunately, I couldn't get the benchmarking numbers.

What error exactly did you get?

In general the project with micro benchmarks targets multiple runtimes, including older ones that don't define this type:

https://github.com/dotnet/performance/blob/af8bc7a227215626a51f427a839c55f90eec8876/src/benchmarks/micro/MicroBenchmarks.csproj#L7-L8

If you want to add benchmarks for type that has been introduced in .NET 8 you need to add it here:

https://github.com/dotnet/performance/blob/af8bc7a227215626a51f427a839c55f90eec8876/src/benchmarks/micro/MicroBenchmarks.csproj#L199-L201

Then the project should compile. By using `--corerun` you should be able to force it to use your local copy of dotnet/runtime.

**Comment by SwapnilGaikwad** [comment]
Thanks @adamsitnik , now I managed to compile the benchmark and get performance number.

> Do you have preliminary performance numbers for this?

Performance numbers doesn't seem to show any improvements. It seems that the additional instructions to prepare updated indices is taking away the gains from combined table lookups. Perfscore also indicate the same (Base: 22.80, patch: 23.30).

```
|         Method |        Job |                                                                    Toolchain | Length |     Mean |     Error |    StdDev |   Median |      Min |      Max | Ratio | MannWhitney(2%) | Allocated | Alloc Ratio |
|--------------- |----------- |----------------------------------------------------------------------------- |------- |---------:|----------:|----------:|---------:|---------:|---------:|------:|---------------- |----------:|------------:|
| LastIndexOfAny | Job-UWUGHD |    /main/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun |   1024 | 5.534 us | 0.0157 us | 0.0147 us | 5.532 us | 5.512 us | 5.555 us |  1.00 |            Base |     112 B |        1.00 |
| LastIndexOfAny | Job-DOIGSP | /runtime/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun |   1024 | 5.510 us | 0.0184 us | 0.0172 us | 5.506 us | 5.488 us | 5.540 us |  1.00 |            Same |     112 B |        1.00 |
```

What do you recommend for this PR?

**Comment by MihaZupan** [comment]
Can you show the benchmark you are using?

**Comment by SwapnilGaikwad** [comment]
> Can you show the benchmark you are using?

[Here](https://gist.github.com/SwapnilGaikwad/afaa66653ee1aa53b88e6f18c3cba7c0). I'll be more than happy to try if you have suggestions to stress the `IndexOfAnyLookup(Vector128<byte>, Vector128<byte>, Vector128<byte>)` for byte arguments. I feel it primarily targets the `IndexOfAnyLookup(Vector128<short>, Vector128<short>, Vector128<byte>)`

**Comment by MihaZupan** [comment]
Can you please test it with the following?

```c#
public class IndexOfAnyBenchmarks
{
    private static readonly SearchValues<byte> s_searchValues =
        SearchValues.Create("aeiou"u8.ToArray().Concat(new[] { (byte)0xFF }).ToArray());

    private byte[] _byteBuffer = null!;

    [Params(8, 16, 32, 1024)]
    public int Length;

    [GlobalSetup]
    public void Setup()
    {
        _byteBuffer = new byte[Length];
        _byteBuffer.AsSpan().Fill((byte)'\n');
        _byteBuffer[Length / 2] = (byte)'a';
    }

    [Benchmark] public int IndexOfAny() => _byteBuffer.AsSpan().IndexOfAny(s_searchValues);
}
```

**Comment by SwapnilGaikwad** [comment]
> Can you please test it with the following?

Thanks @MihaZupan for the benchmark. Please find the following results on executive the benchmark.

```
|     Method |        Job |                                                                    Toolchain | Length |      Mean |    Error |   StdDev |    Median |       Min |       Max | Ratio | MannWhitney(2%) | Allocated | Alloc Ratio |
|----------- |----------- |----------------------------------------------------------------------------- |------- |----------:|---------:|---------:|----------:|----------:|----------:|------:|---------------- |----------:|------------:|
| IndexOfAny | Job-QYJCDR |    /main/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun |      8 |  15.93 ns | 0.058 ns | 0.054 ns |  15.94 ns |  15.85 ns |  16.01 ns |  1.00 |            Base |         - |          NA |
| IndexOfAny | Job-CNHREH | /runtime/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun |      8 |  16.63 ns | 0.039 ns | 0.036 ns |  16.63 ns |  16.56 ns |  16.68 ns |  1.04 |          Slower |         - |          NA |
|            |            |                                                                              |        |           |          |          |           |           |           |       |                 |           |             |
| IndexOfAny | Job-VNBLMH |    /main/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun |     16 |  22.41 ns | 0.097 ns | 0.091 ns |  22.43 ns |  22.26 ns |  22.55 ns |  1.00 |            Base |         - |          NA |
| IndexOfAny | Job-UHWGQK | /runtime/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun |     16 |  22.87 ns | 0.180 ns | 0.168 ns |  22.83 ns |  22.69 ns |  23.13 ns |  1.02 |            Same |         - |          NA |
|            |            |                                                                              |        |           |          |          |           |           |           |       |                 |           |             |
| IndexOfAny | Job-VNBLMH |    /main/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun |     32 |  32.08 ns | 0.387 ns | 0.362 ns |  32.04 ns |  31.45 ns |  32.53 ns |  1.00 |            Base |         - |          NA |
| IndexOfAny | Job-UHWGQK | /runtime/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun |     32 |  31.63 ns | 0.170 ns | 0.159 ns |  31.62 ns |  31.39 ns |  31.90 ns |  0.99 |            Same |         - |          NA |
|            |            |                                                                              |        |           |          |          |           |           |           |       |                 |           |             |
| IndexOfAny | Job-VNBLMH |    /main/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun |   1024 | 179.85 ns | 0.381 ns | 0.356 ns | 179.91 ns | 179.20 ns | 180.44 ns |  1.00 |            Base |         - |          NA |
| IndexOfAny | Job-UHWGQK | /runtime/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun |   1024 | 180.06 ns | 0.310 ns | 0.259 ns | 180.03 ns | 179.46 ns | 180.43 ns |  1.00 |            Same |         - |          NA |
```

**Comment by kunalspathak** [comment]
@SwapnilGaikwad - for benchmark measurements, we typically prefer to run the `Release` version of binaries.

**Comment by SwapnilGaikwad** [comment]
> @SwapnilGaikwad - for benchmark measurements, we typically prefer to run the `Release` version of binaries.

My bad. Please find the following numbers with both runtime and libraries compiled in Release mode (previously, libraries were in Release mode and runtime was in Checked mode).

```
|     Method |        Job |                                                                    Toolchain | Length |     Mean |    Error |   StdDev |   Median |      Min |      Max | Ratio | MannWhitney(2%) | Allocated | Alloc Ratio |
|----------- |----------- |----------------------------------------------------------------------------- |------- |---------:|---------:|---------:|---------:|---------:|---------:|------:|---------------- |----------:|------------:|
| IndexOfAny | Job-INLKUP |    /main/artifacts/tests/coreclr/linux.arm64.Release/Tests/Core_Root/corerun |      8 | 18.64 ns | 0.001 ns | 0.001 ns | 18.64 ns | 18.64 ns | 18.64 ns |  1.00 |            Base |         - |          NA |
| IndexOfAny | Job-EINVMY | /runtime/artifacts/tests/coreclr/linux.arm64.Release/Tests/Core_Root/corerun |      8 | 19.17 ns | 0.005 ns | 0.005 ns | 19.17 ns | 19.17 ns | 19.18 ns |  1.03 |          Slower |         - |          NA |
|            |            |                                                                              |        |          |          |          |          |          |          |       |                 |           |             |
| IndexOfAny | Job-INLKUP |    /main/artifacts/tests/coreclr/linux.arm64.Release/Tests/Core_Root/corerun |     16 | 18.43 ns | 0.002 ns | 0.002 ns | 18.43 ns | 18.43 ns | 18.44 ns |  1.00 |            Base |         - |          NA |
| IndexOfAny | Job-EINVMY | /runtime/artifacts/tests/coreclr/linux.arm64.Release/Tests/Core_Root/corerun |     16 | 19.15 ns | 0.002 ns | 0.002 ns | 19.15 ns | 19.15 ns | 19.15 ns |  1.04 |          Slower |         - |          NA |
|            |            |                                                                              |        |          |          |          |          |          |          |       |                 |           |             |
| IndexOfAny | Job-RLZORX |    /main/artifacts/tests/coreclr/linux.arm64.Release/Tests/Core_Root/corerun |     32 | 18.95 ns | 0.003 ns | 0.003 ns | 18.95 ns | 18.94 ns | 18.95 ns |  1.00 |            Base |         - |          NA |
| IndexOfAny | Job-VQLLAV | /runtime/artifacts/tests/coreclr/linux.arm64.Release/Tests/Core_Root/corerun |     32 | 19.43 ns | 0.006 ns | 0.006 ns | 19.43 ns | 19.43 ns | 19.44 ns |  1.03 |          Slower |         - |          NA |
|            |            |                                                                              |        |          |          |          |          |          |          |       |                 |           |             |
| IndexOfAny | Job-RLZORX |    /main/artifacts/tests/coreclr/linux.arm64.Release/Tests/Core_Root/corerun |   1024 | 80.42 ns | 0.108 ns | 0.096 ns | 80.41 ns | 80.28 ns | 80.61 ns |  1.00 |            Base |         - |          NA |
| IndexOfAny | Job-VQLLAV | /runtime/artifacts/tests/coreclr/linux.arm64.Release/Tests/Core_Root/corerun |   1024 | 83.00 ns | 0.100 ns | 0.094 ns | 82.98 ns | 82.89 ns | 83.19 ns |  1.03 |          Slower |         - |          NA |

```

**Comment by kunalspathak** [comment]
Thanks @SwapnilGaikwad for gathering the numbers. Do you mind pasting the before vs. after code once again for the `IndexOfAny` benchmark that @MihaZupan suggested?

**Comment by danmoseley** [comment]
Whatever happens with this PR perhaps this benchmark ought to be added to dotnet/performance

**Comment by kunalspathak** [comment]
Looking at the disassembly, I don't see how ld2~ld4 would help improve the performance here. @tannergooding - do you have any other opinion about the algorithm?

**Comment by adamsitnik** [comment]
The perf results don't show an improvement, rather a regression (main is the baseline job, MannWhitney column showing Slower)

|     Method | Toolchain | Length |     Mean | Ratio | MannWhitney(2%) |
|----------- |-----------|------- |---------:|------:|---------------- |
| IndexOfAny |     /main/|      8 | 18.64 ns |  1.00 |            Base |
| IndexOfAny |  /runtime/|      8 | 19.17 ns |  1.03 |          Slower |
|            |           |        |          |       |                 |
| IndexOfAny |     /main/|     16 | 18.43 ns |  1.00 |            Base |
| IndexOfAny |  /runtime/|     16 | 19.15 ns |  1.04 |          Slower |
|            |           |        |          |       |                 |
| IndexOfAny |     /main/|     32 | 18.95 ns |  1.00 |            Base |
| IndexOfAny |  /runtime/|     32 | 19.43 ns |  1.03 |          Slower |
|            |           |        |          |       |                 |
| IndexOfAny |     /main/|   1024 | 80.42 ns |  1.00 |            Base |
| IndexOfAny |  /runtime/|   1024 | 83.00 ns |  1.03 |          Slower |

> Looking at the disassembly, I don't see how ld2~ld4 would help improve the performance here. 

I believe we should close the PR.

@SwapnilGaikwad thank you for your contribution!

**Pull request closed without merging**
