### PR TITLE
Fix unique VNs for `ADDR`s

### LINKED ISSUE #64208: Assertion failed 'vnStore->VNExcIsSubset(nodeExcSet.GetLiberal(), operandsExcSet.GetLiberal())' during 'Do value numbering'
```c#
// Found by Antigen
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
public class TestClass
{
    public struct S1
    {
    }
    static S1 s_s1_32 = new S1();
    public S1 LeafMethod15()
    {
        unchecked
        {
            return s_s1_32;
        }
    }
    public void Method0()
    {
        unchecked
        {
            LeafMethod15();
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
    }
}

/*
Environment:

set COMPlus_TieredCompilation=0
set COMPlus_JitAggressiveInlining=1

Assert failure(PID 71508 [0x00011754], Thread: 29652 [0x73d4]): Assertion failed 'vnStore->VNExcIsSubset(nodeExcSet.GetLiberal(), operandsExcSet.GetLiberal())' in 'TestClass:Method0():this' during 'Do value numbering' (IL size 8)
    File: D:\git\dotnet-runtime\src\coreclr\jit\valuenum.cpp Line: 11074
    Image: d:\git\dotnet-runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe
*/

```

### PR DESCRIPTION
**Pull request by SingleAccretion**
They need to keep the exception sets.

Fixes #64208.

### CODE REVIEW

**Comment by EgorBo** [comment]
is that a recently introduced bug or always has been?

**Comment by SingleAccretion** [comment]
Has been there since forever, only now we have a checker that catches these cases.

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by kunalspathak** [comment]
Its interesting that our tests doesn't have coverage to hit the asserts in newly added checker.

**Review by kunalspathak — APPROVED** [review]
LGTM

**Pull request merged**
