### PR TITLE
Update lpFirst and lpTop to reflect accurate compacted blocks

### LINKED ISSUE #46241: fgUpdateLoopsAfterCompacting should update lpFirst and lpTop as well
Today, `fgUpdateLoopsAfterCompacting()` update all the fields except `lpFirst` and `lpTop`. Make sure to update these two as well.

### PR DESCRIPTION
**Pull request by kunalspathak**
Update `lpTop` and `lpFirst` when blocks are compacted.

Fixes: #46241

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib , @BruceForstall

**Comment by BruceForstall** [comment]
Any diffs?

**Comment by BruceForstall** [comment]
Actually, what is a scenario where updating these would be required or legal? We've got BB1 followed by BB2. BB2 is getting merged/compacted into BB1. How could that happen if BB2 was the first or top of a loop?

**Comment by kunalspathak** [comment]
There are no asmdiffs. I noticed this while investigating while working on loop alignment. It was not a correctness issue in any way, but it feels that if the block is getting compacted, we should make sure that the loop table updates all the entries. Let us chat offline about it.

**Comment by BruceForstall** [comment]
Maybe instead of update, assert that lpFirst/lpTop are not bNext?

**Comment by kunalspathak** [comment]
> Maybe instead of update, assert that lpFirst/lpTop are not bNext?

Yes, that would be better to validate first.

**Comment by kunalspathak** [comment]
So I noticed several failures with the assert while building SPC. It turns out that every time we try to compact Loop preheader block with a loop header, we run into this where `lpTop == bbNext`   and should be changed to `block`.

```asm
-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..008)-> BB04 ( cond )                     i label target LIR 
BB02 [0001]  1       BB01                  0.50    [008..013)-> BB04 ( cond )                     i idxlen LIR 
BB05 [0009]  1       BB02                  0.50    [013..???)                                     internal LoopPH LIR 
BB03 [0002]  2       BB03,BB05             4     0 [013..028)-> BB03 ( cond )                     i Loop label target hascall gcsafe idxlen nullcheck bwd bwd-target LIR 
BB04 [0004]  3       BB01,BB02,BB03        1       [028..031)        (return)                     i label target LIR 
-----------------------------------------------------------------------------------------------------------------------------------------


Compacting blocks BB05 and BB03:
```

It looks like we access `lpTop` and `lpFirst` at very few places and hence it doesn't matter if we update it or not. That is the reason I didn't see any asmdiffs. For sanity, I added this and I didn't get any complain on superpmi replay:

```c++
if (optLoopTable[loopNum].lpFirst == bNext)
{
    optLoopTable[loopNum].lpFirst = nullptr;
}

if (optLoopTable[loopNum].lpTop == bNext)
{
    optLoopTable[loopNum].lpTop = nullptr;
}
```

But I think, let us update those fields accurately, so in future we don't have to investigate an issue caused because of this mismatch.

**Comment by BruceForstall** [comment]
Ok, makes sense to do the implementation you originally had.

**Comment by kunalspathak** [comment]
> Ok, makes sense to do the implementation you originally had.

Done.

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
