### PR TITLE
[mono][android] Fix android extra-platforms by renaming the project name

### PR DESCRIPTION
**Pull request by kotlarmilos**
## Description

This PR fixes android extra-platforms by renaming the project name. Bundle attribute package has invalid character `-`.

```
2023-10-06T01:07:48.5821858Z /__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(271,5): error MSB4018: The "AndroidAppBuilderTask" task failed unexpectedly. [/__w/1/s/src/tests/Loader/classloader/regressions/Loader-classloader-regressions.csproj] [/__w/1/s/src/tests/build.proj]
2023-10-06T01:07:48.5822925Z /__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(271,5): error MSB4018: System.Exception: Error: Process returned non-zero exit code: AndroidManifest.xml:2: Tag <manifest> attribute package has invalid character '-'. [/__w/1/s/src/tests/Loader/classloader/regressions/Loader-classloader-regressions.csproj] [/__w/1/s/src/tests/build.proj]
2023-10-06T01:07:48.5823916Z /__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(271,5): error MSB4018: AndroidManifest.xml:20: Tag <instrumentation> attribute targetPackage has invalid character '-'. [/__w/1/s/src/tests/Loader/classloader/regressions/Loader-classloader-regressions.csproj] [/__w/1/s/src/tests/build.proj]
2023-10-06T01:07:48.5825153Z /__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(271,5): error MSB4018: at Utils.RunProcess(TaskLoggingHelper logger, String path, String args, IDictionary`2 envVars, String workingDir, Boolean ignoreErrors, Boolean silent, MessageImportance debugMessageImportance) in /_/src/tasks/Common/Utils.cs:line 123 [/__w/1/s/src/tests/Loader/classloader/regressions/Loader-classloader-regressions.csproj] [/__w/1/s/src/tests/build.proj]
2023-10-06T01:07:48.5826410Z /__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(271,5): error MSB4018: at ApkBuilder.BuildApk(String runtimeIdentifier, String mainLibraryFileName, String monoRuntimeHeaders) in /_/src/tasks/AndroidAppBuilder/ApkBuilder.cs:line 449 [/__w/1/s/src/tests/Loader/classloader/regressions/Loader-classloader-regressions.csproj] [/__w/1/s/src/tests/build.proj]
2023-10-06T01:07:48.5827682Z /__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(271,5): error MSB4018: at AndroidAppBuilderTask.Execute() in /_/src/tasks/AndroidAppBuilder/AndroidAppBuilder.cs:line 141 [/__w/1/s/src/tests/Loader/classloader/regressions/Loader-classloader-regressions.csproj] [/__w/1/s/src/tests/build.proj]
2023-10-06T01:07:48.5828627Z /__w/1/s/src/mono/msbuild/android/build/AndroidBuild.targets(271,5): error MSB4018: at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/__w/1/s/src/tests/Loader/classloader/regressions/Loader-classloader-regressions.csproj] [/__w/1/s/src/tests/build.proj]
```

### CODE REVIEW

**Comment by fanyang-mono** [comment]
Still failing with the same error. Somehow the name didn't seem to be changed.

**Comment by kotlarmilos** [comment]
> Still failing with the same error. Somehow the name didn't seem to be changed.

Actually, project `Loader-classloader-generics` is invalid as well.

**Review by trylek — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
