### PR TITLE
Fix for #60532

### LINKED ISSUE #60532: CLRInformationVersion contains the buildNumber or version suffix
### Description

In one of the tests in the coreclr we are matching the Informational version with ClrProductVersion. We are always including the build number in the InformationalVersion of an assembly but we dont do that for clr Product verison which is leading to the test failure.

This is reproing when we enable the stable bits flag.

 https://github.com/dotnet/runtime/pull/60482
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60482-merge-8ea93e618a844dc487/PayloadGroup0/1/console.cff9299f.log?sv=2019-07-07&se=2021-11-07T04%3A53%3A55Z&sr=c&sp=rl&sig=IBViKwqkqcGqRgvTnM98zHnFWUGmK6yIVdcwvTBcAU8%3D

// failure test https://github.com/dotnet/runtime/blob/release/6.0/src/tests/tracing/eventpipe/processinfo2/processinfo2.cs#L244

is this a test failure or a bug ? 

cc @hoyosjs @ericstj @ViktorHofer @jeffschwMSFT 

### Reproduction Steps

Turn on stable flag

### Expected behavior

```
  Finished:    tracing.eventlistener.XUnitWrapper
  Discovering: tracing.eventpipe.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  tracing.eventpipe.XUnitWrapper (found 14 test cases)
  Starting:    tracing.eventpipe.XUnitWrapper (parallel test collections = on, max threads = 4)
    tracing/eventpipe/processinfo2/processinfo2/processinfo2.sh [FAIL]
      Unhandled exception. System.Exception: ClrProductVersion must match. Expected: "6.0.0-ci", received: "6.0.0"
         at Tracing.Tests.Common.Utils.Assert(Boolean predicate, String message)
         at Tracing.Tests.ProcessInfoValidation.ProcessInfoValidation.Main(String[] args)
      apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7fa83a7aac)
      /root/helix/work/workitem/e/tracing/eventpipe/processinfo2/processinfo2/processinfo2.sh: line 374:  1677 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.eventpipe/processinfo2/processinfo2/processinfo2.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false processinfo2.dll ''
        0.0s: Test PID: 1677
        0.7s: Wrote: { Header={ Magic=System.Byte[]; Size=20; CommandSet=4; CommandId=4; Reserved=0 }; }
        1.1s: Received: <omitted>
        1.1s: Total size of Payload = 358 bytes
        1.1s: pid: 1677
        1.1s: runtimeCookie: 29acf19e-51a3-4d25-b80b-1bdba44bbc91
```

### Actual behavior

I am not sure if these versions should match or its just a test failure

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by trylek**
In stable package mode we should be setting CoreLib informational
version to the ProductVersion according to the discussion on the
issue thread. I have verified locally that this fixes the processinfo2
test for me that was previously failing in the StabilizePackageVersion
mode. Please let me know how to proceed with the fix, whether you
want me to just merge it into dotnet/runtime main, whether I should
pursue its backport into 6.0 release and / or whether Matt considers
cherry-picking my change to his stabilization PR.

Thanks

Tomas

Fixes #60532 

/cc @dotnet/runtime-infrastructure

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by hoyosjs** [comment]
For main we might also want to make sure that `IsPrivateAssembly` and `SuppressFinalPackageVersion` are false and that `IsShippingPackage` is true. Basically, the DBprops looks at `Private` in the name and thinks it's not meant to be a stable assembly.

**Review by hoyosjs — APPROVED** [review]

**Comment by jeffschwMSFT** [comment]
@hoyosjs / @trylek can you elaborate on the impact and if we need this in .NET 6?  We are about to produce our first candidate build.

**Comment by jeffschwMSFT** [comment]
I think we should take this.  @trylek can you create a backport?

**Pull request merged**
