### PR TITLE
Disable STJ reflection by default on AOT publish

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Following up on https://github.com/dotnet/sdk/pull/33757#issuecomment-1628706240 this updates the AOT targets so that the `JsonSerializerIsReflectionEnabledByDefault` feature switch is defaulted to false.

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
This LGTM. It would be good to get a review from @MichalStrehovsky before merging.

**Review by MichalStrehovsky — CHANGES_REQUESTED** [review]
> This LGTM. It would be good to get a review from @MichalStrehovsky before merging.

I don't think this is necessary. Native AOT without trimming doesn't make sense. Neither does a potential [future Mono AOT](https://github.com/dotnet/sdk/pull/33757#issuecomment-1628706240) using Native AOT-specific targets (that this PR is changing). It's likely the RequiresDynamicCode-annotated code doesn't even pose a problem for Mono-based AOT in its current form.

**Comment by eerhardt** [comment]
> > This LGTM. It would be good to get a review from @MichalStrehovsky before merging.
> 
> I don't think this is necessary. Native AOT without trimming doesn't make sense. Neither does a potential [future Mono AOT](https://github.com/dotnet/sdk/pull/33757#issuecomment-1628706240) using Native AOT-specific targets (that this PR is changing). It's likely the RequiresDynamicCode-annotated code doesn't even pose a problem for Mono-based AOT in its current form.

See feedback from @vitek-karas [here](https://github.com/dotnet/sdk/pull/33757#issuecomment-1628706240).

@vitek-karas - thoughts?

**Comment by MichalStrehovsky** [comment]
> See feedback from @vitek-karas https://github.com/dotnet/sdk/pull/33757#issuecomment-1628706240.

I saw that - my comment is that I don't see how the ILCompiler targets (that are edited here) could be relevant for a possible PublishAot-use in Mono and that we haven't even decided how RDC annotations could apply to Mono (Mono doesn't have a matching mode that would be able to take advantage of RDC restrictions so as things stand now, enabling the RDC analyzer on Mono would annoy people with warnings, most of which will not actually be a problem because Mono has both an interpreter, and universal shared code).

**Comment by vitek-karas** [comment]
I will happily follow Michal's guidance on this.

I was thinking about it on the abstract level - feature which is incompatible with AOT (due to RequiresDynamicCode) should be disabled for AOT. On the other hand, NativeAOT currently doesn't support the configuration without trimming and mono might have different needs (and thus different feature switch defaults).

**Pull request closed without merging**
