### PR TITLE
Avoid exceptions from FileVersionInfo.TryLoadManagedAssemblyMetadata on Unix

### PR DESCRIPTION
**Pull request by stephentoub**
Contributes to https://github.com/dotnet/runtime/issues/50207

### CODE REVIEW

**Review by carlossanlop — APPROVED** [review]
Thanks, Stephen for the PR to silence the exception.

Since the description says "_Contributes to_", do you think there could be a way to workaround the file permission restriction (`-rwx--x--x` and `-r-x------`) when the file is owned by root, which is preventing us from reading the file attributes?

**Comment by stephentoub** [comment]
Not sure.  I wrote "contributes to" because I'm not sure how much of the original issue this addresses; it should help improve it, but I don't know if it's sufficient to call it solved.

**Comment by dsyme** [comment]
@stephentoub  Just to mention I hit this bug of an exception in TryLoadManagedAssemblyMetadata triggered somewhere in the MSBuild GenerateDepsFile task, see https://github.com/xamarin/TorchSharp/issues/293#issuecomment-866836324

The specific case was because of a native binary > 2GB in size.  This monstrosity is now happening in AI Runtimes such as PyTorch which includes the absolutely vast native binary `libtorch\lib\libtorch_cuda_cpp.so`, which in recent releases is now > 2GB, because it evidently contains pre-compiled kernels for every imaginable tensor kind, shape, size, operation, whatever.  Quite remarkable but it is what it is, the great new modern world of AI.

Anyway I'd like to chat with someone on the MSBuild/Nuget team in order to ensure we have proper testing in place for dealing with nuget packages that include native dependencies > 2GB in size, as I fear we may have trouble in the future if this is not under test (e.g. through use of `int` indexing instead of `long`).  Do you know who the right person to talk to is, or the right place to add a general end-to-end test issue for this scenario?

**Comment by stephentoub** [comment]
@dsyme, thanks for the information!

> Do you know who the right person to talk to is, or the right place to add a general end-to-end test issue for this scenario?

@rainersigwald, could you point @dsyme in the right direction here?

**Comment by rainersigwald** [comment]
@dsyme if it's in `GenerateDepsFile`, the test will go in https://github.com/dotnet/sdk/. If that layer winds up needing NuGet or MSBuild support, we can work that out no problem -- we have a weekly meeting with all 3 teams.

**Comment by dsyme** [comment]
@rainersigwald OK I'll put an issue in that repo and @ you, thanks

**Comment by dsyme** [comment]
Issue is here, thanks! https://github.com/dotnet/sdk/issues/18507

**Pull request merged**
