### PR TITLE
Revert "Fix source_file bug in mono_ppdb_lookup_location_internal"

### PR DESCRIPTION
**Pull request by thaystg**
Reverts dotnet/runtime#96497

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by vargaz** [comment]
A possible fix would be:
```
		if (!first && delta_il == 0) {
			/* document-record */
			docidx = mono_metadata_decode_value (ptr, &ptr);
			// check the current iloffset to ensure that we do not update docname after the target
			// offset has been reached (the updated docname will be for the next sequence point)
			if (iloffset < offset)
				docname = get_docname (ppdb, image, docidx);
			continue;
		}
```

**Comment by vargaz** [comment]
@bholmes

**Comment by thaystg** [comment]
Do you think we should fix it for preview 1 or revert it for preview 1 and try this in main?

**Comment by vargaz** [comment]
I'd suggest reverting it.

**Comment by bholmes** [comment]
> A possible fix would be:

Yes this looks correct

**Comment by thaystg** [comment]
@bholmes can you please open another PR with @vargaz suggestion?

**Pull request merged**
