### PR TITLE
JIT: fix issue with unreachable blocks in redundant branch opt

### LINKED ISSUE #72767: Assertion failed 'vnWx != NoVN' during 'Redundant branch opts'
```csharp
// Generated by Fuzzlyn v1.5 on 2022-07-24 16:52:25
// Run on X86 Windows
// Seed: 11775672037815743472
// Reduced from 302.0 KiB to 1.4 KiB in 00:06:35
// Hits JIT assert in Release:
// Assertion failed 'vnWx != NoVN' in 'Program:M71()' during 'Redundant branch opts' (IL size 136; hash 0x996ec7e1; FullOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\valuenum.cpp Line: 1306
// 
public struct S0
{
    public short F0;
    public sbyte F1;
    public S0(short f0, sbyte f1): this()
    {
        F0 = f0;
        F1 = f1;
    }
}

public struct S1
{
    public ushort F0;
    public uint F2;
    public S0 F3;
    public S0 F4;
    public int F5;
    public S1(ushort f0, uint f2, S0 f3, S0 f4, int f5): this()
    {
        F0 = f0;
        F2 = f2;
        F4 = f4;
        F5 = f5;
    }
}

public class Program
{
    public static bool[] s_7;
    public static sbyte s_26;
    public static S0[] s_44;
    public static void Main()
    {
        M71();
    }

    public static void M71()
    {
        var vr5 = (0 != s_26) || s_7[0];
        S1 vr20 = default(S1);
        for (int var15 = 0; var15 < 1; var15++)
        {
            return;
        }

        var vr7 = new S0(0, 0);
        if (!M81(true))
        {
            for (int var16 = 0; var16 < 0; var16++)
            {
                try
                {
                    System.Console.WriteLine(vr20.F3.F0);
                }
                finally
                {
                    var vr2 = new S1(0, 0, new S0(0, 0), new S0(0, 0), 0);
                }
            }
        }

        if (s_7[0])
        {
            s_44 = s_44;
        }
    }

    public static bool M81(bool arg0)
    {
        return arg0;
    }
}
```

Looks like another "unreachable code" example so will put it in 8.0 milestone.

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Update `fgGetDomSpeculatively` to return nullptr if the idom of a block is unreachable, even if other preds have refs.

Fixes #72767.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@egorbo PTAL
cc @dotnet/jit-contrib

**Comment by EgorBo** [comment]
@AndyAyersMS I assume a block may still have a valid _real_ dominator since we didn't inspect other preds, but it means that current block->iDom is definitely compromised/stale, hoping it won't lead to terrible diffs 🙂

**Review by EgorBo — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
> @AndyAyersMS I assume a block may still have a valid _real_ dominator since we didn't inspect other preds, but it means that current block->iDom is definitely compromised/stale, hoping it won't lead to terrible diffs 🙂

I didn't see any diffs locally but only based on a few SPMI collections as we're still rebuilding them.

There is an odd divergence between dominators and the flow graph preds in some cases. I don't yet know if it is just unreachable blocks, some issue where we don't model flow out of finallys properly, cases where can't get rid of some EH regions even if unreachable, or something else. 

In this case `BB07` through `BB10` are unreachable and `BB11` has a dominator `BB06`.

RBO discovers that `BB04` must branch to `BB05` and this makes `BB06` also unreachable. 

RBO then looks at `BB11` and as part of that, `fgGetSpeculativeDom` selects `BB10` as a plausible dominator since `BB06` has no preds left. But the IR in `BB10` has been skipped over during value numbering. When we try and unpack BB10's relop VN we get the assert above.

My fix stops RBO from looking at the VNs in `BB10`. It might be more robust to just screen out potential doms with `NoVN`s.
```
-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..007)-> BB03 ( cond )                     i 
BB02 [0001]  1       BB01                  1       [007..010)-> BB04 (always)                     i idxlen 
BB03 [0002]  1       BB01                  1       [010..011)                                     i 
BB04 [0003]  2       BB02,BB03             1       [011..01E)-> BB06 ( cond )                     i 
BB05 [0004]  1       BB04                  1       [01E..01F)        (return)                     i bwd-target 
BB06 [0006]  1       BB04                  1       [023..033)-> BB11 (always)                     i 
BB07 [0009]  1  0    BB10                  0       [037..04A)                 T0      try { }     keep i try rare Loop hascall gcsafe bwd 
BB08 [0016]  1       BB07                  0       [???..???)-> BB14 (callf )                     i internal rare gcsafe 
BB09 [0017]  1       BB14                  0       [???..???)-> BB10 (ALWAYS)                     i internal rare Loop gcsafe KEEP 
BB10 [0011]  1       BB09                  0       [062..06A)-> BB07 ( cond )                     i rare gcsafe bwd 
BB11 [0013]  2       BB06,BB10             1       [06A..073)-> BB13 ( cond )                     i idxlen 
BB12 [0014]  1       BB11                  1       [073..07D)                                     i 
BB13 [0015]  2       BB11,BB12             1       [07D..07E)        (return)                     i 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ funclets follow
BB14 [0010]  2     0 BB08                  0       [04A..062)        (finret)    H0 F finally { } keep i rare gcsafe flet bwd 
-----------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by AndyAyersMS** [comment]
Failures all seem to be from #76041

**Comment by AndyAyersMS** [comment]
No [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=26877&view=ms.vss-build-web.run-extensions-tab).

**Pull request merged**
