### PR TITLE
Typo fixed

### PR DESCRIPTION
**Pull request by WhiteBlackGoose**

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]

**Comment by danmoseley** [comment]
Thanks for the contribution @WhiteBlackGoose . If you would like to offer another, there are many issues with the "up-for-grabs" label (some also have the "easy" label)

**Comment by WhiteBlackGoose** [comment]
@danmoseley thanks. It feels a bit that even for those I need to get a bit more knowledge (you can see my failed PRs 😅 ).

**Comment by danmoseley** [comment]
@WhiteBlackGoose we all started there! You might find issues in dotnet-api-docs an easier way to start. Those are just as important to the product. Here are some marked up for grabs:
https://github.com/dotnet/dotnet-api-docs/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs+

**Comment by danmoseley** [comment]
But don't let that deter you from trying a PR on one of the easier issues in this repo.

**Pull request merged**
