### PR TITLE
Add ICorDebugModule4 - Get Module mapping mode

### PR DESCRIPTION
**Pull request by hoyosjs**
cc; @agocke @tommcdon

### CODE REVIEW

**Comment by hoyosjs** [comment]
Tested this against a Linux and a Windows process with both IL and R2R images and got the expected behavior. Trying to see if there's a way I can test this against single file.

cc: @gregg-miskelly @chuckries

**Review by gregg-miskelly — APPROVED** [review]

**Comment by hoyosjs** [comment]
Tested against single file too, and all is working as expected.

**Comment by agocke** [comment]
cc @VSadov who may be working at stuff in a similar area

**Comment by agocke** [comment]
and @mateoatr to confirm the runtime side

**Comment by hoyosjs** [comment]
@noahfalk is the surface area good like this? Made a tiny changing name to the proposal to be consistent to other APIs I saw on module, but don't have too strong of a stance either way.

**Comment by noahfalk** [comment]
> @noahfalk is the surface area good like this?

Looks fine to me. ICorDebug is used by maybe a few dozen people in the world so I try not to sweat the naming too much : ) If the VS folks consuming the API think it makes sense that is usually a good indicator.

**Review by noahfalk — COMMENTED** [review]
LGTM! : )

**Review by noahfalk — APPROVED** [review]
Oops that was supposed to be approve

**Pull request merged**
