### PR TITLE
Remove single proc WKS helpers

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
These optimizations are for single-proc workstation scenarios. Since that scenario is relatively less common, maintaining these optimizations has lower benefit.

/cc @davidwrighton @richlander @Maoni0 @jkotas

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
This PR is marked as Draft as I am looking for feedback regarding if the single-proc WKS scenario is important enough to do some additional performance investigation on how much benefit these helpers are actually giving relative to their maintenance cost.

**Comment by Maoni0** [comment]
I was told a few years ago that single proc wks case was common on Azure. if you want to remove this I think it would be good to actually do some perf measurements.

**Comment by davidwrighton** [comment]
I would also say that if you can find some time to do some benchmarks, finding out if the assembly helpers for boxing are actually useful at all would be nice to know.

**Comment by davidwrighton** [comment]
I'd like to know if there is evidence that we might want to write helpers for arm64. I would much prefer to discover that the handcoded assembly is out of date and deletable.

**Comment by AaronRobinsonMSFT** [comment]
This wasn't even close. I'm closing this PR.

Using hand-written assembly with fallback to VM calls

|                    Method |      Mean |     Error |    StdDev |
|-------------------------- |----------:|----------:|----------:|
|     CORINFO_HELP_NEWSFAST |  1.853 ns | 0.0906 ns | 0.1513 ns |
|          CORINFO_HELP_BOX |  4.416 ns | 0.1406 ns | 0.2607 ns |
|  CORINFO_HELP_NEWARR_1_VC | 21.385 ns | 0.4733 ns | 0.4649 ns |
| CORINFO_HELP_NEWARR_1_OBJ | 11.062 ns | 0.2762 ns | 0.3961 ns |

Using VM calls

|                    Method |     Mean |    Error |   StdDev |
|-------------------------- |---------:|---------:|---------:|
|     CORINFO_HELP_NEWSFAST | 25.55 ns | 0.514 ns | 0.505 ns |
|          CORINFO_HELP_BOX | 29.60 ns | 0.625 ns | 0.768 ns |
|  CORINFO_HELP_NEWARR_1_VC | 45.96 ns | 0.968 ns | 1.794 ns |
| CORINFO_HELP_NEWARR_1_OBJ | 35.61 ns | 0.758 ns | 1.225 ns |

**Comment by richlander** [comment]
Sorry that I'm finding this late. I just wanted to address the q about whether single-proc was common. That's basically the container scenario. A lot of folks configure containers with 1 core (equivalent) or less.

**Comment by jkotas** [comment]
I expect that these single-proc helpers are rarely used with containers.

These single-proc helpers can be only used when the machine or VM has physically one core. They assume that there are not multiple threads running in parallel that can be only guaranteed when the machine has one core. These single-proc helpers are not usable with <=1 core cpu quotas or cpu affinities that are the common configuration with containers. They can be only used when the machine or VM hosting the containers is single-proc that I believe is a rare situation.

**Comment by richlander** [comment]
Ah. That does sounds rare.

**Pull request closed without merging**
