### PR TITLE
Reenable NativeLibrary callback tests

### LINKED ISSUE #35219: CoreCLR tests on Mono runtime : Failures in Interop/NativeLibrary* tests
Several failures seen when running the Interop/NativeLibrary* tests. These are CoreCLR tests  run on the mono runtime from the dotnet\runtime repo.
Repro : Command to run individual tests : From the dotnet\runtime repo src\mono\netcore run this command or relevant one for a particular test - make run-tests-coreclr CoreClrTest="bash ../../artifacts/tests/coreclr/OSX.x64.Debug/Regressions/coreclr/Interop/NativeLibraryResolveEvent/ResolveEventTests/ResolveEventTests.sh"

1. Interop/NativeLibraryResolveCallback/CallbackTests/CallbackTests.sh
2. Interop/NativeLibraryResolveCallback/CallbackStressTest/CallbackStressTest.sh
3. Interop/NativeLibraryResolveEvent/ResolveEventTests/ResolveEventTests.sh

Full stacks below : 

Interop/NativeLibraryResolveCallback/CallbackTests/CallbackTests.sh [FAIL]
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/NativeLibraryResolveCallback/Reports/Interop.NativeLibraryResolveCallback/CallbackTests/CallbackTests.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun CallbackTests.dll ''
          Expected: 100
          Actual: 106
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/NativeLibraryResolveCallback/CallbackTests/CallbackTests.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/Interop.NativeLibraryResolveCallback/Interop.NativeLibraryResolveCallback.XUnitWrapper.cs(237,0): at Interop_NativeLibraryResolveCallback._CallbackTests_CallbackTests_._CallbackTests_CallbackTests_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         

***************************************        Interop/NativeLibraryResolveCallback/CallbackStressTest/CallbackStressTest.sh [FAIL]
          
          Unhandled Exception:
          System.DllNotFoundException: NativeLib assembly:<unknown assembly> type:<unknown type> member:(null)
             at CallbackStressTest.Main() in /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/coreclr/tests/src/Interop/NativeLibraryResolveCallback/CallbackStressTest.cs:line 152
          [ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: NativeLib assembly:<unknown assembly> type:<unknown type> member:(null)
             at CallbackStressTest.Main() in /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/coreclr/tests/src/Interop/NativeLibraryResolveCallback/CallbackStressTest.cs:line 152
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/NativeLibraryResolveCallback/Reports/Interop.NativeLibraryResolveCallback/CallbackStressTest/CallbackStressTest.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun CallbackStressTest.dll ''
          Expected: 100
          Actual: 1
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/NativeLibraryResolveCallback/CallbackStressTest/CallbackStressTest.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/Interop.NativeLibraryResolveCallback/Interop.NativeLibraryResolveCallback.XUnitWrapper.cs(140,0): at Interop_NativeLibraryResolveCallback._CallbackStressTest_CallbackStressTest_._CallbackStressTest_CallbackStressTest_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
          

***************************************        Interop/NativeLibraryResolveEvent/ResolveEventTests/ResolveEventTests.sh [FAIL]
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/NativeLibraryResolveEvent/Reports/Interop.NativeLibraryResolveEvent/ResolveEventTests/ResolveEventTests.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun ResolveEventTests.dll ''
          Expected: 100
          Actual: 105
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Interop/NativeLibraryResolveEvent/ResolveEventTests/ResolveEventTests.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/Interop.NativeLibraryResolveEvent/Interop.NativeLibraryResolveEvent.XUnitWrapper.cs(140,0): at Interop_NativeLibraryResolveEvent._ResolveEventTests_ResolveEventTests_._ResolveEventTests_ResolveEventTests_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

### PR DESCRIPTION
**Pull request by SamMonoRT**
Enable tests from https://github.com/dotnet/runtime/issues/35219 after the fixes went in
Fixes https://github.com/dotnet/runtime/issues/35219

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Review by CoffeeFlux — CHANGES_REQUESTED** [review]
Re-enabling these does nothing; those exclusions are pre-test refactoring and the tests no longer exist. The one you want to change is `<ExcludeList Include="$(XunitTestBinBase)/Interop/NativeLibrary/Callback/CallbackTests/**">`

**Review by CoffeeFlux — APPROVED** [review]

**Comment by SamMonoRT** [comment]
> Re-enabling these does nothing; those exclusions are pre-test refactoring and the tests no longer exist. The one you want to change is `<ExcludeList Include="$(XunitTestBinBase)/Interop/NativeLibrary/Callback/CallbackTests/**">`

Interesting, where did you find out these tests no longer exist. There maybe others listed here we may need to cleanup (even if it's a no-op if they are not found).

**Comment by CoffeeFlux** [comment]
I didn't do anything fancy to discover that, I just remembered Elinor's refactoring PR from a few months ago. It would not shock me if there were other no-op exclusions, but I'm not sure offhand the best way to locate them.

**Comment by CoffeeFlux** [comment]
The Mono Pri0 test build is taking unusually long for some reason, it normally takes 20-some minutes to build. I'll pull this locally and see if it happens there, but otherwise I'm not sure what's happening here. It seems to stop before `castclass032`?

**Pull request merged**
