### PR TITLE
Fix crossgen2 armel build

### PR DESCRIPTION
**Pull request by t-mustafin**
Build fails with libjitinterface_armel.so and libclrjit_unix_armel_x64.so was not found after #41126.

Signed-off-by: Timur <t.mustafin@partner.samsung.com>

### CODE REVIEW

**Comment by t-mustafin** [comment]
cc @davidwrighton @alpencolt @gbalykov

**Comment by t-mustafin** [comment]
Fail logs:
```
  ILCompiler.ReadyToRun -> /home/runtime/artifacts/bin/ILCompiler.ReadyToRun/armel/Release/ILCompiler.ReadyToRun.dll
/home/runtime/.dotnet/sdk/5.0.100-rc.1.20454.5/Microsoft.Common.CurrentVersion.targets(4689,5): error MSB3030: Could not copy the file "/home/runtime/artifacts/bin/coreclr/Linux.armel.Release/libjitinterface_armel.so" because it was not found. [/home/runtime/src/coreclr/src/tools/aot/crossgen2/crossgen2.csproj]

Build FAILED.
```
```
  crossgen2 -> /home/runtime/artifacts/bin/coreclr/Linux.armel.Release/crossgen2/crossgen2.dll 
/home/runtime/src/coreclr/src/tools/aot/crossgen2/crossgen2.csproj(108,5): error MSB3030: Could not copy the file "/home/runtime/artifacts/bin/coreclr/Linux.armel.Release/x64/libclrjit_unix_armel_x64.so" because it was not found.

Build FAILED.
```

**Comment by davidwrighton** [comment]
In general this is ok, although I hope that we can change the way the JIT handles the arm softfp calling convention so that we support cross compiling to armel with a future change.

I'll approve and merge this change once we get a cleaner test pass,

**Comment by gbalykov** [comment]
@davidwrighton can this be merged now?

**Comment by davidwrighton** [comment]
I was hoping to see a green CI run here in github. To create that you'll need to refresh the pushed commit. However, I'm also looking to enable armel via a simple command line switch, so if you can wait a couple more days, I'm going to push a change which removes the need to actually build a separate copy of the jit compiler.

**Review by davidwrighton — APPROVED** [review]
Looks good

**Pull request merged**
