### PR TITLE
Run all libraries tests in macOS-arm64 outerloop

### PR DESCRIPTION
**Pull request by sdmaclea**
If I understand it, `outerloop` does not include `innerloop` library tests.  Try running `all` tests instead.

### CODE REVIEW

**Comment by sdmaclea** [comment]
It is possible this would be much more logically belong in runtime.yml...., but with limited M1 helix capacity this might be a more efficient way to build and run all tests.

**Comment by ViktorHofer** [comment]
Right, outer loop should only run outer loop tests and not all tests. What are you trying to accomplish does better into a new pipeline IMO

**Comment by sdmaclea** [comment]
OK.  I'll let this run so that I can see the complete set of failing libraries tests, then close/modify it.

**Comment by sdmaclea** [comment]
Separate pipeline might also make sense as these tests aren't stable yet anyway...

**Comment by safern** [comment]
> Separate pipeline might also make sense as these tests aren't stable yet anyway...

Let's add them to `runtime-staging` and to not overload helix we run them only when `isFullMatrix == true`.

**Comment by sdmaclea** [comment]
> Let's add them to runtime-staging and to not overload helix we run them only when isFullMatrix == true.

The PR trigger on `runtime-staging` makes it harder to trigger a `isFullMatrix == true` run on a generic PR.  Last I knew, the only way was to trigger it from the pipeline itself.

For that reasons, I am tempted to add a new `runtime-apple-silicon` pipeline.

In  the early `linux-arm64` days (Jenkins), we would auto trigger PR runs only for PR's from specific users.  Is that still possible with the new CI system?

**Comment by safern** [comment]
> The PR trigger on runtime-staging makes it harder to trigger a isFullMatrix == true run on a generic PR. Last I knew, the only way was to trigger it from the pipeline itself.

> For that reasons, I am tempted to add a new runtime-apple-silicon pipeline.

If only a few people are going to be triggering it I don't think is bad to have to trigger it manually, it takes about the same as adding a comment on the PR itself. 

Adding a new pipeline is more maintenance and a new pipeline we need to know of, plus the runtime-staging pipeline already has the tweaks setup to not fail on PRs, that was the intention of that pipeline for new platforms. 

If you added a new pipeline would you make it available via comments only I guess?

**Comment by sdmaclea** [comment]
If I could trigger a full matrix `runtime-staging` with a comment, I would definitely go that way. If we could remove the PR trigger ...  

> I don't think is bad to have to trigger it manually

For me it is an incantation I have to look up every time.  Find the pipeline in AzDO then `refs/heads/PR/#/merge` or something like that.

> Adding a new pipeline is more maintenance and a new pipeline we need to know of

It would show up with `azp list`
I would intend to delete it as the platform stabilized.

> If you added a new pipeline would you make it available via comments only I guess?

That would be my plan.

**Comment by ViktorHofer** [comment]
I kind of prefer a new pipeline instead of moving everything into staging if the new pipeline doesn't need to run on every PR. It would actually save resources as it would only run per triggered comment.

**Comment by safern** [comment]
Sounds good to me. Given that in this case we don't want to run on every PR and have the ability to run them on specific PRs seems like the best approach.

**Pull request closed without merging**
