### PR TITLE
Handle GT_IND in optVNConstantPropCurStmt

### PR DESCRIPTION
**Pull request by EgorBo**
As discussed with @SingleAccretion filing a separate PR with this change:

It turns out that there are `GT_IND` nodes with "represents a constant" VNs e.g. known methodtable lookups.
This PR introduces a small size regression (64bit imms are heavy) with a PerfScore improvement. I might disable this for arm64 if size regression will be too bad there.

Example of an improvement:
```diff
-mov      rdx, qword ptr [rdi]
+mov      rdx, 0xD1FFAB1E      ; System.Xml.Xsl.IListEnumerator`1[System.Xml.Xsl.Qil.QilNode]
```
https://www.diffchecker.com/94HXdOJJ
```diff
-; Total bytes of code 212, prolog size 22, PerfScore 104.20
+; Total bytes of code 244, prolog size 22, PerfScore 89.90
```
Bigger size but better PerfScore.

### CODE REVIEW

**Comment by EgorBo** [comment]
@dotnet/jit-contrib @jakobbotsch @SingleAccretion PTAL

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=54302&view=ms.vss-build-web.run-extensions-tab). PerfScore diffs look like a stable improvement:
```
Total PerfScoreUnits of delta: -1587.31 (-2.68 % of base)
61 total methods with Perf Score differences (60 improved, 1 regressed).

Total PerfScoreUnits of delta: -3433.92 (-2.56 % of base)
107 total methods with Perf Score differences (105 improved, 2 regressed).

Total PerfScoreUnits of delta: -5089.00 (-1.68 % of base)
318 total methods with Perf Score differences (318 improved, 0 regressed).

Total PerfScoreUnits of delta: -55.32 (-5.57 % of base)
4 total methods with Perf Score differences (4 improved, 0 regressed).

Total PerfScoreUnits of delta: -282.38 (-2.52 % of base)
10 total methods with Perf Score differences (4 improved, 6 regressed).
```
I need this PR because I plan to mark more GT_IND node as "constant-returning" in VN.

**Comment by EgorBo** [comment]
> Are there cases where the new bigger code is measurably faster?

I wasn't able to detect anything noticeable, I decided to file this PR because my future work will need this path (namely folding GT_IND for RVA spans and GT_IND for static readonly array.Length via VN, just wanted to filter out these diffs.

LLVM-MCA example:

####  `mov      rdx, 0x7FFD6E608C68` (10 bytes)
```
Iterations:        100
Instructions:      100
Total Cycles:      28
Total uOps:        100

Dispatch Width:    6
uOps Per Cycle:    3.57
IPC:               3.57
Block RThroughput: 0.3


Instruction Info:
[1]: #uOps
[2]: Latency
[3]: RThroughput
[4]: MayLoad
[5]: MayStore
[6]: HasSideEffects (U)

[1]    [2]    [3]    [4]    [5]    [6]    Instructions:
 1      1     0.25                        movabsq	$140726455274600, %rdx


Resources:
[0]   - SKLDivider
[1]   - SKLFPDivider
[2]   - SKLPort0
[3]   - SKLPort1
[4]   - SKLPort2
[5]   - SKLPort3
[6]   - SKLPort4
[7]   - SKLPort5
[8]   - SKLPort6
[9]   - SKLPort7


Resource pressure per iteration:
[0]    [1]    [2]    [3]    [4]    [5]    [6]    [7]    [8]    [9]    
 -      -     0.25   0.25    -      -      -     0.25   0.25    -     

Resource pressure by instruction:
[0]    [1]    [2]    [3]    [4]    [5]    [6]    [7]    [8]    [9]    Instructions:
 -      -     0.25   0.25    -      -      -     0.25   0.25    -     movabsq	$140726455274600, %rdx
```

#### `mov      rdx, qword ptr [rbx]` (3 bytes)

```
Iterations:        100
Instructions:      100
Total Cycles:      57
Total uOps:        100

Dispatch Width:    6
uOps Per Cycle:    1.75
IPC:               1.75
Block RThroughput: 0.5


Instruction Info:
[1]: #uOps
[2]: Latency
[3]: RThroughput
[4]: MayLoad
[5]: MayStore
[6]: HasSideEffects (U)

[1]    [2]    [3]    [4]    [5]    [6]    Instructions:
 1      5     0.50    *                   movq	(%rbx), %rdx


Resources:
[0]   - SKLDivider
[1]   - SKLFPDivider
[2]   - SKLPort0
[3]   - SKLPort1
[4]   - SKLPort2
[5]   - SKLPort3
[6]   - SKLPort4
[7]   - SKLPort5
[8]   - SKLPort6
[9]   - SKLPort7


Resource pressure per iteration:
[0]    [1]    [2]    [3]    [4]    [5]    [6]    [7]    [8]    [9]    
 -      -      -      -     0.50   0.50    -      -      -      -     

Resource pressure by instruction:
[0]    [1]    [2]    [3]    [4]    [5]    [6]    [7]    [8]    [9]    Instructions:
 -      -      -      -     0.50   0.50    -      -      -      -     movq	(%rbx), %rdx
```

**Comment by AndyAyersMS** [comment]
I wonder about the interaction of this with CSE. If we have multiple method table indirs off the same object with known method table presumably we'll CSE the indirs and then this will replace the CSE def with a constant and then we might constant prop that down to the CSE uses, effectively undoing the CSE. When you look into regressions do you see this happening?

I'm still surprised in general that we are not CSEing large immediates for x64.

**Comment by SingleAccretion** [comment]
> then we might constant prop that down to the CSE uses, effectively undoing the CSE

Propagation ignores locals created by CSE, so this should not happen.

**Comment by EgorBo** [comment]
> I'm still surprised in general that we are not CSEing large immediates for x64.

We do that on x64 for certain handles after https://github.com/dotnet/runtime/pull/70580
but so far regressions are because plain constant handles are lighter than indirect loads (in terms of CSE weight)

**Comment by AndyAyersMS** [comment]
Can you undo the SPMI change so we can see the code size impact?

**Comment by AndyAyersMS** [comment]
Thanks. The bulk of the size diffs seem to be in artificial test cases, so I'm not worried about them.

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=61532&view=ms.vss-build-web.run-extensions-tab)

**Review by AndyAyersMS — APPROVED** [review]

**Pull request merged**
