### PR TITLE
Remove _caseInsensitive field from RegexInterpreter

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Review by joperezr — APPROVED** [review]
Sorry that I missed this.

**Comment by stephentoub** [comment]
@danmoseley, CI didn't run.

**Comment by danmoseley** [comment]
?! Status was green wasn't it?

**Comment by danmoseley** [comment]
I guess it hadn't started yet for some reason. I normally double check - my bad.

**Comment by stephentoub** [comment]
> ?! Status was green wasn't it?

It's always green before the various legs are initiated. I only opened this PR a few minutes ago.

**Comment by joperezr** [comment]
Yeah, looks like for some reason the AzDO web hook wasn't triggered, I've seen this happen before but very rarely a. We can keep an eye on rolling build to make sure this didn't break anything, but I doubt it

**Comment by stephentoub** [comment]
I'll assume it's just you have a lot of confidence in me ;-)

**Pull request merged**
