### PR TITLE
Refactor CMake system to allow cross OS DAC compile

### PR DESCRIPTION
**Pull request by sdmaclea**
Add CLR_CMAKE_HOST_OS

Add rules to determine which cross OS combinations are valid

Make add_defintions depend on TARGET OS properties

Wherever reasonable make C++ define defintions depend on runtime target
rather than host.

### CODE REVIEW

**Comment by sdmaclea** [comment]
This collided with @am11's #1753.  I have fixed the merge conflicts.

**Comment by am11** [comment]
Currently `src/coreclr` and `src/installer` are sharing host definitions via `eng/native/configureplatform.cmake`. We can make `src/libraries/Native/Unix/CMakeLists.txt` also depend on it. Then the will be only one file setting `CLR_CMAKE_{HOST,TARGET}_PLATFORM_*` in the entire repo.

**Comment by jkotas** [comment]
The build break on musl is likely introduced by these changes. Could you please take a look?

**Comment by sdmaclea** [comment]
Thanks @jkotas.  I found the error.  I neglected to set `CLR_CMAKE_TARGET_LINUX` for `alpine` and `tizen`.  This disabled `/PerfMap` support in crossgen and caused the failure.

**Review by jkotas — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]

**Pull request merged**
