### PR TITLE
Recursive validation for Options

### LINKED ISSUE #36093: [Extensions.Options] ValidateDataAnnotation doesn't work when classes have properties that also have DataAnnotations on their members
### Describe the bug
When using ValidateDataAnnotations to validate a configuration hierarchy, you can only validate top level members of the class. Any properties that are types which also include validation are NOT validated. 

Perhaps this was viewed as a design decision, but I think it'd be a lot more consistent if automatic data annotation validation worked in the same fashion as mvc model validation.

### To Reproduce
1. Design the classes which represent the nested configuration
```c#
public class AnnotatedOptions
{
    [Required]
    public string Required { get; set; }

    [StringLength(5, ErrorMessage = "Too long.")]
    public string StringLength { get; set; }

    [Range(-5, 5, ErrorMessage = "Out of range.")]
    public int IntRange { get; set; }

    public AnnotatedOptionsSubsection AnnotatedOptionSubsection { get; set; }
}

public class AnnotatedOptionsSubsection
{
    [Range(-5, 5, ErrorMessage = "Really out of range.")]
    public int IntRange2 { get; set; }
}
```
2. Register the options
```c#
var services= new ServiceCollection();
services
     .AddOptions<AnnotatedOptions>()
     .Configure(o =>
                {
                    o.StringLength = "111111";
                    o.IntRange = 10;
                    o.AnnotatedOptionSubsection = new AnnotatedOptionsSubsection
                    {
                        IntRange2 = 10000
                    };
                })
       .ValidateDataAnnotations();
```
3. Set up a controller which retrieves the options
```c#
[Route("api/[controller]")]
[ApiController]
public class ConfigController : ControllerBase
{
    private readonly AnnotatedOptions _configuration;

    public ConfigController(IOptionsMonitor<AnnotatedOptions> configuration)
    {
        try
        {
            _configuration = configuration.CurrentValue;
        }
        catch (OptionsValidationException ex)
        {
            throw new Exception(string.Join(@"\r\n", ex.Failures), ex);
        }
    }

    // GET api/config/
    [HttpGet("{configKey}")]
    public ActionResult<AnnotatedOptions> Get()
    {
        return _configuration;
    }
}
```

4. Invoke the controller method and observe the error results
````
System.Exception: DataAnnotation validation failed for members Required with the error 'The Required field is required.'.
DataAnnotation validation failed for members StringLength with the error 'Too long.'.
DataAnnotation validation failed for members IntRange with the error 'Out of range.'. ---> Microsoft.Extensions.Options.OptionsValidationException: Exception of type 'Microsoft.Extensions.Options.OptionsValidationException' was thrown.
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.get_CurrentValue()
   at PF.ClinicalEndpoint.Host.Controllers.ConfigController..ctor(IOptionsMonitor`1 configuration) in C:\dev\test\ClinicalEndpoint\src\Host\Controllers\ConfigController.cs:line 19
   --- End of inner exception stack trace ---
   at PF.ClinicalEndpoint.Host.Controllers.ConfigController..ctor(IOptionsMonitor`1 configuration) in C:\dev\test\ClinicalEndpoint\src\Host\Controllers\ConfigController.cs:line 23
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at PF.Core.WebApi.Middleware.ExceptionHandlingMiddleware.InvokeAsync(HttpContext httpContext)
   at PF.Core.WebApi.Middleware.RequestLoggingMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Expected behavior
Another error in the list of failures for the `IntRange2` field which reads as follows
`DataAnnotation validation failed for members IntRange2 with the error 'Really out of range.'`

### PR DESCRIPTION
**Pull request by SteveDunn**
Fixes #36093

### CODE REVIEW

**Comment by eerhardt** [comment]
I think this should be solved at a lower level. I don't think this is the correct level to solve this. If we have scenarios for Validator to validate complex types, we should fix it in System.ComponentModel.DataAnnotations.

See related:

* https://github.com/dotnet/runtime/issues/31400
* https://github.com/dotnet/aspnetcore/issues/28640

**Comment by SteveDunn** [comment]
> I think this should be solved at a lower level. I don't think this is the correct level to solve this. If we have scenarios for Validator to validate complex types, we should fix it in System.ComponentModel.DataAnnotations.
> 
> See related:
> 
> * [Add support for validating complex or collection properties using System.ComponentModel.DataAnnotations.Validator #31400](https://github.com/dotnet/runtime/issues/31400)
> * [Consider shipping ObjectGraphDataAnnotationsValidator / ValidateComplexTypeAttribute aspnetcore#28640](https://github.com/dotnet/aspnetcore/issues/28640)

From reading the original Issue, I was under the impression that this should be limited to `Options` and _not_ validation in general. I'm happy to look at implementing it in that layer. Is there a consensus on this approach?

**Comment by eerhardt** [comment]
> Is there a consensus on this approach?

@ajcvickers @lajones - thoughts here? This seems like a commonly requested feature in DataAnnotations. ASP.NET Blazor wants it, multiple members of the community want it [here](http://www.technofattie.com/2011/10/05/recursive-validation-using-dataannotations.html) and [here](https://www.nuget.org/packages/DataAnnotationsValidator/), and here Options validation wants it.

My thinking is this should be solved in the lower level so upstack callers don't need to create multiple different solutions to this problem.

cc @jeffhandley

**Comment by eerhardt** [comment]
Pinging @SteveSandersonMS as well - since he may have some insight on how ASP.NET plans on supporting validating complex properties.

**Comment by SteveSandersonMS** [comment]
While we're adding people, I'll bring in @DamianEdwards who's been working on a validator library recently and will likely have opinions about what our product goals should be in this area.

Our current non-official solution (`ObjectGraphDataAnnotationsValidator`) remains a candidate for .NET 7 planning - https://github.com/dotnet/aspnetcore/issues/28640.

**Comment by DamianEdwards** [comment]
Thanks @SteveSandersonMS. The library is [MiniValidation](https://github.com/DamianEdwards/MiniValidation) and indeed it supports validating complex properties. It's built atop the `System.ComponentModel.DataAnnotations.Validator` class. The other thing it aims to provide is a single line calling pattern (`MiniValidator.TryValidate(object target, out IDictionary<string, string[]> errors`) and providing the results in a [JSON Problem Details](https://datatracker.ietf.org/doc/html/rfc7807?msclkid=a97c1558b4e611ec9d22187016c1a040) friendly shape (`IDictionary<string, string[]>`).

I agree with @eerhardt that ideally we should solve this in the `System.ComponentModel.DataAnnotations` layer so that all frameworks that leverage the types there for validation could realize the benefit. The calling pattern there is still somewhat cumbersome and inefficient but individual frameworks tend to hide the former anyway and for cases like ASP.NET Core Minimal APIs where the methods would need to be called directly, libraries like mine could act as the nicer interaction model.

**Comment by SteveDunn** [comment]
I'm happy to move this `System.ComponentModel.DataAnnotations` then. Would this work still fit within the remit of the original Issue, or would a new Issue, and a potential API Proposal need creating?

**Comment by eerhardt** [comment]
> Would this work still fit within the remit of the original Issue, or would a new Issue, and a potential API Proposal need creating?

@ajcvickers - thoughts?

I think the original issue proposed by @pranavkm had some advantages. Namely, it doesn't recurse blindly - it only follows complex properties if the model author opts-in to the complex property being validated as well.

**Comment by DamianEdwards** [comment]
@eerhardt if we wish to have these changes be consumable by frameworks like ASP.NET Core MVC, Blazor, etc. then requiring the attribute might make that difficult as existing models won't have it. Perhaps we could consider APIs for both patterns, i.e. default mode which only recurses if attribute is found, opt-in mode that enables recursion at the call site (or forcibly disables it even ignoring the attribute if found).

**Comment by eerhardt** [comment]
My thinking was that it is the model author that decides what should and shouldn't be validated. It isn't really up to ASP.NET MVC or Blazor, is it? The frameworks just say "validate this object", and the object's attributes are what declares what should and shouldn't be validated.

> as existing models won't have it

That was my intention. The behavior is the same until the model is updated to say "drill into this property and validate it as well".

**Comment by DamianEdwards** [comment]
@eerhardt my points was these frameworks already to recursive validation of complex properties today, without the attribute, and that if we update `System.ComponentModel.DataAnnotations` to support recursive validation it would be good to be able to use it while maintaining the existing framework default behavior.

**Comment by maryamariyan** [comment]
Closing this PR as per conversation above. Will take this on in the issue page and relabed to `System.ComponentModel.DataAnnotations`

**Comment by SteveDunn** [comment]
@maryamariyan @eerhardt @SteveSandersonMS @DamianEdwards - new PR with this moved down to `System.Component.DataAnnotations`: https://github.com/dotnet/runtime/pull/67810

**Pull request closed without merging**
