### PR TITLE
[browser] Remove duplicated marshaling of return value for JSExport

### LINKED ISSUE #92400: [browser] __arg_return.ToJS(__retVal); is generated twice in JSExport
```c#
try
{
    __retVal = Sample.Test.X();
    __arg_return.ToJS(__retVal);
}
catch (global::System.Exception ex)
{
    __arg_exception.ToJS(ex);
}

// Marshal - Convert managed data to native data.
__arg_return.ToJS(__retVal);
```

### PR DESCRIPTION
**Pull request by maraf**
- Remove duplicated marshaling of return value for JSExport
- Move unmarshal arguments into try block, so it behaves the as marshaling return value. Exceptions from unmarshal and marshal are all transfered to JS as exception

Before

```c#
[global::System.Diagnostics.DebuggerNonUserCode]
internal static unsafe void __Wrapper_X_1038483311(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
{
    int a;
    int b;
    ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __arg_exception = ref __arguments_buffer[0];
    ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __arg_return = ref __arguments_buffer[1];
    int __retVal = default;
    // Setup - Perform required setup.
    ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __b_native__js_arg = ref __arguments_buffer[3];
    ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __a_native__js_arg = ref __arguments_buffer[2];
    // Unmarshal - Convert native data to managed data.
    __b_native__js_arg.ToManaged(out b);
    __a_native__js_arg.ToManaged(out a);
    try
    {
        __retVal = Sample.Test.X(a, b);
        __arg_return.ToJS(__retVal);
    }
    catch (global::System.Exception ex)
    {
        __arg_exception.ToJS(ex);
    }

    // Marshal - Convert managed data to native data.
    __arg_return.ToJS(__retVal);
}
```

After
```c#
[global::System.Diagnostics.DebuggerNonUserCode]
internal static unsafe void __Wrapper_X_313009907(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
{
    int a;
    int b;
    ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __arg_exception = ref __arguments_buffer[0];
    ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __arg_return = ref __arguments_buffer[1];
    int __retVal = default;
    // Setup - Perform required setup.
    ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __b_native__js_arg = ref __arguments_buffer[3];
    ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __a_native__js_arg = ref __arguments_buffer[2];
    try
    {
        // Unmarshal - Convert native data to managed data.
        __b_native__js_arg.ToManaged(out b);
        __a_native__js_arg.ToManaged(out a);
        __retVal = Sample.Test.X(a, b);
        // Marshal - Convert managed data to native data.
        __arg_return.ToJS(__retVal);
    }
    catch (global::System.Exception ex)
    {
        __arg_exception.ToJS(ex);
    }
}
```

Fixes https://github.com/dotnet/runtime/issues/92400

### CODE REVIEW

**Comment by pavelsavara** [comment]
This may also need fix in Net7

**Comment by pavelsavara** [comment]
I think it's the second call to `__arg_return.ToJS(__retVal);` which need to be removed, because it should not be marshaled if there was an exception.

**Comment by maraf** [comment]
> I think it's the second call to `__arg_return.ToJS(__retVal);` which need to be removed, because it should not be marshaled if there was an exception.

If we remove the second one, any exception from the marshalling will be swallowed. It will be different for arguments and return value.

**Comment by maraf** [comment]
The code for .NET 7 is fine and it had the return value marshalling inside of try statement

```c#
internal static unsafe void __Wrapper_X_577139203(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* __arguments_buffer)
{
    int a;
    int b;
    ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __arg_exception = ref __arguments_buffer[0];
    ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __arg_return = ref __arguments_buffer[1];
    int __retVal;
    // Setup - Perform required setup.
    ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __a_native__js_arg = ref __arguments_buffer[2];
    ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument __b_native__js_arg = ref __arguments_buffer[3];
    // Unmarshal - Convert native data to managed data.
    __b_native__js_arg.ToManaged(out b);
    __a_native__js_arg.ToManaged(out a);
    try
    {
        __retVal = Sample.Test.X(a, b);
        __arg_return.ToJS(__retVal);
    }
    catch (global::System.Exception ex)
    {
        __arg_exception.ToJS(ex);
    }
}
```

**Comment by lewing** [comment]
I assume we will want a backport to 8

**Review by lewing — APPROVED** [review]

**Comment by maraf** [comment]
Discussed offline
- Move all marshalling (parameter+return value) to try-catch block

**Comment by pavelsavara** [comment]
Could we please add unit test similar to JSImportGenerator.UnitTest\Compiles.cs

So that we compare explicitly the generated code as text. 

There is JSImportGenerator.UnitTest\JSTestUtils.cs which could dump it as a text.

**Comment by pavelsavara** [comment]
Ideally also one for `JSImport` and if you add `Task` and `Func<>` as parameters it would cover a lot.

**Comment by maraf** [comment]
Missing automated tests tracked in https://github.com/dotnet/runtime/issues/92870

**Review by pavelsavara — APPROVED** [review]

**Pull request merged**
