### PR TITLE
Fix for issue #80350 tracking runtime deficiencies in the presence of static virtual method reabstraction

### PR DESCRIPTION
**Pull request by trylek**
This change fixes the issue

https://github.com/dotnet/runtime/issues/80350

that uncovered several inconsistencies in the CoreCLR runtime
w.r.t. static virtual methods. In particular, reabstraction (declaring
an abstract explicit override of a static virtual method in a derived
interface) turned out to be causing runtime issues. As part of
the change I'm also fixing the reabstraction unit test
svm_diamondshape as it turns out Roslyn emits the method flags
in a slightly different manner than I originally expected in the
hand-written IL test.

Thanks

Tomas

P.S. This PR would be normally an obvious adept for nominating @davidwrighton as the reviewer. As David is on parental leave right now, I am designating a larger reviewer group to get more pairs of eyes to see the change and also ideally proliferate CoreCLR typesystem knowledge to improve our agility the next time David's not available.

### CODE REVIEW

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by trylek** [comment]
@SamMonoRT - could you please advise someone who might be able to help me fix the Mono issues in this PR? I have updated the <code>svm_diamondshape.il</code> test by marking the static virtual method reabstraction as 'virtual' as I found out that's what Roslyn does and several Mono legs now fail in the test due to some VTable setup error. Thanks a lot!

**Comment by trylek** [comment]
Based on offline discussion with @BrzVlad I have updated this PR by adding a temporary exclusion of the <code>svm_diamondshape</code> tests on Mono where they seem to be crashing VTable construction due to some subtle bug that may take a bit to fix. I plan to merge this in if the PR run finishes fine unless anyone has objections.

Thanks

Tomas

**Comment by trylek** [comment]
The only failure is tracked as #81901 and the fix is currently pending PR under #82309, merging in.

**Pull request merged**
