### PR TITLE
Switch 8.0 build images to Azure Linux 3.0

### PR DESCRIPTION
**Pull request by richlander**
First test of using Azure Linux 3.0 for .NET 8, like we do for .NET 9.

Related: 

- #100942 
- https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1173

@sbomer @jkotas

### CODE REVIEW

**Comment by richlander** [comment]
The failure case seems to relate to ICU. I assume tests use the ICU in the host not the sysroot.

- https://dev.azure.com/dnceng-public/public/_build/results?buildId=774216&view=logs&j=2e4378a6-e59e-5bf9-cb9f-6a73eb8f6782&t=d0d062b2-b2fe-5c87-5748-c09413d137c7&l=525
- https://github.com/dotnet/runtime/pull/106170/checks?check_run_id=28716200426

There is a bump in ICU version due to the image change.  It doesn't seem to be bothering the other architectures, however.

```bash
rich@mazama:~$ docker run --rm -it mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-amd64 tdnf list --installed icu
Loaded plugin: tdnfrepogpgcheck
icu.x86_64                                   68.2.0.9-1.cm2            @System
rich@mazama:~$ docker run --rm -it mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-cross-amd64-net8.0 tdnf list --installed icu
Loaded plugin: tdnfrepogpgcheck
icu.x86_64                                   72.1.0.3-1.azl3           @System
```

**Comment by richlander** [comment]
Thanks for the change @elinor-fung. It makes sense. I am still wondering why this is happening. I just installed the SDK (for `.tar.gz` in the Azure Linux image, ran `dotnet new` and ran the app. It worked fine. That leads me to believe that the installer leg is not run in the Azure Linux image or there is something else at play.

**Comment by richlander** [comment]
OK. @sbomer just discovered that this app is running with .NET Core 3.0 and that it is incompatible with the new ICU. Is that right? If so, shouldn't this test be deleted? It doesn't seem to be adding any obvious value.

**Comment by richlander** [comment]
That context helps @elinor-fung. Thanks for the explanation. Let's just stay the course and continue to focus on `main` for improvements.

**Comment by jkotas** [comment]
@carlossanlop Any concerns with getting this merged? This change is required to keep the build images compliant.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
