### PR TITLE
[wasm-mt] Log exit codes in browser samples to prevent tests from timeouting

### PR DESCRIPTION
**Pull request by simonrozsival**
**WIP** - don't reveiw.

After recent changes the `src/mono/sample/wasm/browser-threads/main.js` script stopped printing `WASM EXIT <exit code>` that xharness is looking for. The CI test then fails:

```
[17:40:59] info: Hello, World!
[17:40:59] info: [MONO] Running class .cctor for System.Runtime.InteropServices.JavaScript.JavaScriptExports/<>c from 'System.Runtime.InteropServices.JavaScript.dll'
[17:55:52] info: Waiting to flush log messages with a timeout of 120 secs ..
[17:55:52] fail: Flushing log messages failed with: System.OperationCanceledException: The operation was canceled.
                    at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
                    at System.Threading.Channels.ChannelReader`1.ReadAllAsync(CancellationToken cancellationToken)+MoveNext()
                    at System.Threading.Channels.ChannelReader`1.ReadAllAsync(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.RunAsync(CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 66
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.RunAsync(CancellationToken token) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 66
                    at Microsoft.DotNet.XHarness.CLI.Commands.Wasm.WasmTestMessagesProcessor.CompleteAndFlushAsync(Nullable`1 timeout) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/WASM/WasmTestMessagesProcessor.cs:line 106. Ignoring.
[17:55:52] fail: Tests timed out. Killing driver service pid 15988
[17:55:52] fail: Application has finished with exit code TIMED_OUT but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

see https://dev.azure.com/dnceng/public/_build/results?buildId=1961582&view=logs&j=5e0663a6-779c-5be5-6d4c-61295b043a58&t=a6da8bfe-2e5e-5d0c-f321-5907e9da992a

The `browser-eventpipe` sample also runs in CI and it doesn't exit at any point (#74487). That makes sense when it runs in the browser but it doesn't work in CI (see https://dev.azure.com/dnceng/public/_build/results?buildId=1961582&view=logs&j=92c81310-cb26-5923-f96e-b7c73963fa3d&t=0aa9a844-8701-5b62-3bc4-3a39f7c23650). I tried adding the `wasm_exit` code into the sample, but it didn't solve the issue. The sample's probably gonna require a bit more restructuring or replacing with a tailored functional test.

### CODE REVIEW

**Comment by pavelsavara** [comment]
You can use internal
```
        .withElementOnExit()
        .withExitCodeLogging()
```

**Comment by simonrozsival** [comment]
@pavelsavara thanks for showing me those APIs. It was all that was needed. I updated the PR and the threading tests are still passing.

**Review by pavelsavara — APPROVED** [review]

**Pull request merged**
