### PR TITLE
Use HashCode.Combine instead of ValueTuple.GetHashCode in MatchingState

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by bollhals** [comment]
Out of personal interest / trying to learn, what's the difference between those two if you don't mind me asking?

**Comment by stephentoub** [comment]
ValueTuple uses HashCode.Combine as its GetHashCode implementation. Creating a tuple and then directly calling its GetHashCode is just doing some unnecessary work to create the tuple and then unwrap its fields to get to the HashCode.Combine call.

**Comment by AaronRobinsonMSFT** [comment]
@bollhals You can see the implementation of `ValueTuple<T1,T2>::GetHashCode()` below.

https://github.com/dotnet/runtime/blob/d5f084e5a36eec83f60beccfed9ded3f4473a5bf/src/libraries/System.Private.CoreLib/src/System/ValueTuple.cs#L557-L565

**Comment by bollhals** [comment]
Well, ... I should've been able to figure this out myself. Thanks for the explanations!

**Pull request merged**
