### PR TITLE
changes based on Issue #28731 ((System.Numerics) Cross Product for Ve…

### PR DESCRIPTION
**Pull request by micampbell**
…ctor2 and Vector4). Added a Cross (product) function for Vector2 and Vector4.

### CODE REVIEW

**Comment by micampbell** [comment]
please see discussion at https://github.com/dotnet/runtime/issues/28731

**Comment by saucecontrol** [comment]
`[Intrinsic]` indicates that the JIT has a special implementation of a method it can emit in place of the managed version.  For example, the SIMD versions of Dot Product are implemented in the JIT here: https://github.com/dotnet/runtime/blob/ffcb4b4535f1400029f97eceb129a4154b529747/src/coreclr/src/jit/simdcodegenxarch.cpp#L2122-L2404

It's not likely you can improve on `Vector2.Cross` with SIMD, so you'll probably want to just move that  as is into Vector2.cs and remove the `[Intrinsic]` attribute.

For `Vector4.Cross`, a SIMD version would be faster, but it probably won't be necessary to make it a JIT intrinsic once https://github.com/dotnet/runtime/issues/952 is done (https://github.com/dotnet/runtime/pull/1280 covered part of this).

Once you can cast `Vector4` to `Vector128<float>` and back for free, you'll be able to write the SIMD version using `System.Runtime.Intrinsics` with a scalar fallback in the same way some of the `Matrix4x4` methods are implemented now.  e.g. https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Private.CoreLib/src/System/Numerics/Matrix4x4.cs#L1755-L1802

That SIMD version might be able to wait for a followup PR, so you could move that one as-is to `Vector4.cs` and remove the `[Intrinsic]` attribute from that as well.

**Comment by micampbell** [comment]
> `[Intrinsic]` indicates that the JIT has a special implementation of a method it can emit in place of the managed version. For example, the SIMD versions of Dot Product are implemented in the JIT here:

Thanks for the info. I wasn't really understanding the Intrinsic until now. The CPP code for dot product is beyond me, but it leads me to a new idea. In the vector and matrix classes there are various methods that invoke simple math operations: a * b + c * d (like a dot product) or a * b - c * d (like in my suggested cross product or in the determinant and inverse functions). Actually, the latter "difference of products" is really what we see alot in `GetDeterminant`, `Invert`, and `Cross`. It would seem a special SIMD function doing a * b - c * d could be used to great effect.

**Comment by saucecontrol** [comment]
Dot product is a no-brainer for SIMD acceleration because SSE4.1 has a single instruction ([`DPPS`](https://www.felixcloutier.com/x86/dpps)) that computes a dot product on 2-4 elements of a float vector.  AVX further expands that with `VDPPS`, which can compute two dot products in a single instruction.  There is no equivalent instruction for the difference of products.

The JIT code has fallback implementations to use other SIMD instructions when SSE4.1 is not available or when the element type is not float.  It works out that the SIMD implementation is actually less efficient than the scalar implementation for `Vector2` when the SSE fallback is used:

https://github.com/dotnet/runtime/blob/ffcb4b4535f1400029f97eceb129a4154b529747/src/coreclr/src/jit/simdcodegenxarch.cpp#L2252-L2258

However, because maintenance of the JIT code is very expensive relative to maintenance of the managed code, the work has not been done to optimize for every case.

The ability to use the individual SIMD instructions from `System.Runtime.Intrinsics` does open up the possibility of optimizing more areas of `System.Numerics` without the cost of writing new higher-level Intrinsics, and it's likely best to approach any 'difference of product' optimizations that way.

**Comment by danmosemsft** [comment]
@tannergooding what's the next action here? Should we close this pending the issue ref'd above?

**Comment by tannergooding** [comment]
The referenced issue is resolved and shouldn't block optimizing the `Vector4` implementation. It's only `Vector2/3` where the conversion is not quite zero-cost.

**Comment by micampbell** [comment]
I'm sorry for my delay in responding. I've not had the bandwidth or resources during quarantine to respond. In re-reading @saucecontrol 's posts, I'm still wondering if the SSE4.1 Dot implementation could be used to speed up functions like ```Cross```, ```GetDeterminant```, and ```Invert```. One could just call Dot in the body of these functions. Would it be faster? For example:
```
        public static double Cross(Vector2 value1, Vector2 value2)
        {
            //instead of return value1.X * value2.Y - value1.Y * value2.X;
            return Dot(value1, new Vector2(value2.Y, -value2.X));
        }
```

**Comment by tannergooding** [comment]
I wouldn't expect so for `Vector2`, the actual cost of building the new vector is likely greater than the `mul, mul, sub` that would otherwise exist.

**Comment by stephentoub** [comment]
@micampbell, are you still working on this, or should it be closed for now?  Thanks.

**Comment by jeffhandley** [comment]
@tannergooding @pgovind Is this something you'd like to pick up and finish, or should we go ahead and close it?

**Comment by tannergooding** [comment]
I think this can be closed for now and the original issue marked up for grabs again, possibly with revisiting the names used.
In particular, there was some discussion around what this is doing for the 4D cross product vs what other libraries, such as DirectX Math do.

If you take a cross product to be essentially that `Cross(u, v)` is always perpendicular to both `u` and `v` and then extrapolate from that, then you will eventually conclude that for a cross-product of an `n` dimensional vector, you need `n-1` inputs.

### Vector2
This means that a "true" 2-dimensional cross product takes one input and is effectively `(Y, -X)`.
The operation being exposed here, in DXMath, and that is commonly exposed for for 2D graphics is actually the wedge product: https://mathworld.wolfram.com/WedgeProduct.html

### Vector4

DXMath exposes a four-dimensional cross product as taking 3 inputs so it can compute a truly perpendicular `Vector4` result
What is defined here is more akin to computing the 3D cross product and additionally multiplying the W components together, which while it makes sense for various scenarios, I'm no longer convinced `Cross Product` is what it should be called (especially when compared to what other similar math libraries expose/name).

**Pull request closed without merging**
