### PR TITLE
disable NTLM tests on RedHat.7

### PR DESCRIPTION
**Pull request by wfurt**
contributes to #83540
It seems like something got broken by OS update

### CODE REVIEW

**Review by hoyosjs — APPROVED** [review]

**Review by carlossanlop — APPROVED** [review]
Assuming the failure goes away in the CI, LGTM.

We will need a backport to 7.0 for sure.

I think we also need it in 6.0, but let me double check.

Thanks for the help!

**Comment by wfurt** [comment]
I think it will need more fixes for System.Net.Security. Mail & Http seems ok now with this change.

**Comment by carlossanlop** [comment]
I just confirmed. We also need this backported to 6.0 as well.

**Comment by wfurt** [comment]
windows failure is unrelated

**Comment by karelz** [comment]
@wfurt should we mark the tracking issue as disabled-test, or is it by design disabling of the test for good?

**Pull request merged**
