### PR TITLE
Cache copies of register sets and data that varies with AVX512

### PR DESCRIPTION
**Pull request by BruceForstall**
1. Fix availableRegCount to only be stored in LSRA, where it is used.
2. Make copies of rbmAllFloat/rbmFltCalleeTrash to CodeGen and LSRA classes during construction, so access is "closer", in case TP is impacted. (This also makes it possible to define inline accessors in the `emitter` class.)

### CODE REVIEW

**Comment by kunalspathak** [comment]
Related https://github.com/dotnet/runtime/issues/81847

**Review by tannergooding — APPROVED** [review]
Nice small wins back from the initial TP regression!

**Comment by BruceForstall** [comment]
cc @kunalspathak @anthonycanino @dotnet/jit-contrib

**Review by kunalspathak — APPROVED** [review]
LGTM. Nice TP win!

**Comment by BruceForstall** [comment]
> Changes look good to me. Do we know the absolute tp diff now?

Compared to pre https://github.com/dotnet/runtime/pull/79544? No, and the improvement is still small compared to that regression.

**Pull request merged**
