### PR TITLE
CMake support in VS open folder for coreclr

### PR DESCRIPTION
**Pull request by huoyaoyuan**
#40049

I don't add remote Linux support because I don't have the environment set.

Making it build is quite easy at least for Windows MSVC. Making debugger works is somehow complicated.

Note: after playing with CMake a while and deleting coreclr artifacts for some times, `build.cmd clr` is failing for can't find `bin\coreclr\Windows.x64.Debug\dotnet-pgo\shims\...`. Is it caused by some build steps not included?

### CODE REVIEW

**Comment by agocke** [comment]
@huoyaoyuan Would you be willing to commit to maintaining this support? No one on the team uses it, so unless we have someone to maintain it I fear that it will simply break later.

**Comment by huoyaoyuan** [comment]
> Would you be willing to commit to maintaining this support?

I will be busy in a couple of months, but would be available after then. I'm willing to maintain this, and expect my further contribute for CLR done under this.

It seems that current form may cause some collision with command line build. Should I put the artifacts under some `ide` directory?

**Comment by agocke** [comment]
I think @jkoritzinsky would be the best person to review this, I'm not sure of the details. I just wanted to make sure someone was going to look at it periodically and fix it if it gets broken. No specific timeline, just a general commitment.

**Review by jkoritzinsky — APPROVED** [review]
This LGTM to my knowledge. We shouldn't put this in an "ide" folder as that would break the MSBuild support we still have.

This isn't perfect support, but it's definitely better than nothing. If the initial load into VS is quick, then this is definitely better than the last time I tried this.

**Pull request merged**
