### PR TITLE
Reset GTF_VAR_USEASG if the combined LCL_FLD becomes a full def

### LINKED ISSUE #31615: AccessViolation trying to compile Method
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-beta0006" />
  </ItemGroup>
  
</Project>
```
```csharp
class Program
{
    static void Main(string[] args)
    {
        SixLabors.ImageSharp.PixelFormats.ColorBuilder<SixLabors.ImageSharp.PixelFormats.RgbaVector>.FromHex("test");
    }
}
```

Repro steps:
1. Publish the above as standalone (`dotnet publish -c Release -r win-x64`)
2. Overwrite the runtime and framework in the standalone publish with the current master build from dotnet/runtime
3. `set COMPlus_TieredCompilation=0`
4. Run the program

Result:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at SixLabors.ImageSharp.PixelFormats.ColorBuilder`1[[SixLabors.ImageSharp.PixelFormats.RgbaVector, SixLabors.ImageSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FromHex(System.String)
   at Program.Main(System.String[])
```

### PR DESCRIPTION
**Pull request by mikedn**
Fixes #31615

### CODE REVIEW

**Comment by mikedn** [comment]
Surgical fix, of course. The proper fix would be to remove `GTF_VAR_USEASG` completely.

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib

**Review by AndyAyersMS — APPROVED** [review]
Thanks!

**Comment by AndyAyersMS** [comment]
@mikedn we still need a fix here; any objection to me reviving your PR?

**Comment by mikedn** [comment]
@AndyAyersMS I would prefer that you do not do that. Thanks.

**Pull request closed without merging**
