### PR TITLE
[release/6.0] Add RID for Alpine 3.19 / 3.20

### LINKED ISSUE #96155: Add RIDs for Alpine 3.19
[Alpine 3.19](https://alpinelinux.org/posts/Alpine-3.19.0-released.html) was released on 2023-12-07. 

I believe we need the RID ASAP due to https://github.com/PowerShell/PowerShell/issues/20945 which is blocking PowerShell support in https://github.com/dotnet/dotnet-docker/pull/5065.

Related: https://github.com/dotnet/core/issues/9013

### PR DESCRIPTION
**Pull request by ayakael**
Adds RID for Alpine 3.19 and 3.20

Fixes https://github.com/dotnet/runtime/issues/96155

Addresses https://github.com/dotnet/dotnet-docker/issues/5243

### CODE REVIEW

**Comment by ayakael** [comment]
I've skipped main because we're not interested in this on main anymore, but tell me if I should up-port this somewhere.

**Review by agocke — APPROVED** [review]

**Comment by agocke** [comment]
> I've skipped main because we're not interested in this on main anymore, but tell me if I should up-port this somewhere.

Unfortunately we might need to push this forward because of the back-compat switch.

**Comment by ayakael** [comment]
> > I've skipped main because we're not interested in this on main anymore, but tell me if I should up-port this somewhere.
> 
> Unfortunately we might need to push this forward because of the back-compat switch.

This PR doesn't apply to master since there are no more non-portable RIDs in RID graph. Do you mean I have to up-port to 7.0?

**Review by carlossanlop — APPROVED** [review]
@ayakael I added the missing required Microsoft.NETCore.Platforms change.

I asked if we would still want a 7.0 equivalent RID update and it has been decided that we won't take one, as that branch only has one more month to live before EOL and it is currently only taking security fixes.

**Comment by elinor-fung** [comment]
> > > I've skipped main because we're not interested in this on main anymore, but tell me if I should up-port this somewhere.
> > 
> > 
> > Unfortunately we might need to push this forward because of the back-compat switch.
> 
> This PR doesn't apply to master since there are no more non-portable RIDs in RID graph. Do you mean I have to up-port to 7.0?

Agree we shouldn't need to apply to main. For the back-compat switch in 8.0+, the intent was that it would use to the 'frozen' non-portable RID graph - and we wouldn't update that non-portable RID graph (anything new should go through the new portable behaviour).

**Review by elinor-fung — APPROVED** [review]

**Comment by carlossanlop** [comment]
@ayakael there is a build failure:

```
##[error]src/libraries/Microsoft.NETCore.Platforms/src/runtimeGroups.props(285,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) The generated CompatibilityMap differs from runtime.compatibility.json and UpdateRuntimeFiles was not specified.  Please specify UpdateRuntimeFiles=true to commit the changes.
```

**Comment by ayakael** [comment]
@elinor-fung I right, I see the lack of ppc64le + armv6 for the 6.0 release. Thanks for catching that!

**Pull request merged**
