### PR TITLE
Change signature for diagnostic binaries

### PR DESCRIPTION
**Pull request by hoyosjs**
- Add DAC signature infrastructure
- Try using a .NET 6 SDK to enable signing

Use a signing infrastructure orthogonal to microbuild to use other certs for diagnostic binaries.

cc: @dotnet/dotnet-diag @leculver

### CODE REVIEW

**Comment by hoyosjs** [comment]
Validation https://dev.azure.com/dnceng/internal/_build/results?buildId=1957924&view=results

**Comment by hoyosjs** [comment]
@akoeplinger I thought the backport action would automatically take new commits to the backport branch. IS that not the case anymore? I don't see anything triggering the action.

**Comment by hoyosjs** [comment]
Failure is https://github.com/dotnet/runtime/issues/73688

**Review by noahfalk — APPROVED** [review]
LGTM
I'm not an expert with these build files, but it all looked reasonable. I assume we'll be manually validating after the build that the binaries got signed appropriately

**Pull request merged**
