### PR TITLE
NetworkInterface.IsReceiveOnly should not throw on OSX

### LINKED ISSUE #48062: NetworkInterface.IsReceiveOnly throws on osx
Stumbled on this when carelessly serializing NetworkInterface instances. On mac, this throws an excpetion:
`The information requested is unavailable on the current platform. The unsupported member type is located on type 'System.Boolean'. Path: $.args.fingerprint.nics.nic.IsReceiveOnly.` whereas it works on windows and linux.

### Description

* https://github.com/dotnet/runtime/blob/eec1e2518ebafadaa08dce19098150bd1e8f2130/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/BsdNetworkInterface.cs#L161 clearly throws this exception, as opposed to
* https://github.com/dotnet/runtime/blob/eec1e2518ebafadaa08dce19098150bd1e8f2130/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/LinuxNetworkInterface.cs#L161 which simply returns false

### Configuration

* net5.0, on big sur 11.2

### Regression?

unknown

### Other information

not clear if this a bug or intended. at least strange linux handles it differently, also this is not handled in the documentation: `This property is not valid on computers running operating systems earlier than Windows XP.` (https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkinterface.isreceiveonly?view=net-5.0)

Thanks for looking  into it, bests 
harald

### PR DESCRIPTION
**Pull request by jaymin93**
Fixes #48062

### CODE REVIEW

**Review by karelz — APPROVED** [review]

**Comment by wfurt** [comment]
We need to update tests and make sure they are passing
```
    System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions_Bsd [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs(111,0): at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions_Bsd()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      Output:
        - NetworkInterface -
        Name: lo0
        Description: lo0
        ID: lo0

```

**Comment by jaymin93** [comment]
> We need to update tests and make sure they are passing
> 
> ```
>     System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions_Bsd [FAIL]
>       Assert.Throws() Failure
>       Expected: typeof(System.PlatformNotSupportedException)
>       Actual:   (No exception was thrown)
>       Stack Trace:
>         /_/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs(111,0): at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions_Bsd()
>         /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>       Output:
>         - NetworkInterface -
>         Name: lo0
>         Description: lo0
>         ID: lo0
> ```

i will update test with your suggestion , Thanks for your comment

**Comment by karelz** [comment]
@jaymin93 did you get chance to update the test?

**Comment by wfurt** [comment]
commit was merged from #50145 with test fixes.

**Pull request closed without merging**
