### PR TITLE
Don't check handles in substitution

### PR DESCRIPTION
**Pull request by SingleAccretion**
This should principally not be necessary after the recent `RETURN`-related changes.

Some CQ improvements are expected.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
SPMI failures are due to the lack of `win-arm64` MCHs.

@dotnet/jit-contrib 

Would be good run [libraries-]stress over this.

**Comment by SingleAccretion** [comment]
Looks like there is at least one stress failure that needs to be investigated.

**Comment by SingleAccretion** [comment]
The [stress](https://dev.azure.com/dnceng-public/public/_build/results?buildId=44140&view=results) failure has been fixed.

[Libraries stress](https://dev.azure.com/dnceng-public/public/_build/results?buildId=44142&view=ms.vss-test-web.build-test-results-tab&runId=899986&resultId=193700&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab) failures look preexisting ([point of reference](https://dev.azure.com/dnceng-public/public/_build/results?buildId=43414&view=ms.vss-test-web.build-test-results-tab)).

**Review by AndyAyersMS — APPROVED** [review]
Thanks!

**Comment by AndyAyersMS** [comment]
Failures look like CI issues:
```
      NuGet.Protocol.Core.Types.FatalProtocolException : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json.
```
Will retry once the arm64 tests finish.

**Comment by AndyAyersMS** [comment]
NAOT failure is a known issue.

**Comment by AndyAyersMS** [comment]
Thank you for your ongoing contributions.

**Pull request merged**
