### PR TITLE
[libraries][Android] Re-enable test suites no longer failing with JSON parsing exception for Android arm64

### LINKED ISSUE #53097: [Android][libraries] Test suites failing with A JSON parsing exception
The following test suites are failing on Android arm64 on CI
System.IO.Pipes.Tests
System.Numerics.Vectors.Tests
System.Reflection.Emit.Tests
System.Xml.Misc.Tests
System.Xml.XmlNodeReader.Tests
System.Xml.XmlSerializer.Tests
System.Security.Claims.Tests
System.Security.Cryptography.Primitives.Tests
System.Text.RegularExpressions.Tests
```
A JSON parsing exception occurred in [C:\h\w\AA5F0978\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21268.1\tools\net6.0\any\Microsoft.DotNet.XHarness.CLI.runtimeconfig.json], offset 0 (line 1, column 1): The document is empty.
Invalid runtimeconfig.json [C:\h\w\AA5F0978\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21268.1\tools\net6.0\any\Microsoft.DotNet.XHarness.CLI.runtimeconfig.json] [C:\h\w\AA5F0978\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.21268.1\tools\net6.0\any\Microsoft.DotNet.XHarness.CLI.runtimeconfig.dev.json]

### PR DESCRIPTION
**Pull request by mdh1418**
Fixes https://github.com/dotnet/runtime/issues/53097

### CODE REVIEW

**Comment by mdh1418** [comment]
The test suites are no longer failing with a JSON parsing exception for Android arm64 on CI https://dev.azure.com/dnceng/public/_build/results?buildId=1263864&view=logs&j=c693b1a1-52cc-5241-304f-e4b4c2d5f73e&t=ca6cd8a5-c31d-5a98-8419-f200a8c4128d

**Review by MaximLipnin — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]
Thanks! Please update the PR title before merging.

**Comment by MaximLipnin** [comment]
This is being hit again on https://dev.azure.com/dnceng/public/_build/results?buildId=1573033&view=ms.vss-test-web.build-test-results-tab&runId=44174110&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=162612

**Comment by steveisok** [comment]
@premun this seems infra related.

**Comment by premun** [comment]
We've seen this months ago with @akoeplinger and we assumed somehow that .NET failed to read/unzip the .json that goes with the .NET command line program.

> A JSON parsing exception occurred in [C:\h\w\B9090A3E\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.22074.1\tools\net6.0\any\Microsoft.DotNet.XHarness.CLI.runtimeconfig.json], offset 0 (line 1, column 1): The document is empty.
Invalid runtimeconfig.json [C:\h\w\B9090A3E\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.22074.1\tools\net6.0\any\Microsoft.DotNet.XHarness.CLI.runtimeconfig.json] [C:\h\w\B9090A3E\p\microsoft.dotnet.xharness.cli\1.0.0-prerelease.22074.1\tools\net6.0\any\Microsoft.DotNet.XHarness.CLI.runtimeconfig.dev.json]
User command ended with -2147450733

I remember I did download that given payload back then and verified that `runtimeconfig.json` was not empty

**Comment by premun** [comment]
Are we seeing this a lot?

**Comment by steveisok** [comment]
Sorry, I commented here before reopening the original issue https://github.com/dotnet/runtime/issues/53097

I believe I've seen it twice this week.

**Comment by premun** [comment]
I am seeing 21 possible occurences of this in the past 14 days.

Can we maybe employ dev WF and put this exit code in the re-run conditions?

**Comment by akoeplinger** [comment]
It's a bad machine, more details in https://github.com/dotnet/core-eng/issues/15447

**Pull request merged**
