### PR TITLE
JIT: Fix invalid smnegl transformation

### LINKED ISSUE #92537: JIT: Invalid smnegl transformation
```csharp
// Generated by Fuzzlyn v1.6 on 2023-09-23 15:15:18
// Run on Arm64 Windows
// Seed: 17929576410580344290
// Reduced from 324.8 KiB to 0.4 KiB in 00:04:43
// Debug: Outputs -2472766155
// Release: Outputs 1822201141

public class C0
{
    public uint F4;
    public C0(uint f4)
    {
        F4 = f4;
    }
}

public class Program
{
    public static C0 s_8 = new C0(2472766155U);
    public static ushort[] s_39 = new ushort[]{1};
    public static void Main()
    {
        uint vr2 = s_8.F4;
        long vr0 = -(s_39[0] * (long)vr2);
        System.Console.WriteLine(vr0);
    }
}
```

The codegen is
```asm
G_M27646_IG03:  ;; offset=0x001C
            movz    x0, #0x1D78      // data for Program:s_8
            movk    x0, #0x7A00 LSL #16
            movk    x0, #657 LSL #32
            ldr     x1, [x0]
            ldr     w1, [x1, #0x08]
            ldr     x0, [x0, #0x08]
            ldr     w2, [x0, #0x08]
            cmp     w2, #0
            bls     G_M27646_IG06
            ldrh    w0, [x0, #0x10]
            smnegl  x0, w0, w1
            movz    x1, #0x5B90      // code for System.Console:WriteLine(long)
            movk    x1, #0x8153 LSL #16
            movk    x1, #0x7FFE LSL #32
            ldr     x1, [x1]
            blr     x1
```

This looks like a regression introduced by #91886, cc @c272 @kunalspathak

### PR DESCRIPTION
**Pull request by jakobbotsch**
The newly introduced TryLowerNegToMulLongOp would always lower to a signed multiplication, even for unsigned multiplications.

Also apply a couple of other fixes to the transformation:
* Replace uses of GenTree::ReplaceWith with LIR::Use::ReplaceWith
* Add some necessary interference checks

Fix #92537

### CODE REVIEW

**Comment by kunalspathak** [comment]
> The newly introduced TryLowerNegToMulLongOp would always lower to a signed multiplication, even for unsigned multiplications.

I pointed that out in the PR https://github.com/dotnet/runtime/pull/91886#issuecomment-1715629341 but seems like we still missed some cases.

**Comment by kunalspathak** [comment]
Interestingly there are no diffs, so seems we don't have coverage for this scenario. Can you please add a test case too?

**Comment by jakobbotsch** [comment]
> Interestingly there are no diffs, so seems we don't have coverage for this scenario. Can you please add a test case too?

Added the test, can you PTAL?

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by kunalspathak** [comment]
superpmi failures are known.

**Pull request merged**
