### PR TITLE
[release/5.0-preview5] Ignore the private key handle cert property for persisted keys

### PR DESCRIPTION
**Pull request by Anipik**
Its already approved by servicing cc @danmosemsft 

Ports https://github.com/dotnet/runtime/pull/36287
Fixes https://github.com/dotnet/runtime/issues/36273

cc @javiercn @mkArtakMSFT

### CODE REVIEW

**Review by joperezr — COMMENTED** [review]
Package index changes port looks good

**Review by bartonjs — APPROVED** [review]

**Review by mkArtakMSFT — APPROVED** [review]
👍

**Comment by danmosemsft** [comment]
@mkArtakMSFT can you please let us know, when your vendors have successfully validated?

**Comment by mkArtakMSFT** [comment]
@danmosemsft they run validation on daily builds - similar to how other CTI vendors do. So this should be merged to get a preview 5 build, so they can validate it

**Comment by danmosemsft** [comment]
Thanks yes, I saw @Anipik close it and thought it got merged 😋

**Comment by Anipik** [comment]
some of the branches were hung, so i reopen it to run the start thiose again

**Pull request merged**
