### PR TITLE
Zip64ExtraField reads StartDiskNumber as uint32

### LINKED ISSUE #31825: Zip64ExtraField should read StartDiskNumber as uint32
According to https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT:

>    4.4.1 General notes on fields
>
>      4.4.1.1  All fields unless otherwise noted are unsigned and stored
>      in Intel low-byte:high-byte, low-word:high-word order.

And the spec for the Zip64ExtraField doesn't note otherwise:

>    4.5.3 -Zip64 Extended Information Extra Field (0x0001):
>
>        Disk Start
>        Number     4 bytes    Number of the disk on which
>                              this file starts 

However, we are reading the "Disk Start Number" as a signed int32, and then throwing an exception if the number is negative:

https://github.com/dotnet/runtime/blob/33b7ed8795d70d28bfeaf40498d94f6bede8769d/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipBlocks.cs#L209-L218

We should change this to `zip64Block._startDiskNumber = reader.ReadUInt32();`, remove the exception, and flow the `uint` value everywhere.

Looking at the reference source:

https://referencesource.microsoft.com/#WindowsBase/Base/MS/Internal/IO/Zip/ZipIOExtraFieldZip64Element.cs,101

That is reading as `uint32` as well. We should update to the same.

Here is a prototype of the change: https://github.com/eerhardt/runtime/commit/b790a945d9adbddbdf8caff4e75c8e9e33682533

### PR DESCRIPTION
**Pull request by steveberdy**
Updates Zip64 to have StartDiskNumber as a uint32.

Fixes #31825

### CODE REVIEW

**Comment by stephentoub** [comment]
Is there a test we can add to ensure an exception isn't being thrown for a value `int.MaxValue < value <= uint.MaxValue`?

**Comment by steveberdy** [comment]
I thought the value was always within uint range.

**Comment by steveberdy** [comment]
I'll add the tests sometime in the next few weeks.

**Comment by steveberdy** [comment]
Where would you like the test to be located? This is my first time writing tests in this particular repository.

**Review by Vadimyan — APPROVED** [review]

**Comment by stephentoub** [comment]
> Where would you like the test to be located? This is my first time writing tests in this particular repository.

Somewhere in https://github.com/dotnet/runtime/tree/49329581982751946fb9610bac38747958fb579c/src/libraries/System.IO.Compression/tests/ZipArchive, probably either https://github.com/dotnet/runtime/blob/49329581982751946fb9610bac38747958fb579c/src/libraries/System.IO.Compression/tests/ZipArchive/zip_InvalidParametersAndStrangeFiles.cs or https://github.com/dotnet/runtime/blob/49329581982751946fb9610bac38747958fb579c/src/libraries/System.IO.Compression/tests/ZipArchive/zip_ReadTests.cs.

Thanks!

**Comment by adamsitnik** [comment]
@steveberdy please let me know if you need some help or don't have the time to finish the PR

**Comment by steveberdy** [comment]
I added a test. Do we have an example zip file for the tests whose `StartDiskNumber` is greater than `int.MaxValue`?

**Comment by eerhardt** [comment]
Looks like the build is broken:

> src/libraries/System.IO.Compression/src/System/IO/Compression/ZipBlocks.cs(225,51): error CS0266: (NETCORE_ENGINEERING_TELEMETRY=Build) Cannot implicitly convert type 'int' to 'uint?'. An explicit conversion exists (are you missing a cast?)

> src/libraries/System.IO.Compression/src/System/IO/Compression/ZipBlocks.cs(231,88): error CS0117: (NETCORE_ENGINEERING_TELEMETRY=Build) 'SR' does not contain a definition for 'FieldTooBigStartDiskNumber'


____

>Do we have an example zip file for the tests whose StartDiskNumber is greater than int.MaxValue?

I don't believe so. Making one is part of the work here.

**Comment by adamsitnik** [comment]
@steveberdy you should be able to build the repo locally once you install the [required pre-requisites](https://github.com/dotnet/runtime/blob/main/docs/workflow/README.md#build-requirements)

```cmd
git clone https://github.com/steveberdy/runtime.git
cd runtime
git checkout zip64
build.[cmd/sh] -rc Release -subset clr+libs+libs.tests
```

And then run the tests using:

```cmd
dotnet.[cmd/sh] build /t:Test .\src\libraries\System.IO.Compression\tests\System.IO.Compression.Tests.csproj /p:Configuration=Debug
```

**Comment by steveberdy** [comment]
@adamsitnik Thanks, I understand. Where would I put test .zip files?

**Comment by danmoseley** [comment]
Do you need one or can you conductivity it from a byte array? I added a test about a week ago in there that does this and it's quite convenient as you can poke the array to get different tests.

**Comment by steveberdy** [comment]
Where should I change the bytes in your byte array?

**Comment by danmoseley** [comment]
You will have to consult the RFC (or whatever the zip spec is). But if you search in the file I linked above for "disk" you will find pointers to various places in this simple zip file where disk numbers may be relevant.

One page I noticed that might be helpful: https://users.cs.jmu.edu/buchhofp/forensics/formats/pkzip-printable.html

**Comment by steveberdy** [comment]
Thanks, I'll check that out

**Comment by steveberdy** [comment]
re-open

**Comment by adamsitnik** [comment]
I am closing due to lack of progress. Please feel free to fix the mentioned issues and reopen the PR. Thanks!

**Pull request closed without merging**
