### PR TITLE
Remove null annotation from *HeaderValue.Parse methods

### LINKED ISSUE #77160: MediaTypeHeaderValue.Parse throws FormatException with null string
Hey,
I'm not sure if this should be classified as a bug or documentation error or simply a misunderstanding of nullable.

The api documentation in Visual Studio for the `MediaTypeHeaderValue.Parse` Method shows the following signature:
image
If I understand this correctly, the `input` string is allowed to be null as indicated by the `?` at the end of the type (nullable string).
When passing a null string into the `Parse` method, it throws a `System.FormatException` with the message `The format of value '<null>' is invalid.`.

I'm fine with it throwing this exception, since there is no good return value - but the method signature is misleading since it suggests `null` is a valid value.

Am I missing something here or am I misunderstanding how nullable should be interpreted by developers?

Dotnet 6.0.402
Visual Studio 17.3.6

### PR DESCRIPTION
**Pull request by fredzeppelin1**
All Parse(string) methods in *HeaderValue.cs classes (e.g. ProductHeaderValue) have the input parameter annotated as nullable, however null values cause an exception. Therefore removing the nullable annotation.

Fix #77160

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=79950) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=79950) before we can accept your contribution.<br/><br/>:x: padraigmyers [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=79950)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=79950) it.</sub>

**Review by MihaZupan — COMMENTED** [review]
Thank you for contributing here.
Can you please also update these signatures in the ref file here https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/ref/System.Net.Http.cs?

**Comment by padraigmyers** [comment]
> Thank you for contributing here. Can you please also update these signatures in the ref file here https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/ref/System.Net.Http.cs?

Done

**Review by MihaZupan — APPROVED** [review]

**Comment by MihaZupan** [comment]
Only known test errors according to Build Analysis

**Comment by wfurt** [comment]
should this go through API review since it is touching ref assemblies @MihaZupan ?

**Comment by MihaZupan** [comment]
There was an email thread with fxdc+ncldev about it - "Nullability of *HeaderValue.Parse(string)". My impression was that there was agreement to just fix the wrong annotations (everything except CacheControl).

**Pull request merged**
