### PR TITLE
Restore erroneously removed encoding of the argument count in a generic method instantiation

### PR DESCRIPTION
**Pull request by kg**
When IBC was removed, we accidentally removed the argument count from the encoding of generic method instantiations (it was previously being conditionally *omitted* when IBC was active, so it should have stayed.)

This can cause crashes in multicore jit scenarios and generally makes it not work for generic methods.

Adding this back will ensure that profiles recorded in the future will be valid, though we can't fix existing ones.

Still looking into where & how I could add regression coverage for this, but I'm not sure it's necessary.

### CODE REVIEW

**Comment by steveisok** [comment]
@jeffschwMSFT who else should we add to the review? In terms of testing on CI, are multicore jit tests kicked off manually?

**Comment by kg** [comment]
The only test coverage I found so far is https://github.com/dotnet/runtime/tree/71344cea37d84bb403d3d303b2add9e6135c539c/src/tests/baseservices/TieredCompilation and it doesn't appear to verify whether the profiled methods were actually jitted. It looks like it's meant for manual verification, presumably on a runtime build with logging turned on.

**Comment by jkotas** [comment]
> When IBC was removed, we accidentally removed the argument count from the encoding of generic method instantiations 

Could you please share a link to the PR where this happened?

**Comment by AaronRobinsonMSFT** [comment]
> > When IBC was removed, we accidentally removed the argument count from the encoding of generic method instantiations
> 
> Could you please share a link to the PR where this happened?

This happened in https://github.com/dotnet/runtime/pull/68717

**Review by jkotas — APPROVED** [review]
LGTM. Thanks

**Comment by AaronRobinsonMSFT** [comment]
> Backport candidate?

Yes, I think so.

**Pull request merged**
