### PR TITLE
runtime: add RIDs for anolis distro

### PR DESCRIPTION
**Pull request by geliwei**
instead of patching dotnet everytime after
it got updated we plan to add runtime ID for
anolis 7/anolis 8/anolis 9.

Signed-off-by: Livy Ge <livy.ge@gmail.com>

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=66132) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=66132) before we can accept your contribution.<br/><br/>:x: geliwei [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=66132)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=66132) it.</sub>

**Comment by bartonjs** [comment]
@richlander is usually involved in the flow for adding new distros to the graph.  Rich?

**Comment by richlander** [comment]
We are currently considering this design proposal.

https://github.com/dotnet/designs/pull/260

I don't think we can reasonably back-port it to .NET 6, however.

Can you share more context? Are you the maintainers for .NET for anolis?

**Comment by ericstj** [comment]
@geliwei can you please answer @richlander’s question?

**Comment by richlander** [comment]
I was thinking more about this (based on our continuing conversations on RID simplification). Is the RID for anolis needed for restoring anolis-specific packages or just to ensure that anolis is correctly treated as either `rhel` or `linux`?

**Comment by geliwei** [comment]
> I was thinking more about this (based on our continuing conversations on RID simplification). Is the RID for anolis needed for restoring anolis-specific packages or just to ensure that anolis is correctly treated as either `rhel` or `linux`?

Hi,  
Yes, I'm the maintainers for Anolis distro.
It's good if the Anolis is treated as rhel. 
I wrote these RID maps manually, I remebered there is a way to automatically work out RID graph via build.sh command, but I forgot on which post I found it. 
I heard some news that you guys are working on code that could created RID on the fly, is that true ? D:

**Comment by omajid** [comment]
Hey @geliwei ! If you don't add the RIDs (manually or otherwise), does the .NET build fail? Can you point us to any build logs that show the failure?

**Comment by richlander** [comment]
This info might be what you are looking for: https://github.com/dotnet/runtime/pull/50818

We have a maintainers group now. I can add you if you want to join it @geliwei.

The new plan for source-build is documented at https://github.com/dotnet/designs/pull/260/files#diff-20aa11d3c5c8d54fc1c45f4b81927255d3951fdd7cf58589fc6d03a2dd2a6a1bR195.

**Comment by geliwei** [comment]
> Hey @geliwei ! If you don't add the RIDs (manually or otherwise), does the .NET build fail? Can you point us to any build logs that show the failure?

I copy a few errors from http://build.openanolis.cn/kojifiles/work/tasks/7092/297092/build.log:
    /builddir/build/BUILD/dotnet-v6.0.105-SDK/previously-built-dotnet/sdk/6.0.104/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1083: The specified RuntimeIdentifier 'anolis.8.6-x64' is not recognized. [/builddir/build/BUILD/dotnet-v6.0.105-SDK/src/runtime/artifacts/source-build/self/src/Build.proj]
    /builddir/build/BUILD/dotnet-v6.0.105-SDK/previously-built-dotnet/sdk/6.0.104/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1083: The specified RuntimeIdentifier 'anolis.8.6-x64' is not recognized. [/builddir/build/BUILD/dotnet-v6.0.105-SDK/src/runtime/artifacts/source-build/self/src/Build.proj]
    /builddir/build/BUILD/dotnet-v6.0.105-SDK/previously-built-dotnet/sdk/6.0.104/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1083: The specified RuntimeIdentifier 'anolis.8.6-x64' is not recognized. [/builddir/build/BUILD/dotnet-v6.0.105-SDK/src/runtime/artifacts/source-build/self/src/Build.proj]
    /builddir/build/BUILD/dotnet-v6.0.105-SDK/previously-built-dotnet/sdk/6.0.104/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(129,5): error NETSDK1083: The specified RuntimeIdentifier 'anolis.8.6-x64' is not recognized. [/builddir/build/BUILD/dotnet-v6.0.105-SDK/src/runtime/artifacts/source-

**Comment by geliwei** [comment]
I have made change to init-distro-rid.sh and also pal.unix.cpp, remove RIDs in runtime.json but keep runtimeGroups.props. But looks like it fails the test again, Would you like to help me figure out why?

**Comment by geliwei** [comment]
> I have made change to init-distro-rid.sh and also pal.unix.cpp, remove RIDs in runtime.json but keep runtimeGroups.props. But looks like it fails the test again, Would you like to help me figure out why?

this change works so far on dotnet5.0 https://gitee.com/src-anolis-os/dotnet5.0/commit/39c160eb817b5bab7366ed1d14f8c91d4316ca96

**Comment by wfurt** [comment]
did we reached conciliation if new bistro is needed @omajid @richlander ? 

As minimum we should rebuild other json files besides runtimeGroups.props and include this with the PR. 
(dotnet pack from https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/readme.md)

**Comment by richlander** [comment]
Ideally, we would not and this RID could be added via source-build per https://github.com/dotnet/runtime/pull/50818. That should be the goto approach for these cases. Is that acceptable?

**Comment by wfurt** [comment]
> Ideally, we would not and this RID could be added via source-build per #50818. 

Would that mean that RH binaries would be unusable e.g. the RID would work only if distribution has own package created via source-build?

**Comment by richlander** [comment]
Here's my take/understanding on how the system should work.

- Everyone should publish portable linux binaries (for packages) as a general rule.
- If they cannot, then they limit the use of their package to non-portable OSes.
- Publishing portable + specific is fine. I hope NuGet ignores RIDs it doesn't understand.

By building .NET for a distro as `foo`, you are not directly affecting package compatibility. You are saying "I'm this and I also accept the things I say I accept".

This is the same thing as blood types.

`linux` is like `O-` as a donor. It's universally compatible.
`foo` is like `AB+` as a donor. It's universally incompatible, except with itself.

image

Credit to the [Wikipedia page on blood types](https://en.wikipedia.org/wiki/Blood_type#Red_blood_cell_compatibility).

This is a fair analogy, right?

**Comment by agocke** [comment]
I agree with @richlander, I think this is the correct direction.

**Comment by richlander** [comment]
I should have added:

- The donors are RIDs
- The recipients are distros.

**Comment by richlander** [comment]
@clairernovotny @aortiz-msft It would be good for the NuGet team to review this approach.

**Comment by ericstj** [comment]
So if I can summarize the state here, @richlander and @agocke are saying that this PR should not be needed due to the changes to how we expect distro's to source build in .NET 7.0.  https://github.com/dotnet/runtime/pull/66132#issuecomment-1171793644

@geliwei do you agree, or are you keeping this PR open for a scenario that wasn't covered by that explanation?

Thanks!
Eric

**Comment by carlossanlop** [comment]
> It would be good for the NuGet team to review this approach.

Ping @clairernovotny @aortiz-msft to help with this request.

> are saying that this PR should not be needed

Ping @richlander @agocke to answer this question.

> do you agree, or are you keeping this PR open for a scenario that wasn't covered by that explanation?

Ping @geliwei to answer this question.

**Comment by tmds** [comment]
> are saying that this PR should not be needed

https://github.com/dotnet/runtime/issues/83246 is superseding https://github.com/dotnet/designs/pull/260 and is still being discussed.

As other rids are still being added, we can add these too.

The graph will be updated as needed for https://github.com/dotnet/runtime/issues/83246.

**Comment by agocke** [comment]
I'm closing new RID PRs for now, until we can sort out the RID plan, as in https://github.com/dotnet/runtime/pull/81115

**Comment by tmds** [comment]
> I'm closing new RID PRs for now, until we can sort out the RID plan, as in https://github.com/dotnet/runtime/pull/81115

I'm not sure why this doesn't get added, while other rids are still being added.

Will we no longer be adding any rids until the RID plan is sorted out?

I have good hope we'll sort it out for .NET 8, but I had the same hope for .NET 7.

I'd keep business as usual until the plan is decided.

**Pull request closed without merging**
