### PR TITLE
[wasm] rationalize internal exports

### PR DESCRIPTION
**Pull request by pavelsavara**
- reduce `BINDING` and `MONO` exports to [minimal scope necessary](https://github.com/dotnet/runtime/blob/368b27d8c2d5025db6044d7854aadd79f89cb4e8/src/mono/wasm/runtime/exports.ts#L212) - as [used by Blazor](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Platform/Mono/MonoTypes.ts)
- introduce `globalThis.INTERNAL` and move all exported methods which we only use internally or for testing
- fix all internal usages in tests
- produce `dotnet.d.ts` and include it in the workload
- moved `Module.config` to `MONO.config`
- added `mono_load_runtime_and_bcl_args` into `MONO` export
- add `mono_wasm_new_root_buffer`, `mono_wasm_new_root`, `mono_wasm_release_roots` to the `MONO` export
- removed obsolete debugger test `InvalidScopeId`
- introduced `INTERNAL.mono_wasm_set_main_args`

### CODE REVIEW

**Comment by kg** [comment]
Cleaning up the 'Module' goo is good, but i feel like INTERNAL is probably the wrong name especially if we end up touching it from tests, etc.

**Comment by kg** [comment]
Blazor uses Module._malloc, but we could expose our own blessed version of it via MONO. instead. I think people would have to be using FS right now to do various things, maybe we should expose an API for that as well (though they can load things ahead of time via mono-config)

**Comment by jeromelaban** [comment]
> > Thanks @pavelsavara. Uno can cope with the change, but many extensions or projects (not just uno-based) are using this particular one:
> > https://github.com/search?q=mono_bind_static_method&type=Code
> 
> Thanks for the hint. Using it via `Module` is pretty bad. I would like to get rid of `Module` from the global namespace in the future (emscripten output as es6 module). Do people also use emscripten low level features, like memory manipulation or FS ?

It happens yes (both memory manipulation and FS). SkiaSharp does memory manipulation for instance, Uno as well.

Modularizing would be very nice indeed.

Is this for net6 or net7 ?

**Comment by pavelsavara** [comment]
> Is this for net6 or net7 ?
net7

**Comment by pavelsavara** [comment]
> I personally think bind_static_method should be public

`Module.mono_bind_static_method` is the same as `BINDING.bind_static_method` so it's already published.

I will keep `Module.mono_bind_static_method` in place for compat for now. No promise about future PRs ;)

**Review by kg — APPROVED** [review]

**Pull request merged**
