### PR TITLE
Revert "Remove "wprintf" from PAL (#77852)"

### PR DESCRIPTION
**Pull request by radical**
This completely broke `dotnet-runtime-perf` pipeline for wasm runs.

This reverts commit 803688595257517f4b47e873d11152b0560c204a.

Issue: https://github.com/dotnet/runtime/issues/77883

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@radical It would be most helpful if you could root out what part of WASM is failing and potential reproduction steps here.

**Comment by radical** [comment]
> @radical It would be most helpful if you could root out what part of WASM is failing and potential reproduction steps here.

I was was able to confirm that this is only happening for wasm. So, I'm trying to check if anything else could be responsible here.

**Comment by radical** [comment]
- I tested with your commit intact
- Between the two CI runs:
  - `dotnet/performance` repo had some new commits, and removing https://github.com/dotnet/performance/commit/860803b569cb8cad6a9da437eddfd7da747ccead seems to fix the issue
  - Even with the commit, building for `net7.0` works fine
  - The 8.0 sdk installed in `dotnet/runtime`, and the `Wasm-tools` workload isn't quite on net8.0 yet. And now we also have https://github.com/dotnet/runtime/pull/77899 . I think this performance commit should be reverted till the sdk+runtime becomes usable for net8.0 .

cc @LoopedBard3 @ericstj

@AaronRobinsonMSFT this looks completely unrelated to your PR 👍

**Pull request closed without merging**
