### PR TITLE
[mono] Test llvm bump

### PR DESCRIPTION
**Pull request by BrzVlad**

### CODE REVIEW

**Comment by matouskozak** [comment]
The EmptyStruct crash isn't related, I missed it in the previous triage and it's a known issue https://github.com/dotnet/runtime/issues/106071. The dwarf error probably is.

**Comment by BrzVlad** [comment]
The dwarf error looks like some failure in gdb, so llvm x64 looks good.

**Comment by steveisok** [comment]
@BrzVlad if you think the fix is good, can you take this out of draft and move it forward? I'd like to get this in before RC1 snaps.

**Comment by BrzVlad** [comment]
The llvm x64 lane is green now. This PR disables emitting of some llvm intrinsic as a current workaround, @tannergooding will take a look at this when there is some time available.

For now this looks good, a review is needed so we can merge. cc @radekdoulik

**Comment by tannergooding** [comment]
> This PR disables emitting of some llvm intrinsic as a current workaround, @tannergooding will take a look at this when there is some time available.

👍, can we make sure a tracking issue is logged for this?

**Review by radekdoulik — APPROVED** [review]
LGTM, please add comment with issue number to the disabled shuffle intrinsic.

**Comment by BrzVlad** [comment]
Issue for follow up: https://github.com/dotnet/runtime/issues/106270

**Pull request merged**
