### PR TITLE
Remove HelperMethodFrame from `Delegate` construction

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
@jkotas I'm likely missing something here. Is the linux_musl arm failure real? It is consistent, which leads me to believe I've done something here. I'll look into it today, but if you have any thoughts it might save me some time.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas No worries. I figured it out.

**Comment by AaronRobinsonMSFT** [comment]
/ba-g Timeout message below, unreleated to change.

```
##[error]Agent failed with exception: The machine running request 752ca8ec-b20f-4822-a3b7-cb589e799e71 restarted. Azure DevOps can't recover from restarts.
,##[warning]Received request to deprovision: The request was cancelled by the remote provider.
```

**Pull request merged**
