### PR TITLE
Vector abi tests

### PR DESCRIPTION
**Pull request by davidwrighton**
Add tests for marshalling Vector2, Vector3, and Vector4 to and from native code
- Ensure that upcoming changes to abi handling of Vector128<float>, and Vector64<float> do not effect abi of Vector2/3/4.

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Review by jkoritzinsky — APPROVED** [review]
The ReversePInvokeTest.cs file is showing up as binary for some reason. Once that's changed to text, this looks good to me!

**Comment by davidwrighton** [comment]
Previously this passed CI, and the only change was a change to move a test from being encoded Utf16 to Utf8.

**Comment by BruceForstall** [comment]
cc @CarolEidt

**Comment by BruceForstall** [comment]
fyi, this led to new JIT assertion failures: https://github.com/dotnet/runtime/issues/32379

**Pull request merged**
