### PR TITLE
Update docs to use the main build script

### PR DESCRIPTION
**Pull request by nxtn**

### CODE REVIEW

**Comment by jkotas** [comment]
We had a long discussion about how to structure the build scripts in the dotnet/runtime repo. I believe that we came to conclusion that these convenience scripts are more confusing than helpful and we plan to delete them, and instead simplify the command line options for the main build.sh/cmd scripts.

cc @dotnet/runtime-infrastructure

**Comment by safern** [comment]
> I believe that we came to conclusion that these convenience scripts are more confusing than helpful and we plan to delete them, and instead simplify the command line options for the main build.sh/cmd scripts.

Yeah, that's the end plan as at the end they're just wrapper scripts that call build.cmd/.sh with `-subsetCategory <coreclr/libraries/installer/mono>`

**Comment by NextTurn** [comment]
`-subsetCategory` is a fairly long option. It would be better to have a short alias.

**Comment by safern** [comment]
> -subsetCategory is a fairly long option. It would be better to have a short alias.

That I completely agree. We should think about a shorter option for this. 
@dotnet/runtime-infrastructure thoughts?

**Comment by jkotas** [comment]
The shortest option length is zero. Hard to beat that.

I really like the no ceremony command line of the coreclr build script. You can just say `build.cmd x86 release` and it builds x86 release build. No need to remember and type the extra `-whatever`.

**Comment by NextTurn** [comment]
> The shortest option length is zero. Hard to beat that.

+1 on this. To "build something"(`build.cmd coreclr`) provides good readability as well.

**Comment by ViktorHofer** [comment]
> The shortest option length is zero. Hard to beat that.

I'm in favor of consistency over simplicity, just my opinion. We are using that argument syntax in all arcadified repos.

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
