### PR TITLE
Update Microsoft.DotNet.Helix.Sdk

### PR DESCRIPTION
**Pull request by akoeplinger**
Extracted from https://github.com/dotnet/runtime/pull/67771 to get the fix for https://github.com/dotnet/runtime/issues/67349

Updates the WASM tests to always use net6.0 until we can upgrade to a net7.0 SDK.

### CODE REVIEW

**Review by premun — APPROVED** [review]
Yeah, this should work

**Review by steveisok — APPROVED** [review]

**Review by jkoritzinsky — APPROVED** [review]

**Comment by steveisok** [comment]
@akoeplinger @premun Is there something wrong with the xharness bump?

I'm seeing this in some of the failed runs:

```
/usr/bin/python3 -u /datadisks/disk1/work/BF180A16/w/A18D0948/u/xharness-event-processor.py
/usr/bin/python3: can't open file '/datadisks/disk1/work/BF180A16/w/A18D0948/u/xharness-event-processor.py': [Errno 2] No such file or directory
```

**Comment by akoeplinger** [comment]
There is an issue on the wasm DebuggerTests leg that blocks this yeah

**Review by stephentoub — APPROVED** [review]

**Comment by premun** [comment]
Ignore the Python error, that one is normal for all wasm runs even though they were supposed to turn off the telemetry to hide it. Regardless it is harmless

**Comment by steveisok** [comment]
Are you sure?  Some of these legs have all passes in their testResults.xml, but yet are being flagged as a failure.

**Comment by premun** [comment]
@steveisok can you show me an example?

**Comment by premun** [comment]
@akoeplinger the build is looking good so far. I believe it's going to finish green.

The one failing wasm leg is a failing test, I checked the logs

**Review by ViktorHofer — APPROVED** [review]

**Comment by akoeplinger** [comment]
@premun not sure whether the two failing wasm jobs are real failures, they just print this which is weird:

```
Console log: 'normal-Invariant.Tests' from job 1a207a32-525d-408a-9972-8eb73eaf1dd3 (windows.amd64.server2022.open) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-ltsc2022-helix-webassembly-20220317203903-1ad56e8 on a002BY9
running %HELIX_CORRELATION_PAYLOAD%\scripts\2e67926377ad48d28d153418c420f78b\execute.cmd in C:\h\w\A091093F\w\9EB708DD\e max 3600 seconds

Output:

Exit Code:-900
```

**Comment by premun** [comment]
@radical do you know what could be up with the two failing WASM legs? We are forcing .NET 6.0 SDK in this PR like I was describing

**Comment by akoeplinger** [comment]
@premun I just looked at the run_py.log and it looks like an infrastructure issue with Docker to me:

```
2022-04-20T16:11:48.431Z	ERROR  	dockerhelper(234)	run	API Error attempting to talk to Docker Server:500 Server Error: Internal Server Error ("CreateComputeSystem b470dbaa253592a57acb6c7ff8844c3d06337e4a756be9d52be9b942f7fd80a0: The request is not supported.
(extra info: 
```

**Pull request merged**
