### PR TITLE
[wasm] Fix scenario specific tests

### PR DESCRIPTION
**Pull request by maraf**
- Fix not copying tests zips to `browserornodejs` and `nodejsonly` folders.
- Disable `System.Net.WebSockets.Client.Tests` on NodeJS, before we fix NodeJS https://github.com/dotnet/runtime/pull/64330

### CODE REVIEW

**Review by pavelsavara — APPROVED** [review]

**Comment by pavelsavara** [comment]
`fail: Failed to find the middleware assembly at /datadisks/disk1/work/A60E08AE/p/xharness/RemoteLoopMiddleware/RemoteLoopServer.dll`
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64800-merge-a3d22ea2168043e88c/WasmTestOnBrowser-System.Net.Http.Functional.Tests/1/console.5062cb59.log?sv=2019-07-07&se=2022-02-24T10%3A41%3A18Z&sr=c&sp=rl&sig=PKkQ0bWmcY%2FeAQKLGW%2FbPgxO8CMrsXEKW2PCyEmDDd0%3D)

**Comment by premun** [comment]
FWIW this setting is now true by default (https://github.com/dotnet/arcade/pull/8216):
```xml
<EnableXHarnessTelemetry>true</EnableXHarnessTelemetry>
```

And as such can be omitted.

**Comment by radical** [comment]
Add `wasmtestonnodejs` at https://github.com/dotnet/runtime/blob/main/eng/pipelines/runtime-extra-platforms.yml#L197 to run the library tests with node. I have https://github.com/dotnet/runtime/pull/64766 open to add it for `main`.

**Comment by maraf** [comment]
> Add `wasmtestonnodejs` at https://github.com/dotnet/runtime/blob/main/eng/pipelines/runtime-extra-platforms.yml#L197 to run the library tests with node

I'm trying to fix wasm on browser here. It seems that the path where `RemoteLoopMiddleware` gets compiled has changed and so it doesn't get included as correlation payload.

**Comment by radical** [comment]
I merged my PR to enable library tests on nodejs, fyi.

**Pull request merged**
