### PR TITLE
Remove arcade packaging workaround

### PR DESCRIPTION
**Pull request by ViktorHofer**

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@steveisok @akoeplinger there are tons of Mono crashes on Desktop configurations. Are these known?

**Comment by steveisok** [comment]
Yes, it looks like the ones I've asked @directhex to handle.

**Comment by ViktorHofer** [comment]
Thanks. The Linux is a different one?

```
~/work/BAC009CA/w/B5ED09A6/e ~/work/BAC009CA/w/B5ED09A6/e
  Discovering: System.Threading.Thread.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Thread.Tests (found 43 of 49 test cases)
  Starting:    System.Threading.Thread.Tests (parallel test collections = on, max threads = 2)
    System.Threading.Threads.Tests.ThreadTests.ApartmentState_NoAttributePresent_DefaultState_Nano [SKIP]
      Condition(s) not met: "IsWindowsNanoServerAndRemoteExecutorSupported"
    System.Threading.Threads.Tests.ThreadTests.ApartmentStateTest_ChangeBeforeThreadStarted_Windows_Nano_Server [SKIP]
      Condition(s) not met: "IsWindowsNanoServer"
  Finished:    System.Threading.Thread.Tests
=== TEST EXECUTION SUMMARY ===
   System.Threading.Thread.Tests  Total: 53, Errors: 0, Failed: 0, Skipped: 2, Time: 2.128s

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
   at System.Threading.WaitSubsystem.OnThreadExiting(Thread thread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/WaitSubsystem.Unix.cs:line 430
   at System.Threading.Thread.Finalize() in /_/src/mono/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs:line 85
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
   at System.Threading.WaitSubsystem.OnThreadExiting(Thread thread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/WaitSubsystem.Unix.cs:line 430
   at System.Threading.Thread.Finalize() in /_/src/mono/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs:line 85
~/work/BAC009CA/w/B5ED09A6/e
```

**Comment by steveisok** [comment]
@CoffeeFlux ^^

**Comment by CoffeeFlux** [comment]
That one should have been fixed with https://github.com/dotnet/runtime/pull/49628

**Review by Anipik — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Pull request merged**
