### PR TITLE
[Mono] Add an attribute to layout runtime visible classes

### PR DESCRIPTION
**Pull request by lambdageek**
## `MonoRuntimeLayoutAware` attribute

Add a new attribute `MonoRuntimeLayoutAware` to be used on classes that are exposed to the runtime.  The fields of the class that are visible to the runtime go into a separate struct, and the attribute ensures that the runtime places the field first in the class.

Usage:

```csharp
[MonoRuntimeLayoutAware(nameof(_runtime)]
sealed class MyClass {
   [StructLayout (LayoutKind.Sequential)]
   private struct RuntimeLayout {
     IntPtr ptr;
     IntPtr ptr2;
  }

  private RuntimeLayout _runtime;     // runtime will put this first in MyClass
  private object _some_other_field;   // other fields can be trimmed by the linker, etc
}
```

Caveats:

* this only works for classes the derive from `object` or from classes that don't add any instance fields.
* this won't work for subclasses that also need to be visible (e.g. most of `System.Reflection.Emit`, and unfortunately `System.ArgumentException`)

## `Mono.ICallArg<T>` ref struct

Currently the IL Linker is conservative and it won't remove any fields from a class that is passed to an `InternalCall`. (This is reasonable behavior.  Although we could potentially teach the linker that for a `MonoRuntimeLayoutAware` class it's ok to just keep the `MonoRuntimeLayoutAware` field, and consider the rest as trimmable)

As a workaround, but also because it aligns us a bit closer with the CoreCLR [`QCallHandles`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/QCallHandles.cs#L24) add a new `ref struct ICallArgs<T>` type.

In places where we would pass, `Thread` to an internall call, now pass `Mono.ICallArg<Thread>` which is, effectively just `MonoInternalThread *volatile *` on the native side - and thus compatible with all our existing `HANDLES` (and some `NOHANDLES`) icalls.

This is enough to get the linker to consider the fields of `Thread` as trimmable.  Currently all the trimmable fields of `Thread` are actually kept alive by other code in the BCL, but if we add `private IntPtr garbage` to `Thread`, the linker will remove it.  So the `ICallArg<Thread>` trick is working.

### CODE REVIEW

**Comment by lambdageek** [comment]
@marek-safar draft of the struct layout idea that we talked about.  I'm not sure why `System.Threading.Thread` is being preserved.  Even if I add garbage fields they are kept for some reason.  (`Mono.MonoDomain` is different - garbage fields there got trimmed)

**Comment by lambdageek** [comment]
This "works" but it's useless until we teach a linker that for some classes it's ok to remove most fields even if there's an `InternalCall`

**Comment by lambdageek** [comment]
ok, new idea. We add a [`ObjectHandleOnStack`](https://github.com/dotnet/runtime/blob/128d3ecf42549f0913e93a0dc2c90d73c651fab4/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/QCallHandles.cs#L24)-style argument
```csharp
namespace Mono
{
    internal unsafe ref struct ICallArg<T> where T : class?
    {
        private void *_ptr;
        internal ICallArg (ref T o) {
            _ptr = Internal.Runtime.CompilerServices.Unsafe.AsPointer (ref o);
        }
    }
}
```

And then pass `new Mono.ICallArg<Thread>(ref t)` wherever we used to pass a plain `Thread` argument.  Turns out we don't have to change anythign on the native side since the `HANDLES` icall wrappers are already effectively a `MonoInternalThread **`.

This is enough to convince the linker that it doesn't need to preserve everything in `Thread`, and it retains a modicum of type safety so we're not just passing around IntPtr everywhere.

If I do this to every icall, then I can add a `private IntPtr garbage` field to `Thread` and the linker will remove it.

**Comment by MichalStrehovsky** [comment]
IMHO, Linker keeping the layout of everything passed to InternalCall methods is something that could be disabled - InternalCall methods are not a user scenario. This is just a convenience to runtime developers that seems to now be inconvenient.

Linker probably only keeps them because it treats p/invoke and InternalCall the same: https://github.com/mono/linker/blob/9d47fbfb5f2fcd2d209ab4b4847f5dd6f2074067/src/linker/Linker.Steps/MarkStep.cs#L2632.

The p/invoke handling within linker is already problematic anyway so it might be beneficial to split those two concept as part of addressing the p/invoke issues. The new handling could just be "keep the hollowed out type" and we could use ILLinkTrim/DynamicDependency or whatever else mechanism to keep the subset of fields the runtime cares about.

**Comment by marek-safar** [comment]
@vargaz your thoughts ?

**Comment by vargaz** [comment]
Wouldn't be easier to just mark the fields accessed by the runtime with [Preserve] ?

**Comment by vargaz** [comment]
The semantics we need is:
* Keep the field alive if the parent type is alive
* Only need to keep layout compatibility, i.e. FooClass Foo; can be replaced by object Foo;

**Comment by marek-safar** [comment]
> Keep the field alive if the parent type is alive

That's very aggressive. We usually need a field only when logic using the field is kept.

> Only need to keep layout compatibility, i.e. FooClass Foo; can be replaced by object Foo;

We need logic that is able to trim fields that are part of the layout but can be fully removed when the dependencies are removed (they cannot be of object type as that would require cast on all references)

**Comment by vargaz** [comment]
The fields need to be kept even if nobody is using them because the runtime depends on the layout so they cannot be individually linked out. Their type can be linked out and changed to object etc. if managed code is not using them.

**Comment by lambdageek** [comment]
If we do everything in the linker, we will need:
*  Add a new attribute on classes `[TrimmableSequential]`: if the class is `[StructLayout(Sequential)]` its fields may be trimmed or their types simplified.
* If a `[TrimmableSequential]` class is passed to an icall, that does not automatically force all fields to be preserved.
* All fields in a `[TrimmableSequential]` class before the first `[Preserve]` upto the last `[Preserve]` will be kept, but they are eligible for type simplification.
* If a `[TrimmableSequential]` has any fields *not* marked with `[Preserve]` after the  last `[Preserve]` field,  they are eligible to  be trimmed or their types may be simplified.
* If a class derives from a `[TrimmableSequential]` class and has at least one `[Preserve]` field, all the fields of the parent  class are kept, but they are eligible for type simplification.
* When fields of a `[TrimmableSequential]` class are only kept because of `[Preserve]` constraints, their types can be simplified:
   * `enum`, `bool` are changed to the underlying primitive integer type
   * reference types are changed to `object`
   * struct types are  recursively eligible for simplification if they're otherwise trimmable.
   * fields of generic parameter types with a `T : class` constraint can be changed to `object` (not sure this is worth it - we don't otherwise monomorphize generics, do we?)
   * fields of all other types are unchanged

Then we won't need any runtime changes.

Something like this would be  reasonable, IMO.  It might be a little bit challenging to maintain `object-internals.h` for subclasses, but probably it's ok.  It might be nice to have some infrastructure to catch trimmability regressions (ie I add a new `[Preserve]` field to some subclass and it forces the `[TrimmableSequential]` parent to grow).

**Comment by marek-safar** [comment]
I was thinking more about a setup like this, would this work?

```c#
[Mono.MonoRuntimeLayoutAware(nameof(_runtime))]
public partial class Thread
{
	[StructLayout(LayoutKind.Explicit)] // Not sure if Size is needed
	public struct RuntimeLayout
	{
		[FieldOffset(16)] public int fieldNeededInManaged;
	    [FieldOffset(42)] public int fieldNeededInManaged2;
	}
	
	private RuntimeLayout _runtime;
}
```

Then the only change in linker we would need to do is to not mark aggressively the whole struct when used in icall or use the trick @lambdageek have with the handle.

**Comment by lambdageek** [comment]
Ok, I will continue to clean up this PR for now. If we decide to do everything purely in the linker, I'll close it.

**Comment by lambdageek** [comment]
Ok, updated to use `[MonoRuntimeLayoutAware(nameof(someField))]`

Also got rid of all the fields in `Mono.MonoDomain` - there were a few places in the runtime where we looked at its data, but we can just return the root domain directly, so there's no need to carry it around.

@marek-safar I removed the `Thread._runtime` field from the linker descriptor file, but I actually think it's a mistake - the runtime is generally not ready to have classes with known layout no have any of those fields at all.  So if `Thread._runtime` is removed entirely, we will get a warning from `class-init.c` followed by some random crash.

**Comment by vargaz** [comment]
Note that these fields are not really a problem, its the types which are kept alive by the field type which could be the problem.

**Comment by marek-safar** [comment]
> Also got rid of all the fields in Mono.MonoDomain - there were a few places in the runtime where we looked at its data, but we can just return the root domain directly, so there's no need to carry it around.

I think that would be great to land separately (maybe we could even remove the MonoObject type and create System.Object instance as one step further)

>I actually think it's a mistake - the runtime is generally not ready to have classes with known layout no have any of those fields at all. So if Thread._runtime is removed entirely, we will get a warning from class-init.c followed by some random crash.

I think it'd be fine to keep that field in descriptor if we need to but we cannot have StructLayout on the type of the field or the illinker has to keep the struct fully with all its type dependencies (as @vargaz pointed out)

**Comment by lambdageek** [comment]
Oh I see - `LayoutKind.Sequential` is the problem.

I think using `LayoutKind.Explicit` is going to be incredibly error-prone.  And we will need separate definitions for 32-bit and 64-bit platforms due to IntPtr size, and padding/alignment requirements.  It's going to be impossible to maintain.
If we can tell the linker to do substitutions on the types of the `RuntimeLayout` structs somehow, I think that would be better.

**Comment by marek-safar** [comment]
> I think using LayoutKind.Explicit is going to be incredibly error-prone.

Yeah, that's what I thought too. What we could do is to introduce SPC only `LayoutKind.Runtime` and teach linker to rewrite fields types wich this value. If we go with a separate struct the linker could actually even convert `LayoutKind.Runtime` to `LayoutKind.Explicit` and add used offsets.

**Comment by lambdageek** [comment]
We're going to try another approach with linker attributes for simplifying the types of fields that the needs to be layout compatible.  (ie replace 'SomeClass' by 'object' and 'SomeStruct' by a byte array of the appropriate fixed size).

**Comment by MichalStrehovsky** [comment]
> 'SomeStruct' by a byte array of the appropriate fixed size

Linker is not aware of type layout rules. I would be wary of doing things that might change the packing or alignment (e.g. if the struct had `double` fields originally and we're on ARM). Those rules are complex to replicate and the bugs manifest themselves as corruptions. Doing something for reference type fields only seems less risky.

**Pull request closed without merging**
