### PR TITLE
Increment nested depth in TooDeepJsonDocument test by 10x

### LINKED ISSUE #105532: Test failure: System.Text.Json.Serialization.Tests.JsonElementTests.DeepEquals_TooDeepJsonDocument_ThrowsInsufficientExecutionStackException
**Failed in:** [runtime-coreclr crossgen2 20240724.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=754702&view=ms.vss-test-web.build-test-results-tab&runId=19131944&resultId=203289&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-x64-TestReadyToRun_Release-Ubuntu.2204.Amd64.Open
    - System.Text.Json.Serialization.Tests.JsonElementTests.DeepEquals_TooDeepJsonDocument_ThrowsInsufficientExecutionStackException
net9.0-linux-Release-x64-TestReadyToRun_Release-(Centos.8.Amd64.Open)Ubuntu.2204.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream8-helix
    - System.Text.Json.Serialization.Tests.JsonElementTests.DeepEquals_TooDeepJsonDocument_ThrowsInsufficientExecutionStackException
net9.0-linux-Release-x64-TestReadyToRun_Release-(Debian.11.Amd64.Open)Ubuntu.2204.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-amd64
    - System.Text.Json.Serialization.Tests.JsonElementTests.DeepEquals_TooDeepJsonDocument_ThrowsInsufficientExecutionStackException
```

**Error message:**
```
 Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.InsufficientExecutionStackException)
```

**Stack trace:**
```
   at System.Text.Json.Serialization.Tests.JsonElementTests.DeepEquals_TooDeepJsonDocument_ThrowsInsufficientExecutionStackException() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/JsonElementTests.cs:line 237

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by stephentoub**
Hopefully fix https://github.com/dotnet/runtime/issues/105532
cc: @lambdageek

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Review by ivdiazsa — APPROVED** [review]
LGTM!

**Comment by eiriktsarpalis** [comment]
Seems to be causing the test to time out in the interpreter:
```
   System.Text.Json.Tests: [Long Running Test] 'System.Text.Json.Serialization.Tests.JsonElementTests.DeepEquals_TooDeepJsonDocument_ThrowsInsufficientExecutionStackException', Elapsed: 00:06:59
   System.Text.Json.Tests: [Long Running Test] 'System.Text.Json.Serialization.Tests.JsonElementTests.DeepEquals_TooDeepJsonDocument_ThrowsInsufficientExecutionStackException', Elapsed: 00:08:59

...
[EXECUTION TIMED OUT]
```

I think we can just disable the test in that environment.

**Comment by stephentoub** [comment]
> Seems to be causing the test to time out in the interpreter

@kg

**Comment by kg** [comment]
Yes, I recommend just disabling this for interp. My guess is that the cost of things like method calls is so much higher that it makes the cost of this test inflated vs JIT.

**Review by eiriktsarpalis — APPROVED** [review]

**Pull request merged**
