### PR TITLE
fix rid processing on macOS

### LINKED ISSUE #60341: RuntimeIdentifierTests.VerifyOSRid started failing on macOS ARM64
Example on runtime-staging: https://dev.azure.com/dnceng/public/_build/results?buildId=1410047&view=ms.vss-test-web.build-test-results-tab&runId=40895764&resultId=162151&paneView=debug

```
Assert.EndsWith() Failure:
Expected:    Arm64
Actual:   ···.11.6
```

The test debug logging prints:
```
### OS: Distro=OSX Version=11.6.0 Description=Darwin 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 Version=Unix 11.6.0 Arch=Arm64 Rid=osx.11.6
```

... so it thinks the RID is `osx.11.6` which indeed looks incorrect.

If I'm reading the AzDO logs correctly it started with https://github.com/dotnet/runtime/commit/04f70d6fc56a5261b0dcad0e6217fcbf92570aaf which brought in a new version of Microsoft.NETCore.DotNetHost.

I'm suspecting https://github.com/dotnet/runtime/pull/59066 since it touched that code and was merged near that timeframe.

/cc @wfurt @agocke @vitek-karas

### PR DESCRIPTION
**Pull request by wfurt**
#59066 made some changes how we calculate RID on macOS and it was not quite right. 

The test was failing because there was embedded '\0'. So even if we add the architecture, that would be stripped with `.c_str`. It actually worked for `11.2.3` I started with but failed on `11.2` (no real ARM dependency IMHO)

There is still another problem. The way how the old code was written we would always return `osx.11.0` from `get_current_os_rid_platform` even for 11.6. That does not break the test but then when we walk the graph we would end up with generic `osx-arm64`. So to maintain compatibility, I added special processing for 11.x (and verified with dotnet --info)

For 12.0+ the rid will be `osx.12-arm64` and that match `<Versions>10.10;10.11;10.12;10.13;10.14;10.15;10.16;11.0;12</Versions>`

fixes #60341

### CODE REVIEW

**Review by vitek-karas — APPROVED** [review]
Looks good.

**Comment by danmoseley** [comment]
Regression was after 6.0 fork right?

**Comment by agocke** [comment]
> The test was failing because there was embedded '\0'. 

I don't understand this -- where was the embedded '\0'?

**Review by akoeplinger — APPROVED** [review]

**Comment by wfurt** [comment]
LLVM AOT looks like infrastructure unrelated to the change.

**Pull request merged**
