### PR TITLE
Removed branches in some UriHelper-methods by using a bitmask-approach

### PR DESCRIPTION
**Pull request by gfoidl**
## Description

Instead of a series of branches use a bitmask for the lookup, thus reducing the branch-count and reducing the code-size.

### `IsLWS`

```
|             Method |      Mean |     Error |    StdDev | Ratio | RatioSD | Code Size |
|------------------- |----------:|----------:|----------:|------:|--------:|----------:|
|            Default | 2.6859 ns | 0.0253 ns | 0.0237 ns |  1.00 |    0.00 |      86 B |
|            BitMask | 2.1301 ns | 0.0305 ns | 0.0437 ns |  0.80 |    0.02 |      85 B |
|     BitMaskInlined | 0.6052 ns | 0.0082 ns | 0.0077 ns |  0.23 |    0.00 |      51 B |
| BitMaskFor32BitToo | 0.5963 ns | 0.0029 ns | 0.0026 ns |  0.22 |    0.00 |      50 B |
```
(.NET SDK=7.0.100-rc.2.22426.5)
`BitMaskFor32BitToo` is used.

_Side note_: it's interesting that the JIT inlines the `int`-variant, whilst the `long`-variant isn't inlined by default.

<details>
  <summary>Benchmark code</summary>

```c#
using System.Runtime.CompilerServices;
using BenchmarkDotNet.Attributes;

Bench bench = new();
Console.WriteLine(bench.Default());
Console.WriteLine(bench.BitMask());
Console.WriteLine(bench.BitMaskInlined());
Console.WriteLine(bench.BitMaskFor32BitToo());

#if !DEBUG
BenchmarkDotNet.Running.BenchmarkRunner.Run<Bench>();
#endif

[DisassemblyDiagnoser]
public class Bench
{
    [Benchmark(Baseline = true, OperationsPerInvoke = char.MaxValue - char.MinValue)]
    public int Default()
    {
        int count = 0;

        for (int i = char.MinValue; i <= char.MaxValue; ++i)
        {
            if (IsLWS((char)i))
            {
                count++;
            }
        }

        return count;
    }

    [Benchmark(OperationsPerInvoke = char.MaxValue - char.MinValue)]
    public int BitMask()
    {
        int count = 0;

        for (int i = char.MinValue; i <= char.MaxValue; ++i)
        {
            if (IsLWSBitmask((char)i))
            {
                count++;
            }
        }

        return count;
    }

    [Benchmark(OperationsPerInvoke = char.MaxValue - char.MinValue)]
    public int BitMaskInlined()
    {
        int count = 0;

        for (int i = char.MinValue; i <= char.MaxValue; ++i)
        {
            if (IsLWSBitmaskInlined((char)i))
            {
                count++;
            }
        }

        return count;
    }

    [Benchmark(OperationsPerInvoke = char.MaxValue - char.MinValue)]
    public int BitMaskFor32BitToo()
    {
        int count = 0;

        for (int i = char.MinValue; i <= char.MaxValue; ++i)
        {
            if (IsLWSBitmaskFor32BitToo((char)i))
            {
                count++;
            }
        }

        return count;
    }

    internal static bool IsLWS(char ch)
    {
        return (ch <= ' ') && (ch == ' ' || ch == '\n' || ch == '\r' || ch == '\t');
    }

    internal static bool IsLWSBitmask(char ch)
    {
        if (ch > ' ')
        {
            return false;
        }

        const long BitMask =
            (1L << ' ')
          | (1L << '\n')
          | (1L << '\r')
          | (1L << '\t');

        return ((1L << ch) & BitMask) != 0;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static bool IsLWSBitmaskInlined(char ch)
    {
        if (ch > ' ')
        {
            return false;
        }

        const long BitMask =
            (1L << ' ')
          | (1L << '\n')
          | (1L << '\r')
          | (1L << '\t');

        return ((1L << ch) & BitMask) != 0;
    }

    internal static bool IsLWSBitmaskFor32BitToo(char ch)
    {
        ch -= '\t';

        if ((uint)ch > ' ' - '\t')
        {
            return false;
        }

        const int BitMask =
            (1 << ' ' - '\t')
          | (1 << '\n' - '\t')
          | (1 << '\r' - '\t')
          | (1 << '\t' - '\t');

        return ((1 << ch) & BitMask) != 0;
    }
}
```
</details>

### `IsGenDelim`

```
|                    Method |      Mean |     Error |    StdDev | Ratio | RatioSD | Code Size |
|-------------------------- |----------:|----------:|----------:|------:|--------:|----------:|
|                   Default | 2.1748 ns | 0.0431 ns | 0.0732 ns |  1.00 |    0.00 |      93 B |
|                   BitMask | 2.2292 ns | 0.0431 ns | 0.0496 ns |  1.02 |    0.04 |      88 B |
|            BitMaskInlined | 0.6262 ns | 0.0123 ns | 0.0168 ns |  0.29 |    0.01 |      56 B |
|        BitMaskFor32BitToo | 2.1815 ns | 0.0425 ns | 0.0436 ns |  0.99 |    0.04 |     115 B |
| BitMaskFor32BitTooInlined | 0.6267 ns | 0.0124 ns | 0.0196 ns |  0.29 |    0.01 |      82 B |
```
(.NET SDK=7.0.100-rc.2.22426.5)
`BitMaskInlined` is used for 64-bit platforms. The variant for 32-bit with `int`s instead of `long`s has same clock-time, but code size is much bigger and it has some additional branches in contrast to the `long`-version.
Thus for 32-bit the current code is kept.

<details>
  <summary>Benchmark code</summary>

```c#
using System.Runtime.CompilerServices;
using BenchmarkDotNet.Attributes;

Bench bench = new();
Console.WriteLine(bench.Default());
Console.WriteLine(bench.BitMask());
Console.WriteLine(bench.BitMaskInlined());
Console.WriteLine(bench.BitMaskFor32BitToo());
Console.WriteLine(bench.BitMaskFor32BitTooInlined());

#if !DEBUG
BenchmarkDotNet.Running.BenchmarkRunner.Run<Bench>();
#endif

[DisassemblyDiagnoser]
public class Bench
{
    [Benchmark(Baseline = true, OperationsPerInvoke = char.MaxValue - char.MinValue)]
    public int Default()
    {
        int count = 0;

        for (int i = char.MinValue; i <= char.MaxValue; ++i)
        {
            if (IsGenDelim((char)i))
            {
                count++;
            }
        }

        return count;
    }

    [Benchmark(OperationsPerInvoke = char.MaxValue - char.MinValue)]
    public int BitMask()
    {
        int count = 0;

        for (int i = char.MinValue; i <= char.MaxValue; ++i)
        {
            if (IsGenDelimBitMask((char)i))
            {
                count++;
            }
        }

        return count;
    }

    [Benchmark(OperationsPerInvoke = char.MaxValue - char.MinValue)]
    public int BitMaskInlined()
    {
        int count = 0;

        for (int i = char.MinValue; i <= char.MaxValue; ++i)
        {
            if (IsGenDelimBitMaskInlined((char)i))
            {
                count++;
            }
        }

        return count;
    }

    [Benchmark(OperationsPerInvoke = char.MaxValue - char.MinValue)]
    public int BitMaskFor32BitToo()
    {
        int count = 0;

        for (int i = char.MinValue; i <= char.MaxValue; ++i)
        {
            if (IsGenDelimBitMaskFor32BitToo((char)i))
            {
                count++;
            }
        }

        return count;
    }

    [Benchmark(OperationsPerInvoke = char.MaxValue - char.MinValue)]
    public int BitMaskFor32BitTooInlined()
    {
        int count = 0;

        for (int i = char.MinValue; i <= char.MaxValue; ++i)
        {
            if (IsGenDelimBitMaskFor32BitTooInlined((char)i))
            {
                count++;
            }
        }

        return count;
    }

    internal static bool IsGenDelim(char ch)
    {
        return (ch == ':' || ch == '/' || ch == '?' || ch == '#' || ch == '[' || ch == ']' || ch == '@');
    }

    internal static bool IsGenDelimBitMask(char ch)
    {
        if ((uint)(ch - '#') > (']' - '#'))
        {
            return false;
        }

        const long BitMask =
            (1L << '#')
          | (1L << '/')
          | (1L << ':')
          | (1L << '?')
          | (1L << '@')
          | (1L << '[')
          | (1L << ']');

        return ((1L << ch) & BitMask) != 0;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static bool IsGenDelimBitMaskInlined(char ch)
    {
        if ((uint)(ch - '#') > (']' - '#'))
        {
            return false;
        }

        const long BitMask =
            (1L << '#')
          | (1L << '/')
          | (1L << ':')
          | (1L << '?')
          | (1L << '@')
          | (1L << '[')
          | (1L << ']');

        return ((1L << ch) & BitMask) != 0;
    }

    internal static bool IsGenDelimBitMaskFor32BitToo(char ch)
    {
        int val = ch - '#';

        if ((uint)val > (']' - '#'))
        {
            return false;
        }

        if ((uint)val <= ('@' - '#'))
        {
            const int BitMask =
                (1 << '#' - '#')
              | (1 << '/' - '#')
              | (1 << ':' - '#')
              | (1 << '?' - '#')
              | (1 << '@' - '#');

            return ((1 << val) & BitMask) != 0;
        }

        val = ch - '[';

        if ((uint)val <= (']' - '['))
        {
            const int BitMask =
                (1 << '[' - '[')
              | (1 << ']' - '[');

            return ((1 << val) & BitMask) != 0;
        }

        return false;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static bool IsGenDelimBitMaskFor32BitTooInlined(char ch)
    {
        int val = ch - '#';

        if ((uint)val > (']' - '#'))
        {
            return false;
        }

        if ((uint)val <= ('@' - '#'))
        {
            const int BitMask =
                (1 << '#' - '#')
              | (1 << '/' - '#')
              | (1 << ':' - '#')
              | (1 << '?' - '#')
              | (1 << '@' - '#');

            return ((1 << val) & BitMask) != 0;
        }

        val = ch - '[';

        if ((uint)val <= (']' - '['))
        {
            const int BitMask =
                (1 << '[' - '[')
              | (1 << ']' - '[');

            return ((1 << val) & BitMask) != 0;
        }

        return false;
    }
}
```
</details>

### `IsBidiControlCharacter` / `StripBidiControlCharacters`

```
|         Method |      Mean |     Error |    StdDev |    Median | Ratio | RatioSD | Code Size |
|--------------- |----------:|----------:|----------:|----------:|------:|--------:|----------:|
|        Default | 2.2298 ns | 0.0440 ns | 0.0858 ns | 2.1911 ns |  1.00 |    0.00 |     107 B |
| DefaultInlined | 1.2352 ns | 0.0227 ns | 0.0287 ns | 1.2315 ns |  0.54 |    0.03 |      76 B |
|        BitMask | 0.6075 ns | 0.0102 ns | 0.0085 ns | 0.6074 ns |  0.27 |    0.01 |      52 B |
```
(.NET SDK=7.0.100-rc.2.22426.5)
`BitMask` is used for 64-bit, see note on previous section.

More interesting are the results for the use of that method, namely `StripBidiControlCharacters`.

```
|         Method |     Mean |    Error |  StdDev | Ratio | RatioSD | Code Size |
|--------------- |---------:|---------:|--------:|------:|--------:|----------:|
|        Default | 415.8 ns |  8.14 ns | 7.99 ns |  1.00 |    0.00 |     400 B |
| DefaultInlined | 300.7 ns |  2.67 ns | 2.49 ns |  0.72 |    0.02 |     426 B |
|        BitMask | 576.9 ns | 10.18 ns | 9.53 ns |  1.39 |    0.02 |     389 B |
| BitMaskInlined | 247.7 ns |  2.31 ns | 2.04 ns |  0.60 |    0.01 |     405 B |
```
(.NET SDK=7.0.100-rc.2.22426.5)
`BitMaskInlined` is used.

<details>
  <summary>Benchmark code</summary>

```c#
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using BenchmarkDotNet.Attributes;

Bench bench = new();
bench.Setup();
string res0 = bench.Default();
string res1 = bench.DefaultInlined();
string res2 = bench.BitMask();
string res3 = bench.BitMaskInlined();
Console.WriteLine(res0 == res1 && res0 == res2 && res0 == res3);
Console.WriteLine(res0);
Console.WriteLine(res1);
Console.WriteLine(res2);
Console.WriteLine(res3);

#if !DEBUG
BenchmarkDotNet.Running.BenchmarkRunner.Run<Bench>();
#endif

[DisassemblyDiagnoser]
public class Bench
{
    private string? _input;

    [GlobalSetup]
    public void Setup()
    {
        char[] chars = { '\u200E', '\u200F', '\u202A', '\u202B', '\u202C', '\u202D', '\u202E' };
        char[] input = new char[100];
        Random rnd = new(Seed: 42);

        for (int i = 0; i < input.Length; ++i)
        {
            if (rnd.Next() % 2 == 0)
            {
                input[i] = chars[rnd.Next(chars.Length)];
            }
            else
            {
                input[i] = (char)(rnd.Next('a', 'z' + 1));
            }
        }

        _input = new string(input);
        Console.WriteLine(_input);
    }

    [Benchmark(Baseline = true)]
    public string Default() => StripBidiControlCharacters(_input);

    [Benchmark]
    public string DefaultInlined() => StripBidiControlCharactersInlined(_input);

    [Benchmark]
    public string BitMask() => StripBidiControlCharactersBitMask(_input);

    [Benchmark]
    public string BitMaskInlined() => StripBidiControlCharactersBitMaskInlined(_input);

    internal static unsafe string StripBidiControlCharacters(ReadOnlySpan<char> strToClean, string? backingString = null)
    {
        Debug.Assert(backingString is null || strToClean.Length == backingString.Length);

        int charsToRemove = 0;
        foreach (char c in strToClean)
        {
            if ((uint)(c - '\u200E') <= ('\u202E' - '\u200E') && IsBidiControlCharacter(c))
            {
                charsToRemove++;
            }
        }

        if (charsToRemove == 0)
        {
            return backingString ?? new string(strToClean);
        }

        if (charsToRemove == strToClean.Length)
        {
            return string.Empty;
        }

        fixed (char* pStrToClean = &MemoryMarshal.GetReference(strToClean))
        {
            return string.Create(strToClean.Length - charsToRemove, (StrToClean: (IntPtr)pStrToClean, strToClean.Length), (buffer, state) =>
            {
                var strToClean = new ReadOnlySpan<char>((char*)state.StrToClean, state.Length);
                int destIndex = 0;
                foreach (char c in strToClean)
                {
                    if ((uint)(c - '\u200E') > ('\u202E' - '\u200E') || !IsBidiControlCharacter(c))
                    {
                        buffer[destIndex++] = c;
                    }
                }
                Debug.Assert(buffer.Length == destIndex);
            });
        }

        static bool IsBidiControlCharacter(char ch)
        {
            return (ch == '\u200E' /*LRM*/ || ch == '\u200F' /*RLM*/ || ch == '\u202A' /*LRE*/ ||
                    ch == '\u202B' /*RLE*/ || ch == '\u202C' /*PDF*/ || ch == '\u202D' /*LRO*/ ||
                    ch == '\u202E' /*RLO*/);
        }
    }

    internal static unsafe string StripBidiControlCharactersInlined(ReadOnlySpan<char> strToClean, string? backingString = null)
    {
        Debug.Assert(backingString is null || strToClean.Length == backingString.Length);

        int charsToRemove = 0;
        foreach (char c in strToClean)
        {
            if ((uint)(c - '\u200E') <= ('\u202E' - '\u200E') && IsBidiControlCharacter(c))
            {
                charsToRemove++;
            }
        }

        if (charsToRemove == 0)
        {
            return backingString ?? new string(strToClean);
        }

        if (charsToRemove == strToClean.Length)
        {
            return string.Empty;
        }

        fixed (char* pStrToClean = &MemoryMarshal.GetReference(strToClean))
        {
            return string.Create(strToClean.Length - charsToRemove, (StrToClean: (IntPtr)pStrToClean, strToClean.Length), (buffer, state) =>
            {
                var strToClean = new ReadOnlySpan<char>((char*)state.StrToClean, state.Length);
                int destIndex = 0;
                foreach (char c in strToClean)
                {
                    if ((uint)(c - '\u200E') > ('\u202E' - '\u200E') || !IsBidiControlCharacter(c))
                    {
                        buffer[destIndex++] = c;
                    }
                }
                Debug.Assert(buffer.Length == destIndex);
            });
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static bool IsBidiControlCharacter(char ch)
        {
            return (ch == '\u200E' /*LRM*/ || ch == '\u200F' /*RLM*/ || ch == '\u202A' /*LRE*/ ||
                    ch == '\u202B' /*RLE*/ || ch == '\u202C' /*PDF*/ || ch == '\u202D' /*LRO*/ ||
                    ch == '\u202E' /*RLO*/);
        }
    }

    internal static unsafe string StripBidiControlCharactersBitMask(ReadOnlySpan<char> strToClean, string? backingString = null)
    {
        Debug.Assert(backingString is null || strToClean.Length == backingString.Length);

        int charsToRemove = 0;
        foreach (char c in strToClean)
        {
            if (IsBidiControlCharacter(c))
            {
                charsToRemove++;
            }
        }

        if (charsToRemove == 0)
        {
            return backingString ?? new string(strToClean);
        }

        if (charsToRemove == strToClean.Length)
        {
            return string.Empty;
        }

        fixed (char* pStrToClean = &MemoryMarshal.GetReference(strToClean))
        {
            return string.Create(strToClean.Length - charsToRemove, (StrToClean: (IntPtr)pStrToClean, strToClean.Length), (buffer, state) =>
            {
                var strToClean = new ReadOnlySpan<char>((char*)state.StrToClean, state.Length);
                int destIndex = 0;
                foreach (char c in strToClean)
                {
                    if (!IsBidiControlCharacter(c))
                    {
                        buffer[destIndex++] = c;
                    }
                }
                Debug.Assert(buffer.Length == destIndex);
            });
        }

        static bool IsBidiControlCharacter(char ch)
        {
            if ((uint)(ch - '\u200E') > ('\u202E' - '\u200E'))
            {
                return false;
            }

            const long BitMask =
                (1 << '\u200E')
              | (1 << '\u200F')
              | (1 << '\u202A')
              | (1 << '\u202B')
              | (1 << '\u202C')
              | (1 << '\u202D')
              | (1 << '\u202E');

            return ((1 << ch) & BitMask) != 0;
        }
    }

    internal static unsafe string StripBidiControlCharactersBitMaskInlined(ReadOnlySpan<char> strToClean, string? backingString = null)
    {
        Debug.Assert(backingString is null || strToClean.Length == backingString.Length);

        int charsToRemove = 0;
        foreach (char c in strToClean)
        {
            if (IsBidiControlCharacter(c))
            {
                charsToRemove++;
            }
        }

        if (charsToRemove == 0)
        {
            return backingString ?? new string(strToClean);
        }

        if (charsToRemove == strToClean.Length)
        {
            return string.Empty;
        }

        fixed (char* pStrToClean = &MemoryMarshal.GetReference(strToClean))
        {
            return string.Create(strToClean.Length - charsToRemove, (StrToClean: (IntPtr)pStrToClean, strToClean.Length), (buffer, state) =>
            {
                var strToClean = new ReadOnlySpan<char>((char*)state.StrToClean, state.Length);
                int destIndex = 0;
                foreach (char c in strToClean)
                {
                    if (!IsBidiControlCharacter(c))
                    {
                        buffer[destIndex++] = c;
                    }
                }
                Debug.Assert(buffer.Length == destIndex);
            });
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        static bool IsBidiControlCharacter(char ch)
        {
            if ((uint)(ch - '\u200E') > ('\u202E' - '\u200E'))
            {
                return false;
            }

            const long BitMask =
                (1 << '\u200E')
              | (1 << '\u200F')
              | (1 << '\u202A')
              | (1 << '\u202B')
              | (1 << '\u202C')
              | (1 << '\u202D')
              | (1 << '\u202E');

            return ((1 << ch) & BitMask) != 0;
        }
    }
}
```
</details>

### CODE REVIEW

**Comment by EgorBo** [comment]
Related: https://github.com/dotnet/runtime/issues/8418 (to do it in jit)

**Comment by gfoidl** [comment]
Ah, cool (also your blog-post that touches this kind of optimizations).

Reading that issue is seems that some work in Roslyn (to be consistent on emitting a switch/jump table and not kind of search) as well in the JIT to pattern match this is needed.
If this works (Roslyn + JIT) is pursued, then it's best to close this PR and leave the work to the compilers? But it looks like it's still some work to do...

**Comment by stephentoub** [comment]
For reference, the Regex source generator spits out:
```C#
(((long)((0x8008010C000000A0UL << (int)(charMinusLow = (uint)c - '#')) & (charMinusLow - 64)) < 0))
```
for the same set as in IsGenDelim.  It'd be great if the JIT could handle this and source generator could emit the more natural/readable:
```C#
(ch == ':' || ch == '/' || ch == '?' || ch == '#' || ch == '[' || ch == ']' || ch == '@')
```
while also optimizing every other case where someone writes code like this.

cc: @markples, who was asking about this the other day.

**Comment by stephentoub** [comment]
> it's best to close this PR and leave the work to the compilers

Does this PR measurably move the needle on public Uri surface area?

**Comment by EgorBo** [comment]
Actually, Jit could emit a bit test if Roslyn emitted `switch` opcode for this:
```csharp
    internal static bool IsGenDelim(char ch)
    {
        switch (ch)
        {
            case ':':
            case '/':
            case '?':
            case '#':
            case '[':
            case ']':
            case '@':
                return true;
            default:
                return false;
        }
    }
```
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANmgExAGoAfAAQCYBGAWAChyBmAAipYGEWBvBl/ltgB2GGFCEBDXG2pIWwCBGkBJAM4BxGEIAiMXNgC2ACjAALCVBZmAlHwG96Apy1UB3bBjMsTp24+f8DgEBYBKqMCwA5CDRdsECoeFRAPSx/vH8iRGRAPxpGQlh2QDE+QVWRVEA2mUFWVEAurUZ9ZHk5M3lbADsLBhQAK4wANxxGQQwAGYSA7hYY13kvdO44aPpzgC+Y9v0m0A=

Unfortunately, Roslyn has fairly conservative limits on switch opcode

**Comment by gfoidl** [comment]
> Does this PR measurably move the needle on public Uri surface area?

The needle is just moved a little bit below of noise. I didn't realize that these methods are hit quite rare when called from public surface. 
So with the less natural code it's not worth it. So I'll close this PR.

But, on the credit side we have a discussion about bit testing in the JIT 😃
https://github.com/dotnet/runtime/issues/8418 tracks this.

---

> For reference, the Regex source generator spits out:

https://github.com/dotnet/runtime/blob/4cf1383c8458945b7eb27ae5f57338c10ed25d54/src/libraries/System.Text.RegularExpressions/gen/RegexGenerator.Emitter.cs#L4504-L4513

🚀 nice use of the bits. Thanks for pointing to this (and the comment in the source, of course).

**Comment by gfoidl** [comment]
ad https://github.com/dotnet/runtime/pull/75705#issuecomment-1248738875

Somewhat interesting: Roslyn doesn't apply much optimizations to C# code, but here where just a plain translation of the switch would be desired Roslyn tries it's best to optimize the emitted code 😉

**Comment by gfoidl** [comment]
Sorry for spamming...

Would something like the following be feasable:

> `(ch is ':' or '/' or '?' or '#' or '[' or ']' or '@')`

Here Roslyn see pattern matching. If there would be a special IL-instruction for "set test" (e.g. `settest.s 35 44 47 63 64 91 93`) then it's quite easy for the JIT to recognize and emit bit-test (iff the range allows it).

Use cases are not only pattern matching chars, but also HTTP status code, on parsing checking for `\n`, `\r` or other special symbols. And the written code is as natural as it could be instead of using bit-hacks.

**Comment by stephentoub** [comment]
> 🚀 nice use of the bits. Thanks for pointing to this (and the comment in the source, of course).

I borrowed the approach from https://github.com/dotnet/runtime/blob/ad8debf62d9ae538c4e1a2f473a5a86377eabbc8/src/libraries/Common/src/System/HexConverter.cs#L310

**Pull request closed without merging**
