### PR TITLE
Revert "Dead Ending Microsoft.CSharp Package and Bumping the leftout assembly versions to 5.0.0.0 (#2264)"

### PR DESCRIPTION
**Pull request by jkotas**
This reverts commit 5fca04171171f118bca0f93aa9741f205b8cdc29.

### CODE REVIEW

**Comment by jkotas** [comment]
This is fixing:

```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040 (FUSION_E_REF_DEF_MISMATCH))\nFile name: 'System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

that majority of PRs are failing with now.

cc @Anipik

**Review by jaredpar — APPROVED** [review]

**Comment by jaredpar** [comment]
Using Admin to merge this change. Everything is already in a broken state and this should be taking us out of it.

**Review by ViktorHofer — COMMENTED** [review]
LGTM.

**Comment by ViktorHofer** [comment]
cc @Anipik

**Comment by ViktorHofer** [comment]
> Using Admin to merge this change. Everything is already in a broken state and this should be taking us out of it.

Why would you need admin permissions to merge the approved change?

**Comment by jaredpar** [comment]
> Why would you need admin permissions to merge the approved change?

It wasn't actually necessary here. I'm used to Roslyn where we have more required status checks. Hence merging before tests run can only be done with admin. The message I posted is just my standard "i'm about to do something outside recommended guidelines"

**Pull request merged**
