### PR TITLE
Unify the FlushProcessWriteBuffers mechanism for macOS arm64 / x64

### PR DESCRIPTION
**Pull request by janvorli**
The macOS arm64 was using a new mechanism to implement FlushProcessWriteBuffers
because the original one based on a wired memory page doesn't work on arm64.
We have seen people hitting problems with the wired memory page allocation on
x64 in the past due to the fact that wired memory is a scarce resource and
in some cases, e.g. in presence of apps that greedily grab all of the available
wired memory pages, we were unable to initialize coreclr and execute any .NET
application.

This change switches x64 to the same mechanism as arm64 to prevent that issue
from happening and updates the minimum supported x64 macOS to 10.14. That's the
version required for the new APIs the change is using. Apple stopped supporting
10.13 a year ago anyways.

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @odhanson

**Review by jkotas — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
According to our docs, our minimum supported macOS version is now 10.15, so if there's anywhere else we want to utilize new APIs that are only available in newer macOS versions than 10.14, it looks like we can use them.

**Comment by odhanson** [comment]
Thanks! Will we be able to service this jnto .NET 6 ?

**Pull request merged**
