### PR TITLE
Add executable bit to tizen sh files

### PR DESCRIPTION
**Pull request by ericstj**

### CODE REVIEW

**Comment by ericstj** [comment]
Fixes https://github.com/dotnet/runtime/issues/42438

**Comment by ericstj** [comment]
@gbalykov does this fix also need to go into 5.0?

**Comment by gbalykov** [comment]
@ericstj, yes, this is needed in 5.0 too. Thanks!

**Review by gbalykov — APPROVED** [review]

**Comment by ericstj** [comment]
@Anipik or @ViktorHofer can I get a review here?

**Review by ViktorHofer — APPROVED** [review]

**Review by Anipik — APPROVED** [review]

**Pull request merged**
