### PR TITLE
System.DirectoryServices.Protocols.LdapConnection has wrong argument check (#78459)

### PR DESCRIPTION
**Pull request by GeertvanHorrik**
See #78459 for more information.

If anything else needs to be done, please let me know.

### CODE REVIEW

**Comment by buyaa-n** [comment]
> If anything else needs to be done, please let me know.

@GeertvanHorrik a (unit) test would be helpful for verifying the fix, also its helpful to make sure somebody would not break it again accidentally

**Comment by GeertvanHorrik** [comment]
@buyaa-n to be honest I am having a little bit of troubles trying to get the unit tests to run on my machine. The error I am getting:

```
System.DllNotFoundException : Unable to load DLL 'libldap.dylib' or one of its dependencies: The specified module could not be found.
```

or a similar one:

```
 System.TypeInitializationException : The type initializer for 'Ldap' threw an exception.
---- System.DllNotFoundException : Unable to load DLL 'libldap-2.4.so.2' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

I am assuming it runs the tests on Linux instead of Windows? I have WSL installed, but running tests from within Visual Studio. I checked the readme, but it has no mention on how to fix this (or I must have missed it).

What can I do to fix this error? Then I will make sure the "new functionality" is covered by working unit tests.

Thank you!

**Comment by buyaa-n** [comment]
> I am assuming it runs the tests on Linux instead of Windows?  I have WSL installed, but running tests from within Visual Studio. I checked the readme, but it has no mention on how to fix this (or I must have missed it).

From `IsWindowsOrLibLdapIsInstalled` condition on the test type looks it run if it is `Windows` or if LDAP server is installed:
https://github.com/dotnet/runtime/blob/4b98c1ef3378d419240351e242f26512e4f393c6/src/libraries/System.DirectoryServices.Protocols/tests/LdapConnectionTests.cs#L12-L13

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.DirectoryServices.Protocols/tests/DirectoryServicesTestHelpers.cs#L13

So, if you are using windows, you can just run the tests without any issue (No need to install WSL and install LDAP server on it, I was able to run them on windows successfully)

In case you want test it on Linux and installed WSL probably you need to install LDAP server too, like OpenLDAP or OpenDJ

By the way what readme did you read? We might want to update that if needed.

**Review by buyaa-n — APPROVED** [review]
LGTM, thank you!

**Comment by GeertvanHorrik** [comment]
Thanks @buyaa-n ! 

Btw it was this readme I was looking on how to run the (AD specific) unit tests correctly:

https://github.com/dotnet/runtime/blob/main/src/libraries/System.DirectoryServices.Protocols/README.md

**Pull request merged**
