### PR TITLE
Remove SELECTANY usage

### LINKED ISSUE #39281: Native .so files are considerably larger in 5.0 than they were in 3.1
### Steps to repro:

1. Using the latest SDK https://github.com/dotnet/installer#installers-and-binaries, create and publish a Hello World app:
    - `dotnet new console`
    - `dotnet publish -r linux-x64 -c Release`
2. Check the sizes of the output .so files. Using `5.0.0-preview.8.20361.2` of the runtime, I see:

Assembly | Size
-- | --
libclrjit.so | 3,323 KB
libcoreclr.so | 11,532 KB
libmscordaccore.so | 4,095 KB
libSystem.IO.Compression.Native.so | 900 KB

3. Now use a 3.1 app and publish:

Assembly | Size
-- | --
libclrjit.so | 2,997 KB
libcoreclr.so | 9,172 KB
libmscordaccore.so | 3,400 KB
libSystem.IO.Compression.Native.so | 771 KB

Why did these assemblies get so much bigger in 5.0? coreclr grew by about 25%.

cc @vitek-karas @janvorli

### PR DESCRIPTION
**Pull request by janvorli**
This change replaces SELECTANY by using constexpr. It results in major
reduction of the native binaries size (3.2MB in the libcoreclr.so case)

Close #39281

### CODE REVIEW

**Comment by jkotas** [comment]
Does `constexpr` guarantee that there are no duplicates? I believe that it only strips unused references, but it does not eliminate duplicates, so we are still leaving money on the table. https://stackoverflow.com/questions/50488831/use-of-constexpr-in-header-file has some context.

I believe that it would have to be `inline constexpr` to actually eliminate duplicates.

**Comment by jkotas** [comment]
Also, we should get rid of other duplicate static const data from the header files. Here are the constant data symbols that I see defined in the .rodata more than once:
```
        0000000000000007              _ZL12__nullstring
        000000000000000c              _ZL22UnwindOpExtraSlotTable
        000000000000000e              _ZL13__wnullstring
        0000000000000010              empty_frame
        0000000000000014              _ZN14DiagnosticsIpcL18GenericErrorHeaderE
        0000000000000014              _ZN14DiagnosticsIpcL20GenericSuccessHeaderE
        0000000000000059              _ZL15__lookuptable_s
        00000000000000a0              _ZL29g_rbTheSilverlightPlatformKey
        0000000000000100              operands
        0000000000000118              _ZN12_GLOBAL__N_114g_shash_primesE
```

**Comment by janvorli** [comment]
@jkotas I was considering that, but inline constexpr is c++17 only. We currently use c++11 features and I am not sure if we want to move to c++17 just for this.

**Comment by jkotas** [comment]
Agree. Should we do this the old-fashioned way and move the definitions to .c/.cpp files?

**Comment by janvorli** [comment]
There are only a few symbols duplicated, all of them taking 16 bytes (896 bytes total). So there doesn't seem to be much to be gained by redoing the change in the traditional way.

Moreover, while some of the cases can be handled trivially, the EXTERN_GUID case would be kind of ugly, as we would have to duplicate all the GUIDS at two places (one in the header, one in a cpp file). Lot of the guids are in prebuilt headers on Unix pregenerated from ild files.

2x IID_ICeeGen
2x IID_ICeeGenInternal
2x IID_IGetIMDInternalImport
5x IID_IMapToken
6x IID_IMDCommon
3x IID_IMDInternalEmit
7x IID_IMDInternalImport
2x IID_IMDInternalImportENC
2x IID_IMetaDataAssemblyEmit
2x IID_IMetaDataDispenserEx
3x IID_IMetaDataEmit
2x IID_IMetaDataEmit2
2x IID_IMetaDataEmitHelper
2x IID_IMetaDataHelper
6x IID_IMetaDataImport
3x IID_IMetaDataImport2
2x IID_IMetaDataTables

20x g_tkCorEncodeToken

So I'd prefer keeping the change as is.

**Comment by janvorli** [comment]
I was referring to the symbols that my change touched.

**Comment by jkotas** [comment]
> There are only a few symbols duplicated, all of them taking 16 bytes (896 bytes total)

Ok, that does not sound too bad. Could you please resolve the conflict?

**Comment by janvorli** [comment]
Rebased

**Comment by jkotas** [comment]
Failure is https://github.com/dotnet/runtime/issues/39484

**Review by jkotas — APPROVED** [review]
Thanks!

**Comment by jkotas** [comment]
This change regressed coreclr.dll size on Windows by ~200kB. I have opened a new bug on this: #39599

**Pull request merged**
