### PR TITLE
[RISC-V] Increase timeouts in CacheTests

### PR DESCRIPTION
**Pull request by yurai007**
This patch fixes System.Text.Json.Serialization.Tests.CacheTests on Debug build.

Part of https://github.com/dotnet/runtime/issues/84834
cc @dotnet/samsung

### CODE REVIEW

**Comment by risc-vv** [comment]
<details><summary>aab7117c is being scheduled for building and testing</summary>

GIT: `aab7117c9ef7c4fc9d9405a3c4760665a72cfaaa`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Review by tomeksowi — APPROVED** [review]

**Review by Bajtazar — APPROVED** [review]

**Review by sirntar — APPROVED** [review]

**Review by clamp03 — APPROVED** [review]

**Review by t-mustafin — APPROVED** [review]

**Review by bartlomiejko — APPROVED** [review]
LGTM

**Comment by risc-vv** [comment]
<details><summary>e288820b is being scheduled for building and testing</summary>

GIT: `e288820bd81342abfbb0d2f5b98d5c21df734ff4`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Review by jkotas — APPROVED** [review]

**Pull request merged**
