### PR TITLE
Perform ldr to ldp peephole optimization

### LINKED ISSUE #35132: ARM64: Optimize pair of "ldr reg, [reg]" to ldp
```asm
ldr     x1, [x19,#16]
ldr     x2, [x19,#24]
```
can be combined into `ldp` if the loads are happening from subsequent memory.
```asm
ldp x1, x2, [x19, #16]
```
I collected no. of such `ldr` pairs in framework libraries and found approx. 5900 pairs in 3500 methods.

Details:

[ldr_ldr_x_to_ldp.txt](https://github.com/dotnet/runtime/files/4495149/ldr_ldr_x_to_ldp.txt)

category:cq
theme:optimization
skill-level:intermediate
cost:small
impact:medium

### PR DESCRIPTION
**Pull request by kunalspathak**
In #77540 we started replacing consecutive loads and stores with `ldp` and `stp` except if they are for local variables. See https://github.com/dotnet/runtime/pull/77540#pullrequestreview-1268515376 for details. For loads, turns out that we do not need `offset` tracking for loads and gc-liveness tracking for `ldp` is already present. So this PR just relaxes the rule and enable the optimization for 2 consecutive loads.

For non-gc stores too, it enabled the peephole optimization because those variables do not need gc liveness tracking.

Contributes to https://github.com/dotnet/runtime/issues/81278 and https://github.com/dotnet/runtime/issues/55365
Fixes: https://github.com/dotnet/runtime/issues/35132 and https://github.com/dotnet/runtime/issues/35130

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib 

[gcstress run is clean](https://dev.azure.com/dnceng-public/public/_build/results?buildId=229976&view=results).

**Comment by kunalspathak** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=229641&view=ms.vss-build-web.run-extensions-tab) from earlier run.

image

**Comment by BruceForstall** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=230556&view=ms.vss-build-web.run-extensions-tab)

Diffs look great.

**Review by BruceForstall — APPROVED** [review]
You didn't update the comment above: "Don't do this if either instruction had a local variable." It would be useful to update this and provide more detail about _why_ ldr is allowed.

It also occurs to me that you could also allow str of locals if both str are non-GC types, e.g., floating-point/SIMD, or even TYP_INT. I still think in both ldr and str cases it would be helpful in DEBUG to be able to annotate JitDisasm with the local var (+offset) being read/written, for each local.

**Comment by kunalspathak** [comment]
> You didn't update the comment above: "Don't do this if either instruction had a local variable." It would be useful to update this and provide more detail about _why_ ldr is allowed.

Done

> 
> It also occurs to me that you could also allow str of locals if both str are non-GC types, e.g., floating-point/SIMD, or even TYP_INT. 

That's true. Added it.

> I still think in both ldr and str cases it would be helpful in DEBUG to be able to annotate JitDisasm with the local var (+offset) being read/written, for each local.

Can we do it as a follow-up PR? I will open a .NET 8 tracking issue for it.

**Comment by BruceForstall** [comment]
> Can we do it as a follow-up PR?

yes. And please open an issue.

**Review by BruceForstall — APPROVED** [review]

**Comment by kunalspathak** [comment]
> yes. And please open an issue.

https://github.com/dotnet/runtime/issues/84504

**Comment by kunalspathak** [comment]
gc-stress failures are unrelated.

**Pull request merged**
