### PR TITLE
Fix condition for building runtime.native.System.IO.Ports

### PR DESCRIPTION
**Pull request by ericstj**

### CODE REVIEW

**Comment by ericstj** [comment]
I'd like to double-check the build output of this PR to ensure we are getting this package now.  So please don't merge until I have confirmed.

**Comment by ericstj** [comment]
Replaces https://github.com/dotnet/runtime/pull/34720
Fixes #34715

**Comment by ericstj** [comment]
Confirmed that this fixes the issue by examining build artifacts.

**Review by safern — APPROVED** [review]

**Comment by ericstj** [comment]
Interesting, rerun caused failure in mono LLVM leg due to duplicate artifact publish:
```
##[error]Artifact BuildLogs_Mono_LLVM_Linux_x64_debug already exists for build 594294.
```
I believe that's a bug in the yml. @directhex

**Comment by safern** [comment]
Maybe the Publish Logs steps should append the attempt at the end.

**Comment by ericstj** [comment]
> Maybe the Publish Logs steps should append the attempt at the end.

Yeah, or not publish on failure.  I misread the build status and it seems like it was just a warning.  The failure was a timeout.

**Comment by ericstj** [comment]
Only failure was timeout.

**Pull request merged**
