### PR TITLE
[release/6.0] Don't lookup the pack without an alias from the workload

### PR DESCRIPTION
**Pull request by lewing**
This doesn't work with aliasing

### CODE REVIEW

**Review by jonathanpeppers — APPROVED** [review]
I tested this locally building this branch: https://github.com/xamarin/xamarin-android/pull/7265

Then locally this change:

```xml
<LatestRuntimeFrameworkVersion Condition="'%(KnownRuntimePack.TargetFramework)' == 'net6.0' and '%(KnownRuntimePack.RuntimePackLabels)' == 'Mono'">6.0.9</LatestRuntimeFrameworkVersion>
```

Allows Android projects to be able to restore again.

Previously, I was hitting:
```
Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error : NETSDKZZZZ: Error getting pack version: Pack 'Microsoft.NETCore.App.Runtime.Mono.android-arm' was not present in workload manifests.
Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error : NETSDKZZZZ: Error getting pack version: Pack 'Microsoft.NETCore.App.Runtime.Mono.android-arm64' was not present in workload manifests.
Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error : NETSDKZZZZ: Error getting pack version: Pack 'Microsoft.NETCore.App.Runtime.Mono.android-x86' was not present in workload manifests.
Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error : NETSDKZZZZ: Error getting pack version: Pack 'Microsoft.NETCore.App.Runtime.Mono.android-x64' was not present in workload manifests.
```

**Review by dsplaisted — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
approved.  Adding @carlossanlop to know when to merge.

**Comment by lewing** [comment]
@carlossanlop the failure has nothing to do with the change, can we merge this asap?

**Comment by carlossanlop** [comment]
@lewing we are past code complete for September servicing. Let me ask if there is still runway. Otherwise, this will have to wait until next month.

**Comment by lewing** [comment]
This is blocking 6.0.9

**Comment by carlossanlop** [comment]
Thanks for the clarification. Merging now.

**Pull request merged**
