### PR TITLE
Make OpenSSL ENGINE support light up

### PR DESCRIPTION
**Pull request by vcsjones**
This is a proposal to make OpenSSL ENGINE support light up to react to Fedora 41 / RHEL soft-disabling OpenSSL ENGINEs.

The background for the Fedora project is here. https://discussion.fedoraproject.org/t/f41-change-proposal-openssl-deprecate-engine-system-wide/111344/8

Fedora, currently, has not fully removed OpenSSL ENGINE support. They moved the header, `engine.h` to a separate package. However, the OpenSSL as-built has all of the ENGINE APIs, the header is just not there by default.

For non-portable builds, we disable ENGINE support.
  * Pros: This is "in line" with what Fedora proposes, and is likely more future proof against a stronger deprecation. Portable builds will still have ENGINE support, provided the platform has a working ENGINE implementation.
  * Cons: We now have a platform that does not have ENGINE. Since we need to support portable builds anyway, we have the function definitions ourselves. So this disables ENGINE support when we can technically light it up.

Contributes to #104775

### CODE REVIEW

**Review by krwq — APPROVED** [review]
Assuming we decide on option 2 looks good to me as is

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
I ran the [manual ENGINE tests](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Security.Cryptography/tests/osslplugins/README.md) in `OpenSslNamedKeysTests` on a system that does have a working ENGINE implementation to ensure nothing broke and all of them passed. This is ready.

**Comment by omajid** [comment]
Hey @vcsjones I am seeing `HAVE_OPENSSL_ENGINE - Failed` on some platforms where I wasn't expecting to. 

On Fedora 40:

```
$ cd runtime
$ git rev-parse HEAD
bbabbc99b6412690641f233c4c1bc506fbcadea7
$ ./build.sh
...
  Commencing CoreCLR Repo build
  __OutputRid: linux-x64
  Setting up directories for build
  Checking prerequisites...
  Commencing build of "install" target in "CoreCLR component" for linux.x64.Debug in /home/omajid/devel/dotnet/runtime/artifacts/obj/coreclr/linux.x64.Debug
  Invoking "/home/omajid/devel/dotnet/runtime/eng/native/gen-buildsys.sh" "/home/omajid/devel/dotnet/runtime/src/coreclr" "/home/omajid/devel/dotnet/runtime/artifacts/obj/coreclr/lin
ux.x64.Debug" x64 linux clang Debug ""  -DCLR_CMAKE_PGO_INSTRUMENT=0 -DCLR_CMAKE_OPTDATA_PATH= -DCLR_CMAKE_PGO_OPTIMIZE=0 -DCLI_CMAKE_FALLBACK_OS="linux" -DFEATURE_DISTRO_AGNOSTIC_SS
L=1 -DCDAC_BUILD_TOOL_BINARY_PATH=/home/omajid/devel/dotnet/runtime/artifacts/bin/coreclr/linux.x64.Debug/cdac-build-tool/cdac-build-tool.dll -DCLR_DOTNET_HOST_PATH=/home/omajid/deve
l/dotnet/runtime/.dotnet/dotnet
  Not searching for unused variables given on the command line.
  -- The C compiler identification is Clang 18.1.6
...
  -- Looking for SSL_get0_alpn_selected
  -- Looking for SSL_get0_alpn_selected - found
  -- Looking for EVP_chacha20_poly1305
  -- Looking for EVP_chacha20_poly1305 - found
  -- Looking for EVP_sha3_256
  -- Looking for EVP_sha3_256 - found
  -- Looking for EVP_DigestSqueeze
  -- Looking for EVP_DigestSqueeze - not found
  -- Performing Test HAVE_OPENSSL_ENGINE
  -- Performing Test HAVE_OPENSSL_ENGINE - Failed
  -- Looking for include file elf.h
  -- Looking for include file elf.h - found
  -- Looking for include file sys/elf.h
...
  __OutputRid: linux-x64
  Setting up directories for build
  Checking prerequisites...
  Commencing build of "install" target in "native libraries component" for linux.x64.Debug in /home/omajid/devel/dotnet/runtime/artifacts/obj/native/net9.0-linux-Debug-x64
  Invoking "/home/omajid/devel/dotnet/runtime/eng/native/gen-buildsys.sh" "/home/omajid/devel/dotnet/runtime/src/native/libs" "/home/omajid/devel/dotnet/runtime/artifacts/obj/native/
net9.0-linux-Debug-x64" x64 linux clang Debug ""  -DCMAKE_USE_PTHREADS=0 -DCMAKE_STATIC_LIB_LINK=0 -DFEATURE_DISTRO_AGNOSTIC_SSL=1 -DFEATURE_DISTRO_AGNOSTIC_SSL=1
  Not searching for unused variables given on the command line.
  -- The C compiler identification is Clang 18.1.6
...
  -- Found OpenSSL: /usr/lib64/libcrypto.so (found version "3.2.1")
  -- Looking for EC_GF2m_simple_method
  -- Looking for EC_GF2m_simple_method - not found
  -- Looking for SSL_get0_alpn_selected
  -- Looking for SSL_get0_alpn_selected - found
  -- Looking for EVP_chacha20_poly1305
  -- Looking for EVP_chacha20_poly1305 - found
  -- Looking for EVP_sha3_256
  -- Looking for EVP_sha3_256 - found
  -- Looking for EVP_DigestSqueeze
  -- Looking for EVP_DigestSqueeze - not found
  -- Performing Test HAVE_OPENSSL_ENGINE
  -- Performing Test HAVE_OPENSSL_ENGINE - Failed
  -- Configuring done (13.6s)
  -- Generating done (0.0s)
  -- Build files have been written to: /home/omajid/devel/dotnet/runtime/artifacts/obj/native/net9.0-linux-Debug-x64
...
```

I see the same behaviour with `mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-24.04-20240711152923-c20804d` container:

```
...
  -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.13")
  -- Looking for EC_GF2m_simple_method
  -- Looking for EC_GF2m_simple_method - found
  -- Looking for SSL_get0_alpn_selected
  -- Looking for SSL_get0_alpn_selected - found
  -- Looking for EVP_chacha20_poly1305
  -- Looking for EVP_chacha20_poly1305 - found
  -- Looking for EVP_sha3_256
  -- Looking for EVP_sha3_256 - found
  -- Looking for EVP_DigestSqueeze
  -- Looking for EVP_DigestSqueeze - not found
  -- Performing Test HAVE_OPENSSL_ENGINE
  -- Performing Test HAVE_OPENSSL_ENGINE - Failed
...
`

**Comment by vcsjones** [comment]
That is not expected. Let me take a look.

**Comment by omajid** [comment]
Thanks for the quick fix, @vcsjones !

**Comment by vcsjones** [comment]
@omajid I just merged a fix, but if would be great if you could check it from your end as well.

**Pull request merged**
