### PR TITLE
Ensure CreateScalarUnsafe gets constant handling on Arm64

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
@kunalspathak, could you assist with this?

I was working on a different PR but was getting failures, so I've isolated it down to something that is trivial and "should" work. But which raises an assert in the Arm64 LSRA

**Comment by kunalspathak** [comment]
I will check it out @tannergooding

**Comment by kunalspathak** [comment]
@tannergooding - This should unblock you.

**Comment by kunalspathak** [comment]
Earlier, the interval corresponding to `CreateScalarUnsafe` was a regular one, but with this change, it is a "constant interval". If a register holds a constant value and if we ever have to save upper half of this vector register, we should clear the constant value from the register as well. We were not doing it and that caused the assert failure. The fix was to clear it as well.

**Comment by tannergooding** [comment]
Thanks much for the fix!

**Comment by tannergooding** [comment]
This should be ready for review. CC. @dotnet/jit-contrib 

Notably SPMI diffs has marked everything as "missed". I've not seen this before

**Comment by jakobbotsch** [comment]
> Notably SPMI diffs has marked everything as "missed". I've not seen this before

The missed contexts look to be just a small fraction of the overall contexts. It is expected due to the revert #76235 that put us back at an old JIT-EE GUID, so the collection we are using now is quite old (from last Sunday) and JIT changes since then are causing some misses.

**Comment by tannergooding** [comment]
Thanks! That's a bit unfortunate as I was expecting a few diffs to show up, but I think that's fine overall

**Review by kunalspathak — APPROVED** [review]
LGTM

**Pull request merged**
