### PR TITLE
[wasm] try this with icu updated

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Comment by lewing** [comment]
@radekdoulik It looks like prereqs:windowsservercore-ltsc2022-helix-webassembly-20220118164817-dc6e6f1 isn't showing up as an image but the json failures are gone on linux.  Maybe it is time to try a 3.1.x bump again?

**Comment by lewing** [comment]
@radical the WBT failure looks like an OOM on blazor?

**Comment by radical** [comment]
> @radical the WBT failure looks like an OOM on blazor?

Yeah, https://github.com/dotnet/runtime/issues/66591 .

**Comment by radekdoulik** [comment]
> @radekdoulik It looks like prereqs:windowsservercore-ltsc2022-helix-webassembly-20220118164817-dc6e6f1 isn't showing up as an image but the json failures are gone on linux. Maybe it is time to try a 3.1.x bump again?

I tried on Friday, but didn't merge main, so it didn't build :-) I have updated it today, https://github.com/dotnet/runtime/pull/63894. The windows image needs different machine with docker, which is able to pull that one.

**Comment by vargaz** [comment]
Note that emscripten is up to 3.1.7 now.

**Pull request closed without merging**
