### PR TITLE
Disable asm checking for JITMinOpts

### LINKED ISSUE #76344: Runtime_34937 and Runtime_33972 JITMinOpts test failures
Affected tests:
- `JIT/Regression/JitBlue/Runtime_34937/Runtime_34937/Runtime_34937.sh`
- `JIT/Regression/JitBlue/Runtime_33972/Runtime_33972/Runtime_33972.sh`

Error: `expected string not found in input`

Runfo failures in [last 30 days (Runtime_34937)](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22jit%2Fregression%2Fjitblue%2Fruntime_34937%2Fruntime_34937%2Fruntime_34937.sh%22) and in [last 30 days (Runtime_33972)](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22jit%2Fregression%2Fjitblue%2Fruntime_33972%2Fruntime_33972%2Fruntime_33972.sh%22) as of 10/3:
- First occurrences of both failures are in Rolling run [28591](https://runfo.azurewebsites.net/view/build/?number=28591) on 9/24
- 10x Rolling runs affected 9/24-9/28 + couple of PRs (no occurrences 9/28-10/3)

Error example from [Console](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-37a52ae3999b4a9085/JIT.Regression/1/console.a10ce08f.log?%3Fhelixlogtype%3Dresult):
```
  Starting:    JIT.Regression.XUnitWrapper (parallel test collections = on, max threads = 8)
    JIT/Regression/JitBlue/Runtime_34937/Runtime_34937/Runtime_34937.sh [FAIL]
      __tmp1_Runtime_34937.cs:36:12: error: ARM64: expected string not found in input
       // ARM64: {{^ *}} and w1, w0, #15{{$}}
                 ^
      __jit_disasm.out:31:56: note: scanning from here
      ; Assembly listing for method Program:PerformMod_2(int):int
                                                             ^
      __jit_disasm.out:52:2: note: possible intended match here
       and w0, w0, #15
       ^
      
      Input file: __jit_disasm.out
      Check file: __tmp1_Runtime_34937.cs
      
      -dump-input=help explains the following input dump.
      
      Input was:
      <<<<<<
```

## Original Report

Various Linux/Mac arm64/x64 JITMinOpts legs of the jitstress pipeline fail these tests.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=32864&view=ms.vss-test-web.build-test-results-tab&runId=660270&resultId=108719&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

### PR DESCRIPTION
**Pull request by BruceForstall**
Fixes #76344

Extension of #76276

### CODE REVIEW

**Review by TIHan — DISMISSED** [review]

**Comment by TIHan** [comment]
Thank you @BruceForstall for this. I remember seeing this same check from "JitOptimizationSensitive". However, some of the FileCheck (csproj) tests themselves forcefully set TieredCompilation=0 and JitMinOpts=0 - which means FileCheck won't run as you are checking for a zero-length JitMinOpts env var. See:
- https://github.com/dotnet/runtime/blob/main/src/tests/JIT/Regression/JitBlue/Runtime_33972/Runtime_33972.csproj#L12
- https://github.com/dotnet/runtime/blob/main/src/tests/JIT/Regression/JitBlue/Runtime_34937/Runtime_34937.csproj#L12

**Review by TIHan — COMMENTED** [review]
Thank you @BruceForstall for this. I remember seeing this same check from "JitOptimizationSensitive". However, some of the FileCheck (csproj) tests themselves forcefully set TieredCompilation=0 and JitMinOpts=0 - which means FileCheck won't run as you are checking for a zero-length JitMinOpts env var. See:

https://github.com/dotnet/runtime/blob/main/src/tests/JIT/Regression/JitBlue/Runtime_33972/Runtime_33972.csproj#L12
https://github.com/dotnet/runtime/blob/main/src/tests/JIT/Regression/JitBlue/Runtime_34937/Runtime_34937.csproj#L12

**Comment by TIHan** [comment]
Isn't this already fixed by https://github.com/dotnet/runtime/pull/76276 ? The link to the issue you mentioned is against a commit from yesterday, I just merged https://github.com/dotnet/runtime/pull/76276 today - we had problems with Linux/Mac specifically not including precommands that would force set `JitMinOpts` to be zero.

**Comment by BruceForstall** [comment]
> Isn't this already fixed by #76276 ? The link to the issue you mentioned is against a commit from yesterday, I just merged #76276 today - we had problems with Linux/Mac specifically not including precommands that would force set `JitMinOpts` to be zero.

It appears to be, since the overnight jitstress job didn't have these failures:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=34429&view=ms.vss-test-web.build-test-results-tab

However, doesn't that just assume that any FileCheck test is required to force TieredCompilation=0 / JITMinOpts=0 and have the block: https://github.com/dotnet/runtime/blob/60986693ea08b865dad65ff6896d7c20f8a04b82/src/tests/JIT/Regression/JitBlue/Runtime_33972/Runtime_33972.csproj#L9-L18?

Shouldn't we allow the test to run in any configuration, but only disable the FileCheck part of the testing in non-default conditions, like TieredCompilation != 0, or JITMinOpts != 0?

**Pull request closed without merging**
