### PR TITLE
Don't include empty prefix with EnvironmentVariablesConfigurationProvider

### PR DESCRIPTION
**Pull request by JamesNK**
Don't include an empty prefix for `EnvironmentVariablesConfigurationProvider`. Makes config debug view cleaner to view:

image

Note that this is a runtime change to `ToString`. It needs to be modified in `ToString` because it's used to build up the debug view string.

### CODE REVIEW

**Comment by tarekgh** [comment]
Would that be a breaking change for any user calling `ToString` in non-debugging scenarios?

**Comment by JamesNK** [comment]
Maybe, which is why I called it out. However, I don't know why anyone would want to parse the result of ToString. All the configuration provides override ToString for debugging. It's not in an easily parsable format.

**Comment by tarekgh** [comment]
>  I don't know why anyone would want to parse the result of ToString.

I understand but nobody knows. Would it make sense if we proceed with this is to file a breaking charge issue? https://github.com/dotnet/docs/issues/new?assignees=gewarren&labels=breaking-change%2CPri1%2Cdoc-idea&projects=&template=breaking-change.yml&title=%5BBreaking+change%5D%3A+

**Comment by JamesNK** [comment]
I don't think we'd create a breaking change issue in dotnet/aspnetcore for this level of change, but dotnet/runtime might have a different standard. It's up to you.

**Review by tarekgh — APPROVED** [review]

**Comment by JamesNK** [comment]
@tarekgh Ok to merge?

**Pull request merged**
