### PR TITLE
JIT: Add support for bounds check no throw assertions in range check and make overflow check more precise

### LINKED ISSUE #9422: [Jit] Loop condition doesn't elide bounds check
As a condition of a `while` it doesn't elide the check
```csharp
while ((uint)i >= (uint)entries.Length)
{    
    // not elided
    if (entries[i].hashCode == hashCode && comparer.Equals(key, entries[i].key))
    {
```
Changing it to an `if` + `break` does elide the check
```csharp
do
{
    if ((uint)i >= (uint)entries.Length)
    {
        break;
    }
    
    // elided
    if (entries[i].hashCode == hashCode && comparer.Equals(key, entries[i].key))
    {
```

category:cq
theme:bounds-checks
skill-level:expert
cost:small

### LINKED ISSUE #83349: Loop condition vs initial guard check impacts bounds checking
Consider these two functionally-identical loops:
```C#
    public static int M1(int i, ReadOnlySpan<char> src)
    {    
        int sum = 0;
        while ((uint)i < (uint)src.Length)
        {
            sum += src[i++];
        }
        return sum;
    }
    
    public static int M2(int i, ReadOnlySpan<char> src)
    {    
        int sum = 0;
        while (true)
        {
            if ((uint)i >= (uint)src.Length) break;

            sum += src[i++];
        }
        return sum;
    }
```
The second simply moves the loop condition to be the very first thing in the body.  [SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+BiAdgVwDZ4CGweMABACYCWAzsaQLABQAAgEwCMzLAzGSxyT82ZAMLMA3szIz+fAUKpYALmQCyHABRLVVADRkASjEIUA8ljwBPAMoAHQlgA8YABaEoAPjI0oYAJTSshKyZEGhMjo+OAC2ZAC8ZAAMANzhEQDurlSkZJqaODr+VGROeYUq/r5gAHQAMjBYAObKroFMEcHpnTI0sWQA1InVANpUAwMAumkdPQC+3bIsAOzRMTOhC7My6bz8gmRRamzaKocGxqYW1vaOLu5ePn7toSGyi5FnfXGJqR9kWRy5E0yigOBgLx6Um2PUiADM8gUiiVPIkkZVqvVGi02mRgLBCABrDaw2TfQbDPxjCbTf5bWErNYkmRbOZAA===) even decompiles them to C# identically.  However, the former has bounds checks whereas they're appropriately removed for the latter:
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8BiAOwFcAbS7YSmAAgBMBLXW+gWACgABAJgCMPXgGYGvQUgn8GAYR4BvHg1UTxk6S1IYGAWUEAKbbpZoGAJRjYmAeVKUAngGUADtlIAeMAAtsUAD4GXCgwAEoVNUU1BkiY1RNg8nwGAF4GAAYAbjj4gHcfFnoGQ0NyEzCWBk8S8p0wkLAAOgAZGFIAcwwfCO54qNz+1VxkhgBqdMaAbRYxsYBdHL6hgF9BtV4AdiT8JZi15dVcsQkpBkS9fmMdc/MrG3snNw9vP0Dg0N6Y6LV1hJuRil0tk/gwCkVGIYMFByDAvkNlIchgkAGYlMoVKoBdIY+qNVrtLo9BjAWDYADWe2RakB40moRmc0WoIOyK2OypqgOKyAA==)
```asm
C.M1(Int32, System.ReadOnlySpan`1<Char>)
    L0000: sub rsp, 0x28
    L0004: mov rax, [rdx]
    L0007: mov edx, [rdx+8]
    L000a: xor r8d, r8d
    L000d: cmp ecx, edx
    L000f: jae short L0039
    L0011: nop [rax]
    L0018: nop [rax+rax]
    L0020: lea r9d, [rcx+1]
    L0024: cmp ecx, edx
    L0026: jae short L0041
    L0028: mov ecx, ecx
    L002a: movzx ecx, word ptr [rax+rcx*2]
    L002e: add r8d, ecx
    L0031: cmp r9d, edx
    L0034: mov ecx, r9d
    L0037: jb short L0020
    L0039: mov eax, r8d
    L003c: add rsp, 0x28
    L0040: ret
    L0041: call 0x00007fff38258b30
    L0046: int3

C.M2(Int32, System.ReadOnlySpan`1<Char>)
    L0000: mov rax, [rdx]
    L0003: mov edx, [rdx+8]
    L0006: xor r8d, r8d
    L0009: cmp ecx, edx
    L000b: jae short L001f
    L000d: lea r9d, [rcx+1]
    L0011: mov ecx, ecx
    L0013: movzx ecx, word ptr [rax+rcx*2]
    L0017: add r8d, ecx
    L001a: mov ecx, r9d
    L001d: jmp short L0009
    L001f: mov eax, r8d
    L0022: ret
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fix #9422
Fix #83349

Example:
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
public static int Foo(int i, int[] indices)
{
    while ((uint)i < (uint)indices.Length)
    {
        i = indices[i];
    }

    return i;
}
```
Before:
```asm
G_M9328_IG02:  ;; offset=0x0004
       mov      eax, dword ptr [rdx+0x08]
       cmp      eax, ecx
       jbe      SHORT G_M9328_IG04
       align    [0 bytes for IG03]
						;; size=7 bbWeight=1 PerfScore 3.25

G_M9328_IG03:  ;; offset=0x000B
       cmp      ecx, eax
       jae      SHORT G_M9328_IG06
       mov      ecx, ecx
       mov      ecx, dword ptr [rdx+4*rcx+0x10]
       cmp      eax, ecx
       ja       SHORT G_M9328_IG03
						;; size=14 bbWeight=4 PerfScore 19.00

G_M9328_IG04:  ;; offset=0x0019
       mov      eax, ecx
						;; size=2 bbWeight=1 PerfScore 0.25

G_M9328_IG05:  ;; offset=0x001B
       add      rsp, 40
       ret      
						;; size=5 bbWeight=1 PerfScore 1.25

G_M9328_IG06:  ;; offset=0x0020
       call     CORINFO_HELP_RNGCHKFAIL
       int3     
						;; size=6 bbWeight=0 PerfScore 0.00
; Total bytes of code: 38
```
After:
```asm
G_M9328_IG02:  ;; offset=0x0004
       mov      eax, dword ptr [rdx+0x08]
       cmp      eax, ecx
       jbe      SHORT G_M9328_IG04
       align    [0 bytes for IG03]
						;; size=7 bbWeight=1 PerfScore 3.25
G_M9328_IG03:  ;; offset=0x000B
       mov      ecx, ecx
       mov      ecx, dword ptr [rdx+4*rcx+0x10]
       cmp      eax, ecx
       ja       SHORT G_M9328_IG03
						;; size=10 bbWeight=4 PerfScore 14.00
G_M9328_IG04:  ;; offset=0x0015
       mov      eax, ecx
						;; size=2 bbWeight=1 PerfScore 0.25
G_M9328_IG05:  ;; offset=0x0017
       add      rsp, 40
       ret      
						;; size=5 bbWeight=1 PerfScore 1.25

; Total bytes of code 28, prolog size 4, PerfScore 19.00, instruction count 12, allocated bytes for code 28 (MethodHash=e6badb8f) for method Program:Foo(int,int[]):int (FullOpts)
; ============================================================
```

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by jakobbotsch** [comment]
This PR in its current state still doesn't fix the duplicated bounds checks in the shared generic version of `GetValueRefOrAddDefault`, so this needs some more work/investigation.

**Comment by jakobbotsch** [comment]
For some reason, the `int i = bucket - 1` that exists before the loop seems to deter range check from eliminating the bounds check. We compute the correct range, but then give up anyway because of that subtraction of 1:
```scala
Merging assertions from pred edges of BB07 for op [000074] $401
   Computed Range [000074] => <0, $346 + -1>
}
Does overflow [000074]?
Does overflow [000526]?
Does overflow [000536]?
Does overflow [000085]?
[000085] does not overflow
[000536] does not overflow
Does overflow [000534]?
Does overflow [000054]?
Does overflow [000052]?
[000052] does not overflow
Does overflow [000053]?
[000053] does not overflow
Checking bin op overflow ADD <Unknown, Unknown> <-1, -1>
[000054] overflows
[000534] overflows
[000526] overflows
[000074] overflows
Method determined to overflow.
```

No idea what range check is trying to do here, why is this "can overflow" check even necessary if we have proved a range through other means? I suppose range check internally reasons without considering overflow, then later only uses the result if it can prove no overflow is possible. But clearly that's conservative here.

A new minimal repro that does not manage to get rid of bounds checks looks like:
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
public static int Foo(ref int startIndex, int[] indices)
{
    int i = startIndex - 1;
    while ((uint)i < (uint)indices.Length)
    {
        i = indices[i];
    }

    return i;
}
```

**Comment by EgorBo** [comment]
Yep, it's not the first time I see "CanOverflow" ruining things becuase of being too conservative 🤷

**Comment by jakobbotsch** [comment]
`DoesOverflow` does not utilize assertions at all while proving this. It should be able to stop following SSA defs as soon as it sees relevant assertions about the local. That should fix the issue.
But it's weird to me that these checks are done as two separate steps. It seems like it would be more natural to make the range computation conservative when it detects the possibility of overflow.

**Comment by EgorBo** [comment]
> I'll try disabling it and investigating some diffs...

I remember I tried that in the past. I think we even discussed possible cases why it currently cannot be removed, probably @SingleAccretion remembers

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS @EgorBo 

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=636419&view=ms.vss-build-web.run-extensions-tab).
I think it should be fine to remove the overflow check entirely, but I need to do more due diligence before doing that. What range check is doing here is very relevant to some of the stuff I'll need to do for strength reduction as well, so I think the time will be well spent regardless.
In the meantime this PR makes the overflow check a bit smarter by avoiding chasing through SSA defs when we get to a path where we can prove (using assertions) that the value is in the final range we reported. When we can prove that it seems like it should be safe to report that no preceding overflow could have impacted any decision we make based on the information.

A few minor regressions which happen because using this new assertion means we may end up computing a range that gives an upper bound in terms of a different array. That might cause us to no longer eliminate some bounds checks on other arrays.

**Review by EgorBo — APPROVED** [review]
Makes sense to me

**Comment by jakobbotsch** [comment]
> > I think it should be fine to remove the overflow check entirely,
> 
> I found this from the discussion we had in the past about it:
> 
> SingleAccretion — 03/29/2023 9:25 AM it is needed for the "monotonically increasing" part to be correct. So it's supposed to prevent issues like [#69735 (comment)](https://github.com/dotnet/runtime/pull/69735#discussion_r882021176).

Thanks for pointing to that! I'll add a test for something like that to #100820 so we at least have some coverage. So it seems like the overflow handling during the range computation just isn't complete. This example computes the following:
```scala
BinOp add ranges <Dependent, $c3 + -1> <2, 2> = <Dependent, $c3 + 1>
            Computed Range [000030] => <Dependent, $c3 + 1>
```
I think this should rather compute to `<Unknown, $c3 + 1>` if `$c3 + 1` can overflow.

**Review by AndyAyersMS — APPROVED** [review]

**Comment by jakobbotsch** [comment]
FWIW, I want to study the example above a bit more carefully before I merge this one.

**Comment by jakobbotsch** [comment]
I think it's fine. The range returned by range check without the overflow check may have an incorrect lower bound for the monotonically increasing cases; but assertions are sufficient on those paths to make the lower bound right anyway.

**Pull request merged**
