### PR TITLE
[release/7.0] Update to latest .NET 7 Roslyn compiler

### PR DESCRIPTION
**Pull request by jaredpar**
This is a back port of #76459. 

The back port command failde due to merge conflicts hence this was created manually.

### CODE REVIEW

**Comment by carlossanlop** [comment]
@jaredpar when/if this PR is ready, please request a code review sign-off, add the usual template descriptions (customer impact, testing, risks), apply the `servicing-consider` label, and email Tactics requesting approval.

**Comment by jaredpar** [comment]
@carlossanlop .NET tactics has approved this change as it's follow up from compiler changes that went through approval. The need for this was asserted in the discussion and approved (assuming runtime had no push back on the changes). 

> please request a code review sign-off,

How do I request sign off?

**Comment by carlossanlop** [comment]
It's usually the same folks who review the PR in main. So far, I see @stephentoub.

**Comment by jaredpar** [comment]
> .NET tactics has approved this change as it's follow up from compiler changes that went through approval 

BTW: this is a general policy going forward. Source build is now in sync with our product ship. That means whenever we make a toolset change, of which compiler is most prominent, that requires a code / build change in one of our repositories we **must** follow through with that change in impacted repositories. Failing to do so means source build cannot ship. Now when we take changes through .NET Tactics which we suspect will have downstream repo impact we get approval for both the toolset change and the downstream repo change as a pair.

**Comment by carlossanlop** [comment]
> .NET tactics has approved this change as it's follow up from compiler changes that went through approval. The need for this was asserted in the discussion and approved (assuming runtime had no push back on the changes).

Alright, so based on this, I'll apply the `servicing-approved` label. We only need someone else to sign-off.

**Comment by jaredpar** [comment]
@stephentoub can you sign off on the backport of the change to `release/7.0`?

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
