### PR TITLE
HttpStress do not use SYS_PTRACE cap for docker runs

### LINKED ISSUE #76045: HttpStress is broken on Windows (CAP_SYS_PTRACE)
CI runs are broken since 9/22, ~need to check local runs~.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=26259&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=abae1f68-3c73-5bff-491f-f2b908580ce6

```
Creating httpstress_server_1 ... error
ERROR: for httpstress_server_1  Cannot create container for service server: invalid CapAdd: unknown capability: "CAP_SYS_PTRACE"
ERROR: for server  Cannot create container for service server: invalid CapAdd: unknown capability: "CAP_SYS_PTRACE"
```

*Edit (pasting comment from below):*

I cannot reproduce this locally. dotnet/dnceng was there any change around  9/22 that may have affected
- the `NetCore-Public` pool -OR-
- the `1es-windows-2022-open` image -OR-
- the [`stress/http.yml`](https://github.com/dotnet/runtime/blob/main/eng/pipelines/libraries/stress/http.yml) pipeline
?

Seeing an error about `CAP_SYS_PTRACE` on Windows is super esoteric.

### PR DESCRIPTION
**Pull request by antonfirsov**
According to an offline discussion with engineering folks, there is no need for SYS_PTRACE on newer Linux kernels, so we can remove it for all platforms.

The PR is marked as draft because ~it contains an emulated crash to test dump creation. If everything works fine, I will remove it.~

Fixes #76045

### CODE REVIEW

**Comment by antonfirsov** [comment]
The artifacts zip-s contain empty folders even after my undo commit [956e887](https://github.com/dotnet/runtime/pull/76307/commits/956e887ac3992507ffa2ceebfae08a6341aff3c6):
https://dev.azure.com/dnceng-public/public/_build/results?buildId=33787&view=artifacts&pathAsName=false&type=publishedArtifacts

I think we should go ahead with the capability removal and investigate the artifact creation issues later.

**Review by ManickaP — APPROVED** [review]
Thanks!

**Pull request merged**
