### PR TITLE
[RISC-V][LoongArch64] Encode missing tailcall in GC info

### PR DESCRIPTION
**Pull request by tomeksowi**
Fixes intermittent crashes with GCStress=0x3 in `baseservices/TieredCompilation/TieredVtableMethodTests/TieredVtableMethodTests.sh`

In Checked mode usually this assertion failed:
```
        Assert failure(PID 1318399 [0x00141dff], Thread: 1319035 [0x14207b]): !CREATE_CHECK_STRING(pMT && pMT->Validate())
            File: /runtime/src/coreclr/vm/object.cpp:553
            Image: /runtime/artifacts/tests/coreclr/linux.riscv64.Checked/Tests/Core_Root/corerun
```
but sometimes also on this check: `pMT->Validate() fails on SanityCheck() on _ASSERTE((GetComponentSize() <= 2) || IsArray())`.

The problem occurred with hijacking and matched the explanation in comment from dotnet/coreclr#16039:
https://github.com/dotnet/runtime/blob/91939711895b6141e1be509ee743a8afb7a64ee7/src/coreclr/vm/threadsuspend.cpp#L4775-L4787

Part of #84834, cc @dotnet/samsung @shushanhf @LuckyXu-HF

### CODE REVIEW

**Comment by risc-vv** [comment]
<details><summary>aa5542bd is being scheduled for building and testing</summary>

GIT: `aa5542bd1a05c9c66279fd55559cd8075213b2ce`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by tomeksowi** [comment]
> but sometimes also on this check: `pMT->Validate() fails on SanityCheck() on _ASSERTE((GetComponentSize() <= 2) || IsArray())`.

@t-mustafin This symptom matches #105808. Does this PR solve your problem?

**Comment by LuckyXu-HF** [comment]
@tomeksowi thanks very much for notification.

We have tested `baseservices/TieredCompilation/TieredVtableMethodTests/TieredVtableMethodTests.sh` under both `Checked mode` and `Debug mode` with `export DOTNET_GCStress=3` on LA64, we can always pass this testcase whether or not add this PR with several times:

* Checked CoreRoot test Checked testcase with `export DOTNET_GCStress=3`:
```
BEGIN EXECUTION
/home/xuliangyu/fork/runtime/artifacts/tests/coreclr/linux.loongarch64.Checked/Tests/Core_Root///corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true TieredVtableMethodTests.dll ''
Expected: 100
Actual: 100
END EXECUTION - PASSED
```

* Debug CoreRoot test Debug testcase  `export DOTNET_GCStress=3`:
```
BEGIN EXECUTION
/home/xuliangyu/fork/runtime/artifacts/tests/coreclr/linux.loongarch64.Release/Tests/Core_Root///corerun -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true TieredVtableMethodTests.dll ''
Expected: 100
Actual: 100
END EXECUTION - PASSED
```

If I missed some test detail information please let me know, thank you.

**Comment by risc-vv** [comment]
<details><summary>09c454d4 is being scheduled for building and testing</summary>

GIT: `09c454d42d03a5cc242682d8fa3b780a536f75bf`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Review by t-mustafin — APPROVED** [review]

**Comment by t-mustafin** [comment]
> > but sometimes also on this check: `pMT->Validate() fails on SanityCheck() on _ASSERTE((GetComponentSize() <= 2) || IsArray())`.
> 
> @t-mustafin This symptom is similar to #105808. Does this PR solve your problem?

@tomeksowi seems to be great finding! I reproduced a problem on current main (6 fails/10 launches, checked build) and started loop testing of main with this patch for night. Now it is 0 fails/ 8 launches, I will return tomorrow with detailed statistics.

**Review by clamp03 — APPROVED** [review]

**Review by gbalykov — APPROVED** [review]

**Review by jkotas — APPROVED** [review]
Thanks

**Pull request merged**
