### PR TITLE
Use read-only auto-implemented property

### PR DESCRIPTION
**Pull request by xtqqczze**
Fix style issue and avoid diverging from PowerShell repo.

In PowerShell/PowerShell#13507 changes like these were made to the following file which comes from dotnet/runtime:

https://github.com/xtqqczze/PowerShell/blob/b201ca0b8ed736155c1761e60dfd88f82a545c65/src/System.Management.Automation/engine/ComInterop/InteropServices/ComEventsMethod.cs

So I thought it would be helpful to make changes in dotnet/runtime too.

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks for the PR, @xtqqczze.  The plethora of compilation failures need to be resolved before we can look at this.

**Comment by xtqqczze** [comment]
Depends on #44700.

**Comment by xtqqczze** [comment]
reopening to restart tests

**Comment by xtqqczze** [comment]
reopening to restart tests

**Comment by xtqqczze** [comment]
restarting tests

**Comment by xtqqczze** [comment]
@stephentoub I've reverted changes to the bare minimum to avoid divergence from PowerShell/PowerShell#13507.

**Review by stephentoub — APPROVED** [review]
Thanks.

**Comment by xtqqczze** [comment]
Some day I will work out how to open the solution in Visual Studio and run a local build so I can make more substantial contributions.

**Pull request merged**
