### PR TITLE
Remove unused USE_REFEMIT define in System.Private.DataContractSerialization

### LINKED ISSUE #41512: Remove unused USE_REFEMIT define in System.Private.DataContractSerialization
`#if USE_REFEMIT` is used in a quite a few source files in DataContractSerialization, but it is never defined in a .csproj.

https://github.com/dotnet/runtime/issues/20131 mentioned it should be removed as it is unused, but that issue was closed because the .NET Native piece of it was resolved, and this unused define was never removed.

We should remove it, so it doesn't continue cluttering up the code and causing confusion when changes need to be made in this area. (For example - https://github.com/dotnet/runtime/pull/41476#discussion_r479255963).

### PR DESCRIPTION
**Pull request by seonyounggg**
Fixes #41512

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=41664) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=41664) before we can accept your contribution.<br/><br/>:x: seonyounggg [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=41664)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=41664) it.</sub>

**Review by jkotas — APPROVED** [review]

**Review by eerhardt — APPROVED** [review]
Looks good. Just a couple random newlines that could be removed.

Thanks @seonyounggg for helping out!

**Review by StephenMolloy — APPROVED** [review]
Looks fine to me.

**Comment by eerhardt** [comment]
I can fix my nits in a separate PR. Thanks for the contribution here @seonyounggg. Merging.

**Pull request merged**
