### PR TITLE
handle null value when deserializing JsonDocument

### LINKED ISSUE #97323: JsonDocument JsonSerializer.Deserialize does not match JsonDocument.Parse for null root elements
### Description

Given the following code 

```cs
using System.Text.Json;

JsonSerializer.Deserialize<JsonDocument>("null");
```

It returns null instead of JsonDocument.s_nullLiteral.

I'm assuming this is because the converter was never implemented with an overridden HandleNull in https://github.com/dotnet/runtime/pull/34537.

For T = JsonElement things work right due to the converter defaulting to HandleNullOnRead as it's a struct type.

### Reproduction Steps

See description

### Expected behavior

Returns "null" not null

### Actual behavior

Returns null

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by pedrobsaila**
Fixes #97323

### CODE REVIEW

**Review by eiriktsarpalis — APPROVED** [review]
Excellent, thank you!

**Comment by Jozkee** [comment]
@eiriktsarpalis wouldn't this be considered a breaking change?

**Comment by eiriktsarpalis** [comment]
Technically speaking perhaps, but at the same time this is fixing an obvious bug (e.g. root level JSON nulls are handled inconsistently compared to nested nulls in a document).

**Comment by jeffhandley** [comment]
Breaking change document issue filed: https://github.com/dotnet/docs/issues/43869

**Pull request merged**
