### PR TITLE
Apple Silicon reenable 49568

### LINKED ISSUE #49568: [macOS-arm64] CoreCLR - Libraries intermittent failures
There are a lot of intermittent libraries failures which need triage.  This will accumulate the list...
```
   1       ManagedTests.DynamicCSharp.Conformance.dynamic.dynamicType.conversions.target003.target003.TargetIsPredefinedValueType.DynamicCSharpRunTest [FAIL]
   2       Microsoft.VisualBasic.Tests.FileSystemTests.CloseAllFiles [FAIL]
   4       ReadKey.RedirectedConsole_ReadKey [FAIL]
   4       RedirectedStream.ErrorRedirect [FAIL]
   4       RedirectedStream.InputRedirect [FAIL]
   4       RedirectedStream.OutputRedirect [FAIL]
   2       System.Diagnostics.Tests.ProcessCollectionTests.TestThreadCollectionBehavior [FAIL]
   2       System.Diagnostics.Tests.ProcessStartInfoTests.EnvironmentGetEnvironmentVariablesIsCaseSensitive [FAIL]
   2       System.Diagnostics.Tests.ProcessStartInfoTests.ProcessStartInfoEnvironmentDoesNotThrowForCaseSensitiveDuplicates [FAIL]
   2       System.Diagnostics.Tests.ProcessStartInfoTests.ProcessStartInfoEnvironmentVariablesDoesNotThrowForCaseSensitiveDuplicates [FAIL]
   2       System.Diagnostics.Tests.ProcessStartInfoTests.TestEnvironmentOfChildProcess [FAIL]
   2       System.Diagnostics.Tests.ProcessStartInfoTests.TestSetEnvironmentOnChildProcess [FAIL]
   2       System.Diagnostics.Tests.ProcessStartInfoTests.TestWorkingDirectoryPropertyInChildProcess [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream_SynchronizingObject(invokeRequired: False) [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncErrorStream_SynchronizingObject(invokeRequired: True) [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncHalfCharacterAtATime [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncOutputStream [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncOutputStream_BeginCancelBeginOutputRead [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestAsyncOutputStream_CancelOutputRead [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestCustomStandardInputEncoding [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestManyOutputLines [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestManyOutputLines_SynchronizingObject(invokeRequired: False) [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestManyOutputLines_SynchronizingObject(invokeRequired: True) [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestMismatchedStandardInputEncoding [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestSyncErrorStream [FAIL]
   2       System.Diagnostics.Tests.ProcessStreamReadTests.TestSyncOutputStream [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.Handle_CreateEvent_BlocksUntilProcessCompleted(useSafeHandle: False) [FAIL]
   1       System.Diagnostics.Tests.ProcessTests.Handle_CreateEvent_BlocksUntilProcessCompleted(useSafeHandle: True) [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_False_OnlyRootProcessTerminated [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_CalledOnTreeContainingCallingProcess_ThrowsInvalidOperationException [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_EntireTreeTerminated [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.Kill_ExitedNonChildProcess_DoesNotThrow(killTree: False) [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.Kill_ExitedNonChildProcess_DoesNotThrow(killTree: True) [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.ProcessStart_UseShellExecute_ExecuteOrder [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "a b c\"def", expectedArgv: "a,b,cdef") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "a\"b c\"d e\"f g\"h i\"j k\"l", expectedArgv: "ab cd,ef gh,ij kl") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "a\\\\b d\"e f\"g h", expectedArgv: "a\\\\b,de fg,h") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "a\\\\\\\"b c d", expectedArgv: "a\\\"b,c,d") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "a\\\\\\\\\"b c\" d e", expectedArgv: "a\\\\b c,d,e") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "b d \"\"a\"\" ", expectedArgv: "b,d,a") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "b d \\\"\\\"a\\\"\\\"", expectedArgv: "b,d,\"\"a\"\"") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "c\"\"\"\" b \"\"\\", expectedArgv: "c\",b,\\") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "\"abc\"      d e", expectedArgv: "abc,d,e") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "\"abc\" d e", expectedArgv: "abc,d,e") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "\"abc\"\t\td\te", expectedArgv: "abc,d,e") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "\"\" b \"\"", expectedArgv: ",b,") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "\"\"a\"\" b d", expectedArgv: "a,b,d") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "\"\"c \"\"b\"\" d\"\\", expectedArgv: "c,b,d\\") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "\"\"\"\" b c", expectedArgv: "\",b,c") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "\"\\a\\\" \\\\\"\\\\\\ b c", expectedArgv: "\\a\" \\\\\\\\,b,c") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "\\ \\\\ \\\\\\", expectedArgv: "\\,\\\\,\\\\\\") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestArgumentParsing(inputArguments: "\\\"\\\"a\\\"\\\" b d", expectedArgv: "\"\"a\"\",b,d") [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestBasePriorityOnUnix [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIds [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestExitCode [FAIL]
   1       System.Diagnostics.Tests.ProcessTests.TestId [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestLongProcessIsWorking [FAIL]
   1       System.Diagnostics.Tests.ProcessTests.TestPagedMemorySize64 [FAIL]
   1       System.Diagnostics.Tests.ProcessTests.TestPagedSystemMemorySize [FAIL]
   1       System.Diagnostics.Tests.ProcessTests.TestPeakWorkingSet [FAIL]
   1       System.Diagnostics.Tests.ProcessTests.TestPriorityClassUnix [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestProcessName [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestProcessorTime [FAIL]
   2       System.Diagnostics.Tests.ProcessTests.TestProcessStartTime [FAIL]
   1       System.Diagnostics.Tests.ProcessTests.TestSessionId [FAIL]
   1       System.Diagnostics.Tests.ProcessThreadTests.TestCommonPriorityAndTimeProperties [FAIL]
   1       System.Diagnostics.Tests.ProcessThreadTests.TestPriorityLevelProperty_Unix [FAIL]
   1       System.Diagnostics.Tests.ProcessThreadTests.TestThreadStateProperty [FAIL]
   2       System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_EnableRaisingEvents_CorrectExitCode(exitCode: 0) [FAIL]
   2       System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_EnableRaisingEvents_CorrectExitCode(exitCode: 1) [FAIL]
   2       System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_EnableRaisingEvents_CorrectExitCode(exitCode: 127) [FAIL]
   2       System.Diagnostics.Tests.ProcessWaitingTests.SingleProcess_TryWaitAsyncMultipleTimesBeforeCompleting [FAIL]
   3       System.Diagnostics.Tests.ProcessWaitingTests.WaitAsyncChain [FAIL]
   2       System.Diagnostics.Tests.ProcessWaitingTests.WaitAsyncForPeerProcess [FAIL]
   2       System.Diagnostics.Tests.ProcessWaitingTests.WaitAsyncForSignal [FAIL]
   2       System.Diagnostics.Tests.ProcessWaitingTests.WaitChain [FAIL]
   2       System.Diagnostics.Tests.ProcessWaitingTests.WaitForExitAsync_AfterProcessExit_ShouldConsumeOutputDataReceived [FAIL]
   2       System.Diagnostics.Tests.ProcessWaitingTests.WaitForExit_AfterProcessExit_ShouldConsumeOutputDataReceived [FAIL]
   2       System.Diagnostics.Tests.ProcessWaitingTests.WaitForPeerProcess [FAIL]
   2       System.Diagnostics.Tests.ProcessWaitingTests.WaitForSignal [FAIL]
   2       System.IO.MemoryMappedFiles.Tests.CrossProcessTests.DataShared [FAIL]
   3       System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.ClientClosesPipe_ServerReceivesEof [FAIL]
   3       System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.PingPong [FAIL]
   3       System.IO.Pipes.Tests.AnonymousPipeTest_CrossProcess.ServerClosesPipe_ClientReceivesEof [FAIL]
   2       System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_Uri_Parsing(_input: "1.1.1.5", _host: "1.1.1.5", _port: "80", _user: null, _password: null) [FAIL]
   2       System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_Uri_Parsing(_input: "domain%5Cfoo:bar@1.1.1.1", _host: "1.1.1.1", _port: "80", _user: "foo", _password: "bar") [FAIL]
   2       System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_Uri_Parsing(_input: "domain\\foo:bar@1.1.1.1", _host: "1.1.1.1", _port: "80", _user: "foo", _password: "bar") [FAIL]
   2       System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_Uri_Parsing(_input: "foo:bar@[::1]:3128", _host: "[::1]", _port: "3128", _user: "foo", _password: "bar") [FAIL]
   2       System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_Uri_Parsing(_input: "foo:Pass$!#\\.$@127.0.0.1:3128", _host: "127.0.0.1", _port: "3128", _user: "foo", _password: "Pass$!#\\.$") [FAIL]
   2       System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_Uri_Parsing(_input: "http://1.1.1.5:3005", _host: "1.1.1.5", _port: "3005", _user: null, _password: null) [FAIL]
   2       System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_Uri_Parsing(_input: "http://1.2.3.4:8888/foo", _host: "1.2.3.4", _port: "8888", _user: null, _password: null) [FAIL]
   2       System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_Uri_Parsing(_input: "http://10.30.62.64:7890/", _host: "10.30.62.64", _port: "7890", _user: null, _password: null) [FAIL]
   2       System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_Uri_Parsing(_input: "HTTP://ABC.COM/", _host: "abc.com", _port: "80", _user: null, _password: null) [FAIL]
   2       System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_Uri_Parsing(_input: "http://foo@1.1.1.5", _host: "1.1.1.5", _port: "80", _user: "foo", _password: "") [FAIL]
   2       System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_Uri_Parsing(_input: "http://[::1]:80", _host: "[::1]", _port: "80", _user: null, _password: null) [FAIL]
   2       System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_Uri_Parsing(_input: "[::1]", _host: "[::1]", _port: "80", _user: null, _password: null) [FAIL]
   1       System.Runtime.Serialization.Formatters.Tests.BinaryFormatterEventSourceTests.RecordsDeserialization [FAIL]
   1       System.Runtime.Serialization.Formatters.Tests.BinaryFormatterEventSourceTests.RecordsNestedSerializationCalls [FAIL]
   1       System.Runtime.Serialization.Formatters.Tests.BinaryFormatterEventSourceTests.RecordsSerialization [FAIL]
   1       System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.RoundtripManyObjectsInOneStream [FAIL]
   3       System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.Roundtrip_CrossProcess(obj: "test") [FAIL]
   3       System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.Roundtrip_CrossProcess(obj: Tree`1 { Left = Tree`1 { Left = Tree`1 { ... }, Right = Tree`1 { ... }, Value = 2 }, Right = Tree`1 { Left = null, Right = null, Value = 5 }, Value = 1 }) [FAIL]
   3       System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.Roundtrip_CrossProcess(obj: [1, 2, 3, 4, 5]) [FAIL]
   1       System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateDeserializationOfObjectWithDifferentAssemblyVersion [FAIL]
   1       System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateDeserializationOfObjectWithGenericTypeWhichGenericArgumentHasDifferentAssemblyVersion [FAIL]
   1       System.Runtime.Serialization.Formatters.Tests.FormatterServicesTests.GetSerializableMembers_Interface [FAIL]
   1       System.Runtime.Serialization.Formatters.Tests.FormatterTests.WriteMember_InvokesProperMethod [FAIL]
   1       System.Runtime.Serialization.Formatters.Tests.SerializationInfoTests.SerializationInfoAddGet [FAIL]
   1       System.Runtime.Serialization.Formatters.Tests.SerializationInfoTests.SerializationInfoEnumerate [FAIL]
   2       System.Runtime.Tests.ProfileOptimizationTest.ProfileOptimization_CheckFileExists(stopProfile: False) [FAIL]
   2       System.Runtime.Tests.ProfileOptimizationTest.ProfileOptimization_CheckFileExists(stopProfile: True) [FAIL]
   2       System.Tests.AppDomainTests.ProcessExit_Called [FAIL]
   2       System.Tests.AppDomainTests.TargetFrameworkTest [FAIL]
   2       System.Tests.EnvironmentTests.FailFast_ExceptionStackTrace_ArgumentException [FAIL]
   2       System.Tests.EnvironmentTests.FailFast_ExceptionStackTrace_InnerException [FAIL]
   2       System.Tests.EnvironmentTests.FailFast_ExceptionStackTrace_StackOverflowException [FAIL]
   2       System.Tests.EnvironmentTests.ProcessId_MatchesExpectedValue [FAIL]
   2       System.Tests.EnvironmentTests.ProcessPath_MatchesExpectedValue [FAIL]
   2       System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: -1) [FAIL]
   2       System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: -45) [FAIL]
   2       System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: 0) [FAIL]
   2       System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: 1) [FAIL]
   2       System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: 255) [FAIL]
   2       System.Tests.Environment_Exit.CheckExitCode(expectedExitCode: 42) [FAIL]
   2       System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue(mode: 1) [FAIL]
   2       System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue(mode: 2) [FAIL]
   2       System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue(mode: 3) [FAIL]
   2       System.Tests.GetCommandLineArgs.GetCommandLineArgs_Invoke_ReturnsExpected(args: ["Arg1", "Arg2"]) [FAIL]
   2       System.Tests.GetCommandLineArgs.GetCommandLineArgs_Invoke_ReturnsExpected(args: ["arg1", "\\\\\\\\\\\"alpha", "\\\"arg3"]) [FAIL]
   2       System.Tests.GetCommandLineArgs.GetCommandLineArgs_Invoke_ReturnsExpected(args: ["singleArg"]) [FAIL]
   2       System.Tests.GetCommandLineArgs.GetCommandLineArgs_Invoke_ReturnsExpected(args: ["\"Arg With Quotes\""]) [FAIL]
   2       System.Tests.GetCommandLineArgs.GetCommandLineArgs_Invoke_ReturnsExpected(args: ["\"Arg1 With Quotes\"", "Arg2", "\"Arg3 With Quotes\""]) [FAIL]
   2       System.Tests.GetCommandLineArgs.GetCommandLineArgs_Invoke_ReturnsExpected(args: ["\"Arg1 With Quotes\"", "\"Arg2 With Quotes\""]) [FAIL]
   4       System.Tests.NonStandardConfigurationTests.NonBlockingStdout_AllDataReceived [FAIL]
   2       System.Tests.UnloadingAndProcessExitTests.UnloadingEventMustHappenBeforeProcessExitEvent [FAIL]
   2       System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix: "") [FAIL]
   2       System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix: "Global\\") [FAIL]
   2       System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix: "Local\\") [FAIL]
   3       System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: "DefaultApartmentStateMain.exe", testName: "GetApartmentStateTest") [FAIL]
   3       System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: "DefaultApartmentStateMain.exe", testName: "SetApartmentStateTest") [FAIL]
   3       System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: "MTAMain.exe", testName: "GetApartmentStateTest") [FAIL]
   3       System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: "MTAMain.exe", testName: "SetApartmentStateTest") [FAIL]
   3       System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: "STAMain.exe", testName: "GetApartmentStateTest") [FAIL]
   3       System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: "STAMain.exe", testName: "SetApartmentStateTest") [FAIL]
   3       System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: "STAMain.exe", testName: "WaitAllNotSupportedOnSta_Test0") [FAIL]
   3       System.Threading.Threads.Tests.ThreadTests.ApartmentState_AttributePresent(appName: "STAMain.exe", testName: "WaitAllNotSupportedOnSta_Test1") [FAIL]
```

### PR DESCRIPTION
**Pull request by sdmaclea**
CI likely fixed by dotnet/core-eng#12776

Fixes #49568

### CODE REVIEW

**Comment by sdmaclea** [comment]
Manually triggered https://dev.azure.com/dnceng/public/_build/results?buildId=1119674&view=results

**Comment by sdmaclea** [comment]
First runs passed.  Fixed merge conflict.  Triggering runs again.

**Comment by ericstj** [comment]
@sdmaclea does this need a rerun or do you think these weren't fixed by  dotnet/core-eng#12776?

**Comment by sdmaclea** [comment]
These weren't fixed by dotnet/core-eng#12776.  

Unfortunately most of these issues do not reproduce (easily?) locally anymore.  

The original runs didn't generate core dumps.  The coredumps have since been fixed.  I planned to rebase and rerun these to see if we could get some more info.

/cc @janvorli @mangod9 @sandreenko

**Comment by sdmaclea** [comment]
Rebased and manually ran https://dev.azure.com/dnceng/public/_build/results?buildId=1176752&view=results

**Comment by sdmaclea** [comment]
This needs a review,  The Apple Silicon tests all passed.

@safern PTAL

**Review by mangod9 — APPROVED** [review]

**Pull request merged**
