### PR TITLE
Revert "Remove uses of DECODE_RETURN_KIND part of GCInfo"

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Reverts dotnet/runtime#110799

Just for testing. ARM32 native AOT outerloop got broken and it's between this and two RyuJIT changes. I suspect this.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
ARM32 still broken here.

**Comment by jkotas** [comment]
@MichalStrehovsky Have you figured out where the Arm32 regression came from?

I think it was introduced by #110732. There is mismatch in the asm thunk layout that makes us jump to address 0. cc @lateralusX

**Comment by jkotas** [comment]
Submitted https://github.com/dotnet/runtime/pull/110983 to validate

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky Have you figured out where the Arm32 regression came from?

I've been taking public holidays and time off work - investigating weird new ARM32-only issues is not compatible with that :).

> Submitted #110983 to validate

I haven't even suspected that one because https://dev.azure.com/dnceng-public/public/_build/results?buildId=899516&view=results already had ARM32 broken and that was presumably before the thunk layout commit. However, your revert of this is the first ARM32 run that is green in two weeks, so I'll just take it as "AzDO works in mysterious ways".

**Pull request closed without merging**
