### PR TITLE
[LoongArch64] Fix some issues related to the clrstack command in dotnet-sos for LA64

### PR DESCRIPTION
**Pull request by lawn123**
This patch improves the clrstack command in dotnet sos. There are certain issues when using the command clrstack - i a or clrstack - p. @shushanhf

### CODE REVIEW

**Comment by am11** [comment]
cc @viewizard, seems like riscv64 needs a similar mapping in coreclr/vm.

**Review by shushanhf — APPROVED** [review]
LGTM,
Thanks!

**Comment by viewizard** [comment]
@am11  thanks, will take a look. BTW, I have tested clrstack SOS command on RISCV64 and don't found any issues with current runtime code, @lawn123 could you please share how you tested clrstack command (what options you are used?), I am interested how we could also check this code for RISCV64.
CC @gbalykov

**Comment by lawn123** [comment]
@viewizard  The test cases are as follows:
```1 using System;
  2 using System.Threading;
  3 public class Program
  4 {
  5     static void MyMethod(string fname)
  6     {
  7       Console.WriteLine(fname + " Refsnes");
  8 
  9       Thread thread = new Thread(MyThreadMethod);
 10       thread.Start();
 11 
 12      
 13      Thread.Sleep(2000);
 14      Console.WriteLine("Main thread resumed.");
 15     }
 16 
 17     static void Main(string[] args)
 18     {
 19       MyMethod("Liam");
 20     }
 21 
 22      static void MyThreadMethod()
 23     {
 24         Console.WriteLine("Thread started.");
 25         Thread.Sleep(1000);
 26         Console.WriteLine("Thread paused.");
 27     }
 28 }
```
When executing the clrstack - p command to display parameters, 'unable to retrieve data' will appear：

```
SOS_HOSTING: Failed to find runtime directory
Unrecognized command 'setsymbolserver' because managed hosting failed or was disabled. See sethostruntime command for details.
(lldb) target create "./artifacts/tests/coreclr/linux.loongarch64.Debug/Tests/Core_Root/corerun"
Current executable set to '/home/liuan/project/dotnet-runtime-loongarch/artifacts/tests/coreclr/linux.loongarch64.Debug/Tests/Core_Root/corerun' (loongarch64).
(lldb) settings set -- target.run-args  "../HelloWorld/bin/Debug/net8.0/HelloWorld.dll"
(lldb)  bpmd HelloWorld.dll Program.MyThreadMethod
(lldb) r
Process 7976 launched: '/home/liuan/project/dotnet-runtime-loongarch/artifacts/tests/coreclr/linux.loongarch64.Debug/Tests/Core_Root/corerun' (loongarch64)
1 location added to breakpoint 1
Liam Refsnes
JITTED HelloWorld!Test.Program.MyThreadMethod()
Setting breakpoint: breakpoint set --address 0x000000FF780F5448 [Test.Program.MyThreadMethod()]
Process 7976 stopped
* thread #10, name = 'corerun', stop reason = breakpoint 3.1
    frame #0: 0x000000ff780f5448
->  0xff780f5448: addi.d $sp, $sp, -0x10
    0xff780f544c: st.d   $r22, $sp, 0x0
    0xff780f5450: st.d   $ra, $sp, 0x8
    0xff780f5454: ori    $r22, $sp, 0x0
(lldb) clrstack -p
OS Thread Id: 0x1f43 (10)
        Child SP               IP Call Site
000000BED34CA200 000000FF780F5448 Test.Program.MyThreadMethod()

000000BED34CA200 000000FF780F5290 System.Threading.Thread+StartHelper.RunWorker()
    PARAMETERS:
        this (0x0000002080000EF8) = <unable to retrieve data>

000000BED34CA240 000000FF780F4F28 System.Threading.Thread+StartHelper.Run()
    PARAMETERS:
        this (0x0000002080000EF8) = <unable to retrieve data>

000000BED34CA280 000000FF780F4DB4 System.Threading.Thread.StartCallback()
    PARAMETERS:
        this (0x0000002080000EF8) = <unable to retrieve data>

000000BED34CA778 000000fff761d918 [DebuggerU2MCatchHandlerFrame: 000000bed34ca778]
```

**Review by jkotas — APPROVED** [review]

**Comment by viewizard** [comment]
@lawn123 thanks! I see you already have lldb for LoongArch64, we still don't have lldb for riscv64 (work in progress as I know and some distros have it already) that usually mean we can't test some SOS commands (like managed breakpoints) and I play around crashdumps with dotnet-dump tool for all test cases. -_-

**Comment by am11** [comment]
@viewizard, alpine edge, ubuntu 22.10 and debian sid has lldb 18 now.

**Comment by am11** [comment]
@viewizard, alpine edge, ubuntu 22.10 and debian sid have lldb 18 now.

**Pull request merged**
