### PR TITLE
Add tests exposing issue #60035

### PR DESCRIPTION
**Pull request by echesakov**
@davidwrighton This is a prototype of the test as we discussed today.

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@tannergooding Do you want such test assembly to be crossgen-d before running?

**Comment by tannergooding** [comment]
> Basically, you want in addition to COMPlus_EnableHWIntrinsic=0 also test disabling individual ISAs with COMPlus_Enable{ISA}=0 under crossgen, right

Right. These `COMPlus_Enable*` switches are effectively "public surface area" and we tell customers they can use them for testing scenarios. So I think it makes sense that we should test and validate they are working (and continue working) as we intended them.

**Comment by echesakovMSFT** [comment]
Hmm, it doesn't look that these are working as expected.

If I disable SSE2 I have discrepancy between what a ReadyToRun image assumes and what `*.IsSupported` returns.

```
D:\echesako\src\runtime>set COMPlus
COMPlus_EnableSSE2=0

D:\echesako\src\runtime>%CORE_ROOT%\corerun.exe artifacts\tests\coreclr\windows.x64.checked\readytorun\Runtime_60035\Runtime_60035\Runtime_60035.dll
System.Runtime.Intrinsics.X86.Sse2.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Sse2.X64.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Sse3.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Ssse3.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Sse41.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Sse41.X64.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Sse42.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Sse42.X64.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Popcnt.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Popcnt.X64.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
```

Similarly, for SSE4.1
```
D:\echesako\src\runtime>set COMPlus
COMPlus_EnableSSE41=0

D:\echesako\src\runtime>%CORE_ROOT%\corerun.exe artifacts\tests\coreclr\windows.x64.checked\readytorun\Runtime_60035\Runtime_60035\Runtime_60035.dll
System.Runtime.Intrinsics.X86.Sse41.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Sse41.X64.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Sse42.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Sse42.X64.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Popcnt.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
System.Runtime.Intrinsics.X86.Popcnt.X64.IsSupported returns 'False' while a loaded into the process ReadyToRun image assumes the value being 'True'
```

It does work for optional ISAs though. Say, for AVX
```
D:\echesako\src\runtime>set COMPlus_EnableAVX=0

D:\echesako\src\runtime>%CORE_ROOT%\corerun.exe artifacts\tests\coreclr\windows.x64.checked\readytorun\Runtime_60035\Runtime_60035\Runtime_60035.dll

D:\echesako\src\runtime>echo %errorlevel%
100

D:\echesako\src\runtime>set COMPlus_EnableAVX=1

D:\echesako\src\runtime>%CORE_ROOT%\corerun.exe artifacts\tests\coreclr\windows.x64.checked\readytorun\Runtime_60035\Runtime_60035\Runtime_60035.dll

D:\echesako\src\runtime>echo %errorlevel%
100
``` 

cc @jkotas

**Comment by jkotas** [comment]
> Hmm, it doesn't look that these are working as expected.

The behavior that you are seeing is what I would expect given how it is implemented currently. R2R code does not pay attention to ISA env variables, and so it always returns the actual configuration on the machine.  

I think we need to move the reading of the ISA env variables to VM to fix this discrepancy as I have said in https://github.com/dotnet/runtime/issues/60035#issuecomment-937439703

>  optional ISAs though. Say, for AVX

Nit: In crossgen terminology, these are called `unsupportedInstructionSet`. If a method depends on `unsupportedInstructionSet` ISA, crossgen does not compile it and it always fallbacks to JIT at runtime.

**Comment by echesakovMSFT** [comment]
> Nit: In crossgen terminology, these are called unsupportedInstructionSet. If a method depends on unsupportedInstructionSet ISA, crossgen does not compile it and it always fallbacks to JIT at runtime.

Got it, thanks for explanation!

**Comment by echesakovMSFT** [comment]
One more question for my education while we are discussing the current behavior. 

Should I expect that under `TieredCompilation=0` different behavior of running these tests?

```
D:\echesako\src\runtime>set COMPlus
COMPlus_EnableSSE41=0
COMPlus_TieredCompilation=0

D:\echesako\src\runtime>%CORE_ROOT%\corerun.exe artifacts\tests\coreclr\windows.x64.checked\readytorun\Runtime_60035\Runtime_60035\Runtime_60035.dll

D:\echesako\src\runtime>echo %errorlevel%
100
```

**Comment by echesakovMSFT** [comment]
I will work on re-writing in C# (as Jan requsted) and minimizing (as David requested) later when I have bandwidth.

**Pull request closed without merging**
