### PR TITLE
Fixed a bug in websocket receive, when a compressed frame with no payload is received.

### LINKED ISSUE #52551: WebSocket compression issues when testing server-side with Autobahn
When trying to add WebSockets compression support to ASP.NET Core I ran the Autobahn test suite against the server and hit multiple test cases failing.

I'm going to focus on a single one in this issue because it's already complicated enough (and hopefully same root issue).

This specific issue is looking at test 12.4.11 which states: "Send 1000 compressed messages each of payload size 8192, auto-fragment to 256 octets. Use default permessage-deflate offer." I modified the client window bits to be 12 (was testing various window bits and hitting issues on different tests with different window bits)

I manually looped over all the messages until I found one that wasn't 8192 in size and have isolated that individual message for the repro below.

Single message test bytes from client
[compressed8192fromClient12bit.txt](https://github.com/dotnet/runtime/files/6454163/compressed8192fromClient12bit.txt)

```c#
[Fact]
public async Task CompressTest()
{
    WebSocketTestStream stream = new();
    using WebSocket server = WebSocket.CreateFromStream(stream, new WebSocketCreationOptions
    {
        IsServer = true,
        KeepAliveInterval = TimeSpan.Zero,
        DangerousDeflateOptions = new()
        {
            ClientMaxWindowBits = 12,
            ServerMaxWindowBits = 15,
            ClientContextTakeover = false,
        }
    });
    using WebSocket client = WebSocket.CreateFromStream(stream.Remote, new WebSocketCreationOptions
    {
        KeepAliveInterval = TimeSpan.Zero,
        DangerousDeflateOptions = new()
        {
            ClientMaxWindowBits = 12,
            ServerMaxWindowBits = 15,
            ClientContextTakeover = false,
        }
    });

    using var fileStream = File.OpenRead("<path to>/compressed8192fromClient12bit.txt");
    int r = 1;
    var fileBuf = new byte[2000];
    while (r != 0)
    {
        r = await fileStream.ReadAsync(fileBuf);
        await stream.Remote.WriteAsync(fileBuf.AsMemory(0, r), default);
    }

    var buf = new byte[8192];
    int total = 0;
    while (true)
    {
        var res = await server.ReceiveAsync(buf, default);
        total += res.Count;
        if (res.EndOfMessage == true)
        {
            Assert.Equal(8192, total);
            break;
        }
    }
}
```

Some more information about this specific message:
Inflated sections (bytes): 320, 3226, 822, 1736, 2115 - total = 8219
WebSocket frame lengths: 256, 256, 256, 256, 243

cc @zlatanov in case you're interested

### PR DESCRIPTION
**Pull request by zlatanov**
There are extremely rare cases where it is possible to receive an empty frame, part of compressed a message.

If such a frame happened to be the last frame of the message, and there was leftover data available in the inflater, the receive
operation would ignore the data and think that there is nothing and return 0 bytes received to the user.

https://github.com/dotnet/runtime/blob/b306268b614145908061b14dd24d860dcf3bd6b9/src/libraries/System.Net.WebSockets/src/System/Net/WebSockets/ManagedWebSocket.cs#L1249

https://github.com/dotnet/runtime/blob/b306268b614145908061b14dd24d860dcf3bd6b9/src/libraries/System.Net.WebSockets/src/System/Net/WebSockets/ManagedWebSocket.cs#L810-L817

One other condition for this case is that the receive buffer is small enough, so the inflate cannot flush everything to the user. This was caught by @BrennanConroy running Autobahn Testsuite with receive buffer size of **4096**. The Testsuite sends such frames occasionally to make sure the implementation handles them correctly.

Our internal implementation however cannot produce such frame. When sending an empty compressed frame, the resulting payload will always be 1 byte - a zero.

The fix for this is to treat empty compressed frames as not processed, until inflation has been run.

@BrennanConroy could you try and run your test server with this branch, please?

Fixes #52551 

//cc @CarnaViire

### CODE REVIEW

**Comment by zlatanov** [comment]
> Can we produce a raw byte stream that simulates a WebSocket with such a frame?

I see no reason why not. I will give it a go in a moment.

**Comment by zlatanov** [comment]
Thanks for the suggestion @halter73! Created a test and verified that with the implementation before the fix, the test fails.

**Comment by BrennanConroy** [comment]
All 12.* and 13.* autobahn tests pass now!

**Review by halter73 — APPROVED** [review]

**Review by CarnaViire — APPROVED** [review]

**Pull request merged**
