### PR TITLE
Tweak Regex compiled code and add more tests

### PR DESCRIPTION
**Pull request by stephentoub**
- Uses the Regex pattern as part of the DynamicMethod name, so that when looking at a profile, instead of seeing lots of methods like "FindFirstChar12", you instead see names like "Regex12_FindFirstChar_abc|def[ghi]*".   This is purely to help with profiling an app that uses multiple regexes.
- Tweaks the generated code in CompileToAssembly to use the right visibility on overrides.  Otherwise trying to compile the generated C# fails.
- Add a bunch of tests based on the AT&T regex test suite.

cc: @danmosemsft, @eerhardt, @ViktorHofer 

@davidwrighton, is there any problem with the arbitrary regex string in a DynamicMethod name?  In theory it could contain any character.  I looked at the CLI spec and didn't see any issues, and we have tests that use every character, and they all succeeded as well.  Just want to make sure.

### CODE REVIEW

**Comment by danmosemsft** [comment]
> @davidwrighton, is there any problem with the arbitrary regex string in a DynamicMethod name? In theory it could contain any character. I looked at the CLI spec and didn't see any issues, and we have tests that use every character, and they all succeeded as well. Just want to make sure.

It's not just the CLI/CLR but also tooling like VS - could that perhaps have an issue? I guess we will find out.

**Review by danmoseley — APPROVED** [review]

**Comment by danmosemsft** [comment]
Thinking a little more, I guess any problem with special regex chars is likely well covered by the unit tests. Any issue of display etc would likely relate to multibyte characters  - what about clamping the character set to ASCII?  Many regexes would use `\uxxxx` syntax for those anyway.

**Comment by stephentoub** [comment]
> what about clamping the character set to ASCII?

We could, it just adds expense.

**Comment by davidwrighton** [comment]
Dynamic method names are not exposed in very many places at all, so I believe that arbitrary strings actually do work. However, I do have some small concern. Most tools that work with method names such as profilers have some issues with very long names. I would suggest putting some sort of cap on the name length.

**Comment by stephentoub** [comment]
Thanks, @davidwrighton. I have a limit of 50 on the pattern:
https://github.com/dotnet/runtime/pull/31730/files#diff-d2c7ddaaa4b196c91a3d72219d9e8ecfR37
Is that sufficient?

**Comment by davidwrighton** [comment]
@stephentoub Lol, I missed that in the diff. Yes, 50 is fine. I'd been thinking 100.

**Comment by danmosemsft** [comment]
> We could, it just adds expense. I'd prefer to only do that if there's an issue, in which case we can absolutely do that.

Sounds fine to me. I love built-in diagnosability.

**Comment by stephentoub** [comment]
I'm going to temporarily remove that commit.

**Pull request merged**
