### PR TITLE
Suppress the special VSD callsite nop marker for NAOT x86 ABI

### PR DESCRIPTION
**Pull request by jkotas**
This is not needed for NAOT

### CODE REVIEW

**Comment by filipnavara** [comment]
This won't work on it's own. We still need the hidden argument passed in the register here:
```diff
--- a/src/coreclr/jit/morph.cpp
+++ b/src/coreclr/jit/morph.cpp
@@ -2055,7 +2055,7 @@ void CallArgs::AddFinalArgsAndDetermineABIInfo(Compiler* comp, GenTreeCall* call
     // If/when we change that, the following code needs to be changed to correctly support the (TBD) managed calling
     // convention for x86/SSE.
 
-    addStubCellArg = call->gtCallType != CT_INDIRECT && comp->IsTargetAbi(CORINFO_NATIVEAOT_ABI);
+    addStubCellArg = comp->IsTargetAbi(CORINFO_NATIVEAOT_ABI);
 #endif
 
     // We are allowed to have a ret buffer argument combined
```

Note that this is basically the diff posted in https://github.com/dotnet/runtime/issues/99516#issuecomment-1989140028.

**Comment by jkotas** [comment]
Yeah, I epxected that that there are more places that need to be adjusted.

> in https://github.com/dotnet/runtime/issues/99516#issuecomment-1989140028 and there's few more places that need the same adjustment.

Could you please submit a PR with this diff (except the part that enables CFG tests) since you have figured the rigth places where this needs to be fixed?

**Comment by filipnavara** [comment]
> Could you please submit a PR with this diff (except the part that enables CFG tests) since you have figured the rigth places where this needs to be fixed?

Sure, submitted.

**Pull request closed without merging**
