### PR TITLE
[release/6.0][Android] Fix SslStream on legacy Android API levels

### PR DESCRIPTION
**Pull request by simonrozsival**
Backport of dotnet/runtime#78849 and dotnet/runtime#78918 to release/6.0

/cc @steveisok 
Supersedes dotnet/runtime#79039

## Customer Impact
These fixes address issues reported by our customers (#78715, dotnet/runtime#78716) when using `SocketsHttpHandler`
.NET declares support for Android API versions 21+ and these changes fix the SslStream class on API 21-26.

## Testing
- CI tests (API 29)
- local testing on Android emulators (API 21, 24, 26, 33) and device (API 31)

## Risk
Low.

### CODE REVIEW

**Comment by carlossanlop** [comment]
@simonrozsival can you please get a code review sign-off? Also, can you please investigate the CI results and determine if they are related or not?

**Comment by simonrozsival** [comment]
CI test failures are unrelated to this PR.

**Review by steveisok — APPROVED** [review]

**Comment by carlossanlop** [comment]
Approved by Tactics (6.0.14).
Signed off by area owner.
No OOB changes needed (Android).
CI failures are unrelated: https://github.com/dotnet/runtime/issues/51097#issuecomment-1375989940 and https://github.com/dotnet/runtime/issues/80252
Ready to merge. :shipit:

**Pull request merged**
