### PR TITLE
System.Numerics readonly annotation

### PR DESCRIPTION
**Pull request by hrrrrustic**
This PR is a part of #46675

### CODE REVIEW

**Comment by tannergooding** [comment]
The changes to `Complex` LGTM. I'm comfortable with us saying that the properties, `Equals`, and `ToString` methods will never mutate. It's probably even worth refactoring `Complex.Sqrt` so it can be a `readonly struct`.

`BitIntegerCalculator.BitsBuffer` on the other hand is an internal type and so I'm not sure if its worth actually updating it to be `readonly`.

**Comment by hrrrrustic** [comment]
@tannergooding Update ```Complex``` (fix Sqrt method and mark whole struct)
Should I revert ```BitIntegerCalculator.BitsBuffer``` now or we are waiting somebody else's opinion?

**Comment by jkotas** [comment]
> Should I revert BitIntegerCalculator.BitsBuffer now 

Yes, I think so.

In general, it is not very valuable to use readonly on types that are designed to be mutable, such as BitsBuffer.

**Comment by hrrrrustic** [comment]
@jkotas Done
Some unrelated errors in CI

**Comment by jeffhandley** [comment]
This PR is being marked as a draft per https://github.com/dotnet/runtime/pull/46675#issuecomment-828694665.

**Review by jkotas — APPROVED** [review]
@tannergooding I think this one is good and we can merge it. Do you agree?

**Comment by tannergooding** [comment]
> I think this one is good and we can merge it. Do you agree?

Yes, just need to do a final review pass over the Sqrt refactoring

**Comment by tannergooding** [comment]
> This PR is being marked as a draft per #46675 (comment).

This is one we are wanting to take. `Complex` is a small numeric struct type where the entire struct should have been `readonly`.

Like many small numeric types, it is conceptually its own primitive and mutating one of its two instance fields isn't really desirable.

**Review by tannergooding — APPROVED** [review]

**Comment by tannergooding** [comment]
I've requeued the failing job and set auto-merge.

**Pull request merged**
