### PR TITLE
Guarantee that initReg won't be a callee-saved register

### PR DESCRIPTION
**Pull request by sirntar**
This PR is the result of a discussion in #99156

Tests fixed by this PR:
- `JIT/jit64/hfa/main/testC/hfa_nd2C_d`
- `JIT/jit64/hfa/main/testC/hfa_sd2C_d`

Part of #84834
cc @dotnet/samsung

### CODE REVIEW

**Comment by sirntar** [comment]
On `ARM64` and `RISC-V64` in method `genPushCalleeSavedRegisters`, we had to use `initReg` before callee-saved registers were saved. This could technically have caused a problem, because with the current implementation (in the upstream) `initReg` can be assigned as one of the callee-saved registers.
So far on `ARM64`, this problem has been solved by using  `REG_SCRATCH` before saving callee-saved registers, but there is no need to do so, since we can guarantee that `initReg` will always be a safe register to use. We just need to replace `RBM_ALLINT` with `RBM_INT_CALLEE_TRASH`, so that we will only use non callee-saved registers as `initReg`.

<details>
<summary>RBM_ALLINT definitions</summary>

```bash
./src/coreclr/jit/targetarm.h
70:  #define RBM_ALLINT              (RBM_INT_CALLEE_SAVED | RBM_INT_CALLEE_TRASH)

./src/coreclr/jit/targetx86.h
142:  #define RBM_ALLINT              (RBM_INT_CALLEE_SAVED | RBM_INT_CALLEE_TRASH)

./src/coreclr/jit/targetloongarch64.h
81:  #define RBM_ALLINT              (RBM_INT_CALLEE_SAVED | RBM_INT_CALLEE_TRASH)

./src/coreclr/jit/targetriscv64.h
77:  #define RBM_ALLINT              (RBM_INT_CALLEE_SAVED | RBM_INT_CALLEE_TRASH)

./src/coreclr/jit/targetarm64.h
82:  #define RBM_ALLINT              (RBM_INT_CALLEE_SAVED | RBM_INT_CALLEE_TRASH)

./src/coreclr/jit/targetamd64.h
175:  #define RBM_ALLINT              (RBM_INT_CALLEE_SAVED | RBM_INT_CALLEE_TRASH)
```
</details>
<details>
<summary>REG_SCRATCH definitions</summary>

```bash
./src/coreclr/jit/targetriscv64.h
116:  #define REG_SCRATCH              REG_T0
119:  #define REG_SCRATCH_FLT          REG_F28

./src/coreclr/jit/targetloongarch64.h
120:  #define REG_SCRATCH              REG_T0
123:  #define REG_SCRATCH_FLT          REG_F11

./src/coreclr/jit/targetx86.h
179:  #define REG_SCRATCH              REG_EAX

./src/coreclr/jit/targetarm.h
120:  #define REG_SCRATCH              REG_LR

./src/coreclr/jit/targetamd64.h
341:  #define REG_SCRATCH              REG_EAX

./src/coreclr/jit/targetarm64.h
130:  #define REG_SCRATCH              REG_R9
```
</details>
<details>
<summary>RBM_INT_CALLEE_TRASH definitions</summary>

```bash
./src/coreclr/jit/targetamd64.h
133:  #define RBM_INT_CALLEE_TRASH    (RBM_EAX|RBM_RDI|RBM_RSI|RBM_EDX|RBM_ECX|RBM_R8|RBM_R9|RBM_R10|RBM_R11)
151:  #define RBM_INT_CALLEE_TRASH    (RBM_EAX|RBM_ECX|RBM_EDX|RBM_R8|RBM_R9|RBM_R10|RBM_R11)

./src/coreclr/jit/targetriscv64.h
67:  #define RBM_INT_CALLEE_TRASH    (RBM_A0|RBM_A1|RBM_A2|RBM_A3|RBM_A4|RBM_A5|RBM_A6|RBM_A7|RBM_T0|RBM_T1|RBM_T2|RBM_T3|RBM_T4|RBM_T5|RBM_T6)

./src/coreclr/jit/targetx86.h
137:  #define RBM_INT_CALLEE_TRASH    (RBM_EAX|RBM_ECX|RBM_EDX)

./src/coreclr/jit/targetloongarch64.h
71:  #define RBM_INT_CALLEE_TRASH    (RBM_A0|RBM_A1|RBM_A2|RBM_A3|RBM_A4|RBM_A5|RBM_A6|RBM_A7|RBM_T0|RBM_T1|RBM_T2|RBM_T3|RBM_T4|RBM_T5|RBM_T6|RBM_T7|RBM_T8)

./src/coreclr/jit/targetarm.h
60:  #define RBM_INT_CALLEE_TRASH    (RBM_R0|RBM_R1|RBM_R2|RBM_R3|RBM_R12|RBM_LR)

./src/coreclr/jit/targetarm64.h
72:  #define RBM_INT_CALLEE_TRASH    (RBM_R0|RBM_R1|RBM_R2|RBM_R3|RBM_R4|RBM_R5|RBM_R6|RBM_R7|RBM_R8|RBM_R9|RBM_R10|RBM_R11|RBM_R12|RBM_R13|RBM_R14|RBM_R15|RBM_IP0|RBM_IP1|RBM_LR)
```
</details>

**Comment by jakobbotsch** [comment]
There are CQ regressions on x64: https://dev.azure.com/dnceng-public/public/_build/results?buildId=589775&view=ms.vss-build-web.run-extensions-tab
Seems the registers picked here require larger encodings.

**Comment by sirntar** [comment]
> There are CQ regressions on x64 and on arm32: https://dev.azure.com/dnceng-public/public/_build/results?buildId=589775&view=ms.vss-build-web.run-extensions-tab Seems the registers picked here require larger encodings.

I'm checking that right now, thanks for notice.

**Comment by jakobbotsch** [comment]
At this point it is just replacing one well-commented ifdef with another non-commented one. I think RISCV-64 should just duplicate the logic that ARM64 has instead of this change.

**Pull request closed without merging**
