### PR TITLE
Remove ICustomMarshaler from linker descriptor linker can keep the type

### PR DESCRIPTION
**Pull request by marek-safar**
conditionally

### CODE REVIEW

**Comment by vargaz** [comment]
How does the linker keep these types/methods alive. If they are not present, the runtime might assert.

**Comment by marek-safar** [comment]
The runtime should not [assert](https://github.com/dotnet/runtime/blob/56f5a0d2d1e595b2056f0ba2a61809ca9a8f1d5b/src/mono/mono/metadata/marshal-ilgen.c#L78) if the type is not needed. If it's needed then the type has to be passed via MarshalAsAttribute.MarshalType which linker detects.

**Comment by vargaz** [comment]
Marshal.GetCustomMarshalerInstance () is called by the runtime only.
The ICustomMarshaller methods are also called by the runtime only.

**Comment by vargaz** [comment]
If we want the linker to keep these alive, it needs special processing in the linker if 
MarshalAs(UnmanagedType.CustomMarshaler) is present in the app.

**Comment by marek-safar** [comment]
> If we want the linker to keep these alive, it needs special processing in the linker if
MarshalAs(UnmanagedType.CustomMarshaler)

yes, and that's what the linker [does](https://github.com/mono/linker/blob/master/src/linker/Linker.Steps/MarkStep.cs#L589)

**Review by vargaz — APPROVED** [review]

**Comment by vargaz** [comment]
Probably needs a linker bump.

**Pull request merged**
