### PR TITLE
Fix issues with verify_regions, clear_batch_mark_array_bits.

### PR DESCRIPTION
**Pull request by PeterSolMS**
Details:
- we cannot verify the tail of the region list from background GC, as it may be updated by threads allocating.
- fix case in clear_batch_mark_array_bits where end is equal to the very end of a segment and we write into uncommitted memory in the mark_array.

### CODE REVIEW

**Review by mangod9 — APPROVED** [review]

**Comment by Maoni0** [comment]
I'm confused about the change in `clear_batch_mark_array_bits`, if the end address is already at the end of the region, it means the only way you could hit `if (startwrd == endwrd)` is when start is the same as end (since the end of a region would be 4mb aligned which means it would start on a new mark array word). are you seeing that we are calling this method with the same start and end address that's at the end of a region? we shouldn't actually do anything in that case.

**Comment by PeterSolMS** [comment]
I believe that the method was called with the both start and end address at the very end of a region, but I arrived at that conclusion via some backwards reasoning.

In the debugger, I could see that we AV inside the if-statement `if (startwrd == endwrd)` when we do `mark_array[startwrd] &= wrd`. I could also see that `wrd `was 0xffffffff, and that `firstwrd` was 0. This would imply that both `startbit` and `endbit` were 0, and together with the value of `startwrd`, I could see that we were at the end of a region. Because the computation of the bit numbers always rounds down, both start and end address must have been at the end of the region.

And I agree, we shouldn't do anything in that case, and that's what my proposed fix accomplishes. 

The question is just whether there's a better way to detect the case, and where we should put the test. I noticed that if `startwrd != endwrd`, we already check if the `endbit` is 0, so I decided to put an additional check only when `startwrd == endwrd`. It's enough to test `endbit` in this case, because if it's 0, then `startbit` must be 0 as well.

I also thought about whether we should test for the addresses being equal earlier, but that seems a loss perf-wise (it's likely a rare case), and functionally equivalent.

**Comment by Maoni0** [comment]
thanks @PeterSolMS. if we want to allow this method to handle being called when `start` and `end` are the same, I would think that means we want to check `if (startbit == endbit)` instead of checking if none of the bits are set in that word? you are getting the AV because the address happened to be at the end of a region and the mark array for that address was not committed. but you could imagine this doesn't need to be at the end of the region and we still wouldn't want to do anything if the 2 addresses are the same. we could also some more assert when the 2 bits are the same (which means `start` and `end` must be the same since 1 bit can't cover more than 1 object) -

```cplusplus
if (startbit != endbit)
{
    unsigned int wrd = firstwrd | lastwrd;
    mark_array[startwrd] &= wrd;
    return;
}
else
{
    assert (start == end);
}
```

**Comment by PeterSolMS** [comment]
I think your solution is fine too, except of course you want to move the return statement outside the if-statement, When `startbit == endbit`, you certainly want to return as well.

If `startbit == endbit`, `wrd` becomes 0xffffffff, so the `&=` becomes a no-op anyway, except at the end of a segment when the word may not be committed.

I worried that the `if (startbit != endbit)` would negatively impact register allocation because one more register is live, but that doesn't seem to be the case. Also, comparing two registers is just as fast as comparing one register to 0.

So, I'll be happy to adopt your solution.

**Review by Maoni0 — APPROVED** [review]
LGTM!

**Pull request merged**
