### PR TITLE
JIT: fix STRESS_BB_PROFILE issue

### LINKED ISSUE #101901: Test failure GC\\API\\GCHandle\\AddrOfPinnedObject_neg\\AddrOfPinnedObject_neg.cmd
**Failed in:** [runtime-coreclr jitstress-random 20240505.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=666195&view=ms.vss-test-web.build-test-results-tab&runId=16524308&resultId=100140&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked jitstress_random_2 @ Windows.11.Arm64.Open
    - GC\\API\\GCHandle\\AddrOfPinnedObject_neg\\AddrOfPinnedObject_neg.cmd
```

**Error message:**
```
 
Assert failure(PID 7540 [0x00001d74], Thread: 5096 [0x13e8]): Assertion failed 'firstILBlock->hasProfileWeight()' in 'Test_AddrOfPinnedObject_neg:Main():int' during 'Compute block weights' (IL size 192; hash 0x4ec04431; Tier0-MinOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\fgprofile.cpp:4544
    Image: C:\h\w\A3C608B7\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\A3C608B7\w\A7BA08D7\uploads\Reports\GC.API\GCHandle\AddrOfPinnedObject_neg\AddrOfPinnedObject_neg.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A3C608B7\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  AddrOfPinnedObject_neg.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 5/5/2024 7:49:19 PM
Processing C:\cores\corerun.exe.7540.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A3C608B7\p
> C:\h\w\A3C608B7\w\A7BA08D7\e\GC\API\GCHandle\AddrOfPinnedObject_neg\AddrOfPinnedObject_neg.cmd
```

**Stack trace:**
```
   at GC_API._GCHandle_AddrOfPinnedObject_neg_AddrOfPinnedObject_neg_._GCHandle_AddrOfPinnedObject_neg_AddrOfPinnedObject_neg_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Incorporate "stress" profile counts even if we're not optimizing.

Fixes #101901.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
I had this fix in #101739 but it got messed up by a bad merge at #101834.

@EgorBo PTAL
cc @dotnet/jit-contrib

**Review by EgorBo — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Still more issues to sort out
```
Assert failure(PID 4748 [0x0000128c], Thread: 2868 [0x0b34]): Assertion failed '!"Inconsistent profile data"' in 'Chaos.A0:RecurseA0(int):this' during 'Morph - Inlining' (IL size 31; hash 0x7595e44c; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\fgprofile.cpp:4922
    Image: C:\h\w\A29B08A1\p\corerun.exe
```

**Comment by AndyAyersMS** [comment]
Need to make sure to scale inlinee counts only after we apply synthesis, otherwise the scale factor may be off.

**Comment by AndyAyersMS** [comment]
Issues are known. This is a stress mode only fix, so no [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=667316&view=ms.vss-build-web.run-extensions-tab), as expected.

**Pull request merged**
