### PR TITLE
Using GC.AllocateUninitializedArray for ToArray.

### PR DESCRIPTION
**Pull request by cincuranet**

### CODE REVIEW

**Comment by cincuranet** [comment]
Similar approach might be worth for other places as well - i.e. `List(IEnumerable<T> collection)` ctor. If so, I'm happy to do it.

**Comment by am11** [comment]
Similar to why `Array.Empty<T>()` isn't used here: https://github.com/dotnet/runtime/blob/84db7e14160cff94f839b0b75967ed3e2110f61f/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L29-L31
it looks like codegen of `AllocateUninitializedArray` is not better compared to `new T[]`: https://godbolt.org/z/5EEoe8Pxc 🤔

**Comment by Wraith2** [comment]
> it looks like codegen of `AllocateUninitializedArray` is not better compared to `new T[]`:

More generally; is there evidence that this is needed or that it increases speed noticably? Benchmarks?

**Comment by stephentoub** [comment]
AllocateUninitializedArray is pure overhead for smaller arrays; in fact, it just delegates to new T[] when the length is under some threshold. List.ToArray is very frequently used with shorter lists, so I expect on average this is likely a deoptimization. We would definitely need perf data to justify the change.

**Comment by cincuranet** [comment]
Thanks @stephentoub for poking me (virtually), because for some reason I though the threshold was smaller. But it's actually `2048 / Unsafe.SizeOf<T>()`. 

https://github.com/dotnet/runtime/blob/ddb22ef2ac96ed31cfd85782d1c38b1523642aaa/src/coreclr/System.Private.CoreLib/src/System/GC.cs#L660

So I agree. For `int`s and similar it has zero (or negative) effect unless one has big list.

For the completeness, I did run some benchmarks for few types (including `string` for fun).

<details>

```text
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1526 (21H1/May2021Update)
AMD Ryzen 7 5800X, 1 CPU, 16 logical and 8 physical cores
.NET SDK=6.0.200
  [Host]     : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT
  DefaultJob : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT
```

## System.Int32

|        Method |  Size |          Mean |      Error |     StdDev | Ratio | RatioSD |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|-------------- |------ |--------------:|-----------:|-----------:|------:|--------:|--------:|--------:|--------:|----------:|
|        Normal |     0 |     0.2409 ns |  0.0402 ns |  0.0376 ns |  1.00 |    0.00 |       - |       - |       - |         - |
| Uninitialized |     0 |     0.2415 ns |  0.0069 ns |  0.0064 ns |  1.02 |    0.14 |       - |       - |       - |         - |
|               |       |               |            |            |       |         |         |         |         |           |
|        Normal |     1 |     5.2151 ns |  0.1045 ns |  0.0977 ns |  1.00 |    0.00 |  0.0019 |       - |       - |      32 B |
| Uninitialized |     1 |     5.5508 ns |  0.0646 ns |  0.0604 ns |  1.06 |    0.02 |  0.0019 |       - |       - |      32 B |
|               |       |               |            |            |       |         |         |         |         |           |
|        Normal |     2 |     5.4955 ns |  0.1414 ns |  0.1322 ns |  1.00 |    0.00 |  0.0019 |       - |       - |      32 B |
| Uninitialized |     2 |     5.5548 ns |  0.0560 ns |  0.0468 ns |  1.01 |    0.03 |  0.0019 |       - |       - |      32 B |
|               |       |               |            |            |       |         |         |         |         |           |
|        Normal |     3 |     5.6620 ns |  0.0954 ns |  0.0892 ns |  1.00 |    0.00 |  0.0024 |       - |       - |      40 B |
| Uninitialized |     3 |     5.2233 ns |  0.1238 ns |  0.1034 ns |  0.92 |    0.02 |  0.0024 |       - |       - |      40 B |
|               |       |               |            |            |       |         |         |         |         |           |
|        Normal |     5 |     5.1825 ns |  0.0711 ns |  0.0594 ns |  1.00 |    0.00 |  0.0029 |       - |       - |      48 B |
| Uninitialized |     5 |     5.7416 ns |  0.1515 ns |  0.1417 ns |  1.11 |    0.04 |  0.0029 |       - |       - |      48 B |
|               |       |               |            |            |       |         |         |         |         |           |
|        Normal |    10 |     5.4563 ns |  0.0766 ns |  0.0640 ns |  1.00 |    0.00 |  0.0038 |       - |       - |      64 B |
| Uninitialized |    10 |     5.6372 ns |  0.0826 ns |  0.0772 ns |  1.03 |    0.02 |  0.0038 |       - |       - |      64 B |
|               |       |               |            |            |       |         |         |         |         |           |
|        Normal |    20 |     7.3776 ns |  0.0616 ns |  0.0514 ns |  1.00 |    0.00 |  0.0062 |       - |       - |     104 B |
| Uninitialized |    20 |     7.4430 ns |  0.1181 ns |  0.1105 ns |  1.01 |    0.02 |  0.0062 |       - |       - |     104 B |
|               |       |               |            |            |       |         |         |         |         |           |
|        Normal |    50 |    10.7617 ns |  0.1391 ns |  0.1233 ns |  1.00 |    0.00 |  0.0134 |       - |       - |     224 B |
| Uninitialized |    50 |    10.9137 ns |  0.2100 ns |  0.1754 ns |  1.01 |    0.02 |  0.0134 |       - |       - |     224 B |
|               |       |               |            |            |       |         |         |         |         |           |
|        Normal |   100 |    16.9776 ns |  0.2446 ns |  0.2168 ns |  1.00 |    0.00 |  0.0253 |  0.0000 |       - |     424 B |
| Uninitialized |   100 |    17.0816 ns |  0.3328 ns |  0.3113 ns |  1.01 |    0.02 |  0.0253 |  0.0000 |       - |     424 B |
|               |       |               |            |            |       |         |         |         |         |           |
|        Normal |  1000 |   119.5980 ns |  2.3123 ns |  3.7991 ns |  1.00 |    0.00 |  0.2404 |  0.0036 |       - |   4,024 B |
| Uninitialized |  1000 |   120.7159 ns |  1.9105 ns |  1.5953 ns |  1.01 |    0.03 |  0.2396 |  0.0036 |       - |   4,024 B |
|               |       |               |            |            |       |         |         |         |         |           |
|        Normal | 10000 | 1,353.0949 ns | 26.7233 ns | 39.9982 ns |  1.00 |    0.00 |  2.3861 |  0.2975 |       - |  40,024 B |
| Uninitialized | 10000 |   904.5351 ns | 17.8805 ns | 41.7951 ns |  0.68 |    0.04 |  2.3804 |  0.2975 |       - |  40,024 B |
|               |       |               |            |            |       |         |         |         |         |           |
|        Normal | 32767 | 5,310.2953 ns | 96.9657 ns | 95.2333 ns |  1.00 |    0.00 | 41.6641 | 41.6641 | 41.6641 | 131,110 B |
| Uninitialized | 32767 | 4,156.2216 ns | 82.2385 ns | 91.4078 ns |  0.78 |    0.02 | 41.6641 | 41.6641 | 41.6641 | 131,110 B |


## System.Byte

|        Method |  Size |          Mean |      Error |     StdDev |  Ratio | RatioSD |  Gen 0 |  Gen 1 | Allocated |
|-------------- |------ |--------------:|-----------:|-----------:|-------:|--------:|-------:|-------:|----------:|
|        Normal |     0 |     0.0289 ns |  0.0055 ns |  0.0051 ns |   1.00 |    0.00 |      - |      - |         - |
| Uninitialized |     0 |     0.0307 ns |  0.0046 ns |  0.0043 ns |   1.10 |    0.26 |      - |      - |         - |
|               |       |               |            |            |        |         |        |        |           |
|        Normal |     1 |     5.7467 ns |  0.1485 ns |  0.1389 ns |   1.00 |    0.00 | 0.0019 |      - |      32 B |
| Uninitialized |     1 |     5.5909 ns |  0.0809 ns |  0.0676 ns |   0.98 |    0.02 | 0.0019 |      - |      32 B |
|               |       |               |            |            |        |         |        |        |           |
|        Normal |     2 |     5.4405 ns |  0.1512 ns |  0.1485 ns |   1.00 |    0.00 | 0.0019 |      - |      32 B |
| Uninitialized |     2 |     5.4402 ns |  0.1298 ns |  0.1084 ns |   1.00 |    0.04 | 0.0019 |      - |      32 B |
|               |       |               |            |            |        |         |        |        |           |
|        Normal |     3 |     5.2886 ns |  0.1305 ns |  0.1221 ns |   1.00 |    0.00 | 0.0019 |      - |      32 B |
| Uninitialized |     3 |     5.4761 ns |  0.1394 ns |  0.1304 ns |   1.04 |    0.04 | 0.0019 |      - |      32 B | 
|               |       |               |            |            |        |         |        |        |           |
|        Normal |     5 |     5.6600 ns |  0.1045 ns |  0.0978 ns |   1.00 |    0.00 | 0.0019 |      - |      32 B |
| Uninitialized |     5 |     5.5776 ns |  0.1210 ns |  0.1132 ns |   0.99 |    0.03 | 0.0019 |      - |      32 B |
|               |       |               |            |            |        |         |        |        |           |
|        Normal |    10 |     5.5743 ns |  0.1364 ns |  0.1276 ns |   1.00 |    0.00 | 0.0024 |      - |      40 B |
| Uninitialized |    10 |     5.7747 ns |  0.1430 ns |  0.1337 ns |   1.04 |    0.04 | 0.0024 |      - |      40 B |
|               |       |               |            |            |        |         |        |        |           |
|        Normal |    20 |     5.8361 ns |  0.1325 ns |  0.1239 ns |   1.00 |    0.00 | 0.0029 |      - |      48 B |
| Uninitialized |    20 |     5.8730 ns |  0.1602 ns |  0.1420 ns |   1.01 |    0.03 | 0.0029 |      - |      48 B | 
|               |       |               |            |            |        |         |        |        |           |
|        Normal |    50 |     6.9978 ns |  0.1573 ns |  0.1471 ns |   1.00 |    0.00 | 0.0048 |      - |      80 B |
| Uninitialized |    50 |     7.0615 ns |  0.0974 ns |  0.0813 ns |   1.01 |    0.02 | 0.0048 |      - |      80 B |
|               |       |               |            |            |        |         |        |        |           |
|        Normal |   100 |     8.1944 ns |  0.1731 ns |  0.2126 ns |   1.00 |    0.00 | 0.0076 |      - |     128 B |
| Uninitialized |   100 |     8.0183 ns |  0.0687 ns |  0.0609 ns |   0.98 |    0.03 | 0.0076 |      - |     128 B |
|               |       |               |            |            |        |         |        |        |           |
|        Normal |  1000 |    35.6855 ns |  0.7367 ns |  1.0327 ns |   1.00 |    0.00 | 0.0612 | 0.0002 |   1,024 B |
| Uninitialized |  1000 |    35.6858 ns |  0.4432 ns |  0.3929 ns |   0.98 |    0.02 | 0.0612 | 0.0002 |   1,024 B |
|               |       |               |            |            |        |         |        |        |           |
|        Normal | 10000 |   293.4366 ns |  5.9210 ns | 10.8270 ns |   1.00 |    0.00 | 0.5984 | 0.0210 |  10,024 B |
| Uninitialized | 10000 |   225.4983 ns |  4.5679 ns | 13.0325 ns |   0.80 |    0.06 | 0.5970 | 0.0210 |  10,024 B |
|               |       |               |            |            |        |         |        |        |           |
|        Normal | 32767 | 1,056.0043 ns | 20.8260 ns | 34.7956 ns |   1.00 |    0.00 | 1.9531 | 0.2155 |  32,792 B |
| Uninitialized | 32767 |   766.7403 ns | 15.2413 ns | 27.8695 ns |   0.73 |    0.04 | 1.9522 | 0.2165 |  32,792 B |


## System.Decimal

|        Method |  Size |            Mean |          Error |         StdDev | Ratio | RatioSD |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|-------------- |------ |----------------:|---------------:|---------------:|------:|--------:|---------:|---------:|---------:|----------:|
|        Normal |     0 |       0.2336 ns |      0.0028 ns |      0.0026 ns |  1.00 |    0.00 |        - |        - |        - |         - |
| Uninitialized |     0 |       0.2282 ns |      0.0072 ns |      0.0067 ns |  0.98 |    0.03 |        - |        - |        - |         - |
|               |       |                 |                |                |       |         |          |          |          |           |
|        Normal |     1 |       5.0706 ns |      0.1453 ns |      0.1427 ns |  1.00 |    0.00 |   0.0024 |        - |        - |      40 B |
| Uninitialized |     1 |       6.0809 ns |      0.1198 ns |      0.1121 ns |  1.20 |    0.03 |   0.0024 |        - |        - |      40 B |
|               |       |                 |                |                |       |         |          |          |          |           |
|        Normal |     2 |       5.1571 ns |      0.0471 ns |      0.0441 ns |  1.00 |    0.00 |   0.0033 |        - |        - |      56 B |
| Uninitialized |     2 |       6.2830 ns |      0.1670 ns |      0.1562 ns |  1.22 |    0.03 |   0.0033 |        - |        - |      56 B |
|               |       |                 |                |                |       |         |          |          |          |           |
|        Normal |     3 |       5.5457 ns |      0.0399 ns |      0.0354 ns |  1.00 |    0.00 |   0.0043 |        - |        - |      72 B |
| Uninitialized |     3 |       6.5098 ns |      0.1580 ns |      0.1478 ns |  1.17 |    0.02 |   0.0043 |        - |        - |      72 B |
|               |       |                 |                |                |       |         |          |          |          |           |
|        Normal |     5 |       7.0810 ns |      0.1296 ns |      0.1212 ns |  1.00 |    0.00 |   0.0062 |        - |        - |     104 B |
| Uninitialized |     5 |       7.9581 ns |      0.1866 ns |      0.1654 ns |  1.12 |    0.03 |   0.0062 |        - |        - |     104 B |
|               |       |                 |                |                |       |         |          |          |          |           |
|        Normal |    10 |       9.5301 ns |      0.2273 ns |      0.3259 ns |  1.00 |    0.00 |   0.0110 |        - |        - |     184 B |
| Uninitialized |    10 |      10.0010 ns |      0.0746 ns |      0.0661 ns |  1.05 |    0.03 |   0.0110 |        - |        - |     184 B |
|               |       |                 |                |                |       |         |          |          |          |           |
|        Normal |    20 |      14.6439 ns |      0.2863 ns |      0.2678 ns |  1.00 |    0.00 |   0.0206 |        - |        - |     344 B |
| Uninitialized |    20 |      15.9616 ns |      0.2879 ns |      0.2693 ns |  1.09 |    0.03 |   0.0206 |        - |        - |     344 B |
|               |       |                 |                |                |       |         |          |          |          |           |
|        Normal |    50 |      31.3276 ns |      0.5656 ns |      0.5290 ns |  1.00 |    0.00 |   0.0492 |   0.0001 |        - |     824 B |
| Uninitialized |    50 |      31.5045 ns |      0.6617 ns |      0.7620 ns |  1.01 |    0.02 |   0.0492 |   0.0001 |        - |     824 B |
|               |       |                 |                |                |       |         |          |          |          |           |
|        Normal |   100 |      56.2371 ns |      0.7089 ns |      0.5535 ns |  1.00 |    0.00 |   0.0970 |   0.0005 |        - |   1,624 B |
| Uninitialized |   100 |      56.9178 ns |      0.3465 ns |      0.2894 ns |  1.01 |    0.01 |   0.0970 |   0.0005 |        - |   1,624 B |
|               |       |                 |                |                |       |         |          |          |          |           |
|        Normal |  1000 |     454.2874 ns |      9.0124 ns |     19.9708 ns |  1.00 |    0.00 |   0.9556 |   0.0525 |        - |  16,024 B |
| Uninitialized |  1000 |     396.3886 ns |      7.9837 ns |     12.8922 ns |  0.85 |    0.04 |   0.9542 |   0.0529 |        - |  16,024 B |
|               |       |                 |                |                |       |         |          |          |          |           |
|        Normal | 10000 |   6,267.9046 ns |     10.1187 ns |      9.4650 ns |  1.00 |    0.00 |  49.9954 |  49.9954 |  49.9954 | 160,041 B |
| Uninitialized | 10000 |   5,192.9213 ns |     31.7136 ns |     28.1133 ns |  0.83 |    0.00 |  49.9954 |  49.9954 |  49.9954 | 160,041 B |
|               |       |                 |                |                |       |         |          |          |          |           |
|        Normal | 32767 | 317,494.2874 ns | 34,880.6440 ns | 99,516.4401 ns |  1.00 |    0.00 | 115.0513 | 115.0513 | 115.0513 | 524,329 B |
| Uninitialized | 32767 | 361,325.8650 ns |  6,906.2377 ns |  9,219.6290 ns |  4.52 |    4.31 | 103.6072 | 103.5767 | 103.5767 | 524,324 B |


## System.String

|        Method |  Size |           Mean |       Error |      StdDev | Ratio | RatioSD |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
|-------------- |------ |---------------:|------------:|------------:|------:|--------:|--------:|--------:|--------:|----------:|
|        Normal |     0 |      0.2401 ns |   0.0040 ns |   0.0036 ns |  1.00 |    0.00 |       - |       - |       - |         - |
| Uninitialized |     0 |      0.0286 ns |   0.0076 ns |   0.0071 ns |  0.12 |    0.03 |       - |       - |       - |         - |
|               |       |                |             |             |       |         |         |         |         |           |
|        Normal |     1 |      6.1457 ns |   0.0739 ns |   0.0655 ns |  1.00 |    0.00 |  0.0019 |       - |       - |      32 B |
| Uninitialized |     1 |      6.1115 ns |   0.0348 ns |   0.0325 ns |  0.99 |    0.01 |  0.0019 |       - |       - |      32 B |
|               |       |                |             |             |       |         |         |         |         |           |
|        Normal |     2 |      6.7494 ns |   0.1074 ns |   0.1004 ns |  1.00 |    0.00 |  0.0024 |       - |       - |      40 B |
| Uninitialized |     2 |      7.0882 ns |   0.1131 ns |   0.0883 ns |  1.05 |    0.02 |  0.0024 |       - |       - |      40 B |
|               |       |                |             |             |       |         |         |         |         |           |
|        Normal |     3 |      6.9449 ns |   0.1090 ns |   0.1019 ns |  1.00 |    0.00 |  0.0029 |       - |       - |      48 B |
| Uninitialized |     3 |      6.8565 ns |   0.0846 ns |   0.0750 ns |  0.99 |    0.02 |  0.0029 |       - |       - |      48 B |
|               |       |                |             |             |       |         |         |         |         |           |
|        Normal |     5 |      7.6069 ns |   0.0620 ns |   0.0580 ns |  1.00 |    0.00 |  0.0038 |       - |       - |      64 B |
| Uninitialized |     5 |      7.6768 ns |   0.0898 ns |   0.0840 ns |  1.01 |    0.02 |  0.0038 |       - |       - |      64 B |
|               |       |                |             |             |       |         |         |         |         |           |
|        Normal |    10 |      9.3419 ns |   0.2194 ns |   0.1945 ns |  1.00 |    0.00 |  0.0062 |       - |       - |     104 B |
| Uninitialized |    10 |      9.4081 ns |   0.1406 ns |   0.1315 ns |  1.01 |    0.02 |  0.0062 |       - |       - |     104 B |
|               |       |                |             |             |       |         |         |         |         |           |
|        Normal |    20 |     11.9345 ns |   0.0636 ns |   0.0531 ns |  1.00 |    0.00 |  0.0110 |       - |       - |     184 B |
| Uninitialized |    20 |     12.0674 ns |   0.1072 ns |   0.0837 ns |  1.01 |    0.01 |  0.0110 |       - |       - |     184 B |
|               |       |                |             |             |       |         |         |         |         |           |
|        Normal |    50 |     19.4895 ns |   0.2403 ns |   0.2248 ns |  1.00 |    0.00 |  0.0253 |  0.0000 |       - |     424 B |
| Uninitialized |    50 |     19.8914 ns |   0.3474 ns |   0.3250 ns |  1.02 |    0.02 |  0.0253 |  0.0000 |       - |     424 B |
|               |       |                |             |             |       |         |         |         |         |           |
|        Normal |   100 |     34.6647 ns |   0.2208 ns |   0.2065 ns |  1.00 |    0.00 |  0.0492 |  0.0001 |       - |     824 B |
| Uninitialized |   100 |     35.1656 ns |   0.3329 ns |   0.2951 ns |  1.01 |    0.01 |  0.0492 |  0.0001 |       - |     824 B |
|               |       |                |             |             |       |         |         |         |         |           |
|        Normal |  1000 |    302.4886 ns |   4.8272 ns |   4.2792 ns |  1.00 |    0.00 |  0.4792 |  0.0138 |       - |   8,024 B |
| Uninitialized |  1000 |    284.3465 ns |   2.4217 ns |   2.1468 ns |  0.94 |    0.01 |  0.4792 |  0.0138 |       - |   8,024 B |
|               |       |                |             |             |       |         |         |         |         |           |
|        Normal | 10000 |  2,578.2052 ns |  51.2544 ns | 101.1712 ns |  1.00 |    0.00 |  4.7607 |  0.9499 |       - |  80,024 B |
| Uninitialized | 10000 |  2,538.4976 ns |  50.7581 ns | 109.2621 ns |  0.99 |    0.06 |  4.7607 |  0.9499 |       - |  80,024 B |
|               |       |                |             |             |       |         |         |         |         |           |
|        Normal | 32767 | 28,120.0151 ns | 116.9852 ns |  97.6879 ns |  1.00 |    0.00 | 83.3130 | 83.3130 | 83.3130 | 262,188 B |
| Uninitialized | 32767 | 27,951.3249 ns |  55.0418 ns |  51.4861 ns |  0.99 |    0.00 | 83.3130 | 83.3130 | 83.3130 | 262,188 B |

</details>

**Pull request closed without merging**
