### PR TITLE
Fix repro project for Release builds

### PR DESCRIPTION
**Pull request by MichalStrehovsky**

### CODE REVIEW

**Comment by VSadov** [comment]
Is this fixing an issue like:

```
  System.AggregateException: One or more errors occurred. (Code generation failed for method '[System.Collections]System.Collections.Generic.TreeSet`1<System.Collections.Generic.KeyValuePair`2<System.__Cano
  n,System.__Canon>>.AddIfNotPresent(KeyValuePair`2<__Canon,__Canon>)')
   ---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[System.Collections]System.Collections.Generic.TreeSet`1<System.Collections.Generic.KeyValuePair`2<System.__Canon,System.
  __Canon>>.AddIfNotPresent(KeyValuePair`2<__Canon,__Canon>)'
   ---> ILCompiler.ScannerFailedException: VTable of type 'System.Collections.Generic.TreeSet`1<System.Collections.Generic.KeyValuePair`2<System.__Canon, System.__Canon>>' not computed by the IL scanner. Yo
  u can work around by running the compilation with scanner disabled.
. . .
```

**Comment by MichalStrehovsky** [comment]
> Is this fixing an issue like:

No, this is just for the repro project.

I'm looking at the `VTable of type 'System.Collections.Generic.TreeSet` issue though. I think it's exposed by #73683 (I didn't verify, but it's likely). I understand what's the problem and working on a fix.

**Comment by MichalStrehovsky** [comment]
@VSadov if it's blocking you, add a projectexclusion like Lakshan did in #73734. I'll have a fix soon.

**Comment by VSadov** [comment]
It is blocking https://github.com/dotnet/runtime/pull/73741, but it can wait till tomorrow.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
