### PR TITLE
Add default method support to virtual statics

### PR DESCRIPTION
**Pull request by davidwrighton**
- The preview feature version of virtual statics implemented for .NET 6 does not allow for the interface methods to have a default implementation.
- With this change, we add support for the interface method having an actual implementation to CoreCLR. From what I can tell the Mono runtime already had such support
- There are some small ECMA spec updates to allow this change that are also included

In addition, I've taken the liberty to enable running the coreclr test suite on Mono on Windows. It needed a small amount of fixup.

### CODE REVIEW

**Comment by davidwrighton** [comment]
@vargaz When I run the new tests on Mono, they fail with crashes after 12 tests. However, we ALSO fail with a crash after 12 tests in the old test which hasn't been changed. When do we plan to fix this test suite for Mono?
@MichalStrehovsky I have not updated anything in NativeAOT. Have static virtuals been implemented for NativeAOT yet or are you waiting for the Crossgen2 implementation to be implemented?
@trylek fyi

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky I have not updated anything in NativeAOT. Have static virtuals been implemented for NativeAOT yet or are you waiting for the Crossgen2 implementation to be implemented?

I've been waiting for the type system change part of #54063 but since it looks like it might not land anytime soon, I might just take the type system part, finish it, and run with it. Might not get to that soon either though. But it looks like NativeAOT has more urgency for that for .NET 7 than crossgen2 has.

**Review by trylek — APPROVED** [review]
This is indeed very nice and clean, thanks David! The expanded test set will be of immense help when stabilizing SVM resolution in Crossgen2 in the presence of default interface methods.

**Comment by davidwrighton** [comment]
Running an outerloop crossgen test to make sure that the rather long new test names don't cause significant issues in our test suite.

**Comment by davidwrighton** [comment]
- The preview feature version of virtual statics implemented for .NET 6 does not allow for the interface methods to have a default implementation.
- With this change, we add support for the interface method having an actual implementation to CoreCLR. From what I can tell the Mono runtime already had such support
- There are some small ECMA spec updates to allow this change that are also included

In addition, I've taken the liberty to enable running the coreclr test suite on Mono on Windows. It needed a small amount of fixup.

**Pull request merged**
