### PR TITLE
Update DNNE

### LINKED ISSUE #90376: ComInterfaceGenerator and LibraryImportGenerator tests fail on linux-arm with "symbol lookup error: /root/helix/work/workitem/e/Microsoft.Interop.Tests.NativeExportsNE.so: undefined symbol: __atomic_compare_exchange_4"
See e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=370764&view=ms.vss-test-web.build-test-results-tab.

```scala
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: ComInterfaceGenerator.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  ComInterfaceGenerator.Tests (found 41 of 44 test cases)
  Starting:    ComInterfaceGenerator.Tests (parallel test collections = on, max threads = 2)
/root/helix/work/correlation/dotnet: symbol lookup error: /root/helix/work/workitem/e/Microsoft.Interop.Tests.NativeExportsNE.so: undefined symbol: __atomic_compare_exchange_4
/root/helix/work/workitem/e
----- end Fri Aug 11 07:50:08 UTC 2023 ----- exit code 127 ----------------------------------------------------------
```

```json
{
  "ErrorMessage": "undefined symbol: __atomic_",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=370764
**Error message validated:** `undefined symbol: __atomic_`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/14/2023 2:20:00 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[373115](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373115)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373115&view=ms.vss-test-web.build-test-results-tab&runId=7925090&resultId=209262)|dotnet/runtime#90519|
|[372849](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372849)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372849&view=ms.vss-test-web.build-test-results-tab&runId=7919178&resultId=205301)|dotnet/runtime#90519|
|[372550](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372550)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372550&view=ms.vss-test-web.build-test-results-tab&runId=7912388&resultId=209250)||
|[372473](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372473)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372473&view=ms.vss-test-web.build-test-results-tab&runId=7909752&resultId=200383)||
|[372445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372445)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372445&view=ms.vss-test-web.build-test-results-tab&runId=7908632&resultId=209261)|dotnet/runtime#90270|
|[372307](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372307)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372307&view=ms.vss-test-web.build-test-results-tab&runId=7903904&resultId=209249)||
|[372247](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372247)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372247&view=ms.vss-test-web.build-test-results-tab&runId=7901958&resultId=200384)||
|[371518](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371518)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371518&view=ms.vss-test-web.build-test-results-tab&runId=7883648&resultId=209248)||
|[371313](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371313)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371313&view=ms.vss-test-web.build-test-results-tab&runId=7879540&resultId=209248)|dotnet/runtime#90413|
|[370973](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370973)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370973&view=ms.vss-test-web.build-test-results-tab&runId=7879210&resultId=200374)|dotnet/runtime#90318|
|[371292](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371292)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371292&view=ms.vss-test-web.build-test-results-tab&runId=7879062&resultId=200381)||
|[370857](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370857)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370857&view=ms.vss-test-web.build-test-results-tab&runId=7868202&resultId=209239)||
|[370764](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370764)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370764&view=ms.vss-test-web.build-test-results-tab&runId=7866530&resultId=200371)||
|[370256](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370256)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370256&view=ms.vss-test-web.build-test-results-tab&runId=7856746&resultId=200343)|dotnet/runtime#90318|
|[370244](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370244)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370244&view=ms.vss-test-web.build-test-results-tab&runId=7856654&resultId=209209)||
|[369870](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369870)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369870&view=ms.vss-test-web.build-test-results-tab&runId=7849200&resultId=209212)|dotnet/runtime#89712|
|[369713](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369713)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369713&view=ms.vss-test-web.build-test-results-tab&runId=7842340&resultId=200320)|dotnet/runtime#90306|
|[369604](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369604)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369604&view=ms.vss-test-web.build-test-results-tab&runId=7840388&resultId=209185)|dotnet/runtime#90150|
|[369496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369496)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369496&view=ms.vss-test-web.build-test-results-tab&runId=7836698&resultId=209185)||
|[369482](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369482)|dotnet/runtime|[LibraryImportGenerator.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369482&view=ms.vss-test-web.build-test-results-tab&runId=7836352&resultId=209185)|dotnet/runtime#90298|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|13|20|

### PR DESCRIPTION
**Pull request by jtschuster**
Fixes https://github.com/dotnet/runtime/issues/90376

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by BruceForstall** [comment]
Ready to merge?

**Comment by jtschuster** [comment]
Yes, thanks for the bump, I lost track of this waiting for CI.

**Comment by BruceForstall** [comment]
@jtschuster @AaronRobinsonMSFT @jkoritzinsky It doesn't look like this fixed the problem. I kicked off a run after this merged, and it still has the failures:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=371718&view=ms.vss-test-web.build-test-results-tab&runId=7887268&resultId=200384&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by jtschuster** [comment]
I don't access to a computer to make the PR, but if you need it ASAP you can revert the version back to 1.0.27 and it should work again.

**Pull request merged**
