### PR TITLE
Remove SupportedOSPlatforms windows on Hosting WindowsServices

### LINKED ISSUE #59037: Remove platform restriction from Hosting.WindowsServices
https://github.com/dotnet/runtime/blob/fa284882f1fec209d2cadd915c621078e8041228/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/Directory.Build.props#L5

This project is windows specific, but it does its own platform checks and no-ops. This enables development on one platform and publishing to another.

The original change was here: https://github.com/dotnet/runtime/pull/53941/files

Some discussion offline with @jeffhandley and @davidfowl:

@jeffhandley said:

> I don’t think we have precedent on such a scenario yet. The attributes are meant to take a runtime failure (PNSE) and turn them into a build-time warning/error. My opinion is to two with your “on the other side” argument—if the API no-ops on non-Windows platforms, then I’m not sure the attribute gains anything. The `UseWindowsService()` / `UseSystemd()` pairing for local/deployed is nice too.
 
> Any objections to setting the precedent here that we can remove/omit attributes in cases where the API connotes the platform support by name or docs summary, and no-ops on other platforms?

@davidfowl said:

> I think this makes the most sense. The API that takes control into their own hands by doing manual platform tests should be able to suppress the warning so that consumers of that library don't get the warning.

### PR DESCRIPTION
**Pull request by eerhardt**
Fix #59037

### CODE REVIEW

**Review by Tratcher — APPROVED** [review]

**Comment by danmoseley** [comment]
failures are https://github.com/dotnet/runtime/issues/58927

**Review by jeffhandley — APPROVED** [review]
Looks good to me.

Per an email conversation, this change sets the precedent that we can omit attributes in cases where the API connotes the platform support by name or docs summary, and no-ops on other platforms.

**Review by buyaa-n — APPROVED** [review]
> Per an email conversation, this change sets the precedent that we can omit attributes in cases where the API connotes the platform support by name or docs summary, and no-ops on other platforms.

I wonder what if the developer doesn't know the API was no-op for other platforms, but for this assembly, it looks good to me as the assembly name indicates it is for `Windows` only

**Comment by eerhardt** [comment]
Merging. Failures are infrastructure and flaky networking.

**Pull request merged**
