### PR TITLE
Fix CI trigger of superpmi-asmdiffs pipeline

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib PTAL

**Review by echesakov — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Does this fix the "triggers too often issue" you were mentioning?

**Comment by BruceForstall** [comment]
> Does this fix the "triggers too often issue" you were mentioning?

yes... or I hope so :)

**Comment by BruceForstall** [comment]
Although it appears that anyone who created a branch with the un-fixed change will still kick off builds... ugh...

**Pull request merged**
