### PR TITLE
Update feature-switches.md

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
See https://github.com/dotnet/sdk/pull/18000

### CODE REVIEW

**Comment by elinor-fung** [comment]
Should probably have a doc update too: https://github.com/dotnet/docs/tree/main/docs/core/run-time-config

The state I see is:
- https://github.com/dotnet/sdk/pull/18000 does not set a default for `AutoreleasePoolSupport` when trimming
- The substitution is for `featurevalue=false`: https://github.com/dotnet/runtime/blob/0f79fe393227af3b2a472d892eab135fed3882aa/src/libraries/System.Private.CoreLib/src/ILLink/ILLink.Substitutions.OSX.xml#L3
- runtime defaults to not enabling support if configuration is not set: https://github.com/dotnet/runtime/blob/483fc90e356cc2d4f45fc5ad5e86dbbd92ef22d9/src/libraries/System.Private.CoreLib/src/System/Threading/AutoreleasePool.cs#L17-L19

Does that mean that the user needs to explicitly set `AutoreleasePoolSupport=false` in their project for the support to be trimmed even though support already won't be enabled?

**Comment by AaronRobinsonMSFT** [comment]
@elinor-fung Thanks. Update to SDK in https://github.com/dotnet/sdk/pull/18050.

**Review by elinor-fung — APPROVED** [review]
Looks good to me, assuming we will update the official docs.

**Comment by AaronRobinsonMSFT** [comment]
@elinor-fung Thanks for the reminder. https://github.com/dotnet/docs/pull/24516

**Pull request merged**
