### PR TITLE
Update guideline of squashing commits

### PR DESCRIPTION
**Pull request by kunalspathak**
@danmoseley @richlander

### CODE REVIEW

**Comment by jkotas** [comment]
I think we should:
- Add link from this doc to https://github.com/dotnet/runtime/blob/main/docs/pr-guide.md so that it is discoverable
- Recommend using merge instead of rebase to resolve merge conflicts.

**Review by jkotas — APPROVED** [review]

**Review by richlander — APPROVED** [review]

**Comment by danmoseley** [comment]
Given this kicked off builds and tests, it might be worth also modifying all places with this
https://github.com/dotnet/runtime/blob/812f8f56f4ce09d91ef6d436ccf88f4ccabc9687/eng/pipelines/global-build.yml#L17-L18

to add `*.md` or just change to `**.md`

**Comment by danmoseley** [comment]
@kunalspathak yes it would be fine to merge it since lint passed.

**Comment by kunalspathak** [comment]
> s it would be fine to merge it since lint passed.

I will fix the .yml to not kick off the builds.

**Pull request merged**
