### PR TITLE
JIT: Fix new helper calls for some block copies involving promoted locals

### LINKED ISSUE #85987: [Perf] Windows/x64: 4 Regressions on 5/2/2023 10:35:24 AM
### Run Information

Name | Value
-- | --
Architecture | x64
OS | Windows 10.0.18362
Queue | TigerWindows
Baseline | [da0aa0cb6944dd49d6c1d1859c4530fe7e38b76f](https://github.com/dotnet/runtime/commit/da0aa0cb6944dd49d6c1d1859c4530fe7e38b76f)
Compare | [c62f69be1405a8e41b56ffc05f22d791bf4c7d2d](https://github.com/dotnet/runtime/commit/c62f69be1405a8e41b56ffc05f22d791bf4c7d2d)
Diff | [Diff](https://github.com/dotnet/runtime/compare/da0aa0cb6944dd49d6c1d1859c4530fe7e38b76f...c62f69be1405a8e41b56ffc05f22d791bf4c7d2d)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Memory.ReadOnlySpan

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[Trim - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Memory.ReadOnlySpan.Trim(input%3a%20%22%22).html>) | 1.21 ns | 6.16 ns | 5.08 | 0.06 | False | 25.748831262174555 | 32.550956279423076 | 1.26417218505917) | [Trace](https://helixri107v0xdeko0k025g8.blob.core.windows.net/results-c740da37e49f40d586/Collect%20System.Memory.ReadOnlySpan.Trim_input%3A%20___/1/artifacts/BenchmarkDotNet.Artifacts/System.Memory.ReadOnlySpan.Trim%28input_%20__%29-20230509-040055.etl?sv=2021-08-06&se=2023-08-07T10%3A58%3A27Z&sr=c&sp=rl&sig=%2Bc6hyVJ2%2BNlKrNNedFUNWmcJElqVqL%2BoAAwpAtJVTZI%3D) | [Trace](https://helixri107v0xdeko0k025g8.blob.core.windows.net/results-8127b3b6acef4f22bb/Collect%20System.Memory.ReadOnlySpan.Trim_input%3A%20___/1/artifacts/BenchmarkDotNet.Artifacts/System.Memory.ReadOnlySpan.Trim%28input_%20__%29-20230509-035939.etl?sv=2021-08-06&se=2023-08-07T10%3A58%3A27Z&sr=c&sp=rl&sig=ESDrEyvjjSqR4eMZLINU3UC3qWEK8zWtIaFSSTI8tz8%3D)

[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_09_2023/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Memory.ReadOnlySpan.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-141be531-c366-43cf-967a-9f94a55ea1a803cd3309441437ca8/ec267393-df5d-4a1d-8e9e-a7e1eedb2f6d.zip?sv=2021-08-06&se=2023-06-01T02%3A04%3A18Z&sr=c&sp=rl&sig=s%2B8dP9ElatoWoeZLNv94fC4arHnxZx%2BM3SjHAe%2Bwtnc%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-44a88771-70bb-4ec2-b8c2-003be36420b377e3520c9be4d74b0/7e8ac75a-89a9-4583-9931-ee9d64135ad3.zip?sv=2021-08-06&se=2023-06-01T17%3A03%3A12Z&sr=c&sp=rl&sig=J6fZahCXMxiVbnHquCklNbssPFym3PCq6HC1dR7GnZQ%3D>)

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Memory.ReadOnlySpan*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-141be531-c366-43cf-967a-9f94a55ea1a803cd3309441437ca8/ec267393-df5d-4a1d-8e9e-a7e1eedb2f6d.zip?sv=2021-08-06&se=2023-06-01T02%3A04%3A18Z&sr=c&sp=rl&sig=s%2B8dP9ElatoWoeZLNv94fC4arHnxZx%2BM3SjHAe%2Bwtnc%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-44a88771-70bb-4ec2-b8c2-003be36420b377e3520c9be4d74b0/7e8ac75a-89a9-4583-9931-ee9d64135ad3.zip?sv=2021-08-06&se=2023-06-01T17%3A03%3A12Z&sr=c&sp=rl&sig=J6fZahCXMxiVbnHquCklNbssPFym3PCq6HC1dR7GnZQ%3D>)
#### System.Memory.ReadOnlySpan.Trim(input: "")

```log

```
### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 6.1584372859667615 > 1.2741125892426048.
IsChangePoint: Marked as a change because one of 4/1/2023 8:54:51 PM, 5/2/2023 4:25:00 AM, 5/9/2023 7:24:34 AM falls between 4/30/2023 6:17:41 PM and 5/9/2023 7:24:34 AM.
IsRegressionStdDev: Marked as regression because -100.89420966987244 (T) = (0 -6.161853322392986) / Math.Sqrt((0.03688747735264881 / (16)) + (5.8223116837808174E-05 / (18))) is less than -2.03693334345674 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (16) + (18) - 2, .025) and -3.6894142377733004 = (1.3139921128654337 - 6.161853322392986) / 1.3139921128654337 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```
### JIT Disasms
[Baseline](https://pvscmdupload.blob.core.windows.net/autofilereport/jitdasms/05_09_2023/System_Memory_ReadOnlySpan_Trim_input______baseline_744322a9-7866-4659-9a6f-6e51958a17fc.log)
[Compare](https://pvscmdupload.blob.core.windows.net/autofilereport/jitdasms/05_09_2023/System_Memory_ReadOnlySpan_Trim_input______compare_744322a9-7866-4659-9a6f-6e51958a17fc.log)
[Diff](https://perfsupport.azurewebsites.net/diff?old=https%3A%2F%2Fpvscmdupload.blob.core.windows.net%2Fautofilereport%2Fjitdasms%2F05_09_2023%2FSystem_Memory_ReadOnlySpan_Trim_input______baseline_744322a9-7866-4659-9a6f-6e51958a17fc.log&new=https%3A%2F%2Fpvscmdupload.blob.core.windows.net%2Fautofilereport%2Fjitdasms%2F05_09_2023%2FSystem_Memory_ReadOnlySpan_Trim_input______compare_744322a9-7866-4659-9a6f-6e51958a17fc.log)

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | Windows 10.0.18362
Queue | TigerWindows
Baseline | [da0aa0cb6944dd49d6c1d1859c4530fe7e38b76f](https://github.com/dotnet/runtime/commit/da0aa0cb6944dd49d6c1d1859c4530fe7e38b76f)
Compare | [c62f69be1405a8e41b56ffc05f22d791bf4c7d2d](https://github.com/dotnet/runtime/commit/c62f69be1405a8e41b56ffc05f22d791bf4c7d2d)
Diff | [Diff](https://github.com/dotnet/runtime/compare/da0aa0cb6944dd49d6c1d1859c4530fe7e38b76f...c62f69be1405a8e41b56ffc05f22d791bf4c7d2d)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Tests.Perf_Boolean

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[TryParse - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Tests.Perf_Boolean.TryParse(value%3a%20%22Bogus%22).html>) | 8.23 ns | 16.09 ns | 1.95 | 0.08 | True | 107.86852800069764 | 103.31347656402268 | 0.9577721924911639) | [Trace](https://helixri107v0xdeko0k025g8.blob.core.windows.net/results-3399003df3084efb99/Collect%20System.Tests.Perf_Boolean.TryParse_value%3A%20_Bogus__/1/artifacts/BenchmarkDotNet.Artifacts/System.Tests.Perf_Boolean.TryParse%28value_%20_Bogus_%29-20230509-040102.etl?sv=2021-08-06&se=2023-08-07T10%3A58%3A31Z&sr=c&sp=rl&sig=Qk89iKzk3bqbC4pH%2F3%2FhFUdVG2XO9XHFO2ZNtObfRM0%3D) | [Trace](https://helixri107v0xdeko0k025g8.blob.core.windows.net/results-aba3f08842974a45a3/Collect%20System.Tests.Perf_Boolean.TryParse_value%3A%20_Bogus__/1/artifacts/BenchmarkDotNet.Artifacts/System.Tests.Perf_Boolean.TryParse%28value_%20_Bogus_%29-20230509-040044.etl?sv=2021-08-06&se=2023-08-07T10%3A58%3A30Z&sr=c&sp=rl&sig=oVRtwlI16l6f4vxxVeElSCia1AnF0RiW6UaQw7GhwYE%3D)
[Parse - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Tests.Perf_Boolean.Parse(value%3a%20%22%20True%20%22).html>) | 11.15 ns | 23.30 ns | 2.09 | 0.04 | True | | |

[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_09_2023/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Tests.Perf_Boolean.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-141be531-c366-43cf-967a-9f94a55ea1a803cd3309441437ca8/ec267393-df5d-4a1d-8e9e-a7e1eedb2f6d.zip?sv=2021-08-06&se=2023-06-01T02%3A04%3A18Z&sr=c&sp=rl&sig=s%2B8dP9ElatoWoeZLNv94fC4arHnxZx%2BM3SjHAe%2Bwtnc%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-44a88771-70bb-4ec2-b8c2-003be36420b377e3520c9be4d74b0/7e8ac75a-89a9-4583-9931-ee9d64135ad3.zip?sv=2021-08-06&se=2023-06-01T17%3A03%3A12Z&sr=c&sp=rl&sig=J6fZahCXMxiVbnHquCklNbssPFym3PCq6HC1dR7GnZQ%3D>)

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Tests.Perf_Boolean*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-141be531-c366-43cf-967a-9f94a55ea1a803cd3309441437ca8/ec267393-df5d-4a1d-8e9e-a7e1eedb2f6d.zip?sv=2021-08-06&se=2023-06-01T02%3A04%3A18Z&sr=c&sp=rl&sig=s%2B8dP9ElatoWoeZLNv94fC4arHnxZx%2BM3SjHAe%2Bwtnc%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-44a88771-70bb-4ec2-b8c2-003be36420b377e3520c9be4d74b0/7e8ac75a-89a9-4583-9931-ee9d64135ad3.zip?sv=2021-08-06&se=2023-06-01T17%3A03%3A12Z&sr=c&sp=rl&sig=J6fZahCXMxiVbnHquCklNbssPFym3PCq6HC1dR7GnZQ%3D>)
#### System.Tests.Perf_Boolean.TryParse(value: "Bogus")

```log

```
### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 16.09071662999389 > 8.645237780024415.
IsChangePoint: Marked as a change because one of 5/2/2023 4:25:00 AM, 5/9/2023 7:24:34 AM falls between 4/30/2023 6:17:41 PM and 5/9/2023 7:24:34 AM.
IsRegressionStdDev: Marked as regression because -434.8770093633579 (T) = (0 -16.110760034502622) / Math.Sqrt((0.001710119303328648 / (16)) + (0.0039529119334182775 / (18))) is less than -2.03693334345674 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (16) + (18) - 2, .025) and -0.9521170175578498 = (8.252968387447188 - 16.110760034502622) / 8.252968387447188 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked as regression because Edge Detector said so.

```
### JIT Disasms
[Baseline](https://pvscmdupload.blob.core.windows.net/autofilereport/jitdasms/05_09_2023/System_Tests_Perf_Boolean_TryParse_value___Bogus___baseline_5e1270b6-0996-43ff-96eb-a0d8a79e25f0.log)
[Compare](https://pvscmdupload.blob.core.windows.net/autofilereport/jitdasms/05_09_2023/System_Tests_Perf_Boolean_TryParse_value___Bogus___compare_5e1270b6-0996-43ff-96eb-a0d8a79e25f0.log)
[Diff](https://perfsupport.azurewebsites.net/diff?old=https%3A%2F%2Fpvscmdupload.blob.core.windows.net%2Fautofilereport%2Fjitdasms%2F05_09_2023%2FSystem_Tests_Perf_Boolean_TryParse_value___Bogus___baseline_5e1270b6-0996-43ff-96eb-a0d8a79e25f0.log&new=https%3A%2F%2Fpvscmdupload.blob.core.windows.net%2Fautofilereport%2Fjitdasms%2F05_09_2023%2FSystem_Tests_Perf_Boolean_TryParse_value___Bogus___compare_5e1270b6-0996-43ff-96eb-a0d8a79e25f0.log)

#### System.Tests.Perf_Boolean.Parse(value: " True ")

```log

```
### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 23.3007016972274 > 11.713417691505466.
IsChangePoint: Marked as a change because one of 5/2/2023 4:25:00 AM, 5/9/2023 7:24:34 AM falls between 4/30/2023 6:17:41 PM and 5/9/2023 7:24:34 AM.
IsRegressionStdDev: Marked as regression because -237.4715523711942 (T) = (0 -23.51061790159726) / Math.Sqrt((0.001930512359178462 / (16)) + (0.04661613103783327 / (18))) is less than -2.03693334345674 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (16) + (18) - 2, .025) and -1.1090681140482666 = (11.147396210200926 - 23.51061790159726) / 11.147396210200926 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked as regression because Edge Detector said so.

```
### JIT Disasms
[Baseline](https://pvscmdupload.blob.core.windows.net/autofilereport/jitdasms/05_09_2023/System_Tests_Perf_Boolean_Parse_value____True____baseline_ee9816af-84e7-49d2-85e9-3049eafab215.log)
[Compare](https://pvscmdupload.blob.core.windows.net/autofilereport/jitdasms/05_09_2023/System_Tests_Perf_Boolean_Parse_value____True____compare_ee9816af-84e7-49d2-85e9-3049eafab215.log)
[Diff](https://perfsupport.azurewebsites.net/diff?old=https%3A%2F%2Fpvscmdupload.blob.core.windows.net%2Fautofilereport%2Fjitdasms%2F05_09_2023%2FSystem_Tests_Perf_Boolean_Parse_value____True____baseline_ee9816af-84e7-49d2-85e9-3049eafab215.log&new=https%3A%2F%2Fpvscmdupload.blob.core.windows.net%2Fautofilereport%2Fjitdasms%2F05_09_2023%2FSystem_Tests_Perf_Boolean_Parse_value____True____compare_ee9816af-84e7-49d2-85e9-3049eafab215.log)

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | x64
OS | Windows 10.0.18362
Queue | TigerWindows
Baseline | [da0aa0cb6944dd49d6c1d1859c4530fe7e38b76f](https://github.com/dotnet/runtime/commit/da0aa0cb6944dd49d6c1d1859c4530fe7e38b76f)
Compare | [c62f69be1405a8e41b56ffc05f22d791bf4c7d2d](https://github.com/dotnet/runtime/commit/c62f69be1405a8e41b56ffc05f22d791bf4c7d2d)
Diff | [Diff](https://github.com/dotnet/runtime/compare/da0aa0cb6944dd49d6c1d1859c4530fe7e38b76f...c62f69be1405a8e41b56ffc05f22d791bf4c7d2d)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Numerics.Tests.Perf_BigInteger

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[Ctor_ByteArray - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Numerics.Tests.Perf_BigInteger.Ctor_ByteArray(numberString%3a%20-2147483648).html>) | 12.28 ns | 14.23 ns | 1.16 | 0.10 | False | 150.3472191466558 | 156.214019115072 | 1.0390216726435988) | [Trace](https://helixri107v0xdeko0k025g8.blob.core.windows.net/results-20f462f7276e4472b1/Collect%20System.Numerics.Tests.Perf_BigInteger.Ctor_ByteArray_numberString%3A%20_2147483648_/1/artifacts/BenchmarkDotNet.Artifacts/System.Numerics.Tests.Perf_BigInteger.Ctor_ByteArray%28numberString_%20-2147483648%29-20230509-040127.etl?sv=2021-08-06&se=2023-08-07T10%3A58%3A36Z&sr=c&sp=rl&sig=EOidS%2BdwJZt2xcUnVtOyVCVmtHYWO2AlreBmlpG3Mf8%3D) | [Trace](https://helixri107v0xdeko0k025g8.blob.core.windows.net/results-ff97cf17d61d40c693/Collect%20System.Numerics.Tests.Perf_BigInteger.Ctor_ByteArray_numberString%3A%20_2147483648_/1/artifacts/BenchmarkDotNet.Artifacts/System.Numerics.Tests.Perf_BigInteger.Ctor_ByteArray%28numberString_%20-2147483648%29-20230509-040104.etl?sv=2021-08-06&se=2023-08-07T10%3A58%3A35Z&sr=c&sp=rl&sig=3bjS3emN6%2Br09yGnz7TEioVCz6otsY4eaO4dZSSloFw%3D)

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_09_2023/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Numerics.Tests.Perf_BigInteger.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-141be531-c366-43cf-967a-9f94a55ea1a803cd3309441437ca8/ec267393-df5d-4a1d-8e9e-a7e1eedb2f6d.zip?sv=2021-08-06&se=2023-06-01T02%3A04%3A18Z&sr=c&sp=rl&sig=s%2B8dP9ElatoWoeZLNv94fC4arHnxZx%2BM3SjHAe%2Bwtnc%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-44a88771-70bb-4ec2-b8c2-003be36420b377e3520c9be4d74b0/7e8ac75a-89a9-4583-9931-ee9d64135ad3.zip?sv=2021-08-06&se=2023-06-01T17%3A03%3A12Z&sr=c&sp=rl&sig=J6fZahCXMxiVbnHquCklNbssPFym3PCq6HC1dR7GnZQ%3D>)

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Numerics.Tests.Perf_BigInteger*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-141be531-c366-43cf-967a-9f94a55ea1a803cd3309441437ca8/ec267393-df5d-4a1d-8e9e-a7e1eedb2f6d.zip?sv=2021-08-06&se=2023-06-01T02%3A04%3A18Z&sr=c&sp=rl&sig=s%2B8dP9ElatoWoeZLNv94fC4arHnxZx%2BM3SjHAe%2Bwtnc%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-44a88771-70bb-4ec2-b8c2-003be36420b377e3520c9be4d74b0/7e8ac75a-89a9-4583-9931-ee9d64135ad3.zip?sv=2021-08-06&se=2023-06-01T17%3A03%3A12Z&sr=c&sp=rl&sig=J6fZahCXMxiVbnHquCklNbssPFym3PCq6HC1dR7GnZQ%3D>)
#### System.Numerics.Tests.Perf_BigInteger.Ctor_ByteArray(numberString: -2147483648)

```log

```
### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 14.229877638173855 > 12.895417745614084.
IsChangePoint: Marked as a change because one of 5/2/2023 4:25:00 AM, 5/9/2023 7:24:34 AM falls between 4/30/2023 6:17:41 PM and 5/9/2023 7:24:34 AM.
IsRegressionStdDev: Marked as regression because -17.21045122210507 (T) = (0 -14.152620211094012) / Math.Sqrt((0.013736477857531142 / (16)) + (0.21019152484066211 / (21))) is less than -2.0301079282477414 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (16) + (21) - 2, .025) and -0.14517624476570484 = (12.358464712992314 - 14.152620211094012) / 12.358464712992314 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```
### JIT Disasms
[Baseline](https://pvscmdupload.blob.core.windows.net/autofilereport/jitdasms/05_09_2023/System_Numerics_Tests_Perf_BigInteger_Ctor_ByteArray_numberString__-2147483648__baseline_647dc869-3571-47f6-b22a-cc31e82190de.log)
[Compare](https://pvscmdupload.blob.core.windows.net/autofilereport/jitdasms/05_09_2023/System_Numerics_Tests_Perf_BigInteger_Ctor_ByteArray_numberString__-2147483648__compare_647dc869-3571-47f6-b22a-cc31e82190de.log)
[Diff](https://perfsupport.azurewebsites.net/diff?old=https%3A%2F%2Fpvscmdupload.blob.core.windows.net%2Fautofilereport%2Fjitdasms%2F05_09_2023%2FSystem_Numerics_Tests_Perf_BigInteger_Ctor_ByteArray_numberString__-2147483648__baseline_647dc869-3571-47f6-b22a-cc31e82190de.log&new=https%3A%2F%2Fpvscmdupload.blob.core.windows.net%2Fautofilereport%2Fjitdasms%2F05_09_2023%2FSystem_Numerics_Tests_Perf_BigInteger_Ctor_ByteArray_numberString__-2147483648__compare_647dc869-3571-47f6-b22a-cc31e82190de.log)

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by jakobbotsch**
The change in #85620 was missing a check for the case where the
destination is not on stack but the source is. The backend still uses a
helper call for this case.

The field-by-field case would also usually involve helper calls since it
would normally need write barriers; however, the exception were for
byref fields, so Span<T>/ReadOnlySpan<T> were particularly affected.

This hopefully fixes https://github.com/dotnet/runtime/issues/85987 and https://github.com/dotnet/perf-autofiling-issues/issues/17605; I'll keep them open and recheck their perf graphs in a week or so to verify.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Ideally the backend should be fixed to be smarter about these block copies. The first problem is that we call a write barrier helped for `TYP_BYREF` fields, which is incorrect and inefficient (#80086). Even with that fixed we still need to ensure atomic field copies (for `TYP_BYREF` pointers), but `genCodeForCpObj` uses `movsq` to implement that, which is very inefficient (#7469). I left some measurements in https://github.com/dotnet/runtime/issues/85987#issuecomment-1547820361.

win-x64 diffs of this change against parent of #85620 (without benchmarks collections as that is currently broken): https://gist.github.com/jakobbotsch/cf4d31d5b84a5558819b369d85262745

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @EgorBo

**Comment by EgorBo** [comment]
@jakobbotsch I see a few size regressions where we emit now CORINFO_HELP_CHECKED_ASSIGN_REF instead of CORINFO_HELP_ASSIGN_BYREF, is that expected?

**Comment by jakobbotsch** [comment]
> @jakobbotsch I see a few size regressions where we emit now CORINFO_HELP_CHECKED_ASSIGN_REF instead of CORINFO_HELP_ASSIGN_BYREF, is that expected?

Yes it's expected, those diffs are essentially just the reverse of #85620... using the checked write barrier helper that also increments dst/src instead of the "normal" checked write barrier.

**Review by EgorBo — APPROVED** [review]

**Pull request merged**
