### PR TITLE
[wasm][debugger] Fix stepping out from an async method

### LINKED ISSUE #41973: [wasm][debugger] Crash/assert when stepping out from an async method
I changed aspnetcore's `StandaloneApp`'s `Counter.razor` to:
```csharp
@code {
    static HttpClient client = new HttpClient();
    int currentCount = 0;

    async Task IncrementCount()
    {
	        currentCount ++;
                await JustWaitAsync("foobar");
    }

    async Task<HttpStatusCode> JustWaitAsync(string some)
    {
        var resp = await client.GetAsync("http://localhost:8080");
        Console.WriteLine($"resp: {resp}"); /// BP at this line

        return resp.StatusCode;
    }
}
```

I set a breakpoint at CWL after `GetAsync`. Once that is hit, then I hit `step-over` twice, to step over the closing brace for `JustWaitAsync`, and then I get:
`: /Users/radical/dev/runtime/src/mono/mono/mini/mini-wasm-debugger.c:248 <disabled>`
.. which corresponds to `	g_error ("set_set_notification_for_wait_completion_flag");`

I'm trying this with my https://github.com/radical/runtime/tree/debugger-5.0-rc2 branch.

### PR DESCRIPTION
**Pull request by thaystg**
Stepping out from an async method fails with:

`: /Users/radical/dev/runtime/src/mono/mono/mini/mini-wasm-debugger.c:248 <disabled>`

.. which corresponds to `g_error ("set_set_notification_for_wait_completion_flag");`

Move some functions from debugger-agent to debugger-engine, which will make the proper implementation of `set_set_notification_for_wait_completion_flag` available for use in `mini-wasm-debugger.c`.

Fixes #41973.

### CODE REVIEW

**Comment by radical** [comment]
IIUC, this is needed as you are fixing issue #41973 .
So, maybe the title should be changed to: `[wasm][debugger] Move some functions from debugger-agent to debugger-engine`

And description to:
```
This will make them usable from mini-wasm-debugger. This needed for fixing #41973.
```

**Comment by radical** [comment]
Build failing with:
```
  /__w/1/s/src/mono/mono/mini/debugger-agent.c:714:20: error: static declaration of 'get_notify_debugger_of_wait_completion_method' follows non-static declaration
  static MonoMethod* get_notify_debugger_of_wait_completion_method (void);
                     ^
  /__w/1/s/src/mono/mono/mini/debugger-engine.h:325:13: note: previous declaration is here
  MonoMethod* get_notify_debugger_of_wait_completion_method (void);
              ^
  1 error generated.
```

**Comment by thaystg** [comment]
Changed the description and fixed the compilation error.
Thanks, @radical

**Review by radical — APPROVED** [review]

**Comment by thaystg** [comment]
@lewing should we backport?

**Comment by radical** [comment]
re:backport, maybe we should wait till we have the full fix for the issue.

**Comment by thaystg** [comment]
What would be the full fix? The variables that you are working on it?

**Comment by radical** [comment]
Oh, sorry, I just looked at the issue again. This is the full fix 😬 I thought that this was stuff needed in support of an upcoming fix!
We need to add tests for this.

**Review by lewing — APPROVED** [review]
This looks good but could use a test.

**Comment by thaystg** [comment]
I will add a test, but didn't add yet, because I think that we should merge it fast to be able to merge on RC2. So I was planning to add the test in another PR.

**Pull request merged**
