### PR TITLE
Move runtime tests out of the coreclr folder (dev/infrastructure branch)

### PR DESCRIPTION
**Pull request by trylek**
This is the initial bulky change aimed towards cleanup and better
convergence of runtime tests between the CoreCLR and Mono
runtimes. In this change I have moved all test source code and
build scripts from

src/coreclr/tests/src

to

src/tests

and I made what I believe to be the minimum number of additional
script changes to make the tests build and run end to end on
Windows and Linux.

Thanks

Tomas

/cc: @dotnet/runtime-infrastructure

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please rebase this against master and make sure that all tests are still moved correctly? There were test changes made in the meantime that the change is not picking up.

**Comment by trylek** [comment]
@jkotas - Thanks for pointing that out. I have already sent out the PR for a new FI from master to dev/infrastructure,

https://github.com/dotnet/runtime/pull/37982

I plan to rebase the change and trigger a new round of testing exactly as you suggest once that's merged in.

**Comment by jkotas** [comment]
Ok, I have not noticed that this is against dev/infrastructure. You will be on a treadmill until this gets to master.

**Comment by trylek** [comment]
I know but I'm afraid this is exactly the kind of change the branch is meant for :-).

**Comment by jkotas** [comment]
> I know but I'm afraid this is exactly the kind of change the branch is meant for :-).

I am not sure about that. This is very straightforward change (60 line delta + directory rename). It is going to have some fallout. There will be a few places that you will miss no matter how hard you try.

It is the kind of change we want to save for the infrastructure rollout (https://github.com/dotnet/runtime/issues/37706), but I think it is fine for it to go directly to master.

**Comment by trylek** [comment]
@jkotas - Thanks for your feedback, that sounds reasonable to me; after all, while the change is bulky, I have tried to make it minimal in the sense that all the outside-facing scripts remain in their preexisting locations so that right now the change doesn't require any pipeline changes or changes to local developer inner loop. I'll send out a rebased PR for this change against master and I'll merge it in tomorrow assuming it's been approved and there's no pushback from the @dotnet/runtime-infrastructure team.

**Comment by safern** [comment]
> I'll send out a rebased PR for this change against master and I'll merge it in tomorrow assuming it's been approved and there's no pushback from the @dotnet/runtime-infrastructure team.

I think we would need to hold until the next infra rollout for this change to be merged.

**Review by naricc — COMMENTED** [review]
I think we need to update the runtimetests subset in runtime.yml, since it refers to the test path: https://github.com/trylek/runtime/blob/6ca9f624c774b613d96d29e786881b1cd772f5ff/eng/pipelines/runtime.yml#L112

We also probably want to change it so the coreclr tests are run if the runtimetest path is updated.

**Comment by trylek** [comment]
Merged into master on 7/7, closing.

**Pull request closed without merging**
