### PR TITLE
perf: Fix issues caused by a shared `dotnet` in helix correlation payload directory

### PR DESCRIPTION
**Pull request by radical**
1. A copy of the `performance` repo is sent as correlation payload to helix. And then
we build from the same directory. But this is shared by the whole job.
And it gets uploaded only once. So, all the workitems on that machine
would share that directory.

This can cause issues like if a workitem has to be retried by helix,
then it will end up building incrementally, because it is using the same
artifacts from the first build. This case was hit when some wasm/aot
workitems were retries.

Solution: copy the diretory to `$HELIX_WORKITEM_ROOT/performance` before
building, since `$HELIX_WORKITEM_ROOT` is private to a workitem.

Thanks to @premun for the suggestion.

2. For blazor/wasm cases we use a `dotnet` in the correlation payload directory, thus shared by all the work items. But the pre/post scripts for the various blazor scenarios can install/uninstall the workload, which affects subsequent builds. Fix by passing the new `--readonly-dotnet` argument.

### CODE REVIEW

**Comment by radical** [comment]
Depends on https://github.com/dotnet/performance/pull/2367

**Comment by radical** [comment]
ping @DrewScoggins @LoopedBard3 @adamsitnik

**Comment by LoopedBard3** [comment]
Is there a test of this to make sure everything still works in the internal pipeline?

**Comment by radical** [comment]
I ran [this](https://dev.azure.com/dnceng/internal/_build/results?buildId=1724115&view=results) on Monday.

**Review by LoopedBard3 — APPROVED** [review]
LGTM, especially with successful test run.

**Pull request merged**
