### PR TITLE
Move CoreCLR community platforms to build with the global build template

### PR DESCRIPTION
**Pull request by jkoritzinsky**
This makes our community-supported platform testing story consistent (we do all testing of community-supported targets in the runtime-community pipeline and none in the runtime pipeline) and allows us to remove more custom code from the CoreCLR build-job.yml file.

Alternatively, we could keep running these legs in the runtime.yml file and just do the move to the global-build-job template.

### CODE REVIEW

**Comment by jkotas** [comment]
runtime-community is optional targets for targets that are too expensive and/or too flaky to run unconditionally. It includes tests.

We have build for linux-x86 and linux-armel in the unconditional pipeline to catch the trivial linux-x86 and linux-armel build breaks. The idea is that the build-only leg for linux-x86 and linux-armel is cheap enough and reliable enough to make it worth run unconditionally - it saves us from having to having to deal with the fix build break PRs.

**Comment by jkoritzinsky** [comment]
Sounds good 👍
I'll move these jobs back into the runtime pipeline.

**Comment by jkoritzinsky** [comment]
Jobs have been moved back into the runtime pipeline and fixed to pass.

**Review by trylek — APPROVED** [review]
LGTM, thanks Jeremy!

**Review by BruceForstall — APPROVED** [review]

**Review by clamp03 — APPROVED** [review]
Thank you

**Review by wscho77 — APPROVED** [review]
Thank you 👍

**Comment by jkoritzinsky** [comment]
Failures are all known.

**Pull request merged**
