### PR TITLE
Update OpenSUSE docker image

### PR DESCRIPTION
**Pull request by rzikm**
Contributes to https://github.com/dotnet/runtime/issues/75262.

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by rzikm** [comment]
OpenSUSE CI leg succeeded, MsQuic is working:
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75534-merge-1ed314aa7364433696/System.Net.Quic.Functional.Tests/1/console.e28a76ac.log?helixlogtype=result

All other CI legs are not relevant for this change

**Comment by carlossanlop** [comment]
Does this need a backport to 7.0 or older branches?

**Comment by rzikm** [comment]
> Does this need a backport to 7.0 or older branches?

Ideally, this would go together with #75479, I asked wfurt to cherry-pick it in

**Pull request merged**
