### PR TITLE
Delete some commented tests

### LINKED ISSUE #4680: Fix the disabled tests in the System V struct passing tests when Issue #2075 is resolved
Once the issue dotnet/runtime#4679 is resolved enable the commented out tests in System V bringup tests in JIT/Methodical/structs and make them test the right thing.

category:correctness
theme:testing
skill-level:beginner
cost:small

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fix #4680

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

**Review by jkoritzinsky — COMMENTED** [review]
These tests aren't going to pass since they rely on being able to marshal `System.Object`. The default marshalling for `System.Object` is Windows-only since it's COM marshalling. These tests should be disabled on non-Windows in a more standard manner (just check `if(OperatingSystem.IsWindows())`)

**Comment by MichalPetryka** [comment]
> These tests aren't going to pass since they rely on being able to marshal `System.Object`. The default marshalling for `System.Object` is Windows-only since it's COM marshalling. These tests should be disabled on non-Windows in a more standard manner (just check `if(OperatingSystem.IsWindows())`)

Wouldn't `PlatformDetection.IsBuiltInComEnabled` Be better here?

**Comment by jakobbotsch** [comment]
> These tests aren't going to pass since they rely on being able to marshal `System.Object`. The default marshalling for `System.Object` is Windows-only since it's COM marshalling. These tests should be disabled on non-Windows in a more standard manner (just check `if(OperatingSystem.IsWindows())`)

Thanks! I just deleted them, this test is under `systemvbringup` folder and seems more focused on the JIT's passing of structs that fit in registers.

**Comment by jakobbotsch** [comment]
Now this is just deleting commented code so I guess there is no point in running outerloop.

**Review by jkoritzinsky — APPROVED** [review]

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
