### PR TITLE
Don't report dependency on canonical forms just because there's GVMs

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
https://github.com/dotnet/runtime/pull/103039#discussion_r1631360914 found that we're generating some orphaned `MethodTable`s. They seem to be coming from here. Wondering if anything breaks if we just delete this.

### CODE REVIEW

**Comment by filipnavara** [comment]
```
Process terminated. Failed to create generic virtual method implementation


Declaring type: Generics+TestSimpleGVMScenarios+GenDerived`1<System.String>
Method name: GMethod1
Instantiation:
Argument 00000000: System.Int32


at System.RuntimeExceptionHelpers.FailFast(String, Exception, String, RhFailFastReason, IntPtr, IntPtr) + 0x250
at Internal.Runtime.TypeLoader.TypeLoaderEnvironment.ResolveGenericVirtualMethodTarget(RuntimeTypeHandle, RuntimeMethodHandle) + 0x310
at System.Runtime.TypeLoaderExports.<>c.<GVMLookupForSlotSlow>b__8_0(IntPtr, IntPtr, Object, IntPtr&) + 0x50
at System.Runtime.TypeLoaderExports.CacheMiss(IntPtr, IntPtr, RuntimeObjectFactory, Object) + 0x38
at System.Runtime.TypeLoaderExports.GVMLookupForSlotSlow(Object, RuntimeMethodHandle) + 0x68
at System.Runtime.TypeLoaderExports.GVMLookupForSlot(Object, RuntimeMethodHandle) + 0xbc
at Generics.TestSimpleGVMScenarios.[T](https://dev.azure.com/dnceng-public/public/_build/results?buildId=704798&view=ms.vss-test-web.build-test-results-tab&runId=17572496&resultId=100019&paneView=debug)estWithGenClassT + 0x38
at Generics.TestSimpleGVMScenarios.Run() + 0x1d8
at Generics.Run() + 0x58
at Program.<<Main>$>g__RunTest|0_0(Func`1, String) + 0x48
at Program.<Main>$(String[] args) + 0xd8
```

_(keeping it here for posterity, the CI results will expire at some point)_

**Comment by MichalStrehovsky** [comment]
So there are _some_ savings with this, but nothing to write home about:

# Size statistics

Pull request dotnet/runtime#103331

| Project | Size before | Size after | Difference |
|---------|-------------|------------|------------|
| avalonia.app-linux | [ 24514576 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596788096) | [ 24514576 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596788106) | 0 |
| avalonia.app-windows | [ 22029312 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596790002) | [ 22029312 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596790402) | 0 |
| hello-linux | [ 1356512 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596786475) | [ 1356512 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596786464) | 0 |
| hello-minimal-linux | [ 1094280 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596786658) | [ 1094280 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596786600) | 0 |
| hello-minimal-windows | [ 863744 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596787809) | [ 863744 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596789158) | 0 |
| hello-windows | [ 1107456 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596787742) | [ 1107456 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596789422) | 0 |
| kestrel-minimal-linux | [ 5771328 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596786684) | [ 5771328 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596786767) | 0 |
| kestrel-minimal-windows | [ 5070848 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596788434) | [ 5069824 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596789810) | -1024 |
| reflection-linux | [ 2232176 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596786359) | [ 2232176 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596786421) | 0 |
| reflection-windows | [ 1886208 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596787919) | [ 1886208 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596789297) | 0 |
| webapiaot-linux | [ 10424016 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596787045) | [ 10419920 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596787117) | -4096 |
| webapiaot-windows | [ 9353216 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596788867) | [ 9351680 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/9494384687/artifacts/1596791514) | -1536 |


I don't know if this is worth the extra 40 lines of code. @dotnet/ilc-contrib anyone thinks this is worth it? (I would lean towards "not worth it".)

**Comment by jkotas** [comment]
Does this make us 100% clean wrt not generating any orphaned symbols? If it does, I would say that it is worth it.

**Comment by MichalStrehovsky** [comment]
> Does this make us 100% clean wrt not generating any orphaned symbols? If it does, I would say that it is worth it.

@ivanpovazan was https://github.com/dotnet/runtime/pull/103039#discussion_r1631360914 the full list of symbols linker was able to strip, or just a sample?

**Comment by MichalStrehovsky** [comment]
UnitTest is pretty representative (it's a kitchen sink).

It might be more valuable if we can not just get clean, but also stay clean. Maybe I could look if the object writer could assert that all generated symbols are also referenced, or are specified as explicit exports (e.g. UnmanagedCallersOnly entrypoints)?

**Pull request closed without merging**
