### PR TITLE
Fix using the nopgooptimize flag in the CoreCLR build scripts.

### LINKED ISSUE #2013: Specifying -nopgooptimize fails when building coreclr
The coreclr fails when trying to build with -nopgooptimize:
```console
$ ./build.sh -nopgooptimize
Commencing CoreCLR Repo build
__DistroRid: linux-x64
__RuntimeId: linux-x64
Setting up directories for build
Checking prerequisites...
Build failed (exit code '1').
Failed to get PGO data package path.
```

### LINKED ISSUE #13693: build.cmd -skippgorestore -nopgooptimize results in error: Unable to locate restored PGO package. Maybe the platform-specific package naming changed?
Title exactly describes the problem. Below the output of build.cmd on Windows:

```cmd
E:\src\ms\dotnet\coreclr>build -x64 -Checked -skiptests -skipmscorlib -skipbuildpackages -skipmanagedtools -skiprestoreoptdata
BUILD: Starting Build at 20:16:56.51
BUILD: Detected Visual Studio 16.0 developer command prompt environment
BUILD: Commencing CoreCLR product build
BUILD: Checking prerequisites
BUILD: Number of processor cores 4
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview7-012821/dotnet-sdk-3.0.100-preview7-012821-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview7-012821/dotnet-sdk-3.0.100-preview7-012821-win-x64.zip
dotnet-install: Adding to current process PATH: "E:\src\ms\dotnet\coreclr\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
  Restore completed in 1.16 sec for E:\src\ms\dotnet\coreclr\eng\empty.csproj.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:03.06
E:\src\ms\dotnet\coreclr\src\.nuget\optdata\optdata.csproj(42,5): error : Unable to locate restored PGO package. Maybe the platform-specific package naming changed?

Build FAILED.

E:\src\ms\dotnet\coreclr\src\.nuget\optdata\optdata.csproj(42,5): error : Unable to locate restored PGO package. Maybe the platform-specific package naming changed?
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.34
Build failed.
Failed to get PGO data package path.
```

Expected no error due to -nopgooptimize option which so far allowed for builds without PGO data.

### LINKED ISSUE #31905: PGO Instrumentation Broken on CoreCLR Build
In the process of bringing up PGO training for the dotnet/runtime CoreCLR build, I've noticed that PGO instrumentation is broken on Linux.

Running this command:
```
./build.sh x64 release skiprestoreoptdata nopgooptimize pgoinstrument
```

results in this error:
```
Failed to get PGO data package path.
```

Without this functionality, we're unable to ship an optimized runtime for Linux.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #31905 
Fixes #2013
Fixes #13693

### CODE REVIEW

**Review by trylek — APPROVED** [review]
LGTM but I'd welcome @davidwrighton to also take a look.

**Review by CarolEidt — APPROVED** [review]
LGTM

**Review by davidwrighton — APPROVED** [review]
Looks good to me.

**Review by brianrob — APPROVED** [review]
LGTM.  Thanks!

**Comment by jkoritzinsky** [comment]
Mac test failure is missing libssl
cc: @safern 

live-build pipeline failure is a known issue.

I'm going to merge this in.

**Pull request merged**
