### PR TITLE
[wasm] Enable WasmTemplateTests on CI

### PR DESCRIPTION
**Pull request by radical**
cc @radekdoulik

### CODE REVIEW

**Review by radekdoulik — APPROVED** [review]

**Comment by radical** [comment]
@safern I've added `eng/Version.Details.xml` to the list of paths to trigger Wasm.Build.Tests, so we can catch issues introduced by arcade update PRs, like when getting an `dotnet/emsdk` update.

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
After this lands we can merge https://github.com/dotnet/emsdk/pull/102

**Comment by lewing** [comment]
I've updated the missing helix lane to something that still exists, I have no idea if it is the best one but we have several prs blocked on the missing one

**Comment by radical** [comment]
`CoreCLR Pri0 Runtime Tests Run Linux arm checked` is https://github.com/dotnet/runtime/issues/60154

Others (unrelated) are due to missing helix queues:
- `CoreCLR Pri0 Runtime Tests Run OSX x64 checked`
- `Libraries Test Run checked coreclr OSX x64 Debug`
- `Mono minijit Pri0 Runtime Tests Run OSX x64 release `
- `Mono monointerpreter Pri0 Runtime Tests Run OSX x64 release`

**Pull request merged**
