### PR TITLE
change regex options tests to extension method

### PR DESCRIPTION
**Pull request by danmoseley**
Readability improvement.

### CODE REVIEW

**Comment by stephentoub** [comment]
> Readability improvement.

Thanks, but I don't find this to be an improvement. The existing syntax is idiomatic and obviously cheap. The proposed change is not idiomatic and means I as a reader need to continually remind myself what these helpers do. There are a couple of existing ones, and the only reason they're still there is because someone chose to make them public; otherwise, they would have been deleted a long time ago.

**Comment by danmoseley** [comment]
> and the only reason they're still there is because someone chose to make them public

The ones in RegexParser? They are not public.

**Comment by stephentoub** [comment]
UseOptionC/R in Regex. The whole style of RegexParser is confusing with unnecessary helpers, as exemplified by your recent change to remove some. If there are more there's, we should get rid of them, too.

**Comment by danmoseley** [comment]
With respect to idiomatic: I'd certainly not want this done for flags in general. But anyone working in this codebase has to have substantial context already, and this pattern appears over and over. You're thinking it might not be efficient?

**Comment by stephentoub** [comment]
My concern is it makes it less readable to me, in part because I need to stop and think about what it's doing whenever I see it.

**Comment by danmoseley** [comment]
>  If there are more there, we should get rid of them, too.

OK, changed to this reverse approach. I do find it less readable but at least it's consistent 😄

**Review by stephentoub — APPROVED** [review]
Thanks

**Pull request merged**
