### PR TITLE
Make sure event generation is incremental

### PR DESCRIPTION
**Pull request by hoyosjs**
@agocke this is what you were seeing. After this there's only some issues with an RC file embedding.

### CODE REVIEW

**Comment by hoyosjs** [comment]
Related to https://github.com/dotnet/runtime/issues/47022

**Comment by ViktorHofer** [comment]
@directhex @akoeplinger @vargaz could someone of you please take a look at this cmake incrementality fix? We are currently short on cmake experts on our team :)

**Comment by agocke** [comment]
Why do we have to have explicit timestamp files? Are they just dummy files that we keep for other steps to depend on?

I presume there are other outputs and you just preferred not to relist all of them as dependencies?

**Comment by hoyosjs** [comment]
It's a common pattern in CMake to have a single output to represent the running of a target, and let it be a timestamp cmake generates. This is particularly common for places where you have a binary, and you modify it (so you don't generate what looks like a cycle). Also makes the "needs to run" comparison trivial. Yes, you could use byproducts and outputs, but this just felt easier and standard to do this.

**Review by agocke — APPROVED** [review]
LGTM, mac test failures don't look related to me

**Pull request merged**
