### PR TITLE
Move IsKnownConstant handling to ExtendedDefaultPolicy

### PR DESCRIPTION
**Pull request by EgorBo**
In https://github.com/dotnet/runtime/pull/63734 I added a special support for `IsKnownConstant` in the inliner, but I added it to the conservative `DefaultPolicy` (that doesn't scan call opcodes and is not able to recognize intrinsics). Moving to `ExtendedDefaultPolicy` (used by default in jit).

The idea of the heuristic is `if callee has IsKnownConstant(X) where X is a constant at the callsite in its caller => try harder inlining that callee into caller"`.

### CODE REVIEW

**Comment by jkotas** [comment]
> Moving to ExtendedDefaultPolicy (used by default in jit).

Is this policy used by AOT as well?

**Comment by EgorBo** [comment]
> > Moving to ExtendedDefaultPolicy (used by default in jit).
> 
> Is this policy used by AOT as well?

Only when `--Ot` is used at the moment.

**Comment by EgorBo** [comment]
@dotnet/jit-contrib PTAL, simple change, I need it for my other PR

**Comment by am11** [comment]
@EgorBo, are these pmi diffs expected:

```
libraries.pmi.Linux.x64.checked.mch:
...
Top method regressions (bytes):
        9499 (55.42 % of base) : 209928.dasm - Sys:GetDriveType(System.String):int
...
4 total methods with Code Size differences (0 improved, 4 regressed), 0 unchanged.
```
in this method:
https://github.com/dotnet/runtime/blob/59e643b9932122a12e71ceb360a9ae3bb9420dec/src/libraries/Common/src/Interop/Unix/System.Native/Interop.MountPoints.FormatInfo.cs#L78
which has a large switch case for variety of filesystems? (probably it is not critical for hot paths, just curious)

**Comment by EgorBo** [comment]
I've lowered the multiplier.

The problem with `IsKnownConstant(arg)` that it increases the benefit multiplier if input is a constant - it's great! But in reality we usually have something like this:

```csharp
if (IsKnownConstant(arg) && arg == 42)
```
so we should inline only if arg not only a constant at the callsite, but also a specific constant. It's not currently possible to correctly handle it unfortunately - inliner doesn't model basic blocks atm (but eventually will!), only if we introduce `RuntimeHelpers.IsKnownTrue(arg == 42)` but even that is not enough.

The regression in `GetDriveType` is rather an improvement I think, `String.Equals` makes sense to always inline for constant input. But for such a large function we most likely don't inline all of the Equals because of too many locals (e.g. Inliner has a heuristic:
https://github.com/dotnet/runtime/blob/fe24ab3040b454fd04983aba9eb0f600a2fb43e9/src/coreclr/jit/inlinepolicy.cpp#L1716-L1723

**Comment by EgorBo** [comment]
@dotnet/jit-contrib @AndyAyersMS PTAL

**Comment by AndyAyersMS** [comment]
It seems like if there are many such calls in a method, we might want to be less aggressive overall.  Can you see if this is the case in some of the larger regressions?
```
        3905 (34.53 % of base) : 48452.dasm - NpgsqlConnectionStringBuilder:ToCanonicalKeyword(String):String:this
```

Right now we evaluate inlinees more or less independently of one another, so recognizing this pattern might not be easy, but it would be interesting to see if there's a way to do this, say at least for the initial root level set of inlinees.

**Comment by EgorBo** [comment]
@AndyAyersMS I decided to remove benefit multiplier for it, because it already gets additional from "foldable branch" since JIT is able to recognize it.
Also, the existence of of IsKnownConstant currently removes BB count limits.

I don't want to add it additional boost because of:
```
if (IsKnownConstant(arg) && arg == 42)
{
    // fast path
}
```
where basically any constant arg will trigger that, but we only care about one specific value. 

No diffs.

**Review by AndyAyersMS — APPROVED** [review]
LGTM.

**Pull request merged**
