### PR TITLE
Remove [Serializable] from OptionException

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
We are no longer introducing `[Serializable]` exception types unless the library targets both .NET and downlevel. (Serialization of exceptions doesn't work in wasm anyway.) This removes the stray annotation.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Review by radical — APPROVED** [review]

**Comment by radical** [comment]
Merge main to get the fixes for the CI failures.

**Comment by danmoseley** [comment]
@radical  looks like there are still failures.

**Comment by radical** [comment]
`merge main` needed here.

**Comment by radical** [comment]
`runtime-wasm` is not needed, as the relevant test will get triggered on runtime, and runtime-staging.

**Comment by radical** [comment]
So many unrelated builds get triggered, like all the coreclr ones, non-wasm mono ones, even though this is strictly a wasm only change.

**Pull request merged**
