### PR TITLE
Set NativeLib=Shared for classlib by default

### LINKED ISSUE #69369: `-p:NativeLib=Shared` to be implied in the absence of NativeLib
Using `7.0.100-preview.5.22262.14` daily build.

Create a classlib project using `dotnet new classlib` and publish it with the following command:

```sh
dotnet publish --use-current-runtime -p:PublishAot=true
```

it fails with the following error:

```
Microsoft (R) Build Engine version 17.3.0-preview-22256-03+72a076794 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /home/am11/projects/nativelib/nativelib.csproj (in 195 ms).
/home/am11/.dotnet7/sdk/7.0.100-preview.5.22262.14/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(216,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/home/am11/projects/nativelib/nativelib.csproj]
  nativelib -> /home/am11/projects/nativelib/bin/Debug/net7.0/linux-x64/nativelib.dll
  Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeNativeAOT
EXEC : error : No entrypoint module [/home/am11/projects/nativelib/nativelib.csproj]
  System.Exception: No entrypoint module
     at ILCompiler.Program.Run(String[] args)
     at ILCompiler.Program.Main(String[] args)
/home/am11/.dotnet7/sdk/7.0.100-preview.5.22262.14/Sdks/Microsoft.DotNet.ILCompiler/build/Microsoft.NETCore.Native.targets(270,5): error MSB3073: The command ""/home/am11/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0-preview.5.22258.4/tools/ilc" @"obj/Debug/net7.0/linux-x64/native/nativelib.ilc.rsp"" exited with code 1. [/home/am11/projects/nativelib/nativelib.csproj]
```

Fix is to specify `NativeLib` property.

```
dotnet publish --use-current-runtime -p:PublishAot=true -p:NativeLib=Shared
```

It would make sense when NativeLib is unspecified for OutputType != Exe, its value is defaulted to `Shared` by the SDK.

cc @LakshanF, @agocke

### PR DESCRIPTION
**Pull request by am11**
Fix #69369

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Sorry @am11, must have missed the notification on this. Are the changes to the props files necessary? It looks like we import them from the targets file. Thank you for looking into this!

**Comment by MichalStrehovsky** [comment]
`Microsoft.NETCore.Native.targets` is the only thing that includes the props files though, so if we set it in `Microsoft.NETCore.Native.targets`, the props files would see it, no?

(The .props files really should have been named .targets, because including them from .targets is odd.)

**Comment by am11** [comment]
Got it. I have renamed .props to to .targets.

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!

**Pull request merged**
