### PR TITLE
Clean `impReturnInstruction` up a bit

### PR DESCRIPTION
**Pull request by SingleAccretion**
Delete target-specific `#ifdef`s and unify the associated code.

[No diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1905186&view=ms.vss-build-web.run-extensions-tab) as expected.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Let's get a fresh CI run here.

**Review by AndyAyersMS — APPROVED** [review]
LGTM, just one comment nit

**Comment by AndyAyersMS** [comment]
Thanks again for your contribution!

**Pull request merged**
