### PR TITLE
Solve recently introduce ASCII regression

### LINKED ISSUE #80247: Regressions in System.Text.Perf_Utf8Encoding and System.Text.Tests.Perf_Encoding
### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.25094
Baseline | [279fb0436f475fbc35ffeff68330f970ee77831a](https://github.com/dotnet/runtime/commit/279fb0436f475fbc35ffeff68330f970ee77831a)
Compare | [8d66372138fca4c9c73eef07c1632f13a0887d8e](https://github.com/dotnet/runtime/commit/8d66372138fca4c9c73eef07c1632f13a0887d8e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/279fb0436f475fbc35ffeff68330f970ee77831a...8d66372138fca4c9c73eef07c1632f13a0887d8e)

### Regressions in System.Text.Perf_Utf8Encoding

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[GetByteCount - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.25094/System.Text.Perf_Utf8Encoding.GetByteCount(Input%3a%20Greek).html>) | 38.55 μs | 58.79 μs | 1.52 | 0.63 | False | | |
[GetBytes - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.25094/System.Text.Perf_Utf8Encoding.GetBytes(Input%3a%20EnglishMostlyAscii).html>) | 203.89 μs | 254.92 μs | 1.25 | 0.60 | False | | |
[GetByteCount - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.25094/System.Text.Perf_Utf8Encoding.GetByteCount(Input%3a%20Chinese).html>) | 31.05 μs | 59.27 μs | 1.91 | 0.63 | False | | |
[GetByteCount - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.25094/System.Text.Perf_Utf8Encoding.GetByteCount(Input%3a%20EnglishMostlyAscii).html>) | 71.94 μs | 127.82 μs | 1.78 | 0.63 | False | | |
[GetByteCount - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.25094/System.Text.Perf_Utf8Encoding.GetByteCount(Input%3a%20Cyrillic).html>) | 23.92 μs | 47.40 μs | 1.98 | 0.65 | False | | |

graph
graph
graph
graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/12_29_2022/refs/heads/main_arm64_Windows%2010.0.25094_Regression/System.Text.Perf_Utf8Encoding.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Text.Perf_Utf8Encoding*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-417a7bda-c48f-4b8c-b921-206db636e6971efafa4f4af4e18bb/afa9cbe7-e7b6-48c4-8f17-0207ff95d0ac.zip?sv=2021-08-06&se=2023-01-20T04%3A52%3A30Z&sr=c&sp=rl&sig=h3a7Nh6gsO2GUfKW2k%2FyXi%2BwgZMJmNBgOymWgCkX0MI%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-b3b4e951-f9e5-47a8-9e66-3d270a8ff36dad0a9b8d3de4e41ac/aa1368b8-be13-4e57-9141-dca2745add61.zip?sv=2021-08-06&se=2023-01-20T23%3A19%3A17Z&sr=c&sp=rl&sig=ztNB3Pi4VtpXTK%2B50vz8MbZdVuIh2JBNhbCIrZ86etI%3D>)
#### System.Text.Perf_Utf8Encoding.GetByteCount(Input: Greek)

```log

```
### Description of detection logic
```IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 58.78677252650176 > 38.56174266572224.
IsChangePoint: Marked as a change because one of 12/21/2022 10:31:08 AM, 12/28/2022 6:20:56 PM falls between 12/19/2022 10:34:07 PM and 12/28/2022 6:20:56 PM.
IsRegressionStdDev: Marked as regression because -24.642880356633054 (T) = (0 -61272.045484563685) / Math.Sqrt((3231635.7490745448 / (13)) + (13770696.509863114 / (20))) is less than -2.0395134463927462 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (13) + (20) - 2, .025) and -0.6375680776935077 = (37416.487484822326 - 61272.045484563685) / 37416.487484822326 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```#### System.Text.Perf_Utf8Encoding.GetBytes(Input: EnglishMostlyAscii)

```log

```
### Description of detection logic
```IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 254.92176315789467 > 202.5638441984954.
IsChangePoint: Marked as a change because one of 12/21/2022 10:31:08 AM, 12/28/2022 6:20:56 PM falls between 12/19/2022 10:34:07 PM and 12/28/2022 6:20:56 PM.
IsRegressionStdDev: Marked as regression because -11.030456260848213 (T) = (0 -249154.62405981254) / Math.Sqrt((201147770.39900446 / (13)) + (151574382.4788075 / (20))) is less than -2.0395134463927462 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (13) + (20) - 2, .025) and -0.2699330956401716 = (196195.0790283279 - 249154.62405981254) / 196195.0790283279 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```#### System.Text.Perf_Utf8Encoding.GetByteCount(Input: Chinese)

```log

```
### Description of detection logic
```IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 59.265270161290324 > 35.61435114979619.
IsChangePoint: Marked as a change because one of 12/21/2022 10:31:08 AM, 12/28/2022 6:20:56 PM falls between 12/19/2022 10:34:07 PM and 12/28/2022 6:20:56 PM.
IsRegressionStdDev: Marked as regression because -23.49290089307371 (T) = (0 -58515.49681304273) / Math.Sqrt((4190721.2612498812 / (13)) + (15601297.696510985 / (20))) is less than -2.0395134463927462 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (13) + (20) - 2, .025) and -0.7287340583031703 = (33848.755701891074 - 58515.49681304273) / 33848.755701891074 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```#### System.Text.Perf_Utf8Encoding.GetByteCount(Input: EnglishMostlyAscii)

```log

```
### Description of detection logic
```IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 127.81981534090906 > 80.15821677714646.
IsChangePoint: Marked as a change because one of 12/21/2022 10:31:08 AM, 12/28/2022 6:20:56 PM falls between 12/19/2022 10:34:07 PM and 12/28/2022 6:20:56 PM.
IsRegressionStdDev: Marked as regression because -20.88937159330011 (T) = (0 -122573.92458679804) / Math.Sqrt((6202223.574572832 / (13)) + (89470089.16861711 / (20))) is less than -2.0395134463927462 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (13) + (20) - 2, .025) and -0.6107971293310409 = (76095.19681581666 - 122573.92458679804) / 76095.19681581666 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```#### System.Text.Perf_Utf8Encoding.GetByteCount(Input: Cyrillic)

```log

```
### Description of detection logic
```IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 47.402465206185575 > 26.441110882146138.
IsChangePoint: Marked as a change because one of 12/21/2022 10:31:08 AM, 12/28/2022 6:20:56 PM falls between 12/19/2022 10:34:07 PM and 12/28/2022 6:20:56 PM.
IsRegressionStdDev: Marked as regression because -24.18386114944223 (T) = (0 -47817.66947918986) / Math.Sqrt((3340879.0019299146 / (13)) + (12035498.973049158 / (20))) is less than -2.0395134463927462 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (13) + (20) - 2, .025) and -0.8820978500452556 = (25406.579938466042 - 47817.66947918986) / 25406.579938466042 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>
### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.25094
Baseline | [279fb0436f475fbc35ffeff68330f970ee77831a](https://github.com/dotnet/runtime/commit/279fb0436f475fbc35ffeff68330f970ee77831a)
Compare | [8d66372138fca4c9c73eef07c1632f13a0887d8e](https://github.com/dotnet/runtime/commit/8d66372138fca4c9c73eef07c1632f13a0887d8e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/279fb0436f475fbc35ffeff68330f970ee77831a...8d66372138fca4c9c73eef07c1632f13a0887d8e)

### Regressions in System.Text.Tests.Perf_Encoding

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[GetBytes - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.25094/System.Text.Tests.Perf_Encoding.GetBytes(size%3a%2016%2c%20encName%3a%20%22ascii%22).html>) | 39.97 ns | 50.39 ns | 1.26 | 0.65 | False | | |
[GetChars - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.25094/System.Text.Tests.Perf_Encoding.GetChars(size%3a%2016%2c%20encName%3a%20%22utf-8%22).html>) | 43.40 ns | 51.90 ns | 1.20 | 0.65 | False | | |

graph
graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/12_29_2022/refs/heads/main_arm64_Windows%2010.0.25094_Regression/System.Text.Tests.Perf_Encoding.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Text.Tests.Perf_Encoding*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-417a7bda-c48f-4b8c-b921-206db636e6971efafa4f4af4e18bb/afa9cbe7-e7b6-48c4-8f17-0207ff95d0ac.zip?sv=2021-08-06&se=2023-01-20T04%3A52%3A30Z&sr=c&sp=rl&sig=h3a7Nh6gsO2GUfKW2k%2FyXi%2BwgZMJmNBgOymWgCkX0MI%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-b3b4e951-f9e5-47a8-9e66-3d270a8ff36dad0a9b8d3de4e41ac/aa1368b8-be13-4e57-9141-dca2745add61.zip?sv=2021-08-06&se=2023-01-20T23%3A19%3A17Z&sr=c&sp=rl&sig=ztNB3Pi4VtpXTK%2B50vz8MbZdVuIh2JBNhbCIrZ86etI%3D>)
#### System.Text.Tests.Perf_Encoding.GetBytes(size: 16, encName: "ascii")

```log

```
### Description of detection logic
```IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 50.38990552918499 > 42.86550871073043.
IsChangePoint: Marked as a change because one of 10/17/2022 3:02:22 AM, 12/21/2022 10:31:08 AM, 12/28/2022 6:20:56 PM falls between 12/19/2022 10:34:07 PM and 12/28/2022 6:20:56 PM.
IsRegressionStdDev: Marked as regression because -5.127555412582627 (T) = (0 -44.637560236603335) / Math.Sqrt((8.958820198634074 / (13)) + (10.93650399530871 / (20))) is less than -2.0395134463927462 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (13) + (20) - 2, .025) and -0.1464031449234489 = (38.93705319482878 - 44.637560236603335) / 38.93705319482878 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```#### System.Text.Tests.Perf_Encoding.GetChars(size: 16, encName: "utf-8")

```log

```
### Description of detection logic
```IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 51.8996410785766 > 48.899269298461725.
IsChangePoint: Marked as a change because one of 12/22/2022 9:36:43 AM, 12/28/2022 6:20:56 PM falls between 12/19/2022 10:34:07 PM and 12/28/2022 6:20:56 PM.
IsRegressionStdDev: Marked as regression because -3.395306959489965 (T) = (0 -54.93801804432714) / Math.Sqrt((20.718999452564333 / (17)) + (12.97011407759705 / (16))) is less than -2.0395134463927462 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (17) + (16) - 2, .025) and -0.09654163952613115 = (50.101169042762955 - 54.93801804432714) / 50.101169042762955 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by adamsitnik**
One of the goals I had in #75012 was to replace the usage of internal helpers with new public API calls.

Initially we wanted to make `Ascii.GetIndexOfFirstNonAsciiChar` public, but at the end we decided to keep it internal.

Here I am removing the redundant call to `Ascii.GetIndexOfFirstNonAsciiChar(ROS)` with a call to the helper method that accepts a pointer and the length. What we get is one less method call, one less span creation and pinning.

fixes #80247

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]
LGTM. I assume we have a good test coverage for the changed APIs.

**Comment by adamsitnik** [comment]
I've applied no merge label as I am about to apply the same pattern in few other places and it would be better to merge of all of them in a single PR.

**Comment by stephentoub** [comment]
If this overhead resulted in a measurable regression, does that suggest there's something to be changed about the public APIs?  Presumably everyone else using them would hit similar issues?

**Comment by adamsitnik** [comment]
> If this overhead resulted in a measurable regression, does that suggest there's something to be changed about the public APIs? Presumably everyone else using them would hit similar issues?

The overhead is quite specific to our needs and is visible only for small inputs. Most of the Encoding methods pin the buffer and then just work with raw pointers:
https://github.com/dotnet/runtime/blob/e9b9489f41cface8f537f87ab1e187c9244c5ea9/src/libraries/System.Private.CoreLib/src/System/Text/ASCIIEncoding.cs#L96-L99
https://github.com/dotnet/runtime/blob/e9b9489f41cface8f537f87ab1e187c9244c5ea9/src/libraries/System.Private.CoreLib/src/System/Text/ASCIIEncoding.cs#L114-L117
https://github.com/dotnet/runtime/blob/e9b9489f41cface8f537f87ab1e187c9244c5ea9/src/libraries/System.Private.CoreLib/src/System/Text/ASCIIEncoding.cs#L144-L147

We introduced Span-accepting methods that are also pinning the memory and then just passing a pointer to the helper. So, the overhead comes from creating a span (from the pointer and length), pinning the memory (again), having one more method call (to our public method) and doing some basic checks again (like checking for empty span). It’s very little, but here it matters.
https://github.com/dotnet/runtime/blob/e9b9489f41cface8f537f87ab1e187c9244c5ea9/src/libraries/System.Private.CoreLib/src/System/Text/ASCIIEncoding.cs#L196
https://github.com/dotnet/runtime/blob/e9b9489f41cface8f537f87ab1e187c9244c5ea9/src/libraries/System.Private.CoreLib/src/System/Text/Ascii.cs#L25-L27
I've checked if we could get rid of pinning, but plenty of our ASCII helpers assume that the pointer is fixed and implement optimizations that are searching for the first aligned address:
https://github.com/dotnet/runtime/blob/e9b9489f41cface8f537f87ab1e187c9244c5ea9/src/libraries/System.Private.CoreLib/src/System/Text/Ascii.Utility.cs#L318
We could switch to using manager pointers and remove the optimizations that try to take advantage of the alignment, but it would be very hard to achieve performance parity.

FWIW I am not happy about making these changes, as it’s as step back s but it seems to be the lesser evil in this particular case.

**Pull request merged**
