### PR TITLE
[release/6.0] OpenSslX509ChainProcessor: ignore NotSignatureValid on last element.

### PR DESCRIPTION
**Pull request by tmds**
Backport of https://github.com/dotnet/runtime/pull/69668 to release/6.0

Fixes: https://github.com/dotnet/runtime/issues/65874#issuecomment-1098256123

# Customer Impact

RHEL9's default crypto policy no longer accepts the use of RSA+SHA1 signatures.

Because .NET uses strict OpenSSL validation, it does not accept certain certificates, which are considered valid by other tools (like `curl`/`wget`). This causes websites like `https://pkgs.dev.azure.com` to no longer be accessible using `HttpClient` on RHEL9.

This change relaxes the validation so these certificates are trusted by .NET.

# Testing

New tests are included as part of the change.

# Risk

Low. The existing tests, combined with the new tests, give confidence to the scoped change.  The version in `main` (and the backport) were authored by a Red Hat employee, so we feel that the new RHEL9 scenario has gotten about as good an eye as it could get.

### CODE REVIEW

**Comment by tmds** [comment]
@bartonjs feel free to improve my initial message.

**Comment by tmds** [comment]
cc @omajid

**Review by bartonjs — APPROVED** [review]

**Comment by bartonjs** [comment]
The failed legs are Helix warnings about queue deprecation, no tests failed.

**Comment by carlossanlop** [comment]
Servicing-approved label applied. Area owner signed off. CI passed with unrelated failures. 
:shipit:

**Pull request merged**
