### PR TITLE
Improve "one asg morphing" and move it to `morphblock.cpp`

### PR DESCRIPTION
**Pull request by SingleAccretion**
Before this change, we would only attempt to retype stores that had the primitive type the LHS. With this change, this is extended to support cases where retyping the RHS is profitable (most notably, if it is a `LCL_FLD<struct>(V00 primitive)`, former `OBJ(ADDR(LCL_VAR))`). For example:

```diff
-Local V04 should not be enregistered because: was accessed as a local field
 MorphCopyBlock (after):
-               [000023] -A-XG------                         *  ASG       struct (copy)
-               [000022] ---XG+-N---                         +--*  BLK       struct<System.Numerics.Quaternion, 16>
+               [000023] -A-XG------                         *  ASG       simd16 (copy)
+               [000022] ---XG+-N---                         +--*  IND       simd16
                [000021] -----+-----                         |  \--*  LCL_VAR   byref  V00 RetBuf
-               [000020] -----+-----                         \--*  LCL_FLD   struct<System.Numerics.Quaternion, 16> V04 loc1         [+0]
+               [000020] -----+-----                         \--*  LCL_VAR   simd16<System.Numerics.Vector4> V04 loc1
+
+fgMorphTree BB01, STMT00003 (after)
+               [000023] -A-XG+-----                         *  ASG       simd16 (copy)
+               [000022] ---XG+-N---                         +--*  IND       simd16
+               [000021] -----+-----                         |  \--*  LCL_VAR   byref  V00 RetBuf
+               [000020] -----+-----                         \--*  LCL_VAR   simd16<System.Numerics.Vector4> V04 loc1
```
This fixes one of the copies seen in #55357.

The change also moves the morphing into `morphblock.cpp`, which simplifies the setup and makes it a bit more efficient.

The diffs are mostly improvements, but there are some regressions as well in cases where losing DNER means we save/restore additional registers.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib 

I was experimenting with fixing codegen issues for "custom vectors" and this is one of the missing pieces.

**Comment by BruceForstall** [comment]
Going to re-test.

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
Failures all look known.

**Pull request merged**
