### PR TITLE
[release/6.0][EventPipe] Fix reverse connection socket leaking to child processes.

### PR DESCRIPTION
**Pull request by hoyosjs**
# Customer Impact

Clients requesting information through EventPipe could see a connection being active for an indeterminate even though the target runtime has closed it if the process forked in the time window from the session started to the time it gets finished. This was reported by customers through VS 4 mac.

# Description 

Sockets were getting leaked upon accepting connections. This meant that child processes could cause fully terminated tracing sessions and other IPC connections alive, causing clients to wait for input indefinitely. This sets the CLOEXEC bits on the socket atomically upon accepting if the OS provides the capability, falling back to a best effort fcntl on systems like macOS and x866 Android emulators.

Port of dotnet/runtime#65365 to release/6.0.

# Regression

No

# Testing

Validated customer scenario on top of testing. 

# Risk

Low. The change mitigates risk by preventing sockets getting inherited and ensuring the state is clean. When possible it does it as an atomic kernel operation. Should fall back to prior behavior if close on exec is not available.

### CODE REVIEW

**Comment by wfurt** [comment]
```
 -- Looking for accept4
  -- Looking for accept4 - not found
  CMake Error: File /eventpipe/ep-shared-config.h.in does not exist.
  CMake Error at /Users/runner/work/1/s/src/native/eventpipe/configure.cmake:12 (configure_file):
    configure_file Problem configuring file
  Call Stack (most recent call first):
    mono/eventpipe/CMakeLists.txt:3 (include)
    mono/component/CMakeLists.txt:56 (include)
    mono/mini/CMakeLists.txt:52 (include)
  ```

**Review by noahfalk — APPROVED** [review]
Source change LGTM (assuming that whatever the build issue is gets resolved)

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  We should take for consideration in 6.0.x

**Review by Therzok — APPROVED** [review]

**Comment by carlossanlop** [comment]
Branch is now open for Tactics-approved changes. The PR is signed off, has the `servicing-approved` label applied, and the CI passed. The mono System.Text.Json.Tests failure is known and unrelated.

**Pull request merged**
