### PR TITLE
[release/8.0] Bump version to GA

### PR DESCRIPTION
**Pull request by carlossanlop**
Here's what we did last year: https://github.com/dotnet/runtime/pull/75649

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]

**Comment by carlossanlop** [comment]
@lewing @steveisok @radical The failure is mono/wasm related. Can you please take a look when you get a chance?:

```
.packages/microsoft.dotnet.build.tasks.packaging/8.0.0-beta.23463.1/build/Packaging.targets(1217,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) System.Exception: The package ID 'Microsoft.NET.Workload.Mono.ToolChain.net6.Manifest-8.0.100-rtm.' contains invalid characters. Examples of valid package IDs include 'MyPackage' and 'MyPackage.Sample'.
   at NuGet.Packaging.Manifest.Validate(Manifest manifest)
   at NuGet.Packaging.Manifest.Save(Stream stream, Int32 minimumManifestVersion, Boolean generateBackwardsCompatible)
   at Microsoft.DotNet.Build.Tasks.Packaging.GenerateNuSpec.Save(Manifest manifest, Stream stream) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNuSpec.cs:line 159
   at Microsoft.DotNet.Build.Tasks.Packaging.GenerateNuSpec.WriteNuSpecFile() in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNuSpec.cs:line 127
   at Microsoft.DotNet.Build.Tasks.Packaging.GenerateNuSpec.Execute() in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/GenerateNuSpec.cs:line 98
```

**Comment by carlossanlop** [comment]
Oh, I think you're fixing it with https://github.com/dotnet/runtime/pull/92306

**Comment by carlossanlop** [comment]
> Oh, I _think_ you're fixing it with #92306

Wait, no. That PR was for RC2. This one is for `release/8.0`. Why is this one failing?

**Comment by steveisok** [comment]
> > Oh, I _think_ you're fixing it with #92306
> 
> Wait, no. That PR was for RC2. This one is for `release/8.0`. Why is this one failing?

There were a few flow PR's needing merged into release/8.0 in emsdk. That's been done and may resolve this once the internal build completes.

**Comment by lewing** [comment]
@steveisok this one looks like it needs the release/rtm check

**Comment by carlossanlop** [comment]
All green now!

**Pull request merged**
