### PR TITLE
Apple Silicon bundle distribution template

### PR DESCRIPTION
**Pull request by sdmaclea**
Apple Silicon requires a different distribution template

Set `options.hostArchitectures` to stop requiring Rosetta

Adjust minimum required version to 11.0

### CODE REVIEW

**Comment by sdmaclea** [comment]
I didn't see dotnet/arcade#7232.  This is my alternative until that merges....

**Comment by sdmaclea** [comment]
Local build. This looks good.

```console
stmaclea@stmaclea-arm64 runtime % pkgutil --expand artifacts/packages/Release/Shipping/dotnet-runtime-6.0.0-dev-osx-arm64.pkg ex
stmaclea@stmaclea-arm64 runtime % grep option ex/Distribution       
    <options customize="never" require-scripts="false" hostArchitectures="arm64"/>
stmaclea@stmaclea-arm64 runtime % grep -i os-version ex/Distribution
        <allowed-os-versions>
            <os-version min="11.0"/>
        </allowed-os-versions>
```

**Comment by sdmaclea** [comment]
Do we think we can get dotnet/arcade#7232 before preview4 snap?  Should I just close this?

**Comment by jkoritzinsky** [comment]
I'll approve this because otherwise we'll miss the snap (Arcade rolls out on Mondays and Wednesdays).

**Review by jkoritzinsky — APPROVED** [review]

**Pull request merged**
