### PR TITLE
FileShare change to ReadWrite

### PR DESCRIPTION
**Pull request by BaY1251**

### CODE REVIEW

**Comment by huoyaoyuan** [comment]
This is a behavioral change that doesn't look correct. Zip expects consistency within a file. The same file shouldn't be written simultaneously.

**Comment by BaY1251** [comment]
@huoyaoyuan  Some files, such as log files, are opened by writing throughout the entire lifecycle of the program.The folder containing these files can never be packaged.

**Comment by pentp** [comment]
You can just create `ZipArchiveEntry` directly yourself. Using `CreateEntryFromFile` isn't appropriate in such situations.

**Comment by BaY1251** [comment]
@pentp  I did solve it as you said, but most of the time people don't want to encounter exceptions when using ZipArchive and spend a lot of time looking for temporary solutions

**Comment by huoyaoyuan** [comment]
> but most of the time people don't want to encounter exceptions when using ZipArchive

This is not true. Most of the time people are expecting the methods to be reliable. Reading files that are written by other process requires extra causion and collaboration with the writer. This is not reliable by default.

**Comment by BaY1251** [comment]
Using compression software such as WinRar, built-in compression in Windows 11, etc., can all be used normally.
Unless debugged under these specific conditions, it will never be found that ZipFile performs differently from mainstream compression software

**Comment by ericstj** [comment]
Agree with what is said by @huoyaoyuan.  Opening a file with write sharing could cause us to write a torn file when we previously would have failed to write at all.  Consider in the middle of the call `CopyTo` a writer writes to both the beginning (missed) and end (observed) of file -- we'd have read a torn version of the file.

You should be able to use other API to perform this action if you can somehow guarantee that other writers to the file will never actually write it, but we should not take this change.

If you'd like to further discuss you can do so in an issue.

**Pull request closed without merging**
