### PR TITLE
Reconfigure the field sequences for statics

### LINKED ISSUE #62108: Assertion failed '(info.compCompHnd->getClassAttribs(fldCls) & CORINFO_FLG_VALUECLASS) == 0' during 'Do value numbering'
Found by Antigen:

With `COMPlus_JitOptRepeat=*`, we hit an assert during value numbering.

```c#

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
public class TestClass
{
    public struct S1
    {
        public struct S1_D1_F1
        {
            public double double_2;
        }
        public int int_4;
    }
    public struct S2
    {
        public S1.S1_D1_F1 s1_s1_d1_f1_6;
    }
    static decimal s_decimal_11 = 1.0533333333333333333333333333m;
    static int s_int_14 = 2;
    static S1 s_s1_23 = new S1();
    static S2 s_s2_24 = new S2();
    decimal decimal_28 = -4.8787878787878787878787878788m;
    int int_31 = -5;
    sbyte sbyte_33 = 1;
    ushort ushort_36 = 15;
    S1 s1_40 = new S1();
    S2 s2_41 = new S2();
    public int LeafMethod6()
    {
        unchecked
        {
            return s_s1_23.int_4 / 15+4<< (s_int_14 |= s_int_14 / (s_s1_23.int_4 += s1_40.int_4)+ 41);
        }
    }
    public ushort Method3(decimal p_decimal_82, ref sbyte p_sbyte_83, S1 p_s1_84, out S2 p_s2_85, out S2 p_s2_86, double p_double_87, short p_short_88)
    {
        unchecked
        {
            p_s2_85 = s2_41;
            p_s2_86 = s_s2_24;
            return ushort_36 <<= int_31 += s1_40.int_4 /= 15+4;
        }
    }
    public void Method0()
    {
        unchecked
        {
            short short_131 = 0;
            S2 s2_142 = new S2();
            S2 s2_143 = s2_142;
            ushort_36 = Method3(decimal_28 += s_decimal_11 *= 15+4, ref sbyte_33, s1_40, out s2_143, out s_s2_24, s2_143.s1_s1_d1_f1_6.double_2, (short)((short_131 |= (short)(2 << LeafMethod6()))% 15+4));
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
    }
}
/*
Got output diff:

--------- Test ---------  

Environment:

set COMPlus_TieredCompilation=0
set COMPlus_JitOptRepeat=*

Assert failure(PID 26888 [0x00006908], Thread: 7044 [0x1b84]): Assertion failed '(info.compCompHnd->getClassAttribs(fldCls) & CORINFO_FLG_VALUECLASS) == 0' in 'TestClass:LeafMethod6():int:this' during 'Do value numbering' (IL size 69)
    File: D:\git\runtime\src\coreclr\jit\valuenum.cpp Line: 9016
    Image: D:\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe
*/

```

### LINKED ISSUE #62178: Invalid field sequence in value numbering
```c#
// Found by Antigen
// TestClass
using System.Runtime.InteropServices;

public class TestClass_A
{
  [StructLayout(LayoutKind.Sequential, Size = 1)]
  public struct S1
  {
  }
  
  [StructLayout(LayoutKind.Sequential, Size = 1)]
  public struct S2
  {
  }
  
  private static byte s_byte_3 = 5;
  
  private static S1 s_s1_16 = default(S1);
  
  private static S2 s_s2_17 = default(S2);
  
  private byte byte_19 = 127;
  
  private short short_23 = -2;
  
  private sbyte sbyte_26 = 2;
  
  private S1 s1_32;
  
  private S2 s2_33;
  
  public byte Method33(ref S1 p_s1_865, ref S2 p_s2_866, ref short p_short_867, S1 p_s1_868, out S1 p_s1_869, out S1 p_s1_870, out S1 p_s1_871, S1 p_s1_872, ref sbyte p_sbyte_873, out S1 p_s1_874, ref S2 p_s2_875)
  {
    p_s1_874 = s1_32;
    return s_byte_3;
  }
  
  public byte Method96(ref S2 p_s2_2493, S2 p_s2_2494, ref S1 p_s1_2495, ref S2 p_s2_2496, ref S1 p_s1_2497, short p_short_2498, S2 p_s2_2499, out ushort p_ushort_2500, ref S2 p_s2_2501, S2 p_s2_2502, out S1 p_s1_2503, ref short p_short_2504, bool p_bool_2505)
  {
    p_ushort_2500 = 11;
    return (byte)((int)Method33(ref p_s1_2497, ref s_s2_17, ref short_23, p_s1_2495, out p_s1_2495, out s_s1_16, out s1_32, s_s1_16, ref sbyte_26, out s_s1_16, ref s2_33) % 15 + 4);
  }
  
  public void Method0()
  {
    ushort p_ushort_ = 2;
    S1 p_s1_ = default(S1);
    S2 p_s2_ = default(S2);
    byte_19 = Method96(ref p_s2_, s_s2_17, ref s_s1_16, ref p_s2_, ref s1_32, 19, s2_33, out p_ushort_, ref p_s2_, s_s2_17, out p_s1_, ref short_23, p_bool_2505: true);
  }
  
  public static void Main(string[] args)
  {
    new TestClass_A().Method0();
  }
}

// Test environment:

// COMPlus_JitOptRepeat=*
// COMPlus_JitStress=2
// COMPlus_TieredCompilation=0

```

```
Assert failure(PID 25408 [0x00006340], Thread: 2848 [0x0b20]): Assertion failed 'fldSeq2 != nullptr' in 'TestClass_A:Method96(byref,S2,byref,byref,byref,short,S2,byref,byref,S2,byref,byref,bool):ubyte:this' during 'Do value numbering' (IL size 71)

    File: D:\git\dotnet-runtime\src\coreclr\jit\valuenum.cpp Line: 9008
    Image: d:\git\dotnet-runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\corerun.exe
```

### PR DESCRIPTION
**Pull request by SingleAccretion**
To make the "boxed static" and, in the future, "shared" cases identical to simple ones.

It used to be that we attached the field sequence to the "inner" constant, and then added the `#FirstElem` pseudo-field for the
outer offset. This was causing complexity and mistakes in the pattern matching performed by `IsFieldAddr`.

The solution is straightforward: always use the outer offset for the sequence. The much simpler pattern is easier and cheaper to recognize, with less room for false positives.

This change is structured a little bit unconventionally to help validate it with SPMI. There are two DEBUG-only commits in it which I intend to use for a run of SPMI in CI, and then revert. This will mean that the end result will have some diffs, and the only source of them will be the fact that the new shape is friendlier to the way `gtGetStructHandleIfPresent` searches for handles on `IND struct` nodes.

Part of #58312.

Fixes #62108 (test added).
Fixes #62178 (test not added because it does not reproduce anymore - my previous change altered the CSE pattern).

### CODE REVIEW

**Comment by SingleAccretion** [comment]
Zero diffs have been recorded: https://dev.azure.com/dnceng/public/_build/results?buildId=1508466&view=ms.vss-build-web.run-extensions-tab.

I will now proceed to revert the debug commits.

**Comment by SingleAccretion** [comment]
[Full diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1509092&view=ms.vss-build-web.run-extensions-tab).

These are all struct CSEs. It seems out tuning could use some work, but overall I don't think it is worth quirking anything here.

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Review by jakobbotsch — APPROVED** [review]
Sorry for the wait -- this looks great to me. Seems much more conceptually simple this way.

> These are all struct CSEs. It seems our tuning could use some work, but overall I don't think it is worth quirking anything here.

Can you post some examples?

I will run Fuzzlyn/Antigen before merging this in the morning.

**Comment by SingleAccretion** [comment]
> Can you post some examples?

[Diffs](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-62632) - a few regressions, less so if one looks at PerfScore (which is more or less a wash as we use a struct from the stack instead of from external memory).

Causes:
1) We don't enregister structs that can be enregistered when they are stored to from an `IND(struct)`, i. e. we turn `STORE_LCL_VAR struct<4>(IND(struct))` into `STOREIND` (aka #59315).
```diff
-;  V07 cse1         [V07,T02] (  5,  5   )   byref  ->  rcx         "CSE - aggressive"
+;  V07 cse1         [V07,T02] (  5,  5   )  struct ( 8) [rsp+28H]   do-not-enreg[SB] "CSE - moderate"
```
2) Some struct CSEs do not pay off, e. g. here is a case in which we CSE a `System.Guid` instead if its address and it causes us to use callee-saved `xmm`s:
```diff
-;  V06 cse0         [V06,T01] (  4,  4   )   byref  ->  rcx         "CSE - aggressive"
+;  V06 cse0         [V06,T01] (  4,  4   )  struct (16) [rsp+20H]   do-not-enreg[SB] "CSE - moderate"
 ;
-; Lcl frame size = 80
+; Lcl frame size = 96

 G_M58351_IG01:        ; gcrefRegs=00000000 {}, byrefRegs=00000000 {}, byref, nogc <-- Prolog IG
        push     rsi
-       sub      rsp, 80
+       sub      rsp, 96
        vzeroupper
-                                               ;; bbWeight=1    PerfScore 2.25
+       vmovaps  qword ptr [rsp+50H], xmm6
+       vmovaps  qword ptr [rsp+40H], xmm7
+       vmovaps  qword ptr [rsp+30H], xmm8
+                                               ;; bbWeight=1    PerfScore 8.25
 G_M58351_IG02:        ; gcrefRegs=00000000 {}, byrefRegs=00000000 {}, byref
        mov      rcx, 0xD1FFAB1E
        mov      rcx, gword ptr [rcx]
        ; gcrRegs +[rcx]
-       add      rcx, 8
-       ; gcrRegs -[rcx]
-       ; byrRegs +[rcx]
-       vmovupd  xmm0, xmmword ptr [rcx]
-       vmovupd  xmmword ptr [rsp+40H], xmm0
-       vmovupd  xmm0, xmmword ptr [rcx]
-       vmovupd  xmmword ptr [rsp+30H], xmm0
-       vmovupd  xmm0, xmmword ptr [rcx]
+       vmovupd  xmm0, xmmword ptr [rcx+8]
        vmovupd  xmmword ptr [rsp+20H], xmm0
+       vmovupd  xmm6, xmmword ptr [rsp+20H]
+       vmovupd  xmm7, xmmword ptr [rsp+20H]
+       vmovupd  xmm8, xmmword ptr [rsp+20H]
        mov      rcx, 0xD1FFAB1E
-       ; byrRegs -[rcx]
+       ; gcrRegs -[rcx]
        call     CORINFO_HELP_NEWSFAST
        ; gcrRegs +[rax]
        ; gcr arg pop 0
@@ -49,22 +48,22 @@ G_M58351_IG02:        ; gcrefRegs=00000000 {}, byrefRegs=00000000 {}, byref
        call     System.Linq.Expressions.SymbolDocumentInfo:.ctor(System.String):this
        ; gcrRegs -[rax rcx rdx]
        ; gcr arg pop 0
-       vmovupd  xmm0, xmmword ptr [rsp+40H]
-       vmovupd  xmmword ptr [rsi+16], xmm0
-       vmovupd  xmm0, xmmword ptr [rsp+30H]
-       vmovupd  xmmword ptr [rsi+32], xmm0
-       vmovupd  xmm0, xmmword ptr [rsp+20H]
-       vmovupd  xmmword ptr [rsi+48], xmm0
+       vmovupd  xmmword ptr [rsi+16], xmm6
+       vmovupd  xmmword ptr [rsi+32], xmm7
+       vmovupd  xmmword ptr [rsi+48], xmm8
        mov      rax, rsi
        ; gcrRegs +[rax]
-                                               ;; bbWeight=1    PerfScore 35.75
+                                               ;; bbWeight=1    PerfScore 25.50
 G_M58351_IG03:        ; , epilog, nogc, extend
-       add      rsp, 80
+       vmovaps  xmm6, qword ptr [rsp+50H]
+       vmovaps  xmm7, qword ptr [rsp+40H]
+       vmovaps  xmm8, qword ptr [rsp+30H]
+       add      rsp, 96
        pop      rsi
        ret
```

**Comment by jakobbotsch** [comment]
Thanks, the diffs look acceptable.
I would just like to get a final confirmation from @jkotas or @davidwrighton that multiple overlapping mutable RVA statics is not a supported scenario so that removing the existing attempt to support it is ok (I realize it is currently broken, but then the question is if that's a bug).

**Comment by jkotas** [comment]
> multiple overlapping mutable RVA statics is not a supported scenario 

Sounds reasonable to me.

**Comment by jakobbotsch** [comment]
Great! Thanks for the contribution once again @SingleAccretion.

**Pull request merged**
