### PR TITLE
Add SystemNative_LowLevelMonitor_TimedWait to System.Native

### PR DESCRIPTION
**Pull request by CoffeeFlux**
First of 3 PRs.

The second will be adding some of the managed Threading implementations from NativeAOT, and the third will modify them, wire them up to the Mono build, and implement the necessary Mono-specific changes.

### CODE REVIEW

**Comment by CoffeeFlux** [comment]
This PR reminds me—we should really start differentiating between `DARWIN` and `MACOS` in `System.Native`, as there are cases where we want one behavior on desktop and another on, say, tvOS. As it is, `TARGET_OSX` is used for all those cases, but the `_XOPEN_SOURCE` change in this PR is only needed on desktop MacOS afaik.

I know historically there was interest in just using `TARGET_MACOS` in place of `TARGET_OSX` everywhere due to `OSX` being outdated, but it doesn't work in Mono for exactly this reason. You _have_ to distinguish between Darwin and MacOS.

**Comment by CoffeeFlux** [comment]
The current iOS/tvOS failures are due to `pthread_condattr_setclock` not being defined on those platforms. In Mono, we're currently very aggressive about what platforms we don't try to use this/`CLOCK_MONOTONIC` on:

```
#if !defined(CLOCK_MONOTONIC) || defined(HOST_DARWIN) || defined(HOST_ANDROID) || defined(HOST_WASM)
#define BROKEN_CLOCK_SOURCE
#endif
```

This is probably overkill nowadays, but the difference is worth noting. I'll add a check for `pthread_condattr_setclock` and see if that fixes things for now, but the target distinction I mentioned above would be very helpful for cases like these.

**Comment by CoffeeFlux** [comment]
I think this logic should work, unless I'm misremembering and these are broken at runtime on iOS as opposed to unavailable.

**Comment by jkotas** [comment]
Still does not build...

**Comment by CoffeeFlux** [comment]
Yeah, I forgot that in System.Native we use `#cmakedefine01` instead of just `#cmakedefine`. Old habits die hard :)

**Comment by CoffeeFlux** [comment]
It's not clear to me why this is breaking the CoreCLR desktop builds but not the Mono ones... Is it using the System.Native CMake stuff in a way I'm not familiar with? Build error it's hitting is here https://github.com/dotnet/runtime/blob/69e114c1abf91241a0eeecf1ecceab4711b8aa62/src/coreclr/gc/unix/events.cpp#L143

**Comment by jkotas** [comment]
I suspect that it is because `HAVE_PTHREAD_CONDATTR_SETCLOCK` is defined differently under CoreCLR, and the two definitions collide somehow.

**Comment by jkotas** [comment]
It may have something to do with `_XOPEN_SOURCE` define.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
