### PR TITLE
Adding check on R2RDump

### PR DESCRIPTION
**Pull request by BrianBohe**
Continuing with @cshung [comment](https://github.com/dotnet/runtime/pull/77289#issuecomment-1301607022).

There shouldn't be variable debug information reported with an empty range. This PR adds the validation check to existent function validation taken place when dumping R2R images. Check is not applied by default, and a command line argument of R2RDump is added to run it. The argument is added to existent projects running tests with R2RDump.

### CODE REVIEW

**Comment by BrianBohe** [comment]
Changes on src/tests/Common/CLRTest.CrossGen.targets will impact on pipelines. How can we test the changes on BasicTests and FrameworkTests?

**Comment by BrianBohe** [comment]
I succeeded buildling BasicTests and FrameworkTests with `.\src\tests\build.cmd dir .\readytorun\r2rdump\FrameworkTests\ dir .\readytorun\r2rdump\BasicTests\` but `.\src\tests\run.cmd` only run the former. Any idea of what can be happening?

**Review by trylek — APPROVED** [review]
Looks great to me, thank you!

**Comment by BrianBohe** [comment]
All errors are known errors so I will continue and merge this pr

**Pull request merged**
