### PR TITLE
JIT: Enable cross-block local assertion prop for natural loops

### PR DESCRIPTION
**Pull request by jakobbotsch**
For natural loop headers we can allow propagating assertions from the entering predecessors without intersecting them with the assertions from the backedges, provided that we take care to kill all assertions about locals that may be defined within the loop. We can pay a bit of TP to compute this set before morph.

This is a similar to what VN does for natural loops, just less general.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
This should effectively subsume what #90622 was doing. But let's see what the throughput cost is.

**Comment by jakobbotsch** [comment]
FYI @AndyAyersMS... Diffs: https://dev.azure.com/dnceng-public/public/_build/results?buildId=661917&view=ms.vss-build-web.run-extensions-tab

I think most of the cost here comes from finding loops, but we might be able to get more mileage out of that, for example by using it to do loop inversion instead of the existing lexical approach.

I'm a bit more concerned about the diffs themselves... they seem very mixed, and the perfscore diffs are mostly regressions.

**Comment by AndyAyersMS** [comment]
> I'm a bit more concerned about the diffs themselves... they seem very mixed, and the perfscore diffs are mostly regressions.

We saw this with the cross-block work too, I suspect the main culprit is simplistic copy prop not realizing when it is creating overlapping lifetimes. Aggressive forwarding of constants should mostly lead to good diffs though.

**Comment by AndyAyersMS** [comment]
And yes it would be nice to have a non-lexical approach to inversion.

**Comment by jakobbotsch** [comment]
The detailed TP breakdown for `benchmarks.run_pgo` looks like the following:
```
Base: 112388175446, Diff: 112575499368, +0.1667%

95138361  : +13.06%  : 15.98% : +0.0847% : public: struct GenTree * __cdecl Compiler::optAssertionProp_LclVar(unsigned __int64 *const &, struct GenTreeLclVarCommon *, struct Statement *)                                                                                                                                                                                                                                                                        
58708825  : +25.54%  : 9.86%  : +0.0522% : public: struct GenTree * __cdecl Compiler::optCopyAssertionProp(struct Compiler::AssertionDsc *, struct GenTreeLclVarCommon *, struct Statement *)                                                                                                                                                                                                                                                                     
43679563  : +19.96%  : 7.34%  : +0.0389% : public: static class FlowGraphNaturalLoops * __cdecl FlowGraphNaturalLoops::Find(class FlowGraphDfsTree const *)                                                                                                                                                                                                                                                                                                       
26554698  : NA       : 4.46%  : +0.0236% : `LoopDefinitions::Find'::`6'::<lambda_1>::operator()                                                                                                                                                                                                                                                                                                                                                                   
25868538  : +19.53%  : 4.35%  : +0.0230% : private: static bool __cdecl FlowGraphNaturalLoops::FindNaturalLoopBlocks(class FlowGraphNaturalLoop *, class ArrayStack<struct BasicBlock *> &)                                                                                                                                                                                                                                                                       
12979224  : +13.38%  : 2.18%  : +0.0115% : public: bool __cdecl FlowGraphNaturalLoop::ContainsBlock(struct BasicBlock *)                                                                                                                                                                                                                                                                                                                                          
12185730  : +12.01%  : 2.05%  : +0.0108% : public: enum PhaseStatus __cdecl Compiler::fgMorphBlocks(void)                                                                                                                                                                                                                                                                                                                                                         
11276461  : +165.45% : 1.89%  : +0.0100% : public: bool __cdecl JitHashTable<unsigned int, struct JitSmallPrimitiveKeyFuncs<unsigned int>, bool, class CompAllocator, class JitHashTableBehavior>::Set(unsigned int, bool, enum JitHashTable<unsigned int, struct JitSmallPrimitiveKeyFuncs<unsigned int>, bool, class CompAllocator, class JitHashTableBehavior>::SetKind)                                                                                       
10250996  : +16.63%  : 1.72%  : +0.0091% : BasicBlock::VisitRegularSuccs<``FlowGraphNaturalLoops::Find'::`7'::<lambda_1>::operator()'::`2'::<lambda_1> >                                                                                                                                                                                                                                                                                                          
9231715   : NA       : 1.55%  : +0.0082% : public: static class LoopDefinitions * __cdecl LoopDefinitions::Find(class FlowGraphNaturalLoops *)                                                                                                                                                                                                                                                                                                                    
8002461   : +33.98%  : 1.34%  : +0.0071% : public: static void __cdecl BitSetOps<unsigned __int64 *, 1, struct BitVecTraits *, struct BitVecTraits>::DiffD(struct BitVecTraits *, unsigned __int64 *&, unsigned __int64 *)                                                                                                                                                                                                                                        
7690405   : +16.36%  : 1.29%  : +0.0068% : ``FlowGraphNaturalLoops::Find'::`7'::<lambda_1>::operator()'::`2'::<lambda_1>::operator()                                                                                                                                                                                                                                                                                                                              
7617110   : +5.67%   : 1.28%  : +0.0068% : public: unsigned __int64 *& __cdecl Compiler::GetAssertionDep(unsigned int)                                                                                                                                                                                                                                                                                                                                            
7042984   : +17.02%  : 1.18%  : +0.0063% : public: void __cdecl jitstd::vector<struct FlowEdge *, class jitstd::allocator<struct FlowEdge *>>::push_back(struct FlowEdge *const &)                                                                                                                                                                                                                                                                                
6990972   : +4.92%   : 1.17%  : +0.0062% : private: void __cdecl JitHashTable<struct CORINFO_FIELD_STRUCT_*, struct JitPtrKeyFuncs<struct CORINFO_FIELD_STRUCT_>, class FieldSeq, class CompAllocator, class JitHashTableBehavior>::Grow(void)                                                                                                                                                                                                                    
6856730   : +2.49%   : 1.15%  : +0.0061% : protected: void __cdecl JitExpandArray<struct ValueNumStore::Chunk *>::EnsureCoversInd(unsigned int)                                                                                                                                                                                                                                                                                                                   
6808622   : +0.27%   : 1.14%  : +0.0061% : public: void * __cdecl ArenaAllocator::allocateMemory(unsigned __int64)                                                                                                                                                                                                                                                                                                                                                
4740058   : NA       : 0.80%  : +0.0042% : private: class JitHashTable<unsigned int, struct JitSmallPrimitiveKeyFuncs<unsigned int>, bool, class CompAllocator, class JitHashTableBehavior> * __cdecl LoopDefinitions::GetOrCreate(class FlowGraphNaturalLoop *)                                                                                                                                                                                                  
4487636   : +7.96%   : 0.75%  : +0.0040% : public: struct FlowEdge * __cdecl Compiler::BlockPredsWithEH(struct BasicBlock *)                                                                                                                                                                                                                                                                                                                                      
2789013   : NA       : 0.47%  : +0.0025% : private: void __cdecl LoopDefinitions::IncludeIntoParent(class FlowGraphNaturalLoop *)                                                                                                                                                                                                                                                                                                                                 
2391038   : +10.76%  : 0.40%  : +0.0021% : public: unsigned short __cdecl Compiler::optAssertionIsSubrange(struct GenTree *, class IntegralRange, unsigned __int64 *const &)                                                                                                                                                                                                                                                                                      
1756909   : +1.16%   : 0.30%  : +0.0016% : public: struct BasicBlock * __cdecl Compiler::fgFindInsertPoint(unsigned int, bool, struct BasicBlock *, struct BasicBlock *, struct BasicBlock *, struct BasicBlock *, bool)                                                                                                                                                                                                                                          
1726162   : +0.60%   : 0.29%  : +0.0015% : void __cdecl DoPhase(class Compiler *, enum Phases, enum PhaseStatus (__cdecl Compiler::*)(void))                                                                                                                                                                                                                                                                                                                      
1262251   : +1.30%   : 0.21%  : +0.0011% : public: void __cdecl emitter::emitUpdateLiveGCvars(unsigned __int64 *const &, unsigned char *)                                                                                                                                                                                                                                                                                                                         
1197536   : +0.56%   : 0.20%  : +0.0011% : public: void __cdecl DataFlow::ForwardAnalysis<class AssertionPropFlowCallback>(class AssertionPropFlowCallback &)                                                                                                                                                                                                                                                                                                     
1092300   : +0.75%   : 0.18%  : +0.0010% : public: static unsigned __int64 * __cdecl BitSetOps<unsigned __int64 *, 1, struct BitVecTraits *, struct BitVecTraits>::MakeCopy(struct BitVecTraits *, unsigned __int64 *)                                                                                                                                                                                                                                            
1091640   : +0.60%   : 0.18%  : +0.0010% : public: static void __cdecl BitSetOps<unsigned __int64 *, 1, struct BitVecTraits *, struct BitVecTraits>::IntersectionD(struct BitVecTraits *, unsigned __int64 *&, unsigned __int64 *)                                                                                                                                                                                                                                
998077    : +0.15%   : 0.17%  : +0.0009% : public: struct GenTree * __cdecl Compiler::optAssertionProp(unsigned __int64 *const &, struct GenTree *, struct Statement *, struct BasicBlock *)                                                                                                                                                                                                                                                                      
877097    : +5.01%   : 0.15%  : +0.0008% : private: void __cdecl Compiler::fgKillDependentAssertionsSingle(unsigned int)                                                                                                                                                                                                                                                                                                                                          
607243    : NA       : 0.10%  : +0.0005% : public: enum PhaseStatus __cdecl Compiler::optFindLoopsBeforeMorph(void)                                                                                                                                                                                                                                                                                                                                               
-608014   : -1.10%   : 0.10%  : -0.0005% : private: void __cdecl TreeLifeUpdater<0>::UpdateLifeBit(unsigned __int64 *&, class LclVarDsc *, bool, bool)                                                                                                                                                                                                                                                                                                            
-609946   : -0.18%   : 0.10%  : -0.0005% : protected: void __cdecl Compiler::lvaMarkLclRefs(struct GenTree *, struct BasicBlock *, struct Statement *, bool)                                                                                                                                                                                                                                                                                                      
-611481   : -0.13%   : 0.10%  : -0.0005% : protected: enum _regNumber_enum __cdecl CodeGen::genConsumeReg(struct GenTree *)                                                                                                                                                                                                                                                                                                                                       
-622483   : -0.72%   : 0.10%  : -0.0006% : private: void __cdecl SsaBuilder::RenameDef(struct GenTree *, struct BasicBlock *)                                                                                                                                                                                                                                                                                                                                     
-626125   : -1.41%   : 0.11%  : -0.0006% : public: bool __cdecl LclVarDsc_BlendedCode_Less::operator()(unsigned int, unsigned int)                                                                                                                                                                                                                                                                                                                                
-627620   : -0.16%   : 0.11%  : -0.0006% : GenTreeVisitor<`Compiler::lvaMarkLocalVars'::`2'::MarkLocalVarsVisitor>::WalkTree                                                                                                                                                                                                                                                                                                                                      
-658788   : -0.46%   : 0.11%  : -0.0006% : BasicBlock::VisitAllSuccs<`Compiler::optReachable'::`12'::<lambda_1> >                                                                                                                                                                                                                                                                                                                                                 
-660765   : -0.22%   : 0.11%  : -0.0006% : public: void __cdecl LclVarDsc::incRefCnts(double, class Compiler *, enum RefCountState, bool)                                                                                                                                                                                                                                                                                                                         
-681874   : -0.13%   : 0.11%  : -0.0006% : public: void __cdecl Compiler::optRelopImpliesRelop(struct RelopImplicationInfo *)                                                                                                                                                                                                                                                                                                                                     
-682823   : -0.18%   : 0.11%  : -0.0006% : public: void __cdecl ArrayStack<struct Scev *>::Push(struct Scev *)                                                                                                                                                                                                                                                                                                                                                    
-684734   : -1.04%   : 0.12%  : -0.0006% : private: unsigned int __cdecl SsaBuilder::RenamePushDef(struct GenTree *, struct BasicBlock *, unsigned int, bool)                                                                                                                                                                                                                                                                                                     
-697532   : -0.81%   : 0.12%  : -0.0006% : private: void __cdecl Lowering::LowerStoreLocCommon(struct GenTreeLclVarCommon *)                                                                                                                                                                                                                                                                                                                                      
-709029   : -0.12%   : 0.12%  : -0.0006% : GenTreeVisitor<`Rationalizer::DoPhase'::`2'::RationalizeVisitor>::WalkTree                                                                                                                                                                                                                                                                                                                                             
-720126   : -0.57%   : 0.12%  : -0.0006% : public: void __cdecl Compiler::compChangeLife<1>(unsigned __int64 *const &)                                                                                                                                                                                                                                                                                                                                            
-727975   : -0.68%   : 0.12%  : -0.0006% : protected: void __cdecl CodeGen::genCodeForStoreLclVar(struct GenTreeLclVar *)                                                                                                                                                                                                                                                                                                                                         
-731548   : -0.28%   : 0.12%  : -0.0007% : private: void __cdecl LinearScan::unassignPhysReg(class RegRecord *, class RefPosition *)                                                                                                                                                                                                                                                                                                                              
-748124   : -0.20%   : 0.13%  : -0.0007% : private: struct GenTree * __cdecl Lowering::LowerNode(struct GenTree *)                                                                                                                                                                                                                                                                                                                                                
-750160   : -0.26%   : 0.13%  : -0.0007% : public: void __cdecl RangeCheck::MergeEdgeAssertions(unsigned int, unsigned __int64 *const &, struct Range *)                                                                                                                                                                                                                                                                                                          
-754720   : -0.07%   : 0.13%  : -0.0007% : private: class RefPosition * __cdecl LinearScan::newRefPositionRaw(unsigned int, struct GenTree *, enum RefType)                                                                                                                                                                                                                                                                                                       
-769534   : -2.99%   : 0.13%  : -0.0007% : GenTreeVisitor<`FlowGraphNaturalLoop::VisitDefs<`FlowGraphNaturalLoop::HasDef'::`2'::<lambda_1> >'::`2'::VisitDefsVisitor>::WalkTree                                                                                                                                                                                                                                                                                   
-788560   : -0.46%   : 0.13%  : -0.0007% : public: void __cdecl Compiler::fgValueNumberAddExceptionSetForIndirection(struct GenTree *, struct GenTree *)                                                                                                                                                                                                                                                                                                          
-797664   : -0.55%   : 0.13%  : -0.0007% : public: unsigned short __cdecl Compiler::optGlobalAssertionIsEqualOrNotEqualZero(unsigned __int64 *const &, struct GenTree *)                                                                                                                                                                                                                                                                                          
-816960   : -0.28%   : 0.14%  : -0.0007% : private: void __cdecl LinearScan::updateAssignedInterval(class RegRecord *, class Interval *)                                                                                                                                                                                                                                                                                                                          
-820336   : -0.29%   : 0.14%  : -0.0007% : private: double __cdecl LinearScan::getWeight(class RefPosition *)                                                                                                                                                                                                                                                                                                                                                     
-828312   : -0.42%   : 0.14%  : -0.0007% : public: unsigned int __cdecl ValueNumStore::VNWithExc(unsigned int, unsigned int)                                                                                                                                                                                                                                                                                                                                      
-830745   : -0.45%   : 0.14%  : -0.0007% : public: bool __cdecl Compiler::fgComputeLifeTrackedLocalDef(unsigned __int64 *&, unsigned __int64 *const &, class LclVarDsc &, struct GenTreeLclVarCommon *)                                                                                                                                                                                                                                                           
-832412   : -0.13%   : 0.14%  : -0.0007% : protected: void __cdecl CodeGen::genCodeForTreeNode(struct GenTree *)                                                                                                                                                                                                                                                                                                                                                  
-850531   : -0.26%   : 0.14%  : -0.0008% : private: void __cdecl SsaBuilder::ComputeIteratedDominanceFrontier(struct BasicBlock *, class JitHashTable<struct BasicBlock *, struct JitPtrKeyFuncs<struct BasicBlock>, class jitstd::vector<struct BasicBlock *, class jitstd::allocator<struct BasicBlock *>>, class CompAllocator, class JitHashTableBehavior> const *, class jitstd::vector<struct BasicBlock *, class jitstd::allocator<struct BasicBlock *>> *)
-852755   : -0.84%   : 0.14%  : -0.0008% : private: void __cdecl TreeLifeUpdater<0>::UpdateLifeVar(struct GenTree *, struct GenTreeLclVarCommon *)                                                                                                                                                                                                                                                                                                                
-853320   : -0.47%   : 0.14%  : -0.0008% : public: enum PhaseStatus __cdecl Compiler::optVnCopyProp(void)                                                                                                                                                                                                                                                                                                                                                         
-856347   : -0.57%   : 0.14%  : -0.0008% : `Compiler::optReachable'::`12'::<lambda_1>::operator()                                                                                                                                                                                                                                                                                                                                                                 
-873710   : -0.42%   : 0.15%  : -0.0008% : public: void __cdecl Compiler::fgComputeLifeTrackedLocalUse(unsigned __int64 *&, class LclVarDsc &, struct GenTreeLclVarCommon *)                                                                                                                                                                                                                                                                                      
-888707   : -0.58%   : 0.15%  : -0.0008% : public: bool __cdecl GenTree::OperRequiresAsgFlag(void) const                                                                                                                                                                                                                                                                                                                                                          
-896057   : -0.12%   : 0.15%  : -0.0008% : private: void __cdecl LinearScan::associateRefPosWithInterval(class RefPosition *)                                                                                                                                                                                                                                                                                                                                     
-903618   : -0.23%   : 0.15%  : -0.0008% : public: static void __cdecl BitSetOps<unsigned __int64 *, 1, class Compiler *, class TrackedVarBitSetTraits>::Assign(class Compiler *, unsigned __int64 *&, unsigned __int64 *)                                                                                                                                                                                                                                        
-908318   : -0.89%   : 0.15%  : -0.0008% : public: static void __cdecl BitSetOps<unsigned __int64 *, 1, class Compiler *, class TrackedVarBitSetTraits>::IntersectionD(class Compiler *, unsigned __int64 *&, unsigned __int64 *)                                                                                                                                                                                                                                 
-912284   : -0.12%   : 0.15%  : -0.0008% : private: enum Compiler::fgWalkResult __cdecl Rationalizer::RewriteNode(struct GenTree **, class ArrayStack<struct GenTree *> &)                                                                                                                                                                                                                                                                                        
-955968   : -0.19%   : 0.16%  : -0.0009% : public: void __cdecl Compiler::fgPerNodeLocalVarLiveness(struct GenTree *)                                                                                                                                                                                                                                                                                                                                             
-960273   : -1.02%   : 0.16%  : -0.0009% : `Compiler::optCopyPropPushDef'::`2'::<lambda_1>::operator()                                                                                                                                                                                                                                                                                                                                                            
-963981   : -0.11%   : 0.16%  : -0.0009% : private: class RefPosition * __cdecl LinearScan::newRefPosition(class Interval *, unsigned int, enum RefType, struct GenTree *, unsigned __int64, unsigned int)                                                                                                                                                                                                                                                        
-964415   : -0.33%   : 0.16%  : -0.0009% : public: bool __cdecl CSE_HeuristicCommon::CanConsiderTree(struct GenTree *, bool)                                                                                                                                                                                                                                                                                                                                      
-1000761  : -0.31%   : 0.17%  : -0.0009% : private: void __cdecl SsaBuilder::BlockRenameVariables(struct BasicBlock *)                                                                                                                                                                                                                                                                                                                                            
-1013707  : -0.28%   : 0.17%  : -0.0009% : public: void __cdecl BitStreamWriter::Write(unsigned __int64, unsigned int)                                                                                                                                                                                                                                                                                                                                            
-1034921  : -0.29%   : 0.17%  : -0.0009% : private: struct GenTree * __cdecl Compiler::fgMorphSmpOpOptional(struct GenTreeOp *, bool *)                                                                                                                                                                                                                                                                                                                           
-1052574  : -0.21%   : 0.18%  : -0.0009% : public: struct GenTree * __cdecl Compiler::gtFoldExpr(struct GenTree *)                                                                                                                                                                                                                                                                                                                                                
-1068602  : -0.30%   : 0.18%  : -0.0010% : public: void __cdecl GCInfo::gcInfoRecordGCRegStateChange(class GcInfoEncoder *, enum GCInfo::MakeRegPtrMode, unsigned int, unsigned __int64, enum GcSlotState, unsigned __int64, unsigned __int64 *)                                                                                                                                                                                                                  
-1084130  : -0.18%   : 0.18%  : -0.0010% : public: void __cdecl LinearScan::resolveRegisters<1>(void)                                                                                                                                                                                                                                                                                                                                                             
-1133579  : -0.27%   : 0.19%  : -0.0010% : public: enum Compiler::fgWalkResult __cdecl GenTreeVisitor<class GenericTreeWalker<0, 1, 0, 1>>::WalkTree(struct GenTree **, struct GenTree *)                                                                                                                                                                                                                                                                         
-1156803  : -0.17%   : 0.19%  : -0.0010% : public: void __cdecl Compiler::fgPerBlockLocalVarLiveness(void)                                                                                                                                                                                                                                                                                                                                                        
-1167973  : -0.33%   : 0.20%  : -0.0010% : public: static void __cdecl BitSetOps<unsigned __int64 *, 1, class Compiler *, class TrackedVarBitSetTraits>::ClearD(class Compiler *, unsigned __int64 *&)                                                                                                                                                                                                                                                            
-1183520  : -0.18%   : 0.20%  : -0.0011% : private: int __cdecl LinearScan::BuildNode(struct GenTree *)                                                                                                                                                                                                                                                                                                                                                           
-1195905  : -0.28%   : 0.20%  : -0.0011% : public: void __cdecl Compiler::fgComputeLifeLIR(unsigned __int64 *&, struct BasicBlock *, unsigned __int64 *const &)                                                                                                                                                                                                                                                                                                   
-1199937  : -0.47%   : 0.20%  : -0.0011% : public: static unsigned __int64 * __cdecl BitSetOps<unsigned __int64 *, 1, class Compiler *, class TrackedVarBitSetTraits>::MakeCopy(class Compiler *, unsigned __int64 *)                                                                                                                                                                                                                                             
-1205123  : -8.82%   : 0.20%  : -0.0011% : GenTree::VisitOperands<`Compiler::gtUpdateNodeSideEffects'::`2'::<lambda_1> >                                                                                                                                                                                                                                                                                                                                          
-1209277  : -0.21%   : 0.20%  : -0.0011% : public: void __cdecl Compiler::fgInterBlockLocalVarLiveness(void)                                                                                                                                                                                                                                                                                                                                                      
-1217329  : -0.93%   : 0.20%  : -0.0011% : public: void __cdecl Compiler::fgValueNumberStore(struct GenTree *)                                                                                                                                                                                                                                                                                                                                                    
-1221639  : -0.52%   : 0.21%  : -0.0011% : public: void __cdecl Compiler::optImpliedByTypeOfAssertions(unsigned __int64 *&)                                                                                                                                                                                                                                                                                                                                       
-1228433  : -0.15%   : 0.21%  : -0.0011% : public: unsigned int __cdecl ValueNumStore::GetRelatedRelop(unsigned int, enum ValueNumStore::VN_RELATION_KIND)                                                                                                                                                                                                                                                                                                        
-1232533  : -0.66%   : 0.21%  : -0.0011% : public: bool __cdecl GenTree::OperRequiresCallFlag(class Compiler *) const                                                                                                                                                                                                                                                                                                                                             
-1235986  : -0.18%   : 0.21%  : -0.0011% : public: void __cdecl Compiler::optAssertionGen(struct GenTree *)                                                                                                                                                                                                                                                                                                                                                       
-1243059  : -0.09%   : 0.21%  : -0.0011% : private: void __cdecl LinearScan::processBlockStartLocations(struct BasicBlock *)                                                                                                                                                                                                                                                                                                                                      
-1275934  : -0.38%   : 0.21%  : -0.0011% : public: bool __cdecl Compiler::optBlockCopyProp(struct BasicBlock *, class JitHashTable<unsigned int, struct JitSmallPrimitiveKeyFuncs<unsigned int>, class ArrayStack<class Compiler::CopyPropSsaDef> *, class CompAllocator, class JitHashTableBehavior> *)                                                                                                                                                          
-1287710  : -0.33%   : 0.22%  : -0.0011% : public: enum PhaseStatus __cdecl Compiler::optAssertionPropMain(void)                                                                                                                                                                                                                                                                                                                                                  
-1323683  : -0.07%   : 0.22%  : -0.0012% : private: bool __cdecl LiveVarAnalysis::PerBlockAnalysis(struct BasicBlock *, bool, bool)                                                                                                                                                                                                                                                                                                                               
-1334023  : -0.15%   : 0.22%  : -0.0012% : protected: void __cdecl CodeGen::genCodeForBBlist(void)                                                                                                                                                                                                                                                                                                                                                                
-1342833  : -0.12%   : 0.23%  : -0.0012% : public: unsigned int __cdecl ValueNumStore::VNForFunc(enum var_types, enum VNFunc, unsigned int, unsigned int)                                                                                                                                                                                                                                                                                                         
-1377540  : -0.54%   : 0.23%  : -0.0012% : private: void __cdecl TreeLifeUpdater<1>::UpdateLifeVar(struct GenTree *, struct GenTreeLclVarCommon *)                                                                                                                                                                                                                                                                                                                
-1439915  : -0.43%   : 0.24%  : -0.0013% : private: void __cdecl JitHashTable<struct ValueNumStore::VNDefFuncApp<2>, struct ValueNumStore::VNDefFuncAppKeyFuncs<2>, class ValueNumStore::MapSelectWorkCacheEntry, class CompAllocator, class JitHashTableBehavior>::Grow(void)                                                                                                                                                                                    
-1446721  : -0.15%   : 0.24%  : -0.0013% : public: struct GenTree * __cdecl Compiler::fgMorphTree(struct GenTree *, struct Compiler::MorphAddrContext *)                                                                                                                                                                                                                                                                                                          
-1490280  : -15.30%  : 0.25%  : -0.0013% : public: struct GenTree * __cdecl GenTree::gtGetParent(struct GenTree ***)                                                                                                                                                                                                                                                                                                                                              
-1493144  : -0.56%   : 0.25%  : -0.0013% : public: struct GenTree * __cdecl Compiler::optVNBasedFoldConstExpr(struct BasicBlock *, struct GenTree *, struct GenTree *)                                                                                                                                                                                                                                                                                            
-1557526  : -0.36%   : 0.26%  : -0.0014% : public: unsigned int __cdecl ValueNumStore::VNForFuncNoFolding(enum var_types, enum VNFunc, unsigned int, unsigned int)                                                                                                                                                                                                                                                                                                
-1575805  : -0.34%   : 0.26%  : -0.0014% : public: void __cdecl LinearScan::buildIntervals<1>(void)                                                                                                                                                                                                                                                                                                                                                               
-1590226  : -0.18%   : 0.27%  : -0.0014% : GenTreeVisitor<`Compiler::fgSetTreeSeq'::`2'::SetTreeSeqVisitor>::WalkTree                                                                                                                                                                                                                                                                                                                                             
-1609905  : -0.49%   : 0.27%  : -0.0014% : private: void __cdecl LinearScan::resolveLocalRef(struct BasicBlock *, struct GenTreeLclVar *, class RefPosition *)                                                                                                                                                                                                                                                                                                    
-1654160  : -0.31%   : 0.28%  : -0.0015% : protected: static enum Compiler::fgWalkResult __cdecl Compiler::optVNAssertionPropCurStmtVisitor(struct GenTree **, struct Compiler::fgWalkData *)                                                                                                                                                                                                                                                                     
-1912378  : -0.31%   : 0.32%  : -0.0017% : private: void __cdecl Compiler::fgMarkUseDef(struct GenTreeLclVarCommon *)                                                                                                                                                                                                                                                                                                                                             
-1949501  : -0.32%   : 0.33%  : -0.0017% : public: unsigned short __cdecl Compiler::optAddAssertion(struct Compiler::AssertionDsc *)                                                                                                                                                                                                                                                                                                                              
-1953507  : -0.56%   : 0.33%  : -0.0017% : public: enum ExceptionSetFlags __cdecl GenTree::OperExceptions(class Compiler *)                                                                                                                                                                                                                                                                                                                                       
-1989966  : -0.40%   : 0.33%  : -0.0018% : public: static void __cdecl BitSetOps<unsigned __int64 *, 1, class Compiler *, class TrackedVarBitSetTraits>::UnionD(class Compiler *, unsigned __int64 *&, unsigned __int64 *)                                                                                                                                                                                                                                        
-1998547  : -0.80%   : 0.34%  : -0.0018% : private: static void __cdecl BitSetOps<unsigned __int64 *, 1, class Compiler *, class TrackedVarBitSetTraits>::LivenessDLong(class Compiler *, unsigned __int64 *&, unsigned __int64 *const, unsigned __int64 *const, unsigned __int64 *const)                                                                                                                                                                         
-2006070  : -0.92%   : 0.34%  : -0.0018% : jitstd::`anonymous namespace'::insertion_sort<unsigned int *,LclVarDsc_BlendedCode_Less>                                                                                                                                                                                                                                                                                                                               
-2191364  : -0.31%   : 0.37%  : -0.0019% : public: void __cdecl Compiler::lvaComputeRefCounts(bool, bool)                                                                                                                                                                                                                                                                                                                                                         
-2361802  : -0.35%   : 0.40%  : -0.0021% : public: void __cdecl Compiler::fgValueNumberTree(struct GenTree *)                                                                                                                                                                                                                                                                                                                                                     
-2654387  : -0.15%   : 0.45%  : -0.0024% : public: void __cdecl LinearScan::allocateRegisters(void)                                                                                                                                                                                                                                                                                                                                                               
-2746197  : -0.92%   : 0.46%  : -0.0024% : public: void __cdecl Compiler::gtUpdateNodeOperSideEffects(struct GenTree *)                                                                                                                                                                                                                                                                                                                                           
-2871960  : -6.88%   : 0.48%  : -0.0026% : GenTreeVisitor<`Compiler::gtFindLink'::`2'::FindLinkWalker>::WalkTree                                                                                                                                                                                                                                                                                                                                                  
-4092109  : -0.23%   : 0.69%  : -0.0036% : public: unsigned int __cdecl Compiler::gtSetEvalOrder(struct GenTree *)                                                                                                                                                                                                                                                                                                                                                
-4129733  : -0.27%   : 0.69%  : -0.0037% : private: struct GenTree * __cdecl Compiler::fgMorphSmpOp(struct GenTree *, struct Compiler::MorphAddrContext *, bool *)                                                                                                                                                                                                                                                                                                
-4454312  : -0.27%   : 0.75%  : -0.0040% : public: unsigned __int64 __cdecl LinearScan::RegisterSelection::select<0>(class Interval *, class RefPosition *)                                                                                                                                                                                                                                                                                                       
-5145418  : -1.35%   : 0.86%  : -0.0046% : jitstd::`anonymous namespace'::quick_sort<unsigned int *,LclVarDsc_BlendedCode_Less>                                                                                                                                                                                                                                                                                                                                   
-5903508  : -1.77%   : 0.99%  : -0.0053% : public: virtual enum PhaseStatus __cdecl LinearScan::doLinearScan(void)                                                                                                                                                                                                                                                                                                                                                
-28719186 : -3.04%   : 4.82%  : -0.0256% : public: bool __cdecl Compiler::optCopyProp(struct BasicBlock *, struct Statement *, struct GenTreeLclVarCommon *, unsigned int, class JitHashTable<unsigned int, struct JitSmallPrimitiveKeyFuncs<unsigned int>, class ArrayStack<class Compiler::CopyPropSsaDef> *, class CompAllocator, class JitHashTableBehavior> *)                                                                                               
```
So looks like most of the cost actually comes from the new copy prop that is enabled. Loop finding and finding the definitions inside the loops looks quite cheap.

**Comment by jakobbotsch** [comment]
Diffs still seem pretty mixed, even with copy assertions removed. Odd.

**Comment by EgorBo** [comment]
> Diffs still seem pretty mixed, even with copy assertions removed. Odd.

My experience with assertprop changes is that we fairly often hit the limit of assertions allowed per method, so if you enable more assertions there is risk that some more useful assertions won't be added

**Comment by AndyAyersMS** [comment]
Local assertion prop scales up the table size differently than global, since we're not solving a global dataflow problem.

We should metric-ify `optAssertionOverflow` which counts how many assertions we could not create because of table size limits, and maybe split it into local/global.

**Pull request closed without merging**
