### PR TITLE
Update il range in optOptimizeBoolsUpdateTrees

### PR DESCRIPTION
**Pull request by En3Tho**
Possible fix for https://github.com/dotnet/runtime/issues/49471

### CODE REVIEW

**Comment by En3Tho** [comment]
``` csharp
static int TestBasicBlocks(int x, int y)
    {
        if (x == 0 && y == 0)
        {
            return 0;
        }

        return 2;
    }
```

```
*************** Finishing PHASE Find loops
Trees after Find loops

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..003)-> BB04 ( cond )                     i 
BB02 [0001]  1       BB01                  0.50    [003..006)-> BB04 ( cond )                     i 
BB03 [0002]  1       BB02                  0.50    [006..008)        (return)                     i 
BB04 [0003]  2       BB01,BB02             0.50    [008..00A)        (return)                     i 
-----------------------------------------------------------------------------------------------------------------------------------------
```

=>

```
*************** Finishing PHASE Optimize bools
Trees after Optimize bools

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..006)-> BB04 ( cond )                     i 
BB03 [0002]  1       BB01                  0.50    [006..008)        (return)                     i 
BB04 [0003]  1       BB01                  0.50    [008..00A)        (return)                     i 
-----------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by En3Tho** [comment]
Should an assert be added somewhere after OptimizeBools?
To check that basic blocks ranges are correctly updated

**Comment by JulieLeeMSFT** [comment]
Thanks @En3Tho for the PR. We are now busy with finishing up .NET 7. @EgorBo, Please review this community contribution.

**Comment by En3Tho** [comment]
Can someone review this please?

**Comment by EgorBo** [comment]
Looks good to me, could you please check what it returns for:
```
static int TestBasicBlocks(int x, int y)
    {
        return x == 0 && y == 0;
    }
```

**Comment by En3Tho** [comment]
@EgorBo I changed you example to

``` csharp
public static bool TestBasicBlocks2(int x, int y) => x == 0 && y == 0;
```

I hope you meant this.

With PR:
```
*************** Finishing PHASE Optimize bools
Trees after Optimize bools

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..00A)        (return)                     i 
-----------------------------------------------------------------------------------------------------------------------------------------
```

Without: 
```
*************** Finishing PHASE Optimize bools
Trees after Optimize bools

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..003)        (return)                     i 
-----------------------------------------------------------------------------------------------------------------------------------------
```

It seems to be correctly updated to 000..00A

For example this is how it looks few phases before:
```
*************** Finishing PHASE Find loops
Trees after Find loops

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..003)-> BB03 ( cond )                     i 
BB02 [0001]  1       BB01                  0.50    [003..008)        (return)                     i 
BB03 [0002]  1       BB01                  0.50    [008..00A)        (return)                     i 
-----------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by EgorBo** [comment]
Thanks for your contribution!

**Review by EgorBo — APPROVED** [review]

**Pull request merged**
