### PR TITLE
Reverse P/Invoke methods do not support tailcalls.

### LINKED ISSUE #33663: Test failure: Interop\\NativeCallable\\NativeCallableTest\\NativeCallableTest.cmd
failed in job: [runtime-coreclr jitstress 20200315.1](https://dev.azure.com/dnceng/public/_build/results?buildId=560455&view=ms.vss-test-web.build-test-results-tab&runId=17650420&resultId=100828&paneView=debug)

error message:
```
Assert failure(PID 1532 [0x000005fc], Thread: 5560 [0x15b8]): !PreemptiveGCDisabled()
CORECLR! Thread::DetachThread + 0x112 (0x00007ffce57d0d6e)
CORECLR!EEDllMain'::5'::__Body::Run + 0x143 (0x00007ffce5696997)
CORECLR! EEDllMain + 0x2A (0x00007ffce5692d52)
CORECLR! DllMain + 0x37 (0x00007ffce562bfaf)
CORECLR! CoreDllMain + 0x9F (0x00007ffce562bf4f)
NTDLL! RtlDeactivateActivationContextUnsafeFast + 0x1BF (0x00007ffd149c38ff)
NTDLL! LdrShutdownThread + 0x151 (0x00007ffd149c0f91)
NTDLL! RtlExitUserThread + 0x3E (0x00007ffd149ab07e)
KERNELBASE! FreeLibraryAndExitThread + 0x43 (0x00007ffd10efb8f3)
KERNEL32! FreeLibraryAndExitThread + 0xA (0x00007ffd1271fb1a)
File: F:\workspace\_work\1\s\src\coreclr\src\vm\threads.cpp Line: 928
Image: C:\h\w\96D90843\p\CoreRun.exe
Return code: 1
Raw output file: C:\h\w\96D90843\w\C2590A16\e\Interop\NativeCallable\Reports\Interop.NativeCallable\NativeCallableTest\NativeCallableTest.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\96D90843\p\corerun.exe" NativeCallableTest.dll
Running TestNativeCallableValid...
Running TestNativeCallableValid_OnNewNativeThread...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\96D90843\p
> C:\h\w\96D90843\w\C2590A16\e\Interop\NativeCallable\NativeCallableTest\NativeCallableTest.cmd
Expected: True
Actual: False


Stack trace:
at Interop_NativeCallable._NativeCallableTest_NativeCallableTest_._NativeCallableTest_NativeCallableTest_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\Interop.NativeCallable\Interop.NativeCallable.XUnitWrapper.cs:line 140
```

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes https://github.com/dotnet/runtime/issues/33663

The change here was the most obvious way to address the associated issue. I am open to other more general ways though. It also doesn't look like this will generally block the tailcall prefix, which is what I was hoping for. I was thinking that if the JIT is compiling Reverse P/Invoke and discovered the prefix then it should throw something, but I am unsure if that is correct so I opted for the minimal.

/cc @dotnet/jit-contrib

### CODE REVIEW

**Comment by davidwrighton** [comment]
I don't think this addresses the issue at all. We don't always compile with tiVerificationNeeded set (in fact its pretty rare), and the check you've wrote is tied to the tail. prefix, not to optimization triggered tail calls. Instead I would add a check to impImportCall just before the call to canTailCall, and if the method is a reverse p/invoke prevent it at that time.

**Comment by jkotas** [comment]
I believe that the right place for this check is `Compiler::impIsImplicitTailCallCandidate`

**Comment by jashook** [comment]
We should not limit it to implicit tailcalls correct? This issue came from tailcall stress, which will force explicit tailcalls.

**Comment by jkotas** [comment]
This should mirror the handling of synchronized methods that have the same fundamental limitations. So this would mean to add the check to:

- `Compiler::impImportCall` next to `if (info.compFlags & CORINFO_FLG_SYNCH)`
- `Compiler::fgMayExplicitTailCall`

**Comment by jkotas** [comment]
And also to `Compiler::fgTransformPatchpoints`

**Comment by jkotas** [comment]
And to `case CEE_JMP:` in importer.cpp

**Comment by AaronRobinsonMSFT** [comment]
The only validation I performed was that COMPlus_TailcallStress=1 no longer fails. That basically aligns with @jashook’s comment. Will investigate other suggested places.

**Comment by AaronRobinsonMSFT** [comment]
@dotnet/jit-contrib @jashook I think there is an issue with the formatting script: https://github.com/dotnet/runtime/pull/33677/checks?check_run_id=514968712. The error is:

> ##[error]Parameter 'toolPath' cannot be null or empty.

**Review by jkotas — APPROVED** [review]

**Comment by jashook** [comment]
@BruceForstall

**Review by jashook — APPROVED** [review]
lgtm

**Comment by AaronRobinsonMSFT** [comment]
Formatting failure is unrelated to this PR.

**Pull request merged**
