### PR TITLE
[6.0] Modify thread pool thread counting to be a bit more defensive

### PR DESCRIPTION
**Pull request by kouvel**
- Port of https://github.com/dotnet/runtime/pull/70478 to 6.0
- An unexpected underflow in one or more thread counts can lead to a large number of threads to be created continually
- Prevented underflows in changes to thread counts, such that following an unexpected underflow, subsequent paired increments and decrements would avoid repeating the underflow
- Verified by creating an unexpected underflow in the debugger

## Customer Impact

It was seen a few times that when all worker threads have exited, somehow there is a decrement on the tracked thread counts, which leads to some counts going negative. As work is queued to the thread pool thereafter, this leads to additional threads being created and for the underflow to repeat when those threads run out of work. Combined with hill climbing frequently resetting the desired count of threads, the issue keeps repeating and more and more worker threads are created. The issue appears to be very rare, but when it occurs, it can lead to the process accumulating >> 100K threads over a relatively short span of time, and with a large amount of CPU time spent in spinning up and tearing down worker threads. This is a defensive fix to have the thread pool behave less erratically in the event of an unexpected underflow.

## Regression?

The issue started happening in .NET 6 with the portable thread pool. The reason for the unexpected underflow being seen is not clear. There doesn't appear to be a realistic possibility of underflow in the source code or generated machine code. Whether it is a regression is unclear at the moment.

## Testing

Verified the issue and fix by creating an unexpected underflow in the debugger and monitoring the process thread count following that.

## Risk

Low - If there is no underflow, the behavior is the same as before.

### CODE REVIEW

**Review by janvorli — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  We will take for consideration in 6.0.x

**Comment by jeffschwMSFT** [comment]
@kouvel/ @mangod9  thoughts on the failures?

**Comment by mangod9** [comment]
both are failing with Helix queue issues: 

`SENDHELIXJOB(0,0): error : Helix queue windows.11.amd64.clientpre.open is set for estimated removal date of 2022-06-16` 

I will retry if this is somehow intermittent.

**Comment by mangod9** [comment]
This would need backport of https://github.com/dotnet/runtime/pull/69871 looks like

**Comment by mangod9** [comment]
PR for the infra change is here: https://github.com/dotnet/runtime/pull/70570. @jeffschwMSFT since this is only a infra change hoping doesnt need a full approval process.

**Comment by carlossanlop** [comment]
@mangod9 I'll merge the [helix PR](https://github.com/dotnet/runtime/pull/70570) first, then I will retry the failed CI legs in this PR.

**Review by mangod9 — APPROVED** [review]

**Pull request merged**
