### PR TITLE
JIT: more fixes for VN loop dependence tracking

### LINKED ISSUE #56174: `kind == Overwrite` assert in jitstress
The failures look like:
```
      Assert failure(PID 1028 [0x00000404], Thread: 3768 [0x0eb8]): Assertion failed 'kind == Overwrite' in 'Microsoft.CodeAnalysis.CodeGen.ILBuilder:RealizeBlocks():this' during 'Do value numbering' (IL size 537)
      
          File: D:\workspace\_work\1\s\src\coreclr\jit\jithashtable.h Line: 238
```

and are common for all platforms, they appeared in https://dev.azure.com/dnceng/public/_build/results?buildId=1252387&view=ms.vss-test-web.build-test-results-tab, changes in that batch https://dev.azure.com/dnceng/public/_traceability/runview/changes?currentRunId=1252387

PTAL @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Specify `Overwrite` when setting loop dependence map entries, as we may
refine the initial result.

Fixes #56174.

Extract loop dependence of `VNF_PhiMemoryDef`.

Fixes new case noted in #55936, and 13/16 or so other cases Jakob sent
me privately. Also update a comment and fix tests to work better with
jitstress per other notes on that PR.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @jakobbotsch @dotnet/jit-contrib 

No spmi diffs.

**Review by BruceForstall — APPROVED** [review]

**Review by briansull — APPROVED** [review]
Looks Good

**Comment by AndyAyersMS** [comment]
@jakobbotsch by my accounting this fixes all the test cases you sent me except for these 3:

```
11656046881568048475.cs
2692166044414030864.cs
11738605779775786426.cs (hits jit assert)
```

I have not looked into these failures.

**Review by jakobbotsch — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
The assert in that other test:
```
corerun.exe 11738605779775786426.exe

Assert failure(PID 20200 [0x00004ee8], Thread: 24136 [0x5e48]): Assertion failed 'i < BitSetTraits::GetSize(env)' 
   in 'Program:Main()' during 'Compute blocks reachability' (IL size 41)
```

**Comment by AndyAyersMS** [comment]
Looks like a flow opts bug, we end up not updating the pred list for BB08 properly and this ultimately leaves a dangling reference from BB07 to BB08 which causes the assert above.
```
*************** In fgUpdateFlowGraph()
Before updating the flow graph:

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..007)-> BB10 (always)                     i 
BB02 [0001]  1       BB10                  1       [007..00E)-> BB07 ( cond )                     i bwd bwd-target 
BB03 [0002]  1       BB02                  1       [00E..010)-> BB04 (always)                     keep i bwd 
BB04 [0009]  1       BB03                  1       [???..???)-> BB06 (always)                     i internal 
BB05 [0010]  0                             1       [???..???)-> BB09 (always)                     i internal 
BB06 [0003]  1       BB04                  1       [010..013)-> BB09 (always)                     keep i bwd 
BB07 [0004]  1       BB02                  1       [013..01A)-> BB09 ( cond )                     i bwd 
BB08 [0005]  1       BB07                  1       [01A..020)                                     i bwd 
BB09 [0006]  4       BB05,BB06,BB07,BB08   1       [020..024)                                     i bwd 
BB10 [0007]  2       BB01,BB09             1       [024..028)-> BB02 ( cond )                     i bwd 
BB11 [0008]  1       BB10                  1       [028..029)        (return)                     i 
-----------------------------------------------------------------------------------------------------------------------------------------


Removing unconditional jump to next block (BB03 -> BB04) (converted BB03 to fall-through)

Compacting blocks BB03 and BB04:
*************** In fgDebugCheckBBlist

Optimizing a jump to an unconditional jump (BB03 -> BB06 -> BB09)
Setting edge weights for BB03 -> BB09 to [0 .. 3.402823e+38]
fgRemoveBlock BB05

Removing unreachable BB05

Compacting blocks BB08 and BB09:
Second block has multiple incoming edges
Setting edge weights for BB03 -> BB08 to [0 .. 3.402823e+38]
Setting edge weights for BB06 -> BB08 to [0 .. 3.402823e+38]
*************** In fgDebugCheckBBlist

Moving BB07 after BB03 to enable reversal
New Basic Block BB12 [0011] created.
Setting edge weights for BB07 -> BB12 to [0 .. 3.402823e+38]

Reversing a conditional jump around an unconditional jump (BB02 -> BB07, BB03 -> BB08)
Setting edge weights for BB02 -> BB08 to [0 .. 3.402823e+38]

After reversing the jump:

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..007)-> BB10 (always)                     i 
BB02 [0001]  1       BB10                  1       [007..00E)-> BB08 ( cond )                     i bwd bwd-target 
BB07 [0004]  1       BB02                  1       [013..01A)-> BB08 ( cond )                     i bwd 
BB12 [0011]  1       BB07                  1       [???..???)-> BB08 (always)                     internal 
BB06 [0003]  0                             1       [010..013)-> BB08 (always)                     keep i bwd 
BB08 [0005]  4       BB02,BB06,BB12(2)     1       [01A..024)                                     i bwd 
BB10 [0007]  2       BB01,BB08             1       [024..028)-> BB02 ( cond )                     i bwd 
BB11 [0008]  1       BB10                  1       [028..029)        (return)                     i 
-----------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by AndyAyersMS** [comment]
The bug is here:

https://github.com/dotnet/runtime/blob/eb1e55e3ce30ca77e490324a0c3b60ab99ae66b0/src/coreclr/jit/fgopt.cpp#L5620-L5629

`fgReplacePred` will replace all pred uses, when we only wanted to replace one of them
```
Compacting blocks BB08 and BB09:
Second block has multiple incoming edges
Setting edge weights for BB03 -> BB08 to [0 .. 3.402823e+38]
Setting edge weights for BB06 -> BB08 to [0 .. 3.402823e+38]
*************** In fgDebugCheckBBlist

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..007)-> BB10 (always)                     i 
BB02 [0001]  1       BB10                  1       [007..00E)-> BB07 ( cond )                     i bwd bwd-target 
BB03 [0002]  1       BB02                  1       [00E..010)-> BB08 (always)                     keep i bwd 
BB06 [0003]  0                             1       [010..013)-> BB08 (always)                     keep i bwd 
BB07 [0004]  1       BB02                  1       [013..01A)-> BB08 ( cond )                     i bwd 
BB08 [0005]  4       BB03,BB06,BB07(2)     1       [01A..024)                                     i bwd 
BB10 [0007]  2       BB01,BB08             1       [024..028)-> BB02 ( cond )                     i bwd 
BB11 [0008]  1       BB10                  1       [028..029)        (return)                     i 
-----------------------------------------------------------------------------------------------------------------------------------------

Moving BB07 after BB03 to enable reversal
New Basic Block BB12 [0011] created.
Setting edge weights for BB07 -> BB12 to [0 .. 3.402823e+38]

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..007)-> BB10 (always)                     i 
BB02 [0001]  1       BB10                  1       [007..00E)-> BB07 ( cond )                     i bwd bwd-target 
BB03 [0002]  1       BB02                  1       [00E..010)-> BB08 (always)                     keep i bwd 
BB07 [0004]  1       BB02                  1       [013..01A)-> BB08 ( cond )                     i bwd 
BB12 [0011]  1       BB07                  1       [???..???)-> BB08 (always)                     internal 
BB06 [0003]  0                             1       [010..013)-> BB08 (always)                     keep i bwd 
BB08 [0005]  4       BB03,BB06,BB12(2)     1       [01A..024)                                     i bwd 
BB10 [0007]  2       BB01,BB08             1       [024..028)-> BB02 ( cond )                     i bwd 
BB11 [0008]  1       BB10                  1       [028..029)        (return)                     i 
-----------------------------------------------------------------------------------------------------------------------------------------

Reversing a conditional jump around an unconditional jump (BB02 -> BB07, BB03 -> BB08)
Setting edge weights for BB02 -> BB08 to [0 .. 3.402823e+38]

After reversing the jump:

-----------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    lp [IL range]     [jump]      [EH region]         [flags]
-----------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1       [000..007)-> BB10 (always)                     i 
BB02 [0001]  1       BB10                  1       [007..00E)-> BB08 ( cond )                     i bwd bwd-target 
BB07 [0004]  1       BB02                  1       [013..01A)-> BB08 ( cond )                     i bwd 
BB12 [0011]  1       BB07                  1       [???..???)-> BB08 (always)                     internal 
BB06 [0003]  0                             1       [010..013)-> BB08 (always)                     keep i bwd 
BB08 [0005]  4       BB02,BB06,BB12(2)     1       [01A..024)                                     i bwd 
BB10 [0007]  2       BB01,BB08             1       [024..028)-> BB02 ( cond )                     i bwd 
BB11 [0008]  1       BB10                  1       [028..029)        (return)                     i 
-----------------------------------------------------------------------------------------------------------------------------------------
```

This is new code that I added, I'll open a fresh issue for this...

**Pull request merged**
