### PR TITLE
UnixFileMode: address remaining feedback.

### PR DESCRIPTION
**Pull request by tmds**
This addresses the open comments of https://github.com/dotnet/runtime/pull/69980.

cc @eerhardt @dotnet/area-system-io

### CODE REVIEW

**Comment by am11** [comment]
Looks like `SystemNative_FChMod` entrypoint is now unused and can be deleted.

**Comment by tmds** [comment]
> Looks like SystemNative_FChMod entrypoint is now unused and can be deleted.

It's used here:

https://github.com/dotnet/runtime/blob/b1221494186e7b8e5199d892dae76481a52f5935/src/libraries/System.Private.CoreLib/src/System/IO/FileStatus.Unix.cs#L447-L448

And it's available publicly now via the new `File.SetUnixFileMode(SafeFileHandle fileHandle, UnixFileMode mode)`.

**Comment by am11** [comment]
Ah, I didn't pulled changes from main.

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @tmds !

**Review by stephentoub — COMMENTED** [review]
Thanks

**Review by eerhardt — COMMENTED** [review]
Thanks @tmds!

**Pull request merged**
