### PR TITLE
Add back the ILStub cache hit event.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
/cc @jkoritzinsky @elinor-fung @sywhang

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jkotas** [comment]
Is there a good reason to add it back?

**Comment by AaronRobinsonMSFT** [comment]
>Is there a good reason to add it back?

I have previously found it useful when investigating issues on .NET Framework. I do not have a specific need right now. Bringing this back was precipitated by updating the documentation for events - see https://github.com/dotnet/docs/pull/20817. If there is a concern about adding these events now we can defer until a specific need is found.

**Comment by jkotas** [comment]
I think we should be adding diagnostic events only when we have a scenario for them, not just because we can.

**Comment by AaronRobinsonMSFT** [comment]
>I think we should be adding diagnostic events only when we have a scenario for them, not just because we can.

Agree.

I don't think this is a "because we can" situation though. This event along with the `ILStubGenerated` event are apart of the same sub-system and closely related. The `ILStubGenerated` was re-added when [COM support was being brought back](https://github.com/dotnet/coreclr/pull/20670) and this event was missed - both were originally missing from CoreCLR. I consider this PR to be ensuring diagnostics regarding interop in .NET Framework have symmetry in CoreCLR.

I accept that not adding it may make sense since no one seems to have reported a concern about its absence. If the above argument doesn't convince anyone I will close the PR.

**Comment by jkotas** [comment]
If this even was not in .NET Framework, would you add it to CoreCLR?

Events are like APIs. For APIs, we are done with porting  from .NET Framework and look at each addition as if it never existed.

**Pull request closed without merging**
