### PR TITLE
Fix Enum field type bug found when underlying type is set from assembly loaded with MLC

### PR DESCRIPTION
**Pull request by buyaa-n**
`EnumBuilder.UnderlyingSystemType`, currently [returns](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Reflection.Emit/src/System/Reflection/Emit/EnumBuilderImpl.cs#L74-L76) `GetEnumUnderlyingType()` which returns `_underlyingField.FieldType` underneath. Because [Type.Equals](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Type.cs#L675) checks `UnderlyingSystemType` for equality when the `EnumBuilder` underlying type is set from MLC Core assembly it is causing issue for enum fields defined, for example:
```cs
Type intType = mlc.CoreAssembly.GetType("System.Int32");
EnumBuilder enumBuilder = mb.DefineEnum("TestEnum", TypeAttributes.Public, intType);
FieldBuilder field = enumBuilder.DefineLiteral("Default", 0);
 ```
In this case the `field` type should be `TestEnum`, but it is evaluated to be equal to `System.Int32` when writing the field signature on Save. I think we should not return underlying field type for `EnumBuilder.UnderlyingSystemType`, should probably return the Enum itself instead (runtime enums returns the enum type itself). Though the `EnumBuilder.GetEnumUnderlyingType()` method should keep returning the underlying field type.

Related to https://github.com/dotnet/runtime/pull/105903

### CODE REVIEW

**Comment by jkotas** [comment]
Should this https://github.com/dotnet/runtime/blob/f9c08462ba81a2aacc9fd85d321e12080c17b9ee/src/libraries/System.Reflection.Emit/src/System/Reflection/Emit/TypeBuilderImpl.cs#L623-L635 be changed to just return `this` as well?

**Comment by jkotas** [comment]
How did you find this issue?

**Comment by steveharter** [comment]
> In this case the field type should be TestEnum, but it is evaluated to be equal to System.Int32 when writing the field signature on Save

Does .NET Framework have this issue?

> Because [Type.Equals](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Type.cs#L675) checks UnderlyingSystemType for equality

Is an alternative to override `Equals(Type)` instead of changing `UnderlyingSystemType`?

**Comment by jkotas** [comment]
> Is an alternative to override Equals(Type)

I would stay away from that. The problem with overriding Type.Equals is that it only works in one direction, it does not handle the case where `this` is the foreign Type and the argument is your Type.

**Comment by buyaa-n** [comment]
> Should this
> 
> https://github.com/dotnet/runtime/blob/f9c08462ba81a2aacc9fd85d321e12080c17b9ee/src/libraries/System.Reflection.Emit/src/System/Reflection/Emit/TypeBuilderImpl.cs#L623-L635
> 
> be changed to just return `this` as well?

Good point, I think we also need to add `GetEnumUnderlyingType()` override that returns this `_enumUnderlyingType`

**Comment by buyaa-n** [comment]
> How did you find this issue?

Found with https://github.com/dotnet/runtime/pull/105903

**Comment by buyaa-n** [comment]
> Does .NET Framework have this issue?

.NET Framework and existing runtime EnumBuilder doesn't have this issue as there is no Core assembly logic, the Type equality check happens when trying to determine the core type from core assembly.

https://github.com/dotnet/runtime/blob/bfd964a91fdf7ea1c854d3de217f79c0feaa7b7d/src/libraries/System.Reflection.Emit/src/System/Reflection/Emit/ModuleBuilderImpl.cs#L108

> > Is an alternative to override Equals(Type)
> 
> I would stay away from that. The problem with overriding Type.Equals is that it only works in one direction, it does not handle the case where this is the foreign Type and the argument is your Type.

I tried that, and exactly as @jkotas said it was not solving the issue completely

**Review by steveharter — APPROVED** [review]

**Pull request merged**
