### PR TITLE
[release/5.0] Prevent emitting Avx2 instruction for Vector256<T>.AllBitsSet and Vector256.Create(-1) when Avx2 is not supported

### LINKED ISSUE #48283: Vector256<Integer>.AllBitsSet emits illegal instructions on a machine without AVX2
### Description

On a machine without AVX2 but with AVX (Sandy Bridge / Ivy Bridge), `Vector256<IntegralType>.AllBitsSet` will emit illegal instructions and cause the program to crash.

In particular, this method:
```C#
public static Vector256<byte> Problem() => Vector256<byte>.AllBitsSet;
```
Will emit the following:
```asm
       vzeroupper 
G_M65241_IG02:
       vpcmpeqd ymm0, ymm0, ymm0
       vmovupd  ymmword ptr[rcx], ymm0
       mov      rax, rcx
G_M65241_IG03:
       vzeroupper 
       ret
```
According to https://www.felixcloutier.com/x86/pcmpeqb:pcmpeqw:pcmpeqd, `vpcmpeqd` with `ymm` operands is only available when AVX2 is.

This is also a problem for `Vector256.Create(-1)`.

### Configuration

This applies to .NET 5 and .NET 6, tested on an Ivy Bridge machine running Windows 10 x64.

### Regression?

This is not a regression in case of `AllBitsSet` (the API was introduced in .NET 5), but it is a regression from .NET Core 3.1 for the `Create(-1)` call (lowering now folds it to the same `get_AllBitsSet` node, see also #47385).

### Other information

During importation, `Vector256<byte>.AllBitsSet` depends on the `Vector256` ISA, presumably because it is declared like so:
```
HARDWARE_INTRINSIC(Vector256, get_AllBitsSet, 32, 0, {INS_pcmpeqd, INS_pcmpeqd, INS_pcmpeqd, INS_pcmpeqd, INS_pcmpeqd, INS_pcmpeqd, INS_pcmpeqd, INS_pcmpeqd, INS_cmpps, INS_cmppd}, HW_Category_Helper, HW_Flag_SpecialImport|HW_Flag_NoContainment|HW_Flag_NoRMWSemantics)
```
This ISA is available when AVX is available, and the intrinsic is recognized:
```
Named Intrinsic System.Runtime.Intrinsics.Vector256`1.get_AllBitsSet: Notify VM instruction set (Vector256) must be supported.
```
And the node is later emitted as `vpcmpeqd`:
https://github.com/dotnet/runtime/blob/7e681c1a02a4051d3d7b09bada6f9e323c975433/src/coreclr/jit/hwintrinsiccodegenxarch.cpp#L1254-L1269

cc @tannergooding

### PR DESCRIPTION
**Pull request by echesakov**
This is backporting of #48383 to 5.0
Closes #48283

### Customer Impact

In the two following cases 
```c#
 var ones = Vector256<int>.AllBitsSet;
```
and
```c#
var minusOnes = Vector256.Create(-1);
```
on x86 and x64 the JIT emits `vpcmpeqd ymmReg, ymmReg, ymmReg` instruction (that is supported by Avx2 CPU feature - see [pcmpeqb:pcmpeqw:pcmpeqd](https://www.felixcloutier.com/x86/pcmpeqb:pcmpeqw:pcmpeqd)) **even** on a machine that doesn't support the feature.

For example, the issue occurs with CPUs that belong to Sandy Bridge or Ivy Bridge microarchitectures. 

As you can see in  #48283, a customer originally observed the issue on an Ivy Bridge machine. The execution of such code on their machine resulted in crash followed by terminating of the process by OS.

### Validation

I don't have access to a machine that doesn't support Avx2. Therefore I used the same methodology we use in CI for ISA-related test scenarios (e.g. [runtime-coreclr jitstress-isas-x86](https://dev.azure.com/dnceng/public/_build?definitionId=664&_a=summary)) where we set corresponding COMPlus environment variables to simulate that a CPU feature is not supported.

I generated all possible variations of `Vector128/256<T>.AllBitsSet` and `Vector128/256.Create((T)-1)` (in the latter case `T` is a signed integer type) (see [Runtime_48283.cs](https://gist.github.com/echesakovMSFT/597902bdb59ec5b46833d67f3da20e8a#file-runtime_48283-cs)) and manually validated that the JIT doesn't emit the forbidden instructions. 

You can find below results of the JIT output for the following three cases - noavx (simulated with ` COMPlus_EnableAVX=0`), avx (simulated with `COMPlus_EnableAVX2=0`) and avx2 (when none of the ISAs were forbidden) for both x86 and x64.

- [noavx-win-x64.asm](https://gist.github.com/echesakovMSFT/597902bdb59ec5b46833d67f3da20e8a#file-noavx-win-x64-asm)
- [avx-win-x64.asm](https://gist.github.com/echesakovMSFT/597902bdb59ec5b46833d67f3da20e8a#file-avx-win-x64-asm)
- [avx2-win-x64.asm](https://gist.github.com/echesakovMSFT/597902bdb59ec5b46833d67f3da20e8a#file-avx2-win-x64-asm)

- [noavx-win-x86.asm](https://gist.github.com/echesakovMSFT/597902bdb59ec5b46833d67f3da20e8a#file-noavx-win-x86-asm)
- [avx-win-x86.asm](https://gist.github.com/echesakovMSFT/597902bdb59ec5b46833d67f3da20e8a#file-avx-win-x86-asm)
- [avx2-win-x86.asm](https://gist.github.com/echesakovMSFT/597902bdb59ec5b46833d67f3da20e8a#file-avx2-win-x86-asm)

After the change, the JIT will emit `vcmptrueps ymmReg, ymmReg, ymmReg` for such cases. This is similar to what Clang does - https://godbolt.org/z/erd5sf.

### Risk 

Low, the changes impacts only code generation of hardware intrinsics `Vector128/256<int>.AllBitsSet` that were introduces in 5.0 and optimization in the JIT of `Vector256.Create(-1)` that uses the mentioned intrinsics (that was also done in 5.0).

### Regression

Yes, the `Vector256.Create(-1)` on 3.1 wouldn't use Avx2 instruction. 
There is no  `Vector128/256<int>.AllBitsSet` API in 3.1.

### Note

The change depends on #48613 being merged - where another problem with `Vector256.Create(-1)` optimization was fixed.
The problem is that, at the moment, the JIT lowers both `Vector128.Create(-1)` and `Vector256.Create(-1)` to `Vector128<T>.AllBitsSet` without taking into account the vector size (see [src/coreclr/src/jit/lowerxarch.cpp](https://github.com/dotnet/runtime/pull/48613/files#diff-5addc7169287ab4150f9e1d3438ff114c416aae89d7c41fdcee7d4134b94a07a)

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@dotnet/jit-contrib @tannergooding PTAL

**Review by tannergooding — APPROVED** [review]

**Comment by echesakovMSFT** [comment]
Can I have sign-off from someone on @dotnet/jit-contrib please?

**Review by briansull — APPROVED** [review]
Looks Good

**Review by EgorBo — APPROVED** [review]

**Comment by echesakovMSFT** [comment]
cc @jeffschwMSFT

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  We will take for consideration in .NET 5.0.x

**Pull request merged**
