### PR TITLE
Avoid new constraint with structs in ILLink analyzer

### PR DESCRIPTION
**Pull request by sbomer**
@simonrozsival reported an issue where the trim analyzer was producing warnings inside Visual Studio, but not from a command-line build, for code similar to the following:

```csharp
var typeName = Console.ReadLine() ?? string.Empty;

if (RuntimeFeature.IsEnabled)
{
    var type = Type.GetType(typeName); // warning IL2057: Unrecognized value passed to the parameter 'typeName'...'System.Type.GetType'...
} else
{
    Console.WriteLine($"Cannot lookup {typeName} because the feature id disabled.");
}

internal static class RuntimeFeature
{
#pragma warning disable IL4000
    [FeatureGuard(typeof(RequiresUnreferencedCodeAttribute))]
    internal static bool IsEnabled => AppContext.TryGetSwitch("RuntimeFeature.IsEnabled", out bool enabled) ? enabled : true;
#pragma warning restore IL4000
}
```

I tracked this down to https://github.com/dotnet/runtime/issues/6536 that was fixed in .NET Core, but still exists in .NET Framework. It means that we can't rely the parameterless struct constructor being called for struct types used through a generic parameter with a `new()` constraint.

This fixes the issue by avoiding use of the `new()` constraint for generic parameters that might be structs. I confirmed locally that this fixes the reported warning, but there are no tests because we don't run tests on full framework.

Includes some unrelated debug helpers I found useful while investigating this.

### CODE REVIEW

**Review by agocke — APPROVED** [review]

**Comment by agocke** [comment]
@jaredpar I recall us not wanting to implement the parameterless-struct-ctor feature on Desktop because of bugs like this in Desktop that we regarded as too breaking to change now. Did we want to ban usage of this feature on non-Core via a RuntimeFeature?

**Comment by jaredpar** [comment]
> Did we want to ban usage of this feature on non-Core via a RuntimeFeature?

That was discussed and decided against. The parameterless ctor feature mostly worked on desktop and having a hard runtime feature flag dependency seemed on the whole not the right decision.

**Review by jtschuster — APPROVED** [review]

**Comment by rmarinho** [comment]
Can this be backported to preview.5 ? since it seems it branched already ?

**Comment by agocke** [comment]
@rmarinho Probably too late for Preview 5

**Pull request merged**
