### PR TITLE
[hot_reload] Fix unresolved token when new nested structs are used

### PR DESCRIPTION
**Pull request by lambdageek**
When a hot reload delta contains a new nested struct that is used as a field in a newly-added class, the metadata delta adds the field of the enclosing class before it adds the fields of the nested struct.  As a result, resolving the token of the field of the enclosing struct too early will make the runtime think that the nested struct has 0 fields and subsequent field lookups will fail.

Example:

Original Code:
```csharp
public class C {
  public void ExistingMethod() { }
```

Delta code:
```csharp
public class C {
  public void ExistingMethod() {
    new AddedClass();
  }
}

public class AddedClass {
  public NestedStruct Field1;
  public AddedClass() {
    Field1 = new NestedStruct { D = 1.0 };
  }
  public struct NestedStruct {
    public double D;
  }
}
```

Expected result:
Applying the hot reload delta succeeds

Actual result:

`System.BadImageFormatException: Could not resolve field token 0x04000014`

### CODE REVIEW

**Comment by lambdageek** [comment]
I'd like to backport this to .NET 7

**Review by vargaz — APPROVED** [review]

**Comment by lambdageek** [comment]
Wasm debugger failure is https://github.com/dotnet/runtime/issues/64188

**Pull request merged**
