### PR TITLE
Change FeedbackSize on Rijndael wrappers to delegate to implementation.

### LINKED ISSUE #46672: AES with CipherMode.CFB and PaddingMode.PKCS7 incompatible between .NET Framework and .NET5.0
### Description
I have a .NET Framework 4.6.2 program that encrypt/decrypt files and I tried to use the same encrypt/decrypt methods for a .NET5.0 console application. The code (below) compiles and works on both systems, but if I try to decrypt a file that is encrypted by the other system it is not compatible.

Encrypted with .NET Framework / Decrypted .NET Framework: Works fine.
Encrypted with .NET5.0 / Decrypted .NET5.0: Works fine.
Encrypted with .NET Framework/ Decrypted .NET5.0: Exception “Padding is invalid and cannot be removed”
Encrypted with .NET5.0 / Decrypted .NET Framework: Exception “Length of the data to decrypt is invalid”

I expected that the code in .NET Framework and .NET5.0 results in the same behaviour, but their seems to be differences.
Are there any properties to make the .NET5.0 project compatible? (The .NET Framework program is already released 2 years ago and changing the algorithm on that side is a bigger issue.)

### Configuration
.NET Framework 4.6.2
.NET5.0

Windows 10, x86

Visual Studio 2019, V16.8.3

### Regression?

Don't know. CipherMode.CFB is supported from .NET5.0 and should not work in older versions.

### Other information

Decryption/Encryption Code Example:

```
/// <summary>
/// Decrypts an encrypted file with the FileEncrypt method through its path and the plain password.
/// </summary>
/// <param name="inputFile"></param>
/// <param name="outputFile"></param>
/// <param name="password"></param>
/// <returns>true if no error, false in all other cases</returns>
public static bool FileDecrypt(string inputFile, string outputFile, string password)
{
	bool returnValue = true; // init value must be true!
	byte[] passwordBytes = System.Text.Encoding.UTF8.GetBytes(password);
	byte[] salt = new byte[32];

	FileStream fsCrypt = new FileStream(inputFile, FileMode.Open);
	fsCrypt.Read(salt, 0, salt.Length);

	RijndaelManaged AES = new RijndaelManaged();
	AES.KeySize = 256;
	AES.BlockSize = 128;
	var key = new Rfc2898DeriveBytes(passwordBytes, salt, 50000);
	AES.Key = key.GetBytes(AES.KeySize / 8);
	AES.IV = key.GetBytes(AES.BlockSize / 8);
	AES.Padding = PaddingMode.PKCS7;
	AES.Mode = CipherMode.CFB;

	CryptoStream cs = new CryptoStream(fsCrypt, AES.CreateDecryptor(), CryptoStreamMode.Read);

	FileStream fsOut = new FileStream(outputFile, FileMode.Create);

	int read;
	byte[] buffer = new byte[1048576];

	try
	{
		while ((read = cs.Read(buffer, 0, buffer.Length)) > 0)
		{
			//Application.DoEvents();
			fsOut.Write(buffer, 0, read);
		}
	}
	catch (CryptographicException ex_CryptographicException)
	{
		returnValue = false;
		Console.WriteLine("CryptographicException error: " + ex_CryptographicException.Message);
	}
	catch (Exception ex)
	{
		returnValue = false;
		Console.WriteLine("Error: " + ex.Message);
	}

	try
	{
		cs.Close();
	}
	catch (Exception ex)
	{
		returnValue = false;
		Console.WriteLine("Error by closing CryptoStream: " + ex.Message);
	}
	finally
	{
		fsOut.Close();
		fsCrypt.Close();
	}
	return returnValue;
}

/// <summary>
/// Creates a random salt that will be used to encrypt your file. This method is required on FileEncrypt.
/// </summary>
/// <returns></returns>
private static byte[] GenerateRandomSalt()
{
	byte[] data = new byte[32];

	using (RNGCryptoServiceProvider rng = new RNGCryptoServiceProvider())
	{
		for (int i = 0; i < 10; i++)
		{
			// Fill the buffer with the generated data
			rng.GetBytes(data);
		}
	}
	return data;
}

public static bool FileEncrypt(string inputFile, string outputFile, string password)
{
	bool returnValue = true; // init value must be true!
	//generate random salt
	byte[] salt = GenerateRandomSalt();

	//create output file name
	FileStream fsCrypt = new FileStream(outputFile, FileMode.Create);

	//convert password string to byte arrray
	byte[] passwordBytes = System.Text.Encoding.UTF8.GetBytes(password);

	//Set Rijndael symmetric encryption algorithm
	RijndaelManaged AES = new RijndaelManaged();
	AES.KeySize = 256;
	AES.BlockSize = 128;
	AES.Padding = PaddingMode.PKCS7;

	//"What it does is repeatedly hash the user password along with the salt." High iteration counts.
	var key = new Rfc2898DeriveBytes(passwordBytes, salt, 50000);
	AES.Key = key.GetBytes(AES.KeySize / 8);
	AES.IV = key.GetBytes(AES.BlockSize / 8);

	//Cipher mode
	AES.Mode = CipherMode.CFB;

	// write salt to the begining of the output file, so in this case can be random every time
	fsCrypt.Write(salt, 0, salt.Length);

	CryptoStream cs = new CryptoStream(fsCrypt, AES.CreateEncryptor(), CryptoStreamMode.Write);

	FileStream fsIn = new FileStream(inputFile, FileMode.Open);

	//create a buffer (1mb) so only this amount will allocate in the memory and not the whole file
	byte[] buffer = new byte[1048576];
	int read;

	try
	{
		while ((read = fsIn.Read(buffer, 0, buffer.Length)) > 0)
		{
			//Application.DoEvents(); // -> for responsive GUI, using Task will be better!
			cs.Write(buffer, 0, read);
		}

		// Close up
		fsIn.Close();
	}
	catch (Exception ex)
	{
		returnValue = false;
		Console.WriteLine("Error: " + ex.Message);
	}
	finally
	{
		cs.Close();
		fsCrypt.Close();
	}
	return returnValue;
}
```

### PR DESCRIPTION
**Pull request by vcsjones**
The FeedbackSize on RijndaelManaged and RijndaelImplementation were not
accurately reflecting the feedback size that the actual implementation
was using. The FeedbackSize would report 128, however the implementation
defaults to 8, so CFB8 is actually what was being used.

Likewise, the setter for FeedbackSize on the Rijndael types had no
effect. The implementation's default feedback size of 8 would always
be used.

Closes #46672

### CODE REVIEW

**Comment by vcsjones** [comment]
@bartonjs This PR makes the "least breaking" change. If we were doing this before .NET 5 shipped, we'd also want to set `impl.FeedbackSize = 128` in the constructor of `RijndaelManaged` and `RijndaelImplementation`. This would be desirable to match .NET Framework's default feedback size, but would break the (effective) default feedback size for the Rijndael types used in .NET 5 RTM.

It might be worth considering making this change anyway - the Rijndael types exist purely for compatibility reasons. It would seem strange that compatibility types are not... compatible.

**Comment by bartonjs** [comment]
Yeah, let's go ahead and try it as the "NetFX compatible" version.

**Comment by vcsjones** [comment]
@bartonjs Changed.

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
I will eventually remember about Windows 7 / CFB stuff. Speaking of which @bartonjs, if you decide to backport this it should probably be done manually (which I am happy to do) to account for the CFB8 differences in .NET 5 vs. 6 in Windows 7.

**Comment by vcsjones** [comment]
Failing mono test is addressed by #46699.

**Comment by bartonjs** [comment]
> if you decide to backport this ...

Yeah, we probably should, just to try to limit the amount of damage (at least the workaround is easy, just assign the mode to CFB8).

> ... it should probably be done manually (which I am happy to do)

Nice, much appreciated :)

**Pull request merged**
