### PR TITLE
[wasm] Add `IMemoryView` as exported type

### PR DESCRIPTION
**Pull request by maraf**
Based on discussion in the https://github.com/dotnet/AspNetCore.Docs/pull/27311#discussion_r1001458497

### CODE REVIEW

**Comment by maraf** [comment]
@pavelsavara Should I make `IMemoryView` extend `IDispoable`? Currently on the implementation `Span` and `ArraySegment` does implement it, but since these types are not exported, user won't probably know about disposing.

**Comment by pavelsavara** [comment]
> @pavelsavara Should I make `IMemoryView` extend `IDispoable`? 
Yes please!

**Review by pavelsavara — APPROVED** [review]
thanks

**Pull request merged**
