### PR TITLE
Use optimized Index.GetOffset in Range.GetOffsetAndLength

### PR DESCRIPTION
**Pull request by yesmey**
`Index.GetOffset` is using an optimization trick to reduce `offset = length - ~value` to `offset = length + value + 1`
We can reuse this in `Range.GetOffsetAndLength` to also simplify the code.

edit: asm diff was wrong. Benchmarking is hard. I was looking at the [DisassemblyDiagnoser] output.
I changed to loop 10_000_000 times and it gives a very similar result now
```
int dummy = 0;
for (int i = 0; i < 10_000_000; i++)
{
    dummy ^= _bytes.AsSpan(0..^_length).Length;
}
return dummy;
```
https://www.diffchecker.com/3T2jMQdy/

regardless it should still be an pretty easy win

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by yesmey** [comment]
Can't reproduce the test error locally
netcore 8:
System.Text.Json.SourceGeneration.Roslyn4.4.Tests  Total: 5577, Errors: 0, Failed: 0, Skipped: 0, Time: 15,288s
net 4.6:
System.Text.Json.SourceGeneration.Roslyn4.4.Tests  Total: 5567, Errors: 0, Failed: 0, Skipped: 0, Time: 25,188s

**Comment by danmoseley** [comment]
rerunning tests then we can merge

**Comment by yesmey** [comment]
Any clue why the pipeline keeps failing? Would you like me to merge from main and have it run again?

**Comment by danmoseley** [comment]
Thanks for the contribution @yesmey . You were unlucky with the validation

**Pull request merged**
