### PR TITLE
Fix ICU build

### LINKED ISSUE #68814: ucol_safeClone deprecated in ICU 71.1
https://unicode-org.github.io/icu-docs/apidoc/dev/icu4c/ucol_8h.html#a917cd8e16df3b35bbe97dd96d881f227

After recent update I'm no longer able to build System.Globalization.Native due to `ucol_safeClone` becoming deprecated.

### PR DESCRIPTION
**Pull request by ManickaP**
Fixes #68814

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]

**Comment by ManickaP** [comment]
Seeing the number of build errors, this is probably not the exactly right way forward with this. This might need some conditional compilation tricks. I'll leave this open and if anyone wants to take over, I'm game.

**Comment by tarekgh** [comment]
`ucol_clone` is introduced in ICU version 71 which cannot work with older versions of ICU. If we need to use `ucol_clone`, it have to be defined as optional APIs and we fallback when it is not supported.

**Comment by ManickaP** [comment]
Yeah, this was my meager attempt to fix the build for me since `ucol_safeClone` is deprecated on 71 ICU and thus failing build of runtime.
I'll close this PR and keep the change locally until you have time to fix this properly.

**Comment by danmoseley** [comment]
My bad. I signed off based on comparing with their documentation. I didn't notice when it was introduced.

**Pull request closed without merging**
