### PR TITLE
[hackathon] `ValueArray` - a compliment type to the `Span`, which owns its data without indirections.

### PR DESCRIPTION
**Pull request by VSadov**
`ValueArray<T, R>` is a data type that represents an indexable fixed-sized chunk of data containing N elements of type T.

The `R` type argument must be an object array type, that is not used for anything other than to convey the length of the value array declaratively - via the `R`'s rank.

The only "magical" part of the `ValueArray` type is that the VM logically replicates the storage N times and adjusts the instance layout and GC tracking accordingly.

In all other ways this is a regular struct - it can be copied by value, embedded in another struct/class, passed in/out of methods, stored on the heap, boxed...

### CODE REVIEW

**Comment by jkotas** [comment]
> The R type argument must be an object array type, that is not used for anything other than to convey the length of the value array declaratively - via the R's rank.

The maximum array rank is constrained by runtime implementation limitations (`MAX_RANK` - currently set to 32). Does this mean that the value arrays cannot have more than 32 elements?

**Comment by jkotas** [comment]
> That is nice at prototyping/experimenting stage.

I agree that the current hack is ok for experimentation. I have been thinking what this may look like if we were to productize this idea, and the hacks mentioned here look pretty ugly. We should be thinking about the clean way to represent it: either add support for parametrizing generics using constants or add a new ELEMENT_TYPE for the fixed array. There was actually ET value for fixed arrays in the early days of .NET https://github.com/search?q=ELEMENT_TYPE_VALUEARRAY_INTERNAL&type=code , but it did not make it.

**Comment by VSadov** [comment]
> Why wouldn't we just use Span<string> span = stackalloc string[4]; once that works
I would ask the question the other way - Why would you use stackalloc if a ValueArray is sufficient? - because ValueArray is conceptually simpler.

`stackalloc` is a powerful feature and when you need it, you really need it. You need it, for example, when allocation has a variable length or when allocation is large, but is rarely necessary. 

There are downsides also:
* `stackalloc` is more error prone. You may accidentally move it into a loop as a part of refactoring causing occasional SO. 
We had such bugs. Maybe even in this same code that I referenced. It looks familiar.
* `stackalloc` will limit your design choices. 
You cannot put stackallock-d variable into a field if evolution of your code requires it. It is difficult to mix with async or lambdas.

If a ValueArray is available I'd ask myself every time I use `stackalloc` for the reasons to use it - vs. just using ValueArray.

**Comment by VSadov** [comment]
> To play devil's advocate, because it's one tool that suffices whether or not the length is variable and it's an existing feature that doesn't increase concept count.

The range of usefulness of `stackalloc` is not a superset of value array. You can advocate the other way too :-)

**Comment by stephentoub** [comment]
> The range of usefulness of stackalloc is not a superset of value array. 

It's not.  That's kind of my point. I think the argument for `ValueArray<T>` should be focused on the things outside of `stackalloc`'s abilities.  We shouldn't cite cases like the `FourStackStrings` one mentioned earlier as being the motivation, as such cases are entirely doable with stackalloc and I don't see a good reason to use something else.  We should instead focus on finding good examples in dotnet/runtime where stackalloc couldn't be used, e.g. places where we'd embed `ValueArray<T>` in other types, where we'd use it in lambdas and async methods, etc.

**Comment by stephentoub** [comment]
> So, should we merge this then and start using it?

I'll defer to @davidwrighton.  From my perspective, this is an experimental branch and merging this into it is fine.

**Comment by VSadov** [comment]
Talked to  @davidwrighton - and we think it is ok to merge this.

**Pull request merged**
