### PR TITLE
Trim Linq.Expressions when using DependencyInjection

### PR DESCRIPTION
**Pull request by eerhardt**
Because ILEmitResolverBuilder (the default resolver) has a dependency on ExpressionResolverBuilder, this forces apps that use DI to bring in System.Linq.Expressions.

Refactoring the logic so Expressions can be trimmed in apps using DI.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by davidfowl** [comment]
I feel like we should delete this code.

**Comment by eerhardt** [comment]
> I feel like we should delete this code.

Which code? The ExpressionResolverBuilder? It is actually used in the netstandard2.0 build. We could just conditionally compile it for that build....

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/CompiledServiceProviderEngine.cs#L10-L14

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.DependencyInjection/src/Microsoft.Extensions.DependencyInjection.csproj#L15-L16

**Comment by eerhardt** [comment]
Test failures are all infrastructure issues unrelated to this change.

**Comment by davidfowl** [comment]
Yes the expression tree code. The places you don't have ref emit but have expressions trees that are compiled is .net core 1.0

**Comment by jkotas** [comment]
netstandard2.0 does not have Reflection.Emit. Are you suggesting to configure netstandard2.0 build to use reflection-based engine only?

**Comment by davidfowl** [comment]
> netstandard2.0 does not have Reflection.Emit. Are you suggesting to configure netstandard2.0 build to use reflection-based engine only?

Right, the idea being that in practice, the reflection only engine won't be used anyways since we would compile against net461 (which we do today) and netcoreapp2.1 (we only have ns2.0 and ns2.1 today).

So that netstandard2.0 assets wouldn't really get picked in practice enough though ns2.0 libraries would compile against it.

**Review by davidfowl — APPROVED** [review]
This looks good regardless. I'll look at removing the Expression tree resolver in another issue.

**Comment by eerhardt** [comment]
> So that netstandard2.0 assets wouldn't really get picked in practice enough

The current, in-market Xamarin apps are netstandard2.0 compatible, but not netfx nor netcoreapp. So when you use this library there, the ns2.0 assets are used.

I think Unity may be the same…

**Comment by davidfowl** [comment]
Xamarin apps and unity apps that do allow reflection emit?

**Comment by eerhardt** [comment]
I'm not sure about reflection emit. Maybe Android??

My point was that the netstandard2.0 asset gets picked when used in a Xamarin app.

**Comment by davidfowl** [comment]
Right I get that but the secondary question is, which platforms benefit from the expression tree implementation? The ones that do require non-interpreted expression tree support **and** no reflection emit support.

**Comment by eerhardt** [comment]
> which platforms benefit from the expression tree implementation?

I think that's a good question all up. I am not sure when the expression implementation is useful. Was it ever useful?

**Comment by davidfowl** [comment]
It was the first implementation before reflection emit was brought back to .NET Core. Then we did the ref emit version (it was more efficient all around and it allocated less) and kept the expression tree version but I'm not convinced it's worth maintaining.

**Comment by marek-safar** [comment]
> Then we did the ref emit version (it was more efficient all around and it allocated less) and kept the expression tree version but I'm not convinced it's worth maintaining.

We do support SRE even on AOTed platforms like iOS so from that perspective it could be removed.

**Comment by davidfowl** [comment]
It seems android is the only platform where this might be relevant.

**Comment by eerhardt** [comment]
> It seems android is the only platform where this might be relevant.

How so? I thought we were discussing NOT using the SRE on Android, and always using pure Reflection in https://github.com/dotnet/maui/issues/880#issuecomment-879083607. In that case, we wouldn't use Linq.Expressions either. Or was I misunderstanding something?

**Comment by davidfowl** [comment]
> How so? I thought we were discussing NOT using the SRE on Android, and always using pure Reflection in dotnet/maui#880 (comment). In that case, we wouldn't use Linq.Expressions either. Or was I misunderstanding something?

Right that discussion proves the point that expression trees are used on android because it does have a JIT. It seems to be the one place where we don't have the Ref emit APIs but we have compiled expression trees. Now we're debating whether we think the expression tree implementation is better on android or not.

**Pull request merged**
