### PR TITLE
Fix some interactions between tiering and multi-core JIT

### PR DESCRIPTION
**Pull request by kouvel**
Issues:
- When a multi-core JIT profile includes a method for which prejitted code is available, and the method contains a loop, when playing back the profile the multi-core JIT of the method disables call counting for the method, then when the method gets called the prejitted code is used but does not get tiered up later. Also hits assertion failures.
- Some cases where this may happen is if the profile is older than the prejitted state of an assembly, or if a profile is collected with R2R disabled (or without the assembly R2R'ed) and then played back on an R2R'ed assembly with R2R enabled.
- Tier 1 rejits also record the method in the multi-core JIT profile, another case where the above situation can occur

Fixes:
- Only record a method in the multi-core JIT profile for the default code version and only once for the code version
- When playing back a profile, don't disable call counting for a method immediately. Just record some info that may be used later when the method is actually gets called, if the multi-core jitted code gets used, to disable call counting if necessary.

### CODE REVIEW

**Comment by kouvel** [comment]
Forgot to add test, will add shortly

**Comment by kouvel** [comment]
Not a regression from 3.1, moved to 6.0

**Review by noahfalk — APPROVED** [review]
LGTM @kouvel : )

**Comment by kouvel** [comment]
I'm not able to repro the Linux arm checked assertion failures in:
- https://dev.azure.com/dnceng/public/_build/results?buildId=777234&view=logs&j=e03af94b-11f0-51a8-61f8-a4bc955f9c96&t=b9bbb17f-7ecb-51b7-5c10-8e4297ab79d0&s=b15d9194-8f26-5328-b47f-5968c76b37e7
- Console: https://helix.dot.net/api/2019-06-17/jobs/4835fe4f-b948-4f23-8d38-25f65b88fcbe/workitems/JIT.Directed/console

I don't seem them happening in other PRs, and doesn't look related to this change.

**Comment by kouvel** [comment]
The arm failure was a subtle issue in this change, fixed

**Pull request merged**
