### PR TITLE
Roll back conversion of native aot tests to merged model

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
There are two issues with this:

### 1. The merged tests are actually broken, but the failures are only observable without Helix

Helix does not report the failures (this is the reason I’m doing a rollback right away instead of waiting around for a fix). Example:

https://github.com/dotnet/runtime/blob/78a895ffee8ee5de89fb0a50b729de5ec733478b/src/tests/nativeaot/SmokeTests/Exceptions/Exceptions.cs#L67-L71

The above should obviously fail because there is no BringUpTest.Main (it got renamed to BringUpTest.TestEntryPoint as part of merging). The CI is all green, despite of this. The test fails if I run it locally through:

```
build clr.aot+libs -rc Checked -lc Release
src\tests\build.cmd nativeaot checked tree nativeaot\SmokeTests
src\tests\run.cmd runnativeaottests checked
```

### 2. There are several test failures, some of which look like they’ll need fixes in the merged wrapper infrastructure

* The Exceptions test wants to be able to test AppDomain.UnhandledException:
    https://github.com/dotnet/runtime/blob/78a895ffee8ee5de89fb0a50b729de5ec733478b/src/tests/nativeaot/SmokeTests/Exceptions/Exceptions.cs#L43
    The wrapper however generates a Try/Catch that doesn’t let UnhandledException happen. The test fails.

* The TrimmingBehaviors test is sensitive to ripple effects in whole program view. The wrapper’s use of Xunit Assert.Equal brings in a massive amount of reflection that causes ripple effects all over the place. The test fails in a rather obscure way and it took a while to root cause.

I’m also concerned about whether we have any tests that may now be succeeding because of the ripple effects from the wrapper (and we would not notice if the thing they are testing gets broken because they get saved by the ripple effects.

To fix this one, can we make it so RequiresProcessIsolation really just generates a Main that calls the other Main, without checking exit codes, wrapping anything, Assert.Equaling etc?

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Comment by jkotas** [comment]
> Helix does not report the failures

Does this affect all merged tests or just the nativeaot ones that you are reverting?

**Comment by MichalStrehovsky** [comment]
> > Helix does not report the failures
> 
> Does this affect all merged tests or just the nativeaot ones that you are reverting?

I'm afraid of the answer to this. I didn't check. Smoke tests are absolutely critical.

**Comment by jkotas** [comment]
> I'm afraid of the answer to this. I didn't check.

Checking: #100319

**Comment by agocke** [comment]
> The wrapper’s use of Xunit Assert.Equal brings in a massive amount of reflection that causes ripple effects all over the place. 

This shouldn't be true anymore. The Dotnet.Microsoft.XUnitAssert package should sub in and it should be trim safe.

**Comment by jkotas** [comment]
> I'm afraid of the answer to this. I didn't check. 

The other runtime tests are failing as expected https://dev.azure.com/dnceng-public/public/_build/results?buildId=620112&view=ms.vss-test-web.build-test-results-tab .

**Comment by MichalStrehovsky** [comment]
> > The wrapper’s use of Xunit Assert.Equal brings in a massive amount of reflection that causes ripple effects all over the place.
> 
> This shouldn't be true anymore. The Microsoft.Dotnet.XUnitAssert package should sub in and it should be trim safe.

Trim safety is not the problem here, it's the use of reflection on random stuff in the BCL.

In the case I saw, somewhere after `Assert.Equal<T>` we marked methods on `IEquatable<T>` as reflected on and that was breaking what a test was trying to exercise because we were no longer able to remove something. (It took extra long to troubleshoot because I thought it's something I broke, only to find out the test is broken in `main`.)

The tests under nativeaot need to have very precise control over what's in the dependency graph to be able to test the things they are testing. The implementation of Assert.Equal that still depends on reflection doesn't feel like what we'd want in the runtime test tree (it's fine for libs testing if it's trim safe, but runtime tests should have as little code running as part of the test infrastructure as possible).

**Comment by MichalStrehovsky** [comment]
> > I'm afraid of the answer to this. I didn't check.
> 
> The other runtime tests are failing as expected https://dev.azure.com/dnceng-public/public/_build/results?buildId=620112&view=ms.vss-test-web.build-test-results-tab .

Thanks for re-running the check - I also suspect this might be related to `RequiresProcessIsolation`; there's not much else that is different in these tests. We'll see if that's the case soon enough...

**Comment by MichalStrehovsky** [comment]
Can anyone sign off? It's not acceptable to have `main` in a state where we basically don't run nativeaot testing for a week.

This needs to be merged before #100331 can fix testing RequiresProcessIsolation tests.

The test failure is an unrelated GC issue.

**Review by vitek-karas — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
Thanks!

**Pull request merged**
