### PR TITLE
Clarify Lowering in ryujit-overview

### PR DESCRIPTION
**Pull request by CarolEidt**

### CODE REVIEW

**Comment by CarolEidt** [comment]
@sandreenko @dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
This came up in the discussion of https://github.com/dotnet/runtime/pull/722

**Review by BruceForstall — APPROVED** [review]
LGTM

You have a conflict, so maybe you're not up-to-date with my recent update of this document?

**Comment by CarolEidt** [comment]
> You have a conflict

Oops! Fixed now - thanks.

**Comment by sandreenko** [comment]
The original change LGTM, but I think it was lost during force-push.
So I do not see `Sometimes `Lowering` will insert nodes into the execution order before the node that it is currently handling.` in the change that was merged (and in the current version of this document https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/botr/ryujit-overview.md)

**Pull request merged**
