### PR TITLE
Fix NRE on EmitCalli

### LINKED ISSUE #44421: Ref emit broken for some calli cases?
Same code works fine on 5.0. 

```C#
public override void EmitCalli(OpCode opcode,
                               CallingConventions callingConvention,
                               Type? returnType,
                               Type[]? parameterTypes,
                               Type[]? optionalParameterTypes)
{
    int stackchange = 0;
    SignatureHelper sig;
    if (optionalParameterTypes != null)
        if ((callingConvention & CallingConventions.VarArgs) == 0)
            throw new InvalidOperationException(SR.InvalidOperation_NotAVarArgCallingConvention);

    sig = GetMemberRefSignature(callingConvention,
                                returnType,
                                parameterTypes,
                                optionalParameterTypes)
```
calls
```C#
internal SignatureHelper GetMemberRefSignature(
    CallingConventions call,
    Type? returnType,
    Type[]? parameterTypes,
    Type[]? optionalParameterTypes)
{
    return GetMemberRefSignature(call, returnType, parameterTypes, null, null, optionalParameterTypes);
}
```
calls
```C#
internal override SignatureHelper GetMemberRefSignature(
                                        CallingConventions call,
                                        Type? returnType,
                                        Type[]? parameterTypes,
                                        Type[][]? requiredCustomModifiers,
                                        Type[][]? optionalCustomModifiers,
                                        Type[]? optionalParameterTypes)
{
    SignatureHelper sig = SignatureHelper.GetMethodSigHelper(call, returnType);
    if (parameterTypes != null)
    {
        for (int i = 0; i < parameterTypes.Length; i++)
        {
            sig.AddArgument(parameterTypes[i], requiredCustomModifiers![i], optionalCustomModifiers![i]);
        }
    }
```
which derefs a null array.

### PR DESCRIPTION
**Pull request by wzchua**
fixes #44421

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thank you for a quick turnaround!

**Comment by jkotas** [comment]
cc @AndyAyersMS

**Comment by AndyAyersMS** [comment]
Thanks, testing this now.

**Comment by AndyAyersMS** [comment]
Works on my scenario.

**Pull request merged**
