### PR TITLE
JIT: Improve forwardsub for small types

### PR DESCRIPTION
**Pull request by EgorBo**
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=466832&view=ms.vss-build-web.run-extensions-tab)

### CODE REVIEW

**Comment by EgorBo** [comment]
@jakobbotsch @SingleAccretion thanks for the suggestion for a better fix! Is there anything else needed here then? This should fix some of the regressions I hit in https://github.com/dotnet/runtime/pull/94621, but I want to land it separately to make that one zero-diff (ideally).

Diffs https://dev.azure.com/dnceng-public/public/_build/results?buildId=466832&view=ms.vss-build-web.run-extensions-tab

cc @dotnet/jit-contrib

**Review by jakobbotsch — APPROVED** [review]
LGTM -- please fix the PR title and commit message

**Comment by jakobbotsch** [comment]
Should probably run jitstress and Fuzzlyn too.

**Comment by EgorBo** [comment]
@jakobbotsch have you seen Fuzzlyn failures like this one https://dev.azure.com/dnceng-public/public/_build/results?buildId=466925&view=ms.vss-build-web.run-extensions-tab ?

**Comment by jakobbotsch** [comment]
> @jakobbotsch have you seen Fuzzlyn failures like this one https://dev.azure.com/dnceng-public/public/_build/results?buildId=466925&view=ms.vss-build-web.run-extensions-tab ?

No, I haven't seen that before. I checked and it is hitting an assert with and without this change, so it is not related to this PR.
```scala
Assert failure(PID 15296 [0x00003bc0], Thread: 13572 [0x3504]): Assertion failed 'codeSize <= MAX_PROLOG_SIZE_BYTES' in 'Program:.cctor()' during 'Emit code' (IL size 10191; hash 0x02c770ad; FullOpts)

    File: C:\dev\dotnet\runtime\src\coreclr\jit\unwindarmarch.cpp Line: 834
    Image: H:\dotnet\runtime\artifacts\tests\coreclr\windows.arm64.Checked\Tests\Core_Root_base\corerun.exe
```
(Looks like Fuzzlyn should be looking at inner exceptions when it sees `System.TypeInitializationException` to be able to extract that assertion failure from it.)

**Comment by cincuranet** [comment]
Regression in `System.Collections.ContainsTrueComparer<Int32>.FrozenSet`: https://github.com/dotnet/perf-autofiling-issues/issues/24578.

**Pull request merged**
