### PR TITLE
[wasm] Rename module file to .mjs

### PR DESCRIPTION
**Pull request by mkhamoyan**
Rename `test-main.js` to `test-main.mjs`

### CODE REVIEW

**Comment by ilonatommy** [comment]
What about this place in the code:
- [src/mono/wasm/Wasm.Build.Tests/WasmRunOutOfAppBundleTests.cs](https://github.com/dotnet/runtime/blob/5e1081f6a0c86489e7fda575735ef49ff2ca3efa/src/mono/wasm/Wasm.Build.Tests/WasmRunOutOfAppBundleTests.cs#L44)

**Comment by mkhamoyan** [comment]
> What about this place in the code:
> 
> * [src/mono/wasm/Wasm.Build.Tests/WasmRunOutOfAppBundleTests.cs](https://github.com/dotnet/runtime/blob/5e1081f6a0c86489e7fda575735ef49ff2ca3efa/src/mono/wasm/Wasm.Build.Tests/WasmRunOutOfAppBundleTests.cs#L44)

Thanks, updated.

**Review by maraf — DISMISSED** [review]
~~Looks good to me 👍~~

**Comment by mkhamoyan** [comment]
@maraf same failure is happeing on my [this](https://github.com/dotnet/runtime/pull/105561) PR
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-105561-merge-2ba2a3dd38fd4dfcbc/WasmTestOnNodeJS-ST-System.Net.Http.Functional.Tests/1/console.c6060693.log?helixlogtype=result

**Pull request closed without merging**
