### PR TITLE
Wasm windows aot

### LINKED ISSUE #49939: 6.0.0-preview.3.21169.6 version of browser-wasm package on Windows is missing cross-compiler
```
ls .nuget\packages\microsoft.netcore.app.runtime.aot.win-x64.cross.browser-wasm\6.0.0-preview.3.21169.6\tools


    Directory: .nuget\packages\microsoft.netcore.app.runtime.aot.win-x64.cross.browser-wasm\6.0.0-preview.3.21169.6\tools

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         3/15/2021  2:44 PM       27256832 llc.exe
-a----         3/19/2021  5:04 PM            831 monocrossaot.deps.json
-a----         3/19/2021  5:04 PM             53 monocrossaot.runtimeconfig.json
-a----         3/15/2021  2:44 PM       31306240 opt.exe
```

### PR DESCRIPTION
**Pull request by lewing**
I think this will fix https://github.com/dotnet/runtime/issues/49939 but someone more familiar with the build should verify

### CODE REVIEW

**Comment by lewing** [comment]
One second, wrong base branch

**Comment by radical** [comment]
The change makes sense. @radekdoulik any idea why this was added?

**Comment by lewing** [comment]
@radekdoulik I think it was there from @steveisok 's original patch and just made it through

**Review by radical — APPROVED** [review]

**Comment by directhex** [comment]
The correct thing to do is, of course, push to internal, add a new subscription from the internal branch to `General testing` in darc, and try an official build from the branch

But

If I can read binlogs properly, I think this is correct. The BuildMonoCross target isn't firing when it should, and the only conditional on there is for BuildMonoAOTCrossCompiler

**Comment by radical** [comment]
Build failed:

```
  Running 'python3 D:\workspace\_work\1\s\src\mono\mono/tools/offsets-tool/offsets-tool.py --abi=wasm32-unknown-none --netcore --targetdir="D:\workspace\_work\1\s\artifacts\obj\mono\Browser.wasm.Debug\" --monodir="D:\workspace\_work\1\s\src\mono" --outfile="D:\works     pace\_work\1\s\artifacts\obj\mono\Browser.wasm.Debug\cross/offsets-wasm32-unknown-none.h" --libclang="D:\workspace\_work\1\s\src\mono\wasm\emsdk\/upstream/lib/libclang.so" --emscripten-sdk="D:\workspace\_work\1\s\src\mono\wasm\emsdk\/upstream/emscripten"'
   Libclang 'D:\workspace\_work\1\s\src\mono\wasm\emsdk\/upstream/lib/libclang.so' doesn't exist.
```

**Comment by steveisok** [comment]
`BuildMonoAOTCrossCompilerOnly=true` should be enough.  Should we add it to the original condition?

`Condition="'$(TargetsBrowser)' == 'true' and ('$(OS)' != 'Windows_NT' or '$(BuildMonoAOTCrossCompilerOnly)' == 'true')"`

**Comment by steveisok** [comment]
Separately, this will get you a little farther w/ the cross compiler in a local windows build.

```
--- a/src/mono/mono.proj
+++ b/src/mono/mono.proj
@@ -449,7 +449,8 @@
       <MonoAotAbi>wasm32-unknown-none</MonoAotAbi>
       <MonoAotOffsetsFile>$(MonoObjDir)cross/offsets-wasm32-unknown-none.h</MonoAotOffsetsFile>
       <MonoLibClang Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(EMSDK_PATH)/upstream/lib/libclang.dylib</MonoLibClang>
-      <MonoLibClang Condition="!$([MSBuild]::IsOSPlatform('OSX'))">$(EMSDK_PATH)/upstream/lib/libclang.so</MonoLibClang>
+      <MonoLibClang Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(EMSDK_PATH)/upstream/lib/libclang.so</MonoLibClang>
+      <MonoLibClang Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(EMSDK_PATH)/upstream/bin/libclang.dll</MonoLibClang>
```

**Comment by steveisok** [comment]
For the regular windows build, we should apply the condition to `BuildMonoAOTCrossCompiler` until we can get it working.  At one point I did locally, but I still can't build the windows build for reasons unknown.

**Comment by radekdoulik** [comment]
> Separately, this will get you a little farther w/ the cross compiler in a local windows build.

I went into that direction a bit before. We don't have `$(EMSDK_PATH)/upstream/bin/libclang.dll` in emscripten on windows, just `libclang.lib` which is static library? I stopped at that point back then.

**Comment by lewing** [comment]
Failure is
```
	  at <unknown> <0xffffffff>
	  at CryptoInitializer:EnsureOpenSslInitialized <0x00007>
	  at CryptoInitializer:.cctor <0x00023>
	  at System.Object:runtime_invoke_void <0x0007f>
	  at <unknown> <0xffffffff>
	  at Crypto:.cctor <0x0005f>
	  at System.Object:runtime_invoke_void <0x0007f>
	  at <unknown> <0xffffffff>
	  at Internal.Cryptography.Pal.OpenSslX509CertificateReader:TryReadX509Der <0x00057>
	  at Internal.Cryptography.Pal.OpenSslX509CertificateReader:FromBlob <0x0005b>
	  at Internal.Cryptography.Pal.CertificatePal:FromBlob <0x00043>
	  at System.Security.Cryptography.X509Certificates.X509Certificate:.ctor <0x000ff>
	  at System.Security.Cryptography.X509Certificates.X509Certificate:.ctor <0x0003f>
	  at System.Security.Cryptography.X509Certificates.X509Certificate2:.ctor <0x0003b>
	  at System.Security.Cryptography.Xml.Tests.TestHelpers:GetSampleX509Certificate <0x0005f>
	  at System.Security.Cryptography.Xml.Tests.SigningVerifyingX509Cert:SignedXmlHasCertificateVerifiableSignature <0x00033>
	  at System.Object:runtime_invoke_void__this__ <0x00087>
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x00007>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x00103>
	  at System.Reflection.MethodBase:Invoke <0x00053>
	  at Xunit.Sdk.TestInvoker`1:CallTestMethod <0x00047>
	  at <<InvokeTestMethodAsync>b__1>d:MoveNext <0x0037b>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0009f>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x0002f>
	  at <>c__DisplayClass48_1:<InvokeTestMethodAsync>b__1 <0x000d3>
	  at <AggregateAsync>d__4:MoveNext <0x000c3>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0009b>
	  at Xunit.Sdk.ExecutionTimer:AggregateAsync <0x000ff>
	  at <>c__DisplayClass48_1:<InvokeTestMethodAsync>b__0 <0x0017b>
	  at <RunAsync>d__9:MoveNext <0x00067>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00093>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x000fb>
	  at <InvokeTestMethodAsync>d__48:MoveNext <0x0030f>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000a7>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.TestInvoker`1:InvokeTestMethodAsync <0x0011b>
	  at Xunit.Sdk.XunitTestInvoker:InvokeTestMethodAsync <0x00127>
	  at <<RunAsync>b__47_0>d:MoveNext <0x00677>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000af>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.TestInvoker`1:<RunAsync>b__47_0 <0x000db>
	  at <RunAsync>d__10`1:MoveNext <0x00073>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x00093>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x000fb>
	  at Xunit.Sdk.TestInvoker`1:RunAsync <0x00103>
	  at Xunit.Sdk.XunitTestRunner:InvokeTestMethodAsync <0x000cb>
	  at <InvokeTestAsync>d__4:MoveNext <0x001c3>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000a3>
	  at Xunit.Sdk.XunitTestRunner:InvokeTestAsync <0x00103>
	  at <>c__DisplayClass43_0:<RunAsync>b__0 <0x00043>
	  at <RunAsync>d__10`1:MoveNext <0x0006f>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0009f>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x00113>
	  at <RunAsync>d__43:MoveNext <0x0048f>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000af>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.TestRunner`1:RunAsync <0x000db>
	  at Xunit.Sdk.XunitTestCaseRunner:RunTestAsync <0x000df>
	  at <RunAsync>d__19:MoveNext <0x0030b>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000a7>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.TestCaseRunner`1:RunAsync <0x000d7>
	  at Xunit.Sdk.XunitTestCase:RunAsync <0x000b3>
	  at Xunit.Sdk.XunitTestMethodRunner:RunTestCaseAsync <0x000a3>
	  at <RunTestCasesAsync>d__32:MoveNext <0x001cf>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000af>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.TestMethodRunner`1:RunTestCasesAsync <0x000db>
	  at <RunAsync>d__31:MoveNext <0x0018b>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x0009f>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.TestMethodRunner`1:RunAsync <0x000d3>
	  at Xunit.Sdk.XunitTestClassRunner:RunTestMethodAsync <0x000df>
	  at <RunTestMethodsAsync>d__38:MoveNext <0x00827>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000b7>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.TestClassRunner`1:RunTestMethodsAsync <0x000df>
	  at <RunAsync>d__37:MoveNext <0x0032b>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000a7>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.TestClassRunner`1:RunAsync <0x000d7>
	  at Xunit.Sdk.XunitTestCollectionRunner:RunTestClassAsync <0x000e3>
	  at <RunTestClassesAsync>d__28:MoveNext <0x0040b>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000af>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.TestCollectionRunner`1:RunTestClassesAsync <0x000db>
	  at <RunAsync>d__27:MoveNext <0x0032b>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000a7>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0002f>
	  at Xunit.Sdk.TestCollectionRunner`1:RunAsync <0x000d7>
	  at Xunit.Sdk.XunitTestAssemblyRunner:RunTestCollectionAsync <0x000af>
	  at <>c__DisplayClass14_2:<RunTestCollectionsAsync>b__2 <0x0006f>
	  at System.Threading.Tasks.Task`1:InnerInvoke <0x0006f>
	  at <>c:<.cctor>b__284_0 <0x0003b>
	  at System.Threading.ExecutionContext:RunInternal <0x000bf>
	  at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x00253>
	  at System.Threading.Tasks.Task:ExecuteEntry <0x000bb>
	  at <>c:<.cctor>b__8_0 <0x00067>
	  at Xunit.Sdk.MaxConcurrencySyncContext:RunOnSyncContext <0x0004f>
	  at <>c__DisplayClass11_0:<WorkerThreadProc>b__0 <0x00053>
	  at System.Threading.ExecutionContext:RunInternal <0x000bf>
	  at System.Threading.ExecutionContext:Run <0x00047>
	  at System.Object:lambda_method2 <0x0008b>
	  at Xunit.Sdk.ExecutionContextHelper:Run <0x00063>
	  at Xunit.Sdk.MaxConcurrencySyncContext:WorkerThreadProc <0x00233>
	  at <>c:<QueueUserWorkItem>b__5_0 <0x00077>
	  at System.Threading.Tasks.Task:InnerInvoke <0x000b7>
	  at <>c:<.cctor>b__284_0 <0x0003b>
	  at System.Threading.ExecutionContext:RunInternal <0x000bf>
	  at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x00253>
	  at System.Threading.Tasks.Task:ExecuteEntryUnsafe <0x000ab>
	  at <>c:<.cctor>b__10_0 <0x0006b>
	  at System.Threading.Thread:StartCallback <0x00127>
	  at System.Object:runtime_invoke_void__this__ <0x00087>
=================================================================
./RunTests.sh: line 162:    99 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Security.Cryptography.Xml.Tests.runtimeconfig.json --depsfile System.Security.Cryptography.Xml.Tests.deps.json xunit.console.dll System.Security.Cryptography.Xml.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
```
and is unrelated

**Pull request merged**
