### PR TITLE
Arm64: Use TYP_SIMD8 for AddAcross

### LINKED ISSUE #108612: osx/arm64: Assertion failed 'm_store->TypeGet() == m_src->TypeGet()' during 'Assertion prop'
```csharp
// Found by Antigen
// Reduced from 18.05 KB to 1.2 KB.


using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;
using System.Runtime.Intrinsics.X86;
using System.Numerics;
public class TestClass
{
    static Vector128<byte> s_v128_byte_27 = Vector128.CreateScalar((byte)0);
    static Vector128<int> s_v128_int_31 = Vector128<int>.Zero;
    static Vector128<uint> s_v128_uint_32 = Vector128.CreateScalar((uint)5);
    Vector64<byte> v64_byte_67 = Vector64.CreateScalar((byte)5);
    Vector128<int> v128_int_81 = Vector128.Create(-1, 6, 2, 1);
    private static List<string> toPrint = new List<string>();
    public void Method0()
    {
        unchecked
        {
            v128_int_81 = AdvSimd.NegateSaturate(s_v128_int_31 *= 15|4);
            s_v128_uint_32 = AdvSimd.ShiftRightLogicalRounded(s_v128_uint_32, Vector128.Sum(s_v128_byte_27 | s_v128_byte_27));
            v64_byte_67 = AdvSimd.Arm64.AddAcross(s_v128_byte_27 | s_v128_byte_27);
            return;
        }
    }
    public static void Main(string[] args)
{}
    public static int Antigen()
    {
        new TestClass().Method0();
        return string.Join(Environment.NewLine, toPrint).GetHashCode();
    }
}
/*
Environment:

set DOTNET_JitForceControlFlowGuard=1
set DOTNET_TieredCompilation=0
set DOTNET_MaxVectorTBitWidth=128
set DOTNET_PreferredVectorBitWidth=0
set DOTNET_JitStress=0
set DOTNET_TailcallStress=0
set DOTNET_JitStressRegs=2
set DOTNET_JitThrowOnAssertionFailure=1
set DOTNET_LegacyExceptionHandling=1

Debug: 0
Specified argument was out of the range of valid values.
Release: 0
JIT assert failed:
Assertion failed 'm_store->TypeGet() == m_src->TypeGet()' in 'TestClass:Method0():this' during 'Assertion prop' (IL size 91; hash 0x46e9aa75; FullOpts)

    File: /Users/runner/work/1/s/src/coreclr/jit/morphblock.cpp Line: 665


*/

```

### PR DESCRIPTION
**Pull request by kunalspathak**
[AddAcross](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.intrinsics.arm.advsimd.arm64.addacross?view=net-9.0) always return `Vector64<T>` and we should use `TYP_SIMD8` when trying to create the intrinsics.

Fixes: https://github.com/dotnet/runtime/issues/108612

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by JulieLeeMSFT** [comment]
Are we going to backport this to 9?

**Comment by kunalspathak** [comment]
> Are we going to backport this to 9?

yes

**Comment by kunalspathak** [comment]
ping @dotnet/jit-contrib @AndyAyersMS

**Review by AndyAyersMS — COMMENTED** [review]
Jit changes LGTM.

You need to fix the test case.

**Review by tannergooding — APPROVED** [review]

**Pull request merged**
