### PR TITLE
Use cached values for GetEnvirionmentValue() in NativeAOT

### PR DESCRIPTION
**Pull request by HJLeee**
#71367

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
I assume you're hitting this in a real world program? It was an explicit design decision back when this was added, but it can certainly be reevaluated: https://github.com/dotnet/corert/pull/7001#discussion_r255922232

**Comment by HJLeee** [comment]
Thank you for quick response. 👍 
I've just started evaluating `NativeAOT` and trying to understand if it is going to be applicable to embedded devices, so it is not yet a real world problem.

If I understand it correctly, the comment says fixing values at some point and stop being affected by native environment variable changes.
IMHO, this PR also fixes values and aligns with coreclr behavior.

**Comment by jkotas** [comment]
> IMHO, this PR also fixes values and aligns with coreclr behavior.

CoreCLR caches the environment very early during the PAL startup. This will cache the environment on the first `Environment.GetEnvironmentVariable` call. It still not going to match coreclr behavior exactly.

There are differences between Windows and non-Windows, and between Mono and CoreCLR. I do not think we want to make guarantees about when or whether the environment variables get cached by the runtime.

This change will increase memory footprint of NativeAOT compiled applications somewhat. Real world apps typically read at least one environment variable somewhere that will pin a copy of the environment in memory.

**Comment by HJLeee** [comment]
Thank you for the clarification.
I think users may call `SetEnvironmentVariable()` if they want partial guarantee as a workaround.

**Pull request closed without merging**
