### PR TITLE
Fix memory errors related to EventPipe setup with COMPlus_EventPipeConfig

### PR DESCRIPTION
**Pull request by gbalykov**
- XplatEventLoggerConfiguration configuration owns strings passed to EventPipeProviderConfiguration pProviders, and configurations are freed before pProviders are copied to EventPipeSessionProvider
- NewArrayHolder shoud be used for pProviders to fix memory leak (delete[] instead of delete)

Bug shows itself in release builds with
```sh
COMPlus_EnableEventPipe=1 COMPlus_EventPipeConfig="*:0xFFFFFFFFFFFFFFFF:5" COMPlus_EventPipeOutputPath=`pwd`/trace.nettrace COMPlus_EventPipeRundown=0 ./corerun ~/hwapp2.dll
```

Correct, passed in env variable:
```
m_pProviderName = 0x5555557cce10 u"*"
```
Incorrect, processed inside `EventPipe::Enable`:
```
m_pProviderName = 0x5555557cce10 u"츰啼啕"
```

cc @alpencolt

### CODE REVIEW

**Comment by maryamariyan** [comment]
@alpencolt is this PR for `area-Tizen`?

**Comment by alpencolt** [comment]
@maryamariyan it's for all platforms

**Review by sywhang — APPROVED** [review]

**Comment by sywhang** [comment]
Thanks, this may need to be backported to 5.0 - I will handle that once this PR is merged.

**Review by noahfalk — APPROVED** [review]
LGTM

**Comment by noahfalk** [comment]
cc @davmason @josalem @sdmaclea - it looked fine to me but I didn't get to scrutinize it while trying to take care of everything before going on vacation. If we decide it needs a backport its probably worth someone else giving it a more careful look.

**Review by josalem — APPROVED** [review]
Walked through the lifetime of the strings, and this should fix the described issue.

@sywhang I think this is the only place where `XplatEventLoggerConfiguration` is used.  Should we subsume the `Parse` logic directly into `EventPipeProviderConfiguration` to reduce duplication and ownership transfers?

**Comment by ViktorHofer** [comment]
// Auto-generated message

https://github.com/dotnet/runtime/commit/69e114c1abf91241a0eeecf1ecceab4711b8aa62 which was merged 12/7 removed the intermediate src/coreclr/**src**/ folder. This PR needs to be updated as it touches files in that directory which causes conflicts.

To update your commits you can use this bash script: https://gist.github.com/ViktorHofer/6d24f62abdcddb518b4966ead5ef3783. Feel free to use the comment section of the gist to improve the script for others.

**Comment by gbalykov** [comment]
Rebased on new master with removed src/coreclr/src/ dir

**Comment by gbalykov** [comment]
@josalem Can this be merged?

**Comment by josalem** [comment]
I believe so.  We recently added a C implementation of EventPipe we are intending on switching to, so we might need to port this change to there as well.  That doesn't need to be part of this PR though.

CC @lateralusX

**Comment by gbalykov** [comment]
Thanks!

**Pull request merged**
