### PR TITLE
Fix The Resource File Name Change

### LINKED ISSUE #31675: Events contained unexpected event in AsyncTaskMethodBuilderTests.DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent
*Example repro:*

https://dev.azure.com/dnceng/public/_build/results?buildId=505090&view=ms.vss-test-web.build-test-results-tab&runId=16033318&resultId=102213&paneView=debug

*Platform:* multiple including Alpine Linux x64 Release

*Error log:*

<pre>
Child exception:
  Xunit.Sdk.XunitException: Events contained unexpected event:
ActivityId: 00000000-0000-0000-0000-000000000000
Channel: None
EventId: 0
EventName: EventSourceMessage
EventSource: EventSource(System.Threading.Tasks.TplEventSource, 2e5dba47-a3d2-4d16-8ee0-6671ffdcd7b5)
Keywords: None
Level: LogAlways
Message: ERROR: Exception in Command Processing for EventSource System.Threading.Tasks.TplEventSource: Could not find the resource "System.Private.CoreLib.Resources.Strings.resources" among the resources "System.Private.CoreLib.Strings.resources", "System.Private.CoreLib.xml" embedded in the assembly "System.Private.CoreLib", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
Opcode: Info
OSThreadId: 48
Payload: ERROR: Exception in Command Processing for EventSource System.Threading.Tasks.TplEventSource: Could not find the resource "System.Private.CoreLib.Resources.Strings.resources" among the resources "System.Private.CoreLib.Strings.resources", "System.Private.CoreLib.xml" embedded in the assembly "System.Private.CoreLib", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
PayloadNames: message
RelatedActivityId: 00000000-0000-0000-0000-000000000000
Tags: None
Task: None
TimeStamp: 2/3/2020 11:58:40 AM
Version: 0

   at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.<>c.<DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent>b__33_0() in /_/src/libraries/System.Threading.Tasks/tests/System.Runtime.CompilerServices/AsyncTaskMethodBuilderTests.cs:line 625

Child process:
  System.Threading.Tasks.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests+<>c Void <DroppedIncompleteStateMachine_RaisesIncompleteAsyncMethodEvent>b__33_0()
</pre>

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #31675

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @trylek

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
What caused this to break?

**Comment by tarekgh** [comment]
> What caused this to break?

In 5.0 someone changed the resources file name in corelib to `System.Private.CoreLib.Strings.resources` instead of `System.Private.CoreLib.resources.Strings.resources`. i.e. removed the redundant `Resources` term from the name. in TplEventSource we hardcode the resource file name in the EventSource attribute. and that broke finding the resources.

**Comment by stephentoub** [comment]
Got it. Thanks.  I assume you searched and this is the only occurrence of this pattern?

**Comment by tarekgh** [comment]
Yes, this is the only hit I got when I searched the whole runtime repo.

**Pull request merged**
