### PR TITLE
Fix zlib-ng compilation on Raspberry Pi ARM32

### LINKED ISSUE #106584: Zlib-ng compilation fails on Raspbian ARM32 system
Log output:
```
  fatal error: error in backend: Cannot select: intrinsic %llvm.arm.uqsub16
  PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
  Stack dump:
  0.	Program arguments: /usr/bin/clang-16 -DARM_ACLE -DARM_ASM_HWCAP -DARM_AUXV_HAS_CRC32 -DARM_AUXV_HAS_NEON -DARM_FEATURES -DARM_NEON -DARM_NEON_HASLD4 -DARM_SIMD -DARM_SIMD_INTRIN -DBUILDENV_DEBUG=1 -DCLR_ARM_FPU_CAPABILITY=0x7 -DCOMPILER_SUPPORTS_W_RESERVED_IDENTIFIER -DDEBUG -DDISABLE_CONTRACTS -DHAVE_ALIGNED_ALLOC -DHAVE_ARM_ACLE_H -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DHAVE_POSIX_MEMALIGN -DHAVE_SYS_AUXV_H -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHOST_ARM -DHOST_UNIX -DPALEXPORT=EXTERN_C -DTARGET_32BIT -DTARGET_ARM -DTARGET_LINUX -DTARGET_UNIX -DURTBLDENV_FRIENDLY=Debug -DWITH_GZFILEOP -DZLIB_COMPAT -D_DBG -D_DEBUG -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE=1 -D_TIME_BITS=64 -D__USE_LARGEFILE64 -I/home/navara/runtime/artifacts/obj/coreclr/linux.arm.Debug/_deps/fetchzlibng-build -I/home/navara/runtime/src/native/external/zlib-ng -I/home/navara/runtime/src/native -I/home/navara/runtime/src/native/inc -std=gnu99 -Wno-declaration-after-statement -D_GNU_SOURCE -g -fPIC -O0 -Wall -Wno-null-conversion -glldb -fno-omit-frame-pointer -fwrapv -fstack-protector-strong -Werror -Wno-unused-variable -Wno-unused-value -Wno-unused-function -Wno-tautological-compare -Wno-unknown-pragmas -Wimplicit-fallthrough -Wno-unused-but-set-variable -ffp-contract=off -Wno-unknown-warning-option -ferror-limit=4096 -Wno-unused-private-field -Wno-constant-logical-operand -Wno-pragma-pack -Wno-incompatible-ms-struct -Wno-reserved-identifier -Wno-unsafe-buffer-usage -Wno-single-bit-bitfield-constant-conversion -Wno-cast-function-type-strict -Wno-switch-default -fsigned-char -fvisibility=hidden -ffunction-sections -mthumb -mfpu=vfpv3 -march=armv7-a -I/home/navara/runtime/src/native/libs/Common -I/home/navara/runtime/artifacts/obj/coreclr/linux.arm.Debug/libs-native/Common -mfloat-abi=hard -DZLIB_DEBUG -Wno-unused-command-line-argument -Wno-logical-op-parentheses -std=c11 -march=armv6 -fno-lto -MD -MT _deps/fetchzlibng-build/CMakeFiles/zlib.dir/arch/arm/slide_hash_armv6.c.o -MF CMakeFiles/zlib.dir/arch/arm/slide_hash_armv6.c.o.d -o CMakeFiles/zlib.dir/arch/arm/slide_hash_armv6.c.o -c /home/navara/runtime/src/native/external/zlib-ng/arch/arm/slide_hash_armv6.c
  1.	<eof> parser at end of file
  2.	Code generation
  3.	Running pass 'Function Pass Manager' on module '/home/navara/runtime/src/native/external/zlib-ng/arch/arm/slide_hash_armv6.c'.
  4.	Running pass 'ARM Instruction Selection' on function '@slide_hash_chain'
  clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
  Debian clang version 16.0.6 (15~deb12u1)
  Target: arm-unknown-linux-gnueabihf
  Thread model: posix
  InstalledDir: /usr/bin
  clang: note: diagnostic msg: 
  ********************
  
  PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
  Preprocessed source(s) and associated run script(s) are located at:
  clang: note: diagnostic msg: /tmp/slide_hash_armv6-72b11a.c
  clang: note: diagnostic msg: /tmp/slide_hash_armv6-72b11a.sh
  clang: note: diagnostic msg: 
  
  ********************
  [ 20%] Built target eventpipe-shared-objects
  make[3]: *** [_deps/fetchzlibng-build/CMakeFiles/zlib.dir/build.make:552: _deps/fetchzlibng-build/CMakeFiles/zlib.dir/arch/arm/slide_hash_armv6.c.o] Error 1
```

The problem boils down to this:
```c
int main()
{
    return __builtin_arm_uqsub16(0, 0);
}
```

The build system tries to compile it with something akin to `clang -cc1 -triple thumbv7-unknown-linux-gnueabihf -target-cpu arm1136jf-s -emit-obj test.c` / `clang -march=armv6 -mthumb -c test.c`.

It compiles to Thumb instruction set, like the rest of the runtime, but selects an ARMv6 processor. That's an invalid combination for the `uqsub16` instruction. It exists in the ARM mode, and it exists in Thumb2 which is available on newer processors. I am not sure what was the intent, CoreCLR is not supported on ARMv6 cores, so the selection of `arm1136jf-s` makes no sense. The newer Raspberry Pis supported by CoreCLR are ARMv7 and have Thumb2 instructions.

### LINKED ISSUE #106585: Package readmes are broken
### Description

Runtime packages have markdown readmes that should be rendered on NuGet gallery page. But latest preview version lost them, there's no package.md file in .nupkg, and NuGet gallery fallbacks to plaintext description. For example, for System.Reflection.Metadata [9.0.0-preview.6.24327.7](https://www.nuget.org/packages/System.Reflection.Metadata/9.0.0-preview.6.24327.7#readme-body-tab) shows markdown readme, but [9.0.0-preview.7.24405.7](https://www.nuget.org/packages/System.Reflection.Metadata/9.0.0-preview.7.24405.7#readme-body-tab) does not.

### Reproduction Steps

Navigate to NuGet gallery page of the package, such as https://www.nuget.org/packages/System.Reflection.Metadata/9.0.0-preview.7.24405.7#readme-body-tab

### Expected behavior

Should show markdown package readme, like for previous version: 

readme-expected

### Actual behavior

Shows plaintext description: 

readme-broken

### Regression?

Broken starting from latest version, 9.0.0-preview.7.24405.7

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #106584

Note that we don't lose any optimized code paths since NEON is enabled:
```
  -- The following features have been enabled:
  
   * CMAKE_BUILD_TYPE, Build type: DEBUG (selected)
   * ACLE_CRC, Support ACLE optimized CRC hash generation, using "-march=armv8-a+crc"
   * NEON_ADLER32, Support NEON instructions in adler32, using "-mfpu=neon"
   * NEON_SLIDEHASH, Support NEON instructions in slide_hash, using "-mfpu=neon"
   * WITH_GZFILEOP, Compile with support for gzFile related functions
   * ZLIB_COMPAT, Compile with zlib compatible API
   * WITH_SANITIZER, Enable sanitizer support
   * WITH_GTEST, Build gtest_zlib
   * WITH_OPTIM, Build with optimisation
   * WITH_NEW_STRATEGIES, Use new strategies
   * WITH_ACLE, Build with ACLE
   * WITH_NEON, Build with NEON intrinsics
```

On the unsupported ARMv6 Mono builds the system Zlib is used instead.

### CODE REVIEW

**Comment by filipnavara** [comment]
The windows-arm64 build failure is unrelated. It was fixed yesterday by https://github.com/dotnet/runtime/pull/106578.

**Comment by am11** [comment]
> On the unsupported ARMv6 Mono builds the system Zlib is used instead.

nit: it's a community-supported platform, not unsupported. 😉

**Comment by carlossanlop** [comment]
We were already blocking armv6 here, so I am wondering why it is not working: https://github.com/dotnet/runtime/blob/main/eng/native/configureplatform.cmake#L511-L516

**Comment by filipnavara** [comment]
> We were already blocking armv6 here, so I am wondering why it is not working: https://github.com/dotnet/runtime/blob/main/eng/native/configureplatform.cmake#L511-L516

This is ARMv7 system though, so it (correctly) is not blocked.

**Review by carlossanlop — APPROVED** [review]
Thanks for the explanations. The comment seems to be descriptive enough about the mismatch.

If this is not an upstream issue in zlib-ng as you mentioned, but rather an issue in runtime, could you please then open an issue for us to continue the discussion around this mismatch and make sure we get it fixed when the time comes?

**Comment by carlossanlop** [comment]
The CI failure in crossaot is unrelated to your PR and has already been fixed in main: https://github.com/dotnet/runtime/pull/106578

**Comment by carlossanlop** [comment]
/ba-g The CI failure in crossaot is unrelated to your PR and has already been fixed in main: https://github.com/dotnet/runtime/pull/106578

**Comment by filipnavara** [comment]
> could you please then open an issue for us to continue the discussion around this mismatch and make sure we get it fixed when the time comes?

I can open an issue but I don't think there's anything else to fix.

ARMv6 is community supported platform that uses system Zlib. There's no degradation from disabling this code path on the supported ARMv7 platforms since they have NEON available and zlib-ng thus gets the fast paths. We may want to double check what happens when cross-compiling but the PR should certainly not make it worse.

Using thumb instruction set in CoreCLR is conscious choice that is unlikely to be changed.

**Comment by carlossanlop** [comment]
> I can open an issue but I don't think there's anything else to fix.

Alright, no problem, I trust your assessment. Do you have permission to hit the merge button or would you like me to do it?

**Comment by filipnavara** [comment]
> Do you have permission to hit the merge button or would you like me to do it?

Please merge it, I don’t have the permissions. Thanks!

**Comment by carlossanlop** [comment]
I also forgot to ask: do you know if the `runtime-community` azp run tests the affected architecture? Asking in case we should execute a run just for peace of mind.

**Comment by filipnavara** [comment]
It should be covered by the regular runtime tests for linux-arm. If you want to be extra cautious then `/azp run runtime-nativeaot-outerloop` has coverage for the build and runtime paths.

**Comment by carlossanlop** [comment]
All the linux-arm legs passed. I think that should be enough. Thanks.

**Pull request merged**
