### PR TITLE
Remove unused locals in System.ServiceProcess.ServiceController

### PR DESCRIPTION
**Pull request by MattKotsenas**
Remove unused locals and private methods in System.ServiceProcess.ServiceController.

This fixes a part of #30457.

### CODE REVIEW

**Comment by MattKotsenas** [comment]
@danmosemsft, sorry for the bother, but would you be able to recommend a reviewer for this change? I looked at git history but there isn't a long trail of changes to follow. Alternatively; if there's a doc or tool to use to find owners, please let me know. Thanks!

**Comment by MattKotsenas** [comment]
Tagging @Anipik per https://github.com/dotnet/runtime/blob/master/docs/area-owners.md. @Anipik, would you mind taking a look, or suggesting a reviewer when you get a chance? Thanks!

**Review by danmoseley — APPROVED** [review]
If the tests pass, looks good to me. Thanks!

**Comment by danmosemsft** [comment]
Unrelated failures

**Review by Anipik — COMMENTED** [review]
lgtm

**Pull request merged**
