### PR TITLE
Fix test bug in FileSystem.Tests

### LINKED ISSUE #107636: Failing test cases System.IO.FileSystem
I have been recently seeing test case failures relating to System.IO.FileSystem on s390x.
```
[xUnit.net 00:00:10.87]     System.IO.Tests.File_ReadWriteAllBytesAsync.WriteToReadOnlyFileAsync [FAIL]
  Failed System.IO.Tests.File_ReadWriteAllBytesAsync.WriteToReadOnlyFileAsync [3 ms]
  Error Message:
   Assert.Equal() Failure: Collections differ
                          ↓ (pos 4)
Expected: [···, 120, 116, 116, 101, 120, ···]
Actual:   [···, 120, 116]
  Stack Trace:
     at System.IO.Tests.File_ReadWriteAllBytesAsync.WriteToReadOnlyFileAsync() in /home/sanjam/runtime/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/ReadWriteAllBytesAsync.cs:line 128
```

```
[xUnit.net 00:00:10.18]     System.IO.Tests.File_ReadWriteAllBytes.WriteToReadOnlyFile [FAIL]
  Failed System.IO.Tests.File_ReadWriteAllBytes.WriteToReadOnlyFile [1 s]
  Error Message:
   Assert.Equal() Failure: Collections differ
                          ↓ (pos 4)
Expected: [···, 120, 116, 116, 101, 120, ···]
Actual:   [···, 120, 116]
  Stack Trace:
     at System.IO.Tests.File_ReadWriteAllBytes.WriteToReadOnlyFile() in /home/sanjam/runtime/src/libraries/System.Runtime/tests/System.IO.FileSystem.Tests/File/ReadWriteAllBytes.cs:line 117
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /home/sanjam/runtime/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs:line 22
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /home/sanjam/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
   ```
   Although this also fails when running as a extracted test case on x64  (with net9-preview7) 
   The failures were introduced here #103308 
   
   cc: @giritrivedi @omajid @stephentoub @akoeplinger

### PR DESCRIPTION
**Pull request by jozkee**
Fixes https://github.com/dotnet/runtime/issues/107636.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
thanks

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @jozkee !

**Comment by adamsitnik** [comment]
Should we backport it to 9.0 branch?

**Comment by jozkee** [comment]
@saitama951 doesn't seem to be using the 9.0 branch and looks like we don't have any CI tests running as root so it won't affect CI until we do, that's also why this wasn't caught.

**Pull request merged**
