### PR TITLE
Remove the dotnet (1) man page

### PR DESCRIPTION
**Pull request by omajid**
All the man pages, including a different version of dotnet.1, are currently maintained in the dotnet/sdk repo. See
https://github.com/dotnet/sdk/tree/main/documentation/manpages and in particular, the documentation on how those are generated from dotnet/docs repository:
https://github.com/dotnet/sdk/blob/main/documentation/manpages/tool/README.md

This leftover copy of dotnet.1 in this repository is extremely out of date and un-maintained. Lets just delete it.

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
cc: @NikolaMilosavljevic any thoughts on this?

**Comment by omajid** [comment]
If you want to know how out of date this man page is, this line is helpful:

```
.TH "dotnet-cli" "1" "January 2016" "" ""
```

That says this file was last updated in January 2016.... And .NET Core 1.0 itself was released in June of 2016.

**Comment by agocke** [comment]
Yeah... sounds like we should delete this

**Comment by NikolaMilosavljevic** [comment]
While this is an issue, I'm not sure if removal of this man page is the right approach. Customers can install .NET Runtime (including .NET host package) without SDK. We should have a single instance of host man page, installed with .NET host package.

**Comment by omajid** [comment]
Thank you for correcting me.

In this case, perhaps we should delete the copy in the sdk repo? We should also copy (or somehow re-use) the automation we have in the sdk repo to re-generate the man pages so the copy in runtime repo stays up to date.

**Comment by omajid** [comment]
I am not sure what the best path forward here is.

I slept on this for a few months and I still think we should delete this man page. The current version is still woefully out of date. It it not appropriate as a man page for just the host/runtime because it mostly talks about SDK commands like `dotnet-publish`. The list of commands is, again, very out of date (eg, `dotnet-compile`). It doesn't even mention `dotnet --info` or `dotnet --list-runtimes` or `dotnet --list-sdks`. The man page doesn't even say how to use the runtime to run .NET programs using the `dotnet /path/to/some/Program.dll`. If someone actually finds this documentation useful, perhaps we should wait for them to file an issue and then we can revert this change and actually update the docs?

In the future when everyone builds and ships .NET using the VMR, perhaps Microsoft can build the host package using the man page copies that are currently in the SDK repo?

**Review by agocke — APPROVED** [review]

**Pull request merged**
