### PR TITLE
Enable activation injection for unix

### PR DESCRIPTION
**Pull request by eterekhin**

### CODE REVIEW

**Comment by eterekhin** [comment]
@hoyosjs, Hello! May I ask you to look at this change?
It's for https://github.com/dotnet/runtime/issues/33561

**Comment by janvorli** [comment]
I wonder why we haven't enabled that right away when adding the activation injection support. I have a feeling that there was some problem, but I can easily be wrong as it was a long time ago. 
@eterekhin can you please share what testing have you done to verify that it works as expected?

**Comment by hoyosjs** [comment]
Sorry - I was out of office and this fell through the cracks. This feels OK, but Jan knows more of the nuances of injection for suspension. The lion's share of issues here will likely be in testing.

**Comment by janvorli** [comment]
@eterekhin thank you for the details, that looks as a sufficient testing to me. Can you please update the branch to the latest main so that it can be merged?

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by eterekhin** [comment]
Thanks a lot for review!

**Pull request merged**
