### PR TITLE
Fix retry when downloading clang tools

### LINKED ISSUE #57196: Formatting jobs fails in CI
I'm not touching anything in the runtime and still the formatting job fails: https://dev.azure.com/dnceng/public/_build/results?buildId=1287580&view=logs&jobId=db5b9618-eefc-58e8-4554-fbce452d4dac&j=db5b9618-eefc-58e8-4554-fbce452d4dac&t=29bb2718-3138-535b-c6ac-1a4597023815

```
Downloading https://raw.githubusercontent.com/dotnet/jitutils/main/bootstrap.cmd to C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\bootstrap.cmd
Convert C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\bootstrap.cmd to Windows line endings
Running: C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\bootstrap.cmd
Running: C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\jitutils\bin\jit-format.bat -a x64 -b Checked -o windows -c D:\a\1\s\src\coreclr --verbose --projects dll
Running: C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\jitutils\bin\jit-format.bat -a x64 -b Checked -o windows -c D:\a\1\s\src\coreclr --verbose --projects standalone
Running: C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\jitutils\bin\jit-format.bat -a x64 -b Checked -o windows -c D:\a\1\s\src\coreclr --verbose --projects crossgen
Running: C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\jitutils\bin\jit-format.bat -a x64 -b Debug -o windows -c D:\a\1\s\src\coreclr --verbose --projects dll
Running: C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\jitutils\bin\jit-format.bat -a x64 -b Debug -o windows -c D:\a\1\s\src\coreclr --verbose --projects standalone
Running: C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\jitutils\bin\jit-format.bat -a x64 -b Debug -o windows -c D:\a\1\s\src\coreclr --verbose --projects crossgen
Running: C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\jitutils\bin\jit-format.bat -a x64 -b Release -o windows -c D:\a\1\s\src\coreclr --verbose --projects dll
Running: C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\jitutils\bin\jit-format.bat -a x64 -b Release -o windows -c D:\a\1\s\src\coreclr --verbose --projects standalone
Running: C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\jitutils\bin\jit-format.bat -a x64 -b Release -o windows -c D:\a\1\s\src\coreclr --verbose --projects crossgen
Creating patch file D:\a\1\s\src\coreclr\format.patch
Deleting C:\Users\VSSADM~1\AppData\Local\Temp\tmp9r8m9v72\bootstrap.cmd
There were errors in formatting. Please run jit-format locally with: 

	jit-format -a x64 -b Checked -o windows -c <absolute-path-to-coreclr> --verbose --fix --projects dll


Or download and apply generated patch:
1. From the GitHub 'Checks' page on the Pull Request, with the failing Formatting
   job selected (e.g., 'Formatting Linux x64'), click the 'View more details on
   Azure Pipelines' link.
2. Select the '1 artifact produced' at the end of the log.
3. Artifacts are located in alphabetical order, target artifact name is
   'format.<OS>.<architecture>.patch.'. Find appropriate format patch artifact.
4. On the right side of the artifact there is a 'More actions' menu shown by a
   vertical three-dot symbol. Click on it and select 'Download artifacts' option.
5. Unzip the patch file.
6. git apply format.patch
##[error](NETCORE_ENGINEERING_TELEMETRY=Build) Format job found errors, please apply the format patch.
##[error]The process 'C:\hostedtoolcache\windows\Python\3.9.6\x64\python.exe' failed with exit code 4294967295
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
Invoke-WebRequest throws an exception when the download fails, so we
should use try-catch instead of status code to check failure.

In addition pass -PassThru to avoid leaving a corrupted download file in
case the download fails. This will buffer the download and write it once
at the end.

Fix #57196

I used [clumsy](https://github.com/jagt/clumsy) to verify that this works. In those tests I also noticed that on PowerShell 7, Invoke-WebRequest with -OutFile but without -PassThru sometimes does not detect when the download fails. It seems to work reliably with -PassThru though. There is already an issue for it: https://github.com/PowerShell/PowerShell/issues/16122

### CODE REVIEW

**Comment by EgorBo** [comment]
I wonder if we can easily re-use [this](https://github.com/dotnet/runtime/blob/main/eng/common/tools.ps1#L239-L262) function there

**Comment by jakobbotsch** [comment]
> I wonder if we can easily re-use this function there

Good idea! Done.

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
Thanks for fixing this!

**Review by ViktorHofer — COMMENTED** [review]
Awesome, thanks.

**Pull request merged**
