### PR TITLE
Add OS loader relocation type statistics to Crossgen2 map file

### PR DESCRIPTION
**Pull request by trylek**

### CODE REVIEW

**Comment by trylek** [comment]
Sample map file for a small test including the reloc type statistics:

https://gist.github.com/trylek/d6347d0fca8baed9f99b67c8a051e2b8

I think that the map file clearly shows that the OS loader relocations stem from the import cells preinitialized to point delay load helper thunks. While this is probably logical, I can easily imagine that patching some 600K cells can easily contribute to composite framework startup in a non-trivial manner, sadly I don't yet see any easy way of fixing this.

**Comment by davidwrighton** [comment]
Well, there is good and bad news here. Its good to know that the relocs are primarily or possibly even exclusively associated with import tables.

From looking at some crossgen1 images, crossgen1 appears to have 1/3 the amount of relocs, so it must be plausible to reduce the reloc count. In addition, there is also the detail that this kind of data could in theory be reloc'd using the method fixup list instead of relying on the relocs to be handled by the OS. If we play our cards right its plausible to do better than the OS reloc mechanism both in file size, and startup time.

**Review by davidwrighton — APPROVED** [review]

**Comment by trylek** [comment]
Thanks @davidwrighton for your comments; I agree that we might be able to distribute some of the startup cost by means of using late initialization via method fixups. In fact I think that it's somewhat related to your other observation regarding the number of imports in comparison with Crossgen1 - current CG2 implementation still has the logic I originally put in based on @jkotas' old R2R design doc - the virtual dispatch import cells are duplicated per call site to improve throughput in case the individual call sites converge on different prevalent callee addresses in the steady state. It might be useful to add a tuning option to Crossgen2 to suppress this logic and analyze the perf and size differences to get a better reading on the effects of this optimization.

**Pull request merged**
