### PR TITLE
[wasi] Fixes to enable more tests

### PR DESCRIPTION
**Pull request by radical**
## [wasi] Copy WasmFilesToIncludeInFileSystem to the bundle too

This could be changed in the future to include in the single file bundle.
- This fixes `System.IO.Packaging`, and `System.Data.DataSetExtensions` tests.

## WasiAppBuilder: Create an empty /tmp

And enable `System.Runtime.Serialization.Xml.Tests`, and `System.Runtime.Serialization.Xml.ReflectionOnly.Tests`

TODO: single file case

### CODE REVIEW

**Review by pavelsavara — CHANGES_REQUESTED** [review]
I would like to differentiate the `WasmFilesToIncludeInFileSystem` vs `WasmExtraFilesToDeploy`.
For browser `WasmFilesToIncludeInFileSystem` is to  VFS and `WasmExtraFilesToDeploy` is to web server.
For wasi VFS doesn't exist [and we don't plan it](https://github.com/dotnet/runtime/issues/81418). And there is no web server.

Could we have other property which would do "copy to output" under different name in WASI ?

**Comment by pavelsavara** [comment]
@maraf could you please chime in for the new Razor static assets ?

**Comment by maraf** [comment]
StaticWebAssets will replace WasmExtraFilesToDeploy. I agree to have a different property WASI "files".

**Comment by radical** [comment]
So, this is temporary to get the tests working.

**Comment by pavelsavara** [comment]
> So, this is temporary to get the tests working.

Makes sense. Could you please open issue for that and put link into the code at right places. Thanks!

**Comment by radical** [comment]
> > So, this is temporary to get the tests working.
> 
> Makes sense. Could you please open issue for that and put link into the code at right places. Thanks!

Opened https://github.com/dotnet/runtime/issues/83108 . Reference at specific places in the code isn't needed.

**Review by pavelsavara — APPROVED** [review]
good as temporary solution to unblock testing

**Pull request merged**
