### PR TITLE
[release/8.0-staging][mono][debugger] Fix inspect Span<byte>

### PR DESCRIPTION
**Pull request by thaystg**
Backport of https://github.com/dotnet/runtime/pull/99843 to release/8.0-staging

## Customer Impact

- [X] Customer reported
- [ ] Found internally

Reported by customers in https://github.com/xamarin/xamarin-android/issues/8792. While debugging a MAUI/Blazor Wasm app and it's paused in a breakpoint/stepping and there is any local that is of type Span<T> the runtime will throw an assertion and finish the debugging session.

## Regression

- [X] Yes it works on .NET 7
- [ ] No

## Testing
- Manually tested.
- Unit tests were added to prevent the fix from regressing.

## Risk

Low. The change only checks if the value that is coming from SDB is NULL and then do not throw the assertion.

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
@thaystg looks like the bot didn't put the backport template in the description for some reason

**Review by jeffschwMSFT — APPROVED** [review]
approved. we will take for consideration in 8.0.x

**Comment by AArnott** [comment]
@jeffschwMSFT I'd sure love for this to be taken. It's completely blocking testing an android app that I've been (personally) developing.

**Comment by jeffschwMSFT** [comment]
it is approved for 8.0.5 shipping in May

**Pull request merged**
