### PR TITLE
[release/5.0] Backport nullability annotations to release/5.0

### PR DESCRIPTION
**Pull request by carlossanlop**
Do not merge yet.

This PR will backport the following master PRs (unchecked = still in review):

- [x] https://github.com/dotnet/runtime/pull/41541 Add nullable annotations for XmlDataDocument @terrajobst 
- [x] https://github.com/dotnet/runtime/pull/41476 Nullable annotations for System.Runtime.Serialization.Xml and System.Runtime.Serialization.Json @eerhardt 
- [x] https://github.com/dotnet/runtime/pull/41474 Port nullability annotations to refs XmlDocument and XmlSerializer @Jozkee
- [x] https://github.com/dotnet/runtime/pull/41086 Port nullability annotations from System.Private.Xml.Linq to contracts - @Jozkee
- [x] https://github.com/dotnet/runtime/pull/40744 Add nullability annotations to System.Private.Xml.Linq project - @Jozkee 
- [x] https://github.com/dotnet/runtime/pull/41060 Enable nullability on System.Xml.XPath - @Jozkee 
- [x] https://github.com/dotnet/runtime/pull/41079 Change nullability of public IXmlNamespaceResolver parameters where appropriate - @Jozkee 
- [x] https://github.com/dotnet/runtime/pull/41082 Annotate DbDataReader.GetSchemaTable as nullable - @roji 
- [x] https://github.com/dotnet/runtime/pull/41189 Nullability annotations for HttpListener - @pgovind 
- [x] https://github.com/dotnet/runtime/pull/41083 Port nullability annotations to System.Xml.ReaderWriter contract - @Jozkee
- [x] https://github.com/dotnet/runtime/pull/41261 Nullable: System.Xml, part 7 (Serialization) - @krwq
- [x] https://github.com/dotnet/runtime/pull/41438 Globally enable nullability in XML @krwq
- [x] https://github.com/dotnet/runtime/pull/41481 Switch text param to nullable in WriteProcessingInstructionAsync @Jozkee 
- [x] https://github.com/dotnet/runtime/pull/41488 Switch Markup property to XmlNode?[]? to reflect it can contain null elements @Jozkee 
- ~~https://github.com/dotnet/runtime/pull/41382 Fix null check in S.Diagnostics.Contract regressed by nullability annotations~~ @krwq - Bug fix, must approve separately.
- ~~System.ComponentModel.TypeConverter~~  @safern - Skipping. Will target 6.0.

### CODE REVIEW

**Comment by krwq** [comment]
@carlossanlop please also add https://github.com/dotnet/runtime/pull/41315

**Comment by carlossanlop** [comment]
> @carlossanlop Carlos Sanchez Lopez FTE please also add #41315

No need, @krwq, because @danmosemsft automatically backported it with the [bot comment](https://github.com/dotnet/runtime/pull/41315#issuecomment-680170802): https://github.com/dotnet/runtime/commit/2aa627b7cf8cc1c697f916c7cd6e76fa52b69576

**Comment by carlossanlop** [comment]
I force-updated this branch to the latest changes in dotnet/release5.0 , you can see change https://github.com/dotnet/runtime/pull/41315 is already included in the commit history.

**Comment by krwq** [comment]
I've added:

#41438 Globally enable nullability in XML
#41382 Fix null check in S.Diagnostics.Contract regressed by nullability annotations

to your list

**Review by roji — APPROVED** [review]
OK for the System.Data parts, thanks!

**Comment by jkotas** [comment]
@krwq Should #41382 be treated separately? #41382 is a real bug that needs to be fixed for 5.0 vs. the rest is just adding more annotations that may or may not meet the bar for .NET 5 at this point.

**Comment by jeffhandley** [comment]
> @krwq Should #41382 be treated separately? #41382 is a real bug that needs to be fixed for 5.0 vs. the rest is just adding more annotations that may or may not meet the bar for .NET 5 at this point.

We've gotten tactics approval to merge this PR in on Monday (August 31st) with however far we get through the remaining annotations--including them all in RC1.  But it's certainly better to separate the bug fix into a separate PR.

@carlossanlop can you remove #41382 from this PR and create a separate port PR for that please?  The port bot should be able to do its magic on that one.

**Comment by ericstj** [comment]
I have reviewed all current commits in this PR as well as linked PR #41541.  This is approved for release/5.0 (previously approved by Tactics).  You are good to go from my side assuming a simple cherry-pick for that last PR.  I'll also be online to have another look if you'd like.

**Comment by ericstj** [comment]
Removing auto-merge since it actually squashes where we want this PR to be merged not squashed.

**Review by jeffhandley — APPROVED** [review]

**Review by ericstj — APPROVED** [review]

**Pull request merged**
