### PR TITLE
Fix Array.Sort in the presence of nulls

### LINKED ISSUE #41235: Array.Sort ( .NET 5.0 Preview 7 ) generates wrong result for a sample data set.
**Array.Sort(sample)** ( .NET 5.0 Preview 7 ) generates wrong result for a sample data set.

The sample data set is a string[] with the _Namespaces_ for each Type in .NET.
This is 8500+ items, including a lot of nulls and repetitions.

I did a short test by modification of the current **Array.Sort** code in the **.NET Core Source Browser.**
I removed the **PartitionSort** part and left only the **HeapSort** for the entire sort.
With the **HeapSort** the result is correct.

Using Visual Studio 2019 version 16.8 with .NET 5.0 Preview 7.
I can provide the sample data set if that helps.

### PR DESCRIPTION
**Pull request by svick**
Fixes https://github.com/dotnet/runtime/issues/41235.

This was introduced by https://github.com/dotnet/runtime/pull/35297/files#diff-54c667fe59347842036834f5b31c5411L513-R477. Notice that the first `while` loop stays `== null`, but the second one incorrectly changes from `!= null` to `== null`.

I think this is a fairly serious bug that should be fixed in 5.0, but as I understand it, master already targets 6.0. Should I rebase and retarget this PR to the release/5.0 branch?

cc: @stephentoub

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
@svick Thank you!

**Comment by jkotas** [comment]
>  Should I rebase and retarget this PR to the release/5.0 branch?

All changes go to master. We backport from master as necessary.

**Comment by jkotas** [comment]
Tes failures are #38159 and #41078

**Comment by danmosemsft** [comment]
Shoukd we have more test combinations, given this involves the complexity of pivots, etc?

**Comment by jeffhandley** [comment]
I added a tracking issue https://github.com/dotnet/runtime/issues/41376 for adding more test combinations.

**Pull request merged**
