### PR TITLE
[NativeAOT] Fix System.Collections.Immutable.Tests

### PR DESCRIPTION
**Pull request by VSadov**
Seems like immutable collections tests are broken again, 
at least when run locally.

Let's see if it is a local issue or the tests are indeed broken.

### CODE REVIEW

**Comment by VSadov** [comment]
perhaps a testcase issue with some incompatible use of reflection that requires adding more stuff to rd.xml

**Comment by VSadov** [comment]
```
System.NotSupportedException : 'Xunit.Sdk.AssertEqualityComparer`1[System.Collections.Generic.HashSet`1[System.Collections.Generic.KeyValuePair`2[System.ValueTup
  le`2[System.Collections.Frozen.Tests.SimpleNonComparableStruct, System.Collections.Frozen.Tests.SimpleNonComparableStruct], System.Int32]]].CompareTypedSets[Syst
  em.Collections.Generic.KeyValuePair`2[System.ValueTuple`2[System.Collections.Frozen.Tests.SimpleNonComparableStruct, System.Collections.Frozen.Tests.SimpleNonCom
  parableStruct], System.Int32]](System.Collections.IEnumerable,System.Collections.IEnumerable)' is missing native code. MethodInfo.MakeGenericMethod() is not comp
  atible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativea
  ot-compatibility
```

**Comment by VSadov** [comment]
There are errors on windows in `Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests` that look like:

```

Error message
System.PlatformNotSupportedException : RemoteExecutor is not supported on this platform.


Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments) + 0x4b1
   at Microsoft.Extensions.Hosting.WindowsServiceLifetimeTests.ExceptionOnStopIsPropagated() + 0x73
   at Microsoft.Extensions.Hosting.WindowsServices.Tests!&lt;BaseAddress&gt;+0x85e2f4
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0xe6
```

@MichalStrehovsky - is that supposed to work?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky - is that supposed to work?

We don't currently support it. It is doable, the work just wasn't done. The test should be conditioned on `RemoteExecutor` being supported, like this:

https://github.com/dotnet/runtime/blob/e0120f0e7ed7c393fcffbc1e6ab84cc77f3beaf7/src/libraries/Microsoft.VisualBasic.Core/tests/ProjectDataTests.cs#L51

Maybe we should start running a NativeAot leg on all PRs to this repo. We can now run a leg in 90 minutes or so. It's starting to be somewhat annoying that we need to mop up these things pretty much every week. Or if we could trigger it on any libs test change (not sure if that makes a meaningful difference). @agocke do you have an opinion?

**Comment by VSadov** [comment]
> We don't currently support it. It is doable, the work just wasn't done.

I think that will have little added value, so should not be a priority.

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!

**Comment by VSadov** [comment]
> Maybe we should start running a NativeAot leg on all PRs to this repo. We can now run a leg in 90 minutes or so. It's starting to be somewhat annoying that we need to mop up these things pretty much every week.

Yes. Every time these tests need to run it starts with fixing all kind of issues.
I think running the fastest combination could be useful. 

I've just checked and `./build clr+libs+libs.tests -rc Checked -lc Release /p:TestNativeAot=true -test`  takes ~40min from clean state on a standard M1 with 16Gb memory.

**Comment by VSadov** [comment]
Thanks!!

**Pull request merged**
