### PR TITLE
Moving "Generic Math" in box and making it no longer experimental

### PR DESCRIPTION
**Pull request by tannergooding**
This is pending WPF uptaking a new C++/CLI toolset so they won't break when encountering types that have static abstract interfaces.

This is just moving the preview surface area to be non-preview, it is explicitly not the "final shape" for many of the interfaces and APIs.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by tannergooding** [comment]
Marking as *blocked* until we confirm this won't break WPF. CC. @jeffhandley

**Comment by tannergooding** [comment]
Rebased to remove conflict

**Comment by tannergooding** [comment]
@akoeplinger could you please check/confirm if the mono failures here are related to Static Abstracts in Interfaces?

**Comment by steveisok** [comment]
> @akoeplinger could you please check/confirm if the mono failures here are related to Static Abstracts in Interfaces?

The android failures look infra related and the wasm ones I believe are flaky.  Not sure about the windows build failure:

`LINK : fatal error LNK1181: cannot open input file 'ijwhost.lib'`

**Comment by MaximLipnin** [comment]
> Not sure about the windows build failure:
> 
> `LINK : fatal error LNK1181: cannot open input file 'ijwhost.lib'`

It was hit on the rolling build - https://github.com/dotnet/runtime/issues/66380

**Comment by tannergooding** [comment]
> The android failures look infra related

@steveisok, any way we could confirm this? I'd prefer to not have to back this out after merging since its unblocking a lot of work related to generic math and it shipping in .NET 7.

Most of the failures look to be showing up as:
> System.AggregateException : One or more errors occurred. (Failed to install mobile app.
Expected: True
Actual:   False) (The following constructor parameters did not have matching fixture data: _Global globalVar)
---- Failed to install mobile app.
Expected: True
Actual:   False
---- The following constructor parameters did not have matching fixture data: _Global globalVar

Also seeing a few failures like
> [21:17:57] info: Attempting to install /datadisks/disk1/work/A1EA0909/w/B8F90A60/e/System.Linq.Tests.apk
[21:17:57] dbug: Executing command: '/datadisks/disk1/work/A1EA0909/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.22153.2/runtimes/any/native/adb/linux/adb -s emulator-5556 install /datadisks/disk1/work/A1EA0909/w/B8F90A60/e/System.Linq.Tests.apk'
[21:17:57] fail: Error:
                 Exit code: 1
                 Std out:
                 Performing Streamed Install
>                 
>                 
>                 Std err:
>                 adb: failed to install /datadisks/disk1/work/A1EA0909/w/B8F90A60/e/System.Linq.Tests.apk: cmd: Can't find service: package

And then for WASM:
> [DevOpsReportFailure: Failed to upload results: Error occurred in request., RetryError: HTTPSConnectionPool(host='dev.azure.com', port=443): Max retries exceeded with url: /dnceng/public/_apis/test/Runs/45564706/Results (Caused by ResponseError('too many 503 error responses',))]()

**Comment by steveisok** [comment]
@tannergooding I'm aware of both problems and they are unrelated to your change.

**Comment by tannergooding** [comment]
Thanks!

@agocke, @marek-safar, @jeffhandley are there any other tests or things that could block this from merging on your end?

Everything looks to be passing with the Mono failures being unrelated as indicated above. I don't see any of the tests disabled for NAOT/Mono under https://github.com/dotnet/runtime/blob/main/src/tests/issues.targets either.

**Comment by marek-safar** [comment]
@tannergooding check out https://github.com/dotnet/runtime/blob/main/src/libraries/tests.proj

**Comment by tannergooding** [comment]
>  check out https://github.com/dotnet/runtime/blob/main/src/libraries/tests.proj

Likewise don't see any disablement here. Notably the tests also moved from `System.Runtime.Experimental` to `System.Runtime` so I think existing disablement (if it had existed) would no longer be working.

**Comment by jeffhandley** [comment]
We'll hold off on merging this until VS 17.2 Preview 2 is available. 🔜

**Comment by tannergooding** [comment]
Merging as per offline conversation with @jeffhandley. Now that VS 17.2 Preview 2 is publicly available and contains the C++/CLI fixes, external contributors will no longer be blocked.

https://github.com/dotnet/arcade/issues/8633 tracks the helix support and should only impact WPF for our known dependents.

**Comment by jeffhandley** [comment]
Visual Studio 17.2 Preview 2 is available here:
https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#1720-pre20--visual-studio-2022-version-172-preview-2

**Pull request merged**
