### PR TITLE
System.Runtime.InteropServices readonly annotation

### PR DESCRIPTION
**Pull request by hrrrrustic**
This PR is a part of #46675

### CODE REVIEW

**Comment by jeffhandley** [comment]
This PR is being marked as a draft per https://github.com/dotnet/runtime/pull/46675#issuecomment-828694665.

**Comment by jkotas** [comment]
@hrrrrustic Could you please change this one to mark the whole type as readonly instead?

**Comment by hrrrrustic** [comment]
@jkotas Done

**Review by jkotas — APPROVED** [review]

**Comment by jkotas** [comment]
Failures are known issue #52031

**Pull request merged**
