### PR TITLE
Rewrite XslNumber.ConvertToDecimal

### PR DESCRIPTION
**Pull request by huoyaoyuan**
Split from #54103 
This is to remove a dependency to XPathConvert.DoubleToString. I don't know if there are test for this.

### CODE REVIEW

**Comment by jeffhandley** [comment]
@krwq This PR is assigned to you for follow-up/decision before the RC1 snap.

**Comment by krwq** [comment]
We should consider merging this after RC1 snap. Marking as *no merge* for now

**Comment by jeffhandley** [comment]
> We should consider merging this after RC1 snap. Marking as _no merge_ for now

@krwq Can you take a look at this again now that `main` targets .NET 7.0? Thanks!

**Comment by eiriktsarpalis** [comment]
Bump. I think we can take another look at this now.

**Comment by krwq** [comment]
We need some perf measurements here. Current version because of all of the NumberFormatInfo related allocations might be slower than original

**Comment by huoyaoyuan** [comment]
Sorry, I have no time to do the measurement recently.

**Pull request closed without merging**
