### PR TITLE
Do not run validation on runtime determined types

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
It doesn't seem like we validate anything for those, the `IsRuntimeDeterminedSubtype` check is rather expensive, and the full AOT compiler would definitely prefer to crash if those enter the system as opposed to taking the "input is valid" code paths.

### CODE REVIEW

**Comment by jkotas** [comment]
Hmmm, would it be better to fix the R2R compiler so that these do not enter the system in R2R mode either?

**Comment by MichalStrehovsky** [comment]
> Hmmm, would it be better to fix the R2R compiler so that these do not enter the system in R2R mode either?

That would definitely be a better fix. I'm hoping Fadi will remember why we needed to call validation from places that deal with runtime determined types and uninstantiated generics (I assume that's where the GenericParameterDesc handling comes from).

**Comment by fadimounir** [comment]
> I'm hoping Fadi will remember why we needed to call validation from places that deal with runtime determined types and uninstantiated generics 

> Hmmm, would it be better to fix the R2R compiler so that these do not enter the system in R2R mode either?

The idea behind the various places where we call the validation is to attempt to load/parse certain properties of the various types and methods, such that whenever we encounter invalid types/methods, we can throw typesystem exceptions before we get to the node emission phase. This would cause us to skip compiling the problematic methods instead of crashing the compiler (now we have a similar behavior to crossgen1).

I think it should be possible to filter out RDST and generic definition types at the root level:
```c#
        public void EnsureLoadableType(TypeDesc type)
        {
            if (!type.IsGenericDefinition && !type.IsRuntimeDeterminedSubtype)
                _validTypes.GetOrCreateValue(type);
        }
```

**Comment by MichalStrehovsky** [comment]
> I think it should be possible to filter out RDST and generic definition types at the root level:

Are runtime determined things entering the validation system from anywhere else than the references to `EnsureLoadable` in GenericLookupSignature.cs? If we're not going to validate anything (which we're not), we might as well not call into the validation from there.

**Comment by fadimounir** [comment]
> If we're not going to validate anything (which we're not), we might as well not call into the validation from there.

We can do that, but these calls are scattered in a couple of places. Wouldn't it be easier to just make a single change in `CompilerTypeSystemContext.Validation.cs` to skip those, instead of adding the check in all the places where we call `EnsureLoadable`?

**Comment by MichalStrehovsky** [comment]
> We can do that, but these calls are scattered in a couple of places.

Which ones? I just built CoreCLR and crossgen2, set a breakpoint to when EnsureLoadable is called with runtime determined things and compiled CoreLib with it. The only places that called EnsureLoadable with runtime determined types were in GenericLookupSignature. Since these are generic lookups, I assume they'll all be runtime determined by definition.

Seems like what we need to do:
1. Delete the calls to validation in GenericLookupSignature - since these are all expected to be runtime determined, we wouldn't validate anything.
2. Delete handling of runtime determined stuff in validation
3. Profit: less code to maintain and faster validation

Am I missing something?

**Comment by fadimounir** [comment]
> Am I missing something?

Thanks Michal for your validation work. Your plan regarding RDSTs seems reasonable to me, however we will need to run your fix against the P1 tests before we commit anything, since s.p.corelib does not cover all cases. JanV and I found a couple of P1 tests that were failing on such validations due to the RDSTs. It would be good to validate that all of them were coming from the GenericLookupSignature (can't think of a reason why they would come from anywhere else, but let's check that)

Also regarding the GenericParameter types, we still need to filter these out. For instance, there was a P1 test where the validation was failing because we hit EcmaGenericParameter types while validating a method. This has more to do with the question of "can i load method MyType<T>.Func"? etc...

**Comment by MichalStrehovsky** [comment]
> however we will need to run your fix against the P1 tests

@trylek Is there maybe already a way to kick off P1 tests on crossgen2 with a pull request? Or should I test this locally?

**Comment by trylek** [comment]
@MichalStrehovsky You can use the build definition runtime-coreclr crossgen2 outerloop,

https://dev.azure.com/dnceng/public/_build?definitionId=701&_a=summary

entering "refs/pull/1357/head" into the Branch field. Without a PR, you need to push your private branch to upstream and then select it in the Branch combo box.

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky You can use the build definition runtime-coreclr crossgen2 outerloop,

Very cool! Thank you!

@fadimounir @janvorli Seems like we got the results back - there are [a couple failures](https://dev.azure.com/dnceng/public/_build/results?buildId=487905&view=ms.vss-test-web.build-test-results-tab&runId=15539986&resultId=109781&paneView=work-items) - do you know if all of these are known or whether I need to have a look at some of them?

**Comment by janvorli** [comment]
@MichalStrehovsky 
Windows and Linux:
* self_override5 is a know issue that @fadimounir is going to work on
* ObjectStackAllocationTests is won't fix - it is failing since it depends on COMPlus_JitObjectStackAllocation being set to 1. I’ve verified that manually modifying the tests .rsp file by adding that JIT option and re-running crossgen2 fixes it.
* ThreadStartSByte failure is unknown to me - fails with System.IO.FileNotFoundException, so it seems most likely related to the SuperILC created directory structure.
* bytemark failure is unknown to me - fails with System.IO.FileNotFoundException, so it seems most likely related to the SuperILC created directory structure.
* b426654 is a known failure that @trylek is looking into
* tracelogging failure seems to happen even without R2R
* DevDiv_374539 is a known compilation timeout (it takes 42 minutes on my machine to complete) due to deep recursive generic instantiatons (end up compiling about 128000 instantiations)
* LdfldaHack is a known runtime issue caused by a JIT problem

Linux only:
* HugeArray1 failure is unknown to me - timeout
* HugeField2 failure is unknown to me - timeout
* 10w5d_cs_do  failure is unknown to me - fails with `Managed assembly not found: No such file or directory`. It seems to be most likely a problem with directory structure created by SuperILC.
* superpmicollect failure is unknown to me - but it fails due to invoking the 10w5d_cs_do above.

**Comment by janvorli** [comment]
Actually, the tracelogging failure is a compilation issue, so it is unrelated to the failures without R2R in the same test.
It fails with
`Error: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: netstandard
Internal.TypeSystem.TypeSystemException+FileNotFoundException: [TEMPORARY EXCEPTION MESSAGE] FileLoadErrorGeneric: netstandard`

**Comment by janvorli** [comment]
Hmm, I am sorry, we are not running the tests using SuperILC, so all of the file not found issues cannot be due to the SuperILC directory structure.

**Comment by MichalStrehovsky** [comment]
@janvorli Thanks! I'll have a look at the FileNotFoundException ones to to figure out what it is. The timeouts seem unlikely to be caused by this change. The HugeArray1 I know from when we were bringing these tests up on CoreRT long time ago - it indeed takes a really long time to compile.

**Review by fadimounir — APPROVED** [review]

**Comment by fadimounir** [comment]
@MichalStrehovsky I think you can go ahead and merge this if you wanted, without blocking on the current test results, because they seem unrelated to the validation fix.

**Comment by trylek** [comment]
@janvorli - as concerns Helix vs. SuperIlc, that can easily affect the failures - for some reason we may be missing some artifacts when publishing the built tests to Helix that we happen to be properly picking up in SuperIlc runs due to its internal subfolder copying rules i.e. the tests happily pass in your local SuperIlc runs and only fail in Helix. If the same tests weren't failing in Crossgen1 Helix testing, that would however disprove this theory.

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky I think you can go ahead and merge this if you wanted, without blocking on the current test results, because they seem unrelated to the validation fix.

Great, thank you!

**Pull request merged**
