### PR TITLE
Update ByteArrayContent ctor with uint casts

### PR DESCRIPTION
**Pull request by hrrrrustic**

### CODE REVIEW

**Review by karelz — COMMENTED** [review]
The original code is easier to read and maintain. Is the saved instruction really worth the "complexity" here? ... Personally I don't think so.

At least we have tests covering the negative inputs:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Http/tests/FunctionalTests/ByteArrayContentTest.cs#L42
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Http/tests/FunctionalTests/ByteArrayContentTest.cs#L60

**Comment by gfoidl** [comment]
> The original code is easier to read and maintain. Is the saved instruction really worth the "complexity" here?

Can we teach the JIT to recognize such patterns and perform this optimization for us?

**Comment by hrrrrustic** [comment]
> Is the saved instruction really worth the "complexity" here? ... Personally I don't think so.

I saw a lot of places where such validations were written with `uint` casts (Spans, String/ArraySegment, string.Substring, etc)
So I decided that's a common practice across whole libs
If it's not worth it right here - that's ok, just close PR 😄

**Comment by karelz** [comment]
Triage: Given that the perf impact won't be measurable in the scenario, it can go either way (based on team discussion).
I would suggest to close it. Let's focus on changes that make difference for customers ;)

**Comment by antonfirsov** [comment]
Yet another personal opinion: I generally dislike microoptimizations on cold path. Readability and maintainability is more important, if the optimization itself doesn't make a measurable difference.

**Pull request closed without merging**
