### PR TITLE
Make JitPrintInlinedMethods less verbose

### PR DESCRIPTION
**Pull request by EgorBo**
Was:

image

Now:

image

We can also introduce a verbosity level e.g. to only print successful inlinees after [guarded] devirtualizations. The goal is to allow developers to easily find out which call-sites were devirtualized (_and inlined because devirtualization without inlining is not interesting_) with PGO and which were not.

cc @dotnet/jit-contrib @AndyAyersMS

### CODE REVIEW

**Comment by jakobbotsch** [comment]
I'm not a fan of removing the ordinal and IL offset, I've been using those a lot in my debug info work. Can we keep those?

**Comment by EgorBo** [comment]
> I'm not a fan of removing the ordinal and IL offset, I've been using those a lot in my debug info work. Can we keep those?

I can make the "verbose mode" to be default. Since we're going to publish a Checked jit for external developers I'd love it to be more friendly and less verbose for them at least with an additional config switch. Especially when ="*" mode is used.

**Comment by jakobbotsch** [comment]
> > I'm not a fan of removing the ordinal and IL offset, I've been using those a lot in my debug info work. Can we keep those?
> 
> I can make the "verbose mode" to be default. Since we're going to publish a Checked jit for external developers I'd love it to be more friendly and less verbose for them at least with an additional config switch. Especially when ="*" mode is used.

Do we expect external developers to use the full JitDump mode? If we had a separate variable to report the things that may be interesting for external devs then we could have the less verbose output for this mode, and keep the more verbose mode for JitDump.

**Comment by EgorBo** [comment]
> > > I'm not a fan of removing the ordinal and IL offset, I've been using those a lot in my debug info work. Can we keep those?
> > 
> > 
> > I can make the "verbose mode" to be default. Since we're going to publish a Checked jit for external developers I'd love it to be more friendly and less verbose for them at least with an additional config switch. Especially when ="*" mode is used.
> 
> Do we expect external developers to use the full JitDump mode? If we had a separate variable to report the things that may be interesting for external devs then we could have the less verbose output for this mode, and keep the more verbose mode for JitDump.

It's not part of JitDump, it's printed for `DOTNET_JitPrintInlinedMethods=Test` (or `DOTNET_JitPrintInlinedMethods=*`).

**Comment by jakobbotsch** [comment]
> It's not part of JitDump, it's printed for DOTNET_JitPrintInlinedMethods=Test (or DOTNET_JitPrintInlinedMethods=*).

The inline tree is also printed in JitDump using this code.

**Comment by jakobbotsch** [comment]
Maybe pass `verbose` parameter to `InlineStrategy::Dump` and `InlineContext::Dump` for JitDump case? Then we can get rid of the new COMPlus variable too, I think the less verbose output makes sense if one is only looking at the inline tree without full jit dump.

**Comment by EgorBo** [comment]
@jakobbotsch good point! addressed in the latest commit.

**Review by jakobbotsch — APPROVED** [review]
I would personally prefer that "leaf" methods like these do not change behavior based on environment variables, e.g. using a `verbose` parameter instead (similar to what is already happening in `InlineStrategy::Dump` with its `showBudget`  parameter). But that's not terribly important, if you prefer it this way that's fine with me.

**Pull request merged**
