### PR TITLE
Big-endian fixes: PDB creation by ilasm

### PR DESCRIPTION
**Pull request by uweigand**
* Fix byte order of debug directory fields

* Fix byte order of PDB stream data (PdbHeap::SetData)

### CODE REVIEW

**Comment by JulieLeeMSFT** [comment]
CC @dotnet/jit-contrib PTAL. Community request to backport to .NET 6 RC2.

**Review by BruceForstall — APPROVED** [review]
LGTM

**Comment by BruceForstall** [comment]
The failures are https://github.com/dotnet/runtime/issues/58481

**Pull request merged**
