### PR TITLE
Remove the rest of the SimdAsHWIntrinsic support

### PR DESCRIPTION
**Pull request by tannergooding**
This removes quite a bit of complexity and ensures that `Vector<T>` handling is identical to the handling for the fixed sized vector types on exposed APIs.

### CODE REVIEW

**Comment by tannergooding** [comment]
This one is for .NET 10 only, it does not need backport

**Review by EgorBo — APPROVED** [review]
Nice clean up! I've noticed some missing ternary ops (avx512) among the regressions but I guess it's not a big deal

**Comment by tannergooding** [comment]
> I've noticed some missing ternary ops (avx512) among the regressions but I guess it's not a big deal

Yeah, we've got a tracking issue for those: https://github.com/dotnet/runtime/issues/107619 and https://github.com/dotnet/runtime/issues/90075

We get a lot of the cases, but there's a bit of slightly more advanced folding we still want to handle

**Review by kunalspathak — APPROVED** [review]
LGTM

**Pull request merged**
