### PR TITLE
Fix various asserts that were found by Antigen

### PR DESCRIPTION
**Pull request by tannergooding**
These were found by antigen (https://dev.azure.com/dnceng-public/public/_build/results?buildId=732346&view=ms.vss-build-web.run-extensions-tab), however the test cases are massive and often not trivially simplified so there isn't an easy way to add regression coverage here.

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @dotnet/jit-contrib This should be ready for review and fixes a few asserts that were caught by antigen.

SPMI replay failure is https://github.com/dotnet/runtime/issues/104585

**Comment by tannergooding** [comment]
Rerunning now that the SPMI replay issue should be fixed.

**Review by jakobbotsch — APPROVED** [review]

**Comment by kunalspathak** [comment]
Can we add some test cases, if they were just caught by Antigen but not by P0/P1 test suite?

**Comment by tannergooding** [comment]
> Can we add some test cases, if they were just caught by Antigen but not by P0/P1 test suite?

It was explicitly commented at the top that most of these were not something for which simplified reproduction could be identified.

They often repro because the antigen source generated is massive and impacts the JIT in weird ways, particularly in how some optimizations/transforms may light up for parts of a method, but not the rest.

For most of them, the JIT never gets to an incorrect sequence otherwise because everything else was already correct or would be coerced to be correct under the default transforms

**Comment by tannergooding** [comment]
Happy for tests to be added if someone knows a way to coerce the JIT to do the right partial transforms here, but I had already spent a couple hours playing around with C# that should trigger it but wouldn’t, even with some of the config knobs that do things like disable vn or cse to try and get it into the right shape for codegen/lowering

**Pull request merged**
