### PR TITLE
[mono][arm] Fix rethrow instruction size

### LINKED ISSUE #76192: [android] `unknown opcode name for 400`, only workaround is UseInterpreter=true
### Description

My app crashes on a `Pax A920 Pro` with:

```
09-12 15:18:08.578  9672  9672 E         : unknown opcode name for 400
--------- beginning of crash
09-12 15:18:08.579  9672  9672 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 9672 (nyname.mauiapp9), pid 9672 (nyname.mauiapp9)
09-12 15:18:08.672  9691  9691 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
09-12 15:18:08.673   475   475 I /system/bin/tombstoned: received crash request for pid 9672
09-12 15:18:08.674  9691  9691 I crash_dump32: performing dump of process 9672 (target tid = 9672)
09-12 15:18:08.675  9691  9691 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-12 15:18:08.675  9691  9691 F DEBUG   : Native Crash TIME: 25743471
09-12 15:18:08.675  9691  9691 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-12 15:18:08.675  9691  9691 F DEBUG   : Build fingerprint: 'PAX/A50/A50:8.1.0/OPM2.171019.012/10:user/release-keys'
09-12 15:18:08.675  9691  9691 F DEBUG   : Revision: '0'
09-12 15:18:08.675  9691  9691 F DEBUG   : ABI: 'arm'
09-12 15:18:08.675  9691  9691 F DEBUG   : pid: 9672, tid: 9672, name: nyname.mauiapp9  >>> com.companyname.mauiapp9 <<<
09-12 15:18:08.675  9691  9691 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-12 15:18:08.677  9691  9691 F DEBUG   :     r0 00000000  r1 000025c8  r2 00000006  r3 00000008
09-12 15:18:08.677  9691  9691 F DEBUG   :     r4 000025c8  r5 000025c8  r6 bea181cc  r7 0000010c
09-12 15:18:08.677  9691  9691 F DEBUG   :     r8 00000000  r9 910200c9  sl 8f3f46e8  fp a286e680
09-12 15:18:08.677  9691  9691 F DEBUG   :     ip bea181f0  sp bea181b8  lr b0b3dc1b  pc b0b37734  cpsr 20000030
09-12 15:18:08.690  9691  9691 F DEBUG   : 
09-12 15:18:08.690  9691  9691 F DEBUG   : backtrace:
09-12 15:18:08.691  9691  9691 F DEBUG   :     #00 pc 00019734  /system/lib/libc.so (abort+63)
09-12 15:18:08.691  9691  9691 F DEBUG   :     dotnet/maui#1 pc 0001c10b  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x195b000)
09-12 15:18:08.691  9691  9691 F DEBUG   :     dotnet/maui#2 pc 00094051  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.691  9691  9691 F DEBUG   :     dotnet/maui#3 pc 001775e1  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.691  9691  9691 F DEBUG   :     dotnet/maui#4 pc 00177569  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.691  9691  9691 F DEBUG   :     dotnet/maui#5 pc 0017761f  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.691  9691  9691 F DEBUG   :     dotnet/maui#6 pc 001095b3  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.691  9691  9691 F DEBUG   :     dotnet/maui#7 pc 00153ef7  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.691  9691  9691 F DEBUG   :     dotnet/maui#8 pc 000cf10f  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.691  9691  9691 F DEBUG   :     dotnet/maui#9 pc 000d0a71  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.691  9691  9691 F DEBUG   :     dotnet/maui#10 pc 000d1963  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.691  9691  9691 F DEBUG   :     dotnet/maui#11 pc 000d45f3  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.692  9691  9691 F DEBUG   :     dotnet/maui#12 pc 000d3de7  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.692  9691  9691 F DEBUG   :     dotnet/maui#13 pc 0004c965  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.692  9691  9691 F DEBUG   :     dotnet/maui#14 pc 000453ab  /data/app/com.companyname.mauiapp9-LeLjmierad7gzvqYMRibag==/split_config.armeabi_v7a.apk (offset 0x19a2000)
09-12 15:18:08.692  9691  9691 F DEBUG   :     dotnet/maui#15 pc 00008e54  <anonymous:af430000>
```

### Steps to Reproduce

This can be recreated by creating a fresh MAUI app and renaming the Debug configuration e.g.

<Configurations>Debug.Pax</Configurations>

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

8.1

### Did you find any workaround?

No

### Relevant log output

See: https://github.com/dotnet/runtime/issues/76192#issuecomment-1258167574

### PR DESCRIPTION
**Pull request by BrzVlad**
It is the same as throw

Fixes https://github.com/dotnet/runtime/issues/76192

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]
@BrzVlad this is safe to backport, I think?

**Comment by lambdageek** [comment]
Do we have some lane to run arm32 device tests? @steveisok

**Comment by BrzVlad** [comment]
> @BrzVlad this is safe to backport, I think?

Yes. I would backport it also to 6.0 where the user hit this issue

**Review by vargaz — APPROVED** [review]

**Comment by radical** [comment]
The WBT failure can be ignored.

**Comment by steveisok** [comment]
> Do we have some lane to run arm32 device tests? @steveisok

We run tests for arm on android devices.

**Pull request merged**
