### PR TITLE
New Method NullEmptyOrWhitespace

### PR DESCRIPTION
**Pull request by FernandoEscoto99**
I see myself often having to use IsNullOrEmpty and IsNullOrWhitespace together and having this class would reduce code by one method call which would look cleaner.

### CODE REVIEW

**Comment by reflectronic** [comment]
I don't understand. How is this different from `string.IsNullOrWhitespace`? To be clear, `IsNullOrWhitespace` returns true for an empty string.

**Comment by FernandoEscoto99** [comment]
In practice, if the string is null or empty, the IsNullEmptyOrWhiteSpace method might be slightly faster because it will return true immediately after checking these conditions, whereas the IsNullOrWhiteSpace method will unnecessarily iterate over the string in case of an empty string. However, for non-null, non-empty strings, both methods should perform similarly.

**Comment by ShreyasJejurkar** [comment]
We can't just add new methods to existing classes by changing code directly, you have to open an API proposal first for the addition ([API proposal template](https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&projects=&template=02_api_proposal.yml&title=%5BAPI+Proposal%5D%3A+)) with your intension and use case! 

Once that is approved, we can only proceed to the actual code change!

**Comment by stephentoub** [comment]
> might be slightly faster because it will return true immediately after checking these conditions

There's no meaningful difference.  If the string's Length == 0, IsNullOrEmpty just jumps straight to returning true.

Thanks.

**Comment by xtqqczze** [comment]
> There's no meaningful difference. If the string's Length == 0, IsNullOrWhiteSpace just jumps straight to returning true.

@FernandoEscoto99 If you're interested, you can see from [this sharplab example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoQgBgAJDSA6AEWwEMBzAOwgGcM2MHyYBhCABMYAQW7tcATz7Y+AbipVCAZgbE6ougG8qdUwx2MkdYBAi46AST4A5AK65cAUQC2ABwwKAPJQAOoAFtgYMADKvuxgMAAUANrOEBhuHuEw3IkAZvJ8MACUALoMpDQA/HQAbvKuJSZmxpRm7XTYeXSJ9biNdAC8g3Tc7vb4+HUNMEwAMjmcGGFDIzTFDADsdBhQjeqUzR10edA92NwYnUN0NKrXADzT/bML3Eth99gA1N/FRx1Wsdjl0egBCMBhdhQJhOcKRGJxBK9GbJbClYobQjbAq4IoHYF0AC+GjawOxOz2MAJZhJZNM2gqVhsdkcLnGwXhUVi8SSqXSmVw2VyuKKZQq1WejX+9KMAPaoJRL1Wo3GWO2u32pMJpyg50u1zWXzoTz6jXmi2WX1+MsJQMJZkVEKhMLhEW5SKSZpgaIx6pOhWp8tp2vJGqpNNMdKJQA==) that your proposed method does not result in improved codegen.

**Pull request closed without merging**
