### PR TITLE
Rename long folder with instructions to fix long paths for git

### PR DESCRIPTION
**Pull request by carlossanlop**
Fixes https://github.com/dotnet/runtime/issues/173

The folder has a really long name and it causes a problem in git when people do not have long paths enabled.

Renaming the folder to contain the instructions to get the issue fixed.

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
I agree that a link to the doc would probably be better.

This assumes no test depends on this folder name, but in a quick look, I don't see any references to it.

**Review by ViktorHofer — APPROVED** [review]

**Review by jaredpar — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@carlossanlop what's the status here? Can we please update the message to point to https://github.com/dotnet/runtime/tree/master/docs/workflow (which lists the requirements for each OS)?

**Comment by stephentoub** [comment]
Do we actually need this long path checked in? Or could whatever test needs it generate it?

**Comment by jaredpar** [comment]
Another possible approach here is to simply check for long path support in the build.ps1 file and warn the developer when it's missing. The error message there can be customized to be more actionable for the developer.

**Comment by carlossanlop** [comment]
> _Do we actually need this long path checked in? Or could whatever test needs it generate it?_

@swaroop-sridhar that question would be for you.

**Comment by carlossanlop** [comment]
All, I just noticed this branch was created in my old fork that got detached after dotnet/runtime became public. I will have to resubmit this PR.

**Comment by carlossanlop** [comment]
BTW Windows does not allow paths to contain `/` or `\` or `:` in their names. I will try to make the URL in the folder name as understandable as possible.
@swaroop-sridhar I think the best approach to get this fixed is to add a test that generates this folder.

**Pull request closed without merging**
