### PR TITLE
Remove unused arguments from C# test Mains

### PR DESCRIPTION
**Pull request by markples**
For test merging, program arguments require extra work.  Removing any unused program parameters removes noise from that process.  This removes them from C# tests.  This was done with an ad-hoc tool.  I scanned the diffs.  Testing will provide basic checks (easy failure if an argument is used).  Risk is if an unused argument was required to test the right thing.

Manually updated the template JIT/Regression/JitBlue/Runtime_64125/Runtime_64125.tt for Runtime_64125.cs

Side effects of tool:

CoreMangLib/system/delegate/miscellaneous/co6010delegateequalstwo.cs converted from UTF16 to UTF8

The following tests had leading bytes (presumably BOM) removed:
- GC/Stress/Tests/DictionaryGrowth.cs
- Interop/PInvoke/SetLastError/SetLastErrorTest.cs
- Interop/PInvoke/SetLastError/SetLastErrorTest.cs
- JIT/IL_Conformance/Convert/TestConvertFromIntegral.cs
- JIT/Intrinsics/BMI1Intrinsics.cs
- JIT/Math/Functions/Program.cs
- JIT/opt/ForwardSub/switchWithSideEffects.cs
- JIT/opt/perf/doublenegate/GitHub_57470.cs
- JIT/opt/perf/doublenegate/doublenegate.cs
- JIT/Regression/JitBlue/GitHub_65690/GitHub_65690.cs
- JIT/Regression/JitBlue/Runtime_45090/Runtime_45090.cs
- JIT/Regression/JitBlue/Runtime_49078/Runtime_49078.cs
- JIT/Regression/JitBlue/Runtime_49780/Runtime_49780.cs
- JIT/Regression/JitBlue/Runtime_51612/Runtime_51612.cs
- JIT/Regression/JitBlue/Runtime_52320/Runtime_52320.cs
- JIT/Regression/JitBlue/Runtime_54647/Runtime_54647.cs
- JIT/Regression/JitBlue/Runtime_62249/Runtime_62249.cs
- JIT/Regression/JitBlue/Runtime_64125/Runtime_64125.cs
- JIT/Regression/JitBlue/Runtime_74773/Runtime_74773.cs

### CODE REVIEW

**Review by trylek — APPROVED** [review]
Looks great to me, thanks Mark, I vaguely recall I made a similar PR when merging the JIT Methodical tests.

**Comment by trylek** [comment]
Just for the sake of completeness, our current stance is that Main parameters in tests are unused in the vast majority of cases as your PR seems to confirm; in the exceptional cases where they are important, most notably in cases of multiple tests run against the same executable with different command-line parameters (<code>CLRTestProjectToRun</code>, <code>CLRTestExecutionArguments</code>) we observed that the most frequent pattern is several variations on the same type of test that should be usually easy to transform to a multitude of <code>[Fact]</code> annotations in the C# source file. IIRC @jkoritzinsky suggested that the <code>Theory</code> clause can be also used to express variations of certain tests running with multiple sets of input arguments.

**Comment by trylek** [comment]
This triplet I've looked at recently is a great example:

https://github.com/dotnet/runtime/blob/main/src/tests/baseservices/exceptions/simple/ParallelCrash.csproj
https://github.com/dotnet/runtime/blob/main/src/tests/baseservices/exceptions/simple/ParallelCrashMainThread.csproj
https://github.com/dotnet/runtime/blob/main/src/tests/baseservices/exceptions/simple/ParallelCrashWorkerThreads.csproj

**Comment by trylek** [comment]
(notwithstanding the fact that I originally authored these particular tests which is something Jeremy just recently made me aware of)

**Comment by trylek** [comment]
To put it yet another way, what typically happens in such a <code>Main</code> method is a trivial command-line parser that either does a <code>switch</code> over the argument to trigger various flavors of a particular test, or parses its value to use as an input argument to the test method. For the former case (<code>switch</code>) I believe that in most cases it should be replaced with a series of methods corresponding to the previous switch cases, each marked with the <code>[Fact]</code> attribute. For the latter case (parsed values) I assume Theory can kick in or we can even try to do something atypical when we deem it appropriate like encoding a static array of values that get subsequently passed to the test routine in question via a for loop.

**Comment by trylek** [comment]
Cf. https://github.com/dotnet/runtime/pull/63770

**Comment by trylek** [comment]
FWIW, I'm not sure what is our overall strategy regarding BOMs on source files, many C# files have them and in the past I got asked to explain my rationale for [inadvertently] removing them from a particular file even though we normally shouldn't be using any non-ASCII characters in our source code unless I'm mistaken, all of that should go into the localization resources.

**Comment by trylek** [comment]
This was the ILPROJ counterpart: https://github.com/dotnet/runtime/pull/64482

**Comment by markples** [comment]
Thank you for all of the comments, @trylek!  I guess I could have been smarter and used CLRTestExecutionArguments instead of scanning the source, though I suppose tests could have dev-time-only arguments.  But that is for a future PR as this is just to remove noise.

One possible danger in removing (used) arguments is that `if (args.Length == 0)` is a way to create a conditional that the optimizers can't remove, which might be useful for creating code shapes to expose JIT bugs.  (well, I suppose the JIT could remove them if it had the arguments and knew the Main wasn't called a second time...)

There was a recent discussion in chat about BOMs and I believe the consensus was to remove them.  It will be nicer this way since future rewriting tools won't have to preserve them.

**Pull request merged**
