### PR TITLE
Fixes typo of word dictionary throughout repo

### PR DESCRIPTION
**Pull request by kamronbatman**
Fixes a typo in a comment in ConditionalWeakTable.cs
- `dictonary` should be `dictionary`

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please fix this typo in all places in the repo? https://github.com/search?q=repo%3Adotnet%2Fruntime%20dictonary&type=code

**Comment by kamronbatman** [comment]
> Could you please fix this typo in all places in the repo? https://github.com/search?q=repo%3Adotnet%2Fruntime%20dictonary&type=code

Great idea, will do.

**Comment by kamronbatman** [comment]
@jkotas - I think I got them all! :)

**Review by jkotas — APPROVED** [review]
Thanks!

**Pull request merged**
