### PR TITLE
Disable binplacing for DependencyInjection.Specification.Tests

### PR DESCRIPTION
**Pull request by ericstj**

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
LGTM

**Comment by ericstj** [comment]
@ViktorHofer @briansull should we merge this immediately to unblock builds?  It wasn't clear to me from https://github.com/dotnet/runtime/pull/48858#issuecomment-789381586 how blocking the failure was.

**Comment by BruceForstall** [comment]
It affects our post-merge rolling "outerloop" CI job: https://dev.azure.com/dnceng/public/_build?definitionId=655&_a=summary

As well as any R2R coreclr job.

**Comment by ericstj** [comment]
@BruceForstall is there anything that's going to validate this fix as part of the CI process?  What's the quickest way to unblock you?

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Given the simplicity of the change I tend towards fast merge. Merging.

**Comment by ericstj** [comment]
My thoughts as well @ViktorHofer.  I'll own the risk here.  If anything breaks ping me and I'll back stuff out.

**Comment by BruceForstall** [comment]
I would manually kick off an outerloop job to validate, but it should automatically kick off in about 15 minutes, so I'll just let that happen.

https://dev.azure.com/dnceng/public/_build?definitionId=655

**Comment by briansull** [comment]
Does this change remove  System.TestStructs.dll  from the CORE_ROOT directory?  
As that is the assembly that fails to compile in the R2RTest task

**Comment by ericstj** [comment]
@briansull I don’t think System.TestStructs.dll was present.

Error was
>  Could not load file or assembly 'System.TestStructs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified

That failure was due to Microsoft.Extensions.DependencyInjection.Specification.Tests which referenced it without copying it.

**Pull request merged**
