### PR TITLE
[browser] remove legacy js interop

### LINKED ISSUE #90044: [browser][MT] legacy JS interop needs GC boundaries on main thread too
Calling legacy `mono_wasm_invoke_method_ref` on the main thread could lead to GC transition assert at `mono-threads-state-machine.c:807`

See https://github.com/dotnet/runtime/issues/89909#issuecomment-1665811281

### PR DESCRIPTION
**Pull request by pavelsavara**
## Public
- `MONO` and `BINDING` JS APIs
- `disableDotnet6Compatibility` JS flag
- doc for `HEAP`XXX on emscripten module
- `dotnet-legacy.d.ts`
- MSBuild property `WasmEnableLegacyJsInterop` and related trimming support for it
- semi-public `mono_wasm_invoke_js_blazor()` and `WebAssembly.JSInterop.InternalCalls.InvokeJS()` ICAL

## Internal
- any internal C# classes like `Runtime` and `JSObject` extensions `DataView` ...
- perf tests related to legacy interop
- unit tests `System.Runtime.InteropServices.JavaScript.Legacy.Tests` 
	- moved `timers.mjs`, `TimerTests`
	- moved `HttpRequestMessageTest`
	- all modern scenarios are covered in `System.Runtime.InteropServices.JavaScript.Tests`
- `call_test_method` used in some tests

## TODO
- debugger tests are still using `bind_static_method` https://github.com/dotnet/runtime/pull/96899
- upgrade Blazor for WBT, to contain https://github.com/dotnet/aspnetcore/pull/52732

Fixes https://github.com/dotnet/runtime/issues/90044

### CODE REVIEW

**Comment by pavelsavara** [comment]
WBT version of blazor is too old still.

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-96841-merge-b8afbe53da2e40b891/NoWorkload-NoWebcil-Wasm.Build.Tests/1/console.126a4ac0.log?helixlogtype=result)
```
[error] crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
              Unhandled exception rendering component: TypeError: Cannot read properties of undefined (reading 'getI32')
```

**Comment by pavelsavara** [comment]
@radical 
In WBT I need Blazor version which contains https://github.com/dotnet/aspnetcore/pull/52732, what do I need to do ?

**Comment by radical** [comment]
You need an installer which references that version or newer of aspnetcore. We update the installer once a day via the darc flow. Just watch for that.

**Comment by pavelsavara** [comment]
> You need an installer which references that version or newer of aspnetcore. We update the installer once a day via the darc flow. Just watch for that.

The flow is `aspnetcore` -> `sdk` -> `installer` -> `runtime`, right ?

**Comment by pavelsavara** [comment]
maybe this https://github.com/dotnet/runtime/pull/96896

**Review by maraf — APPROVED** [review]
Looks good to me 👍

**Review by ilonatommy — APPROVED** [review]
I wonder, we left the legacy API in `src/mono/wasm/Wasm.Build.Tests/data/test-main-7.0.js` but the "dotnet-latest" we use for running wbt will not contain it anymore. @radical, do we ever run wbt with older dotnet?

**Comment by pavelsavara** [comment]
I filled https://github.com/dotnet/runtime/issues/97217 for 
```
Assertion: should not be reached at D:\a\_work\1\s\src\mono\mono\mini\mini-llvm.c:1394
```

**Comment by radical** [comment]
> I wonder, we left the legacy API in `src/mono/wasm/Wasm.Build.Tests/data/test-main-7.0.js` but the "dotnet-latest" we use for running wbt will not contain it anymore. @radical, do we ever run wbt with older dotnet?

No. We can drop any 7.0 stuff.

**Comment by radekdoulik** [comment]
it looks like this caused large blazor startup regression

image

the range is
https://github.com/dotnet/runtime/compare/aca77bdbef56e9be27d93a4636e65c417dc197e4...5a6135e7e6e9fd19a1e319958cc3220dcad9a1e3

**Comment by pavelsavara** [comment]
The slowdown is strange, there is no new code in the startup sequence, just code removed.
Maybe something what was executed early is now executed later ?

There is also 80 KB reduction in uncompressed size, right ?

**Comment by radekdoulik** [comment]
It might be something broken with the UI startup, the time is very close to 20 seconds. So I wonder if it is related to some timeout being set to 20s.

The reduced size is great and is visible in the cold startup.

**Comment by pavelsavara** [comment]
I hope this will fix it https://github.com/dotnet/runtime/pull/97305

Do we have same problem in the other benchmark suite too ?

**Comment by radekdoulik** [comment]
It is indeed a timeout
```
Benchmark started<br/> [main.js:98:21](http://localhost:8844/main.js)
waitFor blazor: Rendered Index.razor timed out [main.js:192:25](http://localhost:8844/main.js)
MONO_WASM: Saved interp_pgo table to cache [logging.ts:22:12](file:///Users/rodo/git/runtime/src/mono/browser/runtime/logging.ts)
waitFor blazor: Rendered Index.razor timed out [main.js:192:25](http://localhost:8844/main.js)
AppStart, Blazor First UI count: 1, per call: 20307ms, total: 20.307s<br/>
```

**Pull request merged**
