### PR TITLE
Support COM objects using IEnumerator

### LINKED ISSUE #37191: COM reference: exception is thrown when iterating over Excel cells
### Description
I am trying to iterarate over Excel cells with `foreach`. This is what I have:

### Project file:

```
<ItemGroup>
	<COMReference Include="Microsoft.Office.Excel">
		<Guid>00020813-0000-0000-c000-000000000046</Guid>
		<VersionMajor>1</VersionMajor>
		<VersionMinor>9</VersionMinor>
		<WrapperTool>primary</WrapperTool>
		<Lcid>0</Lcid>
		<Isolated>false</Isolated>
		<EmbedInteropTypes>true</EmbedInteropTypes>
	</COMReference>
</ItemGroup>
```

### C# code:
```
var file_path = @"C:\test_file.xlsx";
var excel = new Excel.Application { Visible = true };
var book = excel.Workbooks.Open(file_path);
var sheet = book.Worksheets[1] as Excel.Worksheet;
var rng = sheet.Range["A1:B3"];

foreach (Excel.Range cell in rng) //or rng.Cells
{
	listBox.Items.Add(cell.Value);
}
```
However, when execution reaches iteration, I get the following error on `foreach` line (`rng` is highlighted):
> System.TypeLoadException: 'Could not load type 'System.Runtime.InteropServices.ComTypes.IEnumerator' from assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.'

image

### Configuration
**Visual Studio**: Community 2019 16.7.0 Preview 1.0
**.NET**: .NET 5.0 Preview 4, .NET Core 3.1, .NET Core 3.0
**OS**: Windows 10 Pro x64 1909 Build 18363.836

### Regression?
The same code works on .NET Framework 4.8.

### PR DESCRIPTION
**Pull request by elinor-fung**
- Bring back support for COM objects with `IEnumerator` (`IEnumVARIANT`)
- Add COM tests going through `DISPID_NEWENUM` or function returning `IEnumVARIANT`

Resolves #37191

@AaronRobinsonMSFT @jkoritzinsky

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by daxian-dbw** [comment]
@AaronRobinsonMSFT Which preview will this fix be included?

**Comment by AaronRobinsonMSFT** [comment]
@daxian-dbw We just snapped for preview 6 so master should now be preview 7.

**Comment by JohnyL** [comment]
@AaronRobinsonMSFT In .NET 5 Preview 6 still get the error. Do you mean it will be fixed in Preview 7?

**Comment by AaronRobinsonMSFT** [comment]
@johnyl Yes. We missed the P6 snap.

**Pull request merged**
