### PR TITLE
Don't hardcode /tmp in named pipe tests, it's not for us on Android

### LINKED ISSUE #49873: System.IO.Pipes test failures on Android
The following tests fail and we'll skip them for now until we can address further:

- [ ] System.IO.Pipes.Tests.NamedPipeTest_UnixDomainSockets.NamedPipeClient_Connects_With_UnixDomainSocketEndPointServer
`System.Net.Sockets.SocketException : Cannot assign requested address`

- [ ] System.IO.Pipes.Tests.NamedPipeTest_UnixDomainSockets.NamedPipeServer_Connects_With_UnixDomainSocketEndPointClient
`System.Net.Sockets.SocketException : Cannot assign requested address`

### PR DESCRIPTION
**Pull request by directhex**
Closes: #49873

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]
LGTM. It seems we hit cases years ago where TMPDIR on macOS was very long so the named pipe failed, if that's the case then I'd just special case this for Android.

**Comment by directhex** [comment]
The OSX tests have passed. Is there some test beyond what's in the libs tests for this TMPDIR issue?

**Review by filipnavara — APPROVED** [review]

**Comment by Jozkee** [comment]
Is this other one not an issue for Android?
https://github.com/dotnet/runtime/blob/222da17b8d2d1e8627850ce5ae2b5c55e632cf48/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.cs#L46

**Comment by directhex** [comment]
> Is this other one not an issue for Android?
> 
> https://github.com/dotnet/runtime/blob/222da17b8d2d1e8627850ce5ae2b5c55e632cf48/src/libraries/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.CurrentUserOnly.cs#L46

Nope.

https://github.com/dotnet/runtime/blob/222da17b8d2d1e8627850ce5ae2b5c55e632cf48/src/libraries/System.IO.Pipes/tests/System.IO.Pipes.Tests.csproj#L26

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
