### PR TITLE
[mono][jit] For beforefieldinit classes, only field accesses trigger …

### PR DESCRIPTION
**Pull request by vargaz**
…initialization.

### CODE REVIEW

**Comment by lateralusX** [comment]
Seeing same effect as https://github.com/dotnet/runtime/pull/76295 on things like using Math class functions, so this simplified PR seems to do the trick as well.

**Review by lateralusX — APPROVED** [review]
LGTM!

**Comment by vargaz** [comment]
Failures look unrelated.

**Pull request merged**
