### PR TITLE
Remove EXTRA_*FLAGS.

### PR DESCRIPTION
**Pull request by tmds**
These seem to be broken.

Flags can be set by by adding an argument like '--cmakeargs -DCMAKE_C_FLAGS=xyz' to the build.sh command line.

cc @omajid @am11

### CODE REVIEW

**Comment by am11** [comment]
LGTM. For compiler selection, which happens before cmake invocation, `CLR_CC` and `CLR_CXX` are available to point to custom toolchain.

**Comment by tmds** [comment]
This should be good to merge.

**Comment by omajid** [comment]
> Flags can be set by by adding an argument like '--cmakeargs -DCMAKE_C_FLAGS=xyz' to the build.sh command line.

Unfortunately, that's not really a great option when using source-build, other than by patching the various SourceBuild.props or repo-projects/runtime.proj file.

**Comment by tmds** [comment]
> Unfortunately, that's not really a great option when using source-build, other than by patching the various SourceBuild.props or repo-projects/runtime.proj file.

I tried to use these `EXTRA_*FLAGS` but they didn't work

I'm removing them because I think they are broken.

If you need these, can you verify they work, and fix them if needed?

**Comment by tmds** [comment]
@omajid can you answer my question in the previous comment?

**Comment by omajid** [comment]
Oops. Sorry, I forgot to reply earlier. I tried out setting the `EXTRA_` flags and they don't seem to be working. I didn't get a chance to dig more into this.

**Comment by tmds** [comment]
I'm going to close this PR to remove the flags as @omajid intends to fix them.

**Pull request closed without merging**
