### PR TITLE
[wasm][debugger] Debug on Node.js

### PR DESCRIPTION
**Pull request by thaystg**
Done in this PR:
Fix startup to debug nodejs.

To debug the sample:
Build sample console-node:
`dotnet build /p:TargetArchitecture=wasm /p:TargetOS=Browser /p:Configuration=Debug`

Run the sample listening on port 9222:
`make debug-console-node`

run BrowserDebugHost

Open chrome/vscode and choose the address printed on BrowserDebugHost console.

You will see the nodejs process running, you can attach.

You also need to add the folder with the source files on IDE(chrome/vscode), then you can add breakpoints.

TODO: 
- add node configuration to run debugger-tests

### CODE REVIEW

**Comment by lewing** [comment]
the app host changes are in now, what is the state of this?

**Comment by pavelsavara** [comment]
also add `--inspect=9222` here https://github.com/dotnet/runtime/blob/main/src/mono/sample/wasm/Directory.Build.targets#L35

**Comment by radical** [comment]
This needs to be integrated with `src/mono/wasm/host/JSEngineHost.cs` also. `BrowserHost` has an implementation of this, which can be used as an example. Not blocking for this PR though.

**Review by radical — APPROVED** [review]

**Review by radical — APPROVED** [review]

**Review by radical — APPROVED** [review]

**Comment by radical** [comment]
Wasm failure is known, and unrelated.

**Pull request merged**
