### PR TITLE
Use newer microsoft.com certificate chain in X.509 tests

### LINKED ISSUE #48406: S.S.C.X509Certificates.Tests.ChainTests.BuildChainCustomTrustStore failing locally
The test `BuildChainCustomTrustStore` is failing locally for me, all theories.

```
Failed System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChainCustomTrustStore(chainBuildsSuccessfully: True, chainFlags: NoError, testArguments: TrustedIntermediateTrustedRoot) [< 1 ms]
  Error Message:
   System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
  Stack Trace:
     at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index) in /code/personal/dotnet/runtime/src/libraries/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509ChainElementCollection.cs:line 46
   at System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChainCustomTrustStore(Boolean chainBuildsSuccessfully, X509ChainStatusFlags chainFlags, BuildChainCustomTrustStoreTestArguments testArguments) in /code/personal/dotnet/runtime/src/libraries/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs:line 290
```

```
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /code/personal/dotnet/runtime/.dotnet/sdk/5.0.100/
```

```
apt-cache policy ca-certificates      
ca-certificates:
  Installed: 20210119~20.04.1
  Candidate: 20210119~20.04.1
```

Most recently seen at 9195df699fe25d2e752c2bc350c16dc199f02f7a.

--------

I suspect this is occurring because the certificate under test is part of VeriSign whose roots are in-flux in various Linux distributions.

### PR DESCRIPTION
**Pull request by vcsjones**
The old certificate chain used a root certificate that is deprecated and is starting to disappear from some trust stores in Linux. The removal of the root certificate led to a few failing tests, and other tests not running since they were conditional on the trust of that certificate.

Closes #48406

### CODE REVIEW

**Comment by vcsjones** [comment]
This will need an outerloop run.

**Comment by vcsjones** [comment]
Outerloop failures appear irrelevant.

**Comment by bartonjs** [comment]
> Outerloop failures appear irrelevant.

I agree.  Thanks, @vcsjones.

**Review by bartonjs — APPROVED** [review]

**Comment by Anipik** [comment]
@bartonjs  @vcsjones can you port the fix to 5.0 branch, we are hitting the same issue there

**Comment by vcsjones** [comment]
@bartonjs I don't think backport bot will be able to do this one cleanly, I'll prepare a PR for a manual backport.

**Comment by vcsjones** [comment]
@Anipik it looks like this was backported yesterday to release/5.0 in #49300.

**Pull request merged**
