### PR TITLE
[wasm] Don't publish the aot-instances.dll assembly, its not needed a…

### PR DESCRIPTION
**Pull request by vargaz**
…ny more.

The runtime creates a dummy version of it internally.

### CODE REVIEW

**Comment by maraf** [comment]
The target `_WasmGenerateAppBundle` is not called by blazor. Should the change affect also blazor?

**Comment by vargaz** [comment]
It should.

**Comment by vargaz** [comment]
This assembly is still needed to be aot-ed, it just shouldn't be in the final bundle.

**Comment by maraf** [comment]
I see, sorry. Than it should be `_CompleteWasmBuildNative` which is after all AOT targets and just before `_WasmGenerateAppBundle` (which is optional / not called for Blazor).

**Review by maraf — APPROVED** [review]

**Pull request merged**
