### PR TITLE
`JsonIgnoreCondition` controls are extended

### PR DESCRIPTION
**Pull request by onurkanbakirci**
Related #66490. @layomia @eiriktsarpalis 

`JsonIgnoreCondition` controls are extended. `WhenReading` and `WhenWriting` options are added to `JsonIgnoreCondition` enum. Tests are passed but i also want to add `ClassWithProperty_IgnoreConditionWhenReading_Ctor` test case which fails for now. Is there any idea about why `ClassWithProperty_IgnoreConditionWhenReading_Ctor` test case fails? It's like below:

```
private class ClassWithProperty_IgnoreConditionWhenReading_Ctor
{
      public string MyString { get; set; }
      [JsonIgnore(Condition = JsonIgnoreCondition.WhenReading)]
      public DateTime MyDateTime { get; }
      public int MyInt { get; }

     public ClassWithProperty_IgnoreConditionWhenReading_Ctor(DateTime myDateTime, int myInt)
     {
         MyDateTime = myDateTime;
        MyInt = myInt;
    }
}
```

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
Hi @onurkanbakirci, and thanks for submitting this PR. Unfortunately, we cannot accept contributions introducing new public APIs  unless their shape has been previously approved in our [API review process](https://github.com/dotnet/runtime/blob/255c3ab9fa82e0d4d13b5f0a9afcf3df07a845f9/docs/project/api-review-process.md). I would recommend holding off until https://github.com/dotnet/runtime/issues/66490 has been marked with the `api-approved` label. 

I'm going to close this PR for now, but we can always revisit once a decision has been made in API review. In the meantime, please contribute to the conversation in the parent issue, including perhaps upvoting the issue (the more an issue is upvoted, the more likely it is it will get prioritized for a future release). Thanks!

**Comment by eiriktsarpalis** [comment]
HI @onurkanbakirci I've reopened your PR given that the API has now been approved. Would it be possible to rebase your changes?

**Comment by onurkanbakirci** [comment]
Hi @eiriktsarpalis . I've rebased changes.

**Comment by onurkanbakirci** [comment]
Hi @eiriktsarpalis , after reviewing the code again, I noticed that some properties and functions have changed (As you may recall, I opened the PR four months ago, and there have been changes over time in the `dotnet/main` repository). I am currently working on it, and I will share the fully implemented version with a new PR as soon as possible.

**Pull request closed without merging**
