### PR TITLE
Add CoffeeFlux to area-VM-meta-mono

### PR DESCRIPTION
**Pull request by CoffeeFlux**
This ensures I see notifications about new issues, plus i've been doing triage on a lot of these anyway.

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Comment by akoeplinger** [comment]
@danmosemsft does this actually update the GitHub bot, or is that a separate step?

**Comment by danmosemsft** [comment]
@akoeplinger unfortunately not, you have to ping one of the bot admins, although I already did this one.

**Comment by akoeplinger** [comment]
would probably make sense to add a note about that and who to ping to this page :)

**Comment by danmosemsft** [comment]
Feel free, but it notes to ping me in every notification already - I feel like a spammer. Actually, there are other admins, maybe I should list them all.
https://github.com/dotnet/runtime/issues/39744#issuecomment-662157634

**Comment by akoeplinger** [comment]
@danmosemsft what about if we add a link to the doc instead of the `Notify danmosemsft if you want to be subscribed.` in the bot message? then we'd have at least that part centralized

**Comment by danmosemsft** [comment]
Sure go ahead (since you have an idea what you want it to say in the doc) then I'll update the bot message

**Comment by akoeplinger** [comment]
https://github.com/dotnet/runtime/pull/39750

**Pull request merged**
