### PR TITLE
[Arm64] Add ASIMD pairwise reduce instructions

### PR DESCRIPTION
**Pull request by echesakov**
This adds the following Arm64 instructions:

* fmaxp
* fmaxnm
* fmaxnmp
* fmaxnmv
* fmaxv
* fminp
* fminnm
* fminnmp
* fminnmv
* fminv
* smaxp
* sminp
* umaxp
* uminp

I validate that the encodings are right by comparing the output of JIT dump with WinDbg **u** and `ALL_ARM64_EMITTER_UNIT_TESTS` macro defined.

In addition, I fixed the emitter tests for smaxv, sminv, umaxv, uminv, trn1, trn2, uzp1, uzp2, zip1, zip2.

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@dotnet/jit-contrib PTAL

**Review by briansull — APPROVED** [review]
Looks Good

**Comment by echesakovMSFT** [comment]
After multiple attempts to retry **runtime (Libraries Test Run checked coreclr OSX x64 Debug)** continues failing with
```
/Users/runner/runners/2.164.8/work/1/s/.packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20112.7/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(60,5): error : The response contained an invalid status code 404 Not Found [/Users/runner/runners/2.164.8/work/1/s/src/libraries/sendtohelix.proj]
/Users/runner/runners/2.164.8/work/1/s/.packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20112.7/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(60,5): error :  [/Users/runner/runners/2.164.8/work/1/s/src/libraries/sendtohelix.proj]
/Users/runner/runners/2.164.8/work/1/s/.packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20112.7/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(60,5): error : Body:  [/Users/runner/runners/2.164.8/work/1/s/src/libraries/sendtohelix.proj]
/Users/runner/runners/2.164.8/work/1/s/.packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20112.7/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(60,5): error : The response contained an invalid status code 404 Not Found [/Users/runner/runners/2.164.8/work/1/s/src/libraries/sendtohelix.proj]
/Users/runner/runners/2.164.8/work/1/s/.packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20112.7/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(60,5): error :  [/Users/runner/runners/2.164.8/work/1/s/src/libraries/sendtohelix.proj]
/Users/runner/runners/2.164.8/work/1/s/.packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20112.7/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(60,5): error : Body:  [/Users/runner/runners/2.164.8/work/1/s/src/libraries/sendtohelix.proj]
/Users/runner/runners/2.164.8/work/1/s/.packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20112.7/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(60,5): error : The response contained an invalid status code 404 Not Found [/Users/runner/runners/2.164.8/work/1/s/src/libraries/sendtohelix.proj]
/Users/runner/runners/2.164.8/work/1/s/.packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20112.7/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(60,5): error :  [/Users/runner/runners/2.164.8/work/1/s/src/libraries/sendtohelix.proj]
/Users/runner/runners/2.164.8/work/1/s/.packages/microsoft.dotnet.helix.sdk/5.0.0-beta.20112.7/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(60,5): error : Body:  [/Users/runner/runners/2.164.8/work/1/s/src/libraries/sendtohelix.proj]
```

@dotnet/runtime-infrastructure Is this a known/tracked issue?

When I tried to open some of the links in the failure log I got either 
```
Executed on dci-mac-build-042.local
/bin/sh: /tmp/helix/working/C9EB0ADC/p/scripts/bbb19dec871d44408dab06396740fd38/execute.sh: Permission denied
```
or 404 error.

I am merging this change anyway since it doesn't affect x64 side of runtime.

**Comment by trylek** [comment]
I believe @ViktorHofer mentioned earlier today there's a known "permission denied" issue hitting OSX runs overall.

**Comment by safern** [comment]
Yeah, that issue is tracked here: https://github.com/dotnet/core-eng/issues/8971

**Pull request merged**
