### PR TITLE
Support open delegate for Nullable<>

### PR DESCRIPTION
**Pull request by amos402**
Because of the boxing behavior specialization for `Nullable<>`, after the boxing, a nullable object may be boxed by the type it referred to or just `null`, the original type information lost.
For example, 
```c#
int? num1 = 123;
object box = num1;
// box.GetType() == typeof(int);

int? num2= null;
object box = num2;
// box is null
```
Thus it's reasonable that a closed delegate binding for `Nullable<>` such as `Delegate.CreateDelegate(invokeType, boxedNullable, method)` is prohibited.
However, if for an open delegate case for `Nullable<>`, the `invokeType` must point to a delegate in which the first parameter is `ref Nullable<XXX>`, so it's no need to worry about the type information lost.
Currently, there's a special check for nullable type:
https://github.com/dotnet/runtime/blob/38bf4dff86b649e6a31c5a3d715d2a7141e03920/src/coreclr/src/vm/comdelegate.cpp#L2614-L2617
This specialized check is unnecessary, we can just remove it.
case 1: a closed delegate with boxed nullable value, no matter which type it would be, it just can't pass the type validation because the type won't match the nullable type.
case 2: an open delegate targeted by `xx Func(ref Nullable<XXX> self)`, the `self` type for the target method would use its reference type, the `fromHandle` and `toHandle` pass to `IsLocationAssignable` would be the same one.
It makes the code like as follow can't be used on .NetCore(.Net framework as well), on the other side, mono can.
The present version throws an `ArgumentException` for these cases.

```c#
delegate bool HasValueDelegate(ref int? obj);
delegate int GetValueDelegate(ref int? obj);
delegate string ToStringDelegate(ref int? obj);

static void Main(string[] args)
{
    int? num = 123;
    Type type = typeof(int?);
    {
        var mHasValue = typeof(int?).GetProperty("HasValue").GetMethod;
        var HasValue = (HasValueDelegate)Delegate.CreateDelegate(typeof(HasValueDelegate), mHasValue);
        Console.WriteLine("HasValue: {0}", HasValue(ref num));
    }

    {
        var t2 = (GetValueDelegate)Delegate.CreateDelegate(typeof(GetValueDelegate), type.GetProperty("Value").GetMethod);
        int value = t2(ref num);
        Console.WriteLine("Value: {0}", value);
    }

    {
        const BindingFlags MethodFlag = BindingFlags.Public | BindingFlags.Instance;
        var mGetValueOrDefault = typeof(int?).GetMethods(MethodFlag)
            .Single(m => m.Name == "GetValueOrDefault" && m.GetParameters().Length == 0);
        var GetValueOrDefault = (GetValueDelegate)Delegate.CreateDelegate(typeof(GetValueDelegate), mGetValueOrDefault);
        Console.WriteLine("GetValueOrDefault: {0}", GetValueOrDefault(ref num));
    }

    {
        var mToString = type.GetMethod("ToString");
        var ToString = (ToStringDelegate)Delegate.CreateDelegate(typeof(ToStringDelegate), mToString);
        Console.WriteLine("ToString: {0}", ToString(ref num));
    }
}
```

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=42837) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=42837) before we can accept your contribution.<br/><br/>:x: amos402 [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=42837)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=42837) it.</sub>

**Comment by ViktorHofer** [comment]
// Auto-generated message

https://github.com/dotnet/runtime/commit/69e114c1abf91241a0eeecf1ecceab4711b8aa62 which was merged 12/7 removed the intermediate src/coreclr/**src**/ folder. This PR needs to be updated as it touches files in that directory which causes conflicts.

To update your commits you can use this bash script: https://gist.github.com/ViktorHofer/6d24f62abdcddb518b4966ead5ef3783. Feel free to use the comment section of the gist to improve the script for others.

**Comment by mangod9** [comment]
@davidwrighton and @lambdageek will follow up on this.

**Comment by davidwrighton** [comment]
@lambdageek This change looks good from the coreclr point of view, but I'm not prepared to merge with a comment about what you'd like done for the mono interpreter. I could disable the test for the interpreter runs and for wasm, or either you or @amos402 could look into fixing the interpreter.

**Comment by lambdageek** [comment]
@davidwrighton Please disable the test and ping me with the issue. The interpreter has a separate path through our (convoluted) delegate code and I don't think it's necessary to hold up this PR.

**Review by davidwrighton — APPROVED** [review]
This is a good change. I'd like to apologize for how long it took for us to get started on review of it.

**Pull request merged**
