### PR TITLE
Ensure that Arm64 correctly handles multiplication of simd by a 64-bit scalar

### LINKED ISSUE #106838: SIMD multiplication by scalar UInt64 can produce incorrect results on Arm64
The following program should print `<25, 25>` but instead may print a random value for the second element.
```csharp
ulong val = 5;
Vector128<ulong> x = Vector128.Create<ulong>(val);
Console.WriteLine(x * 5UL);
```

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #106838

### CODE REVIEW

**Comment by tannergooding** [comment]
Extracted from https://github.com/dotnet/runtime/pull/106594 so that it can be backported to .NET 9

**Comment by tannergooding** [comment]
CC. @dotnet/jit-contrib for review

This fixes #106838 and will need backport

**Review by EgorBo — APPROVED** [review]
x64 has a similar path - is it ok as is?

**Comment by tannergooding** [comment]
> x64 has a similar path - is it ok as is?

Yes. The issue here was specifically with multiplication by a scalar, since Arm64 handles it by extracting the separate components.

For x64, we always broadcast that scalar to a vector and then use a vectorized implementation instead, not extracting.

**Pull request merged**
