### PR TITLE
[wasm] EmccCompile: Add support for compiling sequentially

### PR DESCRIPTION
**Pull request by radical**
Add support for user specified assemblies that should always be compiled
sequentially. This would be useful for cases where some assemblies fail to compile
because `emcc` runs out of memory when compiled in parallel with other assemblies.

New:
```
      - @(WasmAssemblyToAOTSequentially) - Filenames of assemblies to always compile (to .o) sequentially
```

### CODE REVIEW

**Comment by vargaz** [comment]
Not sure that a build system should retry failing commands. Would a setting limiting the amount of parallelism, like make's -j argument work ?

**Comment by radical** [comment]
> Not sure that a build system should retry failing commands. Would a setting limiting the amount of parallelism, like make's -j argument work ?

Using only `-j` like argument would limit that for all the files, instead of a few, which is the problem that I was trying to solve here. Like when some assemblies run out of memory when aot'ed at the same time as others, but compile fine when aot'ed by themselves.

I have removed the `retry` mechanism here.

**Comment by lewing** [comment]
@ankit do you still think this is useful?

**Pull request closed without merging**
