### PR TITLE
Revert "[Mono] Add SIMD intrinsic for Vector64/128 comparisons (#65128)"

### LINKED ISSUE #66083: TIME OUT - Mono llvmfullaot Pri0 Runtime Tests Run Linux arm64 release
We couldn't find any obvious change that could be causing it between these commits:
git diff a82d92c36624e89e831e37515a9b0c95a4cfe183..c8da2fd5d8b841fc34845218158399cf35eb8bcf

Log which the timeout started:
https://dev.azure.com/dnceng/public/_build/results?buildId=1633880&view=results

### PR DESCRIPTION
**Pull request by simonrozsival**
This PR reverts #65128 in an attempt to fix #66083

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Review by fanyang-mono — APPROVED** [review]

**Comment by vargaz** [comment]
This doesn't seem to solve the problem.

**Comment by thaystg** [comment]
This didn't cause the problem on CI, I'll close the PR.

**Comment by thaystg** [comment]
It looks like that reverting this the timeout issue is gone:

image

**Comment by vargaz** [comment]
Note that the lane still takes 2h52m (172m), and the timeout is 3h20m (200m), so even a 10-15% increase in total AOT time would lead to a timeout.

**Comment by fanyang-mono** [comment]
The step of `Send tests to Helix` did came down to ~10mins from ~1h. I would consider this PR did resolve the issue. This lane usually takes 2h30mins and more. We could let this PR run another time to get another data point.

**Comment by simonrozsival** [comment]
@fanyang-mono I'll re-run the tests

**Comment by simonrozsival** [comment]
The llvm aot lanes are now OK:

image

but so are the same lanes in the rolling build on `main`:

image

Now it's `Mono minijit Pri0 Runtime Tests Run OSX x64 release` and `Mono monointerpreter Pri0 Runtime Tests Run OSX x64 release` that are timing out (both this PR and the rolling build).

**Pull request closed without merging**
