### PR TITLE
[release/6.0] Add osx-arm64.runtime.native.System.IO.Ports

### PR DESCRIPTION
**Pull request by SeanMollet**
Fixes https://github.com/dotnet/runtime/issues/59972

This change adds a package project to build/package it, which also adds it as a dependency to the meta runtime.native.System.IO.Ports package.

## Customer Impact

.NET 6 advertises Apple Silicon support. Not having this means that part of that support is missing. In particular, myself and many others develop for .NET on Apple hw, which is moving fairly quickly to Apple Silicon. Not having this means that I have to use a Linux VM or a remote system if I want to communicate with external devices.

In my specific case, I built electronics that interface with .NET servers and clients using USB, which shows up as a virtual serial port. Not having that functionality on my development machine is quite annoying.

## Testing

Tested on actual Apple Silicon hardware with various serial devices. Since no current M1 device offers native serial ports, all testing was conducted with various USB devices that convert to or present as serial ports. Works correctly.

## Risk

Low. The alternative is that there is no support at all.

### CODE REVIEW

**Comment by SeanMollet** [comment]
Closes #59972

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@dotnet/area-system-io can you please take a look as well?

**Review by jozkee — APPROVED** [review]

**Comment by SeanMollet** [comment]
@Jozkee I copied your template. I'm happy to do this against main if that's the approach that's required.

**Comment by jeffhandley** [comment]
@SeanMollet After you got the local build, were you able to consume these APIs and verify the functionality on the Apple silicon hardware? I'd like to confirm that once the packaging fix is merged into release/6.0, you'll be unblocked.

**Review by ericstj — APPROVED** [review]

**Comment by danmoseley** [comment]
failures - https://github.com/dotnet/runtime/issues/60151 already fixed.
System.Net.Sockets timeouts are clearly unrelated - I won't log an issue as this run is a bit old now.

I will rerun the timed out build out of an excess of caution.

**Pull request merged**
