### PR TITLE
Initialize variable prior to pedantic use.  Caught by ubsan on a bool.

### PR DESCRIPTION
**Pull request by RobertHenry6bev**

### CODE REVIEW

**Comment by bartonjs** [comment]
I don't understand why the tool would flag this one, but not the next function.

Either way, it's a false positive, `(void)variable` doesn't actually use the value, just tells the compiler to stop considering the variable unused (in this case, for builds where asserts disappear).

**Comment by RobertHenry6bev** [comment]
I beg to differ.  (void)expression will evaluate the expression and discard the value.  in this case the evaluation of variable is a read of the variable.  (void) will then discard what is read.  If the optimizer can prove that the read is unnecessary because the value is discarded, then so be it.  The optimizer can not prove the read is unnecessary.

The ubsan discovered this error at runtime, since the random value in the automatic storage (eg, the value left on the stack) happened to be neither 0 nor 1.

The other two cases in the following functions were not caught with this dynamically applied tool, either because the function was not called, or the unintialized automatic storage that was read happened to have either a 0 or a 1 in it, which is what ubsan is checking.

**Comment by danmoseley** [comment]
We can't legally declare local variables at the start of the scope block?

**Comment by RobertHenry6bev** [comment]
Of course you can declare local (automatic) variables at the start of any block.  You just can't read (use) the variable without first initializing it.
```
int variable;
...
(void)variable;
```
Is illegal.  The construct `(void)variable;` says to evaluate the expression `variable`, eg in the context of an expression, to read the variable.  The value of the expression `variable` is then typecast to void, which discards the expression's value.

I can write `(void)do_some_function_with_side_effects()  and the function will be called.

**Comment by danmoseley** [comment]
Sorry, I meant can't the fix just be: declare at the point of first assignment.

**Comment by RobertHenry6bev** [comment]
yes, perhaps more clear to my way of thinking is to have the (void)installed; sink below the monitor block, eg after the last assignment to installed and after the last possible use (through assert(...)).

I didn't do it that way just to keep to minimal diffs.

**Review by AntonLapounov — APPROVED** [review]
Looks good. Declaring at the point of the first assignment would work too.

**Pull request merged**
