### PR TITLE
[mono] Handle Assert failure when GetDelegateForFunctionPointer is invoked with VoidDelegate type

### PR DESCRIPTION
**Pull request by giritrivedi**
RunGetDelForFcnPtrTest is checking if "Invoke" Method is invoked when "GetDelegateForFunctionPointer" is passed
"VoidDelegate". In mono runtime instead of "Invoke" method, "wrapper_native_***" is invoked. The suffix of
"Wrapper_native" keeps changing with every run. With this fix "Invoke" method is returned instead of "wrapper_native_*"

### CODE REVIEW

**Comment by giritrivedi** [comment]
Hi @vargaz , @thaystg , @lambdageek 
Can someone review this?

**Comment by vargaz** [comment]
This might be a mono bug, these wrapper_native_ methods should not bubble up to app code.

**Comment by giritrivedi** [comment]
Yes, this is. The issue is seen on s390X architecture. 
Do I need to add any specific tag to the issue or to the description in order to mark it as mono bug ?

**Comment by vargaz** [comment]
There are mono specific labels.

**Comment by giritrivedi** [comment]
@vargaz ,  I have submitted a new fix . Plz reviews.

**Comment by vargaz** [comment]
Still don't think this is the right fix, these wrapper methods created in marshal.c should not be visible to managed code and should not appear in managed stack traces.

**Comment by giritrivedi** [comment]
@dotnet-policy-service agree company="IBM"

**Pull request closed without merging**
