### PR TITLE
Switch crossgen2 to use SHA256 for PDB hash

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet/crossgen-contrib

**Review by davidwrighton — APPROVED** [review]

**Review by trylek — APPROVED** [review]
Thanks for fixing this so quickly!

**Comment by GrabYourPitchforks** [comment]
The comment on line 191 of GenerateRSDSEntryData makes it seem like some other component is relying on the hash byte array being exactly 16 bytes in length (and thus already in a GUID). Are we missing a change somewhere?

**Comment by davidwrighton** [comment]
@GrabYourPitchforks The comment about ngen is obsolete, and was copied from the old implementation of this in crossgen.exe. We do take care to only write out 16 bytes of data. Note line 198 where only the next 8 bytes are written, not the rest of the hash.

**Review by GrabYourPitchforks — APPROVED** [review]

**Comment by GrabYourPitchforks** [comment]
@davidwrighton Makes sense. The comment - plus the fact that the code took care to write out GUID-endian format - threw me. Thanks for addressing it!

**Pull request merged**
