### PR TITLE
Fix access mode of memory-mapped apphost

### LINKED ISSUE #49332: UnauthorizedAccessException for apphost.exe when trying to use latest nightly dotnet build
When I try to use `dotnet build` or `dotnet run` with the latest nightly build, it crashes with this error:
"System.UnauthorizedAccessException: Access to the path 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\6.0.0-preview.3.21156.6\runtimes\win-x64\native\apphost.exe' is denied."
```
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018: System.UnauthorizedAccessException: Access to the path 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\6.0.0-preview.3.21156.6\runtimes\win-x64\native\apphost.exe' is denied. [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018:    at System.IO.FileStreamHelpers.ValidateFileHandle(SafeFileHandle fileHandle, String path, Boolean useAsyncIO) [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018:    at System.IO.FileStreamHelpers.CreateFileOpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options) [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018:    at System.IO.LegacyFileStreamStrategy..ctor(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018:    at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(String path, FileMode mode, String mapName, Int64 capacity, MemoryMappedFileAccess access) [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.<>c__DisplayClass2_0.<CreateAppHost>b__2() [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018:    at Microsoft.NET.HostModel.RetryUtil.RetryOnIOError(Action func) [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom) [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
C:\Program Files\dotnet\sdk\6.0.100-preview.3.21158.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(522,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\users\stoub\Desktop\Benchmarks\Benchmarks.csproj]
```

### PR DESCRIPTION
**Pull request by mateoatr**
Fix #49332

### CODE REVIEW

**Comment by agocke** [comment]
Any way to test this?

**Comment by stephentoub** [comment]
@brianrob's PR description in https://github.com/dotnet/runtime/pull/48774#issue-580348793 had two bullets for the purpose of the PR, one of which was:
"Use CopyOnWrite MemoryMappedFiles to avoid copying the template host."

Is the CopyOnWrite value passed to CreateViewAccessor sufficient to garner the gains he was aiming for, or does changing the CopyOnWrite to Read passed to CreateFromFile negate the gains from that PR?

**Comment by vitek-karas** [comment]
Reading the docs on [`MapViewOfFile`](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-mapviewoffile) specifically the `FILE_MAP_COPY` flag - it seems to be what we want. The file handle can be opened as read-only and still use the copy-on-write mapping. In that case that pages which are written to are copied into a private working set of the process (and changed from copy-on-write to read-write) and they are no longer backed by the original file (they're backed by the page file). Such pages are never written back to the original file and are discarded when the memory mapping is released.

I'll let @brianrob take another look when he's back, but I think the change is good as is.

**Review by vitek-karas — APPROVED** [review]

**Comment by stephentoub** [comment]
Great.

**Comment by brianrob** [comment]
Following up on this - the change looks good and does not impact the performance gain of the original change.  Thank you very much for handling this while I was out!

**Pull request merged**
