### PR TITLE
Fix potential Debug.Assert in QuicListener

### LINKED ISSUE #103911: Process terminated. Assertion failed. in System.Net.Http.Functional.Tests
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=717514
Build error leg or test failing: System.Net.Http.Functional.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/103873

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["Process terminated. Assertion failed.", "at System.Net.Quic.QuicListener.StartConnectionHandshake"],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```
```
Process terminated. Assertion failed.
   at System.Net.Quic.QuicListener.StartConnectionHandshake(QuicConnection connection, SslClientHelloInfo clientHello) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.cs:line 263
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 264
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 356
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 1020
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 128
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 100
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=717514
**Error message validated:** `[Process terminated. Assertion failed. at System.Net.Quic.QuicListener.StartConnectionHandshake`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/25/2024 12:14:09 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[718455](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718455)|dotnet/runtime|[System.Net.Quic.Tests.MsQuicTests.WriteTests](https://dev.azure.com/dnceng-public/public/_build/results?buildId=718455&view=ms.vss-test-web.build-test-results-tab&runId=18004386&resultId=207488)|dotnet/runtime#100194|
|[717514](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717514)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=717514&view=ms.vss-test-web.build-test-results-tab&runId=17972062&resultId=218012)|dotnet/runtime#103873|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|2|

### PR DESCRIPTION
**Pull request by rzikm**
Fixes #103911.

The reason the crash happened is that both `linkedCts` and `connection.ConnectionShutdownToken` fired. The code checked `ConnectionShutdownToken` first, assuming that the connection close because peer closed it during the handshake, but the reason for the exception was actually because the `HandshakeTimeout` ran out, so the control flow shouldn't have entered that catch block in the first place.

Checking that `linkedCts` has not been signalled yet eliminates the race.

### CODE REVIEW

**Review by ManickaP — APPROVED** [review]

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by wfurt** [comment]
can we craft test that would cause the timeout predictably?

**Comment by rzikm** [comment]
> can we craft test that would cause the timeout predictably?

we have a test for timeouts, but this the failure happened because the timeout ran out at the same time we got connection shutdown notification from MsQuic so it was effectively a data race. I don't see a way to craft a test for this (I tested this by adding extra waits and other changes to trigger the exact failure condition).

**Comment by rzikm** [comment]
/ba-g failures are either known or unrelated (wasm library build errors)

**Pull request merged**
