### PR TITLE
disable token info in traces.

### PR DESCRIPTION
**Pull request by mangod9**
Though token+offset is useful for certain scenarios, they might not be usable for majority of scenarios. So disabling them by default. It was enabled by default in https://github.com/dotnet/runtime/pull/44013

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]

**Comment by danmoseley** [comment]
Incidentally, I wanted to see how I'd set this flag without editing the code. I got to here
https://docs.microsoft.com/en-us/dotnet/api/system.appcontext?view=net-5.0#ForConsumers

and it says it's either registry or `<runtime>` section of app config. I'm guessing this should say that for .NET Core those don't work, and you should use runtimeconfig.json. It can point to https://docs.microsoft.com/en-us/dotnet/core/run-time-config/

@eerhardt is that right?

**Comment by eerhardt** [comment]
> @eerhardt is that right?

That doc looks like it hasn't been updated for .NET Core/5+. Nothing in the runtime respects app.config files, and I'm pretty sure we don't look in the registry anymore either.

**Review by noahfalk — APPROVED** [review]
Thanks for doing this @mangod9 👍 LGTM

**Comment by mangod9** [comment]
Assume we need a separate issue to fix the doc issue?

**Comment by noahfalk** [comment]
> Assume we need a separate issue to fix the doc issue?

Yeah, here is a random example of another issue tracking adding docs if it helps. https://github.com/dotnet/diagnostics/issues/1347

**Pull request merged**
