### PR TITLE
[wasm] fix aotProfiler init

### PR DESCRIPTION
**Pull request by pavelsavara**
This is also wrong on Net7 but this code path via cwraps was not used and it worked via `ccall`.
We don't need to backport it.

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Comment by pavelsavara** [comment]
this sample should run and trigger download file in your browser `src\mono\sample\wasm\browser-profile\`
without the fix it will just fail

**Comment by radical** [comment]
> this sample should run and trigger download file in your browser `src\mono\sample\wasm\browser-profile\`
> without the fix it will just fail

Oh, and it's not used by anything else right now? Or I guess not by 7.0 users, thus not backporting?

**Comment by pavelsavara** [comment]
> Oh, and it's not used by anything else right now? Or I guess not by 7.0 users, thus not backporting?

Thanks for asking @radical , I did bit more research.

So, the method had different name in Net7 it was `mono_wasm_load_profiler_aot` and it had `number` in the cwraps signature.
But the cwraps signature was not used and there was `ccall` in the profiler.ts with `string` signature. 
And it worked, so we don't need to backport.

I changed it in https://github.com/dotnet/runtime/pull/77779 and broken it without noticing it (which is Net8).
And this PR fixes it. 

We should eventually add some WBT+playwrite to cover more samples or more scenarios.
But I plan to work on AOT profiler bit more now, so maybe it would be too early to cover it with test now.

**Pull request merged**
