### PR TITLE
Delete `GT_SIMD_CHK` and `GT_HW_INTRINSIC_CHK`

### PR DESCRIPTION
**Pull request by SingleAccretion**
The former was unused, the latter - barely used. Overall, there is no need for these to be separate opers, it just leads to unnecessary `#ifdef`s.

There are two commits with this change: first just mechanically deletes the opers, leaving for back-compat places where the array checks were treated differently. The second commit removes the distinction as it is not a useful one.

Since the bounds checks are (no longer) array-only, the remaining oper was renamed to simply `GT_BOUNDS_CHECK`.

Some [diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1507109&view=ms.vss-build-web.run-extensions-tab) from the second commit, in particular the assertion propagation change.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Review by jakobbotsch — DISMISSED** [review]

**Comment by jakobbotsch** [comment]
Whoops, that approval was meant for #61911. 😄

**Review by AndyAyersMS — APPROVED** [review]
LGTM

**Comment by AndyAyersMS** [comment]
@echesakov are you going to review as well?

**Review by echesakov — APPROVED** [review]

**Pull request merged**
