### PR TITLE
Try adding cross-compilers for Musl

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Comment by lewing** [comment]
@steveisok I guess we need to add workload manifest entries everywhere too?

**Comment by lewing** [comment]
@dsplaisted is this how we are supposed to handle this?

**Comment by directhex** [comment]
We need a `mono-aot-cross` executable for every host->target pairing we care about. Pretty sure you're right about manifest changes also being needed, but I wanted to see if we could at least compile first

**Comment by steveisok** [comment]
> @steveisok I guess we need to add workload manifest entries everywhere too?

That's what it seems like given what Jo said.

**Comment by directhex** [comment]
OK, sadly not a best-case. real changes required to make it build. Will look tomorrow

**Comment by dsplaisted** [comment]
> @dsplaisted is this how we are supposed to handle this?

I don't understand the background for this enough to know.

**Comment by directhex** [comment]
`/home/directhex/Projects/runtime/artifacts/obj/mono/browser.wasm.Release/cross/out/bin/mono-aot-cross: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-aarch64.so.1, stripped`

**Comment by directhex** [comment]
Manifest changes will be needed in src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Current.Manifest/WorkloadManifest.json.in - unresolved issue is lack of emsdk nuget for Musl (we can solve this when we are self-building emsdk)

**Review by steveisok — APPROVED** [review]

**Pull request merged**
