### PR TITLE
[wasm-mt] Disable and fix remaining failing tests on Browser with multi-threading and perf tracing enabled

### LINKED ISSUE #74487: [wasm-ep] Wasm.Browser.EventPipe.Sample fails
The `Wasm.Browser.EventPipe.Sample` fails when wasm perf tracing is enabled. The process gets stuck and the test timeouts.

Console output:
```
ChromeDriver was started successfully.
[10:50:29] info: http://127.0.0.1:46767/dotnet.js 4:42242 "MONO_WASM: afterLoadWasmModuleToWorker added message event handler" Worker
[10:50:29] info: http://127.0.0.1:46767/dotnet.js 4:42242 "MONO_WASM: afterLoadWasmModuleToWorker added message event handler" Worker
[10:50:29] info: http://127.0.0.1:46767/dotnet.js 4:42242 "MONO_WASM: afterLoadWasmModuleToWorker added message event handler" Worker
[10:50:29] info: http://127.0.0.1:46767/dotnet.js 4:42242 "MONO_WASM: afterLoadWasmModuleToWorker added message event handler" Worker
[10:50:29] info: http://127.0.0.1:46767/dotnet.js 4 MONO_WASM: worker initializing essential C exports and APIs
[10:50:29] info: http://127.0.0.1:46767/dotnet.js 4 MONO_WASM: worker initializing essential C exports and APIs
[10:50:29] info: http://127.0.0.1:46767/dotnet.js 4 MONO_WASM: worker initializing essential C exports and APIs
[10:50:29] info: http://127.0.0.1:46767/dotnet.js 4 MONO_WASM: worker initializing essential C exports and APIs
[10:50:29] info: MONO_WASM: starting the diagnostic server url: ws://localhost:8088/diagnostics
[11:05:20] fail: Tests timed out. Killing driver service pid 31951
[11:05:20] fail: Application has finished with exit code TIMED_OUT but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

Full console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74410-merge-b99b2cf8b7b548de87/Wasm.Browser.EventPipe.Sample/1/console.4158a01b.log?helixlogtype=result

### PR DESCRIPTION
**Pull request by simonrozsival**
This PR
- disables failing tests #74411, #74413, and #75389
- fixes #74487
- increases pthread pool size for CI from the default 4 to 16
- updates the `browser-eventpipe` sample to make it CI friendly

### CODE REVIEW

**Comment by simonrozsival** [comment]
Tests that previously passed are now failing:
- WasmTestOnBrowser-Microsoft.Extensions.DependencyInjection.Tests
- WasmTestOnBrowser-System.Security.Cryptography.Tests
- WasmTestOnBrowser-System.Threading.Tasks.Dataflow.Tests

This PR will need some additional work to fix all the remaining failing tests in the multi-threaded lane. I wonder why it started failing now and how it's connected to the disabled tests.

**Comment by simonrozsival** [comment]
Sample stack trace of some failing `System.Threading.Tasks.Dataflow.Tests`:
```
[19:08:25] fail: [FAIL] System.Threading.Tasks.Dataflow.Tests.JoinBlockTests.TestTree
[19:08:25] info: System.Threading.Tasks.TaskSchedulerException : An exception was thrown by a TaskScheduler.
[19:08:25] info: ---- System.Threading.ThreadStartException : Thread failed to start.
[19:08:25] info: -------- System.ExecutionEngineException : mono_thread_platform_create_thread() failed
[19:08:25] info:    at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
[19:08:25] info:    at System.Threading.Tasks.Task.Start(TaskScheduler scheduler)
[19:08:25] info:    at System.Threading.Tasks.Dataflow.Internal.Common.StartTaskSafe(Task task, TaskScheduler scheduler)
[19:08:25] info:    at System.Threading.Tasks.Dataflow.Internal.SourceCore`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OfferAsyncIfNecessary_Slow(Boolean isReplacementReplica, Boolean outgoingLockKnownAcquired)
[19:08:25] info:    at System.Threading.Tasks.Dataflow.Internal.SourceCore`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OfferAsyncIfNecessary(Boolean isReplacementReplica, Boolean outgoingLockKnownAcquired)
[19:08:25] info:    at System.Threading.Tasks.Dataflow.Internal.SourceCore`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OfferAsyncIfNecessaryWithValueLock()
[19:08:25] info:    at System.Threading.Tasks.Dataflow.Internal.SourceCore`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddMessage(String item)
[19:08:25] info:    at System.Threading.Tasks.Dataflow.BufferBlock`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].System.Threading.Tasks.Dataflow.ITargetBlock<T>.OfferMessage(DataflowMessageHeader messageHeader, String messageValue, ISourceBlock`1 source, Boolean consumeToAccept)
[19:08:25] info:    at System.Threading.Tasks.Dataflow.DataflowBlock.Post[String](ITargetBlock`1 target, String item)
[19:08:25] info:    at System.Threading.Tasks.Dataflow.Tests.DataflowTestHelpers.PostRange[String](ITargetBlock`1 target, Int32 lowerBoundInclusive, Int32 upperBoundExclusive, Func`2 selector)
[19:08:25] info:    at System.Threading.Tasks.Dataflow.Tests.JoinBlockTests.CreateFillLink[String](Int32 messages, ITargetBlock`1 target)
[19:08:25] info:    at System.Threading.Tasks.Dataflow.Tests.JoinBlockTests.TestTree()
[19:08:25] info: --- End of stack trace from previous location ---
[19:08:25] info: ----- Inner Stack Trace -----
[19:08:25] info:    at System.Threading.Thread.ThrowThreadStartException(Exception ex)
[19:08:25] info:    at System.Threading.Thread.StartCore()
[19:08:25] info:    at System.Threading.Thread.Start(Boolean captureContext, Boolean internalThread)
[19:08:25] info:    at System.Threading.Thread.UnsafeStart()
[19:08:25] info:    at System.Threading.PortableThreadPool.WorkerThread.CreateWorkerThread()
[19:08:25] info:    at System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker(PortableThreadPool threadPoolInstance)
[19:08:25] info:    at System.Threading.PortableThreadPool.RequestWorker()
[19:08:25] info:    at System.Threading.ThreadPool.RequestWorkerThread()
[19:08:25] info:    at System.Threading.ThreadPoolWorkQueue.Enqueue(Object callback, Boolean forceGlobal)
[19:08:25] info:    at System.Threading.ThreadPool.UnsafeQueueUserWorkItemInternal(Object callBack, Boolean preferLocal)
[19:08:25] info:    at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
[19:08:25] info:    at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
[19:08:25] info:    at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
[19:08:25] info: ----- Inner Stack Trace -----
[19:08:25] info: 
[19:08:25] warn: 
[19:08:25] warn: Unhandled Exception:
[19:08:25] warn: System.Threading.ThreadStartException: Thread failed to start.
[19:08:25] warn:  ---> System.ExecutionEngineException: mono_thread_platform_create_thread() failed
[19:08:25] warn:    --- End of inner exception stack trace ---
[19:08:25] warn:    at System.Threading.Thread.ThrowThreadStartException(Exception ex)
[19:08:25] warn:    at System.Threading.Thread.StartCore()
[19:08:25] warn:    at System.Threading.Thread.Start(Boolean captureContext, Boolean internalThread)
[19:08:25] warn:    at System.Threading.Thread.UnsafeStart()
[19:08:25] warn:    at System.Threading.PortableThreadPool.WorkerThread.CreateWorkerThread()
[19:08:25] warn:    at System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker(PortableThreadPool threadPoolInstance)
[19:08:25] warn:    at System.Threading.PortableThreadPool.RequestWorker()
[19:08:25] warn:    at System.Threading.ThreadPool.RequestWorkerThread()
[19:08:25] warn:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[19:08:25] warn:    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[19:08:25] warn:    at System.Threading.Thread.StartCallback()
[19:08:25] warn: [ERROR] FATAL UNHANDLED EXCEPTION: System.Threading.ThreadStartException: Thread failed to start.
[19:08:25] warn:  ---> System.ExecutionEngineException: mono_thread_platform_create_thread() failed
[19:08:25] warn:    --- End of inner exception stack trace ---
[19:08:25] warn:    at System.Threading.Thread.ThrowThreadStartException(Exception ex)
[19:08:25] warn:    at System.Threading.Thread.StartCore()
[19:08:25] warn:    at System.Threading.Thread.Start(Boolean captureContext, Boolean internalThread)
[19:08:25] warn:    at System.Threading.Thread.UnsafeStart()
[19:08:25] warn:    at System.Threading.PortableThreadPool.WorkerThread.CreateWorkerThread()
[19:08:25] warn:    at System.Threading.PortableThreadPool.WorkerThread.MaybeAddWorkingWorker(PortableThreadPool threadPoolInstance)
[19:08:25] warn:    at System.Threading.PortableThreadPool.RequestWorker()
[19:08:25] warn:    at System.Threading.ThreadPool.RequestWorkerThread()
[19:08:25] warn:    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[19:08:25] warn:    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[19:08:25] warn:    at System.Threading.Thread.StartCallback()
```

**Comment by simonrozsival** [comment]
The `browser-eventpipe` is still failing but I'm unable to reproduce it locally just yet. I'll keep digging...

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
@kg is it reasonable to use 16 web workers for CI? Are we testing something that will never happen in real code?

**Comment by kg** [comment]
16 is definitely too much. In practice I don't think you'll see more than 8 real threads available on regular user machines anytime soon, and you could end up being limited to way less based on core count. (I don't know how the browser decides on the limit).

It makes sense to run some tests with high and low counts to test those scenarios though.

**Comment by lambdageek** [comment]
@simonrozsival It would be good to understand what the maximum required degree of parallelism is for those dataflow tests - ie: do they really need to run at least 8 threads in parallel, or is the threadpool just spinning up as many threads as it can because there are a lot of async tasks.

If the dataflow tests really have a high degree of required parallelism, we should make an issue to make simplified tests for threaded wasm.  If it's the threadpool, we should make an issue to make it understand that thread creation on wasm can fail sometimes and try to recover.

I don't think we should throw as many workers as we can at a test until it is passing, if we're past a reasonable limit on a user's machine.

**Comment by simonrozsival** [comment]
@lambdageek OK, I'll look deeper into the codebase

**Comment by lambdageek** [comment]
@simonrozsival [`TestFree`](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Threading.Tasks.Dataflow/tests/Dataflow/JoinBlockTests.cs#L454-L455) looks pretty busy, does the stability of the rest of the testsuite improve if you just disable that one?

Let's go with 8 and create an issue to look at these tests again.

**Comment by simonrozsival** [comment]
@lambdageek when that particular test is disabled, it sometimes succeeds, and sometimes it gets stuck. I tried finding a subset of `JoinBlockTests` that we could disable to get the tests passing reliably, but I wasn't successful. It might not be the only test class that is causing the problem after all.

BTW In the last test run I noticed that the `--web-server-use-cop` xharness flag disappeared from the Wasm.Browser.Threads.Sample and Wasm.Browser.EventPipe.Sample and I have no idea why it is missing. It seems as if the tests ran with the `$(RunScriptCommand)` from the basic Browser sample.

**Comment by lambdageek** [comment]
> @lambdageek when that particular test is disabled, it sometimes succeeds, and sometimes it gets stuck. I tried finding a subset of `JoinBlockTests` that we could disable to get the tests passing reliably, but I wasn't successful. It might not be the only test class that is causing the problem after all.

Ok, fair enough. Let's go with 8 workers for now.

> BTW In the last test run I noticed that the `--web-server-use-cop` xharness flag disappeared from the Wasm.Browser.Threads.Sample and Wasm.Browser.EventPipe.Sample and I have no idea why it is missing. It seems as if the tests ran with the `$(RunScriptCommand)` from the basic Browser sample.

I think the tests got rewritten using the new template which uses the wasm app host which I think knows when to add the additional headers on its own

**Comment by radical** [comment]
> BTW In the last test run I noticed that the --web-server-use-cop xharness flag disappeared from the Wasm.Browser.Threads.Sample and Wasm.Browser.EventPipe.Sample and I have no idea why it is missing. It seems as if the tests ran with the $(RunScriptCommand) from the basic Browser sample.

This got dropped in 448680517a26984227ac1e8a18b90e9a5d43d37b as it moved to building a custom RunScriptCommand, but missed referencing `WasmXHarnessArgs` which is getting that argument.

**Comment by radical** [comment]
When we feel confident about these, the tests can be enabled outside `runtime-wasm`. And we can stop ignoring the test failures.

**Comment by simonrozsival** [comment]
The `Build Browser wasm Linux Release LibraryTests_Threading` and `Build Browser wasm Linux Release LibraryTests_Threading_PerfTracing` legs are now green.

**Pull request merged**
