### PR TITLE
Add Span overloads to System.Numerics.Vectors

### LINKED ISSUE #25608: System.Numerics.Vectors and Span<T>
Please think about implementing this operator:

```csharp
public static partial struct Vector2
{
    public Vector2(ReadOnlySpan<byte> values);
    public Vector2(ReadOnlySpan<T> values);

    public readonly void CopyTo(Span<byte> destination);
    public readonly void CopyTo(Span<T> destination);
}

public static partial struct Vector3
{
    public Vector3(ReadOnlySpan<byte> values);
    public Vector3(ReadOnlySpan<T> values);

    public readonly void CopyTo(Span<byte> destination);
    public readonly void CopyTo(Span<T> destination);
}

public static partial struct Vector4
{
    public Vector4(ReadOnlySpan<byte> values);
    public Vector4(ReadOnlySpan<T> values);

    public readonly void CopyTo(Span<byte> destination);
    public readonly void CopyTo(Span<T> destination);
}
```

Since the span can be a stackallocated Array the performance gain should be huge! Also Vertical Operators are missing from Vector<T> like T Min(Vector<T> vector)

### PR DESCRIPTION
**Pull request by C-xC-c**
Fixes #25608

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
@tannergooding You've mentioned in the past that some SIMD instructions (specifically, floating-point instructions) have some weirdness when it comes to alignment. Is using `Read/WriteUnaligned` in these code paths likely to have noticeable perf impact?

**Comment by tannergooding** [comment]
> Is using Read/WriteUnaligned in these code paths likely to have noticeable perf impact?

It shouldn't on modern CPUs. The only real impact should be if it crosses a cache line or page boundary and then only if you repeatedly do that in a hot loop.

**Review by tannergooding — APPROVED** [review]

**Comment by tannergooding** [comment]
CC. @pgovind, can you give a quick review so we can merge?

**Review by pgovind — APPROVED** [review]
LGTM!

**Comment by tannergooding** [comment]
Thanks for the contribution!

**Pull request merged**
