### PR TITLE
SPMI: fix performance of `repRecordCallSite`.

### LINKED ISSUE #41635: superpmi: replay of a particular test takes a very long time.
"JIT\jit64\opt\cse\hugeexpr1.cs" takes at least an hour to be replayed at my machine using x64 collection.

It looks like ` void CompileResult::repRecordCallSite(ULONG instrOffset, CORINFO_SIG_INFO* callSig, CORINFO_METHOD_HANDLE methodHandle)` works much slower with SPMI that it is with CoreRun.

MD5 hash for the method was “E602D1102CCE1B86917BBAF7CA2C224B”.

cc @BruceForstall 

category:testing
theme:super-pmi
skill-level:beginner
cost:small

### PR DESCRIPTION
**Pull request by sandreenko**
After the fix the replay takes around ~100s (before 1000+) on my machine. It could be further improved but I do not think it is a bottle-neck now.

Note that we initialize this data only under `DEBUG` and only access this data from `CallUtils::GetRecordedCallSiteInfo` that is currently unused (as all other methods from `CallUtils` except `GetMethodFullName`), @BruceForstall do you remember what was the scenario when we were using `CallUtils`? If we can delete it we can do nothing for `repRecordCallSite` and save replay time.

Fixes #41635

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
What was causing the perf issues... hash collision?

**Comment by sandreenko** [comment]
> What was causing the perf issues... hash collision?

It is an artificial huge method that records ~10^4 call site with `sigInfo` and 3 * 10^5 without, so when we were putting them in the same map its size was several Gigabytes and the bottle-neck was reallocating this map. Now, we use less memory for the records without `sigInfo` so it works faster.

**Comment by sandreenko** [comment]
cc @dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]
It would be useful to add a comment, probably to `repRecordCallSite`, explaining why there are two maps for this particular call (namely, performance).

>  @BruceForstall do you remember what was the scenario when we were using CallUtils?

I don't remember. We often don't use much CompileResult, except for things we use for ASM diffs.

**Pull request merged**
