### PR TITLE
Add a WebAssembly version of System.Console.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
This has about half the size (linked) as the normal unix version (21k vs 45k).

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
> This has about half the size (linked) as the normal unix version (21k vs 45k).

What accounts for the difference?

**Comment by vargaz** [comment]
All the not implemented methods plus the simplified error handling, i.e. Interop.GetExceptionForIoErrno () is not used.

**Comment by stephentoub** [comment]
> All the not implemented methods

What keeps them linked in? Presumably the app isn't calling them.

**Comment by vargaz** [comment]
There is a huge amount of code which reads the terminal database. Some virtual methods like the Read() methods are also retained.

**Comment by stephentoub** [comment]
> There is a huge amount of code which reads the terminal database. Some virtual methods like the Read() methods are also retained.

Ok, thanks.  I'm fine with this being merged, though I think it'd be good in the future for us to try to factor things in such a way that the linker could get rid of more, e.g. the terminal database, if it's not needed.  It shouldn't be needed if the only thing the app is using is Console.ReadLine, for example.  And it'd be nice if the size gains could accrue in the future to apps on other Unixes as well.

cc: @eerhardt

**Comment by eerhardt** [comment]
> though I think it'd be good in the future for us to try to factor things in such a way that the linker could get rid of more

My understanding is the issue is the `virtual`-ness of `Stream`. Since `ConsoleStream` derives from `Stream`, and the linker needs to preserve the base `Stream.Read` (for obvious reasons), I don't think it will trim `ConsoleStream.Read`. It would probably be pretty hard to figure out statically if a `ConsoleStream` is ever passed into a method that takes a `Stream` and calls `.Read` on it.

cc @vitek-karas @MichalStrehovsky @sbomer

**Comment by vargaz** [comment]
The terminal db code is being kept alive by:
ConsolePal:Write() -> UpdatedCachedCursorPosition() -> GetWindowSize() -> TerminalFormatStrings.Instance.

**Comment by stephentoub** [comment]
> My understanding is the issue is the virtual-ness of Stream.

Isn't that Read small potatoes compared to the terminal db?

**Comment by eerhardt** [comment]
> Isn't that Read small potatoes compared to the terminal db?

My point wasn't specifically `Read`, it was that the virtual methods on a derived `Stream` aren't able to be trimmed.

**Comment by stephentoub** [comment]
> My point wasn't specifically Read, it was that the virtual methods on a derived Stream aren't able to be trimmed.

Understood, thanks.  I'm highlighting that most of those overrides throw just like the one in this PR, they just throw a more appropriate exception that requires a tiny bit more logic to compute.  So it doesn't look like we're saving a ton by having a custom ConsoleStream just for wasm; correct me if I'm wrong.  The larger piece here seems to be the avoidance of the terminal db code, which ended up getting brought in per https://github.com/dotnet/runtime/pull/35555#issuecomment-620723308 in as part of https://github.com/dotnet/runtime/commit/2ef9d363a2cdc5be0850f31d31f4a20e9202624c

**Pull request merged**
