### PR TITLE
[wasm] Make sure the TargetOS is capitalized

### LINKED ISSUE #54926: [wasm] Windows build fails when with -os browser
The windows build fails when the `build.cmd`s `-os` parameter is not capitalized.

With these errors:

    C:\r\src\libraries\shims\manual\System.forwards.cs(8,88): error CS0234: The type or namespace name 'ZLibException' does not exist in the namespace 'System.IO.Compression' (are you missing an assembly reference?) [C:\r\src\libraries\shims\manual\System.csproj]
    C:\r\src\libraries\shims\manual\System.forwards.cs(9,77): error CS0234: The type or namespace name 'CookieVariant' does not exist in the namespace 'System.Net' (are you missing an assembly reference?) [C:\r\src\libraries\shims\manual\System.csproj]
    C:\r\src\libraries\shims\manual\System.forwards.cs(10,77): error CS0234: The type or namespace name 'PathList' does not exist in the namespace 'System.Net' (are you missing an assembly reference?) [C:\r\src\libraries\shims\manual\System.csproj]

The issue here is that the parameter value is passed to msbuild as `/p:TargetOS=browser` and later used in target framework. Some projects, like `System.IO.Compression.csproj` contain:

    <TargetFrameworks>$(NetCoreAppCurrent)-windows;$(NetCoreAppCurrent)-Unix;$(NetCoreAppCurrent)-Browser</TargetFrameworks>

The target frameworks are case sensitive and the project is not build with `$(NetCoreAppCurrent)-Browser`, which leads later to missing references, when building `System.csproj`.

### PR DESCRIPTION
**Pull request by radekdoulik**
Fixes: https://github.com/dotnet/runtime/issues/54926

The `$(TargetOS)` is used in target framework, which is case sensitive.
Make sure it is capitalized for Browser, so that build.cmd works when
used like:

    ./build.cmd -bl -os browser -subset libs

It fixes build errors like:

    C:\r\src\libraries\shims\manual\System.forwards.cs(8,88): error CS0234: The type or namespace name 'ZLibException' does not exist in the namespace 'System.IO.Compression' (are you missing an assembly reference?) [C:\r\src\libraries\shims\manual\System.csproj]
    C:\r\src\libraries\shims\manual\System.forwards.cs(9,77): error CS0234: The type or namespace name 'CookieVariant' does not exist in the namespace 'System.Net' (are you missing an assembly reference?) [C:\r\src\libraries\shims\manual\System.csproj]
    C:\r\src\libraries\shims\manual\System.forwards.cs(10,77): error CS0234: The type or namespace name 'PathList' does not exist in the namespace 'System.Net' (are you missing an assembly reference?) [C:\r\src\libraries\shims\manual\System.csproj]

### CODE REVIEW

**Review by lewing — COMMENTED** [review]
does Configuration have a similar problem?

**Comment by radical** [comment]
What exactly was failing?

**Comment by radekdoulik** [comment]
> 
> 
> does Configuration have a similar problem?

Configuration is fine, https://github.com/dotnet/runtime/blob/39d2ba32ba0ebce7751818c672eb621090536dba/eng/build.ps1#L263

**Comment by radekdoulik** [comment]
> 
> 
> What exactly was failing?

`System.csproj` was failing, because some assemblies were not built. FOr example `System.IO.Compression` was not built with `net6.0-Browser` target framework.

**Review by radical — APPROVED** [review]
I'm not sure where exactly the case difference trips up the build, but this avoids getting into the broken state on windows. So, 👍

**Comment by akoeplinger** [comment]
Looks good to me but I'd have preferred something similar to what we do in build.sh where we do the remapping to the correct casing for all operating systems: https://github.com/radekdoulik/runtime/blob/b82cd2fb882f70e906ca6ee6858c1bdcdb407f15/eng/build.sh#L251-L284

**Pull request merged**
