### PR TITLE
Remove dependency on PerfCounter.dll

### PR DESCRIPTION
**Pull request by ericstj**
This dependency was unnecessary and only for calling through to pdh.dll.

PerfCounter.dll is still needed for the consumption side of performance
counters, but removing from the dependency from the .NET can help enable
some scenarios like reading non-.NET counters.

### CODE REVIEW

**Comment by ericstj** [comment]
Contributes to https://github.com/dotnet/runtime/issues/41144

**Comment by ericstj** [comment]
So running on ARM we now have:
```
=== TEST EXECUTION SUMMARY ===
   System.Diagnostics.PerformanceCounter.Tests  Total: 92, Errors: 0, Failed: 9, Skipped: 1, Time: 122.870s
```

The tests which fail are failing due to inability to read .NET perf counters.  This is due to absense of netfxperf.dll/perfcounter.dll.  I'm going through and fixing all the test conditions to address this.

**Comment by ericstj** [comment]
Fixes #34409 
Fixes #24176

**Comment by ericstj** [comment]
@Anipik @danmosemsft can you have a look at this one?  It enables the reading of non-.NET perf counters on Windows ARM64.

**Review by danmoseley — APPROVED** [review]
LGTM - I see FormatFromRawValue is just a pass through in perfcounter.dll

**Review by Anipik — COMMENTED** [review]
lgtm

**Pull request merged**
