### PR TITLE
[release/9.0] TypeName fuzzer and bug fixes

### PR DESCRIPTION
**Pull request by adamsitnik**
This PR combines the PRs that added Fuzzing for both `TypeName` and `AssemblyNameInfo` with the most recent bug fixes.

Once it gets merged there won't be known bugs related to `TypeName` and `AssemblyNameInfo` parsing in `release/9.0`

Fuzzing PR:

Backport of #107195 to release/9.0 (it has also contained empty name fix)
Backport of #107257 to release/9.0
Backport of #107206 to release/9.0

Bug fixes:

Backport of #106334 to release/9.0
Backport of #107261 to release/9.0

/cc @jkotas @buyaa-n

## Customer Impact

- [ ] Customer reported
- [x] Found internally

Two bugs were found by the Fuzzer (`sbyte` overflow and incorrect handling of empty assembly names), the last one was reported internally by @jkotas.

## Regression

- [ ] Yes
- [x] No

[If yes, specify when the regression was introduced. Provide the PR or commit if known.]

## Testing

All bugs discovered by the Fuzzer has been turned into unit tests (and of course are passing now).

## Risk

Low. The bug fixes were relatively simple:
- don't start `AssemblyNameInfo` parsing when provided name (span) is empty
- don't cast `int` to `sbyte` just to pass it to a `ctor` that accepts an `int`
- increase max node counter when parsing nested types

### CODE REVIEW

**Comment by adamsitnik** [comment]
@MihuBot fuzz TypeName

**Comment by adamsitnik** [comment]
@MihuBot fuzz AssemblyNameInfo

**Review by jkotas — APPROVED** [review]

**Comment by MihaZupan** [comment]
I added support to the bot for running against non-main base branches now.
It's been running the fuzzers for a couple of hours now: https://github.com/MihuBot/runtime-utils/issues/647, https://github.com/MihuBot/runtime-utils/issues/648
FYI the continuous fuzzing only runs against `main`.

**Review by jeffhandley — APPROVED** [review]
@artl93 - Please review this for RC2 inclusion

**Review by buyaa-n — APPROVED** [review]

**Review by artl93 — APPROVED** [review]

**Pull request merged**
