### PR TITLE
suggesting braces around initialization of subobject while building runtime repo 

### PR DESCRIPTION
**Pull request by ashwinik30**
`error: suggest braces around initialization of subobject`
fix : added braces as a fix

### CODE REVIEW

**Comment by vcsjones** [comment]
This seems to be something Clang and GCC disagree on. I'm fine taking the change. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80454

**Comment by bartonjs** [comment]
That issue says the opposite actually:

> The bug is that universal zero initializers are warned about when they are inside of some other initializer, even though we correctly stopped doing that when they appear on their own.

So long as this isn't causing a warning to appear from clang, I'm OK-ish with it (`{{0}}` looks too dense, and `{{ 0 }}` is weird (though maybe my favorite), `{ { 0 } }` is too empty, there's just no good answer, hence the "-ish").  If it comes down to a warning in clang or a warning in gcc... our build is really only supported with clang, AFAIK.

**Comment by ashwinik30** [comment]
hi @bartonjs and @vcsjones are the changes good to merge ?

**Comment by bartonjs** [comment]
I've seen that it doesn't cause any errors or warnings with clang using the OpenSSL 1.1.1 headers; but I haven't been able to try it out with OSSL 3(.anything) headers.  If someone wants to assert that it's warning-free with clang+OSSL3 then we can merge.

**Comment by vcsjones** [comment]
I will assert that it builds with OpenSSL 3.0 and Clang 16 warning / error free.

**Review by bartonjs — APPROVED** [review]

**Pull request merged**
