### PR TITLE
Update IHttpClientLogger.cs and IHttpClientAsyncLogger.cs remarks

### PR DESCRIPTION
**Pull request by danespinosa**
Updated IHttpClientLogger remarks to provide clearer documentation to a developer implementing this interface
This PR pairs up with the doc api pr https://github.com/dotnet/dotnet-api-docs/pull/10653

### CODE REVIEW

**Review by CarnaViire — APPROVED** [review]
LGTM, but I believe the actual [API docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.http.logging.ihttpclientlogger?view=net-8.0-pp#remarks) still need to be updated manually in https://github.com/dotnet/dotnet-api-docs

**Comment by danespinosa** [comment]
@CarnaViire would you have the direct link to the api doc? I searched and searched without any results, that's how I ended up fixing it here 😂

**Comment by danespinosa** [comment]
> @CarnaViire would you have the direct link to the api doc? I searched and searched without any results, that's how I ended up fixing it here 😂

@CarnaViire  I was looking wrong, I have found the doc here, I'll send the PR there too https://github.com/dotnet/dotnet-api-docs/blob/c4ea6458ca24b6cf5c17292db5136a974fb3a5f7/xml/Microsoft.Extensions.Http.Logging/IHttpClientLogger.xml#L4

**Comment by danespinosa** [comment]
> LGTM, but I believe the actual [API docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.http.logging.ihttpclientlogger?view=net-8.0-pp#remarks) still need to be updated manually in https://github.com/dotnet/dotnet-api-docs

Ok, I also fixed IHttpAsyncClientLogger.cs too and added the doc pr here https://github.com/dotnet/dotnet-api-docs/pull/10653

**Comment by CarnaViire** [comment]
> Ok, I also fixed IHttpAsyncClientLogger.cs too

Thanks!

> and added the doc pr here https://github.com/dotnet/dotnet-api-docs/pull/10653 but it seems here is the right place?

Hmm.... Sorry for that. The process was changing back and forth over the last couple of years; I was under impression that the changes in the triple-slash docs don't sync automatically (only manually -- usually via bulk PRs), but maybe that was an outdated info. Anyway, let's go forward with that one and see if it syncs.

**Comment by danespinosa** [comment]
> > Ok, I also fixed IHttpAsyncClientLogger.cs too
> 
> 
> 
> Thanks!
> 
> 
> 
> > and added the doc pr here https://github.com/dotnet/dotnet-api-docs/pull/10653 but it seems here is the right place?
> 
> 
> 
> Hmm.... Sorry for that. The process was changing back and forth over the last couple of years; I was under impression that the changes in the triple-slash docs don't sync _automatically_ (only manually -- usually via bulk PRs), but maybe that was an outdated info. Anyway, let's go forward with that one and see if it syncs.

Thanks @CarnaViire no worries I have updated the dotnet api docs before too so I also got confused 😂

**Comment by CarnaViire** [comment]
/ba-g second reported issue is actually the same infra error (`Build wasi-wasm linux Release LibraryTests_Smoke` timeout) as the already linked https://github.com/dotnet/dnceng/issues/3008

**Pull request merged**
