### PR TITLE
Trial reversion of37679

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Continuation of #38691

### CODE REVIEW

**Comment by kunalspathak** [comment]
@safern  - any idea why CI run didn't kick off automatically?

**Comment by safern** [comment]
No idea. Let's try closing and re-opening.

**Comment by AndyAyersMS** [comment]
Rebased so I could manually kick off some outerloop legs.

**Comment by AndyAyersMS** [comment]
@noahfalk do you know if we run any diagnostics tests with profiler-supplied enter/exit hooks on linux arm32?

Curious if I can find or create a repro for #38230 that does not involve jit stress or gc stress.

**Comment by noahfalk** [comment]
@davmason probably knows the answer. We've got some ELT tests but I can't recall if we have the win arm32 specific variant.

**Comment by davmason** [comment]
@AndyAyersMS the answer is not as clear cut as I would like. The ELT tests live in the private diagnostic tests repo, we don't run arm32 tests in CI there. We do have some ELT tests that theoretically should run on arm, but since they haven't been running for who knows how long I am not sure how much coverage they will provide. If you're just looking for a way to get an ELT profiler up and running I have an ELT profiler I built to help with the arm64 ELT bringup I could share

**Comment by AndyAyersMS** [comment]
The bug I'd be trying to repro (#38230) is arm linux so I'd need something that works exactly for that ISA/OS. I can find various profiler samples out there I could potentially adapt but none of them have the right low-level bits for arm/linux.

I suppose an alternative might be some sort of null profiler mode, where the runtime tells the jit to add the ELT hooks and the hooks get invoked at runtime but end up doing nothing as no profiler is registered -- do we have something like that? It would sure make adding a suitable test in our CI simpler....

**Comment by davmason** [comment]
There's COMPLUS_TestOnlyEnableSlowELTHooks, I haven't used it personally in a long time and the code that reads it is behind ifdef PROF_TEST_ONLY_FORCE_ELT so I am suspicious if it's still compiling on coreclr. 

The sample ELT profiler I have uses slow path ELT so shouldn't require require any changes to run on arm32. I can send it to you

**Comment by AndyAyersMS** [comment]
@dotnet/jit-contrib I think we should merge this as it should improve our arm32 jitstress/gcstress generally.

At this point it might be simpler to sort out what still fails afterwards.

**Review by BruceForstall — APPROVED** [review]

**Review by echesakov — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Let me rerun "runtime" at least to see if it clears up those errors.

**Comment by AndyAyersMS** [comment]
Still seeing those extensions failures, which were fixed in #39404 and I thought would merge up on rerun. Am going to merge anyways.

**Pull request merged**
