### PR TITLE
Disable Http3 tests for Arm

### PR DESCRIPTION
**Pull request by liveans**
Related to #103703 and #103404

### CODE REVIEW

**Comment by jkotas** [comment]
FWIW, these tests are not crashing frequently enough to require disabling all Quic testing on Arm. The crashes should be picked up by the know issue pattern match. I just updated it to be specific to arm. 

(If you prefer disabling the test, you can certainly do that.)

**Comment by liveans** [comment]
> FWIW, these tests are not crashing frequently enough to require disabling all Quic testing on Arm. The crashes should be picked up by the know issue pattern match. I just updated it to be specific to arm.
> 
> (If you prefer disabling the test, you can certainly do that.)

We think that this problem can be solved with msquic v2.4 release, also I agree that this can actually stay without disabling it, given that only affected CI is `runtime-extra-platforms`, and since it will be picked up by known issues, we should be fine.

@dotnet/ncl any pushback?

**Comment by rzikm** [comment]
> given that only affected CI is `runtime-extra-platforms`

The issue affects the outerloop pipeline as well

image

Given that we already disable Quic tests on ARM32, doing the same for HTTP3 tests still makes sense to me.

**Review by rzikm — APPROVED** [review]

**Pull request merged**
