### PR TITLE
Support nocheck prefix

### PR DESCRIPTION
**Pull request by john-h-k**
Resolves #10112

> I would think that, at the very least, we should ignore the opcode (other than the "correctness/verifiability" checks) rather than throwing InvalidProgramException.

It is spec compliant, as it is just a hint, but right now it has no actual functionality (it is verified and immediately ignored). It needs test but I don't know how to write JIT tests yet

It does not allow multiple `no`. prefixes, such as
`no. typecheck no. rangecheck ldelema` - only `no. typecheck | rangecheck ldelema`

### CODE REVIEW

**Comment by ltrzesniewski** [comment]
I'd prefer if you didn't close the issue with a no-op implementation. Sure, it's ECMA-compliant and a good first step, but it does not really implement the feature I'm interested in. 😉

**Comment by john-h-k** [comment]
On a seperate branch I'm working on an actual functioning implementation. So far I've got the basic idea of range check elimination but it's hitting some assertions in morph

**Comment by john-h-k** [comment]
At the moment, `GTF_INX_RNGCHK` has the same value as `GTF_VAR_DEF` which is causing an assertion in `gfMorphLocalVar` to be hit

**Comment by abelbraaksma** [comment]
This is very interesting, and a language like F# could benefit greatly once this is implemented (meaning, if the nullcheck, rangecheck, typecheck are actually skipped). Esp the rangecheck is very beneficial, as in F# many code paths exist that are verifiably correct, but are not always optimized properly in JIT. 

The nullcheck is already skipped quite often by JIT, though it wouldn't hurt making this explicit in F# code, which has a lot non-nullable types. 

(I understand that, once this is implemented, such IL would not be verifiable itself, as the spec states.)

**Comment by john-h-k** [comment]
Came back to this and managed to get `no. rangecheck ldelem/stelem`, `no. nullcheck callvirt` and `no. typecheck castclass` all working. Some of the others require adding new helper methods which I'll give a shot tomorrow

**Comment by abelbraaksma** [comment]
Awesome stuff!

**Comment by AndyAyersMS** [comment]
@john-h-k this PR is getting a bit stale -- any plans to revive it, or should we close and revisit later?

**Comment by ViktorHofer** [comment]
// Auto-generated message

https://github.com/dotnet/runtime/commit/69e114c1abf91241a0eeecf1ecceab4711b8aa62 which was merged 12/7 removed the intermediate src/coreclr/**src**/ folder. This PR needs to be updated as it touches files in that directory which causes conflicts.

To update your commits you can use this bash script: https://gist.github.com/ViktorHofer/6d24f62abdcddb518b4966ead5ef3783. Feel free to use the comment section of the gist to improve the script for others.

**Comment by john-h-k** [comment]
@AndyAyersMS 

Sorry about that - been very busy. I'll revisit it on Friday night or Saturday and give an update on it when I do

**Comment by AndyAyersMS** [comment]
@john-h-k seems like maybe we should close this?

**Comment by abelbraaksma** [comment]
I hope this could be resurrected, compilers could benefit greatly once this gets in.

**Pull request closed without merging**
