### PR TITLE
[lib][tests] Globalization comparison tests cleanup

### PR DESCRIPTION
**Pull request by ilonatommy**
Initiated by https://github.com/dotnet/runtime/pull/85965#discussion_r1194034950. 
In the original globalization comparison tests we used to have test cases with multiple comparison options. Actually never all 3 declared options were relevant which obscured the test readibility. This PR reduces the number of options passed to minimum.

### CODE REVIEW

**Review by mkhamoyan — APPROVED** [review]

**Comment by mkhamoyan** [comment]
Looks good to me. Let's wait for tests to run on iOS.

**Comment by ilonatommy** [comment]
ios failures are unrelated

**Comment by mkhamoyan** [comment]
@ilonatommy there is also supportedCmpOptions which looks like same property. As in my current PR https://github.com/dotnet/runtime/pull/85965 I am touching a lot of lines after this PR got merged there will be need to check a lot of lines one by one. So my suggestion is either I can do these refactoring in my current PR, either let's do this after my PR got merged?

**Comment by mkhamoyan** [comment]
Thanks, I will do then.

**Review by mdh1418 — APPROVED** [review]
Thanks for going in and finding the minimum options!

**Comment by ilonatommy** [comment]
This will get in with https://github.com/dotnet/runtime/pull/85965. We checked that CI is passing with the changes but decided that it's less confusing for Meri to incorporate the changes directly in her PR.

**Pull request closed without merging**
