### PR TITLE
Baseline two failing tests to make outerloop green again

### PR DESCRIPTION
**Pull request by trylek**
/cc @dotnet/runtime-infrastructure

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Are you still seeing `Interop/PInvoke/Generics/GenericsTest` fail after #61229?

**Comment by trylek** [comment]
@AndyAyersMS - well, I saw the failure in my two outerloop runs from last night. If it was actually fixed last night we don't really need the GenericsTest exclusion anymore; I didn't notice the bug was closed. In light of your clarification I'll remove the exclusion from issues.targets and I'll rerun the job to double-check.

**Comment by trylek** [comment]
@AndyAyersMS - interesting, so the test now only fails on arm64 in Crossgen2 mode complaining about mismatch between the compiler-calculated and runtime type layout for Vector:

<pre>
   Testing Vector<bool>
      Type System.Numerics.Vector`1: expected HFA type 00000004, actual 00000000
</pre>

I can confirm I no longer see the bug on Linux x64. The new failure is common to Windows and Linux.

**Comment by AndyAyersMS** [comment]
The new failure has to be something different (though perhaps similar). 

Maybe we're letting some detail of the build machine bleed through?

**Comment by trylek** [comment]
Well, I guess it would be easiest to start from the semantic side - what is the 'expected' HFA value for Vector<bool> on arm64? Is it 4 (as Crossgen2 expects) or 0 (as runtime sets on the type)?

**Comment by BruceForstall** [comment]
@trylek Is this exclusion still needed? I'm confused on the state of things given the conversation.

**Comment by trylek** [comment]
Well, for the GenericTest, that still fails but on other platforms and with a different bug. The test45929 continues failing on arm, albeit non-deterministically (sometimes it passes). I'll update the PR with the new exclusion for GenericTest based on outcomes of the above outerloop test.

**Comment by trylek** [comment]
OK, my bad, I messed up the 2nd iteration - when I sent out the first iteration and Andy Ayers pointed out that the GenericTest should be fixed now, I inadvertently deleted a different exclusion for the GenericTest from the issues.targets file because I didn't notice there were two different ones. That is fixed now and that should make the remaining outerloop failures disappear.

**Review by AndyAyersMS — COMMENTED** [review]
So you're just excluding the one test on windows arm32...?

**Comment by trylek** [comment]
Yes, exactly, as you apparently fixed the GenericTest its exclusion is no longer necessary. The pre-existing exclusion is still in place though, the issue https://github.com/dotnet/runtime/issues/60036 remains in place. It's currently assigned to me but I must admit I'm not an arm64 expert so I need help in figuring out what exactly needs fixing there - i.o.w., which HFA value is the "right one", that should imply whether we need to fix the runtime or Crossgen2 to put them in sync.

**Review by AndyAyersMS — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Formatting was fixed by Bruce in #61334. Not even sure why it is running here.

**Comment by trylek** [comment]
OK, so we're back to two test exclusions now ;-).

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
