### PR TITLE
Adjust console error logging for msbuild

### LINKED ISSUE #37431: Compiler error in native coreclr code build on Windows is not printed to console
When I run build locally (e.g. using `build.cmd Clr+Libs` from the root of the repo) and the compilation of coreclr fails due to a bug in the native source code, the compiler error message is not printed to console anymore. It is only recorded in the build log files. 
This is painful and we should fix it so that the error message is printed to console too, as it used to be in the recent past.

### PR DESCRIPTION
**Pull request by davidwrighton**
- Show a summary of error on completion
- And don't attempt to force alignment to screen width (which will allow for better copy/paste from the console)

Fixes #37431

### CODE REVIEW

**Comment by davidwrighton** [comment]
@ivdiazsa I didn't realize you were looking at this issue. Regardless, this is my approach to fixing it, which I believe addresses the problem. I'd appreciate it if you took a quick look and identified if you also agree the errors are easier to find on the console now.

**Comment by ivdiazsa** [comment]
Just checked and it looks good to me. I have one question though. What is the `ForceNoAlign` flag? Is it just for formatting purposes?

**Comment by davidwrighton** [comment]
Yes, its formatting, what it does is cause msbuild to not inject line breaks at the end of lines. That has the effect that if there is a long error, you can use copy/paste out of the console window file names that were line broken.

**Review by jkoritzinsky — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by jkotas** [comment]
Do we need same fix in the Unix shell scripts?

**Comment by davidwrighton** [comment]
@jkotas, the native build for Unix doesn't have this problem. Up until last week it had a different problem where build failures were ignored entirely, but I fixed that last week.

However, the top level build process which builds the managed code may/may not have this problem. Its not a thing I've worked on and noticed.

**Pull request merged**
