### PR TITLE
Fix SslStress docker build

### LINKED ISSUE #72399: SslStress fails to build on Linux
```
/app/System.Net.Security/tests/StressTests/SslStress/Directory.Build.targets(2,3): error MSB4019: The imported project "/live-runtime-artifacts/targetingpacks.targets" was not found. Confirm that the expression in the Import declaration "/live-runtime-artifacts/targetingpacks.targets" is correct, and that the file exists on disk. [/app/System.Net.Security/tests/StressTests/SslStress/SslStress.csproj]

Build FAILED.
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1886274&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=6c56d998-158d-5232-283c-5140104799fc

It also repros locally for me. `/live-runtime-artifacts` is missing from the SslStress container image filesystem, possible explanation is that `run-docker-compose.sh` fails to propagate the correct correct `$SDK_BASE_IMAGE`.

### PR DESCRIPTION
**Pull request by antonfirsov**
Fixes #72399, broken by #62102

### CODE REVIEW

**Comment by am11** [comment]
> broken by #62102

#62102 changed non-empty string comparison

```
 if [[ "$imagename" != "" ]]; then
```
to non-zero length comparison
```
 if [[ -n "$imagename" ]]; then
```

which is correct  drop-in replacement. This means it was broken before my change...

**Comment by am11** [comment]
Ah, I was looking at HttpStress, the change in StressTest was wrong. Sorry about that. :slightly_smiling_face:

**Review by wfurt — APPROVED** [review]
LGTM

**Pull request merged**
