### PR TITLE
[runtime] Try to load assemblies from bundles on netcore before trying other methods, the ALC might not be initialized yet.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
Without this, calls made to mono_assembly_open () by embedders might end up in assembly-load-context.c:invoke_resolve_method () with a NULL alc->gchandle.

**Comment by vargaz** [comment]
Even without that problem, I think its better to check bundles first, it avoids going into all the alc callbacks etc. so they could be linked out in some cases.

**Review by CoffeeFlux — APPROVED** [review]
Checking bundles first sounds fine to me.

**Comment by jaredpar** [comment]
@vargaz why was this PR merged when test failures were present? This merge ended up taking down all of CI as it broke our rolling builds. This was completely preventable.

**Pull request merged**
