### PR TITLE
FixOptRepeat and force repeating

### PR DESCRIPTION
**Pull request by BruceForstall**
https://github.com/dotnet/runtime/pull/94250
and force repeat each function 4x

### CODE REVIEW

**Comment by BruceForstall** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=624227&view=ms.vss-build-web.run-extensions-tab)

Huge code size improvements: 4MB or more.

TP measurement is odd: on Linux, -0.20% or so, but no change on Windows?

Note that there are a lot more "missing" contexts with OptRepeat.

**Comment by EgorBo** [comment]
While I love the size wins 🙂 it's hard to believe that 4 iterations of SSA + VN + assertprop + etc lead to 0.00% TP on most platforms?

**Comment by BruceForstall** [comment]
Ah, ok, the TP non-change makes sense. OptRepeat isn't getting turned on in Release.

**Comment by AndyAyersMS** [comment]
> Ah, ok, the TP non-change makes sense. OptRepeat isn't getting turned on in Release.

It will need to be enable-able in release for the experiments to work there.

**Pull request closed without merging**
