### PR TITLE
Remove race condition from DllImportGenerator build

### LINKED ISSUE #61687: Race condition writing Microsoft.Interop.DllImportGenerator.dll during library product build (Windows x64 Release)
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1472395&view=logs&j=3ee9f22f-fdeb-5ba9-4d07-86b7b8a7437b&t=796c5bee-4d73-5a57-e6ab-2038dda597c4

Observed on platform: **Windows x64 Release** (the failure is apparently non-deterministic so it may also repro on other platforms)

Diagnostic output:

<pre>
  System.Private.CoreLib.Generators -> D:\a\_work\1\s\artifacts\bin\System.Private.CoreLib.Generators\netstandard2.0-Release\System.Private.CoreLib.Generators.dll
  Microsoft.Interop.SourceGeneration -> D:\a\_work\1\s\artifacts\bin\Microsoft.Interop.SourceGeneration\netstandard2.0-Release\Microsoft.Interop.SourceGeneration.dll
CSC : error CS2012: Cannot open 'D:\a\_work\1\s\artifacts\obj\DllImportGenerator\netstandard2.0-Release\Microsoft.Interop.DllImportGenerator.dll' for writing -- 'The process cannot access the file 'D:\a\_work\1\s\artifacts\obj\DllImportGenerator\netstandard2.0-Release\Microsoft.Interop.DllImportGenerator.dll' because it is being used by another process.' [D:\a\_work\1\s\src\libraries\System.Runtime.InteropServices\gen\DllImportGenerator\DllImportGenerator.csproj]
##[error]CSC(0,0): error CS2012: (NETCORE_ENGINEERING_TELEMETRY=Build) Cannot open 'D:\a\_work\1\s\artifacts\obj\DllImportGenerator\netstandard2.0-Release\Microsoft.Interop.DllImportGenerator.dll' for writing -- 'The process cannot access the file 'D:\a\_work\1\s\artifacts\obj\DllImportGenerator\netstandard2.0-Release\Microsoft.Interop.DllImportGenerator.dll' because it is being used by another process.'
  DllImportGenerator -> D:\a\_work\1\s\artifacts\bin\DllImportGenerator\netstandard2.0-Release\Microsoft.Interop.DllImportGenerator.dll
</pre>

Based on my past experience I would expect this to be caused by interlocking holes that cause two projects to try building the DllImportGenerator project in parallel but I'm not a library build expert. @jkoritzinsky, based on your experience with Roslyn generators, could you please suggest how to continue the investigation?

Thanks

Tomas

### PR DESCRIPTION
**Pull request by jkoritzinsky**
We had a race condition in the DllImportGenerator build due to the workaround implemented for Roslyn 4.0 RC1's new assembly loading scheme. RC2 has a fix that should work to enable us to remove the workaround.

Fixes #61687

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
It looks like the Roslyn bug that I was working around didn't get fixed until after the RC2 release, so this fix as-is depends on the 6.0 RTM SDK update.

I'll try to figure out another fix that works in both VS and at the command line, but it might take a bit

**Comment by trylek** [comment]
I just checked on the [succeeding] leg I retried in the originally failing run and I clearly see in the log that the DllImportGenerator project gets built twice - perhaps it's a dumb idea but wouldn't it be possible to just somehow deduplicate this at the build script level?

<pre>
  WindowsBase -> D:\a\_work\1\s\artifacts\bin\WindowsBase\net7.0-Release\WindowsBase.dll
  System.Private.CoreLib.Generators -> D:\a\_work\1\s\artifacts\bin\System.Private.CoreLib.Generators\netstandard2.0-Release\System.Private.CoreLib.Generators.dll
  Microsoft.Interop.SourceGeneration -> D:\a\_work\1\s\artifacts\bin\Microsoft.Interop.SourceGeneration\netstandard2.0-Release\Microsoft.Interop.SourceGeneration.dll
  DllImportGenerator -> D:\a\_work\1\s\artifacts\bin\DllImportGenerator\netstandard2.0-Release\Microsoft.Interop.DllImportGenerator.dll
  DllImportGenerator -> D:\a\_work\1\s\artifacts\bin\DllImportGenerator\netstandard2.0-Release\Microsoft.Interop.DllImportGenerator.dll
  System.Collections.Specialized -> D:\a\_work\1\s\artifacts\bin\System.Collections.Specialized\net7.0-Release\System.Collections.Specialized.dll
  System.Collections.NonGeneric -> D:\a\_work\1\s\artifacts\bin\System.Collections.NonGeneric\net7.0-Release\System.Collections.NonGeneric.dll
</pre>

**Comment by jkoritzinsky** [comment]
We could try to deduplicate it, but we'd be relying on "private" MSBuild semantics in the implementation of ProjectReferences.

**Comment by jkoritzinsky** [comment]
I was able to hack something together that should work. It's not the cleanest, but since I'm going to remove the workaround next month, we should be fine.

**Review by trylek — APPROVED** [review]
Looks great to my limited understanding, thanks for providing the stopgap fix!

**Comment by jkoritzinsky** [comment]
There's still another race here apparently (just hit it locally). Back to the drawing board I guess.

**Comment by jkoritzinsky** [comment]
Got another design. This one should avoid the case that caused a race condition in my last attempt.

**Comment by trylek** [comment]
Sounds like a solid design for the temporary workaround, thanks Jeremy; LGTM to the extent of my still limited understanding of Roslyn generators (after all that's why I asked you to take an initial look in the first place).

**Review by safern — APPROVED** [review]
LGTM, I'm glad this is just temporary 😄

**Comment by MichalStrehovsky** [comment]
I just hit a race with what's in main right now. Clean enlistment/deleted artifacts, followed by `build.cmd libs -rc Release`.

```
C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\Microsoft.Common.CurrentVersion.targets(3264,5): error MSB3554: Cannot write to the output file "C:\git\runtime2\artifacts\obj\Microsoft.Interop.SourceGeneration\netstandard2.0-Release\Microsoft.Interop.Resources.resources". The process cannot access the file 'C:\git\runtime2\artifacts\obj\Microsoft.Interop.SourceGeneration\netstandard2.0-Release\Microsoft.Interop.Resources.resources' because it is being used by another process. [C:\git\runtime2\src\libraries\System.Runtime.InteropServices\gen\Microsoft.Interop.SourceGeneration\Microsoft.Interop.SourceGeneration.csproj]
CSC : error CS1566: Error reading resource 'Microsoft.Interop.Resources.resources' -- 'Could not find file 'C:\git\runtime2\artifacts\obj\Microsoft.Interop.SourceGeneration\netstandard2.0-Release\Microsoft.Interop.Resources.resources'.' [C:\git\runtime2\src\libraries\System.Runtime.InteropServices\gen\Microsoft.Interop.SourceGeneration\Microsoft.Interop.SourceGeneration.csproj]
```

Rolling back the commit associated with this pull request unblocked me.

**Pull request merged**
