### PR TITLE
Add some upcoming distro RIDs

### PR DESCRIPTION
**Pull request by omajid**
This adds some RIDs that we know are current/upcoming:

- Fedora 33 is in development, and the version after this is most likely going to be Fedora 34. Adding this RID now, so we can get this RID in all current releases when it comes time to build on Fedora 34

- RHEL has generally committed to doing a major release every 3 years. With RHEL 8 released in 2019, RHEL 9 is under development. There's even a plan on how to create that from Fedora here: https://fedoraproject.org/wiki/Changes/ELN_Buildroot_and_Compose. [Also called out here]( https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/7DBZ423UD6AGKD2OCWT4FPWJXBI3KJRI/)

- If there's a RHEL 9, there will most likely be an equivalent CentOS 9. Lets add that too.

- CentOS 7 has an arm64 (aka aarch64) port. As does CentOS 8.

One question: I noticed that this creates an RID graph with an entry for `rhel.7-arm64`. This RID doesn't already exist in the graph. Is that a bad thing? Should I split out the CentOS entries? Should I add an RID for `rhel.7-arm64`, which isn't really "supported", but was a product at one point?

### CODE REVIEW

**Comment by danmosemsft** [comment]
I think (?) this is part of what @wfurt took over from @bartonjs.

**Comment by omajid** [comment]
Anyone willing to review this?

**Comment by danmosemsft** [comment]
Maybe @bartonjs if @wfurt isn't available

**Comment by bartonjs** [comment]
Historically, we've avoided adding things into the RID graph until there's some evidence that the next version is already named (think of it as "everyone was surprised at Windows 10 being 10", but also SUSE's rebrand/reset).  I think I'm willing to handwave and say that someone from RedHat pushing for things RedHat has a lot of influence over (if not outright control over) is acceptable.

This currently doesn't build, do to reporting a dependency on a node that doesn't exist.  I don't have strong opinions on whether we should add a vacuous entry for rhel7-arm64 or split the definition of CentOS inheritance.  @ericstj?

**Comment by omajid** [comment]
> Historically, we've avoided adding things into the RID graph until there's some evidence that the next version is already named (think of it as "everyone was surprised at Windows 10 being 10", but also SUSE's rebrand/reset). I think I'm willing to handwave and say that someone from RedHat pushing for things RedHat has a lot of influence over (if not outright control over) is acceptable.

If it makes you more comfortable, I can remove this part of the patch and just deal with `centos.8-arm64` + `fedora.34-x64` for now. We can perhaps revisit `rhel.9-x64` in a few months/year?

**Comment by wfurt** [comment]
> If it makes you more comfortable, I can remove this part of the patch and just deal with `centos.8-arm64` + `fedora.34-x64` for now. We can perhaps revisit `rhel.9-x64` in a few months/year?

With 32 & 33 Fedora still in future, adding 34 seems quite far given @bartonjs guidance. 
For RHEL, 9 seems more reasonable. Are there any developer preview builds or branch somebody can checkout and build as 9.x @omajid? 

'rhel7-arm64' seems fine since `isn't really "supported", but was a product at one point`.
It feels like simplicity e.g. forking at RHEL would be be better that tracking support contracts.
I would also defer this one to @ericstj

**Comment by omajid** [comment]
As an additional piece of context: please note that Fedora (32 and later) includes .NET Core SDK 3.1 as a standard distro package. You can install `dotnet-sdk-3.1` in Fedora just like you can install `clang` or `gcc` or `curl`. As part of that, the SDK needs to know the RID.

> With 32 & 33 Fedora still in future, adding 34 seems quite far given @bartonjs guidance.

In practice, they are not far at all. According to [the schedule](https://fedorapeople.org/groups/schedule/f-32/f-32-key-tasks.html), 32 is "done" development. 33 is in development. At some point in the future, that will be forked to Fedora 34. When that fork is created, the SDK build in Fedora already needs to know about that RID. Or the SDK in Fedora 34 will stop working.

I can definitely wait a few months, but we need to make this change (in isolation in Fedora, or here in the main repositories) to make this RID available before Fedora 34 starts development and the `fedora.34-x64` RID is set up on the system.

> For RHEL, 9 seems more reasonable. Are there any developer preview builds or branch somebody can checkout and build as 9.x @omajid?

Nope, there's nothing there that I know of. As I linked to earlier, right now there's only discussions going on in the Fedora community on how to create something that might eventually be called RHEL 9.

FWIW, I think RHEL 9 is much further off than Fedora 34.

**Comment by omajid** [comment]
@ericstj Thanks, fixed.

**Review by ericstj — COMMENTED** [review]
This looks good to me.  @wfurt?

**Review by ericstj — APPROVED** [review]

**Review by wfurt — APPROVED** [review]
LGTM.

**Pull request merged**
