### PR TITLE
Fix ConcurrentDictionary test by rooting members accessed via reflection

### LINKED ISSUE #81945: System.Collections.Concurrent.Tests.ConcurrentDictionary_Generic_Tests_string_string.NonRandomizedToRandomizedUpgrade_FunctionsCorrectly fails on extra-platforms
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=165856
Build error leg or test failing: System.Collections.Concurrent.Tests.ConcurrentDictionary_Generic_Tests_string_string.NonRandomizedToRandomizedUpgrade_FunctionsCorrectly
Pull request: https://github.com/dotnet/runtime/pull/81481

## Error Message

```
[FAIL] System.Collections.Concurrent.Tests.ConcurrentDictionary_Generic_Tests_string_string.NonRandomizedToRandomizedUpgrade_FunctionsCorrectly(ignoreCase: False)
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Collections.Concurrent.Tests.ConcurrentDictionary_Generic_Tests_string_string.<GenerateCollidingStrings>g__GetHashCodeFunc|4_0(ConcurrentDictionary`2 cd) + 0x30
   at System.Collections.Concurrent.Tests.ConcurrentDictionary_Generic_Tests_string_string.GenerateCollidingStrings(Int32 count) + 0x6c
   at System.Collections.Concurrent.Tests.ConcurrentDictionary_Generic_Tests_string_string.NonRandomizedToRandomizedUpgrade_FunctionsCorrectly(Boolean ignoreCase) + 0x1f
   at System.Collections.Concurrent.Tests!<BaseAddress>+0x909a6d
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x167
[FAIL] System.Collections.Concurrent.Tests.ConcurrentDictionary_Generic_Tests_string_string.NonRandomizedToRandomizedUpgrade_FunctionsCorrectly(ignoreCase: True)
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Collections.Concurrent.Tests.ConcurrentDictionary_Generic_Tests_string_string.<GenerateCollidingStrings>g__GetHashCodeFunc|4_0(ConcurrentDictionary`2 cd) + 0x30
   at System.Collections.Concurrent.Tests.ConcurrentDictionary_Generic_Tests_string_string.GenerateCollidingStrings(Int32 count) + 0x6c
   at System.Collections.Concurrent.Tests.ConcurrentDictionary_Generic_Tests_string_string.NonRandomizedToRandomizedUpgrade_FunctionsCorrectly(Boolean ignoreCase) + 0x1f
   at System.Collections.Concurrent.Tests!<BaseAddress>+0x909a6d
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x167
```

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/81945

### CODE REVIEW

**Review by eiriktsarpalis — APPROVED** [review]

**Comment by eiriktsarpalis** [comment]
If CI is happy LGTM

**Comment by MichalStrehovsky** [comment]
FWIW, this test would not require the RD.XML if the test replaced `cd.GetType().GetField("_tables", BindingFlags.Instance | BindingFlags.NonPublic)` and similar with `typeof(ConcurrentDictionary<string, string>).GetField("_tables", BindingFlags.Instance | BindingFlags.NonPublic)` (if they're equivalent - they might in this case?).

The reflection analysis only analyzes `foo.GetType()` if `foo` is sealed.

`typeof(X).GetField("literal")` works all the time.

**Pull request merged**
