### PR TITLE
[wasm][debugger][tests] Add some async stepping tests

### PR DESCRIPTION
**Pull request by radical**
.. some of which are failing, with issues filed.

### CODE REVIEW

**Comment by radical** [comment]
@thaystg the tests from the two filed issues are included here, though they are disabled.

**Review by thaystg — APPROVED** [review]
LGTM

**Comment by radical** [comment]
Rebased on master, tracking changes in debugger test files' location.

**Review by thaystg — APPROVED** [review]
LGTM

**Pull request merged**
