### PR TITLE
Onboard new inter-branch merge flow [Workflow]

### PR DESCRIPTION
**Pull request by f-alizada**
### Context
Onboarding new merge flow based on the github actions

### Changes Made
Added github workflow for the branch.

### References
Documentation https://github.com/dotnet/arcade/blob/main/Documentation/Maestro/New-Inter-Branch-Merge-Approach.md
One pager: https://github.com/dotnet/dnceng/blob/main/Documentation/OnePagers/github-action-inter-branch-merge.md

### CODE REVIEW

**Review by carlossanlop — APPROVED** [review]

**Review by carlossanlop — APPROVED** [review]

**Comment by carlossanlop** [comment]
Don't we need a similar PR for the release/6.0 branch, @f-alizada @mmitche ?

**Comment by carlossanlop** [comment]
I'll merge this to unblock the branch but please confirm if we need a similar change for 6.0.

**Comment by f-alizada** [comment]
Yes it is needed for 6.0, I'll create the similar PR for workflow
Thank you!

**Comment by f-alizada** [comment]
The PR to onboard the release/6.0 https://github.com/dotnet/runtime/pull/104417

**Pull request merged**
