### PR TITLE
Making the Microsoft.NET.IL.Sdk cross target.

### PR DESCRIPTION
**Pull request by Anipik**
We need this for cross targeting effort in the libraries subset.
I verified this by locally consuming the feed for System.Runtime.CompilerServices.Unsafe src project

### CODE REVIEW

**Comment by ericstj** [comment]
FYI to other reviewers: this enables ILProj to support TargetFrameworks.

**Review by safern — APPROVED** [review]
The build failure is a known AzDo bug. For more info look at: https://github.com/dotnet/runtime/issues/1967#issuecomment-576799054

However, we should retry.

**Review by ericstj — APPROVED** [review]
This looks good to me.  I replicated the same changes in a the SDK and tried a sample ILProj and it worked for me.  Here's what I tried: https://gist.github.com/ericstj/34947f8edd844bc697e718a403a59e4d

**Review by ViktorHofer — APPROVED** [review]
Thanks :)

**Comment by Anipik** [comment]
Merging this one. As the issue is already known and filed. (retry resulted in failure as well.)

**Pull request merged**
