### PR TITLE
Fix crossgen2 calli GC hole by unifying MethodDesc/MethodSignature IsMarshallingRequired logic

### LINKED ISSUE #58259: Assertion failed '!varTypeIsGC(varDsc) in Checked crossgen over Microsoft.Diagnostics.Runtime.dll
Steps to reproduce:
1) Compile Checked runtime
2) Download `Microsoft.Diagnostics.Runtime` nuget package
3) Try to crossgen it:
```
C:\prj\runtime\dotnet.cmd C:\prj\runtime\artifacts\bin\coreclr\windows.x64.Release\crossgen2\crossgen2.dll ^
--out t.t ^
-r C:\prj\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\*.dll ^
Microsoft.Diagnostics.Runtime.dll
```
Observe an assert:
```
C:\prj\runtime\src\coreclr\jit\codegenlinear.cpp:1211
Assertion failed '!varTypeIsGC(varDsc)' in 'Microsoft.Diagnostics.Runtime.DacInterface.MetadataImport:GetGenericParamProps(int,byref,byref,byref):bool:this' during 'Generate code' (IL size 147)
```

Release seems to work fine.

### PR DESCRIPTION
**Pull request by jakobbotsch**
For unmanaged calli crossgen2 was not properly checking all necessary
conditions for a pinvoke being required. In particular it did not check
for managed byrefs. Unify the MethodDesc/MethodSignature logic to get
all the checks.

Fix #58259

cc @dotnet/crossgen-contrib

### CODE REVIEW

**Comment by jakobbotsch** [comment]
This one should probably be backported to 6.0.

**Comment by jakobbotsch** [comment]
Test failure looks like #58481

**Comment by JulieLeeMSFT** [comment]
@davidwrighton and @MichalStrehovsky Please review the code.

**Review by jkotas — APPROVED** [review]

**Review by davidwrighton — APPROVED** [review]
:shipit:

**Review by MichalStrehovsky — APPROVED** [review]

**Pull request merged**
