### PR TITLE
[mono] Set unwind table kind

### PR DESCRIPTION
**Pull request by radekdoulik**
To stop hitting assert in the verbose output, when aot compiler is built with the debug configuration of llvm

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
This appears to be failing on ios-arm64 and tvos-arm64 (it has been rerun multiple times)

**Comment by lambdageek** [comment]
Maybe related https://reviews.llvm.org/D131153

**Comment by radekdoulik** [comment]
@lewing @pavelsavara the threading tests error looks like https://github.com/dotnet/runtime/issues/102762

possibly the unwind info is now different and hopefully contains more information? @pavelsavara could you take a look? https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-107462-merge-cd527723c6d243f5b7/WasmTestOnFirefox-MT-System.Globalization.Calendars.Tests/1/console.14d43601.log?helixlogtype=result

**Comment by radekdoulik** [comment]
Created https://github.com/dotnet/runtime/issues/108394 for the unrelated failure.

**Comment by radekdoulik** [comment]
/ba-g debug tests failures are unrelated and known issue

**Pull request merged**
