### PR TITLE
Try to enable some JIT tests

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Based on the statuses of their linked issues, these tests seem ready to be re-enabled. Let's see if they pass here.

`JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests/` passes locally. I'm afraid I don't have an ARM32 or x86 machine to verify if the other two tests pass locally...

### CODE REVIEW

**Comment by jakobbotsch** [comment]
We should run outerloop here, since this is reenabling some crossgen2 tests that are not normally tested in PRs. I'll kick it off.

**Comment by amanasifkhalid** [comment]
@jakobbotsch I don't see any of the re-enabled tests popping up in the error logs, but maybe I'm looking in the wrong place... Do you know of any current issues that explain the failing pipelines?

Also, I triaged disabled JIT tests associated with issues in dotnet/runtimelab, and all of the issues were still open (many with notes suggesting a fix/workaround isn't planned for now), so I've left them disabled.

**Comment by jakobbotsch** [comment]
The outerloop failure looks like #89545 (I've added a known error to that issue, which makes build analysis able to automatically find it).
The arm build failure looks like #89941 that was recently fixed. I've requested a rerun.

**Review by jakobbotsch — APPROVED** [review]

**Comment by amanasifkhalid** [comment]
Thank you!

**Pull request merged**
