### PR TITLE
Ensure non-shipping symbol packages get indexed

### LINKED ISSUE #41070: NonShipping non-installer packages are not publishing symbols
Any package that's not produced by installer and that is non-shipping won't get symbols indexed. Ignoring VS insertion packages, we have the following:

Libraries:
- `Microsoft.Extensions.HostFactoryResolver.Sources`
- `Microsoft.Private.CoreFx.OOB`
- `System.Utf8String.Experimental`

Runtime:
- `runtime.linux-arm.Microsoft.CrossOsDiag.Private.CoreCLR`
- `runtime.linux-arm64.Microsoft.CrossOsDiag.Private.CoreCLR`
- `runtime.linux-musl-arm64.Microsoft.CrossOsDiag.Private.CoreCLR`
- `runtime.linux-musl-x64.Microsoft.CrossOsDiag.Private.CoreCLR`
- `runtime.linux-x64.Microsoft.CrossOsDiag.Private.CoreCLR`

### PR DESCRIPTION
**Pull request by hoyosjs**
Fixes https://github.com/dotnet/runtime/issues/41070

### CODE REVIEW

**Comment by safern** [comment]
This is the code that assumes that:
https://github.com/dotnet/runtime/blob/ead6ddf4a70f95052522b5744aae5eff76a813f2/src/installer/publish/Directory.Build.targets#L88-L91

I wonder why it assumes them as Shipping when they are blob artifacts. I think we shouldn't need this assumption and just include all symbols.nupkg files found in `DownloadDirectory` into the `SymbolNupkgToPublishFile` item.

**Comment by hoyosjs** [comment]
@safern not really sure why. I had noted that under It goes as far back as repo merging. One thing is if we do that then things will get a lot slower in publishing. We'll try to re-index the same set of assemblies and symbols for all configuration neutral packages.

**Review by safern — APPROVED** [review]
Just one question, thanks for trying the globing.

**Comment by akoeplinger** [comment]
@hoyosjs FYI you don't need to close the backport PR if you push more commits to the source PR. Doing another `/backport` after the commit will push to the same branch and update the backport PR.

**Pull request merged**
