### PR TITLE
[release/7.0][workloads] Bump the runtime net6 versions for GA

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by steveisok** [comment]
Pre-approving for when emsdk comes along.

**Comment by lewing** [comment]
`https://dotnet.github.io/core-eng/helix-workitem-deadletter.txt` :(

**Review by radical — APPROVED** [review]

**Comment by carlossanlop** [comment]
> `https://dotnet.github.io/core-eng/helix-workitem-deadletter.txt` :(

@lewing should we close and reopen?

> Pre-approving for when emsdk comes along.

@steveisok what's the action I should take here? (assuming the deadletter error goes away)

**Comment by steveisok** [comment]
> @steveisok what's the action I should take here? (assuming the deadletter error goes away)

Do we need to wait on emsdk for anything?  I initially thought we did, but I may be mistaken.

**Comment by lewing** [comment]
depends if we want to wait for 6.0.x branding to make a 6.0.11 runtime?

**Comment by carlossanlop** [comment]
> I guess it wouldn't be a bad idea to try to line things up.

Talked with @steveisok about this. We can merge this after October 4, and we will have a window of 6 days to do so:

- November Release 6.0 Branding: October 4 https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/30715/November-2022
- 7.0 GA snap: October 10 https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/26302/NET-7-Schedule

**Comment by lewing** [comment]
blocked on https://github.com/dotnet/runtime/pull/76620 now

**Comment by lewing** [comment]
@marcpopMSFT @mmitche we really need a better way to deal with these version string only dependencies that break so many things

**Comment by carlossanlop** [comment]
> blocked on #76620 now

@lewing I merged the 6.0 branding PR. Do I need to wait for a dependency to be generated or do I just merge this right away?

**Pull request merged**
