### PR TITLE
Backport crossgen2 fix for musl-libc

### LINKED ISSUE #73908: CrossGen2 nupkg on `linux-musl-arm64` / `linux-musl-arm` environment links to wrong libc
### Description

CrossGen2 6.0.8 nupkg links to wrong libc on `linux-musl-arm64` / `linux-musl-arm` environment.

Unfortunately it seems that it wasn't fixed [here](https://github.com/dotnet/runtime/issues/66791), as to this day the error still occurs.

### Reproduction Steps

```shell
$ wget 'https://globalcdn.nuget.org/packages/microsoft.netcore.app.crossgen2.linux-musl-arm64.6.0.8.nupkg'
$ unzip microsoft.netcore.app.crossgen2.linux-musl-arm64.6.0.8.nupkg
$ ldd tools/crossgen2
		/lib/ld-linux-aarch64.so.1 (0xffffb84a3000)
	libpthread.so.0 => /lib/ld-linux-aarch64.so.1 (0xffffb84a3000)
	libdl.so.2 => /lib/ld-linux-aarch64.so.1 (0xffffb84a3000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xffffb8282000)
	libm.so.6 => /lib/ld-linux-aarch64.so.1 (0xffffb84a3000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0xffffb825d000)
	libc.so.6 => /lib/ld-linux-aarch64.so.1 (0xffffb84a3000)
Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by tools/crossgen2)
```

### Expected behavior

Should link to `ld-linux-musl-aarch64.so.1`

### Actual behavior

Rather links to `ld-linux-aarch64.so.1`

### Regression?

I've been keeping track of the fix, waiting for it to eventually apply to the `crossgen2` nuget packages. It never did.

### Known Workarounds

Does not occur when built via source-build on Alpine environment. See package available at via
`https://dl-cdn.alpinelinux.org/alpine/edge/community/arm64/dotnet6-bootstrap-artifacts-6.0.108-r2.apk` (tar package, available at `./usr/lib/dotnet/artifacts/6.0.108/microsoft.netcore.app.crossgen2.linux-musl-arm64.6.0.8.nupkg)

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by am11**
#### Customer Impact

On the operating systems using musl-libc, some of the compiled binaries such as crossgen2 were incorrectly linked with glibc and that forces the consumer to install glibc on those systems (which is unintended as rest of the runtime artifacts are linked to musl-libc). The issue is that we are not taking libc flavor into account when calculating the OS value in 6.0.

#### Testing

This fix is tested on 7.0. This fix was made during the addition of another libc flavor (bionic-libc), in order to diversify the OS calculation. I have done some sanity testing locally, but not the entire platform matrix which uses cross-building. I will wait for the CI results.

 #### Risk

Low. When CI legs are green, that will indicate that the platforms for which we cross-compile and run tests in Helix are largely unaffected. However, we need to make sure that crossgen2 binary is in working condition on those platforms since we are lacking tests for cross-compiled, crossgen2 binary.

Fixes #73908

### CODE REVIEW

**Review by hoyosjs — APPROVED** [review]
Thanks

**Review by mangod9 — APPROVED** [review]

**Comment by akoeplinger** [comment]
cc @carlossanlop

**Comment by hoyosjs** [comment]
This is release/6.0 - we decided this change can wait for the next train.

**Comment by carlossanlop** [comment]
Branding has been completed, so the branch is open again for changes. Merging since it got approved.

**Pull request merged**
