### PR TITLE
Clean up optSetBlockWeights

### PR DESCRIPTION
**Pull request by BruceForstall**
Try to avoid traversing the return block list it it's not necessary.

Add a header comment.

No diffs.

### CODE REVIEW

**Comment by BruceForstall** [comment]
Any throughput improvement is in the measurement noise.

**Comment by BruceForstall** [comment]
It's still not clear *why* the block weights are adjusted as they are; a better comment might elucidate this (any suggestions?).

**Comment by BruceForstall** [comment]
@AndyAyersMS PTAL
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
ping

**Review by AndyAyersMS — APPROVED** [review]
LGTM

**Pull request merged**
