### PR TITLE
Update emsdk manifest dependency name to Microsoft.NET.Workload.Emscr…

### PR DESCRIPTION
**Pull request by radical**
…ipten.Current.Manifest-8.0.100-preview1

.. and updated the version with darc from channel `".NET 8"`.

### CODE REVIEW

**Comment by radical** [comment]
Should this instead go in #80401?

**Review by steveisok — APPROVED** [review]

**Review by lewing — COMMENTED** [review]
you need to update Versions.props with the new property name too

**Comment by steveisok** [comment]
> Should this instead go in #80401?

Yeah, because we can get everything we need in one PR.

**Comment by radical** [comment]
Closing to merge the changes in to #80401 .

**Comment by lewing** [comment]
@marcpopMSFT @dsplaisted this is going to be panful to update

**Comment by marcpopMSFT** [comment]
> @marcpopMSFT @dsplaisted this is going to be painful to update

@lewing what's going to be the painful part and how can we help?

**Comment by lewing** [comment]
@marcpopMSFT that because the preview name is now in the package name we will have to manually update the darc subscription every preview

**Comment by lewing** [comment]
and it looks like the sdk is only looking in its band so it is looking in `alpha` not `preview` which means the new manifests won't get picked up until the sdk updates branding and we we update the darc flow etc.

cc @mmitche

**Comment by radical** [comment]
Closing in favor of https://github.com/dotnet/runtime/pull/80401 .

**Pull request closed without merging**
