### PR TITLE
JIT: Support for devirtualizing array interface methods

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Update JIT and runtime to devirtualize interface calls on arrays over non-shared element types.

Shared types are not (yet) handled.

Add intrinsic and inlining attributes to key methods in the BCL. This allows the JIT to devirtualize and inline enumerator creation and devirtualize and inline all methods that access the enumerator.

And this in turn allows the enumerator to be stack allocated.

However, the enumerator fields are not (yet) physically promoted, because of an optimization in the BCL to return a static empty array enumerator. So the object being accessed later is ambiguous.

Progress towards #62457.

### CODE REVIEW

**Comment by EgorBo** [comment]
@EgorBot
```cs
using BenchmarkDotNet.Attributes;

public class Bench
{
    IList<int> list = new int[10];

    [Benchmark]
    public void Test()
    {
        foreach (var _ in list) {}
    }
}
```

**Comment by AndyAyersMS** [comment]
I wouldn't expect much perf from this PR, unless perhaps the array is in a local (say an arg)... but would expect the enumerator to be on the stack so a bit less allocation.

**Comment by EgorBo** [comment]
> I wouldn't expect much perf from this PR, unless perhaps the array is in a local (say an arg)... but would expect the enumerator to be on the stack so a bit less allocation.
> 
> Ah, forgot that we are also devirtualizing / inlining, so I guess it does help a bit (been focusing on the stack alloc / promotion end of things lately).

well, it does show an improvement https://github.com/EgorBot/runtime-utils/issues/94#issuecomment-2369235103 (forgot to add memory analyzer)

**Comment by AndyAyersMS** [comment]
It's not handling the GDV case right (at least sometimes)... need to dig in a bit more.

**Comment by AndyAyersMS** [comment]
The JIT ends up calling `resolveVirtualMethod` twice (actually 3 times) for a GDV call site:
1. the first one fails, as we can't devirtualize the site without GDV info
2. the second one builds the GDV candidate (we won't do GDV unless we know the info will make the call devirtualize)
3. the third one more or less replays the second one, but also does the transformation of the call. Here we often plug the outputs of (2) as the inputs for (3) and this actually works out ok.

For array interface methods the second call produces outputs that look nothing like the inputs, eg an interface + virtual method is mapped to a concrete class SZArrayHelper and a generic method. So when we get to step (3) we can't just use step (2)'s outputs as the inputs; we need to use the same inputs as step (2). That's more or less what my last commit does.

A separate issue we should look at is why we can't just remember everything from (2) and not reinvoke in (3)... One issue is that (3)'s invocation is done in the middle of `impDevirtualizeCall` which then goes on to do the transformation... if we split off the latter half of this method perhaps we could just reinvoke that part when we get to step (3).

**Comment by AndyAyersMS** [comment]
@MihuBot

**Comment by AndyAyersMS** [comment]
This seems to mostly work, but unfortunately doesn't enable stack allocation. The problem now is that the `GetEnumerator` calls don't appear inlineable, because we're now checking (2)'s inputs instead of (2)'s outputs when we ask if the GDV candidate can be inlined.

**Comment by AndyAyersMS** [comment]
Fix for that is to remember the original context in the GDV info, and use that (plus original method) if we're trying to (re)-devirtualize an array interface call.

With that, we can now (once again) inline `GetEnumerator` and, for non-GDV cases, stack allocate the enumerator object in many cases. We still see the "empty array" path so we can't promote.

For GDV we also see the non-GDV paths lower down, and because of that, we think the array enumerator might escape (escape analysis is flow-insensitive...).

**Comment by AndyAyersMS** [comment]
A bit more on the above.

The path A->B->B1->D->F is infeasible, but escape analysis doesn't know that, so it thinks that the `newobj` enumerator escapes, when in fact it doesn't.

image - 2024-09-25T112702 621

Note the path A->C->D->E is feasible (as is A->B->B2->D->E), so even in the inlined code in E it is unclear which object is being accessed: it could be the newobj, the static, or some other other SZArrayHelperEnumerator returned by the interface call.

Without GDV the path A->C->D is gone, which means the type of `e` is known, which removes the path D->F, but in E there is still ambiguity as to which object is being used (newobj or static).

**Comment by AndyAyersMS** [comment]
@MihuBot

**Comment by AndyAyersMS** [comment]
Something is broken in the host testing, it is trying to add symbolic links and these are failing, eg
```
✘ HostActivation.Tests.SymbolicLinks.Run_apphost_behind_transitive_symlinks(firstSymlinkRelativePath: "a/b/FirstSymlink", secondSymlinkRelativePath: "c/SecondSymlink")​5ms
Error:
System.IO.IOException : Error creating symbolic link at C:\repos\runtime2\artifacts\tests\host\windows.x64.Release\ha\crzkrgns.dvp\symlink\c/SecondSymlink.exe pointing to C:\repos\runtime2\artifacts\tests\host\windows.x64.Release\ha\zo4lgsgj.5fa\HelloWorld\HelloWorld.exe: CreateSymbolicLink failed with error number 1314

Stack trace:
   at Microsoft.DotNet.CoreSetup.Test.SymLink..ctor(String src, String dest) in C:\repos\runtime2\src\installer\tests\TestUtils\SymLink.cs:line 19
   at HostActivation.Tests.SymbolicLinks.Run_apphost_behind_transitive_symlinks(String firstSymlinkRelativePath, String secondSymlinkRelativePath) in C:\repos\runtime2\src\installer\tests\HostActivation.Tests\SymbolicLinks.cs:line 59
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL
cc @dotnet/jit-contrib 

Sample diffs here: https://github.com/MihuBot/runtime-utils/issues/670 (GUID change, so SPMI not useful).

@MichalStrehovsky I haven't done the R2R/NAOT side yet, all that is missing is the ability to get a class handle for the SZGenericArrayEnumerator for a jit-specfied type, so hopefully not too bad to support?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky I haven't done the R2R/NAOT side yet, all that is missing is the ability to get a class handle for the SZGenericArrayEnumerator for a jit-specfied type, so hopefully not too bad to support?

Do we need that? If I mirror the AggressiveInlining change from this PR into native AOT CoreLib, for the following program:

```csharp
class Program
{
    static int Main()
    {
        IEnumerable<int> e = new int[] { 1, 2, 3 };
        int sum = 0;
        foreach (var i in e)
            sum += i;
        return sum;
    }
}
```

I'm getting:

```
; Assembly listing for method Program:Main():int (FullOpts)
; Emitting BLENDED_CODE for generic X64 - Windows
; FullOpts code
; NativeAOT compilation
; optimized code
; rbp based frame
; fully interruptible
; Final local variable assignments
;
;* V00 loc0         [V00    ] (  0,  0   )     ref  ->  zero-ref    class-hnd exact single-def <int[]>
;  V01 loc1         [V01,T01] (  4, 10   )     int  ->  rsi
;  V02 loc2         [V02,T00] (  5, 13   )     ref  ->  [rbp-0x20]  class-hnd EH-live single-def <System.Collections.Generic.IEnumerator`1[int]>
;* V03 loc3         [V03    ] (  0,  0   )     int  ->  zero-ref
;  V04 OutArgs      [V04    ] (  1,  1   )  struct (32) [rsp+0x00]  do-not-enreg[XS] addr-exposed "OutgoingArgSpace"
;  V05 tmp1         [V05,T03] (  3,  6   )     ref  ->  rbx         class-hnd exact single-def "dup spill" <int[]>
;  V06 tmp2         [V06,T04] (  2,  2   )     ref  ->  rdi         class-hnd "Inline return value spill temp" <System.Collections.Generic.IEnumerator`1[int]>
;* V07 tmp3         [V07    ] (  0,  0   )     ref  ->  zero-ref    class-hnd exact single-def "Inline stloc first use temp" <int[]>
;* V08 tmp4         [V08,T05] (  0,  0   )     int  ->  zero-ref    single-def "Inline stloc first use temp"
;  V09 tmp5         [V09,T02] (  4,  8   )     ref  ->  rdi         class-hnd exact single-def "NewObj constructor temp" <System.SZGenericArrayEnumerator`1[int]>
;* V10 tmp6         [V10,T06] (  0,  0   )     int  ->  zero-ref
;* V11 tmp7         [V11    ] (  0,  0   )   ubyte  ->  zero-ref    "Inlining Arg"
;* V12 tmp8         [V12    ] (  0,  0   )   ubyte  ->  zero-ref    "Inlining Arg"
;
; Lcl frame size = 40

G_M24375_IG01:  ;; offset=0x0000
       push     rbp
       push     rdi
       push     rsi
       push     rbx
       sub      rsp, 40
       lea      rbp, [rsp+0x40]
                                                ;; size=13 bbWeight=1 PerfScore 4.75
G_M24375_IG02:  ;; offset=0x000D
       lea      rcx, [(reloc 0x4000000000420a68)]      ; int[]
       mov      edx, 3
       call     CORINFO_HELP_NEWARR_1_VC
       mov      rbx, rax
       lea      rcx, [(reloc 0x4000000000420aa0)]      ; const ptr
       mov      rax, qword ptr [rcx]
       mov      qword ptr [rbx+0x10], rax
       mov      eax, dword ptr [rcx+0x08]
       mov      dword ptr [rbx+0x18], eax
       xor      esi, esi
       lea      rcx, [(reloc 0x4000000000420b88)]      ; System.SZGenericArrayEnumerator`1[int]
       call     CORINFO_HELP_NEWSFAST
       mov      rdi, rax
       mov      rcx, 0x3FFFFFFFF
       mov      qword ptr [rdi+0x08], rcx
       lea      rcx, bword ptr [rdi+0x10]
       mov      rdx, rbx
       call     CORINFO_HELP_ASSIGN_REF
       mov      gword ptr [rbp-0x20], rdi
                                                ;; size=87 bbWeight=1 PerfScore 14.50
G_M24375_IG03:  ;; offset=0x0064
       mov      rcx, rdi
       lea      r10, [(reloc 0x4000000000420ae8)]      ; function address
       call     [r10]System.Collections.IEnumerator:MoveNext():ubyte:this
       test     eax, eax
       je       SHORT G_M24375_IG05
                                                ;; size=17 bbWeight=8 PerfScore 40.00
G_M24375_IG04:  ;; offset=0x0075
       mov      rcx, rdi
       lea      r10, [(reloc 0x4000000000420af8)]      ; function address
       call     [r10]System.Collections.Generic.IEnumerator`1[int]:get_Current():int:this
       add      esi, eax
       jmp      SHORT G_M24375_IG03
                                                ;; size=17 bbWeight=4 PerfScore 24.00
G_M24375_IG05:  ;; offset=0x0086
       mov      rcx, rdi
       lea      r10, [(reloc 0x4000000000420b08)]      ; function address
       call     [r10]System.IDisposable:Dispose():this
       mov      eax, esi
                                                ;; size=15 bbWeight=1 PerfScore 4.00
G_M24375_IG06:  ;; offset=0x0095
       add      rsp, 40
       pop      rbx
       pop      rsi
       pop      rdi
       pop      rbp
       ret
                                                ;; size=9 bbWeight=1 PerfScore 3.25
G_M24375_IG07:  ;; offset=0x009E
       push     rbp
       push     rdi
       push     rsi
       push     rbx
       sub      rsp, 40
                                                ;; size=8 bbWeight=0 PerfScore 0.00
G_M24375_IG08:  ;; offset=0x00A6
       mov      rcx, gword ptr [rbp-0x20]
       lea      r10, [(reloc 0x4000000000420b08)]      ; function address
       call     [r10]System.IDisposable:Dispose():this
       nop
                                                ;; size=15 bbWeight=0 PerfScore 0.00
G_M24375_IG09:  ;; offset=0x00B5
       add      rsp, 40
       pop      rbx
       pop      rsi
       pop      rdi
       pop      rbp
       ret
                                                ;; size=9 bbWeight=0 PerfScore 0.00

; Total bytes of code 190, prolog size 13, PerfScore 90.50, instruction count 60, allocated bytes for code 190 (MethodHash=d9b8a0c8) for method Program:Main():int (FullOpts)
; ============================================================
```

Even without this PR (i.e. this PR doesn't seem to affect what code gets generated on native AOT in any way).

We correctly devirtualized the GetEnumerator call.

The only thing this is missing is RyuJIT seeming to forget we just allocated `SZGenericArrayEnumerator<int>` and insists on still doing interface calls on the enumerator.

I have JitDump here if this is something obvious that could be fixed: 
[dump.txt](https://github.com/user-attachments/files/17160239/dump.txt)

**Comment by AndyAyersMS** [comment]
> The only thing this is missing is RyuJIT seeming to forget we just allocated `SZGenericArrayEnumerator<int>` and insists on still doing interface calls on the enumerator.

Yeah, that's where the new interface method comes in, it lets the JIT determine the return type from `GetEnumerator` early, so that subsequent calls on the enumerator get devirtualized before inlining. Otherwise, the JIT only knows the exact enumerator type after inlining, and by then it is too late to both devirtualize and do more inlining enabled by that devirtualization.

We have ambitions to make inlining a bit more flexible so it can be invoked opportunistically later on, but it is a fair chunk of work.
```
;; ---------------------- Runtime

impDevirtualizeCall: Trying to devirtualize interface call:
    class for 'this' is int[] [exact] (attrib 000c0010)
    base method is System.Collections.Generic.IEnumerable`1[int]::GetEnumerator
--- base class is interface
    devirt to System.SZArrayHelper::GetEnumerator -- exact
               [000003] --CXG------                         *  CALLV stub ref    System.Collections.Generic.IEnumerable`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this
               [000002] --CXG------ this                    \--*  CALL help ref    CORINFO_HELP_NEWARR_1_VC
               [000001] H---------- arg0                       +--*  CNS_INT(h) long   0x7fff25d5e958 class int[]
               [000000] ----------- arg1                       \--*  CNS_INT   long   10
    exact; can devirtualize
... after devirt...
               [000003] --CXG------                         *  CALL      ref    System.SZArrayHelper:GetEnumerator[int]():System.Collections.Generic.IEnumerator`1[int]:this
               [000002] --CXG------ this                    \--*  CALL help ref    CORINFO_HELP_NEWARR_1_VC
               [000001] H---------- arg0                       +--*  CNS_INT(h) long   0x7fff25d5e958 class int[]
               [000000] ----------- arg1                       \--*  CNS_INT   long   10

CheckCanInline: fetching method info for inline candidate GetEnumerator -- context 00007FFF26658C68
Method context: System.SZArrayHelper:GetEnumerator[int]():System.Collections.Generic.IEnumerator`1[int]:this
INLINER: during 'impMarkInlineCandidate' result 'CheckCanInline Success' reason 'CheckCanInline Success' for 'X:Main()' calling 'System.SZArrayHelper:GetEnumerator[int]():System.Collections.Generic.IEnumerator`1[int]:this'
INLINER: during 'impMarkInlineCandidate' result 'CheckCanInline Success' reason 'CheckCanInline Success'
Special intrinsic: looking for exact type returned by System.SZArrayHelper:GetEnumerator[int]():System.Collections.Generic.IEnumerator`1[int]:this
Named Intrinsic System.SZArrayHelper.GetEnumerator: Recognized
Special intrinsic for type System.Int32: return type is System.SZGenericArrayEnumerator`1[int]
Updating method return type to System.SZGenericArrayEnumerator`1[int]

STMT00000 ( 0x000[E-] ... ??? )
               [000003] I-CXG------                         *  CALL      ref    System.SZArrayHelper:GetEnumerator[int]():System.Collections.Generic.IEnumerator`1[int]:this (exactContextHnd=0x00007FFF26658C68)
               [000002] --CXG------ this                    \--*  CALL help ref    CORINFO_HELP_NEWARR_1_VC
               [000001] H---------- arg0                       +--*  CNS_INT(h) long   0x7fff25d5e958 class int[]
               [000000] ----------- arg1                       \--*  CNS_INT   long   10

;; ---------------------- NAOT

impDevirtualizeCall: Trying to devirtualize interface call:
    class for 'this' is int[] [exact] (attrib 000c0010)
    base method is System.Collections.Generic.IEnumerable`1[int]::GetEnumerator
--- base class is interface

    devirt to System.Array`1[int]::GetEnumerator -- exact
               [000017] --C-G------                         *  CALLV stub ref    System.Collections.Generic.IEnumerable`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this
               [000016] ----------- this                    \--*  LCL_VAR   ref    V00 loc0         
    exact; can devirtualize
... after devirt...
               [000017] --C-G------                         *  CALL nullcheck ref    System.Array`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this
               [000016] ----------- this                    \--*  LCL_VAR   ref    V00 loc0         

CheckCanInline: fetching method info for inline candidate GetEnumerator -- context 4000000000420AC9
Class context: System.Array`1[int]
INLINER: during 'impMarkInlineCandidate' result 'CheckCanInline Success' reason 'CheckCanInline Success' for 'Program:Main():int' calling 'System.Array`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this'
INLINER: during 'impMarkInlineCandidate' result 'CheckCanInline Success' reason 'CheckCanInline Success'


STMT00004 ( 0x014[E-] ... ??? )
               [000017] I-C-G------                         *  CALL nullcheck ref    System.Array`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this (exactContextHnd=0x4000000000420AC9)
               [000016] ----------- this                    \--*  LCL_VAR   ref    V00 loc0         
```

It looks like the `SZArrayHelper` stuff got redone for NAOT, so we might want to generalize things a bit.

**Comment by AndyAyersMS** [comment]
With the latest commit the JIT is now asking for the type in the NAOT case:
```
impDevirtualizeCall: Trying to devirtualize interface call:
    class for 'this' is int[] [exact] (attrib 000c0010)
    base method is System.Collections.Generic.IEnumerable`1[int]::GetEnumerator
--- base class is interface
ResolveVirtualMethod (method 40000000004205E8 class 4000000000420630 context 40000000004205F1)
    devirt to System.Array`1[int]::GetEnumerator -- exact
               [000005] --C-G------                         *  CALLV stub ref    System.Collections.Generic.IEnumerable`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this
               [000004] ----------- this                    \--*  LCL_VAR   ref    V00 loc0         
    exact; can devirtualize
... after devirt...
               [000005] --C-G------                         *  CALL nullcheck ref    System.Array`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this
               [000004] ----------- this                    \--*  LCL_VAR   ref    V00 loc0         

CheckCanInline: fetching method info for inline candidate GetEnumerator -- context 4000000000420661
Class context: System.Array`1[int]
INLINER: during 'impMarkInlineCandidate' result 'CheckCanInline Success' reason 'CheckCanInline Success' for 'X:Main():int' calling 'System.Array`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this'
INLINER: during 'impMarkInlineCandidate' result 'CheckCanInline Success' reason 'CheckCanInline Success'
Special intrinsic: looking for exact type returned by System.Array`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this
Named Intrinsic System.Array`1.GetEnumerator: Recognized
Special intrinsic for type System.Int32: type undetermined, so deferring op
```

**Comment by AndyAyersMS** [comment]
This seems to push things a bit farther
```diff
diff --git a/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs b/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs
index e8fa07d0623..5038448f8ca 100644
--- a/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs
+++ b/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs
@@ -1524,9 +1524,13 @@ static CORINFO_RESOLVED_TOKEN CreateResolvedTokenFromMethod(CorInfoImpl jitInter

         private CORINFO_CLASS_STRUCT_* getSZArrayHelperEnumeratorClass(CORINFO_CLASS_STRUCT_* elemType)
         {
-            // TBD
-            _ = HandleToObject(elemType);
-            return null;
+            TypeDesc elementType = HandleToObject(elemType);
+            MetadataType placeholderType = _compilation.TypeSystemContext.SystemModule.GetType("System", "SZGenericArrayEnumerator`1", throwIfNotFound: false);
+            if (placeholderType == null)
+            {
+                return null;
+            }
+            return ObjectToHandle(placeholderType.MakeInstantiatedType(elementType));
         }
```
We now know the type, but it still doesn't lead to devirtualization:
```
impDevirtualizeCall: Trying to devirtualize interface call:
    class for 'this' is int[] [exact] (attrib 000c0010)
    base method is System.Collections.Generic.IEnumerable`1[int]::GetEnumerator
--- base class is interface
ResolveVirtualMethod (method 40000000004205E8 class 4000000000420630 context 40000000004205F1)
    devirt to System.Array`1[int]::GetEnumerator -- exact
               [000005] --C-G------                         *  CALLV stub ref    System.Collections.Generic.IEnumerable`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this
               [000004] ----------- this                    \--*  LCL_VAR   ref    V00 loc0         
    exact; can devirtualize
... after devirt...
               [000005] --C-G------                         *  CALL nullcheck ref    System.Array`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this
               [000004] ----------- this                    \--*  LCL_VAR   ref    V00 loc0         

CheckCanInline: fetching method info for inline candidate GetEnumerator -- context 4000000000420661
Class context: System.Array`1[int]
INLINER: during 'impMarkInlineCandidate' result 'CheckCanInline Success' reason 'CheckCanInline Success' for 'X:Main():int' calling 'System.Array`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this'
INLINER: during 'impMarkInlineCandidate' result 'CheckCanInline Success' reason 'CheckCanInline Success'
Special intrinsic: looking for exact type returned by System.Array`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this
Named Intrinsic System.Array`1.GetEnumerator: Recognized
Special intrinsic for type System.Int32: return type is System.SZGenericArrayEnumerator`1[int]
Updating method return type to System.SZGenericArrayEnumerator`1[int]

...

lvaUpdateClass: Updating class for V01 from (40000000004205E0) System.Collections.Generic.IEnumerator`1[int] to (4000000000420680) System.SZGenericArrayEnumerator`1[int] [exact]


STMT00002 ( 0x008[E-] ... ??? )
               [000007] DAC--------                         *  STORE_LCL_VAR ref    V01 loc1         
               [000006] --C--------                         \--*  RET_EXPR  ref   (for [000005])

impImportBlockPending for BB02

impImportBlockPending for BB06

Importing BB02 (PC=015) of 'X:Main():int'
    [ 0]  15 (0x00f) br.s
impImportBlockPending for BB04

Importing BB04 (PC=024) of 'X:Main():int'
    [ 0]  24 (0x018) ldloc.1
    [ 1]  25 (0x019) callvirt 0A00000E
In Compiler::impImportCall: opcode is callvirt, kind=2, callRetType is ubyte, structSize is 0

impDevirtualizeCall: Trying to devirtualize interface call:
    class for 'this' is System.SZGenericArrayEnumerator`1[int] [exact] (attrib 21000010)
    base method is System.Collections.IEnumerator::MoveNext
--- base class is interface
ResolveVirtualMethod (method 4000000000420600 class 4000000000420680 context 4000000000420609)
--- no derived method: object class cannot be referenced from R2R code due to missing tokens
```

**Comment by AndyAyersMS** [comment]
Seems like if nothing else, adjustments are needed in the various `ResolveVirtualMethod` layers to handle arrays as interfaces, and devirtualization to a generic method.

**Comment by MichalStrehovsky** [comment]
> We now know the type, but it still doesn't lead to devirtualization:

That looks like a separate program. I have a fix in #108379. With that and your CorInfoImpl.cs change, this devirts fine!

> Seems like if nothing else, adjustments are needed in the various `ResolveVirtualMethod` layers to handle arrays as interfaces, and devirtualization to a generic method.

Native AOT fortunately doesn't do the "non-generic interface call leads to a generic method" thing.

**Comment by AndyAyersMS** [comment]
> > We now know the type, but it still doesn't lead to devirtualization:
> 
> That looks like a separate problem. I have a fix in #108379. With that and your CorInfoImpl.cs change, this devirts fine!
> 
> > Seems like if nothing else, adjustments are needed in the various `ResolveVirtualMethod` layers to handle arrays as interfaces, and devirtualization to a generic method.
> 
> Native AOT fortunately doesn't do the "non-generic interface call leads to a generic method" thing.

Nice! Thanks for looking deeper.

**Review by EgorBo — APPROVED** [review]
LGTM! I need the changes to recognize [Intrinsic] after devirtualization too 🙂. Should we run PGO outerloops for it? (and, presumably, NativeAOT outerloop now)

**Comment by EgorBo** [comment]
@EgorBot -intel -arm64 -profiler
```cs
using BenchmarkDotNet.Attributes;

public class Bench
{
    IList<int> list = new int[1024];

    [Benchmark]
    public int Test()
    {
        int sum = 0;
        foreach (var i in list)
            sum += i;
        return sum;
    }
}
```

**Comment by EgorBo** [comment]
@EgorBot -intel
```cs
[MemoryDiagnoser]
public class Bench
{
    IList<int> list = new int[1024];

    [Benchmark]
    public int Test()
    {
        int sum = 0;
        foreach (var i in list)
            sum += i;
        return sum;
    }
}
```

**Comment by EgorBo** [comment]
@EgorBot -intel
```cs
using BenchmarkDotNet.Attributes;

[MemoryDiagnoser]
public class Bench
{
    IList<int> list = new int[1024];

    [Benchmark]
    public int Test()
    {
        int sum = 0;
        foreach (var i in list)
            sum += i;
        return sum;
    }
}
```

**Comment by AndyAyersMS** [comment]
> Is there something that prevents this kicking in for crossgen2? Do we need to set the "is array devirt" in `resolveVirtualMethod` under `#if READYTORUN`?

I haven't debugged it yet, but here's what the jit sees for R2R:
```
impDevirtualizeCall: Trying to devirtualize interface call:
    class for 'this' is int[] [exact] (attrib 000c0010)
    base method is System.Collections.Generic.IEnumerable`1[int]::GetEnumerator
--- base class is interface
ResolveVirtualMethod (method 4000000000420040 class 4000000000420088 context 4000000000420049)
--- no derived method: object class could not be cast to interface class
    Class not final or exact
Considering guarded devirtualization at IL offset 9 (0x9)
Too many exact classes implementing System.Collections.Generic.IEnumerable`1[int] (-1 > 1)
Not guessing; no PGO and no exact classes
INLINER: during 'impMarkInlineCandidate' result 'failed this call site' reason 'target not direct' for 'X:Main():int' calling 'System.Collections.Generic.IEnumerable`1[int]:GetEnumerator():System.Collections.Generic.IEnumerator`1[int]:this'
INLINER: during 'impMarkInlineCandidate' result 'failed this call site' reason 'target not direct
```

**Comment by MichalStrehovsky** [comment]
I see, so it gets rejected during devirtualization. Psychic debugging tells me it's because of this:

https://github.com/dotnet/runtime/blob/e69077783870ffcb9e6ebf7d2d33e919d9e5431b/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCompilerContext.cs#L162-L165

Should be fine then.

**Comment by AndyAyersMS** [comment]
@MichalStrehovsky are you going to sign off? You got added as a reviewer.

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky are you going to sign off? You got added as a reviewer.

Only because of the CorInfoImpl.cs change. That diff LGTM.

**Comment by LoopedBard3** [comment]
Found regressions:
Linux x64: https://github.com/dotnet/perf-autofiling-issues/issues/42759

**Pull request merged**
