### PR TITLE
JIT: make sure to set compLongUsed during struct promotion

### LINKED ISSUE #32059: System.AccessViolationException only in Release x86 in basic console app
We discovered this issue after moving a project in our product from .NET 4.7.1 to .NET Core 3.1. 
We were able to isolate the issue and reproduce it in a standalone console app. 

**The issue only occurs in Release x86.**

Below is the most compact code to reproduce the issue.

```
module Test

type C = 
    | One of System.DateTime * string * string * string * string * string * string * string * string
with
    member x.P (o:string) =
        [|
            match x with
            | One (a, b, c, d, e, f, g, h, i) ->
                ""
                a.ToString()
                o
                b
                c
                d
                e
                f
                g
                h
                i               
        |]

[<EntryPoint>]
let main argv =
    printfn "%O" (C.One(System.DateTime.UtcNow, "", "", "","", "", "", "", "").P "")
    0 // return an integer exit code
```

If you remove any single yield (or multiple yields), the issue does NOT occur. If you replace the DateTime argument with anything else (int, string, Guid), the issue does NOT occur either.

Fsharp version 4.7.0
Dotnet SDK 3.1.100
Dotnet Runtime Microsoft.WindowsDesktop.App 3.1.0

Unmanaged stack

 	```[Inline Frame] clrjit.dll!GenTreeArgList::{ctor}(genTreeOps) Line 2906	C++
 	clrjit.dll!GenTreeFieldList::GenTreeFieldList(GenTree * arg, unsigned int fieldOffset, var_types fieldType, GenTreeFieldList * prevList) Line 2945	C++
 	clrjit.dll!Lowering::LowerArg(GenTreeCall * call, GenTree * * ppArg) Line 1380	C++
 	[Inline Frame] clrjit.dll!Lowering::LowerArgsForCall(GenTreeCall *) Line 1529	C++
 	[Inline Frame] clrjit.dll!Lowering::LowerCall(GenTree *) Line 1569	C++
 	clrjit.dll!Lowering::LowerNode(GenTree * node) Line 168	C++
 	[Inline Frame] clrjit.dll!Lowering::LowerBlock(BasicBlock *) Line 5381	C++
 	clrjit.dll!Lowering::DoPhase() Line 5189	C++
 	clrjit.dll!Phase::Run() Line 33	C++
 	clrjit.dll!Compiler::compCompile(void * * methodCodePtr, unsigned long * methodCodeSize, JitFlags * compileFlags) Line 4799	C++
 	clrjit.dll!Compiler::compCompileHelper(CORINFO_MODULE_STRUCT_ * classPtr, ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, void * * methodCodePtr, unsigned long * methodCodeSize, JitFlags * compileFlags, CorInfoInstantiationVerification) Line 6035	C++
 	clrjit.dll!Compiler::compCompile(CORINFO_METHOD_STRUCT_ * methodHnd, CORINFO_MODULE_STRUCT_ * classPtr, ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, void * * methodCodePtr, unsigned long * methodCodeSize, JitFlags * compileFlags) Line 5367	C++
 	clrjit.dll!jitNativeCode(CORINFO_METHOD_STRUCT_ * methodHnd, CORINFO_MODULE_STRUCT_ * classPtr, ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, void * * methodCodePtr, unsigned long * methodCodeSize, JitFlags * compileFlags, void * inlineInfoPtr) Line 6663	C++
 	clrjit.dll!CILJit::compileMethod(ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, unsigned int flags, unsigned char * * entryAddress, unsigned long * nativeSizeOfCode) Line 319	C++
 	[Managed to Native Transition]```


category:correctness
theme:ir
skill-level:expert
cost:medium

### PR DESCRIPTION
**Pull request by AndyAyersMS**
If we're promoting a long field, make sure `compLongUsed` gets set.
Otherwise we may fail to properly decompose a long later on.

Fixes #32059.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

Not sure this is reachable in C#. I may need to create an IL test case.

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
@AndyAyersMS Looks like this should get fixed in 3.1?

**Comment by AndyAyersMS** [comment]
Yes, we should make a case for fixing this in 3.1.

I think it can be the exact same fix, but haven't looked yet.

**Comment by AndyAyersMS** [comment]
live build failure is unrelated; will ignore.

**Pull request merged**
