### PR TITLE
Optimize flips between 1 and 0

### PR DESCRIPTION
**Pull request by AZero13**
We can solve this with a bit flip rather than + 1 mod 2.

### CODE REVIEW

**Comment by JulieLeeMSFT** [comment]
@kunalspathak PTAL.

**Comment by am11** [comment]
Speaking of 1's complement, `bool M(bool boolean) => !boolean` can use `movzx+not` instead of `xor+test+sete` on xarch.

**Review by kunalspathak — APPROVED** [review]
LGTM

**Pull request merged**
