### PR TITLE
JIT: fix bug in jump threading

### LINKED ISSUE #85892: JIT: Incorrect redundant branch opts example
```csharp
// Generated by Fuzzlyn v1.5 on 2023-05-07 18:03:16
// Run on X64 Windows
// Seed: 7683094625213390431
// Reduced from 235.6 KiB to 1.4 KiB in 00:02:04
// Debug: Prints 0 line(s)
// Release: Prints 1 line(s)
public interface I1
{
}

public interface I2
{
}

public struct S0 : I2
{
    public ushort F0;
    public short F1;
    public uint F2;
    public uint F3;
    public S0(ushort f0, short f1, uint f2, uint f3): this()
    {
        F0 = f0;
        F1 = f1;
        F2 = f2;
        F3 = f3;
    }
}

public class C0 : I1
{
    public short F0;
}

public class Program
{
    public static I1[] s_17 = new I1[]{new C0()};
    public static long[] s_107;
    public static void Main()
    {
        bool vr2 = default(bool);
        long vr3 = 1234;
        bool vr4 = !!M51();
        if (vr4)
        {
            try
            {
                System.Console.WriteLine(12);
            }
            finally
            {
                var vr5 = new S0(0, 0, 0, 0);
                M58(vr5, new S0(0, 0, 0, 0));
            }

            if (!vr4)
            {
                System.Console.WriteLine(34);
            }
        }

        if (vr4)
        {
            s_107 = s_107;
        }

        if (vr4)
        {
            var vr6 = new C0();
            System.Console.WriteLine(5678);
        }
    }

    public static void M57(ref I1 arg2)
    {
    }

    public static void M58(S0 argThis, I2 arg2)
    {
    }

    public static bool M51()
    {
        bool var27 = default(bool);
        M57(ref s_17[0]);
        return var27;
    }
}
```

Does not repro with `DOTNET_JitDoRedundantBranchOpts=0`. cc @AndyAyersMS

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Verify that the purported dominator of a block to be jump threaded dominates all of the block's predecessors.

This will initially be true (modulo some odd cases with finally continuations), but if we've jump threaded through the dominator it may not remain true as we do not update dominators when optimizing.

Fixes #85892.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

7 or so methods with diffs. Did not check to see if any of them actually were creating bad code.

**Comment by AndyAyersMS** [comment]
You might wonder how a fix for a possibly incorrect dominator is to make even more dominance queries. So this may not a final or complete fix. 

I will keep thinking about what sorts of data we can actually trust....

**Review by jakobbotsch — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Fuzzlyn failures seem unrelated.
```
// Assertion failed 'inVarToRegMap[varIndex] == REG_STK' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'LSRA allocate' (IL size 135; hash 0xade6b36b; FullOpts)

```

**Pull request merged**
