### PR TITLE
[mono][ios] Call mono_gc_init_finalizer_thread to allow gc thread creation

### LINKED ISSUE #90012: [mono][ios] Eventpipe gcdump test failing on apple mobile platforms
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=363106
Build error leg or test failing: tracing/eventpipe/gcdump.dll
Pull request: https://github.com/dotnet/runtime/pull/89726

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Application has finished with exit code 255 but 100 was expected",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Test log:
```
[03:12:26.0256760] Launched application 'net.dot.tracing_eventpipe' on 'DNCENGOSX117' with pid 14378
[03:12:26.1444880] 2023-08-04 03:12:26.185 tracing_eventpipe[14378:13727264]   0.0s: ==TEST STARTING==
[03:12:26.1548200] 2023-08-04 03:12:26.198 tracing_eventpipe[14378:13727274]   0.0s: Started sending sentinel events...
[03:12:26.1581380] 2023-08-04 03:12:26.201 tracing_eventpipe[14378:13727276]   0.0s: Connecting to EventPipe...
[03:12:26.2010550] 2023-08-04 03:12:26.244 tracing_eventpipe[14378:13727276]   0.1s: Creating EventPipeEventSource...
[03:12:26.2053600] 2023-08-04 03:12:26.248 tracing_eventpipe[14378:13727276]   0.1s: EventPipeEventSource created
[03:12:26.2137250] 2023-08-04 03:12:26.257 tracing_eventpipe[14378:13727276]   0.1s: Dynamic.All callback registered
[03:12:26.2137700] 2023-08-04 03:12:26.257 tracing_eventpipe[14378:13727276]   0.1s: Running optional trace validator
[03:12:26.2221300] 2023-08-04 03:12:26.264 tracing_eventpipe[14378:13727276]   0.1s: Finished running optional trace validator
[03:12:26.2221690] 2023-08-04 03:12:26.265 tracing_eventpipe[14378:13727276]   0.1s: Starting stream processing...
[03:12:26.3359410] 2023-08-04 03:12:26.379 tracing_eventpipe[14378:13727276]   0.2s: Saw sentinel event
[03:12:26.3359870] 2023-08-04 03:12:26.379 tracing_eventpipe[14378:13727274]   0.2s: Stopped sending sentinel events
[03:12:26.3371410] 2023-08-04 03:12:26.380 tracing_eventpipe[14378:13727264]   0.2s: Starting event generating action...
[03:12:36.3443740] 2023-08-04 03:12:36.387 tracing_eventpipe[14378:13727264]  10.2s: Stopping event generating action
[03:12:36.3456970] 2023-08-04 03:12:36.389 tracing_eventpipe[14378:13727274]  10.2s: Sending StopTracing command...
[03:12:36.4805540] 2023-08-04 03:12:36.524 tracing_eventpipe[14378:13727276]  10.4s: Saw new provider 'Microsoft-DotNETCore-EventPipe'
[03:12:36.4967410] 2023-08-04 03:12:36.540 tracing_eventpipe[14378:13727276]  10.4s: Saw new provider 'Microsoft-Windows-DotNETRuntimeRundown'
[03:12:36.5134950] 2023-08-04 03:12:36.557 tracing_eventpipe[14378:13727274]  10.4s: Finished StopTracing command
[03:12:36.5411160] 2023-08-04 03:12:36.584 tracing_eventpipe[14378:13727276]  10.4s: Stopping stream processing
[03:12:36.5412890] 2023-08-04 03:12:36.585 tracing_eventpipe[14378:13727276]  10.4s: Dropped 0 events
[03:12:36.5414080] 2023-08-04 03:12:36.585 tracing_eventpipe[14378:13727264]  10.4s: Reader task finished
[03:12:36.5415490] 2023-08-04 03:12:36.585 tracing_eventpipe[14378:13727264]  10.4s: Validating optional callback...
[03:12:36.5416170] 2023-08-04 03:12:36.585 tracing_eventpipe[14378:13727264] Test failed due to missing GC heap events.
[03:12:36.5417250] 2023-08-04 03:12:36.585 tracing_eventpipe[14378:13727264] _seenGCStart =            False
[03:12:36.5417550] 2023-08-04 03:12:36.586 tracing_eventpipe[14378:13727264] _seenGCStop =             False
[03:12:36.5417610] 2023-08-04 03:12:36.586 tracing_eventpipe[14378:13727264] _bulkTypeCount =          0
[03:12:36.5419840] 2023-08-04 03:12:36.586 tracing_eventpipe[14378:13727264] _bulkNodeCount =          0
[03:12:36.5420020] 2023-08-04 03:12:36.586 tracing_eventpipe[14378:13727264] _bulkEdgeCount =          0
[03:12:36.5420080] 2023-08-04 03:12:36.586 tracing_eventpipe[14378:13727264] _bulkRootEdgeCount =      0
[03:12:36.5420130] 2023-08-04 03:12:36.586 tracing_eventpipe[14378:13727264] _bulkRootStaticVarCount = 0
[03:12:36.5420220] 2023-08-04 03:12:36.586 tracing_eventpipe[14378:13727264]  10.4s: ==TEST FINISHED: FAILED!==
[03:12:36.5473960] Xamarin.Hosting: Process '14378' exited with exit code 255 or crashing signal .
[03:12:36.5478560] Application 'net.dot.tracing_eventpipe' terminated (with exit code '255' and/or crashing signal ').
```

## Repro steps

1. Build the runtime
```
./build.sh -ci -arch x64 -os tvossimulator  -s mono+libs -c Release
```
2. Build and AOT compile the tests
```
./src/tests/build.sh  ci os tvossimulator x64 Release -mono tree tracing/eventpipe /p:ArchiveTests=true /p:DevTeamProvisioning=- /p:RunAOTCompilation=true /p:MonoForceInterpreter=true /p:LibrariesConfiguration=Release
```
3. Run the app bundle using Xcode using the following environment variables
```
MONO_APPLE_APP_ENTRY_POINT_LIB_NAME = 'testdir-gcdump/gcdump.dll'
MONO_APPLE_APP_ASSEMBLY_LOAD_PREFIX = 'testdir-gcdump'
```

Note: You may need to provide a correct path to the cross compiler in the AppleBuild.targets.

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=363106
**Error message validated:** `Application has finished with exit code 255 but 100 was expected`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/4/2023 11:24:17 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by kotlarmilos**
This PR modifies the `runtime.m` Apple template to call the `mono_gc_init_finalizer_thread`. This function enables the creation of the finalizer thread. If the runtime is compiled with the lazy gc thread creation flag, embedders must call this function to initiate the finalizer. Otherwise, the function does nothing and the runtime creates the finalizer thread automatically.

Fixes https://github.com/dotnet/runtime/issues/90012

### CODE REVIEW

**Review by lateralusX — APPROVED** [review]
LGTM! Please verify that the GC dump tests now runs on iOS/tvOS devices on CI.

**Review by ivanpovazan — APPROVED** [review]
Looks good!

**Review by akoeplinger — APPROVED** [review]

**Comment by kotlarmilos** [comment]
The test has executed successfully https://helix.dot.net/api/jobs/831b21f1-4098-4f60-a174-033d11d5c3cf/workitems/tracing_eventpipe?api-version=2019-06-17.

**Pull request merged**
