### PR TITLE
Remove unused suppressions for System.Linq.Expressions

### LINKED ISSUE #89206: Unnecessary suppression errors showing up in build using .NET 8 Preview 7 SDK
When attempting to build the runtime repo with the latest build of .NET 8 Preview 7 SDK, it produces the following errors:

### CoreCLR

```
/vmr/src/runtime/artifacts/source-build/self/package-cache/microsoft.dotnet.apicompat.task/8.0.100-preview.7.23364.43/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets(16,5): error : Unnecessary suppressions found. The APICompat suppression file can be updated by rebuilding with '/p:ApiCompatGenerateSuppressionFile=true' [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
/vmr/src/runtime/artifacts/source-build/self/package-cache/microsoft.dotnet.apicompat.task/8.0.100-preview.7.23364.43/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets(16,5): error : CP0001 (Target: 'T:System.Diagnostics.DebuggerGuidedStepThroughAttribute') [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
/vmr/src/runtime/artifacts/source-build/self/package-cache/microsoft.dotnet.apicompat.task/8.0.100-preview.7.23364.43/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets(16,5): error : CP0001 (Target: 'T:System.Runtime.CompilerServices.EagerStaticClassConstructionAttribute') [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
/vmr/src/runtime/artifacts/source-build/self/package-cache/microsoft.dotnet.apicompat.task/8.0.100-preview.7.23364.43/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets(16,5): error : CP0016 (Target: 'M:System.Runtime.InteropServices.Marshal.GetObjectForNativeVariant``1(System.IntPtr)->T?:[T:System.Diagnostics.CodeAnalysis.MaybeNullAttribute]') [/vmr/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
```

### Libraries

```
/vmr/src/runtime/artifacts/source-build/self/package-cache/microsoft.dotnet.apicompat.task/8.0.100-preview.7.23364.43/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets(16,5): error : Unnecessary suppressions found. The APICompat suppression file can be updated by rebuilding with '/p:ApiCompatGenerateSuppressionFile=true' [/vmr/src/runtime/artifacts/source-build/self/src/src/libraries/System.Runtime.InteropServices.JavaScript/src/System.Runtime.InteropServices.JavaScript.csproj]
/vmr/src/runtime/artifacts/source-build/self/package-cache/microsoft.dotnet.apicompat.task/8.0.100-preview.7.23364.43/build/Microsoft.DotNet.ApiCompat.ValidateAssemblies.Common.targets(16,5): error : CP0001 (Target: 'T:System.Runtime.InteropServices.JavaScript.WebWorker', Left: 'ref/net8.0/System.Runtime.InteropServices.JavaScript.dll', Right: 'runtimes/browser/lib/net8.0/System.Runtime.InteropServices.JavaScript.dll') [/vmr/src/runtime/artifacts/source-build/self/src/src/libraries/System.Runtime.InteropServices.JavaScript/src/System.Runtime.InteropServices.JavaScript.csproj]
```

These suppressions only seem to be relevant to Windows. So there needs to be a way to exclude these suppressions for Linux but include them for Windows.

### PR DESCRIPTION
**Pull request by ericstj**
fixes #89206

### CODE REVIEW

**Review by mthalman — APPROVED** [review]

**Review by carlossanlop — APPROVED** [review]
Approving to unblock.

Two questions for my own education:
- What specific change in PR https://github.com/dotnet/runtime/pull/88723/files caused the suppresion errors to start showing up and why?
- Why didn't the CI in that PR show the errors? https://github.com/dotnet/runtime/pull/88723/checks?check_run_id=15146702721

**Comment by mthalman** [comment]
> Approving to unblock.
> 
> Two questions for my own education:
> 
> * What specific change in PR https://github.com/dotnet/runtime/pull/88723/files caused the suppresion errors to start showing up and why?
> * Why didn't the CI in that PR show the errors? https://github.com/dotnet/runtime/pull/88723/checks?check_run_id=15146702721

The error only shows up when using the 8.0 Preview 7 SDK to build. This repo isn't using that.

**Comment by ericstj** [comment]
Correct, we cannot use the Preview7 SDK yet because it is not done.  We cannot use the nightly build of APICompat because it depends on preview7 API that was added to runtime.  So we're in a situation for a few weeks where we'll not have protection for these.

@mthalman another option here would be to just disable the consistency check until we can turn it on in dotnet/runtime.  To do that you can set `ApiCompatPermitUnnecessarySuppressions` to true.

**Review by ivanpovazan — APPROVED** [review]

**Comment by ivanpovazan** [comment]
Regarding:

> * What specific change in PR https://github.com/dotnet/runtime/pull/88723/files caused the suppresion errors to start showing up and why?

Before the change, we were building/shipping `System.Linq.Expressions.dll` differently for iOS-like platforms (ios/tvos/maccatalyst) so the suppressions were put into place to accomodate this (note the extra entries which had platform name in the paths in `Right` element)

> * Why didn't the CI in that PR show the errors? https://github.com/dotnet/runtime/pull/88723/checks?check_run_id=15146702721

I had the same question, so thanks @mthalman @ericstj for the clarification in your comments. 
If I understand correctly, I should have had built the runtime with `/p:ApiCompatGenerateSuppressionFile=true` to update the suppressions and made it part of my PR.

**Comment by ericstj** [comment]
> I should have had built the runtime with `/p:ApiCompatGenerateSuppressionFile=true`

You could have, but I honestly wouldn't expect you to realize that.  Once we can update to the Preview7 SDK it will be obvious, and hopefully the steps you need to take will be apparent in the error message.

Also - you don't need to do it for the whole repo - you could simply do this when building a single src csproj.

**Pull request merged**
