### PR TITLE
[QUIC] Updated MsQuic version

### PR DESCRIPTION
**Pull request by ManickaP**
cc @carlossanlop

### CODE REVIEW

**Review by CarnaViire — APPROVED** [review]

**Review by carlossanlop — APPROVED** [review]
Nice, thanks.

**Comment by EgorBo** [comment]
Hm.. local build fails for me with this:
```
  Restored C:\prj\runtime\src\tasks\MonoTargetsTasks\MonoTargetsTasks.csproj (in 1.52 sec).
C:\prj\runtime\src\libraries\System.Net.Quic\src\System.Net.Quic.csproj : error NU1604: Warning As Error: Project depen
dency Microsoft.Native.Quic.MsQuic.Schannel does not contain an inclusive lower bound. Include a lower bound in the dep
endency version to ensure consistent restore results. [C:\prj\runtime\Build.proj]
  Failed to restore C:\prj\runtime\src\libraries\System.Net.Quic\src\System.Net.Quic.csproj (in 2.83 sec).
```

**Comment by jakobbotsch** [comment]
I see the same. Bad interaction between this and #99713?

**Comment by CarnaViire** [comment]
cc @carlossanlop fyi

**Comment by ManickaP** [comment]
I'm working on a fix.

**Comment by ManickaP** [comment]
Fix in #99756

**Comment by CarnaViire** [comment]
@EgorBo @jakobbotsch fix merged

**Pull request merged**
