### PR TITLE
[RISC-V] Enable R2RDump

### PR DESCRIPTION
**Pull request by tomeksowi**
Part of #84834
cc @wscho77 @HJLeee @clamp03 @JongHeonChoi @t-mustafin @gbalykov @viewizard @ashaurtaev @brucehoult @sirntar @yurai007 @bajtazar

Note: needs dotnet/jitutils#387 for R2RDump --disasm to work.

### CODE REVIEW

**Review by sirntar — APPROVED** [review]
LGTM

**Review by wscho77 — APPROVED** [review]
LGTM

**Review by clamp03 — APPROVED** [review]

**Review by gbalykov — APPROVED** [review]

**Review by Bajtazar — APPROVED** [review]

**Comment by tomeksowi** [comment]
@trylek could you review this please? (the CI failures look unrelated to this PR)

**Review by ashaurtaev — APPROVED** [review]

**Review by jkotas — APPROVED** [review]
Thanks

**Pull request merged**
