### PR TITLE
Fixes issue when monitoring a process launched via the same command line

### PR DESCRIPTION
**Pull request by dramos020**
Fixes https://github.com/dotnet/diagnostics/issues/3366. A NullReferenceException was being thrown and caught because the CommandHandler in MetricsEventSource was being referenced before being initialized. Now custom metrics are displayed when trying to monitor a process in the same command line. Here is example output for a simple application with a custom meter that displays random values:

- Running ```  dotnet-counters monitor --counters System.Runtime,demo_meter -- countersbug.exe ``` will now output:
  
  ```
  Press p to pause, r to resume, q to quit.
      Status: Running
  
  [System.Runtime]
      % Time in GC since last GC (%)                                 0
      Allocation Rate (B / 1 sec)                               16,072
      CPU Usage (%)                                                  0
      Exception Count (Count / 1 sec)                                0
      GC Committed Bytes (MB)                                        0
      GC Fragmentation (%)                                           0
      GC Heap Size (MB)                                              0.462
      Gen 0 GC Count (Count / 1 sec)                                 0
      Gen 0 Size (B)                                                 0
      Gen 1 GC Count (Count / 1 sec)                                 0
      Gen 1 Size (B)                                                 0
      Gen 2 GC Count (Count / 1 sec)                                 0
      Gen 2 Size (B)                                                 0
      IL Bytes Jitted (B)                                       47,239
      LOH Size (B)                                                   0
      Monitor Lock Contention Count (Count / 1 sec)                  0
      Number of Active Timers                                        0
      Number of Assemblies Loaded                                   13
      Number of Methods Jitted                                     438
      POH (Pinned Object Heap) Size (B)                              0
      ThreadPool Completed Work Item Count (Count / 1 sec)           0
      ThreadPool Queue Length                                        0
      ThreadPool Thread Count                                        0
      Time spent in JIT (ms / 1 sec)                                10.01
      Working Set (MB)                                              25.793
  [demo_meter]
      random (Count / 1 sec)
          instance=app                                            -793.95
  ```

- Running ```  dotnet-counters monitor --counters demo_meter -- countersbug.exe ``` will now output:
  ```
  Press p to pause, r to resume, q to quit.
      Status: Running
  
  [demo_meter]
      random (Count / 1 sec)
          instance=app                                 799.513
  ```

### CODE REVIEW

**Comment by noahfalk** [comment]
Can you include the callstack where the NullReferenceException occurs? A lot of the changes were swapping the Log property to a local parent field so does that also mean the static Log property was not initialized at that point? I want to understand what constraints we are working within :)

**Comment by davmason** [comment]
@noahfalk we're trying to grab the original exception but running in to technical difficulties.

The reason it fails is if you start a session before the runtime starts, you see the following scenario
* MetricsEventSource static construct runs to initialize the Log object
* It calls the base EventSource constructor, which sees a session is open and calls the OnEventCommand for MetricsEventSource
* Now we are calling in to MetricsEventSource before the static constructor has fully run and Log is assigned to so any call to Log will have a null reference

**Comment by noahfalk** [comment]
Got it. What if we did something like this?

1. When MetricsEventSource needs to access the command handler it can use a property and implement the property like this:

```C#

private CommandHandler Handler {
    get {
        if(_handler == null) {
            Interlocked.CompareExchange(ref _handler, new CommandHandler(this), null);
        }
        return handler;
    }
```

2. When CommandHandler needs to access the MetricsEventSource it can do that through a property that was initialized in the CommandHandler constructor:

```C#
public CommandHandler(MetricsEventSource parent) {
    Parent = parent;
}
public MetricsEventSource Parent { get; }

// some code that needs to use parent
Parent.Error("Something bad happened");
```

**Comment by davmason** [comment]
Works for me

**Comment by dramos020** [comment]
Just made the changes that were suggested.

**Review by davmason — APPROVED** [review]
LGTM

**Pull request merged**
