### PR TITLE
Fix netfx build for S.S.C.Xml nuget package

### LINKED ISSUE #78652: TypeLoadException in System.Security.Cryptography.Xml v7.0.0.0 for EncryptedData in .NET 4.8 project referencing .NET Standard 2.0 library
### Description

Upgraded System.Security.Cryptography.Xml v5.0.0 to v7.0.0 in a .NET 4.8 project, and now when I try to access the `EncryptedData` class, I get the following error:
```
System.TypeLoadException: Could not load type 'System.Security.Cryptography.Xml.EncryptedData' from assembly 'System.Security.Cryptography.Xml, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```
[Issue_System.Security.Cryptography.Xml.zip](https://github.com/dotnet/runtime/files/10060096/Issue_System.Security.Cryptography.Xml.zip)

### Reproduction Steps

* Open Visual Studio 2022
* Create a .NET 4.8 console app.
* Add a .NET Standard 2.0 class library
* In the library:
  * Reference the `System.Security.Cryptography.Xml` NuGet package v7.0.0.0 (this also occurs in 6.0.0.1, FWIW).
  * Create a public class with a single method.
  * In the method, new up an instance of `EncryptedData`
* In the console app:
  * Ensure the `<RestoreProjectStyle>PackageReference</RestoreProjectStyle>` line is added to the .csproj file so you don't have to reference the NuGet package explicitly here.
  * Reference the class library, above.
  * In Main, new up an instance of the test class, above, and attempt to invoke the single method.

### Expected behavior

Should not throw. 

### Actual behavior

I get the error mentioned in the description, above.
image

### Regression?

This works fine when using System.Security.Encryption.Xml v6.0.1 or lower.  As soon as you update to v7.0.0, BLAM.  

### Known Workarounds

Use v6.0.1 for now.  The vulnerability appears to have been patched, but you don't get the v7.0.0 benefits (if there are any).  

### Configuration

* Console app is running on .NET 4.8
* Class library referencing the package is against .NET Standard 2.0
* Windows 10 Enterprise Version 21H2 (OS Build 19044.2251)
* Architecture is x64
* This has been reproduced on 2 separate machines running (roughly) the same configuration. 

### Other information

When looking at the .dll file using ILSpy or dotPeek, the EncryptedData class does not seem to be there at all.

### PR DESCRIPTION
**Pull request by bartonjs**
Fixes #78652.

Manually verified that the net462/ref.dll and net462/lib.dll were missing the typefowards before, and they're present after.

### CODE REVIEW

**Review by adamsitnik — APPROVED** [review]
The change LGTM, but there is one more project file that has the same bug:

https://github.com/dotnet/runtime/blob/dd0ec9471dde6b6740ae6d9b504b64dec190b438/src/libraries/System.Threading.AccessControl/ref/System.Threading.AccessControl.csproj#L9

@bartonjs would you mind fixing it in this PR as well?

**Review by carlossanlop — APPROVED** [review]

**Comment by carlossanlop** [comment]
@ViktorHofer is there a way to be notified via a build failure when there's a typo like this?

**Review by ViktorHofer — APPROVED** [review]
Thanks for fixing this, @bartonjs

**Comment by ViktorHofer** [comment]
APICompat doesn't catch this because the type forwards don't exist on netstandard2.0. Baseline validation that compares ref/net462 or lib/net462 from the previous package with the live built one could theoretically catch this. That said, we don't have such a feature in ApiCompat today.

I'm a bit surprised that our .NET Framework tests didn't catch this. It looks like the tests don't bind against the package asset and instead directly on the .NET Framework runtime library. That alone is a terrible indicator that we might not be testing our actually .NET Framework shipping assets and that would raise the question why we then even run those tests.

**Comment by bartonjs** [comment]
> that would raise the question why we then even run those tests.

For cryptoxml, to ensure that any changes we do take are still compatible with netfx, because it's effectively a serialization library and needs that level of fidelity.

But, yes, it would be better if the tests (or APICompat/etc) could guard us from this, too.

**Pull request merged**
