### PR TITLE
73150 enable CborDocument_Roundtrip test

### PR DESCRIPTION
**Pull request by mkhamoyan**

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
LGTM if CI is happy with it.

**Comment by akoeplinger** [comment]
@mkhamoyan this still seems to fail the `System.Formats.Cbor.Tests` test suite on iOS (the build is gone so can't look at details), should we close this and investigate #73150 since it seems to still be an issue?

**Comment by mkhamoyan** [comment]
> @mkhamoyan this still seems to fail the `System.Formats.Cbor.Tests` test suite on iOS (the build is gone so can't look at details), should we close this and investigate #73150 since it seems to still be an issue?

yes, I will close this.

**Pull request closed without merging**
