### PR TITLE
[release/7.0-rc1] Revert "[MONO] Move marshal-ilgen into a component (#71203)"

### PR DESCRIPTION
**Pull request by lambdageek**
This reverts commit de32c4466489090fdd41574d1be2945fd03ab7f2.

### CODE REVIEW

**Comment by lambdageek** [comment]
The corresponding revert for `main` is https://github.com/dotnet/runtime/pull/74674

**Comment by lewing** [comment]
is this going to break any of the static web assets in the sdk?  someone will need to keep an eye on that if this flows

**Review by lewing — APPROVED** [review]
lgtm if it is green

**Comment by lambdageek** [comment]
> is this going to break any of the static web assets in the sdk? someone will need to keep an eye on that if this flows

I don't see any mention of marshal-ilgen (or marshal_ilgen) elsewhere in the dotnet org (and in particular not in dotnet/sdk) so I think... probably not?  

https://cs.github.com/?scopeName=All+repos&scope=&q=org%3Adotnet+%28marshal-ilgen+OR+marshal_ilgen%29

the componentization stuff produces only .a files for wasm.  so they wouldn't show up in, for example, blazor's app bundle tests

**Review by naricc — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by carlossanlop** [comment]
CI is green. Ready to merge.

**Pull request merged**
