### PR TITLE
JIT: fix jitstress/gcstress issue with return value liveness

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The jit was not extending return value liveness properly for methods that
returned a ref-wrapped struct, if jitstress caused code to be added between
the final body statement and the epilog (eg a profile leave hook).

Fixes many of the cases in #1971.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]
Would it be worthwhile checking asm diffs (e.g., SPMI diffs)?

**Comment by AndyAyersMS** [comment]
> Would it be worthwhile checking asm diffs (e.g., SPMI diffs)?

Sure, I can do that. Should be no codegen changes.

Is there some kind of gcinfo diff capability in SPMI? These changes should only impact GC info and only for methods that both return a pointer-sized gc struct and have a normal return exit profile hook (or normal return cookie check).

**Comment by BruceForstall** [comment]
> Is there some kind of gcinfo diff capability in SPMI?

It already kicks out a diff if there is a GC info diff.

Looks like superpmi.py doesn't have an option to generate GC info into the generated asm (our Desktop scripting had this). I opened https://github.com/dotnet/runtime/issues/2058 to add it, but you can temporarily hack superpmi.py to set this if needed.

**Comment by AndyAyersMS** [comment]
No SPMI diffs from the test mch:
```
Loaded 485845  Jitted 485845  FailedCompile 78 Excluded 0 Diffs 0
...
Elapsed time: 0:30:04.039052
```
All the failures were `GetLazyStringLiteralHelper` cases.

SPMI is not much faster for me locally than what is likely the equivalent amount of methods via PMI (haven't tried over the full test set, but the FX set jits 200K+ methods in about 15 minutes). Still seeing the "8" slice take quite a bit longer than the rest.

**Pull request merged**
