### PR TITLE
Update Mariner 2.0 to Azure Linux 3.0

### PR DESCRIPTION
**Pull request by richlander**
We are moving to Azure Linux 3.0 for both .NET 8 and 9 builds. This PR is the first stage of that.

Phases:

- Produce `net8.0` Azure Linux 3.0 images.
- Apply these images to `main` to validate quality.
- Produce `net9.0` images.
- Replace `net8.0` with `net9.0` in `main`. Again, validate quality.
- Wait for Azure Linux 3.0 to ship.
- Apply `net8.0` images to `release/net8.0` branch.

Context:

- We decided to have two image variants, differing by toolset versions.
- We started with `net8.0` since Clang 16 was easier. We're having some difficulty with creating an image with Clang 18 (for the `net9.0` images).
- We are staying with Ubuntu 16.04 and Alpine 3.13 as the target Linux versions. No plans to change that.
- We don't yet have `azurelinux` variants that match all the existing `cbl-mariner` images.

Related:

- https://github.com/dotnet/runtime/issues/91826
- https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/995
- https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/996
- https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/997

### CODE REVIEW

**Comment by richlander** [comment]
@sbomer is working on https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1003

**Comment by richlander** [comment]
New images have been published.

**Review by sbomer — APPROVED** [review]

**Comment by richlander** [comment]
Who else should look at this or is this good to go?

**Comment by richlander** [comment]
FYI: @agocke @hoyosjs @jkoritzinsky @jkotas

**Comment by richlander** [comment]
Note: Several Mariner images were skipped because we don't have Azure Linux versions of those yet. That's OK. We're (naturally) using a progressive process here. It will take several steps (including Helix images) to get across the goal line.

**Review by hoyosjs — APPROVED** [review]

**Pull request merged**
