### PR TITLE
DbDataReaderEnumerator with MoveNextAsync

### PR DESCRIPTION
**Pull request by wessleym**
Similar to DbDataReader, this new DbDataReaderEnumerator implements IEnumerator<DbDataRecord> and IAsyncEnumerator<DbDataRecord> and thus allows for MoveNextAsync along with MoveNext.

### CODE REVIEW

**Comment by wessleym** [comment]
@dotnet-policy-service agree

**Comment by huoyaoyuan** [comment]
Thank you for your interest of contribution. Adding new API like methods require going through [API review process](https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md). Pull requests should not be opened before the API get discussed.

**Comment by wessleym** [comment]
@huoyaoyuan, I apologize.
https://github.com/dotnet/runtime/issues/98890
As I said in my above issue, this class does not seem to be me to be a new API. It's just a new class within a larger API. But it's not clear to me what qualifies a change as being a new API.
Would you prefer I close this pull request? I am happy to do so.

**Comment by huoyaoyuan** [comment]
> But it's not clear to me what qualifies a change as being a new API.

Anything new accessible from user code is new API, including `public` things and `protected` members on `public` types.

Once added and shipped in stable version, they can't be removed ever. (Although we still ultimately reserve the right.) Thus, every addition needs approval.

**Comment by wessleym** [comment]
@huoyaoyuan, I accept what you're saying, and if you'd rather I close this, I will. Would you please me proceed with closing?
(Please note that the contribution guidelines say, "If your change adds a new API, follow the [API Review Process](https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md)." In other programming spheres of which I'm aware, a single class wouldn't qualify as a whole new API--more like new API _functionality_. So that's where my confusion arose.)

**Comment by stephentoub** [comment]
@wessleym, thanks for your interest in contributing; and yes, please close it... you're welcome to reopen if/when the API proposal is accepted. We define new APIs as _any_ change that would show up in a reference assembly, including adding a single public method, a single new class, implementing an additional public interface on an existing class, etc.

**Comment by wessleym** [comment]
@stephentoub and @huoyaoyuan, thank you for your patience with me. I'll close this now.

**Pull request closed without merging**
