### PR TITLE
update Alpine test images

### PR DESCRIPTION
**Pull request by wfurt**
update images to cover current latest Alpine 3.18. 
3.15 is EOS.

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Review by CarnaViire — APPROVED** [review]

**Comment by CarnaViire** [comment]
cc @ManickaP FYI

**Review by carlossanlop — APPROVED** [review]
Assuming the CI is green, LGTM.
Do you need to manually trigger any azp run legs for this?

**Comment by CarnaViire** [comment]
It seems that even though libmsquic is present on new images, we fail to load it 😕 @wfurt 
```
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicPlatformDetectionTests.cs(50,0): at System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue()
        --- End of stack trace from previous location ---
      Output:
        /usr/lib/libmsquic.so.2
```
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-94487-merge-f1344e9910b8490584/System.Net.Quic.Functional.Tests/3/console.0e74afd9.log?helixlogtype=result

**Comment by wfurt** [comment]
I'll take a look.

**Comment by wfurt** [comment]
```
bash-5.1$ ldd /usr/lib/libmsquic.so.2
	/lib/ld-musl-x86_64.so.1 (0x7f3f6d947000)
	libcrypto.so.1.1 => /lib/libcrypto.so.1.1 (0x7f3f6d56e000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f3f6d947000)
Error relocating /usr/lib/libmsquic.so.2: EVP_seed_cbc: symbol not found
```

That is interesting as I fixed this long time ago in MsQuic https://github.com/microsoft/msquic/pull/3417

**Comment by carlossanlop** [comment]
@wfurt do we want this backported?

**Comment by wfurt** [comment]
This is not critical AFAIK @carlossanlop. e.g. this is mostly attempt to stay current so I would probably hold of for now. I don't know what strategy we have for old releases ... as the versions we used to run on will eventually EOS/EOL.

**Pull request merged**
