### PR TITLE
Switch to automatic 8.0 version updates

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Comment by carlossanlop** [comment]
Let me know when you want me to merge this.
I see some failures, are they related?
Are we going to wait for all the CI to finish? If not, can you please ping me when the necessary legs finish?

**Comment by lewing** [comment]
the failures aren't related but I think they have been fixed in main. is that correct @akoeplinger ?

**Comment by akoeplinger** [comment]
yeah I think we fixed them in main.

**Review by akoeplinger — APPROVED** [review]

**Comment by lewing** [comment]
need https://github.com/dotnet/runtime/pull/109638/commits/3f26b4c97076c6a5bf4a19c4c5af6bd07aed83d9 in release/9.0 I think

**Comment by lewing** [comment]
> need [3f26b4c](https://github.com/dotnet/runtime/commit/3f26b4c97076c6a5bf4a19c4c5af6bd07aed83d9) in release/9.0 I think

https://github.com/dotnet/runtime/pull/110590

**Pull request merged**
