### PR TITLE
Fix BinderTracingTest

### PR DESCRIPTION
**Pull request by mateoatr**
Takes the changes from https://github.com/dotnet/runtime/pull/55225. This should fix https://github.com/dotnet/runtime/issues/59531.

### CODE REVIEW

**Comment by elinor-fung** [comment]
> Takes the changes from #55225.

Minor clarification: I believe the key part is from https://github.com/dotnet/runtime/pull/53808/commits/77da330bde10e4aa17703a45aeb84045825bc599 - which #55225 was on top of, so the full fix here.

**Review by elinor-fung — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  @Anipik this is a tell mode infra change (test).  Can you merge once there is a good time?
@mateoatr is this change needed to unblock a failing CI?

**Comment by elinor-fung** [comment]
These tests are run on PR, so any PR after https://github.com/dotnet/runtime/pull/59428 got merged - for example, https://github.com/dotnet/runtime/pull/59476 and https://github.com/dotnet/runtime/pull/59548 - will hit this (all CoreCLR runtime test legs fail).

**Comment by jeffschwMSFT** [comment]
@mateoatr can you take a look at the CI failures?

**Comment by agocke** [comment]
Failing CI was just network errors -- reran and everything's passed

**Comment by NikolaMilosavljevic** [comment]
> These tests are run on PR, so any PR after #59428 got merged - for example, #59476 and #59548 - will hit this (all CoreCLR runtime test legs fail).

@elinor-fung how can I get my PR (https://github.com/dotnet/runtime/pull/59548) to succeed - what would be the steps?

**Pull request merged**
