### PR TITLE
[mono][infra] Remove Mono LLVMJIT builds

### PR DESCRIPTION
**Pull request by matouskozak**
Mono no longer uses LLVM JIT backend and uses regular mini JIT instead.

The LLVMJIT jobs were completely removed from the `runtime-llvm` and `runtime-official` CI and refactored into regular Mono product builds for `runtime`.

Additionally, make AOT and fullAOT jobs Release only (both PR and rolling builds).

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
Are you going to work on removing LLVMJIT from the mono runtime too?

**Comment by matouskozak** [comment]
> Are you going to work on removing LLVMJIT from the mono runtime too?

I wasn't planning to. I thought that @radekdoulik was trying to remove that as part of LLVM 19 bump https://github.com/dotnet/runtime/pull/103585 ?

**Comment by radekdoulik** [comment]
> > Are you going to work on removing LLVMJIT from the mono runtime too?
> 
> I wasn't planning to. I thought that @radekdoulik was trying to remove that as part of LLVM 19 bump #103585 ?

We are making the runtime build the LLVM JIT without errors in that PR so far. It removes existing optimizations, which used legacy pass manager.

Given that this configuration (LLVM/JIT) is not used anymore, we can probably just strip it as @akoeplinger says.

**Pull request merged**
