### PR TITLE
[Wasm][AOT] Add the ability to the display the native stack frames

### PR DESCRIPTION
**Pull request by thaystg**
Another approach for PR #45124

How it will be visible in console:
image

### CODE REVIEW

**Comment by radical** [comment]
Just wondering if we should make `mono_runtime_printf*` use logger functions (at least on wasm?), so they will all end up with traces in the js console?

**Comment by thaystg** [comment]
`mono_runtime_printf*` already prints  in the js console.

**Comment by radical** [comment]
> `mono_runtime_printf*` already prints in the js console.

oh, then why the change to use `g_printerr` in case of wasm? If we want it to show up as an error, then maybe `mono_runtime_printf_err`?

**Comment by thaystg** [comment]
Because I want to be able to show the callstack when click on the arrow and not only a message.

**Comment by radical** [comment]
Oh, sorry, I meant, show up in the js console with a trace. I guess, `console.error` would do that.

And `mono_runtime_printf_err` doesn't do that? Maybe that needs to be changed? `console.error` would give you the stack trace with it, right?

**Comment by thaystg** [comment]
I didn't test `mono_runtime_printf_err`, but I would have to do the same ifdef but instead of using `g_printerr` 
 I would use `mono_runtime_printf_err`. I can test you you think this is important for this PR. :)

**Comment by radical** [comment]
> I didn't test `mono_runtime_printf_err`, if it work I would have to do the same ifdef but instead of using `g_printerr`
> I would use `mono_runtime_printf_err`. I can test you you think this is important for this PR. :)

I'm not insisting on anything! I was just thinking that if `mono_runtime_printf_err` would be changed to use the logger, thus writing with `console.error`, and showing up in the console with a stack trace, then all other instances of `mono_runtime_printf_err` callers would get the same benefit. Just a thought :)

**Comment by thaystg** [comment]
@radical I will test right now.

**Comment by radical** [comment]
> >... if it work I would have to do the same ifdef but instead of using `g_printerr`
> > I would use `mono_runtime_printf_err`...

Oh, and I meant replacing the current `mono_runtime_printf` with `mono_runtime_printf_err`, and no `ifdef` in this location. Sorry, I missed mentioning that!

**Comment by thaystg** [comment]
Then I would change the behavior in the case of non wasm, I'm not sure if we want it...

**Comment by radical** [comment]
> Then I would change the behavior in the case of non wasm, I'm not sure if we want it...

True, and that was my question.. if changing that behavior makes sense. If it doesn't, then this change looks fine. Sorry, for being so confusing 😬

**Comment by thaystg** [comment]
Yes, `mono_runtime_printf_err`, shows the stack trace on console.log.
image

**Comment by radical** [comment]
Ok. So, this message itself is just a debug message, but IIUC, on wasm:

- `mono_runtime_printf` - doesn't show this with a trace
- `mono_runtime_printf_err` - does

.. but since the message is just meant as debug message, we wouldn't want to use `mono_runtime_printf_err`.

So, your current change looks good to me! 👍

**Review by radical — APPROVED** [review]

**Review by lewing — COMMENTED** [review]
LGTM.  My only question is if there is a reason we want to preserve the existing behavior on other platforms or was this a bit arbitrary to begin with?

cc @lambdageek @CoffeeFlux

**Review by lewing — APPROVED** [review]

**Pull request merged**
