### PR TITLE
Remove some manual test scaffolding

### PR DESCRIPTION
**Pull request by markples**
These are either propagating unnecessary 100s or doing what the wrapper generator now does.

### CODE REVIEW

**Comment by markples** [comment]
These were found using a hacky analyzer that looked for N-1 of a test's returns to be `if (expr == 100) return k;` or some variations on that. The analyzer itself isn't appropriate for merging.

**Comment by markples** [comment]
@TIHan PTAL

cc @trylek @jkoritzinsky @dotnet/jit-contrib No analyzer changes here - just test cleanup (deleting code and some Assert.Throws)

**Review by trylek — APPROVED** [review]
Looks great to me, thanks Mark!

**Review by TIHan — APPROVED** [review]
Looks good to me as well!

**Review by jkoritzinsky — APPROVED** [review]

**Comment by markples** [comment]
Actually, @TIHan, since you also reviewed this, could you please see this one through?  The issue is just veriying through outerloop (since tests might be pri 1) and extra-platforms (don't want to break mono, for example), but those jobs are often noisy and verifying them isn't immediate.

**Comment by TIHan** [comment]
@markples sure, I can try to get this through

**Comment by trylek** [comment]
Rebased against latest main, tested locally, fixed wrong merge with Mark's help, rerunning lab testing, planning to merge in assuming it passes.

**Comment by trylek** [comment]
Merging in as the linux x64 outerloop issues are known and understood (caused by running Crossgen2 in the lab under .NET 8 Preview 7 SDK, the bug is fixed in RC1 version of the SDK).

**Pull request merged**
