### PR TITLE
Remove crossgen from test build and run scripts

### PR DESCRIPTION
**Pull request by BruceForstall**
https://github.com/dotnet/runtime/pull/53458/ removed crossgen; this removes it from the test scripts.

### CODE REVIEW

**Review by trylek — APPROVED** [review]
Nice cleanup, thanks Bruce!

**Comment by mangod9** [comment]
would this need any change in the pipelines?

**Comment by trylek** [comment]
My 1 cent is that all pipelines running the code Bruce is removing should already be on the floor after Manish's change to shut down Crossgen1.

**Comment by BruceForstall** [comment]
> My 1 cent is that all pipelines running the code Bruce is removing should already be on the floor after Manish's change to shut down Crossgen1.

That was my guess.

Looks like there are some existing CG2 asserts/failures in the test jobs, though... plus arm64/arm32 legs (or machines in Helix) are in terrible shape, causing lots of failures.

**Comment by BruceForstall** [comment]
Failures are all infra or existing failures.

**Pull request merged**
