### PR TITLE
[ARM64] Change INS_bkpt to INS_brk for INS_BREAKPOINT

### PR DESCRIPTION
**Pull request by xiangzhai**
https://github.com/dotnet/runtime/issues/606

Cheers,
Leslie Zhai

### CODE REVIEW

**Comment by xiangzhai** [comment]
False positive? 
* runtime-coreclr — #20191215.15 failed

**Comment by BruceForstall** [comment]
Since arm64 shouldn't ever use bkpt, can you also:

- change the use of `INS_bkpt` in `CodeGen::genCallFinally()` in codegenarm64.cpp,
- remove `bkpt` from the comment in emitarm64.cpp (`case IF_SN_0A: // bkpt, nop`)
- remove the encoding for `bkpt` in instrsarm64.h:
```
INST1(bkpt,    "bkpt",   0, 0, IF_SN_0A,  0xD43E0000)
                                   //  brpt                         SN_0A  1101010000111110 0000000000000000   D43E 0000   0xF000
```

?

**Comment by xiangzhai** [comment]
Hi @BruceForstall 

Thanks for your review!

I updated the patch as you suggested, please review it again.

Cheers,
Leslie Zhai

**Comment by xiangzhai** [comment]
> ##[error]The HTTP request timed out after 00:01:40.

How to ci-help?

**Comment by BruceForstall** [comment]
Unfortunately, it looks like the situation is a little more complicated that it should be.

I reproduced the failure and your fix on Linux, and it looks good.

I tried the existing code and your fix on Windows, and it doesn't work. With the existing code (using bkpt), setting COMPlus_JitHalt to some function and running a test, the Windows windbg debugger works as desired, and stops at that instruction. With your change, windbg shows an illegal instruction exception, and kills the process.

So, I think we need to leave the existing code, but #ifdef your fix (for defining INS_BREAKPOINT especially) under _TARGET_UNIX_.

**Comment by xiangzhai** [comment]
> So, I think we need to leave the existing code, but #ifdef your fix (for defining INS_BREAKPOINT especially) under _TARGET_UNIX_.

Updated as you suggested.  Please review it again.

Cheers,
Leslie Zhai

**Comment by xiangzhai** [comment]
> ##[error](NETCORE_ENGINEERING_TELEMETRY=Build) Format job found errors, please apply the format patch.
##[error]C:\Python\python.exe failed with return code: 4294967294

Any suggestion?

**Comment by BruceForstall** [comment]
@xiangzhai It looks like you ran into a pre-existing problem with the formatting jobs (see https://github.com/dotnet/runtime/pull/990 for some discussion). I would normally encourage you to look at https://github.com/dotnet/jitutils and run "jit-format" over your code. However, it looks like that hasn't been properly updated to work with the new dotnet/runtime repo. For now, you might need to just wait until this gets fixed before re-testing.

**Review by BruceForstall — APPROVED** [review]
Code change looks good to me. Thanks!

**Comment by xiangzhai** [comment]
Hi @BruceForstall 

Thanks for your review and teaching!

Cheers,
Leslie Zhai

**Comment by TamarChristinaArm** [comment]
> Since arm64 shouldn't ever use bkpt, can you also:
> 
> * change the use of `INS_bkpt` in `CodeGen::genCallFinally()` in codegenarm64.cpp,
> * remove `bkpt` from the comment in emitarm64.cpp (`case IF_SN_0A: // bkpt, nop`)
> * remove the encoding for `bkpt` in instrsarm64.h:
> 
> ```
> INST1(bkpt,    "bkpt",   0, 0, IF_SN_0A,  0xD43E0000)
>                                    //  brpt                         SN_0A  1101010000111110 0000000000000000   D43E 0000   0xF000
> ```
> 
> ?

Something is odd here.. I was wondering how this was working at all on Windows if this was really a `bkpt` instruction.  Turns out it's not. This encoding is for `brk` so it seems that it's just the instruction label is wrong. The encoding for `bkpt` in `instrarm64.h` is the encoding for `brk 0xF00` which is a valid breakpoint in AArch64.

the encoding for `brk` seems to be encoding `brk 0x0` but both instructions should have worked in both debuggers..

```
0000000000000000 <.text>:
   0:   d43e0000        brk     #0xf000
   4:   d4200000        brk     #0x0
```

The immediate effects what kind of signal the kernel raises on Linux, but for both `0x0` and `0xF00` the kernel correctly raises `SIGTRAP` but gdb is choosing not to handle it.. I'm not sure why, but because of this `brk 0xF00` causes a loop in the signal handler of gdb and the program "hangs".

I would suggest renaming `bkpt` in `instrsarm64.h` to something else to avoid this confusion.. My suggestion would be `brk_windows` and `brk_linux`.

**Comment by TamarChristinaArm** [comment]
It seems the issue for GDB is that whenever it traps the `SIGTRAP` it loops through its list of breakpoints and because it doesn't find a breakpoint set at that point it continues the program, which triggers another `SIGTRAP` and so on.
For some reason it's treating `brk 0x0` differently but I'm not sure why.

GDB is expecting the breakpoint to be set through `ptrace` with `NT_ARM_HW_BREAK` but in my opinion the `brk` should work... I'll chase this up with the GDB folks, but for the current and old versions of GDB `brk 0x0` seems to be the only one that'll work.

**Comment by BruceForstall** [comment]
@TamarChristinaArm Thanks for looking. I did see that windbg disassembled what the JIT calls `bkpt` as `brk 0xf000`, but I didn't propagate that information up to this issue. So for some reason, then, apparently windbg / Windows likes this one, but doesn't like `brk 0x0`.

**Comment by TamarChristinaArm** [comment]
> @TamarChristinaArm Thanks for looking. I did see that windbg disassembled what the JIT calls `bkpt` as `brk 0xf000`, but I didn't propagate that information up to this issue. So for some reason, then, apparently windbg / Windows likes this one, but doesn't like `brk 0x0`.

Yeah, for GDB it seems that `brk 0x0` was hardcoded into it. They're looking if they can relax this, or at the very least not get into an infinite loop. `windbg` probably has a similar reason I would imagine.

**Comment by xiangzhai** [comment]
Hi @TamarChristinaArm 

Thanks for your teaching!

Cheers,
Leslie Zhai

**Comment by xiangzhai** [comment]
Hi @BruceForstall 

How to retrigger the CI checkers?  https://github.com/dotnet/runtime/pull/990 has been merged.  Could you please help me to retrigger the test?

Thanks,
Leslie Zhai

**Comment by BruceForstall** [comment]
Looks like I managed to re-trigger it.

cc @CarolEidt

**Comment by BruceForstall** [comment]
(If you click on "Details", there is a "Re-run" link on failing jobs)

**Comment by xiangzhai** [comment]
> (If you click on "Details", there is a "Re-run" link on failing jobs)

The "Re-run" link is not available to me.  Perhaps I do not have the access permission?

**Comment by xiangzhai** [comment]
Hi @BruceForstall 

> For now, you might need to just wait until this gets fixed before re-testing.

#990 fixed the issue or not?

> Build #20191223.30 had test failures

Regression?

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Merry Christmas :)

**Comment by BruceForstall** [comment]
I'm going to close and re-open to (hopefully) get re-testing. Note that the Windows ARM jobs are still broken (https://github.com/dotnet/runtime/issues/702).

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
Looks like there are actual formatting job issues:
```
clang-format: there are formatting errors in F:\workspace\_work\1\s\src\coreclr\src\jit\compiler.h
At Line 10610 Before:
const instruction INS_MULADD     = INS_madd;
After:
const instruction INS_MULADD = INS_madd;

Clang-format found formatting errors.
jit-format found formatting errors. Run:
	jit-format --fix --untidy
```

**Comment by xiangzhai** [comment]
Hi @BruceForstall 

Welcome back :)

> Looks like there are actual formatting job issues:
> 
> ```
> clang-format: there are formatting errors in F:\workspace\_work\1\s\src\coreclr\src\jit\compiler.h
> At Line 10610 Before:
> const instruction INS_MULADD     = INS_madd;
> After:
> const instruction INS_MULADD = INS_madd;

**Before** is someone might want to right alignment?

Could I change the `const instruction INS_MULADD = INS_madd;`?

Thanks,
Leslie Zhai

**Comment by BruceForstall** [comment]
You could try that.

Or, you could set yourself up to run `jit-format` from the `dotnet/jitutils` repo -- which would be good to be able to do.

Or, you can download the patch files created by the failing CI job and apply those. From the failing Linux formatting job, it gives these instructions:
```
There were errors in formatting. Please run jit-format locally with: 

	jit-format -a x64 -b Checked -o Linux -c <absolute-path-to-coreclr> --verbose --fix --projects dll


Or download and apply generated patch:
1. From the GitHub 'Checks' page on the Pull Request, with the failing Formatting
   job selected (e.g., 'Formatting Linux x64'), click the 'View more details on
   Azure Pipelines' link.
3. Select the 'Summary' tab.
4. Open the 'Build artifacts published' entry.
5. Find the link to the OS/architecture appropriate format patch file.
6. Click on the link to download it.
7. Unzip the patch file.
8. git apply format.patch
```
Unfortunately, it looks like Azure DevOps changed their UI. But the bottom-line is: find the format.patch artifacts stored with the CI job (they will also have OS / architecture in their name), and apply them.

**Comment by xiangzhai** [comment]
Hi @BruceForstall 

No format issue any more.

But I have no idea about other failures.  False positive?

Thanks,
Leslie Zhai

**Comment by sandreenko** [comment]
> But I have no idea about other failures. False positive?

Most likely from what I see, arm and crossgen-comparison are known. x64 failed during "Download native test artifacts" which I have not seen before, but it is clearly infra.

**Comment by xiangzhai** [comment]
Hi @sandreenko 

Thanks for your kind response!

The patch is accepted and ready to land?

Cheers,
Leslie Zhai

**Comment by BruceForstall** [comment]
Since it looks like infrastructure issues in the CI failures, I'll go ahead and merge it.

@xiangzhai Thanks for your patience and various iterations!

**Comment by xiangzhai** [comment]
Hi,

You are welcome :)

Cheers,
Leslie Zhai

**Pull request merged**
