### PR TITLE
Move Msquic over to Source-generated delegate interop.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
I missed this when turning on DisableRuntimeMarshalling because we don't run any Quic tests in our regular CI that actually use MsQuic and we don't have the DisableRuntimeMarshalling analyzer yet.

cc: @dotnet/interop-contrib

### CODE REVIEW

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by kasperk81** [comment]
why there is so much more code? shouldn't "generator" have the opposite effect?

**Comment by jkoritzinsky** [comment]
This code was generated from a generator that runs in a different mode and adapted to this use case. A source generator to capture this scenario is tracked in https://github.com/dotnet/runtime/issues/63590. When that feature is implemented, we will move this code back to being source-generated.

**Review by elinor-fung — APPROVED** [review]
Do we have a test to run or some other form of confirmation that the related issues in ASP.NET are fixed with this?

**Comment by jkoritzinsky** [comment]
@BrennanConroy is there any validation we can do to make sure I caught all the cases that are causing problems?

**Comment by BrennanConroy** [comment]
All we're doing in ASP.NET Core is calling `QuicImplementationProviders.Default.IsSupported`, so if you can run that successfully (maybe check it failed before) then it should be good.

**Comment by jkoritzinsky** [comment]
It looks like there might be some more non-blittable marshalling places in MsQuic. Marking this as no-merge for now.

**Comment by wfurt** [comment]
just a note that msquic now produce low-level generated binding for c#. There is desire to abandon ours and use theirs in 7.0 time frame.

**Comment by jkoritzinsky** [comment]
I've fixed the last few cases that were causing issues. Once this is green, it's ready to merge.

**Comment by kasperk81** [comment]
> just a note that msquic now produce low-level generated binding for c#. There is desire to abandon ours and use theirs in 7.0 time frame.

if eventually it will be replaced, what value this temporary excessive glue would bring (other than burdening the git history)?

**Comment by jkoritzinsky** [comment]
The library is currently broken without this change, so it is necessary to enable ASP.NET to consume newer dotnet/runtime builds

**Pull request merged**
