### PR TITLE
Replace uses of qsort in jit with a stable sort

### PR DESCRIPTION
**Pull request by davidwrighton**
Current use of `qsort` interferes with cross compilation.
- The `qsort` algorithm is quite different between Windows and Linux, thus causing cross compilation failures

This replaces `qsort` with a drop-in replacement `stable_sort_clr` which provides a stable sort (based on the merge sort algorithm), as well as making that implementation slightly higher performance than can be reached with function pointers. (Particularly in Windows where CFG has costs for function pointer usage.) With a homegrown sort performance test, there is about 15-30% performance win with this sort over `qsort`. (However as these tests do not resemble the behavior of the these sorts in the JIT I do not believe they are spectacularly relevant.)

There is a size cost of about 4KB for the templatized routines. I was unable to measure a performance difference for the JIT itself. (Crossgen is very slightly faster in my testing with the change, but I do not believe the difference is statistically meaningful.)

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
When you say:

> The qsort algorithm is quite different between Windows and Linux, thus causing cross compilation failures

do you mean by "failure" that compilation does not complete successfully? Or, is it something else, like you want cross compilation and native compilation to generate identical binaries, and the current qsort implementation (which is a CRT api?) does not allow that.

**Comment by AndyAyersMS** [comment]
We also have `jitstd::sort` (in `jitstd\algorithms.h`) which is used to sort the lcl var table;.

Should we consolidate onto just one sorting algorithm?

**Comment by BruceForstall** [comment]
> This replaces qsort with a drop-in replacement stable_sort_clr which provides a stable sort

Why does the sort need to be "stable"? It seems like the JIT doesn't require this (and in fact the `jitstd::sort()` function explicitly says it's not stable).

Also, there are zero comments in the stable_sort.h file.

**Comment by davidwrighton** [comment]
@BruceForstall, this is not a matter of correctness in terms of will the jit work correctly, but it is in regards to behavior differing from  running the JIT on various CRTs for both cross-bitness, cross-os. and cross-crt(musl vs glibc) scenarios.

The reason I looked at a stable sort, is that when the sort is stable, it doesn't matter what the algorithm is, it will always behave the same. With an unstable sort, the exact algorithm needs to be the same on each system. As @AndyAyersMS notes, instead of switching to a stable sort, we could standardize on an single algorithm for sorting such as the `jitstd::sort` algorithm. I'm going to prepare a change based on `jitstd::sort`, and see what that looks like, and we can pick and choose which approach we prefer. It will be a more impactful change to the various bits of code which would be harder to swap between use of qsort and the new sorting routine in case there is a size problem for clrjit.dll.

**Comment by briansull** [comment]
With an un-stable sort the JIT would become non-deterministic and we don't want that.

**Comment by davidwrighton** [comment]
The jitstd::sort approach was preferred. That pr is now merged in.

**Pull request closed without merging**
