### PR TITLE
[ocsp stapling] reject incorrect http response if the status code is not 2xx

### PR DESCRIPTION
**Pull request by cdlliuy**
Draft a possible fix for https://github.com/dotnet/runtime/issues/89907

### CODE REVIEW

**Comment by vcsjones** [comment]
If the server really is indeed stapling a nonsense OCSP then I think a more appropriate fix would be to make sure that the stapled response is a well formed OCSP response, valid for the certificate, etc.

This fix as written will still staple incorrect responses if happens to respond with non-OCSP content but with an HTTP 200 status code.

Also, returning `null` for >= HTTP 300 will break following redirects.

A more appropriate fix might be that in

https://github.com/dotnet/runtime/blob/44b05439668f3bec716aa842f74b3b6dd17e723f/src/native/libs/System.Security.Cryptography.Native/pal_ssl.c#L1273

We might consider parsing the content and, if it isn’t a parseable OCSP, then skipping the stapling. That still doesn’t address the problem where a wrong OCSP response might be stapled.

**Comment by wfurt** [comment]
we may still bail for anything > 400 @vcsjones ? The body is likely some kind of error message anyway.

**Comment by vcsjones** [comment]
> still bail for anything > 400 @vcsjones ?

That seems reasonable, but not a complete fix. I would guess that there is greater than zero CAs out there that return an error result with an HTTP 200, or someone has a proxy, captive portal, etc. that intercepts HTTP requests and may return HTTP 200 pages.

**Comment by bartonjs** [comment]
* https://github.com/dotnet/runtime/blob/f43b0c124c2018b7b0fa8be0e173280ebc8031c7/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamCertificateContext.Linux.cs#L226-L233 calls X509DecodeOcspToExpiration, and ignores the response if it fails
* https://github.com/dotnet/runtime/blob/f43b0c124c2018b7b0fa8be0e173280ebc8031c7/src/libraries/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OCSP.cs#L35 calls CryptoNative_X509DecodeOcspToExpiration, and fails if that call returns 0.
* https://github.com/dotnet/runtime/blob/f447532b85af1d64889fe5406c218aa5feb69eb9/src/native/libs/System.Security.Cryptography.Native/pal_x509.c#L1305-L1319 calls d2i_OCSP_RESPONSE, and returns 0 if that fails (or things about it look wrong).

So, I don't think the proposed fix would even help, since it should be hitting the same "we ignored this" case that should already be happening.

If a bad response got in there, it sort of feels like some very wonky thing happened, like that array got overwritten?

CryptoNative_X509DecodeOcspToExpiration looks like it might pass if there was a legitimate response plus some dangling garbage, which probably isn't what was intended, but also doesn't sound like the problem that was experienced.

**Comment by cdlliuy** [comment]
yeah, I agree the original fix won't work (and also break the redirect flow by typo) 

So the current idea is to validate the OCSP content,  and cache the correct format only.  Is my understanding correct?   
will "retrying the connection to ocsp responder" help here in case it is an intermittent failure.  

Then, for the failed case, i.e. a bad response status code or bad content,   does it still "return null" for DownloadOcsp request? 
When "returning null",  what will happen in client side?   will client side fall back to client-driven ocsp?   or just fail the https connection request?

**Comment by bartonjs** [comment]
Since the proposed fix is not correct (it's invalidating the redirect handler code immediately below it), and doesn't feel like the right shape at all (an HTTP 200 with an error message is still "not a valid OCSP payload"), I'm going ahead and closing this PR.  We'll continue discussion/investigation on the issue instead of the PR.

**Pull request closed without merging**
