### PR TITLE
[release/7.0] Remove wbt manifest hack

### PR DESCRIPTION
**Pull request by lewing**
Now that the latest installer has the new manifest names

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Review by radical — APPROVED** [review]

**Comment by radical** [comment]
The WBT failure here is due to network issues.

**Comment by carlossanlop** [comment]
> The WBT failure here is due to network issues.

Should the failed legs be restarted then? Several failed.

**Comment by carlossanlop** [comment]
@marek-safar can we get an approval please?

**Review by jeffschwMSFT — APPROVED** [review]
approved.  Thanks for cleaning up this hack

**Comment by radical** [comment]
@carlossanlop this is ready to go

**Pull request merged**
