### PR TITLE
Some small copy propagation changes

### PR DESCRIPTION
**Pull request by SingleAccretion**
Address https://github.com/dotnet/runtime/pull/65902#discussion_r818153639.

Add some asserts now that we don't push all the defs and don't have them implicitly.

[No diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1661846&view=ms.vss-build-web.run-extensions-tab).

### CODE REVIEW

**Comment by SingleAccretion** [comment]
Will once again assume OSX timeouts are not related.

@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
@kunalspathak ptal

**Comment by SingleAccretion** [comment]
Stress failures look like #66601 and #63854.

**Review by kunalspathak — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
