### PR TITLE
Fix CLR_CMAKE_USE_SYSTEM_LIBUNWIND on macOS

### PR DESCRIPTION
**Pull request by Bo98**
On macOS, `libunwind` does not exist, which causes `find_unwind_libs` to fail. macOS does not require any linker flags as libunwind exists in libSystem, which is implicitly linked.

If accepted, I'd like to request this change is backported to 6.0 since it affects that too.

### CODE REVIEW

**Comment by am11** [comment]
@Bo98, thank you for your contribution. Could you describe why are you passing `-DCLR_CMAKE_USE_SYSTEM_LIBUNWIND=ON` to `./build.sh` on macOS? The usage of this argument from command-line is intended for linux.

**Comment by Bo98** [comment]
Can definitely gate it to Linux if that's preferred. I was torn a bit between that and this. The reason I opted for this way because it makes more semantic sense, given the likes of: https://github.com/dotnet/runtime/blob/9c9ebb945eff9eb8fd02189ff93fb743235413c3/src/coreclr/pal/src/CMakeLists.txt#L1-L4

and 

https://github.com/dotnet/runtime/blob/9c9ebb945eff9eb8fd02189ff93fb743235413c3/src/coreclr/pal/src/CMakeLists.txt#L19-L20

Feels inconsistent to me but if that's intentional then that's fine.

**Comment by Bo98** [comment]
(It was also something that didn't used to be conditioned per OS: https://github.com/dotnet/runtime/commit/b9f273a254f02038216295f49be77faa015036b5, so I must've missed the change that made it Linux-only, apologies.)

**Comment by am11** [comment]
Your change looks alright; fixing this inconsistency is good. 🙂 I was mainly curious about the need of backporting to 6.0, since it is not a widespread issue and it is actually working as designed (the original need for this bailing option emerged from Linux distro package).

---
Note that the copy of libunwind sources, that we have in this repo, has handful of carefully optimized tweaks to improve, enhance and even bugfix (in case of ARM architecutre) the runtime's interaction with stack unwinder on top of latest libunwind v1.6.2. We have upstreamed some of those tweaks back to https://github.com/libunwind/libunwind, but there are still a few patches not upstreamed yet. So compiling libunwind from the in-tree sources (i.e. build without `-DCLR_CMAKE_USE_SYSTEM_LIBUNWIND=ON`) is definitely better than using the one from some distro packages, e.g. Debian, which are providing very old version (1.3.2: https://tracker.debian.org/pkg/libunwind). Last time I checked, their (low priority) criteria of revving this package version was based on the number of its direct dependents (which was just `three` packages when I checked it).

In runtime repo, there are some (regular) dependencies like libkrb5, libnuma, liblttng-ust and libicu which are needed from the system packages (or they are optional like libnuma). Then there are some dependencies which have sources in-tree (all these: https://github.com/dotnet/runtime/tree/e448104/src/native/external), which IMO are best to be compiled with the given runtime version / commit. (hint: there is a reason why the copy of those sources deemed necessary in first place). If there is a security issue which pops up, consider that as part of .NET release (not as a separate one), and wait for the patch issued from this repo.

**Comment by Bo98** [comment]
> definitely better than using the one from some distro packages, e.g. Debian, which are providing very old version

Yeah, to be clear: I'm in a package manager environment where libunwind is latest 1.6.2.

**Comment by am11** [comment]
> I'll have a look further into the additional patches you are mentioning however

We maintain the logs in the corresponding version files, e.g. https://github.com/dotnet/runtime/blob/e448104/src/native/external/libunwind-version.txt.

**Review by janvorli — COMMENTED** [review]
LGTM, thank you!

**Review by janvorli — APPROVED** [review]

**Pull request merged**
