### PR TITLE
Thread abort exceptions, do not preallocate + some cleanup.

### PR DESCRIPTION
**Pull request by VSadov**
- no need to preallocate thread abort and base exceptions at initialization
- cleaned up some tracking of state whether thread abort was requested from the user code (no longer possible) vs. internally - from the debugger cancelling expression evaluation.

Main assumptions: 
- it is no longer possible for a thread abort to happen directly or indirectly because of the user code. 
- the only scenario is the internal use of thread abort by debugger to tear down runaway expression evaluations. 
- thread abort in debug scenario is a "best effort" feature. In theory it is unsafe, especially the rude variant. In practice it typically works ok, and is better than terminating the debuggee.

Resolves:https://github.com/dotnet/runtime/issues/44442

### CODE REVIEW

**Comment by VSadov** [comment]
CC: @tommcdon @hoyosjs

**Comment by VSadov** [comment]
I have run diagnostics tests with these changes, a few times to be sure - no new failures were observed.

**Comment by janvorli** [comment]
I like the cleanup of the ThreadAbort handling. But is it really worth the saved size to not to preallocate the exceptions? It seems that an Exception instance takes ~100 bytes only.

**Comment by VSadov** [comment]
@janvorli - allocations were the original complaint that lead to this PR. 

Allocating these instances and handles may not be a lot, but still measurable in the context of startup. @stephentoub may have more on how much they stick out in the profiles.

As I see this - these exceptions are now used only in an extreme corner case when an expression evaluation times out while debugging, and even then pre-allocating them is not really important, so why have that.

**Comment by janvorli** [comment]
> As I see this - these exceptions are now used only in an extreme corner case when an expression evaluation times out while debugging

I keep hitting timeouts when viewing the locals window in VS very often. So I wouldn't call that extreme corner cases :-). But I am not worried about an impact of the thread abort exception allocation. 

But I was a bit worried about the preallocated base exception removal. The comments at the following two places explicitly mentions that it was not desirable to get OOM exception there in case of OOM:
https://github.com/dotnet/runtime/blob/51f59f509d902088544b1c19578fe84045005249/src/coreclr/vm/clrex.cpp#L135-L150
https://github.com/dotnet/runtime/blob/51f59f509d902088544b1c19578fe84045005249/src/coreclr/vm/clrex.cpp#L820-L833
The new GetBestBaseException would give us OOM exception in case we cannot allocate the Exception, contradicting those two comments.
On the other hand, the likelyhood that the runtime can survive the state when just allocating a new exception results in OOM seems to be very low, so it seems the new way would not make things worse in a general way.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by VSadov** [comment]
Regarding: 
> // Hence, we return preallocated System.Exception instance. Lossy information is better 
 // than wrong or no information (or even FailFast).

My reasoning is that since we cannot not provide the "right" exception, because we cannot allocate it, giving OOM would be fairly truthful - we are in a state where we cannot function normally because of memory shortage.

User can try handle the situation by trimming memory use or at least will see OOM in Watson/dump and have a bit more info about environment at the time of the crash.

**Comment by VSadov** [comment]
Thanks!!!

**Review by stephentoub — COMMENTED** [review]
Thanks!

**Pull request merged**
