### PR TITLE
[NativeAOT] simpler ObjectHasComponentSize

### PR DESCRIPTION
**Pull request by VSadov**
I keep seeing entries like ` BasicMinimalApi!S_P_CoreLib_Internal_Runtime_MethodTable__get_ComponentSize` in profiles. But `MethodTable.ComponentSize` is a simple one-liner that should be inlineable. 

I expected that #83351, besides code reuse, will also take care of this, but there is more.

Turns out things like `Memory<T>.Span` [call `ObjectHasComponentSize` ](https://github.com/dotnet/runtime/blob/55a09408141e4c97b866b7f36910d033d2f1f05d/src/libraries/System.Private.CoreLib/src/System/Memory.cs#L293) to detect if the underlying object is an array and NativeAOT implementation does `EETypePtr.ComponentSize != 0`, and that calls `MethodTable.ComponentSize`. The roundabout way might be difficult to inline. 

`MethodTable.HasComponentSize` is just a sign check for the flags word, so here is a simpler implementation.

I've also switched a few other places that use `EETypePtr.ComponentSize`

### CODE REVIEW

**Review by MichalStrehovsky — APPROVED** [review]
Thanks! Also relevant: https://github.com/dotnet/runtimelab/issues/232

The only things in favor of EETypePtr I see is:

1. no need to type `unsafe`
2. It can override `==`. In the past we had a mode where `MethodTable` for arrays/pointers could be duplicated (i.e. we have multiple `MethodTable` structures for the same array type). But unclear if that comes back.

Otherwise it just hurts things.

**Comment by VSadov** [comment]
Right, I am not sure `EETypePtr` is an interesting abstraction. It looks the same as `MethodTable`, but with special equality. It may be a better name for the concept, but `MethodTable` has been around for a long while.

I checked https://github.com/dotnet/runtimelab/issues/232 and I am more on the "lets remove" side than "lets make JIT inline it".

Perhaps we should start dismantling `EETypePtr`, one API at a time, starting with `ComponentSize`. 
I think only one use of that remained in `GetUninitializedObject` and primarily because there are other uses of `EETypePtr`, but it should be possible to switch all that to MethodTable.

**Comment by MichalStrehovsky** [comment]
> It may be a better name for the concept, but MethodTable has been around for a long while.

🥲 https://github.com/dotnet/runtimelab/pull/1329

**Comment by VSadov** [comment]
Thanks!

**Pull request merged**
