### PR TITLE
Use unix as the parent for the Android RID graph

### LINKED ISSUE #14908: In .NET 6 Android projects, <ResolvePackageAssets/> returns linux native libraries
For example, a .NET 6 Android app adding:
```
<PackageReference Include="akavache" Version="6.0.30"/>
```
This package brings in a lot of dependencies, and eventually this native library:
```
C:\src\xamarin-android\packages\sqlitepclraw.lib.e_sqlite3.linux\1.1.11\runtimes\linux-arm64\native\libe_sqlite3.so
```

When I review the [.binlog](https://github.com/dotnet/sdk/files/5667662/msbuild.zip), I see:
```
Task ResolvePackageAssets
...
OutputItems
    NativeCopyLocalItems
        C:\src\xamarin-android\packages\sqlitepclraw.lib.e_sqlite3.linux\1.1.11\runtimes\linux-arm64\native\libe_sqlite3.so
            AssetType = native
            CopyLocal = true
            DestinationSubPath = libe_sqlite3.so
            NuGetPackageId = SQLitePCLRaw.lib.e_sqlite3.linux
            NuGetPackageVersion = 1.1.11
            PathInPackage = runtimes/linux-arm64/native/libe_sqlite3.so
```
I think `linux` native libraries are being brought in, even though the `$(RuntimeIdentifier)` was `android.21-arm64` in this example. I can see where the Windows and OSX native libraries were excluded.

We currently have this workaround, which I would like to remove, thanks!

https://github.com/xamarin/xamarin-android/blob/97190b6cc56ef81be82bab48737155089a16f500/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1874-L1878

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Fixes: https://github.com/dotnet/sdk/issues/14908

In a .NET 6 Android project, adding a NuGet package such as:

    <PackageReference Include="akavache" Version="6.0.30"/>

...would include Linux native libraries from dependencies, such as:

    packages\sqlitepclraw.lib.e_sqlite3.linux\1.1.11\runtimes\linux-arm64\native\libe_sqlite3.so

Comparing the RID graph for iOS and Android in
`dotnet\sdk\*\RuntimeIdentifierGraph.json`:

    "ios": {
      "#import": [
        "unix"
      ]
    },
    ...
    "android": {
      "#import": [
        "linux"
      ]
    },

It seems like Android graph should match iOS here, as changing `linux`
-> `unix` solved this issue for me locally.

Based on the changes in #45442, I updated `runtimeGroups.props` to
specify `linux` instead of `unix` for Android. Then I ran this command
to update the checked-in `.json` files:

    > dotnet build .\src\libraries\pkg\Microsoft.NETCore.Platforms -p:UpdateRuntimeFiles=true

/cc @marek-safar @steveisok

### CODE REVIEW

**Comment by steveisok** [comment]
I think there's some pretty good resistance against putting android under unix.  See https://github.com/dotnet/runtime/pull/34789

Perhaps this will achieve the intended result?  https://github.com/dotnet/runtime/issues/43347

**Comment by marek-safar** [comment]
Yep, parenting android to unix was rejected. We need agreement first on how we want to address this problem.

@ericstj what do you suggest as the next steps?

**Comment by akoeplinger** [comment]
> Perhaps this will achieve the intended result? #43347

I don't think it will, at least not if we follow the `linux-musl `precedent which specifies `linux-musl -> linux` fallback paths, i.e. we'd still get the `linux` asset for the akavache package if we do the same for `linux-bionic`.

And if we don't do it then we're back to essentially the same situation with this PR where we're reparenting android to unix.

I think the underlying issue is that there are two competing concerns: allowing to reference managed-only `linux` RID-specific implementations that e.g. just p/invoke (which work and we want to have) versus pulling in native `.so` files for `linux` that definitely won't just work on android.

**Comment by ericstj** [comment]
>  allowing to reference managed-only linux RID-specific implementations that e.g. just p/invoke (which work and we want to have) versus pulling in native .so files for linux that definitely won't just work on android.

Do packages need to provide a different native asset in order to work on android?  If so they can provide that in the `android-arm64` folder.

Do packages need to not provide any native asset to work on android?  If so they can make that happen by adding an empty `android-arm64` folder.  Can't change the package?  Consumers can add `ExcludeAssets="native"` on the PackageReference.

There's no promise that a package that specializes for a platform will just work on a brand new platform that they've never considered.  RIDs try to do their best to represent useful reuse, so that more often than not folks can avoid duplication when they specialize by platform.  They can't get it right 100% of the time, but when its wrong there should be a way to make a package specialize for the new platform once the author understands it needs to.  We should only be changing RID hierarchy if there is data out there showing that a majority of the time the RID graph leads to duplication rather than reuse.

**Comment by jonathanpeppers** [comment]
@ericstj I think the problem is if a user brings in an innocent NuGet package in an Android project:

```xml
<PackageReference Include="akavache" Version="6.0.30"/>
```

How do we prevent linux `.so` files from being added to their app? They will not work on Android.

Right now we have this workaround, which doesn't seem right:

https://github.com/xamarin/xamarin-android/blob/59b18d0cf88c4a5b0f032a23fd2a096f57e8d685/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1874-L1878

**Comment by am11** [comment]
The fallback RID is not meant to guarantee binary compatibility for any OS. e.g. there are `linux-arm64` and `linux-mips64` also parented by `linux`.. so in case of fallback, the default x64 `linux` binary will definitely not work there.

> Android graph should match iOS here

If we examine the entire RID graph, we will see that it is actually iOS and tvOS that are at odds by not parented by OSX. It does not necessarily mean one approach is right and other one is wrong, it just shows that we are trying to achieve some concrete goals from the thing which does not guarantee them.

**Comment by ericstj** [comment]
> How do we prevent linux .so files from being added to their app? They will not work on Android.

Who are you to violate the contract of the package author?  The package author decided to include those files you can't just drop them.  What's the library going to do when it tries to load them?   This is a case of a package that needs to specialize for the new platform, we cannot do that for them.

**Comment by jonathanpeppers** [comment]
> The package author decided to include those files you can't just drop them.

In the example above, the app ends up with both Linux and Android `.so` files and unfortunately have the same file name. The NuGet package includes the `MonoAndroid` TFM for Xamarin.Android

The library author could update the package to support .NET 6, but it seems like this situation will happen frequently for users migrating from Xamarin.Android to .NET 6. We need to do _something_, maybe all we can do is give a good error message?

**Comment by ericstj** [comment]
>  the app ends up with both Linux and Android .so files 

How is this possible?  Is more than one package responsible for delivering the same component?   

I tried restoring that package for both net5.0 and monoandroid and I only see `libe_sqlite3.so` and it only comes from SQLitePCLRaw.lib.e_sqlite3.  So I'm not seeing this as anything more than SQLitePCLRaw.lib.e_sqlite3 didn't previously support android and needs an update to do so.  Am I missing something?

**Comment by jonathanpeppers** [comment]
I don't know why these packages are split up so much, but I see the Android native library coming from:

https://www.nuget.org/packages/SQLitePCLRaw.lib.e_sqlite3.android/

In this package, the native library is packed as an EmbeddedResource, which is removed and put in the right place in the Android app at build time. This implementation for native libraries was implemented in Xamarin early on. NuGet might not have existed (or hit popularity yet).

Either way, let's say the library author added a `net6.0-android` TFM with the native library to `SQLitePCLRaw.lib.e_sqlite3.android`. I think we would still hit the problem here, since the Linux package would continue to be pulled in from `SQLitePCLRaw.lib.e_sqlite3`?

**Comment by ericstj** [comment]
> let's say the library author added a net6.0-android TFM 

Native assets must be put in one of the native folders, so they'd need to either use `runtimes\android-<arch>\native` or `runtimes\android-<arch>\nativeassets\net6.0-android`; the latter is helpful if you need to scope the applicability to a TFM to constrain where the package applies.

If you placed the native SO binary in `lib\net6.0-android` it would be passed to the C# compiler, it wouldn't be considered by the `dotnet` host for PInvokes (if that's a concern) and there is no way to encode the architecture (if that is a concern).

If the author decided to provide the native binary in a different package, `SQLitePCLRaw.lib.e_sqlite3.android` then they could also update `SQLitePCLRaw.lib.e_sqlite3` to add a placeholder at `runtimes\android\native\_._` so that the `SQLitePCLRaw.lib.e_sqlite3` doesn't apply any assets to the android RID.  Same would be true if you decided to split up your TFM assets in multiple packages.

**Comment by jonathanpeppers** [comment]
Sorry, I mistyped, I should have put the RID `android-arm`, etc. instead of `net6.0-android`

What should we do here? Emit a nice error message if `linux-**\*.so` files are brought in?

**Comment by jonathanpeppers** [comment]
I think you would currently hit:

**Comment by ericstj** [comment]
Will the check be based off of scanning the binary?  If so then that seems fine.  If the check is based off checking the folder name it seems like it could have false positives.

**Comment by jonathanpeppers** [comment]
Closing this in favor of the latest changes in https://github.com/xamarin/xamarin-android/pull/5386

I added a new warning message that reports if `%(RuntimeIdentifier)` is not an Android platform and excludes the library.

**Pull request closed without merging**
