### PR TITLE
Revert "Improve Span.Reverse fast path performance"

### LINKED ISSUE #78604: Significant Reverse(ReadOnlySpan<byte>) performance regression for certain sizes
## Repro

Run `Reverse(ReadOnlySpan<byte>)` micro-benchmark (https://github.com/dotnet/performance/blob/c599f4c65e60ffe74c4c959ee02d1dddf551968e/src/benchmarks/micro/libraries/System.Memory/Span.cs#L44) for array size 33.

## Result

Current .NET 8 is about 1.6x slower compared to .NET 7 (AVX2 machine)

Introduced by https://github.com/dotnet/runtime/pull/70944/.

### PR DESCRIPTION
**Pull request by stephentoub**
Reverts dotnet/runtime#70944
Fixes https://github.com/dotnet/runtime/issues/78604
cc: @jkotas, @adamsitnik

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Are you able to reproduce the regression as well? (I just want to make sure this is not something that only reproduces for me before we revert it.)

**Comment by stephentoub** [comment]
> Are you able to reproduce the regression as well?

Yes.
```C#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;
using System.Linq;

public partial class Program
{
    static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);

    private byte[] _values = new byte[33];

    [Benchmark]
    public void Reverse() => _values.AsSpan().Reverse();
}
```

```
dotnet run -c Release -f net7.0 --filter ** --runtimes net7.0 --corerun d:\coreclrtest\main\corerun.exe
```

|  Method |        Job | Toolchain |     Mean |     Error |    StdDev | Ratio |
|-------- |----------- |---------- |---------:|----------:|----------:|------:|
| Reverse | Job-JJOFHY |   CoreRun | 4.125 ns | 0.0098 ns | 0.0087 ns |  1.39 |
| Reverse | Job-JFSVLH |    net7.0 | 2.969 ns | 0.0166 ns | 0.0139 ns |  1.00 |

**Comment by adamsitnik** [comment]
@jkotas thank you for reporting the regression.

@stephentoub @jkotas may I ask why you have decided to revert #70944 so quickly? I am not happy about this for multiple reasons:

- Reversing bytes is not on hot path and we are not close to the release, so we don't need hurry.
- As an owner of System.Memory I had no chance to react to the issue, neither the PR as it was opened on Saturday, and I don't work on weekends.
- It has caused a merge conflict in https://github.com/dotnet/runtime/pull/76076 which I've just solved on Friday to unblock @SwapnilGaikwad.

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/pull/70944#issuecomment-1321163943

**Comment by adamsitnik** [comment]
> back out the change as quickly as possible to get things back to a known state

I understand such approach when the CI is red, or we are regressing an IMPORTANT scenario. 

From my perspective you have caused a lot more work for me:

- I'll need to review a large nontrivial PR again.
- I'll need to solve the merge conflict again.
- I'll need to wait for the CI to complete at least twice.
- https://github.com/dotnet/runtime/pull/76076 is blocked again, I'll need to reach out to the contributor and explain the new current situation.

If I was given the time to react, I would just send a small PR with a fix for the bytes code path. It would take me half an hour including running the benchmarks.

**Comment by stephentoub** [comment]
Then you can revert the revert locally, without re-reviewing it, make the change as a commit on top of that, it won't take you any more time, it won't conflict, etc., and in the meantime we haven't incurred a perf regression that other things (like the very PR you're worried about conflicting) compounding the problems and making it harder to understand / investigate, causing noise and work for all the folks that manage interactions with the performance reporting system, etc.

**Comment by adamsitnik** [comment]
I could do that, but the contributor who contributed the PR has already started working on the fix: https://github.com/dotnet/runtime/pull/70944#issuecomment-1321166315

**Comment by stephentoub** [comment]
> the contributor who contributed the PR has already started working on the fix

That was a day ago, and you stated it would take you "half an hour including running the benchmarks".  If you really believe you would have a new PR up in 30 minutes from now, and it'll overall save you a lot of time, I suggest you do so, with thanks to @yesmey for their efforts.  If you don't want to do that, it still shouldn't take you a lot of time, as you can diff the previous commit with the new one and only review the difference, resulting in little additional work, and still minimal impact on the other PR you're concerned about.

**Comment by yesmey** [comment]
Didn't have time last night and I just got back from work :) Running the benchmarks now

**Comment by adamsitnik** [comment]
> causing noise and work for all the folks that manage interactions with the performance reporting system

There would be no noise as we were missing coverage for this code path. PTAL at https://github.com/dotnet/performance/pull/2748

**Comment by stephentoub** [comment]
> There would be no noise as we were missing coverage for this code path.

There are multiple uses of Array.Reverse and MemoryExtensions.Reverse throughout the codebase, including for bytes.

**Pull request merged**
