### PR TITLE
Fix handling SECBUFFER_EXTRA with renegotiation after handshake.

### LINKED ISSUE #91409: AuthenticateAsClientAsync can fail if renegotiation is requested immediately after handshake
full repro is here:  https://github.com/markalward/DotNet/tree/main/RenegotiateIssue
```
Unhandled exception. System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090330): The specified data could not be decrypted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken) in C:\Users\test\github\wfurt-runtime2\src\libraries\System.Net.Security\src\System\Net\Security\SslStream.IO.cs:line 336
   at RenegotiateIssue.Program.DoClientHandshakeAsync(String serverName, Int32 port) in C:\Users\test\github\DotNet\RenegotiateIssue\Program.cs:line 68
   at RenegotiateIssue.Program.DoClientHandshake(String serverName, Int32 port) in C:\Users\test\github\DotNet\RenegotiateIssue\Program.cs:line 43
   at RenegotiateIssue.Program.Main(String[] args) in C:\Users\test\github\DotNet\RenegotiateIssue\Program.cs:line 30
Server error: System.IO.IOException: The encryption operation failed, see inner exception.
```

The problem is that we can feed channel more frames at one and both original handshake and request to renegotiate come in as TLS handshake frames. When we combine them together, `AuthenticateAsClientAsync` fails to complete moving to renegotiation. That would not be big deal IMHO but that eventually fails with decryption error - this is Windows specific issue because the way how it is handled by schannel. 

One way how to fix is to revisit the logic that can feed more than one frame to PAL when available. That _could_ have some perf impact so it feels it would be beter to figure out what schannel is failing to decrypt.

### PR DESCRIPTION
**Pull request by rzikm**
Fixes #91409.

In case Renegotiation request arrives immediately after handshake, we may read it together with the ServerDone message, passing the Renegotiate message to `InitializeSecurityContext` would leave it unprocessed (and reported via `SECBUFFER_EXTRA`), but the existing code would attempt to feed it back into ISC, when the right thing to do is to pass it to `DecryptMessage` (as normal post-handshake data).

This PR bubbles up the amount of consumed bytes from InitializeSecurityContext and AcceptSecurityContext, so that the upper layer can decide where the extra data should go next (back to ISC/ASC if handshake is not yet finished, `DecryptMessage` if handshake is finished). It also adds unit tests (one of which fails without this change).

### CODE REVIEW

**Comment by wfurt** [comment]
I was originally wondering if we can do something here:

https://github.com/dotnet/runtime/blob/f8f450953d71dabe3fd01961c1d05b57c61e8faf/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.IO.cs#L850-L866

we treat it as opaque buffer but it is probably sequence of TLS frames...? 

This issue impacts only Windows IMHO so it would be nice to keep is scoped down.

**Comment by rzikm** [comment]
> we treat it as opaque buffer but it is probably sequence of TLS frames...?

The Renegotiate frame which causes the problem in this case is of type Handshake, so it cannot be distinguished from the tail end of the TLS handshake (`ChangeCipherSpec`, `Finished` and such).

> This issue impacts only Windows IMHO so it would be nice to keep is scoped down.

I tried to scope it down as much as possible, the Unix/OSX paths should behave the same way as before, the only change over there is the added out parameter which always reports that entire buffer passed in was processed.

I have some ideas how to refactor and simplify the Windows/Unix logic split, but I want to postpone them until early .NET 10.

**Review by wfurt — APPROVED** [review]
LGTM

**Pull request merged**
