### PR TITLE
Added generic EventArgs class

### PR DESCRIPTION
**Pull request by Hawkeye4040**
Added a generic event arguments class as mentioned in Issue [#49435](https://github.com/dotnet/runtime/issues/49435).

### CODE REVIEW

**Comment by huoyaoyuan** [comment]
Pull request is the **final** step of adding API. [API review](https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md) must be done first. Don't open a PR so early.

**Comment by Hawkeye4040** [comment]
I don't follow. I thought that submitting the PR was the step that then initiated API review. How do you review it without a PR to look at?

**Comment by huoyaoyuan** [comment]
> How do you review it without a PR to look at?

The api review is reviewing the shape first. Once the shape accepted, the implementation is reviewed in another pass. Sometimes implementation difficulty can result back in re-discussion of the shape.

**Most of the time, the implementation is trivial enough, like this one.** Discussion on the shape is important because we can't change it once shipped in a release version.

**Comment by Hawkeye4040** [comment]
Please define Shape in this specific context. I don't understand why the process varies here so much from elsewhere. Maybe I still don't follow but it seems like there's unnecessary steps in this process that conflict with how things typically work with Git. I have read over the docs on this and the one you linked also didn't really clear anything up for me and just kind of raised more questions if anything.

**Comment by huoyaoyuan** [comment]
The api shape is just the snippet you provided in your issue. It's enough.

**Comment by Hawkeye4040** [comment]
Oh okay I see what you mean by that now exactly. So essentially outline what we're proposing with that there first. Discuss it. Then at what point do you actually submit PR? I'd still work on it locally to make sure I have it right but I don't really see anything on that. I presume you'd say whether to submit PR during discussion then?

Typically in my own experience at least, PR's are done and commits are done updates, changes, etc. discussions occurring as the work happens, hence the confusion here.

**Pull request closed without merging**
