### PR TITLE
Garbage collect CoreLib resource strings

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Most seem to be orphaned after the deletion of Utf8String and built-in WinRT support.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Oh, seems like a lot of the garbage is Mono's garbage. Seems like after #2151 we embed garbage CoreCLR strings into Mono builds and garbage Mono strings into CoreCLR build.

The proper fix for that is still tracked in #7643. I'll bump that issue to .NET 6 and mark as linkable framework.

**Comment by MichalStrehovsky** [comment]
I re-ran the script (the one that Stephen created/ran a couple years ago), including Mono this time too. I manually excluded resources that are dynamically computed here:

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Private.CoreLib/src/System/Text/EncodingTable.cs#L241

**Comment by MichalStrehovsky** [comment]
@stephentoub @danmosemsft could you have a look?

**Review by stephentoub — APPROVED** [review]

**Comment by danmosemsft** [comment]
@MichalStrehovsky could you stick the script here or a gist for it, for future use?

Ideally we would eliminate the places we dynamically construct resource ID's in our tree, then we could trivially run this periodically on the tree. It was not hard to find other dead strings earlier this week, eg. https://github.com/dotnet/runtime/pull/46186

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky could you stick the script here or a gist for it, for future use?

It was this one: https://github.com/dotnet/coreclr/pull/18808#issuecomment-403097784

I just copied Mono's CoreLib into CoreCLR's directory and I have the symbolic links described here as well:

https://github.com/dotnet/runtime/blob/fcf0b8bb8001f72b6a25caa9daabe30c5c3b7558/.gitignore#L343-L351

**Pull request merged**
