### PR TITLE
[wasm] Move some defaults out of the templates

### LINKED ISSUE #72436: [wasm][wbt] - Microsoft.Playwright.PlaywrightException : net::ERR_UNSAFE_PORT
We probably allocate random port number.

During CI `Microsoft.Playwright.PlaywrightException : net::ERR_UNSAFE_PORT at http://localhost:5061/`
[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72275-merge-ffa6da6bb5f9444697/Workloads-.WasmTemplateTests/1/console.cd39eae8.log?helixlogtype=result)

More info 
chrome - https://superuser.com/questions/188006/how-to-fix-err-unsafe-port-error-on-chrome-when-browsing-to-unsafe-ports
FF - https://www-archive.mozilla.org/projects/netlib/portbanning#portlist

### PR DESCRIPTION
**Pull request by lewing**
Also fixes https://github.com/dotnet/runtime/issues/72436 .

### CODE REVIEW

**Review by radical — APPROVED** [review]

**Comment by pavelsavara** [comment]
I noticed that we now have console proxy in the production code
https://github.com/dotnet/runtime/blob/cbe29e860ec909121e8724503785cd5e2e6f5cb9/src/mono/wasm/runtime/debug.ts#L475

perhaps we could add it to `INTERNAL` and remove it from `test-main.js` and `app-support.js` now

**Comment by radical** [comment]
This is ready I believe.

**Comment by lewing** [comment]
Might be some follow up still but this is an improvement.

**Pull request merged**
