### PR TITLE
[LoongArch64] Fix some errors after the kernel supporting SIMD.

### PR DESCRIPTION
**Pull request by shushanhf**
This PR is part of the issue https://github.com/dotnet/runtime/issues/69705 to amend the LA's port.

Fix some errors after the kernel supporting SIMD.
Also preparing the context to implement the JIT-Intrinsics later.

### CODE REVIEW

**Review by shushanhf — COMMENTED** [review]
NOT REVIEWED before updated it.

**Comment by shushanhf** [comment]
Hi, @jakobbotsch 

Could you please review this PR?
Thanks

**Comment by shushanhf** [comment]
Hi, @jkotas 
Could you please review this PR ?
Thanks!

**Review by jkotas — APPROVED** [review]
LGTM

**Comment by shushanhf** [comment]
> LGTM

Ｔｈａｎｋｓ～

**Pull request merged**
