### PR TITLE
Build support for s390x: corehost

### PR DESCRIPTION
**Pull request by uweigand**
* Build the (non-Windows) host binaries with either runtime flavor

* s390x architecture support in get_arch utility

This allows building the host binaries including "dotnet" on s390x, where we only support the Mono runtime.  These hosts all build fine with either runtime, it seems they're just not build currently because there's no need to build them twice.

(I'm not sure the Windows hosts need to be under the RUNTIME_FLAVOR condition either, but I left them alone since I cannot test whether they actually build with Mono.)

### CODE REVIEW

**Comment by ericstj** [comment]
Can some host owners please review and sign off on this change?

**Review by vitek-karas — APPROVED** [review]
Sorry for such a late reply... 
Looks good to me. @Vsadov could you please take a look as well (if there are potential single-file related issues).

**Comment by uweigand** [comment]
As to the singlefilehost, this is no longer built ouf of the corehost directory, but out of coreclr.  This means it is not available on Mono -- this patch has no effect on that.  (If we wanted to support a Mono-based singlefilehost, that would require a much larger change, most likely mirroring the coreclr build process inside the mono directory.   That would in any case be an independent change.)

**Comment by uweigand** [comment]
Hi @vitek-karas @VSadov I was wondering if there is any news on this?   This PR is now the last missing piece blocking a successful build of the runtime on s390x, so if we could make progress here it would be much appreciated.  Thanks!

**Review by agocke — APPROVED** [review]
LGTM. With the refactoring moving the singlefilehost to coreclr I don't think this should run into any problems

**Pull request merged**
