### PR TITLE
JIT: Set default value for JitExtDefaultPolicyProfTrust 0

### PR DESCRIPTION
**Pull request by EgorBo**
The built-in profile works great for TE benchmarks, but regresses many micro-benchmarks if we decrease the benefit multiplier for cold blocks (with profile). Obviously, the micro benchmarks try to cover everything including blocks stated as cold by the built-in profile.
Example:
```
dotnet run -c Release -f net5.0 -- --coreRun %CORE_RUN% --filter "*CreateInstanceGeneric*"
```
Results:
```
|                Method |     Mean |
|---------------------- |---------:|
| CreateInstanceGeneric | 13.17 ns |
| CreateInstanceGeneric | 12.07 ns |  with JitExtDefaultPolicyProfTrust=0
```
In theory we can trust any profile that is not the built-in one (it's too generic) but I'm not sure we can determinate its source in JIT today.

Size regression for R2R'd corelib with `--Ot`: +0.2%

/cc @AndyAyersMS

### CODE REVIEW

**Comment by EgorBo** [comment]
Profile data for `System.RuntimeType.CreateInstanceOfT` (responsible for that ^ benchmark):
```
"Method": "[S.P.CoreLib]System.RuntimeType.CreateInstanceOfT()",
"InstrumentationData": [
  {
    "ILOffset": 0,
    "InstrumentationKind": "NumRuns",
    "Other": 7
  },
  {
    "ILOffset": 15,
    "InstrumentationKind": "EdgeIntCount",
    "Other": 29,
    "Data": 291
  },
  {
    "ILOffset": 37,
    "InstrumentationKind": "EdgeIntCount",
    "Other": 0,
    "Data": 0
  },
  {
    "ILOffset": 71,
    "InstrumentationKind": "EdgeIntCount",
    "Other": 0,
    "Data": 0
  },
  {
    "ILOffset": 79,
    "InstrumentationKind": "EdgeIntCount",
    "Other": 0,
    "Data": 5851
  }
]
```

**Comment by AndyAyersMS** [comment]
You can use `fgPgoSource` to distinguish static PGO from dynamic PGO, if that helps guide things more effectively. We might be able to extend this enum to distinguish our default static PGO from some user-collected static PGO.

**Comment by EgorBo** [comment]
> We might be able to extend this enum to distinguish our default static PGO from some user-collected static PGO.

@AndyAyersMS Yeah it would be nice to have, I guess the user-collected one would be the most truthful one. 
But as for now I'd like to merge it as is (I've had a round of TE benchmarks - no regressions) - does it look good?

**Review by AndyAyersMS — APPROVED** [review]
LGTM

**Pull request merged**
