### PR TITLE
riscv64 is now upstream Debian architecture

### PR DESCRIPTION
**Pull request by dkurt**
https://wiki.debian.org/RISC-V#Package_repository

```
sudo ./eng/common/cross/build-rootfs.sh riscv64 sid --rootfsdir ./riscv64-rootfs
```

### CODE REVIEW

**Comment by dkurt** [comment]
Is there a simple way to update it everywhere used in https://github.com/dotnet/dotnet/?

**Comment by dkurt** [comment]
@dotnet-policy-service agree

**Comment by am11** [comment]
Thanks! Please update it in the upstream repo: https://github.com/dotnet/arcade/tree/main/eng/common/native. It will automatically sync here in a few days.

ps - these scripts are technically "unused" in this repo except for someone trying to build a custom envionrment; they are ultimately used in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/ repo where we build the reuable docker images for CI as well as local dev environments.

**Comment by am11** [comment]
Thanks! Please update it in the upstream repo: https://github.com/dotnet/arcade/tree/main/eng/common/native. It will automatically sync here in a few days.

ps - these scripts are technically "unused" in this repo except for someone trying to build a custom environment; they are ultimately used in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/ repo where we build the reusable docker images for CI as well as local dev environments.

**Comment by Xinlong-Wu** [comment]
Could you provided the log `/home/dkurtaev/runtime/artifacts/obj/coreclr/linux.riscv64.Debug/CMakeFiles/CMakeError.log` ?

Besides, if you want to compile runtime for riscv64,
following may helps
```
# Creating rootfs
sudo  ./eng/common/cross/build-rootfs.sh riscv64 sid
export ROOTFS_DIR=<path to project>/.tools/rootfs/riscv64

# build runtime with mono
./build.sh mono+libs+host -c Debug --cross --arch riscv64

# of build runtime with CoreLR
./build.sh clr+libs+host -c Debug --cross --arch riscv64
```

But if you want to crate installable package like `dotnet-v8.0.0-riscv.tar.gz` may please reference to repo dotnet/dotnet

**Comment by dkurt** [comment]
@Xinlong-Wu, seems like https://github.com/dotnet/runtime/pull/96349#issuecomment-1871779917 is a future problem or I misconfigured somethind. The latest published Docker image works fine:
```
docker run --rm -it mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-cross-riscv64
```
```
export ROOTFS_DIR=/crossrootfs/riscv64/
./build.sh --arch riscv64 --os linux --cross
```
There is a different problem but I will try dotnet/dotnet, thanks!
```
/runtime/src/tools/illink/src/ILLink.Tasks/build/Microsoft.NET.ILLink.targets(138,5): error MSB6006: "dotnet" exited with code 134. [/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
/runtime/src/tools/illink/src/ILLink.Tasks/build/Microsoft.NET.ILLink.targets(91,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/runtime/src/coreclr/tools/aot/crossgen2/crossgen2_publish.csproj]
```

**Comment by Xinlong-Wu** [comment]
> ld.lld: error: /home/dkurtaev/runtime/riscv64-rootfs/lib/riscv64-linux-gnu/Scrt1.o:(.text+0x0): relocation R_RISCV_ALIGN requires unimplemented linker relaxation; recompile with -mno-relax
 
I found the problem, I am contributing the llvm too. your `ld.lld` might be outdate already. please update it and try it again if you want. `ld.lld` has implement linker relaxation at about 1 years ago. 

but at least image source should be update, please do that if you want.

**Comment by dkurt** [comment]
@Xinlong-Wu, sorry for bothering again. Can you please share your approach of cross compilation of dotnet? I managed to build `runtime`, but not a RISC-V RID with dotnet/dotnet. `packs` option during `runtime` build gives a number of nuget but not one of them contains a `dotnet` binary so I can run at least `dotnet -version`

**Pull request closed without merging**
