### PR TITLE
Unify macOS ARM64 write protection holders with W^X ones

### PR DESCRIPTION
**Pull request by janvorli**
This change removes the original holders that were added for changing
memory protection for executable code and moves the actual switching to
the recently added W^X holders.

The debugger code was verified using selected mdbg tests.

It also removes the operator new for allocating debugger executable memory. 
It was used at two places only and it is problematic for double mapped memory,
as the constructor needs the writeable mapping.

Contributes to #50391

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thanks

**Review by sdmaclea — APPROVED** [review]
LGTM Thanks

**Comment by janvorli** [comment]
All the failed legs are Linux MUSL and the failure is an unrelated known issue in a new test (#53836).

**Pull request merged**
