### PR TITLE
Remove unused DeviceIoControl P/Invoke declaration

### LINKED ISSUE #38861: src\libraries\Common\src\Interop\Windows\Kernel32\Interop.DeviceIoControl.cs appears to be a dead file
`src\libraries\Common\src\Interop\Windows\Kernel32\Interop.DeviceIoControl.cs` (and all other files related to `DeviceIoControl`) appear to be unused in dotnet/runtime.

It looks like they were introduced to support System.Data.SqlClient (dotnet/corefx#29879), but no longer used as Microsoft.Data.SqlClient is maintained in dotnet/SqlClient.

### PR DESCRIPTION
**Pull request by qmfrederik**
Closes #38861

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
If/when CI is green, LGTM.

**Comment by danmosemsft** [comment]
Opened https://github.com/dotnet/runtime/issues/38942 for the WASM failure.

**Comment by jkotas** [comment]
Could you please resolve the conflict?

**Comment by jkotas** [comment]
OSX machine hit a network issues.

**Comment by jkotas** [comment]
Thank you!

**Pull request merged**
