### PR TITLE
Remove pinning from string.GetNonRandomizedHashCode

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
Since `string.GetNonRandomizedHashCode` is a fairly hot method, and since the input strings can be in any GC generation and of any length, it seems prudent to remove pinning from this function. That way if a collection does occur the GC doesn't need to work around the fact that this object might be pinned.

The perf improvement here is insignificant. I clocked it at around only 1 ns on my box.

Note to reviewers: [hiding whitespace changes](https://github.com/dotnet/runtime/pull/31880/files?utf8=%E2%9C%93&diff=split&w=1) will make this easier to review.

### CODE REVIEW

**Comment by jkotas** [comment]
The GC is pretty good about dealing with short-term pinning. I do not think we should be changing a more readable code with pinning to less readable code without it just because of we can.

**Comment by Maoni0** [comment]
yeah I agree with Jan. you could get into a situation where you happen to be doing this on really large strings on many threads and GC does want to compact LOH but that's an extreme scenario. 

I'm mostly looking for scenarios where you are actually modifying string content which would be great to fix.

**Comment by GrabYourPitchforks** [comment]
Ok! Thanks for the context. :)

**Comment by GrabYourPitchforks** [comment]
@jkotas @Maoni0 If we could leave the call site readable, would it make sense to clean up some parts of `string` to move away from `wstrcpy` and toward `MemoryMove(ref char, ref char, ...)`? See for example the below ctor.

https://github.com/dotnet/runtime/blob/0f3f8e1930c28b67f29990126bc2e8527e959a2e/src/libraries/System.Private.CoreLib/src/System/String.cs#L55-L67

That copy can be written as `Buffer.Memmove(ref result._firstChar, ref value.GetRawArrayData(), value.Length)`, which still maintain readability while providing codegen improvements for this method.

**Comment by benaadams** [comment]
Probably since `wstrcpy` just forwards to `Buffer.Memmove`

https://github.com/dotnet/runtime/blob/a80e6d4c69fcfa1e17e17130c144a567b23a12a9/src/libraries/System.Private.CoreLib/src/System/String.cs#L512-L515

**Comment by jkotas** [comment]
>  it make sense to clean up some parts of string to move away from wstrcpy and toward `Memmove(ref char, ref char, ...)`

I would be fine with that as long as it does not measurably regress performance. IIRC, `Memmove(ref char, ref char, ...)` has higher overhead than `Memmove(void*, void*, ...)`

**Pull request closed without merging**
