### PR TITLE
Re-add S.T.J.SourceGeneration.UnitTests to STJ sln

### PR DESCRIPTION
**Pull request by layomia**
Looks like it was dropped in https://github.com/dotnet/runtime/pull/56430.

### CODE REVIEW

**Review by eiriktsarpalis — APPROVED** [review]

**Comment by ViktorHofer** [comment]
That's not really a sustainable solution. They will again be dropped with the next solution file format. I will add the corresponding infra to prevent that into the PR, hope that's ok.

**Review by ViktorHofer — APPROVED** [review]

**Comment by eiriktsarpalis** [comment]
@ViktorHofer I wasn't aware that sln files were being regenerated. How can we make sure that other projects are not being dropped as well?

**Comment by ViktorHofer** [comment]
The slngen.template.proj is used traverse through a leaf directory and include all projects that matches the glob pattern. We are probably missing source generators / analyzers and should add them as well. Are you aware of any other type of project that we might be missing?

Also note that https://github.com/dotnet/runtime/pull/56494 will fix a few project files which are missing some reference projects.

**Comment by eiriktsarpalis** [comment]
> Are you aware of any other type of project that we might be missing?

Not that I know of, but I think there is risk of current or future projects being unexpectedly dropped from solution files because they happen to not match these particular glob patterns. Is there anything we could do to prevent this from happening?

**Comment by eiriktsarpalis** [comment]
Build errors seem unrelated, merging away!

**Comment by ViktorHofer** [comment]
> Not that I know of, but I think there is risk of current or future projects being unexpectedly dropped from solution files because they happen to not match these particular glob patterns. Is there anything we could do to prevent this from happening?

I would not expect a project to have any other structure than that. Our build system would need to support it otherwise explicitly. In example, the source project needs to be located under a "src" parent folder, same for ref and for test projects.

We are aiming towards a minimal diff when updating solution files which should then make any projects being dropped more visible.

**Comment by ViktorHofer** [comment]
> Build errors seem unrelated, merging away!

@eiriktsarpalis in future PRs please add a comment with links to issues in the PR legs. In this case it would be:
- https://github.com/dotnet/runtime/issues/55449
- https://github.com/dotnet/runtime/issues/56894

The second issue demonstrates the importance of filing issue for CI failures. @adamsitnik started working on a fix after the issue was filed.

I definitely feel the frustration about the current flakiness in the CI. This comment is meant as constructive feedback so that we can all work together on stabilizing CI and no as finger pointing.

**Pull request merged**
