### PR TITLE
move File.Exists and File.ReadAllBytes to Common

### PR DESCRIPTION
**Pull request by adamsitnik**
I wanted to start working on `File.OpenHandle` which is part of https://github.com/dotnet/runtime/issues/24847#issuecomment-840789333

and then I realized that we have a copy of `File.Exists` and `File.ReadAllBytes` in `System.Private.CoreLib` which was promised to keep in sync with `System.File.IO`:

https://github.com/dotnet/runtime/blob/d1a0a20f9d54694904e42c35edee09de4509040a/src/libraries/System.Private.CoreLib/src/Internal/IO/File.cs#L10-L16

The problem is that it was not kept in sync. The differences:

* lack of `TrimEndingDirectorySeparator` for `File.Exists` 
   * on Unix: 
      * [System.IO.FileSystem](https://github.com/dotnet/runtime/blob/d1a0a20f9d54694904e42c35edee09de4509040a/src/libraries/System.IO.FileSystem/src/System/IO/FileSystem.Exists.Unix.cs#L32)
      * [System.Private.CoreLib](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/Internal/IO/File.Unix.cs)
   * on Windows:
      * [System.IO.FileSystem](https://github.com/dotnet/runtime/blob/d1a0a20f9d54694904e42c35edee09de4509040a/src/libraries/Common/src/System/IO/FileSystem.Attributes.Windows.cs#L58-L59)
      * [System.Private.CoreLib](https://github.com/dotnet/runtime/blob/d1a0a20f9d54694904e42c35edee09de4509040a/src/libraries/System.Private.CoreLib/src/Internal/IO/File.Windows.cs#L27-L29)
* lack of support for file systems that don't report file length for non-empty files for `File.ReadAllBytes`:
   * [System.IO.FileSystem](https://github.com/dotnet/runtime/blob/d1a0a20f9d54694904e42c35edee09de4509040a/src/libraries/System.IO.FileSystem/src/System/IO/File.cs#L335-L346)
   * [System.Private.CoreLib](https://github.com/dotnet/runtime/blob/d1a0a20f9d54694904e42c35edee09de4509040a/src/libraries/System.Private.CoreLib/src/Internal/IO/File.cs#L57-L59)

I moved it to `Common` so we have a single implementation and no code duplication now.

### CODE REVIEW

**Comment by jkotas** [comment]
> lack of TrimEndingDirectorySeparator for File.Exists
> lack of support for file systems that don't report file length for non-empty files for File.ReadAllBytes

CoreLib uses these two APIs for specific purpose where we do not need any of this. You can add a comment to CoreLib copy that this is missing instead of increasing the amount of duplicated code.

Instead of this, it may be better to fold System.IO.FileSystem into CoreLib (contributes to #2138). @marek-safar asked me about it a while ago. System.IO.FileSystem has a dependency on Linq that would need to be cleaned up before it can be done.

**Comment by jkotas** [comment]
> I moved it to Common so we have a single implementation and no code duplication now.

We still have the code duplicated in binaries, and more of it than before.

**Comment by adamsitnik** [comment]
@jkotas I like the idea of folding `System.IO.FileSystem` into `System.Private.CoreLib`. It would definitely make my life easier. I am going to give it a try.

**Comment by carlossanlop** [comment]
@jkotas Why move the whole FileSystem namespace to CoreLib? If Linq has dependencies to FileSystem types, can't we instead move only the types that are needed? For example, `FileStream` and `Path` live in Corelib and are typeforwarded to FileSystem.

I'm interested in knowing the reasoning to move the whole namespace. cc @ericstj

**Comment by jkotas** [comment]
I think that the file and directory enumeration APIs that exist in System.IO.FileSystem.dll really belong to CoreLib.

Note that we have a parallel implementation of file and directory enumeration APIs in CoreCLR PAL (https://github.com/dotnet/runtime/blob/main/src/coreclr/pal/src/file/find.cpp). We are not able to do C# rewrite of the logic that depends on these since the managed file and directory enumeration APIs do not live in CoreLib. Once we move the the managed file and directory enumeration APIs to CoreLib, we will be one stop closer to be able to rewrite a bunch more runtime code in C#.

> Linq

Use of Linq in System.IO as anti-pattern. We try to avoid use Linq at the lower levels of the stack since it has large performance overhead. I would be good to get rid of Linq in System.IO regardless.

**Pull request closed without merging**
