### PR TITLE
[release/8.0] Fix NegotiateStream connections between Linux clients and Windows servers

### LINKED ISSUE #99227: NET8 WcfClient (net-tcp binding) running on linux cannot be authenticated on WCF Server hosted on windows if UseManagedNtlm is set
### Description

Hello!
I found problem while trying to connect to WCF service hosted on Windows over net-tcp connection using WCF client on linux with windows local user credentials. Problem occurs just when switch System.Net.Security.UseManagedNtlm is set to true. Otherwise it working on ubuntu 20.04. On ubuntu 22.04 and higher there is known issue with OpenSSL 3+ (see https://github.com/dotnet/runtime/issues/67353) and in this case it working just with workaround described here https://github.com/dotnet/runtime/issues/67353#issuecomment-1085003764.

I also tried to apply fix from https://github.com/dotnet/runtime/issues/95725 but it doesn't work for me.
Is it any chance to get fix for this problem on net8?

### Reproduction Steps

Here is repository with reproduction solution and steps: https://github.com/AlexanderUsmanov/WcfClientNet8-issue

### Expected behavior

Managed NTLM working

### Actual behavior

Managed NTLM failing

### Regression?

_No response_

### Known Workarounds

Use unmanaged implementation which working just in case of OpenSSL version < 3.0 (because in OpenSSL with version 3 and higher md4 was marked as deprecated).

### Configuration

Client:
- .Net version: Net8
- OS: ubuntu 20.04
- Architecture: x64

Server:
- .Net version: Net Framework 4.7.2
- OS: Windows 10
- Architecture: x64

WCF binding: net-tcp

### Other information

I have captures of traffic using both managed and unmanaged ntlm authentication over net-tcp
[Captures.zip](https://github.com/dotnet/runtime/files/14473503/Captures.zip)

### PR DESCRIPTION
**Pull request by rzikm**
Manual backport of #99909

Fixes #99227

## Customer Impact

Reported by customer via official support channel - they need same behavior on Linux, which works also on Windows and on .NET Framework.

Customers were facing issues when connecting from Linux to Windows when using the `ProtectionLevel.EncryptAndSign` value as `NegotiateAuthenticationClientOptions.RequiredProtectionLevel`. This scenario is common when connecting to WCF services hosted on Windows using WCF clients on Linux.

The bug affects primarily Android clients -- that is where the Managed NTLM implementation is used. We also allow the Managed NTLM as opt-in on macOS and Linux which would be likewise affected if the developer chooses to enable the `System.Net.Security.UseManagedNtlm` app context switch (which is rare).

## Regression

No

## Testing

Unit test was added. Validated by customer who reported the issue via official servicing channel.

## Risk

Low; the modified code path is in platform specific code for a single authentication scheme. There is test coverage for the change.

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM. Assuming this does not depend on any other 9.0 fixes.
cc: @filipnavara

**Comment by filipnavara** [comment]
This one is isolated. I would also like to backport the PR that fixed calculation of channel binding.

**Comment by rzikm** [comment]
/ba-g Test failure is https://github.com/dotnet/runtime/issues/96407

**Comment by wfurt** [comment]
approved via email

**Pull request merged**
