### PR TITLE
[wasm] bump npm packages, fix lint errors

### PR DESCRIPTION
**Pull request by pavelsavara**
Bit broader than https://github.com/dotnet/runtime/pull/72528

### CODE REVIEW

**Comment by pavelsavara** [comment]
`npm ci` died with 
```
  npm ERR! code E401
  npm ERR! Unable to authenticate, your authentication token seems to be invalid.
  npm ERR! To correct this please trying logging in again with:
  npm ERR!     npm login
 ```
It's probably related to `src\mono\wasm\runtime\.npmrc` pointing to `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public-npm/npm/registry/`

But anyway, I have no idea.
@radekdoulik @radical could you please help ?

**Comment by pavelsavara** [comment]
I compared `dotnet.js` in both Release and Debug config. There are only cosmetic changes.

**Comment by maraf** [comment]
> could you please help ?

Here are some instructions how to authenticate
https://github.com/dotnet/runtime/pull/71393#issuecomment-1169312539

**Comment by lewing** [comment]
wait, the npm registry changes mean that anyone trying to build wasm has to generate a azdo PAT and auth npm now?

**Review by lewing — APPROVED** [review]

**Comment by pavelsavara** [comment]
> wait, the npm registry changes mean that anyone trying to build wasm has to generate an azdo PAT and auth npm now?

No, just the one who needs to add new packages to AzDO repo (working as a cache i guess).

**Pull request merged**
