### PR TITLE
Add ARM64 encodings for group IF_SVE_BH_3A,3B,3B_A

### PR DESCRIPTION
**Pull request by snickolls-arm**
Covers encodings for a few SVE variants of the `adr` instruction.

Matching capstone output:
```
adr z4.d, [z2.d, z0.d]
adr z29.s, [z1.s, z10.s, lsl #1]
adr z9.d, [z7.d, z9.d, sxtw]
adr z12.d, [z3.d, z5.d, sxtw #2]
adr z9.d, [z10.d, z14.d, uxtw]
adr z3.d, [z15.d, z11.d, uxtw #3]
```

Contributing towards #94549.

### CODE REVIEW

**Review by a74nh — APPROVED** [review]
Otherwise, LGTM

(EDIT: Didn't mean to approve until the change is made)

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by kunalspathak** [comment]
@snickolls-arm - can you please pull the latest `main` and merge them?

**Comment by kunalspathak** [comment]
superpmi failures seems to be infra issue.

**Pull request merged**
