### PR TITLE
[Pipelines] Noop Writes when Reader completed

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Comment by davidfowl** [comment]
What happens when you call GetMemory() and Advance()? Then call flush ? Does it properly return the blocks?

**Comment by jkotalik** [comment]
Was the behavior throwing before?

**Comment by davidfowl** [comment]
> Was the behavior throwing before?

Nope.

**Comment by BrennanConroy** [comment]
Guess we need to merge to master before trying to backport.

**Review by halter73 — APPROVED** [review]

**Review by davidfowl — APPROVED** [review]

**Comment by danmosemsft** [comment]
test failure is unrelated - https://github.com/dotnet/runtime/issues/40886

**Pull request merged**
