### PR TITLE
Ensure NI_Vector128_AsVector128 (aka `Vector128<T> AsVector128(this Vector<T> value)`) doesn't have a side-effect in its assert

### LINKED ISSUE #76347: Failures in checked/release asm diffs
Pipeline https://dev.azure.com/dnceng-public/public/_build/results?buildId=29308&view=results has been reporting failures, that need to be investigated.

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/76347

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @BruceForstall, @dotnet/jit-contrib

**Comment by tannergooding** [comment]
This bug also exists in .NET 6

**Review by BruceForstall — APPROVED** [review]
Good find!

I suppose this could have been avoided by not re-using the `simdSize` argument as what is really a `argumentSimdSize` value. btw, `simdSize` isn't documented in the function header.

LGTM

**Comment by BruceForstall** [comment]
(btw, this contributes to https://github.com/dotnet/runtime/issues/76347, but doesn't fully resolve it. I have other changes to the test running infrastructure that will do the rest of the work)

**Comment by BruceForstall** [comment]
@tannergooding Do you think this fix should be ported back to .NET 7? .NET 6? What kind of bad codegen implications are there with the unfixed code? Presumably `Vector<T> v = ...; v.AsVector128();` could give incorrect results?

Does a complete fix also require some (or all) of https://github.com/dotnet/runtime/pull/76456?

**Comment by tannergooding** [comment]
> Does a complete fix also require some (or all) of https://github.com/dotnet/runtime/pull/76456?

No. That's independent and just helps ensure codegen is better it should have any impact on the correctness of the codegen.

> Do you think this fix should be ported back to .NET 7? .NET 6? What kind of bad codegen implications are there with the unfixed code? Presumably Vector<T> v = ...; v.AsVector128(); could give incorrect results?

Its probably better to take it than not given its a 1 line fix putting it back inline with .NET Core 3.1 and .NET 5. That being said, I don't think users will see any negative side effects from us doing nothing...

The impact here is that on a system with AVX2 support (which I'd presume is a majority) a user calling vector.AsVector128 will get treated as a "nop" and the value will be consumed directly. Whether that's coming from memory or a register should be fine since the memory slot will be 32-bytes or we'll preserve the 32-bit register.

The potential negative would be if CSE or another optimization tries to look at this local and sees TYP_SIMD32 when it should see TYP_SIMD16. However, I'm not aware of any code that would be directly impacted by that...

**Comment by BruceForstall** [comment]
The superpmi-replay failure looks like a timeout. We've had a few of those lately and need to investigate (separately).

**Comment by tannergooding** [comment]
@BruceForstall, should I go ahead and backport this to 7.0 and go through the approval process? What about 6.0?

@SingleAccretion or @EgorBo might have a better idea if there is potential CSE impact here.

**Comment by BruceForstall** [comment]
I would suggest trying to get it in 7.0, since it is silent bad codegen. However, your description of the impact indicates there really is no impact, so that might not persuade the approvers.

**Comment by BruceForstall** [comment]
One argument for porting it is it will (help) clean up our checked/release asm diffs testing on 7.0, so it could be argued it is a benefit to testing.

**Pull request merged**
