### PR TITLE
SPMI: Hacky workaround for coredistools unsupported instructions

### PR DESCRIPTION
**Pull request by jakobbotsch**
We currently are unable to get SPMI diffs for methods that use ldapur
instructions as our current coredistools does not support this
instruction. While we wait for coredistools to be updated (this was
blocked on some C++ lib issues) here is a hacky temporary workaround for
the problem. It rewrites ldapur* instructions into the corresponding
ldur* instruction before passing it to the near differ.

### CODE REVIEW

**Review by BruceForstall — APPROVED** [review]
That's quite a hack :-)

It would be useful to add a comment about why this code is there, and what it is trying to do. Maybe link to an issue (or two) indicating how it should be ultimately fixed (and the issue can point out to remove this code after coredistools is updated).

**Comment by BruceForstall** [comment]
@jakobbotsch Are you planning to merge this?

I wonder if it's contributing to the checked/release asm diffs failures, e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=401020&view=logs&j=83516c17-6666-5250-abde-63983ce72a49

```
[12:01:32] ERROR: main method 251769 of size 95 failed to load and compile correctly.
[12:01:32] ERROR: Unexpected exception c0000005 was thrown.
... many more
```

**Comment by jakobbotsch** [comment]
> @jakobbotsch Are you planning to merge this?
> 
> I wonder if it's contributing to the checked/release asm diffs failures, e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=401020&view=logs&j=83516c17-6666-5250-abde-63983ce72a49
> 
> ```
> [12:01:32] ERROR: main method 251769 of size 95 failed to load and compile correctly.
> [12:01:32] ERROR: Unexpected exception c0000005 was thrown.
> ... many more
> ```

Done. Yeah, I think the AV could be related. I would expect it to be fixed either by this or #91783

**Comment by jakobbotsch** [comment]
Looks like the x64 run passed, but the x86 run timed out. I think I forgot to increase the imtout of superpmi-asmdiffs-checked-release in #91637.

**Comment by BruceForstall** [comment]
The console logs are odd, though: they finish at the end of the download phase, after less than 10 minutes, with no evidence the replay/run phase even started.

**Comment by jakobbotsch** [comment]
> The console logs are odd, though: they finish at the end of the download phase, after less than 10 minutes, with no evidence the replay/run phase even started.

`run_command` only logs the output of the sub command once it has finished. If the run gets terminated during `run_command` then it is not logged to stdout. This is what confused me the other day when we were investigating the timeouts as well -- you have to download the log files from artifacts to see the output. For the win-x86 run that output is:

```
[14:51:30] ================ Logging to C:\h\w\B34A09AB\w\AA5D098E\uploads\superpmi_windows_x86.log
[14:51:30] Using mcs.exe from Core_Root: C:\h\w\B34A09AB\p\mcs.exe
[14:51:30] Using JIT/EE Version from mcs: a2974440-e8ee-4d95-9e6e-799a330be1a0
[14:51:30] Download: https://clrjit2.blob.core.windows.net/superpmi/libcoredistools/windows-x86/coredistools.dll -> C:\h\w\B34A09AB\p\coredistools.dll
[14:51:31] Found download cache directory "C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86" and --force_download not set; skipping download
[14:51:41] SuperPMI ASM diffs
[14:51:41] ------------------------------------------------------------
[14:51:41] Start time: 14:51:41
[14:51:41] Diff between Checked and Release.
[14:51:41] Base JIT Path: C:\h\w\B34A09AB\p\base\clrjit_win_x86_x86.dll
[14:51:41] Diff JIT Path: C:\h\w\B34A09AB\p\diff\clrjit_win_x86_x86.dll
[14:51:41] Using MCH files:
[14:51:41]   C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\benchmarks.run.windows.x86.checked.mch
[14:51:41]   C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\benchmarks.run_pgo.windows.x86.checked.mch
[14:51:41]   C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\benchmarks.run_tiered.windows.x86.checked.mch
[14:51:41]   C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\coreclr_tests.run.windows.x86.checked.mch
[14:51:41]   C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries.crossgen2.windows.x86.checked.mch
[14:51:41]   C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries.pmi.windows.x86.checked.mch
[14:51:41]   C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries_tests.pmi.windows.x86.checked.mch
[14:51:41]   C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries_tests.run.windows.x86.Release.mch
[14:51:41]   C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries_tests_no_tiered_compilation.run.windows.x86.Release.mch
[14:51:41]   C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\realworld.run.windows.x86.checked.mch
[14:51:41] Using superpmi.exe from Core_Root: C:\h\w\B34A09AB\p\superpmi.exe
[14:51:41] 
[14:51:41] Temp Location: C:\h\w\B34A09AB\t\tmp8emfgz3_
[14:51:41] 
[14:51:41] Running asm diffs of C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\benchmarks.run.windows.x86.checked.mch
[14:51:41] Invoking: C:\h\w\B34A09AB\p\superpmi.exe -a -v ewi -f C:\h\w\B34A09AB\t\tmp8emfgz3_\benchmarks.run.windows.x86.checked.mch_fail.mcl -diffsInfo C:\h\w\B34A09AB\t\tmp8emfgz3_\benchmarks.run.windows.x86.checked.mch_diffs.csv -r C:\h\w\B34A09AB\t\tmp8emfgz3_\repro -baseMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\benchmarks.run.windows.x86.checked.mch_base_metrics.csv -diffMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\benchmarks.run.windows.x86.checked.mch_diff_metrics.csv -jitoption force JitAlignLoops=0 -jitoption force JitEnableNoWayAssert=1 -jitoption force JitNoForceFallback=1 -jit2option force JitAlignLoops=0 -jit2option force JitEnableNoWayAssert=1 -jit2option force JitNoForceFallback=1 -p -failureLimit 100 -ignoreStoredConfig C:\h\w\B34A09AB\p\base\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\diff\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\benchmarks.run.windows.x86.checked.mch
[14:52:44] Clean SuperPMI diff (24524 contexts processed)
[14:52:44] Running asm diffs of C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\benchmarks.run_pgo.windows.x86.checked.mch
[14:52:44] Invoking: C:\h\w\B34A09AB\p\superpmi.exe -a -v ewi -f C:\h\w\B34A09AB\t\tmp8emfgz3_\benchmarks.run_pgo.windows.x86.checked.mch_fail.mcl -diffsInfo C:\h\w\B34A09AB\t\tmp8emfgz3_\benchmarks.run_pgo.windows.x86.checked.mch_diffs.csv -r C:\h\w\B34A09AB\t\tmp8emfgz3_\repro -baseMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\benchmarks.run_pgo.windows.x86.checked.mch_base_metrics.csv -diffMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\benchmarks.run_pgo.windows.x86.checked.mch_diff_metrics.csv -jitoption force JitAlignLoops=0 -jitoption force JitEnableNoWayAssert=1 -jitoption force JitNoForceFallback=1 -jit2option force JitAlignLoops=0 -jit2option force JitEnableNoWayAssert=1 -jit2option force JitNoForceFallback=1 -p -failureLimit 100 -ignoreStoredConfig C:\h\w\B34A09AB\p\base\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\diff\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\benchmarks.run_pgo.windows.x86.checked.mch
[14:56:35] Clean SuperPMI diff (112344 contexts processed)
[14:56:35] Running asm diffs of C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\benchmarks.run_tiered.windows.x86.checked.mch
[14:56:35] Invoking: C:\h\w\B34A09AB\p\superpmi.exe -a -v ewi -f C:\h\w\B34A09AB\t\tmp8emfgz3_\benchmarks.run_tiered.windows.x86.checked.mch_fail.mcl -diffsInfo C:\h\w\B34A09AB\t\tmp8emfgz3_\benchmarks.run_tiered.windows.x86.checked.mch_diffs.csv -r C:\h\w\B34A09AB\t\tmp8emfgz3_\repro -baseMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\benchmarks.run_tiered.windows.x86.checked.mch_base_metrics.csv -diffMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\benchmarks.run_tiered.windows.x86.checked.mch_diff_metrics.csv -jitoption force JitAlignLoops=0 -jitoption force JitEnableNoWayAssert=1 -jitoption force JitNoForceFallback=1 -jit2option force JitAlignLoops=0 -jit2option force JitEnableNoWayAssert=1 -jit2option force JitNoForceFallback=1 -p -failureLimit 100 -ignoreStoredConfig C:\h\w\B34A09AB\p\base\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\diff\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\benchmarks.run_tiered.windows.x86.checked.mch
[14:57:14] Clean SuperPMI diff (47246 contexts processed)
[14:57:14] Running asm diffs of C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\coreclr_tests.run.windows.x86.checked.mch
[14:57:14] Invoking: C:\h\w\B34A09AB\p\superpmi.exe -a -v ewi -f C:\h\w\B34A09AB\t\tmp8emfgz3_\coreclr_tests.run.windows.x86.checked.mch_fail.mcl -diffsInfo C:\h\w\B34A09AB\t\tmp8emfgz3_\coreclr_tests.run.windows.x86.checked.mch_diffs.csv -r C:\h\w\B34A09AB\t\tmp8emfgz3_\repro -baseMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\coreclr_tests.run.windows.x86.checked.mch_base_metrics.csv -diffMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\coreclr_tests.run.windows.x86.checked.mch_diff_metrics.csv -jitoption force JitAlignLoops=0 -jitoption force JitEnableNoWayAssert=1 -jitoption force JitNoForceFallback=1 -jit2option force JitAlignLoops=0 -jit2option force JitEnableNoWayAssert=1 -jit2option force JitNoForceFallback=1 -p -failureLimit 100 -ignoreStoredConfig C:\h\w\B34A09AB\p\base\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\diff\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\coreclr_tests.run.windows.x86.checked.mch
[15:11:03] SuperPMI encountered missing data. Missing with base JIT: 433. Missing with diff JIT: 433. Total contexts: 558399.
[15:11:03] Running asm diffs of C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries.crossgen2.windows.x86.checked.mch
[15:11:03] Invoking: C:\h\w\B34A09AB\p\superpmi.exe -a -v ewi -f C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries.crossgen2.windows.x86.checked.mch_fail.mcl -diffsInfo C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries.crossgen2.windows.x86.checked.mch_diffs.csv -r C:\h\w\B34A09AB\t\tmp8emfgz3_\repro -baseMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries.crossgen2.windows.x86.checked.mch_base_metrics.csv -diffMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries.crossgen2.windows.x86.checked.mch_diff_metrics.csv -jitoption force JitAlignLoops=0 -jitoption force JitEnableNoWayAssert=1 -jitoption force JitNoForceFallback=1 -jit2option force JitAlignLoops=0 -jit2option force JitEnableNoWayAssert=1 -jit2option force JitNoForceFallback=1 -p -failureLimit 100 -ignoreStoredConfig C:\h\w\B34A09AB\p\base\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\diff\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries.crossgen2.windows.x86.checked.mch
[15:13:33] Clean SuperPMI diff (270473 contexts processed)
[15:13:33] Running asm diffs of C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries.pmi.windows.x86.checked.mch
[15:13:33] Invoking: C:\h\w\B34A09AB\p\superpmi.exe -a -v ewi -f C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries.pmi.windows.x86.checked.mch_fail.mcl -diffsInfo C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries.pmi.windows.x86.checked.mch_diffs.csv -r C:\h\w\B34A09AB\t\tmp8emfgz3_\repro -baseMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries.pmi.windows.x86.checked.mch_base_metrics.csv -diffMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries.pmi.windows.x86.checked.mch_diff_metrics.csv -jitoption force JitAlignLoops=0 -jitoption force JitEnableNoWayAssert=1 -jitoption force JitNoForceFallback=1 -jit2option force JitAlignLoops=0 -jit2option force JitEnableNoWayAssert=1 -jit2option force JitNoForceFallback=1 -p -failureLimit 100 -ignoreStoredConfig C:\h\w\B34A09AB\p\base\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\diff\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries.pmi.windows.x86.checked.mch
[15:17:53] SuperPMI encountered missing data. Missing with base JIT: 2. Missing with diff JIT: 2. Total contexts: 300565.
[15:17:53] Running asm diffs of C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries_tests.pmi.windows.x86.checked.mch
[15:17:53] Invoking: C:\h\w\B34A09AB\p\superpmi.exe -a -v ewi -f C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries_tests.pmi.windows.x86.checked.mch_fail.mcl -diffsInfo C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries_tests.pmi.windows.x86.checked.mch_diffs.csv -r C:\h\w\B34A09AB\t\tmp8emfgz3_\repro -baseMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries_tests.pmi.windows.x86.checked.mch_base_metrics.csv -diffMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries_tests.pmi.windows.x86.checked.mch_diff_metrics.csv -jitoption force JitAlignLoops=0 -jitoption force JitEnableNoWayAssert=1 -jitoption force JitNoForceFallback=1 -jit2option force JitAlignLoops=0 -jit2option force JitEnableNoWayAssert=1 -jit2option force JitNoForceFallback=1 -p -failureLimit 100 -ignoreStoredConfig C:\h\w\B34A09AB\p\base\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\diff\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries_tests.pmi.windows.x86.checked.mch
[15:25:31] Clean SuperPMI diff (360473 contexts processed)
[15:25:31] Running asm diffs of C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries_tests.run.windows.x86.Release.mch
[15:25:31] Invoking: C:\h\w\B34A09AB\p\superpmi.exe -a -v ewi -f C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries_tests.run.windows.x86.Release.mch_fail.mcl -diffsInfo C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries_tests.run.windows.x86.Release.mch_diffs.csv -r C:\h\w\B34A09AB\t\tmp8emfgz3_\repro -baseMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries_tests.run.windows.x86.Release.mch_base_metrics.csv -diffMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries_tests.run.windows.x86.Release.mch_diff_metrics.csv -jitoption force JitAlignLoops=0 -jitoption force JitEnableNoWayAssert=1 -jitoption force JitNoForceFallback=1 -jit2option force JitAlignLoops=0 -jit2option force JitEnableNoWayAssert=1 -jit2option force JitNoForceFallback=1 -p -failureLimit 100 -ignoreStoredConfig C:\h\w\B34A09AB\p\base\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\diff\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries_tests.run.windows.x86.Release.mch
[15:35:33] Clean SuperPMI diff (629064 contexts processed)
[15:35:33] Running asm diffs of C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries_tests_no_tiered_compilation.run.windows.x86.Release.mch
[15:35:33] Invoking: C:\h\w\B34A09AB\p\superpmi.exe -a -v ewi -f C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries_tests_no_tiered_compilation.run.windows.x86.Release.mch_fail.mcl -diffsInfo C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries_tests_no_tiered_compilation.run.windows.x86.Release.mch_diffs.csv -r C:\h\w\B34A09AB\t\tmp8emfgz3_\repro -baseMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries_tests_no_tiered_compilation.run.windows.x86.Release.mch_base_metrics.csv -diffMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\libraries_tests_no_tiered_compilation.run.windows.x86.Release.mch_diff_metrics.csv -jitoption force JitAlignLoops=0 -jitoption force JitEnableNoWayAssert=1 -jitoption force JitNoForceFallback=1 -jit2option force JitAlignLoops=0 -jit2option force JitEnableNoWayAssert=1 -jit2option force JitNoForceFallback=1 -p -failureLimit 100 -ignoreStoredConfig C:\h\w\B34A09AB\p\base\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\diff\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\libraries_tests_no_tiered_compilation.run.windows.x86.Release.mch
[15:43:24] Clean SuperPMI diff (313486 contexts processed)
[15:43:24] Running asm diffs of C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\realworld.run.windows.x86.checked.mch
[15:43:24] Invoking: C:\h\w\B34A09AB\p\superpmi.exe -a -v ewi -f C:\h\w\B34A09AB\t\tmp8emfgz3_\realworld.run.windows.x86.checked.mch_fail.mcl -diffsInfo C:\h\w\B34A09AB\t\tmp8emfgz3_\realworld.run.windows.x86.checked.mch_diffs.csv -r C:\h\w\B34A09AB\t\tmp8emfgz3_\repro -baseMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\realworld.run.windows.x86.checked.mch_base_metrics.csv -diffMetricsSummary C:\h\w\B34A09AB\t\tmp8emfgz3_\realworld.run.windows.x86.checked.mch_diff_metrics.csv -jitoption force JitAlignLoops=0 -jitoption force JitEnableNoWayAssert=1 -jitoption force JitNoForceFallback=1 -jit2option force JitAlignLoops=0 -jit2option force JitEnableNoWayAssert=1 -jit2option force JitNoForceFallback=1 -p -failureLimit 100 -ignoreStoredConfig C:\h\w\B34A09AB\p\base\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\diff\clrjit_win_x86_x86.dll C:\h\w\B34A09AB\p\artifacts\spmi\mch\a2974440-e8ee-4d95-9e6e-799a330be1a0.windows.x86\realworld.run.windows.x86.checked.mch
```

**Comment by BruceForstall** [comment]
ah, ok. so the timeouts do need to be increased.

fwiw, I ran the failing cases locally and got no diffs.

**Pull request merged**
