### PR TITLE
Replace TarFileMode with UnixFileMode

### PR DESCRIPTION
**Pull request by carlossanlop**
Replaces the `System.Formats.Tar.TarFileMode` enum originally added in this PR: https://github.com/dotnet/runtime/pull/67883
With the more general one, `System.IO.UnixFileMode`, which was freshly added in this PR:  https://github.com/dotnet/runtime/pull/69980

### CODE REVIEW

**Comment by carlossanlop** [comment]
@baronfel FYI

**Comment by baronfel** [comment]
Lovely, thank you for the ping. @rainersigwald this may be relevant.

**Review by eerhardt — APPROVED** [review]
:shipit:

**Review by tmds — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Comment by carlossanlop** [comment]
Test failures unrelated:

https://github.com/dotnet/runtime/issues/70450 System.IO.Tests.SymbolicLink_Changed_Tests.FileSystemWatcher_SymbolicLink_IncludeSubdirectories_DoNotDereferenceChildLink
https://github.com/dotnet/runtime/issues/71233 System.Net.Http.Functional.Tests - Assertion Failed - ClientCertificates. Expected enumerable cloned value.
https://github.com/dotnet/runtime/issues/70969 The process cannot access the file 'D:\a\_work\1\s\artifacts\log\Release\Microsoft.NET.HostModel.ComHost.Tests_net7.0_x64.log' because it is being used by another process.

**Pull request merged**
