### PR TITLE
Fix incorrect comparison (#54834)

### LINKED ISSUE #54834: TreeSubSet.Min and TreeSubSet.Max work incorrectly with custom comparer
### Description

The code below gives the wrong result:

    var comparer = Comparer<int>.Create((x, y) => x - y);  
    var set = new SortedSet<int>(new[]{1, 4}, comparer);  
    var view = set.GetViewBetween(1, 2);  
    Console.WriteLine(view.Max); // Prints 4 instead of 1  

According to the documentation of IComparer.Compare() it can return any integer, not only [-1, 0, 1]. So this comparer should be ok.

### Configuration

I run it on .net 5, but I think it is present in other versions as well.

### Regression?

A similar issue was mentioned in [20474](https://github.com/dotnet/runtime/issues/20474) (without comparer though). So I think it is regression.

### Other information

I have found the reason why it happens in code:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Collections/src/System/Collections/Generic/SortedSet.TreeSubSet.cs#L135 https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Collections/src/System/Collections/Generic/SortedSet.TreeSubSet.cs#L164
The comparison result is checked against 1 and -1, instead of (comp > 0) and (comp < 0).

### PR DESCRIPTION
**Pull request by petrogavriluk**
Fix #54834
Add test to check fix.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=55094) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=55094) before we can accept your contribution.<br/><br/>:x: petrogavriluk [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=55094)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=55094) it.</sub>

**Review by stephentoub — APPROVED** [review]
Thanks for the fix.

**Comment by petrogavriluk** [comment]
It's my first PR here. Should I do something to pass these failing checks?

**Comment by stephentoub** [comment]
Nope, looks like a CI hiccup. I've rerun those legs.

**Comment by stephentoub** [comment]
Thanks!

**Pull request merged**
