### PR TITLE
Fix execution of ilverify tests in outerloop runs

### PR DESCRIPTION
**Pull request by trylek**
As @jkotas noticed in #73109, outerloop tests don't run the
ilverify/ILVerificationTests.csproj test project. This is because
the project is somewhat atypical in residing just one directory
level beneath the test binary root folder; all other tests reside
under at least two directory levels and the legacy XUnit wrapper
generator reflects it so that each wrapper corresponds to
a two-level directory subtree.

The pre-existing logic for determining active two-level test
directories was quite hacky and perf-costly; I probably accidentally
removed the support for single-subfolder tests in one of my
refactorings of the src/tests/build.proj script. This change fixes
it and makes the construction of TestDirectories much more efficient
as we no longer construct a Carthesian product of all tests
times all two-level directories.

Thanks

Tomas

/cc @dotnet/runtime-infrastructure

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jkotas** [comment]
The XUnitWrapper is failing to find the .cmd file to run the tests:
```
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 7.0.0-preview.5.22301.12)
  Discovering: windows.arm64.Checked.ilverify.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  windows.arm64.Checked.ilverify.XUnitWrapper (found 1 test case)
  Starting:    windows.arm64.Checked.ilverify.XUnitWrapper (parallel test collections = on, max threads = 8)
    ilverify\ILVerificationTests.cmd [FAIL]
      Test Infrastructure Failure: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'D:\h\w\A67608B7\w\B15709AA\e\windows.arm64.Checked\ilverify\ILVerificationTests.cmd' with working directory 'D:\h\w\A67608B7\w\B15709AA\e'. The system cannot find the file specified.
         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
         at CoreclrTestLib.CoreclrTestWrapperLib.RunTest(String executable, String outputFile, String errorFile, String category, String testBinaryBase, String outputDir)
         at windows_arm64_Checked_ilverify._ILVerificationTests_._ILVerificationTests_cmd()
      Expected: True
      Actual:   False
      Stack Trace:
           at windows_arm64_Checked_ilverify._ILVerificationTests_._ILVerificationTests_cmd()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  Finished:    windows.arm64.Checked.ilverify.XUnitWrapper
```

**Comment by trylek** [comment]
The only remaining failure is the timeout in the llvmfullaot tests that is known and hopefully about to be addressed by https://github.com/dotnet/runtime/pull/73265, merging in.

**Comment by jkotas** [comment]
@trylek Thank you!

**Pull request merged**
