### PR TITLE
Update HP libunwind to v1.8.0

### PR DESCRIPTION
**Pull request by am11**
[<kbd>v1.8.0</kbd>](https://github.com/libunwind/libunwind/releases/tag/v1.8.0), see `libunwind-version.txt`.

### CODE REVIEW

**Comment by am11** [comment]
arm64 legs are currently hitting a syntax error in inline asm (clang vs. gcc thing). Filed https://github.com/libunwind/libunwind/issues/702.

**Comment by am11** [comment]
> Revert https://github.com/libunwind/libunwind/pull/503 # issue: https://github.com/libunwind/libunwind/issues/702

Added this note in libunwind-version.txt. I had to revert that assembly change since this it was causing build issue with aarch64-clang (which doesn't allow more than 14 registers without using temps -> the version after the revert).

**Review by janvorli — APPROVED** [review]
LGTM, thank you for taking care of these updates!

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by janvorli** [comment]
The failed legs were unrelated to this PR (windows x86, wasm)

**Pull request merged**
