### PR TITLE
Enable Crossgen for FreeBSD, now that it is actually implemented.

### PR DESCRIPTION
**Pull request by josteink**
Support implemented in this commit: https://github.com/dotnet/runtime/commit/3c63559029276fea97633ea6115bcb9acb2cffe2

cc: @Thefrank @sec @jasonpugsley @jkotas

### CODE REVIEW

**Comment by jasonpugsley** [comment]
I'm not sure how to fix this one. I _think_ Linux is using the crossgen it just built for FreeBSD. What we need it to do is restore crossgen2 (to .packages) and use that - possibly with the `--targetos:freebsd` switch we discussed previously.

**Comment by jasonpugsley** [comment]
Sorry, I mean fix the failed CI build.

**Comment by jasonpugsley** [comment]
Actually Linux is able to crossgen System.Private.CoreLib.dll for FreeBSD so we just need to replicate that configuration.

**Comment by jasonpugsley** [comment]
I still haven't figured out how Linux is able to crossgen2 System.Private.CoreLib.dll for FreeBSD. I get the same failure we are seeing when I try to copy the command it uses and run it manually.

**Comment by jasonpugsley** [comment]
The other option is to only run crossgen2 when doing a native build on FreeBSD - disable crossgen if it's a cross-build.
```diff
diff --git a/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Crossgen2.sfxproj b/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Crossgen2.sfxproj
index 81990fdeea9..fd9b9558407 100644
--- a/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Crossgen2.sfxproj
+++ b/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Crossgen2.sfxproj
@@ -18,8 +18,10 @@
         AddFrameworkFilesToPackage
     </GetSharedFrameworkFilesForReadyToRunDependsOn>
     <PublishReadyToRun>true</PublishReadyToRun>
-    <!-- Disable crossgen on FreeBSD, NetBSD, illumos and Solaris for now. This can be revisited when we have full support. -->
-    <PublishReadyToRun Condition="'$(TargetOS)'=='FreeBSD' Or '$(TargetOS)'=='NetBSD' Or '$(TargetOS)'=='illumos' Or '$(TargetOS)'=='Solaris'">false</PublishReadyToRun>
+    <!-- Disable crossgen on NetBSD, illumos and Solaris for now. This can be revisited when we have full support. -->
+    <PublishReadyToRun Condition="'$(TargetOS)'=='NetBSD' Or '$(TargetOS)'=='illumos' Or '$(TargetOS)'=='Solaris'">false</PublishReadyToRun>
+    <!-- Disable crossgen on FreeBSD when cross builing from Linux. -->
+    <PublishReadyToRun Condition="'$(TargetOS)'=='FreeBSD' and '$(CrossBuild)'=='true'">false</PublishReadyToRun>
     <HostJsonTargetPath>tools/</HostJsonTargetPath>
     <PermitDllAndExeFilesLackingFileVersion>true</PermitDllAndExeFilesLackingFileVersion>
   </PropertyGroup>
diff --git a/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.props b/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.props
index 87aaf9d263c..bae4940b9a8 100644
--- a/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.props
+++ b/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.props
@@ -7,8 +7,10 @@
     </GetSharedFrameworkFilesForReadyToRunDependsOn>
     <PublishReadyToRun Condition="'$(RuntimeFlavor)' != 'Mono'">true</PublishReadyToRun>
     <PublishReadyToRun Condition="'$(RuntimeFlavor)' == 'Mono'">false</PublishReadyToRun>
-    <!-- Disable crossgen on FreeBSD, NetBSD, illumos and Solaris for now. This can be revisited when we have full support. -->
-    <PublishReadyToRun Condition="'$(TargetOS)'=='FreeBSD' Or '$(TargetOS)'=='NetBSD' Or '$(TargetOS)'=='illumos' Or '$(TargetOS)'=='Solaris'">false</PublishReadyToRun>
+    <!-- Disable crossgen on NetBSD, illumos and Solaris for now. This can be revisited when we have full support. -->
+    <PublishReadyToRun Condition="'$(TargetOS)'=='NetBSD' Or '$(TargetOS)'=='illumos' Or '$(TargetOS)'=='Solaris'">false</PublishReadyToRun>
+    <!-- Disable crossgen on FreeBSD when cross builing from Linux. -->
+    <PublishReadyToRun Condition="'$(TargetOS)'=='FreeBSD' and '$(CrossBuild)'=='true'">false</PublishReadyToRun>
     <!-- These components are installed by the root shared framework, but not others. -->
     <IncludeWerRelatedKeys>true</IncludeWerRelatedKeys>
     <IncludeBreadcrumbStoreFolder>true</IncludeBreadcrumbStoreFolder>
```
I will keep working on this but at least we have an option/compromise.

**Comment by josteink** [comment]
Hey Jason and thanks for the suggestions.

That's IMO quite a reasonable compromise. As long as we admittedly don't fully understand how the whole build-process works, it's probably better to side-step this issue for the time being.

If we don't have a fully crossgen'd SDK to bootstrap a native build with, that won't be a show-stopper, and then we can get a better, more performant build when creating the true native build later using the cross-built components.

I'll update my PR accordingly.

**Comment by Thefrank** [comment]
Skipping Crossgening during crossbuild is fine. Most people in the FreeBSD want to be able to build/use a native SDK anyways.

**Comment by josteink** [comment]
Good catch. Done.

**Comment by Thefrank** [comment]
CI failures unrelated?

**Comment by josteink** [comment]
Hard to tell. Can someone restart the build?

**Comment by josteink** [comment]
Rebased and pushed to trigger new build. Lets see what happens.

**Comment by josteink** [comment]
All CI checks passed. Anyone feel like doing a final review or merge? @jkotas ?

**Comment by jkotas** [comment]
> Linux is able to crossgen System.Private.CoreLib.dll for FreeBSD so we just need to replicate that configuration.

You would have to build the native Linux crossgen binary to do this. Linux arm build does that when cross-building from Linux x64.

The change in this PR looks good to me as a workaround if doing it properly is too hard to do.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
