### PR TITLE
[wasm][debugger] Proxy but don't process events from worker sessions

### LINKED ISSUE #57949: VS2022 debuger crashes when reading HTTP Response Object response.Content.ReadAsStringAsync();
I am using VS2022 preview 3.1 with Blazor WebAssembly Hosted Project.

I have code where the Debugger crashes and have to start over Debugging again.

in my client side(WebAssembly Project) i have the following code inside trycatch whcih runs into error.
jsonString = await response.Content.ReadAsStringAsync();
The control does not execute the catch block, it simply crashes.

Here is the response from API call from the Newtwork tab of browser.

`{"currentLocation":{"CurrentLocationCountry":{"COUNTRYID_PK":"5be0b267-9df7-ea11-af8c-000d3a606520","CountryCode2":"US","CountryCode3":"USA","Country_Name":"United States","UNCode":"840","TelephoneCode":"1","IDD":"011","CurrencyName":"US Dollar r (Same day)","CurrencyCode":"USS"},"CurrentLocationState":{"StateID_PK":"e85a659b-e0f3-461c-8336-17398b8e6084","CountryID_FK":"5be0b267-9df7-ea11-af8c-000d3a606520","State_Name":"Illinois","State_Code":"IL","State_Capital":null},"CurrentLocationCity":{"CityID_PK":"41badc02-45fb-ea11-af8c-000d3a606520","StateID_FK":"e85a659b-e0f3-461c-8336-17398b8e6084","City_Name":"Chicago","City_Code":null},"CurrentLocationZipCode":null,"LastRefreshedAt":"0001-01-01T00:00:00"},"locationGuid":""}`

[Link to Screen Recording(gif)](https://1drv.ms/u/s!AtHk7h6Srnk_h9c_Jk99TrJmblFTUg)

### PR DESCRIPTION
**Pull request by lewing**
Should Fix #57949

@thaystg can you see if you can construct a test for this?

### CODE REVIEW

**Review by thaystg — DISMISSED** [review]

**Review by thaystg — APPROVED** [review]

**Comment by radical** [comment]
Isn't the same check needed for `Runtime.consoleAPICalled`, `Target.attachedToTarget`, and `Target.targetDestroyed`?

**Comment by lewing** [comment]
> Isn't the same check needed for `Runtime.consoleAPICalled`, `Target.attachedToTarget`, and `Target.targetDestroyed`?

Not exactly, those don't expect the context to exist in the same way:
   Runtime.consoleAPICalled only does work when a mono runtime is executing.
   Target.AttachedToTarget really does work on those sessions
   Target.targetDestroyed will fail to evaluate on the js side but it should be harmless.

**Comment by radical** [comment]
> > Isn't the same check needed for `Runtime.consoleAPICalled`, `Target.attachedToTarget`, and `Target.targetDestroyed`?
> 
> Not exactly, those don't expect the context to exist in the same way:
> Runtime.consoleAPICalled only does work when a mono runtime is executing.

What are the "worker sessions" mentioned in the title? Are these sessions executing while the mono runtime is also executing? If so, then couldn't we receive this message for a non-mono session?

Looking at the code, it's handling two mono [[1]](https://github.com/lewing/runtime/blob/ignore-worker-events/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs#L62)[[2]](https://github.com/lewing/runtime/blob/ignore-worker-events/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs#L83) specific cases, so it won't be a problem with that, IIUC. But if we *can* receive messages not meant for us, then it might still be a good idea to check in that case, and proxy the message?

**Comment by lewing** [comment]
> > > Isn't the same check needed for `Runtime.consoleAPICalled`, `Target.attachedToTarget`, and `Target.targetDestroyed`?
> > 
> > 
> > Not exactly, those don't expect the context to exist in the same way:
> > Runtime.consoleAPICalled only does work when a mono runtime is executing.
> 
> What are the "worker sessions" mentioned in the title? Are these sessions executing while the mono runtime is also executing? If so, then couldn't we receive this message for a non-mono session?
> 

https://developer.mozilla.org/en-US/docs/Web/API/Worker

> Looking at the code, it's handling two mono [[1]](https://github.com/lewing/runtime/blob/ignore-worker-events/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs#L62)[[2]](https://github.com/lewing/runtime/blob/ignore-worker-events/src/mono/wasm/debugger/BrowserDebugProxy/MonoProxy.cs#L83) specific cases, so it won't be a problem with that, IIUC. But if we _can_ receive messages not meant for us, then it might still be a good idea to check in that case, and proxy the message?

I'm not sure I follow, in the cases where it isn't from mono it does get proxied.

**Review by radical — APPROVED** [review]

**Pull request merged**
