### PR TITLE
Update Linux/arm, Linux/arm64 cross containers to ones including pip3

### PR DESCRIPTION
**Pull request by BruceForstall**
Pick up https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/681

### CODE REVIEW

**Comment by BruceForstall** [comment]
Enables https://github.com/dotnet/runtime/pull/74961 to upload collections for Linux/arm, Linux/arm64.

**Comment by BruceForstall** [comment]
@kunalspathak @dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
Discussion about the failures here is over in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/681

Namely, the docker images named in this PR aren't quite right.

**Review by am11 — COMMENTED** [review]
Latest tags are always published at https://github.com/dotnet/versions/blob/main/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-main.json, you can search for `18.04/cross/arm/` and arm64/ to find the tags.

(we also have Ubuntu 22.04 cross images with llvm 15 final toolchain released today)

**Comment by BruceForstall** [comment]
Thanks, @am11. However, it appears the official build which publishes these Docker images did not succeed the last build (it appears it was manually canceled), and that last build is the one with my changes.

**Comment by BruceForstall** [comment]
Unrelated:
```
Downloading 'https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh'
curl: (92) HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
Curl failed; dumping some information about dotnet.microsoft.com for later investigation
```

**Comment by BruceForstall** [comment]
"Libraries Test Run release mono Linux arm64 Debug" failure is https://github.com/dotnet/runtime/issues/74795

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib Can I get a review on this?

Once this is merged, it should allow the new SuperPMI coreclr tests "run" collection to succeed on Linux/arm and Linux/arm64.

**Comment by BruceForstall** [comment]
Anyone?

**Review by jakobbotsch — APPROVED** [review]

**Comment by kunalspathak** [comment]
Curious, where do you get the version `20220907130538-70ed2e8` from?

**Comment by BruceForstall** [comment]
> Curious, where do you get the version `20220907130538-70ed2e8` from?

After a change to https://github.com/dotnet/dotnet-buildtools-prereqs-docker is merged, an internal build happens that updates https://github.com/dotnet/versions/blob/main/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-main.json with the new container IDs.

**Pull request merged**
