### PR TITLE
Fix script errors in mainv1, mainv2 tests

### PR DESCRIPTION
**Pull request by BruceForstall**
A while back, tests were changed from building .exe to building .dll files
but these were not updated. Fix that.

Add additional testing to detect for possible errors in the inserted script commands.

### CODE REVIEW

**Comment by BruceForstall** [comment]
Testing for just adding the testing, to show that there are existing ignored errors, is in https://github.com/dotnet/runtime/pull/1995.

**Comment by BruceForstall** [comment]
@dotnet/crossgen-contrib

**Comment by BruceForstall** [comment]
fyi, found this due to https://github.com/dotnet/runtime/issues/1789, but this doesn't fix the problem there.

**Review by janvorli — APPROVED** [review]
LGTM, thank you for fixing it!

**Pull request merged**
