### PR TITLE
[Draft][release/7.0-rc1] Backport tar bug fixes and improvements

### PR DESCRIPTION
**Pull request by carlossanlop**
### Customer Impact

The tar APIs are new to 7.0. These changes make sure we ship the new APIs with great performance and fixes for important bugs we found in the last weeks.

### Testing

Added a large number of tests to cover all the bugs fixed in these commits.

### Risk

System.Formats.Tar is a new namespace, so the risk is low.

Pending: https://github.com/dotnet/runtime/pull/74412

### CODE REVIEW

**Comment by danmoseley** [comment]
@carlossanlop I suggest to pull out changes to Zip -- [ZipFile.Create.cs](https://github.com/dotnet/runtime/pull/74414/files?diff=unified&w=1#diff-046c062ee2b687cbafd5e61fad642863ba59bab9026e6bc144a1e8d9b3ff676b)
Those are totally opportunistic. We are only porting all the tar changes together here to avoid confusing code divergence.  There is no such reason to touch Zip. I see the changes in the common code will only be used by Tar, also, so that's fine.

**Comment by danmoseley** [comment]
also it seems from offline discussion we likely want to put in release/7.0. I suggest closing this and creating a new PR against that once your changes go into main today.

**Comment by danmoseley** [comment]
Oh, it already did. If you like, you could keep this open since you already kicked it off again, so we keep the option open to take it into rc1, but put up a new PR for rc2 now.

**Comment by carlossanlop** [comment]
Changes went into main already. I only need to remove the Compression changes. Should I still target 7.0?

**Comment by carlossanlop** [comment]
As discussed, abandoning this PR in favor of one for release/7.0.

**Pull request closed without merging**
