### PR TITLE
Unix: add mode to inline Socket continuations

### PR DESCRIPTION
**Pull request by tmds**

### CODE REVIEW

**Comment by tmds** [comment]
cc @adamsitnik @stephentoub

**Comment by tmds** [comment]
This is a new PR for changes in https://github.com/dotnet/runtime/pull/34945.

**Review by stephentoub — APPROVED** [review]

**Comment by antonfirsov** [comment]
A bunch of test runs are still reported as "Skipped". I wonder if I missed an existing discussion on these CI issues? 

If not I can try to start one, this is not the only PR being blocked.

**Comment by stephentoub** [comment]
> A bunch of test runs are still reported as "Skipped".

A bunch of tests are supposed to be skipped ;-)  Which ones are you referring to?

**Comment by stephentoub** [comment]
Seems there was something wrong with the previous PR.  This one went through.  Thanks, @tmds.

**Comment by antonfirsov** [comment]
@stephentoub sorry, I meant AZP jobs not individual tests. One thing I missed is that all of them are "checked" or mono builds, so it's likely fine, however quite confusing.

**Comment by geoffkizer** [comment]
@tmds I happened to be looking at this code and I'm confused by something.

You added the `bool processAsyncEvents = true` argument to `ProcessSyncEventOrGetAsyncEvent`, but it doesn't seem like this is actually getting set to false anywhere. All callers are either explicitly passing true or using the default arg value, which is true. Am I missing something here?

**Pull request merged**
