### PR TITLE
Add an Azure NPM registry

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
@agocke You'll need to npm install these locally on your machine to ingest the required packages.

**Comment by agocke** [comment]
@mmitche The CI is failing with

>   npm ERR! code E401
  npm ERR! Unable to authenticate, your authentication token seems to be invalid.
  npm ERR! To correct this please trying logging in again with:
  npm ERR!     npm login


Is that the same problem or different?

**Comment by mmitche** [comment]
> @mmitche The CI is failing with
> 
> > npm ERR! code E401
> > npm ERR! Unable to authenticate, your authentication token seems to be invalid.
> > npm ERR! To correct this please trying logging in again with:
> > npm ERR!     npm login
> 
> Is that the same problem or different?

@adiaaida has more experience with this, but I think it's the same. The package feed is anonymously accessible, but the packages required may not be available, requiring authentication to ingest.

**Comment by adiaaida** [comment]
Did you run 

```
vsts-npm-auth -config .npmrc
```

First? You may also have to go through these instructions first: 

```
To use npm packages, get npm (which comes with Node.js) and the vsts-npm-auth helper.
Step 1
[Download Node.js and npm](https://go.microsoft.com/fwlink/?linkid=2103882)

Step 2
Run this command

npm install -g vsts-npm-auth --registry https://registry.npmjs.com --always-auth false
```

**Comment by agocke** [comment]
I've tried running `vsts-npm-auth -config .npmrc` and it seemed to work but after re-running the tests they fail in the same way.

**Comment by mmitche** [comment]
> I've tried running `vsts-npm-auth -config .npmrc` and it seemed to work but after re-running the tests they fail in the same way.

Please ensure your npm cache is cleaned locally so that the ingestion happens (rather than picking up packages locally)

**Comment by adiaaida** [comment]
Oh yeah, there are different instructions for Linux. If you go to https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-public-npm/connect/npm and click the "Other" tab in project setup, it will tell you how to auth on Linux/Mac

**Comment by adiaaida** [comment]
Oh, the log says npm audit isn't supported and they're using npm audit:

```
npm ERR! audit Your configured registry (https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public-npm/npm/registry/) does not support audit requests.
```

**Comment by agocke** [comment]
@steveisok Any idea who could look at this `npm audit` issue?

**Comment by steveisok** [comment]
> @steveisok Any idea who could look at this `npm audit` issue?

@lewing @radical

**Comment by agocke** [comment]
ping @lewing @radical

**Comment by radical** [comment]
```
 npm info it worked if it ends with ok
  npm verb cli [
  npm verb cli   '/usr/local/emscripten/emsdk/node/14.18.2_64bit/bin/node',
  npm verb cli   '/usr/local/emscripten/emsdk/node/14.18.2_64bit/bin/npm',
  npm verb cli   'audit',
  npm verb cli   '--verbose'
  npm verb cli ]
  npm info using npm@6.14.15
  npm info using node@v14.18.2
  npm verb npm-session b8f1af247e4fb9ba
  npm http fetch POST 404 https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public-npm/npm/registry/-/npm/v1/security/audits 158ms
  npm verb stack Error: Your configured registry (https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public-npm/npm/registry/) does not support audit requests.
  npm verb stack     at /usr/local/emscripten/emsdk/node/14.18.2_64bit/lib/node_modules/npm/lib/audit.js:204:18
  npm verb stack     at tryCatcher (/usr/local/emscripten/emsdk/node/14.18.2_64bit/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
  npm verb stack     at Promise._settlePromiseFromHandler (/usr/local/emscripten/emsdk/node/14.18.2_64bit/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
  npm verb stack     at Promise._settlePromise (/usr/local/emscripten/emsdk/node/14.18.2_64bit/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
  npm verb stack     at Promise._settlePromise0 (/usr/local/emscripten/emsdk/node/14.18.2_64bit/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
  npm verb stack     at Promise._settlePromises (/usr/local/emscripten/emsdk/node/14.18.2_64bit/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:695:18)
  npm verb stack     at _drainQueueStep (/usr/local/emscripten/emsdk/node/14.18.2_64bit/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
  npm verb stack     at _drainQueue (/usr/local/emscripten/emsdk/node/14.18.2_64bit/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
  npm verb stack     at Async._drainQueues (/usr/local/emscripten/emsdk/node/14.18.2_64bit/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
  npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/emscripten/emsdk/node/14.18.2_64bit/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
  npm verb stack     at processImmediate (internal/timers.js:464:21)
  npm verb cwd /__w/1/s/src/mono/wasm/runtime
  npm verb Linux 5.4.0-1080-azure
  npm verb argv "/usr/local/emscripten/emsdk/node/14.18.2_64bit/bin/node" "/usr/local/emscripten/emsdk/node/14.18.2_64bit/bin/npm" "audit" "--verbose"
  npm verb node v14.18.2
  npm verb npm  v6.14.15
  npm ERR! code ENOAUDIT
  npm ERR! audit Your configured registry (https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public-npm/npm/registry/) does not support audit requests.
  npm verb exit [ 1, true ]
```

@lewing @pavelsavara @maraf Any idea what could be done here? Since the exception also shows the same error ` npm verb stack Error: Your configured registry (https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public-npm/npm/registry/) does not support audit requests.`, does it mean that the registry really doesn't support audit?

**Review by lewing — APPROVED** [review]

**Pull request merged**
