### PR TITLE
Test PR for #68366

### PR DESCRIPTION
**Pull request by filipnavara**

### CODE REVIEW

**Comment by wfurt** [comment]
It is disabled now as it was constantly failing @vcsjones. I can do local test and if that looks promising we can take another step. 

While I don't mind the fix in general, I'm not sure what it is needed now and was not needed before @filipnavara.

**Comment by filipnavara** [comment]
I just wanted to see if the test pass with this check removed. The Negotiate MIC was never checked before my last changed so either this check didn't work for a while, or it should fail with a different error.

**Pull request closed without merging**
