### PR TITLE
fix TLS resume with client certificates

### LINKED ISSUE #79869: .NET 7, Linux, SSL connection is being reused between independent HttpClients?
### Description

Hello,

The website to which I want to connect requires a client certificate and I am using two different HttpClients, one with and other without the cert. The one with it is supposed to connect and the other should not.

- HttpClient 1 no cert, when request, should receive 400 Bad Request
- HttpClient 2 has cert, when request, should receive 200 OK

The scenario above works correctly under .NET 6, but on .NET 7, the outcome is different:

- If HttpClient 1 calls first, it receives 400 Bad Request. When HttpClient 2 calls subsequently, it also receives 400 Bad Request, even having a client certificate.
- If HttpClient 2 calls first, it receives 200 OK. When HttpClient 1 calls subsequently, it also receives 200 OK, even not having a client certificate.

This problem happens only on Linux; on Windows, the behavior is correct, the same as in .NET 6. I did not test on MacOSX.
The website that I use to test client certificates is https://badssl.com/ (it has certificates for testing).
Code for how the HttpClients are being built: [link](https://github.com/alexandrehtrb/Pororoca/blob/479b327a4a9f97e6f33e7157e51ba23af1251de6/src/Pororoca.Infrastructure/Features/Requester/PororocaHttpClientProvider.cs#L17)

### Reproduction Steps

Video below

[Comportamento HttpClient ClientCertificate Dotnet7.webm](https://user-images.githubusercontent.com/27026741/208796261-b8eb2302-5854-42e7-90b8-46dfad469800.webm)

### Expected behavior

HttpClients with different HttpMessageHandlers should work independently, I believe

### Actual behavior

.

### Regression?

This problem does not happen in .NET 6

### Known Workarounds

_No response_

### Configuration

`dotnet --info`

```
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Ambiente de runtime:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /home/alexandre/.dotnet/sdk/7.0.101/

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  6.0.403 [/home/alexandre/.dotnet/sdk]
  7.0.101 [/home/alexandre/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/home/alexandre/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/home/alexandre/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/home/alexandre/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/home/alexandre/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/alexandre/.dotnet/]

global.json file:
  Not found
```

### Other information

_No response_

### PR DESCRIPTION
**Pull request by wfurt**
This is 7.0 regression caused by combination of #64369 #63200 #63945.
The intention always was to disable TLS resume with client certificates. 
However we also changed how client certificates are selected so the `CertificateContext` may not be set when the handle is created and it is updated later when server asks for it via `UpdateClientCertiticate`.

To make it simple, this change will also disable TLS resume if there are client certificate candidates e.g. the selection was not made yet. With guard for the callback, this hopefully should be complete. 

I added few more tests to guard various combinations of how client certs can be selected.  

fixes #79869
contributes to #75545

### CODE REVIEW

**Comment by wfurt** [comment]
This is getting more complicated. The real fix for https://github.com/dotnet/runtime/issues/79869 is still one line in `Interop.OpenSsl.cs`. However the added tests were failing on Windows, showing that #79128 was not complete fix. 
It seems like we cannot determine reliably usage of the client certificate in case of TLS resume. To fix that, we will now store copy of selected certificate into credentials. And we do that only when Schannel asks so we have confidence it is actually used. With that, we avoid issue I mentioned [here](https://github.com/dotnet/runtime/pull/79128#issuecomment-1344892121). (reverted CertificateValidationClientServer_EndToEnd_Ok test workaround)

Changes around `refreshCredentialNeeded` are unrelated and it is just small optimization to keep the logic together and it allows to replace instance property with local variable. 

contributes to https://github.com/dotnet/runtime/issues/65563

**Review by rzikm — APPROVED** [review]
LGTM.

It might be worth checking if this does not cause perf regression, there have been some sneaky ones in the past in this area.

**Comment by wfurt** [comment]
We did not have any benchmarks so I opened https://github.com/dotnet/performance/pull/2814
For Linux, it will drop back to 6.0 e.g. there will not be TLS resume. After experimenting with Windows, I think we may be able to resume with client certs in some situations but that would be new work for 8.0.

For Windows, the extra work is done only when somebody access `IsMutuallyAuthenticated`. That is probably rare and the cost of extra call is probably small compared to handshake crypto.

**Comment by wfurt** [comment]
WASM & OS X failures seems unrelated. Strangely, the consoles look like success but it is still reported as failure.

**Pull request merged**
