### PR TITLE
Remove the defunct DiagnosticUtility/Fx classes from DataContractSerialization

### PR DESCRIPTION
**Pull request by stephentoub**
- Fx.Assert just delegated to Debug.Assert: replace all the call sites with Debug.Assert/Fail.
- DiagnosticUtility.DebugAssert just delegated to Debug.Assert: replace all the call sites with Debug.Assert/Fail.
- DiagnosticUtility.ExceptionUtility.ThrowHelperError didn't throw anything and just returned its argument: removed all uses of it
- DiagnosticUtility.ExceptionUtility.ThrowHelperCallback didn't throw anything and just returned its argument: removed all uses of it.
- DiagnosticUtility.ExceptionUtility.ThrowHelperFatal didn't throw anything and just wrapped its arguments in a new Exception that was then returned: just changed the call sites to create that exception.
- DiagnosticUtility.ExceptionUtility.ThrowHelperArgument{Null} didn't throw anything and just returned new instances of Argument{Null}Exception: just changed the call sites to create that exception.
- Replaced some argument validation with helpers like ThrowIfNegative.
- Fx.IsFatal: moved to ExceptionUtility class

### CODE REVIEW

**Comment by StephenMolloy** [comment]
I've been looking at this in some spare moments this week. It mostly looks fine to me, but I've dug into what the point of these utilitiy methods used to be for and noticed that it was WCF's way of generating ETW events for errors. I also noticed that the concept of creating a Fatal Exception disappeared from NetFx to .Net Core. I wanted to look more into the Fatal exception wrapper idea to see if that's something we need and have a chat with Matt about where ETW fits with WCF these days.

**Review by StephenMolloy — APPROVED** [review]
Matt says he's never found use for ETW events in DCS, unlike the ETW events in WCF which this utility originally came from in NetFx. We haven't had ETW events here in .Net Core so far, and it doesn't seem like anything we care to bring back. So...

lgtm

**Comment by stephentoub** [comment]
Thanks for following up

**Comment by sebastienros** [comment]
It broke some aspnet unit tests that were checking specific exception types. Can you confirm that this change of exception type is fine here and we should just react to it? Or is that considered a non-acceptable breaking change? 

https://github.com/dotnet/runtime/commit/93ab46bde671f163c6f3243e0b00e0bd0644a68b#diff-b4bbe1b5ee1bb01a618b60e8197a2f0d09e69ae4c9788f3bfd6841dac23e2da2R95

The documentation states that `MaxDepth` can return an `ArgumentException` but after this PR it returns an `ArgumentOutOfRangeException`. I am just not familiar with the breaking changes policy.

**Comment by sebastienros** [comment]
I am realizing that `ArgumentOutOfRangeException` inherits from `ArgumentException` ... that might ease the breaking change policy quite considerably in this case.

**Comment by stephentoub** [comment]
> I am realizing that ArgumentOutOfRangeException inherits from ArgumentException ... that might ease the breaking change policy quite considerably in this case.

Right, we consider it "non-breaking" to throw more derived types than we were previously (even though that can obviously impact code doing an exact type test).  It's the same as returning objects more derived than what's statically typed, e.g. if a method returns a `List<T>`, we don't consider it breaking to return something that derives from `List<T>`.

**Pull request merged**
