### PR TITLE
Avoid capturing the ExecutionContext for the whole HTTP connection lifetime

### LINKED ISSUE #80232: Http2Connection keeps the ExecutionContext of the first request alive
As part of setting up the `Http2Connection` we spin up two background tasks for the read/write channel and in doing so we capture the execution context of the request that initiated the new connection.

We should do the `SuppressFlow`/`RestoreFlow` dance before calling into [`Http2Connection.SetupAsync`](https://github.com/dotnet/runtime/blob/524045bb01369c26a0dfc349c1c6a8e26a8a9833/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L203).

Repro (note that the finalizer doesn't run until you dispose the client):

```c#
var client = new HttpClient
{
    DefaultRequestVersion = HttpVersion.Version20
};

await SendRequest(client);

_ = Task.Run(async () =>
{
    await Task.Delay(5_000);
    Console.WriteLine("Disposing the client");
    client.Dispose();
});

for (int i = 1; ; i++)
{
    Console.WriteLine(i);
    GC.Collect();
    GC.WaitForPendingFinalizers();
    await Task.Delay(1000);
}

async Task SendRequest(HttpClient client)
{
    var asyncLocal = new AsyncLocal<Finalizable>();
    asyncLocal.Value = new Finalizable();
    
    await client.GetStringAsync("https://httpbin.org/ip");
}

public sealed class Finalizable
{
    ~Finalizable() => Console.WriteLine("Finalizer");
}
```

### PR DESCRIPTION
**Pull request by MihaZupan**
Fixes #80232

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by davidfowl** [comment]
This isn’t going to break any of the crazy code we gave to teams to associate connections with requests using async locals right?

**Comment by MihaZupan** [comment]
If you mean hacks like https://github.com/dotnet/runtime/issues/63159#issuecomment-1371345312, those will still work as the connection itself is still used within the async scope of the request's SendAsync (write calls on HTTP/1 at least, which is what that hack relies on).

For things like the connection establishment itself, this PR doesn't change anything, and we have some tests that verify events like `ConnectionEstablished` happen within the request's scope.

**Comment by MihaZupan** [comment]
The HTTP/3 test failure is related. Either a test bug or there's still some place where we capture the context there. Setting to draft for now before I get to investigate.

**Pull request closed without merging**
