### PR TITLE
Revert "[release/8.0-preview5] Update dependencies from dotnet/icu"

### PR DESCRIPTION
**Pull request by lewing**
Reverts dotnet/runtime#86762

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by lewing** [comment]
@carlossanlop the update is causing breakage I think we need to roll this back, it is just a transport package and the p4 version should be fine for runtime p5

**Comment by lewing** [comment]
attn @mmitche

**Comment by lewing** [comment]
I don't know if we need a p5 build with the reverted bits to make checks happy, @steveisok is spinning that up

**Review by carlossanlop — APPROVED** [review]
Ah, thanks for sending the revert. Apologies for the failures caused.
The CI of the original PR did not fail. Where were you looking for the failures, @lewing?
In the future, would you like me to ping you and @steveisok before merging a dotnet/icu dependencies PR?

**Comment by steveisok** [comment]
> Ah, thanks for sending the revert. Apologies for the failures caused. The CI of the original PR did not fail. Where were you looking for the failures, @lewing? In the future, would you like me to ping you and @steveisok before merging a dotnet/icu dependencies PR?

No, we took ICU 72 into ICU main when it wasn't ready and it got branched into P5.

**Comment by lewing** [comment]
basically icu has been stalled trying to sort out the 72 update, flow got turned back on and looked like we were behind but the update has the issues and the flow to p5 didn't trigger the right tests so it looked green.  it is an odd situation that should be resolved soon.  this can be merged at will

**Comment by lewing** [comment]
@radical can you take a look at the triggers?

**Comment by lewing** [comment]
someone with privs should merge this

**Comment by radical** [comment]
There were *zero* pipelines triggered on that PR - https://github.com/dotnet/runtime/pull/86762 ! I'm checking with FR.

**Comment by radical** [comment]
> There were _zero_ pipelines triggered on that PR - #86762 ! I'm checking with FR.

FR said that this was a one time occurrence where no pipelines ran, and shouldn't happen again. This isn't related to triggers in `dotnet/runtime` either.

**Pull request merged**
