### PR TITLE
Remove an assert from impHWIntrinsic

### LINKED ISSUE #72081: Assertion failed 'sizeBytes != 0'
Ran into this while NativeAOT compiling the System.Runtime.Intrinsics.Tests but this has a simple repro with CoreCLR. Not clear why we're not seeing this in test runs.

Compile following:

```csharp
using System;
using System.Runtime.Intrinsics;

Vector128<UInt128> d = default;
d.GetHashCode();
```

With `csc test.cs /noconfig /nostdlib /r:System.Private.CoreLib.dll /O`. Run with corerun.

```
Assert failure(PID 17384 [0x000043e8], Thread: 40284 [0x9d5c]): Assertion failed 'sizeBytes != 0' in 'System.Runtime.Intrinsics.Vector128`1[UInt128][System.UInt128]:GetHashCode():int:this' during 'Importation' (IL size 67; hash 0x04fdae41; MinOpts)

    File: C:\git\runtime2\src\coreclr\jit\hwintrinsic.cpp Line: 777
    Image: C:\git\runtime2\artifacts\bin\coreclr\windows.x64.Debug\corerun.exe
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/72081

### CODE REVIEW

**Review by jakobbotsch — APPROVED** [review]

**Review by tannergooding — APPROVED** [review]

**Comment by EgorBo** [comment]
hm.. the test I added crashes mono llvmaot cc @fanyang-mono @vargaz any quick fix I can apply or just add it to the ignore list and file an issue?

**Comment by vargaz** [comment]
UInt128 is probably not allowed as a simd type by mono, so I'd suggest ignoring the test for now.

**Comment by EgorBo** [comment]
> UInt128 is probably not allowed as a simd type by mono, so I'd suggest ignoring the test for now.

From my understanding it's also not supported on CLR, it's expected to throw an not-supported-exception rather than an assert

**Comment by EgorBo** [comment]
the fix I've just applied seems to work - it also guards from using `Vector128<char>` which is a quite popular mistake users make 🙂

**Comment by tannergooding** [comment]
> From my understanding it's also not supported on CLR, it's expected to throw a not-supported-exception rather than an assert

Right, `Vector128<UInt128>` might be declared by a user and so the runtime should robustly handle it. In this case it should at least fallback to the software path which will then `throw NotSupportedException` since its an unsupported `T`.

**Comment by vargaz** [comment]
The mono change looks ok.

**Comment by fanyang-mono** [comment]
Same check should probably be added to `SN_CreateScalar` and `SN_CreateScalarUnsafe` as well.

**Comment by fanyang-mono** [comment]
> Same check should probably be added to `SN_CreateScalar` and `SN_CreateScalarUnsafe` as well.

I just checked that CoreCLR doesn't those exceptions for unsupported types when calling the above two methods, then mono doesn't need to do so either. Your fix for mono looks good to me.

**Comment by EgorBo** [comment]
There were still asserts, turns out I didn't test properly and didn't realize that Vector128.Create has generic and non-generic overloads, now it works OK, I validated Mono-LLVM codegen for:
```csharp

[MethodImpl(MethodImplOptions.NoInlining)]
static Vector128<int> Foo1() => Vector128.Create(42); // non-generic

[MethodImpl(MethodImplOptions.NoInlining)]
static Vector128<int> Foo2() => Vector128.Create<int>(42); // generic

[MethodImpl(MethodImplOptions.NoInlining)]
static Vector128<char> Foo3() => Vector128.Create<char>('4');

[MethodImpl(MethodImplOptions.NoInlining)]
static Vector128<Int128> Foo4() => Vector128.Create<Int128>(42);
```
Foo1 and Foo2 emit correct broadcast instructions while Foo3 and Foo4 emit `throw new NotSupportedException`

**Comment by EgorBo** [comment]
CI failure is unrelated: https://github.com/dotnet/runtime/issues/72182

**Pull request merged**
