### PR TITLE
fix(76268): Fix invalid behavior for ignored properties with "new" mo…

### LINKED ISSUE #76268: Adding JsonIgnoreAttribute to `new` property fails with ArgumentException
### Description

```C#
using System.Text.Json;
using System.Text.Json.Serialization;

ClassB b = new ClassB();
var test = JsonSerializer.Serialize(b);
Console.ReadLine();

public class ClassA
{
    [JsonIgnore]
    public string test { get; set; }
}

public class ClassB : ClassA
{
    [JsonIgnore]
    public new string test { get; set; }
}
```

The above code will throw an exception: System.ArgumentException:“An item with the same key has already been added. Key: test”

When both base class and derived class has a property with the same name (derived class using new to override property in base class),  and both of this two properties marked as [JsonIgnore], Serialize function throw this exception.

### PR DESCRIPTION
**Pull request by Maximys**
Simple change [Dictionary<TKey,TValue>.Add(TKey, TValue)](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.add?view=net-7.0#system-collections-generic-dictionary-2-add(-0-1)) for adding new ignored property to [Dictionary<TKey,TValue>.Item[TKey]](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.item?view=net-7.0#system-collections-generic-dictionary-2-item(-0))

Fixes #76268

### CODE REVIEW

**Comment by Maximys** [comment]
@jeffhandley  , can you review current PR quickly? I think, #66900 linked with the same lines and I want to fix it separately.

**Comment by layomia** [comment]
@Maximys could you take a look at the test failures? My guess is that the change makes source generation fail in some way e.g. not producing source good to implement the abstract members.

**Comment by Maximys** [comment]
@layomia , ok, I'll try to look at the test failures a bit late.

**Comment by Maximys** [comment]
@layomia , I had just fixed failed tests by amend. Could you review again?

**Review by eiriktsarpalis — APPROVED** [review]
Thanks!

**Pull request merged**
