### PR TITLE
[RISC-V] Add gcinfodumper implementation.

### PR DESCRIPTION
**Pull request by viewizard**
This code changes tested as part of `diagnostics` with `gcinfo` SOS command.
Note, I don't create PR for `diagnostics` upstream, will port this changes into current `diagnostics` upstream after this PR will be merged in `dotnet` upstream.

Test output for riscv64 with this changes:
```
> gcinfo 0000003f206fe840                                                                                                                                                             
entry point 0000003F2063B8B8
Normal JIT generated code
GC info 0000003F2073C840
Pointer table:
Prolog size: 0
Security object: <none>
GS cookie: <none>
PSPSym: caller.sp-8
Generics inst context: <none>
PSP slot: caller.sp-8
GenericInst slot: <none>
Varargs: 0
Frame pointer: fp
Has tailcalls: 0
Size of parameter area: 0
Return Kind: Scalar
Code size: 1e0
Untracked: +fp+50 +fp+48 +fp+40 +fp+38 +fp+30 +fp+28 +fp+20 +fp+18
0000004c interruptible
00000098 +a0
000000a0 +a1
000000ac -a0
000000d0 -a1 +a0
000000f0 -a0
0000011c +a0
0000013c -a0
00000140 +a0
00000154 -a0
0000015c not interruptible
00000180 interruptible
00000180 +a0
00000194 -a0
000001a8 +a0
000001c0 -a0
000001d0 not interruptible
```

for example, arm32 output for same code:
```
> gcinfo b4c5fd64                                                                                                                                                 
entry point B4C79A18
Normal JIT generated code
GC info B4CBE730
Pointer table:
Prolog size: 0
Security object: <none>
GS cookie: <none>
PSPSym: caller.sp-14
Generics inst context: <none>
PSP slot: caller.sp-14
GenericInst slot: <none>
Varargs: 0
Frame pointer: r11
Has tailcalls: 0
Size of parameter area: 0
Return Kind: Scalar
Code size: e4
Untracked: +r11-14 +r11-18 +r11-1c +r11-20 +r11-24 +r11-28 +r11-2c +r11-30
0000001e interruptible
00000042 +r0
0000004c -r0
00000052 +r0
00000054 +r1
0000005e -r1
0000006c -r0
00000082 +r0
00000090 -r0
00000092 +r0
0000009c -r0
000000a0 not interruptible
000000b0 interruptible
000000b0 +r0
000000b8 +r3
000000c2 -r3
000000d0 +r3
000000dc -r0
000000e0 not interruptible
000000e0 -r3
```

CC @dotnet/samsung

### CODE REVIEW

**Comment by viewizard** [comment]
@shushanhf @dotnet/loongarch64-contrib please take a look on changes I provide in this PR, I believe, LoongArch64 also have wrong registers mapping here:
https://github.com/dotnet/runtime/blob/ed7aef86caf0505456a203009d3bdd4b7290b7d8/src/coreclr/gcinfo/gcinfodumper.cpp#L190-L226

**Comment by tommcdon** [comment]
@jkotas @hoyosjs

**Review by clamp03 — APPROVED** [review]
LGTM Thank you!

**Comment by shushanhf** [comment]
> @shushanhf @dotnet/loongarch64-contrib please take a look on changes I provide in this PR, I believe, LoongArch64 also have wrong registers mapping here:
> 
> https://github.com/dotnet/runtime/blob/ed7aef86caf0505456a203009d3bdd4b7290b7d8/src/coreclr/gcinfo/gcinfodumper.cpp#L190-L226

sorry for late repose.
Thanks very much!
We will add for LA64.

**Review by tomeksowi — APPROVED** [review]

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by risc-vv** [comment]
### RISC-V testing failed on init-build
<details>
<summary>details</summary>

GIT: d76a455215cc28def3e591eec3c59e461cc73108
```bash
Cloning into 'runtime'...
Updating files:  18% (10834/58653)
Updating files:  19% (11145/58653)
Updating files:  20% (11731/58653)
Updating files:  21% (12318/58653)
Updating files:  22% (12904/58653)
Updating files:  23% (13491/58653)
Updating files:  24% (14077/58653)
Updating files:  25% (14664/58653)
Updating files:  26% (15250/58653)
Updating files:  27% (15837/58653)
Updating files:  28% (16423/58653)
Updating files:  29% (17010/58653)
Updating files:  30% (17596/58653)
Updating files:  31% (18183/58653)
Updating files:  32% (18769/58653)
Updating files:  33% (19356/58653)
Updating files:  34% (19943/58653)
Updating files:  35% (20529/58653)
Updating files:  36% (21116/58653)
Updating files:  37% (21702/58653)
Updating files:  38% (22289/58653)
Updating files:  39% (22875/58653)
Updating files:  40% (23462/58653)
Updating files:  40% (23936/58653)
Updating files:  41% (24048/58653)
Updating files:  42% (24635/58653)
Updating files:  43% (25221/58653)
Updating files:  44% (25808/58653)
Updating files:  45% (26394/58653)
Updating files:  46% (26981/58653)
Updating files:  47% (27567/58653)
Updating files:  48% (28154/58653)
Updating files:  49% (28740/58653)
Updating files:  50% (29327/58653)
Updating files:  51% (29914/58653)
Updating files:  52% (30500/58653)
Updating files:  53% (31087/58653)
Updating files:  54% (31673/58653)
Updating files:  55% (32260/58653)
Updating files:  56% (32846/58653)
Updating files:  57% (33433/58653)
Updating files:  58% (34019/58653)
Updating files:  59% (34606/58653)
Updating files:  60% (35192/58653)
Updating files:  61% (35779/58653)
Updating files:  62% (36365/58653)
Updating files:  63% (36952/58653)
Updating files:  64% (37538/58653)
Updating files:  64% (37586/58653)
Updating files:  65% (38125/58653)
Updating files:  66% (38711/58653)
Updating files:  67% (39298/58653)
Updating files:  68% (39885/58653)
Updating files:  69% (40471/58653)
Updating files:  70% (41058/58653)
Updating files:  71% (41644/58653)
Updating files:  72% (42231/58653)
Updating files:  73% (42817/58653)
Updating files:  74% (43404/58653)
Updating files:  75% (43990/58653)
Updating files:  76% (44577/58653)
Updating files:  77% (45163/58653)
Updating files:  78% (45750/58653)
Updating files:  79% (46336/58653)
Updating files:  80% (46923/58653)
Updating files:  81% (47509/58653)
Updating files:  82% (48096/58653)
Updating files:  83% (48682/58653)
Updating files:  84% (49269/58653)
Updating files:  85% (49856/58653)
Updating files:  86% (50442/58653)
Updating files:  87% (51029/58653)
Updating files:  87% (51445/58653)
Updating files:  88% (51615/58653)
Updating files:  89% (52202/58653)
Updating files:  90% (52788/58653)
Updating files:  91% (53375/58653)
Updating files:  92% (53961/58653)
Updating files:  93% (54548/58653)
Updating files:  94% (55134/58653)
Updating files:  95% (55721/58653)
Updating files:  96% (56307/58653)
Updating files:  97% (56894/58653)
Updating files:  98% (57480/58653)
Updating files:  99% (58067/58653)
Updating files: 100% (58653/58653)
Updating files: 100% (58653/58653), done.
Switched to a new branch 'build-net'
Checking patch src/coreclr/gcinfo/gcinfodumper.cpp...
error: while searching for:
#undef REG
#elif defined(TARGET_RISCV64)
#undef REG
#define REG(reg, field) { offsetof(RiscV64VolatileContextPointer, field) }
        REG(zero, R0),
        REG(a0, A0),
        REG(a1, A1),
        REG(a2, A2),
        REG(a3, A3),
        REG(a4, A4),
        REG(a5, A5),
        REG(a6, A6),
        REG(a7, A7),
        REG(t0, T0),
        REG(t1, T1),
        REG(t2, T2),
        REG(t3, T3),
        REG(t4, T4),
        REG(t5, T5),
        REG(t6, T6),
#undef REG
#define REG(reg, field) { offsetof(T_KNONVOLATILE_CONTEXT_POINTERS, field) }
        REG(s1, S1),
        REG(s2, S2),
        REG(s3, S3),
        REG(s4, S4),

error: patch failed: src/coreclr/gcinfo/gcinfodumper.cpp:226
error: src/coreclr/gcinfo/gcinfodumper.cpp: patch does not apply

```
</details>

**Review by gbalykov — COMMENTED** [review]
LGTM

**Pull request merged**
