### PR TITLE
Enable Http2.SocketSendQueueFull_RequestCanceled_ThrowsOperationCanceled

### LINKED ISSUE #44352: Test failure: SocketsHttpHandlerTest_Http2.SocketSendQueueFull_RequestCanceled_ThrowsOperationCanceled
#### Outerloop test
`System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.SocketSendQueueFull_RequestCanceled_ThrowsOperationCanceled`

#### Failed in
https://dev.azure.com/dnceng/public/_build/results?buildId=877008&view=ms.vss-test-web.build-test-results-tab
(net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.30.Amd64.Open)ubuntu.1604.amd64.open)

Failed only in PR branches, so it's missing from our test reports.

#### Error message
```
System.TimeoutException : WhenAllOrAnyFailed timed out after 60000ms
```

#### Stack trace
```
at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 88
   at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Http2Options http2Options, Int32 timeout) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs:line 172
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.SocketSendQueueFull_RequestCanceled_ThrowsOperationCanceled() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 3444
--- End of stack trace from previous location ---
```

### PR DESCRIPTION
**Pull request by alnikola**
The test should have been already fixed by #56552.

Fixes #44352

### CODE REVIEW

**Comment by MihaZupan** [comment]
The test is signaling a `CancellationToken`, shouldn't that prevent a timeout even if the request did end up getting retried before #56552?

**Comment by alnikola** [comment]
>The test is signaling a `CancellationToken`, shouldn't that prevent a timeout even if the request did end up getting retried before #56552?

It seems to be so, but it wouldn't have hung, if it had worked this way.

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
