### PR TITLE
[wasm] Add INTERP_OPT_JITERPRETER so that jiterp is disabled in debug mode

### PR DESCRIPTION
**Pull request by kg**
This PR adds a new interpreter option that governs whether the jiterpreter is allowed to engage and adds it to the default set of options. Since when we set up for debugging we configure the interpreter with a different set of options, this ensures traces will not be compiled when debugging.

This PR also fixes a typo in interpreter config parsing.

### CODE REVIEW

**Comment by kg** [comment]
Vlad helped me figure out the correct way to do this, so I'm going to rework this PR.

**Comment by kg** [comment]
Ready for re-review

**Comment by vargaz** [comment]
Wouldn't it better to use the existing mono_opt_jiterp options to turn this off ?

**Comment by kg** [comment]
> Wouldn't it better to use the existing mono_opt_jiterp options to turn this off ?

It's more complicated, so vlad's suggestion was to do this. The existing options still work, this just ensures that if the interp is configured for debugging it will automatically shut off jiterp

**Comment by vargaz** [comment]
Where is the new option set ?

**Comment by kg** [comment]
> Where is the new option set ?

My understanding is that when we configure the interpreter for debugging, we set a specific list of options. I didn't add jiterp to that list, so it won't be enabled. I added it to the default set so it should be enabled by default.

When I ran a local test the diagnostic output didn't say that any traces had been compiled, so it should work.

**Review by vargaz — APPROVED** [review]

**Review by BrzVlad — APPROVED** [review]

**Pull request merged**
