### PR TITLE
Consolidate, expand, and clean up some HTTP proxy tests

### PR DESCRIPTION
**Pull request by geoffkizer**
Move some proxy-related tests into HttpClientHandlerTest.Proxy.cs
Expand some tests to include more variations and be consistent about the variations they test
Re-enable a proxy test that's been disabled for a while and is hopefully no longer flaky
Remove checks for HTTP3 as they are not needed because this class is not included in HTTP3 tests
Various minor cleanup 

Contributes to #30205

### CODE REVIEW

**Comment by wfurt** [comment]
Seems like some platforms do not like the change:
```
HttpClientHandlerTest.Proxy.cs(181,49): error CS8400: (NETCORE_ENGINEERING_TELEMETRY=Build) Feature 'not pattern' is not available in C# 8.0. Please use language version 9.0 or greater.
```

**Comment by geoffkizer** [comment]
Strange. These are caused by using "is not null". We definitely use this in the product, so I'm not sure why it would be disallowed in tests, and apparently only on certain platforms... @stephentoub any idea what's going on here?

Regardless, I'll fix it.

**Comment by stephentoub** [comment]
> any idea what's going on here?

Whatever project/target this is set in is probably being compiled with LangVersion set to a version prior to `is not null` being supported.

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/blob/57acd5676678f836e1cbd70decdac5ac8242398c/src/libraries/System.Net.Http.WinHttpHandler/tests/FunctionalTests/System.Net.Http.WinHttpHandler.Functional.Tests.csproj#L6

**Comment by geoffkizer** [comment]
Thanks. Is that intentional/necessary?

**Comment by stephentoub** [comment]
I don't know why it's needed.  We generally set LangVersion to preview or latest for the whole repo.  It was added here:
https://github.com/dotnet/runtime/commit/188243a1ec2abb19f5d37d8274afa1994e848dd2#diff-a53289c23b6308f9f138e1fa9d47f9bb2cb403b4dd73892f623fcc5ea94a3790R6
Maybe @alnikola knows.

I'd say just delete it and see what if anything fails to compile.

**Comment by geoffkizer** [comment]
@wfurt can you review when you have a minute?

**Review by wfurt — APPROVED** [review]
LGTM.

**Pull request merged**
