### PR TITLE
Add support for `TYP_BYREF` `LCL_FLD`s to VN

### PR DESCRIPTION
**Pull request by SingleAccretion**
First, the code in `fgAddFieldSeqForZeroOffset` that was adding zero-offset sequence to `LCL_FLD` directly was incorrect, because `fgAddFieldSeqForZeroOffset` adds a sequence for the address that the passed-in node represents, while adding a field sequence to `LCL_FLD` directly means adding it to the "implicit" `LCL_FLD_ADDR` it indirects. One can reproduce this issue via code like the following (with `JitNoStructPromotion=1`):
```cs
private static int Problem(StructWithRawFldPtr p)
{
    return ((StructWithIndex*)p.RawFldPtr)->Index;
}

struct StructWithRawFldPtr
{
    public nint RawFldPtr;
}

struct StructWithIndex
{
    public int Index;
    public int Value;
}
```
```scala
LCL_FLD   long   V00 arg0         u:1[+0] Fseq[RawFldPtr, Index] (last use)
```
The first two commits fix this issue, in `fgAddFieldSeqForZeroOffset` and similar code in `ChangeOper` and we now get the lovely combination of `LCL_FLD` + zero-offset sequence in the map.
```scala
LCL_FLD   long   V00 arg0         u:1[+0] Fseq[RawFldPtr] (last use) Zero Fseq[Index]
```
That opens a possibility for another bug of course: partial sequences, that is cases where we will have `ADD((LCL_FLD PtrToStatic [Zero FldSeq]), OFFSET FldSeq)` and fail to incorporate the `Zero FldSeq` into the `PtrToStatic`'s VN. This is fixed in the third commit.

Part of #58312.
Contributes to #63768.

[No diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1580735&view=ms.vss-build-web.run-extensions-tab) as expected.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
Will assume the Win-Arm64 timeout is not related (it passed on the previous CI run).

@dotnet/jit-contrib

**Comment by SingleAccretion** [comment]
Pushed some fixes for typos in commit messages (no code changes).

**Review by jakobbotsch — APPROVED** [review]
LGTM, thanks! Just to check my own understanding of the issue here, conceptually we can think of the zero-offset field seqs stored in the lookaside map to mean there is an implict `ADD(x, 0)` on top of the node with `0` having that field seq, but this code was mixing that up with the field accessed by `x`?

**Comment by SingleAccretion** [comment]
> Just to check my own understanding of the issue here, conceptually we can think of the zero-offset field seqs stored in the lookaside map to mean there is an implict ADD(x, 0) on top of the node with 0 having that field seq, but this code was mixing that up with the field accessed by x?

Yep, exactly.

**Pull request merged**
