### PR TITLE
Fix tracing rundown tests with optimizations and large version bubble

### PR DESCRIPTION
**Pull request by janvorli**
The test is failing when compiled with crossgen2 with optimizations and 
large version bubble enabled due to the fact that it didn't find 
System.Diagnostics.Tracing loaded. The reason is that due to cross module 
inlining, the System.Diagnostics.Tracing was not needed anymore.
I have fixed it by checking for presence of either the
Microsoft.Diagnostics.Tracing.TraceEvent or the
System.Diagnostics.Tracing. This works in all compilation modes.
In some compilation modes, one of the two is missing.

### CODE REVIEW

**Comment by jkotas** [comment]
How can compiling with crossgen2 change the events fired for this test?

This looks more like a problem with the test harness / SuperIlc. Is the SuperIlc using the same binaries as the regular runs of the test?

**Comment by janvorli** [comment]
It doesn't change the events. But the cross module inlining inlines a method from the System.Diagnostics.Tracing that just calls into a method in the Microsoft.Diagnostics.Tracing.TraceEvent. So there are no references to anything in System.Diagnostics.Tracing  and the assembly doesn't get loaded.

**Comment by jkotas** [comment]
Ok, `System.Diagnostics.Tracing` is a pure facade. I get why we skip loading it with large version bubbles.

But what guarantees that `Microsoft.Diagnostics.Tracing.TraceEvent` is loaded when `System.Diagnostics.Tracing` is not? I would expect `Microsoft.Diagnostics.Tracing.TraceEvent` to be always loaded.

**Comment by janvorli** [comment]
With old crossgen generated code, for some reason, the Microsoft.Diagnostics.Tracing.TraceEvent is not loaded. My change was originally exactly that - just replacing the System.Diagnostics.Tracing with Microsoft.Diagnostics.Tracing.TraceEvent. Then I have found that it was actually that way a long time ago and then changed to the current state to fix a problem when old crossgen generated code didn't load the Microsoft.Diagnostics.Tracing.TraceEvent for some reason. I've checked and the old crossgen without large version bubble really didn't have it in the list. I have not tried to look at the code to see why though.

**Comment by janvorli** [comment]
@jkotas I have finally got to checking why the Microsoft.Diagnostics.Tracing.TraceEvent was not on the list with the old crossgen without large version bubble and I was unable to repro it. So I guess it must have been some quirk with my local state at that time. 
So I have modified it to just check for the Microsoft.Diagnostics.Tracing.TraceEvent assembly.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
