### PR TITLE
Remove some allocations from ManifestBuilder.CreateManifestString

### PR DESCRIPTION
**Pull request by stephentoub**
Just happened to see this low-hanging fruit while looking at some traces. For the RuntimeEventSource, this removes around 30K of allocation, though that's only ~3% of what gets allocated.

Contributes to https://github.com/dotnet/runtime/issues/44598

cc: @brianrob

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @noahfalk

**Comment by noahfalk** [comment]
cc @davmason @sywhang @josalem

**Review by davmason — APPROVED** [review]
Thanks. I'm a little worried because I don't trust our tests to catch any subtle bugs here, but the change is small enough it's probably fine.

**Comment by stephentoub** [comment]
> I'm a little worried because I don't trust our tests to catch any subtle bugs here, but the change is small enough it's probably fine.

Is there something I could do to make us more confident?

**Review by sywhang — APPROVED** [review]
LGTM - as David mentioned we don't have that many tests that catches manifest generation issues (which we really should add) but this change is fairly small and is pretty well understood. Adding @josalem for another pair of eyes to take a look.

**Review by josalem — APPROVED** [review]
This looks good to me.  I'd be curious to take a look offline at some of the perf data you collected if it's worth sharing.

**Comment by davmason** [comment]
> 
> 
> > I'm a little worried because I don't trust our tests to catch any subtle bugs here, but the change is small enough it's probably fine.
> 
> Is there something I could do to make us more confident?

The thing that needs to happen is to add more tests, which is too much to ask of you for this change. I think it's a small enough change that we can merge.

**Comment by stephentoub** [comment]
Ok, thanks.  Just to put my mind at ease (I don't like changing code when we believe tests to not cover it well), I ran:
```C#
using System;
using System.Diagnostics.Tracing;

Console.WriteLine(EventSource.GenerateManifest(typeof(object).Assembly.GetType("System.Diagnostics.Tracing.NativeRuntimeEventSource"), null));
```
before and after this change, and there were no diffs in the output.

**Comment by stephentoub** [comment]
> I'd be curious to take a look offline at some of the perf data you collected if it's worth sharing.

@josalem, here's an example, looking at startup allocations for a `dotnet new webapi` app:
image

**Pull request merged**
