### PR TITLE
Change ICorJitHost to use char16_t over WCHAR

### PR DESCRIPTION
**Pull request by tonybaloney**
The ICorJitHost interface uses WCHAR for a number of methods.

These methods are for fetching/setting string values for the configuration of the JIT host. The JIT host is a global singleton, so there are a few consumers of this API throughout the compiler.

TODO: 

- [x] update interface
- [x] update main implementation
- [x] update superpmi
- [x] find and locate other references

### CODE REVIEW

**Comment by tonybaloney** [comment]
I noticed the AOT implementation uses `wchar_t`:
https://github.com/dotnet/runtime/blob/main/src/coreclr/tools/aot/jitinterface/jithost.cpp#L30-L89

**Comment by tonybaloney** [comment]
@jkotas @AndyAyersMS please let me know if this PR is helpful/unhelpful and I'll either abandon it or see it through.
From the Git log, it looks like .net 6 is moving to more standard fixed-width types over the Windows alias types. This is one such occurrence that is quite isolated.

**Comment by tonybaloney** [comment]
2 errors from `compiler.cpp`, both impacting this call:

```cpp
    int index = g_jitHost->getIntConfigValue(W("SuperPMIMethodContextNumber"), -1);
```

I'd assume this should be the literal:

`u"SuperPMIMethodContextNumber"` ?

**Comment by jkotas** [comment]
The `W` macro produces `wchar_t*`, but you need `char16_t*` here now. You can try `u"...."`, but I am not sure whether it is going to work.

**Comment by tonybaloney** [comment]
@jkotas after spending more time thinking about this and seeing the thread that ends up being pulled from changing `WCHAR` to `char16_t`, I came to the following conclusion:

1. The integer setting changes are a fairly benign change
2. Most of the uses for the string settings are the **names of files**. Since this is currently `WCHAR`, which is implementation defined AND file names/unicode support is either UTF16LE, UTF16, or UTF32, I'm worried about making that change to `char16_t` to assume 16-bit string representations of file names, albeit unlikely that people are using character sets requiring 32-bits.
3. There are knock-on impacts to `wchar.cpp` and `file.cpp`, which the compiler uses with the results of the string settings. I'm concerned that a reinterpret cast could cause some issues.

Simply changing to `wchar_t` would be a simpler change, keeping the CorJitHost interface to c++ standard specifications, whilst retaining compatibility for the compiler.

**Comment by jkotas** [comment]
`wchar_t` is not going to work. It is 32-bit on non-Windows and 16-bit on Windows. We need a type that is always 16-bit here.

**Comment by tonybaloney** [comment]
In that case, the options are:

1. Leave it as it is :-)
2. Change to char16_t, create overloaded options for `file.cpp` utils and `wchar` util methods for 16-bit Unicode strings. 

@jkotas let me know which the team would want

**Comment by jkotas** [comment]
Out of these two options, I think it is better to leave it as it. I do not think we would want to create overloaded options for `file.cpp` to deal with the fallout.

**Pull request closed without merging**
