### PR TITLE
Add JitStress=1/2 runs to jitstress-isas-x86 pipeline

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
Well, in addition to the Vector256 failure fixed by https://github.com/dotnet/runtime/pull/58820, this run found one additional assert and one test failure (I'll open issues tomorrow). Looks like maybe it exceeded some timeout also?

cc @tannergooding

**Comment by tannergooding** [comment]
> Well, in addition to the Vector256 failure fixed by #58820, this run found one additional assert and one test failure (I'll open issues tomorrow

Can we rerun the leg now that #58820 is merged to help reduce noise and see only the remaining failures? (I don't remember if this PR needs to be updated first for it to correctly pick up the fix).

> Looks like maybe it exceeded some timeout also?

Its definitely possible as we've had issues here in the past. The hardware intrinsic tests cover a few thousand methods and are largely split by ISA and in some cases, like ARM, we've had to explicitly split this further to ensure the individual test runs are small enough.

**Comment by BruceForstall** [comment]
Newly opened issues:
https://github.com/dotnet/runtime/issues/58897
https://github.com/dotnet/runtime/issues/58899

There's not too much noise, so I'm confident these are the only issues. I'll rerun sometime, but maybe this change is ready to be merged and run weekly. I want to look a little more at why the full set of tests didn't seem to run (timeouts or similar).

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib I propose to expand the `runtime-coreclr jitstress-isas-x86` pipeline by running each case with JitStress=1 and JitStress=2. PTAL.

**Comment by kunalspathak** [comment]
Looks good idea to me.

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib I'm ready to merge this, if someone can approve it.

**Review by tannergooding — APPROVED** [review]
LGTM.

It might be interesting to consider if any of the other stress combinations should be tested (possibly on an even longer outer loop given the cost and likely minimal overall benefit).

**Comment by BruceForstall** [comment]
> It might be interesting to consider if any of the other stress combinations should be tested (possibly on an even longer outer loop given the cost and likely minimal overall benefit).

This stress job itself is getting extremely long. I considered splitting it, but didn't want to create new pipelines (which then don't share builds). But it's not clear it's even worth running these stress modes even once a week (during the normal development phase)

**Pull request merged**
