### PR TITLE
Remove stub of special treatment for POSIX char ranges

### LINKED ISSUE #88587: behavior of [:XX:] inside a regex range has changed
```c#
using System.Text.RegularExpressions;
using System;
namespace ConsoleApp13
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(Regex.IsMatch("a", "[[:abc:]aaa]"));
            Console.WriteLine(Regex.IsMatch("a", "[[:abc:]"));
            Console.WriteLine(Regex.IsMatch("a", "[[::]"));
        }
    }
}
```
C:\Users\danmose\source\repos\ConsoleApp13>dotnet run -f net7.0
False
True
Unhandled exception. System.Text.RegularExpressions.RegexParseException: Invalid pattern '[[::]' at offset 5. Unterminated [] set.
   at System.Text.RegularExpressions.RegexParser.ScanCharClass(Boolean caseInsensitive, Boolean scanOnly)
   at System.Text.RegularExpressions.RegexParser.CountCaptures(RegexOptions& optionsFoundInPattern)
   at System.Text.RegularExpressions.RegexParser.Parse(String pattern, RegexOptions options, CultureInfo culture)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, CultureInfo culture)
   at System.Text.RegularExpressions.RegexCache.GetOrAdd(String pattern)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
   at ConsoleApp13.Program.Main(String[] args) in C:\Users\danmose\source\repos\ConsoleApp13\Program.cs:line 11

C:\Users\danmose\source\repos\ConsoleApp13>dotnet run -f net48
True

Unhandled Exception: System.ArgumentException: parsing "[[:abc:]" - Unterminated [] set.
   at System.Text.RegularExpressions.RegexParser.ScanCharClass(Boolean caseInsensitive, Boolean scanOnly)
   at System.Text.RegularExpressions.RegexParser.CountCaptures()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex.IsMatch(String input, String pattern)
   at ConsoleApp13.Program.Main(String[] args) in C:\Users\danmose\source\repos\ConsoleApp13\Program.cs:line 10

```

This is because this line was accidentally deleted in .NET Core 3.1:

https://github.com/dotnet/corefx/pull/30632/files#diff-7ff2e84732300c51d80db48e484683bceed5a053305731fa906ab61d2e94950fL629

It would previously allow `[:XXX:]` where `XXX` is zero or more word chars and the whole is _inside a range_, and simply ignore it. So eg a pattern `[[:digit:]]` which is equivalent to `\d` in PCRE would be evaluated as `[]` an empty range. With the line removed, now it only ignores literally `[::]` in a range.

If this was an attempt to allow the possibility to add support later, it would have been made to reject patterns with these in, so that adding later wouldn't be a breaking change. The oldest copy I can find is from 2002/08/20 and it has "lookup name (nyi)" there too -- my guess is the nyi was intended to be fixed before .NET Framework 1.0.

My suggestion is to now remove this code entirely as it's useless. This would be a breaking change for anyone who has a pattern containing `[::]` inside a range -- which has to be almost literally zero.

### PR DESCRIPTION
**Pull request by danmoseley**
Fix https://github.com/dotnet/runtime/issues/88587

### CODE REVIEW

**Comment by danmoseley** [comment]
@ViktorHofer given this is reacting to your change ;) do you want to do a quick review?

**Review by ViktorHofer — APPROVED** [review]
Thanks for fixing

**Comment by stephentoub** [comment]
Why did you remove this block rather than reverting the line removal that broke the long-standing behavior?

**Comment by danmoseley** [comment]
I put my reasoning in the issue. 

The behavior pre 3.1 was not useful: the value in keeping it would be to avoid breaking patterns that were incorrectly assuming this syntax did anything. I think there would be a reasonable argument for removing it intentionally today if we hasn't already broken it: its most likely a bug, never intended to be shipped this way in 1.0, and we have plenty of precedent for fixing long standing bugs in such a way that code depending on them might be broken if we think the cases are sufficiently unlikely. But in this case, it was already changed in 3.1. Changing back could break anyone relying on the current behavior. I have seen no reports of anyone complaining about the behavior before the change or after the change, consistent with it being not significantly breaking.

**Comment by danmoseley** [comment]
Also this aligns us now with behavior of two of the three other major engines that don't support POSIX classes, as noted in the issue.

**Pull request merged**
