### PR TITLE
Remove Reflection.Emit APIs

### LINKED ISSUE #49452: Add back Reflection.Emit APIs from .NET Framework
As a follow up to #46681 and #49319, I looked at the rest of the APIs that were missing from Reflection.Emit:

```
Compat issues with assembly System.Reflection.Emit:
MembersMustExist : Member 'public System.Reflection.Emit.ModuleBuilder System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule(System.String, System.Boolean)' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'public System.Reflection.Module System.Reflection.Emit.ConstructorBuilder.GetModule()' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'public System.String System.Reflection.Emit.ConstructorBuilder.Signature.get()' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'public System.Reflection.Module System.Reflection.Emit.MethodBuilder.GetModule()' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'public System.String System.Reflection.Emit.MethodBuilder.Signature.get()' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'public System.Diagnostics.SymbolStore.ISymbolDocumentWriter System.Reflection.Emit.ModuleBuilder.DefineDocument(System.String, System.Guid, System.Guid, System.Guid)' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'protected System.ModuleHandle System.Reflection.Emit.ModuleBuilder.GetModuleHandleImpl()' does not exist in the reference but it does exist in the implementation.
MembersMustExist : Member 'public System.Boolean System.Reflection.Emit.ModuleBuilder.IsTransient()' does not exist in the reference but it does exist in the implementation.
Total Issues: 8
```

The following APIs don't exist (and shouldn't) in .NET Core because we don't support saving the generated assembly to disk. (#15704)
* `AssemblyBuilder.DefineDynamicModule`
* `ModuleBuilder.DefineDocument`

The following API is because of an implementation detail, and doesn't need to be exposed since it has never been exposed:
* `ModuleBuilder.GetModuleHandleImpl` (See the [code comment](https://github.com/dotnet/runtime/blob/e341abfa627bb33538bb62ce0c6d51a3d42936f2/src/libraries/System.Private.CoreLib/src/System/Reflection/Module.cs#L23) for an explanation)

That leaves the following APIs to be decided if we should bring them back:

* `Module ConstructorBuilder.GetModule`
* `Module MethodBuilder.GetModule`
* `string ConstructorBuilder.Signature`
* `string MethodBuilder.Signature`
* `bool ModuleBuilder.IsTransient`

1. The `Signature` properties seem pretty simple. They return a string represenation of the signature of the method.

2. The `GetModule()` methods are interesting because these types already have a `Module` property on them. Looking at the code, the `GetModule()` method and the `Module` property don't have the same code, but eventually return the same thing - the module of the type containing this Method.

3. I'm not exactly sure what `IsTransient` means, and the [MSDN doc](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.modulebuilder.istransient) doesn't give a good explanation.

> Returns a value that indicates whether this dynamic module is transient.

Looking at the code, on mono it [always returns `true`](https://github.com/dotnet/runtime/blob/b38ea6a4f067b571a007b2ac69f3e4431cb100e7/src/mono/System.Private.CoreLib/src/System/Reflection/Emit/ModuleBuilder.Mono.cs#L121-L124). On `coreclr`, it calls into the native runtime, and the only place I can see setting the flag, always sets it to `true` as well.

https://github.com/dotnet/runtime/blob/b38ea6a4f067b571a007b2ac69f3e4431cb100e7/src/coreclr/vm/assembly.cpp#L180

__________

So I guess after all that, the only API I'd recommend adding back is the `ConstructorBuilder.Signature` and `MethodBuilder.Signature` properties. I don't think we need to add the other missing APIs.

### PR DESCRIPTION
**Pull request by i3arnon**
Removes all unused leftover Reflection.Emit APIs

Fix #49452

### CODE REVIEW

**Review by krwq — APPROVED** [review]

**Comment by krwq** [comment]
@i3arnon the only thing which is left is to remove `src/libraries/System.Reflection.Emit/src/MatchingRefApiCompatBaseline.txt`

**Comment by krwq** [comment]
@i3arnon seems you got some build errors:

```
/__w/1/s/src/coreclr/vm/ceeload.cpp:12445:37: error: out-of-line definition of 'Create' does not match any declaration in 'ReflectionModule'
ReflectionModule *ReflectionModule::Create(Assembly *pAssembly, PEFile *pFile, AllocMemTracker *pamTracker, LPCWSTR szName, BOOL fIsTransient)
                                    ^~~~~~
/__w/1/s/src/coreclr/vm/ceeload.cpp:12472:14: error: no member named 'SetIsTransient' in 'ReflectionModule'
    pModule->SetIsTransient(fIsTransient ? true : false);
    ~~~~~~~  ^
/__w/1/s/src/coreclr/vm/ceeload.cpp:12501:5: error: use of undeclared identifier 'm_fIsTransient'
    m_fIsTransient = false;
```

**Comment by eerhardt** [comment]
What about 

* `AssemblyBuilder.DefineDynamicModule(System.String, System.Boolean)`
* `ModuleBuilder.DefineDocument(System.String, System.Guid, System.Guid, System.Guid)`

I believe those public methods should be deleted as well

**Comment by i3arnon** [comment]
> What about
> 
> * `AssemblyBuilder.DefineDynamicModule(System.String, System.Boolean)`
> * `ModuleBuilder.DefineDocument(System.String, System.Guid, System.Guid, System.Guid)`
> 
> I believe those public methods should be deleted as well

Should I just delete the API or follow through all the way? It goes quite deep.
Removing `AssemblyBuilder.DefineDynamicModule(System.String, System.Boolean)` obviates `emitSymbolInfo`:

https://github.com/i3arnon/runtime/blob/6351328858949aed8c1ab452bc93339b822d9ba7/src/coreclr/System.Private.CoreLib/src/System/Reflection/Emit/AssemblyBuilder.cs#L348-L356

And it continues from there.
I'm willing to cut as much as possible :), just want to make sure it's fine..

**Comment by eerhardt** [comment]
I think for this PR, let's just remove the public methods. It would definitely go quite deep to start removing the unused `emitSymbolInfo` parameter. I think that refactoring can be done in a follow up PR.

**Comment by i3arnon** [comment]
The test failures don't seem to be related.
Could they be transient? Is it possible to rerun them?

**Comment by jeffhandley** [comment]
I've kicked off a re-run of the failed jobs.

@krwq This PR is assigned to you for follow-up before the RC1 snap.

**Comment by krwq** [comment]
@i3arnon this looks good to me, are you planning to also remove `System.Reflection.Emit.ModuleBuilder.GetModuleHandleImpl`? Seems that's the only extra API now

**Comment by eerhardt** [comment]
> are you planning to also remove System.Reflection.Emit.ModuleBuilder.GetModuleHandleImpl? Seems that's the only extra API now. Consider changing it to just internal if implementation is used in many places

I don't believe we should change this. See the [code comment](https://github.com/dotnet/runtime/blob/e341abfa627bb33538bb62ce0c6d51a3d42936f2/src/libraries/System.Private.CoreLib/src/System/Reflection/Module.cs#L23) for an explanation.

fyi @MichalStrehovsky since this references CoreRT.

**Review by eerhardt — APPROVED** [review]
LGTM. Thanks @i3arnon for the contribution!

**Comment by i3arnon** [comment]
> I think for this PR, let's just remove the public methods. It would definitely go quite deep to start removing the unused `emitSymbolInfo` parameter. I think that refactoring can be done in a follow up PR.

Now that this is merge.. should I do that follow up PR?

**Comment by krwq** [comment]
@i3arnon yes please, if don't have time please create an issue

**Comment by MichalStrehovsky** [comment]
> fyi @MichalStrehovsky since this references CoreRT.

Yeah, the reflection stack in NativeAOT is not implemented in CoreLib so keeping this protected internal allows the NativeAOT reflection stack to override. If we undo that here, we'll need to undo that change in NativeAOT again. Appreciate that we don't have to :).

**Pull request merged**
