### PR TITLE
[WIP] Adding Inline debug info support

### PR DESCRIPTION
**Pull request by BrianBohe**
This branch is in progress, it would probably change in the following weeks. The purpose of this PR is to start having reviews.

[There is an existing issue with a discussions and steps we are following to achieve this.](https://github.com/dotnet/runtime/issues/2399)

### CODE REVIEW

**Comment by danmosemsft** [comment]
Please help add exactly one area label if the bot does not. It teaches the bot.

**Comment by AndyAyersMS** [comment]
Thanks @BrianBohe, looks like a good start.

I am wondering if we should split this up into several PRs. I don't have a full picture but here's a rough suggestion on how to start.

First put up the changes in the jit to keep better track of inline contexts, to (optionally, perhaps) see the context information as part of a dump (and in disassembly), and perhaps add some sanity checks. This seems like a good base layer on the jit side. It should be zero diff which we can verify. I know there are some bugs here and there in maintaining the inline context tree so perhaps we should also flush those out and fix them. 

At this point it would also interesting to keep track of cases where no statement in a method maps to an inline tree node (which we know can happen, for simple inlinees). If this is a frequent occurrence we probably have some bugs to fix. Once those are fixed, if this is still a frequent occurrence, we may need to think about finer-grained tracking.

Then perhaps add in the ability to optionally track IL offsets for inline methods. I worry this may perturb existing logic in the jit and I would like to be able to consider this part in isolation. For example we can inline at non-stack empty points, so what does it mean when we to reach a stack empty in an inlinee's IL? Likely we need to think this through carefully. This also should be zero diff if disabled, which we can verify.

Then add in the ability to report all this via the debugger info...

**Comment by BrianBohe** [comment]
I have some questions to you @AndyAyersMS :
1. What is the benefit of tracking the inline context on the statements if we don't track also the IL offset of the statement in its original function? One can't figure out how the call stack is having only the name of the inline functions in some order if you could have more than one call to the method B inlined in method A.
2. I have only modified the IL offset checks that already exists. What do you mean with sanity checks for inline context? I have added some checks for debug mode when creating 
3. I have already added information to the dump. The statements dump the function from which they are imported (if they are imported), most of new debug info is created when [genIPmappingGen is happening](https://github.com/dotnet/runtime/blob/4419abf6ee40803089af6cddb2c0dbc60f24a380/src/coreclr/src/jit/codegencommon.cpp#L10972-L11003) and it is [dumped there](https://github.com/dotnet/runtime/blob/4419abf6ee40803089af6cddb2c0dbc60f24a380/src/coreclr/src/jit/ee_il_dll.cpp#L973). Do you think that is enough? Dumping the whole Inline Context tree seems to be much more verbose and it was useless in my case.
4. I was considering adding a compilation flag or a COMPlus_XXX var to avoid generating this information by default. I guess with that off the disassembly will be exactly the same as before. How much time do you think it could take to add information to that disassembly?
5. What are the problems related to non-stack empty points or stack empty points in a inlinee's IL if we are not tracking the variables of the inline method?

**Comment by AndyAyersMS** [comment]
> What is the benefit of tracking the inline context on the statements if we don't track also the IL offset of the statement in its original function

I find it very helpful to break down work like this into a series of PRs, each of which has a clearly stated goal and a way of verifying that goal has been accomplished. 

So, to me, these are separate incremental steps worthy of PRs: first make sure we have reasonable inline contexts for all statements; then make sure we have reasonable IL offsets for all statements.

You don't actually have to develop this way. You can change a bunch of things as you are prototyping, to make sure you've examined the problem end to end, and to build confidence you know all the changes that are needed. But once you have built up an interesting set of changes, you need to think about how to present the work, and here you can benefit by re-expressing what you've done in the form above. Git's ability to merge, split, and reorder commits can come in handy here.

> What do you mean with sanity checks for inline context?

Make sure all statements have inline contexts, and (where possible) that they are the right contexts.

> I have already added information to the dump. How much time do you think it could take to add information to that disassembly?

I think having this information in the disassembly is an interesting step; there are non-jit folks and tools that look at the disasm stream.

Not sure how much time it would take. I would hope not much more than a day or two. It can be off by default initially.

> Dumping the whole Inline Context tree seems to be much more verbose and it was useless in my case.

Right, it is too verbose. But  dumping the name of the inlinee is not sufficient . Each node in the tree has a unique index, so you could dump that too; for more context one can then go back and consult the tree.

> What are the problems related to non-stack empty points or stack empty points in a inlinee's IL if we are not tracking the variables of the inline method?

It depends on what the debugger does with this information. I would guess that the debugger only allows users to set breakpoints at stack empty points. So that would suggest that we should report any inlinee stack empty point as a stack empty point, and not worry about the fact that there might have been things on the stack at the point of the call.

**Comment by BruceForstall** [comment]
> Each node in the tree has a unique index, so you could dump that too; for more context one can then go back and consult the tree.

Would it also be useful to dump the inline depth at a particular location?

**Comment by AndyAyersMS** [comment]
I think we can probably close this.

**Comment by AndyAyersMS** [comment]
Going to close -- ideas here are good but likely require some more thinking.

**Pull request closed without merging**
