### PR TITLE
improve protocol detection in jail

### PR DESCRIPTION
**Pull request by wfurt**
When running simple socket code in jail on freebsd with ipv6=disabled (default), we try to use dual mode socket even if that is not supported. 
The problem is that the current detection code expects only `EAFNOSUPPORT` but it fails with `EPROTONOSUPPORT`.
This change makes both errors indicating that given AF is not available. 

contributes to #14537
cc: @Thefrank

### CODE REVIEW

**Comment by geoffkizer** [comment]
Are we sure this isn't going to catch some valid cases too?

We are passing '0' for the ProtocolType here, which seems weird. It seems possible that this is not valid in jail, and thus is the reason we see the EPROTONOSUPPORT.

**Comment by wfurt** [comment]
The original report come from:
```c#
using System;
using System.Net.Sockets;

namespace SocketsApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine($"IPV4/IPV6Supported: {Socket.OSSupportsIPv4}/{Socket.OSSupportsIPv6}");
            using (var s = new Socket(SocketType.Stream, ProtocolType.Tcp))
            {
                Console.WriteLine("Created a socket with default IPV6 address family and dual mode.");
            }
        }
    }
}
```
and that fails with same error. So I don't think it is the 0. https://github.com/dotnet/runtime/issues/14537#issuecomment-997334759

For background, as the FreeBSD runtime got some traction, people start building apps. And by default all the package builds do run within jail (with IPv6 off by default)

**Comment by geoffkizer** [comment]
Interesting, thanks for the info.

Given this, the change seems reasonable. I think we should add a comment with the above info since it's not obvious.

**Comment by geoffkizer** [comment]
Possibly we should limit this to FreeBSD as well, since it seems like a bit of a quirk of FreeBSD jail behavior? Not sure...

**Comment by Thefrank** [comment]
This is likely due to how FreeBSD abstracts jails.

This happens when the main system has IPv6 enabled (along with IPv4) but IPv6 is disabled along with "VNET" in the jail also being disabled (security.jail.vnet: 0). 

`sysctl` can be used to check if its running in a jail as `security.jail.jailed` will be 1 if jailed and 0 if not. 

Many other jail related settings are under `security.jail` that might be useful to probe if making platform specific tests/checks/workarounds.  

I think both the Linux kernel and OSX will use `EPROTONOSUPPORT` if you try and do something like make an IPv6 socket when IPv6 is disabled. 

There is an extremely long read in the man page (https://www.freebsd.org/cgi/man.cgi?jail(8)) if you want to do a deep dive but I don't think its warranted here unless someone wants to make dotnet / runtime more aware of if its running in jail or not.

**Comment by wfurt** [comment]
I spent some time looking at Linux kernel. You can get `EPROTONOSUPPORT` in case when given family _is_ available but not particular sub-protocol. Like there is check that it is `IPPROTO_IP` for inet/inet6. The 0 we pass in is both `ProtocolType.Ip` and `ProtocolType.Unspecified`. So the likelihood we would ever get it is slim IMHO. 

I could add check for the OS but it seems like extra work for typical case. I can certainly add some comment. 
Adding @tmds for any additional thoughts. 

While there is some work in runtime to detect docker and read some info via cgroups, I don't think we are at that point with Jail. I would feel we do not need to detect presence of jail at this point to keep things simple.

**Comment by tmds** [comment]
@wfurt confirming what you said: the OS check is not needed. Linux won't return `EPROTONOSUPPORT` when the address family is supported for the socket that is created here.

**Review by geoffkizer — APPROVED** [review]

**Comment by geoffkizer** [comment]
Sounds reasonable. Let's just add a comment explaining the need for this on FreeBSD.

**Review by Thefrank — APPROVED** [review]

**Pull request merged**
