### PR TITLE
Deduplicate several special classes of JIT/Methodical tests

### PR DESCRIPTION
**Pull request by trylek**
/cc @dotnet/jit-contrib

### CODE REVIEW

**Review by BruceForstall — APPROVED** [review]

**Comment by am11** [comment]
@trylek, this is just for my own knowledge; will the duplicate code be deleted separately or does deduplication refer to something else in this context?

Looking at the stats (+323 −292) it suggest as if the "deletion" part is missing (since more code was added). 😄

**Comment by trylek** [comment]
@am11 - sorry about the confusion, I may have used imprecise terminology; in context of this and a couple of other changes by 'deduplication' I mean tweaking the tests to remove duplications w.r.t. namespace and type names used in the tests that is a pre-requisite to running them in-proc using the merged test wrapper. For instance, tons of tests used to use the same namespace <code>JitTest</code> and the same class name <code>Test</code> containing the test entrypoint that made them hard to call from the merged wrapper.

**Pull request merged**
