### PR TITLE
[6.0] Bump Ubuntu 19.10 queues to 22.04

### PR DESCRIPTION
**Pull request by carlossanlop**

### CODE REVIEW

**Review by hoyosjs — COMMENTED** [review]
If the queue and the containers contain the same assets, all good. The queues were already 22.04 - this just changes it from 19 container to 22 VM. Is that what you intended?

**Comment by carlossanlop** [comment]
Yes because 19.10 is EOL

**Comment by carlossanlop** [comment]
CI failures are unrelated and already got a fix merged in the staging branch: https://github.com/dotnet/runtime/issues/93491

**Review by dougbu — APPROVED** [review]
lgtm though I can't comment on the validation failures

**Pull request merged**
