### PR TITLE
Ignore some tests on macOS only due to small stack size

### PR DESCRIPTION
**Pull request by EgorBo**
Rationale: https://github.com/dotnet/runtime/issues/87879#issuecomment-1667717261

This PR enables these tests back on non-macOS platforms + disables HugeArray1 on macOS since it hits the same issue too (e.g. in https://github.com/dotnet/runtime/runs/15626705312)

### CODE REVIEW

**Comment by EgorBo** [comment]
@jkotas @jakobbotsch PTAL - this PR doesn't "resolve" https://github.com/dotnet/runtime/issues/87879 but there is no need in disabling the tests for all platforms when only mac is affected

**Review by jkotas — APPROVED** [review]

**Pull request merged**
