### PR TITLE
Revert "Libunwind1.5rc2 (#36027)"

### PR DESCRIPTION
**Pull request by safern**
This change is causing all libraries tests to crash on startup in Linux arm64 (all distros):
https://github.com/dotnet/runtime/pull/36027

I ran a rolling build with this revert in order to prove this:
https://dev.azure.com/dnceng/public/_build/results?buildId=657428&view=results

cc: @sdmaclea @janvorli @jkotas @hoyosjs

### CODE REVIEW

**Comment by safern** [comment]
I wonder if the arm64 libraries tests should run on PRs for coreclr changes only until we get more capacity... @jashook? 

Also another alternative would be to add an arm only leg that could be triggered by comments in the meantime for arm specific changes.

**Comment by jashook** [comment]
@safern  I am confused shouldnt this have been caught in pr as we run linux arm64 currently.

**Comment by safern** [comment]
> @safern I am confused shouldnt this have been caught in pr as we run linux arm64 currently.

You're right, but we don't run the libraries tests for coreclr only changes on linux arm64, this is the build for that PR:
image

**Comment by jashook** [comment]
I think this may have been an assumption on my part. We should be running arm64/arm32 libraries testing on coreclr prs. It is much more valuable than running them for all libraries changes imo.

**Comment by jashook** [comment]
My guess is that the comment holds true for mono changes as well. /cc @naricc

**Comment by safern** [comment]
> I think this may have been an assumption on my part. We should be running arm64/arm32 libraries testing on coreclr prs. It is much more valuable than running them for all libraries changes imo.

I agree. Checked, or release coreclr?

**Comment by jashook** [comment]
Checked

**Review by sdmaclea — APPROVED** [review]
I am assuming this is a full revert.
I will investigate.
We should of course run arm64 libraries tests on coreclr PR if we can afford it.

**Comment by safern** [comment]
Enabling that here: https://github.com/dotnet/runtime/pull/36910

**Comment by am11** [comment]
> to crash on startup in Linux arm64

@sdmaclea, just curious about `startup`; some tests for arm64 target did failed in your PR, when you upstreamed a PR (which was merged post-rc2). Weren't they of same *startup runtime with libunwind* nature?

**Comment by safern** [comment]
Failures are unrelated. The ones from rolling build I’ve taken care of. 

Coreclr Runtime tests is: https://github.com/dotnet/runtime/issues/36850

Mono runtime test I couldn’t find an issue yet, will open one. cc: @naricc

**Comment by sdmaclea** [comment]
@am11 not sure what you meant the final draft of #36027 passed CI w/o any failing tests.  In an early draft they were of a similar nature perhaps...

**Comment by am11** [comment]
@sdmaclea, right, there were some tests which helped spotting this arm64 issue https://github.com/dotnet/runtime/pull/36027#discussion_r426974991. So I meant are there certain class of tests in coreclr which partly(?) validate libunwind initialization? If so can we also update them so they validate a entire startup flow of a dotnet library for sanity testing of future updates (locally). As I remember, we do not execute libunwind provided tests in dotnet/runtime CI,.

**Comment by sdmaclea** [comment]
@am11 I was actually referring to CoreClr tests.  I had never run the libunwind tests at the time I wrote that comment.

I just ran the 1.3-rc1 libunwind tests.  I am seeing 23 of 34 tests passing.
```
PASS: test-proc-info
PASS: test-static-link
PASS: test-strerror
PASS: Gtest-bt
PASS: Ltest-bt
../config/test-driver: line 107: 13626 Bus error               (core dumped) "$@" > $log_file 2>&1
FAIL: Gtest-exc
../config/test-driver: line 107: 13646 Bus error               (core dumped) "$@" > $log_file 2>&1
FAIL: Ltest-exc
PASS: Gtest-init
PASS: Ltest-init
../config/test-driver: line 107: 13712 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: Gtest-concurrent
../config/test-driver: line 107: 13739 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: Ltest-concurrent
PASS: Gtest-resume-sig
PASS: Ltest-resume-sig
PASS: Gtest-resume-sig-rt
PASS: Ltest-resume-sig-rt
PASS: Gtest-trace
PASS: Ltest-trace
../config/test-driver: line 107: 13882 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: Ltest-init-local-signal
FAIL: Ltest-mem-validate
PASS: test-async-sig
PASS: test-flush-cache
PASS: test-init-remote
PASS: test-mem
PASS: test-reg-state
PASS: Ltest-varargs
PASS: Ltest-nomalloc
PASS: Ltest-nocalloc
PASS: Lrs-race
FAIL: test-ptrace
PASS: test-setjmp
FAIL: run-check-namespace
FAIL: run-ptrace-mapper
FAIL: run-ptrace-misc
FAIL: run-coredump-unwind
============================================================================
Testsuite summary for libunwind 1.3-rc1
============================================================================
# TOTAL: 34
# PASS:  23
# SKIP:  0
# XFAIL: 0
# FAIL:  11
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to libunwind-devel@nongnu.org
============================================================================
```
I'll take a look at 1.5rc2 and see if there was a regression.

**Comment by sdmaclea** [comment]
I don't see any improvement or regression in the arm64 libunwind test results checking several versions between 1.3-rc1 and 1.5-rc2.  All versions had the same 11 tests failing.

**Comment by am11** [comment]
Right, libunwind tests are flaky and some of them even failed on Linux x64 when I was running them in a VM and container. On Alpine x64, more tests fail. These are persistent issues across the libunwind versions and maintainers are aware of it.

> I was actually referring to CoreClr tests.

Yes, this bit is also interesting for new platforms. We have ported libunwind to SunOS-derived platforms in v1.5x, and since upstream tests are flaky (sometimes five, and sometimes six tests fail but it is still "better" than results from linux machine), I wanted to test it against the actual CoreCLR and catch issues earlier in the process.

* Do you remember name of one or few of those CoreCLR tests you were referring to?
* Do you have name of one or few of library test that was failing which caused this revert?
* [If possible] Can we enhance those coreclr tests to also cover the scenario caught by libraires tests, which caused this revert? So one set of tests are enough to cover all features of libunwind in use.

**Comment by safern** [comment]
> Do you have name of one or few of library test that was failing which caused this revert?

All test libraries where crashing on startup: 

https://helix.dot.net/api/2019-06-17/jobs/c4ccea9c-b53d-4bf1-92d5-a45c891c64b6/workitems/Invariant.Tests/console

Note that they were crashing on Alpine arm64 only.

**Comment by sdmaclea** [comment]
That would have been nice to know.  It is a huge smoking gun.

**Comment by safern** [comment]
> That would have been nice to know. It is a huge smoking gun.

Yeah, sorry about that. The build had multiple failures and I missed it was only on alpine arm64. I just realized that.

**Pull request merged**
