### PR TITLE
Replace remaining constants to Array.MaxLength

### PR DESCRIPTION
**Pull request by huoyaoyuan**
Did a full search for 0x7FFFFFC7.
Add comment for places cannot be replaced.

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
I wonder if it's worth updating the devdoc on `Array.MaxLength` as part of this PR.

@jkotas @tannergooding - please correct me if I'm mistaken, but `Array.MaxLength` is only valid for szarrays, correct? That is, the expression `new T[len]` for _len \> Array.MaxLength_ is guaranteed to fail, but the expression `Array.Length` may return a value _\> Array.MaxLength_, correct?

**Comment by jkotas** [comment]
Yes, that's right.

**Comment by jkotas** [comment]
And I agree that it would be nice to update the doc block in `src\libraries\System.Private.CoreLib\src\System\Array.cs` to explicitly mention szarrays (single-dimensional array with a zero lower bound).

**Comment by huoyaoyuan** [comment]
CI failure looks unrelated.

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by GrabYourPitchforks** [comment]
Thanks @huoyaoyuan for getting to this and for updating the doc! :)

**Pull request merged**
