### PR TITLE
Fix the osx arm64 build.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by directhex** [comment]
I'm seeing
```
/Users/directhex/Projects/runtime/src/mono/mono/utils/mono-context.c
  /Users/directhex/Projects/runtime/src/mono/mono/utils/mono-context.c:560:2: error: implicit declaration of function 'UCONTEXT_REG_SET_SP' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
          UCONTEXT_REG_SET_SP (sigctx, mctx->regs [ARMREG_SP]);
          ^
  1 error generated.
```

Does your change also need a definition for UCONTEXT_REG_SET_SP, as well as UCONTEXT_REG_SET_PC?

**Review by directhex — APPROVED** [review]

**Comment by directhex** [comment]
Do we have to wait on (broken) CI here? Can we even validate this in CI?

**Comment by CoffeeFlux** [comment]
In theory the install script issue should be fixed now, so restarting the lanes.

**Comment by steveisok** [comment]
I incorporated it into https://github.com/dotnet/runtime/pull/47864 and yes, it works.  Presumably we could close this PR.

**Pull request closed without merging**
