### PR TITLE
JIT: optimize "o is byte[]" casts

### PR DESCRIPTION
**Pull request by EgorBo**
Follow up to https://github.com/dotnet/runtime/pull/75816 that optimized such checks for exact classes.

Array of integers, bytes, etc are special and can be casted to their signed/unsigned equivalents, so let's expand `isinst` for them to handle at least one of the cases as a fast path. Presumably, it's a rare case when e.g. `obj is int[]` and `obj` is `uint[]`. In theory we can check for both without the fallback but that will require a new JIT-EE API with extra complexity while I think the declaration type is the most likely target.

```csharp
bool IsByteArray(IEnumerable o) => o is byte[];
```
Current codegen:
```asm
; Method Tests:IsByteArray(System.Collections.IEnumerable):bool:this
G_M51298_IG01:             
       4883EC28             sub      rsp, 40
G_M51298_IG02:              
       48B920FD447CFE7F0000 mov      rcx, 0x7FFE7C44FD20      ; ubyte[]
       FF155472FBFF         call     [CORINFO_HELP_ISINSTANCEOFARRAY]
       4885C0               test     rax, rax
       0F95C0               setne    al
       0FB6C0               movzx    rax, al
G_M51298_IG03:            
       4883C428             add      rsp, 40
       C3                   ret      
; Total bytes of code: 34
```
New codegen:
```asm
; Method Tests:IsByteArray(System.Collections.IEnumerable):bool:this
G_M51298_IG01:              
       4883EC28             sub      rsp, 40
G_M51298_IG02:             
       488BC2               mov      rax, rdx
       4885C0               test     rax, rax
       741F                 je       SHORT G_M51298_IG05
G_M51298_IG03:         
       48B920FDB976FE7F0000 mov      rcx, 0x7FFE76B9FD20      ; ubyte[]
       483908               cmp      qword ptr [rax], rcx
       7410                 je       SHORT G_M51298_IG05
G_M51298_IG04:             
       48B920FDB976FE7F0000 mov      rcx, 0x7FFE76B9FD20      ; ubyte[]
       FF153D72FBFF         call     [CORINFO_HELP_ISINSTANCEOFARRAY]
G_M51298_IG05:             
       4885C0               test     rax, rax
       0F95C0               setne    al
       0FB6C0               movzx    rax, al
G_M51298_IG06:             
       4883C428             add      rsp, 40
       C3                   ret      
; Total bytes of code: 57
```

### CODE REVIEW

**Comment by jkotas** [comment]
You can make similar argument for all `o is InexactType` cases. Why do we want to do this for arrays and not the other cases - do you have any data to support this?

The problem with the `o is InexactType` is that it tends to be used as part of the pattern matching and execute the fallback pretty frequently.

**Comment by EgorBo** [comment]
> You can make similar argument for all `o is InexactType` cases. Why do we want to do this for arrays and not the other cases - do you have any data to support this?
> 
> The problem with the `o is InexactType` is that it tends to be used as part of the pattern matching and execute the fallback pretty frequently.

@jkotas Thanks, also realized that when I was looking at [this](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/src/System/Linq/Enumerable.cs#L28-L36).
So converting this to double MT check without the fallback, do I understand it correctly that I need to special case these:
```
 byte[], sbyte[]
 short[], ushort[]
 int[], uint[]
 long[], ulong[]
 IntPtr[], UIntPtr[] /nint/nuint
```
other primitives like `bool`, `float`, `double` (pointers, I assume, aren't allowed) are fine with a single pMT check?

**Comment by jkotas** [comment]
Nope. This prints true:
```
object a = new MyEnum[1];

Console.WriteLine(a is int[]); 

enum MyEnum
{
}
```

**Comment by EgorBo** [comment]
Ah, totally forgot about the Enums it makes it way more difficult then 🙁

**Comment by EgorBo** [comment]
Technically still can be allowed for some primitives where we can't use Enums: `char`, `bool`, `float`, `double`, `pointer`, although, it's probably possible via IL/dynamically emitted code

**Pull request closed without merging**
