### PR TITLE
Skip sys/sysctl.h on linux in mono

### PR DESCRIPTION
**Pull request by am11**
Fixes three warnings:
```sh
  [ 56%] Building C object mono/mini/CMakeFiles/monosgen-objects.dir/__/utils/mono-mmap.c.o
  In file included from /runtime/src/mono/mono/utils/mono-mmap.c:23:
  /usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: warning: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Wcpp]
     21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
        |  ^~~~~~~
# snip
  [ 59%] Building C object mono/mini/CMakeFiles/monosgen-objects.dir/__/utils/mono-time.c.o
  In file included from /runtime/src/mono/mono/utils/mono-proclib.c:42:
  /usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: warning: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Wcpp]
     21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
        |  ^~~~~~~
  [ 59%] Building C object mono/mini/CMakeFiles/monosgen-objects.dir/__/utils/mono-uri.c.o
  [ 59%] Building C object mono/mini/CMakeFiles/monosgen-objects.dir/__/utils/mono-poll.c.o
  In file included from /runtime/src/mono/mono/utils/mono-time.c:107:
  /usr/include/x86_64-linux-gnu/sys/sysctl.h:21:2: warning: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Wcpp]
     21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
        |  ^~~~~~~
```

With this PR: 0 warnings - http://sprunge.us/96kyq9

Like in src/libraries/Native, skip linux from sys/sysctl.h check. For other systems, `check_include_files` (instead of `check_include_file` (singular)) when a header depends on another one.
 
Also, simplified few conditions: "is linux" check supersedes "is android".

### CODE REVIEW

**Comment by am11** [comment]
cc @akoeplinger

**Comment by Thefrank** [comment]
FYI: FreeBSD doesn't have a mono section in CI yet as https://github.com/dotnet/runtime/issues/57487 is still pending. 

I don't foresee the change breaking FreeBSD

**Comment by am11** [comment]
The introspection check for sysctl.h is ported from libs.native subset, so it is as good / safe. Harmonizing configs generally reduces the risk of breakage. :)

**Comment by am11** [comment]
It would be nice to replace `ac_check_headers` function with explicit `check_include_files()`  calls (one line per header), like we have in coreclr, libs, corehost and tests. Some of the headers are unused, and some have dependencies (like sys/sysctl.h requires sys/types.h).
@akoeplinger, @vargaz, @lambdageek, wdyt? I can give it a go as part of this PR.

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
> I can give it a go as part of this PR.

I prefer to do it in a separate PR. We could also add parameter(s) for the dependent headers to `ac_check_headers`  to keep the shared `HAVE_*` logic, but I don't feel strongly about it.

**Pull request merged**
