### PR TITLE
[NO-MERGE] Experimental linker map diffing tool

### PR DESCRIPTION
**Pull request by trylek**
At this point I don't intend this to be merged in, I'm just putting
out the PR to share the code and possibly discuss the various diffs
and their relationship to the Ninja switchover.

Thanks

Tomas

Related to: https://github.com/dotnet/runtime/pull/41897

/cc: @dotnet/runtime-infrastructure

### CODE REVIEW

**Comment by trylek** [comment]
Diff for map file set shared by Jeremy on 9/11: https://gist.github.com/trylek/6332a43f4b7166e29443fe16a19fbb8c

**Comment by trylek** [comment]
Initial observations:

1) As you can see in the final summary tables, the biggest total size decrease is in the ".rdata" section (read-only data). In InjectResource.map, for instance, .rsrc$01 and .rsrc$02 are both zero indicating we may be missing some resources in the Ninja version of the executable;

2) Some method variations involve fluctuations regarding one of the initial letters in the mangled identifiers, possibly caused by different calling conventions or some such ambient property;

3) other than that, method size fluctuations are generally minor but existent, possibly indicating size vs. speed optimization differences as Jeremy mentioned.

**Comment by trylek** [comment]
This is a typical tell-tale diff in <code>mscordbi</code>; are we using the same compiler version & options in the two branches? 

<pre>
     Delta       Left      Right   Method changed size
----------------------------------------------------------
      1392          0       1392   __chkstk
     -1392       1392          0   _alloca_probe
</pre>

**Comment by trylek** [comment]
Similar example in <code>superpmi-shim-collector</code>, looks like we're doing the same thing two different ways in the two builds:

<pre>
        64          0 (00000000)         64 (00000040)   _pDefaultRawDllMain
       -64         64 (00000040)          0 (00000000)   _pRawDllMain
</pre>

**Comment by jkoritzinsky** [comment]
Thanks for the initial pointers to checkable diffs. I'll take a look at these targets and see if I can figure out which options differ between the two (they should be using the same compiler toolkit)

**Comment by jkoritzinsky** [comment]
I matched the compiler flags for mscordbi and cordbdbi (where the diffs look to be coming from) and I'm still seeing size differences. I'll keep investigating, but I'm getting increasingly confused.

**Comment by janvorli** [comment]
How about the linker flags? They could also be contributing to size differences.

**Comment by jkoritzinsky** [comment]
Linked flags matched too as far as I could tell.

**Pull request closed without merging**
