### PR TITLE
Use `gtEffectiveVal` for `GT_ADD` op1 in `optCreateAssertion`

### PR DESCRIPTION
**Pull request by TIHan**
**Description**

Using `gtEffectiveVal` in `optCreateAssertion` for the case of `GT_ADD`'s op1 when it's a byref. Helps propagation for non-null assertions. Thanks for @jakobbotsch for guiding me to this solution.

**Acceptance Criteria**

- [x] Passes CI

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Can you identify _why_ this is an improvement? I think it would be better if we could fix the places that benefit from this instead of complicating CSE to compensate for limitations in downstream phases.

That would likely also catch more cases since it wouldn't be limited to first operands, so maybe you could get bigger improvements.

**Comment by TIHan** [comment]
More trees are able to be picked up by constant/assertion prop; the diffs show improvements.

Another alternative could be to change how constant/assertion prop pick up more ops with commas by using effectiveval?

**Comment by jakobbotsch** [comment]
> More trees are able to be picked up by constant/assertion prop; the diffs show improvements.

I think we should try to understand this in a little more detail. Assertion prop uses a tree order and it is not immediately obvious to me why how lifting a comma like this would affect it. There is a transform in `optAssertionProp_Ind` that looks at child nodes of `GT_ADD` trees -- maybe that's where this helps?

> Another alternative could be to change how constant/assertion prop pick up more ops with commas by using effectiveval?

If this is doable it would seem better to me.

**Comment by jakobbotsch** [comment]
> There is a transform in optAssertionProp_Ind that looks at child nodes of GT_ADD trees -- maybe that's where this helps?

Note that #69808 that I just merged affects that particular `GT_ADD` transform.

**Comment by TIHan** [comment]
The majority of improvements here are from 'GT_ADD' with addr and const; just recently discovered it earlier.

**Comment by TIHan** [comment]
Regarding my experiments with rooting `GT_COMMA`s, the main goal is to create side-effectless nodes, so ops like `GT_ADD`, `GT_SUB`, etc, would only have `LCL_VAR`s, `CNS`s, etc as the operands, no commas - they don't have any "interference". I imagine there are places that do not use `gtEffectiveVal` when looking at patterns, so these nodes with commas as their operands are not getting picked up. This is basically why https://github.com/dotnet/runtime/pull/69770 showed improvements, by not having the `COMMA(ASG(LCL_VAR, ...), LCL_VAR)` as the operands of SubMulDiv.

> If this is doable it would seem better to me.

Looking at `optAssertionProp_Ind`, it's not immediately clear how I should use `gtEffectiveVal` for the op to be propagated; you have any suggestions on how it should be used?

**Comment by jakobbotsch** [comment]
> Looking at `optAssertionProp_Ind`, it's not immediately clear how I should use `gtEffectiveVal` for the op to be propagated; you have any suggestions on how it should be used?

Does it not work to use `gtEffectiveVal` when accessing `op1` for that particular transform?
You might also need to change the code below to properly propagate `GTF_EXCEPT` to the indirection when it marks the indirection as non-faulting. Something like

```diff
         tree->gtFlags &= ~GTF_EXCEPT;
+        tree->gtFlags |= tree->AsIndir()->Addr()->gtFlags & GTF_EXCEPT;
         tree->gtFlags |= GTF_IND_NONFAULTING;
```

In fact, I think that ought to be the code there in any case.

**Comment by jakobbotsch** [comment]
I took a closer look at what happens here. In the example I looked at, before this change we have a tree like:
```scala
N015 ( 10, 10) [000023] -A-XG---R--                         ▌  ASG       int    <l:$209, c:$208>
N014 (  1,  1) [000022] D------N---                         ├──▌  LCL_VAR   int    V04 tmp2         d:1 $VN.Void
N013 ( 10, 10) [000005] -A-XG------                         └──▌  ADD       int    <l:$248, c:$247>
N011 (  8,  8) [000014] -A-XG------                            ├──▌  IND       int    <l:$243, c:$244>
N010 (  6,  6) [000037] -A-XG--N---                            │  └──▌  ADD       byref  <l:$144, c:$143>
N008 (  5,  5) [000048] -A-XG------                            │     ├──▌  COMMA     ref    <l:$202, c:$203>
N006 (  4,  4) [000046] -A-XG---R--                            │     │  ├──▌  ASG       ref    $VN.Void
N005 (  1,  1) [000045] D------N---                            │     │  │  ├──▌  LCL_VAR   ref    V05 cse0         d:1 <l:$202, c:$203>
N004 (  4,  4) [000009] ---XG------                            │     │  │  └──▌  IND       ref    <l:$202, c:$203>
N003 (  2,  2) [000039] -------N---                            │     │  │     └──▌  ADD       byref  $140
N001 (  1,  1) [000001] -----------                            │     │  │        ├──▌  LCL_VAR   ref    V01 arg0         u:1 $80
N002 (  1,  1) [000038] -----------                            │     │  │        └──▌  CNS_INT   long   8 field offset Fseq[_builder] $100
N007 (  1,  1) [000047] -----------                            │     │  └──▌  LCL_VAR   ref    V05 cse0         u:1 <l:$202, c:$203>
N009 (  1,  1) [000036] -----------                            │     └──▌  CNS_INT   long   16 field offset Fseq[hackishFieldName] $101
N012 (  1,  1) [000004] -----------                            └──▌  CNS_INT   int    -1 $41
```

whereas after this change we have:
```scala
STMT00006 ( 0x000[E-] ... ??? )
N015 ( 12, 11) [000023] -A-XG---R--                         ▌  ASG       int    <l:$209, c:$208>
N014 (  1,  1) [000022] D------N---                         ├──▌  LCL_VAR   int    V04 tmp2         d:1 $VN.Void
N013 ( 12, 11) [000005] -A-XG------                         └──▌  ADD       int    <l:$248, c:$247>
N011 ( 10,  9) [000014] -A-XG------                            ├──▌  IND       int    <l:$243, c:$244>
N010 (  7,  7) [000048] -A-XG------                            │  └──▌  COMMA     byref  <l:$202, c:$203>
N006 (  4,  4) [000046] -A-XG---R--                            │     ├──▌  ASG       ref    $VN.Void
N005 (  1,  1) [000045] D------N---                            │     │  ├──▌  LCL_VAR   ref    V05 cse0         d:1 <l:$202, c:$203>
N004 (  4,  4) [000009] ---XG------                            │     │  └──▌  IND       ref    <l:$202, c:$203>
N003 (  2,  2) [000039] -------N---                            │     │     └──▌  ADD       byref  $140
N001 (  1,  1) [000001] -----------                            │     │        ├──▌  LCL_VAR   ref    V01 arg0         u:1 $80
N002 (  1,  1) [000038] -----------                            │     │        └──▌  CNS_INT   long   8 field offset Fseq[_builder] $100
N009 (  3,  3) [000037] ----G--N---                            │     └──▌  ADD       byref  <l:$144, c:$143>
N007 (  1,  1) [000047] -----------                            │        ├──▌  LCL_VAR   ref    V05 cse0         u:1 <l:$202, c:$203>
N008 (  1,  1) [000036] -----------                            │        └──▌  CNS_INT   long   16 field offset Fseq[hackishFieldName] $101
N012 (  1,  1) [000004] -----------                            └──▌  CNS_INT   int    -1 $41
```

In the former case we do not manage to create an assertion that `cse0` is non-null even after the indirection `[000014]`. That's because we hit the comma in the following loop, which is probably where you could add `gtEffectiveVal()`:
https://github.com/dotnet/runtime/blob/bad2ab053c53f68a9b7b8ed7d0867fc58261bc9a/src/coreclr/jit/assertionprop.cpp#L1342-L1358

**Comment by TIHan** [comment]
Just used `gtEffectiveVal` and the results are looking quite similar. 

Personally, I would rather have trees normalized in a way where you wouldn't have to rely on `gtEffectiveVal` as it's just another thing that we have to keep in our mind; paying some complexity cost up front so that later phases don't have to worry about peeking into commas.

**Comment by jakobbotsch** [comment]
> Personally, I would rather have trees normalized in a way where you wouldn't have to rely on gtEffectiveVal as it's just another thing that we have to keep in our mind; paying some complexity cost up front so that later phases don't have to worry about peeking into commas.

I like the idea of removing commas, but to rely on this we would need stronger guarantees which seems like a difficult problem (this is essentially moving rationalization/LIR further back in the pipeline). It seemed kind of ad-hoc to move them one layer up; that just introduces commas under a different type of node, which transforms for that one then need to handle. By the way, we do so for `GT_IND` here: https://github.com/dotnet/runtime/blob/24651b88af9b074f3c3b9c23f37429e429fad8ee/src/coreclr/jit/assertionprop.cpp#L1339
which I think is why the previous change did not cause regressions.

**Comment by SingleAccretion** [comment]
I agree with Jakob; it does not seem fruitful to canonicalize `COMMA`s unless we know the "ultimate" canonical shape. I suspect different transforms/phases would have different definitions of "canonical".

For example, canonical shape for an `COMMA` + indirection differs today for structs (`OBJ(COMMA<addr>)`) and primitives (`COMMA(IND<addr>)`), reflecting what we want to CSE (only the address or the whole `IND`).

**Comment by TIHan** [comment]
The intent here isn't to remove commas, just to shape the tree in a way that can get more easily picked up by patterns before rationalization. I still have this issue: https://github.com/dotnet/runtime/pull/68885 with the mod morph - where the cse `comma(asg, var)` interferes with the pattern. I would also have to use `gtEffectiveVal` there as well and maybe some do other checks; I guess it's hard to know when it's safe to use.

Only way to really remove commas is by splitting the tree into statements when the commas are the root; I did an experiment with this and indeed it removed the commas, but there wasn't any benefit except for removing a comma in `GT_RETURN` showed some benefits. I expected there wouldn't be much difference as commas and statements are trying to do basically the same thing.

> (this is essentially moving rationalization/LIR further back in the pipeline)

I guess it's almost the same considering the commas are removed.  But, shaping the tree in this way, the commas are still part of tree but just further up; they are not hidden within the linear order(`gtNext`/`gtPrev`).

There are other places that tend to favor having the comma as the root, such as `importer.cpp`; I'm wondering if the motivations were similar in regard to picking up patterns later on.

> It seemed kind of ad-hoc to move them one layer up; that just introduces commas under a different type of node,

I didn't see it as ad-hoc to move it one layer up, but yes, moving the comma up can also affect other nodes.

This is effectively what our CSE is doing:
```fsharp
let test x =
    let y = (x * x) / 2 in
    let z = (x * x) / 5 in
    ...
```
with cse:
```fsharp
let test x =
    let y = (let cse0 = x * x in cse0) / 2 in // not as easy to match patterns unless gtEffectiveVal is used
    let z = cse0 / 5 in
    ...
```

All that I'm trying to do is turn it into this:
```fsharp
let test x =
    let cse0 = x * x in
    let y = cse0 / 2 in // easier to match patterns
    let z = cse0  / 5 in
    ...
```

> it does not seem fruitful to canonicalize COMMAs unless we know the "ultimate" canonical shape.

I do think it is beneficial, even incrementally; we just merged a change that roots the created commas for `SubMulDiv`: https://github.com/dotnet/runtime/pull/69770 - this gave benefits and made it easier to look for the `SubLshDiv` pattern in https://github.com/dotnet/runtime/pull/68885 - except for a few cases that had cses due to commas.

--

Anyway, I'm not disagreeing with using `gtEffectiveVal` or with the current shape of the trees - I'm just sharing my experience and opinion as I'm passionate about this.

For this PR and future, I'm totally fine using `gtEffectiveVal` as that is the way things are done.

**Review by jakobbotsch — APPROVED** [review]
LGTM. The test failure looks like #67870.

**Pull request merged**
