### PR TITLE
JIT: Allow hot/cold splitting between a `BBJ_COND` block and its false target

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Next step for #93020. When doing hot/cold splitting, if the first cold block succeeds a `BBJ_COND` block (meaning the false target is the first cold block), we previously needed to insert a `BBJ_ALWAYS` block at the end of the hot section to unconditionally jump to the cold section. Since we will need to conditionally generate a jump to the false target depending on its location once `bbFalseTarget` can diverge from `bbNext`, this seemed like a nice opportunity to add that logic in, and instead generate a jump to the cold section by checking if a jump is needed to the false target, rather than by appending a `BBJ_ALWAYS` block to the hot section.

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
cc @dotnet/jit-contrib. [No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=512937&view=ms.vss-build-web.run-extensions-tab), but a slight TP impact. `runtime-coreclr superpmi-diffs` failures don't seem to be related. Hot/Cold splitting tests passed in `runtime-coreclr crossgen2`.

**Review by BruceForstall — APPROVED** [review]
Regarding no diffs: I don't believe we have any hot/cold splitting in any of the SPMI collections. We probably should.

**Comment by amanasifkhalid** [comment]
> Regarding no diffs: I don't believe we have any hot/cold splitting in any of the SPMI collections. We probably should.

Would that just entail enabling "fake" hot/cold splitting (e.g. `DOTNET_JitFakeProcedureSplitting=1`) for some methods?

**Comment by BruceForstall** [comment]
> Would that just entail enabling "fake" hot/cold splitting (e.g. `DOTNET_JitFakeProcedureSplitting=1`) for some methods?

That might be sufficient. Or maybe some crossgen2 + real splitting for some assemblies?

**Comment by amanasifkhalid** [comment]
> Or maybe some crossgen2 + real splitting for some assemblies?

Ah, I just remembered that fake splitting also "fakes" the unwind info by treating the whole method as hot, so turning on real splitting for some crossgen'd assemblies might be more interesting/useful.

**Pull request merged**
