### PR TITLE
Obsolete mutable X509 certificate APIs

### PR DESCRIPTION
**Pull request by vcsjones**
Obsolete some X509Certificate APIs.

Contributes to #47977

### CODE REVIEW

**Comment by vcsjones** [comment]
@bartonjs I could use some input on how to proceed with the obsoletion here since it appears to have run in to a not-yet-seen thing before.

In this PR, the _ref_ project does not currently build. This is because we obsoleted `X509Certificate..ctor`. The constructors in the `ref` for `X509Certificate2` look like this, and they are not obsolete:

https://github.com/dotnet/runtime/blob/bdc5d79e9976aeeeabe2a6e38b1e80e33bd01506/src/libraries/System.Security.Cryptography.X509Certificates/ref/System.Security.Cryptography.X509Certificates.cs#L221

The constructors here don't chain to their base, so they are implicitly calling `X509Certificate..ctor` instead of their not-obsolete versions. So these constructor calls trigger SYSLIB0026.

> /workspaces/runtime/src/libraries/System.Security.Cryptography.X509Certificates/ref/System.Security.Cryptography.X509Certificates.cs(241,9): error SYSLIB0026: 'X509Certificate.X509Certificate()' is obsolete: 'X509Certificate and X509Certificate2 are immutable. Use the appropriate constructor to create a new certificate.' [/workspaces/runtime/src/libraries/System.Security.Cryptography.X509Certificates/ref/System.Security.Cryptography.X509Certificates.csproj]

Putting `#pragma warning disable SYSLIB0026` in the .cs ref file appears to work, but I'm not sure if this is "right".

Putting `<NoWarn>$(NoWarn),SYSLIB0026</NoWarn>` in the ref project file does not work, some autogenerated "notsupported" project does not include this `NoWarn`:

> /workspaces/runtime/artifacts/obj/System.Security.Cryptography.X509Certificates/net6.0-Debug/System.Security.Cryptography.X509Certificates.notsupported.cs(240,9): error SYSLIB0026: 'X509Certificate.X509Certificate()' is obsolete: 'X509Certificate and X509Certificate2 are immutable. Use the appropriate constructor to create a new certificate.' [/workspaces/runtime/src/libraries/System.Security.Cryptography.X509Certificates/src/System.Security.Cryptography.X509Certificates.csproj]

**Comment by bartonjs** [comment]
> Putting <NoWarn>$(NoWarn),SYSLIB0026</NoWarn> in the ref project file does not work, some autogenerated "notsupported" project does not include this NoWarn:

I think you just need to also use that NoWarn in the AnyOS block in https://github.com/dotnet/runtime/blob/54fdd2606170f0b0584eea78c93ae554deaacdf5/src/libraries/System.Security.Cryptography.X509Certificates/src/System.Security.Cryptography.X509Certificates.csproj#L8-L11, too.

**Comment by vcsjones** [comment]
`anotherThingThatWouldTakeMeAMillionYearsToFigureOut++`

**Comment by vcsjones** [comment]
For `needs-breaking-change-doc-created`, is there anything I could / should be doing here?

**Review by bartonjs — APPROVED** [review]

**Comment by bartonjs** [comment]
> For needs-breaking-change-doc-created, is there anything I could / should be doing here?

Best I can tell, for right now we just need to link it in to the master obsoletions doc issue.  So I did that.

**Pull request merged**
