### PR TITLE
Adjust the lpParent of "adopted" child loops

### LINKED ISSUE #74773: Assertion failed '(parentLoop.lpFlags & LPFLG_REMOVED) == 0' during 'Assertion prop'
```c#
// Found by Antigen

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
public class TestClass
{
    public struct S1
    {
        public struct S1_D1_F2
        {
            public decimal decimal_1;
        }
    }
    public struct S2
    {
    }
    static int s_int_12 = 5;
    static string s_string_16 = "Q57IY";
    static S1.S1_D1_F2 s_s1_s1_d1_f2_20 = new S1.S1_D1_F2();
    static S1 s_s1_21 = new S1();
    bool bool_23 = false;
    long long_30 = 5;
    string string_33 = "";
    S1.S1_D1_F2 s1_s1_d1_f2_37 = new S1.S1_D1_F2();
    S2 s2_39 = new S2();
    static int s_loopInvariant = 1;
    public string LeafMethod10()
    {
        unchecked
        {
            return s_string_16 = string_33;
        }
    }
    public decimal Method3(out decimal p_decimal_105, S1.S1_D1_F2 p_s1_s1_d1_f2_106, S1.S1_D1_F2 p_s1_s1_d1_f2_107, ref S2 p_s2_108, out S1 p_s1_109, S1 p_s1_110, ref S2 p_s2_111, long p_long_112, out S1 p_s1_113, out S1.S1_D1_F2 p_s1_s1_d1_f2_114, sbyte p_sbyte_115, ref S2 p_s2_116, S1.S1_D1_F2 p_s1_s1_d1_f2_117)
    {
        unchecked
        {
            p_decimal_105 = 15+4;
            p_s1_s1_d1_f2_114 = p_s1_s1_d1_f2_107;
            switch (long_30)
            {
                case -2:
                {
                    break;
                }
                case 1:
                {
                    break;
                }
                case 2:
                {
                    break;
                }
                default:
                {
                    int __loopvar3 = s_loopInvariant;
                    do
                    {
                        if (__loopvar3 > 15+4)
                            break;
                        ;
                    }
                    while (bool_23 && LeafMethod10() == string_33);
                    break;
                }
            }
            return s_int_12 %= 15|4;
        }
    }
    public void Method0()
    {
        unchecked
        {
            S1.S1_D1_F2 s1_s1_d1_f2_2641 = new S1.S1_D1_F2();
            S1 s1_2642 = new S1();
            S2 s2_2643 = new S2();
            s1_s1_d1_f2_37.decimal_1 = Method3(out s_s1_s1_d1_f2_20.decimal_1, s_s1_s1_d1_f2_20, s1_s1_d1_f2_2641, ref s2_2643, out s_s1_21, s_s1_21, ref s2_39, 15-4, out s1_2642, out s_s1_s1_d1_f2_20, 15^4, ref s2_39, s1_s1_d1_f2_37);
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
    }
}
/*
Environment:

set COMPlus_AltJitName=clrjit_win_x86_x64.dll
set COMPlus_AltJit=Method3

Assert failure(PID 50456 [0x0000c518], Thread: 66184 [0x10288]): Assertion failed '(parentLoop.lpFlags & LPFLG_REMOVED) == 0' in 'TestClass:Method3(byref,S1_D1_F2,S1_D1_F2,byref,byref,S1,byref,long,byref,byref,byte,byref,S1_D1_F2):System.Decimal:this' during 'Assertion prop' (IL size 125; hash 0x612adea7; FullOpts)
    File: D:\git\dotnet-runtime\src\coreclr\jit\fgdiagnostic.cpp Line: 3782
    Image: d:\git\dotnet-runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe
*/

```

### PR DESCRIPTION
**Pull request by kunalspathak**
When we remove a loop, we adjust the `lpParent` of the child loops and point them to the parent of the loop getting removed and thus they get "adopted" by the parent loop. However, we never update the `lpChild` or `lpSibling` of those parent loops which could be tricky. As a result, if a parent loop is also removed eventually, during the loop table check, we see that the "adopted" loop is not a top-level loop (because it is still pointing to some parent loop), but the parent loop has been removed and we assert.

In the method where we remove the loop, I am also iterating through the entire loop table and whichever loops has `lpParent` pointing to current loop getting removed, I update its `lpParent = NOT_IN_LOOP` to reflect the state accurately.

Alternatively, we can update the `lpSibling`/`lpChild` of parent loop to record the "adopted" loop in parent's records and that way, we will automatically reset the `lpParent` of such loops that we already do today. 

https://github.com/dotnet/runtime/blob/ebd80ad07516c7cbf126789c441700db94acbec8/src/coreclr/jit/optimizer.cpp#L10215-L10225

The question, is how to update these fields? Is it as simple as this?

```diff
@@ -10221,6 +10221,35 @@ void Compiler::optMarkLoopRemoved(unsigned loopNum)
             JITDUMP("Resetting parent of loop number " FMT_LP " from " FMT_LP " to " FMT_LP ".\n", l,
                     optLoopTable[l].lpParent, loop.lpParent);
             optLoopTable[l].lpParent = loop.lpParent;
+
+        }
+    }
+
+    if (loop.lpParent != BasicBlock::NOT_IN_LOOP)
+    {
+        LoopDsc& parentLoop = optLoopTable[loop.lpParent];
+        BasicBlock::loopNumber l = BasicBlock::NOT_IN_LOOP;
+
+        // Find the last child of the parent
+        for (l = parentLoop.lpChild; l != BasicBlock::NOT_IN_LOOP; l = optLoopTable[l].lpSibling)
+            ;
+
+        // If there is one, append all the children of current loop
+        if (l != BasicBlock::NOT_IN_LOOP)
+        {
+            LoopDsc& lastChildLoop = optLoopTable[l];
+
+            for (BasicBlock::loopNumber childl = loop.lpChild; //
+                 childl != BasicBlock::NOT_IN_LOOP;            //
+                 childl = optLoopTable[childl].lpSibling)
+            {
+                if ((optLoopTable[childl].lpFlags & LPFLG_REMOVED) == 0)
+                {
+                    lastChildLoop.lpSibling = childl;
+                    lastChildLoop           = optLoopTable[childl];
+                    // Tricky to get this right because what happens to the `optLoopTable[childl].lpSibling.
+
+                    JITDUMP("Adding " FMT_LP " as sibling of " FMT_LP " for parent loop " FMT_LP "\n.", childl, l, loop.lpParent);
+                }
+            }
```

Fixes: https://github.com/dotnet/runtime/issues/74773

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Note: this is a follow-up to https://github.com/dotnet/runtime/pull/68804/.

There is an important typo in that change, it has the comment:
```
// TODO: As `optAnyChildNotRemoved()` points out, child loops should
// be live ...
```
which should be:
```
// TODO: As `optAnyChildNotRemoved()` points out, child loops should NOT
// be live ...
```

**Comment by BruceForstall** [comment]
I think probably better to insert all the children of the loop-to-be-removed as children of their new parent loop, but not at the end of the list -- in the same place the current loop-to-be-removed exists in the list. Maybe:
```
    // Insert the children of the loop being removed, if any, as siblings, immediately after the loop being
    // removed, in the new parent.
    if (loop.lpParent != BasicBlock::NOT_IN_LOOP)
    {
        BasicBlock::loopNumber lLastChild = BasicBlock::NOT_IN_LOOP;
        for (BasicBlock::loopNumber l = loop.lpChild; //
             l != BasicBlock::NOT_IN_LOOP;            //
             lLastChild = l, l = optLoopTable[l].lpSibling)
        {
        }

        if (lLastChild != BasicBlock::NOT_IN_LOOP)
        {
            // There's at least one child of the loop being removed.

            // Save the removed loop's sibling (next pointer)
            BasicBlock::loopNumber lSuccessor = optLoopTable[loopNum].lpSibling;
            // Insert the removed loop's first child after the removed
            optLoopTable[loopNum].lpSibling = optLoopTable[loopNum].lpChild;
            // After the last child comes what previously followed the removed loop
            optLoopTable[lLastChild].lpSibling = lSuccessor;
            // The removed loop has no more children; they've been hoisted to the parent.
            optLoopTable[loopNum].lpChild = BasicBlock::NOT_IN_LOOP;

            JITDUMP("Inserting " FMT_LP " children in parent loop " FMT_LP " child list.\n", loopNum, loop.lpParent);
        }
    }
```

This leaves the removed list in the child list, but it should be ignored by being marked `LPFLG_REMOVED`.

It does make the `optAnyChildNotRemoved()` assert useless (so it can be removed).

**Comment by AndyAyersMS** [comment]
A goal to aspire to here is that the loop table be fully correct&mdash;unless somehow that's just not possible. Otherwise, we're just asking for trouble somewhere.

I like Bruce's suggestion.

**Comment by kunalspathak** [comment]
/benchmark runtime-win-x64 aspnet-citrine-win-ampere plaintext,json

**Comment by kunalspathak** [comment]
/benchmark runtime-win-arm64 aspnet-citrine-win-ampere plaintext

**Comment by kunalspathak** [comment]
> A goal to aspire to here is that the loop table be fully correct

Agree. I took some time to rewrite majority portion of `optMarkLoopRemoved()` to properly update the states of all the loops that gets affected when a particular loop `loopToRemove` is removed. I took Bruce's suggestion of inserting the children loops in-place where the `loopToRemove` was, but it is not straightforward.  I considered following cases to be handled.

1. If the `loopToRemove` has no children:
  a. If `loopToRemove` is the first child of its parent, then update the `lpChild` of parent to point to the next sibling of `loopToRemove`
  b. If `loopToRemove` is the non-first child, then update the `prevSibling`'s `'lpSibling` to point to the `nextSibling` that follows `loopToRemove`.
2. If the `loopToRemove` has children:
  a. If `loopToRemove` is the first child of its parent, then update the `lpChild` of parent to point to the `firstChild` of `loopToRemove`.
  b. If `loopToRemove` is the non-first child of its parent, then update the `lpSibling` to point to the `firstChild` of `loopToRemove`.
  c. Link `lastChild` of `loopToRemove` to point to the `nextSibling` of `loopToRemove`.

This cuts all the ties of others loops from `loopToRemove` and hence, we should never come across a loop via `lpParent`, `lpChild` or `lpSibling` which is marked as removed. Hence, I also converted the code `if (loopIsRemoved()) continue; ` to `assert(!loopisRemoved())` to make sure we never encounter a case where we reach a loop entry that was marked as removed.

**Comment by kunalspathak** [comment]
Few asmdiffs are coming because we are correctly tracking the `bbNaturalLoopNum` information where earlier we would have it point to the removed loop.

image

**Review by AndyAyersMS — APPROVED** [review]

**Pull request merged**
