### PR TITLE
Suppress warnings for taking address of TypedReference

### PR DESCRIPTION
**Pull request by jcouv**
Relates to compiler change: https://github.com/dotnet/roslyn/pull/66328
Tagging @AaronRobinsonMSFT to confirm those suppressions are okay.

### CODE REVIEW

**Review by stephentoub — COMMENTED** [review]
At some point soon we may want to just suppress 8500 for the whole repo, but for now doing it locally is good.

**Comment by AaronRobinsonMSFT** [comment]
> At some point soon we may want to just suppress 8500 for the whole repo, but for now doing it locally is good.

Agreed. Do we think this is one of those warnings we want to permit when performed in an `unsafe` context? I can't recall all those details but we were discussing the idea of if you are in an `unsafe` context Roslyn is more permissive? Or was that around converting an error to warning - I don't recall all the details.

**Comment by stephentoub** [comment]
>  Or was that around converting an error to warning

Right.  Previously this was an unsuppressable error.  Now in an unsafe context it becomes a suppressable warning CS8500.

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by danmoseley** [comment]
S.R.CS seems a resaonable label?

**Comment by jcouv** [comment]
@stephentoub My understanding is that this is generally unsafe, but there are a few situations where it is okay. When it comes to compiler warnings, this is one that is **stern** :-P
In that light, having a local suppression seems beneficial to call reviewers' attention to something subtle. So I'm not sure that a repo-wide suppression is a good idea.

**Comment by jcouv** [comment]
> how the problems this averts are significantly worse than many other things I can do with pointers in an unsafe context with zero warning

I see your point. This is not worse than other things you can do with pointers in unsafe context. A broader suppression would make sense.

**Pull request merged**
