### PR TITLE
Socket.Tests: remove TestSettings.UDPRedundancy 

### PR DESCRIPTION
**Pull request by antonfirsov**
dotnet/corefx#15697 changed this value to 1, and no-one touched it since then.

As the comment in that PR points out, the root cause of the UDP test failures wasn't packet loss, but IPv4 / IPv6 port collision on Unix in dual-mode cases.

The value and the for loops are complicating Socket test code unnecessarily, simplification seems reasonable.

/cc @geoffkizer @stephentoub

### CODE REVIEW

**Review by geoffkizer — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]
LGTM if @wfurt is happy with it (he's been looking a lot at test failures).

**Comment by wfurt** [comment]
I think this may be ok - I certainly like the simplification. We can watch the results and react if we see new failures.

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by antonfirsov** [comment]
The `System.Diagnostics.Tests` failures are unrelated.

The `Read_PartiallySatisfied_RemainderOfBufferUntouched` failure seems to be related to #44214.

**Comment by antonfirsov** [comment]
The outerloop test hang #44219 seems to be unrelated, since `NetworkStreamTest` is untouched by this PR.

**Pull request merged**
