### PR TITLE
Remove unsafe code from Boolean.TryFormat

### PR DESCRIPTION
**Pull request by xtqqczze**
`MemoryMarshal.AsBytes` would throw unnecessarily when `destination.Length` exceeds 0x3FFFFFFF.

### CODE REVIEW

**Comment by xtqqczze** [comment]
@MihuBot

**Comment by xtqqczze** [comment]
@MihuBot

**Comment by huoyaoyuan** [comment]
This may get superseded by #108575

**Comment by EgorBo** [comment]
> This may get superseded by #108575

I was just wondering about perf overhead from a more idiomatic code (since we already do the same for UTF8 formatter for bools, see [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Buffers/Text/Utf8Formatter/Utf8Formatter.Boolean.cs#L35-L42))

Surprisingly, the idiomatic way seems to be cheaper? 😐

**Comment by xtqqczze** [comment]
@EgorBot -intel -arm64 -profiler
```cs
using System.Runtime.CompilerServices;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);

public class Benchmarks
{
    static bool[] _values = Enumerable.Range(0, 256).Select(i => i % 2 == 0).ToArray();
    static char[] _output = new char[4096];

    [Benchmark]
    public void WriteBools()
    {
        Span<char> output = _output;
        foreach (var value in _values)
        {
            if (value.TryFormat(output, out int written))
                output = output.Slice(written);
            else
                throw new InvalidOperationException();
        }

        Consume(output);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    void Consume(Span<char> _){}
}
```

**Comment by EgorBo** [comment]
@xtqqczze feel free to just incorporate my change in your PR, but we may need to keep your version for Mono

**Comment by jkotas** [comment]
> just incorporate https://github.com/dotnet/runtime/pull/108575 in your PR, but we may need to keep your version for Mono since it can't unroll Memmove.

bool formatting is very unlikely to be on a hot path in scenarios targeted by Mono. I think it would be acceptable to take regression for Mono to keep the code simple and safe.

**Comment by xtqqczze** [comment]
Related: https://github.com/dotnet/runtime/pull/77398

**Comment by xtqqczze** [comment]
@EgorBot -mono -intel -arm64
```cs
using System.Runtime.CompilerServices;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);

public class Benchmarks
{
    static bool[] _values = Enumerable.Range(0, 256).Select(i => i % 2 == 0).ToArray();
    static char[] _output = new char[4096];

    [Benchmark]
    public void WriteBools()
    {
        Span<char> output = _output;
        foreach (var value in _values)
        {
            if (value.TryFormat(output, out int written))
                output = output.Slice(written);
            else
                throw new InvalidOperationException();
        }

        Consume(output);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    void Consume(Span<char> _){}
}
```

**Comment by EgorBo** [comment]
> bool formatting is very unlikely to be on a hot path in scenarios targeted by Mono. I think it would be acceptable to take regression for Mono to keep the code simple and safe.

Agree. In fact it improves [Mono-jit (mini)](https://github.com/EgorBot/runtime-utils/issues/111), but slightly regresses [Interpreter](https://github.com/EgorBot/runtime-utils/issues/112).

**Comment by xtqqczze** [comment]
@EgorBot -mono -intel -arm64 --envvars MONO_ENV_OPTIONS:--interpreter
```cs
using System.Runtime.CompilerServices;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);

public class Benchmarks
{
    static bool[] _values = Enumerable.Range(0, 256).Select(i => i % 2 == 0).ToArray();
    static char[] _output = new char[4096];

    [Benchmark]
    public void WriteBools()
    {
        Span<char> output = _output;
        foreach (var value in _values)
        {
            if (value.TryFormat(output, out int written))
                output = output.Slice(written);
            else
                throw new InvalidOperationException();
        }

        Consume(output);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    void Consume(Span<char> _){}
}
```

**Comment by xtqqczze** [comment]
> bool formatting is very unlikely to be on a hot path in scenarios targeted by Mono. I think it would be acceptable to take regression for Mono to keep the code simple and safe.

@jkotas For monointerpreter, the ratio between https://github.com/dotnet/runtime/pull/108572 and https://github.com/dotnet/runtime/pull/108575 ratio is 0.60.

## Benchmark results on `AzureAmpere`

```
BenchmarkDotNet v0.14.0, Ubuntu 22.04.5 LTS (Jammy Jellyfish)
AzureAmpere
  Job-QUXZYN : .NET 10.0.0 (42.42.42.42424) using MonoVM, Arm64 AOT
  Job-CRJMBB : .NET 10.0.0 (42.42.42.42424) using MonoVM, Arm64 AOT
EnvironmentVariables=MONO_ENV_OPTIONS=--interpreter
```

| Method     | Toolchain               | Mean     | Error    | Ratio |
|----------- |------------------------ |---------:|---------:|------:|
| WriteBools | Main | 22.75 μs | 0.266 μs |  1.00 |
| WriteBools | https://github.com/dotnet/runtime/pull/108572 | 16.58 μs | 0.329 μs |  0.73 |
| WriteBools | Main | 22.00 μs | 0.440 μs | 1.00 |
| WriteBools | https://github.com/dotnet/runtime/pull/108575 | 26.90 μs | 0.529 μs | 1.22 |

**Comment by EgorBo** [comment]
>For monointerpreter, the ratio between https://github.com/dotnet/runtime/pull/108572 and https://github.com/dotnet/runtime/pull/108575 ratio is 0.60.

I think 20% regression is fine here, even the best case is still a lot slower than the JIT, so it always can be handled via an intrinsic in the interpreter if it really becomes a bottle-neck. A safer/easier-to-read code worth it.

**Comment by xtqqczze** [comment]
@EgorBo Do you expect to merge https://github.com/dotnet/runtime/pull/108576 soon?

**Comment by EgorBo** [comment]
> @EgorBo Do you expect to merge #108576 soon?

You don't have to wait for it, it improves a tiny bit

**Comment by xtqqczze** [comment]
@EgorBot -intel -arm64 -profiler
```cs
using System.Runtime.CompilerServices;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);

public class Benchmarks
{
    static bool[] _values = Enumerable.Range(0, 256).Select(i => i % 2 == 0).ToArray();
    static char[] _output = new char[4096];

    [Benchmark]
    public void WriteBools()
    {
        Span<char> output = _output;
        foreach (var value in _values)
        {
            if (value.TryFormat(output, out int written))
                output = output.Slice(written);
            else
                throw new InvalidOperationException();
        }

        Consume(output);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    void Consume(Span<char> _){}
}
```

**Review by EgorBo — APPROVED** [review]
LGTM, I think it's fine to leave constants instead of .Length to avoid making mono even more slower, but I don't have a strong opinion. I think it should be a good idea to fold `ldstr+length` in Mono too (I once tried to do so in Mono via https://github.com/mono/mono/pull/16898 but didn't finish)

**Comment by xtqqczze** [comment]
> LGTM, I think it's fine to leave constants instead of .Length to avoid making mono even more slower, but I don't have a strong opinion. I think it should be a good idea to fold `ldstr+length` in Mono too (I once tried to do so in Mono via [mono/mono#16898](https://github.com/mono/mono/pull/16898) but didn't finish)

Issue opened: https://github.com/dotnet/runtime/issues/108857

**Review by jkotas — APPROVED** [review]
LGTM

**Pull request merged**
