### PR TITLE
Add ArraySegmentPool

### PR DESCRIPTION
**Pull request by wizardars**
I made a pull request because I was afraid to be late for .Net 5. https://github.com/wizardars/test

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=41237) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=41237) before we can accept your contribution.<br/><br/>:x: wizardars [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=41237)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=41237) it.</sub>

**Comment by jkotas** [comment]
All new public .NET APIs have to go through API review process: https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md . We do not accept PRs for unapproved APIs. Could you please start with API proposal issue instead?

Thank you for trying to contribute to .NET Runtime!

**Comment by wizikus** [comment]
ok

**Comment by wizardars** [comment]
ok

**Comment by GrabYourPitchforks** [comment]
@wizardars In addition to what Jan said, .NET 5 is essentially closed for new feature requests. If you open an API proposal it'll be considered for .NET 6. Just wanted to give you a heads up!

**Comment by wizardars** [comment]
@GrabYourPitchforks Yes, I saw in the broadcast that you send everyone to .Net 6. Therefore, I made a pull request for luck, but it didn't work)

**Pull request closed without merging**
