### PR TITLE
Fix help formatting in cg2/ilc

### LINKED ISSUE #76770: crossgen/llc --help is malformed
`crossgen2.exe --help` prints an exception:
```
armel: Unhandled exception. System.CommandLine.CommandLineException: Target architecture 'armel' is not supported
   at System.CommandLine.Helpers.GetTargetArchitecture(String token) in C:\prj\runtime-main\src\coreclr\tools\Common\CommandLineHelpers.cs:line 109
   at ILCompiler.Crossgen2RootCommand.<>c.<GetExtendedHelp>b__182_0(HelpContext _) in C:\prj\runtime-main\src\coreclr\tools\aot\crossgen2\Crossgen2RootCommand.cs:line 337
   at System.CommandLine.Help.HelpBuilder.Write(HelpContext context)
   at System.CommandLine.Help.HelpResult.Apply(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.GetExitCode(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<Invoke>g__FullInvocationChain|3_0(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole console)
   at System.CommandLine.Parsing.ParseResultExtensions.Invoke(ParseResult parseResult, IConsole console)
   at System.CommandLine.Parsing.ParserExtensions.Invoke(Parser parser, String[] args, IConsole console)
   at ILCompiler.Program.Main(String[] args) in C:\prj\runtime-main\src\coreclr\tools\aot\crossgen2\Program.cs:line 874
```

`llc.exe --help` produces a long malformed list of ISAs, I think it should be either removed or hidden under `--instruction-set help`
```
The allowable values for the --instruction-set option are described in the table below. Each architecture has a different set of valid instruction sets, and multiple instruction sets may be specified by separating the instructions sets by a ','. For example 'avx2,bmi,lzcnt'
arm: arm64: base
, neon
, aes
, crc
, dotprod
, rdma
, sha1
, sha2
, lse



, rcpc
x86: base
, sse
, sse2
, sse3
, ssse3
, sse4.1
, sse4.2
, avx
, avx2
, aes
, bmi
, bmi2
, fma
, lzcnt
, pclmul
, popcnt


, avxvnni
, movbe
, serialize
, avx512f
, avx512f_vl
, avx512bw
, avx512bw_vl
, avx512cd
, avx512cd_vl
, avx512dq
, avx512dq_vl
x64: base
, sse
, sse2
, sse3
, ssse3
, sse4.1
, sse4.2
, avx
, avx2
, aes
, bmi
, bmi2
, fma
, lzcnt
, pclmul
, popcnt


, avxvnni
, movbe
, serialize
, avx512f
, avx512f_vl
, avx512bw
, avx512bw_vl
, avx512cd
, avx512cd_vl
, avx512dq
, avx512dq_vl
```

### PR DESCRIPTION
**Pull request by am11**
Fixes #76770.

### CODE REVIEW

**Comment by EgorBo** [comment]
That was quick! Do you think it still makes sense to occupy 70 lines of help listing all possible ISAs?
can we just suggest user to use `--instruction-set help` to list them there?

**Comment by am11** [comment]
> There is also an inconsistency here with crossgen that doesn't do it.

I don't see the inconsistency; both `ilc` and `crossgen2` with `--instruction-set --help` have same behavior (i.e. it is currently not supported).

**Comment by am11** [comment]
> can we just suggest user to use `--instruction-set` help to list them there?

Yup, make sense. It should be easy to support `--instruction-set --help`. Let me take a look.

(CI seems to be broken due to infrastructure outage)

**Comment by jkotas** [comment]
> Do you think it still makes sense to occupy 70 lines of help listing all possible ISAs?

In the .NET 7 ilc, the isa listings took 4 lines (one line for each arm, arm64, x86, x64). Where is the 70 lines coming from?

**Comment by am11** [comment]
Console.WriteLine was misplaced in ilc, which I've fixed. So it's back to four lines as before.

**Comment by EgorBo** [comment]
> Console.WriteLine was misplaced in ilc, which I've fixed. So it's back to four lines as before.

Ah, so it was `WriteLine`'s fault? I though it was intentional to list them each at a new line, that's why I proposed to hide them under "help" 🙂 if it's back to 4 lines then great!

**Review by EgorBo — APPROVED** [review]

**Comment by am11** [comment]
Yup.

ILC:

image

Crossgen2 (which has `armel` in addition to ILC's output):
image


I have the other change ready for `--instruction-set --help` as well (but couldn't test it yet due to an ongoing incidence: https://status.dev.azure.com/).

**Pull request merged**
