### PR TITLE
[release/8.0-preview5] Use fully qualified type names for parameters and don't copy parameter attributes

### PR DESCRIPTION
**Pull request by jtschuster**
Fixes https://github.com/dotnet/source-build/issues/3483 by not copying the attributes for the parameters on generated base implementation methods since they're not strictly necessary.

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]
Can we add a test to make sure we've fixed the issue?

**Review by mthalman — APPROVED** [review]

**Comment by carlossanlop** [comment]
@jtschuster @jkoritzinsky @mthalman I see the test was added. There were test failures. Let me know if they are not related and if this is ready to merge.

**Comment by jtschuster** [comment]
The failures look like unrelated internet issues. I'll let @jkoritzinsky confirm, but it should be ready to merge.

**Review by lewing — APPROVED** [review]

**Comment by carlossanlop** [comment]
The CI got reset with the merge. But since the CI passed before, I'll merge.

**Pull request merged**
