### PR TITLE
Ad-Hoc codesign on macOS-arm64 for crossgen2 binaries

### PR DESCRIPTION
**Pull request by EgorBo**
This fixes super annoying issue https://github.com/dotnet/runtime/issues/65228 on macOS M1 where we randomly hit
image
when we rebuild Clr (I know @AndyAyersMS hit it too recently)

I am not sure I don't brake official package signing with this PR so it needs some review
Don't know who to ping, so pinging those who touched other codesign related files @agocke @janvorli @am11

### CODE REVIEW

**Comment by am11** [comment]
@EgorBo, I tried to repro it on M1 MBP when you posted issue the other day, but it was working fine on my machine ™️. If there is a deterministic way to repro it, I can try.

The fix I had in mind was to change: https://github.com/dotnet/runtime/blob/957575e886d0cda9659a6380690291e09c5514c1/eng/native/functions.cmake#L394 to:
` if (LOWERCASE_CMAKE_BUILD_TYPE MATCHES "^(release|checked)$")`
since your screenshot suggests it is happening with checked builds? 💭

**Comment by EgorBo** [comment]
> @EgorBo, I tried to repro it on M1 MBP when you posted issue the other day, but it was working fine on my machine 

I think this should repro:
```
./build.sh Clr -c Checked
# modify some lower.cpp
./build.sh Clr -c Checked
# if doesn't repro - edit lower.cpp again 
```

**Comment by am11** [comment]
Thanks. Yes I am able to reprodce it with `-c checked`, but not `-c release`. If you can also not repro it with `-c release`, then I think the safe condition would be:

```diff
-    <Exec Condition="$([MSBuild]::IsOSPlatform('OSX')) and '$(_hostArch)' == 'arm64'"
+    <Exec Condition="'$(Configuration)' == 'Checked' and $([MSBuild]::IsOSPlatform('OSX')) and '$(_hostArch)' == 'arm64'"
```

**Comment by EgorBo** [comment]
> Thanks. Yes I am able to reprodce it wit

Does the fix you suggested earlier help?

**Comment by am11** [comment]
Upstream issue: https://gitlab.kitware.com/cmake/cmake/-/issues/22372.

**Comment by AndyAyersMS** [comment]
@EgorBo this affects more than just crossgen2 -- if I change the jit or runtime and rebuild the test layout then `corerun` will fail too.

**Comment by am11** [comment]
Deleting `artifacts/bin` only (as a workaround) still performs the incremental build and passes the CG2 step without error, but it later fails on dotnet-pgo step like this:

```sh
% rm -rf artifacts/bin
% ./build.sh clr -c checked
__DistroRid: osx-arm64
  Determining projects to restore...
### snip
  Microsoft.NETCore.ILAsm -> /Users/am11/projects/runtime/artifacts/packages/Checked/Shipping/Microsoft.NETCore.ILAsm.7.0.0-dev.nupkg
  dotnet-pgo -> /Users/am11/projects/runtime/artifacts/bin/coreclr/OSX.arm64.Checked/dotnet-pgo/dotnet-pgo.dll
/Users/am11/projects/runtime/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(248,5): error MSB3030: Could not copy the file "/Users/am11/projects/runtime/artifacts/bin/coreclr/OSX.arm64.Checked//dotnet-pgo/shims/net6.0/win-x64/dotnet-pgo.exe" because it was not found. [/Users/am11/projects/runtime/src/coreclr/tools/dotnet-pgo/dotnet-pgo.csproj]
/Users/am11/projects/runtime/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(248,5): error MSB3030: Could not copy the file "/Users/am11/projects/runtime/artifacts/bin/coreclr/OSX.arm64.Checked//dotnet-pgo/shims/net6.0/osx-x64/dotnet-pgo" because it was not found. [/Users/am11/projects/runtime/src/coreclr/tools/dotnet-pgo/dotnet-pgo.csproj]
/Users/am11/projects/runtime/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(248,5): error MSB3030: Could not copy the file "/Users/am11/projects/runtime/artifacts/bin/coreclr/OSX.arm64.Checked//dotnet-pgo/shims/net6.0/win-arm/dotnet-pgo.exe" because it was not found. [/Users/am11/projects/runtime/src/coreclr/tools/dotnet-pgo/dotnet-pgo.csproj]
/Users/am11/projects/runtime/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(248,5): error MSB3030: Could not copy the file "/Users/am11/projects/runtime/artifacts/bin/coreclr/OSX.arm64.Checked//dotnet-pgo/shims/net6.0/win-x86/dotnet-pgo.exe" because it was not found. [/Users/am11/projects/runtime/src/coreclr/tools/dotnet-pgo/dotnet-pgo.csproj]
```
So as it stands, deleting the whole `artifacts` directory and build clr subset again is the way.

**Comment by am11** [comment]
The "shims" error comes from from PackAsTool target when it sees `PackAsToolShimRuntimeIdentifiers` property (used in `dotnet-pgo.csproj`). That target comes from SDK and creates a sentinel file in obj directory and skips copying shims if it was present: https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.PackTool.targets#L110. Apparently, there is no simple `AlwaysRegenerateShim` sort of  property for consumer that is conveyed to `GenerateShims` task.

The complete workaround for incremental build (modulo incremental build of dotnet-pgo, which builds instantly) is:

```sh
% ./build.sh clr -c checked
# modifying lower.cpp (e.g. dup `childNode->SetContained()` line)

# Workaround:
# delete bin directory to workaround inode issue and
# dotnet-pgo to workaround shims/sentinel file issue.
% rm -rf artifacts/bin artifacts/obj/coreclr/dotnet-pgo

% ./build.sh clr -c checked
__DistroRid: osx-arm64
  Determining projects to restore...
### snip
  Microsoft.NETCore.ILDAsm -> /Users/am11/projects/runtime/artifacts/packages/Checked/Shipping/Microsoft.NETCore.ILDAsm.7.0.0-dev.nupkg
  Microsoft.NETCore.ILAsm -> /Users/am11/projects/runtime/artifacts/packages/Checked/Shipping/Microsoft.NETCore.ILAsm.7.0.0-dev.nupkg
  dotnet-pgo -> /Users/am11/projects/runtime/artifacts/bin/coreclr/OSX.arm64.Checked/dotnet-pgo/dotnet-pgo.dll
  Successfully created package '/Users/am11/projects/runtime/artifacts/packages/Checked/NonShipping/dotnet-pgo.7.0.0-dev.nupkg'.
  Successfully created package '/Users/am11/projects/runtime/artifacts/packages/Checked/NonShipping/dotnet-pgo.7.0.0-dev.symbols.nupkg'.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:39.86
```

All signed binary files under `artifacts/bin` get the new inode number, and work on macOS hardened runtime. :)

**Pull request closed without merging**
