### PR TITLE
Remove libunwind disabled warnings.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Contributes to https://github.com/dotnet/runtime/issues/66154

/cc @GrabYourPitchforks @jkotas @am11

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
if it compiles..

**Review by stephentoub — APPROVED** [review]

**Comment by am11** [comment]
@AaronRobinsonMSFT, sorry I have just noticed this 🤦:
We should not revert this file as it is not the one we are using for compilation anymore.

The idea is, `src/native/external/{dependency-name}/` directory will be untouched third-party tree. "Our" config files (cmake etc.) will live outside of vendor's directory. Any patch that we apply in vendors tree will have some note in `src/native/external/{dependency-name}-version.txt` file.

In this case, we are now using `src/native/external/libunwind.cmake` and `src/native/external/libunwind_extras/CMakeLists.txt`.

**Comment by AaronRobinsonMSFT** [comment]
@am11 Are you saying this is the official libunwind version?

**Comment by am11** [comment]
Yup `src/native/external/libunwind/CMakeLists.txt` is the copy of upstream: https://github.com/libunwind/libunwind/blob/v1.6-stable/CMakeLists.txt which we do not use anymore (since https://github.com/dotnet/runtime/pull/64043).

**Comment by AaronRobinsonMSFT** [comment]
Okay. I've been updating this in the official libunwind repo too - see https://github.com/libunwind/libunwind/pull/333. I assume this means they will be back in sync?

**Comment by am11** [comment]
Ah great, libunwind-version.txt has https://github.com/libunwind/libunwind/pull/333 already listed. All good. 👍

**Pull request merged**
