### PR TITLE
JIT: refactor fields of GenTreeCall

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Move `gtStubCallStubAddr` out of the union it shares with class probe,
inline, and guarded devirt information, so that we no longer need to
save and restore the stub address when we want to probe, guardedly
devirtualize, or inline calls.

Delete all the code that did saving and restoring, and the field in the
inline info struct that held the saved copy.

Reorder the fields of the call node so that a bit we're less likely to
have internal padding.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

This is in anticipation of adding yet another kind of info to the mix....

No spmi diffs seen locally.

**Review by EgorBo — APPROVED** [review]
LGTM, `SuppressProbesFunctor` really felt a bit weird 🙂

**Comment by SingleAccretion** [comment]
This adds 16 more bytes to `GenTreeCall` on Windows 64 bit: https://www.diffchecker.com/GN2WH582.

Notably it will have to add at least 8 bytes on 64 bit in any case (on 32 bit there's padding we can steal some space from and indeed, this change does not affect the node's size on x86), I am assuming we're willing to give those 8 bytes up.

**Comment by AndyAyersMS** [comment]
> This adds 16 more bytes to `GenTreeCall`

Thanks. Reverted that bit.

**Pull request merged**
