### PR TITLE
[HTTP/3] Stress fixed docker

### LINKED ISSUE #64902: HttpStress fails to build on Linux, msquic package seems to be outdated
This line seems to fail now:
https://github.com/dotnet/runtime/blob/179ffff7967f3136d8f8d0d17510a5460dd01adb/src/libraries/System.Net.Http/tests/StressTests/HttpStress/Dockerfile#L12

Maybe we shall consider to move the package download logic to a separate `.sh` that only fails for HTTP 3.0 runs?

### PR DESCRIPTION
**Pull request by ManickaP**
Fixes #64902

### CODE REVIEW

**Review by CarnaViire — APPROVED** [review]
LGTM, thanks!

**Review by antonfirsov — APPROVED** [review]
Thanks!

**Pull request merged**
