### PR TITLE
Resolve warnings for assignment or explicit cast of possibly null type parameter value

### PR DESCRIPTION
**Pull request by cston**
Resolve warnings for assignment or explicit cast of possibly null type parameter value.

```C#
T t = default; // warning: may be null

object? o = ...;
t = (T)o; // warning: may be null
```

See https://github.com/dotnet/roslyn/pull/48803.

### CODE REVIEW

**Comment by cston** [comment]
cc @jaredpar, @RikkiGibson

**Review by stephentoub — APPROVED** [review]
I was concerned when I saw the number of files being edited,  but this looks quite reasonable.

**Comment by cston** [comment]
@stephentoub, please note the signatures of `AtomicComposition.TryGetValue<T>()` were updated to `[NotNullWhen(true)] out T? value` rather than `[MaybeNullWhen(false)] out T value`, so that callers can use `composition.TryGetValue(key, out T? value)` without explicit type arguments.

If the signature uses `[MaybeNullWhen(false)] out T value`, then `composition.TryGetValue(key, out T? value)` will be treated as `composition.TryGetValue<T?>(key, out T? value)`.

**Comment by stephentoub** [comment]
> please note the signatures of AtomicComposition.TryGetValue<T>() were updated to [NotNullWhen(true)] out T? value rather than [MaybeNullWhen(false)] out T value

But that's not a valid change, is it?  null values are valid, and the caller could specify a nullable T, in which case the annotation is wrong: TryGetValue could successfully return true and give back value == null.  In general that's why we use `[MaybeNullWhen(false)]` on generic outs from TryGetValue.  What makes this one special?

**Comment by cston** [comment]
Thanks @stephentoub. I agree, `[NotNullWhen(true)] out T?` is not the correct annotation.

It looks the issue that the compiler reports warnings when calling `TryGetValue()` without explicit type arguments is a variant of https://github.com/dotnet/roslyn/issues/48992.

**Pull request merged**
