### PR TITLE
Revert "[release/8.0] Downgrade 6 & 7 per tactics"

### PR DESCRIPTION
**Pull request by mmitche**
Reverts dotnet/runtime#94863

### CODE REVIEW

**Review by carlossanlop — APPROVED** [review]
LGTM

cc @lewing @steveisok

**Comment by carlossanlop** [comment]
Please wait for @lewing to confirm this is all we need.

**Review by steveisok — APPROVED** [review]

**Comment by steveisok** [comment]
EMSDK needs the same kind of change.

**Comment by carlossanlop** [comment]
> EMSDK needs the same kind of change.

@steveisok I assume you mean a change in the dotnet/emsdk repo, as opposed to an additional change here in runtime that affects emsdk?

**Comment by carlossanlop** [comment]
Whatever the case, I'll merge this and anything extra can be addressed in a separate PR, since the CI here is about to finish.

**Pull request merged**
