### PR TITLE
Update docs.microsoft.com usages to learn.microsoft.com

### PR DESCRIPTION
**Pull request by kendaleiv**

### CODE REVIEW

**Review by ilonatommy — APPROVED** [review]

**Comment by jkotas** [comment]
Could you please delete `en-us` from all links that you are touching while you are on it?

We prefer to omit `en-us` from the link to show localized content where possible.

**Comment by kendaleiv** [comment]
@jkotas Good idea! Updated.

**Comment by amcasey** [comment]
> Could you please delete `en-us` from all links that you are touching while you are on it?
> 
> We prefer to omit `en-us` from the link to show localized content where possible.

Can you elaborate a bit?  I do my best not to post localized links on GH, etc, but I would have thought that someone reading en-us docs would want links to go to other en-us docs, even if that's not their default locale.

**Comment by jkotas** [comment]
> Can you elaborate a bit? I do my best not to post localized links on GH, etc, but I would have thought that someone reading en-us docs would want links to go to other en-us docs, even if that's not their default locale. 

I do not think there is obvious right answer. You can make an argument either way. The preference for omitting en-us in the links is not new (e.g. see https://github.com/dotnet/runtime/pull/32273#discussion_r379266666). There are 718 `microsoft.com/dotnet` links and 207 `microsoft.com/en-us/dotnet` links in this repo at the moment.

**Review by akoeplinger — APPROVED** [review]

**Comment by amcasey** [comment]
> > Can you elaborate a bit? I do my best not to post localized links on GH, etc, but I would have thought that someone reading en-us docs would want links to go to other en-us docs, even if that's not their default locale.
> 
> I do not think there is an obvious right answer. You can make an argument either way. The preference for omitting en-us in the links is not new (e.g. see [#32273 (comment)](https://github.com/dotnet/runtime/pull/32273#discussion_r379266666)). There are 718 `microsoft.com/dotnet` links and 207 `microsoft.com/en-us/dotnet` links in this repo at the moment.

The precedent I had in mind was something like Wikipedia.  Links stay within a language, even if there's a corresponding entry in your preferred language.

**Comment by jkotas** [comment]
> The precedent I had in mind was something like Wikipedia. Links stay within a language, even if there's a corresponding entry in your preferred language.

That's true for Wikipedia->Wikipedia links. I do not think it is the rule for links going from Wikipedia to external websites.

For example, the link to learn.microsoft.com from https://en.wikipedia.org/wiki/Microsoft_Learn is language-neutral https://learn.microsoft.com. It is not language specific https://learn.microsoft.com/en-us.

**Pull request merged**
