### PR TITLE
Fix build break in System.Net.Sockets

### PR DESCRIPTION
**Pull request by stephentoub**
Two PRs crossed in CI.
cc: @sbomer, @tmds

### CODE REVIEW

**Comment by benaadams** [comment]
dotnet-linker-tests (Build OSX x64 release Runtime_Release)

```
Users/runner/runners/2.170.1/work/1/s/
src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj :
 error MSB4057: The target "PublishTrimmed" does not exist in the project.

##[error]src/libraries/System.Runtime/tests/TrimmingTests/
System.Runtime.TrimmingTests.proj(0,0): 
error MSB4057: (NETCORE_ENGINEERING_TELEMETRY=Build) The target "PublishTrimmed" does not exist in the project.
/Users/runner/runners/2.170.1/work/1/s/eng/testing/linker/trimmingTests.targets(75,5):
 error MSB3073: The command ""/Users/runner/runners/2.170.1/work/1/s/.dotnet/dotnet" msbuild /t:PublishTrimmed /nr:false /warnaserror -p:configuration=Release" exited with code 1. [/Users/runner/runners/2.170.1/work/1/s/src/libraries/System.Runtime/tests/TrimmingTests/System.Runtime.TrimmingTests.proj]
##[error]eng/testing/linker/trimmingTests.targets(75,5): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Build) The command ""/Users/runner/runners/2.170.1/work/1/s/.dotnet/dotnet" msbuild /t:PublishTrimmed /nr:false /warnaserror -p:configuration=Release" exited with code 1.

```

**Comment by stephentoub** [comment]
Thanks, Ben. @joperezr, presumably these build failures in linker tests are known? Is your pending PR fixing this? Thanks.

**Comment by joperezr** [comment]
Yup sorry guys this was my bad, I literally merged a PR this fix like 30 seconds ago so you can restart that pipeline and it should pass now

**Comment by stephentoub** [comment]
Thanks

**Comment by safern** [comment]
Thanks @stephentoub for fixing 😄

**Pull request merged**
