### PR TITLE
runtime-wasm-perf: add triggers for PRs

### PR DESCRIPTION
**Pull request by radical**
This is useful to prevent perf pipeline from breaking when changes are
made in `dotnet/runtime`.

### CODE REVIEW

**Comment by radical** [comment]
@dougbu I want to have the `runtime-wasm-perf` pipeline run by default for PRs, such that it is triggered based on the `triggers:` section of the `yml`. I have made some changes here but those don't seem to be enough. What am I missing?

**Comment by dougbu** [comment]
> @dougbu I want to have the `runtime-wasm-perf` pipeline run by default for PRs, such that it is triggered based on the `triggers:` section of the `yml`. I have made some changes here but those don't seem to be enough. What am I missing?

1. I suspect you need to add an `include:` path to match e.g., eng/pipelines/runtime-wasm-perf.yml
2. you likely also want to include 'main' in the branches that should trigger runs

**Comment by dougbu** [comment]
Also &hellip;

3. the AzDO UI _does_ override triggers here, turning of CI runs and changing when PR validations run. this would restore YAML control of when the pipeline runs.
  
image
I could untick the top-level "override" checkboxes or change the branches to check here

or, I could get rid of the lower-level tick shown below
image

**Comment by radical** [comment]
> Also …
> 
> 3. the AzDO UI _does_ override triggers here, turning of CI runs and changing when PR validations run. this would restore YAML control of when the pipeline runs.
> I could untick the top-level "override" checkboxes or change the branches to check here

Yes, having the triggers control in the yml would be preferable.

> 
> or, I could get rid of the lower-level tick shown below image

Yes, please. We want this pipeline to run by default and only be controlled by the triggers in yml.
I'm guessing that this won't affect running the pipeline manually on a pr with `/azp run runtime-wasm-perf`.

Thank you!

**Comment by dougbu** [comment]
> I'm guessing that this won't affect running the pipeline manually on a pr with /azp run runtime-wasm-perf.

That'll still work for re-running the pipeline _except_ the `include` items will be honoured, meaning nobody will be able to run  or rerun the pipeline for PRs unless the PR updates a matched file.

**Comment by dougbu** [comment]
done

note: I turned off **both** the CI (`trigger:`) and PR (`pr:`) overrides. this helped me realize the YAML you're changing doesn't have a `pr:` entry; you'll need one to get this working. see https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pr?view=azure-pipelines and https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/trigger?view=azure-pipelines

**Comment by radical** [comment]
> done

Thank you!


> note: I turned off **both** the CI (`trigger:`) and PR (`pr:`) overrides. this helped me realize the YAML you're changing doesn't have a `pr:` entry; you'll need one to get this working. see [learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pr?view=azure-pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pr?view=azure-pipelines) and [learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/trigger?view=azure-pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/trigger?view=azure-pipelines)

Ah, and the `trigger:` is for triggering the pipeline on non-pr builds. I changed it to `pr:` now.

**Comment by radical** [comment]
The pipeline is running for everyone now, so this should get merged soon.

**Comment by radical** [comment]
Ready for review.

**Review by steveisok — APPROVED** [review]

**Review by thaystg — APPROVED** [review]

**Comment by radical** [comment]
Failure is a helix issue. Merging this now to stop running `runtime-wasm-perf` for unrelated PRs!

**Pull request merged**
