### PR TITLE
Call simpler overloads of Substring and Slice

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
Minor code simplification which looks for places where we have code utilizing one of the following patterns:

```cs
someString.Substring(newOffset, someString.Length - newOffset);
someSpan.Slice(newOffset, someSpan.Length - newOffset);
```

And calls the single-parameter overload instead:

```cs
someString.Substring(newOffset);
someSpan.Slice(newOffset);
```

In particular, I _did not_ try to improve the perf of the call sites, such as changing from an allocating call to an allocation-free call, etc. This is just a code simplification and doesn't try to change any of the logic.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
Looks like fodder for another analyzer.

**Comment by GrabYourPitchforks** [comment]
> Looks like fodder for another analyzer.

Pondered that while doing this, but it's not really a perf gain. It's more of a code readability thing. Do we have good examples of analyzers in that category today?

**Comment by GrabYourPitchforks** [comment]
CI failures are known issue https://github.com/dotnet/runtime/issues/68939.

**Pull request merged**
