### PR TITLE
Disable frequently failing CriticalFinalizer test

### PR DESCRIPTION
**Pull request by jkotas**
Contributes to #76041

### CODE REVIEW

**Comment by filipnavara** [comment]
I thought https://github.com/dotnet/runtime/pull/76089/files was already supposed to do that and got merged...

**Comment by jkotas** [comment]
> I thought https://github.com/dotnet/runtime/pull/76089/files was already supposed to do that and got merged...

It disabled the test for coreclr only. The test is failing everywhere else as well. And the issue was not labelled `disabled-test` so I did not even know that this was done.

**Comment by VSadov** [comment]
It looks like #76089 did this incorrectly. The format of this file is confusing. - there should be a name of the test (not the containing folder) followed by a "/".

Also I disabled the test for coreclr only, but it fails on Mono, with the same "Finalized 0 Normal and 0 Critical objects." failure.
That likely indicates the issue with the test. Hard to imagine the same bug in two different GCs.

**Comment by jkotas** [comment]
> That likely indicates the issue with the test. 

Yes, it is a test issue. 

Note that this test was recently moved from old Mono test bed that was not running to the actively running tests

**Comment by VSadov** [comment]
> That likely indicates the issue with the test. Hard to imagine the same bug in two different GCs.

There is still a possibility that there are different reasons for objects not collected - Mono does not guarantee anything since the stack scan is conservative, (although the stack should be nearly empty when Collect() is called)

The reason for CoreCLR failing to collect is harder to guess. It should be deterministic.

**Review by VSadov — APPROVED** [review]
Thanks!

**Comment by VSadov** [comment]
> moved from old Mono test bed that was not running

Not running? That would explain failures on Mono.

**Review by filipnavara — APPROVED** [review]

**Review by karelz — APPROVED** [review]

**Comment by AntonLapounov** [comment]
For CoreCLR, I have found that either setting `arr = null` or doing `GC.Collect(); GC.WaitForPendingFinalizers();` two times in a row fixes the issue, which may indicate the `arr` array remains rooted on the first `GC.Collect()` call.  Apparently, a number of existing tests for finalizers also call `GC.Collect()` twice in a row, e.g., https://github.com/dotnet/runtime/blob/ab5639217624dbea4acc9368f27bfd56ad3eb792/src/tests/GC/Features/Finalizer/finalizeother/finalizearray.cs#L44-L46

Also, it is much easier to reproduce the issue with tiered compilation turned off.

The original Mono test would not use the array of references and it would pass if at least one of the `Normal` (`P`) instances out of 100 was collected, so it used to be much weaker (and not compatible with GC stress).

**Review by AntonLapounov — APPROVED** [review]
Thanks!

**Comment by AntonLapounov** [comment]
The failure in 'CoreCLR Product Build windows x86 release' is #48070.

**Comment by VSadov** [comment]
I suppose, since this is blocking clean CI and tests are passing we can merge.

**Pull request merged**
