### PR TITLE
JIT: Simplify block insertion logic during loop compaction

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Similar to #107371, don't worry about breaking up fallthrough when moving non-loop blocks out of loop bodies. We can rely on block layout to restore any fallthrough behavior worth keeping.

I expect this will incur diffs from `optSetBlockWeights`, since it still relies on the lexical ordering of blocks.

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
[Small diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=798788&view=ms.vss-build-web.run-extensions-tab) as expected; odd that TP didn't improve. I'm guessing we don't need to compact loops all that often, so pre-computing `insertionPoint` is often wasted.

**Comment by amanasifkhalid** [comment]
cc @dotnet/jit-contrib, @AndyAyersMS PTAL. Thanks!

**Review by AndyAyersMS — APPROVED** [review]
Ultimately, we should not need to compact loops at all.

But that may be too radical a change to make right now.

**Comment by amanasifkhalid** [comment]
> Ultimately, we should not need to compact loops at all.

Yeah, once we replace `optSetBlockWeights` with something graph-based, I think it'll be easier to get rid of loop compaction. I'll give it a try once we're at that point.

**Comment by AndyAyersMS** [comment]
Which reminds me -- I wonder if we should switch the layout RPO over to something like the "loop aware" RPO-inspired ordering that is now used in VN?

The main distinction being that that RPO may intermingle non-loop blocks with loop blocks, whereas the loop aware ordering takes care to visit all loop blocks before any blocks that may follow.

**Comment by AndyAyersMS** [comment]
There's not yet a convenient abstraction for this order but it would not be too hard to make one that VN and something else could share.

**Comment by amanasifkhalid** [comment]
> Which reminds me -- I wonder if we should switch the layout RPO over to something like the "loop aware" RPO-inspired ordering that is now used in VN?

Interesting, I wasn't aware of this functionality. I'll take a look at it next. It would be nice if this could render `fgMoveHotJumps` mostly redundant: Aside from ensuring loops are compact, if the RPO-aware layout also ensures the loop head is at the top of the loop, then I think we shouldn't have to consider back edges in `fgMoveHotJumps` at all. Instead, `fgMoveHotJumps` will just be for moving blocks with multiple predecessors up to the hottest one.

**Pull request merged**
