### PR TITLE
add RID for Alpine 3.15

### PR DESCRIPTION
**Pull request by ayakael**
Contributes to dotnet/core#6985 
I havn't seen this popup yet, so here is a merge request to add RID for Alpine 3.15. Tell me if I'm stepping on your toes @wfurt, I'll close it if so :). 

Made as part of Alpine Linux dotnet31 / dotnet5 packaging project, see dotnet/source-build#2695

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=62938) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=62938) before we can accept your contribution.<br/><br/>:x: ayakael [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=62938)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=62938) it.</sub>

**Comment by danmoseley** [comment]
@wfurt do you normally do this?

**Comment by wfurt** [comment]
yes, sometimes @danmoseley .

**Review by wfurt — APPROVED** [review]
LGTM

**Pull request merged**
