### PR TITLE
FastMod for EEHashTable (Faster virtual generics)

### LINKED ISSUE #65778: Use Fast-Mod algorithm for native EEHashTableBase
When I profile this simple virtual generic callsite:
```csharp
public class Prog
{
    static void InvokeVGM(Prog p)
    {
        while (true)
            p.VGM<string>();
    }

    virtual void VGM<T>() {}
}
```
in VTune I see `div` as the most expensive part (if I read it correctly):
image
It turns out to be a EEHashTable lookup:
image

And It does make sense since div is a very expensive operation, on some CPU its latency can be bigger than 100 cycles. On my Coffee Lake it's 26/6 while e.g. mul is 3/1 (Latency/rec.trput)

The managed Dictionary was optimized with ["Fast Mod" algorithm](https://lemire.me/blog/2019/02/08/faster-remainders-when-the-divisor-is-a-constant-beating-compilers-and-libdivide/) where we pre-calculate a special multiplier every time a new bucket is added and then can avoid expensive idiv operation by using mul see https://github.com/dotnet/coreclr/pull/27299 and https://github.com/dotnet/runtime/pull/406

Quick demo:
```csharp
public static uint Test(uint x)
{
    uint result = 0;

    ulong cachedMul = GetFastModMultiplier(y);
    for (int i = 0; i < x; i++)
    {
        // result = i % x;
        result = FastMod(i, x, cachedMul);
    }
    return result;
}

public static ulong GetFastModMultiplier(uint divisor) =>
    ulong.MaxValue / divisor + 1;

[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static uint FastMod(uint value, uint divisor, ulong multiplier) => 
    (uint)(((((multiplier * value) >> 32) + 1) * divisor) >> 32);
```

NOTE: the algorithm adds an overhead on dictionary expansion
NOTE2: `CompareKeys` is not inlined

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/65778

It was suggested to use a different data structure for `CORINFO_HELP_VIRTUAL_FUNC_PTR` but that is a more complicated change and I think this one worth having too anyway.

Benchmark:
```csharp
using System.Text.Json.Nodes;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Benchmarks).Assembly).Run(args);

public class Benchmarks
{
    public virtual void VGM<T>() { }

    [Benchmark]
    public void CallVirtualGenericMethod() => VGM<int>();



    // System.Text.Json
    JsonNode _jsonNode = true;

    [Benchmark]
    public bool JsonNodeConversion() => (bool)_jsonNode;



    // string interning
    string str = "Hello";

    [Benchmark]
    public string StrIsInterned() => string.IsInterned(str);
}
```

|                    Method |                 Toolchain |      Mean |     Error |    StdDev | Ratio |
|-------------------------- |-------------------------- |----------:|----------:|----------:|------:|
|  CallVirtualGenericMethod |    \Core_Root\corerun.exe |  5.299 ns | 0.0364 ns | 0.0322 ns |  1.00 |
|  CallVirtualGenericMethod | \Core_Root_PR\corerun.exe |  4.166 ns | 0.1064 ns | 0.1383 ns |  0.79 |
|                           |                           |           |           |           |       |
|        JsonNodeConversion |    \Core_Root\corerun.exe |  5.509 ns | 0.0070 ns | 0.0062 ns |  1.00 |
|        JsonNodeConversion | \Core_Root_PR\corerun.exe |  4.177 ns | 0.0461 ns | 0.0431 ns |  0.76 |
|                           |                           |           |           |           |       |
|             StrIsInterned |    \Core_Root\corerun.exe | 54.741 ns | 0.1900 ns | 0.1780 ns |  1.00 |
|             StrIsInterned | \Core_Root_PR\corerun.exe | 50.172 ns | 0.3521 ns | 0.2750 ns |  0.92 |

### CODE REVIEW

**Comment by EgorBo** [comment]
PTAL @VSadov @jkotas

**Comment by VSadov** [comment]
In the long term we should experiment with a more lightweight caching scheme for virtual generics. 
However, this change is an obvious improvement to the current implementation and will benefit everything that uses `EEHashTable`.

**Review by VSadov — APPROVED** [review]
LGTM. Thanks!!

**Review by jkotas — APPROVED** [review]
Thanks!

**Comment by elinor-fung** [comment]
@EgorBo `System.Runtime.InteropServices.Tests.GetEndComSlotTests.GetEndComSlot_Windows_ReturnsExpected` are failing on x64 with this change: https://dev.azure.com/dnceng/public/_build/results?buildId=1634854&view=ms.vss-test-web.build-test-results-tab&runId=45284702&resultId=151347&paneView=debug

```
System.Runtime.InteropServices.Tests.GetEndComSlotTests.GetEndComSlot_Windows_ReturnsExpected(type: typeof(System.Runtime.InteropServices.Tests.Common.IComImportObject), expected: 6) [FAIL]
  System.DivideByZeroException : Attempted to divide by zero.
  Stack Trace:
       at System.Runtime.InteropServices.Marshal.GetEndComSlot(Type t)
```

**Comment by EgorBo** [comment]
Ouch, sorry for that, I thought that job failed everywhere and merged, looking at it now

**Comment by EgorBo** [comment]
@elinor-fung filed https://github.com/dotnet/runtime/pull/66035

**Comment by EgorBo** [comment]
Improvement on alpine-x64 https://github.com/dotnet/perf-autofiling-issues/issues/3977

**Pull request merged**
