### PR TITLE
JIT: Handle TYP_DOUBLE on arm softFP similarly to TYP_LONG

### PR DESCRIPTION
**Pull request by jakobbotsch**
Avoids `PUTARG_REG` being a multi-reg node on arm32 to handle this special case.

The gist of the change: we expect multi-reg structs, including `TYP_LONG` on arm32/x86, to be put into a `FIELD_LIST(PUTARG_REG(low), PUTARG_REG(high))` form before LSRA. For multi-reg structs this happens during morph, while for `TYP_LONG` we keep them as primitives until lowering, so it happens during lowering.

There was a special case for arm32 with softFP where `TYP_DOUBLE` also ends up being a similar multi-reg struct that is passed in two integer registers. There was a bunch of special casing to handle this in the backend, by making `PUTARG_REG` and `BITCAST` multireg nodes on arm32 only.
This PR instead puts `TYP_DOUBLE` into the expected multireg-struct form during lowering, allowing it to be handled like any other multireg struct.

Motivation is to avoid arm32-specific logic in #103866, which currently fails in CI for arm32 softFP because of this special case.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @dotnet/samsung @kunalspathak

**Review by tomeksowi — APPROVED** [review]
Thank you for the cleanup. LGTM, shouldn't affect RISC-V.

**Review by t-mustafin — APPROVED** [review]

**Review by clamp03 — APPROVED** [review]
Thank you.
\+ Checked coreclr test on armel tizen

**Review by kunalspathak — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
