### PR TITLE
[Android] Add an AzDO pipeline to run tests on emulators running all supported Android API levels

### PR DESCRIPTION
**Pull request by simonrozsival**
We support Android API 21+ but we only run runtime and library tests on devices and emulators running API 29. This PR will add a separate pipeline that'll run once a week on all the API levels currently available in helix (21-32).

### CODE REVIEW

**Comment by MattGal** [comment]
This pull request caused 13,817 work items to run in Helix.  Is there a solid reason why we think this is going to be worth the compute and investigation costs it incurs?

**Comment by steveisok** [comment]
> This pull request caused 13,817 work items to run in Helix (from the commit 15 hours ago). Is there a solid reason why we think this is going to be worth the compute and investigation costs it incurs?

We can certainly scale back the number of work items because that's... quite a lot.  I would like to have some coverage as there have been issues found at various API levels.

**Comment by steveisok** [comment]
@simonrozsival @akoeplinger We should discuss what tests make sense.

**Comment by simonrozsival** [comment]
@MattGal 14k is definitely too much. This pipeline should result in roughly third of that: 2 architectures * 12 API levels * 220 work items per queue = 5,280 work items. Did some work items run multiple times because the emulators for API 31 and 32 kept failing (https://github.com/dotnet/arcade/issues/12336)?

We could run the tests only on x64 and cut the number of work items in half. I also agree that not all tests need to be tested across all API levels and there don't have to be 220 work items per queue.

**Comment by MattGal** [comment]
> @MattGal 14k is definitely too much. This pipeline should result in roughly third of that: 2 architectures * 12 API levels * 220 work items per queue = 5,280 work items. Did some work items run multiple times because the emulators for API 31 and 32 kept failing ([dotnet/arcade#12336](https://github.com/dotnet/arcade/issues/12336))?
> 
> We could run the tests only on x64 and cut the number of work items in half. I also agree that not all tests need to be tested across all API levels and there don't have to be 220 work items per queue.

I'm sorry you're right, it's more like **14481** work items ran :).  However to be fair I was just adding up all the work items run by a single commit of this draft PR.

If you have Kusto access you can check my work by doing:
```
let theJobIds = 
Jobs 
| where Source == "pr/public/dotnet/runtime/refs/pull/80925/merge" 
| extend propz = parse_json(Properties)
| where propz["BuildId"] == "148993" or propz["BuildId"] == "148994"
| project JobId;
WorkItems
| where JobId  in (theJobIds)
| where Name != JobName // ignore the queueing work items, these aren't real
```
Where the two Job Ids (148993, 148994) represent the "runtime" and "runtime android..." pipelines you ran as part of your recent commit:

https://dnceng-public.visualstudio.com/public/_build/results?buildId=148994&view=results
https://dnceng-public.visualstudio.com/public/_build/results?buildId=148993&view=results

If you add `| where QueueName contains "android"`, you'll indeed see 5812 work items which is super close to your estimate.

This is still an enormous number.  I'm in no way blocking you I just wanted folks to be aware what this would cost in terms of machine time.  The query I shared above can easily be extended to summarize total runtime, which for JUST the 5812 android work items I mentioned is 3 days, 6.5 hours of machine time.

**Comment by steveisok** [comment]
@MattGal I gave it a little thought and talked a bit more with Alex and Simon... I think it's important to run the full suite as it has uncovered problems with older and newer API levels that were previously untested.  If we run this once a week or once every two weeks, I don't think the traffic generated is significant enough to hold it back.

**Comment by MattGal** [comment]
> @MattGal I gave it a little thought and talked a bit more with Alex and Simon... I think it's important to run the full suite as it has uncovered problems with older and newer API levels that were previously untested. If we run this once a week or once every two weeks, I don't think the traffic generated is significant enough to hold it back.

As long as someone actually pays attention to it, no objections here.

**Pull request closed without merging**
