### PR TITLE
[mono][aot] Fix an assert.

### PR DESCRIPTION
**Pull request by vargaz**
This is hit when AOTing GitHub_27678.dll.

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
Should also remove

https://github.com/dotnet/runtime/blob/2c37a2df57ffd8e940a12a678e1cac383d7acf97/src/tests/issues.targets#L1918-L1920

**Comment by vargaz** [comment]
Didn't enable the test as running it still seems to fail.

**Pull request merged**
