### PR TITLE
Fix NativeLibraryTests for ilasm round-trip

### LINKED ISSUE #84914: Test failure Interop\\NativeLibrary\\API\\NativeLibraryTests\\NativeLibraryTests.cmd
Run: [runtime-coreclr ilasm 20230415.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=240791&view=ms.vss-test-web.build-test-results-tab&runId=4623314&resultId=101167&paneView=debug)

Failed test:
```
coreclr windows x64 Checked ilasmroundtrip @ Windows.10.Amd64.Open

- Interop\\NativeLibrary\\API\\NativeLibraryTests\\NativeLibraryTests.cmd
```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\B28409BA\w\AC66093D\uploads\Reports\Interop.NativeLibrary\API\NativeLibraryTests\NativeLibraryTests.output.txt
Raw output:
BEGIN EXECUTION
C:\h\w\B28409BA\p\ildasm.exe /raweh /unicode /out=NativeLibraryTests.dasm.il NativeLibraryTests.dll
C:\h\w\B28409BA\p\ilasm.exe /output=NativeLibraryTests.asm.dll  NativeLibraryTests.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'NativeLibraryTests.dasm.il'  to EXE --> 'NativeLibraryTests.asm.dll'
Source file is UNICODE

Assembled method Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableContextAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullablePublicOnlyAttribute::.ctor
Assembled method GetLibraryExportTests?<>c__DisplayClass8_0::.ctor
Assembled method GetLibraryExportTests?<>c__DisplayClass8_0::<GetLibraryExport>b__0
Assembled method GetLibraryExportTests?<>c__DisplayClass9_0::.ctor
Assembled method GetLibraryExportTests?<>c__DisplayClass9_0::<TryGetLibraryExport>b__0
Assembled method GetLibraryExportTests::.ctor
Assembled method GetLibraryExportTests::GetValidExport_ManualMangling
Assembled method GetLibraryExportTests::GetValidExport
Assembled method GetLibraryExportTests::NullHandle
Assembled method GetLibraryExportTests::NullExport
Assembled method GetLibraryExportTests::ExportDoesNotExist
Assembled method GetLibraryExportTests::Dispose
Assembled method GetLibraryExportTests::GetLibraryExport
Assembled method GetLibraryExportTests::TryGetLibraryExport
Assembled method GetLibraryExportTests::RunExportedFunction
Assembled method GetMainProgramHandleTests?<>c__DisplayClass9_0::.ctor
Assembled method GetMainProgramHandleTests?<>c__DisplayClass9_0::<GetSymbolFromMainProgramHandle>b__0
Assembled method GetMainProgramHandleTests::CanAccessCoreRunExportFromMainProgramHandle
Assembled method GetMainProgramHandleTests::NativeLibraryLoadDoesNotLoadSymbolsGlobally
Assembled method GetMainProgramHandleTests::GloballyLoadedLibrarySymbolsVisibleFromMainProgramHandle
Assembled method GetMainProgramHandleTests::InvalidSymbolName_Fails
Assembled method GetMainProgramHandleTests::GloballyLoadedLibrarySymbolsVisibleFromMainProgramHandle_Mangling
Assembled method GetMainProgramHandleTests::FreeMainProgramHandle
Assembled method GetMainProgramHandleTests::get_IsHostedByCoreRun
Assembled method GetMainProgramHandleTests::GetSymbolFromMainProgramHandle
Assembled method GetMainProgramHandleTests::LoadLibraryGlobally
Assembled method GetMainProgramHandleTests::.ctor
Assembled method GetMainProgramHandleTests::.cctor
Assembled method NativeLibraryTests?<>c__DisplayClass24_0::.ctor
Assembled method NativeLibraryTests?<>c__DisplayClass24_0::<LoadLibrary_NameOnly>b__0
Assembled method NativeLibraryTests?<>c__DisplayClass25_0::.ctor
Assembled method NativeLibraryTests?<>c__DisplayClass25_0::<TryLoadLibrary_NameOnly>b__0
Assembled method NativeLibraryTests?<>c__DisplayClass26_0::.ctor
Assembled method NativeLibraryTests?<>c__DisplayClass26_0::<LoadLibrary_WithAssembly>b__0
Assembled method NativeLibraryTests?<>c__DisplayClass27_0::.ctor
Assembled method NativeLibraryTests?<>c__DisplayClass27_0::<TryLoadLibrary_WithAssembly>b__0
Assembled method NativeLibraryTests?<>c__DisplayClass28_0::.ctor
Assembled method NativeLibraryTests?<>c__DisplayClass28_0::<FreeLibrary>b__0
Assembled method NativeLibraryTests::.ctor
Assembled method NativeLibraryTests::LoadLibraryFullPath_NameOnly
Assembled method NativeLibraryTests::LoadLibraryOnNonExistentFile_NameOnly
Assembled method NativeLibraryTests::LoadLibraryOnInvalidFile_NameOnly
Assembled method NativeLibraryTests::LoadLibraryRelativePaths_NameOnly
Assembled method NativeLibraryTe


Stack trace
   at Interop_NativeLibrary._API_NativeLibraryTests_NativeLibraryTests_._API_NativeLibraryTests_NativeLibraryTests_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by elinor-fung**
Fixes https://github.com/dotnet/runtime/issues/84914

### CODE REVIEW

**Comment by elinor-fung** [comment]
Manually kicked off ilasm run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=267561

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Review by jkoritzinsky — APPROVED** [review]

**Comment by elinor-fung** [comment]
The ilasm run failure in ParallelCrashMainThread is unrelated.
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85991-head-43693245b7c342a888/PayloadGroup0/1/console.20fe21c9.log?helixlogtype=result

**Comment by elinor-fung** [comment]
Sharing violation when ilasm tries to write the file?
```
    baseservices\exceptions\simple\ParallelCrashMainThread\ParallelCrashMainThread.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\h\w\9BEB08EE\w\BB1D09DD\uploads\Reports\baseservices.exceptions\simple\ParallelCrashMainThread\ParallelCrashMainThread.output.txt
      Raw output:
      BEGIN EXECUTION
       cmd /c ..\ParallelCrash\ParallelCrash.cmd
      BEGIN EXECUTION
      C:\h\w\9BEB08EE\p\ildasm.exe /raweh /unicode /out=ParallelCrash.dasm.il ParallelCrash.dll
      C:\h\w\9BEB08EE\p\ilasm.exe /output=ParallelCrash.asm.dll  ParallelCrash.dasm.il
      
      .NET IL Assembler.  Version 8.0.0-ci
      Copyright (c) Microsoft Corporation.  All rights reserved.
      Assembling 'ParallelCrash.dasm.il'  to EXE --> 'ParallelCrash.asm.dll'
      Source file is UNICODE
      
      Assembled method Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor
      Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
      Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
      Assembled method System.Runtime.CompilerServices.NullableContextAttribute::.ctor
      Assembled method System.Runtime.CompilerServices.NullablePublicOnlyAttribute::.ctor
      Assembled method ParallelCrash::Main
      Assembled method ParallelCrash::CrashInParallel
      Assembled method ParallelCrash::.ctor
      Creating PE file
      
      Emitting classes:
      Class 1:System.Runtime.CompilerServices.NullablePublicOnlyAttribute
      Class 2:Microsoft.CodeAnalysis.EmbeddedAttribute
      Class 3:System.Runtime.CompilerServices.NullableAttribute
      Class 4:System.Runtime.CompilerServices.NullableContextAttribute
      Class 5:ParallelCrash
      Class 6:ParallelCrash?<>O
      
      Emitting fields and methods:
      Global 
      Class 1Fields: 1;Methods: 1;
      Class 2Methods: 1;
      Class 3Fields: 1;Methods: 2;
      Class 4Fields: 1;Methods: 1;
      Class 5Fields: 4;Methods: 3;
      Class 6Fields: 1;
      Resolving local member refs: 21 -> 21 defs, 0 refs, 0 unresolved
      
      Emitting events and properties:
      Global 
      Class 1
      Class 2
      Class 3
      Class 4
      Class 5
      Class 6
      Resolving local member refs: 0 -> 0 defs, 0 refs, 0 unresolved
      Writing PE file
      Failed to write output file, error code=0x80070020
      
      ***** FAILURE ***** 
      EXECUTION OF ILASM - Try 1 FAILED with status 1 
```

@BruceForstall have you seen anything similar in ilasm test runs? One thing I see is that `ParallelCrashMainThread` does call `cmd /c ..\ParallelCrash\ParallelCrash.cmd` since it sets `CLRTestProjectToRun`
https://github.com/dotnet/runtime/blob/c06191ee399ab060836c343096dfd8635ce3977b/src/tests/baseservices/exceptions/simple/ParallelCrashMainThread.csproj#L5
Maybe that would cause intermittent issues with ilasm round-trip runs?

**Comment by BruceForstall** [comment]
Some retry logic was added with https://github.com/dotnet/runtime/pull/46765 -- We thought we were seeing sharing violations due to anti-virus. But I haven't seen any similar issue since. In the linked example, it does try 4 times over 30+ seconds.

**Pull request merged**
