### PR TITLE
Add Microsoft.Extensions.Options.SourceGeneration to Transport Package

### PR DESCRIPTION
**Pull request by tarekgh**

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @eerhardt

**Review by ViktorHofer — APPROVED** [review]

**Review by ericstj — APPROVED** [review]

**Review by eerhardt — APPROVED** [review]

**Comment by tarekgh** [comment]
We are tracking the improvement of the process of including the source gen projects into the transitive package through the issue https://github.com/dotnet/runtime/issues/91698.

**Comment by tarekgh** [comment]
Failure is tracked with https://github.com/dotnet/runtime/issues/81911. Other failures are network connection/certificate failures.

**Pull request merged**
