### PR TITLE
Change our Android build and test legs to use the new CBL-Mariner-based images.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
This moves us closer to having all official platforms building on CBL-Mariner-based images.

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
I may have opened this a little prematurely (before the new docker images were published)... I'll rerun the pipelines tomorrow after the new images should be available.

**Review by sbomer — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
All the android legs passed and the failures are unrelated.

**Comment by MichalStrehovsky** [comment]
I think this broke the linux-bionic legs in the official builds. I'm monitoring them because I also made a change to bionic yesterday but we had an official build before my change merged that already had a broken bionic leg:

Official build at the commit this PR merged:
https://dnceng.visualstudio.com/internal/_build/results?buildId=2189200&view=results

Last official build before this one:
https://dnceng.visualstudio.com/internal/_build/results?buildId=2189095&view=results

Official build with my bionic change:
https://dnceng.visualstudio.com/internal/_build/results?buildId=2189352&view=results

The failure is:

```
  CMake Error at System.Security.Cryptography.Native/extra_libs.cmake:20 (file):
    file COPY cannot find "/usr/include/openssl": No such file or directory.
  Call Stack (most recent call first):
    System.Security.Cryptography.Native/CMakeLists.txt:14 (append_extra_cryptography_libs)
```

IIRC we had to do something special for OpenSSL since it's not part of the Android NDK. CC @directhex @akoeplinger @steveisok

**Comment by MichalStrehovsky** [comment]
I've submitted a revert PR here in case we want to unblock quickly: #86854

I just realized Monday is a holiday on the US so it's unlikely official build will be fixed very soon. I'm not completely blocked, because I have a long backlog of other things to do, but also there's two things that I want to see an official build for and official builds are currently broken.

**Pull request merged**
