### PR TITLE
Release 6.0 rc2 localized manifest

### PR DESCRIPTION
**Pull request by wli3**
Part of https://github.com/dotnet/sdk/issues/20497

### CODE REVIEW

**Review by lewing — APPROVED** [review]
Looks reasonable to me

@danroth27 any objections?

**Review by steveisok — APPROVED** [review]

**Comment by danroth27** [comment]
No objections from me.

**Review by marek-safar — APPROVED** [review]

**Comment by wli3** [comment]
@lewing @steveisok could you help me merge it? I don't have the permission

**Comment by wli3** [comment]
?

**Review by radical — APPROVED** [review]

**Comment by steveisok** [comment]
Approved by tactics over email.

**Pull request merged**
