### PR TITLE
Block exporting DllMain

### LINKED ISSUE #109543: [NativeAOT] Creating a new thread from DllMain makes the program get stuck.
### Description

NativeAOT dlls get stuck when creating a new thread from DllMain using `new Thread()`.
`Task.Run` does similar behavior, instead when I try to sleep inside the Task, it gets stuck.

### Reproduction Steps

- Make NativeAOT dynamic library project for Windows with DllMain.
```cs
using System.Runtime.InteropServices;
using Windows.Win32;

namespace ThreadTesting;

public static class ThreadTest {
    [UnmanagedCallersOnly(EntryPoint = "DllMain")]
    public unsafe static int DllMain(nint hModule, uint ul_reason_for_call, nint lpReserved) {
        // DLL_PROCESS_ATTACH = 1
        if (ul_reason_for_call == 1) {
            Console.WriteLine("Creating new thread");

            var thread = new Thread(SomeFunction);
            // It gets stuck here
            thread.Start();

            Console.WriteLine("Thread created");
        }

        return 1;
    }

    public static void SomeFunction() {
        Console.WriteLine("Hello inside new thread");
        Thread.Sleep(1000);
        Console.WriteLine("Slept successfully");
    }
}
```

- Make a simple C++ console app that loads the library with LoadLibrary.
```cpp
int main()
{
    LoadLibrary(L"ThreadTesting.dll");
}
```

### Expected behavior

The new thread runs correctly.

### Actual behavior

The program gets stuck.

### Regression?

_No response_

### Known Workarounds

Using Native Windows function CreateThread (PInvoke) works.

### Configuration

- .NET 9.0.0-rc.2.24473.5
- Windows 11 Build 22631
- x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by MichalPetryka**
Try to block defining DllMain in NativeAOT.

@jkotas @MichalStrehovsky would this make sense?

Closes #109543

### CODE REVIEW

**Comment by MichalPetryka** [comment]
Would https://github.com/dotnet/runtime/blob/23eaf2568fd7d3d712654f1f7224eaef21819d43/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ExportsFileWriter.cs#L31 maybe be a better place for this?

**Comment by nitrog0d** [comment]
I think this should be optional or not implemented because you can still call native code from it using DirectPInvoke, and a few projects use DllMain unsafely.

**Comment by MichalStrehovsky** [comment]
> @jkotas @MichalStrehovsky would this make sense?

IMHO this just causes a compiler crash with a stack trace that looks like a compiler bug. A determined person is just going to export it under a different name and pass `/entry:` as a `<LinkerArg>` item to tell the linker to find a different entrypoint and we won't see DllMain in the stack trace when they inevitably go and file an issue in this repo because what they just did doesn't work and ask us to troubleshoot. I'd prefer seeing DllMain so that I can won't fix and close in two minutes.

Also, people who do cursed thing

> I think this should be optional or not implemented because you can still call native code from it using DirectPInvoke, and a few projects use DllMain unsafely

One must not take locks under loader locks. If you're running managed code, you never know when the GC is going to trigger. This **never** works safely.

**Comment by MichalPetryka** [comment]
> I'd prefer seeing DllMain so that I can won't fix and close in two minutes.

Issue is, without this people might keep doing this if they don't see it crash immediately in some cases.

**Comment by nitrog0d** [comment]
Maybe this can be documented somewhere? I know [this](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-best-practices#general-best-practices) exists (`Use managed code.` line), but I didn't know it applied to NativeAOT.

**Comment by nitrog0d** [comment]
> A more reasonable approach would be to add a lang warning/error or to only allow it in an unsafe context.
+1 this, a warning would be way better.

**Comment by Algoinde** [comment]
I also think a compiler warning to educate the user about the consequences of doing this would be the way to go. It'll result in less wasted time for both people who didn't know this is problematic (they will not spend extra time trying to figure out why it is failing, because if they didn't know it to begin with, it will be even harder for them to understand), and for the people who do know what they are doing (they will just understand and choose to ignore the warning).

This also adds the opportunity to reduce support tickets by explicitly stating that this behavior is not supported.

**Comment by hez2010** [comment]
It's already not possible to export a `DllMain` because managed implementation of `DllMain` can make the loader deadlock and crash on startup. It won't break any existing projects because of this.

**Comment by nitrog0d** [comment]
> It's already not possible to export a `DllMain` because managed implementation of `DllMain` can make the loader deadlock and crash on startup. It won't break any existing projects because of this.

It is currently possible to export `DllMain` (as this PR is trying to do the opposite, stop this), and it is being used in some projects. I now understand what a loader lock is and all we're asking is for is an warning and documentation for people who might come across the same issue as me.

**Comment by slxdy** [comment]
> One must not take locks under loader locks. If you're running managed code, you never know when the GC is going to trigger. This never works safely.

Also, if I understand this correctly, the GC runs on a separate thread right? The thread shouldn't be able to start until after the loader has finished loading the module, so the only issue I see is the lack of GC until DllMain is done?

**Comment by jkotas** [comment]
> the GC runs on a separate thread right? 

It does not matter which thread the GC physically runs on. The important detail is that the thread that is executing DllMain may get suspended and wait for the GC to finish running.

> If anything, it would break some existing projects.

Projects that use this can be broken anytime by seemingly unrelated change. It is fairly common situation with invalid interop patterns. It happens to work and then breaks all of a sudden.

**Comment by huoyaoyuan** [comment]
I don't think it's right to block something *just* because it's potentially unreliable. I believe there's safe pattern that can work, though it will be for the user's own risk.

**Comment by MichalStrehovsky** [comment]
> I believe there's safe pattern that can work, though it will be for the user's own risk.

If you don't believe the GC suspension argument, think about what needs to happen before the first line of `DllMain` can run - the entire runtime needs to initialize first, background GC threads, finalizer thread, etc. None of that was written with `DllMain` in mind. We do in fact `LoadLibrary`/`GetProcAddress` at runtime startup for example, we just happen to not do it for a DLL that is not already loaded. We also run all of the managed module initializers before the first line of users DllMain, who knows what's there. An app that does this can get broken by a minor servicing fix in the libraries. This code is completely out of user control and runs as part of the reverse p/invoke transition before the "real" DllMain body starts executing.

We very explicitly don't initialize the runtime in `DllMain`, but do it lazily the first time an `UnamangedCallersMethod` is called. By making `DllMain` an `UnmanagedCallersOnly` method one's making all that code run in `DllMain`. We went to great lengths not to run that in `DllMain`.

I don't think there's any pattern where this can be safe, it's just luck-driven development and you never know when it stops working. We run so much code that there's no way to tell what to test for, it could even fail due to OS version, AV products, GPU drivers with user mode components, etc. We don't audit any of this for DllMain safety.

**Comment by huoyaoyuan** [comment]
> I don't think there's any pattern where this can be safe, it's just luck-driven development and you never know when it stops working.

Yes I do agree that luck-driven development is always not reliable, but workloads like hooks are already luck-driven. There are also more hacky areas like zerosharp, though you may know more details of it.

I'm concerned about doing hard error at non-ideal position of the toolchain. It's in the compiler that builds the object file, not in the sdk toolchain that links and assembles the runtime activation code. It will force people who want to do more hacky stuffs to rebuild their own toolchain.

**Comment by slxdy** [comment]
I would also like to add that the usage of NativeAOT for unsafe tasks like this is unavoidable. I understand the main point of NativeAOT is it avoid JIT and make the runtime faster in general, but let's be honest, if you're already giving people the ability to create native modules with exports without the need for mid level languages, of course you'd expect other basic DLL features to be supported.

**Comment by jkotas** [comment]
> It will force people who want to do more hacky stuffs to rebuild their own toolchain.

It would be perfectly fine with me. We prefer clarity, reliability and deterministic behaviors over unreliable non-deterministic behaviors. You can find number of examples where we have turned unreliable behaviors that sometimes worked by luck into a hard error.

> if you're already giving people the ability to create native modules with exports without the need for mid level languages, of course you'd expect other basic DLL features to be supported.

This is invalid assumption.

There are many low-level interop constructs that are impossible to implement in .NET (with or without NativeAOT) reliably. More examples in addition to DllMain on Windows: SEH exception handlers on Windows (e.g. the handler that you register with `AddVectoredExceptionHandler`), signal handlers on Unix, or in-proc [interop with golang](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/abi-support#golang). .NET is not appropriate tool for these situations. You have to use more lower-level language in these cases.

**Comment by hez2010** [comment]
I don't think it's appropriate to do this in ilc. Instead, we can do this in the msbuild task. 
By using ilc directly we can link the program to a custom runtime where there's no GC at all, just like what zerosharp did. In this case `DllMain` would just run fine without any issue. 
Ilc is a compiler that compiles IL to machine code, blocking exporting `DllMain` in ilc is not the correct layer to do this.

**Comment by nitrog0d** [comment]
Or drop the idea of blocking it and add warnings and documentation, as multiple people asked...

**Comment by slxdy** [comment]
> I don't think it's appropriate to do this in ilc. Instead, we can do this in the msbuild task. 
> By using ilc directly we can link the program to a custom runtime where there's no GC at all, just like what zerosharp did. In this case `DllMain` would just run fine without any issue. 
> Ilc is a compiler that compiles IL to machine code, it's agnostic with .NET runtime and there are use cases outside .NET, blocking exporting `DllMain` in ilc is not the correct layer. 

If I understand this correctly, you mean completely disable the GC until we're out of the load context?

**Comment by hez2010** [comment]
> you mean completely disable the GC until we're out of the load context?

Nope. I meant linking to a customized runtime without DllImport and GC at all or even not linking to any runtime.

**Comment by slxdy** [comment]
Hm, im still confused. So if this was a thing, what exactly would be the limitations for DllMain?

**Comment by hez2010** [comment]
> Hm, im still confused. So if this was a thing, what exactly would be the limitations for DllMain?

Threads in `DllMain` hold the loader lock so no additional DLLs can be dynamically loaded or initialized. This can lead to deadlock because the initialization of the default nativeaot runtime calls `LoadLibrary` to load other libraries. Making it works out-of-box is not possible.
However, if you provide your own runtime that doesn't load any other libraries (for example, you use pure assembly code to implement a runtime without relying on any other libraries), you can make `DllMain` work, but which would also mean that you won't be able to use most features provided by the BCL.

**Comment by MichalStrehovsky** [comment]
> The real issue is the GC and other threads, which wont start until DllMain is done

It will start before the first line of DllMain per my last comment https://github.com/dotnet/runtime/pull/109545#issuecomment-2458801150.

Here's disassembly of:

```csharp
    [UnmanagedCallersOnly(EntryPoint = "DllMain")]
    static int DllMain(nint hinst, int reason, nint reserved)
    {
        return 1;
    }
```

image

The call in the red circle will create GC threads and run tons of code that is totally out of your control. None of that code was written with DllMain in mind. Even code from random NuGets your project depends on will run as part of that call since that's where we run all `[ModuleInitializer]` from the entire app.

C# is not a suitab̷͎́͛̽̎͌̌̐l̸̪͑̀́̊̕̚̚͝e lang̶̡̪̿͂͊͆͝u̴̬̖̭͔̭̅͌̒̾́̊̂̾̕̕͠a̵͚̟̰͇̦͂͛̚ge to write DllMain. You cannot write DllMain in C#. The C# language is not ḽ̴̼̳̹̯͎̿͐̔̐̓̍̏̆̀̇̂͘ơ̸̻̝͊͛ẘ̸̩̬̊͛͆͗ ̴̟̰͖̹̯͉̇̍͊͗̂̓͗̓͘͜͠͝ͅl̷̨͚͍̤̭̭͉̥̈͂̀̈́͒̂̊̒͒͐͛̈́́̏̚͜è̸̻̬̭̘̻̐́͒́͘͠͝vel enough to write DllMain in.

Just write DllMain in C and [link it into the shared library](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop#linking).

**Comment by slxdy** [comment]
I don't think you understand. Threads created in DllMain won't start executing until the module is fully loaded.
So to summarize the current potential dangers:
- No GC threads
- Potential dead locks from nuget packages
- Sys API restrictions

Does that really justify completely blacklisting an export name?

> Just write DllMain in C and [link it into the shared library](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop#linking).

So you'll blacklist it from the official exports feature, yet still give people a workaround? What's the point. People will still use it. You're just going to make it more difficult than it has to be. Literally no one is benefiting from this change. If anything, looking at the reactions to this PR, it's only going to break existing projects.
If you don't officially support it, then let users know, but don't block it completely if it is being used in existing projects. Sure, it might not work depending on what the user does, but if that's the risk they're willing to take, then so be it.
You wouldn't ban the usage of pointers just because they had the potential to segfault the entire process, would you?

**Comment by huoyaoyuan** [comment]
> Literally no one is benefiting from this change.

No. C implementation is totally reliable, because it won't initialize anything not written by the user.

> If anything, looking at the reactions to this PR, it's only going to break existing projects.

All the existing projects are **already broken** if no action is taken. My concern is about how it blocks hacky workarounds.

> You wouldn't ban the usage of pointers just because they had the potential to segfault the entire process, would you?

Pointers are safe if you use them properly. Reverse P/Invoke in DllMain is never safe.

**Comment by AhmedZero** [comment]
I have case the DLLMain is worked for me and I use it in my projects without any problems.
The cases worked in . NET 8, I don't test it in .NET 9 yet.

**Comment by MichalPetryka** [comment]
Superseded by #109699.

**Pull request closed without merging**
