### PR TITLE
Remove platform dependent compilation of System.Private.Uri

### PR DESCRIPTION
**Pull request by huoyaoyuan**
It's only using a boolean property to decide platform dependent behavior. I've seen `OperatingSystem.IsWindows()` already in for other BCL libraries.
Don't know if any infrastructure change required.

### CODE REVIEW

**Comment by MihaZupan** [comment]
What's the motivation behind this change?

Does the build treat this as a constant and is able to eliminate the dead code?

If not, this becomes a size regression, and I don't think we should make the change.

**Comment by huoyaoyuan** [comment]
> Does the build treat this as a constant and is able to eliminate the dead code?

That's what I want to ask. It should be true for R2R, but I don't know if IL trim is platform dependent when trimming BCL.

**Comment by huoyaoyuan** [comment]
Release build size of System.Private.Uri, placed in `artifacts\bin\runtime`:

PR: 90112 bytes
image
main: 90112 bytes
image

I confirmed again that they are same size with different timestamp.

It's better to ask someone in infrastructure team how exactly it builds.

**Comment by ViktorHofer** [comment]
cc @ericstj as we just recently talked about runtime checks vs build dimensions for platforms.

**Comment by ViktorHofer** [comment]
> If not, this becomes a size regression, and I don't think we should make the change.

As System.Private.Uri doesn't use any compiler preprocessor directives, non applicable platform dependent code is already emitted into the assembly. That's why a difference in size isn't observable when switching to runtime checks.

**Comment by ericstj** [comment]
> As System.Private.Uri doesn't use any compiler preprocessor directives, non applicable platform dependent code is already emitted into the assembly. That's why a difference in size isn't observable when switching to runtime checks.

Exactly.  This change is just removing metadata for the constant, and changing all the call-sites from having the constant literal to a method call to `OperatingSystem.IsWindows()` -- negligible code size diff.  If any of the modified codepaths are performance sensitive it might be interesting to profile this change to see if the JIT produces code that's just as fast and doesn't introduce method calls.  Alternatively since the only place this assembly ships is in the shared framework which links the assembly for a specific platform it's possible the linker could remove the method call and replace it with a constant as it was before.

**Comment by danmoseley** [comment]
It's hard to imagine this not getting inlined...
```c#
        /// Indicates whether the current application is running on Windows.
        /// </summary>
        public static bool IsWindows() =>
#if TARGET_WINDOWS
            true;
#else
            false;
#endif
```

**Review by jkotas — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
