### PR TITLE
Improve auto-atomicity for Regex loops

### PR DESCRIPTION
**Pull request by stephentoub**
This is the same as the first commit from https://github.com/dotnet/runtime/pull/63518.  It was reverted in #63984  due to test failures after merging, tracked down to the second commit from that PR being inherently flawed.  I've simply deleted that commit, save for a single test that it was adding which I've amended into the first commit.

Since the code for the commit hasn't changed and was already reviewed, I'll go ahead and merge it once it's green.

### CODE REVIEW

**Comment by danmoseley** [comment]
Are you force pushing more these days ? 🙂 I'm not sure whether I reviewed both commits or just the first. What was flawed about the second one?

**Comment by stephentoub** [comment]
> Are you force pushing more these days ?

Adding a commit isn't force pushing.

> What was flawed about the second one?

The whole concept of extending auto-atomicity to lazy loops was flawed. It works with greedy because you've already explored the full extent of what could match the loop. But with lazy, making it atomic will cause it to only explore the minimum, which will then introduce match failures if the match would only have succeeded by exploring the full length of the loop.

**Comment by danmoseley** [comment]
Makes sense.

(I just meant that the commits in the original change appear below my review)

**Comment by stephentoub** [comment]
> (I just meant that the commits in the original change appear below my review)

Rebased to fix merge conflicts

**Pull request merged**
