### PR TITLE
[release/7.0] Crash when region survives >2GB

### LINKED ISSUE #79486: NET 7: Calling `GC.Collect()` causes Access Violation exception (cx0000005)
### Description

Calling `GC.Collect()` when having sufficiently large objects in LOH and using the Server Garbage Collection causes Access Violation exception (cx0000005) being thrown from `coreclr.dll`

    CoreCLR Version: 7.0.22.51805
    .NET Version: 7.0.0
    Description: The process was terminated due to an unhandled exception.
    Exception Info: exception code c0000005

We have seen this on `Windows 10 Enterprise` and on `Windows Server 2016`

### Code

    open System

    [<Struct>]
    type T = {
        A: DateTime
        B: int
        C: float
        D: byte }

    let data: T array = Array.zeroCreate 2_000_000_000

    GC.Collect()

    printfn "All OK"

### Project file

    <Project Sdk="Microsoft.NET.Sdk">

      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ServerGarbageCollection>true</ServerGarbageCollection>
      </PropertyGroup>

      <ItemGroup>
        <Compile Include="Program.fs" />
      </ItemGroup>

    </Project>

Run this with `dotnet run -c release`

### Changes that leads to program running OK
- Allocating with size `1_000_000_000`
- Changing the order of `B` and `C` in the struct

### Expected behavior

The program writes `All OK` to the console.

### Actual behavior

The program crashes and we see in the Event log that `The process was terminated due to an unhandled exception` with `exception code c0000005`

### Regression?

We never saw this on NET 6, but it appeared immediately efter we upgraded to NET 7.

### Known Workarounds

_No response_

#### .NET version
CoreCLR Version: 7.0.22.51805
.NET Version: 7.0.0

#### OS
Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎03/‎10/‎2020
OS build	19044.2251
Experience	Windows Feature Experience Pack 120.2212.4180.0

#### Architecture
x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by mrsharm**
Backport of https://github.com/dotnet/runtime/pull/80302 that fixes https://github.com/dotnet/runtime/issues/79486

## Customer Impact

The impact of this bug is constrained to users who have very large LOH segments where one segment survives more than 2GB - leading to a crash.

## Testing

We were able to test locally after consistently repro'ing the issue and proved that the fix took care of the bug. 

## Risk

Low risk change since it fixes the semantics of a type that was meant to be unsigned (from an int).

### CODE REVIEW

**Review by mangod9 — APPROVED** [review]

**Review by Maoni0 — CHANGES_REQUESTED** [review]
this actually doesn't look like it has most of the fix, for example, the part where it changes int to size_t for the survived field?

**Review by jeffschwMSFT — APPROVED** [review]
approved.  we will take for consideration in 7.0.x

**Review by Maoni0 — APPROVED** [review]

**Comment by mrsharm** [comment]
Failures don't look related to the changes.

**Review by PeterSolMS — APPROVED** [review]
Looks good to me!

**Comment by carlossanlop** [comment]
Approved by Tactics (7.0.3).
Signed off by area owners.
No OOB changes needed (native coreclr code).
All the CI failures are https://github.com/dotnet/runtime/issues/80428
Ready to merge. :shipit:

**Pull request merged**
