### PR TITLE
[wasm] current dedup breaks blazor template apps

### LINKED ISSUE #49676: [wasm] generic dedup breaks AOT blazor template apps.
On by default size optimizations without tests against the p0 targets are problematic.

```
 Assertion at /__w/1/s/src/mono/mono/mini/aot-runtime.c:2391, condition `<disabled>' not met
2386852@dotnet.6.0.0-preview.3.21164.8.js:1
_emscripten_asm_const_int@dotnet.6.0.0-preview.3.21164.8.js:1
wasm_trace_logger@dotnet.wasm:0x3fce91
eglib_log_adapter@dotnet.wasm:0x4b5dcd
monoeg_g_logstr@dotnet.wasm:0x42a9c5
monoeg_g_logv_nofree@dotnet.wasm:0x1c7e1a
monoeg_assertion_message@dotnet.wasm:0x2ea03
mono_assertion_message@dotnet.wasm:0x236bf
mono_assertion_message_disabled@dotnet.wasm:0x1eab2
load_container_amodule@dotnet.wasm:0x44df07
mono_aot_get_method@dotnet.wasm:0x7161f
mono_jit_compile_method_with_opt@dotnet.wasm:0x1d0fcd
mono_jit_compile_method_jit_only@dotnet.wasm:0x4e3ce
mono_jit_runtime_invoke@dotnet.wasm:0x439682
do_runtime_invoke@dotnet.wasm:0x12ca1a
mono_runtime_invoke_checked@dotnet.wasm:0x3073c
mono_runtime_invoke_handle_void@dotnet.wasm:0x443f5
create_exception_two_strings@dotnet.wasm:0x215443
mono_exception_from_name_two_strings_checked@dotnet.wasm:0x558ad
create_domain_objects@dotnet.wasm:0x4bf2ce
mono_runtime_init_checked@dotnet.wasm:0x430c5e
mini_init@dotnet.wasm:0x447ec0
mono_jit_init_version@dotnet.wasm:0x439b8e
mono_wasm_load_runtime@dotnet.wasm:0x42b6b7
Module._mono_wasm_load_runtime@dotnet.6.0.0-preview.3.21164.8.js:
```
Works with WasmDedup=false

### PR DESCRIPTION
**Pull request by lewing**
fixes https://github.com/dotnet/runtime/issues/49676 

Correctness before size.

### CODE REVIEW

**Comment by lewing** [comment]
cc @marek-safar @steveisok

**Comment by lewing** [comment]
cc @radical @pranavkm

**Review by vargaz — APPROVED** [review]

**Comment by vargaz** [comment]
Would be better to force set WasmDedup to false.

**Review by pranavkm — APPROVED** [review]
I guess?

**Comment by lewing** [comment]
sorry, bad patch.  I'm a little tired, will update

**Review by radical — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
