### PR TITLE
Move assignment rationalization to before forward substitution

### PR DESCRIPTION
**Pull request by SingleAccretion**
Expecting some sizeable improvements from the lack of interference with "LHS side effects".

### CODE REVIEW

**Comment by SingleAccretion** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=267800&view=ms.vss-build-web.run-extensions-tab). The summary for 64 bit got mysteriously truncated, [even though it was there](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/267800/logs/124).

@dotnet/jit-contrib

**Comment by SingleAccretion** [comment]
The 64 bit summary is still missing, for still unclear reasons. The one manually extracted from the log looks like this: https://gist.github.com/SingleAccretion/b6a593c1b7b888de3338aafff560fa36.

**Review by AndyAyersMS — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Thanks again. Looking forward to the next steps here.

**Comment by BruceForstall** [comment]
@SingleAccretion Do you expect we'll be able to get rid of `GTF_VAR_DEF`? Already it seems like there are a lot of `assert((tree->gtFlags & GTF_VAR_DEF) == 0);` in codegen that are obsolete.

**Comment by SingleAccretion** [comment]
> Do you expect we'll be able to get rid of `GTF_VAR_DEF`

@BruceForstall yes (along with `GTF_VAR_USEASG`). It is still used/useful currently because calls with return buffers and some lowering transforms use `LCL_ADDR` nodes as "definitions".

**Pull request merged**
