### PR TITLE
Add additional URI scheme fields (#35180)

### PR DESCRIPTION
**Pull request by poke**
This PR addresses #35180 and adds public fields for the following schemes: WS, WSS, SSH, Telnet, SFTP and FTPS.

This is the first draft which should add all required functionality. I still plan to add some tests to verify the parsing logic in `CheckKnownSchemes` but since this is my first contribution to the new mono repo, I am struggling a bit with the tooling to get everything building properly.

Until then, I hope I didn’t miss something that also needs to be added to add proper support for those protocols. I would also be happy to get some feedback on the UriParser flags since I wasn’t perfectly sure which flags would be appropriate for the new protocols.

### CODE REVIEW

**Comment by vcsjones** [comment]
The build errors are due to needing to add the new members to the `System.Runtime.cs` reference source.

```diff
diff --git a/src/libraries/System.Runtime/ref/System.Runtime.cs b/src/libraries/System.Runtime/ref/System.Runtime.cs
index e74776a76c0..7df659fb227 100644
--- a/src/libraries/System.Runtime/ref/System.Runtime.cs
+++ b/src/libraries/System.Runtime/ref/System.Runtime.cs
@@ -4629,6 +4629,7 @@ public partial class Uri : System.Runtime.Serialization.ISerializable
         public static readonly string SchemeDelimiter;
         public static readonly string UriSchemeFile;
         public static readonly string UriSchemeFtp;
+        public static readonly string UriSchemeFtps;
         public static readonly string UriSchemeGopher;
         public static readonly string UriSchemeHttp;
         public static readonly string UriSchemeHttps;
@@ -4637,6 +4638,11 @@ public partial class Uri : System.Runtime.Serialization.ISerializable
         public static readonly string UriSchemeNetTcp;
         public static readonly string UriSchemeNews;
         public static readonly string UriSchemeNntp;
+        public static readonly string UriSchemeSFtp;
+        public static readonly string UriSchemeSsh;
+        public static readonly string UriSchemeTelnet;
+        public static readonly string UriSchemeWs;
+        public static readonly string UriSchemeWss;
         protected Uri(System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext) { }
         public Uri(string uriString) { }
```

> I am struggling a bit with the tooling to get everything building properly.

Anything specific that we can help with?

**Comment by MihaZupan** [comment]
The initial change we had in mind for this API would be simply exposing the `static readonly` fields for these schemes (so lines 21-33 in this change).

We don't want to change the parsing logic as that could negatively impact backwards-compatibility (or if we do, we would require a significant amount of tests).

**Comment by poke** [comment]
@MihaZupan 
> The initial change we had in mind for this API would be simply exposing the static readonly fields

Oh! That de-complicates this a lot. Guess I was reading a bit too much into it, thinking that this can’t be seriously all that’s being asked for. I’m fine either way though. If adding parsing logic would have some possible drawbacks, then I’m happy to remove that again from the PR.

Should I keep the UriParser instances though, for a possible future expansion and to be able to reference the scheme names that way, or should the fields just be hardcoded completely?

@vcsjones 
> The build errors are due to needing to add the new members to the System.Runtime.cs reference source.

Thanks for that, I didn’t get to check that last night and just wanted to get something out first. Did you write the changes manually or is there some tool that generates that automatically from the public interface? I remember there being something similar in the AspNetCore repos that automated this.

> Anything specific that we can help with?

So far, I just had problems all over the place. After adding some more bits that I was missing, I was following the [library quick start workflow](https://github.com/dotnet/runtime/blob/c7242f00176cac72e79629ff515d0c517f685e7e/docs/workflow/building/libraries/README.md) and at least was able to build the runtime and the library from the console. I wasn’t able to launch the System.Private.Uri solution in Visual Studio though since that apparently didn’t pick up the self-compiled runtime and as such couldn’t open the projects (I don’t need a preview VS for this, do I? The [requirements](https://github.com/dotnet/runtime/blob/c7242f00176cac72e79629ff515d0c517f685e7e/docs/workflow/requirements/windows-requirements.md) just specify 16.6, so current stable should work).

Anyway, I’m not sure if I missed something there but I didn’t have the time today to retry it properly. I will have more time for this tomorrow though, so I will play around more and see if I get everything running properly, so that I can finish the PR then. I’ll let you know if I hit any other walls. I hope that this small PR will help me get the tooling running well enough so that I can see if I can find some more things to do in the future :blush:

(Btw. I’m not too happy that I need to compile C++ just to work on the .NET part of the repo; it would be cool if I could just use a pre-build SDK/runtime and just needed to compile those bits that I am working on)

**Comment by MihaZupan** [comment]
> Should I keep the UriParser instances though, for a possible future expansion and to be able to reference the scheme names that way, or should the fields just be hardcoded completely?

I would remove them and have the field values hardcoded (still keep them `static readonly`, not `const` though).

Uri has a way or registering custom parsers for unknown schemes. If we add an internal UriParser for SSH, any custom parsers for the scheme would stop being used. This is a design flaw in Uri and its extensibility that makes any such changes riskier.

**Review by stephentoub — APPROVED** [review]
Thanks.

**Pull request merged**
