### PR TITLE
[mono] Implement Rdm and Dp

### PR DESCRIPTION
**Pull request by imhameed**
See https://github.com/dotnet/runtime/issues/42322 and
https://github.com/dotnet/runtime/issues/42280.

Tested manually on an arm64 Linux VM running on an M1 Mac Mini. Does not
enable RDM or DP when AOT-compiling the associated runtime tests; our CI
hardware doesn't support these extensions yet.

### CODE REVIEW

**Comment by SamMonoRT** [comment]
@imhameed - I assume you will be enabling related tests as part of the follow up PR ?

**Comment by imhameed** [comment]
> @imhameed - I assume you will be enabling related tests as part of the follow up PR ?

The related tests are enabled as part of this PR.

**Review by vargaz — APPROVED** [review]

**Comment by imhameed** [comment]
The AOT cross-compilation failures are related and I am looking into them now.

**Comment by imhameed** [comment]
`llvm::sys::getHostCPUFeatures` doesn't probe for rdm or dotprod on arm64 Linux.

**Comment by imhameed** [comment]
https://github.com/dotnet/llvm-project/pull/103

**Comment by imhameed** [comment]
Well, I thought I had fixed this in https://github.com/dotnet/llvm-project/pull/103 and I thought that this had been made accessible to this repo via https://github.com/dotnet/runtime/commit/e64237dbc195c39a3d095653654f0b48c620dbd4, but the same problem (RDM and DP not detected by the runtime) is still occurring. I don't know what to do other than trial-and-error debugging against CI.

**Comment by SamMonoRT** [comment]
> Well, I thought I had fixed this in [dotnet/llvm-project#103](https://github.com/dotnet/llvm-project/pull/103) and I thought that this had been made accessible to this repo via [e64237d](https://github.com/dotnet/runtime/commit/e64237dbc195c39a3d095653654f0b48c620dbd4), but the same problem (RDM and DP not detected by the runtime) is still occurring. I don't know what to do other than trial-and-error debugging against CI, which has a multiple-hour turnaround time.

@steveisok @akoeplinger any suggestions here ?

**Comment by imhameed** [comment]
I suppose I could try running virtualized Linux on the M1 mini. There's also various Android devices (like the Vivo IQOO 5G and Samsung Galaxy S20 Ultra) that appear to support asimdrdm and asimddp although I have no idea how easy it is to run a normal Linux distribution on these.

**Comment by imhameed** [comment]
I'll be away from my desk until April 5th. The current plan is to pick this up again when I return, and to attempt to do local debugging on an M1, where it is apparently possible to run a virtualized copy of Linux.

**Comment by imhameed** [comment]
CoreCLR checks `AT_HWCAP` in the auxiliary vector in preference to parsing `/proc/cpuinfo`. The tokens that the [CoreCLR cpuinfo parser](https://github.com/dotnet/runtime/blob/24900f8333bd97ebb9b5837bbec10c28f02598d8/src/coreclr/pal/src/misc/jitsupport.cpp) scans for are not different from Mono's. I wonder what's going on.

**Comment by imhameed** [comment]
Spent some time setting up the M1 with an arm64 Linux VM. The tests all pass locally (with LLVM AOT + LLVM JIT and without) but they still crash on CI: https://gist.github.com/imhameed/dc1cf3ca935c1cd6d366bb1b721d0a76

**Comment by vargaz** [comment]
Does the CI machine support these instructions ?

**Comment by imhameed** [comment]
If I did https://github.com/dotnet/runtime/pull/52345 correctly, then yeah, I think so.

**Review by fanyang-mono — APPROVED** [review]

**Comment by imhameed** [comment]
> 
> 
> If I did #52345 correctly, then yeah, I think so.

I evidently did not do this correctly. Neither RDM nor DP are reported as supported by AT_HWCAP or /proc/cpuinfo: https://gist.github.com/imhameed/3095248a51d5ab5324cd06d59e8fb09b

**Pull request merged**
