### PR TITLE
Move serializable types for xml serialization generator tests to separate assembly

### LINKED ISSUE #43137: Invoking SGen creates a dependency on the repo local's shared framework
When using the repo local SDK (`$(DotNetTool)`) to invoke `dotnet-Microsoft.XmlSerializer.Generator` which dynamically (via reflection) loads the test assembly `Microsoft.XmlSerializer.Generator.Tests.dll` we create a dependency between the repo local shared framework and the test assembly.

This surfaces in the following error locally:
```
  .NET Xml Serialization Generation Utility, Version 6.0.0]
  Assembly 'C:\git\runtime2\artifacts\bin\Microsoft.XmlSerializer.Generator.Tests\net5.0-Debug\Microsoft.XmlSerializer.Generator.Tests.dll' does not contain any types that can be serialized using XmlSerializer.
C:\git\runtime2\src\libraries\Microsoft.XmlSerializer.Generator\tests\Microsoft.XmlSerializer.Generator.Tests.csproj(45,5): warning : Fail to generate C:\git\runtime2\artifacts\bin\Microsoft.XmlSerializer.Generator.Tests\net5.0-Debug\Microsoft.XmlSerializer.Generator.Tests.XmlSerializers.cs
C:\git\runtime2\src\libraries\Microsoft.XmlSerializer.Generator\tests\Microsoft.XmlSerializer.Generator.Tests.csproj(46,5): error MSB3030: Could not copy the file "C:\git\runtime2\artifacts\bin\Microsoft.XmlSerializer.Generator.Tests\net5.0-Debug\Microsoft.XmlSerializer.Generator.Tests.XmlSerializers.cs" because it was not found.
```

The exact cause is that the call to [`Type.GetTypes`](https://github.com/dotnet/runtime/blob/d6887d4aeec045aa4d708463abdfb6e071660dc8/src/libraries/Microsoft.XmlSerializer.Generator/src/Sgen.cs#L218) fails with an `ReflectionTypeLoadException` saying that references with assembly version X can't be resolved.

This likely has to do with us bumping the assembly version of our shared framework assemblies to 6.0.0 while the SDK still uses 5.0.0 shared framework assemblies.

There are couple of options:
1. Don't feed an assembly to sgen that compiles against the very latest. Use ie a `netcoreapp3.1` test helper assembly.
2. Don't invoke sgen during the test assembly's compilation at all.
3. Downgrade the test assembly (which is the input to sgen) to `netcoreapp3.1`. This is problematic as we would also need to downgrade `TestUtilities` and add support for testing non `$(NetCoreAppCurrent)` configurations (unreleated but we might want do this anyway at some point, similar to .NETFramework testing).
4. Upgrade to a 6.0 SDK. This would fix the issue temporarily but it would re-appear with 7.0.

This needs to be sorted out now as it already started to happen on my machine and because I thought it was related to one of my PRs I already lost multiple hours on that. Others will start noticing this soon as well.

cc @ericstj @Anipik @safern

### PR DESCRIPTION
**Pull request by safern**
Fixes: https://github.com/dotnet/runtime/issues/43137

cc: @GrabYourPitchforks

### CODE REVIEW

**Review by ericstj — APPROVED** [review]
Looks ok to me.  It might be helpful to note somewhere the "why" behind this separation.

**Comment by safern** [comment]
> Looks ok to me. It might be helpful to note somewhere the "why" behind this separation.

I'll add a comment to the SerializableAssembly csproj.

**Review by Anipik — APPROVED** [review]

**Comment by GrabYourPitchforks** [comment]
🥳

**Comment by safern** [comment]
Failures are unrelated.

**Review by ViktorHofer — COMMENTED** [review]
LGTM, thanks.

**Comment by ViktorHofer** [comment]
> Failures are unrelated and known.

Are you sure about the test failure?

`System.IO.Compression.GzipStreamUnitTests.Write_DataReadFromDesiredOffset(mode: AsyncAPM)` failed and I couldn't find a tracking issue for it and created one: https://github.com/dotnet/runtime/issues/44189

**Comment by stephentoub** [comment]
> I couldn't find a tracking issue for it 

https://github.com/dotnet/runtime/issues/44173

**Comment by ViktorHofer** [comment]
Cool. Why does Github search not list that issue? https://github.com/dotnet/runtime/search?q=Write_DataReadFromDesiredOffset&type=issues

**Comment by stephentoub** [comment]
GitHub search isn't great.  If you search for the full name, you'll find it:
https://github.com/dotnet/runtime/search?q=System.IO.Compression.GzipStreamUnitTests.Write_DataReadFromDesiredOffset&type=issues

**Comment by ViktorHofer** [comment]
Thanks

**Pull request merged**
