### PR TITLE
Move assignment rationalization to before the late helper expansion phases

### PR DESCRIPTION
**Pull request by SingleAccretion**
And adapt more common code to work with store nodes, notably, block morphing and costing. The latter had to be refactored quite substantially to avoid regressing TP.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=257963&view=results) - no code diffs as expected, TP regression is an artifact of how the overall work from #85494 is being sliced.

@dotnet/jit-contrib

**Comment by SingleAccretion** [comment]
Some failures and timeouts in libraries stress, but all look present in an [earlier run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258936&view=ms.vss-test-web.build-test-results-tab&runId=5059752&resultId=197314&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab) as well.

**Review by jakobbotsch — APPROVED** [review]
Looks good to me! I'll also run Fuzzlyn just to be safe.

**Comment by jakobbotsch** [comment]
Nevermind, I ran Fuzzlyn with the stress jobs, so looks like we are good to go :-)

**Pull request merged**
