### PR TITLE
Create dotnetcore.yml

### PR DESCRIPTION
**Pull request by Juspem1980**

### CODE REVIEW

**Comment by jkotas** [comment]
What is this yaml file for?

**Comment by ViktorHofer** [comment]
No idea what this is for?

**Comment by wjk** [comment]
@jkotas If committed, this file would enable [GitHub Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-github-actions), which is a kind of CI system that is built into GitHub.

@Juspem1980 I seriously doubt that this PR will ever be accepted, as .NET Core already has an extensive CI system already in place, built using Azure DevOps. Furthermore, your actions file is neither correct nor functional; to build this repo, run [`build.sh`](https://github.com/dotnet/runtime/blob/master/build.sh) instead. Hope this helps!

**Comment by jkotas** [comment]
@Juspem1980 As @wjk said, we are using Azure DevOps for this repository. We are not interested in switching to GitHub Actions.

**Pull request closed without merging**
