### PR TITLE
Revert "Fix malformed XML documentation (#78868)"

### PR DESCRIPTION
**Pull request by srwrr**
This reverts commit 942e34e0313b742cae9c311620577b083925c52d.

### CODE REVIEW

**Comment by srwrr** [comment]
78881

**Comment by srwrr** [comment]
commit

**Comment by srwrr** [comment]
#78881

**Comment by srwrr** [comment]
XML

**Comment by srwrr** [comment]
7

**Comment by tarekgh** [comment]
@srwrr what you are trying to do here?

**Comment by srwrr** [comment]
change

**Comment by srwrr** [comment]
1

**Comment by srwrr** [comment]
srwrr :reverse- 78868

**Comment by srwrr** [comment]
4596

**Pull request closed without merging**
