### PR TITLE
Change return type for MemberData tests to array

### PR DESCRIPTION
**Pull request by agocke**
The XUnit convention for MemberData is to return an enumerable of arrays. I'm not sure why this suddenly broke now.

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
> I'm not sure why this suddenly broke now.

We picked up a breaking xunit update in #108968 so my bet would be on that

**Comment by agocke** [comment]
OK, I think Michal's right -- I think the XUnit change did break this inadvertently.

What I didn't realize is that `TheoryData` is a special XUnit type that's special-cased for Theory operations in XUnit. That's not supported in the XUnitWrapper generator.

However, it also looks like TheoryData used to have an implicit conversion to `object[]`. No more. So my wrapping in an array is probably wrong. I probably want to change these members to return an object array instead of a TheoryData.

**Pull request merged**
