### PR TITLE
[ios] Add optimized property to the Native AOT sample app

### PR DESCRIPTION
**Pull request by kotlarmilos**
This PR adds optimized property to the sample app for AppleAppBuilder.

Fixes failing perf job https://dev.azure.com/dnceng/internal/_build/results?buildId=2243250&view=logs&j=3ed67216-8d06-57e4-e860-09ab51946aa1&t=ae27ed72-ed5a-5253-cbac-402a1b387446

### CODE REVIEW

**Comment by kotlarmilos** [comment]
Test job: https://dev.azure.com/dnceng/internal/_build/results?buildId=2243650&view=results

**Comment by ivanpovazan** [comment]
In the perf job failure, it says: `##[warning]No file or directory found - /Users/runner/work/1/s/src/mono/sample/iOS-NativeAOT/bin/ios-arm64/Bundle/HelloiOS/Release-iphoneos/HelloiOS.app` 

If `Optimized` is not set, does that mean the build failed, or the bundle path is different in that case?

**Comment by kotlarmilos** [comment]
> If `Optimized` is not set, does that mean the build failed, or the bundle path is different in that case?

The bundle path is different in that case. If the optimized is not set, the bundle is always created in `/Users/runner/work/1/s/src/mono/sample/iOS-NativeAOT/bin/ios-arm64/Bundle/HelloiOS/Debug-iphoneos/HelloiOS.app`. Later, it was searched in `##[warning]No file or directory found - /Users/runner/work/1/s/src/mono/sample/iOS-NativeAOT/bin/ios-arm64/Bundle/HelloiOS/Release-iphoneos/HelloiOS.app`.

**Review by ivanpovazan — APPROVED** [review]

**Pull request merged**
