### PR TITLE
Alternative fix of #60182

### PR DESCRIPTION
**Pull request by sakno**
Alternative way to fix #60182 without _try-catch_ block. Quick fix is available as separated PR #60224

### CODE REVIEW

**Comment by mangod9** [comment]
Hi @sakno, could you please rebase to main and once CI completes we could get this merged. Thx.

**Comment by sakno** [comment]
@mangod9 , done.

**Review by stephentoub — APPROVED** [review]
Thanks.

**Comment by danmoseley** [comment]
@BruceForstall formatting failed https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1459736/logs/217

I'll merge as this didn't touch the JIT code (should formatting only trigger if the JIT tree is changed?)

**Comment by BruceForstall** [comment]
@danmoseley It looks like the JIT formatting job runs anytime there's a change in coreclr, and that appears to include System.Private.CoreLib: https://dev.azure.com/dnceng/public/_build/results?buildId=1459736&view=logs&jobId=db5b9618-eefc-58e8-4554-fbce452d4dac&j=c8204876-824e-5bf9-8c45-a4628bfcec7d&t=c0cab5ad-9de6-5568-2ae4-6c24d2f3402f

@safern can probably explain this better.

Maybe we could add more granularity there to allow only running if there's a change in the JIT directory itself.

As for the failure, I did briefly break the job last week (fixed with https://github.com/dotnet/runtime/pull/61334), but it's not clear if this change was unlucky to pick up the break, or hit some other unknown error.

**Comment by danmoseley** [comment]
what folders should it trigger on exactly? then we can create a new group here
https://github.com/dotnet/runtime/blob/03e90a540cb2dfe5cab4086ea54ad5dd1f655749/eng/pipelines/common/evaluate-default-paths.yml#L11

and then use it here
https://github.com/dotnet/runtime/blob/03e90a540cb2dfe5cab4086ea54ad5dd1f655749/eng/pipelines/runtime.yml#L197

**Comment by BruceForstall** [comment]
@danmoseley Something like: https://github.com/dotnet/runtime/pull/61632? (can move discussion there)

**Pull request merged**
