### PR TITLE
remove duplicate Connect logic from TcpClient

### LINKED ISSUE #67879: discrepancy between TcpClient constructor and Connect method
`TcpClient` has public constructor that takes host name and port and when used, it connects underlying Socket. However the behavior is different when creating `TcpClient` and calling `Connect` method to the same host.

```c#
using System.Net.Sockets;

string host = "localhost";

var client1 = new TcpClient();
client1.Connect(host, 8080);
Console.WriteLine(client1.Client.LocalEndPoint);

var client2 = new TcpClient();
client2.ConnectAsync(host, 8080).GetAwaiter().GetResult();
Console.WriteLine(client2.Client.LocalEndPoint);

var client3 = new TcpClient(host, 8080);
Console.WriteLine(client3.Client.LocalEndPoint);
```

will produce something like 
```
[::ffff:127.0.0.1]:51920
[::ffff:127.0.0.1]:51922
127.0.0.1:51924
```

So in some cases use dual mode socket and sometimes we use socket for specific address family. `Connect` and `ConnectAsync` produce same result in example above (localhost resolves to single IPv4 address) but `ConnectAsync` use `Socket.ConnectAsync` while the synchronous implementation use implementation from `TcpClient` and that can produce different results. 

Also documentation (https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.-ctor?view=net-6.0#system-net-sockets-tcpclient-ctor(system-string-system-int32)) claims that IPv6 will be preferred when available but that is not what the code really does:

https://github.com/dotnet/runtime/blob/a074a2de15f38238a1344f4a621d1621680b2552/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs#L144-L150

While somebody may depend on this particular behavior, it seems like it would make sense to decease number of `Connect` implementations and overall behavior variations. 

related to #63162

### PR DESCRIPTION
**Pull request by wfurt**
defer the logic to underlying Socket. We already redirect ConnectAsync to Client.ConnectAsync.
+3, -85 lines of code.

fixes #67879

### CODE REVIEW

**Comment by rzikm** [comment]
This seems to break tests
```
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Net.Sockets.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Sockets.Tests (found 1244 of 1687 test cases)
  Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 2)
    System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_IPv6_AnyInterface_Succeeds [SKIP]
      IPv6 multicast environment not available
    System.Net.Sockets.Tests.TcpClientTest.Active_Roundtrips [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Net.Sockets.SocketException)
      Actual:   typeof(System.Net.Internals.SocketExceptionFactory+ExtendedSocketException): Name or service not known
      ---- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known
      Stack Trace:
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(365,0): at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Int64 startingTimestamp)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(346,0): at System.Net.Dns.GetHostAddressesCore(String hostName, AddressFamily addressFamily, Int64 startingTimestamp)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(196,0): at System.Net.Dns.GetHostAddresses(String hostNameOrAddress, AddressFamily family)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(170,0): at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(884,0): at System.Net.Sockets.Socket.Connect(String host, Int32 port)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs(129,0): at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TcpClientTest.cs(74,0): at System.Net.Sockets.Tests.TcpClientTest.<>c__DisplayClass6_0.<Active_Roundtrips>b__0()
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(365,0): at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, Int64 startingTimestamp)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(346,0): at System.Net.Dns.GetHostAddressesCore(String hostName, AddressFamily addressFamily, Int64 startingTimestamp)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(196,0): at System.Net.Dns.GetHostAddresses(String hostNameOrAddress, AddressFamily family)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(170,0): at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(884,0): at System.Net.Sockets.Socket.Connect(String host, Int32 port)
        /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs(129,0): at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TcpClientTest.cs(74,0): at System.Net.Sockets.Tests.TcpClientTest.<>c__DisplayClass6_0.<Active_Roundtrips>b__0()
```

**Review by ManickaP — APPROVED** [review]
Thanks.

**Comment by wfurt** [comment]
Test failures seems related. We should no leak `System.Net.Internals.SocketExceptionFactory+ExtendedSocketException` public IMHO.

**Comment by antonfirsov** [comment]
@wfurt there is no way to create a customized (thus more informative) exception message for `SocketException` without deriving a new type at the moment. See: https://github.com/dotnet/runtime/issues/37150#issuecomment-636098894.

IMO the tests using `Assert.Throws` instead of `Assert.ThrowsAny` are generally wrong unless the exception type is sealed.

**Review by Marusyk — APPROVED** [review]

**Pull request merged**
