### PR TITLE
Updating Vector<T> to support nint and nuint

### LINKED ISSUE #36160: Consider expanding `Vector<T>` to support `nint` and `nuint`
### Rationale

Today `Vector<T>` supports the following 10 primitive types: `byte`, `sbyte`, `short`, `ushort`, `int`, `uint`, `long`, `ulong`, `float`, and `double`.

C# 9 is introducing support for `nint` and `nuint` which are variable sized integers matching the bitness of the underlying platform. That is, they are 32-bits on 32-bit systems and 64-bits on 64-bit systems.

As such, it may be beneficial to expand `Vector<T>` to additionally support these types so we can get rid of the using aliases and support performing the cross-platform vector operations using these new primitive types.

### Proposal

Extend `Vector<T>` to support `nint` and `nuint` as valid primitive types. This will extend a number of existing generic functions which take a `Vector<T>` to also support taking the new types rather than throwing a `PlatformNotSupportedException`.

Additionally, the following non-generic APIs should be added for parity with the existing surface area:
```csharp
namespace System.Numerics
{
    public partial struct Vector<T>
    {
        public static explicit operator Vector<nint>(Vector<T> value);
        public static explicit operator Vector<nuint>(Vector<T> value);
    }

    public static partial class Vector
    {
        public static Vector<nint> AsVectorIntPtr<T>(Vector<T> value);
        public static Vector<nuint> AsVectorUIntPtr<T>(Vector<T> value);

        public static Vector<nint> Equals(Vector<nint> left, Vector<nint> right);
        public static Vector<nuint> Equals(Vector<nuint> left, Vector<nuint> right);

        public static Vector<nint> GreaterThan(Vector<nint> left, Vector<nint> right);
        public static Vector<nuint> GreaterThan(Vector<nuint> left, Vector<nuint> right);

        public static Vector<nint> GreaterThanOrEqual(Vector<nint> left, Vector<nint> right);
        public static Vector<nuint> GreaterThanOrEqual(Vector<nuint> left, Vector<nuint> right);

        public static Vector<nint> LessThan(Vector<nint> left, Vector<nint> right);
        public static Vector<nuint> LessThan(Vector<nuint> left, Vector<nuint> right);

        public static Vector<nint> LessThanOrEqual(Vector<nint> left, Vector<nint> right);
        public static Vector<nuint> LessThanOrEqual(Vector<nuint> left, Vector<nuint> right);
    }
}
```

### Other Considerations

For API names, we have a guideline that states to use the framework name rather than the language keyword name (e.g. `Int32` and `Int64` rather than `int` and `long`). However, the framework name for `nint` is `IntPtr` but the operators exposed and general use case for the two types is somewhat different, as such a name such as `NInt` and `NUInt` may be a better alternative. Whatever we choose, it should likely become the standard for `nint` moving forward.

The same request could be made for `System.Runtime.Intrinsics`, but the API bloat for this would be much larger and would need further consideration. It might be worthwhile to allow `nint`/`nuint` as valid `T` without exposing the additional overloads initially as that would at least unblock users from providing such APIs themselves.

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/36160

In order for this to work, `GenTreeJitIntrinsic` was updated to track the baseType as a `CorInfoType` rather than as a `var_types` (as discussed in https://github.com/dotnet/runtime/issues/36160#issuecomment-703855625). There is additionally a new `JitType2PreciseVarType` method which ensures that a `CorInfoType` is converted to a `var_types` in a way that preserves the sign (`JITtype2varType` will convert `CORINFO_TYPE_UINT` to `CORINFO_TYPE_INT` otherwise).

I ran `jit-diff --pmi` for `--frameworks`, `--benchmarks`, and `--tests` after the second commit to ensure there were no diffs due to the above changes. I then added the three latter commits supporting `Vector<nint>` and `Vector<nuint>`.

Edit: The vast majority of the PR is hardware intrinsic tests being added via the `NotSupported` template (so they are auto-generated, like most of the hwintrinsic tests).
Review of the PR can be simplified by just reviewing one of the generated tests since they all follow the same pattern.

Edit: This work was completed:
~~I am marking this as a draft until I can get some more tests up, including negative validating for `nint`/`nuint` on `Vector64/128/256<T>`.~~
~~I will also take a look at updating the couple places where we still have `using nuint_t = System.UInt64`, such as in `Utf16Utility.Validation.cs`~~

### CODE REVIEW

**Comment by tannergooding** [comment]
@fanyang-mono, could you assist with the mono failures here?

It looks like there are two kinds of failures:
1. Mono isn't correctly treating `Vector128<nint>.Zero` as unsupported
2. Mono is faulting in `src/mono/mono/mini/simd-intrinsics.c` due to an assertion that shouldn't be reached

Related, it looks like Mono has some hard-coded logic around `ThrowForUnsupportedVectorBaseType` and that is being renamed/split into two methods for this PR.

**Comment by fanyang-mono** [comment]
> @fanyang-mono, could you assist with the mono failures here?
> 
> It looks like there are two kinds of failures:
> 
> 1. Mono isn't correctly treating `Vector128<nint>.Zero` as unsupported
> 2. Mono is faulting in `src/mono/mono/mini/simd-intrinsics.c` due to an assertion that shouldn't be reached (looks like its not handling the `MONO_TYPE_` for `nint` and `nuint`).
> 
> Related, it looks like Mono has some hard-coded logic around `ThrowForUnsupportedVectorBaseType` (in `src/mono/mono/mini/intrinsics.c`) and that is being renamed/split into two methods for this PR.
> 
> The latter two issues look fairly straightforward to resolve, I'm just not familiar with what the correct `MONO_TYPE_` is for `nint` or `nuint`.
> The first issue I'm not sure where to start looking.

`nint` and `nuint` is currently not support by mono. @vargaz Zoltan, could you please provide a little more details, if there is any?

**Comment by tannergooding** [comment]
> nint and nuint is currently not support by mono

I'm not sure I understand this, they are just aliases for `System.IntPtr` and `System.UIntPtr` as far as the JIT type system is concerned?

**Comment by vargaz** [comment]
IntPtr/UIntPtr is MONO_TYPE_I/MONO_TYPE_U.

**Comment by fanyang-mono** [comment]
> > nint and nuint is currently not support by mono
> 
> I'm not sure I understand this, they are just aliases for `System.IntPtr` and `System.UIntPtr` as far as the JIT type system is concerned?

If that's the case, they should be mapped to `MONO_TYPE_I` and `MONO_TYPE_U`. Sorry that I misunderstood them with struct types.

**Comment by tannergooding** [comment]
I believe I've fixed the first issue:
> Mono isn't correctly treating Vector128<nint>.Zero as unsupported

and the third issue:
> it looks like Mono has some hard-coded logic around ThrowForUnsupportedVectorBaseType (in src/mono/mono/mini/intrinsics.c) and that is being renamed/split into two methods for this PR.

I've also fixed part of the second issue:
> Mono is faulting in src/mono/mono/mini/simd-intrinsics.c due to an assertion that shouldn't be reached (looks like its not handling the MONO_TYPE_ for nint and nuint).

The remainder of the second issue looks to be that a couple code paths will still assert (`type_to_expand_op`, `type_to_insert_op`, and `type_to_extract_var_op`) since `MONO_TYPE_I8` and `MONO_TYPE_U8` aren't handled.
It isn't clear if this is better handled by picking an existing op (e.g. `OP_EXPAND_I4` when targeting 32-bit and `OP_EXPAND_I8` when targeting 64-bit) or if it is better to add a new op (e.g. `OP_EXPAND_I`) and plumb the handling through.

**Comment by fanyang-mono** [comment]
> I believe I've fixed the first issue ([70432e5](https://github.com/dotnet/runtime/commit/70432e503281dfbdaa26a070fad9505a011d8dc4)):
> 
> > Mono isn't correctly treating Vector128.Zero as unsupported
> 
> and the third issue ([c3107e0](https://github.com/dotnet/runtime/commit/c3107e0c5d2735e0aa78818a02d626f4d3d3e832)):
> 
> > it looks like Mono has some hard-coded logic around ThrowForUnsupportedVectorBaseType (in src/mono/mono/mini/intrinsics.c) and that is being renamed/split into two methods for this PR.
> 
> I've also fixed part of the second issue (also [c3107e0](https://github.com/dotnet/runtime/commit/c3107e0c5d2735e0aa78818a02d626f4d3d3e832)):
> 
> > Mono is faulting in src/mono/mono/mini/simd-intrinsics.c due to an assertion that shouldn't be reached (looks like its not handling the MONO_TYPE_ for nint and nuint).
> 
> The remainder of the second issue looks to be that a couple code paths will still assert (`type_to_expand_op`, `type_to_insert_op`, and `type_to_extract_var_op`) since `MONO_TYPE_I8` and `MONO_TYPE_U8` aren't handled.
> It isn't clear if this is better handled by picking an existing op (e.g. `OP_EXPAND_I4` when targeting 32-bit and `OP_EXPAND_I8` when targeting 64-bit) or if it is better to add a new op (e.g. `OP_EXPAND_I`) and plumb the handling through.

Maybe something like this
```
case MONO_TYPE_I:
#if TARGET_SIZEOF_VOID_P == 8
<treat it the same as I8>
#else
<treat it as I4>
#endif
```

**Comment by tannergooding** [comment]
I believe the relevant mono paths are now updated to correctly handle `Vector<nint>` and `Vector<nuint>` and to block the same for `Vector64/128/256<T>` (at least until we take those to API review and hopefully unblock them as well). Hopefully CI passes now 😄

**Comment by tannergooding** [comment]
CC. @echesakovMSFT, @dotnet/jit-contrib for review

**Comment by lambdageek** [comment]
@vargaz could you review the mono commit https://github.com/dotnet/runtime/pull/50832/commits/8eb6fe9242e3797b82fe3c03c3e8401eddc9b550

**Comment by vargaz** [comment]
The mono changes look ok to me.

**Comment by tannergooding** [comment]
Rebased to resolve a conflict, believe I've also resolved the remaining ARM64 issue (it passed on my Windows box).

**Comment by tannergooding** [comment]
> The mono changes look ok to me.

@vargaz, I had to push another commit for Mono: https://github.com/dotnet/runtime/pull/50832/commits/0f4764d54b0c55ec45fffbf1187fc76b046ea432

A bit of the handling existed in `mini-amd64.c` and so was missed in my first pass, but caught by the tests.
I think I've gotten it all this time, but we'll see what CI says 😄

**Comment by tannergooding** [comment]
Everything is passing now except for two LLVM AOT scenarios. It isn't clear to me what's wrong here given that the regular Mono leg passed.

@vargaz or @fanyang-mono, could you provide some guidance on how to root cause the failure here?

**Comment by tannergooding** [comment]
Actually, I may have found it, there is a single line calling out an assert about halfway through the log:
* `Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/mini-llvm.c:580`

**Comment by tannergooding** [comment]
Only test failures are unrelated and due to https://github.com/dotnet/runtime/issues/51346

This should be ready for final review/merge.

**Comment by GrabYourPitchforks** [comment]
My small contribution to the review: commit https://github.com/dotnet/runtime/pull/50832/commits/57fc73d19c23650dfab277dda4a75fc69399e55d LGTM!

**Review by echesakov — APPROVED** [review]
LGTM
Thank you for your contribution, @tannergooding!

cc @dotnet/jit-contrib

**Pull request merged**
