### PR TITLE
Fix visibility of SslStreamCertificateContext fields

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by filipnavara** [comment]
Why was this not caught by the comparison to the ref assembly?

**Comment by stephentoub** [comment]
So apparently Quic is using these fields? Why have we not exposed public API for these if they're needed by such protocols?

**Comment by stephentoub** [comment]
We should reconsider. Four reasons:
1. These kinds of ref vs src tricks are harder to maintain. The fewer we have, the better.
2. Being public in the implementation means things like `dynamic` will by default allow access to them, making them supported anyway but without tooling to guarantee we're not breaking them.
3. If both SslStream and Quic need access, that's a strong indicator other protocols will as well.
4. There's currently no way to properly clean up after an SslStreamCertificateContext. It's not disposable and this state isn't exposed, which means everything created and stored is left for finalization when one is no longer used.

**Comment by stephentoub** [comment]
I will close this and open an issue for post-7.

**Comment by stephentoub** [comment]
https://github.com/dotnet/runtime/issues/72226

**Pull request closed without merging**
