### PR TITLE
Improve performance of IsRootScope check

### LINKED ISSUE #54351: Regressions in Microsoft.Extensions.DependencyInjection.GetService
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [a4b3772d1ada339220145843138d4c622134adeb](https://github.com/dotnet/runtime/commit/a4b3772d1ada339220145843138d4c622134adeb)
Compare | [43b1f2c165257faae4d6a4aa886b701b63d2d5c0](https://github.com/dotnet/runtime/commit/43b1f2c165257faae4d6a4aa886b701b63d2d5c0)
Diff | [Diff](https://github.com/dotnet/runtime/compare/a4b3772d1ada339220145843138d4c622134adeb...43b1f2c165257faae4d6a4aa886b701b63d2d5c0)

### Regressions in Microsoft.Extensions.DependencyInjection.GetService

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[ServiceScopeProvider - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/Microsoft.Extensions.DependencyInjection.GetService.ServiceScopeProvider.html>) | 21.97 ns | 38.43 ns | 1.75 | 0.26 | | |
[ServiceScope - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/Microsoft.Extensions.DependencyInjection.GetService.ServiceScope.html>) | 45.32 ns | 60.61 ns | 1.34 | 0.19 | | |

graph
graph
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_14_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/Microsoft.Extensions.DependencyInjection.GetService.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Microsoft.Extensions.DependencyInjection.GetService*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-84118154-61d2-4753-9aa5-7d91f360e7241157b74a2d847b3ac/b2fd9846-55bd-4cf9-860c-45355a1abd96.zip?sv=2019-07-07&se=2021-07-10T04%3A30%3A54Z&sr=c&sp=rl&sig=zoX4zvAgvxmYREIwvORUMSmoM9IaAq79bZTTDx%2F3zcM%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-258899a6-e611-44a0-bd82-487291cbd08f8f525ac29f34eb3a7/e3480ebb-9555-4c4f-837c-22604502eef3.zip?sv=2019-07-07&se=2021-07-10T17%3A43%3A16Z&sr=c&sp=rl&sig=ATa9Zh4HD3RRZ1FcpQLFrxsGseKxCvfqP7HIAKsYchg%3D>)

#### Microsoft.Extensions.DependencyInjection.GetService.ServiceScopeProvider

```log

```
#### Microsoft.Extensions.DependencyInjection.GetService.ServiceScope

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### PR DESCRIPTION
**Pull request by davidfowl**
- Stash a field instead of doing an equality comparison.

Fixes #54351

PS: I'm not sure how to run those performance tests.

### CODE REVIEW

**Review by pakrym — APPROVED** [review]
>Fixes #54351

Optimistic :)

**Comment by eerhardt** [comment]
> PS: I'm not sure how to run those performance tests.

There is a `Repro` section in the issue https://github.com/dotnet/runtime/issues/54351

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Microsoft.Extensions.DependencyInjection.GetService*'
```

**Comment by davidfowl** [comment]
python3 wtf. Is there an easy way to run on the same hardware? Also do I need to manually patch bits and run before and after?

**Comment by eerhardt** [comment]
> python3 wtf.

+💯 

> Is there an easy way to run on the same hardware? Also do I need to manually patch bits and run before and after?

cc @DrewScoggins @billwert

**Comment by billwert** [comment]
What's wrong with python? :)

If you have two runtimes you want to run back to back, I recommend running benchmarks_ci.py once to bootstrap everything and then you can follow the directions here:
https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md#preventing-regressions

Snapshot your baseline, then you can iterate as necessary with the after build.

**Comment by davidfowl** [comment]
OR I could just merge it.

**Comment by billwert** [comment]
Sure. We'll see the impact in the system soon enough if you do.

**Review by stephentoub — APPROVED** [review]

**Review by eerhardt — APPROVED** [review]

**Pull request merged**
