### PR TITLE
Add FrameworkName property to RuntimeLibrary

### PR DESCRIPTION
**Pull request by rseanhall**
This is the dotnet/runtime part of https://github.com/dotnet/sdk/issues/3339.

### CODE REVIEW

**Comment by rseanhall** [comment]
All of the build failures are infrastructure issues.

The `new-api-needs-documentation` label doesn't seem to apply in this case since the existing file didn't have any documentation to begin with.

**Comment by stephentoub** [comment]
@terrajobst, are these libraries going through the API review process?

**Comment by davidfowl** [comment]
They should

**Comment by stephentoub** [comment]
I agree ;-)

**Comment by rseanhall** [comment]
When can I expect a ruling on this? Based on the [api review process doc](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md), I wouldn't expect such a trivial change in a low impact API in the Microsoft.* namespace to require it.

> The rule of thumb is that we (dotnet/runtime) review every API that is being added to the System.* namespaces. In some cases, we also review APIs that are added to other namespaces, such as Microsoft.*. We mostly do this for high impact APIs, such as Roslyn, and when both the owner of the technology and we feel there is win-win for both sides if we review the APIs. However, we can't scale to review all APIs being added to .NET.

**Comment by rseanhall** [comment]
@vitek-karas Will you be responsible for this PR or does someone else own this area?

**Comment by vitek-karas** [comment]
I will be the owner from the runtime/hosting side. I'm trying to find out who will be the owner from the SDK side (I know it's relatively trivial change, I just don't want to force it through).

As noted above this should go through the API review process (should be easy though). To do that, please open a new issue in the runtime repo and describe the proposed API (including the "declaration" of the new API). I'll be the owner of it.

Regarding the PR itself:
As noted by the bot, please add XML-style comments to the new public API (I know the existing APIs don't have them, but we have to start somewhere). And please also add at least some test.

**Pull request closed without merging**
