### PR TITLE
[mono] Only ship runtime packs that are classified as mobile targets

### PR DESCRIPTION
**Pull request by steveisok**
In past .NET releases, we have shipped mono runtime packs for most of our support matrix. Starting in .NET 9, we will pull this back significantly and only ship runtime packs that are targeted at our 'mobile' platforms. This includes apple, android, wasm, and wasi targets.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Just for my own understanding, why do we still produce and upload them to the transport feed?

**Comment by steveisok** [comment]
> Just for my own understanding, why do we still produce and upload them to the transport feed?

If that's the best non-shipping feed, yes.

**Comment by lambdageek** [comment]
> Just for my own understanding, why do we still produce and upload them to the transport feed?

I don't know if the transport feed is the best place, but the general use case for the desktop Mono runtime packs are:

1. Allow runtime engineers to try out issues on Mono in console apps.  Often this is easier than debugging and validating fixes in mobile or wasm apps.
2. Give some sophisticated users an option to experiment with the mono hosting api on desktop platforms instead of jumping into mobile.  (For basically the same reason - it's easier to debug)

**Comment by lambdageek** [comment]
Related to https://github.com/dotnet/docs/issues/41366

**Comment by steveisok** [comment]
I manually ran an official build and it shows all of the desktop related mono runtime packs in the NonShipping folder.

**Comment by srxqds** [comment]
there are so many team embed mono with game engine。
I hope you keep the original plan. upload the mono desktop runtime package.

**Comment by steveisok** [comment]
This should land after P6 snaps

**Review by ViktorHofer — APPROVED** [review]

**Comment by steveisok** [comment]
One more trip around the CI world and this is ready to go.

**Pull request merged**
