### PR TITLE
Don't generate a nearly empty file

### LINKED ISSUE #76298: The interop source generators generate an empty file if unused.
On a blank .NET 7 app the `JSImport`, `JSExport` and `LibraryImport` generators always generate a file with only `/// <auto-generated/>` in it, even if we don't use the generators at all. Not a bug, but the regex and JSON generators don't generate any file by default.

### PR DESCRIPTION
**Pull request by jasonmalinowski**
When generators are running in the Visual Studio IDE, there's some overhead to having to manage a project that actually has generated output. It requires us to maintain two Roslyn Compilation objects, each which have their own symbol information. These interop generators are producing a file that's effectively empty (just an <auto-generated> comment on the top), and since they're installed in all .NET 7.0 applications, they are the reason we'll be having to manage more memory than before. Since the fix is simple enough to only generate the output if necessary, we should do so.

This also will help with telemetry, since we have telemetry that lets us tracking in the wild which generators are producing how many files; if we're always producing exactly one file we won't know how many sessions out there are actually using this generator in a meaningful way.

Fixes https://github.com/dotnet/runtime/issues/76298

### CODE REVIEW

**Review by AaronRobinsonMSFT — APPROVED** [review]
Thanks!

**Comment by AaronRobinsonMSFT** [comment]
@pavelsavara I think we might also need a fix in the JavaScript interop source generator, right?

**Comment by jasonmalinowski** [comment]
@AaronRobinsonMSFT: as far as I can tell, this is a common helper used for everything, but unless there's another copy somewhere else I don't know about?

**Comment by jasonmalinowski** [comment]
Marking as draft since I presume this broke some tests, but I don't know where they are yet.

**Review by jkoritzinsky — APPROVED** [review]
LGTM. I believe the JS generator uses the same extension methods to build out the generated sources, so this should cover the JS generators as well.

**Comment by jasonmalinowski** [comment]
@jkoritzinsky @AaronRobinsonMSFT I assumed this would have broken a test somewhere but I guess there's no negative test asserting no files are produced if nothing is needed. Where should one be added?

**Comment by AaronRobinsonMSFT** [comment]
> I guess there's no negative test asserting no files are produced if nothing is needed

Likely not. I think the most appropriate place would be after the following tests or integrated into them. These are confirming we compile even though `unsafe` isn't enabled on the project. You could add a bool that indicates if a file should be generated. @elinor-fung do you have any thoughts on location?

https://github.com/dotnet/runtime/blob/65561786b4c07d487bf9c0e7c4f16d6a6d6ad7ed/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/Compiles.cs#L644-L671

**Comment by elinor-fung** [comment]
I think integrating with the one Aaron pointed at makes sense. I would:
- Remove the case with `CodeSnippets.TrivialClassDeclarations` and allowUnsafe=true
  - This is already covered by `ValidateSnippets`
- Rename to something like `ValidateNoLibraryImport` and then always create the compilation with allowUnsafe=false and add a check that no source is generated.

**Comment by jasonmalinowski** [comment]
@jkoritzinsky @AaronRobinsonMSFT @elinor-fung Test added, so this would need a small re-review. Otherwise I think it's ready to go?

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Review by jkoritzinsky — APPROVED** [review]

**Review by elinor-fung — APPROVED** [review]

**Pull request merged**
