### PR TITLE
Add time prefix to (almost) all superpmi.py output

### PR DESCRIPTION
**Pull request by BruceForstall**
E.g.,
    [13:51:15] SuperPMI ASM diffs

Also, for collections, add a "Done" message with elapsed time
for every parallel item completion.

These two things will make it easier to see what is taking time
during SuperPMI runs, especially those run in the CI system.

### CODE REVIEW

**Comment by BruceForstall** [comment]
Here's an example default console output for a replay:
```
================ Logging to c:\spmi\superpmi.20.log
[13:51:00] Using JIT/EE Version from jiteeversionguid.h: bcc99ca6-5291-4cc0-a5d9-2758456053f3
[13:51:00] Found download cache directory "c:\spmi\mch\bcc99ca6-5291-4cc0-a5d9-2758456053f3.windows.x64" and --force_download not set; skipping download
[13:51:00] SuperPMI replay
[13:51:00] JIT Path: C:\gh\runtime3\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\clrjit.dll
[13:51:00] Using MCH files:
[13:51:00]   c:\spmi\mch\bcc99ca6-5291-4cc0-a5d9-2758456053f3.windows.x64\benchmarks.run.windows.x64.checked.mch
[13:51:00] Running SuperPMI replay of c:\spmi\mch\bcc99ca6-5291-4cc0-a5d9-2758456053f3.windows.x64\benchmarks.run.windows.x64.checked.mch
[13:51:09] Clean SuperPMI replay (26579 contexts processed)
[13:51:09] Replay summary:
[13:51:09]   All replays clean
```

**Comment by BruceForstall** [comment]
@kunalspathak @dotnet/jit-contrib PTAL

**Review by kunalspathak — CHANGES_REQUESTED** [review]
Was there an easy way to do this? Like inherit from `logging` and override `.log`  method?

**Comment by BruceForstall** [comment]
> Was there an easy way to do this? Like inherit from `logging` and override `.log` method?

No idea; I'm a very basic Python programmer.

**Comment by jakobbotsch** [comment]
Looks like you can create a formatter that includes timestamps and add it to our logging handlers, something like this:

```diff
diff --git a/src/coreclr/scripts/superpmi.py b/src/coreclr/scripts/superpmi.py
index 1034a7aacf9..7123ffbd756 100644
--- a/src/coreclr/scripts/superpmi.py
+++ b/src/coreclr/scripts/superpmi.py
@@ -2801,10 +2801,14 @@ def setup_args(args):
     logger = logging.getLogger()
     logger.setLevel(logging.DEBUG)
 
+    formatter = logging.Formatter("[%(asctime)s] %(message)s", datefmt="%H:%M:%S")
+
     stream_handler = logging.StreamHandler(sys.stdout)
     stream_handler.setLevel(logging.DEBUG)
+    stream_handler.setFormatter(formatter)
     logger.addHandler(stream_handler)
 
+
     # Parse the arguments
 
     coreclr_args = CoreclrArguments(args, require_built_core_root=False, require_built_product_dir=False, require_built_test_dir=False, default_build_type="Checked")
@@ -2873,6 +2877,7 @@ def setup_args(args):
             os.remove(log_file)
         file_handler = logging.FileHandler(log_file, encoding='utf8')
         file_handler.setLevel(logging.DEBUG)
+        file_handler.setFormatter(formatter)
         logger.addHandler(file_handler)
         logging.critical("================ Logging to %s", log_file)
```

**Comment by BruceForstall** [comment]
This was superseded by #66575

**Pull request closed without merging**
