### PR TITLE
If the base type is a sequential zero-sized type, treat a derived auto-layout type as starting from field offset 0.

### LINKED ISSUE #63106: ReadyToRun executable crashes at Marshal.StructureToPtr when trying to Marshal an Inherited class
### Description

The following sample code crashes when ReadyToRun is enabled in the Publish Settings.

```
using System.Runtime.InteropServices;

byte[] testString = (new MSG1()
{
    e = 20
}).GetBuffer();

Console.WriteLine(Convert.ToHexString(testString));
Console.ReadLine();

[StructLayout(LayoutKind.Sequential, Pack = 1)]
class IPacket
{    internal byte[] GetBuffer()
    {
        byte[] arr = new byte[GetSize()];
        IntPtr hglobal = Marshal.AllocHGlobal(GetSize());
        Marshal.StructureToPtr(this, hglobal, true);
        Marshal.Copy(hglobal, arr, 0, arr.Length);
        Marshal.FreeHGlobal(hglobal);

        return arr;
    }

    internal ushort GetSize()
    {
        return (ushort)Marshal.SizeOf(this);
    }
}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal class MSG_HEADER : IPacket
{
    internal MSG_HEADER() { }
    internal MSG_HEADER(uint _b, byte _c, byte _d)
    {
        b = _b;
        c = _c;
        d = _d;
        a = GetSize();
    }
    internal UInt32 a;
    internal UInt32 b;
    internal Byte c;
    internal Byte d;
}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
internal class MSG1 : IPacket
{
    internal MSG1()
    {
        MsgHeader = new MSG_HEADER
        {
            a = GetSize(),
            b = 0x1800,
            c = 0x01,
            d = 0xE0
        };
    }
    internal MSG_HEADER MsgHeader;
    internal byte e;
}
```

### Reproduction Steps

Use the above code and publish the executable with **Enable ReadyToRun compilation** enabled. The executable crashes with an Object Reference not set error.

### Expected behavior

The following is printed when ReadyToRun compilation is disabled and the program executes as intended.

`0B0000000018000001E014`

### Actual behavior

The executable crashes with the following error when ReadyToRun compilation is enabled in Publish Settings

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Runtime.InteropServices.Marshal.StructureToPtr(Object structure, IntPtr ptr, Boolean fDeleteOld)
   at System.Runtime.InteropServices.Marshal.StructureToPtr[T](T structure, IntPtr ptr, Boolean fDeleteOld)
```

### Regression?

Executable works fine on .NET Core Runtine 5.0.7 with ReadyToRun compilation enabled
Issue occurs on .NET Core 6.0 with ReadyToRun compilation enabled.

### Known Workarounds

Disabling ReadyToRun compilation fixes the executable

### Configuration

.NET Version: 6.0.101
Windows Server 2019
x64

Publish Settings:
Configuration: Release
Target Framework: net6.0
Target Runtime: win-x64
Produce Single File
Enable ReadyToRun compilation

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes https://github.com/dotnet/runtime/issues/63106 by making CoreCLR match the managed type system's layout rules for this case.

I decided to fix CoreCLR instead of changing Crossgen2 for a few reasons:

1. I think the behavior in Crossgen2 is more correct
2. The behavior in Crossgen2 is more performant (less memory consumption)
3. Changing the layout rules in Crossgen2 requires us to rev the R2R version in a backward-incompatible way, which breaks all R2R images. Changing the rules in CoreCLR doesn't cause any breaks as the CoreCLR layout rules are not persisted outside of the process.

~~Unless someone feels that this should be merged into .NET 7, I would think that we should wait until .NET 8 to merge this as layout-related changes are relatively higher risk.~~ Let's get this in for 7 based on feedback from Jan.

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
Changing this layout behavior is potentially tricky as this behavior has existed since .NET Framework. Doesn't mean we shouldn't do it, but it has been this way for a long time.


```csharp
[StructLayout(LayoutKind.Sequential)]
public class A
{
}

[StructLayout(LayoutKind.Sequential)]
public class B : A
{
    public object F;
}

[StructLayout(LayoutKind.Sequential)]
public class C : A
{
    public int F;
}
```

Viewing data in WinDBG via SOS.
```
0:000> !name2ee Hello_Desktop B
Module:      00007ff964cc4148
Assembly:    Hello_Desktop.exe
Token:       0000000002000005
MethodTable: 00007ff964cc5bf0
EEClass:     00007ff964cc2910
Name:        B
0:000> !DumpClass /d 00007ff964cc2910
Class Name:      B
mdToken:         0000000002000005
File:            ...\Hello_Desktop.exe
Parent Class:    00007ff964cc2880
Module:          00007ff964cc4148
Method Table:    00007ff964cc5bf0
Vtable Slots:    4
Total Method Slots:  5
Class Attributes:    100001  
Transparency:        Critical
NumInstanceFields:   1
NumStaticFields:     0
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ff9c0315dd8  4000007       10        System.Object  0 instance           F
0:000> !name2ee Hello_Desktop C
Module:      00007ff964cc4148
Assembly:    Hello_Desktop.exe
Token:       0000000002000006
MethodTable: 00007ff964cc5c80
EEClass:     00007ff964cc29a0
Name:        C
0:000> !DumpClass /d 00007ff964cc29a0
Class Name:      C
mdToken:         0000000002000006
File:            ...\Hello_Desktop.exe
Parent Class:    00007ff964cc2880
Module:          00007ff964cc4148
Method Table:    00007ff964cc5c80
Vtable Slots:    4
Total Method Slots:  5
Class Attributes:    100009  
Transparency:        Critical
NumInstanceFields:   1
NumStaticFields:     0
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ff9c03185a0  4000008        8         System.Int32  1 instance           F
```

**Comment by jkotas** [comment]
> Unless someone feels that this should be merged into .NET 7,

I think we should get this merged for .NET 7. Could you please add a test? The change looks good to me otherwise. Thanks.

**Comment by AaronRobinsonMSFT** [comment]
> > Unless someone feels that this should be merged into .NET 7,
> 
> I think we should get this merged for .NET 7. Could you please add a test? The change looks good to me otherwise. Thanks.

@jkotas Are you concerned at all with the impact of this change so close to a release? We've hit issues in the past with changing layout. I'm not entirely sure of the impact of the change.

I've not run the following, but would like to understand how this impacts the P/Invoke as well as a potential COM interop scenario.

```csharp
using System;
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Sequential)]
public class A
{
}
[StructLayout(LayoutKind.Sequential)]
public class B : A
{
    public object F;
}
[StructLayout(LayoutKind.Sequential)]
public class C : A
{
    public int F;
}

public class Program
{
    [DllImport("foo")]
    extern static A MyFunc(A a1, in A a2, ref A a3, out A a4);
    
    public A M(A a, out A o) {
        return MyFunc(a, in a, ref a, out o);
    }
}
```

**Comment by jkotas** [comment]
This is silent bad codegen bug that has impact beyond interop. The assessment in https://github.com/dotnet/runtime/issues/63106#issuecomment-1182601199 that it only shows up in `Marshal.StructureToPtr` is not quite right.

For example, `dotnet publish -c Release /p:PublishReadyToRun=true -r win-x64` the following and run it:
```
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

var a = new MyType();
a.Value = 42;

for (int i = 0; i < 1_000_000_000; i++)
{
    Test(a, i);
}
Console.WriteLine("PASSED");

[MethodImpl(MethodImplOptions.NoInlining)]
static void Test(MyType a, int i)
{
    if (a.Value != 42)
    {
        Console.WriteLine($"FAILED in iteration {i}");
        Environment.Exit(1);
    }
}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
class IFoo
{
}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
class MyType : IFoo
{
    public object o;
    public int Value;
}
```

Silent bad codegen bugs are P1. Yes, the fixes may have risk, but it is a risk that we have to take.

> I've not run the following, but would like to understand how this impacts the P/Invoke as well as a potential COM interop scenario.

I assume the unmanaged layout is not affected by this fix and there is no change in the unmanaged layout presented by interop. Is that correct?

**Comment by AaronRobinsonMSFT** [comment]
> I assume the unmanaged layout is not affected by this fix and there is no change in the unmanaged layout presented by interop. Is that correct?

If there is no impact on the unmanaged layout, which I'd like to understand why and confirm, I'd be less concerned.

**Comment by jkoritzinsky** [comment]
This fix does not change anything with unmanaged layout. The unmanaged layout is handled separately in `classlayoutinfo.cpp` (similarly to managed-sequential and managed-explicit). This fix only effects managed auto-layout.

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by AaronRobinsonMSFT** [comment]
I've confirmed on my side this doesn't impact any of the issues I was considering. Dubious there aren't others - especially given our previous issues touching layout.

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
The failure is due to the ARM64 machine not correctly picking up the job.

**Pull request merged**
