### PR TITLE
Make `ObjectFactory<T>` covariant

### LINKED ISSUE #101829: `ObjectFactory<T>` delegate should be covariant
Current workaround is to use the non-generic ObjectFactory and cast but that shouldn't be necessary.

```cs
ObjectFactory<A> a = ...;
ObjectFactory<B> b = ...;
ObjectFactory<Base> f = c ? a : b;
return f(...);
```

### API Proposal
```diff
namespace Microsoft.Extensions.DependencyInjection;
- public delegate T ObjectFactory<T>(IServiceProvider serviceProvider, object?[]? arguments);
+ public delegate T ObjectFactory<out T>(IServiceProvider serviceProvider, object?[]? arguments);
```

### PR DESCRIPTION
**Pull request by alrz**
Closes #101829

### CODE REVIEW

**Comment by lilinus** [comment]
I think you need to update `src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/ref/Microsoft.Extensions.DependencyInjection.Abstractions.cs` too?

**Comment by alrz** [comment]
> I think you need to update `src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/ref/Microsoft.Extensions.DependencyInjection.Abstractions.cs` too?

Yes, thanks! I did it manually for this change though, is there a tool to regenerate refs?

**Comment by huoyaoyuan** [comment]
The API proposal hasn't been reviewed yet. Since it's so trivial, it's a bit eager to open this PR.

**Comment by ericstj** [comment]
This is blocked on API review

**Review by stephentoub — APPROVED** [review]

**Review by steveharter — APPROVED** [review]

**Comment by steveharter** [comment]
/ba-g infrastructure issue (timeout) on linux-arm64 Debug Libraries_CheckedCoreCLR

**Pull request merged**
