### PR TITLE
Distinguish Debug and Checked builds in version resource

### PR DESCRIPTION
**Pull request by BruceForstall**
In the Win32 version resource, this changes the "Comment" field
from:
```
  Flavor=Checked
```
to:
```
  Flavor=Debug
```

Also, properly set `BUILDENV_DEBUG=1` for debug builds (only used in
exactly one place: gc.cpp).

### CODE REVIEW

**Comment by BruceForstall** [comment]
cc @Maoni0

**Comment by Maoni0** [comment]
I wonder this build_variant was used at some point but no longer because I don't see any usage of it in the diagnostics repo. @mikem8361 would you happen to know if build_variant was ever used in DAC?

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by mikem8361** [comment]
> I wonder this build_variant was used at some point but no longer because I don't see any usage of it in the diagnostics repo. @mikem8361 would you happen to know if build_variant was ever used in DAC?

The DAC should be just fine with this PR's change.

**Comment by BruceForstall** [comment]
@Maoni0 I assumed it was for GC developer use; maybe so you could verify in a crash dump what flavor was actually running.

**Comment by Maoni0** [comment]
@BruceForstall I have never used it... if I want to see if a build is retail/debug lmvm would do; maybe on linux? it still seems weird this would be a DAC thing since we don't do anything special for DAC wrt ret/dbg.

**Pull request merged**
