### PR TITLE
[wasm] Fix emsdk check

### PR DESCRIPTION
**Pull request by radekdoulik**
We use system python on osx too

### CODE REVIEW

**Comment by radekdoulik** [comment]
@mkhamoyan please check that it fixes the issue with the sample build for you

**Comment by mkhamoyan** [comment]
> @mkhamoyan please check that it fixes the issue with the sample build for you

@radekdoulik yes this fixed the issue, thanks!

**Review by mkhamoyan — APPROVED** [review]

**Review by maraf — APPROVED** [review]

**Comment by akoeplinger** [comment]
> We use system python on osx too

That's not what we intended, we should use our own python on osx and windows. Only Linux uses the system python.

**Comment by radekdoulik** [comment]
> > We use system python on osx too
> 
> That's not what we intended, we should use our own python on osx and windows. Only Linux uses the system python.

do you remember what is the reason?

I think it might have changed in https://github.com/dotnet/runtime/pull/100266

**Comment by akoeplinger** [comment]
MacOS doesn't ship with Python anymore, you probably just have it installed from homebrew like I do.

**Comment by radekdoulik** [comment]
Let's merge it for now. I have opened new issue to not forget about it. https://github.com/dotnet/runtime/issues/103120

**Pull request merged**
