### PR TITLE
[release/8.0-staging] Update alpine arm32 in release 8.0 CI

### PR DESCRIPTION
**Pull request by CarnaViire**
Contributes to https://github.com/dotnet/runtime/issues/91757

Alpine docker images were rebuilt [on Oct 26](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/923), which updated MsQuic to latest -- and brought in a regression for Alpine Arm32.

This PR rolls back to the previous image version that was used before Oct 26. This should stop the noise for release/8.0 that is https://github.com/dotnet/runtime/issues/91757. For main, I expect we would also update from 3.15 which is EOL to 3.16, so this PR is only for 8.0.

@carlossanlop this is test-infra-only change to reduce noise in CI.

Tested by running the tests in CI, see https://github.com/dotnet/runtime/pull/94609#issuecomment-1806588324

cc @wfurt @ManickaP @hoyosjs 

---

~~cc @wfurt - I took a look and alpine arm32 is only used in "checked runtime libraries test" combination. And in that case only 3.15 was used, which is EOL, so I believe we can just bump it to 3.17?~~

~~I was thinking and I'm not a fan of reverting to August's docker tag anymore... because it does not contain 10B fix (msquic 2.2.3)~~

### CODE REVIEW

**Comment by CarnaViire** [comment]
Ok, the problem is not with 3.15 specifically... [logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-94609-merge-afc9c6e61cdc4a40b4/System.Net.Quic.Functional.Tests/1/console.583851fa.log?helixlogtype=result) are full with the same error
```
System.Net.Quic.Tests.MsQuicCipherSuitesPolicyTests.SupportedCipher_Success [FAIL]
      System.Net.Quic.QuicException : The connection timed out from inactivity.
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(476,0): at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
```

So it is arm32 + updated msquic 😢 That means pinning the previous image tag seems to be the only fast option @wfurt

**Comment by CarnaViire** [comment]
Previous tag works, yay 😄😅

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-94609-merge-fd773b474a0e4ee380/System.Net.Quic.Functional.Tests/1/console.5165ff67.log?helixlogtype=result
```
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
MsQuic supported and using 'libmsquic.so 2.3.0.0 (b484c06f0867a8a1229219fa9bae352f60eede66)'.
  Discovered:  System.Net.Quic.Functional.Tests (found 124 of 134 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.UnsupportedPlatforms_ThrowsPlatformNotSupportedException [SKIP]
      Condition(s) not met: "IsQuicUnsupported"
  Finished:    System.Net.Quic.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Quic.Functional.Tests  Total: 358, Errors: 0, Failed: 0, Skipped: 1, Time: 144.686s
/root/helix/work/workitem/e
----- end Fri Nov 10 19:00:16 UTC 2023 ----- exit code 0 ----------------------------------------------------------
```

**Review by hoyosjs — COMMENTED** [review]
I'm ok if this is a temp fix, but it's better to keep containers patched. Is there any plan to re-enable the moving tag?

**Comment by wfurt** [comment]
test only change to stabilize CI @carlossanlop

**Comment by wfurt** [comment]
> I'm ok if this is a temp fix, but it's better to keep containers patched. Is there any plan to re-enable the moving tag?

This issue appears to be a regression in MsQuic. We should look into it and open a tracking issue in their repository. It's not something within our direct purview to address.

**Review by wfurt — APPROVED** [review]

**Pull request merged**
