### PR TITLE
System.Text.Json: TimeSpan support

### LINKED ISSUE #29932: JsonSerializer support for TimeSpan in 3.0?
EDIT @eiriktsarpalis: See https://github.com/dotnet/runtime/issues/29932#issuecomment-857574430 for the API proposal.

_Apologies if this is already answered somewhere else, but if it was my search abilities failed me._

I'm trying out the preview 6 of 3.0 with some existing production application code, and one of the issues that's come out of testing is that some of our existing objects we use in our API contracts use properties which are `TimeSpan` values, which are then represented as strings.

Is support for `TimeSpan` properties planned for 3.0 for the new System.Text.Json APIs?

If it's not going to be that gives us notice to do some refactoring ahead of September to change them to strings so we can use the new serializer, where as if it's planned but just not implemented yet then we just need to wait for a later preview to get this working.

Below is a minimal repro unit test that demonstrates the failure for `TimeSpan` to be handled compared to our existing JSON .NET code.

```csharp
using System;
using System.Text.Json.Serialization;
using Xunit;
using JsonConvert = Newtonsoft.Json.JsonConvert;
using JsonSerializer = System.Text.Json.Serialization.JsonSerializer;

namespace JsonSerializerTimeSpanNotSupportedException
{
    public static class Repro
    {
        [Fact]
        public static void Can_Deserialize_Object_With_SystemTextJson()
        {
            // Arrange
            string json = "{\"child\":{\"value\":\"00:10:00\"}}";

            // Act (fails in preview 6, throws: System.Text.Json.JsonException : The JSON value could not be converted to System.TimeSpan. Path: $.child.value | LineNumber: 0 | BytePositionInLine: 28.)
            var actual = JsonSerializer.Parse<Parent>(json, new JsonSerializerOptions() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });

            // Assert
            Assert.NotNull(actual);
            Assert.NotNull(actual.Child);
            Assert.Equal(TimeSpan.FromMinutes(10), actual.Child.Value);
        }

        [Fact]
        public static void Can_Deserialize_Object_With_NewtonsoftJson()
        {
            // Arrange
            string json = "{\"child\":{\"value\":\"00:10:00\"}}";

            var actual = JsonConvert.DeserializeObject<Parent>(json);

            // Assert
            Assert.NotNull(actual);
            Assert.NotNull(actual.Child);
            Assert.Equal(TimeSpan.FromMinutes(10), actual.Child.Value);
        }

        private sealed class Parent
        {
            public Child Child { get; set; }
        }

        private sealed class Child
        {
            public TimeSpan Value { get; set; }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by CodeBlanch**
Fixes #29932

## Description

Adds `TimeSpan` support to System.Text.Json (Utf8JsonReader, Utf8JsonWriter, JsonElement, JsonSerializer, & JsonNode/JsonValue).

Uses [Utf8Parser.TryParse](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.text.utf8parser.tryparse?view=net-5.0#System_Buffers_Text_Utf8Parser_TryParse_System_ReadOnlySpan_System_Byte__System_TimeSpan__System_Int32__System_Char_) & [Utf8Formatter.TryFormat](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.text.utf8formatter.tryformat?view=net-5.0#System_Buffers_Text_Utf8Formatter_TryFormat_System_TimeSpan_System_Span_System_Byte__System_Int32__System_Buffers_StandardFormat_) for the heavy lifting.

## Public API Changes

```csharp
    public readonly partial struct JsonElement
    {
       public System.TimeSpan GetTimeSpan() { throw null; }
       public bool TryGetTimeSpan(out System.TimeSpan value) { throw null; }
    }

    public ref partial struct Utf8JsonReader
    {
       public System.TimeSpan GetTimeSpan() { throw null; }
       public bool TryGetTimeSpan(out System.TimeSpan value) { throw null; }
    }

    public sealed partial class Utf8JsonWriter
    {
       public void WriteString(System.ReadOnlySpan<byte> utf8PropertyName, System.TimeSpan value) { }
       public void WriteString(System.ReadOnlySpan<char> propertyName, System.TimeSpan value) { }
       public void WriteString(string propertyName, System.TimeSpan value) { }
       public void WriteString(System.Text.Json.JsonEncodedText propertyName, System.TimeSpan value) { }
       public void WriteStringValue(System.TimeSpan value) { }
    }

    public abstract partial class JsonNode
    {
       public static explicit operator System.TimeSpan (System.Text.Json.Nodes.JsonNode value) { throw null; }
       public static explicit operator System.TimeSpan? (System.Text.Json.Nodes.JsonNode? value) { throw null; }
       public static implicit operator System.Text.Json.Nodes.JsonNode (System.TimeSpan value) { throw null; }
       public static implicit operator System.Text.Json.Nodes.JsonNode? (System.TimeSpan? value) { throw null; }
    }

    public abstract partial class JsonValue
    {
       public static System.Text.Json.Nodes.JsonValue Create(System.TimeSpan value, System.Text.Json.Nodes.JsonNodeOptions? options = default(System.Text.Json.Nodes.JsonNodeOptions?)) { throw null; }
       public static System.Text.Json.Nodes.JsonValue? Create(System.TimeSpan? value, System.Text.Json.Nodes.JsonNodeOptions? options = default(System.Text.Json.Nodes.JsonNodeOptions?)) { throw null; }
    }

    public static partial class JsonMetadataServices
    {
       public static System.Text.Json.Serialization.JsonConverter<System.TimeSpan> TimeSpanConverter { get { throw null; } }
    }
```

## Considerations

This is using the constant ("c") format. I think the general short format ("g") could compact things a bit, but not sure if that would round-trip with Newtonsoft and it is culture-sensitive.

/cc @layomia @eiriktsarpalis @JamesNK

### CODE REVIEW

**Comment by layomia** [comment]
@CodeBlanch thanks for this contribution!

All the new API needs to go through API review before we can merge. Please feel free to add the proposed API to this issue https://github.com/dotnet/runtime/issues/32965.

Most of the `TimeSpan` support requests I've seen are at the serializer level. I'd recommend splitting the PR into two separate PRs so that we can fast-track the support that most users are asking for.
- Add TimeSpan support to JsonSerializer (minimal API additions; the `JsonMetadataServices` changes can remain in this PR)
- Add TimeSpan support to the rest of System.Text.Json

**Comment by CodeBlanch** [comment]
@layomia Added to the issue. I'll look for the review decision and go from there. I intended to just do a converter but then those were calling into Utf8JsonReader/Writer so I did those updates. That left it in a state where most things had `TimeSpan` support, but not all things. Felt wrong to leave it like that so I made it all consistent 🤷

**Comment by eiriktsarpalis** [comment]
Echoing @layomia's comment I would recommend following the approach employed in #53539, and only put the `JsonMetadataServices` APIs for review. #32965 concerns adding `TimeSpan` support to `Utf8JsonWriter`/`Utf8JsonReader` and should be reviewed independently.

For now we really only need the following API:
```csharp
public static partial class JsonMetadataServices
{
    public static System.Text.Json.Serialization.JsonConverter<System.TimeSpan> TimeSpanConverter { get; }
}
```
I'll add it to #29932 and mark it ready for review.

**Comment by CodeBlanch** [comment]
OK to wait and see what is approved and then go from there? It won't take long to spin up new PRs, just trying to minimize re-work.

**Comment by eiriktsarpalis** [comment]
Yeah I think it would be a good idea to wait, just in case the API design gets revised.

**Comment by eiriktsarpalis** [comment]
Hey @CodeBlanch, FYI the API has just been approved as proposed.

**Comment by CodeBlanch** [comment]
Opened #54186

**Pull request closed without merging**
