### PR TITLE
[wasm] Bump sdk for workload testing to `7.0.100-preview.3.22151.18`

### PR DESCRIPTION
**Pull request by radical**
- also, updates WBT to target `net7.0`
- a follow up PR will add explicit `net6.0` tests

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Comment by radical** [comment]
The failing CoreCLR tests are https://github.com/dotnet/runtime/issues/66100 .

**Comment by radical** [comment]
All the test failures are https://github.com/dotnet/runtime/issues/66100 .

**Pull request merged**
