### PR TITLE
Add runtimeFlavor parameter to build-test-job.yml

### PR DESCRIPTION
**Pull request by trylek**
I have verified this fixes the jitstress pipeline.

### CODE REVIEW

**Comment by safern** [comment]
It seems like @naricc also put up a PR:https://github.com/dotnet/runtime/pull/35376 but didn't do the fix for `xplat-setup` to use `jobParameters`. So we either need to close his, or integrate the extra changes of this into his.

**Review by safern — APPROVED** [review]
THanks @trylek

**Review by naricc — APPROVED** [review]

**Comment by naricc** [comment]
Let's just take this one, its better than mine.

**Review by BruceForstall — APPROVED** [review]
LGTM

**Comment by BruceForstall** [comment]
@trylek The jitstress pipeline failed with lots of regressions, but at least the fundamental infra problem is fixed. Can this be merged?

**Pull request merged**
