### PR TITLE
Always keep global symbols on ApplePlatforms

### LINKED ISSUE #99503: Native AOT SOS debugging on MacOS isn't working
Even though `-exported_symbols_list "obj/Debug/net9.0/osx-x64/native/nativeaot.exports"` is being passed to clang and the nativeaot.exports file contains the _DotNetRuntimeDebugHeader export the symbol doesn't show up in the resulting binary.
See [log.txt](https://github.com/dotnet/runtime/files/14551588/log.txt)

### PR DESCRIPTION
**Pull request by am11**
Fixes #99503

### CODE REVIEW

**Comment by am11** [comment]
cc @mikem8361, this preserves the symbol in executable. Note that symbol was always there but stripped in a separate dSYM file `{binary}.dSYM/Contents/Resources/DWARF/{binary}`, now it is part of the binary. Size overhead in console app binary is 32 bytes and webapiaot app is 48 bytes.

**Review by mikem8361 — APPROVED** [review]

**Comment by mikem8361** [comment]
I've validated that the changes work for my native AOT test app.

**Comment by tommcdon** [comment]
> Should we backport this to 8.0?

Agreed.  @mikem8361 or @MichalStrehovsky would you be interested in starting the backport approval process?

**Comment by MichalStrehovsky** [comment]
> > Should we backport this to 8.0?
> 
> Agreed. @mikem8361 or @MichalStrehovsky would you be interested in starting the backport approval process?

I would appreciate if Mike could drive that. I haven't used anything made by Apple for years and I'm not able to reason about risks/impact of this PR (can't even try it as I don't have a Mac).

**Pull request merged**
