### PR TITLE
Enable outerloop helix legs on the "runtime-coreclr outerloop" pipeline.

### LINKED ISSUE #57007: CoreCLR Runtime Tests aren't running on outerloop-only queues
CoreCLR has some test queues defined to only run in outerloop scenarios. Specifically, there are some queues that we used to run tests only on during the official build back before repo consolidation.

This was conditioned by setting the `helixQueuesGroup:` property in the pipeline definitions for test jobs to `all`.

When we consolidated repositories, we removed the test runs on the internal pipelines, but we never moved these queues to be run on any public builds by default. This includes all CoreCLR runtime test runs on Windows 7 and Windows 8.1.

I've checked the Kusto data, and I have verified that we have not run any CoreCLR runtime tests on Windows 7 in dotnet/runtime, but we are running them on dotnet/coreclr.

cc: @AaronRobinsonMSFT

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Also, clean up the CoreCLR helix queue configuration since we don't run any tests in the internal build.

Fixes #57007

### CODE REVIEW

**Comment by ViktorHofer** [comment]
> Also, clean up the CoreCLR helix queue configuration since we don't run any tests in the internal build.

We eventually want to run tests on internal, i.e. for MSRC servicing. We haven't yet enabled that but it is tracked in https://github.com/dotnet/runtime/issues/47328 which needs to happen before we start servicing for 6.0.

I would just leave those in for now.

**Comment by jkoritzinsky** [comment]
I'd rather we add a new Helix queues setup template when we set up the internal queues unless we're planning on using the same pipeline definition (with the same platform matrix) for servicing as we do in main.

#47328 also tracks adding running libraries tests, which will also need a helix queues file update to support running on internal queues.

**Review by hoyosjs — APPROVED** [review]

**Comment by ViktorHofer** [comment]
> I'd rather we add a new Helix queues setup template when we set up the internal queues unless we're planning on using the same pipeline definition (with the same platform matrix) for servicing as we do in main.

That was my assumption. I don't think we would want to add another build definition entry point. Unrelated, we also have a tracking issue to merge runtime-official.yml and runtime.yml but that hasn't happened yet.

**Review by BruceForstall — APPROVED** [review]

**Comment by danmoseley** [comment]
@jkoritzinsky I'm going to close this as no progress. Feel free to reopen if you plan to revisit.

**Pull request closed without merging**
