### PR TITLE
Fix fgValueNumberArrIndexVal for wide reads

### LINKED ISSUE #57914: [JitStressWithRandomNumbers]  inliningVars.cmd fails
Example:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57900-merge-139159ef372d48dba3/JIT/1/console.27a10f26.log?sv=2019-07-07&se=2021-09-12T00%3A04%3A54Z&sr=c&sp=rl&sig=LVwZuDyZuoFiIx5A5sBz65LlH%2FmTz5q9NpOiuvvQaEU%3D

Repro steps (x86 windows):
```
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=100
JIT\opt\Inline\regression\bug584219\inliningVars\inliningVars.cmd
```

Failure log:
```
   3412
      78563412
      0
      1
      Expected: 100
      Actual: 101
```
the issue from a quality week JitStress experiment.

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/57914

Minimal repro:
```csharp
private static bool Test1()
{
    byte[] array = new byte[2];
    array[0] = 1;
    array[1] = 2;


    byte  a1 = Unsafe.ReadUnaligned<byte>(ref array[0]);
    short a2 = Unsafe.ReadUnaligned<short>(ref array[0]);
    array[1] = 42;
    short a3 = Unsafe.ReadUnaligned<short>(ref array[0]);

    return a1 == a2 && a1 == a3; // returns True currently
}
```
`a1`, `a2` and `a3` all have different values here with the same liberal VN resulting `Test1` to return true.

a1:
```
\--*  IND       byte   <l:$42, c:$401>
    \--*  ADD       byref  $300
        +--*  LCL_VAR   ref    V04 tmp1         u:2 $240
        \--*  CNS_INT   long   16 Fseq[#FirstElem] $181
```

a2:
```
\--*  IND       short  <l:$500, c:$5c1>
    \--*  LCL_VAR   byref  V07 tmp4         u:2 (last use) $300
```
(`$500` here is `$42` with NullRefExc)

a3:
```
\--*  IND       byte   <l:$42, c:$402>
    \--*  ADD       byref  $300
        +--*  LCL_VAR   ref    V04 tmp1         u:2 (last use) $240
        \--*  CNS_INT   long   16 Fseq[#FirstElem] $181
```

The fix is quite conservative - it treats such array element loads as "non-proper" and assign a unique VN.
SuperPMI diffs are empty.

PS: Doesn't reproduce on .NET 5.0

/cc @dotnet/jit-contrib

### CODE REVIEW

**Comment by SingleAccretion** [comment]
Heh, so I always wondered if it is possible to make VN use `CAST`s where it ought to use `BITCAST`s. Turns out it is very possible.
```C#
private static float Problem2()
{
    int[] array = new int[2];
    array[0] = 1;
    
    return Unsafe.ReadUnaligned<float>(ref Unsafe.As<int, byte>(ref array[0]));
}
```

```scala
  wholeElem $41 is MapSelect(hAtArrTypeAtArr($340), ind=$142).
    VNForCastOper(float) is $42
    VNForCast($41, $42) returns $440 {FltCns[1.000000]}
  selectedElem is $440 after applying selectors.
```
But that is a separate issue.

**Review by sandreenko — APPROVED** [review]
LGTM

**Review by briansull — APPROVED** [review]
Looks Good,

**Pull request merged**
