### PR TITLE
Use conditional statement instead of switch in System.Linq.Enumerable

### PR DESCRIPTION
**Pull request by alexcovington**
Small improvement by using a conditional instead of switch+goto.

Baseline is c4d5f6dff367ba1197

```
PS C:\Users\acovingt\source\repos\performance> py .\scripts\benchmarks_ci.py -c Release -f net6.0 --filter LinqBenchmark* --corerun C:\Users\acovingt\source\repos\runtime-master\artifacts\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe --bdn-artifacts D:\dotnet-micro-results\linq-use-conditional\base --bdn-arguments "--launchCount 5"
PS C:\Users\acovingt\source\repos\performance> py .\scripts\benchmarks_ci.py -c Release -f net6.0 --filter LinqBenchmark* --corerun C:\Users\acovingt\source\repos\runtime\artifacts\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe --bdn-artifacts D:\dotnet-micro-results\linq-use-conditional\diff --bdn-arguments "--launchCount 5"
PS C:\Users\acovingt\source\repos\performance\src\tools\ResultsComparer> dotnet run -- --base D:\dotnet-micro-results\linq-use-conditional\base\results\ --diff D:\dotnet-micro-results\linq-use-conditional\diff\results\ --threshold 3% --noise 5ns
summary:
better: 4, geomean: 1.057
total diff: 4

No Slower results for the provided threshold = 3% and noise filter = 5ns.

| Faster                            | base/diff | Base Median (ns) | Diff Median (ns) | Modality|
| --------------------------------- | ---------:| ----------------:| ----------------:| --------:|
| LinqBenchmarks.Where00LinqQueryX  |      1.07 |     562294600.00 |     523471200.00 |         |
| LinqBenchmarks.Where00LinqMethodX |      1.07 |     561668600.00 |     523850750.00 |         |
| LinqBenchmarks.Where01LinqMethodX |      1.04 |     239930400.00 |     230370400.00 |         |
| LinqBenchmarks.Where01LinqQueryX  |      1.04 |     239949600.00 |     230396200.00 |         |
```

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks.

Do you have an explanation for the improvements you're seeing?  Your results cite a 7% improvement in:
https://github.com/dotnet/performance/blob/d7dac8a7ca12a28d099192f8a901cf8e30361384/src/benchmarks/micro/runtime/Linq/Linq.cs#L125-L143
which is using Where on a `List<T>` and as such shouldn't be using this code path at all.  The change you've made is to WhereEnumerableIterator but a query on a `List<T>` should be using WhereListIterator.

FWIW, I also personally find the switch format easier to read.

**Comment by stephentoub** [comment]
> The change you've made is to WhereEnumerableIterator but a query on a List<T> should be using WhereListIterator.

Nevermind, somehow I missed in the diff you were modifying both.

**Comment by stephentoub** [comment]
Even with that, I still find the switch easier to read and understand.  If we're really trying to eek out a few percentage points improvement here and willing to sacrifice understandability to do so, I'd expect it'd be even better to restructure the code so that on the hot path of _state == 2 we're not having to check _state == 1 first (_state == 1 should happen at most once for the whole enumeration).

**Comment by alexcovington** [comment]
@stephentoub The `goto` statement within the switch is particularly expensive in this case according to PerfView:

linq-goto-samples

> I'd expect it'd be even better to restructure the code so that on the hot path of _state == 2 we're not having to check _state == 1 first (_state == 1 should happen at most once for the whole enumeration).

I see, I did not catch that `_state == 1` only happens once. I can try to move that check out of the hot path to reduce the number of checks.

**Comment by danmoseley** [comment]
PerfView can give you instruction level cost? I thought it was only method level. TIL.

**Comment by alexcovington** [comment]
> PerfView can give you instruction level cost? I thought it was only method level. TIL.

Well, I'm not sure exactly how accurate PerfView's cost reporting here (it's just stack sampling, right?), but the benchmark is clearly spending a lot of time just doing the `goto`.

**Comment by stephentoub** [comment]
> but the benchmark is clearly spending a lot of time just doing the goto

I don't believe that's being correctly attributed.

**Comment by EgorBo** [comment]
btw, related:


```csharp
static void Test(int s)
{
    if (s == 1)
    {
        Console.WriteLine("1");
        s = 2;
    }

    if (s == 2)
    {
        Console.WriteLine("2");
    }
}
```
is optimized by jit into:
```
static void Test(int s)
{
    if (s == 1)
    {
        Console.WriteLine("1");
        s = 2;
        goto jt;
    }

    if (s == 2)
    {
jt:
        Console.WriteLine("2");
    }
}
```
🙂 (aka Jump-Threading). Not sure it kicks in here as _state is a field (but maybe still kicks in becuase of struct)

**Comment by tannergooding** [comment]
> There's no "goto" in the generated IL

`goto case ...` in C# is generally used as `__fallthrough` is in C/C++. C# doesn't allow implicit fallthrough and `goto case ...`/`goto default` are the alternative.
* You can use `goto case ...` to jump to a non-sequential IL statement, but that's not "super" common

**Comment by alexcovington** [comment]
> Not sure it kicks in here as _state is a field (but maybe still kicks in becuase of struct)

Doesn't look like it kicks in for this case:

```assembly
G_M35240_IG04:
       nop      
       mov      rcx, gword ptr [rbp+10H]
       cmp      dword ptr [rcx+20], 1         ;; Check if _state == 1
       sete     cl
       movzx    rcx, cl
       mov      dword ptr [rbp-1CH], ecx
       cmp      dword ptr [rbp-1CH], 0
       je       SHORT G_M35240_IG05						   
       nop      			  
       mov      rcx, gword ptr [rbp+10H]        ;; _state == 1
       mov      gword ptr [rbp-88H], rcx
       mov      rcx, gword ptr [rbp+10H]
       mov      rcx, gword ptr [rcx+24]
       lea      rdx, [rbp-A0H]
       cmp      dword ptr [rcx], ecx
       call     System.Collections.Generic.List`1[__Canon][System.__Canon]:GetEnumerator():Enumerator[__Canon]:this
       mov      rdi, gword ptr [rbp-88H]
       add      rdi, 40
       lea      rsi, bword ptr [rbp-A0H]
       call     CORINFO_HELP_ASSIGN_BYREF
       call     CORINFO_HELP_ASSIGN_BYREF
       movsq    
       mov      rcx, gword ptr [rbp+10H]
       mov      dword ptr [rcx+20], 2         ;; Set _state = 2, fall through
       nop      							   
						;; bbWeight=1    PerfScore 26.25
G_M35240_IG05:
       mov      rcx, gword ptr [rbp+10H]
       cmp      dword ptr [rcx+20], 2         ;; Still checks if _state == 2
       sete     cl
       movzx    rcx, cl
       mov      dword ptr [rbp-20H], ecx
       cmp      dword ptr [rbp-20H], 0
       je       G_M35240_IG15
       nop      
       nop      
       jmp      G_M35240_IG11
						;; bbWeight=1    PerfScore 11.75
```

**Comment by alexcovington** [comment]
@stephentoub I've been testing a few different ways to move the `_state == 1` check out of the hot path, but so far nothing has been as performant as the current PR. Adding extra logic to handle the case requires either goto's or extra comparisons, which cancel out the benefits of the PR and result in on-par performance.

**Comment by eiriktsarpalis** [comment]
Running the Linq benchmarks locally using statistical testing does appear to show any improvements, with the exception of `Where00LinqQueryX`:

``` ini

BenchmarkDotNet=v0.13.1.1620-nightly, OS=Windows 10.0.22000
Intel Core i9-10900X CPU 3.70GHz, 1 CPU, 20 logical and 10 physical cores
.NET SDK=7.0.100-alpha.1.21568.2
  [Host]     : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT
  Job-LKYDPG : .NET 7.0.0 (42.42.42.42424), X64 RyuJIT
  Job-LWIZGT : .NET 7.0.0 (42.42.42.42424), X64 RyuJIT

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog  IterationTime=250.0000 ms  
MaxIterationCount=20  MinIterationCount=15  WarmupCount=1  

```
|                   Method |        Job |                                                                                                        Toolchain |      Mean |     Error |    StdDev |    Median |       Min |       Max | Ratio | MannWhitney(3%) | RatioSD |      Gen 0 |     Allocated |
|------------------------- |----------- |----------------------------------------------------------------------------------------------------------------- |----------:|----------:|----------:|----------:|----------:|----------:|------:|---------------- |--------:|-----------:|--------------:|
|        Where00LinqQueryX | Job-LKYDPG | main | 561.73 ms | 12.557 ms | 14.460 ms | 554.03 ms | 547.48 ms | 586.21 ms |  1.00 |            Base |    0.00 |  7000.0000 |  72,004,504 B |
|        Where00LinqQueryX | Job-LWIZGT |   pr | 527.72 ms |  4.169 ms |  3.695 ms | 529.74 ms | 521.63 ms | 532.13 ms |  0.94 |          Faster |    0.03 |  7000.0000 |  72,000,312 B |
|                          |            |                                                                                                                  |           |           |           |           |           |           |       |                 |         |            |               |
|       Where00LinqMethodX | Job-LKYDPG | main | 535.79 ms |  5.814 ms |  4.855 ms | 536.83 ms | 529.82 ms | 546.06 ms |  1.00 |            Base |    0.00 |  7000.0000 |  72,001,520 B |
|       Where00LinqMethodX | Job-LWIZGT |   pr | 539.44 ms |  4.872 ms |  4.557 ms | 538.89 ms | 533.17 ms | 546.55 ms |  1.01 |            Same |    0.01 |  7000.0000 |  72,000,528 B |
|                          |            |                                                                                                                  |           |           |           |           |           |           |       |                 |         |            |               |
|              Where00ForX | Job-LKYDPG | main | 159.74 ms |  2.964 ms |  2.628 ms | 159.06 ms | 156.89 ms | 164.29 ms |  1.00 |            Base |    0.00 | 17000.0000 | 176,000,480 B |
|              Where00ForX | Job-LWIZGT |   pr | 162.19 ms |  2.908 ms |  2.578 ms | 161.66 ms | 159.50 ms | 166.45 ms |  1.02 |            Same |    0.02 | 17000.0000 | 176,000,480 B |
|                          |            |                                                                                                                  |           |           |           |           |           |           |       |                 |         |            |               |
|        Where01LinqQueryX | Job-LKYDPG | main | 256.44 ms |  2.653 ms |  2.216 ms | 256.31 ms | 253.44 ms | 261.27 ms |  1.00 |            Base |    0.00 |  1000.0000 |  18,000,480 B |
|        Where01LinqQueryX | Job-LWIZGT |   pr | 249.80 ms |  2.897 ms |  2.710 ms | 249.05 ms | 246.81 ms | 254.10 ms |  0.97 |            Same |    0.02 |  1000.0000 |  18,001,888 B |
|                          |            |                                                                                                                  |           |           |           |           |           |           |       |                 |         |            |               |
|       Where01LinqMethodX | Job-LKYDPG | main | 256.68 ms |  3.933 ms |  3.285 ms | 255.95 ms | 252.58 ms | 262.06 ms |  1.00 |            Base |    0.00 |  1000.0000 |  18,000,480 B |
|       Where01LinqMethodX | Job-LWIZGT |   pr | 249.86 ms |  3.183 ms |  2.658 ms | 249.51 ms | 246.17 ms | 255.06 ms |  0.97 |            Same |    0.02 |  1000.0000 |  18,000,848 B |
|                          |            |                                                                                                                  |           |           |           |           |           |           |       |                 |         |            |               |
| Where01LinqMethodNestedX | Job-LKYDPG | main | 314.72 ms |  4.315 ms |  3.603 ms | 313.12 ms | 310.22 ms | 319.74 ms |  1.00 |            Base |    0.00 |  5000.0000 |  60,000,480 B |
| Where01LinqMethodNestedX | Job-LWIZGT |   pr | 308.07 ms |  2.600 ms |  2.305 ms | 308.49 ms | 304.74 ms | 313.40 ms |  0.98 |            Same |    0.01 |  5000.0000 |  60,001,520 B |
|                          |            |                                                                                                                  |           |           |           |           |           |           |       |                 |         |            |               |
|              Where01ForX | Job-LKYDPG | main | 179.58 ms |  2.253 ms |  2.108 ms | 179.11 ms | 176.51 ms | 183.15 ms |  1.00 |            Base |    0.00 |  2000.0000 |  22,000,480 B |
|              Where01ForX | Job-LWIZGT |   pr | 178.60 ms |  2.732 ms |  2.556 ms | 177.74 ms | 175.38 ms | 183.86 ms |  0.99 |            Same |    0.02 |  2000.0000 |  22,000,480 B |
|                          |            |                                                                                                                  |           |           |           |           |           |           |       |                 |         |            |               |
|       Count00LinqMethodX | Job-LKYDPG | main | 809.08 ms |  6.156 ms |  4.806 ms | 809.62 ms | 798.45 ms | 816.94 ms |  1.00 |            Base |    0.00 |  3000.0000 |  40,000,480 B |
|       Count00LinqMethodX | Job-LWIZGT |   pr | 814.45 ms |  5.190 ms |  4.052 ms | 814.03 ms | 808.01 ms | 820.86 ms |  1.01 |            Same |    0.01 |  3000.0000 |  40,000,480 B |
|                          |            |                                                                                                                  |           |           |           |           |           |           |       |                 |         |            |               |
|              Count00ForX | Job-LKYDPG | main | 105.83 ms |  1.968 ms |  1.933 ms | 105.06 ms | 104.10 ms | 111.69 ms |  1.00 |            Base |    0.00 |          - |         240 B |
|              Count00ForX | Job-LWIZGT |   pr | 105.37 ms |  1.388 ms |  1.298 ms | 104.78 ms | 104.06 ms | 107.88 ms |  1.00 |            Same |    0.02 |          - |         240 B |
|                          |            |                                                                                                                  |           |           |           |           |           |           |       |                 |         |            |               |
|        Order00LinqQueryX | Job-LKYDPG | main |  65.78 ms |  0.965 ms |  0.806 ms |  65.34 ms |  64.86 ms |  67.13 ms |  1.00 |            Base |    0.00 |  5750.0000 |  58,600,120 B |
|        Order00LinqQueryX | Job-LWIZGT |   pr |  65.92 ms |  1.226 ms |  1.204 ms |  65.52 ms |  64.77 ms |  69.36 ms |  1.00 |            Same |    0.02 |  5750.0000 |  58,600,120 B |
|                          |            |                                                                                                                  |           |           |           |           |           |           |       |                 |         |            |               |
|       Order00LinqMethodX | Job-LKYDPG | main |  66.20 ms |  1.117 ms |  1.045 ms |  66.17 ms |  64.92 ms |  68.17 ms |  1.00 |            Base |    0.00 |  5750.0000 |  58,600,120 B |
|       Order00LinqMethodX | Job-LWIZGT |   pr |  65.22 ms |  0.720 ms |  0.638 ms |  65.02 ms |  64.59 ms |  66.78 ms |  0.99 |            Same |    0.02 |  5750.0000 |  58,600,120 B |
|                          |            |                                                                                                                  |           |           |           |           |           |           |       |                 |         |            |               |
|           Order00ManualX | Job-LKYDPG | main |  99.39 ms |  0.655 ms |  0.512 ms |  99.47 ms |  98.35 ms | 100.14 ms |  1.00 |            Base |    0.00 |  1000.0000 |  16,000,480 B |
|           Order00ManualX | Job-LWIZGT |   pr | 100.21 ms |  1.884 ms |  1.670 ms |  99.44 ms |  98.20 ms | 103.55 ms |  1.01 |            Same |    0.02 |  1000.0000 |  16,000,480 B |

I feel like this might optimizing for the current implementation of the JIT, and breaks convention with how all the other enumerators are implemented, for example

https://github.com/dotnet/runtime/blob/c79e093b42abe132f66838ea4a5412812c0f62dc/src/libraries/System.Linq/src/System/Linq/SelectMany.cs#L166

https://github.com/dotnet/runtime/blob/c79e093b42abe132f66838ea4a5412812c0f62dc/src/libraries/System.Linq/src/System/Linq/AppendPrepend.cs#L195

https://github.com/dotnet/runtime/blob/c79e093b42abe132f66838ea4a5412812c0f62dc/src/libraries/System.Linq/src/System/Linq/Partition.SpeedOpt.cs#L378

**Comment by stephentoub** [comment]
> I feel like this might optimizing for the current implementation of the JIT, and breaks convention with how all the other enumerators are implemented

Yeah.  I appreciate the work that's gone into this, but without a compelling explanation for why this is an enduring improvement, my preference is to keep the implementation consistent with the others (and, at least personally, I find the switch easier to read and reason about, but that may just be me).

**Comment by alexcovington** [comment]
@stephentoub No worries, I think we can just close this PR since the exact reason for the improvement isn't obvious, like you mentioned.

Thanks for the review, everyone!

**Comment by eiriktsarpalis** [comment]
Thanks @alexcovington!

**Pull request closed without merging**
