### PR TITLE
Disable AVX for Sve leg

### PR DESCRIPTION
**Pull request by kunalspathak**
This should fix the failures seen on sve leg in https://dev.azure.com/dnceng-public/public/_build/results?buildId=746417&view=ms.vss-test-web.build-test-results-tab.

### CODE REVIEW

**Comment by kunalspathak** [comment]
passing build - https://dev.azure.com/dnceng-public/public/_build/results?buildId=747997&view=results

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib @tannergooding PTAL

**Review by tannergooding — APPROVED** [review]

**Pull request merged**
