### PR TITLE
Update "LICENSE.txt" so that it's recognized as MIT

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
This PR replicates PowerShell/PowerShell#12729 and PowerShell/PowerShell#12190 (it also removes the `All Rights Reserved`).

### CODE REVIEW

**Comment by stephentoub** [comment]
@richlander, @terrajobst, can you please review this? Thanks.

**Comment by ViktorHofer** [comment]
The reason why our repository's license isn't recongnized as MIT is because of the PATENTS.TXT file which lists conflicting licenses. This change won't help with that.

**Comment by teo-tsirpanis** [comment]
I see. At least this PR removes the `All rights reserved`.

**Review by richlander — APPROVED** [review]

**Comment by richlander** [comment]
This looks good. 

This updated license should be viewed as the canonical license for the .NET project.

**Pull request merged**
