### PR TITLE
Disable publishing CoreCLR product binaries on GCC leg

### PR DESCRIPTION
**Pull request by safern**
This fixes the segmentation fault failures on Linux x64 checked runs.

cc: @jkotas @am11 @AndyAyersMS

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Review by jashook — APPROVED** [review]

**Comment by am11** [comment]
Thanks @safern! 
wondering why wasn't it get caught in the original PR and many build runs since. 🤔

**Comment by safern** [comment]
> wondering why wasn't it get caught in the original PR and many build runs since. 🤔

It is a timing issue. It depends on which build finishes and uploads the binaries first.

**Comment by AndyAyersMS** [comment]
In my failing PR run the GCC build published about 2 minutes after the Clang build, so the GCC built assets were the ones that propagated. Failure mode was pretty cryptic.

As an aside, I wonder if this is something that could/should have produced an error message instead of a segv, presumably it was a native library load failure of some sort?

Seems like the same thing maybe could happen with the product build? Does the fix above stop all publishing from the GCC builds?
```
;; CLANG
2020-03-13T00:47:50.1915549Z Upload '/datadisks/disk1/workspace/_work/1/a/CoreCLRProduct_Linux_x64_checked.tar.gz' to file container: '#/3640272/CoreCLRProduct_Linux_x64_checked'

2020-03-13T00:47:50.6261487Z Associated artifact 9329041 with build 557918

;; GCC
2020-03-13T00:50:30.1347541Z Upload '/datadisks/disk1/workspace/_work/1/a/CoreCLRProduct_Linux_x64_checked.tar.gz' to file container: '#/3640272/CoreCLRProduct_Linux_x64_checked'

2020-03-13T00:50:32.0552290Z Associated artifact 9329041 with build 557918
```

**Comment by safern** [comment]
> Seems like the same thing maybe could happen with the product build? Does the fix above stop all publishing from the GCC builds?

The product build is defined in a separate yml which doesn't do any GCC builds, so it doesn't hit this issue. However, if it were the case it would fix it. If at some point we want for some reason to publish GCC assets, we should be able to just change the artifacts name so that they don't clash.

**Pull request merged**
