### PR TITLE
Fix a potential shutdown hang with `Environment.Exit()` on Windows depending on timing with GCs

### LINKED ISSUE #84006: Test failure baseservices/threading/regressions/2164/foreground-shutdown/foreground-shutdown.cmd
Run: [runtime-coreclr gcstress-extra 20230326.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=217853&view=ms.vss-test-web.build-test-results-tab&runId=4073620&resultId=347720&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked gcstress0xc_jitstress1 @ Windows.11.Arm64.Open
- baseservices/threading/regressions/2164/foreground-shutdown/foreground-shutdown.cmd

coreclr windows x64 Checked gcstress0xc_zapdisable @ Windows.10.Amd64.Open
- baseservices/threading/regressions/2164/foreground-shutdown/foreground-shutdown.cmd

coreclr windows x64 Checked gcstress0xc_jitstress1 @ Windows.10.Amd64.Open
- baseservices/threading/regressions/2164/foreground-shutdown/foreground-shutdown.cmd

coreclr windows x86 Checked gcstress0xc_tailcallstress @ Windows.10.Amd64.Open
- baseservices/threading/regressions/2164/foreground-shutdown/foreground-shutdown.cmd

coreclr windows arm64 Checked gcstress0xc_jitstress2 @ Windows.11.Arm64.Open
- baseservices/threading/regressions/2164/foreground-shutdown/foreground-shutdown.cmd

coreclr windows x86 Checked gcstress0xc_jitstress1 @ Windows.10.Amd64.Open
- baseservices/threading/regressions/2164/foreground-shutdown/foreground-shutdown.cmd

coreclr windows x86 Checked gcstress0xc_zapdisable @ Windows.10.Amd64.Open
- baseservices/threading/regressions/2164/foreground-shutdown/foreground-shutdown.cmd

coreclr windows x86 Checked gcstress0xc_jitminopts_heapverify1 @ Windows.10.Amd64.Open
- baseservices/threading/regressions/2164/foreground-shutdown/foreground-shutdown.cmd
```
**Error message:**
```
cmdLine:C:hwA05C0952wACDA0907easeservices	hreading	hreading_group1../regressions/2164/foreground-shutdown/foreground-shutdown.cmd Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 3/26/2023 11:30:07 PM, end: 3/27/2023 1:00:07 AM)

Return code:      -100
Raw output file:      C:hwA05C0952wACDA0907uploads
egressions2164oreground-shutdownoutput.txt
Raw output:
BEGIN EXECUTION
"C:hwA05C0952pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  foreground-shutdown.dll

cmdLine:C:hwA05C0952wACDA0907easeservices	hreading	hreading_group1../regressions/2164/foreground-shutdown/foreground-shutdown.cmd Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 3/26/2023 11:30:07 PM, end: 3/27/2023 1:00:07 AM)
Test Harness Exitcode is : -100
To run the test:
Set up CORE_ROOT and run.

C:hwA05C0952wACDA0907easeservices	hreading	hreading_group1../regressions/2164/foreground-shutdown/foreground-shutdown.cmd
Expected: True
Actual:   False


Stack trace
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String basePath, String assemblyPath)
   at Program.<<Main>$>g__TestExecutor2|0_1(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by kouvel**
- On Windows when a thread calls `ExitProcess`, the `TlsDestructionMonitor` for the thread appears to be destructed after all other threads in the process are torn down. It's possible for a GC to be in progress during that time, and the thread cleanup code in `TlsDestructionMonitor` tries to enter cooperative GC mode to fix the frame pointer, leading to a hang. Fixed by deactivating the `TlsDestructionMonitor` for the thread before calling `ExitProcess`.
  - I believe it wouldn't have been an issue prior to https://github.com/dotnet/runtime/pull/43423 and https://github.com/dotnet/runtime/pull/65358, since the thread cleanup code was done on `DLL_THREAD_DETACH`, which is not raised by `ExitProcess`.
  - On Linux, upon a call to `exit` the `TlsDestructionMonitor` for the thread appears to be destructed while other threads are still running, so it is eventually able to enter cooperative GC mode. It seems the cleanup is unnecessary in this case anyway, and the behavior is similar to before, so I didn't special-case the fix for Windows.
- Also disabled the relevant test due to a different issue (https://github.com/dotnet/runtime/issues/83658) occurring in the same test on multiple platforms/architectures, which is not understood yet.

Fixes https://github.com/dotnet/runtime/issues/84006

### CODE REVIEW

**Review by mangod9 — APPROVED** [review]
Assume this isnt a regression and the issue started showing up now due to timing changes?

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by jkotas** [comment]
Can this change introduce deadlocks or data corruptions? Are there places in the runtime where suppressing unregistration of the exiting thread is going to lead to orphaned pointer?

**Comment by jkotas** [comment]
For example, what is going to happen if a thread exits right after `DeactivateTlsDestructionMonitor` and then another thread triggers GC. The suspend for GC is going to hang or crash - it will try to wait the thread that exited to get to the safe spot, but that is not ever going to happen since the thread is gone.

**Comment by kouvel** [comment]
> For example, what is going to happen if a thread exits right after `DeactivateTlsDestructionMonitor` and then another thread triggers GC. The suspend for GC is going to hang or crash - it will try to wait the thread that exited to get to the safe spot, but that is not ever going to happen since the thread is gone.

Is it possible for a thread to exit right after `DeactivateTlsDestructionMonitor` but before `ExitProcess` starts tearing down the threads?

My rationale was that `DeactivateTlsDestructionMonitor` is called just before the thread (T1) calls `ExitProcess`, both in preemptive mode. If a different thread T2 triggers GC in-between T1 deactivating and the call to ExitProcess, T2 shouldn't have to wait for T1 since T1 is in preemptive mode.

Also I was thinking the pointers relevant to T1 would continue to be valid (like for walking the stack) until the OS starts tearing down all threads. If it's possible that the memory behind those pointers would be deallocated while another thread is still running, then it would be problematic, but the same issue would have existed back when thread cleanup was done upon `DLL_THREAD_DETACH` since that's not raised for `ExitProcess` and the thread calling `ExitProcess` would not have done any cleanup. On Windows anyway, the thread that called `ExitProcess` appears to be the last thread that gets torn down.

**Comment by jkotas** [comment]
A different example: `ExitProcess` can be called by 3rd party component. This is going to the common situation when CoreCLR is hosted and does not own "Main". Is it going to hit the same problem?

**Comment by danmoseley** [comment]
Just curious, why does any code at all run on Environment.Exit? What is expected to happen other than rapid process termination?

**Comment by jkotas** [comment]
>Just curious, why does any code at all run on Environment.Exit?

Environment.Exit is graceful process termination. It runs both managed (`AppDomain.ExitProcess`) and unmanaged (`atexit`, `DLL_PROCESS_DETATCH`) exit handlers.

**Comment by kouvel** [comment]
> A different example: ExitProcess can be called by 3rd party component. This is going to the common situation when CoreCLR is hosted and does not own "Main". Is it going to hit the same problem?

I think returning from the main function would be ok, even if a 3rd party component owns main, because there wouldn't be any managed frames on the stack, and the frame pointer of that thread would be the top frame.

If a thread that has managed frames on the stack calls `ExitProcess` directly, bypassing `Environment.Exit`, then it could run into the same type of hang. I'm not sure at the moment what would be a good way of fixing that. Fixing the frame pointer only in `DllMain` I expect would resolve the issue when coreclr is loaded as a DLL, but I'm not sure about statically-linked cases.

> Just curious, why does any code at all run on Environment.Exit? What is expected to happen other than rapid process termination?

I'm not sure about why C++ `thread_local` objects are destructed for a thread that calls `ExitProcess` or `exit`. The `thread_local` objects for other threads are not destructed, so in that sense it's not a completely graceful exit anyway.

**Comment by jkotas** [comment]
Note that this comment https://github.com/dotnet/runtime/blob/773c1807b73abfa1204b8e260ffd20518d34c328/src/coreclr/vm/ceemain.cpp#L1742-L1744 talks about `ExitThread`. I do not see how this can help to make `ExitThread` work better. And even if it did make `ExitThread` work better in some cases, I would not have a problem with breaking it. `ExitThread` on a managed thread is one of those cases that are always going to work poorly.

**Comment by kouvel** [comment]
> I do not see how this can help to make `ExitThread` work better. And even if it did make `ExitThread` work better in some cases, I would not have a problem with breaking it. `ExitThread` on a managed thread is one of those cases that are always going to work poorly.

I had done some brief testing with `ExitThread` also based on the comment, it looks like while `ExitThread` would obviously not run destructors on the stack, it does run thread-local destructors both on Windows and Linux. That I believe is similar in behavior to before, where `DLL_THREAD_DETACH` is raised for a thread that calls `ExitThread`.

That said, I don't think this would make `ExitThread` scenarios any better, I'm supposing that it wouldn't make them worse either.

**Comment by jkotas** [comment]
> If a thread that has managed frames on the stack calls ExitProcess directly, bypassing Environment.Exit, then it could run into the same type of hang. I'm not sure at the moment what would be a good way of fixing that. Fixing the frame pointer only in DllMain I expect would resolve the issue when coreclr is loaded as a DLL, but I'm not sure about statically-linked cases.

Would switching to `FlsAlloc` callback on Windows, like we do in native AOT https://github.com/dotnet/runtime/blob/9ae1a7cb4e024fce01bee35f533c268858e3320b/src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp#L149 help with addressing this?

We do not set any flags before exiting the process in native AOT. It would be best for CoreCLR to be on the same plan.

**Comment by kouvel** [comment]
> Would switching to `FlsAlloc` callback on Windows, like we do in native AOT help with addressing this?

I did some testing, it looks like while the `FlsAlloc` callbacks are raised a bit earlier, they can still run after all other threads have been torn down. It looks like other threads can be torn down asynchronously with running the `FlsAlloc` or thread-local callbacks for the thread that called `ExitProcess`.

I also checked out `atexit` on Windows to see if it would detect a direct call to `ExitProcess` after noticing that NativeAOT is using it to avoid performing cleanup on the same thread:

https://github.com/dotnet/runtime/blob/d34ed289d34b2f9588e10673800d269d7b1a6376/src/coreclr/nativeaot/Runtime/startup.cpp#L324-L330

It looks like the `atexit` callback is not called when a thread calls `ExitProcess` unfortunately, it is called though when exiting from `main`.

Also noticed the following:

https://github.com/dotnet/runtime/blob/d34ed289d34b2f9588e10673800d269d7b1a6376/src/coreclr/nativeaot/Runtime/startup.cpp#L332-L336

Which should probably also be checked in CoreCLR, I'll update to check the thread ID on Unixes.

**Comment by kouvel** [comment]
Updated to check the thread ID on Unixes in the `TlsDestructionMonitor`, please take a look again. The diff is a bit simpler when ignoring whitespace.

**Comment by jkotas** [comment]
I still think that setting the flag that suppresses thread exit notifications before exiting is going in a wrong direction.

I think we should rather go in the direction of deleting the problematic pieces from the thread shutdown notification. It is the plan that native AOT is on. The thread shutdown notification does very little work on native AOT.

If it is not possible for some reason, it likely means that there is a problem in native AOT too.

**Comment by kouvel** [comment]
> I think we should rather go in the direction of deleting or rearranging the problematic pieces in the thread shutdown notification.

If it weren't for `ExitThread` cases, the thread shutdown notification probably wouldn't need to fix the frame pointer at all, as I suppose in all other cases there wouldn't be any managed frames on the stack when the thread is exiting. Maybe we can break `ExitThread` cases and remove the frame pointer fixup?

**Comment by jkotas** [comment]
I would not mind regressing `ExitThread`. Do you know whether `ExitThread` will be actually broken if you delete the code the resets m_pFrame?

**Comment by kouvel** [comment]
> Do you know whether ExitThread will be actually broken if you delete the code the resets m_pFrame?

I believe it would be broken, my understanding is that the main purpose of entering cooperative GC mode is to ensure that no other thread is waking that thread's stack before the thread's stack is deallocated, which would make those frame pointers invalid.

**Comment by jkotas** [comment]
The thread store lock is taken when the runtime is suspended and the stackwalks are happening. The thread detach takes the thread store lock to delete the thread from the thread store. The thread detach will wait on the thread store lock until the runtime is resumed. It should prevent stack walk from ever encountering deallocated thread stack.

**Comment by kouvel** [comment]
> The thread detach takes the thread store lock to delete the thread from the thread store. The thread detach will wait on the thread store lock until the runtime is resumed.

It's quite possible that I missed that, I had checked but I didn't see the thread store lock being taken, could you please point me to where that happens?

**Comment by kouvel** [comment]
From a very brief rescan it looks like the thread detach adjusts the state of the thread object to "detached" but the thread object wouldn't actually be removed from the thread store until some other point in time, as there could still be references to the managed thread object.

**Comment by kouvel** [comment]
> The thread detach will wait on the thread store lock until the runtime is resumed.

Could this also lead to a hang? The resume may never happen in `ExitProcess` cases on Windows.

**Comment by kouvel** [comment]
It seems like this:
https://github.com/dotnet/runtime/blob/49a0633fc77ff548740d4e8b3e7b8e210f0f7294/src/coreclr/vm/threads.cpp#L995
Should be done inside the thread store lock but I don't see it being taken.

There is another lock taken here:
https://github.com/dotnet/runtime/blob/49a0633fc77ff548740d4e8b3e7b8e210f0f7294/src/coreclr/vm/threads.cpp#L989

If the detach code would run when the same thread called `ExitProcess`, I don't think it's safe for it to wait for anything. Otherwise, the detach code shouldn't run in that case.

I suspect there's an issue in NativeAOT too:
https://github.com/dotnet/runtime/blob/49a0633fc77ff548740d4e8b3e7b8e210f0f7294/src/coreclr/nativeaot/Runtime/threadstore.cpp#L183-L185

I believe the comment above would not hold when it's the same thread that called `ExitProcess` and the detach code is running as a result of that. A different thread may have been torn down while holding the thread store lock, and this thread would hang.

**Comment by jkotas** [comment]
> From a very brief rescan it looks like the thread detach adjusts the state of the thread object to "detached" 

Yes, you are right. (I have described how the detach works in native AOT. I forgot that CoreCLR uses different scheme.)

**Comment by jkotas** [comment]
> > The thread detach will wait on the thread store lock until the runtime is resumed.

> Could this also lead to a hang? The resume may never happen in ExitProcess cases on Windows.

It won't hang, assuming thread store lock is CRITICAL_SECTION. Instead, it is going to exit the process immediately, skipping the remaining cleanup. During shutdown, EnterCriticalSection terminates the process immediately when it is called on a critical section taken by some other thread.

**Comment by jkotas** [comment]
> It seems like this:
https://github.com/dotnet/runtime/blob/49a0633fc77ff548740d4e8b3e7b8e210f0f7294/src/coreclr/vm/threads.cpp#L995
> Should be done inside the thread store lock but I don't see it being taken.

Yes, it is a tricky lock-free scheme. It is likely that it is has subtle race conditions.

I would avoid coupling it with thread store lock. Instead, introduce a single counter that counts the number of foreground threads and check that counter atomically to detect when it is safe to exit. It is what native does here: https://github.com/dotnet/runtime/blob/4b75f938a6a76a7dea177ca70de7b81878f14d33/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.NativeAot.cs#L489-L502. (If you would like to clean it up, it should be a separate PR.)

**Comment by kouvel** [comment]
Should I close this PR and open a separate one to remove the frame pointer fixup that breaks `ExitThread` cases?

**Comment by kouvel** [comment]
> remove the frame pointer fixup

Actually nevermind, that may not work either, and there may be more things to investigate. Closing for now.

**Comment by kouvel** [comment]
> It won't hang, assuming thread store lock is CRITICAL_SECTION. Instead, it is going to exit the process immediately, skipping the remaining cleanup. During shutdown, EnterCriticalSection terminates the process immediately when it is called on a critical section taken by some other thread.

I imagine this would also prevent thread-local destructors and `DLL_PROCESS_DETACH` from being raised. Is that ok?

**Comment by jkotas** [comment]
Correct, the rest of the cleanup code won't run.

**Comment by kouvel** [comment]
I guess it's a necessity.

**Pull request closed without merging**
