### PR TITLE
Remove invalid assertion in InitializePropCache

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Contributes to #60962.

### CODE REVIEW

**Review by krwq — CHANGES_REQUESTED** [review]
Please do not edit this code path. I'll be changing this code path in my next change and this will create unnecessary merge conflict for me. Also the assert will actually be true after my changes

**Comment by jkotas** [comment]
> Please do not edit this code path. I'll be changing this code path in my next change and this will create unnecessary merge conflict for me. Also the assert will actually be true after my changes

**Review by krwq — APPROVED** [review]
approving so that CI is greener

**Comment by krwq** [comment]
quic failures are unrelated so merging

**Pull request merged**
