### PR TITLE
Try to skip pause_* tests again

### PR DESCRIPTION
**Pull request by agocke**
Previous syntax didn't work, I guess.

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by hoyosjs** [comment]
Somehow they are still running... https://dev.azure.com/dnceng/public/_build/results?buildId=1476452&view=ms.vss-test-web.build-test-results-tab&runId=42303712&resultId=102801&paneView=debug

**Comment by agocke** [comment]
Arghhh it's a typo I didn't close the paren!!

**Comment by hoyosjs** [comment]
That explains the lack of mono runs maybe?

**Pull request merged**
