### PR TITLE
Update solution files to include all CoreLib dependencies

### PR DESCRIPTION
**Pull request by ViktorHofer**
VS requires all dependencies to be listed in a solution file. If they aren't present, they don't get built which usually fails the build then.

Update the three CoreLib solution files:
- coreclr
- mono
- nativeaot

I forgot to mention that this fixes CoreLib failing to build in VS from a fresh clone. cc @EgorBo

### CODE REVIEW

**Comment by huoyaoyuan** [comment]
Does this cover the problem in #103819?

**Comment by ViktorHofer** [comment]
Yes it does :) Forgot about commenting in your PR, sorry.

**Review by MichalStrehovsky — APPROVED** [review]
> which usually fails the build then.

It only fails the build because there's a disagreement between where the build output should be between VS build and build.cmd build.

I always just copy a build.cmd-built binary to whatever location VS complains about.

It is unfortunate we need to add extra projects to the solution file that then slows down VS, but I know it is the current status quo.

LGTM.

**Comment by MichalStrehovsky** [comment]
> That should be fixed, shouldn't it?

I looked at it in the past and had no clue how to approach the VS build (how do I even get a binlog of the fast up-to-date check and why is it looking where it's looking)

**Comment by ViktorHofer** [comment]
You can set these two environment variables and then launch devenv.exe and will find binlogs produced under `MSBUILDDEBUGPATH`: https://learn.microsoft.com/en-us/visualstudio/ide/msbuild-logs?view=vs-2022#capture-binary-logs-through-visual-studio

**Pull request merged**
