### PR TITLE
Revert MSVC changes for libunwind

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
The changes made to libunwind for SDL requirements seem to have caused a regression in libunwind. This PR reverts them since they have been confirmed to cause regressions that we may not be observing but could be causing underlying issues.

See https://github.com/libunwind/libunwind/pull/333#issuecomment-1136277964 for the revert.

/cc @janvorli @am11

### CODE REVIEW

**Review by am11 — APPROVED** [review]
Looks good, thanks!
Since it was a partial revert upstream, please add a reference to the commit in `libunwind-version.txt`:

```
Apply https://github.com/libunwind/libunwind/commit/7cf6e84bb86ff5840896b4910ccc3865d4f00ffb
```

**Comment by AaronRobinsonMSFT** [comment]
@elinor-fung can you confirm this revert?

**Review by elinor-fung — APPROVED** [review]
Aside from @am11's comment about `libunwind-version.txt`, looks good to me.

**Comment by AaronRobinsonMSFT** [comment]
Last commit is textual change in version tracking file. Previous run was green.

**Pull request merged**
