### PR TITLE
Make virtual delegate targets less costly

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Saves 1.5% on the Stage2 app.

We make sure delegate targets are reflection visible to support Delegate.GetMethodInfo. When I originally did this work in #70198 I made a shortcut to avoid yet another node kind in the system (with a giant comment explaining what the problem is). But there's a lot of benefit in having this new node for apps with many reflection visible virtual methods.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Comment by jkotas** [comment]
Test failure looks related:

Method `Mono.Linker.Tests.Cases.DataFlow.StaticInterfaceMethodDataflow.DamOnGenericKeepsMethod.ImplIFoo.VirtualMethod()' should have been kept\nExpected: True\nActual:   False

**Comment by vitek-karas** [comment]
The test infra reacts to ReflectableMetod nodes, not the new node type. That said I don't see why the test in question would have anything marked as a delegate target.

**Comment by MichalStrehovsky** [comment]
The test that's failing is this one:

https://github.com/dotnet/runtime/blob/19712d9cbeb086bf196c43b8b502e463702fc910/src/tools/illink/test/Mono.Linker.Tests.Cases/DataFlow/StaticInterfaceMethodDataflow.cs#L22-L55

I can't think of any reason why `ImplIFoo.VirtualMethod` should be kept besides `Type.GetInterfaceMap`. Can anyone see other way how that would be observable?

If there isn't any, I'd suggest we just disable this test on https://github.com/dotnet/runtimelab/issues/861 and move on with life. If that issue is ever fixed we'd need to make this marking conditional on `GetInterfaceMap` being called somewhere in the app because 1.5% is a lot to leave on the table.

**Comment by vitek-karas** [comment]
I think you're correct - the method is not needed.
I updated the test and also added a variation which actually calls the method to make sure it's kept.

**Comment by MichalStrehovsky** [comment]
@vitek-karas could you have a look?

**Review by vitek-karas — APPROVED** [review]
Nice - thanks!

**Pull request merged**
