### PR TITLE
Allow the inliner to substitute for small arguments

### PR DESCRIPTION
**Pull request by jakobbotsch**
Since we no longer have contextual nodes to indicate small arguments
this should be safe to do. For register arguments it does not matter and
for stack arguments it is handled in codegen (for macOS arm64).

### CODE REVIEW

**Comment by jakobbotsch** [comment]
This is waiting on #69117

**Comment by jakobbotsch** [comment]
Failures are #69349, #68690, #69350, #69232, #69154, #68513

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS
I need to spot check the [diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1769356&view=results), but this is generally an improvement and just undoes the limitation added in #43130.

**Review by AndyAyersMS — APPROVED** [review]

**Pull request merged**
