### PR TITLE
Disable failing tests under GCStress

### PR DESCRIPTION
**Pull request by BruceForstall**
https://github.com/dotnet/runtime/issues/51477
https://github.com/dotnet/runtime/issues/53359

### CODE REVIEW

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall The Objective-C test failure has only been observed on ARM64. If possible I would like to continue to run it on x64.

**Comment by BruceForstall** [comment]
I think you get to choose either don't run the test on arm64, or don't run it under GCStress. You don't get to choose "don't run it under both arm64 and GCStress"

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall okay. I will keep this on my backlog to monitor. Thanks.

**Review by josalem — APPROVED** [review]

**Comment by josalem** [comment]
Looks like #51477 has dumps for the gcstress failures. I'll try taking a look when I get access to a Windows machine. Thanks, Bruce.

**Pull request merged**
