### PR TITLE
Don't create multiple large files at the same time

### PR DESCRIPTION
**Pull request by adamsitnik**
Related to https://github.com/dotnet/runtime/issues/56165#issuecomment-988510349, contributes to #56165 (hopefully)

@danmoseley is there any chance you could try this PR on your machine with low disk space?

```cmd
git clone https://github.com/adamsitnik/runtime.git adsitnik && cd adsitnik && git checkout largeFileTests
.\build.cmd -c Release -subset clr+libs+libs.tests
dotnet build /t:Test .\src\libraries\System.IO.FileSystem\tests\System.IO.FileSystem.Tests.csproj  /p:Configuration=Release /p:Outerloop=true
```

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by danmoseley** [comment]
Sure I'll try it out now. machine's disk space is ~10GB 

BTW I find `gh pr checkout nnnn` to be very helpful for this kind of thing too.

**Comment by danmoseley** [comment]
@adamsitnik it still ran out of disk. 

you see the files it was trying to create were in the right places:
```
      System.IO.FileSystem.Tests.LargeFileTests.ReadFileOver2GBAsync [FAIL]
        System.IO.IOException : There is not enough space on the disk. : 'C:\Users\danmose\AppData\Local\Temp\LargeFileTests_yfuemujx.aqv\ReadFileOver2GBAsync_44_0578bd57'
        Stack Trace:
          C:\git\adsitnik\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\FileStreamHelpers.Windows.cs(128,0): at System.IO.Strategies.FileStreamHelpers.SetFileLength(SafeFileHandle handle, Int64 length)
          C:\git\adsitnik\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\OSFileStreamStrategy.cs(234,0): at System.IO.Strategies.OSFileStreamStrategy.SetLengthCore(Int64 value)
          C:\git\adsitnik\src\libraries\System.IO.FileSystem\tests\LargeFileTests.cs(47,0): at System.IO.FileSystem.Tests.LargeFileTests.ReadFileOver2GBAsync()
          --- End of stack trace from previous location ---
        System.IO.IOException : There is not enough space on the disk. : 'C:\Users\danmose\AppData\Local\Temp\LargeFileTests_lgynieba.ygu\ReadFileOverMaxArrayLength_31_da4c3d20'
      System.IO.FileSystem.Tests.LargeFileTests.ReadFileOverMaxArrayLength [FAIL]
        Stack Trace:
          C:\git\adsitnik\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\FileStreamHelpers.Windows.cs(128,0): at System.IO.Strategies.FileStreamHelpers.SetFileLength(SafeFileHandle handle, Int64 length)
          C:\git\adsitnik\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\OSFileStreamStrategy.cs(234,0): at System.IO.Strategies.OSFileStreamStrategy.SetLengthCore(Int64 value)
          C:\git\adsitnik\src\libraries\System.IO.FileSystem\tests\LargeFileTests.cs(34,0): at System.IO.FileSystem.Tests.LargeFileTests.ReadFileOverMaxArrayLength()
      System.IO.FileSystem.Tests.LargeFileTests.NoInt32OverflowInTheBufferingLogic [FAIL]
        System.IO.IOException : There is not enough space on the disk. : 'C:\Users\danmose\AppData\Local\Temp\LargeFileTests_sb4yip4j.i2z\NoInt32OverflowInTheBufferingLogic_73_8718ad16'
        Stack Trace:
          C:\git\adsitnik\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\BufferedFileStreamStrategy.cs(1020,0): at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
          C:\git\adsitnik\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\BufferedFileStreamStrategy.cs(169,0): at System.IO.Strategies.BufferedFileStreamStrategy.Dispose(Boolean disposing)
          C:\git\adsitnik\src\libraries\System.Private.CoreLib\src\System\IO\Stream.cs(158,0): at System.IO.Stream.Dispose()
          C:\git\adsitnik\src\libraries\System.IO.FileSystem\tests\LargeFileTests.cs(85,0): at System.IO.FileSystem.Tests.LargeFileTests.NoInt32OverflowInTheBufferingLogic()
      System.IO.FileSystem.Tests.LargeFileTests.ReadFileOverMaxArrayLengthAsync [FAIL]
        System.IO.IOException : There is not enough space on the disk. : 'C:\Users\danmose\AppData\Local\Temp\LargeFileTests_tzxp1xbo.h1k\ReadFileOverMaxArrayLengthAsync_57_f6bcc8b7'
        Stack Trace:
          C:\git\adsitnik\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\FileStreamHelpers.Windows.cs(128,0): at System.IO.Strategies.FileStreamHelpers.SetFileLength(SafeFileHandle handle, Int64 length)
          C:\git\adsitnik\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\OSFileStreamStrategy.cs(234,0): at System.IO.Strategies.OSFileStreamStrategy.SetLengthCore(Int64 value)
          C:\git\adsitnik\src\libraries\System.IO.FileSystem\tests\LargeFileTests.cs(60,0): at System.IO.FileSystem.Tests.LargeFileTests.ReadFileOverMaxArrayLengthAsync()
          --- End of stack trace from previous location ---
      System.IO.FileSystem.Tests.LargeFileTests.ReadFileOver2GB [FAIL]
        System.IO.IOException : There is not enough space on the disk. : 'C:\Users\danmose\AppData\Local\Temp\LargeFileTests_55b3wisa.xm2\ReadFileOver2GB_18_13dcae8f'
        Stack Trace:
          C:\git\adsitnik\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\FileStreamHelpers.Windows.cs(128,0): at System.IO.Strategies.FileStreamHelpers.SetFileLength(SafeFileHandle handle, Int64 length)
          C:\git\adsitnik\src\libraries\System.Private.CoreLib\src\System\IO\Strategies\OSFileStreamStrategy.cs(234,0): at System.IO.Strategies.OSFileStreamStrategy.SetLengthCore(Int64 value)
          C:\git\adsitnik\src\libraries\System.IO.FileSystem\tests\LargeFileTests.cs(21,0): at System.IO.FileSystem.Tests.LargeFileTests.ReadFileOver2GB()
``
I had ~9GB free, but these two files filled it up:

```
C:\Users\danmose\AppData\Local\Temp>
12/07/2021  11:56 PM     4,294,967,311 tmpD2D1.tmp
12/07/2021  07:46 PM     4,294,967,311 tmpF5B4.tmp
```
I do not understand the time stamps. The tests ran just after 12PM. I looked at one of the files, it was consistent with the writes done in NoInt32OverflowInTheBufferingLogic.

The log above shows that TestDirectory is correct. Do we expect temp files to be created as part of the process of writing these large files?

BTW does FileCleanupTestBase get disposed every test? I suspect it is every test fixture. So all files created by this class must exist together.

**Comment by danmoseley** [comment]
Hmm, all LargeFileTest failed. So it is not them creating the file. hmm

**Comment by danmoseley** [comment]
And now after cleaning everything, I can't repro it. I suggest to commit this as it's an improvement and I'll look if it happens again.

Please do check that the files are deleted between each test though. As it is, they require ~4GB free space each.

**Comment by adamsitnik** [comment]
> Please do check that the files are deleted between each test though

I've used `FileOptions.DeleteOnClose` to ensure that each file is removed before the test finishes.

I've also merged 4 tests that were testing `File.ReadAllBytes` and `File.ReadAllBytes` for two file sizes into one, so instead of creating four 2 GB files, we create a single one.

**Comment by danmoseley** [comment]
rerunning failed

**Comment by adamsitnik** [comment]
> https://github.com/dotnet/runtime/issues/62616

It's https://github.com/dotnet/runtime/issues/62616

> rerunning failed

You mean re-running the CI legs or the IO tests locally on your machine with limited disk space?

**Comment by danmoseley** [comment]
I just meant i clicked the button to rerun them in Azdo. I don't think we need to do more local testing.

**Comment by danmoseley** [comment]
Validation results look good to me.

**Comment by danmoseley** [comment]
I am satisfied that failures are unrelated.

**Pull request merged**
