### PR TITLE
[wasm] add zone.tab to dotnet.timezones.blat 

### LINKED ISSUE #39342: WASM: System.Tests.TimeZoneInfoTests.GetSystemTimeZones test fails in Browser
The test is currently doing:

```cs
ReadOnlyCollection<TimeZoneInfo> timeZones = TimeZoneInfo.GetSystemTimeZones();
Assert.NotEmpty(timeZones);
Assert.Contains(timeZones, t => t.Id == s_strPacific);
Assert.Contains(timeZones, t => t.Id == s_strSydney);
Assert.Contains(timeZones, t => t.Id == s_strGMT);
Assert.Contains(timeZones, t => t.Id == s_strTonga);
Assert.Contains(timeZones, t => t.Id == s_strBrasil);
Assert.Contains(timeZones, t => t.Id == s_strPerth);
Assert.Contains(timeZones, t => t.Id == s_strBrasilia);
Assert.Contains(timeZones, t => t.Id == s_strNairobi);
Assert.Contains(timeZones, t => t.Id == s_strAmsterdam);
Assert.Contains(timeZones, t => t.Id == s_strRussian);
Assert.Contains(timeZones, t => t.Id == s_strLibya);
Assert.Contains(timeZones, t => t.Id == s_strCatamarca);
Assert.Contains(timeZones, t => t.Id == s_strLisbon);
Assert.Contains(timeZones, t => t.Id == s_strNewfoundland);
```

Currently `Browser` for `TimeZoneInfo.GetSystemTimeZones` returns:
```
America/St_Johns
America/Argentina/Catamarca
UTC
Europe/London
Europe/Lisbon
Africa/Casablanca
Europe/Berlin
Africa/Johannesburg
Africa/Nairobi
```

cc: @lewing @tqiu8 @steveisok @akoeplinger

### PR DESCRIPTION
**Pull request by tqiu8**
Fixes #39342 by adding zone.tab to dotnet.timezones.blat.

### CODE REVIEW

**Review by safern — DISMISSED** [review]

**Review by safern — COMMENTED** [review]
Can we re-enable the test that is disabled on: #39342 to actually make sure this fixes that?

**Comment by lewing** [comment]
The wasm test failure is https://github.com/dotnet/runtime/issues/39473

**Review by lewing — APPROVED** [review]
This looks good but adds some size, should we consider trimming the core list?

**Review by safern — APPROVED** [review]
Module the size question.

**Pull request merged**
