### PR TITLE
Proposal to fix issue #38800 System.Text.Json: IgnoreNullValues ignores field that have default value

### LINKED ISSUE #38800: System.Text.Json: IgnoreNullValues ignores field that have a default value
### Description
When JsonSerializerOptions IgnoreNullValues is true then it won't serialize value type fields having default value.
See below test case as an example:

```c#
        [Fact]
        public void Should_Not_Be_An_Empty_Json_When_IgnoreNullValues_Is_True()
        {
            var options = new System.Text.Json.JsonSerializerOptions()
            {
                IgnoreNullValues = true
            };
            var emptyObj = new { };
            var obj = new
            {
                PlayOrder = 0
            };

            var jsonForEmptyObj = System.Text.Json.JsonSerializer.Serialize(emptyObj, options);
            var json = System.Text.Json.JsonSerializer.Serialize(obj, options);

            Assert.NotEqual(jsonForEmptyObj, json);
        }
```

### Configuration
.NET SDK: 5.0.100-preview.6.20318.15
Windows 10 or Linux image mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim show the same behaviour
Architecture: x64, but doesn't seem specific to it

### Regression?
It is a regression in .NET Core 3.1 it was working as expected.
It was also fine in former .NET 5 versions.

### Other information
I would be happy to help adding the test case to the framework tests if guided.

### PR DESCRIPTION
**Pull request by molinch**
Fixes #38800

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=38811) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=38811) before we can accept your contribution.<br/><br/>:x: molinch [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=38811)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=38811) it.</sub>

**Comment by molinch** [comment]
@layomia sorry it took me a few commits to fix the tests, it was really hard for me to run them
let me know your thoughts, thanks !

**Comment by layomia** [comment]
Thanks for your contribution, @molinch.

This change requires API review and approval. Please see the process [here](https://github.com/dotnet/runtime/blob/125dfe7ab4c0a93c48f94e2691b72d87288b86c7/docs/project/api-review-process.md).

Fixing the [regression ](https://github.com/dotnet/runtime/issues/38800) where value type properties are ignored when serializing with `IgnoreNullValues` active does not need any API changes. I've opened a PR to fix this here - https://github.com/dotnet/runtime/issues/38800.

FWIW - the way to prevent individual value type properties from being ignored when `JsonIgnoreCondition.WhenWritingDefault` is active on `JsonSerializerOptions` is to set `[JsonIgnore(Condition = JsonIgnoreCondition.Never)]` on the properties you wish to exclude.

If you have another concern or API suggestion, please open another issue, taking into account the documentation linked above.

**Comment by molinch** [comment]
Hi @layomia, thanks for fixing the issue. While I know about JsonIgnoreCondition.Never I don't think that having to set it on top of every value type makes sense, hence I'll propose the API suggestion.
Thanks!

**Pull request closed without merging**
