### PR TITLE
Explicitly omit RID from crossgen2 binary path

### LINKED ISSUE #29177: [release/7.0.2xx] Runtime fails to generate native System.Private.CoreLib in source-build bootstrap
I have been looking at this issue for a little bit and can't seem to make any progress, so I'm hoping someone here can point me in the right direction.

The runtime-portable build is failing in the 7.0.2xx source build bootstrap scenario only with the following error:

```
      Generating native image of System.Private.CoreLib for Linux.x64.Release. Logging to 
      /tarball/src/runtime/artifacts/source-build/self/src/dotnet.sh /tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/crossgen2/crossgen2.dll -o:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/System.Private.CoreLib.dll -r:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/*.dll --targetarch:x64 -O /tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/System.Private.CoreLib.dll --perfmap-format-version:1 --perfmap --perfmap-path:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/
      Specify which project file to use because this '/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr' contains more than one project file.
    /tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/crossgen-corelib.proj(104,5): error MSB3073: The command "/tarball/src/runtime/artifacts/source-build/self/src/dotnet.sh /tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/crossgen2/crossgen2.dll -o:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/System.Private.CoreLib.dll -r:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/*.dll --targetarch:x64 -O /tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/System.Private.CoreLib.dll --perfmap-format-version:1 --perfmap --perfmap-path:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/" exited with code 1.
    
    Build FAILED.
    
    /tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/crossgen-corelib.proj(104,5): error MSB3073: The command "/tarball/src/runtime/artifacts/source-build/self/src/dotnet.sh /tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/crossgen2/crossgen2.dll -o:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/System.Private.CoreLib.dll -r:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/*.dll --targetarch:x64 -O /tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/IL/System.Private.CoreLib.dll --perfmap-format-version:1 --perfmap --perfmap-path:/tarball/src/runtime/artifacts/source-build/self/src/artifacts/bin/coreclr/Linux.x64.Release/" exited with code 1.
        0 Warning(s)
        1 Error(s)
```

Inside `src/coreclr` are multiple project files, `crossgen-corelib.proj`, `runtime.proj`, and `runtime-prereqs.proj`. I checked that these are also present in the runtime that's in .NET 7.0.1xx.
I also checked that the error from the .NET CLI isn't new to .NET 7.0.2xx. I'm not sure where else to look. Maybe @ViktorHofer knows who to tag?

### PR DESCRIPTION
**Pull request by jkotas**
Fixes https://github.com/dotnet/sdk/issues/29177

### CODE REVIEW

**Review by nagilson — APPROVED** [review]
LGTM, but be aware that this is still a changed behavior. `RuntimeIdentifier` will be set where it didn't used to be set before, even if it's not in the path. And I don't know if that has implications with how crossgen uses `RuntimeIdentifiers`. `SelfContained` and friends shouldn't allow you to build/publish if you don't have a `RuntimeIdentifier` unless there is some spicy customization going on here. If there's logic somewhere to allow that, it's unnecessary if the SDK infers a `RuntimeIdentifier` for you now, so it could be removed. 

Also, FYI failure in musl arm64 appears unrelated:
```go
   System.Net.Http.Tests.ContentDispositionHeaderValueTest.FileNameStar_NeedsEncoding_EncodedAndDecodedCorrectly [FAIL]
      Assert.Equal() Failure
                    ↓ (pos 4)
      Expected: FileÃName.bat
      Actual:   File?�Name.bat
                    ↑ (pos 4)
```

**Comment by jkotas** [comment]
@nagilson Thank you!

> SelfContained and friends shouldn't allow you to build/publish if you don't have a RuntimeIdentifier unless there is some spicy customization going on here

There is a lot of customization in dotnet/runtime build. My reason for fixing the issue using `AppendRuntimeIdentifierToOutputPath` is that other [very similar project](https://github.com/dotnet/runtime/blob/fdec9204d8a7eaee5542b3cd971ad48621e8da20/src/coreclr/tools/aot/ILCompiler/ILCompiler.props#L21) has this property set, and so it is unlikely to run into unexpected issues.

> the SDK infers a RuntimeIdentifier for you now

I do not think that the SDK can infer RuntimeIdentifier for us. dotnet/runtime supports number of cross-building scenarios (e.g. running on linux-x64 and building for linux-arm64). The RID has to be explicitly specified for these cases.

> failure in musl arm64 appears unrelated

Yes, it is unrelated (build-analysis has a link to the tracking issue).

**Comment by nagilson** [comment]
> I do not think that the SDK can infer RuntimeIdentifier for us 

While the SDK might not be able to cleverly in this case, the breaking change is that it will try to use the machine RID if you have a property like SelfContained or PublishSingleFile, as normally these properties will fail your build if `RuntimeIdentifier` is not set. 
`UseCurrentRuntimeIdentifier` would disable that. But I think the path decision was the right way to go, because we are also considering making net 8 apps RID specific by default, so then you'd need that _and_ `RuntimeSpecific` = false.

**Pull request merged**
