### PR TITLE
[tests][mobile] Enable diagnostic_tracing for iOS runtime tests

### PR DESCRIPTION
**Pull request by mdh1418**
This PR looks to stand-up diagnostics tests for iOS. Diagnostics runtime components have been made compatible for mobile platforms, and here, they will be tested and integrated.

This is the iOS parallel of https://github.com/dotnet/runtime/pull/60879

The following are changes made:
Includes diagnostics_tracing runtime components in BuildiOSApp
----
With a goal of emulating the diagnostics tracing tests on mono desktop, the following tests now pass locally.

## eventlistener
eventlistener

## eventcounter
eventcounter
pollingcounter
regression-46938
regression-25709
incrementingpollingcounter
runtimecounters
incrementingeventcounter
gh53564

## eventactivityidcontrol
eventactivityidcontrol

----

### CODE REVIEW

**Comment by mdh1418** [comment]
If the diagnostics tests on extra platforms lane are good, then I'll revert the code that reenables the ios runtime tests as there are still problematic tests there.

**Comment by mdh1418** [comment]
Checked in the CI runs, all 10 of the tests mentioned in the description are passing on runtime-staging https://helix.dot.net/api/jobs/5d44bace-4d99-4cde-9ac8-eb29f4997b73/workitems/PayloadGroup0?api-version=2019-06-17
Will revert the commit that re-enabled iOS runtime tests.

The other failures seem unrelated.

**Review by MaximLipnin — APPROVED** [review]

**Pull request merged**
