### PR TITLE
[iOS][maccatalyst] Reenable MacCatalyst and Simulator CI runs

### PR DESCRIPTION
**Pull request by mdh1418**
Since ioslike simulator x64 library lanes are looking healthy, try reenabling

This reverts commit 67b6e81d9d2fca8544d37f04998d352bdc0fd69e.

### CODE REVIEW

**Comment by steveisok** [comment]
The catalyst failure will be fixed by https://github.com/dotnet/runtime/pull/84842

**Comment by steveisok** [comment]
`NamedPipeTest_CreateServer.PipeOptions_FirstPipeInstanceWithSameNameReuse_Throws_UnauthorizedAccessException` needs fixed.  

```
System.ArgumentOutOfRangeException : The path '/Users/helix-runner/Library/Developer/CoreSimulator/Devices/92790E07-0212-4175-87AB-3F59CEEFF99F/data/Containers/Data/Application/C9BE5F0F-363D-4725-8439-6DF065A25458/tmp/CoreFxPipe_toz2mdfe.y1q' is of an invalid length for use with domain sockets on this platform.  The length must be between 1 and 104 characters, inclusive. (Parameter 'path')
Actual value was /Users/helix-runner/Library/Developer/CoreSimulator/Devices/92790E07-0212-4175-87AB-3F59CEEFF99F/data/Containers/Data/Application/C9BE5F0F-363D-4725-8439-6DF065A25458/tmp/CoreFxPipe_toz2mdfe.y1q.
```
@mkhamoyan I recall you addressing temp names such as this before. Was that for named pipes or file system?

**Comment by mkhamoyan** [comment]
@steveisok we had several issues open for that (from brief looking found https://github.com/dotnet/runtime/issues/51390, https://github.com/dotnet/runtime/issues/67853). 
In my PR https://github.com/dotnet/runtime/pull/72935 , I tried to shorten pipe name but I was getting a permission denied error on the socket bind, then PR was closed as  @directhex fixed it with https://github.com/dotnet/runtime/pull/74927

**Comment by steveisok** [comment]
@mkhamoyan the maccatalyst failures are IsolatedStorage ones.  They pass for me locally, which does not make a whole lot of sense right now.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=303959&view=ms.vss-test-web.build-test-results-tab

**Comment by mkhamoyan** [comment]
Works for me also locally. Maybe WipeStore doesn't clean old existing paths , will update it.

**Review by steveisok — APPROVED** [review]

**Pull request merged**
