### PR TITLE
Annotate WebSockets.RegisterPrefixes with [Obsolete]

### LINKED ISSUE #50530: Annotate unsupported APIs in System.Net
As part of https://github.com/dotnet/runtime/issues/47228 i am running an analyzer to detect APIs throwing PNSE but not annotated with Obsolete/SupportedOSPlatform/UnsupportedOSPlatform attributes, we need to annotate them so that developers get warnings when they use them unexpectedly

For now, I have results only for cross-platform builds, analysis of targeted builds are coming soon which could detect more APIs and will be added here

API | Comment | Suggestion | Location
-- | -- | -- | --
'WebSocket.RegisterPrefixes()' | unconditionally throws on all platforms | add [Obsolete] | libraries\System.Net.WebSockets\src\System\Net\WebSockets\WebSocket.cs(172,13)
All APIs in Quic |Seems only supported on windows, Linux, OSX, FreeBSD | add assembly level SupportedOSPlaform("windows"), SupportedOSPlaform("Linux"), SupportedOSPlaform("OSX"), SupportedOSPlaform("FreeBSD") attributs | runtime\artifacts\obj\System.Net.Quic\net6.0-Debug\System.Net.Quic.notsupported.cs(103,49)

Note: We are suggesting adding [Obsolete] for the APIs only supported in .Net framework but not supported in .NetCore, with the corresponding Message, DiagnosticId, and UrlFormat https://github.com/dotnet/runtime/blob/cecc76a29a8b6c1fca181a38f076b4d949081746/src/libraries/System.Net.Requests/src/System/Net/AuthenticationManager.cs#L17 You can claim the next available DiagnosticId from Obsoletions.cs .

cc @jeffhandley @terrajobst @GrabYourPitchforks

### PR DESCRIPTION
**Pull request by alnikola**
Fixes #50530

### CODE REVIEW

**Comment by stephentoub** [comment]
Did we discuss this one in API review?

Does it need a unique diagnostic ID or we're ok just with the general ID?

The ref needs to be updated accordingly as well.

**Comment by alnikola** [comment]
@stephentoub Sorry, I didn't know that an API review is required for this since the issue #50530 explicitly asks to do it and a similar thing was done for QUIC API #49261.
Should I close this PR then?

**Comment by stephentoub** [comment]
> Should I close this PR then?

No, this one's pretty simple.  @bartonjs, @terrajobst, any concerns?  This API is useless and is already hidden.

**Comment by bartonjs** [comment]
> any concerns?

Not from me.  I like Obsoleting things :smile:.

It'd be a good idea to fix the tests so they compile, though :smirk:

**Comment by alnikola** [comment]
Build fixed.

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
