### PR TITLE
[mono][workload] Add workloads for win-arm64 using emulation

### PR DESCRIPTION
**Pull request by lewing**
Reverts dotnet/runtime#67154

### CODE REVIEW

**Comment by lewing** [comment]
see https://github.com/dotnet/emsdk/pull/139 for discussion

**Comment by lewing** [comment]
would fix https://github.com/dotnet/runtime/issues/72722

**Comment by steveisok** [comment]
Official build run https://dev.azure.com/dnceng/internal/_build/results?buildId=2022393&view=results

**Comment by steveisok** [comment]
Official build passed.  We should also manually validate on win-arm64.

**Review by steveisok — APPROVED** [review]

**Pull request merged**
