### PR TITLE
[Infra] Add ABORT based dumps back for macOS

### PR DESCRIPTION
**Pull request by josalem**
Recently discovered that the dumps generated `createdump` on mac are _only_ debuggable in `dotnet-dump analyze` and _only_ contain the necessary information to inspect managed code.  This is due to `createdump` generating an ELF dump on a macOS system which typically would have a MACH format dump.  This means that the `createdump` dump can't be debugged under LLDB to inspect native information.  The previous version of the dumping logic invoked a `SIGABRT` causing the system to generate the core dump in the MACH format.  This dump could be inspected under LLDB for native information, but could not be used to inspect managed information since SOS doesn't know how to unwind a MACH coredump.

To combat this, I'm adding back in the `SIGABRT` mechanism for macOS _in addition to_ the `createdump` mechanism.  This unfortunately results in 2x the dumps on macOS, but also allows us to be able to triage managed code or native code.

I'm open to switching entirely to one or the other with a small preference for _just_ the `SIGABRT` mechanism due to native code usually being the thing needing triaging for `coreclr` tests.  Once `createdump`/`SOS` have a MACH format dumper and reader, we could rely solely on `createdump` on macOS.

CC @tommcdon

### CODE REVIEW

**Comment by hoyosjs** [comment]
Is this injecting a SigAbort and then doing the createdump path? I think I'd rather capture managed state before getting handlers on the stacks. As for choosing one if we had to, the system dump is better for most cases for us. LLDB will still open it and we can use SOS, the main issue is that it's not a full fidelity dump (have to trust the OS to get the necessary memory - I don't know what's Darwin's equivalent of `coredump_filter` as cores are not as common practice there - and we've mucked the state by injecting a signal).

**Comment by mikem8361** [comment]
The reason we are creating dumps both ways is because of the lldb bug that breaks SOS for the system generated dump. So the createdump generated one to inspect the managed state with dotnet-dump and the system dump for native state.  

@josalem there is one problem with the SIGABRT if the env var COMPlus_DbgEnableMiniDump=1. You will get both an system dump and createdump will be launched and a dump will attempted to be created.  It will fail because the binaries are not signed/entitled properly but once that happens you will end up with both being generated by the SIGABRT and a third by the explicit createdump.

**Comment by josalem** [comment]
Based on this discussion I think it might be better to simply use `COMPlus_DbgEnableMiniDump=1` + `SIGABRT` on macOS.  @mikem8361 where does the induced `createdump` end up when `COMPlus_DbgEnableMiniDump=1` is set?  I want to make sure both it and the system one make it into the HELIX drops directory.

**Comment by mikem8361** [comment]
COMPlus_DbgEnableMiniDump should already be set by the harness along with COMPlus_DbgMiniDumpName for the name. But triggering it with SIGABRT still has the two problems:

1) It is still an ELF coredump with no way to analyze the native state.
2) The createdump will be launched but fails on the task_to_pid api because of the signing/entitlement.

**Comment by josalem** [comment]
So what we want on macOS is the following:
* `COMPlus_DbgEnableMiniDump=0`
* `SIGABRT` with system collected dump
* manually invoked `createdump` 

Does that track?

**Comment by hoyosjs** [comment]
Can we do creatdump first and then the other two?

**Comment by josalem** [comment]
When I looked, I didn't see the harness setting `COMPlus_DbgEnableMiniDump` anywhere, so I don't think the tests are being run with this command unless it is being set elsewhere.  Anyone know?

**Comment by josalem** [comment]
Adding the no merge label until the validation test is removed since the test purposefully times out.

**Comment by josalem** [comment]
Closing as stale, since the test wrapper has changed a bit since this PR.  We can revisit this if it turns out to still be necessary.

**Pull request closed without merging**
