### PR TITLE
Submit to helix without managed pdbs

### LINKED ISSUE #33438: Prune all helix payloads
1. Investigate core_root size (1g) and prune for helix testing
2. Investigate test payload sizes and prune where possible.

### PR DESCRIPTION
**Pull request by jashook**
Closes https://github.com/dotnet/runtime/issues/33438

### CODE REVIEW

**Comment by jaredpar** [comment]
How much size does this end up saving?

**Comment by jashook** [comment]
I will post size and time saved once the runs finish.

**Review by echesakov — CHANGES_REQUESTED** [review]
If the intent here to remove ALL pdb from the Helix submission then you don't need to change testgrouping.proj This file should be left for specifying partitioning of the test tree.

Also, some of the test tree subdirectories are not included in TestGrouping so you would miss pdb-s in those.

What you want instead is to add 
```xml
  <_PayloadFiles Remove="*.pdb" />
```
at the end of this ItemGroup
https://github.com/dotnet/runtime/blob/ee0aadc3dad5c8d64ce67c6f7ddeb07326aeb8ec/src/coreclr/tests/helixpublishwitharcade.proj#L125-L137

**Comment by jashook** [comment]
Looks like this did not correctly remove pdbs. Looking further into it.

**Comment by jashook** [comment]
After way more time than I wanted to spend looking at msbuild logs, I believe this correctly filters out the managed pdbs. I added removing the .sh/.cmd files on the perspective targets while I was there. Although the size difference for scripts is extremely small.

**Comment by echesakovMSFT** [comment]
> 
> 
> After way more time than I wanted to spend looking at msbuild logs, I believe this correctly filters out the managed pdbs. I added removing the .sh/.cmd files on the perspective targets while I was there. Although the size difference for scripts is extremely small.

Yeah, MSBuild debugging is painful. Have you figured out why my approach didn't work out?

**Comment by jashook** [comment]
I cannot explain why remove failed to remove... I came to the (possibly incorrect assumption) that you cannot use a wildcard to remove from a list.

**Comment by jashook** [comment]
Its quite unfortunate as well because your proposed solution was quite clean.

**Comment by echesakovMSFT** [comment]
> 
> 
> I cannot explain why remove failed to remove... I came to the (possibly incorrect assumption) that you cannot use a wildcard to remove from a list.

No, you can *usually* do this. See https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2019#BKMK_RemoveAttribute

But I remember observing a similar behavior in the past...

Maybe @sbomer knows why? I put a link to the change with wrong behavior - https://github.com/dotnet/runtime/pull/36577/commits/65859c5373b1c6a96dacb177951c8dc2704f3477

**Comment by jashook** [comment]
I was looking at the same thing earlier, it could be a bug with removing things with Attributes?

**Comment by jashook** [comment]
I do not have timing information yet, but this change reduces the aggregate size of our pri0 Windows payload from `1.92 gb` to `313 mb`.

**Review by echesakov — APPROVED** [review]
Thanks a lot @jashook !

Changes look good - I don't think it's worth spending more time to figure out why Remove-attribute doesn't work (even though I would love to know why)

At some point we need to collect information how this affects the Helix setup time.

**Comment by jashook** [comment]
I will have that information soon. I am currently a few days behind, but I believe I should ingest up to today over the long weekend. Will post with timing then.

https://gist.github.com/jashook/42fb536682ac34f032f1bc095397c59b

**Comment by sbomer** [comment]
I think the wildcard matches against files in the current directory only, not members of the ItemGroup. I haven't confirmed, but that might be why it didn't work.

**Comment by jashook** [comment]
Failures are unrelated. Data I hard to show without more runs as networking gives a lot of noise. However, rough estimate is roughly 30-50% improvement.

**Comment by jashook** [comment]
After ~1 week of data collection there is enough data to show this change reduced helix setup time for coreclr and mono submissions by ~50%.

**Pull request merged**
