### PR TITLE
Reduce the trim requirements on MetadataUpdateHandlerAttribute

### LINKED ISSUE #66069: Reduce the trim requirements on MetadataUpdateHandlerAttribute
Currently the type passed to the `.ctor` of `MetadataUpdateHandlerAttribute` will be annotated with `DynamicallyAccessedMemberTypes.All`. For apps this doesn't matter because the attribute is marked for removal in trimmed apps by default, so the annotation is not applied.

But this does matter for analysis of libraries for trimming. The `All` annotation is particularly problematic because it will force include all nested types and may cause additional warnings produced by the analysis as it will treat all members on the type as potentially accessed via reflection (so any member annotated for trimming in any way will produce a warning).

My reading of the usage of `MetadataUpdateHandlerAttribute` shows that we only need methods on the target type (in fact we only need two specific static methods, but there's no way to annotate it that way right now).

Can we improve the annotation on the `MetadataUpdateHandlerAttribute` to only ask for methods: `DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods`?

### PR DESCRIPTION
**Pull request by pedrobsaila**
Fixes #66069

### CODE REVIEW

**Comment by pedrobsaila** [comment]
@vitek-karas I tried updating MetadataUpdateHandlerAttribute but got compatibility errors with .net7.0.
Is introducing a breaking change intended ? if yes how to by pass the check ?

**Comment by vitek-karas** [comment]
This is hitting the same problem as https://github.com/dotnet/runtime/pull/84326 - just different attribute.
In this case it's a bit more subtle: For `DynamicallyAccessedMembersAttribute` it should be OK to reduce the annotation (in this case from `All` to "all methods only"). It should NOT be OK to broaden the annotation as that may introduce new warnings.

Do we have a way to baseline just one specific attribute difference - as intentional?

@ericstj @eerhardt

**Comment by eerhardt** [comment]
In 7.0 we had

https://github.com/dotnet/runtime/blob/release/7.0/src/libraries/apicompat/ApiCompatBaseline.NetCoreAppLatestStable.txt

that allowed us to baseline specific known API compat issues. But I'm not seeing this in main. @ericstj, @ViktorHofer ?

**Comment by ericstj** [comment]
It's the new format in Main: https://github.com/dotnet/runtime/blob/main/src/libraries/apicompat/ApiCompatBaseline.NetCoreAppLatestStable.xml

You could modify it directory, or try generating it.

To generate it you could do:
```
dotnet build ApiCompat.proj /p:ApiCompatGenerateSuppressionFile=true
```

**Review by steveharter — APPROVED** [review]

**Comment by steveharter** [comment]
@pedrobsaila thanks for this contribution.

**Pull request merged**
