### PR TITLE
Deduplicate runtime tests using the class name 'Test'

### PR DESCRIPTION
**Pull request by trylek**
This change deduplicates test class names 'Test' by appending the identifier-sanitized filename of the source file containing the Main method for the test. The next group will be 553 occurrences of 'BringUpTest'.

Thanks

Tomas

Contributes to: https://github.com/dotnet/runtime/issues/54512

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by BruceForstall** [comment]
Looks like Loader\classloader\DictionaryExpansion\DictionaryExpansion.cs depends on the test name.

Can you make sure to run the outerloop test job on these big changes, where you need to run Pri-1 tests to validate?

**Comment by trylek** [comment]
@BruceForstall - as you can see, I'm running outerloop runs on each of these changes, I completely agree with you.

**Comment by BruceForstall** [comment]
There's kind of an interesting implication of this work, that all tests need to have globally unique names. So when I create a new test, there will presumably be a build failure if I create one with a conflicting (e.g., simple) name. Hopefully that's not too annoying.

**Comment by trylek** [comment]
@BruceForstall - strictly speaking not all tests need to have unique names; our current thinking is that the grouping will be based on explicit markers in the tree and that implies that test class names need to be unique just within a single group. One way or another, the grouped build (that I expect to become the default, both locally and in the lab) should immediately identify an inadvertently introduced duplication when adding a new test and bail out where the error message should clearly indicate the problem.

**Comment by trylek** [comment]
Merging in with 1 known outerloop failure https://github.com/dotnet/runtime/issues/60152.

**Pull request merged**
