### PR TITLE
JIT: reset max bbnum after failed inline attempt

### PR DESCRIPTION
**Pull request by AndyAyersMS**
And if we renumber blocks in the inlinee's portion of the flow graph, start renumbering from the max bbnum before the inline attempt, rather than the current maximum.

More prep work in anticipation of moving pred list building to happen before (or the root) and during (for inlinees) inlining.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
More refactoring in preparation for moving pred list building earlier.

@EgorBo PTAL
cc @dotnet/jit-contrib

**Review by EgorBo — APPROVED** [review]
Reminds me that normally we almost never inline methods with SWITCHes (only with foldable ones) but in some jitstress mode we do that due to extra multipliers so I think I once hit some BBNum related bug there (and fixed)

**Comment by AndyAyersMS** [comment]
> Reminds me that normally we almost never inline methods with SWITCHes (only with foldable ones) but in some jitstress mode we do that due to extra multipliers so I think I once hit some BBNum related bug there (and fixed)

Are you politely suggesting that I should run jit stress?

**Comment by AndyAyersMS** [comment]
Building pri1 tests may be broken?
```
/__w/1/s/src/tests/reflection/regression/github_25697/25697.cs(9,73): error CS8500: This takes the address of, gets the size of, or declares a pointer to a managed type ('TypedReference') [/__w/1/s/src/tests/reflection/regression/github_25697/25697.csproj] [/__w/1/s/src/tests/build.proj]
```

**Comment by AndyAyersMS** [comment]
Libraries stress hitting an assert, probably something I did recerntly (if not in this PR)
```
Assert failure(PID 28 [0x0000001c], Thread: 41 [0x0029]): Assertion failed 'topBB->bbNum <= botBB->bbNum' in 'FsCheck.TypeClass+FromType@48:Invoke(System.Type):bool:this' during 'Set block order' (IL size 9; hash 0xf9ed1197; Tier0-FullOpts-MinOpts)

    File: /__w/1/s/src/coreclr/jit/optimizer.cpp Line: 4695
    Image: /root/helix/work/correlation/dotne
```

**Comment by AndyAyersMS** [comment]
> Building pri1 tests may be broken?
> 
> ```
> /__w/1/s/src/tests/reflection/regression/github_25697/25697.cs(9,73): error CS8500: This takes the address of, gets the size of, or declares a pointer to a managed type ('TypedReference') [/__w/1/s/src/tests/reflection/regression/github_25697/25697.csproj] [/__w/1/s/src/tests/build.proj]
> ```

Related: #80931

**Comment by AndyAyersMS** [comment]
> Libraries stress hitting an assert

When we're not optimizing, `fgSetBlockOrder` requires bbNums in increasing order (or at least `fgFirstBB` lower than any other BB. We don't have that in this case. Will need a fix.

**Comment by AndyAyersMS** [comment]
Merging to pick up the jitstress fix.

**Comment by AndyAyersMS** [comment]
No diffs in SPMI.

Runtime failure is https://github.com/dotnet/runtime/issues/80773.
Coreclr jitstress failures are https://github.com/dotnet/runtime/issues/80666.
Libraries jitstress failures are https://github.com/dotnet/runtime/issues/80773.

**Pull request merged**
