### PR TITLE
Use latest released SDK for HttpStress.

### PR DESCRIPTION
**Pull request by rzikm**
This PR removes the .1xx suffix on the channel of the installed SDK to allow installing more recent SDKs.

### CODE REVIEW

**Comment by ManickaP** [comment]
Not for ssl stress?
https://github.com/dotnet/runtime/blob/0d426df37c6ac2c1d22f952a2e359ffd4281d47b/src/libraries/System.Net.Security/tests/StressTests/SslStress/build-local.sh#L43
https://github.com/dotnet/runtime/blob/0d426df37c6ac2c1d22f952a2e359ffd4281d47b/src/libraries/System.Net.Security/tests/StressTests/SslStress/Build-Local.ps1#L41

**Comment by antonfirsov** [comment]
```
client_1  | Failure Type 1/1:
client_1  | System.Exception: Expected response content "vX34jzA5zhRzqXM0Gciwk2wbKFctx6a2VoxTcIiqrZatioxxDAiXWUZsaRjTNH8t7OU2atOxus5BS3sWIegnN3W0E4sAYESaRhlJJvMKllceOOQXYDBiaKV3sUnV0DOfPVjlHZCNHL1cQrcqeLbL3jz6CiQp7qJXMwFteeFz0oQFJsd1rxrfc3cfVdZZ8NFQ1TFTciBz5cKFJjmJ4PxAzevJKZN15grdYzDpc9P9lrZziNMlqFUjP5RNXw92KAtPlggJWxgvzoO74wawDbApB7DTYqIgzNobxAE1h3FtZZjbgJIbLDojz4EdSCkgf0vcznAuhYFAMHG", got "vX34jzA5zhRzqXM0Gciwk2wbKFctx6a2VoxTcIiqrZatioxxDAiXWUZsaRjTNH8t7OU2atO".
client_1  |  Diverging at index 71. server checksum does not match client value.
```

:(

**Comment by ManickaP** [comment]
> ```
> client_1  | Failure Type 1/1:
> client_1  | System.Exception: Expected response content "vX34jzA5zhRzqXM0Gciwk2wbKFctx6a2VoxTcIiqrZatioxxDAiXWUZsaRjTNH8t7OU2atOxus5BS3sWIegnN3W0E4sAYESaRhlJJvMKllceOOQXYDBiaKV3sUnV0DOfPVjlHZCNHL1cQrcqeLbL3jz6CiQp7qJXMwFteeFz0oQFJsd1rxrfc3cfVdZZ8NFQ1TFTciBz5cKFJjmJ4PxAzevJKZN15grdYzDpc9P9lrZziNMlqFUjP5RNXw92KAtPlggJWxgvzoO74wawDbApB7DTYqIgzNobxAE1h3FtZZjbgJIbLDojz4EdSCkgf0vcznAuhYFAMHG", got "vX34jzA5zhRzqXM0Gciwk2wbKFctx6a2VoxTcIiqrZatioxxDAiXWUZsaRjTNH8t7OU2atO".
> client_1  |  Diverging at index 71. server checksum does not match client value.
> ```
> 
> :(

The received message is cut:
```
vX34jzA5zhRzqXM0Gciwk2wbKFctx6a2VoxTcIiqrZatioxxDAiXWUZsaRjTNH8t7OU2atOxus5BS3sWIegnN3W0E4sAYESaRhlJJvMKllceOOQXYDBiaKV3sUnV0DOfPVjlHZCNHL1cQrcqeLbL3jz6CiQp7qJXMwFteeFz0oQFJsd1rxrfc3cfVdZZ8NFQ1TFTciBz5cKFJjmJ4PxAzevJKZN15grdYzDpc9P9lrZziNMlqFUjP5RNXw92KAtPlggJWxgvzoO74wawDbApB7DTYqIgzNobxAE1h3FtZZjbgJIbLDojz4EdSCkgf0vcznAuhYFAMHG
vX34jzA5zhRzqXM0Gciwk2wbKFctx6a2VoxTcIiqrZatioxxDAiXWUZsaRjTNH8t7OU2atO
```

:cry:

**Comment by rzikm** [comment]
This is weird, according to versions, sha, and other indicators the pulled in runtime should already contain the fix. I will investigate.

**Review by ManickaP — APPROVED** [review]
Let's merge it, but I think we should re-open the HTTP stress issue with content mismatch until we know what's going on.

**Comment by rzikm** [comment]
Reopened https://github.com/dotnet/runtime/issues/76183

**Review by antonfirsov — APPROVED** [review]
> Let's merge it

OK!

**Pull request merged**
