### PR TITLE
Enable EventPipe when EventSource is enabled

### PR DESCRIPTION
**Pull request by LakshanF**
Fixes issue #81943. CrossGen2 has `EventSourceSupport` enabled and needs the `EventPipe `library in Windows.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Circling back to the discussion in https://github.com/dotnet/runtime/pull/80382#discussion_r1100439476.

If EventSource doesn't work without enabling event pipe, shouldn't EventSourceSupport then enable event pipe? It doesn't look right that `<EventSourceSupport>true</EventSourceSupport>` is producing broken apps.

**Comment by MichalStrehovsky** [comment]
The libraries tests that are broken since eventpipe merged also enable eventsource so it's probably the same issue:

https://github.com/dotnet/runtime/pull/82022#issuecomment-1430003691

I'd like to do something with those failing tests because it's noise and we tend to regress things worse once there's noise (old issue) that we can't distinguish from signal (newly introduced issue).

**Comment by LakshanF** [comment]
> The libraries tests that are broken since eventpipe merged also enable eventsource so it's probably the same issue:
> 
> [#82022 (comment)](https://github.com/dotnet/runtime/pull/82022#issuecomment-1430003691)
> 
> I'd like to do something with those failing tests because it's noise and we tend to regress things worse once there's noise (old issue) that we can't distinguish from signal (newly introduced issue).

Created https://github.com/dotnet/runtime/issues/82231 to track this

**Comment by MichalStrehovsky** [comment]
> > The libraries tests that are broken since eventpipe merged also enable eventsource so it's probably the same issue:
> > [#82022 (comment)](https://github.com/dotnet/runtime/pull/82022#issuecomment-1430003691)
> > I'd like to do something with those failing tests because it's noise and we tend to regress things worse once there's noise (old issue) that we can't distinguish from signal (newly introduced issue).
> 
> Created #82231 to track this

I'm looking at the reasoning there: "In `NativeAOT`, `EventPipe` library is not included by default in applications due to size considerations."

Here's how the numbers look like:

Default: 1,864,192
EventPipe: 1,928,192
EventSource: 3,277,824
EventSource+EventPipe: 3,342,848

I don't know how much bigger EventPipe is going to be, but even if it doubles in size (causing an almost 4% size increase for the EventSource enabled scenario), it might be the right tradeoff: simplifying the configuration matrix for users.

Cc @dotnet/ilc-contrib for thoughts

**Comment by agocke** [comment]
> I'm looking at the reasoning there: "In NativeAOT, EventPipe library is not included by default in applications due to size considerations."

Could we leave this decision up to the managed linker? Is there a way to structure it such that you either use EventSource and EventPipe gets brought in automatically, or you don't and it's trimmed away?

**Comment by agocke** [comment]
> I'd like to do something with those failing tests because it's noise and we tend to regress things worse once there's noise (old issue) that we can't distinguish from signal (newly introduced issue).

Yeah, we can't leave these tests failing for more than a day or two. @LakshanF if you can't get them to green soon we should revert the PR

**Comment by MichalStrehovsky** [comment]
Would defaulting EventPipe to enabled if EventSource is enabled on Windows fix both the tests and crossgen2? Based on the stack in https://github.com/dotnet/runtime/pull/82022#issuecomment-1429033382 it very well may.

We could then use https://github.com/dotnet/runtime/issues/82231 for discussion whether that's the default we want to ship.

Managed trimming unfortunately can't get rid of EventSource even in a hello world because we statically use it in places - it's the reason why we need a feature switch for it.

**Comment by LakshanF** [comment]
image

**Comment by LakshanF** [comment]
Seems like the EventSource related tests are no longer failing in NativeAOT

**Review by MichalStrehovsky — APPROVED** [review]

**Pull request merged**
