### PR TITLE
Enhancements to MCS dumpMap

### PR DESCRIPTION
**Pull request by AndyAyersMS**
I've been trying to correlate methods in SPMI collections with methods
seen in profile data (say perfview). But for generic classes or generic
methods this is not easy.

To make it more feasible, in the "extra query" mode, get the names of
all the generic parameters, and then add these to the class name in MCS's
dumpMap output.

Also dump out the jit flags, so it's easier to find a particular instance
if the method was jitted more than once.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall ptal
cc @dotnet/jit-contrib 

Old vs new output... now I can tell which of the dozens of `MoveNext`s is the one I am interested in:
```
9785,AsyncStateMachineBox`1:MoveNext,"$dontInline  void MoveNext(class Thread)"

9781,AsyncStateMachineBox`1:MoveNext,"$dontInline  void MoveNext[VoidTaskResult, <ProcessRequests>d__223`1](class Thread)",  DEBUG_INFO FEATURE_SIMD SKIP_VERIFICATION BBOPT TIER1 HAS_PGO HAS_EDGE_PROFILE
```

(note one of the class parameters is itself generic;  not sure if we want to recursively chase all these down...)

**Review by BruceForstall — APPROVED** [review]
LGTM. Can you check two things:
1. Do a crossgen2 collection, to ensure crossgen2 doesn't die with these new extra queries (should be as simple as doing `superpmi.py collect --crossgen2 -output_mch_path foo.mch -assemblies ...`)
2. Can you make sure Excel can load the new map dump format as a csv? You might need/want to put double quotes around the jit flags

**Comment by AndyAyersMS** [comment]
Jit flags loads up ok in Excel (importing with `,` as a delim) but there's not header for the column, so I'll add that.

**Comment by AndyAyersMS** [comment]
And as you suspected, crossgen2 is not happy, I'll exclude these queries from crossgen for now.

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
--------------------------------
```

**Comment by BruceForstall** [comment]
Looks good. Thanks for checking.

**Pull request merged**
