### PR TITLE
[wasm] Suppress export name minification

### PR DESCRIPTION
**Pull request by kg**
Possible fix for https://github.com/dotnet/runtime/issues/94939.
See https://github.com/emscripten-core/emscripten/issues/20762

### CODE REVIEW

**Comment by pavelsavara** [comment]
It seems to me that this could also fix https://github.com/dotnet/runtime/pull/92664#issuecomment-1833341096

@kg could you please elaborate about the alternative solution "Rather than export those functions, could you add them to the table at compile time" mentioned in the emscripten discussion ?

We need the raw exports for the jiterp trace .wasm, right ? I don't understand how that would be possible without export from dotnet.wasm

**Comment by pavelsavara** [comment]
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-95613-merge-aae7977892b0410384/System.Globalization.Tests/1/console.d5b4a4b4.log?helixlogtype=result)
```
WasiApp.Native.targets(303,5): error : 
Failed to compile C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\aot-instances.dll.bc -> C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\aot-instances.dll.o [ProxyProjectForAOTOnHelix.proj]
C:\helix\work\workitem\e\publish>C:\Windows\System32\chcp.com 65001 1>nul  [ProxyProjectForAOTOnHelix.proj]
C:\helix\work\workitem\e\publish>setlocal [ProxyProjectForAOTOnHelix.proj]
C:\helix\work\workitem\e\publish>set errorlevel=dummy  [ProxyProjectForAOTOnHelix.proj]
C:\helix\work\workitem\e\publish>set errorlevel=  [ProxyProjectForAOTOnHelix.proj]
C:\helix\work\workitem\e\publish>C:\helix\work\correlation\build\\wasi-sdk\\bin\clang.exe "@C:\helix\work\correlation\build\microsoft.netcore.app.runtime.wasi-wasm\runtimes\wasi-wasm\native\src\wasi-default.rsp"  "@C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\wasi-compile-bc.rsp" -c -o "C:\Users\ContainerAdministrator\AppData\Local\Temp\tmpvcc01g.tmp" "C:\helix\work\workitem\e\wasm_build\obj\wasm\for-build\aot-instances.dll.bc"  [ProxyProjectForAOTOnHelix.proj]
clang version 16.0.0 [ProxyProjectForAOTOnHelix.proj]
Target: wasm32-unknown-wasi [ProxyProjectForAOTOnHelix.proj]
Thread model: posix [ProxyProjectForAOTOnHelix.proj]
InstalledDir: C:/helix/work/correlation/build//wasi-sdk//bin [ProxyProjectForAOTOnHelix.proj]
 (in-process) [ProxyProjectForAOTOnHelix.proj]
 "C:/helix/work/correlation/build/wasi-sdk/bin/clang.exe" -cc1 -triple wasm32-unknown-wasi -emit-obj -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name aot-instances.dll.bc -mrelocation-model static -mframe-pointer=none -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu generic -fvisibility=hidden -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb -v -fcoverage-compilation-dir=C:/helix/work/workitem/e/publish -resource-dir C:/helix/work/correlation/build/wasi-sdk/lib/clang/16 -Oz -fdebug-compilation-dir=C:/helix/work/workitem/e/publish -ferror-limit 19 -fgnuc-version=4.2.1 -vectorize-slp -o "C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\tmpvcc01g.tmp" -x ir "C:\\helix\\work\\workitem\\e\\wasm_build\\obj\\wasm\\for-build\\aot-instances.dll.bc" [ProxyProjectForAOTOnHelix.proj]
clang -cc1 version 16.0.0 based upon LLVM 16.0.0 default target wasm32-wasi [ProxyProjectForAOTOnHelix.proj]
LLVM ERROR: out of memory [ProxyProjectForAOTOnHelix.proj]
Allocation failed [ProxyProjectForAOTOnHelix.proj]
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script. [ProxyProjectForAOTOnHelix.proj]
Stack dump: [ProxyProjectForAOTOnHelix.proj]
0.	Program arguments: C:\\helix\\work\\correlation\\build\\\\wasi-sdk\\\\bin\\clang.exe @C:\\helix\\work\\correlation\\build\\microsoft.netcore.app.runtime.wasi-wasm\\runtimes\\wasi-wasm\\native\\src\\wasi-default.rsp @C:\\helix\\work\\workitem\\e\\wasm_build\\obj\\wasm\\for-build\\wasi-compile-bc.rsp -c -o C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\tmpvcc01g.tmp C:\\helix\\work\\workitem\\e\\wasm_build\\obj\\wasm\\for-build\\aot-instances.dll.bc [ProxyProjectForAOTOnHelix.proj]
1.	Code generation [ProxyProjectForAOTOnHelix.proj]
Exception Code: 0xC000001D [ProxyProjectForAOTOnHelix.proj]
0x008DFB73 <unknown module> [ProxyProjectForAOTOnHelix.proj]
0x7292C902 <unknown module> [ProxyProjectForAOTOnHelix.proj]
0x008C23A1 <unknown module> [ProxyProjectForAOTOnHelix.proj]
0x00D3FD3C <unknown module> [ProxyProjectForAOTOnHelix.proj]
0x00D3FFBC <unknown module> [ProxyProjectForAOTOnHelix.proj]
0x00D40133 <unknown module> [ProxyProjectForAOTOnHelix.proj]
0x0079E5CF <unknown module> [ProxyProjectForAOTOnHelix.proj]
clang: error: clang frontend command failed due to signal (use -v to see invocation) [ProxyProjectForAOTOnHelix.proj]
clang version 16.0.0 [ProxyProjectForAOTOnHelix.proj]
Target: wasm32-unknown-wasi [ProxyProjectForAOTOnHelix.proj]
Thread model: posix [ProxyProjectForAOTOnHelix.proj]
InstalledDir: C:/helix/work/correlation/build//wasi-sdk//bin [ProxyProjectForAOTOnHelix.proj]
clang: note: diagnostic msg: Error generating preprocessed source(s) - no preprocessable inputs. [took 91.69s] [ProxyProjectForAOTOnHelix.proj]
```

**Review by pavelsavara — APPROVED** [review]

**Comment by kg** [comment]
> It seems to me that this could also fix [#92664 (comment)](https://github.com/dotnet/runtime/pull/92664#issuecomment-1833341096)
> 
> @kg could you please elaborate about the alternative solution "Rather than export those functions, could you add them to the table at compile time" mentioned in the emscripten discussion ?
> 
> We need the raw exports for the jiterp trace .wasm, right ? I don't understand how that would be possible without export from dotnet.wasm

It would be a single exported function that contains a massive switch statement that returns references to all of the exports, so they end up having pre-reserved slots in the function pointer table. It's kind of a pain to build this

**Comment by pavelsavara** [comment]
> It would be a single exported function that contains a massive switch statement that returns references to all of the exports, so they end up having pre-reserved slots in the function pointer table. It's kind of a pain to build this

So you get back pointer, but in the trace import, you need the index into the export table, no ?

**Comment by kg** [comment]
> > It would be a single exported function that contains a massive switch statement that returns references to all of the exports, so they end up having pre-reserved slots in the function pointer table. It's kind of a pain to build this
> 
> So you get back pointer, but in the trace import, you need the index into the export table, no ?

The function pointer is an index

**Review by lewing — APPROVED** [review]
I think it would be worth capturing the potential alternate work in an issue here but this fixes known issues directly.

**Comment by kg** [comment]
Red is https://github.com/dotnet/runtime/issues/89409, and we have confirmation from a user that this fixes the issue for them, so merging

**Comment by pavelsavara** [comment]
are we going to backport it to Net8 ?

**Pull request merged**
