### PR TITLE
Cleanup stale ApiCompatBaseline files

### LINKED ISSUE #17279: Cleanup ApiCompat baseline for 4.6.3+ TargetingPack
Also includes APIs from dotnet/runtime#16720.

While enabling ApiCompat for our builds by default https://github.com/dotnet/corefx/pull/8513 we are hitting the following compat errors:

netcore50

```
TypesMustExist : Type 'System.Security.Cryptography.ECDsa' does not exist in the implementation but it does exist in the contract.
```

net463 - I suspect these are planned to go into net463 so it there might not be anything needed except the baseline before the actually exist there.

```
TypesMustExist : Type 'System.Security.Cryptography.ECCurve' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsa.Create(System.Security.Cryptography.ECCurve)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsa.Create(System.Security.Cryptography.ECParameters)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsa.ExportExplicitParameters(System.Boolean)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsa.ExportParameters(System.Boolean)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsa.GenerateKey(System.Security.Cryptography.ECCurve)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.ECDsa.ImportParameters(System.Security.Cryptography.ECParameters)' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'System.Security.Cryptography.ECParameters' does not exist in the implementation but it does exist in the contract.
TypesMustExist : Type 'System.Security.Cryptography.ECPoint' does not exist in the implementation but it does exist in the contract.
```

@bartonjs @steveharter

### PR DESCRIPTION
**Pull request by ericstj**
Fixes https://github.com/dotnet/runtime/issues/17279

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]
Why are those stale/outdated?

**Comment by ericstj** [comment]
In some cases folks removed the configurations, in others they were really old and using an older targeting pack for desktop.

**Comment by ericstj** [comment]
I essentially looked at every ApiCompatBaseline* under libraries and checked to see if it could be removed.  With this, I believe we only have one, the Cng one.  🎉 

I have plans for eventually removing that too, but not yet.

**Comment by ViktorHofer** [comment]
Thanks for providing details

**Pull request merged**
