### PR TITLE
Clean up debugger attributes tests.

### PR DESCRIPTION
**Pull request by mrvoorhe**
* Remove `SetupLinkerKeepDebugMembersAttribute`.  This isn't supported anymore by the linker.

* Remove NETCOREAPP behavior difference in debugger attribute removal tests

* Move `DebuggerDisplayAttributeOnTypeWithNonExistentMethod` to the `KeepDebugMembers` folder since that is the scenario this test is testing

### CODE REVIEW

**Comment by mrvoorhe** [comment]
@vitek-karas Do I have to do something to get the tests to rerun?  The failure about
```
src/coreclr/tools/aot/Mono.Linker.Tests/TestCasesRunner/TestCaseMetadataProvider.cs(30,57): error CS0103: (NETCORE_ENGINEERING_TELEMETRY=Build) The name 'SetupLinkerKeepDebugMembersAttribute' does not exist in the current context
```

Seems out of date.  I deleted that line.

**Comment by mrvoorhe** [comment]
> Note the error is for a file in `src/coreclr/tools/aot`, not `src/tools/illink`.

I did not see that coming!  A copy of `Mono.Linker.Tests\TestCasesRunner` 🙈

**Review by sbomer — APPROVED** [review]

**Comment by vitek-karas** [comment]
>  A copy of Mono.Linker.Tests\TestCasesRunner

Yeah - it's good and bad. It's good since we share the tests between illink and NativeAOT. It's bad because it's the same mess as in illink, just slightly different.

When I get some time I want to:
* Rename the assembly for NativeAOT - currently it's the same name between illink/NativeAOT and it can do bad things to CI/local builds sometimes
* See if we could refactor the runner to share code between the two in some easy way

**Comment by mrvoorhe** [comment]
@vitek-karas I think these changes are good now?

**Review by vitek-karas — APPROVED** [review]

**Comment by vitek-karas** [comment]
In the product we went with source sharing and partial types typically. But it was mostly for performance reasons to avoid casting a virtual calls everywhere. I would need to look into this some more which approach would work best for the tests.

**Pull request merged**
