### PR TITLE
Fix the issue that ToString method incorrectly carries "$Port"

### PR DESCRIPTION
**Pull request by DevSplash**
The following code can reproduce the issue. 
```
Cookie cookie = new Cookie("cookie", "1");
Console.WriteLine(cookie);
cookie.Port = null;
Console.WriteLine(cookie);
```
Output: 
```
cookie=1
cookie=1; $Port
```

### CODE REVIEW

**Comment by ManickaP** [comment]
Hi @DevSplash, is the fix covered by any tests? If not, since you already have a nice repro, could you add it?

**Comment by KalleOlaviNiemitalo** [comment]
RFC 2965 section 3.3.4 says:

```
port            =  "$Port" [ "=" <"> value <"> ]
```

Does this PR make it impossible to have `"$Port"` without `"=" <"> value <">`?

**Comment by KalleOlaviNiemitalo** [comment]
In the existing implementation, m_port_implicit is initially true, can be changed to false, and cannot be changed back to true. That may be unfortunate but it is consistent with m_path_implicit and m_domain_implicit. (Only Cookie.Clone() can change m_domain_implicit to false and immediately back to true.)

**Comment by DevSplash** [comment]
> RFC 2965 section 3.3.4 says:
> 
> ```
> port            =  "$Port" [ "=" <"> value <"> ]
> ```
> 
> Does this PR make it impossible to have `"$Port"` without `"=" <"> value <">`?

In fact, RFC 2965 has been obsoleted by RFC 6265. 
I think a distinction should be made:
port = null -> no carry $port
port = String.Empty -> carry $port

> RFC 2965 section 3.3.4 says:
> 
> ```
> port            =  "$Port" [ "=" <"> value <"> ]
> ```
> 
> Does this PR make it impossible to have `"$Port"` without `"=" <"> value <">`?

In fact, RFC 2965 has been obsoleted by RFC 6265. 
I think the distinction should be made: 
port = null -> no carry $port
port = String.Empty -> carry $port

**Comment by KalleOlaviNiemitalo** [comment]
RFC 6265 does not define "$Port" at all; instead, _"cookies for a given host are shared across all the ports on that host"_. I think, as long as the Cookie class implements "$Port", it should do what the historic RFC 2965 says.

**Comment by KalleOlaviNiemitalo** [comment]
> I think the distinction should be made:\
> port = null -> no carry $port\
> port = String.Empty -> carry $port

That may be a breaking change. Does it help actual applications? I imagine two reasons for setting Cookie.Port = null but neither of them is very strong:

- Pooling and recycling Cookie instances. However, setting Cookie.Path = null does not restore the original state, so it isn't very useful to have this feature just for Cookie.Port.
- Copying Cookie.Port from another instance. However, there is Cookie.Clone() already. Also, your implementation so far does not support this because the Cookie.Port returns String.Empty if null was previously set. And changing that could hurt application compatibility even more.

**Comment by KalleOlaviNiemitalo** [comment]
I think, instead of trying to improve Cookie.Port, it would be better to obsolete it because port-specific cookies are no longer supported by browsers.

**Comment by DevSplash** [comment]
> I think, instead of trying to improve Cookie.Port, it would be better to obsolete it because port-specific cookies are no longer supported by browsers.

Once port is set, there will be no way to restore the original state. 
I agree with you. The port is obsolete, it is better to obsolete it.

**Comment by KalleOlaviNiemitalo** [comment]
Any obsoletion will require an API proposal issue then, not just a pull request.
Should presumably dedicate a [diagnostic ID](https://github.com/dotnet/runtime/blob/770d630b283ec1be4a8ed41ac78e13ec1fd957b1/docs/project/list-of-diagnostics.md) to it, as well.

**Pull request closed without merging**
