### PR TITLE
Unblock publishing symbols with exclusion file

### PR DESCRIPTION
**Pull request by hoyosjs**

### CODE REVIEW

**Comment by ViktorHofer** [comment]
I assume this is only temporary until the Arcade change gets ingested into dotnet/runtime? Also the publishing pipeline only runs on Unix machines?

**Comment by hoyosjs** [comment]
Yes, it's temporary until the full fix flows.

**Comment by hoyosjs** [comment]
This depends on https://github.com/dotnet/arcade/pull/7733 being merged

**Review by ViktorHofer — APPROVED** [review]

**Comment by hoyosjs** [comment]
Failure is #44689

**Pull request merged**
