### PR TITLE
Delete `fgMorphBlockOperand`

### PR DESCRIPTION
**Pull request by SingleAccretion**
No longer necessary as we don't need to compensate for invalid IR.

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80322&view=ms.vss-build-web.run-extensions-tab) - a TP improvement, plus one small diff where we don't reduce `OBJ(ADDR(LCL_VAR))` created by forward substitution, but it ends up being a bit better anyway.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
Interesting OSX x64 [failure](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-77688-merge-6b45f1a3ca9248cb80/System.IO.FileSystem.Watcher.Tests/1/console.5273dde6.log?helixlogtype=result):

```
./RunTests.sh: line 168: 57924 Illegal instruction: 4  "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.IO.FileSystem.Watcher.Tests.runtimeconfig.json --depsfile System.IO.FileSystem.Watcher.Tests.deps.json xunit.console.dll System.IO.FileSystem.Watcher.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
```

**Comment by SingleAccretion** [comment]
> Interesting OSX x64 failure

No dump, sigh. Let's see if it is persistent.

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib 

SPMI failures are due to missing Win-ARM64 collections.

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
> SPMI failures are due to missing Win-ARM64 collections.

This was due to an undetermined failure to upload files. A recollect is in progress (takes ~6 hours). There is a usual one scheduled on Sundays.

**Pull request merged**
