### PR TITLE
signable single file apps on mac

### PR DESCRIPTION
**Pull request by VSadov**
Resolves:https://github.com/dotnet/runtime/issues/3671

After adding bundle data to the singlefile host, we need to patch up the file structure so it would satisfy expectations of codesign.

The approach is basically a copy of @swaroop-sridhar changes in https://github.com/dotnet/core-setup/compare/master...swaroop-sridhar:macsign?expand=1
We are extending the size of string table in `__LINKEDIT` segment to include bundle data.
This makes the bundle data to appear as a large string in a string table in otherwise compliant Mach-O file.

The approach is similar to what `codesign_alocate` itself does for the `-p` option (`"page align the code signature data by padding string table and changing its size"`).

### CODE REVIEW

**Comment by VSadov** [comment]
\azp list

**Comment by VSadov** [comment]
**DO NOT MERGE**. This is blocked on https://github.com/dotnet/runtime/pull/46640

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Review by swaroop-sridhar — APPROVED** [review]

**Comment by VSadov** [comment]
Thanks!!

**Pull request merged**
