### PR TITLE
Fix case of DefaultValue using enum backing type.

### LINKED ISSUE #52116: ShouldSerializeValue for PropertyDescriptor fails for values of underlying enum types
### Description

The `ShouldSerializeValue` method of the `PropertyDescriptor` fails, when - in C# - a `DefaultValue` for a Property of an enum type is not defined with the enum type, but with it's underlying type. For example:

```
    internal class Foo : Component
    {
        [DefaultValue(0)]
        public TestEnum Bar { get; set; }
    }

    internal enum TestEnum
    {
        Value1 = 0,
        Value2 = 1
    }
```

This is even more dramatic in Visual Basic, where the compiler replaces the Enum type by its underlaying type by default, which makes properties of type enum, which have been defined in Visual Basic, never succeed in a `ShouldSerializeValue` call.

```
    <DefaultValue(TestEnum.Value1)>
    Public Property Bar As TestEnum
```

becomes automatically (IL translated to C#):

```
    [DefaultValue(0)]
    public TestEnum Bar
    {
        [CompilerGenerated]
        get
        {
            return _Bar;
        }
        [CompilerGenerated]
        set
        {
            _Bar = value;
        }
    }
```
Background:
When the `DefaultValue` property of a `ReflectPropertyDescriptor` is called, e.g. by calling `ShouldSerializeProperty` of  `PropertyDescriptor`, and then the `DefaultValue` is of Type `Enum` but the value is given of the type of the underlying type, a `NullReferenceException` is thrown and the call fails.

_Making this work and most likely serviced from .NET Core 3.1 on is, amongst other scenarios, critical for the Windows Forms Designer not to crash in those scenarios._ (Which are not niche.)

### Configuration
* All .NET Core/.NET Versions.
* Windows.
* x86, x64, ARM
* No.

### Regression?
No.

### Other information

The error might be here:
https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectPropertyDescriptor.cs#L303

where `toObject` is called with `_defaultValue` instead of the local variable `defaultValue`.

(Thanks @DustinCampbell for helping tracking this down. 
Also @merriemcgaw, @RussKie, @JeremyKuhne, @Pilchie for reference.)

### PR DESCRIPTION
**Pull request by ericstj**
Fixes https://github.com/dotnet/runtime/issues/52116

### CODE REVIEW

**Review by safern — APPROVED** [review]
LGTM

**Review by stephentoub — APPROVED** [review]
Oops. Thanks.

**Review by KlausLoeffelmann — APPROVED** [review]
LGTM, too!

**Comment by ericstj** [comment]
Staging failure is nuget package download issue during workload install:
```
Workload installation failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (pkgs.dev.azure.com:443) 
```

**Comment by DustinCampbell** [comment]
w00t! 🎉

**Pull request merged**
