### PR TITLE
Ensure Vector.Sum uses SSE3, rather than SSSE3, for floating-point

### LINKED ISSUE #54119: Failed System.Numerics.Tests.GenericVectorTests tests on CI
PR: #54101
Build log:
https://dev.azure.com/dnceng/public/_build/results?buildId=1184792&view=ms.vss-test-web.build-test-results-tab&runId=35620188&resultId=132884&paneView=debug

```
System.NullReferenceException : Object reference not set to an instance of an object.
Stack trace
   at System.Numerics.Tests.GenericVectorTests.TestSum[T](Func`2 expected) in /_/src/libraries/System.Numerics.Vectors/tests/GenericVectorTests.cs:line 3176
   at System.Numerics.Tests.GenericVectorTests.SumDouble() in /_/src/libraries/System.Numerics.Vectors/tests/GenericVectorTests.cs:line 3152
```

```
System.NullReferenceException : Object reference not set to an instance of an object.
Stack trace
   at System.Numerics.Tests.GenericVectorTests.TestSum[T](Func`2 expected) in /_/src/libraries/System.Numerics.Vectors/tests/GenericVectorTests.cs:line 3176
   at System.Numerics.Tests.GenericVectorTests.SumSingle() in /_/src/libraries/System.Numerics.Vectors/tests/GenericVectorTests.cs:line 3149
```

cc @zlatanov @tannergooding

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/54119 and was introduced in https://github.com/dotnet/runtime/pull/53527

CC. @zlatanov, @echesakovMSFT

### CODE REVIEW

**Comment by tannergooding** [comment]
This wasn't caught by the ISA tests that were run as those only run for the runtime side tests and only library side tests were added.

I've added a runtime side test, mirroring the other runtime tests for Vector<T>, to help ensure this gets the ISA validation.

**Comment by zlatanov** [comment]
Thanks @tannergooding. Looking at this now I can see that SSSE3 HorizontalAdd is not supported for floats and doubles, but I must have missed it when using it.

I actually tried to see if somehow the macros that are generating the NI_ enums could also have comments generated with them, which would include information for which native types the instruction is supported, but I failed.

For example I think it would be invaluable to have something like:

```c++
/// <summary>Supported for ...</summary>
NI_SSSE3_HorizontalAdd
```

**Comment by tannergooding** [comment]
> For example I think it would be invaluable to have something like:

That information is all in the metadata table here (either an instruction or `INS_invalid`, there are a few cases where `invalid` can still generate something, but those are rare and typically "helper" intrinsics): https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/hwintrinsiclistxarch.h#L348

The expansion of a macro isn't normally visible without explicitly running an explicit compilation step and saving the pre-processor output, so I don't think having a comment would be beneficial.

**Comment by tannergooding** [comment]
ARM64 failures are unrelated.

**Review by echesakov — APPROVED** [review]

**Pull request merged**
