### PR TITLE
JIT: Don't emit nullchecks for 'this' objects

### PR DESCRIPTION
**Pull request by EgorBo**
Just a CI test, the asm-diff is quite big
The only failing test is [GetPinnableReference_WithNullInput_ThrowsNullRef](https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Runtime/tests/System/StringTests.cs#L952-L970) where we emit (by hands) `ldnull` + `call` (not `callvirt`) - not sure it can be reproduced in pure C#.

```
asm.aspnet.run.windows.x64.checked

Total bytes of base: 1412609
Total bytes of diff: 1391234
Total bytes of delta: -21375 (-1.51% of base)
    diff is an improvement.
```
```
asm.benchmarks.run.windows.x64.checked

Total bytes of base: 383978
Total bytes of diff: 382411
Total bytes of delta: -1567 (-0.41% of base)
    diff is an improvement.
```
```
asm.libraries.crossgen.windows.x64.checked

Total bytes of base: 1884112
Total bytes of diff: 1849283
Total bytes of delta: -34829 (-1.85% of base)
    diff is an improvement.
```
```
asm.libraries.crossgen2.windows.x64.checked

Total bytes of base: 2329618
Total bytes of diff: 2290413
Total bytes of delta: -39205 (-1.68% of base)
    diff is an improvement.
```
```
asm.libraries.pmi.windows.x64.checked

Total bytes of base: 1758232
Total bytes of diff: 1746511
Total bytes of delta: -11721 (-0.67% of base)
    diff is an improvement.
```
```
asm.tests.pmi.windows.x64.checked

Total bytes of base: 4839156
Total bytes of diff: 4338207
Total bytes of delta: -500949 (-10.35% of base)   ;; due to Tests.ThousandMoreField
    diff is an improvement.
```
```
asm.tests_libraries.pmi.windows.x64.checked

Total bytes of base: 3871869
Total bytes of diff: 3830039
Total bytes of delta: -41830 (-1.08% of base)
    diff is an improvement.
```
Full diff: https://gist.github.com/EgorBo/4d691b7077ba14a4a3f579dd15a9d932

### CODE REVIEW

**Comment by EgorBo** [comment]
Diff examples:
```csharp
public class TestClass
{
    private char _c;

    public ref readonly char Test1() => ref _c;
}
```
Codegen for `Test1` in Main:
```asm
       3909                 cmp      dword ptr [rcx], ecx
       488D4108             lea      rax, bword ptr [rcx+8]
```
Codegen for `Test1` in this PR:
```asm
       488D4108             lea      rax, bword ptr [rcx+8]
```

**Comment by MichalStrehovsky** [comment]
Technically one can call methods with a null this with reflection, but we probably don't care about those use cases much:

https://twitter.com/MStrehovsky/status/1183447787532443653

**Comment by EgorBo** [comment]
> Technically one can call methods with a null this with reflection, but we probably don't care about those use cases much:
> 
> https://twitter.com/MStrehovsky/status/1183447787532443653

I kept this tweet in mind 🙂 
this PR doesn't fold "this == null" checks btw, only the implicit ones.

**Comment by EgorBo** [comment]
@dotnet/jit-contrib any opinion on that?

**Comment by jakobbotsch** [comment]
You can also end up with `this == null` in C++/CLI, e.g.
```C++
public ref class CppCli
{
    int m_field;

    [MethodImpl(MethodImplOptions::NoInlining)]
    int% Foo()
    {
        Console::WriteLine(this == nullptr);
        return m_field;
    }

    static void Main()
    {
        CppCli^ test = Environment::TickCount > 5 ? nullptr : gcnew CppCli();
        test->Foo() = 5;
    }
};
```

Prints `True` and then throws a null ref exception inside `Foo`. I guess with this change it could access violate on the write in `Main` instead if you had a lot of data before `m_field` so that the runtime did not see it as a null-ref.

**Comment by MichalStrehovsky** [comment]
We're already pretty broken with a null `this` if the class is generic and instantiated over a reference type - even if it doesn't touch its instance state, running with a null this can result in a crash in the VM because we can't get to the generic context (the tweet above has an example with C#, but with C++/CLI you can get to that crash without reflection).

If we don't already have "if an instance method is called with a null `this`, the behavior is undefined" in the ECMA-335 spec, we should probably add it because we already don't support it due to shared generic code.

**Comment by EgorBo** [comment]
Another (my favorite) example is:
```csharp
        ref Guid guid = ref Unsafe.NullRef<Guid>();
        Type hc = guid.GetType();
```
It throws `Fatal error. Internal CLR error. (0x80131506)` in `Release` because JIT assumes byref value types are never null.

**Comment by AaronRobinsonMSFT** [comment]
@EgorBo The C++/CLI case would be a big concern for me. One possible way to start validating this would be to run the WPF test suite against the change. @jkoritzinsky can point you at how that is done.

**Comment by BruceForstall** [comment]
Would this be a breaking change, where users would see a different exception than before?

**Comment by MichalStrehovsky** [comment]
> Prints `True` and then throws a null ref exception inside `Foo`.

Did you run this with CoreCLR?

I made a new desktop project with C++/CLI:

```c++
public ref class CppCli
{
    int m_field;

    [System::Runtime::CompilerServices::MethodImpl(System::Runtime::CompilerServices::MethodImplOptions::NoInlining)]
    void Bar(int% x)
    {
        System::Console::WriteLine("Here");
    }

    [System::Runtime::CompilerServices::MethodImpl(System::Runtime::CompilerServices::MethodImplOptions::NoInlining)]
    int% Foo()
    {
        System::Console::WriteLine(this == nullptr);
        Bar(m_field);
        return m_field;
    }
public:
    static void Main()
    {
        CppCli^ test = System::Environment::TickCount > 5 ? nullptr : gcnew CppCli();
        test->Foo() = 5;
    }
};

int main()
{
    CppCli::Main();

    return 0;
}
```

This one prints:

```
True
Here
```

Then it nullref while trying to write into the Byref in main.

But only on x86.

On x64 it will print:

```
True
```

And then NullRef while trying to get the address of m_field.

I think we have quite a bit of leeway here...

Dereferencing a null is undefined behavior in C++. I don't know about C++/CLI, but C++ devs generally don't do that.

**Comment by jakobbotsch** [comment]
Yes, this was CoreCLR x64. Interesting that we already forego the null-check on desktop x86 here.

> I think we have quite a bit of leeway here...
> 
> Dereferencing a null is undefined behavior in C++. I don't know about C++/CLI, but C++ devs generally don't do that.

I agree, I'm not against doing this optimization, just saying that C++/CLI code can hit this without having to do exotic things.

**Comment by aloraman** [comment]
I'm worried about dynamic codegen in unit tests. Dynamic proxies and mocks are often prefer `.call` over `.callvirt` (or in some case require to use `.call`, e.g. default interface implementations). I feel this optimization can break unit tests for some end users in non-obvious way. E.g. if unit test checks behavior with passing null argument and expects `Assert.Throws<NullReferenceException>(...)` to pass, but instead runtime crashes (because that null argument has been passed into dynamically generated mock, and `.call` was used) - that would be very surprising for user. 
It is just a feeling though, I don't have any specific examples, maybe I'm being overly cautious.

**Comment by AndyAyersMS** [comment]
See also #7924, where I was looking at something similar, but restricted to generic methods.

Would be interesting to have some PMI diffs to get a better sense of overall code size impact. 

And as for perf impact, an unconsumed read likely doesn't impact perf all that much...? But if there are follow-on optimizations like the ones discussed in #7924 ,that might make it more compelling.

**Pull request closed without merging**
