### PR TITLE
Use helpers for implicit casts in importer

### PR DESCRIPTION
**Pull request by SingleAccretion**
Use the implicit casts helpers to simplify code.

Some MinOpts [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=115300&view=ms.vss-build-web.run-extensions-tab) because MinOpts didn't constant-fold the implicit casts, forcing explicit null check insertion.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Review by jakobbotsch — APPROVED** [review]
LGTM, nice cleanup.

**Comment by jakobbotsch** [comment]
Failure was #79439.

**Pull request merged**
