### PR TITLE
Enable Libraries R2R Testing in CI

### PR DESCRIPTION
**Pull request by ivdiazsa**
This PR is a follow-up to #80946. Now that we have `TestReadyToRun` enabled for the appropriate libraries tests (done in the aforementioned PR), we can add it to our CI, so these tests can get run regularly. Currently a WIP.

### CODE REVIEW

**Comment by ivdiazsa** [comment]
@trylek Here's my initial attempt on adding the `TestReadyToRun` legs to the pipelines.

**Comment by trylek** [comment]
Interestingly enough the <code>runtime-extra-platforms</code> is now failing even in NativeAOT legs, at the first glance I don't see how that can be related to Ivan's R2R changes, it looks like some dependency issue, @MichalStrehovsky - do you have any ideas what might be going on?

<pre>
EXEC : error : Failed to load assembly 'SQLitePCLRaw.core' [D:\a\_work\1\s\src\libraries\Microsoft.Extensions.Configuration.Binder\tests\SourceGenerationTests\Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests.csproj::TargetFramework=net8.0]
##[error]EXEC(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Failed to load assembly 'SQLitePCLRaw.core'
  Internal.TypeSystem.TypeSystemException+FileNotFoundException: Failed to load assembly 'SQLitePCLRaw.core'
     at Internal.TypeSystem.ThrowHelper.ThrowFileNotFoundException(ExceptionStringID, String) + 0x30
     at Internal.TypeSystem.ResolutionFailure.Throw() + 0xf8
     at Internal.TypeSystem.Ecma.EcmaModule.GetObject(EntityHandle, NotFoundBehavior) + 0x95
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ResolveHandle(EntityHandle) + 0x1c
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseTypeImpl(SignatureTypeCode) + 0x96
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType(SignatureTypeCode) + 0x43
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseType() + 0x4c
     at Internal.TypeSystem.Ecma.EcmaSignatureParser.ParseFieldSignature() + 0x38
     at Internal.TypeSystem.Ecma.EcmaField.InitializeFieldType() + 0x12a
     at Internal.TypeSystem.MetadataFieldLayoutAlgorithm.ComputeInstanceLayout(DefType, InstanceLayoutKind) + 0x149
     at Internal.TypeSystem.DefType.ComputeInstanceLayout(InstanceLayoutKind) + 0x5d
     at ILCompiler.CompilerTypeSystemContext.EnsureLoadableTypeUncached(TypeDesc) + 0x43c
     at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey) + 0x11
     at ILCompiler.DependencyAnalysis.EETypeNode..ctor(NodeFactory, TypeDesc) + 0x14b
     at ILCompiler.DependencyAnalysis.NodeFactory.CreateNecessaryTypeNode(TypeDesc) + 0xf1
     at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey) + 0x11
     at ILCompiler.DependencyAnalysis.NodeFactory.NecessaryTypeSymbol(TypeDesc) + 0x95
     at ILCompiler.DependencyAnalysis.GenericCompositionNode.GetDehydratableData(NodeFactory, Boolean) + 0x1ee
     at ILCompiler.DependencyAnalysis.DehydratableObjectNode.GetData(NodeFactory, Boolean) + 0x26
     at ILCompiler.DependencyAnalysis.ObjectNode.GetStaticDependencies(NodeFactory) + 0x32
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1) + 0x44
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1) + 0x32
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() + 0xb5
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() + 0x4e
     at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan() + 0x14
     at ILCompiler.Program.<Run>g__RunScanner|3_0(Program.<>c__DisplayClass3_0&) + 0x108
     at ILCompiler.Program.Run() + 0x1519
     at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass206_0.<.ctor>b__0(InvocationContext context) + 0x20c
</pre>

**Pull request closed without merging**
