### PR TITLE
Repoint urls in docs

### LINKED ISSUE #73682: Repoint URL's to docs from corefx to runtime repo
Some comments, on classes primarily related to EventSource/DiagnosticSource, have urls in them that point to docs located in archived corefx repo, perhaps they should be repointed to docs that are at runtime repo? Or is it intended to have docs point to corefx repo?

An alternative would be to extract such docs to separate docs pages at dotnet/docs repo for example rather than having them at corefx/runtime repo.

Here are urls that i found:
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L211
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L249
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L282
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L1760
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticListener.cs#L26
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSource.cs#L14
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventCounter.cs#L13
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/MetadataBuilder.Heaps.cs#L301
https://github.com/dotnet/runtime/blob/6da2046387798432f471036a94b3ea1352bb844b/src/mono/mono/metadata/debug-mono-ppdb.c#L783

### PR DESCRIPTION
**Pull request by N0D4N**
## Summary
Closes #73682
Repoint urls in docs and xmldocs from those that point to archived repos as dotnet/corefx, dotnet/coreclr, dotnet/core-setup so that they point to runtime repo. I also changed urls that point to file in dotnet/diagnostics repo that were moved, and urls that use obsolete default branch name.  
In cases when commit hashes were used as part of url I used most recent commit hash.

## Notes
* I've left links in [FreeBSD building instructions](https://github.com/dotnet/runtime/blob/main/docs/workflow/building/coreclr/freebsd-instructions.md) in place since patching them requires some knowledge about building coreclr and corefx that I don't have.
* I also didn't change docs that point to corefxlab repo, even though it's archived I couldn't find those docs in dotnet/runtime and dotnet/designs repos
https://github.com/dotnet/runtime/blob/384dceb4547d3aa240107dc3fbd4abc4387ced70/docs/coding-guidelines/api-guidelines/System.Memory.md?plain=1#L7-L8
* Also i didn't repoint urls to PRs since it looks like they didn't move to dotnet/runtime
* Also it seems there are some tests that use "obsolete" issue id as part of their filename like [this one](https://github.com/dotnet/runtime/blob/main/src/tests/nativeaot/SmokeTests/DynamicGenerics/GitHub21379.cs), i ignored such files.
* https://github.com/dotnet/coreclr/blob/master/src/zap/ referenced in https://github.com/dotnet/runtime/blob/17154bd7b8f21d6d8d6fca71b89d7dcb705ec32b/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs#L1391 https://github.com/dotnet/runtime/blob/17154bd7b8f21d6d8d6fca71b89d7dcb705ec32b/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunMethod.cs#L552 https://github.com/dotnet/runtime/blob/753d12facef5aa9d7926e3e284bfb40b7197f016/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/Amd64/UnwindInfo.cs#L173 isn't present in runtime repo so references are left as is

* https://github.com/dotnet/runtime/blob/753d12facef5aa9d7926e3e284bfb40b7197f016/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/NativeReader.cs#L296 references code in https://github.com/dotnet/runtime/blob/main/src/coreclr/debug/daccess/nidump.cpp that isn't present there.

* https://github.com/dotnet/runtime/blob/b908ecf514f32c7ba7d59ecc28fa3fdd64a10a1a/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/SignatureDecoder.cs#L315 references removed code it seems, the most close thing i could find is [here](https://github.com/dotnet/runtime/blob/b908ecf514f32c7ba7d59ecc28fa3fdd64a10a1a/src/coreclr/utilcode/util.cpp#L1752), it handles the same case, but logic isn't the same i suppose

* https://github.com/dotnet/runtime/blob/14be2a080974c454bed200dbdaa3fd1293ee530a/docs/project/garbage-collector-guidelines.md?plain=1#L42 references project in dotnet/coreclr which is no longer available

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
LGTM, thanks!
Not sure about the failures. I pushed a minor fix to re run everything.

**Comment by danmoseley** [comment]
Your notes above also seem reasonable. cc @MichalStrehovsky for the AOT links you mention.

**Review by MichalStrehovsky — APPROVED** [review]
> Your notes above also seem reasonable. cc @MichalStrehovsky for the AOT links you mention.

The AOT stuff looks good. The links to deleted code are links to the deleted crossgen1. Crossgen2 devs liked referring to crossgen1 source code in comments. Those comments are only meaningful to those who know what crossgen1 was.

**Comment by danmoseley** [comment]
Thanks @N0D4N

**Pull request merged**
