### PR TITLE
HttpStress: reduce cancellation probability for HTTP 1.1

### LINKED ISSUE #50854: HttpStress: connection failures with HTTP 1.1 -- thousands of server sockets in TIME_WAIT
Currently, the the vast majority of our HttpStress failures are Socket connection failures on HTTP 1.1. (Socket error 10060 running inside, 10061 running outside of Docker):
https://dev.azure.com/dnceng/public/_build/results?buildId=1045441&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=ac0b0b0f-051f-52f7-8fb3-a7e384b0dde9&l=1244
https://gist.github.com/antonfirsov/dc7af2d9cb4213c835a41f59f09a0775#file-type1-txt

While running these tests, there are **thousands** of Kestrel sockets in lingering in `TIME_WAIT`. This may lead to port exhaustion, which I believe explains the CI failures.

It doesn't look like the stress client's [`ClientOperations`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/tests/StressTests/HttpStress/ClientOperations.cs) are doing anything unconventional -- `HttpRequestMessage`-es seem to be properly disposed. 

Things I tried:
- Reducing `-cancelRate` to `0`, but it did not change the amount of lingering sockets
- (Unless I made a mistake in my experiment) After limiting `MaxConnectionsPerServer` to `100` there were still thousands of lingering sockets

I'm not familiar enough with SocketsHttpHandler codebase and Kestrel (or webservers in general), so I can't assess if what I'm seeing is extreme or not in a stress scenario.

@geoffkizer @scalablecory @halter73 @stephentoub thoughts?

### PR DESCRIPTION
**Pull request by antonfirsov**
Fixes #50854 by reducing the number of lingering sockets on the machine by using a lower cancellation rate for HTTP 1.1.

Although 8% worked fine in my local tests, I reduced it further to 5% following the advice in https://github.com/dotnet/runtime/issues/50854#issuecomment-818063421.

### CODE REVIEW

**Review by ManickaP — APPROVED** [review]
Thanks!

**Comment by antonfirsov** [comment]
This change seems to be insufficient on the actual CI machine, converting to draft for further experiments.

**Pull request closed without merging**
