### PR TITLE
Convert JIT/Performance to a merged test group

### PR DESCRIPTION
**Pull request by markples**
See https://github.com/markples/utils/tree/for-PR-dotnet-runtime-85847-others for ILTransform tool.  As usual, I recommend viewing the commit list since it partitions the changes in a more readable way and paying more attention to manual changes.

- [x] Does anything special need to be done for this directory?
- [x] outerloop, extra-platforms, gcstress

### CODE REVIEW

**Review by trylek — APPROVED** [review]
Looks great to me but I must admit I don't have too much of a context on the perf side of these tests.

**Comment by BruceForstall** [comment]
It's useful to keep these tests' source code as close to equivalent to the dotnet/performance repo versions as possible -- at least in the core algorithm part.

**Comment by markples** [comment]
Thank you for all of the quick reviews @trylek!

**Pull request merged**
