### PR TITLE
[release/5.0-preview3] Fixup more package dependencies for Microsoft.Windows.Compatibility

### PR DESCRIPTION
**Pull request by mmitche**
A few more dependencies on removed packages. System.Reflection.Emit*

### CODE REVIEW

**Comment by mmitche** [comment]
@jaredpar @dotnet/runtime-infrastructure Is this a new failure? It looks like cmake is crashing while generating the iOS build. This is required for p3

**Comment by ViktorHofer** [comment]
Those legs were disabled with https://github.com/dotnet/runtime/commit/0375524a91a47ca4db3ee1be548f74bab7e26e76 yesterday. I recommend to cherry-pick this into your PR.

cc @akoeplinger

**Review by safern — APPROVED** [review]

**Comment by safern** [comment]
Can we also do this in master?

**Comment by mmitche** [comment]
Already did: https://github.com/dotnet/runtime/pull/34479

**Pull request merged**
