### PR TITLE
Fix typo in managed port of strong name validation

### LINKED ISSUE #66545: terrafx.interop.windows and Assembly.FullName problem when compile using NativeAOT
### Description

Hello,
when I build a simple program with terrafx using nativeaot. and using GetAssemblies, it makes the exception.

### Reproduction Steps

Program.cs
```C#
using TerraFX.Interop.Windows;
using static TerraFX.Interop.Windows.Windows;
using static TerraFX.Interop.Windows.COINITBASE;
using static TerraFX.Interop.Windows.CLSCTX;
using System.Runtime.InteropServices;

namespace MyApp // Note: actual namespace depends on the project name.
{
    internal unsafe class Program
    {
      
        static void Main(string[] args)
        {
            var assembly = Array.Find(AppDomain.CurrentDomain.GetAssemblies(), z => z.FullName == "ssss");

            Console.WriteLine(WMI("Win32_Processor", "ProcessorId"));

            Console.ReadKey();
        }
        public static string WMI(string wmiClass, string wmiProperty)
        {
            var hresult = CoInitializeEx(null, (uint)COINITBASE_MULTITHREADED);
            if (FAILED(hresult))
                return "";
            hresult = CoInitializeSecurity(
        null,
        -1,
        null,
        null,
        0,
        3,
        null,
        0,
        null
    );
            if (FAILED(hresult))
                return "";
            IWbemLocator* pLoc = null;
            hresult = CoCreateInstance(
        __uuidof<WbemLocator>(),
        null,
        (uint)CLSCTX_INPROC_SERVER,
        __uuidof<IWbemLocator>(),
        (void**)(&pLoc)
    );
            if (FAILED(hresult))
                return "";
            IWbemServices* pServ = null;
            hresult = pLoc->ConnectServer(
                    (ushort*)Marshal.StringToBSTR("ROOT\\CIMV2").ToPointer(),
        null,
        null,
        null,
        0,
        null,
        null,
        &pServ
    );
            if (FAILED(hresult))
                return "";
            hresult = CoSetProxyBlanket(
        (IUnknown*)pServ,
        10,
        0,
        null,
        3,
        3,
        null,
        0
    );
            if (FAILED(hresult))
                return "";
            IEnumWbemClassObject* pEnumerator = null;
            hresult = pServ->ExecQuery(
                (ushort*)Marshal.StringToBSTR("WQL").ToPointer(),
                (ushort*)Marshal.StringToBSTR($"SELECT * FROM {wmiClass}").ToPointer(),
                (int)(WBEM_GENERIC_FLAG_TYPE.WBEM_FLAG_FORWARD_ONLY | WBEM_GENERIC_FLAG_TYPE.WBEM_FLAG_RETURN_IMMEDIATELY),
                null,
                &pEnumerator
            );
            if (FAILED(hresult))
                return "";
            IWbemClassObject* pclsObj = null;
            uint uReturn = 0;

            string result = "";

            while (pEnumerator != null)
            {
                HRESULT hr =
                    pEnumerator->Next((int)WBEM_TIMEOUT_TYPE.WBEM_INFINITE, 1, &pclsObj, &uReturn);
                if (uReturn == 0)
                    break;
                VARIANT vtProp;

                fixed (char* lpString = wmiProperty)
                    hr = pclsObj->Get((ushort*)lpString, 0, &vtProp, null, null);
                string manufacturer = Marshal.PtrToStringBSTR((IntPtr)vtProp.bstrVal);

                //hr = pclsObj->Get(L"Product", 0, &vtProp, 0, 0);
                //string product = W2A(vtProp.bstrVal);
                //hr = pclsObj->Get(L"SerialNumber", 0, &vtProp, 0, 0);
                //string serialNumber = W2A(vtProp.bstrVal);

                result = manufacturer;

                VariantClear(&vtProp);

                pclsObj->Release();
                break;
            }
            pServ->Release();
            pLoc->Release();
            pEnumerator->Release();
            CoUninitialize();
            return result;
        }
    }
}
```

```XML
<Directives>
	<Application>

		<Assembly Name="TerraFx.Interop.Windows" Dynamic="Required All"  />

	</Application>
</Directives>
```

### Expected behavior
GetAssemblies used in reactiveui with avalonia and I want to get the output of my processor id in my project
[teobugslayer/AvaloniaCoreRTDemo#17](https://github.com/teobugslayer/AvaloniaCoreRTDemo/issues/17)

### Actual behavior

```
Unhandled Exception: System.Security.SecurityException: Invalid assembly public key.
   at WMIComWrapper!<BaseAddress>+0x2396a3
   at System.Reflection.AssemblyName.get_FullName() + 0x8a
   at WMIComWrapper!<BaseAddress>+0x29d5df
   at MyApp.Program.<>c.<Main>b__0_0(Assembly) + 0x30
   at System.Array.Find[T](T[], Predicate`1) + 0x71
   at MyApp.Program.Main(String[]) + 0xca
   at WMIComWrapper!<BaseAddress>+0x38d137
   at WMIComWrapper!<BaseAddress>+0x38d1c5

```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #66545

### CODE REVIEW

**Comment by jkotas** [comment]
@vsadov This is a bug in the managed port of AssemblyName. It is affecting all runtimes now that we have switched to managed implementation of the AssemblyName everywhere.

I was actually thinking about deleting this strong name key validation instead. It is useless in CoreCLR. CoreCLR can treat the strong name key as opaque blob. What do you think?

**Review by stephentoub — APPROVED** [review]

**Comment by VSadov** [comment]
> I was actually thinking about deleting this strong name key validation instead. It is useless in CoreCLR. CoreCLR can treat the strong name key as opaque blob. What do you think?

The validation does not seem to be very expensive. We basically sanity-check the size and hash/alg IDs.
My concern is that once we relax the validation, more cases will become valid and may potentially break some tool or whatever took dependency on these constraints that we check now.
If there is not a lot to gain by relaxing, but there is some, even though low, probability of breaking, maybe we should just keep it?

**Review by VSadov — APPROVED** [review]
LGTM. Thanks!

**Comment by jkotas** [comment]
@VSadov Have you just created the `area-runtime` label? The issue automation expects to have all `area-` labels associated with owners in https://github.com/dotnet/runtime/blob/main/docs/area-owners.md .

**Comment by jkotas** [comment]
All failures are timeouts. Helix running out of capacity?

**Comment by teo-tsirpanis** [comment]
FYI `area-runtime` came from issues transferred from ASP.NET Core. (https://github.com/dotnet/runtime/issues/62032#issuecomment-1042913605)

**Comment by VSadov** [comment]
Yes. I could not place this in a particular runtime, since this is in a shared component (so not strictly coreclr or mono or NativeAOT), then I noticed `area-runtime` and used it. It was already in the list.

**Pull request merged**
