### PR TITLE
Reenable C4242 and C4244 warnings in libunwind

### LINKED ISSUE #99471: SDL signoff requirements - enable MSVC warnings C4242 and C4244 (libunwind)
> __Please prioritize this work.__ We want to address BinSkim alerts early in the development cycle.

Per [the SDL guidelines](https://liquid.microsoft.com/Web/Object/Read/ms.security/Requirements/Microsoft.Security.SystemsADM.10086) (MSFT internal only), C/C++ warning **C4242** and **C4244** are required to be enabled, and fixing violations of it is mandatory.

In **src/native/external/libunwind_extras/CMakeLists.txt**, we also need to delete these two lines:

https://github.com/dotnet/runtime/blob/1e2fdb51249733756b6b52a00ab3843de8d65927/src/native/external/libunwind_extras/CMakeLists.txt#L143-L144

We will need to make changes to our local copy of libunwind as part of this. See the "What about third-party code?" section below.

Thanks for your assistance!

## Quick FAQ

__What code is bound to this requirement?__

This affects only _production_ code. Production code is generally defined as code which ships as part of the product and which runs on customer machines or which manages infrastructure, such as our build labs. Unit and functional test projects are not considered production code.

__Does this need to be backported?__

No backporting plans at this time. If actual bugs are found during this process, individual product teams have discretion to selectively backport into the next downlevel servicing vehicle.

__What about third-party code?__

This requirement applies to all code that MSFT builds from source, regardless of its provenance. Ideally any changes that we make to local forked copies can be submitted upstream as a PR so that the wider ecosystem can enjoy their benefits.

The recommended pattern - and what we did with zlib a while back - is to create a .patch file which contains our local fixes to libunwind, then commit this .patch file as part of the same PR where we make the changes. See https://github.com/dotnet/runtime/pull/91245 for an example of how this was done.

If this is impractical, exceptions to this requirement can be sought on an as-needed basis. However, exceptions are: (a) not guaranteed to be granted; and (b) time-constrained. The exception process is not intended to provide a permanent deferral of this work. Please contact the _fxsecurity_ alias if an exception is needed.

__What about C# and other languages?__

This requirement only affects C/C++ code. Requirements for other languages will be filed as separate issues.

### LINKED ISSUE #100207: C4242 error when compiling CoreCLR on Windows with -msbuild
### Description

Compiling with the `-msbuild` flag fails with many C4242 errors in libunwind.

### Reproduction Steps

On commit 4e0d5d4bb45ecd9a74f651a0682b8d5371c9695b

```
build.cmd -s clr -c debug -msbuild
```

### Expected behavior

Compiles successfully. Note that that compiling with Ninja works fine:

```
build.cmd -s clr -c debug -ninja
```

### Actual behavior

Many errors like this:

> src\native\external\libunwind\include\libunwind_i.h(342,13): error C4242: '=': conversion from 'ssize_t' to 'int', possible loss of data [artifacts\obj\external\libunwind\libunwind_xdac.vcxproj]
    (compiling source file 'src/native/external/libunwind/src/os-linux.c')

### Regression?

Presumably this has something to do with #99470.

### Known Workarounds

_No response_

### Configuration

* Visual Studio 2022 v17.9.4
* cmake version 3.28.0
* Windows 11 10.0.22631.3296
* Windows SDK version 10.0.22621.0

### Other information

It looks like the intention was to not enable this warning for libunwind:

https://github.com/dotnet/runtime/blob/6c685e3302ebdc2aeb008a40ff475d3d3b9f2a78/src/native/external/libunwind_extras/CMakeLists.txt#L143

One thing I notice is that `eng\native\configurecompiler.cmake` [turns this warning on](https://github.com/dotnet/runtime/blob/6c685e3302ebdc2aeb008a40ff475d3d3b9f2a78/eng/native/configurecompiler.cmake#L846) guarded by `if (MSVC)` while `src/native/external/libunwind_extras/CMakeLists.txt` tries to turn this off guarded by `if(CLR_CMAKE_HOST_WIN32)`. I'm not enough of an expert on CMake to know if this is a problem or not.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #99471 
Fixes #100207

Big thanks to @filipnavara for doing this.

Will create upstream ([libunwind](https://github.com/libunwind/libunwind)) patch after confirmation we are clean.

### CODE REVIEW

**Comment by am11** [comment]
Looks great! :)

Few errors showing up in the CI:

```
  D:\a\_work\1\s\src\native\external\libunwind\src\aarch64\Gstash_frame.c(57): error C4242: 'function': conversion from 'unw_word_t' to 'long', possible loss of data
  D:\a\_work\1\s\src\native\external\libunwind\src\aarch64\Gstash_frame.c(63): error C4242: 'function': conversion from 'unw_word_t' to 'long', possible loss of data
  D:\a\_work\1\s\src\native\external\libunwind\src\aarch64\Gstash_frame.c(69): error C4242: 'function': conversion from 'unw_word_t' to 'long', possible loss of data
  D:\a\_work\1\s\src\native\external\libunwind\src\aarch64\Gstash_frame.c(75): error C4242: 'function': conversion from 'unw_word_t' to 'long', possible loss of data
  D:\a\_work\1\s\src\native\external\libunwind\src\dwarf\Gexpr.c(369): error C4242: 'function': conversion from 'unw_word_t' to 'int', possible loss of data
  D:\a\_work\1\s\src\native\external\libunwind\src\dwarf\Gparser.c(885): error C4242: '=': conversion from 'unw_word_t' to 'unw_regnum_t', possible loss of data
```

> Will create upstream ([libunwind](https://github.com/libunwind/libunwind)) patch after confirmation we are clean.

When upstream PR is created, please include its reference in <kbd>src/native/external/libunwind-version.txt</kbd> in this PR's branch.

**Comment by AustinWise** [comment]
This should also fix #100207.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by AaronRobinsonMSFT** [comment]
@am11 if you could also take another pass at this, I would be most appreciated.

**Review by filipnavara — APPROVED** [review]
Thanks for wrapping this up! LGTM

**Comment by am11** [comment]
@AaronRobinsonMSFT, looks good but can you please open a PR upstream and reference it in version file? We have been following that pattern for all similar PRs.

**Pull request merged**
