### PR TITLE
Avoid hardcoded illink.tasks TFM

### PR DESCRIPTION
**Pull request by ViktorHofer**
Replaces https://github.com/dotnet/runtime/pull/109619

We made a similar change recently in arcade to not use the TFM but a normalized value of the TargetFrameworkIdentifier property for tools packages.

### CODE REVIEW

**Comment by am11** [comment]
Nice! It'll also needs https://github.com/am11/runtime/commit/fd067c5e6cfc262dc5b1a69f68e4e957a89d2741.

**Comment by am11** [comment]
Nice! It'll also need https://github.com/am11/runtime/commit/fd067c5e6cfc262dc5b1a69f68e4e957a89d2741.

**Comment by ViktorHofer** [comment]
Oh right, we don't need that with this change anymore. Perfect :)

**Review by akoeplinger — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@am11 I tried to directly apply your patch to keep you as the committer but GH didn't let me (corrupt file at L...). So I manually applied it.

**Comment by am11** [comment]
No worries. I'm just happy to see another hardcoded platform list going away. 🙂

**Comment by am11** [comment]
Another piece of the puzzle: https://github.com/dotnet/runtime/compare/main...am11:runtime:patch-19

**Review by sbomer — APPROVED** [review]
Nice, thank you!

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
/ba-g wasm failures are note related to the ILLink changes

**Pull request merged**
