### PR TITLE
Disable failing XxHash3Tests on s390x

### PR DESCRIPTION
**Pull request by akoeplinger**
See https://github.com/dotnet/runtime/issues/78043

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by stephentoub** [comment]
Is this still necessary with https://github.com/dotnet/runtime/pull/78084?

**Comment by akoeplinger** [comment]
I triggered the s390x build there so let's see

**Comment by akoeplinger** [comment]
It worked, closing this one.

**Pull request closed without merging**
