### PR TITLE
Reenable HugeExpr Test on macOS ARM64

### PR DESCRIPTION
**Pull request by ivdiazsa**
Issue #62881 was not reproducible. It had been open for a while, so it may have been fixed at some point. This PR reenables the test.

### CODE REVIEW

**Review by mangod9 — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Just to confirm but you tested this under R2R right? We (the JIT team) recently discussed that we have different or no thresholds in R2R, this could be one of the tests where the JIT compilation during R2R hits some quadratic behavior due to that.

**Comment by ivdiazsa** [comment]
> Just to confirm but you tested this under R2R right? We (the JIT team) recently discussed that we have different or no thresholds in R2R, this could be one of the tests where the JIT compilation during R2R hits some quadratic behavior due to that.

Thanks for the observation Jakob. I had not but I've spent some time now trying different scenarios, and I still can't get it to repro. Here's what I tried:
- Vanilla
- Crossgen2'd without Composite
- Crossgen2'd with Composite
- The same three with `DOTNET_ReadyToRun=1`, `DOTNET_TieredCompilation=0`, and other permutations.

It is worth mentioning that in between each of these experiments, I rebuilt the test from scratch. It also surprised me how much faster it was with Crossgen2 applied. Is this reasonable? Or did I miss other scenarios where it can potentially repro?

**Review by jakobbotsch — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Sounds like you've covered the bases.

**Comment by ivdiazsa** [comment]
Thanks a lot Jakob!

**Pull request merged**
