### PR TITLE
[mono] Fix the handling of jit icall wrappers in mono_aot_method_hash (), the name might be different at runtime if DISABLE_JIT is set.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
The issue is caused by https://github.com/dotnet/runtime/pull/48150.

**Review by filipnavara — APPROVED** [review]
Tested manually with the iOS sample app in full AOT mode. The startup now works again on device and lldb confirms the correct AOT data are looked up.

**Review by spouliot — APPROVED** [review]

**Review by lambdageek — APPROVED** [review]

**Review by dalexsoto — APPROVED** [review]

**Comment by spouliot** [comment]
@vargaz after the merge, we'll need a backport to the preview 3 branch. thanks!

**Comment by CoffeeFlux** [comment]
cc: @marek-safar re: backport

**Pull request merged**
