### PR TITLE
Break ExtensionsTests.cs into one file per type tested

### PR DESCRIPTION
**Pull request by bartonjs**
This change is essentially just style, no tests have been altered, added, or removed.

The tests that were about a particular extension have moved to a class named
for the type being tested (with the X509 prefix and Extension suffix omitted).
Now that the type tested is inferred from the name, the method names were
adjusted accordingly. e.g. ExtensionsTests.KeyUsageExtension_CrlSign is now
KeyUsageTests.EncodeDecode_CrlSign

The one test that wasn't about a single extension is now in the file
ExtensionsTests\ComprehensiveTests.cs, as it checks all of the extensions,
and the order of the extensions, from an existing certificate.

### CODE REVIEW

**Review by vcsjones — APPROVED** [review]

**Comment by vcsjones** [comment]
An afterthought, but should these new files be in System.Security.Cryptography/tests? Or keep everything together until it all moves at once?

**Comment by bartonjs** [comment]
Hmm. They... could... move.

`System.Security.Cryptography\tests\X509Certificates\ExtensionTests\...` and `namespace System.Security.Cryptography.Tests.X509Certificates.ExtensionTests`?

**Comment by vcsjones** [comment]
> System.Security.Cryptography\tests\X509Certificates\ExtensionTests\... and namespace System.Security.Cryptography.Tests.X509Certificates.ExtensionTests?

Makes sense to me. The X500DNBuilder tests are there already.

**Comment by bartonjs** [comment]
Hm.  Since they use `TestData` that feels like a slightly complicated move.  I think I'll just let them get unified in with everything else later.

**Pull request merged**
