### PR TITLE
Fix condition in PAL's SetThreadDescription

### PR DESCRIPTION
**Pull request by am11**
Regressed in #108370 refactoring.

### CODE REVIEW

**Review by janvorli — APPROVED** [review]
LGTM, thank you for a quick fix!

**Comment by am11** [comment]
Thank you for the catch. Looks like we don't have test coverage for this path. 🥲

**Comment by jkotas** [comment]
Looks like another bug has been hiding behind the first one. This is failing when setting the name of PAL WorkerThread now.

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by jkotas** [comment]
/ba-g Known issues - mac queue deprecation, CLR_Tools timeout (#109520)

**Pull request merged**
