### PR TITLE
Add NetworkError.TimedOut, rename Unknown to Other

### PR DESCRIPTION
**Pull request by antonfirsov**
- Adds `NetworkError.TimedOut`
- Renames `Unknown` to `Other` assuming my proposal gets accepted, will revert if not
- Improves exception message

Will add a case for `TimedOut` as soon as the Connection PR gets merged. (Based on local test it gets translated fine.)

### CODE REVIEW

**Review by scalablecory — APPROVED** [review]

**Review by geoffkizer — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Comment by geoffkizer** [comment]
@antonfirsov The failure in System.Net.Requests.Tests looks related, though I'm not sure how your change would affect this... can you take a look?

**Comment by geoffkizer** [comment]
That also could have been caused by the recent ConnectionFactory PR.

**Comment by ManickaP** [comment]
The problem is in missing mapping in https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Requests/src/System/Net/WebException.cs#L74

@antonfirsov if you're afk, I can try to fix it.

**Comment by antonfirsov** [comment]
OuterLoop test failures are unrelated. Opened new issues: #40926, #40927

**Pull request merged**
