### PR TITLE
Updating JitInterface to support Vector512.

### PR DESCRIPTION
**Pull request by DeepakRajendrakumaran**
Checking if tests pass

### CODE REVIEW

**Comment by DeepakRajendrakumaran** [comment]
@tannergooding @BruceForstall

**Review by BruceForstall — APPROVED** [review]

**Review by tannergooding — COMMENTED** [review]
LGTM.

**Comment by BruceForstall** [comment]
@DeepakRajendrakumaran The superpmi collection for this change succeeded and is available.

**Comment by DeepakRajendrakumaran** [comment]
> @DeepakRajendrakumaran The superpmi collection for this change succeeded and is available.

Thanks for merging. I've updated the PR

**Pull request merged**
