### PR TITLE
Pass RID to msbuild task

### PR DESCRIPTION
**Pull request by am11**
First commit is reverting #103497, second commit has the fix for official build.

### CODE REVIEW

**Comment by am11** [comment]
@MichalStrehovsky, I was able to repro it locally (with command from https://github.com/dotnet/runtime/pull/103469#issuecomment-2167672451).

**Comment by MichalStrehovsky** [comment]
Thanks! I'll test this out by doing an official build from a branch once the infra is stable enough, but for now marking no merge.

@jkoritzinsky could you please have a look at the [ddf4666](https://github.com/dotnet/runtime/pull/103508/commits/ddf466609fcab4acdb9dae0f9a54da7c42f49310) commit? The rest was already reviewed and is a revert of a revert.

**Comment by am11** [comment]
runtime builds are now flowing normally through the SDK. No rush, but would be good to avoid conflicts if we can, as testing it requires spending time on multiple VMs / containers (and at some point I'd like to restart my computer 😅).

**Review by jkoritzinsky — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
/ba-g binaryformatter CI issues were fixed in the meantime and is unrelated

**Comment by MichalStrehovsky** [comment]
Thank you! I'll watch the official builds...

**Pull request merged**
