### PR TITLE
Return exit code 1 in android test runner if a test failed

### PR DESCRIPTION
**Pull request by safern**
In order to fail the build we need to return a failing exit code if there were test failures.

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]
Looks good but it seems we don't do this in the AppleTestRunner. I guess xharness interprets the failures there?

**Review by MattGal — APPROVED** [review]

**Comment by safern** [comment]
The Apple Xharness command is parsing the log stream and looking to see if the log contains “[FAIL]” and if it does then it returns 1. 

Android command doesn’t do that, it doesn’t read the log at all instead it relies on the instrumentation returning the correct error code.

**Comment by akoeplinger** [comment]
> The Apple Xharness command is parsing the log stream and looking to see if the log contains “[FAIL]” and if it does then it returns 1.

Ok, that sounds pretty brittle, we should return a proper exit code. @EgorBo

**Comment by safern** [comment]
> Ok, that sounds pretty brittle, we should return a proper exit code. @EgorBo

Yeah I agree.

Here is the code that handles that: 
https://github.com/dotnet/xharness/blob/a8346dcc301875ef9cede0500f3736a73dbbc3cf/src/Microsoft.DotNet.XHarness.iOS.Shared/TestReporter.cs#L318-L322

We always return 0 from the AppleTestRunner: https://github.com/dotnet/runtime/blob/45af31b2dfe778603c77c7d154f5aa1b6378cd21/src/mono/msbuild/AppleTestRunner/AppleTestRunner.cs#L70-L91

But we already listen to the `TestCompleted` event, so we could just set returnCode to 1 when the test failed and then change XHarness iOS command to listen to the exit code. I guess we should open and issue in xharness.

**Pull request merged**
