### PR TITLE
[mono] Fix support for generic custom attributes.

### LINKED ISSUE #77047: Blazor: Generic attributes do not work in Mono
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

At the moment I am running a C# 10 .NET 6 Blazor Webassembly app with EnablePreviewFeatures so I can use generic attributes. Unfortunately when running the app, I get the following error:
`dotnet..w98fhuowzh.js:1430 * Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/custom-attrs.c:2433`

which leads to this code in the Mono repository: https://github.com/mono/mono/blob/main/mono/metadata/custom-attrs.c#L2451

Apparently generic attributes are not supported at the moment in Mono. And even won't be supported in .NET 7, here is the issue: https://github.com/dotnet/runtime/issues/56887

I have the following questions:

- Shouldn't this be implemented in Mono for .NET 7, because .NET 7 will support generic attributes?
- I guess this is the runtime crashing. I don't know which part of the code crashes now because I don't see a stacktrace. How can I discover what part of my code causes this error?
- My generic attributes are only used for source generation. Is there a way to exclude the attributes in the IL output? For example by putting the attribute in a different file (partial) and excluding the file somehow?

### Expected Behavior

The Mono runtime can handle generic attributes.

### Steps To Reproduce

I don't know how I can reproduce this problem as it happens in the Mono runtime and not on the IL-level.

### Exceptions (if any)

* Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/custom-attrs.c:2433

### .NET Version

6.0.402

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/dotnet/runtime/issues/77047.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Do we need a regression test? It would contribute to #73735.

**Comment by MichalStrehovsky** [comment]
> The test seems to fail on nativeaot.

Not completely surprised. This used to be a compiler crash until very late in RC1 when System.Reflection.Metadata finally fixed a bug around this leaving no runway in 7.0 to look at this. I added an ActiveIssue.

**Comment by am11** [comment]
Can we delete https://github.com/dotnet/runtime/blob/52eed7dc3912594631dfecca56da3057bec52ba6/src/tests/issues.targets#L1363 as part of this PR?

**Comment by vargaz** [comment]
Removed the added test and reenabled the existing ones.

**Comment by vargaz** [comment]
Failure is 
https://github.com/dotnet/runtime/issues/78290

**Comment by am11** [comment]
`.targets` change got lost after the rebase.

**Review by lewing — APPROVED** [review]

**Review by am11 — APPROVED** [review]
Thanks. It also fixes #56887. 👍

**Comment by lewing** [comment]
should we backport this?

**Comment by vargaz** [comment]
Its low risk.

**Comment by marek-safar** [comment]
If it's low risk then we should.

**Comment by vargaz** [comment]
It did seems to cause a small number of perf regressions:
https://github.com/dotnet/runtime/issues/78821

**Pull request merged**
