### PR TITLE
[HTTP/3] Reenable ResponseCancellation_ServerReceivesCancellation

### LINKED ISSUE #56194: Failure test System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.ResponseCancellation_ServerReceivesCancellation
Run: [runtime 20210722.80](https://dev.azure.com/dnceng/public/_build/results?buildId=1253976&view=ms.vss-test-web.build-test-results-tab&runId=37212094&resultId=184464&paneView=debug)
Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408

- System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.ResponseCancellation_ServerReceivesCancellation(type: Dispose)
```
**Error message:**
```
System.AggregateException : One or more errors occurred. (One or more errors occurred. (The operation has timed out.)) (One or more errors occurred. (Stream aborted by peer (4294967295).))
---- System.AggregateException : One or more errors occurred. (The operation has timed out.)
-------- System.TimeoutException : The operation has timed out.
---- System.AggregateException : One or more errors occurred. (Stream aborted by peer (4294967295).)
-------- System.Net.Quic.QuicStreamAbortedException : Stream aborted by peer (4294967295).


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 80
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 49
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ResponseCancellation_ServerReceivesCancellation(CancellationType type) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 544
--- End of stack trace from previous location ---
----- Inner Stack Trace #1 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass12_0.<<ResponseCancellation_ServerReceivesCancellation>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 512
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 63
----- Inner Stack Trace #2 (System.AggregateException) -----

----- Inner Stack Trace -----
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleWriteStartState(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 328
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync(ReadOnlyMemory`1 buffer, Boolean endStream, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 256
   at System.Net.Test.Common.Http3LoopbackStream.SendFrameHeaderAsync(Int64 frameType, Int32 payloadLength) in /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 149
   at System.Net.Test.Common.Http3LoopbackStream.SendFrameAsync(Int64 frameType, ReadOnlyMemory`1 framePayload) in /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 155
   at System.Net.Test.Common.Http3LoopbackStream.SendHeadersFrameAsync(IEnumerable`1 headers) in /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 109
   at System.Net.Test.Common.Http3LoopbackStream.SendResponseHeadersAsync(HttpStatusCode statusCode, IEnumerable`1 headers) in /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs:line 252
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass12_0.<<ResponseCancellation_ServerReceivesCancellation>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs:line 486
```

### PR DESCRIPTION
**Pull request by rzikm**
Since #57156 enforced sending RequestCancelled HTTP response code when disposing the stream, we no longer need to check for the 0xffffffff error code.

Fixes #56194

### CODE REVIEW

**Comment by CarnaViire** [comment]
This test sometimes timed out before -- just to double check, have you tried running it in a tight loop for some time, to be sure it doesn't reproduce anymore?

**Comment by rzikm** [comment]
I have run about 200 iterations on a VM similar to what we use on CI and this particular test did not fail.

**Comment by rzikm** [comment]
CI Failures are:
- https://github.com/dotnet/runtime/issues/67349
- https://github.com/dotnet/runtime/issues/66970

**Review by ManickaP — APPROVED** [review]
LGTM if it runs, thanks!

**Comment by rzikm** [comment]
Lots of unrelated CI failures:
- https://github.com/dotnet/runtime/issues/67349
- https://github.com/dotnet/runtime/issues/66970
- LibraryImportGenerator.Tests
- Microsoft.Bcl.AsyncInterfaces.Tests
- System.Text.RegularExpressions.Tests
- and other.

**Pull request merged**
