### PR TITLE
React to API Compat bug fix around attribute diffing in members

### PR DESCRIPTION
**Pull request by safern**
There was a regression introduced in API Compat a couple of months ago when adding a new feature, causing Attributes to not be diff'd for TypeMembers (methods, properties, fields, etc). 

This reacts to fixing that: https://github.com/dotnet/arcade/pull/7376. This depends on that PR to be merged and produce a new version of API Compat and consume it, so at the moment the build will fail. 

It seems like there was a lot of attribute updates from .NET 5.0 to .NET 6.0. I've baselined those errors here but please let me know if any of them shouldn't be baselined and instead fixed.

cc: @vitek-karas @eerhardt @joperezr for the differences in the linker attributes

cc: @jeffhandley @buyaa-n for the differences in OS attributes.

cc: @ericstj for general review.

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
:shipit:

**Review by vitek-karas — APPROVED** [review]

**Comment by safern** [comment]
@dotnet/dnceng workitem failed when reporting test results to azure devops.

```
Found results file /datadisks/disk1/work/A4E90908/w/AB2708A3/uploads/xharness-output/testResults.xml with format xunit
Worker 7: uploaded 1000 results
Worker 4: uploaded 1000 results
Worker 3: uploaded 1000 results
Worker 6: uploaded 1000 results
Worker 1: uploaded 1000 results
Worker 5: uploaded 1000 results
Worker 0: uploaded 1000 results
Worker 8: uploaded 1000 results
Worker 7: uploaded 2000 results
Worker 1: uploaded 2000 results
Worker 3: uploaded 2000 results
Worker 5: uploaded 2000 results
Worker 0: uploaded 2000 results
Worker 4: uploaded 2000 results
Worker 6: uploaded 2000 results
Worker 9: uploaded 1000 results
Worker 8: uploaded 2000 results
Worker 7: uploaded 3000 results
Worker 8: uploaded 3000 results
Worker 6: uploaded 3000 results
Worker 5: uploaded 3000 results
Worker 1: uploaded 3000 results
Worker 3: uploaded 3000 results
Worker 4: uploaded 3000 results
Worker 9: uploaded 2000 results
Worker 0: uploaded 3000 results
Worker 7: uploaded 4000 results
Worker 6: uploaded 4000 results
Worker 8: uploaded 4000 results
Worker 3: uploaded 4000 results
Worker 1: uploaded 4000 results
Worker 5: uploaded 4000 results
Worker 0: uploaded 4000 results
Worker 4: uploaded 4000 results
Worker 7: uploaded 5000 results
Worker 9: uploaded 3000 results
Worker 3: uploaded 5000 results
Worker 8: uploaded 5000 results
Worker 1: uploaded 5000 results
Worker 0: uploaded 5000 results
Worker 5: uploaded 5000 results
Worker 4: uploaded 5000 results
Worker 7: uploaded 6000 results
Worker 9: uploaded 3639 results
Worker 2: uploaded 1000 results
Worker 6: got error: Traceback (most recent call last):
  File "/datadisks/disk1/work/A4E90908/p/reporter/run.py", line 44, in run
    self.__process(item)
  File "/datadisks/disk1/work/A4E90908/p/reporter/run.py", line 34, in __process
    self.publisher.upload_batch(batch)
  File "/datadisks/disk1/work/A4E90908/p/reporter/azure_devops_result_publisher.py", line 35, in upload_batch
    self.publish_results(test_case_results, test_name_order, results_with_attachments)
  File "/datadisks/disk1/work/A4E90908/p/reporter/azure_devops_result_publisher.py", line 70, in publish_results
    published_results = test_client.add_test_results_to_test_run(list(test_case_results), self.team_project, self.test_run_id)  # type: List[TestCaseResult]
  File "/home/helixbot/.azdo-env/lib/python3.6/site-packages/azure/devops/v5_1/test/test_client.py", line 679, in add_test_results_to_test_run
    content=content)
  File "/home/helixbot/.azdo-env/lib/python3.6/site-packages/azure/devops/client.py", line 104, in _send
    response = self._send_request(request=request, headers=headers, content=content, media_type=media_type)
  File "/home/helixbot/.azdo-env/lib/python3.6/site-packages/azure/devops/client.py", line 68, in _send_request
    self._handle_error(request, response)
  File "/home/helixbot/.azdo-env/lib/python3.6/site-packages/azure/devops/client.py", line 272, in _handle_error
    status_code=response.status_code))
azure.devops.exceptions.AzureDevOpsClientRequestError: Operation returned an invalid status code of 503.
```

**Review by buyaa-n — APPROVED** [review]
LGTM

**Comment by riarenas** [comment]
@safern the azdo problem is being tracked by https://github.com/dotnet/core-eng/issues/13026. We also have an FR issue to add retries to this code path to guard against Azdo's 503s: https://github.com/dotnet/arcade/issues/7371

**Pull request merged**
