### PR TITLE
[release/8.0-staging] [mono][jit] Fix passing of byref arguments in m…

### PR DESCRIPTION
**Pull request by vargaz**
Backport of https://github.com/dotnet/runtime/pull/97721 to release/8.0-staging

## Customer Impact

- [x] Customer reported
- [ ] Found internally

A customer reported an [issue](https://github.com/dotnet/runtime/issues/97625) where they were calling `Sum` or `Average` on a List type of ~20K items resulting in a crash with an unclear stacktrace. After triaging, we noticed the runtime was not properly dereferencing byref values. We went in and fixed the glitch.

## Regression

- [x] Yes
- [ ] No

## Testing

Regression test added on CI to make sure this usage passes.

Also manually tested .Sum in a foreach and it works as expected.

## Risk

Low

### CODE REVIEW

**Comment by lambdageek** [comment]
@vargaz will you backport the test to 8.0, also?

**Review by lambdageek — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
approved.  we will take for consideration in 8.0.x

**Pull request merged**
