### PR TITLE
Use highest thread priority in linux

### LINKED ISSUE #49317: GC does not release memory easily on kubernetes cluster in workstation mode
### Description

* Application is a simple Api for up/download of (large) files from blob storage
* Deployed on kubernetes cluster
* GC in workstation mode as we need memory to be released for monitoring, scaling etc.
* In VS locally this works just fine
    * Directly or few minutes after 1 GB download memory is released
    * It is always a `Generation 2G` collection, smaller generations do not release
image
* However, on the cluster memory can stay up for hours:
alt text

### Configuration

* .Net Core 3.1 App
* Running in a docker container with 2Gi memory limit
* AKS cluster, machines with 4 cores 16GB Ram
* `htop` inside container:
image

### Other information

* This option looks promising: https://docs.microsoft.com/de-de/dotnet/core/run-time-config/garbage-collector#high-memory-percent
* But it doesn't work, seems only available for .Net Core 5.x?

### PR DESCRIPTION
**Pull request by ntovas**
Trying to fix #49317

I believe the fact that it is not clearly communicated that the gc in other envs besides windows **doesn't** run in high priority have made a lot of teams to try to debug issues produced by this fact.

Same facts as this https://github.com/dotnet/runtime/pull/89682 applies for the author.

### CODE REVIEW

**Comment by mangod9** [comment]
Hello @ntovas, thanks for your contribution here. Have you validated whether this change actually has any material impact on memory utilization in your (or other) scenarios?

**Comment by ntovas** [comment]
Hello @mangod9,
It is based on the assumption than on a very thread hungry app, like our case, priority will help gc to complete tasks faster, that's why on windows we didn't face similar problems.
We are trying to find a way to build a runtime with this changes that we will be able to deploy on a traffic heavy environment, because it is very hard for us to completely reproduce our case with mocked data/traffic.
From my understanding it may be required to reduce heaps, to a lower number that the core count, but we are ready to test a lot of configurations, if they seem plausible improvements.

**Comment by mangod9** [comment]
cool sounds good. Thanks for the due diligence.

**Comment by janvorli** [comment]
@ntovas you can easily build a libcoreclr.so with your change and do a drop in replacement in your environment to verify its effect. Here is how to do that:
* Find the commit hash of the libcoreclr.so you are currently using in your production using `strings /path/to/libcoreclr.so | grep "@(#)"`. This will print out the commit hash
* Check out dotnet/runtime repo at the hash you've found
* In the root of the repo, run `./build.sh clr+libs -c Release -rc Release`
* The libcoreclr.so to use is in artifacts/bin/coreclr/linux.x64.Release/libcoreclr.so. You can just copy it over the one that you have on our production systems, since it was built from the same commit, it should just work.

Note: You need to build it on a distro that is the same as the one you are using in production or on a distro that's based on the same libc (glibc or MUSL) with a version that's the same or less than the one on your production distro. On glibc based distros, you can run `ldd --version` to find out the glibc version.
Please let me know if you need any additional guidance with the build.

**Comment by Maoni0** [comment]
as a note, since we do not check the return value of calling `GCToOSInterface::BoostThreadPriority` it would be worthwhile making sure the priority is indeed changed :)

**Comment by ntovas** [comment]
Hello,
@janvorli thanks for the info, I will try it. :)

@Maoni0 yes we will check it first with a dummy app in our environments, and then with changes in runtime, thank you. :)

**Comment by mangod9** [comment]
Hello @ntovas, just checking in whether you were able to validate the change to ensure it has the desired impact?

**Comment by mangod9** [comment]
Hello @ntovas, checking in again on whether you were able to validate perf improvement with this change?

**Comment by ntovas** [comment]
@mangod9 
Hello, I have done some initial tests and it seems that in specific use cases it improves how gc works, but on containerized environments (docker, openshift) it seems that by default the app will not have privileges to change the thread scheduler/priority.

**Comment by mangod9** [comment]
perhaps its not worth taking the change then?

**Pull request closed without merging**
