### PR TITLE
Fix coreclr Test570 due to ICU on Windows feature

### LINKED ISSUE #35039: Test failure: Regressions\\coreclr\\0570\\Test570\\Test570.cmd
failed in job: [runtime-coreclr outerloop 20200415.4 ](https://dev.azure.com/dnceng/public/_build/results?buildId=602088&view=ms.vss-test-web.build-test-results-tab&runId=18961384&resultId=109953&paneView=debug)

Error message
~~~
Return code: 1
Raw output file: C:\dotnetbuild\work\AD6B09DB\w\A6D00946\e\Regressions\coreclr\Reports\Regressions.coreclr\0570\Test570\Test570.output.txt
Raw output:
BEGIN EXECUTION
1 file(s) copied.
" "C:\dotnetbuild\work\AD6B09DB\p\crossgen.exe" /Platform_Assemblies_Paths C:\dotnetbuild\work\AD6B09DB\p;C:\dotnetbuild\work\AD6B09DB\w\A6D00946\e\Regressions\coreclr\0570\Test570 /in C:\dotnetbuild\work\AD6B09DB\w\A6D00946\e\Regressions\coreclr\0570\Test570\Test570.org /out C:\dotnetbuild\work\AD6B09DB\w\A6D00946\e\Regressions\coreclr\0570\Test570\\Test570.dll"
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
Copyright (c) Microsoft Corporation. All rights reserved.
Native image C:\dotnetbuild\work\AD6B09DB\w\A6D00946\e\Regressions\coreclr\0570\Test570\\Test570.dll generated successfully.
"C:\dotnetbuild\work\AD6B09DB\p\corerun.exe" Test570.dll 
enUS.NumberFormat.NumberDecimalDigits=3
Error: enUS.NumberFormat.NumberDecimalDigits=3, expected 2
enUS.NumberFormat.PercentDecimalDigits=3
Error: enUS.NumberFormat.PercentDecimalDigits=3, expected 2
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\dotnetbuild\work\AD6B09DB\p
> C:\dotnetbuild\work\AD6B09DB\w\A6D00946\e\Regressions\coreclr\0570\Test570\Test570.cmd
Expected: True
Actual: False


Stack trace
   at Regressions_coreclr._0570_Test570_Test570_._0570_Test570_Test570_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm64.Checked\TestWrappers\Regressions.coreclr\Regressions.coreclr.XUnitWrapper.cs:line 2080
~~~

### PR DESCRIPTION
**Pull request by safern**
Fixes: https://github.com/dotnet/runtime/issues/35039

### CODE REVIEW

**Comment by safern** [comment]
I queued a build from this branch: https://dev.azure.com/dnceng/public/_build/results?buildId=616798&view=results

**Review by BruceForstall — APPROVED** [review]

**Comment by GrabYourPitchforks** [comment]
I reviewed the "build 18362" part of the change and confirmed that it matches the 19H1 RTM build. So there's my minor contribution. :)

**Comment by safern** [comment]
> I reviewed the "build 18362" part of the change

Thanks 😄

**Comment by jkotas** [comment]
It would be better to fix this by moving the test to live under libraries where it belongs.

**Comment by jkotas** [comment]
If we have appropriate coverage under libraries, just delete the test.

**Comment by safern** [comment]
We already test this in Libraries: https://github.com/dotnet/runtime/blob/1db45ed953745c0e270d09df99828cb58772f4ad/src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoNumberDecimalDigits.cs#L15

It seems like for PercentDecimalDigits we don't have such test case:
https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoPercentDecimalDigits.cs

I guess I can just delete this test and add a test case in NumberFormatInfoPercentDecimalDigits tests

**Comment by safern** [comment]
Updated to remove the test and add the missing test data in libraries test.

**Review by jkotas — APPROVED** [review]
Thanks!

**Comment by jkotas** [comment]
The test failures are issues #35452 #35438 #35451

**Pull request merged**
