### PR TITLE
[browser][http] Set HttpResponseMessage.RequestMessage

### LINKED ISSUE #42691: Blazor WASM: HttpClient.SendAsync does not set the RequestMessage in ResponseMessage
### Describe the bug

When `SendAsync` is called on `HttpClient`, the `HttpResponseMessage.RequestMessage` is null when the `HttpClient` is in Blazor WASM, but not null (and equal to the original HttpRequestMessage) on NET Core.

In NET Core, we do:

```
HttpClient httpclient = new HttpClient();
HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Get, "https://www.bing.com");
HttpResponseMessage responseMessage = await httpclient.SendAsync(
    requestMessage,
    HttpCompletionOption.ResponseHeadersRead);
```

In Blazor WASM, we have the `HttpClient` registered as:

```
builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
```

And in a Blazor page:

```
@inject HttpClient Http

HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Get, "https://localhost:44384/");
HttpResponseMessage responseMessage = await Http.SendAsync(
    requestMessage,
    HttpCompletionOption.ResponseHeadersRead);
```

### To Reproduce

Sample code in this repo: https://github.com/ealsur/httpclientwasm

Running the Console app, the output is:

https://github.com/ealsur/httpclientwasm/blob/master/ConsoleApp/Program.cs#L19

image

Running the Blazor WASM app and browsing to Fetch Data, shows the output in the Browser Console:

https://github.com/ealsur/httpclientwasm/blob/master/Blazor/Pages/FetchData.razor#L48

image

### PR DESCRIPTION
**Pull request by campersau**
Fixes https://github.com/dotnet/runtime/issues/42691

### CODE REVIEW

**Review by lewing — APPROVED** [review]
Looks good

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
Are we running our HTTP tests?  I'm wondering if we have a test hole here, or if we do in fact have a test that would catch this but it didn't because we're not running them.

**Comment by lewing** [comment]
wasm Http tests in CI are waiting on https://github.com/dotnet/runtime/pull/40786 but we've done recent manual runs that did not catch this so I suspect a test hole.

**Comment by stephentoub** [comment]
> but we've done recent manual runs that did not catch this so I suspect a test hole.

Hmm.  I just searched the tests.  It's true that there aren't any dedicated to this, and I can fix that.  But there are a bunch of tests that just assume this is non-null and would null ref if it was, so something about those manual runs must have skipped all those tests.

**Comment by lewing** [comment]
Agreed, we're standing up the tests as quickly as possible.

@kjpou1 please look into why the tests aren't catching this.

**Comment by lewing** [comment]
The issue with the testing here is that browser can't support the loopback server because we don't have sockets and can't listen for requests so all the test that require the loopback server will throw PNSE and have to be skipped.

**Comment by stephentoub** [comment]
> so all the test that require the loopback server will throw PNSE and have to be skipped.

Oookeeyyy... that's the vast majority of the functional tests ;-)

**Comment by lewing** [comment]
> > so all the test that require the loopback server will throw PNSE and have to be skipped.
> 
> Oookeeyyy... that's the vast majority of the functional tests ;-)

Yeah... I think we're the first platform to hit this but I don't think we will be the last.

**Comment by lewing** [comment]
Opened #42852 for discussion

**Comment by lewing** [comment]
Lane failure looks like https://github.com/jaredpar/devops-util/issues/47 and this change is browser specific

**Pull request merged**
