### PR TITLE
Bump main version to Preview 6

### PR DESCRIPTION
**Pull request by carlossanlop**

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by carlossanlop** [comment]
@lewing @steveisok @radical is this failure related to my PR?
```
/tmp/workload-xglpaio3.21k/izbxxz0a.2za/restore/Restore.csproj : error NU1101: Unable to find package Microsoft.NET.Workload.Emscripten.Current.Manifest-8.0.100-preview.6. No packages exist with this id in source(s): dotnet-eng, dotnet-libraries, dotnet-libraries-transport, dotnet-public, dotnet-tools, dotnet7, dotnet7-transport, dotnet8, dotnet8-transport, nuget-local
```

**Comment by ViktorHofer** [comment]
Yes, I think that one is related. See `WorkloadVersionSuffix` in Versions.props.

**Comment by lewing** [comment]
I think the problem is that there is an assumption in the workload logic that emsdk and runtime have the same value there that breaks for a moment when we branch, pushed this to #86678 and will investigate further

**Comment by carlossanlop** [comment]
https://github.com/dotnet/runtime/pull/86678 got merged and it includes the version bump. Closing this one.

**Pull request closed without merging**
