### PR TITLE
[mono][aot] Prefer concrete instances instead of gshared ones for met…

### PR DESCRIPTION
**Pull request by vargaz**
…hods containing type equality checks.

For example, calls to Vector<T>.IsSupported cannot be optimized away in a method where T is T_BYTE because its written as:

```
            get => (typeof(T) == typeof(byte)) ||
                   (typeof(T) == typeof(double)) ||
```

and T_BYTE could be instantiated with an enum whose basetype is byte.

Fixes some of the issues in https://github.com/dotnet/runtime/issues/78163.

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
@vargaz Should we also prefer instances for `op_Inequality` ?

**Comment by vargaz** [comment]
Maybe, it wasn't a problem in practice so far.

**Comment by SamMonoRT** [comment]
@vargaz  - would this change contribute to size increase for blazor-wasm app (Interpreter) one. We are seeing size regressions in all wasm apps(New blank template, pizza app, aot-wasm, interpreter-wasm) in the same commit range.

**Comment by vargaz** [comment]
No, it should only affect AOT apps.

**Comment by radekdoulik** [comment]
That might be same regression as here https://radekdoulik.github.io/WasmPerformanceMeasurements/?startDate=2022-11-09T20%3A56%3A48.000Z&endDate=2022-11-12T14%3A17%3A58.000Z&tasks=Size

obrazek

It increases managed size by 0.192 %

adiff output of corlib https://gist.github.com/radekdoulik/a7b2743a4fae5d9e6711717ea46359cd for this commit range https://github.com/dotnet/runtime/compare/78322ae89f4e2be735520bcb34f8a6eb8a769295...3e94fdc791206bd83f247dd87156bdbc14d516c0

**Comment by kotlarmilos** [comment]
@radekdoulik is this main branch? There was a regression backported to `.net7` in https://github.com/dotnet/runtime/compare/403aa5841adfb6501f2016522917ce95150b16a5...1c341dea80da83a6eb137d743b9bb593e9fb2aad for pizza app.

**Pull request merged**
