### PR TITLE
Fix Configuration Save Full setting default value

### LINKED ISSUE #39967: Configuration.Save() does write changes to appsettings
### Description

The following little code sniplet writes an empty app.config 
`            var config = ConfigurationManager.OpenMappedExeConfiguration(configMap, ConfigurationUserLevel.None);
            config.AppSettings.Settings.Add("YourKey", "YourValue");
            config.Save(ConfigurationSaveMode.Full);
`
In 4.7.2 it did write the old app.config plus the new key. 

### Configuration

x64, Windows, .NET3.1

### Regression?

Worked on 4.7.2.

### Other information

It seems like the change in the appsettings is no longer recorded in the configuration anymore, as the save does exactly what it should when there really were no changes.

### PR DESCRIPTION
**Pull request by wzchua**
Fixes #39967

### CODE REVIEW

**Comment by danmosemsft** [comment]
This fix reverses a regression from .NET Framework introduced here 
https://github.com/dotnet/corefx/pull/14883/files#diff-c6794cd8a14d801813022876585e183cR1004

I see @ericstj mentions in issue it is not a regression, so is it something different?

**Comment by safern** [comment]
Interesting, it seems like it was a regression on that PR. It seems like the intention on that PR was to negate the `IsNullOrNullProperty` condition but somehow missed it.

**Review by safern — APPROVED** [review]

**Comment by danmosemsft** [comment]
@ericstj I assume this does not meet the bar for 5.0, It's not a regression and only has one customer report. Both Winforms and WPF seem to only use config files marginally, and not to save them, let alone with ConfigurationSaveMode.Full. So my assumption is no.

**Comment by ericstj** [comment]
Correct, this is not for 5.0.  Folks can pick up the nightly package and use on whichever framework they need it on, and it should be OK to stabilize and ship in 6.0.

**Comment by ericstj** [comment]
That said, I want to say a big thank you to @wzchua for finding and fixing this.  Let us know if you needed this sooner.  We'd need some pretty strong justification (similar to a servicing bar) to bring this into 5.0 at this point.

**Pull request merged**
