### PR TITLE
Eliminate DACCESS_COMPILE from gc.cpp and gcpriv.h

### PR DESCRIPTION
**Pull request by cshung**
It appears to me that `DACCESS_COMPILE` is never defined on `gc.cpp` and `gcpriv.h`. Eliminate them from the files to simplify things.

### CODE REVIEW

**Review by PeterSolMS — APPROVED** [review]
LGTM!

**Comment by PeterSolMS** [comment]
Looks good to me.

Perhaps we should protect against DACCESS_COMPILE being defined after all through some source code or build change though?

Something like:

#ifdef DACCESS_COMPILE
#error this source file should not be compiled with DACCESS_COMPILE!
#endif //DACCESS_COMPILE

**Comment by cshung** [comment]
> Looks good to me.
> 
> Perhaps we should protect against DACCESS_COMPILE being defined after all through some source code or build change though?
> 
> Something like:
> 
> #ifdef DACCESS_COMPILE
> #error this source file should not be compiled with DACCESS_COMPILE!
> #endif //DACCESS_COMPILE

I will add this in my next PR.

**Comment by cshung** [comment]
https://github.com/dotnet/runtime/issues/58120

**Pull request merged**
