### PR TITLE
Harden and re-enable DualMode socket tests

### LINKED ISSUE #1481: Re-enable dual-mode socket tests that were disabled on Linux\Mac
We should re-enable tests that were disabled on Linux\Mac. The tests would randomly fail because of the way that port allocation is different than on Windows. On Linux\Mac, when asking for an available free port, the returned port number is a random unused port. On Windows, it is incremental and eventually rolls over.

These tests are negative tests that connect to a V4 port and then send\listen on a V6 port (or vise-versa) of the same number expecting an unused port and thus failure case. However, in Linux\Mac there is a chance that the port is active instead of unused, causing the test to succeed, and\or interfering with a 'good' test. The port may be active on Windows too, causing similar problems, but the odds are much less as any given test run should not have active ports open that longs.

Two options to re-enable these tests:
1) Enable a test mode where a given test is flagged an runs serially
2) Move the tests to a new assembly with the CollectionBehavior attribute (DisableTestParallelization=true, MaxParallelThreads=1)

For these to work, all other tests should be done running, including tests in other assemblies (at least those tests which use sockets).

An alternative way to re-enable these tests is to keep them in the current assembly, but change the logic to something like this to preserve the original intent of making sure the socket is isn't 'dual mode':
1) Bind to address family with port 0 so we get unused port
2) Bind to the other address family + same port
3) The bind should succeed (otherwise retry by going back to step 1)
4) Unbind (so we can do the receive on it)
5) Do the actual receive on that unbound port
6) Should fail (as these tests are negative tests)

This alternative approach will increase reliability but there is a small chance between 4 and 5 another test grabbed that port.
However, if 3 succeeds then it probably proves that the socket wasn't dual mode because you can't bind to the same port + family twice; thus perhaps the test can stop there and not include 4-6.

See issues dotnet/corefx#16548, dotnet/corefx#9017, dotnet/corefx#13213, dotnet/corefx#17362, dotnet/corefx#17154, dotnet/corefx#13967 

Tests that were disabled below, located in DualModeSocketTest.cs. Note history should be checked for each of the commits as there are cases of Linux vs. Mac differences in the original test code which needs to be accounted for when the tests are enabled again.

https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs
```
DualModeConnect_IPAddressListToHost_Throws
BeginAcceptV6BoundToSpecificV4_CantConnect
BeginAcceptV4BoundToSpecificV6_CantConnect
BeginAcceptV6BoundToAnyV4_CantConnect
AcceptAsyncV6BoundToSpecificV4_CantConnect
AcceptAsyncV4BoundToSpecificV6_CantConnect
AcceptAsyncV6BoundToAnyV4_CantConnect
SendToV4IPEndPointToV6Host_NotReceived
SendToV6IPEndPointToV4Host_NotReceived
SendToAsyncV4IPEndPointToV6Host_NotReceived
SendToAsyncV6IPEndPointToV4Host_NotReceived
ReceiveMessageFromV6BoundToAnyV4_NotReceived
ReceiveFromV6BoundToSpecificV4_NotReceived
ReceiveFromV4BoundToSpecificV6_NotReceived
ReceiveFromV6BoundToAnyV4_NotReceived
BeginReceiveFromV6BoundToSpecificV4_NotReceived
BeginReceiveFromV4BoundToSpecificV6_NotReceived
BeginReceiveFromV6BoundToAnyV4_NotReceived
ReceiveMessageFromV6BoundToSpecificV4_NotReceived
ReceiveMessageFromV4BoundToSpecificV6_NotReceived
```

### LINKED ISSUE #21853: DualModeConnectAsync_DnsEndPointToHost_Helper failed with Timed out waiting for Connection
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fportable~2Fcli~2F/build/20170521.02/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.DualModeConnectAsync~2FDualModeConnectAsync_DnsEndPointToHost_Helper(listenOn:%20::,%20dualModeServer:%20True)

```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Timed out while waiting for connection\nExpected: True\nActual:   False
Stack Trace :
   at System.Net.Sockets.Tests.DualModeConnectAsync.DualModeConnectAsync_DnsEndPointToHost_Helper(IPAddress listenOn, Boolean dualModeServer) in /Users/buildagent/agent/_work/29/s/corefx/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 630
```

### LINKED ISSUE #79820: Connect_ThrowSocketException_Success failures on Linux
Test case: `System.Net.Sockets.Tests.ConnectTask.Connect_ThrowSocketException_Success`

Error message:
```
Assert.Fail(): Socket Connect should throw SocketException in this case.
```

Stack trace:
```
   at System.Net.Sockets.Tests.ConnectTask.Connect_ThrowSocketException_Success() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/Connect.cs:line 230
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

The socket seems to make a succesful connect to an unrelated dual socket in a parallel test. Can be fixed with a trick like https://github.com/dotnet/runtime/issues/1481#issuecomment-1355099578.

### PR DESCRIPTION
**Pull request by antonfirsov**
Fixes #1481.
Fixes #79820.

Throwing `DisableParallelization` at all tests in DualModeSocketTest increased the total execution time of those tests by approximately 1 minute on my Windows machine, so I decided to go with a more sophisticated approach.

- UDP tests are moved to a non-parallel collection, since there is no way to prevent parallel UDP tests from intercepting each other's packets. This only increases the execution time by ~2 seconds.
- TCP interferences are prevented by a utility `PortBlocker`, which creates and binds a "shadow" socket of the opposite address family to prevent sockets in parallel tests to bind to the same port.
- Accept and SendTo tests are refactored to use `SocketTestHelperBase<T>`, reducing duplicate code.

### CODE REVIEW

**Review by liveans — APPROVED** [review]
LGTM

**Comment by antonfirsov** [comment]
@wfurt do you want to take a look, or should I go ahead and merge this?

**Review by wfurt — APPROVED** [review]
LGTM. I would probably go with disabled parallelization but I'm fine with the helper if you feel it would stabilize the test. Time will tell and keeping the test disable does not provide any benefits.

**Comment by ManickaP** [comment]
I think that some of the re-enabled / shuffled tests are failing on extra platform pipeline:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=165856&view=ms.vss-test-web.build-test-results-tab&runId=3369863&resultId=168462&paneView=debug
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-81481-merge-79b8ca868c0d49858f/System.Net.Sockets.Tests/3/testResults.xml?helixlogtype=result

```
<test name="System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.ReceiveMessageFromAsyncV4BoundToSpecificV6_NotReceived" type="System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom" method="ReceiveMessageFromAsyncV4BoundToSpecificV6_NotReceived" time="0.0168523" result="Fail">
<traits>
<trait name="IPv4" value="true"/>
<trait name="IPv6" value="true"/>
</traits>
<failure exception-type="Xunit.Sdk.ThrowsException">
<message>
Assert.Throws() Failure\nExpected: typeof(System.TimeoutException)\nActual: typeof(System.ArgumentException): The supplied EndPoint of AddressFamily InterNetwork is not valid for this Socket, use InterNetworkV6 instead. (Parameter 'e')\n---- System.ArgumentException : The supplied EndPoint of AddressFamily InterNetwork is not valid for this Socket, use InterNetworkV6 instead. (Parameter 'e')
</message>
<stack-trace>
at System.Net.Sockets.Socket.ReceiveMessageFromAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken) at System.Net.Sockets.Socket.ReceiveMessageFromAsync(SocketAsyncEventArgs e) at System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.ReceiveMessageFromAsync_Helper(IPAddress listenOn, IPAddress connectTo, Boolean expectedToTimeout) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1666 at System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.<ReceiveMessageFromAsyncV4BoundToSpecificV6_NotReceived>b__39_0() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1613 ----- Inner Stack Trace ----- at System.Net.Sockets.Socket.ReceiveMessageFromAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken) at System.Net.Sockets.Socket.ReceiveMessageFromAsync(SocketAsyncEventArgs e) at System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.ReceiveMessageFromAsync_Helper(IPAddress listenOn, IPAddress connectTo, Boolean expectedToTimeout) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1666 at System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.<ReceiveMessageFromAsyncV4BoundToSpecificV6_NotReceived>b__39_0() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1613
</stack-trace>
</failure>
</test>


```

**Pull request merged**
