### PR TITLE
Move GetMethodTable to JIT

### PR DESCRIPTION
**Pull request by MichalPetryka**
Resurrection of #88860 now that the assert is gone since #104976.

Simplifies the VM code and should improve the codegen.

### CODE REVIEW

**Comment by MichalPetryka** [comment]
@MihuBot

**Comment by EgorBo** [comment]
I don't think it's needed in JIT at all, you can just drop the VM side and leave the [Intrinsic] as a hint for the inliner.

**Comment by MichalPetryka** [comment]
> I don't think it's needed in JIT at all, you can just drop the VM side and leave the [Intrinsic] as a hint for the inliner.

This should also be safer since we avoid the `ref Unsafe.As<RawData>(obj)` with this.
Also, `gtNewMethodTableLookup` spawns the indir as invariant so I'd assume this lets the JIT hoist this better.

**Comment by EgorBo** [comment]
> > I don't think it's needed in JIT at all, you can just drop the VM side and leave the [Intrinsic] as a hint for the inliner.
> 
> This should also be safer since we avoid the `ref Unsafe.As<RawData>(obj)` with this. Also, `gtNewMethodTableLookup` spawns the indir as invariant so I'd assume this lets the JIT hoist this better.

Jit should be smart enough to figure out that IND<intptr>(obj) is invariant, if it's not - it needs to be fixed then

**Comment by JulieLeeMSFT** [comment]
This is optimization, and not correctness issue. We don't have time to work on this for .NET 9, so we will review it in .NET 10.

**Comment by jkotas** [comment]
> Jit should be smart enough to figure out that IND<intptr>(ref) is invariant, if it's not - it needs to be fixed then

Reading the field at offset 0 is tricky. The byref pointing to offset 0 is technically invalid byref. The VM treats is as part of the object currently (vs. as part of the preceding object in memory), but I think we should minimize the number of places that depend on this details. I think it is best to keep reading of the method table as a JIT intrinsic like this PR does. Ideally, I would like to get rid of the m_pEEType field in native AOT to make `System.Object` impl the same between regular CoreCLR and native AOT.

**Review by jkotas — APPROVED** [review]
LGTM

**Comment by jkotas** [comment]
@dotnet/jit-contrib There seems to be an infrastructure issue with SuperPMI. Could you please take a look?

**Pull request merged**
