### PR TITLE
JIT: Enable edge based profiles for all scenarios

### LINKED ISSUE #47942: JIT: resolve issues with OSR and PGO
OSR and PGO don't play nicely together.

See https://github.com/dotnet/runtime/issues/46882#issuecomment-774371966 and follow on comments.

### LINKED ISSUE #66101: Fix interaction of PGO and partial compilation
We currently assume that a Tier0+BBINSTR jit can anticipate all the (root level) probes that might be needed during a subsequent OSR+BBINSTR rejit. But this assumption breaks down with partial compilation as the Tier0 jit only sees a subset of the full method.

As a result, the OSR+BBINSTR schema is incompatible and OSR instrumentation fails. We need to fix this.

Things work out for normal OSR because the Tier0 jit importation is a superset, and if OSR imports less, we consider OSR subset schema to be compatible with the Tier0 schema.

See [notes](https://github.com/dotnet/runtime/issues/65992#issuecomment-1057222198) on #65992 for more context.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Enable edge based profiles for OSR, partial compilation, and optimized plus instrumented cases.

For OSR this requires deferring flow graph modifications until after we have built the initial probe list, so that the initial list reflects the entirety of the method. This set of candidate edge probes is thus the same no matter how the method is compiled. A given compile may schematize a subset of these probes and materialize a subset of what gets schematized; this is tolerated by the PGO mechanism provided that the initial instrumented jitting produces a schema which is a superset of the schema produced by any subsequent instrumented rejitting. This is normally the case.

Partial compilation may still need some work to ensure full schematization but it is currently off by default. Will address this subsequently.

For optimized compiles we give the EfficientEdgeCountInstrumentor the same kind of probe relocation abilities that we have in the BlockCountInstrumentor. In particular we need to move probes that might appear in return blocks that follow implicit tail call blocks, since those return blocks must remain empty.

The details on how we do this are a bit different but the idea is the same: we create duplicate copies of any probe that was going to appear in the return block and instead instrument each pred. If the pred reached the return via a critical edge, we split the edge and put the probe there. This analysis relies on cheap preds, so to ensure we can use them we move all the critial edge splitting so it happens before we need the cheap pred lists.

The ability to do block profiling is retained but will no longer be used without special config settings.

There were also a few bug fixes in the spanning tree visitor. It must visit a superset of the blocks we end up importing and was missing visits in some cases.

This should improve jit time and code quality for instrumented code.

Fixes #47942.
Fixes #66101.
Contributes to #74873.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL
cc @dotnet/jit-contrib 

Expect sizeable diffs in ASP.NET.

**Comment by EgorBo** [comment]
Nice diffs for the aspnet collection! Btw, perhaps it makes sense to enable Dynamic PGO for coreclr_tests.run collection

I'll take a look tomorrow if you don't mind, I'm OOF today

**Comment by AndyAyersMS** [comment]
> I'll take a look tomorrow if you don't mind, I'm OOF today

Sure ... might be easier to ignore whitespace when you look at diffs as I moved / re-indented some of the block profiling code.

**Comment by AndyAyersMS** [comment]
Extended pgo testing is seeing some failures:

* Assert failure(PID 4392 [0x00001128], Thread: 8428 [0x20ec]): Assertion failed 'curr->KindIs(BBJ_COND, BBJ_SWITCH, BBJ_ALWAYS)' in 'System.StubHelpers.CSTRMarshaler:ConvertToNative(int,System.String,long):long' during 'Profile instrumentation' (IL size 194; hash 0xc31c0dcd; Instrumented Tier1)

    File: D:\a\_work\1\s\src\coreclr\jit\fgbasic.cpp Line: 4374

**Comment by EgorBo** [comment]
@AndyAyersMS `Instrumented Tier1` is when we re-jit R2R in order to instrument it. That tier was using block instrumentation.
When we re-jit normal Tier0 to instrumentation we use edge-based instrumentation (because we don't use optimizations).

So, for easier testing, we can always use optimizations in the instrumentation tier even if we rejit just IL-only tier0. (or it can be stress-mode based).

**Comment by AndyAyersMS** [comment]
> So, for easier testing, we can always use optimizations in the instrumentation tier even if we rejit just IL-only tier0. (or it can be stress-mode based)

Probably a good stress mode to add, yeah.

**Comment by AndyAyersMS** [comment]
Recent failures all looked like infra issues, retrying.

**Comment by AndyAyersMS** [comment]
@EgorBo ping

**Review by EgorBo — APPROVED** [review]
Played with your branch locally and it looks great!

**Comment by AndyAyersMS** [comment]
TE improvements (instrumented Tier0 code perf). Note we're still quite a ways below Tier0 (which is quite a ways below optimized).

image

image

**Comment by EgorBo** [comment]
Wow, nice wins! block counters seem to be expensive

**Pull request merged**
