### PR TITLE
Ensure that iOS builds get correct library identity for native libraries

### LINKED ISSUE #34637: Dynamic libraries in the microsoft.netcore.app.runtime.ios-x64 package has incorrect identity
Repro:

```shell
otool -l ~/.nuget/packages/microsoft.netcore.app.runtime.ios-x64/5.0.0-*/runtimes/ios-x64/native/*dylib | grep LC_ID_DYLIB -A 2
          cmd LC_ID_DYLIB
      cmdsize 184
         name /Users/runner/runners/2.165.2/work/1/s/artifacts/obj/native/netcoreapp5.0-iOS-Release-x64/System.IO.Compression.Native/libSystem.IO.Compression.Native.dylib (offset 24)
```

This should be something like `@executable_path/libSystem.IO.Compression.Native.dylib`.

CC @akoeplinger

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #34637 

I am not 100% sure this is the right place to put it. The `otool -L` output now looks like this:
```
otool -L /Users/filipnavara/Projects/runtime/artifacts/bin/native/net6.0-iOS-Debug-x64/./libSystem.IO.Compression.Native.dylib
/Users/filipnavara/Projects/runtime/artifacts/bin/native/net6.0-iOS-Debug-x64/./libSystem.IO.Compression.Native.dylib:
	@rpath/libSystem.IO.Compression.Native.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
```

/cc @akoeplinger @rolfbjarne

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]
LGTM, thanks!

**Comment by akoeplinger** [comment]
Looks like the iOS arm64 build fails with:
```
##[error]ld(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) embedded dylibs/frameworks only run on iOS 8 or later
```

We're indeed targetting iOS 7 for device builds and iOS 8 for simulator. @rolfbjarne do you know what this error means, should we use `@executable_path` instead?

**Comment by filipnavara** [comment]
That's quite unfortunate. I think [Xamarin itself uses `@rpath`](https://github.com/xamarin/xamarin-macios/blob/d602cf76cf39dec1882d80992dbbc68cd953e8d5/runtime/Makefile#L242) but it does it through `install_name_tool` and not the linker. That may simply behave differently and ignore the iOS version. It also seems that `@rpath` actually worked on iOS 7 but it was not officially supported.

**Comment by filipnavara** [comment]
Hm, `@executable_path` fails with the exact same error.

**Comment by akoeplinger** [comment]
Looks like this is usually a warning instead of an error but we're using warnings-as-errors so this gets turned into an error.

**Comment by akoeplinger** [comment]
We discussed on Discord and iOS 8 is fine as the minimum version these days.

**Comment by rolfbjarne** [comment]
> We discussed on Discord and iOS 8 is fine as the minimum version these days.

8.0 as the minimum version is fine for dynamic libraries or frameworks, it's not for static libraries, since we still support iOS 7.

> We're indeed targetting iOS 7 for device builds and iOS 8 for simulator.

Apple is dropping support for older simulators quite aggressively, so there's not much purpose in building for a simulator you can never use. On the other hand it's still possible to build for older device versions in Xcode.

**Pull request merged**
