### PR TITLE
Fix partial compilation for CETCOMPAT mode

### PR DESCRIPTION
**Pull request by EgorBo**
Copy `JIT_Patchpoint`'s implementation to `JIT_PartialCompilationPatchpoint` since the latter crashes when CET is enabled.

We can probably move shared bits to a helper, although, my attempt to do so was a bit ugly

I guess this doesn't need to be backported to 9.0 since `DOTNET_TC_PartialCompilation` is disabled by default (and not officially advertised)

### CODE REVIEW

**Comment by EgorBo** [comment]
@AndyAyersMS how do I test this change on CI? Should I enable it by default in my PR or can run some jitstress?

**Comment by AndyAyersMS** [comment]
> @AndyAyersMS how do I test this change on CI? Should I enable it by default in my PR or can run some jitstress?
> 
> This change does fix the crash in AvaloniaILSpy that we discussed yesterday

There is testing done in jit-experimental, so run that.

Did you notice any perf impact once this was fixed?

**Comment by EgorBo** [comment]
> Did you notice any perf impact once this was fixed?

A small one. I was running AvaloniILSpy in a loop (it exits once initialized) via
```ps1
for(;;) { Measure-Command { C:\...\corerun.exe C:\...\ILSpy.dll } }
```

0.9559 sec. - Best time for default mode
0.9445 sec. - Best time with Partial Compilation.

For both, I've disabled R2R.

**Comment by EgorBo** [comment]
@AndyAyersMS does it look good otherwise?

**Review by AndyAyersMS — APPROVED** [review]

**Pull request merged**
