### PR TITLE
Bugfix InvalidOperationException/IndexOutOfRangeException in HttpListener.EndGetContext

### PR DESCRIPTION
**Pull request by pjannesen**
See #107025

### CODE REVIEW

**Comment by kg** [comment]
Please rebase your commit(s) onto main or change the target branch

**Comment by pjannesen** [comment]
@dotnet-policy-service agree [company="Jannesen"]

**Comment by pjannesen** [comment]
> @dotnet-policy-service agree [company="{your company}"]



> @pjannesen please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement



> @pjannesen please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree [company="Jannesen"]

**Comment by MihaZupan** [comment]
I'm closing this PR as any changes/comments here are notifying many people from unrelated areas.

@pjannesen please open a new PR based on the `main` branch. When creating a PR, you should only see your own modifications in the list of changes if the branches are set correctly.

**Pull request closed without merging**
