### PR TITLE
Delete `(unsigned)CHECK_SPILL_ALL|NONE` casts

### PR DESCRIPTION
**Pull request by SingleAccretion**
The no-diffs second part of #72291.

[No diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1905291&view=ms.vss-build-web.run-extensions-tab).

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
@SingleAccretion can you fix the merge conflicts here?

**Comment by SingleAccretion** [comment]
@AndyAyersMS This is waiting on #73233 -- when/if that's merged, the conflicts should (mostly) fix themselves.

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Review by jakobbotsch — APPROVED** [review]

**Pull request merged**
