### PR TITLE
JIT: Check for call interference when placing PUTARG nodes

### LINKED ISSUE #102919: Source generator tests failing with AV in Roslyn
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=693513
Build error leg or test failing: System.Text.RegularExpressions.Tests.RegexPcre2Tests.IsMatchTests
Pull request: https://github.com/dotnet/runtime/pull/102903

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": [ "System.AccessViolationException", "Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileMethods" ],
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=693513
**Error message validated:** `[System.AccessViolationException Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CompileMethods`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 5/31/2024 5:13:05 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[713808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713808)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713808&view=ms.vss-test-web.build-test-results-tab&runId=17856370&resultId=222081)||
|[713038](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713038)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713038&view=ms.vss-test-web.build-test-results-tab&runId=17833152&resultId=222446)|dotnet/runtime#103706|
|[709265](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709265)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709265&view=ms.vss-test-web.build-test-results-tab&runId=17710064&resultId=213585)||
|[705911](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705911)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705911&view=ms.vss-test-web.build-test-results-tab&runId=17608962&resultId=220816)|dotnet/runtime#103381|
|[693513](https://dev.azure.com/dnceng-public/public/_build/results?buildId=693513)|dotnet/runtime|[System.Text.RegularExpressions.Tests.RegexPcre2Tests.IsMatchTests](https://dev.azure.com/dnceng-public/public/_build/results?buildId=693513&view=ms.vss-test-web.build-test-results-tab&runId=17225330&resultId=219785)|dotnet/runtime#102903|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|5|

### LINKED ISSUE #103300: JIT: Lowering's insertion of `PUTARG_*` nodes is questionable
When we lower arguments to calls we create `PUTARG_*` nodes and insert them right after their corresponding argument definitions:
https://github.com/dotnet/runtime/blob/d06fb0872b5f6cc82dd74876f778154974de8410/src/coreclr/jit/lower.cpp#L1510-L1511

This insertion location does not make sense, since conceptually the definitions of the argument nodes can be arbitrarily far away from the call and there can even be interfering calls between the argument and consuming call.

The choice was probably made because the argument placement order is decided during morph when the call is in tree order, and the expectation is that args are placed in the early/late order decided there.

A few potential fixes:
- Insert `PUTARG` nodes during rationalization when we can depend on tree order and the early/late args call invariant. Seems to move something that is conceptually ABI lowering into rationalization which is unfortunate.
- Insert the `PUTARG` nodes right before the call node. Unfortunately has large regressions.
- Check for call interference between the arg and call and place the argument early on no interference and late on interference. Probably costs some TP.
- Move arg lowering from morph to lowering with appropriate interference checking (similar to what morph has to do today anyway). Probably best long term solution, but takes the most work.

cc @dotnet/jit-contrib

### LINKED ISSUE #104042: Test issue: AccessViolationException on CodeAnalysis.CSharp.Binder.BindConstructorInitializerCoreContinued
Likely a duplicate of https://github.com/dotnet/runtime/issues/102919

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=719926
Build error leg or test failing: System.Text.RegularExpressions.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/103968

LOG:
```
C:\h\w\A622090A\w\B1E7098D\e>"C:\h\w\A622090A\p\dotnet.exe" exec --runtimeconfig System.Text.RegularExpressions.Tests.runtimeconfig.json --depsfile System.Text.RegularExpressions.Tests.deps.json xunit.console.dll System.Text.RegularExpressions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Text.RegularExpressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.RegularExpressions.Tests (found 345 of 373 test cases)
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on [2 threads], stop on fail = off)
    System.Text.RegularExpressions.Tests.RegexParserTests.RegexParseException_Serializes [SKIP]
      Condition(s) not met: "IsBinaryFormatterSupported"
    System.Text.RegularExpressions.Tests.RegexMatchTimeoutExceptionTests.SerializationRoundtrip [SKIP]
      Condition(s) not met: "IsBinaryFormatterSupported"
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.CodeAnalysis.CSharp.Binder.BindConstructorInitializerCoreContinued(Boolean, Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.AnalyzedArguments, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol, Boolean, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, Microsoft.CodeAnalysis.Location, Boolean, Microsoft.CodeAnalysis.CSharp.MemberResolutionResult`1<Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol>, Microsoft.CodeAnalysis.CompoundUseSiteInfo`1<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> ByRef, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindConstructorInitializerCore(Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindImplicitConstructorInitializer(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag, Microsoft.CodeAnalysis.CSharp.CSharpCompilation)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.TypeCompilationState, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag, Boolean, Microsoft.CodeAnalysis.CSharp.BoundNode, Boolean, Microsoft.CodeAnalysis.CSharp.ImportChain ByRef, Boolean ByRef, Boolean ByRef, InitialState ByRef)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, ProcessedFieldInitializers ByRef, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol)
   at Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(System.Threading.PortableThreadPool, Boolean ByRef)
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

STACK:
```
        Child SP               IP Call Site
000000621252B558                  [InlinedCallFrame: 000000621252b558] System.Private.CoreLib.dll!System.Runtime.ExceptionServices.InternalCalls.<RhpSfiInit>g____PInvoke|0_0(System.Runtime.StackFrameIterator*, Void*, Int32, Boolean*)
000000621252B860                  [FaultingExceptionFrame: 000000621252b860] 
000000621252E1D0 000000620B662117 Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindConstructorInitializerCoreContinued(Boolean, Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.AnalyzedArguments, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol, Boolean, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, Microsoft.CodeAnalysis.Location, Boolean, Microsoft.CodeAnalysis.CSharp.MemberResolutionResult`1<Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol>, Microsoft.CodeAnalysis.CompoundUseSiteInfo`1<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> ByRef, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag) + 343
000000621252E1D8 00000062BCBD1018 
000000621252E650 000000620B661429 Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindConstructorInitializerCore(Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag) + 889
000000621252EA40 000000620B5D57A1 Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.Binder.BindImplicitConstructorInitializer(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag, Microsoft.CodeAnalysis.CSharp.CSharpCompilation) + 1409
000000621252EAB0 0000006208DB537A Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.TypeCompilationState, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag, Boolean, Microsoft.CodeAnalysis.CSharp.BoundNode, Boolean, Microsoft.CodeAnalysis.CSharp.ImportChain ByRef, Boolean ByRef, Boolean ByRef, InitialState ByRef) + 3770
000000621252EC80 0000006208DB22D0 Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Int32, ProcessedFieldInitializers ByRef, Microsoft.CodeAnalysis.CSharp.SynthesizedSubmissionFields, Microsoft.CodeAnalysis.CSharp.TypeCompilationState) + 2288
000000621252F080 000000620B5CFA5D Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol) + 4061
000000621252F3B0 000000620B5CE9B5 Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MethodCompiler+<>c__DisplayClass25_0.<CompileNamedTypeAsync>b__0() + 37
000000621252F3F0 000000620BE29DE1 System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) + 145
000000621252F440 0000006208546DCC System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) + 236
000000621252F4E0 000000620BED2922 System.Private.CoreLib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() + 1378
000000621252F5A0 000000620BED8ABB System.Private.CoreLib.dll!System.Threading.PortableThreadPool+WorkerThread.WorkerDoWork(System.Threading.PortableThreadPool, Boolean ByRef) + 123
000000621252F660 00007FFB97A3CB46 System.Private.CoreLib.dll!System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart() + 518
000000621252F940                  [DebuggerU2MCatchHandlerFrame: 000000621252f940] 
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "at Microsoft.CodeAnalysis.CSharp.Binder.BindConstructorInitializerCoreContinued(Boolean, Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.AnalyzedArguments, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol, Boolean, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, Microsoft.CodeAnalysis.Location, Boolean, Microsoft.CodeAnalysis.CSharp.MemberResolutionResult`1<Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol>, Microsoft.CodeAnalysis.CompoundUseSiteInfo`1<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> ByRef, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=719926
**Error message validated:** `[at Microsoft.CodeAnalysis.CSharp.Binder.BindConstructorInitializerCoreContinued(Boolean, Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.AnalyzedArguments, Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol, Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol, Boolean, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, Microsoft.CodeAnalysis.Location, Boolean, Microsoft.CodeAnalysis.CSharp.MemberResolutionResult`1<Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol>, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol>, Microsoft.CodeAnalysis.CompoundUseSiteInfo`1<Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol> ByRef, Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/26/2024 3:06:45 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[719926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=719926)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=719926&view=ms.vss-test-web.build-test-results-tab&runId=18048750&resultId=222298)|dotnet/runtime#103968|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

### PR DESCRIPTION
**Pull request by jakobbotsch**
This adds a legalization pass for call argument `PUTARG` nodes after they have been created. We currently insert PUTARG_* nodes right after argument definitions, which is usually a good placement because morph ensured that this was ok.
However, due to LIR transformations this placement might not be legal if there are any calls after the node. This PR moves the PUTARG_* nodes ahead of those interfering calls when they exist.

For example, for the case in #102919 we now end up with:
```
Call [000278] has 7 PUTARG nodes that interfere with [002686]; will move them after it
Relocating [002700] after [002686]
Relocating [002699] after [002686]
Relocating [002698] after [002686]
Relocating [002697] after [002686]
Relocating [002696] after [002686]
Relocating [002695] after [002686]
Relocating [002694] after [002686]
Final result after legalization:
N001 (  1,  1) [000263] -----------                  t263 =    LCL_VAR   ref    V65 tmp36        u:4 $441
N002 (  1,  1) [000264] -----------                  t264 =    LCL_VAR   ref    V76 tmp47        u:4 $446
N003 (  1,  1) [000265] -----------                  t265 =    LCL_VAR   ref    V07 loc3         u:4 $448
N004 (  1,  1) [000266] -----------                  t266 =    LCL_VAR   int    V08 loc4         u:2 $371
N005 (  3,  2) [000267] -----------                  t267 =    LCL_VAR   ref    V09 loc5         u:6 $44c
N006 (  1,  1) [000268] -----------                  t268 =    LCL_VAR   ref    V10 loc6         u:6 $44d
N007 (  3,  2) [000269] -----------                  t269 =    LCL_VAR   int    V11 loc7         u:4 $780
N008 (  3,  2) [001733] -----------                 t1733 =    LCL_VAR   ref    V125 tmp96       u:2 (last use) $755
N009 (  1,  1) [001740] -c---------                 t1740 =    CNS_INT   long   16 $1c3
                                                            ┌──▌  t1733  ref    
                                                            ├──▌  t1740  long   
N010 (  3,  3) [001741] -------N---                 t1741 = ▌  ADD       byref  $3d4
                                                            ┌──▌  t1741  byref  
               [002690] DA---------                         ▌  STORE_LCL_VAR byref  V162 rat3        
               [002691] -----------                 t2691 =    LCL_VAR   byref  V162 rat3        
               [002692] -----------                 t2692 =    LCL_VAR   byref  V162 rat3        
                                                            ┌──▌  t2692  byref  
               [002693] ---X-------                         ▌  NULLCHECK byte  
               [002681] D----------                 t2681 =    LCL_ADDR  byref  V141 tmp112      [+0]
                                                            ┌──▌  t2681  byref  
               [002687] -----------                 t2687 = ▌  PUTARG_REG byref  REG rcx
                                                            ┌──▌  t2691  byref  
               [002688] -----------                 t2688 = ▌  PUTARG_REG byref  REG rdx
               [002682] -----------                 t2682 =    CNS_INT   long   128
                                                            ┌──▌  t2682  long   
               [002689] -----------                 t2689 = ▌  PUTARG_REG long   REG r8
                                                            ┌──▌  t2687  byref  arg0 in rcx
                                                            ├──▌  t2688  byref  arg1 in rdx
                                                            ├──▌  t2689  long   arg2 in r8
N004 ( 17, 11) [002686] --CXG------                         ▌  CALL help void   CORINFO_HELP_BULK_WRITEBARRIER
                                                            ┌──▌  t263   ref    
               [002694] -----------                         ▌  PUTARG_STK [+0x20] void  
                                                            ┌──▌  t264   ref    
               [002695] -----------                         ▌  PUTARG_STK [+0x28] void  
                                                            ┌──▌  t265   ref    
               [002696] -----------                         ▌  PUTARG_STK [+0x30] void  
                                                            ┌──▌  t266   int    
               [002697] -----------                         ▌  PUTARG_STK [+0x38] void  
                                                            ┌──▌  t267   ref    
               [002698] -----------                         ▌  PUTARG_STK [+0x40] void  
                                                            ┌──▌  t268   ref    
               [002699] -----------                         ▌  PUTARG_STK [+0x48] void  
                                                            ┌──▌  t269   int    
               [002700] -----------                         ▌  PUTARG_STK [+0x50] void  
N013 ( 19, 14) [001744] -----------                            NOP       void  
N014 (  3,  2) [000275] -----------                  t275 =    LCL_VAR   ref    V123 tmp94       u:2 $754
                                                            ┌──▌  t275   ref    
               [002701] -----------                         ▌  PUTARG_STK [+0x60] void  
N015 (  3,  3) [000276] -----------                  t276 =    LCL_ADDR  long   V22 loc18        [+0] $3d1
                                                            ┌──▌  t276   long   
               [002702] -----------                         ▌  PUTARG_STK [+0x68] void  
N016 (  1,  1) [000277] -----------                  t277 =    LCL_VAR   ref    V03 arg3         u:1 $103
                                                            ┌──▌  t277   ref    
               [002703] -----------                         ▌  PUTARG_STK [+0x70] void  
N017 (  3,  3) [001745] -----------                 t1745 =    LCL_ADDR  long   V141 tmp112      [+0] $3d8
                                                            ┌──▌  t1745  long   
               [002704] -----------                         ▌  PUTARG_STK [+0x58] void  
N018 (  1,  1) [000261] -----------                  t261 =    LCL_VAR   ref    V01 arg1         u:1 $101
                                                            ┌──▌  t261   ref    
               [002705] -----------                 t2705 = ▌  PUTARG_REG ref    REG r8
N019 (  1,  1) [000262] -----------                  t262 =    LCL_VAR   ref    V02 arg2         u:1 $102
                                                            ┌──▌  t262   ref    
               [002706] -----------                 t2706 = ▌  PUTARG_REG ref    REG r9
N020 (  1,  1) [000259] -----------                  t259 =    LCL_VAR   ref    V00 this         u:1 $100
                                                            ┌──▌  t259   ref    
               [002707] -----------                 t2707 = ▌  PUTARG_REG ref    REG rcx
N021 (  1,  1) [001124] -----------                 t1124 =    CNS_INT   int    1 $c1
                                                            ┌──▌  t1124  int    
               [002708] -----------                 t2708 = ▌  PUTARG_REG int    REG rdx
                                                            ┌──▌  t2705  ref    arg2 in r8
                                                            ├──▌  t2706  ref    arg3 in r9
                                                            ├──▌  t2707  ref    this in rcx
                                                            ├──▌  t2708  int    arg1 in rdx
N022 ( 91, 46) [000278] -ACXGO-----                  t278 = ▌  CALL      ref    Microsoft.CodeAnalysis.CSharp.Binder:BindConstructorInitializerCoreContinued(ubyte,Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentListSyntax,Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol,Microsoft.CodeAnalysis.CSharp.AnalyzedArguments,Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol,Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol,ubyte,Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode,Microsoft.CodeAnalysis.Location,ubyte,Microsoft.CodeAnalysis.CSharp.MemberResolutionResult`1[Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol],System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol],byref,Microsoft.CodeAnalysis.CSharp.BindingDiagnosticBag):Microsoft.CodeAnalysis.CSharp.BoundExpression:this $135
```

without this change the `PUTARG_STK` nodes end up before the `BULKWRITEBARRIER` call.

The algorithm works by first marking all `PUTARG` operand nodes of the call, and then walking backwards from the call in linear order until we have visited all marked nodes.
If we see any call before visiting all marked nodes then we have found an interfering call, and the remaining `PUTARG_` nodes need to be moved after it.

Fix #103300
Fix #102919
Fix #104042

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @EgorBo 

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=719974&view=ms.vss-build-web.run-extensions-tab). ASM diffs are pretty small. MinOpts TP regressions are pretty large, but it's about balanced out from #103809 that I just merged.

**Comment by EgorBo** [comment]
Btw, I wonder if it makes sense to introduce an assert that certain types of helper calls (backed by managed impl or with safe points) never appear in nogc regions

**Comment by jakobbotsch** [comment]
> Btw, I wonder if it makes sense to introduce an assert that certain types of helper calls (backed by managed impl or with safe points) never appear in nogc regions

Probably would, but note that the call arg setup isn't in a nogc region, so it wouldn't have caught this bug.

**Comment by jakobbotsch** [comment]
jitstress failures are #103624 and #103577.
libraries-jitstress failures are #103784, #103549, and a number of timeouts that I'm going to attribute to #103624.

**Review by EgorBo — APPROVED** [review]
LGTM!

**Pull request merged**
