### PR TITLE
System.DirectoryServices.Protocols.LdapConnection: allow non-ASCII Passwords on Linux Systems

### PR DESCRIPTION
**Pull request by KonH**
Related to https://github.com/dotnet/runtime/issues/76426

### CODE REVIEW

**Comment by joperezr** [comment]
So I am trying to test this locally but can't seem to get a repro even without your change, so even when I set a server where the password is `passwörd` I'm able to authenticate just fine using the existing pointer. Do you happen to recall which environment you were working on when hitting the issue? Meaning, was the server that you were trying to connect to an Active Directory server or was it a linux slapd server?

**Comment by MichaWe** [comment]
We were running on a Linux system and tried to connect to an active directory service.

**Comment by joperezr** [comment]
Ok, so I'll try to repro on Active Directory then. This doesn't repro on non-Active Directory LDAP servers.

**Comment by stephentoub** [comment]
This PR is changing `Marshal.StringToHGlobalAnsi(s)` to `Marshal.StringToHGlobalAuto(s)` on Linux.  But on Linux, I'd expect those to be identical in behavior, both marshaling as UTF8.  What's the exact issue this is going to fix? (Also, PtrToString and StringToPtr should be opposites of each other.)

**Comment by iSazonov** [comment]
> This PR is changing `Marshal.StringToHGlobalAnsi(s)` to `Marshal.StringToHGlobalAuto(s)` on Linux. But on Linux, I'd expect those to be identical in behavior, both marshaling as UTF8. What's the exact issue this is going to fix? (Also, PtrToString and StringToPtr should be opposites of each other.)

Exact issue is that buffer length too short on Unix if password contains Unicode chars. StringToHGlobalAnsi evaluates the length based on GetSystemMaxDBCSCharSize const, StringToHGlobalAuto (really StringToHGlobalUTF8 on Unix) - Encoding.UTF8.GetMaxByteCount.

**Comment by stephentoub** [comment]
> Exact issue is that buffer length too short on Unix if password contains Unicode chars.

Can you share an example input that's a problem?

**Comment by iSazonov** [comment]
> > Exact issue is that buffer length too short on Unix if password contains Unicode chars.
> 
> Can you share an example input to StringToHGlobalAnsi that repros the problem?

@stephentoub There is an example in OP of the related issue #76426

**Comment by stephentoub** [comment]
> @stephentoub There is an example in OP of the related issue https://github.com/dotnet/runtime/issues/76426

@iSazonov, yes, that example uses `var userPassword = "passwörd"`, and you've stated the problem is that Marshal.StringToHGlobalAnsi uses too small a buffer, but on Linux, this:
```C#
using System.Runtime.InteropServices;

internal unsafe class Program
{
    private static void Main()
    {
        string pw = "passwörd";

        Print((byte*)Marshal.StringToHGlobalAnsi(pw));
        Print((byte*)Marshal.StringToHGlobalAuto(pw));
        Print((byte*)Marshal.StringToCoTaskMemUTF8(pw));

        void Print(byte* p)
        {
            int length = 0;
            while (*p != 0)
            {
                Console.WriteLine($"0x{*p:X2} ('{(char)*p}')");
                p++;
                length++;
            }
            Console.WriteLine($"Length: {length}");
            Console.WriteLine();
        }
    }
}
```
prints out:
```
0x70 ('p')
0x61 ('a')
0x73 ('s')
0x73 ('s')
0x77 ('w')
0xC3 ('Ã')
0xB6 ('¶')
0x72 ('r')
0x64 ('d')
Length: 9

0x70 ('p')
0x61 ('a')
0x73 ('s')
0x73 ('s')
0x77 ('w')
0xC3 ('Ã')
0xB6 ('¶')
0x72 ('r')
0x64 ('d')
Length: 9

0x70 ('p')
0x61 ('a')
0x73 ('s')
0x73 ('s')
0x77 ('w')
0xC3 ('Ã')
0xB6 ('¶')
0x72 ('r')
0x64 ('d')
Length: 9
```

So... what input to StringToHGlobalAnsi repros the difference in behavior you're seeing between StringToHGlobalAnsi  and StringToHGlobalAuto such that the latter fixes some problem?

**Comment by joperezr** [comment]
@stephentoub Just to add more background and context here. The original report, as you've seen, said that when people try to login to an LDAP server using S.D.P with credentials that contain unicode characters, they get a failure. When I was triaging the issue, I just ran some eye-debugging to follow the flow and find where could the potential bug be, and found that we were calling `Marshal.StringToHGlobalAnsi` before sending the result as PInvoke to openldap library. I am not very familiar with the implementation of that API, but when quickly looking at the Marshal surface area, I found that we also have a `StringToHGlobalUni` for unicode, and so that made me think that was the root of the problem. I also found that we have this `Auto` method, which I assumed would pick the Ansi or Uni overload depending on the contents of the string, so I suggested on the issue to try switching the call to use the `Auto` method to see if that fixed their problem. I don't think we have been able to fully validate that this change fixes the problem, and from your comments, seems like the answer is that it won't.

**Comment by iSazonov** [comment]
If I understand correctly LDAPv3 allow Utf8 and as @stephentoub pointed we correctly send Utf8.
In the case I wonder what LDAP version we use:
https://github.com/dotnet/runtime/blob/1350579859435ee18bd530e18022a880ae418132/src/libraries/Common/src/Interop/Interop.Ldap.cs#L125

**Comment by joperezr** [comment]
By default, when instantiating a new LdapConnection v2.0 will be selected due to backwards compatibility, but it is suggested to set it to 3.0 always, which is what we do in our tests:

https://github.com/dotnet/runtime/blob/e6bac1e15f3ea795c84cbd009eb8b77da460c9e1/src/libraries/System.DirectoryServices.Protocols/tests/DirectoryServicesProtocolsTests.cs#L762-L769

That actually might be why I wasn't able to repro, as I am using the tests to validate.

**Comment by iSazonov** [comment]
> By default, when instantiating a new LdapConnection v2.0 will be selected due to backwards compatibility

Can you point the code? I see `LDAP_OPT_VERSION = 0x11` in Linux code - it is not 2.0 and it is not 3.0.

**Comment by joperezr** [comment]
We don't do that in managed code. This is the default on openldap 2.4 native library which is what we use underneath.

**Comment by iSazonov** [comment]
@joperezr Thanks! 

Could you explain why we set version 17?  `LDAP_OPT_VERSION = 0x11` I guess it is a root of the issue.

**Comment by joperezr** [comment]
We don't set it to `0x11`. When we try to set different options in the connection handle, we call into openldap's [ldap_set_option](https://www.openldap.org/software/man.cgi?query=ldap_set_option&apropos=0&sektion=0&manpath=OpenLDAP+2.6-Release&arch=default&format=html) method. This method, recieves 3 parameters, the connection handle, the option which defines which option should be set, and the value to set it to. `LDAP_OPT_VERSION` or `0x11`, is the second argument that gets passed, meaning it is defining that the value that is passed in as the third parameter should be used to select the Ldap version to be set. You can see that more clearly if you look at how we set ProtocolVersion:

https://github.com/dotnet/runtime/blob/9e795c014b0be513c84f96427c544bae486bb101/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapSessionOptions.Linux.cs#L31

As you see, that helper is essentially just calling ldap_set_option passing the handle, then 0x11 (signaling that we want to set the ldap version), and then a pointer to the passed in version value.

**Comment by stephentoub** [comment]
This PR doesn't appear to solve the associated issue (please correct me if I'm wrong).  As such, I'd prefer we close it while the issue is investigated, and then when a proper fix is understood, a new PR can be opened with that fix.

**Comment by joperezr** [comment]
Agreed. Closing for now until we validate what the actual problem is.

**Pull request closed without merging**
