### PR TITLE
Don't create duplicate ZeroInits

### PR DESCRIPTION
**Pull request by CarolEidt**

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
If you like, I'll launch the jit-expermential pipleine onthis to see if there are any EH Write Thru tests still failing.

**Comment by CarolEidt** [comment]
> If you like, I'll launch the jit-expermential pipleine onthis to see if there are any EH Write Thru tests still failing.

I think I should rebase on master to pick up your other fix?

**Comment by CarolEidt** [comment]
OK, I've rebased (should have done that before).

**Comment by AndyAyersMS** [comment]
> I think I should rebase on master to pick up your other fix?

Right, the manually launched pipelines run exactly what's on the PR branch. Will launch the other testing shortly.

**Comment by AndyAyersMS** [comment]
Down from ~320 failures to ~34 with EH Write Thru enabled. All of the failures look like unexpected null reference exceptions.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Review by AndyAyersMS — APPROVED** [review]
Thanks.

**Pull request merged**
