### PR TITLE
adjust renegotiation tests to match product change

### LINKED ISSUE #43122: SslStream renegotiate Outerloop tests are failing
```
SslStream_NetworkStream_Renegotiation_Succeeds
SslStream_AllowRenegotiation_True_Succeeds
```
are failing with `Assert.InRange() Failure\r\nRange:  (2 - 2147483647)\r\nActual: 1`

this is regression caused by #42836

### PR DESCRIPTION
**Pull request by wfurt**
With #42836 in place, RemoteValidationCallback will be called during renegotiation only if remote certificate change. 
It seems like #42836 missed to run Outerloop test. 
This was originally intended for TLS 13 where it happens on every session on Windows but it impacted other platforms and versions where we do less work now. 
 
The fix is to update impacted tests as we currently do not have good way how to test renegotiation because SslStream does not offer API to control it.  

Alternatively we can update the production change and scope it only to TLS13. In that case we can probably also address some comment from @stephentoub as SocketsHttpHandler assumes there will always be only one callback. (or we can do that independently)  

fixes  #43122

### CODE REVIEW

**Comment by geoffkizer** [comment]
This seems entirely reasonable to me.

**Comment by geoffkizer** [comment]
That said, I wonder if we should modify the tests to validate the new behavior -- meaning that the callback is *not* called a second time.

**Comment by stephentoub** [comment]
> Alternatively we can update the production change and scope it only to TLS13. In that case we can probably also address some comment from @stephentoub as SocketsHttpHandler assumes there will always be only one callback. (or we can do that independently)

What update would be needed to the product code to ensure that for < TLS13 the callback is only ever invoked at most once?  I thought that was how things already worked, but I guess I misunderstood?

And if I've understood correctly, it will always be possible with TLS13 for the callback to be invoked multiple times.  Given that, I think we need to update the signature of the callback to take an `HttpRequestMessage?`, since it can actually be null (even though it'll rarely be so).

**Comment by wfurt** [comment]
What I meant was to revert pre-13 behavior so the call-back is called on every renegotiation attempt as it used to be instead of fixing the tests. Since TLS 13 does not have renegotiation the observed behavior is because of internal Windows implementation so I think it still make sense to call the callback just once.

**Comment by stephentoub** [comment]
> What I meant was to revert pre-13 behavior so the call-back is called on every renegotiation attempt as it used to be instead of fixing the tests. Since TLS 13 does not have renegotiation the observed behavior is because of internal Windows implementation so I think it still make sense to call the callback just once.

Sorry, I'm still confused.

In .NET 5:
| Version   | Can possibly invoke callback multiple times |
|-----------|------------------------------------|
| <= TLS1.2 |                                    |
| TLS1.3    |                                    |

In master:
| Version   | Can possibly  invoke callback multiple times |
|-----------|------------------------------------|
| <= TLS1.2 |                                    |
| TLS1.3    |                                    |

Proposed:
| Version   | Can possibly  invoke callback multiple times |
|-----------|------------------------------------|
| <= TLS1.2 |                                    |
| TLS1.3    |                                    |

Can you put an X in each cell it belongs?

**Comment by wfurt** [comment]
I'm sorry for not making that clear @stephentoub. As I start filling the 'X'es I realized this is it even more complicated. So instead of just X, let me describe each cell separately. 

Let's look at it from prospective of client:
In .NET 5:
| Version   | Can possibly invoke callback multiple times |
|-----------|------------------------------------|
| <= TLS1.2 |   X -> This would generally happen late in the session. Typically client can access URL requiring client certificate and that triggers negotiation. Every time this happens, callback is called.  (generally this is rare)                       |
| TLS1.3    |  X -> This would never happen on Linux. TLS 1.3 does not support renegotiation - if server requires client certificate it needs to be negotiated upfront. It would always happen twice on Windows. In TLS 1.3 the handshake is really not done when `AuthenticateAs*` finishes. Part of the negotiation happen on first data transfer and that triggers the renegotiation logic on Windows.                                  |

In master:
| Version   | Can possibly  invoke callback multiple times |
|-----------|------------------------------------|
| <= TLS1.2 | 0/x -> While this may be possible, in practice server certificate does not change. The new code would call the callback only on certificate change e.g. null -> X or X -> Y. In case that server just wants certificate from client, there will not be extra callback.                                       |
| TLS1.3    |  0 -> TLS 1.3 does not support renegotiation so all the certificates needs to be negotiated and set up upfront.                                  |

Proposed: I'm not proposing to change the behavior from master. That seems like improvement to me as it is more consistent. However, since that broke our tests, I'm wondering if this could be considered as breaking change or if we want to preserve old behavior for some reason. So I mentioned it as possibility so people can consider it. _If_ we would make change I would envision it as:

| Version   | Can possibly  invoke callback multiple times |
|-----------|------------------------------------|
| <= TLS1.2 |  X -> behaves as 5.0 and previous releases                                  |
| TLS1.3    |   0 -> both Linux and Windows calls the callback only one. e.g. scope #42836 to only TLS 1.3                               |

let me know if this makes more sense. I do like @geoffkizer suggestion to assert that the callback is **not** called twice on typical renegotiation.

**Comment by geoffkizer** [comment]
> While this may be possible, in practice server certificate does not change.

Yeah, to be clear, I don't even think the server cert *can* change. Renegotiation as I understand it is mainly used to solicit a cert from the client when you haven't done so previously. But it can't be used to actually change the cert once you've sent it, from either client or server.

I think this is confusing because the underlying APIs here are handing us the cert multiple times, but also only giving us the actual cert when it's available. 

So I think we can and should say that the callback never fires multiple times. It fires when the cert first becomes available to us. If a subsequent renegotiation causes the OS to hand us the cert again, we should validate that it's the same cert and not fire the callback again.

**Comment by stephentoub** [comment]
Thanks, that helps clarify.

**Comment by antonfirsov** [comment]
Pinging this, because #43122 produced about 1300 failures only in the last 1 week according to Kusto.

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
