### PR TITLE
Remove uses of Rijndael from EncryptedXml where possible

### LINKED ISSUE #54145: EncryptedXml uses obsolete Rijndael* types
```
C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(549,17): error SYSLIB0022: 'RijndaelManaged' is obsolete: 'The Rijndael and RijndaelManaged types are obsolete. Use Aes instead.' [C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System.Security.Cryptography.Xml.csproj]
C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(549,44): error SYSLIB0022: 'RijndaelManaged' is obsolete: 'The Rijndael and RijndaelManaged types are obsolete. Use Aes instead.' [C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System.Security.Cryptography.Xml.csproj]
C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(598,32): error SYSLIB0022: 'Rijndael' is obsolete: 'The Rijndael and RijndaelManaged types are obsolete. Use Aes instead.' [C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System.Security.Cryptography.Xml.csproj]
C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(624,13): error SYSLIB0022: 'RijndaelManaged' is obsolete: 'The Rijndael and RijndaelManaged types are obsolete. Use Aes instead.' [C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System.Security.Cryptography.Xml.csproj]
C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(624,40): error SYSLIB0022: 'RijndaelManaged' is obsolete: 'The Rijndael and RijndaelManaged types are obsolete. Use Aes instead.' [C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System.Security.Cryptography.Xml.csproj]
C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(871,44): error SYSLIB0022: 'Rijndael' is obsolete: 'The Rijndael and RijndaelManaged types are obsolete. Use Aes instead.' [C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System.Security.Cryptography.Xml.csproj]
C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\EncryptedXml.cs(915,44): error SYSLIB0022: 'Rijndael' is obsolete: 'The Rijndael and RijndaelManaged types are obsolete. Use Aes instead.' [C:\git\runtime2\src\libraries\System.Security.Cryptography.Xml\src\System.Security.Cryptography.Xml.csproj]
```

https://github.com/dotnet/runtime/blob/9d771a26f058a9fa4a49850d4778bbab7aa79a22/src/libraries/System.Security.Cryptography.Xml/src/System.Security.Cryptography.Xml.csproj#L9-L10

cc @bartonjs @GrabYourPitchforks

### PR DESCRIPTION
**Pull request by vcsjones**
This removes uses of RijndaelManaged and replaces it with Aes since as of .NET Core, the Rijndael types were a simple shim to the AES types, anyway.

This removes the project-level warning ignore and adds targeted error supressions.

Closes #54145.

### CODE REVIEW

**Review by bartonjs — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Comment by bartonjs** [comment]
Most overly signed off change ever? :smile:

**Comment by bartonjs** [comment]
Interestingly, we already did this fix in .NET Framework.  And fixed that the value didn't get disposed.

https://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/encryptedxml.cs,546

**Comment by vcsjones** [comment]
> And fixed that the value didn't get disposed.

Eh I thought about it and decided not to, but if the Framework did it, I feel more comfortable doing it.

**Review by GrabYourPitchforks — APPROVED** [review]

**Comment by vcsjones** [comment]
@GrabYourPitchforks It looks like Pipelines are running... statuses just aren't getting reported to GitHub. https://dev.azure.com/dnceng/public/_build/results?buildId=1190227&view=results

**Comment by GrabYourPitchforks** [comment]
Per https://dev.azure.com/dnceng/public/_build/results?buildId=1189505&view=results, tests are passing except for some filesystem stuff which is already being tracked.

**Pull request merged**
