### PR TITLE
[WinHttpHandler] Move `_cachedSendPinnedBuffer` ownership to `WinHttpRequestState`

### PR DESCRIPTION
**Pull request by antonfirsov**
A race between `WinHttpRequestStream.WriteAsync` and `WinHttpRequestStream.Dispose` can lead to `Dispose` unpinning the buffer forwarded to `WinHttp`, which can potentially lead to `AccessViolationException`:

https://github.com/dotnet/runtime/blob/9fa12355097e1ac17ac44445649a381323e9c35f/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpRequestStream.cs#L254

This has been fixed in https://github.com/dotnet/corefx/pull/6500 for `WinHttpResponseStream`, this PR is applying the same fix for `WinHttpRequestStream`.

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM.

To answer https://github.com/dotnet/corefx/pull/6500/files#diff-8db7e154523836be1aa177c05ae0decb22c602791eabf11d01823c80ac9927d8R131
It seems like the WriteAsync has also similar logic to ReadAsync, right?

**Comment by antonfirsov** [comment]
> It seems like the WriteAsync has also similar logic to ReadAsync, right?

Yes:

https://github.com/dotnet/runtime/blob/017593d90781d797df8b2241f6d1f83c236c442b/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpRequestStream.cs#L131-L135

Note that the logic is prone to races in both streams, but that's beyond this PR.

**Review by karelz — APPROVED** [review]

**Comment by antonfirsov** [comment]
There are [possibly related outerloop failures](https://dev.azure.com/dnceng-public/public/_build/results?buildId=660993&view=ms.vss-test-web.build-test-results-tab&runId=16385836&resultId=108160&paneView=debug), this needs investigation.

**Comment by antonfirsov** [comment]
After a second look and more testing, the failures look unrelated:
- `SendAsync_SlowServerRespondsAfterDefaultReceiveTimeout_ThrowsHttpRequestException` is #96481
- `InvalidCertificateServers_CertificateValidationDisabled_Succeeds` also failed in an extensive run without changes, see #101939. The most likely root case is a connection issue to `badssl.com`.
- `UseCallback_BadCertificate_ExpectedPolicyErrors` also failed for `SocketsHttpHandler` in the previous run, but did not fail in reruns. This again implies that the most likely root case is a connection issue.

I will do a couple of further outerloop reruns before merging this.

**Comment by antonfirsov** [comment]
All test failures are unrelated, merging.

**Pull request merged**
