### PR TITLE
[browser][MT] test GC

### PR DESCRIPTION
**Pull request by pavelsavara**
testing GC

### CODE REVIEW

**Comment by pavelsavara** [comment]
Something about this leaks like crazy
```
[STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.VeryLongRunningGC(executor: Main)
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 713K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (user request) time 8.26ms, stw 8.29ms los size: 0K in use: 0K
dotnet.native.js:993 GC.GetTotalMemory: 4625048
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 293K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (user request) time 6.43ms, stw 6.62ms los size: 262208K in use: 262144K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 293K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (user request) time 3.91ms, stw 3.93ms los size: 262208K in use: 262144K
dotnet.native.js:993 GC.GetTotalMemory: 273061440

....

GC.GetTotalMemory: 1346809184
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 295K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (user request) time 3.11ms, stw 3.15ms los size: 1573248K in use: 1572864K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 295K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (user request) time 4.04ms, stw 4.07ms los size: 1573248K in use: 1572864K
dotnet.native.js:993 GC.GetTotalMemory: 1615244656
dotnet.native.js:993 [FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.VeryLongRunningGC(executor: ThreadPool)
dotnet.native.js:993 System.OutOfMemoryException : Out of memory
dotnet.native.js:993    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.<>c.<VeryLongRunningGC>b__18_0() in C:\Dev\runtime\src\libraries\System.Runtime.InteropServices.JavaScript\tests\System.Runtime.InteropServices.JavaScript.UnitTests\System\Runtime\InteropServices\JavaScript\WebWorkerTest.cs:line 501
dotnet.native.js:993    at System.Runtime.InteropServices.JavaScript.Tests.Executor.<>c__DisplayClass7_0.<Execute>g__wrapExecute|0() in C:\Dev\runtime\src\libraries\System.Runtime.InteropServices.JavaScript\tests\System.Runtime.InteropServices.JavaScript.UnitTests\System\Runtime\InteropServices\JavaScript\WebWorkerTestHelper.cs:line 161
dotnet.native.js:993    at System.Threading.Tasks.Task`1[[System.Threading.Tasks.Task, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke() in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Tasks\Future.cs:line 501
dotnet.native.js:993    at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj) in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 2383
dotnet.native.js:993    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object ) in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\ExecutionContext.cs:line 264
dotnet.native.js:993 --- End of stack trace from previous location ---
dotnet.native.js:993    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread , ExecutionContext , ContextCallback , Object ) in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\ExecutionContext.cs:line 289
dotnet.native.js:993    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& , Thread ) in C:\Dev\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\Tasks\Task.cs:line 2345
dotnet.native.js:993 --- End of stack trace from previous location ---
dotnet.native.js:993    at System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.VeryLongRunningGC(Executor executor) in C:\Dev\runtime\src\libraries\System.Runtime.InteropServices.JavaScript\tests\System.Runtime.InteropServices.JavaScript.UnitTests\System\Runtime\InteropServices\JavaScript\WebWorkerTest.cs:line 484
dotnet.native.js:993 --- End of stack trace from previous location ---
```

**Comment by pavelsavara** [comment]
Current code will cause `LOS overflow` and then deadlock ??

```
Starting:    System.Runtime.InteropServices.JavaScript.Tests.dll
dotnet.native.js:993 [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.VeryLongRunningGC
dotnet.native.js:993 VeryLongRunningGC NewThread 0
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 696K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 9.15ms, stw 9.20ms los size: 16512K in use: 16384K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 285K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 4.19ms, stw 4.43ms los size: 33024K in use: 32768K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 286K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 4.20ms, stw 4.26ms los size: 49536K in use: 49152K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 286K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 4.34ms, stw 4.76ms los size: 74304K in use: 73728K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 286K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 4.42ms, stw 4.45ms los size: 107328K in use: 106496K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 286K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 4.41ms, stw 4.43ms los size: 148608K in use: 147456K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 286K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 4.45ms, stw 4.49ms los size: 206400K in use: 204800K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 286K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 4.52ms, stw 4.55ms los size: 280704K in use: 278528K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 286K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 4.36ms, stw 4.39ms los size: 379776K in use: 376832K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 286K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 5.71ms, stw 5.74ms los size: 511872K in use: 507904K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 287K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 4.40ms, stw 4.43ms los size: 685248K in use: 679937K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 286K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 4.32ms, stw 4.44ms los size: 916416K in use: 909313K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 288K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 5.66ms, stw 5.69ms los size: 1221888K in use: 1212418K
dotnet.runtime.js:1296 [MONO] GC_MAJOR_SWEEP: major size: 3456K in use: 287K empty reserved: 0K
dotnet.runtime.js:1296 [MONO] GC_MAJOR: (LOS overflow) time 4.47ms, stw 4.50ms los size: 1626432K in use: 1613827K
```

**Comment by lambdageek** [comment]
@BrzVlad There's something going on with large object allocations on multi-threaded wasm (and possibly elsewhere).  

Two cases:

if `size > SGEN_MAX_SMALL_OBJ_SIZE && size <= LOS_SECTION_OBJECT_LIMIT`, in this case (for example if we allocate `new long[100*1024]` the LOS memory management seems to be working properly.  We see log messages about collections and the los size stays roughly constant.


if `size > LOS_SECTION_OBJECT_LIMIT` it looks like we never return the memory to the OS properly or we keep asking for more memory.

on the freeing side, I think we're supposed to end up here

https://github.com/dotnet/runtime/blob/4eadfbea0bb863050959559916d0503e647cc8f5/src/mono/mono/utils/mono-mmap-wasm.c#L168-L190

and then in emscripten's `munmap`:

https://github.com/emscripten-core/emscripten/blob/aef81424cdd99be99e62f995cbb37248434b8df5/system/lib/libc/emscripten_mmap.c#L52-L93

but what we see is the LOS grows bigger and bigger.
Maybe it's because we do this:

https://github.com/dotnet/runtime/blob/4eadfbea0bb863050959559916d0503e647cc8f5/src/mono/mono/sgen/sgen-los.c#L442-L459

as far as I can tell this is all fine - I think we pass `addr` and `size` of the huge object aligned back to the page sizes so we should be passing exactly the same values that we passed to `mono_valloc`.

On the allocation side, I think things might be a bit wrong:

does `sgen_ensure_free_space` always try to reserve some space from the OS even if `size` is too big?  We never end up using the LOS space if the object is bigger than the LOS section size.

https://github.com/dotnet/runtime/blob/main/src/mono/mono/sgen/sgen-los.c#L442-L459

It looks like maybe `sgen_ensure_free_space` always ends up taking some memory, even if `size > LOS_SECTION_OBJECT_LIMIT` and we never even use the LOS memory.  Is that possible?

**Comment by pavelsavara** [comment]
I pushed simpler repro as `src/mono/sample/wasm/browser/Program.cs` in this PR

**Comment by lambdageek** [comment]
@BrzVlad I usually do `/build.sh --os browser -c Release /p:MonoWasmBuildVariant=multithread /p:KeepNativeSymbols=true  /p:WasmNativeDebugSymbols=true /p:MonoEnableAssertMessages=true`


I'm going to try to see if I can repro the problem with the single-threaded runtime or in a osx-arm64 console app, too.

**Comment by lambdageek** [comment]
@BrzVlad I can repro in a console app.  I made a new issue https://github.com/dotnet/runtime/issues/97991

**Comment by pavelsavara** [comment]
@BrzVlad @lambdageek 

`/p:MonoWasmBuildVariant` is no longer a thing. We refactored it and now it's `/p:WasmEnableThreads=true`

**Comment by pavelsavara** [comment]
Looks OK now, thanks @BrzVlad 

```
info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerTest.VeryLongRunningGC
  info: VeryLongRunningGC 0
  info: GC.GetTotalMemory: 105297488
  info: GC.GetTotalMemory: 105297512
  info: GC.GetTotalMemory: 105297512
  info: GC.GetTotalMemory: 71743064
  info: GC.GetTotalMemory: 71743064
  info: GC.GetTotalMemory: 71743064
  info: GC.GetTotalMemory: 105297512
  info: GC.GetTotalMemory: 105297512
  info: VeryLongRunningGC 1
  info: GC.GetTotalMemory: 172406920
  info: GC.GetTotalMemory: 105298024
  info: GC.GetTotalMemory: 105298024
  info: GC.GetTotalMemory: 105298024
  info: GC.GetTotalMemory: 105298024
  info: GC.GetTotalMemory: 105298024
  info: GC.GetTotalMemory: 105298024
  info: GC.GetTotalMemory: 71743576
  info: VeryLongRunningGC 2
  info: GC.GetTotalMemory: 71743592
  info: GC.GetTotalMemory: 138852488
  info: GC.GetTotalMemory: 138852488
  info: GC.GetTotalMemory: 172406936
  info: GC.GetTotalMemory: 105298040
  info: GC.GetTotalMemory: 71743592
  info: GC.GetTotalMemory: 105298040
  info: VeryLongRunningGC 3
  info: GC.GetTotalMemory: 105297256
  info: GC.GetTotalMemory: 105297256
  info: GC.GetTotalMemory: 71742808
  info: GC.GetTotalMemory: 105297256
  info: GC.GetTotalMemory: 71742808
  info: GC.GetTotalMemory: 71742808
  info: GC.GetTotalMemory: 71742808
  info: VeryLongRunningGC 4
  info: GC.GetTotalMemory: 71742824
  info: GC.GetTotalMemory: 71742824
  info: GC.GetTotalMemory: 71742824
  info: GC.GetTotalMemory: 71742824
  info: GC.GetTotalMemory: 71742824
  info: GC.GetTotalMemory: 71742824
  info: GC.GetTotalMemory: 71742824
  info: VeryLongRunningGC 5
  info: GC.GetTotalMemory: 105297360
  info: GC.GetTotalMemory: 105297360
  info: GC.GetTotalMemory: 71742912
  info: GC.GetTotalMemory: 138851808
  info: GC.GetTotalMemory: 105297360
  info: GC.GetTotalMemory: 105297360
  info: GC.GetTotalMemory: 71742912
  info: VeryLongRunningGC 6
```

**Pull request closed without merging**
