### PR TITLE
[mono][wasm] Fix a performance regression introduced by #97096.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
@radekdoulik

**Comment by vargaz** [comment]
Fixes https://github.com/dotnet/runtime/issues/98522.

**Comment by lateralusX** [comment]
@vargaz what happened? Did we end up hitting a case where we reported is_supported as true for a generic type where we should have reported false?

**Comment by lateralusX** [comment]
OK, pretty sure that was an issue on some other platforms, that's why I added support for T_BYTE, since it was inline with what the implementation of IsSupported returned in its managed implementation. Maybe this is just an issue on some platforms?

**Comment by vargaz** [comment]
With our gsharing implementation, T_BYTE can stand for enums whose basetype is byte as well, so we can't return true for Vector<T_BYTE>.IsSupported. With that code removed, we now hit this code:
```
	if (!MONO_TYPE_IS_VECTOR_PRIMITIVE (etype)) {
		return NULL;
	}

So the IsSupported call is not intrinsified, so it will fall back to the managed implementation which does the right thing.

The perf regression is some other issue which is also fixed with this change.

**Review by lambdageek — APPROVED** [review]

**Review by fanyang-mono — APPROVED** [review]

**Pull request merged**
