### PR TITLE
[wasm] Do not run embuilder minimal build

### PR DESCRIPTION
**Pull request by radekdoulik**
emsdk has now the the cache primed https://github.com/dotnet/emsdk/pull/315, so we don't need to run embuilder minimal build in `WasmApp.Native.targets` anymore. That avoids writing into cache, which is located in installed nuget and can be read only.

### CODE REVIEW

**Review by pavelsavara — APPROVED** [review]

**Comment by lewing** [comment]
Is the cache prepopulated in the helix images too?

**Comment by radekdoulik** [comment]
Lets try to use the default cache for AOT tests again.

One of the tests timeouted in the last build. Probably the first one to build.

```
  system_libs:INFO: compiled 21 inputs
  cache:INFO:  - ok
  cache:INFO: generating system asset: symbol_lists/f071237d11694561702b3c0c06c6cd2d1359efbc.txt... (this will be cached in "C:\Users\ContainerAdministrator\.emscripten-cache\symbol_lists\f071237d11694561702b3c0c06c6cd2d1359efbc.txt" for subsequent builds)
  cache:INFO: generating system asset: sysroot\lib\wasm32-emscripten\struct_info.json... (this will be cached in "C:\Users\ContainerAdministrator\.emscripten-cache\sysroot\lib\wasm32-emscripten\struct_info.json" for subsequent builds)
...
[17:16:55] info: Starting:    System.Net.WebSockets.Client.Tests.dll
[17:16:55] warn: WARNING: Web browsers do not support closing the output side of a WebSocket. CloseOutputAsync has closed the socket and discarded any incoming messages.
[17:16:56] fail: [out of order message from the browser]: http://127.0.0.1:49224/dotnet.js 2 WebSocket connection to 'ws://127.0.0.1:49224/WebSocket/EchoWebSocket.ashx?subprotocol=CustomProtocol' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request: CustomProtocol
[17:16:56] fail: [out of order message from the browser]: http://127.0.0.1:49224/dotnet.js 2 WebSocket connection to 'wss://127.0.0.1:49225/WebSocket/EchoWebSocket.ashx?subprotocol=CustomProtocol' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request: CustomProtocol
[17:16:56] fail: [out of order message from the browser]: http://127.0.0.1:49224/dotnet.js 2 WebSocket connection to 'ws://127.0.0.1:49275/' failed: Connection closed before receiving a handshake response
[17:16:58] fail: [out of order message from the browser]: http://127.0.0.1:49224/dotnet.js 2 WebSocket connection to 'ws://278ce290cae04b17bd9de225189217d6/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
[17:46:52] fail: Tests timed out. Killing driver service pid 3916
[17:46:52] fail: Application has finished with exit code TIMED_OUT but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

**Pull request merged**
