### PR TITLE
[PERF][MAUI]dotnet-podcast startup time and size measurements

### PR DESCRIPTION
**Pull request by naricc**
Changes to run the dotnet-podcast app in both CI, for both size and start up time.

### CODE REVIEW

**Comment by naricc** [comment]
I have this building the dotnet-podcast app in CI, but it is not yet running. I can't see the error because of some issue with retrieving logs from helix. I am blocked on this until that is resolved.

**Comment by naricc** [comment]
I needed to make additional changes to the podcast app, because it was crashing on startup. I am now attempting to see if it will run in CI.

**Review by LoopedBard3 — APPROVED** [review]
LGTM

**Comment by naricc** [comment]
There are a few runtime test failures, but they appear to be spurious. We made no runtime changes, an didn't even touch the related templates. So I am merging this.

**Pull request merged**
