### PR TITLE
Fixed Memory leak in src/libraries/Native/Unix/System.Security.Cryptography.Native.Apple/pal_seckey.c (#1975)

### LINKED ISSUE #1975: Memory leak in src/libraries/Native/Unix/System.Security.Cryptography.Native.Apple/pal_seckey.c
As part of our testing, we have detected a memory leak. At line 163 in ExportImportKey we make a call to SecItemImport which returns the CFArray outItems. This array is never released.

Additional information from our memory leak detection tool:
```
STACK OF 1 INSTANCE OF 'ROOT LEAK: <NSMutableArray>':
[thread 0]:
80  libdyld.dylib                      0x7fff7f4c23d5 start + 1
79  com.microsoft.Excel                   0x10f046d22 main + 34
78  com.microsoft.Excel                   0x112d4f487 XLMain + 103
77  com.apple.AppKit                   0x7fff50b53d7c NSApplicationMain + 777
76  com.apple.AppKit                   0x7fff50b6483c -[NSApplication run] + 699
75  com.apple.AppKit                   0x7fff50b6a71f -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
74  com.apple.AppKit                   0x7fff50b6bc7e _DPSNextEvent + 1724
73  com.apple.HIToolbox                0x7fff527dae97 AEProcessAppleEvent + 54
72  com.apple.AE                       0x7fff54734b01 aeProcessAppleEvent + 414
71  com.apple.AE                       0x7fff54734c29 dispatchEventAndSendReply(AEDesc const*, AEDesc*) + 41
70  com.apple.AE                       0x7fff54735397 aeDispatchAppleEvent(AEDesc const*, AEDesc*, unsigned int, unsigned char*) + 1815
69  com.microsoft.Excel                   0x112dd0eb5 ExcelAEHandler(AEDesc const*, AEDesc*, void*) + 229
68  com.microsoft.Excel                   0x115f75db3 CEAEPreHandler(AEDesc const*, AEDesc*, void*) + 131
67  com.microsoft.Excel                   0x115f779a2 ProcessCEAppleEvent(OpaqueCEAEHandlerRef*, AEDesc const*, AEDesc*) + 546
66  com.microsoft.Excel                   0x115f779fa InvokeAEEventHandlerUPP + 42
65  com.microsoft.Excel                   0x112ad89ee smXLImpEvent(AEDesc const*, AEDesc*, void*) + 38190
64  com.microsoft.Excel                   0x112adfdb8 smXLImp::DoRunInProcTests(AEDesc const*, AEDesc*, void*) + 56
63  com.microsoft.Excel                   0x112e9acd8 LocalsmXLDoRunInProcTests(void*, AEDesc const*, AEDesc*, void*) + 264
62  com.microsoft.Excel                   0x118cddbb2 _X_HrAppRunInProcTests + 482
61  com.microsoft.Excel                   0x1191f8041 HrAppRunInProcTests + 33
60  com.microsoft.Excel                   0x112f4f174 HrRunInProcTestsXL + 356
59  com.microsoft.Excel                   0x10f0d26c1 -[XLAppDelegate(InProc) FRunInProcTests:] + 49
58  com.microsoft.Excel                   0x10feaf9b1 FRunInProcTestCore(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 1521
57  com.microsoft.Excel                   0x10f135e54 InProcHarness::executeMotifTest(std::__1::basic_string<wchar_t, wc16::wchar16_traits, std::__1::allocator<wchar_t> >, std::__1::basic_string<wchar_t, wc16::wchar16_traits, std::__1::allocator<wchar_t> >) + 276
56  com.microsoft.Excel                   0x10f135d16 InProcHarness::runGroupOrSingleUnitTest(__CFString const*, __CFString const*) + 134
55  com.microsoft.Excel                   0x112a5f95c UTExecuteSingleUnitTest + 124
54  com.microsoft.Excel                   0x112a6200f UTestImpl::ExecuteSingleTest(__CFString const*, __CFString const*, UTTestGroupType, void const*, void const**) + 447
53  com.microsoft.Excel                   0x112a64028 MbuTestGroup::FExecuteSingleTest(__CFString const*, void const*, void const**) + 184
52  com.microsoft.Excel                   0x112a5f362 TestHolder::FExecuteTest(_UTTestAPI const*, void*, void const*, void const**) + 178
51  com.microsoft.Excel                   0x112a603c1 NamedTest::FExecute(_UTTestAPI const*, void*, ...) + 65
50  com.microsoft.Excel                   0x112a55003 MBUUnitTestBridge::TestRunner(__CFString const*, __CFString const*) + 419
49  com.microsoft.Excel                   0x112a5db17 UnitTestCollection::RunUnitTestMethod(UnitTestString const&, UnitTestString const&) + 151
48  com.microsoft.Excel                   0x112a5d3aa UnitTestCollection::RunUnitTestMethodImplementation(UnitTestString const&, UnitTestString const&) + 90
47  com.microsoft.Excel                   0x112a5c6f8 UnitTestCollection::RunTestAction(RunnableMotifTest*, void (*)(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&)) + 72
46  com.microsoft.Excel                   0x112a5c7d7 UnitTestCollection::TryInvokeTestAction(UnitTestRunner*, RunnableMotifTest*, void (*)(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&)) + 135
45  com.microsoft.Excel                   0x112a5c87d bool Motif::ActionRunner::Run<UnitTestCollection::TryInvokeTestAction(UnitTestRunner*, RunnableMotifTest*, void (*)(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&))::$_0>(UnitTestCollection::TryInvokeTestAction(UnitTestRunner*, RunnableMotifTest*, void (*)(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&))::$_0 const&, TestErrorLogger&, Motif::IExceptionHandler const&) + 45
44  com.microsoft.Excel                   0x112a5e08b bool Motif::ActionRunner::RunWithCPPExceptionHandling<UnitTestCollection::TryInvokeTestAction(UnitTestRunner*, RunnableMotifTest*, void (*)(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&))::$_0>(UnitTestCollection::TryInvokeTestAction(UnitTestRunner*, RunnableMotifTest*, void (*)(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&))::$_0 const&, TestErrorLogger&, Motif::IExceptionHandler const&) + 75
43  com.microsoft.Excel                   0x112a5e251 bool Motif::ActionRunner::RunWithStructuredExceptionHandling<UnitTestCollection::TryInvokeTestAction(UnitTestRunner*, RunnableMotifTest*, void (*)(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&))::$_0>(UnitTestCollection::TryInvokeTestAction(UnitTestRunner*, RunnableMotifTest*, void (*)(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&))::$_0 const&, TestErrorLogger&, Motif::IExceptionHandler const&) + 33
42  com.microsoft.Excel                   0x112a5e2d4 UnitTestCollection::TryInvokeTestAction(UnitTestRunner*, RunnableMotifTest*, void (*)(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&))::$_0::operator()() const + 52
41  com.microsoft.Excel                   0x112a5c641 UnitTestCollection::TestActionRunTest(UnitTestRunner*, RunnableMotifTest*, TestErrorLogger&) + 49
40  com.microsoft.Excel                   0x10f8506cd UnitTestRunner::RunTest(RunnableMotifTest*, TestErrorLogger&) + 29
39  com.microsoft.Excel                   0x10f8509d2 RunnableMotifTest::RunTest() + 50
38  com.microsoft.Excel                   0x10f850970 RunnableMotifTest::Run(void (MotifCppTestBase::*)(), bool) + 464
37  com.microsoft.Excel                   0x10f538384 PowerQueryTextCSVRefreshTest::LoadPowerQueryManager() + 52
36  com.microsoft.Excel                   0x113a56bb6 PowerQueryManager::HrHandleLazyLoading(XLSWORKBOOK*, bool) + 230
35  com.microsoft.Excel                   0x113a5472d PowerQueryManager::HrGetInstanceForWorkbook(IMemHeap*, XLSWORKBOOK*, bool, PowerQueryManager const**) + 141
34  com.microsoft.Excel                   0x113a54056 PowerQueryManager::HrTryCreateInstance(IMemHeap*, XLSWORKBOOK*, bool) + 454
33  com.microsoft.Excel                   0x1139c1343 PowerQueryManagerImpl::HrCreateInstanceForWorkbook(IMemHeap*, XLSWORKBOOK*, bool, PowerQueryManagerImpl**) + 1203
32  com.microsoft.Excel                   0x1139c2b69 PowerQueryManagerImpl::HrInitManagedParts(XLSWORKBOOK*) + 2377
31  com.microsoft.Excel                   0x113a44fed ClrPowerQueryFacade::HrInit(XLSWORKBOOK*, IClrHost*, IMemHeap*, PowerQueryErrorInfo*, IAddinService*, void* const*, int) + 1165
30  com.microsoft.Excel                   0x1162c8ef3 CoreClrManager::HrCreateObjectInstance(wchar_t const*, wchar_t const*, wchar_t const*, wchar_t const*, void* const*, int, void**, int*, tagVARIANT*) + 131
29  com.microsoft.Excel                   0x1162c936b CoreClrManager::HrCreateObjectInstanceImpl(wchar_t const*, wchar_t const*, wchar_t const*, void* const*, int, void**, int*) + 1067
28  libcoreclr.dylib                      0x1c9ed042b UMThunkStub + 273
27  ???                                   0x1cc4c1759 0x7fffffffffffffff + 9223372044577281882
26  ???                                   0x1cc4c24ce 0x7fffffffffffffff + 9223372044577285327
25  ???                                   0x1cc4cd1f8 0x7fffffffffffffff + 9223372044577329657
24  ???                                   0x1cc4d2437 0x7fffffffffffffff + 9223372044577350712
23  ???                                   0x1cc4dc4b5 0x7fffffffffffffff + 9223372044577391798
22  ???                                   0x1cd3f02fd 0x7fffffffffffffff + 9223372044593201918
21  ???                                   0x1cd3f07a6 0x7fffffffffffffff + 9223372044593203111
20  ???                                   0x1cc097c61 0x7fffffffffffffff + 9223372044572916834
19  ???                                   0x1cc097a1f 0x7fffffffffffffff + 9223372044572916256
18  ???                                   0x1cc097911 0x7fffffffffffffff + 9223372044572915986
17  ???                                   0x1cd3f229a 0x7fffffffffffffff + 9223372044593210011
16  ???                                   0x1cd3f6d51 0x7fffffffffffffff + 9223372044593229138
15  ???                                   0x1cd4e936f 0x7fffffffffffffff + 9223372044594221936
14  ???                                   0x1cd4e8c21 0x7fffffffffffffff + 9223372044594220066
13  ???                                   0x1cd701090 0x7fffffffffffffff + 9223372044596416657
12  ???                                   0x1cd7035fe 0x7fffffffffffffff + 9223372044596426239
11  ???                                   0x1cd6e8c44 0x7fffffffffffffff + 9223372044596317253
10  ???                                   0x1cd3f8531 0x7fffffffffffffff + 9223372044593235250
9   System.Security.Cryptography.Native.Apple.dylib        0x1c9186796 AppleCryptoNative_RsaGenerateKey + 310
8   System.Security.Cryptography.Native.Apple.dylib        0x1c9187221 ExportImportKey(OpaqueSecKeyRef**, SecExternalItemType) + 161
7   com.apple.security                 0x7fff5ebf8338 SecItemImport + 120
6   com.apple.security                 0x7fff5ebf7323 SecKeychainItemImport + 180
5   com.apple.CoreFoundation           0x7fff534cd386 +[__NSArrayM __new:::] + 36
4   com.apple.CoreFoundation           0x7fff534bc897 __CFAllocateObject2 + 15
3   libobjc.A.dylib                    0x7fff7dcef1de class_createInstance + 83
2   libsystem_malloc.dylib             0x7fff7f66f4c0 calloc + 30
1   libsystem_malloc.dylib             0x7fff7f66f540 malloc_zone_calloc + 99
0   libsystem_malloc.dylib             0x7fff7f6782eb stack_logging_lite_calloc + 107 
====
    9 (1.23K) ROOT LEAK: <NSMutableArray 0x7fb2be33b0b0> [48]
       8 (1.19K) <NSMutableArray (Storage) 0x7fb2bcd215a0> [16]
          7 (1.17K) <SecKey 0x7fb2ba871100> [80]
             5 (1.02K) <SecKeychainItem 0x7fb2be1ed590> [576]
                2 (368 bytes) <Security::CssmClient::KeyImpl 0x7fb2be3496e0> [352]
                   1 (16 bytes) 0x7fb2ba8a2720 [16]
                2 (96 bytes) 0x7fb30e629be0 [80]
                   1 (16 bytes) 0x7fb30e406bd0 [16]
             1 (80 bytes) <pthread_mutex_t 0x7fb30e6b2b20> [80]
```

### PR DESCRIPTION
**Pull request by odhanson**
Added a cleanup section that releases the CFArray outItems

Fixes #1975.

### CODE REVIEW

**Comment by odhanson** [comment]
cc: @bartonjs , @stephentoub

**Comment by danmosemsft** [comment]
Adding link to issue: https://github.com/dotnet/runtime/issues/1975

**Review by bartonjs — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
