### PR TITLE
Replace command-line parser for Crossgen2 

### PR DESCRIPTION
**Pull request by AntonLapounov**
Switch back to the old command-line parser for Crossgen2 to improve performance of parsing arguments.  The source code for the old command-line parser was taken from https://github.com/dotnet/runtimelab/tree/feature/NativeAOT/src/coreclr/src/tools/System.CommandLine.  I updated copyright comments and replaced the `System.CommandLine` namespace with `Internal.CommandLine`.

This change removes the dependency on the System.CommandLine package and reduces the unpacked size of the Crossgen2 win-x64 package by 133 KiB.  To estimate performance impact on parsing arguments, I ran Crossgen2 processes in a loop with a typical command line used by the SDK, exiting the process immediately after the arguments are parsed.  The response file contained 171 lines and had size about 25 KiB.  For that setup, the time spent parsing the arguments decreased from 153 ms to 28 ms.

Known behavior differences: the old parser displays the help text differently, it treats `-abc` as `-a -b -c`, and it does not recognize `/?`.  That may be addressed separately.

### CODE REVIEW

**Comment by AntonLapounov** [comment]
@jkotas @nattress FYI

**Comment by nattress** [comment]
Is there a reason to differ from what we have already in runtimelab with the location (`tools\System.CommandLine`) and namespace name? It will be easier to keep these copies in sync if we keep it in the same spot.

**Comment by jkotas** [comment]
It is trivial to fix the runtimelab to match. 

I like the directory in this PR better. [System.CommandLine](https://www.nuget.org/packages?q=System.CommandLine) is a real package and it is mildly confusing to use it as a name.

**Review by davidwrighton — APPROVED** [review]
The only functional difference I see in code review is that this now lets much of the code in the product see things like relative paths and such, by representing filenames as strings instead of some file object. I'd like you to run a quick test to make sure relative paths work, but otherwise this looks good.

**Comment by AntonLapounov** [comment]
Relative paths seem to work fine.  The only difference I noticed is that file names are not expanded in some diagnostic messages like "Error: No files matching {0}". Also please note that it is how it used to work before the command-line parser switch made by dotnet/coreclr#27489.

**Pull request merged**
