### PR TITLE
JIT: Fix assertion due to remorph

### LINKED ISSUE #107542: Fuzzlyn: Assertion failed '((tree->gtDebugFlags & GTF_DEBUG_NODE_MORPHED) == 0) && "ERROR: Already morphed this node!"'
On osx arm64:
```csharp
// Generated by Fuzzlyn v2.4 on 2024-09-08 16:29:27
// Run on Arm64 MacOS
// Seed: 8130614614026339575-vectort,vector64,vector128,armadvsimd,armadvsimdarm64,armaes,armarmbase,armarmbasearm64,armcrc32,armcrc32arm64,armdp,armrdm,armrdmarm64,armsha1,armsha256
// Reduced from 29.8 KiB to 0.5 KiB in 00:00:24
// Hits JIT assert in Release:
// Assertion failed '((tree->gtDebugFlags & GTF_DEBUG_NODE_MORPHED) == 0) && "ERROR: Already morphed this node!"' in 'Program:M3():uint' during 'Morph - Global' (IL size 49; hash 0x5ffe8ca8; FullOpts)
// 
//     File: /Users/runner/work/1/s/src/coreclr/jit/morph.cpp Line: 12250
// 
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

public class Program
{
    public static void Main()
    {
        M3();
    }

    public static uint M3()
    {
        var vr1 = Vector64.Create<uint>(0);
        var vr3 = (byte)0;
        var vr2 = Vector64.CreateScalar(vr3);
        var vr4 = Vector64.Create<byte>(1);
        var vr0 = Dp.DotProductBySelectedQuadruplet(vr1, vr2, vr4, 6);
        return (uint)(-9223372036854775808L & AdvSimd.Extract(vr0, 0));
    }
}
```

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by hez2010**
Extracted from #104906 

We always set `GTF_DEBUG_NODE_MORPHED` in `gtFoldExprCompare`, `gtFoldExprSpecial`, `gtFoldExprConditional` and `gtFoldExprHWIntrinsic` if the tree is morphed, but not in `gtFoldExprConst` as it may creates a new tree that can be morphed again.
Especially, `gtFoldExprSpecial` can create a new `COMMA` containing a subtree of side effects, which leads to the assertion later when we try to remorph it, as `newTree != oldTree` can yield false positives for this. The subtree of `COMMA` is already morphed anyway so in this case we can avoid morphing it again by using a flag instead of relying on `newTree != oldTree`.

Fixes #107542 

cc: @AndyAyersMS

### CODE REVIEW

**Comment by hez2010** [comment]
[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889590&view=ms.vss-build-web.run-extensions-tab)

**Comment by jakobbotsch** [comment]
`gtFoldExprConst` is already conditioned on `fgGlobalMorph` when it folds overflowing arithmetic into a helper call. Can we just invoke morph from there in that case? It's not elegant, but it seems more elegant than this fix.

**Comment by hez2010** [comment]
The issue here is that `gtFoldExprSpecial` can create a new `COMMA` while its subtree is already morphed, so that the tree returned by `gtFoldExpr` is not equal to neither `op1` nor `op2`. Then `tree->AsOp()->gtOp1 = fgMorphTree(tree->AsOp()->gtOp1);` caused the tree to be morphed again which leads to the assertion.

Regarding to the fix, in global morph, do we really need to morph `op1` again? I think it should already be morphed anyway.

**Comment by hez2010** [comment]
Let's see how CI going

**Comment by hez2010** [comment]
Okay it becomes `Assertion failed '(tree->gtDebugFlags & GTF_DEBUG_NODE_MORPHED) && "ERROR: Did not morph this node!"` now. 

> I think it should already be morphed anyway.

Seems that this is not true.

**Comment by hez2010** [comment]
> Can we just invoke morph from there in that case? It's not elegant, but it seems more elegant than this fix.

It seems that similar patterns can also be produced by `gtFoldExprHWIntrinsic` and it's really not obvious where should we put the invocation. I would like to leave it as is to keep the fix simple instead.

**Comment by jakobbotsch** [comment]
> > Can we just invoke morph from there in that case? It's not elegant, but it seems more elegant than this fix.
> 
> It seems that similar patterns can also be produced by `gtFoldExprHWIntrinsic` and it's really not obvious where should we put the invocation. I would like to leave it as is to keep the fix simple instead.

What problem did you hit? `gtFoldExprConst` introduces a helper call in some cases. Morphing of a new helper call is very much necessary. But I don't see `gtFoldExprHWIntrinsic` introducing helper calls, and the point where it is invoked by morph makes me think that it should be unnecessary to call morph on anything in there.

**Comment by jakobbotsch** [comment]
I opened #110658 as an example of what I meant. Does this fix the assertion for the case in the issue, and for your own case?

**Comment by hez2010** [comment]
> I opened #110658 as an example of what I meant. Does this fix the assertion for the case in the issue, and for your own case?

Thanks! I will check it and see whether it fixes the issue I hit or not.

**Comment by AndyAyersMS** [comment]
Likely obsoleted by #110787

**Comment by hez2010** [comment]
Okay, I'm closing this PR.

**Pull request closed without merging**
