### PR TITLE
[7.0.0-test] Version.props changes for build test

### PR DESCRIPTION
**Pull request by carlossanlop**
As requested in the instructions.

### CODE REVIEW

**Review by smasher164 — APPROVED** [review]

**Comment by carlossanlop** [comment]
@ViktorHofer @ericstj I am unsure if my changes are all we need to do. The instructions say: 

> Set 7.0.0-test "StabilizePackageVersion" to true (if it's in the Versions.props), **and all other necessary changes needed for a stable build**

Do we need to add other changes to consider the build "stable"?

**Comment by ViktorHofer** [comment]
@carlossanlop is it intentional that builds didn't run?

**Comment by akoeplinger** [comment]
We only trigger on `main` and `release/*` in the .yml. I hit the same issue in emsdk and had to schedule a manual build through AzDO.

**Comment by ViktorHofer** [comment]
Does the instruction force the name to be 7.0.0-test or can it instead be release/7.0.0-test?

**Comment by ViktorHofer** [comment]
Closing as this should be done in the internal repository: dnceng/internal.

**Pull request closed without merging**
