### PR TITLE
Allow using SupportedOSPlatform, UnsupportedOSPlatform attributes on interfaces 

### LINKED ISSUE #47599: Allow using `SupportedOSPlatformAttribute` on interfaces
## Background and Motivation

This is a slight addition to the existing `[SupportedOSPlatform]` attribute type.

For Xamarin (iOS, tvOS, macOS and Catalyst) we expose Objective-C protocols as .net interfaces. However the current implementation of `SupportedOSPlatformAttribute` [1] does not let us annotate interfaces.

Apple does include versioning information for their protocols and the current version of Xamarin SDK do support this feature (with our own attributes).

The lack of support for annotating interface is blocking the completion of https://github.com/xamarin/xamarin-macios/issues/10170

[1] https://docs.microsoft.com/en-us/dotnet/api/system.runtime.versioning.supportedosplatformattribute?view=net-5.0

## Proposed API

Add `AttributeTargets.Interface` to `SupportedOSPlatformAttribute`

```diff
[System.AttributeUsage(System.AttributeTargets.Assembly | System.AttributeTargets.Class |
System.AttributeTargets.Constructor | System.AttributeTargets.Enum | System.AttributeTargets.Event |
System.AttributeTargets.Field | System.AttributeTargets.Method | System.AttributeTargets.Module |
+ System.AttributeTargets.Interface |
System.AttributeTargets.Property | System.AttributeTargets.Struct, AllowMultiple=true, Inherited=false)]
public sealed class SupportedOSPlatformAttribute : System.Runtime.Versioning.OSPlatformAttribute
```

## Usage Examples

This is how an existing generated interface for a protocol looks like:

``` C#
[Introduced (PlatformName.WatchOS, 6,0, ObjCRuntime.PlatformArchitecture.All)]
[Introduced (PlatformName.iOS, 7,0, ObjCRuntime.PlatformArchitecture.All)]
[Protocol (Name = "AVPlayerItemOutputPushDelegate", WrapperType = typeof (AVPlayerItemOutputPushDelegateWrapper))]
[ProtocolMember (IsRequired = false, IsProperty = false, IsStatic = false, Name = "OutputSequenceWasFlushed", Selector = "outputSequenceWasFlushed:", ParameterType = new Type [] { typeof (AVPlayerItemOutput) }, ParameterByRef = new bool [] { false })]
public partial interface IAVPlayerItemOutputPushDelegate : INativeObject, IDisposable
{
}
```

And we would like to be able to do this for .net6

```csharp
[SupportedOSPlatform ("watchos6.0")]
[SupportedOSPlatform ("ios7.0")]
[Protocol (Name = "AVPlayerItemOutputPushDelegate", WrapperType = typeof (AVPlayerItemOutputPushDelegateWrapper))]
[ProtocolMember (IsRequired = false, IsProperty = false, IsStatic = false, Name = "OutputSequenceWasFlushed", Selector = "outputSequenceWasFlushed:", ParameterType = new Type [] { typeof (AVPlayerItemOutput) }, ParameterByRef = new bool [] { false })]
public partial interface IAVPlayerItemOutputPushDelegate : INativeObject, IDisposable
{
}
```

## Alternative Designs

Annotating only interface members is possible but:
* this requires changes to the generator;
* there are thousands of extra annotations that will increase the platform assemblies, affecting build and deploy times;

## Risks

The existing analyzers might need to consider interfaces (if they do not scan them already).

### PR DESCRIPTION
**Pull request by buyaa-n**
Fixes https://github.com/dotnet/runtime/issues/47599

cc @jeffhandley @terrajobst @spouliot

### CODE REVIEW

**Review by spouliot — APPROVED** [review]
😄

**Comment by buyaa-n** [comment]
I have got `ApiCompat` error on many builds:
```
src/libraries/shims/ApiCompat.proj(116,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) CannotChangeAttribute : Attribute 'System.AttributeUsageAttribute' on 'System.Runtime.Versioning.SupportedOSPlatformAttribute' changed from '[AttributeUsageAttribute(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Constructor | AttributeTargets.Enum | AttributeTargets.Event | AttributeTargets.Field | AttributeTargets.Method | AttributeTargets.Module | AttributeTargets.Property | AttributeTargets.Struct, AllowMultiple=true, Inherited=false)]' in the contract to '[AttributeUsageAttribute(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Constructor | AttributeTargets.Enum | AttributeTargets.Event | AttributeTargets.Field | AttributeTargets.Interface | AttributeTargets.Method | AttributeTargets.Module | AttributeTargets.Property | AttributeTargets.Struct, AllowMultiple=true, Inherited=false)]' in the implementation.

src/libraries/shims/ApiCompat.proj(123,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) ApiCompat failed comparing net5.0 to netcoreapp
```
Not sure how handle it, I think it is expected, so probably add the error into [ApiCompatBaseline.PreviousNetCoreApp.txt](https://github.com/ViktorHofer/runtime/blob/main/src/libraries/shims/ApiCompatBaseline.PreviousNetCoreApp.txt)?

cc @ericstj @ViktorHofer @safern @Anipik

**Comment by safern** [comment]
> Not sure how to handle it, but I think it is expected, so probably add the error into ApiCompatBaseline.PreviousNetCoreApp.txt?

Yeah, or after doing a build locally you can run: 
```
dotnet msbuild src/libraries/shims/ApiCompat.proj /p:BaselineApiCompat=true
```

This will add the necessary entries to `ApiCompatBaseline.PreviousNetCoreApp.txt`

**Comment by buyaa-n** [comment]
> Yeah, or after doing a build locally you can run:
> 
> `dotnet msbuild src/libraries/shims/ApiCompat.proj /p:BaselineApiCompat=true`
> 
> This will add the necessary entries to ApiCompatBaseline.PreviousNetCoreApp.txt

Hm somehow the command did not update `ApiCompatBaseline.PreviousNetCoreApp.txt` instead it updated `ApiCompatBaseline.netcoreapp.netfx461.txt` and added thousands of rows

**Comment by buyaa-n** [comment]
Seems i also need to add `/p:UpdatePreviousNetCoreAppBaseline=true` and merge with latest as its adding many other unrelated rows

**Comment by buyaa-n** [comment]
Thanks, @safern the tool updating too many rows, after update the issue numbers even decreased by 4:
```diff
-Total Issues: 102
+Total Issues: 98
```
Not sure if the tool producing consistent result, as too many updates will be difficult to review, I just updated it manually

**Comment by joperezr** [comment]
Code changes look good, but can we add tests for this?

**Comment by buyaa-n** [comment]
> Code changes look good, but can we add tests for this?

By my understanding we don't add such a test, that would be a test for an attribute functionality test. All attribute tests does only for parameter check this case: https://github.com/dotnet/runtime/blob/bd7630dee87742594f1d8ec40cb5116c8b34528b/src/libraries/System.Runtime/tests/System/Runtime/Versioning/OSPlatformAttributeTests.cs#L33-L42

**Review by jeffhandley — APPROVED** [review]

**Pull request merged**
