### PR TITLE
Support deleting "entire" stores in the VN-based dead store removal phase

### PR DESCRIPTION
**Pull request by SingleAccretion**
In the initial change, I reverted the bits needed to make this work, since it did not seem worthwhile. Since then, I came across a scenario which this helps: removing zero-initis of tracked structs that codegen is guaranteed to make "must-init", hence this improvement.

Minor positive [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=123075&view=results), with minor TP impact as well (payed for with the recent `ADDR`-related changes).

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by SingleAccretion** [comment]
`System.Private.Xml` x86 [failure](https://dev.azure.com/dnceng-public/public/_build/results?buildId=123072&view=ms.vss-test-web.build-test-results-tab&runId=2646744&resultId=196113&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab) is also present in an [earlier (few days old) run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=121847&view=ms.vss-test-web.build-test-results-tab&runId=2609926&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab&resultId=196113):

```
  Starting:    System.Private.Xml.Tests (parallel test collections = on, max threads = 4)
   System.Private.Xml.Tests: [Long Running Test] 'System.Xml.XmlConvertTests.XmlConvertTests.RunTests', Elapsed: 00:02:12

Assert failure(PID 4892 [0x0000131c], Thread: 4344 [0x10f8]): !PreemptiveGCDisabled()

CORECLR! GetCLRRuntimeHost + 0x1406D6 (0x727d78e6)
CORECLR! GetCLRRuntimeHost + 0x5A7011 (0x72c3e221)
CORECLR! coreclr_shutdown_2 + 0xAE56 (0x72c507f6)
NTDLL! RtlDecompressBuffer + 0xDE (0x778fea4e)
NTDLL! LdrShutdownThread + 0x386 (0x778ceeb6)
NTDLL! LdrSetAppCompatDllRedirectionCallback + 0x1052A (0x77923c6a)
NTDLL! LdrShutdownProcess + 0x15F (0x778e2d7f)
NTDLL! RtlExitUserProcess + 0x96 (0x778e3886)
KERNEL32! ExitProcess + 0x13 (0x7592b3e3)
CORECLR! coreclr_shutdown_2 + 0x452D8 (0x72c8ac78)
    File: D:\a\_work\1\s\src\coreclr\vm\threads.cpp Line: 979
    Image: C:\h\w\A7CC0910\p\dotnet.exe
```

**Comment by jakobbotsch** [comment]
Is my understanding correct that we model the implicit zero init as an SSA def (that we end up getting via `defIndex - 1`), so this is removing subsequent explicit zero inits based on those?
Presumably liveness DCE would otherwise remove the first def in this particular case?

**Comment by SingleAccretion** [comment]
> Is my understanding correct that we model the implicit zero init as an SSA def (that we end up getting via defIndex - 1), so this is removing subsequent explicit zero inits based on those?

Yes, that is correct.

>  Presumably liveness DCE would otherwise (often) remove the first def in this particular case?

Liveness does not model this "implicit zero-init", so it would not remove explicit inits based on it. It is why we have a whole separate phase dedicated just to this (`optRemoveRedundantZeroInits`).

**Comment by jakobbotsch** [comment]
> Liveness does not model this "implicit zero-init", so it would not remove explicit inits based on it. It is why we have a whole separate phase dedicated just to this (`optRemoveRedundantZeroInits`).

Right, that's what I meant with "otherwise" -- I assume the "whole" case is otherwise often handled by liveness (when the explicit IR is there).

**Review by jakobbotsch — APPROVED** [review]
This looks good to me, but would like to get @AndyAyersMS's review too.

**Review by AndyAyersMS — APPROVED** [review]
At some point it would be good to think about how to update SSA, but since this opt runs last in the opt phases I suppose it doesn't matter today.

**Pull request merged**
