### PR TITLE
[wasm][windows][aot-cross] Skip ninja and cmake errors in aotcrossonly mode

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by lewing** [comment]
This appears to be breaking the rolling build.

**Comment by lewing** [comment]
Waiting while we do some checks to see what actually changed.

**Comment by lewing** [comment]
Does not look correct.

**Review by radical — APPROVED** [review]
let's try this!

**Pull request merged**
