### PR TITLE
Upgrade to msbuild version 16.10 to fix big-endian bug

### LINKED ISSUE #54826: Microsoft.NETCore.Platforms.Tests uses MSBuild version with big-endian bug
### Description

Using a Mono runtime based "dotnet" host to build and run the runtime libs.tests target currently fails with an error running the Microsoft.NETCore.Platforms.Tests test cases.

The actual command that fails is the following:
```
uweigand@m8345019:~/runtime/artifacts/bin/Microsoft.NETCore.Platforms.Tests/net6.0-Debug$ /home/uweigand/runtime/artifacts/bin/testhost/net6.0-Linux-Debug-s390x/dotnet exec --runtimeconfig Microsoft.NETCore.Platforms.Tests.runtimeconfig.json --depsfile Microsoft.NETCore.Platforms.Tests.deps.json xunit.console.dll Microsoft.NETCore.Platforms.Tests.dll -xml testResults.xml -nologo -notrait category=OuterLoop -notrait category=failing -method Microsoft.NETCore.Platforms.BuildTasks.Tests.GenerateRuntimeGraphTests.CanCreateRuntimeGraph
  Discovering: Microsoft.NETCore.Platforms.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.NETCore.Platforms.Tests (found 1 of 18 test case)
  Starting:    Microsoft.NETCore.Platforms.Tests (parallel test collections = on, max threads = 8)
    Microsoft.NETCore.Platforms.BuildTasks.Tests.GenerateRuntimeGraphTests.CanCreateRuntimeGraph [FAIL]
      System.TypeInitializationException : The type initializer for 'Microsoft.NETCore.Platforms.BuildTasks.Tests.GenerateRuntimeGraphTests' threw an exception.
      ---- Microsoft.Build.Exceptions.InvalidProjectFileException : The result "" of evaluating the value "$(_generateRuntimeGraphTask)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  /home/uweigand/runtime/artifacts/bin/Microsoft.NETCore.Platforms.Tests/net6.0-Debug/runtimeGroups.props
```

As it turns out, this is a known bug in MSBuild expression evaluation on big-endian systems, which was fixed here: https://github.com/dotnet/msbuild/pull/6204 , but the test case currently pulls in MSBuild 16.9.0, which does not yet have this fix.

### Configuration

I'm building natively on s390x-ibm-linux, using a .NET 6 Preview5 host toolchain rebuilt for s390x from the official sources (plus some extra patches required to support s390x - these are mostly backports from mainline plus pending PRs). 

### Regression?

It is a regression in the sense that the libs.tests target used to run successfully previously. But that is caused simply by the fact that the test cases exposing the problem were only added a few months back. 

### Other information

I have tried to fix the issue by updating the MSBuild requirement from 16.9.0 to 16.10.0 in eng/Versions.props:
```
Index: runtime/eng/Versions.props
===================================================================
--- runtime.orig/eng/Versions.props
+++ runtime/eng/Versions.props
@@ -140,7 +140,7 @@
       These are used as reference assemblies only, so they must not take a ProdCon/source-build
       version. Insert "RefOnly" to avoid assignment via PVP.
     -->
-    <RefOnlyMicrosoftBuildVersion>16.9.0</RefOnlyMicrosoftBuildVersion>
+    <RefOnlyMicrosoftBuildVersion>16.10.0</RefOnlyMicrosoftBuildVersion>
     <RefOnlyMicrosoftBuildFrameworkVersion>$(RefOnlyMicrosoftBuildVersion)</RefOnlyMicrosoftBuildFrameworkVersion>
     <RefOnlyMicrosoftBuildTasksCoreVersion>$(RefOnlyMicrosoftBuildVersion)</RefOnlyMicrosoftBuildTasksCoreVersion>
     <RefOnlyMicrosoftBuildUtilitiesCoreVersion>$(RefOnlyMicrosoftBuildVersion)</RefOnlyMicrosoftBuildUtilitiesCoreVersion>
```

But that simply triggers a different error now:
```
/home/uweigand/runtime/src/libraries/Microsoft.NETCore.Platforms/tests/Microsoft.NETCore.Platforms.Tests.csproj : error NU1201: Project System.Security.AccessControl is not compatible with net472 (.NETFramework,Version=v4.7.2). Project System.Security.AccessControl supports: net6.0 (.NETCoreApp,Version=v6.0)
```
This in turn seems to be caused simply by the fact that Microsoft.Build 16.10.0 now has an indirect dependency on System.Security.AccessControl which wasn't present in 16.9.0, and System.Security.AccessControl is indeed not available on net472.

If I in addition remove net472 from the TargetFrameworks list for Microsoft.NETCore.Platforms/tests/Microsoft.NETCore.Platforms.Tests.csproj, then the test builds and runs fine on net6.0 with MSBuild 16.10.0.

Any suggestions on how to proceed here would be appreciated!

### PR DESCRIPTION
**Pull request by uweigand**
* Fixes https://github.com/dotnet/runtime/issues/54826

* Adjust net472 dependencies of Microsoft.NETCore.Platforms.Tests

### CODE REVIEW

**Review by ericstj — APPROVED** [review]

**Comment by ericstj** [comment]
Actually, I might have signed off too soon.  Looks like this property is shared across many projects and is meant to be `RefOnly`  I think rather than change this we should add a reference in the test to a non-RefOnly version.

**Comment by ericstj** [comment]
Looking through the history, I made a significant change here https://github.com/dotnet/runtime/commit/75206ed0853b39501ae13219be6f55bfa7096c49#diff-1ea18ff65faa2ae6fed570b83747086d0317f5e4bc325064f6c14319a9c4ff67R142 and @radical made a change here: https://github.com/dotnet/runtime/commit/0416c3469b7bccff087b89db3d9967dfd36070a3#diff-1ea18ff65faa2ae6fed570b83747086d0317f5e4bc325064f6c14319a9c4ff67R143.

I think we're OK bumping this.  MSBuild doesn't change the assembly version in their packages, so by updating our references the worst we do is expose MSBuild API to consuming projects that may not be present in a version of MSBuild they wish to run in.

In the future it might make sense to add a DARC subscription from MSBuild -> runtime for test purposes that we use in test projects for tasks.

**Comment by uweigand** [comment]
> Actually, I might have signed off too soon. Looks like this property is shared across many projects and is meant to be `RefOnly` I think rather than change this we should add a reference in the test to a non-RefOnly version.

Is there a reason why we cannot just upgrade that version everywhere?  It was upgraded from 16.8 to 16.9 only a month ago, shouldn't it track recent releases anyway?

If we do have create a special version for this package, I guess this would mean updating this block in `src/libraries/Microsoft.NETCore.Platforms/src/Microsoft.NETCore.Platforms.csproj`:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Build" Version="$(RefOnlyMicrosoftBuildVersion)" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" Version="$(RefOnlyMicrosoftBuildTasksCoreVersion)" />
    <PackageReference Include="NuGet.ProjectModel" Version="$(RefOnlyNugetProjectModelVersion)" />
  </ItemGroup>
```
using a new property (or multiple) in eng/Versions.props, right?   I haven't added a new propery to that file before, are there any specific concerns about naming etc.?   I see some comments about automatic updates, not sure if this has to be taken into consideration.

**Comment by ericstj** [comment]
Networking failures are https://github.com/dotnet/runtime/issues/56295 and https://github.com/dotnet/runtime/issues/55957

**Pull request merged**
