### PR TITLE
Run large file test on its own

### LINKED ISSUE #67730: Test failure: System.IO.Tests.StreamReaderWithBufferedStream_Tests.ReadToEndAsync_WithCancellation
Run: [runtime-libraries-coreclr outerloop 20220407.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1704798&view=ms.vss-test-web.build-test-results-tab&runId=46435126&resultId=102087&paneView=debug)

Failed test: 
```
net7.0-Linux-Release-x64-CoreCLR_release-RedHat.7.Amd64.Open

- System.IO.Tests.StreamReaderWithBufferedStream_Tests.ReadToEndAsync_WithCancellation

```
**Error message:**
```
System.IO.IOException : No space left on device : '/tmp/StreamReaderWithBufferedStream_Tests_koju4dc4.shc/ReadToEndAsync_WithCancellation_140_a25ccac0'


Stack trace
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.BufferedFileStreamStrategy.Flush(Boolean flushToDisk)
   at System.IO.Strategies.BufferedFileStreamStrategy.Dispose(Boolean disposing)
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at System.IO.Tests.StreamReaderTests.CreateLargeFile(String path) in /_/src/libraries/System.IO/tests/StreamReader/StreamReaderTests.cs:line 188
   at System.IO.Tests.StreamReaderTests.ReadToEndAsync_WithCancellation() in /_/src/libraries/System.IO/tests/StreamReader/StreamReaderTests.cs:line 141
--- End of stack trace from previous location ---
```

### PR DESCRIPTION
**Pull request by danmoseley**
Fix https://github.com/dotnet/runtime/issues/67730

- Segregate large file StreamReader test
- Extract just problematic test from BinaryWriter.Encoding tests rather than running all of them alone; this significantly speeds up the tests.

### CODE REVIEW

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @danmoseley !

**Comment by dakersnar** [comment]
When you say you expect test speedup, do you mean like this? https://github.com/dotnet/perf-autofiling-issues/issues/4603

**Comment by danmoseley** [comment]
@dakersnar no, this is a change to the unit tests -- the change in the graph above represents the result of running the perf tests (in dotnet/performance) against the product itself.

**Comment by dakersnar** [comment]
@danmoseley Got it. I figured that might be the case, but this was my best guess considering this commit is related to BinaryWriter. I'll reopen the issue take a closer look.

**Pull request merged**
