### PR TITLE
Fix method context number seen by the jit with parallel SPMI

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The jit can see the SPMI method context number by querying the
jit host for `SuperPMIMethodContextNumber`. Update the way this
value is computed, so it gives the same answer when running SPMI
in parallel that it does when running serially.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib

**Review by BruceForstall — CHANGES_REQUESTED** [review]
I don't think this is the right way to do this. Instead, the `MethodContext::Initialize` functions should take `mcIndex` instead of `loadedCount` (actually, just rename the arguments; no change in functionality). Then, in superpmi.cpp, change:
```
        if (!MethodContext::Initialize(loadedCount, mcb.buff, mcb.size, &mc))
```
to:
```
        if (!MethodContext::Initialize(reader->GetMethodContextIndex(), mcb.buff, mcb.size, &mc))
```

**Comment by AndyAyersMS** [comment]
Thanks, will revise.

**Review by BruceForstall — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
