### PR TITLE
Updated XML documentation for `IConfigurationProvider.GetReloadToken`.

### PR DESCRIPTION
**Pull request by tacosontitan**
This PR updates the XML documentation for `IConfigurationProvider.GetReloadToken`.

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]
Thanks @tacosontitan for providing the fix.

**Comment by tarekgh** [comment]
@carlossanlop do you know if this change will get ported to the public docs? Or do we have to do it manually?

**Comment by carlossanlop** [comment]
> @carlossanlop do you know if this change will get ported to the public docs? Or do we have to do it manually?

Manually. The porting tool only ports new docs, it does not overwrite existing docs.

**Comment by tarekgh** [comment]
@tacosontitan are you interested in submitting another API to fix the public doc too? https://github.com/dotnet/dotnet-api-docs/blob/c6d149f9dcd34d1d466c7dc85bdad6e6ad5cb77b/xml/Microsoft.Extensions.Configuration/IConfiguration.xml#L74

**Comment by MaceWindu** [comment]
With this change signature doesn't match documentation. Shouldn't return value be nullable? `IChangeToken GetReloadToken();` -> `IChangeToken? GetReloadToken();`

**Comment by tacosontitan** [comment]
> With this change signature doesn't match documentation. Shouldn't return value be nullable? `IChangeToken GetReloadToken();` -> `IChangeToken? GetReloadToken();`

@MaceWindu, the prior documentation stated it would return `null` even though the return type wasn't marked as nullable.

**Comment by MaceWindu** [comment]
My bad. Anyway, it is strange to see deceptive signature.

**Pull request merged**
