### PR TITLE
[wasm] test case for broken .locals init

### PR DESCRIPTION
**Pull request by pavelsavara**
See https://github.com/dotnet/runtime/issues/71425

### CODE REVIEW

**Comment by pavelsavara** [comment]
cc @vargaz

**Comment by BrzVlad** [comment]
This just looks like https://github.com/dotnet/runtime/issues/37955. Is this showing somewhere relevant ?

**Comment by vargaz** [comment]
The failure seems to happen when tiering up.

**Comment by BrzVlad** [comment]
@pavelsavara This issue doesn't happen normally because C# requires you to initialize all vars explicitly.

**Comment by pavelsavara** [comment]
But BCL is also full of PInvoke. Are there reasons why this is not worth fixing ?

**Comment by BrzVlad** [comment]
I'm not sure I understand why this is a problem. The pinvoke signature has the argument defined as `out`. So this logically means that this argument passes no value and the native code is responsible to initialize it to whatever the result of the pinvoke is. Why would the native code rely on this variable to be already initialized to 0, given that it has to write the result to it ? If the pinvoke does expect a certain value, then you should pass `ref` and C# would force you to initialize the variable.

**Pull request closed without merging**
