### PR TITLE
Fix IParseable/ISpanParseable NumberStyles for Single and Double

### PR DESCRIPTION
**Pull request by nietras**
@tannergooding as I've detailed on my twitter account the implementations for Single and Double appear to be incorrect. I hope I have fixed them correctly in this PR.

image

### CODE REVIEW

**Comment by nietras** [comment]
Appears there already is a PR for fixing this https://github.com/dotnet/runtime/pull/59205

**Comment by tannergooding** [comment]
Thanks for trying out the preview feature and catching the issue.

As you mentioned there is already an existing PR that was up and that has now been merged: #59205

**Comment by nietras** [comment]
Sorry forgot to close myself. When will a backport to dotnet 6 be available? Do we have to wait for new RC or can we get from nightly?

**Comment by tannergooding** [comment]
The backport PR is https://github.com/dotnet/runtime/pull/59349, it will need to be merged first and then would be in the .NET 6 nightlies.

#59205 went into `main` and so should be in the .NET 7 nightlies later today.

**Comment by nietras** [comment]
@tannergooding `6.0.100-rc.2.21471.3` works like a charm now 👍

**Pull request closed without merging**
