### PR TITLE
[wasm] Add Vector128 and PackedSimd support to the jiterpreter; add PackedSimd to the interpreter

### PR DESCRIPTION
**Pull request by kg**
This updates the jiterpreter to implement simd intrinsics that were added to the interp, which removes the need for most traces using those opcodes to bail out. It operates in one of two modes:
1. Semi-native SIMD using WASM v128 opcodes. If code generation fails while this is active, it will automatically be switched off
2. Emulated SIMD using the same C functions that the interp uses to implement the opcodes, for equivalent behavior. These are called directly as wasm imports instead of via an indirect call + table lookup like in the interp.

Not all of the SIMD opcodes are implemented directly, so even with v128 opcodes turned on some of them will be dispatched to the interpreter's C. I stuck to ones I could be relatively confident I was implementing correctly, since the wasm spec's documentation for its vector opcodes is written in cipher.

Along with this I added interp opcodes for most of the PackedSimd API, with C interp intrinsics auto-generated for each one by wrapping clang's matching intrinsics.

This PR also updates genmintops to generate SIMD tables, and inlines trace entry logic because we saw a performance regression when it was outlined.

This PR also improves and unifies the imported function logic in jiterpreter-support so it's easier to work with.

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by kg** [comment]
browser-bench timings with this rebased on main:

| measurement | jiterp (v128) | jiterp (no v128) | no interp simd |
|-:|-:|-:|-:|
|         Json, non-ASCII text serialize |     2.9236ms |     3.0078ms |     2.9899ms |
|       Json, non-ASCII text deserialize |     5.5887ms |     5.7569ms |     5.5366ms |
|                  Json, small serialize |     0.1248ms |     0.1266ms |     0.1287ms |
|                Json, small deserialize |     0.2142ms |     0.2190ms |     0.2100ms |
|                  Json, large serialize |    33.3725ms |    34.3400ms |    34.7770ms |
|                Json, large deserialize |    56.4239ms |    58.3258ms |    55.8387ms |
|                    Span, Reverse bytes |     0.0210ms |     0.0736ms |     0.0892ms |
|                    Span, Reverse chars |     0.1310ms |     0.1310ms |     0.0914ms |
|                    Span, IndexOf bytes |     0.7161us |     0.8906us |     0.8870us |
|                    Span, IndexOf chars |     0.1101ms |     0.1329ms |     0.0840ms |
|              Span, SequenceEqual bytes |     0.0325ms |     0.0248ms |     0.0889ms |
|              Span, SequenceEqual chars |     0.0647ms |     0.0496ms |     0.1781ms |
|                      String, Normalize |     1.4029ms |     1.3966ms |     1.4207ms |
|                String, Normalize ASCII |     0.1752ms |     0.1732ms |     0.1752ms |
|               Vector, Create Vector128 |     0.0942us |     0.0928us |     0.0902us |
|              Vector, Add 2 Vector128's |     0.1076us |     0.1062us |     0.1133us |
|         Vector, Multiply 2 Vector128's |     0.1076us |     0.1065us |     0.1133us |
|                Vector, Dot product int |     0.1004us |     0.0998us |     0.1069us |
|              Vector, Dot product ulong |     0.0891us |     0.0878us |     0.0891us |
|              Vector, Dot product float |     0.1117us |     0.1095us |     0.1109us |
|             Vector, Dot product double |     0.0916us |     0.0909us |     0.0916us |
|                      Vector, Sum sbyte |     0.1411us |     0.1407us |     0.1417us |
|                      Vector, Sum short |     0.1100us |     0.1109us |     0.1111us |
|                       Vector, Sum uint |     0.0907us |     0.0898us |     0.0912us |
|                     Vector, Sum double |     0.0898us |     0.0893us |     0.0900us |
|                      Vector, Min float |     0.1532us |     0.1549us |     0.1592us |
|                      Vector, Max float |     0.1673us |     0.1636us |     0.1646us |
|                     Vector, Min double |     0.1197us |     0.1180us |     0.1197us |
|                     Vector, Max double |     0.1209us |     0.1194us |     0.1237us |
|                Vector, Normalize float |     0.2620us |     0.2593us |     0.4157us |

My opinion is pretty mixed based on this. It looks like there are some workloads in our bench suite here that vectorize, and the performance improves (especially if we enable native use of wasm v128 opcodes). But a lot of stuff seems to hold steady or even be worse - presumably cases where the interpreter intrinsics support isn't broad enough, so saying 'v128 is hardware accelerated'! hurts us.

Not sure what the right approach to take is with this. Maybe if we had wider support for Vector128 at the interpreter intrinsic level we'd see more gains?

@BrzVlad what do you think? I think for now it makes sense to leave `INTERP_ENABLE_SIMD` guarded with `#if !HOST_BROWSER && __GNUC__`, and to land the jiterpreter support so that we have a starting point so we can consider enabling it later. The downside is that it could potentially bitrot in this state since it would never run.

**Comment by BrzVlad** [comment]
@kg I don't think the way you test is correct, since the numbers make no sense. It is like you are testing the same thing. What does `no interp simd` mean ? Are you enabling simd in csproj ? (`WasmEnableSIMD`, I think the linker trims out vectorized bcl code if not enabled)

**Comment by kg** [comment]
> @kg I don't think the way you test is correct, since the numbers make no sense. It is like you are testing the same thing. What does `no interp simd` mean ? Are you enabling simd in csproj ? (`WasmEnableSIMD`, I think the linker trims out vectorized bcl code if not enabled)

I enable interp SIMD for the first two columns by changing
`#if !HOST_BROWSER && __GNUC__`
to
`#if __GNUC__`
which does cause interpreter simd opcodes to appear in various places as expected.

I'll retest by editing the browser-bench csproj to add that property; because SIMD had been enabled on main I thought it would be sufficient to set the constant in the interp. If the code is being trimmed out that would explain not seeing much of a difference - the opcodes I'm seeing must be for stuff that escaped trimming.

**Comment by kg** [comment]
I rebuilt the runtime with `WasmEnableSIMD` set to true, then rebuilt browser-bench with it set as well. Then I did a second rebuild of browser-bench with it set to false. The results from a run are effectively the same, I don't think that msbuild property is working in non-AOT. I have trimming disabled too.

**Comment by lewing** [comment]
@kg I merged main can you double check the legacy_cwraps bit

**Comment by kg** [comment]
> @kg I merged main can you double check the legacy_cwraps bit

Looks right

**Comment by kg** [comment]
I still have no explanation for why this performs the way it does.

| measurement | time (this PR) | time (this+AOT) | time (main)
|-:|-:|-:|-:|
|         Json, non-ASCII text serialize |     3.8978ms |     0.2363ms |     4.1681ms |
|       Json, non-ASCII text deserialize |     6.2145ms |     0.4287ms |     6.3337ms |
|                  Json, small serialize |     0.1357ms |     0.0126ms |     0.1324ms |
|                Json, small deserialize |     0.2251ms |     0.0328ms |     0.2198ms |
|                  Json, large serialize |    36.5108ms |     3.5608ms |    35.9710ms |
|                Json, large deserialize |    59.1910ms |     9.3782ms |    58.2045ms |
|                    Span, Reverse bytes |     0.0219ms |     0.0021ms |     0.1244ms |
|                    Span, Reverse chars |     0.1289ms |     0.0053ms |     0.4433ms |
|                    Span, IndexOf bytes |     0.7610us |     0.1028us |     0.0010ms |
|                    Span, IndexOf chars |     0.1153ms |     0.0028ms |     0.0864ms |
|              Span, SequenceEqual bytes |     0.0400ms |     0.0022ms |     0.0295ms |
|              Span, SequenceEqual chars |     0.0797ms |     0.0042ms |     0.0590ms |
|                      String, Normalize |     1.4766ms |     0.7871ms |     1.4346ms |
|                String, Normalize ASCII |     0.1815ms |     0.0061ms |     0.1811ms |
|               Vector, Create Vector128 |     0.0975us |     0.0449us |     0.0930us |
|              Vector, Add 2 Vector128's |     0.1103us |     0.0479us |     0.1089us |
|         Vector, Multiply 2 Vector128's |     0.1117us |     0.0453us |     0.1100us |
|                Vector, Dot product int |     0.1060us |     0.0458us |     0.1036us |
|              Vector, Dot product ulong |     0.0933us |     0.0453us |     0.0910us |
|              Vector, Dot product float |     0.1162us |     0.0449us |     0.1152us |
|             Vector, Dot product double |     0.0971us |     0.0447us |     0.0940us |
|                      Vector, Sum sbyte |     0.1494us |     0.0449us |     0.1449us |
|                      Vector, Sum short |     0.1165us |     0.0447us |     0.1150us |
|                       Vector, Sum uint |     0.0961us |     0.0446us |     0.0945us |
|                     Vector, Sum double |     0.0947us |     0.0447us |     0.0922us |
|                      Vector, Min float |     0.2321us |     0.0451us |     0.2200us |
|                      Vector, Max float |     0.2233us |     0.0447us |     0.1786us |
|                     Vector, Min double |     0.1850us |     0.0451us |     0.1859us |
|                     Vector, Max double |     0.1447us |     0.0450us |     0.1349us |
|                Vector, Normalize float |     0.2761us |     0.0493us |     0.4228us |

A handful of things like Span.Reverse and Vector.Normalize are obviously improved, some are worse like Span.IndexOf, and some of these timing samples just make no sense and make me wonder if browser-bench is broken on my hardware.

**Comment by BrzVlad** [comment]
I think it is best to investigate why `Vector, Add 2 Vector128's` is not improved since it seems the simplest and most outrageous case. You could add verbose logging to see exactly what C#/jiterp trace code is being executed and if it is correct. If my understanding is correct you are also not falling back to interp C vector methods, but are emitting directly wasm simd opcode ? If that is the case, not having a perf improvement is absurd.

**Comment by kg** [comment]
> I think it is best to investigate why `Vector, Add 2 Vector128's` is not improved since it seems the simplest and most outrageous case. You could add verbose logging to see exactly what C#/jiterp trace code is being executed and if it is correct. If my understanding is correct you are also not falling back to interp C vector methods, but are emitting directly wasm simd opcode ? If that is the case, not having a perf improvement is absurd.

It falls back to your C helpers with direct calls when it can't generate wasm simd, so I would expect everything to speed up. That's why I'm so confused, the statistics I've added show that it is engaging and only using the C helpers for a few of the intrinsics
I'll try to dump the mint opcodes for add to see what's going on there

**Review by lewing — APPROVED** [review]
it makes sense that vector ops would imply shorter traces

**Comment by kg** [comment]
| measurement | this pr | main |
|-:|-:|-:|
|         Json, non-ASCII text serialize |     3.7600ms |     4.0896ms |
|       Json, non-ASCII text deserialize |     5.9917ms |     6.2475ms |
|                  Json, small serialize |     0.1303ms |     0.1319ms |
|                Json, small deserialize |     0.2081ms |     0.2141ms |
|                  Json, large serialize |    34.8243ms |    35.2138ms |
|                Json, large deserialize |    55.2174ms |    57.1556ms |
|                    Span, Reverse bytes |     0.0211ms |     0.1213ms |
|                    Span, Reverse chars |     0.1254ms |     0.4376ms |
|                    Span, IndexOf bytes |     0.7121us |     0.8778us |
|                    Span, IndexOf chars |     0.1113ms |     0.0851ms |
|              Span, SequenceEqual bytes |     0.0389ms |     0.0293ms |
|              Span, SequenceEqual chars |     0.0776ms |     0.0582ms |
|                      String, Normalize |     1.4191ms |     1.4089ms |
|                String, Normalize ASCII |     0.1762ms |     0.1768ms |
|               Vector, Create Vector128 |     0.0850us |     0.0991us |
|              Vector, Add 2 Vector128's |     0.0839us |     0.1153us |
|         Vector, Multiply 2 Vector128's |     0.0846us |     0.1185us |
|                Vector, Dot product int |     0.1021us |     0.1162us |
|              Vector, Dot product ulong |     0.0898us |     0.0988us |
|              Vector, Dot product float |     0.1133us |     0.1253us |
|             Vector, Dot product double |     0.0950us |     0.1042us |
|                      Vector, Sum sbyte |     0.1459us |     0.1522us |
|                      Vector, Sum short |     0.1144us |     0.1217us |
|                       Vector, Sum uint |     0.0926us |     0.1009us |
|                     Vector, Sum double |     0.0925us |     0.1004us |
|                      Vector, Min float |     0.2195us |     0.2205us |
|                      Vector, Max float |     0.1818us |     0.1867us |
|                     Vector, Min double |     0.1754us |     0.1804us |
|                     Vector, Max double |     0.1348us |     0.1421us |
|                Vector, Normalize float |     0.2582us |     0.4212us |

Much better now. SequenceEqual has known problems (non-simd) already in jiterp, but will investigate

**Comment by kg** [comment]
The IndexOf Chars regression (not a big one) is because it uses some opcodes that don't have (obvious, at least) wasm v128 opcodes, so it relies on the interpreter's C helpers. It also has a lot of branching, which causes known overhead in traces that will be fixed (mostly at least) once I implement the CFG.

SequenceEqual makes less sense, I don't see anything obviously wrong with the compiled trace. But it's also a big function with a lot of branches, so CFG should help there too. My guess is the code for the v128 version of it just compiles to a less efficient trace (maybe due to how they handle alignment). Bitwise inequality (as used by SequenceEqual) does generate 3 v128 opcodes in the jiterp, which might be suboptimal. The interp C helper does two 64-bit compares instead, so it's possible that might generate better code for some reason.

**Comment by BrzVlad** [comment]
As previously mentioned, we shouldn't dive too deep into jiterp perf investigations before desktop interp is fully fixed. Current set of regressions on desktop FYI https://github.com/dotnet/perf-autofiling-issues/issues/13747

**Comment by kg** [comment]
> As previously mentioned, we shouldn't dive too deep into jiterp perf investigations before desktop interp is fully fixed. Current set of regressions on desktop FYI [dotnet/perf-autofiling-issues#13747](https://github.com/dotnet/perf-autofiling-issues/issues/13747)

Thanks, I didn't realize it was an active project in this fashion. Let me know if I can help.

**Comment by kg** [comment]
Rebased and updated with a partial PackedSimd implementation. Converting to draft for now until PS is done.

**Comment by kg** [comment]
@BrzVlad this isn't merge ready but it's close enough that I'd love to get your opinion on all the interpreter changes, so I can clean them up based on your feedback.

**Comment by kg** [comment]
@radekdoulik are there tables somewhere in the packedsimd AOT implementation I could leverage here?

**Comment by kg** [comment]
All of PackedSimd is implemented now except ExtractLane, ReplaceLane and Shuffle. Those three sets of opcodes require some new interpreter logic to handle compile-time-constant args, so for now any code using them will cause an assert in the interpreter that logs the name of the method that was used.

To implement those ones I think the interp will need hand written C intrinsics that implement those methods in a scalar dynamic fashion, and the interp will need to identify the constant arg at IR generation time. Then the jiterpreter can harvest that constant from the instruction stream and generate the correct wasm opcodes when jitting a trace.

**Comment by kg** [comment]
The custom conditional select and bitwise equality/inequality opcodes in the jiterpreter side are broken somehow, so I've disabled them. I'm not sure what's going on there since tests pass, but unless they're disabled the beginning of xharness output XML ends up going missing. This means that the interpreter C helpers get used instead, which isn't the end of the world.

**Comment by kg** [comment]
This is now blocked on real failures in the vectorized IndexOfAny code that didn't run before due to lack of PackedSimd. I am unable to come up with a satisfactory explanation for why it's not working. (Incidentally, the set of tests that fail locally is different from the set that fail on CI, and the values are different, which makes me think some sort of memory corruption or uninitialized memory.)

```

[07:08:44] info: Starting:    System.Memory.Tests.dll
[07:10:23] fail: [FAIL] System.SpanTests.ReadOnlySpanTests.DefaultFilledIndexOfMany_Char
[07:10:23] info: Assert.Equal() Failure
[07:10:23] info: Expected: 0
[07:10:23] info: Actual:   -1
[07:10:23] info:    at System.SpanTests.ReadOnlySpanTests.DefaultFilledIndexOfMany_Char()
[07:10:23] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
[07:10:23] info:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[07:11:13] fail: [FAIL] System.SpanTests.SpanTests.IndexOfAny_LastIndexOfAny_AlgComplexity_Chars
[07:11:13] info: Assert.Equal() Failure
[07:11:13] info: Expected: 7168
[07:11:13] info: Actual:   -1
[07:11:13] info:    at System.SpanTests.SpanTests.RunLastIndexOfAnyAlgComplexityTest[Char](Char[] needle)
[07:11:13] info:    at System.SpanTests.SpanTests.RunIndexOfAnyLastIndexOfAnyAlgComplexityTest[Char]()
[07:11:13] info:    at System.SpanTests.SpanTests.IndexOfAny_LastIndexOfAny_AlgComplexity_Chars()
[07:11:13] info:    at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
[07:11:13] info:    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[07:11:14] info: Finished:    System.Memory.Tests.dll
```

While I'm mildly suspicious of the vectorized code since it was previously being guarded, I don't see anything wrong with it. It's possible we're now exercising some part of the interp v128 code that we weren't before, but it doesn't seem to heavily use those APIs. I double and triple checked that I am using the correct clang intrinsic for the relevant opcode, and even experimented with using different intrinsics anyway in case I misread something. It also fails even if jiterpreter is disabled, so that isn't a factor.

**Comment by kg** [comment]
Disabling the interp v128 intrinsics doesn't seem to fix it either (I verified that doing this results in mostly-scalar code with wasm packedsimd opcodes scattered inside). So that seems to indicate that somehow the PackedSimd operation(s) are the problem.

**Comment by kg** [comment]
Radek pointed out that this failure could be https://github.com/dotnet/runtime/issues/84775 . It could be that there is something wrong with the way interp aligns v128 arguments or return values, or my copy-paste produced some incorrect alignment.

**Comment by kg** [comment]
The remaining issue on this PR seems to be that once we report PackedSimd support, writing XML for the testResults.xml file ends up dropping a few characters at the start or end of the stream. It's not clear to me why this would happen.

**Comment by vargaz** [comment]
Can this be turned off by default so the PR can be merged ?

**Comment by kg** [comment]
> Can this be turned off by default so the PR can be merged ?

I could probably comment out the PackedSimd support, but it makes this PR much less useful since the BCL uses it now. I'm fine with doing that assuming none of the CI tests fail and the only remaining problem is the xml, since it means we're not merging tremendously broken code.

**Comment by kg** [comment]
All the failures I saw were the test results xml size problem, so I added runtime options to govern interp v128 and packedsimd support and set them both to FALSE for browser.

**Pull request merged**
