### PR TITLE
Copy the LLVM jobs into their own pipeline

### PR DESCRIPTION
**Pull request by tannergooding**
The `llvmaot` and `llvmfullaot` jobs can take over an hour longer than any other job from the `runtime` pipeline. Due to current UX limitations, this restricts the ability to rerun jobs that fail due to networking, disk I/O, or are otherwise flaky until after these longer jobs complete.

This splits them out into their own pipeline to workaround the UX limitation. We will effectively still have a "long leg", but one that only blocks impacts itself.

Remaining steps:
1. Get this PR merged
2. Ensure AzDO is configured to read this pipeline
3. Submit a PR that removes the same job from the runtimes.yml pipeline and ensure that the new pipeline runs
4. If so, we are good to merge that PR and "be done"

### CODE REVIEW

**Comment by tannergooding** [comment]
We may want to actually move the other `llvmaot` jobs here as well, as they still represent around `25-30%` of the top 10 steps by duration (`LLVM AOT cross-compile CoreCLR tests` and `LLVM AOT compile CoreCLR tests`).

**Comment by tannergooding** [comment]
CC. @ViktorHofer. 

I'd ping Sam as well, but I'm not sure of their alias.

**Comment by ViktorHofer** [comment]
@SamMonoRT

**Review by naricc — APPROVED** [review]

**Comment by tannergooding** [comment]
@ViktorHofer, any other sign-off needed here or can we merge?

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Actually we would have been able to test the pipeline if we had an upstream branch. But anyway that's too late now. Let me check what's missing.

**Pull request merged**
