### PR TITLE
Only include Microsoft.NET.Runtime.RuntimeConfigParser.Task on mobile

### PR DESCRIPTION
**Pull request by lewing**
https://github.com/dotnet/installer/pull/10856#issuecomment-863473689

### CODE REVIEW

**Comment by lewing** [comment]
@steveisok does android need this all the time or can it be skipped in some cases?

**Comment by steveisok** [comment]
> @steveisok does android need this all the time or can it be skipped in some cases?

I believe so, but @jonathanpeppers can better answer that.

**Review by dsplaisted — APPROVED** [review]

**Comment by jonathanpeppers** [comment]
Yes, Android & Apple platforms use the `<RuntimeConfigParser/>` MSBuild task now by default.

**Comment by lewing** [comment]
The maccatalyst failure isn't relevant because the workload isn't actually used in any part of the runtime build that is being tested on that lane.

**Pull request merged**
