### PR TITLE
Add Android 32 to RID graph

### PR DESCRIPTION
**Pull request by steveisok**
Supports Android 12L, which will be stable most likely by summer or earlier.

### CODE REVIEW

**Comment by agocke** [comment]
I've been looking into deprecating our usage of RIDs for linux distributions, since it hasn't been particularly useful to have that information. Is the same true for Android? Or do these distro identifiers bring significant changes or benefits?

**Comment by agocke** [comment]
@marek-safar I would like to have a simpler distribution model based more on our dependencies than the specific distro names or publish names. So, for linux-x64, we have a minimum glibc that we support, and for linux-musl-x64, we compile in the glibc.

However, you can see in the Windows RID that sometimes changes between "releases" changes the dependencies, so we have to keep track of versions. I'm wondering if there's more than just libc/icu/openssl dependency in the Android SKU, or is it just the standard linux dependencies.

**Comment by marek-safar** [comment]
> So, for linux-x64, we have a minimum glibc that we support, and for linux-musl-x64, we compile in the libc.

I don't think that's the best way forward. We are actually in a need to introduce another RID in the graph and for Android we cannot use linux-x64 which is glibc.

My preference would be to abstract at system C level library such such (linux-glibc, linux-musl, linux-bionic, etc).

This has been discussed few times already like in #34789

**Comment by agocke** [comment]
I think we're in agreement here -- my understanding is that the thing we actually care most of the time is the OS, arch, and libc, but we constantly rev the other RIDs (like `android-` and `alpine-`), instead of refining down to the targets we care about.

Are you saying that if we had a `linux-bionic-arm` we could stop regularly rev'ing the `android-` RIDs?

**Comment by akoeplinger** [comment]
> Are you saying that if we had a linux-bionic-arm we could stop regularly rev'ing the android- RIDs?

Yes, but it would mean that users wouldn't be able to vary implementation of their native dependencies based on the platform version. As far as I know that was the original design for having these version-specific RIDs in the first place to allow you to have a separate native binary that takes advantage of APIs added in later versions.

I think those cases are pretty rare though, especially on Android/iOS since it hasn't shipped officially yet.

**Comment by am11** [comment]
> to allow you to have a separate native binary that takes advantage of APIs added in later versions.

I think APIs like NativeLibrary.Load are better suited for those scenarios. Usually they differ at the package archive (apk, tgx, deb, ipa) level, so there shouldn't be any collision per-se.

**Comment by ericstj** [comment]
> I've been looking into deprecating our usage of RIDs for linux distributions, since it hasn't been particularly useful to have that information. Is the same true for Android? Or do these distro identifiers bring significant changes or benefits?

Have a chat with @eerhardt about this.  He was looking into a similar problem a couple months ago.

I think this change is OK to take as it is so long as we still are maintaining the RID graph.

**Review by ericstj — APPROVED** [review]

**Pull request merged**
