### PR TITLE
[release/6.0] Add Fedora 37 RID

### PR DESCRIPTION
**Pull request by omajid**
Fedora 37 has now started development, and the distribution now
identifies itself as Fedora 37 instead of Fedora 36:
https://fedorapeople.org/groups/schedule/f-37/f-37-key-tasks.html

### CODE REVIEW

**Comment by ericstj** [comment]
Should we make this change in `main` first before taking in release?

**Comment by wfurt** [comment]
probably. But I think it would be OK to take it now here and do it in main tomorrow or next week. @carlossanlop noticed some differences how the RID is generated. We are probably ought to check all active branches to make sure the RIDs are the same. AFAIK that was our general goal, right?

**Review by wfurt — APPROVED** [review]
LGTMN.
But should we start with main/7.0 and roll it back to servicing?

**Comment by wfurt** [comment]
> LGTMN.
> But should we start with main/7.0 and roll it back to servicing?

missed #67021

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/issues/7467 to track support for Fedora 37

**Comment by rbhanda** [comment]
@wfurt looks like this has a merge conflict. Can we have this merge for the July servicing asap

**Pull request merged**
