### PR TITLE
allow passing jit option to superpmi.py replay

### PR DESCRIPTION
**Pull request by AndyAyersMS**

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib 

I am using this to enable extra checking with my locally collected PGO MCH files, as part of tracking down where profiles become inconsistent:
```
superpmi.py replay -mch_files d:\bugs\spmi-pgo\tiered-pgo-9.mch --jitoption JitProfileChecks=2
```

**Comment by AndyAyersMS** [comment]
@kunalspathak maybe you can take a look?

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by BruceForstall** [comment]
I guess you prefer this to setting an environment variable before invoking the python script? Seems like this feature might be more convenient in some scripting.

For consistency, though, I think the option should only have a single leading `-` : my understanding of the convention is that a single `-` switch takes an argument; a double `--` does not.

**Comment by AndyAyersMS** [comment]
Ah, did not realize that was the convention, thought maybe `--` was for more obscure options.

Do we document in superpmi.py that ambient COMPlus env vars are hoovered up and passed along as `jitoption` ? 

I wasn't sure I could/should count on this.

**Comment by BruceForstall** [comment]
> Do we document in superpmi.py that ambient COMPlus env vars are hoovered up and passed along as jitoption ?

superpmi.exe (implementing the host interface) itself reads the environment: https://github.com/dotnet/runtime/blob/a3ed2e2e9e126001f32984dcb322cb8f6ecfb3fc/src/coreclr/ToolBox/superpmi/superpmi/jithost.cpp#L140. It looks in this order:
1. -jitoption force
2. stored value in collection
3. -jitoption
4. environment

I also realized you only changed `replay`. You also want to set these for asmdiffs, in which case you need to add them to target_flags (probably): https://github.com/dotnet/runtime/blob/a3ed2e2e9e126001f32984dcb322cb8f6ecfb3fc/src/coreclr/scripts/superpmi.py#L1570. There are a set of flags that get passed to both the "determine asm diffs" command and each "generated textual asm", and you want these to be set for both. Currently, this is only the target and altjit-related commands, so the variable name is a bit specific to altjit, as complus vars are handled separately.

**Pull request merged**
