### PR TITLE
JIT: Enable EVEX embedded broadcast in more places

### PR DESCRIPTION
**Pull request by saucecontrol**
Factored out the containment checks and included an attempt to use embedded broadcast where possible.

### CODE REVIEW

**Comment by saucecontrol** [comment]
I expected there might be a couple of diffs from this one.  Wild guess is that spmi failed because the embedded encoding diffs would have something like `qword ptr [reloc @RWD00] {1to8}` in the asm, which may have fouled up the json parsing.

**Comment by MichalPetryka** [comment]
@MihuBot

**Comment by saucecontrol** [comment]
@MihuBot -intel

**Review by tannergooding — APPROVED** [review]

**Comment by JulieLeeMSFT** [comment]
@BruceForstall PTAL for code review.

**Comment by saucecontrol** [comment]
FWIW, I think this is a net negative change code quality wise since the current broadcast logic only handles constant vectors.  An aligned full-width vector load is cheaper than a broadcast, so I don't think you'd normally do it unless optimizing for code size.

This does, however, make it possible to test embedded broadcast encoding of more instructions (I added it while testing the GFNI implementation for correctness) and makes it easier to improve centrally later.  I'd like to look at containing normal data broadcasts, where containment actually saves a broadcast instruction -- unless someone else has that planned.

**Comment by tannergooding** [comment]
> FWIW, I think this is a net negative change code quality wise since the current broadcast logic only handles constant vectors. An aligned full-width vector load is cheaper than a broadcast, so I don't think you'd normally do it unless optimizing for code size.

That's not the case for embedded broadcasts. Both Intel and AMD document full-width memory loads and embedded broadcast memory loads as being the same cost, sites such as `uops.info` similarly show latencies and throughput measurements as identical (for almost all instructions).

Additionally, it also helps cache locality and other factors, so it is typically viewed as a net win and is the preferred default.

**Comment by saucecontrol** [comment]
Good to know, thanks!

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
