### PR TITLE
Remove ThreadPool event tests

### PR DESCRIPTION
**Pull request by noahfalk**
The threadpool events being verified by this test aren't
guaranteed to occur given the test code. All of them are
the results of background timers and relative execution
speed of work items. Given the relatively low event coverage
of the existing test and my historical understanding that
specific events don't often regress, trying to stabilize this test
is probably more hassle than it is worth.

This is part of resolving #48727

### CODE REVIEW

**Comment by noahfalk** [comment]
Hit unrelated outerloop issues: 
System.Cryptography - https://github.com/dotnet/runtime/issues/734
System.ServiceProcess.Tests - https://github.com/dotnet/runtime/issues/56679 
System.Runtime.Tests - https://github.com/dotnet/runtime/issues/56567

**Review by josalem — APPROVED** [review]

**Pull request merged**
