### PR TITLE
Adjust determinism tests to store away the 2 different binaries that are generated

### PR DESCRIPTION
**Pull request by davidwrighton**
- This should allow comparison without needing full rebuilds
- as well as comparison in cases where locally running the tooling doesn't result in equivalent results
- Generate map files to make comparing the binaries easier

Additionally, there is a determinism fix to the handling of instruction set fixups, where a culture sensitive compare is replaced with an ordinal based comparison

### CODE REVIEW

**Comment by davidwrighton** [comment]
Failures in runtime tests are duplicates of a known issue. The failures in the crossgen2 outerloop run are either rare (the comparison test failure, which I've never seen before, but is unrelated to the changes, or known).

**Review by trylek — APPROVED** [review]
Beautiful, thanks David for fixing this!

**Pull request merged**
