### PR TITLE
JIT: clear lvMustInit from dependent locals

### LINKED ISSUE #64808: Assertion failed 'compiler->opts.IsOSR() || ((genInitStkLclCnt > 0) == hasUntrLcl)'
### Description

The following program hits a JIT assert on x64 linux.

### Reproduction Steps

```csharp
// Generated by Fuzzlyn v1.5 on 2022-02-03 20:05:52
// Run on X64 Linux
// Seed: 17645686525285880576
// Reduced from 66.2 KiB to 1.0 KiB in 00:04:27
// Hits JIT assert in Release:
// Assertion failed 'compiler->opts.IsOSR() || ((genInitStkLclCnt > 0) == hasUntrLcl)' in 'Program:M8():S0' during 'Generate code' (IL size 110)
// 
//     File: /__w/1/s/src/coreclr/jit/codegencommon.cpp Line: 7256
// 
public class C0
{
    public int F0;
    public ulong F1;
    public sbyte F2;
}

public struct S0
{
    public int F0;
    public S0(int f0): this()
    {
    }
}

public class Program
{
    private static IRT s_rt;
    public static long[] s_16;
    public static bool s_23;
    public static void Main()
    {
        s_rt = new C();
        M8();
    }

    public static S0 M8()
    {
        try
        {
            var vr0 = new ushort[]{0};
            C0[] vr3 = default(C0[]);
            return M15(vr0, ref s_23, vr3);
        }
        finally
        {
            var vr2 = new S0[]{new S0(0), new S0(0), new S0(0), new S0(0), new S0(0), new S0(0)};
        }
    }

    public static S0 M15(ushort[] arg0, ref bool arg1, C0[] arg2)
    {
        s_16[0] = 5695124424168538056L;
        s_rt.WriteLine("L1", arg0[0]);
        s_rt.WriteLine("L2", arg1);
        s_rt.WriteLine("L3", arg2[0].F0);
        s_rt.WriteLine("L4", arg2[0].F1);
        s_rt.WriteLine("L5", arg2[0].F2);
        S0 vr5 = default(S0);
        return vr5;
    }
}

public interface IRT
{
    void WriteLine<T>(string a, T value);
}

public class C : IRT
{
    public void WriteLine<T>(string a, T value)
    {
        System.Console.WriteLine(value);
    }
}
```

### Expected behavior

No assert hit.

### Actual behavior

Assert hit.

### Regression?

Since the assertion message mentions OSR, I would assume so.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Their initialization is handled by the parent local.

Closes #64808.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

Cleared `lvMustInit` for some other early-out cases too, just to be consistent.

**Review by EgorBo — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Runtime failures look like the current set of usual suspects.

**Comment by AndyAyersMS** [comment]
Looks like we were indeed double-initializing in some cases (eg linux, x64)
```asm
; Assembly listing for method BenchmarkDotNet.Parameters.ParameterExtractor:GetParameter(System.Collections.Generic.IEnumerable`1[ValueTuple`2],int):System.ValueTuple`2[__Canon,CompareOptions]
...
       xor      eax, eax
       mov      qword ptr [rbp-38H], rax
       mov      qword ptr [rbp-30H], rax
       mov      qword ptr [rbp-38H], rax
       mov      dword ptr [rbp-30H], eax
```

**Comment by AndyAyersMS** [comment]
Spot checked and all the diffs are like this.

**Pull request merged**
