### PR TITLE
Update Alpine and Azure Linux versions

### PR DESCRIPTION
**Pull request by richlander**
Added coverage for Alpine 3.21. Removed Mariner 2.0.

Per https://github.com/dotnet/core/pull/9647, set min versions:

- Alpine 3.21
- Azure Linux 3.0

Talked to and validated dropping Mariner 2.0 support for .NET 10 with the Azure Linux team.

### CODE REVIEW

**Comment by richlander** [comment]
@carlossanlop Just need an approval. Thanks.

**Review by carlossanlop — APPROVED** [review]
LGTM assuming the CI is good.

**Comment by jkotas** [comment]
> #110636 #110637 #110638 #110639 #110640

It is not ok to intentionally introduce new blocking-clean-ci failures in a PR. The relevant tests need to be fixed or disabled against an issue, so that the CI continues to be green.

(Also, the issues are missing the failure matching patterns, so they are not suppressing the CI failures.)

**Comment by richlander** [comment]
I removed Debian 13 and Ubuntu 24.10 (which come with breaks) for now. That will allow us to lock in the other changes.

**Comment by richlander** [comment]
This PR is ready for approval @carlossanlop @jkotas.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
