### PR TITLE
Fix Alpine Linux mono build and coreclr pgo support

### PR DESCRIPTION
**Pull request by ayakael**
https://github.com/dotnet/runtime/pull/86804 renamed `CLR_CMAKE_HOST_ALPINE_LINUX` to `CLR_CMAKE_TARGET_LINUX_MUSL`. This PR applies the name change to missing files, fixing build of mono-based runtime and coreclr pgosupport on Alpine Linux.

@am11

### CODE REVIEW

**Review by am11 — APPROVED** [review]
Thanks for catching, not sure how I missed these. 🤦
Another file using the old name: `src/coreclr/pgosupport.cmake`.

**Comment by ayakael** [comment]
> Thanks for catching, not sure how I missed these. facepalm Another file using the old name: `src/coreclr/pgosupport.cmake`.

No worries! Happens to the best of us.

**Review by vargaz — APPROVED** [review]

**Comment by am11** [comment]
@vargaz, can we backport it to net8? Impact is that linux-musl-s390x doesn't get ucontext linked and gives missing reference errors.

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
LGTM, sorry I missed this somehow.

**Pull request merged**
