### PR TITLE
Revert "[wasm] browser profiler (#77449)"

### PR DESCRIPTION
**Pull request by radical**
This reverts commit 0e24ea7c2a0436a8f2bf83e8f5981ec035518b99.

It broke all the perf pipeline wasm builds. It happens with v8 `10.9.130`:

```
Error: Invalid 'startMark' argument: No numeric 'startTime' field
    at pe (/home/helixbot/work/B2E7090F/w/A520093B/e/performance/artifacts/bin/for-running/MicroBenchmarks/659adab0-5c86-4e74-8913-672bd56fd58e/bin/net7.0/browser-wasm/AppBundle/dotnet.js:3:12994)
    at /home/helixbot/work/B2E7090F/w/A520093B/e/performance/artifacts/bin/for-running/MicroBenchmarks/659adab0-5c86-4e74-8913-672bd56fd58e/bin/net7.0/browser-wasm/AppBundle/dotnet.js:5:95874
exiting due to exception: Error: Invalid 'startMark' argument: No numeric 'startTime' field
```

- It works fine with older versions like `10.7.193` (current stable).
- It wasn't caught in the CI checks because those are using an older version of v8.

### CODE REVIEW

**Comment by radical** [comment]
I'll open a separate PR to use the same version of V8 for all our testing on CI - https://github.com/dotnet/runtime/issues/66164 .

**Review by lambdageek — APPROVED** [review]

**Comment by radical** [comment]
All the wasm jobs are passing. Merging this now to unblock CI.

**Comment by pavelsavara** [comment]
thanks for this

**Comment by pavelsavara** [comment]
It's interesting. They added the `performance.measure` API in minor update, it's not in the 10.7.193
It's also interesting they use NodeJS shape of the API.

Here is another attempt https://github.com/dotnet/runtime/pull/77779

**Pull request merged**
