### PR TITLE
Tweak code gen for Guid parsing

### PR DESCRIPTION
**Pull request by stephentoub**
Following-up on @GrabYourPitchforks' suggestion in https://github.com/dotnet/runtime/pull/55792#discussion_r675008631

|   Method |         Toolchain |      Mean | Ratio | Code Size |
|--------- |------------------ |----------:|------:|----------:|
|        D | \main\CoreRun.exe |  38.43 ns |  1.00 |   2,951 B |
|        D |   \pr\CoreRun.exe |  37.52 ns |  0.98 |   2,900 B |
|          |                   |           |       |           |
|        N | \main\CoreRun.exe |  37.52 ns |  1.00 |   2,302 B |
|        N |   \pr\CoreRun.exe |  37.08 ns |  0.99 |   2,249 B |
|          |                   |           |       |           |
|        B | \main\CoreRun.exe |  39.30 ns |  1.00 |   3,050 B |
|        B |   \pr\CoreRun.exe |  38.07 ns |  0.97 |   2,999 B |
|          |                   |           |       |           |
|        P | \main\CoreRun.exe |  39.41 ns |  1.00 |   3,055 B |
|        P |   \pr\CoreRun.exe |  38.85 ns |  0.99 |   3,004 B |
|          |                   |           |       |           |
| InvalidD | \main\CoreRun.exe |  42.55 ns |  1.00 |   3,139 B |
| InvalidD |   \pr\CoreRun.exe |  41.01 ns |  0.96 |   3,088 B |
|          |                   |           |       |           |
|   WeirdD | \main\CoreRun.exe | 102.16 ns |  1.00 |   3,418 B |
|   WeirdD |   \pr\CoreRun.exe | 100.44 ns |  0.98 |   3,367 B |

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
Was hoping for a slightly better clock time measurement. But hey, I'll take the 50-byte codegen win. :)

**Review by GrabYourPitchforks — APPROVED** [review]
Here's another experiment which may be worth running. Changing the definition of `DecodeByte` to use _nuint_ instead of _char_ results in a 93-byte savings in the _TryParse_ method (per sharplab). I'm not currently set up to measure how it might affect clock time.

```cs
private static byte DecodeByte(nuint ch1, nuint ch2, ref int invalidIfNegative)
{
    // TODO https://github.com/dotnet/runtime/issues/13464:
    // Replace the Unsafe.Add with HexConverter.FromChar once the bounds checks are eliminated.

    ReadOnlySpan<byte> lookup = CharToHexLookup;

    int h1 = -1;
    if (ch1 < (nuint)lookup.Length)
    {
        h1 = (sbyte)Unsafe.Add(ref MemoryMarshal.GetReference(lookup), (nint)ch1);
    }
    h1 <<= 4;

    int h2 = -1;
    if (ch2 < (nuint)lookup.Length)
    {
        h2 = (sbyte)Unsafe.Add(ref MemoryMarshal.GetReference(lookup), (nint)ch2);
    }

    int result = h1 | h2;
    invalidIfNegative |= result;
    return (byte)result;
}
```

**Comment by jeffhandley** [comment]
@GrabYourPitchforks This PR is assigned to you for follow-up/decision before the RC1 snap.

**Comment by stephentoub** [comment]
> Here's another experiment

Thanks. Gives a small bump in throughput.

**Pull request merged**
