### PR TITLE
[release/9.0][browser] Enable the log profiler

### PR DESCRIPTION
**Pull request by pavelsavara**
Backport of https://github.com/dotnet/runtime/pull/107434 to release/9.0

## Customer Impact

- [x] Customer reported, customer contribution
- [ ] Found internally

Enables [Uno](https://platform.uno/) to use legacy memory profiler, which they already use with custom build of the runtime in Net8. 
We don't have EventPipe solution for browser yet.

## Regression

- [ ] Yes
- [x] No

## Testing

Automated test on main branch

## Risk

Low. This is only used when 
- customer installed wasm workload
- customer enabled `<WasmProfilers>log;</WasmProfilers><WasmBuildNative>true</WasmBuildNative>`

### CODE REVIEW

**Comment by pavelsavara** [comment]
servicing approved here https://github.com/dotnet/runtime/pull/107626#issuecomment-2346748146

cc @jeffschwMSFT

**Review by lewing — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
approved. we can merge when ready

**Comment by jeffschwMSFT** [comment]
@pavelsavara please take a look at the failing PR legs.

**Comment by maraf** [comment]
The failure in WasmBuildTests is https://github.com/dotnet/runtime/issues/106160

**Comment by pavelsavara** [comment]
> @pavelsavara please take a look at the failing PR legs.

It's unrelated known issue https://github.com/dotnet/runtime/issues/106160

**Pull request merged**
