### PR TITLE
[NativeAOT] Use ld_classic in ILC build and in build integration

### PR DESCRIPTION
**Pull request by jkotas**
Forward port of #97856

Workaround for #97745

### CODE REVIEW

**Comment by jkotas** [comment]
The actual fix for the xcode 15+ linker issue is likely going to require xcode update, so we should forward port the servicing fix in the meantime.

**Comment by VSadov** [comment]
The change is also a part of https://github.com/dotnet/runtime/pull/98117 .

I assume we just want to go ahead with a standalone fix (not a part of that change)?

**Comment by jkotas** [comment]
Yes, I do not think we want to wait for that change to stabilize.

**Review by VSadov — APPROVED** [review]
LGTM. Thanks!

**Comment by VSadov** [comment]
I've run checked tests with this (as in `./build.sh clr+libs+libs.tests -rc checked -lc release /p:TestNativeAot=true -test`) locally with xcode 15.2.

Everything passed.

**Pull request merged**
