### PR TITLE
Re-enable Windows arm32 testing of JIT stress modes

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
I manually triggered the jitstress/jitstress2-jitstressregs/jitstressregs pipelines on this change.

**Review by trylek — APPROVED** [review]
LGTM but please work with Jarret on assessing the impact on the available ARM pool as I believe he expressed concerns about its current capacity.

**Comment by BruceForstall** [comment]
jistressregs and jitstress2-jitstressregs only run once Saturday and once Sunday. jitstress runs once per day.

**Comment by jashook** [comment]
My concern is that there is no ABI difference for arm windows and arm linux. It seems this is a question of we can run the tests but should we.

There seem to me to be many reasons not to run these tests on windows arm.

**Comment by trylek** [comment]
@AndyAyersMS, would you mind sharing your thoughts?

**Comment by BruceForstall** [comment]
> There seem to me to be many reasons not to run these tests on windows arm.

Can you give some of these reasons? Is it just the load, or machine resource constraints, or flakiness?

Given that it is a supported platform, I'd like to say we have fully tested on it.

**Comment by BruceForstall** [comment]
The Windows arm stress jobs are showing a number of test failures: crashes and JIT asserts. The corresponding Linux arm jobs succeeded. That indicates to me that these jobs have value. Either the platform is different in some noticeable ways, or the set of tests run is different. Or, my frequent biggest fear: we're not testing what we think we're testing in some cases (like not setting the correct COMPlus variables, or incorrectly casing them on Linux).

I'm going to open issues for the Windows arm failures.

**Comment by jashook** [comment]
Didn't linux arm fail to build?

**Comment by BruceForstall** [comment]
Check, e.g., the manually-triggered jitstress job:

https://dev.azure.com/dnceng/public/_build/results?buildId=574937&view=results

**Comment by BruceForstall** [comment]
Worse than the tests failing, the machines appear to be misconfigured in some way, such that failure reporting itself fails. Lots of script errors. Looks like perhaps it boils down to python not being available.

**Comment by jashook** [comment]
I see, @MattGal  for the xunit reporting issues.

**Review by jashook — APPROVED** [review]

**Comment by MattGal** [comment]
> I see, @MattGal for the xunit reporting issues.

Dealt with that earlier this week, should eventually flow to you via Arcade updates.  See https://github.com/dotnet/core-eng/issues/9434 for details.  Basically after creating the venv Windows holds onto the file handle for several seconds.  I just added retries.

**Comment by BruceForstall** [comment]
> Dealt with that earlier this week, should eventually flow to you

@MattGal Do you know when we might see this fix in the runtime repo runs?

**Comment by MattGal** [comment]
> > Dealt with that earlier this week, should eventually flow to you
> 
> @MattGal Do you know when we might see this fix in the runtime repo runs?

Whenever your Helix assets get to `20175.3` or greater you should be good to go, or if other users of the same queue get there (if anyone running on it has the change and gets venv set up right, your existing scripts will start working)

**Comment by BruceForstall** [comment]
There are some JIT stress regressions that will need to be investigated.

**Pull request merged**
