### PR TITLE
V3 publishing 

### PR DESCRIPTION
**Pull request by epananth**
Use V3 publishing for runtime 

Test with default channel => https://dev.azure.com/dnceng/internal/_build/results?buildId=802296&view=results
Test without default channel => https://dev.azure.com/dnceng/internal/_build/results?buildId=802367&view=results

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@epananth @mmitche can/should the post build checks also be moved into the outer ring validation? 

image

**Comment by epananth** [comment]
@ViktorHofer  yes that is correct.

**Comment by epananth** [comment]
For stable build test ->https://dnceng.visualstudio.com/internal/_build/results?buildId=803153&view=results

@mmitche please merge this PR for me, I do not have access to merge this one.

**Comment by ViktorHofer** [comment]
@epananth my question was if we can/should move the whole "Validate Build Assets" stage out of the build.

**Comment by mmitche** [comment]
> @epananth my question was if we can/should move the whole "Validate Build Assets" stage out of the build.

@epananth I think we can for v3 publishing. If none of the SDL, etc. validations are enabled and v3 is enabled, then I don't think this stage doesn't have any real purpose. It used to verify that the default channel was available, but in v3 this is not a relevant concern.

Does that sound right to you?

**Comment by epananth** [comment]
Thanks @mmitche! I created a issue to safely remove this stage for V3.

**Comment by jkoritzinsky** [comment]
@epananth is there a plan to move master to publishing v3 as well?

**Comment by epananth** [comment]
@jkoritzinsky you can just merge release/5.0-rc2 to master then it should pick up the V3 changes.

**Comment by jkoritzinsky** [comment]
We don't merge release branches back to master in dotnet/runtime. We exclusively use the dual-checkin model.

If this change should work as written against master, we can use the backport GitHub action to port it to master.

**Comment by epananth** [comment]
oh okay, good to know. 

The changes should work in master. Like discussed, I will run my changes against master and back port it to master.

**Pull request merged**
