### PR TITLE
Download Mono AOT workload .nupkg in prepare-artifacts.proj

### PR DESCRIPTION
**Pull request by akoeplinger**
Fixes the official build failure after https://github.com/dotnet/runtime/pull/51327 since the pattern we were using didn't include it.

Note: it sounds wrong to have these in `RuntimeNupkgFile` but I'm sending the PR to unblock the official build, we'll refactor it in a follow-up PR.

Test official build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1120630&view=results

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Are the `Microsoft.NET.Sdk.Mono.Toolchain.Manifest.*.nupkg` packages rid agnostic or specific?

**Comment by akoeplinger** [comment]
They're rid-agnostic, it's basically `Microsoft.NET.Sdk.Mono.Toolchain.Manifest.6.0.0-preview.5.21253.8.nupkg`

**Comment by ViktorHofer** [comment]
Cool. Can you please add to this item instead then? https://github.com/dotnet/runtime/blob/bde0bab4cad0cc1cfc72acfe971545b2b5c70a08/src/installer/prepare-artifacts.proj#L219

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Should we queue an official build to make sure this mitigates the build break?

**Comment by akoeplinger** [comment]
@ViktorHofer I queued one here (before your feedback): https://dev.azure.com/dnceng/internal/_build/results?buildId=1120630&view=results

Do you think we need another one after your feedback? Seems unlikely to break :)

**Comment by ViktorHofer** [comment]
Don't think we need another build. I believe the whole logic in this file is outdated and the separation of items actually doesn't do much.

**Comment by akoeplinger** [comment]
Official build passed, merging.

**Pull request merged**
