### PR TITLE
JIT: allow suppressing some dumps or parts of dumps

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Another bit of code that I've had lying around that might be generally useful.
* Optionally suppress Tier0 compilation dumps
* Optionally suppress dumps from inline compiler phases

Setting JitDumpNoTier0 prevents you from getting two dumps when you specify
dumping a method by name or hash, when TC is enabled.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
PTAL @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
We currently have `JitDumpFgPhase` and `JitDumpFgPrePhase` for specifying a set of phases before/after which to dump the flow graph. Maybe we should add `JitDumpPhase` for allowing JitDump output for a set of particular named phases? `JitDump` and friends would still control which function(s) this applies to. Thus, we wouldn't need to create a new variable for every phase.

**Review by BruceForstall — APPROVED** [review]
I'm ok with this, but I'd prefer to remove the "No" from the names, and set the default to 1/true to avoid "double negative" confusion:
```
CONFIG_INTEGER(JitDumpTier0, W("JitDumpTier0"), 1)       // Allow dumping for tier0 requests
CONFIG_INTEGER(JitDumpInlinePhases, W("JitDumpInlinePhases"), 1) // Allow dumping of inline compiler phases
```

**Comment by AndyAyersMS** [comment]
> I'd prefer to remove the "No" from the names, and set the default to 1/true to avoid "double negative" confusion

Good suggestion.

> Displaying details of individual phases should be opt-in

@kunalspathak how does Bruce's suggestion sound to you? I think not dumping phases by default will make things more confusing (unless there is some per-phase placeholder output reminding you that those phases exist and ran).... It also makes selective IR dumping only before/after phases that make change a bit tricky).

**Comment by BruceForstall** [comment]
btw, I think Kunal's suggestion and my proposal are orthogonal to this PR, as Tier-0 affects many phases, and disabling output for all phases induced by inlining overlaps with sets of phases you want to normally see dumped, even if you don't want to see the inlinee dumping.

**Comment by kunalspathak** [comment]
My suggestion was not for this PR, but in general. Today, because of the volume of contents we log in JitDump is huge and is very hard to find relevant things so I wanted something related to one and only phase's output. Now one could argue that even if they are interested in a particular phase's output, they might want to know how the IR reached that point and so prior verbose logs are useful.

**Comment by EgorBo** [comment]
> My suggestion was not for this PR, but in general. Today, because of the volume of contents we log in JitDump is huge and is very hard to find relevant things so I wanted something related to one and only phase's output. Now one could argue that even if they are interested in a particular phase's output, they might want to know how the IR reached that point and so prior verbose logs are useful.

I agree, I really enjoy the way it's done in LLVM: 
```
-print-before= //Print IR before specified passes
-print-after= //Print IR after specified passes
-print-before-all //Print IR before each pass
-print-after-all //Print IR after each pass
```
e.g. we can ask LLVM to print whole IR before and after all phases

**Review by EgorBo — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
I'm happy to consider the before/after and possibly "phase range" options, but still find the short phase name syntax to be a clunky way to express this.

I wonder if we should rename all phases so they're just short descriptive non-whitespace strings and we can match on those, rather than having a second set of names to keep in mind, and get rid of the concept of short names.

Maybe I'll investigate as a follow up as I find just the changes here to be pretty useful.

**Comment by AndyAyersMS** [comment]
Failures are unrelated (regex timeouts).

**Pull request merged**
