### PR TITLE
Remove unnecessary Sun license

### LINKED ISSUE #56394: Non Open Source license notice in THIRD-PARTY-NOTICES.TXT
https://github.com/dotnet/runtime/pull/42476 introduced a bunch of code and an additional license with this note:

```
You acknowledge that this software is not designed, licensed or
intended  for  use  in  the  design, construction, operation or
maintenance of any nuclear facility.
```

That's a field-of-use restriction, which is not compatible with the [Open Source Definition](https://opensource.org/osd-annotated):
 
> 6. No Discrimination Against Fields of Endeavor
> 
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

Or with the [Debian Free Software Guidelines](https://www.debian.org/social_contract):

> No Discrimination Against Fields of Endeavor
>
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

[This license was also rejected by Fedora](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/3EPXMPK3PADRZ5PPWG53SKP3RZ6QAXQW/), as well as Red Hat (though I don't have a public reference for the last one).

cc @dleeapho @leecow @dseefeld @crummel @MichaelSimons

### PR DESCRIPTION
**Pull request by danmoseley**
Fixes https://github.com/dotnet/runtime/issues/56394 per discussion there.

### CODE REVIEW

**Comment by danmoseley** [comment]
Do you want to throw up PR's?

**Comment by am11** [comment]
Sure, I will prepare it in a few hours. :)

**Review by krwq — APPROVED** [review]
LGTM considering @richlander's sign-off on the issue

**Review by stephentoub — APPROVED** [review]

**Comment by omajid** [comment]
Thanks!

**Pull request merged**
