### PR TITLE
[arm64] JIT: Drop redundant dmb from Interlocked.*

### PR DESCRIPTION
**Pull request by EgorBo**
```csharp
static int Test1(ref int a, int b, int c) => Interlocked.Add(ref a, b);
static int Test2(ref int a, int b, int c) => Interlocked.CompareExchange(ref a, b, c);
```
Codegen on arm64 v8.0 (no atomics):
```diff
; Method Prog:Test1(byref,int,int):int
G_M10511_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
G_M10511_IG02:
            ldaxr   w4, [x0]
            add     w3, w4, w1
            stlxr   w2, w3, [x0]
            cbnz    w2, G_M10511_IG02
-           dmb     ish
            add     w0, w4, w1
G_M10511_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
-; Total bytes of code: 40
+; Total bytes of code: 36


; Method Prog:Test2(byref,int,int):int
G_M5868_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
G_M5868_IG02:
            ldaxr   w4, [x0]
            cmp     w4, w2
            bne     G_M5868_IG03
            stlxr   w3, w1, [x0]
            cbnz    w3, G_M5868_IG02
G_M5868_IG03:
-           dmb     ish
            mov     w0, w4
G_M5868_IG04:
            ldp     fp, lr, [sp],#16
            ret     lr
-; Total bytes of code: 44
+; Total bytes of code: 40
```
I am not sure I understand the purpose of these `dmb` here, native compilers don't emit it for the exactly the same functions: https://godbolt.org/z/1fdTE46h3 ldaxr/stlxr should be enough?

### References:
- https://developer.arm.com/documentation/den0024/a/Memory-Ordering/Barriers/One-way-barriers
- https://developer.arm.com/documentation/dui0802/h/A64-Data-Transfer-Instructions/STLXR
- https://developer.arm.com/documentation/dui0802/b/A64-Data-Transfer-Instructions/LDAXR

PS: As far as I know, our PerfLab arm hardware (TE benchamarks, etc) doesn't support Atomics (8.1).

cc @kunalspathak @echesakovMSFT @dotnet/jit-contrib

### CODE REVIEW

**Comment by EgorBo** [comment]
NOTE: clang emits `clrex` to clear the local record of the executing processor that an address has had a request for an exclusive access. 🤔

**Comment by EgorBo** [comment]
## benchmarks.run.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 14933416 (overridden on cmd)
Total bytes of diff: 14931788 (overridden on cmd)
Total bytes of delta: -1628 (-0.01 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -36 : 17280.dasm (-1.80% of base)
         -24 : 16941.dasm (-1.86% of base)
         -24 : 3703.dasm (-4.17% of base)
         -16 : 17268.dasm (-1.39% of base)
         -16 : 10340.dasm (-2.00% of base)
         -16 : 5873.dasm (-2.12% of base)
         -16 : 17541.dasm (-1.70% of base)
         -16 : 13251.dasm (-1.17% of base)
         -12 : 13237.dasm (-1.14% of base)
         -12 : 20214.dasm (-0.94% of base)
         -12 : 4188.dasm (-0.69% of base)
         -12 : 5815.dasm (-3.95% of base)
         -12 : 14894.dasm (-1.87% of base)
         -12 : 3689.dasm (-3.66% of base)
         -12 : 4199.dasm (-3.85% of base)
         -12 : 4212.dasm (-1.18% of base)
         -12 : 6428.dasm (-2.29% of base)
         -12 : 9215.dasm (-3.95% of base)
         -12 : 10343.dasm (-3.95% of base)
         -12 : 4461.dasm (-2.21% of base)

260 total files with Code Size differences (260 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -36 (-1.80% of base) : 17280.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol:ForceComplete(Microsoft.CodeAnalysis.SourceLocation,System.Threading.CancellationToken):this
         -24 (-1.86% of base) : 16941.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol:ForceComplete(Microsoft.CodeAnalysis.SourceLocation,System.Threading.CancellationToken):this
         -24 (-4.17% of base) : 3703.dasm - System.IO.UnmanagedMemoryStream:Seek(long,int):long:this
         -16 (-1.70% of base) : 17541.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberMethodSymbol:ForceComplete(Microsoft.CodeAnalysis.SourceLocation,System.Threading.CancellationToken):this
         -16 (-1.39% of base) : 17268.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceModuleSymbol:ForceComplete(Microsoft.CodeAnalysis.SourceLocation,System.Threading.CancellationToken):this
         -16 (-2.00% of base) : 10340.dasm - System.IO.RandomAccess:QueueAsyncReadFile(Microsoft.Win32.SafeHandles.SafeFileHandle,System.Memory`1[Byte],long,System.Threading.CancellationToken,System.IO.Strategies.OSFileStreamStrategy):System.ValueTuple`2[[Microsoft.Win32.SafeHandles.SafeFileHandle+OverlappedValueTaskSource, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
         -16 (-2.12% of base) : 5873.dasm - System.IO.RandomAccess:QueueAsyncWriteFile(Microsoft.Win32.SafeHandles.SafeFileHandle,System.ReadOnlyMemory`1[Byte],long,System.Threading.CancellationToken,System.IO.Strategies.OSFileStreamStrategy):System.ValueTuple`2[[Microsoft.Win32.SafeHandles.SafeFileHandle+OverlappedValueTaskSource, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
         -16 (-1.17% of base) : 13251.dasm - System.Threading.CancellationTokenSource:ExecuteCallbackHandlers(bool):this
         -12 (-0.94% of base) : 20214.dasm - <AsyncModeCopyToAsync>d__5:MoveNext():this
         -12 (-0.89% of base) : 19120.dasm - <WriteGatherAtOffsetSingleSyscallAsync>d__35:MoveNext():this
         -12 (-1.87% of base) : 14894.dasm - CompleteOnCountdownPromise`1[__Canon][System.__Canon]:Invoke(System.Threading.Tasks.Task):this
         -12 (-0.74% of base) : 4145.dasm - GateThread:GateThreadStart()
         -12 (-2.27% of base) : 16939.dasm - Microsoft.CodeAnalysis.CSharp.Imports:Complete(System.Threading.CancellationToken):this
         -12 (-1.89% of base) : 5895.dasm - OverlappedValueTaskSource:Complete(int,int):this
         -12 (-1.14% of base) : 13237.dasm - System.Collections.Concurrent.BlockingCollection`1[__Canon][System.__Canon]:TryAddWithNoTimeValidation(System.__Canon,int,System.Threading.CancellationToken):bool:this
         -12 (-3.66% of base) : 3689.dasm - System.IO.UnmanagedMemoryStream:ReadByte():int:this
         -12 (-2.29% of base) : 3685.dasm - System.IO.UnmanagedMemoryStream:ReadCore(System.Span`1[Byte]):int:this
         -12 (-2.21% of base) : 4461.dasm - System.Runtime.CompilerServices.AsyncTaskMethodBuilder:SetResult():this
         -12 (-2.29% of base) : 6428.dasm - System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder:SetResult():this
         -12 (-0.87% of base) : 5011.dasm - System.Threading.Barrier:SignalAndWait(int,System.Threading.CancellationToken):bool:this

Top method improvements (percentages):
          -4 (-8.33% of base) : 24529.dasm - System.Threading.Tests.Perf_Interlocked:Add_long():long:this
          -4 (-8.33% of base) : 23612.dasm - System.Threading.Tests.Perf_Interlocked:Decrement_int():int:this
          -4 (-8.33% of base) : 24245.dasm - System.Threading.Tests.Perf_Interlocked:Decrement_long():long:this
          -4 (-8.33% of base) : 10017.dasm - System.Threading.Tests.Perf_Interlocked:Exchange_int():int:this
          -4 (-8.33% of base) : 11561.dasm - System.Threading.Tests.Perf_Interlocked:Exchange_long():long:this
          -4 (-8.33% of base) : 23341.dasm - System.Threading.Tests.Perf_Interlocked:Increment_int():int:this
          -4 (-8.33% of base) : 23957.dasm - System.Threading.Tests.Perf_Interlocked:Increment_long():long:this
          -4 (-7.69% of base) : 12105.dasm - System.Threading.Tests.Perf_Interlocked:CompareExchange_int():int:this
          -4 (-7.69% of base) : 12542.dasm - System.Threading.Tests.Perf_Interlocked:CompareExchange_long():long:this
          -4 (-7.14% of base) : 5386.dasm - System.Drawing.DrawingCom:.ctor():this
          -4 (-7.14% of base) : 20535.dasm - System.IO.Enumeration.FileSystemEnumerator`1[__Canon][System.__Canon]:CloseDirectoryHandle():this
          -4 (-7.14% of base) : 4194.dasm - System.Runtime.InteropServices.GCHandle:Free():this
          -4 (-6.67% of base) : 5207.dasm - System.Collections.Immutable.SecureObjectPool:NewId():int
          -4 (-6.25% of base) : 9838.dasm - System.Threading.AsyncMutex:Exit():this
          -8 (-6.06% of base) : 4895.dasm - System.Threading.Tasks.TaskScheduler:get_Id():int:this
          -4 (-5.88% of base) : 5881.dasm - OverlappedValueTaskSource:FinishedScheduling():this
          -4 (-5.88% of base) : 14707.dasm - System.Collections.Concurrent.ConcurrentQueueSegment`1[__Canon][System.__Canon]:EnsureFrozenForEnqueues():this
          -4 (-5.88% of base) : 20168.dasm - System.Collections.Concurrent.ConcurrentQueueSegment`1[Int32][System.Int32]:EnsureFrozenForEnqueues():this
          -4 (-5.88% of base) : 3679.dasm - System.IO.UnmanagedMemoryStream:get_Length():long:this
          -4 (-5.56% of base) : 9406.dasm - System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo:GetObjectInfo(System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit):System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo

260 total methods with Code Size differences (260 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## coreclr_tests.pmi.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 168115576 (overridden on cmd)
Total bytes of diff: 168114292 (overridden on cmd)
Total bytes of delta: -1284 (-0.00 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -56 : 233356.dasm (-2.87% of base)
         -24 : 209546.dasm (-3.92% of base)
         -20 : 163890.dasm (-0.53% of base)
         -20 : 209108.dasm (-2.53% of base)
         -16 : 209547.dasm (-2.47% of base)
         -16 : 209548.dasm (-3.92% of base)
         -16 : 235153.dasm (-0.69% of base)
         -12 : 223720.dasm (-0.77% of base)
         -12 : 259501.dasm (-8.33% of base)
         -12 : 246226.dasm (-2.70% of base)
         -12 : 164059.dasm (-1.30% of base)
         -12 : 254261.dasm (-0.89% of base)
         -12 : 163889.dasm (-1.52% of base)
         -12 : 246407.dasm (-0.43% of base)
         -12 : 246410.dasm (-1.47% of base)
          -8 : 209649.dasm (-0.49% of base)
          -8 : 223727.dasm (-0.87% of base)
          -8 : 82174.dasm (-9.09% of base)
          -8 : 82551.dasm (-3.57% of base)
          -8 : 209543.dasm (-4.55% of base)

235 total files with Code Size differences (235 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -56 (-2.87% of base) : 233356.dasm - GCHandleTest:FreeTest():this
         -24 (-3.92% of base) : 209546.dasm - Internal.TypeSystem.DefType:ComputeInstanceLayout(int):this
         -20 (-2.53% of base) : 209108.dasm - Internal.TypeSystem.LockFreeReaderHashtable`2[__Canon,__Canon][System.__Canon,System.__Canon]:TryAddOrGetExisting(System.__Canon,byref):System.__Canon:this
         -20 (-0.53% of base) : 163890.dasm - ReliabilityFramework:StartTestWorker(System.Object):this
         -16 (-2.47% of base) : 209547.dasm - Internal.TypeSystem.DefType:ComputeStaticFieldLayout(int):this
         -16 (-3.92% of base) : 209548.dasm - Internal.TypeSystem.DefType:ComputeTypeContainsGCPointers():this
         -16 (-0.69% of base) : 235153.dasm - IntrinsicTest:MainTest():bool
         -12 (-1.30% of base) : 164059.dasm - <>c__DisplayClass40_0:<StartTestWorker>b__0():this
         -12 (-0.77% of base) : 223720.dasm - ComWrappersTests.Program:ValidateWrappersInstanceIsolation()
         -12 (-0.43% of base) : 246407.dasm - LOHPin.LOHPin:Main(System.String[]):int
         -12 (-8.33% of base) : 259501.dasm - NCS:Main():int
         -12 (-1.52% of base) : 163889.dasm - ReliabilityFramework:StartTest(ReliabilityTest):this
         -12 (-1.47% of base) : 246410.dasm - request:Main(System.String[]):int
         -12 (-2.70% of base) : 246226.dasm - Tracing.Tests.RuntimeEventListener:OnEventWritten(System.Diagnostics.Tracing.EventWrittenEventArgs):this
         -12 (-0.89% of base) : 254261.dasm - WhenAllPromise`1[Byte][System.Byte]:Invoke(System.Threading.Tasks.Task):this
          -8 (-0.62% of base) : 239595.dasm - BenchmarksGame.FannkuchRedux_9:Run(int,int)
          -8 (-1.32% of base) : 254413.dasm - CompleteOnCountdownPromise`1[Byte][System.Byte]:Invoke(System.Threading.Tasks.Task):this
          -8 (-1.18% of base) : 223725.dasm - ComWrappersTests.Program:ValidateBadComWrapperImpl()
          -8 (-0.95% of base) : 223716.dasm - ComWrappersTests.Program:ValidateComInterfaceCreation()
          -8 (-1.40% of base) : 223717.dasm - ComWrappersTests.Program:ValidateComInterfaceCreationRoundTrip()

Top method improvements (percentages):
          -8 (-11.76% of base) : 163952.dasm - ReliabilityTest:TestStarted():this
          -4 (-10.00% of base) : 259499.dasm - NCS:Add(byref,int):int
          -4 (-10.00% of base) : 259498.dasm - NCS:Decrement(byref):int
          -4 (-10.00% of base) : 259497.dasm - NCS:Increment(byref):int
          -4 (-9.09% of base) : 228613.dasm - <>c__DisplayClass6_0:<RenderParallelShowingThreads>b__2(float):this
          -8 (-9.09% of base) : 82174.dasm - Foo:Function():int:this
          -4 (-9.09% of base) : 259500.dasm - NCS:CompareExchange(byref,int,int):int
          -8 (-9.09% of base) : 261206.dasm - Program:DoWork()
          -4 (-9.09% of base) : 163953.dasm - ReliabilityTest:TestStopped():this
          -8 (-8.33% of base) : 209346.dasm - Internal.TypeSystem.ThreadSafeFlags:AddFlags(int):this
         -12 (-8.33% of base) : 259501.dasm - NCS:Main():int
          -8 (-8.33% of base) : 163892.dasm - ReliabilityFramework:SignalTestFinished(ReliabilityTest):this
          -4 (-7.69% of base) : 260559.dasm - GitHub_12398:TestBinary():long
          -4 (-7.69% of base) : 260561.dasm - GitHub_12398:TestMul():long
          -4 (-7.14% of base) : 228611.dasm - <>c__DisplayClass6_0:<RenderParallelShowingThreads>b__0():float:this
          -4 (-7.14% of base) : 212230.dasm - ComWrappersTests.Common.Test:Finalize():this
          -4 (-7.14% of base) : 223733.dasm - ComWrappersTests.Common.Test:Finalize():this
          -4 (-7.14% of base) : 260560.dasm - GitHub_12398:TestCompare():bool
          -4 (-7.14% of base) : 212288.dasm - GlobalComWrappers:.ctor():this
          -4 (-7.14% of base) : 257921.dasm - System.IO.Enumeration.FileSystemEnumerator`1[Byte][System.Byte]:CloseDirectoryHandle():this

235 total methods with Code Size differences (235 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.crossgen2.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 50733148 (overridden on cmd)
Total bytes of diff: 50731068 (overridden on cmd)
Total bytes of delta: -2080 (-0.00 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -24 : 214151.dasm (-3.64% of base)
         -24 : 76679.dasm (-3.35% of base)
         -16 : 214149.dasm (-3.39% of base)
         -16 : 214150.dasm (-2.31% of base)
         -16 : 163605.dasm (-1.94% of base)
         -16 : 76675.dasm (-1.75% of base)
         -16 : 76678.dasm (-2.50% of base)
         -16 : 192641.dasm (-2.11% of base)
         -16 : 29708.dasm (-3.28% of base)
         -16 : 192642.dasm (-2.16% of base)
         -16 : 192644.dasm (-0.77% of base)
         -16 : 76672.dasm (-2.20% of base)
         -16 : 84328.dasm (-0.99% of base)
         -12 : 170063.dasm (-0.37% of base)
         -12 : 84221.dasm (-2.94% of base)
         -12 : 182144.dasm (-1.35% of base)
         -12 : 35922.dasm (-0.28% of base)
         -12 : 76680.dasm (-3.09% of base)
         -12 : 76683.dasm (-1.94% of base)
         -12 : 203628.dasm (-0.91% of base)

391 total files with Code Size differences (391 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -24 (-3.64% of base) : 214151.dasm - Internal.TypeSystem.DefType:ComputeInstanceLayout(int):this
         -24 (-3.35% of base) : 76679.dasm - System.IO.UnmanagedMemoryStream:Seek(long,int):long:this
         -16 (-2.31% of base) : 214150.dasm - Internal.TypeSystem.DefType:ComputeStaticFieldLayout(int):this
         -16 (-3.39% of base) : 214149.dasm - Internal.TypeSystem.DefType:ComputeTypeContainsGCPointers():this
         -16 (-3.28% of base) : 29708.dasm - Microsoft.CodeAnalysis.Collections.SmallConcurrentSetOfInts:Add(Microsoft.CodeAnalysis.Collections.SmallConcurrentSetOfInts,int):bool
         -16 (-0.77% of base) : 192644.dasm - System.ComponentModel.Composition.Registration.RegistrationBuilder:GetCustomAttributes(System.Reflection.MemberInfo,System.Collections.Generic.IEnumerable`1[System.Object]):System.Collections.Generic.IEnumerable`1[System.Object]:this
         -16 (-2.16% of base) : 192642.dasm - System.ComponentModel.Composition.Registration.RegistrationBuilder:ReadMemberCustomAttributes(System.Reflection.MemberInfo):System.Collections.Generic.List`1[System.Attribute]:this
         -16 (-2.11% of base) : 192641.dasm - System.ComponentModel.Composition.Registration.RegistrationBuilder:ReadParameterCustomAttributes(System.Reflection.ParameterInfo):System.Collections.Generic.List`1[System.Attribute]:this
         -16 (-2.50% of base) : 76678.dasm - System.IO.UnmanagedMemoryStream:SetLength(long):this
         -16 (-2.20% of base) : 76672.dasm - System.IO.UnmanagedMemoryStream:WriteByte(ubyte):this
         -16 (-1.75% of base) : 76675.dasm - System.IO.UnmanagedMemoryStream:WriteCore(System.ReadOnlySpan`1[System.Byte]):this
         -16 (-1.94% of base) : 163605.dasm - System.Runtime.Caching.MemoryCacheStatistics:UpdateConfig(System.Collections.Specialized.NameValueCollection):this
         -16 (-0.99% of base) : 84328.dasm - System.Threading.CancellationTokenSource:ExecuteCallbackHandlers(bool):this
         -12 (-0.28% of base) : 35922.dasm - <ProcessServerStreamAsync>d__41:MoveNext():this
         -12 (-0.37% of base) : 170063.dasm - <RenegotiateAsync>d__172`1:MoveNext():this
         -12 (-0.35% of base) : 170714.dasm - <RenegotiateAsync>d__172`1:MoveNext():this
         -12 (-2.75% of base) : 84096.dasm - SpinLock:EnterSpin(int):this
         -12 (-1.35% of base) : 182144.dasm - System.Data.ProviderBase.DbConnectionPool:WaitForPendingOpen():this
         -12 (-0.91% of base) : 203628.dasm - System.Data.ProviderBase.DbConnectionPool:WaitForPendingOpen():this
         -12 (-3.09% of base) : 76680.dasm - System.IO.UnmanagedMemoryStream:ReadByte():int:this

Top method improvements (percentages):
          -4 (-11.11% of base) : 84787.dasm - System.Threading.Interlocked:Exchange(byref,int):int
          -4 (-11.11% of base) : 84786.dasm - System.Threading.Interlocked:Exchange(byref,long):long
          -4 (-11.11% of base) : 84785.dasm - System.Threading.Interlocked:Exchange(byref,long):long
          -4 (-10.00% of base) : 84795.dasm - System.Threading.Interlocked:Add(byref,int):int
          -4 (-10.00% of base) : 84781.dasm - System.Threading.Interlocked:Add(byref,int):int
          -4 (-10.00% of base) : 84794.dasm - System.Threading.Interlocked:Add(byref,long):long
          -4 (-10.00% of base) : 84780.dasm - System.Threading.Interlocked:Add(byref,long):long
          -4 (-10.00% of base) : 84789.dasm - System.Threading.Interlocked:Decrement(byref):int
          -4 (-10.00% of base) : 84799.dasm - System.Threading.Interlocked:Decrement(byref):int
          -4 (-10.00% of base) : 84788.dasm - System.Threading.Interlocked:Decrement(byref):long
          -4 (-10.00% of base) : 84798.dasm - System.Threading.Interlocked:Decrement(byref):long
          -4 (-10.00% of base) : 84791.dasm - System.Threading.Interlocked:Increment(byref):int
          -4 (-10.00% of base) : 84801.dasm - System.Threading.Interlocked:Increment(byref):int
          -4 (-10.00% of base) : 84790.dasm - System.Threading.Interlocked:Increment(byref):long
          -4 (-10.00% of base) : 84800.dasm - System.Threading.Interlocked:Increment(byref):long
          -4 (-9.09% of base) : 83670.dasm - Counts:InterlockedCompareExchange(System.Threading.LowLevelLifoSemaphore+Counts,System.Threading.LowLevelLifoSemaphore+Counts):System.Threading.LowLevelLifoSemaphore+Counts:this
          -4 (-9.09% of base) : 83702.dasm - CountsOfThreadsProcessingUserCallbacks:InterlockedCompareExchange(System.Threading.PortableThreadPool+CountsOfThreadsProcessingUserCallbacks,System.Threading.PortableThreadPool+CountsOfThreadsProcessingUserCallbacks):System.Threading.PortableThreadPool+CountsOfThreadsProcessingUserCallbacks:this
          -4 (-9.09% of base) : 84784.dasm - System.Threading.Interlocked:CompareExchange(byref,int,int):int
          -4 (-9.09% of base) : 84782.dasm - System.Threading.Interlocked:CompareExchange(byref,long,long):long
          -4 (-9.09% of base) : 84783.dasm - System.Threading.Interlocked:CompareExchange(byref,long,long):long

391 total methods with Code Size differences (391 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.pmi.windows.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 52282388 (overridden on cmd)
Total bytes of diff: 52276940 (overridden on cmd)
Total bytes of delta: -5448 (-0.01 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -64 : 166938.dasm (-4.42% of base)
         -44 : 169629.dasm (-2.72% of base)
         -36 : 44798.dasm (-1.19% of base)
         -28 : 168303.dasm (-2.57% of base)
         -28 : 165841.dasm (-0.79% of base)
         -24 : 229053.dasm (-1.73% of base)
         -24 : 141293.dasm (-3.92% of base)
         -24 : 44359.dasm (-1.83% of base)
         -20 : 229055.dasm (-1.90% of base)
         -20 : 201777.dasm (-9.62% of base)
         -20 : 211594.dasm (-4.90% of base)
         -20 : 198782.dasm (-2.19% of base)
         -20 : 166971.dasm (-5.32% of base)
         -20 : 198788.dasm (-2.37% of base)
         -20 : 141771.dasm (-2.53% of base)
         -16 : 110111.dasm (-1.26% of base)
         -16 : 161105.dasm (-0.82% of base)
         -16 : 162098.dasm (-2.86% of base)
         -16 : 211589.dasm (-2.48% of base)
         -16 : 44983.dasm (-1.17% of base)

950 total files with Code Size differences (950 improved, 0 regressed), 1 unchanged.

Top method improvements (bytes):
         -64 (-4.42% of base) : 166938.dasm - System.Configuration.SectionInformation:SetRuntimeConfigurationInformation(System.Configuration.BaseConfigurationRecord,System.Configuration.FactoryRecord,System.Configuration.SectionRecord):this
         -44 (-2.72% of base) : 169629.dasm - System.Data.ProviderBase.DbConnectionPool:TryGetConnection(System.Data.Common.DbConnection,int,bool,bool,System.Data.Common.DbConnectionOptions,byref):bool:this
         -36 (-1.19% of base) : 44798.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol:ForceComplete(Microsoft.CodeAnalysis.SourceLocation,System.Threading.CancellationToken):this
         -28 (-0.79% of base) : 165841.dasm - System.Configuration.BaseConfigurationRecord:Init(System.Configuration.Internal.IInternalConfigRoot,System.Configuration.BaseConfigurationRecord,System.String,System.String):this
         -28 (-2.57% of base) : 168303.dasm - System.Data.ProviderBase.DbConnectionPool:TryGetConnection(System.Data.Common.DbConnection,int,bool,bool,System.Data.Common.DbConnectionOptions,byref):bool:this
         -24 (-3.92% of base) : 141293.dasm - Internal.TypeSystem.DefType:ComputeInstanceLayout(int):this
         -24 (-1.83% of base) : 44359.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceAssemblySymbol:ForceComplete(Microsoft.CodeAnalysis.SourceLocation,System.Threading.CancellationToken):this
         -24 (-1.73% of base) : 229053.dasm - System.Threading.ReaderWriterLock:AcquireReaderLock(int):this
         -20 (-2.53% of base) : 141771.dasm - Internal.TypeSystem.LockFreeReaderHashtable`2[__Canon,__Canon][System.__Canon,System.__Canon]:TryAddOrGetExisting(System.__Canon,byref):System.__Canon:this
         -20 (-5.32% of base) : 166971.dasm - System.Configuration.SectionInformation:.ctor(System.Configuration.ConfigurationSection):this
         -20 (-2.19% of base) : 198782.dasm - System.Net.Mail.CheckCommand:BeginSend(System.Net.Mail.SmtpConnection,System.AsyncCallback,System.Object):System.IAsyncResult
         -20 (-2.37% of base) : 198788.dasm - System.Net.Mail.ReadLinesCommand:BeginSend(System.Net.Mail.SmtpConnection,System.AsyncCallback,System.Object):System.IAsyncResult
         -20 (-9.62% of base) : 201777.dasm - System.Net.Security.NetSecurityTelemetry:ConnectionClosed(int):this
         -20 (-4.90% of base) : 211594.dasm - System.Runtime.Caching.MemoryCacheStore:UpdateExpAndUsage(System.Runtime.Caching.MemoryCacheEntry,bool):this
         -20 (-1.90% of base) : 229055.dasm - System.Threading.ReaderWriterLock:AcquireWriterLock(int):this
         -16 (-2.47% of base) : 141294.dasm - Internal.TypeSystem.DefType:ComputeStaticFieldLayout(int):this
         -16 (-3.92% of base) : 141295.dasm - Internal.TypeSystem.DefType:ComputeTypeContainsGCPointers():this
         -16 (-3.45% of base) : 81852.dasm - Microsoft.CodeAnalysis.Collections.SmallConcurrentSetOfInts:Add(Microsoft.CodeAnalysis.Collections.SmallConcurrentSetOfInts,int):bool
         -16 (-1.00% of base) : 44860.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberMethodSymbol:LazyAsyncMethodChecks(System.Threading.CancellationToken):this
         -16 (-1.67% of base) : 44925.dasm - Microsoft.CodeAnalysis.CSharp.Symbols.SourceMethodSymbol:ForceComplete(Microsoft.CodeAnalysis.SourceLocation,System.Threading.CancellationToken):this

Top method improvements (percentages):
          -4 (-11.11% of base) : 172821.dasm - System.Diagnostics.PerformanceData.CounterData:set_Value(long):this
          -4 (-10.00% of base) : 172823.dasm - System.Diagnostics.PerformanceData.CounterData:Decrement():this
          -4 (-10.00% of base) : 172822.dasm - System.Diagnostics.PerformanceData.CounterData:Increment():this
          -4 (-10.00% of base) : 172824.dasm - System.Diagnostics.PerformanceData.CounterData:IncrementBy(long):this
          -4 (-10.00% of base) : 194149.dasm - System.Net.WebSockets.WebSocketBase:UpdateReceiveState(int,int):this
         -20 (-9.62% of base) : 201777.dasm - System.Net.Security.NetSecurityTelemetry:ConnectionClosed(int):this
          -8 (-9.52% of base) : 195996.dasm - System.Net.Http.HttpTelemetry:<OnEventCommand>b__39_4():double:this
          -8 (-9.52% of base) : 201782.dasm - System.Net.Security.NetSecurityTelemetry:<OnEventCommand>b__24_2():double:this
          -4 (-9.09% of base) : 181730.dasm - System.IO.Pipelines.SequencePipeReader:CancelPendingRead():this
          -4 (-9.09% of base) : 199149.dasm - System.Net.Mime.MultiAsyncResult:Enter():this
          -4 (-9.09% of base) : 199153.dasm - System.Net.Mime.MultiAsyncResult:Increment():this
          -4 (-9.09% of base) : 202478.dasm - System.Net.Sockets.SocketsTelemetry:DatagramReceived():this
          -4 (-9.09% of base) : 202479.dasm - System.Net.Sockets.SocketsTelemetry:DatagramSent():this
          -4 (-9.09% of base) : 203490.dasm - System.Net.WebClient:EndOperation():this
          -4 (-9.09% of base) : 229617.dasm - System.Transactions.CheapUnfairReaderWriterLock:ExitReadLock():this
          -4 (-9.09% of base) : 237483.dasm - Xunit.DelegatingExecutionSummarySink:<OnMessageWithTypes>b__13_0(Xunit.MessageHandlerArgs`1[[Xunit.Abstractions.IErrorMessage, xunit.abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c]]):this
          -4 (-8.33% of base) : 9404.dasm - Choose@1376-3:Invoke(int):this
          -8 (-8.33% of base) : 141866.dasm - Internal.TypeSystem.ThreadSafeFlags:AddFlags(int):this
          -4 (-8.33% of base) : 54107.dasm - Microsoft.CodeAnalysis.VisualBasic.Symbols.EmbeddedSymbolManager:SealCollection():this
          -4 (-8.33% of base) : 9434.dasm - Partition@1448-2:Invoke(int):this

950 total methods with Code Size differences (950 improved, 0 regressed), 1 unchanged.

```

</details>

--------------------------------------------------------------------------------

**Comment by VSadov** [comment]
All interlocked operations in CLR are meant to have a full fence semantics. 

The issue is that when interlocked operations are implemented via a loop of half-fenced LL/SC – like in  `ldaxr`/`<op>`/`stlxr`/`cbnz`, there is a chance for the **subsequent** loads to float before the `stlxr` into the `<op>` body thus violating the full-fence expectation. Preventing that requires adding a full fence after the loop (i.e. `ldaxr`/`<op>`/`stlxr`/`cbnz`/`dmb`) to have the right semantics.

**Comment by EgorBo** [comment]
> All interlocked operations in CLR are meant to have a full fence semantics.
> 
> The issue is that when interlocked operations are implemented via a loop of half-fenced LL/SC – like in `ldaxr`/`<op>`/`stlxr`/`cbnz`, there is a chance for the **subsequent** loads to float before the `stlxr` into the `<op>` body thus violating the full-fence expectation. Preventing that requires adding a full fence after the loop (i.e. `ldaxr`/`<op>`/`stlxr`/`cbnz`/`dmb`) to have the right semantics.

Good point, it's mentioned in https://patchwork.kernel.org/project/linux-arm-kernel/patch/1391516953-14541-1-git-send-email-will.deacon@arm.com/

**Comment by EgorBo** [comment]
@VSadov however, looks like there is an issue in our code for `CompareExchange`:
```
            ldaxr   w4, [x0]
            cmp     w4, w2
            bne     G_M5868_IG03
            stlxr   w3, w1, [x0]
            cbnz    w3, G_M5868_IG02
G_M5868_IG03:
            dmb     ish
            mov     w0, w4
```
if we go `bne     G_M5868_IG03` path we don't clear `Exclusive Access` flag from that memory which is why clang emits `clrx` https://godbolt.org/z/9jsGGEWd4

**Comment by VSadov** [comment]
As I understand `clrx` is used rarely for cases like OS switching threads - so that if one thread preempts another on the same core there is no confusion who has the access. 

Not sure why clang emits it there. Assuming ldaxr and stlxr are used in pairs, nothing would go wrong if monitor is not reset. And it will not last anyways because of context switches, interrupts, etc.

Maybe there is a scenario if you write the actual OS code or a device driver.

**Comment by VSadov** [comment]
FWIW: MSVC does not do `clrx` - https://godbolt.org/z/jcYqxjn99

**Comment by EgorBo** [comment]
@VSadov thanks! learned more today about atomics 🙂

**Pull request closed without merging**
