### PR TITLE
Remove the directory src/coreclr/tests/src

### PR DESCRIPTION
**Pull request by trylek**
Move CLRTest.*.targets under src/tests/Common;
Consolidate Directory.Build.props in src/tests, src/tests/Common and src/coreclr/tests/src - src/tests is now the "master" version, src/tests/Common just points to it and src/coreclr/tests/src no longer exists;
Move Directory.Build.targets from src/coreclr/tests/src to src/tests/Directory.Build.targets that was previously just importing the src/coreclr/tests/src version;
Move the few remaining scripts under src/coreclr/tests/src to src/tests/Common (dirs.proj, nobuild.targets, runonly.targets, xunitconsolerunner.depproj).

Thanks

Tomas

### CODE REVIEW

**Comment by trylek** [comment]
Seems to be finally working now... /cc @dotnet/runtime-infrastructure

**Review by ViktorHofer — APPROVED** [review]
LGTM assuming the outerloop failures are unrelated?

**Comment by trylek** [comment]
I believe the outerloop failure in the Alpine run is expected, adding @janvorli to confirm.

**Comment by trylek** [comment]
Confirmed with Jan, he's already sent out the PR for the fix (https://github.com/dotnet/runtime/pull/42195). I suspect we'll need to add a WASM-specific exclusion for the UnmanagedCallersOnlyTest to issues.targets, apparently after Aaron's recent refactoring the test is no longer compatible with the WASM platform, FYI /cc @naricc, @SamMonoRT and @directhex.

**Review by safern — COMMENTED** [review]
LGTM

**Pull request merged**
