### PR TITLE
[JIT] SVE Cleanup: Merging formats SVE_AB_3A and SVE_AD_3A into SVE_AA_3A

### PR DESCRIPTION
**Pull request by TIHan**
There is the first part some SVE cleanup where we are going to try to merge similar formats into one.

### CODE REVIEW

**Comment by TIHan** [comment]
@kunalspathak @dotnet/arm64-contrib this is ready.

**Review by a74nh — APPROVED** [review]
This LGTM. Glad there were some groups to be found.

**Comment by TIHan** [comment]
> Glad there were some groups to be found.

Yea, there are still more, I just don't want to make a giant PR for it. :)

**Review by kunalspathak — APPROVED** [review]
LGTM, Thanks for doing it. I know it is tricky to find these out.

**Pull request merged**
