### PR TITLE
First pass removing IL verifier from JIT

### PR DESCRIPTION
**Pull request by BruceForstall**
https://github.com/dotnet/runtime/issues/32648

### CODE REVIEW

**Comment by BruceForstall** [comment]
@AndyAyersMS It's pretty easy to "play compiler" and remove everything we're not currently using. But extracting some things is harder, e.g., `verCheckTailCallConstraint` is harder to tease out.

**Comment by AndyAyersMS** [comment]
Do you think there's value in doing this now, or should we wait and do it early in the .NET 7 cycle?

**Comment by BruceForstall** [comment]
It was a quick experiment to see how easy it would be to remove. There are a lot of tendrils of the "verifier" that are still used in apparently non-verifier contexts, so would be harder to remove. I'll close this.

**Comment by EgorBo** [comment]
I guess now it's a good time to do it 🙂 (early stage of .NET 7)

**Pull request closed without merging**
