### PR TITLE
[RISC-V] System.Console CancelKeyPressTests.ExitDetectionNotBlockedByHandler increase timeout

### PR DESCRIPTION
**Pull request by tomeksowi**
Increase timeout on CancelKeyPressTests.ExitDetectionNotBlockedByHandler on Debug RISC-V, similar to #96187 or #96186.

Part of #84834, cc @dotnet/samsung

### CODE REVIEW

**Review by Bajtazar — APPROVED** [review]

**Review by yurai007 — APPROVED** [review]

**Comment by risc-vv** [comment]
<details><summary>c17a0c04 is being scheduled for building and testing</summary>

GIT: `c17a0c04c8613cc68f33b584cd0a8aaf8ca573c9`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by risc-vv** [comment]
<details><summary>c17a0c04 is being scheduled for building and testing</summary>

GIT: `c17a0c04c8613cc68f33b584cd0a8aaf8ca573c9`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by jkotas** [comment]
The change does not work as expected:
```
    CancelKeyPressTests.HandlerInvokedForSigInt(redirectStandardInput: False) [FAIL]
      System.ArgumentException : Field marshaling is not supported by Invoke: WaitFailTestTimeoutSeconds
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs(602,0): at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.GetMethodInfo(Delegate d)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs(128,0): at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Action`1 method, String arg, RemoteInvokeOptions options)
        /_/src/libraries/System.Console/tests/CancelKeyPress.Unix.cs(100,0): at CancelKeyPressTests.HandlerInvokedForSignal(Int32 signalOuter, Boolean redirectStandardInput)
        /_/src/libraries/System.Console/tests/CancelKeyPress.Unix.cs(26,0): at CancelKeyPressTests.HandlerInvokedForSigInt(Boolean redirectStandardInput)
```

**Comment by risc-vv** [comment]
<details><summary>832b95f9 is being scheduled for building and testing</summary>

GIT: `832b95f93df4bfd0ef482054e438448fb2474c56`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by risc-vv** [comment]
<details><summary>832b95f9 is being scheduled for building and testing</summary>

GIT: `832b95f93df4bfd0ef482054e438448fb2474c56`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by risc-vv** [comment]
<details><summary>832b95f9 is being scheduled for building and testing</summary>

GIT: `832b95f93df4bfd0ef482054e438448fb2474c56`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Review by jkotas — APPROVED** [review]

**Pull request merged**
