### PR TITLE
Add `-skipgenerateversion` option to not generate native version headers

### PR DESCRIPTION
**Pull request by BruceForstall**
This allows skipping yet another thing when doing incremental builds.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib Can someone review this minor build change?

**Review by sandreenko — APPROVED** [review]

**Review by jashook — CHANGES_REQUESTED** [review]
Please make the changes in the Unix script as well if they are not there already.

**Review by jashook — COMMENTED** [review]
Comment instead of request change.

**Comment by BruceForstall** [comment]
It turns out the Unix script already had `-skipgenerateversion` so I just renamed my Windows option change to match.

**Comment by BruceForstall** [comment]
@jashook I need you to approve (or somehow not be in the state "1 change requested" before I can merge. Can you take a look?

**Review by jashook — APPROVED** [review]

**Pull request merged**
