### PR TITLE
Corrected and fixed comparison for System.Reflection.MetadataLoadContext

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
This PR will add fix to System.Reflection.MetadataLoadContext
Corresponding issue - #28046

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please also add a test case for this?

**Comment by MCCshreyas** [comment]
@jkotas Can you please give me direction to test file where should I write tests!
Thanks.

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.Get.CornerCases.cs looks most appropriate.

**Comment by steveharter** [comment]
Closing; no repro was found. See the original issue for more info.

**Pull request closed without merging**
