### PR TITLE
[release/6.0] Update dotnet host for testing and fix failing globalization test

### PR DESCRIPTION
**Pull request by akoeplinger**
We changed how we got the OS version in f30e7fa to account for the macOS versioning changes.

The `dotnet` host used for testing was still on a version before that change so the RID it set (which flows through to `RuntimeInformation.RuntimeIdentifier`) was using the old format.
Updating to the latest 6.0.13 and adding the change from 5da4464 so we only check for the major OS version fixes the OSVersion_ValidVersion_OSX test.

This also backports https://github.com/dotnet/runtime/pull/63971 which is necessary to fix a globalization test on macOS 12.

Fixes https://github.com/dotnet/runtime/issues/80252

### CODE REVIEW

**Comment by akoeplinger** [comment]
@carlossanlop this is a test/CI-only change so I think we don't need approval right?

**Review by ViktorHofer — APPROVED** [review]

**Review by tarekgh — APPROVED** [review]
Thanks @akoeplinger for fixing this.

**Review by carlossanlop — APPROVED** [review]
Thank you so much for fixing this, @akoeplinger.

**Comment by carlossanlop** [comment]
> @carlossanlop this is a test/CI-only change so I think we don't need approval right?

Yes, it's tell mode, no approval needed. I'll merge when the CI finishes.

**Comment by carlossanlop** [comment]
CI failures are unrelated.

- Wasm Emscripten exception, seen in other PRs: https://github.com/dotnet/runtime/issues/80574
- Console mono linux failure: https://github.com/dotnet/runtime/issues/80575
- System.Drawing test failed due to failure of OSX XType to connect to font daemon. Infra problem, will open issue if I see it again.
- OSX checked failure is https://github.com/dotnet/runtime/issues/80476

Ready to merge. :shipit:

**Pull request merged**
