### PR TITLE
Fix build issues

### PR DESCRIPTION
**Pull request by ivo-stoilov**
Backport #76189 to release/7.0 branch

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
@ivo-stoilov Servicing 7.0 requires some more work and a business case. Can you elaborate on the need for this change in the .NET 7 branch? More than willing to help make a case if it is blocking you.

**Comment by ivo-stoilov** [comment]
Hello @AaronRobinsonMSFT, actually I have found this issue using the official 7.0.2 release tag, which is the main reason for this change.

**Comment by AaronRobinsonMSFT** [comment]
> Hello @AaronRobinsonMSFT, actually I have found this issue using the official 7.0.2 release tag, which is the main reason for this change.

If this isn't blocking or negatively impacting a supported scenario there isn't an option for adding this to a servicing branch, which is what release/7.0 represent.

**Comment by AaronRobinsonMSFT** [comment]
@ivo-stoilov I'm going to close this for now as I can't see a way to justify this going into a servicing branch. If you have a blocking scenario for .NET 7, we can reconsider.

/cc @jeffschwMSFT

**Comment by ivo-stoilov** [comment]
@AaronRobinsonMSFT, agreed, I would like just to avoid this issue in the future .net 7 releases.

**Pull request closed without merging**
