### PR TITLE
Switch over JIT/Methodical tests to run using merged wrappers

### PR DESCRIPTION
**Pull request by trylek**
fyi @jkoritzinsky

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
Two things that immediately popped out to me:

1. We can remove the `range_d.csproj` and `range_r.csproj` projects as the tests they include are covered by `Methodical_d.csproj` and `Methodical_r.csproj` respectively.
2. We need to update the generator to automatically exclude all `<RequiresProcessIsolation>true</RequiresProcessIsolation>` tests on any platforms where we can't launch new processes. Given the small test coverage loss there, I think that's okay (many of the tests that are going to have `RequiresProcessIsolation` set to true already don't run on mobile platforms due to other reasons).

**Comment by trylek** [comment]
@BruceForstall - once I pass initial outerloop validation on the change, I plan to start triggering Crossgen2 and stress runs to further validate the change. Please let me know which pipelines you find the most important to start with.

**Comment by trylek** [comment]
@jkoritzinsky - thanks for your immediate feedback. I believe my change should include removal of the wrappers under Array you previously added, if it doesn't, it will likely fail the build.

**Comment by trylek** [comment]
Hmm, in fact it won't fail the build, it only fails local test run because the Python code for producing the summary table hits a duplicate dictionary key. I'm not sure whether that's exercised in lab pipeline runs, I guess we'll see in an hour or two.

**Comment by jkoritzinsky** [comment]
Yes, it looks like they have been removed. GitHub's diff was not showing it to me due to the number of changed files, but I validated in the GitHub Codespaces view that the Range merged wrappers are gone.

**Comment by trylek** [comment]
@jkoritzinsky - Hehe, I was curious why we're not observing the removal of the range_d and range_r projects you previously added. Turns out GitHub decided the newly added Methodical_* projects are their renames.

**Comment by trylek** [comment]
One additional bit of debt in this change is the lack of issues.targets migration regarding the tests involved; I plan to work on that next.

**Comment by trylek** [comment]
@jkoritzinsky - OK, so the failure in the hijacking test is "our" bug; the test is suppressed in issues.targets, it's just that my "AdditionalInfraFixes" PR https://github.com/dotnet/runtime/pull/67718 marks it as out-of-process, I suspect that's why something breaks and the issues.targets entry is not honored.

**Comment by jkoritzinsky** [comment]
Okay if the hijacking failure is our bug, then the only other failing test is `JIT/Methodical/tailcall/compat_i4_u_il_d/compat_i4_u.dll` on the Mono interpreter, which I would be fine disabling for now against a new issue.

**Comment by trylek** [comment]
I have removed the WIP tag and I believe the change should be ready for review. In recent testing I have already achieved a green runtime-coreclr outerloop, runtime-coreclr jitstress, and runtime-coreclr ilasm runs, I'm rerunning the r2r-extra pipeline where I hit some timeouts yesterday.

**Comment by BruceForstall** [comment]
The formatting job should get fixed with https://github.com/dotnet/runtime/pull/67785

**Review by jkoritzinsky — APPROVED** [review]
LGTM!

**Comment by BruceForstall** [comment]
GitHub is hanging my browser when I try to review...

CLRTest.CrossGen.targets:
Use `2>NUL` not `2>NULL` on Windows. With 2 `L`, you'll create an actual file named `NULL`.

Otherwise, LGTM.

**Review by BruceForstall — APPROVED** [review]

**Comment by trylek** [comment]
Thanks Bruce for your feedback, I'll fix the NULL -> NUL in the AdditionalInfraFixes PR and I'll rebase and retest this PR on top of it. Have a great weekend!

**Comment by trylek** [comment]
Based on Andrew's suggestion I have experimentally combined this change with a subtle tweak to <code>src/tests/run.sh</code> making event log opt-in instead of opt-out. The purpose of this experiment is to validate whether it fixes the failures seen in the r2r-extra pipeline on Unix. You can find more detail in the tracking issue https://github.com/dotnet/runtime/issues/64263.

**Comment by trylek** [comment]
Hmm, in fact I don't think there's any chance this might work as the script is not actually exercised in the lab pipelines at all; instead I'll add targeted instrumentation letting us see at runtime whether the event log has been activated (in some other manner) directly in the offending runs.

**Comment by trylek** [comment]
I have verified that in the latest r2r-extra run I no longer see the hangs; some unrelated tests failed and two merged wrappers crashed on a runtime JIT assertion that is a known issue according to Bruce. I plan to merge this in after retesting unless some new catastrophic failure appears.

**Pull request merged**
