### PR TITLE
[WIP] #61971 - Fix a bug causing EventCounter to fire twice on linux

### PR DESCRIPTION
**Pull request by Tomius**
The #61971 bug was introduced in c67684b because  the `sleepDurationInMilliseconds` started to be calculated using `counterGroup._nextPollingTimeStamp` before updating it.

The fix here is to calculate the  `sleepDurationInMilliseconds` after having run the `counterGroup.OnTimer();` (and so updating the `counterGroup._nextPollingTimeStamp`)

### CODE REVIEW

**Comment by kasperk81** [comment]
https://github.com/dotnet/runtime/blob/c0dabb527176d1fdb6ba7bdca75fd80d69482be2/src/libraries/Microsoft.Diagnostics.Tracing.EventSource.Redist/src/Microsoft.Diagnostics.Tracing.EventSource.Redist.csproj#L1
is a .net framework project failing with cs8179, it needs
```
  <ItemGroup>
    <PackageReference Include="System.ValueTuple" Version="$(SystemValueTupleVersion)" />
  </ItemGroup>
```

**Comment by Tomius** [comment]
Hello @sywhang, could you review this change please?

**Comment by sywhang** [comment]
@Tomius hey, I am no longer on the .NET team. @noahfalk and @josalem would be more appropriate people to review this PR now

**Comment by kasperk81** [comment]
https://github.com/dotnet/runtime/blob/235915ea5e15604c80889c2ad7da9e999bc36e57/src/tests/tracing/eventcounter/runtimecounters.cs#L113 test is failing due to your change.

**Comment by Tomius** [comment]
> https://github.com/dotnet/runtime/blob/235915ea5e15604c80889c2ad7da9e999bc36e57/src/tests/tracing/eventcounter/runtimecounters.cs#L113 test is failing due to your change.
Interesting, thanks for letting me know!

I'm a bit confused about this one, because locally for me it consistently fails on master, but it starts consistently passing after my change :confused:

**Comment by Tomius** [comment]
This PR has become very messy, closing it in favor of https://github.com/dotnet/runtime/pull/62139

**Pull request closed without merging**
