### PR TITLE
[LoongArch64] add gc directory for LoongArch64.

### PR DESCRIPTION
**Pull request by shushanhf**
[LoongArch64] add gc directory for LoongArch64.

### CODE REVIEW

**Comment by mangod9** [comment]
LGTM, but will have someone take a look as well

**Comment by BruceForstall** [comment]
> LGTM, but will have someone take a look as well

@mangod9 Could you assign one or more reviewers to this PR?

**Review by Maoni0 — APPROVED** [review]
LGTM

**Review by mangod9 — APPROVED** [review]
Looks like there are no conflicts, so should be ok to merge if ready.

**Pull request merged**
