### PR TITLE
[release/6.0] Handle parameterless ctors in structs in STJ's ReflectionEmitMemberAccessor

### PR DESCRIPTION
**Pull request by EgorBo**
Backport of https://github.com/dotnet/runtime/pull/62989

## Customer Impact
Structs with field initializations ([C#10 feature](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/parameterless-struct-constructors)) can cause NRE or AVE exceptions(crashes), minimal repro:
```csharp
JsonSerializer.Deserialize<Foo>("{}");

public struct Foo
{
    public Foo() {}
    public float A = 1;
}
```
causes `AccessViolationException`. There are two bug reports by users against 6.0: https://github.com/dotnet/runtime/issues/62983 and https://github.com/dotnet/runtime/issues/67781
This PR fixes this behaviour.

## Testing
This PR adds tests

## Risk

low

cc @eiriktsarpalis @danmoseley

### CODE REVIEW

**Review by eiriktsarpalis — APPROVED** [review]
Thanks Egor!

**Comment by JulieLeeMSFT** [comment]
@EgorBo  please check the test failure. Once it is good, we will request to @jeffschwMSFT for servicing consider.

**Review by RikkiGibson — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
lgtm.  @danmoseley would you also like to review?

**Comment by danmoseley** [comment]
Seems good to me. Where is the AV, though? Is that worth a separate fix, or does the JIT generally not promise to not AV on bad IL?

**Comment by jeffschwMSFT** [comment]
Unverifiable IL can easily cause the runtime and JIT to lead to crashes.  No guarantees with bad IL.

**Comment by danmoseley** [comment]
is CI broken?

**Comment by carlossanlop** [comment]
@danmoseley this was missing the `servicing-consider` label, I added it. Needs Tactics approval.

**Comment by ericstj** [comment]
@eerhardt I see we took a similar fix in DependencyInjection in https://github.com/dotnet/runtime/pull/59625.  Should we backport that to 6.0 as well?

**Comment by ericstj** [comment]
For that matter, if I look at all uses of `OpCodes.Newobj` I see other places that don't seem to handle value types with constructors.
https://source.dot.net/#System.Private.CoreLib/OpCodes.cs,69b6a0a0bb8ecaa2,references

At least this one seems broken too:
https://github.com/dotnet/runtime/blob/53859621b73159abe7242c4bb4b837e382f0a519/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlDataContract.cs#L277-L312

**Comment by eerhardt** [comment]
> I see we took a similar fix in DependencyInjection in https://github.com/dotnet/runtime/pull/59625. Should we backport that to 6.0 as well?

I'm not sure it would meet the bar. It was never supported in DI before, so it isn't a regression. Also I haven't seen real user feedback needing it. You also don't typically gain anything by using ValueTypes in DI since you are always boxing/unboxing. So you might as well just use a `class`.

So unless there is a need, I don't think it is necessary to backport to 6.0.

**Review by carlossanlop — CHANGES_REQUESTED** [review]
@EgorBo @eiriktsarpalis @layomia @dotnet/area-system-text-json this PR is missing the OOB version bumping changes. Example: https://github.com/dotnet/runtime/pull/67104/files

In the S.T.Json.csproj, need to add this line:
```cs
<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
```

And need to bump the ServicingVersion number to the next one:
```cs
    <ServicingVersion>INCREASE ME</ServicingVersion>
```

**Comment by eiriktsarpalis** [comment]
@carlossanlop done.

**Review by carlossanlop — APPROVED** [review]

**Comment by carlossanlop** [comment]
Failures are unrelated: `System.IO.Compression.Tests.ZipFile_Unix.UnixCreateSetsPermissionsInExternalAttributes`

**Pull request merged**
