### PR TITLE
Extend CPU capabilities detection for osx-arm64 (#62832)

### LINKED ISSUE #62832: System.Runtime.Intrinsics.Arm.Sha256 APIs are unavailable on Apple Silicon
### Description

It appears that `System.Runtime.Intrinsics.Arm.Sha256.IsSupported` returns `false` on M1 Pro and, consequently, fails JIT when attempting to use the corresponding intrinsics.

Please let me know if you need any additional details. Unfortunately, I have no experience with C++ specifically but otherwise would be happy to investigate if you point me to the right direction where to look for the bits and pieces responsible for CPU feature detection on macOS.

### Reproduction Steps

Execute the following snippet:
```csharp
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;

Console.WriteLine(
    $"{nameof(ArmBase)}:{ArmBase.IsSupported}, " +
    $"{nameof(ArmBase.Arm64)}:{ArmBase.Arm64.IsSupported}, " +
    $"{nameof(AdvSimd)}:{AdvSimd.IsSupported}, " +
    $"{nameof(Sha256)}:{Sha256.IsSupported}\n");

var msg0 = Vector128<uint>.Zero;
var msg1 = Vector128<uint>.Zero;

msg0 = Sha256.ScheduleUpdate0(msg0, msg1);
```

### Expected behavior

Output:
```
ArmBase:True, Arm64:True, AdvSimd:True, Sha256:True
```

### Actual behavior

Output:
```
ArmBase:True, Arm64:True, AdvSimd:True, Sha256:False

Unhandled exception. System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.Intrinsics.Arm.Sha256.ScheduleUpdate0(Vector128`1 w0_3, Vector128`1 w4_7)
   at Program.<Main>$(String[] args) in /Users/____/Code/LOC/Sha256Repro/Program.cs:line 11
```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

NB: Reproducible with both 6.0.100 and 6.0.101
`dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.1
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc
```

`sysctl -a | grep hw.optional`:
```
hw.optional.arm.FEAT_AES: 1
hw.optional.arm.FEAT_BF16: 0
hw.optional.arm.FEAT_BTI: 0
hw.optional.arm.FEAT_CSV2: 1
hw.optional.arm.FEAT_CSV3: 1
hw.optional.arm.FEAT_DPB: 1
hw.optional.arm.FEAT_DPB2: 1
hw.optional.arm.FEAT_DotProd: 1
hw.optional.arm.FEAT_ECV: 1
hw.optional.arm.FEAT_FCMA: 1
hw.optional.arm.FEAT_FHM: 1
hw.optional.arm.FEAT_FP16: 1
hw.optional.arm.FEAT_FPAC: 0
hw.optional.arm.FEAT_FRINTTS: 1
hw.optional.arm.FEAT_FlagM: 1
hw.optional.arm.FEAT_FlagM2: 1
hw.optional.arm.FEAT_I8MM: 0
hw.optional.arm.FEAT_JSCVT: 1
hw.optional.arm.FEAT_LRCPC: 1
hw.optional.arm.FEAT_LRCPC2: 1
hw.optional.arm.FEAT_LSE: 1
hw.optional.arm.FEAT_LSE2: 1
hw.optional.arm.FEAT_PAuth: 1
hw.optional.arm.FEAT_PAuth2: 0
hw.optional.arm.FEAT_PMULL: 1
hw.optional.arm.FEAT_RDM: 1
hw.optional.arm.FEAT_SB: 1
hw.optional.arm.FEAT_SHA1: 1
hw.optional.arm.FEAT_SHA256: 1
hw.optional.arm.FEAT_SHA3: 1
hw.optional.arm.FEAT_SHA512: 1
hw.optional.arm.FEAT_SPECRES: 0
hw.optional.arm.FEAT_SSBS: 1
hw.optional.AdvSIMD: 1
hw.optional.AdvSIMD_HPFPCvt: 1
hw.optional.arm64: 1
hw.optional.armv8_1_atomics: 1
hw.optional.armv8_2_fhm: 1
hw.optional.armv8_2_sha3: 1
hw.optional.armv8_2_sha512: 1
hw.optional.armv8_3_compnum: 1
hw.optional.armv8_crc32: 1
hw.optional.armv8_gpi: 1
hw.optional.breakpoint: 6
hw.optional.floatingpoint: 1
hw.optional.neon: 1
hw.optional.neon_fp16: 1
hw.optional.neon_hpfp: 1
hw.optional.ucnormal_mem: 1
hw.optional.watchpoint: 4
```

### Other information

_No response_

### PR DESCRIPTION
**Pull request by neon-sunset**
Fixes https://github.com/dotnet/runtime/issues/62832

This change adds support for detection of CPU capabilities on targets like `osx-arm64` which do not have `getauxval(AT_HWCAP)` as recommended in https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code.

In addition, we also opportunistically assume that the environment does not support the scenario in which the execution of `DC ZVA` memory zeroing instructions can be trapped by the kernel or host system. However, if https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/codeman.cpp#L1485 completely overrides this flag, then the change is unnecessary. Please let me know what is the best way to handle it.

Otherwise, on M1, `DC ZVA` zeroing completely saturates data bandwidth which makes it fully efficient. 
References: https://www.realworldtech.com/forum/?threadid=192122&curpostid=192321 and https://twitter.com/polydron/status/1458890243336138771?s=21

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=62958) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=62958) before we can accept your contribution.<br/><br/>:x: neon-sunset [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=62958)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=62958) it.</sub>

**Comment by neon-sunset** [comment]
Hm, it seems like the bot didn't tag area owners. CC @janvorli just in case :)

**Comment by janvorli** [comment]
cc: @dotnet/jit-contrib, this stuff is managed by the JIT people.

**Review by EgorBo — APPROVED** [review]

**Comment by EgorBo** [comment]
Looks good to me except `Dczva` I am not familiar with, so waiting for Approval from @echesakovMSFT who used it in https://github.com/dotnet/runtime/pull/46609

**Review by echesakov — APPROVED** [review]

**Comment by neon-sunset** [comment]
@EgorBo if you still have an M1 device with 12.0/12.0.1, could you post the output of `systcl -a | grep machdep.cpu`?

**Comment by echesakovMSFT** [comment]
@neon-sunset Do you know why the logic in https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/codeman.cpp#L1485 does not set the flag? 

I looked more carefully at the Arm spec and it might be that `DC ZVA` uses a different size of the block when zeroing the memory. If it is a case, we cannot just enable it like that.

**Comment by EgorBo** [comment]
> @EgorBo if you still have an M1 device with 12.0/12.0.1, could you post the output of `systcl -a | grep machdep.cpu`?

```
machdep.cpu.brand_string: Apple M1
machdep.cpu.core_count: 8
machdep.cpu.cores_per_package: 8
machdep.cpu.logical_per_package: 8
machdep.cpu.thread_count: 8
```

> Update: given that M1 uses 128 bytes cacheline

as well as most other arm hw I'd guess?

**Comment by echesakovMSFT** [comment]
> > Update: given that M1 uses 128 bytes cacheline
> 
> as well as most other arm hw I'd guess?

I don't know if most of them use 128 bytes cacheline. 
I always thought it's 64 bytes. For example, [Cortex-A77](https://developer.arm.com/documentation/101111/0101/functional-description/level-1-memory-system/about-the-l1-memory-system?lang=en)

**Comment by EgorBo** [comment]
> I don't know if most of them use 128 bytes cacheline. I always thought it's 64 bytes. For example, [Cortex-A77](https://developer.arm.com/documentation/101111/0101/functional-description/level-1-memory-system/about-the-l1-memory-system?lang=en)

.NET assumes it's 128 by default on arm, e.g. https://github.com/dotnet/runtime/blob/38477909eeb6296664cc184d461035b1774ea2df/src/libraries/System.Private.CoreLib/src/Internal/Padding.cs#L13 (used against "false sharing")

**Comment by neon-sunset** [comment]
Some update regarding `DC ZVA`. After re-reading documentation it appears that the erased block size is not constrained or limited to cache line size.

Excerpt from ARM [documentation](https://developer.arm.com/documentation/ddi0487/gb/):
```
DCZID_EL0, Data Cache Zero ID register
...
Indicates the block size that is written with byte values of 0 by the DC ZVA (Data Cache Zero by Address) System instruction....
--- DZP, bit [4] ---
Data Zero Prohibited. This field indicates whether use of DC ZVA instructions is permitted or prohibited.
...
--- BS, bits [3:0] ---
Log2 of the block size in words. The maximum size supported is 2KB (value == 9).
```
After further research, I found an interesting piece of code that performs the heuristics to check the behaviour of `DC ZVA`:
https://i10git.cs.fau.de/pycodegen/pystencils/-/merge_requests/230/diffs#d279bd8f1d8c70fc71e225327b9a92bf44666f4d

On my device (M1 Pro macOS 12.1) it does return `64 (bytes)` as the zeroed block size.

**Comment by echesakovMSFT** [comment]
@neon-sunset Thanks for following up. I believe we don't need to do anything for `DC ZVA` in this PR - if `GetDataCacheZeroIDReg()` returns `4` on macOS that the corresponding flag will be set.

**Comment by neon-sunset** [comment]
@echesakovMSFT Thanks, that's what I was asking about in the initial post :) Still, it was interesting to look into. Will revert the `DC ZVA` part.

**Comment by echesakovMSFT** [comment]
I double checked this.

Consider the following C# program:
```c#
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace StackZeroing
{
    [StructLayout(LayoutKind.Sequential, Size = 1024)]
    struct LargeStruct
    {
    }

    class Program
    {
        [MethodImpl(MethodImplOptions.NoInlining)]
        static void KeepAlive(ref LargeStruct ls)
        {
        }

        static void Main(string[] args)
        {
            LargeStruct ls = default(LargeStruct);
            KeepAlive(ref ls);
        }
    }
}
```

On Apple M1 the JIT will generate:
```asm
$CORE_ROOT/corerun StackZeroing.dll
; Assembly listing for method StackZeroing.Program:Main(System.String[])
; Emitting BLENDED_CODE for generic ARM64 CPU - MacOS
; optimized code
; fp based frame
; partially interruptible
; No PGO data
; Final local variable assignments
;
;* V00 arg0         [V00    ] (  0,  0   )     ref  ->  zero-ref    class-hnd single-def
;  V01 loc0         [V01    ] (  1,  1   )  struct (1024) [fp+10H]   do-not-enreg[XS] must-init addr-exposed ld-addr-op single-def
;# V02 OutArgs      [V02    ] (  1,  1   )  lclBlk ( 0) [sp+00H]   "OutgoingArgSpace"
;
; Lcl frame size = 1024

G_M10532_IG01:              ;; offset=0000H
        00000000          sub     sp, sp, #0x410
        00000000          stp     fp, lr, [sp]
        00000000          mov     fp, sp
        00000000          movi    v16.16b, #0x00
        00000000          add     x9, fp, #80
        00000000          add     x10, fp, #976
        00000000          stp     q16, q16, [x9,#-64]
        00000000          stp     q16, q16, [x9,#-32]
        00000000          bfm     x9, xzr, #0, #5
        00000000          dczva   x9
        00000000          add     x9, x9, #64
        00000000          cmp     x9, x10
        00000000          blo     pc-16 (-4 instructions)
        00000000          stp     q16, q16, [x10]
        00000000          stp     q16, q16, [x10,#32]
						;; bbWeight=1    PerfScore 11.50
G_M10532_IG02:              ;; offset=003CH
        00000000          add     x0, fp, #16	// [V01 loc0]
        00000000          bl      StackZeroing.Program:KeepAlive(byref)
						;; bbWeight=1    PerfScore 1.50
G_M10532_IG03:              ;; offset=0044H
        00000000          ldp     fp, lr, [sp]
        00000000          add     sp, sp, #0x410
        00000000          ret     lr
						;; bbWeight=1    PerfScore 2.50

; Total bytes of code 80, prolog size 60, PerfScore 23.50, instruction count 20, allocated bytes for code 80 (MethodHash=826bd6db) for method StackZeroing.Program:Main(System.String[])
; ============================================================
```

**Review by echesakov — APPROVED** [review]
LGTM

**Comment by echesakovMSFT** [comment]
@neon-sunset Thank you for your contribution!

**Pull request merged**
