### PR TITLE
Add support for containing RotateLeft/RotateRight on Arm64

### LINKED ISSUE #101027: arm64: ror+eor -> eor, ror
A pattern that can be found in `Marvin.Block`:
```cs
uint Block(uint p0, uint p1) => p0 ^ BitOperations.RotateLeft(p1, 23);
```
Current codegen:
```asm
    ror     w1, w1, #23
    eor     w0, w0, w1
```
Expected codegen:
```asm
    eor     w0, w0, w1, ror #23
```

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #101027

### CODE REVIEW

**Comment by tannergooding** [comment]
Some decent diffs with no TP impact for the x ^ rotate(y, cns) pattern: https://dev.azure.com/dnceng-public/public/_build/results?buildId=643031&view=ms.vss-build-web.run-extensions-tab

-11,540 on Linux Arm64, with about 25% of that in PGO benchmarks

CC. @dotnet/jit-contrib, @EgorBo this should be ready for review.

**Review by EgorBo — APPROVED** [review]
LGTM, thanks!

**Comment by tannergooding** [comment]
hmmm, there is an SPMI replay failure. But it's in `hwintrinsiccodegenarm64.cpp` for `DecodeFromUtf8` (which was updated over the weekend): https://discord.com/channels/143867839282020352/312132327348240384/1229436153703170188

I think it's likely unrelated to this PR, but I'll investigate and make sure an issue is opened before merging.

**Comment by tannergooding** [comment]
Opened https://github.com/dotnet/runtime/issues/101070, it is asserting without this PR and in other CI legs.

**Pull request merged**
