### PR TITLE
Do not use ExecutableMemoryAllocator on 64 bit platforms if default base address usage is requested

### PR DESCRIPTION
**Pull request by gbalykov**
cc @alpencolt

### CODE REVIEW

**Comment by gbalykov** [comment]
@janvorli we use `g_useDefaultBaseAddr` with custom default base addresses in r2r images (see https://github.com/dotnet/runtime/pull/65567) in order to ensure that no relocations happen in these images and, thus, memory consumption is reduced. On 64bit platforms executable memory allocator is tried first and default base address is never used even if we requested runtime to use it. Also a mitigation of the problem that you've described will simply be to not set `g_useDefaultBaseAddr`.

**Comment by janvorli** [comment]
@gbalykov thank you, that makes sense then.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by gbalykov** [comment]
Thanks!

**Pull request merged**
