### PR TITLE
Fix handling of non-mergeable char classes in regex prefix analyzer

### LINKED ISSUE #52612: Incorrect Regex matching result in compiled mode
Reproduce in .NET5.0.
The code below will print the following where False is an error:
False
True

```c#
string input = "this string has .digest as a substring";
Regex reC = new(@"[^a-z0-9]etag|[^a-z0-9]digest", RegexOptions.Compiled);
Regex re = new(@"[^a-z0-9]etag|[^a-z0-9]digest");
Console.WriteLine(reC.IsMatch(input));
Console.WriteLine(re.IsMatch(input));
```

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/52612

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
Looks reasonable to me.

**Comment by danmoseley** [comment]
@veanes if you want this fix in your branch, you can do `git format-patch` etc. Or just wait and I can update the srm branch once this flows to that repo.

**Comment by veanes** [comment]
I'll wait for your update @danmoseley. I'm not familiar with the required git procedure.

**Review by pgovind — COMMENTED** [review]
I know this is in already, but this LGTM!

**Pull request merged**
