### PR TITLE
Remove distros versions calculation

### PR DESCRIPTION
**Pull request by am11**
Remove distro version calculation for non-portable builds. The user can specify the desired value via `--outputrid` option (which is already used by source-build).

### CODE REVIEW

**Comment by am11** [comment]
@tmds, @elinor-fung, I was thinking something along these lines. It entails additional work such as:

* Add `--outputrid` required argument in dotnet/dotnet's build.sh: https://github.com/dotnet/dotnet/compare/main...am11:dotnet:patch-2
* Sync https://github.com/dotnet/dotnet/blob/1550d92/Directory.Build.props#L50 with https://github.com/dotnet/runtime/blob/e8f163a4c56b88cec8288b7d739208dc5c98cafa/Directory.Build.props#L251
* Upstream eng/common changes to dotnet/arcade repo.
* Add a comment in corehost `normalize_linux_rid()` "Non-Portable RID is frozen since .NET 8; this code need to stay for backward compatibility." something to that effect.

This way, distro maintainers will be free to use their preferred convention without needing to maintain those details in dotnet infra.

**Comment by am11** [comment]
> For non-portable Linux build, I think we should keep the logic that determines a rid based on `/etc/os-release`. This calculates a sensible value in a consistent way. Maintainers that want something different can take control by specifying `--output-rid`

That will defeat its purpose. Previous discussion was to remove these cases https://github.com/dotnet/arcade/pull/14595#issuecomment-2003761334.

I think either we should make it consistently agnostic of distro info for all platforms, or keep maintaining it (and keep accepting `Add support for ___ linux` PRs). I am leaning towards former.

**Comment by tmds** [comment]
> That will defeat its purpose. Previous discussion was to remove these cases https://github.com/dotnet/arcade/pull/14595#issuecomment-2003761334.

With that comment I meant remove the special cases for specific Linux distros, like Oracle Linux.

I don't think we should force every distro maintainer to "choose" a rid and specify it using `--output-rid` when the script can calculate a sensible value to use.

**Comment by am11** [comment]
> With that comment I meant: remove the special cases for specific Linux distros, like Oracle Linux.

Alright, you mean by using the same default for all distros: `${ID}.${VERSION}` (and `${ID}` when VERSION is empty), correct?

> --output-rid

You named it `--outputrid` https://github.com/dotnet/runtime/commit/58c3d52399bdddf0a7a7d6527f4df474141aef7d 😉

**Comment by tmds** [comment]
cc @dotnet/distro-maintainers

**Comment by am11** [comment]
@omajid, in case it wasn't obvious, this is a dead code from VMR's perspective (TargetRid in dotnet/dotnet repo is always set which maps to --outputrid in this repo). Since .NET 8, runtime repo is pretty much agnostic of nonportable RIDs. This PR is a followup cleanup to avoid future "Add support for ___ linux" type of PRs.

**Comment by am11** [comment]
@omajid, in case it wasn't obvious, this is dead code from VMR's perspective (TargetRid in dotnet/dotnet repo is always set which maps to --outputrid in this repo). Since .NET 8, runtime repo is pretty much agnostic of nonportable RIDs. This PR is a followup cleanup to avoid future "Add support for ___ linux" type of PRs.

**Review by jkoritzinsky — APPROVED** [review]

**Review by elinor-fung — APPROVED** [review]

**Review by clamp03 — APPROVED** [review]
Thank you.

**Comment by mthalman** [comment]
> * Add `--outputrid` required argument in dotnet/dotnet's build.sh: [dotnet/dotnet@main...am11:dotnet:patch-2](https://github.com/dotnet/dotnet/compare/main...am11:dotnet:patch-2)

@am11 - It doesn't look like this has been applied yet. This should be applied to https://github.com/dotnet/sdk/blob/main/src/SourceBuild/content/build.sh. Note that this change has surfaced an issue in how we reference the produced output from the build. So once it's exposed as a build script parameter, we'd need to flow the desired RID into that from the build pipeline. I think this would only need to be done for Alpine as its version changes with each revision.

**Pull request merged**
