### PR TITLE
update the package index to have the latest stable package for harvesting

### PR DESCRIPTION
**Pull request by Anipik**
Fixes the build failure in https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/985165/logs/1333

### CODE REVIEW

**Comment by safern** [comment]
@elinor-fung also opened: https://github.com/dotnet/runtime/pull/48074

**Comment by Anipik** [comment]
thanks i will close this one

**Comment by safern** [comment]
Merging since Libraries All Configurations build is green and already running tests, to unblock other PRs.

**Review by safern — APPROVED** [review]

**Review by ViktorHofer — COMMENTED** [review]
LGTM

**Pull request merged**
