### PR TITLE
Windows executables: only load imported DLLs from System32

### PR DESCRIPTION
**Pull request by AustinWise**
By using the [/DEPENDENTLOADFLAG](https://learn.microsoft.com/en-us/cpp/build/reference/dependentloadflag) `link.exe` flag, we can tell the Windows loader to only look for referenced DLLs in the System32 directory. This prevents [DLL injection](https://en.wikipedia.org/wiki/DLL_injection).

While this would not have prevented this month's CVE (see #84637), it could prevent DLL injection bugs from being introduced in native code.

### Questions

Is there a better way to apply this flag in the CMake files? Ideally it would be the default and tests that don't work with it would opt out.

When I added this flag, I got this error message from `LINK.exe`:

```
LINK : fatal error LNK1268: inconsistent option 'DEPENDENTLOADFLAG:0x800' specified with /USEPROFILE but not with /GENPROFILE
```

How can this be worked around? Currently I have commented out applying PGO to make the build pass.

### CODE REVIEW

**Comment by AustinWise** [comment]
Leaving this as draft for now to see if it breaks anything.

**Comment by jkotas** [comment]
> /DEPENDENTLOADFLAG

The docs say that this flag is effective on newer Windows 10 RS1+ only. It does not hurt to add it, but I do not think we can depend on it as long as we support Windows Server 2012: https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#windows. I would expect the tests to fail on Windows Server 2012.

**Comment by AustinWise** [comment]
I finally got a chance to look at the failures. It appears that some tests (like for IJW) are impacted by this change. I think I will rework this to only target the main product DLLs and EXEs, like `coreclr.dll` and `dotnet.exe`.

> > /DEPENDENTLOADFLAG
> 
> The docs say that this flag is effective on newer Windows 10 RS1+ only. It does not hurt to add it, but I do not think we can depend on it as long as we support Windows Server 2012: https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#windows. I would expect the tests to fail on Windows Server 2012.

Opps, I did not check the minimum server version of Windows. In that case I will revert the changes to delay loading version.dll and let this be a defense-in-depth change before I mark this ready for review.

**Comment by AustinWise** [comment]
I removed the test because it was pretty hacky. I think the ideal test would enumerate all loaded modules and make sure this flag is set in non-operating-systems module. I'm not 100% sure on how to write such a test.

In the absence of test, I manually verified that the follow executable have the dependent load flag using `LINK.EXE /DUMP /HEADERS /LOADCONFIG file.dll`:

 * coreclr.dll
 * apphost.exe
 * dotnet.exe
 * singlefilehost.exe
 * comhost.dll
 * hostfxr.dll
 * hostpolicy.dll
 * ijwhost.dll
 * nethost.dll

 Which I think covers the main product executable.

**Comment by AustinWise** [comment]
I wrote a program to check for files missing this flag:

https://github.com/AustinWise/CheckDependentLoadFlags

I'm satisfied that I've covered the main product DLLs, so I will open this for review.

**Comment by elinor-fung** [comment]
cc @blowdart @GrabYourPitchforks

**Comment by AustinWise** [comment]
I identified some further revision I'd like to do, so I'm marking this as draft again. Sorry for the churn.

**Pull request closed without merging**
