### PR TITLE
[mono][wasm] Store the exception object in a GC handle while it is be…

### PR DESCRIPTION
**Pull request by vargaz**
…ing thrown.

### CODE REVIEW

**Comment by vargaz** [comment]
Might fix 
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-f475aecec619441682/normal-System.Collections.Tests/1/console.913e6508.log?sv=2019-07-07&se=2022-04-09T21%3A55%3A44Z&sr=c&sp=rl&sig=yWLYpMnSv0T%2FrPoE1PH0nKCB6L8k4eXixnQgvbuQ7AM%3D

**Review by lambdageek — COMMENTED** [review]
Do you also need to change `mono_resume_unwind` ?  It's the only other place that I see that's using `resume_state.ex_obj`.  Or is it accessed from LLVM code somewhere?

https://github.com/dotnet/runtime/blob/aea7c73b6be57845df53880cf95b3f7fa58e477c/src/mono/mono/mini/mini-exceptions.c#L3119

**Comment by vargaz** [comment]
Thats the 'normal' llvm case, this only changes the llvmonly case.

**Review by lambdageek — APPROVED** [review]

**Pull request merged**
