### PR TITLE
Robustify a name resolution test

### PR DESCRIPTION
**Pull request by danmoseley**
These tests get all IP addresses configured for the local machine and arbitrarily try to resolve the first one to a name. On my machine at least, not all these addresses are resolvable. By the comments, it seems this is a configuration issue on some Unix machines as well. Changed the tests to verify that at least one of the addresses are resolved.

On this machine I still have failures in tests that try to resolve ipv6 addresses. This is because [GetNameInfoW here](https://github.com/danmoseley/runtime/blob/bd3c9aa442b2ebda6dad164be0be9157c62121ba/src/libraries/System.Net.NameResolution/src/System/Net/NameResolutionPal.Windows.cs#L98) is returning HostNotFound for `::1` or similar addresses. `ping ::1` and `tracert ::1` work fine, so ipv6 is enabled in some sense. There is no relevant entry in `hosts`. @wfurt any idea why this might be happening? If there was an independent way to verify that a machine is in this configuration, I could use that to make the test skip for such machines.

### CODE REVIEW

**Comment by wfurt** [comment]
I don't know @danmoseley  but I know who to ask. Can you share more info about your setup - OS & configuration. (either here os shoot me private message)

**Comment by danmoseley** [comment]
@wfurt meantime, should we merge this one? It seems from the Unix comments that it's a valid potential configuration for localhost to be mapped to a set of addresses, not all of which can be mapped back. We have the other tests (that we're investigating) to ensure that localhost, 127.0.0.1, ::1 etc can all be mapped (which surely should always happen)

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by danmoseley** [comment]
failure already linked.

**Comment by danmoseley** [comment]
Curiously the name resolution tests mentioned above all seem to pass now. It looks like some update was pushed to the VPN configuration.

Summarizing what we learned: the name resolution tests failed for "::1" and equivalent due to GetNameInfoW returning host not found. DNS team found this was due to a NRPT policy applied to the machine for "ip6.arpa". This could be seen with `get-dnsclientnrptpolicy` (or possibly it was `get-dnsclientnrptrule`). This appeared to be applied as part of setting up the Microsoft employee VPN.

I was going to set the tests to skip if this key existed: `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DnsPolicyConfig\<varies>@Name= .ip6.arpa`. But mysteriously the policy seems to be gone now and indeed they're passing.

**Pull request merged**
