### PR TITLE
Refactor ProcessStartInfoTests to use WindowsTestAccount

### PR DESCRIPTION
**Pull request by hangy**
As discussed in #77637, simplifies the test code by using the reusable `WindowsTestAccount` class.

### CODE REVIEW

**Comment by adamsitnik** [comment]
@ViktorHofer @carlossanlop the CI legs failed with:

> error : (NETCORE_ENGINEERING_TELEMETRY=Build) A call to an Azure DevOps api returned 401, which may indicate a bad 'System.AccessToken' value.

Is it a known issue?

**Comment by ViktorHofer** [comment]
> @ViktorHofer @carlossanlop the CI legs failed with:
error : (NETCORE_ENGINEERING_TELEMETRY=Build) A call to an Azure DevOps api returned 401, which may indicate a bad 'System.AccessToken' value.
Is it a known issue?

cc @dotnet/dnceng

**Comment by MilenaHristova** [comment]
> 

Looks like we have seen the issue before. Instructions from @ilyas1974 to resolve it:

Navigate to Pipeline
Click in “Edit”   
Select the “Triggers” tab/menu item     
    If yaml based Pipeline, select the vertical ellipses in upper right corner next to “Run”    
Under “Pull request validation” select the Repo
Check the "Make secrets available to builds of forks" checkbox.
Check the “Make fork builds have the same permissions as regular builds”

**Comment by MilenaHristova** [comment]
> > @ViktorHofer @carlossanlop the CI legs failed with:
> > error : (NETCORE_ENGINEERING_TELEMETRY=Build) A call to an Azure DevOps api returned 401, which may indicate a bad 'System.AccessToken' value.
> > Is it a known issue?
> 
> cc @dotnet/dnceng

we're working on it

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @hangy !

**Comment by hangy** [comment]
> LGTM, thank you @hangy !

Thanks for the suggestion and review. 🙂

**Pull request merged**
