### PR TITLE
Restrict parallelism in LLVM FullAOT compile, to prevent OOM

### LINKED ISSUE #60234: Error in CI `Mono llvmfullaot Pri0 Runtime Tests Run Linux arm64 release`
in `LLVM AOT cross-compile CoreCLR tests`

Error message:
`##[error]Exit code 137 returned from process: file name '/usr/bin/docker', arguments 'exec -i -u 1000  -w /home/cloudtest_azpcontainer 12e65458950cdcacb35a892c9bd140157953823f62a984dfc4c13e1632863c42 /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.`

https://dev.azure.com/dnceng/public/_build/results?buildId=1411090&view=logs&j=b40c4ee0-d59d-50cb-cee3-6c499edc769b&t=24038e5f-e5d5-5f4a-9cc0-31eac914e6d6

Is this a real error or infrastructure/random? Is it known? What is the actual problem?

@dotnet/runtime-infrastructure
<!-- runfo report start -->
Runfo Tracking Issue: [LLVM AOT build gets killed under docker](https://runfo.azurewebsites.net/tracking/issue/193)
|Definition|Build|Kind|Job Name|
|---|---|---|---|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1569424](https://dev.azure.com/dnceng/public/_build/results?buildId=1569424)|[PR 63800](https://github.com/dotnet/runtime/pull/63800)|Mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1553349](https://dev.azure.com/dnceng/public/_build/results?buildId=1553349)|[PR 63800](https://github.com/dotnet/runtime/pull/63800)|Mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|
|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[1551116](https://dev.azure.com/dnceng/public/_build/results?buildId=1551116)|[PR 63689](https://github.com/dotnet/runtime/pull/63689)|Mono llvmfullaot Pri0 Runtime Tests Run  Linux arm64 release|



Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|1|1|3|

<!-- runfo report end -->

### PR DESCRIPTION
**Pull request by directhex**
Limit msbuild parallelism whilst building LLVM FullAOT to 3

The largest tests - mostly the Microsoft.CodeAnalyis tests - require about 5GB RAM during the build. If we don't limit the number of concurrent builds, the AzDO agent will OOM.

Ref: https://github.com/dotnet/core-eng/issues/14964
Closes: https://github.com/dotnet/runtime/issues/60234

### CODE REVIEW

**Comment by directhex** [comment]
The fix works, but we have actual test failures:

```
    JIT/SIMD/VectorExp_ro/VectorExp_ro.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.SIMD/VectorExp_ro/VectorExp_ro.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false VectorExp_ro.dll ''
      Failed Int64
        sum: [ 1, 25 ]
      Expected: 100
      Actual: 255
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/JIT/SIMD/VectorExp_ro/VectorExp_ro.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_SIMD._VectorExp_ro_VectorExp_ro_._VectorExp_ro_VectorExp_ro_sh()
      Output:
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.SIMD/VectorExp_ro/VectorExp_ro.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false VectorExp_ro.dll ''
        Failed Int64
          sum: [ 1, 25 ]
        Expected: 100
        Actual: 255
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/JIT/SIMD/VectorExp_ro/VectorExp_ro.sh
    JIT/HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Yield_r.dll ''
      Expected: 100
      Actual: 0
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/JIT/HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_HardwareIntrinsics._Arm_ArmBase_Yield_r_Yield_r_._Arm_ArmBase_Yield_r_Yield_r_sh()
      Output:
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Yield_r.dll ''
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/JIT/HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.sh
    JIT/HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Yield_ro.dll ''
      Expected: 100
      Actual: 0
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/JIT/HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_HardwareIntrinsics._Arm_ArmBase_Yield_ro_Yield_ro_._Arm_ArmBase_Yield_ro_Yield_ro_sh()
      Output:
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Yield_ro.dll ''
        Expected: 100
        Actual: 0
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/JIT/HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.sh
```

**Comment by imhameed** [comment]
I'll take a look at the test failures. I'm concerned about how long compilation takes with this little parallelism though: 1h30m is not fast!

**Comment by directhex** [comment]
@imhameed it's actually great - I've only added the `-maxcpucount:3` to the arm64 run (which took 1h30), and not touched the x64 run (which took 1h25) - I think 5 minutes is a pretty small penalty.

On our standard build VM, the parallel limit is 4, so we're not really losing much here.

**Comment by imhameed** [comment]
Ah ok; that's not bad at all relative to the baseline.

**Review by imhameed — APPROVED** [review]

**Comment by SamMonoRT** [comment]
> The fix works, but we have actual test failures:
> 
> ```
>     JIT/SIMD/VectorExp_ro/VectorExp_ro.sh [FAIL]
>       
>       Return code:      1
>       Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.SIMD/VectorExp_ro/VectorExp_ro.output.txt
>       Raw output:
>       BEGIN EXECUTION
>       /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false VectorExp_ro.dll ''
>       Failed Int64
>         sum: [ 1, 25 ]
>       Expected: 100
>       Actual: 255
>       END EXECUTION - FAILED
>       Test Harness Exitcode is : 1
>       To run the test:
>       > set CORE_ROOT=/root/helix/work/correlation
>       > /root/helix/work/workitem/e/JIT/SIMD/VectorExp_ro/VectorExp_ro.sh
>       Expected: True
>       Actual:   False
>       Stack Trace:
>            at JIT_SIMD._VectorExp_ro_VectorExp_ro_._VectorExp_ro_VectorExp_ro_sh()
>       Output:
>         
>         Return code:      1
>         Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.SIMD/VectorExp_ro/VectorExp_ro.output.txt
>         Raw output:
>         BEGIN EXECUTION
>         /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false VectorExp_ro.dll ''
>         Failed Int64
>           sum: [ 1, 25 ]
>         Expected: 100
>         Actual: 255
>         END EXECUTION - FAILED
>         Test Harness Exitcode is : 1
>         To run the test:
>         > set CORE_ROOT=/root/helix/work/correlation
>         > /root/helix/work/workitem/e/JIT/SIMD/VectorExp_ro/VectorExp_ro.sh
>     JIT/HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.sh [FAIL]
>       
>       Return code:      1
>       Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.output.txt
>       Raw output:
>       BEGIN EXECUTION
>       /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Yield_r.dll ''
>       Expected: 100
>       Actual: 0
>       END EXECUTION - FAILED
>       Test Harness Exitcode is : 1
>       To run the test:
>       > set CORE_ROOT=/root/helix/work/correlation
>       > /root/helix/work/workitem/e/JIT/HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.sh
>       Expected: True
>       Actual:   False
>       Stack Trace:
>            at JIT_HardwareIntrinsics._Arm_ArmBase_Yield_r_Yield_r_._Arm_ArmBase_Yield_r_Yield_r_sh()
>       Output:
>         
>         Return code:      1
>         Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.output.txt
>         Raw output:
>         BEGIN EXECUTION
>         /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Yield_r.dll ''
>         Expected: 100
>         Actual: 0
>         END EXECUTION - FAILED
>         Test Harness Exitcode is : 1
>         To run the test:
>         > set CORE_ROOT=/root/helix/work/correlation
>         > /root/helix/work/workitem/e/JIT/HardwareIntrinsics/Arm/ArmBase/Yield_r/Yield_r.sh
>     JIT/HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.sh [FAIL]
>       
>       Return code:      1
>       Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.output.txt
>       Raw output:
>       BEGIN EXECUTION
>       /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Yield_ro.dll ''
>       Expected: 100
>       Actual: 0
>       END EXECUTION - FAILED
>       Test Harness Exitcode is : 1
>       To run the test:
>       > set CORE_ROOT=/root/helix/work/correlation
>       > /root/helix/work/workitem/e/JIT/HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.sh
>       Expected: True
>       Actual:   False
>       Stack Trace:
>            at JIT_HardwareIntrinsics._Arm_ArmBase_Yield_ro_Yield_ro_._Arm_ArmBase_Yield_ro_Yield_ro_sh()
>       Output:
>         
>         Return code:      1
>         Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.output.txt
>         Raw output:
>         BEGIN EXECUTION
>         /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Yield_ro.dll ''
>         Expected: 100
>         Actual: 0
>         END EXECUTION - FAILED
>         Test Harness Exitcode is : 1
>         To run the test:
>         > set CORE_ROOT=/root/helix/work/correlation
>         > /root/helix/work/workitem/e/JIT/HardwareIntrinsics/Arm/ArmBase/Yield_ro/Yield_ro.sh
> ```

are these the only test failures, or just a subset. If these are the only ones, I suggest we add to issues.target file and get this merged to restart coverage again @imhameed  ?

**Comment by imhameed** [comment]
I just noticed that the most recent llvmfullaot arm64 test run for this PR failed, presumably due to OOM: https://dev.azure.com/dnceng/public/_build/results?buildId=1553349&view=logs&jobId=f706423a-fbdb-5b56-756a-071599d59ff7&j=f706423a-fbdb-5b56-756a-071599d59ff7&t=ab4712e5-669b-581b-1bf6-f1c35ac0966b

I've submitted a PR to disable the two failing tests. It is here: https://github.com/dotnet/runtime/pull/64180

We're generating bad LLVM IR for VectorExp_ro; I'm surprised that nothing else has broken yet. I should have a fix for this soon.

**Review by steveisok — APPROVED** [review]

**Pull request merged**
