### PR TITLE
Refactor optimizing morph for commutative operations

### PR DESCRIPTION
**Pull request by SingleAccretion**
I have noticed that there is some low-hanging fruit in these optimizations (plus I will need to add a new optimization here for the purposes of #11057), this change refactors the code in preparation for that.

Included:
- Splitting things into `fgOptimize*` functions.
- Removal of redundant conditions.
- Fixing the type of the constant node created for the "mulshift" optimization.
- Tightening of comments.

We're expecting two diffs:
- Better comma throw propagation (the new code does not exit early from `fgMorphSmpOp` in all cases the old code did).
- A CSE change due to a different VN for the fixed constant node.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Review by EgorBo — APPROVED** [review]
👍

**Review by BruceForstall — APPROVED** [review]
LGTM. Nice cleanup.

**Comment by BruceForstall** [comment]
Linux arm64 failure is:
```
createdump: /__w/1/s/src/coreclr/pal/src/libunwind/src/dwarf/Gfind_proc_info-lsb.c:929: int _Uaarch64_dwarf_search_unwind_table(unw_addr_space_t, unw_word_t, unw_dyn_info_t *, unw_proc_info_t *, int, void *): Assertion `ip >= di->start_ip && ip < di->end_ip' failed.
```
but that's not unique to this run.

net7.0-OSX-Debug-x64-CoreCLR_checked-OSX.1014.Amd64.Open failure is out of disk space.

**Pull request merged**
