### PR TITLE
Clarify System.Diagnostics.Process' README

### PR DESCRIPTION
**Pull request by jozkee**
It should say that you shall not install a NuGet package if your TFM is Netstandard2.0 compatible.

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Review by teo-tsirpanis — APPROVED** [review]
You didn't link to the NuGet package but who cares? 😅

**Comment by Jozkee** [comment]
> You didn't link to the NuGet package

That's also the case on https://github.com/dotnet/runtime/tree/main/src/libraries/System.Reflection.Primitives#deployment. Since this is already merged, let's see how it works.

**Comment by ViktorHofer** [comment]
IMO we shouldn't link to the NuGet package as it's not recommended to be used at all anymore.

**Comment by teo-tsirpanis** [comment]
> we shouldn't link to the NuGet package

I agree, just mentioned it for consistency with the others and because the README mentions a "package".

**Pull request merged**
