### PR TITLE
[DO NOT MERGE] Evaluating some MacOS build size

### PR DESCRIPTION
**Pull request by MattGal**
Related to https://github.com/dotnet/core-eng/issues/9448.  See @ilyas1974 for more details.

### CODE REVIEW

**Comment by dougbu** [comment]
Why not merge this to let everyone keep an eye on disk usage?

**Comment by MattGal** [comment]
> Why not merge this to let everyone keep an eye on disk usage?

We could merge part of it, but not the part that makes it use pool DotNetCore-Mac as that only has one machine.

**Comment by dougbu** [comment]
> We could merge part of it

Sounds like goodness (though I rarely build this repo)

**Comment by safern** [comment]
It seems like we sort this out by adding it to the runtime-live build. Will close this, @MattGal please re-open if needed.

**Pull request closed without merging**
