### PR TITLE
[wasm] Fix perf pipeline runs

### PR DESCRIPTION
**Pull request by radical**
- Update to use `tfm=net9.0`

- Add `Microsoft.NETCore.App.Ref` nuget to helix payload to fix `/home/helixbot/work/AEA10974/p/performance/src/scenarios/blazor/app/emptyblazorwasmtemplate.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 9.0.0-ci)`
- Run only a few benchmarks on `runtime-wasm-perf` as it is just a sanity check run. And running a full partition can take more than 30mins.

Corresponding PR - https://github.com/dotnet/performance/pull/3428

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Comment by radical** [comment]
wip: aot run didn't aot for some reason!

**Comment by radical** [comment]
This is blocked on https://github.com/dotnet/BenchmarkDotNet/pull/2447, and https://github.com/dotnet/performance/pull/3428 .

**Comment by radical** [comment]
> wip: aot run didn't aot for some reason!

This was because wasm/net9.0 didn't have some handling in `dotnet/performance`, and `dotnet//BenchmarkDotnet` but failed silently, falling back to coreclr.

**Comment by radical** [comment]
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2295935

**Comment by radical** [comment]
Merging to fix CI.

**Pull request merged**
