### PR TITLE
Rename mentions of corefx-testdata to runtime-assets

### PR DESCRIPTION
**Pull request by ViktorHofer**
We renamed the dotnet/corefx-testdata repository to dotnet/data.
This PR updates all mentions of the old repositories' name.

### CODE REVIEW

**Comment by jkotas** [comment]
https://github.com/dotnet/data is very generic looking name. Should it be rather called  https://github.com/dotnet/runtime-testdata ?

Also, the description of https://github.com/dotnet/data still references corefx.

**Comment by ViktorHofer** [comment]
We discussed this offline and I believe we need a repository to store big blobs not just for testdata for other usages as well going forward. Mono has one use-case with Unicode data. I hope we can move some of the bigger blobs from Mono to the data repository before we consolidate.

**Comment by ViktorHofer** [comment]
> Also, the description of https://github.com/dotnet/data still references corefx.

Thanks, updated.

> https://github.com/dotnet/data is very generic looking name.

I'm happy for other naming suggestions.

**Comment by jkotas** [comment]
> we need a repository to store big blobs not just for testdata for other usages as well going forward. 

We can call it `runtime-data` if we do not like test in the name.

There are many repositories under dotnet. wpf, winforms, orleans .... and more are likely comming in future. Do we want dotnet/data to be a dumping ground for large data files for all of these as the current description suggests?

**Review by davidsh — APPROVED** [review]

**Comment by ViktorHofer** [comment]
> Do we want dotnet/data to be a dumping ground for large data files for all of these as the current description suggests?

Yes, that's the plan. We evaluated Git LFS for the runtime repo and it was just far too costly (5$ / 500MB bandwith, including forks). I think we should open this repository for all _our_ repositories. As it just pushed to the well established feeds, the protocol is already established. If I have enough time I will enable CI/CD in that repository so that we can take a direct dependency on it via the dependency flow.

**Comment by ViktorHofer** [comment]
I agree with you that "data" might not be the best choice.

**Comment by jkotas** [comment]
> > Do we want dotnet/data to be a dumping ground for large data files for all of these as the current description suggests?

> Yes, that's the plan.

Do we know about any non-runtime team that would actually want to store the large data files in this repository?

My primary concern is ownership and branching/synchronization with release cycles.

**Comment by davidsh** [comment]
>This PR updates all mentions of the old repositories' name.

FWIW, System.Net is planning on removing its use of the 'data' repository for our tests. Instead of relying on PFX files, for example, we plan to generate the certs on the fly since we have .NET API support for that now.

**Comment by ViktorHofer** [comment]
> Do we know about any non-runtime team that would actually want to store the large data files in this repository?

I don't. cc @jaredpar @Pilchie @mmitche @markwilkie 

> My primary concern is ownership and branching/synchronization with release cycles.

That's something that we definitely need to solve. We currently push to a very generic feed which isn't versioned to a specific release. We want to get rid of those feeds: https://github.com/dotnet/runtime/issues/199

**Comment by ViktorHofer** [comment]
cc @danmosemsft

**Comment by danmosemsft** [comment]
I think `dotnet/runtime-data` or `dotnet/runtime-test-data` would be better names. I think to repo-squat something as broad as `dotnet/data` it might be necessary to seek larger consensus than ourselves.

**Comment by stephentoub** [comment]
Agreed; it shouldn't be dotnet/data. runtime-supportfiles, runtime-assets, whatever, but not something as general as data.

**Comment by ViktorHofer** [comment]
Sounds good. I'll rename the repo to dotnet/runtime-assets then.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
