### PR TITLE
Strip the ILLinkTrim.xml file from System.Private.Xml

### LINKED ISSUE #30912: Address SqlXml to CreateSqlReader dependency for assembly size
System.Data.Common.dll contains the SqlXml type.  This type uses reflection to access the internal CreateSqlReader method in System.Private.Xml.dll:
https://github.com/dotnet/corefx/blob/5bc2806f33090e78b38fafe4d5b46d5a0a4c1f08/src/System.Data.Common/src/System/Data/SQLTypes/SqlXml.cs#L134
To ensure that this internal method (which has no other consumers) isn't trimmed away, System.Private.Xml lists this method in its ILLinkTrim.xml file:
https://github.com/dotnet/corefx/blob/5bc2806f33090e78b38fafe4d5b46d5a0a4c1f08/src/System.Private.Xml/src/ILLinkTrim.xml#L3-L6
which means that even if SqlXml isn't used by an app, this method and everything it depends on can't be trimmed away.  That ends up keeping alive ~300KB of code that's likely otherwise unused.  We should address this somehow, e.g. https://github.com/dotnet/corefx/issues/41201 (though this is a case of the cross-assembly private reflection mentioned there).

### PR DESCRIPTION
**Pull request by eerhardt**
The two methods being preserved in System.Private.Xml (CreateSqlReader and GenerateSerializer) are large, and are not necessary when linking a mobile app. These methods only need to be preserved when linking the shared framework. When a normal app is linked, the linker is able to figure out if the two methods are necessary.

Contributes to #35199

Fixes #30912

### CODE REVIEW

**Comment by stephentoub** [comment]
> When a normal app is linked, the linker is able to figure out if the two methods are necessary.

Is https://github.com/dotnet/runtime/issues/30912 stressed then as well? The linker recognizes the pattern used in https://github.com/dotnet/runtime/blob/e1ffadd6521b29db350e701b11d78a286ecd783a/src/libraries/System.Data.Common/src/System/Data/SQLTypes/SqlXml.cs#L134 ? Should we add PreserveDependency anyway, to make it explicit?

**Review by stephentoub — APPROVED** [review]

**Review by krwq — APPROVED** [review]

**Comment by eerhardt** [comment]
> Is #30912 addressed then as well? The linker recognizes the pattern used in https://github.com/dotnet/runtime/blob/e1ffadd6521b29db350e701b11d78a286ecd783a/src/libraries/System.Data.Common/src/System/Data/SQLTypes/SqlXml.cs#L134 ?

Yes, I tested it on a standalone application:

```C#
        static void Main(string[] args)
        {
            SqlXml x = new SqlXml();
            XmlReader r = x.CreateReader();
            Console.WriteLine(x);
        }
```

And told the linker `--ignore-descriptors true` (which ignores the ILLinkTrim.xml file during the app build), and it still preserved the internal `XmlReader.CreateSqlReader` method.

>  Should we add PreserveDependency anyway, to make it explicit?

I think that is a good idea. I like being explicit so we don't have any surprises in case the linker changes behavior or has a bug.

A problem to be solved here is how we test this so we can catch regressions. We don't really have the capability of linking test applications today. Maybe once Xamarin apps are fully plumbed into our builds, we could make a Xamarin app that does similar to the above, and we run it to ensure it behaves correctly?

**Comment by eerhardt** [comment]
Just a note for the size difference this change makes on the `WorldCities` Xamarin app:

Here's the linked app without the change:

image

And here's the linked app with this change:

image

**Review by marek-safar — APPROVED** [review]
Perhaps instead of hard to notice flag in csproj we could call the XML file differently for this mode and use that to control the logic. We also need to be careful not to ever build this library twice.

**Comment by eerhardt** [comment]
> Perhaps instead of hard to notice flag in csproj we could call the XML file differently for this mode and use that to control the logic.

This is a good idea. I've implemented it. I went back and forth on some different names:
- ILLinkTrim_NonEmbedded.xml
- ILLinkTrim_Stripped.xml
- ILLinkTrim_SharedFrameworkOnly.xml

but settled on `ILLinkTrim_LibraryBuild.xml`. Let me know what you think. I can definitely change the file name if a better name is chosen.

**Comment by marek-safar** [comment]
> Let me know what you think. I can definitely change the file name if a better name is chosen.

This looks good! About the name, I'd personally go with `ILLink.Descriptors.Build.xml` but I'm fine with what you like.

**Pull request merged**
