### PR TITLE
Reduce contention in pipelines

### PR DESCRIPTION
**Pull request by benaadams**
Drops the lock for common path through the highlighted code paths:

image

Need to add some comments still

### CODE REVIEW

**Comment by benaadams** [comment]
[System.IO.Pipelines.zip](https://github.com/dotnet/runtime/files/4672720/System.IO.Pipelines.zip)

/cc @adamsitnik

**Comment by benaadams** [comment]
[System.IO.Pipelines.zip](https://github.com/dotnet/runtime/files/4672890/System.IO.Pipelines.zip)

**Comment by benaadams** [comment]
[System.IO.Pipelines.zip](https://github.com/dotnet/runtime/files/4672985/System.IO.Pipelines.zip)

/cc @adamsitnik

**Comment by benaadams** [comment]
Can do something simplier to test

**Comment by adamsitnik** [comment]
@benaadams I've kicked off the benchmarks yesterday before you have closed this PR. Here they are:

obraz

**Comment by benaadams** [comment]
Thank you @adamsitnik

**Pull request closed without merging**
