### PR TITLE
delete a failing test project.

### PR DESCRIPTION
**Pull request by sandreenko**

### CODE REVIEW

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by sandreenko** [comment]
Thanks @kunalspathak , the test build passed (see https://dev.azure.com/dnceng/public/_build/results?buildId=734924&view=logs&j=db768a9e-3325-5ce3-2d52-896c40bee68a), so I am merging this.

**Comment by jashook** [comment]
I think next time an easier fix is to add the `<DisableProjectBuild>true</DisableProjectBuild>` with the issue #.

:)

**Comment by jashook** [comment]
Thank you for getting outerloop building again!

**Comment by sandreenko** [comment]
> I think next time an easier fix is to add the <DisableProjectBuild>true</DisableProjectBuild> with the issue #.

Thank you, I was trying to find that command yesterday, but did not succeed.

**Comment by BruceForstall** [comment]
> I think next time an easier fix is to add the <DisableProjectBuild>true</DisableProjectBuild> with the issue #.

Is there a document that describes all the different ways to disable tests and when to use them? E.g., GCStressIncompatible, DisableProjectBuild, JitOptimizationSensitive, issues.targets, the libraries attributes like SkipOnCoreClr, ActiveIssue, etc.? I don't think so, and it would be very useful to have such a thing.

**Comment by danmosemsft** [comment]
@BruceForstall there is https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/filtering-tests.md#L8. Would be good to extend but it is for libraries though.

**Comment by BruceForstall** [comment]
@danmosemsft That's a useful link, but even that doesn't describe the `SkipOnCoreClr` attribute used in libraries tests.

**Comment by danmosemsft** [comment]
@safern probably knows these attributes better than most, and could maybe add them there.

**Comment by safern** [comment]
> @safern probably knows these attributes better than most, and could maybe add them there.

Sure... added to my TODO 😄

**Pull request merged**
