### PR TITLE
Enable build + pack of cross-OS diagnostic artifacts on Linux-musl-arm

### PR DESCRIPTION
**Pull request by hoyosjs**

### CODE REVIEW

**Comment by hoyosjs** [comment]
cc: @dotnet/dotnet-diag

**Comment by hoyosjs** [comment]
Internal validation for the packages: https://dev.azure.com/dnceng/internal/_build/results?buildId=810244

**Review by sdmaclea — APPROVED** [review]
LGTM Thanks @hoyosjs

**Review by safern — APPROVED** [review]
Thanks!

**Comment by hoyosjs** [comment]
The assets look correct in the internal build. This should unblock the rolling builds.

**Comment by janvorli** [comment]
@hoyosjs should we also add linux-musl-arm here?:
https://github.com/dotnet/runtime/blob/bcbb7d8f76f9370bc564feef06abd7bfb45e1f6b/src/coreclr/src/.nuget/Microsoft.CrossOsDiag.Private.CoreCLR/Microsoft.CrossOsDiag.Private.CoreCLR.proj#L16-L23

**Comment by safern** [comment]
@janvorli I think you already took care of that, right? 

https://github.com/dotnet/runtime/blob/bcbb7d8f76f9370bc564feef06abd7bfb45e1f6b/src/coreclr/src/.nuget/Microsoft.CrossOsDiag.Private.CoreCLR/Microsoft.CrossOsDiag.Private.CoreCLR.proj#L22

**Comment by janvorli** [comment]
@safern oops, I was looking at a different state of the repo and haven't realized that I've made this change myself before.

**Pull request merged**
