### PR TITLE
[wasm] Bump emscripten to 3.1.7

### PR DESCRIPTION
**Pull request by radekdoulik**

### CODE REVIEW

**Comment by radical** [comment]
To keep the PR progressing, I updated the exported functions list to `_malloc,_memalign,_memset,_htons,_ntohs`.

**Comment by radical** [comment]
The Wasm.Build.Tests failures are because the emscripten packages are still on 3.1.1 .
ref: Radek's PR for emsdk bump - https://github.com/dotnet/emsdk/pull/124

**Comment by radical** [comment]
the debugger test failure should be unrelated. It's racy, and I'll open a PR with a fix.

**Comment by lewing** [comment]
mono osx and linux failures appear to be https://github.com/dotnet/runtime/issues/60962

**Comment by lewing** [comment]
Failures are logged and unrelated.

**Review by lewing — APPROVED** [review]

**Review by radical — APPROVED** [review]

**Pull request merged**
