### PR TITLE
Fix SPMI handling of PGO schemas with class profiles

### PR DESCRIPTION
**Pull request by AndyAyersMS**
SPMI wasn't capturing enough data for PGO schemas that had class profiles,
leading to replay failures.

Also, add a bit of logging to the new likely class computation, so we can
tell in a jit dump when we're using a live histogram vs a crosssgen summary
of a histogram.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@davidwrighton PTAL
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Hmm, we may not be able to have `JITDUMP` inside `getLikelyClass`.

**Review by BruceForstall — APPROVED** [review]
LGTM

Does `repAllocPgoInstrumentationBySchema` need to be fixed? namely:
```
     // Add 16 bytes of represent writeable space
    size_t bufSize = maxOffset + 16;
```

As for `so cross-bitness replay may not work here` -- should the instrumentation data be serialized/deserialized to pointer-agnostic form, like everything else?

**Comment by AndyAyersMS** [comment]
> Does repAllocPgoInstrumentationBySchema need to be fixed

The jit currently never writes into the class profile table --only the runtime does -- so it's not absolutely required to be the right size here. But it might make sense to fix anyways.

> should the instrumentation data be serialized/deserialized to pointer-agnostic form, like everything else?

Probably so, yeah. I'll need to remind myself how we do that...

**Comment by BruceForstall** [comment]
You can look at spmirecordhelper.h for examples of how we deal with `CORINFO_SIGN_INFO` and `CORINFO_SIG_INST`, both quite complicated.

You can do something more expedient now and "more correct" later, if necessary.

**Comment by AndyAyersMS** [comment]
Ok, I will go ahead and merge this version since it will unbreak the most typical use case (64 bit replay of a 64 bit collection).

The arm64 leg passed but the CI hiccupped reporting success and eventually timed out.
```
   JIT.Stress.XUnitWrapper  Total: 5, Errors: 0, Failed: 0, Skipped: 0, Time: 41.035s
...
+ /home/helixbot/.azdo-env/bin/python -c import azure.devops
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'azure'
+ /home/helixbot/.azdo-env/bin/python -m pip install azure-devops==5.0.0b9
The directory '/home/helixbot/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/helixbot/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting azure-devops==5.0.0b9
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa6eedc88>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/azure-devops/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa6eedda0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/azure-devops/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa6eede80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/azure-devops/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa6eedfd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/azure-devops/

...
[EXECUTION TIMED OUT]
Exit Code:-3Executor timed out after 1800 seconds and was killed
['JIT.Stress' WORK ITEM LOG TRUNCATED: Command timed out, and was killed]
```

**Pull request merged**
