### PR TITLE
Mark Thread.ResetAbort as obsolete

### LINKED ISSUE #41925: Mark System.Threading.Thread ResetAbort as Obsolete
It was recognized in https://github.com/dotnet/runtime/pull/41892 that `System.Threading.Thread` `ResetAbort` throws `PlatformNotSupportedException` everywhere and should be marked as Obsolete.

### PR DESCRIPTION
**Pull request by Hona**
Closes #41925 

Uses the same diagnostic ID as per the issue discussion.

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
thank you!

**Review by GrabYourPitchforks — CHANGES_REQUESTED** [review]
Hi @TheRealHona, thanks for the PR! Please make two changes, and then we can merge it. First, please mark the _src_ code obsolete, same as the _ref_ code. Feel free to copy + paste the original obsoletion lines that are on the `Abort` class - I don't think we need to change the .resx text for this.

https://github.com/dotnet/runtime/blob/b147bbe7d0a5b9d6b71eb174c37a9986a84d5451/src/libraries/System.Private.CoreLib/src/System/Threading/Thread.cs#L180-L195

Second, please fix the compilation break in _ImageAnimator_. It should involve removing the 'catch' clause, leaving only the code within the original 'try' block remaining.

https://github.com/dotnet/runtime/blob/b147bbe7d0a5b9d6b71eb174c37a9986a84d5451/src/libraries/System.Drawing.Common/src/System/Drawing/ImageAnimator.Unix.cs#L180-L196

**Comment by danmosemsft** [comment]
Ah, thanks Levi. I didn't find the existing one in the src, because I was looking for SYSLIB not Obsoletions.ThreadAbortDiagId.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=42228) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=42228) before we can accept your contribution.<br/><br/>:x: TheRealHona [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=42228)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=42228) it.</sub>

**Comment by TheRealHona** [comment]
Should the entire try/catch block be removed?

**Comment by GrabYourPitchforks** [comment]
@TheRealHona Remove lines 182 - 183 and 192 - 196. That keeps the _while_ loop intact while removing the _try_ / _catch_ parts.

**Review by GrabYourPitchforks — APPROVED** [review]
Awesome, much appreciated! :)

**Comment by TheRealHona** [comment]
I will squash these commits when I get home, unless you will squash it all with the merge.

**Comment by GrabYourPitchforks** [comment]
> I will squash these commits when I get home, unless you will squash it all with the merge.

No need. It's easier for us to do it as part of merge. Force-pushing PRs makes reviewing them more difficult.

Thanks for offering, though!

**Comment by GrabYourPitchforks** [comment]
Failure is known issue https://github.com/dotnet/runtime/issues/41652.

**Pull request merged**
