### PR TITLE
[wasm] Add support for a random test case orderer, for xunit tests

### PR DESCRIPTION
**Pull request by radical**
This is enabled by default for wasm with `$(XUnitUseRandomizedTestOrderer)=true`.

When the library tests run, they print two messages like:

```
  info: Using random seed for test cases: 700149826
  info: Using random seed for collections: 700149826
  info: Starting:    System.Collections.Immutable.Tests.dll
```

These seeds are picked randomly every time the tests are run. To run the
tests with a specific seed, use environment variable
`XUNIT_RANDOM_ORDER_SEED`, which would run the tests in the exact same order.

When running tests, the environment variable is automatically passed to
the wasm app.

### CODE REVIEW

**Comment by radical** [comment]
I'm not sure where to add the documentation. Thoughts?

**Comment by vargaz** [comment]
Does this make the test order deterministic wrt to a specific seed ?

**Comment by radical** [comment]
Yep

**Review by vargaz — APPROVED** [review]

**Comment by radical** [comment]
Random test failure with v8/linux, but seems to be reliably reproducible with `XUNIT_RANDOM_ORDER_SEED=1883302047`:

```
[03:29:54] info: Starting:    System.Runtime.Numerics.Tests.dll
[03:29:58] fail: [FAIL] System.Numerics.Tests.cast_toTest.RunDoubleExplicitCastToBigIntegerTests
[03:29:58] info: Assert.Equal() Failure
[03:29:58] info:           ↓ (pos 0)
[03:29:58] info: Expected: -0
[03:29:58] info: Actual:   0
[03:29:58] info:           ↑ (pos 0)
[03:29:58] info:    at System.Numerics.Tests.cast_toTest.VerifyDoubleExplicitCastToBigInteger(Double value)
[03:29:58] info:    at System.Numerics.Tests.cast_toTest.RunDoubleExplicitCastToBigIntegerTests()
[03:29:58] info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
```

**Comment by radical** [comment]
[System.Runtime.Loader.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65628-merge-d2d09977c2a3474e86/normal-System.Runtime.Loader.Tests/1/console.a566875d.log?sv=2019-07-07&) fail randomly, but deterministically with `XUNIT_RANDOM_ORDER_SEED=2106784294`.

```
[06:25:43] fail: [FAIL] System.Runtime.Loader.Tests.SatelliteAssembliesTests.SatelliteLoadsCorrectly_FromName(alc: "Empty", assemblyName: "System.Runtime.Loader.Tests", culture: "en")
[06:25:43] info: Assert.Same() Failure
[06:25:43] info: Expected: "Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0
[06:25:43] info: Actual:   "Empty" System.Runtime.Loader.AssemblyLoadContext #4
[06:25:43] info:    at System.Runtime.Loader.Tests.SatelliteAssembliesTests.SatelliteLoadsCorrectly_FromName(String alc, String assemblyName, String culture)
[06:25:43] info:    at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)
```

Maybe these tests have some unintended dependence on order?

**Comment by radical** [comment]
I have disabled random ordering for these for now. But I haven't opened any issues, because I'm not entirely sure if it's a bug.

**Review by akoeplinger — APPROVED** [review]
LGTM, the random bugs you found look real, I'd file an issue for them and add a comment to the issue to the .csproj's

**Comment by radical** [comment]
The runtime tests failure is https://github.com/dotnet/runtime/issues/65681, which was hit on a rolling build too. I will try to use this randomizer for runtime tests in a follow up PR.

The debugger tests failure is https://github.com/dotnet/runtime/issues/64588 .

**Pull request merged**
