### PR TITLE
Cleanup EventSource

### PR DESCRIPTION
**Pull request by jkotas**
- Move StubEnvironment that is used to compile EventSource for older runtimes to the OOB package
- Change EventSource in CoreLib to call the right APIs directly without going through the portability glue
- Delete ES_BUILD_PCL and ES_BUILD_AGAINST_DOTNET_V35. No longer needed.

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]
LGTM. Would be nice to wait for @noahfalk review too as he more familiar with this area.

**Review by noahfalk — APPROVED** [review]
LGTM, thanks @jkotas : )

**Comment by noahfalk** [comment]
fyi @brianrob @dotnet/dotnet-diag

**Comment by eerhardt** [comment]
This fixes https://github.com/dotnet/runtime/issues/39412 as well.

**Comment by brianrob** [comment]
Thanks @noahfalk.  Seems reasonable, considering that we're no longer syncing with desktop sources.

**Pull request merged**
