### PR TITLE
[NativeAOT] Save full ARM64 SIMD arg registers in UniversalTransition

### PR DESCRIPTION
**Pull request by VSadov**
On arm64 entire SIMD registers (q0-q7) could be used for argument passing.

I am not sure if JIT uses HVA argument passing for NativeAOT, maybe it is disabled, but it looks like our save/restore of arguments in UniversalTransition frames could be incomplete.

### CODE REVIEW

**Comment by VSadov** [comment]
Re: PreStub in CoreClr.

It looks like PreStub on ARM64 stores full q registers

ThePreStub uses PROLOG_WITH_TRANSITION_BLOCK macro
```
NESTED_ENTRY ThePreStub

        PROLOG_WITH_TRANSITION_BLOCK
        ... 
```

PROLOG_WITH_TRANSITION_BLOCK uses SAVE_FLOAT_ARGUMENT_REGISTERS
```
        IF "$SaveFPArgs" != ""
__PWTB_SaveFPArgs SETL $SaveFPArgs
        ELSE
__PWTB_SaveFPArgs SETL {true}
        ENDIF

. . . 

        ; Spill argument registers.
        SAVE_ARGUMENT_REGISTERS        sp, __PWTB_ArgumentRegisters

        IF __PWTB_SaveFPArgs
        SAVE_FLOAT_ARGUMENT_REGISTERS  sp, __PWTB_FloatArgumentRegisters
        ENDIF

```

and SAVE_FLOAT_ARGUMENT_REGISTERS saves q registers

https://github.com/dotnet/runtime/blob/d365ff2e866ff2b9684262d139e79ba1c4641f76/src/coreclr/vm/arm64/asmmacros.h#L200

**Comment by VSadov** [comment]
Interestingly nativeaot has `SAVE_FLOAT_ARGUMENT_REGISTERS` defined on unix, but it could be dead code, I could not track it to its use.

https://github.com/dotnet/runtime/blob/536f34d9ab88e153aa11329e789afe6975fbe9a9/src/coreclr/nativeaot/Runtime/unix/unixasmmacrosarm64.inc#L182

**Comment by VSadov** [comment]
There is also use of `d0, d1` in   RhCallDescrWorker

https://github.com/dotnet/runtime/blob/b2dc37ba181a7fa4427e717eab819ba3543d0ae4/src/coreclr/nativeaot/Runtime/arm64/CallDescrWorker.asm#L114

it looks like this corresponds to CoreClr  CallDescrWorkerInternal , which has an additional conditional handling of HVA returns

https://github.com/dotnet/runtime/blob/4e61fb11116393b9babdb029412eb37274cddf73/src/coreclr/vm/arm64/CallDescrWorkerARM64.asm#L114

I do not know if these should match

**Comment by jkotas** [comment]
> I do not know if nativeaot and CoreClr should match here

RhCallDescrWorker is probably a dead code.

**Review by jkotas — APPROVED** [review]
I think this is candidate for release/7.0 backport. The arm64 calling convention is passing HFA in these registers.

**Comment by VSadov** [comment]
I will check once more on the nativeaot+unix version of SAVE_FLOAT_ARGUMENT_REGISTERS - to be sure it is unused.

**Comment by VSadov** [comment]
> I will check once more on the nativeaot+unix version of SAVE_FLOAT_ARGUMENT_REGISTERS - to be sure it is unused.

it is unused. I will just remove it to be less confusing, since it seems to be subtly incorrect.

**Comment by VSadov** [comment]
Tests are not starting. :-/

**Comment by VSadov** [comment]
Although the new commit just deletes code, I’d like to see it builds on everything.

**Comment by jkotas** [comment]
> Tests are not starting. :-/

Yes, it is a planned eng system downtime. Check your email.

**Comment by VSadov** [comment]
> Yes, it is a planned eng system downtime. Check your email.

I am one of those who miss the email from the airline about 1 hour earlier departure for the last flight to the mainland. (true story)

**Comment by VSadov** [comment]
Thanks!!

**Pull request merged**
