### PR TITLE
Fix: CTS.TryReset() concurrency issue #60182

### PR DESCRIPTION
**Pull request by sakno**
PR contains a fix for #60182

Also, the fix resolves potential concurrency between `Cancel` and `TryReset` as follows:
* If `Cancel` happens before `TryReset` then CTS will be canceled normally
* If `TryReset` happens before `Cancel` then `Cancel` will have no effect

### CODE REVIEW

**Comment by sakno** [comment]
@BrzVlad , @EgorBo , @eiriktsarpalis , @imhameed , @lambdageek , @lateralusX , @layomia , @marek-safar , @naricc , @SamMonoRT , @steveharter , @thaystg , @vargaz I'm very sorry guys, my bad, you're all added because I changed the base for this PR. The participation is not needed.

**Comment by stephentoub** [comment]
The original intent here was to use the timer's lock as the coordination mechanism.  That's still valid; the only thing that was missed was that the timer might explicitly throw if it's been closed. We're about to ship the release, and the proposed lock-free and non-trivial changes to synchronization are inherently risky, as is the potential perf impact to IsCancellationRequested I mentioned. We don't have time to fully vet such changes and any downstream impact. It's a lot less risky to simply add the catch block to deal with the one missed aspect initially. Even when we're not constrained by time, I'd prefer to follow-through with the original design and continue using the existing lock for the coordination and just avoiding the throw rather than adding any expense at all to IsCancellationRequested.

**Comment by sakno** [comment]
All expenses related to `IsCancellationRequested` removed in the last change. And there are still two mechanisms of synchronization: timer and __state_ field, even without my changes. _try-catch_ adds constant overhead to `TryReset` method. Moreover, a big plus here is a solution for `Cancel` and `TryReset` concurrency.

However, I'm agree with you about the timeline, so I see the following consensus here:
* I'll add a separated PR with _dirty hack_ for ObjectDisposedException
* This one I prefer to remain opened for further discussions

What do you think?

**Comment by stephentoub** [comment]
> I'll add a separated PR with _dirty hack_ for ObjectDisposedException

You keep trying to label it that way, but I disagree with the categorization.  TimerQueueTimer is signaling a particular state used for coordination with an exception rather than a return value, and the bug fundamentally is that the call site isn't properly handling that signal.  The true fix for the bug is thus adding that catch block.  Separately I dislike that this is the mechanism by which the internal TimerQueueTimer.Change is signaling that condition, and we can subsequently look at addressing that such that the state is optionally signaled via return value rather than exception, and both this catch block and the other in the file could then be changed to listen for that new signal (which this call site already is, and the other one doesn't actually need to pay attention to).

But, yes, please either change this PR to be that fix or open a new one for it.  Either way is fine, though I still don't think what's in this PR is the proper long-term change, as it's adding complexity for little reason.  It's also a breaking change: note that with how it's in this PR now, exceptions thrown from cancellation callbacks may be thrown out of TryReset.

**Comment by sakno** [comment]
> exceptions thrown from cancellation callbacks may be thrown out of TryReset.

Good catch. I'll change this PR with a quick fix (let's use this term instead of _dirty hack_ :smile: ) using `try-catch` and open a new PR with necessary changes to `TimerQueueTimer` class.

**Review by stephentoub — APPROVED** [review]
Thanks.

**Pull request merged**
