### PR TITLE
Handle embedded assignments in copy propagation

### PR DESCRIPTION
**Pull request by SingleAccretion**
There are two parts to this change:

First, refactor `optCopyProp` a little, mostly just rename locals to makes things less confusing. This is the first two commits; there are no diffs for them.

Second, and the point of this change: refactor the main copy propagation loop to correctly handle embedded assignments:
```
Previously, as the comments in copy propagation tell us, it
did not handle "intervening", or not-top-level definitions of
locals, instead opting to maintain a dedicated kill set of them.

This is obviously a CQ problem, but also a TP one, as it meant
there had to be a second pass over the statement's IR, where
the definitions would be pushed on the stack.

This change does away with that, instead pushing new definitions
as they are encountered in execution order, and simultaneously
propagating on uses. Notably, this means the code now needs to
look at the real definition nodes, i. e. ASGs, not the LHS locals,
as those are encountered first in canonical execution order, i. e.
for a tree like:

  ASG
    LCL_VAR V00 "def"
    ADD
      LCL_VAR V00
      LCL_VAR V00

Were we to use the "def" as the definition point, we would wrongly
push it as the definition on the stack, even as the assignments
itself hasn't happened yet at that point.

There are nice diffs with this change, all resulting from unblocked
propagations, and mostly coming from setup arguments under calls.
```

This has CQ benefits, however, for me, this is needed because I want copy propagation to stop relying on VNs being assigned to the LHSs of ASGs (they should all have `$VN.Void` VNs). For that to work, I need the context from the parent ASG to properly retain the previous behavior when making that change.

There are also, apparently, (big) TP benefits to this change: PIN reports `0.6%` decrease in instructions retired when replaying the benchmarks collection.

Contributes to #10873.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]
LGTM. I'm going to kick off jitstress runs.

**Comment by SingleAccretion** [comment]
The x86 stress failure does not appear related, but is unique.

FWIW, I have ran the test locally a few hundred times, and could not reproduce it.

**Comment by BruceForstall** [comment]
The plug.cmd test failure is https://github.com/dotnet/runtime/issues/63854 (presumably even though that was opened for arm64, the x86 failure here is the same).

**Pull request merged**
