### PR TITLE
[browser] Turn `BlazorCacheBootResources` off by default when targeting .NET 9

### PR DESCRIPTION
**Pull request by maraf**
With https://github.com/dotnet/runtime/pull/103755 in place, custom cache is not needed anymore

### CODE REVIEW

**Comment by pavelsavara** [comment]
The cache code could be deleted (to reduce size & complexity). 
Do we have good reason to keep it ?

**Comment by maraf** [comment]
> The cache code could be deleted (to reduce size & complexity). 
> Do we have good reason to keep it ?

It's still useful when users disable fingerprinting. I would prefer leaving it place for 9 and discuss more about removing it for 10.

**Review by pavelsavara — APPROVED** [review]

**Pull request merged**
