### PR TITLE
[wasm] Use latest stable version of chrome

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Review by lewing — APPROVED** [review]
LGTM assuming it is green

**Comment by radical** [comment]
Is this the System.Collections.Immutable.Tests timeout that was being seen with chrome earlier?

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-85114-merge-f49d5d592dc34ca39a/normal-System.Collections.Immutable.Tests/1/console.17140551.log?helixlogtype=result :
```
[01:40:42] info: Starting:    System.Collections.Immutable.Tests.dll
[02:10:23] fail: Tests timed out after 1800secs
[02:10:23] info: Process 67 didn't exit within 00:30:00 and will be killed
                 
[02:10:23] info: Killing process tree of 67...
                 
[02:10:23] info: Pids to kill: 67, 69
                 
[02:10:23] info: Running lldb diagnostics for pid 67
                 
[02:10:23] info: Printing backtrace for pid=67
                 
[02:10:23] info: lldb was not found, skipping diagnosis..
                 
[02:10:23] info: Running lldb diagnostics for pid 69
                 
[02:10:23] info: Printing backtrace for pid=69
                 
[02:10:23] info: lldb was not found, skipping diagnosis..
                 
[02:10:23] info: 67 Execution timed out after 1800 seconds and the process was killed.
                 
[02:10:23] info: Process v8 exited with 137
                 
XHarness exit code: 70 (TIMED_OUT)
```

**Comment by radical** [comment]
The timeout is happening on `main` too, as seen in rolling builds.

**Comment by radical** [comment]
Rest of the failures are known, and unrelated.

**Pull request merged**
