### PR TITLE
remove WSL checks in Socket tests

### PR DESCRIPTION
**Pull request by geoffkizer**
Contributes to https://github.com/dotnet/runtime/issues/18258

@ViktorHofer @tarekgh

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
These tests now work on WSL?

Or the failures were with WSL1 and they work fine with WSL2?

**Review by ViktorHofer — APPROVED** [review]

**Comment by geoffkizer** [comment]
> Or the failures were with WSL1 and they work fine with WSL2?

Yes

**Comment by ManickaP** [comment]
AFAIR the WSL2 shows up as a regular Linux OS, so the conditional attribute and check for `IsNotWindowsSubsystemForLinux` were specifically for WSL 1.
If the tests work for WSL 1 than great, if not we should probably keep the attribute.
Note that the tests should have been run on WSL2 even with the condition.
However, something might have changed since the last time I checked this, so my info might be outdated.

**Comment by ViktorHofer** [comment]
> If the tests work for WSL 1 then great, if not we should probably keep the attribute.

As already mentioned in another thread, we shouldn't support WSL1 in dotnet/runtime at all anymore.

**Pull request merged**
