### PR TITLE
Test merging baseservices/threading

### PR DESCRIPTION
**Pull request by BrianBohe**
This another pr merging JIT tests as https://github.com/dotnet/runtime/pull/81969. It starts with a commit removing args from test entrypoint, and then applies ILTransform with the arguments specified on each commit in the same directory (baseservices/threading). This is [the version of the tool](https://github.com/markples/utils/commit/cefdaff2982bc029bebe5cdb05118e99e38903ad) I used.
Last two commits are a patch on the test merging approach to avoid deduplicating test classes on il tests. These are taken from [PR merging JIT/Directed](https://github.com/dotnet/runtime/pull/81969).

### CODE REVIEW

**Comment by BrianBohe** [comment]
Before:

```
Time [secs] | Total | Passed | Failed | Skipped | Assembly Execution Summary
============================================================================
    126.661 |   180 |    180 |      0 |       0 | baseservices.threading.XUnitWrapper.dll
----------------------------------------------------------------------------
    126.661 |   180 |    180 |      0 |       0 | (total)
```

Now:

```
Time [secs] | Total | Passed | Failed | Skipped | Assembly Execution Summary
============================================================================
    222.114 |    85 |     85 |      0 |       0 | baseservices.threading.threading_group1
    152.050 |    95 |     95 |      0 |       0 | baseservices.threading.threading_group2
----------------------------------------------------------------------------
    374.164 |   180 |    180 |      0 |       0 | (total)
```

**Comment by BrianBohe** [comment]
There are only 3 baseservices/threading tests on issues.target but none of those has change

**Comment by BrianBohe** [comment]
Related issue https://github.com/dotnet/runtime/issues/71732

**Review by trylek — APPROVED** [review]
Looks great to me, thanks Brian!

**Pull request merged**
