### PR TITLE
Fix a typo.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
This seems to show up in github labels, i.e.:
https://github.com/dotnet/perf-autofiling-issues/labels/CompliationMode%3Dwasm
or maybe its unrelated ?

**Review by pavelsavara — APPROVED** [review]

**Comment by LoopedBard3** [comment]
I am hesitant to merge this without Drew taking a look as he would have better insights into where this typo may propagate in other systems. He will be back within the next few days, is that going to be too long of a wait? If not, I will make sure he sees this and provides his feedback.

**Review by agocke — APPROVED** [review]

**Comment by agocke** [comment]
@LoopedBard3 Anything left here?

**Comment by LoopedBard3** [comment]
@DrewScoggins Any thoughts? Since you are more familiar with potential impacts of this change.

**Pull request merged**
