### PR TITLE
Bump to new Ubuntu 22.04 queue for PPC64

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]

**Review by am11 — APPROVED** [review]
Looks good! 👍
We also added linux-musl-{ppc64le,s390x,riscv64,etc.} images in 22.04. At some point, can add those under community pipeline as well.

**Comment by directhex** [comment]
> Looks good! 👍 We also added linux-musl-{ppc64le,s390x,riscv64} images etc. in 22.04. At some point, can add those under community pipeline as well.

As long as a community port has a community submitting patches & actually looking at build logs, then the more the merrier

**Comment by am11** [comment]
> As long as a community port has a community submitting patches & actually looking at build logs, then the more the merrier

@ayakael is the resident expert on linux-musl architectures. 8-)

**Comment by directhex** [comment]
(Has anyone from the community ever indicated they're using or contributing to the armv6 target? Kinda feels like dead weight to me)

**Comment by ayakael** [comment]
re armv6, I tried porting to that for Alpine, but threw in the towel, as that target is basically on hospice care for the Alpine developpers.

**Pull request merged**
