### PR TITLE
Delete more type equivalence logic

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
In .NET Native times we could have a situation where two different `MethodTable` pointers represented the same type. This could happen for cloned types, or structurally equivalent parameterized types. The cloned type concept was never used in Native AOT. The structural equivalence disappeared in https://github.com/dotnet/runtimelab/commit/0ef7bd6cfe129f4c308f5d6dae1eccf48c3cdff4. Neither of those seems useful. So getting rid of some of the vestiges.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thanks!

**Review by jkotas — CHANGES_REQUESTED** [review]
Reflection smoke test is failing

**Comment by MichalStrehovsky** [comment]
> Reflection smoke test is failing

Should be fixed. This was a preexisting issue that was wrong ever since we started telling RyuJIT it's okay to inline type checks. I realized this when doing the function pointers (I left a gap between FunctionPointerTypeMap and ArrayMap for pointer types) but wondered whether we'll run into this in testing.

There was a similar issue for mdarrays.

I didn't fix it for byrefs, but it might be reachable there so I'm going to look into that too...

**Review by jkotas — APPROVED** [review]
Thanks!

**Pull request merged**
