### PR TITLE
HTTP3: Dispose HTTP3 connection when HttpClientHandler is disposed

### PR DESCRIPTION
**Pull request by geoffkizer**
Fixes https://github.com/dotnet/runtime/pull/56785

### CODE REVIEW

**Comment by wfurt** [comment]
Would this be only when there are no pending requests/responses or always? 
I though we preserve the HttpResponseStreams but maybe I'm mistaken with something else.

**Comment by geoffkizer** [comment]
We do preserve HttpResponseStreams, but that's the responsibility of the Http3Connection to do it -- in other words, when you call Dispose on it, it will initiate client-based shutdown and close the connection when the outstanding requests are completed.

Note HTTP2 works the same way -- we dispose all the HTTP2 connections, even though some may have in flight requests.

**Review by stephentoub — APPROVED** [review]
src update LGTM

**Comment by wfurt** [comment]
Ok. So this will not automatically call QuicConnection.Dispose, right? (that would rest all the streams)

**Comment by geoffkizer** [comment]
> So this will not automatically call QuicConnection.Dispose, right?

Right. Http3Connection.Dispose marks the connection as shutting down, then calls CheckForShutdown, which does the drain logic I described above.

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by ManickaP** [comment]
@geoffkizer Is this fixing #56766 ? Because the link description points to a PR not an issue and this looks like work on #56766. If so we should close that issue.

**Comment by geoffkizer** [comment]
> @geoffkizer Is this fixing #56766 ? 

Yes. Sorry, don't know how I ended up linking the wrong one.

**Pull request merged**
