### PR TITLE
[mono] Remove the llvmonly exception handling code, its not used any …

### PR DESCRIPTION
**Pull request by vargaz**
…more.

### CODE REVIEW

**Comment by akoeplinger** [comment]
would you mind updating the comments here to document that llvmonly and llvmonly-interp are the same now: https://github.com/dotnet/runtime/blob/858221cc3326c55d8df5966ea4bad6336b21dc87/src/native/public/mono/jit/details/jit-types.h#L24-L25

**Comment by vargaz** [comment]
Some failures are relevant.

**Review by lambdageek — APPROVED** [review]

**Comment by vargaz** [comment]
The 'Build Browser wasm windows Release LibraryTests_AOT' lane times out, not sure whenever its relevant or not.

**Pull request merged**
