### PR TITLE
Add X64/Arm64 nested classes to System.Runtime.Intrinsics where missing

### LINKED ISSUE #34587: Add empty X64/Arm64 nested classes to some System.Runtime.Intrinsics
### Rationale
Imagine you have an arm64 CPU with `ArmBase` and `ArmBase.Arm64` support (both are always enabled for any arm64 CPU), but without `Aes`, `Sha1` and `Sha256` features, let's run the following snippet:
```csharp
Console.WriteLine(ArmBase.IsSupported);       // true
Console.WriteLine(ArmBase.Arm64.IsSupported); // true

Console.WriteLine(Aes.IsSupported);           // false
Console.WriteLine(Aes.Arm64.IsSupported);     // true (??)

Console.WriteLine(Sha1.IsSupported);          // false
Console.WriteLine(Sha1.Arm64.IsSupported);    // true (??)

Console.WriteLine(Sha256.IsSupported);        // false
Console.WriteLine(Sha256.Arm64.IsSupported);  // true (??)
```
The problem here is the fact that `Aes`, `Sha1` and `Sha256` inherit from `ArmBase` but don't define their own `Arm64` nested classes, see [sharplab.io](https://sharplab.io/#v2:EYLgHgbALANALiAlgGwD4AEBMBGAsAKAKP3QGYACLcgQQCcBbAIQEMBnAUwIG8Dy/KK6bBHLAA9mOTkAkqwDKAVwAOSsbTjsAJuQC8APnJxaC9gG5e/C3zKVMNBtCvke+fm4GVhoiVNmKVahra+obGZk4AvgRRhCSCdnIAFsyYAKwiIPZMbJz4Lm42QiLikjLyyqrqWroGAGbMyBym5AD0LeTsAHQA5p3k9ACe5IkA7uSaYuysAHYA5HDkrBWB5Ekp6U5ObavJaSITU3MLyQBu7OSIcKzkYiPTWY74MQSFdkIA7Nxb7XJiFwvICQAa2uyEQQPO0nIAGNEuxoUDyLU1Dt1iJmCdmChmMAUJchnDaLk3NtgAoFoh7tIADL/WbXABE0IaUhKUjo2Q4LQ50BAIG67DgAH0/MsqpoABQASgZTkKXjZ5AAYhJpTVUXtOjyoJ1RQFxc1tuh3tcjCZokA===) for more details (it explains why it can't be fixed in the jit).

### Proposed API
```diff
    [Intrinsic]
    [CLSCompliant(false)]
    public abstract class Sha1 : ArmBase
    {
        internal Sha1() { }

        public static new bool IsSupported { get => IsSupported; }
        
+       public abstract class Arm64 : ArmBase.Arm64;
+       {
+           public static new bool IsSupported => Sha1.IsSupported; // && IntPtr.Size == 8 ?
+       }
```
(same for `Sha256` and `Aes`)
**UPD** same for `Aes`, `Avx`, `Avx2`, `Fma`, `Pclmulqdq`, `Sse3`, `Ssse3`

/cc @tannergooding @echesakovMSFT

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/34587 by adding in X64 and Arm64 nested classes to the System.Runtime.Intriniscs classes where they were missing.

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @echesakovMSFT, @CarolEidt for review.

CC. @EgorBo, this seems to have broken Mono, is there something specific I need to update?

**Comment by EgorBo** [comment]
@tannergooding looks like it's a different issue, so should be OK from mono side.

**Comment by tannergooding** [comment]
Alright, it looked to be a failure in the test this PR is adding, so I wasn't sure. Thanks!

**Comment by tannergooding** [comment]
@EgorBo, looks like its still failing. Based on the failure, some API is returning `IsSupported` where a lower ISA is not. It isn't clear which API that is as there is no line information in the failure.

**Comment by EgorBo** [comment]
@tannergooding where can I find that test? I don't see any `Runtime_34587` test in the sources, is it internal?

**Comment by tannergooding** [comment]
Right here: https://github.com/dotnet/runtime/pull/38460/files#diff-e4e58d0c6a832040d081a159b95e83bb

It just validates that for any `IsSupported == true`, the relevant related conditions are met.

**Comment by EgorBo** [comment]
> Right here: https://github.com/dotnet/runtime/pull/38460/files#diff-e4e58d0c6a832040d081a159b95e83bb
> 
> It just validates that for any `IsSupported == true`, the relevant related conditions are met.

can you please add this test to `issues.targets` to ignore on Mono and I'll take a look tomorrow.
it looks like our hierarchy is a bit outdated e.g. we don't support X86Base

**Review by CarolEidt — APPROVED** [review]
LGTM

**Comment by jkotas** [comment]
This was JIT/EE interface breaking change and it should have updated the JIT/EE interface GUID.

I am adding a note about it in https://github.com/dotnet/runtime/pull/39777

**Pull request merged**
