### PR TITLE
Avoid SafeHandle finalization from failed registry operations

### LINKED ISSUE #71773: Passing a path to a key that doesn't exist to OpenSubKey() causes a SafeRegistryHandle to be finalized
### Description

In cases where the specified registry key doesn't exist, a `SafeRegistryHandle` isn't properly disposed and is finalized. The call to `RegOpenKeyEx()` causes the creation of the `SafeRegistryHandle` which is normally passed to the `RegistryKey` constructor and disposed by the caller. In the error case, `OpenSubKey()` returns `null` and fails to dispose the wrapper around the invalid handle.

https://github.com/dotnet/runtime/blob/6a889d234267a4c96ed21d0e1660dce787d78a38/src/libraries/Microsoft.Win32.Registry/src/Microsoft/Win32/RegistryKey.Windows.cs#L269

Something like this is sufficient to expose the issue:
`const string regKeyPath = "some\\invalaid\\path";`
`using var subKey = Registry.CurrentUser.OpenSubKey(regKeyPath);`

### Regression?

This looks like a long-standing issue. I see finalization happening in both .NET Framework 4.8 and .NET 6.

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/71773

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
Just curious, do we make any attempt in tests of some sort to look for unintended finalizations? I guess without some kind of diagnostics into the GC there is no reliable way and we just rely on code inspection, and the unlikely situation of it being exposed by what stress tests we do run.

**Comment by danmoseley** [comment]
Thinking, perhaps it would look something like: an environment variable to disable the finalizer thread (does that exist?); then manually running a set of unit tests (presumably we have unit tests for invalid reg keys e.g.), forcing GC, and inspecting a dump to see objects pending finalization, perhaps focusing on certain types. Or simply events/tracing of finalizer activity .

**Comment by stephentoub** [comment]
> Just curious, do we make any attempt in tests of some sort to look for unintended finalizations?

We've done things in the past like this:
https://github.com/dotnet/runtime/blob/60d3d052eaa8359746090291d81e5e3e17366e06/src/libraries/Common/src/Microsoft/Win32/SafeHandles/SafeX509Handles.Unix.cs#L12-L26

**Comment by danmoseley** [comment]
Curious how many hits we'd get if we ran our unit tests now with that pasted into SafeRegistryHandle, e.g.. I'm guessing  leaky tests would hide such bugs. Would it be worth creating an issue in case a community member is interested in such an experiment? If it was not too painful they could then try with SafeFileHandle E.g.

**Comment by stephentoub** [comment]
I'm already working on it.  It's _a lot_.

**Pull request merged**
