### PR TITLE
Add Microsoft.Extensions.Diagnostics.* to Aspnet Transport package

### PR DESCRIPTION
**Pull request by wtgodbe**
Should unblock https://github.com/dotnet/aspnetcore/pull/48407/

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
If this is really all it takes +💯

**Review by ericstj — APPROVED** [review]
LGTM

**Review by tarekgh — APPROVED** [review]

**Comment by carlossanlop** [comment]
CI failures were sudden platform crashes during test execution, unrelated. Merging now.

```
[16:18:04.7833420] Xamarin.Hosting: Process '46177' exited with exit code 1 or crashing signal .
[16:18:04.7838740] Application 'net.dot.System.Runtime.Tests' terminated (with exit code '1' and/or crashing signal ').
```

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
