### PR TITLE
Add pool provider template reference

### PR DESCRIPTION
**Pull request by hoyosjs**
Use template to determine pool provider to use. 

The provider can't be expanded in the pipeline-with-resources step as the expansion breaks once global variables are consolidated. All variables end up in the global scope correctly, but several expansion points are expanded before assignment - particularly the ones at the pipeline scope - meaning that several parameters derived from them are empty and cause issues in further expansion decisions.

### CODE REVIEW

**Review by MattGal — APPROVED** [review]
LGTM,  make sure to check in on any pipelines not run as part of PR validation after it merges.

**Review by MattGal — APPROVED** [review]

**Review by jkoritzinsky — APPROVED** [review]
Do we want to add the variable template in the `pipeline-with-resources.yml` template instead of in each job template? Not sure if it makes an appreciable difference.

**Comment by hoyosjs** [comment]
@jkoritzinsky I tried, the yml fails to expand sadly. something already defines a variable scope globally.

**Comment by jkoritzinsky** [comment]
Dang. Let's just go with this then.

**Comment by MattGal** [comment]
> Dang. Let's just go with this then.

There are some... compromises... in the eng/common folder's usage of the same for the same reason.  I'm just happy it can work at all.

**Comment by hoyosjs** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2120060&view=logs&j=af986455-df3a-5ed6-b067-9144b6c8d0c6

verifies the internal build used the variables were properly expanded.

**Pull request merged**
