### PR TITLE
System.Net Telemetry style changes

### PR DESCRIPTION
**Pull request by MihaZupan**
- Changed `Http11ConnectionEstablished` and `Http20ConnectionEstablished` events to `ConnectionEstablished(version)`
- Changed `Http11ConnectionClosed` and `Http20ConnectionClosed` events to `ConnectionClosed(version)`
- Changed `Http11RequestLeftQueue` to `RequestLeftQueue(version)`
- Added an `Http20` equivalent of `RequestLeftQueue` and added a `http20-requests-queue-duration` counter
- Changed `System.Net.Security.HandshakeStop` event's `protocol` property from `string` to `SslProtocols` enum.

### CODE REVIEW

**Review by ManickaP — APPROVED** [review]
LGTM, thanks!

**Comment by MihaZupan** [comment]
Test failure: #41381

**Pull request merged**
