### PR TITLE
[mono][sgen] Update memory load information after world is resumed

### PR DESCRIPTION
**Pull request by BrzVlad**
Following recent cgroup support (https://github.com/dotnet/runtime/pull/74237), mono_determine_physical_ram_size is no longer safe to call during GC.

### CODE REVIEW

**Comment by naricc** [comment]
What part of https://github.com/dotnet/runtime/pull/74237 makes it unsafe to call `mono_determine_physical_ram_size` during GC?

**Review by naricc — APPROVED** [review]

**Comment by nealef** [comment]
> @nealef @akoeplinger Any idea if this impacts android ?

The new code explicitly excludes Android. That is, it uses the previous code path.

**Comment by BrzVlad** [comment]
@naricc `getCGroupMemoryLimit` is the main one, it uses a lot of C api's that are unsafe.

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
I didn't realize we query the ram size on each GC stw cycle, do we know if the cgroup additions have any perf impact?

We'll also need to backport this to 7.0 since we backported the cgroup change.

**Comment by naricc** [comment]
> I didn't realize we query the ram size on each GC stw cycle, do we know if the cgroup additions have any perf impact?
> 
> We'll also need to backport this to 7.0 since we backported the cgroup change.

I have not seen any perf regressions that I could attribute to this, although the microbenchmarks are so micro I am not sure how many of them exercise the GC much. There was also some missing data on some platforms around the time this was merged.

**Comment by akoeplinger** [comment]
Failures are unrelated.

**Pull request merged**
