### PR TITLE
Delete pragma suppression for warning disabled with UnconditionalSuppressMessage

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
https://github.com/dotnet/runtime/pull/109963#discussion_r1850060556

### CODE REVIEW

**Review by Youssef1313 — APPROVED** [review]

**Comment by Youssef1313** [comment]
@MichalStrehovsky Is this going to be backported for .NET 8 to avoid the IL3000 in apps?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky Is this going to be backported for .NET 8 to avoid the IL3000 in apps?

The thing that needs backporting is the UnconditionalSuppressMessage on line 73 (that I'm not touching here). Deleting the pragma is not necessary to service.

I believe @rzikm is on top of that.

**Comment by rzikm** [comment]
Thanks, I was planning to address your comment today myself.

Servicing PR is in progress.

**Review by CarnaViire — APPROVED** [review]
Thanks!

**Pull request merged**
