### PR TITLE
[release/7.0][mono] Use unsigned char when computing UTF8 string hashes

### LINKED ISSUE #78638: AOT - Cannot use System.Reflection on type named `AktifBarkod.AktifPOS.Mobil.EkranDiğer.Ana.AnaPage`
### Description

I have published a .NET Maui app it is working on emulators but not working on real devices.  By the way, I have tested 5 different real device.

### **When trimming and AOT is disabled it works but incredibly slow and sluggish.** 

There is a apk file I have uploaded for testing, you can download it to your devices and emulators also.
https://aktifbarkod.com/d just go and download apk file. ( There is a only one apk file )

The only log output I can find is below from a real device:
```
android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load type AktifBarkod.AktifPOS.Mobil.EkranDiğer.Ana.AnaPage while decoding custom attribute: (null)
   at System.Reflection.CustomAttribute.GetCustomAttributesBase(ICustomAttributeProvider , Type , Boolean )
   at System.Reflection.CustomAttribute.GetCustomAttributes(ICustomAttributeProvider , Type , Boolean )
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(Assembly , Type )
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[XamlResourceIdAttribute](Assembly )
   at Microsoft.Maui.Controls.Xaml.XamlResourceIdAttribute.GetTypeForPath(Assembly assembly, String path)
   at Microsoft.Maui.Controls.ResourceDictionary.SetAndLoadSource(Uri value, String resourcePath, Assembly assembly, IXmlLineInfo lineInfo)
   at AktifBarkod.AktifPOS.Mobil.App.InitializeComponent()
   at AktifBarkod.AktifPOS.Mobil.App..ctor()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type )
   at System.Collections.Concurrent.ConcurrentDictionary2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type , Func`2 )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type )
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider )
   at Microsoft.Maui.MauiApplication.OnCreate()
   at Android.App.Application.n_OnCreate(IntPtr , IntPtr )
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
 at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
 at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6975)
 at android.app.ActivityThread.access$1500(ActivityThread.java:257)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:236)
 at android.app.ActivityThread.main(ActivityThread.java:8037)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

Real device

https://user-images.githubusercontent.com/7950917/201405363-05593aff-26bb-4aee-bfc3-e8017199dbad.mp4

Emulator

https://user-images.githubusercontent.com/7950917/201408674-68cda6da-3e98-42d6-91d5-ae0782785c0f.mp4

PS:

### Steps to Reproduce

-

### Link to public reproduction project repository

This is a private repo.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All android versions

### Did you find any workaround?

no

### Relevant log output

_No response_

### LINKED ISSUE #82187: Crash on startup on Android in Release when referencing a class with non ascii characters from a class library
### Description

I have a class _Tür_ in a .NET 7 class library and I reference this class in a MAUI-App.  When compiled in Release with AOT enabled, on an Android device, the app crashes immediatly.
Works on Windows.
Works on Android Emulator

I am using Visual Studio 17.4.5.

Installed Workload Id      Manifest Version      Installation Source
--------------------------------------------------------------------
maui                       7.0.59/7.0.100        SDK 7.0.200

### Steps to Reproduce

1. Create a new .NET MAUI App
2. Create a .NET 7 class library
3. Add a Reference to the class libarary to the MAUI app
4. Add a class Tür to the class library
5. Add a field to App.xaml.cs using the class Tür
6. Run the app on an android device in Release

### Link to public reproduction project repository

https://github.com/CodeAuChocolat/MauiUmlautCrash

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 7, Android 12

### Did you find any workaround?

Rename class or disable AOT

### Relevant log output

```shell
Time	Device Name	Type	PID	Tag	Message
02-15 10:04:07.288	CipherLab RS31	Error	18286	AndroidRuntime	android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load type of field 'MauiUmlautCrash.App:_tor' (0) due to: Could not resolve type with token 01000058 from typeref (expected class 'UmlautLib.Tür' in assembly 'UmlautLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:UmlautLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:UmlautLib.Tür member:(null)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type )
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type , Func`2 )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type )
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider )
   at Microsoft.Maui.MauiApplication.OnCreate()
   at Android.App.Application.n_OnCreate(IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
	at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
	at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5503)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
 from settings cache , name = dropbox:data_app_crash , value = null
 from settings cache , name = send_action_app_error , value = 1
 from settings cache , name = logcat_for_data_app_crash , value = null
  Force finishing activity com.companyname.mauiumlautcrash/crc642a249426a1f98bd8.MainActivity
 from settings cache , name = dropbox:data_app_crash , value = null
 from settings cache , name = dropbox_age_seconds , value = null
 from settings cache , name = dropbox_max_files , value = null
 from settings cache , name = dropbox_quota_percent , value = null
 from settings cache , name = dropbox_reserve_percent , value = null
 from settings cache , name = dropbox_quota_kb , value = null
```

### PR DESCRIPTION
**Pull request by lambdageek**
Backport of #83273 to release/7.0

Resolves #82187 
Resolves #78638

The corresponding 6.0 PR is #83303 

## Customer Impact

Resolves crashes in Release builds of Android apps that include classes with non-ASCII names that use AOT compilation.

## Testing

Manual testing.  New regression test.

## Risk

Low. For code that uses ASCII names the hash code computation is unchanged.

### CODE REVIEW

**Comment by carlossanlop** [comment]
Hey @lambdageek - Are you intending to get this approved for the April servicing release? Code-complete is today.

**Comment by lambdageek** [comment]
@carlossanlop I don't think we'll make it. Let's try for the next one

**Comment by lambdageek** [comment]
@vargaz review plz.  And also #83303

**Comment by lambdageek** [comment]
@vargaz @thaystg could I get a review for this PR and for #83303

**Review by thaystg — APPROVED** [review]

**Comment by carlossanlop** [comment]
I'm retargeting this PR to the new `release/7.0-staging` branch, which is the one that we will use from now on for servicing fixes. 

Repo maintainers will now be allowed to merge their own servicing PR as long as it meets the requirements:

- It is appoved by Tactics (signaled by adding the `Servicing-approved` label).
- It's signed-off by an area owner.
- The CI is green, or the failures are investigated as unrelated.
- And if the PR touches an OOB package, the necessary OOB authoring changes are added.

The new process is described here: [runtime/docs/project/library-servicing.md](https://github.com/dotnet/runtime/blob/release/7.0-staging/docs/project/library-servicing.md).

The infra team will be actively monitoring servicing PRs to ensure all requirements are met and to help with any issues.

Let me know if you have any questions.

**Comment by carlossanlop** [comment]
I see you already retargeted it, @lambdageek. You're awesome.

**Review by vargaz — APPROVED** [review]

**Pull request merged**
