### PR TITLE
Produce symbols archives

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Contributes to #49026

### CODE REVIEW

**Review by hoyosjs — APPROVED** [review]

**Comment by hoyosjs** [comment]
Do you know if the nethost archive is also needed?

**Comment by jkoritzinsky** [comment]
Based on the issue in dotnet/source-build,  I don't believe the nethost archive is needed for source-build. Since it's a little more work to re-enable, I decided to get this done first before handling that.

**Review by safern — APPROVED** [review]

**Review by MichaelSimons — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
Only failure is a machine disconnect, so I'm going to merge this.

**Pull request merged**
