### PR TITLE
Fix JIT pipeline issues with instantiation

### LINKED ISSUE #82506: superpmi diff/replay jobs are failing
See this error:

image

Most likely caused by https://github.com/dotnet/runtime/pull/82452

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Could not find a pool with name $(DncEng",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by hoyosjs**
Fixes https://github.com/dotnet/runtime/issues/82506

### CODE REVIEW

**Comment by kunalspathak** [comment]
runtime-coreclr superpmi-diffs

**Comment by kunalspathak** [comment]
@hoyosjs - could you trigger the 2 jobs manually? Not sure it is not letting me start using `/azp`

**Comment by BruceForstall** [comment]
I manually triggered diffs and replay pipelines

**Comment by jakobbotsch** [comment]
The failure is #82397

**Review by jakobbotsch — APPROVED** [review]

**Pull request merged**
