### PR TITLE
Fix diagnosticport test failure in ilasm/ildasm round-trip testing

### LINKED ISSUE #80680: Test failure tracing\\eventpipe\\diagnosticport\\diagnosticport\\diagnosticport.cmd
Run: [runtime-coreclr ilasm 20230114.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=137887&view=ms.vss-test-web.build-test-results-tab&runId=2999018&resultId=122104&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked ilasmroundtrip @ Windows.11.Arm64.Open
- tracing\\eventpipe\\diagnosticport\\diagnosticport\\diagnosticport.cmd

coreclr linux arm64 Checked ilasmroundtrip @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
- tracing/eventpipe/diagnosticport/diagnosticport/diagnosticport.sh

coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open
- tracing\\eventpipe\\diagnosticport\\diagnosticport\\diagnosticport.cmd

coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open
- tracing\\eventpipe\\diagnosticport\\diagnosticport\\diagnosticport.cmd

coreclr linux arm Checked ilasmroundtrip @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
- tracing/eventpipe/diagnosticport/diagnosticport/diagnosticport.sh

coreclr linux x64 Checked ilasmroundtrip @ Ubuntu.1804.Amd64.Open
- tracing/eventpipe/diagnosticport/diagnosticport/diagnosticport.sh

coreclr osx x64 Checked ilasmroundtrip @ OSX.1200.Amd64.Open
- tracing/eventpipe/diagnosticport/diagnosticport/diagnosticport.sh

coreclr osx arm64 Checked ilasmroundtrip @ OSX.1200.ARM64.Open
- tracing/eventpipe/diagnosticport/diagnosticport/diagnosticport.sh
```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\B94E09EE\w\C3920A54\uploads\Reports\tracing.eventpipe\diagnosticport\diagnosticport\diagnosticport.output.txt
Raw output:
BEGIN EXECUTION
C:\h\w\B94E09EE\p\ildasm.exe /raweh /unicode /out=diagnosticport.dasm.il diagnosticport.dll
C:\h\w\B94E09EE\p\ilasm.exe /output=diagnosticport.asm.dll  diagnosticport.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'diagnosticport.dasm.il'  to EXE --> 'diagnosticport.asm.dll'
Source file is UNICODE

Assembled method Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableContextAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullablePublicOnlyAttribute::.ctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c::.cctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c::.ctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c::<TEST_CanGetProcessInfo2WhileSuspended>b__6_0
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c::<TEST_CanGetProcessInfo2WhileSuspended>b__6_1
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c::<Main>b__7_0
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_0?<<TEST_MultipleConnectPortsNoSuspend>b__0>d::MoveNext
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_0?<<TEST_MultipleConnectPortsNoSuspend>b__0>d::SetStateMachine
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_0::.ctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_0::<TEST_MultipleConnectPortsNoSuspend>b__0
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_1?<<TEST_MultipleConnectPortsNoSuspend>b__1>d::MoveNext
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_1?<<TEST_MultipleConnectPortsNoSuspend>b__1>d::SetStateMachine
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_1::.ctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass1_1::<TEST_MultipleConnectPortsNoSuspend>b__1
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_0?<<TEST_MultipleConnectPortsSuspend>b__0>d::MoveNext
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_0?<<TEST_MultipleConnectPortsSuspend>b__0>d::SetStateMachine
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_0::.ctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_0::<TEST_MultipleConnectPortsSuspend>b__0
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_1?<<TEST_MultipleConnectPortsSuspend>b__1>d::MoveNext
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_1?<<TEST_MultipleConnectPortsSuspend>b__1>d::SetStateMachine
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_1::.ctor
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_1::<TEST_MultipleConnectPortsSuspend>b__1
Assembled method Tracing.Tests.DiagnosticPortValidation.DiagnosticPortValidation?<>c__DisplayClass2_1::<TEST_MultipleConnectPortsSuspend>b__2
Assembled method Tracing.Tests.DiagnosticPortValidation.Dia


Stack trace
   at tracing_eventpipe._diagnosticport_diagnosticport_diagnosticport_._diagnosticport_diagnosticport_diagnosticport_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by elinor-fung**
Fixes https://github.com/dotnet/runtime/issues/80680

### CODE REVIEW

**Review by BruceForstall — APPROVED** [review]
LGTM if ilasm round-trip test passes.

**Comment by BruceForstall** [comment]
I manually triggered ilasm:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=140755&view=results

Not sure why comment trigger doesn't work.

**Review by davmason — APPROVED** [review]
Thanks!

**Comment by elinor-fung** [comment]
Failures are known:
- https://github.com/dotnet/runtime/issues/80666

**Pull request merged**
