### PR TITLE
Improve codegen in impStringEqualsOrStartsWith

### PR DESCRIPTION
**Pull request by EgorBo**
A quick improvement for `impStringEqualsOrStartsWith` suboptimal codegen noticed by @MichalPetryka 
```cs
public static int A() => B("b");

[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static int B(string s)
{
    switch (s)
    {
        case "a":
            return 1;
        case "b":
            return 2;
        case "c":
            return 3;
        default:
            return 0;
    }
}
```
Old codegen for `A`:
```asm
; Method Tests:A():int (FullOpts)
       mov      rax, 0x1BC003094DC
       movzx    rax, word  ptr [rax]
       mov      rcx, 0x1BC003094F4
       cmp      ax, word  ptr [rcx]
       sete     al
       movzx    rax, al
       test     eax, eax
       je       SHORT G_M44172_IG04
       mov      eax, 1
       jmp      SHORT G_M44172_IG05
G_M44172_IG04:  ;; offset=0x002B
       mov      eax, 2
       ret      
; Total bytes of code: 49
```
New codegen for `A`:
```asm
; Method Tests:A():int (FullOpts)
       mov      eax, 2
       ret      
; Total bytes of code: 6
```

### CODE REVIEW

**Comment by EgorBo** [comment]
@MihuBot

**Comment by ShreyasJejurkar** [comment]
I wonder if this wasn't happening earlier? Even surprising to me is that input itself is a constant string and still earlier JIT was not able to fold!? Strange!  

Btw how do we make sure that codegen doesn't change in the future, I mean do we have unit tests for generated codegen?

**Comment by EgorBo** [comment]
> I wonder if this wasn't happening earlier? Even surprising to me is that input itself is a constant string and still earlier JIT was not able to fold!? Strange!
> 
Switch over string literals is quite complicated under the hood, although, in this case it's actually a series of String.Equals which still are complicated.

> Btw how do we make sure that codegen doesn't change in the future, I mean do we have unit tests for generated codegen?

Yes, we do have FILECHECK tests but considering that jit-diff only found a single case I guess it's an overkill here

**Comment by EgorBo** [comment]
@jakobbotsch ptal, quick change - no diffs almost in BCL but might find something in user's code. The idea is to not give up on case when both args are string literals so the unrolled version will be still foldable

**Review by jakobbotsch — APPROVED** [review]

**Pull request merged**
