### PR TITLE
Enable Alpine ARM support

### PR DESCRIPTION
**Pull request by janvorli**
This change enables Alpine ARM support in the lab build scripts,
packages and RID graph.

### CODE REVIEW

**Review by safern — COMMENTED** [review]
Overall looks good. However this is not adding any builds to either official builds or PR/CI.

**Comment by janvorli** [comment]
@safern I have not realized this before, but @trylek mentioned it yesterday too. I am going to update this PR with changes in the runtime.yml (I hope I understand it correctly that that is where we define what gets built in official builds and PR/CI). But I am quite confused by the seemingly random selection of OSes / architectures for various templates in that file. Do you have a guidance on where it would make sense to add the Linux_musl_arm? I've started by trying to put it everywhere where I've seen Linux_musl_arm64, but I am not sure if that's the right approach.

**Comment by safern** [comment]
`runtime.yml` is for PR/CI -- `runtime-official.yml` is for official builds.

> Do you have a guidance on where it would make sense to add the Linux_musl_arm? I've started by trying to put it everywhere where I've seen Linux_musl_arm64, but I am not sure if that's the right approach.

In `runtime-official.yml` that should be enough. For `runtime.yml` we should be more clinical because we don't have much resources to run tests on arm in all PRs. What I would suggest for `PR/CI` is to add this new platform wherever we have `linux_musl_arm64` push the changes and by looking at the diff it would be easier to give feedback.

**Comment by janvorli** [comment]
Thanks @safern, I've just added a new commit that updates runtime.yml and runtime-official.yml.

**Comment by safern** [comment]
`runtime-official.yml` looks good.

`runtime.yml` is just adding build legs. Do we want to run libraries tests on `linux_musl_arm` against a checked runtime?

https://github.com/dotnet/runtime/blob/89726136b4e4b6eacdf5abbf4b9c32a4e92c0700/eng/pipelines/runtime.yml#L911

**Comment by safern** [comment]
Also, do we know what kind of test coverage we need for `linux_musl_arm`?

**Comment by janvorli** [comment]
Ah, I've missed that one. I'll add it in a second.
As for test coverage, it seems that we can use the same we have for Linux-musl-arm64. But I don't have a strong opinion there and I am not sure what is our reasoning behind test matrix for platforms we have right now.

**Review by safern — APPROVED** [review]
LGTM from the yml changes.

**Comment by janvorli** [comment]
@safern I can see that coreclr, libraries and installer builds for arm musl have succeeded, but library tests are failing early with this error:
```
./RunTests.sh: line 161: /root/helix/work/correlation/dotnet: No such file or directory
```
Do you have any idea what can be wrong? Is it possible that it is some kind of chicken and egg issue?

One of the test logs is here:
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-41982-merge-16b4c390e366456f83/Microsoft.Extensions.Configuration.CommandLine.Tests/console.d3067d68.log?sv=2019-02-02&se=2020-09-29T18%3A12%3A23Z&sr=c&sp=rl&sig=33ZU3C7EONbfYcvMy4tH4rS0g0dk6dFogdTW56XQMps%3D

**Comment by trylek** [comment]
@janvorli - I think we should take a closer look at this bit:

https://github.com/dotnet/runtime/blob/ded9f9d0d601561d3a615a5b58fc0cd509d5f153/eng/common/templates/steps/send-to-helix.yml#L20

**Comment by safern** [comment]
Could it be that the dotnet host doesn't have support for Linux_musl_arm leg yet?

We consume the host package produced from dotnet/runtime. So what we should probably do is merge this without running tests and then once we produce a new host package with musl_arm support update the package version and add test runs.

**Comment by janvorli** [comment]
I don't know where it was supposed to get the dotnet executable from. I was thinking that it would come from the installer build and test leg. But I guess you are most likely right and the package needs to be produced first.

**Comment by safern** [comment]
Yeah it comes from a Package, we don't yet use the live built host. We have an active issue to do that.

**Comment by janvorli** [comment]
Ok, let me disable the tests for now.

**Comment by janvorli** [comment]
@ericstj do the RID related changes look good to you?

**Review by ericstj — APPROVED** [review]
Lgtm

**Pull request merged**
