### PR TITLE
Fix ARM64 floating point registers unwinding in PAL

### LINKED ISSUE #56522: Arm64 codegen bug.
Such tests produces different results with `COMPlus_JitDoValueNumber=0` and `COMPlus_JitDoValueNumber=1`:

The issue is in `TestConvertFromFloatToU8`.

```
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Reflection;
using System.Reflection.Emit;

namespace CheckGenericSbyte
{
    class Program
    {

        static int failedCount = 0;

        static readonly bool ExpectException = true;
        static readonly bool DontExpectException = false;

        static readonly bool UnspecifiedBehaviour = true;

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void GenerateTest<F, T>(F from, OpCode fromOpcode, OpCode convOpcode, bool exceptionExpected, T expectedTo, bool undefined = false) where F : struct where T : struct, IEquatable<T>
        {
            bool checkResult = !exceptionExpected && !undefined;
            Debug.Assert(!exceptionExpected || !checkResult);
            Debug.Assert(checkResult || expectedTo.Equals(default(T)));

            Type[] args = new Type[] { }; // No args.
            Type returnType = typeof(T);
            Console.WriteLine("Run test from " + typeof(F).FullName + ", value " + from.ToString() + " To " + typeof(T).FullName + "with Op " + convOpcode.Name + " exception expected: " + exceptionExpected);
            string name = "DynamicConvertFrom" + typeof(F).FullName + "To" + typeof(T).FullName + from.ToString() + "Op" + convOpcode.Name;
            DynamicMethod dm = new DynamicMethod(name, returnType, args);

            ILGenerator generator = dm.GetILGenerator();

            if (typeof(F) == typeof(int)) generator.Emit(fromOpcode, (int)(object)from);
            else if (typeof(F) == typeof(long)) generator.Emit(fromOpcode, (long)(object)from);
            else if (typeof(F) == typeof(nint)) generator.Emit(fromOpcode, (nint)(object)from);
            else if (typeof(F) == typeof(float)) generator.Emit(fromOpcode, (float)(object)from);
            else if (typeof(F) == typeof(double)) generator.Emit(fromOpcode, (double)(object)from);
            else
            {
                throw new NotSupportedException();
            }

            generator.Emit(convOpcode);
            generator.Emit(OpCodes.Ret);

            try
            {
                T res = (T)dm.Invoke(null, BindingFlags.Default, null, new object[] { }, null);
                if (exceptionExpected)
                {
                    failedCount++;
                    Console.WriteLine("No exception in " + name);
                }
                if (checkResult && !expectedTo.Equals(res))
                {
                    failedCount++;
                    Console.WriteLine("Wrong result in " + name);
                }
            }
            catch
            {
                if (!exceptionExpected)
                {
                    failedCount++;
                    Console.WriteLine("Not expected exception in " + name);
                }
            }
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void TestConvertFromFloatToU8()
        {
            OpCode sourceOp = OpCodes.Ldc_R4;

            OpCode convNoOvf = OpCodes.Conv_U8;
            GenerateTest<float, ulong>(long.MinValue, sourceOp, convNoOvf, DontExpectException, 0, UnspecifiedBehaviour);

            OpCode convOvf = OpCodes.Conv_Ovf_U8;
            GenerateTest<float, ulong>(long.MinValue, sourceOp, convOvf, ExpectException, 0);

            OpCode convOvfUn = OpCodes.Conv_Ovf_U8_Un;
            GenerateTest<float, ulong>(int.MinValue, sourceOp, convOvfUn, ExpectException, 0);
            GenerateTest<float, ulong>(long.MinValue, sourceOp, convOvfUn, ExpectException, 0);

            TestSimple(long.MinValue, (float)long.MinValue);
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        public static void TestSimple(float f, object f1)
        {
            Console.WriteLine("Test Simple value is " + f + ", f1 is " + f1.ToString());
            Debug.Assert(f < -1E-9);
        }

        static int Main(string[] args)
        {
            TestConvertFromFloatToU8();
            return 100;
        }
    }
}

```

It looks like we do wrong CSE in `TestConvertFromFloatToU8` and we pass `0` instead of `long.MinValue` in some cases:
```
seandree@seandreemac TestConvertFromIntegral % export COMPlus_JitDoValueNumber=1
seandree@seandreemac TestConvertFromIntegral % ./TestConvertFromIntegral.sh
BEGIN EXECUTION
/Users/seandree/git/runtime/artifacts/tests/coreclr/OSX.arm64.Checked/Tests/Core_Root/corerun TestConvertFromIntegral.dll ''
Run test from System.Single, value -9.223372E+18 To System.UInt64with Op conv.u8 exception expected: False
Run test from System.Single, value -9.223372E+18 To System.UInt64with Op conv.ovf.u8 exception expected: True
Run test from System.Single, value -2.1474836E+09 To System.UInt64with Op conv.ovf.u8.un exception expected: True
Run test from System.Single, value 0 To System.UInt64with Op conv.ovf.u8.un exception expected: True
No exception in DynamicConvertFromSystem.SingleToSystem.UInt640Opconv.ovf.u8.un <- wrong
Test Simple value is 0, f1 is 0 <- wrong

seandree@seandreemac TestConvertFromIntegral % export COMPlus_JitDoValueNumber=0
seandree@seandreemac TestConvertFromIntegral % ./TestConvertFromIntegral.sh
BEGIN EXECUTION
/Users/seandree/git/runtime/artifacts/tests/coreclr/OSX.arm64.Checked/Tests/Core_Root/corerun TestConvertFromIntegral.dll ''
Run test from System.Single, value -9.223372E+18 To System.UInt64with Op conv.u8 exception expected: False
Run test from System.Single, value -9.223372E+18 To System.UInt64with Op conv.ovf.u8 exception expected: True
Run test from System.Single, value -2.1474836E+09 To System.UInt64with Op conv.ovf.u8.un exception expected: True
Run test from System.Single, value -9.223372E+18 To System.UInt64with Op conv.ovf.u8.un exception expected: True
Test Simple value is -9.223372E+18, f1 is -9.223372E+18

```

found during work on https://github.com/dotnet/runtime/pull/56450.

It is not a minimum repro but if I replace `GenerateTest` body with something trivial it goes away, so I am not sure what happens there.

### PR DESCRIPTION
**Pull request by janvorli**
We were not unwinding the non-volatile floating point registers at all
(not transferring them between the CONTEXT and ucontext_t before and
after the unw_step). That causes crashes on arm64 Unix in some of
the tests since JIT now generates code that uses e.g. the D8 register
and a runtime code that was throwing an exception was using it too.

Close #56522

### CODE REVIEW

**Comment by sandreenko** [comment]
cc @echesakov @briansull  fix for the issue that we were looking at.

**Comment by sandreenko** [comment]
Could you please delete this as well:
https://github.com/dotnet/runtime/blob/b69069588c452e62f6314785e4edfbdd2bc4e88d/src/tests/JIT/IL_Conformance/Convert/TestConvertFromIntegral.csproj#L10-L20
it was a workaround for this issue.

**Comment by janvorli** [comment]
I haven't noticed that the libunwind on Linux uses V instead of D in the UNW_AARCH64_* constants. Fixing it now.

**Comment by janvorli** [comment]
> Could you please delete this as well:

Done

**Comment by davidwrighton** [comment]
How is it that we don't need to unwind the saved floating point registers on other architectures like ARM and X64?

**Comment by sandreenko** [comment]
> How is it that we don't need to unwind the saved floating point registers on other architectures like ARM and X64?

The test is failing on arm Linux but only in JitStress that I was not checking while merging (I ran only outerloop) there.
Based on the output it is the same problem there:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-be4915f89d4c4f0a9b/JIT.IL_Conformance/1/console.41ed0c51.log?sv=2019-07-07&se=2021-08-24T05%3A11%3A46Z&sr=c&sp=rl&sig=R7YcMBEMOZeOZEGlbEAGCkhSNfRsqWmyPxCw4H4Y89A%3D
```
      No exception in DynamicConvertFromSystem.SingleToSystem.UInt640Opconv.ovf.u8
      No exception in DynamicConvertFromSystem.SingleToSystem.UInt640Opconv.ovf.u8.un
```
but without stress testing we don't allocate d8.

**Comment by janvorli** [comment]
x64 Unix ABI doesn't have any non-volatile floating point registers. But for arm, it seems we will need the same fix.

**Comment by janvorli** [comment]
Interestingly, the Linux arm64 has now many legs failing with this change. I am investigating ...

**Comment by briansull** [comment]
And what about ARM64 Windows?
Do we save the non-volatile floating point registers, or is this fix only for Linix/PAL

**Comment by janvorli** [comment]
> And what about ARM64 Windows?

This is need for Unix. On Windows, unwinding is done using the OS.

**Comment by briansull** [comment]
It is odd that we are just now noticing this, as the JIT will often use the non-volatile floating point registers.
I guess that an exception has to be thrown and caught, for the corruption to occur.  Maybe that test case is rare/missing.

**Comment by janvorli** [comment]
> It is odd that we are just now noticing this

It is also needed to modify a non-volatile FP register in the native code that throws the exception that's propagated to managed code. So I guess the C++ compiler just started doing that at some places.

**Comment by janvorli** [comment]
Bummer. Libunwind doesn't support unwinding floating point registers on ARM.

**Comment by am11** [comment]
> Bummer. Libunwind doesn't support unwinding floating point registers on ARM.

(maybe the future minipal can share [mono's unwind implementation](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/mono/mono/mini/mini-unwind.h) so we can get rid of no-gnu libunwind dependency altogether 🙂)

**Comment by janvorli** [comment]
@am11 IIRC, the mono unwind library is just very minimal one supporting only what mono generates. We need to be able to unwind whatever C++ compiler decides to generate.

**Comment by am11** [comment]
> We need to be able to unwind whatever C++ compiler decides to generate.

@janvorli, in this case, would it make more sense to use the unwinder from one of the compiler toolchain? If llvm's libunwind is missing context pointers support, and pinning is an option in GC (as used for macOS and FreeBSD, btw, both of which actually use llvm's libunwind), would it cause a significant degradation in quality? In 2013, I think Apple opensourced their system unwinder to llvm and it became llvm libunwind.

I am asking because nognu libunwind does not have many consumers and lacks proper/decicated maintainership. In Debian, only three (1,2,3 not 3% 🙂) packages depend on nognu libunwind and even they have option to switch to other unwinders. Distro maintainers of nognu libunwind package, as far as I know (Alpine, Gentoo, Debian/Ubuntu) are not really thrilled about the fact it has longstanding unresolved bugs and [the fact that it is complicated implementation and tries to do many things](https://lists.llvm.org/pipermail/cfe-dev/2016-September/050649.html). On the other hand, the compiler toolchains dogfood on their unwinder implementation and they keep the implementation up to date.

**Comment by janvorli** [comment]
Unfortunately, the LLVM libunwind has one significant deficiency - it doesn't support `unw_get_save_loc` which is important for our GC performance. When GC needs to update a reference to an object in some call frame in the middle of a stack and the reference is in a non-volatile register, it needs to know where the register was later saved so that it can update the reference in that stack slot. Later on when the code execution returns to that frame, the reference is then restored to the correct updated value. 
When we cannot get the save location for a register (like on macOS where we use their libunwind), we cannot relocate any objects that are referenced by non-volatile registers in the whole stack. That makes those effectively pinned, which increases fragmentation of the GC heap and can prevent its shrinking.

**Comment by janvorli** [comment]
Actually, I have forgotten to mention that it is related to the cases when we actually unwind using the libunwind, which excludes unwinding from managed code frames. So the problem I have mentioned only occurs on native / managed boundaries.

**Comment by janvorli** [comment]
In the past, I was already thinking about adding support for the unw_get_save_loc to the LLVM libunwind and after taking a brief look, it seemed it would not be that complicated. However, I think would add small penalty to all unwind operations, so I am not sure how difficult it would be to get such a change into the upstream libunwind.

As for how to solve the current problem for ARM, I can see several approaches:
* Disable using the VFP registers in the whole native runtime for Linux ARM (compiler option `-mfpu=none` or `-mfloat-abi=soft`). 
* Fix the current libunwind to support unwinding the floating point registers. I have no idea yet how complicated that would be, I assume comparing arm and arm64 stuff in the libunwind would give some hints.
* Prevent JIT from using non-volatile D8..D15 on Unix ARM. I have no idea how complicated that would be.
* Migrate to the LLVM libunwind and either add support for unw_get_save_loc or live with the issue around some of the objects  being effectively pinned as I've described before.

**Comment by janvorli** [comment]
Hmm, looking at our libunwind, there seems to be actually support for floating point unwinding, just the unw_context_t doesn't contain the FP regs. I need to understand it better then. There is a concept of context and cursor in the libunwind. It seems that the context is used for the initialization while the cursor for walking the stack. So there is a chance that the fix would be easy.

**Comment by am11** [comment]
> just the unw_context_t doesn't contain the FP regs.

A few related commits were not included in v1.5:
* https://github.com/libunwind/libunwind/commit/535f86a7c8b2345a1d50259673e88ee806108c2e
* https://github.com/libunwind/libunwind/commit/f8327f50be0413357816c2a41348455af476b9e5
* https://github.com/libunwind/libunwind/commit/0e7f74fad9cee71164c4face63c26885ecc43bd3
* https://github.com/libunwind/libunwind/commit/13f62c917e1d725162362dd6439becee2e5f3e08
* https://github.com/libunwind/libunwind/commit/5df1555828add4e256cb4bba49fffffc22127c34
* https://github.com/libunwind/libunwind/commit/556dec4e2fa1e8a54f71ffef7996fbb1bebc779f

Can we take their latest master (https://github.com/libunwind/libunwind/commit/c720133faa27293a0e8e075ddf9ccefa55a2efa1) and try out if it solves problems? There were some fixes for x86 and x64 since the last release as well.

**Comment by janvorli** [comment]
I have looked at the main branch there before and the context still didn't have the FP registers for ARM.

**Review by davidwrighton — APPROVED** [review]
Fix looks good now. I've opened an issue to track fixing this on arm32.

**Pull request merged**
