### PR TITLE
Fix ref counting in ComWrappers tests

### LINKED ISSUE #35349: Verify that GC handle leak in Interop\COM\ComWrappers\API\ComWrappersTests is a test issue
When running the Interop\COM\ComWrappers\API\ComWrappersTests test inside of an unloadable context, I have found that the context unload has failed. It was due to 1000 strong GC handles created here:
https://github.com/dotnet/runtime/blob/d449e51afb1df7e3f8e70cbc1d4fab7f87f27294/src/coreclr/src/vm/interoplibinterface.cpp#L561

We should verify that this is a test issue and not a real problem in the relatively new feature.

### PR DESCRIPTION
**Pull request by elinor-fung**
Fixes https://github.com/dotnet/runtime/issues/35349

cc @AaronRobinsonMSFT @jkoritzinsky

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
I'll go start the pipeline on the AzDO side. (I wish the bot would let you run pipelines manually even when they're excluded)

**Comment by jkoritzinsky** [comment]
Looks like you beat me to it :smile:

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by elinor-fung** [comment]
Failures are unrelated. The ComWrappers test ran and passed in the runincontext pipeline.

**Pull request merged**
