### PR TITLE
Implement native GetModuleIndex

### LINKED ISSUE #34920: CoreCLR should error if `clr.buildtools` are not built and you try to build a subset that is dependent of that
Right now if I do: `build clr.runtime` I get a native error... something like:
> Generating DAC module index file -> C:/repos/runtime/artifacts/obj/coreclr/Windows_NT.x64.Release/src/inc/dacmoduleindex.h
  C:\Program Files\dotnet
  Specify which project file to use because this 'C:\repos\runtime\artifacts\obj\coreclr\Windows_NT.x64.Release\src\dlls\mscordac' contains more than one project file.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(231,5): error MSB6006: "cmd.exe" exited with code 1. [C:\repos\runtime\artifacts\obj\coreclr\Windows_NT.x64.Release\src\d
lls\mscordac\dac_module_index_header.vcxproj]

It turns out this is because we introduced the `GetModuleIndex` tool which the `clr.runtime` build depends on. I think we should error out just like we do in other subsets if the `clr.buildtools` subset is not built and we try to build a dependent subset so that the errors are more clear and easier to fix. 

Also, as a side note, since this are local tools, why do we have to build them as a subset manually if we just want to build one piece of coreclr. I think we should follow what we do with other local tools that are built always unless a semaphore file is there:
https://github.com/dotnet/runtime/blob/42183b1b86656a348e0b6af7fa7c75072865f759/Build.proj#L40

cc: @dotnet/runtime-infrastructure

### PR DESCRIPTION
**Pull request by janvorli**
This change replaces managed GetModuleIndex tool by shell scripts using
native tools.

Close #34920

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by mikem8361** [comment]
Thanks Jan for doing this. 

Should the "clr.buildtools" subset be removed now (eng\subsets.props) and the line in eng\pipelines\coreclr\templates\build-job.yml that builds it? And the GetModuleIndex tool source?

I can do that clean if you want.

**Review by mikem8361 — APPROVED** [review]
Look good. Thanks Jan for doing this.

**Comment by janvorli** [comment]
> Should the "clr.buildtools" subset be removed now

Ah, I knew I have forgotten something. Thank you for reminding me that. I'll add the cleanup to this PR.

**Comment by janvorli** [comment]
@mikem8361 I've removed the clr.buildtools stuff, can you please take a look one more time to make sure I've not forgotten anything?

**Comment by mikem8361** [comment]
Some minor things that shouldn't be needed anymore. They are not that important to remove.

eng/Versions.props line 80: remove \<MicrosoftFileFormatsVersion\>1.0.120601\</MicrosoftFileFormatsVersion\>

src/coreclr/CMakeLists.txt line 28: remove CLR_DOTNET_COMMAND cmake property

**Comment by janvorli** [comment]
> src/coreclr/CMakeLists.txt line 28: remove CLR_DOTNET_COMMAND cmake property

I've done that already.
I've pushed one more commit to remove the eng/Versions.props line 80.

**Comment by mikem8361** [comment]
Thanks Jan.  Looks good.

**Pull request merged**
