### PR TITLE
[browser] ENVIRONMENT_IS_WEB is also true on WebWorker

### LINKED ISSUE #91528: [browser] ENVIRONMENT_IS_WEB is false when dotnet started on worker, leads to exit(0)
### Description

Hi,
I am facing a weird crash when using .NET 8 Latest Preview for targeting WASM Browser (AOT build).
The bug is observed in the following conditions.
The bug came out while benchmarking the performance of JS  and .NET AOT Wasm.
When running a React Application, that uses web workers.
The idea is to let user select a file and to compress it using .NET WASM code.
Because this is a heavy task, a web worker is used to delegate the task to .NET WASM compression layer.
The Web App works fine with small files < 5MB.
But If we chose to go with larger files, the compression still succeeds (ofc until we hit OOM) but the .NET runtime exits abruptly with the following weird stack trace if we use files >`10MB`

### Reproduction Steps

A repository to reproduce the issue is can he found here [dotnet-wasm-react](https://github.com/Tarun047/dotnet-wasm-react).

Inorder to reproduce this issue, 
1. Have the .NET 8.0.100-preview.7.23376.3 SDK and also install the wasm-tools, wasm-experimental workloads.

2. Checkout the repository and perform the following actions:
Publish the `compress.csproj` by running
`dotnet publish -c Release`
Copy the outputs of `/bin/Release/net8.0/browser-wasm/AppBundle/` to `compressy-frontend/public/vendor`

3. From the `compressy-frontend` folder,
 Install `npm` dependencies by running `npm install` and start the `webpack` dev server  by running `npm run dev`

4.  Use a browser and navigate to `http://localhost:8080` and keep the browser `console` window in browser `dev tools` open select the `choose file` button next to `WASM .NET Compress` and select any large file (>`10MB` preferably) in file chooser.

5. check the `console` output for failure stack trace.

### Expected behavior

The .NET WASM AOT runtime does not abruptly exit.

### Actual behavior

The .NET WASM AOT Run time exits with following weird stack trace which I suspect is due to a possible stack corruption.

```
[Error] MONO_WASM: {"name":"ExitStatus","message":"Program terminated with exit(undefined)","stack":
"H@http://localhost:8080/vendor/_framework/dotnet.js:3:9846
@http://localhost:8080/vendor/_framework/dotnet.runtime.js:3:203721
_proc_exit@http://localhost:8080/vendor/_framework/dotnet.native.js:8:73946
exitJS@http://localhost:8080/vendor/_framework/dotnet.native.js:8:74058
maybeExit@http://localhost:8080/vendor/_framework/dotnet.native.js:8:89407
Ko@http://localhost:8080/vendor/_framework/dotnet.runtime.js:3:56101
callUserCallback@http://localhost:8080/vendor/_framework/dotnet.native.js:8:89507
@http://localhost:8080/vendor/_framework/dotnet.native.js:8:89634","silent":true}
	l (dotnet.js:3:673)
	(anonymous function) (dotnet.js:3:10723)
	H (dotnet.js:3:10910)
	(anonymous function) (dotnet.runtime.js:3:203722)
	_proc_exit (dotnet.native.js:8:73947)
	exitJS (dotnet.native.js:8:74059)
	maybeExit (dotnet.native.js:8:89408)
	Ko (dotnet.runtime.js:3:56102)
	callUserCallback (dotnet.native.js:8:89508)
	(anonymous function) (dotnet.native.js:8:89635)
```

### Regression?

The issue doesn't happen in .NET 7 WASM AOT builds

### Known Workarounds

I haven't found a way to make this work

### Configuration

Version: .NET 8.0.100-preview.7.23376.3
OS: Reproducible on Mac OS X, Windows.
Architecture: ARM64, X64
Browsers: Safari, Firefox, Chrome

### Other information

_No response_

### PR DESCRIPTION
**Pull request by pavelsavara**
`ENVIRONMENT_IS_WEB` impacts `noExitRuntime` among other things.

Fixes https://github.com/dotnet/runtime/issues/91528

This may need Net8 backport

### CODE REVIEW

**Review by ilonatommy — APPROVED** [review]

**Comment by pavelsavara** [comment]
In MT build, when we are on worker, does `noExitRuntime` need to stay `false` ?

@lambdageek

**Comment by lambdageek** [comment]
> In MT build, when we are on worker, does `noExitRuntime` need to stay `false` ?
> 
> @lambdageek

yes I think so

**Comment by pavelsavara** [comment]
All failures are known and linked above.

**Pull request merged**
