### PR TITLE
Remove unnecessary spills from BufferedStream.ReadAsync

### PR DESCRIPTION
**Pull request by stephentoub**
Saves a field in each state machine.

### CODE REVIEW

**Review by adamsitnik — APPROVED** [review]
LGTM, however I wish our compiler could optimize that for us.

**Comment by adamsitnik** [comment]
the failures are unrelated, I am merging

**Comment by stephentoub** [comment]
> I wish our compiler could optimize that for us.

For the most part this is by design: to maintain order of operations, if you have `A() + await B()` the compiler has to evaluate `A()` first, at which point it has to store the result somewhere across the await.  In this constrained case, where `A()` is actually a local whose address is never exposed, isn't passed by ref, isn't captured by a closure, etc., it could probably avoid it, and for that I opened https://github.com/dotnet/roslyn/issues/54629.  But it's also possible the rewards from such a constrained optimization are limited (e.g. these were the only two occurrences in product code of `+ await` in all of dotnet/runtime), and there may be reasons why even for this case the compiler might face correctness issues.

**Comment by adamsitnik** [comment]
@stephentoub thanks!

**Pull request merged**
