### PR TITLE
[browser] move files around

### PR DESCRIPTION
**Pull request by pavelsavara**
Introducing directories 
- `core`
- `jiterpreter`
- `interop`

and moving TS files into them.

### CODE REVIEW

**Comment by campersau** [comment]
I guess this is going to conflict with #91699

**Comment by pavelsavara** [comment]
> I guess this is going to conflict with #91699

It was not that bad :)

**Comment by maraf** [comment]
What about splitting the code by module?
- runtime
  - diagnostics
  - jiterpreter
  - ...
- loader
  - run.ts
  - ...
- emscripten
  - dotnet.lib.js
  - dotnet.pre.js
  - ...

What about moving typescript/js code to a separate folde (like client/client-side)?

**Comment by pavelsavara** [comment]
> What about splitting the code by module?

That's exactly the idea, and we could do better than I did so far.

I did `core` for `dotnet.runtime.js` because I didn't like `runtime/runtime`  folder. We could rename the outer folder.

Rename of `es6` to `emscripten` is good idea, I forgot about that. But maybe we could do `native` instead.

**Comment by pavelsavara** [comment]
I need to work on something else ... maybe later

**Pull request closed without merging**
