### PR TITLE
HostFactoryResolver - Increase default timeout and add env var option

### PR DESCRIPTION
**Pull request by maryamariyan**
#### Customer Impact

When customer has debugger attached or when using tools like EF migration, host startup path using `WebApplicationBuilder` for hosting and `WebApplicationFactory<T>` for testing, may fail to build and throw an `InvalidOperationException` with the message “Unable to build IHost.”, because the default timeout is only 5 seconds.

We are proposing to use a higher timeout (5 minute) to be used so that when an application is taking longer to build, we could allow startup code to complete, and the host can start successfully. Check comment here for more detail.

Increasing the timeout should not have a negative impact on experience.

We also added an environment variable option called `DOTNET_HOST_FACTORY_RESOLVER_DEFAULT_TIMEOUT_IN_SECONDS` in case user needs to set their own custom timeout.

See issue: https://github.com/dotnet/runtime/issues/60891 

#### Testing

Check PR https://github.com/dotnet/runtime/pull/61621

#### Risk

Very low.

#### Regression

No, new 6.0 feature/code flow for discovering a host

cherry pick of https://github.com/dotnet/runtime/pull/61621

### CODE REVIEW

**Review by safern — CHANGES_REQUESTED** [review]
We need packaging changes. See: https://github.com/dotnet/runtime/commit/39ecea66f01371e9a8af3169a02a63f916e54217#diff-c7518d66e82e24aa3bb3bcf33bfa8717242e02d446983237f6ae56602785fde6R12 for an example.

Make sure that the package is created locally when building all configurations leg.

**Comment by eerhardt** [comment]
> We need packaging changes.

I'm not sure if it matters, but this package isn't a traditional library package.

1. It is a "source-only" package
2. It isn't shipping on nuget.org. It is only created for other teams (like EF) to consume.

Hopefully that doesn't change how we service this package, but I just wanted to call that out.

**Comment by safern** [comment]
Thanks, @eerhardt for calling that out.

I'm not sure how we build source packages, but I believe we still need the `GeneratePackageOnBuild` set to `true` in order for the servicing builds to generate the package. Just looked at the latest release/6.0 official build and it didn't produce this package at all. 

I would still bump the servicing version even though it doesn't land on NuGet.org as that helps reason about versions even for internal consumption, i.e aspnet transport packages also get that patch version bumped.

**Comment by ericstj** [comment]
> I would still bump the servicing version

Looks like this happens automatically for this package.

**Comment by ericstj** [comment]
> Looks like this happens automatically for this package.

Or perhaps that's the default unless you specify `ServicingVersion`.  In which case we should specify it.  Aside: I wonder if we can enforce this in servicing so that folks don't accidentally miss it.

**Review by Anipik — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Comment by safern** [comment]
Tests are definitely unrelated. I will open issues for them.

**Pull request merged**
