### PR TITLE
JIT: synthesize PGO if no schema, when dynamic PGO is active

### PR DESCRIPTION
**Pull request by AndyAyersMS**
If we know dynamic PGO is active, and we do not find a PGO schema for a method, synthesize PGO data. The schema may be missing if the method was prejitted but not covered by static PGO, or was considered too simple to need profiling (aka minimal profiling).

This synthesis removes the possibility of a mixed PGO/no PGO situation. These are problematic, especially in methods that do a lot of inlining. Now when dynamic PGO is active all methods that get optimized will have some form of PGO data.

Contributes to #93020.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL
cc @dotnet/jit-contrib

Fairly large number of diffs in PGO scenarios, mostly changes in inlining decisions. Hopefully these are a bit less arbitrary than before.

**Review by EgorBo — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
There should be no TP impact to minopts, not sure what's going on there.

**Comment by AndyAyersMS** [comment]
Must be doing some wasted work -- let me dig in

image

**Comment by AndyAyersMS** [comment]
Will run some stress on this once it gets farther along.

**Comment by AndyAyersMS** [comment]
Libraries-jitstress failures are https://github.com/dotnet/runtime/issues/101721

**Comment by AndyAyersMS** [comment]
One jitstress OSX leg hit a CI issue, going to ignore this.

**Pull request merged**
