### PR TITLE
[Android] Enable ThreadPoolCanPickUpOneOrMoreWorkItemsWhenThreadIsAvailable test

### LINKED ISSUE #43754: ThreadPoolCanPickUpOneOrMoreWorkItemsWhenThreadIsAvailable test failure on Android
```
Assert.True() Failure\nExpected: True\nActual:   False

Stack trace
   at System.Threading.Tests.ThreadTestHelpers.CheckedWait(WaitHandle wh) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 153
   at System.Threading.ThreadPools.Tests.ThreadPoolTests.ThreadPoolCanPickUpOneOrMoreWorkItemsWhenThreadIsAvailable() in /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs:line 608
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

### PR DESCRIPTION
**Pull request by steveisok**
Fixes https://github.com/dotnet/runtime/issues/43754

### CODE REVIEW

**Review by mdh1418 — APPROVED** [review]
It looks like the test suite crashed previously based on https://github.com/dotnet/runtime/issues/43754#issuecomment-814350045. Once we double check that the test suite runs and this test indeed passes, looks good!

**Comment by mdh1418** [comment]
Looks like this test fails on just Android emulators

**Comment by mdh1418** [comment]
@akoeplinger Does the change to handle when there is 1 core look good to you?

**Review by naricc — APPROVED** [review]

**Pull request merged**
