### PR TITLE
[HTTP/SSL] Fix stress

### LINKED ISSUE #91672: Http/SslStress builds failing on main
The build failures started on the 1st of September: https://dev.azure.com/dnceng-public/public/_build/results?buildId=393119&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=ebe1360c-fe50-5ebc-628a-48ef9bf66506

### PR DESCRIPTION
**Pull request by ManickaP**
Fixed docker ignore, updated stress images, fixed some minor warnings.
Fixes #91672

### CODE REVIEW

**Review by antonfirsov — APPROVED** [review]
Thanks a lot! LGTM, assuming the CI builds succeed.

**Comment by ManickaP** [comment]
Stress tests are running, failures are : #93204

**Pull request merged**
