### PR TITLE
Fix `Item4` is missing in some `ValueTuple`s' `IStructuralEquatable.Equals`

### LINKED ISSUE #91457: Item4 is missing in some `ValueTuple`s' `IStructuralEquatable.Equals`
### Description

Some `ValueTuple`s' `IStructuralEquatable.Equals` methods skip comparing Item4.

https://github.com/dotnet/runtime/blob/91ac6b3544d53fcf9e6962575813c1cd54aa27bd/src/libraries/System.Private.CoreLib/src/System/ValueTuple.cs#L1123-L1128

Search `vt.Item3) &&` in that file to find more.

### Reproduction Steps

```csharp
using System.Collections;

IStructuralEquatable a = ValueTuple.Create(1, 2, 3, 4, 5);
IStructuralEquatable b = ValueTuple.Create(1, 2, 3, 0, 5);

Console.WriteLine(a.Equals(b, EqualityComparer<object>.Default));
await Task.Delay(-1);
```

### Expected behavior

False

### Actual behavior

True

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by hamarb123**
Fixes #91457

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
Thanks!

**Comment by stephentoub** [comment]
@jeffhandley, we should backport this to release/8.0.

**Comment by EgorBo** [comment]
> @jeffhandley, we should backport this to release/8.0.

It seems that it was introduced in net6.0 so do we need to backport it to 6.0 and 7.0 as well?

**Comment by jeffhandley** [comment]
With the potential for data loss that could occur in customers' applications, I do think we should backport this to 6.0 and 7.0 too.

**Review by jeffhandley — APPROVED** [review]

**Comment by jeffhandley** [comment]
@dotnet/compat -- Do you have any compatibility concerns with the 6.0 and 7.0 backports of this functional fix? It's clearly a behavioral change for the better, but could there be any surprises for customers when the patch goes through?

**Comment by Junjun-zhao** [comment]
Adding @marklio @PriyaPurkayastha for more comments.

Is this fix merged into the latest .NET 8 RC2 build? We conducted a test pass with the latest build dotnet-sdk-8.0.100-rc.2.23456.6, and no related issues were found till now.

**Pull request merged**
