### PR TITLE
Change LSRA to more efficiently initialize the availableRegs array

### PR DESCRIPTION
**Pull request by tannergooding**
This was noticed in https://github.com/dotnet/runtime/pull/82731#discussion_r1129794470 and should provide a minor improvement since it will just linearly initialize the data without needing to do any checks.

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @dotnet/jit-contrib, @kunalspathak 

Some nice TP wins: https://dev.azure.com/dnceng-public/public/_build/results?buildId=206256&view=ms.vss-build-web.run-extensions-tab

### Windows X64
```
Overall (-0.05% to -0.02%)
MinOpts (-0.28% to -0.03%)
FullOpts (-0.05% to -0.01%)
```

### Windows Arm64
```
Overall (-0.03% to -0.01%)
MinOpts (-0.13% to -0.02%)
FullOpts (-0.03% to -0.01%)
```

Linux is similar numbers.

**Comment by kunalspathak** [comment]
LGTM...surprisingly it showed TP win given that this is only used in constructor. Also, may be not worth another commit, but I would change the name of variable from `lsra` to `availableRegisters`.

**Review by kunalspathak — APPROVED** [review]

**Comment by tannergooding** [comment]
> surprisingly it showed TP win given that this is only used in constructor

I've noticed that almost any change to LSRA can have significant impact on TP, more so than almost any other phase.

My hypothesis is that even though this constructor is only called once, it's doing such a significant amount of "more work" than most other phases (there are many methods which are only 1-5 opcodes). It being required for every single method and that coupled with T0 being the default and so no other optimizations being typically done makes LSRA one of the most perf critical points.

> but I would change the name of variable from lsra to availableRegisters

I tried to go with some short name so as to not deviate from the other names in the macro and picked something that wasn't likely to conflict with any other local/field in the scope

**Comment by jakobbotsch** [comment]
> surprisingly it showed TP win given that this is only used in constructor

We did see that this was hot already in the measurements at https://github.com/dotnet/runtime/pull/76850#issuecomment-1376771783. That's why I had similar suggestion to improve this loop there.

**Pull request merged**
