### PR TITLE
Compile methods in canon form only 

### PR DESCRIPTION
**Pull request by davidwrighton**
- The previous logic would compile methods that were not in canonical form
- These methods would never be used by the runtime, and contributed 70MB to a 170MB composite image

Also a small fix to an assertion so that debug builds work well

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/crossgen-contrib

**Review by trylek — APPROVED** [review]
Wow, awesome improvement, thanks David!

**Comment by EgorBo** [comment]
Does it mean the SDK size will be significantly smaller? (and `dotnet publish` result)?

**Comment by davidwrighton** [comment]
@EgorBo, this is an improvement to crossgen2, which is expected to replace crossgen in the future. So, this isn't expected to have an impact on size in the .NET 5 timeframe, as we're not using this tool for any customer scenarios yet.

**Review by nattress — APPROVED** [review]
Nice!

**Pull request merged**
