### PR TITLE
Mark operands of non-RMW as delayFree 

### LINKED ISSUE #56967: Illegal encoding for AVX2 Gather instructions
### Description

Sometime between net6.0 preview 5 and preview 6, the codegen for AVX2 gather instructions changed, presumably to eliminate what might have appeared to be redundant reg/reg moves.  This has resulted in an illegal instruction encoding where the index and destination registers are the same.  As stated in the Intel developer manual for `vpgatherdd`: 

> If any pair of the index, mask, or destination registers are the same, this instruction results a UD fault.

### Quick Repro

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net5.0;net6.0</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TieredCompilation>false</TieredCompilation>
  </PropertyGroup>
</Project>
```

```c#
using System;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

class Program
{
    static unsafe void Main()
    {
        int* values = stackalloc int[256];
        var vmsk = Vector256.Create(-1, -1, -1, 0, -1, -1, -1, 0);
        var vlu1 = Vector256.Create(0, 1, 2, 3, 4, 5, 6, 7);
        var vlu2 = Vector256.Create(7, 6, 5, 4, 3, 2, 1, 0);

        vlu1 = Avx2.GatherMaskVector256(vlu1, values, vlu1, vmsk, sizeof(int));
        vlu2 = Avx2.GatherMaskVector256(vlu2, values, vlu2, vmsk, sizeof(int));

        Console.WriteLine(vlu1);
        Console.WriteLine(vlu2);
    }
}
```

### Regression?

Yep.

```
:>dotnet run -c release -f net5.0
<0, 0, 0, 3, 0, 0, 0, 7>
<0, 0, 0, 4, 0, 0, 0, 0>

:>dotnet run -c release -f net6.0
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Program.Main()
```

Gather codegen for net5.0

```asm
vmovaps     ymm1,ymm0  
vmovaps     ymm2,ymm6  
vpgatherdd  ymm2,dword ptr [rcx+ymm6*4],ymm1  
vmovaps     ymm6,ymm2  
vmovaps     ymm1,ymm0  
vmovaps     ymm2,ymm7  
vpgatherdd  ymm2,dword ptr [rcx+ymm7*4],ymm1  
vmovaps     ymm7,ymm2  
```

And for net6.0

```asm
vmovaps     ymm1,ymm0  
vpgatherdd  ymm6,dword ptr [rcx+ymm6*4],ymm1  'eek
vmovaps     ymm1,ymm0  
vpgatherdd  ymm7,dword ptr [rcx+ymm7*4],ymm1  
```

### Other information

Interestingly, both debug and checked builds of JIT from current main generate good code.  Only getting the failure with release JIT.  The codegen was fine up through net6.0 preview5 and first blew up in preview 6.

### PR DESCRIPTION
**Pull request by kunalspathak**
For non-RMW intrinsics like `NI_AVX2_GatherVector256` and `NI_AVX2_GatherMaskVector256`, there is no `rmwNode` involved and hence we should always mark the operand as `delayFree`. It was regressed by my change in https://github.com/dotnet/runtime/pull/53964.

No asm diffs

Fixes: https://github.com/dotnet/runtime/issues/56967

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by kunalspathak** [comment]
Can someone take a look so we can get this in before next week? @echesakov or @tannergooding

**Review by tannergooding — APPROVED** [review]

**Review by echesakov — APPROVED** [review]
Changes LGTM. @kunalspathak can you please check if there are any diffs?

**Comment by kunalspathak** [comment]
> Changes LGTM. @kunalspathak can you please check if there are any diffs?

Thanks @echesakov . I verified and there were no diffs in benchmarks/libraries.pmi/coreclr_tests collections.

**Pull request merged**
