### PR TITLE
Delete Windows arm32 support

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
Continuation of https://github.com/dotnet/runtime/pull/85947

**Comment by vcsjones** [comment]
`docs/workflow/README.md` "Build Requirements" should have the table updated to indicate ARM is not supported on Windows (and maybe change ARM to ARM32 so as not to be ambiguous).

**Comment by EgorBo** [comment]
Presumably we can also close all active win-arm32 [issues](https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+label%3Aarch-arm32) (not all of them have OS label)?

**Review by BruceForstall — APPROVED** [review]
LGTM.

Additional things to remove:
1. in root .vsconfig, presumably we can remove "Microsoft.VisualStudio.Component.VC.Tools.ARM"
2. remove "arm" case from src\coreclr\build-runtime.cmd
3. Remove win-arm32 cross-components builds case from eng\Subsets.props. I think that would be:
```
  <ItemGroup Condition="(('$(ClrRuntimeBuildSubsets)' != '' and '$(PrimaryRuntimeFlavor)' == 'CoreCLR' and '$(TargetsMobile)' != 'true') or $(_subset.Contains('+clr.crossarchtools+'))) and $([MSBuild]::IsOsPlatform(Windows)) and '$(TargetArchitecture)' == 'arm' and '$(BuildArchitecture)' == 'x64'">
    <ProjectToBuild
      Include="$(CoreClrProjectRoot)runtime.proj"
      AdditionalProperties="%(AdditionalProperties);
                            ClrCrossComponentsSubset=true;
                            HostArchitecture=x86;
                            PgoInstrument=false;
                            NoPgoOptimize=true;
                            CrossBuild=false;
                            CMakeArgs=$(CMakeArgs) -DCLR_CROSS_COMPONENTS_BUILD=1"
      Category="clr" />
  </ItemGroup>
```

**Comment by jkotas** [comment]
> Presumably we can also close all active win-arm32 [issues](https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+label%3Aarch-arm32) (not all of them have OS label)?

Yes, we have been closing win-arm32 issues as won't fix for a while now. If there are any still left, feel free to close them.

**Pull request merged**
