### PR TITLE
Add main branch to yml files

### PR DESCRIPTION
**Pull request by ViktorHofer**
**Part of March's batched infrastructure rollout: https://github.com/dotnet/runtime/issues/48168**

### CODE REVIEW

**Review by safern — COMMENTED** [review]
Isn't the best way to instead add the `-main` trigger, check that in, and after the rename just remove the `master` trigger?

**Comment by ViktorHofer** [comment]
How would that be better?

**Comment by safern** [comment]
I don't know how you think of doing it but we could end on a state where people once we rename the branch and all PRs are re-targeted that the trigger is not there and then we would need to go and trigger the builds on all PRs.

**Review by safern — APPROVED** [review]
Approving in case you rather do it in one PR to unblock merging this.

**Pull request merged**
