### PR TITLE
Reverts https://github.com/dotnet/corefx/pull/37583 ("Use clonefile for CopyFile, if available #37583")

### LINKED ISSUE #31429: File.Copy no longer respects FileShare.None on Linux/Mac in 5.0
Found this taking a new runtime into dotnet/sdk test run environment, as one of our tests started failing on Linux/Mac.

### Program.cs
``` C#
using System;
using System.IO;

class Program
{
    static void Main()
    { 
        File.WriteAllText("x", "x");
        File.WriteAllText("y", "y");

        using (var stream = new FileStream("y", FileMode.Open, FileAccess.Read, FileShare.None))
        {
            File.Copy("x", "y", overwrite: true);
        }
        
        Console.WriteLine("Success");
    }
}
```

### Repro.csproj
``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.0;netcoreapp5.0</TargetFrameworks>
  </PropertyGroup>
</Project>
```

### Repro steps
* dotnet run -f netcoreapp3.0
* dotnet run -f netcoreapp5.0

### Expected result
Both 3.0 and 5.0 fail with IOExceptions

### Actual result
Only 3.0 fails, 5.0 succeeds unexpectedly

#### 3.0 (fails as expected)

```/
Unhandled exception. System.IO.IOException: The process cannot access the file '/home/nicholg/src/sdk/q/y' because it is being used by another process.
   at System.IO.FileStream.Init(FileMode mode, FileShare share, String originalPath)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)      
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Program.Main()
```

#### 5.0 (succeeds unexpectedly)
```
Success
```

@stephentoub @JeremyKuhne

### PR DESCRIPTION
**Pull request by jozkee**
Fixes https://github.com/dotnet/runtime/issues/31429
We will bring back the reverted change on 6.0 and ensure that doesn't regress functionality

### CODE REVIEW

**Comment by carlossanlop** [comment]
cc @filipnavara

**Review by carlossanlop — COMMENTED** [review]
Thanks for making the change, @Jozkee. It looks good, let's wait for the CI results.

**Comment by carlossanlop** [comment]
The WASM CI leg failed with errors that seem related to this change:
```

[20:10:22] dbug: test[0]
      [FAIL] System.IO.Tests.FileInfo_CopyTo_str_b.CopyFileWithData(data: [], readOnly: False)
[20:10:22] dbug: test[0]
      [FAIL] System.IO.Tests.FileInfo_CopyTo_str_b.CopyFileWithData(data: [0x008f], readOnly: False)
[20:10:23] dbug: test[0]
      [FAIL] System.IO.Tests.FileInfo_CopyTo_str_b.CopyFileWithData(data: ['D', 'Â¢', 'Y', 0x009c, 'Ã©', ...], readOnly: False)
[20:10:23] dbug: test[0]
      [FAIL] System.IO.Tests.FileInfo_CopyTo_str_b.CopyFileWithData(data: ['Ã¶', 0x0080, '\r', 'Ã—', 'Ã–', ...], readOnly: False)
[20:10:27] dbug: test[0]
      [FAIL] System.IO.Tests.FileInfo_CopyTo_str_b.CopyFileWithData(data: ['3', 'F', 'ÃŽ', 0x008e, 0x000e, ...], readOnly: False)
...
...
```

**Comment by safern** [comment]
@steveisok this seems related to the tests we just enabled? Could you help @david here? Should we open an issue and disable the tests and then in 6.0 enable them once we have this fix in? cc: @lewing

**Comment by steveisok** [comment]
Hmm - I think something / somethings in copy may be broken with this change.  Unfortunately, we need to look closer to be able to tell.

**Comment by steveisok** [comment]
Actually, the failures are `Assert.InRange() Failure\r\nRange:  (08/13/2020 08:08:37 - 08/13/2020 08:08:39)\r\nActual: 08/13/2020 07:08:38`.  Is this branch behind master to some degree?

**Comment by Jozkee** [comment]
@steveisok I just merged with master but seems that the `Assert.InRange` failure persists.

A new test added on this PR also fails for wasm:
```
[22:39:38] dbug: test[0]
      [FAIL] System.IO.Tests.File_Copy_Single.EnsureThrowWhenCopyToNonSharedFile
      
[22:39:38] dbug: test[0]
      Assert.Throws() Failure
      
[22:39:38] dbug: test[0]
      Expected: typeof(System.IO.IOException)
      
[22:39:38] dbug: test[0]
      Actual:   (No exception was thrown)
```

Is this something that we could defer to RC2?
@danmosemsft @jeffhandley

**Comment by steveisok** [comment]
I say disable the tests and we can take a closer look.

**Review by carlossanlop — APPROVED** [review]

**Comment by Jozkee** [comment]
Current CI issues are unrelated:
https://github.com/dotnet/runtime/issues/40881
https://github.com/dotnet/runtime/issues/11063

**Pull request merged**
