### PR TITLE
Relax constructor type requirements

### PR DESCRIPTION
**Pull request by GabeDeBacker**
This change allows deserialization into object where it contains a member property (or field) whose type is "assignable" instead to the constructor type. This address some of the ideas mentioned in #44428.

Previously a class a simple as this would not "round trip" through System.Text.Json (which is a common pattern for applications using data binding to WPF/XAML, etc.)

```c#
public class ClassWithConstructorArgumentTypeThatIsAssignableFromImmutablePropertyType
{
   public ReadOnlyObservableCollection<int> Values { get; }
   private readonly ObservableCollection<int> valueCollection;
 
   public ClassWithConstructorArgumentTypeThatIsAssignableFromImmutablePropertyType(IEnumerable<int> values)
    {
        this.valueCollection = new ObservableCollection<int>(values);
        this.Values = new ReadOnlyObservableCollection<int>(this.valueCollection);
    }
}
```

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47661) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47661) before we can accept your contribution.<br/><br/>:x: GabeDeBacker [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47661)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=47661) it.</sub>

**Comment by ericstj** [comment]
@eiriktsarpalis @layomia can you have a look?

**Comment by ericstj** [comment]
Ping.  Reviewers, please have a look and provide next steps (other than rebase of course).

**Comment by layomia** [comment]
I chatted with @GabeDeBacker offline - I'll pick up the work here. Thanks for the effort!

**Pull request closed without merging**
