### PR TITLE
Fix libraries outerloop pipelines

### LINKED ISSUE #76755: outerloop legs failing to detect `dotnet`
Original issue was opened in dotnet/arcade: https://github.com/dotnet/arcade/issues/11185

Many outerloop legs fail with this message when attempting to run unit tests:

```
./RunTests.sh: line 168: /tmp/helix/working/A6B808E3/p/dotnet: No such file or directory
```

The investigation found that this may have been caused by a runtime change that happened between these two runs (from 8/2 to 8/3):

pr/public/dotnet/runtime/refs/pull/73300/merge
pr/public/dotnet/runtime/refs/pull/73020/merge

<details>
<summary>Kusto Query</summary>

```kusto
Jobs
| where QueueName == "osx.1200.amd64.open"
| extend Propz = parse_json(Properties)
| where Propz["DefinitionName"] == "runtime-libraries-coreclr outerloop"
| where Propz["System.PhaseName"] == "libraries_build_OSX_x64_Debug"
| order by Finished desc 
```
</details>

The main suspect PR is one that seeked to remove the host packages conditionally and was merged at a time between the above two PRs likely merge commits: https://github.com/dotnet/runtime/pull/73095/files

We need to confirm this issue caused the regression and get it fixed.

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/runtime/issues/76755

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Validation build: https://dnceng-public.visualstudio.com/public/_build/results?buildId=112228&view=logs&j=f77d05a1-f641-5087-dd31-1106f5b808d0

**Comment by ViktorHofer** [comment]
Rolling validation build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=112256&view=results

**Comment by ViktorHofer** [comment]
New validation rolling build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=112306&view=results

**Pull request merged**
