### PR TITLE
Remove deprecated build scripts.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
**No Merge. Part of batched rollout in May: https://github.com/dotnet/runtime/issues/35202**

Remove the deprecated CoreCLR build scripts (build.cmd/build.sh and build.proj).

We're removing these scripts because I keep catching people making infra changes only in these scripts and then have to point them to the scripts we use in CI so their changes are actually effective.

### CODE REVIEW

**Review by jashook — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Comment by safern** [comment]
Should we update any build defs that might be using these scripts?

**Comment by jkoritzinsky** [comment]
There should be no build definitions using these scripts, but if there are, they should be updated.

I've validated that the CoreCLR build and formatting jobs don't use these scripts, and the optimization team and source-build team have moved off of these scripts to my knowledge.

Tagging @dseefeld and @brianrob so they can let us know if they haven't moved off these scripts yet and won't be able to do so by May 4th.

**Comment by safern** [comment]
I asked cause I recalled seeing one, which just found, but I'm updating here: https://github.com/dotnet/runtime/pull/35011/files#diff-3672729464fb95f4293e8adfcbdbf3e6L11

**Comment by jkoritzinsky** [comment]
Right.... I totally forgot about the networking stress tests since they use a completely separate pipeline. Yeah we need to update those. I can go do that if you want.

**Comment by jkoritzinsky** [comment]
Actually, you're already fixing it, so that's covered then.

**Review by ViktorHofer — APPROVED** [review]

**Comment by brianrob** [comment]
I have moved optimization training off of these scripts.  Thanks for adding me here @jkoritzinsky.

**Pull request merged**
