### PR TITLE
Fix Http test failure because of Activity Id Format default change.

### LINKED ISSUE #38205: Test failure: Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
failed in job: [runtime-libraries outerloop 20200621.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=697688&view=ms.vss-test-web.build-test-results-tab&runId=21622464&resultId=103147&paneView=debug)

failed tests:
System.Net.Http.Functional.Tests.SocketsHttpHandler_DiagnosticsTest.SendAsync_ExpectedDiagnosticSourceActivityLogging_InvalidBaggage
System.Net.Http.Functional.Tests.SocketsHttpHandler_DiagnosticsTest.SendAsync_ExpectedDiagnosticSourceActivityLoggingDoesNotOverwriteHeader

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  System.AggregateException: One or more errors occurred. (Assert.False() Failure
Expected: False
Actual:   True)
 ---> Xunit.Sdk.FalseException: Assert.False() Failure
Expected: False
Actual:   True
   at System.Net.Http.Functional.Tests.DiagnosticsTest.<>c__DisplayClass14_0.<SendAsync_ExpectedDiagnosticSourceActivityLoggingDoesNotOverwriteHeader>b__1(KeyValuePair`2 kvp) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs:line 576
   at System.Net.Http.Functional.Tests.FakeDiagnosticListenerObserver.FakeDiagnosticSourceWriteObserver.OnNext(KeyValuePair`2 value) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/FakeDiagnosticSourceListenerObserver.cs:line 31
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value) in /_/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticListener.cs:line 262
   at System.Diagnostics.DiagnosticSource.StopActivity(Activity activity, Object args) in /_/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceActivity.cs:line 51
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs:line 129
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 533
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 471
   at System.Threading.Tasks.Task`1.get_Result() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 440
   at System.Net.Http.Functional.Tests.DiagnosticsTest.<>c.<SendAsync_ExpectedDiagnosticSourceActivityLoggingDoesNotOverwriteHeader>b__14_0(String useVersionString) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs:line 587

Child process:
  System.Net.Http.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.DiagnosticsTest+<>c Void <SendAsync_ExpectedDiagnosticSourceActivityLoggingDoesNotOverwriteHeader>b__14_0(System.String)

Child arguments:
  1.1
~~~

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/38205

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @stephentoub @noahfalk

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
Should I be concerned about this as an indication that the activity change is a larger breaking change than anticipated?

**Comment by tarekgh** [comment]
> Should I be concerned about this as an indication that the activity change is a larger breaking change than anticipated?

From what I am seeing is now storing more stuff as W3C Id format became a default. so I expect the breaking wouldn't be big in such cases (I guess). NCL may talk about this scenario better. 

CC @karelz who may loop other guys can talk about that. to get @karelz up to speed, we have changed the Activity Id default Format from Heiraracal to W3C, and Http logs more info in the harder when having W3C format (e.g. `transparent` and `tracestate` fields). we have a config switch to get back the old behavior if necessary. 

@noahfalk @shirhatti do you have any more input here?

**Comment by noahfalk** [comment]
Certainly there is some risk involved in making the breaking change, but this issue didn't change my assessment of it if that helps at all : )

**Comment by tarekgh** [comment]
The failures including the outerloop failures are not related. Also, this PR is addressed all Http test failures. I am going to merge this one.

**Pull request merged**
