### PR TITLE
[release/6.0] Fix KeepNativeSymbols to work on mono as well (backport of #66594)

### PR DESCRIPTION
**Pull request by ayakael**
Backport of https://github.com/dotnet/runtime/pull/66594

Per @omajid:
```
When packaging .NET on s390x through source-build, we want to keep debug
symbols enabled in the build. The package manager (debbuild, rpmbuild,
etc) generally strips the binaries to create distro-standard
-debug/-debuginfo packages. This was supported in coreclr via
--keepnativesymbols flag, but wasn't supported in mono (ie, s390x). Fix
that.
```
# Customer impact
Source-build with mono-flavored runtime is problematic without this patch.

# Testing
* unit tests in ci
* source-build build within Alpine environment passes

# Risk
Low, as it is already in `main`, and only activates when `KeepNativeSymbols!=true`

### CODE REVIEW

**Comment by carlossanlop** [comment]
@marek-safar @directhex this needs to go through Tactics. When/if this is ready, please add the `servicing-consider` label and send an email to Tactics requesting merge approval.

**Comment by carlossanlop** [comment]
@omajid @ayakael @directhex I see some CI failures that I haven't seen in any other backport PR. Are they related to this change? 

@directhex can you please provide a code review sign-off?

**Comment by ayakael** [comment]
> @omajid @ayakael @directhex I see some CI failures that I haven't seen in any other backport PR. Are they related to this change?
> 
> @directhex can you please provide a code review sign-off?

It really shouldn't be, as `KeepNativeSymbols` is really only used by `source-build` to memory, and the failures seem related to CoreCLR which this PR doesn't touch. Pushing a new rebase as to trigger another round of CI tests. Maybe it was just a fluke.

**Comment by carlossanlop** [comment]
Ping @directhex @marek-safar for a code review-sign off.

**Review by marek-safar — APPROVED** [review]

**Review by directhex — APPROVED** [review]

**Comment by carlossanlop** [comment]
CI failure confirmed offline to be unrelated. Signed off by area owners. Approved by Tactics. No OOB package authoring changes needed. Ready to merge. :shipit:

**Pull request merged**
