### PR TITLE
Fix crash in SuperPMI PGO apis

### PR DESCRIPTION
**Pull request by BruceForstall**
The real fix is a trivial fix in the linked list handling
of AllocJitTempBuffer.

The rest of the changes are making the code conform more to SuperPMI
conventions, adding comments, and improving SPMI dumping.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@kunalspathak @AndyAyersMS PTAL
cc @dotnet/jit-contrib

**Review by kunalspathak — APPROVED** [review]
Fix looks good to me. If you agree, can you also update the pipeline schedule to also trigger if there are any chances in `src\coreclr\ToolBox\superpmi\*`?

**Comment by BruceForstall** [comment]
> If you agree, can you also update the pipeline schedule to also trigger if there are any chances in src\coreclr\ToolBox\superpmi\*

I was thinking about this, and I decided not to do that: I don't want to force a re-collection on the potential to just fix a bug that doesn't require a re-collection. So, I'd prefer giving developers more choice and responsibility to "do the right thing" even if that means people might forget to do a collection when it would be required. Hopefully that doesn't bite us too often.

**Comment by kunalspathak** [comment]
> I was thinking about this, and I decided not to do that: I don't want to force a re-collection on the potential to just fix a bug that doesn't require a re-collection. So, I'd prefer giving developers more choice and responsibility to "do the right thing" even if that means people might forget to do a collection when it would be required. Hopefully that doesn't bite us too often.

Sure, so I guess what you are saying is if I just sync your SPMI changes, my existing SPMI collection should work. Makes sense.

**Comment by BruceForstall** [comment]
> so I guess what you are saying is if I just sync your SPMI changes, my existing SPMI collection should work.

That's not quite true: I changed the SPMI file format. However, I also changed the JIT/EE GUID, so if you pick up these changes, you need to wait until the triggered SPMI collection is published.

**Pull request merged**
