### PR TITLE
global.json: Bump sdk to 7.0.100-rtm.22476.1 to pick up a msbuild fix 

### PR DESCRIPTION
**Pull request by radical**
And remove the workarounds

### CODE REVIEW

**Comment by radical** [comment]
Should the `tools` version also be updated to match?

**Comment by marcpopMSFT** [comment]
@radical @lewing 7.0.1xx finally merged last night so there are now rtm builds with the msbuild change. Try 7.0.100-rtm.22478.12 maybe

**Comment by radical** [comment]
Builds failing with `Unable to find package Microsoft.NETCore.App.Ref with version (= 6.0.10)`:

```
System.Collections.Immutable.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 6.0.10) [/__w/1/s/Build.proj]
System.Collections.Immutable.csproj : error NU1102:   - Found 1552 version(s) in dotnet7 [ Nearest version: 7.0.0-alpha.1.21417.28 ] [/__w/1/s/Build.proj]
System.Collections.Immutable.csproj : error NU1102:   - Found 54 version(s) in dotnet-public [ Nearest version: 7.0.0-preview.1.22076.8 ] [/__w/1/s/Build.proj]
System.Collections.Immutable.csproj : error NU1102:   - Found 1 version(s) in dotnet-eng [ Nearest version: 5.0.0-alpha.1.19618.1 ] [/__w/1/s/Build.proj]
System.Collections.Immutable.csproj : error NU1102:   - Found 1 version(s) in dotnet7-transport [ Nearest version: 7.0.0-rc.1.22426.10 ] [/__w/1/s/Build.proj]
System.Collections.Immutable.csproj : error NU1102:   - Found 0 version(s) in richnav [/__w/1/s/Build.proj]
System.Collections.Immutable.csproj : error NU1102:   - Found 0 version(s) in dotnet-libraries [/__w/1/s/Build.proj]
System.Collections.Immutable.csproj : error NU1102:   - Found 0 version(s) in dotnet-tools [/__w/1/s/Build.proj]
```

**Comment by carlossanlop** [comment]
Added the no merge label for now. Please remove when ready.

**Comment by lewing** [comment]
@marcpopMSFT nothing that targets net6.0 can build with the implicit version bump in this sdk

**Comment by marcpopMSFT** [comment]
Can you override the implicit version in a directory.build.props file?  I can give you the rough logic that would do that. BTW, we have a new build that has additional msbuild changes: 7.0.100-rtm.22479.5

**Comment by marcpopMSFT** [comment]
Here's some code that Damien got to work in directory.build.targets
```
Project InitialTargets="HackTargetingPackBack">
  <PropertyGroup>
    <_Net60ServicingVersionOverride>6.0.8</_Net60ServicingVersionOverride>
  </PropertyGroup>
  <Target Name="HackTargetingPackBack">
    <ItemGroup>
      <KnownFrameworkReference>
        <TargetingPackVersion Condition="'%(TargetFramework)' == 'net6.0'">$(_Net60ServicingVersionOverride)</TargetingPackVersion>
        <LatestRuntimeFrameworkVersion Condition="'%(TargetFramework)' == 'net6.0'">$(_Net60ServicingVersionOverride)</LatestRuntimeFrameworkVersion>
      </KnownFrameworkReference>
      <KnownRuntimePack>
        <LatestRuntimeFrameworkVersion Condition="'%(TargetFramework)' == 'net6.0'">$(_Net60ServicingVersionOverride)</LatestRuntimeFrameworkVersion>
      </KnownRuntimePack>
      <KnownAppHostPack>
        <AppHostPackVersion Condition="'%(TargetFramework)' == 'net6.0'">$(_Net60ServicingVersionOverride)</AppHostPackVersion>
      </KnownAppHostPack>
      <KnownCrossgen2Pack>
        <Crossgen2PackVersion Condition="'%(TargetFramework)' == 'net6.0'">$(_Net60ServicingVersionOverride)</Crossgen2PackVersion>
      </KnownCrossgen2Pack>
    </ItemGroup>
  </Target>
</Project>
```

**Pull request closed without merging**
