### PR TITLE
[wasm] Add incremental build support

### LINKED ISSUE #51013: [wasm][aot] Incremental builds don't work correctly for AOT
In case of incremental builds, we should be rebuilding only the bits that changed.

### PR DESCRIPTION
**Pull request by radical**
- Adds Inputs/Outputs to wasm targets, which msbuild can use for dependency checking
- Updates tasks to write out to the files being used as inputs, only when there is a change

- MonoAOTCompiler:
  - Compiles assemblies to .bc files.
  - Hashes for the .bc files are stored in a json cache file.
  - mono-aot-cross is used to compile `.dll -> .bc.tmp`
  - And the actual `.bc` file is overwritten only if the generated one is different
  - note: the cache is optional. this can be changed to be required, if iOS/android also adopt it

- EmccCompile.cs: Support a `%(Dependencies)` metadata on the source
files, to compile the files only when needed.

- All the emcc args are written to rsp files, if different
  - and used as inputs/dependencies for the native output files

- Adds some tests
- Use msbuild's resource API, to request cores for building in parallel

- Also, updates the build output:

```
  Wasm.Console.Sample -> /Users/radical/dev/r2/src/mono/sample/wasm/console/bin/browser-wasm/publish/
  AOT'ing 7 assemblies
  [1/7] Wasm.Console.Sample.dll -> Wasm.Console.Sample.dll.bc
  [6/7] skipped unchanged assemblies.
  Compiling native assets with emcc. This may take a while ...
  Compiling assembly bitcode files...
  [1/1] Wasm.Console.Sample.dll.bc -> Wasm.Console.Sample.dll.o [took 0.612s]
  Linking with emcc. This may take a while ...
```

Fixes https://github.com/dotnet/runtime/issues/51013

### CODE REVIEW

**Comment by radical** [comment]
Splitting up the tests into separate jobs. So, disabled non-wasm jobs, to make sure that it's working.

**Comment by radical** [comment]
Ready for review

**Comment by lewing** [comment]
failure in runtime (Libraries Test Run checked coreclr windows x86 Release) is 
```
C:\h\w\A8F309AF\w\A8620915\e>"C:\h\w\A8F309AF\p\dotnet.exe" exec --runtimeconfig System.Diagnostics.Process.Tests.runtimeconfig.json --depsfile System.Diagnostics.Process.Tests.deps.json xunit.console.dll System.Diagnostics.Process.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Diagnostics.Process.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.Process.Tests (found 254 of 278 test cases)
  Starting:    System.Diagnostics.Process.Tests (parallel test collections = on, max threads = 4)
    System.Diagnostics.Tests.ProcessModuleTests.LongModuleFileNamesAreSupported [FAIL]
      Assert.Contains() Failure
      Not found: C:\h\w\A8F309AF\t\ProcessModuleTests_otibjh1e.nwu\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\LongPath.dll
      In value:  String[] ["C:\\h\\w\\A8F309AF\\p\\dotnet.exe", "C:\\Windows\\SYSTEM32\\ntdll.dll", "C:\\Windows\\System32\\KERNEL32.DLL", "C:\\Windows\\System32\\KERNELBASE.dll", "C:\\Windows\\System32\\ucrtbase.dll", ...]
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessModuleTests.cs(127,0): at System.Diagnostics.Tests.ProcessModuleTests.LongModuleFileNamesAreSupported()
    System.Diagnostics.Tests.ProcessStartInfoTests.ShellExecute_Nano_Fails_Start [SKIP]
      Condition(s) not met: "IsWindowsNanoServer"
Invalid number of parameters
0 File(s) copied
  Finished:    System.Diagnostics.Process.Tests
=== TEST EXECUTION SUMMARY ===
```

**Comment by lewing** [comment]
created https://github.com/dotnet/runtime/issues/57452

**Review by lewing — APPROVED** [review]

**Pull request merged**
