### PR TITLE
Remove code for GC Poll marking and insertion.

### PR DESCRIPTION
**Pull request by erozenfeld**
This is a follow-up to
https://github.com/dotnet/runtime/issues/13582#issuecomment-542386711
and
https://github.com/dotnet/runtime/issues/13582#issuecomment-653235564

The code to insert gc polls was added in desktop for gc suspension not based
on hijaking. All platforms we target support hijaking so this code is not exercised
or tested. It also clutters other code and adds a bit of runtime overhead.
This change removes all that code.

There are minimal asm diffs because of a removed call to `fgRenumberBlocks`.

pin-icount reports a small but measurable throughput improvement when crossgen-ing SPC on x64: 0.07% (noise level is less than 0.01%).

### CODE REVIEW

**Comment by erozenfeld** [comment]
x64 pmi framework diffs:

```
PMI CodeSize Diffs for System.Private.CoreLib.dll, framework assemblies for  default jit

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 50341895
Total bytes of diff: 50341740
Total bytes of delta: -155 (-0.000% of base)
    diff is an improvement.

Top file regressions (bytes):
           2 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.000% of base)

Top file improvements (bytes):
        -144 : System.Private.Xml.dasm (-0.004% of base)
         -13 : Microsoft.CodeAnalysis.CSharp.dasm (-0.000% of base)

3 total files with Code Size differences (2 improved, 1 regressed), 264 unchanged.

Top method regressions (bytes):
           2 (0.228% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - VisualBasicWarningStateMap:CreateWarningStateEntries(ImmutableArray`1):ref

Top method improvements (bytes):
        -144 (-3.643% of base) : System.Private.Xml.dasm - SchemaGraph:Depends(XmlSchemaObject,ArrayList):this
         -13 (-0.591% of base) : Microsoft.CodeAnalysis.CSharp.dasm - RetargetingSymbolTranslator:Retarget(NamedTypeSymbol,ubyte):NamedTypeSymbol:this

Top method regressions (percentages):
           2 (0.228% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - VisualBasicWarningStateMap:CreateWarningStateEntries(ImmutableArray`1):ref

Top method improvements (percentages):
        -144 (-3.643% of base) : System.Private.Xml.dasm - SchemaGraph:Depends(XmlSchemaObject,ArrayList):this
         -13 (-0.591% of base) : Microsoft.CodeAnalysis.CSharp.dasm - RetargetingSymbolTranslator:Retarget(NamedTypeSymbol,ubyte):NamedTypeSymbol:this

3 total methods with Code Size differences (2 improved, 1 regressed), 258658 unchanged.
```

**Comment by erozenfeld** [comment]
@dotnet/jit-contrib @jkotas PTAL

**Review by jkotas — APPROVED** [review]
Thanks

**Review by sandreenko — APPROVED** [review]
Jit changes look good, thank you.

**Pull request merged**
