### PR TITLE
Allow prefix match in StressLogAnalyzer

### PR DESCRIPTION
**Pull request by cshung**
This PR introduces two different modes for StressLogAnalyzer.

`-p` can be used to specify a prefix to match through the stress log messages. For example, `-p:"commit-accounting"` will give out all the `dprintf` starting with the prefix "commit-accounting".

`-d` can be used to suppress the default messages. Together with the `-p` flag above, this will allow the output to be processed by other tools as we need.

### CODE REVIEW

**Comment by Maoni0** [comment]
> -d can be used to suppress the default messages.

what's a default message?

**Comment by cshung** [comment]
> > -d can be used to suppress the default messages.
> 
> what's a default message?

All the messages that we print unconditionally, such as the start and stop of various phases of the GCs.

**Comment by Maoni0** [comment]
I mean, we print based on the level so it would be helpful to indicate which messages these are - are they level 1 messages or something (we don't have to print level 1 messages)? a clarification would be nice. for example, I don't think we ever print unconditionally - it's whatever we pick to print that gets printed.

**Comment by cshung** [comment]
It is not the runtime, it is on the stress log analyzer side. When the stress log analyzer sees those messages of these types available in the stress log,

```
IS_LOGGING_OFF
IS_GCSTART
IS_GCEND
IS_MARK_START
IS_PLAN_START
IS_RELOCATE_START
IS_RELOCATE_END
IS_COMPACT_START
IS_COMPACT_END
```

it will always print them, and without my changes, there is no way to switch them off. Of course, we could change the runtime code to not emit the message into the stress log, it is just so much easier to add a flag on the stress log analyzer side to suppress them instead.

**Review by PeterSolMS — APPROVED** [review]
LGTM!

**Pull request merged**
