### PR TITLE
Correct error messages for CoreCLR Win32 PAL uses in CoreLib

### PR DESCRIPTION
**Pull request by jkotas**
Contributes to #76736

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Review by elinor-fung — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by danmoseley** [comment]
I guess we should backport?

**Comment by AaronRobinsonMSFT** [comment]
> I guess we should backport?

I think so, but perhaps we could wait to our first servicing window rather than GA?

**Comment by danmoseley** [comment]
I'd say it's worth asking - there's been nothing deferred to 7.0.1 yet.

**Comment by jkotas** [comment]
> we could wait to our first servicing window rather than GA?

It is for the servicing shiproom to decide. The basic rule is to take fixes sooner because of adoption (and thus blast radius of a potentially bad change) increases with time.

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
