### PR TITLE
Fix a nested-externs warning in mono

### PR DESCRIPTION
**Pull request by am11**
```sh
   In file included from /runtime/src/native/eventpipe/ep-rt.h:741,
                   from /runtime/src/native/eventpipe/ep-stack-contents.h:7,
                   from /runtime/src/native/eventpipe/ep.h:8,
                   from /runtime/src/native/eventpipe/ep.c:7,
                   from /runtime/artifacts/obj/mono/illumos.x64.Release/mono/mini/CMakeFiles/eventpipe-mono-objects.dir/Unity/unity_0_c.c:3:
  /runtime/src/mono/mono/mini/../../mono/eventpipe/ep-rt-mono.h: In function 'ep_rt_mono_is_runtime_initialized':
  /runtime/src/mono/mono/mini/../../mono/eventpipe/ep-rt-mono.h:1996:18: warning: nested extern declaration of '_ep_rt_mono_runtime_initialized' [-Wnested-externs]
    extern gboolean _ep_rt_mono_runtime_initialized;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

....
  In file included from /runtime/src/native/containers/dn-fwd-list.c:26:
  /runtime/src/native/containers/dn-fwd-list.h: In function 'dn_fwd_list_before_begin':
  /runtime/src/native/containers/dn-fwd-list.h:183:28: warning: nested extern declaration of '_fwd_list_before_begin_it_node' [-Wnested-externs]
    extern dn_fwd_list_node_t _fwd_list_before_begin_it_node;
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by am11** [comment]
before: https://dev.azure.com/dnceng-public/public/_build/results?buildId=739155&view=logs&j=9d44ffa5-6dbb-5c44-43bb-984541de6129&t=2c1dca5f-db26-547e-262f-8b403ec0d74c

after: https://dev.azure.com/dnceng-public/public/_build/results?buildId=739380&view=logs&j=9d44ffa5-6dbb-5c44-43bb-984541de6129&t=2c1dca5f-db26-547e-262f-8b403ec0d74c

**Review by lambdageek — APPROVED** [review]

**Review by mdh1418 — APPROVED** [review]

**Comment by tommcdon** [comment]
@dotnet-bot retest this please

**Comment by am11** [comment]
@tommcdon, fyi, when i merged `main` in PR branch, it was already running the build and was half way through. Now it's reset.

**Comment by thaystg** [comment]
@lewing can you confirm that the wasm tests are flaky and not side effect of this PR?

**Comment by thaystg** [comment]
@pavelsavara can you please confirm that the wasm tests are flaky and not side effect of this PR?

**Comment by lewing** [comment]
if the build analysis step is green (it is) that is sufficient confirmation

**Comment by pavelsavara** [comment]
Yes, they are flaky.

**Comment by am11** [comment]
Feel free to merge this, I don't have the merge rights. :)

**Pull request merged**
