### PR TITLE
Rename MinimumOSPlatformAttribute and RemovedInOSPlatformAttribute

### LINKED ISSUE #40360: Rename MinimumOSPlatformAttribute and RemovedInOSPlatformAttribute
In https://github.com/dotnet/runtime/issues/39989#issuecomment-665197220 we decided to rename these attributes in order to unify platform-specific attribution with marking platforms as unsupported. Please coordinate this change with @wli3 because he'll have to submit a [follow up to his PR](https://github.com/dotnet/sdk/pull/11499).

```diff
 namespace System.Runtime.Versioning
 {
     public abstract class OSPlatformAttribute : Attribute
     {
         private protected OSPlatformAttribute(string platformName);
         public string PlatformName { get; }
     }
 
     [AttributeUsage(AttributeTargets.Assembly,
                     AllowMultiple=false, Inherited=false)]
     public sealed class TargetPlatformAttribute : OSPlatformAttribute
     {
         public TargetPlatformAttribute(string platformName);
     }
 
     [AttributeUsage(AttributeTargets.Assembly |
                     AttributeTargets.Class |
                     AttributeTargets.Constructor |
                     AttributeTargets.Enum |
                     AttributeTargets.Event |
                     AttributeTargets.Field |
                     AttributeTargets.Method |
                     AttributeTargets.Module |
                     AttributeTargets.Property |
                     AttributeTargets.Struct,
                     AllowMultiple=true, Inherited=false)]
-    public sealed class MinimumOSPlatformAttribute : OSPlatformAttribute
+    public sealed class SupportedOSPlatformAttribute : OSPlatformAttribute
     {
-        public MinimumOSPlatformAttribute(string platformName);
+        public SupportedOSPlatformAttribute(string platformName);
     }
 
     [AttributeUsage(AttributeTargets.Assembly |
                     AttributeTargets.Class |
                     AttributeTargets.Constructor |
                     AttributeTargets.Enum |
                     AttributeTargets.Event |
                     AttributeTargets.Field |
                     AttributeTargets.Method |
                     AttributeTargets.Module |
                     AttributeTargets.Property |
                     AttributeTargets.Struct,
                     AllowMultiple=true, Inherited=false)]
-    public sealed class RemovedInOSPlatformAttribute : OSPlatformAttribute
+    public sealed class UnsupportedOSPlatformAttribute : OSPlatformAttribute
     {
-        public RemovedInOSPlatformAttribute(string platformName);
+        public UnsupportedOSPlatformAttribute(string platformName);
     }
 
     [AttributeUsage(AttributeTargets.Assembly |
                     AttributeTargets.Class |
                     AttributeTargets.Constructor |
                     AttributeTargets.Enum |
                     AttributeTargets.Event |
                     AttributeTargets.Field |
                     AttributeTargets.Method |
                     AttributeTargets.Module |
                     AttributeTargets.Property |
                     AttributeTargets.Struct,
                     AllowMultiple=true, Inherited=false)]
     public sealed class ObsoletedInOSPlatformAttribute : OSPlatformAttribute
     {
         public ObsoletedInOSPlatformAttribute(string platformName);
         public ObsoletedInOSPlatformAttribute(string platformName, string message);
         public string? Message { get; }
         public string? Url { get; set; }
     }
 }
```

### PR DESCRIPTION
**Pull request by adamsitnik**
fixes #40360

cc @terrajobst

### CODE REVIEW

**Comment by adamsitnik** [comment]
@krwq @eiriktsarpalis any chances I could get an approval from you during European working hours? this PR blocks me from fixing https://github.com/dotnet/runtime/issues/40095 and I would prefer to send two separate PRs

**Review by krwq — APPROVED** [review]
Looks good, please fix build errors

**Comment by adamsitnik** [comment]
the build failures seem unrelated, merging

**Review by jeffhandley — COMMENTED** [review]
Thanks!

**Pull request merged**
