### PR TITLE
update missing docs for System.IO.UnmanagedMemoryStream

### PR DESCRIPTION
**Pull request by martynasapanavicius**
As per this request: https://github.com/dotnet/corefx/pull/42732#issuecomment-558873520
> danmosemsft commented 37 minutes ago
> Hello, this code has now moved to the dotnet/runtime repo. (The code inthis repo will vanish soon.) Can you please move this PR there? Thanks!

Original message:
> martynasapanavicius commented 1 hour ago
> Was looking into System.IO.UnmanagedMemoryStream.ReadByte() return documentation because apparently it has some encoded meaning to it. Updated that one + some other docs while looking around.

### CODE REVIEW

**Comment by davidsh** [comment]
@carlossanlop Are we still using XML comments to update the [dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs) information? If not, documentation updates should happen directly in the docs [repo](https://github.com/dotnet/dotnet-api-docs).

**Comment by carlossanlop** [comment]
> _Are we still using XML comments to update the dotnet-api-docs information? If not, documentation updates should happen directly in the docs repo._

@davidsh, I noticed @martynasapanavicius is copying the missing triple slash documentation directly from MS docs. 
For example, here is the constructor that receives 3 arguments:
https://docs.microsoft.com/en-us/dotnet/api/system.io.unmanagedmemorystream.-ctor?view=netframework-4.8#System_IO_UnmanagedMemoryStream__ctor_System_Runtime_InteropServices_SafeBuffer_System_Int64_System_Int64_

@martynasapanavicius we consider MS Docs the source of truth, and those APIs you're documenting in triple slash, are already documented in MS Docs.

Triple slash comments are only meant to be used for seeding the MS Docs documentation the first time (we manually port them), but after that, we don't make efforts to update them (we only update the documentation in MS Docs).

Although I don't see any harm on having the triple slash comments match what we have in MS Docs, I think it is unnecessary.

**Comment by danmosemsft** [comment]
> Although I don't see any harm on having the triple slash comments match what we have in MS Docs, I think it is unnecessary.

It doesn't need to match, but they should be useful (for our own use when working in the repo), or we should remove them. Clearly `/// <param name="buffer"></param>` isn't useful.

**Comment by martynasapanavicius** [comment]
> > Although I don't see any harm on having the triple slash comments match what we have in MS Docs, I think it is unnecessary.
> 
> It doesn't need to match, but they should be useful (for our own use when working in the repo), or we should remove them. Clearly `/// <param name="buffer"></param>` isn't useful.

Thanks for explanation on the documentation.

The only thing why I bothered with this in a first place was due to lack of return docs on ReadByte():
```
/// <summary>
/// Returns the byte at the stream current Position and advances the Position.
/// </summary>
/// <returns></returns>
public override int ReadByte()
```
And it's all because it actually has an encoded meaning into its return value.
```
/// <returns>The unsigned byte cast to an Int32 object, or -1 if at the end of the stream.</returns>
```
That took me extra couple of minutes of my time to google for docs. Absolutely not a big deal, just thought it would be nice to have it there. And along with that I also went with the rest of the file since I was there.

When working with default .net libs I usually browse source instead of only reading docs online. The source code is mostly important for performance prediction (at least for me).

It's up to you guys. I'm totally fine with any decision.

**Comment by davidsh** [comment]
>The only thing why I bothered with this in a first place was due to lack of return docs on ReadByte():

The docs on [docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/api/system.io.unmanagedmemorystream.readbyte?view=netframework-4.8) describe the return value:

```
Returns
Int32
The unsigned byte cast to an Int32 object, or -1 if at the end of the stream.
```

>When working with default .net libs I usually browse source instead of only reading docs online. The source code is mostly important for performance prediction (at least for me).

This is a good point. However, it's a lot of work to have to maintain two sets of documentation: one in the source code, and another on docs.microsoft.com. We've chosen that latter as the source of truth. As you can see from the entire repo, we don't have XML comments everywhere.

We do use XML comments though when we first seeded docs.microsoft.com and we also expect folks to add XML comments for new APIs are added since it helps get the documentation written faster for docs.microsoft.com.

**Comment by martynasapanavicius** [comment]
> However, it's a lot of work to have to maintain two sets of documentation: one in the source code, and another on docs.microsoft.com. We've chosen the latter as the source of truth.
Totally understandable. I'm closing this.

**Pull request closed without merging**
