### PR TITLE
[CI only] Use pessimistic long branches on ARM

### PR DESCRIPTION
**Pull request by filipnavara**
@MichalStrehovsky can you run NativeAOT outer loop with this, please?

Ref: https://github.com/dotnet/runtime/issues/99079#issuecomment-1971393588

### CODE REVIEW

**Comment by filipnavara** [comment]
Thanks, this uncovered some new failure mode. Unfortunately I left my Raspberry Pi at office so I won't be able to reproduce it immediately.

**Comment by filipnavara** [comment]
@am11 Do you remember if there's a reason not to use `-fPIC` for shared libraries in src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets? We already have `PositionIndependentExecutable` and default to `true`. Do you think it would make sense to do something like that for shared libraries too, or even enable `-fPIC` unconditionally?

**Comment by jkotas** [comment]
Should  `-fPIC` be on by default for shared libraries? If it is not, it is certainly fine to enable it.

**Comment by filipnavara** [comment]
I assumed it is but the CI suggests otherwise (for ARM32, at least). I'll check it on Raspberry Pi tomorrow morning.

**Comment by am11** [comment]
-fPIC -fPIE are for compilation and -pie is for linking.

shared libraries and ELF are both executable by default, we set entrypoint to 0x0; something we picked up from how llvm toolchain build on Ubuntu:
https://github.com/dotnet/runtime/blob/8ec2b5084b76c16cdf852af85622c920a5f4d11a/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets#L202

so the idea that PIE is for executable and PIC is for shared lib is not definitive.

**Comment by filipnavara** [comment]
> -fPIC -fPIE are for compilation and -pie is for linking.

Well, the linker in the PR failed with
```
ld.lld(0,0): error : relocation R_ARM_THM_MOVW_PREL_NC cannot be used against symbol 'memmove'; recompile with -fPIC [/__w/1/s/src/tests/nativeaot/SmokeTests/SharedLibrary/SharedLibrary.csproj]
ld.lld(0,0): error : relocation R_ARM_THM_MOVT_PREL cannot be used against symbol 'memmove'; recompile with -fPIC [/__w/1/s/src/tests/nativeaot/SmokeTests/SharedLibrary/SharedLibrary.csproj]
```

I was caught a bit off guard by that because I assumed that (on Linux) shared libraries are always position independent.

**Pull request closed without merging**
