### PR TITLE
Fix NonBacktracking hanging in System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfLoops

### PR DESCRIPTION
**Pull request by olsaarik**
Addresses issue https://github.com/dotnet/runtime/issues/65271 which was introduced by https://github.com/dotnet/runtime/pull/65129 that enabled captures support for NonBacktracking.

One problem was that `TransitionRegex` did not simplify away effects on paths leading to nothing `[]` leaves, which was causing other simplification rules to not trigger leading to blow-up. Now the `Effect` constructor for `TransitionRegex` checks for nothing.

A second problem is that for a pattern like `(((...(a)*...)*)*)*` the `TransitionRegex` after the second step will include paths corresponding to each of the loop levels to represent the different choices in which loop loops again. This combined with lists of effects getting accumulated was causing a blow-up in time and memory usage. However, the backtracking engines would always take the innermost loop, which in the `TransitionRegex` is the leftmost path. Because that transition leads to a pattern that is nullable (accepts the empty string), none of the other transitions actually matter, since the backtracking engine would never go down a path corresponding to them. An optimization that allows the stress tests to finish is to ignore all transitions after the first nullable one.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
I'm glad a fix for these specific cases is easy.

Do we need to be concerned about other stressful situations that don't have as easy a solution?  Does this fit into the outstanding work item of defining bounds for what will have guaranteed processing times / memory usage?

**Comment by stephentoub** [comment]
Does this also fix https://github.com/dotnet/runtime/issues/65289?

**Comment by olsaarik** [comment]
https://github.com/dotnet/runtime/issues/65289 looks like a separate issue, maybe something has disabled Antimirov mode.

I think this is still separate from the work on defining bounds. For these huge patterns there's still only two calls into the derivative creation process. The state space is 2 states I think. I think for this we just need to examine the algorithms used to create the derivatives and make sure there's no surprise-quadratic-terms. I believe problems arising from these deeply nested regexes should still be all fixable by making sure the derivatives aren't getting constructed in some naive way.

**Comment by olsaarik** [comment]
Looks like that Build Analysis task failure isn't related to this. Do we ignore it or re-run it, and if so, how?

**Comment by stephentoub** [comment]
> Do we ignore it or re-run it, and if so, how?

I gave it a little nudge.

**Pull request merged**
