### PR TITLE
Move off preview onto regular Windows 11 client images

### PR DESCRIPTION
**Pull request by MattGal**
ClientPre is leaving as of 2022-06-16, move to newer non-preview Windows 11

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
Nice!

**Review by ViktorHofer — APPROVED** [review]

**Comment by MattGal** [comment]
@wfurt can you comment on whether I should merge here? the two failing linux legs are definitely unrelated but the Quic test is failing in the specific image I changed (https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-69871-merge-767c9d837644425e9d/System.Net.Quic.Functional.Tests/1/console.c15b690d.log?helixlogtype=result )

**Comment by wfurt** [comment]
that should be fine. The QUic failure is known and it should be resolved if you sync from main. 
cc: @rzikm

**Comment by MattGal** [comment]
@mangod9 just a simple grep is likely easier than the backport.

**Pull request merged**
