### PR TITLE
[mono] Split the shared tooling into a separate abstract workload

### PR DESCRIPTION
**Pull request by lewing**
Draft for discussion/review around VS and upgrade tooling.

This moves the shared parts of the mono workload to a separate abstract workload to allow the VS packaging tooling to treat it as a component group.

cc @joeloff @steveisok

### CODE REVIEW

**Comment by MihaZupan** [comment]
Would be interesting to see why the bot decided on `System.Net` here

**Comment by lewing** [comment]
@mhutch is this what you were suggesting for the shared packs?

**Review by steveisok — APPROVED** [review]
LGTM

**Comment by joeloff** [comment]
@lewing is this planned to merge soon? I'll have to update the Arcade tasks to support this fully because we need to generate different groups of projects for the setup authoring to separate all the workload models for VS. All concrete workloads will become visible components in VS, all abstract workloads will become component groups, but we'll only publish component groups if a workload in the same manifest extends it as we can't publish unreferenced components into VS as that will fail manifest validation

**Comment by lewing** [comment]
> @lewing is this planned to merge soon? I'll have to update the Arcade tasks to support this fully because we need to generate different groups of projects for the setup authoring to separate all the workload models for VS. All concrete workloads will become visible components in VS, all abstract workloads will become component groups, but we'll only publish component groups if a workload in the same manifest extends it as we can't publish unreferenced components into VS as that will fail manifest validation

@joeloff I just want to open the discussion to make sure this is the plan.  If it is, I'll coordinate with you before landing anything.

**Comment by lewing** [comment]
cc @jonathanpeppers

**Review by jonathanpeppers — COMMENTED** [review]
While you're reorganizing these, could you split up the Android packs further, too? If we could have the `Microsoft.NETCore.App.Runtime.AOT.Cross.*` packages in a separate workload, we could make those optional.

We would want to have something like:

```json
"microsoft-android-sdk-minimal": {
...
  "extends" : [ "microsoft-net-runtime-android" ]
},
"microsoft-android-sdk-full": {
...
  "extends" : [ "microsoft-net-runtime-android-aot" ]
},
```
Where `microsoft-android-sdk-minimal` could leave out AOT for file size concerns. Our "Hello World" Android experience wouldn't actually need to use AOT.

**Comment by lewing** [comment]
> While you're reorganizing these, could you split up the Android packs further, too? If we could have the `Microsoft.NETCore.App.Runtime.AOT.Cross.*` packages in a separate workload, we could make those optional.
> 
> We would want to have something like:
> 
> ```json
> "microsoft-android-sdk-minimal": {
> ...
>   "extends" : [ "microsoft-net-runtime-android" ]
> },
> "microsoft-android-sdk-full": {
> ...
>   "extends" : [ "microsoft-net-runtime-android-aot" ]
> },
> ```
> 
> Where `microsoft-android-sdk-minimal` could leave out AOT for file size concerns. Our "Hello World" Android experience wouldn't actually need to use AOT.

should these be kind = "build" to give @joeloff a hint on the vs tooling?

**Comment by jonathanpeppers** [comment]
@lewing was reading up on `kind=build`: https://github.com/dotnet/designs/blob/main/accepted/2020/workloads/workload-manifest.md#workload-definitions

I think these AOT packs will need to be default `kind=dev` (or leave the value blank), because we will probably have a checkbox, description, and UI for them in the VS Installers.

**Comment by mhutch** [comment]
I wouldn't worry too much about the `kind` metadata as it isn't used. I'm kinda thinking this metadata would be better on packs anyways, so it might never be used.

**Review by jonathanpeppers — COMMENTED** [review]
I don't know if this causes an issue, but I saw this one is lowercase:
https://github.com/dotnet/runtime/blob/ea2d26d8938972d7e622218cec62134944a80ee6/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/WorkloadManifest.json.in#L151

I noticed it because I was looking in Explorer:

image

**Pull request merged**
