### PR TITLE
[release/7.0] Fix delegate allocation in CachingContext.GetOrAddJsonTypeInfo

### LINKED ISSUE #80430: Massive allocations of Func<Type, JsonTypeInfo> in System.Text.Json.JsonSerializerOptions+CachingContext.GetOrAddJsonTypeInfo(Type)
Create a plain F# console app targeting .NET 7, with this minimal repro code:

```f#
open System.Text.Json

let data = Array.init 1_000_000 (fun _ -> [box 1])
let json = JsonSerializer.Serialize(data)
```

This initializes an array with one million elements, each being an F# list with a boxed integer. It then serializes the data.

When I run a memory profiler (dotMemory), the top hitter in terms of allocation size is `Func<Type, JsonTypeInfo>` in System.Text.Json, specifically in `GetOrAddJsonTypeInfo`. It is allocated almost 900.000 times:

```
Allocated type : System.Func<Type, JsonTypeInfo>
  Objects : 896629
  Bytes   : 57384256

Allocated by
   100%  GetOrAddJsonTypeInfo • 54,73 MB / 54,73 MB • System.Text.Json.JsonSerializerOptions+CachingContext.GetOrAddJsonTypeInfo(Type)
     100%  GetTypeInfoInternal • 54,73 MB / - • System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type, Boolean, Boolean)
      ►  95,0%  ResolvePolymorphicConverter • 51,99 MB / - • System.Text.Json.Serialization.JsonConverter.ResolvePolymorphicConverter(Object, JsonTypeInfo, JsonSerializerOptions, WriteStack)
      ►  5,00%  InitializePolymorphicReEntry • 2,74 MB / - • System.Text.Json.WriteStackFrame.InitializePolymorphicReEntry(Type, JsonSerializerOptions)
      ► <0,01%  get_ElementTypeInfo • 128 B / - • System.Text.Json.Serialization.Metadata.JsonTypeInfo.get_ElementTypeInfo()
      ► <0,01%  GetTypeInfoForRootType • 64 B / - • System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type)
```

I assume the reason is that there is a lambda or similar somewhere that is not being optimized/cached by the C# compiler.

You may want to adjust your code to prevent these allocations.

Maybe related: https://github.com/dotnet/roslyn/issues/5835 and linked issues

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Fixes #80430.

## Customer Impact

Fixes a customer reported performance regression in STJ's metadata caching implementation, which will a allocate a new delegate on every metadata lookup operation. This becomes particularly noticeable when serializing object graphs containing many polymorphic values, for example large non-generic collections.

## Testing

N/A.

## Risk

Low. It is a small change that caches the metadata factory delegate in a field.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by ericstj** [comment]
Needs the servicing authoring.  cc @carlossanlop

**Comment by eiriktsarpalis** [comment]
Approved by Tactics over email.

**Review by ericstj — APPROVED** [review]
LGTM

**Comment by Sergio0694** [comment]
Just curious, will this also be shipped for the OOB package? 🙂

**Comment by carlossanlop** [comment]
> Just curious, will this also be shipped for the OOB package? 🙂

Yep. This commit will take care of that:  https://github.com/dotnet/runtime/pull/80513/commits/81a735863d920450b5716a314e55f61b98a78fcc

**Comment by Sergio0694** [comment]
Sweet, that's awesome! Thank you 😄

**Comment by carlossanlop** [comment]
Approved by Tactics (7.0.3).
Signed off by area owners.
Required OOB changes look correct (and may be reused by the other Json PR if it also gets merged: https://github.com/dotnet/runtime/pull/80576).
CI failure was a timeout cancellation. No test-specific failures logged.
Ready to merge. :shipit:

**Pull request merged**
