### PR TITLE
[release/7.0] Add a RID for Fedora 39

### PR DESCRIPTION
**Pull request by omajid**
This is a backport of https://github.com/dotnet/runtime/pull/82185

I don't know why runtime.json has all these extra changes. Is this a platform-specific sorting issue?

### CODE REVIEW

**Comment by carlossanlop** [comment]
There was some discussion about the tooling here: https://github.com/dotnet/runtime/pull/82185#issuecomment-1431871079

And if I'm not mistake, @ViktorHofer fixed the issue(s). So if you generated this PR using the latest version of the tool that include those fixes, the changes you see _should_ be expected. Can you please help confirm @ViktorHofer / @wfurt ?

**Comment by ViktorHofer** [comment]
The additional changes are expected as some RIDs were manually added and @wfurt then run the tool which sorted them correctly.

**Review by ViktorHofer — APPROVED** [review]

**Comment by carlossanlop** [comment]
@omajid Can you please update Microsoft.NETCore.Platorms.csproj as described here?:
 https://github.com/dotnet/runtime/blob/release/7.0/docs/project/library-servicing.md

Need to set GeneratePackageOnBuild to true and increase the ServicingVersion number:
https://github.com/dotnet/runtime/blob/94213eb25fe3867e66708fe6bb103b0bc9f11d0a/src/libraries/Microsoft.NETCore.Platforms/src/Microsoft.NETCore.Platforms.csproj#L26-L27

@wfurt do you mind reviewing this?

**Review by carlossanlop — CHANGES_REQUESTED** [review]
Needs OOB changes.

**Review by carlossanlop — APPROVED** [review]
The OOB changes look good. Thanks @omajid.

**Pull request merged**
