### PR TITLE
Publish `UpDownCounter` and `ObservableUpDownCounter` Events for System.Diagnostics.Metrics

### LINKED ISSUE #79916: `MetricsEventSource` Not Publishing `UpDownCounter` For `dotnet-counters`/`dotnet-monitor`?
The `dotnet monitor` tool is currently working on adding support for `System.Diagnostics.Metrics` (the `dotnet-counters` tool already supports this). Just from taking a look at https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Metrics/MetricsEventSource.cs#L44, it looks like there isn't an event being published for `UpDownCounter` (e.g. UpDownCounterValuePublished) - does this need to be added so that `dotnet-counters` and `dotnet-monitor` can process those events?

### PR DESCRIPTION
**Pull request by kkeirstead**
Publishing events for `UpDownCounter` and `ObservableUpDownCounter` for consumption by `dotnet counters`/`dotnet monitor` - this was likely omitted unintentionally in https://github.com/dotnet/runtime/pull/64365. Includes testing changes for both instruments.

Fixes #79916

### CODE REVIEW

**Review by noahfalk — APPROVED** [review]
Thanks @kkeirstead, this looks great. One request, can you change at least one of the MetricsEventSource tests to verify that the emitted data is correct when the UpDownCounter/ObservableUpDownCounter has negative rates and negative values. I don't predict any issue, but since that is the key difference of the UpDownCounter its good to confirm.

**Review by noahfalk — APPROVED** [review]
👍

**Comment by noahfalk** [comment]
Are you happy with the changes at this point? I can sort out the test failures and get it merged if so. The failures appear unrelated to your change.

**Comment by kkeirstead** [comment]
> Are you happy with the changes at this point? I can sort out the test failures and get it merged if so. The failures appear unrelated to your change.

I think so - I didn't have any more changes I planned on making.

**Comment by noahfalk** [comment]
Alright its in, thanks @kkeirstead!

**Pull request merged**
