### PR TITLE
Fix multiple version strings in coreclr shared libraries

### LINKED ISSUE #39456: @Commit appears multiple times in strings libcoreclr.so output
Noticed this while working on a bug, `@Commit` string appears multiple times during `strings libcoreclr.so | grep "@Commit"` command that suggest version.c was included multiple times. While this behavior was reproduced on linux-arm, it is probably not specific to the architecture.

```
robox@DDNANO3:~/echesako/runtime/artifacts/bin/testhost/net5.0-Linux-Release-arm/shared/Microsoft.NETCore.App/5.0.0$ strings libcoreclr.so | grep "@Commit"
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
@(#)Version 42.42.42.42424 @Commit: e708795013a1bcca337daeee09732d4d5fad6281
```

cc @janvorli @VSadov

### PR DESCRIPTION
**Pull request by janvorli**
We were incorrectly adding the version.c source to all coreclr
libraries and not just the shared ones. That caused multiple
occurences of the version string in coreclr shared libraries
composed of sublibraries.
This change fixes it by adding that source file for shared
libraries only.
I've also discovered that libcoreclrtraceptprovider.so was
missing the version string completely, so I've added it there.

Close #39456

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
LGTM. Thanks!

**Comment by am11** [comment]
@janvorli, a question related to version string; currently we get version line like `@(#)Version 42.42.42.42424 @Commit: e7b332a50fccbd13d7f0041a7d9a6a0597c657bd` from:

```sh
$ strings ./artifacts/bin/coreclr/OSX.x64.Release/libcoreclr.dylib | grep "@Commit"
$ strings ./.dotnet/dotnet | grep "@Commit"
# etc.
```
what is `42.42.42.42424`? Can it be something more useful like `5.0.0-dev` which corresponds to the version of toolset we built the product against?

**Comment by janvorli** [comment]
> what is `42.42.42.42424`?

That is for local builds. Official builds have the proper version number.

**Comment by am11** [comment]
Ah right, the RC1 I have installed has `@(#)Version 5.0.20.42518 @Commit: 55ab8ce696ea3d2458543176c79c332fecf0af6c`.

**Pull request merged**
