### PR TITLE
Fix interpreter build

### PR DESCRIPTION
**Pull request by BruceForstall**
Fix the x86, arm32, and arm64 builds, and the Release builds.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib Can someone take a look?

**Review by AndyAyersMS — APPROVED** [review]
LGTM

**Comment by josalem** [comment]
Whoops, had meant to approve, but looks like I forgot to hit the submit button.  thanks, @AndyAyersMS & @BruceForstall.  @yuchong-pan, I think this change removes the attempts at scoping `get_IsSupported` to just HW intrinsic classes for Checked/Release builds of the runtime.  Effectively, this will now return false for any method named `get_IsSupported` inside `SPCL`.  In fact, I think this might have already been the behavior since `GetDebugClassName` only works under `DEBUG` builds to begin with.  This isn't necessarily an issue right now, just something to consider when we go to make a production quality version of HW intrinsics for the interpreter 😄.

**Comment by BruceForstall** [comment]
>  I think this change removes the attempts at scoping get_IsSupported to just HW intrinsic classes for Checked/Release builds of the runtime.

Correct. The problem is it broke the Release builds. I didn't look to see if there was an equivalent functionality that would work in Release builds, or we should just find a "production quality" implementation as previously described.

**Pull request merged**
