### PR TITLE
Fix issues in PAL

### PR DESCRIPTION
**Pull request by kant2002**

### CODE REVIEW

**Comment by am11** [comment]
Can you describe a bit what's the issue? Please make sure there is no regression in the [PAL tests](https://github.com/dotnet/runtime/blob/3b40c7cfc4519a95e9d03ac85a2a2de68299aa7f/docs/workflow/testing/coreclr/unix-test-instructions.md#pal-tests). It is using `dwSrcFileAttributes = GetFileAttributes(lpExistingFileName)` since the initial commit of coreclr, so it would be interesting to know what this PR aims to fix.

**Comment by kant2002** [comment]
I'm definitely have unusual case. I'm [trying](https://github.com/kant2002/myjit) to build Jit as standalone component outside of CoreCLR. I still rely on the CMake files in `src\coreclr`, just concentrate mostly on building `src\coreclr\jit` and `src\coreclr\pal`. I'm trying to do build with plain CMake without existing infra.

This error happens on Linux x64.

Eventually I plan replace some C++ files of JIT with code written in NativeAOT (just as experiment). You can think about all that as educational experiment.

So either I miss some configuration which I should pass to CMake, or based on my understanding, this is small mistake which doest not exibit itself in normal build, just on the exotic ones, like mine setup.

that's actually 1 line change + 3 comment changes for "purity"

**Comment by kant2002** [comment]
I think I mess up by define `UNICODE` in my attempts to build, and thus this small thing was discovered.

**Comment by kant2002** [comment]
PAL tests seems to be running fine, even if I receive this
```
Running PAL tests from ~/runtime/artifacts/bin/coreclr/Linux.x64.Debug/paltests
~/runtime/artifacts/bin/coreclr/Linux.x64.Debug/paltests ~/runtime
./src/coreclr/pal/tests/palsuite/runpaltests.sh: line 41: cd: ./src/coreclr/pal/tests/palsuite: No such file or directory
The list of PAL tests to run will be read from ~/runtime/artifacts/bin/coreclr/Linux.x64.Debug/paltests/paltestlist.txt
./src/coreclr/pal/tests/palsuite/runpaltests.sh: line 82: cd: /tmp/PalTestOutput/default: No such file or directory
PAL tests will store their temporary files and output in /tmp/PalTestOutput/default.
```
results 
```
<assembly name="PAL" total="695" passed="695" failed="0" skipped="0">
```

**Comment by kant2002** [comment]
@am11 do I need to provide additional information?

**Comment by am11** [comment]
Thanks for the info, it's an interesting case. There was some effort made to build JIT without PAL (pure STL), but currently we need PAL.

@janvorli, could you please take a look?

---
> ./src/coreclr/pal/tests/palsuite/runpaltests.sh: line 41: cd: ./src/coreclr/pal/tests/palsuite: No such file or directory

Yup, these warnings are harmless, but needs to be fixed some day. I'll take a look. :)

**Comment by kant2002** [comment]
@am11 I think I can simplify (somewhat?) looking if you take a look at the sibling PR #62642 ;)

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
