### PR TITLE
JIT: Simplify block insertion logic during loop canonicalization

### LINKED ISSUE #107175: JIT: Simplify loop canonicalization
With RPO layout we should be able to simplify loop canonicalization -- it can stop paying attention to the exact physical position it inserts the blocks it creates.

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Fixes #107175. With #107350 merged in locally, I saw modest diffs from `optSetBlockWeights`, as it still relies on lexical ordering to scale loop weights (we should probably clean that up for .NET 10, too).

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
cc @dotnet/jit-contrib, @AndyAyersMS PTAL. [Small diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=798758&view=ms.vss-build-web.run-extensions-tab) presumably from `optSetBlockWeights` messing with the block weights. Thanks!

**Comment by amanasifkhalid** [comment]
I decided to add a helper for inserting new blocks in try regions now, since I'm seeing potential to simplify `fgNewBBinRegion` callsites in other spots. Hopefully, we can phase it out altogether.

**Review by AndyAyersMS — APPROVED** [review]

**Comment by amanasifkhalid** [comment]
Looks like the helper change is hitting asserts. I'll take a look...

**Comment by amanasifkhalid** [comment]
Suppose we have nested try regions T0, T1, and T2, such that they currently all end on the same block. If we want to insert a new block at the end of T1, we need to extend T1 and T2, but we shouldn't extend child regions like T0. Thus, `fgNewBBatTryRegionEnd` should iterate EH regions starting from the region we inserted in, and not necessarily the whole EH table.

**Comment by amanasifkhalid** [comment]
@AndyAyersMS sorry for the premature review -- could you PTAL? Thanks!

**Review by AndyAyersMS — APPROVED** [review]
EH nesting can be tricky to reason about.

**Pull request merged**
