### PR TITLE
Address timeouts in merged test groups

### PR DESCRIPTION
**Pull request by markples**
See #68529 for theories.

Should solve the first timeouts in #83961 (baseservices/threading), Directed_1, Regression_1, and Regression_2 by marking tests as RequiresProcessIsolation.
Adds striping to Regression_1, Regression_4, threading_group1.

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]
Thanks for the comments in each test for why it's process isolated!

**Comment by markples** [comment]
CI and gcstress passed with the latest iteration other than tests failing elsewhere

**Pull request merged**
