### PR TITLE
Don't use AVX-512 for small inputs in Memmove due to throttle issues

### PR DESCRIPTION
**Pull request by EgorBo**
I noticed that my PR https://github.com/dotnet/runtime/pull/84348 regressed TE benchmarks

image

I assume that our hardware for these benchmarks matches the official TE hardware which is `CPU Intel Xeon Gold 5120`  - a Q3'17 SkylakeX where, presumably, AVX-512 first appeared. Presumably, most AVX-512 instructions have high power licenses on that CPU and can lead to throttle on extensive use. I validated that my change fixes RPS issue on that hardware, but I'm not sure it's the right fix, should we somehow check that the current CPU is modern enough to freely use AVX-512? As far as I know, LLVM switched to "prefer 256bit vectors" because of the same issue - https://reviews.llvm.org/D67259 (Although, if e.g. `-mcpu=znver4` set - it will use 512)

I still enabled `129..256` range for unrolling because without AVX-512 we'll fallback to memmove call - I validated that this PR fixes the RPS issue and it's back to normal (even makes code faster than the base in my local runs)

PS: CoreCLR GC uses AVX-512 in VXSort to sort card tables and I think I saw perf improvements when I disabled AVX-512 there too.

cc @dotnet/avx512-contrib

### CODE REVIEW

**Comment by EgorBo** [comment]
Codegen example this PR changes:
```csharp
bool Foo(Span<byte> s1, Span<byte> s2) =>
    s1.Slice(0, 70).TryCopyTo(s2);
```
```diff
; Method Prog:Foo(System.Span`1[ubyte],System.Span`1[ubyte]):bool:this
G_M65161_IG01:
       sub      rsp, 40
       vzeroupper 
						;; size=7 bbWeight=1 PerfScore 1.25

G_M65161_IG02:
       cmp      dword ptr [rdx+08H], 70
       jb       SHORT G_M65161_IG06
       mov      rax, bword ptr [rdx]
       mov      rdx, bword ptr [r8]
       mov      ecx, dword ptr [r8+08H]
       xor      r8d, r8d
       cmp      ecx, 70
       jb       SHORT G_M65161_IG04
						;; size=24 bbWeight=1 PerfScore 11.50

G_M65161_IG03:
-      vmovdqu32 zmm0, zmmword ptr[rax]
-      vmovdqu  xmm1, xmmword ptr [rax+36H]
-      vmovdqu32 zmmword ptr[rdx], zmm0
-      vmovdqu  xmmword ptr [rdx+36H], xmm1
+      vmovdqu  ymm0, ymmword ptr [rax]
+      vmovdqu  ymm1, ymmword ptr [rax+20H]
+      vmovdqu  xmm2, xmmword ptr [rax+36H]
+      vmovdqu  ymmword ptr [rdx], ymm0
+      vmovdqu  ymmword ptr [rdx+20H], ymm1
+      vmovdqu  xmmword ptr [rdx+36H], xmm2
       mov      r8d, 1
						;; size=28 bbWeight=0.50 PerfScore 6.12

G_M65161_IG04:
       mov      eax, r8d
						;; size=3 bbWeight=1 PerfScore 0.25

G_M65161_IG05:
       add      rsp, 40
       ret      
						;; size=5 bbWeight=1 PerfScore 1.25

G_M65161_IG06:
       call     [System.ThrowHelper:ThrowArgumentOutOfRangeException()]
       int3     
						;; size=7 bbWeight=0 PerfScore 0.00
; Total bytes of code: 74
```

**Review by BruceForstall — APPROVED** [review]
This seems good for now. I wonder if we'll have to be more fine-grained in our performance tuning, e.g., even tuning the JIT dynamically by CPU part instead of only by ABI, as we do now.

**Comment by benaadams** [comment]
Is due to frequency scaling on early 512 chips. Cloudflare did a write up on it https://blog.cloudflare.com/on-the-dangers-of-intels-frequency-scaling/

Xeon Gold 5120 - Intel : Turbo Frequency/Active Cores

image

**Comment by EgorBo** [comment]
Is there any way to check that a chip is modern enough? I assume just checking processors we have in Azure is not enough or we really need to make a allow-list 😐

**Comment by EgorBo** [comment]
Btw, I think I saw improvements in TE when I also disabled AVX1-AVX2 and it matches Ben's picture. But I connected that with the fact we mostly work with small inputs..

**Comment by tannergooding** [comment]
> Is there any way to check that a chip is modern enough?

Not outside model/stepping/revision checks, which we've avoided doing so far. Throttling is a general concern, even for `Vector256<T>`, its just "less" on newer chips and we've passed the point where its considered beneficial enough on average.

For `Vector512<T>`, we're probably still a ways out from being able to assume any `64-byte` workload is good enough and so we'll probably need to maintain checks for `>128-256` bytes for the time being. We still have a lot of benefit available via 128-bit and 256-bit instructions available on AVX-512+ hardware, however. -- The throttling largely comes from using 512-bits, not from using AVX-512 instructions.

**Comment by EgorBo** [comment]
Thanks for the inputs Everyone!! Since this PR unblocks the TE regression I'm going to merge it and since we have a plan to enable AVX-512 in other places I guess we'll have to come up with some univeral heuristic or something like that.

**Pull request merged**
