### PR TITLE
Fix enum memory code paths

### LINKED ISSUE #57960: Dump generation for the server GC apps failure
### Description

Heap dump generation for the server GC apps failure on Windows.

### Configuration

Windows x64, Linux and MacOS
Latest rc2 builds from main (6.0.0-rc.2.21420.29)

### Regression?

Yes, caused by the GC USE_REGION support

### Other information

The failure (throws an exception) is on line 260 below.  It is because "heap" is a local copy of the gc_heap struct and can't be cast to a dac ptr. 

request_svr.cpp line 260:
```
   for (int i = 0; i < heaps; i++)
    {
        TADDR heapAddress = HeapTableIndex(g_gcDacGlobals->g_heaps, i);    
        dac_gc_heap heap = LoadGcHeapData(heapAddress);
        dac_gc_heap* pHeap = &heap;

        size_t gen_table_size = g_gcDacGlobals->generation_size * (*g_gcDacGlobals->max_gen + 2);
-->     DacEnumMemoryRegion(dac_cast<TADDR>(pHeap), sizeof(dac_gc_heap));
        DacEnumMemoryRegion(dac_cast<TADDR>(pHeap->finalize_queue), sizeof(dac_finalize_queue));

        TADDR taddrTable = dac_cast<TADDR>(pHeap) + offsetof(dac_gc_heap, generation_table);
        DacEnumMemoryRegion(taddrTable, gen_table_size);

            // address. To make sure there is always a base address, start with the first NT_FILE entry
            // found and then replace it with the PageOffset == 0 entry found.




```

### PR DESCRIPTION
**Pull request by cshung**
Fix #57960 

This fixes a few things:

- The fields corresponding to the `dac_gc_heap` are no longer guaranteed to be matching the target, in fact, the fields are no longer contiguous, therefore we need to call `DacEnumMemoryRegion` on individual fields separately.
- Same applies to `dac_generation`.
- We also want the POH segments.
- We also want to make sure it works under regions.

The arguments passed into `DacEnumMemoryRegion` should correspond to the right target addresses.
Beyond manual inspection, is there something we can run to make sure this is correct?

### CODE REVIEW

**Review by mikem8361 — APPROVED** [review]
Looks good. I built/ran your changes under the SOS tests on Windows and Linux and everything passes.

We will need to backport to rc2 (release/6.0).

**Comment by mikem8361** [comment]
@cshung is there anything else needed before merging this PR?

**Comment by cshung** [comment]
I am working on testing it under `USE_REGIONS`. I will merge it today if my testing is good.

**Review by mikem8361 — APPROVED** [review]
Looks good. Ran the SOS tests again on Windows and Linux.

**Pull request merged**
