### PR TITLE
Cleaned up code

### PR DESCRIPTION
**Pull request by ghost**
Removed the unnecessary if-else block, replaced with a cleaner and shorter statement.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=66981) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=66981) before we can accept your contribution.<br/><br/>:x: Danyy427 [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=66981)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=66981) it.</sub>

**Comment by teo-tsirpanis** [comment]
Hello @Danyy427 and thanks for the contribution! Unfortunately [the code does not compile](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACY8pJ0hgYQYG8aH+GASwB2GGFGHYANkxYMAKgwDiMDAHlhMADzyAfAAoAlHwG9qAi0IBmDfRgCeABxgQr++YYB0ASVwAFKEF8QQxBADcYBkJCBgdnV3dDBgBeZNinFzcAExgwIOlDY3NLfjMSkuIAdlsPfQhgACtcjENE/XJDAG4TEoBfHssMAAsoCAB3Bk0JgDkIDABlAFdHR2gxLIBRBDAYR1CIYSNu4v5+6l6gA) because it casts an `int` to a generic type, which is not allowed.

The pattern we do instead is to first box `1` to an object, and then unbox it to that generic parameter. Don't worry about the boxing's impact on performance, the JIT is smart enough to figure out and produces very optimized code.

I am going to close this PR. Thanks again for taking the time to contribute to .NET.

**Comment by teo-tsirpanis** [comment]
On a second thought, what you could do instead is change only the `Zero` property to return `default` instead of casting `Zero` (I don't see a way to change `One`). But you still need to keep the many type comparisons because `Type.IsPrimitive` does not generate optimized code. Here's how the code would look like:

``` csharp
if (typeof(T) == typeof(bool)
    || typeof(T) == typeof(byte)
    || ...)
{
    return default;
}

throw new NotSupportedException();
```

@tannergooding what do you think?

**Comment by Danyy427** [comment]
@teo-tsirpanis What if instead of first casting the `int` to a generic type, we cast it immediately to a object and then to the generic type. Something like this:

`if(typeof(T).IsPrimitive || typeof(T) == typeof(decimal))
{
    return (T)(object)(1)
}`

Just a thought

**Comment by teo-tsirpanis** [comment]
It won't work. `1` in your example is an integer. If `T` is something else like a float, casting will fail.

And either way using `Type.IsPrimitive` is unacceptable because it is not yet optimized by the JIT.

**Comment by Danyy427** [comment]
@teo-tsirpanis sorry didn't see the second comment

**Comment by tannergooding** [comment]
`IsPrimitive` is not a JIT time constant and so this change cannot be taken as it will massively hurt the generated code and therefore perf of the library.

**Pull request closed without merging**
