### PR TITLE
Fix: add missed open curly

### LINKED ISSUE #61282: CustomAttributeTypedArgument.ToString() is missing an open curly
### Description

`CustomAttributeTypedArgument.ToString()` produces malformed output if the argument is an array.

### Reproduction Steps

```csharp
Console.WriteLine(
    new System.Reflection.CustomAttributeTypedArgument(
        new [] { new System.Reflection.CustomAttributeTypedArgument(0) }));
```

### Expected behavior

```text
new CustomAttributeTypedArgument[1] { 0 }
```

### Actual behavior

```text
new CustomAttributeTypedArgument[1]0 }
```

### Regression?

It's a regression. The bug was introduced after the .NET 5 release: https://github.com/dotnet/runtime/commit/0c793920f62dd2711e6423a3425110e5cb7acfde#diff-f43b9f98fddac0e7fa971362f6f07f5fc9a3a0a41b485e9df15df87c99d638cb

### Known Workarounds

_No response_

### Configuration

Works before https://github.com/dotnet/runtime/commit/0c793920f62dd2711e6423a3425110e5cb7acfde. Doesn't work after.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by annchous**
Fixes #61282

### CODE REVIEW

**Comment by am11** [comment]
Would be good to have a test like:
```c#
[Fact]
public static void Test_CustomAttributeTypedArgument_ToString()
{
    var argument = new CustomAttributeTypedArgument(new [] { new CustomAttributeTypedArgument(0) });

    Assert.Equal("new CustomAttributeTypedArgument[1] { 0 }", argument.ToString());
}
```
after: https://github.com/dotnet/runtime/blob/39ece73bd08b1bcea0b9447cf34690bb1b41ba0a/src/libraries/System.Runtime/tests/System/Reflection/CustomAttribute_Named_Typed_ArgumentTests.cs#L53

**Comment by buyaa-n** [comment]
@annchous please add unit test in here https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime/tests/System/Reflection/CustomAttribute_Named_Typed_ArgumentTests.cs

**Comment by annchous** [comment]
> @annchous please add unit test in here https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime/tests/System/Reflection/CustomAttribute_Named_Typed_ArgumentTests.cs

Yup, I've already found that place, thanks! In process with test now :)

**Review by buyaa-n — APPROVED** [review]
LGTM, thanks!

**Comment by buyaa-n** [comment]
The build failure unrelated, filed an [issue](https://github.com/dotnet/runtime/issues/61331) for failure, merging

**Pull request merged**
