### PR TITLE
Move NoInt32OverflowInTheBufferingLogic to OuterLoop

### PR DESCRIPTION
**Pull request by jozkee**
It appears to be a long running test in CI: https://dev.azure.com/dnceng/public/_build/results?buildId=1424571&view=ms.vss-test-web.build-test-results-tab&runId=41213488&resultId=193806&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

In addition, this PR addresses some suggestions left in https://github.com/dotnet/runtime/pull/60459.

### CODE REVIEW

**Review by hoyosjs — APPROVED** [review]

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you for doing this @Jozkee !

**Comment by akoeplinger** [comment]
FYI you need to unlock a locked issue otherwise the backport bot can't post comments on it.

This is also failing on `coreclr windows x64` on https://github.com/dotnet/runtime/pull/63014

/backport to release/6.0

**Comment by akoeplinger** [comment]
@Jozkee oh well, looks like this will need to be done manually anyway 😄

**Pull request merged**
