### PR TITLE
[release/8.0-staging] Transition to 1ES templates work (Backport #92901)

### PR DESCRIPTION
**Pull request by eduardo-vp**
This is part of the work to transition to the 1ES templates in servicing branches.

### CODE REVIEW

**Comment by carlossanlop** [comment]
@eduardo-vp FYI there are some merge conflicts after the recent merge in related files.

**Comment by eduardo-vp** [comment]
Results of the runtime pipeline (1bfcdabe84f3fe5326075964463eec41c6b8b267): https://dev.azure.com/dnceng-public/public/_build/results?buildId=663664&view=results

**Comment by eduardo-vp** [comment]
Results of the runtime pipeline after reverting #101518 (334200d4767549616c3b5e716d140fa2360d46b6): https://dev.azure.com/dnceng-public/public/_build/results?buildId=663964&view=results

**Comment by eduardo-vp** [comment]
Official build (7963b61077c974756d8bc6c1604ed206db4b5a39): https://dev.azure.com/dnceng/internal/_build/results?buildId=2439636&view=results

**Comment by eduardo-vp** [comment]
Official build (c9076d1ea4de77e2e44b7552ff72edf1abb7baee): https://dev.azure.com/dnceng/internal/_build/results?buildId=2444882&view=results

**Pull request closed without merging**
