### PR TITLE
Add crossgen2 runs for x86 (#58053)

### PR DESCRIPTION
**Pull request by Lxiamail**
* Add crossgen2 runs for x86 and Arm64

* Remove Arm64 for now

### CODE REVIEW

**Review by billwert — APPROVED** [review]

**Comment by jeffschwMSFT** [comment]
@Lxiamail can you take a look at the failing ci?

**Comment by Lxiamail** [comment]
> @Lxiamail can you take a look at the failing ci?

Hmm, the change is only in perf test pipeline. There should be no impacted to CI result. I clicked rerun to see how it goes.

**Comment by Lxiamail** [comment]
@jeffschwMSFT can you please merge it when you have a moment? Expect this fixed a windows x86 crossgen perf test job failing right now.

**Review by jeffschwMSFT — APPROVED** [review]
Approved.

**Pull request merged**
