### PR TITLE
[release/7.0] Use the register of CAST for contained index operator

### PR DESCRIPTION
**Pull request by kunalspathak**
Backport of #74275 

If index is contained and the underlying operator is GT_CAST we were not handling that case and that led to using REG_COUNT register from index in genScaledAdd() . I have fixed it and also added checks to see if more such cases are missing.

Fixes: https://github.com/dotnet/runtime/issues/74117

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by carlossanlop** [comment]
@BruceForstall can we get a code review sign off?
@jeffschwMSFT can we get an approval?

**Review by BruceForstall — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
approved.  once we get a green ci we can merge.

**Comment by carlossanlop** [comment]
There were a ton of llvmaot failures. Are they related to this change?

All failed with the same error code:
```
BEGIN : coreclr_initialize failed - error : 0x80004005 [/__w/1/s/src/mono/msbuild/aot-compile.proj]
END : coreclr_initialize failed - error : 0x80004005 [/__w/1/s/src/mono/msbuild/aot-compile.proj]
/__w/1/s/src/mono/msbuild/aot-compile.proj(19,9): error MSB3073: The command "/__w/1/s/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/corerun /__w/1/s/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/xunit.runner.utility.netcoreapp10.dll" exited with code 255.
    0 Warning(s)
    10770 Error(s)
```
Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=5862&view=logs&j=ac444259-14dc-5e9e-4846-f4aabcc22cf0&t=616bd7d0-b458-5b0a-3812-dbea2ad61cca

**Comment by kunalspathak** [comment]
Original PR didn't had those. The failure seems very fundamental that it failed to initialize coreclr. May be rerun?

**Comment by carlossanlop** [comment]
@jkotas @MichalStrehovsky  do the above llvmaot failures look familiar to you? Should I open an issue? I am unsure if any of the open issues with that error number is the same: https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+0x80004005

**Comment by MichalStrehovsky** [comment]
> @jkotas @MichalStrehovsky do the above llvmaot failures look familiar to you? Should I open an issue?

llvmaot is Mono. Looks like #72114. Cc @lambdageek @SamMonoRT

**Comment by carlossanlop** [comment]
Approved and signed off.
CI failure determined to be unrelated.
Ready to merge. :shipit:

**Pull request merged**
