### PR TITLE
[wasm] Wasm.Build.Tests: Use the default cache for emcc

### PR DESCRIPTION
**Pull request by radical**
On windows, WBT overrides the cache path to a new directory -
`~/.emscripten-cache`. Because of this the first native build takes a
long time (~16-20mins) as it run `embuilder build MINIMAL`.

Instead, we can use the new workload pack for emscripten Cache, which is
the default behavior. So, not overriding the cache path improves the
test run times on windows by ~17-20mins.

- Also, use multithreading with `robocopy`, which saves ~5mins .

### CODE REVIEW

**Comment by pavelsavara** [comment]
Should we also drop it here https://github.com/dotnet/runtime/blob/c075692ea8b786b52e351d13206b0a8b6c4f17dc/eng/testing/tests.wasm.targets#L107

**Comment by radical** [comment]
That requires some extra work, and I'm working on that in a separate PR.

**Review by lambdageek — APPROVED** [review]

**Pull request merged**
