### PR TITLE
[LoongArch64] change instructions in IMAGE_REL_LOONGARCH64_PC & fix genCodeForJumpCompare

### PR DESCRIPTION
**Pull request by sunlijun-610**
Change pcaddu12i to pcalau12i in relocation IMAGE_REL_LOONGARCH64_PC.
Fix GT_CNS_INT generation in CodeGen::genCodeForJumpCompare.

### CODE REVIEW

**Comment by sunlijun-610** [comment]
> @sunlijun-610 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

**Review by shushanhf — APPROVED** [review]
Hi, @jakobbotsch @MichalStrehovsky 

This PR is the first patch before pushing the Native-AOT for LoongArch64, which followed the llvm's relocation.

LGTM
Thanks

**Review by MichalStrehovsky — APPROVED** [review]
Changes under tools look good to me!

**Comment by shushanhf** [comment]
Hi, @jakobbotsch 
Could you please review this PR?
Thanks!

**Comment by shushanhf** [comment]
> Hi, @jakobbotsch Could you please review this PR? Thanks!

Hi, @jakobbotsch 
Could you please review this PR?

**Review by jakobbotsch — APPROVED** [review]

**Comment by am11** [comment]
> This PR is the first patch before pushing the Native-AOT for LoongArch64, which followed the llvm's relocation.

both @filipnavara and I are looking forward to it. 😉

**Comment by shushanhf** [comment]
> > This PR is the first patch before pushing the Native-AOT for LoongArch64, which followed the llvm's relocation.
> 
> both @filipnavara and I are looking forward to it. 😉

we will push the second PR later.

**Pull request merged**
