### PR TITLE
[mono] Remove more multi-domain functionality

### PR DESCRIPTION
**Pull request by CoffeeFlux**
Still an issue in method to ir that I need to figure out, so draft.

### CODE REVIEW

**Comment by vargaz** [comment]
Note that whenever the current domain is set is used to detect whenever a thread is attached to the runtime or not in a couple of places, so the 'current_domain' TLS var and its set/get cannot be currently removed.

**Comment by lambdageek** [comment]
I agree with Zoltan, I don't think we should get rid of the domain TLS var yet.

I think we'll end up living with `MonoDomain` for a while.  But we should think of it as `MonoRootDomain` or `MonoRoot` or something - it's basically a singleton type now.  It's still useful to have as a place to put global state, and for now it's ok to store a reference to it in the TLS var as a sentinel for whether the thread is attached or not.

It would be nice eventually to whittle down the number of TLS vars that mean "this thread is attached in some way" (ie, MonoThreadInfo, jit_tls, and current domain) but I think that can be done separately from the current cleanup that just removes passing a domain around as an argument.

**Comment by CoffeeFlux** [comment]
> I think we'll end up living with MonoDomain for a while. But we should think of it as MonoRootDomain or MonoRoot or something - it's basically a singleton type now.

Agreed, though actually renaming it right now seems painful.

> It would be nice eventually to whittle down the number of TLS vars that mean "this thread is attached in some way" (ie, MonoThreadInfo, jit_tls, and current domain) but I think that can be done separately from the current cleanup

I don't really like the thread attach/detach code, so I'll split the actual TLS simplification off into a separate PR but don't want to abandon the effort since I think simplifying that would be valuable. I think this PR can still remove most of the actual domain check/set calls that _use_ the TLS variable.

**Comment by vargaz** [comment]
The test failures are relevant.

**Comment by vargaz** [comment]
Made a PR with a more piece-by-piece approach in
https://github.com/dotnet/runtime/pull/48291

**Pull request closed without merging**
