### PR TITLE
Fixing where `ClearContained` is called for certain Arm64 cast ops

### LINKED ISSUE #76511: Assertion failed '!op1->isUsedFromMemory()'
"runtime-coreclr outerloop" R2R-CG2 test failures on arm64 in JIT\\Regression\\JitBlue\\Runtime_76273\\Runtime_76273\\Runtime_76273.cmd:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=37881&view=ms.vss-test-web.build-test-results-tab&runId=755738&resultId=108102&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
    JIT\Regression\JitBlue\Runtime_76273\Runtime_76273\Runtime_76273.cmd [FAIL]
      
      Return code:      1
      Raw output file:      D:\h\w\B49209AE\w\A7DB0945\uploads\Reports\JIT.Regression\JitBlue\Runtime_76273\Runtime_76273\Runtime_76273.output.txt
      Raw output:
      BEGIN EXECUTION
      Runtime_76273.dll
              1 file(s) copied.
       7:07:25.95
      Response file: D:\h\w\B49209AE\w\A7DB0945\e\JIT\Regression\JitBlue\Runtime_76273\Runtime_76273\Runtime_76273.dll.rsp
      D:\h\w\B49209AE\w\A7DB0945\e\JIT\Regression\JitBlue\Runtime_76273\Runtime_76273\IL-CG2\Runtime_76273.dll
      -o:D:\h\w\B49209AE\w\A7DB0945\e\JIT\Regression\JitBlue\Runtime_76273\Runtime_76273\Runtime_76273.dll
      --targetarch:arm64
      --verify-type-and-field-layout
      --method-layout:random
      -r:D:\h\w\B49209AE\p\System.*.dll
      -r:D:\h\w\B49209AE\p\Microsoft.*.dll
      -r:D:\h\w\B49209AE\p\mscorlib.dll
      -r:D:\h\w\B49209AE\p\netstandard.dll
      -O
      " "dotnet" "D:\h\w\B49209AE\p\crossgen2\crossgen2.dll" @"D:\h\w\B49209AE\w\A7DB0945\e\JIT\Regression\JitBlue\Runtime_76273\Runtime_76273\Runtime_76273.dll.rsp"   -r:D:\h\w\B49209AE\w\A7DB0945\e\JIT\Regression\JitBlue\Runtime_76273\Runtime_76273\IL-CG2\*.dll"
      D:\a\_work\1\s\src\coreclr\jit\codegenarm64.cpp:4543
      Assertion failed '!op1->isUsedFromMemory()' in 'Program:M11(C0,short)' during 'Generate code' (IL size 87; hash 0xb0dcda0a; FullOpts)
      
       7:07:33.84
      Crossgen2 failed with exitcode - -2147483645
      Test Harness Exitcode is : 1
```

@dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/76511

### CODE REVIEW

**Comment by tannergooding** [comment]
AV failures need: https://github.com/dotnet/runtime/pull/76532

**Comment by tannergooding** [comment]
The failure for Runtime_40607 is #76546

**Comment by tannergooding** [comment]
CC. @dotnet/jit-contrib 

This resolves #76511. Failures all look to be known. It might be desirable to wait to merge this until after #76532 goes in since that will fix most of the AVs.

**Review by BruceForstall — APPROVED** [review]

**Comment by tannergooding** [comment]
Merged in main to pickup #76532

**Comment by tannergooding** [comment]
jitstress failures were all known:
* https://github.com/dotnet/runtime/issues/76550 - JIT\Regression\JitBlue\Runtime_72926\Runtime_72926\Runtime_72926.cmd
* https://github.com/dotnet/runtime/issues/76507 - JIT\jit64\opt\lur\lur_02\lur_02.cmd
* https://github.com/dotnet/runtime/issues/76546 - JIT\Regression\JitBlue\Runtime_40607\Runtime_40607\Runtime_40607.cmd

**Pull request merged**
