### PR TITLE
Fold "X >= 0 && X < NN" to "X u< NN"

### PR DESCRIPTION
**Pull request by EgorBo**
Fold e.g. `X >= 0 && X < arr.Length` to `(uint)X < arr.Length`. Not too many diffs because:
1) We already use `uint` hack (I call it a **hack** because IMO it's not how most developers check ranges. Also, it's not "use checked context" [friendly](https://github.com/dotnet/runtime/issues/78214)) everywhere in BCL
2) For arrays we need to land https://github.com/dotnet/runtime/pull/93531 first (and that depends on a fix for a CSE issue)

```cs
static void Test(Span<int> span, int i)
{
    if (i >= 0 && i < span.Length)
        Console.WriteLine("In range!");
}
```
```diff
; Method InitblkPerformanceIssue.Program:Test(System.Span`1[int],int) (FullOpts)
       sub      rsp, 40
-      test     edx, edx
-      jl       SHORT G_M55087_IG04
       cmp      edx, dword ptr [rcx+0x08]
-      jge      SHORT G_M55087_IG04
+      jae      SHORT G_M55087_IG04
       mov      rcx, 0x1AC80209320      ; 'In range!'
       call     [System.Console:WriteLine(System.String)]
G_M55087_IG04:
       nop      
       add      rsp, 40
       ret      
-; Total bytes of code: 35
+; Total bytes of code: 31

```

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Would still prefer we sort these out earlier, but also like having some "defense in depth."

> 1. We already use `uint` hack (I call it a **hack** because IMO it's not how most developers check ranges. Also, it's not "use checked context" [friendly](https://github.com/dotnet/runtime/issues/78214)) everywhere in BCL

Once take this change, can we undo some of these?

**Review by AndyAyersMS — APPROVED** [review]

**Comment by markples** [comment]
@EgorBo just a few notes on the test as I looked through it due to #94146.  Some are just ideas to make test authoring easier in the future and might not be worth retroactive changes

- The messages in the test exceptions have copy/paste errors.  I believe that TestEntryPoint could be split into 3 (or 4) different [Fact] methods and then the messages wouldn't be needed at all as the test names would suffice.
- I think `Assert.Throws` could be used instead of reimplementing it.
- Are Test_Span1 and Test_Array identical?  I don't understand the comment in Test_Array about arr being null since arr is a Span.

**Comment by BruceForstall** [comment]
Please cc @dotnet/jit-contrib for JIT PRs.

**Comment by EgorBo** [comment]
> Please cc @dotnet/jit-contrib for JIT PRs.

It wasn't merged by me, I planned to ask for review once I am back from vacation 🤷‍♂️ It's unfortunate that `return 100;` typo didn't make CI red.

@markples thanks, will apply the suggestions as part of some other PR

**Comment by kunalspathak** [comment]
> It wasn't merged by me, I planned to ask for review once I am back from vacation

Sorry, i was going through the "approved PRs" list and merged this one.

>  It's unfortunate that return 100; typo in the test didn't make CI red.

Do we know why this happened and if there is a fix needed?

**Comment by EgorBo** [comment]
> Do we know why this happened and if there is a fix needed?

https://github.com/dotnet/runtime/pull/94146#issuecomment-1786058264 it's not clear yet

**Pull request merged**
