### PR TITLE
Try re-enabling System.Transactions.Local tests on Arm64

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Review by roji — APPROVED** [review]
So are we saying we're no longer able to repro any failure, including with jitstress? The would likely mean that the GUID interop fixes (#74226, #74570) made this go away (though IIRC @kunalspathak was able to see the bug with them, 
https://github.com/dotnet/runtime/pull/74226#issuecomment-1220809176).

In any case, we can certainly see if the failures reappear in CI other elsewhere.

**Comment by jkotas** [comment]
None of the failures are related to System.Transactions

**Comment by roji** [comment]
@jkotas I know, but they were intermittent before as well.

**Comment by jkotas** [comment]
> @jkotas I know, but they were intermittent before as well.

The System.Transactions tests were run on Win Arm64 multiple times in the CI, and also locally. No crashes observed.

**Pull request merged**
