### PR TITLE
Change Mono runtime to use static linked c-runtime on debug builds.

### PR DESCRIPTION
**Pull request by lateralusX**

### CODE REVIEW

**Comment by jkotas** [comment]
> use static linked c-runtime, aligning with CoreCLR

CorecCLR does not use statically linked c-runtime:

image

We copy all the necessary files next to coreclr.dll.

**Comment by lateralusX** [comment]
@jkotas Looked in the generated .sln and there the settings was /MTd for debug and /MT for release and when I looked at imports for runtime\artifacts\bin\coreclr\Windows_NT.x64.Debug\coreclr.dll it didn't have any dependecies on c-runtime.

**Comment by jkotas** [comment]
> Windows_NT.x64.Debug\coreclr.dll it didn't have any dependecies on c-runtime.

We statically link debug builds, but release builds are linked dynamically: https://github.com/dotnet/runtime/blob/master/src/coreclr/configurecompiler.cmake#L100

**Comment by lateralusX** [comment]
I was looking at the release config in the solution generated for debug build, that's why it was the same on both debug and release. So to sum up, static linked C-runtime on debug and dynamic linked on release. If we do that on Mono we will do similar to what I guess the static on debug also resolve the issues we see on CI where we don't have debug version of c-runtime on CI.

**Review by vargaz — APPROVED** [review]

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/pull/4381 was the CoreCLR that introduced the CRT scheme that we are using. I am not sure where the reasons for this complex setup are still valid, but we are definitely not statically linking the whole CRT in the shipping bits.

**Comment by lateralusX** [comment]
Updated to only static link in debug build, but keep dynamic linked c-runtime in release builds.

**Comment by lateralusX** [comment]
Next step to align with coreclr would be to static link whats coming in from vcruntime140.dll even in release build, https://github.com/dotnet/coreclr/pull/4381.

**Comment by lateralusX** [comment]
https://github.com/dotnet/runtime/pull/33853

**Pull request merged**
