### PR TITLE
Set fgOptimizedFinally flag correctly

### PR DESCRIPTION
**Pull request by davidwrighton**
- Initialize to 0 at compiler startup
- Set flag when finally cloning optimization kicks in

Fixes non-deterministic generation of nop opcodes into ARM32 code

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/jit-contrib

**Comment by davidwrighton** [comment]
Jit-diffs show no difference, but I couldn't get a reliable printout. There are problems where the baseline crashes unpredictably on my system, but generates data on re-run. I then manually diffed the generated dasm files and they are all identical.

**Comment by echesakovMSFT** [comment]
@BruceForstall

**Review by echesakov — APPROVED** [review]
Looks good to me.
Thank you, David, for tracking this down!

**Pull request merged**
