### PR TITLE
[wasm][debugger] Don't need to escape special characters anymore

### LINKED ISSUE #76777: Cannot hit breakpoint when Blazor wasm project path contains special characters
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

This problem occurs when the created project path contains the # character

### Expected Behavior

Hit breakpoint

### Steps To Reproduce

Create a Blazor WASM project with the # character in the project path

### Exceptions (if any)

_No response_

### .NET Version

6.0.400

### Anything else?

image
image

### PR DESCRIPTION
**Pull request by thaystg**
I removed the code and it works well debugging from VS and also from Chrome, also the debugger-tests works well without this code.

Fixes https://github.com/dotnet/runtime/issues/76777

### CODE REVIEW

**Comment by marek-safar** [comment]
I think we want to backport this to 7.x

**Review by ilonatommy — APPROVED** [review]
Works fine.

**Comment by radical** [comment]
@thaystg @ilonatommy Was this reproducible only with Blazor? Was this reproducible without VS?

**Comment by ilonatommy** [comment]
State before the fix. Special signs in path (#): 
- wasmbrowser on Browser: OK
- wasmbrowser on VS: OK
- blazorwasm on Browser: OK
- blazorwasm on VS: OK

Diacritic signs in path (żółw):
- wasmbrowser on Browser: not OK (a mess in finding files)
- wasmbrowser on VS: OK
- blazorwasm on Browser: not OK (files names are found but loaded without content and under a wrong tree)
- blazorwasm on VS: NOT OK

**Pull request merged**
