### PR TITLE
[mono] Fix read of image_info while raising image_unload event

### PR DESCRIPTION
**Pull request by stefan-sf-ibm**
While raising image_unload event `ep_rt_mono_write_event_module_unload` is called which itself calls `get_module_event_data` which accesses `image->image_info`. Thus set `image->image_info` to `NULL` after free.

### CODE REVIEW

**Comment by vargaz** [comment]
Might be better to call image_unloaded earlier instead of calling it on a basically freed structure.

**Comment by lambdageek** [comment]
@lateralusX @josalem What's the difference between the `ModuleUnloading` and `ModuleUnloaded` events?  Is the timing important?

I think `mono_profiler_module_unloaded` probably shouldn't call `get_module_event_data` (or maybe do it  in a special mode where it only accesses the bare minimum information - the module path).  Alternately if we know in mono that `ModuleUnloading` is always followed by `ModuleUnloaded`, maybe we can access the information we need early and store it away in "Unloading" until the corresponding "Unloaded" event needs it.

**Comment by lambdageek** [comment]
I would also not be opposed to a new MonoProfiler `image_unloaded_with_details` event where we just pass the path and guid as event arguments.

**Comment by lateralusX** [comment]
For the unload profiler event it looks like a lot of things will be freed up in the image struct, any most is just releasing memory, so moving the event up to a location where data is still valid is probably the more safe alternative.

**Comment by lateralusX** [comment]
> I think `mono_profiler_module_unloaded` probably shouldn't call `get_module_event_data` (or maybe do it in a special mode where it only accesses the bare minimum information - the module path)

I think to problem is the design of the profiler API, if it pass a data structure as part of its API, that needs to be accessible or NULL:ed out, if not, it should use a different API altogether, not passing a Image * as parameter, or we should fire the event at a location where the data is still around.

**Comment by lambdageek** [comment]
> For the unload profiler event it looks like a lot of things can be freed up in the image struct, and most logic in `mono_image_close_except_pools` is mainly releasing memory, so moving the event up to a location where data is still valid is probably the more safe alternative.

Sounds good to me

@stefan-sf-ibm could you update this PR to move the `image_unloaded` event earlier.  Setting `image_info` to null is good, too, so leave that in there.

**Comment by vargaz** [comment]
image_unloaded should probably come after other events caused by the unloading, i.e. references to other images are dropped causing them to be unloaded as well.

**Comment by stefan-sf-ibm** [comment]
Pushed the unloaded event upwards which means it is pretty close to the unloading event, now. Anyhow, it should come before `mono_image_storage_close` I guess. At that point in time at least `name`, `filename` etc. are also available.

**Comment by lateralusX** [comment]
Looks like mono_image_close_except_pools_all will trigger more unload events.

**Comment by lateralusX** [comment]
So what `get_module_event_data` looks at during the unloaded event is mainly the following image fields:

image->assembly (just converting it to uint64_t)
image->dynamic
image->aot_module
image->filename
image->image_info
image->guid

and for the EventPipe unloaded event, we are pretty much only using:

pointer to image itself, that should still be valid.
image guid
image->filename, if not NULL.

so one option, could be to make sure that atleast these fields are still available when we do the profiler callback.

**Comment by lateralusX** [comment]
So maybe delay parts of this, https://github.com/dotnet/runtime/blob/58fa90be46a9e4ca96ee47ed44c114f5bcde8a39/src/mono/mono/metadata/image.c#L2165 until after profiler callback and set image->image_info to NULL as you already did, will at least take care of the fields currently in use, but as previously said, the underlying issue is with the profiler API, handing out access to a struct with unknown state.

**Review by vargaz — APPROVED** [review]

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=67138) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=67138) before we can accept your contribution.<br/><br/>:x: stefan-sf-ibm [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=67138)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=67138) it.</sub>

**Comment by lateralusX** [comment]
Problem with changing existing API is that this is a public API, so that would break other profiler providers, if we are going down that route we will need to add a new API for the unloaded event, aligned with what @lambdageek suggested above and then let EventPipe profiler provider hook up to the new API, instead of using the old. Profiler still needs to fire both events (but inexpensive if there are no listeners).

`get_module_event_data` checks that image->image_info is not NULL before it tries to calculate `module_il_pdb_path` and `module_il_pdb_age`, https://github.com/dotnet/runtime/blob/0e35b8d33851efde52e4e7aaadac239f3c2e97d5/src/mono/mono/eventpipe/ep-rt-mono.c#L3146, so if we NULL that field when we close the underlying image, that code should not try to access underlying data structures.

**Comment by stefan-sf-ibm** [comment]
Right I somehow managed to neglect the fact that this is a public API. Sorry for the noise.

I will restore the old commit and delay freeing of `image->filename` and `image->guid` only in case of `!debug_assembly_unload` (as previously).

**Comment by lateralusX** [comment]
Failure in debugger tests might be related, https://dev.azure.com/dnceng/public/_build/results?buildId=1688158&view=logs&j=2cb5cbbb-10b2-57f5-cb06-88ab02df11cd&t=8e3b5183-1166-552f-0d9e-c49b4956b6ef

**Comment by lateralusX** [comment]
It could be a flaky, just saw that test seemed to have code that read out the image GUID and did some lazy loading. I rerun the test suite on CI to see if it fails again.

**Comment by lateralusX** [comment]
All pass, when not setting image->guid to NULL, let's try to revert it back and see test results.

**Pull request merged**
