### PR TITLE
Fix invalid optimization of (-1 * -A) + A

### LINKED ISSUE #61077: JIT: Invalid optimization of (-1 * -A) + A
### Description

The following program computes a wrong result when optimizations are turned on:

### Reproduction Steps

```csharp
// Generated by Fuzzlyn v1.5 on 2021-10-31 17:07:34
// Run on X86 Windows
// Seed: 493124741082014941
// Reduced from 80.3 KiB to 0.2 KiB in 00:02:01
// Debug: Outputs 2
// Release: Outputs 0
public class Program
{
    public static long s_14 = 1;
    public static void Main()
    {
        long vr7 = s_14;
        ushort vr6 = (ushort)((-1 * -vr7) + vr7);
        System.Console.WriteLine(vr6);
    }
}
```

### Expected behavior

Same result.

### Actual behavior

Differing result.

### Regression?

Does not repro in .NET 5.

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

We hit both transforms in this block:
https://github.com/dotnet/runtime/blob/1d08e154b942a41e72cbe044e01fff8b13c74496/src/coreclr/jit/morph.cpp#L12379-L12427

It leads to the following transformation:
```scala
fgMorphTree (before 9):
               [000014] ------------              ▌  ADD       long  
               [000012] ------------              ├──▌  MUL       long  
               [000009] ------------              │  ├──▌  CNS_INT   long   -1
               [000011] ------------              │  └──▌  NEG       long  
               [000010] ------------              │     └──▌  LCL_VAR   long   V00 loc0         
               [000013] ------------              └──▌  LCL_VAR   long   V00 loc0         

fgMorphTree (after 9):
               [000014] ------------              ▌  SUB       long  
               [000013] -----+------              ├──▌  LCL_VAR   long   V00 loc0         
               [000010] -----+------              └──▌  LCL_VAR   long   V00 loc0         
```

Seems difficult to hit this, so probably does not need a backport. I can submit a fix.

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by jakobbotsch**
We were hitting both transforms in this block, but the first transform
changes the node from GT_ADD to GT_SUB, while the second transform is
valid only for GT_ADD. It is difficult to have natural code that hits
both of these transforms, so I have just made them mutually exclusive
instead of rechecking the oper in the second one.

No SPMI diffs.

Fix #61077

### CODE REVIEW

**Comment by kasperk81** [comment]
regressed in cecbbfb87c1bcf661d64d799df1cb7bad325f447, so applicable to 6.0 too?

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

> regressed in cecbbfb, so applicable to 6.0 too?

Yes, it is. Not sure if this meets the bar for a backport, however. @dotnet/jit-contrib any opinions? Personally, I believe the pattern to be quite unnatural, e.g. we have no occurences in our own collections. But the fix is very low risk as well.

**Comment by kasperk81** [comment]
> we have no occurences in our own collections.

I can't comment on how "complete" this collection is, but looking at the past few cases you have discovered via fuzzlyn and fixed, we can't be too confidence about test coverage. :)
In real-world code, a misbehaving `(-1 * -A) + A` expression in any construct (`A` is static / local / whatnot)  is too fundamental to be taken lightly.

**Comment by EgorBo** [comment]
I'd backport this, the pattern to reproduce the issue is too simple and can appear after inlining

**Comment by EgorBo** [comment]
e.g.:
```csharp
using System;
using System.Runtime.CompilerServices;

class Runtime_61077
{
    static void Main() => Console.WriteLine(Go(1));

    static long Test2(long x) => -x;

    static long Test(long x) => -1 * Test2(x);

    [MethodImpl(MethodImplOptions.NoInlining)]
    static long Go(long x) => Test(x) + x;
}
```
prints 0 in Release and 2 in Debug

**Comment by jakobbotsch** [comment]
> I can't comment on how "complete" this collection is, but looking at the past few cases you have discovered via fuzzlyn and fixed, we can't be too confident about test coverage. :)

I'm not talking about test coverage. No occurences in this case means that in our collections (all library code, System.Private.CoreLib, benchmarks and all tests) we don't see the pattern `(-1 * -A) + A` anywhere. We did not have test coverage to catch many of the previously found issues through fuzzing, but it is still quite common that we find occurrences once fixed and we can check the diffs.

> In real-world code, a misbehaving (-1 * -A) + A expression in any construct (A is static / local / whatnot) is too fundamental to be taken lightly.

I agree, but we also have to prioritize these issues and the fact that they are fuzzer found instead of customer reported usually means a lower priority (as we can't gauge impact well). 

> I'd backport this, the pattern to reproduce the issue is too simple and can appear after inlining. The fix is definitely safe.

Ok, I'll make sure this meets the bar and submit it. I understand that we can hit this in various situations, but we don't in all our code.

**Comment by kasperk81** [comment]
> all library code, System.Private.CoreLib, benchmarks and all tests

this is indeed a good matrix, however, all code in runtime and aspnet follow certain set of coding conventions (like usage of yoda is discouraged), which misses many mathematical expressions used in code out in the wild, that may or may not be dynamically generated by data.

> as we can't gauge impact well

agreed, but from a different perspective, if "expressions are important and fundamental in any programming language", then _any_ issue arising in that area has the same level of concern.

**Comment by BruceForstall** [comment]
Looks like we should also add an "else" here for clarity: https://github.com/dotnet/runtime/blob/24e7a4a1a101d91b6666dc6f44137574246fdd9c/src/coreclr/jit/morph.cpp#L12183, added at the same time as this code being fixed. In that case, we can't get a bug (luckily) because the first case checks `!op1->OperIs(GT_NEG)` and the second case checks `op1->OperIs(GT_NEG)`, and `op1` isn't touched in the first optimization.

**Review by BruceForstall — APPROVED** [review]

**Comment by jakobbotsch** [comment]
I asked for an internal bar check and to check for impact we used grep.app to look for occurences on GitHub of this pattern. We did not find anything that would hit this in a straightforward way. Because of this and the fact that there is no customer (including ourselves) it was decided that we will hold off on the backport and watch for impact.

**Comment by jakobbotsch** [comment]
The test failures look like infra issues, the console log is basically empty and I see no failure.

**Comment by kasperk81** [comment]
> internal bar check

says a lot actually, does not inspire open source spirit at all

**Comment by jeffschwMSFT** [comment]
@kasperk81 servicing is a balance of risk and value.  Each issue has to be evaluated based on these metrics.  The things that were weighed for this issue were the undiagnosable nature of silent bad codegen, the current impact, and likely future impact.  We have taken this issue for our next release and will reevaluate for a future one.

**Pull request merged**
