### PR TITLE
Delete FX_PRODUCT_VERSION host key/value pair

### PR DESCRIPTION
**Pull request by jkotas**
It is no longer necessary now that the whole runtime is being built together in dotnet/runtime repo.

### CODE REVIEW

**Comment by jkotas** [comment]
Technical breaking change

**Comment by filipnavara** [comment]
I was pretty sure that BenchmarkDotNet and ML.NET used it at some point. However, I cannot find the reference in BDN so my memory could have been a bit wonky. The reference in ML.NET was removed 2 days ago (https://github.com/dotnet/machinelearning/pull/5047).

**Review by swaroop-sridhar — APPROVED** [review]

**Comment by swaroop-sridhar** [comment]
Is there a place where we document APIs no longer supported? We could recommend that 
`RuntimeInformation.FrameworkDescription` be used in place of `AppDomain.CurrentDomain.GetData("FX_PRODUCT_VERSION")` .

Some use of `FX_PRODUCT_VERSION` (ex in `machinelearning` repo) to detect whether the runtime is `netcoreapp3.1`, will continue to be true. 

`FX_PRODUCT_VERSION`  is not one of the arguments documented in [AppDomain.GetData()](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.getdata?view=netcore-3.1) description. so I think removing it is low risk.

**Comment by jkotas** [comment]
>  Is there a place where we document APIs no longer supported?

We document breaking changes. The breaking-change tag will make this change visible to that process.

**Pull request merged**
