### PR TITLE
add Http3LoopbackConnection.ShutdownAsync and use in AcceptConnectionAsync

### PR DESCRIPTION
**Pull request by geoffkizer**
Contributes to https://github.com/dotnet/runtime/issues/57779

Add a ShutdownAsync method on the HTTP3 loopback connection. This will send a GOAWAY frame to the client and wait for the client to close the connection gracefully. It will also eat connection abort exceptions if the client already has closed the connection.

Use this method in AcceptConnectionAsync, after the user's connection handling code has finished. The intent here is to avoid the kind of data loss seen in https://github.com/dotnet/runtime/issues/57779. and avoid HTTP3-specific one-offs to reenable tests as in https://github.com/dotnet/runtime/pull/58041.

Also, some fixes to GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly to work properly with these changes and clean up some unnecessarily complicated logic.

@ManickaP @CarnaViire

### CODE REVIEW

**Comment by ManickaP** [comment]
I ran this with the re-enabled test from #58041, it works nicely. I'd merge this and than I can merge my PR with just re-enabling the test.

**Review by ManickaP — APPROVED** [review]

**Comment by ManickaP** [comment]
We have some failing mock tests:
```
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Finalization_Http3_Mock.IncompleteResponseStream_ResponseDropped_CancelsRequestToServer [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Finalization.cs(33,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Finalization_Test.IncompleteResponseStream_ResponseDropped_CancelsRequestToServer()
        --- End of stack trace from previous location ---
```
Seems relevant.

**Review by ManickaP — APPROVED** [review]

**Comment by geoffkizer** [comment]
@karelz @ManickaP I believe we want to backport for RC2, right?

**Pull request merged**
