### PR TITLE
Delete the RequiresPreviewFeaturesAttribute from RefreshMemoryLimit

### PR DESCRIPTION
**Pull request by cshung**

### CODE REVIEW

**Review by mangod9 — APPROVED** [review]

**Comment by jkotas** [comment]
Also, submit PR to delete the preview label in the docs (https://learn.microsoft.com/en-us/dotnet/api/system.gc.refreshmemorylimit?view=net-8.0). The API docs for CoreLib API are not updated automatically.

**Comment by mangod9** [comment]
looks like there are api compat failures as part of build too

**Review by Maoni0 — APPROVED** [review]

**Comment by stephentoub** [comment]
@cshung, I assume you intend to backport this to release/8.0?

**Comment by cshung** [comment]
@stephentoub Yes, that is the intention.

**Pull request merged**
