### PR TITLE
Remove trim_whitespaces from editorconfig

### PR DESCRIPTION
**Pull request by Youssef1313**
See https://github.com/dotnet/sdk/pull/12865#discussion_r468743717

### CODE REVIEW

**Comment by jkotas** [comment]
Did you find this option problematic in dotnet/runtime repo? 

I have not run into any of the issues mentioned in the linked comment while working in dotnet/runtime.

**Comment by jkotas** [comment]
Maybe there are a few files where it may be causing problem, but I would think that the benefits outweighs it.

**Comment by stephentoub** [comment]
I don't understand why we're removing this. It's very helpful.

**Comment by Youssef1313** [comment]
@stephentoub @jkotas Thanks for reviews. But as stated in sharwell's comment:

> Some files have significant trailing whitespace (e.g. Markdown, C# verbatim string literals)

I think if, **now** there aren't significant trailing whitespaces, I think it's not guaranteed that this will remain the same in **future**.

**Comment by stephentoub** [comment]
We have an analyzer that fails the build if there's any trailing whitespace in C# files.

And end-of-line invisible code is practically impossible to maintain.

**Comment by Youssef1313** [comment]
@stephentoub Thanks for clarifying that. In that case, it would be possibly to exclude this option for markdown only? (I haven't seen an example in this repo where markdown trailing spaces are significant, but I've seen that in dotnet/docs before).

Also, can I ask which analyzer is used for the trailing whitespaces in C# files?

**Comment by Youssef1313** [comment]
@stephentoub Another solution for the markdown files is to enable markdownlint with [MD009](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md009---trailing-spaces) rule enabled.

**Pull request closed without merging**
