### PR TITLE
[release/6.0-staging] [Mono] Fix offset calculation for nested struct, when pinvoke is enabled

### PR DESCRIPTION
**Pull request by fanyang-mono**
Backport of #91292 to release/6.0-staging

/cc @fanyang-mono

## Customer Impact
Prior to this change, the offset of fields was calculated incorrectly for nested struct when PInvoke is enabled. One of the Android customers hit an assertion when build an app.

## Testing
Added a new test, which passed on CI. 
Validated customer's use case locally. It works correctly now.

## Risk
Low risk.

### CODE REVIEW

**Comment by carlossanlop** [comment]
@fanyang-mono if this is ready, can you please request a code review sign-off and also send an email to Tactics requesting approval? 

September 10th is the code complete date for the October Release.

cc @SamMonoRT

**Review by lambdageek — APPROVED** [review]

**Review by SamMonoRT — APPROVED** [review]

**Comment by fanyang-mono** [comment]
@SteveMCarroll approved via email.

**Pull request merged**
