### PR TITLE
Remove DAM from design-time attributes

### PR DESCRIPTION
**Pull request by agocke**
I noticed these attributes were bringing in a lot of designer code in WinForms due to the DAM annotation. However, I don't think the DAM annotation is appropriate for attributes meant for design time. I would instead expect the code using these attributes to get RUC, or find a different way to preserve the code.

### CODE REVIEW

**Comment by agocke** [comment]
@eerhardt @LakshanF @vitek-karas @sbomer I would appreciate your thoughts here

When looking at WinForms I noticed that most of the designer stuff was being brought in by these attributes, which are meant for design-time-only. The existing codebase tried to make the retrieval methods trim-compatible by annotating these attributes. But I'm not sure that's right. Aside from the fact that it didn't work, and those retrieval methods are still RUC for other reasons, I don't think making those methods safe is the right answer.

If the intention of design-time is to only run during build, not during publish, I would actually expect this stuff to produce warnings if it were ever being kept in a production app (i.e., an app where trimming is enabled). If the user wanted to preserve this stuff for production, I would expect they would use some other attribute or code to do so.

This could technically be considered a breaking change, but since all the main usage points are RUC, I don't think it's meaningful.

**Review by eerhardt — COMMENTED** [review]
We should probably update the RUC message on

https://github.com/dotnet/runtime/blob/4d69ab7d59e7a7ded3aaf56789740b0698f07b17/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs#L2345-L2355

Since this is now another reason (probably a main reason) why that method is incompatible.

The same goes for the usages of EditorAttribute:

https://github.com/dotnet/runtime/blob/4d69ab7d59e7a7ded3aaf56789740b0698f07b17/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/PropertyDescriptor.cs#L236-L267

https://github.com/dotnet/runtime/blob/4d69ab7d59e7a7ded3aaf56789740b0698f07b17/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/TypeDescriptor.cs#L955-L965

**Comment by eerhardt** [comment]
We had a bit of discussion on this in https://github.com/dotnet/runtime/pull/49467#discussion_r592383280.

cc @RussKie @vitek-karas

**Comment by vitek-karas** [comment]
Just a note on making the app smaller - another consideration might be to completly remove these attributes during trimming. That would in itself "fix" the problem with the DAM, but we could/should change that as well I think.

**Comment by agocke** [comment]
> Just a note on making the app smaller - another consideration might be to completly remove these attributes during trimming

Yeah, that's another approach, but I thought this one was actually simpler. The current design implies that "EditorAttribute" and "DesignerAttribute" intend to preserve stuff in your app (due to the DAM annotation) -- I think that's backwards. I would expect most people would think the target code should be trimmed away

**Comment by agocke** [comment]
Also @JeremyKuhne

**Comment by RussKie** [comment]
A dam question, what's DAM (pun intended)? :)

A lot of designer attributes may required for the PropertyGrid control to function at the runtime...

**Comment by agocke** [comment]
> [RussKie](https://github.com/RussKie) [on Mar 16, 2021](https://github.com/dotnet/runtime/pull/49467#discussion_r595638213)
These attributes can be and are used at runtime by [PropertyGrid control](https://docs.microsoft.com/dotnet/api/system.windows.forms.propertygrid), and can be used by custom designers (e.g. a report viewer)

This is unfortunate. However, I don't think it changes the calculus that much.

From what I can see, WinForms trimming is not viable if the designer stack is brought in. It's all fundamentally unsafe. That implies that DesignerAttribute and EditorAttribute alone can't be sufficient to root code.

So it still seems to follow that we should remove DAM from these attributes. The only question is if PropertyGrid can somehow be made safe in another way, or if we will just have to annotate PropertyGrid as RUC.

**Comment by RussKie** [comment]
I moved out of the Windows Forms team, @KlausLoeffelmann may be able to provide deeper insights.

**Comment by JeremyKuhne** [comment]
@agocke I believe that `EditorAttribute` is the only one we really need to make work (for `PropertyGrid`).

**Comment by KlausLoeffelmann** [comment]
> A lot of designer attributes may required for the [PropertyGrid control](https://learn.microsoft.com/dotnet/api/system.windows.forms.propertygrid) to function at the runtime...

Yes, but I would consider this to be a niche case.
We have been thinking about a Project feature flag, which would indicate that an App opt out of Designer functionality (like using Editors in the PropertyGrid, or even Custom Type Descriptors).

The "only" thing to solve for your average WinForms LOB App is reading resource files and DataBinding. I am currently working on the side on a Prototype to make DataBinding type safe: As long as we have customers wire-up the binding definition for their Forms/UserControls at design-time, we _know_ both the data source/property source and the data destination/property destination. And since we generate that `Binding` class code for `InitializeComponent` anyway (since 17.6 via Roslyn, btw!), we should as well be able to generate that type information in a way, that a type-safe `Binding<Tsource, Tdestination>` would principally work the same way as the existing, just not by pushing and pulling the data via reflection.

I haven't looked into the resource topic, yet, though, but there should be a similar approach possible.

**Comment by agocke** [comment]
> We have been thinking about a Project feature flag, which would indicate that an App opt out of Designer functionality (like using Editors or even Custom Type Descriptors in the PropertyGrid scenario).

Yeah, that's another alternative to making PropertyGrid RUC -- use a feature flag to remove the Editor-specific functionality. As long as that's an acceptable user experience, I think that's a good path forward.

Broadly, I think the question in this PR is: do we expect every `Editor` or `Designer` target to be trim-compatible? If not, we run into a real problem where the attribute forces the type to be kept, and then the type produces unsolvable warnings because it wasn't designed to be trim-compatible.

By removing the annotation on the above types, we basically say, "this attribute is not supported when trimming." It doesn't necessarily mean that the types can't be preserved or used in a different way, it just means that the given attributes won't be enough to keep the targets around.

**Comment by KlausLoeffelmann** [comment]
> By removing the annotation on the above types, we basically say, "this attribute is not supported when trimming." It doesn't necessarily mean that the types can't be preserved or used in a different way, it just means that the given attributes won't be enough to keep the targets around.

Makes perfect sense to me!

**Comment by MichalStrehovsky** [comment]
> This could technically be considered a breaking change, but since all the main usage points are RUC, I don't think it's meaningful

It will likely break https://github.com/meziantou/Meziantou.Framework/blob/ba361873c94491e459c81862b4b9b6abee8189ac/src/Meziantou.AspNetCore.Components/GenericFormField.cs#L212 (the repo does have references to `IsTrimmable` as well but not sure if this is already trimmable).

The upswing from doing this is probably worth the break. We just have to make a breaking change notice and explain the upswing.

Alternatively we could strip the attribute under a feature switch. This way people can still opt into the old semantic. #92043 has the diff to apply because I already experimented with it in the past. But I hate suggesting this because I detest feature switches and I hate attribute stripping as well because they require careful emulation during F5 debug time that breaks down for unit testing... and attribute stripping cannot even be emulated.

**Comment by KlausLoeffelmann** [comment]
> The argument that would persuade me the other way is that EditorAttribute is not meant to be a design-time attribute.

Especially for WinForms App, the definition of something being design-time or run-time is a bit fuzzy. After all, the WinForms Designer itself is actually _running_ at the user's design time.

What I mean is: Folks are using the WinForms Property Browser Control for an easy way to collect for example a large amount of settings data. I don't think that that is the most frequent usage, but it certainly happens. Those cases would be qualifying as using Design-time functionality at runtime, especially, when they are authoring custom type editors which are called for a certain type through the property browser at (then) runtime.

I think, there are workarounds around this, which could be trimmable, but the worst case would be, that those kinds of apps would not be able to use a feature flag (at least in the first iteration) and would be excluded from trimming.

**Comment by agocke** [comment]
Yup, to be clear I expect there will be many people who are taking advantage of designer functionality at runtime for a variety of different reasons. However, the scope of making everything built for design-time be compatible with trimming is... challenging, if it's even possible. I think those apps are fine as is and should continue working -- they just won't be compatible with trimming without modification.

**Comment by MichalStrehovsky** [comment]
> ILLink will at least warn on attempts to use the attribute type. Would you consider it good enough if we had ILC/analyzer support for this? @MichalStrehovsky

If the analyzer could warn about this, it would alleviate some of my concerns. I don't know if it's possible with the current attribute stripping design. And we'd still have a hole in reflection APIs that don't take the attribute type as a parameter (they just list all attributes). We'd need to mark those as trim-unsafe and that might be a hard to swallow pill.

Maybe better to open a separate issue for those conversations. I don't know if there's a way to make these experiences _good_. It might be that this is a mechanism we need to use when retrofitting trimming into things designed before trimming because nothing else is possible. But we'd advise against using these mechanism in any _new code_ and not spend time designing experiences around it.

**Comment by agocke** [comment]
@eerhardt Anything else?

**Review by eerhardt — APPROVED** [review]
LGTM

**Pull request merged**
