### PR TITLE
Revert "Restore Seperate test builds, but fix broken pipe (#35378)"

### PR DESCRIPTION
**Pull request by sdmaclea**
This reverts commit 6d64040a3a577e097e8d06ef72c10f700a17bf9c.

### CODE REVIEW

**Review by jashook — APPROVED** [review]
We will need to disable failing tests but thanks for this!

**Review by trylek — APPROVED** [review]
Sigh - that's how infra changes go.

**Comment by sdmaclea** [comment]
Based on recent #35783 runs, I suspect you will need something approximately like this.

```diff
commit af4725ad629cbe687c62d0701b429a92412614a8
Author: Steve MacLean <Steve.MacLean@Microsoft.com>
Date:   Tue May 5 17:12:44 2020 -0400

    Add issues related to CI coverage outage

diff --git a/src/coreclr/tests/issues.targets b/src/coreclr/tests/issues.targets
index ce48665..360f6f1 100644
--- a/src/coreclr/tests/issues.targets
+++ b/src/coreclr/tests/issues.targets
@@ -11,6 +11,25 @@
         <ExcludeList Include="$(XunitTestBinBase)/Regressions/coreclr/GitHub_22888/test22888/*">
             <Issue>https://github.com/dotnet/runtime/issues/13703</Issue>
         </ExcludeList>
+        <!-- Test regressions during CI coverage outage -->
+        <ExcludeList Include="$(XunitTestBinBase)/baseservices/exceptions/stackoverflow/*">
+            <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
+        </ExcludeList>
+        <ExcludeList Include="$(XunitTestBinBase)/JIT/SIMD/Vector3Interop_r/*">
+            <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
+        </ExcludeList>
+        <ExcludeList Include="$(XunitTestBinBase)/JIT/SIMD/Vector3Interop_ro/*">
+            <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
+        </ExcludeList>
+        <ExcludeList Include="$(XunitTestBinBase)/baseservices/typeequivalence/simple/Simple/*">
+            <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
+        </ExcludeList>
+        <ExcludeList Include="$(XunitTestBinBase)/Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/Reverse/*">
+            <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
+        </ExcludeList>
+        <ExcludeList Include="$(XunitTestBinBase)/Interop/PInvoke/Vector2_3_4/Vector2_3_4/*">
+            <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
+        </ExcludeList>
     </ItemGroup>
 
     <!-- All OS/Arch CoreCLR excludes -->
```

**Comment by BruceForstall** [comment]
@sdmaclea These test failures are regressions that crept in when we weren't testing everything properly?

**Comment by sdmaclea** [comment]
> regressions that crept in

@BruceForstall That would be my guess....

**Comment by sdmaclea** [comment]
CI looks OK except for 
+ regressions mentioned above
+ new regression `Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest`
+ minor merge conflict.

**Comment by sdmaclea** [comment]
I added a merge commit w/ origin/master & disabled the 6 new failing (regressing) tests.

**Review by jashook — APPROVED** [review]

**Pull request merged**
