### PR TITLE
Update SPCL to use GeneratedDllImport where possible.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
/cc @jkoritzinsky @elinor-fung

### CODE REVIEW

**Review by jkoritzinsky — COMMENTED** [review]
Can you make sure to run the code-fix on the other target OSes of System.Private.CoreLib as well so we can catch the Linux and MacOS P/Invokes too? I think if you set the TargetOS environment variable before opening VS, you'll be able to override the target OS. Or you can change https://github.com/dotnet/runtime/blob/25da88cc34673e9ec051d720ecbdfbe5e479d107/Directory.Build.props#L21 to Linux, OSX, etc. to cycle through the different OSes in VS.

**Review by jkoritzinsky — APPROVED** [review]

**Review by elinor-fung — APPROVED** [review]

**Comment by stephentoub** [comment]
> where possible

What remains that's not possible? Do we have a plan to get to 100%, whether by improving the source generator or by changing the P/Invoke signatures or both?

**Comment by AaronRobinsonMSFT** [comment]
> What remains that's not possible? Do we have a plan to get to 100%, whether by improving the source generator or by changing the P/Invoke signatures or both?

The biggest change is the blittable signatures with `Guid`&mdash;we do have a plan. There are also a few scenarios involving marshalling via COM interop that will need to be updated using `ComWrappers`. So we do have a plan longer term and have added a TODO for each signature with what is needed.

**Comment by elinor-fung** [comment]
This also doesn't include converting QCalls. Now that @jkoritzinsky has updated how the runtime handles QCalls, we should be able to do another pass over SPCL to convert those as well.

There are also a couple of other things like `CriticalHandle`, `HandleRef`, and `StringBuilder` that the generator doesn't support.

**Comment by stephentoub** [comment]
Thanks.

> There are also a couple of other things like CriticalHandle, HandleRef, and StringBuilder that the generator doesn't support.

But we should be able to update any use of those to not need them, right?  I'm just trying to nudge us to a place where a) we've proven that GeneratedDllImport can be used exclusively instead of DllImport (using our vast numbers of DllImports in dotnet/runtime as a proxy for real-world usage) and b) we ship .NET 7 without having to generate any stubs at run-time.

**Comment by AndyAyersMS** [comment]
arm64 regression (likely since fixed): https://github.com/dotnet/perf-autofiling-issues/issues/2405

**Comment by EgorBo** [comment]
Improvements on windows-arm64: https://github.com/dotnet/perf-autofiling-issues/issues/2555

**Pull request merged**
