### PR TITLE
Fix concurrent collections CA1836 rule violations

### PR DESCRIPTION
**Pull request by jozkee**
Follow-up to https://github.com/dotnet/roslyn-analyzers/pull/3978

Fix places where the rule detects an inefficient usage of `Count == 0` or similar condition after changing the rule to only diagnose allowed types (concurrent types for now).

Also updates rule severity to `Warning` in CodeAnalysis.ruleset file.

cc @mavasani @jeffhandley

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
Nice

**Review by mavasani — APPROVED** [review]

**Comment by Jozkee** [comment]
Seems like CI issues are due to dotnet/runtime hasn't ingested the latest bits from dotnet/roslyn-analyzers, maybe we should holf-off changing severity until then.

**Comment by mavasani** [comment]
> Seems like CI issues are due to dotnet/runtime hasn't ingested the latest bits from dotnet/roslyn-analyzers, maybe we should holf-off changing severity until then.

I think you can just bump up the below to `3.3.0-beta3.20410.1` to pick up the latest version from https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet5&package=Microsoft.CodeAnalysis.NetAnalyzers&protocolType=NuGet&version=3.3.0-beta3.20410.1&view=versions in this PR itself: 
https://github.com/dotnet/runtime/blob/aa5fdab9654d74bc6274c0b5d820272c8e859621/eng/Analyzers.props#L9

**Comment by jkotas** [comment]
"The operation is not allowed on non-connected sockets.". #38159 ?

**Pull request merged**
