### PR TITLE
Remove MONO ifdef from Vector128 bitcasts

### PR DESCRIPTION
**Pull request by xtqqczze**
Follow-up to https://github.com/dotnet/runtime/pull/104309.

### CODE REVIEW

**Comment by tannergooding** [comment]
We should wait on this until after we ensure it doesn't need to be backed out for Mono WASM: https://github.com/dotnet/perf-autofiling-issues/issues/37893

Just trying to confirm the handling that needs to be added

**Comment by xtqqczze** [comment]
Depends on https://github.com/dotnet/runtime/pull/104698.

**Comment by xtqqczze** [comment]
Depends on https://github.com/dotnet/runtime/pull/105009.

**Comment by xtqqczze** [comment]
```log
* Assertion at D:\a\_work\1\s\src\mono\mono\mini\method-to-ir.c:13613, condition `var->opcode == OP_REGOFFSET' not met
```

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-104694-merge-21b422aec23d4be0ac/HardwareIntrinsics_General_r/1/console.8b18dec4.log?helixlogtype=result

**Comment by tannergooding** [comment]
You'll need to log an issue for it and wait for the Mono side to be fixed before this PR can be taken.

**Comment by xtqqczze** [comment]
> You'll need to log an issue for it and wait for the Mono side to be fixed before this PR can be taken.

Issue created: https://github.com/dotnet/runtime/issues/109345

**Pull request closed without merging**
