### PR TITLE
Shrink ManifestEnvelope.MaxChunkSize to hold extended data

### LINKED ISSUE #87255: The ETW event generated by EventSource.SendManifest is lost at receiver due to size limit when extended data is appended
### Description

For [EventSource.SendManifest](https://github.com/dotnet/runtime/blob/90b416a511564b109d6e9f4534f2de86cab7dd0c/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L2796), the current `ManifestEnvelope.MaxChunkSize` used is `0xFF00`. In extended data is requested at receiver (e.g., ContainerId), the ETW event will exceed the ETW limit (0xFFFF), which causes the event lost and all events from the ETW provider unable to be analyzed. 

### Reproduction Steps

At sender, using an `EventSource` which has hundreds of events so its manifest will be larger than 64K. Emit an event in container.

At receiver, using `TraceEventSession` with `EnableSourceContainerTracking` set.

### Expected behavior

PerfView can analyze the .etl file correctly.

### Actual behavior

PerfView report events lost and cannot analyze the event correctly. Event name and message are missing.

### Regression?

_No response_

### Known Workarounds

At receiver, don't set  `EnableSourceContainerTracking`.

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ms-hujia**
Fix #87255.

### CODE REVIEW

**Comment by brianrob** [comment]
The change itself looks fine to me.  For me, the bigger question is how much reserve space we should leave for other properties to make sure that we don't hit this problem in another mainline scenario.  @idigdoug, I'd like to get your opinion on how large of an ETW payload you would recommend as a max size in order to ensure that extended data doesn't push the event over the 64kB maximum.

**Comment by idigdoug** [comment]
> 

Size of extended data can include stacks. The max size for stack capture is currently 192 frames * 8 bytes = 1.5KB. So maybe you could assume a "probably safe" number of 2KB?

**Comment by brianrob** [comment]
> > 
> 
> Size of extended data can include stacks. The max size for stack capture is currently 192 frames * 8 bytes = 1.5KB. So maybe you could assume a "probably safe" number of 2KB?

Sounds good to me.  @ms-hujia would you mind dropping the chunk size by 2kB to 0xF700?

**Comment by ms-hujia** [comment]
Thanks for confirming the capacity of ETW extended data sets. I've modified the chunk size as your suggestion.

**Review by brianrob — APPROVED** [review]
The code looks good to me.  @davmason any thoughts on the test failure?  Looks likely unrelated to me.

**Comment by davmason** [comment]
The test failure is unrelated, I'm going to merge

**Pull request merged**
