### PR TITLE
[browser] Enable threads in Wasm SDK

### PR DESCRIPTION
**Pull request by maraf**
- Allows threads for blazor
- Publish dotnet.worker.js when threads are enabled
- Append fingerprint for dotnet.worker.js
- Support for dotnet run requires https://github.com/dotnet/aspnetcore/pull/47855

### CODE REVIEW

**Comment by lambdageek** [comment]
How do I try this out?

**Comment by maraf** [comment]
The same story as for webcil. Until SDK PR lands and makes through installer, you need a lot of local patching. I can show you tomorrow if you want.

**Comment by lewing** [comment]
wait for https://github.com/dotnet/sdk/pull/31912 to have an installer build then you  can use wbt on this pr

**Comment by maraf** [comment]
> wait for https://github.com/dotnet/sdk/pull/31912 to have an installer build then you  can use wbt on this pr

That one is not enough. This one is needed https://github.com/dotnet/sdk/pull/31519

**Comment by lewing** [comment]
https://github.com/dotnet/installer/pull/16197

**Comment by lambdageek** [comment]
I tried this one the same way as https://github.com/dotnet/runtime/pull/84977#issuecomment-1518513985 but I don't see `dotnet.worker.js` in `wwwroot/_framework`

**Comment by lambdageek** [comment]
Getting some blazor errors about `blazor-internal` not being loaded yet.  

Seems like some of the blazor async code is running on worker threads instead of the main thread.

**Comment by lambdageek** [comment]
Also the blazor weather forecast page from the default template breaks because http fetching has a `ConfigureAwait(false)` somewhere.  @pavelsavara, I think we need to fix that HTTP client thing that you found

```
   Unhandled exception rendering component: The JavaScript object can be used only on the thread where it was created.
System.InvalidOperationException: The JavaScript object can be used only on the thread where it was created.
   at System.Runtime.InteropServices.JavaScript.JSObject.AssertThreadAffinity(Object )
   at System.Net.Http.BrowserHttpInterop.AbortResponse(JSObject )
   at System.Net.Http.WasmFetchResponse.Dispose()
   at System.Net.Http.BrowserHttpContent.Dispose(Boolean )
   at System.Net.Http.HttpContent.Dispose()
   at System.Net.Http.HttpResponseMessage.Dispose(Boolean )
   at System.Net.Http.HttpResponseMessage.Dispose()
   at System.Net.Http.Json.HttpClientJsonExtensions.<<FromJsonAsyncCore>g__Core|4_0>d`2[[bl1.Pages.FetchData.WeatherForecast[], bl1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Text.Json.JsonSerializerOptions, System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext()
   at bl1.Pages.FetchData.OnInitializedAsync()
 ```

**Comment by pavelsavara** [comment]
> Also the blazor weather forecast page from the default template breaks because http fetching has a `ConfigureAwait(false)` somewhere. @pavelsavara, I think we need to fix that HTTP client thing that you found

Here is the draft, but I need to try on top of your branch. https://github.com/dotnet/runtime/pull/85244

I wonder if also user code would have to contain `ConfigureAwait(true)` on all lines with `await` keyword. If so, that means massive inconvenience even for our HTTP unit test suite. 

Any ideas ?

**Comment by lambdageek** [comment]
@maraf Any reason this is still draft?  I think this PR is working, even if the libraries and blazor need a bit of work.

**Comment by lambdageek** [comment]
Fingerprinting stuff is working. I see fetches for `dotnet.worker.8.0.0-dev.p6hue5g3ye.js` and the webworkers are starting properly.

**Review by lambdageek — APPROVED** [review]

**Comment by maraf** [comment]
Failures are unrelated

**Pull request merged**
