### PR TITLE
Expose various Convert intrinsics for Avx512F, Avx512BW, and Avx512DQ

### PR DESCRIPTION
**Pull request by tannergooding**
This exposes some instructions unique to the AVX512 family of instructions making progress towards completing:
* https://github.com/dotnet/runtime/issues/74813
* https://github.com/dotnet/runtime/issues/73604
* https://github.com/dotnet/runtime/issues/76579

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @dotnet/jit-contrib, @dotnet/avx512-contrib 

As with the last change, most of this is simply updating entries in the JIT intrinsic tables and exposing the managed side + xml docs.

**Comment by tannergooding** [comment]
Fixed a few failures that were masked by https://github.com/dotnet/runtime/issues/85056. Manually inspecting both logs shows everything passing again.

**Comment by tannergooding** [comment]
> Manually inspecting both logs shows everything passing again.

Also went and ran various other stress tests and those are all passing as well. This includes:
* TieredCompilation=0
* JitStressEvexEncoding=1
* JitStress=1
* JitStressRegs=0x2000

**Comment by tannergooding** [comment]
WASM timeouts are https://github.com/dotnet/runtime/issues/85304

**Review by EgorBo — APPROVED** [review]

**Pull request merged**
