### PR TITLE
Enable src/JIT/Methodical/explicit/coverage tests on non-Windows

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
Kicked off outerloop job: https://dev.azure.com/dnceng/public/_build/results?buildId=578398&view=results

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/34233

**Comment by BruceForstall** [comment]
Outerloop job: https://dev.azure.com/dnceng/public/_build/results?buildId=628222&view=results

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib PTAL

**Review by AndyAyersMS — APPROVED** [review]

**Pull request merged**
