### PR TITLE
[release/9.0-staging] Update ApiCompatNetCoreAppBaselineVersion to 9.0.0

### PR DESCRIPTION
**Pull request by carlossanlop**
Fixes https://github.com/dotnet/runtime/issues/106598
Follow up of https://github.com/dotnet/runtime/pull/109316#discussion_r1820295635

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by carlossanlop** [comment]
@dotnet/dotnet-webassembly-admin @akoeplinger @lewing can you please take a look at the failure? Seems we will need additional changes in this PR related to wasm.

**Comment by akoeplinger** [comment]
should be fixed now

**Comment by carlossanlop** [comment]
> should be fixed now, mirrored the stable packages to dotnet-public

Do we need the same fix in the main PR @akoeplinger ? https://github.com/dotnet/runtime/pull/109790

**Comment by akoeplinger** [comment]
Yes, but I agree with Viktor's comment in https://github.com/dotnet/runtime/pull/109790#issuecomment-2477676826 that we need to port https://github.com/dotnet/runtime/pull/109316 too so you could put the change into that PR to restart CI.

**Pull request merged**
