### PR TITLE
[wasm] Make windows wasm build run tests on helix

### PR DESCRIPTION
**Pull request by radekdoulik**
Some of the tests were disabled for now: https://github.com/dotnet/runtime/issues/52138

### CODE REVIEW

**Review by lewing — COMMENTED** [review]
Is there a reason you're excluding whole test assemblies instead of marking individual tests with ActiveIssue?

**Comment by radekdoulik** [comment]
> Is there a reason you're excluding whole test assemblies instead of marking individual tests with ActiveIssue?

My motivation was to make this PR merged quickly, so that we can use the infrastructure changes for PR to enable few AOT tests on windows helix. So did similar change we do for failing AOT tests. In some libraries there are many tests failing. I can annotate these which have only few tests failing if you think it is worth.

**Review by lewing — COMMENTED** [review]
Looks good to me.  @steveisok @akoeplinger anything we need to worry about here?

**Comment by steveisok** [comment]
> Looks good to me. @steveisok @akoeplinger anything we need to worry about here?

Not that I can see.  Looks good.

**Review by radical — CHANGES_REQUESTED** [review]
Just a couple of comments.

**Review by radical — APPROVED** [review]
LGTM! Excited to have these enabled 👍

**Pull request merged**
