### PR TITLE
Pass the argument to formatting function

### PR DESCRIPTION
**Pull request by kunalspathak**
One of the place was missing an argument.

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib , @JulieLeeMSFT

**Review by BruceForstall — APPROVED** [review]

**Comment by am11** [comment]
Another similar case: https://github.com/dotnet/runtime/blob/e5eee9a9c6dbdcf0ca018347da73830e42d0e8c9/src/coreclr/jit/fgehopt.cpp#L446
spotted by `git grep '(.*FMT_.*)' src/coreclr | grep -v ,`

**Comment by BruceForstall** [comment]
> Another similar case:

I have a fix for that and another. Unfortunately, the tool opening these issues opened bugs in an internal database, not on GitHub.

**Comment by kunalspathak** [comment]
> > Another similar case:
> 
> I have a fix for that and another. Unfortunately, the tool opening these issues opened bugs in an internal database, not on GitHub.

Ah, was not aware that you also have them assigned. Should I revert my latest patch?

**Comment by AndyAyersMS** [comment]
I have one of these too. Seems like they should have all been aggregated into one issue.

**Comment by AndyAyersMS** [comment]
https://github.com/dotnet/runtime/blob/b1c4fbfebd5c2a5384c6b4dd32213ab2ee8fda89/src/coreclr/jit/compiler.cpp#L9137

Feel free to fix this one too.

**Comment by BruceForstall** [comment]
> Should I revert my latest patch?

yeah; I pushed my fixes in https://github.com/dotnet/runtime/pull/68007

**Comment by BruceForstall** [comment]
@TIHan also has been assigned:

https://github.com/dotnet/runtime/blob/52ae06ec33a1a2cf5dd7b63232b754b12f92669c/src/coreclr/jit/lower.cpp#L55-L56

Which looks like it should be:
```
JITDUMP("** Unsafe mem containment of [%06u] in [%06u]\n", comp->dspTreeID(childNode),
                    comp->dspTreeID(parentNode));
```

**Comment by kunalspathak** [comment]
Errors seems unrelated.

**Comment by kunalspathak** [comment]
@BruceForstall - can you take another look?

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
