### PR TITLE
Enable tests blocked on closed issue #50381

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
This issue is closed. Either these are fixed, or the issue needs to be open.

### CODE REVIEW

**Comment by janvorli** [comment]
I think the issue was closed by mistake. The discussion on the original issue got hijacked by another question that sounded related, but turned out to be something else. I've explained in the discussion that that issue was fixed, but I guess that David has seen that and closed the issue based on this.
However, I've made a fix #79426 to a similar issue in December and it seems it probably had the same culprit - the GC stress C preventing signal delivery in a race condition. So let's make this change and see.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Review by jakobbotsch — APPROVED** [review]
None of these tests seemed to fail in the GCStress runs. I opened #82037 for the win-x86 failures.

**Comment by MichalStrehovsky** [comment]
Thank you @janvorli and @jakobbotsch!

(I stumbled on this by accident when looking for ways to exclude test from building for a particular OS)

**Pull request merged**
