### PR TITLE
update SIGKILL hint msg

### PR DESCRIPTION
**Pull request by danmoseley**
re https://github.com/dotnet/runtime/issues/97049#issuecomment-1894564427

### CODE REVIEW

**Comment by danmoseley** [comment]
Will need to update pattern in https://github.com/dotnet/runtime/issues/97049#issue-2084987073 and any similar ones.

**Review by carlossanlop — APPROVED** [review]
Much more helpful.

**Review by jkotas — APPROVED** [review]
Thanks!

**Comment by danmoseley** [comment]
@carlossanlop is there a way I can tell it to merge if everything ends up green? I can do this in some other repos.

**Comment by carlossanlop** [comment]
You mean automerge? We would have to ask folks if anyone has an objection to reenabling it. I do not know why it was disabled but I'm sure there was a good reason. @ViktorHofer @ericstj @stephentoub @jkotas

**Comment by stephentoub** [comment]
> You mean automerge? We would have to ask folks if anyone has an objection to reenabling it. I do not know why it was disabled but I'm sure there was a good reason. @ViktorHofer @ericstj @stephentoub @jkotas

If memory serves you need required legs in order to use that safely, and we don't have any right now because of the variations of what's run for different kinds of changes.

**Comment by danmoseley** [comment]
ah - yes.

**Comment by ViktorHofer** [comment]
> If memory serves you need required legs in order to use that safely, and we don't have any right now because of the variations of what's run for different kinds of changes.

Exactly.

**Comment by danmoseley** [comment]
ironically it produced an example
```
===========================================================================================================
/private/tmp/helix/working/BE490A9E/w/A6C008DC/e /private/tmp/helix/working/BE490A9E/w/A6C008DC/e
  Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 7275 of 7334 test cases)
  Starting:    System.Text.Json.Tests (parallel test collections = on [6 threads], stop on fail = off)
./RunTests.sh: line 180: 50798 Killed: 9               "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Text.Json.Tests.runtimeconfig.json --depsfile System.Text.Json.Tests.deps.json xunit.console.dll System.Text.Json.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/private/tmp/helix/working/BE490A9E/w/A6C008DC/e
----- end Thu Jan 25 11:56:01 PST 2024 ----- exit code 137 ----------------------------------------------------------
exit code 137 means SIGKILL Killed either due to out of memory/resources (see /var/log/messages) or by explicit kill.
ulimit -c value: 0
Unable to obtain kernel buffer: Operation not permitted
usage: sudo dmesg
----- start =============== XUnitLogChecker Output =====================================================
No dumps found in /cores.
----- end =============== XUnitLogChecker Output - exit code 0 ===========================
```

**Comment by danmoseley** [comment]
or maybe @wfurt knows the answer to above.

**Comment by jkoritzinsky** [comment]
I don't know how sudo permissions are set up on the Helix machines. dnceng should know.

**Comment by jkotas** [comment]
If the regular CI jobs had machine admin access, I think it would be a security issue to fix.

**Comment by wfurt** [comment]
runing sudo in container or disposable VM is ok IMHO. But that would be problematic on Mac as we keep physical machine AFAIK. You can perhaps make the test conditional on privilege access @danmoseley so it can be at least executed locally. 

Also we can ask@dotnet/dnceng to make `dmesg` SUID or try to use `log show` instead.

**Comment by danmoseley** [comment]
Sounds good to me but I don't think I can do this myself as I can't test locally. It is worth fixing though.

**Pull request merged**
