### PR TITLE
Remove defensive OID copies

### PR DESCRIPTION
**Pull request by vcsjones**
Since OID is init-only, this removes defensive copies. This only addresses Oid to Oid copies. Next step is to provide shared instances of OIDs where possible instead of constructing a new ones from strings every time.

Contributes to #2043

### CODE REVIEW

**Comment by vcsjones** [comment]
> Next step is to provide shared instances of OIDs

I wonder if we should make these public somewhere, off of `Oid` seems logical.

```c#
partial class Oid {
    public static Oid Sha1 { get; } = new Oid("1.3.14.3.2.26", "SHA1");
}
```

Seems like we could do the top (rolls die) dozen or so.

**Comment by bartonjs** [comment]
I thought about public copies, but we should probably become equatable before then, so that programs don't end up in the bad state of `if (foo.Oid == Oid.Sha1)` working half the time.

I don't think exposing the arc-tree is really anything anyone would understand :).

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
> I don't think exposing the arc-tree is really anything anyone would understand :).

Well, I meant

```c#
partial class Oid {
  public static class Digests {
    public static Oid Sha1...
    public static Oid Sha256...
  }

  public static class Signatures {
    public static Oid Rsa...
  }
}
```

Yeah I don't think anyone would know what a class `Oiw.Secsig` is.

**Comment by bartonjs** [comment]
Yeah, but then we get the fun debate of "is `id-rsaEncryption` a signature algorithm? an encryption algorithm? a key format identifier?"  Sort of, kind of, and yes. :smile:

**Pull request merged**
