### PR TITLE
[release/6.0] Update ESRP Code Signing

### PR DESCRIPTION
**Pull request by dkurepa**
Port of https://github.com/dotnet/runtime/pull/102948

### CODE REVIEW

**Comment by dkurepa** [comment]
test: https://dev.azure.com/dnceng/internal/_build/results?buildId=2480986&view=results

**Comment by hoyosjs** [comment]
@carlossanlop should this go to staging? Consider this and https://github.com/dotnet/runtime/pull/103896 signed off by me. I am just deferring to you for branches + prodcon.

**Comment by mmitche** [comment]
I've changed this to staging.

**Comment by mmitche** [comment]
Changed to staging.

**Comment by mmitche** [comment]
@carlossanlop Please merge when possible

**Review by carlossanlop — APPROVED** [review]
CI failures are all unrelated.

**Pull request merged**
