### PR TITLE
Store status code in exception for ProxyTunnelError

### LINKED ISSUE #66329: [API Proposal]: Provide tunnel status code for proxy exceptions
### Background and motivation

API user would like to have specific information about why a proxy connection failed without the need to parse a text based error message.

Dotnet 6 altered how proxy errors were handled as part of #48679.  Rather than the proxy response being returned to the user, an error message is returned.  This was done to distinguish proxy related errors from upstream errors.

I have a need to distinguish proxy errors based upon the status code the proxy returned.  This information is conveyed as part of the error message "The proxy tunnel request to proxy {proxyUri} failed with status code {statusCode}."

Please make the proxy status code somehow directly available to the user rather than by parsing a text string.

### API Proposal

TBD

### API Usage

TBD

### Alternative Designs

_No response_

### Risks

_No response_

### LINKED ISSUE #105546: HttpRequestException Lacks StatusCode Information on ProxyTunnelError
### Description

When HttpRequestException is thrown with ProxyTunnelError HttpRequestError, the StatusCode is not included. This behavior may not be ideal for scenarios involving web scraping where backconnecting proxy is utilized extensively.

In web scraping, we mostly do not connect to the proxy directly. Instead, a backconnecting proxy service is employed which dynamically assigns different proxies which is convenient to provide rotating proxies. The CONNECT request is critical as it is the point where the backconnecting proxy might reject a request. Typically, proxies communicate the nature of such rejections via HTTP status codes (e.g., 429 when request rate is too high, 502 when no available proxy). Some will use HTTP headers detailing the reason too.

Currently, we have to parse the Message to find the actual status code

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/105546
Closes https://github.com/dotnet/runtime/issues/66329

@antonfirsov, @wfurt, is it by-design or an accident that we didn't do this? The original PR:
https://github.com/dotnet/runtime/pull/88974/files#diff-bc2faad6c76ecb9b115e305763eb55ebfde74de1eee27ed549e5edaabb097a99R1767
has it with the status code only going into the error message but not being used to intialize the property.

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM.
I don't know if this was the reason but at some point there was concern about mingling status from proxy vs actual server. https://github.com/dotnet/runtime/issues/48679

It seems like this effectively solves https://github.com/dotnet/runtime/issues/66329, right? e.g. the ask is the same.

**Comment by stephentoub** [comment]
> It seems like this effectively solves https://github.com/dotnet/runtime/issues/66329, right? e.g. the ask is the same.

I believe so

> I don't know if this was the reason but at some point there was concern about mingling status from proxy vs actual server. https://github.com/dotnet/runtime/issues/48679

I read through that and it doesn't actually seem like being about status, rather than the response couldn't be differentiated from the actual response, and the resulting fix was to throw this exception. Now that an exception is being thrown and that exception can carry a status code, providing that status code seems like the correct answer. It's clear it's a proxy tunnel failure from the error enum.

**Comment by wfurt** [comment]
that make sen se to me. Can we add test(s) and perhaps also update documentation to make it clear?

**Review by antonfirsov — COMMENTED** [review]
> @antonfirsov, @wfurt, is it by-design or an accident that we didn't do this?

`HttpRequestException.StatusCode` has been introduced in #32455 but hasn't been systematically forwarded for cases other than trivial `EnsureSuccessStatusCode()` validations. #88974 didn't change anything in that regard.

**Review by antonfirsov — APPROVED** [review]

**Comment by stephentoub** [comment]
> but hasn't been systematically forwarded for cases

Meaning we're likely missing the status code being included in the exception in other cases? Is there an open issue for auditing all of them?

**Comment by antonfirsov** [comment]
Opened #105700.

**Pull request merged**
