### PR TITLE
[iOS][MacOS] Run tests on iOS 17 and MacOS 14 scouting queues

### PR DESCRIPTION
**Pull request by steveisok**
This will hopefully show us where we currently stand.

### CODE REVIEW

**Comment by steveisok** [comment]
The chances aren't good for any of the failures to show up in azdo as the job will likely time out. However, the work items will finish and can be analyzed.

**Comment by steveisok** [comment]
@akoeplinger does anything in xharness / mlaunch need updated?

**Comment by vcsjones** [comment]
I would consider an outerloop run here, too. We have a good number of S.S.Cryptography tests that are outer loop that I would be interested in understanding their behavior on macOS 14. Particularly some of the X.509 things that we know test to break from release to release.

**Comment by akoeplinger** [comment]
> @akoeplinger does anything in xharness / mlaunch need updated?

I'm seeing this from xharness in the log so that seems likely:

```
[09:43:43] crit: System.Exception: Failed to list devices.
                    at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.HardwareDeviceLoader.LoadDevices(ILog log, Boolean includeLocked, Boolean forceRefresh, Boolean listExtraData, Boolean includeWirelessDevices, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/HardwareDeviceLoader.cs:line 103
```

**Comment by akoeplinger** [comment]
More detailed log from mlaunch:
```
[09:43:43.8203300] error HE0004: Could not load the framework 'IDEProducts' (path: /Applications/Xcode15_beta.app/Contents/SharedFrameworks/IDEProducts.framework/IDEProducts): 
[09:43:43.8203930] dlopen(/Applications/Xcode15_beta.app/Contents/SharedFrameworks/IDEProducts.framework/IDEProducts, 0x0001): Library not loaded: @rpath/IDEDistribution.framework/Versions/A/IDEDistribution
[09:43:43.8204040]   Referenced from: <33B36F10-89CE-3E88-AECE-A71AD0608B28> /Applications/Xcode15_beta.app/Contents/SharedFrameworks/IDEProducts.framework/Versions/A/IDEProducts
[09:43:43.8204400]   Reason: tried: '/private/tmp/helix/working/A4BB094A/p/microsoft.dotnet.xharness.cli/8.0.0-prerelease.23326.1/runtimes/any/native/mlaunch/lib/mlaunch/mlaunch.app/Contents/Frameworks/IDEDistribution.framework/Versions/A/IDEDistribution' (no such file), '/Applications/Xcode15_beta.app/Contents/SharedFrameworks/IDEProducts.framework/Versions/A/Frameworks/IDEDistribution.framework/Versions/A/IDEDistribution' (no such file), '/private/tmp/helix/working/A4BB094A/p/microsoft.dotnet.xharness.cli/8.0.0-prerelease.23326.1/runtimes/any/native/mlaunch/lib/mlaunch/mlaunch.app/Contents/Frameworks/IDEDistribution.framework/Versions/A/IDEDistribution' (no such file), '/Applications/Xcode15_beta.app/Contents/SharedFrameworks/IDEProducts.framework/Versions/A/Frameworks/IDEDistribution.framework/Versions/A/IDEDistribution' (no such file)
[09:43:43.8204570]         
[09:43:43.8239930]   at Xamarin.Hosting.Services.LoadFramework (System.String framework, System.Boolean warnIfMissing) [0x00089] in /Users/builder/azdo/_work/3/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/Services.cs:275 
[09:43:43.8240200]   at Xamarin.Hosting.Services.LoadFrameworks () [0x00423] in /Users/builder/azdo/_work/3/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/Services.cs:164 
[09:43:43.8240300]   at Xamarin.Hosting.Services.Initialize (System.String xcode_location, System.Boolean enable_xcode_plugins) [0x000d8] in /Users/builder/azdo/_work/3/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/Services.cs:91 
[09:43:43.8240370]   at Xamarin.Launcher.DevController.Initialize () [0x00001] in /Users/builder/azdo/_work/3/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:35 
[09:43:43.8240440]   at Xamarin.Launcher.DevController.ListDevicesAsync (Xamarin.Launcher.OutputFormat format, System.String output_file, System.Boolean list_extra_data) [0x0003f] in /Users/builder/azdo/_work/3/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-device.cs:446 
[09:43:43.8240700]   at Xamarin.Utils.NSRunLoopExtensions.RunUntilTaskCompletion[T] (Foundation.NSRunLoop this, System.Threading.Tasks.Task`1[TResult] task) [0x00082] in /Users/builder/azdo/_work/3/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Utils/Extensions.cs:35 
[09:43:43.8240790]   at Xamarin.Launcher.Driver.Main2 (System.String[] args) [0x00ba3] in /Users/builder/azdo/_work/3/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:435 
[09:43:43.8240860]   at Xamarin.Launcher.Driver.Main (System.String[] args) [0x0006d] in /Users/builder/azdo/_work/3/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:123 
[09:43:43.8298690] Process mlaunch exited with 1
[09:43:43.8536290] Failed to parse device list: System.Exception: Failed to list devices.
```

**Comment by akoeplinger** [comment]
I've sent a PR to mlaunch with the fix.

**Comment by steveisok** [comment]
@akoeplinger the latest run with an updated xharness gives me:

```
[13:03:13.7809040] Xamarin.Hosting: Loaded Xcode plugins successfully.
[13:03:13.8164650] error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
[13:03:13.8830640] System.IO.FileNotFoundException: Could not find required file 'net.dot.System.Runtime.Tests/Info.plist'.
[13:03:13.8831020]    at Xamarin.Hosting.PList.FromFile(String) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/PList.cs:line 24
[13:03:13.8831110]    at Xamarin.Hosting.PlistBasedAppBundle..ctor(String) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/PlistBasedAppBundle.cs:line 21
[13:03:13.8831300]    at Xamarin.Launcher.Driver.LaunchOrDebugUsingDeviceCtl(Action, RealDevice) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 576
[13:03:13.8831390]    at Xamarin.Launcher.Driver.LaunchOrDebugAsync(Action) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 547
[13:03:13.8831450]    at Xamarin.Launcher.Driver.MainAsync() in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 491
[13:03:13.8831570]    at Xamarin.Utils.NSRunLoopExtensions.RunUntilTaskCompletion[T](NSRunLoop, Task`1) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Utils/Extensions.cs:line 30
[13:03:13.8831640]    at Xamarin.Launcher.Driver.Main2(String[]) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 436
[13:03:13.8831710]    at Xamarin.Launcher.Driver.Main(String[]) in /Users/builder/azdo/_work/1/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 123
```

**Pull request closed without merging**
