### PR TITLE
Disable cache clearing S.CM.TC test from running in parallel

### LINKED ISSUE #51819: Intermittent failure in AddProvider_InvokeTypeMultipleTimes_Refreshes test and AddProviderTransparent_InvokeTypeMultipleTimes_Refreshes
AddProvider_InvokeTypeMultipleTimes_Refreshes test [failed](https://github.com/dotnet/runtime/pull/51818/checks?check_run_id=2427633910) in runtime (Libraries Test Run checked coreclr OSX x64 Debug) leg:
```
  Starting:    System.ComponentModel.TypeConverter.Tests (parallel test collections = on, max threads = 4)
    System.ComponentModel.Tests.TypeDescriptorTests.AddProvider_InvokeTypeMultipleTimes_Refreshes [FAIL]
      Assert.Equal() Failure
      Expected: 2
      Actual:   3
```

### PR DESCRIPTION
**Pull request by danmoseley**
Fix https://github.com/dotnet/runtime/issues/51819

The 1->2 is because it counts the attributes on its own class.

### CODE REVIEW

**Comment by safern** [comment]
I believe we should also add it to the class containing these tests? 

https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.ComponentModel.TypeConverter/tests/TypeDescriptorTests.cs#L242

**Comment by danmoseley** [comment]
Sure why not. Ironically the tests in this library complete in hardly any time, so we could have just disabled parallelism entirely.

**Review by safern — APPROVED** [review]
Thanks for hunting it down!

**Comment by danmoseley** [comment]
Failure is https://github.com/dotnet/runtime/issues/52447

**Pull request merged**
