### PR TITLE
Fix GetModuleFileName in GetProcessPath

### LINKED ISSUE #110800: Environment.ProcessPath hangs with exe path > MAX_PATH
### Description

Running an exe that is located in a path that exceeds the MAX_PATH (260 chars) will hang if it calls `Environment.ProcessPath`. Currently `Environment.ProcessPath` on Windows calls `GetProcessPath`

https://github.com/dotnet/runtime/blob/e65457031da52f57d03da721f381a82a5be64c03/src/libraries/System.Private.CoreLib/src/System/Environment.Windows.cs#L127-L142

The current logic is

+ Allocate `ValueStringBuilder` to a capacity of 260
+ When the length returned by [GetModuleFileNameW](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamew) is greater than or equal to the capacity, grow it

The issue is that `GetModuleFileNameW` does not return the required capacity if the provided buffer size is too small but rather the return value is the length of the string that is copied to the buffer. If the exe is located in a path that exceeds 260 the first call will be with a buffer of 260 and the return value of 260. As `260 >= 260` the `builder.EnsureCapacity(260)` call is a no-op because the capacity is already that size. As the capacity is never increased the loop will continue to run indefinitely.

A quick example in a PowerShell script showing this behaviour when the provided capacity is less than what is required. This example runs in an exe that does not exceed MAX_PATH but it illustrates how `GetModuleFileNameW` acts when the provided size is not enough to copy the full file name.

```powershell
Add-Type -Namespace Native -Name Kernel32 -MemberDefinition @'
[DllImport("Kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
public static extern int GetModuleFileNameW(IntPtr hModule, IntPtr lpFilename, int nSize);
'@

$buffer = [System.Runtime.InteropServices.Marshal]::AllocHGlobal(4)
[Native.Kernel32]::GetModuleFileNameW([IntPtr]::Zero, $buffer, 4)
# Returns 4

$buffer = [System.Runtime.InteropServices.Marshal]::ReAllocHGlobal($buffer, 260)
[Native.Kernel32]::GetModuleFileNameW([IntPtr]::Zero, $buffer, 260)
# Returns something less than 260
```

The logic will have to change to see if the return value is equal to the provided size and increase the value string builder by x amount until the return value is less than the provided size.

### Reproduction Steps

Use the following C# project that will copy itself to a path that exceeds MAX_PATH and start the process. It uses `CreateProcess` here internally because .NET cannot start an exe for something that exceeds MAX_PATH.

This uses the following csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

</Project>
```

```csharp
using System;
using System.Buffers;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.IO.Pipes;
using System.Runtime.InteropServices;
using System.Threading.Tasks;

namespace LongPathTest;

public static class Program
{
    public static void Main(string[] args)
    {
        if (args.Length == 0)
        {
            Setup();
            return;
        }

        string? processPath = args[0] switch
        {
            "PInvoke" => GetModuleFileName(),
            "ProcessMainModule" => Process.GetCurrentProcess()?.MainModule?.FileName,
            "ProcessPath" => Environment.ProcessPath,
            _ => throw new ArgumentException($"Unknown action {args[0]}"),
        };
        Console.WriteLine("Path: '{0}'", processPath);
    }

    public static void Setup()
    {
        string basePath = Path.GetDirectoryName(typeof(Program).Assembly.Location)
            ?? throw new Exception("Could not find current dll path");

        string[] filesToCopy = Directory.GetFiles(basePath);

        string dir1 = "\\\\?\\" + Path.Combine(basePath, new string('a', 255));
        string dir2 = Path.Combine(dir1, new string('b', 255));
        try
        {
            Directory.CreateDirectory(dir1);
            Directory.CreateDirectory(dir2);

            string? shortExePath = null;
            string? longExePath = null;
            foreach (string toCopy in filesToCopy)
            {
                string filename = Path.GetFileName(toCopy);
                string destPath = Path.Combine(dir2, filename);

                File.Copy(toCopy, destPath, true);
                if (Path.GetExtension(filename) == ".exe")
                {
                    shortExePath = toCopy;
                    longExePath = destPath;
                }
            }
            Debug.Assert(shortExePath is not null);
            Debug.Assert(longExePath is not null);

            string banner = new string('=', Console.BufferWidth);
            foreach (string scenario in new [] {"PInvoke", "ProcessMainModule", "ProcessPath"})
            {
                foreach (string exePath in new[] { shortExePath, longExePath })
                {
                    (string stdout, string stderr, int rc) = RunProcess(exePath, scenario);
                    Console.WriteLine("{0}\n{1} RC {2}\nSTDOUT:\n{3}\nSTDERR:\n{4}", banner, scenario, rc, stdout, stderr);
                }
            }
        }
        finally
        {
            if (Directory.Exists(dir1))
            {
                Directory.Delete(dir1, true);
            }
        }
    }

    public static (string, string, int) RunProcess(
        ReadOnlySpan<char> executable,
        ReadOnlySpan<char> commandLine)
    {
        using AnonymousPipeServerStream stdoutPipe = new(PipeDirection.In, HandleInheritability.Inheritable);
        using AnonymousPipeServerStream stderrPipe = new(PipeDirection.In, HandleInheritability.Inheritable);

        Kernel32.STARTUPINFOW si = new()
        {
            cb = Marshal.SizeOf<Kernel32.STARTUPINFOW>(),
            dwFlags = Kernel32.STARTF_USESTDHANDLES,
            hStdOutput = stdoutPipe.ClientSafePipeHandle.DangerousGetHandle(),
            hStdError = stderrPipe.ClientSafePipeHandle.DangerousGetHandle(),
        };
        Kernel32.PROCESS_INFORMATION pi = new();

        int commandLineLength = executable.Length + commandLine.Length + 4;
        char[] commandLineBuffer = ArrayPool<char>.Shared.Rent(commandLineLength);
        try
        {
            commandLineBuffer[0] = '"';
            executable.CopyTo(commandLineBuffer.AsSpan(1));
            commandLineBuffer[executable.Length + 1] = '"';
            commandLineBuffer[executable.Length + 2] = ' ';
            commandLine.CopyTo(commandLineBuffer.AsSpan(executable.Length + 3));
            commandLineBuffer[commandLineLength - 1] = '\0';

            unsafe
            {
                fixed (char* executablePtr = executable)
                fixed (char* commandLinePtr = commandLineBuffer)
                {
                    bool res = Kernel32.CreateProcessW(
                        executablePtr,
                        commandLinePtr,
                        nint.Zero,
                        nint.Zero,
                        true,
                        Kernel32.CREATE_UNICODE_ENVIRONMENT,
                        nint.Zero,
                        nint.Zero,
                        ref si,
                        ref pi);
                    if (!res)
                    {
                        throw new Win32Exception();
                    }
                }
            }

            stdoutPipe.DisposeLocalCopyOfClientHandle();
            stderrPipe.DisposeLocalCopyOfClientHandle();

            using StreamReader stdoutReader = new(stdoutPipe);
            using StreamReader stderrReader = new(stderrPipe);
            Task<string> stdoutTask = Task.Run(stdoutReader.ReadToEndAsync);
            Task<string> stderrTask = Task.Run(stderrReader.ReadToEndAsync);

            bool terminated = false;
            int waitRes = Kernel32.WaitForSingleObject(pi.hProcess, 5000);
            if (waitRes == Kernel32.WAIT_TIMEOUT)
            {
                Kernel32.TerminateProcess(pi.hProcess, -1);
                terminated = true;
            }
            else if (waitRes == Kernel32.WAIT_FAILED)
            {
                throw new Win32Exception();
            }

            int rc;
            if (!Kernel32.GetExitCodeProcess(pi.hProcess, out rc))
            {
                throw new Win32Exception();
            }

            string stdout = stdoutTask.GetAwaiter().GetResult();
            string stderr = stderrTask.GetAwaiter().GetResult();
            if (terminated && string.IsNullOrWhiteSpace(stderr))
            {
                stderr = "Timed out waiting for process output";
            }
            return (stdout, stderr, rc);
        }
        finally
        {
            ArrayPool<char>.Shared.Return(commandLineBuffer);
            if (pi.hProcess != nint.Zero)
            {
                Kernel32.CloseHandle(pi.hProcess);
            }
            if (pi.hThread != nint.Zero)
            {
                Kernel32.CloseHandle(pi.hThread);
            }
        }
    }

    public static string GetModuleFileName()
    {
        int bufferLength = 260;
        char[] pool = ArrayPool<char>.Shared.Rent(bufferLength);
        try {
            while (true)
            {
                unsafe
                {
                    fixed (char* poolPtr = pool)
                    {
                        int res = Kernel32.GetModuleFileNameW(nint.Zero, poolPtr, bufferLength);
                        if (res < bufferLength)
                        {
                            return new string(pool.AsSpan(0, res));
                        }
                        else if (res == bufferLength)
                        {
                            bufferLength += 260;
                            ArrayPool<char>.Shared.Return(pool);
                            pool = ArrayPool<char>.Shared.Rent(bufferLength);
                        }
                        else
                        {
                            throw new Win32Exception();
                        }
                    }
                }
            }
        }
        finally
        {
            ArrayPool<char>.Shared.Return(pool);
        }
    }
}

internal static partial class Kernel32
{
    public const int CREATE_UNICODE_ENVIRONMENT = 0x00000400;
    public const int STARTF_USESTDHANDLES = 0x00000100;
    public const int WAIT_TIMEOUT = 0x00000102;
    public const int WAIT_FAILED = unchecked((int)0xFFFFFFFF);

    [StructLayout(LayoutKind.Sequential)]
    public struct PROCESS_INFORMATION
    {
        public nint hProcess;
        public nint hThread;
        public int dwProcessId;
        public int dwThreadId;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct STARTUPINFOW
    {
        public int cb;
        public nint lpReserved;
        public nint lpDesktop;
        public nint lpTitle;
        public int dwX;
        public int dwY;
        public int dwXSize;
        public int dwYSize;
        public int dwXCountChars;
        public int dwYCountChars;
        public int dwFileAttribute;
        public int dwFlags;
        public short wShowWindow;
        public short cbReserved2;
        public nint lpReserved2;
        public nint hStdInput;
        public nint hStdOutput;
        public nint hStdError;
    }

    [LibraryImport("kernel32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool CloseHandle(
        nint hObject);

    [LibraryImport("kernel32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static unsafe partial bool CreateProcessW(
        char* lpApplicationName,
        char* lpCommandLine,
        nint lpProcessAttributes,
        nint lpThreadAttributes,
        [MarshalAs(UnmanagedType.Bool)] bool bInheritHandles,
        int dwCreationFlags,
        nint lpEnvironment,
        nint lpCurrentDirectory,
        ref STARTUPINFOW lpStartupInfo,
        ref PROCESS_INFORMATION lpProcessInformation);

    [LibraryImport("kernel32.dll", SetLastError = true)]
    public static unsafe partial int GetModuleFileNameW(
        nint hModule,
        void* lpFilename,
        int nSize);

    [LibraryImport("kernel32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool GetExitCodeProcess(
        nint hProcess,
        out int lpExitCode);

    [LibraryImport("kernel32.dll", SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static partial bool TerminateProcess(
        nint hProcess,
        int uExitCode);

    [LibraryImport("kernel32.dll", SetLastError = true)]
    public static partial int WaitForSingleObject(
        nint hHandle,
        int dwMilliseconds);
}
```

### Expected behavior

Exe path is returned. I'm unsure whether it should have the `\\?\` prefix or not.

### Actual behavior

Process hangs indefinitely. With the reproducer above, it will be killed after 5 seconds.

```
PS D:\LongPathTest> dotnet run
==============================================================================================================================
PInvoke RC 0
STDOUT:
Path: 'D:\LongPathTest\bin\Debug\net9.0-windows\LongPathTest.exe'

STDERR:

==============================================================================================================================
PInvoke RC 0
STDOUT:
Path: '\\?\D:\LongPathTest\bin\Debug\net9.0-windows\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\LongPathTest.exe'

STDERR:

==============================================================================================================================
ProcessMainModule RC 0
STDOUT:
Path: 'D:\LongPathTest\bin\Debug\net9.0-windows\LongPathTest.exe'

STDERR:

==============================================================================================================================
ProcessMainModule RC 0
STDOUT:
Path: 'D:\LongPathTest\bin\Debug\net9.0-windows\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\LongPathTest.exe'

STDERR:

==============================================================================================================================
ProcessPath RC 0
STDOUT:
Path: 'D:\LongPathTest\bin\Debug\net9.0-windows\LongPathTest.exe'

STDERR:

==============================================================================================================================
ProcessPath RC -1
STDOUT:

STDERR:
Timed out waiting for process output
```

### Regression?

No

### Known Workarounds

You can use `Process.GetCurrentProcess().MainModule.FileName` or PInvoke the call to `GetModuleFileNameW` with the correct logic.

### Configuration

.NET 9
Windows 2025 but same behaviour occurs on older WIndows versions
Tested on ARM64 but same behaviour occurs on x64 and probably x86
The only thing specific to this configuration is that it runs on Windows. I think Windows XP had a slightly different return value behaviour of `GetModuleFileNameW` but that has long been unsupported.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by huoyaoyuan**
Fixes #110800

### CODE REVIEW

**Comment by jkotas** [comment]
Ideally, we would have a test for this. Unfortunately, it is not easy to build one because of other issues in the end-to-end handling of longs paths (https://github.com/dotnet/runtime/issues/58492).

Have you done ad-hoc testing for this? Does the API return the path with or without `\\?\` prefix?

**Comment by huoyaoyuan** [comment]
Ad-hoc testing passed, path is returned without `\\?\` prefix: 

image

Explorer refuses to create folder or file exceeding MAX_PATH, and PowerShell can't start process exceeding MAX_PATH. cmd can launch the executable.

**Comment by huoyaoyuan** [comment]
Does there need to be a bound to prevent integer overflow? It would cause infinite loop again if path length exceeds 2^30, which is unlikely to happen in any situation.

**Comment by jkotas** [comment]
> It would cause infinite loop again if path length exceeds 2^30, which is unlikely to happen in any situation.

I do not think it would lead to infinite loop. `EnsureCapacity` would throw an exception once there is an overflow and it gets called with negative capacity.

**Comment by jborean93** [comment]
> Ad-hoc testing passed, path is returned without \\?\ prefix:

That's interesting, in my manual test in https://github.com/dotnet/runtime/issues/110800 using PInvoke to call `GetModulePath` it returned the `\\?\` prefix. I wonder if it's due to how the executable was started because I was setting the path to `CreateProcess` with that prefix.

**Comment by am11** [comment]
Seems like there is an opportunity for consolidation here, as logically the control wouldn't reach this point if the runtime/corehost initialization had this logic flawed; so corehost (and only corehost) is doing it right. Maybe it's better to delete calls from all these places:

1. https://github.com/dotnet/runtime/blob/2eb59bf786b7d29feb84fc270530ff2aed65d9e7/src/native/corehost/hostmisc/pal.windows.cpp#L102
2. https://github.com/dotnet/runtime/blob/2eb59bf786b7d29feb84fc270530ff2aed65d9e7/src/libraries/System.Private.CoreLib/src/System/Environment.Windows.cs#L127
3. https://github.com/dotnet/runtime/blob/2eb59bf786b7d29feb84fc270530ff2aed65d9e7/src/coreclr/hosts/corerun/corerun.hpp#L108
4. https://github.com/dotnet/runtime/blob/2eb59bf786b7d29feb84fc270530ff2aed65d9e7/src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp#L244

(there maybe others)

in favor of https://github.com/dotnet/runtime/blob/2eb59bf786b7d29feb84fc270530ff2aed65d9e7/src/native/minipal/getexepath.h#L67 and update it to the logic used in `hostmisc/pal.windows.cpp`. After that, use this `minipal_getexepath()` as we do on unix repo-wide (and windows+unix on mono).

**Comment by jkotas** [comment]
> so corehost (and only corehost) is doing it right

I think that all shipping code is fine, except `Environment.ProcessPath`. Mono on Windows and corerun are non-shipping code. It is fine to fix the non-shipping code, it is low priority though.

> use this minipal_getexepath() as we do on unix repo-wide (and windows+unix on mono).

Note that some of these places want paths for arbitrary modules. For managed implementations on Windows, we tend to avoid the native shims and call the OS APIs directly from C#, even if it means a bit of duplication.

This change LGTM. Number of end-to-end scenarios with process long paths do not work, but that's tracked by other issues.

**Review by jkotas — APPROVED** [review]
Thanks!

**Comment by jkotas** [comment]
/ba-g DeadLetterered linux-arm32 Helix queue, testing not relevant to this change.

**Pull request merged**
