### PR TITLE
[QUIC] Return connection dispose in H3loopback connection

### LINKED ISSUE #57779: [HTTP/3] Loopback server should dispose underlying QUIC connection
The logic to do this is currently disabled: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs#L57

We should re enable this and fix tests accordingly.

### PR DESCRIPTION
**Pull request by ManickaP**
Fixes https://github.com/dotnet/runtime/issues/57779

Seems like everything is working as it should. We do have `WaitForClientDisconnectAsync` as part of H3Loopback connection shutdown.

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by ManickaP** [comment]
Failures unrelated.

**Pull request merged**
