### PR TITLE
Implement resource lookup in satellite assemblies

### LINKED ISSUE #86651: Satellite assembly support in NativeAOT
While working on NativeAOT for iOS support we noticed that satellite resource assemblies aren't loaded in NativeAOT.

This seems to be expected for now:
https://github.com/dotnet/runtime/blob/f6f7d89b99f64d86ceb8cca385a487f825f41007/src/coreclr/tools/aot/ILCompiler.Build.Tasks/ComputeManagedAssembliesToCompileToNative.cs#L167-L170

Filing this issue to track enabling satellite assembly support.

/cc @MichalStrehovsky @jkotas

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #86651.

This was implemented in .NET Native so we just need to resurface it from the compiler.

Note that this is not full support for satellite assemblies (in the assembly binder, etc.) that never existed and nobody ever asked for and I don't even know what it entails.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
> I think we should add at least some testing for this.

You made me look harder for an existing test because I'm not keen to learn how to make satellite assemblies. Hopefully it will pass.

**Comment by vitek-karas** [comment]
> I'm not keen to learn how to make satellite assemblies. 

Not sure if it's a good idea in runtime repo, but I would use Humanizer - it's a prime example of a NuGet which uses localized resources, so if that doesn't work, it's broken.

**Comment by MichalStrehovsky** [comment]
> > I'm not keen to learn how to make satellite assemblies.
> 
> Not sure if it's a good idea in runtime repo, but I would use Humanizer - it's a prime example of a NuGet which uses localized resources, so if that doesn't work, it's broken.

I used System.CommandLine locally. It ships a ton of them. They all have the same strings because everything around System.CommandLine has been a disappointment for me. Hacked my NuGet cache and updated a string in one of them with a hex editor so I could test this. Still better than learning how to make them.

**Comment by MichalStrehovsky** [comment]
Back to draft. Found some issues when the resources don't come from nuget. We might need a brand new command line argument for these things.

**Comment by MichalStrehovsky** [comment]
This is ready for review now.

**Comment by MichalStrehovsky** [comment]
Wow, what a dumb reason to fail the build!

```
2023-05-25T06:12:16.9819457Z     Unhandled Exception: System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
2023-05-25T06:12:16.9826571Z     fr-FR is an invalid culture identifier.
2023-05-25T06:12:16.9833329Z        at System.Reflection.AssemblyName.set_CultureName(String) + 0xa4
2023-05-25T06:12:16.9839851Z        at Internal.TypeSystem.Ecma.EcmaAssembly.GetName() + 0x325
2023-05-25T06:12:16.9846426Z        at ILCompiler.UsageBasedMetadataManager.<GetSatelliteAssemblies>d__25.MoveNext() + 0x42
```

**Review by akoeplinger — APPROVED** [review]

**Review by vitek-karas — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
Fixes #86651.

This was implemented in .NET Native so we just need to resurface it from the compiler.

Note that this is not full support for satellite assemblies (in the assembly binder, etc.) that never existed and nobody ever asked for and I don't even know what it entails.

Cc @dotnet/ilc-contrib

**Pull request merged**
