### PR TITLE
Enable lib tests that used to fail with GC issues

### LINKED ISSUE #70889: NativeAOT - Massive failures
Massive failures on following test run:
- Build [1831520](https://runfo.azurewebsites.net/view/build/?number=1831520) (6/17 PM) - **1057 failures**
    - net7.0-windows-Release-x64-NativeAOT_Release-Windows.81.Amd64.Open - 215 failures
    - net7.0-windows-Release-x64-NativeAOT_Release-Windows.11.Amd64.Client.Open - 215 failures
    - net7.0-windows-Release-x64-NativeAOT_Release-Windows.10.Amd64.Server2022.ES.Open - 209 failures
    - net7.0-windows-Release-x64-NativeAOT_Release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504 - 209 failures
    - net7.0-windows-Release-arm64-NativeAOT_Release-Windows.10.Arm64.Open - 209 failures
- Build [1830538](https://runfo.azurewebsites.net/view/build/?number=1830538) (6/17 AM) - net7.0-windows-Release-x64-NativeAOT_Release-Windows.81.Amd64.Open - **215 failures**
- Build [1829491](https://runfo.azurewebsites.net/view/build/?number=1829491) (6/16 PM) - net7.0-windows-Release-x64-NativeAOT_Release-Windows.81.Amd64.Open - **209 failures** (173 are NullReferenceException)
    - Affected runs (unclear if the list is complete):
        - [System.Net.Numerics](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-fddb64584af14636b1/System.Numerics.Vectors.Tests/1/console.ec6a55f7.log?%3Fhelixlogtype%3Dresult) - 690 failures in the log
        - [Microsoft.Extensions.Logging.EventSource](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-fddb64584af14636b1/Microsoft.Extensions.Logging.EventSource.Tests/1/console.da396e03.log?%3Fhelixlogtype%3Dresult) - 15 failures in the log
        - [Microsoft.Extensions.Caching.Memory](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-fddb64584af14636b1/Microsoft.Extensions.Caching.Memory.Tests/1/console.506f3516.log?%3Fhelixlogtype%3Dresult) - 2 failures in the log
        - [System.Collections.NonGeneric](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-fddb64584af14636b1/System.Collections.NonGeneric.Tests/1/console.4470a024.log?%3Fhelixlogtype%3Dresult) - 4 failures in the log
        - [System.ComponentModel.Annotations](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-fddb64584af14636b1/System.ComponentModel.Annotations.Tests/1/console.343ac2ca.log?%3Fhelixlogtype%3Dresult) - 7 failures in the log
        - [System.Diagnostics.DiagnosticSource](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-fddb64584af14636b1/System.Diagnostics.DiagnosticSource.Tests/1/console.cd367c85.log?%3Fhelixlogtype%3Dresult) - 4 failures in the log

### PR DESCRIPTION
**Pull request by LakshanF**
Fixes #70889. 

Also checks status of the issue #67805

### CODE REVIEW

**Comment by LakshanF** [comment]
Both the NativeAot jobs pass in the latest runs.

1. [Build windows x64 Release NativeAOT_Libs_Passing](https://dev.azure.com/dnceng/public/_build/results?buildId=1831883&view=logs&j=d9366717-4230-52c6-0a51-0b43431c29c7)
2. [Build windows arm64 Release NativeAOT_Libs_Passing](https://dev.azure.com/dnceng/public/_build/results?buildId=1831883&view=logs&j=fd144ac3-b5f0-5ebc-6df0-ea8fd9ae97c1)

**Review by jkotas — APPROVED** [review]

**Pull request merged**
