### PR TITLE
Revert "Revert "Reduce CoreCLR PAL""

### PR DESCRIPTION
**Pull request by janvorli**
Reverts dotnet/runtime#76860

### CODE REVIEW

**Comment by am11** [comment]
A minimal fix is:

```diff
--- a/src/mono/dlls/dbgshim/dbgshim.cpp
+++ b/src/mono/dlls/dbgshim/dbgshim.cpp
@@ -16,7 +16,7 @@
 #include <libloaderapi.h>
 #else
 #include <dlfcn.h>
-#define putenv _putenv
+extern "C" int putenv (const char *__string);
 #endif
 
 #ifndef MAX_LONGPATH
```

For clang14/15, this (or supressing `Wstrict-prototypes`) is also needed:

```diff
--- a/src/native/external/libunwind/include/libunwind_i.h
+++ b/src/native/external/libunwind/include/libunwind_i.h
@@ -132,7 +132,7 @@ byte_order_is_big_endian(int byte_order)
 }
 
 static inline int
-target_is_big_endian()
+target_is_big_endian(void)
 {
     return byte_order_is_big_endian(UNW_BYTE_ORDER);
 }
diff --git a/src/native/external/libunwind/src/mi/init.c b/src/native/external/libunwind/src/mi/init.c
index aa9319981..e4431eeb2 100644
--- a/src/native/external/libunwind/src/mi/init.c
+++ b/src/native/external/libunwind/src/mi/init.c
@@ -41,7 +41,7 @@ long unwi_debug_level;
 #endif /* UNW_DEBUG */
 long unw_page_size;
 static void
-unw_init_page_size ()
+unw_init_page_size (void)
 {
   errno = 0;
   long result = sysconf (_SC_PAGESIZE);
```

(but I'd leave the second one for now and rather upstream that to libunwind directly)

**Comment by janvorli** [comment]
@am11 this would not work. The PAL maintains its own copy of the environment, so the `CreateProcessW` would not see the changes added by the OS `putenv`.

**Comment by janvorli** [comment]
@jkotas the `_putenv` turned out to be the only issue, so I've put it back. Can you please take a look at this revert of revert?
Please note I've left a dummy change in one of the files in the `eng` so that this PR verifies the mono build. I'll remove it before merging the change.

**Review by jkotas — APPROVED** [review]
LGTM!

**Comment by am11** [comment]
@janvorli, Mono's llvmaot leg is failing with:

```
  [ 88%] Building CXX object dlls/mscordbi/utilcode/CMakeFiles/utilcode_obj.dir/configuration.cpp.o
  /__w/1/s/src/mono/dlls/mscordbi/cordb-value.cpp:351:44: error: allocating an object of abstract class type 'CordbArrayValue'
          CordbArrayValue* objectValue = new CordbArrayValue(conn, m_pCordbType, m_debuggerId, m_pClass);
                                             ^
  /__w/1/s/src/coreclr/pal/prebuilt/inc/cordebug.h:15647:43: note: unimplemented pure virtual method 'HasBaseIndicies' in 'CordbArrayValue'
          virtual HRESULT STDMETHODCALLTYPE HasBaseIndicies(
                                            ^
  /__w/1/s/src/coreclr/pal/prebuilt/inc/cordebug.h:15650:43: note: unimplemented pure virtual method 'GetBaseIndicies' in 'CordbArrayValue'
          virtual HRESULT STDMETHODCALLTYPE GetBaseIndicies(
                                            ^
  1 error generated.

```
https://dev.azure.com/dnceng-public/public/_build/results?buildId=51175&view=logs&jobId=cc858e6b-b6f5-5c08-4b62-8cd383bd096a&j=cc858e6b-b6f5-5c08-4b62-8cd383bd096a&t=74861b75-1f67-5a94-490e-d5eb4723f5a5

Looks like dummy change was needed in src/tests as well.

**Comment by janvorli** [comment]
@am11 this doesn't seem to be related to my changes. I have not removed anything that could result in this error. And yesterday I've built using the same command line that the failing build is using locally and it passed.

**Comment by janvorli** [comment]
@jkotas seems like it was caused by your https://github.com/dotnet/runtime/pull/76966.

**Pull request merged**
