### PR TITLE
[release/6.0-rc2][wasm] Fixes, and improvements based on user feedback

### PR DESCRIPTION
**Pull request by radical**
This contains:

- Fix to handle pinvokes with function pointers, which unblocks using native `sqlite` library

- fix for an incremental build issue where the compiled native `.o` files would
  incorrectly get deleted after linking. And that would cause them to be
  recompiled, unnecessarily increasing the build time.

- Change to the default optimization flag used when building for `Debug` config
  from `-Oz` to `-O1`

## Customer impact

- Unblocks being able to use sqlite with blazorwasm
- Improved incremental build experience.
- Faster debug builds. Time for building a blazorwasm template
  project with a native library goes down from `22s` to `12s`.

## Testing

Manual testing, existing tests, and specific new tests.

## Risk

Low. Improves build experience.

### CODE REVIEW

**Comment by radical** [comment]
The test failures are due to missing `Microsoft.NETCore.App.Runtime.browser-wasm` version `5.0.11` on nuget.org . The version is embedded in the latest rc2 sdk, which we use for testing the workloads.
The latest version on `nuget.org` seems to be `5.0.10`.

**Comment by Anipik** [comment]
@marek-safar should we re-target this to 6.0 or is it blocking for rc2 ?

**Comment by radical** [comment]
cc @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
RC2 would definitely help us get better feedback about this feature. But if it’s a big problem I expect we could live with 6.0.

**Comment by radical** [comment]
Closing in favor of https://github.com/dotnet/runtime/pull/59671 .

**Pull request closed without merging**
