### PR TITLE
[release/5.0] Backport Fix for Issue 46529 incorrect 64-bit shift result with cast to int

### LINKED ISSUE #47724: [release/5.0] Backport Fix for Issue 46529 incorrect 64-bit shift result with cast to int
### Incorrect behavior a 64-bit long with shift of 32 or more combined with a cast to int 

The JIT generates incorrect code for this code pattern:

`(int) (X << C)`

where C >= 32 and
and  X is anything with a potential side-effect and is 64-bit integer type

## Customer Impact

Reported by customer who was migrating to .Net Core from the Desktop runtime.

## Regression?

This is a regression that was introduced in the .Net 3.X timeframe by 
https://github.com/dotnet/coreclr/pull/19899

## Testing

SuperPMI, new unit test, CLR outerloop,  asm diffs.

## Risk

Low

### PR DESCRIPTION
**Pull request by briansull**
### Incorrect behavior a 64-bit long with shift of 32 or more combined with a cast to int 

The JIT generates incorrect code for this code pattern:

`(int) (X << C)`

where C >= 32 and
and  X is anything with a potential side-effect and is 64-bit integer type

## Customer Impact

Reported by customer who was migrating to .Net Core from the Desktop runtime.

## Regression?

This is a regression that was introduced in the .Net 3.X timeframe by 
https://github.com/dotnet/coreclr/pull/19899

## Testing

SuperPMI, new unit test, CLR outerloop,  asm diffs.

## Risk

Low

Fixes issue #47724

### CODE REVIEW

**Comment by jeffschwMSFT** [comment]
@briansull can you move the template from the issue into the PR?  We only consider PRs and not issues when doing servicing reviews.  Please ensure to get a CR for this change.

**Review by sandreenko — APPROVED** [review]
LGTM, thank you

**Comment by briansull** [comment]
@jeffschwMSFT Updated

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  We will take for consideration for 5.0.x

**Comment by briansull** [comment]
Posted the fix for [release/3.1]
https://github.com/dotnet/coreclr/pull/28146 [release/3.1] Backport the fix for dotnet/runtime issue 46529

**Pull request merged**
