### PR TITLE
Socket.Unix: improve Linux UDP ReuseAddress implementation

### LINKED ISSUE #30782: Inconsistent socket behavior between dotnet and native
I have observed what I believe to be a discrepancy between managed and native socket.

I am on dotnet core 2.2 and 3.0 on linux x64.

The problem is when you have 2 sockets. Both _bound_ to the same endpoint (`localEP`), and one _connected_ to a remote endpoint (`remoteEp`). AFAIK, dgrams from `remoteEp` should _always_ end up at the _connected_ socket, and dgrams from _anywhere_ else should end up at the _bound_ socket. This behavior can be observed in the code from [here](https://github.com/nplab/DTLS-Examples/blob/master/src/dtls_udp_echo.c). This code implements a DTLS server. It listens for DTLS connection requests on one socket which is only bound to a local EP. When a connection is established, it creates a new socket _bound to the same EP_ and _connects_ it to the remote EP.

The result is that all dgrams from a connected client end up at their respective sockets.

In C# (dotnet 2.2 and 3.0), this cannot be reproduced. Take, for example, the following:

```c#
var localEp = new IPEndPoint(IPAddress.Loopback, 1114);

var socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
socket.Bind(localEp);
...
accept a connection...
...
var clientSocket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
clientSocket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
clientSocket.Bind(localEp);
clientSocket.Connect(remoteEp);
```

At this point, there is no way to guarantee that the client's dgrams will make it to clientSocket. This does not match the behavior of the code I linked above.

From reading dotnet/runtime#27274 I know that as of core 3.0, when setting SO_REUSEADDRESS, SO_REUSEPORT is also set. In the linked code, SO_REUSEPORT is _not_ set on linux. I doubt this is the problem however since my code also doesn't work in 2.2.

I posted a [question on SO](https://stackoverflow.com/questions/57780384/managed-sockets-not-behaving-as-i-expected). I did a test with managed sockets and the result is confusing at best.

[This document](https://lwn.net/Articles/542629/) confirms the expected behavior:

> The first of these is a useful aspect of the implementation. Incoming connections and datagrams are distributed to the server sockets using a hash based on the 4-tuple of the connection—that is, the peer IP address and port plus the local IP address and port. This means, for example, that if a client uses the same socket to send a series of datagrams to the server port, then those datagrams will all be directed to the same receiving server (as long as it continues to exist). This eases the task of conducting stateful conversations between the client and server.

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/dotnet/runtime/issues/30782

The implementation matches with what is reported to work by @matthew798 in https://github.com/dotnet/runtime/issues/30782#issuecomment-540575096.

It is also consistent with nodejs implementation for UDP re-use.

I tried to capture the issue with a new test, but the test actually doesn't fail on Linux for me with the existing implementation.
@matthew798 do you have some input on what needs to change so the test would fail?

### CODE REVIEW

**Comment by tmds** [comment]
cc @dotnet/ncl @antonfirsov

**Review by stephentoub — COMMENTED** [review]
The changes seem reasonable, but I'd really like us to be able to confirm it actually fixes the issue.

**Comment by matthew798** [comment]
Sorry for the late reply. I can try it out tomorrow!

**Comment by tmds** [comment]
@matthew798 besides verifying the fix with your application, can you have a look at the test added in the PR? I think it captures the issue, but it doesn't fail for .NET Core 3.1.

**Comment by tmds** [comment]
@stephentoub @antonfirsov this PR introduces a functional change. Instead of load balancing unicast to multiple sockets bound to the same address, only one socket out of all bound sockets will be receiving the unicast. I **think** this is similar to what ReuseAddress does on Windows: it steals the port from another socket. So the functional change, improves cross-platform behaviour.

**Comment by antonfirsov** [comment]
@tmds I'm hoping to review this by the end of the week.

**Comment by tmds** [comment]
@matthew798 are you able to verify this fixes the issue you reported?

**Comment by tmds** [comment]
ping @matthew798 . Afaik .NET 5 is still taking changes for bug fixes. Based on your input this change may still be included.

**Comment by matthew798** [comment]
Sorry guys, I keep telling myself I'll have time to test it but since the original issue I've had 2 kids so... Well I'm sure you understand.

What I can tell you is that the code I would have used to test it is posted in the original issue with the expected outcome and the actual one. If I do every get a free moment, I might try to test it but I don't see myself having much time. Truly sorry gents, wish I could be more help.

**Comment by tmds** [comment]
> Sorry guys, I keep telling myself I'll have time to test it but since the original issue I've had 2 kids so... Well I'm sure you understand.

I understand :smile: 

> What I can tell you is that the code I would have used to test it is posted in the original issue with the expected outcome and the actual one.

I tried running this code you put in https://github.com/dotnet/runtime/issues/30782#issuecomment-529039689, but I cannot reproduce the issue (like @wfurt https://github.com/dotnet/runtime/issues/30782#issuecomment-531885370).

This PR implements what was suggested in https://github.com/dotnet/runtime/issues/30782#issuecomment-537849493, and you reported to work in https://github.com/dotnet/runtime/issues/30782#issuecomment-540575096.

> If I do every get a free moment, I might try to test it but I don't see myself having much time. Truly sorry gents, wish I could be more help.

If you have a moment, can you check these changes fix the issue for you?

I've [compiled the changes in this PR](https://github.com/dotnet/runtime/files/5195306/compiled.tar.gz). You can patch a [preview8 sdk](https://download.visualstudio.microsoft.com/download/pr/c58adb8a-49cf-466c-9b72-e4c51edae0e5/f915b953a5bfdafc300bd277d80c3513/dotnet-sdk-5.0.100-preview.8.20417.9-linux-x64.tar.gz) by placing them at `shared/Microsoft.NETCore.App/5.0.0-preview.8.20407.11/libSystem.Native.so` and `shared/Microsoft.NETCore.App/5.0.0-preview.8.20407.11/System.Net.Sockets.dll`.

**Comment by danmosemsft** [comment]
@tmds looks like it needs merging.

@matthew798 do you expect you'll have time in the next couple weeks, say, to confirm the fix works? I understand if you can't - but not sure whether we should take the change in that case.

**Comment by tmds** [comment]
I think this change fixes the reported problem, but since we're unable to reproduce the issue, I'm closing the PR.

**Pull request closed without merging**
