### PR TITLE
Fix NTLM authentication from macOS to Windows machines

### LINKED ISSUE #887: NTLM interop problems with MacOS
.NET Core NTLM support is broken on MacOS. It has probably been broken for a while. But due to lack of test coverage we didn't notice. I did my testing on MacOS X 10.15.2 (Catalina).

The root cause is complex and due to possible interop issues with the NTLM support in the Heimdal library that ships with the Mac. Prior to MacOS 10.7, the Mac used MIT Kerberos open-source libraries. In 10.7, it switched to Heimdal open-source libraries. You can see the source code of the various open-source libraries used in the Mac [here](https://opensource.apple.com/).

We have had some reports by customers of problems with Mac .NET Core clients using NTLM. At first, we thought that some NTLM support package was missing on the Mac. On Linux, we require the installation of the 'gss-ntlmssp' package which by default is not present on Linux distros nor on our .NET Core docker images. But the Mac already has NTLM support installed in the GSS-API mechanisms.

We have some simple NTLM tests in our repo:

https://github.com/dotnet/runtime/blob/57df20206691c6123b6e2d392b661cb3541fc24a/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Authentication.cs#L588-L593

And these were running and passing on the Mac. However, the tests only validate that an initial NTLM base64 token is generated and sent to the server. Those tests don't do end-to-end validation of a username/password.

We have other tests for HttpClient that do end-to-end validation:

https://github.com/dotnet/runtime/blob/57df20206691c6123b6e2d392b661cb3541fc24a/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Authentication.cs#L568-L570

But those are not turned on right now. They require environment variables to be enabled to point to a remote NTLM server. After turning on those tests on my local Mac, I discovered that NTLM is broken for Mac .NET Core.

More NTLM (and Kerberos) tests will be enabled for CI as part of follow-up PRs to #463 

If I use Safari on the Mac, it works fine against the NTLM test server. But the Safari app on the Mac uses its own NTLM library and not the GSS-API Heimdal library that .NET Core uses. 

Looking at several WireShark traces of working and non-working scenarios  shows differences in various NTLM protocol fields. Although the Mac is sending NTLM packets to the server, the end result is that the server (Windows in this case) denies the authentication. We'll need to work with the Windows protocol team to help enable advanced diagnostics to see why the Windows server denied the authentication.

I will continue looking into the problem by trying out different NTLM servers to test against (such as Linux Apache) to get more information on working versus non-working scenarios. My current hypothesis is that there is a problem with Heimdal's NTLM v2 support. The [NTLM protocol](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/b38c36ed-2804-4868-a9ff-8dd3182128e4) has many differences between NTLMv1 versus NTLMv2.

### PR DESCRIPTION
**Pull request by filipnavara**
The GSSAPI implementation on macOS has partially broken NTLM implementation. It only supports NTLMv2 with the message integrity code (MIC) as specified by the [MS-NLMP specification](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-nlmp/b38c36ed-2804-4868-a9ff-8dd3182128e4). The MIC is calculated using HMAC-MD5 authentication code over the exchanged NTLM messages with a key named `ExportedSessionKey`. The proper generation of `ExportedSessionKey` requires the implementation to negotiate correct capabilities, namely `NTLMSSP_NEGOTIATE_KEY_EXCH` and at least one of `NTLMSSP_NEGOTIATE_SIGN` or `NTLMSSP_NEGOTIATE_SEAL` flags. By default the macOS implementation negotiates `NTLMSSP_NEGOTIATE_KEY_EXCH` and sends MIC but fails to set one of the additional flags that would make the key exchange valid. This results in violation of the following part of the NTLM specification:

> A session key MUST always exist to generate the MIC (section 3.1.5.1.2) in the authenticate message. NTLMSSP_NEGOTIATE_ALWAYS_SIGN MUST be set in the NEGOTIATE_MESSAGE to the server and the CHALLENGE_MESSAGE to the client.

Adding the `GSS_C_INTEG_FLAG` flag forces macOS to properly [negotiate all the necessary flags](https://github.com/apple-opensource/Heimdal/blob/dfcffe7531e8175ccea972bd0965de241befd205/lib/gssapi/ntlm/init_sec_context.c#L215-L218) (`NTLMSSP_NEGOTIATE_ALWAYS_SIGN` and `NTLMSSP_NEGOTIATE_SIGN`) to make the MIC exchange valid. This in turn enables the whole NTLM exchange to be recognized as valid by Windows server side.

The gss-ntlmssp package on Linux [interprets the `GSS_C_INTEG_FLAG` flag as additional negotiation of `NTLMSSP_NEGOTIATE_SIGN` and `NTLMSSP_NEGOTIATE_KEY_EXCH`](https://github.com/gssapi/gss-ntlmssp/blob/9b6493b1419d615e347d67c636fd238aa4d0f780/src/gss_sec_ctx.c#L132-L137). That should not hurt anything and in fact it may improve security depending on specific configuration. The flag was already specified when NTLM was used by `System.Net.Mail.SmtpClient`.

Fixes #887

### CODE REVIEW

**Comment by filipnavara** [comment]
Due to lack of sufficient testing infrastructure I opted to add a temporary test that connects to a Windows Server 2019 running in disposable Azure virtual machine. I do not intend to include the test permanently and I'll remove it before switching the PR from draft status.

**Comment by filipnavara** [comment]
The results from the CI  on Linux are somewhat mixed:
- Failed authentication on RedHat 7, Ubuntu 16.04, Ubuntu 18.04
- Missing `gss-ntlmssp` package on Centos 8, Debian 10, Fedora 30, Alpine 3.12
- Cannot find KDC for realm "emclientntlm.westus.cloudapp.azure.com" on SLES 15 (possibly missing package as well)

It's hard to say whether the failed authentication is result of the change or whether it never really worked in the first place (for a given server and parameters). I suppose it would be reasonable to open another PR just with the test for comparison.

Predictably Windows and macOS passed just fine.

**Comment by wfurt** [comment]
Linux should be covered somewhat by the "Enterprise tests". It would be interesting to know if the  Ubuntu 18.04 would pass without the change or if there is some general incompatibility. 
While we don't have automated run for macOS, one can build the docker container.
I'll build your change next week and I'll give it some try in my old setup.

**Comment by filipnavara** [comment]
I run three variations of the PR on the CI servers and connecting to my virtual machine.

The Linux machines that have gss-ntlmssp installed successfully connected both with and without this PR when the NETBIOS name was used as domain. The same machines consistently didn't connect when full DNS name was used for the domain.

macOS now connects both with the NETBIOS domain name and the full DNS one.

It would be useful to run the enterprise tests but I expect them to work just fine.

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by filipnavara** [comment]
Thanks for review! Glad to make it in the Preview 6 timeframe 😅

**Pull request merged**
