### PR TITLE
Split superpmi-diffs pipeline runs

### PR DESCRIPTION
**Pull request by BruceForstall**
Run tpdiffs and asmdiffs on separate Helix machines, in parallel, to improve overall job throughput.

### CODE REVIEW

**Comment by BruceForstall** [comment]
Sample run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=232648&view=results

**Comment by BruceForstall** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Fixes #80718

(There are other ideas in that issue for additional parallelization work, but this is the "easy" fix that fixes the biggest time concern.)

**Comment by BruceForstall** [comment]
I created a diff type of "all" that is untested (and unused) -- just in case we might want it someday -- that would allow the previous behavior of doing both asmdiffs/tpdiff on the same machine. This turns out to have been easy to do and almost "falls out".

**Review by jakobbotsch — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Nice!

**Pull request merged**
