### PR TITLE
Use newest PGO data for Linux and windows-x86

### PR DESCRIPTION
**Pull request by agocke**
This data was previously held back because we weren't producing
builds with Linux or windows-x86 but now we are. The Linux builds
now also only produce a single profdata file, coreclr.profdata,
which should contain all the profile information for all the
libraries in the runtime.

### CODE REVIEW

**Review by brianrob — APPROVED** [review]
LGTM.  Am I correct that with this change, if the PGO data doesn't get downloaded properly that the build will fail?  If so, that is a good change.

**Comment by agocke** [comment]
@brianrob In my local testing, yes, that's the behavior.

**Review by davidwrighton — CHANGES_REQUESTED** [review]
Unfortunately, we need to allow for builds that do not have pgo data.

In particular source builds do not use pgo on any platform, and this is encoded in the logic where we don't attempt to restore pgo data on those builds, and the logic in cmake where missing pgo data is tolerated.

**Comment by agocke** [comment]
Change reverted, but I wonder if we could just have source build pass -npgooptimize or something.

**Comment by brianrob** [comment]
Official builds pass an `enforcepgo` flag to make sure that PGO was successful (on Windows at least).  I agree that it would be good to be intentional about whether or not we expect PGO data to be present and used.  That way if something goes wrong when we do expect it to be present, we can fail, rather than just falling back to not using it.

**Review by davidwrighton — APPROVED** [review]

**Comment by agocke** [comment]
Looks like there's something busted here with the MSBuild win-x86 instrumentation. I'll try to figure out what's different.

**Comment by DrewScoggins** [comment]
https://github.com/DrewScoggins/performance-2/issues/5369

**Comment by DrewScoggins** [comment]
We saw some major improvements in Crossgen scenarios, about 8%.

**Pull request merged**
