### PR TITLE
Reenable consumption of PGO data

### PR DESCRIPTION
**Pull request by AustinWise**
This reverts commit 810231cc53d0a397855f038c76a79accb5bc60a5 from #89311. Once the PGO data has been updated with the new linker flags and CI passes on this PR, this can be merged to reenable PGO.

### CODE REVIEW

**Comment by DrewScoggins** [comment]
Sorry, this didn't get updated. We have had updated PGO data for the last three weeks.

**Comment by jeffschwMSFT** [comment]
now that runtime official build has over come an infra issue, this issue is now the top cause of build breaks.  what is the ETA for getting it merged?

**Comment by AustinWise** [comment]
I think #91501 might need to be merged first. I'll cherry pick the changes from that PR into this one to see if that is the case.

**Comment by elinor-fung** [comment]
@jeffschwMSFT what build breaks is this causing? https://github.com/dotnet/runtime/pull/89311 went in last week (29-AUG) and we've had successful builds since then.

**Comment by elinor-fung** [comment]
If you are talking about the `LNK1264` error, I expect that is from: https://github.com/dotnet/runtime/pull/91563 - specifically https://github.com/dotnet/runtime/pull/91563#issuecomment-1710291912

**Comment by AustinWise** [comment]
It looks like #91497 does not currently contain the updated linker flags that would allow this PR to be merged.

**Comment by DrewScoggins** [comment]
Is this ready to merge?

**Comment by AustinWise** [comment]
@DrewScoggins It can be merged once the main branch contains PGO data that was produced from the main branch. Currently it appears the PGO data is being built from the 8.0 branch, which is not compatible. See #93280 for an example of PR that updates the PGO data.

**Comment by amanasifkhalid** [comment]
Hi all, #95510 was recently merged. Is this PR ready to be merged?

**Comment by AustinWise** [comment]
It is still failing with this error:

> LINK : fatal error LNK1268: inconsistent option 'DEPENDENTLOADFLAG:0x800' specified with /USEPROFILE but not with /GENPROFILE

I'm guessing the PGO data is being built from the dotnet/runtime 8.0 branch, which does not have the `DEPENDENTLOADFLAG`. Someone at Microsoft would need to update the dnceng/internal/dotnet-optimization repo to build from the dotnet/runtime main branch to fix the problem.

**Comment by AustinWise** [comment]
Closing in favor of #95540 .

**Pull request closed without merging**
