### PR TITLE
Remove System.Reflection.DispatchProxy package

### LINKED ISSUE #34253: Consider harvesting S.CM.Composition and S.R.DispatchProxy for netstandard2.x
We still live build S.CM.Composition and S.R.DispatchProxy for netstandard2.x even though those are part of the netstandard closure. We should consider harvesting them for netstandard2.x and add a netcoreapp configuration.

This is controversial so I'm not saying we should do it but considering it.

@ericstj thoughts?

### PR DESCRIPTION
**Pull request by ericstj**
This library was added to .NETStandard2.1 and thus can no-longer be
changed.

Fixes https://github.com/dotnet/runtime/issues/34253

### CODE REVIEW

**Comment by stephentoub** [comment]
> This library was added to .NETStandard2.1 and thus can no-longer be changed.

Surface area can't be changed, but what happens if we need to fix a bug?  Do we just do that in the corefx release/3.1 servicing branch?

**Comment by joperezr** [comment]
> Surface area can't be changed, but what happens if we need to fix a bug in the package? Do we just do that in the corefx release/3.1 servicing branch?

Yup that would also mimic to similar packages that we have removed in the past.

FWIW I have cherry picked this into my configurations PR which needs it in case you want to go ahead and close this one and just merge mine instead.

**Comment by ericstj** [comment]
Yep, if the fix was important for downlevel we'd ship it in servicing.  If we only care about fix in 5.0 we'd just update the codebase in master.  Effectively we're no longer treating this as an OOB component in master which is consistent with the assembly being part of the shared framework and .NETStandard.

**Comment by stephentoub** [comment]
Thanks.

**Review by ViktorHofer — APPROVED** [review]
Thanks 👍

**Comment by ViktorHofer** [comment]
Failures are known (archive decompression issue, macos timeout).

**Pull request merged**
