### PR TITLE
JIT: don't optimize calls to CORINFO_HELP_VIRTUAL_FUNC_PTR for interface class lookups

### LINKED ISSUE #82127: Test failure Loader/classloader/DefaultInterfaceMethods/reabstraction/reabstraction/reabstraction.sh
https://dev.azure.com/dnceng-public/public/_build/results?buildId=169012&view=ms.vss-test-web.build-test-results-tab&runId=3405426&paneView=debug

Looks like it fails in all `jitobjectstackallocation` scenarios.

coreclr linux arm64 Checked jitobjectstackallocation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8

```
export DOTNET_TieredCompilation=0
export DOTNET_DbgEnableMiniDump=1
export DOTNET_EnableCrashReport=1
export DOTNET_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export DOTNET_JitObjectStackAllocation=1
```

```
    Loader/classloader/DefaultInterfaceMethods/reabstraction/reabstraction/reabstraction.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/Loader.classloader/DefaultInterfaceMethods/reabstraction/reabstraction/reabstraction.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false reabstraction.dll ''
      Expected: 100
      Actual: 255
      END EXECUTION - FAILED
      Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 2/13/2023 12:01:11 AM
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/Loader/classloader/DefaultInterfaceMethods/reabstraction/reabstraction/reabstraction.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at Loader_classloader._DefaultInterfaceMethods_reabstraction_reabstraction_reabstraction_._DefaultInterfaceMethods_reabstraction_reabstraction_reabstraction_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/Loader.classloader/DefaultInterfaceMethods/reabstraction/reabstraction/reabstraction.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false reabstraction.dll ''
        Expected: 100
        Actual: 255
        END EXECUTION - FAILED
        Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 2/13/2023 12:01:11 AM
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/Loader/classloader/DefaultInterfaceMethods/reabstraction/reabstraction/reabstraction.sh
  Finished:    Loader.classloader.XUnitWrapper
```

@AndyAyersMS

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The jit currently replaces calls to `CORINFO_HELP_VIRTUAL_FUNC_PTR` whose results are unused with null pointer checks.

But if we're looking up a method on an interface, this helper can now throw a variety of exceptions, so this optimization is incorrect.

Fixes #82127.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib 

I could not figure out when or why the helper call behavior changed, but per SPMI this optimization only kicks in for this one test, so it's not that important.

**Comment by jkotas** [comment]
I have added this optimization based on 2004/08/31 ... memories :-) It was based on customer feedback: Some (3rd party?) compiler used `ldvirtftn` + `pop` to implement null checks and the ask was to make it more efficient. Is this idiomatic pattern to implement null checks going to regress?

**Comment by AndyAyersMS** [comment]
> Is this idiomatic pattern to implement null checks going to regress?

Yes, if it is heavily used by some class of IL generators, we'll end up with helper calls instead of simple null checks, and perhaps miss downstream inferences that after this point the ref can't be null (that part I'd need to investigate further).

It seems like the possibility of some other exception kinds being thrown by `CORINFO_HELP_VIRTUAL_FUNC_PTR` is a relatively new thing -- I have not yet been able to track down exactly when or how this changed.

**Review by BruceForstall — APPROVED** [review]

**Comment by jkotas** [comment]
The interface method resolution can fail for number of different reasons. It has been the case since forever, we just did not notice. I think it should be still ok to do this optimization for non-interface methods.

**Comment by AndyAyersMS** [comment]
Odd and seemingly unrelated failure on musl arm/arm64:
```
  Discovering: System.Collections.Immutable.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Collections.Immutable.Tests (found 2901 of 2986 test cases)
  Starting:    System.Collections.Immutable.Tests (parallel test collections = on, max threads = 2)

Assert failure(PID 22 [0x00000016], Thread: 41 [0x0029]): pImportSection == pModule->GetImportSectionForRVA(rva)
    File: /__w/1/s/src/coreclr/vm/prestub.cpp Line: 2991
    Image: /root/helix/work/correlation/dotnet
```

**Comment by AndyAyersMS** [comment]
I don't see those diffs building locally.

**Comment by AndyAyersMS** [comment]
Going to update to latest main and retry.

**Comment by BruceForstall** [comment]
Testing hit a lot of infra issues. Going to cycle it.

**Comment by AndyAyersMS** [comment]
Tizen armel: dotnet build tool installation crashed
```
Welcome to .NET 8.0!
---------------------
SDK Version: 8.0.100-alpha.1.23061.8

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
/__w/1/s/eng/common/tools.sh: line 469:   547 Segmentation fault      (core dumped) "$_InitializeBuildTool" "$@"

```

**Comment by AndyAyersMS** [comment]
This PR is jinxed.

**Comment by AndyAyersMS** [comment]
Failure to unzip build assets:
```
Searching for: **\libraries_bin_windows_x64_Release.zip under directory: D:\a\_work\1\s\__download__\libraries_bin_windows_x64_Release\
Found: 1 files to extract:
D:\a\_work\1\s\__download__\libraries_bin_windows_x64_Release\libraries_bin_windows_x64_Release.zip
Extracting file: D:\a\_work\1\s\__download__\libraries_bin_windows_x64_Release\libraries_bin_windows_x64_Release.zip
D:\a\_work\_tasks\ExtractFiles_5e1e3830-fbfb-11e5-aab1-090c92bc4988\1.213.0\7zip\7z.exe x -oD:\a\_work\1\s\artifacts D:\a\_work\1\s\__download__\libraries_bin_windows_x64_Release\libraries_bin_windows_x64_Release.zip
ERROR: D:\a\_work\1\s\__download__\libraries_bin_windows_x64_Release\libraries_bin_windows_x64_Release.zip
Can not open the file as archive
```

**Comment by AndyAyersMS** [comment]
Runtime failure looks like an instance of #25979.

**Comment by AndyAyersMS** [comment]
SPMI replay failure is #82397.

**Pull request merged**
