### PR TITLE
JIT: Propagate LCL_ADDRs into natural loops

### PR DESCRIPTION
**Pull request by jakobbotsch**
Just an experiment to see TP cost vs asm diffs... probably unlikely to be worth it.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Diffs were tiny, doesn't seem to be worth the complexity.

**Comment by AndyAyersMS** [comment]
@jakobbotsch I am likely going to want to revive this or something like it, so I can get stack allocated enumerator addresses propagated into loops.

But I will also need something more aggressive for handlers, since in my cases there are updates needed in finally/fault regions.

I have a prototype that builds a handler entry assertion set as follows:
* start with the try region entry assertions set (currently recomputed, but can be simply saved since the try entry should appear before the handler entry in the RPO)
* remove any assertions for locals defined in the try or any enclosed EH region
* remove any assertions for locals defined in any enclosing try's filter
* remove any assertions for locals defined in the handler, if the handler entry is a loop header (or clear all assertions, if handler entry has a non-loop backedge)

Diffs from this are still small, but I expect will be bigger once I figure out how to handle the case where the enumerator is conditionally defined to be a local (as in GDV).

I'm less sure how to compute this at acceptable cost, especially the loop and EH regions nest and/or intersect, and we need the computation for loops as well. One thought is to revise the work in this PR to populate suitable per-block bit vectors, so that the per-block analysis (which is the costly part) doesn't need to be done more than once, and then just compute the per-block parts on demand if missing.

**Comment by jakobbotsch** [comment]
@AndyAyersMS I don't think anything special needs to happen for handlers since they are modelled faithfully by the DFS traversal we are using. That is, I think we can just switch the `PredBlocks` use in `StartBlock` to `BlockPredsWithEH` and then remove the `bbIsHandlerBeg` restriction. I think the existing logic should be fine with those changes, unless you can see any problems with that?

As for `LoopDefinitions`, there is `LoopLocalOccurrences` in inductionvariableopts.cpp that I think we should factor and reuse for the purpose here as well. I don't expect the TP cost to be super high for it.

**Comment by jakobbotsch** [comment]
Hmm, that won't be sufficient since we logically need to differentiate between "assertions true at the predecessor's out edges" and "assertions true over the entire predecessors". Perhaps we could just track both...

**Pull request closed without merging**
