### PR TITLE
Enable more libraries tests

### PR DESCRIPTION
**Pull request by MichalStrehovsky**

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
@jkotas does the fix for RuntimeInformation.RuntimeIdentifier look reasonable? We could compute the Linux distro name at runtime, but I would want it to be done lazily and that's currently not compatible with it being stored as an AppContext value. Could just file an issue on that.

**Comment by jkotas** [comment]
> does the fix for RuntimeInformation.RuntimeIdentifier look reasonable? 

Yes, it looks reasonable. We are working towards getting rid of the distro-specific RIDs: https://github.com/dotnet/designs/pull/260

**Pull request merged**
