### PR TITLE
Introduce a diagnostic switch to turn off the use of file mapping in PE loader.

### PR DESCRIPTION
**Pull request by VSadov**
Introducing unsupported/internal `DOTNET_PELoader_DisableMapping` switch.

The switch is available in both debug and release builds.
Setting `DOTNET_PELoader_DisableMapping` to not 0 will force the fallback paths in PE loader where file sections are copied to preallocated memory ranges instead of being mapped. 

We needed to turn off file mapping in a few scenarios recently when narrowing down the root cause of bugs. 
Without a switch, turning off the file mapping is nontrivial and especially so in a singlefile scenario.

### CODE REVIEW

**Comment by VSadov** [comment]
CC: @tommcdon

**Comment by VSadov** [comment]
close/reopen to ustuck the CLA check

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by VSadov** [comment]
Thanks!!

**Pull request merged**
