### PR TITLE
Define SystemReflectionMetadataLoadContextVersion property for package references

### PR DESCRIPTION
**Pull request by MichaelSimons**
System.Reflection.MetadataLoadContext references in WasmAppBuilder/WasmAppBuilder.csproj were using an incorrect version.props property which breaks source-build. In 6.0.3 SystemReflectionMetadataVersion was revved but not SystemReflectionMetadataLoadContextVersion therefore breaking
the build because a System.Reflection.MetadataLoadContext with the SystemReflectionMetadataVersion does not exist.

### CODE REVIEW

**Review by crummel — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]

**Comment by MichaelSimons** [comment]
@akoeplinger - can you please help with CI.  The failures seem unrelated.

**Comment by MichaelSimons** [comment]
@akoeplinger - Friendly ping, can you please help with CI. The failures seem unrelated.

**Comment by akoeplinger** [comment]
The CI failure is unrelated (https://github.com/dotnet/runtime/issues/61524), but I don't have permissions to merge. @ericstj please merge this one.

**Pull request merged**
