### PR TITLE
JIT: Avoid mask<->vector optimization for masks used in unhandled ways

### LINKED ISSUE #110306: JIT: Assertion failed 'newLclValue.BothDefined()' during 'Do value numbering'
```csharp
// Generated by Fuzzlyn v2.4 on 2024-12-01 16:32:26
// Run on X64 Linux
// Seed: 7861295224295601455-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86avx512fx64,x86bmi1,x86bmi1x64,x86bmi2,x86bmi2x64,x86fma,x86lzcnt,x86lzcntx64,x86pclmulqdq,x86popcnt,x86popcntx64,x86sse,x86ssex64,x86sse2,x86sse2x64,x86sse3,x86sse41,x86sse41x64,x86sse42,x86sse42x64,x86ssse3,x86x86base
// Reduced from 115.8 KiB to 0.9 KiB in 00:02:27
// Hits JIT assert in Release:
// Assertion failed 'newLclValue.BothDefined()' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Do value numbering' (IL size 61; hash 0xade6b36b; FullOpts)
// 
//     File: /__w/1/s/src/coreclr/jit/valuenum.cpp Line: 6138
// 
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class C0
{
    public uint F0;
}

public struct S0
{
    public C0 F2;
}

public class C3
{
    public byte F0;
}

public class Program
{
    public static S0 s_3;
    public static void Main()
    {
        var vr5 = Vector256.Create(1, 0, 0, 0);
        Vector256<long> vr15 = Vector256.Create<long>(0);
        Vector256<long> vr8 = Avx512F.VL.CompareNotEqual(vr5, vr15);
        long vr9 = 0;
        var vr10 = new C3();
        vr8 = M3(vr10);
        long vr11 = vr9;
        var vr12 = s_3.F2.F0;
        vr8 = vr8;
    }

    public static Vector256<long> M3(C3 argThis)
    {
        try
        {
        }
        finally
        {
            byte var5 = argThis.F0;
        }

        return Vector256.Create<long>(0);
    }
}
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
When a local is used as a return buffer it is not address exposed, so the address-exposure check was not sufficient. Add checks for `LCL_ADDR`, `LCL_FLD` and `STORE_LCL_FLD` to make sure any use of a mask local that is not converted disqualifies it from participating in the optimization.

Also avoid doing some work for locals that are not SIMD/mask typed (common case). Previously we would do some unnecessary hash table lookups and other things in these cases.

Fix #110306

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
I haven't looked into them, but I suspect this will also fix the "Assert `unreached()`" failures from the [latest Antigen run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=883086&view=ms.vss-build-web.run-extensions-tab).

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @a74nh @tannergooding 

[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=883673&view=ms.vss-build-web.run-extensions-tab)

**Review by tannergooding — APPROVED** [review]

**Comment by tannergooding** [comment]
Do we not have an outerloop job testing `SVE` under the AltJit?

Is that why these didn't get caught after the initial PR went in, and only after the x64 support came online?

**Comment by kunalspathak** [comment]
> Do we not have an outerloop job testing `SVE` under the AltJit?
> 
> Is that why these didn't get caught after the initial PR went in, and only after the x64 support came online?

The existing pipeline is broken because it was not testing the right thing. I had https://github.com/dotnet/runtime/pull/107475 but I saw some other non-sve failures which I didn't get time to investigate. We would get Cobalt machines in CI added shortly, so going forward, it will get caught naturally.

**Comment by tannergooding** [comment]
> This doesn't repro on arm64 because SIMD16 is always returned by value there

I don't believe we do this for cases like `struct S { Vector128<T> field; }` or other HVA qualifying structs today; it is a known gap/mismatch in the ABI handling.

**Comment by jakobbotsch** [comment]
> > This doesn't repro on arm64 because SIMD16 is always returned by value there
> 
> I don't believe we do this for cases like `struct S { Vector128<T> field; }` or other HVA qualifying structs today; it is a known gap/mismatch in the ABI handling.

16 byte structs on ARM64 are returned in two registers, not via return buffer.

**Comment by jakobbotsch** [comment]
> Could this appear on Arm64? Interesting as I never saw any failures myself on Fuzzlyn Arm64.

The `LCL_FLD` and `STORE_LCL_FLD` cases could probably occur, but it requires some odd looking C# to make them appear.

**Comment by tannergooding** [comment]
> 16 byte structs on ARM64 are returned in two registers, not via return buffer.

For some classifications, not all classifications. There are multiple factors that influence it including total size, whether it is all integer, all floating-point, all SIMD, or mixed data types, etc.

The classifications are effectively `Composite Type - Known Size`, `Compositive Type - Unknown Size`, `HFA`, `HVA`. It is only `Composite Type - Known` size where the size is no more than 16 bytes that it may get passed/returned in 2 general purpose registers. An HFA/HVA may instead be passed in 1-4 floating-point/SIMD registers, while all other structs are effectively passed by return buffer. Similarly other special considerations (such as copy constructors in C++) may change the classification.

But regardless, my point was that I imagine this general issue should've been reproducible on SVE, it is not unique to x64

**Review by kunalspathak — APPROVED** [review]
LGTM

**Pull request merged**
