### PR TITLE
Remove dead code in XML

### PR DESCRIPTION
**Pull request by danmoseley**
Remove some dead code using https://github.com/dotnet/codeformatter's useful DeadRegions.exe.

ENABLEDATABINDING seems to be undefined even in .NET Framework.

I left a couple of #if false places that still seemed to be useful.

### CODE REVIEW

**Review by buyaa-n — APPROVED** [review]
> Remove some dead code using https://github.com/dotnet/codeformatter's useful DeadRegions.exe.
> 
> ENABLEDATABINDING seems to be undefined even in .NET Framework.

LGTM, thanks!

> I left a couple of #if false places that still seemed to be useful.

I am OK with removed `#if false` sections, i guess devs added them for reference might not needed anymore, i would let @krwq take another look as he know more the context

**Comment by danmosemsft** [comment]
Thanks @buyaa-n the only reason I didn't @ you was because I saw @krwq on email 😄

**Comment by SunnyWar** [comment]
Actual link: [https://github.com/dotnet/codeformatter](url)

**Review by krwq — APPROVED** [review]
LGTM, double checking with outerloop tests there is no weird test dependency

**Comment by krwq** [comment]
Thanks @danmosemsft!

**Comment by krwq** [comment]
Failures don't look XML related so LGTM

**Pull request merged**
