### PR TITLE
Add HttpClient.PatchAsJsonAsync() apis

### LINKED ISSUE #60531: [API Proposal]: HttpClient.PatchAsJsonAsync()
### Background and motivation

#45405

It's natural to have `PatchAsJsonAsync` when we already got `PostAsJsonAsync` and `PutAsJsonAsync`.

### API Proposal

```C#
namespace  System.Net.Http.Json
{
    public static class HttpClientJsonExtensions
    {
        public Task<HttpResponseMessage> PatchAsJsonAsync<TValue>(this HttpClient client, string? requestUri, TValue value, JsonSerializerOptions? options = null, CancellationToken cancellationToken = default);
        public Task<HttpResponseMessage> PatchAsJsonAsync<TValue>(this HttpClient client, Uri? requestUri, TValue value, JsonSerializerOptions? options = null, CancellationToken cancellationToken = default);
        public Task<HttpResponseMessage> PatchAsJsonAsync<TValue>(this HttpClient client, string? requestUri, TValue value, JsonTypeInfo<TValue> jsonTypeInfo = null, CancellationToken cancellationToken = default);
        public Task<HttpResponseMessage> PatchAsJsonAsync<TValue>(this HttpClient client, Uri? requestUri, TValue value, JsonTypeInfo<TValue> jsonTypeInfo = null, CancellationToken cancellationToken = default);
        public Task<HttpResponseMessage> PatchAsJsonAsync<TValue>(this HttpClient client, string? requestUri, TValue value, CancellationToken cancellationToken = default);
        public Task<HttpResponseMessage> PatchAsJsonAsync<TValue>(this HttpClient client, Uri? requestUri, TValue value, CancellationToken cancellationToken = default);
    }
}
```     

### API Usage

```C#
var client = new HttpClient();
client.DefaultRequestHeaders.Add("Accept", "application/vnd.github.v3+json");
var body = new { Sha = "sha" };
var response = await client.PatchAsJsonAsync("https://api.github.com/repos/octocat/hello-world/git/refs/REF", body);
if (response.IsSuccessfulStatusCode)
{
    Console.WriteLine("Patched!");
}
```     

### Alternative Designs

_No response_

### Risks

_No response_

### PR DESCRIPTION
**Pull request by ikesnowy**
Fixes #60531

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
@dotnet/ncl FYI

**Comment by scalablecory** [comment]
Were the revised defaults ran through API review? I think just an email will be enough...

**Review by scalablecory — COMMENTED** [review]
lgtm once addressed

**Review by eiriktsarpalis — APPROVED** [review]
Thanks!

**Review by eiriktsarpalis — CHANGES_REQUESTED** [review]

**Review by eiriktsarpalis — APPROVED** [review]

**Pull request merged**
