### PR TITLE
PGO: Enable profiled casts by default

### PR DESCRIPTION
**Pull request by EgorBo**
This PR enables PGO for `castclass/isinst` by default. Since we now have a dedicated tier for instrumentation it should not be a big deal to enable more probes IMO. Profiled casts seem to help LINQ for small inputs since LINQ is typically full of type casts for fast paths (e.g. [this](https://github.com/dotnet/runtime/blob/21b4a8585362c1bc12d545b63e62a0d9dd4e8673/src/libraries/System.Linq/src/System/Linq/SequenceEqual.cs#L25-L27)).

### Benchmark:
```cs
[HideColumns("Error", "Job", "StdDev", "Median", "RatioSD")]
public class LinqBenchmarks
{
    IEnumerable<int> _enum1 = new int[10];
    IEnumerable<int> _enum2 = new int[10];

    [Benchmark]
    public bool SequenceEqual() => _enum1.SequenceEqual(_enum2);

    [Benchmark]
    public int ElementAt() => _enum1.ElementAt(5);

    [Benchmark]
    public int Count() => _enum1.Count();

    [Benchmark]
    public List<int> ToList() => _enum1.ToList();
}
```

| Method        | Toolchain                 | Mean     | Ratio |
|-------------- |-------------------------- |---------:|------:|
| SequenceEqual |    \Core_Root\corerun.exe | 9.372 ns |  2.96 |
| SequenceEqual | \Core_Root_PR\corerun.exe | **3.171 ns** |  1.00 |
|               |                          |          |       |
| ElementAt     |   \Core_Root\corerun.exe | 7.163 ns |  4.69 |
| ElementAt     | \Core_Root_PR\corerun.exe | **1.529 ns** |  1.00 |
|               |                           |          |       |
| Count         |    \Core_Root\corerun.exe | 3.482 ns |  3.14 |
| Count         | \Core_Root_PR\corerun.exe | **1.127 ns** |  1.00 |
|               |                          |          |       |
| ToList |    \Core_Root\corerun.exe | 16.334 ns |  1.30 |
| ToList | \Core_Root_PR\corerun.exe | **12.332 ns** |  1.00 |

_PS: `SequenceEqual` should benefit from https://github.com/dotnet/runtime/pull/96571 too_

### Codegen example

```cs
// Promote IsList to Tier1 with PGO
for (int i = 0; i < 200; i++)
{
    IsList(new int[10]); // source is always int[]
    Thread.Sleep(10);
}

[MethodImpl(MethodImplOptions.NoInlining)]
bool IsList<T>(IEnumerable<T> source) => source is IList<T>;
```
Codegen diff (Main vs PR) for `IsList`:
```diff
; Assembly listing for method IsList
G_M12490_IG01:
       sub      rsp, 40
G_M12490_IG02:
+      mov      rax, rcx
+      test     rax, rax                 ; if (source == null)
+      je       SHORT G_M12490_IG05
+G_M12490_IG03:
+      mov      rdx, 0x7FF941DE9750
+      cmp      qword ptr [rax], rdx
+      je       SHORT G_M12490_IG05      ; if (source is int[])
+G_M12490_IG04:
       mov      rdx, rcx
       mov      rcx, 0x7FF942439A60
       call     CORINFO_HELP_ISINSTANCEOFINTERFACE ; slow fallback
+G_M12490_IG05:
       test     rax, rax
       setne    al
       movzx    rax, al
-G_M12490_IG03:
+G_M12490_IG06:
       add      rsp, 40
       ret      
; Total bytes of code 59
```

@AndyAyersMS @dotnet/jit-contrib do you think this should go through an internal run of dotnet/performance first?
I tested impact on TE (no impact on startup and rps) and a few desktop app. Also, I did a run of 250 LINQ benchmarks in dotnet/performance (10% of them improved, none regressed).

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks. If this is isinst/castclass only, I assume it doesn't cover a pattern like this?
https://github.com/dotnet/runtime/blob/21b4a8585362c1bc12d545b63e62a0d9dd4e8673/src/libraries/System.Linq/src/System/Linq/Enumerable.cs#L39-L59
(or is that covered separately?)

**Comment by EgorBo** [comment]
> Thanks. If this is isinst/castclass only, I assume it doesn't cover a pattern like this?
> 
> https://github.com/dotnet/runtime/blob/21b4a8585362c1bc12d545b63e62a0d9dd4e8673/src/libraries/System.Linq/src/System/Linq/Enumerable.cs#L39-L59
> 
> 
> (or is that covered separately?)

This code looks like it's already devirtualized by hands so there is nothing JIT can do additionally here. Although, you can convert it back to `is TSource[] arr` if you want (but it might regress NAOT that typically doesn't have any PGO data and Mono).

**Comment by stephentoub** [comment]
> you can convert it back to is TSource[] arr if you want
> One benefit of is TSource[] arr would be that uint[]/int[] case 🙂

It was written this way to explicitly avoid the variance costs

**Review by AndyAyersMS — APPROVED** [review]

**Comment by EgorBo** [comment]
> As a follow up you might look at whether cloning can profitably key off of one of these casts. Right now type test cloning requires `OMF_HAS_GUARDEDDEVIRT`.

Ah good point, will file an issue for it!

**Comment by EgorBo** [comment]
Improvements:

- https://github.com/dotnet/perf-autofiling-issues/issues/27131
- https://github.com/dotnet/perf-autofiling-issues/issues/27117

**Pull request merged**
