### PR TITLE
CI: specify BaseOS for the unknown rid build.

### LINKED ISSUE #86169: CI failure in the "banana" rid leg on Centos Stream 8
We're seeing a failure on the `banana` leg where we use a fake RID that isn't in the RID graph. The RID graph construction tools look like they are unable to determine where to add the `banana.24-x64` RID into the RID graph. I think this is new with the CentOS Stream 8 base image change, but there have been many different failures in this leg for a while that I'm not sure what caused it to start failing in this manner.

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/dotnet/runtime/issues/86169.

@jkoritzinsky @ViktorHofer @ericstj ptal.

### CODE REVIEW

**Review by jkoritzinsky — DISMISSED** [review]
The files in eng/common come from dotnet/arcade. Can we update them there and consume the updates here?

**Comment by tmds** [comment]
> The files in eng/common come from dotnet/arcade. Can we update them there and consume the updates here?

I will look into it.

Can we trigger the banana-leg on this PR to validate this fixes the issue?

**Comment by ViktorHofer** [comment]
Unfortunately there isn't a good way without a yml change. If you temporarily remove the following condition, the banana sourcebuild leg should run: https://github.com/dotnet/runtime/blob/f345a70611c2a061d9913a6ddf89f20ca486c1f1/eng/pipelines/runtime.yml#L1455

**Comment by tmds** [comment]
The banana leg passed: https://dev.azure.com/dnceng-public/public/_build/results?buildId=284723&view=logs&j=7b858ce4-c6ea-5e44-1ed3-07363cd3c838&t=7b858ce4-c6ea-5e44-1ed3-07363cd3c838.

I've removed the validation commit.

**Comment by tmds** [comment]
> The files in eng/common come from dotnet/arcade. Can we update them there and consume the updates here?

Created https://github.com/dotnet/arcade/pull/13677.

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
