### PR TITLE
Compile the wasm cross compiler with llvm.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
Cannot reproduce the failure locally.

**Comment by directhex** [comment]
@vargaz CI runs wasm builds on Linux, but the changes in here are adding a dependency on LLVM macOS builds. We need slightly smarter logic to take host OS into account, not just target OS, in picking the LLVM build to use.

**Comment by vargaz** [comment]
Needs
https://github.com/dotnet/llvm-project/commit/59b943ad8cef9138370098717e946fc3fa59bcdc

**Comment by vargaz** [comment]
Depends on:
https://github.com/dotnet/runtime/pull/35443

**Comment by vargaz** [comment]
This seems to work now.

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
