### PR TITLE
Add internal nuget to package tasks, and targets for workload testing

### PR DESCRIPTION
**Pull request by radical**
New nuget: `Microsoft.NET.Runtime.WorkloadTesting.Internal`

Nuget to package the workload testing targets, and tasks for internal
use. This is a non-shipping nuget which can be used for by other dotnet
repos to test workloads.

`eng/testing/workloads-testing.targets` is extracted into a
`WorkloadTesting.Core.targets`, and the `dotnet/runtime` repo specific
bits are left in `eng/testing/workloads-testing.targets`.

Also, build the task for `net8.0`. It will be used by `dotnet/aspire`.

### CODE REVIEW

**Review by maraf — APPROVED** [review]

**Comment by radical** [comment]
thanks for review @maraf!

**Comment by EgorBo** [comment]
@radical I think this broke main?

```
/__w/1/s/artifacts/sb/src/src/tasks/WorkloadBuildTasks/InstallWorkloadFromArtifacts.cs(61,38): error CS8795: Partial method 'InstallWorkloadFromArtifacts.bandVersionRegex()' must have an implementation part because it has accessibility modifiers. [/__w/1/s/artifacts/sb/src/src/tasks/WorkloadBuildTasks/WorkloadBuildTasks.csproj::TargetFramework=net8.0]
      0 Warning(s)
      1 Error(s)
```

**Comment by radical** [comment]
https://github.com/dotnet/runtime/issues/98130

**Pull request merged**
