### PR TITLE
Avoid setting the brick of the next region during sweep in plan

### PR DESCRIPTION
**Pull request by cshung**
Note that the `last_marked_obj_end_b` is the exclusive end address of the last marked object including alignment, therefore in a special case when the region ends with a marked object, `last_marked_obj_end_b` is exactly the end of the region. 

In that case, if we set that brick, we could potentially overwrite the brick of another region (which could belong to another heap)

Let's say we had a plug tree root stored on the brick of the next region, but the entry got overwritten by -1 because of the above. The subsequent `relocate_address` would read a `-1` on that brick and miss the plug tree. The rest will go south.

### CODE REVIEW

**Comment by Maoni0** [comment]
definitely not a good idea to be setting another region's bricks... 😰 

now I'm re-reading the code, I don't believe the else block is needed at all - if last marked object's start is in a different brick from that of its end, it means we would have already called fix_brick_to_highest on it and its next object which would do the right thing of not setting the end object's brick. can you please get rid of the else and verify that it works?

**Comment by Maoni0** [comment]
definitely not a good idea to be setting another region's bricks... 😰 

I believe we should be using 

`        size_t last_marked_obj_end_b = brick_of (last_marked_obj_end - 1);`

instead of 

`        size_t last_marked_obj_end_b = brick_of (last_marked_obj_end);`

because if last_marked_obj_end_b is right at a brick boundary it means we should not be setting that brick at all. and then the code should be correct. we still need to set the brick for when the last part of the last object is in the brick that's different from last_marked_obj_start_b. we just don't want to set the brick when the last object end is right where a brick starts (as we'd be setting the brick for memory isn't in use).

**Review by phocodes — APPROVED** [review]

**Comment by cshung** [comment]
I agree with the analysis, and I did the testing

I confirm the original symptom does not repro with the new fix, so we will go with the new fix.

**Review by Maoni0 — APPROVED** [review]
LGTM!

**Pull request merged**
