### PR TITLE
[Group 9] Enable nullable annotations for `Microsoft.Extensions.Hosting.Systemd`

### LINKED ISSUE #43605: Annotate Microsoft.Extensions.* assemblies for nullable reference types
In .NET 6.0, we plan to annotate Microsoft.Extensions.* assemblies built from the dotnet/runtime repo. Work involves:

* Submit individual PRs, one for each assembly. Each PR should include changes to both the src and the ref. Each PR should contain only changes related to the nullable annotations/attributes, no other changes.
* PRs can be merged once the annotations have been appropriately reviewed in PR.

*In .NET 5.0, nullable references types was tracked in #2339, and remainder are being tracked in #41720 for .NET 6.0*

#### Group 1 ####
- [ ] Microsoft.Extensions.Logging.Abstractions
- [ ] Microsoft.Extensions.DependencyModel
- [ ] Microsoft.Extensions.DependencyInjection.Abstractions
- [ ] Microsoft.Extensions.Primitives
- [ ] Microsoft.Extensions.FileSystemGlobbing
- [ ] Microsoft.Extensions.Configuration.Abstractions
- [ ] Microsoft.Extensions.FileProviders.Abstractions

#### Group 2 ####
- [ ] Microsoft.Extensions.Options
- [ ] Microsoft.Extensions.Caching.Abstractions
- [ ] Microsoft.Extensions.DependencyInjection
- [ ] Microsoft.Extensions.FileProviders.Physical
- [ ] Microsoft.Extensions.FileProviders.Composite
- [ ] Microsoft.Extensions.Hosting.Abstractions
- [ ] Microsoft.Extensions.Configuration
- [ ] Microsoft.Extensions.Configuration.FileExtensions 
- [ ] Microsoft.Extensions.Configuration.Ini
- [ ] Microsoft.Extensions.Configuration.Json
- [ ] Microsoft.Extensions.Configuration.Xml *(Check first if `System.Security.Cryptography.Xml` nullable enabled)*
- [ ] Microsoft.Extensions.Configuration.CommandLine
- [ ] Microsoft.Extensions.Configuration.Binder *(Check first if `System.ComponentModel.TypeConverter` nullable enabled)*
- [ ] Microsoft.Extensions.Configuration.EnvironmentVariables
- [ ] Microsoft.Extensions.Configuration.UserSecrets

#### Group 3  ####
- [ ] Microsoft.Extensions.Logging
- [ ] Microsoft.Extensions.Http
- [ ] Microsoft.Extensions.Caching.Memory
- [ ] Microsoft.Extensions.Options.DataAnnotation
- [ ] Microsoft.Extensions.Options.ConfigurationExtensions

#### Group 4  ####
- [ ] Microsoft.Extensions.Logging.Configuration
- [ ] Microsoft.Extensions.Logging.EventLog *(Check first if `System.Diagnostics.EventLog` nullable enabled)*
- [ ] Microsoft.Extensions.Logging.EventSource
- [ ] Microsoft.Extensions.Logging.TraceSource *(Check first if `System.Diagnostics.TraceSource` nullable enabled)*
- [ ] Microsoft.Extensions.Logging.Debug

#### Group 5 ####
- [ ] Microsoft.Extensions.Logging.Console
- [ ] Microsoft.Extensions.Hosting

### PR DESCRIPTION
**Pull request by maxkoshevoi**
Fixes https://github.com/dotnet/runtime/issues/43605

~It's not mentioned in 43605, but it exists, so why not?~

### CODE REVIEW

**Comment by eerhardt** [comment]
> It's not mentioned in 43605, but it exists, so why not?

Thanks for calling this out. I've added it and Hosting.WindowsServices to the list.

**Comment by maxkoshevoi** [comment]
Seems like this needs a suppression file

**Comment by eerhardt** [comment]
> Seems like this needs a suppression file

It was just simpler to use a `!` operator here in one place.

**Review by eerhardt — APPROVED** [review]
LGTM

**Pull request merged**
