### PR TITLE
Enable UMOD optimization for x64

### PR DESCRIPTION
**Pull request by TIHan**
**Description**

We added an optimization for GT_UMOD in ARM64. This PR enables the same optimization for x64.

**Acceptance Criteria**
- [x] Passes CI

### CODE REVIEW

**Comment by TIHan** [comment]
@kunalspathak @jakobbotsch This is ready.

This is a trivial change and the diffs look good; though there are not very many of them.

**Comment by kunalspathak** [comment]
>  though there are not very many of them.

Do you know why? I am asking to make sure that we know if these changes are good enough to catch the scenarios or did we miss something.

**Comment by kunalspathak** [comment]
You can probably take some methods that were improved in arm64 work and not in x64 and then compare what make us generate differently?

**Comment by TIHan** [comment]
I think the reason is that this optimization also happens in lowering for x64 where as for ARM64 it does not: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lower.cpp#L5549

**Comment by kunalspathak** [comment]
> I think the reason is that this optimization also happens in lowering for x64 where as for ARM64 it does not: https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/lower.cpp#L5556

So we were covering x64 but just missed few opportunities that we are also covering with this PR. Is that the case? Wonder what prohibited us from covering those scenarios in x64 prior to your PR.

**Comment by TIHan** [comment]
> So we were covering x64 but just missed few opportunities that we are also covering with this PR. Is that the case?

That was my thinking. It's similar to SubMulDiv optimization for 'mod' since that exists in both morph and lowering.

> Wonder what prohibited us from covering those scenarios in x64 prior to your PR.

Probably just low hanging fruit.

**Comment by TIHan** [comment]
@kunalspathak is there anything that needs to be done in this PR?

**Review by kunalspathak — APPROVED** [review]
LGTM. Sorry, I forgot to sign off.

**Comment by TIHan** [comment]
No worries thank you! :)

**Pull request merged**
