### PR TITLE
Change to GetLastPInvokeError where possible

### PR DESCRIPTION
**Pull request by danmoseley**
We added `Marshal.GetLastPInvokeError()` a while back, and made `GetLastWin32Error()` an alias for it, in order to reduce the use of "Win32" in non Windows contexts.

This now uses it whereever it's available. No functional change.

### CODE REVIEW

**Review by stephentoub — COMMENTED** [review]
LGTM _if_ it builds, but I expect it's going to fail... some of these projects target pre-.NET 6, where GetLastPInvokeError was added.

**Comment by danmoseley** [comment]
Hmm, I did "build libs -allconfigurations".. is there more? We will see.

**Comment by danmoseley** [comment]
Oh! Tests too.

**Comment by danmoseley** [comment]
@stephentoub looks like it's going to build - do you want to sign off?

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
