### PR TITLE
Add attribute to support inline namespaces in C++/CLI.

### PR DESCRIPTION
**Pull request by tgani-msft**
A new assembly-scope custom attribute

[CppInlineNamespace(string dottedName)]

has been added to implement inline namespaces in C++/CLI. For every
inline namespace encountered in a translation unit, the C++ compiler
will emit this attribute with the fully scoped name, in CLR dotted
form, as the argument for the attribute.

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
cc: @terrajobst

**Comment by terrajobst** [comment]
@tgani-msft @jkoritzinsky

Please [file an issue](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md) with the proposed API plus some more explanation. Also, it would help to see some C++ sample code to understand what inline namespace is.

**Comment by tgani-msft** [comment]
Filed #783

**Comment by tgani-msft** [comment]
@jkoritzinsky looks like I have to add the attribute class in a reference assembly as well? Where?

**Comment by terrajobst** [comment]
> Filed #783

Thanks. I've added some questions there.

**Comment by tgani-msft** [comment]
@jkoritzinsky I would appreciate help getting this through. I mis-remembered that this had been merged but this is blocked due to failures like this:

.packages\microsoft.dotnet.apicompat\5.0.0-beta.19608.1\build\Microsoft.DotNet.ApiCompat.targets(143,5): error : TypesMustExist : Type 'System.Runtime.CompilerServices.CppInlineNamespaceAttribute' does not exist in the reference but it does exist in the implementation.

Where/how does this need to be fixed? Thanks.

**Comment by jkoritzinsky** [comment]
You'll need to also add a definition of the type in `src\libraries\System.Runtime.CompilerServices.VisualC\src\System\Runtime\CompilerServices\Attributes.cs`

**Comment by tgani-msft** [comment]
@jkoritzinsky I already have that change (actually the only change I have in this PR). I think it also needs to be duplicated somewhere else. I would have assumed that the refs were generated automatically?

**Comment by jkoritzinsky** [comment]
Sorry swap the last src in that path with ref. That’s the file you need to edit.

**Comment by tgani-msft** [comment]
Yes, thanks.

**Review by jkoritzinsky — APPROVED** [review]

**Pull request merged**
