### PR TITLE
Add exclusion paths for coreclr CI builds

### PR DESCRIPTION
**Pull request by safern**
cc: @ViktorHofer @jashook @trylek @jkoritzinsky

### CODE REVIEW

**Review by trylek — APPROVED** [review]
I have one non-blocking question but LGTM overall, thanks for fixing this!

**Review by ViktorHofer — COMMENTED** [review]
We definitely need these changes in pr.yml as well.

**Review by trylek — APPROVED** [review]
Jarret is the expert on include / exclude precedence but to me this still looks good.

**Review by jashook — APPROVED** [review]
I think we probably should delete perf.yml.

**Pull request merged**
