### PR TITLE
Revert "Build an apphost with hostfxr and hostpolicy linked in (#35368)"

### LINKED ISSUE #35967: Installer Build and Test coreclr Linux_musl_x64 Release failing in CI
This job has about 100% failure now with lots of tests failing.

```
CompatibilityCheck_Frameworks 39
RunApp 29
AppWithSameAssemblyAsFramework 25
CompatibilityCheck_Properties 22
MostSpecificRidAssemblySelected 9
MostSpecificRidAssemblySelectedPerType 9
MostSpecificRidNativeLibrarySelected 9
RidSpecificAssembly 9
RidSpecificNativeLibrary 9
RunApp_GetDelegate 7
MostSpecificRidAssemblySelectedPerTypeMultipleAssets 6
AdditionalDepsDontAffectComponentDependencyResolution 1
ComponentWithCorruptedDepsJsonShouldFail 1
ComponentWithDependencies 1
ComponentWithDependenciesAndDependencyRemoved 1
ComponentWithDependenciesAndNoDeps 1
ComponentWithDependenciesAndNoDepsAndDependencyRemoved 1
ComponentWithNoDependencies 1
ComponentWithNoDependenciesAndNoDeps 1
ComponentWithResourcesShouldReportResourceSearchPaths 1
ComponentWithSameDependencyNativeImageShouldFail 1
ComponentWithSameDependencyWithDifferentExtensionShouldFail 1
InvalidMainComponentAssemblyPathFails 1
Microsoft.Extensions.Caching.Memory.Tests Work Item 1
MultiThreadedComponentDependencyResolutionWhichSucceeeds 1
MultiThreadedComponentDependencyResolutionWhithFailures 1
RunApp_UnhandledException 1
```

### PR DESCRIPTION
**Pull request by safern**
This reverts commit f6e5219b13f4bb9d6c1c9f80fd6ca6c594c6c7f8.

This change broke Linux_musl_x64 Release rolling builds. We need to bring pass rate up and has been failing for 2 days without any fix. Usually we try to revert after 1 day.

Fixes: https://github.com/dotnet/runtime/issues/35967

cc: @dotnet/runtime-infrastructure @VSadov @swaroop-sridhar

### CODE REVIEW

**Review by swaroop-sridhar — COMMENTED** [review]
I'd be OK with this -- in order to keep the lab green.

However, @VSadov  @safern  it'd be good to actually verify that the release tests will pass if we revert this change.  I'll start a run now -- unless one of you already checked it. Thanks.

**Comment by swaroop-sridhar** [comment]
CC: @jeffschwMSFT

**Comment by swaroop-sridhar** [comment]
For more details please see: https://github.com/dotnet/runtime/issues/35755

**Comment by safern** [comment]
I queued a rolling build from this branch here: https://dev.azure.com/dnceng/public/_build/results?buildId=635948&view=results

**Comment by VSadov** [comment]
is it possible to run the musli thing on this PR with some azp command?

**Comment by VSadov** [comment]
@safern - Thanks!

**Comment by safern** [comment]
>is it possible to run the musli thing on this PR with some azp command?

No, you have to queue it manually from the UI and then set the branch to: `refs/pull/<pr-id>/merge`

**Comment by safern** [comment]
So the Installer leg in Linux_musl_x64 Release is green in my rolling build with this revert:
https://dev.azure.com/dnceng/public/_build/results?buildId=635948&view=logs&j=bf685d4e-b902-5b69-856e-ae456c52090c

**Pull request merged**
