### PR TITLE
Testmerging jit64

### PR DESCRIPTION
**Pull request by BrianBohe**
This another pr merging JIT tests as https://github.com/dotnet/runtime/pull/81969. It starts with a commit removing args from test entrypoint, and then applies ILTransform with the arguments specified on each commit in the same directory (baseservices/threading). This is [the version of the tool](https://github.com/markples/utils/commit/cefdaff2982bc029bebe5cdb05118e99e38903ad) I used.
Last two commits are a patch on the test merging approach to avoid deduplicating test classes on il tests. These are taken from https://github.com/dotnet/runtime/pull/81969.

### CODE REVIEW

**Comment by BrianBohe** [comment]
Before:
```
Time [secs] | Total | Passed | Failed | Skipped | Assembly Execution Summary
    ============================================================================
        404.212 |   884 |    884 |      0 |       0 | JIT.jit64.XUnitWrapper.dll
    ----------------------------------------------------------------------------
        404.212 |   884 |    884 |      0 |       0 | (total)
```

Now:
```
Time [secs] | Total | Passed | Failed | Skipped | Assembly Execution Summary
============================================================================
    247.204 |   140 |    140 |      0 |       0 | JIT.jit64.jit64_d
     39.049 |   205 |    204 |      1 |       0 | JIT.jit64.jit64_do
    261.956 |   184 |    184 |      0 |       0 | JIT.jit64.jit64_others
    255.325 |   291 |    291 |      0 |       0 | JIT.jit64.jit64_r
    241.254 |   104 |    104 |      0 |       0 | JIT.jit64.jit64_ro
----------------------------------------------------------------------------
   1044.789 |   924 |    923 |      1 |       0 | (total)
```

**Comment by BrianBohe** [comment]
It seems I missed a few cases in issue.targets

**Comment by BrianBohe** [comment]
There were three ilproj renames that needed to be updated in issue.targets. Also, an out of memory exception is being thrown on 373472\\test_il. We have deal with this problem in the past: https://github.com/dotnet/runtime/issues/10002, https://github.com/dotnet/runtime/issues/8661 and https://github.com/dotnet/runtime/issues/56197, and the conclusion was to ommit the test on Windows x86, Windows arm32, unix arm 32 and Arm32 All OS. We may want to add it for wasm now too.

**Review by trylek — APPROVED** [review]
Looks great to me, thanks Brian!

**Comment by JulieLeeMSFT** [comment]
@markples please take care of this PR. Thanks @BrianBohe for working on this.

**Comment by markples** [comment]
@trylek Thanks for approving an earlier iteration of this. I've made a few additional changes that will hopefully be a quick re-review.

- [Match jit64 to recent changes to merged projects and analyzers. Disable a few warnings.](https://github.com/dotnet/runtime/pull/83151/commits/70577c5ac54166159978626fdb1946a9912818f7)
- [Fix xUnit1013 in pri1 tests](https://github.com/dotnet/runtime/pull/83151/commits/b4f138a13e029d832509e26310009b3f923f5deb)
- [Extend IL project renaming to handle _il_do and _il_ro](https://github.com/dotnet/runtime/pull/83151/commits/075bbbdc8c00541da1ca1dde7b05cb7052be1875) plus [fix typo](https://github.com/dotnet/runtime/pull/83151/commits/81c1a7e69503852c9b5d4b41386d2ed735e3a65c)
- [Change arithmetic in an IL test to produce 100 to match the merged wrapper check. Add IL comments while there.](https://github.com/dotnet/runtime/pull/83151/commits/4478cc6bc4679b169b154007d20df84dc69d6a4b)

I also added an unrelated fix. I noticed that Regression's b16102 was testing an empty Main method, so merged test conversion lost its purpose. First [undo the change and use RequiresProcessIsolation and ReferenceXUnitWrapperGenerator](https://github.com/dotnet/runtime/pull/83151/commits/bb83f426ea6e144e02684c36032af750445d9bc0). Then [unconditionally set CLRTestExpectedExitCode in .cmd/.sh wrappers so that the merged wrapper expected value doesn't override embedded tests](https://github.com/dotnet/runtime/pull/83151/commits/92b1190534c324ab311478393d2af562e3d0f39a). I couldn't find anything in dotnet/runtime that appears to depend on the conditional. If this requires discussion, then I can separate it out in order to merge jit64. Thanks!

**Review by markples — APPROVED** [review]

**Comment by markples** [comment]
I've added a review to this since Brian started the work and I reviewed those portions, but I authored the final changes so obviously my review doesn't work for those.

**Review by trylek — APPROVED** [review]
Thanks Mark for finishing Brian's change, your change still looks great to me.

**Pull request merged**
