### PR TITLE
Set name .NET SigHandler

### PR DESCRIPTION
**Pull request by HJLeee**
CI mono llvmaot

### CODE REVIEW

**Comment by danmoseley** [comment]
Errors are "Error while reaping child. errno = 10" which is existing issue

https://github.com/dotnet/runtime/issues/74795

**Comment by HJLeee** [comment]
Thank you for the kind notification. :)

**Comment by danmoseley** [comment]
Is this good to merge? Or was it the code you thought was breaking tests in the other PR?
@jkotas  any feedback on this part?

**Comment by jkotas** [comment]
It looks good to me, but it would be nice to take all thread name changes together in one PR.

**Comment by HJLeee** [comment]
OK. I'll close this and the commit back to https://github.com/dotnet/runtime/pull/75113

**Pull request closed without merging**
