### PR TITLE
[mono][jit] Pass generic context when ldftn of generic method

### PR DESCRIPTION
**Pull request by BrzVlad**
Fixes cases like https://github.com/mono/mono/issues/20962

### CODE REVIEW

**Comment by lambdageek** [comment]
Also fixes https://github.com/mono/mono/issues/20962 (which is the same as https://github.com/mono/mono/issues/20962)

**Review by lambdageek — COMMENTED** [review]
we need something for llvm, too, I think:

https://github.com/dotnet/runtime/blob/906146aba64a9c14bcc77cffa5f540ead31cd4a7/src/mono/mono/mini/jit-icalls.c#L50-L52

**Comment by SamMonoRT** [comment]
Contributes to https://github.com/dotnet/runtime/issues/63548

**Comment by vargaz** [comment]
Looks ok, but the last time I tried this in mono, it broke some other tests.

**Comment by BrzVlad** [comment]
> Looks ok, but the last time I tried this in mono, it broke some other tests.

The original change was https://github.com/mono/mono/pull/20969/files. That change assumed that it needs to pass a rgctx for every indirect call. The problem with it is that it is not true in the case of tailcalls, where the called method is already known and the rgctx is passed as part of the call. OP_TAILCALL uses a MONO_PATCH_INFO_METHOD_JUMP.

Also the jump trampolines used as part of ldftn are not optimal, since no patching is taking place. They always go into the common_call_trampoline. We will probably need something else there at some point.

**Review by lambdageek — APPROVED** [review]

**Comment by SamMonoRT** [comment]
azdo reports an all clean build : https://dev.azure.com/dnceng/public/_build/results?buildId=1668431&view=results

**Pull request merged**
