### PR TITLE
[release/6.0] Port test-only test fixes

### PR DESCRIPTION
**Pull request by danmoseley**
Port test only change to fix CallQueryDosDevice. While I was at it, port some other test only fixes as well, some of which I hit locally.

Discovered yet another EncryptDecrypt failure mode after messing with my settings - ERROR_ENCRYPTION_DISABLED - and skip on that.

### CODE REVIEW

**Comment by eerhardt** [comment]
Can you link to the change / PR in main that you are porting? I'd like to compare.

**Comment by danmoseley** [comment]
https://github.com/dotnet/runtime/pull/59760
https://github.com/dotnet/runtime/pull/63243
part of https://github.com/dotnet/runtime/pull/62559
part of https://github.com/dotnet/runtime/pull/58154

**Comment by eerhardt** [comment]
Looks like some build issues. The first one:

```
src\libraries\System.IO.FileSystem\tests\File\EncryptDecrypt.Windows.cs(21,36): error CS1069: (NETCORE_ENGINEERING_TELEMETRY=Build) The type name 'ServiceController' could not be found in the namespace 'System.ServiceProcess'. This type has been forwarded to assembly 'System.ServiceProcess.ServiceController, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.
```

**Comment by danmoseley** [comment]
Curious I didn't get that locally. Hmm..

**Review by safern — APPROVED** [review]

**Comment by danmoseley** [comment]
@lewing  this one timed out after 1 hour -- seems that "wasm-opt" hung. anything we can collect to diagnose such a thing?
```
emcc : error : '/datadisks/disk1/work/ABF5097B/p/build/emsdk/upstream/bin/wasm-opt --post-emscripten --no-exit-runtime -Oz --low-memory-unused --zero-filled-memory --strip-producers /datadisks/disk1/work/ABF5097B/w/B57209DA/e/wasm_build/obj/wasm/for-build/dotnet.wasm -o /datadisks/disk1/work/ABF5097B/w/B57209DA/e/wasm_build/obj/wasm/for-build/dotnet.wasm -g --mvp-features --enable-mutable-globals' failed (received SIGKILL (-9)) [/datadisks/disk1/work/ABF5097B/w/B57209DA/e/publish/ProxyProjectForAOTOnHelix.proj]
/datadisks/disk1/work/ABF5097B/p/build/wasm/WasmApp.Native.targets(375,5): error MSB3073: The command "emcc "@/datadisks/disk1/work/ABF5097B/p/build/microsoft.netcore.app.runtime.browser-wasm/runtimes/browser-wasm/native/src/emcc-default.rsp" "@/datadisks/disk1/work/ABF5097B/w/B57209DA/e/wasm_build/obj/wasm/for-build/emcc-link.rsp"" exited with code 1. [/datadisks/disk1/work/ABF5097B/w/B57209DA/e/publish/ProxyProjectForAOTOnHelix.proj]
```

**Review by eerhardt — APPROVED** [review]
LGTM

**Comment by danmoseley** [comment]
Linked issues for all failures.

**Pull request merged**
