### PR TITLE
[release/8.0-preview4] Comment out support for mtag extension in libunwind

### PR DESCRIPTION
**Pull request by jkotas**
Fixes https://github.com/dotnet/source-build/issues/3424

## Customer Impact

Break in source build caused by recent upgrade of libunwind from libunwind upstream. The update brought it inline assembly code that does not compile with older compilers.

Comment out the offending code since it is not needed for our libunwind use case.

## Testing

Local build

## Risk

Low. The change is effectively reverting recent change.

### CODE REVIEW

**Comment by jkotas** [comment]
cc @mthalman

**Comment by VSadov** [comment]
Regarding:
> Please reference the commit modifying external source in src/native/external/llvm-libunwind-version.txt.

I assume we will do a similar change in the main and then reference that commit?

@am11

**Review by VSadov — APPROVED** [review]
LGTM Thanks!

**Comment by am11** [comment]
> I assume we will do a similar change in the main and then reference that commit?

We can reference the commit during the forwardport to main branch (makes it easier during the updates).

**Comment by jeffschwMSFT** [comment]
@jkotas @VSadov this is ready to merge.  Please take a look at the CI failures.

**Comment by VSadov** [comment]
It looks like the PR needs rebasing

**Comment by jeffschwMSFT** [comment]
@VSadov thanks for taking a look.  To make Preview 4 we will need to merge today.  Hopefully we will have a green ci by then, but we will need to monitor it.

**Comment by VSadov** [comment]
@jeffschwMSFT   I think the failures were unrelated to the change, since this is a build fix that is specific to nativeaot+arm64+linux, but the PR got behind the base branch and became unmergeable (according to GitHub).  
I've rebased the PR.

I think once NativeAOT builds on linux/arm64, we know that the fix works (there should be no other effects), but it would be better to see green where it can be green.  I'll be watching.

**Comment by mthalman** [comment]
FWIW, I've verified this fix in the pipeline that originally found this issue: [Debian11_Offline_MsftSdk_arm64](https://dev.azure.com/dnceng/internal/_build/results?buildId=2168790&view=logs&j=e61b7abd-894e-5e85-4be3-722f2d80caa2) (internal link). This [build leg was previously failing](https://dev.azure.com/dnceng/internal/_build/results?buildId=2168877&view=logs&j=e61b7abd-894e-5e85-4be3-722f2d80caa2) (internal link) without this change.

**Pull request merged**
