### PR TITLE
[NativeAOT] Reverted the change in IsInstanceOfException

### LINKED ISSUE #90848: JIT test GenericCatchInterfaceProgram fails in Checked NativeAOT
Stack trace:

```
00:15:44.971 Running test: JIT/Generics/Exceptions/GenericCatchInterfaceProgram/GenericCatchInterfaceProgram.dll
Unhandled Exception: System.Diagnostics.DebugProvider+DebugAssertException: IsInstanceOfClass called with interface MethodTable
   at System.Diagnostics.DebugProvider.Fail(String, String) + 0x35
   at System.Diagnostics.Debug.Fail(String, String) + 0x30
   at System.Runtime.TypeCast.IsInstanceOfClass(MethodTable*, Object) + 0x75
   at System.Runtime.EH.FindFirstPassHandler(Object, UInt32, StackFrameIterator&, UInt32&, Byte*&) + 0x108
   at System.Runtime.EH.DispatchEx(StackFrameIterator&, EH.ExInfo&) + 0x13f
   at System.Runtime.EH.RhThrowEx(Object, EH.ExInfo&) + 0x4e
   at GenericCatchInterfaceProgram.Main() + 0x27
   at Program.<<Main>$>g__TestExecutor23|0_24(StreamWriter tempLogSw, StreamWriter statsCsvSw, Program.<>c__DisplayClass0_0&) + 0xa5
   at Program.<Main>$(String[] args) + 0x338
   at JIT!<BaseAddress>+0x477a6c
```

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: https://github.com/dotnet/runtime/issues/90848

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by VSadov** [comment]
Thanks!

**Comment by VSadov** [comment]
My thought on whether we need to backport this is that it is ok to be a 9.0 fix only: 
- This affects a corner case scenario when catch clause is used with irregular types (arrays, interfaces,..). It would require writing IL directly.
- This is an assert-only bug. Everything works correctly in Release.

**Comment by jkotas** [comment]
I agree

**Pull request merged**
