### PR TITLE
[release/8.0][wasm] Define `getWasmIndirectFunctionTable` before initializing the

### PR DESCRIPTION
**Pull request by radical**
.. runtime also, so it is available at that time.

Based on feedback from Katelyn Gadd.

## Customer impact

Ensure that the indirect function table is available when the runtime is being initialized. This is a precautionary measure, and was not breaking any existing tests.

## Testing

Unit tests.

## Risk

Low.

### CODE REVIEW

**Review by pavelsavara — DISMISSED** [review]
Could you please explain the scenarios under which this is necessary ?

**Comment by kg** [comment]
> Could you please explain the scenarios under which this is necessary ?

startup can engage the interpreter, which could under rare circumstances (i.e. if you set low thresholds, disable tiering) engage the jiterpreter which will need these tables

**Comment by radical** [comment]
> Could you please explain the scenarios under which this is necessary ?

Address your suggestion in https://github.com/dotnet/runtime/pull/92664#discussion_r1338325977 . I didn't change `getMemory` though, to match what we have in `main`.

**Comment by radical** [comment]
@kg interestingly removing `getWasmIndirectFunctionTable` after the runtime is initialized, only failed the AOT tests here.

**Comment by radical** [comment]
Failing tests will be fixed by - https://github.com/dotnet/runtime/pull/92747

**Comment by carlossanlop** [comment]
@radical if this is ready, please send an email to Tactics requesting approval (unless you're waiting for @pavelsavara to approve the change first).

**Comment by carlossanlop** [comment]
@radical @kg @pavelsavara  the CI is green after the latest feedback was addressed. When you're ready, please send the email to Tactics requesting approval. And please get a code review sign-off from an area owner.

**Review by pavelsavara — APPROVED** [review]
This is good enough fix for Net8 (because it's low risk), but for Net9 we need better solution (because it's ugly).

**Comment by radical** [comment]
This was not approved for 8.

**Pull request closed without merging**
