### PR TITLE
[mono][aot] Allow valuetype sharing for more sizes.

### PR DESCRIPTION
**Pull request by vargaz**
This happens for Vector256<T>.

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Comment by radekdoulik** [comment]
we see regression around the time this was merged in Normalize ASCII

image

I scheduled more measurements in the range to confirm whether this is the change.

**Comment by vargaz** [comment]
Will check.

**Comment by vargaz** [comment]
Which benchmark shows a slowdown ?

**Comment by radekdoulik** [comment]
> Which benchmark shows a slowdown ?

https://github.com/dotnet/runtime/blob/main/src/mono/sample/wasm/browser-bench/String.cs#L105-L110

**Pull request merged**
