### PR TITLE
Ensure the Equals instance method for the various vector types is correct

### LINKED ISSUE #58853: System.Numerics.Vector2.Equals doesn't use float.Equals in Equals implementation
It is possible to add multiple `new System.Numerics.Vector2(float.NaN, float.NaN)` to a `HashSet<object>`:

image

While it isn't possible to add multiple `float.NaN` because

`float.NaN == float.NaN` is false

`float.NaN.Equals(float.NaN)` is true

This applies to other System.Numeric.* structures as well.

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #58853

### CODE REVIEW

**Review by GrabYourPitchforks — APPROVED** [review]
LGTM. However, I would suggest adding a unit test validating that vectors populated from two _different_ NaN patterns (if such a concept exists) still compare as equal.

Edit: We should also make sure the breaking change doc calls out the _GetHashCode_ changes. Namely, that it's no longer stable.

**Comment by tannergooding** [comment]
> However, I would suggest adding a unit test validating that vectors populated from two different NaN patterns (if such a concept exists) still compare as equal.

Such a concept does exist. There are actually `2^n` (where `n` is `23` for `float` and `52` for `double`) different variations of `NaN`. However, all `NaN` follow the principle of `NaN != NaN` (regardless of `sign` or `payload`) and we are explicitly checking for `x == x` to get the `sign mask`.

This combined with our other NaN tests (throughout the various APIs) should be sufficient coverage of correctness in total.

**Comment by GrabYourPitchforks** [comment]
The suggestion was mainly to ensure that somebody didn't try to be overly clever and "optimize" this code:

```cs
Vector128<T> result = Vector128.Equals(this, other) | ~(Vector128.Equals(this, this) | Vector128.Equals(other, other));
```

To this:

```cs
Vector128<T> result = Vector128.Equals(this, other) | Vector128.Equals(this.AsTSizedInt(), other.AsTSizedInt()).AsT();
```

Your unit tests would still pass even though this code is incorrect.

**Comment by GrabYourPitchforks** [comment]
> I'd hope no one goes touching this code and ignores the comments in place.

I'd hope so to. Ultimately this was just a suggestion, and I think you have better judgment than I do on what people may / may not try here. Perhaps I'm a naturally paranoid person. :)

If you think this is overkill I'll defer to your decision.

**Comment by tannergooding** [comment]
I do think its good to add as an extra safety measure. I just don't want to re-spin CI and block the bug fix from going in on it ;)

**Comment by tannergooding** [comment]
Logged https://github.com/dotnet/runtime/issues/68710 to track said test enhancement

**Comment by dakersnar** [comment]
We're seeing a number of regressions caused by this PR on the 7.0 RC2 vs .NET 6.0 perf report, but we assume they are all by design and expected.

**Pull request merged**
