### PR TITLE
[release/7.0] Install native dependencies on all Apple OS in CI

### PR DESCRIPTION
**Pull request by am11**
Backport of https://github.com/dotnet/runtime/pull/82263.

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by akoeplinger** [comment]
https://github.com/actions/runner-images/pull/7125 was merged which should add pkg-config back, it still needs to roll out as builds still fail as of right now. I'd be in favor of merging this but I'll let @carlossanlop decide.

**Comment by steveisok** [comment]
@carlossanlop are you good with merging this?

**Comment by carlossanlop** [comment]
@mmitche can this get merged now or should we wait until branding?

**Comment by akoeplinger** [comment]
Can we get this in now?

**Pull request merged**
