### PR TITLE
[release/7.0][wasm] Fix broken `dotnet-runtime-perf`

### PR DESCRIPTION
**Pull request by radical**
Build SizeOnDisk, and Startup tools for `net7.0` instead of `net6.0`.

It current fails with:

```
error NU1102: Unable to find package Microsoft.NETCore.App.Ref with version (= 6.0.10)
error NU1102:   - Found 2073 version(s) in dotnet6 [ Nearest version: 6.0.2-servicing.1.22101.5 ]
error NU1102:   - Found 1520 version(s) in dotnet7 [ Nearest version: 7.0.0-alpha.1.21417.28 ]
error NU1102:   - Found 1120 version(s) in dotnet5 [ Nearest version: 6.0.0-alpha.1.20420.3 ]
error NU1102:   - Found 76 version(s) in dotnet3.1 [ Nearest version: 3.1.1-servicing.19602.11 ]
error NU1102:   - Found 52 version(s) in dotnet-public [ Nearest version: 7.0.0-preview.1.22076.8 ]
error NU1102:   - Found 1 version(s) in dotnet-eng [ Nearest version: 5.0.0-alpha.1.19618.1 ]
error NU1102:   - Found 0 version(s) in benchmark-dotnet-prerelease
error NU1102:   - Found 0 version(s) in dotnet-tools
error NU1102:   - Found 0 version(s) in dotnet3.1-transport
error NU1102:   - Found 0 version(s) in dotnet5-transport
```

### CODE REVIEW

**Comment by radical** [comment]
Building on `dotnet-runtime-perf` - `20220910.6`.

**Comment by carlossanlop** [comment]
@lewing @marek-safar can we get a sign off and an approval, respectively?

**Review by LoopedBard3 — APPROVED** [review]
LGTM

**Comment by LoopedBard3** [comment]
Is this also something we should update on the main branch?

**Comment by radical** [comment]
> Is this also something we should update on the main branch?

Yep, and there is a PR for that - https://github.com/dotnet/runtime/pull/75406 .

**Comment by carlossanlop** [comment]
SIgned off. CI failure unrelated. Just noticed it is an infra change only, so no approval needed. Ready to merge. :shipit:

**Pull request merged**
