### PR TITLE
Refactor the generic TensorPrimitives implementation into multiple files.

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Breaks up the `TensorPrimitives.netcore.cs` implementation into multiple files, using roughly one source file per method group.

Contributes to #93286.

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks. Some of these are still enormous, though, in particular TensorPrimitives.T.Operators.cs, and it's only going to get bigger.

Did you consider instead one file per operator?

**Comment by eiriktsarpalis** [comment]
> Did you consider instead one file per operator?

Presumably you mean one file per operator interface? It's possible, and it might also make sense to factor that into a separate class that TP just consumes.

**Comment by eiriktsarpalis** [comment]
The majority of these operator types are trivial or derivates though. We can certainly employ a more fine grained grouping for related ops, but my feeling is that creating one source file per class is probably stretching it.

**Comment by stephentoub** [comment]
> The majority of these operator types are trivial or derivates though.

But many aren't. I'm fine with having a bunch of small files if it means we don't have enormous ones.

We could also put the public APIs that correspond to the operators in the same files as the operators. There are a few cases where that doesn't work as well, where an operator is used in multiple places, but in most places it's 1:1.

We can do whatever, but I'd rather err on the side of one file per operator.  For the most part, you're not looking at other operators when working on a specific one, so having other stuff in the same file is just noise.

**Comment by eiriktsarpalis** [comment]
I've pushed more changes refactoring to roughly one source file per public method group.

**Comment by eiriktsarpalis** [comment]
> What is the "Operators" folder?

It contains all the operator interfaces and related workhorse methods. I thought about calling it `OperatorAbstractions` but this seemed terser.

**Comment by stephentoub** [comment]
> I thought about calling it OperatorAbstractions but this seemed terser.

I think just "Operators" is confusing, because it doesn't actually contain the operators.  Can you rename it to "Abstractions" or "Shared" or "Helpers" or "Runners" or "Workhorses" or "Common" or something along those lines?

**Review by stephentoub — APPROVED** [review]
Other than the naming and formatting comments, LGTM.

**Comment by eiriktsarpalis** [comment]
Renamed "Operators" folder to "Common".

**Pull request merged**
