### PR TITLE
Update CredScanSuppressions.json with new TestData.cs path

### PR DESCRIPTION
**Pull request by akoeplinger**
See https://github.com/dotnet/runtime/issues/104021

### CODE REVIEW

**Review by pavelsavara — APPROVED** [review]

**Comment by akoeplinger** [comment]
/ba-g unblocking code mirroring, this PR can't introduce failures.

**Comment by akoeplinger** [comment]
Looks like this wasn't enough, the push to AzDO is still being blocked.

**Comment by pavelsavara** [comment]
maybe the rules only apply after they are merged

**Comment by akoeplinger** [comment]
I found the reason why it is blocked, talking internally.

**Pull request merged**
