### PR TITLE
Default media type used when 'null' is passed to StringContent #81506

### PR DESCRIPTION
**Pull request by slovely**
This fixes issue #81506

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=81722) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=81722) before we can accept your contribution.<br/><br/>:x: slovely [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=81722)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=81722) it.</sub>

**Comment by wfurt** [comment]
My guess is that it hits  #83110. Offending change was reverted so you can try to rebase from mainline @slovely. That is probably easiest, otherwise we can look at the code dump.

**Comment by slovely** [comment]
@dotnet-policy-service agree

**Review by antonfirsov — APPROVED** [review]
If we backport this, I think this is a sufficient minimal fix to unblock people facing the unintentional breaking change. We should revisit the unintentional nullability changes for .NET 8.0, opened #83423 to track that.

**Pull request merged**
