### PR TITLE
Convert h2inc to a cmake function

### PR DESCRIPTION
**Pull request by am11**

### CODE REVIEW

**Review by jkoritzinsky — COMMENTED** [review]
Could we change the usage of the generated temp file to now use the `preprocess_file` function as well (instead of preprocessing it manually)?

**Comment by am11** [comment]
Test failure is https://github.com/dotnet/runtime/issues/63717.

**Review by jkoritzinsky — APPROVED** [review]

**Comment by EgorBo** [comment]
@am11 could this change possibly cause random build failures like this:
image

when I nuke `artifacts` and rebuild it fixes things for some time

**Comment by am11** [comment]
@EgorBo, interesting, nothing. Does it repro with: clean->build->rebuild or when we change something in the middle?

**Comment by EgorBo** [comment]
> @EgorBo, interesting, nothing jumping out at me. Does it repro with: clean->build->rebuild or when we change something in the middle?

This time I only touched clrjit and INSTALL targets

**Comment by am11** [comment]
`build.cmd -v CoreCLR.sln` on clean repo did not succeed for me with VS2022 due to some unrelated error. So I first ran `build.cmd clr`, then `build.cmd -vs CoreCLR.sln` and `Build Solution`. Made a random modification in importer.cpp and pressed `Build Solution` again., it succeeded. Make another modification in jit/importer.cpp again and this time used `Rebuild Solution` button, that has also succeeded.

Do you use similar steps or I am doing it differently?

**Comment by am11** [comment]
Ok, I was just making sure if your workflow is similar to the one I posted, so I can try to fuzz that up and reproduce the issue. VS workflow can vary from person to person. I’ve followed the one closer to how it is written in repo docs.

**Comment by am11** [comment]
Thanks! I was able to reproduce the issue. It was appending the existing file rather than overwriting it.

https://github.com/dotnet/runtime/pull/65113 has the fix.

**Pull request merged**
