### PR TITLE
[wasm] Upgrade wasm helix VMs to ubuntu 22.04

### LINKED ISSUE #86480: [wasm] Upgrade VMs to Ubuntu 22.04
https://github.com/dotnet/runtime/pull/86194 upgrades all the non-wasm VMs to Ubuntu 22.04 .

What is needed on wasm side to do the same?

https://github.com/dotnet/runtime/blob/29d485c14f1ce5a7358cbed3dd97df725a5bec6d/eng/pipelines/libraries/helix-queues-setup.yml#L182-L192

## dotnet-runtime-perf pipeline
- [x] Update perf pipeline too (thanks to @cincuranet)
- [ ] Update node, and jsvu in all these places (*WIP*)

## runtime pipeline
- [ ] Helix: main wasm queue is still on 18.04
- [ ] Helix: queue used for firefox debugger tests is still on 18.04
- [ ] What is needed for upgrading the build machines we use?
- [ ] Update node, and jsvu in all these places

cc @radekdoulik @maraf

### PR DESCRIPTION
**Pull request by radical**
And revert earlier workarounds for icu tests, as the image now uses *latest* v8. - Ilona Tomkowicz

The v8 version will be pinned to a corresponding version for chrome in a follow up PR.

Fixes https://github.com/dotnet/runtime/issues/86480

### CODE REVIEW

**Comment by radical** [comment]
@ilonatommy There are icu related failures, because of the change in v8 version being used to run the tests. Could you please take a look at them?

**Comment by radical** [comment]
`runtime-wasm-perf` failures can be ignored.

**Review by ilonatommy — APPROVED** [review]

**Review by maraf — APPROVED** [review]

**Pull request merged**
