### PR TITLE
Always write sample events in EventPipe based on sample frequency.

### PR DESCRIPTION
**Pull request by lateralusX**
If no managed frames are located on stack, sample was dropped and not emitted into EventPipe by sample profiler. This cause issues in tooling that try to do thread time calculations based on sample, especially in cases where embedded threads returned to native code during several samples before calling back into runtime. In such scenarios the last sampled event would be prolonged, giving false information that that stack frame lasted much longer than it really did.

Always writing samples into EventPipe will also visualize time an attached thread spend outside of runtime, not running managed code.

Fix should open up for better visualization as described in https://github.com/xamarin/xamarin-android/issues/6243.

We can do similar fix to CoreCLR as well:

https://github.com/dotnet/runtime/blob/db042594240709d61e6e9fc44c0d5b88ccb7a579/src/coreclr/vm/eventing/eventpipe/ep-rt-coreclr.cpp#L117)

but I'm splitting fixes into different PR's since MonoVM's embedding scenario makes this scenario much more likely to occur (already observed in different embedding scenarios) than CoreCLR.

### CODE REVIEW

**Comment by lateralusX** [comment]
//CC @josalem

**Review by josalem — APPROVED** [review]
This is a good step while we rethink some of the semantics of our stackwalker. I wish there was a way to indicate this state without sending sample events, but the Sample Profiler provider doesn't have that capability and I'm not sure it's worth adding at this moment.

CC @brianrob since this will impact PerfView's parsing of stack samples (for the better)

**Comment by lateralusX** [comment]
Perfview will collect these as unmanaged code right below the thread since there is no callstack associated with sample event, so it already handles the case, but It would be good if we could have option in Perfview to exclude events without available callstacks in for example calltree, right now you can exclude UNAMANGED_CODE_TIME, but that will exclude all occurrences, would be good to be able to exclude these occurrences happening when UNAMANGED_CODE_TIME represent a sample event in external code without any callstack.

**Pull request merged**
