### PR TITLE
reset flag to false in preview

### PR DESCRIPTION
**Pull request by Anipik**
The flag needs to be set to avoid release pre release features in previews

### CODE REVIEW

**Comment by ViktorHofer** [comment]
just so that you know, you can retarget a PR against a different branch:

image

**Review by ViktorHofer — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Comment by Anipik** [comment]
> just so that you know, you can retarget a PR against a different branch:

Did u opt into something bcoz i am not still not getting that option

Screen Shot 2020-06-23 at 10 06 11 AM

**Comment by ViktorHofer** [comment]
No, just click the edit button ;)

image

**Comment by Anipik** [comment]
Ah nice :P

**Pull request merged**
