### PR TITLE
Update documentation for analyzing PR failures

### PR DESCRIPTION
**Pull request by jkotas**
Document the recent engineering system improvements

### CODE REVIEW

**Review by davidwrighton — APPROVED** [review]

**Comment by jkotas** [comment]
cc @dotnet/runtime-infrastructure

**Comment by danmoseley** [comment]
cc @markwilkie

**Comment by tommcdon** [comment]
cc @hoyosjs

**Review by hoyosjs — APPROVED** [review]

**Comment by ViktorHofer** [comment]
FYI @danmoseley

**Comment by markwilkie** [comment]
Thanks all!

**Comment by danmoseley** [comment]
I actually didn't know about this known errors format/system. How can we increase awareness? @ViktorHofer maybe including in your next SDK update mail (not sure when that is)?

**Comment by markwilkie** [comment]
There's been some talk too of "advertising" in a PR comment.  Is this something folks are interested in?   (we've been slow to do this kind of thing so we're not SPAMmy)

**Comment by ViktorHofer** [comment]
> @ViktorHofer maybe including in your next SDK update mail (not sure when that is)?

cc @jkoritzinsky @joperezr whoI believe will update the SDK in arcade and runtime soon.

**Comment by danmoseley** [comment]
> There's been some talk too of "advertising" in a PR comment. Is this something folks are interested in? (we've been slow to do this kind of thing so we're not SPAMmy)

Can you do that only for PR's that were merged on red? If so, seems like something worth a trial. "This PR was merged with one or more failing pipelines, but it is not linked to any known failures. Our goal is for all PR's merged with failures to be linked to a known failure. Please see foo.md for information about how to create and link known failures."  or something better ?

**Comment by markwilkie** [comment]
> Can you do that only for PR's that were merged on red?

We could.  Would devs go back and actually look at it?  @tommcdon mentioned too the possibility of advertising the build analysis tab for each failed PR.  (this obviously has the create known issue link too)

Again....not sure what folks want.

**Comment by danmoseley** [comment]
They would see the notification, either for their PR or someone else's. It would be an experiment for a temporary period, and if it was a problem we'd stop it. 
We were recently discussing posting info about pipeline costs when a particularly expensive PR is merged, so it seems reasonable to try

**Comment by hoyosjs** [comment]
There was an issue with this recently and the test log search will be rolling out. After that a how we work talk could be a good forum for this.

**Pull request merged**
