### PR TITLE
Naming policies are applied to [Flags] enum values by JsonStringEnumConverter

### PR DESCRIPTION
**Pull request by illialarka**
Add logic for converting ```[Flags]``` enums to a string using ```JsonStringEnumConverter``` with naming policy.
Fixed issue #31622 

The problem was that ```JsonStringEnumConverter``` just converts the enum to string as-is. The naming policy was applied to the beginning of the original value.

```csharp
FileAttributes enumCombinedValue = FileAttributes.Hidden | FileAttributes.Device;
var stringEnumValue = enumCombinedValue.ToString(); // Hidden, Device
JsonNamingPolicy namingPolicy = JsonNamingPolicy.CamelCase;
var transformedEnumValue = namingPolic.ConvertName(stringEnumValue); // hidden, Device
```
Added logic to convert a combined enumeration to a string. To do this, you need to know all the values of the enum. 
Added a cache for enum information.
The flow with enum information possible only for flag enum.

### CODE REVIEW

**Review by layomia — CHANGES_REQUESTED** [review]
Thanks for the PR!

A simple implementation where we parse the individual flag values from the result of `value.ToString()`, apply the naming policy on each, and stitch them back together is significantly faster and has less allocs than this reflection based approach:

|               Method |            enumValue |        Mean |      Error |     StdDev |      Median | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------------------- |--------------------- |------------:|-----------:|-----------:|------------:|------:|-------:|------:|------:|----------:|
|  BuildWithReflection |           Compressed | 4,775.43 ns |  72.184 ns |  67.521 ns | 4,755.75 ns | 1.000 | 0.3052 |     - |     - |    1307 B |
| ReformatEnumToString |           Compressed |    25.58 ns |   0.358 ns |   0.318 ns |    25.46 ns | 0.005 | 0.0076 |     - |     - |      32 B |
|                      |                      |             |            |            |             |       |        |       |       |           |
|  BuildWithReflection | Direc(...)tream [38] | 4,968.75 ns |  26.770 ns |  22.354 ns | 4,967.59 ns |  1.00 | 0.3967 |     - |     - |    1668 B |
| ReformatEnumToString | Direc(...)tream [38] |   197.84 ns |   3.448 ns |   3.690 ns |   196.72 ns |  0.04 | 0.0956 |     - |     - |     400 B |
|                      |                      |             |            |            |             |       |        |       |       |           |
|  BuildWithReflection |  Read(...)Data [100] | 6,064.24 ns | 121.986 ns | 342.061 ns | 5,927.36 ns |  1.00 | 0.6104 |     - |     - |    2574 B |
| ReformatEnumToString |  Read(...)Data [100] |   587.48 ns |  10.970 ns |  13.874 ns |   582.10 ns |  0.09 | 0.2575 |     - |     - |    1080 B |

**Let's simplify the code here** and we can investigate optimizing the naive code further by maybe [utilizing the shared arraypool](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.arraypool-1.rent?view=netcore-3.1) & parsing/stitching the flag values by hand rather than calling `string.Split` and `string.Join`. This can either be in this PR or we can file an issue to address this later.

Here's the benchmark I ran + the simplified logic:

```csharp
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;
using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;

namespace EnumFlagNamingPolicy
{
    [MemoryDiagnoser]
    public class Benchmark
    {
        [Params(
            FileAttributes.Compressed,
            FileAttributes.Directory | FileAttributes.Compressed | FileAttributes.IntegrityStream,
            FileAttributes.Hidden | FileAttributes.Normal | FileAttributes.ReadOnly | FileAttributes.NoScrubData |FileAttributes.SparseFile |
            FileAttributes.Archive | FileAttributes.Encrypted | FileAttributes.Compressed | FileAttributes.NotContentIndexed
            )]
        public FileAttributes enumValue;

        private string enumAsStr;

        private static readonly JsonNamingPolicy s_namingPolicy = JsonNamingPolicy.CamelCase;

        private const string _commaSeparator = ", ";

        [GlobalSetup]
        public void Setup()
        {
            // Both algorithms have access to this value.
            enumAsStr = enumValue.ToString();
        }

        [Benchmark(Baseline = true)]
        public string BuildWithReflection()
        {
            string ConvertEnum(EnumInformation enumInformation, FileAttributes value)
            {
                int index = enumInformation.Names.Length - 1;
                ulong copyEnumValue = Unsafe.As<FileAttributes, ulong>(ref value);
                StringBuilder valueBuilder = new StringBuilder();
                bool firstOccurrence = true;

                while (index >= 0)
                {
                    if (index == 0 && enumInformation.Values[index] == 0)
                    {
                        break;
                    }

                    if ((copyEnumValue & enumInformation.Values[index]) == enumInformation.Values[index])
                    {
                        copyEnumValue -= enumInformation.Values[index];

                        if (!firstOccurrence)
                        {
                            valueBuilder.Insert(0, _commaSeparator);
                        }

                        string transformed = s_namingPolicy.ConvertName(enumInformation.Names[index]);
                        valueBuilder.Insert(0, transformed);
                        firstOccurrence = false;
                    }

                    index--;
                }
                return valueBuilder.ToString();
            }

            Type enumType = typeof(FileAttributes);
            string[] enumAllNames = Enum.GetNames(enumType);
            ulong[] enumAllValues = new ulong[enumAllNames.Length];

            for (int i = 0; i < enumAllNames.Length; i++)
            {
                FieldInfo fieldInfo = enumType.GetField(
                    enumAllNames[i],
                    BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Static)!;
                enumAllValues[i] = Convert.ToUInt64(fieldInfo.GetValue(null));
            }

            EnumInformation enumInformation = new EnumInformation(enumAllValues, enumAllNames);

            return ConvertEnum(enumInformation, enumValue);
        }

        [Benchmark]
        public string ReformatEnumToString()
        {
            string[] enumValues = enumAsStr.Split(", ");

            for (int i = 0; i < enumValues.Length; i++)
            {
                enumValues[i] = s_namingPolicy.ConvertName(enumValues[i]);
            }

            return string.Join(", ", enumValues);
        }
    }

    internal class EnumInformation
    {
        public EnumInformation(ulong[] values, string[] names)
        {
            Values = values;
            Names = names;
        }

        public ulong[] Values;
        public string[] Names;
    }

    public class Program
    {
        static void Main(string[] args) => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);
    }
}
```

**Comment by illialarka** [comment]
@layomia Thank you for the explanation and the polite answer. I will conduct an investigation and fix PR as soon as possible.

**Comment by layomia** [comment]
@illialarka, we'd like to get this in soon - are you able to take another look?

**Comment by illialarka** [comment]
> @illialarka, we'd like to get this in soon - are you able to take another look?

Hi 👋
I faced a problem with my laptop, it is broken, now I have access to a workstation only. I should have warned you about this. Sorry for the late reply.  I will close this request.

**Pull request closed without merging**
