### PR TITLE
Make ILBlittablePtrMarshaler participate in marshaller inheritance

### LINKED ISSUE #39357: Marshalling differences between 3.1 and 5.0 for classes
Simplified repro from https://github.com/ControlzEx/ControlzEx/issues/120

```csharp
using System;
using System.Runtime.InteropServices;

sealed class Program
{
    [StructLayout(LayoutKind.Sequential)]
    public struct RECT
    {
        public int left;
        public int top;
        public int right;
        public int bottom;
    }

    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]
    public class MONITORINFO
    {
        public int cbSize = Marshal.SizeOf(typeof(MONITORINFO));
        public RECT rcMonitor = new RECT();
        public RECT rcWork = new RECT();
        public int dwFlags = 0;
    }

    [DllImport("user32", EntryPoint = "GetMonitorInfoW", ExactSpelling = true, CharSet = CharSet.Unicode)]
    [return: MarshalAs(UnmanagedType.Bool)]
    internal static extern bool GetMonitorInfo([In] IntPtr hMonitor, [Out] MONITORINFO lpmi);

    [DllImport("user32")]
    internal static extern IntPtr MonitorFromWindow([In] IntPtr handle, uint flags);

    static void Main()
    {
        IntPtr primaryMonitorHandle = MonitorFromWindow((IntPtr)0, 0x1U);

        MONITORINFO mi = new MONITORINFO();
        GetMonitorInfo(primaryMonitorHandle, mi);

        Console.WriteLine($"rcMonitor: {mi.rcMonitor.right}*{mi.rcMonitor.bottom}");
        Console.WriteLine($"rcWork: {mi.rcMonitor.right}*{mi.rcMonitor.bottom}");
    }
}
```
Output for `netcoreapp3.1`:
```
rcMonitor: 1920*1080
rcWork: 1920*1080
```
Output for `net5.0` (latest public preview):
```
rcMonitor: 0*0
rcWork: 0*0
```
If I change `MONITORINFO` to `struct` - it'll work fine on both.

/cc @punker76

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #39357 

/cc @jkoritzinsky @elinor-fung

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jkotas** [comment]
Do we need a test?

**Comment by AaronRobinsonMSFT** [comment]
> Do we need a test?

Yes, I am working on that. Wanted to start the CI and make sure the approach was correct on platforms in parallel.

**Comment by AaronRobinsonMSFT** [comment]
Failing tests are from https://github.com/dotnet/runtime/issues/39404

**Comment by AaronRobinsonMSFT** [comment]
No changes to mono runtime so skipping the iOS x86 mono leg.

**Pull request merged**
