### PR TITLE
NativeAOT/linux/arm: Fix native linux/arm failure

### LINKED ISSUE #102715: ILC: Assertion failed '(unsigned)reg < ArrLen(regMasks)' in '...' during 'Generate code' (IL size 6; hash 0x04901a61; FullOpts)
Native AOT ARM32 Linux outerloop runs are on the floor due to hitting asserts in RyuJIT: https://dev.azure.com/dnceng-public/public/_build/results?buildId=687421&view=results

This regression was introduced in #102592 (the outerloop run at the commit right before the PR was clean).

### PR DESCRIPTION
**Pull request by kunalspathak**
Fix a bug introduced in https://github.com/dotnet/runtime/pull/102592

Fixes: https://github.com/dotnet/runtime/issues/102715

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by kunalspathak** [comment]
The failure in outerloop arm leg seems to be pre-existing before https://github.com/dotnet/runtime/pull/102592

https://dev.azure.com/dnceng-public/public/_build/results?buildId=687088&view=results

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Review by jakobbotsch — APPROVED** [review]

**Comment by kunalspathak** [comment]
/ba-g failure seems to be https://github.com/dotnet/runtime/pull/102592. superpmi failures are timeout and https://github.com/dotnet/runtime/issues/102773

**Pull request merged**
