### PR TITLE
Remove usused rd.xml files

### LINKED ISSUE #51112: Remove usused rd.xml files
There are many rd.xml that are not needed and could be removed. The ones which might still be used are in OOB libraries.

```
./System.Dynamic.Runtime/tests/Resources/System.Dynamic.Runtime.Tests.rd.xml
./System.IO.FileSystem/tests/Resources/System.IO.FileSystem.Tests.rd.xml
./Microsoft.Win32.Primitives/tests/Resources/Microsoft.Win32.Primitives.Tests.rd.xml
./Microsoft.CSharp/src/Resources/Microsoft.CSharp.rd.xml
./System.Linq.Queryable/tests/Resources/System.Linq.Queryable.Tests.rd.xml
./System.ComponentModel.Annotations/src/Resources/System.ComponentModel.Annotations.rd.xml
./System.Text.Encodings.Web/tests/Resources/System.Text.Encodings.Web.Tests.rd.xml
./System.Transactions.Local/tests/Resources/System.Transactions.Local.Tests.rd.xml
./System.Runtime/tests/Resources/System.Runtime.Tests.rd.xml
./System.Globalization.Extensions/tests/Resources/System.Globalization.Extensions.Tests.rd.xml
./System.Configuration.ConfigurationManager/src/Resources/System.Configuration.ConfigurationManager.rd.xml
./System.IO/tests/Resources/System.IO.Tests.rd.xml
./System.Linq.Expressions/src/Resources/System.Linq.Expressions.rd.xml
./System.Runtime.Serialization.Primitives/src/Resources/System.Runtime.Serialization.Primitives.rd.xml
./System.Security.Cryptography.Xml/src/Resources/System.Security.Cryptography.Xml.rd.xml
./System.Diagnostics.Tracing/tests/Resources/System.Diagnostics.Tracing.Tests.rd.xml
./System.Data.Common/tests/Resources/System.Data.Common.Tests.rd.xml
./System.Data.Common/src/Resources/System.Data.Common.rd.xml
./System.Private.Uri/src/Resources/System.Private.Uri.rd.xml
./System.Runtime.Serialization.Json/tests/ReflectionOnly/Resources/System.Runtime.Serialization.Json.ReflectionOnly.Tests.rd.xml
./System.Security.AccessControl/tests/Resources/System.Security.AccessControl.Tests.rd.xml
./System.Security.Cryptography.Cng/tests/Resources/System.Security.Cryptography.Cng.Tests.rd.xml
./System.Runtime.Serialization.Xml/tests/Resources/System.Runtime.Serialization.Xml.Tests.rd.xml
./System.Runtime.Serialization.Xml/tests/ReflectionOnly/Resources/System.Runtime.Serialization.Xml.ReflectionOnly.Tests.rd.xml
./Microsoft.VisualBasic.Core/tests/Resources/Microsoft.VisualBasic.Core.Tests.rd.xml
./System.Collections.Specialized/tests/Resources/System.Collections.Specialized.Tests.rd.xml
./System.Security.Cryptography.Algorithms/tests/Resources/System.Security.Cryptography.Algorithms.Tests.rd.xml
./System.ComponentModel.TypeConverter/src/Resources/System.ComponentModel.TypeConverter.rd.xml
./System.Collections.Immutable/tests/Resources/System.Collections.Immutable.Tests.rd.xml
./System.Memory/tests/Resources/System.Memory.Tests.rd.xml
./System.Net.HttpListener/tests/Resources/System.Net.HttpListener.Tests.rd.xml
./System.Collections/tests/Resources/System.Collections.Tests.rd.xml
./System.Globalization.Calendars/tests/Resources/System.Globalization.Calendars.Tests.rd.xml
./System.Runtime.Serialization.Formatters/tests/BinaryFormatterTests.rd.xml
./System.Runtime.Serialization.Formatters/src/Resources/System.Runtime.Serialization.Formatters.rd.xml
./System.Net.Sockets/tests/FunctionalTests/Resources/System.Net.Sockets.Tests.rd.xml
./System.Security.Permissions/tests/Resources/System.Security.Permissions.Tests.rd.xml
./System.Private.DataContractSerialization/src/Resources/System.Private.DataContractSerialization.rd.xml
./System.Linq/tests/Resources/System.Linq.Tests.rd.xml
./System.Private.Xml.Linq/tests/events/Resources/System.Xml.Linq.Events.Tests.rd.xml
./System.Private.Xml/tests/XmlSerializer/Resources/System.Xml.XmlSerializer.Tests.rd.xml
./System.Private.Xml/tests/XmlSerializer/ReflectionOnly/Resources/System.Xml.XmlSerializer.ReflectionOnly.Tests.rd.xml
./System.Private.Xml/src/Resources/System.Private.Xml.rd.xml
./System.Net.Primitives/tests/FunctionalTests/Resources/System.Net.Primitives.Functional.Tests.rd.xml
./System.Net.Primitives/src/Resources/System.Net.Primitives.rd.xml
```

### PR DESCRIPTION
**Pull request by kant2002**
Closes #51112

### CODE REVIEW

**Comment by danmoseley** [comment]
@eerhardt can you confirm these are all dead? I assume so and I'm surprised we didn't delete them way back.

**Comment by eerhardt** [comment]
The ILLinker doesn't read these files at all. The only thing I'm aware of that reads them is the UWP tooling, which we've removed support for in this repo.

cc @MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
Yup. These might have been useful for OOB assemblies since .NET Native devs can reference NuGet packages with these, but the support for embedding the RD.XML was pulled out in 2019 along will all the .NET Native testing. They're dead since. If we were testing with .NET Native like we test with .NET Framework these would be useful but we don't do that.

**Review by eerhardt — APPROVED** [review]
LGTM. Thanks for the help, @kant2002!

**Pull request merged**
