### PR TITLE
Use bidirectional marshallers for elements.

### LINKED ISSUE #89893: [ComInterfaceGenerator] PreserveSig with collection return type will not properly marshal back to caller
This is probably not a realistic situation, but we may want to fix it or warn when the [PreserveSig] return value unmarshaller doesn't take an int as the unmanaged type.

This method definition
```C#
        [PreserveSig]
        [return: MarshalUsing(CountElementName = nameof(size))]
        StatelessCollection<StatelessType> ReturnPreserveSig(int size);

```
will generate this unmanaged to managed method
```C#
    internal static global::SharedTypes.ComInterfaces.NativeCollection<global::SharedTypes.ComInterfaces.StatelessType> ABI_ReturnPreserveSig(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int size)
    {
        global::SharedTypes.ComInterfaces.IStatelessCollectionStatelessElement @this = default;
        global::SharedTypes.ComInterfaces.StatelessCollection<global::SharedTypes.ComInterfaces.StatelessType> __retVal = default;
        global::SharedTypes.ComInterfaces.NativeCollection<global::SharedTypes.ComInterfaces.StatelessType> __retVal_native = default;
        // Setup - Perform required setup.
        int __retVal_native__numElements;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out __retVal_native__numElements);
        try
        {
            // Unmarshal - Convert native data to managed data.
            @this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::SharedTypes.ComInterfaces.IStatelessCollectionStatelessElement>(__this_native);
            __retVal = @this.ReturnPreserveSig(size);
            // Marshal - Convert managed data to native data.
            __retVal_native = global::SharedTypes.ComInterfaces.StatelessCollectionMarshaller<global::SharedTypes.ComInterfaces.StatelessType, nint>.ManagedToUnmanaged.AllocateContainerForUnmanagedElements(__retVal, out __retVal_native__numElements);
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.StatelessType> __retVal_native__managedSpan = global::SharedTypes.ComInterfaces.StatelessCollectionMarshaller<global::SharedTypes.ComInterfaces.StatelessType, nint>.ManagedToUnmanaged.GetManagedValuesSource(__retVal);
                System.Span<nint> __retVal_native__nativeSpan = global::SharedTypes.ComInterfaces.StatelessCollectionMarshaller<global::SharedTypes.ComInterfaces.StatelessType, nint>.ManagedToUnmanaged.GetUnmanagedValuesDestination(__retVal_native, __retVal_native__numElements);
                __retVal_native__nativeSpan.Clear();
                ; // Should be a for loop here that marshals elements
            }
        }
        catch (System.Exception __exception)
        {
            __retVal_native = System.Runtime.InteropServices.Marshalling.ExceptionAsDefaultMarshaller<global::SharedTypes.ComInterfaces.NativeCollection<global::SharedTypes.ComInterfaces.StatelessType>>.ConvertToUnmanaged(__exception);
        }

        return __retVal_native;
    }
```

For comparison, a regular managed return value

```C#
        [return: MarshalUsing(CountElementName = nameof(size))]
        StatelessCollection<StatelessType> Return(int size);
```

Generates this unmanaged to managed stub

```C#
    internal static int ABI_Return(System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch* __this_native, int size, global::SharedTypes.ComInterfaces.NativeCollection<global::SharedTypes.ComInterfaces.StatelessType>* __invokeRetValUnmanaged__param)
    {
        global::SharedTypes.ComInterfaces.IStatelessCollectionStatelessElement @this = default;
        ref global::SharedTypes.ComInterfaces.NativeCollection<global::SharedTypes.ComInterfaces.StatelessType> __invokeRetValUnmanaged = ref *__invokeRetValUnmanaged__param;
        global::SharedTypes.ComInterfaces.StatelessCollection<global::SharedTypes.ComInterfaces.StatelessType> __invokeRetVal = default;
        int __retVal = default;
        // Setup - Perform required setup.
        int __invokeRetValUnmanaged__numElements;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out __invokeRetValUnmanaged__numElements);
        try
        {
            // Unmarshal - Convert native data to managed data.
            __retVal = 0; // S_OK
            @this = System.Runtime.InteropServices.ComWrappers.ComInterfaceDispatch.GetInstance<global::SharedTypes.ComInterfaces.IStatelessCollectionStatelessElement>(__this_native);
            __invokeRetVal = @this.Return(size);
            // Marshal - Convert managed data to native data.
            __invokeRetValUnmanaged = global::SharedTypes.ComInterfaces.StatelessCollectionMarshaller<global::SharedTypes.ComInterfaces.StatelessType, nint>.ManagedToUnmanaged.AllocateContainerForUnmanagedElements(__invokeRetVal, out __invokeRetValUnmanaged__numElements);
            {
                System.ReadOnlySpan<global::SharedTypes.ComInterfaces.StatelessType> __invokeRetValUnmanaged__managedSpan = global::SharedTypes.ComInterfaces.StatelessCollectionMarshaller<global::SharedTypes.ComInterfaces.StatelessType, nint>.ManagedToUnmanaged.GetManagedValuesSource(__invokeRetVal);
                System.Span<nint> __invokeRetValUnmanaged__nativeSpan = global::SharedTypes.ComInterfaces.StatelessCollectionMarshaller<global::SharedTypes.ComInterfaces.StatelessType, nint>.ManagedToUnmanaged.GetUnmanagedValuesDestination(__invokeRetValUnmanaged, __invokeRetValUnmanaged__numElements);
                __invokeRetValUnmanaged__nativeSpan.Clear();
                for (int __i0 = 0; __i0 < __invokeRetValUnmanaged__managedSpan.Length; ++__i0)
                {
                    __invokeRetValUnmanaged__nativeSpan[__i0] = global::SharedTypes.ComInterfaces.StatelessTypeMarshaller.ManagedToUnmanaged.ConvertToUnmanaged(__invokeRetValUnmanaged__managedSpan[__i0]);
                }
            }
        }
        catch (System.Exception __exception)
        {
            __retVal = System.Runtime.InteropServices.Marshalling.ExceptionAsHResultMarshaller<int>.ConvertToUnmanaged(__exception);
        }

        return __retVal;
    }

```

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #89893

Also updates the analyzer to require the element shapes to be bidirectional in all cases.

Technically this is a source-breaking change in the analyzer, but since it can be suppressed like all analyzers, I'm not sure if we need to fill out a breaking-change form.

### CODE REVIEW

**Review by jtschuster — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
I've figured out a way to limit the breaking change to cases where the user explicitly specifies the `ElementIn`, `ElementRef`, or `ElementOut` marshal modes. I think those cases will be rare enough that merging this in this late in the release may be okay.

I found one user outside of dotnet/runtime and dotnet/samples that uses the Element marshaller modes specifically: https://grep.app/search?q=MarshalMode.Element.

If we're not sure, we can also merge this into .NET 9 as soon as we branch.

@AaronRobinsonMSFT @elinor-fung what do you think?

**Comment by AaronRobinsonMSFT** [comment]
> I found one user outside of dotnet/runtime and dotnet/samples that uses the Element marshaller modes specifically: https://grep.app/search?q=MarshalMode.Element.

That looks like a rather popular library. How impactful will this be to them?

**Comment by jkoritzinsky** [comment]
They should be able to change the marshaller that they're using to the stateless marshaller that they already have for the ElementRef case.

I can also try to make the errors into warnings for the Element modes (like we do with the Default mode) to reduce the impact further.

**Comment by lambdageek** [comment]
@jkoritzinsky I'm seeing

```
##[error]src/libraries/System.Runtime.InteropServices/tests/TestAssets/SharedTypes/ComInterfaces/IStatelessPinnableCollectionBlittableElements.cs(53,92): error SYSLIB1057: (NETCORE_ENGINEERING_TELEMETRY=Build) The type 'SharedTypes.ComInterfaces.StatelessPinnableCollectionMarshaller<T, TUnmanagedElement>.ManagedToUnmanaged' specifies that it supports the 'ElementIn' marshal mode for 'SharedTypes.ComInterfaces.StatelessPinnableCollection<T>' but does not provide a two-parameter 'AllocateContainerForManagedElements' method that takes the unmanaged type as the first parameter and an 'int' as the second parameter
```

from Linux and Windows libraries builds on my PR (#90166)

**Comment by jtschuster** [comment]
@lambdageek I think I merged a PR with a new test type that this PR warns on between when this passed CI and when it was merged. I'll get a fix out, thanks for the head up!

**Pull request merged**
