### PR TITLE
Add RIDs for macOS 13

### PR DESCRIPTION
**Pull request by filipnavara**

### CODE REVIEW

**Review by am11 — COMMENTED** [review]
Looks good. Please run `dotnet build src/libraries/Microsoft.NETCore.Platforms -p:UpdateRuntimeFiles=true` task which sorts the RID graph values.

**Comment by filipnavara** [comment]
> Looks good. Please run `dotnet build src/libraries/Microsoft.NETCore.Platforms -p:UpdateRuntimeFiles=true` task which sorts the RID graph values.

Haha. That would have saved me some manual edits if I did it in the first place... Turns out I made cut and paste error though.

**Comment by jkotas** [comment]
@danmoseley I assume that we want to take this change for .NET 7. Have we done any scouting on macOS 13? It will releases in October.

**Comment by wfurt** [comment]
I have VM and I was planning to run tests when I get some more time. Probably next week @jkotas

**Review by jkotas — APPROVED** [review]

**Pull request merged**
