### PR TITLE
Fix the reverse of genCodeForJumpCompare for LoongArch64 and RISCV64.

### PR DESCRIPTION
**Pull request by shushanhf**
This PR is part of the issue https://github.com/dotnet/runtime/issues/69705 to amend the LA's port.

Fix the reverse of genCodeForJumpCompare for LoongArch64 and RISCV64.

### CODE REVIEW

**Comment by shushanhf** [comment]
Hi, @jakobbotsch 
Could you please review this PR?

**Comment by clamp03** [comment]
> As I don't have RISCV64, I think this PR is value for RISCV64.

@shushanhf Thank you very much. It is valuable for RISC-V as well.  Actually, just *CC me* would have been a big help to me. I'd just like to ask you (if you don't mind) to add RISC-V such simple fixes to as https://github.com/dotnet/runtime/pull/85216 from next time. I really appreciate your work.
I know you don't have to test patches on RISC-V at all. Just include me in the patch. I will!!!
In fact, I cannot even imagine starting the RISC-V port without your work. Thanks again.

**Review by clamp03 — APPROVED** [review]

**Comment by shushanhf** [comment]
> > As I don't have RISCV64, I think this PR is value for RISCV64.
> 
> @shushanhf Thank you very much. It is valuable for RISC-V as well. Actually, just _CC me_ would have been a big help to me. I'd just like to ask you (if you don't mind) to add RISC-V such simple fixes to as #85216 from next time. I really appreciate your work. I know you don't have to test patches on RISC-V at all. Just include me in the patch. I will!!! In fact, I cannot even imagine starting the RISC-V port without your work. Thanks again.

I didn't modify the RISC-V at some time just because I can‘t test RISC-V liking the LoongArch64.

**Comment by shushanhf** [comment]
As #85242 refactor

**Pull request closed without merging**
