### PR TITLE
Vectorize interface casts

### PR DESCRIPTION
**Pull request by benaadams**
For the unrolled loop there are currently 8 conditional jumps for 4 checks
```asm
G_M54280_IG04:
    cmp      qword ptr [r9+8*r10], rcx
    je       SHORT G_M54280_IG06
    dec      r8
    test     r8, r8
    je       SHORT G_M54280_IG05
    cmp      qword ptr [r9+8*r10+8], rcx
    je       SHORT G_M54280_IG06
    dec      r8
    test     r8, r8
    je       SHORT G_M54280_IG05
    cmp      qword ptr [r9+8*r10+16], rcx
    je       SHORT G_M54280_IG06
    dec      r8
    test     r8, r8
    je       SHORT G_M54280_IG05
    cmp      qword ptr [r9+8*r10+24], rcx
    je       SHORT G_M54280_IG06
    dec      r8
    test     r8, r8
    je       SHORT G_M54280_IG05
    add      r10, 4
    jmp      SHORT G_M54280_IG04
```
The vectorized path changes it to 2 per 4 checks
```asm
G_M8434_IG04:
    mov      rsi, r9
    vmovupd  xmm1, xmmword ptr [rsi+r10]
    mov      rsi, r9
    lea      rdi, [r10+16]
    vmovupd  xmm2, xmmword ptr [rsi+rdi]
    vpcmpeqq xmm1, xmm1, xmm0
    vpcmpeqq xmm2, xmm2, xmm0
    vpor     xmm1, xmm1, xmm2
    vpmovmskb esi, xmm1
    test     esi, esi
    jne      SHORT G_M8434_IG09
    add      r10, 32
    cmp      r10, r11
    jb       SHORT G_M8434_IG04
```
And non-vectorized path to 5 per 4 checks
```asm
G_M8434_IG04:
    cmp      qword ptr [rdi+8*rbx], rcx
    je       SHORT G_M8434_IG09
    cmp      qword ptr [rdi+8*rbx+8], rcx
    je       SHORT G_M8434_IG09
    cmp      qword ptr [rdi+8*rbx+16], rcx
    je       SHORT G_M8434_IG09
    cmp      qword ptr [rdi+8*rbx+24], rcx
    je       SHORT G_M8434_IG09
    add      rbx, 4
    cmp      rbx, rax
    ja       SHORT G_M8434_IG04
```

/cc @VSadov @jkotas

### CODE REVIEW

**Comment by VSadov** [comment]
I tried vectorizing this too. It was a mild win on long lookups and loss on short ones. Short lookups, when matching interface is found in 1-4 checks is very common, since most interface lists are short and in perf-critical cases sorted by likelihood of casts.

Your approach is a bit different, so I wonder how perf looks like?

**Comment by benaadams** [comment]
I was interested in this method as it was showing up as very significant; for PlatformBenchmarks etc

image

It also had a number of issues, including branch issues:

image


While the vectorisation seems fine Block 48/51 (have issue with pdb and VTune); the biggest hit of this method looks to be getting `InterfaceCount` from the method table; which looking back was also an issue:

image

Significantly its on simple `mov` instructions looks to be due to a high Cache and TLB-miss rate; which is problematic. 

At a guess it's due to the method being called on ThreadPool on a woken up thread with cleared caches as part of timing attack mitigations. Not sure there is much that can be done about the instruction cache misses; however could the method table be prefetched in someway? (e.g. in `ThreadPoolWorkQueue.Dispatch`)

Not sure how to approach it...

**Comment by VSadov** [comment]
Another thing to consider is that interface scan has roughly linear cost (ignoring cache line effects) while cast cache lookup is roughly constant. Cache becomes faster than scan at about 6-8 interface compares.

If we could know beforehand that lookup will go through many interfaces, just using cache would be a win. Perhaps we can assume that for types with really long interface count? 
I did not have a real-world case to experiment with such approach. It looks like we have one here.

**Comment by benaadams** [comment]
Does seem to mostly be called from the Dispatch loop; so the cleared TLB/Cache would seem to fit the issue seen in https://github.com/dotnet/runtime/pull/35468#issuecomment-619560661?

image


/cc @stephentoub

**Comment by benaadams** [comment]
Benchmarking says it needs work... 😢

**Comment by benaadams** [comment]
Is proving quite hard...

> while cast cache lookup is roughly constant. 

How large is the cache? Is it a single shared static or per site?

`Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection<TContext>` is one to look at for many interfaces that are also used.

**Pull request closed without merging**
