### PR TITLE
Update NotNullIfNotNullAttribute XML documentation

### PR DESCRIPTION
**Pull request by ghost**
dotnet/dotnet-api-docs PR as well: dotnet/dotnet-api-docs#9527

### CODE REVIEW

**Comment by stephentoub** [comment]
Why is this change appropriate? It's making a distinction between the input and output value, eg if a parameter is marked with this, is the parameter not-null upon entrance to the method, or is the correspomding argument not-null upon exit from the method?

**Comment by joegoldman2** [comment]
> Why is this change appropriate? It's making a distinction between the input and output value, eg if a parameter is marked with this, is the parameter not-null upon entrance to the method, or is the correspomding argument not-null upon exit from the method?

Can you please check https://github.com/dotnet/runtime/pull/93750?

**Comment by stephentoub** [comment]
Thanks. I see that PR. It doesn't explain why the change improves things. Can you elaborate?

**Comment by joegoldman2** [comment]
The term output seems to refer to the return value and is slightly confusing. If you don't think the change is worth it, feel free to close both PRs.

**Comment by stephentoub** [comment]
> The term output seems to refer to the return value

It would refer to the return value in a situation like:
https://github.com/dotnet/runtime/blob/8121f82d7d46118eef03a99eecbde64d8021cec7/src/libraries/System.Web.HttpUtility/src/System/Web/HttpUtility.cs#L136-L137
which is the most common use for the attribute.

It would refer to the output value of a ref argument after the method call returns in a situation like:
https://github.com/dotnet/runtime/blob/8121f82d7d46118eef03a99eecbde64d8021cec7/src/coreclr/System.Private.CoreLib/src/System/Threading/Interlocked.CoreCLR.cs#L71

**Comment by joegoldman2** [comment]
TIL. Thank you!

**Pull request closed without merging**
