### PR TITLE
Clean up in importervectorization.cpp

### PR DESCRIPTION
**Pull request by EgorBo**
A small clean up in importervectorization.cpp:

- I've removed a bit obscured logic and the separation between SIMD and scalar. It's now a single function with a single loop
- The logic is no longer hard-limited by 1 or 2 loads per expansion. I plan to allow arm64 to use more loads to be on par with x64
- I've removed 32-bit specific limitations (hence, more improvements on x86 in the diffs)
- We now try to minimize the load size for the remainder, e.g. when our string is 6 bytes, we do the comparison as 4+2 instead of 4+4 (with overlap) - hence, we less likely hit a cache-line ([clang does the same](https://godbolt.org/z/eT5fbrW31)). This change is responsible for SPMI diffs.

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841179&view=ms.vss-build-web.run-extensions-tab)

### CODE REVIEW

**Comment by EgorBo** [comment]
@EgorBot -intel -gv4 -profiler
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Bencha).Assembly).Run(args);

public class Bencha
{
    static string[] Data = 
        Enumerable.Range(1000, 5000).Select(i => i.ToString()).ToArray();

    [Benchmark]
    public int Bench()
    {
        int sum = 0;
        foreach (var item in Data)
            if (item.StartsWith("111"))
                sum++;
        return sum;
    }

    [Benchmark]
    public int Bench_IgnoreCase()
    {
        int sum = 0;
        foreach (var item in Data)
            if (item.StartsWith("111", StringComparison.OrdinalIgnoreCase))
                sum++;
        return sum;
    }
}
```

**Comment by EgorBo** [comment]
@jakobbotsch @AndyAyersMS @dotnet/jit-contrib PTAL

the changes are mainly in one function so I suggest reviewing it as a whole, e.g. here: https://github.com/dotnet/runtime/blob/51a333705f3dcf6a552375ff1185fc91a6e82a12/src/coreclr/jit/importervectorization.cpp#L90-L213

This simplifies code along with some benefits (see description).

**Review by jakobbotsch — APPROVED** [review]
LGTM, nice clean up.

Btw I see that arm64 still uses bitwise ops instead of conditional compares. The conditional compares would likely be more dense.

**Comment by EgorBo** [comment]
> Btw I see that arm64 still uses bitwise ops instead of conditional compares. The conditional compares would likely be more dense.

I presume it's better if some other phase (morph/lower) handles it

**Comment by jakobbotsch** [comment]
> I presume it's better if some other phase (morph/lower) converts to a whatever is better shape. So it can also handle users inputs with bitwise ops

It would make more sense to me for this transform to produce the obvious IR (using GT_EQ), which will indeed be transformed to conditional compares.
Then I agree the x64 backend could transform to the bitwise version if that is actually better.

**Pull request merged**
