### PR TITLE
Make HttpResponseMessage.Content non-nullable

### LINKED ISSUE #35859: HttpResponseMessage.Content nullable annotation is... annoying
The annotation we have is correct: it can be null.  However, it'll never be null from the built-in handlers, yet developers are forced to either then do unnecessary null checks or `!`-away the nullable warnings, e.g.
```C#
using (var resp = await client.GetAsync(...))
{
    string s = await resp.Content.ReadAsStringAsync(); // nullable warning; need to do `Content!` instead
}
```

I wonder if we should change `HttpResponseMessage.Content` to be non-null returning and to lazily-initialize an empty content object if it would otherwise be null.

cc: @scalablecory, @davidsh, @safern, @buyaa-n

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/35859

cc: @scalablecory, @davidsh, @buyaa-n

### CODE REVIEW

**Review by scalablecory — APPROVED** [review]

**Comment by davidsh** [comment]
Do we need to change WinHttpHandler as well?

**Comment by stephentoub** [comment]
> Do we need to change WinHttpHandler as well?

This didn't actually change SocketsHttpHandler, just HttpResponseMessage.Content's getter.

**Review by davidsh — APPROVED** [review]

**Review by buyaa-n — APPROVED** [review]
LGTM, you might be already aware of, anyway just in case there is some test failures in `Microsoft.Extensions.Http.Logging.RedactedLogValueIntegrationTest.` seems related

**Comment by wfurt** [comment]
probably use of EmptyContent.
```
     Expected: ···ve: innocuous value\n
     Actual:   ···ve: innocuous value\nContent-Length: 0\n
```

**Comment by stephentoub** [comment]
> probably use of EmptyContent

Yup. Thanks.

**Review by safern — COMMENTED** [review]
LGTM

**Comment by gewarren** [comment]
@stephentoub As noted in https://github.com/dotnet/docs/issues/25953, it appears that this is a breaking change. Can you confirm?

**Comment by stephentoub** [comment]
Any bug fix can break something, but this doesn't qualify as a breaking change as far as our definition of the term applies.  To my knowledge the behavior of this member was never documented as to when it returned null or didn't, and we don't consider returning non-null when we previously returned null to be a "breaking change", even though, yes, it could break code checking for null (just as we don't consider changing something that was returning instances of type A to instance return an instance of type B that derives from A to be breaking, even though it can of course break someone).  On top of that, this would really only affect testing scenarios, as HttpResponseMessage.Content never returned null for responses coming back from HttpMessageHandler/SocketsHttpHandler/WinHttpHandler/etc.

**Pull request merged**
