### PR TITLE
JIT: Optimize liveness fixpoint computation

### PR DESCRIPTION
**Pull request by jakobbotsch**
When propagating liveness as part of the fixpoint computation we union the live-in state of all successors into the live-out state. We then further handle EH successors more conservatively since control can flow to those from any point in the BB.

The all-successors include successors from two additional sources compared to the regular successors:
1. They include the EH successors, but we already handle these conservatively later, so this is unnecessary.
2. They include EH successors of regular successors, but this liveness is already contributed from the regular successors since they will contain it in their live-in state at some point during the fixpoint computation.

Thus we can switch the first loop in liveness to only look at regular successors.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @BruceForstall 

[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=385880&view=ms.vss-build-web.run-extensions-tab) except for good TP improvements (e.g. -1.3% in asp.net win-x64).

**Review by BruceForstall — APPROVED** [review]
LGTM

**Pull request merged**
