### PR TITLE
Make AsnReader/AsnWriter public: Part 1 of 3.

### PR DESCRIPTION
**Pull request by bartonjs**
This change copies all of the AsnReader-relevant files from their current locations into System.Formats.Asn1:
* Common/src/System/Security/Cryptography/Asn1 to System.Formats.Asn1/src
  * All AsnReader.* files have been renamed to AsnDecoder.*, since the AsnDecoder class will be the ultimate repository for the core logic.
* System.Security.Cryptography.Encoding/tests to System.Formats.Asn1/tests
  * The tests.csproj has all of the Compile directives commented out in this phase, since there's nothing to compile the project against.

No changes have been made to these files in this copy.  This phase does set up System.Formats.Asn1 src/ref/tests to build, and to publish a System.Formats.Asn1 package. As of this phase the package has the right files, but the ref assembly is empty and the lib assembly has all types declared as internal.

---

Part 2 will apply all of the API Review feedback, make everything public, and activate testing.  This is being done as a separate step so it's easier to review the changes to the core logic as a result of factoring out state (AsnValueReader => AsnDecoder).

As of part 2, the package will be fully ready for downstream consumption.

---

Part 3 will split the AsnDecoder and AsnReader classes into separate files ("one class per file"). This is being done as a followup standalone change to ease reviewability.

---

Parts 4..N will involve determining the appropriate internal consumption model for this logic, leading up to the removal of the current files in Common (and S.S.C.Encodings.Tests).

### CODE REVIEW

**Comment by stephentoub** [comment]
> This change copies all of the AsnReader-relevant files from their current locations into System.Formats.Asn1:

Do you know why they aren't just showing up as renames?

**Comment by bartonjs** [comment]
> Do you know why they aren't just showing up as renames?

I think that only happens when there's a delete in the same commit.

**Comment by stephentoub** [comment]
> I think that only happens when there's a delete in the same commit.

Why isn't there? :)

**Comment by bartonjs** [comment]
Alright, I'll hold off until I figure out internal consumption and rewrite all the callers to adjust for the API review changes.

**Comment by stephentoub** [comment]
Thanks.  Sorry :-)

**Comment by stephentoub** [comment]
(You could still move the files and rename things, just update the call sites to match.)

**Comment by scott-xu** [comment]
Can you please make types under `System.Security.Cryptography.Pkcs.Asn1` and `System.Security.Cryptography.X509Certificates.Asn1` be public as well?

**Comment by scott-xu** [comment]
I ask because I want to verify a SignedCMS which is very similar with https://github.com/dotnet/runtime/blob/master/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Rfc3161TimestampToken.cs#L292

**Comment by scott-xu** [comment]
However, X509IssuerSerial, EssCertId and EssCertIdV2 etc. is internal.

**Comment by bartonjs** [comment]
@scott-xu No, those types are implementation details, and depend on a lot of assumptions that we can't take as public API.  If there are specific aspects that you wish there was public API available for, please open a new issue describing the problem space and what's lacking.

**Comment by scott-xu** [comment]
Let’s say if I have a SignerInfo and it has EssCertId and EssCertIdV2 in its SignedAttributes, how can I verify if the signing certificate is match?
IMHO, the types, for example EssCertId and EssCertIdV2 are kind of contract.

**Pull request closed without merging**
