### PR TITLE
Don't inline >8 bytes of IL calls in BBJ_THROW

### LINKED ISSUE #78300: Throw helper methods that just construct exceptions get inlined
Repro:
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8BiAOwFcAbS7YSmAAgBMBLXW+gWACgABAJgCMPXgAYGvQQDoASuVIYW+GFIDCEfAAcW9KAGUYUAG4swMXAG4eIgMwT+DVQwDePBu4l3eKBgFlBABQsCgwsAJQuoQBmDEEMALzxDKIRGAAWUBAA7o6w2BgwAWEWDAC+bh68Xj6+/EEh4ZEsMXGJyakZ2bkw+TAAchAAkqSUwcEA5kUl5dwenhI1NvUYoRHO0bEsCUkpDAAqnVlTZRXupxKCSAwAYtD4+QCiCGaaihCk3b1FCQB8DKQwHK3KD3DBPF5vUgBPQyKR7cwYYrnc4AbV8MHSECYgy0lAC6Mx2NxAHlXix3rgpANhqNSBMwgBdc6SK7A0HgmBk96fArUkZjUiTCLxP4AoF3R7PTmQ6Gw+G4RFWWYeZmXBb7Q7fEUMdKZHJim4SsFSrlQmFwhFI7gzEQOGE8VzK9xVC5XSTieUrbUAIm9StKQA=)
```C#
#nullable disable
using System;
using System.Runtime.CompilerServices;

public class C {
    public void M1(int i) { if (i == 0) throw Create(); }
    public void M2(int i) { if (i == 0) throw CreateNoInlining(); }
    public void M3(int i) { if (i == 0) Throw(); }
    
    static FormatException Create() => new FormatException(SR.Test);
    
    [MethodImpl(MethodImplOptions.NoInlining)]
    static FormatException CreateNoInlining() => new FormatException(SR.Test);
    
    static void Throw() => throw new FormatException(SR.Test);
}

class SR
{
    public static string Test => "";
}
```

This produces:
```
C.M1(Int32)
    L0000: push rsi
    L0001: sub rsp, 0x20
    L0005: test edx, edx
    L0007: je short L000f
    L0009: add rsp, 0x20
    L000d: pop rsi
    L000e: ret
    L000f: mov rcx, 0x7ffce3d82f68
    L0019: call 0x00007ffd4376f130
    L001e: mov rsi, rax
    L0021: mov ecx, 1
    L0026: mov rdx, 0x7ffceffec060
    L0030: call 0x00007ffd43741ec0
    L0035: mov rdx, rax
    L0038: mov rcx, rsi
    L003b: mov rax, 0x7ffce3d91f30
    L0045: call qword ptr [rax]
    L0047: mov rcx, rsi
    L004a: call 0x00007ffd4369fb10
    L004f: int3

C.M2(Int32)
    L0000: sub rsp, 0x28
    L0004: test edx, edx
    L0006: je short L000d
    L0008: add rsp, 0x28
    L000c: ret
    L000d: call 0x00007ffcefff0060
    L0012: mov rcx, rax
    L0015: call 0x00007ffd4369fb10
    L001a: int3

C.M3(Int32)
    L0000: sub rsp, 0x28
    L0004: test edx, edx
    L0006: je short L000d
    L0008: add rsp, 0x28
    L000c: ret
    L000d: call 0x00007ffcefff0078
    L0012: int3
```

I'd have expected M1 and M2 to be identical, with the JIT deciding not to inline `Create()` as all it's doing is constructing the exception that's about to be thrown, but without the NoInlining, it does get inlined.

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes: https://github.com/dotnet/runtime/issues/78300

```csharp
public static void Test(int i)
{
    if (i == 0) throw Create();
}

static FormatException Create() => new FormatException(SR.Test);

class SR
{
    public static string Test => "";
}
```
Codegen for `Test`, was:
```asm
; Method P:Test(int)
G_M000_IG01:                
       56                   push     rsi
       4883EC20             sub      rsp, 32
G_M000_IG02:                
       85C9                 test     ecx, ecx
       7406                 je       SHORT G_M000_IG04
G_M000_IG03:                
       4883C420             add      rsp, 32
       5E                   pop      rsi
       C3                   ret      
G_M000_IG04:                
       48B9F8A9FF0DFA7F0000 mov      rcx, 0x7FFA0DFFA9F8
       E8A244AE5F           call     CORINFO_HELP_NEWSFAST
       488BF0               mov      rsi, rax
       B901000000           mov      ecx, 1
       48BA18B2EF0DFA7F0000 mov      rdx, 0x7FFA0DEFB218
       E84B74AB5F           call     CORINFO_HELP_STRCNS
       488BD0               mov      rdx, rax
       488BCE               mov      rcx, rsi
       FF15070B2300         call     [System.FormatException:.ctor(System.String):this]
       488BCE               mov      rcx, rsi
       E88750A15F           call     CORINFO_HELP_THROW
       CC                   int3     
; Total bytes of code: 74
```
Now:
```asm
; Method P:Test(int)
G_M11252_IG01:            
       4883EC28             sub      rsp, 40
G_M11252_IG02:              
       85C9                 test     ecx, ecx
       7405                 je       SHORT G_M11252_IG04
G_M11252_IG03:              ;; offset=0008H
       4883C428             add      rsp, 40
       C3                   ret      
G_M11252_IG04:            
       FF153D1C4500         call     [P:Create():System.FormatException]
       488BC8               mov      rcx, rax
       E835E84E5F           call     CORINFO_HELP_THROW
       CC                   int3     
; Total bytes of code: 28
```

Currently, we almost never inline anything in throw blocks above 16 bytes of IL, but it seems that it's a good idea to not inline small methods too:

Pros:
1) inlining, even for small methods, is expensive (may lead to type load events for cold code we never execute) - I learned that from my "allow inlining in tier0" work.
2) ^ snippet is a great example of code bloated because we inlined a 11 bytes of IL method inside `throw`
3) Andy planned to not to compile BBJ_THROW at all via partial compilation

Cons:
1) Might regress performance for exceptions by adding `call` overhead, likely not noticeably. We can handle this via Dynamic PGO (if a throw blocks is not cold according to profile)
2) Sometimes inlining even in cold sections might improve overall type/memory/escape-analysis picture. I personally don't think it's the case here with Exception handling machinery.

### CODE REVIEW

**Comment by stephentoub** [comment]
Just for reference, I noticed it while looking at the codegen for the not-yet-merged https://github.com/dotnet/runtime/pull/71590/files#diff-f7c1029305b8ff70a95e36e675c08e17c8f816c5a1be8a204dc42d0595129e18R1419.

**Comment by stephentoub** [comment]
(And I suspect the diffs may be influenced by such NoInlining in use elsewhere to work around this, e.g. https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.Pipelines/src/System/IO/Pipelines/ThrowHelper.cs)

**Comment by EgorBo** [comment]
@dotnet/jit-contrib @jakobbotsch PTAL, Diffs: https://dev.azure.com/dnceng-public/public/_build/results?buildId=85004&view=ms.vss-build-web.run-extensions-tab

I made the PR less conservative so now the number of size regressions is minimal. The current logic is to inline everything below 8 bytes of IL (e.g. properties) and immediately give up on everything larger where previously we had IL prescan. Number of regressions seem reasonable to me now, previous version of this PR was more aggressive.

**Review by jakobbotsch — APPROVED** [review]
LGTM in principle.

Any examples of the regressions? I can imagine not exposing some facts, even in the throwing BBs, can hurt codegen in the rest of the function. For example if we no longer inline a function with an argument `in S someStruct` then that could result in new address exposure.

**Comment by EgorBo** [comment]
@jakobbotsch I was not able to find any case like that in the diffs. What I did find is the cases like these:

image

I tried to adjust the heuristic to not do that for methods returning structs by value but it hid many previous improvements. Overall the number of regressions is "big" only in PMI collections:

image

From the same methods with different generic types (pmi)

**Comment by jakobbotsch** [comment]
How come there's no diffs in the crossgen2 collections?

**Comment by EgorBo** [comment]
> How come there's no diffs in the crossgen2 collections?

crossgen2 uses more conservative inliner while I did my changes in ExtendedDefaultPolicy.
I can move them into the baseclass so crossgen will also pick it up.

**Review by jakobbotsch — APPROVED** [review]

**Comment by EgorBo** [comment]
image

new diffs with crossgen2 included, thanks for the suggestion

**Comment by BruceForstall** [comment]
Seems like the JIT shouldn't inline any function that is straight-line code leading to a `throw` (or more generally, where the IL entrypoint is post-dominated by a `throw`). Maybe we don't have that information, or it would be expensive to compute.

**Comment by EgorBo** [comment]
> [Edit] I slightly misread the issue, as the throw is in the caller, not callee. So why do we inline any functions at all in this case? the throw is presumably going to dominate any performance.

The initial change in this PR did exactly that but that produced a lot of size regressions and many examples actually affected non-cold path too (e.g. more registers were saved) so I changed it to "Ok, inline only under 8 bytes of IL", mostly for various properties (getters/setters), I tried to play with that threshold and 8 (actually even 9) was the best value.

**Comment by BruceForstall** [comment]
I guess the size regression was because the call overhead was larger than the generated code for very small functions.

**Pull request merged**
