### PR TITLE
Add Android support to System.IO.Ports

### LINKED ISSUE #86619: SerialPort is not supported on Android ?
### Description

when open serialport Exception : System.DllNotFoundException: 'libSystem.IO.Ports.Native'

### Reproduction Steps

1.Create a SerialPort class
2.Configure the serial port settings
3.Open the serial port

### Expected behavior

open serialport success

### Actual behavior

monodroid-assembly Shared library 'libSystem.IO.Ports.Native' not loaded, p/invoke 'SystemIoPortsNative_SerialPortOpen' may fail

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

.net core7.0
android 7.1
arm

### Other information

_No response_

### PR DESCRIPTION
**Pull request by akoeplinger**
Fixes https://github.com/dotnet/runtime/issues/86619

Also removes unused `HAVE_TERMIOS2_EXITCODE` from tryrun.cmake, the `HAVE_TERMIOS2` check is not a tryrun one but a compile check.

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by wfurt** [comment]
The package now fails to restore
```

    <PackageReference Include="System.IO.Ports" Version="9.0.0-alpha.1.23608.3" />


furt@ubu20:~/projects/sslTest$ ~/dotnet-8/dotnet restore
  Determining projects to restore...
/home/furt/projects/sslTest/sslTest.csproj : error NU1101: Unable to find package runtime.android-arm.runtime.native.System.IO.Ports. No packages exist with this id in source(s): dotnet-labs, dotnet6, dotnet7, dotnet8, dotnet9, nuget.org
/home/furt/projects/sslTest/sslTest.csproj : error NU1101: Unable to find package runtime.android-arm64.runtime.native.System.IO.Ports. No packages exist with this id in source(s): dotnet-labs, dotnet6, dotnet7, dotnet8, dotnet9, nuget.org
/home/furt/projects/sslTest/sslTest.csproj : error NU1101: Unable to find package runtime.android-x64.runtime.native.System.IO.Ports. No packages exist with this id in source(s): dotnet-labs, dotnet6, dotnet7, dotnet8, dotnet9, nuget.org
/home/furt/projects/sslTest/sslTest.csproj : error NU1101: Unable to find package runtime.android-x86.runtime.native.System.IO.Ports. No packages exist with this id in source(s): dotnet-labs, dotnet6, dotnet7, dotnet8, dotnet9, nuget.org
  Failed to restore /home/furt/projects/sslTest/sslTest.csproj (in 774 ms).
```

It is curious that I see `runtime.linux-bionic-arm64.runtime.native.System.IO.Ports` that was added by this PR but not the android. 
https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet9

I'm wondering if there is some patter filter for package publishing...???
cc: @ViktorHofer for infra angle.

**Comment by ViktorHofer** [comment]
Do we have official build CI legs that build the native binaries, i.e. `runtime.android-arm.runtime.native.System.IO.Ports`? If not then we would need to add them.

**Comment by akoeplinger** [comment]
The package issue was fixed with https://github.com/dotnet/runtime/pull/96026

**Pull request merged**
