### PR TITLE
Try full benchmark run for SPMI collection

### PR DESCRIPTION
**Pull request by kunalspathak**

### CODE REVIEW

**Comment by BruceForstall** [comment]
@kunalspathak Is this close to getting merged?

I'm worried that with all the recent JIT-EE version changes, when you trigger this PR and publish new collections, it might be doing builds/tests not against current master -- at least, some behavior I'm seeing might indicate I'm not seeing the right collection MCH format.

**Comment by kunalspathak** [comment]
We might need more time to understand why benchmark mch don't show TIER flags. See https://github.com/dotnet/runtime/pull/48281#issuecomment-780690721 and https://github.com/dotnet/runtime/pull/48281#issuecomment-780803729. May be you should merge your changes in https://github.com/dotnet/runtime/pull/48375 so we can at least get Linux x64 collection back.

**Comment by BruceForstall** [comment]
Ok. Then maybe you should temporarily change the JIT/EE GUID in this PR while you're iterating on it. Or maybe you should change it anyway, to force a new collection when you eventually merge.

**Comment by kunalspathak** [comment]
For now I am closing this PR and might reopen specifically if we want to enable dynamic PGO flags.

**Pull request closed without merging**
