### PR TITLE
Update Roslyn Testing SDK

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Update the Roslyn testing SDK to pick up fixes for the NuGet package download that's part of the ReferenceAssemblies API.

### CODE REVIEW

**Comment by elinor-fung** [comment]
We should also be able to get rid of this, right?
https://github.com/dotnet/runtime/blob/d2688883510318aa0114268930fb2022d3dc64cf/src/libraries/System.Runtime.InteropServices/tests/LibraryImportGenerator.UnitTests/TestUtils.cs#L226

**Comment by jkoritzinsky** [comment]
I thought I removed that... I'll go back and make sure I delete it

**Comment by jkoritzinsky** [comment]
Test failure is unrelated. This is ready for another round of review

**Review by elinor-fung — APPROVED** [review]
Hurray!

**Pull request merged**
