### PR TITLE
Avoid crashing on unresolved dependencies

### LINKED ISSUE #70815: NativeAOT compiler crashes if assembly missing
Create console application which targets net7.0 and attempt to add `Microsoft.Extensions.Hosting` with explicit dependencies and missing reference to `Microsoft.Extensions.Configuration.EnvironmentVariables`. ILC crashes.
```
  System.AggregateException: One or more errors occurred. (Code generation failed for method '[Microsoft.Extensions.Hosting]Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.ConfigureDefaults(IHostBui
  lder,string[])')
   ---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[Microsoft.Extensions.Hosting]Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.ConfigureDefaults(IHostBuilder,stri
  ng[])'
   ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at ILCompiler.LazyGenericsSupport.GraphBuilder.WalkMethod(EcmaMethod method) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/LazyGenerics/GraphBuilder.cs:line 204
     at ILCompiler.LazyGenericsSupport.GraphBuilder..ctor(EcmaModule assembly) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/LazyGenerics/GraphBuilder.cs:line 59
     at ILCompiler.LazyGenericsSupport.CycleInfoHashtable.CreateValueFromKey(EcmaModule key) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/LazyGenerics/ModuleCycleInfo.cs:line 50
     at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey key) in /_/src/coreclr/tools/Common/TypeSystem/Common/Utilities/LockFreeReaderHashtable.cs:line 559
     at ILCompiler.LazyGenericsSupport.GenericCycleDetector.DetectCycle(TypeSystemEntity owner, TypeSystemEntity referent) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/LazyGenerics/ModuleCycleInfo
  .cs:line 193
     at Internal.IL.ILImporter.GetMethodEntrypoint(MethodDesc method) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs:line 253
     at Internal.IL.ILImporter.ImportCall(ILOpcode opcode, Int32 token) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs:line 685
     at Internal.IL.ILImporter.ImportBasicBlock(BasicBlock basicBlock) in /_/src/coreclr/tools/Common/TypeSystem/IL/ILImporter.cs:line 600
     at Internal.IL.ILImporter.ImportBasicBlocks() in /_/src/coreclr/tools/Common/TypeSystem/IL/ILImporter.cs:line 311
     at Internal.IL.ILImporter.Import() in /_/src/coreclr/tools/aot/ILCompiler.Compiler/IL/ILImporter.Scanner.cs:line 156
     at ILCompiler.ILScanner.CompileSingleMethod(ScannedMethodNode methodCodeNodeNeedingCode) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ILScanner.cs:line 123
     --- End of inner exception stack trace ---
     at ILCompiler.ILScanner.CompileSingleMethod(ScannedMethodNode methodCodeNodeNeedingCode) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ILScanner.cs:line 134
     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
     at System.Threading.Tasks.TaskReplicator.Replica.Execute()
     --- End of inner exception stack trace ---
     at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
     at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit
  , Action`1 localFinally)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit
  , Action`1 localFinally)
     at ILCompiler.ILScanner.CompileMultiThreaded(List`1 methodsToCompile) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ILScanner.cs:line 97
     at ILCompiler.ILScanner.ComputeDependencyNodeDependencies(List`1 obj) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ILScanner.cs:line 86
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 315
     at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan() in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ILScanner.cs:line 140
     at ILCompiler.Program.Run(String[] args) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 828
     at ILCompiler.Program.Main(String[] args) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 1085
```

Addition to console app.
```
<ItemGroup>
    <Reference Include="Microsoft.Extensions.Hosting">
      <HintPath>$(RuntimeRepoRoot)artifacts\bin\Microsoft.Extensions.Hosting\Release\net7.0\Microsoft.Extensions.Hosting.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Hosting.Abstractions">
      <HintPath>$(RuntimeRepoRoot)artifacts\bin\Microsoft.Extensions.Hosting.Abstractions\Release\net7.0\Microsoft.Extensions.Hosting.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging">
      <HintPath>$(RuntimeRepoRoot)artifacts\bin\Microsoft.Extensions.Logging\Release\net7.0\Microsoft.Extensions.Logging.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>$(RuntimeRepoRoot)artifacts\bin\Microsoft.Extensions.Logging.Abstractions\Release\net7.0\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection">
      <HintPath>$(RuntimeRepoRoot)artifacts\bin\Microsoft.Extensions.DependencyInjection\Release\net7.0\Microsoft.Extensions.DependencyInjection.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>$(RuntimeRepoRoot)artifacts\bin\Microsoft.Extensions.DependencyInjection.Abstractions\Release\net7.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Configuration">
      <HintPath>$(RuntimeRepoRoot)artifacts\bin\Microsoft.Extensions.Configuration\Release\net7.0\Microsoft.Extensions.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Configuration.Abstractions">
      <HintPath>$(RuntimeRepoRoot)artifacts\bin\Microsoft.Extensions.Configuration.Abstractions\Release\net7.0\Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.FileProviders.Physical">
      <HintPath>$(RuntimeRepoRoot)artifacts\bin\Microsoft.Extensions.FileProviders.Physical\Release\net7.0\Microsoft.Extensions.FileProviders.Physical.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.FileProviders.Abstractions">
      <HintPath>$(RuntimeRepoRoot)artifacts\bin\Microsoft.Extensions.FileProviders.Abstractions\Release\net7.0\Microsoft.Extensions.FileProviders.Abstractions.dll</HintPath>
    </Reference>
  </ItemGroup>
```

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #70815.

### CODE REVIEW

**Review by vitek-karas — APPROVED** [review]
Side question (not just about this PR): What's our story for testing? We're adding lot of great fixes, but very little tests. In this case adding a regression test would be nice.

**Comment by MichalStrehovsky** [comment]
I usually add tests for things that were not found in our repo testing. So for example #70883 has a test. Then #70881 doesn't because it was found in libs test.

I consider invalid inputs best effort. Writing tests for them is really annoying because one can't just write C#, or if it's written in C#. one needs to mess with it. It's a lot of effort for "best effort".

**Comment by MichalStrehovsky** [comment]
The motivation why it's best effort is captured down in https://github.com/dotnet/runtime/issues/70815#issuecomment-1158431222.

**Comment by vitek-karas** [comment]
Thanks for the explanation - I agree that invalid inputs are probably not worth too much testing effort.

**Pull request merged**
