### PR TITLE
HttpContent disposal in HttpClientJsonExtensions

### PR DESCRIPTION
**Pull request by sstronin**
HttpClient doesn't dispose HttpContent in .NET, it's the caller's responsibility. Here is a fix for missing disposal in built-in extension methods.

### CODE REVIEW

**Comment by stephentoub** [comment]
This adds expense to each operation. What resource does this disposal help clean up? In all of these situations, is the JsonContent.Dispose not an effective nop?

**Comment by stephentoub** [comment]
> but underlying HttpContent could dispose some streams

But the aren't any here, are there?

> adding another await frame to it doesn't look affecting overall cost somehow

It adds more allocation.

**Comment by karelz** [comment]
@stephentoub any thoughts for next steps? Is there anything we should use from the PR, or do you recommend closing it? Thanks!

**Comment by stephentoub** [comment]
> @stephentoub any thoughts for next steps? Is there anything we should use from the PR, or do you recommend closing it? Thanks!

While I appreciate @sstronin's efforts and goal, I don't currently see this providing meaningful benefit that outweighs the real overhead. I suggest we close it, unless @MihaZupan sees something I've missed.

**Pull request closed without merging**
