### PR TITLE
Various fixes for merged test runners on Mono

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fix a few different issues we've encountered with the merged test runners around llvmfullaot and mobile runs in combination with our issues.targets compatibility story during the transition.

### CODE REVIEW

**Review by trylek — APPROVED** [review]
Looks great to me, thanks Jeremy!

**Review by steveisok — APPROVED** [review]

**Review by radical — APPROVED** [review]

**Comment by radical** [comment]
Wasm failures are unrelated to this PR.

**Comment by jkoritzinsky** [comment]
Android runtime test failure is a failure with the xharness event processor script.

All other test failures are in the libraries tests, which are not touched at all by these changes.

I'll re-run the runtime-extra-platforms failing legs to see if the libraries test failures are infra-related (they look like they are in the Helix logs).

**Comment by jkoritzinsky** [comment]
The failures in the re-run all look unrelated, so I'm going to merge this in.

**Comment by premun** [comment]
> Android runtime test failure is a failure with the xharness event processor script.

@jkoritzinsky could you please point me to that failure? I wasn't able to find it (plus any error in that script should not actually have effect on the work item result).

I see 2 failed Android legs from the first attempt:
- https://dev.azure.com/dnceng/public/_build/results?buildId=1703423&view=logs&j=b6e5d97f-d4f8-506b-9e47-e3e32385754a&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=94ce2805-f3e2-5f9a-1d92-0da5613f733d&l=59 - Failed test
- https://dev.azure.com/dnceng/public/_build/results?buildId=1703423&view=logs&j=b6f63eff-75cc-59ca-fdbf-d2121601a613&s=96ac2280-8cb4-5df5-99de-dd2da759617d&t=92df95dc-ad7c-5fec-a8b4-c8301b7a2225&l=125 - Here I am actually not sure what failed, I will investigate but I don't see problems with the script here

**Pull request merged**
