### PR TITLE
Respect JitEnableOptionalRelocs in TryReserveInitialMemory

### PR DESCRIPTION
**Pull request by EgorBo**
Let's not **try** to allocate the loader heap near coreclr when `JitEnableOptionalRelocs=0` is set since it seems to be pretty random whether we successfully do that or fallback to a random memory - that leads to inconsistent performance measurements. From what I see we are more often fail to do that anyway or arm64. It also not uncommon on Linux-x64 as well.

### CODE REVIEW

**Comment by EgorBo** [comment]
PTAL @jkotas @janvorli

**Comment by jkotas** [comment]
If you want the JitEnableOptionalRelocs switch to be fully reliable, I do not think that tweaking how memory gets allocated is the right strategy. I won't ever make it fully reliable.

Instead, should this switch be telling the JIT and VM to always go through jump stubs, and to disable other optimizations that depend on address proximity instead?

**Comment by EgorBo** [comment]
> If you want the JitEnableOptionalRelocs=0 switch to be fully reliable, I do not think that tweaking how memory gets allocated is the right strategy. I won't ever make it fully reliable.

Do you mean it might be still reachable even with random address? (extremely unlikely with arm64 I suppose). 

> Instead, should this switch be telling the JIT and VM to always go through jump stubs, and to disable other optimizations that depend on address proximity instead?

including all managed-to-managed as well? won't it have a heavy impact compared to default mode?

**Comment by jkotas** [comment]
> including all managed-to-managed as well? won't it have a heavy impact compared to default mode?

All these are opportunistic optimizations that can be non-deterministic, The switch documentation says that setting it to 0 should disable all of them: https://github.com/dotnet/runtime/blob/063ae05c63307becef004eefbc8704ccb03c7f04/src/coreclr/inc/clrconfigvalues.h#L314-L316

It sounds like that you would like the switch to disable some of these, but not all of them. How do we decide what the switch should disable and what it should not disable?

**Comment by EgorBo** [comment]
@EgorBot -arm64 --envvars DOTNET_JitEnableOptionalRelocs:0
```cs
using BenchmarkDotNet.Attributes;
using System.Runtime.CompilerServices;

public class Bench
{
    [Benchmark]
    public void Test1() => Test2();

    [MethodImpl(MethodImplOptions.NoInlining)] void Test2() => Test3();
    [MethodImpl(MethodImplOptions.NoInlining)] void Test3() => Test4();
    [MethodImpl(MethodImplOptions.NoInlining)] void Test4(){}
}
```

**Comment by EgorBo** [comment]
@EgorBot -arm64 -perf --envvars DOTNET_JitEnableOptionalRelocs:0
```cs
using BenchmarkDotNet.Attributes;
using System.Runtime.CompilerServices;

public class Bench
{
    [Benchmark]
    public void Test1() => Test2();

    [MethodImpl(MethodImplOptions.NoInlining)] void Test2() => Test3();
    [MethodImpl(MethodImplOptions.NoInlining)] void Test3() => Test4();
    [MethodImpl(MethodImplOptions.NoInlining)] void Test4(){}
}
```

**Comment by EgorBo** [comment]
@EgorBot -arm64 -intel -perf --envvars DOTNET_JitEnableOptionalRelocs:0
```cs
using BenchmarkDotNet.Attributes;
using System.Runtime.CompilerServices;

public class Bench
{
    [Benchmark]
    public void ManagedToManaged()
    {
        DoWork();
        DoWork();
        DoWork();
        DoWork();
    }
    [MethodImpl(MethodImplOptions.NoInlining)] void DoWork() { }

    object a;
    object b;

    [Benchmark]
    public void WriteBarrier() => a = b;
}
```

**Comment by EgorBo** [comment]
Ah, managed-to-managed doesn't go through a jump-stub, but rather starts doing:
```
 00007fa6`cf831e2d        mov      rax, 0x7FA6CFC34348      ; code for Proga:Test()
 00007fa6`cf831e37        call     [rax]Proga:Test()
```
if it can't do a reloc'd call.

**Comment by EgorBo** [comment]
@EgorBot -arm64 -perf
```cs
using BenchmarkDotNet.Attributes;
using System.Runtime.CompilerServices;

public class Bench
{
    [Benchmark]
    public void ManagedToManaged()
    {
        DoWork();
        DoWork();
        DoWork();
        DoWork();
    }
    [MethodImpl(MethodImplOptions.NoInlining)] void DoWork() { }

    object a;
    object b;

    [Benchmark]
    public void WriteBarrier() => a = b;
}
```

**Pull request closed without merging**
