### PR TITLE
Add missing compiler-generated attributes to corelib

### LINKED ISSUE #85612: Attribute definitions included in assemblies using Nullable on the latest framework
### Description

I would expect that assemblies compiling against the latest framework would not need to define attribute types when using compiler features.

Instead I see a number of internal attributes included:
```c#
namespace System.Runtime.CompilerServices
{
    [CompilerGenerated]
    [Microsoft.CodeAnalysis.Embedded]
    internal sealed class IsUnmanagedAttribute : Attribute
    {
    }

    [CompilerGenerated]
    [Microsoft.CodeAnalysis.Embedded]
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Parameter | AttributeTargets.ReturnValue | AttributeTargets.GenericParameter, AllowMultiple = false, Inherited = false)]
    internal sealed partial class NullableAttribute : Attribute
    {
        public readonly byte[] NullableFlags;
        public NullableAttribute(byte value) { }

        public NullableAttribute(byte[] value) { }
    }

    [CompilerGenerated]
    [Microsoft.CodeAnalysis.Embedded]
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Method | AttributeTargets.Interface | AttributeTargets.Delegate, AllowMultiple = false, Inherited = false)]
    internal sealed partial class NullableContextAttribute : Attribute
    {
        public readonly byte Flag;
        public NullableContextAttribute(byte value) { }
    }

    [CompilerGenerated]
    [Microsoft.CodeAnalysis.Embedded]
    [AttributeUsage(AttributeTargets.Module, AllowMultiple = false, Inherited = false)]
    internal sealed partial class NullablePublicOnlyAttribute : Attribute
    {
        public readonly bool IncludesInternals;
        public NullablePublicOnlyAttribute(bool value) { }
    }
    [CompilerGenerated]
    [Microsoft.CodeAnalysis.Embedded]
    [AttributeUsage(AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
    internal sealed class ScopedRefAttribute : Attribute
    {
    }
}
```

https://github.com/dotnet/runtime/issues/29039 mentions that these were not included because 
> Any code reasoning about the attribute has to assume that attribute is emitted, so you can't optimize the path.

Correct.  Language features shouldn't depend on type location, but that's true even for language feature supporting types we put in the framework.  We don't put the type in the framework to make it easier for the compiler.

> The size is small

I briefly measured the size and it seemed to increase an assembly by ~512 bytes by defining these types.  While that's small it can add up.  Across the framework assemblies in the ref packs and runtimes I found 476 assemblies defining these types accounting for >200KB size on disk.  I'm also seeing another 300 assemblies in the SDK.  Probably if you consider every customer assembly produced it would add up even more.

### Reproduction Steps

Build a library using nullable and target `net8.0`.

### Expected behavior

Only types defined by my project appear in my assembly.

### Actual behavior

Language / framework types are emitted into my assembly.

### Regression?

No

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/85612

Cherry-picked @ericstj's commit for adding these and then tweaked it a bit (e.g. added docs and tests).

### CODE REVIEW

**Comment by ericstj** [comment]
Interesting - we had one test that expected to find `NullableContextAttribute` defined in System.Text.Json.dll:
https://github.com/dotnet/runtime/blob/9fc5fcb0af7d068298bb1950e8d00ce26a70456c/src/libraries/System.Text.Json/tests/Common/UnsupportedTypesTests.cs#L173-L182

Perhaps that test should fallback to looking in the core assembly for `NullableContextAttribute`.  cc @eiriktsarpalis

**Comment by eiriktsarpalis** [comment]
@ericstj Either that or conditioning the `Assembly` on the tested TFM.

**Comment by 333fred** [comment]
I do want to hold off on this until we have a bit of time investigate on the roslyn-side about the correct ordering we should look for these attributes and making sure that we're not about to introduce a large metadata-breaking change as libraries update to .NET 8. I should have some time for that next week after we get collection literals merged.

**Comment by ericstj** [comment]
> @ericstj Either that or conditioning the Assembly on the tested TFM.

I wasn't sure if that test was actually specific to that type, or you just happened to choose it because it had the characteristics you needed to serve as a repro.  From your [comment ](https://github.com/dotnet/runtime/issues/58690#issuecomment-1201726052) in the issue:

> Root cause appears to be IL https://github.com/dotnet/runtime/issues/73188#issuecomment-1201720842 containing parameters with stripped names.

So maybe we could add some test type that is guaranteed to have stripped parameter names.  I actually don't understand why the JsonSerializer would ever try to serialize an attribute, unless the user passed in a value of that attribute to serialize which seems really unusual.

**Comment by stephentoub** [comment]
I pushed a commit to disable the json test on netcoreapp.

There are other failures on mono in release, all related to moq / castle, I'm guessing something to do with trimming.

**Comment by eiriktsarpalis** [comment]
> So maybe we could add some test type that is guaranteed to have stripped parameter names. I actually don't understand why the JsonSerializer would ever try to serialize an attribute, unless the user passed in a value of that attribute to serialize which seems really unusual.

The original [customer reported issue](https://github.com/dotnet/runtime/issues/58690) was trying to serialize that attribute. I tried reproducing the problem with a test type but couldn't. IIRC it had something to do with how the compiler emitted IL for the particular compiler generated attribute.

**Review by eiriktsarpalis — APPROVED** [review]

**Comment by 333fred** [comment]
> I do want to hold off on this until we have a bit of time investigate on the roslyn-side about the correct ordering we should look for these attributes and making sure that we're not about to introduce a large metadata-breaking change as libraries update to .NET 8. I should have some time for that next week after we get collection literals merged. I don't expect to encounter unsolvable issues, but measure twice cut once.

I put my investigation notes into https://github.com/dotnet/roslyn/issues/68697#issuecomment-1608216658, but the TLDR is that our past selves were smart and thought about this, and we are good to proceed.

**Comment by stephentoub** [comment]
@lewing, suggestions on how to track down why this is failing?  Seems likely it's related to trimming, given the mono legs that are failing.

**Comment by ericstj** [comment]
Still failing, but most were fixed by picking up the new version of Moq.  Everything failing here is failing at this:
https://github.com/castleproject/Core/blob/dca4ed09df545dd7512c82778127219795668d30/src/Castle.Core/DynamicProxy/Generators/MethodWithInvocationGenerator.cs#L78C22-L78C32
```c#
var constructor = invocation.GetConstructors()[0];
```
Where `invocation` is a `System.Type` that seems to be generated.  Seeing the same callstack across multiple different tests, all trying to create mocks for abstract types or interfaces.  It's not clear to me why this is failing only on browser-wasm - perhaps some difference with Reflection / Emit behavior here?  @lewing any suggestions for how to follow up on this?

**Comment by lewing** [comment]
Is it just a case of the constructors being linked out then an attempt to access them via reflection?

cc @lambdageek

**Comment by ericstj** [comment]
> Is it just a case of the constructors being linked out then an attempt to access them via reflection

I'm not certain - looking through this code it seems to me like these types are generated at runtime with ref.emit - so the linker *shouldn't* be involved.  I'm trying to debug what Moq is doing in the non-browser case to try and answer the question about "what types are these".

**Comment by ericstj** [comment]
Ok, so at least on windows I see these types being used:
```
{Name = "InterfaceMethodWithoutTargetInvocation" FullName = "Castle.DynamicProxy.Internal.InterfaceMethodWithoutTargetInvocation"}
```
That type does have a constructor, when not trimmed: https://github.com/castleproject/Core/blob/dca4ed09df545dd7512c82778127219795668d30/src/Castle.Core/DynamicProxy/Internal/InterfaceMethodWithoutTargetInvocation.cs#L28

So I downloaded the helix payload for the failing test and examined the IL, sure enough that constructor is missing:
```
.class public auto ansi sealed beforefieldinit Castle.DynamicProxy.Internal.InterfaceMethodWithoutTargetInvocation
	extends Castle.DynamicProxy.AbstractInvocation
{
	.custom instance void [System.Private.CoreLib]System.ComponentModel.EditorBrowsableAttribute::.ctor(valuetype [System.Private.CoreLib]System.ComponentModel.EditorBrowsableState) = (
		01 00 01 00 00 00 00 00
	)
	// Methods
	.method public hidebysig specialname virtual 
		instance object get_InvocationTarget () cil managed 
	{
		// Method begins at RVA 0x5059
		// Header size: 1
		// Code size: 2 (0x2)
		.maxstack 8

		IL_0000: ldnull
		IL_0001: ret
	} // end of method InterfaceMethodWithoutTargetInvocation::get_InvocationTarget

	.method public hidebysig specialname virtual 
		instance class [System.Private.CoreLib]System.Reflection.MethodInfo get_MethodInvocationTarget () cil managed 
	{
		// Method begins at RVA 0x5059
		// Header size: 1
		// Code size: 2 (0x2)
		.maxstack 8

		IL_0000: ldnull
		IL_0001: ret
	} // end of method InterfaceMethodWithoutTargetInvocation::get_MethodInvocationTarget

	.method public hidebysig specialname virtual 
		instance class [System.Private.CoreLib]System.Type get_TargetType () cil managed 
	{
		// Method begins at RVA 0x5059
		// Header size: 1
		// Code size: 2 (0x2)
		.maxstack 8

		IL_0000: ldnull
		IL_0001: ret
	} // end of method InterfaceMethodWithoutTargetInvocation::get_TargetType

	.method family hidebysig virtual 
		instance void InvokeMethodOnTarget () cil managed noinlining 
	{
		// Method begins at RVA 0x504d
		// Header size: 1
		// Code size: 11 (0xb)
		.maxstack 8

		IL_0000: ldstr "Linked away"
		IL_0005: newobj instance void [System.Private.CoreLib]System.NotSupportedException::.ctor(string)
		IL_000a: throw
	} // end of method InterfaceMethodWithoutTargetInvocation::InvokeMethodOnTarget

	// Properties
	.property instance object InvocationTarget()
	{
		.get instance object Castle.DynamicProxy.Internal.InterfaceMethodWithoutTargetInvocation::get_InvocationTarget()
	}
	.property instance class [System.Private.CoreLib]System.Reflection.MethodInfo MethodInvocationTarget()
	{
		.get instance class [System.Private.CoreLib]System.Reflection.MethodInfo Castle.DynamicProxy.Internal.InterfaceMethodWithoutTargetInvocation::get_MethodInvocationTarget()
	}
	.property instance class [System.Private.CoreLib]System.Type TargetType()
	{
		.get instance class [System.Private.CoreLib]System.Type Castle.DynamicProxy.Internal.InterfaceMethodWithoutTargetInvocation::get_TargetType()
	}

} // end of class Castle.DynamicProxy.Internal.InterfaceMethodWithoutTargetInvocation
```

That explains the error, but doesn't really explain why **this PR** would cause that.  I see the same test passing in other PRs, so I'm downloading the helix payload from those to see if they differ (retain the constructor).

**Comment by ericstj** [comment]
I found this -- https://github.com/dotnet/runtime/blob/a2c19cd005a1130ba7f921e0264287cfbfa8513c/eng/testing/ILLinkDescriptors/ILLink.Descriptors.Castle.xml#L2-L6
Which looks like it's preserving metadata on similar types... I wonder if something about the update I made to Moq / Castle.Core caused it to start hitting this codepath that it did not before and we just need to root more types for the linker 🤔.

**Comment by ericstj** [comment]
I see -- indeed that is the problem.  This change started using the type in Castle.Core instead of emitting a type: https://github.com/castleproject/Core/commit/0c8f9d0d237ae2bc25c325fce2da562c467ca313#diff-4ba914dc0e136772f890d9ffaf385d702f91df37c92f648ff06bb31a39def6c1

That change came down as part of the update to Moq so I'll need to include that type in the ILLink.Descriptors.Castle.xml.

**Comment by ericstj** [comment]
Ok - I learned how to get a repro in a plain-old console app.  `dotnet new console` add reference to Moq and set `PublishTrimmed` to true.  This lets me debug and work through the issues using a proper debugger.  👍 The latest changes got me through the callstack that was failing -- now to see if things get further in browser...

**Comment by ericstj** [comment]
All remaining issues in PR validation are known failures.

**Pull request merged**
