### PR TITLE
[wasm] CI: Add support for running WBT with multithreaded runtime installed too

### PR DESCRIPTION
**Pull request by radical**
# [wasm] CI: Add support for running WBT with multiple runtime packs

This depends on two other builds:
1. A single threaded build run from wasm-build-only, which publishes its nugets, and other artifacts.
2. A multi threaded build similar to (1)

The actual WBT job does not build anything now. Instead:
1. Downloads the artifacts from the two builds
2. Downloads Wasm.Build.Tests.zip
2. Sets up `artifacts/` to enable the steps below
3. Prepare the sdk for workload testing
4. Run the zip from (2) with sdk from (3), on helix

## Details
- [wasm] Rename GlobalizationMode.Default to GlobalizationMode.Sharded
- [wasm] WBT: Add BlazorRunOptions
- [wasm] WBT: Add $(PreparePackagesForWorkloadInstall) to control
- Add new `mono.wasmworkload` subset
- [wasm] CI: rename wasm-build-tests.yml to simple-wasm-build-tests.yml
- CI: Add preBuildSteps parameter to global-build-job.yml
- [wasm] CI: Add support for building, and publishing from multiple wasm
- [wasm] CI: Add support for running WBT with multiple runtime packs
- [wasm] WBT: Add a blazor test for multithreaded build

## Notes
- Multithreading tests are run locally only if the multithreading runtime pack (with `dotnet.native.worker.js`) is available
- These tests are always run on CI

### CODE REVIEW

**Comment by radical** [comment]
Notes for reviewer: Read the individual commits in order.

**Comment by radical** [comment]
@akoeplinger this has some non-wasm CI, and build bits. Would you mind taking a look?

**Comment by pavelsavara** [comment]
the non-MT and the MT build still can't run on in the same `artifacts`, right ? What does it mean for running BTW locally ?

**Comment by radical** [comment]
Failures are known, and unrelated.

**Comment by radical** [comment]
> the non-MT and the MT build still can't run on in the same `artifacts`, right ? What does it mean for running WBT locally ?

Hm good question. I will disable the MT test for local runs right now. And in a follow up PR, add some detection mechanism so it runs only if you have a proper mt runtime available.

**Review by pavelsavara — APPROVED** [review]

**Pull request merged**
