### PR TITLE
Fixes to static field offsets

### PR DESCRIPTION
**Pull request by fadimounir**
1) Stop counting offsets for RVA fields (this messes up the offsets of all statics)
2) Small fix to the size computation of nonGC statics (we were counting some GC statics as non-gc statics)
3) Bringing a small optimization we had with crossgen1 (safe static byref return)
4) Tiny micro-optimization: avoid allocation while looking up offsets for a type in one of the Typesystem hashtables (introduced with determinism work)

### CODE REVIEW

**Comment by fadimounir** [comment]
@dotnet/crossgen-contrib

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by fadimounir** [comment]
This fix caused some regressions in the R2R tests. I'm currently taking a look.

**Comment by fadimounir** [comment]
> This fix caused some regressions in the R2R tests. I'm currently taking a look.

Fixed. This was due to the fact that when the runtime approximated the gc/non-gc module field layout for static fields, it treated valuetype RVA statics as boxed value types (only non-RVA valuetype statics are boxed). This created a difference between the layout in coreclr and crossgen2 with my previous fix attempt.

**Review by janvorli — APPROVED** [review]

**Pull request merged**
