### PR TITLE
[release/5.0-preview3] Fix System.Data.SqlClient baseline (#34352)

### PR DESCRIPTION
**Pull request by mmitche**
Fix the package baseline for Microsoft.Windows.Compatibility so that the System.Data.SqlClient dependency is 4.8.1

## Customer Impact
In preview1 and 2, Microsoft.Windows.Compatibility is dependent on System.Data.SqlClient 5.0.0-preview.X. System.Data.SqlClient is currently at 4.8.1, so this makes the package unusable.

## Regression?
Yes,

## Risk
Low, fix in master has been verified.

### CODE REVIEW

**Comment by danmosemsft** [comment]
Supportive. Is there a checklist we need to tweak to avoid this next time?

**Comment by ViktorHofer** [comment]
cc @jkotas

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by danmosemsft** [comment]
was approved

**Comment by ericstj** [comment]
> Is there a checklist we need to tweak to avoid this next time?

A checklist for deleting a library from the repo?  Not sure we have such a thing or if it happens often enough.

I do think we should test the compat pack during package testing.  @safern can you file an issue for that?  I suspect it's not being tested because it's not validated for support.

**Comment by ericstj** [comment]
Nevermind, we have that issue: https://github.com/dotnet/runtime/issues/27503

**Pull request merged**
