### PR TITLE
Anscoggi/fix arch

### PR DESCRIPTION
**Pull request by DrewScoggins**

### CODE REVIEW

**Comment by DrewScoggins** [comment]
I need to make this checkin directly instead of waiting for Arcade, as this is currently causing incorrect data to be injected into our Performance database. I have a PR in Arcade, here, to get this fixed the right way, but I need to move this forward before that.

**Comment by DrewScoggins** [comment]
@adiaaida @trylek

**Review by michellemcdaniel — APPROVED** [review]

**Comment by adiaaida** [comment]
I definitely didn't realize this was in the runtime repo. This will likely be overwritten when they take the next arcade update.

**Comment by DrewScoggins** [comment]
That is why I also have the arcade PR up. My hope is the next time we take the update that will have been checked in.

**Pull request merged**
