### PR TITLE
Added ? nullable annotation.

### LINKED ISSUE #44328: SMR DecodeSignature methods should have nullable ref on second parameter
The DecodeSignature method (here and perhaps on other classes) behave just fine with a null argument for the second parameter:

https://github.com/dotnet/runtime/blob/ae47aa26544227ef632598d91a798b8f83d56634/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/TypeSystem/MethodDefinition.cs#L66

There should be a `?` nullable ref annotation on this.

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
Added nullable `?` nullable.

Fixes https://github.com/dotnet/runtime/issues/44328

### CODE REVIEW

**Review by AArnott — APPROVED** [review]

**Comment by huoyaoyuan** [comment]
Do you have ref source updated?

https://github.com/dotnet/runtime/blob/894b730164d2f7bde661da448e10af367ed99639/src/libraries/System.Reflection.Metadata/ref/System.Reflection.Metadata.cs#L1373

I wonder why ApiCompat passes.

**Comment by AArnott** [comment]
Per @stephentoub's comment: https://github.com/dotnet/runtime/issues/44328#issuecomment-723656149

Please close this PR without merging.

**Comment by stephentoub** [comment]
Thanks, @MCCshreyas and @AArnott.

**Pull request closed without merging**
