### PR TITLE
JIT: Add a disabled-by-default loop peeling phase

### PR DESCRIPTION
**Pull request by jakobbotsch**
Add a phase that peels loops by duplicating their loop body once. No
heuristics are yet included, so this is only going to be enabled under
stress for now.

Based on #97506

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Hitting an assert on x86 with `JitStressRegs=0x80`. We have the following IR after LSRA:
```scala
------------ BB96 [0297] [00C..03A) -> BB92,BB03,BB14,BB17,BB11,BB20,BB91,BB91,BB93,BB40 (switch), preds={BB02} succs={BB03,BB11,BB14,BB17,BB20,BB40,BB91,BB92,BB93}
N071 (???,???) [002516] ----------Z                 t2516 =    LCL_VAR   int    V04 loc0          edx REG edx
N073 (???,???) [002517] -----------                 t2517 =    JMPTABLE  int    REG eax
N001 (  1,  1) [002789] ----------z                 u2789 =    LCL_VAR   int    V04 loc0          edi REG edi
                                                            ┌──▌  t2516  int    
                                                            ├──▌  t2517  int    
N075 (???,???) [002518] -----------                         ▌  SWITCH_TABLE void   REG NA
```

`[002789]` seems to be inserted for resolution. When codegen consumes `[002516] ` as part of generating the `SWITCH_TABLE` we hit the assert in the `if` here:
https://github.com/dotnet/runtime/blob/0f70e9aa5f08847680162a6dc712e069f0334b52/src/coreclr/jit/codegenlinear.cpp#L923-L930

@kunalspathak any idea?

**Comment by kunalspathak** [comment]
At the end of BB96, `V04` is marked as inActive and hence, `[002516]` is marked as `GT_SPILL`. During resolution, we see that most of the successors requires it to be present in `rdi`, so we add a resolution node `[002789]` from `rdi <- stk` 
```
BB96 bottom: move V04 from STK to edi (SharedCritical)
N001 (  1,  1) [002789] ----------z                 u2789 =    LCL_VAR   int    V04 loc0          edi REG edi
```
This gets added before the `GT_SWITCH` node:

https://github.com/dotnet/runtime/blob/fe51bd72fbe3948bbb895ca8788aea5fc9a6463a/src/coreclr/jit/lsra.cpp#L8430-L8441

During codegen, throughout `BB96`, `V04` was present in `rdx`, while `[002789]` needs it to be in `rdi`. We try to consume the registers for that node, and we do a move from `V04` to `treeNode` i.e. `rdi <- rdx`. Then, we unspill the register from stack (which is the reason `[002789]` was added in first place) into `rdi` and set `V04` to be in `rdi` going forward. This gives us:

```asm
Generating: N001 (  1,  1) [002789] ----------z                 u2789 =    LCL_VAR   int    V04 loc0          edi REG edi
IN000b:        mov      edi, edx <-- can be eliminated??
IN000c:        mov      edi, dword ptr [V04 ebp-0x10]
```

(I think the first `mov` instruction can be eliminated if we check [here](https://github.com/dotnet/runtime/blob/fe51bd72fbe3948bbb895ca8788aea5fc9a6463a/src/coreclr/jit/codegenlinear.cpp#L1506-L1509) that it will be anyway get overwritten from unspilling. But that's a separate topic.)

Next, we 

```
                                                                        ┌──▌  t2516  int    
                                                                        ├──▌  t2517  int    
Generating: N075 (???,???) [002518] -----------                         ▌  SWITCH_TABLE void   REG NA
IN000d:        mov      edx, edi
IN000e:        mov      dword ptr [V04 ebp-0x10], edx
							V04 in reg edi is becoming dead  [002516]
							Live regs: 000000CC {edx ebx esi edi} - {edi} => 0000004C {edx ebx esi}

**Comment by jakobbotsch** [comment]
> the resolution should happen after the last use of `V04` in block `BB96`. The last use is `[002516]` after which it gets spilled to the stack.

I guess the problem is we can't really make that happen, since the relative ordering of `[002516]` and `[002789]` does not matter -- `[002516]` is being handled as part of codegen of the `SWITCH_TABLE`, so only the ordering of `[002789]` and the `SWITCH_TABLE` matter (and they cannot be reordered).

One thing that might be insightful is to figure out how the same situation gets handled for `BBJ_COND` on arm64. On arm64 we have many `BBJ_COND` blocks with terminator statements that have locals in them due to the "branch if zero" instruction that exists there.

Initially I thought the handling was happening here:
https://github.com/dotnet/runtime/blob/b76ef7fa73c758daaa663a4d36d78d536df152fe/src/coreclr/jit/lsra.cpp#L8874-L8887

The `BBJ_SWITCH` case above misses some of the handling around locals that the `BBJ_COND` case has. However, when I tried duplicating the logic for `BBJ_SWITCH` it didn't fix the problem.

**Comment by kunalspathak** [comment]
>  so only the ordering of [002789] and the SWITCH_TABLE matter (and they cannot be reordered).

Exactly.

> The BBJ_SWITCH case above misses some of the handling around locals that the BBJ_COND case ha

Yes, I was wondering about that too last night. I tried a prototype and that seems to solve the problem. I have sent out https://github.com/dotnet/runtime/pull/97713 to see the results of superpmi-replay .

**Pull request closed without merging**
