### PR TITLE
Fixed #44343 by including Name in GetHashCode of Font

### LINKED ISSUE #44343: System.Drawing.Font.GetHashCode() return is not unique because it does not include the fontName
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/SystemDrawingFontGetHashCode-return/998779)._

---
<p>System.Drawing.Font.GetHashCode hashes the fontStyle, fontUnit, and fontSize, but does not hash the fontName.     Thus, New Font(&quot;Arial&quot;, 16, FontStyle.Bold, GraphicsUnit.Point). GetHashCode() returns the same value as New Font(&quot;Lucida Sans Unicode&quot;, 16, FontStyle.Bold, GraphicsUnit.Point). GetHashCode()</p>

---
#### Feedback Bot on 4/20/2020, 08:19 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/28/2020, 08:00 PM: 

I have detected that for the last 35 days, this issue didn't have much product team activity and a very small amount of new votes or comments. Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Dada Huo [MSFT] on 11/3/2020, 00:29 AM: 

<p>Thank you for taking the time to log this issue! Did you still reproduce this issue in the latest stable version of Visual Studio installed from <a target='_blank' href="https://visualstudio.microsoft.com/downloads">https://visualstudio.microsoft.com/downloads</a> ?<br>
If so, in order for us to investigate this further, could you please provide repro steps, a more detailed description of the faulty behavior and the actions you were taking when the issue appeared to help us better understand this scenario? It would be very helpful if you could provide some screenshots.<br>
We look forward to hearing from you!</p>

#### Peter Knibbe on 11/5/2020, 07:03 AM: 

<p>Yes. I took the time to build a small project that demonstrates the behavior. Here is the code and I have attached a screenshot.</p>
<p>Public Class Form1<br>
Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click</p>
<pre><code>    Dim fmss = New Font(&quot;Microsoft Sans Serif&quot;, 12)
    Dim bsmt = New Font(&quot;Brush Script MT&quot;, 12)

    Dim match As Boolean = (fmss.GetHashCode() = bsmt.GetHashCode())
    Label3.Text = $&quot;The two fonts {If(match, &quot;&quot;, &quot;do not &quot;)} have the same hash code.&quot;
End Sub
</code></pre>
<p>End Class</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by iSatishYadav**

### CODE REVIEW

**Comment by safern** [comment]
Can you add a test to validate that the hash code in between 2 fonts with a different name is not the same? That test should've failed before making this change.

**Comment by danmosemsft** [comment]
Hello @iSatishYadav do you expect to be able to add the test? With a test, we can merge this.

**Comment by iSatishYadav** [comment]
> Hello @iSatishYadav do you expect to be able to add the test? With a test, we can merge this.

Hi, @danmosemsft! I was not able to build the repo locally. I'll try again.

**Comment by safern** [comment]
Closing in favor of: https://github.com/dotnet/runtime/pull/46816

**Pull request closed without merging**
