### PR TITLE
[mono][jit] Reenable branch optimizations when running with llvm.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by vargaz** [comment]
This PR will reduce both executable size and aot compiler memory usage by eliminating code early. Previously, we were only running branch optimizations in opt/llc, so if we had code like:
if (Vector.IsSupported) <vector code>
the aot compiler couldn't figure out that <vector code> was not needed, so it ended up generating a lot of extra vector generic instances.

**Comment by vargaz** [comment]
This saves around 120k on an aot hello world on wasm.

**Comment by vargaz** [comment]
Failures are probably unrelated, the llvm lanes are timing out.

**Review by kg — APPROVED** [review]
I assume the changes to `lhs` are to fix crashes you hit while doing this. Looks fine to me.

**Pull request merged**
