### PR TITLE
AOT ILC using a LKG bits

### PR DESCRIPTION
**Pull request by LakshanF**
First draft of using a native AOT ILCompiler and builds on PR #73987 by importing the AOT target file, which will trigger publishing an AOT version of ILC.

The target, `RewriteRuntimePackDir`, is not used as is done by the [crossgen2 package](https://github.com/dotnet/runtime/blob/main/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Crossgen2.sfxproj#L42) with this change. That will trigger using the [runtime packages](https://github.com/dotnet/runtime/blob/main/src/coreclr/tools/aot/crossgen2/crossgen2.csproj#L52-L64) as done by `crossgen2 `but want to get a read of the LKG changes first.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Why do we need to use live ILCompiler targets if we want to use the LKG build? Why not just set PublishAot instead of what we have there now (SingleFile+Trimmed+ReadyToRun)?

**Comment by LakshanF** [comment]
> Why do we need to use live ILCompiler targets if we want to use the LKG build? Why not just set PublishAot instead of what we have there now (SingleFile+Trimmed+ReadyToRun)?

Makes sense to first do AOT with the LKG build.

**Comment by MichalStrehovsky** [comment]
> Makes sense to first do AOT with the LKG build.

It was the title of this pull request :).

I think all of these changes should still go into the `<!-- BEGIN: Workaround for https://github.com/dotnet/runtime/issues/67742 -->` section (and the comment should not be deleted).

Using LKG is still just a workaround for #67742. The real fix would be doing the RunningPublish and all the other stuff that is necessary to use live bits. We would not be publishing into `$(RuntimeBinDir)ilc-published` as part of the clr partition build either because we don't have the libs to do that. It's all just workarounds.

**Comment by LakshanF** [comment]
> Thinking about this more - what do we get from this exercise? We needed the R2R trimmed singlefile stopgap because we were about to ship 7.0 and the ILCompiler nuget package was huge and slow to start. The stopgap got us halfway there.
> 
> Now we have more time to do the real fix (put things on the same plan as crossgen2 where we produce the bits with the live compiler in the installer partition build). What do we expect to gain from this temporary switchover?

Good point! I've also been thinking that its better to do the full fix and will close this PR

**Pull request closed without merging**
