### PR TITLE
Pick up a new build of Xunit

### PR DESCRIPTION
**Pull request by ericstj**
This is the latest pre-release of Xunit 2.x.  It contains updated asserts library and manually updated to the latest analyzers.

The analyzers found some new issues with our tests, which I have fixed.  There are a few issues I worked around.

xunit/xunit#2393
xunit/xunit#2394
xunit/xunit#2395

Reviewable commit-by-commit.

### CODE REVIEW

**Review by safern — APPROVED** [review]
LGTM

**Comment by ericstj** [comment]
Looks like there was a breaking change in `Assert.Throws<ArgumentException>`.  https://github.com/xunit/xunit/issues/2396

Will need to see if we can workaround this or not.

**Review by maryamariyan — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]
LGTM. Reminds me of when we had to do this back when v2 was actively developed.

**Comment by ericstj** [comment]
Ok, that's this issue: https://github.com/xunit/xunit/issues/2402

Not seeing an easy workaround at the moment.  I'll see if we can make a fix to xunit.

**Review by danmoseley — APPROVED** [review]

**Comment by ericstj** [comment]
Closing this for now, Will need to merge a fix and pick up a new build to proceed.

**Pull request closed without merging**
