### PR TITLE
[mono] Assume C99 support

### PR DESCRIPTION
**Pull request by CoffeeFlux**
We don't seem to have been setting this define properly, but we can just remove the ifdef entirely

### CODE REVIEW

**Comment by lambdageek** [comment]
We might be better off using the `#else` definitions of all that stuff.  The C99 standard variadic macros are a mess <https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html> that don't expand how you want anyway. 

I think we could put a `MONO_ATTR_FORMAT_PRINTF` on `g_log` and get the benefit of warnings if the format string is incorrectly specified).

**Comment by vargaz** [comment]
Older msvc versions didn't have c99 support, newer ones might have it.

**Comment by tannergooding** [comment]
> newer ones might have it.

AFAIK it still doesn't and things like `_Complex` and `variable length arrays` are still not supported.

**Comment by CoffeeFlux** [comment]
I believe they've committed to supporting all required C11 features, but that does mean some of the C99 stuff like VLAs isn't supported (since they were made optional).

Also seeing the build failures, I'm almost certainly just going to switch to the `#else` definitions here. I just haven't had a chance to update the PR.

**Review by lambdageek — APPROVED** [review]

**Pull request merged**
