### PR TITLE
Fix Type.GetFields() after EnC/Hot reload update

### PR DESCRIPTION
**Pull request by mikem8361**
Switch to the EncApproxFieldDescIterator in the GetFields() FCall.

Issue: #51517

Added MethodDesc::ResetCodeEntryPointForEnC() that reset the entry point without
the asserts that caused the problem.

Introduced in the fix for #50445.

### CODE REVIEW

**Comment by jkotas** [comment]
Build breaks. LGTM otherwise.

**Review by jkotas — APPROVED** [review]

**Comment by mikem8361** [comment]
I changed my test case to also add a method to the test type and under debug hit this assert. In a release build, the method seems to be added according to type.GetMethods() after the ApplyUpdate.

```
Assert failure(PID 46692 [0x0000b664], Thread: 22348 [0x574c]): ! IsEnCAddedMethod() || !"Cannot get slot for method added via EnC"

CORECLR! MethodDesc::GetSlot + 0x50 (0x00007ffd`5c7aa650)
CORECLR! MethodDesc::IsVirtualSlot + 0x30 (0x00007ffd`5c7e0b20)
CORECLR! MethodDesc::IsVtableSlot + 0x30 (0x00007ffd`5c7e0b90)
CORECLR! MethodDesc::SetTemporaryEntryPoint + 0x5D (0x00007ffd`5caab2ad)
CORECLR! EEClass::AddMethod + 0x6E4 (0x00007ffd`5c8a01f4)
CORECLR! EditAndContinueModule::AddMethod + 0x392 (0x00007ffd`5c97d372)
CORECLR! EditAndContinueModule::ApplyEditAndContinue + 0xB00 (0x00007ffd`5c97eff0)
CORECLR! AssemblyNative::ApplyUpdate + 0x3F4 (0x00007ffd`5cc58cd4)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x00007ffd`6c26e9cf)
<no module>! <no symbol> + 0x0 (0x00007ffc`fe399747)
    File: C:\ssd\runtime\src\coreclr\vm\method.hpp Line: 1084
    Image: c:\sd\builds\dotnet\dotnet.exe
```

Is this assert in GetSlot() accurate since it seems to work in release?

```
//==================================================================
    // The slot number of this method in the corresponding method table.
    //
    // Use with extreme caution.  The slot number will not be
    // valid for EnC code or for MethodDescs representing instantiation
    // of generic methods.  It may also not mean what you think it will mean
    // for strange method descs such as BoxedEntryPointStubs.
    //
    // In any case we should be moving to use slot numbers a lot less
    // since they make the EE code inflexible.

    inline WORD GetSlot()
    {
        LIMITED_METHOD_DAC_CONTRACT;
#ifndef DACCESS_COMPILE
        // The DAC build uses this method to test for "sanity" of a MethodDesc, and
        // doesn't need the assert.
        _ASSERTE(! IsEnCAddedMethod() || !"Cannot get slot for method added via EnC");
#endif // !DACCESS_COMPILE

        // Check if this MD is using the packed slot layout
        if (!RequiresFullSlotNumber())
        {
            return (m_wSlotNumber & enum_packedSlotLayout_SlotMask);
        }

        return m_wSlotNumber;
    }
```

**Comment by jkotas** [comment]
It is regression introduced by https://github.com/dotnet/runtime/commit/7d6c1a52d903d5af6b1d6d56521400678191a9c0#diff-9803aaaa063f4a7b743e0e5b0e4f1400d2cdf719862896b33f78f82fa4e8cf10R4723 . I think you can just delete the assert.

**Review by stephentoub — APPROVED** [review]

**Comment by devsko** [comment]
Hi @mikem8361 . I tried to verify this fix for my use case with a local build. 
The behavior now is as follows:
- Loaded class with 7 public fields
- Adding an 8th public field
- Update via EnC and clear cache without any problem
- `type.GetFields()` now returns 
    * 7 original fields
    * 1 new field
    * 3 of the original fields twice (with different field handle)

**Comment by devsko** [comment]
I found a minimal repro for this. Key is that the class contains a field of type `nint` or `nuint` before the edit. 
I created https://github.com/devsko/WebApplication1. 
- dotnet watch it
-  uncomment the second field in Class1 and 
- refresh your browser to reproduce.

**Pull request merged**
