### PR TITLE
proposed fix #33727 for illegal instruction in arm

### LINKED ISSUE #33727: SIGILL's on ARM32 while using valgrind
Hi all,

I am currently debugging an application with valgrind in a raspberry pi and I came across some "Illegal Instructions" issues on "libcoreclr.so".

Not sure if these instructions are actually being executed, however, as they are being detected by valgrind, an "Illegal Instruction" signal is being raised.

See the messages below:

The first one concerns to sub.w instruction: SP is being used in Rd position and r8 in Rn (according to the ISA, if SP is being used as Rd, SP should also be in Rn, see http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0552a/BABFFEJF.html).

done.
0x04000a30 in _start () from /lib/ld-linux-armhf.so.3
(gdb) c
Continuing.
[New Thread 17257]

Thread 1 received signal SIGILL, Illegal instruction.
0x05f837fe in _DacGlobals::InitializeEntries(unsigned int) () from /home/pi/workspace-00032/edge/libcoreclr.so
(gdb) x/i $pc
   0x5f837ff <_ZN11_DacGlobals17InitializeEntriesEj+3262>:      sub.w   sp, r8, #80     ; 0x50

I managed to bypass this SIGILL by patching valgrind, explicitly allowing this constraint (this probably shouldn`t be done). However, another SIGILL was raised, but this time it was located elsewhere.  

(gdb) c
Continuing.
[New Thread 4291]

Thread 1 received signal SIGILL, Illegal instruction.
0x23f7d48e in ?? ()
(gdb) x/i $pc
   0x23f7d48f:  ldmia.w sp!, {lr}
(gdb)

Apparently, this one concerns to the use of only one register in the register list in instruction LDMIA. For more information, see: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0489g/Cihcadda.html.

I wonder if these instructions are being emmited by the JIT compiler, or maybe this is a CLANG issue.

Thanks in advance!

PS:
more info about my environment:

First, I am running a container to publish my app. The app publishing process is located in build.sh.

docker run -v %ProductContainersFolder%:/product_containers  --rm mcr.microsoft.com/dotnet/core/sdk:3.1 bash /product_containers/build.sh

The "dotnet publish" command is described below:

dotnet publish -c Release --framework netcoreapp3.1 -r linux-arm --self-contained yes --output  .....

After publishing the app, I`m copying the whole environment (app+runtime+libs including libcoreclr.so) to my raspberry to run it there. 

It's important to note that, if I don`t use valgrind, my application runs without problems on raspberry.

category:correctness
theme:codegen
skill-level:beginner
cost:small

### PR DESCRIPTION
**Pull request by oldzhu**
Fix for arm illegal instruction  ldmia.w sp!, {lr} (0xe8bd0000)
tested and worked in local testing.
before the fix:
~~~
249c: 01 b4            push    {r0}
249e: 00 b5            push    {lr}
24a0: 01 98            ldr     r0, [sp, #4]
24a2: 40 f0 00 50      orr     r0, r0, #536870912
24a6: bd e8 00 40      ldm.w   sp!, {lr}     // illegal instruction 
24aa: 01 b0            add     sp, #4
24ac: 70 47            bx      lr
~~~
after the fix:
~~~
249c: 01 b4            push    {r0}
249e: 00 b5            push    {lr}
24a0: 01 98            ldr     r0, [sp, #4]
24a2: 40 f0 00 50      orr     r0, r0, #536870912
24a6: 5d f8 04 eb      ldr     lr, [sp], #4   //correct T2_E2 encoding
24aa: 01 b0            add     sp, #4
24ac: 70 47            bx      lr
~~~

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=55502) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=55502) before we can accept your contribution.<br/><br/>:x: oldzhu [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=55502)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=55502) it.</sub>

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
> 24a6: 5d f8 04 eb      ldr     lr, [sp], #4   //correct T2_E2 encoding

Looks like we generate that bit pattern but disassemble to:

> 00001A  F85D EB04      pop     lr

Which is (in the manual I'm looking at) "A8.8.131 POP (Thumb), Encoding T3". Is `ldr lr, [sp], #4` just a pseudo-instruction, or has the same encoding? I couldn't find a `ldr` encoding that would be equivalent.

Anyway, this does look correct.

**Review by BruceForstall — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
