### PR TITLE
[wasm] Move microbenchmarks, and blazor SOD runs to net8.0

### PR DESCRIPTION
**Pull request by radical**
- Use `dotnet-latest` instead of `dotnet-net7+latest` for running benchmarks. The former only has `wasm-tools` workload installed. And is sufficient for net8.0 projects, and would break any projects trying to build for net7.0 .
- Fix up blazor timeout to increase from the default 5mins to 30mins, since the AOT ones (template) are taking longer
- Various changes to help with diagnostics, and debugging

### CODE REVIEW

**Comment by radical** [comment]
Also waiting on [dotnet-runtime-perf run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2086792&view=results).

**Review by lewing — APPROVED** [review]

**Comment by radical** [comment]
All the wasm jobs passed on https://dev.azure.com/dnceng/internal/_build/results?buildId=2087129&view=results . Except for one AOT job that had a timeout during AOT. That does not need to block this PR though. I'll investigate it separately.

**Comment by radical** [comment]
Other failures here are unrelated. Merging.

**Pull request merged**
