### PR TITLE
Add path filters to runtime.yml triggers

### PR DESCRIPTION
**Pull request by safern**
Reported in: https://github.com/dotnet/runtime/pull/537

### CODE REVIEW

**Review by trylek — APPROVED** [review]
Ahh, thanks for fixing my omission!

**Comment by safern** [comment]
I'm also including another change in this PR to exclude runtime.yml from other pipelines, so that if we only touch runtime.yml they are not triggered.

**Comment by trylek** [comment]
Good idea, thanks for doing that!

**Review by jashook — APPROVED** [review]

**Review by ViktorHofer — COMMENTED** [review]
thanks

**Pull request merged**
