### PR TITLE
Seal nested classes

### PR DESCRIPTION
**Pull request by davidfowl**
Fixes https://github.com/dotnet/efcore/blob/36dd65ca8c309541e53a4b5a2f2124db5695fda6/test/EFCore.Design.Tests/DesignApiConsistencyTest.cs#L30

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by davidfowl** [comment]
@danmoseley can we turn auto merge on for this repo?

**Comment by eerhardt** [comment]
> can we turn auto merge on for this repo?

We use the 'auto-merge' label. To use GitHub's auto-merge feature we would need to make the `runtime` CI leg "required", which means only admins could merge PRs when the `runtime` CI leg failed.

**Review by eerhardt — APPROVED** [review]

**Comment by davidfowl** [comment]
I see

**Comment by davidfowl** [comment]
What is going on with the builds...

**Pull request merged**
