### PR TITLE
Remove internal NuGet.config that is not needed anymore

### PR DESCRIPTION
**Pull request by safern**
This is no longer needed as we moved to use the nuget authentication plugin:
https://github.com/dotnet/runtime/blob/72b7d236ad634c2280c73499ebfc2b594995ec06/eng/pipelines/common/restore-internal-tools.yml#L2

And the restore sources are specified in:
https://github.com/dotnet/runtime/blob/72b7d236ad634c2280c73499ebfc2b594995ec06/eng/common/internal/Tools.csproj#L15-L24

Official build test: https://dev.azure.com/dnceng/internal/_build/results?buildId=882076&view=results

### CODE REVIEW

**Comment by safern** [comment]
Restore internal tools step is green in some legs that already ran it: https://dev.azure.com/dnceng/internal/_build/results?buildId=882076&view=logs&j=d1c61015-de25-57ee-85fb-2d3ab25a5b85&t=9ac5eefd-1bb2-5bc7-16cf-c7f7c2ca696f

**Review by stephentoub — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]
Awesome if it works

**Comment by safern** [comment]
This only affects official build and the test official build is green.

**Comment by ViktorHofer** [comment]
Just wondering, do we have tracking issues for the failing Android legs and the one libraries test?

**Comment by safern** [comment]
That is exactly what I'm looking at the moment 😄

**Comment by safern** [comment]
The Android failures are: https://github.com/dotnet/runtime/issues/43873
The IO test failure is: https://github.com/dotnet/runtime/issues/24181

**Pull request merged**
