### PR TITLE
JIT: Split out call importation into new importercalls.cpp

### PR DESCRIPTION
**Pull request by jakobbotsch**
No code changes yet, purely moving the code.

### CODE REVIEW

**Comment by EgorBo** [comment]
we already have `importer_vectorization.cpp` should we have `importer_call.cpp` ?

**Comment by jakobbotsch** [comment]
> we already have `importer_vectorization.cpp` should we have `importer_call.cpp` ?

Most of the JIT files do not use underscores as separators so I'm not really sure. Seems like `importer_vectorization` is the odd one out.

**Comment by jakobbotsch** [comment]
Maybe we should rename `importer_vectorization.cpp` -> `stringintrinsics.cpp` to make it consistent with `hwintrinsics.cpp`?

**Comment by EgorBo** [comment]
> > we already have `importer_vectorization.cpp` should we have `importer_call.cpp` ?
> 
> Most of the JIT files do not use underscores as separators so I'm not really sure. Seems like `importer_vectorization` is the odd one out.

Feel free to fix that but currently it looks inconsistent. I'd prefer %phase name%%what it does% -- similar to LLVM: https://github.com/llvm/llvm-project/tree/main/llvm/lib/Transforms/InstCombine `InstCombine` phase splitted to `InstCombineCalls`, `InstCombineCasts`, etc

**Comment by EgorBo** [comment]
And honestly, I hate `hwintrinsics.cpp` its name doesn't tell if it's Importer-phase related code or codegen or lower 🙂

**Comment by jakobbotsch** [comment]
How about I just rename `importer_vectorization.cpp` -> `importervectorization.cpp`, `importcall.cpp` -> `importercalls.cpp` and `register_arg_convention` -> `registerargconvention`?

**Comment by EgorBo** [comment]
> How about I just rename `importer_vectorization.cpp` -> `importervectorization.cpp`, `importcall.cpp` -> `importercalls.cpp` and `register_arg_convention` -> `registerargconvention`?

Works for me (although I'd prefer capital letters but it's against our guidelines for file names I assume) 👍 maybe someone from @dotnet/jit-contrib have a different opinion?

**Comment by jakobbotsch** [comment]
This change shows some differences in diff algorithms:
```scala
❯ git diff 79a78728bd40ae917^..79a78728bd40ae917 --diff-algorithm=myers --shortstat -- .\src\coreclr\jit\importer.cpp
 1 file changed, 8765 insertions(+), 16568 deletions(-)
```

```scala
❯ git diff 79a78728bd40ae917^..79a78728bd40ae917 --diff-algorithm=histogram --shortstat -- .\src\coreclr\jit\importer.cpp
 1 file changed, 7803 deletions(-)
```

Unfortunately I'm not sure if Git today supports using a different diff algorithm than Myers for `git blame`/`git log -L`.

**Comment by am11** [comment]
A typical way to retain history is to keep the rename and code change commits separate, and merge the PR without squashing (or split file renames into a separate PR).

**Comment by jakobbotsch** [comment]
> A typical way to retain history is to keep the rename and code change commits separate, and merge the PR without squashing (or split file renames into a separate PR).

I am not just renaming a file here, I am splitting `importer.cpp` into `importer.cpp` and `importercalls.cpp`. There are no code changes, the problem is that Git's default diff algorithm does not realize that I am just deleting code in `importer.cpp` and for some reason thinks I am changing the deleted functions into differently named functions from later in the file.

I tried splitting the delete in two commits where the first commit left all comments as sort of "anchors" and the second commit then deleted all the comments. Indeed this would then have to be rebased in. Unfortunately the same problem just happens in the second commit, with Git's default diff algorithm believing I am changing the comments I am deleting into code from later in the file.

**Comment by jakobbotsch** [comment]
I'm trying now to see if I can do the move in a few chunks instead to convince the diff algorithm so that `git blame`/`git log -L` will continue working properly (on at least the remaining importer code, and hopefully on the moved code too with some of the args meant for that).

**Comment by tannergooding** [comment]
@jakobbotsch, feel free to rename `hwintrinsic.cpp` to `importhwintrinsic.cpp` as well.

We might want to decide how to do cases like `hwintrinsiccodegenxarch.cpp` in that it could be either `codegenxarchhwintrinsic.cpp` or `codegenhwintrinsicxarch.cpp`.

Also just noting, as names get longer like this, I think that the `_` might help with readability and discoverability of files. Not a huge preference, just noting that since its all lower `codegenxarchhwintrinsic` is harder to read than `codegen_xarch_hwintrinsic.cpp`

**Comment by jakobbotsch** [comment]
hwintrinsic.cpp does seem to have some functions that are not related to importation, e.g. `Compiler::vnEncodesResultTypeForHWIntrinsic`. I think I'll leave it as is for now, we can do follow-up changes if we want to make things more consistent or change the file name conventions.

**Comment by jakobbotsch** [comment]
Ok, moving the functions in batches seems to have worked out, Git properly tracks the deletions in the individual commits. Now we'll just need to rebase/merge this PR.

**Comment by AndyAyersMS** [comment]
> Ok, moving the functions in batches seems to have worked out, Git properly tracks the deletions in the individual commits. Now we'll just need to rebase/merge this PR.

Are you planning on not squashing this?

I have some edits for `impCheckCanInline` in a local branch, will be interesting to see if they can make it into the new location. When I split up flowgraph.cpp it was one big commit and git could not figure out what went where.

**Comment by AndyAyersMS** [comment]
I suppose I can pull down your changes and rebase what I have on top of that.

**Comment by jakobbotsch** [comment]
> Are you planning on not squashing this?
> 
> I have some edits for `impCheckCanInline` in a local branch, will be interesting to see if they can make it into the new location. When I split up flowgraph.cpp it was one big commit and git could not figure out what went where.

Yes, that would be the plan. But I don't think Git can figure the code move out automatically, unfortunately. 
But at least Git is not going to think I touched the remaining parts of the importer in this PR.

**Review by AndyAyersMS — APPROVED** [review]

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib, any final thoughts?

**Comment by stephentoub** [comment]
rebased and merged per @jakobbotsch's request

**Pull request merged**
