### PR TITLE
Use static abstract interface methods in SymbolicRegexMatcher

### PR DESCRIPTION
**Pull request by stephentoub**
@tannergooding, @davidwrighton, any reason not to start relying on static abstract interface methods?

cc: @joperezr, @olsaarik

### CODE REVIEW

**Comment by tannergooding** [comment]
@stephentoub, still waiting on some Mono and Crossgen2 fixes before we can: https://github.com/dotnet/runtime/pull/60905#issuecomment-953024159
* https://github.com/dotnet/runtime/issues/49904
* https://github.com/dotnet/runtime/pull/54063

CC. @lambdageek, @akoeplinger

**Comment by stephentoub** [comment]
Thanks, Tanner.  Presumably CI will fall over with this then? :smile:

**Comment by stephentoub** [comment]
> still waiting on some Mono and Crossgen2 fixes before we can

From @lambdageek's comments on the other issue, it seems like this isn't a problem as it relates to this PR (which doesn't try to take the address of such a method).  What about crossgen2?  CI passed; does that mean we're not crossgen'ing these assemblies as part of this build, or that any such use will cause crossgen to fail and we simply then always JIT that assembly, or something else?

**Comment by tannergooding** [comment]
> What about crossgen2

@jkotas ?

**Comment by jkotas** [comment]
> does that mean we're not crossgen'ing these assemblies as part of this build,

Right, libraries CI tests are not crossgening anything under libraries.

I expect that we will see outer loop crossgen legs failing at least. We may see other failure modes as well, not sure.

I think we really need to finish the crossgen support before we start using this feature in libraries.

**Comment by stephentoub** [comment]
> I think we really need to finish the crossgen support before we start using this feature in libraries.

That's fine. Do we know when that will happen? If soon,  I'll leave this open. Otherwise,  I'll close it.

**Comment by stephentoub** [comment]
This isn't actionable right now.  Will revisit once crossgen supports it.

**Pull request closed without merging**
