### PR TITLE
update crossfs for FreeBSD 12.2

### PR DESCRIPTION
**Pull request by wfurt**
pick up changes from new roots and OS updates. 

cc: @jasonpugsley @Thefrank @josteink

### CODE REVIEW

**Comment by Thefrank** [comment]
LGTM!
image contains FreeBSD 12.2 crossroot with terminfo pkg

**Review by josteink — APPROVED** [review]
LGTM

**Comment by josteink** [comment]
That's a few good reviews, but none of our votes "count", since none of us have write access to the dotnet repos.

Maybe @jkotas could assist?

**Review by ViktorHofer — APPROVED** [review]

**Comment by josteink** [comment]
I guess that means you are ready to merge @wfurt 😃

**Comment by ViktorHofer** [comment]
> I guess that means you are ready to merge @wfurt 😃

When the build is green or when unrelated test failure have been reported according to our [PR guide](https://github.com/dotnet/runtime/blob/main/docs/pr-guide.md#what-to-do-if-you-determine-the-failure-is-unrelated).

**Comment by jkotas** [comment]
All failures are unrelated infrastructure problems:

- error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json.

- Failed to upload results: Error occurred in request., ConnectionError: HTTPSConnectionPool(host='dev.azure.com', port=443): Max retries exceeded with url: /dnceng/public/_apis/test/Runs/39924850/Results (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04E1EC28>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

**Comment by jkotas** [comment]
https://github.com/dotnet/core-eng/issues/14404

**Comment by josteink** [comment]
> https://github.com/dotnet/core-eng/issues/14404

That links to a private repo, but I’ll take your word for it 😃

**Pull request merged**
