### PR TITLE
Implement concept of unstable ABI into crossgen2

### LINKED ISSUE #13522: [crossgen2] Making sure Vector64/128/256 are not generated unless CoreLib is part of the version bubble

### PR DESCRIPTION
**Pull request by davidwrighton**
- Use for the Vector types based on current defined stability rules
- Will prevent compilation of methods with not yet stable abis, or calls to methods with said unstable apis

Fixes #13522

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
We're already doing something similar for `Vector<T>`: we basically just say that the layout in `Indeterminate` and there's code checking for that that aborts crossgening the method whenever a piece of layout info is needed and it ends up Indeterminate.

Do we need to introduce a new general purpose mechanism here? Could we just have a FieldLayoutAlgorithm that returns `Indeterminate` layout for these same as for `Vector<T>` but only do it if the version bubble doesn't include CoreLib?

Cc @dotnet/crossgen-contrib

**Review by janvorli — APPROVED** [review]
It looks ok, but I wonder about the same thing that @MichalStrehovsky said. It seems it would make the change more local.

**Comment by davidwrighton** [comment]
Unfortunately, making the types have indeterminate size also prevents usage of the Vector intrinsics. This approach allows the intrinsics to continue to work and use the Vector128/256 types while simultaneously not permitting these apis to cross an ABI boundary.

**Comment by janvorli** [comment]
Makes sense.

**Review by MichalStrehovsky — APPROVED** [review]

**Pull request merged**
