### PR TITLE
JIT: fix inliner profile consistency computation

### LINKED ISSUE #109657: Libraries jitstress: Assertion failed 'target->hasProfileWeight()'
Many tests failing with
```
Assert failure(PID 4380 [0x0000111c], Thread: 944 [0x03b0]): Assertion failed 'target->hasProfileWeight()' in 'System.Security.Cryptography.X509Certificates.Tests.X509CertificateLoaderTests:LoadCertificate_WithTrailingData():this' during 'Morph - Inlining' (IL size 143; hash 0x69436fb7; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\fginline.cpp:675
    Image: C:\h\w\B576099D\p\dotnet.exe
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=864401&view=ms.vss-test-web.build-test-results-tab

### LINKED ISSUE #109730: JIT: libraries jitstress AV failures
See eg https://dev.azure.com/dnceng-public/public/_build/results?buildId=867258&view=ms.vss-test-web.build-test-results-tab

windows x64 jitstress 2 (and many others)

```
DOTNET_JitStress=2
DOTNET_TieredCompilation=0

... 

C:\h\w\A30E091D\w\B1B8091D\e>"C:\h\w\A30E091D\p\dotnet.exe" exec --runtimeconfig System.Text.Json.Tests.runtimeconfig.json --depsfile System.Text.Json.Tests.deps.json xunit.console.dll System.Text.Json.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 8722 of 8789 test cases)
  Starting:    System.Text.Json.Tests (parallel test collections = on [4 threads], stop on fail = off)
Fatal error. 0xC0000005
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
It's possible for the JIT to inline a profiled inlinee into an unprofiled context, and then have a subsequent inline fold a profiled branch. If so we may see a case where the folded edges don't have profile information.

Tolerate this.

Fixes #109657

Re-morphing of a statement during early-prop may mistakenly believe it has altered the flow graph and so invalidates DFS. Value numbering is not set up to handle this and crashes. Since this seems like a rare occurrence, have morph detect if it has really changed the flowgraph and avoid invalidating the DFS when it hasn't.

Fixes #109730

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 
@amanasifkhalid PTAL

There is some other libraries jitstress issue, so it still may not run cleanly.

**Review by amanasifkhalid — APPROVED** [review]
LGTM, thanks!

> There is some other libraries jitstress issue, so it still may not run cleanly.

Do you know if there's an issue already tracking this? I'm seeing quite a few tests fail with AVs.

**Comment by AndyAyersMS** [comment]
Not sure why build analysis is unhappy here...

**Comment by amanasifkhalid** [comment]
> Not sure why build analysis is unhappy here...

I suspect it's because there aren't tracking issues for the timeouts, and opening a meta-issue to capture all timeouts isn't ideal.

**Comment by AndyAyersMS** [comment]
I added a fix for the AVs, so let's see if libraries jit stress is now happy.

s

**Review by amanasifkhalid — APPROVED** [review]
AV fix LGTM

**Comment by AndyAyersMS** [comment]
Jitutils build is failing, wonder if 6.0 packages are no longer findable? 6.0 is out of support now.

```
Determining projects to restore...
/__w/runtime/runtime/jitutils/src/jit-dasm/jit-dasm.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-x64 with version (= 6.0.36)
/__w/runtime/runtime/jitutils/src/jit-dasm/jit-dasm.csproj : error NU1102:   - Found 1562 version(s) in dotnet7 [ Nearest version: 7.0.0-alpha.1.21[41](https://github.com/dotnet/runtime/actions/runs/11804422106/job/32884591447?pr=109714#step:5:42)7.28 ]
/__w/runtime/runtime/jitutils/src/jit-dasm/jit-dasm.csproj : error NU1102:   - Found 174 version(s) in dotnet-public [ Nearest version: 7.0.0-preview.1.22076.8 ]
/__w/runtime/runtime/jitutils/src/jit-dasm/jit-dasm.csproj : error NU1102:   - Found 0 version(s) in dotnet-libraries
/__w/runtime/runtime/jitutils/src/jit-dasm/jit-dasm.csproj : error NU1102:   - Found 0 version(s) in myget-legacy
  Failed to restore /__w/runtime/runtime/jitutils/src/jit-dasm/jit-dasm.csproj (in 1.28 sec).
```

**Comment by AndyAyersMS** [comment]
libraries-jitstress still not clean:
```
Assert failure(PID 4116 [0x00001014], Thread: 9356 [0x248c]): Assertion failed 'doesVNMatch' in 'System.Collections.Immutable.Tests.ImmutableArrayTest+<ChangeType>d__192`1[int]:MoveNext():ubyte:this' during 'Assertion prop' (IL size 362; hash 0x08aa2d36; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\assertionprop.cpp:1486
    Image: C:\h\w\A3450896\p\dotnet.exe
```
Opened https://github.com/dotnet/runtime/issues/109745

**Comment by AndyAyersMS** [comment]
handful of [Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=867932&view=ms.vss-build-web.run-extensions-tab)... not sure why yet.

**Comment by AndyAyersMS** [comment]
Diffs are because `fgConvertBBtoThrowBB` also makes the block rare. So revising the fix a bit to preserve this behavior.

**Pull request merged**
