### PR TITLE
Use live dependencies for netcoreapp3.0 depencies

### LINKED ISSUE #45560: System.Text.Json defines netcoreapp3.0 with no dependencies
Users are hitting an issue with needing to add an explicit reference to System.Text.Encodings.Web when they have System.Text.Json 5.0.0 in a netcoreapp3.1 project. I'm not sure why there is even a netcoreapp3.0 target for this package, but that's not my concern.

Looks like the regression was added between preview8 and rc1 of the 5.0.0 package.

image

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/runtime/issues/45560

I looked at the all the OOBs and these two stood out. I will go over the list yet again for master after this is in.

### CODE REVIEW

**Review by Anipik — CHANGES_REQUESTED** [review]
We need to add the packaging changes here. https://github.com/dotnet/runtime/blob/release/5.0/docs/project/library-servicing.md

**Review by Anipik — APPROVED** [review]
ah i missed the base branch

**Review by safern — APPROVED** [review]

**Comment by safern** [comment]
@ViktorHofer is there any validation we could add in the future to avoid this from happening again?

**Comment by ViktorHofer** [comment]
The PR is now ready. I scanned all packages twice and am now confident that I found all packages that misbehaved. While scanning them I found more issues and filed:
- https://github.com/dotnet/runtime/issues/48307
- https://github.com/dotnet/runtime/issues/48306
- https://github.com/dotnet/runtime/issues/48248
- https://github.com/dotnet/runtime/issues/48311

> @ViktorHofer is there any validation we could add in the future to avoid this from happening again?

Yes, I believe that making sure that live dependencies (if available) are used instead of prebuilts via a common syntax is the right mitigation. That is tracked via https://github.com/dotnet/runtime/issues/48238.

**Pull request merged**
