### PR TITLE
Fix unsafe walking of DacEnumerableHash

### LINKED ISSUE #85688: Bug in the lock-free logic of DacEnumerableHash
### Description

In looking at internal Microsoft reports of issues with CoreCLR, I've found an issue where the lock-free lookup logic in `DacEnumerableHash` is not correct.

### Reproduction Steps

Under the following set of conditions, it is possible for a lookup in the `DacEnumerableHash` to fail to find already present entries. 

Given Thread A which is growing the table, and thread B which is attempting to perform a lookup.

1. Thread B reads an `VolatileEntry*` from a bucket in the hashtable. Let this be EntryB. EntryB will have a next pointer which points to EntryThatWeNeedToFind, but it will not yet read that pointer value from EntryB.
2. Thread A reads the pointer to EntryB from the same bucket in the hashtable.
3. Thread A adds EntryB to the new hashtable
4. Thread A sets the bucket in the old hashtable to point to EntryThatWeNeedToFind
5. Thread A sets the next pointer in EntryB to point to NULL.
6. Thread B reads the next pointer, sees that the next pointer is NULL, and falls back to looking in the "new" hashtable for any possible updates
7. Thread B looks in the appropriate bucket in the "new" hashtable. That bucket does not yet contain EntryThatWeNeedToFind, as it hasn't yet been moved from the old hashtable.
8. Thread B returns NULL __*INCORRECTLY*__, indicating that there are no entries with the matching in them.

### Expected behavior

Given the reproduction steps, we should have a mechanism in the table to detect this problematic scenario, and find the correct result.

### Actual behavior

The hashtable can return NULL unexpectedly. This is known to be able to cause unexpected behaviors and crashes.

### Regression?

Yes. This was regressed by #61346

### Known Workarounds

_No response_

### Configuration

This has only been observed on very large, official build machines, and extremely rarely.

### Other information

Contact me via Teams for additional details about the internally reported issue.

### PR DESCRIPTION
**Pull request by davidwrighton**
Under the following set of conditions, it is possible for a lookup in the `DacEnumerableHash` to fail to find already present entries. 

Given Thread A which is growing the table, and thread B which is attempting to perform a lookup.

1. Thread B reads an `VolatileEntry*` from a bucket in the hashtable. Let this be EntryB. EntryB will have a next pointer which points to EntryThatWeNeedToFind, but it will not yet read that pointer value from EntryB.
2. Thread A reads the pointer to EntryB from the same bucket in the hashtable.
3. Thread A adds EntryB to the new hashtable
4. Thread A sets the bucket in the old hashtable to point to EntryThatWeNeedToFind
5. Thread A sets the next pointer in EntryB to point to NULL.
6. Thread B reads the next pointer, sees that the next pointer is NULL, and falls back to looking in the "new" hashtable for any possible updates
7. Thread B looks in the appropriate bucket in the "new" hashtable. That bucket does not yet contain EntryThatWeNeedToFind, as it hasn't yet been moved from the old hashtable.
8. Thread B returns NULL __*INCORRECTLY*__, indicating that there are no entries with the matching in them.

This change adjust how these linked lists work, but giving each one a version number which can be checked as the linked list finishes reading. The fix allows finding entries from an earlier set of buckets (as those can be in the new list temporarily, and will not interfere with finding the correct result), but will actively detect walking entries in the new list when attempting to walk the old entries. 

In addition, there is a drive by fix for an issue where if there are more than ~14,000,000 entries in the table, it allocates a full new list each time the list is added to.

Fixes #85688

### CODE REVIEW

**Comment by VSadov** [comment]
@davidwrighton  I am wondering if you managed to get a more reliable repro for this. 
The scenario that you describe seems plausible. Maybe we can amplify the race by introducing a small delay at step`#6` - before `Thread B reads the next pointer` part?

I think I will try that and run the tests. If things start failing, it will work as a "repro".

**Comment by davidwrighton** [comment]
I did not manage to get any form of reliable repro unfortunately. I expect that you'll both need to force a couple of things

1. The hash function could be made substantially worse. 
2. Adding a delay where you suggest

The problem is that actually making a failed lookup into a crash is fairly tricky. It won't always happen, and depends on how the found type is used.

Also this will only fail in the presence of actual multithreading, so the runtime tests are not very useful. You would probably need to run the libraries test suite.

**Comment by VSadov** [comment]
>The hash function could be made substantially worse.

I am trying to limit the max number of buckets. Should do the same thing.

> The problem is that actually making a failed lookup into a crash is fairly tricky.

Right. Missed lookup is not always a crash or assert. I think that makes it hard to arrange a failure on purpose.

I did not look into details of the fix to make sure it does what it claims to do (i.e. no off-by-one errors and such), but I get the overall idea and it makes sense. 
I'd really want to be able to say - "here is a way to force the race to happen, after the fix we see no race"

**Comment by VSadov** [comment]
> Missed lookup is not always a crash or assert.

The reason for this is that during stages when the hashtable is filling up, the common pattern is:
- do a lookup for a thing
- if failed, take a lock
- do another lookup 
- if not failed when lock is taken, then some other thread added the item, return that
- otherwise make the thing and add to the hashtable
- release the lock

The above can tolerate lookups that are missing due to concurrent resizes (since resize cannot be concurrent with the second lookup, when lock is taken)

There is a way to catch the missing lookup though by doing lookup twice inside `BaseFindFirstEntryByHash` - if the first lookup returned a value, the second should not return nullptr. 
If I also constrain the number of buckets to something like 640, I see violations.

I can use such instrumentation as a repro.

**Comment by VSadov** [comment]
I see some failures with the change when running the libraries tests. (as-is, without any additional instrumentation)

Looks like we may get into null dereferencing. 
```c
        // Walk the bucket chain one entry at a time.
        while (!IsEndSentinel(pEntry))
        {
            if (pEntry->m_iHashValue == iHash)     <=== here
            {
                // We've found our match.
```


```
[0xa]   ntdll!RtlpCallVectoredHandlers+0x108   0xafab65d2d0   0x7ffeb7a41316   
[0xb]   ntdll!RtlDispatchException+0x66   0xafab65d370   0x7ffeb7a90f8e   
[0xc]   ntdll!KiUserExceptionDispatch+0x2e   0xafab65d580   0x7ffe52a3257d   
[0xd]   coreclr!DacEnumerableHashTable<EETypeHashTable,EETypeHashEntry,2>::BaseFindFirstEntryByHashCore+0x30d   0xafab65dc80   0x7ffe52a32221   
[0xe]   coreclr!DacEnumerableHashTable<EETypeHashTable,EETypeHashEntry,2>::BaseFindFirstEntryByHash+0x2e1   0xafab65de60   0x7ffe52a347db   
[0xf]   coreclr!EETypeHashTable::FindItem+0x47b   0xafab65e030   0x7ffe52a351ce   
[0x10]   coreclr!EETypeHashTable::GetValue+0x18e   0xafab65e420   0x7ffe5273691c   
[0x11]   coreclr!ClassLoader::LookupTypeKey+0x47c   0xafab65e540   0x7ffe52735a2f   
[0x12]   coreclr!ClassLoader::LookupInLoaderModule+0x46f   0xafab65e800   0x7ffe52736408   
[0x13]   coreclr!ClassLoader::LookupTypeHandleForTypeKey+0x388   0xafab65eaa0   0x7ffe5272bb19   
[0x14]   coreclr!ClassLoader::LoadConstructedTypeThrowing+0x989   0xafab65eca0   0x7ffe5272d17d   
[0x15]   coreclr!ClassLoader::LoadGenericInstantiationThrowing+0xb5d   0xafab65f250   0x7ffe529ad746   
[0x16]   coreclr!SigPointer::GetTypeHandleThrowing+0x21c6   0xafab65f790   0x7ffe5272f7fe   
[0x17]   coreclr!ClassLoader::LoadTypeDefOrRefOrSpecThrowing+0x9be   0xafab660ab0   0x7ffe52c5595c   
[0x18]   coreclr!MethodTableBuilder::LoadExactInterfaceMap+0x5cc   0xafab660fb0   0x7ffe526ff777   
[0x19]   coreclr!ClassLoader::LoadExactParentAndInterfacesTransitively+0x647   0xafab661880   0x7ffe526ffbfc   
[0x1a]   coreclr!ClassLoader::LoadExactParents+0x41c   0xafab661b60   0x7ffe52721a00   
[0x1b]   coreclr!ClassLoader::DoIncrementalLoad+0x780   0xafab661e10   0x7ffe5273371c   
```

(this is on 32 logical cores machine with server GC enabled, so it is a bit more stressful than a lab run)

I will look into this a bit more. Hopefully it is caused by something trivial like a typo, and easy to fix.

**Comment by VSadov** [comment]
Another variant, now with method lookup, but I think it is the same issue:

```
[0xa]   ntdll!RtlpCallVectoredHandlers+0x108   0x2791f36ad0   0x7ffeb7a41316   
[0xb]   ntdll!RtlDispatchException+0x66   0x2791f36b70   0x7ffeb7a90f8e   
[0xc]   ntdll!KiUserExceptionDispatch+0x2e   0x2791f36d80   0x7ffe52846e6d   
[0xd]   coreclr!DacEnumerableHashTable<InstMethodHashTable,InstMethodHashEntry,4>::BaseFindFirstEntryByHashCore+0x30d   0x2791f374b0   0x7ffe52846b11   
[0xe]   coreclr!DacEnumerableHashTable<InstMethodHashTable,InstMethodHashEntry,4>::BaseFindFirstEntryByHash+0x2e1   0x2791f37690   0x7ffe5284803d   
[0xf]   coreclr!InstMethodHashTable::FindMethodDesc+0x2dd   0x2791f37860   0x7ffe52b827b8   
[0x10]   coreclr!InstantiatedMethodDesc::FindLoadedInstantiatedMethodDesc+0x7f8   0x2791f37af0   0x7ffe52b84b1c   
[0x11]   coreclr!MethodDesc::FindOrCreateAssociatedMethodDesc+0x21fc   0x2791f37f70   0x7ffe5280bd55   
[0x12]   coreclr!Dictionary::PopulateEntry+0x1655   0x2791f38e40   0x7ffe52c0817a   
[0x13]   coreclr!JIT_GenericHandleWorker+0x3fa   0x2791f39710   0x7ffe52c088d5   
[0x14]   coreclr!JIT_GenericHandle_Framed+0x5b5   0x2791f399e0   0x7ffe52bf3241   
[0x15]   coreclr!JIT_GenericHandleMethod+0x4e1   0x2791f3a130   0x7ffdf6a7834e   
[0x16]   System_ComponentModel_Composition!System.ComponentModel.Composition.Hosting.ExportProvider.GetExports<object>+0x4e   0x2791f3a5d0   0x7ffdf6db4f14   
[0x17]   System_ComponentModel_Composition_Tests!+   0x2791f3a610   0x7ffe530524c3   
[0x18]   coreclr!CallDescrWorkerInternal+0x83   0x2791f3a680   0x7ffe52a9bdee   
[0x19]   coreclr!CallDescrWorkerWithHandler+0x12e   0x2791f3a6c0   0x7ffe52d3354a   
[0x1a]   coreclr!RuntimeMethodHandle::InvokeMethod+0xe2a   0x2791f3a720   0x7ffe518a08d2   
[0x1b]   System_Private_CoreLib!System.Reflection.MethodInvoker.Invoke+0x92   0x2791f3b170   0x7ffe518aea25   
```

**Comment by davidwrighton** [comment]
@VSadov I believe I've been able to fix the issue you found.

**Comment by VSadov** [comment]
> I believe I've been able to fix the issue you found.

I no longer see the failures mentioned above when running the code from the PR as-is (no stress instrumentation yet)
The last fix seems sufficient.

**Comment by VSadov** [comment]
I have tried running libraries tests with and without additional instrumentation that could cause the original race to appear and there were no failures.

**Comment by VSadov** [comment]
Perhaps it would be worth adding an assert like the following to the `BaseFindFirstEntryByHash`:

```c++
    // return BaseFindFirstEntryByHashCore(curBuckets, iHash, pContext);      <--- instead of this

    DPTR(VALUE) result = BaseFindFirstEntryByHashCore(curBuckets, iHash, pContext);
    // if we found somehing, another lookup should not result in a miss
    _ASSERTE(result == nullptr || BaseFindFirstEntryByHashCore(curBuckets, iHash, pContext) != nullptr);
    return result;
```

Just in case this is not fixed on some platforms or may regress somehow. This would essentially query the table twice and compare the results. 
Such assert might be too expensive though. So it is just a thing to consider.

**Review by VSadov — APPROVED** [review]
LGTM. Thanks!!!

**Pull request merged**
