### PR TITLE
Enabled `System.ComponentModel.TypeConverter.Tests`.

### LINKED ISSUE #39709: [wasm] Enable System.Xml.Linq.Tests.XTypeDescriptionProviderTests class
While enabling `System.ComponentModel.TypeConverter.Tests` on Browser WASM, I faced the failures in  [System.Xml.Linq.Tests.XTypeDescriptionProviderTests](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.ComponentModel.TypeConverter/tests/XTypeDescriptionProviderTests.cs) test class.

There are 7 test cases which mostly test the property-related logic for XElement and XAttribute classes (https://github.com/dotnet/corefx/pull/33082).
Those classes are annotated with `System.ComponentModel.TypeDescriptionProviderAttribute` so that TypeDescriptor.GetProperties() can provide with some additional properties https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.ComponentModel.TypeConverter/src/MS/Internal/Xml/Linq/ComponentModel/XComponentModel.cs#L36-L61.

The mentioned tests get a collection of property descriptors by calling something like below
```
var xel = new XElement("someElement");
var props = TypeDescriptor.GetProperties(xel);
```
Actually `props` contains only a collection of some general properties and doesn't include the additional ones.

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/39709.
`System.ComponentModel.TypeConverter.Tests` on Browser are passing now.

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
LGTM. Thanks!

**Review by lewing — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Comment by radical** [comment]
Running `runtime-wasm` so we can check the test for AOT also.

**Comment by radical** [comment]
The wasm/HighResource_AOT failures are https://github.com/dotnet/runtime/issues/71848 .

**Pull request merged**
