### PR TITLE
Added method overload for `IServiceCollection.Configure<T>(Action<T, IServiceProvider>)`

### PR DESCRIPTION
**Pull request by lazytarget**
### What
Be able to use `IServiceProvider` to resolve a dependency within an `services.Configure<MyOptions>()` registration.

### Why
Currently the only way to resolve a dependency inside of `ConfigureServices` you will need to create an intermediate `IServiceProvider` using the BuildServiceProvider() method. The big issue with this, apart from performance, is that different instances of the service provider can give different singleton services.

### How
Enables the user to configure an options instance using a factory that exposes the `IServiceProvider` instance.
Making it possible to lazily resolve dependencies inside an options class.

### Examples

	public class MyOptions
	{
		public double Threshold { get; set; }
	}

	public static IServiceCollection ConfigureServices(this IServiceCollection services)
	{
		return services
			.AddSingleton<Random>()

			// #1 Resolving dependency inside of an options configurator (by creating an intermediate service provider(
			.Configure<MyOptions>((opt) =>
			{
				var sp = services.BuildServiceProvider();
				var random = sp.GetRequiredService<Random>(),
				opt.Threshold = random.NextDouble();
			})

			// #2 You could use the `AddSingleton` method directly (which is how `Configure` works) and passing the service provider
			.AddSingleton<IConfigureOptions<ApiKeyAuthenticationOptions>>(
				(sp) => new ConfigureNamedOptions<ApiKeyAuthenticationOptions>("", (o) =>
				{
				    o.Threshold = sp.GetRequiredService<Random>().NextDouble();
				})
			)

			// #3 This variant is a result of this PR, allowing for a much simpler syntax
			.Configure<MyOptions>((opt, sp) =>
			{
				var random = sp.GetRequiredService<Random>(),
				opt.Threshold = random.NextDouble();
			})
	}

NOTE: That _alternative 2_ is what is actually happening behind the scenes when writing the _alternative 3_. 
It is just easier to read, more future-proof and it also resembles the classic _alternative 1_

### Risks
No breaking changes, this would extend the API surface.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=72942) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=72942) before we can accept your contribution.<br/><br/>:x: LazyTarget [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=72942)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=72942) it.</sub>

**Comment by eerhardt** [comment]
Thanks for the interest, @LazyTarget.

Have you seen https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md? We won't be able to accept any new public API until the API is proposed and approved. Until the new API is approved, we don't allow PRs to be created. See https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#pull-requests.

**Comment by LazyTarget** [comment]
> Thanks for the interest, @LazyTarget.
> 
> Have you seen https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md? We won't be able to accept any new public API until the API is proposed and approved. Until the new API is approved, we don't allow PRs to be created. See https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#pull-requests.

For some reason, I thought it might not be needed for this change 😄 
Created a proposal issue here: #73050

**Comment by teo-tsirpanis** [comment]
Closing until the proposal gets accepted.

**Pull request closed without merging**
