### PR TITLE
Fix a minor assert issue in long decomposition

### PR DESCRIPTION
**Pull request by SingleAccretion**
Rotation/shift decomposition was risking hitting an assert in `LIR::Use::ReplaceWithLclVar` when it was removing the `gtLong` node from the linear order too early. This is not a correctness problem.

No diffs (SPMI win-x86) for this change as expected.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
Hmm, turns out there more such cases.

**Comment by JulieLeeMSFT** [comment]
CC @dotnet/jit-contrib PTAL.

**Comment by BruceForstall** [comment]
@SingleAccretion You write:

> Rotation/shift decomposition was risking hitting an assert

Why is it that it is only "risking hitting an assert" and we don't actually hit an assert?

**Comment by SingleAccretion** [comment]
@BruceForstall The reason is that the [assert](https://github.com/dotnet/runtime/blob/cc0c1213003ca9fbbae5c300c6ac47738f4a3fd7/src/coreclr/jit/lir.cpp#L257) is only [enabled](https://github.com/dotnet/runtime/blob/cc0c1213003ca9fbbae5c300c6ac47738f4a3fd7/src/coreclr/jit/lir.cpp#L389-L399) when we have "expensive debug checks" on, which I guess only happens in stress scenarios, and these codepaths are hit rarely enough for it not to have surfaced as a problem.

**Comment by BruceForstall** [comment]
I don't think we ever test with `JitExpensiveDebugCheckLevel != 0`, although the code that consults `expensiveDebugCheckLevel` does see `1` sometimes, based on stress. But nobody sees `2` since we don't have test runs that set that. And there are some asserts with `2` and SuperPMI replay.

**Comment by SingleAccretion** [comment]
Interesting. I assumed we have it set at least sometimes. It makes all the `Contains` asserts effectively dead. What should we do with them in your opinion (fix/delete/defer judgement)?

**Comment by BruceForstall** [comment]
fyi, I opened a couple bugs for asserts in SuperPMI replay with `JitExpensiveDebugCheckLevel=2` (https://github.com/dotnet/runtime/issues/58396, https://github.com/dotnet/runtime/issues/58397) but didn't see this assert

**Comment by BruceForstall** [comment]
> What should we do with them in your opinion (fix/delete/defer judgement)?

I don't know how valuable they are if enabled. Ideally, if valuable, they could be enabled at least sometimes during stress, in cases they aren't "too expensive", e.g., for small-ish functions.

**Comment by SingleAccretion** [comment]
> but didn't see this assert

FWIW, there is a reverted commit in this PR that contains a test which reproduces the issue, so it is "detectable".

> I don't know how valuable they are if enabled.

I am similarly not sure... The assert in this particular case is fully benign, since `ReplaceWithLclVar` doesn't depend on the user being in the linear order. Its sister assert (for the use itself) could be useful, though I suspect trying to insert nodes into random places will be detected either way. Should I close this PR perhaps?

**Comment by BruceForstall** [comment]
Let's go ahead and take this.

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
