### PR TITLE
[wasm][debugger] Skip generated wrappers when trying to step into/out with JustMyCode enabled

### PR DESCRIPTION
**Pull request by thaystg**
If we don't add this flag and try to step out in a C# function we will see the generated file in the debugger because it's embedded in the PDB, even if we are using JustMyCode enabled, and I think we should change this behavior.

### CODE REVIEW

**Comment by thaystg** [comment]
@jkoritzinsky as discussed with @pavelsavara offline, he asked me to ping you about it.
Do you think it makes sense? Also, do we need the same thing on LibraryImport?

**Comment by jkoritzinsky** [comment]
The sources for these generated stubs can be available if the developer embeds the generated sources into the PDB, so auto-skipping them is a little concerning for me.

A big part of the LibraryImport feature is that you can step through the generated code, so automatically skipping the frame is definitely not something we want to do.

**Comment by thaystg** [comment]
And what do you think about marking them with: `System.Diagnostics.DebuggerNonUserCode` does it make more sense?

**Comment by jkoritzinsky** [comment]
All of the "Debugger" attributes that limit stepping through are things we don't want for LibraryImport, but if you feel that they're the right thing for the JS generators, then that would be okay.

I'd be more curious here to know if we could fix the "view the source-generated source" experience for WASM instead of having the debugger skip the frames.

**Comment by thaystg** [comment]
If the source is embedded in the PDB it will work on WASM. 
But as far as you explained it's not always there right? Is it optional? How can I enable and disable it?

**Comment by jkoritzinsky** [comment]
I'm not sure the option, but someone on the Roslyn team should know it. It's needed for determinism, so it's definitely available with some setting.

`DebuggerNonUserCode` might actually be an interesting idea/option for generators after giving it a second look. That way, people that use "Just My Code" wouldn't step through it. We should open an issue and tag the maintainers for the generators in the repo and define a repo-wide policy for it if we want to use it.

**Comment by lewing** [comment]
Where is the debug info being written in the non embedded case?

**Comment by thaystg** [comment]
Okay, after doing more tests, the source is ALWAYS embedded in the PDB, but I still think that makes sense to emit the `System.Diagnostics.DebuggerNonUserCode`, then is the programmer has JustMyCode enabled it will not step into this generated source.

**Comment by jkoritzinsky** [comment]
If the source is always embedded, why isn't it showing up when stepping into it? I think that's an issue that also needs to be investigated.

**Comment by thaystg** [comment]
> If the source is always embedded, why isn't it showing up when stepping into it? I think that's an issue that also needs to be investigated.

It was another situation, the generated code is being showed correctly:
image

**Review by pavelsavara — APPROVED** [review]
`DebuggerNonUserCode` looks right to me.

**Pull request merged**
