### PR TITLE
xor register to 0 instead of pushing 0 to the register

### PR DESCRIPTION
**Pull request by ghost**
The preferred way to 0 a register is by xoring it with itself, as it does not waste 6 extra bytes to encode vs. the mov command and works regardless of flags.

These changes were tested manually to ensure no side effects happen.

### CODE REVIEW

**Comment by jaykrell** [comment]
What are the effects on eflags, and does it matter?

**Comment by jaykrell** [comment]
That is in fact difference.
mov does not change eflags.
xor does.
It might not matter here.

**Comment by jaykrell** [comment]
The difference appears to be 4 bytes per instruction.
Not sure what the quoted 7 is.

**Comment by jaykrell** [comment]
The difference appears to be 2 bytes in each of 2 instructions, 4 bytes total.
What is the quoted 7?

**Comment by pi1024e** [comment]
I meant 6

**Comment by pi1024e** [comment]
the changing of the flags does not seem to matter here

**Comment by pi1024e** [comment]
By the way, xoring with itself is something a processor will notice and not change the flags in this special case.

**Review by lpereira — APPROVED** [review]
LGTM. `StubDispatchFixupWorker()` is a STDCALL function, so it doesn't really care about the eflags.

**Comment by jaykrell** [comment]
Xor is special and doesn't modify eflags, really? That seems surprising.
It is true that eflags is very rarely an input or output of a function, but that is not by virtue of being stdcall.

**Comment by pi1024e** [comment]
Any updates?

**Comment by VSadov** [comment]
@davidwrighton - looks right to me. Can you take a look?

**Comment by davidwrighton** [comment]
This code change is semantically correct. As the next instruction is a call to a function implemented in C++, the detail is that STDCALL abi does not consider EFLAGS to be part of the input argument set, nor are they expected to be preserved across a call.

While the guidance for writing high performance, dense assembly suggests using xor in this way, the performance/size characteristics of this particular function is such that it will not have an impact on the product, and the existing code is (somewhat) easier to read for developers who may not be as familiar with assembly. That guidance is much more important for compiler developers than for engineers writing small amounts of hand-coded assembly.

I do not believe we should take this change, as the existing logic is somewhat more self-documenting as its meaning, and the updated logic, while not wrong, does not improve the codebase. In addition, this change does not update the numerous other locations throughout or assembly code which also use the mov register, 0 pattern.

**Review by davidwrighton — CHANGES_REQUESTED** [review]
As I said in my comment, this change does not meaningfully improve the generated code quality, and makes the logic somewhat more difficult to read. I do not believe we should make this sort of change.

**Comment by jaykrell** [comment]
Huh, NT kinda takes opppsite approach.
Assembly isn’t really meant for the feint of heart.
For example 32bit zero extension to 64 bits is always taken advantage of. CLR is inconsistent on that.

**Comment by pi1024e** [comment]
Added comments to make it easier. Also xor with itself is an idiom. An idiom all CPUs understand. Not to mention, 32bit zero extension happens anyway when you xor everything out.

**Comment by pi1024e** [comment]
That and I am pretty sure xoring is the canonical way to set a register to 0.

**Comment by jaykrell** [comment]
I agree it is idiomatic.

Zero extension to upper 32 bits is not specific to xor, all 32bit operations do it.

Nobody should consider it difficult to understand, any more than any other assembly.

The eflags mutation bugs me a little, since these are stubs.

**Comment by stephentoub** [comment]
@davidwrighton, per your comments, this should be closed?  Thanks.

**Comment by tannergooding** [comment]
> As I said in my comment, this change does not meaningfully improve the generated code quality, and makes the logic somewhat more difficult to read. I do not believe we should make this sort of change.

I agree that the change is probably not worthwhile due to the location it is being used, etc. But I don't buy that it makes the code more difficult to read. `xor reg, reg` is the idiomatic way to do this such that it gets specialized support in the CPU, is taught in various programming courses, and most compilers emit it even for DEBUG binaries.

> In addition, this change does not update the numerous other locations throughout or assembly code which also use the mov register, 0 pattern.

We should probably log a bug for this as it could represent minor performance gains in some scenarios (as `xor reg, reg` is a dependency breaking pattern as well).

**Comment by stephentoub** [comment]
> I agree that the change is probably not worthwhile

> We should probably log a bug

I opened https://github.com/dotnet/runtime/issues/33556.

Thanks.

**Pull request closed without merging**
