### PR TITLE
[mono] Add Vector128 Dot intrinsics for Amd64

### PR DESCRIPTION
**Pull request by matouskozak**
Add support for the following Vector128 API's:

- Dot (works for every primitive type, except byte and sbyte).

Change `emit_sum_vector` function on Amd64 to follow same syntax as Arm64 version.

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Review by fanyang-mono — APPROVED** [review]
LGTM! One suggestion for future is to create a function for doing `dot`, so it could be reused by `emit_vector_2_3_4`.

**Pull request merged**
