### PR TITLE
Bump main version to RC1

### PR DESCRIPTION
**Pull request by carlossanlop**

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
@steveisok 

> Could not restore Microsoft.NET.Workload.Emscripten.Current.Manifest-8.0.100-rc.1/8.0.0-preview.7.23367.1

and other workload related failures

**Comment by lewing** [comment]
will have a fix for wasm build tests shortly

**Comment by lewing** [comment]
build should be green now

**Comment by lewing** [comment]
The WBT failure is unrelated to the workload stuff but we're taking a look

**Comment by carlossanlop** [comment]
> The WBT failure is unrelated to the workload stuff but we're taking a look

@lewing Would you like me to wait for a fix to be included here or is this PR unblocked for merging?

**Comment by lewing** [comment]
> > The WBT failure is unrelated to the workload stuff but we're taking a look
> 
> @lewing Would you like me to wait for a fix to be included here or is this PR unblocked for merging?

was a transient timeout that went away on rerun so I merged.

**Pull request merged**
