### PR TITLE
[wasm] Wasm.Build.Tests - split helix workload to be one per config

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by safern** [comment]
Question: I see that with this change the `browser` job is sending two helix job with the same azure devops test run. Is that correct? Should that be only 1 helix job?

```
  Job 36c6166c-8e84-4dc1-8767-3990a61f251e on Ubuntu.1804.Amd64.Open is completed with 2 finished work items.
  Stopping Azure Pipelines Test Run net6.0-Browser-Release-wasm-Mono_Release-buildwasmapps-Ubuntu.1804.Amd64.Open
  Job c7a3149d-b184-4901-8394-930e055e2e77 on Ubuntu.1804.Amd64.Open is completed with 2 finished work items.
  Stopping Azure Pipelines Test Run net6.0-Browser-Release-wasm-Mono_Release-buildwasmapps-Ubuntu.1804.Amd64.Open
```

Or are they missing something on the test run name like `AOT` or a test run mode?

**Comment by radical** [comment]
> Question: I see that with this change the `browser` job is sending two helix job with the same azure devops test run. Is that correct? Should that be only 1 helix job?
> 
> Or are they missing something on the test run name like `AOT` or a test run mode?

I want to split the test run so they run in parallel - for Debug, and Release. I tried submitting them as two helix work items in the same job, but that seemed to not run in parallel. So, I tried sending them as separate jobs. Does that sound correct?

I can modify the names, so it's clearer what they are for.

**Comment by safern** [comment]
> Does that sound correct?

Yes that sounds correct. 

> I can modify the names, so it's clearer what they are for.

It would be great to include the configuration on the test run name so that it is clear when there is a test failure in the test failures tab.

Also I noticed that the "new" workitems take 23 mins to run, is there a way we can do that more granular so that they are faster? The problem with such long workitems is that we are not taking so much advantage from the helix infrastructure which is parallelize as much tests or workitems as we can in multiple agents.

**Comment by radical** [comment]
> Also I noticed that the "new" workitems take 23 mins to run, is there a way we can do that more granular so that they are faster? The problem with such long workitems is that we are not taking so much advantage from the helix infrastructure which is parallelize as much tests or workitems as we can in multiple agents.

Yep, and I plan to do exactly that in follow up PRs, and do it in a way to reduce changes needed to the helix proj files. This one is to let the timings back to reasonable, so we can enable the Wasm.Build tests again.

**Comment by radical** [comment]
@safern I'm looking at the logs for this - https://dev.azure.com/dnceng/public/_build/results?buildId=1040170&view=logs&jobId=108d2c4a-8a62-5a58-8dad-8e1042acc93c&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=568f884b-cc12-5fd3-e7fe-790b5ac403f4 .

(raw log with timestamps: https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1040170/logs/1779)

There are four jobs submitted:
1. Debug wasm.build.tests
2. Release wasm.build.tests
3. normal (running with v8, I think)
4. wasmtestonbrowser (running with chrome)

* wasm.build tests submission

```
2021-03-15T23:07:41.1142549Z   Sent Helix Job; see work items at https://helix.dot.net/api/jobs/22c04ee1-52bb-40cf-b859-5ec490aba39b/workitems?api-version=2019-06-17
2021-03-15T23:07:41.1336632Z   Sent Helix Job; see work items at https://helix.dot.net/api/jobs/a32b297a-d4a1-46c0-8ae4-c631e096edd2/workitems?api-version=2019-06-17
```

* library tests submission
```
2021-03-15T23:07:55.4873872Z   Sent Helix Job; see work items at https://helix.dot.net/api/jobs/ef5ecd49-671c-4d2c-a48f-e262dec9ba9d/workitems?api-version=2019-06-17
2021-03-15T23:07:55.5659204Z   Sent Helix Job; see work items at https://helix.dot.net/api/jobs/e5a3970e-87c2-4b3e-8a30-fc6c4330fa59/workitems?api-version=2019-06-17
```

They get submitted at roughly the same time. Then (3), and (4) complete after ~23mins.

```
2021-03-15T23:31:37.9796887Z   Job ef5ecd49-671c-4d2c-a48f-e262dec9ba9d on Ubuntu.1804.Amd64.Open is completed with 216 finished work items.
2021-03-15T23:34:58.3293216Z   Job e5a3970e-87c2-4b3e-8a30-fc6c4330fa59 on Ubuntu.1804.Amd64.Open is completed with 216 finished work items.
```

And (1), and (2) complete after ~42mins after submission:
```
2021-03-15T23:49:57.6478348Z   Job 22c04ee1-52bb-40cf-b859-5ec490aba39b on Ubuntu.1804.Amd64.Open is completed with 2 finished work items.
2021-03-15T23:50:57.5418212Z   Job a32b297a-d4a1-46c0-8ae4-c631e096edd2 on Ubuntu.1804.Amd64.Open is completed with 2 finished work items.
```

But looking at the logs for the wasm build test runs, those seem to complete in roughly 25mins each. What could be causing them to take extra 17mins to return from helix?

Console log for (1), and (2):
[a32b297ad4a146c08a](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49559-merge-a32b297ad4a146c08a/Wasm.Build.Tests/console.b55a5550.log/?sv\=2019-07-07\&se\=2021-04-04T23%3A07%3A41Z\&sr\=c\&sp\=rl\&sig\=xtFf7DVquJc%2FM3%2BR%2BapzSn%2FoxiS4XpduGLkIBm8tE1E%3)
[22c04ee152bb40cfb8](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-49559-merge-22c04ee152bb40cfb8/Wasm.Build.Tests/console.89307f03.log\?sv\=2019-07-07\&se\=2021-04-04T23%3A07%3A41Z\&sr\=c\&sp\=rl\&sig\=WdhWJ5qbA9zo7%2FiEHfFEkHWCEE7q4rt0oVO1vSAWieE%3D)

Am I doing something wrong, or is this expected?

**Comment by radical** [comment]
> I want to split the test run so they run in parallel - for Debug, and Release. I tried submitting them as two helix work items in the same job, but that seemed to not run in parallel. So, I tried sending them as separate jobs. Does that sound correct?

I was talking to @steveisok, and he said that submitting these as separate work items should make them run in parallel too. But his hypothesis is that in this case, since one job would have only two work items, maybe helix is doing some kinda "optimization" just run them sequentially? Is that correct, @safern ?

And to be clear, the current PR does two separate job submissions, instead of two work items in the same job.

**Comment by radical** [comment]
Closing this, because I plan to split the test runs more, and in a different manner.

**Pull request closed without merging**
