### PR TITLE
Fix the GenericTest.Vector*Boolean

### PR DESCRIPTION
**Pull request by sandreenko**
Bool need special marshaling attribute, the test was failing on arm64 apple
where C++ was expecting them to be packed as 1 byte.

Thanks, @jkoritzinsky for helping with this.

### CODE REVIEW

**Comment by sandreenko** [comment]
cc @sdmaclea, @janvorli , @mangod9

**Review by jkoritzinsky — APPROVED** [review]

**Comment by sandreenko** [comment]
I think it was the lest test that was failing constantly in my local runs (with #46665 applied)

**Comment by sdmaclea** [comment]
I am not sure this is the right fix.  As this requires all C# code to be changed to work with Apple Silicon.  Maybe the default marshalling of `bool` on Apple Silicon needs to be changed instead?

**Comment by jkoritzinsky** [comment]
This fix fixes a bug that was on all platforms that we just hadn’t noticed. The previous code was semantically wrong in all cases and just happened to work.

**Comment by tannergooding** [comment]
> The previous code was semantically wrong in all cases and just happened to work.

Yep, my bad 😄. I always forget that `bool` is `int` by default, even on non-Windows (this also why I explicitly use `byte` and `int` in my own P/Invoke code >.>).

**Review by tannergooding — APPROVED** [review]

**Pull request merged**
