### PR TITLE
Make GCToEEInterface::Get*ConfigValue check the runtimeconfig.json

### LINKED ISSUE #12948: GCToEEInterface::Get*ConfigValue should also check the runtimeconfig.json
this should return all the known configs (known as in already processed by eeconfig) back and for the rest right now it just does this check
`if (CLRConfig::IsConfigOptionSpecified(configKey))`
we should also check `GetConfigurationValue` which check if the config is specified in runtimeconfig.json. and the former overwrites the latter.

### LINKED ISSUE #32956: System.GC.HeapCount not recognised when set via runtimeconfig.json
I've written a very simple .net core 3.1 application and tried to set the GC heap count using either the environment variable or the `runtimeconfig.json` file and have found that it only works when it is set via the environment variable.  I checked that the heaps were created by verifying the number of GC Server threads created (inspecting a dump or using perfview).

Other settings such as `System.GC.Server` work correctly in both configuration modes.

The `runtimeconfig.json` used is as follows:

```
{
  "runtimeOptions": {
    "tfm": "netcoreapp3.1",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "3.1.0"
    },
    "configProperties": {
      "System.GC.Server": true,
      "System.GC.HeapCount": 2
    }
  }
}
```

### PR DESCRIPTION
**Pull request by cshung**
Fixes https://github.com/dotnet/runtime/issues/12948
Fixes  https://github.com/dotnet/runtime/issues/32956

### CODE REVIEW

**Comment by Maoni0** [comment]
since now you are checking both env var and runtimeconfig in gcenv.ee.cpp, it means we can get rid of code like this:

```
    if (strcmp(privateKey, "GCSegmentSize") == 0)
    {
        *value = g_pConfig->GetSegmentSize();
        return true;
    }
```
and not get the configs in eeconfig.cpp at all unless they are also used on the VM side (like LOHThresHold).

**Comment by cshung** [comment]
In an ideal world, all the configuration related logic should go through the table-driven logic I refined in this PR. But as I started to go through the individual public configuration keys to find opportunities to eliminate manually written code. I detected all sort of inconsistencies in the code with respect to these knobs summarized below:

| Tables                        | Note                       | 
| ----------------------------- | -------------------------- |
|System.GC.Server               | Unix/Corerun/CorerunCommon |
|System.GC.Concurrent           | Unix/Corerun               |
|System.GC.RetainVM             | Unix                       |
|System.GC.HeapAffinitizeMask   | Arch specific size         |
|System.GC.HeapHardLimit        | Json Only                  |
|System.GC.HeapHardLimitPercent | Json Only                  |
|System.GC.LOHThreshold         | Used in profiler           |
|System.GC.NoAffinitize         | eeconfig not used          |
|System.GC.HeapCount            | eeconfig not used          |

(These items are not in a particular order)

The first three are boolean flags, they might be specified through the `STARTUP_FLAGS`

https://github.com/dotnet/runtime/blob/91f14182958b0fad9c9b4dc7d908ff955581979b/src/coreclr/src/vm/ceemain.cpp#L417-L437

The interesting inconsistency between these flags have to do with where they occurs. If we search for `System.GC.Server`. It appears in 3 source files related to host initialization, `System.GC.Concurrent` has only 2, `System.GC.RetainVM` has only one. This is just weird. At this point I am not sure what the functional differences are and if that is expected or not.

In any case, the table-driven logic wouldn't be able to replace that code, and I will keep the `eeconfig` logic for them for now.

`System.GC.HeapAffinitizeMask` has an arch specific size, this is obvious.

`System.GC.HeapHardLimit` and `System.GC.HeapHardLimitPercent` configuration code seems to only read from the json file. 

The fact that `System.GC.LOHThreshold` is used in the profiler code is fine, but this will stop us from using the table.

The last two are interesting, whoever wrote that code go through the work to create an accessor in eeconfig, but the accessor is never called. I experimented with commenting that out, and CoreCLR build just fine.

**Comment by Maoni0** [comment]
thanks for looking into this! `System.GC.Server`, `System.GC.Concurrent" and `System.GC.RetainVM" are specially handled just because they can be specified as startup flags and are interpreted in ceemain.cpp as part of handling the startup flags. strictly speaking, only `System.GC.Server` needs to be specially handled because it dictates which namespace we will be initializing the GCHeap in. Concurrent/RetainVM can always be enabled and disabled as needed. but no one really took the time to unify things like this when we moved to core so I'm glad that you are doing that now. 

it's definitely better to make this logic have as little special handling as possible so if we could have a simply policy as you suggested, as much as possible, it'd be great.

**Review by Maoni0 — APPROVED** [review]
LGTM; also chatted with Andrew offline and he will make a separate PR to address my last comment.

**Pull request merged**
