### PR TITLE
[mini] Fix typo in mono_decompose_vtype_opts

### LINKED ISSUE #90800: [Mono] RuntimeTypeHandle.Equals seems to be broken in Release mode
### Description

A recent Xamarin iOS PR (https://github.com/xamarin/xamarin-macios/pull/18742) ran into an issue in .NET 8/Mono with the `RuntimeTypeHandle.Equals` method.

The Xamarin tooling generates several lookup functions in IL using Mono.Cecil which look something like this:
```c#
public uint LookupTypeId(RuntimeTypeHandle handle) {
   if (handle.Equals(typeof(NSString).TypeHandle)) {
        return 1u;
   }
   if (handle.Equals(typeof(NSSet).TypeHandle)) {
        return 2u;
   }
   // ...
   return unchecked((uint)-1);
}
```

While this worked fine in .NET 7, in .NET 8 calling for example `LookupTypeId(typeof(NSString).TypeHandle)` won't return the correct value (`4294967295` instead of `1`).

### Reproduction Steps

The issue can be reproduced with a modified HelloWorld Mono sample:
```xml
<!-- src/mono/sample/LookupTable/LookupTable.ilproj -->
<Project Sdk="Microsoft.NET.Sdk.IL">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>$(NetCoreAppCurrent)</TargetFramework>
  </PropertyGroup>
</Project>
```
```cil
// src/mono/sample/LookupTable/LookupTable.il
.assembly extern mscorlib{}
.assembly LookupTable{}

.class public auto ansi abstract sealed beforefieldinit LookupTable
    extends [mscorlib]System.Object
{
    .method public hidebysig static
        int32 LookupTypeId (
            valuetype [mscorlib]System.RuntimeTypeHandle handle
        ) cil managed
    {
        .maxstack 8

        IL_aaaa: ldarga.s handle
        ldtoken [mscorlib]System.String
        call instance bool [mscorlib]System.RuntimeTypeHandle::Equals(valuetype [mscorlib]System.RuntimeTypeHandle)
        brfalse.s IL_aaab

        ldc.i4.2
        ret

        IL_aaab: ldc.i4.0
        ret
    }
}
```
```xml
<!-- src/mono/sample/HelloWorld/HelloWorld.csproj -->
<ItemGroup>
  <ProjectReference Include="..\LookupTable\LookupTable.ilproj" />
</ItemGroup>
```
```c#
// src/mono/sample/HelloWorld/Program.cs

if (LookupTable.LookupTypeId(typeof(string).TypeHandle) == 2) {
    System.Console.WriteLine("FOUND");
} else {
    System.Console.WriteLine("NOT FOUND");
}
```

Build the mono runtime with: `./build.sh mono+libs -c Release`
Build and run the sample with `mono -C src/mono/sample/HelloWorld MONO_CONFIG=Release MONO_ARCH=arm64 clean run`

### Expected behavior

The program should print `FOUND`.

### Actual behavior

The program prints `NOT FOUND`.

### Regression?

The generated lookup tables worked well before bumping to .NET 8.

### Known Workarounds

When we disable inlining of the `RuntimeTypeHandle.Equals` method in `src/mono/System.Private.CoreLib/src/System/RuntimeTypeHandle.cs`, the lookup function works correctly:
```c#
[MethodImpl(MethodImplOptions.NoInlining)]
public bool Equals(RuntimeTypeHandle handle)
{
    return value == handle.Value;
}
```

### Configuration

- .NET 8 (`e9ce3aac5440b8d5b76bddfea6285e546083589d`)
- building on macOS 13.5
- ARM64 (M1)
- Specific to `Release` configuration

### Other information

@filipnavara managed to workaround the issue by preventing inlining of the `Equals` method and so we believe that the culprit is inlining.

cc @rolfbjarne @ivanpovazan @filipnavara

### PR DESCRIPTION
**Pull request by lambdageek**
Without this, if some previous instruction already created a vreg for `ins->dest` (for example if we are doing multiple passes over the basic block because `restart == TRUE`) we will use an incorrect vreg for the `src` when decomposing the current VMOVE

---

Additionally, only emit `OP_LDTOKEN_FIELD` if we loaded a field token

This is used by a CreateSpan intrinsic https://github.com/dotnet/runtime/pull/81695 that needs access to the `MonoClassField*`

For other cases of a bare LDTOKEN (such as hand-written IL that calls LDTOKEN on a type but doesn't follow it up with a call to `GetTypeFromHandle` leave the opcode as a VMOVE (from the `EMIT_NEW_TEMPLOAD` above))

Fixes #90800

### CODE REVIEW

**Comment by lambdageek** [comment]
TODO: need to add a regression test.

attn @SamMonoRT we will need to backport this to net8.

**Comment by lambdageek** [comment]
@simonrozsival @rolfbjarne do we need to try to get this into rc1, is it completely blocking ios?

As a workaround, emitting roslyn-style IL will avoid this issue (because there will be an intervening `callvirt` that will avoid the decompose bug) 
https://sharplab.io/#v2:C4LglgNgPgAgTARgLACgDEA7ArhCBDAIwgFMACAEzAGdCTVSHTUYBmU+UgYVIG97HWpAEpYMwMAFtiAFQCeAB2IAJPBnIlSAWQAUASl79GAgOylgC4gHsAZtpgIADLoB0cxSrUkA3IdIBfVD8gA=

ie instead of `ldtoken System.Runtime]System.String` emit

```
        IL_0000: ldtoken [System.Runtime]System.String
        IL_0005: call class [System.Runtime]System.Type [System.Runtime]System.Type::GetTypeFromHandle(valuetype [System.Runtime]System.RuntimeTypeHandle)
        IL_000a: callvirt instance valuetype [System.Runtime]System.RuntimeTypeHandle [System.Runtime]System.Type::get_TypeHandle()
```

**Review by SamMonoRT — APPROVED** [review]

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
if this is a blocker for rc1 we should open the backport now and send the email

**Comment by lambdageek** [comment]
@lewing I'm offline for at least another 3 hours. Can you send the email - see the comments in the issue for  details

**Pull request merged**
