### PR TITLE
Fixing memory ordering issue in ConcurrentQueue

### LINKED ISSUE #76501: ManyConcurrentAddsTakes_ForceContentionWithToArray fails intermittently on osx-arm64
```
Assert.DoesNotContain() Failure
Found:    0
In value: Int32[] [0]
   at System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(Double seconds) + 0x110
   at System.Collections.Concurrent!<BaseAddress>+0x9fa6bc
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x148
```

```json
 {
    "ErrorMessage" : "System.Collections.Concurrent.Tests.ProducerConsumerCollectionTests.ManyConcurrentAddsTakes_ForceContentionWithToArray",
    "BuildRetry": false
 }
```

Failed in #76499. Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-76499-merge-3c4c964d671349bdbd/System.Collections.Concurrent.Tests/1/console.b1cceddc.log?helixlogtype=result

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[74353](https://dev.azure.com/dnceng-public/public/_build/results?buildId=74353)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=74353&view=ms.vss-test-web.build-test-results-tab&runId=1532538&resultId=109615)||
|[74067](https://dev.azure.com/dnceng-public/public/_build/results?buildId=74067)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=74067&view=ms.vss-test-web.build-test-results-tab&runId=1527146&resultId=109853)||
|[73941](https://dev.azure.com/dnceng-public/public/_build/results?buildId=73941)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=73941&view=ms.vss-test-web.build-test-results-tab&runId=1525586&resultId=110947)|dotnet/runtime#77934|
|[73002](https://dev.azure.com/dnceng-public/public/_build/results?buildId=73002)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=73002&view=ms.vss-test-web.build-test-results-tab&runId=1506092&resultId=109657)||
|[72557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=72557)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=72557&view=ms.vss-test-web.build-test-results-tab&runId=1499280&resultId=112941)||
|[71724](https://dev.azure.com/dnceng-public/public/_build/results?buildId=71724)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_ForceContentionWithGetEnumerator](https://dev.azure.com/dnceng-public/public/_build/results?buildId=71724&view=ms.vss-test-web.build-test-results-tab&runId=1474384&resultId=112672)||
|[70399](https://dev.azure.com/dnceng-public/public/_build/results?buildId=70399)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=70399&view=ms.vss-test-web.build-test-results-tab&runId=1447882&resultId=112246)|dotnet/runtime#77770|
|[67757](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67757)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67757&view=ms.vss-test-web.build-test-results-tab&runId=1380518&resultId=114637)||
|[67272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67272)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67272&view=ms.vss-test-web.build-test-results-tab&runId=1370366&resultId=110597)||
|[67179](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67179)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67179&view=ms.vss-test-web.build-test-results-tab&runId=1367648&resultId=105375)||
|[66666](https://dev.azure.com/dnceng-public/public/_build/results?buildId=66666)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=66666&view=ms.vss-test-web.build-test-results-tab&runId=1358674&resultId=113160)|dotnet/runtime#76630|
|[64951](https://dev.azure.com/dnceng-public/public/_build/results?buildId=64951)|dotnet/runtime|[System.Collections.Concurrent.Tests.ConcurrentQueueTests.ManyConcurrentAddsTakes_ForceContentionWithToArray(seconds: 1)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=64951&view=ms.vss-test-web.build-test-results-tab&runId=1322298&resultId=112278)|dotnet/runtime#77522|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|5|12|

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #76501

### CODE REVIEW

**Comment by VSadov** [comment]
I am running the repro in multiple processes for about 20 min now with no failures. It typically fails in under one minute.

**Comment by VSadov** [comment]
No failures for an hour. So it looks like the scenario has no other issues.

**Comment by VSadov** [comment]
thanks @filipnavara for a repro scenario!

**Comment by filipnavara** [comment]
Thanks for the fix, LGTM. It should probably be backported to 7.0.

**Review by stephentoub — APPROVED** [review]
Thanks. Nice find.

**Comment by stephentoub** [comment]
> It should probably be backported to 7.0.

I'm fine with that; CQ is at the heart of the system due to its usage in ThreadPool. Just note this isn't new; been this way since I missed adding the volatile in 2016 :)
https://github.com/dotnet/corefx/pull/14254/files#diff-c12f070bb2033f631c1e51c214b49d678ecb1c871b24652213654486f8cb187bR567

**Comment by VSadov** [comment]
Thanks!!

**Comment by VSadov** [comment]
The issue is on ToArray/CopyTo/Enumerate path. I think it would be unusual to do such operations while the queue is mutated. Any kind of synchronization that guarantees quiescence will likely make this issue disappear. 

Also it requires weak architecture and hardware that utilizes that weakness aggressively. - Missing write fences often cause troubles as write-buffering is common. Missing read fences require that CPU speculates far ahead. These are probably still not very common. Evidently, we have only seen this issue on M1.

I think chances of seeing this causing problems in actual programs are low. On the other hand it is possible and the fix is very low risk and 7.0 may see a bigger share of weak architectures than prior releases.

I think it may be worth porting.

**Comment by VSadov** [comment]
I also think this issue may become a test/stress nuisance in 7.0

**Pull request merged**
