### PR TITLE
enable zip unicode tests on OSX

### LINKED ISSUE #1551: Investigate rel OSX ZipFile failures
Some ZipFile tests are failing on OSX in rel/1.0.0 and rel/1.1.0 because they're unable to match file names to entries in the FileData class. We need to investigate why they're only failing on rel e.g. if they're missing some recent test fixes and determine if there is something more insidious happening. 

PR's to disable the tests temporarily:
https://github.com/dotnet/corefx/pull/23346
https://github.com/dotnet/corefx/pull/23359

### PR DESCRIPTION
**Pull request by wfurt**
I did test ruin on my OSX and it seems to work fine. 

fixes #1551

### CODE REVIEW

**Comment by safern** [comment]
All configurations leg was just fixed in: https://github.com/dotnet/runtime/pull/1729

**Review by carlossanlop — APPROVED** [review]
Thanks for the change, @wfurt. I clicked on Re-Run for the failed CI runs, but maybe a rebase is required?

**Comment by safern** [comment]
@wfurt runtime-installer pipeline is deprecated, now everything is part of the "runtime" pipeline. We're in the process of updating docs... if you want to remove the red badges, you can amend your commit (to change the hash) and push, or just ignore the failures in runtime-libraries if "runtime" is green, we test the same things now in "runtime". 

The failure you're seeing on Installer Build and Test Windows_NT_x86 Release is a known issue and you can ignore, so basically this PR is good to merge.

**Comment by wfurt** [comment]
I really wanted to run ' (Libraries Build OSX x64 Debug)' Since it was canceled I could not use restart option.

**Comment by safern** [comment]
> I really wanted to run ' (Libraries Build OSX x64 Debug)' Since it was canceled I could not use restart option.

Right, but the one that was cancelled was the one under the "runtime-libraries" pipeline. If you look at the "runtime" pipeline it also has a step to Build OSX x64 Debug and run tests:

image

image

That's what I meant with now these steps are part of the "runtime" pipeline as "runtime-libraries" no longer exist. The reason why it is showed, is because GH stores the badge information in relation to the HEAD commit hash, since you only closed/re-open the PR and the pipelines changed while your PR was open, it will see that the hash existed and will not remove badges for builds that no longer exist.

**Pull request merged**
