### PR TITLE
Fix inlining of IPAddress ctor

### LINKED ISSUE #65512: Regressions in System.Net.Primitives.Tests.IPAddressPerformanceTests
### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [b2eba58b2c1f52f609616a7c7380c04fed516abf](https://github.com/dotnet/runtime/commit/b2eba58b2c1f52f609616a7c7380c04fed516abf)
Compare | [615224c46bb9d2113c040bb6824429fd42b60bd4](https://github.com/dotnet/runtime/commit/615224c46bb9d2113c040bb6824429fd42b60bd4)
Diff | [Diff](https://github.com/dotnet/runtime/compare/b2eba58b2c1f52f609616a7c7380c04fed516abf...615224c46bb9d2113c040bb6824429fd42b60bd4)

### Regressions in System.Net.Primitives.Tests.IPAddressPerformanceTests

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[Ctor_Bytes - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Net.Primitives.Tests.IPAddressPerformanceTests.Ctor_Bytes(address%3a%20%5b143%2c%2024%2c%2020%2c%2036%5d).html>) | 6.90 ns | 8.71 ns | 1.26 | 0.20 | False | | |

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/02_16_2022/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Net.Primitives.Tests.IPAddressPerformanceTests.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net6.0 --filter 'System.Net.Primitives.Tests.IPAddressPerformanceTests*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-3be24458-e5d5-46d9-bd62-e23dd85ee6995f8fc3c5a4e453e8a/2e852a29-03b8-433f-8b35-024b717da247.zip?sv=2019-07-07&se=2022-03-12T20%3A17%3A57Z&sr=c&sp=rl&sig=D8mVYXnta3UPkywoJMSl%2Bx%2FzFr5l3tHq85qQMGM5fsE%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-839aa7ea-c811-4e2c-ac7b-d5a96aac12946b55ae528ca4ee49e/306e52cb-f73e-4da7-8078-d8a4774407b9.zip?sv=2019-07-07&se=2022-03-13T14%3A21%3A22Z&sr=c&sp=rl&sig=OpneHuLvZLgPTElEdaJesebYxizskqyVDWH4jRc7XjU%3D>)
#### System.Net.Primitives.Tests.IPAddressPerformanceTests.Ctor_Bytes(address: [143, 24, 20, 36])

```log

```
### Description of detection logic
```IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 8.711041242235293 > 7.365624976923407.
IsChangePoint: Marked as a change because one of 11/12/2021 1:41:39 AM, 11/12/2021 5:41:55 PM, 2/11/2022 12:34:36 AM, 2/17/2022 2:02:19 AM falls between 2/8/2022 9:17:51 AM and 2/17/2022 2:02:19 AM.
IsRegressionStdDev: Marked as regression because -7.361068167774787 (T) = (0 -8.781514318770144) / Math.Sqrt((0.06104314171374399 / (16)) + (0.8759473801917672 / (21))) is less than -2.0301079282477414 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (16) + (21) - 2, .025) and -0.21781461172364655 = (7.210879418125175 - 8.781514318770144) / 7.210879418125175 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>
### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [b2eba58b2c1f52f609616a7c7380c04fed516abf](https://github.com/dotnet/runtime/commit/b2eba58b2c1f52f609616a7c7380c04fed516abf)
Compare | [615224c46bb9d2113c040bb6824429fd42b60bd4](https://github.com/dotnet/runtime/commit/615224c46bb9d2113c040bb6824429fd42b60bd4)
Diff | [Diff](https://github.com/dotnet/runtime/compare/b2eba58b2c1f52f609616a7c7380c04fed516abf...615224c46bb9d2113c040bb6824429fd42b60bd4)

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/65512
cc: @EgorBo

### CODE REVIEW

**Comment by wfurt** [comment]
Do you think this will also fix the perf inconsistencies? (And why the `!!` no longer works/perform)

**Comment by stephentoub** [comment]
> Do you think this will also fix the perf inconsistencies

Which inconsistencies?

!! is pretty much always better than writing out the if throw manually. This case was different, as it was already using a throw helper, and this PR just reverts out to the way it was before my changes.

**Comment by wfurt** [comment]
> 
> Which inconsistencies?
> 

https://camo.githubusercontent.com/faf3fe9a279212d4c3289fea0efb6155db1c8e0499e989eeab24758cb4307682/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30325f31365f323032322f726566732f68656164732f6d61696e5f61726d36345f57696e646f777325323031302e302e31393034315f52656772657373696f6e2f53797374656d2e4e65742e5072696d6974697665732e54657374732e495041646472657373506572666f726d616e636554657374735f312e706e67

It seems like the test had random spikes in the pass as well

**Comment by EgorBo** [comment]
> > Which inconsistencies?
> 
> https://camo.githubusercontent.com/faf3fe9a279212d4c3289fea0efb6155db1c8e0499e989eeab24758cb4307682/68747470733a2f2f707673636d6475706c6f61642e626c6f622e636f72652e77696e646f77732e6e65742f6175746f66696c657265706f72742f6175746f66696c657265706f7274732f30325f31365f323032322f726566732f68656164732f6d61696e5f61726d36345f57696e646f777325323031302e302e31393034315f52656772657373696f6e2f53797374656d2e4e65742e5072696d6974697665732e54657374732e495041646472657373506572666f726d616e636554657374735f312e706e67
> 
> It seems like the test had random spikes in the pass as well

trust me, it's not even close to what we call flaky 😄 spikes like these are most likely caused by "random" data alignment, we might fix them eventually via memory randomization in BDN

**Review by EgorBo — APPROVED** [review]

**Comment by EgorBo** [comment]
Eventually, I believe, we will be able to recognize more stuff at IL prescan stage, e.g "noreturn" calls, or special case <ImplDetails>.ThrowIfNull call as we might start to see it more and more often in future.

**Pull request merged**
