### PR TITLE
[release/6.0] Bump the macOS image to one that isn't EOL yet

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by lewing** [comment]
needs #68847

**Review by carlossanlop — APPROVED** [review]

**Comment by carlossanlop** [comment]
> needs #68847

Considering https://github.com/dotnet/runtime/pull/68847#issuecomment-1241331578 failed to backport, what's the plan with this?

**Comment by steveisok** [comment]
> > needs #68847
> 
> Considering [#68847 (comment)](https://github.com/dotnet/runtime/pull/68847#issuecomment-1241331578) failed to backport, what's the plan with this?

Let me see what I can do to resolve this.

**Comment by steveisok** [comment]
@tarekgh since the ICU changes needed to be manually integrated, can you please sanity check me?

**Review by tarekgh — APPROVED** [review]
The changes LGTM. 

I hope this change will stay for some time before releasing it to reduce the risk in the servicing release. I am not seeing any problem though.

**Comment by steveisok** [comment]
Since this contains some ICU changes, I think having tactics approve / be aware is the right way to go.

**Comment by carlossanlop** [comment]
Approved, signed off, CI is green. Ready to merge. :shipit:

**Pull request merged**
