### PR TITLE
Run stress tests on private Asp.Net Core package

### PR DESCRIPTION
**Pull request by alnikola**
Currently, it's possible to run stress tests on privately built CoreCLR and libraries by executing `load-corefx-testhost.ps1 -b` followed by `run-docker-compose.ps1 -b`. However, it was not possible to run the stress server on a private Asp.Net Core package which is used for private libraries build.

This PR adds a new `-pa` parameter to `run-docker-compose.ps1` which builds a server container with a private Asp.Net Core package version.

### CODE REVIEW

**Comment by wfurt** [comment]
Think what ever is under eng/* should be submitted to arcade project (and than that's roll in automatically) 
cc: @safern @ViktorHofer

**Comment by wfurt** [comment]
yes, I understand that. But lot of the eng/build files live in arcade repo and are mirrored to runtime. But it seems like docker is not one one them.

**Comment by safern** [comment]
What needs to go into arcade is everything under `eng/common` not under `eng`.

**Review by davidsh — APPROVED** [review]
LGTM. 

I would recommend you manually invoke the stress tests pipelines in this PR to validate it. Currently the stress tests aren't automatically invoked for every PR.

**Pull request merged**
