### PR TITLE
Fix armel build

### PR DESCRIPTION
**Pull request by gbalykov**
Build for armel fails after #47502 with:
```
/home/runtime/src/coreclr/tools/aot/crossgen2/crossgen2.csproj(114,5): error MSB3030: Could not copy the file "/home/runtime/artifacts/bin/coreclr/Linux.armel.Release/x64/libclrjit_unix_armel_x64.so" because it was not found.
```

This change is a cleanup for armel, since there was some inconsistency. 

Before:
```
ARCH_HOST_NAME=armel
ARCH_TARGET_NAME=arm
```

After:
```
ARCH_HOST_NAME=armel
ARCH_TARGET_NAME=armel
```

cc @alpencolt

### CODE REVIEW

**Comment by gbalykov** [comment]
cc @jkotas

**Comment by jkotas** [comment]
Looks like a follow up on #41126 . @davidwrighton Could you please take a look?

**Review by davidwrighton — APPROVED** [review]
Yes, this looks good

**Comment by gbalykov** [comment]
Thanks!

**Pull request merged**
