### PR TITLE
[LoongArch64] Fix the arithmetic shift right in CodeGen::genSaveCalleeSavedRegistersHelp.

### PR DESCRIPTION
**Pull request by sunlijun-610**

### CODE REVIEW

**Comment by sunlijun-610** [comment]
@shushanhf Could you please review this change？
Thanks！

**Comment by huoyaoyuan** [comment]
Is this also applicable to other archs?

https://github.com/dotnet/runtime/blob/35b94da00d4a79de3252ba79b6d3942cc3716405/src/coreclr/jit/codegenriscv64.cpp#L214

**Review by shushanhf — APPROVED** [review]
LGTM
Thanks

**Comment by huoyaoyuan** [comment]
> But for riscv64, callee saved float registers are F8, F9, F18-F27, so `maskSaveRegs` here cannot be a negative number. So I didn't apply to riscv64.

It doesn't have real impact here, but using unsigned right shift will make the code more correct for all archs.

**Comment by sunlijun-610** [comment]
> It doesn't have real impact here, but using unsigned right shift will make the code more correct for all archs.

OK, thanks! I've applied it to riscv64 too.
Thanks a lot!

**Comment by sunlijun-610** [comment]
@jakobbotsch Could you please review this PR?
Thanks a lot!

**Review by jakobbotsch — APPROVED** [review]

**Pull request merged**
