### PR TITLE
Remove --flat from default dsymutil options

### PR DESCRIPTION
**Pull request by agocke**
--flat is a diagnostic-only option and not fully supported. It can still be specified if necessary through the DsymUtilOptions property and NativeSymbolExt property, but it will no longer be the default.

### CODE REVIEW

**Comment by jkotas** [comment]
I assume that this is related to https://github.com/dotnet/runtime/issues/86734.

Are we going to need a follow up change to upload symbols in the dsym format for AOT compiled binaries in the official builds?

We have been using `--flat` option for unmanaged binaries https://github.com/dotnet/runtime/blob/d40ca00ca2fb5411ff159b2e84b800e8dfbd681e/eng/native/functions.cmake#L419 . Should we remove the `--flat` option for the unmanaged binaries as well?

**Comment by filipnavara** [comment]
> Should we remove the `--flat` option for the unmanaged binaries as well?

There's a tracking issue for that - https://github.com/dotnet/runtime/issues/88286.

I would be happy if this PR goes in since it makes debugging apps much easier but there's always the concern about SymStore and related utilities that are not able to handle dSYM yet.

**Comment by agocke** [comment]
> Are we going to need a follow up change to upload symbols in the dsym format for AOT compiled binaries in the official builds?

Yeah, we can either set the `--dwarf` flag just for our CI, or we can support zipping up the dsym bundle. I'd prefer the latter, but will see if I can do the former in this PR just to unblock things.

As for native builds, I think they should also use the dsym bundle eventually, but it matters slightly less since it's only for debugging coreclr itself, which is a more uncommon user scenario. In this case, debugging Mac-compiled Native AOT apps is a first-class scenario, so we should use the Apple-preferred thing by default.

**Comment by agocke** [comment]
Well, I looked in the crossgen2 symbols package and I actually don't see the `.dwarf` file in there. Is that expected, @hoyosjs?

**Comment by hoyosjs** [comment]
No, that'd break postmortem of crossgen. There's several problems. Right now the easiest one is telling the SDK that dsym is a symbol file, after you need to teach the uploaders how to index dsyms.

**Review by jkotas — APPROVED** [review]
This change looks good on its own. It would be nice to have the follow up plan figured out before merging.

**Comment by agocke** [comment]
@hoyosjs can the symbol uploader index .dwarf files today? Also, `.dsym` is a folder. Would we want to zip it?

**Comment by hoyosjs** [comment]
I thought it was an archive. Don't know of prior art in symbol packages, need to check

**Pull request merged**
