### PR TITLE
Add microsoft-extensions to area owners

### PR DESCRIPTION
**Pull request by danmoseley**
@maryamariyan is this right? 

Also should area-Microsoft.Extensions be named with a hyphen?

### CODE REVIEW

**Comment by danmosemsft** [comment]
@ajcvickers do the data rows match your expectations?

**Comment by danmosemsft** [comment]
also area-Codegen-LLVM-mono is missing an area owner - @marek-safar who are the owners for that?

**Comment by marek-safar** [comment]
@danmosemsft added to this PR

**Review by stephentoub — APPROVED** [review]

**Comment by ajcvickers** [comment]
@danmosemsft Yes.

**Review by ajcvickers — APPROVED** [review]

**Review by maryamariyan — APPROVED** [review]

**Pull request merged**
