### PR TITLE
[release/8.0] Stable branding for .NET 8 GA

### PR DESCRIPTION
**Pull request by carlossanlop**
This is it folks.

### CODE REVIEW

**Review by hoyosjs — APPROVED** [review]

**Comment by lewing** [comment]
This needs https://github.com/aspnet/Benchmarks/pull/1916 to land first as things are.  I can work around that but not tonight

**Review by ViktorHofer — APPROVED** [review]

**Review by dkurepa — APPROVED** [review]

**Comment by lewing** [comment]
Failure now in runtime (Build windows-x64 Checked NativeAOT) is

```
      > C:\h\w\B2ED097A\w\AEAA094B\e\tracing\eventpipe\processinfo3\processinfo3\processinfo3.cmd
      Expected: True
      Actual:   False
      Stack Trace:
        D:\a\_work\1\s\artifacts\tests\coreclr\windows.x64.Checked\TestWrappers\tracing.eventpipe\tracing.eventpipe.XUnitWrapper.cs(1040,0): at tracing_eventpipe._processinfo3_processinfo3_processinfo3_._processinfo3_processinfo3_processinfo3_cmd()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
      Output:
        Unhandled Exception: System.Exception: ClrProductVersion must match. Expected: "8.0.0-ci", received: "8.0.0"
           at Tracing.Tests.Common.Utils.Assert(Boolean predicate, String message) + 0x36
           at Tracing.Tests.ProcessInfoValidation.ProcessInfoValidation.Main() + 0x29ca
           at processinfo3!<BaseAddress>+0xa8c02b
```

**Comment by akoeplinger** [comment]
Not sure why it didn't show up in servicing readiness but we probably need to this override to NativeAOT corelib, it is there both in CoreCLR and Mono corelib:

https://github.com/dotnet/runtime/blob/0f2cf16467dbd376bf4ac3040262699f850a9155/src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj#L46-L48

**Comment by ericstj** [comment]
Here's the test:
https://github.com/dotnet/runtime/blob/0f2cf16467dbd376bf4ac3040262699f850a9155/src/tests/tracing/eventpipe/processinfo2/processinfo2.cs#L263

Its checking the `AssemblyInformationalVersionAttribute` on System.Private.Corelib against the diagnostics protocol which returns CLR_PRODUCT_VERSION which seems to be defined as RuntimeProductVersion -> https://github.com/dotnet/runtime/blob/0f2cf16467dbd376bf4ac3040262699f850a9155/eng/versioning.targets#L167

**Comment by dkurepa** [comment]
> Why didn't this show up in servicing readiness? cc @dkurepa

I'm not sure. I just checked and it definitely didn't show up

**Comment by akoeplinger** [comment]
This is actually not a regression, I checked the `runtime.linux-x64.Microsoft.DotNet.ILCompiler` 7.0.12 nuget package and it does include the `servicing` version suffix in AssemblyInformationalVersionAttribute:

```
  .custom instance void System.Reflection.AssemblyInformationalVersionAttribute::.ctor(string) = ( 01 00 42 37 2E 30 2E 31 32 2D 73 65 72 76 69 63   // ..B7.0.12-servic
                                                                                                   69 6E 67 2E 32 33 34 37 37 2E 32 30 2B 34 61 38   // ing.23477.20+4a8
                                                                                                   32 34 65 66 33 37 63 61 61 35 31 30 37 32 32 32   // 24ef37caa5107222
                                                                                                   31 35 38 34 63 36 34 63 62 66 31 35 34 35 35 66   // 1584c64cbf15455f
                                                                                                   34 30 36 63 61 00 00 )                            // 406ca..
```

... while a normal Microsoft.NETCore.App.Runtime.linux-x64 CoreCLR runtime pack does not:

```
  .custom instance void System.Reflection.AssemblyInformationalVersionAttribute::.ctor(string) = ( 01 00 2F 37 2E 30 2E 31 32 2B 34 61 38 32 34 65   // ../7.0.12+4a824e
                                                                                                   66 33 37 63 61 61 35 31 30 37 32 32 32 31 35 38   // f37caa5107222158
                                                                                                   34 63 36 34 63 62 66 31 35 34 35 35 66 34 30 36   // 4c64cbf15455f406
                                                                                                   63 61 00 00 )                                     // ca..
```

I assume this test didn't run on NativeAOT in 7.0.

**Comment by carlossanlop** [comment]
@akoeplinger are you the right person to look into this remaining failure?

**Comment by akoeplinger** [comment]
@carlossanlop yes I'm 99% sure I know the fix, if it works should I push to this PR or should we go to main first and then backport?

**Comment by carlossanlop** [comment]
> @carlossanlop yes I'm 99% sure I know the fix, if it works should I push to this PR or should we go to main first and then backport?

Let's do main + backport. Thanks!

**Comment by carlossanlop** [comment]
Actually, since we're late, i think it will be better to do main + submit the fix to this PR directly, not backport. @akoeplinger

**Comment by akoeplinger** [comment]
Pushed, main PR is in https://github.com/dotnet/runtime/pull/93889

**Review by hoyosjs — APPROVED** [review]

**Review by mmitche — APPROVED** [review]

**Comment by mmitche** [comment]
Thanks, please merge ASAP.

**Comment by akoeplinger** [comment]
> Changes look OK to me, but FWIW Roslyn always ships with a suffix in the version. It doesn't seem like we care much either way. This test seems overly aggressive to me.

@agocke this is actually exposed through `System.Runtime.InteropServices.RuntimeInformation.FrameworkDescription` and there have been multiple reports in the past if it shows the wrong version (see https://github.com/dotnet/runtime/issues/45812 and duplicated issues)

https://github.com/dotnet/runtime/blob/64b93dd62cc7a6bd47e57c0bb909450e2301c8f4/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/RuntimeInformation.cs#L14-L34

**Pull request merged**
