### PR TITLE
Add DOTNET_JitDisasmOnlyOptimized knob

### PR DESCRIPTION
**Pull request by EgorBo**
We already have `DOTNET_JitDumpTier0` to hide unoptimized dumps, this PR add the same for JitDisasm. Users often don't care about unoptimized asm.

### CODE REVIEW

**Review by jakobbotsch — COMMENTED** [review]
The name is `DisasmTier0` but the behavior is `DisasmOnlyTier1`. I'd suggest renaming it to `JitDisasmOnlyOptimized` and switch the check to `OptimizationEnabled()` instead.

**Comment by EgorBo** [comment]
> The name is `DisasmTier0` but the behavior is `DisasmOnlyTier1`. I'd suggest renaming it to `DisasmOnlyOptimized` and switch the check to `OptimizationEnabled()` instead.

OptimizationEnabled() triggered an assert because it's not yet initialized so I consumed the flag directly to avoid changing too much code unnecessarily. Tier1 flag means "optimizations are allowed", I'm fine renaming the knob though

**Comment by jakobbotsch** [comment]
I don't think the check is correct as it stands. It does not cover scenarios where the JIT switches from unoptimized code to optimized code or vice versa. Also, do crossgen2/ILC even set the `Tier1` flag?

I think you should just delay checking for these conditions until we've made all the decisions around optimization level, including switching between optimized/deoptimizing, and switch to `OptimizationEnabled()`. We can do that for `JitDisasm`, but we cannot really do it for `JitDump`.

**Review by jakobbotsch — APPROVED** [review]

**Comment by EgorBo** [comment]
Failure is https://github.com/dotnet/runtime/issues/96904

**Comment by BruceForstall** [comment]
Don't forget to cc jit-contrib on PRs.

**Comment by EgorBo** [comment]
> Don't forget to cc jit-contrib on PRs.

Yep, I forgot because Jakob approved it before I requested for review to anyone 🙂

**Pull request merged**
