### PR TITLE
Remove -O=-float32 from Default AOT process arguments

### PR DESCRIPTION
**Pull request by steveisok**
Addresses https://github.com/dotnet/runtime/issues/51992 and https://github.com/dotnet/runtime/issues/53033

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by lambdageek** [comment]
@steveisok Is this ok to merge?

**Comment by steveisok** [comment]
> @steveisok Is this ok to merge?

Yes, failures are unrelated.

**Comment by akoeplinger** [comment]
@steveisok we added this because XI is using it here: https://github.com/xamarin/xamarin-macios/blob/aad913db8673637150af01b13e76605966b8f14a/msbuild/Xamarin.iOS.Tasks.Core/Tasks/MTouchTaskBase.cs#L169-L172

We should figure out if we want to change XI too.

**Comment by vargaz** [comment]
That was probably added to avoid changing the behavior of preexisting apps.

**Pull request merged**
