### PR TITLE
Add ActivityContext.TryParse overload

### LINKED ISSUE #42575: ActivityContext.TryParse should support IsRemote
### Description

When using ActivitySource I wanted to support IsRemote (for opentelemetry), as the majority of the time any activity started with a w3c trace context will be remote.

To start an activity with IsRemote set needs an ActivityContext, the best option appears to be use:
ActivityContext.TryParse(traceParent, traceState, out var context)
However, a context then needs creating to copy the parsed context, and set IsRemote.

It would be useful if TryParse could provide a version that can pass IsRemote into the ActivityContext.  I'd expect the majority of new activities that use TryParse are providing a traceparent and state from a remote caller.

### Configuration
.net framework 4.8
Windows 10
x64

https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/5.0.0-rc.1.20451.14

### Regression?

No, new functionality

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/42575

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @CodeBlanch @cijothomas @reyang @noahfalk

**Review by stephentoub — APPROVED** [review]

**Review by reyang — APPROVED** [review]
LGTM.

**Review by noahfalk — APPROVED** [review]
LGTM!

**Review by CodeBlanch — APPROVED** [review]
LGTM

**Review by cijothomas — APPROVED** [review]

**Pull request merged**
