### PR TITLE
JIT: Propagate only BBF_COPY_PROPAGATE flags during inliner substitution

### PR DESCRIPTION
**Pull request by jakobbotsch**
Quite a few diffs expected.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS @EgorBo 
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=72179&view=ms.vss-build-web.run-extensions-tab)

Diffs due to less aggressive inlining as we no longer mark inlining blocks with `BBF_PROF_WEIGHT` if the inlinee's `ret` instruction is in a hot block.

**Review by AndyAyersMS — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Failure is #77241

**Comment by EgorBo** [comment]
Improvements on arm64-ubuntu: https://github.com/dotnet/perf-autofiling-issues/issues/9678

**Pull request merged**
