### PR TITLE
[release/6.0] [wasm][debugger] Fixing the race condition while modifying pending_ops

### PR DESCRIPTION
**Pull request by thaystg**
Fixing the race condition, modifying pending_ops, as discussed here:
https://github.com/dotnet/runtime/pull/76900

Fixes: https://github.com/dotnet/runtime/issues/68402

Backport of https://github.com/dotnet/runtime/pull/65752/commits/fdc0d16020874da55372211388303f51e4b852eb to release/6.0

## Customer Impact
There isn't a easy way to reproduce it, but the customer is debugging his app, then suddenly this error message is showed, and the debugging session is aborted, the customer needs to start the app again to continue debugging.
`fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] DevToolsProxy::Run: Exception System.ArgumentException: The tasks argument included a null value. (Parameter 'tasks')    at System.Threading.Tasks.Task.WhenAny(Task[] tasks)    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
`
There was a racing condition while adding and removing items from pending_ops, that is the list with the messages which were sent from the BrowserDebugProxy, @radical refactored this code and now it's using ChannelWriter and ChannelReader to avoid this racing condition on the pending_ops list.

## Testing
Manually tested.

## Risk
Low risk, applying a change that is already landed on .net7.

IMPORTANT: Is this backport for a servicing release? If so and this change touches code that ships in a NuGet package, please make certain that you have added any necessary [package authoring](https://github.com/dotnet/runtime/blob/main/docs/project/library-servicing.md) and gotten it explicitly reviewed.

### CODE REVIEW

**Comment by thaystg** [comment]
@lewing @radical if you think this makes sense please let me know. Then I can send the email to tactics.

**Review by lewing — APPROVED** [review]
Active customer issue on LTS with a well tested fix, makes sense to me if you're confident in the backport.

**Comment by carlossanlop** [comment]
Approved by Tactics (7.0.3).
Signed off by area owner.
No OOB changes needed (wasm).
CI failures:
- The browser legs are failures when attempting to cancel after reaching the timeout. @thaystg do you think they could be related? Do you want to re-run?
- OSX failure is known/unrelated: https://github.com/dotnet/runtime/issues/80252
- MacCatalyst is known/unrelated, and a fix was merged shortly after this PR was created, hence why it hit it: https://github.com/dotnet/runtime/pull/79097
- tvOS, Android, iOS are warnings, unrelated.

**Comment by thaystg** [comment]
The wasm failure is not related with the PR. The debugger-tests I ran locally and they are passing.

**Review by radical — APPROVED** [review]

**Comment by carlossanlop** [comment]
Thanks for checking. Let's get this merged. :shipit:

**Comment by mwasson74** [comment]
Hello, @thaystg!! I do not know the correct terminology to use but how can I tell which version of .NET 6 and when this will be released to the public?

Thank you!!

**Comment by carlossanlop** [comment]
@mwasson74 Version 6.0.14 will contain this fix, which is the February Servicing Release.

**Comment by mwasson74** [comment]
Excellent, thanks so much @carlossanlop!! I saw the milestone was .NET 7 and wasn't sure if it was on the right "track" to being released to a new .NET 6 version.

**Comment by carlossanlop** [comment]
Apologies. I applied the wrong milestone but it's corrected now.

**Pull request merged**
