### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by UdayKharatmol**
Issue : Grammatically wrong Sentence
Changes :  removed s because instructions explains not correct grammatically and added the word before installation

I hope that @dotnet/dnr-codeflow should took attention on this grammatical mistakes.

### CODE REVIEW

**Comment by danmoseley** [comment]
The second one is reasonable - could you update your PR to just include that?

**Review by UdayKharatmol — COMMENTED** [review]
Issue : Grammatically wrong Sentence
Changes : removed s because instructions explains not correct grammatically and added the word before installation

I hope that you should took attention on this grammatical mistakes.

**Comment by UdayKharatmol** [comment]
Yah sure

**Review by danmoseley — APPROVED** [review]

**Comment by danmoseley** [comment]
@carlossanlop what happened to the markdown linting step?

**Comment by danmoseley** [comment]
thanks @UdayKharatmol

**Pull request merged**
