### PR TITLE
Remove bounds checks, improving performance

### PR DESCRIPTION
**Pull request by sonnemaf**
These changes eliminate bounds checks. This will improve the performance.

### CODE REVIEW

**Comment by stephentoub** [comment]
> These changes eliminate bounds checks

It might remove the JIT-injected ones, but the `i < _size` being added is still a bounds check, just a different shape.

Can you share perf numbers from this change? And for another comparison, what happens if you instead enumerate over a ReadOnlySpan initially created from 0 to _size?

Thanks.

**Comment by GrabYourPitchforks** [comment]
This is a behavioral breaking change for the scenario where the predicate mutates the list contents.

**Comment by stephentoub** [comment]
> This is a behavioral breaking change for the scenario where the predicate mutates the list contents.

Good point.  It makes me sad that someone would do that, but I've no doubt someone is.

**Comment by sonnemaf** [comment]
I created the benchmark you suggested. It turned out that my initial improvement had no performance gain (as you expected). Your suggested improvement using a ReadOnlySpan is 14% faster. So I modified the code for the List<T> class (methods Find, FindAll and TrueForAll). Maybe this solution can be used in other methods too (FindLast, FindIndex, ...). I will investigate this next week if you agree that this is useful. 

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace ConsoleApp418 {
    class Program {
        static void Main(string[] args) {
            var l = new List<double>(new double[1024], 800);

            BenchmarkRunner.Run<BM>();
        }
    }

    public class BM {

        private List<double> _list;

        [Params(32, 256, 1024, 8192)]
        public int Size { get; set; } 

        [GlobalSetup]
        public void Setup() {
            this._list = new List<double>(new double[Size], (int)(Size * 0.8));
        }

        [Benchmark(Baseline = true)]
        public bool OriginalTrueForAll() {
            return _list.TrueForAll(n => n > -1);
        }

        [Benchmark]
        public bool TrueForAllLocalArray() {
            return _list.TrueForAllLocalArray(n => n > -1);
        }

        [Benchmark]
        public bool TrueForAllReadOnlySpan() {
            return _list.TrueForAllReadOnlySpan(n => n > -1);
        }

    }


    class List<T> {

        private T[] _items;
        private int _size;

        public List(T[] items, int size) {
            _items = items;
            _size = size;
        }

        public bool TrueForAll(Predicate<T> match) {
            if (match == null) {
                ArgumentNullException.ThrowIfNull(match);
            }
            for (int i = 0; i < _size; i++) {
                if (!match(_items[i])) {
                    return false;
                }
            }
            return true;
        }

        public bool TrueForAllLocalArray(Predicate<T> match) {
            if (match == null) {
                ArgumentNullException.ThrowIfNull(match);
            }
            T[] items = _items;
            for (int i = 0; i < items.Length && i < _size; i++) {
                if (!match(items[i])) {
                    return false;
                }
            }
            return true;
        }

        public bool TrueForAllReadOnlySpan(Predicate<T> match) {
            if (match == null) {
                ArgumentNullException.ThrowIfNull(match);
            }
            var span = new ReadOnlySpan<T>(_items, 0, _size);
            for (int i = 0; i < span.Length; i++) {
                if (!match(span[i])) {
                    return false;
                }
            }
            return true;
        }

    }
}
```


``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
AMD Ryzen 9 3900X, 1 CPU, 24 logical and 12 physical cores
.NET SDK=6.0.200
  [Host]     : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT
  DefaultJob : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT


```
|                 Method | Size |         Mean |     Error |    StdDev | Ratio | RatioSD |
|----------------------- |----- |-------------:|----------:|----------:|------:|--------:|
|     **OriginalTrueForAll** |   **32** |     **50.49 ns** |  **0.115 ns** |  **0.102 ns** |  **1.00** |    **0.00** |
|   TrueForAllLocalArray |   32 |     50.87 ns |  0.804 ns |  0.752 ns |  1.01 |    0.01 |
| TrueForAllReadOnlySpan |   32 |     43.44 ns |  0.373 ns |  0.330 ns |  0.86 |    0.01 |
|                        |      |              |           |           |       |         |
|     **OriginalTrueForAll** |  **256** |    **344.43 ns** |  **0.853 ns** |  **0.756 ns** |  **1.00** |    **0.00** |
|   TrueForAllLocalArray |  256 |    342.63 ns |  0.702 ns |  0.656 ns |  0.99 |    0.00 |
| TrueForAllReadOnlySpan |  256 |    296.47 ns |  0.561 ns |  0.469 ns |  0.86 |    0.00 |
|                        |      |              |           |           |       |         |
|     **OriginalTrueForAll** | **1024** |  **1,354.17 ns** |  **3.353 ns** |  **2.800 ns** |  **1.00** |    **0.00** |
|   TrueForAllLocalArray | 1024 |  1,350.76 ns |  3.297 ns |  3.084 ns |  1.00 |    0.00 |
| TrueForAllReadOnlySpan | 1024 |  1,183.51 ns | 22.493 ns | 21.040 ns |  0.87 |    0.02 |
|                        |      |              |           |           |       |         |
|     **OriginalTrueForAll** | **8192** | **10,786.04 ns** | **21.449 ns** | **20.063 ns** |  **1.00** |    **0.00** |
|   TrueForAllLocalArray | 8192 | 10,815.82 ns | 31.106 ns | 25.975 ns |  1.00 |    0.00 |
| TrueForAllReadOnlySpan | 8192 |  9,273.35 ns | 43.096 ns | 35.987 ns |  0.86 |    0.00 |

**Comment by sonnemaf** [comment]
> > This is a behavioral breaking change for the scenario where the predicate mutates the list contents.
> 
> Good point. It makes me sad that someone would do that, but I've no doubt someone is.

Yet it is. Does that mean it is a NO GO? Or do these method need a Version check (which is also breaking behavior)?

**Comment by stephentoub** [comment]
I appreciate your submitting this PR, but for the cited reason, I'm going to close it. If you can find other places to improve perf, we'd welcome more PRs.

**Pull request closed without merging**
