### PR TITLE
[wasm] Fix S.T.Regex test failures due to line ending differences

### LINKED ISSUE #65978: [wasm] Windows test failures - `PrecompiledRegex_*` in `System.Text.RegularExpressions.Tests`
Hitting on rolling builds:

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1634259&view=logs&j=a07e672c-d717-5036-7657-9f851d8c04dc&t=95c8462d-76dc-506a-26a4-fefb7abc2e07). The full console log doesn't seem to be accessible, but the failure can be seen in the [wasm app output](https://dev.azure.com/dnceng/public/_build/results?buildId=1634259&view=logs&j=a07e672c-d717-5036-7657-9f851d8c04dc&t=95c8462d-76dc-506a-26a4-fefb7abc2e07).

```
[FAIL] System.Text.RegularExpressions.Tests.PrecompiledRegexScenarioTest.PrecompiledRegex_SplitTest
Assert.Equal() Failure
                                 ↓ (pos 3)
Expected: ···"", "4", "success", "\nbsdf135success1245somethingelse\ncsdf1···
Actual:   ···"", "4", "success", "\nbsdf135success1245somethingelse\r\ncsd···
                                 ↑ (pos 3)
   at System.Text.RegularExpressions.Tests.PrecompiledRegexScenarioTest.PrecompiledRegex_SplitTest() in /_/src/libraries/System.Text.RegularExpressions/tests/PrecompiledRegexScenarioTest.cs:line 73
   at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386

[FAIL] System.Text.RegularExpressions.Tests.PrecompiledRegexScenarioTest.PrecompiledRegex_MatchesTest
Assert.Equal() Failure
                                 ↓ (pos 27)
Expected: ···success1245something\r
Actual:   ···success1245something
                                 ↑ (pos 27)
   at System.Text.RegularExpressions.Tests.PrecompiledRegexScenarioTest.PrecompiledRegex_MatchesTest() in /_/src/libraries/System.Text.RegularExpressions/tests/PrecompiledRegexScenarioTest.cs:line 36
   at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters) in /_/src/mono/System.Private.
CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
```

And it seems to have started with https://github.com/dotnet/runtime/commit/26b91db713579c9919315a25dff12cd55f3637b1 .

### PR DESCRIPTION
**Pull request by radical**
Fixes https://github.com/dotnet/runtime/issues/65978 .

When running `System.Text.RegularExpressions.Tests` tests on windows and
targeting `Browser`, the line ending differs between host and target
systems. Use helper `LineEndingsHelper.Normalize` method to update
expected strings.

The `Browser` Environment.NewLine is `\n`, while windows use `\r\n`.

### CODE REVIEW

**Comment by joperezr** [comment]
Makes sense, thanks for fixing @radical. Looks like at least the two LibraryTests legs that are failing are still relevant to the change though, any clues why this fix isn't working there?

**Comment by radical** [comment]
The only relevant failure left is:
```
[FAIL] System.Text.RegularExpressions.Tests.PrecompiledRegexScenarioTest.PrecompiledRegex_SplitTest
Assert.Equal() Failure
                                 ↓ (pos 3)
Expected: ···"", "4", "success", "\nbsdf135success1245somethingelse\ncsdf1···
Actual:   ···"", "4", "success", "\nbsdf135success1245somethingelse\r\ncsd···
                                 ↑ (pos 3)
   at System.Text.RegularExpressions.Tests.PrecompiledRegexScenarioTest.PrecompiledRegex_SplitTest() in /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/PrecompiledRegexScenarioTest.cs:line 73
   at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
```

I'm building locally on windows now.

**Comment by radical** [comment]
it doesn't fail locally on windows :/

**Review by vargaz — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
