### PR TITLE
Fix Vector<T> != operator

### LINKED ISSUE #78163: [mono] Performance regression in many places caused by #77562
We see many large regressions caused by #77562

Microbenchmarks issues:

https://github.com/dotnet/perf-autofiling-issues/issues/9599
https://github.com/dotnet/perf-autofiling-issues/issues/9612
https://github.com/dotnet/perf-autofiling-issues/issues/9636
https://github.com/dotnet/perf-autofiling-issues/issues/9637

### PR DESCRIPTION
**Pull request by radekdoulik**
Also fixes https://github.com/dotnet/runtime/issues/78163

### CODE REVIEW

**Comment by dakersnar** [comment]
This is closely related to the fix we merged here: https://github.com/dotnet/runtime/pull/77815. Are there any other locations that might need this fix?

**Review by dakersnar — APPROVED** [review]

**Review by tannergooding — APPROVED** [review]

**Comment by hughbe** [comment]
surprised there isn't a test for this?

**Comment by filipnavara** [comment]
> surprised there isn't a test for this?

https://github.com/dotnet/runtime/pull/77815#issuecomment-1301541719 😅

**Comment by hughbe** [comment]
Ah... well I think we should also have some deterministic tests IMO

**Comment by tannergooding** [comment]
> Ah... well I think we should also have some deterministic tests IMO

We were supposed to have some hard coded tests to cover edges like this, but it looks like they never got checked in.

I'll log an issue and track getting this all audited/fixed.

**Comment by BruceForstall** [comment]
Does this need to get back-ported to 7?

**Comment by tannergooding** [comment]
No, this was a .NET 8 exclusive change.

**Pull request merged**
