### PR TITLE
Changed GetNetworkInterfaces method to to retrieve information related to all interfaces

### LINKED ISSUE #89990: `NetworkInterface.GetAllNetworkInterfaces()` doesn't list disabled adapters on Windows
### Description

On Windows, a disabled network adapter is not listed by `NetworkInterface.GetAllNetworkInterfaces()`.

### Reproduction Steps

1.
    ```csharp
    foreach (var ni in System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces())
    {
        Console.WriteLine(ni.Name + ": " + ni.OperationalStatus);
    }
    ```
2. Disable a network adapter.
3. Run the code again.

### Expected behavior

The disabled adapter is listed with `OperationalStatus.Down`.

### Actual behavior

The disabled adapter is not listed.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

Windows 10
.NET 6 / .NET 7

### Other information

_No response_

### PR DESCRIPTION
**Pull request by MojtabaTajik**
Based on [Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getadaptersaddresses), we should pass "GAA_FLAG_INCLUDE_ALL_INTERFACES" to retrieve information related to all interfaces.

Fix #89990

### CODE REVIEW

**Review by wfurt — COMMENTED** [review]
test failure seems related
```
  Starting:    System.Net.NetworkInformation.Functional.Tests (parallel test collections = on [2 threads], stop on fail = off)
    System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions [FAIL]
      Assert.Equal() Failure: Values differ
      Expected: 6
      Actual:   0
      Stack Trace:
        /_/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs(55,0): at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs(36,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
      Output:
        - NetworkInterface -
        Name: Ethernet 2
        Description: Microsoft Hyper-V Network Adapter #2
        ID: {5A812509-8FA5-4802-9EAC-92A43D5C3D7D}
        IsReceiveOnly: False
        Type: Ethernet
        Status: Up
        Speed: 50000000000
        SupportsMulticast: True
        GetPhysicalAddress(): 000D3A5A03C9
        - NetworkInterface -
        Name: Loopback Pseudo-Interface 1
        Description: Software Loopback Interface 1
        ID: {46BCBBDA-D902-11EE-A1F4-806E6F6E6963}
        IsReceiveOnly: False
        Type: Loopback
        Status: Up
        Speed: 1073741824
        SupportsMulticast: True
        GetPhysicalAddress(): 
        - NetworkInterface -
        Name: vEthernet (nat)
        Description: Hyper-V Virtual Ethernet Adapter
        ID: {30CAB5C1-869C-4879-AF7F-BF5232024FC8}
        IsReceiveOnly: False
        Type: Ethernet
        Status: Up
        Speed: 10000000000
        SupportsMulticast: True
        GetPhysicalAddress(): 00155D4F8F8B
        - NetworkInterface -
        Name: vSwitch (nat)-Hyper-V Virtual Switch Extension Filter-0000
        Description: Hyper-V Virtual Switch Extension Adapter-Hyper-V Virtual Switch Extension Filter-0000
        ID: {9330C02E-F697-11EE-A203-000D3A5A03C9}
        IsReceiveOnly: False
        Type: Ethernet
        Status: Up
        Speed: 10000000000
        SupportsMulticast: True
        GetPhysicalAddress(): 
  Finished:    System.Net.NetworkInformation.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.NetworkInformation.Functional.Tests  Total: 244, Errors: 0, Failed: 1, Skipped: 0, Time: 0.725s
```

**Comment by MojtabaTajik** [comment]
@wfurt I just investigated the issues related to the change because now we list all interfaces.
The failed test is related to this line in tests:

https://github.com/dotnet/runtime/blob/aab9a4a00e8969323ad5c79ebe3bd05c055511ce/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs#L53-L56

Based on test logs, it fails on "Microsoft Hyper-V Network Adapter" I just enabled Hyper-V on my local and got the same error. After investigation, I figured out there are some NICs without a Mac address, so this assertion part of this test is invalid and should be removed.

Based on the documentation of [GetAdaptersAddresses](https://learn.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-getadaptersaddresses), this change will retrieve even those addresses associated with adapters not bound to an address family specified in the Family parameter.

> If the GAA_FLAG_INCLUDE_ALL_INTERFACES is set, then all NDIS adapters will be retrieved even those addresses associated with adapters not bound to an address family specified in the Family parameter. When this flag is not set, then only the addresses that are bound to an adapter enabled for the address family specified in the Family parameter are returned.


I just removed that assertion because it's not valid anymore.

**Comment by wfurt** [comment]
> I just removed that assertion because it's not valid anymore.

what does it return @MojtabaTajik? I'm generally ok with the approach. However it seems like this only one call to `GetPhysicalAddress().GetAddressBytes()` so it may be in just to see it does not crash or throw. If the length is predictable perhaps we can something like `Assert.True(length == 0 || length == 6)` ??? If that works could we perhaps even drop the check for `Speed`???

**Comment by MojtabaTajik** [comment]
@wfurt Indeed, that's a better approach; I just updated my PR.

**Review by wfurt — APPROVED** [review]
LGTM.  Thanks @MojtabaTajik for the contribution.

**Comment by wfurt** [comment]
all test failures are known errors.

**Comment by LoopedBard3** [comment]
Related performance regressions:
Windows x64: https://github.com/dotnet/perf-autofiling-issues/issues/33051

**Pull request merged**
