### PR TITLE
Failfast on Vector256 test failure

### PR DESCRIPTION
**Pull request by jkotas**
Investigating #76280

### CODE REVIEW

**Comment by tannergooding** [comment]
So the dump file is here, but the PDBs aren't available so we don't get symbol info.

The merge commit it was built against (13875a35bb)  also is no longer available via `refs/pull/76656/head` (which is 381039e, the commit you publicly see) nor `refs/pull/76656/merge` (which is currently 1cb1385dd8, the internal commit of this PR merged against `dotnet/runtime/main` for the purposes of CI testing and checking for conflicts/etc)

**Comment by tannergooding** [comment]
Ah, found the artifacts in helix. Unfortunately, it doesn't show anything interesting at first glance:
image

It's unclear which stack entry, if any, is the disassembly for the managed method and so it isn't clear if something is somehow different under the failure scenario.

I've still yet to reproduce the issue locally which makes debugging this incredibly difficult.

**Comment by AaronRobinsonMSFT** [comment]
This is what I used to get the symbols and artifacts.

`runfo get-helix-payload -j 093c4baa-1097-4841-8e40-b4787e5dfa0f -w JIT.HardwareIntrinsics.General.Vector256 -o F:\bone_yard\runtime76280`

**Comment by tannergooding** [comment]
Thanks! I expect the interesting bits start at `/__w/1/s/src/tests/JIT/HardwareIntrinsics/General/Vector256/BitwiseAnd.Byte.cs @ 212:` which is where the boxing and actual reflection call happens.

I looked at the prologue and all seems well, but haven't gone in depth on the codegen "in between" yet. It's just resolving the method to reflect however, so I don't expect anything "interesting" there.

**Comment by tannergooding** [comment]
Don't think I see anything wrong with the assembly either. It all looks correct and non-conflicting

**Comment by tannergooding** [comment]
There was a group debugging effort between @EgorBo, @SingleAccretion, and I on Discord. Grabbing values from the dump, it looks like the boxed return value already contains the "incorrect data":
```asm
0:000> ?? *(void**)(0x00000073CB57DC30 + 0x290 - 0x118)
void * 0x00000225`9a11fb18
0:000> !do 0x000002259a11fb18
Name:        System.Runtime.Intrinsics.Vector256`1[[System.Byte, System.Private.CoreLib]]
MethodTable: 00007ffd0e485990
EEClass:     00007ffd0e4959f8
Size:        48(0x30) bytes
File:        C:\h\w\A4B60946\p\System.Private.CoreLib.dll
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ffd0e485088  40010cd        8 ...Private.CoreLib]]  1 instance 000002259a11fb20 _lower
00007ffd0e485088  40010ce       18 ...Private.CoreLib]]  1 instance 000002259a11fb30 _upper
0:000> !DumpVC /d 00007ffd0e485088 000002259a11fb30
Name:        System.Runtime.Intrinsics.Vector128`1[[System.Byte, System.Private.CoreLib]]
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ffd0e209060  40010ca        0        System.UInt64  1 instance                0 _00
00007ffd0e209060  40010cb        8        System.UInt64  1 instance                0 _01
0:000> ?? *(void**)(0x00000073CB57DC30 + 0x290 - 0x118)
void * 0x00000225`9a11fb18
0:000> !do 0x000002259a11fb18
Name:        System.Runtime.Intrinsics.Vector256`1[[System.Byte, System.Private.CoreLib]]
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ffd0e485088  40010cd        8 ...Private.CoreLib]]  1 instance 000002259a11fb20 _lower
00007ffd0e485088  40010ce       18 ...Private.CoreLib]]  1 instance 000002259a11fb30 _upper
0:000> !DumpVC /d 00007ffd0e485088 000002259a11fb30
Name:        System.Runtime.Intrinsics.Vector128`1[[System.Byte, System.Private.CoreLib]]
Fields:
              MT    Field   Offset                 Type VT     Attr            Value Name
00007ffd0e209060  40010ca        0        System.UInt64  1 instance                0 _00
00007ffd0e209060  40010cb        8        System.UInt64  1 instance 
```

The disassembly for `Vector256.BitwiseAnd` likewise looks fine:
```asm
0:000> !U /d 00007ffd0e33ce80
Normal JIT generated code
System.Runtime.Intrinsics.Vector256.BitwiseAnd[[System.Byte, System.Private.CoreLib]](System.Runtime.Intrinsics.Vector256`1<Byte>, System.Runtime.Intrinsics.Vector256`1<Byte>)
ilAddr is 00007FFD6CAB9670 pImport is 0000027C78933D20
Begin 00007FFD0E33CE80, size 39
/_/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Vector256.cs @ 290:
> 00007ffd`0e33ce80 c5f877          vzeroupper
> 00007ffd`0e33ce83 c5fd1002        vmovupd ymm0,ymmword ptr [rdx]
> 00007ffd`0e33ce87 c5fc28c8        vmovaps ymm1,ymm0
> 00007ffd`0e33ce8b c4e37d39c901    vextracti128 xmm1,ymm1,1
> 00007ffd`0e33ce91 c4c17d1010      vmovupd ymm2,ymmword ptr [r8]
> 00007ffd`0e33ce96 c5fc28da        vmovaps ymm3,ymm2
> 00007ffd`0e33ce9a c4e37d39db01    vextracti128 xmm3,ymm3,1
> 00007ffd`0e33cea0 c5f9dbc2        vpand   xmm0,xmm0,xmm2
> 00007ffd`0e33cea4 c5f1dbcb        vpand   xmm1,xmm1,xmm3
> 00007ffd`0e33cea8 c4e37d38c101    vinserti128 ymm0,ymm0,xmm1,1
> 00007ffd`0e33ceae c5fd1101        vmovupd ymmword ptr [rcx],ymm0
> 00007ffd`0e33ceb2 488bc1          mov     rax,rcx
> 00007ffd`0e33ceb5 c5f877          vzeroupper
> 00007ffd`0e33ceb8 c3              ret
```

**Comment by AaronRobinsonMSFT** [comment]
I have stepped through the [dispatch in the Invoke paths](https://github.com/dotnet/runtime/blob/3a578af1c9be66e577c4fb0bc69f2bd0e61afe2e/src/coreclr/vm/reflectioninvocation.cpp#L472-L806) and the logic appears to be correct. I can't find anything that is obviously wrong.

**Pull request closed without merging**
