### PR TITLE
Update Roslyn compiler build

### PR DESCRIPTION
**Pull request by cston**
Update to compiler build 4.4.0-3.22431.10 with support for `RefSafetyRulesAttribute`.

### CODE REVIEW

**Comment by stephentoub** [comment]
It looks like this is also bringing in https://github.com/dotnet/roslyn/pull/63264 which is causing build failures due to the interop analyzer assembly being referenced multiple times.
cc: @jkoritzinsky, @ViktorHofer

**Comment by ViktorHofer** [comment]
> It looks like this is also bringing in https://github.com/dotnet/roslyn/pull/63264 which is causing build failures due to the interop analyzer assembly being referenced multiple times.

Ack. Will submit a PR shortly.

**Review by ViktorHofer — APPROVED** [review]
LGTM. Just curious, will the 7.0-rc1 SDK contain the require compiler bits or do we need a 7.0-rc2 SDK?

**Comment by jaredpar** [comment]
> LGTM. Just curious, will the 7.0-rc1 SDK contain the require compiler bits

No.

> or do we need a 7.0-rc2 SDK?

The RC2 SDK will have the new bits but they package update effectively shoves the compiler bits into the RC1 SDK.

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Pull request merged**
