### PR TITLE
Avoid an assert in ves_icall_RuntimeFieldInfo_SetValueInternal

### PR DESCRIPTION
**Pull request by bholmes**
When the field is a valuetype and the value being assigned to the field 
is a reference type, throw an ArgumentException. Without this change the 
call to mono_object_handle_pin_unbox will assert and kill the process.

This can occur when de-serializing an object and the field types have
changed.

### CODE REVIEW

**Comment by bholmes** [comment]
Also requesting this get picked back to mono/mono

**Review by vargaz — APPROVED** [review]

**Comment by lambdageek** [comment]
> When the field is byref but the value being passes in is not, 

@bholmes do you mean the field is `ref SomeStruct` and the value is `SomeStruct`? or the field is a struct and the value is some reference type (like a class or something)?

is it possible to add a test for this?

**Comment by bholmes** [comment]
@lambdageek while looking into adding a test, I found that we (probably) do not need this in the dotnet/runtime repo. As part of the class lib update, the code no longer calls `UnsafeSetValue `from `System.Runtime.Serialization.FormatterServices.SerializationSetValue`

https://github.com/mono/mono/blob/bdd772531d379b4e78593587d15113c37edd4a64/mcs/class/referencesource/mscorlib/system/runtime/serialization/formatterservices.cs#L334

The question is, what is the better fix that we can use in the mono/mono repo? We can pull in this runtime change to avoid the assert or we can change the above file my calling `SetValue` instead of `UnsafeSetValue `.

The case we hit, is when we are attempting to set the value of a char field with a string. The unbox of the string asserts.

**Comment by lambdageek** [comment]
> @lambdageek while looking into adding a test, I found that we (probably) do not need this in the dotnet/runtime repo.

It seems harmless to add it to dotnet/runtime imo.

> The question is, what is the better fix that we can use in the mono/mono repo? We can pull in this runtime change to avoid the assert or we can change the above file my calling `SetValue` instead of `UnsafeSetValue `.

I think this runtime change is reasonable.  I think your PR description just doesn't match the code (or the comment below).  (byref makes it sound like `ref T` types are somehow involved)

> The case we hit, is when we are attempting to set the value of a char field with a string. The unbox of the string asserts.

Ok yea, that example makes sense to me.  Code LGTM.  Please change the commit message with this example (field is a valuetype, the value being assigned to the field is a reference type).

**Review by lambdageek — APPROVED** [review]

**Comment by bholmes** [comment]
The messages have been updated

**Comment by marek-safar** [comment]
Can test case be added or enabled for this logic?

**Pull request merged**
