### PR TITLE
[HTTP/3] Fixed stress

### PR DESCRIPTION
**Pull request by ManickaP**
The artifact pulling in msquic has been deleted from AzDO --> pulled newer msquic.
Remove exclusion of 100-continue scenario from H/3, which should now be fixed in the base image.

### CODE REVIEW

**Review by antonfirsov — COMMENTED** [review]
msquic changes look good, but there are some unrelated ones, I'd like to understand the purpose.

Is it that we need to get this fix in despite stress being completely broken on main, so we can propagate the fix to the servicing branches? Shouldn't we also backport #59410 then?

**Comment by ManickaP** [comment]
As I said in the older comment:
> EDIT: I can revert all the "pull newest image" changes, that was my first attempt to fix this, but it doesn't help (nor it hurts).

In another words, the only change that matters is the one with msquic, the rest are my feeble attempts to fix the complete brokenness of the stress test and I can revert them.

**Review by antonfirsov — APPROVED** [review]
Thanks! Sorry for being overly worried about the other changes. It's pure pain to make stress work again, any change we can't validate on the CI makes me more anxious now.

**Pull request merged**
