### PR TITLE
JIT: Quirk a quirk in fgExpandVirtualVtableCallTarget

### LINKED ISSUE #88349: Assertion failed '!(*use)->OperMayThrow(m_compiler)'
runtime-coreclr libraries-pgo
net8.0-linux-Release-x64-CoreCLR_checked-fullpgo_random_gdv_methodprofiling_only-Ubuntu.1804.Amd64.Open and net8.0-linux-Release-arm64-CoreCLR_checked-fullpgo_random_gdv_methodprofiling_only
System.Text.RegularExpressions.Tests, ComInterfaceGenerator.Unit.Tests, LibraryImportGenerator.Unit.Tests

https://dev.azure.com/dnceng-public/public/_build/results?buildId=327721&view=ms.vss-test-web.build-test-results-tab

```
DOTNET_TC_QuickJitForLoops=1
DOTNET_JitRandomGuardedDevirtualization=1
DOTNET_EnableCrashReport=1
DOTNET_JitDelegateProfiling=1
DOTNET_TieredCompilation=1
DOTNET_JitVTableProfiling=1
DOTNET_DbgMiniDumpName=/home/helixbot/dotnetbuild/dumps/coredump.%d.dmp
DOTNET_TieredPGO=1
DOTNET_DbgEnableMiniDump=1
DOTNET_JitClassProfiling=0
DOTNET_JitRandomlyCollect64BitCounts=1
DOTNET_ReadyToRun=0
+ ./RunTests.sh --runtime-path /datadisks/disk1/work/AB27091A/p
----- start Sun Jul 2 16:47:57 UTC 2023 =============== To repro directly: =====================================================
pushd .
/datadisks/disk1/work/AB27091A/p/dotnet exec --runtimeconfig System.Text.RegularExpressions.Tests.runtimeconfig.json --depsfile System.Text.RegularExpressions.Tests.deps.json xunit.console.dll System.Text.RegularExpressions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/datadisks/disk1/work/AB27091A/w/AB990976/e /datadisks/disk1/work/AB27091A/w/AB990976/e
  Discovering: System.Text.RegularExpressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.RegularExpressions.Tests (found 327 of 357 test cases)
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 2)

Assert failure(PID 4474 [0x0000117a], Thread: 5445 [0x1545]): Assertion failed '!(*use)->OperMayThrow(m_compiler)' in 'Microsoft.CodeAnalysis.Text.SourceText:WithChanges(System.Collections.Generic.IEnumerable`1[Microsoft.CodeAnalysis.Text.TextChange]):Microsoft.CodeAnalysis.Text.SourceText:this' during 'Physical promotion' (IL size 587; hash 0x0ca863c3; Tier1)

    File: /__w/1/s/src/coreclr/jit/promotion.cpp Line: 2256
    Image: /datadisks/disk1/work/AB27091A/p/dotnet
```

@AndyAyersMS @EgorBo

### PR DESCRIPTION
**Pull request by jakobbotsch**
Initially I just removed this, but that has somewhat impactful regressions (see https://github.com/dotnet/runtime/pull/88355#issuecomment-1619881729), which I'm not interested in taking on at this point of .NET 8. So this adds a further quirk on top of the quirk, which in this case ensures we have the right flags set after GDV call expansion.

Also fix a JITDUMP in physical promotion.

Fix #88349

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @EgorBo 

[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=328873&view=ms.vss-build-web.run-extensions-tab).

**Review by EgorBo — APPROVED** [review]
so it's not  zero-diff as the comment states? 🙂

**Comment by jakobbotsch** [comment]
> so it's not zero-diff as the comment states? 🙂

I think the comment is saying that the quirk exists to keep a previous PR zero-diff. Indeed removing it has quite large diffs.

**Comment by jakobbotsch** [comment]
Failure is known according to build analysis.

**Pull request merged**
