### PR TITLE
Remove static modifiers from ThreadPool events in NativeRuntimeEventSource.PortableThreadPool.NativeSinks.cs

### PR DESCRIPTION
**Pull request by nickyMcDonald**
Here is a fix for issue #78006 that works with win11 .NET 7.

The EventPipeEventDispatcher cycles through EventPipeInternal via QCall and sends them to be processed by the NativeRuntimeEventSource.
https://github.com/dotnet/runtime/blob/0c612cf7c36f53651e646d62d3bb362823880c00/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventPipeEventDispatcher.cs#L169-L181
From there they are sent to be decoded by the EventPipePayloadDecoder.
https://github.com/dotnet/runtime/blob/a08818ead21c46fa18d2390438ae5b3425165bc0/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/NativeRuntimeEventSource.cs#L55
There is where the NRE occurs because the metadata is uninitialized. Parameters is default null and attempting to get its length results in NRE. Looking back at the NativeRuntimeEventSource the NRE occurs with eventID 64 (ThreadPoolIODequeue).
https://github.com/dotnet/runtime/blob/a08818ead21c46fa18d2390438ae5b3425165bc0/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventPipePayloadDecoder.cs#L16-L19
In the EventSource. There are no BindingFlags for static methods. This is important because any static methods from the NativeRuntimeEventSource won’t get loaded. Because this data is used to initialize m_eventData values, any methods left out will leave uninitialized slots in m_eventData. Slot 64 being one of them.
https://github.com/dotnet/runtime/blob/0c612cf7c36f53651e646d62d3bb362823880c00/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L3042
The fix will allow for event 64 and 63 to be loaded into m_eventData before pr #66333 again.

### CODE REVIEW

**Comment by jkotas** [comment]
cc @marek-safar This is regression introduced by https://github.com/dotnet/runtime/pull/66333/files#diff-f7c0dd1b698275f0f183b9517883bc82280850fc6f256e8b7405c02ce0d0c22fR152

**Comment by jkotas** [comment]
Is it possible to add a test for this?

e.g. here: https://github.com/dotnet/runtime/blob/main/src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs

**Comment by hoyosjs** [comment]
Hmm... `tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh` is now timing out and a dump was collected on macOS x64

**Comment by tommcdon** [comment]
@davmason ptal

**Review by davmason — APPROVED** [review]

**Pull request merged**
