### PR TITLE
Fix crossgen for FreeBSD by adding FreeBSD RID.

### PR DESCRIPTION
**Pull request by josteink**
Fix implemented as described by @Thefrank in this thread: https://github.com/dotnet/runtime/issues/14537#issuecomment-922546527

Also contains fix described by @sec here: https://github.com/dotnet/runtime/issues/14537#issuecomment-922770010

cc: @jasonpugsley @jkotas

### CODE REVIEW

**Comment by jasonpugsley** [comment]
It's possible you might also need to add `"freebsd"` to the possible list of OS names parsed on the command line.
https://github.com/dotnet/runtime/blob/6c9921d2ad188d81af53892930a87ee5ad97c979/src/coreclr/tools/aot/crossgen2/CommandLineOptions.cs#L192
Though I'm not sure how OS specific crossgen is. I would have thought AMD64 bytecode would be the same regardless of OS but there may be other OS specific shims added or the like.

**Comment by josteink** [comment]
Thanks for the feedback @jasonpugsley!

Looking at the code, it only seems to affect what is shown to the user when the user explicitly requests help from the crossgen2 tool or uses it incorrectly. If so... It doesn't seem to do much in terms of *actual* code generation happening when used correctly?

As this code is explicitly about help/shell-output, I also fear that adding this might signal a higher level of "official support" than MS is willing to concede at this point. As such, I think that might be a patch best left for later?

**Review by jasonpugsley — APPROVED** [review]
This looks good to me. I agree with the comment, we can revisit this again later.

**Comment by jasonpugsley** [comment]
I just want to save this here if we search for it later. When run on FreeBSD, the change in this PR in `ComputeDefaultOptions()` detects FreeBSD, in that case `--targetos` doesn't have to be specified. Here's the command from the runtime build run on FreeBSD to crossgen System.Private.CoreLib.dll:
```
/dotnet/runtime/dotnet.sh /dotnet/runtime/artifacts/bin/coreclr/FreeBSD.x64.Debug/crossgen2/crossgen2.dll -o:/dotnet/runtime/artifacts/bin/coreclr/FreeBSD.x64.Debug/System.Private.CoreLib.dll -r:/dotnet/runtime/artifacts/bin/coreclr/FreeBSD.x64.Debug/IL/*.dll --targetarch:x64 -O --verify-type-and-field-layout /dotnet/runtime/artifacts/bin/coreclr/FreeBSD.x64.Debug/IL/System.Private.CoreLib.dll
```
However, when doing a cross-build from Linux, it's possible we might need to specify `--targetos:freebsd`
It might not be needed but I wanted to make a note here for future reference.

**Comment by josteink** [comment]
That’s an interesting theory. I don’t see any other conditionals for other platforms there though. 

Is that because FreeBSD currently is the only platform using/needing a cross build?

**Comment by jasonpugsley** [comment]
> Is that because FreeBSD currently is the only platform using/needing a cross build?

I'm not sure. Maybe building iOS from Mac and Android from Linux is different to building FreeBSD from Linux but we'll find out I guess 😀

**Comment by Thefrank** [comment]
FreeBSD (and likely Illumos) need a crossbuild under Linux AFAIK. I will say I have not tried the "BuildFromSource" stuff but from what I recall that still required a bootstrap pre-built SDK
Once that is done, that generated SDK can be used for future native builds (unless there is a big jump like net5->net6).

**Comment by jasonpugsley** [comment]
So long as the PR automated builds use Linux for FreeBSD builds we'll want to ensure they're as complete/correct as we can keep them. There's no guarantee we'll every have FreeBSD hosts in the azure devops build pool (for PR automated builds).

**Comment by josteink** [comment]
So what’s the conclusion? Do I need to add a <CrossGenDllCmd> or not?

**Comment by jasonpugsley** [comment]
At this point we're only guessing. We need someone who understands crossgen2 to tell us.

**Comment by jasonpugsley** [comment]
I think go ahead with what you have submitted. I have tried enabling various additional bits but they break the cross-build. We can keep working on those pieces later.

**Comment by josteink** [comment]
So…? Is anyone willing to merge? 🙂

**Review by jkotas — APPROVED** [review]

**Pull request merged**
