### PR TITLE
[HTTP/3] Add libnuma-dev into docker image

### LINKED ISSUE #81706: HttpStress fails to build msquic
Starting from 02/04 the "Build HttpStress" step fails to build msquic:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=160889&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=7fe64d4e-bb7a-5b68-0c5c-ad57d12d4da9

```
[ 82%] Building C object src/platform/CMakeFiles/platform.dir/platform_posix.c.o
/msquic/msquic/src/msquic/src/platform/platform_posix.c:40:10: fatal error: numa.h: No such file or directory
   40 | #include <numa.h>
      |          ^~~~~~~~
compilation terminated.
gmake[2]: *** [src/platform/CMakeFiles/platform.dir/build.make:160: src/platform/CMakeFiles/platform.dir/platform_posix.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:272: src/platform/CMakeFiles/platform.dir/all] Error 2
gmake: *** [Makefile:160: all] Error 2
The command '/bin/sh -c cd msquic/src/msquic &&     mkdir build &&     cmake -B build -DCMAKE_BUILD_TYPE=Release -DQUIC_ENABLE_LOGGING=false -DQUIC_USE_SYSTEM_LIBCRYPTO=true -DQUIC_BUILD_TOOLS=off -DQUIC_BUILD_TEST=off -DQUIC_BUILD_PERF=off &&     cd build &&     cmake --build . --config Release' returned a non-zero code: 2
Service 'server' failed to build : Build failed
```

@ManickaP any suggestion how to fix this?

### PR DESCRIPTION
**Pull request by ManickaP**
Attempt to fix #81706

cc: @antonfirsov

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM. 
We may also try to fix msquic but that would certainly be much longer path.
And we already install bunch of `-dev` packages....

**Review by CarnaViire — APPROVED** [review]

**Comment by ManickaP** [comment]
> LGTM. We may also try to fix msquic but that would certainly be much longer path. And we already install bunch of `-dev` packages....

I can file an issue in msquic if you think we should pursue this. It doesn't have to be fixed right here right now as we have this fix.

**Comment by antonfirsov** [comment]
It worked, so the fix is good enough for now. I'm also adding my +1 to make msquic packaging more stable, but can't comment on technical details there.

Thanks!

**Pull request merged**
