### PR TITLE
Look up Queryable operator MethodInfos without MakeGenericMethod

### LINKED ISSUE #79199: Make LINQ providers (Queryable) compatible with NativeAOT
The queryable LINQ operators are currently marked with [RequiresDynamicCode] (e.g. [Where](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Queryable/src/System/Linq/Queryable.cs#L47)), because their implementation [uses MakeGenericType](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Queryable/src/System/Linq/CachedReflection.cs#L1000). This makes them incompatible with NativeAOT.

In typical LINQ providers, the expression tree doesn't end up getting compiled and executed, but rather translated to something else (e.g. SQL); this means that the Types and MethodInfos in the tree are only there for the proper tree structure, and we don't need them to actually contain code. However, MakeGenericType and MakeGenericMethod are currently eager, and throw right away in NativeAOT if the native code isn't pregenerated.

To solve this, we'd need to be able to make **lazy** Types, MethodInfos, which only throw if a method/property is actually invoked on them. From a conversation with @jkotas, the eager behavior of the reflection types was done in order to provide fail-fast behavior to users; we could revisit this decision.

As an alternative, since Type/MethodInfo/PropertyInfo are abstract base classes, we could add lazy implementations of these. These implementations could either throw if code is invoked, or lazily call the real MakeGenericMethod when needed (which would fail in NativeAOT). Construction of these lazy types should be exposed as a new API, since LINQ providers such as EF would need to make use of them as well (otherwise LINQ providers would need to duplicate the lazy types internally).

Thanks for @jkotas for the suggestions and conversation. 

/cc @ajcvickers @AndriySvyryd

### PR DESCRIPTION
**Pull request by roji**
Replaces MethodInfo lookup for Queryable LINQ operators to stop using MakeGenericMethod, making them NativeAOT-compatible (and slightly faster).

The current code caches the generic method definition and calls MakeGenericMethod every time:

```c#
[RequiresDynamicCode("Calls System.Reflection.MethodInfo.MakeGenericMethod(params Type[])")]
public static MethodInfo Where_TSource_2(Type TSource) =>
    (s_Where_TSource_2 ??= new Func<IQueryable<object>, Expression<Func<object, bool>>, IQueryable<object>>(Queryable.Where).GetMethodInfo().GetGenericMethodDefinition())
    .MakeGenericMethod(TSource);
```

This PR replaces that with the following:

```c#
new Func<IQueryable<TSource>, Expression<Func<TSource, bool>>, IQueryable<TSource>>(Where).Method
````

There's no more caching, but the new implementation is slightly faster than MakeGenericMethod:

|                          Method |     Mean |   Error |  StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------------------------------- |---------:|--------:|--------:|-------:|------:|------:|----------:|
|     ViaMethodGenericMethodValue | 395.5 ns | 1.21 ns | 0.95 ns | 0.0463 |     - |     - |     200 B |
| ViaMethodGenericMethodReference | 388.1 ns | 6.57 ns | 5.49 ns | 0.0463 |     - |     - |     200 B |
|                    ViaFuncValue | 326.8 ns | 5.27 ns | 4.68 ns | 0.0610 |     - |     - |     264 B |
|                ViaFuncReference | 325.6 ns | 2.48 ns | 2.20 ns | 0.0610 |     - |     - |     264 B |

Note the increase in allocations though.

<details>
<summary>Benchmark code</summary>

```c#
BenchmarkRunner.Run<Benchmark>();

[MemoryDiagnoser]
public class Benchmark
{
    private static readonly MethodInfo GenericMethodDefinition
        = new Func<IQueryable<object>, Expression<Func<object, bool>>, IQueryable<object>>(Queryable.Where)
            .GetMethodInfo().GetGenericMethodDefinition();

    [Benchmark]
    public MethodInfo ViaMethodGenericMethodValue()
        => GenericMethodDefinition.MakeGenericMethod(typeof(int));

    [Benchmark]
    public MethodInfo ViaMethodGenericMethodReference()
        => GenericMethodDefinition.MakeGenericMethod(typeof(string));

    [Benchmark]
    public MethodInfo ViaFuncValue()
        => new Func<IQueryable<int>, Expression<Func<int, bool>>, IQueryable<int>>(Queryable.Where).Method;

    [Benchmark]
    public MethodInfo ViaFuncReference()
        => new Func<IQueryable<string>, Expression<Func<string, bool>>, IQueryable<string>>(Queryable.Where).Method;
}
```

</details>

Closes #79199

/cc @jkotas @vitek-karas @ajcvickers

### CODE REVIEW

**Comment by jkotas** [comment]
cc @MichalStrehovsky

**Review by jkotas — APPROVED** [review]
LGTM. Thank you!

**Comment by MichalStrehovsky** [comment]
Nice!

Cc @jaredpar if there's an issue where we track use cases for a `methodof` operator. The ones I could find were all closed.

**Comment by jaredpar** [comment]
@MichalStrehovsky I don't believe there is an active issue around this. There was a lot of discussion around this around the time that `nameof` was introduced. The proposed addition was called `infoof` rather than `methodof` (allowed for identifying all members, not just methods). It was cut though due to lack of need. 

This has come up several times in the following years though. The design is fairly well understood but there has never been the need to push it over the top. I think the way to move this forward is to outline the benefit this would have over the current solution (send it to me). I can add in the other scenarios I'm aware of and try to get an issue filed.

**Pull request merged**
