### PR TITLE
[wasm] Use newer ubuntu 20.04 images

### PR DESCRIPTION
**Pull request by radekdoulik**

### CODE REVIEW

**Comment by lewing** [comment]
cc @directhex

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/pull/80866

**Comment by radical** [comment]
Chrome failing to start because: `/datadisks/disk1/work/AC560949/p/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory`.

**Comment by radical** [comment]
Debugger tests break because: 
`/datadisks/disk1/work/AF6E0A04/p/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory`

Same for the WBT failures too.

**Comment by radical** [comment]
oh, sorry. I thought you were testing the changes here.

**Pull request closed without merging**
