### PR TITLE
Fix precondition if HOST_UNIX in ClrVirtualAllocWithinRange()

### LINKED ISSUE #83818: System.OutOfMemoryException when allocating jump stub on macOS ARM64
Hi!

Sometimes I get a `System.OutOfMemoryException` exception in .NET 7 app on macOS ARM64 in arbitrary places like:
```
System.OutOfMemoryException
at InvokeStub_ContextConsumersWithAttributesManager..ctor(Object, Object, IntPtr*)
at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Digging into this, it turned out that the exception is thrown from `HostCodeHeap::InitializeHeapList()`:
https://github.com/dotnet/runtime/blob/d037e070ebe5c83838443f869d5800752b0fcb13/src/coreclr/vm/dynamicmethod.cpp#L442-L449

because `ExecutableAllocator::Commit()` failed to commit executable memory:
https://github.com/dotnet/runtime/blob/d037e070ebe5c83838443f869d5800752b0fcb13/src/coreclr/vm/dynamicmethod.cpp#L758-L762

On macOS ARM64 `ExecutableAllocator::IsDoubleMappingEnabled()` is disabled, thus it internally calls `VirtualAlloc(..., MEM_COMMIT, PAGE_EXECUTE_READWRITE)` for the pre-reserved memory `HostCodeHeap::m_pLastAvailableCommittedAddr`, but then `mprotect(..., PROT_EXEC | PROT_READ | PROT_WRITE)` fails with errno `EACCES` (aka `Permission denied`):
https://github.com/dotnet/runtime/blob/d037e070ebe5c83838443f869d5800752b0fcb13/src/coreclr/pal/src/map/virtual.cpp#L1202-L1216

because initially this memory region was reserved w/o `MEM_RESERVE_EXECUTABLE` flag (which is used for `MAP_JIT`):
https://github.com/dotnet/runtime/blob/d037e070ebe5c83838443f869d5800752b0fcb13/src/coreclr/utilcode/util.cpp#L448-L460

despite the fact that `ExecutableAllocator::ReserveWithinRange()` actually requests it:
https://github.com/dotnet/runtime/blob/d037e070ebe5c83838443f869d5800752b0fcb13/src/coreclr/utilcode/executableallocator.cpp#L595-L605

Linked issues: https://github.com/dotnet/runtime/issues/50391, https://github.com/dotnet/runtime/pull/54954.

### PR DESCRIPTION
**Pull request by k15tfu**
Fixes #83818

### CODE REVIEW

**Comment by k15tfu** [comment]
Addresses comments from https://github.com/dotnet/runtime/pull/83958.

**Review by jkotas — APPROVED** [review]
Thanks!

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by jkotas** [comment]
The failure is https://github.com/dotnet/runtime/issues/84010

**Pull request merged**
