### PR TITLE
Fix System.Number.BigInteger.DivRem outputting an incorrect remainder

### LINKED ISSUE #72113: System.Number.BigInteger.DivRem can output an incorrect remainder
## Summary
`Number.BigInteger.DivRem` outputs an incorrect remainder when some of the computed remainder blocks are zero.

## Explanation
`Number.BigInteger` is an internal helper type (not to be confused with the public `System.Numerics.BigInteger`), so reproduction is tricky, but I can outline the scenario that led to me discovering this bug.

`Number.BigInteger` is internally represented as an array of uints called `_blocks`, and an array length `_length`. This array is ordered from least significant to most significant.

`Number.BigInteger.DivRem` outputs a remainder called `BigInteger rem`. Right before returning, the algorithm attempts to cull `rem` blocks with value `0` by subtracting `1` from `_length`, essentially removing those extra unneeded blocks. However, while removing leading zero blocks is useful and harmless, the current algorithm also reduces the length when it finds a trailing zero block. For example, if the algorithm is intending to return a `rem` where `_blocks = [0, 1], _length = 2`, because of that trailing zero block it will reduce the length and end up returning `_blocks = [0], _length = 1`, which is incorrect.

## Impact
The current usage of `BigInteger.DivRem` is limited, so I'd imagine it hasn't yet been called with an expected remainder that has a non-zero `_block[1]` and a zero `_block[0]`. I'm currently working on something that hits this case.

### LINKED ISSUE #72133: Importer's spilling logic is incomplete in subtle ways
Reproduction (requires Fody.InlineIL):
```cs
Console.WriteLine(Problem(1, 2, 0));

[MethodImpl(MethodImplOptions.NoInlining)]
static int Problem(int a, int b, int c)
{
    IL.Emit.Ldarg(0);
    IL.Emit.Ldarga(0);
    IL.Emit.Ldarg(2);
    IL.Emit.Add();
    IL.Emit.Ldarga(1);
    IL.Emit.Ldobj<StructWithInt>();
    IL.Emit.Stobj<StructWithInt>();

    return IL.Return<int>(); 
}

struct StructWithInt
{
    public int Int;
}
```
Compile and run.

Expected result: program prints `1`.

Actual result: program prints `2`.

Cause: the importer doesn't spill `a` when it appends the `stobj`:
```scala
Importing BB01 (PC=000) of 'RyuJitReproduction.Program:Problem(int,int,int):int'
    [ 0]   0 (0x000) ldarg.0
    [ 1]   1 (0x001) ldarga.s 0
    [ 2]   3 (0x003) ldarg.2
    [ 3]   4 (0x004) add
    [ 2]   5 (0x005) ldarga.s 1
    [ 3]   7 (0x007) ldobj 0200002D
    [ 3]  12 (0x00c) stobj 0200002D

STMT00000 ( 0x000[E-] ... ??? )
               [000010] -A-X-------                         *  ASG       struct (copy)
               [000009] -----------                         +--*  BLK       struct<RyuJitReproduction.Program+StructWithInt, 4>
               [000005] -----------                         |  \--*  ADD       long  
               [000002] -----------                         |     +--*  ADDR      long  
               [000001] -------N---                         |     |  \--*  LCL_VAR   int    V00 arg0         
               [000004] -----------                         |     \--*  CAST      long <- int
               [000003] -----------                         |        \--*  LCL_VAR   int    V02 arg2         
               [000008] n--X-------                         \--*  OBJ       struct<RyuJitReproduction.Program+StructWithInt, 4>
               [000007] -----------                            \--*  ADDR      byref 
               [000006] -------N---                               \--*  LCL_VAR   int    V01 arg1         

    [ 1]  17 (0x011) ret

STMT00001 ( ??? ... ??? )
               [000011] -----------                         *  RETURN    int   
               [000000] -----------                         \--*  LCL_VAR   int    V00 arg0         
```

### PR DESCRIPTION
**Pull request by dakersnar**
Fixes #72113

### CODE REVIEW

**Comment by stephentoub** [comment]
> let me try to figure out InternalsVisableTo

We try to avoid InternalsVisibleTo, for a variety of reasons, e.g. it inhibits assembly-level trimming we do.

Why does this require internals access?  If there's no way to trigger this via public surface area, I think it's fine to forego a test.

**Comment by stephentoub** [comment]
If there's no other way to trigger this bug via public surface area, sounds fine.

**Review by stephentoub — APPROVED** [review]

**Comment by dakersnar** [comment]
@jeffhandley I think we discussed wanting to get this into 7.0. What does that process look like at this point?

**Comment by stephentoub** [comment]
> I think we discussed wanting to get this into 7.0. What does that process look like at this point?

Everything going into main right now will make it into .NET 7.

**Pull request merged**
