### PR TITLE
JIT: Prefer block copies for unenregisterable locals even with GC pointers

### PR DESCRIPTION
**Pull request by jakobbotsch**
This comment seems outdated/wrong, the backend's block copy strategy when GC pointers are involved is highly tuned and often no helper is necessary at all.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Opened #85637 for the failure.

cc @dotnet/jit-contrib PTAL @EgorBo. [Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258833&view=ms.vss-build-web.run-extensions-tab) -- not bad for a simple change.

**Review by EgorBo — APPROVED** [review]
Nice! So we now do BLK copy where previously we used to do field-by-field copy/init due to gc pointers?

**Comment by jakobbotsch** [comment]
> Nice! So we now do BLK copy where previously we used to do field-by-field copy/init due to gc pointers?

Indeed (when we know the struct is going to be on stack anyway).

**Comment by EgorBo** [comment]
Although, I guess we'll still be doing GPR movs (can't use SIMD for structs with gc handles) so I thought it's basically the same as physical promotion?

**Comment by jakobbotsch** [comment]
> Although, I guess we'll still be doing GPR movs (can't use SIMD for structs with gc handles) so I thought it's basically the same as physical promotion?

The backend does use SIMD copies even when GC pointers are involved by disabling GC during the copy.

**Pull request merged**
