### PR TITLE
Keep array MT alive while getting component size

### PR DESCRIPTION
**Pull request by MichalStrehovsky**

### CODE REVIEW

**Review by EgorBo — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
Alternative fix would be to add a note in a comment (that nobody will read), similar to the comment on `ObjectHasComponentSize`. Looking at the source history I assume there's no `KeepAlive` because of codegen differences.

**Comment by joperezr** [comment]
@MichalStrehovsky this has now been approved and open for over a month, but I haven't merged due to you adding the No-merge label. Do we still plan to eventually merge this? What are we currently waiting on?

**Comment by jkotas** [comment]
> What are we currently waiting on?

We should check the asm-diffs that this change introduces.

**Comment by joperezr** [comment]
I see. @MichalStrehovsky do you plan to do this?

**Comment by MichalStrehovsky** [comment]
> I see. @MichalStrehovsky do you plan to do this?

I'm taking an extended leave, so no.

**Pull request closed without merging**
