### PR TITLE
Enable loc build

### PR DESCRIPTION
**Pull request by ericstj**
This adds a localization drop process to our official builds, per the process outlined by @jonfortescue.

Here's an internal build that uses this: https://dev.azure.com/dnceng/internal/_build/results?buildId=1128537&view=results

### CODE REVIEW

**Review by safern — APPROVED** [review]
Curious, how is the localized drop used?

**Comment by ericstj** [comment]
> how is the localized drop used?

See https://github.com/dotnet/arcade/blob/main/Documentation/OneLocBuild.md and https://ceapex.visualstudio.com/CEINTL/_wiki/wikis/CEINTL.wiki/107/Localization-with-OneLocBuild-Task?anchor=overview

This produces a drop that the loc team uses to localize, they in-turn produce a package that contains localized LCLs.  At the moment this is unable to commit those changes to XLFs in the repo, but @jonfortescue mentioned this will be fixed shortly, and in the meantime he'll be doing some manual work to apply the localizations.

**Comment by ericstj** [comment]
Both failures here are https://github.com/dotnet/runtime/issues/52464
And I've confirmed that's been fixed via runfo query.

**Review by ViktorHofer — APPROVED** [review]
I'm surprised that the eng/common yml file works with all kinds or arcadified repositories but as long as this is doing the right things LGTM.

**Pull request merged**
