### PR TITLE
Remove duplicate android and wasm yaml templates to run the runtime tests after a "global-build" build step.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
I'm planning on utilizing this template in #74623 with CoreCLR and I noticed that we had two very similar copies. I figured it was a good idea to collapse them into a single copy and make it work for CoreCLR for at least simple cases.

### CODE REVIEW

**Comment by naricc** [comment]
I merged the wasm template into build-runtime-tests-and-send-to-helix.yml  but I guess I didn't think to also merge in the android one. This is a good idea.

**Review by naricc — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
Failure is https://github.com/dotnet/runtime/issues/79874. Merging this in to unblock my other work.

**Pull request merged**
