### PR TITLE
[mono][interpreter] Throw when basic blocks after branch are not created

### LINKED ISSUE #54396: [MONO][Interp] Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/interp/interp.c:3285 with interpreter
Failed tests list:

- JIT/jit64/verif/sniff/fg/ver_fg_13/ver_fg_13.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.jit64/console.0629b13a.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

```
      06-17 16:46:22.310 14810 14827 I DOTNET  : MonoRunner initialize,, entryPointLibName=ver_fg_13.dll
      06-17 16:46:22.311 14810 14827 D DOTNET  : file_path: /data/user/0/net.dot.JIT_jit64/files/runtimeconfig.bin
      06-17 16:46:22.311 14810 14827 D DOTNET  : Interp Enabled
      06-17 16:46:22.312 14810 14827 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_jit64/files
      06-17 16:46:22.333 14810 14827 D DOTNET  : assembly_preload_hook: ver_fg_13.dll (null) /data/user/0/net.dot.JIT_jit64/files
      06-17 16:46:22.333 14810 14827 D DOTNET  : Executable: ver_fg_13.dll
      06-17 16:46:22.333 14810 14827 D DOTNET  : assembly_preload_hook: mscorlib  /data/user/0/net.dot.JIT_jit64/files
      06-17 16:46:22.333 14810 14827 D DOTNET  : assembly_preload_hook: System.Console  /data/user/0/net.dot.JIT_jit64/files
      06-17 16:46:22.333 14810 14827 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.JIT_jit64/files
      06-17 16:46:22.372 14810 14827 D DOTNET  : ((null) error) * Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/interp/interp.c:3285
      06-17 16:46:22.372 14810 14827 E DOTNET  : Exit code: 1.
      06-17 16:46:22.428  1792  2648 I ActivityManager: Process net.dot.JIT_jit64 (pid 14810) has died: fore FGS 
      06-17 16:46:22.431  1792  2648 W ActivityManager: Crash of app net.dot.JIT_jit64 running instrumentation ComponentInfo{net.dot.JIT_jit64/net.dot.MonoRunner}
      06-17 16:46:22.432  1792 13884 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 16:46:22.432  1792 13884 W Binder  : java.lang.Throwable
      06-17 16:46:22.432  1792 13884 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 16:46:22.432  1792 13884 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 16:46:22.432  1792 13884 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 16:46:22.435  1792  2648 I ActivityManager: Force stopping net.dot.JIT_jit64 appid=10128 user=0: finished inst
      06-17 16:46:22.436  1536  1536 I Zygote  : Process 14810 exited cleanly (1)
      06-17 16:46:22.439 14799 14799 D AndroidRuntime: Shutting down VM
      06-17 16:46:22.458  1792 13884 I ActivityManager: Failure reporting to instrumentation watcher: comp=ComponentInfo{net.dot.JIT_jit64/net.dot.MonoRunner} results=Bundle[{shortMsg=Process crashed.}]
      06-17 16:46:22.473  1792  1819 I libprocessgroup: Successfully killed process cgroup uid 10128 pid 14810 in 43ms
      Expected: True
```

### PR DESCRIPTION
**Pull request by kotlarmilos**
New blocks are created when branch/jump instructions are encountered (i.e. `ret`, `br`, `throw`). In such cases, if a new block is not created before the end of the instruction stream, IL code is invalid and `InvalidProgramException` should be thrown. Similar approach in Mono JIT: https://github.com/dotnet/runtime/blob/a83c661bb8061b65404fb154b328ff1d3993d9ec/src/mono/mono/mini/method-to-ir.c#L11969-L11970

Fix for https://github.com/dotnet/runtime/issues/54396

### CODE REVIEW

**Comment by kotlarmilos** [comment]
@BrzVlad not sure if there is an existing attribute that could be used.

**Comment by BrzVlad** [comment]
There shouldn't be a problem if the last bblock is dead in a method. The problem in the test case seems to be that `leave` has an invalid offset which is caught in `get_basic_blocks`, but on interp we don't throw error.

**Comment by kotlarmilos** [comment]
New blocks are created when branch/jump instructions are encountered (i.e. `ret`, `br`, `throw`). In such cases, if a new block is not created before the end of the instruction stream, IL code is invalid.

`get_basic_blocks` checks if opcode exists but can't check if an offset is invalid:
https://github.com/dotnet/runtime/blob/a83c661bb8061b65404fb154b328ff1d3993d9ec/src/mono/mono/mini/method-to-ir.c#L4950-L4952

Var `start_new_bblock` in `method-to-ir.c` indicates if a new block should be created according to particular instructions (i.e. `ret`, `br`, `throw`). If instruction stream ends with `start_new_bblock == 0` it means that a new BB should have been created and `InvalidProgramException` is thrown.

**Comment by BrzVlad** [comment]
I don't understand what `start_new_bblock` is trying to achieve and how it is related to the test case you are trying to fix. Once again, the problem in the test case is that leave has an invalid offset which is caught in the jit in get_basic_blocks, but on interp we don't throw error.

**Comment by kotlarmilos** [comment]
After offline sync with Vlad, we agreed to check how it is implemented in coreclr as the current implementation in mono jit doesn't cover all cases.

**Comment by kotlarmilos** [comment]
The fix proposed in this PR doesn't cover all cases. Closing this PR in favour of https://github.com/dotnet/runtime/pull/80136.

**Pull request closed without merging**
