### PR TITLE
Move FabricBot generation scripts to dotnet/runtime

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Moves FabricBot generation scripts from the private repo in https://github.com/jeffhandley/dotnet-fabricbot.

### CODE REVIEW

**Review by jeffhandley — CHANGES_REQUESTED** [review]
I think we should exclude the generated files from getting committed. Maybe either generate them into the `artifacts` folder at the root of the repo, or name the folder such that our `gitignore` will ignore it.

**Comment by eiriktsarpalis** [comment]
I'm intentionally tracking the generated files. It was meant as way for folks editing the generator to immediately see the results of their changes in diff form. Of course it requires keeping the generated files in sync with any change to the generator itself.

**Comment by jeffhandley** [comment]
Ah, I see. Presumably the workflow will involve using the script to generate those files and prepare a PR to both `dotnet/runtime` and `dotnet/dotnet-api-docs` (:soon: `dotnet/machinelearning`); right?

Could we instead add notes to the script that explain the expectation is that changes to this file are expected to be accompanied with capturing the resulting changes to the `fabricbot.json` file in this repo in the same PR, with PRs to `dotnet-api-docs` and `machinelearning` then also produced and linked to the PR that updates the script?

**Comment by eiriktsarpalis** [comment]
Added documentation. Also, it looks like there was a mix-up with roll-outs; we had onboarded Carlos & Santi last week instead of Michael & Tanner. I've updated the script and bolted on the changes on this PR. [Related PR in dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs/pull/7668).

FYI @michaelgsharp @tannergooding

**Review by jeffhandley — APPROVED** [review]

**Pull request merged**
