### PR TITLE
Fix the guid for the transaction

### LINKED ISSUE #31177: OleDbTransaction.Commit Exception ''SQLNCLI11' failed with no error message available
* `netcoreapp2.1`
* `System.Data.OleDB 4.6.0`

Calling `OleDbTransaction.Commit` throws this exception:

    System.Data.OleDb.OleDbException: ''SQLNCLI11' failed with no error message available, result code: E_NOINTERFACE(0x80004002).'

This does not occur when targeting net461.

If I execute the operations without a transaction they appear to work correctly.

### LINKED ISSUE #32405: [System.Data.OleDb] Wrong IID of ITransactionLocal interface
https://github.com/dotnet/runtime/blob/12cf6a8e5766678482df969d008eaabf6fa69872/src/libraries/System.Data.OleDb/src/SafeHandles.cs#L197-L200

Correct IID: 0c733a5f-2a1c-11ce-ade5-00aa0044773d

``` cpp
EXTERN_C const IID IID_ITransactionLocal;

#if defined(__cplusplus) && !defined(CINTERFACE)
    
    MIDL_INTERFACE("0c733a5f-2a1c-11ce-ade5-00aa0044773d")
    ITransactionLocal : public ITransaction
```
Also - see screenshot.

2020-02-16--System_Data_OleDb__from_nuget

### PR DESCRIPTION
**Pull request by saurabh500**
The guid for `ITransactionLocal` was incorrectly coded. The change fixes the Guid and also adds a test to verify this. 

The test was throwing an exception before the fix. 

The guid was verified from oledb.h header and also was reported in https://github.com/dotnet/runtime/issues/32405

Fixes https://github.com/dotnet/runtime/issues/31177
Fixes https://github.com/dotnet/runtime/issues/32405

### CODE REVIEW

**Review by maryamariyan — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Comment by danmosemsft** [comment]
Servicing candidate?

**Comment by jkotas** [comment]
System.Data.OleDb.Tests are failing with this change.

**Comment by saurabh500** [comment]
@jkotas I am looking into the test failure. I haven't been able to replicate the failure on my dev box. The tests are passing for me. I am testing using `dotnet build /t:RebuildAndTest /p:ArchGroup=x64`

This could be a test issue, and my testing pattern differs from the rest of the test class, because I am not reusing the connection, but creating a new one. I will submit a change to try out the hypothesis. Potentially because there are parallel connections being opened for a shared resource viz a csv file.

**Comment by jkotas** [comment]
Note that the tests are failing on Win7 and Win81 only. Perhaps that may be a factor?

**Comment by saurabh500** [comment]
I could get a repro while executing tests from Visual Studio. However I couldn't repro the same call stack from Command Line. From command line I started seeing AVs. (which isn't good either)

While looking into the code I realized that there are duplicate instances of ITransactionLocal object with the same GUID (after I made this change). This causes failure to execute the `IDataInitializeGetDataSource` delegate declared in `src\libraries\System.Data.OleDb\src\UnsafeNativeMethods.cs` 
I could remove one of the declarations of ITransacactoinLocal and get the tests to execute fine. 

The existing duplicate interface is at  https://github.com/dotnet/runtime/blob/1c498fe9ae4729f57c66151fc1f6402896d79c53/src/libraries/System.Data.OleDb/src/UnsafeNativeMethods.cs#L741-L758

Since the Guid for the two transaction types were different, there were no problems being surfaced during test execution. However after fixing the Guid in the duplicate ITrasnsactionLocal, there seems to be some problem with calling the delegate above which either surfaces as an AV or with `E_FAIL HRESULT`. At this point, I have not dug deeper into what causes the AV or the E_FAIL.

The duplicate interface is https://github.com/dotnet/runtime/blob/1c498fe9ae4729f57c66151fc1f6402896d79c53/src/libraries/System.Data.OleDb/src/SafeHandles.cs#L197-L236

The duplicate interface was added after the port to Core to replicate the behavior of what Managed C++ part of System.Data.dll used to handle, which interacting with the ITransactionLocal interface. 

I will update the PR with the findings and continue to investigate in parallel to see if I can make sense of why the failures are happening. I have very limited knowledge of COM and OleDb APIs to quickly find a solution here. However I will update the PR with the proposed solution and see if there is any feedback.

**Comment by danmosemsft** [comment]
@AaronRobinsonMSFT any thoughts come to mind?

**Comment by AaronRobinsonMSFT** [comment]
This is a huge mess. The GUID on `ITransactionLocal` is really for [`IChapteredRowset`](https://github.com/dotnet/runtime/blob/0b32c1a48b4176914cf2020018209a32f13ad992/src/libraries/System.Data.OleDb/src/UnsafeNativeMethods.cs#L244-L258). To further complicate things the `ICharteredRowSet` inherits directly from `IUnknown` so the interface definition is simple and only has the two new slots. However, the actual `ITransactionLocal` inherits so inherited slots must be added.

I can imagine various assumptions with how these are validated. Let me take a look at some of the failures when/if they come back.

**Comment by AaronRobinsonMSFT** [comment]
I am going to have to dig into this implementation tomorrow in order to help.

It would appear that the OleDB API implementation decided to circumvent the entire RCW/CCW support and manually handle all COM interop - this seems like a bad idea, but fine. What this means is somewhere there is a offset issue or some assumption about the layout of a specific interface that is no longer valid now that the type in question has been updated.

**Comment by FreddyD-GH** [comment]
Since there haven't been any updates on this PR for a week, does that mean the changes won't be merged anytime soon?  It'd be really nice to have this fixed.

**Comment by AaronRobinsonMSFT** [comment]
I completely forgot about this issue. Fixing this is clearly the correct thing here, but understanding the failure is important - especially considering the failure is consistent. I will try to look into this today.

**Comment by AaronRobinsonMSFT** [comment]
@saurabh500 I am unable to build this branch locally. I am getting the following:

```
System\Diagnostics\ProcessStartInfo.Win32.cs(21,42): error CS8600: Converting null literal or possible null value to non-nullable type. [D:\runtime\src\libraries\System.Diagnostics.Process\src\System.Diagnostics.Process.csproj]
System\Diagnostics\ProcessStartInfo.Win32.cs(30,49): error CS8600: Converting null literal or possible null value to non-nullable type. [D:\runtime\src\libraries\System.Diagnostics.Process\src\System.Diagnostics.Process.csproj]
System\Diagnostics\PerformanceCounterLib.cs(116,37): error CS8600: Converting null literal or possible null value to non-nullable type. [D:\runtime\src\libraries\System.Diagnostics.Process\src\System.Diagnostics.Process.csproj]
System\Diagnostics\PerformanceCounterLib.cs(118,37): error CS8600: Converting null literal or possible null value to non-nullable type. [D:\runtime\src\libraries\System.Diagnostics.Process\src\System.Diagnostics.Process.csproj]
System\Diagnostics\PerformanceCounterLib.cs(240,32): error CS8600: Converting null literal or possible null value to non-nullable type. [D:\runtime\src\libraries\System.Diagnostics.Process\src\System.Diagnostics.Process.csproj]
System\Diagnostics\PerformanceCounterLib.cs(241,32): error CS8603: Possible null reference return. [D:\runtime\src\libraries\System.Diagnostics.Process\src\System.Diagnostics.Process.csproj]
D:\runtime\src\libraries\Common\src\System\Diagnostics\TraceListenerHelpers.Windows.cs(28,38): error CS0103: The name 'Process' does not exist in the current context [D:\runtime\src\libraries\System.Diagnostics.TraceSource\src\System.Diagnostics.TraceSource.csproj]
    0 Warning(s)
    7 Error(s)
```

**Comment by jkotas** [comment]
@AaronRobinsonMSFT This is a build break than sneaked through the CI. Merge current master into the branch to fix it.

**Comment by saurabh500** [comment]
@AaronRobinsonMSFT this is strange. I didn't touch the path where your build is failing. 
I followed the Workflow and Building guide to get this done.

Are you able to build the master? Perhaps a rebase of the branch with master might help ?

**Comment by AaronRobinsonMSFT** [comment]
@jkotas I just merged in origin/master and now am getting the following error. Please tell me this isn't another known issue.

```D:\runtime\src\coreclr\src\jit\codegencommon.cpp(11307,31): error C2660: 'emitLocation::Print': function does not take
0 arguments [D:\runtime\artifacts\obj\coreclr\Windows_NT.x64.Checked\src\jit\linuxnonjit\linuxnonjit.vcxproj]
D:\runtime\src\coreclr\src\jit\emit.h(197,10): message : see declaration of 'emitLocation::Print' (compiling source fil
e D:\runtime\src\coreclr\src\jit\codegencommon.cpp) [D:\runtime\artifacts\obj\coreclr\Windows_NT.x64.Checked\src\jit\li
nuxnonjit\linuxnonjit.vcxproj]
  gcdecode.cpp
  pefile.cpp
D:\runtime\src\coreclr\src\jit\codegencommon.cpp(11311,33): error C2660: 'emitLocation::Print': function does not take
0 arguments [D:\runtime\artifacts\obj\coreclr\Windows_NT.x64.Checked\src\jit\linuxnonjit\linuxnonjit.vcxproj]
```

**Comment by AaronRobinsonMSFT** [comment]
Scratch that. Nonsense happening locally.

**Comment by AaronRobinsonMSFT** [comment]
Actually no. This is from dotnet/runtime/master. Boo.

**Comment by AaronRobinsonMSFT** [comment]
A brief update. This test appears to require Access 2016. The failure is in x64, but I can't install that on my machine because it can't be installed if Office (32-bit) is already installed. I hope it doesn't offend anyone that I am not going to uninstall my version of Office simply to attempt a local repro.

Looking through the code locally, there are some points of interest to investigate. Based on an offline conversation with @saurabh500, the function throwing the exception is propagating an `HRESULT` returned from: https://github.com/dotnet/runtime/blob/c727a412bf2c415bb2b94eeef0939aa07b87591c/src/libraries/System.Data.OleDb/src/OleDbWrapper.cs#L145

1) We should ensure the VTable is correct and we are calling what we think we are (i.e. [`IDbInitialize::Initialize()`](https://docs.microsoft.com/previous-versions/windows/desktop/ms718026(v%3Dvs.85))).

1) We need to step into the `IDbInitialize::Initialize()` call and see why the implementation is returning `E_FAIL`.

Since OleDB is manually handling all their COM calls/marshaling this is entirely in the test owners control and nothing to do with built-in COM interop support. Since other tests seem to be working I am going to assume that the VTable is okay which means we need good ol' mixed-mode debugging. We should step through the Access 2016 implementation of `IDbInitialize::Initialize()` and figure out why `E_FAIL` is being returned for this test.

**Comment by FreddyD-GH** [comment]
I spent some time looking at this, and I couldn't pinpoint the exact problem, but my findings may be helpful to you.

On .NET Framework, when an OleDbConnection is opened, MS Access creates a record-locking information file (.laccdb) in the same directory as the database.  When the OleDbConnection is closed/disposed, the .laccdb file is deleted.  However, on .NET Core, if you begin a transaction on a connection, the locking info file is created on open, but does not get deleted on close.  (If you don't begin a transaction, the locking info file behaves normally.)

On .NET Core, what I observed is that if you rapidly open several connections, the .laccdb file seems to grow in size each time, and it appears that the file has a hard size limit (I found to be 4KB).  In my tests, once the file reached that maximum size, any future calls to OleDbConnection.Open() would fail.

I noticed that when @saurabh500 merged the duplicate interfaces, the signature he used for ITransactionLocal.StartTransaction(...) has the pulTransactionLevel parameter as an int, instead of a uint*.  I don't think this is the issue, but might be worth double-checking the proper signature.

Furthermore, I found that if I insert an explicit call to ```GC.Collect()``` on line 337 of OleDbTransaction.cs (right after ```_transaction.Dispose();```), that seems to fix the issue: the record-locking file gets deleted when the connection is closed, and my version of the tests passed.  This doesn't seem like the RIGHT solution (although, any port in a storm?), but I'd imagine knowing this could be helpful to you.  It seems to me if I put the ```GC.Collect()``` any earlier, the tests fail, which leads me to believe that the problem lies somewhere with the ```WrappedTransaction``` not having something released properly, but I'm not famaliar enough to say for sure.

**Comment by FreddyD-GH** [comment]
I'm not sure if anyone can confirm that doing a manual GC.Collect() between test runs causes the tests to pass, but that was my experience, so I believe I have found the problem.  It looks like the issue is reference counting on the COM interfaces.  The documentation for Marshal.GetObjectForIUnknown(IntPtr) states:

> This method wraps IUnknown in a managed object. This has the effect of incrementing the reference count of the COM component. The reference count will be decremented when the runtime performs garbage collection on the managed object that represents the COM object.

In SafeHandles.cs, there are three calls to Marshal.GetObjectForIUnknown() that create a local variables that disappear into the ether and never have Marshal.ReleaseComObject() called on them (until garbage collection).  In my tests, adding a Marshal.ReleaseComObject() call to each of these will fix the issue.  For example:

```
internal static unsafe OleDbHResult ITransactionAbort(System.IntPtr ptr)
        {
            OleDbHResult hr = OleDbHResult.E_UNEXPECTED;
            ITransactionLocal transactionLocal = null;
            RuntimeHelpers.PrepareConstrainedRegions();
            try
            { }
            finally
            {
                Guid IID_ITransactionLocal = typeof(ITransactionLocal).GUID;
                hr = (OleDbHResult)Marshal.QueryInterface(ptr, ref IID_ITransactionLocal, out var pTransaction);
                if (pTransaction != IntPtr.Zero)
                {
                    transactionLocal = (ITransactionLocal)Marshal.GetObjectForIUnknown(pTransaction);
                    hr = (OleDbHResult)transactionLocal.Abort(IntPtr.Zero, false, false);
                    Marshal.ReleaseComObject(transactionLocal); // INSERT THIS LINE HERE
                    Marshal.Release(pTransaction);
                }
            }
            return hr;
        }
```

Like I said, I believe this fixes the issue (presumably, the right way) and should allow this PR to be merged.  Please let me know your thoughts.  It'd be great if we could get this merged soon.  Thanks.

@saurabh500

**Comment by saurabh500** [comment]
@FreddyD-GH Thanks for the investigation and providing the potential fix. 
I will look into incorporating your recommendations in this PR to see if I can fix the issue overall.

**Comment by FreddyD-GH** [comment]
@saurabh500 Just to clarify the changes I'm proposing: simply adding these 3 lines to the rest of your PR allowed things to work in my test environment:
https://github.com/FreddyD-GH/runtime/commit/6ebc323812cc9f3697c89d4fb93997350ab37be4#diff-d1b2f88061cc8f2e9fa31b0d2b46012a

**Comment by saurabh500** [comment]
I did just that and now I have new failures in the tests that I am running locally.
So I am investigating those

**Comment by FreddyD-GH** [comment]
Thanks for the update.  I just took a look at my tests to double check that they all passed after the change (they did), and I realized that that I had forgotten the System.Data.OleDb library uses the text/csv format for its tests, not the accdb format.  I apologize for probably sounding like a crazy person before when I was talking about .laccdb files and what not.

The only way I could observe bugs from the changed transaction code was to write my own tests, and to do so, I used the driver with an accdb file (since this is my intended scenario).  I assume using the driver with text/csv will have a similar issue due to not being disposed properly, but it could be that there are two different bugs.  Hopefully, that's not the case, but it is a possibility.

**Comment by saurabh500** [comment]
@FreddyD-GH Looks like the test issue was specific to my environment. The tests are passing now for me and the CI is green as well. 

@maryamariyan @jkotas and @stephentoub  there are changes since you folks last reviewed this. Can you take a look and let me know if the changes look good ?

**Review by jkotas — APPROVED** [review]
LGTM

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by MaceWindu** [comment]
Cool. Will it go into 5.0 or there are changes to see it in 2.1/3.1 ?

**Comment by jader1313** [comment]
I need this in 3.1, please!

**Comment by lauxjpn** [comment]
> Servicing candidate?

> I need this in 3.1, please!

For [EntityFrameworkCore.Jet](https://github.com/bubibubi/EntityFrameworkCore.Jet)'s EF Core 3.1 support we will need this as part of a service release targeting .NET Core 3.1 as well.

**Comment by saurabh500** [comment]
The PR for porting this fix into servicing is at https://github.com/dotnet/corefx/pull/42878
It has been approved for 3.1.x

@jader1313 You can consume the nightly build of System.Data.OleDb to verify the fix as well. It is shipped as an out of box package and shouldn't need a runtime update.

**Comment by jader1313** [comment]
@saurabh500 thank you very much, it worked on my tests.

**Comment by lauxjpn** [comment]
@saurabh500 Works for [EntityFrameworkCore.Jet](https://github.com/bubibubi/EntityFrameworkCore.Jet) as well.

**Pull request merged**
