### PR TITLE
Delete dead TRACE_VERBOSE code from System.Net.*

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by davidsh** [comment]
Instead of deleting it all, perhaps some of it is useful? If so, it could be changed from `NetEventSource.Info()` to `NetEventSource.Verbose()` calls.  @wfurt recently added that to our logging.

**Comment by wfurt** [comment]
> Instead of deleting it all, perhaps some of it is useful?

I was thinking the same but than nothing got my attention as useful. I think we should primarily log errors and making sure events can be correlated together. Perhaps doing tracing pass through Sockets similar to what I did for SslStream may be useful. Also perhaps let ToString() be more useful in general, not just under verbose.

**Comment by stephentoub** [comment]
> I was thinking the same but than nothing got my attention as useful.

Same for me; nothing under these TRACE_VERBOSEs stood out to me as being something we should promote to an event.

**Pull request merged**
