### PR TITLE
JIT: build pred lists first

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Move pred list building before importation. It now runs as the first phase in the phase list.

* Split up some unions in block.h as some things can't share storage anymore (may revisit this later).
* Modify importer not to rely on cheap preds. Most of the work here is in `impImportLeave`.
* Adjust OSR protection strategy for the method entry. In particular, watch for the degenerate case where the OSR entry is the method entry.
* Ensure we don't double-decrement some ref counts when blocks with degenerate or folded flow are re-imported.
* Update spill clique discovery to use the actual pred lists.
* Add new method `impFixPredLists` for the importer to use at the end of importation. This adds pred list entries finally returns, which can't be done until all `BBJ_LEAVE` blocks are processed.

Contributes to #80193.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL (and/or @BruceForstall if you're only quasi-vacationing)
cc @dotnet/jit-contrib 

This gets pred list building to the front of the phase list and removes one more user of cheap pred lists. 

Some small diffs in methods with patchpoints; the adaptive placement strategy is sensitive to `bbRefs` and the old code was not always accurate there.

Next step will be to build pred lists when we initially build the flow graph and get rid of the pred list building phase and the last user of cheap preds (eh normalization). Then I'm envisioning a bunch more cleanup as it seems like we can just do "automatic" maintenance of all these references.

**Comment by AndyAyersMS** [comment]
Failing on some bad IL tests -- think the issue was actually introduced by my previous PR and presumably only will show up in outerloop somewhere.

Will work on a separate fix.

**Comment by AndyAyersMS** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=155152&view=ms.vss-build-web.run-extensions-tab)

TP impact looks high (with minopts close to 1%), but drilling in, the only collection actually slower is minopts coreclr-tests; the other collections are all faster, so possibly a scaling issue with some of the crazier tests. We may gain some of this back in the next stage of work.

**Review by jakobbotsch — APPROVED** [review]
Generally looks fine to me, though I must admit I didn't spend too much time verifying that all the new `fgAddRefPred/fgRemoveRefPred` calls are right.
Maybe run some stress pipelines?

**Comment by jakobbotsch** [comment]
> [Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=155152&view=ms.vss-build-web.run-extensions-tab)
> 
> TP impact looks high (with minopts close to 1%), but drilling in, the only collection actually slower is minopts coreclr-tests; the other collections are all faster, so possibly a scaling issue with some of the crazier tests. We may gain some of this back in the next stage of work.

Maybe related to #78267?

**Comment by AndyAyersMS** [comment]
> Maybe run some stress pipelines?

Sure.

> > TP impact looks high ...
> 
> Maybe related to #78267?

Yeah, probably cases like that one. Add/Remove ref can also be quadratic in worst case since they have to search a list, but it only matters when there are huge numbers of predecessors.

**Comment by AndyAyersMS** [comment]
Looks like some widespread jitstress issue. Will investigate.

**Comment by AndyAyersMS** [comment]
Stress is green.

**Pull request merged**
