### PR TITLE
enable TieredPGO by default

### PR DESCRIPTION
**Pull request by AndyAyersMS**

### CODE REVIEW

**Comment by stephentoub** [comment]
❤️❤️❤️❤️❤️❤️❤️

**Comment by Sewer56** [comment]
💜

**Comment by AndyAyersMS** [comment]
Looks like `tracing.runtimeeventsource` times out on linux / osx x64:
```
  Starting:    tracing.runtimeeventsource.XUnitWrapper (parallel test collections = on, max threads = 2)
   tracing.runtimeeventsource.XUnitWrapper: [Long Running Test] 'tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh', Elapsed: 00:02:11
   tracing.runtimeeventsource.XUnitWrapper: [Long Running Test] 'tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh', Elapsed: 00:04:12
...
   tracing.runtimeeventsource.XUnitWrapper: [Long Running Test] 'tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh', Elapsed: 01:48:12
   tracing.runtimeeventsource.XUnitWrapper: [Long Running Test] 'tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh', Elapsed: 01:50:12
Killed
['PayloadGroup0' END OF WORK ITEM LOG: Command timed out, and was killed]
```

**Comment by AndyAyersMS** [comment]
Outerloop failures look to be pre-existing (though there are enough that it is hard to be 100% sure).

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL

cc @dotnet/jit-contrib

**Review by EgorBo — APPROVED** [review]
giphy

**Comment by AndyAyersMS** [comment]
Also https://github.com/dotnet/perf-autofiling-issues/issues/18171 (possible dup?)

**Pull request merged**
