### PR TITLE
[wasm][debugger] Implementing support to Debugger::Break.

### LINKED ISSUE #44210: Blazor Web Assembly call Azure Function crashes .Net 5.0 rc2
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-Web-Assembly-call-Azure-Function-/1232255?preview=true)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:.Net 5.0 rc2]
I recreated this in a very simple pair of projects.  Project 1 is a Blazor WebAssembly project.  Project 2 is an Azure Function project.  Only change to Blazor project was to setup CORS and add code to all Azure Function.  Just go to the Fetch data page and the error will happen.  The Browser window will crash in the Web Assembly code.  Look at the F12 debugger on the console.  See BlazorCrash.zip for project files.  This seems to happen all calling to Functions.  This used to work at I am blocked from using rc2 because of this.

Uncaught (in promise) RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (https://localhost:44358/_framework/dotnet.5.0.0-rc.2.20475.5.js:1:14903)
    at _abort (https://localhost:44358/_framework/dotnet.5.0.0-rc.2.20475.5.js:1:105666)
    at stub_debugger_agent_user_break (<anonymous>:wasm-function[6500]:0xf94a6)
    at do_debugger_tramp (<anonymous>:wasm-function[3306]:0x79e23)
    at interp_exec_method (<anonymous>:wasm-function[2155]:0x442e1)
    at interp_runtime_invoke (<anonymous>:wasm-function[7859]:0x12ef59)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7344]:0x118db9)
    at do_runtime_invoke (<anonymous>:wasm-function[3304]:0x79d37)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[629]:0x12977)
    at mono_runtime_invoke (<anonymous>:wasm-function[7115]:0x10eb85)
abort @ dotnet.5.0.0-rc.2.20475.5.js:1
_abort @ dotnet.5.0.0-rc.2.20475.5.js:1
stub_debugger_agent_user_break @ 00ab9d9a:0xf94a6
do_debugger_tramp @ 00ab9d9a:0x79e23
interp_exec_method @ 00ab9d9a:0x442e1
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_try_invoke @ 00ab9d9a:0x12977
mono_runtime_invoke @ 00ab9d9a:0x10eb85
mono_wasm_invoke_method @ 00ab9d9a:0x108e03
Module._mono_wasm_invoke_method @ dotnet.5.0.0-rc.2.20475.5.js:1
call_method @ dotnet.5.0.0-rc.2.20475.5.js:1
set_task_result @ dotnet.5.0.0-rc.2.20475.5.js:1
(anonymous) @ dotnet.5.0.0-rc.2.20475.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.0-rc.2.20475.5.js:1
mono_wasm_convert_return_value @ dotnet.5.0.0-rc.2.20475.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.0-rc.2.20475.5.js:1
do_icall @ 00ab9d9a:0x194d3f
do_icall_wrapper @ 00ab9d9a:0x79dee
interp_exec_method @ 00ab9d9a:0x44ac8
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_try_invoke @ 00ab9d9a:0x12977
mono_runtime_invoke @ 00ab9d9a:0x10eb85
mono_wasm_invoke_method @ 00ab9d9a:0x108e03
Module._mono_wasm_invoke_method @ dotnet.5.0.0-rc.2.20475.5.js:1
call_method @ dotnet.5.0.0-rc.2.20475.5.js:1
set_task_result @ dotnet.5.0.0-rc.2.20475.5.js:1
(anonymous) @ dotnet.5.0.0-rc.2.20475.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.0-rc.2.20475.5.js:1
mono_wasm_convert_return_value @ dotnet.5.0.0-rc.2.20475.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.0-rc.2.20475.5.js:1
do_icall @ 00ab9d9a:0x194d3f
do_icall_wrapper @ 00ab9d9a:0x79dee
interp_exec_method @ 00ab9d9a:0x44ac8
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_try_invoke @ 00ab9d9a:0x12977
mono_runtime_invoke @ 00ab9d9a:0x10eb85
mono_wasm_invoke_method @ 00ab9d9a:0x108e03
Module._mono_wasm_invoke_method @ dotnet.5.0.0-rc.2.20475.5.js:1
call_method @ dotnet.5.0.0-rc.2.20475.5.js:1
set_task_result @ dotnet.5.0.0-rc.2.20475.5.js:1
(anonymous) @ dotnet.5.0.0-rc.2.20475.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.0-rc.2.20475.5.js:1
mono_wasm_convert_return_value @ dotnet.5.0.0-rc.2.20475.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.0-rc.2.20475.5.js:1
do_icall @ 00ab9d9a:0x194d3f
do_icall_wrapper @ 00ab9d9a:0x79dee
interp_exec_method @ 00ab9d9a:0x44ac8
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_try_invoke @ 00ab9d9a:0x12977
mono_runtime_invoke @ 00ab9d9a:0x10eb85
mono_wasm_invoke_method @ 00ab9d9a:0x108e03
Module._mono_wasm_invoke_method @ dotnet.5.0.0-rc.2.20475.5.js:1
call_method @ dotnet.5.0.0-rc.2.20475.5.js:1
set_task_result @ dotnet.5.0.0-rc.2.20475.5.js:1
(anonymous) @ dotnet.5.0.0-rc.2.20475.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.0-rc.2.20475.5.js:1
mono_wasm_convert_return_value @ dotnet.5.0.0-rc.2.20475.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.0-rc.2.20475.5.js:1
do_icall @ 00ab9d9a:0x194d3f
do_icall_wrapper @ 00ab9d9a:0x79dee
interp_exec_method @ 00ab9d9a:0x44ac8
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_invoke_checked @ 00ab9d9a:0xf652
mono_runtime_try_invoke_array @ 00ab9d9a:0x10e78b
ves_icall_InternalInvoke @ 00ab9d9a:0xed487
ves_icall_InternalInvoke_raw @ 00ab9d9a:0xecf4c
do_icall @ 00ab9d9a:0x194d3f
do_icall_wrapper @ 00ab9d9a:0x79dee
interp_exec_method @ 00ab9d9a:0x44ac8
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_try_invoke @ 00ab9d9a:0x12977
mono_runtime_invoke @ 00ab9d9a:0x10eb85
mono_wasm_invoke_method @ 00ab9d9a:0x108e03
Module._mono_wasm_invoke_method @ dotnet.5.0.0-rc.2.20475.5.js:1
call_method @ dotnet.5.0.0-rc.2.20475.5.js:1
(anonymous) @ dotnet.5.0.0-rc.2.20475.5.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
h @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
d @ blazor.webassembly.js:1
f @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
e.onGlobalEvent @ blazor.webassembly.js:1
Show 44 more frames

---
#### Feedback Bot on 10/25/2020, 09:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Brett McDonald on 10/27/2020, 08:10 AM: 

<p>Is there any word on this?  This is a showstopper for me.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by thaystg**
Fixes #44210

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
Browser failure looks like https://github.com/dotnet/runtime/issues/44214 so I don't think the new skipping method worked either.  Maybe the attribute needs to be on the concrete class?  Interesting that does pass sometime, it would probably pass all the time if it skipped the sync version of the tests.

https://dev.azure.com/dnceng/public/_build/results?buildId=876685&view=logs&j=108d2c4a-8a62-5a58-8dad-8e1042acc93c&t=09a92b4c-3493-52a9-1172-0680b62c9e30&l=94
```
[16:57:36] info: MONO_WASM: Initializing mono runtime
[16:57:36] info: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
[16:57:36] info: mono_wasm_runtime_ready
[16:57:36] info: Initializing.....
[16:57:36] info: Discovering: System.IO.FileSystem.Tests.dll (method display = ClassAndMethod, method display options = None)
[16:57:39] info: Discovered:  System.IO.FileSystem.Tests.dll (found 2623 of 3305 test cases)
[16:57:39] info: Starting:    System.IO.FileSystem.Tests.dll
[16:57:51] fail: [FAIL] System.IO.Tests.UnbufferedAsyncFileStreamStandaloneConformanceTests.Read_PartiallySatisfied_RemainderOfBufferUntouched(mode: SyncSpan)
[16:57:51] info: System.PlatformNotSupportedException : Cannot wait on monitors on this runtime.
[16:57:51] info:    at System.Threading.Monitor.ObjWait(Int32 millisecondsTimeout, Object obj)
[16:57:51] info:    at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
[16:57:51] info:    at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[16:57:51] info:    at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[16:57:51] info:    at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[16:57:51] info:    at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[16:57:51] info:    at System.IO.FileStream.Read(Byte[] buffer, Int32 offset, Int32 count)
[16:57:51] info:    at System.IO.Stream.Read(Span`1 buffer)
[16:57:51] info:    at System.IO.FileStream.Read(Span`1 buffer)
[16:57:51] info:    at System.IO.Tests.StreamConformanceTests.ReadAsync(ReadWriteMode mode, Stream stream, Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
[16:57:51] info:    at System.IO.Tests.StandaloneStreamConformanceTests.Read_PartiallySatisfied_RemainderOfBufferUntouched(ReadWriteMode mode)
[16:57:51] info: --- End of stack trace from previous location ---
[16:57:51] fail: [FAIL] System.IO.Tests.UnbufferedAsyncFileStreamStandaloneConformanceTests.Read_PartiallySatisfied_RemainderOfBufferUntouched(mode: SyncArray)
[16:57:51] info: System.PlatformNotSupportedException : Cannot wait on monitors on this runtime.
[16:57:51] info:    at System.Threading.Monitor.ObjWait(Int32 millisecondsTimeout, Object obj)
[16:57:51] info:    at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
[16:57:51] info:    at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[16:57:51] info:    at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[16:57:51] info:    at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[16:57:51] info:    at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[16:57:51] info:    at System.IO.FileStream.Read(Byte[] buffer, Int32 offset, Int32 count)
[16:57:51] info:    at System.IO.Tests.StreamConformanceTests.ReadAsync(ReadWriteMode mode, Stream stream, Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
[16:57:51] info:    at System.IO.Tests.StandaloneStreamConformanceTests.Read_PartiallySatisfied_RemainderOfBufferUntouched(ReadWriteMode mode)
[16:57:51] info: --- End of stack trace from previous location ---
[16:58:46] info: )
[16:58:46] info: fo_Directory.AltSeparatorCharInPath
[16:58:46] info: em.IO.Tests.Directory_EnumFiles_str_str_so.UnixSearchPatternFileValidChar(valid: "\n")
[16:58:46] info: nTests_DosDotQm(pattern: "foo.???.?.?.?", sourceFiles: ["foo", "foo.t", "foo.tx", "foo.txt", "bar.txt", ...], expected: ["foo", "foo.t", "foo.tx", "foo.txt"])
[16:58:46] info: foo.??", sourceFiles: ["foo", "foo.", "foo.t", "foo.tx", "foo.txt", ...], expected: ["foo", "foo.", "foo.t", "foo.tx"])
[16:58:46] info: le
[16:58:47] info: Finished:    System.IO.FileSystem.Tests.dll
[16:58:47] info: 
[16:58:47] info: === TEST EXECUTION SUMMARY ===
[16:58:47] info: Total: 4763, Errors: 0, Failed: 2, Skipped: 80, Time: 67.10568s
[16:58:47] info: 
[16:58:47] info: WASM EXIT 1
```
cc @stephentoub

**Comment by lewing** [comment]
@akoeplinger any idea what is going on with the corrupt text at the end of that failure?  You can see a slightly different version on #44214  as well

**Comment by akoeplinger** [comment]
Hm no, that's weird.

**Pull request merged**
