### PR TITLE
JIT: Properly allocate shadow space for block op helpers on win-x64

### LINKED ISSUE #80140: CoreCLR JIT-generated code does not respect the Win x64 calling convention for the Memcpy/Memset helper calls
### Description

On Windows-x64, the calling convention requires 32 bytes of outgoing args space for a call. The JIT correctly accounts for this requirement and provides the space, except when calling the JIT helpers for `CORINFO_HELP_MEMSET` and `CORINFO_HELP_MEMCPY`. These helpers are only referenced in the CodeGen phase (and the decision to use them is only calculated in the Lowering phase), but the outgoing args space size is calculated in simple lowering. As a result, a method that does not call any functions other than `CORINFO_HELP_MEMSET` or `CORINFO_HELP_MEMCPY` will not have the required outgoing args space.

The standard CRT implementation for `memmove` and `memset` in the CRT is hand-rolled assembly, so it doesn't try to use the missing args space, which is why this has never been noticed. However, while working on bringing up AddressSanitizer on CoreCLR, I encountered this issue because ASAN intercepts `memset` (and `memmove`) to do its tracking, and the generated code does try to use the (missing) outgoing args space, causing intermittent failures.

### Reproduction Steps

Look at the optimized generated code (no TC or Tier 1) for any method that only calls MemSet and no other functions, such as `Span<byte>.Fill()`.

### Expected behavior

There should be at least the `MIN_ARG_AREA_FOR_CALL` outgoing args space.

### Actual behavior

There is no outgoing args space on Windows-x64.

### Regression?

_No response_

### Known Workarounds

I have a patch in the ASAN branch that updates the helper implementations in CoreCLR to allocate the missing space before calling the helpers on Windows-x64 when the runtime is built with ASAN enabled, but I'd prefer to not have to keep this workaround.

### Configuration

Windows x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by jakobbotsch**
Move the accounting of the outgoing arg space size from simple lowering to lowering and start accounting for the fact that some block ops may turn into helper calls.

Fix #80140

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Need to look into some unexpected regressions:
image

**Comment by jakobbotsch** [comment]
> Need to look into some unexpected regressions:

The problem is that we have a dead `STORE_BLK` that we classify as needing a helper:
```scala
*************** Starting PHASE Lowering nodeinfo
lowering store lcl var/field (before):
N001 (  1,  1) [000002] -----------                    t2 =    CNS_INT   int    0 $42
                                                            ┌──▌  t2     int    
N003 ( 11,  8) [000003] DA---------                         ▌  STORE_LCL_VAR struct<Runtime_45090._2000, 8192> V01 loc0         d:2


Local V01 should not be enregistered because: written/read in a block op
Bumping outgoing arg space size from 0 to 32 for [000003]
lowering store lcl var/field (after):
N001 (  1,  1) [000002] -----------                    t2 =    CNS_INT   int    0 $42
               [000018] D----------                   t18 =    LCL_FLD_ADDR byref  V01 loc0         [+0]
                                                            ┌──▌  t18    byref  
                                                            ├──▌  t2     int    
N003 ( 11,  8) [000003] sA---------                         ▌  STORE_BLK struct<Runtime_45090._2000, 8192> (init) (Helper)


...

*************** In fgInterBlockLocalVarLiveness()

BB liveness after fgLiveVarAnalysis():

BB01 IN (0)={}
     OUT(0)={}

Removing dead indirect store:
N003 ( 11,  8) [000003] sA---------                         ▌  STORE_BLK struct<Runtime_45090._2000, 8192> (init) (Helper)
Removing dead LclVar address:
               [000018] D----------                         ▌  LCL_FLD_ADDR byref  V01 loc0         [+0] (last use)
Removing dead node:
N001 (  1,  1) [000002] -----------                         ▌  CNS_INT   int    0 $42
```

I will just leave this rare case as is.

TP regressions are because MSVC no longer uses a switch table in `fgSimpleLowering` with the removal of the `GT_CAST` cast. The detailed breakdown is:
```scala
Base: 56113164932, Diff: 56146201461, +0.0589%

?fgSimpleLowering@Compiler@@QEAA?AW4PhaseStatus@@XZ                                                                 : 26085033 : +32.88% : 78.30% : +0.0465%
?LowerCall@Lowering@@AEAAPEAUGenTree@@PEAU2@@Z                                                                      : 3071019  : +9.69%  : 9.22%  : +0.0055%
memset                                                                                                              : 2676011  : +0.64%  : 8.03%  : +0.0048%
?DoPhase@Lowering@@UEAA?AW4PhaseStatus@@XZ                                                                          : 1226965  : +3.52%  : 3.68%  : +0.0022%
?fgPerBlockLocalVarLiveness@Compiler@@QEAAXXZ                                                                       : 57580    : +0.02%  : 0.17%  : +0.0001%
?compCompile@Compiler@@IEAAXPEAPEAXPEAIPEAVJitFlags@@@Z                                                             : 35599    : +0.05%  : 0.11%  : +0.0001%
?AssignAllowUninitRhs@?$BitSetOps@PEA_K$00PEAVCompiler@@VTrackedVarBitSetTraits@@@@SAXPEAVCompiler@@AEAPEA_KPEA_K@Z : -121818  : -1.23%  : 0.37%  : -0.0002%
```

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=222737&view=ms.vss-build-web.run-extensions-tab). As expected mostly regressions from the new prolog/epilog code. Sometimes improvements for the unrolled memmoves that we now realize we don't need to allocate shadow space for.

cc @dotnet/jit-contrib PTAL @TIHan @kunalspathak

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by jkoritzinsky** [comment]
@jakobbotsch is this ready to be merged in?

**Comment by jakobbotsch** [comment]
> @jakobbotsch is this ready to be merged in?

Yep, done now (I was OOF yesterday).

**Pull request merged**
