### PR TITLE
Fix NCL stress tests after ProductVersion upgrade

### LINKED ISSUE #74604: NCL stress tests fail to build since ProductVersion update to 8.0.0
In #61689 HttpStress and SslStress has been updated to utilize the live-built runtime with the help of `targetingpacks.targets` in a manner similar to our unit and functional tests.

Builds are broken since #73985: with `ProductVersion` still set to 7.0.0 in our tests, we get the usual framework resolution error "`You must install or update .NET to run this application`".

However, bumping `ProductVersion` in our [`Directory.Build.props`](https://github.com/dotnet/runtime/blob/48713582dd5a8a27e4d1439725777250d0694ed9/src/libraries/System.Net.Http/tests/StressTests/HttpStress/Directory.Build.props#L10) seems to be insufficient. After setting it to `8.0.0`, `<testhost>/dotnet.exe exec HttpStress.dll` reports the following error:

```
The specified framework 'Microsoft.NETCore.App', version '7.0.0-rc.1.22422.12', apply_patches=1, version_compatibility_range=patch cannot roll-forward to the previously referenced version '8.0.0'.
```

Note that one tricky detail is that we need to use the `7.0.0` `Microsoft.AspNetCore.App` runtime (currently `7.0.0-rc.2.22424.4`) together with the live-built `Microsoft.NETCore.App`.

@ViktorHofer any idea how to solve this, or what should be my next troubleshooting step? This is a high-priority issue, since we need to get stress tests running to stabilize QUIC / HTTP3.

### PR DESCRIPTION
**Pull request by antonfirsov**
Fixes #74604

- Set `ProductVersion` to `8.0.0`
- Configure roll-forward as recommended in https://github.com/dotnet/runtime/issues/74604#issuecomment-1235844402
- Build non-containerized SslStress using a private dotnet install, just like HttpStress

### CODE REVIEW

**Comment by MihaZupan** [comment]
Should the other 7.0 constants also be updated ([in](https://github.com/dotnet/runtime/blob/58da3e93c9f821f8308ad435a6d3d4cea8a73618/src/libraries/System.Net.Http/tests/StressTests/HttpStress/Dockerfile#L23) [dockerfiles](https://github.com/dotnet/runtime/blob/58da3e93c9f821f8308ad435a6d3d4cea8a73618/src/libraries/System.Net.Http/tests/StressTests/HttpStress/windows.Dockerfile#L11), [Build.targets](https://github.com/dotnet/runtime/blob/58da3e93c9f821f8308ad435a6d3d4cea8a73618/src/libraries/System.Net.Http/tests/StressTests/HttpStress/Directory.Build.targets#L9))?

**Review by MihaZupan — APPROVED** [review]

**Comment by antonfirsov** [comment]
> Should the other 7.0 constants also be updated ([in](https://github.com/dotnet/runtime/blob/58da3e93c9f821f8308ad435a6d3d4cea8a73618/src/libraries/System.Net.Http/tests/StressTests/HttpStress/Dockerfile#L23) [dockerfiles](https://github.com/dotnet/runtime/blob/58da3e93c9f821f8308ad435a6d3d4cea8a73618/src/libraries/System.Net.Http/tests/StressTests/HttpStress/windows.Dockerfile#L11), [Build.targets](https://github.com/dotnet/runtime/blob/58da3e93c9f821f8308ad435a6d3d4cea8a73618/src/libraries/System.Net.Http/tests/StressTests/HttpStress/Directory.Build.targets#L9))?

Not yet. Unless I missed a PR `NetCoreAppCurrent` is still `7.0` on main.

**Pull request merged**
