### PR TITLE
Broaden checks for BigInteger.Multiply

### PR DESCRIPTION
**Pull request by ts2do**
Multiply methods will call simpler algorithms for additional applicable cases.
These are the last few worthwhile changes I see in BigInteger.

### CODE REVIEW

**Comment by stephentoub** [comment]
@ts2do, presumably this is for performance? Can you share your perf tests and results?

@tannergooding, any feedback on the change?

Thanks.

**Comment by ts2do** [comment]
Yes, this is for performance. For the `Multiply(ref BigInteger, uint, out BigInteger)` and `Multiply(ref BigInteger, ref BigInteger, out BigInteger)` overloads, the change results in reducing the number of branches when the operation can't be simplified while adding one branch when it can be simplified. Would benchmarking the BigInteger methods directly be sufficient here?

**Comment by stephentoub** [comment]
> Would benchmarking the BigInteger methods directly be sufficient here?

Yes, thanks.

**Comment by stephentoub** [comment]
>> Would benchmarking the BigInteger methods directly be sufficient here?

> Yes, thanks.

Oh, actually, for a moment I was thinking this was about the public BigInteger, but it's not.  It'd be good to benchmark the public APIs through which this actually surfaces.

**Comment by tannergooding** [comment]
Changes look reasonable to me, but it would be good if we had some perf numbers showing the improvements to be had.

**Comment by ts2do** [comment]
I'm reviewing the changes to try to eliminate/limit impact on the slow path. I'll try to have something ready ASAP.

**Comment by ts2do** [comment]
Here are 4 tests I came up with to benchmark this:
```csharp
bool BigInteger1() => double.TryParse("1.23456789012345678901234567890123456789e15", out _);
string BigInteger2() => 1e-99.ToString("F99");
bool BigInteger3() => double.TryParse("1.234567890123456", out _);
string BigInteger4() => 1e99.ToString("F");
```

And here's the output:
|      Method |       Mean |    Error |   StdDev |     Median |        Min |        Max | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |-----------:|---------:|---------:|-----------:|-----------:|-----------:|------:|--------:|-------:|------:|------:|----------:|
| BigInteger1 |   440.5 ns |  6.36 ns |  5.31 ns |   439.6 ns |   431.9 ns |   450.8 ns |  0.91 |    0.01 |      - |     - |     - |         - |
| BigInteger1 |   482.4 ns |  8.71 ns |  8.15 ns |   480.8 ns |   473.2 ns |   498.2 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|             |            |          |          |            |            |            |       |         |        |       |       |           |
| BigInteger2 |   513.0 ns |  3.72 ns |  3.48 ns |   513.6 ns |   508.3 ns |   519.6 ns |  0.97 |    0.01 | 0.0519 |     - |     - |     224 B |
| BigInteger2 |   531.7 ns |  6.61 ns |  5.52 ns |   532.8 ns |   523.4 ns |   541.8 ns |  1.00 |    0.00 | 0.0529 |     - |     - |     224 B |
|             |            |          |          |            |            |            |       |         |        |       |       |           |
| BigInteger3 |   335.2 ns |  1.82 ns |  1.61 ns |   335.4 ns |   332.6 ns |   337.9 ns |  0.98 |    0.01 |      - |     - |     - |         - |
| BigInteger3 |   343.7 ns |  2.97 ns |  2.48 ns |   342.9 ns |   341.8 ns |   350.9 ns |  1.00 |    0.00 |      - |     - |     - |         - |
|             |            |          |          |            |            |            |       |         |        |       |       |           |
| BigInteger4 | 4,603.4 ns | 86.09 ns | 84.55 ns | 4,585.8 ns | 4,527.4 ns | 4,803.1 ns |  1.01 |    0.02 | 0.0549 |     - |     - |     232 B |
| BigInteger4 | 4,565.2 ns | 27.43 ns | 24.31 ns | 4,565.2 ns | 4,535.0 ns | 4,616.0 ns |  1.00 |    0.00 | 0.0548 |     - |     - |     232 B |

**Comment by tannergooding** [comment]
Closing and reopening to retrigger the jobs against current master. This should be good to merge once they pass.

**Review by tannergooding — APPROVED** [review]

**Comment by ts2do** [comment]
@tannergooding Will this ever be merged?

**Comment by danmosemsft** [comment]
Let's try to get green CI so we can merge this.

**Comment by danmosemsft** [comment]
Failing leg seems defunct now.

**Comment by danmosemsft** [comment]
Thanks @ts2do for the contribution. We are going to try to improve our processes for next cycle to get PRS to merge more quickly.

**Pull request merged**
