### PR TITLE
Propagate VNF_PtrToLoc(lcl, offset) as GT_LCL_ADDR node

### PR DESCRIPTION
**Pull request by EgorBo**
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=675605&view=ms.vss-build-web.run-extensions-tab)

### CODE REVIEW

**Comment by EgorBo** [comment]
PTAL @jakobbotsch @dotnet/jit-contrib 

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=675605&view=ms.vss-build-web.run-extensions-tab). I decided to give up on side-effects since they didn't improve the diffs. Also, the "is constant profitable to propagate" doesn't apply here

**Review by jakobbotsch — APPROVED** [review]
LGTM. I kicked off a Fuzzlyn run

**Comment by EgorBo** [comment]
Fuzzlyn is all green

**Pull request merged**
