### PR TITLE
Rename `SafeSecKeyRefHandle`

### PR DESCRIPTION
**Pull request by xtqqczze**
`SafeSecKeyRefHandle` would be better named as `SafeSecKeyHandle`.

This is to be consistent with the other safe handles used for marshalling in Interop, for example `CFStringRef` in our C code becomes `SafeCFStringHandle` in C#.

### CODE REVIEW

**Comment by vcsjones** [comment]
The handles are wrapping a [`SecKeyRef`](https://developer.apple.com/documentation/security/seckeyref). For example:

https://github.com/dotnet/runtime/blob/55e1ac7c07df62c4108d4acedf78f77574470ce5/src/native/libs/System.Security.Cryptography.Native.Apple/pal_x509.c#L63

**Comment by xtqqczze** [comment]
> The handles are wrapping a [`SecKeyRef`](https://developer.apple.com/documentation/security/seckeyref).

It can be `SecKey` in a language with reference types. Look at the documentation for [`SecKey`](https://developer.apple.com/documentation/security/seckey) and notice the name changes to `SecKeyRef` when the display language is changed from Swift to Obective-C.

**Comment by xtqqczze** [comment]
Consider the existing `SafeCFErrorHandle` in C#, which corresponds to a _[`CFError`](https://developer.apple.com/documentation/corefoundation/cferror)_ class in Swift:
https://github.com/dotnet/runtime/blob/ebd2cb6ec87a4e40f80812b0a20257ff7ef176e4/src/libraries/Common/src/Interop/OSX/Interop.CoreFoundation.CFError.cs#L52

We use the `SafeCFErrorHandle` in a PInvoke in C#:

https://github.com/dotnet/runtime/blob/ebd2cb6ec87a4e40f80812b0a20257ff7ef176e4/src/libraries/Common/src/Interop/OSX/System.Security.Cryptography.Native.Apple/Interop.SecKeyRef.cs#L157-L164

However lacking reference types we use a _[`CFErrorRef`](https://developer.apple.com/documentation/corefoundation/cferrorref?language=objc)_ structure in C.

https://github.com/dotnet/runtime/blob/ebd2cb6ec87a4e40f80812b0a20257ff7ef176e4/src/native/libs/System.Security.Cryptography.Native.Apple/pal_seckey.c#L26-L31

**Comment by bartonjs** [comment]
When interoperating with these handles we're using C, where they're called `SecKeyRef`.  Therefore the current name is more correct.

**Comment by xtqqczze** [comment]
> When interoperating with these handles we're using C, where they're called `SecKeyRef`. Therefore the current name is more correct.

@bartonjs @vcsjones Literally all other types that have safe handles in C# are named "Safe{Name}Handle", not "Safe{Name}RefHandle", a few examples:

- `CFArrayRef` -> `SafeCFArrayHandle`
- `CFDataRef` -> `SafeCFDataHandle`
- `CFDateRef` -> `SafeCFDateHandle`
- `CFDictionaryRef` -> `SafeCFDictionaryHandle`
- `CFErrorRef` -> `SafeCFErrorHandle`
- `CFStringRef` -> `SafeCFStringHandle`
- `CFStringRef` -> `SafeCreateHandle`
- `FSEventStreamRef` -> `SafeEventStreamHandle`
- `SecKeychainRef` -> `SafeKeychainHandle`
- `SecKeychainRef` -> `SafeTemporaryKeychainHandle`
- `CFTypeRef` -> `SafeKeychainItemHandle`

**Comment by xtqqczze** [comment]
`SafeSecKeyRefHandle` is actually the only match for `Safe[^\s]+RefHandle` in the repository.

**Pull request closed without merging**
