### PR TITLE
Draft: Try to identify the scenario that causes stat throw EINVAL in OSX

### PR DESCRIPTION
**Pull request by jozkee**
Related to https://github.com/dotnet/runtime/issues/57221

### CODE REVIEW

**Comment by adamsitnik** [comment]
which syscall gives us an EINVAL?

**Comment by Jozkee** [comment]
@adamsitnik I suspect is stat since the call-stack in https://github.com/dotnet/runtime/issues/57221 is related to validation of lstat and stat caches in FileSystem.Unix.cs. However I find it strange since there is no documentation stating that stat is capable of throwing EINVAL. You can look at the conversation I had with Dan for context https://github.com/dotnet/runtime/issues/57221#issuecomment-898615402. I also find it very strange that it only fails in macOS/OSX.

**Comment by Jozkee** [comment]
Based on the latest [helix log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57502-merge-185dcbeef11e44cf9b/Microsoft.Extensions.FileProviders.Physical.Tests/1/console.9ec10b68.log?sv=2019-07-07&se=2021-09-05T21%3A08%3A00Z&sr=c&sp=rl&sig=Glt95w9lY2qYsN99aRdH0R4DAyIUCElep2OaugEkLDw%3D), I think we can be more certain that the issue is in the stat performed in `FileSystemInfo.Refresh()`.
```
Unhandled exception. System.IO.IOException: Invalid argument : '/var/folders/4m/hrs4drf17cxbyfbbkbhtxczh0000gy/T/afbguk0e.avl/UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetDeleted_133_4d15e445'
   at System.IO.FileStatus.ThrowOnCacheInitializationError(ReadOnlySpan`1 path) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileStatus.Unix.cs:line 418
   at System.IO.FileStatus.GetLastWriteTime(ReadOnlySpan`1 path, Boolean continueOnError) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileStatus.Unix.cs:line 284
   at System.IO.FileSystemInfo.get_LastWriteTimeUtc() in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystemInfo.cs:line 115
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.GetLastWriteTimeUtc() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PollingFileChangeToken.cs:line 61
   at Microsoft.Extensions.FileProviders.Physical.PollingFileChangeToken.get_HasChanged() in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PollingFileChangeToken.cs:line 108
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.RaiseChangeEvents(Object state) in /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs:line 455
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 673
   at System.Threading.TimerQueue.FireNextTimers() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Timer.cs:line 327
```

And judging by the filename which shows the test in which is being created (UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetDeleted_133_4d15e445), it might have something to do with the file ceasing to exist between lstat (line 354) and stat (line 365). cc @carlossanlop

https://github.com/dotnet/runtime/blob/c0fc818cd41d30e78f284382951c36c8cc804e1e/src/libraries/System.Private.CoreLib/src/System/IO/FileStatus.Unix.cs#L345-L369

I'm still curious why this happens on macOS 1014 and 1015, I've stressed calling stat with multiple invalid paths but none has returned me the error "Invalid argument"/EINVAL.

**Comment by Jozkee** [comment]
Closing as I was finally able to repro locally.

**Pull request closed without merging**
