### PR TITLE
Enable nullability on System.Xml.XPath

### PR DESCRIPTION
**Pull request by jozkee**
Contributes to https://github.com/dotnet/runtime/issues/2339
~No annotations are needed for the APIs exposed in this assembly.~
Add missing annotations to `XPathException`.

### CODE REVIEW

**Comment by stephentoub** [comment]
> No annotations are needed for the APIs exposed in this assembly.

That doesn't sound right. For example, I see there's an XpathException type, and its message and inner exception arguments should be nullable.

**Comment by Jozkee** [comment]
@stephentoub 
* InnerException is not overriden so is not declared in the ref.
* Exception.Message is overriden but I can see that the base definition is not `string?`.
https://source.dot.net/#System.Private.CoreLib/Exception.cs,5fba0e16215b42a3,references

**Comment by buyaa-n** [comment]
> * InnerException is not overriden so is not declared in the ref.
> * Exception.Message is overriden but I can see that the base definition is not `string?`.
>   https://source.dot.net/#System.Private.CoreLib/Exception.cs,5fba0e16215b42a3,references

Constructor overloads accept nullable
https://source.dot.net/#System.Private.CoreLib/Exception.cs,32

**Comment by Jozkee** [comment]
@stephentoub @buyaa-n you are right, I missed the `message` parameter in the src annotations as well. Will add them here.

**Review by jeffhandley — APPROVED** [review]
~~LGTM.  @buyaa-n can you take a look too?~~

Never mind -- I see you already did; I needed to refresh.

**Review by buyaa-n — APPROVED** [review]
LGTM, thanks!

**Comment by jeffhandley** [comment]
@Jozkee Is there anything left on this one, or is it ready for merge?  Did you want a review from @krwq first?

**Comment by Jozkee** [comment]
@jeffhandley I think is fine, will merge now...

**Comment by krwq** [comment]
LGTM thanks!

**Pull request merged**
