### PR TITLE
[release/6.0][iOS] Grab the default timezone using native API

### PR DESCRIPTION
**Pull request by steveisok**
Backport of https://github.com/dotnet/runtime/pull/70149

## Customer Impact
When loading the default time zone on iOS apps, `/etc/localtime` and `/usr/share/zoneinfo/localtime` are not found.  As a result, we will default to UTC and not take into account the time zone on the device.

This change adds a lookup of the device's time zone name.

## Testing
A unit test was added to validate the local time zone of the device was not UTC.

## Risk
Low

### CODE REVIEW

**Comment by carlossanlop** [comment]
@steveisok this was approved for servicing, but still needs approval from an area owner. How are the tests looking?

**Comment by steveisok** [comment]
Tests are good from this PR.  There were a few legs that need re-run.

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
the failures appear to be out of date queue failures

**Comment by carlossanlop** [comment]
@lewing I believe you're seeing the error that will be fixed by this PR: https://github.com/dotnet/runtime/pull/70570

After merging that helix PR, I'll retry the failed legs here.

**Pull request merged**
