### PR TITLE
Update to the stable 7.0.100 SDK

### PR DESCRIPTION
**Pull request by ViktorHofer**

### CODE REVIEW

**Comment by agocke** [comment]
Thanks for getting this started -- I think we should also eventually do this for the 7.0 branch.

**Comment by kasperk81** [comment]
@ViktorHofer is this blocked on something?

**Comment by marek-safar** [comment]
@vzarytovskii is the error `resource ILLink.Substitutions.xml in FSharp.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a(3,6): error IL2040: FSharp.Core: Could not find embedded resource 'FSharpOptimizationCompressedData.FSharp.Core' to remove in assembly 'FSharp.Core'. [/__w/1/s/src/libraries/System.Formats.Cbor/tests/System.Formats.Cbor.Tests.csproj::TargetFramework=net7.0]
` know issue ?

**Comment by ViktorHofer** [comment]
> @ViktorHofer is this blocked on something?

Not blocked on anything. We just need to spend some time to understand the build and test failures. Thanks @marek-safar for starting with that.

**Comment by vzarytovskii** [comment]
> @vzarytovskii is the error `resource ILLink.Substitutions.xml in FSharp.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a(3,6): error IL2040: FSharp.Core: Could not find embedded resource 'FSharpOptimizationCompressedData.FSharp.Core' to remove in assembly 'FSharp.Core'. [/__w/1/s/src/libraries/System.Formats.Cbor/tests/System.Formats.Cbor.Tests.csproj::TargetFramework=net7.0]
> ` know issue ?

Those resources may or may not be there, depending on which compiler version is used (newer versions are compressing resource, older do not).
When it was added (by @teo-tsirpanis), we assumed that linker will just ignore it if it's missing.

**Comment by teo-tsirpanis** [comment]
The error is actually a warning so we can suppress it.

**Comment by vzarytovskii** [comment]
> I don't think we want to suppress this warning for whole runtime repo and updating each affected project manually is not a great experience either.

I have disabled trimming all resorces for `FSharp.Core` - https://github.com/dotnet/fsharp/pull/14395
It will take time to insert, propagate and release though.

**Comment by kasperk81** [comment]
> Could not find embedded resource 'FSharpOptimizationCompressedData.FSharp.Core'

false alarm: f# package has never included this resource. runtime has no control over that package. usage is same as before. so it should not raise to "error" level

> for whole runtime repo

there are five fsproj files in this repo and only one of them is trimmed: cbor test project. suppressing the warning in one file or removing cbor test project from trimming test should be alright for sdk update (esp when the error's severity itself is in question)

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
Suppressing the linker warning about the missing F# resource was indeed just necessary in one project so I went with that. We can remove it once the F# fix propagates.

The MacCatalyst failure is unrelated.

**Comment by akoeplinger** [comment]
> Thanks for getting this started -- I think we should also eventually do this for the 7.0 branch.

@agocke release/7.0 is already using the stable 7.0.100 SDK, it was bumped as part of https://github.com/dotnet/runtime/pull/78107. For some reason we didn't hit the F# linker issue there though.

**Pull request merged**
