### PR TITLE
Increase multiple HTTP/2 connections test timeouts again

### LINKED ISSUE #40115: Http2_MultipleConnectionsEnabled_IdleConnectionTimeoutExpired_ConnectionRemovedAndNewCreated  test failure
```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_IdleConnectionTimeoutExpired_ConnectionRemovedAndNewCreated [FAIL]
      Assert.Equal() Failure
      Expected: 2
      Actual:   1
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs(2176,0): at System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_IdleConnectionTimeoutExpired_ConnectionRemovedAndNewCreated()
        --- End of stack trace from previous location ---
```
Failed in #40053 on net5.0-Linux-Debug-x64-CoreCLR_release-Debian.9.Amd64.Open

Log: https://github.com/dotnet/runtime/pull/40053/checks?check_run_id=925107221

### LINKED ISSUE #40436: Flaky test: Http2_MultipleConnectionsEnabled_ConnectionLimitNotReached_ConcurrentRequestsSuccessfullyHandled
Test _Http2_MultipleConnectionsEnabled_ConnectionLimitNotReached_ConcurrentRequestsSuccessfullyHandled_ appears to be flaky. Occasionally timing out and causing CI failures.

See:
https://github.com/dotnet/runtime/pull/36252/checks?check_run_id=951684309
https://github.com/dotnet/runtime/pull/40426/checks?check_run_id=951565333

```txt
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_ConnectionLimitNotReached_ConcurrentRequestsSuccessfullyHandled [FAIL]
      System.TimeoutException : Task timed out after 00:01:00
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(41,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs(2213,0): at System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.PrepareConnection(Http2LoopbackServer server, HttpClient client, UInt32 maxConcurrentStreams, Int32 readTimeout, Int32 expectedWarpUpTasks)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs(2008,0): at System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_ConnectionLimitNotReached_ConcurrentRequestsSuccessfullyHandled()
        --- End of stack trace from previous location ---
  Finished:    System.Net.Http.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Http.Functional.Tests  Total: 2085, Errors: 0, Failed: 1, Skipped: 14, Time: 131.149s
```

### PR DESCRIPTION
**Pull request by alnikola**
Fixes #40115
Fixes #40436

### CODE REVIEW

**Review by geoffkizer — APPROVED** [review]

**Comment by stephentoub** [comment]
Do we know that these are just sometimes taking slightly longer, rather than them outright hanging such that no amount of additional time will be helpful?

**Comment by alnikola** [comment]
No evidence of this being a real hang has been found so far, but it is still possible. If it keeps reappearing after this increase, I will try investigating it further.

**Comment by alnikola** [comment]
Open / close to trigger CI.

**Comment by alnikola** [comment]
Open / close to trigger CI.

**Comment by alnikola** [comment]
Ok, it seems it doesn't work this way.

**Pull request merged**
