### PR TITLE
Fix corerun binplacing in testhost

### LINKED ISSUE #40215: CoreRun and hostpolicy are not in bin/testhost
I think this is related to recent changes in the infrastructure to make testhost more closely aligned to the shipping product. 

1. Running the performance benchmarks needs CoreRun to be in the `testhost` (though this can be fixed in the perf repo I'm guessing) folder. 

2. Sometimes I also run into `A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'D:\repos\runtime\artifacts\bin\testhost\net5.0-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\5.0.0'` though I'm not certain if this is something messed up in my environment. 

For both these issues, copying the dlls from elsewhere into testhost works, so this is not a pressing issue.

cc @ViktorHofer @safern

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/runtime/issues/40215

### CODE REVIEW

**Review by agocke — APPROVED** [review]
LGTM

**Comment by am11** [comment]
It was also missing the hostpolicy, for which we have a property `HostPolicyFileName` defined, but it is unused. Looks like after line 48, we need:

```xml
    <Copy SourceFiles="@(HostPolicyFileName)"
          DestinationFolder="$(TestHostRootPath)shared\Microsoft.NETCore.App\$(ProductVersion)"
          SkipUnchangedFiles="true"
          UseHardlinksIfPossible="$(UseHardlink)" />
```

**Comment by ViktorHofer** [comment]
I believe that's dead code. The hostpolicy is binplaced as part of the `.depproj` build. That must be a different issue...

**Review by safern — APPROVED** [review]

**Comment by am11** [comment]
#40215's title has it: CoreRun *and hostpolic*y are not in bin/testhost :)
(context:  we were also hitting the missing libhostpolicy.dylib on macOS with jit-diff the other day: https://github.com/dotnet/jitutils/issues/275#issuecomment-663653517)

**Comment by ViktorHofer** [comment]
It's unclear to me what the immediate fix for that would be as I can't repro it locally on Windows :( https://github.com/dotnet/runtime/issues/38034 would definitely fix this but no one had time to start with it yet.

**Review by adamsitnik — APPROVED** [review]
so the problem was the order of copying the files? thanks for fixing this @ViktorHofer !

**Pull request merged**
