### PR TITLE
Regression test for GitHub issue #71319

### LINKED ISSUE #71319: Targets of variant static interface method resolution
For the following program:

```csharp
using System;

interface IFoo<in T>
{
    static virtual void DoStatic() => Console.WriteLine(typeof(IFoo<T>));
}

class Program : IFoo<object>
{
    static void CallStatic<T, U>() where T : IFoo<U> => T.DoStatic();

    static void Main()
    {
        CallStatic<Program, string>();
    }
}
```

My expectation is that we're doing a variant dispatch to `IFoo<object>` implemented on `Program`. But unexpectedly, the program prints ``IFoo`1[System.String]``. Somehow we dispatched to an interface `Program` doesn't implement.

If I modify the program to not use default interface methods, the program prints `object` as expected.

```csharp
using System;

interface IFoo<in T>
{
    static abstract void DoStatic();
}

class Fooer<T> : IFoo<T>
{
    public static void DoStatic() => Console.WriteLine(typeof(T));
}

class Program
{
    static void CallStatic<T, U>() where T : IFoo<U> => T.DoStatic();

    static void Main()
    {
        CallStatic<Fooer<object>, string>();
    }
}
```

Cc @trylek @davidwrighton

### PR DESCRIPTION
**Pull request by trylek**
I have created a regression test to cover the scenario described in the GitHub issue.
In runtime main the test is passing now for me so I don't think there's anything to
investigate right now.

Thanks

Tomas

Fixes: #71319

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Thank you for adding the regression test! Looks like it's asserting the checked legs, so we actually found something interesting!

**Review by MichalStrehovsky — APPROVED** [review]
The test looks good. Maybe we could check it in ActiveIssue'd. Looks like the Mono team also has a bug to look at.

**Comment by trylek** [comment]
Hmm, that is weird, I believe I tested the test locally in debug mode and I didn't see any assertions although this one looks deterministic. I'll take a first look to get more info regarding how we should proceed here. Thanks Michal for reviewing!

**Comment by trylek** [comment]
Considering David is on vacation this week I'm inclined to merge this in before today Preview 7 fork as it fixes an important CoreCLR runtime bug; I'll address any feedback David might have in a follow-up change once he's back. Assuming there's no pushback I'll merge this in after 2PM today.

**Pull request merged**
