### PR TITLE
Use pattern value in the summary for the generated regex method.

### LINKED ISSUE #94760: Escaped pattern in the summary of GeneratedRegex
See #88175, the screenshot was showing `\.` for the IP address regex, which is expected.

screenshot

But somehow I don't see the same behavior in VS17.8?

image

### PR DESCRIPTION
**Pull request by pawchen**
Fixes #94760

### CODE REVIEW

**Comment by pawchen** [comment]
OK, so we're failing the tests with special chars that are not valid XML chars in the pattern, such as 0x00 and 0xFFFF. I think we should use the Regex escape syntax (`\u`nnnn) for those, which happens to be the same C# string escape syntax that was handled by `Literal(..)`.

**Comment by pawchen** [comment]
The current logic is not quite correct for `RegexOptions.IgnorePatternWhitespace`, please don't merge yet.

**Comment by pawchen** [comment]
Wrong direction. As the `IgnorePatternWhitespace` option can be inlined and being on and off through the pattern. Closing.

**Comment by stephentoub** [comment]
Thanks, anyway, for your efforts.

**Pull request closed without merging**
