### PR TITLE
JIT: Optimize redundant memory barriers on arm/arm64

### LINKED ISSUE #60021: [JIT][arm64] recognize Interlocked.Increment in volatile increment
```csharp
volatile int a;

void Test() => a++;
```
Currently emits:
```asm
; Method Program:Test():this
G_M27469_IG01:              ;; offset=0000H
        A9BF7BFD          stp     fp, lr, [sp,#-16]!
        910003FD          mov     fp, sp
						;; bbWeight=1    PerfScore 1.50

G_M27469_IG02:              ;; offset=0008H
        B9400801          ldr     w1, [x0,#8]
        D50339BF          dmb     ishld
        52800022          mov     w2, #1
        0B020021          add     w1, w1, w2
        D5033BBF          dmb     ish
        B9000801          str     w1, [x0,#8]
						;; bbWeight=1    PerfScore 25.00

G_M27469_IG03:              ;; offset=0020H
        A8C17BFD          ldp     fp, lr, [sp],#16
        D65F03C0          ret     lr
						;; bbWeight=1    PerfScore 2.00
; Total bytes of code: 40
```
I guess we can use armv8.1 LDADDAL (acquire and release) here? to get:
```asm
; Method Program:Test2():this
G_M27469_IG01:              ;; offset=0000H
        A9BF7BFD          stp     fp, lr, [sp,#-16]!
        910003FD          mov     fp, sp
						;; bbWeight=1    PerfScore 1.50

G_M27469_IG02:              ;; offset=0008H
        B940001F          ldr     wzr, [x0]
        D2800101          mov     x1, #8
        8B010000          add     x0, x0, x1
        52800021          mov     w1, #1
        B8E10000          ldaddal w1, w0, [x0]
						;; bbWeight=1    PerfScore 7.50

G_M27469_IG03:              ;; offset=001CH
        A8C17BFD          ldp     fp, lr, [sp],#16
        D65F03C0          ret     lr
						;; bbWeight=1    PerfScore 2.00
; Total bytes of code: 36
```
Basically replace
```
[000006] -A-XGO------              *  ASG       int   
[000005] V--XGO-N----              +--*  FIELD     int    a
[000000] ------------              |  \--*  LCL_VAR   ref    V00 this         
[000004] ---XGO------              \--*  ADD       int   
[000002] V--XGO-N----                 +--*  FIELD     int    a
[000001] ------------                 |  \--*  LCL_VAR   ref    V00 this         
[000003] ------------                 \--*  CNS_INT   int    1
```
with `GT_XADD(GT_FIELD)`

am I correct? @dotnet/jit-contrib

### LINKED ISSUE #60023: [JIT][arm64] double dmb
```csharp
public class Program
{
    volatile int a;

    void Test2(Program p) => p.a = a;
}
```
currently emits:
```asm
; Method Program:Test2(Program):this
G_M27705_IG01:              ;; offset=0000H
        A9BF7BFD          stp     fp, lr, [sp,#-16]!
        910003FD          mov     fp, sp
						;; bbWeight=1    PerfScore 1.50

G_M27705_IG02:              ;; offset=0008H
        B9400800          ldr     w0, [x0,#8]
        D50339BF          dmb     ishld
        D5033BBF          dmb     ish
        B9000820          str     w0, [x1,#8]
						;; bbWeight=1    PerfScore 24.00

G_M27705_IG03:              ;; offset=0018H
        A8C17BFD          ldp     fp, lr, [sp],#16
        D65F03C0          ret     lr
						;; bbWeight=1    PerfScore 2.00
; Total bytes of code: 32
```
I guess the 2nd dmb is redundant here (not even mentioning that both of them actually redundant here?)

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/60023
Fixes https://github.com/dotnet/runtime/issues/60021

This PR removes redundant load-only or full memory barriers if we already emitted one in current IG and there were no memory accesses after it. By "memory accesses" I mean all instructions in this table [instrsarm64.h](https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/instrsarm64.h) (and [instrsarm.h](https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/instrsarm.h) for arm32) with "ST" or "LD" in the 3rd column.

Examples:
```csharp
class Prog
{
    volatile int a;

    void Test1(Prog p) => p.a = a;

    void Test2() => a++;
}
```
Codegen diff
```diff

; Method Prog:Test1(Prog):this
G_M46938_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
G_M46938_IG02:
            ldr     w0, [x0,#8]
-           dmb     ishld
            dmb     ish
            str     w0, [x1,#8]
G_M46938_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
-; Total bytes of code: 32
+; Total bytes of code: 28


; Method Prog:Test2():this
G_M48563_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
G_M48563_IG02:
            ldr     w1, [x0,#8]
-           dmb     ishld
+           dmb     ish
            add     w1, w1, #1
-           dmb     ish
            str     w1, [x0,#8]
G_M48563_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
-; Total bytes of code: 36
+; Total bytes of code: 32
```

Diffs (aljit):
## coreclr_tests.pmi.Linux.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 166112668 (overridden on cmd)
Total bytes of diff: 166112628 (overridden on cmd)
Total bytes of delta: -40 (-0.00 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -24 : 88442.dasm (-6.12% of base)
          -8 : 252713.dasm (-1.10% of base)
          -8 : 236119.dasm (-5.13% of base)

3 total files with Code Size differences (3 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -24 (-6.12% of base) : 88442.dasm - stfldstatic2:Main():int
          -8 (-1.10% of base) : 252713.dasm - CCSE:Main():int
          -8 (-5.13% of base) : 236119.dasm - ScenarioMonitor:ScenarioShouldContinueRunning():bool:this

Top method improvements (percentages):
         -24 (-6.12% of base) : 88442.dasm - stfldstatic2:Main():int
          -8 (-5.13% of base) : 236119.dasm - ScenarioMonitor:ScenarioShouldContinueRunning():bool:this
          -8 (-1.10% of base) : 252713.dasm - CCSE:Main():int

3 total methods with Code Size differences (3 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.crossgen2.Linux.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 48198936 (overridden on cmd)
Total bytes of diff: 48198692 (overridden on cmd)
Total bytes of delta: -244 (-0.00 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -12 : 169237.dasm (-3.80% of base)
         -12 : 207967.dasm (-1.10% of base)
         -12 : 22180.dasm (-0.75% of base)
          -8 : 31114.dasm (-0.91% of base)
          -8 : 30586.dasm (-3.03% of base)
          -8 : 31115.dasm (-1.92% of base)
          -4 : 195940.dasm (-1.23% of base)
          -4 : 30540.dasm (-1.49% of base)
          -4 : 31145.dasm (-0.99% of base)
          -4 : 661.dasm (-0.20% of base)
          -4 : 14686.dasm (-3.70% of base)
          -4 : 30338.dasm (-0.84% of base)
          -4 : 42184.dasm (-1.79% of base)
          -4 : 201007.dasm (-0.19% of base)
          -4 : 22200.dasm (-1.49% of base)
          -4 : 30624.dasm (-1.10% of base)
          -4 : 42802.dasm (-0.68% of base)
          -4 : 22187.dasm (-11.11% of base)
          -4 : 30565.dasm (-2.27% of base)
          -4 : 31148.dasm (-0.68% of base)

52 total files with Code Size differences (52 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -12 (-3.80% of base) : 169237.dasm - Microsoft.Win32.RegistryKey:.ctor(Microsoft.Win32.SafeHandles.SafeRegistryHandle,bool,bool,bool,bool,int):this
         -12 (-0.75% of base) : 22180.dasm - System.Collections.Hashtable:Insert(System.Object,System.Object,bool):this
         -12 (-1.10% of base) : 207967.dasm - WorkStealingQueue:LocalPush(System.__Canon,byref):this
          -8 (-3.03% of base) : 30586.dasm - System.Threading.Tasks.Task:Dispose(bool):this
          -8 (-0.91% of base) : 31114.dasm - WorkStealingQueue:LocalFindAndPop(System.Object):bool:this
          -8 (-1.92% of base) : 31115.dasm - WorkStealingQueue:LocalPush_HandleTailOverflow():int:this
          -4 (-0.68% of base) : 42802.dasm - IdManager:GetId(bool):int:this
          -4 (-0.68% of base) : 31148.dasm - IdManager:GetId(bool):int:this
          -4 (-0.99% of base) : 31145.dasm - IdManager:ReturnId(int,bool):this
          -4 (-0.99% of base) : 42803.dasm - IdManager:ReturnId(int,bool):this
          -4 (-1.23% of base) : 195940.dasm - Microsoft.Extensions.Logging.LoggerFactory:Dispose():this
          -4 (-4.76% of base) : 207766.dasm - StaticIndexRangePartition`1:MoveNext():bool:this
          -4 (-1.41% of base) : 22201.dasm - System.Collections.Hashtable:Clear():this
          -4 (-1.49% of base) : 22200.dasm - System.Collections.Hashtable:Clone():System.Object:this
          -4 (-1.05% of base) : 22186.dasm - System.Collections.Hashtable:rehash(int):this
          -4 (-0.55% of base) : 22178.dasm - System.Collections.Hashtable:Remove(System.Object):this
          -4 (-11.11% of base) : 22187.dasm - System.Collections.Hashtable:UpdateVersion():this
          -4 (-1.43% of base) : 786.dasm - System.ComponentModel.Composition.Hosting.ApplicationCatalog:Dispose(bool):this
          -4 (-0.20% of base) : 661.dasm - System.ComponentModel.Composition.Hosting.ComposablePartExportProvider:Compose(System.ComponentModel.Composition.Hosting.CompositionBatch):this
          -4 (-0.63% of base) : 487.dasm - System.ComponentModel.Composition.Hosting.FilteredCatalog:Dispose(bool):this

Top method improvements (percentages):
          -4 (-11.11% of base) : 22187.dasm - System.Collections.Hashtable:UpdateVersion():this
          -4 (-4.76% of base) : 207766.dasm - StaticIndexRangePartition`1:MoveNext():bool:this
         -12 (-3.80% of base) : 169237.dasm - Microsoft.Win32.RegistryKey:.ctor(Microsoft.Win32.SafeHandles.SafeRegistryHandle,bool,bool,bool,bool,int):this
          -4 (-3.70% of base) : 14686.dasm - System.Net.Http.HttpClientHandler:Dispose(bool):this
          -4 (-3.57% of base) : 14813.dasm - System.Net.Http.DelegatingHandler:Dispose(bool):this
          -4 (-3.23% of base) : 14543.dasm - System.Net.Http.HttpMessageInvoker:Dispose(bool):this
          -4 (-3.23% of base) : 163790.dasm - System.Threading.Tasks.Dataflow.ActionBlock`1:Complete():this
          -8 (-3.03% of base) : 30586.dasm - System.Threading.Tasks.Task:Dispose(bool):this
          -4 (-2.86% of base) : 30588.dasm - System.Threading.Tasks.Task:set_CapturedContext(System.Threading.ExecutionContext):this
          -4 (-2.56% of base) : 30577.dasm - System.Threading.Tasks.Task:UpdateExceptionObservedStatus():this
          -4 (-2.27% of base) : 31372.dasm - System.Threading.ManualResetEventSlim:set_SpinCount(int):this
          -4 (-2.27% of base) : 30565.dasm - System.Threading.Tasks.Task:ExecuteEntryUnsafe(System.Threading.Thread):this
          -4 (-2.13% of base) : 30536.dasm - System.Threading.Tasks.Task:SetCancellationAcknowledged():this
          -8 (-1.92% of base) : 31115.dasm - WorkStealingQueue:LocalPush_HandleTailOverflow():int:this
          -4 (-1.85% of base) : 30623.dasm - System.Threading.Tasks.Task:AddNewChild():this
          -4 (-1.79% of base) : 14710.dasm - System.Net.Http.HttpClient:Dispose(bool):this
          -4 (-1.79% of base) : 42184.dasm - System.Threading.Tasks.Task`1:DangerousSetResult(System.Threading.Tasks.VoidTaskResult):this
          -4 (-1.72% of base) : 31505.dasm - System.Threading.CancellationTokenSource:Dispose(bool):this
          -4 (-1.69% of base) : 41930.dasm - System.Threading.Tasks.Task`1:DangerousSetResult(bool):this
          -4 (-1.69% of base) : 42228.dasm - System.Threading.Tasks.Task`1:DangerousSetResult(int):this

52 total methods with Code Size differences (52 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.pmi.Linux.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 47235868 (overridden on cmd)
Total bytes of diff: 47235624 (overridden on cmd)
Total bytes of delta: -244 (-0.00 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -12 : 196881.dasm (-1.14% of base)
         -12 : 196872.dasm (-1.15% of base)
         -12 : 196880.dasm (-1.14% of base)
         -12 : 196863.dasm (-1.18% of base)
         -12 : 196884.dasm (-1.14% of base)
         -12 : 196882.dasm (-1.13% of base)
         -12 : 220988.dasm (-5.66% of base)
         -12 : 196883.dasm (-1.13% of base)
          -8 : 35858.dasm (-0.47% of base)
          -8 : 153848.dasm (-3.92% of base)
          -8 : 198764.dasm (-1.28% of base)
          -4 : 167270.dasm (-1.61% of base)
          -4 : 199232.dasm (-2.22% of base)
          -4 : 30213.dasm (-1.89% of base)
          -4 : 171945.dasm (-4.00% of base)
          -4 : 199225.dasm (-0.23% of base)
          -4 : 171961.dasm (-4.00% of base)
          -4 : 215812.dasm (-1.01% of base)
          -4 : 173316.dasm (-0.52% of base)
          -4 : 199094.dasm (-1.33% of base)

42 total files with Code Size differences (42 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -12 (-5.66% of base) : 220988.dasm - Microsoft.Win32.RegistryKey:.ctor(Microsoft.Win32.SafeHandles.SafeRegistryHandle,bool,bool,bool,bool,int):this
         -12 (-1.18% of base) : 196863.dasm - WorkStealingQueue[__Canon][System.__Canon]:LocalPush(System.__Canon,byref):this
         -12 (-1.15% of base) : 196872.dasm - WorkStealingQueue[Byte][System.Byte]:LocalPush(ubyte,byref):this
         -12 (-1.13% of base) : 196882.dasm - WorkStealingQueue[Double][System.Double]:LocalPush(double,byref):this
         -12 (-1.14% of base) : 196880.dasm - WorkStealingQueue[Int16][System.Int16]:LocalPush(short,byref):this
         -12 (-1.14% of base) : 196881.dasm - WorkStealingQueue[Int32][System.Int32]:LocalPush(int,byref):this
         -12 (-1.14% of base) : 196884.dasm - WorkStealingQueue[Int64][System.Int64]:LocalPush(long,byref):this
         -12 (-1.13% of base) : 196883.dasm - WorkStealingQueue[Vector`1][System.Numerics.Vector`1[System.Single]]:LocalPush(System.Numerics.Vector`1[Single],byref):this
          -8 (-0.47% of base) : 35858.dasm - Microsoft.Diagnostics.Symbols.SourceFile:GetSourceFromSrcServer():System.String:this
          -8 (-1.28% of base) : 198764.dasm - System.ComponentModel.Composition.ReflectionModel.ExportingMember:GetExportedValue(System.Object,System.Object):System.Object:this
          -8 (-3.92% of base) : 153848.dasm - System.Net.Http.HttpClient:Dispose(bool):this
          -4 (-0.88% of base) : 30147.dasm - IdManager[Byte][System.Byte]:GetId(bool):int:this
          -4 (-1.22% of base) : 30150.dasm - IdManager[Byte][System.Byte]:ReturnId(int,bool):this
          -4 (-1.01% of base) : 215812.dasm - Microsoft.Extensions.Logging.LoggerFactory:Dispose():this
          -4 (-3.12% of base) : 220987.dasm - Microsoft.Win32.RegistryKey:.ctor(Microsoft.Win32.SafeHandles.SafeRegistryHandle,bool,int):this
          -4 (-1.89% of base) : 220931.dasm - Microsoft.Win32.RegistryKey:FromHandle(Microsoft.Win32.SafeHandles.SafeRegistryHandle,int):Microsoft.Win32.RegistryKey
          -4 (-4.76% of base) : 197474.dasm - StaticIndexRangePartition`1[__Canon][System.__Canon]:MoveNext():bool:this
          -4 (-4.76% of base) : 197477.dasm - StaticIndexRangePartition`1[Byte][System.Byte]:MoveNext():bool:this
          -4 (-1.33% of base) : 199094.dasm - System.ComponentModel.Composition.Hosting.ApplicationCatalog:Dispose(bool):this
          -4 (-2.22% of base) : 199181.dasm - System.ComponentModel.Composition.Hosting.CatalogExportProvider:EnsureRunning():this

Top method improvements (percentages):
         -12 (-5.66% of base) : 220988.dasm - Microsoft.Win32.RegistryKey:.ctor(Microsoft.Win32.SafeHandles.SafeRegistryHandle,bool,bool,bool,bool,int):this
          -4 (-4.76% of base) : 197474.dasm - StaticIndexRangePartition`1[__Canon][System.__Canon]:MoveNext():bool:this
          -4 (-4.76% of base) : 197477.dasm - StaticIndexRangePartition`1[Byte][System.Byte]:MoveNext():bool:this
          -4 (-4.17% of base) : 153798.dasm - System.Net.Http.DelegatingHandler:Dispose(bool):this
          -4 (-4.00% of base) : 171945.dasm - System.Threading.Tasks.Dataflow.ActionBlock`1[__Canon][System.__Canon]:Complete():this
          -4 (-4.00% of base) : 171961.dasm - System.Threading.Tasks.Dataflow.ActionBlock`1[Byte][System.Byte]:Complete():this
          -8 (-3.92% of base) : 153848.dasm - System.Net.Http.HttpClient:Dispose(bool):this
          -4 (-3.70% of base) : 154080.dasm - System.Net.Http.HttpMessageInvoker:Dispose(bool):this
          -4 (-3.57% of base) : 153948.dasm - System.Net.Http.HttpClientHandler:Dispose(bool):this
          -4 (-3.33% of base) : 154716.dasm - System.Net.Http.Http2Connection:ProcessPingAck(long):this
          -4 (-3.12% of base) : 220987.dasm - Microsoft.Win32.RegistryKey:.ctor(Microsoft.Win32.SafeHandles.SafeRegistryHandle,bool,int):this
          -4 (-2.22% of base) : 199181.dasm - System.ComponentModel.Composition.Hosting.CatalogExportProvider:EnsureRunning():this
          -4 (-2.22% of base) : 199232.dasm - System.ComponentModel.Composition.Hosting.ComposablePartExportProvider:EnsureRunning():this
          -4 (-2.08% of base) : 171946.dasm - System.Threading.Tasks.Dataflow.ActionBlock`1[__Canon][System.__Canon]:System.Threading.Tasks.Dataflow.IDataflowBlock.Fault(System.Exception):this
          -4 (-2.08% of base) : 171962.dasm - System.Threading.Tasks.Dataflow.ActionBlock`1[Byte][System.Byte]:System.Threading.Tasks.Dataflow.IDataflowBlock.Fault(System.Exception):this
          -4 (-2.00% of base) : 30253.dasm - System.Threading.Tasks.Task`1[Double][System.Double]:DangerousSetResult(double):this
          -4 (-1.89% of base) : 220931.dasm - Microsoft.Win32.RegistryKey:FromHandle(Microsoft.Win32.SafeHandles.SafeRegistryHandle,int):Microsoft.Win32.RegistryKey
          -4 (-1.89% of base) : 30213.dasm - System.Threading.Tasks.Task`1[Byte][System.Byte]:DangerousSetResult(ubyte):this
          -4 (-1.89% of base) : 30246.dasm - System.Threading.Tasks.Task`1[Int16][System.Int16]:DangerousSetResult(short):this
          -4 (-1.61% of base) : 167252.dasm - System.Linq.Parallel.AsynchronousChannel`1[__Canon][System.__Canon]:EnqueueChunk(System.__Canon[]):this

42 total methods with Code Size differences (42 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries_tests.pmi.Linux.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 112411060 (overridden on cmd)
Total bytes of diff: 112410808 (overridden on cmd)
Total bytes of delta: -252 (-0.00 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
          -8 : 115030.dasm (-0.47% of base)
          -8 : 218162.dasm (-3.92% of base)
          -8 : 273881.dasm (-2.74% of base)
          -8 : 87601.dasm (-2.02% of base)
          -8 : 87562.dasm (-1.69% of base)
          -8 : 90484.dasm (-0.95% of base)
          -8 : 253194.dasm (-0.94% of base)
          -8 : 87552.dasm (-0.87% of base)
          -8 : 120219.dasm (-1.03% of base)
          -8 : 196277.dasm (-1.07% of base)
          -8 : 87561.dasm (-1.44% of base)
          -8 : 115444.dasm (-0.34% of base)
          -8 : 242383.dasm (-1.10% of base)
          -4 : 115035.dasm (-0.27% of base)
          -4 : 115070.dasm (-0.39% of base)
          -4 : 147545.dasm (-0.25% of base)
          -4 : 323862.dasm (-0.08% of base)
          -4 : 115081.dasm (-0.22% of base)
          -4 : 115227.dasm (-0.49% of base)
          -4 : 196132.dasm (-0.10% of base)

50 total files with Code Size differences (50 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
          -8 (-0.95% of base) : 90484.dasm - <SendAsync_NullRequest_ThrowsException>d__2:MoveNext():this
          -8 (-0.34% of base) : 115444.dasm - <TestLinkTo_MaxMessages>d__24:MoveNext():this
          -8 (-0.47% of base) : 115030.dasm - <TestSchedulerUsage>d__6:MoveNext():this
          -8 (-2.74% of base) : 273881.dasm - Microsoft.AspNetCore.Http.Features.FeatureCollection:set_Item(System.Type,System.Object):this
          -8 (-1.07% of base) : 196277.dasm - System.Data.SqlClient.TdsParserStateObject:SNIWritePacket(System.Data.SqlClient.PacketHandle,byref,bool,bool):System.Threading.Tasks.Task:this
          -8 (-1.10% of base) : 242383.dasm - System.Data.SqlClient.TdsParserStateObject:SNIWritePacket(System.Data.SqlClient.PacketHandle,byref,bool,bool):System.Threading.Tasks.Task:this
          -8 (-2.02% of base) : 87601.dasm - System.Net.Http.Functional.Tests.CustomHttpClientTest:Send_NullRequest_ThrowsException():this
          -8 (-1.44% of base) : 87561.dasm - System.Net.Http.Functional.Tests.HttpClientTest:DefaultRequestVersion_InitialValueExpected():this
          -8 (-1.69% of base) : 87562.dasm - System.Net.Http.Functional.Tests.HttpClientTest:DefaultRequestVersion_Roundtrips():this
          -8 (-0.87% of base) : 87552.dasm - System.Net.Http.Functional.Tests.HttpClientTest:Send_SingleThread_Succeeds(int):this
          -8 (-3.92% of base) : 218162.dasm - System.Net.Http.HttpClient:Dispose(bool):this
          -8 (-0.94% of base) : 253194.dasm - System.Net.Http.Json.Functional.Tests.JsonContentTestsBase:JsonContentThrowsOnIncompatibleTypeAsync():this
          -8 (-1.03% of base) : 120219.dasm - System.Net.Tests.HttpListenerTests:EndGetContext_AlreadyCalled_ThrowsInvalidOperationException():this
          -4 (-0.34% of base) : 250616.dasm - <>c:<HttpClient_ValidAuthentication_Success>b__1_0(System.String,System.String,System.String):this
          -4 (-0.99% of base) : 115752.dasm - <>c__DisplayClass0_0:<TestEtw>b__10():this
          -4 (-3.45% of base) : 115439.dasm - <>c__DisplayClass23_0:<TestLinkTo_Predicate>b__2(System.Threading.Tasks.Task):this
          -4 (-3.45% of base) : 115837.dasm - <>c__DisplayClass6_0:<WriteOnceToAction>b__3(System.Threading.Tasks.Task):this
          -4 (-0.08% of base) : 323862.dasm - <TestAsyncOutputStream_BeginCancelBeginOutputRead>d__7:MoveNext():this
          -4 (-0.15% of base) : 115026.dasm - <TestBasicMessageProcessing>d__5:MoveNext():this
          -4 (-0.27% of base) : 115035.dasm - <TestInputCount>d__7:MoveNext():this

Top method improvements (percentages):
          -4 (-4.17% of base) : 218131.dasm - System.Net.Http.DelegatingHandler:Dispose(bool):this
          -8 (-3.92% of base) : 218162.dasm - System.Net.Http.HttpClient:Dispose(bool):this
          -4 (-3.70% of base) : 88846.dasm - MockHandler:Dispose(bool):this
          -4 (-3.70% of base) : 218299.dasm - System.Net.Http.HttpMessageInvoker:Dispose(bool):this
          -4 (-3.45% of base) : 115439.dasm - <>c__DisplayClass23_0:<TestLinkTo_Predicate>b__2(System.Threading.Tasks.Task):this
          -4 (-3.45% of base) : 115837.dasm - <>c__DisplayClass6_0:<WriteOnceToAction>b__3(System.Threading.Tasks.Task):this
          -8 (-2.74% of base) : 273881.dasm - Microsoft.AspNetCore.Http.Features.FeatureCollection:set_Item(System.Type,System.Object):this
          -8 (-2.02% of base) : 87601.dasm - System.Net.Http.Functional.Tests.CustomHttpClientTest:Send_NullRequest_ThrowsException():this
          -8 (-1.69% of base) : 87562.dasm - System.Net.Http.Functional.Tests.HttpClientTest:DefaultRequestVersion_Roundtrips():this
          -4 (-1.64% of base) : 307097.dasm - System.ComponentModel.DataAnnotations.Tests.ValidationAttributeTests:TestNoThrowIfOverrideIsValid01()
          -4 (-1.54% of base) : 279329.dasm - System.Threading.Tasks.Tests.UserActionEnumerator`1[__Canon][System.__Canon]:MoveNext():bool:this
          -4 (-1.54% of base) : 279336.dasm - System.Threading.Tasks.Tests.UserActionEnumerator`1[Byte][System.Byte]:MoveNext():bool:this
          -8 (-1.44% of base) : 87561.dasm - System.Net.Http.Functional.Tests.HttpClientTest:DefaultRequestVersion_InitialValueExpected():this
          -4 (-1.41% of base) : 87769.dasm - System.Net.Http.Functional.Tests.MessageProcessingHandlerTest:Ctor_CreateDispose_Success():this
          -4 (-1.23% of base) : 87770.dasm - System.Net.Http.Functional.Tests.MessageProcessingHandlerTest:Ctor_CreateWithHandlerDispose_Success():this
          -8 (-1.10% of base) : 242383.dasm - System.Data.SqlClient.TdsParserStateObject:SNIWritePacket(System.Data.SqlClient.PacketHandle,byref,bool,bool):System.Threading.Tasks.Task:this
          -8 (-1.07% of base) : 196277.dasm - System.Data.SqlClient.TdsParserStateObject:SNIWritePacket(System.Data.SqlClient.PacketHandle,byref,bool,bool):System.Threading.Tasks.Task:this
          -8 (-1.03% of base) : 120219.dasm - System.Net.Tests.HttpListenerTests:EndGetContext_AlreadyCalled_ThrowsInvalidOperationException():this
          -4 (-0.99% of base) : 115752.dasm - <>c__DisplayClass0_0:<TestEtw>b__10():this
          -8 (-0.95% of base) : 90484.dasm - <SendAsync_NullRequest_ThrowsException>d__2:MoveNext():this

50 total methods with Code Size differences (50 improved, 0 regressed), 0 unchanged.

```

</details>

--------------------------------------------------------------------------------

### CODE REVIEW

**Comment by EgorBo** [comment]
PTAL @dotnet/jit-contrib

**Comment by EgorBo** [comment]
Unrelated: the cost of memory ordering (TSO vs arm) 🙂:
image

**Review by jakobbotsch — APPROVED** [review]
LGTM, but may want to get another review.

**Comment by EgorBo** [comment]
cc @echesakovMSFT

**Comment by echesakovMSFT** [comment]
@EgorBo In a case when a volatile write followed by a volatile read (it is an inversion of your example) - we will still insert a barrier before the write and after the read to guarantee their release/acquire semantics. Is this correct interpretation of the change?

**Review by echesakov — APPROVED** [review]
LGTM

**Pull request merged**
