### PR TITLE
Try to work around random CI failures in "dotnet restore" of benchmarks

### PR DESCRIPTION
**Pull request by BruceForstall**
Set the "retry" environment variable described in
https://github.com/NuGet/NuGet.Client/pull/4259.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@kunalspathak PTAL
cc @dotnet/jit-contrib @DrewScoggins

**Review by kunalspathak — APPROVED** [review]
LGTM. @DrewScoggins - in case you are not aware.

**Comment by BruceForstall** [comment]
I'll kick off a collection to test this after https://github.com/dotnet/runtime/pull/66110 is merged (and everything mirrors)

**Comment by BruceForstall** [comment]
Unfortunately, it looks like this didn't help. The collection failed for many other infra-related reasons, though, as well.

Maybe I should up the retry count and wait-between-retry times.

**Pull request merged**
