### PR TITLE
Fix `DataContractJsonSerializer`'s handling of -0.0

### LINKED ISSUE #69019: `System.Runtime.Serialization`'s `DataContractJsonSerializer.ReadObject` loses the sign when reading "-0" as a double
### Description

`System.Runtime.Serialization.Json.DataContractJsonSerializer` round trips `double`s as follows:

| double originalValue      | string serializedValue | double deserializedValue  | 
|---------------------------|------------------------|---------------------------|
| `double.NaN`              | `"NaN"`                | `double.NaN`              |
| `double.PositiveInfinity` | `"INF"`                | `double.PositiveInfinity` |
| `double.NegativeInfinity` | `"-INF"`               | `double.NegativeInfinity` |
| `0.0`                     | `"0"`                  | `0.0`                     |
| `-0.0`                    | `"-0"`                 | `0.0` (wrong!)            |

The sign of `-0` is lost upon deserialization as a `double`. The same applies to `float`s.

This bug is the cause of https://github.com/microsoft/testfx/issues/1096, which remains unfixed.

### Reproduction Steps

```cs
double originalValue = -0.0;
string expectedSerialization = "-0";

DataContractJsonSerializer dataContractJsonSerializer = new(typeof(double));

// Serialize `originalValue`.
MemoryStream memoryStream = new();
dataContractJsonSerializer.WriteObject(memoryStream, originalValue);
string serializedValue = Encoding.UTF8.GetString(memoryStream.ToArray());
Assert.AreEqual(expectedSerialization, serializedValue);

// Now deserialize it.
memoryStream.Seek(0, SeekOrigin.Begin);
object? obj = dataContractJsonSerializer.ReadObject(memoryStream);

if (obj is double deserializedValue)
{
    Assert.AreEqual(originalValue, deserializedValue);
    // Now check the sign.
    // This assertion fails.
    Assert.AreEqual(1.0 / originalValue, 1.0 / deserializedValue, $"Deserialization of {serializedValue} had wrong sign.");
}
```

### Expected behavior

The negative sign of the double is preserved.

### Actual behavior

The negative sign is lost.

### Regression?

Unlikely

### Known Workarounds

_No response_

### Configuration

.NET 6

### Other information

`System.Private.DataContractSerialization`'s `System.Xml.XmlConverter.TryParse{Single,Double}` is the source of the bug:
https://github.com/dotnet/runtime/blob/722d55040a63de27430a500d388a8f6cbbe86734/src/libraries/System.Private.DataContractSerialization/src/System/Xml/XmlConverter.cs#L649-L699

Line 695 ought to be `result = -(double)value;`, since `value` is an `int`.

### PR DESCRIPTION
**Pull request by notcake**
Fixes #69019.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=69020) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=69020) before we can accept your contribution.<br/><br/>:x: notcake [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=69020)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=69020) it.</sub>

**Comment by danmoseley** [comment]
Hi there. Thanks. Did you miss a file?

**Comment by notcake** [comment]
I did, thank you!

**Review by stephentoub — APPROVED** [review]

**Comment by danmoseley** [comment]
@StephenMolloy is this mergeable?

**Comment by StephenMolloy** [comment]
Yeah. I wanted to hold off on DCS-related merges until after the big DCS merge (71752) coming later today. But yes, it is our plan to accpet/mert this PR this weekend.

**Pull request merged**
