### PR TITLE
Do not reference `System.Text.Encoding.CodePages` on frameworks where it is inbox.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**

### CODE REVIEW

**Review by ViktorHofer — CHANGES_REQUESTED** [review]
This behavior is by design, see my comment here: https://github.com/dotnet/runtime/issues/67196#issuecomment-1081657399. We should document this though as we got this wrong multiple times in the past.

**Comment by teo-tsirpanis** [comment]
So should I remove the dependency only when we target .NET 7?

**Comment by ViktorHofer** [comment]
> So should I remove the dependency only when we target .NET 7?

In the example of System.Runtime.CompilerServices.Unsafe, as the library doesn't produce a package anymore starting with net7.0, we don't use a package reference anymore for net7.0 but for older tfms.

In this case, `System.Text.Encoding.CodePages` still produces a packages in main, hence we always want to reference the package, even if the library is exposed in the microsoft.netcore.app.ref targeting pack.

In general, anything that ships out of band (via a package) of course depends on the microsoft.netcore.app.ref targeting pack and on top of that, on dependent libraries' packages.

**Comment by stephentoub** [comment]
@ViktorHofer, what are the next steps here?  Should this just be closed?  A doc update instead?

**Comment by ViktorHofer** [comment]
Let's close the PR for now and I will send a PR to update the docs.

**Pull request closed without merging**
