### PR TITLE
[Mono] Disabled failing tests on Mono Android and interpreter lanes to keep CI green

### PR DESCRIPTION
**Pull request by fanyang-mono**
Trying to make `runtime-extra-platforms` greener

### CODE REVIEW

**Comment by SamMonoRT** [comment]
> Trying to make `runtime-extra-platforms` greener

Just to clarify, we have the interpreter lanes running in extra-platforms or just Android emulator ones, and you updated interp lane too.

**Comment by fanyang-mono** [comment]
Yes, I am disabling one test on interpreter lane as well, per @miloszkukla requested. 

`mono monointerpreter Pri0 Runtime Tests Run linux arm64 release` is the interpreter lane runs in extra-platforms.

**Comment by SamMonoRT** [comment]
> Yes, I am disabling one test on interpreter lane as well, per @miloszkukla requested.
> 
> `mono monointerpreter Pri0 Runtime Tests Run linux arm64 release` is the interpreter lane runs in extra-platforms.

you meant @kotlarmilos

**Review by kotlarmilos — APPROVED** [review]
Thanks, I will take a look at the interpreter test.

**Comment by fanyang-mono** [comment]
The tests that this PR intended to disable are not failing on CI anymore.

**Pull request merged**
