### PR TITLE
[release/6.0][mono] Disable DoublinkList/dlstack tests

### PR DESCRIPTION
**Pull request by steveisok**
This test is disabled in main and this change makes its way back to 6.0

Fixes https://github.com/dotnet/runtime/issues/83245

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Review by vargaz — APPROVED** [review]

**Comment by steveisok** [comment]
@lambdageek @vargaz are there more ignores I need to backport?

**Comment by steveisok** [comment]
> @steveisok in case you plan to add more tests to ignore, please ping me when this is ready to merge so I hit the button.

Will do. Given the results I think we may need to backport more.

**Comment by carlossanlop** [comment]
Hmm... I'm curious to see if the bot will be smart enough to know what to backport from a 6.0 branch into a 7.0. Technically, it would be a forward-port.

**Pull request merged**
