### PR TITLE
Arm64: Implement ReverseBitOrder

### PR DESCRIPTION
**Pull request by echesakov**
I am porting Tamar's PR https://github.com/dotnet/coreclr/pull/27856 (see https://github.com/dotnet/coreclr/pull/27856#issuecomment-557469896)

@CarolEidt @tannergooding Can you please sign off on this?

cc @dotnet/jit-contrib

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
cc @TamarChristinaArm @BruceForstall

**Review by CarolEidt — APPROVED** [review]
Thanks for porting this over @echesakovMSFT

**Review by tannergooding — APPROVED** [review]

**Comment by echesakovMSFT** [comment]
Unfortunately, GitHub changes the commit author when squashing and I was under impression that it wouldn't - I wish we had "rebase and merge" option enabled.

**Comment by tannergooding** [comment]
> Unfortunately, GitHub changes the commit author when squashing

Thats strange. It normally changes the author to include both the original author plus the merger...

**Comment by jaredpar** [comment]
> I wish we had "rebase and merge" option enabled

The "rebase and merge" option hurts git bisect when commit depth is greater than one. That is why it's disabled.

**Pull request merged**
