### PR TITLE
[mono][wasm] Link the aot profiler into dotnet.wasm by default in deb…

### PR DESCRIPTION
**Pull request by vargaz**
…ug mode.

Enable it using a define instead of generating code into driver-gen.c.

### CODE REVIEW

**Comment by vargaz** [comment]
This will allow the AOT profiler to be used in debug mode without having to relink the app.

**Comment by marek-safar** [comment]
Looks reasonable to me, @lewing ?

**Review by lewing — COMMENTED** [review]
Looks like we should remove the empty _GenerateDriverGenC target?

**Comment by vargaz** [comment]
We might need it later thats why it wasn't removed.

**Review by lewing — APPROVED** [review]

**Pull request merged**
