### PR TITLE
Arm64 managed vm changes.

### PR DESCRIPTION
**Pull request by sandreenko**

### CODE REVIEW

**Comment by mangod9** [comment]
Hi @sandreenko, are these changes experimental or something we need to merge? Are they required for a specific issue?

**Comment by sandreenko** [comment]
@mangod9 this is managed (crossgen2) mirror of https://github.com/dotnet/runtime/pull/46665 for https://github.com/dotnet/runtime/issues/46456 so we need them.
I am waiting for crossgen2 outerloop job to be clean to test these changes in CI. It was first blocked on https://github.com/dotnet/runtime/issues/47308 and now on https://github.com/dotnet/runtime/issues/48204.

**Comment by mangod9** [comment]
Assume this is still blocked on #48204? Is there any progress on that?

**Pull request closed without merging**
