### PR TITLE
Relax Socket.DualMode exception behavior

### PR DESCRIPTION
**Pull request by antonfirsov**
Currently we are throwing `NotSupportedException` from both the getter and setter if the socket is not IPv6. This might be counter-intuitive to users:
https://developercommunity2.visualstudio.com/t/SocketDualMode-documentation-is-missing/1286040

Quoting @geoffkizer from email discussion:

> We try to avoid throwing from property getters. It can make sense in a few cases, but it’s usually in situations where the object is in a state where the property doesn’t have any real meaning, e.g. disposed or not initialized/started or something like that. This doesn’t seem to be any of those.

Proposing to only throw, if the user tries to set the property to `true` for a non-IPv6 socket.

Pro: the proposed behavior is probably more intuitive.
Con: behavioral change between 5 and 6, we need to make sure to update the docs.

@geoffkizer @scalablecory @stephentoub yea or nay?

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM.
It always annoyed me that the getter throws. 
I don't know if this would be considered breaking change.
The risks & impact is probably low. 

It would be good to reach quorum on this one.

**Comment by geoffkizer** [comment]
I'm in favor of making this change. 

@stephentoub Any opinion here?

**Comment by stephentoub** [comment]
> I'm in favor of making this change.
> @stephentoub Any opinion here?

The getter change seems beneficial.  Given an arbitrary socket, you should be able to ask whether it's dual mode without first asking for its family.

I'm less sold on the setter change; it's not clear to me when you'd be given an arbitrary socket and then want to set its DualMode without knowing more about the socket.  That said, it doesn't seem like a big problem to make the change, just not particularly beneficial.

**Comment by antonfirsov** [comment]
I applied the setter change for better consistency between getter and setter behavior. Code equivalent to `if (!socket.DualMode) socket.DualMode = false` should be a NOP instead of throwing IMO.

I acknowledge that the practical significance for this is low, will revert the setter change if my arguments don't stand in your opinion.

**Comment by scalablecory** [comment]
Getting or setting `DualMode` on a non-IPv6 socket indicates a usage error that I'd prefer throw instead of hiding the error.

Relaxing this for the `get` makes some sense to me; mostly to make the debugging experience better. Relaxing this for set seems wrong, though.

**Comment by antonfirsov** [comment]
It looks like we had a consensus on relaxing the getter. Reverted the setter change.

**Review by scalablecory — APPROVED** [review]
lgtm

**Comment by antonfirsov** [comment]
Outerloop test failures are unrelated.

**Pull request merged**
