### PR TITLE
Flow rid from yml to sendtohelix

### PR DESCRIPTION
**Pull request by ViktorHofer**
Not ideal implementation of being able to access the RID in a yml build job. Opened https://github.com/dotnet/runtime/issues/37650 to replace the "Platform" format with the RID.

### CODE REVIEW

**Comment by safern** [comment]
This should not be necessary. The rid should be available as we set it as PackageRID on Directory.Build.props based on osgroup and arch. Send to helix already knows this information.

Also: #37476 is outdated and haven’t merged with master where the mono jobs are collapsed.

I’ll work with @premun and @directhex to accordingly get the latest changes from master.

**Comment by safern** [comment]
What I’m trying to say is that build-job no longer needs to publish this as we will build tests and publish to helix as part of the same job.

**Comment by ViktorHofer** [comment]
Understood, that makes sense. Thanks

**Comment by ViktorHofer** [comment]
Reopening as we need to flow the rid to sendtohelix.proj for https://github.com/dotnet/runtime/pull/39923.

**Review by akoeplinger — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Failure is https://github.com/dotnet/runtime/pull/42893

**Comment by ViktorHofer** [comment]
All tests are successfully submitted to helix. Merging.

**Review by safern — COMMENTED** [review]
LGTM

**Pull request merged**
