### PR TITLE
Update wasm workload name to `wasm-tools`

### PR DESCRIPTION
**Pull request by lewing**
Change `microsoft-net-sdk-blazorwebassembly-aot` to `wasm-tools`

Every other workload in the file is abstract and probably shouldn't have a short name.

### CODE REVIEW

**Review by danroth27 — APPROVED** [review]
:shipit:

**Comment by lewing** [comment]
redirect is defined here https://github.com/dotnet/designs/blob/main/accepted/2020/workloads/workload-manifest.md#redirects

**Comment by lewing** [comment]
@joeloff throwing another feature into the mix

**Comment by lewing** [comment]
@mhutch looks like https://github.com/dotnet/sdk/pull/18166 isn't in yet?

We can remove the alias but there is a lot of existing tooling/instruction that uses the old name and things will break until they are updated.

**Comment by mhutch** [comment]
@lewing it looks like redirects won't make it for .NET 6 as we're not 100% confident they won't have unexpected side effects as currently implemented. I think we just have to take the breaking change while we're in preview, sorry :/

**Comment by lewing** [comment]
This is going to generate 50 more complaint emails across multiple teams.

**Comment by lewing** [comment]
> @lewing it looks like redirects won't make it for .NET 6 as we're not 100% confident they won't have unexpected side effects as currently implemented. I think we just have to take the breaking change while we're in preview, sorry :/

It's not a problem, I was just hoping to avoid breaking the world again this week.

**Comment by lewing** [comment]
I'm going to land this later tonight unless there are strong objections.

**Review by mhutch — APPROVED** [review]

**Review by steveisok — APPROVED** [review]

**Comment by SamMonoRT** [comment]
@naricc - possibly this affects the BDN Microbenchmark runs ?

**Pull request merged**
