### PR TITLE
Fix uname usage and add binlogs 

### LINKED ISSUE #33164: Building dotnet/runtime fails with exit code 253
Building the dotnet/runtime repo after `git clean -xdff` with `./coreclr.sh -c release` failed with

```
/Users/mdhwang/runtime/src/coreclr/crossgen-corelib.proj(17,5): error MSB3073: The command ""/Users/mdhwang/runtime/src/coreclr/crossgen-corelib.sh" -release" exited with code 253.
/Users/mdhwang/runtime/.dotnet/sdk/5.0.100-preview.2.20153.3/Microsoft.Common.CurrentVersion.targets(4643,5): error MSB3030: Could not copy the file "/Users/mdhwang/runtime/artifacts/bin/coreclr/OSX.x64.Release/libclrjit.dylib" because it was not found. [/Users/mdhwang/runtime/src/coreclr/src/tools/crossgen2/crossgen2/crossgen2.csproj]
/Users/mdhwang/runtime/.dotnet/sdk/5.0.100-preview.2.20153.3/Microsoft.Common.CurrentVersion.targets(4643,5): error MSB3030: Could not copy the file "/Users/mdhwang/runtime/artifacts/bin/coreclr/OSX.x64.Release/libjitinterface.dylib" because it was not found. [/Users/mdhwang/runtime/src/coreclr/src/tools/crossgen2/crossgen2/crossgen2.csproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error : Error when creating nuget lib package from /Users/mdhwang/runtime/artifacts/packages/Release/specs/runtime.osx-x86.Microsoft.NETCore.ILAsm.nuspec. NuGet.Packaging.Core.PackagingException: File not found: '/Users/mdhwang/runtime/artifacts/bin/coreclr/OSX.x64.Release/ilasm'. [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/Microsoft.NETCore.ILAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/Microsoft.NETCore.ILAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/Microsoft.NETCore.ILAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, String nupkgPath, Manifest manifest, Boolean packSymbols) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs:line 254 [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/Microsoft.NETCore.ILAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error : Error when creating nuget packed package from /Users/mdhwang/runtime/artifacts/packages/Release/specs/runtime.osx-x86.Microsoft.NETCore.ILAsm.nuspec. NuGet.Packaging.Core.PackagingException: File not found: '/Users/mdhwang/runtime/artifacts/bin/coreclr/OSX.x64.Release/ilasm'. [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/Microsoft.NETCore.ILAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/Microsoft.NETCore.ILAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/Microsoft.NETCore.ILAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, String nupkgPath, Manifest manifest, Boolean packSymbols) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs:line 254 [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/Microsoft.NETCore.ILAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error : Error when creating nuget lib package from /Users/mdhwang/runtime/artifacts/packages/Release/specs/runtime.osx-x86.Microsoft.NETCore.ILDAsm.nuspec. NuGet.Packaging.Core.PackagingException: File not found: '/Users/mdhwang/runtime/artifacts/bin/coreclr/OSX.x64.Release/ildasm'. [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/Microsoft.NETCore.ILDAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/Microsoft.NETCore.ILDAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/Microsoft.NETCore.ILDAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, String nupkgPath, Manifest manifest, Boolean packSymbols) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs:line 254 [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/Microsoft.NETCore.ILDAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error : Error when creating nuget packed package from /Users/mdhwang/runtime/artifacts/packages/Release/specs/runtime.osx-x86.Microsoft.NETCore.ILDAsm.nuspec. NuGet.Packaging.Core.PackagingException: File not found: '/Users/mdhwang/runtime/artifacts/bin/coreclr/OSX.x64.Release/ildasm'. [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/Microsoft.NETCore.ILDAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/Microsoft.NETCore.ILDAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/Microsoft.NETCore.ILDAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, String nupkgPath, Manifest manifest, Boolean packSymbols) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs:line 254 [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/Microsoft.NETCore.ILDAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error : Error when creating nuget packed package from /Users/mdhwang/runtime/artifacts/packages/Release/specs/runtime.osx-x86.Microsoft.NETCore.ILDAsm.nuspec. NuGet.Packaging.Core.PackagingException: File not found: '/Users/mdhwang/runtime/artifacts/bin/coreclr/OSX.x64.Release/ildasm'. [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/Microsoft.NETCore.ILDAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/Microsoft.NETCore.ILDAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/Microsoft.NETCore.ILDAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, String nupkgPath, Manifest manifest, Boolean packSymbols) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs:line 254 [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILDAsm/Microsoft.NETCore.ILDAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error : Error when creating nuget packed package from /Users/mdhwang/runtime/artifacts/packages/Release/specs/runtime.osx-x86.Microsoft.NETCore.ILAsm.nuspec. NuGet.Packaging.Core.PackagingException: File not found: '/Users/mdhwang/runtime/artifacts/bin/coreclr/OSX.x64.Release/ilasm'. [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/Microsoft.NETCore.ILAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/Microsoft.NETCore.ILAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/Microsoft.NETCore.ILAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, String nupkgPath, Manifest manifest, Boolean packSymbols) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs:line 254 [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.ILAsm/Microsoft.NETCore.ILAsm.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error : Error when creating nuget lib package from /Users/mdhwang/runtime/artifacts/packages/Release/specs/runtime.osx-x86.Microsoft.NETCore.TestHost.nuspec. NuGet.Packaging.Core.PackagingException: File not found: '/Users/mdhwang/runtime/artifacts/bin/coreclr/OSX.x64.Release/corerun'. [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/Microsoft.NETCore.TestHost.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/Microsoft.NETCore.TestHost.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/Microsoft.NETCore.TestHost.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, String nupkgPath, Manifest manifest, Boolean packSymbols) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs:line 254 [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/Microsoft.NETCore.TestHost.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error : Error when creating nuget packed package from /Users/mdhwang/runtime/artifacts/packages/Release/specs/runtime.osx-x86.Microsoft.NETCore.TestHost.nuspec. NuGet.Packaging.Core.PackagingException: File not found: '/Users/mdhwang/runtime/artifacts/bin/coreclr/OSX.x64.Release/corerun'. [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/Microsoft.NETCore.TestHost.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/Microsoft.NETCore.TestHost.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/Microsoft.NETCore.TestHost.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, String nupkgPath, Manifest manifest, Boolean packSymbols) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs:line 254 [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/Microsoft.NETCore.TestHost.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error : Error when creating nuget packed package from /Users/mdhwang/runtime/artifacts/packages/Release/specs/runtime.osx-x86.Microsoft.NETCore.TestHost.nuspec. NuGet.Packaging.Core.PackagingException: File not found: '/Users/mdhwang/runtime/artifacts/bin/coreclr/OSX.x64.Release/corerun'. [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/Microsoft.NETCore.TestHost.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/Microsoft.NETCore.TestHost.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files) [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/Microsoft.NETCore.TestHost.pkgproj]
/Users/mdhwang/.nuget/packages/microsoft.dotnet.build.tasks.packaging/5.0.0-beta.20152.4/build/Packaging.targets(1260,5): error :    at Microsoft.DotNet.Build.Tasks.Packaging.NuGetPack.Pack(String nuspecPath, String nupkgPath, Manifest manifest, Boolean packSymbols) in /_/src/Microsoft.DotNet.Build.Tasks.Packaging/src/NuGetPack.cs:line 254 [/Users/mdhwang/runtime/src/coreclr/src/.nuget/Microsoft.NETCore.TestHost/Microsoft.NETCore.TestHost.pkgproj]
    0 Warning(s)
    12 Error(s)
```

[Full build log](https://github.com/dotnet/runtime/files/4289140/coreclr_release_build.txt)

Running `uname -p` gave `i386`.

Forcing the architecture in `eng/native/init-os-and-arch.sh` by changing https://github.com/dotnet/runtime/blob/389835b1597180c0753c4daeb88afe008252dfe4/eng/native/init-os-and-arch.sh#L16 to `CPUName=x86_64` allows for a successful build.

There seems to be an inconsistency with the system detecting 32-bit, yet building with `amd64` paths. Changing `uname -p` to `uname-m` might help properly detect 64-bit.

##
System
macOS Catalina 10.15.3

### LINKED ISSUE #33210: Version symbol missing from MacOS coreclr assets
Somewhere between b3f81350 and 9bcf3b12 we stopped producing version information for our OSX images.

### LINKED ISSUE #33211: macOS ends up as marked as a cross build
Using `uname -p` on mac returns `i386`, which means here we classify the host as x86:

https://github.com/dotnet/runtime/blob/389835b1597180c0753c4daeb88afe008252dfe4/eng/native/init-os-and-arch.sh#L42

And this cascades into flagging this as a cross build here:
https://github.com/dotnet/runtime/blob/389835b1597180c0753c4daeb88afe008252dfe4/src/coreclr/build-runtime.sh#L183

A better solution might be to use `uname -m`, although there's a comment stating `# Some Linux platforms report unknown for platform, but the arch for machine.` That seems like the desired outcome nonetheless. 

Related: #33164

### PR DESCRIPTION
**Pull request by hoyosjs**
According to https://en.wikipedia.org/wiki/Uname#Examples as pointed out by @danmosemsft matches most of the values we have used over time. Thanks @mdh1418 for the fix suggestion to use the -m flag.  

@jkoritzinsky it's either this, or just return `init-os-and-arch` to the older fallback tree. Any reason to extend the tree as you did? Any impact on RIDs or other component builds? Specially for 1386?

Fixes #33164
Fixes #33211
Fixes #33210

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
I extended the tree based on @am11’s feedback. I didn’t have any particular reason to extend it.

**Comment by am11** [comment]
@jkoritzinsky, this OSX build is before your PR was merged and has the same issue: https://dev.azure.com/dnceng/public/_build/results?buildId=514798&view=logs&j=8a742514-b8bd-5f7f-a706-89d0e8c57cc6&t=63254f6c-9351-50b1-ef65-7fd2e7d08b71&l=21. I think `init-os-and-arch` changes are irrelevant to this issue. Please CMIIW. :)

**Comment by jkoritzinsky** [comment]
There's a slight difference from before my PR was merged and after. Before it was merged, i386 showed up as an "Unknown arch" so we would default to building for x64. After it was merged, we recognized i386, so we recognized it as an unsupported arch, but would still try to build for osx-x86 (which is expected, some of our partners build us for Linux x86 so we allowed it even though we don't support it).

**Comment by am11** [comment]
Thanks for the info @jkoritzinsky! I didn't realized this difference.
I also think `-m` is the right default. As a reference, please take a look at CMake's platform detection logic (which has quite a large array of supported platforms): https://github.com/Kitware/CMake/blob/e484b42/Modules/CMakeDetermineSystem.cmake#L46.

**Review by akoeplinger — APPROVED** [review]

**Review by jashook — APPROVED** [review]

**Review by jkoritzinsky — APPROVED** [review]

**Comment by hoyosjs** [comment]
Failures are #33291 which are pre-existing. This doesn't touch any Windows bits.

**Pull request merged**
