### PR TITLE
[mono] Fix diamond pattern encountered with static virtual interface methods

### PR DESCRIPTION
**Pull request by BrzVlad**
Test for this is added in PR https://github.com/dotnet/runtime/pull/66887

### CODE REVIEW

**Review by trylek — APPROVED** [review]
I don't really consider myself a Mono expert but to my limited knowledge this looks good, thank you!

**Comment by BrzVlad** [comment]
The test case from the CoreCLR PR might suffer further additions so keeping this on hold until then.

**Comment by BrzVlad** [comment]
This still passes the latest version of the testcase, so all good.
@lambdageek Would you like to also take a look at this change ?

**Comment by vargaz** [comment]
The JIT changes look ok to me.

**Comment by lewing** [comment]
/azp run runtime-wasm

lgtm

**Review by lambdageek — APPROVED** [review]

**Pull request merged**
