### PR TITLE
Fix DynamicInvokeMethodThunk hash code collisions

### LINKED ISSUE #103070: Unoptimal hash code combine in TypeHashingAlgorithms.ComputeMethodHashCode
There's a TODO in the code:

https://github.com/dotnet/runtime/blob/b438888c5504c8dafe3746393ab76f3e5e1eff6d/src/coreclr/tools/Common/TypeSystem/Common/TypeHashingAlgorithms.cs#L229-L234

Notably, this comes up as a sore spot in my profiles:

image

Changing to `HashCode.Combine` yields about >20% less hash collisions in this method alone:

image

This compilation speed improvement is quite noticable.

Unfortunately, there seems to be some dependency on the hash combining algorithm somewhere in the code because this produces an executable that fails to run at runtime:

```
Process terminated. Failed to create generic virtual method implementation

Declaring type: Microsoft.Extensions.Options.OptionsBuilder`1<Microsoft.Extensions.Options.StartupValidatorOptions>
Method name: Configure
Instantiation:
  Argument 00000000: Microsoft.Extensions.Options.IOptionsMonitor`1<Microsoft.Extensions.DependencyInjection.MetricsServiceExtensions+NoOpOptions>

   at System.RuntimeExceptionHelpers.FailFast(String, Exception, String, RhFailFastReason, IntPtr, IntPtr) + 0x2b0
   at Internal.Runtime.TypeLoader.TypeLoaderEnvironment.ResolveGenericVirtualMethodTarget(RuntimeTypeHandle, RuntimeMethodHandle) + 0x210
   at System.Runtime.TypeLoaderExports.<>c.<GVMLookupForSlotSlow>b__8_0(IntPtr context, IntPtr signature, Object contextObject, IntPtr& auxResult) + 0x31
   at System.Runtime.TypeLoaderExports.CacheMiss(IntPtr, IntPtr, RuntimeObjectFactory, Object) + 0x28
   at System.Runtime.TypeLoaderExports.GVMLookupForSlotSlow(Object, RuntimeMethodHandle) + 0x4e
   at System.Runtime.TypeLoaderExports.GVMLookupForSlot(Object, RuntimeMethodHandle) + 0x9a
   at Microsoft.Extensions.DependencyInjection.OptionsBuilderExtensions.ValidateOnStart[TOptions](OptionsBuilder`1) + 0x6e
   at Microsoft.Extensions.DependencyInjection.MetricsServiceExtensions.AddMetrics(IServiceCollection) + 0x47
   at Microsoft.Extensions.DependencyInjection.HttpClientFactoryServiceCollectionExtensions.AddHttpClient(IServiceCollection) + 0x26
   at MailClient.Program.SetUpDependencyInjection() + 0x2a9
   at MailClient.Program.Main(String[] args) + 0xd2
```

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #103070

Let's see the CI if it breaks anything.

### CODE REVIEW

**Review by MichalStrehovsky — APPROVED** [review]
Alternative fix would be to go back to how we used to compute the name of these methods (it wasn't always a constant string), but I don't have a strong opinion. We don't otherwise override `ComputeHashCode` anywhere else. It's only virtual because of instantiated methods:

https://github.com/dotnet/runtime/blob/eb8f54d92b015c8b416f6e506fd4c3335740302c/src/coreclr/tools/Common/TypeSystem/Common/MethodDesc.cs#L493-L495

**Comment by jkotas** [comment]
> Should only be overridden by a MethodDesc that represents an instantiated method.

Delete this comment since it is not valid anymore?

**Comment by filipnavara** [comment]
> Delete this comment since it is not valid anymore?

I would like to keep some comment there.

There are runtime dependencies on the hash code both in NativeAOT and R2R. For NativeAOT it should mostly link to the same code in `TypeHashingAlgorithms` so the code is in sync with runtime implementation. For R2R there are places in unmanaged CoreCLR that do the XOR hash combining and that are not in any way linked to the Crossgen2 implementation even if they need to produce the same value. 

Any suggestion for wording?

**Comment by MichalStrehovsky** [comment]
It might be easier to just add some suffix to the Name/DiagnosticName (e.g. number of parameters) so that we avert at least some of the collisions, drop the override, and call it good enough.

**Review by jkotas — COMMENTED** [review]
> Any suggestion for wording?

This hashcode is persisted into the image. The algorithm to compute it must be in sync with the one used at runtime.

> It might be easier to just add some suffix to the Name/DiagnosticName (e.g. number of parameters)

Number of parameters is going to reduce the collisions like 3x (a lot of methods take one or two arguments). It would be still leaving a lot on the table.

**Review by jkotas — APPROVED** [review]

**Comment by jkotas** [comment]
Thank you!

**Pull request merged**
