### PR TITLE
JIT: metrics for profile consistency, gdv, devirt...

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Add some metrics to early jit phases. Also add the ability to automatically merge inlinee counts to the root method, for successful inlines.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@amanasifkhalid @jakobbotsch PTAL
cc @dotnet/jit-contrib 

Was a bit puzzled by `JitMetrics` in release vs debug. Looks like the class is there in release but none of the methods are?

Some data from ASP.NET:

Metric | Value
-- | --
ProfileSynthesizedBlendedOrRepaired | 191577
ProfileInconsistentInitially | 29
ProfileInconsistentResetLeave | 0
ProfileInconsistentImporterBranchFold | 7713
ProfileInconsistentImporterSwitchFold | 92
ProfileInconsistentChainedGDV | 0
ProfileInconsistentScratchBB | 2
GDV | 25315
ClassGDV | 23744
MethodGDV | 1571
MultiGuessGDV | 0
ChainedGDV | 1618
DevirtualizedCall | 41887
DevirtualizedCallUnboxedEntry | 455
DevirtualizedCallRemovedBox | 21
ImporterBranchFold | 58803
ImporterSwitchFold | 114

**Review by amanasifkhalid — APPROVED** [review]
LGTM, thanks for sharing the metrics -- I'm curious to see how profile consistency fares after inlining...

**Review by jakobbotsch — APPROVED** [review]
Cool, happy to see someone else adding some metrics.

**Comment by jakobbotsch** [comment]
> Was a bit puzzled by `JitMetrics` in release vs debug. Looks like the class is there in release but none of the methods are?

Yeah, I think we should enable parts of this in release, perhaps doing the reporting only under `JitConfig.JitMetrics`. We should also be able to get (non-detailed) memory measurements this way.

**Pull request merged**
