### PR TITLE
Ensure only one empty string exists in the UserString heap.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
According to §II.24.2.4 of ECMA-335, `The first entry in [the UserString heap] is the empty 'blob' that consists of the single byte 0x00.`. We write this byte but do not make use of it, and when we call `GetOrAddUserString("")` it creates a new entry. A similar thing happens when reserving a user string of zero size. This PR fixes these problems.

### CODE REVIEW

**Comment by teo-tsirpanis** [comment]
Hmm, some regex generator tests are failing with a `System.BadImageFormatException : No string associated with token.`. Did I miss something? 🤔

**Comment by tmat** [comment]
I don't see much benefit of changing this.

**Comment by buyaa-n** [comment]
> I don't see much benefit of changing this.

From the description isn't it at least reusing the empty string? @teo-tsirpanis could you collaborate on benefits?

@tmat is this change could break somebody or if it would not affect perf badly somehow?

**Comment by tmat** [comment]
IDK, just not sure what value this change adds. Is saving 2 bytes per assembly worth the effort?

**Comment by teo-tsirpanis** [comment]
> From the description isn't it at least reusing the empty string?

Well, that's the only benefit actually.

**Comment by buyaa-n** [comment]
> Well, that's the only benefit actually.

Sounds like @teo-tsirpanis agree with that there is not much benefit of changing this. Closing as not planned, feel free to reopen.

**Pull request closed without merging**
