### PR TITLE
SPMI: Ensure we disable loop alignment consistently

### PR DESCRIPTION
**Pull request by jakobbotsch**
Recently we disabled loop alignment in SPMI diffs, but this was only done for the SPMI invocations when we generate disassembly. This would result in the diffs run seeing different generated code than subsequent disassembly runs.

This splits the environment variables we want to have enabled in the diffs SPMI invocation out into its own dictionary. These are force overridden.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @kunalspathak @BruceForstall

**Review by kunalspathak — APPROVED** [review]
LGTM. How was this caught? Also, what is "force" about? I see its reference in other places in the file too.

**Comment by jakobbotsch** [comment]
> LGTM. How was this caught? Also, what is "force" about? I see its reference in other places in the file too.

I noticed when I did an asmdiffs run that the diffs reported by jit-analyze did not sum to the one reported by superpmi.py.

Force is used to override JIT env vars that were recorded into the context. For example, if we in the future record a test with `DOTNET_JitAlignLoops=1`, then the "force" allows this to be overridden to `DOTNET_JitAlignLoops=0` in asmdiffs runs.

**Review by BruceForstall — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Kicked off a superpmi-diffs run at https://dev.azure.com/dnceng-public/public/_build/results?buildId=172165&view=results

**Comment by jakobbotsch** [comment]
Hmm, there are two same size diffs in the SPMI-diffs run, but the .dasm files do not have any diffs. Will investigate.

**Comment by jakobbotsch** [comment]
That happens on main too. It seems there is some issue with recording relocations, the diffs that SPMI is finding is in constants that should have been recorded as relocations. When I look at the dump, the offsets for those relocations are off by 0x10 bytes.
I wonder if it also explains some of the recent regressions in #82105, #82106, #82111 that look like they could be loop alignment related.

**Comment by jakobbotsch** [comment]
I will merge this and continue investigating the relocation issue separately.

**Comment by jakobbotsch** [comment]
Hmm, actually no, there is no relocation emitted for that particular constant I was looking at, which is probably the problem:

https://github.com/dotnet/runtime/blob/3a3692029a2a038581fdc8c1c6496e0506a7e0c7/src/coreclr/jit/compiler.cpp#L3114

A newly added test has `DOTNET_JitStress=1` and it causes us to insert these enter/leave calls to this method, which resides in clrjit.dll and will be different for base/diff JIT.

**Comment by BruceForstall** [comment]
> A newly added test has `DOTNET_JitStress=1` and it causes us to insert these enter/leave calls to this method, which resides in clrjit.dll and will be different for base/diff JIT.

Maybe we should fix the JIT to emit relocations.

However, we generally shouldn't have tests that set DOTNET_JitStress, since the mix of stress modes invoked might change based on the test hash (theoretically this shouldn't change unless the test is altered).

Looks like the tests are:

JIT\Regression\JitBlue\Runtime_81585\Runtime_81585.csproj
JIT\Regression\JitBlue\Runtime_81725\Runtime_81725.csproj

Instead, these should use DOTNET_JitStressModeNames and set exactly the stress modes needed for the test.

**Pull request merged**
