### PR TITLE
Remove perfinfo-%pid.map

### PR DESCRIPTION
**Pull request by brianrob**
This functionality was previously used along with `crossgen` (not `crossgen2`) to support resolution of R2R symbols by `perfcollect`.

Perfinfo-%pid.map files are no longer needed now that jitdump and r2rmap functionality exists.  Jitdumps natively allow `perf` to resolve both jitted and R2R symbols.  r2rmap files allow for custom collectors to resolve symbols in traces.

### CODE REVIEW

**Comment by tommcdon** [comment]
FYI @steveisok

**Comment by noahfalk** [comment]
@brianrob - In the past I thought we had customer feedback saying that jitdumps were much larger files and than perfmaps and they were reporting resource exhaustion. I think it was memory exhaustion because either a tool or the OS itself was mapping all these files into memory, but it also may have been disk space exhaustion. Does any of that ring a bell? I think we should figure out if anyone is still relying on being able to downgrade to perfmaps before removing the functionality.

If we do remove it we need to figure out what the new behavior of the DOTNET_PerfMapEnabled environment variable should be. Currently setting it to 1 means emit a perfmap and I'm guessing now that wouldn't do anything? We'd probably want to update the code that reads this config to make that clear.

**Comment by brianrob** [comment]
> @brianrob - In the past I thought we had customer feedback saying that jitdumps were much larger files and than perfmaps 

@noahfalk, thanks for the feedback.  This change does not remove perfmaps.  This only removes `perfinfo-%pid.map`.  This is a custom file that `perf` doesn't know anything about.  It was used prior to .NET 5 to enable PerfView to know which R2R images were loaded so that we could use `crossgen` to generate symbols for PerfView to consume.  This functionality has not worked since we switched to `crossgen2`.

If someone wants to avoid using jitdumps due to overhead, they can use the perfmap functionality, but if they want to resolve R2R symbols, they will need to use a custom collector that captures mmap events and then uses `crossgen2` to generate `r2rmap` files for those R2R images.  We have a couple of cases internally where this happens, but so far, externally, everyone that I'm aware of uses jitdumps.  `perfcollect` doesn't currently support this.

**Comment by noahfalk** [comment]
Ah, my mistake then, no concerns then :)

**Review by noahfalk — APPROVED** [review]

**Review by davmason — APPROVED** [review]

**Pull request merged**
