### PR TITLE
Dynamic heap count

### PR DESCRIPTION
**Pull request by PeterSolMS**
This is an initial implementation for changing the GC heap count dynamically in response to changing load conditions.

Using more heaps will increase memory footprint, but in most cases also improve throughput because more GC work is parallelized, and lock contention on the allocation code path is reduced by spreading the load.

The algorithm used makes this tradeoff explicit and increases the heap count by comparing the estimated percentage increase in throughput with the estimated percentage increase in memory footprint. It increases the heap count if the throughput is estimated to increase at least one percentage point more than the memory footprint increase, and decreases the heap count if the estimated reduction in memory footprint is at least one percentage point more than the decrease in throughput.

Because the input data for GC pause etc. are quite noisy, we use a median of 3 filter before the data is used to make decisions. Preliminary data suggests this is effective, but probably not enough.

### CODE REVIEW

**Review by Maoni0 — APPROVED** [review]
@PeterSolMS and I talked about this and we do want to get this in for Preview 5 to get more testing. we've already gone through the changes offline.

**Comment by PeterSolMS** [comment]
Regarding the assert failures in `compute_new_dynamic_data`, the cases I could repro were all for gen 1 where the `dd_current_size` is actually irrelevant for the budget computation. Nonetheless, it seemed safer to set `dd_current_size` to 0 rather than a huge positive value for the case of `total_gen_size < dd_fragmentation (dd)`. My guess is that when we empty gen 1, we don't actually zero `generation_free_obj_space`.

**Review by mangod9 — APPROVED** [review]

**Comment by mangod9** [comment]
> Regarding the assert failures in `compute_new_dynamic_data`, the cases I could repro were all for gen 1 where the `dd_current_size` is actually irrelevant for the budget computation. Nonetheless, it seemed safer to set `dd_current_size` to 0 rather than a huge positive value for the case of `total_gen_size < dd_fragmentation (dd)`. My guess is that when we empty gen 1, we don't actually zero `generation_free_obj_space`.

Is this something which needs to be fixed before merging?

**Comment by PeterSolMS** [comment]
No, this is a lurking issue that has nothing to do with dynamic heap count. It happened without the feature active, and all the cases I looked at were on WKS GC, and were benign in the sense that there was no impact on the budget computation or other correctness aspects.

**Comment by mangod9** [comment]
Looks like the failures are known per Build-Analysis. Should be ok to merge.

**Comment by PeterSolMS** [comment]
Agree. Note that I have a PR out for the assert failure.

**Pull request merged**
