### PR TITLE
[wasm] bump devDependencies to rollup 3 and TypeScript 4.9

### LINKED ISSUE #78708: [wasm] consider bumping devDependencies
We should consider bumping the devDependencies for our wasm runtime (in particular, rollup and TypeScript both have had major version releases):

```console
$ npm outdated -D
Package                           Current  Wanted  Latest  Location                                       Depended by
@rollup/plugin-typescript           8.3.3   8.3.3   9.0.2  node_modules/@rollup/plugin-typescript         runtime
@typescript-eslint/eslint-plugin   5.30.7  5.30.7  5.44.0  node_modules/@typescript-eslint/eslint-plugin  runtime
@typescript-eslint/parser          5.30.7  5.30.7  5.44.0  node_modules/@typescript-eslint/parser         runtime
eslint                             8.20.0  8.20.0  8.28.0  node_modules/eslint                            runtime
fast-glob                          3.2.11  3.2.11  3.2.12  node_modules/fast-glob                         runtime
rollup                             2.77.0  2.77.0   3.4.0  node_modules/rollup                            runtime
rollup-plugin-dts                   4.2.2   4.2.2   5.0.0  node_modules/rollup-plugin-dts                 runtime
terser                             5.14.2  5.14.2  5.15.1  node_modules/terser                            runtime
tslib                               2.4.0   2.4.0   2.4.1  node_modules/tslib                             runtime
typescript                          4.7.4   4.7.4   4.9.3  node_modules/typescript                        runtime
```

### PR DESCRIPTION
**Pull request by lambdageek**
1. `rollup-plugin-consts` hasn't released a version that works with rollup 3.  But `@rollup/plugin-virtual` can do everything that we need from consts.
2. `rollup-plugin-terser` is unmaintained and has been superseded by `@rollup/plugin-terser`
3. TypeScript 4.9 got rid of a type used by http.ts, but fortunately there's a straightforward replacement for what we need.
4. `fast-glob` changed how it exports the `sync` API

Fixes #78708

### CODE REVIEW

**Comment by lambdageek** [comment]
```
 npm ERR! code E401
  npm ERR! Unable to authenticate, your authentication token seems to be invalid.
  npm ERR! To correct this please trying logging in again with:
  npm ERR!     npm login
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /home/cloudtest_azpcontainer/.npm/_logs/2022-11-22T20_45_44_497Z-debug.log
```

What does this mean? It seems related to `src/mono/wasm/runtime/.npmrc`. similar to what was happening with https://github.com/dotnet/runtime/pull/71393.  Any ideas how that issue was resolved? @radical @steveisok

**Comment by pavelsavara** [comment]
> What does this mean? 

I think it means that some of the NPM packages you use are not in the corporate NPM repository. I think we need to ask fires-responders to add the package.

**Comment by pavelsavara** [comment]
`"lockfileVersion": 2,` please use nodejs version in the emsdk to create the lock file v 1.

**Comment by pavelsavara** [comment]
Just visual sanity check: take the minified dotnet.js, prettify it with some tool and run diff to previous version. 
Since emsdk has it's own closure compiler on top of our terser, there may be (new) problems.

**Comment by maraf** [comment]
> @maraf Marek Fisera FTE do you know how ?

No idea

**Comment by lambdageek** [comment]
> `"lockfileVersion": 2,` please use nodejs version in the emsdk to create the lock file v 1.

I did the upgrade using npm from emsdk. Is there some trick to make it generate a v1 lockfile?

**Comment by lambdageek** [comment]
Ok I see.  

Apparently the workflow has to be something like this (based on https://github.com/dotnet/runtime/pull/71393#issuecomment-1170346952):

1. Run `source .../emsdk_env.sh` so that the EMSDK  version of node and npm are used 
2. Run `npm cache clean -force`
3. Go to https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-public-npm/connect/npm and install the auth tools (you have to be logged in to see the link) from the "Other" tab to get the linux/mac tools.
4. Edit the `package.json` to bump the versions
5. run `npm update --save-dev --lockfile-version 1`

I haven't done this myself yet, but I'll do it in a couple hours and push the results

**Comment by lambdageek** [comment]
> `"lockfileVersion": 2,` please use nodejs version in the emsdk to create the lock file v 1.

oh I see what happened - my `make provision-wasm` was fine, but at some point I must have upgraded npm in the emscripten sdk.

**Comment by lambdageek** [comment]
Hmm... rollup potentially doesn't like npm v6. I suspect it doesn't matter for us, but maybe the warning will trip something up on CI

```
npm WARN notsup Unsupported engine for rollup@3.4.0: wanted: {"node":">=14.18.0","npm":">=8.0.0"} (current: {"node":"14.18.2","npm":"6.14.15"})
npm WARN notsup Not compatible with your version of node/npm: rollup@3.4.0
```

**Comment by lambdageek** [comment]
Comparing `runtime.es6.iffe.js` from this PR and main after running through VS Code "prettier" extension, the only differences I see are the choice of some of the minified variable names (new terser seems to like `_` more than `d` and `W` more than `P`)

**Comment by radical** [comment]
>..
> 1. Run `source .../emsdk_env.sh` so that the EMSDK  version of node and npm are used
> 2. Run `npm cache clean -force`
> 3. Go to https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-public-npm/connect/npm and setup authentication to the azdo npm registry -  on linux/mac login and look at the "Other" tab for instructions on modifying your `~/.npmrc`
> 4. Edit the `package.json` to bump the versions
> 5. run `npm install --lockfile-version=1`

Can this be added to `src/mono/wasm/README.md`? this and the thing about using specific npm version.

**Comment by lambdageek** [comment]
> Can this be added to `src/mono/wasm/README.md`? this and the thing about using specific npm version.

done

**Review by pavelsavara — APPROVED** [review]
many thanks!

**Pull request merged**
