### PR TITLE
JIT: fix exit edge likelihood computation for capped loops

### LINKED ISSUE #84789: Regressions in System.Reflection.Invoke
### Run Information

Name | Value
-- | --
Architecture | arm64
OS | ubuntu 20.04
Queue | AmpereUbuntu
Baseline | [605eb6eda2b1e04f79a2f7937506cd9deaec6a9b](https://github.com/dotnet/runtime/commit/605eb6eda2b1e04f79a2f7937506cd9deaec6a9b)
Compare | [c22b79ae2d1b2a9ca73a42e246e3f3da02e631fe](https://github.com/dotnet/runtime/commit/c22b79ae2d1b2a9ca73a42e246e3f3da02e631fe)
Diff | [Diff](https://github.com/dotnet/runtime/compare/605eb6eda2b1e04f79a2f7937506cd9deaec6a9b...c22b79ae2d1b2a9ca73a42e246e3f3da02e631fe)
Configs | CompilationMode:tiered, RunKind:micro

### Regressions in System.Reflection.Invoke

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[Field_Get_int - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu 20.04/System.Reflection.Invoke.Field_Get_int.html>) | 74.83 ns | 93.81 ns | 1.25 | 0.28 | False | | |

graph
[Test Report](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_30_2023/refs/heads/main_arm64_ubuntu%2020.04_Regression/System.Reflection.Invoke.html>)

### Repro
General Docs link: https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-393cb2bb-c4c0-4a0a-921c-6ed59f29b032bd26bc84235452abd/86379c35-faa9-4269-94a8-206820ef714f.zip?sv=2021-08-06&se=2023-04-23T19%3A55%3A55Z&sr=c&sp=rl&sig=pICAcUkxsHFulpCx%2BCigv%2BRzaiQZRMcAzIrSiJoJHgs%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-0114e38f-1268-4b15-b6e0-bc03ee5737dcdd969a6b4fe49e985/d41f593d-b68c-4e29-b722-afdd2a17f7b1.zip?sv=2021-08-06&se=2023-04-24T15%3A02%3A04Z&sr=c&sp=rl&sig=9htIeIXfxC11K3q7u3QtVTZdNHWdA56cVu9Qv15wKss%3D>)

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net8.0 --filter 'System.Reflection.Invoke*'
```

<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-393cb2bb-c4c0-4a0a-921c-6ed59f29b032bd26bc84235452abd/86379c35-faa9-4269-94a8-206820ef714f.zip?sv=2021-08-06&se=2023-04-23T19%3A55%3A55Z&sr=c&sp=rl&sig=pICAcUkxsHFulpCx%2BCigv%2BRzaiQZRMcAzIrSiJoJHgs%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-0114e38f-1268-4b15-b6e0-bc03ee5737dcdd969a6b4fe49e985/d41f593d-b68c-4e29-b722-afdd2a17f7b1.zip?sv=2021-08-06&se=2023-04-24T15%3A02%3A04Z&sr=c&sp=rl&sig=9htIeIXfxC11K3q7u3QtVTZdNHWdA56cVu9Qv15wKss%3D>)
#### System.Reflection.Invoke.Field_Get_int

```log

```
### Description of detection logic
```
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsRegressionBase: Marked as regression because the compare was 5% greater than the baseline, and the value was not too small.
IsRegressionChecked: Marked as regression because the three check build points were 0.05 greater than the baseline.
IsRegressionWindowed: Marked as regression because 93.8067525548623 > 78.1986461298077.
IsChangePoint: Marked as a change because one of 1/13/2023 9:23:19 AM, 3/17/2023 5:40:49 AM, 3/25/2023 12:18:49 AM, 3/30/2023 4:24:24 AM falls between 3/21/2023 2:53:21 PM and 3/30/2023 4:24:24 AM.
IsRegressionStdDev: Marked as regression because -24.345292438042073 (T) = (0 -92.92124544278508) / Math.Sqrt((0.4761242123680715 / (22)) + (9.688559887847028 / (17))) is less than -2.026192463026769 = MathNet.Numerics.Distributions.StudentT.InvCDF(0, 1, (22) + (17) - 2, .025) and -0.252365131071706 = (74.19660859071358 - 92.92124544278508) / 74.19660859071358 is less than -0.05.
IsImprovementBase: Marked as not an improvement because the compare was not 5% less than the baseline, or the value was too small.
IsChangeEdgeDetector: Marked not as a regression because Edge Detector said so.

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

---

### Run Information

Name | Value
-- | --
Architecture | arm64
OS | ubuntu 20.04
Queue | AmpereUbuntu
Baseline | [605eb6eda2b1e04f79a2f7937506cd9deaec6a9b](https://github.com/dotnet/runtime/commit/605eb6eda2b1e04f79a2f7937506cd9deaec6a9b)
Compare | [c22b79ae2d1b2a9ca73a42e246e3f3da02e631fe](https://github.com/dotnet/runtime/commit/c22b79ae2d1b2a9ca73a42e246e3f3da02e631fe)
Diff | [Diff](https://github.com/dotnet/runtime/compare/605eb6eda2b1e04f79a2f7937506cd9deaec6a9b...c22b79ae2d1b2a9ca73a42e246e3f3da02e631fe)
Configs | CompilationMode:tiered, RunKind:micro

### LINKED ISSUE #84798: Assertion failed 'likelihood >= 0.0' during 'Profile incorporation'
Failed in [libraries-pgo pipeline](https://dev.azure.com/dnceng-public/public/_build?definitionId=145&_a=summary)

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-84772-merge-ca986f3aaa67420399/System.Collections.Tests/1/console.b3c01543.log?helixlogtype=result

cc @AndyAyersMS

### PR DESCRIPTION
**Pull request by AndyAyersMS**
The initial version of this only really worked for very simple cases. Generalize to handle loops with multiple exits better.

The rough idea is to compute how much additional profile flow needs to come out of the loop to match the capped probability, and then try and find one exit block where we can adjust likelhoods to cause exactly this amount of extra flow to leave the loop.

Closes #84798.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@egorbo PTAL
cc @dotnet/jit-contrib 

File this one under "I really should have known better" -- I recall thinking about this problem long ago and deciding it wasn't simple to fix, so my simplistic initial fix in #84741 should have set off some personal alarm bells.

No SPMI diffs. Have verified some of the pgo pipeline cases in #84798 are fixed, will run them here to check the rest.

**Comment by EgorBo** [comment]
Failures are related? e.g.
```
Assertion failed 'cappedExitWeight < 1.0' in 'System.Xml.XmlUtf8RawTextWriter:WriteCommentOrPi(System.String,int):this' during 'Profile incorporation'
```

**Comment by AndyAyersMS** [comment]
> Failures are related? e.g.
> 
> ```
> Assertion failed 'cappedExitWeight < 1.0' in 'System.Xml.XmlUtf8RawTextWriter:WriteCommentOrPi(System.String,int):this' during 'Profile incorporation'
> ```

Yes, this is a newly added assert.

**Review by EgorBo — APPROVED** [review]
LGTM assuming CI passes

**Comment by AndyAyersMS** [comment]
Neither PGO pipeline is clean, but so far the failures are known
* libraries-pgo failure in QUIC is #82771 (or similar)
* coreclr-pgo same failures as in baseline

**Pull request merged**
