### PR TITLE
FIx Invariant Culture Casing

### LINKED ISSUE #39522: `System.Globalization.Nls.Tests.ToUpper/ToLower_netcore` test failures in local environment
### Description

Run tests in `System.Globalization.Nls.Tests` test project. The characters after the ToLower/ToUpper call do not change even though we expect it to change.
```
Test	Duration	Traits	Error Message
System.Globalization.Tests.TextInfoMiscTests.ToLower_Netcore Failed	24 ms		Assert.Equal() Failure            ↓ (pos 1) Expected: 𐐨 Actual:   𐐀            ↑ (pos 1)
System.Globalization.Tests.TextInfoMiscTests.ToUpper_netcore Failed	< 1 ms		Assert.Equal() Failure            ↓ (pos 1) Expected: 𐐀 Actual:   𐐨            ↑ (pos 1)

```

Please note that this only seems to happen when no culture name is specified (`new CultureInfo("")`); the exact same test but with the culture name `en-US` / `fr` / `fr-FR` passes fine.

https://github.com/dotnet/runtime/blob/f4e9146d1d2ba7cf48ab59022658619fc9dbaec3/src/libraries/System.Globalization/tests/System/Globalization/TextInfoTests.cs#L174-L184

### Configuration

* Windows 10 Pro Insider Preview, Build 20170 (Also noticed in a couple previous flights), x64
* Locale ko-KR
* Ran with VS2019 16.7 P4, with `./build.cmd -vs System.Globalization -runtimeConfiguration Release -librariesConfiguration Debug`

### Other information

Possibly a Windows NLS issue, rather than the libraries implementation being wrong? Using builds from the dev channel probably doesn't help a lot 😅

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/39522

### CODE REVIEW

**Comment by tarekgh** [comment]
@safern could you please have a look. If this change pass the CI on Win7/Win8, we should be ok to have it.

**Review by safern — APPROVED** [review]
LGTM as long as CI is green.

**Comment by GrabYourPitchforks** [comment]
@tarekgh Do you know what these two lines were trying to guard against in the first place?

https://github.com/dotnet/runtime/blob/6bb606099c6d442aec08fe9825ce5a0acc16f484/src/libraries/System.Private.CoreLib/src/System/Globalization/TextInfo.Nls.cs#L20-L21

**Comment by tarekgh** [comment]
> Do you know what these two lines were trying to guard against in the first place?

No. looks we just inherited this from the full framework. I doubt this is the case anymore. this is why I the comment to Santi was trying to tell if the CI pass on Win7/Win8 then we should be fine to proceed with this fix. 

a side from that, the behavior of not enabling the linguistic casing for invariant is wrong. as you seeing, Windows turning off some casing which will not be the desired behavior for us.

**Comment by tarekgh** [comment]
@GrabYourPitchforks looks turning on the linguistic casing on Invariant cause it support Turkish casing too :-( this looks wrong behavior to me but I doubt Windows will change that. So, I'll close this PR and will try to fix the test instead for now. 

I am thinking when I work on fixing the ordinal casing, I'll make the invariant to use that ordinal casing instead. I can investigate more when I reach this point.

**Pull request closed without merging**
