### PR TITLE
[mono] Disable unsupported apply update scenarios

### LINKED ISSUE #55228: [mono] block debugger attach after managed `ApplyUpdate` is called
Block two scenarios:
1. managed `ApplyUpdate` is called with debugger attached
2. debugger tries to attach after managed `ApplyUpdate` is called.

The issue is that if updates and debugger state are out of sync, we don't have a mechanism to play the debugger up to the modified state so attaching would see outdated breakpoints, locals, etc.  Revisit in future releases.

The only supported scenarios are:
- all updates come in through the debugger protocol
- all updates come from `ApplyUpdate` and the debugger never attaches

### PR DESCRIPTION
**Pull request by lambdageek**
* Disallow mixing managed `ApplyUpdate` and debugger protocol apply update
* Disallow connecting a debugger after `ApplyUpdate` has been called
* Disallow calling `ApplyUpdate` if debugger is attached

Note that I didn't do the last 2 changes on wasm, since the debugging there doesn't fully work yet and it would impede further work to disable stuff now.

Fixes #55228, contributes to #44806

### CODE REVIEW

**Comment by lambdageek** [comment]
@thaystg Do the debugger changes make sense?

@stephentoub I think this matches the scenarios we discussed.

@mikem8361 I think this is consistent with what CoreCLR does?

**Comment by stephentoub** [comment]
> I think this matches the scenarios we discussed.

The second two bullets.  I'm not sure what the first bullet means?

**Comment by lambdageek** [comment]
> > I think this matches the scenarios we discussed.
> 
> The second two bullets. I'm not sure what the first bullet means?

I think the first bullet is more of a technical point (in case I messed up the first two) in the core hot reload method I keep track of whether we are called due to a debugger command or due to a call to the managed ApplyUpdate API and throw an exception if we see a mix of the two.  The other two changes should prevent that from ever happening, but it seemed easy and harmless to add an extra check.

**Comment by stephentoub** [comment]
Got it.  Sounds right then. Thanks.

**Review by thaystg — APPROVED** [review]

**Comment by mikem8361** [comment]
I know it is late, but your logic looks good and follows coreclr's.

**Pull request merged**
