### PR TITLE
Minimum CMake downgrade for Linux (#39044)

### PR DESCRIPTION
**Pull request by jashook**
Port [Minimum CMake downgrade for Linux](https://github.com/dotnet/runtime/pull/39044) back to preview 8. This addresses #38755 and unblocks source-build in preview 8 using cmake < 3.15.

/cc @jkoritzinsky @janvorli @jeffschwMSFT @mmitche

### CODE REVIEW

**Comment by jashook** [comment]
Similar to the master branch I will validate that the build works and a run pri0 tests.

**Review by jkoritzinsky — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]

**Comment by jashook** [comment]
Manually validated the build on centos7 and centos8.

**Comment by mmitche** [comment]
@jashook Any concern with the OSX failure? I've retried it a ton of times.

**Comment by jashook** [comment]
No concern. I believe we need to port back the timeout change we made in master now that the osx machines are slower.

**Pull request merged**
