### PR TITLE
Annotate System.Private.DataContractSerialization

### PR DESCRIPTION
**Pull request by tlakollo**
Reenable the AOT analyzer in System.Private.DataContractSerialization

Related to: https://github.com/dotnet/runtime/pull/73337

### CODE REVIEW

**Review by MichalStrehovsky — APPROVED** [review]
Thanks!

**Review by StephenMolloy — APPROVED** [review]
I don't have a firm grasp on what `RequiresDynamicCode` is attempting to accomplish here. It obviously looks quite similar to and even mostly tags the same places as `RequiresUnreferencedCode` - so I assume its a similar idea but for IL/code we generate instead of code we reflect. It looks mostly like attributes going in, so I don't have a problem here so long as you guys are comfortable that you've got the right set of things attributed.

**Review by LakshanF — APPROVED** [review]

**Comment by LakshanF** [comment]
> I don't have a firm grasp on what `RequiresDynamicCode` is attempting to accomplish here. It obviously looks quite similar to and even mostly tags the same places as `RequiresUnreferencedCode` - so I assume its a similar idea but for IL/code we generate instead of code we reflect. It looks mostly like attributes going in, so I don't have a problem here so long as you guys are comfortable that you've got the right set of things attributed.

Yes, both attributes are related but `RequiresUnreferencedCode` (RUC) is used in [trimming](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained), where a static analysis of the full dependency closure by the compiler cannot determine correctness and warns the developer. Use of unbounded reflection is one such area where the compiler has problems. `RequiresUnreferencedCode` (RDC) is used to create `NativeAOT` [applications](https://docs.microsoft.com/en-us/dotnet/core/deploying/native-aot) and the attribute is used to warn the developer that runtime code generation is likely used by the application which is not supported in that deployment model. `NativeAOT` relies heavily on trimming and the RUC warnings.

**Comment by LakshanF** [comment]
The tests shown as failing seems to be passing - for example, at least the test [here](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-73977-merge-622b508d350e46849e/Microsoft.Extensions.Logging.Tests.Attempt.3/1/console.8bfd2cde.log?helixlogtype=result), and the failure seems to be related to a cloud issue where upload test run result XML is failing.

**Comment by tlakollo** [comment]
In the PR there are a couple of cases in which we suppress because the `RuntimeFeature.IsDynamicCodeSupported` flag is used, meaning the code has a way to execute the code when published using a tool that doesn't support DynamicCode. On the other hand RUC sometimes uses DynamicallyAccessedMembers to keep members around and making things safe which sometimes is not enough for DynamicCode purposes. The PR also annotates things that directly generate code dynamically ([example](https://github.com/dotnet/runtime/blob/68c0cde0ae9e4b4c9b75adf2a635e49f2e987337/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/CodeGenerator.cs#L132-L135)) and that piece of code is completely safe for Trimming purposes

**Pull request merged**
