### PR TITLE
Remove some IAsyncResult implementations from System.Net.Mail

### PR DESCRIPTION
**Pull request by stephentoub**
Whittling away at our remaining APM implementations.

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
nice. Do you plan to do rest of the Mail as well?  (at some point)

**Comment by stephentoub** [comment]
Ideally.  The rest is harder and more error-prone, though, so I'm hesitant to attempt it with our current test coverage.

**Comment by wfurt** [comment]
It has been on my wishlist for a long time. Maybe @filipnavara or others can help. We did talk about https://github.com/dotnet/runtime/issues/19436 specifically but I'm sure there may be more.

**Comment by filipnavara** [comment]
> It has been on my wishlist for a long time. Maybe @filipnavara or others can help. We did talk about #19436 specifically but I'm sure there may be more.

This one is very low on my list given the fact that the whole library is effectively deprecated. I have some cleanup PRs for System.Net.Security that I would like to resurrect in the .NET 8 timeframe but currently nothing for the Mail libraries.

**Comment by stephentoub** [comment]
> I have some cleanup PRs for System.Net.Security

There aren't any APM implementations remaining there, is there?

**Comment by filipnavara** [comment]
> > I have some cleanup PRs for System.Net.Security
> 
> There aren't any APM implementations remaining there, is there?

There's `NegotiateStream` but it already uses the `TaskToAsyncResult` pattern in all the places IIRC. I didn't mean that my cleanup are specific to APM. Sorry, should have made that clearer.

**Pull request merged**
