### PR TITLE
[mono][jit] Transition the x86 backend to use SSE for fp arithmetic.

### LINKED ISSUE #65557: [Android][x86] System.Runtime.InteropServices.Tests.NFloatTests failed
There are the following failures in the `System.Runtime.InteropServices.Tests.NFloatTests` library test suite which are being hit on Android x86 leg in https://github.com/dotnet/runtime/pull/65551:

```
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Subtraction(left: -4567, right: 3.1400001)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Subtraction" time="0.0140883" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: -4570.1400001049042\nActual:   -4570.14013671875]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Subtraction(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 244
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Subtraction(left: -4567.89111, right: 3.14568996)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Subtraction" time="0.0003036" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: -4571.0368032455444\nActual:   -4571.03662109375]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Subtraction(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 244
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Subtraction(left: 0, right: 3.1400001)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Subtraction" time="0.0000064" result="Pass" />
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Subtraction(left: 4567, right: -3.1400001)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Subtraction" time="0.0002445" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: 4570.1400001049042\nActual:   4570.14013671875]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Subtraction(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 244
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Subtraction(left: 4567.89111, right: -3.14568996)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Subtraction" time="0.000254" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: 4571.0368032455444\nActual:   4571.03662109375]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Subtraction(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 244
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Division(left: -4567, right: 3.1400001)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Division" time="0.0005455" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: -1454.4585501341485\nActual:   -1454.45849609375]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Division(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 284
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Division(left: -4567.89111, right: 3.14568996)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Division" time="0.000232" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: -1452.1110360937337\nActual:   -1452.111083984375]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Division(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 284
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Division(left: 0, right: 3.1400001)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Division" time="0.0000054" result="Pass" />
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Division(left: 4567, right: -3.1400001)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Division" time="0.0002909" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: -1454.4585501341485\nActual:   -1454.45849609375]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Division(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 284
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Division(left: 4567.89111, right: -3.14568996)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Division" time="0.0002319" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: -1452.1110360937337\nActual:   -1452.111083984375]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Division(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 284
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Addition(left: -4567, right: 3.1400001)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Addition" time="0.0005737" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: -4563.8599998950958\nActual:   -4563.85986328125]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Addition(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 224
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Addition(left: -4567.89111, right: 3.14568996)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Addition" time="0.0002292" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: -4564.7454233169556\nActual:   -4564.74560546875]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Addition(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 224
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Addition(left: 0, right: 3.1400001)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Addition" time="0.0000053" result="Pass" />
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Addition(left: 4567, right: -3.1400001)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Addition" time="0.0029769" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: 4563.8599998950958\nActual:   4563.85986328125]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Addition(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 224
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Addition(left: 4567.89111, right: -3.14568996)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Addition" time="0.0002373" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: 4564.7454233169556\nActual:   4564.74560546875]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Addition(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 224
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Multiply(left: -4567, right: 3.1400001)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Multiply" time="0.0005585" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: -14340.380479097366\nActual:   -14340.380859375]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Multiply(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 264
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Multiply(left: -4567.89111, right: 3.14568996)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Multiply" time="0.0002354" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: -14369.169233038556\nActual:   -14369.1689453125]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Multiply(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 264
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Multiply(left: 0, right: 3.1400001)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Multiply" time="0.0000054" result="Pass" />
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Multiply(left: 4567, right: -3.1400001)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Multiply" time="0.0020525" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: -14340.380479097366\nActual:   -14340.380859375]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Multiply(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 264
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
<test name="System.Runtime.InteropServices.Tests.NFloatTests.op_Multiply(left: 4567.89111, right: -3.14568996)" type="System.Runtime.InteropServices.Tests.NFloatTests" method="op_Multiply" time="0.0002333" result="Fail">
<failure exception-type="Xunit.Sdk.EqualException">
    <message><![CDATA[Assert.Equal() Failure\nExpected: -14369.169233038556\nActual:   -14369.1689453125]]></message>
    <stack-trace><![CDATA[   at System.Runtime.InteropServices.Tests.NFloatTests.op_Multiply(Single left, Single right) in /_/src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs:line 264
at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters)]]></stack-trace>
</failure>
</test>
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1620509&view=ms.vss-test-web.build-test-results-tab&runId=45058618&paneView=debug&resultId=166936

cc @steveisok @akoeplinger @tannergooding @vargaz

### PR DESCRIPTION
**Pull request by vargaz**
* Add SSE2 and FCMOV to the cpu requirements for mono on x86.
* Also force the usage of r4fp on x86, the same as on arm.
* Most of the code is copied from amd64-codegen.h and
  mini-amd64.c.

Fixes https://github.com/dotnet/runtime/issues/65557

### CODE REVIEW

**Comment by vargaz** [comment]
Todo:
* Compile the runtime itself with -msse2 -mfpmath=sse on x86
* Remove unused fp stack code
* Remove the old non-r4fp code

**Comment by vargaz** [comment]
Fixes https://github.com/dotnet/runtime/issues/65557

**Comment by akoeplinger** [comment]
Please also reenable the tests that were disabled with ActiveIssue in src/libraries/System.Runtime.InteropServices/tests/System.Runtime.InteropServices.UnitTests/System/Runtime/InteropServices/NFloatTests.cs

**Review by BrzVlad — APPROVED** [review]

**Comment by vargaz** [comment]
The android-x86 lane failures are relevant.

**Comment by vargaz** [comment]
The failures are fixed now. Should this be in 7.0 ?
@lambdageek

**Pull request merged**
