### PR TITLE
[RISC-V] Increase timeouts in System.Text.Json.Serialization.Tests.OptionsTests

### PR DESCRIPTION
**Pull request by sirntar**
Fixes tests in `System.Text.Json.Serialization.Tests.OptionsTests` that are using RemoteExecutor

For `rv64` (especially on QEMU/Debug) those tests requires a slightly longer timeouts due to overheat from RemoteExecutor.

Part of https://github.com/dotnet/runtime/issues/84834
cc @dotnet/samsung

### CODE REVIEW

**Comment by risc-vv** [comment]
<details><summary>25e9e821 is being scheduled for building and testing</summary>

GIT: `25e9e8214970b9478db90f77ad382f6781e1983c`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by risc-vv** [comment]
<details><summary>43beafe3 is being scheduled for building and testing</summary>

GIT: `43beafe36e5f23eacac2e03d0e61150c724a0ac9`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Review by tomeksowi — APPROVED** [review]

**Review by Bajtazar — APPROVED** [review]

**Comment by risc-vv** [comment]
<details><summary>61e6c390 is being scheduled for building and testing</summary>

GIT: `61e6c39006473366d7e1e3c14e1764507048a332`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by sirntar** [comment]
@jkotas @eiriktsarpalis Could you take a look on this PR? Thank you!

Yes, Its a similar case as in https://github.com/dotnet/runtime/pull/108879 - test uses `RemoteExecutor` which adds some overheat that causes test to fail due to a timeout. To my knowledge this doesn't affect any other architectures besides `rv64` - at least in this case.

**Comment by risc-vv** [comment]
<details><summary>1b14d962 is being scheduled for building and testing</summary>

GIT: `1b14d962aeed6ed96976867dc43a858802772eb3`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by jkotas** [comment]
There are two other RemoteExecutor tests in this file that do pretty much the same thing. Are those running fine?

**Comment by sirntar** [comment]
@jkotas You are right - in Release configuration, only this test shows a timeout problem, but after switching to Debug, almost all tests in OptionsTests that are using RemoteExecutor failed. Of course all those problems are only on rv64.  
I've changed that PR to address all those problems.

**Comment by risc-vv** [comment]
<details><summary>c520c953 is being scheduled for building and testing</summary>

GIT: `c520c953c5b19b85f25c3349a8150f981733cc00`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by jkotas** [comment]
> after switching to Debug

Are you testing Debug runtime (ie debug build of libcoreclr.so)?

We never run tests on Debug runtime. It is super slow. We only ever test Checked or Release runtime (ie checked or release build of libcoreclr.so).

**Comment by sirntar** [comment]
I usually test in Release/Checked config, but when I encounter potential problems, I switch to Debug. Yes, it's quite slow, so I only use this configuration for specific classes or methods when I need to get more information from the runtime.  

The original problem with `System.Text.Json.Serialization.Tests.OptionsTests.Options_RespectRequiredConstructorParameters_FeatureSwitch` was discovered on the Release configuration on the rv64 architecture. After your comment I switched to Debug to see if there would be problems with other RemoteExecutors in this class, as there were no more in Release configuration.

**Comment by sirntar** [comment]
Closed after https://github.com/dotnet/arcade/pull/15215 merge

**Pull request closed without merging**
