### PR TITLE
Increase default HostOptions.ShutdownTimeout value to 30 seconds

### LINKED ISSUE #63709: `Microsoft.Extensions.Hosting.HostOptions.ShutdownTimeout` default value of 5s is too short
The `HostOptions.ShutdownTimeout` value determines how long the host waits for services to gracefully terminate before initiating ungraceful termination.

The default value is currently 5 seconds, which is too short for many production applications. Processes in such applications often have state which needs to be stored in a database or responsibilities which need to be offloaded onto their surviving peers. Eg, consider a process which is the leader in a quorum of processes. It may take longer than 5s to reliably transfer leadership to a new leader before shutdown in that case.

Applications can never rely on graceful shutdown for continued correct operation, but this is a question of graceful shutdown.

In principle, the default `HostOptions.ShutdownTimeout` value should be long enough that functioning applications can shutdown gracefully and short enough that misbehaving processes do not prevent the application from functioning for too long. Both are subjective bounds, but **I suggest we change the default value to 30 seconds, in line with Kubernetes** (see `terminationGracePeriodSeconds` in the [reference docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/)):

> Optional duration in seconds the pod needs to terminate gracefully. May be decreased in delete request. Value must be non-negative integer. The value zero indicates delete immediately. If this value is nil, the default grace period will be used instead. The grace period is the duration in seconds after the processes running in the pod are sent a termination signal and the time when the processes are forcibly halted with a kill signal. Set this value longer than the expected cleanup time for your process. **Defaults to 30 seconds.**

Of course, this value is configurable, but we don't want developers to need to configure this value for typical applications. It's better to err towards the value being too high than too low (i.e, we shouldn't optimize for malfunctioning applications).

### PR DESCRIPTION
**Pull request by ReubenBond**
Fixes #63709

See the above for context.

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
I think this reasoning makes sense.

FYI @Tratcher @davidfowl, in case you have any objections.

**Comment by eerhardt** [comment]
Note that the WebHost still has a 5 second shutdown time out (which is where the generic Host got its default value from):

https://github.com/dotnet/aspnetcore/blob/2e66c71b8ae285bd5b142ad66fb3219f35fbe9dd/src/Hosting/Hosting/src/Internal/WebHostOptions.cs#L68

And just an FYI https://github.com/aspnet/Hosting/pull/1237 is the PR where the Host shutdown timeout was introduced.

**Comment by Tratcher** [comment]
This is a big jump and somewhat concerning. This can also affect dev inner-loop scenarios.

Ultimately it is subjective and app specific which is why it's configurable. Kubernetes is just one of many scenarios. I'm not sure of a constructive way to pick an appropriate default.

**Comment by eerhardt** [comment]
> This can also affect dev inner-loop scenarios.

Can you elaborate? When would a dev inner-loop scenario hang on shutdown? (beyond a dev mistake, which I'd assume they would want to correct sooner rather than later)

**Comment by davidfowl** [comment]
It really only affects inner loop scenarios when the app is hanging.

**Comment by Tratcher** [comment]
> It really only affects inner loop scenarios when the app is hanging.

Right, it's not uncommon to break your shutdown sequence when developing, we used to do it with kestrel all the time. Long running requests would cause a similar issue.

> If we're concerned about that we could change the defaults in dev vs non dev scenarios.

Please no, trying to distinguish environments or having multiple timeouts would only make this more complicated.

How do we decide if 30s is really a better value than 5s? Do we have any data about how long apps take to shut down?

**Comment by ReubenBond** [comment]
> How do we decide if 30s is really a better value than 5s? Do we have any data about how long apps take to shut down?

I laid out the principles behind picking a value in the original post. 5s is the outlier - a value of 30s-2min is more typical for a shutdown timeout. No firm data, but I work with teams internal and external and it's common for them to need to increase this to make things work smoothly on Kubernetes.

If an app is hanging on shutdown then it's better that it annoys developers during dev time rather than causing odd/ungraceful behavior in production. I agree that we should change that in templates for local dev (like we do for binding ports and the environment).

We should optimize towards:
* Correct apps work well in production
* Defects are apparent at dev/test time

**Comment by Tratcher** [comment]
> It's better to err towards the value being too high than too low (i.e, we shouldn't optimize for malfunctioning applications).

This is the main premise I want to push on. This limit exists precisely to catch malfunctioning apps and prevent them from having an outside impact. Yes, 5s is short, but how long is enough for the 50th or 90th percentile?

You picked 30s based on Kubernetes, but shouldn't we be slightly lower than their timeout so we can attempt a non-graceful shutdown before the container is killed? E.g. 20 or 25s?

I'm not going to block this any further, I just want to make sure we're not picking an arbitrary value, and that we don't keep changing it on a whim.

**Comment by maryamariyan** [comment]
Converting to draft until a consensus is made on the conversation here. 
@davidfowl @Tratcher what is the drawback in increasing this timeout?

**Review by Tratcher — APPROVED** [review]

**Pull request merged**
