### PR TITLE
Check that 'lvDoNotEnregister' is set as necessary. 

### LINKED ISSUE #49780: Assertion failed '!foundDiff' when an HFA local var is passed on stack
The following is a simple repro of an issue that a customer reported [here](https://github.com/dotnet/runtime/issues/49489#issuecomment-797204283) - reproduces on both linux-arm64 and win-arm64 on 3.1, 5.0 and 6.0.

```c#
using System;
using System.Runtime.CompilerServices;
using System.Numerics;

namespace Runtime_49489
{
    public class Program
    {
        [MethodImpl(MethodImplOptions.NoInlining)]
        static void Callee(float fltReg0, float fltReg1, float fltReg2, float fltReg3, float fltReg4, float fltReg5, float fltReg6, float fltReg7, Vector2 simd8)
        {
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void Caller(int i)
        {
            Vector2 simd8 = new Vector2();

            if (i > 0)
            {
                Callee(0, 0, 0, 0, 0, 0, 0, 0, simd8);
            }
        }

        static void Main(string[] args)
        {
            Caller(1);
        }
    }
}
```

Running the program with checked runtime and `COMPlus_TieredCompilation=0` would result in the following assertion

```
Assert failure(PID 4680 [0x00001248], Thread: 8804 [0x2264]): Assertion failed '!foundDiff' in 'Runtime_49489.Program:Caller(int)' during 'Linear scan register alloc' (IL size 59)

    File: F:\echesako\git\runtime4\src\coreclr\jit\lsra.cpp Line: 2260
    Image: F:\echesako\git\runtime4\artifacts\tests\coreclr\windows.arm64.Checked\Tests\Core_Root\CoreRun.exe
```

Note that if `if (i > 0)` is commented out or removed
```c#
            //if (i > 0)
            {
                Callee(0, 0, 0, 0, 0, 0, 0, 0, simd8);
            }
```

this will fail with a different assertion (on 5.0 and 6.0 but not 3.1)
```
Assert failure(PID 16692 [0x00004134], Thread: 18316 [0x478c]): Assertion failed '!fldVarDsc->lvIsInReg()' in 'Runtime_49489.Program:Caller(int)' during 'Generate code' (IL size 55)

    File: F:\echesako\git\runtime4\src\coreclr\jit\treelifeupdater.cpp Line: 337
    Image: F:\echesako\git\runtime4\artifacts\tests\coreclr\windows.arm64.Checked\Tests\Core_Root\CoreRun.exe
```

I attached two JIT dumps for the different failure modes.

[jitDump.un-cond.txt](https://github.com/dotnet/runtime/files/6159698/jitDump.un-cond.txt)
[jitDump.if-cond.txt](https://github.com/dotnet/runtime/files/6159699/jitDump.if-cond.txt)

cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by sandreenko**
In order to enable https://github.com/dotnet/runtime/issues/43867 by default we need to make sure that all structs that should be on the stack are marked as doNotEnreg. Currently, it is not very important because all structs are getting their 'doNotEnreg' just because they are structs. 

This PR adds check that after lowering we have correct `lvDoNotEnreg` flag on variables that are accessed via their address or via non-promoted fields or with both promoted and non-promoted accesses. 

If you see more contracts related to doNotEnreg that can be added - please comment. There are also many unclear parts about multi-reg nodes that I am going to address soon.

No diffs (all available spmi collections) as expected. 

Fixes https://github.com/dotnet/runtime/issues/49780 (change in rationalize RewriteSIMDIndir).

Contributes to https://github.com/dotnet/runtime/issues/43867, needed #53269 (phi store of long vars were not decomposed so the contract for them did not hold), #53067, #52803.

### CODE REVIEW

**Comment by sandreenko** [comment]
I think this is ready for review, PTAL @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
You can ignore the pgo failures, sorry about that.

**Review by AndyAyersMS — APPROVED** [review]
Perhaps consider adding a debug-only field that tracks the union of all the DNER settings for a local var, and adjust the dump info to show all reasons?

**Comment by sandreenko** [comment]
> Perhaps consider adding a debug-only field that tracks the union of all the DNER settings for a local var, and adjust the dump info to show all reasons?

Sound valuable, will add in one of the next changes.

**Pull request merged**
