### PR TITLE
[RISC-V] Disable robust mutexes in PAL on Qemu

### PR DESCRIPTION
**Pull request by yurai007**
Before this change due to https://gitlab.com/qemu-project/qemu/-/issues/2446 we get lot of System.Threading.Tests/System.IO.IsolatedStorage.Tests errors like:
```
System.Threading.Tests.MutexTests.AbandonExisting(name: "Local\\0908829282ce40db90b073ccd04b4c62", waitType: WaitAny, waitCount: 1, notAbandonedWaitIndex: 0, isNotAbandonedWaitObjectSignaled: False, abandonDuringWait: False) [FAIL]
      System.AggregateException : One or more errors occurred. (Not enough storage is available to process this command. : 'Local\0908829282ce40db90b073ccd04b4c62'. One or more system calls failed: pthread_mutex_init(...) == ENOTSUP/EOPNOTSUPP;)
      ---- System.IO.IOException : Not enough storage is available to process this command. : 'Local\0908829282ce40db90b073ccd04b4c62'. One or more system calls failed: pthread_mutex_init(...) == ENOTSUP/EOPNOTSUPP;
```
In this patch we force PAL to use file locks which fixes System.Threading.Tests/System.IO.IsolatedStorage.Tests on Qemu.

Part of https://github.com/dotnet/runtime/issues/84834, cc @dotnet/samsung

### CODE REVIEW

**Review by tomeksowi — APPROVED** [review]

**Comment by jkotas** [comment]
This change means that the runtime build for QEMU is going to be different from the regular runtime build. I am not sure we want to take this path. It is different from the earlier uses of `DOTNET_RUNNING_UNDER_QEMU` that just disabled specific tests on QEMU. It would eventually mean that QEMU needs its own RID (runtime identifier). Should this be a runtime check instead so that the same binary works both on QEMU and non-QEMU?

**Comment by risc-vv** [comment]
<details><summary>f28142d6 is being scheduled for building and testing</summary>

GIT: `f28142d61efb233688e8c0496cb2441cfdcdf4e2`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by risc-vv** [comment]
<details><summary>f28142d6 is being scheduled for building and testing</summary>

GIT: `f28142d61efb233688e8c0496cb2441cfdcdf4e2`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by yurai007** [comment]
> This change means that the runtime build for QEMU is going to be different from the regular runtime build. I am not sure we want to take this path. It is different from the earlier uses of `DOTNET_RUNNING_UNDER_QEMU` that just disabled specific tests on QEMU. It would eventually mean that QEMU needs its own RID (runtime identifier). Should this be a runtime check instead so that the same binary works both on QEMU and non-QEMU?

In alternative solution we may special-case only RISC-V and force cmake to perform robust mutex runtime checks on config time (without using hardcoded values from tryrun.cmake). Then I believe relying on Qemu shouldn't be long needed.

**Comment by kouvel** [comment]
> In alternative solution we may special-case only RISC-V and force cmake to perform robust mutex runtime checks on config time (without using hardcoded values from tryrun.cmake). Then I believe relying on Qemu shouldn't be longer needed.

Wouldn't that mean a build produced under QEMU would always use file locks instead of pthread robust mutexes? I wonder if we should include both the pthread robust mutex and file lock implementations into the build and choose one at runtime based on the not-supported error. Then regardless of how the build is produced it would have consistent behavior when running under QEMU or not.

**Comment by yurai007** [comment]
> Wouldn't that mean a build produced under QEMU would always use file locks instead of pthread robust mutexes? 

Given that https://gitlab.com/qemu-project/qemu/-/issues/2424 is really "won't fix" and assuming glibc _pthread_mutex_init_ implementation won't change much in nearest future I think answer is "yes" :) 

> I wonder if we should include both the pthread robust mutex and file lock implementations into the build and choose one at runtime based on the not-supported error. Then regardless of how the build is produced it would have consistent behavior when running under QEMU or not.

If I understand your idea correctly it would require PAL mutex adjustment, I think at least _PAL_CreateMutexW_. I can explore this direction and check if that's enough or require more work.

**Comment by risc-vv** [comment]
<details><summary>f28142d6 is being scheduled for building and testing</summary>

GIT: `f28142d61efb233688e8c0496cb2441cfdcdf4e2`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by risc-vv** [comment]
<details><summary>f28142d6 is being scheduled for building and testing</summary>

GIT: `f28142d61efb233688e8c0496cb2441cfdcdf4e2`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by risc-vv** [comment]
<details><summary>f28142d6 is being scheduled for building and testing</summary>

GIT: `f28142d61efb233688e8c0496cb2441cfdcdf4e2`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Review by sirntar — APPROVED** [review]
LGTM

**Comment by yurai007** [comment]
In _mutex.cpp_ pthread robust mutex code and file lock specific code are scattered across file. Choosing one at runtime instead compile time _NAMED_MUTEX_USE_PTHREAD_MUTEX_ macro need more adjustment than only in _InitializeProcessSharedRobustRecursiveMutex_/_NamedMutexSharedData_. I'm not convinced it's good idea. 
From the other hand change I meant previously would be something as simple as: https://github.com/yurai007/runtime/commit/ca004b10a3ea114cae3dfc2763a5799f96c7af56 which would force cmake to perform runtime checks on RISC-V excluding Tizen. It should have effect same as original PR change and doesn't need information about whether we are on Qemu.

**Comment by risc-vv** [comment]
<details><summary>f28142d6 is being scheduled for building and testing</summary>

GIT: `f28142d61efb233688e8c0496cb2441cfdcdf4e2`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

**Comment by kouvel** [comment]
> In _mutex.cpp_ pthread robust mutex code and file lock specific code are scattered across file. Choosing one at runtime instead compile time _NAMED_MUTEX_USE_PTHREAD_MUTEX_ macro need more adjustment than only in _InitializeProcessSharedRobustRecursiveMutex_/_NamedMutexSharedData_.

Yes, it would involve switching a number of compile-time checks to run-time checks such that both implementations are included in the build on Linux.

> From the other hand change I meant previously would be something as simple as: [yurai007@ca004b1](https://github.com/yurai007/runtime/commit/ca004b10a3ea114cae3dfc2763a5799f96c7af56) which would force cmake to perform runtime checks on RISC-V excluding Tizen. It should have effect same as original PR change and doesn't need information about whether we are on Qemu.

With that it sounds like a build produced under QEMU would differ in behavior from a build produced on similar non-emulated hardware, as the former would use the file lock implementation and the latter would use pthread robust mutex. Ideally, the produced build should have consistent behavior. For instance, it would be problematic to use QEMU to cross-build a patch and apply it on non-emulated hardware, if the shipped binaries were produced on non-emulated hardware. Maybe this kind of issue already exists to some degree, but perhaps it should be fixed.

A safer approach may be to always use the file lock implementation based on arch, but that would be unfortunate, as it's less efficient. It's also very difficult to change the behavior between releases for compat reasons. I'm still favoring run-time checks over build-time checks.

**Comment by yurai007** [comment]
> With that it sounds like a build produced under QEMU would differ in behavior from a build produced on similar non-emulated hardware, as the former would use the file lock implementation and the latter would use pthread robust mutex. Ideally, the produced build should have consistent behavior. For instance, it would be problematic to use QEMU to cross-build a patch and apply it on non-emulated hardware, if the shipped binaries were produced on non-emulated hardware. Maybe this kind of issue already exists to some degree, but perhaps it should be fixed.

Thanks, now with this explanation solution based on run-time checks makes more sense to me.

**Comment by BruceForstall** [comment]
@kouvel  @yurai007 Based on the above conversation, can this PR be closed? (It sounds like a new, different, dynamic checking implementation would be preferred.)

**Pull request closed without merging**
