### PR TITLE
Use AVX512 intrinsics for number conversion when possible

### PR DESCRIPTION
**Pull request by martinothamar**
This PR implements AVX512DQ intrinsics where possible for converting integers to floating points and vice versa.

Usecase: I had been working on vectorized PRNGs [in my Fast.PRNGs .NET library](https://github.com/martinothamar/Fast.PRNGs.NET) and [in my simd-rand Rust library](https://github.com/martinothamar/simd-rand). I was unable to match the performance in the Rust implementation partially due to uint64 -> double conversion being slower (when running on hardware with AVX512).

I did also search for related issues, where I found this: #85207. I think this fixes the first few bullet points there.

I benchmarked with disasm for a ulong -> double Vector256 conversion which seems to look good. I used a modified Vector256 version of this benchmark: https://github.com/dotnet/performance/blob/981a1a6730a5c54b3292428690ac9948e68c4823/src/benchmarks/micro/libraries/System.Runtime.Intrinsics/Perf_Vector128.cs#L36
My only modification was not using a `static readonly` field to convert in the benchmark method, rather initializing a member field in a `GlobalSetup` method using random values (it had some small effect on the generated code). I noticed an open issue relating to the benchmarking setup: https://github.com/dotnet/performance/issues/2555. I could contribute benchmarks for wider vectors, but when doing conversion in a loop I struggled and didn't manage to avoid some dead code elimination to mess up the generated code, so the benchmarks would look pretty similar to the current 128bit ones, aside from the static data. Is there a good way to try to prevent these types of compiler optimizations from benchmark code? Something like the [black_box](https://doc.rust-lang.org/stable/std/hint/fn.black_box.html) intrinsic in Rust, or inline asm tricks commonly used in C/C++

# Benchmarks

## .NET 8.0.0 (8.0.23.32907), X64 RyuJIT AVX2
```assembly
; System.Runtime.Intrinsics.Tests.Perf_Vector256.ConvertULongToDoubleBenchmark()
       vzeroupper
       vmovups   ymm0,[rdi+8]
       vpblendd  ymm1,ymm0,[7F9E757F1580],0AA
       vpsrlq    ymm0,ymm0,20
       vpxor     ymm0,ymm0,[7F9E757F15A0]
       vsubpd    ymm0,ymm0,[7F9E757F15C0]
       vaddpd    ymm0,ymm0,ymm1
       vmovups   [rsi],ymm0
       mov       rax,rsi
       vzeroupper
       ret
; Total bytes of code 54
```

```

BenchmarkDotNet v0.13.7-nightly.20230717.35, Ubuntu 22.04.2 LTS (Jammy Jellyfish)
11th Gen Intel Core i7-11800H 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.100-preview.6.23330.14
  [Host]     : .NET 8.0.0 (8.0.23.32907), X64 RyuJIT AVX2
  Job-JPWDTA : .NET 8.0.0 (8.0.23.32907), X64 RyuJIT AVX2

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:EnableUnsafeBinaryFormatterSerialization=true  IterationTime=250.0000 ms  
MaxIterationCount=20  MinIterationCount=15  WarmupCount=1  

```
|                        Method |      Mean |     Error |    StdDev |    Median |       Min |       Max | Code Size | Allocated |
|------------------------------ |----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|
| ConvertULongToDoubleBenchmark | 0.2772 ns | 0.0546 ns | 0.0628 ns | 0.2719 ns | 0.1851 ns | 0.4117 ns |      54 B |         - |

## .NET 8.0.0 (42.42.42.42424), X64 RyuJIT AVX2
```assembly
; System.Runtime.Intrinsics.Tests.Perf_Vector256.ConvertULongToDoubleBenchmark()
       vzeroupper
       vcvtuqq2pd ymm0,[rdi+8]
       vmovups   [rsi],ymm0
       mov       rax,rsi
       vzeroupper
       ret
; Total bytes of code 24
```

```

BenchmarkDotNet v0.13.7-nightly.20230717.35, Ubuntu 22.04.2 LTS (Jammy Jellyfish)
11th Gen Intel Core i7-11800H 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.100-preview.6.23330.14
  [Host]     : .NET 8.0.0 (8.0.23.32907), X64 RyuJIT AVX2
  Job-ASZUPG : .NET 8.0.0 (42.42.42.42424), X64 RyuJIT AVX2

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:EnableUnsafeBinaryFormatterSerialization=true  Toolchain=CoreRun  
IterationTime=250.0000 ms  MaxIterationCount=20  MinIterationCount=15  
WarmupCount=1  

```
|                        Method |      Mean |     Error |    StdDev |    Median |    Min |       Max | Code Size | Allocated |
|------------------------------ |----------:|----------:|----------:|----------:|-------:|----------:|----------:|----------:|
| ConvertULongToDoubleBenchmark | 0.0277 ns | 0.0251 ns | 0.0289 ns | 0.0218 ns | 0.0 ns | 0.0868 ns |      24 B |         - |

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet/avx512-contrib

**Comment by martinothamar** [comment]
I guess this could be done in the JIT as well? Not sure what is preferred/intended https://github.com/dotnet/runtime/blob/08a6e06d8fdc29efebc5c0ec7d2b6ba215810e71/src/coreclr/jit/simdashwintrinsic.cpp#L533-L545

**Review by adamsitnik — APPROVED** [review]
Overall it looks good to me, thank you for your contribution @martinothamar!

**Comment by tannergooding** [comment]
I'd prefer this to be in the JIT so that a mainline path (which compiles down to 1 instruction) doesn't end up pessimized by inlining heuristics

**Comment by adamsitnik** [comment]
> I'd prefer this to be in the JIT so that a mainline path (which compiles down to 1 instruction) doesn't end up pessimized by inlining heuristics

@tannergooding could you please provide some hints about how to achieve that? Like links to some sample code that does that for one simple instruction?

**Comment by martinothamar** [comment]
> I'd prefer this to be in the JIT so that a mainline path (which compiles down to 1 instruction) doesn't end up pessimized by inlining heuristics

Makes sense, I'll have a look some time this week 👍

**Comment by martinothamar** [comment]
Started on #93896, does that look like the right approach?

**Pull request closed without merging**
