### PR TITLE
Add Socket.UseOnlyOverlappedIO functionality (#34458)

### PR DESCRIPTION
**Pull request by AhmedMostafa16**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47151) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47151) before we can accept your contribution.<br/><br/>:x: AhmedMostafa16 [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=47151)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=47151) it.</sub>

**Comment by antonfirsov** [comment]
@AhmedMostafa16 `UseOnlyOverlappedIO` was used on .NET Framework to force-disable IOCP and enforce using Win32 event handles for asynchronous IO instead. This was achieved by setting `BaseOverlappedAsyncResult.m_UseOverlappedIO == true` when `Socket.UseOnlyOverlappedIO == true`:
https://referencesource.microsoft.com/#System/net/System/Net/Sockets/_BaseOverlappedAsyncResult.cs,fa657f0bd7ce6a95,references

.NET Core / .NET 5 asynchronous Windows sockets are entirely IOCP-based, therefore this property lost it's meaning. Just putting back the backing field is not sufficient to bring back the original semantics. We would need a refactor to reintroduce the old event-based logic. This would be a Windows-specific feature with very limited usage, so it's definitely not something we want in .NET 6.

**Comment by karelz** [comment]
Note that the tracking issue #34458 explains the goal is to update comment, not to bring back functionality (which @antonfirsov explains about in detail).

**Comment by AhmedMostafa16** [comment]
Ok

**Pull request closed without merging**
