### PR TITLE
[Ppc64le] bug fixes

### PR DESCRIPTION
**Pull request by alhad-deshpande**
This PR fixes below things:

1. g_assert mentioned in github issue [71080](https://github.com/dotnet/runtime/issues/71080)
2. Test case failures occurring on CICD pipeling due to incorrect instruction length of tailcall.
3. Corrections in instruction lengths for all opcodes in which new memory patch thunking has been impemented.

### CODE REVIEW

**Comment by carlossanlop** [comment]
@alhad-deshpande RC1 changes need a fix in main first. Was this done already? If not, please close this PR, send a PR to main first, then you can backport it with the help of the bot (ping me and I can help you).

**Comment by carlossanlop** [comment]
Oh I see the `main` PR got merged. But this one did not get automatically backported by the maestro bot.

@akoeplinger @lewing can you please manually review this PR, since it's not a direct backport?

**Comment by carlossanlop** [comment]
There were failures in `runtime-community`. Please help confirm if they are related to this change.

**Comment by akoeplinger** [comment]
The failures are unrelated.

**Review by akoeplinger — APPROVED** [review]

**Comment by carlossanlop** [comment]
Thanks for the sign-off @akoeplinger. Now I just need approval from @lewing.

I am pausing merges right now, in favor of getting the [7-rc1->7 PR merged](https://github.com/dotnet/runtime/pull/74045) without any more changes (the bot autocommits anything merged to rc1, and restarts the CI).

**Review by lewing — APPROVED** [review]
Lgtm

**Comment by carlossanlop** [comment]
The [7.0-rc1 -> 7.0 PR](https://github.com/dotnet/runtime/pull/74045) was merged, so now we're unblocked to merge this.
Approved and signed-off.
CI failures are unrelated.
Ready to merge. :shipit:

**Comment by alhad-deshpande** [comment]
@carlossanlop @lewing @akoeplinger 
Thanks for merging this PR into RC1 branch. But I dont see similar PR [74058](https://github.com/dotnet/runtime/pull/74058) raised against main yet merged. So I think RC1 has these changes which are not yet in main. 

The PR [73616](https://github.com/dotnet/runtime/pull/73616) was for memory thunking and those changes are already there in RC1 branch. 


Can you please merge PR [74058](https://github.com/dotnet/runtime/pull/74058) into main so that both the branches are at par?

**Comment by akoeplinger** [comment]
@alhad-deshpande I merged #74058, thanks!

**Comment by alhad-deshpande** [comment]
@rzikm @akoeplinger 
Did not understood why issue PR [74484](https://github.com/dotnet/runtime/pull/74484) got tagged. Is this got tagged mistakenly?

**Comment by akoeplinger** [comment]
@alhad-deshpande yeah it was inadvertently mentioned in the PR description of that PR, no worries.

**Comment by alhad-deshpande** [comment]
@akoeplinger 
Thanks for the confirmation.

**Comment by rzikm** [comment]
> @rzikm @akoeplinger Did not understood why issue PR [74484](https://github.com/dotnet/runtime/pull/74484) got tagged. Is this got tagged mistakenly?

Yes, it mistakenly created the PR against different base and it tagged lots of people for review and lots of PRs 🤦

**Pull request merged**
