### PR TITLE
JIT: tail merge returns with multiple statements

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Remove the restriction that a mergeable return have one statement.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL
cc @dotnet/jit-contrib 

Like #109661, I spotted this when I was experimenting with a very early flow opts pass. Seems to have good diffs. There are some cases now where we'll jump to a `ret`, but that sort of thing should be handled later on, once we have an idea how big the epilogs can be.

**Review by EgorBo — APPROVED** [review]
I remember that I wanted to relax it in a follow up PR after that change, but forgot 🙂

**Comment by EgorBo** [comment]
the diffs look nice, but I guess the CI failure is related? I don't recall it when I was disabling it

**Comment by AndyAyersMS** [comment]
> the diffs look nice, but I guess the CI failure is related? I don't recall it when I was disabling it.
> 
> Looks like tail call related

Yes, they are quite likely related.

**Comment by AndyAyersMS** [comment]
> > the diffs look nice, but I guess the CI failure is related? I don't recall it when I was disabling it.
> > Looks like tail call related
> 
> Yes, they are quite likely related.

It's because X86 does not set `FEATURE_TAILCALL_OPT` and so does not set `FEATURE_TAILCALL_OPT_SHARED_RETURN` and so can't handle having a block with a (nonrecursive) tail call branch to a return block.

Not sure why x86 is special here, but assuming it needs to be this way, I can just use the old logic for x86, or check if the statement before the return is a tail call candidate, and defer merging if so.

FYI @jakobbotsch

**Comment by AndyAyersMS** [comment]
> > > the diffs look nice, but I guess the CI failure is related? I don't recall it when I was disabling it.
> > > Looks like tail call related
> > 
> > 
> > Yes, they are quite likely related.
> 
> It's because X86 does not set `FEATURE_TAILCALL_OPT` and so does not set `FEATURE_TAILCALL_OPT_SHARED_RETURN` and so can't handle having a block with a (nonrecursive) tail call branch to a return block.
> 
> Not sure why x86 is special here, but assuming it needs to be this way, I can just use the old logic for x86, or check if the statement before the return is a tail call candidate, and defer merging if so.
> 
> FYI @jakobbotsch

I ended up not splitting returns from any tail call as there is a fair bit of twisty logic in morph that expects certain shapes.

**Pull request merged**
