### PR TITLE
Add test for boxing byreflike fail.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
/cc @AlekseyTs @elinor-fung @lambdageek @fanyang-mono

### CODE REVIEW

**Comment by AlekseyTs** [comment]
I am also curious if the following going to be considered a valid IL for `Test1` method:
```
{
  // Code size       41 (0x29)
  .maxstack  1
  .locals init (T V_0) //t
  IL_0000:  ldarg.0
  IL_0001:  isinst     ""T""
  IL_0006:  brfalse.s  IL_0022
  IL_0008:  ldarg.0
  IL_0009:  isinst     ""T""
  IL_000e:  unbox.any  ""T""
  IL_0013:  stloc.0
  IL_0014:  ldloca.s   V_0
  IL_0016:  constrained. ""T""
  IL_001c:  callvirt   ""void I1.M()""
  IL_0021:  ret
  IL_0022:  ldc.i4.2
  IL_0023:  call       ""void System.Console.Write(int)""
  IL_0028:  ret
}
```

```
class Helper1<T>
    where T : I1, allows ref struct
{
    public static void Test1(I1 h1)
    {
        if (h1 is T t)
        {
            t.M();
        }
        else
        {
            System.Console.Write(2);
        }
    }
}
ref struct S : I1
{
    public void M()
    {
        System.Console.Write(3);
    }
}

interface I1
{
    void M();
}

class Program : I1
{
    static void Main()
    {
        Helper1<S>.Test1(new Program());
        Helper1<Program>.Test1(new Program());
    }

    public void M()
    {
        System.Console.Write(1);
    }
}
``` 

The behavior of IL is reasonable, but sequences `isinst ; unbox.any` and `isinst ; br_true/false` aren't explicitly listed as supported. However, `box ; isinst ; unbox.any ` and `box ; isinst ; br_true/false` are listed as supported at https://github.com/dotnet/runtime/blob/main/docs/design/features/byreflike-generics.md#special-il-sequences.

This is not an ask from compiler to support an IL like that.

**Comment by AaronRobinsonMSFT** [comment]
> I am also curious if the following going to be considered a valid IL for Test1 method:

I will validate those sequences today.

> The behavior of IL is reasonable, but sequences isinst ; unbox.any and isinst ; br_true/false aren't explicitly listed as supported.

@AlekseyTs Correct. The JIT only specifically recognizes sequences in this area that begin with `CEE_BOX`. See https://github.com/dotnet/runtime/blob/56ee7c5950b55529c2b5618d8f9b796d1b425813/src/coreclr/jit/importer.cpp#L2829-L2848

> This is not an ask from compiler to support an IL like that.

Understood.

**Comment by fanyang-mono** [comment]
https://github.com/dotnet/runtime/pull/101509 should fix the current mono test failures.

**Comment by AaronRobinsonMSFT** [comment]
> I am also curious if the following going to be considered a valid IL for Test1 method:

@AlekseyTs Yes, that is valid. I've also added a test for that case.

**Comment by AaronRobinsonMSFT** [comment]
@lambdageek @fanyang-mono @steveisok Please take a look. The CI is now green.

**Review by fanyang-mono — APPROVED** [review]
LGTM!

**Pull request merged**
