### PR TITLE
Fix signature for 64-bit delegate profiling helper

### LINKED ISSUE #74295: F# compiler crashes with DOTNET_TieredPGO=1
When I try to compile https://github.com/giraffe-fsharp/Giraffe using F# compiler compiled with .NET 7.0P7 I get:
```
Fatal error. Internal CLR error. (0x80131506)
   at Internal.Utilities.FSharpEnvironment.get_FSharpProductName()
   at FSharp.Compiler.CompilerConfig+TcConfigBuilder.CreateNew(FSharp.Compiler.CodeAnalysis.LegacyReferenceResolver, System.String, ReduceMemoryFlag, System.String, Boolean, Boolean, CopyFSharpCoreFlag, Microsoft.FSharp.Core.FSharpFunc`2<System.Tuple`2<System.String,System.DateTime>,Microsoft.FSharp.Core.FSharpOption`1<System.Tuple`3<System.Object,IntPtr,Int32>>>, Microsoft.FSharp.Core.FSharpOption`1<System.String>, FSharp.Compiler.Text.Range)
   at FSharp.Compiler.Driver.main1(Internal.Utilities.Library.CompilationThreadToken, System.String[], FSharp.Compiler.CodeAnalysis.LegacyReferenceResolver, Boolean, ReduceMemoryFlag, CopyFSharpCoreFlag, Exiter, DiagnosticsLoggerProvider, DisposablesTracker)
   at FSharp.Compiler.Driver.CompileFromCommandLineArguments(Internal.Utilities.Library.CompilationThreadToken, System.String[], FSharp.Compiler.CodeAnalysis.LegacyReferenceResolver, Boolean, ReduceMemoryFlag, CopyFSharpCoreFlag, Exiter, DiagnosticsLoggerProvider, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<TcImports,Microsoft.FSharp.Core.Unit>>, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<System.Tuple`4<TcConfig,TcGlobals,System.String,ILModuleDef>,Microsoft.FSharp.Core.Unit>>)
   at FSharp.Compiler.CommandLineMain.main(System.String[])
```
Does not reproduce when `DOTNET_TieredPGO` is disabled (its default value)

### PR DESCRIPTION
**Pull request by jakobbotsch**
I missed updating the signature of the 64-bit variant here when the
vtable and delegate profiling helpers were originally split up.

Fix #74295

### CODE REVIEW

**Comment by jakobbotsch** [comment]
I've added a `JitRandomlyCollect64BitCounts` and turned it on in the randomized PGO legs to get some testing for this mode.

cc @dotnet/jit-contrib PTAL @EgorBo @AndyAyersMS

**Review by EgorBo — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Bunch of the runs seem to have been "dead-lettered".. will retry

**Comment by markples** [comment]
Would it be worth devising a way for the compiler to assert that it has the right types (or at least number) of arguments for helper calls?  Presumably these issues are going to be caught by normal testing, so it would be more a productivity thing, so is this kind of issue common?

**Comment by JulieLeeMSFT** [comment]
@jakobbotsch are we going to backport this to 7.0?

**Comment by jakobbotsch** [comment]
> @jakobbotsch are we going to backport this to 7.0?

Yes, I will backport this one.

**Pull request merged**
