### PR TITLE
WIP: [test-only, not for merge] Signing in PR runs + revert 31807

### PR DESCRIPTION
**Pull request by trylek**
This experiment will successfully complete if the PR job fails :-).

### CODE REVIEW

**Review by dagood — APPROVED** [review]
Looks good as a test. (For https://github.com/dotnet/runtime/pull/31926)

**Comment by trylek** [comment]
@dagood - could you please double-check that the failures in the installer jobs match your expectations when you have a chance?

**Comment by dagood** [comment]
Yep, perfect! Thanks.

**Comment by ViktorHofer** [comment]
@trylek I think we can close this now?

**Comment by trylek** [comment]
For sure, thanks for reminding me.

**Pull request closed without merging**
