### PR TITLE
[ppc64le] Performance improvements while branching during function calls

### PR DESCRIPTION
**Pull request by alhad-deshpande**
Performance improvements has been made while branching during function calls by using bcctrl instruction instead of blrl instruction.

### CODE REVIEW

**Comment by directhex** [comment]
green on ppc

**Review by vargaz — APPROVED** [review]

**Comment by alhad-deshpande** [comment]
@vargaz  @directhex
Opened up PR https://github.com/dotnet/runtime/pull/90656 for backporting to release/8.0-rc1 branch.

**Comment by vargaz** [comment]
Why did the auto backport fail ?

**Pull request merged**
