### PR TITLE
JIT: remove inlining restriction for some methods that throw

### LINKED ISSUE #2156: Possible JIT inlining optimization: removing multiple argument null checks
Would it make sense for the JITer to eliminate redundant "if null then throw" (i.e. `if (arg == null) throw Exception();`) checks for a given argument if it is not possible for that argument value to have changed between the checks? As far as I can tell this does not currently happen, even for simple cases.

For example:
```c#
void M1(string value) => M2(value ?? throw new ArgumentNullException();

[MethodImpl(MethodImplOptions.AggressiveInlining)]
void M2(string value) => M3(value ?? throw new ArgumentNullException();

[MethodImpl(MethodImplOptions.AggressiveInlining)]
void M3(string value) => M4(value ?? throw new ArgumentNullException();

[MethodImpl(MethodImplOptions.AggressiveInlining)]
void M4(string value)
{
    if (value == null)
        throw new ArgumentNullException();
}

// After inlining M1 effectively becomes:

void M1(string value)
{
    if (value == null) throw new ArgumentNullException();
    // These can be removed:
    if (value == null) throw new ArgumentNullException();
    if (value == null) throw new ArgumentNullException();
    if (value == null) throw new ArgumentNullException();
}

```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
We were blocking inlines for methods that throw with more than one thing on the
evaluation stack. There was already logic for the non-inlining case to flush
the stack and preserve pending side effects. So we can simply remove the
inlining restriction.

Fixes #2156.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

PMI diffs shows a few cases where inlining is unblocked; all cause code size increases.
```
PMI CodeSize Diffs for System.Private.CoreLib.dll, framework assemblies for x64 default jit
Summary of Code Size diffs:
(Lower is better)
Total bytes of diff: 566 (0.00% of base)
    diff is a regression.
Top file regressions (bytes):
         180 : System.Composition.AttributedModel.dasm (29.80% of base)
         161 : System.Private.CoreLib.dasm (0.00% of base)
         133 : System.Security.Cryptography.Pkcs.dasm (0.03% of base)
          63 : System.DirectoryServices.Protocols.dasm (0.07% of base)
          29 : System.Runtime.Numerics.dasm (0.04% of base)
5 total files with Code Size differences (0 improved, 5 regressed), 160 unchanged.
Top method regressions (bytes):
         161 (22.39% of base) : System.Private.CoreLib.dasm - CustomAttributeData:get_NamedArguments():IList`1:this
         133 (36.34% of base) : System.Security.Cryptography.Pkcs.dasm - PkcsHelpers:DeepCopy(CmsRecipientCollection):CmsRecipientCollection
          96 (457.14% of base) : System.Composition.AttributedModel.dasm - SharedAttribute:.ctor(String):this
          84 (400.00% of base) : System.Composition.AttributedModel.dasm - SharedAttribute:.ctor():this
          63 (14.58% of base) : System.DirectoryServices.Protocols.dasm - AddRequest:.ctor(String,String):this
          29 ( 7.67% of base) : System.Runtime.Numerics.dasm - BigNumber:HexNumberToBigInteger(byref,byref):bool
Top method regressions (percentages):
          96 (457.14% of base) : System.Composition.AttributedModel.dasm - SharedAttribute:.ctor(String):this
          84 (400.00% of base) : System.Composition.AttributedModel.dasm - SharedAttribute:.ctor():this
         133 (36.34% of base) : System.Security.Cryptography.Pkcs.dasm - PkcsHelpers:DeepCopy(CmsRecipientCollection):CmsRecipientCollection
         161 (22.39% of base) : System.Private.CoreLib.dasm - CustomAttributeData:get_NamedArguments():IList`1:this
          63 (14.58% of base) : System.DirectoryServices.Protocols.dasm - AddRequest:.ctor(String,String):this
          29 ( 7.67% of base) : System.Runtime.Numerics.dasm - BigNumber:HexNumberToBigInteger(byref,byref):bool
6 total methods with Code Size differences (0 improved, 6 regressed), 244490 unchanged.
```
SPMI shows one beneficial inline:
```
         -63 (-12.73% of base) : 377923.dasm - System.DirectoryServices.Protocols.AddRequest:.ctor(System.String,System.String):this
```

**Comment by briansull** [comment]
If you gather PerfScore diffs on this chnage there shouldn't be regressions, as the block is marked as RarelyRun (with a weight of zero).   The cost will be reduced to a very small amount based upon the codesize:

```
emit.h:1321:#define PERFSCORE_CODESIZE_COST_HOT 0.10f
emit.h:1322:#define PERFSCORE_CODESIZE_COST_COLD 0.01f
```

**Comment by AndyAyersMS** [comment]
This change allows inlining of some methods with conditional throws.  The throw block will be rarely run, but the rest of the inlined method won't be. So perf scores end up higher too.
```
Summary of Perf Score diffs:
(Lower is better)

Total PerfScoreUnits of diff: 84.47 (0.00% of base)
    diff is a regression.

Top file regressions (PerfScoreUnits):
       30.50 : System.Composition.AttributedModel.dasm (15.91% of base)
       21.30 : System.Security.Cryptography.Pkcs.dasm (0.02% of base)
       19.10 : System.Private.CoreLib.dasm (0.00% of base)
        7.80 : System.DirectoryServices.Protocols.dasm (0.02% of base)
        5.77 : System.Runtime.Numerics.dasm (0.02% of base)

5 total files with Perf Score differences (0 improved, 5 regressed), 160 unchanged.

Top method regressions (PerfScoreUnits):
       21.30 (10.89% of base) : System.Security.Cryptography.Pkcs.dasm - PkcsHelpers:DeepCopy(CmsRecipientCollection):CmsRecipientCollection
       19.10 ( 4.38% of base) : System.Private.CoreLib.dasm - CustomAttributeData:get_NamedArguments():IList`1:this
       17.10 (259.09% of base) : System.Composition.AttributedModel.dasm - SharedAttribute:.ctor(String):this
       13.40 (203.03% of base) : System.Composition.AttributedModel.dasm - SharedAttribute:.ctor():this
        7.80 ( 7.75% of base) : System.DirectoryServices.Protocols.dasm - AddRequest:.ctor(String,String):this
        5.77 ( 3.22% of base) : System.Runtime.Numerics.dasm - BigNumber:HexNumberToBigInteger(byref,byref):bool

Top method regressions (percentages):
       17.10 (259.09% of base) : System.Composition.AttributedModel.dasm - SharedAttribute:.ctor(String):this
       13.40 (203.03% of base) : System.Composition.AttributedModel.dasm - SharedAttribute:.ctor():this
       21.30 (10.89% of base) : System.Security.Cryptography.Pkcs.dasm - PkcsHelpers:DeepCopy(CmsRecipientCollection):CmsRecipientCollection
        7.80 ( 7.75% of base) : System.DirectoryServices.Protocols.dasm - AddRequest:.ctor(String,String):this
       19.10 ( 4.38% of base) : System.Private.CoreLib.dasm - CustomAttributeData:get_NamedArguments():IList`1:this
        5.77 ( 3.22% of base) : System.Runtime.Numerics.dasm - BigNumber:HexNumberToBigInteger(byref,byref):bool

6 total methods with Perf Score differences (0 improved, 6 regressed), 244490 unchanged.
```

**Review by sandreenko — APPROVED** [review]
LGTM

**Review by briansull — APPROVED** [review]
LGTM

**Pull request merged**
