### PR TITLE
[wasm] Fix support for debugging wasm debugger tests with VSCode

### PR DESCRIPTION
**Pull request by radical**
Screen Shot 2022-10-17 at 11 10 06 PM

### CODE REVIEW

**Comment by radical** [comment]
@thaystg @ilonatommy I haven't tried this on windows, could you please do that?

**Comment by ilonatommy** [comment]
So far I checked running the tests from VSCode's Poweshell and it has changed. After setting the `RunSettingsFilePath` `dotnet.sh/cmd` is expected to reside in one of the paths specified in `DebuggerTestSuite.csproj`, e.g. `\artifacts\obj\vscode\`. Thus, running 

```
./dotnet.cmd test src/mono/wasm/debugger/DebuggerTestSuite --filter DebuggerTests.EvaluateOnCallFrameTests.EvaluateStaticLocalsWithDeepMemberAccess -e RuntimeConfiguration=Debug -e Configuration=Debug -e DebuggerHost=chrome > out.txt
```
that worked before does not work anymore, from the `vscode` dir in artifacts neither:
`./../../../dotnet.cmd test ../../../src/mono/wasm/debugger/DebuggerTestSuite ....etc`

```
Failed to launch testhost with error: System.IO.FileNotFoundException: Path does not exist: runtime-fork\artifacts\obj\vscode\dotnet.exe
File name: 'runtime-fork\artifacts\obj\vscode\dotnet.exe'
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.ProcessHelper.LaunchProcess(String processPath, String arguments, String workingDirectory, IDictionary`2 envVariables, Action`2 errorCallback, Action`1 exitCallBack, Action`2 outputCallBack)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchHost(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.LaunchTestHostAsync(TestProcessStartInfo testHostStartInfo, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings)
```

I cannot come with a workaround, it might be something simple but what about adding some info [here](https://github.com/radical/runtime/blob/wasm-debugger-tests-debug/src/mono/wasm/debugger/README.md) if any additional steps are needed now, to avoid confusion?

**Comment by radical** [comment]
I will fix invoking it from the shell. Are you able to run a test by "run test" or "debug test" shown over a test?

**Comment by radical** [comment]
I meant this: 
Screen Shot 2022-10-18 at 4 33 58 PM

**Review by thaystg — APPROVED** [review]

**Review by lewing — APPROVED** [review]

**Pull request merged**
