### PR TITLE
FIX ConfigurationBinder resets sub objects stored in dictionaries

### LINKED ISSUE #96682: Net8: ConfigurationBinder resets sub objects stored in dictionaries to default for json defined empty objects
### Description

In my use case i have some POCO `Options` objects stored in a string keyed dictionary:
```
class RootOptions
{
    public MainOptions MainOptions { get; } = new();
}
class MainOptions
{
    public Dictionary<string, ChildOptions> Dic { get; } = new();
    public string Prop { get; set; } = "default";
}
class ChildOptions
{
    public string Prop1 { get; set; } = "default";
    public string Prop2 { get; set; } = "default";
}
```

in an early stage of program initialization, i have some hardcoded children objects to provide a default "configuration":
```
private static RootOptions CreateHardcodedOptions()
{
    var opts = new RootOptions();
    opts.MainOptions.Dic["child1"] = new()
    {
        Prop1 = "hardcoded",
        Prop2 = "hardcoded",
    };
    opts.MainOptions.Dic["child2"] = new()
    {
        Prop1 = "hardcoded",
        Prop2 = "hardcoded",
    };
    return opts;
}
```

then i use `ConfigurationBinder` to override some children props and/or add new children based on json configuration files...
```
var opts = CreateHardcodedOptions();
var cfg = new ConfigurationBuilder()
    .AddJsonFile("xxx.json")
    .Build();
cfg.Bind(opts);
```

The problem arises when in the json file i have empty json objects that match the string key of an existing hardcoded child (in my real world use case i have a json file with all hardcoded children defined as empty objects because i commented out all properties... just to provide a quick customizable template to the user!!!)
```
{
    "MainOptions": {
        "Prop": "fromJsonCfg",
        "Dic": {
            "child1": { 
                //"Prop1": "fromJsonCfg",
                //"Prop2": "fromJsonCfg",
            },
        },
    },
}
```

with Net7.0 the json defined empty children matching an existent child in "hardcoded" configuration was "merged" exactly how i expect:
```
{ "Prop1": "hardcoded", "Prop2": "hardcoded" } + { } =  { "Prop1": "hardcoded", "Prop2": "hardcoded" }
{ "Prop1": "hardcoded", "Prop2": "hardcoded" } + { "Prop1": "fromJsonCfg" } =  { "Prop1": "fromJsonCfg", "Prop2": "hardcoded" }
{ "Prop1": "hardcoded", "Prop2": "hardcoded" } + { "$dummy": 0 } =  { "Prop1": "hardcoded", "Prop2": "hardcoded" }
```
but with Net8.0 the empty child case results in a defaulted child:
```
{ "Prop1": "hardcoded", "Prop2": "hardcoded" } + { } =  { "Prop1": "default", "Prop2": "default" }
{ "Prop1": "hardcoded", "Prop2": "hardcoded" } + { "Prop1": "fromJsonCfg" } =  { "Prop1": "fromJsonCfg", "Prop2": "hardcoded" }
{ "Prop1": "hardcoded", "Prop2": "hardcoded" } + { "$dummy": 0 } =  { "Prop1": "hardcoded", "Prop2": "hardcoded" }
```

I'm aware of this (probably related?) breaking change: https://learn.microsoft.com/en-us/dotnet/core/compatibility/extensions/8.0/dictionary-configuration-binding

I don't know if this issue is to be  considered as a BUG, or an undocumented breaking change... Anywhere (IMHO) it's affecting with a bad way a perfectly reasonable use case (json configuration files with empy objects acting as user config. template)

I also don't know if the real issue is in the `ConfigurationBinder` or in the `JsonConfigurationFileParser` https://github.com/dotnet/runtime/blob/710774a3117dbf62ab35565f4b0b300f7a775319/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationFileParser.cs#L73

### Reproduction Steps

1. create a new empty directory
2. paste all this text in a new file `ConfigurationBinding.csproj`
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup Condition="$(TargetFramework) == 'net8.0' ">
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework) == 'net7.0' ">
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>

```
3. paste all this text in a new file `ConfigurationBinding.cs`
```
using Microsoft.Extensions.Configuration;
using System.Text;
using Xunit;

namespace ConfigurationBinding;
public class ConfigurationBinding
{
    class RootOptions
    {
        public MainOptions MainOptions { get; } = new();
    }
    class MainOptions
    {
        public Dictionary<string, ChildOptions> Dic { get; } = new();
        public string Prop { get; set; } = "default";
    }
    class ChildOptions
    {
        public string Prop1 { get; set; } = "default";
        public string Prop2 { get; set; } = "default";
    }

    private static Stream StringToStream(string s) => new MemoryStream(Encoding.UTF8.GetBytes(s));

    private static RootOptions CreateHardcodedOptions()
    {
        var opts = new RootOptions();
        opts.MainOptions.Dic["child1"] = new()
        {
            Prop1 = "hardcoded",
            Prop2 = "hardcoded",
        };
        opts.MainOptions.Dic["child2"] = new()
        {
            Prop1 = "hardcoded",
            Prop2 = "hardcoded",
        };
        return opts;
    }

    [Fact]
    public void NullChildObject()
    {
        var opts = CreateHardcodedOptions();

        const string jsonCfg = """
{
    "MainOptions": {
        "Prop": "fromJsonCfg",
        "Dic": {
            "child1": null,
        },
    },
}
""";
        var cfg = new ConfigurationBuilder()
            .AddJsonStream(StringToStream(jsonCfg))
            .Build();

        Assert.Equal("default", opts.MainOptions.Prop);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop1);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop2);

        cfg.Bind(opts);

        Assert.Equal("fromJsonCfg", opts.MainOptions.Prop);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop1);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop2);
    }

    [Fact]
    public void EmptyChildObject()
    {
        var opts = CreateHardcodedOptions();

        const string jsonCfg = """
{
    "MainOptions": {
        "Prop": "fromJsonCfg",
        "Dic": {
            "child1": { 
                //"Prop1": "fromJsonCfg",
                //"Prop2": "fromJsonCfg",
            },
        },
    },
}
""";
        var cfg = new ConfigurationBuilder()
            .AddJsonStream(StringToStream(jsonCfg))
            .Build();

        Assert.Equal("default", opts.MainOptions.Prop);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop1);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop2);

        cfg.Bind(opts);

        Assert.Equal("fromJsonCfg", opts.MainOptions.Prop);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop1);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop2);
    }

    [Fact]
    public void NotEmptyChildObject()
    {
        var opts = CreateHardcodedOptions();

        const string jsonCfg = """
{
    "MainOptions": {
        "Prop": "fromJsonCfg",
        "Dic": {
            "child1": {
                "$dummy": false,
                //"Prop1": "fromJsonCfg",
                //"Prop2": "fromJsonCfg",
            }
        },
    },
}
""";

        var cfg = new ConfigurationBuilder()
            .AddJsonStream(StringToStream(jsonCfg))
            .Build();

        Assert.Equal("default", opts.MainOptions.Prop);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop1);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop2);

        cfg.Bind(opts);

        Assert.Equal("fromJsonCfg", opts.MainOptions.Prop);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop1);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop2);
    }

    [Fact]
    public void OverrideChildObjectProp()
    {
        var opts = CreateHardcodedOptions();

        const string jsonCfg = """
{
    "MainOptions": {
        "Prop": "fromJsonCfg",
        "Dic": {
            "child1": {
                "Prop1": "fromJsonCfg",
                //"Prop2": "fromJsonCfg",
            }
        },
    },
}
""";

        var cfg = new ConfigurationBuilder()
            .AddJsonStream(StringToStream(jsonCfg))
            .Build();

        Assert.Equal("default", opts.MainOptions.Prop);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop1);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop2);

        cfg.Bind(opts);

        Assert.Equal("fromJsonCfg", opts.MainOptions.Prop);
        Assert.Equal("fromJsonCfg", opts.MainOptions.Dic["child1"].Prop1);
        Assert.Equal("hardcoded", opts.MainOptions.Dic["child1"].Prop2);
    }

    [Fact]
    //https://learn.microsoft.com/en-us/dotnet/core/compatibility/extensions/8.0/dictionary-configuration-binding
    public void DocumentedBreakingChange_net7_net8()
    {
        var opts = CreateHardcodedOptions();

        const string jsonCfg = """
{
    "MainOptions": {
        "Prop": "fromJsonCfg",
        "Dic": {
            "childNew1": { "Prop1": "fromJsonCfg" },
            "childNew2": { },
        },
    },
}
""";
        var cfg = new ConfigurationBuilder()
            .AddJsonStream(StringToStream(jsonCfg))
            .Build();

        Assert.Equal("default", opts.MainOptions.Prop);
        Assert.Equal(2, opts.MainOptions.Dic.Count);

        cfg.Bind(opts);

        Assert.Equal("fromJsonCfg", opts.MainOptions.Prop);
        Assert.Equal("fromJsonCfg", opts.MainOptions.Dic["childNew1"].Prop1);
#if NET8_0_OR_GREATER
        Assert.Equal("default", opts.MainOptions.Dic["childNew2"].Prop1);
        Assert.Equal(4, opts.MainOptions.Dic.Count);
#else
        Assert.Equal(3, opts.MainOptions.Dic.Count);
#endif
    }

}
```
4. run this command `dotnet test .\ConfigurationBinding.csproj`

### Expected behavior

All the tests must pass

### Actual behavior

Only the tests in net7.0 configuration passed:
`Passed!  - Failed:     0, Passed:     5, Skipped:     0, Total:     5, Duration: 11 ms - ConfigurationBinding.dll (net7.0)`

Some tests in net8.0 configuration are failed!!!:
`Failed!  - Failed:     2, Passed:     3, Skipped:     0, Total:     5, Duration: 6 ms - ConfigurationBinding.dll (net8.0)`

### Regression?

Yes, it worked as expected in net7.0 

### Known Workarounds

Insert a dummy unbound property in the json template file. i.e.:
```
{
    "MainOptions": {
        "Prop": "fromJsonCfg",
        "Dic": {
            "child1": {
                "$dummy": false,
                //"Prop1": "fromJsonCfg",
                //"Prop2": "fromJsonCfg",
            }
        },
    },
}
```

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by beppemarazzi**
fixes #96682

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]
Thanks @beppemarazzi

**Comment by beppemarazzi** [comment]
@tarekgh I don't know how the workflow works, but since the issue affects the released Net8.0 IMHO this may be backported... 
There are specific labels to do this?
Eventually for future contribution is better to make a PR against the affected release branch?

**Comment by eiriktsarpalis** [comment]
Assuming it's a regression from .NET 7 then this would get backported to 8.

**Comment by beppemarazzi** [comment]
> @beppemarazzi how blocking this issue for you. I am asking because we backport only the high impact or blocking fixes.

Not really blocking for me: I've the luck to have a full control over the deployed configuration files, so once I caught it, I've "adjusted" my configuration templates with a "dummy" property. i.e.:
```
{
    "MainOptions": {
        "Dic": {
            "child1": { 
                "$dummy": 0,
                //"Prop1": "fromJsonCfg",
                //"Prop2": "fromJsonCfg",
            },
        },
    },
}
```

but IMHO it's an "high impact" regression... in fact there are for sure a lot of use cases around the world adopting this pattern (a dictionary with some nested sub-objects "pre-defined" in the application code but customizable from the `appsettins.json`). The bad thing with the new Net8 behavior is that in a lot of cases the already deployed configuration file is managed by the final user, so it's out of the control from the developer point of view....

**Comment by tarekgh** [comment]
Thanks @beppemarazzi for the feedback. I would rather let the fix simmer in the main codebase for a while to gain more confidence that it won't introduce any issues. We'll closely monitor the situation, and if there is a noticeable increase in demand, we can speed up porting the fix at that time.

**Pull request merged**
