### PR TITLE
Use TaskDialog for error dialog in Windows GUI apps

### LINKED ISSUE #71288: Use modern-themed buttons in the host error message box.
The recent blog post with the apphost improvements features an error message box for the cases when the appropriate runtime was not found.

image

As seen in the screenshot, the message box uses old-style buttons. They could be made more modern [pretty easily](https://docs.microsoft.com/en-us/windows/win32/controls/cookbook-overview). This is how it would look like:

image

### PR DESCRIPTION
**Pull request by elinor-fung**
Show runtime/framework not found error via a [task dialog](https://learn.microsoft.com/windows/win32/controls/task-dialogs) instead of a message box when possible - falls back to message box if not.

Screenshots of what it looks like with the current change are below. We can definitely move text around (for example, only include the docs link in the main text and app/architecture/framework in the collapsible details section) or do something different for the icon (for example, don't try to use the app icon and always use the standard error icon or no icon at all).

Resolves https://github.com/dotnet/runtime/issues/71288
Related: https://github.com/dotnet/runtime/issues/3816

@richlander @vitek-karas thoughts?

image
image

The current change also tries to use the app's icon if it exists:
image

The expanded details has the full details including the download link:
image
image

### CODE REVIEW

**Comment by vitek-karas** [comment]
Adding @mairaw - this is one of the common ways to get to the website. Maybe there's opportunity to provide consistent UX and terminology.

I think we can design the default dialog content to be "End user friendly" and then include the technical details in the collapsed drop down section of the dialog.

Nit: (I noticed this with our current dialog as well) - the dialog doesn't have the standard "Red X" close button in the top right corner. I think ideally it should have that.

**Comment by elinor-fung** [comment]
Some example variations for reference:

Technical details moved to collapsed section:
image
Expanded (technical details end up after the docs link)
image

Expanded info can also be put in the footer instead of the main content:
image

With cancellation (title bar X button, esc to close) - also ends up with the icon in the title bar:
image

No icon:
image

**Comment by danmoseley** [comment]
I'm not sure that "Framework resolution" is a meaningful term for end users.

**Comment by elinor-fung** [comment]
Maybe "Learn about app launch failures"?

**Comment by danmoseley** [comment]
> Maybe "Learn about application launch failures" for both cases?

or even "Learn more:"  (or actually -- is that link to something end users will understand? perhaps the text should be "More information for developers:")

**Comment by elinor-fung** [comment]
The link is intended to be a page that end users will understand. But yeah, we'd expect/want users to just be able to use the download button to get the right runtime.

Everything moved to collapsible details section (whitespace looks kind of awkward - I feel like we want some basic text there):
image

**Comment by elinor-fung** [comment]
Added cancellation/close and moved details to the expanded info section. Images in description are updated.

@mairaw @richlander @vitek-karas thoughts/improvements on the wording or visual? 

I think the icon being in both the main dialog and title bar is odd, but apparently showing the icon in the title bar is the TaskDialog behaviour once you enable cancellation.

**Comment by vitek-karas** [comment]
In general I like it (I'll leave the exact wording for people who actually speak English)!
I agree that the two icons are a bit weird, but I don't think it's too bad - for me the presence of the cancellation outweighs it.

**Comment by elinor-fung** [comment]
Ran through this with @mairaw and @richlander - keeping the layout in its current state and going with `Required:` instead of `Framework:` in the details section.

**Review by vitek-karas — APPROVED** [review]

**Pull request merged**
