### PR TITLE
ensure test TestUserCredentialsPropertiesOnWindows is run only by elevated accounts

### LINKED ISSUE #46208: Test failure: System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows
failed in job: [runtime-libraries-coreclr outerloop 20201217.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=924882&view=ms.vss-test-web.build-test-results-tab&runId=29343938&resultId=102792&paneView=debug)

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

Error message
~~~
System.UnauthorizedAccessException : Attempted to perform an unauthorized operation.


Stack trace
   at System.Security.AccessControl.Win32.SetSecurityInfo(ResourceType type, String name, SafeHandle handle, SecurityInfos securityInformation, SecurityIdentifier owner, SecurityIdentifier group, GenericAcl sacl, GenericAcl dacl) in /_/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/Win32.cs:line 314
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, SafeHandle handle, AccessControlSections includeSections, Object exceptionContext) in /_/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/NativeObjectSecurity.cs:line 263
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, AccessControlSections includeSections, Object exceptionContext) in /_/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/NativeObjectSecurity.cs:line 353
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, AccessControlSections includeSections) in /_/src/libraries/System.Security.AccessControl/src/System/Security/AccessControl/NativeObjectSecurity.cs:line 343
   at System.Security.AccessControl.FileSystemSecurity.Persist(String fullPath) in /_/src/libraries/System.IO.FileSystem.AccessControl/src/System/Security/AccessControl/FileSystemSecurity.cs:line 124
   at System.IO.FileSystemAclExtensions.SetAccessControl(FileInfo fileInfo, FileSecurity fileSecurity) in /_/src/libraries/System.IO.FileSystem.AccessControl/src/System/IO/FileSystemAclExtensions.cs:line 78
   at System.Diagnostics.Tests.ProcessStartInfoTests.SetAccessControl(String userName, String filePath, AccessControlType accessControlType) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 523
   at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs:line 502
~~~

### PR DESCRIPTION
**Pull request by adamsitnik**
Fixes #46208

### CODE REVIEW

**Comment by adamsitnik** [comment]
@danmosemsft is there any chance that you could take a look?

The CI failure is unrelated (`System.Net.Http.Functional.Tests.SocketsHttpHandler` test failured)

**Review by danmoseley — APPROVED** [review]

**Comment by danmosemsft** [comment]
Nice you're making test improvements.

**Comment by adamsitnik** [comment]
> Nice you're making test improvements.

I want to get to the point where there is 0 unstable and disabled tests in the areas that I own. It's a way to get a little bit more familiar with the code before everyone is back from the winter holiday break

**Pull request merged**
