### PR TITLE
Remove unused local variables and methods from System.Drawing.Common

### PR DESCRIPTION
**Pull request by MattKotsenas**
Remove unused locals, and update a few unit tests that had no asserts.

Fixes a part of #30457

### CODE REVIEW

**Review by safern — APPROVED** [review]
Thanks!

**Comment by danmosemsft** [comment]
One failure in WASM
```
Assert.True() Failure\r\nExpected: True\r\nActual:   False


Stack trace
   at System.Drawing.Printing.Tests.PrinterSettingsTests.CanDuplex_ReturnsExpected() in /_/src/libraries/System.Drawing.Common/tests/Printing/PrinterSettingsTests.cs:line 53
```

**Comment by MattKotsenas** [comment]
> One failure in WASM
> 
> ```
> Assert.True() Failure\r\nExpected: True\r\nActual:   False
> 
> 
> Stack trace
>    at System.Drawing.Printing.Tests.PrinterSettingsTests.CanDuplex_ReturnsExpected() in /_/src/libraries/System.Drawing.Common/tests/Printing/PrinterSettingsTests.cs:line 53
> ```

Thanks for that! This was a case of a test that wasn't asserting anything, so my initial change was to default to true. From code inspection it looks like on "unix" systems `CanDuplex` is always false, so I've changed the assert to false.

If there are Windows tests that have / simulate a duplex printer, then I'll weaken the assert to just verify that the property doesn't throw and use a discard to avoid tripping the unused local check.

**Comment by danmosemsft** [comment]
I only know of `[ConditionalFact(Helpers.AnyInstalledPrinters, Helpers.IsDrawingSupported)]`. I don't think we have a way to also know whether it's a duplex printer without using the API itself. Probably all you can do is check it doesn't throw. Or conceivably call it twice and check you get the same result 😉

**Comment by safern** [comment]
I was going to comment that actually but then thought it might just work and now I remember we intentionally don't assert on those properties, just make sure they "work" don't fail, since we can guarantee they will have the same behavior specially because the installed printers can be different in every computer we use to run tests and in every platform.

**Comment by MattKotsenas** [comment]
> I was going to comment that actually but then thought it might just work and now I remember we intentionally don't assert on those properties, just make sure they "work" don't fail, since we can guarantee they will have the same behavior specially because the installed printers can be different in every computer we use to run tests and in every platform.

This makes sense! I was a bit confused when I saw tests that looked like they weren't verifying anything -- the "assert that it doesn't throw" behavior makes sense now that you mention it.

I've undone my changes for all 4 tests in that area.

If you have any questions, please let me know. Thanks!

**Review by safern — APPROVED** [review]
Thanks again 😄

**Pull request merged**
