### PR TITLE
Delete CallingConventions.cs

### LINKED ISSUE #67519: Consider deleting CallingConventions.cs
https://github.com/dotnet/runtime/issues/67232#issuecomment-1086724380

We only exercise this when a reflection invoke thunk is not available, which means it's pretty much untested and likely doesn't work outside Windows. We might want to untangle it and remove it similar to how we removed the rest of universal shared code support logic.

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
This file was added for universal shared code. We can restore it again if it's needed, but we don't need it now.

On NativeAOT we could leverage the CCC for reflection invoke, but this code was never updated to work outside Windows. It's safer to delete it.

Fixes #67519.

### CODE REVIEW

**Comment by am11** [comment]
Thanks!
Is it so that the reflection invoke thunks are unavailable in cases like "reflection-free mode" and some `ILCompiler.Xyz` which are not intended to support reflection?

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by jkotas** [comment]
Do we want to also change https://github.com/dotnet/runtime/blob/4881a639e7c3f27b5a8d2d160e234d8055333cda/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DynamicInvokeThunkGenerationPolicy.cs#L38-L43 to return true? We do not have the fallback anymore.

**Comment by MichalStrehovsky** [comment]
I actually thought about this code when I was doing this work. I added this limit because we were getting compiler crashes for some of the Pri-0 tests:

https://github.com/dotnet/runtime/blob/4881a639e7c3f27b5a8d2d160e234d8055333cda/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DynamicInvokeThunkGenerationPolicy.cs#L39-L40

There needs to be _some_ limit, and I'm not sure what the limit for "RyuJIT crashes" is.

With this code in place, we avoid compiler crash, and there will be a NotSupportedException if someone ever actually hits this. They probably won't.  Maybe it's good as it is?

**Comment by jkotas** [comment]
I would expect that the codegen limits for the reflection stub are approximately in the same order of magnitude as for the method itself.

I agree that this is probably ok as it is. If we ever hear otherwise, we can re-evaluate. Maybe we can give the NotSupportedException a specific message so that the situation is easier to diagnose?

**Pull request merged**
