### PR TITLE
BindConfiguration registers change token source with the right options name

### LINKED ISSUE #85665: Reload configuration not work for named options add with BindConfiguration extension method.
### Description

Hello,

I want to reload a JSON configuration from a file after the file changed. I'm using the IOptionsMonitor and  the OnChnage event is fired but when I'm using named options OnChnage is always fired for DefaultOptionName (""). I register the options class to DI container with BindConfiguration extension method. If I use Bind extension method it works.

### Reproduction Steps

I made a [repro ](https://github.com/McMlok/NamedOptionsReloadTest)with working and not working code how to add options to the container.

working code
```csharp
services.AddOptions<ConsoleHostOptions>("Test").Bind(hostContext.Configuration.GetSection("Config:Test"));
```

not working code

```csharp
services.AddOptions<ConsoleHostOptions>("Test").BindConfiguration("Config:Test");
```

### Expected behavior

When a change in an underlying file occurred OnChnage event is fired for named options with the correct options class and the correct name.

### Actual behavior

When a change occurred the change event is fired but for the CurrentValue option class with "" value in arg2 event parameter (option name).

### Regression?

_No response_

### Known Workarounds

Manually register IOptionsChangeTokenSource<> with correct name

```csharp
services.AddSingleton<IOptionsChangeTokenSource<ConsoleHostOptions>>(new ConfigurationChangeTokenSource<ConsoleHostOptions>("Test", hostContext.Configuration));
```

### Configuration

tested on .NET 6 (6.0.408), .NET 7 (7.0.203) on Windows 10 x64 22H2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by asimmon**
Fixes #85665

`BindConfiguration()` now uses the options name from `OptionsBuilder<>` instead of the default empty options name, which enables options change detection for the right options name.

### CODE REVIEW

**Comment by asimmon** [comment]
@microsoft-github-policy-service agree

**Comment by tarekgh** [comment]
@asimmon please have a look at the failing tests https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-91842-merge-626554015c334c69aa/WasmTestOnBrowser-Microsoft.Extensions.Options.ConfigurationExtensions.SourceGeneration.Tests/1/console.11e77603.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-91842-merge-626554015c334c69aa/WasmTestOnBrowser-Microsoft.Extensions.Options.ConfigurationExtensions.SourceGeneration.Tests/1/console.11e77603.log?helixlogtype=result)

**Comment by tarekgh** [comment]
@asimmon for SLA signing, please look at the comment https://github.com/dotnet/runtime/pull/91355#issuecomment-1705620083 for how you can complete the signing. Thanks!

**Comment by asimmon** [comment]
@dotnet-policy-service agree

**Comment by asimmon** [comment]
Thanks @tarekgh for helping me out with the agreement. The failing tests link highlighted more work needed on the source generator related projects; I'll handle it.

**Comment by tarekgh** [comment]
@asimmon currently we are doing some source gen urgent fixes and trying to stabilize it for .NET 8.0. We may delay merging your fix here for later, after two weeks or so. I am going to convert this PR to draft and then we can revisit it after two weeks or so. You can go ahead and add more changes to this PR. I appreciate your work here. 

CC @layomia

**Comment by tarekgh** [comment]
@asimmon https://[helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-91842-merge-9a85c2bf9cf441f090/Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests/1/console.61aa5598.log?helixlogtype=result](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-91842-merge-9a85c2bf9cf441f090/Microsoft.Extensions.Configuration.Binder.SourceGeneration.Tests/1/console.61aa5598.log?helixlogtype=result)

**Comment by pinkfloydx33** [comment]
I realize it's nearing the end of the cycle, but is there no way to get the fix into 8? According to blame, the bug has been around for 2+ years. It'd feel silly to introduce the same bug into the new source generator (or to fix it in SG but then not have parity). 

We've been able to work around it with a custom extension that registers an extra/correct reload token ourselves so it's not currently blocking, but it's definitely a bit annoying 😢

**Comment by tarekgh** [comment]
> I realize it's nearing the end of the cycle, but is there no way to get the fix into 8?

The threshold for incorporating fixes into version 8.0 is quite stringent, primarily because we must be extremely cautious at this stage to mitigate any potential risks. It's important to recognize that appearances can be deceiving, and even changes that seem harmless may harbor unexpected issues. Consequently, we intend to retain this fix within the primary codebase for an extended period to bolster our confidence in its stability. Moreover, for those who require the fix urgently, it will be accessible in the early previews of .NET 9.0.

**Comment by pinkfloydx33** [comment]
Thanks @tarekgh. I figured I'd ask anyways despite pretty much knowing the answer ahead of time. Was hoping to avoid jumping through the hoops that'll be required to light up the SG _and_ retain our workaround. But, hey... c'est la vie

**Comment by asimmon** [comment]
@tarekgh it's been a month and the PR was closed, what should I do? Shall I wait and ask to reopen the PR later or should I update the branch with main?

**Comment by tarekgh** [comment]
@asimmon sorry this is automatically closed. I reopened it. We still need some more time before we proceed with this one. Meanwhile, I would appreciate it if you could resolve the conflict against the main branch. Thanks!

**Comment by tarekgh** [comment]
@asimmon did you have a chance to resolve the merge conflicts?

**Comment by tarekgh** [comment]
@asimmon looks the change is causing a failure in the source gen test. Could you please have a look? Thanks!

```
    Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.BindConfiguration [FAIL]
      Line numbers do not match. Expected: 194 lines, but generated 198
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/GeneratorTests.Helpers.cs(146,0): at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.VerifyAgainstBaselineUsingFile(String filename, String testSourceCode, ExtensionClassType extType, ExpectedDiagnostics expectedDiags)
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/GeneratorTests.Baselines.Options.cs(204,0): at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.BindConfiguration()
        --- End of stack trace from previous location ---
```

**Comment by asimmon** [comment]
I'll take care of it, thanks!

**Comment by asimmon** [comment]
@tarekgh it's done!

**Review by tarekgh — APPROVED** [review]
@asimmon thanks a lot for your help with this fix and your patience too. LGTM.

**Pull request merged**
