### PR TITLE
Refactor `GetGetSystemTimeAsFileTimeFnPtr`

### PR DESCRIPTION
**Pull request by xtqqczze**
* Don't check whether `GetSystemTimePreciseAsFileTime` exists, it is always available in `win8`.
* Move PInvokes to `Interop.Kernel32`.
* Don't use `Math.Abs` to avoid unecessary overflow check.

### CODE REVIEW

**Comment by jkotas** [comment]
> Don't check whether GetSystemTimePreciseAsFileTime exists, it is always available in win8

We do not officially support Windows 7. However, we are trying to avoid breaking Windows 7 intentionally for the time being.

**Comment by xtqqczze** [comment]
> We do not officially support Windows 7. However, we are trying to avoid breaking Windows 7 intentionally for the time being.

@jkotas It was my understanding this was the case for .NET 7, and that Windows 7 specific code would be removed with .NET 8. Is this still the current thinking?

**Comment by stephentoub** [comment]
> that Windows 7 specific code would be removed with .NET 8. Is this still the current thinking?

No. We're avoiding removing such code paths.

**Comment by xtqqczze** [comment]
> > that Windows 7 specific code would be removed with .NET 8. Is this still the current thinking?
> 
> No. We're avoiding removing such code paths.

Closing for now. Has a final decision has been made one way or the other for either .NET 8 or future versions?

**Pull request closed without merging**
