### PR TITLE
Add COMPlus_SampleProfilerSamplePeriodMS

### PR DESCRIPTION
**Pull request by sywhang**
This adds the environment variable `COMPlus_SampleProfilerSamplePeriodMS` which can be used to change the sampling rate of the SampleProfiler. 

The changes in PAL happened because `nanosleep` does not know how to sleep more than 999999999 set on the `tv_nsec` field of `timespec` struct.

### CODE REVIEW

**Review by josalem — APPROVED** [review]
I think this change is fine provided you've tested it locally.

**Review by noahfalk — COMMENTED** [review]
The change looks fine technically, but what is the need for this work? 

Also adding @janvorli for all things PAL related.

**Comment by danmosemsft** [comment]
@sywhang do you plan to finish this one up?

**Comment by sywhang** [comment]
@danmosemsft thanks for the heads up - after discussing with Noah we decided to not put this in. I'll close this PR now!

**Pull request closed without merging**
