### PR TITLE
[release/5.0] Fix optRemoveRedundantZeroInits for loops #48571

### PR DESCRIPTION
**Pull request by EgorBo**
Issue: https://github.com/dotnet/runtime/issues/48394
Fix in master: https://github.com/dotnet/runtime/pull/48571

## Customer Impact
Jit tries to eliminate redundant (duplicated) zero initializations for all types of local variables if we don't do anything with them in-between. Unfortunately, there is a case with backward branches (loops) where it can drop zero inits where they're actually needed. It might lead to an unexpected behavior.

A simple repro:
```csharp
static void MakeSureIsNullAndSetValue(ref object obj)
{
    if (obj != null)
        throw new System.Exception("should be null at this point");
    obj = new object();
}

static void Test()
{
    object obj = null;
    int i = 0;
    do
    {
        obj = null; // this assignment shouldn't be removed
        MakeSureIsNullAndSetValue(ref obj);
    }
    while (i++ < 10);
}

Test();
```
It throws that exception in Release mode (only on .NET 5.0), Debug is fine since the optimization is not kicked in.
Jit-diff tools found a place in the BCL where JIT removes not-redundant assignment: https://github.com/dotnet/runtime/blob/d5ab93c4a8e45da2dab8924c2165000bf78f84e6/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs#L776 

## Testing
This PR adds a regression test.

## Risk
Low. The fix is pretty straightforward and disables the optimization once we hit a loop 

## Regression
Yes, the optimization was introduced in 5.0

### CODE REVIEW

**Comment by JulieLeeMSFT** [comment]
CC @jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
@EgorBo please request a code review and then we can take this for consideration.

cc @JulieLeeMSFT

**Comment by JulieLeeMSFT** [comment]
@dotnet/jit-contrib PTAL

**Review by AndyAyersMS — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  We will take for consideration for 5.0.x

**Comment by Anipik** [comment]
https://github.com/dotnet/runtime/issues/48406

**Comment by Anipik** [comment]
Known crypto failures merging this one

**Pull request merged**
