### PR TITLE
Fix runtime-llvm pipeline

### PR DESCRIPTION
**Pull request by ViktorHofer**

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@tannergooding I assumed that these jobs are standalone and build everything they need themselves. Apparently they are not and require other jobs to run first. This means that we will run more jobs in total than before but as we just talk about building the product it should be fine.

I will take a look later when I have more time.

**Comment by ViktorHofer** [comment]
@tannergooding I didn't forget about this but I need to complete another task first before I can finish this. Latest by Monday.

**Comment by ViktorHofer** [comment]
Apparently the llvm(full)aot test runs require the following jobs to be run:

image

It's surprising that mono relies on the coreclr job, IIRC that's because they depend on CoreRun which is only built as part of coreclr. The other two jobs are expected to be required even though I would have assumed that the global build jobs make the libraries assets available. The mono_common_test build is IMO the only true dependency that is missing as the runtime tests aren't built anywhere in the yml.

@tannergooding this seems to be much more complex as I initially thought. I currently don't have more time to look into this but maybe folks from the mono team could help?

**Comment by steveisok** [comment]
@directhex Can you please help out here?

**Comment by ViktorHofer** [comment]
I'm closing this PR now as I don't have the bandwidth to look more close into this. @tannergooding can you please work with @steveisok and @directhex to complete your work?

**Pull request closed without merging**
