### PR TITLE
Replace TargetFrameworks with TargetFramework where possible

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
Follow up on https://github.com/dotnet/runtime/pull/66175#discussion_r819655491

**Review by stephentoub — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by danmoseley** [comment]
@ViktorHofer didn't you have some concurrent or recent change to change TargetFrameworks to TargetFramework in some way? Just want to make sure this doesn't conflict or have some wierd consequence.

**Review by danmoseley — APPROVED** [review]

**Review by agocke — APPROVED** [review]

**Comment by jkotas** [comment]
The test failures are #66232 and infrastructure issue (Failed to upload results).

**Comment by ViktorHofer** [comment]
> @ViktorHofer didn't you have some concurrent or recent change to change TargetFrameworks to TargetFramework in some way? Just want to make sure this doesn't conflict or have some wierd consequence.

Note that there was a technical limitation that required all libraries projects to use the `TargetFrameworks` property even if the project wasn't multi-targeting but that was fixed with https://github.com/dotnet/runtime/commit/20e8f905d05f2d8f390d0e2ef10f1a4a1289967c. Reference and source projects were updated via the same commit and test projects were then later updated with https://github.com/dotnet/runtime/commit/7671b5084a41944d7a0c1fb9674e354183ec722d.

The src/libraries projects touched here were either added/updated meanwhile, or my regex skills that I used to update the projects failed me 🤦 Anyway, the change looks good to me.

**Pull request merged**
