### PR TITLE
[release/6.0] Skip test suites crashing on CI for iOS/tvOS/MacCatalyst and test fixes for Android

### PR DESCRIPTION
**Pull request by mdh1418**
Manual backport of #57208, #58519, #58562, #58210, #57732, #58428, #58586, #58745, #57687 to release/6.0

Numerous test suites have been failing for iOS/tvOS/MacCatalyst consistently on CI without useful logs as to why. Moreover, some of these suites pass locally. 

This PR looks to reduce the failures on CI by skipping the problematic suites
Skips test suites logged in https://github.com/dotnet/runtime/issues/53624

ActiveIssues
https://github.com/dotnet/runtime/issues/58440
https://github.com/dotnet/runtime/issues/58418
https://github.com/dotnet/runtime/issues/58367
https://github.com/dotnet/runtime/issues/58584

/cc @mdh1418

## Customer Impact
A majority of the changes are all dev-facing and are related to testing libraries. This include #57208, #58519, #58562, #58210, #57732, #58428, #58745

#58586 introduces a change that fixes when 32 bit arm Android apps getting an incorrect flag

#57687 adds mtriple values for MacCatalyst for proper mono AOT linking during the AppleAppBuilder task, it was primarily included because the error was hit in the previous CI Build run

## Testing
This change is related to testing with a primary focus to re-enable test suites that are no longer crashing, and disable test suites and tests that still crash or are new crashes.

## Risk
Low, the majority of changes are related to testing. #58586 fixes a flag issue on 32bit arm Android apps, and #57687 fixes a linking issue but is noted to be slow in the PR description.

### CODE REVIEW

**Comment by mdh1418** [comment]
This is a WIP, there are more changes I plan to include in this backport.

**Comment by mdh1418** [comment]
@akoeplinger Were there more commits that you were aware of that I missed in regards to making runtime-staging more green?

**Comment by akoeplinger** [comment]
@mdh1418 I pushed the changes

**Review by marek-safar — APPROVED** [review]

**Comment by mdh1418** [comment]
Browser wasm release Browser_wasm_Windows lane seems to be flakey @lewing, has failed for separate reasons the past few runs.

**Pull request merged**
