### PR TITLE
disable MainWindow*_GetWithGui_ShouldRefresh_Windows tests for Windows Server Core

### LINKED ISSUE #46352: Test failure: System.Diagnostics.Tests.ProcessTests.MainWindowTitle_GetWithGui_ShouldRefresh_Windows
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=929390&view=ms.vss-test-web.build-test-results-tab&runId=29452414&resultId=101161&paneView=debug

failed tests:
System.Diagnostics.Tests.ProcessTests.MainWindowTitle_GetWithGui_ShouldRefresh_Windows
System.Diagnostics.Tests.ProcessTests.MainWindowHandle_GetWithGui_ShouldRefresh_Windows

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

Error message
~~~
Assert.NotEqual() Failure
Expected: Not ""
Actual:   ""

Stack trace
   at System.Diagnostics.Tests.ProcessTests.MainWindowTitle_GetWithGui_ShouldRefresh_Windows() in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.cs:line 1619
~~~

### PR DESCRIPTION
**Pull request by adamsitnik**
Fixes #46352

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
Thanks

**Comment by danmosemsft** [comment]
Failures were https://github.com/dotnet/runtime/issues/44351 and https://github.com/dotnet/runtime/issues/41531

**Pull request merged**
