### PR TITLE
Unpin wasi docker image in pipeline-with-resources.yml

### PR DESCRIPTION
**Pull request by akoeplinger**

### CODE REVIEW

**Comment by pavelsavara** [comment]
This would mean that for example bump to WASI SDK 22 in the VM images would automatically break runtime main. Is that what we want ? 

cc @lewing

**Comment by akoeplinger** [comment]
That's how the infrastructure team wants to maintain these images, yes. The point is getting OS etc. updates automatically.
If we know a new wasi sdk version breaks existing consumers then we need to create a new image.

**Comment by akoeplinger** [comment]
I guess longer term we should move to using our own nuget packages for emsdk/wasi-sdk, then this wouldn't matter.

**Review by pavelsavara — APPROVED** [review]

**Comment by akoeplinger** [comment]
Merging since the floating tag refers to the same version so there's no point in wasting CI resources.

**Pull request merged**
