### PR TITLE
Parse `DOTNET_PROCESSOR_COUNT` with a 10 radix not 16

### LINKED ISSUE #53150: `DOTNET_PROCESSOR_COUNT` is a hex value -- should be decimal
`DOTNET_PROCESSOR_COUNT` is treated as a hex value. That's unexpected and likely to surprise users. It should be changed to a decimal value.

Context: https://github.com/dotnet/runtime/issues/53149

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #53150 

/cc @richlander @AntonLapounov

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
Nice

**Comment by AntonLapounov** [comment]
Could you please fix this line as well? https://github.com/dotnet/runtime/blob/53735f77ec5d223b6d39e5de93951ef1d1edaffb/src/libraries/System.Runtime.Extensions/tests/System/Environment.ProcessorCount.cs#L33

**Comment by AaronRobinsonMSFT** [comment]
@AntonLapounov Yep. I was just validating locally and noticed that. Thanks for calling it out too.

**Review by AntonLapounov — APPROVED** [review]
Thank you.

**Review by richlander — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
Product builds/test all pass.

**Pull request merged**
