### PR TITLE
Clean up Crossgen2 executions in installer after SDK P2 ingestion

### LINKED ISSUE #48252: Clean up ReadyToRun.targets in the installer after consuming SDK repo update with CG2 execution fixes
To expedite CG2 bring-up I need to merge in a hack in

https://github.com/dotnet/runtime/blob/master/src/installer/pkg/sfx/Microsoft.NETCore.App/ReadyToRun.targets

to make CG2 work even with SDK 5.0 / SDK 6.0 preview 1 that don't support running CG2 via explicitly specified .NET host. I have currently a PR open for the SDK change,

https://github.com/dotnet/sdk/pull/15529/files

but that will make it to SDK 6.0 preview 2 in the best case and it's going to be another 1-2 months before this SDK update is consumed in the runtime repo. Once that happens, the script should be cleaned up by removing the construction of JitPath and by passing TargetArch / TargetOS instead.

/cc @dotnet/crossgen-contrib 
/cc @ViktorHofer

### PR DESCRIPTION
**Pull request by trylek**
Fixes: https://github.com/dotnet/runtime/issues/48252
/cc @dotnet/crossgen-contrib

### CODE REVIEW

**Review by AntonLapounov — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Do we need to wait until the minimum required version of the SDK is P2? When using P1 (which is the current min version), would the sfxproj then fail to build?

**Comment by trylek** [comment]
@ViktorHofer - yes, the sfxproj would fail to build now as P1 SDK doesn't support <code>DotNetHostPath</code> argument, that was the main reason for the workaround in the first place. What is the scenario that requires building runtime using P1 SDK after you bumped up its version to P2 in the March infra rollout?

**Comment by ViktorHofer** [comment]
> What is the scenario that requires building runtime using P1 SDK after you bumped up its version to P2 in the March infra rollout?

The March infra rollout bumped the minimum required version of the SDK to 6.0 **Preview 1**: https://github.com/dotnet/runtime/commit/3e31241090bddac1e1fe5b87d56a427093705f78. The target version is currently a nightly preview 2 build, because we needed a newer SDK change in CI (for linker tests).

MSBuild respects and checks the minimum required SDK version but doesn't know anything about the target version in global.json as that's something Arcade custom. If you merge this change, a `dotnet build src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj` will fail without a corresponding SDK installed (>= 6.0 P2). Don't know how common it is to directly build the sfxprojs but it's something that would regress.

**Comment by ViktorHofer** [comment]
I recommend to hold this PR off until 4/5 (first Monday of April) when we will update to the next publicly available SDK which I believe will be Preview 2.

**Comment by trylek** [comment]
OK, I have marked it with the no-merge label; for now I assume this is going to be merged in as part of or after the April infra rollout per your suggestion.

**Comment by ViktorHofer** [comment]
Thanks for your understanding 👍

**Comment by mangod9** [comment]
Is the preview2 sdk integrated into runtime now, or will that happen with the April rollout.

**Comment by trylek** [comment]
As @ViktorHofer explained to me, in practice we're already consuming SDK Preview2 in the runtime repo but technically the runtime repo still supports SDK Preview1. For this reason I plan to rebase and merge this in after Viktor completes the April rollout next Monday (or maybe Tuesday considering next Monday is most likely national holiday in Austria just like in Czechia).

**Comment by ViktorHofer** [comment]
The PR is now unblocked as we just updated the SDK to 6.0 Preview 2: https://github.com/dotnet/runtime/pull/50084.

**Comment by trylek** [comment]
I have rebased the change and I plan to merge it in once testing successfully completes as the change has already been reviewed unless anyone objects.

**Comment by trylek** [comment]
I have rebased the change but now it's hitting a new error I didn't see previously; @jkoritzinsky, could you please take a quick look at the error message and advise me what else needs changing or what most likely broke it as I guess you'll see that off the top of your head? I believe the framework gets compiled successfully, this error happens when we compile the framework for the second time as part of CG2 publishing. Thank you in advance!

<pre>
D:\git\runtime5\.dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(404,5): error : Error: [D:\git\runtime5\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Crossgen2.sfxproj]
D:\git\runtime5\.dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(404,5): error :   An assembly specified in the application dependencies manifest (crossgen2.deps.json) has already been found but with a different file extension: [D:\git\runtime5\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Crossgen2.sfxproj]
D:\git\runtime5\.dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(404,5): error :     package: 'crossgen2', version: '6.0.0-dev' [D:\git\runtime5\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Crossgen2.sfxproj]
D:\git\runtime5\.dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(404,5): error :     path: 'crossgen2.dll' [D:\git\runtime5\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Crossgen2.sfxproj]
D:\git\runtime5\.dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(404,5): error :     previously found assembly: 'D:\git\runtime5\artifacts\bin\coreclr\windows.x64.Release\crossgen2\crossgen2.exe' [D:\git\runtime5\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Crossgen2.sfxproj]
D:\git\runtime5\.dotnet\sdk\6.0.100-preview.2.21155.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(404,5): error : Error: [D:\git\runtime5\src\installer\pkg\sfx\Microsoft.NETCore.App\Microsoft.NETCore.App.Crossgen2.sfxproj]
</pre>

**Pull request merged**
