### PR TITLE
[release/7.0] Turn in-build signing on

### PR DESCRIPTION
**Pull request by mmitche**
Only on in release branches

### CODE REVIEW

**Comment by mmitche** [comment]
Test build (with tweaked conditional): https://dev.azure.com/dnceng/internal/_build/results?buildId=1981480&view=results

**Review by carlossanlop — APPROVED** [review]
I assume the CI would show if this failed?

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
> I assume the CI would show if this failed?

No. The runtime-official.yml pipeline doesn't run publicly on PRs. We will see post-merge if this worked but based on these changes, they should work.

**Review by hoyosjs — APPROVED** [review]

**Comment by mmitche** [comment]
Passed here: https://dev.azure.com/dnceng/internal/_build/results?buildId=1981501&view=results

**Comment by mmitche** [comment]
@carlossanlop can you merge this? org JIT is down so I don't have perms right now

**Pull request merged**
