### PR TITLE
JIT: use bbID for pred list ordering

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Make `bbID` available in release builds, and use it to control the order of edges in the pred list. This removes the need for reordering pred lists when blocks are renumbered (`bbNum` changes, but `bbID` doesn't).

Also remove the need for sorting pred lists; in the one remaining place where sorting might be needed, just remove, modify, and then re-add the edge.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL
cc @dotnet/jit-contrib 

The pred sorting code was prominent in a profile shared by a 1st party.

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=821379&view=ms.vss-build-web.run-extensions-tab). For some reason not all of them are showing up. Looks like mostly code size improvements, and 0.15% or so TP win.

Here is the windows x64 code size diff / tp diffs extracted from the job log:

|Collection|Contexts with diffs|Improvements|Regressions|Same size|Improvements (bytes)|Regressions (bytes)|
|---|--:|--:|--:|--:|--:|--:|
|aspnet.run.windows.x64.checked.mch|1,137|<span style="color:green">581</span>|<span style="color:red">375</span>|<span style="color:blue">181</span>|<span style="color:green">-7,928</span>|<span style="color:red">+3,787</span>|
|benchmarks.run.windows.x64.checked.mch|607|<span style="color:green">335</span>|<span style="color:red">167</span>|<span style="color:blue">105</span>|<span style="color:green">-9,309</span>|<span style="color:red">+2,725</span>|
|smoke_tests.nativeaot.windows.x64.checked.mch|312|<span style="color:green">183</span>|<span style="color:red">82</span>|<span style="color:blue">47</span>|<span style="color:green">-4,580</span>|<span style="color:red">+1,051</span>|
|benchmarks.run_pgo.windows.x64.checked.mch|1,211|<span style="color:green">825</span>|<span style="color:red">306</span>|<span style="color:blue">80</span>|<span style="color:green">-6,773</span>|<span style="color:red">+2,709</span>|
|benchmarks.run_tiered.windows.x64.checked.mch|174|<span style="color:green">89</span>|<span style="color:red">57</span>|<span style="color:blue">28</span>|<span style="color:green">-2,373</span>|<span style="color:red">+750</span>|
|coreclr_tests.run.windows.x64.checked.mch|2,227|<span style="color:green">1,569</span>|<span style="color:red">394</span>|<span style="color:blue">264</span>|<span style="color:green">-17,926</span>|<span style="color:red">+5,167</span>|
|libraries.crossgen2.windows.x64.checked.mch|2,022|<span style="color:green">925</span>|<span style="color:red">597</span>|<span style="color:blue">500</span>|<span style="color:green">-12,960</span>|<span style="color:red">+7,370</span>|
|libraries.pmi.windows.x64.checked.mch|3,452|<span style="color:green">1,823</span>|<span style="color:red">985</span>|<span style="color:blue">644</span>|<span style="color:green">-35,822</span>|<span style="color:red">+14,803</span>|
|libraries_tests.run.windows.x64.Release.mch|4,877|<span style="color:green">2,396</span>|<span style="color:red">1,378</span>|<span style="color:blue">1,103</span>|<span style="color:green">-35,286</span>|<span style="color:red">+11,894</span>|
|benchmarks.run_tiered.windows.x64.checked.mch|174|<span style="color:green">89</span>|<span style="color:red">57</span>|<span style="color:blue">28</span>|<span style="color:green">-2,373</span>|<span style="color:red">+750</span>|
|smoke_tests.nativeaot.windows.x64.checked.mch|312|<span style="color:green">183</span>|<span style="color:red">82</span>|<span style="color:blue">47</span>|<span style="color:green">-4,580</span>|<span style="color:red">+1,051</span>|
||16,505|<span style="color:green">8,998</span>|<span style="color:red">4,480</span>|<span style="color:blue">3,027</span>|<span style="color:green">-139,910</span>|<span style="color:red">+52,057</span>|

-----

|Collection|PDIFF|
|---|--:|
|aspnet.run.windows.x64.checked.mch|<span style="color:green">-0.15%</span>|
|benchmarks.run.windows.x64.checked.mch|<span style="color:green">-0.18%</span>|
|smoke_tests.nativeaot.windows.x64.checked.mch|<span style="color:green">-0.16%</span>|
|benchmarks.run_pgo.windows.x64.checked.mch|<span style="color:green">-0.17%</span>|
|benchmarks.run_tiered.windows.x64.checked.mch|<span style="color:green">-0.17%</span>|
|coreclr_tests.run.windows.x64.checked.mch|<span style="color:green">-0.05%</span>|
|libraries.crossgen2.windows.x64.checked.mch|<span style="color:green">-0.09%</span>|
|libraries.pmi.windows.x64.checked.mch|<span style="color:green">-0.20%</span>|
|libraries_tests.run.windows.x64.Release.mch|<span style="color:green">-0.13%</span>|
|libraries_tests_no_tiered_compilation.run.windows.x64.Release.mch|<span style="color:green">-0.12%</span>|
|realworld.run.windows.x64.checked.mch|<span style="color:green">-0.14%</span>|

**Review by EgorBo — APPROVED** [review]
Interesting, I presume the TP wins are from removed `ensurePredListOrder`?

**Review by amanasifkhalid — APPROVED** [review]
Nice to see this get checked in. We can probably win back more TP now by skipping renumbering before LSRA without incurring diffs (since we search for block preds in that phase).

> The pred sorting code was prominent in a profile shared by a 1st party.

Are you planning on backporting this?

**Comment by AndyAyersMS** [comment]
> Interesting, I presume the TP wins are from removed `ensurePredListOrder`?

Sort of? It's mostly from no longer having to resort pred lists after renumbering blocks (we renumber fairly often).

**Comment by AndyAyersMS** [comment]
> Are you planning on backporting this?

No, I don't plan to... it was like 3% in the profile. But seeing it there reminded me it really shouldn't take any time at all.

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/99730

**Comment by BruceForstall** [comment]
`fgRenumberBlocks` now has an obsolete comment?

```
//   As a consequence of renumbering, block pred lists may need to be reordered.
```

**Pull request merged**
