### PR TITLE
Add explicit flushing to ProcessStartInfoTests

### PR DESCRIPTION
**Pull request by akoeplinger**
We're seeing some tests fail due to an invalid base64 string, see https://github.com/dotnet/runtime/issues/76140
We can't repro locally but one cause might be because the string isn't fully written yet, so try flushing.

Also capture the output so we can see what it was when something goes wrong.

### CODE REVIEW

**Comment by filipnavara** [comment]
Looks like invalid base64 indeed...

```
                 =================================================================
                 	Native Crash Reporting
                 =================================================================
                 Got a SIGABRT while executing native code. This usually indicates
                 a fatal error in the mono runtime or one of the native libraries 
                 used by your application.
                 =================================================================
                 
                 No native Android stacktrace (see debuggerd output).
                 
                 =================================================================
                 	Basic Fault Address Reporting
                 =================================================================
                 Memory around native instruction pointer (0x79f2626acc):0x79f2626abc  e3 83 00 91 c2 00 80 52 08 1e 80 52 01 00 00 d4  .......R...R....
                 0x79f2626acc  e1 03 00 91 c0 00 80 52 e2 03 1f aa e0 07 00 ad  .......R........
                 0x79f2626adc  fd ab 01 94 a1 63 00 91 40 00 80 52 e2 03 1f aa  .....c..@..R....
                 0x79f2626aec  f5 ab 01 94 80 15 80 52 17 ab 01 94 f3 03 00 aa  .......R........
                 
                 =================================================================
                 	Managed Stacktrace:
                 =================================================================
                 	  at <unknown> <0xffffffff>
                 	  at Globalization:LoadICU <0x00007>
                 	  at System.Globalization.GlobalizationMode:LoadICU <0x00023>
                 	  at Settings:.cctor <0x000bb>
                 	  at System.Object:runtime_invoke_void <0x0007f>
                 	  at <unknown> <0xffffffff>
                 	  at <unknown> <0xffffffff>
                 	  at System.Globalization.GlobalizationMode:get_Invariant <0x00023>
                 	  at System.Globalization.CultureData:CreateCultureWithInvariantData <0x00df3>
                 	  at System.Globalization.CultureData:get_Invariant <0x0004b>
                 	  at System.Globalization.CultureInfo:.cctor <0x00023>
                 	  at System.Object:runtime_invoke_void <0x0007f>
                 	  at <unknown> <0xffffffff>
                 	  at <unknown> <0xffffffff>
                 	  at System.Globalization.CompareInfo:.cctor <0x00023>
                 	  at System.Object:runtime_invoke_void <0x0007f>
                 	  at <unknown> <0xffffffff>
                 	  at <unknown> <0xffffffff>
                 	  at System.Reflection.AssemblyNameParser:Parse <0x002a7>
                 	  at System.Reflection.AssemblyNameParser:Parse <0x000eb>
                 	  at System.Reflection.AssemblyName:.ctor <0x0008f>
                 	  at Microsoft.DotNet.RemoteExecutor.Program:Main <0x0021b>
                 	  at <Module>:runtime_invoke_int_object <0x00087>
                 =================================================================
```

**Comment by stephentoub** [comment]
> so try flushing

Isn't the console stream's Flush a nop?

**Comment by filipnavara** [comment]
> > so try flushing
> 
> Isn't the console stream's Flush a nop?

It is, at least in normal circumstances. The debug print showed the crash message though.

**Comment by akoeplinger** [comment]
Yeah the flushing was just a shot in the dark, the crash report is indeed why it's not valid base64 😆 
Not really sure why it's trying to load ICU at that point though, will need to investigate.

**Comment by danmoseley** [comment]
It would be good to leave that logging in even after this is fixed.

**Comment by stephentoub** [comment]
@akoeplinger, if the flushing isn't the issue, should this be closed then?

**Pull request closed without merging**
