### PR TITLE
Fill out array bounds in metadata transform

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
The metadata writer will nullref if these are not set.

Found by pri0 tests.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Comment by jkotas** [comment]
> The metadata writer will nullref if these are not set.

Why have we not noticed this earlier?

**Comment by MichalStrehovsky** [comment]
> > The metadata writer will nullref if these are not set.
> 
> Why have we not noticed this earlier?

I have no idea

**Comment by MichalStrehovsky** [comment]
@dotnet/ilc-contrib could someone have a look?

**Comment by MichalStrehovsky** [comment]
The exception was somewhere during interning when we were trying to compare two ArraySignature records. Sorry, I don't have the stack anymore and getting a repro requires building the whole pri0 JIT subtree and I'm not keen on doing that again just to get an exception. The test build has incrementality issues.

The metadata writer schema doesn't generally tolerate nulls, to the extent of allocating everything upfront like this:

https://github.com/dotnet/runtime/blob/fbe5827984a2c24a14c7620e1da91c06304a9f01/src/coreclr/tools/aot/ILCompiler.MetadataTransform/Internal/Metadata/NativeFormat/Writer/NativeFormatWriterGen.cs#L4567-L4574

Bounds are not a `List<T>` so they don't get preallocated like this.

**Comment by jkotas** [comment]
> The exception was somewhere during interning when we were trying to compare two ArraySignature records

My guess is that it is caused by inconsistency between GetHashCode implementation and Equals implementation.

- GetHashCode tolarates nulls: https://github.com/dotnet/runtime/blob/fbe5827984a2c24a14c7620e1da91c06304a9f01/src/coreclr/tools/aot/ILCompiler.MetadataTransform/Internal/Metadata/NativeFormat/Writer/NativeFormatWriterGen.cs#L56-L69

- Equals does not tolerate nulls:
https://github.com/dotnet/runtime/blob/fbe5827984a2c24a14c7620e1da91c06304a9f01/src/coreclr/tools/aot/ILCompiler.MetadataTransform/Internal/Metadata/NativeFormat/Writer/NativeFormatWriterGen.cs#L43-L44

We were unlucky to get hash collision or something like that, that made us to execute Equals and crash.

Can we fix Equals and GetHashCode match to ensure that there are no hard-to-repro bugs like this? Either add null check to Equals, or delete the null check for GetHashCode, for sequences.

**Comment by MichalStrehovsky** [comment]
Fixed it by making GetHashCode non-tolerant to null. There was a similar problem for Lists so fixed that too.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
