### PR TITLE
Fixed XML docs for ILoggingBuilder AddProvider extension method

### PR DESCRIPTION
**Pull request by alefranz**
The description of the parameter was reversed.

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]

**Comment by gewarren** [comment]
Please also update the docs at dotnet/dotnet-api-docs when /// comments are updated in the source code. Otherwise, the fixes won't make it into the docs and IntelliSense.

**Comment by alefranz** [comment]
Apologies @gewarren, I wasn't aware of that. Raised https://github.com/dotnet/dotnet-api-docs/pull/4807.
Question for next time: is there a tool to copy the changes?

**Comment by gewarren** [comment]
> Apologies @gewarren, I wasn't aware of that. Raised [dotnet/dotnet-api-docs#4807](https://github.com/dotnet/dotnet-api-docs/pull/4807).
> Question for next time: is there a tool to copy the changes?

No worries, I wouldn't expect you to know that. Thanks for fixing it in the docs. There is a tool, but it only copies XML doc comments for brand new APIs.

**Pull request merged**
