### PR TITLE
Disable failing System.Reflection.Tests.ModuleTests.GetMethods

### PR DESCRIPTION
**Pull request by BruceForstall**
Tracking: https://github.com/dotnet/runtime/issues/50831

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
@BruceForstall, has this only ever failed in stress runs?  If yes, can we only disable it for such runs?

**Comment by BruceForstall** [comment]
It does look like it's only failed in libraries-jitstress modes, but one failure was in "no tiered compilation", and I'm not sure that counts as "stress" to the excluder code. Maybe switch to `[SkipOnCoreClr...`?

**Comment by BruceForstall** [comment]
fwiw, we really need a comprehensive "how to disable a test anywhere in the tree under any set of conditions" document...

**Comment by stephentoub** [comment]
> Maybe switch to [SkipOnCoreClr...?

That's what I was thinking, but if it might be failing elsewhere as well, we can stick with the "disable everywhere" for now.

**Comment by BruceForstall** [comment]
release coreclr windows x86 Debug failure:
```
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Http2_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:02:10
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Http2_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:04:22
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Http2_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:06:22
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Http2_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:08:22
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Http2_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:10:22
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Http2_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:12:22
['System.Net.Http.WinHttpHandler.Functional.Tests' WORK ITEM LOG TRUNCATED: Command timed out, and was killed]
```

**Pull request merged**
