### PR TITLE
Fix ISA outerloop tests

### LINKED ISSUE #86569: Test failure Interop\\COM\\Activator\\Activator\\Activator
Run: [runtime-coreclr jitstress-isas-x86 20230520.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280980&view=ms.vss-test-web.build-test-results-tab&runId=5573708&resultId=101773&paneView=debug)

Failed test:
```
coreclr windows x86 Checked jitstress_isas_x86_nosse41 @ Windows.10.Amd64.Open
- JIT\\PGO\\ProfileCastClassAndIsInst\\ProfileCastClassAndIsInst_random2\\ProfileCastClassAndIsInst_random2.cmd
- Interop\\COM\\Activator\\Activator\\Activator.cmd
- CoreMangLib\\system\\enum\\EnumIConvertibleToUint32\\EnumIConvertibleToUint32.cmd
- Loader\\classloader\\explicitlayout\\objrefandnonobjrefoverlap\\case11\\case11.cmd
- JIT\\RyuJIT\\DoWhileBndChk\\DoWhileBndChk.cmd
... ...

coreclr windows x86 Checked jitstress_isas_1_x86_nosse3 @ Windows.10.Amd64.Open
- readytorun\\determinism\\crossgen2determinism\\crossgen2determinism.cmd
- Interop\\MarshalAPI\\IUnknown\\IUnknownTest\\IUnknownTest.cmd
- Loader\\classloader\\MethodImpl\\CovariantReturns\\UnitTest\\UnitTest_GVM\\UnitTest_GVM.cmd
- Interop\\PInvoke\\Delegate\\DelegateTest\\DelegateTest.cmd
- Interop\\COM\\NETClients\\IInspectable\\NETClientIInspectable\\NETClientIInspectable.cmd
... ...

coreclr windows x86 Checked jitstress_isas_x86_nossse3 @ Windows.10.Amd64.Open
- CoreMangLib\\system\\type\\TypeGetType1\\TypeGetType1.cmd
- Loader\\classloader\\MethodImpl\\generics_override1\\generics_override1.cmd
- Loader\\classloader\\MethodImpl\\self_override3\\self_override3.cmd
- ilverify\\ILVerificationTests.cmd
- Interop\\PInvoke\\Variant\\VariantTest\\VariantTest.cmd
... ...

coreclr windows x86 Checked jitstress_isas_1_x86_nossse3 @ Windows.10.Amd64.Open
- Interop\\COM\\ComWrappers\\API\\ComWrappersTests\\ComWrappersTests.cmd
- Loader\\classloader\\DefaultInterfaceMethods\\regressions\\github60486\\github60486.cmd
- GC\\API\\GCSettings\\InputValidation\\InputValidation.cmd
- GC\\Regressions\\v2.0-beta1\\289745\\289745\\289745.cmd
- baseservices\\exceptions\\unittests\\Pending\\Pending.cmd
... ...

coreclr windows x86 Checked jitstress_isas_1_x86_nosse41 @ Windows.10.Amd64.Open
- baseservices\\exceptions\\unittests\\StrSwitchFinally\\StrSwitchFinally.cmd
- Interop\\ICustomMarshaler\\Primitives\\ICustomMarshaler_TargetWindows\\ICustomMarshaler_TargetWindows.cmd
- baseservices\\exceptions\\generics\\TypeParameter001\\TypeParameter001.cmd
- baseservices\\exceptions\\regressions\\V1\\SEH\\VJ\\NestedEx1\\NestedEx1.cmd
- baseservices\\exceptions\\stacktrace\\Tier1StackTrace\\Tier1StackTrace.cmd
... ...

coreclr windows x86 Checked jitstress_isas_x86_nosse3 @ Windows.10.Amd64.Open
- baseservices\\exceptions\\regressions\\v4.0\\640474\\test640474\\test640474.cmd
- baseservices\\exceptions\\generics\\TypeParameter006\\TypeParameter006.cmd
- baseservices\\exceptions\\exceptioninterop\\ExceptionInterop_ro\\ExceptionInterop_ro.cmd
- tracing\\eventpipe\\config\\name_config_with_pid\\name_config_with_pid.cmd
- Loader\\classloader\\explicitlayout\\objrefandnonobjrefoverlap\\case7\\case7.cmd
... ...

coreclr windows x86 Checked jitstress_isas_2_x86_nosse41 @ Windows.10.Amd64.Open
- baseservices\\exceptions\\sharedexceptions\\emptystacktrace\\OOMException01\\OOMException01.cmd
- GC\\Features\\LOHCompaction\\lohcompactapi_exceptions\\lohcompactapi_exceptions.cmd
- Interop\\COM\\Activator\\Activator\\Activator.cmd
- baseservices\\exceptions\\exceptioninterop\\ExceptionInterop\\ExceptionInterop.cmd
- Regressions\\coreclr\\16123\\ambiguousconstraint\\ambiguousconstraint.cmd
... ...

coreclr windows x86 Checked jitstress_isas_2_x86_nosse3_4 @ Windows.10.Amd64.Open
- Loader\\classloader\\MethodImpl\\CovariantReturns\\ReturnTypeValidation\\ImplicitOverrideSameSigAsDecl\\ImplicitOverrideSameSigAsDecl.cmd
- Loader\\classloader\\MethodImpl\\override_override1\\override_override1.cmd
- CoreMangLib\\system\\runtime\\interopservices\\marshal\\MarshalSizeOf2_PSC\\MarshalSizeOf2_PSC.cmd
- Interop\\StringMarshalling\\VBByRefStr\\VBByRefStrTest\\VBByRefStrTest.cmd
- Interop\\COM\\NETClients\\IDispatch\\NETClientIDispatch\\NETClientIDispatch.cmd
... ...

coreclr windows x86 Checked jitstress_isas_x86_nosse3_4 @ Windows.10.Amd64.Open
- Interop\\MarshalAPI\\IUnknown\\IUnknownTest\\IUnknownTest.cmd
- GC\\Features\\KeepAlive\\keepaliveother\\keepalivetry\\keepalivetry.cmd
- GC\\API\\GC\\GetConfigurationVariables\\GetConfigurationVariables.cmd
- Loader\\classloader\\MethodImpl\\CovariantReturns\\Interfaces\\UnsupportedScenario1\\UnsupportedScenario1.cmd
- GC\\Features\\Finalizer\\finalizeother\\finalizeexcep\\finalizeexcep.cmd
... ...

coreclr windows x86 Checked jitstress_isas_2_x86_nossse3 @ Windows.10.Amd64.Open
- Loader\\classloader\\TypeInitialization\\CctorsWithSideEffects\\CctorThrowInlinedStatic\\CctorThrowInlinedStatic.cmd
- CoreMangLib\\system\\delegate\\delegate\\DelegateRemove\\DelegateRemove.cmd
- Loader\\classloader\\DefaultInterfaceMethods\\regressions\\github60486\\github60486.cmd
- CoreMangLib\\system\\type\\TypeGetType2\\TypeGetType2.cmd
- GC\\API\\GCHandle\\PinObj_neg\\PinObj_neg.cmd
... ...

coreclr windows x86 Checked jitstress_isas_1_x86_nosse3_4 @ Windows.10.Amd64.Open
- ilasm\\System\\Runtime\\CompilerServices\\MethodImplOptionsTests\\MethodImplOptionsTests.cmd
- Loader\\classloader\\MethodImpl\\CovariantReturns\\ReturnTypeValidation\\OverrideSameSigAsDecl\\OverrideSameSigAsDecl.cmd
- readytorun\\tests\\mainv2\\mainv2.cmd
- JIT\\superpmi\\superpmicollect\\CscBench\\CscBench.cmd
- Interop\\COM\\NativeClients\\Primitives\\Primitives.cmd
... ...

coreclr windows x86 Checked jitstress_isas_2_x86_nosse3 @ Windows.10.Amd64.Open
- JIT\\RyuJIT\\DoWhileBndChk\\DoWhileBndChk.cmd
- Loader\\classloader\\generics\\Variance\\IL\\Unbox003\\Unbox003.cmd
- reflection\\GenericAttribute\\GenericAttributeTests\\GenericAttributeTests.cmd
- baseservices\\exceptions\\sharedexceptions\\emptystacktrace\\OOMException01\\OOMException01.cmd
- profiler\\eventpipe\\eventpipe_readevents\\eventpipe_readevents.cmd
... ...
```
**Error message:**
```
Assert failure(PID 5256 [0x00001488], Thread: 5456 [0x1550]): Assertion failed 'compIsaSupportedDebugOnly(InstructionSet_SSE41)' in 'System.Text.Unicode.Utf8Utility:TranscodeToUtf16(uint,int,uint,int,byref,byref):int' during 'Morph - Inlining' (IL size 1892; hash 0x7e314681; Tier0-FullOpts)


File: D:\a\_work\1\s\src\coreclr\jit\gentree.cpp Line: 22096
Image: C:\h\w\B07A094A\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\B07A094A\w\BAD409DB\uploads\Reports\JIT.PGO\ProfileCastClassAndIsInst\ProfileCastClassAndIsInst_random2\ProfileCastClassAndIsInst_random2.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B07A094A\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  ProfileCastClassAndIsInst_random2.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 5/20/2023 9:39:37 PM
Processing C:\cores\corerun.exe.5256.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\B07A094A\t\tmpobp0jz.tmp" -z "C:\cores\corerun.exe.5256.dmp"
stdout:
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.5256.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\B07A094A\p\PDB
Symbol search path is: C:\h\w\B07A094A\p\PDB
Executable search path is:
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.5125 (rs1_release.220429-1732)
Machine Name:
Debug session time: Sat May 20 21:40:03.000 2023 (UTC + 0:00)
System Uptime: 0 days 0:23:57.767
Process Uptime: 0 days 0:00:26.000
..............................


************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified


You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(1488.1550): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
eax=02f751f8 ebx=00000000 ecx=00000000 edx=00000000 esi=02f751a8 edi=02f751f8
eip=7015afeb esp=02f754dc ebp=02f76574 iopl=0         nv up ei pl nz ac pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000216
coreclr!FailFastOnAssert+0x21:
7015afeb 5e              pop     esi
0:000> cdb: Reading initial command '$<C:\h\w\B07A094A\t\tmpobp0jz.tmp'
0:000> .load C:\Users\runner.dotnet\sos\sos.dll
0:000> ~*k


.  0  Id: 1488.1550 Suspend: 0 Teb: 02d3f000 Unfrozen
ChildEBP RetAddr

02f754e8 7015bcd1 coreclr!FailFastOnAssert+0x21
02f76574 6fd46488 coreclr!_DbgBreakCheck+0x331
*** WARNING: Unable to verify checksum for clrjit.dll
02f765dc 6e927ce4 coreclr!CEEInfo::doAssert+0x68
02f7860c 6e975a8d clrjit!assertAbort+0xd8
02f78634 6ea7cd2c clrjit!Compiler::gtNewSimdGetElementNode+0xeb
02f786f0 6e97f0fd clrjit!Compiler::impSpecialIntrinsic+0x1597
02f78760 6e98939b clrjit!Compiler::impHWIntrinsic+0x730
02f78850 6e986a1e clrjit!Compiler::impIntrinsic+0x35c
02f789c4 6e9978cc clrjit!Compiler::impImportCall+0x466
02f790ac 6e993693 clrjit!Compiler::impImportBlockCode+0x3bb0
02f79124 6e992f92 clrjit!Compiler::impImportBlock+0xc2
02f79144 6e952aae clrjit!Compiler::impImport+0x290



Stack trace
   at JIT_PGO._ProfileCastClassAndIsInst_ProfileCastClassAndIsInst_random2_ProfileCastClassAndIsInst_random2_._ProfileCastClassAndIsInst_ProfileCastClassAndIsInst_random2_ProfileCastClassAndIsInst_random2_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/86569

### CODE REVIEW

**Comment by EgorBo** [comment]
@tannergooding PTAL, this unblocks outerloop and codegen for ToScalar seems ok on x86 without x86

**Review by tannergooding — APPROVED** [review]

**Comment by EgorBo** [comment]
Failures are https://github.com/dotnet/runtime/issues/86612

**Pull request merged**
