### PR TITLE
JIT: fix interaction of GDV and boxing

### PR DESCRIPTION
**Pull request by AndyAyersMS**
In #56126 we disabled GDV if the object being boxed came from a call with a
hidden return buffer pointer.

Fix this and enable GDV for these cases by inserting the box allocation before
the call.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
The issue is that in some cases, when generating the box newobj we actually create several statements, so all of them need to move as a group.

**Comment by AndyAyersMS** [comment]
I am seeing jit asserts in the dll import generator tests on Arm64 (which are new: https://github.com/dotnet/runtime/pull/59579)
```
/root/helix/work/correlation/dotnet exec --runtimeconfig DllImportGenerator.Tests.runtimeconfig.json --depsfile DllImportGenerator.Tests.deps.json xunit.console.dll DllImportGenerator.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: DllImportGenerator.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  DllImportGenerator.Tests (found 94 test cases)
  Starting:    DllImportGenerator.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 27 [0x0000001b], Thread: 43 [0x002b]): Assertion failed 'op2->TypeIs(TYP_LONG)' in 'Span:AndAllMembers(System.Span`1[BoolStruct],int):bool' during 'Lowering nodeinfo' (IL size 180)

    File: /__w/1/s/src/coreclr/jit/gentree.cpp Line: 2449
    Image: /root/helix/work/correlation/dotnet
```
Not sure if this is a PGO specific failure yet.

cc @AaronRobinsonMSFT

**Comment by AndyAyersMS** [comment]
Other than the failure above (which I suspect is unrelated) I think this is ready to go.

@EgorBo PTAL
cc @dotnet/jit-contrib

**Review by EgorBo — APPROVED** [review]

**Pull request merged**
