### PR TITLE
Do not add x86 host to PATH on 64-bit machines

### PR DESCRIPTION
**Pull request by NikolaMilosavljevic**
This fixes the remaining issue with non-native host paths in machine's environment (PATH).

The fix uses a different model than x64-on-arm64. It is a simpler change as it's easy to determine if machine is 64-bit, using WersionNT64 property. This solution avoids unnecessary changes in arcade infra and adding additional complexity.

### CODE REVIEW

**Comment by joeloff** [comment]
We should document this change so that users that only install the x86 SDK on a 64-bit OS manually update the PATH variable.

**Review by joeloff — APPROVED** [review]

**Comment by NikolaMilosavljevic** [comment]
> We should document this change so that users that only install the x86 SDK on a 64-bit OS manually update the PATH variable.

Yes, this needs to be documented as a breaking change. @richlander is there any guidance for publishing BCNs? I could help with that, unless there is an established process and team, to which I should defer this.

**Comment by richlander** [comment]
https://github.com/dotnet/runtime/blob/main/docs/project/breaking-change-process.md

**Pull request merged**
