### PR TITLE
[release/5.0] backports #67763: fix build with musl 1.2.3

### PR DESCRIPTION
**Pull request by ayakael**
Backports [#67762](https://github.com/dotnet/runtime/pull/67772) to release/5.0

### CODE REVIEW

**Comment by ayakael** [comment]
Patch as is builds fine on Alpine pipelines.

**Comment by carlossanlop** [comment]
@ayakael with 5.0 going out of support, do we still want to take this change? This also needs sign-off from area owner and needs to be approved by tactics to go through. I am adding the `servicing consider` label.

**Comment by carlossanlop** [comment]
Actually, this is the 5.0 backport. We won't be taking it since 5.0 is going out of support. cc @janvorli @mangod9

**Comment by mangod9** [comment]
yeah Ok to skip for 5.0

**Pull request closed without merging**
