### PR TITLE
Fix implicit nullchecks for floats on arm64

### LINKED ISSUE #65942: Test failure JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd
Run: [runtime-coreclr jitstress-isas-arm 20220226.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1634260&view=ms.vss-test-web.build-test-results-tab&runId=45274372&paneView=debug&resultId=106130)

Failed test:
```
CoreCLR windows arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ Windows.10.Arm64v8.Open
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR windows arm64 Checked jitstress_isas_nosimd @ Windows.10.Arm64v8.Open
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR windows arm64 Checked jitstress_isas_nohwintrinsic @ Windows.10.Arm64v8.Open
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR Linux arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR Linux arm64 Checked jitstress_isas_nohwintrinsic @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR Linux arm64 Checked jitstress_isas_nosimd @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ OSX.1200.ARM64.Open
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nohwintrinsic @ OSX.1200.ARM64.Open
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nosimd @ OSX.1200.ARM64.Open
- JIT\\Directed\\StructABI\\structreturn\\structreturn.cmd
```
**Error message:**
```
Assert failure(PID 6424 [0x00001918], Thread: 12796 [0x31fc]): Assertion failed '(shiftAmount == scale) || (shiftAmount == 0)' in 'TestHFAandHVA:TestReturnViaThrowing()' during 'Generate code' (IL size 37)

File: D:\a\_work\1\s\src\coreclr\jit\emitarm64.cpp Line: 6996
Image: D:\h\w\B0CA094F\p\corerun.exe
Return code:      1
Raw output file:      D:\h\w\B0CA094F\w\A50C090C\uploads\Reports\JIT.Directed\StructABI\structreturn\structreturn.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\B0CA094F\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  structreturn.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B0CA094F\p
D:\h\w\B0CA094F\w\A50C090C\e\JIT\Directed\StructABI\structreturn\structreturn.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Directed._StructABI_structreturn_structreturn_._StructABI_structreturn_structreturn_cmd()
```
Failed test:
```
CoreCLR windows arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ Windows.10.Arm64v8.Open
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR windows arm64 Checked jitstress_isas_nosimd @ Windows.10.Arm64v8.Open
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR windows arm64 Checked jitstress_isas_nohwintrinsic @ Windows.10.Arm64v8.Open
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR Linux arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR Linux arm64 Checked jitstress_isas_nohwintrinsic @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR Linux arm64 Checked jitstress_isas_nosimd @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ OSX.1200.ARM64.Open
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nohwintrinsic @ OSX.1200.ARM64.Open
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nosimd @ OSX.1200.ARM64.Open
- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd
```
**Error message:**
```
Assert failure(PID 1264 [0x000004f0], Thread: 584 [0x0248]): Assertion failed '(allRegs(theInterval->registerType) & mask) != 0' in 'projs.GitHub_35821:Main(System.String[]):int' during 'Linear scan register alloc' (IL size 48)

File: D:\a\_work\1\s\src\coreclr\jit\lsrabuild.cpp Line: 596
Image: D:\h\w\B0CA094F\p\corerun.exe
Return code:      1
Raw output file:      D:\h\w\B0CA094F\w\A494090D\uploads\Reports\JIT.Regression\JitBlue\GitHub_35821\GitHub_35821\GitHub_35821.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\B0CA094F\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  GitHub_35821.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B0CA094F\p
D:\h\w\B0CA094F\w\A494090D\e\JIT\Regression\JitBlue\GitHub_35821\GitHub_35821\GitHub_35821.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_GitHub_35821_GitHub_35821_GitHub_35821_._JitBlue_GitHub_35821_GitHub_35821_GitHub_35821_cmd()
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/65942#issuecomment-1063233714

### CODE REVIEW

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by AntonLapounov** [comment]
@EgorBo I hit the same assertion in my PR.  Is it a different issue?
https://github.com/dotnet/runtime/pull/71661/checks?check_run_id=7203673648
```
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 21 [0x00000015], Thread: 37 [0x0025]): Assertion failed '(shiftAmount == scale) || (shiftAmount == 0)' in 'Microsoft.CodeAnalysis.DotnetRuntime.Extensions.SyntaxValueProviderExtensions:<GetMatchingNodes>g__matchesAttributeName|4_2(byref,byref,System.String,bool,byref):bool' during 'Generate code' (IL size 286; hash 0x72e8996c; Tier1)

    File: /__w/1/s/src/coreclr/jit/emitarm64.cpp Line: 7028
```

**Comment by EgorBo** [comment]
@AntonLapounov could be 🤔 in theory can be caused by https://github.com/dotnet/runtime/pull/71439 - it sets nullchecks to be TYP_BYTE always even if we access a local of other type - it's ok on x64 but on ARM we're can't do that, scale must match input's type. cc @jakobbotsch

**Comment by jakobbotsch** [comment]
I'll take a look tomorrow, maybe we ended up in the box removal logic with a `GT_LEA` child node. Though it also seems like a backend bug if it cannot handle any combination of indirection and node computing an address.

**Pull request merged**
