### PR TITLE
Enable Console Logging test in NativeAOT

### PR DESCRIPTION
**Pull request by eerhardt**
Log_WritingScopes_LogsWithCorrectColorsWhenColorEnabled appears to be passing for me in NativeAOT on both Windows and Linux.

Contributes to #73436

### CODE REVIEW

**Review by LakshanF — APPROVED** [review]

**Review by tarekgh — APPROVED** [review]

**Comment by eerhardt** [comment]
@MichalStrehovsky @LakshanF - how do I tell if the test in question ran? I don't see it failing on any legs, but I'm also not sure it passed on all the NativeAOT legs either.

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky @LakshanF - how do I tell if the test in question ran? I don't see it failing on any legs, but I'm also not sure it passed on all the NativeAOT legs either.

I think it's good. I spot checked one of the helix logs - https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74381-merge-67c3cd974086489fa0/Microsoft.Extensions.Logging.Console.Tests/1/console.cb457c28.log?helixlogtype=result.

**Pull request merged**
