### PR TITLE
Try again to suppress stream tests on browser

### LINKED ISSUE #44214: BufferedAsyncFileStreamStandaloneConformanceTests.Read_EmptyStream_Nop_Success failing with PNSE
### Test
`System.IO.Tests.BufferedAsyncFileStreamStandaloneConformanceTests.Read_EmptyStream_Nop_Success` 
(Multiple variants)

- Failing since ~30/10~ #44069
- On queues: `ubuntu.1804.amd64.open`, `windows.10.amd64.server19h1.es.open`, `windows.81.amd64.open`

https://dev.azure.com/dnceng/public/_build/results?buildId=874130&view=ms.vss-test-web.build-test-results-tab

#### Linux:
```
System.PlatformNotSupportedException : Cannot wait on monitors on this runtime.
```

#### Windows:
```
System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
```

#### Linux
<details>

```
   at System.Threading.Monitor.ObjWait(Int32 millisecondsTimeout, Object obj)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.IO.FileStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at System.IO.FileStream.Read(Span`1 buffer)
   at System.IO.Tests.StreamConformanceTests.ReadAsync(ReadWriteMode mode, Stream stream, Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Tests.StandaloneStreamConformanceTests.Read_EmptyStream_Nop_Success(ReadWriteMode mode)
--- End of stack trace from previous location ---
```

</details>

#### Windows
<details>

```
   at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolBoundHandle.PlatformNotSupported.cs:line 24
   at System.IO.FileStream.Init(FileMode mode, FileShare share, String originalPath) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Windows.cs:line 91
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) in /_/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.cs:line 252
   at System.IO.Tests.FileStreamStandaloneConformanceTests.CreateStream(Byte[] initialData, FileAccess access) in /_/src/libraries/System.IO.FileSystem/tests/FileStream/FileStreamConformanceTests.cs:line 23
   at System.IO.Tests.FileStreamStandaloneConformanceTests.CreateReadOnlyStreamCore(Byte[] initialData) in /_/src/libraries/System.IO.FileSystem/tests/FileStream/FileStreamConformanceTests.cs:line 26
   at System.IO.Tests.StandaloneStreamConformanceTests.CreateReadOnlyStream(Byte[] initialData) in /_/src/libraries/Common/tests/Tests/System/IO/StreamConformanceTests.cs:line 653
   at System.IO.Tests.StandaloneStreamConformanceTests.Read_EmptyStream_Nop_Success(ReadWriteMode mode) in /_/src/libraries/Common/tests/Tests/System/IO/StreamConformanceTests.cs:line 833
--- End of stack trace from previous location ---
```

</details>

### PR DESCRIPTION
**Pull request by stephentoub**
Closes https://github.com/dotnet/runtime/issues/44214, take 2

### CODE REVIEW

**Comment by safern** [comment]
I wonder if the `PlatformSpecificAttribute` didn't work because it was on the abstract class...

**Review by akoeplinger — APPROVED** [review]

**Comment by stephentoub** [comment]
So.... the attribute was obviously having an impact when applied to the base type, as evidenced by the bazillion failures when I removed the attribute from the base.

**Comment by safern** [comment]
@stephentoub from looking at XUnit it seems like XUnit only get's traits from the first base class, it doesn't traverse the whole tree up:

https://github.com/xunit/xunit/blob/42bf9c19e5dbd7eec2512910bffb7faca9bab359/src/xunit.v3.core/Sdk/Frameworks/XunitTestCase.cs#L159-L167

So the ones that were still failing after you added the PlatformSpecifiAttribute to `StreamConformanceTests` had another base class who's base was then `StreamConformanceTests`. 

In the example you shared here: https://github.com/dotnet/runtime/issues/44214#issuecomment-721901202 we didn't have that case. 

I guess if we try doing: 
```cs
[PlatformSpecific(~TestPlatforms.Windows)]
    public abstract class BaseClassWithPlatformSpecific
    {
        [Fact]
        public void Test1()
        {
            if (OperatingSystem.IsWindows()) throw new Exception("Shouldn't have run");
        }
    }

    public class DerivedClassWithBasePlatformSpecific : BaseClassWithPlatformSpecific
    {
        [Fact]
        public void Test2()
        {
            if (OperatingSystem.IsWindows()) throw new Exception("Shouldn't have run");
        }
    }

   public class DerivedClassFromDerivedClassWithBasePlatformSpecific : DerivedClassWithBasePlatformSpecific 
    {
        [Fact]
        public void Test3()
        {
            if (OperatingSystem.IsWindows()) throw new Exception("Shouldn't have run");
        }
    }

```

I would expect Test3 to fail... I'm trying this locally now (you can try it as well).

**Comment by stephentoub** [comment]
> it seems like XUnit only get's traits from the first base class, it doesn't traverse the whole tree up

Thanks for investigating.  That design makes no sense to me.  But it does appear to be as you suggest.

**Comment by safern** [comment]
> Thanks for investigating. That design makes no sense to me.

It doesn't make sense to me either... seems like a non-intentional bug. @ViktorHofer I guess this XUnit pieces are still maintained?

**Comment by ViktorHofer** [comment]
> @ViktorHofer I guess this XUnit pieces are still maintained?

Yes and it will be shipping with v3. We should open an issue in xunit/xunit to discuss.

**Comment by stephentoub** [comment]
@safern, this doesn't fail for me:
```C#
[PlatformSpecific(~TestPlatforms.Windows)]
    public abstract class BaseClassWithPlatformSpecific
    {
        [Fact]
        public void Test1()
        {
            if (OperatingSystem.IsWindows()) throw new Exception("Shouldn't have run");
        }
    }

    public class DerivedClassWithBasePlatformSpecific : BaseClassWithPlatformSpecific
    {
        [Fact]
        public void Test2()
        {
            if (OperatingSystem.IsWindows()) throw new Exception("Shouldn't have run");
        }
    }

   public class DerivedClassFromDerivedClassWithBasePlatformSpecific : DerivedClassWithBasePlatformSpecific 
    {
        [Fact]
        public void Test3()
        {
            if (OperatingSystem.IsWindows()) throw new Exception("Shouldn't have run");
        }
    }
```
Does it for you?

**Comment by safern** [comment]
> Does it for you?

Hmmm no, my assumption was incorrect. I just tested this and it works fine. However I did find something. This is not failing on regular WASM test runs that use v8 runner. I just tested this exact scenario skipping them on Browser using our infrastructure to run with v8 and the tests didn't fail. 

I looked at the logs for the test failures you posted, and they are failing when running inside a browser which uses a more complex xharness infrastructure, so that is where it might be broken. If you look at the logs that you shared on the issue:
```
XHarness command issued: wasm test-browser --app=. --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js --output-directory=./xharness-output -- --working-dir=/test-dir --run WasmTestRunner.dll System.IO.FileSystem.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
Starting ChromeDriver 84.0.4147.0 (ff714bcb10c3356b1b1b2819148507a34fa4b1f8-refs/heads/master@{#768968}) on port 34779
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
```

**Comment by safern** [comment]
Ok, now I'm more confused than ever... tried to repro this locally using the `test-browser` command which runs inside a browser environment and didn't get a repro:

```cs
[PlatformSpecific(~TestPlatforms.Browser)]
    public abstract class BaseClassWithPlatformSpecific
    {
        [Fact]
        public void Test1()
        {
            if (OperatingSystem.IsBrowser()) throw new Exception("Shouldn't have run");
        }
    }

    public abstract class DerivedClassWithBasePlatformSpecific : BaseClassWithPlatformSpecific
    {
        [Fact]
        public void Test2()
        {
            if (OperatingSystem.IsBrowser()) throw new Exception("Shouldn't have run");
        }
    }

    public class DerivedClassFromDerivedClassWithBasePlatformSpecific : DerivedClassWithBasePlatformSpecific
    {
        [Fact]
        public void Test3()
        {
            Assert.False(true);
        }
    }
```

```
 XHarness command issued: wasm test-browser --app=. --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js --output-directory=/Users/santifdezm/repos/runtime/artifacts/bin/Microsoft.CSharp.Tests/net6.0-Release/browser-wasm/AppBundle/xharness-output -- --run WasmTestRunner.dll Microsoft.CSharp.Tests.dll -notrait category=OuterLoop -notrait category=failing
  Starting ChromeDriver 86.0.4240.22 (398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs/branch-heads/4240@{#378}) on port 55086
  Only local connections are allowed.
  Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
  ChromeDriver was started successfully.
  info: browser: Console websocket connected.
  info: URL ARG: arg=--run
  info: URL ARG: arg=WasmTestRunner.dll
  info: URL ARG: arg=Microsoft.CSharp.Tests.dll
  info: URL ARG: arg=-notrait
  info: URL ARG: arg=category=OuterLoop
  info: URL ARG: arg=-notrait
  info: URL ARG: arg=category=failing
  info: Arguments: --run,WasmTestRunner.dll,Microsoft.CSharp.Tests.dll,-notrait,category=OuterLoop,-notrait,category=failing
  info: MONO_WASM: Initializing mono runtime
  info: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
  info: mono_wasm_runtime_ready
  info: Initializing.....
  info: Discovering: Microsoft.CSharp.Tests.dll (method display = ClassAndMethod, method display options = None)
  info: Discovered:  Microsoft.CSharp.Tests.dll (found 309 of 312 test cases)
  info: Starting:    Microsoft.CSharp.Tests.dll
  info: Finished:    Microsoft.CSharp.Tests.dll
  info: 
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 4802, Errors: 0, Failed: 0, Skipped: 0, Time: 11.82394s
  info: 
  info: WASM EXIT 0
  XHarness exit code: 0
  XHarness artifacts: /Users/santifdezm/repos/runtime/artifacts/bin/Microsoft.CSharp.Tests/net6.0-Release/browser-wasm/AppBundle/xharness-output
```

**Comment by safern** [comment]
Hmmm even more weird. It seems like our simple repro is not a good enough repro. I went ahead and tried this on Windows. I added the following test to `BufferedAsyncFileStreamStandaloneConformanceTests` and `[PlatformSpecific(~TestPlatforms.Windows)]` to `StreamConformanceTests` and the test failed

```cs
        [Fact]
        public void Test3()
        {
            if (OperatingSystem.IsWindows()) throw new Exception("Shouldn't have run");
        }
```

```
System.IO.Tests.BufferedAsyncFileStreamStandaloneConformanceTests.Test3 [FAIL]
        System.Exception : Shouldn't have run
        Stack Trace:
          E:\repos\runtime\src\libraries\System.IO.FileSystem\tests\FileStream\FileStreamConformanceTests.cs(62,0): at System.IO.Tests.BufferedAsyncFileStreamStandaloneConformanceTests.Test3()
```

So there is something weird about this test setup that is causing them to not be skipped.

**Comment by safern** [comment]
Ok, I found what's going on FINALLY 😄 

It seems like if a Child class has a TraitAttribute, it will not honor the base class' TraitAttribute. In this case, `UnbufferedAsyncFileStreamStandaloneConformanceTests` and `BufferedAsyncFileStreamStandaloneConformanceTests` have an `ActiveIssueAttribute` so that is causing the `PlatformSpecificAttribute` on `StreamConformanceTests` to not be honored at all. 

This would be the minimal repro:
```cs
[PlatformSpecific(~TestPlatforms.Windows)]
public abstract class BaseClassWithPlatformSpecific
{
    [Fact]
    public virtual void Test1()
    {
        if (OperatingSystem.IsWindows()) throw new Exception("Shouldn't have run");
    }
}

[ActiveIssue("", TestPlatforms.Windows, TargetFrameworkMonikers.Netcoreapp, TestRuntimes.Mono)]
public class DerivedClassWithBasePlatformSpecific : BaseClassWithPlatformSpecific
{
    [Fact]
    public void Test2()
    {
        if (OperatingSystem.IsWindows()) throw new Exception("Shouldn't have run");
    }
}
```

This fails even on Windows. So this is definitely a XUnit bug rather than our test infrastructure.

**Comment by stephentoub** [comment]
Nice job tracking that down,  @safern! Armed with that knowledge,  I'll work around the bug in the morning.

**Comment by safern** [comment]
I opened: https://github.com/xunit/xunit/issues/2186

**Pull request closed without merging**
