### PR TITLE
Add custom name binding for .Net Configuration.

### PR DESCRIPTION
**Pull request by Coderrob**
Took a swag at addressing the gap between the Json source and the Binder projects. The Json settings I work with contain names that don't match the setting classes. Those are mapped by `JsonProperty` or `DataMember` where a name is given that can be mapped.

The binder project, rightfully, doesn't know about Json or any other formats. The one area where it could be built up more is around looking at the attributes associated with the properties of the object it's attempting to bind to the configuration dictionary. This is an attempt to try to just that.

Summary of the changes (Less than 80 chars):

- Added new BindingOption flag for binding by attribute names
- Broke out the property value lookup into a standalone function
- Added a function to return "name" values from custom attribute data from the PropertyType

Addresses issue https://github.com/dotnet/runtime/issues/36010

### CODE REVIEW

**Comment by Coderrob** [comment]
@maryamariyan Do you know what steps I should take for this PR? Seems like there is a CI/CD issue with installing required prerequisites for the failing tests.

**Comment by maryamariyan** [comment]
If you are [working on windows](https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md) is a doc page on requirements for building on windows.

A bit more on [building](https://github.com/dotnet/runtime/tree/master/docs/workflow/building/libraries) and [testing](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing.md).

Also note since you are adding API, the issue page needs to represent API proposal, usage, and the API needs approval as per guideline in [API review process](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md).

**Comment by Coderrob** [comment]
> If you are [working on windows](https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/windows-requirements.md) is a doc page on requirements for building on windows.
> 
> A bit more on [building](https://github.com/dotnet/runtime/tree/master/docs/workflow/building/libraries) and [testing](https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/libraries/testing.md).
> 
> From what I see in the CI results, there is an error on the test project. I think it will repro for you locally:
> 
> ```
> ConfigurationBinderTests.cs(221,31): error CS1061: (NETCORE_ENGINEERING_TELEMETRY=Build) 'BinderOptions' does not contain a definition for 'BindPropertyUsingAttributeName' and no accessible extension method 'BindPropertyUsingAttributeName' accepting a first argument of type 'BinderOptions' could be found (are you missing a using directive or an assembly reference?)
> ```
> 
> Also note since you are adding API, the issue page needs to represent API proposal, usage, and the API needs approval as per guideline in [API review process](https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md). PRs cannot be merged or approved until the API is approved first. We are approaching the 5.0 code complete this week, so chances are this would most probably fall on the 6.0 timeframe because it involves a new API.

@maryamariyan weird - all the other builds could reference it and the `runtime` builds there were the only ones error on `(NETCORE_ENGINEERING_TELEMETRY=InitializeToolset) Failed to install dotnet SDK from public location (exit code '1').`

Does this count as a new API? It adds a boolean binding property to the `BinderOptions` to allow custom name binding.

**Comment by davidfowl** [comment]
Yes it's new API and it's a new feature

**Comment by Coderrob** [comment]
Closing pending another issue to determine whether API is decided upon per request in issue https://github.com/dotnet/runtime/issues/36010

**Pull request closed without merging**
