### PR TITLE
Use adjusted parent layout size to handle a non-zero-sized class inheriting from a zero-sized class that inherits from another zero-sized class.

### LINKED ISSUE #50764: Marshalling record via PtrToStructure with two levels of inheritance shifts field offset
### Description

I've encountered this situation. I have the code below and after executed, the `result.Value` is `{ 0x02, 0x03, 0x00 }` instead of contents of data. Note: freeing memory stripped off for brevity.

```
public static void Main()
{
    Byte[] data = { 0x01, 0x02, 0x03 };
    GCHandle memory = GCHandle.Alloc(data, GCHandleType.Pinned);
    IntPtr handle = memory.AddrOfPinnedObject();
    FinalRecord result = (FinalRecord) Marshal.PtrToStructure(handle, typeof(FinalRecord));
}

[StructLayout(LayoutKind.Sequential)]
public abstract record BaseRecord;

[StructLayout(LayoutKind.Sequential)]
public abstract record InheritedRecord : BaseRecord;

[StructLayout(LayoutKind.Sequential)]
public sealed record FinalRecord : InheritedRecord
{
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)] 
    private readonly Byte[] Value;
}
```

But if I remove one level of inheritance (below), it works correctly again: `result.Value` is `{ 0x01, 0x02, 0x03 }`. I've digged a bit, but only thing I've found is that `Marshal.OffsetOf` the field is set to `0` when it's working and to `1` (for unknown reason) when it's not. As far as I know abstract/sealed/readonly has no effect on this. Only three (or more) levels of inheritance. It doesn't get worse with 4 levels (still shifted by 1 byte). Happens on both x86/x64 builds.

```
[StructLayout(LayoutKind.Sequential)]
public record InheritedRecord; // : BaseRecord;

```

### Configuration

Which version of .NET is the code running on? **.NET 5.0.4**
What OS and version, and what distro if applicable? **Windows 10** 20H2 (19042.906)
What is the architecture (x64, x86, ARM, ARM64)? **x64**
Do you know whether it is specific to that configuration? **No**, I don't. But I don't think it is.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
This should be the last fix for any of the zero-sized inheritance cases.

Fixes #50764

### CODE REVIEW

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
I assume we are folding this into the .NET 5 servicing change?

**Comment by elinor-fung** [comment]
> the .NET 5 servicing change

Are you talking about #50138 or something else? (Looks like that one got merged yesterday.)

**Comment by AaronRobinsonMSFT** [comment]
>Are you talking about #50138 or something else? (Looks like that one got merged yesterday.)

Sigh... yes. Do we think this needs to be included?

**Comment by jkoritzinsky** [comment]
Yeah I'll put together a minimal servicing change for this.

**Comment by elinor-fung** [comment]
Might be worth explicitly listing out all the scenarios we know about around this along with the previous behaviour vs. behaviour with these fixes? Especially with putting the changes in 5.0, considering we've already discovered various test gaps and things we had to re-fix.

**Pull request merged**
