### PR TITLE
Eliminate some redundant transient allocations

### PR DESCRIPTION
**Pull request by geeknoid**

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
Isn't this an observable behavioral change? If the implementation assumes it can mutate the options value passed into it (since the caller passed ownership of the options object to the callee), then the new code may result in implementations being able to mutate shared static state.

**Comment by geeknoid** [comment]
Yes, it has this potential.

However, the API contract is not stated clearly. As a consumer of the IDistributedCache interface, I would (and do) assume that I can reuse the DistributedCacheEntryOptions instance between calls. Given this use, which I have seen in more than one code base, I would argue that an implementation of IDistributedCache that mutates the entry option can likely be considered broken.

**Comment by Tratcher** [comment]
Assumptions make for a poor API contract. If re-use is part of the contract then it should be explicitly stated in the API docs.

**Comment by tarekgh** [comment]
I know the API contract is not clear but still it is potentially breaking even if users currently doing something breaking. I would suggest we can have internal private field inside `DistributedCacheEntryOptions` called like `_mutated` and can be set to true when the object is mutated. then before passing the static `_options` to other APIs, we can check if mutated then we reset `_options` to a new created object before passing it to the cache APIs. what you think about that?

**Comment by GrabYourPitchforks** [comment]
@tarekgh Your workaround sounds good, assuming you want to keep compat.

I should clarify my earlier comment. My intent was to call out that this would normally be considered a breaking change, and the area owners should weigh that as appropriate. I didn't mean to make a value judgment on whether this change was positive or negative. You all know my own personal stance on "we should break more often." :)

**Comment by tarekgh** [comment]
> I should clarify my earlier comment. My intent was to call out that this would normally be considered a breaking change, and the area owners should weigh that as appropriate. I didn't mean to make a value judgment on whether this change was positive or negative. You all know my own personal stance on "we should break more often." :)

Understood :-) 

These libraries are moved to our ownership recently and we still cannot tell exactly if we go with such breaking would be just ok or it can be a real issue. That is why I prefer for something like this one to not go with the breaking change while we can avoid it. In same time, we'll get the perf gain too.

**Comment by Tratcher** [comment]
Whatever you choose, please start clarifying the expected (re)use contract for these options types in their API docs.

**Comment by tarekgh** [comment]
> Whatever you choose, please start clarifying the expected (re)use contract for these options types in their API docs.

I opened the doc issue https://github.com/dotnet/dotnet-api-docs/issues/5454 track that.

@geeknoid could you please apply the suggestion https://github.com/dotnet/runtime/pull/48565#issuecomment-804223385 if you agree with so we can move forward with the PR? thanks for your help with this issue.

**Comment by tarekgh** [comment]
@geeknoid did you have a chance to look at the remaining feedback? we are trying to close the long-aged PR's. Please let's know or you need help someone address the remaining feedback. Thanks!

**Comment by geeknoid** [comment]
Yes, I did look at the feedback. I'm not thrilled with the idea of adding extra fields and logic in the option struct for a scenario that is realistically not happening in the field.

This is not a big deal, just a bit of perf hygiene. So I'll just close this PR, safe in the knowledge that you guys are now aware of the opportunities for improving the code in this area. As code owners, you can then assess the right way to deliver this improvement, if needed. 

Thanks.

**Pull request closed without merging**
