### PR TITLE
Add `Zero` and `IsZero` properties to `Quaternion`.

### LINKED ISSUE #57253: [API Proposal]: Quaternion.Zero is missing
### Background and motivation

Vector2, Vector3, and Vector4 when created with new() are all zeroed out and have corresponding `.Zero` static properties. `Quaternion` on the otherhand only has the `Identity` static property and doesn't have the corresponding `Zero` one to represent its base state when created with `new()`.

### API Proposal

```C#
namespace System.Numerics
{
     public class Quaternion
     {
        /// <summary>Gets a newly initialized quaternion.</summary>
        /// <value>A quaternion whose values are <c>(0, 0, 0, 0)</c>.</value>
        public static Quaternion Zero
        {
            get => new();
        }
     }
}
```     

### API Usage

```C#
// New Quaternion
var q = Quaternion.Zero;
q.X = 0.5;

// Checking
if (q == Quaternion.Zero)
{
  // Was uninitialized
}
```     

### Risks

No breaking changes, adds value to matching base struct types in the System.Numerics package for base initialization state.

### PR DESCRIPTION
**Pull request by Takym**
This pull request resolves #57253.

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
Hi @Takym! Thanks for the PR. Unfortunately the original issue is not yet marked __api-approved__, so we can't accept this PR at this time. See https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#pull-requests for more information on the API approval process and the timelines for when PRs are accepted.

**Comment by Takym** [comment]
Hello @GrabYourPitchforks! Thank you for replying. Do I need to re-create a PR when the original issue is marked as **api-approved**, or will you reopen this PR?

**Comment by GrabYourPitchforks** [comment]
I think you have the power to reopen the PR yourself at the right time. If not, leave a comment here and somebody should be able to reopen it on your behalf. The system won't auto-lock the issue for quite some time.

**Comment by Takym** [comment]
I clearly understood. Thanks.

**Comment by Takym** [comment]
The issue was marked as **api-approved**. So, would you please reopen this PR?

**Comment by GrabYourPitchforks** [comment]
@Takym Reopening. Only the `Zero` property was approved in API review; there didn't seem to be much love for an `IsZero` property.

Don't forget to update the ref assemblies and provide unit tests for the new API while you're at it. :)

**Comment by Takym** [comment]
I added property definitions to the reference assembly in 7a54468.

Also, I have created a "no `IsZero`" version below:
https://github.com/Takym/runtime/compare/Quaternion...Quaternion2

**Comment by stephentoub** [comment]
This can be closed now that https://github.com/dotnet/runtime/pull/58406 has been opened, yes?

**Comment by Takym** [comment]
@stephentoub Yes.

**Pull request closed without merging**
