### PR TITLE
Exclude delegates from ConfigurationBinder source generator

### LINKED ISSUE #94117: Exclude properties of delegate types in configuration source generator
Presently, the configuration source generator generates binding code for properties employing `delegate`, `Func`, or `Action` types. However, there is no means to bind configuration to such types. Consequently, the generator generates an abundance of code for all types associated with these delegates, many of which will not be utilized and may lead to code that does not compile. Here's an example:

https://github.com/dotnet/extensions/blob/14943b99572078f1bcf2c51e9507cf2631133fae/src/Libraries/Microsoft.Extensions.Resilience/Resilience/Internal/FailureEventMetricsOptions.cs#L11

This issue is tracking to fix the source generator to skip generating any code for such properties or types.

### PR DESCRIPTION
**Pull request by ericstj**
Fixes #94117

### CODE REVIEW

**Comment by davidfowl** [comment]
How does JSON avoid this problem? Does it has any logic for stopping the scan?

**Comment by ericstj** [comment]
Json allows folks to specify `JsonIgnore` on members you don't want it to mess with.  We don't have that *yet* but I discussed it here: https://github.com/dotnet/runtime/issues/93132
I'll double check if there's any default handling for wacky types in JSON.  Moving this to draft anyhow as I'm noticing I might have missed some places I need to block.

**Comment by ericstj** [comment]
This didn't fix the case where the Func was in an array, collection, etc.  The generator was throwing an IOE there.  Need to take a closer look at this code and see if there's a natural place to make type exclusions or if we'll need to add one.

**Comment by ericstj** [comment]
JSON has a default set of types, including delegates that it ignores: https://github.com/dotnet/runtime/blob/9461f4b5bd036005f37e78516c48b13396f76750/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs#L1687C26-L1687C43

**Comment by davidfowl** [comment]
> JSON has a default set of types, including delegates that it ignores: https://github.com/dotnet/runtime/blob/9461f4b5bd036005f37e78516c48b13396f76750/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs#L1687C26-L1687C43

This is what we have to do, not explode.

**Pull request closed without merging**
