### PR TITLE
Port NuGet Audit back to 9.0

### PR DESCRIPTION
**Pull request by ericstj**
Enables NuGet audit in 9.0 and fix the references of build tasks to avoid update churn.

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Review by jkoritzinsky — APPROVED** [review]

**Comment by ericstj** [comment]
@rainersigwald - can we count on System.Text.Json 8.0.5 being present in all VS versions that support using the 9.0 GA SDK?

**Comment by rainersigwald** [comment]
No, it's not in 17.12-preview3 and I'm not aware of plans to push it to preview4+. It's in 17.13-preview1.

Should we change that?

**Comment by ericstj** [comment]
I wanted to check before we pushed this into 9.0, I was triple checking this work for potential product fallout and this stood out.

> No, it's not in 17.12-preview3 and I'm not aware of plans to push it to preview4+. It's in 17.13-preview1.

I see - I think this means we need to keep the tasks at 8.0.4 and suppress the NuGet Audit warning.

**Comment by rainersigwald** [comment]
We just discussed this in Tactics but to preserve it: the current 17.11 patch release is relevant to the 9.0.100 SDK requirement to be buildable on day 1 of release, and it has 8.0.4, so the SDK **must** ship with 8.0.4 (for the references in build tasks and their dependencies).

**Comment by ericstj** [comment]
I made a change here.  I think I also made it so we won't need to chase our tail here if we have future CVE's in 8.0 STJ.  Can I get a new review?

**Review by rainersigwald — APPROVED** [review]
MSBuild stuff lgtm!

**Comment by ericstj** [comment]
Tell-mode infrastructure change, also discussed in tactics.

**Pull request merged**
