### PR TITLE
Mark EnumerateMetafileProc's callbackData parameter as nullable

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Follow up to #71225

### CODE REVIEW

**Comment by stephentoub** [comment]
Any idea why Graphics.cs is showing as every line having been edited?
image

**Comment by jkoritzinsky** [comment]
No clue. I edited it on the online editor. I'll retry the change from a local clone tomorrow.

**Comment by jkotas** [comment]
> Any idea why Graphics.cs is showing as every line having been edited?

Unix newlines got converted to Windows newlines. You can tell by looking at the file size on Unix or by opening the file on Unix in editor that is able to the diffence. You won't see any difference on Windows if you use default git settings. git converts Unix new lines to Windows new lines behind the scenes on Windows by default.

```
jkotas@jkotas11:~/runtime/src/libraries/System.Drawing.Common/src/System/Drawing$ ls -la Graphics.cs
-rw-r--r-- 1 jkotas jkotas 128939 Jun 23 22:01 Graphics.cs
jkotas@jkotas11:~/runtime/src/libraries/System.Drawing.Common/src/System/Drawing$ git checkout nullable-callbackdata
Switched to branch 'nullable-callbackdata'
Your branch is up to date with 'upstream/nullable-callbackdata'.
jkotas@jkotas11:~/runtime/src/libraries/System.Drawing.Common/src/System/Drawing$ ls -la Graphics.cs
-rw-r--r-- 1 jkotas jkotas 132393 Jun 23 22:02 Graphics.cs
```

**Comment by stephentoub** [comment]
I fixed it.

**Review by stephentoub — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
Failures are #70969 and https://github.com/dotnet/runtime/issues/70549#issuecomment-1152956584

**Pull request merged**
