### PR TITLE
Resolve tvOS/iOS FileSystem test failures

### LINKED ISSUE #67853: [tests][tvOS] Some System.IO tests are failing
OS: tvOS
Architecture: arm64
Configuration: release
Runtime: mono

It appears that some System.IO tests on tvOS have been silently failing for at least a month. The #67746 bugfix removes a crash that prevented xharness from reporting the test failures properly (e.g. [rolling build from 4/10](https://dev.azure.com/dnceng/public/_build/results?buildId=1709824&view=logs&j=f4520fb1-1559-5885-1d9c-3cb3f6a85e23&t=6c7a8cfe-f92e-569a-eef9-b2ad3e13056d) with this [System.IO.Tests output](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-preview1b4d075be3db04238bd/System.IO.Tests/1/net.dot.System.IO.Tests.log?sv=2019-07-07&se=2022-04-30T18%3A39%3A43Z&sr=c&sp=rl&sig=LeGYoJpKoDnBw%2BFDvgi1JfOz98Hij1%2BoOBXDzePP4J0%3D)).

The following tests are failing:
- `DevicesPipesAndSockets.NamedPipe_ReadWrite`
- `DevicesPipesAndSockets.NamedPipe_ReadWrite_Async`
- `NamedPipeFileStreamConnectedConformanceTests.Dispose_ClosesStream`
- `NamedPipeFileStreamConnectedConformanceTests.Read_Eof_Returns0`
- `NamedPipeFileStreamConnectedConformanceTests.Disposed_ThrowsObjectDisposedException`
- `NamedPipeFileStreamConnectedConformanceTests.ZeroByteWrite_OtherDataReceivedSuccessfully`
- `NamedPipeFileStreamConnectedConformanceTests.Read_DataStoredAtDesiredOffset`
- `NamedPipeFileStreamConnectedConformanceTests.ReadAsync_ContinuesOnCurrentTaskSchedulerIfDesired`
- `NamedPipeFileStreamConnectedConformanceTests.ReadAsync_CancelPendingTask_ThrowsCancellationException`
- `NamedPipeFileStreamConnectedConformanceTests.Write_DataReadFromDesiredOffset`
- `NamedPipeFileStreamConnectedConformanceTests.ReadAsync_ContinuesOnCurrentSynchronizationContextIfDesired`
- `NamedPipeFileStreamConnectedConformanceTests.ArgumentValidation_ThrowsExpectedException`
- `NamedPipeFileStreamConnectedConformanceTests.ReadTimeout_Expires_Throws`
- `NamedPipeFileStreamConnectedConformanceTests.Flush_ValidOnWriteableStreamWithNoData_Success`
- `NamedPipeFileStreamConnectedConformanceTests.ZeroByteRead_BlocksUntilDataAvailableOrNops`
- `NamedPipeFileStreamConnectedConformanceTests.ReadAsync_CancelPendingValueTask_ThrowsCancellationException`
- `NamedPipeFileStreamConnectedConformanceTests.ReadWriteAsync_PrecanceledOperations_ThrowsCancellationException`
- `NamedPipeFileStreamConnectedConformanceTests.Timeout_Roundtrips`
- `NamedPipeFileStreamConnectedConformanceTests.ReadWrite_CustomMemoryManager_Success`
- `NamedPipeFileStreamConnectedConformanceTests.Flush_ValidOnReadableStream_Success`
- `NamedPipeFileStreamConnectedConformanceTests.ReadWriteByte_Success`
- `NamedPipeFileStreamConnectedConformanceTests.ReadWrite_MessagesSmallerThanReadBuffer_Success`
- `NamedPipeFileStreamConnectedConformanceTests.CopyToAsync_AllDataCopied`
- `NamedPipeFileStreamConnectedConformanceTests.ReadWrite_Success`
- `Directory_ExistsAsFile.FalseForNonRegularFile`
- `DirectoryInfo_EnumFSI_str_str.SearchPatternCaseSensitive`
- `FileInfo_Exists.TrueForNonRegularFile`
- `Directory_Delete_str_bool.ExtendedDirectoryWithSubdirectories`
- `Directory_Delete_str_bool.LongPathExtendedDirectory`
- `File_GetSetAttributesCommon.SettingInvalidAttributes_UnixExceptOSXAndFreeBSD(attributes: Hidden)`
- `Directory_CreateDirectory.DriveLetter_Unix`
- `Directory_EnumFSE_str_str_so.SearchPatternCaseSensitive`
- `File_ReadWriteAllBytes.ReadAllBytes_NonSeekableFileStream_InUnix`
- `FileInfo_GetSetAttributesCommon.SettingInvalidAttributes_UnixExceptOSXAndFreeBSD(attributes: Hidden)`
- `PathFile_Exists.TrueForNonRegularFile`
- `DirectoryInfo_Delete_bool.ExtendedDirectoryWithSubdirectories`
- `DirectoryInfo_Delete_bool.LongPathExtendedDirectory`
- `File_ReadWriteAllBytesAsync.ReadAllBytesAsync_NonSeekableFileStream_InUnix`
- `File_ExistsAsDirectory.FalseForNonRegularFile`
- `Directory_GetLogicalDrives.GetsValidDriveStrings_Unix`
- `DirectoryInfo_Create.DriveLetter_Unix`
- `DirectoryInfo_Exists.FalseForNonRegularFile`
- `DirectoryInfo_Delete.ExtendedDirectoryWithSubdirectories`
- `DirectoryInfo_Delete.LongPathExtendedDirectory`
- `Directory_Delete_str.ExtendedDirectoryWithSubdirectories`
- `Directory_Delete_str.LongPathExtendedDirectory`

### PR DESCRIPTION
**Pull request by directhex**
Use SetCurrentDirectory on tests which use an unrooted path on non-Windows out of the app's working directory, which is readonly on some platforms.

Closes: #67853

### CODE REVIEW

**Comment by directhex** [comment]
Outstanding failures are unrelated infra, I think

**Review by carlossanlop — APPROVED** [review]
I see that you're wrapping some of those tests with a remote executor and adding the SetCurrentDirectory invocation at the beginning. I'd like to assume it's fine to do this in a remote executor context, because I worry that changing the current directory would affect the current process. But as long as that doesn't happen, we're ok.

I am also seeing that you're excluding tvos/ios/browser from the test platforms. I guess that is fine, because IIRC, remote executor does not work in any of those platforms.

@adamsitnik @Jozkee I'm approving it but if you can take an extra look, that would be great.

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @directhex !

**Pull request merged**
