### PR TITLE
WindowsService: Set the event log entry type according to whether it is an error or an information

### PR DESCRIPTION
**Pull request by zanseb**
Distinguish between an `information` or an `error` when creating an event log entry in `System.ServiceProcess.ServiceBase`

Fix for #37360

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=37513) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=37513) before we can accept your contribution.<br/><br/>:x: zanseb [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=37513)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=37513) it.</sub>

**Comment by zanseb** [comment]
According to the pipeline's output it appears that only the `SafeServiceControllerTests` are executed.

**Comment by danmosemsft** [comment]
Apologies for somehow missing this. It's a duplicate of #39766. Arbitrarily taking the other one since CI just ran on it. Sorry about that and thanks for the fix.

**Comment by NextTurn** [comment]
Apologies for not looking for duplicates when opening the PR. @danmosemsft You can merge the test here if it was passing.

**Pull request closed without merging**
