### PR TITLE
Mark UnmanagedCallersOnlyTest as NativeAOT incompatible

### PR DESCRIPTION
**Pull request by MichalStrehovsky**

### CODE REVIEW

**Comment by jkotas** [comment]
I have tried a simple repro:
```
using System.Runtime.InteropServices;

unsafe class Program
{
    static void Main()
    {
        new Program().ToString();
        delegate* unmanaged<void> p = &foo;
        p();
    }

    [UnmanagedCallersOnly]
    static void foo() // ildasm / change to instance method in IL / ilasm
    {
        Console.WriteLine("Here!");
    }
}
```
It still fails compilation with this change with:
```
ILC: Method '[repro]Program.foo()' will always throw because: UnmanagedCallersOnly attribute specified on non-static method 'Void Program.foo()'
Error: VTable of type 'System.InvalidProgramException' not computed by the IL scanner. You can work around by running the compilation with scanner disabled.
ILCompiler.ScannerFailedException: VTable of type 'System.InvalidProgramException' not computed by the IL scanner. You can work around by running the compilation with scanner disabled.
```

**Comment by jkotas** [comment]
> We try to prevent compiler crashes and aborts as much as reasonable. The justification is that if the problematic codepath exists, but it's unreachable with a JIT based runtime, the app would work despite having the problem. 

Yes, to the limit. I agree with this stance for stuff you can write in C#.  If you can only generate the bad IL using ilasm or some other non-C# compiler, I think it is fine for the compiler crash on it. We have not been trying to match behavior for bad IL between runtime and AOT compilers.

> We take this stance for missing references and other invalidness. In .NET Native times we saw a lot of invalid code being generated by non-C# compilers.

The goal for .NET Native for UWP was to get all apps, no matter how broken, AOT compiled and working. We do not have to the same bar for the current native AOT project.

The runtime failure mode if somebody tries to call this method is AV in stackwalk:
```
repro!StackFrameIterator::InternalInit+0x68:
00007ff7`7a4499e8 488b07          mov     rax,qword ptr [rdi] ds:0000b87e`fafb6000=????????????????
0:000> g
(3740.6bbc): Access violation - code c0000005 (!!! second chance !!!)
repro!StackFrameIterator::InternalInit+0x68:
00007ff7`7a4499e8 488b07          mov     rax,qword ptr [rdi] ds:000000b8`7efae800=00000254d70c0000
```
I think it is better to crash the compiler instead of being exposed to this failure mode.

**Comment by MichalStrehovsky** [comment]
This will be reachable by user written code once we fix the TODO to make this also throw when marshalling is needed (I'm touching that code here). Just make an unmanagedcallersonly with a book or something...

**Comment by jkotas** [comment]
We can make the UnmanagedCallersOnly with bool fail gracefully by skipping the `IsMarshallingRequired` check for `_isFallbackBodyCompilation`. C# enforces that arguments and return value of UnmanagedCallersOnly are unmanaged types, so the JIT should not have a problem with compiling the fallback method as proper reverse P/Invoke as long as you wrote it in C#.

**Review by jkotas — APPROVED** [review]
Thanks

**Pull request merged**
