### PR TITLE
[release/5.0] Extract bundled files when IncludeAllContentForSelfExtract is set

### PR DESCRIPTION
**Pull request by agocke**
## Description

Backport of #42435 to release/5.0.

This change fixes the "3.1 compat mode" for single-file. This flag allows people to return to the previous "extraction" behavior of single-file that was available in 3.1. 

## Customer impact

In certain scenarios, like use of changed APIs in a dependent library, this may be the only workaround for users who were previously using the 3.1 version of single-file. In compat testing, we found as many as half of the applications which worked with single-file were broken with the 5.0 changes.

## Regression

The 3.1 -> 5.0 mode was an intentional breaking change, and this mode was intended to be present to mitigate the break.

## Testing

Manual testing of all of the app compat libraries, both in the compat scenario, and in 5.0 after the compat fix.

## Risk

This change is entirely in single-file. It is a large change and bares moderate risk, but the risk would be isolated to single-file publishing.

(cherry picked from commit 0be66cbac680adc6ae1ec4c84adc028b2c340413)

### CODE REVIEW

**Comment by vitek-karas** [comment]
Are we going to merge with the other PR about native libs as well?

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  Please get crs and add the customer impact in the description.  We should consider this for GA

**Comment by agocke** [comment]
@vitek-karas Yes, I'm going to add the commit from https://github.com/dotnet/runtime/pull/42876 once that is merged

**Comment by agocke** [comment]
This should be up to date and ready for final review

**Review by vitek-karas — APPROVED** [review]

**Review by elinor-fung — APPROVED** [review]

**Review by mateoatr — APPROVED** [review]

**Pull request merged**
