### PR TITLE
JIT: fix remaining phases that were rebuilding pred edges

### LINKED ISSUE #49030: Loop opts should not be recomputing pred lists from scratch
Several loop opts end up calling `fgUpdateChangedFlowGraph` when done, and this calls `fgComputePreds`, leaking previous pred lists and losing the profile weights carefully calculated earlier.

This seems wrong-headed; I think those optimizations should maintain pred lists and not rebuild them.

Removing the call to `fgComputePreds` shows a number of places in loop opts where pred lists are not properly updated, and more downstream failures from places unknown where `BBF_JMP_TARGET` is not properly set, so cleaning this up may be nontrivial.

category:cq
theme:loop-opt
skill-level:expert
cost:medium
impact:medium

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Loop canonicalization now maintains pred edges. GC poll insertion was already maintaining the edges but was rebuilding them anyways.

Now pred lists are never rebuilt.

Also revise `fgUpdateChangedFlowGraph` so that it no longer has the ability to remove or rebuild.

Fixes #49030.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib 

A handful of diffs expected, where we now have original edge weights instead of freshly constructed "know nothing" weights.

**Comment by AndyAyersMS** [comment]
Seeing

```
Assert failure(PID 9175 [0x000023d7], Thread: 9191 [0x23e7]): Assertion failed '!varTypeUsesFloatReg(targetType) || (emitTypeSize(targetType) == emitTypeSize(op1Type))' in 'System.Numerics.Tests.Matrix3x2Tests:Matrix3x2EqualsNaNTest():this' during 'Generate code' (IL size 763; hash 0xd96aa0b9; FullOpts)
```
which is known stress issue #80773

**Review by BruceForstall — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=141322&view=ms.vss-build-web.run-extensions-tab)

Small TP win. Either rebuilding pred lists is pretty cheap or (more likely) most methods don't need gc polls or loop canonicalization. But that's not the point of this change - when we rebuild pred lists we throw away information, and (in upcoming work) we want to keep even more useful information there.

**Comment by AndyAyersMS** [comment]
Jitstress had some timeouts.

Libraries jitstress had some widespread issue that seems unrelated. I am going to merge since I think I fixed the relevant issue and hopefully tonight's runs on main will be good.

**Pull request merged**
