### PR TITLE
[mono][wasm] Exit with a nonzero exit code on asserts.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Review by lewing — APPROVED** [review]
This looks fine to me, are there other assertion paths we need to catch?  Are there other assertion paths we need to catch and should we stop invoking back into the runtime once we've exited?

**Comment by radical** [comment]
> .. should we stop invoking back into the runtime once we've exited?

for reference: https://github.com/dotnet/runtime/issues/51329

**Comment by radical** [comment]
The change works, yay! And also, now we can see the 174 library test suites [failing](https://dev.azure.com/dnceng/public/_build/results?buildId=1171651&view=logs&j=f217f715-90ad-5404-53bd-b93e3b80f465&t=9df76bd4-3041-5537-002b-9e29a53263b9) ;)

**Comment by radical** [comment]
.. and those failures should be fixed with https://github.com/dotnet/runtime/issues/53697 . But that wasn't merged in this yet.

**Review by radical — APPROVED** [review]

**Pull request merged**
