### PR TITLE
Add FreeBSD-specific logic to pal::get_default_installation_dir_for_arch

### PR DESCRIPTION
**Pull request by arrowd**
The full problem context: https://reviews.freebsd.org/D44560

This change tries to address it for the native FreeBSD case. The Linuxulator case can hopefully be fixed by installing `/compat/linux/etc/dotnet/install_location`.

@sec @Thefrank can you look into this?

### CODE REVIEW

**Comment by arrowd** [comment]
@dotnet-policy-service agree

**Comment by Thefrank** [comment]
LGTM

As an aside: `/etc/dotnet/install_location` file did also work for FreeBSD. I can only find documentation of it in design docs: https://github.com/dotnet/designs/blob/main/accepted/2020/install-locations.md so this may have changed.

**Comment by arrowd** [comment]
On FreeBSD the `/etc` is reserved for the base system usage. Third-party software should use a prefix path called LOCALBASE which defaults to `/usr/local`.

**Comment by Thefrank** [comment]
Fair point. That file would not make sense for a FreeBSD port.

oooh! That differential also has a working powershell port from "zirias" which means I can close out 3 upstream PRs for getting FreeBSD added to the 3 powershell repos. Happy to see someone get that over the finish line

**Comment by sec** [comment]
@arrowd LGMT. IIRC setting `DOTNET_ROOT` also works, as I use it on my machines, but your fix is more elegant.

**Comment by Thefrank** [comment]
Looking at this and according to [hier(7)](https://man.freebsd.org/cgi/man.cgi?query=hier%287%29&apropos=0&sektion=0&manpath=FreeBSD+14.0-RELEASE+and+Ports&arch=default&format=html), `share` is for architecture-independent files. I am not sure this location is a good fit for `dotnet`, however this specific file is actually arch agnostic as any arch of `dotnet` will look for it.  As you are the port maintainer, I will defer to you where you want the files. hier(7) is more guidance than law as per the notes.

**Comment by arrowd** [comment]
Bump. Can we get this in?

**Comment by agocke** [comment]
@elinor-fung  for review

**Review by jkotas — APPROVED** [review]

**Review by elinor-fung — APPROVED** [review]

**Pull request merged**
