### PR TITLE
Build NativeAOT-iOS runtime tests as standalone to restore test runs

### LINKED ISSUE #107346: [Infra][NativeAOT-iOS] Runtime tests workitems not getting sent to helix
After https://github.com/dotnet/runtime/pull/107002, NativeAOT on IOS runtime tests are not getting bundled for Helix, reporting `error : SendHelixJob given no WorkItems to send.`

First failing build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=793084&view=logs&j=6ad81d5f-e956-5767-2437-61a9fc4dc8db&t=c71d6c6f-8520-5c9e-5bd9-f9fda7bcc121

image

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes Issue https://github.com/dotnet/runtime/issues/107346

cc: @matouskozak

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
CI shows the correct tests running again for the NativeAOT legs.

**Review by matouskozak — APPROVED** [review]
Thanks for the quick fix. 
fyi: @ivanpovazan @kotlarmilos

**Comment by ivanpovazan** [comment]
Hey @jkoritzinsky thanks for fixing this quickly! 

One thing that is missing, is doing the same for `maccatalyst` jobs running NativeAOT runtime tests, so adding `buildAllTestsAsStandalone: true`
to somewhere around here:
https://github.com/dotnet/runtime/blob/88f9aba91e11d1695ebe9ab572736ee62ac7ad61/eng/pipelines/extra-platforms/runtime-extra-platforms-maccatalyst.yml#L114-L116
and here:
https://github.com/dotnet/runtime/blob/88f9aba91e11d1695ebe9ab572736ee62ac7ad61/eng/pipelines/extra-platforms/runtime-extra-platforms-maccatalyst.yml#L151-L153
should do the trick.

Failure for reference (from the original failing build): https://dev.azure.com/dnceng-public/public/_build/results?buildId=793084&view=logs&j=c49026c0-42bb-519d-cdde-df21b0e596aa&t=246f45a3-de00-568c-c61c-f424913337a0&l=26

**Comment by jkoritzinsky** [comment]
I'll make sure to do the maccatalyst jobs as well before merging today. Thanks for the heads up!

**Pull request merged**
