### PR TITLE
[mono][aot] Fixed decompose_flag propagation issues

### PR DESCRIPTION
**Pull request by jandupej**
Addresses #79710.

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by jandupej** [comment]
Some build failures due to https://github.com/dotnet/runtime/issues/79843.

**Comment by lewing** [comment]
should this go back to 6.0 too?

**Comment by jandupej** [comment]
@lewing https://github.com/dotnet/runtime/issues/79710 mentions the issue does occur with 6.0.

**Pull request merged**
