### PR TITLE
Ignore type resolution failures when checking for attributes in `StackTrace.ToString`.

### LINKED ISSUE #104528: F# program fails with an unprintable exception when `FSharp.Core` is not referenced.
### Description

I have noticed a reincarnation of #39910 in an F# project of mine. I have disabled automatic referencing of `FSharp.Core` in the solution but had forgotten to manually reference it in one of the executables. When trying to run it it failed with a `FileNotFoundException`, which was however not able to be printed to the console.

### Reproduction Steps

Compile and run the following F# project:

__fsharp-repro.fsproj__
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="Program.fs"/>
    </ItemGroup>
</Project>
```

__Program.fs__
```fsharp
module Program

[<EntryPoint>] // Without an explicit entry point method, it does not reproduce.
let main _ =
    printfn "Hello from F#"
    0
```

### Expected behavior

Program fails with:

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'FSharp.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Δεν είναι δυνατή η εύρεση του καθορισμένου αρχείου από το σύστημα.
File name: 'FSharp.Core, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at <StartupCode$fsharp-repro>.$Program.main@()
```

### Actual behavior

Program fails with:

```
Unhandled exception. 
   Cannot print exception string because Exception.ToString() failed.
```

### Regression?

I managed to reproduce the issue on .NET 6 and .NET 8. It does not reproduce on .NET Framework.

### Known Workarounds

_No response_

### Configuration

.NET 8

### Other information

Since dotnet/coreclr#14655 when formatting a stacktrace, we have been checking if every method in the stacktrace exists in a type that has the `CompilerGeneratedAttribute` applied.

However, the `main` method is declared in an F# module, which is marked with an attribute in the `FSharp.Core` assembly. The call to `IsDefined(typeof(CompilerGeneratedAttribute))` tries to resolve that attribute type, fails because `FSharp.Core` is not found, which causes formatting the stacktrace to fail, and the program to fail with a vague message.

Checking for the presence of `StacktraceHiddenAttribute` in the method (which we are doing earlier and would also fail for `main` because of `[<EntryPoint>]`) does not fail because that code is already guarded for exceptions since #48535.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
Fixes #104528.

Similar to #48535, this PR makes `StackTrace.ToString` resilient to exceptions when performing some more custom attribute retrieving. We do this by introducing `***Safe` edition of reflection methods that perform the operation and return a negative result if an exception was thrown, and updating all uses of `IsDefined` and `GetCustomAttributes` in the `StackTrace` class.

### CODE REVIEW

**Comment by jkotas** [comment]
I do not think we want to be catching exceptions in reflection to make it resilient against missing assemblies. It is very fragile path. For example, this fix would make unsealing an attribute potentially breaking change going forward.

https://github.com/dotnet/runtime/pull/48535 should be fixed by ignoring reflection failures in the stacktrace printing code.

**Comment by teo-tsirpanis** [comment]
> For example, this fix would make unsealing an attribute potentially breaking change going forward.

Didn't think about this, thanks! I updated the PR as you suggested, and guarded another possible source of resolver failures.

**Comment by jkotas** [comment]
Build breaks...

**Comment by teo-tsirpanis** [comment]
Fixed build failures. Current CI failures are seemingly unrelated.

**Review by jkotas — APPROVED** [review]
LGTM! Thanks

**Pull request merged**
