### PR TITLE
add back stress run readme

### PR DESCRIPTION
**Pull request by Maoni0**
when the test src was moved this file didn't get moved so added it back; also adjusted dirs in it to the new locations.

### CODE REVIEW

**Comment by cshung** [comment]
The file is available here now
https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/coreclr/gc-stress-run-readme.md

**Comment by Maoni0** [comment]
oh lol...I totally forgot about it and also did not notice that the dirs in it were not changed.

**Comment by Maoni0** [comment]
@cshung would you like to correct the dirs in the doc you checked in? I'm referring to these -

    The stress framework is built from <REPO_ROOT>\src\coreclr\tests\src\GC\Stress\Framework

    The tests are built from <REPO_ROOT>\src\coreclr\tests\src\GC\Stress\Tests

    The config is at <REPO_ROOT>\src\coreclr\tests\src\GC\Stress\testmix_gc.config, this will be copied to the output folder of Framework

The easiest way to build the Framework+Tests is by building all tests - <REPO_ROOT>\src\coreclr\build_test[.bat|.sh]

**Comment by cshung** [comment]
> @cshung oh lol...I totally forgot about it. sorry! would you like to correct the dirs in the doc you checked in? 

Working on it, https://github.com/dotnet/runtime/pull/45392

**Comment by Maoni0** [comment]
thank you @cshung. I will close this PR then.

**Pull request closed without merging**
