### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by ShuiRuTian**
Change "text=auto" to "text" for non-binary files

### CODE REVIEW

**Comment by jkotas** [comment]
@ShuiRuTian What is the motivation for this change?

**Comment by ShuiRuTian** [comment]
- To make things a bit clearer. 
- I copied CLR's .gitattributes and want to feedback the upstream.

A file is either binary or text. According to https://mirrors.edge.kernel.org/pub/software/scm/git/docs/gitattributes.html#_end_of_line_conversion, if "text=auto" is set, git need to judge whether it's binary or text. This might be a reasonable default behavior, but for a known file extension it seems to be meaningless.

And since git would not need to judge whether a file is binary or text, it might be little faster, although it's not motivation.

**Review by agocke — APPROVED** [review]

**Comment by agocke** [comment]
/ba-g re-run seems to be stuck, but this passed all the important builds.

**Comment by agocke** [comment]
@ShuiRuTian Thanks!

**Pull request merged**
