### PR TITLE
[mono] Force AOT+interpreter for iOSSimulator arm64 library test local build

### PR DESCRIPTION
**Pull request by mdh1418**
When building library tests on iOSSimulator arm64, `Thread 6: EXC_BAD_ACCESS (code=1, address=0x0)` was being hit at https://github.com/dotnet/runtime/blob/7e175e615eedabb42d7a7b3d6a08cbf926cbc94f/src/mono/mono/mini/tramp-arm64.c#L571
`./build.sh -s mono+libs -os iOSSImulator -arch arm64 -c Debug`
`./dotnet.sh build /t:Test /p:TargetOS=iOSSimulator /p:TargetArchitecture=arm64 /p:Configuration=Debug src/libraries/System.Buffers/tests`

iOSSimulator arm64 doesn't support JIT, so we need to force AOT+interpreter.

This PR does the following to improve local development experience:
Sets `RunAOTCompilation` to true (if unset) automatically for iOS/tvOS device/sims arm64
Sets `MonoForceInterpreter` to true (if unset) automatically for iOS/tvOS simulators arm64
Sets `MonoAotOption` `"Interp"` if `MonoForceInterpreter` is set.

Now, contributors can run library tests for iOSlike arm64 platforms without manually specifying `RunAOTCompilation=True` `MonoForceInterpreter=True`, making the library testing experience more uniform.

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]
LGTM. Do you plan to update the samples and functional tests too?

**Comment by steveisok** [comment]
@mdh1418 can you bring this up to date and if it's all good, merge?

**Comment by mdh1418** [comment]
The failing test on iOSlike is filed at https://github.com/dotnet/runtime/issues/78380

**Pull request merged**
