### PR TITLE
Remove the src/mono/netcore directory, move its contents to src/mono.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by steveisok** [comment]
There are subfolders mono and wasm still in there.  Not that I like the name netcore, but I still think it's important to differentiate.

**Comment by srxqds** [comment]
> There are subfolders mono and wasm still in there. Not that I like the name netcore, but I still think it's important to differentiate.

just like coreclr, made mono/mono to mono/vm ?

**Comment by vargaz** [comment]
> There are subfolders mono and wasm still in there. Not that I like the name netcore, but I still think it's important to differentiate.

netcore was added as a place to put netcore only stuff in the old repo, its not needed in the new one, since everything is netcore.

**Comment by lambdageek** [comment]
Should we merge `src/mono/netcore/.gitignore` into `src/mono/.gitignore`?

**Review by lambdageek — APPROVED** [review]

**Pull request merged**
