### PR TITLE
NativeAOT: Conversion for opcode conv_u4 is unsigned

### PR DESCRIPTION
**Pull request by yowl**
This PR makes the conversion for `conv_u4` unsigned, matching `conv_u8` in the following switch case.  Originates from https://github.com/dotnet/runtimelab/pull/1994#discussion_r983065472

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Do we have the same bug here?

https://github.com/dotnet/runtime/blob/43fa22f07449f24f6959b959e49c69aff91a8a14/src/coreclr/tools/Common/TypeSystem/IL/ILImporter.cs#L822-L824

**Review by MichalStrehovsky — APPROVED** [review]
Thanks!

**Comment by jkotas** [comment]
> Do we have the same bug here?

I think so - pushed commit with the fix.

**Comment by yowl** [comment]
> I think so - pushed commit with the fix.

Thanks!

**Pull request merged**
