### PR TITLE
JIT: Mark replacements as dirty after setting GTF_VAR_DEATH

### LINKED ISSUE #88616: Fuzzlyn failure on linux arm64
Fuzzlyn failure on linux arm64. Possibly from a change on or after 2023-07-02.

```csharp
// Generated by Fuzzlyn v1.5 on 2023-07-09 18:33:04
// Run on Arm64 Linux
// Seed: 15657484969728248792
// Reduced from 43.9 KiB to 2.0 KiB in 00:01:40
// Debug: Outputs 0
// Release: Outputs 1
public class C0
{
    public int F7;
}

public struct S0
{
    public long F0;
    public int F1;
    public ushort F2;
    public byte F3;
    public ulong F4;
    public S0(long f0, int f1, byte f3, ulong f4): this()
    {
        F0 = f0;
        F1 = f1;
        F3 = f3;
        F4 = f4;
    }
}

public class Program
{
    public static IRuntime s_rt;
    public static S0 s_1;
    public static byte[][] s_4 = new byte[][]{new byte[]{0}};
    public static S0 s_10;
    public static void Main()
    {
        s_rt = new Runtime();
        C0 vr43 = new C0();
        var vr26 = new C0();
        ushort vr44 = default(ushort);
        var vr27 = (short)vr44;
        var vr32 = (ushort)0;
        var vr33 = new ushort[]{0};
        var vr34 = (short)Program.M7(vr26, 0, ref s_1.F1, vr27, vr32, vr33);
        var vr35 = new ushort[]{1};
        ushort vr36 = (ushort)Program.M7(vr43, 0, ref s_1.F1, vr34, 0, vr35);
        S0 vr37 = new S0(0, 0, 0, 0);
        var vr38 = vr36 == vr37.F1;
        short vr39 = (short)M5(vr38, vr37);
        vr37.F2 = 0;
        var vr40 = new S0(s_10.F0, 0, vr37.F3, vr37.F4);
        var vr41 = new sbyte[]{0};
        M11(vr40, vr41) = vr37.F3;
        var vr42 = vr37.F0--;
        vr37.F4 = 0;
        M5(true, vr37);
        s_rt.WriteLine(vr37.F1);
    }

    public static int M5(bool arg0, S0 arg3)
    {
        s_rt.WriteLine(arg3.F1);
        var vr9 = new C0();
        ref int vr65 = ref arg3.F1;
        vr9.F7 = vr65++;
        return 0;
    }

    public static ulong M7(C0 argThis, uint arg0, ref int arg1, short arg2, ushort arg3, ushort[] arg4)
    {
        return 0;
    }

    public static ref byte M11(S0 argThis, sbyte[] arg3)
    {
        argThis.F4 = 0;
        arg3 = new sbyte[]{1};
        return ref s_4[0][0];
    }
}

public interface IRuntime
{
    void WriteLine<T>(T value);
}

public class Runtime : IRuntime
{
    public void WriteLine<T>(T value) => System.Console.WriteLine(value);
}
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
Physically promoted struct locals are marked as dying when their remainder dies since all other state is stored in other locals. However, when we do this we must also mark all replacements as stale; otherwise a future struct use could skip writebacks and effectively introduce new uses, invalidating the previously marked last use bit.

Fix #88616

Note that the regression test introduced here requires #88665 to actually fail.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS

[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=335462&view=ms.vss-build-web.run-extensions-tab).

Looks like I'll need to rerun CI; license/cla seems to be stuck.

**Review by AndyAyersMS — COMMENTED** [review]
I am confused about something here -- are we somehow avoiding making a copy of `foo` to pass to `Mutate`?

**Comment by AndyAyersMS** [comment]
> I am confused about something here -- are we somehow avoiding making a copy of `foo` to pass to `Mutate`?

Your repro case passes for me w/o your fix and makes a copy to pass to `Mutate`

**Comment by jakobbotsch** [comment]
> I am confused about something here -- are we somehow avoiding making a copy of `foo` to pass to `Mutate`?

> Your repro case passes for me w/o your fix and makes a copy to pass to `Mutate`

Yes, we avoid the copy, but the particular test I have introduced requires #88665 to actually expose the problem. Without that change we do not mark `foo` as a last use when passed to the first call because we think the second appearance uses the remainder (even though there is none).

The Fuzzlyn found test case is more complex but repros the bug without #88665. The found test case there has an actual unpromoted remainder and redefines it between the two calls which has the effect of both uses of `vr37` being marked as last uses.

**Comment by jakobbotsch** [comment]
There's a couple of [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338030&view=ms.vss-build-web.run-extensions-tab) now with this change after #88665 was merged. The diffs failure is some internal server error from Helix. The other failures are the known file check ones, it seems.

**Review by AndyAyersMS — APPROVED** [review]

**Pull request merged**
