### PR TITLE
Delete task code that has been moved to the shared framework SDK in Arcade

### PR DESCRIPTION
**Pull request by v-chayan**
Deleted below files that were moved to Arcade.
BuildFPMToolPreReqs.cs
CopyNupkgAndChangeVersion.cs
CreateFrameworkListFile.cs
ExecWithRetries.cs
GenerateDebRepoUploadJsonFile.cs
GenerateJsonObjectString.cs
ProcessSharedFrameworkDeps.cs
RuntimeGraphManager.cs
RuntimeReference.cs
StabilizeWixFileId.cs
ZipFileExtractToDirectory.cs
ZipFileGetEntries.cs

### CODE REVIEW

**Comment by ViktorHofer** [comment]
The regenerate readme files are also obsolete and can be removed :)

**Comment by v-chayan** [comment]
> The regenerate readme files are also obsolete and can be removed :)

I didn't find a copy of RegenerateReadmeTable.cs in Arcade repo. So I didn't remove that file according to the instruction from https://github.com/dotnet/runtime/issues/34907
I am trying to build again after removed this file to ensure it was really not needed. Will update later.

**Comment by ViktorHofer** [comment]
> I didn't find a copy of RegenerateReadmeTable.cs in Arcade repo.

Right, because we are now following a different approach where we are dynamically generating/updating aka.ms links so there's no need for the regeneration of the readme file anymore. We still haven't added the build table back to the README.md though. It should be safe to delete this.

**Comment by dagood** [comment]
> Right, because we are now following a different approach where we are dynamically generating/updating aka.ms links so there's no need for the regeneration of the readme file anymore. We still haven't added the build table back to the README.md though. It should be safe to delete this.

`RegenerateReadmeTable` is unrelated to aka.ms link generation, it's just a way to help humans manually update the table when the list of platforms or branches changes, through basic templating. Arcade may help generate readme tables at some point, but I don't think we should remove `RegenerateReadmeTable` and wait for that. https://github.com/dotnet/runtime/issues/32055 is delayed enough as it is.

**Comment by dagood** [comment]
> > The regenerate readme files are also obsolete and can be removed :)
> 
> I didn't find a copy of RegenerateReadmeTable.cs in Arcade repo. So I didn't remove that file according to the instruction from #34907
> I am trying to build again after removed this file to ensure it was really not needed. Will update later.

I recommend not doing this--at the very least, not as part of this PR. The task isn't exercised as part of the builds, and this is intentional. It also looks like the normal entrypoint disappeared in https://github.com/dotnet/runtime/commit/42183b1b86656a348e0b6af7fa7c75072865f759#diff-f1921dfe4ae191cbfc80c608aa17dd4a.

**Comment by dagood** [comment]
> Right, because we are now following a different approach where we are dynamically generating/updating aka.ms links so there's no need for the regeneration of the readme file anymore. 

I see, it sounds like you're under the impression that the readme was updated for every official build? This actually hasn't changed with aka.ms link generation: the links were always being dynamically updated and the table text was always static. There's nothing new here with aka.ms links.

**Review by dagood — CHANGES_REQUESTED** [review]
Per https://github.com/dotnet/runtime/pull/35405#issuecomment-619044813

**Comment by ViktorHofer** [comment]
> I see, it sounds like you're under the impression that the readme was updated for every official build?

Right, I thought that was the case and the regenerate-readme-table.proj was used to update it and flow it back into the public repo somehow. Sounds like the proj simply avoids the hand-editing of the build table.

**Comment by v-chayan** [comment]
> > > The regenerate readme files are also obsolete and can be removed :)
> > 
> > 
> > I didn't find a copy of RegenerateReadmeTable.cs in Arcade repo. So I didn't remove that file according to the instruction from #34907
> > I am trying to build again after removed this file to ensure it was really not needed. Will update later.
> 
> I recommend not doing this--at the very least, not as part of this PR. The task isn't exercised as part of the builds, and this is intentional. It also looks like the normal entrypoint disappeared in [42183b1#diff-f1921dfe4ae191cbfc80c608aa17dd4a](https://github.com/dotnet/runtime/commit/42183b1b86656a348e0b6af7fa7c75072865f759#diff-f1921dfe4ae191cbfc80c608aa17dd4a).

I've reverted the change. Thanks for pointing this out!

**Review by dagood — APPROVED** [review]

**Review by NikolaMilosavljevic — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
What about GetTargetMachineInfo?

**Comment by v-chayan** [comment]
> What about GetTargetMachineInfo?

This file is still used. Removing it will cause below build error:
F:\GitHub\runtime\tools-local\tasks\installer.tasks\installer.tasks.csproj(52,5): error MSB4062: The "GetTargetMachineInfo" task could not be loaded from the assembly F:\GitHub\runtime\artifacts\bin\installer.tasks\Debug\netstandard2.0\installer.tasks.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by ViktorHofer** [comment]
Ok, I'll deal with it in https://github.com/dotnet/runtime/pull/35538.

**Pull request merged**
