### PR TITLE
Mark tasks projects as non-source projects

### LINKED ISSUE #84157: BinClashes for Microsoft.Interop.SourceGeneration.dll
### Description

I opened a binlog and noticed this:
image

That indicates the build is building both debug and release copies of Microsoft.Interop.SourceGeneration.dll.  We end up shipping whichever one builds last.

### Reproduction Steps

Build the product and examine binlog.

### Expected behavior

No binclashes

### Actual behavior

Binclashes for Microsoft.Interop.SourceGeneration.dll

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elinor-fung**
This will avoid having source generators like `LibraryImportGenerator` enabled for the tasks projects.

Fixes https://github.com/dotnet/runtime/issues/84157

@dotnet/runtime-infrastructure the underlying issue here is that the tasks always build as `Debug` (https://github.com/dotnet/runtime/issues/84157#issuecomment-1500456760) instead of respecting the `Configuration` property. I assume this to avoid issues with locking/node reuse based on this comment? https://github.com/dotnet/runtime/blob/0760f7702e0ae682c521623925ff0a8b49b9a430/src/tasks/tasks.proj#L13-L16

That does cause conflicts with any projects for shipping assemblies those tasks reference though. For `LibraryImportGenerator` specifically, we can just avoid the unnecessary reference. However, I think it remains an issue for other references like `Microsoft.NET.WebAssembly.Webcil`.

Should the tasks always be `Release` instead? At least then there wouldn't be the danger of accidentally shipping debug bits.

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by elinor-fung** [comment]
Ah, this doesn't actually address the `LibraryImportGenerator` double write. As mentioned in the description, `Microsoft.NET.WebAssembly.Webcil` also has a double write issue as it is referenced by one of the tasks that are always building in Debug. That is a source project, so still has the generator enabled, so we are building the generator in Debug too.

Suggestions on what we should do here? Is there a reason the tasks are always built in Debug? Can we switch them to Release (would have double writes in debug, but without the potential of clobbering shipping release bits with debug ones)?

**Comment by jkoritzinsky** [comment]
I think we build them in Debug today as it makes it easier to construct the paths to the task assemblies (since they're always consistent) and it makes it easier to debug (as Debug is much easier to debug than Release).

**Comment by elinor-fung** [comment]
How about switching the default to Release for CI and official builds, but leaving it Debug on local builds? I feel like it would generally make sense for CI builds to use the presumably faster Release versions and I don't think computing the paths using a property vs a hard-coded 'Debug' makes it any harder.

**Comment by jkoritzinsky** [comment]
If we can do it easily, I'm okay with switching it to Release sometimes.

**Review by jkoritzinsky — APPROVED** [review]

**Comment by lewing** [comment]
this seems to have broken wasm/mobile builds

**Comment by lewing** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=235249&view=logs&j=e847dbc9-1eac-5acf-c55e-fa567d2d051e&t=99c1b762-4320-56b6-4032-5660a24658c1&l=509

**Comment by lewing** [comment]
@elinor-fung can you fix the regression quickly or should we revert?

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/blob/563408ab1bf514d562b9dfea1d2a4c97eae27366/src/mono/wasm/build/WasmApp.LocalBuild.props#L35

**Comment by lewing** [comment]
and https://github.com/search?q=repo%3Adotnet%2Fruntime+MonoTargetsTasksDir&type=code

**Comment by steveisok** [comment]
For mobile, it looks to be exclusive to the android runtime tests.

**Comment by elinor-fung** [comment]
https://github.com/dotnet/runtime/pull/84666 should propagate the tasks config to the test builds, which looked like the immediate problem based on the binlogs. It's doesn't touch *LocalBuild.props though. If that isn't sufficient, we can revert.

**Pull request merged**
