### PR TITLE
[QUIC] Move ByteMixingOrNativeAVE_MinimalFailingTest to OuterLoop

### LINKED ISSUE #55588: system.net.quic.tests.msquictests.bytemixingornativeave_minimalfailingtest times out on Fedora
Runfo Tracking Issue: [system.net.quic.tests.msquictests.bytemixingornativeave_minimalfailingtest times out on Fedora](https://runfo.azurewebsites.net/tracking/issue/147)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1234989](https://dev.azure.com/dnceng/public/_build/results?buildId=1234989)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55430](https://github.com/dotnet/runtime/pull/55430)|net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55430-merge-b7c85f1087e04b5eba/System.Net.Quic.Functional.Tests/console.467175fe.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T16%25253A43%25253A49Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DaOw1rG5XqVc47%25252F9t9IZU%25252BI60Sa4%25252FVa8CQPIn%25252FD9hXzw%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55430-merge-b7c85f1087e04b5eba/System.Net.Quic.Functional.Tests/308cd24d-8dc2-4da5-81d7-a2a5be380774.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T16%25253A43%25253A49Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DaOw1rG5XqVc47%25252F9t9IZU%25252BI60Sa4%25252FVa8CQPIn%25252FD9hXzw%25253D)|
|[1234975](https://dev.azure.com/dnceng/public/_build/results?buildId=1234975)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55530](https://github.com/dotnet/runtime/pull/55530)|net6.0-Linux-Debug-x64-Mono_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55530-merge-df545c3b94ab40cb9a/System.Net.Quic.Functional.Tests/console.44e77fc1.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T16%25253A22%25253A31Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Duj4gJaw5N1cHdFWklkxY9CXD9i3m7S1c%25252BuShUgPuWUM%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55530-merge-df545c3b94ab40cb9a/System.Net.Quic.Functional.Tests/535134b4-f94c-4da3-ad50-b815ec48ba6c.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T16%25253A22%25253A31Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Duj4gJaw5N1cHdFWklkxY9CXD9i3m7S1c%25252BuShUgPuWUM%25253D)|
|[1234899](https://dev.azure.com/dnceng/public/_build/results?buildId=1234899)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55373](https://github.com/dotnet/runtime/pull/55373)|net6.0-Linux-Debug-x64-Mono_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55373-merge-1f4d56abfe274bf69c/System.Net.Quic.Functional.Tests/console.d7307022.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T15%25253A16%25253A47Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dr2gzF%25252F29dNqq4Xzi1muSwB2YBEbJEBKvkIROwvkFIZE%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55373-merge-1f4d56abfe274bf69c/System.Net.Quic.Functional.Tests/2260914e-c9bd-4a70-a9fa-39f536aac856.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T15%25253A16%25253A47Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dr2gzF%25252F29dNqq4Xzi1muSwB2YBEbJEBKvkIROwvkFIZE%25253D)|
|[1234506](https://dev.azure.com/dnceng/public/_build/results?buildId=1234506)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 54991](https://github.com/dotnet/runtime/pull/54991)|net6.0-Linux-Debug-x64-Mono_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54991-merge-50da02bd17174c9aa9/System.Net.Quic.Functional.Tests/console.7c129d98.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T11%25253A09%25253A44Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DUxLGcQZivDWb3oFaTiimJvRHMM4IsoF7p6MyPFoJzRw%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54991-merge-50da02bd17174c9aa9/System.Net.Quic.Functional.Tests/a7b4834f-06e0-4022-a2b7-e96e79aabfe8.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T11%25253A09%25253A44Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DUxLGcQZivDWb3oFaTiimJvRHMM4IsoF7p6MyPFoJzRw%25253D)|
|[1234437](https://dev.azure.com/dnceng/public/_build/results?buildId=1234437)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-Mono_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-04a1a3b4d137496097/System.Net.Quic.Functional.Tests/console.da44072d.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T09%25253A31%25253A13Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DlnUmiODgiv4I35b7HruDkl%25252Fkl66SbnWWCbbWfcjTGOk%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-04a1a3b4d137496097/System.Net.Quic.Functional.Tests/bf39f3d8-9874-4e00-ae58-98137be06249.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T09%25253A31%25253A13Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DlnUmiODgiv4I35b7HruDkl%25252Fkl66SbnWWCbbWfcjTGOk%25253D)|
|[1234232](https://dev.azure.com/dnceng/public/_build/results?buildId=1234232)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55493](https://github.com/dotnet/runtime/pull/55493)|net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55493-merge-1de596dd3aca430390/System.Net.Quic.Functional.Tests/console.483e4520.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T05%25253A09%25253A56Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D338RWEtldbJ1SjqzTYDpqNim%25252BJZxB3hPmBQcNzqfgL4%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55493-merge-1de596dd3aca430390/System.Net.Quic.Functional.Tests/3755bfc9-9ed5-46f4-a788-ebc8124f1251.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T05%25253A09%25253A56Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D338RWEtldbJ1SjqzTYDpqNim%25252BJZxB3hPmBQcNzqfgL4%25253D)|
|[1234062](https://dev.azure.com/dnceng/public/_build/results?buildId=1234062)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55548](https://github.com/dotnet/runtime/pull/55548)|net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55548-merge-4c71a8caaff04314b4/System.Net.Quic.Functional.Tests/console.ab797da7.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T02%25253A39%25253A03Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D5pSiD%25252BAxXdEUB%25252F%25252FnlVJyqKSpljIt1yhQ1JhFdZXixKs%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55548-merge-4c71a8caaff04314b4/System.Net.Quic.Functional.Tests/97242d2f-3ee2-4aef-9e07-afb98bfef7a2.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T02%25253A39%25253A03Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D5pSiD%25252BAxXdEUB%25252F%25252FnlVJyqKSpljIt1yhQ1JhFdZXixKs%25253D)|
|[1234024](https://dev.azure.com/dnceng/public/_build/results?buildId=1234024)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55458](https://github.com/dotnet/runtime/pull/55458)|net6.0-Linux-Debug-x64-Mono_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55458-merge-2d474087fc68431f86/System.Net.Quic.Functional.Tests/console.e93fb709.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T15%25253A34%25253A26Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D29F17mxHWitbQqNE%25252Byofe9OWaJj94QmjrDUVWyDKM34%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55458-merge-2d474087fc68431f86/System.Net.Quic.Functional.Tests/00963c40-9f84-4daf-891f-31a761629e8e.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T15%25253A34%25253A26Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D29F17mxHWitbQqNE%25252Byofe9OWaJj94QmjrDUVWyDKM34%25253D)|
|[1233864](https://dev.azure.com/dnceng/public/_build/results?buildId=1233864)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55513](https://github.com/dotnet/runtime/pull/55513)|net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55513-merge-2316525bf22d47c8b7/System.Net.Quic.Functional.Tests/console.67a6fb2e.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T11%25253A24%25253A47Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DdDfAtkn3Dqbx%25252FOZdTSXX8u8HWHxUkVRTECaJgrPID5k%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55513-merge-2316525bf22d47c8b7/System.Net.Quic.Functional.Tests/4976d654-d33b-431e-94e9-f2e3b9ca7a12.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T11%25253A24%25253A47Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DdDfAtkn3Dqbx%25252FOZdTSXX8u8HWHxUkVRTECaJgrPID5k%25253D)|
|[1233610](https://dev.azure.com/dnceng/public/_build/results?buildId=1233610)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55533](https://github.com/dotnet/runtime/pull/55533)|net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55533-merge-17d76f1db986492984/System.Net.Quic.Functional.Tests/console.7135ff0b.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T22%25253A56%25253A41Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D8oSQ9s4wCaGkhi4VFj166GCaRs4r9ys9V2xrraFaj%25252Fw%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55533-merge-17d76f1db986492984/System.Net.Quic.Functional.Tests/ad7b383b-6e46-4711-a9ef-c1ec1cbca627.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T22%25253A56%25253A41Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D8oSQ9s4wCaGkhi4VFj166GCaRs4r9ys9V2xrraFaj%25252Fw%25253D)|
|[1233374](https://dev.azure.com/dnceng/public/_build/results?buildId=1233374)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55507](https://github.com/dotnet/runtime/pull/55507)|net6.0-Linux-Debug-x64-Mono_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55507-merge-1b317b8661d94ac79c/System.Net.Quic.Functional.Tests/console.6a35c0de.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T00%25253A09%25253A01Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DUsmwFM5ZDfKHfxiuwk%25252FUZQKYnNf78sNkCJjBcJIeYj8%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55507-merge-1b317b8661d94ac79c/System.Net.Quic.Functional.Tests/e33ea4f0-3051-4fbc-b3eb-011849796faa.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T00%25253A09%25253A01Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DUsmwFM5ZDfKHfxiuwk%25252FUZQKYnNf78sNkCJjBcJIeYj8%25253D)|
|[1233374](https://dev.azure.com/dnceng/public/_build/results?buildId=1233374)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55507](https://github.com/dotnet/runtime/pull/55507)|net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55507-merge-e82fc51c855d49dc95/System.Net.Quic.Functional.Tests/console.cf2c98c5.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T00%25253A10%25253A00Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DmZogaa0f2sQwuAWGIUMmyY7jmWd%25252BXtdsd3%25252BPc4hZ2no%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55507-merge-e82fc51c855d49dc95/System.Net.Quic.Functional.Tests/b21669dd-dde5-42e0-825d-0715728a25e6.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T00%25253A10%25253A00Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DmZogaa0f2sQwuAWGIUMmyY7jmWd%25252BXtdsd3%25252BPc4hZ2no%25253D)|
|[1233250](https://dev.azure.com/dnceng/public/_build/results?buildId=1233250)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55530](https://github.com/dotnet/runtime/pull/55530)|net6.0-Linux-Debug-x64-Mono_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55530-merge-36eacd3f1670418aa1/System.Net.Quic.Functional.Tests/console.8ce0064d.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T20%25253A15%25253A08Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Djl1Ziqffk6ymNoVfHMCbNd%25252FywBM1L9OV3DkufTyV2pE%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55530-merge-36eacd3f1670418aa1/System.Net.Quic.Functional.Tests/e7d122d8-4f1e-4e62-a642-d10d757f73f4.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T20%25253A15%25253A08Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Djl1Ziqffk6ymNoVfHMCbNd%25252FywBM1L9OV3DkufTyV2pE%25253D)|
|[1233170](https://dev.azure.com/dnceng/public/_build/results?buildId=1233170)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55369](https://github.com/dotnet/runtime/pull/55369)|net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55369-merge-40827716223c4cdc80/System.Net.Quic.Functional.Tests/console.ecc51568.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T19%25253A29%25253A18Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dy%25252FQKDEXhRpV%25252FaJWzXrwem6SdOAIUFDdEzejQ1IZGtpk%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55369-merge-40827716223c4cdc80/System.Net.Quic.Functional.Tests/4da80606-5931-4533-a8a0-069856937c90.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T19%25253A29%25253A18Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dy%25252FQKDEXhRpV%25252FaJWzXrwem6SdOAIUFDdEzejQ1IZGtpk%25253D)|
|[1232861](https://dev.azure.com/dnceng/public/_build/results?buildId=1232861)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8899a62e6f614ea1b3/System.Net.Quic.Functional.Tests/console.d6482988.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T16%25253A44%25253A18Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DMVc106OR9ELNjM4Y3Vq93U4lMQzyII0ikOA86WYj08Y%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8899a62e6f614ea1b3/System.Net.Quic.Functional.Tests/ad272a7a-737b-4704-a496-b2a7e042479f.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T16%25253A44%25253A18Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DMVc106OR9ELNjM4Y3Vq93U4lMQzyII0ikOA86WYj08Y%25253D)|
|[1232822](https://dev.azure.com/dnceng/public/_build/results?buildId=1232822)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55338](https://github.com/dotnet/runtime/pull/55338)|net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55338-merge-a0c1262d76f24f9785/System.Net.Quic.Functional.Tests/console.c57e0b0f.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T16%25253A33%25253A53Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DvU0T059%25252FCQf%25252BbUc2ONAWyze%25252BX%25252BRlFq%25252B%25252FxoI%25252Fz%25252FHIHj4%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55338-merge-a0c1262d76f24f9785/System.Net.Quic.Functional.Tests/f5323bbe-65e0-4987-8bf7-fa5e1a25e97e.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T16%25253A33%25253A53Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DvU0T059%25252FCQf%25252BbUc2ONAWyze%25252BX%25252BRlFq%25252B%25252FxoI%25252Fz%25252FHIHj4%25253D)|
|[1232722](https://dev.azure.com/dnceng/public/_build/results?buildId=1232722)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55478](https://github.com/dotnet/runtime/pull/55478)|net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55478-merge-c452f8ceb23c424997/System.Net.Quic.Functional.Tests/console.01ed3eed.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T17%25253A14%25253A37Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DJsDvwkapsQSr66vR8iFI%25252BjewYtrmdljqqTjMKulptr4%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55478-merge-c452f8ceb23c424997/System.Net.Quic.Functional.Tests/33431a91-27e9-42b0-85ab-bac42f39eb22.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T17%25253A14%25253A37Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DJsDvwkapsQSr66vR8iFI%25252BjewYtrmdljqqTjMKulptr4%25253D)|
|[1232256](https://dev.azure.com/dnceng/public/_build/results?buildId=1232256)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55108](https://github.com/dotnet/runtime/pull/55108)|net6.0-Linux-Debug-x64-Mono_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55108-merge-35c2b45726d140ff86/System.Net.Quic.Functional.Tests/console.b05945d6.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T08%25253A20%25253A54Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DgqaAuTCihFj8dujwWHwW9gJkYBAWFDvf%25252BlE7VCcTtXc%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55108-merge-35c2b45726d140ff86/System.Net.Quic.Functional.Tests/93b039a0-5dd3-46e0-bf2e-b6e8d113051e.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T08%25253A20%25253A54Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DgqaAuTCihFj8dujwWHwW9gJkYBAWFDvf%25252BlE7VCcTtXc%25253D)|
|[1232206](https://dev.azure.com/dnceng/public/_build/results?buildId=1232206)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55493](https://github.com/dotnet/runtime/pull/55493)|net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55493-merge-3d1163701df74ae597/System.Net.Quic.Functional.Tests/console.60a5da73.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T06%25253A04%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DZ4iLY53qllnBH%25252FNjvjLBkZMmwR8kp502qbL6rw69dGQ%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55493-merge-3d1163701df74ae597/System.Net.Quic.Functional.Tests/dc65605a-9b8b-4592-bb22-1f54ae3d0eb7.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T06%25253A04%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DZ4iLY53qllnBH%25252FNjvjLBkZMmwR8kp502qbL6rw69dGQ%25253D)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|12|18|18|

### PR DESCRIPTION
**Pull request by CarnaViire**
~~Disable ByteMixingOrNativeAVE_MinimalFailingTest test by ActiveIssue #55588~~
Move ByteMixingOrNativeAVE_MinimalFailingTest to outerloop. Fixes #55588

### CODE REVIEW

**Comment by wfurt** [comment]
can we just move just to outer loop? That may be good enough as it won't block others.

**Comment by CarnaViire** [comment]
> can we just move just to outer loop? That may be good enough as it won't block others.
Yep, I was not sure what will be better, so did both 😂

**Comment by wfurt** [comment]
Let's try it. Outerloop would still probably catch crashes.

**Review by wfurt — APPROVED** [review]
LGTM

**Review by stephentoub — APPROVED** [review]

**Comment by geoffkizer** [comment]
We shouldn't *just* move this to Outerloop, because it's just going to keep timing out there.

This tests takes a long time to run by design. We should either reduce the time it takes (e.g. reduce iterations from 20 to ??), or increase the timeout.

**Comment by wfurt** [comment]
How much time you think we need @geoffkizer ?

**Comment by geoffkizer** [comment]
Am I reading the code correctly, that the current timeout is _**16 minutes**_? (1000 seconds?)

How is it possible that a test that runs in 10s on my dev box takes more than 16 minutes on a CI machine?

**Comment by wfurt** [comment]
I think that is overall timeout for all the test. Each test may fail faster. So as each operation within the test can fail sooner.

**Comment by CarnaViire** [comment]
`RunClientServer` actually has a default timeout of 10s
https://github.com/dotnet/runtime/blob/430d87f67d29bb2001ce9b53509488db754deab4/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs#L114
so 1000s outside does not make sense in the end :(

**Comment by CarnaViire** [comment]
Shall we pass 50s as an iteration timeout then?

**Comment by CarnaViire** [comment]
Or, merge it as it is to unblock CI and discuss timeouts or other ways to fix it later

**Comment by karelz** [comment]
This is blocking everyone, we need to disable it or move to Outerloop ASAP. @CarnaViire can you please merge your PR? We can discuss proper solution later. Thanks!

**Comment by ManickaP** [comment]
@geoffkizer 

> How is it possible that a test that runs in 10s on my dev box takes more than 16 minutes on a CI machine?

From my experience, if it gets stuck for 16 minutes on a CI machine and eventually killed by CI infra, it's a deadlock (in tests mostly, rarely in production code). The CI is slow enough, or has a different timing, so that different races happen and we end up with something like this.
After all, we're using semaphores, manualresetevents, taskcompletionsources etc. to synchronize work between client and server. And there's plenty of room to not to see all the possible execution paths and getting a hang/deadlock.

Some of these problem I've successfully debugged in the past by crashing the process on purpose after a certain amount of time and then getting a dump from which you can (in ~90% of times) figure out where it got stuck.

**Comment by CarnaViire** [comment]
> if it gets stuck for 16 minutes

It didn't stuck for 16 mins, it timeouted from one iteration timeout inside RunClientServer, which is 10s by default
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8899a62e6f614ea1b3/System.Net.Quic.Functional.Tests/console.d6482988.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T16%25253A44%25253A18Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DMVc106OR9ELNjM4Y3Vq93U4lMQzyII0ikOA86WYj08Y%25253D
you can see it in the logs, and the full test suite took 31s

**Comment by CarnaViire** [comment]
That being said, we still need to investigate why 10s was not enough, it is possible CI machine is just slow and this test is big, so we just need to increase the timeout for the iteration, but some deadlock is also possible

**Pull request merged**
