### PR TITLE
Specify and test that `0x` is case-invariant in the Convert class

### PR DESCRIPTION
**Pull request by Dubzer**
Hi!
I was confused by the comment, so decided to specify that method can accept `0x` and `0X` as a prefix for hex numbers

### CODE REVIEW

**Comment by Dubzer** [comment]
@dotnet-policy-service agree

**Comment by danmoseley** [comment]
Are there tests for all these already

**Review by tannergooding — APPROVED** [review]

**Comment by tannergooding** [comment]
This is already covered in the official docs under the remarks section: https://learn.microsoft.com/en-us/dotnet/api/system.convert.tobyte?view=net-8.0#system-convert-tobyte(system-string-system-int32)

> Are there tests for all these already

Looks like no, @Dubzer would you mind adding explicit coverage to the various `Convert.To*.cs` files, specifically under the `FromStringWithBase` tests in https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime/tests/System.Runtime.Extensions.Tests/System ?

**Comment by Dubzer** [comment]
@tannergooding sure! I'll add it to my PR when I have time

**Comment by Dubzer** [comment]
@tannergooding done! I've added tests and also fixed small comment typo for the ToString method

**Review by tannergooding — APPROVED** [review]

**Pull request merged**
