### PR TITLE
disable sending NT Authority in TLS handshake if specific trust was specified

### LINKED ISSUE #60949: SslStream: Don't include "NT AUTHORITY" in Distinguished Names list of CertificateRequest.
During client certificate authentication, it is necessary to configure trusted certificate authorities (CA) list in certain scenarios. This trusted CA list is configured in the _Distinguished Names_ of the _Certificate Request_ message of the TLS handshake.

In NET 6.0, the ability to configure _Distinguished Names_ list was added to SslStream via https://github.com/dotnet/runtime/issues/45456. The trusted CA list is set using any machine store on the server as shown [here](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.sslcertificatetrust.createforx509store?view=net-6.0#System_Net_Security_SslCertificateTrust_CreateForX509Store_System_Security_Cryptography_X509Certificates_X509Store_System_Boolean_). 

However, for servers using SslStream, in addition to the CA list from the configured store, there is an additional "NT AUTHORITY" string in the _Distinguished Names_ during the TLS handshake. This is unexpected and breaks clients, especially in scenarios where the intention is to send an empty _Distinguished Names_ list in the TLS handshake.

Below trace shows the **expected** behavior when the intention is to send an empty CA list in the _Distinguished Names_. (This trace was collected on http.sys (not SslStream)

The below snippet shows **frame 55** from the attached wireshark capture. There are zero entries in the _Distinguished Names_ because the CA list was configured with an empty store.

emptyCTL_expected

Below snippet shows the EmptyCTL store on the server that was used to configure the CA list.

EmptyCTL

On SslStream, below trace shows the **unexpected** behavior when the _Distinguished Names_ is configured with an empty list. As shown below, the _Distinguished Names_ list is not empty, it contains the string "NT AUTHORITY"

EmptyCTL3

This breaks the scenario and client does not send any certificate in the _Certificate_ message of the TLS handshake as shown below.

EmptyCTL5

The expectation is to be able to configure the CA lists from the contents of the stores _only_ and not have any additional strings (such as "NT AUTHORITY") in the _Distinguished Names_ during TLS handshake.

Wireshark logs: [serverhello.zip](https://github.com/dotnet/runtime/files/7430132/serverhello.zip)

### PR DESCRIPTION
**Pull request by wfurt**
When Windows sends trusted CA list in handshake it by default includes `NT Authority` as special case. 
I'm not sure if anybody depends on it but it seems to break some use cases with new API from  #45456.
Particularly attempt to send empty trust list seems to break .NET clients when only `NT Authority` is present.
That may be issue with the client selection but we don't have control over all of them.

To deal with it, I added explicit `SCH_CRED_NO_SYSTEM_MAPPER` flag to suppress that channel behavior when `SslCertificateTrust` is provided and `sendTrustInHandshake` is set to `true`. (SslStreamPal.Windows.cs)
Alternatively, we could set it always but I'm concern about backward compatibility. (`SslCertificateTrust` was introduced in 6.0 so changing it there should be ok)

Since this is done on credential handle, we need to also update the caching logic to not mingle that case with others. 

We don't have any automated tests since this still depends on Windows registry setting. I did manual tests and verified that the `NT Authority` is not in the CA list as well as pointing to empty certificate store sends empty list.

fixes #60949

### CODE REVIEW

**Review by scalablecory — APPROVED** [review]
Give in to the null conditional operator, @wfurt! :)

LGTM either way.

**Comment by stephentoub** [comment]
Small preference for the null conditional, but either way is ok.

**Comment by geoffkizer** [comment]
> The problem with the null conditional operator is that pesky literal `== true' at the end to force the type to bool. The brevity is better but the clarity is poor imo.

I agree with this. I always find it weird to see "== true" because normally it's unnecessary. It makes me have to stop and think about what's going on.

An alternative that still uses the null conditional operator, but doesn't use "== true", is:

```csharp
    bool sendTrustedList = _sslAuthenticationOptions.CertificateContext!.Trust?._sendTrustInHandshake ?? false;
```

I prefer this slightly, since the use of "?? false" instead of "== true" makes it obvious that you're handling the null case.

Also, for the reverse case where you want to treat null as true, "?? true" seems much clearer to me than "!= false", which makes my head hurt even more than "== true". That doesn't apply here though.

**Comment by wfurt** [comment]
> An alternative that still uses the null conditional operator, but doesn't use "== true", is:

I was thinking about it more and I like this best @geoffkizer. It is basically use "this" or "default".

**Pull request merged**
