### PR TITLE
Put back FindCaseSensitivePrefix regex alternation support

### PR DESCRIPTION
**Pull request by stephentoub**
https://github.com/dotnet/runtime/pull/63976#issuecomment-1019716016

### CODE REVIEW

**Review by joperezr — APPROVED** [review]
Sorry for missing the cases in the perf repo. Thanks for putting this back.

**Comment by joperezr** [comment]
Are we able to run a sample perf run to ensure this specific case's regression is fixed(since technically this is not the exact same code we used to have as we always return false now)? Or is that not possible until the change is merged?

**Comment by stephentoub** [comment]
> Sorry for missing the cases in the perf repo

For future reference, the majority of cases I saw are actually here:
https://raw.githubusercontent.com/dotnet/runtime-assets/main/src/System.Text.RegularExpressions.TestData/Regex_RealWorldPatterns.json

**Comment by stephentoub** [comment]
> Are we able to run a sample perf run to ensure this specific case's regression is fixed(since technically this is not the exact same code we used to have as we always return false now)? Or is that not possible until the change is merged?

Yes:

| Method |         Toolchain |                              Pattern |         Options |      Mean | Ratio |
|------- |------------------ |------------------------------------- |---------------- |----------:|------:|
|  Count | \main\corerun.exe | (?m)^Sherlock(...)rlock Holmes$ [37] |            None | 111.66 us |  1.00 |
|  Count |   \pr\corerun.exe | (?m)^Sherlock(...)rlock Holmes$ [37] |            None |  53.99 us |  0.49 |
|        |                   |                                      |                 |           |       |
|  Count | \main\corerun.exe | (?m)^Sherlock(...)rlock Holmes$ [37] |        Compiled |  54.32 us |  1.00 |
|  Count |   \pr\corerun.exe | (?m)^Sherlock(...)rlock Holmes$ [37] |        Compiled |  44.04 us |  0.81 |
|        |                   |                                      |                 |           |       |
|  Count | \main\corerun.exe | (?m)^Sherlock(...)rlock Holmes$ [37] | NonBacktracking |  82.29 us |  1.00 |
|  Count |   \pr\corerun.exe | (?m)^Sherlock(...)rlock Holmes$ [37] | NonBacktracking |  62.57 us |  0.76 |

**Pull request merged**
