### PR TITLE
Change OnRemovePerEntryCleanupAction to delete[] its underlying bytes

### LINKED ISSUE #73789: asan reports mismatched new[] vs delete
### Description

static member function OnRemovePerEntryCleanupAction in src/coreclr/vm/crossloaderallocatorhash.h deletes storage  that was previously allocated with new BYTE[...].  This causes address sanitizer (asan) to complain at runtime that there are mismatches of the new/delete new[]/delete[] protocol.

### Reproduction Steps

compile and run with clang14 -fsanitize=address

### Expected behavior

no runtime error for mismatched new[]/delete

### Actual behavior

asan runtime error

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by RobertHenry6bev**
Change OnRemovePerEntryCleanupAction to explicitly fire the destructor
and then free up the underlying bytes using delete[], so that the delete[] matches the new BYTE[] used to allocate the underlying storage.

Fixes https://github.com/dotnet/runtime/issues/73789

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
I have an alternative fix for this that is a little cleaner imho. I'll put up a fix in a minute.

**Comment by jkoritzinsky** [comment]
Alternative that better matches how we've solved alloc/dealloc mismatches in CoreCLR so far: https://github.com/dotnet/runtime/pull/73820

**Comment by danmoseley** [comment]
@RobertHenry6bev does this PR still apply given the linked PR was merged?

**Comment by mangod9** [comment]
@RobertHenry6bev closing this PR based on the other change.

**Pull request closed without merging**
