### PR TITLE
[release/8.0-preview4] Bump package version for .net 7 to 7.0.6

### PR DESCRIPTION
**Pull request by steveisok**

### CODE REVIEW

**Comment by steveisok** [comment]
@carlossanlop this is a tell mode change.

**Review by lewing — APPROVED** [review]

**Review by carlossanlop — APPROVED** [review]
Approved.

@steveisok should I update my snap checklist to ensure we do this change before snapping? Would that avoid problems in main, or is this change not needed in that branch?

**Comment by steveisok** [comment]
> @steveisok should I update my snap checklist to ensure we do this change before snapping? Would that avoid problems in main, or is this change not needed in that branch?

This should happen when we snap a preview branch to make sure the down level version is lined up. We can't do that in main because we want to run tests and can't if it's set to a version that hasn't been released.

**Comment by carlossanlop** [comment]
@steveisok is this ready to merge? CI looks good?

**Comment by steveisok** [comment]
@carlossanlop it should be good to go once the latest CI run completes.

**Pull request merged**
