### PR TITLE
Backport #51237 to release/6.0-preview4

### PR DESCRIPTION
**Pull request by agocke**
## Description 
This fixes the last trimming warning in HelloWorld. The last remaining trim warningis from EventSource – it’s warning about reflection on implementors. The first fix is just a backport of #51237 to add the appropriate annotation to preserve members on types inheriting from EventSource. The fix also requires the linker to understand how to keep types through inheritance, which we implemented shortly before the snap. A bug was found and fixed (https://github.com/mono/linker/pull/1972) in that feature just after the snap. That fix is the sole change in the new version of the linker included here.

 
## Customer Impact
There is an unactionable EventSource warning produced by almost all trimming on .NET 6.
 
## Regression?
- [ ] Yes
- [X] No
 
## Risk
- [ ] High
- [ ] Medium
- [X] Low

The change in runtime is just attributes. The change in the linker fixes a bug that would still exist without the fix.

## Verification
- [] Manual
- [X] Automated
 
## Packaging changes reviewed?
- [ ] Yes
- [] No
- [X ] N/A

### CODE REVIEW

**Comment by agocke** [comment]
Approved by Tactics over email.

**Review by vitek-karas — APPROVED** [review]

**Comment by eerhardt** [comment]
> The fix also requires the linker to understand how to keep types through inheritance, which we implemented shortly before the snap. A bug was found and fixed (mono/linker#1972) in that feature just after the snap. That fix is the sole change in the new version of the linker included here.

Will this version of the linker also get backported into the preview4 SDK?

**Review by eerhardt — APPROVED** [review]

**Comment by sbomer** [comment]
Looks like the preview4 SDK already has a later version (they snapped a couple days later than runtime) https://github.com/dotnet/sdk/blob/c95bbcc2cb86abe93d83782c9812c87655e1c4d2/eng/Versions.props#L77

**Comment by agocke** [comment]
Ah, well, even better.

**Comment by agocke** [comment]
I'll revert the props change

**Comment by eerhardt** [comment]
> actually it's probably right to keep this in here, just in case we hit the crash in the runtime repo itself.

I would expect it is needed because CI was failing for @LakshanF without the linker bug fix. So I think what you have now is correct.

**Pull request merged**
