### PR TITLE
Fix some low-hanging HWIntrinsic issues

### PR DESCRIPTION
**Pull request by tannergooding**
This fixes a few low-hanging issues:
* It ensures `WithElement` for `Vector64/128/256` isn't claiming to be a System.Numerics type
* It ensures `Vector128.AsVector2` and `Vector128.AsVector3` are intrinsic
* It ensures `Vector2.AsVector128` and `Vector3.Vector128` are intrinsic
* It ensures `AsNInt` and `AsNUInt` for `Vector64/128/256` are intrinsic
* It ensures `get_Count` and `IsSupported` for `Vector64/128/256` and `Vector<T>` are intrinsic

### CODE REVIEW

**Comment by tannergooding** [comment]
For `IsSupported` in particular it allow some significant amount of dead code elimination in the case where the `T` was not supported. In one such method we get the following diff:
```diff
- ; Lcl frame size = 1112
+ ; Lcl frame size = 72
```

In the above code, the actual method body remains the same. We just no longer have a non-trivial amount of locals we couldn't determine were dead:
```asm
G_M3734_IG02:
       mov      ecx, 66
       call     [System.ThrowHelper:ThrowNotSupportedException(int)]
       int3
```

**Comment by tannergooding** [comment]
Likewise for `get_Count` we see some better codegen for the software fallback cases and more loop unrolling occurring. It does cause an expected and slight increase in code size when `T` is supported but really only impacts a subset of the `Vector128/256/512` software fallbacks.

**Comment by tannergooding** [comment]
Really great improvement to size and TP. There are few small size regressions due to additional inlining that occurs in a few places now. The TP and size wins may be a little misrepresented since SPMI tests `Vector<float>` as one of the generic types so this is really impacting all the `Vector128<Vector<float>>` paths that get tested by SPMI.

That being said, such paths do appear in practice almost anywhere we have `Vector###<T>` support. This is because many of those paths are generic and we only take the "accelerated path" when T is supported. This leaves the JIT with the job of doing dead code elimination and these being intrinsic make that much simpler/easier.

On Windows x64
> Overall (-257,636 bytes)
> MinOpts (-916 bytes)
> FullOpts (-256,720 bytes)

and
> Overall (-0.12%)
> FullOpts (-0.16%)

Will post Arm64 numbers once CI finishes.

**Comment by tannergooding** [comment]
CC. @dotnet/jit-contrib. Fixing some low-hanging fruit giving a significant decrease to SPMI generated bytes and improvement to throughput for x64

**Review by TIHan — APPROVED** [review]
The diffs look great! The dead code elimination really helped out.

**Comment by tannergooding** [comment]
Logged https://github.com/dotnet/runtime/issues/80666 to track the jitstress/outerloop failures

**Pull request merged**
