### PR TITLE
Try to get more info about a named mutex creation failure

### PR DESCRIPTION
**Pull request by kouvel**

### CODE REVIEW

**Comment by lewing** [comment]
There isn't any harm in capturing this on main for a few days so feel free to merge it

**Comment by kouvel** [comment]
Ok sure, I'll see if I can get a repro first and see if I need to do more like an strace, if I don't get a repro then I can merge this small change for a few days.

**Review by lewing — APPROVED** [review]
conditionally approved for diagnostics

**Comment by kouvel** [comment]
Darn, containers need special permissions to use strace. Will have to try something else.

**Pull request closed without merging**
