### PR TITLE
Don't throw from RemoteExecutor on SkipTestExceptions

### LINKED ISSUE #63008: EventSource_SuccessfulHandshake_LogsStartStop failures on Windows11
Impacted test: `EventSource_SuccessfulHandshake_LogsStartStop`

We throw a `[SkipTestException]` from an inner call to `SslStream_StreamToStream_Authentication_Success` (#59135):
https://github.com/dotnet/runtime/blob/e8343ee9ce107a419cf201a63d64ce2a58d2d80d/src/libraries/System.Net.Security/tests/FunctionalTests/TelemetryTest.cs#L53

But it looks like it's not being propagated because of `RemoteExecutor`:
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62870-merge-83671b73f8b34d3085/System.Net.Security.Tests/2/console.ae014fcd.log?sv=2019-07-07&se=2022-01-06T22%3A03%3A15Z&sr=c&sp=rl&sig=baGyxGNbdVauzUOgTjrUPFOLeR4fZlOgkWOSBATBEBs%3D

I don't understand why is this failure intermittent.

### PR DESCRIPTION
**Pull request by MihaZupan**
Fixes #63008

Should be reviewed [without looking at whitespace changes](https://github.com/dotnet/runtime/pull/65105/files?diff=split&w=1).

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Review by wfurt — APPROVED** [review]
LGTM.

**Comment by jkoritzinsky** [comment]
Is there any interest in generalized support for communicating a SkipTestException from a RemoteExecutor callback back to the test process? Or is this enough of a one-off scenario that it's not worth the effort?

**Comment by wfurt** [comment]
> Is there any interest in generalized support for communicating a SkipTestException from a RemoteExecutor callback back to

I'm not sure @jkoritzinsky. That would be handy in cases when the skip is determined inside of the code that runs inside of the remote. It seems like in most cases we can determine this upfront. In this case, this is caused by this test calling another test that now has SkipTest and this dependency was not obvious.

**Comment by jkoritzinsky** [comment]
@wfurt In that case, I think this is an obtuse-enough scenario that we don't need to add support to RemoteExecutor directly.

**Pull request merged**
