### PR TITLE
JIT: Avoid duplicate hash table lookups in VN

### PR DESCRIPTION
**Pull request by jakobbotsch**
We can switch to recently added `LookupPointerOrAdd` to avoid duplicate hash table lookups for the `VNForFunc` family of functions.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @EgorBo 

[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=740580&view=ms.vss-build-web.run-extensions-tab). Some (small-ish) TP improvements. Some TP regressions on Linux that I posted detailed stats of above.

**Review by EgorBo — APPROVED** [review]
I am wondering - is it possible to post "Detailed tp diff" on CI? could be on-demand

**Comment by jakobbotsch** [comment]
> I am wondering - is it possible to post "Detailed tp diff" on CI? could be on-demand

Sure, it would be nice to have something like that. Ideally we would add support for parallelism and automatically filtering out TP from misses if we were to add it into CI.

**Pull request merged**
