### PR TITLE
Tiny improvement of `StringBuilder.Append(StringBuilder)`

### PR DESCRIPTION
**Pull request by skyoxZ**
it is guaranteed that  `m_ChunkLength == 0` and `m_ChunkChars.Length >= count` after `ExpandByABlock(count);`.

### CODE REVIEW

**Comment by danmoseley** [comment]
Worth an assert to self document?

**Comment by skyoxZ** [comment]
> Worth an assert to self document?

My answer would rather be no. Perhaps `ExpandByABlock` had been something more complicated but at the moment its responsibility is quite straightforward and well documented: asserting current chunk is full and moving to a new chunk with a minimum size of `minBlockCharCount`. 
https://github.com/dotnet/runtime/blob/fa1164c327052042120bf0d3b6fc81e86cfab69d/src/libraries/System.Private.CoreLib/src/System/Text/StringBuilder.cs#L2438-L2446

**Comment by tannergooding** [comment]
If we're making an assumption, we should add an assert to validate that assumption holds true long term. Otherwise, it is trivially possible for a bug to be introduced due to a later refactoring or change.

**Review by stephentoub — APPROVED** [review]

**Review by danmoseley — APPROVED** [review]

**Comment by danmoseley** [comment]
timeouts, let's try again

**Pull request merged**
