### PR TITLE
[mono] Initialize module's image ALC for dynamic objects

### LINKED ISSUE #90164: get attributes from objects created on runtime
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`Runtimebject.GetType().GetProperty("prop1").GetCustomAttributes()` raised an error when the runtime object was created through `System.Reflection.Emit.TypeBuilder`

platform: Blazor wasm
version: 7.0.8
browser: Chrome

### Expected Behavior

`Runtimebject.GetType().GetProperty("prop1").GetCustomAttributes()` return a list of attributes contains Display and Required attribute

### Steps To Reproduce

I created a type through `System.Reflection.Emit.TypeBuilder` and named it `RutimeObject`

then I added a property named `prope1`. then add some attributes to the prop1 (`Display` and `Required` attributes)
then I create an instance from `RuntimeObject`
when I try to get custom attributes through reflection 
`Runtimebject.GetType().GetProperty("prop1").GetCustomAttributes();`

this has not happened if you add only one attribute and it happened if add 2 or  more attributes

### Exceptions (if any)

```
dotnet.7.0.7.d6ly7i5yxa.js:5  Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:735, condition `<disabled>' not met

    at xe (dotnet.7.0.7.d6ly7i5yxa.js:5:509)
    at Object.je (dotnet.7.0.7.d6ly7i5yxa.js:5:792)
    at _mono_wasm_trace_logger (dotnet.7.0.7.d6ly7i5yxa.js:14:104923)
    at 00993286:0x9bf7
    at 00993286:0xa5a65
    at 00993286:0x1c0037
    at 00993286:0x1c00c6
    at 00993286:0x1c0109
    at 00993286:0x1c00dc
    at 00993286:0x33f41
```

### .NET Version

8.0.100-preview.3.23178.7

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kotlarmilos**
This PR initializes module's image ALC for dynamic objects created during the runtime.

Fixes https://github.com/dotnet/runtime/issues/90164

### CODE REVIEW

**Comment by vargaz** [comment]
Maybe we should set the alc of the dynamic images instead ?

**Comment by kotlarmilos** [comment]
During initialization, the ALC is set in `mono_reflection_dynimage_basic_init` to default `mono_alc_get_default`:
https://github.com/dotnet/runtime/blob/82fdd0bf83cebf71dcc49a03cfd3cbe0fa9b6280/src/mono/mono/metadata/sre.c#L1265

When retrieving custom attributes in `mono_reflection_get_custom_attrs_by_type_handle`, parameter `MonoObjectHandle obj` seems to be a MonoClass containing an image without ALC.

**Comment by lambdageek** [comment]
> During initialization, the ALC is set in `mono_reflection_dynimage_basic_init` to default `mono_alc_get_default`:
> 
> https://github.com/dotnet/runtime/blob/82fdd0bf83cebf71dcc49a03cfd3cbe0fa9b6280/src/mono/mono/metadata/sre.c#L1265
> 
> When retrieving custom attributes in `mono_reflection_get_custom_attrs_by_type_handle`, parameter `MonoObjectHandle obj` seems to be a MonoClass containing an image without ALC. Should the MonoObjectHandle's image contain the ALC?

I wonder if this is because dynamic assemblies have two images - one for the assembly, and one for the image. (this is some old legacy stuff from how the SRE api works).  Maybe only the assembly image has an ALC set, but the module image does not? I think the emitted class gets assigned to the module image.

**Comment by kotlarmilos** [comment]
> I wonder if this is because dynamic assemblies have two images - one for the assembly, and one for the image. (this is some old legacy stuff from how the SRE api works). Maybe only the assembly image has an ALC set, but the module image does not? I think the emitted class gets assigned to the module image.

Thanks for pointing out, the module's image ALC wasn't set.

Is there anything we can do to retrieve the image from the assembly, instead of creating a new one for the module?
https://github.com/dotnet/runtime/blob/64243bbf5e9ee53c0c4c5678f2cd8c7f1c9b4f6f/src/mono/mono/metadata/sre.c#L1286C4-L1291

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
> Is there anything we can do to retrieve the image from the assembly, instead of creating a new one for the module?

 I haven't thought about it on a while, but I think I convinced myself that it's a consequence of how the SRE public API works and there's no way to avoid it without a bunch of hacks. But maybe it's with another look

**Comment by srxqds** [comment]
why this pr not merged to release/8.0?

**Pull request merged**
