### PR TITLE
Upgrade SDK to Preview 5

### PR DESCRIPTION
**Pull request by agocke**
First attempt at an upgrade to Preview 5.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
OMG; all checks successful. But we should also queue an official build :)

**Review by stephentoub — APPROVED** [review]

**Comment by agocke** [comment]
Official build succeeded :)

**Comment by ViktorHofer** [comment]
@agocke I converted this to a draft so that it doesn't get merged until P5 is released.

**Review by ViktorHofer — APPROVED** [review]

**Comment by agocke** [comment]
Failures look like they're already in the target branch. I don't see anything that looks like it's caused by the new SDK. This may help address existing CI issues (https://github.com/dotnet/runtime/issues/68393) so I think it's worth merging now.

**Pull request merged**
