### PR TITLE
Fixes #62167. WriteAsync may truncate data if called after .Advance(int)

### LINKED ISSUE #62167: Calling Pipe.Writer.WriteAsync after Pipe.Writer.Advance flush truncated data to the PipeReader.
### Description
(I edited this issue when I noticed the bug did not affected only ReadAtLeastAsync, original title was 'Pipe.ReadAtLeastAsync return with less bytes than asked.')

Calling Pipe.Writer.WriteAsync after Pipe.Writer.Advance flush truncated data to the PipeReader.
I initially found this bug because ReadAtLeastAsync returned me a 12 bytes buffer, when I asked for 26.
image

### Reproduction Steps

**Edit:**

```csharp
[Test]
public async Task ReadAtLeastAsync_works()
{
    Pipe pipe = new Pipe(new PipeOptions(minimumSegmentSize: 1));
    Task<ReadResult> resTask = pipe.Reader.ReadAtLeastAsync( 26 ).AsTask();

    pipe.Writer.GetSpan( 14 );
    pipe.Writer.Advance( 14 );
    await pipe.Writer.WriteAsync( new byte[12] );
    ReadResult res = await resTask;
    res.Buffer.Length.Should().Be( 26 ); //fails
}
```
### Expected behavior

Data written is not overwritten.

### Actual behavior

Only 12 bytes are returned. The first write is partially overwritten.

### Regression?

The reproduction does not show the bug on version 4.5.4.

### Known Workarounds

Call FlushAsync before calling WriteAsync if you did Advance() before.

### Configuration

N/A.

### PR DESCRIPTION
**Pull request by Kuinox**
Fixes #62167. 
It took me way too much time to pinpoint where this issue came from ^^'.

### CODE REVIEW

**Review by halter73 — APPROVED** [review]
Great find!

**Comment by halter73** [comment]
While this is an unusual writing pattern, it is valid. Without this fix, you can get corrupted data. We should service this.

**Comment by danmoseley** [comment]
thanks @Kuinox !

**Comment by Kuinox** [comment]
> While this is an unusual writing pattern

I use this pattern to write an user provided buffer.
In the first part, I write the small packet header, then I call WriteAsync to write the user data.

**Review by davidfowl — APPROVED** [review]
Old bug it seems!

**Review by BrennanConroy — APPROVED** [review]

**Comment by BrennanConroy** [comment]
Thanks a lot @Kuinox!

**Comment by Kuinox** [comment]
Thanks everyone !

**Comment by davidfowl** [comment]
Thank you!

**Pull request merged**
