### PR TITLE
Reduce calli address spilling

### PR DESCRIPTION
**Pull request by MichalPetryka**
Avoid spilling FTN_ADDR params, removes spilling of address on 0 arg default cconv callis.

Split off from #85197.

### CODE REVIEW

**Review by AndyAyersMS — APPROVED** [review]

**Comment by MichalPetryka** [comment]
This seems to trigger huge diffs due to delegate constructors taking less of the inliner budget.

**Comment by AndyAyersMS** [comment]
Seems like the huge diffs are mostly in what are likely unrealistic test cases.

I'd like to see the ASP.NET diffs but unfortunately I can't recollect this right now as the machine I use is offline. So let's hold onto this change until I can get that collection going again.

**Comment by AndyAyersMS** [comment]
I have a new ASP.NET SPMI collection so am going to rerun that part of normal CI.

@jakobbotsch do you know if the stress failures here mostly from promotion?

**Comment by AndyAyersMS** [comment]
Seems like since SPMI passed the first time the only rerun option is to bounce the PR.

@MichalPetryka why don't we merge this up to main and trigger a new round of CI that way? Would prefer you to do this but I can do it if you like.

**Comment by MichalPetryka** [comment]
> do you know if the stress failures here were mostly from promotion?

I'd like to rerun stress after @jakobbotsch fixes the promotion issues.

**Comment by AndyAyersMS** [comment]
FYI you can generally just merge and not rebase -- that makes it a bit easier for us to track what is going on.

**Comment by jakobbotsch** [comment]
> @jakobbotsch do you know if the stress failures here were mostly from promotion?

Looks like it, the remaining failures are #85449, #85426 and #48798 as far as I can tell.

**Comment by AndyAyersMS** [comment]
Seems like the various failures are known, so let's merge.

**Comment by AndyAyersMS** [comment]
@MichalPetryka thanks!

**Pull request merged**
