### PR TITLE
DO NOT MERGE: test JIT assert on superpmi replay/asmdiffs pipelines

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
cc @kunalspathak 

I want to see what our current replay/asmdiffs pipelines do for a JIT assert during SPMI replay

**Comment by BruceForstall** [comment]
For asmdiffs, the Extensions page shows "No diffs found", as expected. If you don't dig deeper, you wouldn't see the errors.

The asmdiffs jobs do have errors. However, they also have errors currently if there is MISSING data, so people might start ignoring the errors. If you look at the console logs for each failure (e.g., drilling in from [this](https://dev.azure.com/dnceng/public/_build/results?buildId=1465622&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=486c0909-f67d-5748-80b3-bb1d531e7b43) page), you see failures [like](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61477-merge-e9606bb7dc3b44b183/unix-arm64/1/console.56062aa8.log?sv=2019-07-07&se=2021-12-01T20%3A25%3A43Z&sr=c&sp=rl&sig=uNjvPifukcpgCo7zznELlncXyfVZxWHe0a4z1ZLK5fs%3D):

```
ERROR: Exception thrown: DebugBreak or AV Exception 123
ERROR: Method 1 of size 86 failed to load and compile correctly by JIT2.
ERROR: method 1 is missing a compileResult, cannot do diffing
ISSUE: <ASSERT> D:\a\_work\1\s\src\coreclr\jit\compiler.cpp (1782) - info.compMethodSuperPMIIndex != 1
```

**Comment by kunalspathak** [comment]
> If you look at the console logs for each failure (e.g., drilling in from this page), you see failures like:

Right, it is very easy to get these errors ignored. If we can scan them and report it back to the extension under a separate section, that might help.

**Comment by BruceForstall** [comment]
With the replay pipeline, you need to dig into the log files. The jobs do show as failed.

@kunalspathak Is there an equivalent of #61483 for the replay pipeline? Maybe some kind of summary output to an "Extensions" tab would make sense here, also?

**Comment by kunalspathak** [comment]
We don't have a tracking issue, but should probably do it when we pursue #61483

**Pull request closed without merging**
