### PR TITLE
[mono] Use llvm 19.1.0

### PR DESCRIPTION
**Pull request by radekdoulik**

### CODE REVIEW

**Comment by radekdoulik** [comment]
Linker error on Windows:

```  LLVMSupport.lib(ErrorHandling.cpp.obj) : error LNK2001: unresolved external symbol __imp_RtlGetLastNtStatus
  mono\mini\mono-aot-cross.exe : fatal error LNK1120: 1 unresolved externals
```

is a new dependency on `ntdll`. Coming from https://github.com/dotnet/llvm-project/commit/cb7690af09b95bb944baf1b5a9ffb18f86c12130

**Comment by radekdoulik** [comment]
The WBT errors are:

```
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Workload installation failed: Version 8.0.8 of package microsoft.net.runtime.emscripten.3.1.34.node.linux-x64 is not found in NuGet feeds [https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/general-testing/nuget/v3/index.json;file:///__w/1/s/artifacts/packages/Release/Shipping/.](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/general-testing/nuget/v3/index.json;file:///__w/1/s/artifacts/packages/Release/Shipping/) [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : workload install failed with exit code 1: Installing pack Microsoft.NET.Runtime.WebAssembly.Sdk version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Skipping NuGet package signature verification. [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Writing workload pack installation record for Microsoft.NET.Runtime.WebAssembly.Sdk version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Installing pack Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Writing workload pack installation record for Microsoft.NETCore.App.Runtime.Mono.browser-wasm version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Installing pack Microsoft.NETCore.App.Runtime.AOT.linux-x64.Cross.browser-wasm version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Writing workload pack installation record for Microsoft.NETCore.App.Runtime.AOT.linux-x64.Cross.browser-wasm version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Installing pack Microsoft.NET.Runtime.MonoAOTCompiler.Task version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Writing workload pack installation record for Microsoft.NET.Runtime.MonoAOTCompiler.Task version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Installing pack Microsoft.NET.Runtime.MonoTargets.Sdk version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Writing workload pack installation record for Microsoft.NET.Runtime.MonoTargets.Sdk version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Installing pack Microsoft.NET.Runtime.Emscripten.3.1.34.Node.linux-x64 version 8.0.8... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Workload installation failed. Rolling back installed packs... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Rolling back pack Microsoft.NET.Runtime.Emscripten.3.1.34.Node.linux-x64 installation... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Rolling back pack Microsoft.NET.Runtime.MonoTargets.Sdk installation... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Uninstalling workload pack Microsoft.NET.Runtime.MonoTargets.Sdk.net8 version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Rolling back pack Microsoft.NET.Runtime.MonoAOTCompiler.Task installation... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Uninstalling workload pack Microsoft.NET.Runtime.MonoAOTCompiler.Task.net8 version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Rolling back pack Microsoft.NETCore.App.Runtime.AOT.linux-x64.Cross.browser-wasm installation... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Uninstalling workload pack Microsoft.NETCore.App.Runtime.AOT.Cross.net8.browser-wasm version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Rolling back pack Microsoft.NETCore.App.Runtime.Mono.browser-wasm installation... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Uninstalling workload pack Microsoft.NETCore.App.Runtime.Mono.net8.browser-wasm version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Rolling back pack Microsoft.NET.Runtime.WebAssembly.Sdk installation... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Uninstalling workload pack Microsoft.NET.Runtime.WebAssembly.Sdk.net8 version 8.0.7... [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
/__w/1/s/src/mono/nuget/Microsoft.NET.Runtime.WorkloadTesting.Internal/Sdk/WorkloadTesting.Core.targets(201,5): error : Workload installation failed: Version 8.0.8 of package microsoft.net.runtime.emscripten.3.1.34.node.linux-x64 is not found in NuGet feeds [https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/general-testing/nuget/v3/index.json;file:///__w/1/s/artifacts/packages/Release/Shipping/.](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-libraries-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/general-testing/nuget/v3/index.json;file:///__w/1/s/artifacts/packages/Release/Shipping/) [/__w/1/s/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
    0 Warning(s)
    2 Error(s)
```

@lewing @maraf, is it something new or happening on main as well?

**Comment by radekdoulik** [comment]
The aot compiler fails when trying to register intrinsics

```
(gdb) bt
#0  0x0000aaaaab9a38a0 in DecodeFixedType(llvm::ArrayRef<llvm::Intrinsic::IITDescriptor>&, llvm::ArrayRef<llvm::Type*>, llvm::LLVMContext&) ()
#1  0x0000aaaaab9a3510 in llvm::Intrinsic::getType(llvm::LLVMContext&, unsigned int, llvm::ArrayRef<llvm::Type*>) ()
#2  0x0000aaaaab9a543c in llvm::Intrinsic::getDeclaration(llvm::Module*, unsigned int, llvm::ArrayRef<llvm::Type*>) ()
#3  0x0000aaaaab308eac in mono_llvm_register_intrinsic (module=0xaaaaabd22060, id=INTRINS_EH_TYPEID_FOR, out_type=0xffffffffd7f0) at /root/llvm/runtime/src/mono/mono/mini/mini-llvm-cpp.cpp:717
#4  0x0000aaaaab2fe90c in add_intrinsic (ctx=0xaaaaabd36750, id=66) at /root/llvm/runtime/src/mono/mono/mini/mini-llvm.c:13843
#5  0x0000aaaaab2fe878 in get_overloaded_intrins (ctx=0xaaaaabd36750, id=66, overloaded_id=66) at /root/llvm/runtime/src/mono/mono/mini/mini-llvm.c:13951
#6  0x0000aaaaab2fe6ec in call_overloaded_intrins (ctx=0xaaaaabd36750, id=66, ovr_tag=0, args=0xffffffffda70, name=0xaaaaaab8d6b8 "") at /root/llvm/runtime/src/mono/mono/mini/mini-llvm.c:5793
#7  0x0000aaaaab2fe188 in call_intrins (ctx=0xaaaaabd36750, id=66, args=0xffffffffda70, name=0xaaaaaab8d6b8 "") at /root/llvm/runtime/src/mono/mono/mini/mini-llvm.c:5810
#8  0x0000aaaaab2ecf90 in emit_llvmonly_landing_pad (ctx=0xaaaaabd36750, group_index=0, group_size=1) at /root/llvm/runtime/src/mono/mono/mini/mini-llvm.c:5169
#9  0x0000aaaaab2e141c in emit_method_inner (ctx=0xaaaaabd36750) at /root/llvm/runtime/src/mono/mono/mini/mini-llvm.c:13412
#10 0x0000aaaaab2df1a0 in mono_llvm_emit_method (cfg=0xaaaaabd2c460) at /root/llvm/runtime/src/mono/mono/mini/mini-llvm.c:12869
#11 0x0000aaaaab0ed7ec in mini_method_compile (method=0xaaaaabc67228, opts=391195135, flags=(JIT_FLAG_AOT | JIT_FLAG_FULL_AOT | JIT_FLAG_LLVM | JIT_FLAG_EXPLICIT_NULL_CHECKS | JIT_FLAG_LLVM_ONLY | JIT_FLAG_INTERP), parts=0, aot_method_index=0)
    at /root/llvm/runtime/src/mono/mono/mini/mini.c:3927
#12 0x0000aaaaab1e31b8 in compile_method (acfg=0xaaaaabcdb9d0, method=0xaaaaabc67228) at /root/llvm/runtime/src/mono/mono/mini/aot-compiler.c:9586
#13 0x0000aaaaab1d960c in compile_methods (acfg=0xaaaaabcdb9d0) at /root/llvm/runtime/src/mono/mono/mini/aot-compiler.c:13194
#14 0x0000aaaaab1d3738 in aot_assembly (ass=0xaaaaabcdb070, jit_opts=374417919, aot_options=0xffffffffe890) at /root/llvm/runtime/src/mono/mono/mini/aot-compiler.c:15306
#15 0x0000aaaaab1d07c0 in mono_aot_assemblies (assemblies=0xaaaaabcdb3c0, nassemblies=1, jit_opts=374417919, runtime_args=0xaaaaabc53ce0, 
    aot_options=0xaaaaabc53f70 "no-opt,static,direct-icalls,deterministic,_child,mattr=simd,nodebug,llvm-path=/root/llvm/runtime/src/mono/browser/emsdk/bin/,static,dwarfdebug,dedup-skip,trimming-eligible-methods-outfile=/root/llvm/r"...)
    at /root/llvm/runtime/src/mono/mono/mini/aot-compiler.c:15860
#16 0x0000aaaaab1c6494 in main_thread_handler (user_data=0xffffffffed78) at /root/llvm/runtime/src/mono/mono/mini/driver.c:1423
#17 0x0000aaaaab1c26ac in mono_main (argc=5, argv=0xffffffffef98) at /root/llvm/runtime/src/mono/mono/mini/driver.c:2581
#18 0x0000aaaaaaed0178 in mono_main_with_options (argc=6, argv=0xffffffffef98) at /root/llvm/runtime/src/mono/mono/mini/main.c:36
#19 0x0000aaaaaaed0138 in main (argc=6, argv=0xffffffffef98) at /root/llvm/runtime/src/mono/mono/mini/main.c:88
```

**Comment by pavelsavara** [comment]
This is interesting `out of bounds memory access` in AOT `System.Collections.Specialized.Tests`
[Log](https://gist.github.com/pavelsavara/4b4c8aab5975115375d6c0f8ae18629b) [Original](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-105427-merge-4530f0f7bb494542b4/System.Collections.Specialized.Tests/1/console.33360852.log?helixlogtype=result) on this PR

**Comment by pavelsavara** [comment]
This doesn't impact WASI-SDK, right ? That's still LLVM 18

**Comment by lewing** [comment]
> This doesn't impact WASI-SDK, right ? That's still LLVM 18

it only impacts the aot-compiler for wasi, everything else is built using the sdk

**Review by lewing — APPROVED** [review]

**Pull request merged**
