### PR TITLE
SPMI: Avoid duplicate key lookups on replay

### PR DESCRIPTION
**Pull request by jakobbotsch**
The commonly used pattern AssertMapAndKeyExists followed by map->Get
means we do two key lookups. Change the macros to return the value after
we have verified that the key exists. This makes replay 2-3% faster and
avoids some of the boilerplate.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

**Review by TIHan — APPROVED** [review]

**Review by BruceForstall — APPROVED** [review]
Nice!

Now if you want to improve replay speed... https://github.com/dotnet/runtime/issues/77878 :-)

**Comment by jakobbotsch** [comment]
> Now if you want to improve replay speed... #77878 :-)

Tempting, seems like some low hanging fruit :)

**Comment by jakobbotsch** [comment]
The failure is #78079

**Pull request merged**
