### PR TITLE
Use workstation GC in outerloop NativeAOT libs runs

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Linux has a habit of overpromising memory and then underdelivering when one wants to actually use it.

Native AOT test legs often get OOM killed. For Pri-0 runs we had success switching to workstation GC that is slower, but uses less memory. Try the same for libs testing.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Comment by Suchiman** [comment]
Is this a problem with or without the new memory conserving DATAS mode?

**Comment by MichalStrehovsky** [comment]
> Is this a problem with or without the new memory conserving DATAS mode?

I think it was only made default on NativeAOT+ASP.NET for whatever reason and it's opt in everywhere else, so this would be without.

**Comment by Suchiman** [comment]
> I think it was only made default on NativeAOT+ASP.NET for whatever reason and it's opt in everywhere else, so this would be without.

Might be worth a try enabling as it can cut down heap size by up to 10x in server GC mode.

**Comment by MichalStrehovsky** [comment]
> > I think it was only made default on NativeAOT+ASP.NET for whatever reason and it's opt in everywhere else, so this would be without.
> 
> Might be worth a try enabling as it can cut down heap size by up to 10x in server GC mode.

Sure, but we have `IlcUseServerGc` already hooked up and it gets the job done. We'd need another hook for datas and it's not clear if it would be an improvement. We're running many ilc.exe instances in parallel.

**Review by jkotas — APPROVED** [review]

**Pull request merged**
