### PR TITLE
Workload promotion

### PR DESCRIPTION
**Pull request by joeloff**
This PR fixes up the build promotion issue around duplicate aka.ms links where some of the new zips used for VSDROP are causing duplicate files. It's also cleaning up published artifacts for VS.

We previously published the individual MSIs + JSON manifests for VS. Since we now group these by SDK feature bands in zip files, we only need to publish the zips. The zips were also duplicated in two artifacts folders so we'd download the zip from workloads and workloads-vs.

### CODE REVIEW

**Review by mmitche — APPROVED** [review]
LGTM with a verify of the official build. I would do a test promotion by assigning to the general testing channel:

`darc add-build-to-channel <BAR build id> --channel "General Testing"`

Note you'll need an azdo pat in addition to your normal darc PAT for this

**Comment by joeloff** [comment]
> LGTM with a verify of the official build. I would do a test promotion by assigning to the general testing channel:
> 
> `darc add-build-to-channel <BAR build id> --channel "General Testing"`
> 
> Note you'll need an azdo pat in addition to your normal darc PAT for this

I assume the BAR ID is just the one from the official build against my internal branch?

**Review by hoyosjs — APPROVED** [review]

**Comment by mmitche** [comment]
> > LGTM with a verify of the official build. I would do a test promotion by assigning to the general testing channel:
> > `darc add-build-to-channel <BAR build id> --channel "General Testing"`
> > Note you'll need an azdo pat in addition to your normal darc PAT for this
> 
> I assume the BAR ID is just the one from the official build against my internal branch?

Correct. The one that appears in the build tags:

image

**Comment by joeloff** [comment]
Internal builds are all green. Rerunning the CI checks that failed

**Pull request merged**
