### PR TITLE
Make bashing to constants nicer

### PR DESCRIPTION
**Pull request by SingleAccretion**
Replace `ChangeOperConst` with `BashToConst`.

The nature of bashing to a constant is that the code doing it practically always wants to set the constant value and the type so it makes sense to do all three at once - it also enables some more stringent asserts.

But mostly this method is for convenience.

Unfortunately, the second commit causes diffs, because now containment is enabled where it was not previously (for `float` constants with the upper bit set). Even more unfortunately, this causes the following regression in `System.Numerics.Tests.Perf_Quaternion:ConjugateBenchmark` (and two sister benchmarks):
```diff
-       mov      eax, 0xD1FFAB1E
-       mov      dword ptr [rdx], eax
-       mov      dword ptr [rdx+4], eax
-       mov      dword ptr [rdx+8], eax
+       mov      dword ptr [rdx], 0xD1FFAB1E
+       mov      dword ptr [rdx+4], 0xD1FFAB1E
+       mov      dword ptr [rdx+8], 0xD1FFAB1E
```
I have built the benchmarks locally and can measure ~20-40% increase in time, though the accuracy of such measurements is highly questionable as the benchmarks "take" `0.1 ns`, with errors of the same magnitude. It is a CQ regression, so, given fixing it properly is out of scope for this PR, I see a few ways to address the problem:

1) Abandon the change.
2) Abandon the new assert.
3) Quirk the lowering transform to retain the previous behavior.

Without the second commit, there is one other source of diffs, which has to do with the fact that the old code in assertion propagation for relops left nodes with small types unchanged, and `gtFoldExprConst` fails to fold things like `EQ(bool 0, int 0)`. The new code (correctly) retypes the node to `TYP_INT`, thus enabling the folding. I have checked that using "actual" types in `gtFoldExprConst` does not yield much beyond what this PR enables already.

Diffs with the second commit: [`win-x64`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-58171/win-x64.md), [`win-arm64`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-58171/win-arm64.md), [`win-x86`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-58171/win-x86.md), [`linux-x64`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-58171/linux-x64.md).

### CODE REVIEW

**Comment by JulieLeeMSFT** [comment]
cc @dotnet/jit-contrib @AndyAyersMS please review the community PR.

**Comment by AndyAyersMS** [comment]
For the regression, seems like we ought to extend #44419 to cover float literals as well?

**Comment by SingleAccretion** [comment]
The tricky part may be that the encoding for floating point operations is larger, so we'll still not be able to get "the best" result.

**Comment by AndyAyersMS** [comment]
> The tricky part may be that the encoding for floating point operations is larger, 

Can you elaborate? I'm not sure I follow. 

If there is a tradeoff, presumably the CSE cost heuristics would try and balance this somehow?

**Comment by SingleAccretion** [comment]
> Can you elaborate? I'm not sure I follow.

Sure. The existing codegen is "ideal" since it uses an integer register for the stores. Were we to CSE the floating point constant, we'd end up using the floating point stores (because we don't want to play tricks with types in the optimizer - or do we...?), which are a bit bigger. It is still better than not using any register at all for the stores though.

> If there is a tradeoff, presumably the CSE cost heuristics would try and balance this somehow?

I would say it is a bit complicated case to handle "cleanly"... Basically the ideal outcome requires us to:
1) See how many uses a constant float has.
2) If it has "enough" uses where the type doesn't matter (in indirect stores say), retype them to integers.
3) CSE the integer constant.

I am not convinced the gains would justify the complexity in this case. I was also thinking of some way to handle this later, in lowering, by keeping tabs on stores as we lower the range and re-evaluating containment if we see a situation where LSRA could reuse a register with a constant (would also open the door for some coalescing I suppose). But it requires more careful design and I worry about the TP implications.

**Comment by AndyAyersMS** [comment]
These benchmarks are perhaps not all that valuable. @tannergooding any way we can measure something more meaningful?

newplot (70)

**Review by AndyAyersMS — APPROVED** [review]
I like the change, and since we were already containing some float constants it seems odd to hold back here because of a few regressions and not allow containing them all.

**Pull request merged**
