### PR TITLE
Add support for unwinding function fragments in the DAC

### PR DESCRIPTION
**Pull request by davmason**
With lots of help from @ChrisAhna we discovered that the latest BBT will optimize runtime FCALLs in to multiple function fragments, which the unwinder does not currently support.

This change adds the ability to map from a function fragment back to the owning function.

### CODE REVIEW

**Comment by jkotas** [comment]
What was the manifestation of this bug? Is there issue opened on it?

**Comment by davmason** [comment]
It was found on desktop after a toolset update. As far as we know coreclr is not currently affected by it, but will be whenever we update to a new enough BBT to start doing function fragment optimizations.

The symptom is that debugger/DAC stackwalking fails on any FCALL frames that have been optimized with fragments.

**Review by davidwrighton — APPROVED** [review]
Change looks good. I assume you've tested the logic in the problematic scenario.

**Comment by davmason** [comment]
@davidwrighton yes, I verified it fixes the failing desktop testcase.

**Pull request merged**
