### PR TITLE
Correctly find the node to fix in regex generator codefix

### LINKED ISSUE #72047: `UpgradeToRegexGeneratorCodeFixer` crashes with `InvalidCastException`
### Description

Test:

```csharp
        [Fact]
        public async Task TestAsArgument()
        {
            string test = @"using System.Text.RegularExpressions;
public class C
{
    void M1(Regex r) => _ = r;
    void M2() => M1([|new Regex("""")|]);
}
";

            string fixedCode = @"using System.Text.RegularExpressions;
public partial class C
{
    void M1(Regex r) => _ = r;
    void M2() => M1(MyRegex());
    [RegexGenerator("""")]
    private static partial Regex MyRegex();
}
";

            await VerifyCS.VerifyCodeFixAsync(test, fixedCode);
        }
```

### Expected behavior

No crash. The test should pass

### Actual behavior

Test fails

### Other information

The fix here is pass `true` for `getInnermostNodeForTie`. The fix was included in https://github.com/dotnet/runtime/pull/71264, but we're breaking down the PR now.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes https://github.com/dotnet/runtime/issues/72047

### CODE REVIEW

**Review by joperezr — APPROVED** [review]
Thanks @Youssef1313.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks @Youssef1313.  You're awesome!

**Comment by joperezr** [comment]
Looks like my latest PR caused a merge conflict on the tests. I took the liberty of fixing the merge conflict and pushing to your PR, I hope that is ok. Will merge this as soon as CI is green.

**Comment by Youssef1313** [comment]
@joperezr CI failures are unrelated.

**Pull request merged**
