### PR TITLE
Fix BigInteger bitwise operators on certain negative numbers

### LINKED ISSUE #109669: BigInteger correctness regression from .NET 8
### Description

BigInteger produces incorrect results in .NET 9, while this doesn't repro with .NET 8 or earlier.

### Reproduction Steps

```cs
Console.WriteLine(new BigInteger(-4294967296) & new BigInteger(-1919810));
Console.WriteLine(new BigInteger(-4042322161) & new BigInteger(-252645136));
Console.WriteLine(new BigInteger(-8589934592) | new BigInteger(-21474836480));

Console.WriteLine(BigInteger.Parse("-4294967296") & BigInteger.Parse("-1919810"));
Console.WriteLine(BigInteger.Parse("-4042322161") & BigInteger.Parse("-252645136"));
Console.WriteLine(BigInteger.Parse("-8589934592") | BigInteger.Parse("-21474836480"));
```

### Expected behavior

```
-4294967296
-4294967296
-4294967296
-4294967296
-4294967296
-4294967296
```

### Actual behavior

```
0
0
0
0
0
0
```

### Regression?

Yes

### Known Workarounds

No

### Configuration

.NET 9 rc2

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Rob-Hague**
Fixes #109669 c.f. https://github.com/dotnet/runtime/issues/109669#issuecomment-2466727223

### CODE REVIEW

**Comment by Rob-Hague** [comment]
An alternative or follow-up could be to remove this constructor and replace the 3 uses with calls to the public ROS\<byte> constructor, e.g.

```diff
diff --git a/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigInteger.cs b/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigInteger.cs
index b3355ff6867..4a0d53e6be2 100644
--- a/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigInteger.cs
+++ b/src/libraries/System.Runtime.Numerics/src/System/Numerics/BigInteger.cs
@@ -2476,7 +2476,7 @@ private static BigInteger Subtract(ReadOnlySpan<uint> leftBits, int leftSign, Re
             if (rightBufferFromPool != null)
                 ArrayPool<uint>.Shared.Return(rightBufferFromPool);

-            var result = new BigInteger(z);
+            var result = new BigInteger(MemoryMarshal.AsBytes(z));

             if (resultBufferFromPool != null)
                 ArrayPool<uint>.Shared.Return(resultBufferFromPool);
```

**Comment by huoyaoyuan** [comment]
Duplicate of #105456

**Comment by tannergooding** [comment]
Merged https://github.com/dotnet/runtime/pull/105456

Will still take this PR for the explicit regression test and typo fix.

**Comment by jeffhandley** [comment]
@tannergooding Once this is merged, do you want to cherry-pick it into #109732 for the backport too so we take this new test with the fix?

**Comment by tannergooding** [comment]
Can do.

**Review by tannergooding — APPROVED** [review]

**Pull request merged**
