### PR TITLE
Fix restore of internal tools and enable IBC merge

### LINKED ISSUE #1024: Fix internal tool restore in official build and re-enable
I saw this error with the CoreCLR and Libraries "Restore internal tools" steps while trying to develop official builds:

```
Build FAILED. 
 
 "/Users/runner/runners/2.160.1/work/1/s/eng/common/internal/Tools.csproj" (Restore target) (1) -> 
 (Restore target) -> 
 /Users/runner/runners/2.160.1/work/1/s/.dotnet/sdk/5.0.100-alpha1-015772/NuGet.targets(123,5): error : Value cannot be null. (Parameter 'folderName') [/Users/runner/runners/2.160.1/work/1/s/eng/common/internal/Tools.csproj] 
```

https://github.com/dotnet/runtime/pull/1016 removes internal tooling to unblock the official build, but this needs to be fixed and re-enabled.

https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/pipelines/coreclr/templates/build-job.yml#L83-L87

https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/pipelines/coreclr/templates/build-job.yml#L111-L130

https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/pipelines/libraries/build-job.yml#L68-L80

https://github.com/dotnet/runtime/blob/385121f62de417c2a2416add568b34880b4c5ea6/eng/Versions.props#L18-L19

### PR DESCRIPTION
**Pull request by safern**
Fixes: https://github.com/dotnet/runtime/issues/1024

Test build is: https://dev.azure.com/dnceng/internal/_build/results?buildId=487330

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Do we have similar challenges on the installer side? We do have some nuget credprovider files in eng which I don't really know what they are for: https://github.com/dotnet/runtime/blob/master/eng/install-nuget-credprovider.sh.

**Comment by dagood** [comment]
`install-nuget-credprovider.sh` is used by `install-nuget-credprovider-then-build.sh` and `install-nuget-credprovider-then-msbuild.sh` to install the cred provider inside the Docker container for Linux Installer builds. It's already being exercised by official builds so I don't think there's any concern there. (Although we probably need to re-validate the internal build functionality in general, post-consolidation.)

**Comment by safern** [comment]
Yeah. Installer is special enough  because it runs inside a docker container but without using azure devops container support because some things need to be inside and other outside docker (from my understanding, @dagood can correct me). So that's why I didn't need to do anything in the installer side.

Rather than using those scripts I think it makes sense for coreclr and libraries to use the first class support stuff which are the AzDo tasks. Does that make sense to you guys?

**Comment by jaredpar** [comment]
> Rather than using those scripts I think it makes sense for coreclr and libraries to use the first class support stuff which are the AzDo tasks. Does that make sense to you guys?

I'd prefer to keep using the AzDO tasks here. 

The issue right now is builds are blocked hard stop. The issue is likely to go away in 1-3 days given that AzDO is working on a fix. Think we should just take the minimal to unblock builds now, and revert once the fix is in. Moving to a new container model should be a separate item (happy to discuss).

**Comment by safern** [comment]
> The issue right now is builds are blocked hard stop. The issue is likely to go away in 1-3 days given that AzDO is working on a fix. Think we should just take the minimal to unblock builds now, and revert once the fix is in. Moving to a new container model should be a separate item (happy to discuss).

This is a different thing though 😄 -- this is re-enabling IBC merge, this has nothing to do with the issue for the `Build.SourcesDirectory` evaluation.

**Comment by jaredpar** [comment]
> This is a different thing though 😄 -- this is re-enabling IBC merge, this has nothing to do with the issue for the Build.SourcesDirectory evaluation.

Well that's a silly mistake on my part. I retract my statement 😄

**Comment by safern** [comment]
Could someone please review?

**Review by trylek — APPROVED** [review]
LGTM

**Pull request merged**
