### PR TITLE
[release/5.0] Remove usages of native bootstrapping (#65901)

### PR DESCRIPTION
**Pull request by agocke**
* Remove usages of native bootstrapping
* Make sure cmake is in the path for mono wasm builds

Co-authored-by: Adeel Mujahid <3840695+am11@users.noreply.github.com>
(cherry picked from commit 8727ac772e1d8031691ee52e2d66e2520f78d01a)

### CODE REVIEW

**Comment by agocke** [comment]
Hmm, looks like this might require more work for 5.0. I wonder if not using Ninja is making a difference here.

**Comment by hoyosjs** [comment]
This might need https://github.com/dotnet/runtime/commit/ce4bf13ff1497b996383fd1917f218196fc63ea3

**Comment by agocke** [comment]
That seemed to have helped arm32, but not arm64 -- unfortunately I don't have a machine with VS2019 so I can't repro this locally

**Comment by akoeplinger** [comment]
It probably needs the changes from https://github.com/dotnet/runtime/commit/8c6a049cdb4bcd958cc3487775174bdd32e5fb64#diff-75d3892a37c4ce5e28b7c8d451beb0b8537b5f0526159cabbae6f62c877af1bfR173

> # CMake does not support the ARM or ARM64 assemblers on Windows when using the 
# MSBuild generator. When the MSBuild generator is in use, we manually compile the assembly files
# using this function.

**Comment by akoeplinger** [comment]
Do we really need to this when .NET 5 goes out of support in a ~two months?

**Comment by agocke** [comment]
This can produce a lot of stability issues, so it's good to get the product in a good state, even if it's going out of support

**Comment by agocke** [comment]
I think this fixes the build problems. Test problems are probably unrelated.

**Comment by hoyosjs** [comment]
The failures are pretty odd here. The tests are done within 40 seconds, but it gets killed after not having exited in 16 mins. cc: @dotnet/dnceng as I have no idea what could be done here to investigate, other than checking out a machine and see if it repros. Also, cc: @jbarton as it's odd that this is happening only on the crypto workitems.

For example https://helix.dot.net/api/jobs/7cebc4b8-65f5-4054-a2d9-a2033d89123e/workitems/System.Security.Cryptography.Algorithms.Tests?api-version=2019-06-17

**Comment by lpatalas** [comment]
> cc: dotnet/dnceng as I have no idea what could be done here to investigate

I'm not sure what's happening here but it seems intermittent. For example 7 out of the last 4k runs of `System.Security.Cryptography.Algorithms.Tests` finished with the same timeout error. I don't see any pattern there so far. It seems like someone would need to reproduce it on standalone VM to be able to tell more.

**Comment by akoeplinger** [comment]
Apart from the Crypto timeout it looks like the failures are unrelated:
- DirectoryLongerThanMaxLongPathWithExtendedSyntax_ThrowsException test needs https://github.com/dotnet/runtime/pull/64955
- SchSendAuxRecordHttpTest and other TLS handshake stuff was refactored in https://github.com/dotnet/runtime/pull/50815

**Comment by agocke** [comment]
@hoyosjs anything else?

**Comment by hoyosjs** [comment]
From an infra perspective - the changes LGTM. The failures are oddly hitting Crypto, seems consistent. Not sure how this would be related though.

**Review by hoyosjs — APPROVED** [review]
Without this we won't even be able to get a build. I think the failures should still be taken a look at.

**Comment by carlossanlop** [comment]
Libraries Test Run release coreclr Windows_NT x86 Release (windows.amd64.server2022.open.svc)

- **System.Security.Cryptography.Algorithms** - didn't seem to have any failures, but all the tests were skipped (not sure why they show up as failed, though):

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66406-merge-7cebc4b865f54054a2/System.Security.Cryptography.Algorithms.Tests/1/console.13b29219.log?sv=2019-07-07&se=2022-03-31T02%3A34%3A29Z&sr=c&sp=rl&sig=j7ZGR7zy057zUasKBWxR7RMjvGQmwD4C0OskQp3NQT0%3D


- **System.IO.FileSystem** - The tests that verify a very long path, failed. The paths were preceded with the extended path prefix `\\?\` as expected. I noticed these tests are running in windows.amd64.server2022. I do not know if these machines have long paths enabled by default. That could be the reason.

```
Expected one of: (System.IO.PathTooLongException, System.IO.DirectoryNotFoundException)
Actual: (System.IO.IOException)
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66406-merge-4d22085f3c51418993/System.IO.FileSystem.Tests/1/console.e1434b0c.log?sv=2019-07-07&se=2022-03-31T02%3A34%3A30Z&sr=c&sp=rl&sig=VXtCINtD42MKFIb3OqxIKODMFTIZD1IuxgB6Q1Oy6VI%3D

- **System.Net.Http.Functional** and **System.Net.Security**: All the issues seem to be caused by not being able to authenticate.

Exception examples:

```
System.Security.Authentication.AuthenticationException : Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.
```

```
System.ComponentModel.Win32Exception : The client and server cannot communicate, because they do not possess a common algorithm.
```

```
System.AggregateException : One or more errors occurred. (One or more errors occurred. ( Received an unexpected EOF or 0 bytes from the transport stream.)) (One or more errors occurred. (An error occurred while sending the request.))
      ---- System.AggregateException : One or more errors occurred. ( Received an unexpected EOF or 0 bytes from the transport stream.)
      -------- System.IO.IOException :  Received an unexpected EOF or 0 bytes from the transport stream.
      ---- System.AggregateException : One or more errors occurred. (An error occurred while sending the request.)
      -------- System.Net.Http.HttpRequestException : An error occurred while sending the request.
      ------------ System.Net.Http.WinHttpException : Error 12175 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A security error occurred'.
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66406-merge-4d22085f3c51418993/System.Net.Http.Functional.Tests/1/console.f7fecafa.log?sv=2019-07-07&se=2022-03-31T02%3A34%3A30Z&sr=c&sp=rl&sig=VXtCINtD42MKFIb3OqxIKODMFTIZD1IuxgB6Q1Oy6VI%3D

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66406-merge-4d22085f3c51418993/System.Net.Security.Tests/1/console.ef773acf.log?sv=2019-07-07&se=2022-03-31T02%3A34%3A30Z&sr=c&sp=rl&sig=VXtCINtD42MKFIb3OqxIKODMFTIZD1IuxgB6Q1Oy6VI%3D

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  We should treat this as tell mode.  Please work with @carlossanlop on a good time to merge.

**Comment by agocke** [comment]
The test failures seem unrelated -- machine issues, and the crypto tests passed in the checked configuration. I kicked off a re-run to see if the test hang goes away on retry

**Comment by hoyosjs** [comment]
They repeat... which is kind of odd.

**Comment by agocke** [comment]
OK, confirmed this is https://github.com/dotnet/runtime/issues/64389, we should be good to merge

**Pull request merged**
