### PR TITLE
Set DisableArcadeExcludeFromBuildSupport & support DotNetBuildTests flag

### PR DESCRIPTION
**Pull request by ViktorHofer**
Corresponding change in Arcade: https://github.com/dotnet/arcade/commit/cf685b45c1a9268dae9cec2478948c143a695168

1. Disable Arcade's infrastructure that caused test projects to be always excluded. We don't want and/or need this in runtime.
2. Respect the `DotNetBuildTests=true` flag and include the libs.tests subset. I think the libs tests are sufficient initially.

@tmds with this change you can now again remove the `DotNetBuildSkipTests=false` flag from your pipeline. Sorry for the mixed message here but it took us a while to get this right. I suggest to set `DotNetBuildTests=true` instead. See https://github.com/dotnet/arcade/commit/dd50030a0278e8c82f45624446fbec120b83c26b for the reasoning behind this. We inverted the default behavior to not build tests in the product (even outside of the source-only build).

### CODE REVIEW

**Comment by tmds** [comment]
> with this change you can now again remove the DotNetBuildSkipTests=false flag from your pipeline. Sorry for the mixed message here but it took us a while to get this right. I suggest to set DotNetBuildTests=true instead.

I had seen the Arcade PR, and had already made the corresponding change to our CI scripts. Our internal CI jobs are working, running tests, and passing!

**Review by ViktorHofer — COMMENTED** [review]
Builds are failing but I can't find a typo...

**Comment by tmds** [comment]
The error is:
```
Expected "$(_SuppressAllTargets)" to evaluate to a boolean instead of "", in condition "!$(_SuppressSdkImports) and !$(_SuppressAllTargets)".
```

`_SuppressAllTargets` gets set in `ExcludeFromBuild.BeforeCommonTargets.targets` which no longer gets imported due to setting `DisableArcadeExcludeFromBuildSupport` to `true`:
```
<Import Project="ExcludeFromBuild.BeforeCommonTargets.targets" Condition="'$(DisableArcadeExcludeFromBuildSupport)' != 'true'" />
```

**Comment by ViktorHofer** [comment]
Yes, thanks. I submitted https://github.com/dotnet/arcade/pull/14443 to fix that. @akoeplinger let me know about that offline.

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
