### PR TITLE
Mono: Update MBR samples 

### PR DESCRIPTION
**Pull request by lambdageek**
Update the wasm and console mbr samples.  The wasm sample now uses the WasmApp.InTree props and targets.  Both samples also use a json file for specifying the pre-canned changes that will be used to generate deltas.

### CODE REVIEW

**Comment by lambdageek** [comment]
@radical could you look over the stuff I copied over from the wasm sample.

**Comment by radical** [comment]
@lambdageek I was able to get the `mbr/browser` building with https://gist.github.com/radical/9dc72d1fe03ce99943d854b82f0fdc40

.. but then it fails because I don't have `/Users/alklig/work/roslynildiff/roslynildiff`

**Review by vargaz — APPROVED** [review]

**Comment by lambdageek** [comment]
@radical I'm confused. it was already building for me with the way that I have it in the PR - with `Directory.Build.props` just in the `sample/mbr/browser` folder.  The `sample/mbr/console` sample doesn't need it (because it's a normal desktop sample - not console v8 wasm).
My issue is that the `sample/mbr/browser/Directory.Build.props` is a copy/paste of `sample/wasm/Directory.Build.props` and it's a lot of boilerplate.  It would be better if we could share more of the contents in there.  But I'm not sure how to do that cleanly.

**Comment by radical** [comment]
```
/Users/radical/dev/runtime/src/mono/wasm/build/WasmApp.InTree.targets(4,3): warning MSB4011: "/Users/radical/dev/runtime/src/mono/wasm/build/WasmApp.targets" cannot be imported again. It was already imported at "/Users/radical/dev/runtime/src/mono/netcore/sample/mbr/browser/WasmDelta.csproj (33,3)". This is most likely a build authoring error. This subsequent import will be ignored.
/Users/radical/dev/runtime/src/mono/wasm/build/WasmApp.InTree.targets(4,3): warning MSB4011: "/Users/radical/dev/runtime/src/mono/wasm/build/WasmApp.targets" cannot be imported again. It was already imported at "/Users/radical/dev/runtime/src/mono/netcore/sample/mbr/browser/WasmDelta.csproj (33,3)". This is most likely a build authoring error. This subsequent import will be ignored.
```

Ah ok, it does build (till `roslynildiff`) but I get the warnings above.

I have changed it now to move some parts to `WasmApp.InTree*`, and others into the project file itself: https://github.com/radical/runtime/tree/mbr-use-json-deltas

Does that look better? There is still some duplication, but I will continue improving that. I have an open PR for similar stuff - https://github.com/dotnet/runtime/pull/46958. I will update the uses here too, when I update wasm targets.

**Comment by lambdageek** [comment]
@radical mind taking another look? I picked up the changes from your tree, rebased on master to pickup  #46958 and changed my Makefile to use the PROJECT_NAME and run-browser stuff.  I verified that the browser sample works for me.  I think it looks pretty good now.  thanks for refactoring the Directory.Build.stuff

**Review by radical — APPROVED** [review]

**Pull request merged**
