### PR TITLE
Revisiting nullable annotations on caching

### PR DESCRIPTION
**Pull request by maryamariyan**
This PR fixes some mismatches between nullability of the arguments between ref and src

### CODE REVIEW

**Comment by maryamariyan** [comment]
Updated this PR, some of the changes were already addressed in https://github.com/dotnet/runtime/pull/65804

**Comment by tarekgh** [comment]
@maryamariyan I am seeing this PR changes almost no-op. am I missing anything here?

**Comment by maryamariyan** [comment]
PR is ready for review. 

@tarekgh aside from changes requested by @eerhardt in https://github.com/dotnet/runtime/pull/65775 I am also fixing the placement of `Clear` in caching ref file, as dictated via `GenerateReferenceAssemblySource` target.

**Review by eerhardt — APPROVED** [review]
LGTM. Thanks!

**Review by maxkoshevoi — APPROVED** [review]
LGTM

**Pull request merged**
