### PR TITLE
[WIP] System.Linq.Expressions.Interpreter.CallInstruction.CanCreateArbitraryDelegates should respect IsDynamicCodeSupported

### PR DESCRIPTION
**Pull request by ivanpovazan**
This PR is marked as draft as its sole purpose is to test potential issues with the change.

The work reflects what @MichalStrehovsky noted regarding adaptations of `Linq.Expressions` to be AOT compilation friendly: https://github.com/dotnet/runtime/issues/69410#issuecomment-1149334036 and the suggested way of enabling the mentioned codepath proposed by @rolfbjarne

### CODE REVIEW

**Comment by ivanpovazan** [comment]
Rerun the pipelines once: https://github.com/dotnet/runtime/pull/86971 gets merged in

**Comment by ivanpovazan** [comment]
The failures seem unrelated.

@MichalStrehovsky would it make sense to add a unit test for NativeAOT/MonoAOT which verifies that:
`CanCreateArbitraryDelegates=false`

Maybe something like:
```c#
var linqExprAssembly = typeof(System.Linq.Expressions.Expression).Assembly;
var callInstrType = linqExprAssembly?.GetType("System.Linq.Expressions.Interpreter.CallInstruction");
var canCreateArbitraryDelegatesGetter = callInstrType?.GetMethod("get_CanCreateArbitraryDelegates", BindingFlags.NonPublic | BindingFlags.Static);
Assert.False(canCreateArbitraryDelegatesGetter?.Invoke(null, null));
```

**Comment by MichalStrehovsky** [comment]
> The failures seem unrelated.
> 
> @MichalStrehovsky would it make sense to add a unit test for NativeAOT/MonoAOT which verifies that: `CanCreateArbitraryDelegates=false`
> 
> Maybe something like:
> 
> ```cs
> var linqExprAssembly = typeof(System.Linq.Expressions.Expression).Assembly;
> var callInstrType = linqExprAssembly?.GetType("System.Linq.Expressions.Interpreter.CallInstruction");
> var canCreateArbitraryDelegatesGetter = callInstrType?.GetMethod("get_CanCreateArbitraryDelegates", BindingFlags.NonPublic | BindingFlags.Static);
> Assert.False(canCreateArbitraryDelegatesGetter?.Invoke(null, null));
> ```

I don't have an opinion. The value of this switch affects runtime throughput and size. We should be able to observe this in size/throughput testing.

**Comment by eerhardt** [comment]
FYI - note the snags that I hit in this area in https://github.com/dotnet/runtime/issues/81803#issuecomment-1454200820.

**Pull request closed without merging**
