### PR TITLE
CI matrix change: add Windows.Server.Core.20H2 - Second attempt

### PR DESCRIPTION
**Pull request by aik-jahoda**
The original CI matrix change was reverted (#60040) because of a docker issue:

```
Unable to pull image mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-20H2-helix-amd64-20210922171304-edc3733
Exit Code:-4
```

This is attempt to investigate and re-revert it back.

https://dev.azure.com/dnceng/public/_build/results?buildId=1405926&view=results

part of #59572

### CODE REVIEW

**Comment by aik-jahoda** [comment]
@krwq , I try fix the docker issue. We all all green, can we trigger rolling builds on this PR?

**Comment by krwq** [comment]
you will need to push your branch to dotnet, i.e.:
`git push origin cimatrix20h2:cimatrix20h2`
then go to https://dev.azure.com/dnceng/public/_build?definitionId=686&_a=summary and click `Run pipeline` and choose your branch name

**Comment by aik-jahoda** [comment]
Latest commit is passing in runtime CI: https://github.com/dotnet/runtime/commit/febb494edd5e7ea506cd749639363c545082621a

**Review by danmoseley — APPROVED** [review]
if it works..

**Comment by ericstj** [comment]
This PR introduced regressions https://github.com/dotnet/runtime/issues/62205 and is being reverted in https://github.com/dotnet/runtime/pull/62253#event-5702625828

**Pull request merged**
