### PR TITLE
[Http/SslStress] Update linux container centos-stream9

### LINKED ISSUE #105560: HTTP/SSL stress Linux builds broken by PGO update
#105236 contains a PGO update that broke our stress builds on Linux.

```
  [ 63%] Built target cee_wks_core
  make: *** [Makefile:156: all] Error 2
  /repo/src/coreclr
##[error]Failed to build "CoreCLR component".
/repo/src/coreclr/runtime.proj(108,5): error MSB3073: The command ""/repo/src/coreclr/build-runtime.sh" -x64 -release -ci -os linux -pgodatapath "/repo/.packages/optimization.linux-x64.pgo.coreclr/1.0.0-prerelease.24369.3" -outputrid linux-x64 -cmakeargs "-DCLR_DOTNET_HOST_PATH=/repo/.dotnet/dotnet" -cmakeargs "-DCDAC_BUILD_TOOL_BINARY_PATH=/repo/artifacts/bin/coreclr/linux.x64.Release/cdac-build-tool/cdac-build-tool.dll"" exited with code 2.
##[error]/repo/src/coreclr/runtime.proj(108,5): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Build) The command ""/repo/src/coreclr/build-runtime.sh" -x64 -release -ci -os linux -pgodatapath "/repo/.packages/optimization.linux-x64.pgo.coreclr/1.0.0-prerelease.24369.3" -outputrid linux-x64 -cmakeargs "-DCLR_DOTNET_HOST_PATH=/repo/.dotnet/dotnet" -cmakeargs "-DCDAC_BUILD_TOOL_BINARY_PATH=/repo/artifacts/bin/coreclr/linux.x64.Release/cdac-build-tool/cdac-build-tool.dll"" exited with code 2.

Build FAILED.

```

Example build:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=755072&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=ebe1360c-fe50-5ebc-628a-48ef9bf66506&l=3028

### PR DESCRIPTION
**Pull request by antonfirsov**
This should bump the clang version and fix #105560.

### CODE REVIEW

**Review by rzikm — APPROVED** [review]
LGTM, thanks!

**Comment by antonfirsov** [comment]
This should bump clang version and fix #105560

**Pull request merged**
