### PR TITLE
JIT: optimize non-constant stackalloc to constant

### PR DESCRIPTION
**Pull request by EgorBo**
This PR optimizes 
```
span = x <= 64 ? stackalloc byte[n] : ...
```
to
```
span = x <= 64 ? stackalloc byte[64] : ...
```
because the latter is faster to zero (single instruction). Although, this consumes more stack, so the threshold is low.

Also, I need the generic `optAssertionProp_GetInt32Range` function in future opts I wanted to try.

Example:
```cs
static void Test(int n)
{
    Span<byte> span = (uint)n <= 64 ? stackalloc byte[n] : new byte[n];
    Consume(span);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void Consume(Span<byte> span){}
```

Codegen diff for `Test()`: https://www.diffchecker.com/s6pIRCSa/

### CODE REVIEW

**Comment by stephentoub** [comment]
> span = x <= 64 ? stackalloc byte[n] : ...
> to
> span = x <= 64 ? stackalloc byte[64] : ...

Does it slice it as well?  Otherwise, that's a visible change that's almost guaranteed to break code that depended on span.Length being n rather than 64.

**Comment by EgorBo** [comment]
> > span = x <= 64 ? stackalloc byte[n] : ...
> > to
> > span = x <= 64 ? stackalloc byte[64] : ...
> 
> Does it slice it as well? Otherwise, that's a visible change that's almost guaranteed to break code that depended on span.Length being n rather than 64.

Right, it doesn't change that behaviour, my example is not entirely correct from C# point of view, but it gives the idea of what JIT does for it.

**Comment by EgorBo** [comment]
Also. This PR closes https://github.com/dotnet/runtime/issues/81160 (although, I didn't plan it)

**Comment by EgorBo** [comment]
> What is the escape hatch for a user that truly wants to allocate as little stack as possible? In general I think we should be careful around changing stack consumption for patterns like this unless we have good evidence of benefits to motivate it (stack consumption vs execution speed is, as you say, a tradeoff)...

This just a draft to see the diffs. I wrote this function for a different opt, just noticed that it's a few lines of code to apply it for LCLHEAP. I don't have an answer on what threshold is safe to use to potentially increase stack usage for better perf.

**Comment by EgorBo** [comment]
Closing since I am not feeling confident enough to increase stack consumption in such functions.
I'll move my other changes to a separate PR and leave this as a history record

**Pull request closed without merging**
