### PR TITLE
Remove trailing comma from System.Private.Xml

### PR DESCRIPTION
**Pull request by kronic**

### CODE REVIEW

**Comment by krwq** [comment]
What's wrong with the trailing comma? It produces less diff when someone adds new value/removes values

**Review by krwq — COMMENTED** [review]
What's wrong with trailing commas?

**Comment by stephentoub** [comment]
I agree with @krwq.  We don't have a style that dictates one way or the other, and there are legitimate reasons to want to use a trailing comma.

**Comment by kronic** [comment]
@krwq, @stephentoub Why do we need a comma at the end. What meaning does it carry, except for garbage?

**Comment by stephentoub** [comment]
It lets you add another line without modifying an existing one, which helps keep history and diffs cleaner.

**Comment by kronic** [comment]
@stephentoub Why, then, are they not everywhere? I think there must be uniformity.

**Comment by kronic** [comment]
I think the lack of rules on this matter is a mistake in the rules.

**Comment by kronic** [comment]
I can change this pr to the opposite or close. Is it your choice?

**Comment by krwq** [comment]
+ @bartonjs for coding guidelines

**Comment by stephentoub** [comment]
> I can change this pr to the opposite or close. Is it your choice?

Let's close it.  Thanks.

**Comment by krwq** [comment]
Thanks @kronic - note I appreciate most of the refactoring changes you're doing but this particular one I don't agree with

**Comment by kronic** [comment]
@krwq I agree with the argument @Stephentoub. I don't like that there are no coding rules in this.

**Pull request closed without merging**
