### PR TITLE
Disable some Speech tests on Server Core

### PR DESCRIPTION
**Pull request by danmoseley**

### CODE REVIEW

**Comment by danmosemsft** [comment]
@safern just curious is there a way to run Server Core (or Nano) tests in CI?

**Comment by safern** [comment]
>@safern just curious is there a way to run Server Core (or Nano) tests in CI?

Nano tests run in CI by default. Server Core, not yet, you would need to manually trigger a CI build from the AzDo page using your pull request ref. 

Server Core the plan is to get them to run on CI by default but we don't have enough capacity yet.

**Review by safern — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Comment by danmosemsft** [comment]
Not sure why automerge isn't working.

**Comment by danmosemsft** [comment]
Fixes #46800

**Pull request merged**
