### PR TITLE
Enable more iOS/tvOS device tests

### PR DESCRIPTION
**Pull request by steveisok**
Add a few more suites to help validate the device infrastructure

### CODE REVIEW

**Review by marek-safar — APPROVED** [review]

**Comment by akoeplinger** [comment]
Looks good but there are a bunch of test failures due to `DebuggerDisplayAttribute` missing on iOS, presumably related to aggressive trimming.

Also I think @premun wanted these additional workitems for tvOS too, not just iOS.

**Comment by premun** [comment]
Yes, tvOS too, thanks!

To be honest I look at tvOS these days way more as we have ~50 devices in one queue and ~50 in the other so it seems as a more viable option for future testing as opposed to the 10 iPhones.

**Comment by steveisok** [comment]
@akoeplinger Looks like an ILStrip issue in the failure.

**Comment by ViktorHofer** [comment]
We are already hitting timeouts in the Apple runtime-staging legs in many PRs which is tracked via https://github.com/dotnet/runtime/issues/58549. Shouldn't we first mitigate the existing issues to unblock PRs which are red because of the timeouts instead of adding more tests?

cc @marek-safar @jeffkl and @danmoseley as we just recently talked about this in the M2 sync.

**Comment by premun** [comment]
@ViktorHofer the currently running tests are simulators only. This PR enables more tests for **real devices** where we don't run almost any tests yet.
We run 1 test suite per main build only. This PR makes it 5 suites per PR build.

**Comment by akoeplinger** [comment]
Yeah this will not impact the other runtime-staging issue.

**Comment by ViktorHofer** [comment]
Got it, thanks for the clarification. Sounds like we are in agreement to not pile on top of the existing issue.

**Comment by steveisok** [comment]
Failures are unrelated

**Pull request merged**
