### PR TITLE
JIT: Fix handling of filter successors

### LINKED ISSUE #86538: JIT: Audit `GetAllSuccs`/`GetEHSuccs` when filters are involved
Liveness has special logic to take into account that control may flow from filters to practically any enclosed or enclosing handler. However, `GetAllSuccs` does not seem to have the same handling.

For:
```csharp
public class Program
{
    public static bool IsExpectedException(Exception e)
    {
        Console.WriteLine("In filter");
        return false;
    }
    
    public static int Main()
    {
        int result = 0;
        // BB01

        try
        {
            // BB02
            try
            {
                // BB03
                try
                {
                    // BB04
                    throw new Exception();
                }
                finally
                {
                    // BB05
                    Console.WriteLine("In finally");
                }
            }
            catch (Exception e1 /* BB06, BB07 */) when (/* BB08 */ IsExpectedException(e1) /* BB09 */)
            {
                // BB10
                Console.WriteLine("In catch 1");
            }
            // BB11
        }
        catch (Exception e2)
        {
            // BB12
            Console.WriteLine("In catch 2");
            result = 100;
        }

        // BB13
        return result;
    }
}
```

`GetAllSuccs` returns the following:
```scala
BB01
  Succ BB02
  Succ BB12
BB02
  Succ BB03
  Succ BB12
  Succ BB06
BB03
  Succ BB04
  Succ BB06
  Succ BB12
  Succ BB05
BB04
  Succ BB05
  Succ BB06
  Succ BB12
BB05
  Succ BB06
  Succ BB12
BB06
  Succ BB07
  Succ BB08
  Succ BB12
BB07
  Succ BB09
  Succ BB12
BB08
  Succ BB09
  Succ BB12
BB09
  Succ BB10
  Succ BB12
BB10
  Succ BB11
  Succ BB12
BB11
  Succ BB13
  Succ BB12
BB12
  Succ BB13
BB13
```

In particular I would expect the successors to indicate that the finally block `BB05` is reachable from the filter blocks `BB06` to `BB09`.

### LINKED ISSUE #88168: [jitstress] GC hole in libraries test with JitStress=2
Looking at this failure: https://dev.azure.com/dnceng-public/public/_build/results?buildId=323067&view=ms.vss-test-web.build-test-results-tab&runId=6640628&resultId=201899&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab
Console log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-88090-merge-db22b0df4ffd4c4bae/System.Runtime.Serialization.Xml.Tests/1/console.c66fcf9f.log?helixlogtype=result

```
C:\h\w\C0A909A9\w\A6330968\e>set DOTNET 
DOTNET_JitStress=2
DOTNET_TieredCompilation=0

C:\h\w\C0A909A9\w\A6330968\e>call RunTests.cmd --runtime-path C:\h\w\C0A909A9\p 
----- start Wed 06/28/2023  5:16:38.33 ===============  To repro directly: =====================================================
pushd C:\h\w\C0A909A9\w\A6330968\e\
"C:\h\w\C0A909A9\p\dotnet.exe" exec --runtimeconfig System.Runtime.Serialization.Xml.Tests.runtimeconfig.json --depsfile System.Runtime.Serialization.Xml.Tests.deps.json xunit.console.dll System.Runtime.Serialization.Xml.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\C0A909A9\w\A6330968\e>"C:\h\w\C0A909A9\p\dotnet.exe" exec --runtimeconfig System.Runtime.Serialization.Xml.Tests.runtimeconfig.json --depsfile System.Runtime.Serialization.Xml.Tests.deps.json xunit.console.dll System.Runtime.Serialization.Xml.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Runtime.Serialization.Xml.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Serialization.Xml.Tests (found 279 of 280 test cases)
  Starting:    System.Runtime.Serialization.Xml.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 904 [0x00000388], Thread: 1924 [0x0784]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

CORECLR! GetCLRRuntimeHost + 0xEE190 (0x72415e80)
CORECLR! GetCLRRuntimeHost + 0xEDC38 (0x72415928)
CORECLR! GetCLRRuntimeHost + 0xE97F6 (0x724114e6)
CORECLR! GetCLRRuntimeHost + 0x173CB1 (0x7249b9a1)
CORECLR! GetCLRRuntimeHost + 0x173B6B (0x7249b85b)
<no module>! <no symbol> + 0x0 (0x0d748f93)
<no module>! <no symbol> + 0x0 (0x0d8dedbe)
<no module>! <no symbol> + 0x0 (0x0d748360)
<no module>! <no symbol> + 0x0 (0x0b4d1184)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x714dfc74)
    File: D:\a\_work\1\s\src\coreclr\vm\object.cpp Line: 600
    Image: C:\h\w\C0A909A9\p\dotnet.exe
```

Note that this is win-x86. It reproduces locally for me on every run with `DOTNET_TieredCompilation=0`, `DOTNET_JitStress=2` and `DOTNET_GCStress=c`.

### PR DESCRIPTION
**Pull request by jakobbotsch**
Filters are run during the first pass of EH which makes determining their successors complicated, and the JIT did not get this right.  In particular, after running filters as part of first-pass EH, control may flow to any enclosed finally or fault handler as part of second-pass EH. Thus, these should be considered as EH successors. This adds a BasicBlock::VisitEHSecondPassSuccs to visit these successors.

The logic was mostly extracted from liveness that (almost) got it right: there was a condition that meant the logic did not run for top-level try-filter clauses. This change folds in Bruce's change to fix this scenario as well.

There was one more bug in the logic in liveness: to determine the enclosed fault/finally blocks, the logic iterates backwards in the EH table while looking for enclosed clauses. However, this was only checking for clauses enclosed in the try region when it should also check for clauses enclosed in the handler region.

Fix #86538
Fix #88168

### CODE REVIEW

**Comment by jakobbotsch** [comment]
There is still a TP regression for linux. The detailed stats look like:
```scala
Base: 57696352942, Diff: 57808766749, +0.1948%

BasicBlockVisit VisitEHSuccessors<LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)::'lambda'(BasicBlock*)>(Compiler*, BasicBlock*, LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)::'lambda'(BasicBlock*))     : 114296864 : NA       : 22.04% : +0.1981%
Compiler::fgAddHandlerLiveVars(BasicBlock*, unsigned long*&)                                                                                                                                                                        : 45110935  : NA       : 8.70%  : +0.0782%
BasicBlockVisit VisitEHSuccessors<Compiler::optReachable(BasicBlock*, BasicBlock*, BasicBlock*)::$_0>(Compiler*, BasicBlock*, Compiler::optReachable(BasicBlock*, BasicBlock*, BasicBlock*)::$_0)                                   : 33963609  : NA       : 6.55%  : +0.0589%
BasicBlockVisit VisitEHSuccessors<SsaBuilder::AddPhiArgsToSuccessors(BasicBlock*)::$_1>(Compiler*, BasicBlock*, SsaBuilder::AddPhiArgsToSuccessors(BasicBlock*)::$_1)                                                               : 16226626  : NA       : 3.13%  : +0.0281%
BasicBlockVisit VisitEHSuccessors<ValueNumberState::FinishVisit(BasicBlock*)::'lambda'(BasicBlock*)>(Compiler*, BasicBlock*, ValueNumberState::FinishVisit(BasicBlock*)::'lambda'(BasicBlock*))                                     : 15772530  : NA       : 3.04%  : +0.0273%
BasicBlockVisit VisitEHSuccessors<void DataFlow::ForwardAnalysis<AssertionPropFlowCallback>(AssertionPropFlowCallback&)::'lambda'(BasicBlock*)>(Compiler*, BasicBlock*, AssertionPropFlowCallback)                                  : 15625325  : NA       : 3.01%  : +0.0271%
BasicBlockVisit VisitEHSuccessors<AllSuccessorEnumerator::AllSuccessorEnumerator(Compiler*, BasicBlock*)::$_0>(Compiler*, BasicBlock*, AllSuccessorEnumerator::AllSuccessorEnumerator(Compiler*, BasicBlock*)::$_0)                 : 14836539  : NA       : 2.86%  : +0.0257%
BasicBlockVisit VisitEHSuccessors<void DataFlow::ForwardAnalysis<CSE_DataFlow>(CSE_DataFlow&)::'lambda'(BasicBlock*)>(Compiler*, BasicBlock*, CSE_DataFlow)                                                                         : 11960412  : NA       : 2.31%  : +0.0207%
BasicBlockVisit BasicBlock::VisitEHSecondPassSuccs<LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)::'lambda'(BasicBlock*)>(Compiler*, LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)::'lambda'(BasicBlock*)) : 10856173  : NA       : 2.09%  : +0.0188%
BasicBlockVisit VisitEHSuccessors<PromotionLiveness::PerBlockLiveness(BasicBlock*)::$_0>(Compiler*, BasicBlock*, PromotionLiveness::PerBlockLiveness(BasicBlock*)::$_0)                                                             : 5703223   : NA       : 1.10%  : +0.0099%
Compiler::bbInFilterBBRange(BasicBlock*)                                                                                                                                                                                            : 5138265   : NA       : 0.99%  : +0.0089%
BasicBlockVisit VisitEHSuccessors<void LinearScan::buildIntervals<true>()::'lambda'(BasicBlock*)>(Compiler*, BasicBlock*, true)                                                                                                     : 4811984   : NA       : 0.93%  : +0.0083%
Compiler::BlockPredsWithEH(BasicBlock*)                                                                                                                                                                                             : 4334425   : +2.56%   : 0.84%  : +0.0075%
LiveVarAnalysis::LiveVarAnalysis(Compiler*)                                                                                                                                                                                         : 3271145   : NA       : 0.63%  : +0.0057%
BasicBlockVisit BasicBlock::VisitAllSuccs<LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)::'lambda'(BasicBlock*)>(Compiler*, LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)::'lambda'(BasicBlock*))          : 2790940   : +0.82%   : 0.54%  : +0.0048%
EHblkDsc::InFilterRegionBBRange(BasicBlock*)                                                                                                                                                                                        : 2203961   : +856.34% : 0.42%  : +0.0038%
BasicBlockVisit BasicBlock::VisitEHSecondPassSuccs<void DataFlow::ForwardAnalysis<AssertionPropFlowCallback>(AssertionPropFlowCallback&)::'lambda'(BasicBlock*)>(Compiler*, AssertionPropFlowCallback)                              : 1318125   : NA       : 0.25%  : +0.0023%
BasicBlockVisit BasicBlock::VisitAllSuccs<void LinearScan::buildIntervals<true>()::'lambda'(BasicBlock*)>(Compiler*, true)                                                                                                          : 1210747   : +4.75%   : 0.23%  : +0.0021%
SsaBuilder::AddPhiArg(BasicBlock*, Statement*, GenTreePhi*, unsigned int, unsigned int, BasicBlock*)                                                                                                                                : 1204341   : +3.19%   : 0.23%  : +0.0021%
BasicBlockVisit BasicBlock::VisitEHSecondPassSuccs<void DataFlow::ForwardAnalysis<CSE_DataFlow>(CSE_DataFlow&)::'lambda'(BasicBlock*)>(Compiler*, CSE_DataFlow)                                                                     : 1061830   : NA       : 0.20%  : +0.0018%
BasicBlockVisit BasicBlock::VisitEHSecondPassSuccs<ValueNumberState::FinishVisit(BasicBlock*)::'lambda'(BasicBlock*)>(Compiler*, ValueNumberState::FinishVisit(BasicBlock*)::'lambda'(BasicBlock*))                                 : 1043750   : NA       : 0.20%  : +0.0018%
BasicBlockVisit BasicBlock::VisitAllSuccs<void DataFlow::ForwardAnalysis<AssertionPropFlowCallback>(AssertionPropFlowCallback&)::'lambda'(BasicBlock*)>(Compiler*, AssertionPropFlowCallback)                                       : 650373    : +1.57%   : 0.13%  : +0.0011%
AllSuccessorEnumerator::AllSuccessorEnumerator(Compiler*, BasicBlock*)                                                                                                                                                              : -594474   : -2.03%   : 0.11%  : -0.0010%
PromotionLiveness::PerBlockLiveness(BasicBlock*)                                                                                                                                                                                    : -690959   : -3.24%   : 0.13%  : -0.0012%
Compiler::fgLiveVarAnalysis(bool)                                                                                                                                                                                                   : -4197657  : -100.00% : 0.81%  : -0.0073%
Compiler::fgInterBlockLocalVarLiveness()                                                                                                                                                                                            : -5039714  : -1.68%   : 0.97%  : -0.0087%
LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)                                                                                                                                                                          : -5349213  : -1.03%   : 1.03%  : -0.0093%
Compiler::optReachable(BasicBlock*, BasicBlock*, BasicBlock*)                                                                                                                                                                       : -5955380  : -8.63%   : 1.15%  : -0.0103%
Compiler::fgGetHandlerLiveVars(BasicBlock*)                                                                                                                                                                                         : -48197118 : -100.00% : 9.29%  : -0.0835%
Compiler::ehBlockHasExnFlowDsc(BasicBlock*)                                                                                                                                                                                         : -56110722 : -72.16%  : 10.82% : -0.0973%
Compiler::ehGetBlockExnFlowDsc(BasicBlock*)                                                                                                                                                                                         : -76371220 : -72.81%  : 14.73% : -0.1324%
```
(future note to self: need to unstrip libclrjit.so (or presumably just pass -keepnativesymbols) to get it to work).

When looking closer, clang is fully inlining `VisitEHSuccessors` into `VisitAllSuccs` before this change, while it stops doing this inlining now that `VisitEHSuccessors` becomes more complicated. I'll see if I can shape the code so it can at least inline the `HasPotentialEHSuccs` check, but overall this is the kind of thing I would expect native PGO to improve once we get updated data.

**Comment by jakobbotsch** [comment]
If I manually add checks for `HasPotentialEHSuccs` before all the calls to `VisitEHSuccessors` then the detailed stats look like:
```scala
Base: 57696352942, Diff: 57670826699, -0.0442%

BasicBlockVisit VisitEHSuccessors<LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)::'lambda'(BasicBlock*)>(Compiler*, BasicBlock*, LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)::'lambda'(BasicBlock*))     : 47713859  : NA       : 12.25% : +0.0827%
Compiler::fgAddHandlerLiveVars(BasicBlock*, unsigned long*&)                                                                                                                                                                        : 45110935  : NA       : 11.58% : +0.0782%
BasicBlockVisit BasicBlock::VisitEHSecondPassSuccs<LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)::'lambda'(BasicBlock*)>(Compiler*, LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)::'lambda'(BasicBlock*)) : 24743137  : NA       : 6.35%  : +0.0429%
BasicBlockVisit VisitEHSuccessors<Compiler::optReachable(BasicBlock*, BasicBlock*, BasicBlock*)::$_0>(Compiler*, BasicBlock*, Compiler::optReachable(BasicBlock*, BasicBlock*, BasicBlock*)::$_0)                                   : 13075204  : NA       : 3.36%  : +0.0227%
BasicBlockVisit VisitEHSuccessors<void DataFlow::ForwardAnalysis<AssertionPropFlowCallback>(AssertionPropFlowCallback&)::'lambda'(BasicBlock*)>(Compiler*, BasicBlock*, AssertionPropFlowCallback)                                  : 5267582   : NA       : 1.35%  : +0.0091%
Compiler::bbInFilterBBRange(BasicBlock*)                                                                                                                                                                                            : 5138265   : NA       : 1.32%  : +0.0089%
BasicBlockVisit VisitEHSuccessors<SsaBuilder::AddPhiArgsToSuccessors(BasicBlock*)::$_1>(Compiler*, BasicBlock*, SsaBuilder::AddPhiArgsToSuccessors(BasicBlock*)::$_1)                                                               : 4638729   : NA       : 1.19%  : +0.0080%
Compiler::BlockPredsWithEH(BasicBlock*)                                                                                                                                                                                             : 4334425   : +2.56%   : 1.11%  : +0.0075%
BasicBlockVisit VisitEHSuccessors<void DataFlow::ForwardAnalysis<CSE_DataFlow>(CSE_DataFlow&)::'lambda'(BasicBlock*)>(Compiler*, BasicBlock*, CSE_DataFlow)                                                                         : 4217076   : NA       : 1.08%  : +0.0073%
BasicBlockVisit VisitEHSuccessors<AllSuccessorEnumerator::AllSuccessorEnumerator(Compiler*, BasicBlock*)::$_0>(Compiler*, BasicBlock*, AllSuccessorEnumerator::AllSuccessorEnumerator(Compiler*, BasicBlock*)::$_0)                 : 4129431   : NA       : 1.06%  : +0.0072%
BasicBlockVisit BasicBlock::VisitEHSecondPassSuccs<void DataFlow::ForwardAnalysis<AssertionPropFlowCallback>(AssertionPropFlowCallback&)::'lambda'(BasicBlock*)>(Compiler*, AssertionPropFlowCallback)                              : 3784453   : NA       : 0.97%  : +0.0066%
LiveVarAnalysis::LiveVarAnalysis(Compiler*)                                                                                                                                                                                         : 3271145   : NA       : 0.84%  : +0.0057%
BasicBlockVisit BasicBlock::VisitEHSecondPassSuccs<void DataFlow::ForwardAnalysis<CSE_DataFlow>(CSE_DataFlow&)::'lambda'(BasicBlock*)>(Compiler*, CSE_DataFlow)                                                                     : 3003646   : NA       : 0.77%  : +0.0052%
BasicBlockVisit BasicBlock::VisitEHSecondPassSuccs<ValueNumberState::FinishVisit(BasicBlock*)::'lambda'(BasicBlock*)>(Compiler*, ValueNumberState::FinishVisit(BasicBlock*)::'lambda'(BasicBlock*))                                 : 2965178   : NA       : 0.76%  : +0.0051%
BasicBlockVisit VisitEHSuccessors<PromotionLiveness::PerBlockLiveness(BasicBlock*)::$_0>(Compiler*, BasicBlock*, PromotionLiveness::PerBlockLiveness(BasicBlock*)::$_0)                                                             : 2321743   : NA       : 0.60%  : +0.0040%
EHblkDsc::InFilterRegionBBRange(BasicBlock*)                                                                                                                                                                                        : 2181918   : +847.77% : 0.56%  : +0.0038%
BasicBlockVisit VisitEHSuccessors<void LinearScan::buildIntervals<true>()::'lambda'(BasicBlock*)>(Compiler*, BasicBlock*, true)                                                                                                     : 1656054   : NA       : 0.43%  : +0.0029%
SsaBuilder::AddPhiArg(BasicBlock*, Statement*, GenTreePhi*, unsigned int, unsigned int, BasicBlock*)                                                                                                                                : 1204341   : +3.19%   : 0.31%  : +0.0021%
BasicBlockVisit BasicBlock::VisitEHSecondPassSuccs<void LinearScan::buildIntervals<true>()::'lambda'(BasicBlock*)>(Compiler*, true)                                                                                                 : 1154594   : NA       : 0.30%  : +0.0020%
BasicBlockVisit BasicBlock::VisitAllSuccs<void LinearScan::buildIntervals<true>()::'lambda'(BasicBlock*)>(Compiler*, true)                                                                                                          : 523034    : +2.05%   : 0.13%  : +0.0009%
SsaBuilder::AddPhiArgsToSuccessors(BasicBlock*)                                                                                                                                                                                     : -686946   : -2.38%   : 0.18%  : -0.0012%
PromotionLiveness::PerBlockLiveness(BasicBlock*)                                                                                                                                                                                    : -923898   : -4.33%   : 0.24%  : -0.0016%
BasicBlockVisit BasicBlock::VisitAllSuccs<void DataFlow::ForwardAnalysis<CSE_DataFlow>(CSE_DataFlow&)::'lambda'(BasicBlock*)>(Compiler*, CSE_DataFlow)                                                                              : -1107936  : -3.45%   : 0.28%  : -0.0019%
BasicBlockVisit BasicBlock::VisitAllSuccs<void DataFlow::ForwardAnalysis<AssertionPropFlowCallback>(AssertionPropFlowCallback&)::'lambda'(BasicBlock*)>(Compiler*, AssertionPropFlowCallback)                                       : -1369265  : -3.30%   : 0.35%  : -0.0024%
Compiler::fgLiveVarAnalysis(bool)                                                                                                                                                                                                   : -4197657  : -100.00% : 1.08%  : -0.0073%
Compiler::fgInterBlockLocalVarLiveness()                                                                                                                                                                                            : -5039714  : -1.68%   : 1.29%  : -0.0087%
LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)                                                                                                                                                                          : -5349213  : -1.03%   : 1.37%  : -0.0093%
Compiler::optReachable(BasicBlock*, BasicBlock*, BasicBlock*)                                                                                                                                                                       : -7533498  : -10.92%  : 1.93%  : -0.0131%
BasicBlockVisit BasicBlock::VisitAllSuccs<LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)::'lambda'(BasicBlock*)>(Compiler*, LiveVarAnalysis::PerBlockAnalysis(BasicBlock*, bool, bool)::'lambda'(BasicBlock*))          : -14544499 : -4.29%   : 3.73%  : -0.0252%
Compiler::fgGetHandlerLiveVars(BasicBlock*)                                                                                                                                                                                         : -48197118 : -100.00% : 12.37% : -0.0835%
Compiler::ehBlockHasExnFlowDsc(BasicBlock*)                                                                                                                                                                                         : -56110722 : -72.16%  : 14.40% : -0.0973%
Compiler::ehGetBlockExnFlowDsc(BasicBlock*)                                                                                                                                                                                         : -61886436 : -59.00%  : 15.89% : -0.1073%
```

However, I'm struggling to get clang to make these choices during inlining.

**Comment by jakobbotsch** [comment]
I think I'm going to leave this as is (with the small TP regression on Linux) -- I think there's an easier way to optimize liveness here -- I see no reason that we even need to visit all successors the way we are doing it from liveness. The successor-EH-successors should be unnecessary because they are already part of the live-in sets of the regular successors, so the fixpoint will take care of those. The normal EH successors are handled by `fgAddHandlerLiveVars`. That just leaves regular successors. So let me try to optimize this in a follow-up to ensure no diffs.

I ran stress jobs above; the failures were
* The new test failed on OSX x64 where we don't support GCStress. I disabled forced DOTNET_GCStress in https://github.com/dotnet/runtime/pull/89275/commits/75b67e81939d9e89d5dfae01533d13fb3300e835.
* #88618

cc @dotnet/jit-contrib PTAL @BruceForstall

**Review by BruceForstall — APPROVED** [review]
Nice!

LGTM

**Pull request merged**
