### PR TITLE
Add icon to dotnet.exe on Windows

### LINKED ISSUE #69372: Iconize executable
grafik
I noticed that the `dotnet.exe` unfortunately has no icon. I would like to see the .NET icon here, for example.
Of course, it's nothing critical but just a "nice-to-have" feature. But in my opinion it doesn't hurt either.

I don't find it nice to see a boring standard Windows icon there.

---

* [ ] Windows - #70578
* [ ] OSX
* [ ] possibly other systems

### PR DESCRIPTION
**Pull request by elinor-fung**
This is +44 kB for `dotnet.exe` on Windows.

Resolves https://github.com/dotnet/runtime/issues/69372

In file explorer:
image
image
image

In task manager:
image
image

cc @richlander

### CODE REVIEW

**Review by vitek-karas — APPROVED** [review]

**Review by agocke — APPROVED** [review]

**Review by richlander — APPROVED** [review]
Looks pretty!

**Review by deeprobin — APPROVED** [review]
LGTM

**Comment by danmoseley** [comment]
What was the reasoning for including so many resolutions, including 256x256? I believe this falls under 'toolbar icon' and [our recommendations for that ](https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons?redirectedfrom=MSDN) are 16x16, 24x24, 32x32 (unless there is newer guidance I didn't find). I don't think we should care about the scenario of viewing your install folder as huge icons.

dropping your 5 largest resolutions leaving just those 3 will make it much smaller.

**Comment by agocke** [comment]
Only including the smaller sizes sounds fine to me, but I want to clarify that I think this only changes the muxer (dotnet.exe) and not the host. I don't think we should provide any icon for the host -- that would be the user's responsibility.

**Comment by danmoseley** [comment]
You might also be able to change 32 bit to 24 bit color without any noticeable effect.

**Comment by danmoseley** [comment]
Dropping to the 3 recommended sizes, keeping 32 bit, changes impact from 44Kb to 8Kb.

**Comment by richlander** [comment]
Let's just go with this as is. This has zero effect on apps. We're talking about tens of k difference for the product install.

**Comment by elinor-fung** [comment]
> and therefore every app will be smaller too

As @agocke and @richlander said, this is only for `dotnet.exe`. It does not affect the executable produced for apps (`apphost`).

**Comment by deeprobin** [comment]
> Resolves https://github.com/dotnet/runtime/issues/69372

I think this does not resolve the whole issue. Imo we should also provide a icon for apple (OSX).
I was told that there is a .plist file for Apple where you can define an .icns.

**Comment by richlander** [comment]
Good point. This is what the situation looks like on macOS.

image

I'm not sure if any other icon use matters on macOS. Hey @davidortinau, what does `dotnet run` on macOS look like in terms of icons (like CMD-tab)?

I'd suggest we merge this PR as-is and then look at implementing Linux and macOS support in addition.

**Comment by deeprobin** [comment]
> I'd suggest we merge this PR as-is and then look at implementing Linux and macOS support in addition.

Yes that's fine imo, but be careful that the "resolves" description doesn't close the issue :D

**Comment by richlander** [comment]
Hey @omajid, do you have any suggestions on how to approach icons on (desktop) Linux?

**Comment by directhex** [comment]
I don’t think ELF supports an embedded icon you'd see in a file manager - apps usually ship with an icon file alongside, as an xpm or png

**Comment by directhex** [comment]
That said, I think an app can self identify its own icon during execution, that's what'll show up in apps like task managers & app switchers. I'm sure I remember doing that for Edge.

https://specifications.freedesktop.org/wm-spec/1.4/ar01s05.html

**Comment by richlander** [comment]
Thanks for the info. That's helpful. 

That seems a bit overkill for `dotnet`. I don't think we want it interacting with window messages. Seems more appropriate for a client app stack. Right?

**Comment by directhex** [comment]
I agree

**Comment by Bosch-Eli-Black** [comment]
I love the idea of this, but the ".NET" text in the icon file looks pretty blurry.

In the largest icon, it loos like the letters have semi-transparent stripes along their edges:
dotnet logo - large


For the smallest icon, the ".NET" text is pretty blurry, as though it was just scaled down from the larger version of the logo, instead of being hand drawn at the lower resolution:
dotnet logo - small

**Comment by deeprobin** [comment]
> For the smallest icon, the ".NET" text is pretty blurry. Was the text scaled down from the larger version of the logo, or was it redrawn at the lower resolution?
.NET blurry icon

This is most likely some scaling interpolation problem. Maybe you could try it with the interpolation turned off or "paint" the icon yourself in this low resolution.

On the other hand, I don't think these small sizes are too important.

**Comment by Bosch-Eli-Black** [comment]
@deeprobin Any thoughts on the large icon? 🙂  I would have expected the edges of the letters (except for the dot and the diagonal on the "N") to be 100% white.

**Comment by deeprobin** [comment]
> @deeprobin Any thoughts on the large icon? 🙂 I would have expected the edges of the letters (except for the dot and the diagonal on the "N") to be 100% white.

I'm a little surprised. I don't know why this is so (maybe also due to interpolation).
I know that in Adobe Illustrator you can export a vector graphic with a text optimization, maybe this was (not) used here.

**Comment by davidhosejr** [comment]
Thanks for the feedback, I created the .ICO file, just wanted to follow up regarding the .NET text in the attached icon size ramp, more specifically the semi-transparent pixel people have commented on. I tried my best to adjust the .NET text to read well at each size in the .ico file. I did this by adjusting the positioning of the .NET text on the pixel grid however we don’t and can’t adjust the kerning of individual letter vector paths as this is a branding no-no. In short, we can adjust the scale/size of the all the .NET text as one series of paths however we cannot move individual paths for each letter.
IconRamp_PixelPreview

**Comment by Bosch-Eli-Black** [comment]
Thanks for the reply, @davidhosejr! 🙂

I think the main issue is that antialiasing is turned on. My understanding is that, for icons, turning off antialiasing for vertical and horizontal lines generally increases readability.

Here's a comparison of the .NET logo at the smallest resolution with antialiasing turned on (top) and with it turned off (bottom):

dotnet icon - small

I think the bottom one, with no antialiasing, is more readable 🙂

(Side note: Are you working with font  files (`.otf`, `.ttf`) or with raw SVG's?)

**Comment by richlander** [comment]
We researched adding an icon for macOS, per https://github.com/dotnet/runtime/pull/70578#issuecomment-1152949038. We were not able to find a solution. It appears that the host would need to take a dependency on Cocoa APIs. We don't want to do that. It's a new level of complexity w/o much value. The Windows model works better for us since it is data-oriented (we don't have to do anything interesting).

**Comment by davidhosejr** [comment]
> Thanks for the reply, @davidhosejr! 🙂
> 
> I think the main issue is that antialiasing is turned on. My understanding is that, for icons, turning off antialiasing for vertical and horizontal lines generally increases readability.
> 

@Bosch-Eli-Black, thanks for your comment. I've optimized the smaller sizes in the icon size ramp for a crisper preview.

**Comment by richlander** [comment]
That looks significantly better @davidhosejr. Thanks!

**Comment by Bosch-Eli-Black** [comment]
Thanks, @davidhosejr! 🙂

**Comment by elinor-fung** [comment]
Thanks, all!

**Pull request merged**
