### PR TITLE
[NO-MERGE] Dummy PR to test PR benchmarks

### PR DESCRIPTION
**Pull request by CarnaViire**

### CODE REVIEW

**Comment by CarnaViire** [comment]
/benchmark microbenchmarks aspnet-perf-win runtime --variable filter="*SocketSendReceivePerfTest*"

**Comment by CarnaViire** [comment]
/benchmark microbenchmarks aspnet-perf-win runtime --variable filter=System.Memory*

**Comment by CarnaViire** [comment]
/benchmark microbenchmarks aspnet-perf-lin runtime --variable filter=*SocketSendReceivePerfTest*

**Comment by CarnaViire** [comment]
/benchmark microbenchmarks aspnet-perf-lin runtime --variable filter=*LinqBenchmarks*

**Comment by CarnaViire** [comment]
/benchmark microbenchmarks aspnet-perf-win runtime --variable filter=*SocketSendReceivePerfTest*

**Comment by CarnaViire** [comment]
/benchmark microbenchmarks aspnet-perf-win runtime --variable filter=System.Memory*

**Comment by CarnaViire** [comment]
/benchmark microbenchmarks aspnet-perf-win libs --variable filter=*LinqBenchmarks*

**Comment by CarnaViire** [comment]
/benchmark httpclient-kestrel-configured aspnet-perf-win libs

**Comment by MihaZupan** [comment]
> +0.46%

Nice improvement, :shipit: :)

**Comment by CarnaViire** [comment]
6:38 PM comment, 7:14 PM result --> 36 min run

8 min - initial bot reaction
5 min - git clone
19 min - build no.1
1.5min - benchmark no.1
2 min - build no.2 (but there were no code changes in this PR, so not fully representative)
1min - benchmark no.2 (first benchmark was longer possibly due to installing latest .net to agent)

CI run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2035524&view=logs&j=9ef21fd1-5d60-5fa4-f8b2-6dc79e173863&t=245c5015-ae8e-5bb0-ff34-6d6f59122374

**Comment by CarnaViire** [comment]
/benchmark httpclient-kestrel-configured aspnet-perf-win libs --variable httpVersion="3.0"

**Comment by CarnaViire** [comment]
/benchmark microbenchmarks aspnet-perf-win libs --variable filter=*LinqBenchmarks*

**Comment by CarnaViire** [comment]
git clone failure:

```
[STDERR] error: unable to create file src/tools/illink/test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/Inheritance.Interfaces.OnReferenceType.BaseProvidesInterfaceMemberTests.g.cs: Filename too long
[STDERR] error: unable to create file src/tools/illink/test/ILLink.RoslynAnalyzer.Tests/generated/ILLink.RoslynAnalyzer.Tests.Generator/ILLink.RoslynAnalyzer.Tests.TestCaseGenerator/Inheritance.Interfaces.OnReferenceType.NoKeptCtorButInterfaceNeededTests.g.cs: Filename too long
[STDERR] fatal: unable to checkout working tree
```

**Comment by karelz** [comment]
@CarnaViire can you turn it into Draft PR when you are back? Thanks!

**Pull request closed without merging**
