### PR TITLE
Add rules for changing InstructionSetDesc.txt

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
cc @tannergooding @MichalStrehovsky

**Review by tannergooding — APPROVED** [review]
LGTM.

It might be nice to just have https://github.com/dotnet/runtime/blob/0d5b3623852b2f0ec81721e486a68fb50e301571/src/coreclr/src/tools/Common/JitInterface/ThunkGenerator/Program.cs insert a new random Guid as part of the update.

**Comment by tannergooding** [comment]
Just confirming, some other change already updated the JIT/EE GUID, right?

**Comment by jkotas** [comment]
> Just confirming, some other change already updated the JIT/EE GUID, right?

I do not think so. @MichalStrehovsky tried to update RyuJIT in CoreRT repo last night (https://github.com/dotnet/corert/pull/8242) and it failed hard way, not with the nice JIT/EE interface needs an update error.

**Comment by tannergooding** [comment]
I'll get a change up in a new PR

**Pull request merged**
