### PR TITLE
Skip native composite ReadyToRun images as inputs to Crossgen2

### LINKED ISSUE #49247: Ignore composite images in Crossgen2 inputs
When Crossgen2 is asked to compile a folder that's already been compiled with Crossgen2 in composite mode, the compilation fails because the compiler finds the composite DLL and claims it uses unsupported managed C++. Crossgen2 should be able to recognize previously produced composite files and just skip them as inputs similar to what it does for native DLLs.

/cc @dotnet/crossgen-contrib

### LINKED ISSUE #60381: Test failure baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd
Run: [runtime-coreclr outerloop 20211013.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1418559&view=ms.vss-test-web.build-test-results-tab&runId=41086662&resultId=109958&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd

```
**Error message:**
```
Process terminated. Assertion failed.
Unexpected error code getting attributes 433 from path F:\Builds\5443\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\Binaries\Obj\CSharpCodeAnalysis\Release\Microsoft.CodeAnalysis.CSharp.pdb
at System.IO.FileSystem.FillAttributeInfo(String path, WIN32_FILE_ATTRIBUTE_DATA& data, Boolean returnErrorOnNotFound)
at System.IO.FileSystem.FileExists(String fullPath)
at System.IO.File.Exists(String path)
at ILCompiler.CompilerTypeSystemContext.OpenAssociatedSymbolFile(String peFilePath, PEReader peReader)
at ILCompiler.CompilerTypeSystemContext.AddModule(String filePath, String expectedSimpleName, Boolean useForBinding, ModuleData oldModuleData)
at ILCompiler.CompilerTypeSystemContext.GetOrAddModuleFromPath(String filePath, Boolean useForBinding)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)
Could Not Find D:\h\w\B7620A12\w\A5AD08D8\e\baseservices\TieredCompilation\BasicTestWithMcj\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\B7620A12\w\A5AD08D8\e\baseservices\TieredCompilation\BasicTestWithMcj\BasicTestWithMcj.dll.rsp
Activation Context creation failed. Error: 0x00000002
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'D:\h\w\B7620A12\w\A5AD08D8\e\baseservices\TieredCompilation\BasicTestWithMcj\r2r\BasicTestWithMcj.dll'. The system cannot find the file specified.
File name: 'D:\h\w\B7620A12\w\A5AD08D8\e\baseservices\TieredCompilation\BasicTestWithMcj\r2r\BasicTestWithMcj.dll'

Return code:      1
Raw output file:      D:\h\w\B7620A12\w\A5AD08D8\uploads\Reports\baseservices.TieredCompilation\BasicTestWithMcj\BasicTestWithMcj.output.txt
Raw output:
BEGIN EXECUTION
BasicTestWithMcj.dll
1 file(s) copied.
Response file: D:\h\w\B7620A12\w\A5AD08D8\e\baseservices\TieredCompilation\BasicTestWithMcj\BasicTestWithMcj.dll.rsp
D:\h\w\B7620A12\w\A5AD08D8\e\baseservices\TieredCompilation\BasicTestWithMcj\IL-CG2\BasicTestWithMcj.dll
-o:D:\h\w\B7620A12\w\A5AD08D8\e\baseservices\TieredCompilation\BasicTestWithMcj\BasicTestWithMcj.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\B7620A12\p\System..dll
-r:D:\h\w\B7620A12\p\Microsoft..dll
-r:D:\h\w\B7620A12\p\mscorlib.dll
-r:D:\h\w\B7620A12\p\netstandard.dll
-O
" "dotnet" "D:\h\w\B7620A12\p\crossgen2\crossgen2.dll" @"D:\h\w\B7620A12\w\A5AD08D8\e\baseservices\TieredCompilation\BasicTestWithMcj\BasicTestWithMcj.dll.rsp"   -r:D:\h\w\B7620A12\w\A5AD08D8\e\baseservices\TieredCompilation\BasicTestWithMcj\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\B7620A12\w\A5AD08D8\e\baseservices\TieredCompilation\BasicTestWithMcj\BasicTestWithMcj.dll
call RunBasicTestWithMcj.cmd --runCustomTest D:\h\w\B7620A12\w\A5AD08D8\e\baseservices\TieredCompilation\BasicTestWithMcj\ BasicTestWithMcj.dll
Collect profile without R2R, use profile without R2R
Collect profile with R2R, use profile with R2R
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B7620A12\p
D:\h\w\B7620A12\w\A5AD08D8\e\baseservices\TieredCompilation\BasicTestWithMcj\BasicTestWithMcj.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_TieredCompilation._BasicTestWithMcj_BasicTestWithMcj_._BasicTestWithMcj_BasicTestWithMcj_cmd()
```

### PR DESCRIPTION
**Pull request by trylek**
According to the issue #49247
a known pre-existing Crossgen2 bug is that it fails when presented
with the components of a previous Crossgen2 compilation in the
composite mode. This is because Crossgen2 lacks proper logic to
recognize the composite images and mistakes them for currently
unsupported managed C++ MSIL assemblies. This change adds the extra
check; I have also unified it between Crossgen2 and R2RDump.

Thanks

Tomas

Fixes: #49247
Fixes: #60381

### CODE REVIEW

**Review by jkoritzinsky — COMMENTED** [review]
This test uses crossgen2 directly in its custom scripting. I think we should mark this with CrossgenIncompatible in the project file.

**Review by jkoritzinsky — APPROVED** [review]
Ignore my last comment. We don't have a `CrossgenIncompatible` property similar to `GCStressIncompatible`. Using `issues.targets` is the right thing here.

**Comment by trylek** [comment]
@jkoritzinsky - well, we do have the property <code>CrossGenTest</code>, e.g. here:

https://github.com/dotnet/runtime/blob/a0824ba41098db9dd49fa5aa519c51788b09c5d0/src/tests/Loader/classloader/generics/Instantiation/Negative/abstract04.ilproj#L7

I do see that the test uses explicit CG2 invocation and I believe it should be trivial to convert it to use the standard test scripting logic akin to what we do e.g. in the test

https://github.com/dotnet/runtime/blob/main/src/tests/readytorun/crossgen2/crossgen2smoke.csproj

I still however find it weird how come the test only seems to fail in CG2 runs - or are you aware of instances where it fails in JITted outerloop runs?

Thanks

Tomas

**Comment by jkoritzinsky** [comment]
That's the name... I didn't realize it didn't follow the pattern of the rest. Either using that property or following a similar mechanism as the smoke test would be something I'd agree with.

**Comment by trylek** [comment]
Thanks Jeremy for your feedback. I have converted the test to our standard infra logic for running tests with forced CG2 execution. According to my local testing the test seems to be passing so for now I removed the issues.targets entry as I suspect the apparent failures may have been unintended side effects of the custom CG2 execution logic. For now I plan to close the issue assuming the PR test run finishes fine; we will reopen the issue if the test turns out to still fail in some situations.

**Review by jkoritzinsky — COMMENTED** [review]
I don't think your change has the same semantics as the old scripts. Can you take another look?

**Comment by trylek** [comment]
Thanks Jeremy, I have fixed the execution argument <code>--runCustomTest</code>, are you aware of any additional differences between the current test behavior and the simplified version using the stock CG2 compilation scripting?

**Comment by jkoritzinsky** [comment]
Yes, it looks like the test wants both the non-R2R and the R2R versions of the DLL. It wants has the R2R one in a separate R2R subfolder.

Additionally, it uses custom scripts to actually do the test run: https://github.com/dotnet/runtime/blob/main/src/tests/baseservices/TieredCompilation/RunBasicTestWithMcj.cmd

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Review by mangod9 — APPROVED** [review]

**Comment by trylek** [comment]
The assertion failure <code>op2->TypeIs(TYP_LONG)</code> is apparently known and tracked under https://github.com/dotnet/runtime/issues/60624, merging in.

**Pull request merged**
