### PR TITLE
Fix ArgumentNullException when using minimum json file

### LINKED ISSUE #41117: ArgumentNullException when using a minimal Json file with the JsonConfigurationProvider
### Description
Using a minimal Json file `{}`
with the JsonConfigurationProvider fails with:

```
System.ArgumentNullException : Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.SortedDictionary`2.set_Item(TKey key, TValue value)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.VisitElement(JsonElement element)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
```

This is because `_currentPath` will be null and try to set the `null` to null in the new code path.
https://github.com/dotnet/runtime/blob/a52f237fe7a9f61d480e95912dcf6c16525bbee7/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationFileParser.cs#L60

### Regression?
Yes, caused by https://github.com/dotnet/runtime/pull/40829

cc @maryamariyan 

This is blocking the Runtime -> AspNetCore dependency update. We can skip our failing tests to workaround, but ideally this will be fixed ASAP.

### PR DESCRIPTION
**Pull request by maryamariyan**
Fixes #41117 

cc: @BrennanConroy @alefranz

### CODE REVIEW

**Review by BrennanConroy — APPROVED** [review]

**Comment by alefranz** [comment]
ouch! sorry about that!

**Review by HaoK — APPROVED** [review]

**Comment by maryamariyan** [comment]
> ouch! sorry about that!

No worries. 
Thanks @BrennanConroy for reporting the regression.

**Comment by BrennanConroy** [comment]
Wasn't the original change in 6.0

**Pull request merged**
