### PR TITLE
[LoongArch64] Fix the clr build error on Alpine.

### PR DESCRIPTION
**Pull request by LuckyXu-HF**
[LoongArch64] Fix the clr build error on Alpine.
* Also apply https://github.com/libunwind/libunwind/pull/741

### CODE REVIEW

**Comment by LuckyXu-HF** [comment]
Hi @jkotas , do we have a chance to align the `./src/native/external/libunwind/src/loongarch64/getcontext.S` with `https://github.com/libunwind/libunwind/blob/master/src/loongarch64/getcontext.S`?
Because the `endina.h` is useless in `getcontext.S` for LA64.
Could you please give us some suggestions? Thank you very much.

**Comment by jkotas** [comment]
Add note "Apply https://github.com/libunwind/libunwind/pull/741" to https://github.com/dotnet/runtime/blob/main/src/native/external/libunwind-version.txt and delete the `#include <endian.h>`.

**Comment by LuckyXu-HF** [comment]
> Add note "Apply [libunwind/libunwind#741](https://github.com/libunwind/libunwind/pull/741)" to https://github.com/dotnet/runtime/blob/main/src/native/external/libunwind-version.txt and delete the `#include <endian.h>`.

Ok, Thanks very much, I will do this in this PR.

**Comment by LuckyXu-HF** [comment]
@shushanhf @jkotas Could you please review this PR?

**Review by jkotas — APPROVED** [review]
LGTM!

**Review by shushanhf — APPROVED** [review]
LGTM~
Thanks!

**Pull request merged**
