### PR TITLE
Preparation for JIT\Regression test merging - assembly/file renames

### PR DESCRIPTION
**Pull request by markples**
This is a collection of renames that can be merged independently of actual test merging.  It may be easier to look at each commit separately.  I have them collected here in order to just do one PR process, but I can split them if needed.  Automated changes were done with the ILTransform tool (started by @trylek, my version at https://github.com/markples/utils/tree/for-PR-dotnet-runtime-79489, commit 131b3764).

[[ILTransform -p] Rename projects due to project name suffixes or proj…](https://github.com/dotnet/runtime/pull/79489/commits/4c422099dd40170b0a9e591dd9cd9f9bb0110739) 

- Standardize project suffixes since _d, etc., are special cases for test merging but -dbg is not
- Rename a few tests where the project and IL files had CaSiNg differences

[[ILTransform -ilfile] Rename IL files and <Compile> Includes to match…](https://github.com/dotnet/runtime/pull/79489/commits/64c711e022057fda21259920d13809d4c6d92e7b)

- Rename IL files to match the .ilproj root name (which excludes suffixes such as _d)
- Update the project files to refer to the new filenames using $(MSBuildProjectName) except src/tests/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b323557 where the IL file doesn't have the suffix

[[ILTransform -m] Remove .module from IL files](https://github.com/dotnet/runtime/pull/79489/commits/82c6b68c2a531deecf17f7a775337ad7ad03bbb4)

- Remove all .module (including extern) lines from IL files

[[ILTransform -a] Update .assembly to match filename in IL files](https://github.com/dotnet/runtime/pull/79489/commits/a55516d8c55b8f335b90fb52f54711fee3afe777)

- Rename IL .assembly names to match their filenames
- Some lines were `.assembly foo // as "foo"` - remove those comments too

[[ILTransform -n -a -ilfile] Deduplicate project names and update IL f…](https://github.com/dotnet/runtime/pull/79489/commits/5379d5091acc6c45f073e42f1c9d3659bc71c862)

- Deduplicate project names across JIT/Regression
  - If a set of duplicates is simply one csproj and one ilproj, then add _il to the ilproj and leave the csproj alone
  - Otherwise append the difference in the closest different directory names.  For example:
    - V1-M11-Beta1/b40347/b40347.ilproj -> b40347_M11-Beta1.ilproj
    - V1-M12-Beta2/b40347/b40347.ilproj -> b40347_M12-Beta2.ilproj
  - However, avoid creating foo_foo.  For example:
    - V1-M12-Beta2/b51875/b51875.csproj -> <unchanged>
    - V1-M12-Beta2/b51875/Desktop/b51875.csproj -> b51875_Desktop.csproj
- Also rename IL files and .assembly names to match the new project names

[Fix assembly reference in test dev11_132534](https://github.com/dotnet/runtime/pull/79489/commits/2ef9045a4199a78b7fcfc1aa3b8923c09924780a)
[Fix assembly reference in test dev11_145295](https://github.com/dotnet/runtime/pull/79489/commits/6a6e58f45f5c39e50a98173c85683d640ab63329)

Handwritten fixes to for IL->C# assembly references that were broken by the renames.

### CODE REVIEW

**Comment by markples** [comment]
All failures are #79517

**Review by trylek — APPROVED** [review]
LGTM, thank you! I also love the way you modified the msbuild projects to refer to <code>$(MSBuildProjectName)</code> instead of the particular test IL name, that's exactly the type of maintenance cost reduction cleanup the infra is all about.

**Review by BruceForstall — APPROVED** [review]
LGTM

**Pull request merged**
