### PR TITLE
Fix NRE in EncodingProvider

### PR DESCRIPTION
**Pull request by SergeiPavlov**
Issue https://github.com/dotnet/runtime/issues/55233

Add provider into array copy `newProviders` instead of original array before assigning array copy to `s_providers`

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]
Thanks @SergeiPavlov for fixing this issue. LGTM.

**Comment by stephentoub** [comment]
Thanks for finding and fixing.  Could you add a test as well?

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
I pushed a commit with a test.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=55238) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=55238) before we can accept your contribution.<br/><br/>:x: SergeiPavlov [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=55238)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=55238) it.</sub>

**Pull request merged**
