### PR TITLE
[mono][jit] Fix an infinite loop in the abcrem pass.

### LINKED ISSUE #71592: Publish error with blazor .7 preview 5 and AOT
### Description

I get this error when I try to publish a wasm blazor app with .net 7 preview 5 and aot:
```
Exec:  "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.7.Sdk.win-x64\7.0.0-preview.5.22268.1\tools\bin\wasm-emscripten-finalize" -g --dyncalls-i64 D:\Userware\code\SISE.Riva-MyFork\sise.ria\sise.ria.area.laminacion\sise.laminacion.opensilver\OpenSilverApp\OpenSilverApp.Browser\obj\Release\net7.0\wasm\for-publish\dotnet.wasm -o D:\Userware\code\SISE.Riva-MyFork\sise.ria\sise.ria.area.laminacion\sise.laminacion.opensilver\OpenSilverApp\OpenSilverApp.Browser\obj\Release\net7.0\wasm\for-publish\dotnet.wasm --detect-features
emcc(0,0): Error : '"C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.7.Sdk.win-x64\7.0.0-preview.5.22268.1\tools\bin\wasm-emscripten-finalize" -g --dyncalls-i64 D:\Userware\code\SISE.Riva-MyFork\sise.ria\sise.ria.area.laminacion\sise.laminacion.opensilver\OpenSilverApp\OpenSilverApp.Browser\obj\Release\net7.0\wasm\for-publish\dotnet.wasm -o D:\Userware\code\SISE.Riva-MyFork\sise.ria\sise.ria.area.laminacion\sise.laminacion.opensilver\OpenSilverApp\OpenSilverApp.Browser\obj\Release\net7.0\wasm\for-publish\dotnet.wasm --detect-features' failed (returned 3221226505)
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0-preview.5.22301.12\Sdk\WasmApp.Native.targets(415,5): Error MSB3073: The command "emcc "@C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.0-preview.5.22301.12\runtimes\browser-wasm\native\src\emcc-default.rsp" "@C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\7.0.0-preview.5.22301.12\runtimes\browser-wasm\native\src\emcc-link.rsp" "@D:\Userware\code\SISE.Riva-MyFork\sise.ria\sise.ria.area.laminacion\sise.laminacion.opensilver\OpenSilverApp\OpenSilverApp.Browser\obj\Release\net7.0\wasm\for-publish\emcc-link.rsp"" exited with code 1.
                Done executing task "Exec" -- FAILED.
                Done building target "_WasmLinkDotNet" in project "OpenSilverApp.Browser.csproj" -- FAILED.
```
### Reproduction Steps

It builds fine in debug an release

### Expected behavior

should publish successfully 

### Actual behavior

publish fails with the mentioned error.

Please don't ask for binlog unless you let me know how to get one while publishing.
I tried this
msbuild OpenSilverApp.Browser.csproj -bl:msbuild.binlog -p:DeployOnBuild=true -p:publishprofile=release.aot7

and it doesn't publish, but here is the bin I get
[msbuild.zip](https://github.com/dotnet/runtime/files/9034617/msbuild.zip)

### Regression?

_No response_

### Known Workarounds

arch-wasm
area-build-mono

### Configuration

.net version : 7.0.100-preview.5.22307.18
Windows 10 , 64

### Other information

.NET SDK:
 Version:   7.0.100-preview.5.22307.18
 Commit:    bd8b088037

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.5.22307.18\

global.json file:
  Not found

Host:
  Version:      7.0.0-preview.5.22301.12
  Architecture: x64
  Commit:       425fedc0fb

.NET SDKs installed:
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.5.22307.18 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.5.22303.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.5.22301.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.5.22302.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/dotnet/runtime/issues/71592.

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
@vargaz can we add a test for this one? can you extract the loop from that OpenSilver thing?

Also this is worth backporting to 6.0, I think

**Comment by lewing** [comment]
Should we backport this to release/6.0?

**Comment by lambdageek** [comment]
> Should we backport this to release/6.0?

I think we should backport.

**Comment by vargaz** [comment]
Is it ok to add a test for this under tests/Regressions/coreclr ?

**Comment by lambdageek** [comment]
@vargaz I think `src/tests/JIT/Regression/JitBlue/Runtime_NNNNN/` (for example see https://github.com/dotnet/runtime/tree/main/src/tests/JIT/Regression/JitBlue/Runtime_72081)

**Comment by jakobbotsch** [comment]
@vargaz The test added here doesn't seem to build:
https://dev.azure.com/dnceng/public/_build/results?buildId=1892472&view=logs&j=db768a9e-3325-5ce3-2d52-896c40bee68a&t=59112ad9-fe58-56ee-6943-84df6f0e3f8e&l=8616

```scala
/__w/1/s/src/tests/JIT/Regression/JitBlue/Runtime_71592/test71592.cs(7,14): error CS0660: 'Test' defines operator == or operator != but does not override Object.Equals(object o)
```

**Pull request merged**
