### PR TITLE
WIP: Add library outerloop testing on Mono runtime

### LINKED ISSUE #24101: Add libraries outerloop runs running on Mono
We currently only run our outerloop tests on coreclr, we should add mono as well so that outerloop tests are tested on Mono.

cc @dotnet/runtime-infrastructure

### PR DESCRIPTION
**Pull request by trylek**
Fixes: https://github.com/dotnet/runtime/issues/24101

### CODE REVIEW

**Comment by safern** [comment]
@trylek I was already working on this and planning on adding a separate build pipeline for this because at the end mono will want to run different modes, i.e: https://github.com/dotnet/runtime/issues/41365

**Comment by trylek** [comment]
OK, I'll close the review then, thanks for letting me know.

**Comment by safern** [comment]
The reason why I thought having a different pipeline would be beneficial is because people might want to just run the outerloop tests against mono on a PR? 

@ViktorHofer thoughts on that?

**Comment by ViktorHofer** [comment]
that makes sense to me, also we could schedule it differently, right?

**Comment by safern** [comment]
> that makes sense to me, also we could schedule it differently, right?

Yeah, we could have different schedules for it.

**Pull request closed without merging**
