### PR TITLE
JIT: Fix NumArgs for `GetFfr*` and `CreateTrueMaskAll` HW intrinsics

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fixes https://github.com/dotnet/runtime/pull/105869#issuecomment-2269013026.

### CODE REVIEW

**Comment by a74nh** [comment]
Checking....

**Comment by a74nh** [comment]
Looks like the issue is still present with this PR

**Comment by mikabl-arm** [comment]
@jakobbotsch , seems that it doesn't fix the error we began to experience after 014632b2dcd5362febe6fe56df4a9215ae3937c8 . Have you encountered this assertion fail? Please let me know if the patch fixes the error for you.

```
Starting test: /home/mikabl01/dotnet/runtime/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true ./artifacts/tests/coreclr/linux.arm64.Checked/JIT/HardwareIntri
nsics/HardwareIntrinsics_Arm_ro/HardwareIntrinsics_Arm_ro.dll GatherVectorFirstFaulting                                                                        
===================Running default===================                                                                                                                                                                                                                                                                         
------------------- {} -------------------                                                                                                                                                                                                                                                                                    
Errors:                                                                        
                                                                                                                                                                                                                                                                                                                              
Assert failure(PID 3447181 [0x0034998d], Thread: 3447181 [0x34998d]): Assertion failed 'vnStore->VNFuncArity(func) == 1' in 'JIT.HardwareIntrinsics.Arm._Sve.SveGatherVectorVectorBasesTest__Sve_GatherVectorFirstFaulting_Bases_double_ulong:RunBasicScenario_UnsafeRead():this' during 'Do value numbering' (IL size 110; ha
sh 0x04f13b09; FullOpts)                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                              
    File: /home/mikabl01/dotnet/runtime/src/coreclr/jit/valuenum.cpp:12998                                                                                                                                                                                                                                                    
    Image: /home/mikabl01/dotnet/runtime/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun   
```

**Comment by jakobbotsch** [comment]
> @jakobbotsch , seems that it doesn't fix the error we began to experience after [014632b](https://github.com/dotnet/runtime/commit/014632b2dcd5362febe6fe56df4a9215ae3937c8) . Have you encountered this assertion fail? Please let me know if the patch fixes the error for you.
> 
> ```
> Starting test: /home/mikabl01/dotnet/runtime/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true ./artifacts/tests/coreclr/linux.arm64.Checked/JIT/HardwareIntri
> nsics/HardwareIntrinsics_Arm_ro/HardwareIntrinsics_Arm_ro.dll GatherVectorFirstFaulting                                                                        
> ===================Running default===================                                                                                                                                                                                                                                                                         
> ------------------- {} -------------------                                                                                                                                                                                                                                                                                    
> Errors:                                                                        
>                                                                                                                                                                                                                                                                                                                               
> Assert failure(PID 3447181 [0x0034998d], Thread: 3447181 [0x34998d]): Assertion failed 'vnStore->VNFuncArity(func) == 1' in 'JIT.HardwareIntrinsics.Arm._Sve.SveGatherVectorVectorBasesTest__Sve_GatherVectorFirstFaulting_Bases_double_ulong:RunBasicScenario_UnsafeRead():this' during 'Do value numbering' (IL size 110; ha
> sh 0x04f13b09; FullOpts)                                                                                                                                                                                                                                                                                                      
>                                                                                                                                                                                                                                                                                                                               
>     File: /home/mikabl01/dotnet/runtime/src/coreclr/jit/valuenum.cpp:12998                                                                                                                                                                                                                                                    
>     Image: /home/mikabl01/dotnet/runtime/artifacts/tests/coreclr/linux.arm64.Checked/Tests/Core_Root/corerun   
> ```

I have not reproduced it myself, no. I was hoping to be able to guess what the problem was. Let me spend some time to set up the environment to do that.

**Comment by jakobbotsch** [comment]
Same problem just for another HW intrinsic. Should fix it now.

**Review by TIHan — APPROVED** [review]

**Pull request merged**
