### PR TITLE
[mono] Make HelloWorld and wasm samples compile again

### PR DESCRIPTION
**Pull request by lambdageek**
Since 296aaf818ec02101226845aea39ca14d32519cf2 it seems we need `$(NetCoreAppToolCurrent)` as the `TargetFramework`

### CODE REVIEW

**Comment by lambdageek** [comment]
@akoeplinger @ViktorHofer  - I have no idea what i'm doing...

**Comment by lambdageek** [comment]
I'm not sure if `src/mono/netcore/sample/wasm/{console,browser}/WasmSample.csproj need to be changed too.  I think so...

**Review by vargaz — APPROVED** [review]

**Comment by naricc** [comment]
I thought we had the sample project compiling as a libraries test now? Did this some how escape that?

**Comment by lambdageek** [comment]
@naricc Looks like only the ios and android samples are included so far.  @MaximLipnin 
 has a PR open to also run the console wasm test https://github.com/dotnet/runtime/pull/45768, but HelloWorld and the browser wasm test aren't included, so they can fall behind

**Review by vargaz — APPROVED** [review]

**Review by radical — APPROVED** [review]

**Review by ViktorHofer — COMMENTED** [review]
LGTM. Note using $(NetCoreAppToolCurrent) is just a point in time fix until we can get them compile against the live built targeting pack.

**Pull request merged**
