### PR TITLE
Fix Thread::SetProfilerFilterContext usage

### PR DESCRIPTION
**Pull request by mikem8361**
Issue: https://github.com/dotnet/runtime/issues/47895

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
LGTM otherwise

**Comment by mikem8361** [comment]
It looked to me like StackWalkFrames shouldn't throw any exceptions but I may be wrong. Should  I add an exception handler around it?
________________________________

**Comment by jkotas** [comment]
Everything in DAC can throw DacError.

**Comment by mikem8361** [comment]
Oops. I merged the PR before seeing you comment after looking StackWalkFramesEx again, but I didn't think about DacErrors.

**Comment by mikem8361** [comment]
Is there a try/finally like pattern with the EX_TRY/EX_CATCH, etc macros?  That would be better than this code:
```

        EX_TRY
        {
            mEnumerated = true;
            mThread->StackWalkFrames(DacStackReferenceWalker::Callback, &gcctx, flagsStackWalk);
        }
        EX_CATCH
        {
            if (clearProfilerFilterContext)
            {
                mThread->SetProfilerFilterContext(NULL);
            }
            EX_RETHROW;
        }
        EX_END_CATCH(SwallowAllExceptions)

        if (clearProfilerFilterContext)
        {
            mThread->SetProfilerFilterContext(NULL);
        }
```

**Pull request merged**
