### PR TITLE
[release/9.0-preview5] Update implicit versions for 6,7,8

### PR DESCRIPTION
**Pull request by lewing**
These are the p5 versions for runtime based on the discussions with the SDK team.

### CODE REVIEW

**Comment by lewing** [comment]
The downlevel workload tests will fail for this since these versions don't exist in public yet.  We should probably disable them in the preview/release branches.

cc @maraf

**Review by akoeplinger — APPROVED** [review]

**Comment by dkurepa** [comment]
@lewing are these failures the ones you expected? Is this OK to merge?

**Comment by lewing** [comment]
yeah these failures are expected for now, @maraf is working on some logic to avoid them in the future

**Comment by dkurepa** [comment]
So I can merge this?

**Pull request merged**
