### PR TITLE
Fix KeepNativeSymbols to work on mono as well

### PR DESCRIPTION
**Pull request by omajid**
When packaging .NET on s390x through source-build, we want to keep debug
symbols enabled in the build. The package manager (debbuild, rpmbuild,
etc) generally strips the binaries to create distro-standard
-debug/-debuginfo packages. This was supported in coreclr via
--keepnativesymbols flag, but wasn't supported in mono (ie, s390x). Fix
that.

### CODE REVIEW

**Comment by omajid** [comment]
@uweigand I only tested this on x64, can you help me confirm that this works on s390x as well? I have been building with

    CXXFLAGS=-g CFLAGS=-g ./build.sh -c Release --keepnativesymbols true

And looking at the presence of debug symbols in "libcoreclr.so"

**Comment by omajid** [comment]
I have verified this on s390x.

The mono llvmfullaot errors look unrelated, can anyone confirm?

**Comment by omajid** [comment]
@marek-safar @uweigand can you please take a look at this?

**Comment by marek-safar** [comment]
@directhex how does this look to you?

**Comment by omajid** [comment]
Ping. Any review/feedback would be nice.

We have included this change for our 6.0 builds on RHEL/CentOS already: https://git.centos.org/rpms/dotnet6.0/blob/3afb15f24b3fc61da3d56a3e8269f85d084cb71a/f/SOURCES/runtime-66594-s390x-debuginfo.patch

**Comment by omajid** [comment]
Any thoughts, @directhex?

**Review by directhex — APPROVED** [review]

**Pull request merged**
