### PR TITLE
JIT: Avoid using type info from GDV guesses during import

### LINKED ISSUE #72363: [libraries-pgo] NRE in System.Collections.Immutable.Tests.ImmutableArrayBuilderTest.IndexOf
Failure: https://dev.azure.com/dnceng/public/_build/results?buildId=1886357&view=ms.vss-test-web.build-test-results-tab&runId=49269680&resultId=111042&paneView=debug
Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5b5f63f24f5746a780/System.Collections.Immutable.Tests/1/console.6b41d0ff.log?helixlogtype=result
```scala
    System.Collections.Immutable.Tests.ImmutableArrayBuilderTest.IndexOf [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.Enumerator.cs(202,0): at System.Collections.Immutable.ImmutableList`1.Enumerator.ResetStack()
        /_/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.Enumerator.cs(107,0): at System.Collections.Immutable.ImmutableList`1.Enumerator..ctor(Node root, Builder builder, Int32 startIndex, Int32 count, Boolean reversed)
        /_/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList_1.Node.cs(766,0): at System.Collections.Immutable.ImmutableList`1.Node.IndexOf(T item, Int32 index, Int32 count, IEqualityComparer`1 equalityComparer)
        /_/src/libraries/System.Collections.Immutable/tests/IndexOfTests.cs(78,0): at System.Collections.Immutable.Tests.IndexOfTests.IndexOfTest[TCollection](Func`2 factory, Func`3 indexOfItem, Func`4 indexOfItemIndex, Func`5 indexOfItemIndexCount, Func`6 indexOfItemIndexCountEQ)
        /_/src/libraries/System.Collections.Immutable/tests/ImmutableArrayBuilderTest.cs(253,0): at System.Collections.Immutable.Tests.ImmutableArrayBuilderTest.IndexOf()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(69,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  Finished:    System.Collections.Immutable.Tests
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
We can only use this type information after they have been expanded and
if we are on the happy path.

Fix #72363

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Covariant returns would have the same problem but `resolveVirtualMethod` currently fails for them with `CORINFO_DEVIRTUALIZATION_FAILED_SLOT`, so I think generics is the only case we can see this.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS @EgorBo

**Review by AndyAyersMS — APPROVED** [review]
This bug is also in 6.0, right?

We should consider porting the fix there.

**Comment by jakobbotsch** [comment]
> This bug is also in 6.0, right?

Doesn't look like it, we don't manage to do GDV for the test in 6.0. Looks like #56254 added that support.

**Pull request merged**
