### PR TITLE
Remove defunct !s after Roslyn changes for default(T)

### PR DESCRIPTION
**Pull request by stephentoub**
This will need a compiler update, which I believe @safern is already working on.

https://github.com/dotnet/roslyn/issues/34757#issuecomment-580002147

cc: @jcouv, @cston, @safern, @buyaa-n

### CODE REVIEW

**Comment by safern** [comment]
Yep. Once we get the arcade update merge we should have the new compiler in.

**Review by cston — APPROVED** [review]

**Comment by safern** [comment]
https://github.com/dotnet/runtime/pull/2074 has been merged. Triggering builds to re-run.

**Comment by jcouv** [comment]
Very cool. Nice :)

**Review by safern — APPROVED** [review]

**Pull request merged**
