### PR TITLE
[release/9.0] Backport "Fix SVE ExtendWidening ConditionalSelect tests" (#107601)

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Backport of #107601to release/9.0

/cc @kunalspathak @SwapnilGaikwad

## Customer Impact

- [ ] Customer reported
- [x] Found internally

The test template logic for `*ExtendWidening` SVE intrinsics was not calling the correct helper method to verify the intrinsic's return value for an enabled vector lane under `ConditionalSelect` scenarios. Furthermore, for vector lanes disabled by the mask passed to `ConditionalSelect`, the test logic was not comparing the element to the expected true/false value. This PR fixes both issues.

## Regression

- [ ] Yes
- [x] No

This was introduced by #107207, which was fixing an actual JIT bug, and added this new test logic to improve coverage.

## Testing

With this fix, all of our SVE tests are now passing.

## Risk

Low. This fix is only to ensure CI is clean on `release/9.0`.

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
#107722 needs to be merged in first.

**Comment by amanasifkhalid** [comment]
@kunalspathak PTAL, thanks!

**Review by kunalspathak — APPROVED** [review]
LGTM

**Review by jeffschwMSFT — APPROVED** [review]
approved. we can take this as tell mode (test only)

**Pull request merged**
