### PR TITLE
Fix tizen rootfs build

### PR DESCRIPTION
**Pull request by gbalykov**
Required after #37747

cc @alpencolt

### CODE REVIEW

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by am11** [comment]
It's best to push the change upstream (dotnet/arcade), otherwise anything under eng/common will be overwritten with the next arcade update.

ps: perhaps, it would be a good idea to add a git-push hook to notify users for such things.

**Comment by gbalykov** [comment]
@am11 thanks for information, I'll open PR to arcade

**Comment by janvorli** [comment]
Oops, I haven't noticed it didn't go to arcade, let me revert this change here.

**Pull request merged**
