### PR TITLE
[wasm][debugger] Fix failed to fetch debugger MT tests

### PR DESCRIPTION
**Pull request by thaystg**
.. by limiting parallel downloads of resources to 10.

### CODE REVIEW

**Comment by thaystg** [comment]
@pavelsavara 

Any idea why we are getting this failure:

```
System.ArgumentException : {
"timestamp": 1690833873333.062,
"exceptionDetails": {
"exceptionId": 2,
"text": "Uncaught (in promise)",
"lineNumber": 1637,
"columnNumber": 30,
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"stackTrace": {
"callFrames": [
{
"functionName": "fetch_like",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 1637,
"columnNumber": 30
},
{
"functionName": "fetchResource",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 946,
"columnNumber": 25
},
{
"functionName": "download_resource_with_cache",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 911,
"columnNumber": 25
}
],
"parent": {
"description": "Promise.then",
"callFrames": [
{
"functionName": "download_resource",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 884,
"columnNumber": 26
},
{
"functionName": "start_asset_download_sources",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 810,
"columnNumber": 36
},
{
"functionName": "start_asset_download_with_throttle",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 749,
"columnNumber": 31
}
],
"parent": {
"description": "await",
"callFrames": [
{
"functionName": "start_asset_download",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 699,
"columnNumber": 21
},
{
"functionName": "countAndStartDownload",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 494,
"columnNumber": 40
},
{
"functionName": "mono_download_assets",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 508,
"columnNumber": 16
}
],
"parent": {
"description": "await",
"callFrames": [
{
"functionName": "mono_wasm_pre_init_full",
"scriptId": "8",
"url": "http://localhost:9400/_framework/dotnet.runtime.js",
"lineNumber": 17701,
"columnNumber": 24
},
{
"functionName": "",
"scriptId": "8",
"url": "http://localhost:9400/_framework/dotnet.runtime.js",
"lineNumber": 17508,
"columnNumber": 18
}
],
"parent": {
"description": "await",
"callFrames": [
{
"functionName": "preInit",
"scriptId": "8",
"url": "http://localhost:9400/_framework/dotnet.runtime.js",
"lineNumber": 17518,
"columnNumber": 6
},
{
"functionName": "module.preInit",
"scriptId": "8",
"url": "http://localhost:9400/_framework/dotnet.runtime.js",
"lineNumber": 17427,
"columnNumber": 28
},
{
"functionName": "",
"scriptId": "9",
"url": "http://localhost:9400/_framework/dotnet.native.js",
"lineNumber": 7802,
"columnNumber": 25
},
{
"functionName": "initializeModules",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 2161,
"columnNumber": 4
},
{
"functionName": "createEmscriptenMain",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 2187,
"columnNumber": 10
}
],
"parent": {
"description": "await",
"callFrames": [
{
"functionName": "createEmscripten",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 2144,
"columnNumber": 10
}
],
"parent": {
"description": "await",
"callFrames": [
{
"functionName": "create",
"scriptId": "7",
"url": "http://localhost:9400/_framework/dotnet.js",
"lineNumber": 2079,
"columnNumber": 22
},
{
"functionName": "",
"scriptId": "5",
"url": "http://localhost:9400/debugger-main.js",
"lineNumber": 14,
"columnNumber": 9
}
]
}
}
}
}
}
}
},
"exception": {
"type": "object",
"subtype": "error",
"className": "TypeError",
"description": "TypeError: Failed to fetch\n    at Object.fetch_like (http://localhost:9400/_framework/dotnet.js:1638:31)\n    at fetchResource (http://localhost:9400/_framework/dotnet.js:947:26)\n    at download_resource_with_cache (http://localhost:9400/_framework/dotnet.js:912:26)",
"objectId": "-1987880161643711710.1.3",
"preview": {
"type": "object",
"subtype": "error",
"description": "TypeError: Failed to fetch\n    at Object.fetch_like (http://localhost:9400/_framework/dotnet.js:1638:31)\n    at fetchResource (http://localhost:9400/_framework/dotnet.js:947:26)\n    at download_resource_with_cache (http://localhost:9400/_framework/dotnet.js:912:26)",
"overflow": false,
"properties": [
{
"name": "stack",
"type": "string",
"value": "TypeError: Failed to fetch\n    at Object.fetch_lik…ttp://localhost:9400/_framework/dotnet.js:912:26)"
},
{
"name": "message",
"type": "string",
"value": "Failed to fetch"
}
]
}
},
"executionContextId": 1,
"exceptionMetaData": {
"requestId": "311.37"
}
},
"__forMethod": "Runtime.exceptionThrown"
}


```

**Comment by pavelsavara** [comment]
Is this un-handled exception?
When the browser has low memory, sometimes we see `TypeError: Failed to fetch` and we re-try the download.

**Review by radical — APPROVED** [review]

**Pull request merged**
