### PR TITLE
Fix ValidateResult for StoreSelectedScalar tests

### LINKED ISSUE #40542: [GCStress][HeapVerify] JIT/HardwareIntrinsics/Arm/StoreSelectedScalar
**linux-arm64**
```
export COMPlus_TieredCompilation=0
export COMPlus_DbgEnableMiniDump=1
export COMPlus_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export COMPlus_GCStress=0xC
export COMPlus_HeapVerify=1
export COMPlus_ReadyToRun=0
export COMPlus_ZapDisable=1

      Beginning test case StoreSelectedScalar.Vector128.UInt32.3 at 8/7/2020 3:32:22 AM
      Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
      
      Beginning scenario: RunBasicScenario_UnsafeRead
      Beginning scenario: RunBasicScenario_Load
      Beginning scenario: RunReflectionScenario_UnsafeRead
      Beginning scenario: RunReflectionScenario_Load
      Beginning scenario: RunClsVarScenario
      Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.1026.dmp
      Process 1026 corerun
      Written 62410752 bytes (15237 pages) to core file
      Dump successfully written
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
```

https://helix.dot.net/api/2019-06-17/jobs/f563defe-e209-4b8d-8582-f66a5b15f09e/workitems/JIT.HardwareIntrinsics/console

**windows-arm64**
```
set COMPlus_TieredCompilation=0
set COMPlus_GCStress=0xC
set COMPlus_HeapVerify=1
set COMPlus_ReadyToRun=0
set COMPlus_ZapDisable=1

      Beginning test case StoreSelectedScalar.Vector128.Byte.15 at 8/6/2020 7:46:57 PM
        Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
        
        Beginning scenario: RunBasicScenario_UnsafeRead
        Expected: 100
        Actual: -1073740286
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=D:\h\w\AD7B0933\p
        > D:\h\w\AD7B0933\w\AECD0933\e\JIT\HardwareIntrinsics\Arm\AdvSimd\AdvSimd_Part14_ro\AdvSimd_Part14_ro.cmd
    JIT\HardwareIntrinsics\Arm\AdvSimd\AdvSimd_Part15_r\AdvSimd_Part15_r.cmd [FAIL]
      
      Assert failure(PID 10932 [0x00002ab4], Thread: 2268 [0x08dc]): dwCode != EXCEPTION_BREAKPOINT
      
      CORECLR! DebuggerController::DispatchNativeException + 0x158 (0x00007ff8`549d28d0)
      CORECLR! Debugger::FirstChanceNativeException + 0xAC (0x00007ff8`549e2cbc)
      CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x138 (0x00007ff8`546f1f68)
      CORECLR! CLRVectoredExceptionHandler + 0x168 (0x00007ff8`546f1e08)
      CORECLR! CLRVectoredExceptionHandlerShim + 0x1C4 (0x00007ff8`546f25d4)
      NTDLL! RtlGetSaclSecurityDescriptor + 0x180 (0x00007ff8`890cccb0)
      NTDLL! LdrControlFlowGuardEnforced + 0x794 (0x00007ff8`8908cdc4)
      NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007ff8`89063434)
      KERNELBASE! DebugBreak + 0x0 (0x00007ff8`86ca52d0)
      CORECLR! WKS::gc_heap::verify_free_lists + 0x19C (0x00007ff8`5499beb4)
          File: F:\workspace\_work\1\s\src\coreclr\src\debug\ee\controller.cpp Line: 4142
          Image: D:\h\w\AD7B0933\p\CoreRun.exe
      
      
      Return code:      1
      Raw output file:      D:\h\w\AD7B0933\w\AECD0933\e\JIT\HardwareIntrinsics\Reports\JIT.HardwareIntrinsics\Arm\AdvSimd\AdvSimd_Part15_r\AdvSimd_Part15_r.output.txt
      Raw output:
      BEGIN EXECUTION
       "D:\h\w\AD7B0933\p\corerun.exe" AdvSimd_Part15_r.dll 
      Supported ISAs:
        AdvSimd:   True
        Aes:       True
        ArmBase:   True
        Crc32:     True
        Dp:        False
        Rdm:       False
        Sha1:      True
        Sha256:    True
      
      Beginning test case StoreSelectedScalar.Vector128.Int64.1 at 8/6/2020 7:52:59 PM
      Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
      
      Beginning scenario: RunBasicScenario_UnsafeRead
      Expected: 100
      Actual: -1073740286
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=D:\h\w\AD7B0933\p
      > D:\h\w\AD7B0933\w\AECD0933\e\JIT\HardwareIntrinsics\Arm\AdvSimd\AdvSimd_Part15_r\AdvSimd_Part15_r.cmd
      Expected: True
      Actual:   False
      Stack Trace:
        F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm64.Checked\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(2565,0): at JIT_HardwareIntrinsics._Arm_AdvSimd_AdvSimd_Part15_r_AdvSimd_Part15_r_._Arm_AdvSimd_AdvSimd_Part15_r_AdvSimd_Part15_r_cmd()
      Output:
        
        Assert failure(PID 10932 [0x00002ab4], Thread: 2268 [0x08dc]): dwCode != EXCEPTION_BREAKPOINT
        
        CORECLR! DebuggerController::DispatchNativeException + 0x158 (0x00007ff8`549d28d0)
        CORECLR! Debugger::FirstChanceNativeException + 0xAC (0x00007ff8`549e2cbc)
        CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x138 (0x00007ff8`546f1f68)
        CORECLR! CLRVectoredExceptionHandler + 0x168 (0x00007ff8`546f1e08)
        CORECLR! CLRVectoredExceptionHandlerShim + 0x1C4 (0x00007ff8`546f25d4)
        NTDLL! RtlGetSaclSecurityDescriptor + 0x180 (0x00007ff8`890cccb0)
        NTDLL! LdrControlFlowGuardEnforced + 0x794 (0x00007ff8`8908cdc4)
        NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007ff8`89063434)
        KERNELBASE! DebugBreak + 0x0 (0x00007ff8`86ca52d0)
        CORECLR! WKS::gc_heap::verify_free_lists + 0x19C (0x00007ff8`5499beb4)
            File: F:\workspace\_work\1\s\src\coreclr\src\debug\ee\controller.cpp Line: 4142
            Image: D:\h\w\AD7B0933\p\CoreRun.exe
        
        
        Return code:      1
        Raw output file:      D:\h\w\AD7B0933\w\AECD0933\e\JIT\HardwareIntrinsics\Reports\JIT.HardwareIntrinsics\Arm\AdvSimd\AdvSimd_Part15_r\AdvSimd_Part15_r.output.txt
        Raw output:
        BEGIN EXECUTION
         "D:\h\w\AD7B0933\p\corerun.exe" AdvSimd_Part15_r.dll 
        Supported ISAs:
          AdvSimd:   True
          Aes:       True
          ArmBase:   True
          Crc32:     True
          Dp:        False
          Rdm:       False
          Sha1:      True
          Sha256:    True
        
        Beginning test case StoreSelectedScalar.Vector128.Int64.1 at 8/6/2020 7:52:59 PM
        Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
        
        Beginning scenario: RunBasicScenario_UnsafeRead
        Expected: 100
        Actual: -1073740286
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=D:\h\w\AD7B0933\p
        > D:\h\w\AD7B0933\w\AECD0933\e\JIT\HardwareIntrinsics\Arm\AdvSimd\AdvSimd_Part15_r\AdvSimd_Part15_r.cmd
    JIT\HardwareIntrinsics\Arm\AdvSimd\AdvSimd_Part15_ro\AdvSimd_Part15_ro.cmd [FAIL]
      
      Assert failure(PID 7684 [0x00001e04], Thread: 6560 [0x19a0]): dwCode != EXCEPTION_BREAKPOINT
      
      CORECLR! DebuggerController::DispatchNativeException + 0x158 (0x00007ff8`549d28d0)
      CORECLR! Debugger::FirstChanceNativeException + 0xAC (0x00007ff8`549e2cbc)
      CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x138 (0x00007ff8`546f1f68)
      CORECLR! CLRVectoredExceptionHandler + 0x168 (0x00007ff8`546f1e08)
      CORECLR! CLRVectoredExceptionHandlerShim + 0x1C4 (0x00007ff8`546f25d4)
      NTDLL! RtlGetSaclSecurityDescriptor + 0x180 (0x00007ff8`890cccb0)
      NTDLL! LdrControlFlowGuardEnforced + 0x794 (0x00007ff8`8908cdc4)
      NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007ff8`89063434)
      KERNELBASE! DebugBreak + 0x0 (0x00007ff8`86ca52d0)
      CORECLR! WKS::gc_heap::verify_free_lists + 0x19C (0x00007ff8`5499beb4)
          File: F:\workspace\_work\1\s\src\coreclr\src\debug\ee\controller.cpp Line: 4142
          Image: D:\h\w\AD7B0933\p\CoreRun.exe
      
      
      Return code:      1
      Raw output file:      D:\h\w\AD7B0933\w\AECD0933\e\JIT\HardwareIntrinsics\Reports\JIT.HardwareIntrinsics\Arm\AdvSimd\AdvSimd_Part15_ro\AdvSimd_Part15_ro.output.txt
      Raw output:
      BEGIN EXECUTION
       "D:\h\w\AD7B0933\p\corerun.exe" AdvSimd_Part15_ro.dll 
      Supported ISAs:
        AdvSimd:   True
        Aes:       True
        ArmBase:   True
        Crc32:     True
        Dp:        False
        Rdm:       False
        Sha1:      True
        Sha256:    True
      
      Beginning test case StoreSelectedScalar.Vector128.Int64.1 at 8/6/2020 8:05:21 PM
      Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
      
      Beginning scenario: RunBasicScenario_UnsafeRead
      Expected: 100
      Actual: -1073740286
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=D:\h\w\AD7B0933\p
      > D:\h\w\AD7B0933\w\AECD0933\e\JIT\HardwareIntrinsics\Arm\AdvSimd\AdvSimd_Part15_ro\AdvSimd_Part15_ro.cmd
      Expected: True
      Actual:   False
      Stack Trace:
        F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm64.Checked\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(2468,0): at JIT_HardwareIntrinsics._Arm_AdvSimd_AdvSimd_Part15_ro_AdvSimd_Part15_ro_._Arm_AdvSimd_AdvSimd_Part15_ro_AdvSimd_Part15_ro_cmd()
      Output:
        
        Assert failure(PID 7684 [0x00001e04], Thread: 6560 [0x19a0]): dwCode != EXCEPTION_BREAKPOINT
        
        CORECLR! DebuggerController::DispatchNativeException + 0x158 (0x00007ff8`549d28d0)
        CORECLR! Debugger::FirstChanceNativeException + 0xAC (0x00007ff8`549e2cbc)
        CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x138 (0x00007ff8`546f1f68)
        CORECLR! CLRVectoredExceptionHandler + 0x168 (0x00007ff8`546f1e08)
        CORECLR! CLRVectoredExceptionHandlerShim + 0x1C4 (0x00007ff8`546f25d4)
        NTDLL! RtlGetSaclSecurityDescriptor + 0x180 (0x00007ff8`890cccb0)
        NTDLL! LdrControlFlowGuardEnforced + 0x794 (0x00007ff8`8908cdc4)
        NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007ff8`89063434)
        KERNELBASE! DebugBreak + 0x0 (0x00007ff8`86ca52d0)
        CORECLR! WKS::gc_heap::verify_free_lists + 0x19C (0x00007ff8`5499beb4)
            File: F:\workspace\_work\1\s\src\coreclr\src\debug\ee\controller.cpp Line: 4142
            Image: D:\h\w\AD7B0933\p\CoreRun.exe
        
        
        Return code:      1
        Raw output file:      D:\h\w\AD7B0933\w\AECD0933\e\JIT\HardwareIntrinsics\Reports\JIT.HardwareIntrinsics\Arm\AdvSimd\AdvSimd_Part15_ro\AdvSimd_Part15_ro.output.txt
        Raw output:
        BEGIN EXECUTION
         "D:\h\w\AD7B0933\p\corerun.exe" AdvSimd_Part15_ro.dll 
        Supported ISAs:
          AdvSimd:   True
          Aes:       True
          ArmBase:   True
          Crc32:     True
          Dp:        False
          Rdm:       False
          Sha1:      True
          Sha256:    True
        
        Beginning test case StoreSelectedScalar.Vector128.Int64.1 at 8/6/2020 8:05:21 PM
        Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
        
        Beginning scenario: RunBasicScenario_UnsafeRead
        Expected: 100
        Actual: -1073740286
        END EXECUTION - FAILED
        FAILED
```
https://helix.dot.net/api/2019-06-17/jobs/dbbbc822-7246-492b-831d-4114a2a158ad/workitems/JIT.HardwareIntrinsics/console
https://helix.dot.net/api/2019-06-17/jobs/399ac619-ae16-47a8-8250-5f323a14bcbc/workitems/JIT.HardwareIntrinsics/console

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #40542

### CODE REVIEW

**Comment by CarolEidt** [comment]
@echesakovMSFT @dotnet/jit-contrib  PTAL

**Review by echesakov — APPROVED** [review]
Thanks for tracking this down!

**Comment by CarolEidt** [comment]
Thanks @echesakovMSFT for the review, and thanks for the help with getting lldb working!

**Comment by CarolEidt** [comment]
Failures are in the `Loader/CollectibleAssemblies/ByRefLocals/ByRefLocals/ByRefLocals.sh` test which is also failing with JitStress: #40751

**Pull request merged**
