### PR TITLE
[release/7.0] JIT: Simplify JitDisasm matching behavior and support namespaces/generics in release

### PR DESCRIPTION
**Pull request by jakobbotsch**
Backport of #74430 to release/7.0

## Customer Impact
Without this PR specifying methods via the `DOTNET_JitDisasm` that we enabled in release builds in .NET 7 is limited in the following ways:
* It does not support disambiguating generic instantiations
* It does not support disambiguating by namespaces
* It does not support disambiguating overloads
* Wildcard support is severely limited

Additionally, the way that methods can be specified is inconsistent between debug/checked/release builds and between CG2/NAOT/runtime scenarios.

This PR fixes all of these items and aligns the behavior of debug/checked/release builds and CG2/NAOT/runtime scenarios to be the same.

The PR results in a change in behavior of how the matching for `JitDisasm` works, and how names are printed by `JitDisasmSummary`. Since these are new features we'd like to get the behavior change in from the beginning instead of taking a potential break in .NET 8, however small it might be.

## Testing
Testing was done manually on crossgen2/runtime/SPMI scenarios by specifying various combinations for these environment variables.

## Risk
While the change looks big there are minimal changes to main product scenarios. All of this code, except for the crossgen2 change, is only enabled when `DOTNET_JitDisasm`/`DOTNET_JitDisasmSummary` are set. I have verified that these functions are otherwise not called in release builds. Therefore I view the risk as low.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib @stephentoub PTAL @EgorBo

**Review by EgorBo — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
approved.  once we have a green ci we can merge.

**Comment by BruceForstall** [comment]
@jakobbotsch I presume this is a new, unique JIT-EE GUID in the release/7.0 branch?

If so, we won't be able to use any existing SuperPMI collections on release/7.0 testing. We should probably manually kick off a SuperPMI collection on this branch after this change merges (and propagates to the internal mirror) to ensure we have a usable collection.

**Comment by jakobbotsch** [comment]
> @jakobbotsch I presume this is a new, unique JIT-EE GUID in the release/7.0 branch?

Yep.

> If so, we won't be able to use any existing SuperPMI collections on release/7.0 testing. We should probably manually kick off a SuperPMI collection on this branch after this change merges (and propagates to the internal mirror) to ensure we have a usable collection.

I'll make sure to do that.

**Comment by carlossanlop** [comment]
Signed off, approved.
CI failure is known (NativeAOT SmokeTests in OSX x64 release): https://github.com/dotnet/runtime/issues/75005

>> We should probably manually kick off a SuperPMI collection on this branch after this change merges (and propagates to the internal mirror) to ensure we have a usable collection.
> 
> I'll make sure to do that.

@jakobbotsch I'm about to merge, so this is a friendly reminder to do the action requested above.

**Pull request merged**
