### PR TITLE
change win32 to derived types

### PR DESCRIPTION
**Pull request by KZedan**
Fixes #26227

### CODE REVIEW

**Comment by KZedan** [comment]
FYI seems like NegotiateStreamPal.Windows.cs doesn't like this change which will leave only 2 files eligible for this change. Is this what was expected? Could this be the reason why derived types haven't been used as this may need too much structural change?

It seems like within the System.Net files there are quite a few Win32 exceptions a very few of them fit within the context of these 4:

System.Net.HttpListenerException
System.Net.NetworkInformation.NetworkInformationException
System.Net.Sockets.SocketException
System.Net.WebSockets.WebSocketException

Which are the only available derived types it seems.

**Comment by danmoseley** [comment]
If you click through to Azure Devops and look at the raw log, it shows the project files:
```
2021-05-23T14:39:01.4323284Z D:\workspace\_work\1\s\src\libraries\Common\src\System\Net\Security\NegotiateStreamPal.Windows.cs(172,25): error CS0246: The type or namespace name 'HttpListenerException' could not be found (are you missing a using directive or an assembly reference?) [D:\workspace\_work\1\s\src\libraries\System.Net.Mail\src\System.Net.Mail.csproj]
2021-05-23T14:39:01.4325935Z D:\workspace\_work\1\s\src\libraries\Common\src\System\Net\Security\NegotiateStreamPal.Windows.cs(172,25): error CS0246: The type or namespace name 'HttpListenerException' could not be found (are you missing a using directive or an assembly reference?) [D:\workspace\_work\1\s\src\libraries\System.Net.Security\src\System.Net.Security.csproj]
2021-05-23T14:39:01.4330147Z D:\workspace\_work\1\s\src\libraries\Common\src\System\Net\Security\NegotiateStreamPal.Windows.cs(172,25): error CS0246: The type or namespace name 'HttpListenerException' could not be found (are you missing a using directive or an assembly reference?) [D:\workspace\_work\1\s\src\libraries\System.Net.Http\src\System.Net.Http.csproj]
```

Basically these are shared source files and 3 of the projects pulling them in don't have a reference to HttpListenerException, which is in System.Net.HttpListener. 

I think this is indicating that this is not a good choice. Would SocketException be a better choice? This should be visible to all these libraries. @wfurt is it appropriate?

**Comment by danmoseley** [comment]
Oh, I didn't read all of your posting above. OK, I would like to hear @wfurt  opinion on whether any of those are appropriate or we need to consider a new type.

**Comment by wfurt** [comment]
HttpListenerException is certainly not appropriate for SslStream or NegotiateStream. One way to go may be wrapping win32 exception in. AuthenticationException and do the same for low-level OpenSSL codes. With that the exception type would be consistent while preserving the platform details.

**Comment by KZedan** [comment]
@danmoseley does what @wfurt suggested require a proposal?

**Comment by stephentoub** [comment]
> One way to go may be wrapping win32 exception in. AuthenticationException and do the same for low-level OpenSSL codes

AuthenticationException does not derive from Win32Exception, so such a change would change the type thrown to one that could break catch blocks expecting Win32Exception.

**Comment by stephentoub** [comment]
Thanks for the PR.  As noted by others, though, none of the changes in this PR as it's currently written should be merged... HttpListenerException is not acceptable in these call sites.

**Comment by KZedan** [comment]
No problems. I noted that only the above 4 exceptions I mentioned are derived from Win32Exception which are not suitable for any of these cases so I have closed the PR.

**Pull request closed without merging**
