### PR TITLE
Remove Crossgen2's -O option in Test Builds Wherever Possible

### LINKED ISSUE #56148: R2R jobs should not pass -O to crossgen2
When -O is passed, crossgen2 will ignore the assembly's "debug" bit. We have some JIT tests that rely on this bit to be respected which are currently disabled because of this behavior since our R2R jobs pass -O. Some more discussion in #55062.

cc @dotnet/crossgen-contrib

### PR DESCRIPTION
**Pull request by ivdiazsa**
This PR fixes issue #56148. The `-O` option for Crossgen2 was required in the past for several reasons. However, nowadays it's causing issues in some tests that depend on their assembly's debug bit, which the `-O` option causes to be ignored.

### CODE REVIEW

**Comment by ivdiazsa** [comment]
@trylek Hi Tomas! I removed all the `-O` calls to Crossgen I could find, but I'm not sure if I missed others or whether some of these must remain. PTAL and let me know your thoughts.

**Review by trylek — APPROVED** [review]
Looks great to me, thank you!

**Comment by ivdiazsa** [comment]
Hmm seems like something broke in certain AOT configurations. Taking a look right now.

**Comment by ivdiazsa** [comment]
Extra Platforms seems to be utterly broken for Mono, completely unrelated to my changes. Will try to run only the default *innerloop* and *outerloop* with all the changes and if those pass, then this PR is ready to merge.

**Pull request merged**
