### PR TITLE
JIT: Remove loop-related VN quirks

### PR DESCRIPTION
**Pull request by jakobbotsch**
Some minor diffs expected from increased VN precision around newly recognized loops, which leads to different CSEs.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Hitting a loop alignment related assert I'll need to investigate:
```scala
ISSUE: <ASSERT> #567048 D:\a\_work\1\s\src\coreclr\jit\emit.cpp (4636) - Assertion failed '(jmpGroup->igFlags & IGF_HAS_ALIGN) == 0' in 'System.Security.Cryptography.Tests.RandomNumberGeneratorTests:VerifyDistribution[ushort](System.ReadOnlySpan`1[ushort],double)' during 'Generate code' (IL size 218; hash 0x53d500b4; Tier1)
```

**Comment by EgorBo** [comment]
> Hitting a loop alignment related assert I'll need to investigate:
> 
> ```scala
> ISSUE: <ASSERT> #567048 D:\a\_work\1\s\src\coreclr\jit\emit.cpp (4636) - Assertion failed '(jmpGroup->igFlags & IGF_HAS_ALIGN) == 0' in 'System.Security.Cryptography.Tests.RandomNumberGeneratorTests:VerifyDistribution[ushort](System.ReadOnlySpan`1[ushort],double)' during 'Generate code' (IL size 218; hash 0x53d500b4; Tier1)
> ```

I think we have similar asserts in the outerloop PGO pipeline in Main, will file an issue

**Comment by kunalspathak** [comment]
> I think we have similar asserts in the outerloop PGO pipeline in Main, will file an issue

The one in https://github.com/dotnet/runtime/issues/95755 seems to be different than what @jakobbotsch is getting and most likely happening due to recent changes in jump removal. I will take a look.

**Comment by jakobbotsch** [comment]
The issue repros on main if you comment the following code:
https://github.com/dotnet/runtime/blob/9080024d1ccd38974f0d297ac6373e6e8d62ec5d/src/coreclr/jit/optimizer.cpp#L8704-L8714
and then run
```
py .\src\coreclr\scripts\superpmi.py replay -f libraries_tests.run -target_os linux
```

**Comment by kunalspathak** [comment]
> Any ideas? Do we need to force a new IG after an IG that is a candidate for jmp removal, or before a basic block that is marked for align insertion?

We shouldn't force a new IG in such case because that defeats the purpose of placing the `align` instruction at that position. We are trying to hide it after `jmp` and if the `jmp` is removed, the `align` instruction will get executed. The assert actually was in wrong place, and I fixed it in https://github.com/dotnet/runtime/pull/95845.

BTW, it occurred to me, I don't see that we mark the new loops detected in `optFindNewLoops()` for alignment. Is there a plan to do that?

https://github.com/dotnet/runtime/blob/6de7549ae1872009baade9091be76071f955c47d/src/coreclr/jit/optimizer.cpp#L5541-L5544

**Comment by jakobbotsch** [comment]
> BTW, it occurred to me, I don't see that we mark the new loops detected in `optFindNewLoops()` for alignment. Is there a plan to do that?

Yes, but I am focusing on porting everything first, before enabling optimizations for new loops (which I will do in individual PRs after).
For loop alignment specifically there is #95836 first to move the candidate identification into `placeLoopAlignmentInstructions` first (reviving Bruce's old PR). That PR also switches to the new loop structures, but it currently still has a quirk that the loop was recognized by old loop finding, which will be removed separately. When we do that we may need some heuristic that the loop blocks are somewhat tightly packed together, since that's not guaranteed for new loops.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @BruceForstall 

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=497122&view=ms.vss-build-web.run-extensions-tab). As mentioned above it's because of some increased precision in VN in some cases, leading to different CSEs.

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
