### PR TITLE
Consume regs for BlkOpKindLoop

### LINKED ISSUE #96599: Assertion failed 'tmpGetCount == 0'
**Failed in:** [runtime-coreclr gcstress-extra 20240106.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=517056&view=ms.vss-test-web.build-test-results-tab&runId=12132898&resultId=133111&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.11.Arm64.Open
    - JIT/Regression/JitBlue/GitHub_65690/GitHub_65690/GitHub_65690.cmd
coreclr osx arm64 Checked gcstress0xc_zapdisable_jitstress2 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/GitHub_65690/GitHub_65690/GitHub_65690.cmd
```

**Error message:**
```
 
Assert failure(PID 6112 [0x000017e0], Thread: 9080 [0x2378]): Assertion failed 'tmpGetCount == 0' in 'System.StartupHookProvider:ProcessStartupHooks(System.String)' during 'Generate code' (IL size 169; hash 0x6685ce12; FullOpts)

    File: D:_work1ssrccoreclrjit
egset.cpp Line: 1056
    Image: C:hwA864095Apcorerun.exe


Return code:      1
Raw output file:      C:hwA864095AwA8D8091AuploadsJitBlueGitHub_65690GitHub_65690output.txt
Raw output:
BEGIN EXECUTION
 "C:hwA864095Apcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  GitHub_65690.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 1/6/2024 11:31:31 PM
Processing C:corescorerun.exe.6112.dmp
Unable to find cdb.exe at C:Program Files (x86)Windows Kits10Debuggersrm64cdb.exe
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hwA864095AwA8D8091AeJITRegressionRegression_3../JitBlue/GitHub_65690/GitHub_65690/GitHub_65690.cmd
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor346|0_347(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-01-07T07:35:18.438Z | runtime-coreclr crossgen2-composite gcstress | Checked-gcstress0xc_zapdisable_jitstress2 | osx.1200.arm64.open | arm64 | JIT/Regression/JitBlue/GitHub_65690/GitHub_65690/GitHub_65690.cmd | Failed | {"DefinitionId":"141","configuration":"Checked-gcstress0xc_zapdisable_jitstress2","System.JobAttempt":"1","System.JobName":"__default","DefinitionName":"runtime-coreclr crossgen2-composite gcstress","operatingSystem":"OSX.1200.ARM64.Open","System.PhaseAttempt":"1","Reason":"Schedule","System.JobId":"4b5575ba-4f05-5198-bc88-a075c735caa5","BuildId":"517145","Project":"public","System.StageAttempt":"1","BuildNumber":"20240106.1","AzurePipelinesTestRunId":"12135748","System.StageName":"Build","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"arm64","System.PhaseName":"run_test_p1_Composite_osx_arm64_checked"} | Schedule
2024-01-06T22:31:23.521Z | runtime-coreclr gcstress-extra | Checked-gcstress0xc_zapdisable_jitstress2 | osx.1200.arm64.open | arm64 | JIT/Regression/JitBlue/GitHub_65690/GitHub_65690/GitHub_65690.cmd | Failed | {"DefinitionId":"113","configuration":"Checked-gcstress0xc_zapdisable_jitstress2","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-coreclr gcstress-extra","operatingSystem":"OSX.1200.ARM64.Open","BuildNumber":"20240106.1","BuildId":"517056","architecture":"arm64","System.StageName":"Build","Project":"public","System.PhaseName":"run_test_p1__osx_arm64_checked","AzurePipelinesTestRunId":"12132936","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.JobAttempt":"1","Reason":"Schedule","System.StageAttempt":"1","System.JobName":"__default"} | Schedule

### PR DESCRIPTION
**Pull request by kunalspathak**
In https://github.com/dotnet/runtime/pull/95530, we forgot to consume the register that leads to a temp register around.

Fixes: #96599

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib @EgorBo PTAL

**Comment by EgorBo** [comment]
Does it lead to bad codegen? (because that PR was backported to 8.0) or just consumes unnecessary reg?

CI failures seem related?

**Comment by kunalspathak** [comment]
> Does it lead to bad codegen? (because that PR was backported to 8.0) or just consumes unnecessary reg?

It should consume the unnecessary reg, but perhaps that is leading to unused register and that is getting used somewhere below with wrong value. Let me investigate. However, I think for arm64, if we know that we will be using `xzr` for `op1`, we should ideally convey that information during LSRA or should we mark the node as contained.

> CI failures seem related?

Taking a look

**Comment by kunalspathak** [comment]
>  should we mark the node as contained

I see that they are marked contained https://github.com/dotnet/runtime/pull/95530/files#diff-547b75c8f8dd006693805c30d7a0e2ddcdd6b10691383dfbb16e3ed0c50f236aR621-R628

**Review by BruceForstall — APPROVED** [review]

**Review by EgorBo — APPROVED** [review]

**Comment by kunalspathak** [comment]
Failures seems unrelated because the changes are on arm64, and failures are x86.

**Pull request merged**
