### PR TITLE
Add armv8l virtualized 32-bit ARM core detection

### PR DESCRIPTION
**Pull request by ayakael**
## Expected behavior
Runtime should be able to build within 32-bit userspace on 64-bit ARM cores.

## Actual behavior
Per dotnet/source-build#2781, runtime does not know to parse as `arm` when output of `uname -m` is `armv8l`.

## Proposed modifications
This pull request modifies existing logics to parse `armv8l` in the same way as `armv7l`.

## Varia
Parallel merge request on Alpine's [side](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/31812)
Arm support on source-build at https://github.com/dotnet/installer/pull/13378

Made as part of Alpine Linux dotnet6 packaging project, see dotnet/source-build#2782

### CODE REVIEW

**Review by directhex — APPROVED** [review]

**Review by jkoritzinsky — COMMENTED** [review]
This looks okay to me. My only concern is that someone could build on an ARMv8 system and it would fail to run on an ARMv7 system. Is that something that can occur with this change?

**Comment by directhex** [comment]
@jkoritzinsky I don't believe that can occur here. As it happens I already filed an issue similar to this in 2019. https://github.com/dotnet/arcade/pull/4527

**Review by jkoritzinsky — APPROVED** [review]
@directhex has more experience in this area and says there's no issue, so I'm okay with the change

**Comment by ayakael** [comment]
@directhex Should I change the logics to cover `arm*vl` like in your PR?

**Comment by akoeplinger** [comment]
Yeah I think that makes sense so we're ready for `armv9l` 😄 
There's also another check here that needs updating: https://github.com/dotnet/runtime/blob/458524aa752f6841db44bd4443ccc3f3863e0a4e/eng/native/configuretools.cmake#L56

**Comment by ayakael** [comment]
> Yeah I think that makes sense so we're ready for `armv9l` smile There's also another check here that needs updating:
> 
> https://github.com/dotnet/runtime/blob/458524aa752f6841db44bd4443ccc3f3863e0a4e/eng/native/configuretools.cmake#L56

I'm ignorant of proper syntax, does  `CMAKE_SYSTEM_PROCESSOR MATCHES "^(armv*l|aarch64|arm|s390x)$")` and ` elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL armv*l)` work?

**Comment by akoeplinger** [comment]
It's a regex so it'd need to be `.*`, but I wonder if we shouldn't just use the explicit names in this case and update it once/if armv9l becomes a thing.

**Comment by ayakael** [comment]
> It's a regex so it'd need to be `.*`, but I wonder if we shouldn't just use the explicit names in this case and update it once/if armv9l becomes a thing.

That might be more prudent, indeed.

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
