### PR TITLE
Upgrade `StyleCopAnalyzers` to `v1.2.0-beta.333`

### PR DESCRIPTION
**Pull request by xtqqczze**
cc: @sharwell, @danmoseley 

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases/tag/1.2.0-beta.333

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/compare/1.2.0-beta.304...1.2.0-beta.333

_Draft PR to run CI, as suggested in https://github.com/dotnet/runtime/pull/45779#issuecomment-748243876_

### CODE REVIEW

**Comment by danmoseley** [comment]
Marking No-Merge as this is just for validation.

**Comment by sharwell** [comment]
There are several bug fixes in this, but nothing you would need unless you're seeing bad behavior in an analyzer you have enabled (or want to enable). No significant perf changes.

**Comment by danmoseley** [comment]
@xtqqczze could you remind me what you're trying to achieve here? I don't think we will pick up a new StyleCop package until we need one (for perf, feature or bug fix)

**Comment by xtqqczze** [comment]
```
src/tasks/tasks.proj(0,0): error NU1102: (NETCORE_ENGINEERING_TELEMETRY=Restore) Unable to find package StyleCop.Analyzers.Unstable with version (>= 1.2.0.333)
  - Found 16 version(s) in dotnet-public [ Nearest version: 1.2.0.321 ]
```

**Comment by xtqqczze** [comment]
```
nuget search StyleCop.Analyzers -PreRelease -Source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json
====================
Source: dotnet-public
--------------------
> StyleCop.Analyzers | 1.2.0-beta.333 | Downloads: N/A
  An implementation of StyleCop's rules using Roslyn analyzers and code fixes
--------------------
> StyleCop.Analyzers.Unstable | 1.2.0.321 | Downloads: N/A
  An implementation of StyleCop's rules using Roslyn analyzers and code fixes
--------------------
```

**Comment by xtqqczze** [comment]
@mmitche I see `StyleCop.Analyzers` `1.2.0-beta.333` has a dependency on `StyleCop.Analyzers.Unstable` `1.2.0.333`, which has not yet been published to `dotnet-public`.

**Comment by mmitche** [comment]
Pushed.

**Comment by stephentoub** [comment]
@xtqqczze, why is this PR needed? Thanks.

**Comment by stephentoub** [comment]
@xtqqczze, again,  what is the purpose of this PR? If we don't hear back from you soon,  we'll close it. Thanks.

**Comment by xtqqczze** [comment]
@stephentoub The purpose is to run CI, as suggested in https://github.com/dotnet/runtime/pull/45779#issuecomment-748243876_

Since the failures are seemingly unrelated, I suppose you could close this for now.

**Comment by danmoseley** [comment]
@xtqqczze if you want to validate new style cop versions against this repo, you do not need CI - you can do this locally.

**Pull request closed without merging**
