### PR TITLE
Adding area owners for new mono labels

### PR DESCRIPTION
**Pull request by maryamariyan**
cc: @marek-safar

### CODE REVIEW

**Review by marek-safar — APPROVED** [review]

**Comment by jeffschwMSFT** [comment]
Once all the github issues from dotnet/coreclr are integrated, we should make a similar change for the coreclr areas that have overlap (eg. `area-debugger-coreclr`)

**Review by stephentoub — APPROVED** [review]

**Comment by danmosemsft** [comment]
> Once all the github issues from dotnet/coreclr are integrated, we should make a similar change for the coreclr areas that have overlap (eg. area-debugger-coreclr)

@jeffschwMSFT if you look at the runtime team's labels in the [current content](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md) do you see any remaining edits or label changes you would like?

**Comment by jeffschwMSFT** [comment]
My recommendation is that we move all the labels that have overlap with mono to include the post fix `-coreclr`.

**Comment by danmosemsft** [comment]
@jeffschwMSFT sounds good to me. If you do this now, we can roll it into a retraining that @maryamariyan is about to do (I think)

cc @marek-safar

**Comment by maryamariyan** [comment]
noted.

**Pull request merged**
