### PR TITLE
Split AsnReader into a class and a ref struct (AsnValueReader)

### PR DESCRIPTION
**Pull request by bartonjs**
Largely, the intent of this change was to reduce the number of temporary readers required for deeply structured payloads (`ReadSequence` returns a new reader), while still maintaining the better usability of the class; and, frankly, to understand what the impact of splitting functionality into "bare metal" and "more usable" pieces was.

```
foreach (file in AsnReader.*)
{
    Copy/paste the entirety of the `partial class AsnReader`;
    Change the top version to say ref partial struct AsnValueReader;
    Replace all AsnReader calls in the top version to say AsnValueReader.
    Replace all ReadOnlyMemory in the top portion with ReadOnlySpan;
    Remove ArraySegment overloads from the top portion (when present);
    Rewrite the bottom portion to open a ref reader at the state the memory is tracking and defer work into the ref reader;
    Run all the existing tests to ensure that nothing broke in that piece;
}
```

Once that was done, I changed the asn.xslt to generate all of the decoding in terms of AsnValueReader.  This didn't change field generation from ReadOnlyMemory to ReadOnlySpan (and the types from struct to ref struct)--a change that could be done later--but instead added a new ReadOnlyMemory input parameter so it can use Overlaps to slice the memory as appropriate (with a fallback of ToArray()).

While I was editing asn.xslt I fixed probably all of the whitespace errors it generated.  I still left the "stylecop, have no opinion about whitespace" pragma since the generator isn't run as part of most people's (or the official) builds.  This also turns on the nullability checks in all of the generated structs.

Perf-wise, it has almost no impact.  There are methods that currently do data prevalidation with one quick load of a reader and call PeekEncodedValue (sometimes just to process the length).  Changing those methods to use AsnValueReader could have virtue, but none are really in tight loops.  The biggest GC and throughput stability benefit is when a BER encoded payload uses deeply nested indefinite encoding (because it makes nested readers to find where each one ends).  That's not a common scenario, so I don't have a practical benchmark for it.

Benchmarks, for the curious.  `baseline` is 5f999925be098efd2dedbdd78a4298adf22fd349. `valuereader` is with splitting the type, but not changing anything to use it.  `asnxml` is with also changing the generator.  I changed the tables to show them in this order.

* rsa.ImportEncryptedPkcs8(...)

|             Method |                Toolchain |     Mean |   Error |  StdDev | Ratio | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------- |------------------------- |---------:|--------:|--------:|------:|------:|------:|------:|----------:|
| ImportDiminishedDP |    \baseline\CoreRun.exe | 713.9 us | 3.35 us | 3.13 us |  1.00 |     - |     - |     - |   2.07 KB |
| ImportDiminishedDP | \valuereader\CoreRun.exe | 711.1 us | 2.56 us | 2.27 us |  1.00 |     - |     - |     - |   2.07 KB |
| ImportDiminishedDP |      \asnxml\CoreRun.exe | 700.0 us | 3.63 us | 3.40 us |  0.98 |     - |     - |     - |   1.89 KB |

* rfc3161Request.ProcessResponse(...)

|                Method |                Toolchain |     Mean |     Error |    StdDev | Ratio |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|---------------------- |------------------------- |---------:|----------:|----------:|------:|-------:|-------:|------:|----------:|
| PairTimestampResponse |    \baseline\CoreRun.exe | 1.583 ms | 0.0051 ms | 0.0047 ms |  1.00 | 9.7656 | 1.9531 |     - |  44.33 KB |
| PairTimestampResponse | \valuereader\CoreRun.exe | 1.591 ms | 0.0040 ms | 0.0035 ms |  1.00 | 9.7656 | 1.9531 |     - |  44.31 KB |
| PairTimestampResponse |      \asnxml\CoreRun.exe | 1.589 ms | 0.0033 ms | 0.0031 ms |  1.00 | 9.7656 | 1.9531 |     - |   42.3 KB |

### CODE REVIEW

**Comment by bartonjs** [comment]
I guess I should say (and meant to hit submit right after opening the PR, whoops)

* The split style was done such that the complicated spec-conforming work didn't change (except the occasional local variable rename).
* The AsnReader classes are worth strong scrutiny.  The .xml.cs files are worth some spot checking; then cross-reference some of the output changes with the asn.xslt changes to see the scope.

**Comment by bartonjs** [comment]
OK, so I know the change I need to make to fix the test failure; but every test I've written to capture the state in a unit test has thrown the "right" exception, instead of an ANE.  Working on tracking down the minimal repro for a unit test.

Also, for the record, it's super frustrating that `ReadOnlyMemory<T>.Slice(int start, int length)` claims "start" is wrong when length is the problem.  (vs ROSpan, which, differently annoying, doesn't report any specific parameter)

**Review by GrabYourPitchforks — APPROVED** [review]
A question re: stackalloc, but otherwise LGTM.

**Pull request merged**
