### PR TITLE
Enable EHWrite thru

### PR DESCRIPTION
**Pull request by kunalspathak**
DO NOT MERGE : This is an experimental PR to see if jitstressregs and jitstressregs - libraries work with EH write thru on.

### CODE REVIEW

**Comment by naricc** [comment]
What is EHWrite thru? Some kind of cache write thru?

**Comment by kunalspathak** [comment]
> What is EHWrite thru? Some kind of cache write thru?

It is write thru the values to stack as well as register if the method has exception handling (EH) code. See https://github.com/dotnet/runtime/issues/35923 for more context.

**Comment by AndyAyersMS** [comment]
> What is EHWrite thru?

There's a good writeup here: [Exception Handling Write Through Optimization](https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/jit/eh-writethru.md).

**Comment by kunalspathak** [comment]
Another experiment to see if "Combine free and busy alloc" work in #45135 broke `EhWriteThru` scenarios.

**Comment by kunalspathak** [comment]
Failures after reverting "Combine busy and free alloc" work is minimal in "runtime-coreclr jitstressregs". So probably, that work introduced issues in EHWriteThru scenarios.

**Comment by kunalspathak** [comment]
> Failures after reverting "Combine busy and free alloc" work is minimal in "runtime-coreclr jitstressregs". So probably, that work introduced issues in EHWriteThru scenarios.

Not sure which results I was checking out, but seems there are failures even before "Combine busy and free alloc", so possibly EHWriteThru default was never verified still jitstressregs?

**Pull request closed without merging**
