### PR TITLE
Mop-up changes per Jakob's PR suggestions

### LINKED ISSUE #69900: Delete `doesFieldBelongToClass`
With #68712 and #68986, there is no longer a need for it.

Ref: https://github.com/dotnet/runtime/pull/68986#discussion_r883745928.

### PR DESCRIPTION
**Pull request by trylek**
1) Rename CORINFO_HELP_STATIC_VIRTUAL_AMBIGUOUS_RESOLUTION to
CORINFO_HELP_THROW_AMBIGUOUS_RESOLUTION_EXCEPTION and put it next
to the other CORINFO_HELP_THROW methods;

2) Add the new helper to CorInfoHelpFunc.cs;

3) Remove the obsolete jitinterface member doesFieldBelongToClass;

4) Update the JIT EE GUID.

Thanks

Tomas

Fixes: #69900

/cc @dotnet/jit-contrib

### CODE REVIEW

**Review by jakobbotsch — APPROVED** [review]
Thanks!

**Comment by BruceForstall** [comment]
I don't have an opinion on the actual change, however I wonder if it would be ok to delay merging it temporarily? Our benchmark SuperPMI collection is failing due to some kind of un-investigated/un-resolved infrastructure issue (@kunalspathak plans to keep investigating), and if we change the JIT-EE GUID before that is fixed, we will lose having the benchmark test for spmi testing.

**Comment by jakobbotsch** [comment]
> I wonder if it would be ok to delay merging it temporarily?

I think that's probably fine -- though one thing to note is that this is a follow-up to #66887 that added a new helper without updating the JIT-EE GUID, so we could potentially have some weird JIT behavior if we end up with mismatched JIT/VM/SPMI collections that use that helper.

**Comment by trylek** [comment]
No worries, let me know when / how to proceed with this change, it's not blocking to any of my work assignments.

**Comment by jakobbotsch** [comment]
The issue @BruceForstall talked about should be fixed now with https://github.com/dotnet/performance/pull/2469, so will merge this.

**Pull request merged**
