### PR TITLE
Use generated version files when printing/tracing host version info

### LINKED ISSUE #80961: Single-file host tracing should include version and/or commit hash
We intentionally do not set file version information for `apphost` and `singlefilehost`, since they represent the user's application. With `apphost`, we can still see the version and commit hashes in traces - for example:
```
--- Invoked apphost [version: 7.0.0, commit hash: d099f075e45d2aa6007a22b71b45a08758559f80] main = {
--- Invoked hostfxr_main_startupinfo [commit hash: d037e070ebe5c83838443f869d5800752b0fcb13]
--- Invoked hostpolicy [commit hash: d037e070ebe5c83838443f869d5800752b0fcb13] [runtime.win-x64.Microsoft.NETCore.DotNetHostPolicy,7.0.2,runtimes/win-x64/native][x64] corehost_main = {
```

For `singlefilehost`, we explicitly set this information to `static`:
https://github.com/dotnet/runtime/blob/ff12237f483eb0afdabf1aeb71b69ff992d6bd40/src/native/corehost/setup.cmake#L4-L14

So all we have is:
```
--- Invoked apphost [version: static, commit hash: static] main = {
--- Invoked hostfxr_main_bundle_startupinfo [commit hash: static]
--- Invoked hostpolicy [commit hash: static] [static,static,static][x64] corehost_main = {
```

There doesn't seem to be any reasonable way to get at the version of the host is running. It is probably worth having a real value for at least either the version or commit so we can better understand what is being used when customers hit issues.

### PR DESCRIPTION
**Pull request by elinor-fung**
Use generated version files when printing/tracing host version info.
- Use `VER_PRODUCTVERSION_STR` / `sccsid` from generated `_version.(h|c)` for version and commit info (for tracing)
- Use `RuntimeProductVersion` for version from header generated by `GenerateRuntimeVersionFile` 
- Remove `HOST_*_PKG_VER` defines and script arguments for passing that info around

Fixes https://github.com/dotnet/runtime/issues/80961

Host traces will have:
```
--- Invoked apphost [version: 8.0.0-dev @Commit: c088228be355eef650fbde9593122e21b2b124aa] main = {
--- Invoked hostfxr_main_bundle_startupinfo [version: 8.0.0-dev @Commit: c088228be355eef650fbde9593122e21b2b124aa]
--- Invoked hostpolicy [version: 8.0.0-dev @Commit: c088228be355eef650fbde9593122e21b2b124aa] corehost_main = {
```

### CODE REVIEW

**Comment by am11** [comment]
`_version.c` is generated here: https://github.com/dotnet/runtime/blob/41bc9351e2fa6ab70dc8750fe4c765d92ffcb846/eng/native/version/copy_version_files.sh#L14 and included in multiple (all native?) projects, including the hosts: https://github.com/dotnet/runtime/blob/41bc9351e2fa6ab70dc8750fe4c765d92ffcb846/src/native/corehost/common.cmake#L23

would be nice to generalize and reuse that global info instead of wiring up a new mechanism.

e.g. diagnostics has mirrored `eng/native` directory, and we reused that SCCSID thing in SOS which also needed it internally to log the version and commit info, with a small cmake hack: https://github.com/dotnet/diagnostics/blob/ef7b8a56a162818e0af8bf5fe1de589fa0bf38e4/CMakeLists.txt#L41-L46.

All these seem very similar use-cases for which we can do something better, IMO.

Currently, one limitation is imposed by arcade is that it only allows one version file per platform, so it is either _version.c (Unix) or _version.h (Windows): https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Arcade.Sdk/tools/Version.targets., we can change it to emit both on all platforms.

cc @jkoritzinsky, @ViktorHofer

**Comment by elinor-fung** [comment]
Thanks. Switched to using generated `_version.h`/`version.h` and `runtime_verion.h` and removed the assorted version defines in the host.

**Review by am11 — APPROVED** [review]
Looks great!

These properties can also be cleaned up: https://github.com/dotnet/runtime/blob/79b970739df6ff8d75ff7f4f262a8b2785c20940/Directory.Build.targets#L216-L227

**Comment by elinor-fung** [comment]
I think the only things still using those are the host packages (which I opted not to touch in this change). Most of those can be removed (and the remaining one switched to just used the product version) when we get to https://github.com/dotnet/runtime/issues/35244

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Pull request merged**
