### PR TITLE
Add profiler ELT test

### PR DESCRIPTION
**Pull request by davmason**
As mentioned in #39335 we currently have no ELT hook coverage in the runtime repo.

cc @AndyAyersMS

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Thanks! This will be interesting when run conjunction with gc stress. Should happen in our overnight testing, once this is merged.

**Comment by davmason** [comment]
There are some bugs in the runtime's slow path ELT assembly stubs on linux. Not surprising given that we haven't ever been testing them, I am going to go through and root cause them.

**Comment by davmason** [comment]
@noahfalk the remaining failures are an infrastructure issue, this is ready to review now

@AndyAyersMS do you or anyone else from the jit team want to take a look at the assembly stub changes I made? 

I found the following issues:

- On amd64 linux we didn't save and restore the xmm registers, and didn't handle enregistered 16 bytes structs as return values
- On arm we didn't save and restore the floating point registers (I made the linux arm helpers match the windows arm helpers)
- On arm64 we didn't handle 16 byte enregistered structs as return values

If there are other interesting corner cases to test, please let me know.

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib

**Comment by davmason** [comment]
@jashook this is the PR we talked about in standup, didn't realize you weren't part of the dotnet-diag group

**Comment by noahfalk** [comment]
> @jashook this is the PR we talked about in standup, didn't realize you weren't part of the dotnet-diag group

That is fixed now right or is there still an issue?

**Review by noahfalk — APPROVED** [review]
LGTM, though mostly I am relying on your test cases rather than my ability spot suspicious assembly code : )

As a broader issue if we've had these long standing bugs and nobody is complaining we should keep an eye out for feedback whether these APIs matter to the profiler authors. Its not clear to me that they do.

**Comment by davmason** [comment]
The CI legs marked as in progress are actually complete, going to merge.

**Pull request merged**
