### PR TITLE
Disable binary formatter tests when DotNetBuildSourceOnly.

### LINKED ISSUE #107534: BinaryFormatter tests are no longer skipped when ran against source-built runtime
When building runtime under the source-build configuration, no functional BinaryFormatter is being built.

Tests that require a functional binary formatter are skipped based on:

https://github.com/dotnet/runtime/blob/aa418fca02995ecfdfe64f89f040fb65ef38557a/src/libraries/System.ObjectModel/tests/ReadOnlyDictionary/ReadOnlyDictionary_SerializationTests.cs#L19

These tests are no longer being skipped on the `main` branch. This causes 1000s of test failures across different test projects.

@adamsitnik I suspect this regressed in https://github.com/dotnet/runtime/pull/106858 by removing the assembly version logic in `DetermineBinaryFormatterSupport`.

cc @ViktorHofer @omajid

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/dotnet/runtime/issues/107534.

@adamsitnik @am11 ptal.

cc @omajid

### CODE REVIEW

**Review by am11 — APPROVED** [review]
👍

**Review by adamsitnik — APPROVED** [review]
LGTM, thank you @tmds!

**Comment by adamsitnik** [comment]
@tmds please excuse me if this is a stupid question, but I need to backport this PR to 9.0 branch and want to make sure that it has actually solved the problem. What is the best way to test this build configuration?

**Comment by tmds** [comment]
In our CI, I see the test failures are gone now that this change was merged to `main`. Based on that, you don't need to validate this.

I've copied the following from one of our CI jobs, in case you'd like to run it yourself.
(You can leave out the `--cmakeargs` arguments.)

```
# build
./build.sh /p:NoPgoOptimize=true --portablebuild false /p:DotNetBuildFromSource=true /p:DotNetBuildSourceOnly=true /p:DotNetBuildTests=true --cmakeargs -DCLR_CMAKE_USE_SYSTEM_BROTLI=true --cmakeargs -DCLR_CMAKE_USE_SYSTEM_LIBUNWIND=true --cmakeargs -DCLR_CMAKE_USE_SYSTEM_RAPIDJSON=true --cmakeargs -DCLR_CMAKE_USE_SYSTEM_ZLIB=true --runtimeconfiguration Release --librariesConfiguration Debug --subset clr+libs+host+packs+libs.tests
# test
./build.sh --subset libs.tests --test /p:WithoutCategories=IgnoreForCI /p:NoPgoOptimize=true --portablebuild false /p:DotNetBuildFromSource=true /p:DotNetBuildSourceOnly=true /p:DotNetBuildTests=true --cmakeargs -DCLR_CMAKE_USE_SYSTEM_BROTLI=true --cmakeargs -DCLR_CMAKE_USE_SYSTEM_LIBUNWIND=true --cmakeargs -DCLR_CMAKE_USE_SYSTEM_RAPIDJSON=true --cmakeargs -DCLR_CMAKE_USE_SYSTEM_ZLIB=true --runtimeconfiguration Release --librariesConfiguration Debug
```

**Comment by adamsitnik** [comment]
@tmds thank you!

**Pull request merged**
