### PR TITLE
Don't call user operator for null check of HttpMethod value

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Review by ManickaP — APPROVED** [review]
LGTM

**Review by stephentoub — APPROVED** [review]
This is fine, but what's driving the change? Does this cause the operator to be linked away in wasm?

**Comment by marek-safar** [comment]
> what's driving the change

Simpler codegen, seems odd to me to call user operator for null check (I thought we had analyzer for that).

**Comment by stephentoub** [comment]
> Simpler codegen, seems odd to me to call user operator for null check (I thought we had analyzer for that).

Why this one? There are literally thousands in the code base.

**Comment by marek-safar** [comment]
> Why this one? There are literally thousands of == null in the code base, 

I was just looking at some traces from blazor/wasm samples and the fix is trivial. If you think we have thousands of cases where us calls user operator to for null check then it's really worth adding the analyzer rule

**Pull request merged**
