### PR TITLE
[release/7.0] [wasm][debugger] Don't escape accented letters

### PR DESCRIPTION
**Pull request by thaystg**
Backport of #78171 to release/7.0

/cc @thaystg

## Customer Impact
When the customer adds a breakpoint in a file that contains any special character like (swedish characters) and the breakpoint is hit, the file is not opened correctly on VS.

## Testing
Manually tested using a Blazor app, adding special characters in the folder, in the project name and in the source file name.

## Risk
Low risk, do not escape all the letters and not only the ones unaccented.

IMPORTANT: Is this backport for a servicing release? If so and this change touches code that ships in a NuGet package, please make certain that you have added any necessary [package authoring](https://github.com/dotnet/runtime/blob/main/docs/project/library-servicing.md) and gotten it explicitly reviewed.

### CODE REVIEW

**Comment by thaystg** [comment]
Please, do not merge.

**Review by radical — APPROVED** [review]
Changes look fine for 7.0 branch. @thaystg will explore using `Uri.EscapeDataString`, and friends to handle the escaping in follow up PRs.

**Comment by carlossanlop** [comment]
This was approved by Tactics via email and is signed off by area owner. No OOB package authoring changes needed for this.
I'm just waiting for the CI to finish before merging.

**Comment by carlossanlop** [comment]
Failures happened all in the installer legs, none seem related to this change (it's all network/infra issues).

**Pull request merged**
