### PR TITLE
Avoid integer overflow on ARM machine with 8G of memory

### LINKED ISSUE #65466: GetGCMemoryInfo.TotalAvailableMemoryBytes returns negative value on ARM32
### Description

`GC.GetGCMemoryInfo().TotalAvailableMemoryBytes` reports negative values on linux/ARM32.

The is issue was brought to our attention original with [ImageSharp Raspberry Pi OS 11 Issue](https://github.com/SixLabors/ImageSharp/issues/2001)

There was a similar Issue already reported here [issues/13115](https://github.com/dotnet/runtime/issues/13115), but this was closed.

The following simple code snippet triggers the issue:
```
Console.WriteLine("TotalAvailableMemoryBytes = " + GC.GetGCMemoryInfo().TotalAvailableMemoryBytes);
```

I tried the following official dotnet sdk images:

- mcr.microsoft.com/dotnet/sdk:6.0.102-bullseye-slim-arm32v7
- mcr.microsoft.com/dotnet/sdk:6.0.102-focal-arm32v7
- mcr.microsoft.com/dotnet/sdk:5.0.405-buster-slim-arm32v7

All report TotalAvailableMemoryBytes = -402354176

### Reproduction Steps

```
Console.WriteLine("TotalAvailableMemoryBytes = " + GC.GetGCMemoryInfo().TotalAvailableMemoryBytes);
```

### Expected behavior

Report a positive number of available bytes.

### Actual behavior

TotalAvailableMemoryBytes = -402354176

### Regression?

ARM64 does not seem to be affected.

.NET Core 3.1.416 does not seem to be affected (tried with docker image: `mcr.microsoft.com/dotnet/sdk:3.1.416-bullseye-arm32v7`)

### Known Workarounds

_No response_

### Configuration

- .NET version  6.0.102 and 5.0.405
- architecture: ARM32

### Other information

_No response_

### PR DESCRIPTION
**Pull request by cshung**
Fixes https://github.com/dotnet/runtime/issues/65466

On Raspberry Pi 4 model d03114, there is 8G of physical memory.

If we install the ARM dotnet SDK and run an application there, `GetGCMemoryInfo.TotalAvailableMemoryBytes` would return a negative number, and that is because we are hitting an integer overflow with the multiplication in this change.

Note that `sysconf` returns a `long` and that is a signed 32-bit number on ARM.

I confirmed that the negative value no longer repros on that machine, and it reports a number close to 8G.

### CODE REVIEW

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by jkotas** [comment]
Can you fix the same issue in the standalone GC PAL: https://github.com/dotnet/runtime/blob/2201016c1e13bdb9abf49e2e38cadf4ee0568df2/src/coreclr/gc/unix/gcenv.unix.cpp#L1232

**Comment by Maoni0** [comment]
wouldn't be better if we just used unsigned exclusively here? 

```cplusplus
uint64_t physical_memory;
// Get the Physical memory size
physical_memory = ((uint64_t)sysconf( _SC_PHYS_PAGES )) * ((uint64_t) sysconf( _SC_PAGE_SIZE ));
```

**Comment by jkotas** [comment]
Test failure tracked by #73299

**Pull request merged**
