### PR TITLE
#ifdef out code that requires FEATURE_EVENT_TRACE

### PR DESCRIPTION
**Pull request by yowl**
This PR follows #90847 and removes some more code when FEATURE_EVENT_TRACE is not defined.  Surfaced as part of https://github.com/dotnet/runtimelab/pull/2396

Not sure about the `gcrhenv.cpp` change.  Maybe I should be removing all the `DiagGC*` methods and `#ifdef`ing their usages ?

cc @EgorBo 

Thanks

### CODE REVIEW

**Comment by EgorBo** [comment]
LGTM, but leaving for @dotnet/gc to approve/merge

**Comment by yowl** [comment]
> We can also just remove the assert - it doesn't add a lot of value

I have no preference here.

**Comment by yowl** [comment]
Sorry I closed this by mistake.  

> for the changed related to the `FEATURE_EVENT_TRACE ifdef` checks in gc.cpp, why are only some removed but not all?

I've gone ahead and just removed the assert so `gc.cpp` only has that as a change.  @Maoni0 is there anything else I can answer or change here?  Thanks.

**Review by EgorBo — APPROVED** [review]
LGTM, but leaving for @dotnet/gc to review/merge

**Comment by mangod9** [comment]
@cshung, can you please review and merge?

**Comment by TheSpydog** [comment]
Is this fix going to be merged into a .NET 8.x release? For our game console ports of NativeAOT, we do not enable FEATURE_EVENT_TRACE, so we’re running into compile errors when upgrading our runtime support to .NET 8.

**Comment by jkotas** [comment]
We will take it for the consideration. We do not typically backport fixes for custom configuration like this one, but I think we can make an exception for this one given that it is a regression from .NET 7, it is shortly after release and the fix is very low risk.

**Pull request merged**
