### PR TITLE
[release/6.0] Fix stable builds for some transport packages

### PR DESCRIPTION
**Pull request by mmitche**
Some non-shipping transport and sources packages were getting incorrectly getting stable versions. This didn't show up in the servicing excercise, though they probably did the right thing for unrelated reasons. My guess is that a number of the .proj files that should not be stabilized used to be pkgproj files. The conditional only covered pkgproj.

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Review by Anipik — APPROVED** [review]

**Comment by mmitche** [comment]
@Anipik This doesn't fix the issue: https://dev.azure.com/dnceng/internal/_build/results?buildId=1430080&view=results. Can I hand this off to you?

**Comment by mmitche** [comment]
```
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : Package 'Microsoft.Extensions.HostFactoryResolver.Sources' has stable version '6.0.0' but is targeted at a non-isolated feed 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6-transport/nuget/v3/index.json'
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : Package 'Microsoft.Internal.Runtime.AspNetCore.Transport' has stable version '6.0.0' but is targeted at a non-isolated feed 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6-transport/nuget/v3/index.json'
D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\7.0.0-beta.21518.6\tools\SdkTasks\PublishArtifactsInManifest.proj(139,5): error : Package 'Microsoft.Internal.Runtime.WindowsDesktop.Transport' has stable version '6.0.0' but is targeted at a non-isolated feed 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6-transport/nuget/v3/index.json'
```

**Comment by Anipik** [comment]
found the issue. Fixing it, the problem was introduced here in stable rtm pr

**Review by ViktorHofer — APPROVED** [review]
I agree with your assessment and the clean-up looks right but at this point of the 6.0 release I would prefer a more targeted fix to reduce risk. Is that possible?

**Comment by safern** [comment]
> I agree with your assessment and the clean-up looks right but at this point of the 6.0 release I would prefer a more targeted fix to reduce risk. Is that possible?

Sure. I can just rename the property to be a "private" property and then do this cleanup on main.

**Review by ViktorHofer — APPROVED** [review]

**Comment by radical** [comment]
> I don't think we should include workloads-testing.targets on all of `src\libraries\Directory.Build.props` tree as those are only intended to install workloads for testing when sending to helix. Also these are only intended/needed for mobile testing, so I moved the import to `tests.mobile.targets` and also cleaned up a little bit how we set some properties.

Just fyi, we do use this when testing locally too, eg when running `Wasm.Build.Tests`. And currently this is used only by wasm, but it will likely get used for other mobile cases too - iOS/android etc.

**Review by radical — APPROVED** [review]

**Pull request merged**
