### PR TITLE
Add back fixed xunit decimal, IntPtr and UIntPtr commented test cases

### PR DESCRIPTION
**Pull request by joaonunomota**
Closes #27187

These tests were removed due to an issue in xunit that is now resolved on the latest version. The test projects are also on the latest xunit version, so all that is needed is to uncomment the marked tests.

### CODE REVIEW

**Comment by danmoseley** [comment]
Could you look at the build errors?

**Comment by joaonunomota** [comment]
@danmoseley Sorry! Looking at those now, putting this as a draft PR until I get that fixed.

**Comment by joaonunomota** [comment]
@danmoseley The failing tests are related to Native AOT deployments. I'm not familiar with this kind of deployment, but it seems odd that it only fails with the Decimal type.

Are these tests failing expected behavior or am I missing some Native AOT deployment specific configuration?

**Review by stephentoub — APPROVED** [review]
LGTM when CI is happy

**Comment by danmoseley** [comment]
```
[SKIP] System.Reflection.Tests.MethodBaseTests.TestMethodBody
[FAIL] System.Reflection.Tests.InvokeRefReturnNetcoreTests.TestNullRefReturnInvoke
System.NotSupportedException : 'System.Reflection.Tests.InvokeRefReturnNetcoreTests.TestNullRefReturnInvoke[System.Decimal](System.Decimal)' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x30
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.MakeGenericMethod(Type[]) + 0x1c4
[FAIL] System.Reflection.Tests.InvokeRefReturnNetcoreTests.TestRefReturnPropertyGetValue
System.NotSupportedException : 'System.Reflection.Tests.InvokeRefReturnNetcoreTests.TestRefReturnPropertyGetValue[System.Decimal](System.Decimal)' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x30
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.MakeGenericMethod(Type[]) + 0x1c4
[FAIL] System.Reflection.Tests.InvokeRefReturnNetcoreTests.TestRefReturnMethodInvoke
System.NotSupportedException : 'System.Reflection.Tests.InvokeRefReturnNetcoreTests.TestRefReturnMethodInvoke[System.Decimal](System.Decimal)' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x30
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.MakeGenericMethod(Type[]) + 0x1c4
[SKIP] System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod
```

**Comment by danmoseley** [comment]
I pushed a change that will likely fix it, but I didn't attempt to test. we'll see.

**Comment by danmoseley** [comment]
@joaonunomota I should be able to merge tomorrow. Thanks for your first contribution! Are you interested in another? We have quite a few issues marked "help wanted" and also a fair number marked "api-approved" that would be adding a new API to .NET. You are welcome to grab any not already assigned.

**Comment by joaonunomota** [comment]
@danmoseley Thank you for all the help! I'll have a look through those other issues

**Comment by danmoseley** [comment]
@dotnet/dnceng a variety of flavors ran over 4 hours here and timed out. this is the 2nd time around. is there a known issue -- does this mean low capacity, or slow machines?

**Comment by danmoseley** [comment]
@stephentoub Any thoughts about above stack?

**Comment by danmoseley** [comment]
Thanks. I'll not open an issue since it's not actionable -- with your assert, it will be next time.

**Pull request merged**
