### PR TITLE
Fix typo in ComInterfaceInfo.OptionsAreValid

### PR DESCRIPTION
**Pull request by omajid**
We want to check the derived type has the same wrapper as the base type. But the code seems to have a copy-paste or typo error where it checks the derived type wrapper against a different base type wrapper.

### CODE REVIEW

**Comment by omajid** [comment]
cc @jtschuster @jkoritzinsky

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
Can we add a test for this?

**Comment by omajid** [comment]
I can't seem to find an existing test case exercising this class directly.

I will try and write something from scratch, but I am not familiar with the code, so it might take me some time.

**Comment by jtschuster** [comment]
Here's some info about our generator tests if it helps:

The tests we have that validate if snippets compile with/without warnings are in `ComInterfaceGenerator.Unit.Tests.csproj`

You can put snippets in [CodeSnippets.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime.InteropServices/tests/ComInterfaceGenerator.Unit.Tests/CodeSnippets.cs). The notation `{|#1:identifierWithWarning|}` indicates where an error or warning should be reported by the generator, for example, [here](https://github.com/dotnet/runtime/blob/839dac9c71cb179a3101092876ad194bc9ac2c95/src/libraries/System.Runtime.InteropServices/tests/ComInterfaceGenerator.Unit.Tests/CodeSnippets.cs#L244C77-L244C89) warnings are expected on the method name and parameters.

Then, add the snippets that should compile without warnings to [ComInterfaceSnippetsToCompile](https://github.com/dotnet/runtime/blob/839dac9c71cb179a3101092876ad194bc9ac2c95/src/libraries/System.Runtime.InteropServices/tests/ComInterfaceGenerator.Unit.Tests/Compiles.cs#L334) in Compiles.cs. The ones that should have warnings/errors should go in the [ComInterfaceGeneratorSnippetsToCompile](https://github.com/dotnet/runtime/blob/839dac9c71cb179a3101092876ad194bc9ac2c95/src/libraries/System.Runtime.InteropServices/tests/ComInterfaceGenerator.Unit.Tests/CompileFails.cs#L24) in CompileFails.cs method with their expected diagnostics.

Thank you!

**Review by jtschuster — APPROVED** [review]

**Review by agocke — APPROVED** [review]

**Pull request merged**
