### PR TITLE
Fix r4 r8 format numbers

### PR DESCRIPTION
**Pull request by ilonatommy**
AssignmentTests.InspectVariableBeforeAndAfterAssignment for MONO_TYPE_R4 and MONO_TYPE_R8 failed on some cultures where decimal separator is a comma, not a dot. This change fixes it. Separated from PR: https://github.com/dotnet/runtime/pull/66821#discussion_r831416997 and should be merged **only** after that PR.

Reason: we are passing double/float without type change into JSON, so it preserves dot in every culture. We are passing description as a string, converting double/float to string before passing to JSON. This makes description vary from culture to culture.
Then, in tests we have this method overriding:
```
internal static JObject TNumber(string value)
```
where we pass string as a description, without editing it according to culture.

Failed tests:
```
DebuggerTests.AssignmentTests.InspectVariableBeforeAndAfterAssignment(clazz: "MONO_TYPE_R4", checkDefault: [[[...]], [[...]], [[...]]], checkValue: [[[...]], [[...]], [[...]]]) [FAIL]
DebuggerTests.AssignmentTests.InspectVariableBeforeAndAfterAssignment(clazz: "MONO_TYPE_R8", checkDefault: [[[...]], [[...]], [[...]]], checkValue: [[[...]], [[...]], [[...]]]) [FAIL]
```

Failure description:
```
Expected: 3.1415
Actual:   3,1415 
Expected: {
  "type": "number",
  "value": "3.1415",
  "description": "3.1415"
} 
Actual: {
  "type": "number",
  "value": 3.1415,
  "description": "3,1415"
}
  Failed DebuggerTests.AssignmentTests.InspectVariableBeforeAndAfterAssignment(clazz: "MONO_TYPE_R4", checkDefault: [[[...]], [[...]], [[...]]], checkValue: [[[...]], [[...]], [[...]]]) [142 ms]
  Error Message:
   [[r] Value for json property named description didn't match.]

Expected: 3.1415
Actual:   3,1415
```

Fix:
Leave the method with string as param but assume all strings passed there will be in InvariantCulture double format. Then, first cast the string to double and afterwards, using current culture - back to string. It will eliminate inconsistency between Debugger and Tests while preserving description consistent with machine's culture.

### CODE REVIEW

**Comment by radical** [comment]
Can you add what the failure looks like, in the PR description?

**Comment by radical** [comment]
I think the test should be fixed for this. I would expect the proxy to honor the culture so the user would see the expected format. What do you think?

**Comment by ilonatommy** [comment]
Actually yes, that it a better solution I think. I will just check if normal Console App respects it as well as we are trying to mirror its behavior.

**Comment by ilonatommy** [comment]
Console App does not really care and displays always dot for these values. We can do it better than its solved there and I'll add info in the description that we agreed on different behavior.

**Review by thaystg — APPROVED** [review]

**Pull request merged**
