### PR TITLE
[mono] Adding osx-arm64 Mono Interpreter runtime tests job to extra-platforms

### PR DESCRIPTION
**Pull request by matouskozak**
# Description
This PR adds osx-arm64 Mono interpreter runtime tests job to `runtime-extra-platforms`.

- The full job takes ~1h 27min with ~8min spent running the tests on Helix.
- One failing test was discovered by this job (https://github.com/dotnet/runtime/issues/96051).

# Motivation
Currently, we have coverage for Mono on osx-x64 (miniJIT and interpreter) as part of `runtime` CI job but we are lacking coverage over arm64 for Apple platforms. We have Mono jobs running on Apple arm64 (`ios/tvos_arm64_AllSubsets_Mono_RuntimeTests`) but these are running very limited set of runtime tests (https://github.com/dotnet/runtime/issues/84254). We need this coverage for testing Swift Interop support.

Until we have sufficient coverage over runtime tests for Apple arm64 mobile platforms it would be good to have at least some coverage for Apple arm64.

### CODE REVIEW

**Review by kotlarmilos — APPROVED** [review]

**Comment by SamMonoRT** [comment]
@steveisok - do we need approval from any infra folks for this PR?

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
>  do we need approval from any infra folks for this PR?

I don't think so, the additional job targets osx_arm64 and we usually have enough capacity there.

**Pull request merged**
