### PR TITLE
Take into account the provided format in Utf8Parser.TryParse for bool

### LINKED ISSUE #100659: Utf8Parser.TryParse ignores the provided format for bool
### Description

The current implementation of `Utf8Parser.TryParse` for bool ignores the format:

https://github.com/dotnet/runtime/blob/beac27479b402391a7cc04e207bf54ed20803c49/src/libraries/System.Private.CoreLib/src/System/Buffers/Text/Utf8Parser/Utf8Parser.Boolean.cs#L29-L58

### Reproduction Steps

```cs
byte[] bytes = Encoding.UTF8.GetBytes("true");
var result = Utf8Parser.TryParse(bytes, out DateTime value, out int byteConsumed, standardFormat: 'G');
Console.WriteLine(result);
```

### Expected behavior

`result` should be `false` because for the format `G`, `True` or `False` beginning with uppercase should be expected.

### Actual behavior

`result` is `true`.

### Regression?

I don't think so. In dotnet/corefx, the implementation already didn't take the format into account.

### Known Workarounds

_No response_

### Configuration

9.0.0-preview.2.24128.5

### Other information

_No response_

### PR DESCRIPTION
**Pull request by ghost**
Fixes #100659.
I couldn't find any existing unit tests for this class but I'd be happy to add/update them if anyone can give me a hint.

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks for the issue and fix.

I'm not sure we should take this, though. It's been this way for a very long time, and there could easily be code relying on both casings being parsed.

Can you elaborate on in what situation it's breaking you that TryParse allows for additional casings to be parsed successfully?

**Comment by joegoldman2** [comment]
Thank you for your feedback.

To be honest, I don't have a scenario in mind and I saw the "issue" when reading the code. I'm fine with keeping the current implementation, which allows parsing regardless of the case sensitivity.

**Comment by stephentoub** [comment]
Thanks. Personally, I'd be more inclined to "fix" the comment in the source as well as the docs, to make them match the long-standing behavior.  But I'll leave that up to the area owners. @dotnet/area-system-buffers ?

**Comment by tannergooding** [comment]
I'd like weigh in from @GrabYourPitchforks since he was involved in getting this all supported in the first place.

I think this is overall less important if we just update `System.Boolean` to implement `IUtf8SpanParsable` and `IUtf8SpanFormattable. There are a number of existing quirks/oddities with the Utf8Parser/Utf8Formatter types and we opted not to "fix" those either.

**Comment by joegoldman2** [comment]
@GrabYourPitchforks could you please share your thoughts?

**Comment by joegoldman2** [comment]
Closing in favor of #103861.

**Pull request closed without merging**
