### PR TITLE
Improve atomic type detection in ConcurrentDictionary

### PR DESCRIPTION
**Pull request by ts2do**
This change supports checking any value type provided in TValue for direct write capability (including small Nullable<> types), avoiding allocation of a new Node.

### CODE REVIEW

**Comment by jkotas** [comment]
This is not a valid change. Non-primitive types are not guaranteed to be read/written atomically, even if they fit into a pointer size.

**Comment by ts2do** [comment]
OK

**Comment by ts2do** [comment]
I'm guessing this is related to potential alignment issues that are otherwise guaranteed by primitives. I'm curious whether there is a change that could be made here to improve it. Perhaps also ensuring the alignment of _value in Node would make this change correct?

**Comment by jkotas** [comment]
This goes much deeper than just the alignment. The JIT compiler is not guaranteed to load non-primitive types atomically.

**Comment by ts2do** [comment]
Right; thanks for the insight. This check only affects writing to Node._value from an argument. Is stfld also lacking this guarantee?

**Comment by jkotas** [comment]
Yes.

**Comment by ts2do** [comment]
Right... and even if it wasn't, it could affect a concurrent read.

**Pull request closed without merging**
