### PR TITLE
[release/5.0] Don't rev the platforms package unless we ship it

### PR DESCRIPTION
**Pull request by ericstj**
We should technically pin more here, similar to https://github.com/dotnet/runtime/pull/46447, but just doing the minimal in servicing to unblock https://github.com/dotnet/runtime/pull/46598 and https://github.com/dotnet/runtime/pull/46590

This is infra only change so should be mergeable on review.

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Comment by ericstj** [comment]
Mono test failure is https://github.com/dotnet/runtime/issues/43981

**Comment by ericstj** [comment]
I think we should wait to merge this until @Anipik comes back.  Branch is locked right now for 5.0.2 release.

**Review by Anipik — APPROVED** [review]

**Comment by Anipik** [comment]
> I think we should wait to merge this until @Anipik comes back. Branch is locked right now for 5.0.2 release

Branch will be opened tomorrow for the new changes.

**Comment by Anipik** [comment]
@ericstj can we close this one as this change is included in eventlog pr as well

**Comment by ericstj** [comment]
Sure we can close this if we merged the other PRs which cherry-picked it.

**Pull request closed without merging**
