### PR TITLE
[wasm] Use compile rsp instead of link, for compiling native files

### PR DESCRIPTION
**Pull request by radical**
.. and fix logging that broke recently.

`tasks/Common/Utils.cs`:

`TaskLoggingHelper Utils.Logger` is a static field, which must be set by
task else any methods in `Utils`, eg. `RunProcess`, silently fail to log
any messages. Also, this would be a problem when building multiple
projects in parallel, since the logger is a task-specific one.

Instead, we pass logger as an arg to all the methods.

### CODE REVIEW

**Review by lewing — APPROVED** [review]
I don't really like putting the logger first or how many arguments the helpers are accumulating but the changes fix real issues and the code is all part of the tests.

**Comment by radical** [comment]
I want to clean it up, but because the iOS/android tasks also use these, I have tried to only add stuff. I will clean it up over time, with future changes.

**Comment by radical** [comment]
`Linux x64` test failure - `System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.SendMoreThanStreamLimitRequestsConcurrently_LastWaits(streamLimit: 10)` might be https://github.com/dotnet/runtime/issues/53688 .

**Comment by radical** [comment]
Test failure is unrelated to this PR, as mentioned in the last comment.

**Pull request merged**
