### PR TITLE
Remove a number of unneeded nullability suppressions.

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Even though all generic `JsonSerializer.Serialize*` methods support serializing `null` values, this is not reflected in the current nullability annotation.

### CODE REVIEW

**Comment by tarekgh** [comment]
>             return WriteDocument(value, jsonTypeInfo);

I assume such methods including jsonTypeInfo.Serialize handle null values correctly. right?

---
Refers to: src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.Document.cs:76 in 61c4059. [](commit_id = 61c40591429e01944f64120000bd71eb0db08caa, deletion_comment = False)

**Review by tarekgh — APPROVED** [review]

**Comment by stephentoub** [comment]
I don't think this change is desirable (it's also something we've discussed and dismissed in the past). By using a non-nullable T, the developer has specified that null is not valid in their domain of values. Even if the serializer can handle it, but using a non-nullable T instead of a nullable T, they've effectively asked for warnings is null might be passed in.

**Comment by eiriktsarpalis** [comment]
> I assume such methods including jsonTypeInfo.Serialize handle null values correctly. right?

Correct, ultimately all methods flow to the internal `JsonConverter.TryWrite` method:

https://github.com/dotnet/runtime/blob/b7c4ad80a32cdbcd2f87c20e5c7368c4043b02e4/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L368-L374

**Comment by eiriktsarpalis** [comment]
> I don't think this change is desirable (it's also something we've discussed and dismissed in the past).

If you're refering to https://github.com/dotnet/runtime/issues/56645, the reason we made the `JsonConverter<T>.Write` method agnostic is that nullability depends on whether the converter in question overrides the [`HandleNull` property](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconverter-1.handlenull?view=net-7.0). This concern doesn't apply for the case of the `JsonSerializer` methods, null values are guaranteed to work for all types and configurations.

>  the developer has specified that null is not valid in their domain of values.

My motivation for making the change stems from the following scenario:

```C#
static string Test(MyPoco? value) =>
    JsonSerializer.Serialize(value, MyContext.Default.MyPoco);

public record MyPoco(int x, int y);

[JsonSerializable(typeof(MyPoco))]
public partial class MyContext : JsonSerializerContext { }
```
Becauce the source generator only produces metadata for non-nullable types, this will produce the following warning:
```
Argument of type 'JsonTypeInfo<MyPoco>' cannot be used for parameter 'jsonTypeInfo' of type 'JsonTypeInfo<MyPoco?>' in 'string JsonSerializer.Serialize<MyPoco?>(MyPoco? value, JsonTypeInfo<MyPoco?> jsonTypeInfo)' due to differences in the nullability of reference types.
```

**Comment by stephentoub** [comment]
> If you're refering to https://github.com/dotnet/runtime/issues/56645

I'm not.  I'm referring to discussions when Json was originally annotated, as well as in discussions for other similar cases, like those I mentioned.

> Becauce the source generator only produces metadata for non-nullable types, this will produce the following warning:

This is a bug in a source generator, then.  The developer is explicitly using a nullable type `MyPoco?`:
```C#
static string Test(MyPoco? value) =>
    JsonSerializer.Serialize(value, MyContext.Default.MyPoco);
```
They've opted-in to having null be valid in their domain.

**Comment by eiriktsarpalis** [comment]
> This is a bug in the source generator, then.

`typeof(MyPoco?)` is not a valid expression, so it wouldn't be possible for the source generator to produce properties of type `JsonTypeInfo<MyPoco?>` without changes to API.

> The developer is explicitly using a nullable type MyPoco?:

> They've opted-in to having null be valid in their domain.

I would argue that the boundaries of a domain model should not be enforced by the type signature of a general-purpose piece of infrastructure such as a serializer. At this layer I think it is more important that the annotation accurately reflects the runtime behavior of the implementation.

**Comment by stephentoub** [comment]
> At this layer I think it is more important that the annotation accurately reflects the runtime behavior of the implementation.

That's not the path we've taken.  There are many places where nulls are tolerated by the implementation but we still adhere to the typing the developer supplied.  Even something as fundamental as `List<T>.Contains(T)`.  `Contains` is fine if you pass null, but we've not typed that as `T?` because it violates the semantics the developer specified.

**Comment by eiriktsarpalis** [comment]
How about we specifically make the `JsonTypeInfo<T>` parameters annotation agnostic?
```C#
public static string Serialize<T>(
    T value,
#nullable disable
    JsonTypeInfo<T> typeInfo
#nullable enable
);
```
I believe this should address the SG usability issue while still validating nullability of `value` w.r.t. the type argument.

**Comment by stephentoub** [comment]
I think that's reasonable.

**Comment by eiriktsarpalis** [comment]
I ended up reverting changes to public API, since all the `#nullable` directives ended up messing up the format of the reference source file in too many places, which was adding complexity disproportionate to the problem I was attempting to address.

I'm re-purposing this PR to one that removes a number of unnecessary suppressions from the internal implementation.

**Comment by stephentoub** [comment]
> since all the #nullable directives ended up messing up the format of the reference source file in too many places, which was adding complexity disproportionate to the problem I was attempting to address

I thought your follow-up solution was fine. Do you want to try again after this PR? I wouldn't expect the impact on the refs to be too problematic.

**Pull request merged**
