### PR TITLE
Change Environment.OSVersion to use RtlGetVersion

### LINKED ISSUE #33643: Change Environment.OSVersion to return actual OS version on Windows
`Environment.OSVersion` returns quirked OS version from app manifest on Windows. Consider changing it to return the actual OS version. It's not the recommended solution, but so many times I've seen folks say that Environment.OSVersion is buggy and then go and just do the P/Invoke themselves (or parse some other string-based representation that's doing it).

Related:
- https://github.com/dotnet/designs/pull/97#discussion_r393169688
- https://github.com/dotnet/runtime/issues/32575

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/33643
cc: @jkotas, @GrabYourPitchforks

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Review by GrabYourPitchforks — APPROVED** [review]

**Comment by stephentoub** [comment]
@davidsh, what is the breaking change concern here? We're worried someone is relying on this returning the wrong version?

**Comment by davidsh** [comment]
>@davidsh, what is the breaking change concern here? We're worried someone is relying on this returning the wrong version

Yes. It's quite possible that someone is using Environment.OSVersion and it will be unexpected to suddenly get different values after upgrading to .NET 5. So, at the very least, this breaking change needs to be documented as such.

**Comment by davidsh** [comment]
@karelz @danmosemsft

**Comment by scalablecory** [comment]
`GetVersionEx` lies to allow forward-compat with apps doing broken version detection. Do we believe `Environment.OSVersion` is used differently enough that we would avoid the same issue? May want to reach out to Windows team for data.

**Comment by stephentoub** [comment]
`dotnet.exe` is manifested to support Windows 10, so if someone is using `dotnet app.dll` or `dotnet run`, Environment.OSVersion is already going to return the same value this will.  Same goes if they've added an appropriate manifest to their app.

I believe your concerns are the same as David's, and as this is a major release of .NET, even if it is technically breaking, I think it's the right trade-off.

A ton of code is doing its own P/Invoke to get a better version, since the version that Environment.OSVersion returns is often either wrong or inconsistent based on how the app is run.  We already use RtlGetVersion in RuntimeInformation:
https://github.com/dotnet/runtime/blob/0d19a5e18a988ad52ca0c2907edeb40ba4e00d9b/src/libraries/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.Windows.cs#L22
.NET Framework's mscorlib uses it:
https://referencesource.microsoft.com/#mscorlib/microsoft/win32/win32native.cs,2798
Windows Forms uses it:
https://github.com/dotnet/winforms/blob/084afd290719163557de1b78d85ade45c3aa0e59/src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/OsVersion.cs#L19
A bazillion uses of it show up in arbitrary code on GitHub:
https://github.com/search?l=C%23&q=RtlGetVersion&type=Code
Even our public samples use it:
https://github.com/dotnet/aspnetcore/blob/37399bc2175cc253e83bd2d7b2a66e613daad38a/src/MusicStore/samples/MusicStore/Platform.cs#L43
I think it's much better if we just fix Environment.OSVersion to actually be meaningful.

**Comment by ericstj** [comment]
@stephentoub can you please file a breaking change doc? https://github.com/dotnet/docs/issues/new?template=dotnet-breaking-change.md

**Comment by stephentoub** [comment]
> can you please file a breaking change doc?

Going through my backlog from while I was out, and I see you already took care of this in https://github.com/dotnet/docs/issues/19684.  Thanks.

**Pull request merged**
