### PR TITLE
JIT: Split trees containing no-return calls to avoid creating illegal IR

### LINKED ISSUE #103853: Assert in InsertPInvokeMethodEpilog
When running Libraries tests with GC stress, I see once in a while assert in 

```c
    // Method doing PInvoke calls has exactly one return block unless it has "jmp" or tail calls.
    assert(returnBB->KindIs(BBJ_RETURN) || returnBB->endsWithTailCallOrJmp(comp));

```

Possibly just assert is too strong. 
The `returnBB` is `BBJ_THROW` in this case.

Happens when running "Microsoft.Extensions.DependencyInjection.ExternalContainers.Tests.dll", in `DryIoc.ReflectionFactory.GetClosedTypeArgsOrNullForOpenGenericType`, but may happen in other cases too.

```
 	KernelBase.dll!RaiseFailFastException()	Unknown
 	coreclr.dll!_DbgBreakCheck(const char * szFile, int iLine, const char * szExpr, int fConstrained) Line 291	C++
 	coreclr.dll!CEEInfo::doAssert(const char * szFile, int iLine, const char * szExpr) Line 10448	C++
 	clrjit.dll!assertAbort(const char * why, const char * file, unsigned int line) Line 286	C++
>	clrjit.dll!Lowering::InsertPInvokeMethodEpilog(BasicBlock * returnBB, GenTree * lastExpr) Line 5710	C++
 	clrjit.dll!Lowering::LowerRet(GenTreeOp * ret) Line 4626	C++
 	clrjit.dll!Lowering::LowerNode(GenTree * node) Line 525	C++
 	[Inline Frame] clrjit.dll!Lowering::LowerBlock(BasicBlock *) Line 7763	C++
 	clrjit.dll!Lowering::DoPhase() Line 7531	C++
 	clrjit.dll!Phase::Run() Line 62	C++
 	clrjit.dll!Compiler::compCompile(void * * methodCodePtr, unsigned int * methodCodeSize, JitFlags * compileFlags) Line 5322	C++
 	clrjit.dll!Compiler::compCompileHelper(CORINFO_MODULE_STRUCT_ * classPtr, ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, void * * methodCodePtr, unsigned int * methodCodeSize, JitFlags * compileFlags) Line 7420	C++
 	[Inline Frame] clrjit.dll!Compiler::compCompile::__l170::__Body::Run(Compiler::compCompile::__l2::__JITParam *) Line 6553	C++
 	clrjit.dll!Compiler::compCompile(CORINFO_MODULE_STRUCT_ * classPtr, void * * methodCodePtr, unsigned int * methodCodeSize, JitFlags * compileFlags) Line 6557	C++
 	[Inline Frame] clrjit.dll!jitNativeCode::__l8::__Body::Run::__l6::__Body::Run(jitNativeCode::__l8::__Body::Run::__l5::__JITParam *) Line 8056	C++
 	clrjit.dll!`jitNativeCode'::`8'::__Body::Run(jitNativeCode::__l2::__JITParam * __JITpParam) Line 8059	C++
 	clrjit.dll!jitNativeCode(CORINFO_METHOD_STRUCT_ * methodHnd, CORINFO_MODULE_STRUCT_ * classPtr, ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, void * * methodCodePtr, unsigned int * methodCodeSize, JitFlags * compileFlags, void * inlineInfoPtr) Line 8083	C++
 	clrjit.dll!CILJit::compileMethod(ICorJitInfo * compHnd, CORINFO_METHOD_INFO * methodInfo, unsigned int flags, unsigned char * * entryAddress, unsigned int * nativeSizeOfCode) Line 294	C++
 	[Inline Frame] coreclr.dll!invokeCompileMethodHelper(EEJitManager *) Line 12403	C++
 	coreclr.dll!invokeCompileMethod(EEJitManager * jitMgr, CEEInfo * comp, CORINFO_METHOD_INFO * info, CORJIT_FLAGS jitFlags, unsigned char * * nativeEntry, unsigned int * nativeSizeOfCode) Line 12466	C++
 	coreclr.dll!UnsafeJitFunction(PrepareCodeConfig * config, COR_ILMETHOD_DECODER * ILHeader, CORJIT_FLAGS * pJitFlags, unsigned long * pSizeOfCode) Line 12910	C++
 	coreclr.dll!MethodDesc::JitCompileCodeLocked(PrepareCodeConfig * pConfig, COR_ILMETHOD_DECODER * pilHeader, ListLockEntryBase<NativeCodeVersion> * pEntry, unsigned long * pSizeOfCode) Line 939	C++
 	coreclr.dll!MethodDesc::JitCompileCodeLockedEventWrapper(PrepareCodeConfig * pConfig, ListLockEntryBase<NativeCodeVersion> * pEntry) Line 820	C++
 	coreclr.dll!MethodDesc::JitCompileCode(PrepareCodeConfig * pConfig) Line 707	C++
 	coreclr.dll!MethodDesc::PrepareILBasedCode(PrepareCodeConfig * pConfig) Line 433	C++
 	coreclr.dll!MethodDesc::PrepareCode(PrepareCodeConfig * pConfig) Line 321	C++
 	coreclr.dll!TieredCompilationManager::CompileCodeVersion(NativeCodeVersion nativeCodeVersion) Line 958	C++
 	coreclr.dll!TieredCompilationManager::OptimizeMethod(NativeCodeVersion nativeCodeVersion) Line 935	C++
 	coreclr.dll!TieredCompilationManager::DoBackgroundWork(unsigned __int64 * workDurationTicksRef, unsigned __int64 minWorkDurationTicks, unsigned __int64 maxWorkDurationTicks) Line 821	C++
 	coreclr.dll!TieredCompilationManager::BackgroundWorkerStart() Line 533	C++
 	coreclr.dll!TieredCompilationManager::BackgroundWorkerBootstrapper1(void * __formal) Line 482	C++
 	coreclr.dll!ManagedThreadBase_DispatchInner(ManagedThreadCallState * pCallState) Line 7129	C++
 	coreclr.dll!ManagedThreadBase_DispatchMiddle(ManagedThreadCallState * pCallState) Line 7173	C++
 	coreclr.dll!``ManagedThreadBase_DispatchOuter'::`11'::__Body::Run'::`5'::__Body::Run(Param * pParam) Line 7331	C++
 	coreclr.dll!`ManagedThreadBase_DispatchOuter'::`11'::__Body::Run(ManagedThreadBase_DispatchOuter::__l2::TryArgs * pArgs) Line 7333	C++
 	coreclr.dll!ManagedThreadBase_DispatchOuter(ManagedThreadCallState * pCallState) Line 7353	C++
 	coreclr.dll!ManagedThreadBase_FullTransition(void(*)(void *) pTarget, void * args, UnhandledExceptionLocation filterType) Line 7377	C++
 	coreclr.dll!TieredCompilationManager::BackgroundWorkerBootstrapper0(void * args) Line 465	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

```

### PR DESCRIPTION
**Pull request by jakobbotsch**
When morph sees a no-return call it will remove all statements executed after that no-return call in the block, and convert the block into a `BBJ_THROW` block. However, morph was leaving trees executed after the no-return call in place, which could end up producing illegal IR. For example, if the ancestor node of the call is a `GT_RETURN` node we would end up with a `GT_RETURN` node inside a non-`BBJ_RETURN` block, which is not legal.

This change adds a function to split out all side effects of (ancestor) sibling nodes of the no-return call into separate statements. Once this has been done the no-return call can safely be made the root node of the statement.

Fix #103853

Example diff in JITDUMP for

```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
public static int Test(C x, C y)
{
    return x.X + (y.X / x.X - Throw());
}

private static int Throw()
{
    throw new Exception("foo");
}

public class C
{
    public int X;
}
```

```diff
@@ -1,51 +1,75 @@
 fgMorphTree BB01, STMT00003 (after)
                [000018] --CXG+-----                         ▌  RETURN    int
                [000017] --CXG+-----                         └──▌  ADD       int
                [000002] ---XG+-----                            ├──▌  IND       int
                [000021] -----+-----                            │  └──▌  ADD       byref
                [000000] -----+-----                            │     ├──▌  LCL_VAR   ref    V00 arg0
                [000020] -----+-----                            │     └──▌  CNS_INT   long   8 Fseq[X]
                [000016] --CXG+-----                            └──▌  SUB       int
                [000009] ---XG+-----                               ├──▌  DIV       int
                [000005] ---XG+-----                               │  ├──▌  IND       int
                [000023] -----+-----                               │  │  └──▌  ADD       byref
                [000003] -----+-----                               │  │     ├──▌  LCL_VAR   ref    V01 arg1          (last use)
                [000022] -----+-----                               │  │     └──▌  CNS_INT   long   8 Fseq[X]
                [000008] ---XG+-----                               │  └──▌  IND       int
                [000025] -----+-----                               │     └──▌  ADD       byref
                [000006] -----+-----                               │        ├──▌  LCL_VAR   ref    V00 arg0          (last use)
                [000024] -----+-----                               │        └──▌  CNS_INT   long   8 Fseq[X]
                [000010] --CXG+-----                               └──▌  CALL      int    Example:Throw():int
+Removing trees after no-return call [000010]
+Extracting side effects of (ancestor) sibling [000002]:
+STMT00004 ( ??? ... ??? )
+               [000002] ---XG+-----                         ▌  IND       int
+               [000021] -----+-----                         └──▌  ADD       byref
+               [000000] -----+-----                            ├──▌  LCL_VAR   ref    V00 arg0
+               [000020] -----+-----                            └──▌  CNS_INT   long   8 Fseq[X]
+Extracting side effects of (ancestor) sibling [000009]:
+STMT00005 ( ??? ... ??? )
+               [000009] ---XG+-----                         ▌  DIV       int
+               [000005] ---XG+-----                         ├──▌  IND       int
+               [000023] -----+-----                         │  └──▌  ADD       byref
+               [000003] -----+-----                         │     ├──▌  LCL_VAR   ref    V01 arg1          (last use)
+               [000022] -----+-----                         │     └──▌  CNS_INT   long   8 Fseq[X]
+               [000008] ---XG+-----                         └──▌  IND       int
+               [000025] -----+-----                            └──▌  ADD       byref
+               [000006] -----+-----                               ├──▌  LCL_VAR   ref    V00 arg0          (last use)
+               [000024] -----+-----                               └──▌  CNS_INT   long   8 Fseq[X]
+New final statement:
+STMT00003 ( ??? ... ??? )
+               [000010] --CXG+-----                         ▌  CALL      int    Example:Throw():int
 Converting BB01 to BBJ_THROW
 morph assertion stats: 64 table size, 2 assertions, 0 dropped

 *************** Finishing PHASE Morph - Global
 Trees after Morph - Global

 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 BBnum BBid ref try hnd preds           weight   [IL range]   [jump]                            [EH region]        [flags]
 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 BB01 [0000]  1                             0    [000..01B)                           (throw )                     i rare hascall gcsafe
 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------

 ------------ BB01 [0000] [000..01B) (throw), preds={} succs={}

+***** BB01 [0000]
+STMT00004 ( ??? ... ??? )
+               [000002] ---XG+-----                         ▌  IND       int
+               [000021] -----+-----                         └──▌  ADD       byref
+               [000000] -----+-----                            ├──▌  LCL_VAR   ref    V00 arg0
+               [000020] -----+-----                            └──▌  CNS_INT   long   8 Fseq[X]
+
+***** BB01 [0000]
+STMT00005 ( ??? ... ??? )
+               [000009] ---XG+-----                         ▌  DIV       int
+               [000005] ---XG+-----                         ├──▌  IND       int
+               [000023] -----+-----                         │  └──▌  ADD       byref
+               [000003] -----+-----                         │     ├──▌  LCL_VAR   ref    V01 arg1          (last use)
+               [000022] -----+-----                         │     └──▌  CNS_INT   long   8 Fseq[X]
+               [000008] ---XG+-----                         └──▌  IND       int
+               [000025] -----+-----                            └──▌  ADD       byref
+               [000006] -----+-----                               ├──▌  LCL_VAR   ref    V00 arg0          (last use)
+               [000024] -----+-----                               └──▌  CNS_INT   long   8 Fseq[X]
+
 ***** BB01 [0000]
 STMT00003 ( ??? ... ??? )
-               [000018] --CXG+-----                         ▌  RETURN    int
-               [000017] --CXG+-----                         └──▌  ADD       int
-               [000002] ---XG+-----                            ├──▌  IND       int
-               [000021] -----+-----                            │  └──▌  ADD       byref
-               [000000] -----+-----                            │     ├──▌  LCL_VAR   ref    V00 arg0
-               [000020] -----+-----                            │     └──▌  CNS_INT   long   8 Fseq[X]
-               [000016] --CXG+-----                            └──▌  SUB       int
-               [000009] ---XG+-----                               ├──▌  DIV       int
-               [000005] ---XG+-----                               │  ├──▌  IND       int
-               [000023] -----+-----                               │  │  └──▌  ADD       byref
-               [000003] -----+-----                               │  │     ├──▌  LCL_VAR   ref    V01 arg1          (last use)
-               [000022] -----+-----                               │  │     └──▌  CNS_INT   long   8 Fseq[X]
-               [000008] ---XG+-----                               │  └──▌  IND       int
-               [000025] -----+-----                               │     └──▌  ADD       byref
-               [000006] -----+-----                               │        ├──▌  LCL_VAR   ref    V00 arg0          (last use)
-               [000024] -----+-----                               │        └──▌  CNS_INT   long   8 Fseq[X]
-               [000010] --CXG+-----                               └──▌  CALL      int    Example:Throw():int
+               [000010] --CXG+-----                         ▌  CALL      int    Example:Throw():int
```

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS 

[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=766264&view=ms.vss-build-web.run-extensions-tab)

**Review by AndyAyersMS — COMMENTED** [review]
I think this gets us closer to the state Vlad was looking for in #101037 where we could assert post-morph that all no-return calls are root and end blocks.

Though it appears qmarks are exempted still?

**Comment by jakobbotsch** [comment]
> I think this gets us closer to the state Vlad was looking for in https://github.com/dotnet/runtime/pull/101037 where we could assert post-morph that all no-return calls are root and end blocks.
> 
> Though it appears qmarks are exempted still?

Yes, we cannot do this for QMARKs with no-return calls in them, since the no-return call may not necessarily be executed. The previous behavior handles it as part of visiting `GT_COLON` instead:
https://github.com/dotnet/runtime/blob/d606c601510c1a1a28cb6ef3550f12db049c0776/src/coreclr/jit/morph.cpp#L8864-L8872

If we want to have guarantees here then it seems we need to do this transformation after qmark expansion as well. But in my opinion this treatment of no-return calls should be strictly an optimization, and it should be just fine to leave a no-return call in a non `BBJ_THROW` block. There are many calls we cannot know statically are no-return calls, so it seems weird to me to have IR invariants about optimizations happening for the ones we do.

**Comment by jakobbotsch** [comment]
@AndyAyersMS Any other comments here?

**Review by AndyAyersMS — APPROVED** [review]
No, sorry, thought I had approved already.

**Pull request merged**
