### PR TITLE
always try to add the result of getegid to the list returned by getgroups

### LINKED ISSUE #28922: Test failure: System.Diagnostics.Tests.ProcessTests/TestCheckChildProcessUserAndGroupIds
Opened on behalf of @wfurt

The test `System.Diagnostics.Tests.ProcessTests/TestCheckChildProcessUserAndGroupIds` has failed.

Failure Message:
```
System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.
```

Stack Trace:
```

Child exception:
  Xunit.Sdk.XunitException: Expected: 4, 20, 24, 25, 27, 29, 30, 44, 46, 109, 110, 998, 1000
Actual: 4, 20, 24, 25, 27, 29, 30, 44, 46, 109, 110, 1000
   at System.AssertExtensions.Equal[T](HashSet`1 expected, HashSet`1 actual) in /__w/1/s/src/CoreFx.Private.TestUtilities/src/System/AssertExtensions.cs:line 349
   at System.Diagnostics.Tests.ProcessTests.CheckUserAndGroupIds(String userId, String groupId, String groupIdsJoined, String checkGroupsExact) in /__w/1/s/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 515

Child process:
  System.Diagnostics.Process.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Diagnostics.Tests.ProcessTests Int32 CheckUserAndGroupIds(System.String, System.String, System.String, System.String)

Child arguments:
  1000, 1000, 4,20,24,25,27,29,30,44,46,109,110,998,1000, True

```

Build : 3.0 - 20190310.5 (Core Tests)
Failing configurations:
- Ubuntu.1604.Amd64-x64
  - Release

### PR DESCRIPTION
**Pull request by adamsitnik**
https://man7.org/linux/man-pages/man2/getgroups.2.html

>    
       It is unspecified whether the effective group ID of the calling
       process is included in the returned list.  (Thus, an application
       should also call getegid(2) and add or remove the resulting value.)

Another try to fix #28922

### CODE REVIEW

**Comment by adamsitnik** [comment]
I've forgot to re-enable this test... apologies for that.

**Comment by adamsitnik** [comment]
@wfurt it looks like it did the trick and the test has passed (the CI failures are not related to Process)

**Review by wfurt — APPROVED** [review]
LGTM.

**Pull request merged**
