### PR TITLE
WIP: Add private {ReadOnly}Span ctor that takes a ref, index and length

### PR DESCRIPTION
**Pull request by xtqqczze**

### CODE REVIEW

**Comment by jkotas** [comment]
What are you trying to achieve with this?

**Comment by xtqqczze** [comment]
> What are you trying to achieve with this? 

Just a code cleanup. I was hoping to see no regressions on asmdiffs.

**Comment by jkotas** [comment]
The new method in `Span<T>` will make every `Span<T>` instantiation more expensive. So this is a footprint regression at minimum.

**Comment by jkotas** [comment]
Thank you for contribution. We do not want to make `Span<T>` instantiations more expensive for this minor style improvement.

**Pull request closed without merging**
