### PR TITLE
[HTTP/3] Attempt at using newer image to allow H/3 Windows stress

### LINKED ISSUE #82258: Enable HTTP/3 stress on Windows
Previously, we run HTTP/3 stress tests only on Linux, because Windows containers did not support TLS 1.3.
It should support TLS 1.3 now, so we should enable HttpStress tests there as well.

### PR DESCRIPTION
**Pull request by ManickaP**
Fixes #82258

### CODE REVIEW

**Comment by ManickaP** [comment]
Windows H/3 stress is now running :tada: 

The failure seems to be present before this change, see https://github.com/dotnet/runtime/issues/82528

@antonfirsov Do you think we could merge this and solve that failure separately since it seems to be unrelated?

**Review by CarnaViire — APPROVED** [review]
LGTM, thanks Mana! :shipit:

**Review by antonfirsov — APPROVED** [review]
> Do you think we could merge this and solve that failure separately since it seems to be unrelated?

Makes sense to me, let's :shipit:!

**Pull request merged**
