### PR TITLE
Don't re-initialize static fields in Console

### PR DESCRIPTION
**Pull request by marek-safar**
the compiler is not capable removing the initialization

### CODE REVIEW

**Comment by stephentoub** [comment]
> the compiler is not capable removing the initialization

It's fine to remove the `= false`, but the C# compiler does remove those assignments.  It will still generate an empty cctor, though, if those would have been the only initialization; that's tracked by https://github.com/dotnet/roslyn/issues/42985.

**Review by stephentoub — APPROVED** [review]

**Comment by marek-safar** [comment]
> but the C# compiler does remove those assignments

It does not in all cases like this one. It does remove the assignments only where there is no needed assignment. Simple example bellow

```c#
class C
{
    static object o = new object ();
    static bool b = false;
}
```

**Comment by stephentoub** [comment]
> It does not in all cases like this one.

If that's true that's a bug.  Have you opened one on dotnet/roslyn?

**Comment by EgorBo** [comment]
I see there are more cases like this in BCL (I used `static (.*) = null;` and `static (.*) = false;` regex in VSCode)

**Comment by marek-safar** [comment]
> Have you opened one on dotnet/roslyn?

https://github.com/dotnet/roslyn/issues/43652

**Comment by marek-safar** [comment]
> I see there are more cases like this in BCL (I used static (.*) = null; and static (.*) = false; regex in VSCode)

@EgorBo could you submit PR to clear them up?

**Pull request merged**
