### PR TITLE
Arm64: Always use SIMD features 

### LINKED ISSUE #64972: Test failure JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd
Run: [runtime-coreclr jitstress-isas-arm 20220207.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1598659&view=ms.vss-test-web.build-test-results-tab&runId=44666192&paneView=debug&resultId=101403)

Failed test:
```
CoreCLR windows arm64 Checked jitstress_isas_nosimd @ Windows.10.Arm64v8.Open

- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR windows arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ Windows.10.Arm64v8.Open

- JIT\\Regression\\JitBlue\\GitHub_35821\\GitHub_35821\\GitHub_35821.cmd

CoreCLR OSX arm64 Checked jitstress_isas_nohwintrinsic @ OSX.1200.ARM64.Open

- JIT/Regression/JitBlue/GitHub_35821/GitHub_35821/GitHub_35821.sh

CoreCLR OSX arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ OSX.1200.ARM64.Open

- JIT/Regression/JitBlue/GitHub_35821/GitHub_35821/GitHub_35821.sh

CoreCLR OSX arm64 Checked jitstress_isas_nosimd @ OSX.1200.ARM64.Open

- JIT/Regression/JitBlue/GitHub_35821/GitHub_35821/GitHub_35821.sh

CoreCLR Linux arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/Regression/JitBlue/GitHub_35821/GitHub_35821/GitHub_35821.sh

CoreCLR Linux arm64 Checked jitstress_isas_nohwintrinsic @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/Regression/JitBlue/GitHub_35821/GitHub_35821/GitHub_35821.sh

CoreCLR Linux arm64 Checked jitstress_isas_nosimd @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- JIT/Regression/JitBlue/GitHub_35821/GitHub_35821/GitHub_35821.sh

```
**Error message:**
```
Assert failure(PID 13208 [0x00003398], Thread: 11352 [0x2c58]): Assertion failed '(allRegs(theInterval->registerType) & mask) != 0' in 'projs.GitHub_35821:Main(System.String[]):int' during 'Linear scan register alloc' (IL size 48)

File: D:\a\_work\1\s\src\coreclr\jit\lsrabuild.cpp Line: 596
Image: D:\h\w\B90F0A35\p\corerun.exe
Return code:      1
Raw output file:      D:\h\w\B90F0A35\w\B4BE09AB\uploads\Reports\JIT.Regression\JitBlue\GitHub_35821\GitHub_35821\GitHub_35821.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\B90F0A35\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  GitHub_35821.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B90F0A35\p
D:\h\w\B90F0A35\w\B4BE09AB\e\JIT\Regression\JitBlue\GitHub_35821\GitHub_35821\GitHub_35821.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_GitHub_35821_GitHub_35821_GitHub_35821_._JitBlue_GitHub_35821_GitHub_35821_GitHub_35821_cmd()
```

### PR DESCRIPTION
**Pull request by kunalspathak**
On Arm64, we always support SIMD types but in the code base, we were sometimes relying on `featureSIMD` flag which can be `false` in case `COMPlus_FeatureSIMD=0` and doesn't work on Arm64. On Arm64, we always need SIMD features to support ABI handling. Modified all the usages to instead use `supportSIMDTypes()`.

Will fix https://github.com/dotnet/runtime/issues/64972

Thanks @tannergooding for your the references:

- https://github.com/dotnet/runtime/issues/66206
- https://github.com/dotnet/runtime/issues/11701
- https://github.com/dotnet/runtime/issues/9473.

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by kunalspathak** [comment]
The underlying problem https://github.com/dotnet/runtime/issues/64972#issuecomment-1062693347 still needs a fix, but this will unblock the outerloop.

**Comment by tannergooding** [comment]
We should also make the backing field `private` to enforce usage goes through the method.

Might also be good to ensure https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/compiler.cpp#L2670 is either always setting the field to `true` on Arm64 or that the field doesn't exist on Arm64.

**Comment by kunalspathak** [comment]
> We should also make the backing field `private` to enforce usage goes through the method.

It is already private and the usage was in Compiler methods.

> Might also be good to ensure https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/compiler.cpp#L2670 is either always setting the field to `true` on Arm64 or that the field doesn't exist on Arm64.

I can make that x64 only field.

**Comment by kunalspathak** [comment]
ping

**Review by tannergooding — APPROVED** [review]

**Pull request merged**
