### PR TITLE
copy CoreRun to the testhost directory to make benchmarking and profiling of local builds easier

### LINKED ISSUE #1523: How can I obtain a folder with CoreRun and all runtime and reference assemblies after recent build changes?
### Background

Some time ago we have switched to BenchmarkDotNet which runs every benchmark in a dedicated process (to achieve process-level isolation and reproducible results). It also generates some boilerplate code to help the users avoid common benchmarking pitfalls (consuming the method result etc).  So **it needs to be able to build and run some code**.

To work with local builds of CoreCLR|FX, we have decided to use **CoreRun** as a runner. It loads the `System*.dlls` that are next to it without checking the version numbers and just executes the code.

The feature got exposed via console line argument `--coreRun` and is very frequently used by devs who work on the Team.

https://github.com/dotnet/performance/blob/master/docs/benchmarkdotnet.md#CoreRun

### The problem

When we have initially switched to the new mono repo, I've tested that everything worked properly.

But before I've started my winter holidays I was told by few team members that it does not work anymore.

I've pulled the recent changes and built entire repo using following command:

```cmd
build -c Release
```

I can find `CoreRun.exe` in two folders:

```log
C:\Projects\runtime\artifacts\bin\coreclr\Windows_NT.x64.Release
C:\Projects\runtime\artifacts\obj\coreclr\Windows_NT.x64.Release\src\hosts\corerun\Release
```

The problem is that **none of these folders contains System.dll assemblies required to run the benchmarks** and benchmarking fails with following error:

```log
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

### Solution

I've tried to read the docs and run a few extra commands (`build.cmd -c Release -buildtests` for example), but I was not able to get what I wanted. Did I miss something?

I don't know why `CoreRun` is not copied to the folder with `System*.dlls` anymore. @ViktorHofer @ericstj  Could we just restore the old behavior? Or expose it via some optional script argument? I would really like to keep it simple to make sure that benchmarking and profiling local builds is easy for everyone.

/cc @stephentoub

### PR DESCRIPTION
**Pull request by adamsitnik**
fixes #1523

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
LGTM, but @ViktorHofer should review and sign-off before it's merged.

**Comment by adamsitnik** [comment]
@ViktorHofer PTAL. It's more or less a revert of https://github.com/dotnet/runtime/pull/494/commits/002e6640b63debdab2e7b5dbcaad140c97deda9e

**Review by jkoritzinsky — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]
Do we have a tracking issue to remove the CoreRun dependency? That's a internal which really shouldn't be exposed/used over dotnet.exe if not absolutely necessary.

**Comment by janvorli** [comment]
@ViktorHofer the corerun will probably always be needed for running coreclr tests.

**Comment by ViktorHofer** [comment]
> the corerun will probably always be needed for running coreclr tests.

Can you explain why?

I don't have any concerns with using it inside the repository for our own testing but exposing it or taking a dependency on it from another repository is controversial.

**Comment by adamsitnik** [comment]
> I don't have any concerns with using it inside the repository for our own testing but exposing it or taking a dependency on it from another repository is controversial.

It's not used by the performance repo. Performance repo is testing the end product: it downloads .NET Core SDK and runs the benchmarks using dotnet cli.

As I've described it in #1523 we need CoreRun when we are benchmarking|profiling local builds of dotnet runtime as part of development workflow.

Just to give you example. Let's say that I want to profile `DateTime.UtcNow` using my local dotnet runtime build.

I need to compile and run following program:

```
class Program
{
    static int Main()
    {
        long ticks = 0;

        for (int i = 0; i < 30_000_000; i++) // 30_000_000 is enough to run for 2-3 seconds
        {
            ticks ^= DateTime.UtcNow.Ticks; // xor is cheap operation (modulo is not)
        }

        return (int)ticks; // return the result to prevent from dead code elimination
    }
}
```

With CoreRun, I just build it using any dotnet cli and run by passing the path to the dll. With `dotnet cli` is much more complex: https://github.com/dotnet/runtime/blob/master/docs/workflow/using-dotnet-cli.md

**Comment by ViktorHofer** [comment]
Thanks for providing more details. The linked workflow when using the dotnet CLI will stop working relatively soon as we won't produce these packages anymore. The combined repo instead allows to test the product far more easily as we now have one combined testhost. I think it's worth discussing the requirements in more detail offline as I believe that the existing CLI workflow can be simplified significantly.

**Pull request merged**
