### PR TITLE
Fix fgOptimizeAddition opt for AOT

### LINKED ISSUE #94332: JIT incorrectly adds handles to integer constants
Regression from .NET 7.

Compile following program with native AOT:

```csharp
unsafe partial class Program
{
    const int Width = 320;
    const int Height = 180;

    struct Pixels
    {
        public fixed byte Data[Width * Height];
    }

    static Pixels pixels;

    static void Main()
    {
        for (nint i = 0; i < Width; i++)
            pixels.Data[(Height - 1) * Width + i] = 36;
    }
}
```

This will crash with an `IndexOutOfRangeException` in JitInterface because RyuJIT is asking about a non-sensical handle.

I've root caused it to following code in Morph:

https://github.com/dotnet/runtime/blob/aea45f7aaa8f73cb2a585d8b14ce66634d58cb68/src/coreclr/jit/morph.cpp#L11105-L11125

One of these integer constants is actually a handle and doing an addition with it is not valid.

```
fgMorphTree BB02, STMT00020 (before)
               [000106] -A-XG------                         *  STOREIND  byte
               [000104] -----------                         +--*  ADD       long
               [000099] -----------                         |  +--*  FIELD_ADDR long   Program+Pixels+<Data>e__FixedBuffer:FixedElementField
               [000098] -----------                         |  |  \--*  FIELD_ADDR long   Program+Pixels:Data
               [000097] -----------                         |  |     \--*  ADD       long
               [000095] H----------                         |  |        +--*  CNS_INT(h) long   0x40000000004201c8 static
               [000096] -----------                         |  |        \--*  CNS_INT   long   0 Fseq[pixels]
               [000103] -----------                         |  \--*  ADD       long
               [000101] -----------                         |     +--*  CNS_INT   long   0xDFC0
               [000102] -----------                         |     \--*  LCL_VAR   long   V04 loc4
               [000105] -----------                         \--*  CNS_INT   int    36

Final value of Compiler::fgMorphFieldAddr after morphing:
               [000097] -----+-----                         *  ADD       long
               [000096] -----+-----                         +--*  CNS_INT   long   0 Fseq[pixels]
               [000095] H----+-----                         \--*  CNS_INT(h) long   0x40000000004201c8 static

Final value of Compiler::fgMorphFieldAddr after morphing:
               [000097] -----+-----                         *  ADD       long
               [000096] -----+-----                         +--*  CNS_INT   long   0 Fseq[pixels]
               [000095] H----+-----                         \--*  CNS_INT(h) long   0x40000000004201c8 static

fgMorphTree BB02, STMT00020 (after)
               [000106] -A-XG+-----                         *  STOREIND  byte
               [000104] -----+-----                         +--*  ADD       long
               [000097] -----+-----                         |  +--*  ADD       long
               [000096] -----+-----                         |  |  +--*  CNS_INT   long   0 Fseq[pixels]
               [000102] -----+-----                         |  |  \--*  LCL_VAR   long   V04 loc4
               [000095] H----+-----                         |  \--*  CNS_INT(h) long   0x400000000042e188 static
               [000105] -----+-----                         \--*  CNS_INT   int    36
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/94332

Thanks @MichalStrehovsky for finding the root cause, indeed, a Morph optimization folded "CNS1 + CNS2" where it wasn't legal. `gtFoldExprConst` cares about such cases so I am just forwarding the folding to that.

### CODE REVIEW

**Comment by EgorBo** [comment]
@dotnet/jit-contrib PTAL, [no diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=459574&view=ms.vss-build-web.run-extensions-tab) but fixes the AOT issue. `gtFoldExprConst` won't fold "CNS1 + CNS2" when either (or both) are handles.

**Review by jakobbotsch — APPROVED** [review]

**Pull request merged**
