### PR TITLE
Update analyzers

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @ViktorHofer, @safern

### CODE REVIEW

**Review by ViktorHofer — COMMENTED** [review]
updating the CSharpCodeStyle package to 3.9 means that we bump VS minimum supported veresion to 16.9. Are we fine with that?

**Comment by stephentoub** [comment]
Hmm. When/why would we otherwise increase the minimum?

**Comment by ViktorHofer** [comment]
> Hmm. When/why would we otherwise increase the minimum?

Usually when we depend on a newer SDK we would require a newer of VS to be used. Should we pair this change with the monthly infra rollout which bumps the min SDK's version to 6.0 P1? From the P1 blog post:

> .NET 6 has been tested with Visual Studio 16.9 Preview 4 and Visual Studio for Mac 8.9. We recommend you use those builds if you want to try .NET 6.

**Comment by safern** [comment]
> Usually when we depend on a newer SDK

But this doesn't require a newer SDK, that is why we follow the approach of referencing the analyzers directly to be able to bump the analyzer's version without having to upgrade the SDK.

**Comment by ViktorHofer** [comment]
Stephen was asking about when we would update the minimum required version of VS which I responded to when we require a newer SDK or in this case when the CodeStyle package is updated: https://github.com/dotnet/roslyn/issues/50833#issuecomment-768479955.

**Comment by safern** [comment]
> in this case when the CodeStyle package is updated: dotnet/roslyn#50833 (comment).

I didn't know the CodeStyle package had this limitation... We control the version of the compiler we use, why not override the arcade version in the meantime?

**Comment by ViktorHofer** [comment]
We already use the required version of the compiler package in dotnet/runtime. Visual Studio does come with its own dependency and hence VS 16.9 is required if we wanna use the update CodeStyle package.

**Comment by safern** [comment]
> Visual Studio does come with its own dependency and hence VS 16.9 is required if we wanna use the update CodeStyle package.

I see, I thought VS honored the compiler if it was referenced via a PackageReference.

**Comment by stephentoub** [comment]
> Should we pair this change with the monthly infra rollout which bumps the min SDK's version to 6.0 P1?

Sure, though I thought I saw that that was happening now as part of https://github.com/dotnet/arcade/pull/6975?

**Comment by ViktorHofer** [comment]
> Sure, though I thought I saw that that was happening now as part of dotnet/arcade#6975?

Whenever that change flows into dotnet/runtime, we will hold it until 3/1.

**Comment by stephentoub** [comment]
> we will hold it until 3/1.

Ok, then let's just sit on this PR until then.

**Comment by stephentoub** [comment]
Now that the March update is in, I can update and proceed with this, right, Viktor?

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
You may want to update the version to `3.9.0-5.final` which is now available on nuget.org: https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/3.9.0-5.final

**Comment by sharwell** [comment]
> I see, I thought VS honored the compiler if it was referenced via a PackageReference.

It honors the compiler for _builds_, but not for _IntelliSense_. Updating the code style package to something newer than the IDE means you get analyzers for builds, but you don't get any IDE live diagnostics and you don't get any code fixes.

**Comment by stephentoub** [comment]
Yup

**Review by safern — APPROVED** [review]

**Pull request merged**
