### PR TITLE
Update all of the net 6 packs to be labeled .net6

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Comment by lambdageek** [comment]
@radical What needs to be fixed up in the WBT tests to use the updated pack names, if anything?

**Comment by lambdageek** [comment]
```
Rolling back pack Microsoft.NET.Runtime.WebAssembly.Sdk.net6 installation...
/__w/1/s/src/libraries/workloads-testing.targets(127,5): error : Workload installation failed: microsoft.net.runtime.webassembly.sdk.net6::6.0.9 is not found in NuGet feeds [https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-1026ad55/nuget/v3/index.json;/__w/1/s/artifacts/packages/Release/Shipping/;/__w/1/s/artifacts/packages/Release/NonShipping/;/__w/1/s/artifacts/packages/Release/Shipping/;/__w/1/s/artifacts/packages/Release/NonShipping/;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-buildservices/nuget/v3/index.json".](https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-1026ad55/nuget/v3/index.json;/__w/1/s/artifacts/packages/Release/Shipping/;/__w/1/s/artifacts/packages/Release/NonShipping/;/__w/1/s/artifacts/packages/Release/Shipping/;/__w/1/s/artifacts/packages/Release/NonShipping/;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-buildservices/nuget/v3/index.json%22.) [/__w/1/s/src/tests/BuildWasmApps/Wasm.Build.Tests/Wasm.Build.Tests.csproj]
##[error]src/libraries/workloads-testing.targets(127,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Workload installation failed: microsoft.net.runtime.webassembly.sdk.net6::6.0.9 is not found in NuGet feeds [https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-1026ad55/nuget/v3/index.json;/__w/1/s/artifacts/packages/Release/Shipping/;/__w/1/s/artifacts/packages/Release/NonShipping/;/__w/1/s/artifacts/packages/Release/Shipping/;/__w/1/s/artifacts/packages/Release/NonShipping/;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-buildservices/nuget/v3/index.json".](https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-1026ad55/nuget/v3/index.json;/__w/1/s/artifacts/packages/Release/Shipping/;/__w/1/s/artifacts/packages/Release/NonShipping/;/__w/1/s/artifacts/packages/Release/Shipping/;/__w/1/s/artifacts/packages/Release/NonShipping/;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6-transport/nuget/v3/index.json;https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-buildservices/nuget/v3/index.json%22.)
  Exit code: 1
```

Does this mean we need to add a dotnet6 feed to some NuGet.config?

**Comment by radical** [comment]
The generated package names need to be updated too.

**Comment by radical** [comment]
I will add that, and test locally.

**Comment by radical** [comment]
```xml
    "Microsoft.NETCore.App.Runtime.AOT.Cross.net6.browser-wasm": {
      "kind": "Sdk",
      "version": "${PackageVersion}",
      "alias-to": {
        "win-x64": "Microsoft.NETCore.App.Runtime.AOT.win-x64.Cross.browser-wasm",
        "linux-x64": "Microsoft.NETCore.App.Runtime.AOT.linux-x64.Cross.browser-wasm",
        "osx-x64": "Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.browser-wasm",
        "osx-arm64": "Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.browser-wasm"
      }
    },
```

@marcpopMSFT Here, `Microsoft.NETCore.App.Runtime.AOT.Cross.net6.browser-wasm` is being mapped to packs without `net6` in the name. Is that deliberate?

**Comment by radical** [comment]
cc @jonathanpeppers @steveisok

**Comment by radical** [comment]
It was able to install the workload now:
```
  ** Installing workload manifest wasm-tools **
  
  Installing workload manifest for Microsoft.NET.Workload.Mono.ToolChain/6.0.9 for sdk band 6.0.400
  Installing workload manifest for Microsoft.NET.Workload.Emscripten/6.0.8 for sdk band 6.0.400
```

Now, waiting on tests against that installed workload.

**Comment by radical** [comment]
Wasm.Build.Tests are passing on Linux. Waiting on the windows ones.

**Comment by radical** [comment]
> Wasm.Build.Tests are passing on Linux. Waiting on the windows ones.

Oops, I forgot. We didn't have these tests running on windows for 6.0 .

**Comment by radical** [comment]
The wasm/workload tests were run with SDK `6.0.400-rtm.22371.2`, but the latest is `6.0.401`. Should that be updated here?

**Review by radical — APPROVED** [review]
The wasm workload tests ran successfully here. They used the new updated packs, and manifest. And they were run against `dotnet-sdk-6.0.400-rtm.22371.2-linux-x64`.

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
