### PR TITLE
Add Lerp to IFloatingPointIeee754

### LINKED ISSUE #80044: [API Proposal]: IFloatingPointIeee754<T>.Lerp
### Background and motivation

_Lerp_ stands for [linear interpolation](https://en.wikipedia.org/wiki/Linear_interpolation). It can be widely used to mix two values with a given proportion.

### API Proposal

```csharp
namespace System.Numerics;

public interface IFloatingPointIeee754<T> where T : IFloatingPointIeee754<T>?
{
    static virtual T Lerp(T value1, T value2, T amount) => (value1 * (T.One - amount)) + (value2 * amount);
}
```

```csharp
namespace System;

public readonly struct Half : IFloatingPointIeee754<Half>
{
    public static Half Lerp(Half value1, Half value2, Half amount)
    {
        return value1 * (One - amount) + value2 * amount;
    }
}

public readonly struct Single : IFloatingPointIeee754<float>
{
    public static float Lerp(float value1, float value2, float amount)
    {
        return value1 * (One - amount) + value2 * amount;
    }
}

public readonly struct Double : IFloatingPointIeee754<double>
{
    public static double Lerp(double value1, double value2, double amount)
    {
        return value1 * (One - amount) + value2 * amount;
    }
}
```

```csharp
namespace System.Runtime.InteropServices;

public readonly struct NFloat : IFloatingPointIeee754<NFloat>
{
    public static NFloat Lerp(NFloat value1, NFloat value2, NFloat amount)
    {
        return value1 * (One - amount) + value2 * amount;
    }
}
```

### API Usage

```csharp
float value1 = 3f;
float value2 = 12f;
float amount = 0.5f;
Console.WriteLine(float.Lerp(value1, value2, amount));
Console.WriteLine(double.Lerp(value1, value2, amount));
Console.WriteLine(Half.Lerp((Half)value1, (Half)value2, (Half)amount));
Console.WriteLine(NFloat.Lerp(value1, value2, amount));
```

### Alternative Designs

_No response_

### Risks

_No response_

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/80044

### CODE REVIEW

**Review by dakersnar — APPROVED** [review]
LGTM. Anything notably tricky that could use a triple check?

**Comment by tannergooding** [comment]
> LGTM. Anything notably tricky that could use a triple check?

Not really, this is a really straightforward API with a trivial implementation.

The biggest "gotcha" is ensuring that it is implemented as `(value1 * (1.0f - amount)) + (value2 * amount)` and not as `value1 + ((value2 - value1) * amount)`

The two algorithms are mathematically "equivalent" (assuming amount is between 0 and 1, inclusive). However, they produce different results for various edge cases when considering floating-point values and only the former is guaranteed to correctly return `value2` when `amount == 1.0f`

**Comment by dakersnar** [comment]
The floating-point-specific behavior for this functionality is _not_ specified in the IEEE spec, correct? Given that, I assume we are just following common sense and industry standards when deciding how these edge cases are handled?

**Comment by tannergooding** [comment]
Correct

**Pull request merged**
