### PR TITLE
[wasm] pass ExitStatus when calling quit_

### LINKED ISSUE #64727: [wasm] NodeJS samples failing at exit with emsdk `2.0.34`
Hit on https://github.com/dotnet/runtime/pull/62499 . [Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1588560&view=logs&j=329e2a42-7849-55e5-399c-04716ed16daa&t=49f2a43b-2af7-512f-9858-2f6cef5f8a91).

Fails for both CJS, and ES6 in the same way:

```
[02:11:49] fail: undefined
[02:11:49] fail: (Use `node --trace-uncaught ...` to show where the exception was thrown)
[02:11:49] info: Process node exited with 7
```

Running locally with `--trace-uncaught`:
```
undefined
Thrown at:
    at /Users/radical/dev/runtime/src/mono/sample/wasm/console-node-cjs/bin/Release/AppBundle/dotnet.js:12:2969
    at emit (node:events:394:28)
    at node:internal/process/execution:170:25
```

Seems to be because of undefined `quit_` function.

cc @pavelsavara 

|Build|Kind|Start Time|
|---|---|---|
[1589203](https://dev.azure.com/dnceng/public/_build/results?buildId=1589203)|Rolling|2022-03-02|

### PR DESCRIPTION
**Pull request by pavelsavara**
For explanation Posix `exit` is implemented in emscripten as 
1) On NodeJS it would also call `process.exit` and stop immediately.
2) Throwing javascript `ExitStatus` exception. That exception need to bubble thru all the call stack out into `uncaughtException` handler, which will recognize the class and swallow it. I think that going thru all the catch/finally statements it why it's designed this way. Also onV8 it's probably the only way how to stop, but I'm not sure now.

There is also `noExitRuntime` setting which could prevent that. We have it true on browser and I just set it to false on node and v8 in this PR.

Fixes https://github.com/dotnet/runtime/issues/64727

### CODE REVIEW

**Review by radekdoulik — APPROVED** [review]

**Comment by pavelsavara** [comment]
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64734-merge-e903f3595089479bad/Workloads-.WasmBuildAppTest/1/console.b8a75806.log?sv=2019-07-07&se=2022-02-23T11%3A02%3A12Z&sr=c&sp=rl&sig=FGP58Y7GnNjmgehd6O6NioUTc4hpy%2BFXJ%2FC9V7nP1b4%3D)
```
[wasm test] [11:29:54] fail: {"name":"ExitStatus","message":"Program terminated with exit(42)","status":42}
[wasm test]                  
[wasm test] [11:29:54] info: Process node exited with 1
[wasm test]                  
[wasm test] [11:29:54] fail: Application has finished with exit code 1 but 42 was expected
[wasm test] [11:29:54] dbug: Saving diagnostics data to '/datadisks/disk1/work/A4E10928/w/B36509BA/e/diagnostics.json'
[wasm test] XHarness exit code: 71 (GENERAL_FAILURE)
```

**Comment by radekdoulik** [comment]
There's also:
```
[wasm test] [11:38:10] fail: Error
[wasm test]                  
[wasm test] [11:38:10] fail:     at Object.onAbort (test-main.js:157:25)
[wasm test]                  
[wasm test] [11:38:10] fail:     at abort (./dotnet.js:1973:24)
[wasm test]                  
[wasm test] [11:38:10] fail:     at Object.get (./dotnet.js:1116:7)
[wasm test]                  
[wasm test] [11:38:10] fail:     at Object.initializeImportsAndExports [as __initializeImportsAndExports] (./dotnet.js:3:83482)
[wasm test]                  
[wasm test] [11:38:10] fail:     at ./dotnet.js:7530:47
[wasm test]                  
[wasm test] [11:38:10] fail:     at test-main.js:123:12
[wasm test]                  
[wasm test] [11:38:10] fail: "Module.noExitRuntime has been replaced with plain noExitRuntime (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)"
```

**Comment by radical** [comment]
In case it helps - I had found that `set_exit_code` was getting called twice for node.
1. `set_exit_code(result)`, which would eventually call `mono_wasm_exit`-> `exit`, and that would throw an `Error`,
2. causing ` set_exit_code(1, error)` to get called then

As a fix I changed `test-main.js` to explicitly call `process.exit(result)` on node.

**Pull request merged**
