### PR TITLE
[Mono] Fix EnumCompareTo for small integers

### LINKED ISSUE #48190: [Mono] Comparer_get_Default runtime test fails on Mono
Repro:
```csharp
using System;
using System.Collections.Generic;

class Program
{
    public static void Main()
    {
        Console.WriteLine(((byte)0).CompareTo(2));
        Console.WriteLine(MyEnum.A.CompareTo(MyEnum.C));
        Console.WriteLine(Comparer<MyEnum>.Default.Compare(MyEnum.A, MyEnum.C));
    }
}

public enum MyEnum : byte
{
    A, B, C
}
```
Output on CoreCLR:
```
-2
-2
-2
```
Mono:
```
-2
-2
-1
```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/48190 for both JIT and Interpreter.

### CODE REVIEW

**Comment by BrzVlad** [comment]
I don't understand why this is an issue ? This change rather looks like an optimization ?

**Comment by EgorBo** [comment]
> I don't understand why this is an issue ? This change rather looks like an optimization ?

It's an issue in the existing optimization. `Comparer<MyByteEnum>.Default` is supposed to mirror C# `Byte.CompareTo` logic. https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Byte.cs#L46-L49

**Comment by BrzVlad** [comment]
@EgorBo Do you know who makes that constraint ? Why isn't it enough to just return <0, 0, >0, and the actual value matters ?

**Comment by EgorBo** [comment]
> @EgorBo Do you know who makes that constraint ? Why isn't it enough to just return <0, 0, >0, and the actual value matters ?

Not really, in theory the current behavior is correct since the public API says `<0 means x is less y`.
But this PR just aligns the behavior between the optimization in JIT/Interpreter and C# code that does the same (and CoreCLR runtime).
I never said it's a bug 🙂

**Review by BrzVlad — APPROVED** [review]

**Comment by EgorBo** [comment]
Failure is unrelated: https://github.com/dotnet/runtime/issues/48198

**Pull request merged**
