### PR TITLE
[aot] mono_aot_split_options: reset state after a backslash

### LINKED ISSUE #108066: [aot] mono_aot_split_options handles \ incorrectly
The idea is that you can pass an option like `--aot=foo=bar,baz="abc\"def\",xyz=012` and the AOT compiler will see options `foo=bar`, `baz=abc"def` and `zyx=012`.

But this line that is supposed to handle the character following a `\` is wrong

https://github.com/dotnet/runtime/blob/68b90acee9d8fbc18d47dd9409a89e3ea083d1fa/src/mono/mono/mini/aot-compiler.c#L8749-L8750

it never resets the state back to `MONO_AOT_OPTION_STATE_STRING`, so everything after the `\` until the end of the options is treated as a single long option: `foo=bar`, `baz=abc\"def",xyz=012`

Also the `\` is itself never removed from the option - instead of `bar=abc"def` we get `bar=abc\"def`.  (And this is a hard problem because we woudl need to copy or modify the string, which we don't otherwise do)

### PR DESCRIPTION
**Pull request by lambdageek**
Fixes https://github.com/dotnet/runtime/issues/108066

### CODE REVIEW

**Comment by lambdageek** [comment]
@steveisok I kind of want to backport this to 9 and 8, but to be perfectly honest I suspect noone really used this `\` capability because it so very clearly did the wrong thing before (treated the entire remainder of the input as one long option)

**Review by lewing — APPROVED** [review]

**Review by steveisok — APPROVED** [review]

**Pull request merged**
