### PR TITLE
Delete workaround for classic zlib

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by carlossanlop** [comment]
Lots of failures.

**Comment by jkotas** [comment]
> Lots of failures.

Fixed

**Review by carlossanlop — APPROVED** [review]

**Comment by carlossanlop** [comment]
CI failure in both Mono_Interpreter_Libraries and Mono_MiniJIT are the same:
> `exit code 137 means SIGKILL Killed either due to out of memory/resources (see /var/log/messages) or by explicit kill.`

**Comment by jkotas** [comment]
> CI failure in both Mono_Interpreter_Libraries and Mono_MiniJIT are the same

Known issues according to the build analysis

**Pull request merged**
