### PR TITLE
Regenerate fabricbot config to include several new/revised automation tasks

### PR DESCRIPTION
**Pull request by jeffhandley**
The `fabricbot.json` config file is generated from https://github.com/dotnet/fabricbot-config. Here are the configuration tasks that are included for this repository:

1. **New** [trackUntriaged](https://github.com/dotnet/fabricbot-config/blob/main/src/issueAndPullRequestTasks/trackUntriaged.js)
    1. Add `untriaged` label to new/reopened issues without a milestone (or when the milestone is removed)
    1. Remove `untriaged` label from issues when closed or added to a milestone
1. **Revised** [addInPrLabel](https://github.com/dotnet/fabricbot-config/blob/main/src/issueAndPullRequestTasks/addInPrLabel.js)
    1. Add `in-pr` label on the issue when a pull request is opened to target it
    1. _This task is now part of the fabricbot-config generation_
1. **Revised** [assignTeamAuthor](https://github.com/dotnet/fabricbot-config/blob/main/src/issueAndPullRequestTasks/assignTeamAuthor.js)
    1. Assign Team PRs to author when the PR is opened
    1. _This task is now part of the fabricbot-config generation_
    1. _The logic has been fixed to handle different team member permission levels correctly_
1. **Revised** [addCommunityContributionLabel](https://github.com/dotnet/fabricbot-config/blob/main/src/issueAndPullRequestTasks/addCommunityContributionLabel.js)
    1. Add `community-contribution` label to pull requests created by users that don't have admin, maintain, or write permissions (and the common bot accounts are excluded too)
    1. _This task is now part of the fabricbot-config generation_
    1. _The logic has been fixed to handle different team member permission levels correctly_
1. **Revised** [trackNeedsAuthorAction](https://github.com/dotnet/fabricbot-config/blob/main/src/issueAndPullRequestTasks/trackNeedsAuthorAction.js)
    1. Add a reply when the `needs-author-action` label is applied
    1. Apply the `needs-author-action` label when changes are requested on a PR (by a triager or team member)
    1. Replace `needs-author-action` with `needs-further-triage` when the author comments on an issue
    1. Remove the `needs-author-action` label when changes are pushed to the PR 
    1. Remove the `needs-author-action` label when the author comments on the PR
    1. Remove the `needs-author-action` label when the author response to a review comment
    1. _These tasks are now part of the fabricbot-config generation_
1. **Revised** [trackNoRecentActivity](https://github.com/dotnet/fabricbot-config/blob/main/src/issueAndPullRequestTasks/trackNoRecentActivity.js)
    1. Add `no-recent-activity` label to issues with `needs-author-action` and no activity for 14 days (via a scheduled search)
    1. Add `no-recent-activity` label to PRs with `needs-author-action` and no activity for 14 days (via a scheduled search)
    1. Remove `no-recent-activity` label from issues when the issue is modified
    1. Remove `no-recent-activity` label from issues when the issue is commented on
    1. Remove `no-recent-activity` label from PRs when the PR is modified
    1. Remove `no-recent-activity` label from PRs when the PR is commented on
    1. Remove `no-recent-activity` label from PRs when the PR has a new review added
    1. Close issues that go an additional 14 days with no activity after having `no-recent-activity` added
    1. Close PRs that go an additional 14 days with no activity after having `no-recent-activity` added
    1. _These tasks are now part of the fabricbot-config generation_
1. **Revised** [trackInactiveDrafts](https://github.com/dotnet/fabricbot-config/blob/main/src/issueAndPullRequestTasks/trackInactiveDrafts.js)
    1. Close inactive Draft PRs after 30 days of inactivity (via a scheduled search)
    1. _This task is now part of the fabricbot-config generation_
1. **Revised** [trackStaleIssuesAndPullRequests](https://github.com/dotnet/fabricbot-config/blob/main/src/issueAndPullRequestTasks/trackStaleIssuesAndPullRequests.js)
    1. Lock issues and PRs after being closed and going 30 days with no activity (via a scheduled search)
    1. _This task is now part of the fabricbot-config generation_
1. **Revised** Area Pod issue triage project board automation (configured for each area pod)
    1. **Existing** [issueNeedsTriage](https://github.com/dotnet/fabricbot-config/blob/main/src/projectBoardTasks/issueNeedsTriage.js)
        * Add issues to the "Needs Triage" column when opened/reopened, no milestone is set, the area is included in the pod, and the issue isn't already on the board, or the issue was previously moved to "Triaged"
    1. **New** [issueTriageStarted](https://github.com/dotnet/fabricbot-config/blob/main/src/projectBoardTasks/issueTriageStarted.js)
        * Move issues from "Needs Triage" into a pod member's column when that pod member edits or comments on an issue
    1. **Existing** [issueTriaged](https://github.com/dotnet/fabricbot-config/blob/main/src/projectBoardTasks/issueTriaged.js)
        * Move issues into "Triaged" when a milestone is applied, the issue is closed, or when the `needs-author-action` label is added
    1. **Existing** [issueMovedToAnotherArea](https://github.com/dotnet/fabricbot-config/blob/main/src/projectBoardTasks/issueMovedToAnotherArea.js)
        * Move issues into "Triaged" when the area label is changed to another pod's area
    1. **Existing** [issueNeedsFurtherTriage](https://github.com/dotnet/fabricbot-config/blob/main/src/projectBoardTasks/issueNeedsFurtherTriage.js)
        * Move issues from "Triaged" to "Needs Triage" when a community member (without triage permission) comments on the issue
1. **Revised** Area Pod PR project board automation (configured for each area pod)
    1. **Revised** [pullRequestNeedsChampion](https://github.com/dotnet/fabricbot-config/blob/main/src/projectBoardTasks/pullRequestNeedsChampion.js)
        * Add PRs to the "Needs Champion" column when opened/reopened, no pod member is assigned, the area is included in the pod, the PR wasn't just opened by a pod member, and the PR isn't already on the board, or the PR was previously moved to "Done"
    1. **New** [pullRequestChampionAssigned](https://github.com/dotnet/fabricbot-config/blob/main/src/projectBoardTasks/pullRequestChampionAssigned.js)
        * Move PRs from "Needs Champion" into a pod member's column when that pod member is assigned, or if the pod member themselves submitted the PR (bypassing the "Needs Champion" column), and the PR has one of the pod's area labels
    1. **Existing** [pullRequestDone](https://github.com/dotnet/fabricbot-config/blob/main/src/projectBoardTasks/pullRequestDone.js)
        * Move PRs to the "Done" column when merged, closed without merge, or it was moved to another pod's area

The following tasks are also in place via manual configuration (outside the scope of the fabricbot-config scripts), and they are unedited in this PR:

1. Area-owners (issue-routing mentions)
2. Add breaking change doc label to issue
3. Add breaking change doc label to PR
4. Mention for linkable-framework
5. Mention for size-reduction
6. Mention for wasm
7. Mention for ios
8. Mention for android
9. Mention for tvos
10. Mention for maccatalyst
11. [Linkable-framework workgroup] Add linkable-framework label to new Prs that touch files with *ILLink* that do not have it already
12. [Linkable-framework workgroup] Add linkable-framework label to PRs that get changes pushed where they touch *ILLInk* files
13. Auto-approve maestro PRs
14. [hoyosjs/tommcdon] Add diagnostics 6.0 issues to project
15. Manual Issue Cleanup
16. Automated Issue cleanup

Once this is in place, we will also deploy dotnet/issue-labeler#39 to remove its step of adding `untriaged` to new issues in the dotnet/runtime repository. At that point, fabricbot will be exclusively responsible for adding that label.

### CODE REVIEW

**Comment by jeffhandley** [comment]
This update also introduces the "Libraries Analyzers" pod, with @carlossanlop and @buyaa-n as its members. Issues and PRs with `code-analyzer` and `code-fixer` are added to the project boards, along with issues and PRs from the roslyn-analyzers repo that are labeled as `Area-Microsoft.NetCore.Analyzers`. All of the logic for that pod is the same as all other pods, and issues/PRs can coexist on the Libraries Analyzers boards as well as the area-specific pod's boards.

See https://github.com/dotnet/roslyn-analyzers/pull/5983 for the roslyn-analyzers side of that configuration.

**Comment by jeffhandley** [comment]
Since this is really hard to review, let me know if anyone is interested in an interactive walkthrough of the scripts and how this config file is generated or what it now contains.

**Comment by danmoseley** [comment]
I assume adding `no-recent-activity` removes `needs-author-action` at the same time

**Review by danmoseley — APPROVED** [review]
I didn't try to read it, but your rules make sense to me. fwiw

**Comment by jeffhandley** [comment]
> I assume adding `no-recent-activity` removes `needs-author-action` at the same time

No; we leave `needs-author-action` in place on those intentionally. That points the issue/PR in the direction of getting closed with `needs-author-action` still applied, which is a nice artifact to see. And if the author comments during the time of both `needs-author-action` and `no-recent-activity` being in place, both labels will get removed.

**Pull request merged**
