### PR TITLE
Fix `CopyStringDictionary`

### LINKED ISSUE #96092: `TraceUtils.CopyStringDictionary()` is broken
### Description

`TraceUtils.CopyStringDictionary()` (from `System.Configuration.ConfigurationManager`) only works for empty dictionaries.

This is because it uses a `foreach` loop over a `StringDictionary` but uses a `string` loop variable while the enumeration provides dictionary entries.

### Reproduction Steps

1. `dotnet new console`
2. `dotnet add package System.Configuration.ConfigurationManager`
3. edit Program.cs:
   ```cs
   ```
4. create app.config:
   ```xml
    <configuration>
      <system.diagnostics>
        <sources>
          <source name="Foo" switch="Foo">
            <listeners>
              <add name="console" type="System.Diagnostics.ConsoleTraceListener" traceOutputOptions="DateTime,ProcessId" />
            </listeners>
          </source>
        </sources>
        <switches>
          <add name="Foo" value="All" />
        </switches>
      </system.diagnostics>
    </configuration>
   ```
   (note incorrect use of `switch` instead of `switchName`)
5. `dotnet run`

### Expected behavior

A trace message is shown, similar to

```
Foo Information: 0 : Hello World
    ProcessId=1234
    DateTime=2023-12-16T12:34:26.1102915Z
```

### Actual behavior

The application abends:

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Collections.DictionaryEntry' to type 'System.String'.
   at System.Diagnostics.TraceUtils.CopyStringDictionary(StringDictionary source, StringDictionary dest)
   at System.Diagnostics.TraceConfiguration.InitializingTraceSource(Object sender, InitializingTraceSourceEventArgs e)
   at System.Diagnostics.TraceSource.OnInitializing(InitializingTraceSourceEventArgs e)
   at System.Diagnostics.TraceSource.Initialize()
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args)
   at System.Diagnostics.TraceSource.TraceInformation(String message)
   at Program.<Main>$(String[] args)
```

### Regression?

Regression from .NET Framework.
The implementation added in .NET 7 seems to have always had this issue; it's unfortunate that there were no unit tests for this (it also feels like this could/should be detectable by source analyzers).

### Known Workarounds

None.

### Configuration

Tested with .NET SDK 8.0.100

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Zastai**
Fixes #96092.

It may be faster to use

```cs
foreach (DictionaryEntry entry in source)
{
  dest[(string) entry.Key] = (string) entry.Value;
}
```

but the casts make that ugly, so I went with the minimal patch.

### CODE REVIEW

**Comment by jkotas** [comment]
Do we need to add a test that exercises this codepath?

**Comment by Zastai** [comment]
> Do we need to add a test that exercises this codepath?

This would make sense. However, I've run into an issue trying to add one.

In order to have a unit test, I need to have access to the internals of the library (because the method and class are both internal), but adding an `InternalsVisibleTo` cause a bunch of compilation errors that I'm not sure how to resolve:

```
PlatformAttributes.cs(35,48): Error CS0436 : The type 'OSPlatformAttribute' in '...\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\Versioning\PlatformAttributes.cs' conflicts with the imported type 'OSPlatformAttribute' in 'System.Configuration.ConfigurationManager, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Using the type defined in '...\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\Versioning\PlatformAttributes.cs'.
```
(occurs once for every time `OSPlatformAttribute` is used as a base class).
Looks like this one goes away when I change the `IncludePlatformAttributes` property in `Directory.Build.props` to `false` (but not when I comment it out), but not certain that that's the right approach.

```
ValidatiorUtilsTests.cs(56,21): Error CS0436 : The type 'SR' in '...\runtime\src\libraries\Common\src\/System/SR.cs' conflicts with the imported type 'SR' in 'System.Configuration.ConfigurationManager, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Using the type defined in '...\runtime\src\libraries\Common\src\/System/SR.cs'.
```
This one happens for every use of `SR` in the unit test assembly (so 40-odd times).
Looks like this gets auto-included (by `runtime/eng/resources.props`, using slightly inconsistent path names, as shown (`...src\/System/SR.cs`)) when an assembly has string resources, with no separate condition on the `<Compile>` item vs the `<EmbeddedResource>` item, so I would need guidance on how to resolve that clash.

**Comment by jkotas** [comment]
We avoid `InternalsVisibleTo` for testing in this repo. The test infrastructure is not setup for it in many projects as you have found.

We prefer to write all tests against public APIs. What is the public API that exposes this bug? Is it possible to write a test against that API?

**Comment by Zastai** [comment]
Well I encountered it when using the wrong attribute in the config (`switch` instead of `switchName` on a source); that causes that attribute to be stored in a string dictionary that later gets copied, triggering the bug.

I suppose I can test for such a case (custom attribute on a source in the config file).

**Comment by jkotas** [comment]
> On the command-line, tests do run but it takes a significant amount of time to discover and run the tests

The instructions for running tests on the command line are at https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/libraries/testing.md .  "Running tests for a single library" typically takes seconds (with release runtime - `-rc release`).

> I'm not sure how I'm supposed to get this reproduced in an xUnit context.

Are you able to write a console app that demonstrates the bug? You can always convert that into a test using [RemoteExecutor](https://github.com/dotnet/runtime/blob/main/docs/project/writing-tests.md#remoteexecutor).

**Comment by Zastai** [comment]
The issue is triggered by app configuration; it's easy to reproduce in a console app (see the linked PR), but I don't see a way to specify `RemoteExecutor` to use a particular app.config.

But I'll start by rebuilding with `-rc Release` to see if I can at least make the tests fast to rerun.

**Comment by Zastai** [comment]
Right, with the `-rc Release` build the testing is speedy enough.

However, I am plagued by two remaining issues:
- Debugging the unit tests from Visual Studio (17.8.3) does not work; it just runs the unit test, with breakpoints not getting hit. Even an explicit `Debugger.Break()` does nothing.
- I still do not see a way of setting a unit test up such that `ConfigurationManager.GetSection("system.diagnostics")` will read XML I provide.
  - I hacked extra API to get it to check a `Configuration` I provide (as returned by `OpenExeConfiguration`), and that enables me to reproduce the issue and verify that the fix works, but that's of course not a viable solution

I'll try a few more things; worst case I'll push an always-failing unit test as a starting point.

**Comment by Zastai** [comment]
It's not ideal but with an `app.config` added to the test project (with a target to copy it to the output as `testhost.dll.config`), the unit test works.

**Comment by Zastai** [comment]
Interesting - the test works locally but seems to fail in CI.

**Review by stephentoub — APPROVED** [review]
Thanks!

The fix looks good, but tests are still failing. Kicking the build again as the last build is now gone.

**Comment by Zastai** [comment]
Well, the unit tests rely on 2 things:
- the test run will load `testhost.dll.config` from the output directory
- the target added to the project will correctly create this file:
  ```xml
  <Target Name="AddApplicationConfiguration" AfterTargets="AfterBuild">
    <Copy SourceFiles="app.config" DestinationFiles="$(OutDir)testhost.dll.config" />
  </Target>
  ```

Both seem to be satisfied in my tree on Windows, but apparently not on linux or osx. Unfortunately those failures cancel the testing on Windows, so I can't tell whether it really is a platform-specific thing, or something that's just generally different between CI and a normal build env.

**Comment by Zastai** [comment]
I mean, in the end the actual fix is super trivial; in this case, it seems to me like the effort to get a unit test set up is not exactly worth it.

If `RemoteExecutor` were to be extended with support for specifying an `app.config` to use, then things would be a lot easier.

**Comment by steveharter** [comment]
The test should be added to `System.Diagnostics.TraceSource` solution, not the S.SC.M one.

There is infrastructure to add your config file and load it. Search for an existing config like "testhost_AllTypes.config" and modify that as you have in the PR. Then the test will look something like:
```cs
        [Fact]
        [SkipOnPlatform(TestPlatforms.Browser, "Not supported on Browser")]
        [ActiveIssue("https://github.com/dotnet/runtime/issues/74244", TestPlatforms.tvOS)]
        public void Switch_Invalid()
        {
            CreateAndLoadConfigFile("testhost_Switch_Invalid.config");
            var traceSource = new TraceSource("Foo", SourceLevels.Off);
            // When the config is loaded and TraceUtil.CopyStringDictionary() works, you get
            //   System.ArgumentException : 'foo' is not a valid attribute for type 'System.Diagnostics.TraceSource'.
            Assert.Throws<ArgumentException>(() => traceSource.TraceInformation("Test"));
        }
```

A quick test locally **without** your fix shows:
```
  Message: 
    Assert.Throws() Failure: Exception type was not an exact match
    Expected: typeof(System.ArgumentException)
    Actual:   typeof(System.InvalidCastException)
    ---- System.InvalidCastException : Unable to cast object of type 'System.Collections.DictionaryEntry' to type 'System.String'.

  Stack Trace: 
    ConfigurationTests.Switch_Invalid() line 330
    RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
    MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) line 57
    ----- Inner Stack Trace -----
    TraceUtils.CopyStringDictionary(StringDictionary source, StringDictionary dest) line 208
    TraceConfiguration.InitializingTraceSource(Object sender, InitializingTraceSourceEventArgs e) line 100
    TraceSource.OnInitializing(InitializingTraceSourceEventArgs e) line 506
    TraceSource.Initialize() line 85
    TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String format, Object[] args) line 282
    TraceSource.TraceInformation(String message) line 418
    <>c__DisplayClass11_0.<Switch_Invalid>b__0() line 330
```

**Comment by Zastai** [comment]
Aha - thanks, that helps a lot

**Comment by Zastai** [comment]
Moved the unit test; still works locally, hopefully it'll work in CI too now.

**Comment by Zastai** [comment]
If I'm reading this right, these latest test failures are timeouts rather than actual failures, which is unfortunate.

One of the failures points to https://helix.dot.net/api/2019-06-17/jobs/73dd59fe-5b20-4bc0-8cce-387a2650e269/workitems/iOS.Device.ExportManagedSymbols.Test/console which contains

```
[23:19:24] dbug: Running /private/tmp/helix/working/B4B3097B/p/microsoft.dotnet.xharness.cli/9.0.0-prerelease.23611.1/tools/net7.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --sdkroot /Applications/Xcode_14.3.app -setenv=RUN_END_TAG=4da1427a-62c7-44a7-93d3-6503404661f4 --disable-memory-limits --devname 00008030-000A21D10E85402E --launchdevbundleid net.dot.iOS.Device.ExportManagedSymbols.Test --wait-for-exit -v -v -v -v -v
ERROR: WORKLOAD TIMED OUT - Killing user command..
```

In addition, the `runtime (Build Installer Build and Test coreclr osx_arm64 Release) ` check is currently listed here as in progress, but clicking through to Azure Pipelines shows

```
##[warning]Received request to deprovision: The request was cancelled by the remote provider.
,##[error]We stopped hearing from agent Azure Pipelines 86. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610
Agent: Azure Pipelines 86
Started: Today at 05:39
Duration: 1h 15m 16s
```

**Comment by steveharter** [comment]
> If I'm reading this right, these latest test failures are timeouts rather than actual failures, which is unfortunate.

When the tests are done, the "Build Analysis" link will show you the known issues and note the timeout was in there.

**Review by steveharter — APPROVED** [review]
Thanks!

**Pull request merged**
