### PR TITLE
[release/5.0-preview1] Fix overaggressive CanBeMadeAtomic check for Set + Notone

### PR DESCRIPTION
**Pull request by stephentoub**
Port https://github.com/dotnet/runtime/pull/33405 to release/5.0-preview1

### CODE REVIEW

**Comment by benaadams** [comment]
Also to  release/5.0-preview2 ?

**Comment by stephentoub** [comment]
> Also to release/5.0-preview2 ?

You have to give me time to type git commands :)

**Review by danmoseley — APPROVED** [review]

**Comment by danmosemsft** [comment]
@dotnet/dnceng clicked on one failure, console output was
```
Executed on dci-mac-build-099.local
/bin/sh: /tmp/helix/working/B48E099B/p/scripts/353d32e8453e455992d1a10ea539ee62/execute.sh: Permission denied
```

I clicked on several and it was always this same machine.

**Comment by ulisesh** [comment]
> @dotnet/dnceng clicked on one failure, console output was
> 
> ```
> Executed on dci-mac-build-099.local
> /bin/sh: /tmp/helix/working/B48E099B/p/scripts/353d32e8453e455992d1a10ea539ee62/execute.sh: Permission denied
> ```
> 
> I clicked on several and it was always this same machine.

I'll take this machine offline and create an issue to investigate

**Comment by MattGal** [comment]
> > @dotnet/dnceng clicked on one failure, console output was
> > ```
> > Executed on dci-mac-build-099.local
> > /bin/sh: /tmp/helix/working/B48E099B/p/scripts/353d32e8453e455992d1a10ea539ee62/execute.sh: Permission denied
> > ```
> > 
> > 
> > I clicked on several and it was always this same machine.
> 
> I'll take this machine offline and create an issue to investigate

@ulisesh that's not the relevant error.  OpenSSL is not configured properly on this machine:

```
/private/tmp/helix/working/9CB9092E/w/AFD208F1/e /private/tmp/helix/working/9CB9092E/w/AFD208F1/e
  Discovering: System.Security.Cryptography.X509Certificates.Tests (method display = ClassAndMethod, method display options = None)
Process terminated. Assertion failed.
X509ChainGetStatusAtIndex returned unexpected error 2
   at Internal.Cryptography.Pal.SecTrustChainPal.ParseResults(SafeX509ChainHandle chainHandle, X509RevocationMode revocationMode) in /_/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/ChainPal.cs:line 299
   at Internal.Cryptography.Pal.SecTrustChainPal.Execute(DateTime verificationTime, Boolean allowNetwork, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationFlag revocationFlag) in /_/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/ChainPal.cs:line 259
   at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, X509Certificate2Collection customTrustStore, X509ChainTrustMode trustMode, DateTime verificationTime, TimeSpan timeout) in /_/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/ChainPal.cs:line 630
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException) in /_/src/libraries/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Chain.cs:line 133
   at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate) in /_/src/libraries/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Chain.cs:line 106
   at System.Security.Cryptography.X509Certificates.Tests.ChainTests.get_TrustsMicrosoftDotComRoot() in /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs:line 31
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at Microsoft.DotNet.XUnitExtensions.ConditionalTestDiscoverer.EvaluateSkipConditions(ITestMethod testMethod, Object[] conditionArguments) in /_/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/ConditionalTestDiscoverer.cs:line 65
   at Microsoft.DotNet.XUnitExtensions.ConditionalTestDiscoverer.TryEvaluateSkipConditions(ITestFrameworkDiscoveryOptions discoveryOptions, IMessageSink diagnosticMessageSink, ITestMethod testMethod, Object[] conditionArguments, String& skipReason, ExecutionErrorTestCase& errorTestCase) in /_/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/ConditionalTestDiscoverer.cs:line 101
   at Microsoft.DotNet.XUnitExtensions.ConditionalFactDiscoverer.CreateTestCase(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo factAttribute) in /_/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/ConditionalFactDiscoverer.cs:line 19
   at Xunit.Sdk.FactDiscoverer.Discover(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo factAttribute) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\FactDiscoverer.cs:line 55
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 119
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 132
   at Xunit.Sdk.TestFrameworkDiscoverer.FindTestsForTypeAndWrapExceptions(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestFrameworkDiscoverer.cs:line 156
   at Xunit.Sdk.TestFrameworkDiscoverer.<>c__DisplayClass26_0.<Find>b__0() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestFrameworkDiscoverer.cs:line 101
   at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _) in C:\Dev\xunit\xunit\src\common\XunitWorkerThread.cs:line 37
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2370
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2352
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 172
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2310
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2246
   at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ThreadPoolTaskScheduler.cs:line 36
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 47
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 172
   at System.Threading.ThreadHelper.ThreadStart(Object obj) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 75
Unknown Chain Status: GrayListedLeaf
./RunTests.sh: line 161: 84426 Abort trap: 6           (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Security.Cryptography.X509Certificates.Tests.runtimeconfig.json --depsfile System.Security.Cryptography.X509Certificates.Tests.deps.json xunit.console.dll System.Security.Cryptography.X509Certificates.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonnetcoreapptests -notrait category=nonosxtests $RSP_FILE
/private/tmp/helix/working/9CB9092E/w/AFD208F1/e
----- end Tue Mar 10 08:17:13 PDT 2020 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
+ export _commandExitCode=134
+ _commandExitCode=134

```

Take it offline and ping @parose1

**Comment by MattGal** [comment]
@danmosemsft the access denied issue is actually a bug fixed in master which we didn't port to the release branches (has to do with how the AzDO reporter works).  @ulisesh will create an issue and get the fix backported shortly.

**Comment by danmosemsft** [comment]
OK thanks!

**Comment by danmosemsft** [comment]
BTW mentioned offline, but for others benefit I shared that "Unknown Chain Status: GrayListedLeaf" is already fixed in master.

**Comment by danmosemsft** [comment]
per tactics, we will just document for preview 1.

**Pull request closed without merging**
