### PR TITLE
Update SDK to preview 6

### PR DESCRIPTION
**Pull request by am11**
Related: https://github.com/dotnet/arcade/pull/14925
Related https://github.com/dotnet/runtime/issues/104737

### CODE REVIEW

**Comment by akoeplinger** [comment]
Given the prevalence of https://github.com/dotnet/dnceng/issues/3304 and https://github.com/dotnet/dnceng/issues/3100 I wonder if we should postpone the P6 upgrade and upgrade straight to P7

**Comment by am11** [comment]
Is it due to preview 6? I saw that SDK is at preview 5 and yet it's also failing. Normally when we have a tracking / known issue, we do not block the progression.

**Comment by am11** [comment]
Is it due to preview 6? I saw that dotnet/sdk repo is at preview 5 and yet it's also failing with the same error. Normally when we have a tracking / known issue, we do not block the progression.

**Comment by ViktorHofer** [comment]
I discussed this with @mmitche offline and our consensus was that repos strongly affected by the NuGet restore issue should manually update to a P7 SDK (ideally to the one that we use inside the VMR).

Runtime definitely meets the bar but I would recommend to do that in a follow-up PR.

**Comment by am11** [comment]
https://github.com/dotnet/runtime/issues/104765 is tracking inlinearray test failure. (behavior changed in https://github.com/dotnet/runtime/pull/103612, we don't use live-builds everywhere..)

**Comment by am11** [comment]
@ilonatommy TBH that merge was really unnecessary. It took several hours to get it to good state.. :(

**Comment by ilonatommy** [comment]
Merging was blocked by merge conflict, without it we would not be able to close this PR.

**Comment by am11** [comment]
> Merging was blocked by merge conflict coming from this one: #104751, without it we would not be able to close this PR.

There was no merge conflict. If two PRs are changing the same line with same delta, git is smart enough to mark it no-diff. i.e. https://github.com/dotnet/runtime/pull/104696/commits/8a4a2cf932a63ebbd26c21b9842220da913c1bd5 has no delta.

**Comment by ilonatommy** [comment]
Oh, I did not know that, sorry. In this situation we can use `/ba-g` to unblock the merge and do it before CI finishes, as it was already green before and the merge change is non-breaking. Right?

**Comment by ViktorHofer** [comment]
Let's wait until CI finishes. This isn't on any critical path.

**Comment by am11** [comment]
@ViktorHofer if there is nothing else, please get this in this week. You probably know this, it is not really non-critical either. Among other things, we should be testing builds with new SDK to find out issues in outerloop etc. The sooner we do that the faster we will know of issues, resolve and stabilize.

**Review by ViktorHofer — CHANGES_REQUESTED** [review]
I'm inclined to hold off on this until we figured out the root cause that forced us to revert the SDK upgrade in Arcade: https://github.com/dotnet/arcade/pull/14933, cc @mmitche

**Comment by ericstj** [comment]
@mmitche can you let us know if there's anything blocking this update?

**Comment by mmitche** [comment]
> @mmitche can you let us know if there's anything blocking this update? You mentioned there:
> 
> > Potentially unblocks some symbol publishing timeouts in build promotion
> 
> Did that turn out to be fixed by undoing the SDK update, or not?

This was in arcade's usage of p6 in the publishing process. This would not be affected by upgrading here. In fact, I think it would be largely good to get a bit more dogfooding as we didn't get a chance to dig into that failure.

**Comment by ericstj** [comment]
Wow, the elusive green PR validation build 😮 🟢 

Are we OK merging this one @ViktorHofer?

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Let's try things out :shipit:

**Comment by jakobbotsch** [comment]
> I discussed this with @mmitche offline and our consensus was that repos strongly affected by the NuGet restore issue should manually update to a P7 SDK (ideally to the one that we use inside the VMR).
> 
> Runtime definitely meets the bar but I would recommend to do that in a follow-up PR.

What is the process for doing this, and when can we do that? The issue highlighted by @akoeplinger above is super disruptive.

**Comment by mmitche** [comment]
Update the repo's global.json with the new SDK version. That said, this will get updated today in Arcade as part of the normal release process, then flow out to repos afterward.

**Pull request merged**
