### PR TITLE
Add AssemblyName overload for ILVerify.IResolver.Resolve method

### LINKED ISSUE #65573: ILVerify.IResolver with AssemblyName
### Discussed in https://github.com/dotnet/runtime/discussions/64068

<div type='discussions-op-text'>

<sup>Originally posted by **KalleOlaviNiemitalo** January 20, 2022</sup>
In the ILVerify.IResolver interface, the Resolve method has only `string simpleName` as a parameter. Can an implementation of this interface get more information about the assembly reference? Preferably the referenced AssemblyName like in [AssemblyLoadContext.Load](https://docs.microsoft.com/dotnet/api/system.runtime.loader.assemblyloadcontext.load?view=net-6.0), and perhaps also a MetadataReader on the referencing module. I would use this to simulate .NET Framework assembly probing when verifying a set of assemblies that support .NET Framework.

<https://github.com/dotnet/runtime/blob/3a25a7f1cc446b60678ed25c9d829420d6321eba/src/coreclr/tools/ILVerification/IResolver.cs#L10-L16>

I found this comment that appears to explain why the AssemblyName is not passed to IResolver, but am not sure what it means.

<https://github.com/dotnet/runtime/blob/3a25a7f1cc446b60678ed25c9d829420d6321eba/src/coreclr/tools/ILVerification/ILVerifyTypeSystemContext.cs#L31-L36></div>

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #65573

### CODE REVIEW

**Comment by jkotas** [comment]
@KalleOlaviNiemitalo Does this change address your concern?

**Comment by jkotas** [comment]
@jcouv This will require small adjustment on the Roslyn side.

**Review by MichalStrehovsky — APPROVED** [review]

**Comment by KalleOlaviNiemitalo** [comment]
This looks OK, but I haven't tried in practice yet. Also, this does not add information about the referencing assembly to the error if the referenced assembly is not found.

**Comment by KalleOlaviNiemitalo** [comment]
The netmodule resolver `PEReader Resolve(string simpleName)` still doesn't get information about the assembly to which the module belongs. That feature could be useful if the assembly being verified references multiple versions of a multimodule assembly. I have not needed that feature in production though, and multimodule assemblies are going to become even rarer in the future.

**Comment by KalleOlaviNiemitalo** [comment]
Typo in the PR title: ILVerity vs. ILVerify.

**Comment by jkotas** [comment]
@KalleOlaviNiemitalo Thank you for the feedback. I have added AssemblyName argument to the resolve module callback.

**Pull request merged**
