### PR TITLE
Remove SOS_README.md from every app's OutDir

### LINKED ISSUE #33648: Please remove SOS_README.md from every app's OutDir
This file is trite and pointless, but if I fail to install it alongside my app, it won't launch because this file is written into the deps.json file, and is therefore treated as vital. It comes from the `Microsoft.NETCore.App.Runtime.win-x64` runtime pack, and I am not entirely certain how to stop it from being included. Nor am I successful with removing it at build time using injected MSBuild targets. Could someone please point me to the correct way to do this (or submit a PR to remove that file from the runtime packs, which would be even better)? Thanks!

### PR DESCRIPTION
**Pull request by mikem8361**
Issue #https://github.com/dotnet/runtime/issues/33648

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Review by stephentoub — COMMENTED** [review]
Thanks.

**Comment by stephentoub** [comment]
Should we service this?

**Comment by mikem8361** [comment]
I don’t know if it meets the bar for servicing.

**Comment by nathan-alden-hp** [comment]
@mikem8361 I ran into an issue related to the inlcusion of this file in .NET Core app publishing. Can I expect this file to be removed completely and no longer included in `.deps.json` in .NET Core SDK 3.1.300?

**Comment by mikem8361** [comment]
Not for 3.1.x. This fix only went into the 5.0 sdk/runtimes.

**Pull request merged**
