### PR TITLE
[mono][aot] Refactor deduplication to use enum instead of flags

### PR DESCRIPTION
**Pull request by kotlarmilos**
This PR contributes to https://github.com/dotnet/runtime/issues/83973. It doesn't change the behavior and improves code maintenance by using deduplication enum instead of multiple flags.

Related PRs are https://github.com/dotnet/runtime/pull/84304 and https://github.com/dotnet/runtime/pull/85044.

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Comment by kotlarmilos** [comment]
The change has been tested by measuring the number of methods and size on HelloiOS app, and also by evaluating the speed on a WASM console sample app. Here are the results:
 - HelloiOS bundle size difference: 5kb
 - Number of symbols: No changes detected (94,633)
 - WASM performance template (`Vector<T>.Zero + Vector<T>.Zero`): No changes detected (~9,500 timer ticks)

[HelloiOS-base.zip](https://github.com/dotnet/runtime/files/11354262/HelloiOS-base.zip)
[HelloiOS-target.zip](https://github.com/dotnet/runtime/files/11354266/HelloiOS-target.zip)
[symbols-list.zip](https://github.com/dotnet/runtime/files/11354270/symbols-list.zip)

**Comment by kotlarmilos** [comment]
The failures are known issues and shouldn't be related.

**Pull request merged**
