### PR TITLE
fix the loading of  Microsoft.VisualBasic.Core/Microsoft.VisualBasic.Core.sln  in VS

### PR DESCRIPTION
**Pull request by Anipik**
Relates to https://github.com/dotnet/project-system/issues/5878

### CODE REVIEW

**Comment by ericstj** [comment]
Can you explain what was wrong and how this fixes it?

**Review by danmoseley — APPROVED** [review]
The change is fine but please remove the comment "Fixes dotnet/project-system#5878" We do not want to close that issue. VS should never hang no matter what sln and project files I feed it. They should investigate that bug.

**Review by stephentoub — APPROVED** [review]

**Comment by Anipik** [comment]
> Can you explain what was wrong and how this fixes it?

I was able to find that there was no configuration specified relating to the src\*.vbproj. This was the only difference between this and if we just create a new solution and add a bunch of projects.
I dont know why we were not hitting it earlier.

**Comment by Anipik** [comment]
the cmake failure is known

**Pull request merged**
