### PR TITLE
[wasm][debugger] GetProperties broken on chrome

### PR DESCRIPTION
**Pull request by thaystg**
After #62627 we need to change the test and fix the implementation.

### CODE REVIEW

**Review by ilonatommy — APPROVED** [review]

**Comment by radical** [comment]
How was it broken?

**Comment by radical** [comment]
I mean, in what way was it broken.

**Comment by thaystg** [comment]
As it wasn't returning an array as it's expected, when we try to expand the getters we are getting this as result:
image
And the expected behavior is:
image

**Comment by thaystg** [comment]
Wow, I think it would be better to pass NULL as the name value, so we would see something like this, which is more similar to VS:
image

**Pull request merged**
