### PR TITLE
[RISC-V] Use getUnrollThreshold() to get unroll limits

### PR DESCRIPTION
**Pull request by minxuanz**
#83274

### CODE REVIEW

**Review by EgorBo — APPROVED** [review]
LGTM. Btw, I was wondering about this: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Buffer.cs#L5

It enables block store/copy on Loongarch but doesn't on RISC-V - is it expected?

**Comment by EgorBo** [comment]
Or in other words, what is the RISC-V codegen for:
```cs
void Foo(ref byte dst, ref byte src)
{
    Unsafe.CopyBlockUnaligned(ref dst, ref src, 64);
}
```
?

**Comment by monstercatss** [comment]
hi,@clamp03 
Could you please review and help answer?
I don't have a riscv machine yet
may call memcpy

**Comment by clamp03** [comment]
@monstercatss Thank you so much!
@bartlomiejko Could you (or someone in SRPOL) review and help @monstercatss for testing? And I think we missed some LOONGARCH PR (like #62888) Please check. CC @sirntar @tomeksowi

**Comment by tomeksowi** [comment]
> LGTM. Btw, I was wondering about this: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Buffer.cs#L5
> 
> It enables block store/copy on Loongarch but doesn't on RISC-V - is it expected?

Yes, the ISA we're currently targeting is RV64GC, no "V" (vector ops) extension.

**Review by tomeksowi — APPROVED** [review]

**Review by clamp03 — APPROVED** [review]

**Comment by EgorBo** [comment]
> > LGTM. Btw, I was wondering about this: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Buffer.cs#L5
> > It enables block store/copy on Loongarch but doesn't on RISC-V - is it expected?
> 
> Yes, the ISA we're currently targeting is RV64GC, no "V" (vector ops) extension.

SIMD is not necessary here, `HAS_CUSTOM_BLOCKS` implies that e.g. 
```cs
void Foo(ref byte dst, ref byte src)
{
    Unsafe.CopyBlockUnaligned(ref dst, ref src, 64);
}
```
is inlined in codegen whether to a set of simd or GPR stores or MEMSET call.

**Comment by tomeksowi** [comment]
> SIMD is not necessary here, `HAS_CUSTOM_BLOCKS` implies that e.g.
> 
> ```cs
> void Foo(ref byte dst, ref byte src)
> {
>     Unsafe.CopyBlockUnaligned(ref dst, ref src, 64);
> }
> ```
> 
> is inlined in codegen whether to a set of simd or GPR stores (supports such blocks) or MEMSET call (doesn't support). According to
> 
> ```diff
> + // | riscv64 | 64 | 32 | no SIMD support
> ```

In that case, I think you're right. The only caveat I can think of is the one discussed [here](https://github.com/dotnet/runtime/pull/98484#discussion_r1494406559). Currently Unsafe.CopyBlockUnaligned generates misaligned GPR loads/stores; in theory the ISA we're compiling against [permits not supporting them](https://github.com/riscv/riscv-isa-manual/blob/d69bfb84324f34a60859e8160efa1709bcfd87e3/src/rv32.adoc?plain=1#L706-L732) (that's RV32, and I don't see RV64 overriding that). In practice I don't know of a general-purpose RISC-V 64-bit implementation that doesn't support misaligned load/stores for non-atomic instructions, RVA20U64 profile even mandates it.

We're currently focusing on bugfixing and missing features, codegen optimizations will come later. We'll have to think what to do about it, maybe .NET should simply require it and compile with `-mno-strict-align`. @brucehoult any thoughts?

**Comment by EgorBo** [comment]
Totally makes sense! 

> Currently Unsafe.CopyBlockUnaligned generates misaligned GPR loads/stores; i

I presume it can emit a set of byte stores (for that, you will need to decrease the threshold in `getUnrollThreshold` to avoid emitting 64 byte stores for 64 byte blocks 🙂) but that can be done separately. Also, I presume it'll make sense to revise the base class library to find places where unaligned loads are assumed to be cheap.

**Comment by brucehoult** [comment]
> > SIMD is not necessary here, `HAS_CUSTOM_BLOCKS` implies that e.g.
> > ```cs
> > void Foo(ref byte dst, ref byte src)
> > {
> >     Unsafe.CopyBlockUnaligned(ref dst, ref src, 64);
> > }
> > ```

If RV64GC then there are really only two sensible things to do:

1) an inline byte by byte loop, or

2) call memcpy()

> In that case, I think you're right. The only caveat I can think of is the one discussed [here](https://github.com/dotnet/runtime/pull/98484#discussion_r1494406559). Currently Unsafe.CopyBlockUnaligned generates misaligned GPR loads/stores; in theory the ISA we're compiling against [permits not supporting them](https://github.com/riscv/riscv-isa-manual/blob/d69bfb84324f34a60859e8160efa1709bcfd87e3/src/rv32.adoc?plain=1#L706-L732) (that's RV32, and I don't see RV64 overriding that). In practice I don't know of a general-purpose RISC-V 64-bit implementation that doesn't support misaligned load/stores for non-atomic instructions, RVA20U64 profile even mandates it.

The profile mandates that non-aligned load/store don't crash the program in User-mode programs. Implementations are free to trap to M mode and have SBI emulate it. The necessary code is always present, just in case, so for example accesses that cross a cache like or VM page might trap even if others don't.

It seems VisionFive 2 does support misaligned, but not very quickly.

    #include <stdio.h>
    
    int main(){
        char *s = "The quick brown fox";
        unsigned long t = 0;
        for (int i=0; i<1000000000; ++i){
          t += *(volatile unsigned long*)(s+1);
        }
        printf("%ld\n", t);
        return 0;
    }

With -O1 this takes 11.4s vs 2.0s if the amount added to s is a multiple of 8.

(I checked the codegen and it's the expected "ld;add;addiw -1;bnez")

On the Lichee Pi 4A (THead C910) it's 4.65s vs 1.1s

On my x86 box (2990wx) it's 0.27s either way.

As a comparison, using the following takes 3.36s on VF2, so it's a bit faster than doing misaligned in hardware:

    t += ((*(volatile unsigned long*)(s)) >> 8) | ((*(volatile unsigned long*)(s+8)) << 56);

On the Lichee Pi it takes 1.65s, almost three times faster than the misaligned access. On the AMD it takes 0.51s, almost twice as slow as the misaligned access.

So ... avoid misaligned access if possible, but it's not a complete disaster if it happens sometimes, on the cores we have now, and future cores.

**Comment by monstercatss** [comment]
> Totally makes sense!
> 
> > Currently Unsafe.CopyBlockUnaligned generates misaligned GPR loads/stores; i
> 
> I presume it can emit a set of byte stores (for that, you will need to decrease the threshold in `getUnrollThreshold` to avoid emitting 64 byte stores for 64 byte blocks 🙂) but that can be done separately. Also, I presume it'll make sense to revise the base class library to find places where unaligned loads are assumed to be cheap.

btw，Is threshold just based on performance? Is it faster to use memset call when size is larger than 512 on x86 avx512?

**Comment by jakobbotsch** [comment]
Can you please fix the formatting errors and conflicts?

**Comment by monstercatss** [comment]
> Can you please fix the formatting errors and conflicts?

done

**Review by jakobbotsch — APPROVED** [review]

**Pull request merged**
