### PR TITLE
Update dependencies for dotnet/optimization to build 20230626.3

### PR DESCRIPTION
**Pull request by hoyosjs**
Unblocks preview 6 by updating PGO data: https://github.com/dotnet/runtime/issues/87807

### CODE REVIEW

**Review by jeffschwMSFT — APPROVED** [review]
lgtm

**Review by jkotas — APPROVED** [review]

**Comment by jkotas** [comment]
> src\native\corehost\build.cmd" Release x86

This is https://github.com/dotnet/runtime/issues/88172  (build break introduced by VS update on build machines)

**Comment by hoyosjs** [comment]
Confirmed the regression is fixed

**Comment by hoyosjs** [comment]
Test failure was https://github.com/dotnet/runtime/issues/84392. All other legs didn't exercise this path.

**Pull request merged**
