### PR TITLE
[mono] Enable MBR by default if interpreter is enabled

### PR DESCRIPTION
**Pull request by lambdageek**
Enable Mono MBR support by default.
Goal is to check that there are no perf regressions for non-MBR scenarios

### CODE REVIEW

**Comment by lambdageek** [comment]
@naricc assuming the tests here look ok, would it be possible to do a perf comparison of [`alklig/enable-metadata-update` branch in dotnet/runtime](https://github.com/dotnet/runtime/tree/alklig/enable-metadata-update) vs the normal runtime.  primarily interested in interp on desktop and wasm, but for sanity-checking also normal JIT numbers are interesting - just to make sure I didn't put update checking on some hotpath.

**Comment by naricc** [comment]
@lambdageek Yes; I should be able to do that tomorrow. The runs take on the order of hours, so probably we will have the results tomorrow afternoon. The way it is setup it always runs everything in the pipeline, so we will get results for JIT, desktop interpreter, and WASM.

**Comment by naricc** [comment]
Performance runs:

    Interpreter: https://pvscmdupload.blob.core.windows.net/drewtest/report_Daily_ca%3Dx64_cb%3Drefs-heads-alklig-enable-metadata-update_co%3DUbuntu1804_cr%3Ddotnetruntime_cc%3DCompilationMode%3Dtiered-LLVM%3Dfalse-MonoAOT%3Dfalse-MonoInterpreter%3Dtrue-RunKind%3Dmicro_mono_bb%3Drefs-heads-master_2021-01-15.html

    JIT: https://pvscmdupload.blob.core.windows.net/drewtest/report_Daily_ca%3Dx64_cb%3Drefs-heads-alklig-enable-metadata-update_co%3DUbuntu1804_cr%3Ddotnetruntime_cc%3DCompilationMode%3Dtiered-LLVM%3Dfalse-MonoAOT%3Dfalse-MonoInterpreter%3Dfalse-RunKind%3Dmicro_mono_bb%3Drefs-heads-master_2021-01-15.html

    WASM: https://pvscmdupload.blob.core.windows.net/drewtest/report_Daily_ca%3Dx64_cb%3Drefs-heads-alklig-enable-metadata-update_co%3DUbuntu1804_cr%3Ddotnetruntime_cc%3DCompilationMode%3Dwasm-RunKind%3Dmicro_bb%3Drefs-heads-master_2021-01-15.html

**Comment by lambdageek** [comment]
I've looked at profiles of interpreter results on `Burgers2`, `Compare_Exchange(long)` and `System.Collections.Concurrent.Count<String>` using Instruments on OSX.  But in all cases, the actual timing of the runs was pretty inconsistent so I'm not convinced that the perf runs are highlighting an actual problem.  (Wasm run was more definitive - I had turned off interpreter inlining on all wasm runs - it was hurting performance).

 I was able to identify some differences in profiles, primarily due to profiler choices around `mono_metadata_decode_row` and `mono_metadata_decode_row_col`.  I added https://github.com/dotnet/runtime/pull/47716, but it doesn't not alter the run times in any meaningful way. (it does nudge the xcode clang inliner to the same choices as before, so the profile stack traces look more similar, and I think it's better to logically separate the slow path with an explicit state change.)

My overall conclusion is that the microbenchmark runs did not highlight actionable issues in turning on the metadata update code by default.

The other PRs that came out of this perf investigation are:
- https://github.com/dotnet/runtime/pull/47505
- https://github.com/dotnet/runtime/pull/47246

**Comment by lambdageek** [comment]
Closing this PR. it was only for the perf investigation

**Pull request closed without merging**
