### PR TITLE
Fix SIMD store to spilled multi-reg local

### LINKED ISSUE #37761: System.Numerics.Vectors.Tests failing on checked Linux arm with assert failure
```
  Discovering: System.Numerics.Vectors.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Numerics.Vectors.Tests (found 1195 test cases)
  Starting:    System.Numerics.Vectors.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 130 [0x00000082], Thread: 144 [0x0090]): Assertion failed 'varReg != REG_NA' in 'System.Numerics.Tests.QuaternionTests:QuaternionCreateFromYawPitchRollTest2():this' during 'Generate code' (IL size 262)

    File: /__w/1/s/src/coreclr/src/jit/codegenarm64.cpp Line: 1945
    Image: /root/helix/work/correlation/dotnet

./RunTests.sh: line 161:   130 Aborted                 "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Numerics.Vectors.Tests.runtimeconfig.json --depsfile System.Numerics.Vectors.Tests.deps.json xunit.console.dll System.Numerics.Vectors.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/root/helix/work/workitem
----- end Thu Jun 11 18:33:17 UTC 2020 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
```

https://helix.dot.net/api/2019-06-17/jobs/dba44811-bf3b-46c9-a0ff-cc9127e458d2/workitems/System.Numerics.Vectors.Tests/console
https://dev.azure.com/dnceng/public/_build/results?buildId=682815&view=ms.vss-test-web.build-test-results-tab
cc: @tannergooding @CarolEidt

### PR DESCRIPTION
**Pull request by CarolEidt**
Fix #37761

### CODE REVIEW

**Comment by CarolEidt** [comment]
There were three problems with a spilled store to a multi-reg local where the source is a single SIMD register:
- First, the register allocator doesn't actually give a local node a register if it's going to be immediately spilled - the code generator simply writes the result to the stack. However, if the target is a multi-reg node, and the source is not (which is currently only supported for SIMD HFAs, so only Arm64), then it needs to have the register to extract into.
- Second, we weren't calling `genProduceReg`, which handles spill. This isn't needed if it's directly written to the stack, and if it's in a register it can't be a GC pointer (which an HFA field will never be) so it won't need tracking, but it is needed if we need to spill it.
- Third, the liveness code wasn't happy to see a promoted local marked for spill. However, this is a redundant check (it won't spill if the local has already marked as being on the stack), so I added an assert that for a multireg local, there are no remaining fields in registers if it's marked for spill. Then we can skip the redundant check. I think this merits a cleanup (I don't think there should ever be remaining spill at this point).

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib PTAL

**Comment by CarolEidt** [comment]
@safern - the 3 arm/arm64 libraries tests legs have timed out twice. The Release build of the System.Numerics.Vectors.Tests pass on my arm64/linux system. Is this a known issue?

**Review by BruceForstall — APPROVED** [review]

**Comment by CarolEidt** [comment]
Thanks very much @safern - can you educate me about how to find those test logs?

**Comment by safern** [comment]
@CarolEidt yeah of course:

First you go to the "Send to Helix" step logs in the build and look for the helix job-id:
Screen Shot 2020-06-12 at 11 38 58 AM

Then you can just construct the URL:
https://helix.dot.net/api/2019-06-17/jobs/{jobID}/workitems/{workitemName}

Workitem name is the test assembly name.

**Comment by safern** [comment]
Btw, this are the available helix APIs to get info about a run:
https://helix.dot.net/swagger/ui/index

**Comment by CarolEidt** [comment]
Thanks @safern!

**Pull request merged**
