### PR TITLE
[NativeAOT] Address some COOP native helpers that could cause suspension pauses.

### LINKED ISSUE #73655: [NativeAOT] Review COOP helpers that may cause long GC suspension pauses.
`RhpCopyObjectContents` can cause long pauses when copying large arrays.
it was observed on `System.Security.Cryptography.Tests`.

Other `COOP_PINVOKE_HELPER` need to be examined as well on whether the potential wait is bounded and short.
For example `RhCompareObjectContentsAndPadding` might have the same issues.

In the copy object/array case, we can use the same approach as in CoreClr that does the copying in managed code and if needs to set cards, does it in chunks. Perhaps the code can be unified?

`RhBulkMoveWithWriteBarrier`  has the same issue. Long pauses were observed when running `System.Private.Uri.Functional.Tests`

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: https://github.com/dotnet/runtime/issues/73655
 
Fixes common cases of unbounded data copying in COOP mode, that may cause suspension pauses. 
(Such pauses were actually observed while testing and measuring suspension changes)

Also moves `Buffer.Memmove<T>` to shared code to be used by both CoreCLR and NativeAOT. 

I think Mono may use it too and benefit form interruptibility, in theory, but I am not sure. 
For blobs containing GC references, we perform GC-atomic card-updating copies in chunks which are not necessarily aligned to array elements. I am not sure if Mono `BulkMoveWithWriteBarrier` can be used like this.

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thanks!

**Comment by VSadov** [comment]
Thanks!

**Comment by VSadov** [comment]
@BrzVlad  Re: `BulkMoveWithWriteBarrier` . Just wonder - can Mono move `BulkMoveWithWriteBarrier` on the same shape as CoreCLR and NativeAOT? 
If that is possible, Mono could also benefit from the shared implementation of `Buffer.Memmove<T>`

**Comment by BrzVlad** [comment]
@VSadov Yeah, it is fairly straightforward. I opened issue https://github.com/dotnet/runtime/issues/78498 so I remember to do it sometime in the future.

**Pull request merged**
