### PR TITLE
Add missing space padding before exception message in log

### PR DESCRIPTION
**Pull request by maryamariyan**
Fixes: #39531

### CODE REVIEW

**Comment by davidfowl** [comment]
Screenshot?

**Comment by maryamariyan** [comment]
>Screenshot?

The ones on the issue description? yes!

**Review by tarekgh — APPROVED** [review]

**Comment by danmosemsft** [comment]
test timeout
```
Half-way through waiting for remote process.
Memory load: 17

Image Name                     PID Services                                    
========================= ======== ============================================
svchost.exe                    668 DcomLaunch, PlugPlay, Power                 
svchost.exe                    740 RpcEptMapper, RpcSs                         
svchost.exe                    808 Dhcp, eventlog, lmhosts, vmictimesync       
svchost.exe                    876 CryptSvc, Dnscache, LanmanWorkstation,      
                                   NlaSvc, WinRM                               
svchost.exe                    912 AeLookupSvc, Appinfo, BITS, CertPropSvc,    
                                   gpsvc, iphlpsvc, LanmanServer, ProfSvc,     
                                   sacsvr, Schedule, seclogon, SENS,           
                                   SessionEnv, ShellHWDetection, Winmgmt,      
                                   wuauserv                                    
svchost.exe                    956 AppIDSvc                                    
svchost.exe                    980 EventSystem, FontCache, netprofm, nsi,      
                                   W32Time, WinHttpAutoProxySvc                
svchost.exe                    336 Netman, TrkWks, UmRdpService, UxSms,        
                                   vmickvpexchange, vmicshutdown, vmicvss      
svchost.exe                    456 BFE, DPS, MpsSvc, pla                       
svchost.exe                   1164 vmicheartbeat, vmicrdv                      
svchost.exe                   1264 AppHostSvc                                  
svchost.exe                   1300 DiagTrack                                   
svchost.exe                   1576 RemoteRegistry                              
svchost.exe                   1640 W3SVC, WAS                                  
svchost.exe                   2092 TermService                                 
Timed out at 7/17/2020 7:16:55 PM after 60000ms waiting for remote process.
Wrote mini dump to: C:\h\w\A2BC0914\w\AAFF096A\uploads\1040.a50bts1w.14y.dmp
	Process ID: 1040
	Handle: 1696
	Name: dotnet
	MainModule: C:\h\w\A2BC0914\p\dotnet.exe
	StartTime: 7/17/2020 7:15:54 PM
	TotalProcessorTime: 00:00:01.0937500
	Threads:
		Thread #1 (OS 0x1054)   [MTA]
			[HelperMethodFrame_1OBJ] (System.Threading.Monitor.ObjWait)
			System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)
			System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken)
			System.Threading.Tasks.Task.InternalWaitCore(Int32, System.Threading.CancellationToken)
			System.Threading.Tasks.Task.InternalWait(Int32, System.Threading.CancellationToken)
			System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
			System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task)
			System.Runtime.CompilerServices.TaskAwaiter.GetResult()
			Microsoft.DotNet.RemoteExecutor.Program.Main(System.String[])
		Thread #2 (OS 0x1070) [Finalizer] [Background] [MTA]
			[DebuggerU2MCatchHandlerFrame]
		Thread #3 (OS 0x3CC) [Thread pool worker] [Background] [MTA]
		Thread #5 (OS 0x186C) [Thread pool completion port] [Background] [MTA]
		Thread #7 (OS 0x348) [Thread pool worker] [Background] [MTA]

```

**Comment by wfurt** [comment]
it should not be debian-10 if the main process is dotnet.exe, right?

**Review by eerhardt — APPROVED** [review]
:shipit:

**Comment by ericstj** [comment]
This was approved for preview8.  Merge when ready.  Also be sure to make the same fix to master.

**Comment by maryamariyan** [comment]
dotnet-linker-tests is hung for three days. I'd merge as it's unrelated to this PR.

**Pull request merged**
