### PR TITLE
Bump intellisense version to RC1 (main)

### PR DESCRIPTION
**Pull request by carlossanlop**
The .NET 6.0 RC1 documentation is live now in MS Docs: https://docs.microsoft.com/en-us/dotnet/api/?view=net-6.0

I generated the IntelliSense nuget package version for that branch. Here's the pipeline output of the package push: https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=253085&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=11e7ea89-affe-5194-cdc6-0171c3394706

This is the change for `main`. I'll send a separate PR for the RC2 branch (after it gets snapped).

### CODE REVIEW

**Comment by carlossanlop** [comment]
@dotnet/runtime-infrastructure The CI is failing to find the intellisense package. Any idea what could be causing this?

```
Build.proj(0,0): error NU1102: (NETCORE_ENGINEERING_TELEMETRY=Restore) Unable to find package Microsoft.Private.Intellisense with version (= 6.0.0-preview-20210914.1)
  - Found 2 version(s) in dotnet-public [ Nearest version: 1.0.0-rc3-24214-00 ]
  - Found 2 version(s) in dotnet6-transport [ Nearest version: 5.0.0-preview-20201104.1 ]
  - Found 1 version(s) in dotnet-eng [ Nearest version: 3.0.0-preview8-190815-0 ]
  - Found 1 version(s) in dotnet-tools [ Nearest version: 3.0.0-preview8-190815-0 ]
  - Found 0 version(s) in richnav
  - Found 0 version(s) in dotnet6
  - Found 0 version(s) in dotnet7-transport
  - Found 0 version(s) in dotnet7
```

**Comment by carlossanlop** [comment]
@joperezr helped me. Apparently the package is being pushed to a feed called `dotnet5-transport` but we expect `dotnet6-transport` now, according to this file: https://github.com/dotnet/runtime/blob/0c903477b052afc317c15f922e62f9883f88e2fa/NuGet.config#L22

I'll contact the Docs Dev team so they fix the feed to which they publish the intellisense nuget package, then I will regenerate the pacakge, and will then update this PR with the new package number.

**Comment by carlossanlop** [comment]
@ericstj @Anipik the nuget package was successfully consumed after we fixed the feed URL. Can I get a sign-off so I can cherry-pick this to the RC2 branch?

**Review by jeffhandley — APPROVED** [review]

**Comment by ViktorHofer** [comment]
> @joperezr helped me. Apparently the package is being pushed to a feed called dotnet5-transport but we expect dotnet6-transport now, according to this file:

.NET 7 (main) should not consume packages from the dotnet6* feeds. Instead we should publish that package to the dotnet7-transport feed as well. cc @mmitche

**Pull request merged**
