### PR TITLE
ServiceProcess Controller Refactor

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
1. Simplified if checks.
2. Use expression property syntax.
3. Used using-declaration.
4. Inline `out` declaration.
5. Removed unwanted unsafe modifier.
6. Removed redundant casting.

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
thanks

**Comment by danmosemsft** [comment]
Ah, I just remembered that we don't get coverage of the ServiceController tests in CI, because many of them require they are run in an elevated prompt. I will run them.

**Comment by MCCshreyas** [comment]
> Ah, I just remembered that we don't get coverage of the ServiceController tests in CI, because many of them require they are run in an elevated prompt. I will run them.

Sure, Thanks! 😇😇

**Comment by danmosemsft** [comment]
```
C:\git\runtime>.\build.cmd clr+libs+libs.tests -rc release -lc release
```
admin prompt
```
C:\git\runtime\src\libraries\System.ServiceProcess.ServiceController\tests>\git\runtime\.dotnet\dotnet build /t:test /p:outerloop=true -c Release
...
  pushd C:\git\runtime\artifacts\bin\System.ServiceProcess.ServiceController.Tests\net6.0-Windows_NT-Release\
...
  ===========================================================================================================
    Discovering: System.ServiceProcess.ServiceController.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.ServiceProcess.ServiceController.Tests (found 36 of 37 test cases)
    Starting:    System.ServiceProcess.ServiceController.Tests (parallel test collections = on, max threads = 8)
    Finished:    System.ServiceProcess.ServiceController.Tests
  === TEST EXECUTION SUMMARY ===
     System.ServiceProcess.ServiceController.Tests  Total: 39, Errors: 0, Failed: 0, Skipped: 0, Time: 67.660s
  ----- end Mon 10/26/2020 11:40:38.07 ----- exit code 0 ----------------------------------------------------------
```

So we're good.

**Comment by MCCshreyas** [comment]
Hi @danmosemsft, while doing refactoring of code I saw weird syntax of writing comments take a look at this following line of comment
https://github.com/dotnet/runtime/blob/9b3575d8e9580647a7ca4f910460d95906865a57/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs#L100

From my understanding, it should be like this in the summary block. 
```
///<summary>
/// Tells if the service referenced by this object can be paused. 
///</summary>
```
By doing this, if anyone hovers over the mouse on that given code block, they can able to see this description in the tooltip. Current comments don't show up in the tooltip because VS is not able to parse that comments.

So, would you accept a PR of fixing this comments issue? I will be happy to do that! I know that is not adding any value to code, but that maintains the code quality and provides a good user experience!

Thanks!

**Comment by danmosemsft** [comment]
@MCCshreyas sure, thanks

**Comment by MCCshreyas** [comment]
> @MCCshreyas sure, thanks

OK, I will open PR this weekend! Thanks for support and reply! Really appreciated! 😊

**Pull request merged**
