### PR TITLE
Reenable GetHostAddressesTest_Cancellation on Unix

### PR DESCRIPTION
**Pull request by rzikm**
The original issue (#33378) is marked as closed by (#34633).

### CODE REVIEW

**Comment by wfurt** [comment]
do we know if anything releavent changed or is this just opportunistic?

**Comment by rzikm** [comment]
I have just noticed this when looking at https://github.com/dotnet/runtime/issues/69993

**Review by stephentoub — APPROVED** [review]
If they work, LGTM

**Comment by antonfirsov** [comment]
#34633 has been reverted, there is still no async name resolution and cancellation support on Linux, therefore we should undo this PR.

There was a GitHub bookkeeping problem with `[ActiveIssue()]` referencing a closed issue #33378 (with the "solution" eventually reverted).

**Pull request merged**
