### PR TITLE
[IGNORE] [Experiment] Try to return MSBuild Server back.

### PR DESCRIPTION
**Pull request by AR-May**
This is an experimental PR, do not merge. 
Goal: running the CI with an MSBuild fix.

### CODE REVIEW

**Comment by lewing** [comment]
problem appears to still be there

**Comment by AR-May** [comment]
> problem appears to still be there

Well, the fix is not yet there. The fix is in sdk build 7.0.100-rtm.22479.5, but these ones are still running at rc 1. I am still trying to figure out how to upgrade it.

**Comment by lewing** [comment]
https://github.com/dotnet/runtime/pull/76220

**Comment by marcpopMSFT** [comment]
@lewing , some of the build legs like `Build Browser wasm windows Release WasmBuildTests` don't appear to be using the directory.build.props updates included that should override the known framework references. Any ideas on those?
https://dev.azure.com/dnceng-public/public/_build/results?buildId=41146&view=logs&j=f386e426-bcac-5c89-397e-589b8da0ec42&t=801956ba-ad06-543c-70c6-b6c4added600

**Comment by radical** [comment]
> @lewing , some of the build legs like `Build Browser wasm windows Release WasmBuildTests` don't appear to be using the directory.build.props updates included that should override the known framework references. Any ideas on those?

Could you please point to those updates?

**Comment by lewing** [comment]
Wasm build tests would need overrides for the workload package versions but we don't really need to resolve that if 
`runtime (Build Browser wasm Linux Release AllSubsets_Mono_RuntimeTests) ` is failing the way it is to know that msbuild still has an issue

**Comment by radical** [comment]
`Wasm.Build.Tests` install the `wasm-tools*` workloads using the manifest packages in `artifacts`. These manifests use the 6.0 version from `$(PackageVersionNet6)`, which is currently `6.0.10`. And that would need to be updated too. And these versions are used in:

https://github.com/dotnet/runtime/blob/d462be072d71d98534da318d3418465f788ecea1/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.net6.Manifest/Microsoft.NET.Workload.Mono.Toolchain.net6.Manifest.pkgproj

https://github.com/dotnet/runtime/blob/d462be072d71d98534da318d3418465f788ecea1/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Manifest/Microsoft.NET.Workload.Mono.Toolchain.Manifest.pkgproj

https://github.com/dotnet/runtime/blob/d462be072d71d98534da318d3418465f788ecea1/src/mono/wasm/Wasm.Build.Tests/Wasm.Build.Tests.csproj

**Comment by AraHaan** [comment]
Honestly, I feel that the build-server in CI's is not great anyway, due to the fact that you technically only need to use msbuild for ``build``/``pack`` and then nuget to push packages (conditionally). As such I think it is beneficial to just keep it off for everyone whenever they run the .NET SDK in their CI's by default (turning it off seems to help solve a few problems as well in CI on a few of my repos recently as well).

**Pull request closed without merging**
