### PR TITLE
Arm32 Crossgen2 initial support

### PR DESCRIPTION
**Pull request by davidwrighton**
- Fix type layout bugs
  - Sequential or Explicit layout classes without explicit field offsets on arm32 should align their fields based on the start of the field list of the object
  - The field base offset used for R2R calculation on Arm32 should respect the RequiresAlign8 flag
  - Computing true for requiresAlign8 in auto field layout should set the alignment of a class to 8 during auto layout
  - if a class derives from an type which requires 8 byte alignment, set the derived to require higher alignment
- Align the EH info table on 4 byte boundaries
- Set the thumb bit on the arm32 personality routine RVA in XData
- Enable Crossgen2 smoke test for arm
- Adjust type system architecture specific layout tests to match CoreCLR behavior

With this, crossgen2 is able to compile the crossgen2smoke test for Windows arm32, and run it, with the framework also run through crossgen2.

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/crossgen-contrib

**Review by trylek — APPROVED** [review]
Looks beautiful, thank you!

**Comment by davidwrighton** [comment]
Sigh, Linux arm32 doesn't quite work. I'll investigate that today.

**Review by trylek — COMMENTED** [review]
Thanks for fixing the export table alignments, that was obviously my fault!

**Comment by trylek** [comment]
Linux arm leg passes, congrats!

**Comment by gbalykov** [comment]
@davidwrighton Could you, please, share further tasks related to arm32, which are required for full arm32 (armhf/armel) support in crossgen2? We are investigating performance and bugs in crossgen2 on armel tizen, for example, #43035 issue is related and was fixed by this PR.

**Pull request merged**
