### PR TITLE
Use IndexOf in NamespaceCache.SynthesizeNamespaceData

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
Would a Count(T) method on `Span<T>` be worthwhile?

**Comment by gfoidl** [comment]
> Would a Count(T) method on `Span<T>` be worthwhile?

Kind of popcount for Span<T>.
Thus such an implementation could be vectorized quite easily.

**Comment by stephentoub** [comment]
That's https://github.com/dotnet/runtime/issues/59466

**Comment by stephentoub** [comment]
Failure is https://github.com/dotnet/runtime/issues/75329

**Pull request merged**
