### PR TITLE
Adjust weights of blocks with profile inside loops in non-profiled methods

### LINKED ISSUE #71649: PGO: Static profile affects loop alignment where it's not supposed to do
Extracted from dotnet/performance:
```csharp
    private static uint[] input_uint = Enumerable.Range(0, 1000).Select(i => (uint)i).ToArray();

    [MethodImpl(MethodImplOptions.NoInlining)]
    public int TrailingZeroCount_uint()
    {
        int sum = 0;
        uint[] input = input_uint;
        for (int i = 0; i < input.Length; i++)
            sum += BitOperations.TrailingZeroCount(input[i]);
        return sum;
    }
```
Codegen diff: https://www.diffchecker.com/dIVV1Iwy
Left: `ReadyToRun=1`, Right: `ReadyToRun=0`

My theory that when we collect the profile for `TrailingZeroCount` we don't have BMI on that machine so it messes weights up which then inmported into this loop and mark it as non-profitable to align.

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/71649 (and a couple of related performance regressions in dotnet/performance).

Repro:
```csharp
using System;
using System.Linq;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Threading;

public class Program
{
    public static void Main()
    {
        for (int i = 0; i < 50; i++)
        {
            new Program().Test();
            Thread.Sleep(50);
        }

        Console.WriteLine("Done");
        //Console.ReadKey();
    }

    uint[] input_uint = Enumerable.Range(0, 1000).Select(i => (uint)i).ToArray();

    [MethodImpl(MethodImplOptions.NoInlining |
                MethodImplOptions.AggressiveOptimization)]
    public int Test()
    {
        int sum = 0;
        uint[] input = input_uint;
        for (int i = 0; i < input.Length; i++)
            sum += BitOperations.TrailingZeroCount(input[i]);
        return sum;
    }
}
```

When we run this, `Test` is not profiled, but it imports inside its loop `BitOperations.TrailingZeroCount` which is profiled (static BCL profile). Then `optSetBlockWeiths` divides its weight by 2 because it doesn't dominate all returns and the current method does not have profile data, see [here](https://github.com/dotnet/runtime/blob/05c446760221714de2f433956d2778c4b17b31b7/src/coreclr/jit/optimizer.cpp#L80-L124).
At the same time, `optScaleLoopBlocks` does not touch loop body because it has profile data so it doesn't scale it back to something "hot". My PR changes that - if the root method is not profiled - we try to adjust weights in such loops.

Codegen diff https://www.diffchecker.com/dIVV1Iwy 
Left: ReadyToRun=0, Right: ReadyToRun=1 - take a look at loop body (its weight is 1 in case of static pgo so loop aligner does not think it's profitable to align)

cc @AndyAyersMS

### CODE REVIEW

**Comment by EgorBo** [comment]
Fixes these perf regressions: https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_28_2022/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Numerics.Tests.Perf_BitOperations.html

**Review by AndyAyersMS — APPROVED** [review]
I thought about doing something like this but was concerned that it might have much wider impact than I'd like. But it might be worth a try.

We should prepare for a follow-on perf assessment to determine if this is a net improvement.

Looking at SPMI there are quite a few affected methods. Oddly no diffs from benchmarks. I wonder if that collection is broken right now or something?

**Comment by EgorBo** [comment]
@AndyAyersMS how do I run SPMI and get a sort of statistics - how many methods with PGO data, how many loops were clonned - etc?

**Comment by AndyAyersMS** [comment]
> @AndyAyersMS how do I run SPMI and get a sort of statistics - how many methods with PGO data, how many loops were clonned - etc?

You would have to do something custom... we have never gotten around to implementing the "generalized metrics" work that would make this sort of thing easy.

**Comment by EgorBo** [comment]
I hacked it locally - only +10 new loop clonning, around 200 regressions (among 1200 in libraries.pmi) are due to loop-alignment (so number are better with `-jitoption JitAlignLoops=0`) - the rest look like "random" block shuffling, nothing looks super offensive so far so I assume we can merge and then watch for improvements/regressions.

**Comment by EgorBo** [comment]
Improvements on linux-x64 https://github.com/dotnet/perf-autofiling-issues/issues/6724

**Comment by AndyAyersMS** [comment]
Regression on arm64: https://github.com/dotnet/perf-autofiling-issues/issues/6746

**Comment by mrsharm** [comment]
We noticed that this PR is associated with the following regression across a few configurations. Specifically looking at the x64 Windows historical data, we observed a clear regression: 

image

Strangely, we cannot find an associated issue in the Perf Auto-filler and runtime repos for this configuration. 
 
<details>

System.Collections.IndexerSet<String>.Array(Size: 512)

| Result |Ratio | Alloc Delta | Operating System      | Bit   | Processor Name                                  |
| ------ |-----:| -----------:| --------------------- | ----- | ----------------------------------------------- |
| Same   | 1.00 |          +0 | Windows 11            | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Same   | 1.00 |          +0 | Windows 11            | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Same   | 0.99 |          +0 | macOS Monterey 12.3   | Arm64 | Apple M1 Max                                    |
| Slower | 0.88 |          +0 | Windows 10            | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Slower | 0.83 |          +0 | Windows 10            | X64   | Intel Core i7-6700 CPU 3.40GHz (Skylake)        |
| Slower | 0.85 |          +0 | Windows 10            | X64   | Intel Core i7-6700 CPU 3.40GHz (Skylake)        |
| Slower | 0.84 |          +0 | Windows 10            | X64   | Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R)   |
| Slower | 0.83 |          +0 | Windows 10            | X64   | Intel Core i9-10900K CPU 3.70GHz                |
| Slower | 0.57 |          +0 | Windows 11            | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
| Slower | 0.59 |          +0 | Windows 11            | X64   | AMD Ryzen 9 3950X                               |
| Slower | 0.66 |          +0 | Windows 11            | X64   | AMD Ryzen 9 5900X                               |
| Slower | 0.64 |          +0 | Windows 11            | X64   | AMD Ryzen 9 5950X                               |
| Slower | 0.83 |          +0 | Windows 11            | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    |
| Slower | 0.84 |          +0 | Windows 11            | X64   | Intel Core i9-10900K CPU 3.70GHz                |
| Slower | 0.77 |          +0 | Windows 11            | X64   | 11th Gen Intel Core i9-11900H 2.50GHz           |
| Slower | 0.86 |          +0 | ubuntu 18.04          | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Faster | 1.16 |          +0 | ubuntu 18.04          | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) |
| Slower | 0.85 |          +0 | ubuntu 18.04          | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    |
| Slower | 0.67 |          +0 | ubuntu 20.04          | X64   | AMD Ryzen 9 5900X                               |
| Slower | 0.83 |          +0 | ubuntu 20.04          | X64   | Intel Core i9-10900K CPU 3.70GHz                |
| Same   | 1.00 |          +0 | Windows 10            | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Same   | 0.98 |          +0 | Windows 10            | X86   | Intel Core i7-6700 CPU 3.40GHz (Skylake)        |
| Same   | 1.00 |          +0 | Windows 11            | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
| Slower | 0.89 |          +0 | macOS Big Sur 11.6.8  | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       |
| Slower | 0.86 |          +0 | macOS Monterey 12.3.1 | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     |
| Slower | 0.88 |          +0 | macOS Monterey 12.4   | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       |

</details>

**Comment by danmoseley** [comment]
@EgorBo is the regression above resolved or do we need an issue for it?

**Comment by Jozkee** [comment]
Ping @EgorBo. This popped up in the 6.0 vs 7.0 RC2 report as well.

**Comment by EgorBo** [comment]
Thanks, looking at the issue, it was expected to see improvements and regressions from that change

**Pull request merged**
