### PR TITLE
[tests] Re-enable generic math Create tests on iOS

### LINKED ISSUE #61920: [iOS][tvOS] Generic math IntPtr SByte and Int16 test failures
The following generic math tests fail on iOS/tvOS devices:

IntPtrTests:
- CreateSaturatingFromSByteTest
- CreateSaturatingFromInt16Test
- CreateTruncatingFromSByteTest
- CreateTruncatingFromInt16Test
- TryCreateFromSByteTest
- TryCreateFromInt16Test

Each failure is due to actual results being positive when it's expected they are negative.

For example:
```
TryCreateFromSByteTest()

Expected: -128
Actual: 128
```

### PR DESCRIPTION
**Pull request by lambdageek**
Fixes https://github.com/dotnet/runtime/issues/61920

Fixed by https://github.com/dotnet/runtime/pull/66739

### CODE REVIEW

**Comment by lambdageek** [comment]
`Build tvOS arm64 Release AllSubsets_Mono` on runtime-extra-platforms passed the System.Runtime testsuite, and failed other unrelated tests.

**Review by steveisok — APPROVED** [review]

**Review by mdh1418 — APPROVED** [review]
Looks good to me! Thanks

**Comment by lambdageek** [comment]
Failures are unrelated

**Pull request merged**
