### PR TITLE
Override BaseType in TypeRefTypeSystemType

### PR DESCRIPTION
**Pull request by jakobbotsch**
BaseType is being used to determine whether the type is a value type or
class type. This meant that `dotnet-pgo merge` would always produce
metadata saying that all types were class types.

In practice, this meant that we had the following behavior:
```
.\dotnet-pgo.exe merge --input IBCTrace28800.mibc --output identity.mibc
.\dotnet-pgo.exe merge --input IBCTrace28800.mibc --input identity.mibc --output foo.mibc
Opening IBCTrace28800.mibc
Opening identity.mibc
Unhandled exception. System.Exception: Same type `[S.P.CoreLib]System.ReadOnlySpan`1` used as both ValueType and non-ValueType
   at Microsoft.Diagnostics.Tools.Pgo.TypeRefTypeSystem.TypeRefTypeSystemType.SetIsValueType(Boolean isValueType)
   at Microsoft.Diagnostics.Tools.Pgo.TypeRefTypeSystem.TypeRefTypeSystemContext.TypeRefSignatureParserProvider.GetTypeFromReference(MetadataReader reader, TypeReferenceHandle handle, Byte rawTypeKind)
```

The same problem would occur when using compare-mibc to compare a
merged mibc file with some of its constituents. These scenarios work
now.

I don't think this actually has any negative effect when the runtime consumes the .mibc files, however, though I have not looked in detail.

cc @davidwrighton

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Hmm, maybe I should rather change `MetadataType` to override and seal `BaseType`, forwarding it to `MetadataBaseType`?

**Comment by MichalStrehovsky** [comment]
> Hmm, maybe I should rather change `MetadataType` to override and seal `BaseType`, forwarding it to `MetadataBaseType`?

That would make calling BaseType a lot slower because it becomes two virtual calls most of the time.

Maybe we can now use covariant returns and simply replace:

```csharp
        public abstract MetadataType MetadataBaseType { get; }
```

with

```csharp
        public abstract override MetadataType BaseType { get; }
```

?

**Comment by MichalStrehovsky** [comment]
Or if we want to keep the ability to run the typesystem on downlevel runtimes, just add an `abstract override` of BaseType to force the children of MetadataType to override it.

We actually had the same bug in (in a different MetadataType derivative) in NativeAOT so it would be nice to do something systematic to prevent it.

@davidwrighton Do you have an opinion?

**Comment by davidwrighton** [comment]
I like the idea @MichalStrehovsky has around using a covariant return override. While I like the ability to compile targetting older runtimes, its not something that has actually been particularly valuable recently, and dotnet 5.0 is old enough for me. If the covariant approach doesn't work though, adding the re-abstraction of BaseType to force children of MetadataType to override it is completely worth it. If you make the covariant override, make sure to remove MetadataBaseType and just have BaseType everywhere.

**Comment by jakobbotsch** [comment]
It was problematic to use covariant returns since `$(NetCoreAppToolCurrent)` is .NET 6. There are also a few tools in the base (ILVerify, ILVerification are two) that target earlier versions. After speaking to @MichalStrehovsky offline we decided to go with the re-abstract approach instead for now.

**Review by davidwrighton — APPROVED** [review]

**Pull request merged**
