### PR TITLE
SPMI: Implement fallback schema layout

### LINKED ISSUE #74718: SPMI with `JitNoInline=1` asserts in instrumentation code
Reproduction: run an SPMI replay of the `aspnet` collection with `-jitoption JitNoInline=1`.

Expected result: clean replay.

Actual result:
```
ISSUE: <ASSERT> #1 C:\Users\Accretion\source\dotnet\runtime\src\coreclr\jit\fgprofile.cpp (1709)
Assertion failed 'reinterpret_cast<uint8_t*>(h32->HandleTable) == &m_profileMemory[tableEntry.Offset]'
in 'LoggingConfiguration:Close():this' during 'Profile instrumentation'
(IL size 112; hash 0xe34aa6a7; Instrumented Tier1-OSR)
```
Preceded by a number of `ERROR: AllocPgoInstrumentationBySchema mismatch`.

`JitNoInline` can be a nice setting to verify changes "modulo inlining", it would be nice to keep it assert-free.

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fallback to doing actual layout of the schema data when the schema does not match the recorded schema. This ensures replays are still consistent with the recording in cases where the JIT and environment variables match, but that we can still succeed a replay on changes to these.

Fix #74718

### CODE REVIEW

**Comment by jakobbotsch** [comment]
I still need to double check why inlining has an impact on schema layout.

**Comment by jakobbotsch** [comment]
> I still need to double check why inlining has an impact on the requested schema.

Hmm, I actually cannot reproduce this anymore, even with this change reverted. @SingleAccretion does it still reproduce for you?

**Comment by SingleAccretion** [comment]
@jakobbotsch just checked, it doesn't.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
@EgorBo can you take a look at this?

**Review by EgorBo — APPROVED** [review]
Interesting, curious why we didn't see any asserts/crashes before

**Comment by jakobbotsch** [comment]
> Interesting, curious why we didn't see any asserts/crashes before

It's pretty rare that the schema is different, but we have seen those in a few cases

**Pull request merged**
