### PR TITLE
Public sign ilasm output by default

### LINKED ISSUE #47426: ILAsm should support public signing
Related https://github.com/dotnet/runtime/issues/12132
Originally reported https://github.com/dotnet/runtime/issues/42250 and https://github.com/dotnet/sdk/issues/15225

Public signing is supported by our other compilers and should be added to ILAsm. 
 It should be pretty cheap.  https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/public-signing.md
Here's what it looks like: https://github.com/dotnet/buildtools/blob/78260239e4db68ad5c2df774a27d5f9a54fd92e5/src/Microsoft.DotNet.Build.Tasks/OpenSourceSign.cs#L71

cc @briansull

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #47426

### CODE REVIEW

**Comment by jkotas** [comment]
cc @briansull @ericstj

**Comment by ericstj** [comment]
Looks ok, I don’t suppose this would break anyone?

**Review by ericstj — APPROVED** [review]

**Comment by jkotas** [comment]
I do not expect that this will break anyone. We can always add command line option for it if necessary. I have started by adding a command line option, but then decided to keep it simple and just set it by default.

**Comment by ericstj** [comment]
If we do make the commandline option we should make sure to update the ILProj SDK to honor the publicsign property so that we'll set it (and not regress the fix where we needed it).

**Comment by briansull** [comment]
I took a look, Looks like it should work to me.

**Pull request merged**
