### PR TITLE
Update pull request/issue management bot configuration

### PR DESCRIPTION
**Pull request by DragosDanielBoia**
Allow users to get tagged after a PR or an issue is opened, when new labels defined in the config are added.

### CODE REVIEW

**Review by jeffhandley — APPROVED** [review]
Thanks, @DragosDanielBoia! As we maintain this going forward, we'll consider the trade-off of using `labelAdded` without specifying the list of `label` values.

If we went that approach, the result of the task would be a bunch of `if` statements that are all false -- would that still function OK?

**Comment by DragosDanielBoia** [comment]
@jeffhandley can you give me an example with your config, will test it and see if it's working.

**Comment by jeffhandley** [comment]
Sure thing. It would be removing the `label:` portion of the `labelAdded` condition, with the intent of matching any event where a label was added.

```yml
name: area-label-routing
description: Area Label Routing
resource: repository
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - if:
      - or:
        - payloadType: Issues
        - payloadType: Pull_Request
      - isAction:
          action: Opened
      - or:
        - labelAdded
      then:
      - if:
        - hasLabel:
            label: area-AssemblyLoader-coreclr
        then:
        - mentionUsers:
            mentionees:
            - vitek-karas
            - agocke
            - vsadov
            replyTemplate: >-
              Tagging subscribers to this area: ${mentionees}
              See info in [area-owners.md](https://github.com/dotnet/runtime/blob/main/docs/area-owners.md) if you want to be subscribed.
            assignMentionees: False
      - if:
        - hasLabel:
            label: area-AssemblyLoader-mono
        then:
        - mentionUsers:
            mentionees: []
            replyTemplate: >-
              Tagging subscribers to this area: ${mentionees}
              See info in [area-owners.md](https://github.com/dotnet/runtime/blob/main/docs/area-owners.md) if you want to be subscribed.
            assignMentionees: False
      description: Area-owners
```

**Comment by DragosDanielBoia** [comment]
Not sure if this is going to work is you don't specify the labels, will try this next week and let you know.
- or:
     - labelAdded

**Pull request merged**
