### PR TITLE
Update void struct to readonly struct

### PR DESCRIPTION
**Pull request by Gallimathias**
I wonder why the void struct is not readonly. With this content i believe it could be.

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
Thanks for the contribution. I'm curious - what inspired this? Does marking this struct _readonly_ unblock any of your scenarios?

**Comment by jkotas** [comment]
This was discussed in https://github.com/dotnet/coreclr/pull/14789#discussion_r148280488

**Comment by Gallimathias** [comment]
@GrabYourPitchforks this was a idea in a livestream, so no real use case :D

**Comment by Gallimathias** [comment]
Ok now i try it a little bit on my PC and i want to close this because with readonly a method call is in average 1152,6 Ticks slower than without readonly. (No perfect test).

**Pull request closed without merging**
