### PR TITLE
Implement SinPi, CosPi and TanPi and inverses

### PR DESCRIPTION
**Pull request by huoyaoyuan**
Part of #20137

Implementations are copied from boost/math. However, I can't find AsinPi/AcosPi/AtanPi implementation there. It feels better to add them together.

Question: IEEE754 spec explicitly specifies +0 and -0. Do we need to test it?

### CODE REVIEW

**Comment by tannergooding** [comment]
Thanks for your contribution. I'll need to do a license check to confirm boost is compatible (I believe it is) and also consider whether this is something we are willing to take as the implementation.

In particular, there are some potential problems to implementing this as managed code such as the ease in which we can add constant folding support in the JIT. This likewise differs from the [amd/aocl-libm-ose](https://github.com/amd/aocl-libm-ose) implementation I was looking into for this already, which is known to be performant and which is effectively an extension of the code that already powers the x64 Windows math implementations (which is `amd/win-libm`).

> Question: IEEE754 spec explicitly specifies +0 and -0. Do we need to test it?

Yes. We need explicit tests for all edge cases explicitly specified by IEEE 754. That includes the special handled of `+0` and `-0` for `sinpi`, `cospi`, and `tanpi`. It likewise includes:
* `sinpi(+n)` is `+0` and `sinpi(-n)` is `-0` for positive integer `n`
* `cospi(n + 0.5)` is `+0` for any integer `n` where `n + 0.5` is representable
* `tanpi(2 * n + 0.5)` is `+infinity` for positive integer `n`
* `tanpi(2 * n + 1)` is `-0` for positive integer `n`
* `tanpi(2 * n + 1.5)` is `-infinity` for positive integer `n`
* `tanpi(2 * n + 2)` is `+0` for positive integer `n`
* `tanpi(2 * n - 0.5)` is `-infinity` for negative integer `n`
* `tanpi(2 * n - 1)` is `+0` for negative integer `n`
* `tanpi(2 * n - 1.5)` is `+infinity` for negative integer `n`
* `tanpi(2 * n - 2)` is `-0` for negative integer `n`

**Comment by huoyaoyuan** [comment]
Yes I've read IEEE spec (I have access through my university).
So boost's implementation is effectively wrong, because it returns -0 for odd numbers.
I think I can write a new implementation.

**Comment by huoyaoyuan** [comment]
Inverses should be fairly easier, since there's no need to fold the numbers.

**Comment by jeffhandley** [comment]
@tannergooding This PR is assigned to you for follow-up/decision before the RC1 snap.

**Comment by tannergooding** [comment]
Thanks for the contribution here @huoyaoyuan. Due to it being so late in the cycle, this is going to miss out on the .NET 6 release and we'll instead be able to merge it after the RC1 snap and we begin accepting changes for .NET 7 (ETA: 3-4 weeks)

**Comment by huoyaoyuan** [comment]
The implementation (in fact software fallbacks) may benefit from generic math. I agree to delay it and make it a very first consumer of generic math.

**Comment by jeffhandley** [comment]
> The implementation (in fact software fallbacks) may benefit from generic math. I agree to delay it and make it a very first consumer of generic math.

@huoyaoyuan / @tannergooding Should we close this PR then to have it replaced with a new one that uses that approach?

**Comment by tannergooding** [comment]
@jeffhandley, beyond that I think this needs more consideration with regards to the future direction of System.Math (as alluded to in https://github.com/dotnet/runtime/pull/53675#issuecomment-853908049).

We still need to determine if implementing this in managed vs native is appropriate and should ensure that whatever we choose stays generally consistent (in terms of algorithm source and implementation location) for the various Math APIs.

**Comment by jeffhandley** [comment]
Closing this PR as the direction is uncertain at this time. Thank you, @huoyaoyuan; this effort is contributing to our strategic thinking in the Math space, so your PR was valuable even though it's not being merged.

**Pull request closed without merging**
