### PR TITLE
Allow build with VS2022 installed

### PR DESCRIPTION
**Pull request by BrennanConroy**

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
Seems reasonable, if it works for you.

**Comment by danmoseley** [comment]
thanks @BrennanConroy

**Comment by lpatalas** [comment]
@danmoseley Regarding the failure you linked above https://github.com/dotnet/runtime/pull/52487#issuecomment-836124100 - it's probably intermittent AzDO issue. @MattGal elaborated a bit more about it here: https://github.com/dotnet/runtime/pull/52420#issuecomment-834563842.

**Comment by ViktorHofer** [comment]
cc @AntonLapounov 

should we also update https://github.com/dotnet/runtime/blob/403ae357667dfd46c7bfb0a657566d6890ecbb0c/eng/native/gen-buildsys.cmd#L31-L32 or change it so that it doesn't hardcode the VS versions?

**Comment by AntonLapounov** [comment]
At present CMake has no special support for Visual Studio 2022, so we should probably use "Visual Studio 16 2019" unconditionally for now.  The `vs2017` line may be deleted.

**Pull request merged**
