### PR TITLE
More preparation for JIT\Regression test merging

### PR DESCRIPTION
**Pull request by markples**
This is another collection of changes that can be merged independently of actual test merging. It may be easier to look at each commit separately. I have them collected here in order to just do one PR process, but I can split them if needed. Automated changes were done with the ILTransform tool (started by @trylek, my version at https://github.com/markples/utils/tree/for-PR-dotnet-runtime-79697, commit 6324a32f).

[Remove test JIT/Regression/VS-ia64-JIT/V1.2-Beta1/b102887 - identical…](https://github.com/dotnet/runtime/pull/79697/commits/6bb8742da49ac7c5c955d8879990f5ae862938bf)
- Tests JIT/Regression/VS-ia64-JIT/V1.2-Beta1/b102887 and JIT/Regression/VS-ia64-JIT/V1.2-M02/b28077 were identical

[Dedup class names in GitHub_23199](https://github.com/dotnet/runtime/pull/79697/commits/179cf76c8e3311a5787aa4a3f71eef23e8044199)
- JIT/Regression/JitBlue/GitHub_23199 used #ifdefs to create 32 and 64 bit versions of the test
- Both versions can run on any host
- Duplicate the test with different names and no ifdefs
- Run both versions on all hosts

[Merge b399444 into one test that handles both cases](https://github.com/dotnet/runtime/pull/79697/commits/e3504642f1e1ae3bf5a44837ec6566362cf97c0c)
- JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b399444 used #ifdefs to create two tests
- Combine both into one test that checks both without #ifdefs
- Delete unused .xml files

[Add RequiresProcessIsolation](https://github.com/dotnet/runtime/pull/79697/commits/40637c5b2db06d12f4511e3affaaf5586acf630c)
- Automated via `ILTransform -prociso`
- Add `<RequiresProcessIsolation>true</RequiresProcessIsolation>` for any test with CLRTestTargetUnsupported, GCStressIncompatible, UnloadabilityIncompatible, JitOptimizationSensitive, TieringTestIncompatible, HeapVerifyIncompatible, IlasmRoundTripIncompatible, SynthesizedPgoIncompatible, or CrossGenTest properties.
- Add `<RequiresProcessIsolation>true</RequiresProcessIsolation>` for any test with CLRTestBashEnvironmentVariable, CLRTestBatchEnvironmentVariable, CLRTestEnvironmentVariable, Content, CMakeProjectReference (not sure about the last two, but they only impact 3 tests and can be examined later)
- Add `<RequiresProcessIsolation>true</RequiresProcessIsolation>` for any test that calls Environment.Exit
- Add comment explaining why RequiresProcessIsolation is set to help with removing them later

[ILTransform -public](https://github.com/dotnet/runtime/pull/79697/commits/40da6588dc15df0e71c790e2152e802cff161a8c)
- Automated via `ILTransform -public`
- Update entry point method (`Main` for C#, whatever is marked `.entrypoint` for IL) to be public
- Update entry point's enclosing type to be public if it exists
- Wrap IL entry points in a new class if one doesn't exist (e.g., CLR-x86-JIT/V1-M09.5-PDC/b10940/b10940a.il)

[Manual fixes for public changes](https://github.com/dotnet/runtime/pull/79697/commits/747ffb7456a28d67e0ad1657ad3a43421dc04fb6)
- These were all C# cases where Main was previously in a non-public type with other public methods that contained non-public types
- Fix in all cases is to just make the other method not public

### CODE REVIEW

**Comment by markples** [comment]
"Build Installer Build and Test coreclr OSX_x64 Release" failure is a timeout.  The entire leg ran incredibly slowly from the beginning (project restore, configuring), so I don't think it is relevant here.

**Comment by markples** [comment]
Note: I force pushed back to an earlier version of this change without class deduplication.  The tests pass with and without, but in doing the next steps I discovered that it appears that all classes, not just the entry point ones, need to be unique.  Therefore, I will be reimplementing the dedup logic.  The changes here can be merged without dedup - I had simply added those since they build on this PR and (I thought) were ready.

**Review by trylek — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
