### PR TITLE
Adding sequential read as the file option in ReadAllBytes

### PR DESCRIPTION
**Pull request by RiskRunner0**
Fixing #40001, adding Sequential Read file option for ReadAllBytes in File.cs.

### CODE REVIEW

**Comment by danmosemsft** [comment]
This seems reasonable/safe, we already use SequentialScan for other similar methods, and StreamReader/StreamWriter always use it (thus also File.ReadAllText, WriteAllText etc)

What about File.InternalWriteAllBytes, WriteAllTextAsync, and AppendAllTextAsync. Should those have it?

**Comment by QueenCitySmitty** [comment]
I think that makes sense, I'd want to validate it with someone else though (relatively new to .NET contributing and internals) so cc: @jkotas thoughts?

**Comment by jkotas** [comment]
> What about File.InternalWriteAllBytes, WriteAllTextAsync, and AppendAllTextAsync. Should those have it?

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea#caching-behavior says that `FILE_FLAG_SEQUENTIAL_SCAN` helps with reading. It does not say anything about writing.

**Comment by danmosemsft** [comment]
@jkotas, right but I see it's on StreamWriter even in .NET Framework.
https://source.dot.net/#System.Private.CoreLib/StreamWriter.cs,169

**Comment by jkotas** [comment]
If we were do add it to the file writing helpers, I would like to see data that prove it helps and does not hurt.

**Comment by danmosemsft** [comment]
For sure. Anyway I think this change can go ahead as its.

**Review by danmoseley — APPROVED** [review]

**Review by jkotas — APPROVED** [review]
@QueenCitySmitty Thank you!

**Comment by QueenCitySmitty** [comment]
@jkotas thank YOU for letting me contribute.. first time! :D

**Comment by QueenCitySmitty** [comment]
Found this one in Up for Grabs, going to keep poking there, thanks for the encouragement!

**Pull request merged**
