### PR TITLE
Specify callback calling convention for callbacks on Windows x86 causes crashes on Mono.

### LINKED ISSUE #88992: [mono] Access Violation when running certain outerloop tests on Windows x86
This happens on e.g. System.Diagnostics.DiagnosticSource.Tests:

```
build.cmd mono+libs -c Release -arch x86
dotnet.cmd build /t:Test /p:RuntimeFlavor=mono /p:TargetArchitecture=x86 /p:TestScope=outerloop -c Release .\src\libraries\System.Diagnostics.DiagnosticSource\tests\ -f net8.0
```

The process crashes pretty much immediately, with exit code -1073741819:
```
  ===========================================================================================
    Discovering: System.Diagnostics.DiagnosticSource.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Diagnostics.DiagnosticSource.Tests (found 30 of 261 test cases)
    Starting:    System.Diagnostics.DiagnosticSource.Tests (parallel test collections = on, max threads = 16)
  ----- end Thu 07/13/2023 18:11:08.71 ----- exit code -1073741819 ----------------------------------------------------------
```

In VS we see the access violation:
image

### PR DESCRIPTION
**Pull request by lateralusX**
Fixes #88992.

CoreCLR runtime build using stdcall while Mono uses cdecl (default for c/c++ source files) as default calling convention. If a native runtime function takes a reverse pinvoke managed callback, this difference will cause issues on Mono Windows x86 since reverse pinvoke callbacks uses stdcall on Windows x86, but native functions calling callbacks have been prototyped to use the "default" calling convention used by native runtime build.

* Since CoreCLR already uses stdcall on Windows x86 this change won't change anything on CoreCLR.
* On Windows x64 stdcall == cdecl so this change won't change anything on CoreCLR, Mono or NativeAOT.

PR also re-enable test suites previously disabled due to this issue as well as making sure native EventPipe tests suites build/run/ pass using Mono Windows x86.

### CODE REVIEW

**Comment by lateralusX** [comment]
Timeout seen in runtime (Build tvos-arm64 Release AllSubsets_Mono) occurs on other PR's as well, so unrelated to changes done in this PR.

**Comment by lateralusX** [comment]
@davmason, mainly a nop change on all platforms except Mono Windows x86 since CoreCLR Windows x86 already uses stdcall as default calling convention for native code.

**Review by davmason — APPROVED** [review]
LGTM

**Comment by lateralusX** [comment]
Failures in runtime-libraries-mono outerloop (Build windows-x86 Release AllSubsets_Mono) test run after fix and re-enabled tests are not related (failure in System.Numerics.Tests.logTest.RunLargeValueLogTests, and System.Collections.Frozen.Tests.FrozenDictionary_Generic_Tests_ulong_ulong.CreateHugeDictionary_Success), so re-enabled tests seems to have been fixed by changes in this PR.

**Comment by lateralusX** [comment]
Errors are infrastructure or known issues.

**Pull request merged**
