### PR TITLE
Add RIDs for Tizen 7.0

### PR DESCRIPTION
**Pull request by JoonghyunCho**
This PR adds RIDs for
  - upcoming Tizen 7.0 Platform version which will be officially released soon in Oct, 2022.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@ericstj do you know if we need a template for this change?

**Review by ViktorHofer — APPROVED** [review]

**Comment by carlossanlop** [comment]
@wfurt can you please provide a review sign-off?

**Review by JongHeonChoi — APPROVED** [review]

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by carlossanlop** [comment]
CI failure is an unexpected termination of the test process.

All looks good. Only pending thing to address is the question:

> @ericstj do you know if we need a template for this change?

**Comment by carlossanlop** [comment]
I'll send the email to Tactics.

**Comment by carlossanlop** [comment]
No issues raised by Tactics, we can consider this approved. Merging now.

**Pull request merged**
