### PR TITLE
Replace usage of out-of-support TFM compiler directives

### PR DESCRIPTION
**Pull request by ViktorHofer**
... and directives for TFMs that we don't target anymore in main.

Replaces the following directives with `NET` or `!NET`:
- `#if NETCOREAPP2*`
- `#if !NETCOREAPP2*`
- `#if NETCOREAPP3*`
- `#if !NETCOREAPP3*`
- `#if NET5*`
- `#if !NET5*`
- `#if NET6*`
- `#if !NET6*`
- `#if NET7*`
- `#if !NET7*`

### CODE REVIEW

**Comment by jkotas** [comment]
> #if NETCOREAPP2*

Is there a reason why you have not replaced `#if NETCOREAPP`?

**Comment by jkotas** [comment]
Some of the test failures look related to the change.

**Comment by ViktorHofer** [comment]
> Is there a reason why you have not replaced #if NETCOREAPP?

Yeah, 300+ hits. i wanted to keep this scoped on the other TFMs. I can send another PR to then replace NETCOREAPP with NET if we want to go that direction.

**Review by carlossanlop — APPROVED** [review]
Do you mind sharing why this change is being made? Why did the old directives lose their value?

Assuming the CI is all good, LGTM.

**Comment by ViktorHofer** [comment]
> Do you mind sharing why this change is being made? Why did the old directives lose their value?

The main branch doesn't benefit from the distinction between NETCOREAPP2 vs NETCOREAPP3 vs NET5 vs NET6 vs NET7 as non of those TFMs are built anymore. Most of them are already out-of-support or soon will be. From a code point perspective, differentiating between .NET Framework, modern .NET and specific modern .NET versions that we target and build in main is sufficient.

Or to rephrase, `NETCOREAPP2` and similar compiler directives are things from the past that we don't need in our main source anymore.

**Pull request merged**
