### PR TITLE
Allow marshalling IL_STUB compilation for ndirect methods using crossgen2 if SPC.dll is in the same bubble

### PR DESCRIPTION
**Pull request by gbalykov**
This is an updated version of https://github.com/dotnet/runtime/pull/54847.

This change reduces number of IL_STUBs compiled during startup on ~70 on tizen xamarin apps. Startup time is improved on ~2.5%.

Fix for `BlittableArrayMarshaller` is required because `Interop/PInvoke/Array/MarshalArrayAsParam/AsDefault/AsDefaultTest/AsDefaultTest.sh` and `Interop/PInvoke/Array/MarshalArrayAsParam/AsLPArray/AsLPArrayTest/AsLPArrayTest.sh` fail when compiled with crossgen2 with input bubble. For example:
```
============ [CStyle_Array_Int_InOut_ZeroLength]	 ============
[CStyle_Array_Int_InOut_ZeroLength] Error: parameter actual is NULL

TEST FAIL: TestLibrary.AssertTestException: Assert.IsTrue: CStyle_Array_Int_InOut_ZeroLength
   at TestLibrary.Assert.HandleFail(String assertionName, String message) in /home/z/Dev/runtime/src/tests/Common/CoreCLRTestLibrary/Assertion.cs:line 734
   at ArrayMarshal.TestMarshalInOut_ByVal() in /home/z/Dev/runtime/src/tests/Interop/PInvoke/Array/MarshalArrayAsParam/AsDefault/AsDefaultTest.cs:line 397
   at ArrayMarshal.Main() in /home/z/Dev/runtime/src/tests/Interop/PInvoke/Array/MarshalArrayAsParam/AsDefault/AsDefaultTest.cs:line 661
```

For both tests problem is with array with 0 length, which is passed as NULL to native function. But it should be a pointer to the non-existing element, and IL_STUB generated at runtime does exactly this. This error might occur even without IL_STUB saving part of this PR when array with 0 length is marshalled in SPC.dll.

Minimal example to reproduce:
```c#
using System;
using System.Runtime.InteropServices;

namespace marshal_test
{
    class Program
    {
  	[DllImport("tmp.so", EntryPoint = "test_func")]
        internal static extern int testFunc([In, Out] int[] value);
	
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
			
	    int[] array = new int[0];

            testFunc(array);
            Console.WriteLine(array.Length);
        }
    }
}
```

```c
#include <malloc.h>
#include <string.h>
#include <stdio.h>

int test_func(int * array)
{
  if (array != NULL)
  {
    printf("NOT NULL ARRAY\n");
  }  
  else
  {
    printf("NULL ARRAY\n");
  }
  return 0;
}
```

cc @alpencolt @jkotas

### CODE REVIEW

**Comment by gbalykov** [comment]
@mangod9 could you, please, take a look? This PR is an updated version of https://github.com/dotnet/runtime/pull/54847

**Comment by jkotas** [comment]
I am not sure we have a high confidence in the correctness of the marshaling stubs generated by crossgen2 to enable it for arbitrary code outside corelib. I believe that @jkoritzinsky plans to delete the interop marshaling stubs generation from crossgen2 now that we have source generators for interop.

**Comment by jkoritzinsky** [comment]
I was planning on removing support for IL stub generation in Crossgen2 as the use cases where it is valid to be used are very small (CoreLib, composite and large version bubble) and shrinking with source-generated interop. And now that CoreLib has moved to source-generated interop, the code is very minimally tested (as you’ve seen) and it’s unused in any mainline scenario.

I just haven’t had the cycles to get around to removing support as I want source-generated P/Invokes to be fully shippable before I remove crossgen2’s marshalling stubs.

**Comment by gbalykov** [comment]
Can you share the status of source generators in .NET 6? Can they already be used to generate IL_STUBs or is this only planned in .NET 7?

**Comment by jkotas** [comment]
The interop source generator is new in .NET 7.

**Comment by gbalykov** [comment]
Thanks for clarification, I'll close this PR then

**Pull request closed without merging**
