### PR TITLE
[mono] Update runtimeFlavor property for Mono AOT perf jobs

### PR DESCRIPTION
**Pull request by kotlarmilos**
This PR updates the `runtimeFlavor` property for Mono AOT performance jobs.

### CODE REVIEW

**Comment by lewing** [comment]
```
[10:30:30] info: [2023-08-09T10:30:30.638Z] [FAIL] System.Net.WebSockets.Client.Tests.InvokerCloseTest.CloseOutputAsync_ClientInitiated_CanReceive_CanClose(server: ws://127.0.0.1:49166/WebSocket/EchoWebSocket.ashx)
[10:30:30] info: Assert.Equal() Failure
[10:30:30] info: Expected: 17
[10:30:30] info: Actual:   0
[10:30:30] info:    at System.Net.WebSockets.Client.Tests.CloseTest.CloseOutputAsync_ClientInitiated_CanReceive_CanClose(Uri server)
[10:30:30] info: --- End of stack trace from previous location ---
[10:30:30] info: [2023-08-09T10:30:30.639Z] [STRT] System.Net.WebSockets.Client.Tests.InvokerCloseTest.CloseOutputAsync_ClientInitiated_CanReceive_CanClose(server: wss://127.0.0.1:49168/WebSocket/EchoWebSocket.ashx)

```

**Comment by pavelsavara** [comment]
> `InvokerCloseTest.CloseOutputAsync_ClientInitiated_CanReceive_CanClose`

Could be just fragile test, let's re-run

**Comment by pavelsavara** [comment]
I created https://github.com/dotnet/runtime/issues/90257 to see if that happens more often

**Comment by kotlarmilos** [comment]
The failure doesn't look related to the changes in this PR, could be a transient issue.

**Review by LoopedBard3 — APPROVED** [review]

**Pull request merged**
