### PR TITLE
Optimize ReadOnlyTernaryTree for System.Private.Xml

### PR DESCRIPTION
**Pull request by kronic**

### CODE REVIEW

**Comment by danmoseley** [comment]
Thanks @kronic I'll let area owner review this. One thing that would really help reviewers in future would be to keep formatting and functional changes separate. Either a separate PR (if large) or at least a separate commit 😄

**Comment by kronic** [comment]
@danmoseley I will consider in the future

**Comment by eiriktsarpalis** [comment]
Hi @kronic, we would need a bit more information on this PR. Would it be possible to 1) provide a synopsis of the performance optimizations you are attempting to make and 2) share benchmarks demonstrating the improvements? Thanks.

**Comment by kronic** [comment]
@Eiriktsarpalis I will do when free time will appear

**Comment by kronic** [comment]
before System.Private.Xml.dll size 3 087 360 byte
|                 Method |     Mean |   Error |   StdDev |   Median |      Min |      Max |  Gen 0 |  Gen 1 | Allocated |
|----------------------- |---------:|--------:|---------:|---------:|---------:|---------:|-------:|-------:|----------:|
|      WriteStartElement | 451.1 ns | 9.52 ns | 10.58 ns | 453.1 ns | 429.5 ns | 466.2 ns | 0.8927 | 0.0238 |      7 KB |
| WriteStartElementIdent | 473.2 ns | 9.32 ns |  8.72 ns | 474.9 ns | 458.1 ns | 488.2 ns | 0.8960 | 0.0243 |      7 KB |

after System.Private.Xml.dll size 3 086 848 byte
|                 Method |     Mean |   Error |  StdDev |   Median |      Min |      Max |  Gen 0 |  Gen 1 | Allocated |
|----------------------- |---------:|--------:|--------:|---------:|---------:|---------:|-------:|-------:|----------:|
|      WriteStartElement | 437.8 ns | 7.44 ns | 7.30 ns | 438.6 ns | 424.5 ns | 454.8 ns | 0.8929 | 0.0237 |      7 KB |
| WriteStartElementIdent | 465.4 ns | 8.97 ns | 9.60 ns | 465.9 ns | 453.4 ns | 485.1 ns | 0.8951 | 0.0241 |      7 KB |

**Review by krwq — APPROVED** [review]
LGTM thank you! Will only kick off the outerloop tests to double check no regressions

**Comment by krwq** [comment]
I'll close/reopen PR since something broke with the CI checks

**Comment by jeffhandley** [comment]
I've marked this PR as "needs more info" for now. We'd like to better understand the risk/reward for the series of XML changes. See https://github.com/dotnet/runtime/pull/61773#issuecomment-973646209. Thanks!

**Comment by kronic** [comment]
I gave my answer [https://github.com/dotnet/runtime/pull/61773#issuecomment-973936099](Comment)

**Comment by krwq** [comment]
@jeffhandley this particular PR looks like a good optimization to me. In general as we've mentioned in the other PRs: please create an uber issue with motivation and share the approach you're taking so that we can also give you pointers how to achieve performance goals you have and also bucketize types of changes you're making so that any mistakes are easier to catch and fix

**Comment by krwq** [comment]
test failures are unrelated

**Pull request merged**
