### PR TITLE
Disable EtwManifest tests under jitstress

### LINKED ISSUE #82021: Test failure BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover
Run: [runtime-coreclr libraries-jitstress 20230211.2](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=168816)
 
 **Failed tests:**
 ```
net8.0-windows-Release-x64-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open

- BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover
 ```
 
 **Error message:**
 ```
 Half-way through waiting for remote process.
Memory load: 14

Image Name                     PID Services                                    
========================= ======== ============================================
svchost.exe                    764 BrokerInfrastructure, DcomLaunch, LSM,      
                                   PlugPlay, Power, SystemEventsBroker         
svchost.exe                    828 RpcEptMapper, RpcSs                         
svchost.exe                    964 Appinfo, CertPropSvc, DsmSvc, gpsvc,        
                                   iphlpsvc, lfsvc, ProfSvc, sacsvr, Schedule, 
                                   SENS, SessionEnv, ShellHWDetection, Themes, 
                                   UserManager, Winmgmt, WpnService, wuauserv  
svchost.exe                    972 TermService                                 
svchost.exe                    396 Dhcp, EventLog, lmhosts, NgcCtnrSvc,        
                                   TimeBrokerSvc, vmictimesync                 
svchost.exe                    476 NcbService, PcaSvc, TrkWks, UALSVC,         
                                   UmRdpService, vmickvpexchange,              
                                   vmicshutdown, WdiSystemHost                 
svchost.exe                   1032 BFE, CoreMessagingRegistrar, DPS, MpsSvc,   
                                   pla                                         
svchost.exe                   1112 EventSystem, FontCache, netprofm, nsi,      
                                   RemoteRegistry, W32Time, WinHttpAutoProxySv 
svchost.exe                   1164 vmicheartbeat                               
svchost.exe                   1348 CryptSvc, Dnscache, LanmanWorkstation,      
                                   NlaSvc, WinRM                               
svchost.exe                   1496 Wcmsvc                                      
svchost.exe                   1696 AppHostSvc                                  
svchost.exe                   2004 DiagTrack                                   
svchost.exe                   2144 LanmanServer                                
svchost.exe                   2156 W3SVC, WAS                                  
svchost.exe                   2200 StateRepository, tiledatamodelsvc           
svchost.exe                   3912 CDPUserSvc_4b448, OneSyncSvc_4b448          
svchost.exe                   3844 AppReadiness                                
Timed out at 2/12/2023 8:21:29 AM after 60000ms waiting for remote process.
Wrote mini dump to: C:\h\w\A9CB0917\w\C97C0AF9\uploads\5408.hvbc3zhv.c1b.dmp
	Process ID: 5408
	Handle: 1072
	Name: dotnet
	MainModule: C:\h\w\A9CB0917\p\dotnet.exe
	StartTime: 2/12/2023 8:20:29 AM
	TotalProcessorTime: 00:00:03.9531250
	Threads:
		Thread #1 (OS 0xBBC)   [MTA]
			[HelperMethodFrame] (System.Threading.Thread.SleepInternal)
			System.Threading.Thread.Sleep(Int32)
			BasicEventSourceTests.TestsManifestGeneration.<Test_EventSource_EtwManifestGenerationRollover>b__3_0()
			[HelperMethodFrame_PROTECTOBJ] (System.RuntimeMethodHandle.InvokeMethod)
			System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
			System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
			Microsoft.DotNet.RemoteExecutor.Program.Main(System.String[])
		Thread #2 (OS 0x16B4) [Finalizer] [Background] 
			[DebuggerU2MCatchHandlerFrame]

 ```
 
 **Stack trace:**
 ```
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 224
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
 ```

### PR DESCRIPTION
**Pull request by hoyosjs**
Fixes https://github.com/dotnet/runtime/issues/82021

### CODE REVIEW

**Comment by BruceForstall** [comment]
@hoyosjs I don't think this is going to fix the issue. In the failing case, none of the JitStress variables are set: the only thing set is `DOTNET_TieredCompilation=0` -- which should make everything faster!

**Comment by hoyosjs** [comment]
@BruceForstall do you know why jitstress is running tests that run on regular CI? But yeah, this is a slow operation regardless (at least from what I can see in the dump).

**Comment by BruceForstall** [comment]
AFAIK, `TieredCompilation=0` is never set as a configuration in the libraries test run, so we specifically add that as a configuration in the libraries-jitstress pipeline.

**Comment by hoyosjs** [comment]
Ah ok, so purely the libs. Thanks.

**Pull request closed without merging**
