### PR TITLE
Fix bad folding

### PR DESCRIPTION
**Pull request by SingleAccretion**
`GT_CNS_INT` of `TYP_INT` on 64 hosts has an implicit contract: the value returned by `IconValue()` must "fit" into 32 bit
signed integer, i. e. `static_cast<int>(IconValue()) == IconValue()`. `gtFoldExprConst` was failing to uphold this contract when the target was 32 bit and the host was 64 bit.

Fix this by always truncating before calling `SetIconValue()`.

I also added a test that reproduces the bad behavior, but to be effective it needs to be CG'ed on a 64 bit machine for a 32 bit target. I am not sure how to make sure that happens...

**This change is not zero-diff**. There were ~10 cases of either bad codegen or missed folding in the SPMI collections (all available for win-64 -> win-x86 cross-compilation), though none in the product code.

Found while looking at #53983.

### CODE REVIEW

**Comment by sandreenko** [comment]
Sorry for a late response, the change looks good, but I would like to repro the issue.

> I also added a test that reproduces the bad behavior, but to be effective it needs to be CG'ed on a 64 bit machine for a 32 bit target. I am not sure how to make sure that happens...

It should be pretty straightforward with this instruction: https://github.com/dotnet/runtime/blob/main/docs/workflow/debugging/coreclr/debugging-crossgen2.md

you run your test with `set RunCrossgen2=1` it will give you a command like `dotnet crossgen2.dll *.rsp`, now change in the rsp file target from x64 to x86 and run with --jitpath `path to clrjit_windows_x86_x64.dll` and it should produce a native image compiled on x64 host for x86 target. I should have time this week to check that it reproduces the issue that you described if you don't do this first.

**Comment by SingleAccretion** [comment]
@sandreenko Hmm, I suppose I was not really clear with the wording. What I meant is how to make sure the test is run the right way in CI, locally it can be reproduced easily with the usual AltJit setup.

That said, I have now checked that it does indeed reproduce with CG2 too.

**Review by sandreenko — APPROVED** [review]
LGTM

**Comment by SingleAccretion** [comment]
Will rerun the CI one more time...

**Comment by SingleAccretion** [comment]
> Will rerun the CI one more time...

Well, that's not so many failures, so, progress :).

1\) [`Build windows x64 Release SingleFile`](https://dev.azure.com/dnceng/public/_build/results?buildId=1232523&view=logs&jobId=3b4be47f-cc1b-5bf8-4e5e-8c012379f178&j=3b4be47f-cc1b-5bf8-4e5e-8c012379f178&t=815bd5f7-6733-5b57-4168-1099761dca5a) - mysterious build failures:
```
error NU1105: (NETCORE_ENGINEERING_TELEMETRY=Restore) Unable to find project information for 'D:\workspace\_work\1\s\src\libraries\System.Runtime.CompilerServices.Unsafe\src\System.Runtime.CompilerServices.Unsafe.ilproj'. If you are using Visual Studio, this may be because the project is unloaded or not part of the current solution so run a restore from the command-line. Otherwise, the project file may be invalid or missing targets required for restore.
```
2\) [`CoreCLR Pri0 Runtime Tests Run OSX arm64 checked`](https://dev.azure.com/dnceng/public/_build/results?buildId=1232523&view=logs&jobId=20fe7460-93d0-5227-a516-81881a5140fd&j=20fe7460-93d0-5227-a516-81881a5140fd&t=53619a80-c87d-56bb-fa5f-84ca37beaaf7):
  - [`log1`](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54722-merge-08dcf192083f4eda8d/JIT.jit64.hfa/console.0c4c94f1.log?sv=2019-07-07&se=2021-08-01T14%3A26%3A55Z&sr=c&sp=rl&sig=FWIhr8DwI%2FGfES7M4p5v%2BFSq6HhaAr2dOnm5omtit1M%3D), [`log2`](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54722-merge-5c47d4117dcb4d9288/JIT.Methodical.eE/console.3046d00d.log?sv=2019-07-07&se=2021-08-01T14%3A26%3A55Z&sr=c&sp=rl&sig=3n%2Fd4CUHKAVYYGVrs1LNm1L36A5%2FCgwqac7fCME6mzo%3D) - tests succeeded, but the work item failed. Unclear why.
  - [`log3`](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54722-merge-08dcf192083f4eda8d/profiler.unittest/console.0deb34a3.log?sv=2019-07-07&se=2021-08-01T14%3A26%3A55Z&sr=c&sp=rl&sig=FWIhr8DwI%2FGfES7M4p5v%2BFSq6HhaAr2dOnm5omtit1M%3D) - truncated log, likewise unclear what's up.

3\) [`Installer Build and Test coreclr windows_x86 Debug`](https://dev.azure.com/dnceng/public/_build/results?buildId=1232523&view=logs&jobId=20fe7460-93d0-5227-a516-81881a5140fd&j=f827f174-7a88-54e3-54c2-8dcd28f39edd&t=5bc77b52-54d3-5da9-c79e-6dacacea45ab) - download failure, chalking up to #55449.
```
D:\workspace\_work\1\s\.dotnet\sdk\6.0.100-preview.4.21255.9\NuGet.targets(131,5): error : Failed to retrieve information about 'System.Spatial' from remote source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/flat2/system.spatial/index.json'. [D:\workspace\_work\1\s\src\installer\tests\Assets\TestProjects\ResourceLookup\ResourceLookup.csproj]
```

**Comment by sandreenko** [comment]
I saw these failures in other PRs, the infra is in a bad state, azure is trying to patch it up, but for now we have to merge on red.

**Pull request merged**
