### PR TITLE
fix NRE in XNodeNavigator.MoveToNext(XPathNodeType)

### LINKED ISSUE #31710: NullReferenceException on XNodeNavigator.MoveToNext(XPathNodeType)
```cs
// Create current element and it's parent
var current = new XElement("foo");
new XElement("parent", current);

// Try to find next sibling via xpath
var nav = current.CreateNavigator();
nav.MoveToNext(XPathNodeType.Element);
```

**expected**: MoveToNext returned false
**got**: NullReferenceException, probably in this line: https://github.com/dotnet/runtime/blob/9524bb599ea231fee1f9e233cb1a71850289ea57/src/libraries/System.Private.Xml.Linq/src/System/Xml/XPath/XNodeNavigator.cs#L552

### PR DESCRIPTION
**Pull request by mayorovp**
fixes #31710

### CODE REVIEW

**Review by stephentoub — COMMENTED** [review]
Thanks. Is there a test you can add that would have failed before and passes now?

**Comment by buyaa-n** [comment]
@mayorovp thank you for your contribution, seems you are not signed CLA, please sign.
@stephentoub test added, please review

**Review by danmoseley — APPROVED** [review]

**Comment by danmosemsft** [comment]
Issues exist for unrelated failures

**Comment by danmosemsft** [comment]
Thanks @mayorovp for the contribution.

**Pull request merged**
