### PR TITLE
Allow building libs tests for all configurations

### PR DESCRIPTION
**Pull request by ViktorHofer**
Building libraries tests and passing in the -allconfigurations switch
results in the libraries packages being built and tested. Conditioning
the packages build/test on the /p:TestPackages switch.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@akoeplinger a few wasm test builds will probably fail. Do you want to fix them as part of this PR or should I? Should be trivial to unblock.

**Comment by safern** [comment]
I don’t understand why do we need this? When did we see it break? The tests should be built for all rids once we enable test runs for iOS and Android.

**Comment by ViktorHofer** [comment]
> I don’t understand why do we need this?

It's for the local developer workflow. I want to build ALL libraries tests. There is no way to do that today. Also I don't think we have protection for cross-building test projects today.

**Comment by safern** [comment]
A ok, makes sense. Will take a look.

**Review by safern — APPROVED** [review]

**Comment by ViktorHofer** [comment]
The LibrariesTests_AllConfigurations leg is expected to fail but I don't know why the normal allConfiguration now fails... Don't understand the error in the log...

**Comment by safern** [comment]
It is because `TestPackages` is a property to tell which packages to build/test locally so that you don't have to run all test packages to get a minimal repro:

https://github.com/dotnet/runtime/blob/cf66f084ca8b563c42cd814e8ce8b03519af51bd/src/libraries/pkg/test/testPackages.proj#L5

You will need to rename that to something like `PackagesToTest`

**Comment by safern** [comment]
Note that that is not the only place used so I suggest grepping for all usages of it before this change:
https://github.com/dotnet/runtime/search?q=TestPackages&unscoped_q=TestPackages

**Comment by ViktorHofer** [comment]
I removed the global-build-job protection for now to unblock the PR and will add that in a subsequent one after #35606 is in.

**Pull request merged**
