### PR TITLE
Update package baseline for 5.0.1

### PR DESCRIPTION
**Pull request by ericstj**

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Feel free to do a quick merge after the allconfigurations leg finished.

**Review by Anipik — APPROVED** [review]

**Review by joperezr — APPROVED** [review]

**Comment by safern** [comment]
Last time this happened (with S.D.Common) @ericstj started a conversation about making this less breaking:
> One thought here for how we make this less breaking: what if we only turn this on for release branches? Thoughts @joperezr / @Anipik?

I replied
> I think that would work as whenever we branch for a preview or a release we turn it off and it will fail to remind us to update this. However, daily built packages could be broken.

https://github.com/dotnet/runtime/pull/44481#issuecomment-724943820

Thoughts? I think we should do it for to be less breaking.

**Review by safern — APPROVED** [review]

**Comment by ViktorHofer** [comment]
> Thoughts? I think we should do it for to be less breaking.

We will stop harvesting in master sooner than later. I would not invest in any other solution meanwhile.

**Comment by ericstj** [comment]
All configurations succeeded: https://dev.azure.com/dnceng/public/_build/results?buildId=912731&view=logs&j=81a0f8c2-d4db-561f-9b8e-3f045280d7fe

**Comment by xtqqczze** [comment]
In #45779, there are CI failures:

```
src\libraries\pkg\test\testPackages.proj(214,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Validation Failed: System.Security.Cryptography.Pkcs is harvesting assets from package version 5.0.0 which is not the latest for that package release. Latest package version from that release is 5.0.1. In order to fix this, run `dotnet msbuild System.Security.Cryptography.Pkcs.pkgproj /t:UpdateHarvestVersionOnPackageIndex /p:UpdateStablePackageInfo=true`
```

https://github.com/dotnet/runtime/pull/45779/checks?check_run_id=1519390883

**Comment by safern** [comment]
> In #45779, there are CI failures, possibly resulting from this PR:

@xtqqczze thanks for reaching out. This PR is fixing those failures, it is possible that your build ran before this fix was merged. If you run your pipeline again (by opening/closing, or pushing a new commit) you shouldn't see this failure anymore.

**Pull request merged**
