### PR TITLE
add RID for Ubuntu 23.04

### PR DESCRIPTION
**Pull request by wfurt**
it seems like  #82204 fixed the generation. Alpine diff is big but it seems just some changes in ordering.

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Review by carlossanlop — COMMENTED** [review]
Is this failure related?
```
src/native/corehost/corehost.proj(93,5): error MSB3073: (NETCORE_ENGINEERING_TELEMETRY=Build)
The command ""/Users/runner/work/1/s/src/native/corehost/build.sh" Debug x64 -apphostver "8.0.0-ci"
 -hostver "8.0.0-ci" -fxrver "8.0.0-ci" -policyver "8.0.0-ci" -commithash "4af962d6cc39903cf2d361b26abaf2d4bf5b9d78"
-os osx -cmakeargs "-DVERSION_FILE_PATH=/Users/runner/work/1/s/artifacts/obj/_version.c" -runtimeflavor mono
-outputrid osx-x64" exited with code 1.
```

**Comment by wfurt** [comment]
It does not seems to @carlossanlop 
```
Checking prerequisites...
  Please install pkg-config before running this script, see https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/macos-requirements.md
```

looks like infrastructure issue to me.  I can hold on until the tests are clean. There is no rush for `main` AFAIK.

**Comment by wfurt** [comment]
failure tracked as https://github.com/dotnet/runtime/issues/82240

**Comment by carlossanlop** [comment]
@wfurt that one's different, it got automatically detected by KnownBuildErrors before my comment.

The `pkg-config` error message is pre-existing and unrelated to this PR. It affects `tvossimulator-x64 Debug AllSubsets_Mono` - https://dev.azure.com/dnceng-public/public/_build/results?buildId=175539&view=logs&j=236574dc-1268-595c-f18d-7a54631907f7&t=cb60e9b1-fa4e-523e-f53e-42c53fc8c842&l=2204

The one I'm talking about is a corehost command failure, it affects the `Prepare TestHost` step, and showed up in these jobs:

- `Libraries Test Run release mono osx x64 Debug` - https://dev.azure.com/dnceng-public/public/_build/results?buildId=175539&view=logs&j=ab5d32de-6d19-5068-e03b-b69cf4db6cd5&t=cd017e3f-8d98-5649-5fab-ee4dac9a32a3
- `Libraries Test Run release coreclr osx x64 Debug` - https://dev.azure.com/dnceng-public/public/_build/results?buildId=175539&view=logs&j=5da4f169-faec-5863-fdf3-ac008545b5e6&t=5c18c803-11ff-5276-e279-5235d97f8fde
- `Libraries Test Run checked coreclr osx x64 Debug` - https://dev.azure.com/dnceng-public/public/_build/results?buildId=175539&view=logs&j=69b60b53-a417-56e9-d4e0-3a40344d5e67&t=95c30fd4-1a3d-50e2-db4e-324f09502d92

**Review by carlossanlop — APPROVED** [review]
Approved.

I marked my previous comment as resolved. My bad. I didn't see the info message above the failed core-host error.

**Review by tmds — APPROVED** [review]

**Comment by wfurt** [comment]
While I agree @tmds I wanted this for consistency with maintenance branches.

**Pull request merged**
