### PR TITLE
Update System.Threading.Channels dependency

### PR DESCRIPTION
**Pull request by WeihanLi**
Remove `System.Threading.Tasks.Extensions` dependency since it's already a dependency of `Microsoft.Bcl.AsyncInterfaces`

relates to https://github.com/dotnet/runtime/pull/94417

### CODE REVIEW

**Comment by stephentoub** [comment]
> Remove `System.Threading.Tasks.Extensions` dependency since it's already a dependency of `Microsoft.Bcl.AsyncInterfaces`

Why is this beneficial?

**Comment by WeihanLi** [comment]
> > Remove `System.Threading.Tasks.Extensions` dependency since it's already a dependency of `Microsoft.Bcl.AsyncInterfaces`
> 
> Why is this beneficial?


image
Currently, it would have two dependencies from the package dependencies(for netstandard2.0 and net462), when removed, it should be only one dependency for `Microsoft.Bcl.AsyncInterfaces`

From my limited knowledge, think it would behave the same way whether the reference existed or not, so trying to remove the reference, make the dependency cleaner and we could keep the `Microsoft.Bcl.AsyncInterfaces` updated without considering the upgrade of `System.Threading.Tasks.Extensions`.

While if there are more benefits to having a reference for `System.Threading.Tasks.Extensions` feel free to close

**Comment by stephentoub** [comment]
Thanks.

@ericstj, is this desirable?

**Comment by ericstj** [comment]
No it's not desirable.  There's nothing wrong with stating your dependencies.  Being explicit is actually better since it insulates you from a breaking change if a transitive dependency were removed.

**Pull request closed without merging**
