### PR TITLE
JIT: Add simple late layout pass

### PR DESCRIPTION
**Pull request by amanasifkhalid**
LSRA may introduce new blocks after we've run layout (see #107419). Ideally, we'd do `optOptimizeLayout` and `fgDetermineFirstColdBlock` after LSRA so that we only need to reorder once, but many of the transformations in `fgUpdateFlowGraph` aren't designed to be run after lowering, and will hit asserts. Once some of the later flowgraph optimizations like `optSwitchRecognition` are decoupled from lexical block order, we can look into only running `fgUpdateFlowGraph` before lowering/LSRA, and then run only reordering afterwards. For now, I think we can get away with just rerunning RPO layout; hopefully this is relatively cheap.

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
cc @dotnet/jit-contrib, @AndyAyersMS PTAL. [Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=800320&view=ms.vss-build-web.run-extensions-tab) show the usual amount of churn with layout changes, though seems to be a net PerfScore improvement. TP cost isn't too bad.

**Comment by amanasifkhalid** [comment]
I added a check to see that the RPO layout is enabled since we're still running the old layout in CI, and it probably doesn't make sense to mix them.

**Comment by AndyAyersMS** [comment]
I happen to know the `LDecomp` benchmark method suffered pretty badly from poor block placement, so it is good to see it getting some benefit here (https://github.com/dotnet/runtime/issues/9833#issuecomment-372785483)
```
        -177 (-2.68 % of base) : 55033.dasm - LUDecomp:Run():double:this (Tier1)
```
Any idea what's up with windows x86? Given how few allocatable registers there on x86 are it is a good stress test for LSRA inserted blocks.

**Comment by amanasifkhalid** [comment]
> Any idea what's up with windows x86?

I took a look at the top regressions from `benchmarks.run_pgo` (that and `coreclr_tests` were the only collections with net size regressions), and some of the size increases are from the JIT now moving cold blocks out-of-line. For example, from `Microsoft.CodeAnalysis.CSharp.BoundBlock:Update`, the layout goes from this:
```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    IBC [IL range]   [jump]                            [EH region]        [flags]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1    6055 [000..00E)-> BB20(0),BB02(1)         ( cond )                     i LIR IBC label
BB02 [0001]  1       BB01                  1    6055 [00E..01C)-> BB21(0),BB03(1)         ( cond )                     i LIR IBC
BB03 [0002]  1       BB02                  1    6055 [01C..025)-> BB22(0),BB04(1)         ( cond )                     i LIR IBC
BB04 [0003]  1       BB03                  1    6055 [025..02F)-> BB23(0),BB05(1)         ( cond )                     i LIR IBC
BB05 [0004]  1       BB04                  1    6055 [02F..03E)-> BB06(0.6),BB07(0.4)     ( cond )                     i LIR IBC
BB23 [0052]  1       BB04                  0       0 [???..???)-> BB07(1)                 (always)                     LIR IBC rare internal label
BB22 [0051]  1       BB03                  0       0 [???..???)-> BB07(1)                 (always)                     LIR IBC rare internal label
BB21 [0050]  1       BB02                  0       0 [???..???)-> BB07(1)                 (always)                     LIR IBC rare internal label
BB20 [0049]  1       BB01                  0       0 [???..???)-> BB07(1)                 (always)                     LIR IBC rare internal label
BB06 [0006]  1       BB05                  0.60 3633 [05E..060)                           (return)                     i LIR IBC label
BB07 [0005]  5       BB05,BB20,BB21,BB22,BB23   0.40 2422 [000..056)-> BB16(0.00862),BB08(0.991)   ( cond )                     i LIR IBC label hascall newobj
BB08 [0020]  1       BB07                  0.40 2401 [000..000)-> BB10(0),BB09(1)         ( cond )                     i LIR IBC internal
BB09 [0026]  1       BB08                  0.40 2401 [000..000)-> BB16(0),BB10(1)         ( cond )                     i LIR IBC internal
BB10 [0021]  2       BB08,BB09             0.40 2401 [000..000)-> BB11(1)                 (always)                     i LIR IBC internal label hascall gcsafe
BB11 [0023]  2       BB10,BB16             0.40 2422 [000..000)-> BB18(0),BB12(1)         ( cond )                     i LIR IBC internal label
BB12 [0034]  2       BB11,BB18             0.40 2422 [000..057)-> BB14(0),BB13(1)         ( cond )                     i LIR IBC label newobj nullcheck
BB13 [0041]  1       BB12                  0.40 2422 [056..057)-> BB14(1)                 (always)                     i LIR IBC
BB14 [0042]  2       BB12,BB13             0.40 2422 [056..05D)-> BB19(0),BB15(1)         ( cond )                     i LIR IBC label newobj nullcheck
BB15 [0047]  2       BB14,BB19             0.40 2422 [056..05E)                           (return)                     i LIR IBC label newobj nullcheck
BB16 [0022]  2       BB07,BB09             0.00   21 [000..000)-> BB11(1)                 (always)                     i LIR IBC internal label
BB18 [0033]  1       BB11                  0       0 [000..000)-> BB12(1)                 (always)                     i LIR IBC rare internal label
BB19 [0046]  1       BB14                  0       0 [056..057)-> BB15(1)                 (always)                     i LIR IBC rare label
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

To this:
```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight    IBC [IL range]   [jump]                            [EH region]        [flags]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1    6055 [000..00E)-> BB20(0),BB02(1)         ( cond )                     i LIR IBC label
BB02 [0001]  1       BB01                  1    6055 [00E..01C)-> BB21(0),BB03(1)         ( cond )                     i LIR IBC
BB03 [0002]  1       BB02                  1    6055 [01C..025)-> BB22(0),BB04(1)         ( cond )                     i LIR IBC
BB04 [0003]  1       BB03                  1    6055 [025..02F)-> BB23(0),BB05(1)         ( cond )                     i LIR IBC
BB05 [0004]  1       BB04                  1    6055 [02F..03E)-> BB07(0.4),BB06(0.6)     ( cond )                     i LIR IBC
BB06 [0006]  1       BB05                  0.60 3633 [05E..060)                           (return)                     i LIR IBC
BB07 [0005]  5       BB05,BB20,BB21,BB22,BB23   0.40 2422 [000..056)-> BB16(0.00862),BB08(0.991)   ( cond )                     i LIR IBC label hascall newobj
BB08 [0020]  1       BB07                  0.40 2401 [000..000)-> BB10(0),BB09(1)         ( cond )                     i LIR IBC internal
BB09 [0026]  1       BB08                  0.40 2401 [000..000)-> BB16(0),BB10(1)         ( cond )                     i LIR IBC internal
BB10 [0021]  2       BB08,BB09             0.40 2401 [000..000)-> BB11(1)                 (always)                     i LIR IBC internal label hascall gcsafe
BB11 [0023]  2       BB10,BB16             0.40 2422 [000..000)-> BB18(0),BB12(1)         ( cond )                     i LIR IBC internal label
BB12 [0034]  2       BB11,BB18             0.40 2422 [000..057)-> BB14(0),BB13(1)         ( cond )                     i LIR IBC label newobj nullcheck
BB13 [0041]  1       BB12                  0.40 2422 [056..057)-> BB14(1)                 (always)                     i LIR IBC
BB14 [0042]  2       BB12,BB13             0.40 2422 [056..05D)-> BB19(0),BB15(1)         ( cond )                     i LIR IBC label newobj nullcheck
BB15 [0047]  2       BB14,BB19             0.40 2422 [056..05E)                           (return)                     i LIR IBC label newobj nullcheck
BB16 [0022]  2       BB07,BB09             0.00   21 [000..000)-> BB11(1)                 (always)                     i LIR IBC internal label
BB23 [0052]  1       BB04                  0       0 [???..???)-> BB07(1)                 (always)                     LIR IBC rare internal label
BB22 [0051]  1       BB03                  0       0 [???..???)-> BB07(1)                 (always)                     LIR IBC rare internal label
BB21 [0050]  1       BB02                  0       0 [???..???)-> BB07(1)                 (always)                     LIR IBC rare internal label
BB20 [0049]  1       BB01                  0       0 [???..???)-> BB07(1)                 (always)                     LIR IBC rare internal label
BB18 [0033]  1       BB11                  0       0 [000..000)-> BB12(1)                 (always)                     i LIR IBC rare internal label
BB19 [0046]  1       BB14                  0       0 [056..057)-> BB15(1)                 (always)                     i LIR IBC rare label
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

In other cases, the size increases come from the JIT moving new blocks in-line, breaking up existing fallthrough. For example, the layout in `Benchstone.BenchI.AddArray2:BenchInner2` went from this:
```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight     IBC [IL range]   [jump]                            [EH region]        [flags]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1      100 [000..007)-> BB08(0.1),BB02(0.9)     ( cond )                     i LIR IBC
BB02 [0013]  2       BB01,BB07             9.00   900 [007..00E)-> BB11(0.1),BB03(0.9)     ( cond )                     i LIR IBC loophead bwd
BB03 [0014]  2       BB02,BB14            72.90  7290 [00E..013)-> BB12(0.01),BB04(0.995)  ( cond )                     i LIR IBC loophead bwd
BB04 [0023]  1       BB03                 72.90  7290 [???..???)-> BB09(0.00501),BB05(0.995)   ( cond )                     LIR IBC internal idxlen has-align
BB05 [0019]  2       BB04,BB13           721.71 72171 [013..037)-> BB13(0.9),BB06(0.1)     ( cond )                     i LIR IBC loophead idxlen bwd align
BB06 [0026]  2       BB05,BB09            81.00  8100 [037..042)-> BB14(0.9),BB07(0.1)     ( cond )                     i LIR IBC bwd
BB07 [0017]  2       BB06,BB11             9.00   900 [042..04A)-> BB02(0.9),BB08(0.1)     ( cond )                     i LIR IBC bwd
BB08 [0018]  2       BB01,BB07             1      100 [04A..04B)                           (return)                     i LIR IBC
BB14 [0031]  1       BB06                 72.90  7290 [???..???)-> BB03(1)                 (always)                     LIR IBC internal bwd
BB13 [0030]  1       BB05                649.54 64954 [???..???)-> BB05(1)                 (always)                     LIR IBC internal bwd
BB12 [0029]  1       BB03                  0.73    73 [???..???)-> BB09(1)                 (always)                     LIR IBC internal bwd has-align
BB11 [0028]  1       BB02                  0.90    90 [???..???)-> BB07(1)                 (always)                     LIR IBC internal bwd
BB09 [0020]  3       BB04,BB12,BB15        7.29   729 [013..037)-> BB06(0.1),BB15(0.9)     ( cond )                     i LIR IBC loophead idxlen bwd align
BB15 [0032]  1       BB09                  6.56   656 [???..???)-> BB09(1)                 (always)                     LIR IBC internal bwd
BB10 [0027]  0                             0          [???..???)                           (throw )                     i LIR rare keep internal
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

To this:
```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BBnum BBid ref try hnd preds           weight     IBC [IL range]   [jump]                            [EH region]        [flags]
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
BB01 [0000]  1                             1      100 [000..007)-> BB08(0.1),BB02(0.9)     ( cond )                     i LIR IBC
BB02 [0013]  2       BB01,BB07             9.00   900 [007..00E)-> BB11(0.1),BB03(0.9)     ( cond )                     i LIR IBC loophead bwd
BB14 [0031]  1       BB06                 72.90  7290 [???..???)-> BB03(1)                 (always)                     LIR IBC internal bwd
BB03 [0014]  2       BB02,BB14            72.90  7290 [00E..013)-> BB12(0.01),BB04(0.995)  ( cond )                     i LIR IBC loophead bwd
BB04 [0023]  1       BB03                 72.90  7290 [???..???)-> BB09(0.00501),BB05(0.995)   ( cond )                     LIR IBC internal idxlen has-align
BB13 [0030]  1       BB05                649.54 64954 [???..???)-> BB05(1)                 (always)                     LIR IBC internal bwd align
BB05 [0019]  2       BB04,BB13           721.71 72171 [013..037)-> BB13(0.9),BB06(0.1)     ( cond )                     i LIR IBC loophead idxlen bwd
BB12 [0029]  1       BB03                  0.73    73 [???..???)-> BB09(1)                 (always)                     LIR IBC internal bwd has-align
BB15 [0032]  1       BB09                  6.56   656 [???..???)-> BB09(1)                 (always)                     LIR IBC internal bwd align
BB09 [0020]  3       BB04,BB12,BB15        7.29   729 [013..037)-> BB15(0.9),BB06(0.1)     ( cond )                     i LIR IBC loophead idxlen bwd
BB06 [0026]  2       BB05,BB09            81.00  8100 [037..042)-> BB14(0.9),BB07(0.1)     ( cond )                     i LIR IBC bwd
BB11 [0028]  1       BB02                  0.90    90 [???..???)-> BB07(1)                 (always)                     LIR IBC internal bwd
BB07 [0017]  2       BB06,BB11             9.00   900 [042..04A)-> BB02(0.9),BB08(0.1)     ( cond )                     i LIR IBC bwd
BB08 [0018]  2       BB01,BB07             1      100 [04A..04B)                           (return)                     i LIR IBC
BB10 [0027]  0                             0          [???..???)                           (throw )                     i LIR rare keep internal
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

In this example, we seem to be interleaving more paths, but the loop bodies are more compact (`BB05 -> BB13` looks particularly rough in the old layout), so this seems to be worth it.

> Given how few allocatable registers there on x86 are it is a good stress test for LSRA inserted blocks.

I think you're right. I'm seeing this same pattern of block movement on other platforms, but we aren't introducing as many new blocks as we are on x86, hence the larger diffs in both directions.

**Review by AndyAyersMS — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Improvements:
* https://github.com/dotnet/perf-autofiling-issues/issues/41302

**Comment by amanasifkhalid** [comment]
@AndyAyersMS @LoopedBard3 thanks for organizing the perf diffs. If LSRA introduces new blocks, then re-running layout should be the right decision, assuming the profile is maintained correctly. `Compiler::fgSplitEdge` sometimes gets the new block's weight wrong, and it's pretty easy to fix this now that we have likelihood-based edge weights; I opened #107941 for this.

I suspect some of these regressions may be from the JCC erratum mitigation now triggering due to layout churn. I'm curious to see if the arm64 diffs reflect this by being more conservative in both directions.

**Pull request merged**
