### PR TITLE
Force build failure if AOT compiler is missing, and avoid bad path

### PR DESCRIPTION
**Pull request by directhex**
An error in paths was introduced last week. Work around that, and make it a fatal build failure if the AOT compiler is missing in future to catch this faster

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by lewing** [comment]
should fix https://github.com/dotnet/runtime/pull/50198

**Comment by steveisok** [comment]
The failures were fixed by https://github.com/dotnet/runtime/pull/52762

**Comment by lewing** [comment]
@marcpopMSFT this is a hard requirement for preview5

**Comment by marcpopMSFT** [comment]
@lewing , I don't think the runtime repo has branched for preview 5 yet so this should be included already.  Any reason to be concerned about that?

**Comment by lewing** [comment]
@marcpopMSFT nope just brief confusion on my part on friday.

**Pull request merged**
