### PR TITLE
[wasm] Remove unused bindings

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Review by thaystg — APPROVED** [review]

**Comment by lewing** [comment]
These are js changes that can't have impacted the failing CI lanes

**Comment by midnight-dev** [comment]
I don't have any stake in this, just browsing a neat repository, so don't let me break your stride. But are there any tests in the pipeline that assume `find_class` & `find_method` exist or rely on the environment settings?

The GitHub android app does not have a convenient way to view CI results. Otherwise, I'd have taken a peak myself.

**Comment by lewing** [comment]
@midnight-dev the lanes that failed don't use the wasm js in any way.  Additionally the methods that were removed are exposed and used from the runtime bindings where needed and don't need to be bound here.

**Comment by midnight-dev** [comment]
@lewing Roger. That satisfies my curiosity. Thanks for taking the time to respond. 👌

**Comment by danmosemsft** [comment]
@midnight-dev we have up for grabs issues if you're interested!

**Pull request merged**
