### PR TITLE
[mono][aot] Emit only virtual methods of instances when a class insta…

### PR DESCRIPTION
**Pull request by vargaz**
…nce is added.

### CODE REVIEW

**Comment by vargaz** [comment]
This saves a lot of space, but it might cause regressions since less method instances are emitted.

**Comment by lewing** [comment]
runtime (Build Linux x64 Release AllSubsets_Mono_LLVMFullAot_RuntimeTests llvmfullaot) failed with 

```Ran out of trampolines of type 3 in '/datadisks/disk1/work/B6DC09BF/p/System.Private.CoreLib.dll' (limit 4400)```

which I don't think is unique to this?

**Comment by lambdageek** [comment]
Won't this leave out a ton of methods?  Why do we only want virtual ones?

For example anything that uses `typeof(GenericParam)` will be left out:

```csharp
class GenericContainer<T> {
  public int SomeMethod() {
    if (typeof(T) == typeof(string))
      return 1;
    return 2;
   }
}
```

**Comment by vargaz** [comment]
This is just an experiment. Right now, if we encounter a generic instance, we will add all of its methods which leads to a ton of code generated which will never be called.

**Comment by vargaz** [comment]
This saves about 100k (2%) on a wasm hello world.

**Pull request closed without merging**
