### PR TITLE
Add more precise tracking of static bases

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Under some circumstances, the compiler needs to generate information about the bases where static fields of a type are placed.

The existing logic was simple: if a static base was accessed, generate the owning type. If owning type was generated, generate all of it's static bases. At object emission, go over all generated types and preserve information about their bases.

We couldn't do better at the time this was implemented.

The information about static bases is needed in two cases:

1. A static field on the type is reflectable. We now know when that happens and it doesn't happen very often.
2. The generic type whose static base we generated has a template and we could build the type at runtime. This also doesn't happen very often anymore.

This PR teaches the compiler to only emit the information for these two cases. It prevents generating unnecessary EETypes, static bases, and .cctors.

Also adding a test case for scenario 2 above since we didn't have coverage for the scenario. Scenario 1 is covered.

Saves 0.2% on a hello world. Not much, but at least it's easier to reason about why this is generated.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
So the Build windows x64 Release NativeAOT_Checked_Libs has a failure and the stack is:

```
[0x0]   KERNELBASE!RaiseFailFastException + 0x152   
[0x1]   System_Collections_Tests!S_P_CoreLib_Interop_Kernel32__RaiseFailFastException + 0xa4   
[0x2]   System_Collections_Tests!S_P_CoreLib_System_RuntimeExceptionHelpers__FailFast_1 + 0x142   
[0x3]   System_Collections_Tests!S_P_CoreLib_System_RuntimeExceptionHelpers__GetRuntimeException + 0x2be   
[0x4]   System_Collections_Tests!S_P_CoreLib_System_Runtime_EH__GetClasslibException + 0x2d   
[0x5]   System_Collections_Tests!S_P_CoreLib_System_Runtime_EH__RhThrowHwEx + 0xa2   
[0x6]   System_Collections_Tests!RhpThrowHwEx + 0xeb   
[0x7]   System_Collections_Tests!S_P_CoreLib_System_RuntimeExceptionHelpers__FailFast_1 + 0x116   
[0x8]   System_Collections_Tests!S_P_CoreLib_System_RuntimeExceptionHelpers__RuntimeFailFast + 0xfe   
[0x9]   System_Collections_Tests!S_P_CoreLib_System_Runtime_EH__UnhandledExceptionFailFastViaClasslib + 0x8c   
[0xa]   System_Collections_Tests!S_P_CoreLib_System_Runtime_EH__DispatchEx + 0x193   
[0xb]   System_Collections_Tests!S_P_CoreLib_System_Runtime_EH__RhThrowEx + 0x51   
[0xc]   System_Collections_Tests!RhpThrowEx + 0x117   
[0xd]   System_Collections_Tests!S_P_CoreLib_Internal_Runtime_CompilerHelpers_ThrowHelpers__ThrowIndexOutOfRangeException + 0x24   
[0xe]   System_Collections_Tests!S_P_CoreLib_Internal_Runtime_ThreadStatics__GetThreadStaticBaseForTypeSlow + 0x76   
[0xf]   System_Collections_Tests!S_P_CoreLib_System_Threading_Thread__OnThreadExit + 0x13   
[0x10]   System_Collections_Tests!ThreadStore::DetachCurrentThread + 0x60   
[0x11]   System_Collections_Tests!RuntimeThreadShutdown + 0x7a   
[0x12]   ntdll!RtlProcessFlsData + 0xf4   
[0x13]   ntdll!LdrShutdownThread + 0x43   
[0x14]   ntdll!RtlExitUserThread + 0x3e   
```

I got the binary from the CI and I couldn't quickly repro it. I am touching static base related stuff so this could be my fault, but this looks like a pretty impossible failure mode. The first thing `GetThreadStaticBaseForTypeSlow` is doing is that it ensures the array is big enough. I don't see how we could end up being out of range unless we're eventually trying to store to a wrong location. @vsadov could there be some GC issue on thread shutdown?

You can quickly get the dump with `runfo get-helix-payload -j d632ca13-8645-4da3-a011-ef79e92f8478 -w System.Collections.Tests -o c:\helixout` (also `dotnet tool install --global runfo` if you don't have runfo yet).

**Comment by MichalStrehovsky** [comment]
Oh, this is actually a double fault because we're AVing while trying to fail fast because the exception object is also wrong.

**Comment by VSadov** [comment]
This is clearly happening on a thread detach (since we see `DetachCurrentThread` on the stack). 

However, since we are trying to detach the thread must be attached and its threadstatics must be initialized. It could be a result of recent changes in threading, but it could be exposing existing race.

One guess would be - previously, once we see that process is shutting down, we would not detach some threads, but now we would not detach only the special thread that performs the shutdown. Other threads will be detached. 
If this is a result of the that change, then the same scenario was possible before (as knowing if a process is shutting down would have a race), just more easy to get into this now.

I will take a look at the dump.

**Comment by VSadov** [comment]
I've got the dump. 
The most suspicious thing is that a blocking GC is in progress and we are crashing in `private static void OnThreadExit()`.  We should not be able to run managed code concurrently with blocking GC. 

`OnThreadExit` is called from native code, but as any other reverse pinvoke, it would just block and wait for GC done. Or if it manages to get into managed code, GC would need to suspend it. 

Not sure yet how we could get both going. Maybe GC started when `OnThreadExit` already crashed ...

**Comment by VSadov** [comment]
> Maybe GC started when OnThreadExit already crashed ...

This seems the most possible explanation. At the point in the dump the crashing thread is running preemptively in the native code  (in `KERNELBASE.dll!RaiseFailFastException`), so it is possible that GC started after that and the dump picked up the state where GC is in progress. 

The question remains - what could cause the crash.

**Comment by VSadov** [comment]
The thread that is crashing is actually a background GC thread. Most likely it was out of work for too long and timed out, so started exiting. 
Background GC threads do not normally run managed code, but for they are suspendable/attached threads, so the thread gets detached and runs `OnThreadExit()`, which is a managed pre-mortem callback.

It would be an easy fix - check if the thread is a GC thread and not run callbacks. Seems like a good idea regardless, since background GC threads are not user threads. 

I am still worried that it has crashed. Even though we do not want this thread to run `OnThreadExit()`, I wonder why I could not. (also - why is this crash not happening more often?, can the crash happen with user threads?)

**Comment by VSadov** [comment]
BTW, It seems unlikely that the crash was caused by this PR. So I'd not consider this blocking.

**Pull request merged**
