### PR TITLE
Update lead specification for AppModel items

### PR DESCRIPTION
**Pull request by agocke**
Replace @jeffschwMSFT with @agocke for lead on AssemblyLoader and SingleFile

@jeffschwMSFT does this look right? Am I missing a path? I assume linker is separate and will have to be tracked separately.

@danmosemsft would these changes be sufficient to give me notifications on new issues in these areas? I hoped to get access to issue notifications so I can do triage.

Thanks!

### CODE REVIEW

**Review by jeffschwMSFT — COMMENTED** [review]
Can you also take ownership of the following two areas?
area-Host    
area-HostModel

**Comment by agocke** [comment]
Done

**Review by danmoseley — APPROVED** [review]

**Comment by agocke** [comment]
@jeffschwMSFT Anything else?

**Review by jeffschwMSFT — APPROVED** [review]
lgtm

**Comment by agocke** [comment]
@danmosemsft Forgot to mention -- could I also get subscribed to the issues for these areas?

**Comment by danmosemsft** [comment]
@agocke done

**Pull request merged**
