### PR TITLE
Stop retyping RHSes to byrefs on type mismatch

### PR DESCRIPTION
**Pull request by SingleAccretion**
This is an interesting piece of code. Using it, it is possible to give `TYP_BYREF` to any node that would ordinarily have `TYP_I_IMPL`. In particular, I encountered it in my `GT_CAST` work: we have tests in the SPMI collections with `CAST(byref <- long <- int)` in them. Ordinarily such a tree would [assert](https://github.com/dotnet/runtime/blob/a579575853cea23aa1b6b6b8d3ef978aa9321e16/src/coreclr/jit/valuenum.cpp#L9392) in VN, but in that case optimizations were off and so everything went smoothly.

It is possible to have `TYP_BYREF` `UMOD`/`MUL_OVF_UN` and similar with this code. Naturally, the compiler does not like it and fails with asserts in multiple places.

So, just delete the retyping. The cited assert either no longer exists (though I had a look at the legacy codegen and could not
find it there...) or got reworked at some point.

There are GC Info diffs with this change. They consist of cases when a constant zero node was retyped to `TYP_BYREF` and thus its register's liveness was recorded:
```diff
-       xor      rcx, rcx
-       ; byrRegs +[rcx]
+       xor      ecx, ecx
        mov      bword ptr [rbp+78H], rcx
        mov      rcx, 0xD1FFAB1E
-       ; byrRegs -[rcx]
```
There is also a case where this happens for a `long` field.
```diff
             ldr     x1, [x2,#8]
-            ; byrRegs +[x1]
             str     x1, [fp,#40]       // [V07 loc4]
             ; GC ptr vars +{V07}
             ldr     x3, [x1,#8]
             mov     x0, x3
             bl      System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers:INetToIPEndPoint(byref):System.Net.IPEndPoint
             ; gcrRegs +[x0]
-            ; byrRegs -[x1-x2]
+            ; byrRegs -[x2]

                [000058] -A-XG-------              *  ASG       byref
                [000057] D------N----              +--*  LCL_VAR   byref  V07 loc4
-               [000056] ---XG-------              \--*  FIELD     byref  hackishFieldName
+               [000056] ---XG-------              \--*  FIELD     long   hackishFieldName
```

There are no code size diffs on `win-x64` with this change.

It does pessimize VN a little because we will now have more cases where a cast VN is added for an assignment, so there are some minor code size differences on other platforms, but VN is already very pessimistic for byrefs, so it seems acceptable.

There are diffs on [`win-x86`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-58297/win-x86.md) in IL stubs that have revealed a potential problem with how copy propagation operates. I have added a test that demonstrates it.

More diffs: [`linux-arm`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-58297/linux-arm.md), [`win-arm64`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-58297/win-arm64.md).

### CODE REVIEW

**Comment by SingleAccretion** [comment]
Mono LLVM failure is #58062, OSX arm64 is #11063. In any case, this change most likely deserves a round of GCStress runs.

**Comment by AndyAyersMS** [comment]
What happens if the assertion we disabled in #56192 is re-enabled?

**Comment by SingleAccretion** [comment]
> What happens if the assertion we disabled in `#56192` is re-enabled?

It seems to me that this change should find more opportunities for the (two) assert(s), given it causes the RHS tree to be evaluated as a non-byref, however, at least SPMI doesn't show new failures (there's one, known, in `System.IO.Hashing`).

It is unclear to me if less retyping is a better place to be in this assert-wise. It is easier to reason about I suppose.

**Review by AndyAyersMS — APPROVED** [review]
Looks good.

Thank you for your continued efforts to improve and simplify the jit.

**Pull request merged**
