### PR TITLE
[Release/5.0] Fix GDI handle leak in Graphics.DrawIcon

### PR DESCRIPTION
**Pull request by safern**
Backport of https://github.com/dotnet/runtime/pull/47836
Fixes https://github.com/dotnet/runtime/issues/46789

## Customer Impact

Customer reported a GDI resource leak in their WinForms application after they targeted it to NET 5.0.

In any application that draws a lot of icons to a graphics object associated to the current device context we would leak GDI+ handles as observed in the issue, which could potentially cause application crashes if we exceed the GDI handles limit imposed by the OS.

This impacts winforms as System.Drawing.Common is part of their shared framework.

## Regression?

Yes, caused by https://github.com/dotnet/corefx/commit/f807df691a3007cea9c7aa169f18be4cd9540758 in 5.0.

## Testing

Manual testing and also included a regression test which was failing before the fix, the test and fix have been in master for about a week already and the test is pretty stable, we haven't seen failures from it or any other System.Drawing test.

## Risk

Low, the fix is just making sure we call GDI.DeleteObject on a handle that is no longer used.

cc: @danmoseley @ericstj @Anipik

### CODE REVIEW

**Comment by danmoseley** [comment]
Updated template to note this was customer reported.

**Review by JeremyKuhne — APPROVED** [review]
:shipit:

**Comment by safern** [comment]
It was approved over email

**Comment by safern** [comment]
Failures are unrelated.

**Pull request merged**
