### PR TITLE
Fix line endings under src/mono

### LINKED ISSUE #2222: Some mono files show as modified on Linux even with clean checkout
I guess that it is most likely caused by wrong line endings, as there was a problem recently with the same symptoms caused by that. I get the following output from git status even though my local repo clone is completely clean:
```
        modified:   src/mono/mono/tests/bug-335131.2.cs
        modified:   src/mono/mono/tests/bug-472600.2.cs
        modified:   src/mono/mono/tests/bug-515884.il
        modified:   src/mono/mono/tests/checked.cs
        modified:   src/mono/mono/tests/exiting/appdomain.out
        modified:   src/mono/mono/tests/exiting/delegate-async-exit.out
        modified:   src/mono/mono/tests/exiting/delegate-delegate-exit.out
        modified:   src/mono/mono/tests/exiting/delegate.out
        modified:   src/mono/mono/tests/exiting/finalizer-abort.out
        modified:   src/mono/mono/tests/exiting/finalizer-exit.out
        modified:   src/mono/mono/tests/exiting/main-exit.out
        modified:   src/mono/mono/tests/exiting/main-returns-abort-resetabort.out
        modified:   src/mono/mono/tests/exiting/main-returns-background-abort-resetabort.out
        modified:   src/mono/mono/tests/exiting/main-returns-background-resetabort.out
        modified:   src/mono/mono/tests/exiting/main-returns-background.out
        modified:   src/mono/mono/tests/exiting/main-returns.out
        modified:   src/mono/mono/tests/exiting/subthread-exit.out
        modified:   src/mono/mono/tests/load-missing.il
        modified:   src/mono/mono/tests/metadata-verifier/module.il
        modified:   src/mono/mono/tests/mutexes.cs
        modified:   src/mono/mono/tests/thread4.cs
        modified:   src/mono/mono/tests/verifier/unverifiable_ldobj_with_generic_type_definition.il
        modified:   src/mono/mono/tests/verifier/unverifiable_throw_with_unboxed_generic_argument.il
        modified:   src/mono/msvc/libmonoruntime.targets
        modified:   src/mono/msvc/mono_csharp.vssettings
        modified:   src/mono/msvc/monoposixhelper.def
        modified:   src/mono/msvc/win32.xml
        modified:   src/mono/netcore/sample/AspNetCore/Properties/launchSettings.json
        modified:   src/mono/netcore/sample/AspNetCore/appsettings.Development.json
        modified:   src/mono/netcore/sample/AspNetCore/appsettings.json
```
Trying to do `git checkout --` on any of these files has no effect.

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #2222

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by jkotas** [comment]
I need to double check that I got it right...

**Comment by marek-safar** [comment]
not sure what that will do with the mirroring

/cc @directhex @akoeplinger

**Comment by akoeplinger** [comment]
Mirror seems to have worked fine: https://github.com/mono/mono/pull/19215

**Review by akoeplinger — APPROVED** [review]

**Comment by jkotas** [comment]
@akoeplinger Could you please merge the mirror PR? I do not seem to have write permission for mono/mono.

**Pull request merged**
