### PR TITLE
Elide SocketFlags in Socket API

### LINKED ISSUE #43934: Consider adding Socket Send/ReceiveAsync overloads that elide SocketFlags argument
## Background and Motivation

The sync methods for Send, Receive, SendTo, and ReceiveFrom all have overloads that don't take a SocketFlags argument. This argument is rarely used.

The Task-based async methods don't have these overloads. We actually approved overloads without SocketFlags for SendTo and ReceiveFrom in #938, but these haven't been implemented yet, and it doesn't really make sense to implement them just for SendTo and ReceiveFrom.

#### Additions to existing overloads
```C#
// Existing overloads in comments
public static class SocketTaskExtensions
{
//  public static Task<int> ReceiveAsync(this Socket socket, ArraySegment<byte> buffer, SocketFlags socketFlags);
    public static Task<int> ReceiveAsync(this Socket socket, ArraySegment<byte> buffer);
    
//  public static Task<int> ReceiveAsync(this Socket socket, IList<ArraySegment<byte>> buffers, SocketFlags socketFlags);
    public static Task<int> ReceiveAsync(this Socket socket, IList<ArraySegment<byte>> buffers);
    
//  public static ValueTask<int> ReceiveAsync(this Socket socket, Memory<byte> buffer, SocketFlags socketFlags, CancellationToken cancellationToken = default(CancellationToken));
    public static ValueTask<int> ReceiveAsync(this Socket socket, Memory<byte> buffer, CancellationToken cancellationToken = default(CancellationToken));
    
//  public static Task<SocketReceiveFromResult> ReceiveFromAsync(this Socket socket, ArraySegment<byte> buffer, SocketFlags socketFlags, EndPoint remoteEndPoint);
    public static Task<SocketReceiveFromResult> ReceiveFromAsync(this Socket socket, ArraySegment<byte> buffer, EndPoint remoteEndPoint);
    
//  public static Task<SocketReceiveMessageFromResult> ReceiveMessageFromAsync(this Socket socket, ArraySegment<byte> buffer, SocketFlags socketFlags, EndPoint remoteEndPoint);
    public static Task<SocketReceiveMessageFromResult> ReceiveMessageFromAsync(this Socket socket, ArraySegment<byte> buffer, EndPoint remoteEndPoint);
    
//  public static Task<int> SendAsync(this Socket socket, ArraySegment<byte> buffer, SocketFlags socketFlags);
    public static Task<int> SendAsync(this Socket socket, ArraySegment<byte> buffer);
    
//  public static Task<int> SendAsync(this Socket socket, IList<ArraySegment<byte>> buffers, SocketFlags socketFlags);
    public static Task<int> SendAsync(this Socket socket, IList<ArraySegment<byte>> buffers);
    
//  public static ValueTask<int> SendAsync(this Socket socket, ReadOnlyMemory<byte> buffer, SocketFlags socketFlags, CancellationToken cancellationToken = default(CancellationToken));
    public static ValueTask<int> SendAsync(this Socket socket, ReadOnlyMemory<byte> buffer, CancellationToken cancellationToken = default(CancellationToken));
    
//  public static Task<int> SendToAsync(this Socket socket, ArraySegment<byte> buffer, SocketFlags socketFlags, EndPoint remoteEP);
    public static Task<int> SendToAsync(this Socket socket, ArraySegment<byte> buffer, EndPoint remoteEP);
}
```

#### Additions to #938

```C#
// #938 overloads in comments
public static class SocketTaskExtensions
{
//  public static ValueTask<int> SendToAsync(this Socket socket, ReadOnlyMemory<byte> buffer, SocketFlags socketFlags, EndPoint remoteEP, CancellationToken cancellationToken = default);
    public static ValueTask<int> SendToAsync(this Socket socket, ReadOnlyMemory<byte> buffer, EndPoint remoteEP, CancellationToken cancellationToken = default);

//  public static ValueTask<SocketReceiveFromResult> ReceiveFromAsync(this Socket socket, Memory<byte> buffer, SocketFlags socketFlags, EndPoint remoteEP, CancellationToken cancellationToken = default);
    public static ValueTask<SocketReceiveFromResult> ReceiveFromAsync(this Socket socket, Memory<byte> buffer, EndPoint remoteEP, CancellationToken cancellationToken = default);

//  public static ValueTask<SocketReceiveMessageFromResult> ReceiveMessageFromAsync(this Socket socket, Memory<byte> buffer, SocketFlags socketFlags, EndPoint remoteEP, CancellationToken cancellationToken = default);
    public static ValueTask<SocketReceiveMessageFromResult> ReceiveMessageFromAsync(this Socket socket, Memory<byte> buffer, EndPoint remoteEP, CancellationToken cancellationToken = default);
}
```

#### Consider: addition to #43933

This is not an async API but probably worth to add.

```C#
// #43933 overload in comments
public class Socket
{
//  public int ReceiveMessageFrom(Span<byte> buffer, ref SocketFlags socketFlags, ref EndPoint remoteEP, out IPPacketInformation ipPacketInformation);
    public int ReceiveMessageFrom(Span<byte> buffer, ref EndPoint remoteEP, out IPPacketInformation ipPacketInformation);
}

```

@scalablecory @wfurt @antonfirsov @stephentoub Thoughts?

### PR DESCRIPTION
**Pull request by i3arnon**
Fix #43934

### CODE REVIEW

**Comment by i3arnon** [comment]
I've left out `ReceiveMessageFrom` as the `SocketFlags` does return data from the operation

**Review by antonfirsov — COMMENTED** [review]
Thank you for the contribution! The implementation looks good. 

What's worrying me that the overloads that elide `SocketFlags` are missing test coverage (both old and new ones). I think we should fix this as part of the current PR.

I believe it would be an overkill to address this by duplicating our tests a couple of more times by adding more `SocketHelperBase` subclasses, unnecessarily penalizing our test execution time. My recommendation would be to change the existing `SocketHelperTask` and `SocketHelperSpanSync` to elide `SocketFlags` in their calls to `Socket`. We aren't really testing the effect of `SocketFlags` in those tests anyways. @geoffkizer do you agree?

> I've left out `ReceiveMessageFrom` as the `SocketFlags` does return data from the operation:

@geoffkizer do you think it's a useful overload regardless? The approved proposal is also questioning them: https://github.com/dotnet/runtime/issues/43934#issuecomment-900535135

**Comment by i3arnon** [comment]
> My recommendation would be to change the existing `SocketHelperTask` and `SocketHelperSpanSync` to elide `SocketFlags` in their calls to `Socket`

Done.



> @geoffkizer do you think it's a useful overload regardless? The approved proposal is also questioning them: [#43934 (comment)](https://github.com/dotnet/runtime/issues/43934#issuecomment-900535135)

I'll add that also in the sync overloads, there's an overload for `ReceiveFrom` that elides the flags, which are **not** passed by ref, but there isn't one for `ReceiveMessageFrom` which passes the flags by ref.

**Comment by geoffkizer** [comment]
> My recommendation would be to change the existing SocketHelperTask and SocketHelperSpanSync to elide SocketFlags in their calls to Socket. We aren't really testing the effect of SocketFlags in those tests anyways. @geoffkizer do you agree?

Just to be clear -- the idea here is that we cover these new overloads by making some of the existing test variations use them, but leave some using the old overloads so we continue to have coverage for those as well?

That seems reasonable to me. 

Let's make sure to add comments that explain this, otherwise it will be far from obvious and we'll look at the code in the future and say "why are we using these overloads here but those overloads there??"

**Comment by geoffkizer** [comment]
> I'll add that also in the sync overloads, there's an overload for ReceiveFrom that elides the flags, which are not passed by ref, but there isn't one for ReceiveMessageFrom which passes the flags by ref.

This is a strong argument for not eliding the flags on ReceiveMessageFrom.

**Review by antonfirsov — COMMENTED** [review]
Just one thing, and this is good to merge. I think we should leave out the sync `ReceiveMessageFrom`.

**Review by antonfirsov — APPROVED** [review]
LGTM. Shall be good to merge once outerloop CI completes.

**Comment by antonfirsov** [comment]
Outerloop failures are unrelated (#32955 and a bunch of ProcessStartInfo tests on Windows 11).

**Comment by antonfirsov** [comment]
@i3arnon thanks again for the work and your patience!

**Pull request merged**
