### PR TITLE
[mono][debugger] Remove cast bug

### LINKED ISSUE #86765: Blazor Wasm: debugging broken by attribute with type parameter
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a generic attribute is applied in a hosted Blazor Web Assembly project, debugging is broken.

Reproduction is here:  https://github.com/zbecknell/UndebuggableV2

Notice `Index.razor` is applying `@attribute [Bad<App>]`.  Remove that line and debugging now works.

Clues as to how to fix this would hopefully be found in this old previous issue https://github.com/dotnet/aspnetcore/issues/25380 where the same thing would happen when an attribute had an `enum` parameter.

### Expected Behavior

Debugging the client web assembly application hits breakpoints as expected.

### Steps To Reproduce

Run and attempt to debug the client side of this hosted web assembly app: https://github.com/zbecknell/UndebuggableV2

### Exceptions (if any)

The console outputs this when failure occurs:

```
[13:14:55] fail: DevToolsProxy[0]
      Failed to load https://localhost:7129/_framework/DebugTest.Client.dll (Specified cast is not valid.)
```

### .NET Version

7.0.302

### Anything else?

System info (though this is reproduced across OSs):

```
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.302/

Host:
  Version:      7.0.5
  Architecture: arm64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.100 [/usr/local/share/dotnet/sdk]
  7.0.200 [/usr/local/share/dotnet/sdk]
  7.0.203 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/86765.

We had an exception on operation `metadataReader.GetTypeReference((TypeReferenceHandle)container.Value).Name` - while for regular custom attributes the type there was `TypeReference`, for generic custom attributes from the issue it was `TypeSpecification` (unable to cast).

### CODE REVIEW

**Review by thaystg — APPROVED** [review]

**Comment by ilonatommy** [comment]
Failures: multithreaded debugger + SetBreakpointInProjectWithSpecialCharactersInPath - not connected.

**Comment by radical** [comment]
@ilonatommy Could you please add some details to the PR description?

**Pull request merged**
