### PR TITLE
Revert "Initial runtime changes for composite support"

### PR DESCRIPTION
**Pull request by jkotas**
Reverts dotnet/runtime#32500

### CODE REVIEW

**Comment by jkotas** [comment]
The change broke debugging because of the code is not DACized correctly.

windbg is enable to resolve managed symbols in R2R images, etc. This makes us unable to triage and diagnose other crashes happening in CI.

**Comment by jkotas** [comment]
cc @trylek

**Review by trylek — APPROVED** [review]
Thanks Jan for doing this. Can you please advise me how to "test that debugging works" or that "the code is DACized properly" prior to sending out an updated PR for this change?

**Comment by tommcdon** [comment]
@dotnet/dotnet-diag SOS ClrStack -n should be able to reproduce the issue (https://github.com/dotnet/diagnostics/blob/master/documentation/sos-debugging-extension.md)

**Comment by jkotas** [comment]
As @tommcdon said. You may want to `set COMPlus_TieredCompilation=0` to prevent the tiered compilation from kicking it that will make the problem easier to reproduce.

**Pull request merged**
