### PR TITLE
[mono] Don't generate safepoints inside write barrier wrapper

### PR DESCRIPTION
**Pull request by BrzVlad**
A ref store and its associated write barrier need to happen atomically relative to garbage collections. No GCs should happen between the ref store and the card mark.

### CODE REVIEW

**Comment by BrzVlad** [comment]
@imhameed @EgorBo I think I might be missing a place where safe points are added. I think there is some logic in llvm itself adding safepoints. Any observations ?

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
Do we have a list of LLVM passes that we use somewhere?  It should be the https://llvm.org/docs/Statepoints.html#placesafepoints PlaceSafepoints pass that adds calls to `gc.safepoint_poll`.  I don't see anything in the documentation about how to tell it to keep safepoints out of particular functions.  But maybe that's evident in the implementation of the pass? @imhameed 

I guess the way to mark a `Function` not to do a safepoint is to make sure that `Function::getGC` returns something other than `"mono"` (or "coreclr" or "safepoint-example"), right?   Do we have that exposed to the aot-compiler?

**Comment by imhameed** [comment]
> @imhameed @EgorBo I think I might be missing a place where safe points are added. I think there is some logic in llvm itself adding safepoints. Any observations ?

Calls to `gc.safepoint_poll` are automatically inserted by the `PlaceSafepoints` pass, which we always use with LLVM as an AOT backend and LLVM as a JIT backend.

**Comment by imhameed** [comment]
> Do we have a list of LLVM passes that we use somewhere? It should be the https://llvm.org/docs/Statepoints.html#placesafepoints PlaceSafepoints pass that adds calls to `gc.safepoint_poll`.

We don't have a centralized list of all the LLVM passes we use, and the passes we use differ between LLVM AOT and LLVM as a JIT. For AOT, the flags we pass to opt and llc are [here](https://github.com/dotnet/runtime/blob/5df6cc63151d937724fa0ce8138e69f933052606/src/mono/mono/mini/aot-compiler.c#L10060).

> I think the decision of which functions should get safepoints is controlled by `PlaceSafepoints::shouldRewriteFunction` https://github.com/dotnet/llvm-project/blob/release/11.x/llvm/lib/Transforms/Scalar/PlaceSafepoints.cpp#L454-L456
> 
> I guess the way to mark a `Function` not to do a safepoint is to make sure that `Function::getGC` returns something other than `"mono"` (or "coreclr" or "safepoint-example"), right? Do we have that exposed to the aot-compiler?

You could call `LLVMSetGC(method, NULL)` to make `PlaceSafepoints::runOnFunction` leave your function alone (or simply not call `LLVMSetGC` at all).

**Comment by lambdageek** [comment]
> > Do we have a list of LLVM passes that we use somewhere? It should be the https://llvm.org/docs/Statepoints.html#placesafepoints PlaceSafepoints pass that adds calls to `gc.safepoint_poll`.
> 
> We don't have a centralized list of all the LLVM passes we use, and the passes we use differ between LLVM AOT and LLVM as a JIT. For AOT, the flags we pass to opt and llc are [here](https://github.com/dotnet/runtime/blob/5df6cc63151d937724fa0ce8138e69f933052606/src/mono/mono/mini/aot-compiler.c#L10060). For JIT, the passes we use are listed [here](https://github.com/dotnet/runtime/blob/5df6cc63151d937724fa0ce8138e69f933052606/src/mono/mono/mini/llvm-jit.cpp#L181) and [here](https://github.com/dotnet/runtime/blob/5df6cc63151d937724fa0ce8138e69f933052606/src/mono/mono/mini/llvm-jit.cpp#L496).
> 
> > I think the decision of which functions should get safepoints is controlled by `PlaceSafepoints::shouldRewriteFunction` https://github.com/dotnet/llvm-project/blob/release/11.x/llvm/lib/Transforms/Scalar/PlaceSafepoints.cpp#L454-L456
> > I guess the way to mark a `Function` not to do a safepoint is to make sure that `Function::getGC` returns something other than `"mono"` (or "coreclr" or "safepoint-example"), right? Do we have that exposed to the aot-compiler?
> 
> You could call `LLVMSetGC(method, NULL)` to make `PlaceSafepoints::runOnFunction` leave your function alone (or simply not call `LLVMSetGC` at all).

@BrzVlad So add the barrier wrapper here:
https://github.com/dotnet/runtime/blob/b6cc82253bbca3f01e7c68094bedfbec18bc5469/src/mono/mono/mini/mini-llvm.c#L11464-L11470

@imhameed Why do we bother with a "mono" GC type when the runtime actually uses "coreclr" 🤪

**Comment by BrzVlad** [comment]
Refactored the code a little bit so we disable safepoints in GC wrappers both on aot and !aot.

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
@BrzVlad do we want this for 6.0? How risky is it?

**Review by imhameed — APPROVED** [review]

**Comment by BrzVlad** [comment]
I think the risk is low but not negligible. 

I don't know if this issue ever lead to a crash, so I don't think it is a mandatory backport.

This change might have some noticeable perf gains on AOT since we avoid wrapper + safepoints for stores into ref fields, so that could be a motivating factor. Maybe if we see some crazy perf gains in the benchmark runs that could justify it.

**Pull request merged**
