### PR TITLE
Fix issue #36999

### PR DESCRIPTION
**Pull request by Nikolay-parhimovich**
Fix issue #36999 :
Created two resources string for exceptions.
Replaced static strings with resource.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43723) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43723) before we can accept your contribution.<br/><br/>:x: Nikolay-parhimovich [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43723)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=43723) it.</sub>

**Review by kjpou1 — APPROVED** [review]
Looks good to me.  Thanks Nikolay

**Review by lewing — APPROVED** [review]
Thanks!

**Review by kjpou1 — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]
Thanks. (These were also being handled in the larger https://github.com/dotnet/runtime/pull/43414 from @Marusyk.)

**Pull request merged**
