### PR TITLE
remove repetitions ';'

### PR DESCRIPTION
**Pull request by kronic**
Cleanup code

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
Thanks. LGTM.  There's a related stylecop rule we should look at subsequently enabling.

**Comment by kronic** [comment]
@stephentoub I think now is the time

**Comment by stephentoub** [comment]
> Where can I enable it?

You'd change the "None" in this line to be "Warning":
https://github.com/dotnet/runtime/blob/400311b032fe5d05b49fb6a813e4a5a60604d8dd/eng/CodeAnalysis.ruleset#L289

I've not tried and don't know what else it might flag.  Feel free to try.

**Comment by stephentoub** [comment]
Turns out we can't enable SA1106.  I just tried it, and it's flagging empty-body loops as empty statements.

**Comment by danmoseley** [comment]
cc @sharwell

**Comment by sharwell** [comment]
> Turns out we can't enable SA1106. I just tried it, and it's flagging empty-body loops (which we allow) as empty statements

Yes, this is unlikely to change for StyleCop Analyzers. However, the relaxed form of the rule you want seems reasonably likely to get accept as part of the code style package in Roslyn so maybe we implement it there?

**Comment by stephentoub** [comment]
@sharwell, sounds good to me.

**Pull request merged**
