### PR TITLE
Fix threading issue in MulticoreJit

### LINKED ISSUE #46778: MulticoreJIT accesses `m_GenericInfoCount` field from multiple threads without synchronization
See MultiCoreJitRecord::WriteOutput for an example.

This looks like it can cause memory corruption.

### PR DESCRIPTION
**Pull request by clamp03**
Fix https://github.com/dotnet/runtime/issues/46778 issue

### CODE REVIEW

**Comment by clamp03** [comment]
It writes a profile file once (default is 12 seconds after a first method is recorded ) while an application is running. It may block execution for a long time.

**Comment by clamp03** [comment]
@jkotas Could you review?
PlayerLock is locked before StopProfile in WriteMulticoreJitProfiler like others. Actually, I concern about the execution block. If you have any other way, please share.
And does it really need to write a profile while an application runs in non-unix? If possible, I want to remove it.

**Comment by jkotas** [comment]
> And does it really need to write a profile while an application runs in non-unix? 

I suspect that there are applications out there that depend on this behavior on Windows. We would need to go through the breaking change process to delete this delayed write.

**Review by jkotas — APPROVED** [review]
LGTM. Thank you for fixing this

**Pull request merged**
