### PR TITLE
Less aggressive `stfld` spilling

### LINKED ISSUE #71638: Importer's spilling logic for `stfld` is not correct
Reproduction (requires `InlineIL.Fody`):
```cs
using InlineIL;
using System;
using System.Runtime.CompilerServices;

int b = 0;
Console.WriteLine(Problem(10, ref b));

[MethodImpl(MethodImplOptions.NoInlining)]
static int Problem(int a, ref int b)
{
    IL.Emit.Ldarga(0);
    IL.Emit.Starg(1);

    IL.Emit.Ldarg(0);
    IL.Emit.Ldarg(1);
    IL.Emit.Ldc_I4(0);
    IL.Emit.Stfld(new FieldRef(typeof(StructWithIndex), "Index"));

    return IL.Return<int>();
}

struct StructWithIndex
{
    public int Index;
}
```
Compile and run.

Expected result: program prints `10`.

Actual result: program prints `0`.

Cause: the importer sometimes only spills "value classes" (`TYP_STRUCT`-containing trees) here:

https://github.com/dotnet/runtime/blob/a583698b809bc21d932c86d68c01c02529e259d1/src/coreclr/jit/importer.cpp#L16277-L16302

### PR DESCRIPTION
**Pull request by SingleAccretion**
The spilling logic for `st[s]fld` was quite quite complex, and not complete. Replace it with the simple spilling of side effects and global data accesses, which is all that's needed.

The new logic is less conservative because it doesn't spill invariant nodes when the assign is to a struct field, so we see a good number of positive diffs.

Fixes #71638.

[Diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1868040&view=ms.vss-build-web.run-extensions-tab).

### CODE REVIEW

**Comment by SingleAccretion** [comment]
Fuzzer failures look preexisting.

@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Can you look into some of the larger diffs? eg x64 win libraries pmi:
```
Top method regressions (percentages):
         266 (30.09 % of base) : 242426.dasm - ILCompiler.DependencyAnalysis.ReadyToRun.ImportThunk:EmitCode(ILCompiler.DependencyAnalysis.NodeFactory,byref,bool):this
```

**Comment by AndyAyersMS** [comment]
How many temps do we end up with in that case? I though we only backed off inlining once we got near the tracking limit.

**Comment by SingleAccretion** [comment]
> How many temps do we end up with in that case?

Overall in the diffs (i. e. with the new inlinees) we have only 83 locals.

> I though we only backed off inlining once we got near the tracking limit.

I think it's this heuristic that's responsible:

https://github.com/dotnet/runtime/blob/0ab2c1e92e2383b3969688ede5bbcf106527bbcb/src/coreclr/jit/inlinepolicy.cpp#L1707-L1714

**Comment by AndyAyersMS** [comment]
> I think it's this heuristic that's responsible:

Ah, right. Thanks for investigating.

**Review by AndyAyersMS — APPROVED** [review]

**Pull request merged**
