### PR TITLE
Use a list for tests in src/tests/run.py

### LINKED ISSUE #78462: Local test run fails to analyze HardwareIntrinsics test results
After a local crossgen2 tests run, using `.\src\tests\run.cmd checked runcrossgen2tests`, I hit

```
Analyzing C:\dev\dotnet\runtime2\artifacts\log\JIT.HardwareIntrinsics.HardwareIntrinsics_r.testRun.xml
Analyzing C:\dev\dotnet\runtime2\artifacts\log\JIT.HardwareIntrinsics.HardwareIntrinsics_ro.testRun.xml
Traceback (most recent call last):
  File "C:\dev\dotnet\runtime2\src\tests\run.py", line 1411, in <module>
    sys.exit(main(args))
  File "C:\dev\dotnet\runtime2\src\tests\run.py", line 1399, in main
    parse_test_results(args, tests, assemblies)
  File "C:\dev\dotnet\runtime2\src\tests\run.py", line 1196, in parse_test_results
    parse_test_results_xml_file(args, item, item_name, tests, assemblies)
  File "C:\dev\dotnet\runtime2\src\tests\run.py", line 1255, in parse_test_results_xml_file
    assert tests[test_name] == None
AssertionError
```

There is a test named `JIT.HardwareIntrinsics.Arm::Abs_Vector128_Double (global::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.Abs_Vector128_Double())` in both `JIT.HardwareIntrinsics.HardwareIntrinsics_r.testRun.xml` and `JIT.HardwareIntrinsics.HardwareIntrinsics_ro.testRun.xml` which causes the assert.

Does the analysis need to disambiguate by the assembly somehow too?

cc @davidwrighton, presumably related to your recent changes here

### PR DESCRIPTION
**Pull request by jakobbotsch**
Fix #78462

### CODE REVIEW

**Comment by BrianBohe** [comment]
Can we change the test names and leave this as a check for future problems?

**Comment by jakobbotsch** [comment]
> Can we change the test names and leave this as a check for future problems?

It's like I said above – I don't think it matters.

**Comment by jakobbotsch** [comment]
For example, here's one of these test failures:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=81571&view=ms.vss-test-web.build-test-results-tab&runId=1704060&resultId=110825&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

You can see both `HardwareIntrinsics_r` as the work item name and when you look at the console log:
```scala
BEGIN EXECUTION
/datadisks/disk1/work/B5A409B3/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false HardwareIntrinsics_r.dll ''
23:16:14.616 Running test: global::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.Abs_Vector128_Double()
Supported ISAs:
```

Anyway, I will leave it up to @trylek and @davidwrighton whether they think this fix is ok, or if we should try to disambiguate the hardware intrinsics test names by assembly also. I'm not sure where to do the latter after #74886.

**Review by BruceForstall — APPROVED** [review]
LGTM, but feel free to wait for @trylek and/or @davidwrighton for more context

**Review by trylek — APPROVED** [review]
Nice, thanks for fixing this!

**Comment by davidwrighton** [comment]
I think this change is fine, but I'll admit I with the testresults.xml file had the distinction in it itself.

**Pull request merged**
