### PR TITLE
Remove obsolete managedOsxBuild et. al

### PR DESCRIPTION
**Pull request by sdmaclea**
Remove managedOsxBuild
Remove managedTestBuildOsGroup
Remove managedTestBuildOsSubgroup

### CODE REVIEW

**Comment by sdmaclea** [comment]
@trylek I assumed this is what you were looking for when you ask to clean up `managedTestBuildOsGroup`

@naricc @direecthex I am not sure if this will negatively impact Mono

**Comment by naricc** [comment]
I'm not sure if I appreciate what this PR does. What is managedTestBuildOsGroup/Subgroup vs OsGroup/Subgroup? What does removing it do?

**Comment by sdmaclea** [comment]
This was driven by @trylek comment 
> 2.	Get rid of managedBuildOsGroup/Subgroup as it should be superfluous with this change

The PR he was referring to was splitting the build of AnyOS AnyCPU CoreCLR tests (`TargetGeneric`) from target specific tests.

`managedBuildOsGroup`/`Subgroup` allowed building tests on one platform and running them on another.
 
As I was removing this, I saw cases where Mono wasn't setting `osGroup` the same as `managedBuildOsGroup`. I copied @naricc because I saw you authored the patch to run these tests for Mono.

**Comment by naricc** [comment]
It seems like we don't need this.

**Review by naricc — APPROVED** [review]

**Review by trylek — APPROVED** [review]
LGTM, thanks for cleaning this up!

**Comment by sdmaclea** [comment]
Reverted by #35647 
This caused outerloop failures because outerloop builds are still running OSX tests.

Will revisit after #35645 goes in and then is generalized for all pipes.

**Pull request merged**
