### PR TITLE
Clean-up generators.targets

### PR DESCRIPTION
**Pull request by ViktorHofer**
From what I can see, the two targets in generators.targets aren't used anymore. The `LibraryImportGenerator_UseMarshalType` setting was already defined in LibraryImportGenerator.props. Also, remove that props file and inline the values into generators.targets.

### CODE REVIEW

**Review by jkoritzinsky — COMMENTED** [review]
We have the props file so we have a close relationship between which options the LibraryImportGenerator supports and the MSBuild infrastructure to expose the options. Can we add a comment around the `CompilerVisibleProperty` items saying to keep in sync with the OptionsHelper.cs file in LibraryImportGenerator?

**Comment by elinor-fung** [comment]
> Also, remove that props file and inline the values into generators.targets.

Is that the general best practice for libraries generators? I find it nice to have the separate props right next to the generator itself. That way it is easy to see what settings there are for the generator.

**Comment by ViktorHofer** [comment]
A props file adds value when it is imported by another props file, i.e. Directory.Build.props. It's benefit is questionable if a props file is imported by targets file. That said, I'm fine with keeping it if that's desirable.

**Comment by jkoritzinsky** [comment]
We can create a generators.props file that just includes the props files for generator options if that makes it more worthwhile.

**Comment by ViktorHofer** [comment]
Closing as this doesn't seem necessary.

**Pull request closed without merging**
