### PR TITLE
Update System.Drawing.Common stable versions to fix harvesting

### LINKED ISSUE #44480: Libraries AllConfigurations leg failing
The Libraries AllConfigurations leg is failing with the following error:

> Validation Failed: System.Drawing.Common is harvesting assets from package version 4.7.0 which is not the latest for that package release. Latest package version from that release is 4.7.1. In order to fix this, run `dotnet msbuild System.Drawing.Common.pkgproj /t:UpdateHarvestVersionOnPackageIndex /p:UpdateStablePackageInfo=true`

Looks like something broke now that we released new stable package versions.

cc: @Anipik

### PR DESCRIPTION
**Pull request by safern**
Fixes: https://github.com/dotnet/runtime/issues/44480

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Merging to unblock CI.

**Comment by ViktorHofer** [comment]
@safern I assume we need to backport the change to 5.0?

**Comment by safern** [comment]
> @safern I assume we need to backport the change to 5.0?

Yeah

**Comment by ericstj** [comment]
One thought here for how we make this less breaking: what if we only turn this on for release branches?  Thoughts @joperezr / @Anipik?

**Comment by safern** [comment]
I think that would work as whenever we branch for a preview or a release we turn it off and it will fail to remind us to update this. However, daily built packages could be broken.

**Pull request merged**
