### PR TITLE
Enable passing coreclr tests

### PR DESCRIPTION
**Pull request by fanyang-mono**
Enable passing coreclr tests mentioned by #35960

### CODE REVIEW

**Comment by SamMonoRT** [comment]
@naricc - why are Mono Pri 0 lanes not running in this PR ?

**Comment by naricc** [comment]
> @naricc - why are Mono Pri 0 lanes not running in this PR ?

I think it is because of the extra / here: https://github.com/dotnet/runtime/blob/cf1390cbb7262fbedbbfc677f49a7fb3ed0df336/eng/pipelines/runtime.yml#L110

The other paths don't have it. But it was working before for test changes; I'm not sure if something else changed so it no longer works with that leading /.

**Comment by naricc** [comment]
PR to get rid of that /: https://github.com/dotnet/runtime/pull/36722

**Comment by SamMonoRT** [comment]
@naricc - still don't see Mono lanes, I assume this is after your last PR was merged to remove the '/'

**Comment by safern** [comment]
PR to fix that is here: https://github.com/dotnet/runtime/pull/36780

**Comment by safern** [comment]
I've merged my PR. Re-running the build.

**Comment by safern** [comment]
I just doubled checked and now it works 😄 

```script
Script contents:
eng/pipelines/evaluate-changed-paths.sh --azurevariable containsChange --difftarget origin/master --subset runtimetests --includepaths 'src/coreclr/tests/*+src/coreclr/build-test.sh'
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/runners/2.168.2/work/_temp/00fc6f97-14f5-4c8b-acce-78e622fc7997.sh

******* Probing runtimetests include paths *******
src/coreclr/tests/*
src/coreclr/build-test.sh

+ git diff -M -C -b --ignore-cr-at-eol --ignore-space-at-eol --exit-code --quiet origin/master -- ':src/coreclr/tests/*' :src/coreclr/build-test.sh

----- Matching files for runtimetests -----
+ git diff -M -C -b --ignore-cr-at-eol --ignore-space-at-eol --name-only origin/master -- ':src/coreclr/tests/*' :src/coreclr/build-test.sh
src/coreclr/tests/issues.targets

Setting pipeline variable containsChange=true
```

**Review by naricc — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Pull request merged**
