### PR TITLE
Apple Silicon enable R2R CI testing

### PR DESCRIPTION
**Pull request by sdmaclea**
This enables R2R testing on Apple Silicon.
It also enables the R2R stress testing in R2R-extra

/cc @mangod9

### CODE REVIEW

**Comment by sdmaclea** [comment]
I guess I need to enable 
```
runtime-coreclr crossgen2
runtime-coreclr crossgen2 outerloop
runtime-coreclr crossgen2-composite
runtime-coreclr crossgen2-composite gcstress
```
Too.

**Review by AntonLapounov — APPROVED** [review]
Thank you!

**Review by hoyosjs — APPROVED** [review]

**Comment by sdmaclea** [comment]
I am going to merge this.  The pipelines are not green, but other platforms aren't either. 

The macOS-arm64 issues look like the typical macOS issues....

**Pull request merged**
