### PR TITLE
[wasm] Wasm.Build.Tests: add support for shared builds

### PR DESCRIPTION
**Pull request by radical**
- Essentially, we want to share builds wherever possible. Example cases:

    - Same build, but run with different hosts like v8/chrome/safari, as
      separate test runs
    - Same build but run with different command line arguments

- Sharing builds especially helps when we are AOT'ing, which is slow!

- This is done by caching the builds with the key:

    `public record BuildArgs(string ProjectName, string Config, bool AOT, string ProjectFileContents, string? ExtraBuildArgs);`

- Also, ` SharedBuildClassFixture` is added, so that the builds can be
  cleaned up after all the tests in a particular class have finished
  running.

- Each test run gets a randomly generated test id. This is used for
  creating:
  1. build paths, like `artifacts/bin/Wasm.Build.Tests/net6.0-Release/browser-wasm/xharness-output/logs/n1xwbqxi.ict`
  2. and the log for running with xharness, eg. for Chrome, are in
     `artifacts/bin/Wasm.Build.Tests/net6.0-Release/browser-wasm/xharness-output/logs/n1xwbqxi.ict/Chrome/`

- split `WasmBuildAppTest.cs` into : `BuildTestBase.cs`, and
  `MainWithArgsTests.cs`.

Note: In interest of lowering test run times, this builds the tests in `Release` config only, on CI.
But when running the tests locally, both `Debug`, and `Release` configs are used.

### CODE REVIEW

**Comment by radical** [comment]
This will be rebased once #49446 is merged.

**Comment by radical** [comment]
Unrelated test failures.

**Review by steveisok — APPROVED** [review]
LGTM. I'm curious the average helix run time w/ these changes.

**Comment by radical** [comment]
AFAICS, the test time stays at about 45mins. With this one we actually are building only `Release`, but https://github.com/dotnet/runtime/pull/49559 will enable testing for `Debug` too. And I will add support to enable more parallelization.

Though when I look at the run times for the individual runs for wasm.build tests, they seem to be around ~25mins.

**Comment by radical** [comment]
> AFAICS, the test time stays at about 45mins.

The total helix step wasm 45mins when I looked at one of the earlier `main` builds. The wasm.build test run itself takes ~25mins, it runs in parallel to the library tests.

**Comment by radical** [comment]
Repeatedly getting test run failures:

```
.packages/microsoft.dotnet.helix.sdk/6.0.0-beta.21155.1/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(47,5): error : (NETCORE_ENGINEERING_TELEMETRY=Helix) RestApiException`1: The response contained an invalid status code 500 Internal Server Error

Body: {"Message":"An error occured.","ActivityId":"0ade13a01812c1468a790d153e2fc3a0"}
   at Microsoft.DotNet.Helix.Client.Storage.OnNewFailed(Request req, Response res) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Storage.cs:line 202
   at Microsoft.DotNet.Helix.Client.Storage.NewAsync(ContainerCreationRequest body, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Storage.cs:line 164
   at Microsoft.DotNet.Helix.Client.ApiBlobHelper.GetContainerAsync(String requestedName, String targetQueue, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobSender/StorageHelpers/ApiBlobHelper.cs:line 22
   at Microsoft.DotNet.Helix.Client.JobDefinition.SendAsync(Action`1 log, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs:line 157
   at Microsoft.DotNet.Helix.Sdk.SendHelixJob.ExecuteCore(CancellationToken cancellationToken) in /_/src/Microsoft.Dot
```

.. tracked in https://github.com/dotnet/core-eng/issues/12499 .

**Comment by radical** [comment]
investigating the test run time

**Comment by radical** [comment]
@akoeplinger with your suggested change (https://github.com/dotnet/runtime/pull/49398/commits/7caed5ab609f499e471a2012192ccb225a5714f9) it ran in 43mins, instead of 59! 👍

**Comment by radical** [comment]
@lewing @steveisok this is ready for another look! And hopefully merge :D

**Review by steveisok — APPROVED** [review]

**Pull request merged**
