### PR TITLE
[browser] optimize condition on mono_log_debug

### PR DESCRIPTION
**Pull request by pavelsavara**

### CODE REVIEW

**Review by kg — APPROVED** [review]
Thanks for doing this!

**Comment by kg** [comment]
```
[warning] MONO_WASM: Failed to import library initializer '../WasmBasicTestApp.lib.module.js': ReferenceError: mono_always_log_debug is not defined
[warning] MONO_WASM: mono_exit A failed ReferenceError: mono_always_log_debug is not defined
    at et (http://127.0.0.1:36513/_framework/dotnet.js:3:21128)
    at Object.create (http://127.0.0.1:36513/_framework/dotnet.js:3:38329)
    at async http://127.0.0.1:36513/main.js:89:71
[error] MONO_WASM: mono_always_log_debug is not defined
ReferenceError: mono_always_log_debug is not defined
    at at (http://127.0.0.1:36513/_framework/dotnet.js:3:33959)
    at http://127.0.0.1:36513/_framework/dotnet.js:3:31339
    at async http://127.0.0.1:36513/_framework/dotnet.js:3:38276
    at async Object.create (http://127.0.0.1:36513/_framework/dotnet.js:3:38045)
    at async http://127.0.0.1:36513/main.js:89:71
[info] WASM EXIT 1
[ERROR] PageError: ReferenceError: mono_always_log_debug is not defined
    at at (http://127.0.0.1:36513/_framework/dotnet.js:3:33959)
    at http://127.0.0.1:36513/_framework/dotnet.js:3:31339
    at async http://127.0.0.1:36513/_framework/dotnet.js:3:38276
    at async Object.create (http://127.0.0.1:36513/_framework/dotnet.js:3:38045)
    at async http://127.0.0.1:36513/main.js:89:71
```

**Comment by pavelsavara** [comment]
MT CI fails with https://github.com/dotnet/runtime/issues/102196

**Comment by pavelsavara** [comment]
/ba-g MT CI fails with https://github.com/dotnet/runtime/issues/102196

**Pull request merged**
