### PR TITLE
Host test error format

### PR DESCRIPTION
**Pull request by vitek-karas**
The host tests use FluentAssertions which has its own implementation of string formatting, for things like `FailWith("Some {0}", "message\r\nline")`. Instead of taking the string replacement as-is, it formats it by wrapping it in double quotes and replaces newlines with escaped values, so the above would output:
```
Some "message\r\nline"
```

This makes the test output quite hard to read without formatting it back (by unescaping the newlines).

Unfortunately FluentAssertions tries hard to always run the value through its own formatter. So even if we preformat everything and instead call `FailWith($"Some {"message\r\nline"})` it only works sometimes. The string is still parsed and the parser may fail if it finds for example only an open `{` without a closing one. This makes it nest to useless as we would have to make sure to somehow escape everything we feed in.

So this change introduces a new extension method `FailWithPreformatted` which circumvents the automatic formatting and uses the underlying `AddFailure` method which will not format anything.

### CODE REVIEW

**Comment by vitek-karas** [comment]
@am11 you suggested doing something about this - so I gave it a try. It's probably not super clean, but it works.

**Comment by am11** [comment]
Thanks, @vitek-karas! This will make error messages readable in AzDO test views. 👍

ps - the format I personally like to use consistently (wherever I can) for logging / exception messages is:
```
<constant short description string>. <variable k/v>
```
e.g.
```diff
- The resolved "assemblies" contains unexpected value: "D:\a\_work..."
- Arguments: resolved...
- Exit Code: 0
+ Unexpected resolved value encountered.
+ Property: assemblies
+ Value: "D:\a\_work..."
+ Arguments: resolved
+ Exit Code: 0
```
such consistency makes searching and parsing (by humans / tools) slightly more efficient, especially for those who deal with torrents of log streams frequently. 😄

**Comment by vitek-karas** [comment]
That sounds a bit like serialization - basically making it sort of machine readable.
I'm not totally against it... but it's true that I was mostly going for humanly readable.

Curious - what kind of tools are you thinking - like regexes, or something more complicated.

**Comment by am11** [comment]
> That sounds a bit like serialization

Yup, a little. The constant part makes the messages slightly more discoverable / searchable, while keeping it equally readable, IMO that is. :)

> Curious - what kind of tools are you thinking - like regexes, or something more complicated.

We use multiple services (logentries, datadog and application insight in Azure) to capture volume of logs from different cloud services / microservices. System-wide consistency in log message format is not easy to establish, but when/if it does, it makes live operations folks life bit easier while troubleshooting issues in production-like environments; manual analysis or using query syntax (python based, regexes and other query languages such as kusto in Azure).

**Review by elinor-fung — APPROVED** [review]

**Pull request merged**
