### PR TITLE
FinalCoreFXRenames

### PR DESCRIPTION
**Pull request by eanova**
The last of the CoreFX renames.  Anything remaining are generally Issue urls for the old repo. Is there a simple way to remove these links if the issue is closed already?

@danmosemsft @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please resolve the conflicts?

> generally Issue urls for the old repo

We are working on the issues separately. They corefx issue urls can stay, for now at least.

**Comment by eanova** [comment]
Looks like an error in DirectorySearcher.cs.  I'll push another commit shortly.

**Review by jkotas — APPROVED** [review]

**Comment by eanova** [comment]
Anything I can do about the failed tests?  Looks like they are unrelated but they seem to be all Json Tests.

**Comment by jkotas** [comment]
Yeah, it looks like a CI problem. Could you please push another merge from master to reset the CI?

**Comment by eanova** [comment]
Should I start a new PR?  Also I'm not sure where these two other commits are coming from? My fork is also giving me weird numbers of being 36000 commits behind master, pretty sure that's not possible.

**Comment by jkotas** [comment]
> Should I start a new PR?

Yes, that may be the easiest way to fix this. Rebase everything on top of current master if possible.

> being 36000 commits behind master, pretty sure that's not possible.

It is possible. We just merged PR that added Mono runtime, including the history that added a lot of commits.

**Pull request closed without merging**
