### PR TITLE
Generate type generic composition information as constructed

### LINKED ISSUE #105034: MissingMethodException thrown in native AoT application using AddStandardResilienceHandler() with .NET 9 preview.2
### Description

I've been testing an application of mine which is a native AoT application deployed to AWS Lambda with .NET 9. As part of the testing I wanted to try out the new [JsonSerializerOptions.AllowOutOfOrderMetadataProperties](https://github.com/dotnet/runtime/pull/97474) property to support using polymorphism with the JSON serialization for types used by the AWS Alexa skills API.

Having resolved an issue with getting that to work properly, I've run into a new issue where trying to resolve an `HttpClient` with HttpClientFactory when `AddStandardResilienceHandler()` has been associated with all instances causes a `MissingMethodException` to be thrown (https://github.com/martincostello/alexa-london-travel/pull/1116#issuecomment-2016517791).

```
System.MissingMethodException: Constructor on type 'Polly.Registry.ResiliencePipelineRegistryOptions`1[Microsoft.Extensions.Http.Resilience.Internal.HttpKey]' not found.
   at System.Activator.CreateInstance[T]() + 0x88
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String) + 0x38
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value() + 0xbc
   at Polly.PollyServiceCollectionExtensions.<>c__6`1.<AddResiliencePipelineRegistry>b__6_0(IServiceProvider serviceProvider) + 0x3c
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite, RuntimeResolverContext) + 0x1c
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite, RuntimeResolverContext) + 0x74
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument) + 0xb8
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite, ServiceProviderEngineScope) + 0x34
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier) + 0x130\n   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier, ServiceProviderEngineScope) + 0x384
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider, Type) + 0xc8
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider) + 0x30
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite, RuntimeResolverContext) + 0x1c
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite, RuntimeResolverContext) + 0x74
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument) + 0xb8
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite, ServiceProviderEngineScope) + 0x34
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier) + 0x130\n   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier, ServiceProviderEngineScope) + 0x384
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider, Type) + 0xc8\n   at Microsoft.Extensions.DependencyInjection.ResilienceHttpClientBuilderExtensions.CreatePipelineSelector(IServiceProvider, String) + 0x48
   at Microsoft.Extensions.DependencyInjection.ResilienceHttpClientBuilderExtensions.<>c__DisplayClass6_0.<AddResilienceHandler>b__0(IServiceProvider serviceProvider) + 0x20
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass3_0.<AddHttpMessageHandler>b__1(HttpMessageHandlerBuilder) + 0x24
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass17_0.<CreateHandlerEntry>g__Configure|0(HttpMessageHandlerBuilder) + 0x78
   at Microsoft.Extensions.Http.MetricsFactoryHttpMessageHandlerFilter.<>c__DisplayClass2_0.<Configure>b__0(HttpMessageHandlerBuilder) + 0x28
   at Microsoft.Extensions.Http.LoggingHttpMessageHandlerBuilderFilter.<>c__DisplayClass6_0.<Configure>b__0(HttpMessageHandlerBuilder) + 0x30
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String) + 0x258\n   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode) + 0x50
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue() + 0xdc
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String) + 0x58
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String) + 0x2c
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.AddTransientHelper[TClient](IServiceProvider, IHttpClientBuilder) + 0x3c\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite, RuntimeResolverContext) + 0x1c
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite, RuntimeResolverContext) + 0x20
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument) + 0x154
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext) + 0x88
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite, RuntimeResolverContext) + 0x20
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument) + 0x154
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite, ServiceProviderEngineScope) + 0x34
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier, ServiceProviderEngineScope) + 0x344
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider, Type) + 0xc8
   at MartinCostello.LondonTravel.Skill.IntentFactory.Create(Intent) + 0x278
   at MartinCostello.LondonTravel.Skill.AlexaSkill.<OnIntentAsync>d__5.MoveNext() + 0x38
--- End of stack trace from previous location ---
   at MartinCostello.LondonTravel.Skill.FunctionHandler.<HandleRequestAsync>d__4.MoveNext() + 0x198
```

It could be that this is a trimmer issue (or something wrong in my code that wasn't wrong before), but as the `Microsoft.Extensions.Http.Resilience.Internal.HttpKey` type is defined in this repo and removing the call to `AddStandardResilienceHandler()` (see https://github.com/martincostello/alexa-london-travel/pull/1053/commits/e3e7de16d9e94d370e1baecdbc5bf99419d6ae5c) fixes the issue, I figured this was the best first port of call.

### Reproduction Steps

~~I'll try and create a branch with an easy-to-execute local repro later, but the code with the issue is at this commit: https://github.com/martincostello/alexa-london-travel/pull/1053/commits/50eb0a279f3a55d45c0cfc5b5472834e6a221e3b.~~

~~1. Clone https://github.com/martincostello/alexa-london-travel/pull/1157/commits/75e5c8b6e8db1e61f6622199cd4f2167fe8adaf5~~
~~2. Run `build.ps1` in the root directory of the repository.~~

1. Clone https://github.com/martincostello/dotnet-extensions-5062-repro
2. Run the following commands from the root of the repository:
   ```bash
   dotnet publish
   ./artifacts/publish/dotnet-extensions-5062-repro/release/repro
    ```

### Expected behavior

`HttpClient` requests using resilience are correctly resolved from DI and work as expected.

### Actual behavior

A `MissingMethodException` is thrown from here:

https://github.com/dotnet/extensions/blob/16b40667278d24a23af0c839f4c277499b3fee19/src/Libraries/Microsoft.Extensions.Http.Resilience/Resilience/ResilienceHttpClientBuilderExtensions.Resilience.cs#L80

### Regression?

From .NET 8, yes.

### Known Workarounds

None.

### Configuration

- .NET SDK `9.0.100-preview.2.24157.14`
- Microsoft.Extensions.Http.Resilience `9.0.0-preview.2.24157.4`

### Other information

_No response_

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #105034.

Before this PR, whenever we had a generic instance `Foo<SomeType, OtherType<SomeOtherType>>` and we had a constructed `MethodTable` for this (i.e. `MethodTable` that is suitable to be used for types on the GC heap), we'd still try to optimize out the `MethodTable`s for `SomeType`, `OtherType<SomeOtherType>` into the "unconstructed" form (i.e. without a GCDesc or vtable).

This is generally a safe optimization - if `Foo<,>` actually had a `typeof(T)` somewhere, we'd upgrade the unconstructed forms into constructed forms, for example.

One place where the unconstructed types can be obtained is when reflection-inspecting such instantiation - asking for `GetGenericArguments` of a type could produce things that have unconstructed `MethodTable`s in them. In general, this is also fine - one can't do much reflection with these and asking for e.g. names would still work fine. Trying to access members or activating something obtained from `GetGenericArguments` would trigger trimming warnings, so that's also fine.

Enter Microsoft.Extension.DependencyInjection and a trimming warning suppression in there.

DI has support for something called `IOption<T>` where the T is annotated with DAM attributes. Then there's another type (`OptionFactory<T>`? Can't be bothered to look at that again.) that has the T annotated the same way. Then there's some code that will deconstruct the `IOption` instance that we saw statically, and `MakeGenericType` an `OptionFactory` with its generic arguments. The warnings on MakeGenericType are suppressed on account of: T is annotated the same, and T is not a valuetype.

The suppression _sounds_ reasonable. It just doesn't hold right now, since nothing accesses the T in IOption and we're therefore left with the unconstructed form of the T. The OptionFactory though accesses the T and tries to activate it.

This is especially a problem if IOption is instantiated over a generic type that is instantiated over a valuetype. We know we need to keep the ctor due to the annotation, but not on unconstructed forms of the type.

I was struggling with how to fix this. The easiest fix is to just stop optimizing things into unconstructed forms. This is a size regression.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
# Size statistics

Pull request dotnet/runtime#105133

| Project | Size before | Size after | Difference |
|---------|-------------|------------|------------|
| avalonia.app-linux | [ 24639504 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718376686) | [ 24661200 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718376340) | 21696 |
| avalonia.app-windows | [ 22122496 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718385816) | [ 22139904 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718383869) | 17408 |
| hello-linux | [ 1352384 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718373180) | [ 1360672 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718373202) | 8288 |
| hello-minimal-linux | [ 1077864 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718373148) | [ 1086136 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718373207) | 8272 |
| hello-minimal-windows | [ 858624 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718381381) | [ 864768 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718383041) | 6144 |
| hello-windows | [ 1105408 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718382744) | [ 1112576 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718380926) | 7168 |
| kestrel-minimal-linux | [ 5583712 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718373956) | [ 5609680 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718373743) | 25968 |
| kestrel-minimal-windows | [ 4929536 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718382568) | [ 4949504 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718384984) | 19968 |
| reflection-linux | [ 2228144 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718373160) | [ 2252928 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718373246) | 24784 |
| reflection-windows | [ 1885184 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718382338) | [ 1898496 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718385570) | 13312 |
| webapiaot-linux | [ 10230400 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718374271) | [ 10255136 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718374599) | 24736 |
| webapiaot-windows | [ 9161728 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718382499) | [ 9183232 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718385574) | 21504 |
| winrt-component-full-windows | [ 5515776 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718386791) | [ 5520896 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718387219) | 5120 |
| winrt-component-minimal-windows | [ 1833984 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718384902) | [ 1847808 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10005290278/artifacts/1718385847) | 13824 |

**Review by jkotas — APPROVED** [review]
Sigh

**Comment by MichalStrehovsky** [comment]
> Sigh

Hmm, maybe we can restrict it to types that have DAM-annotations somewhere on the generic parameters? It still fixes the DI suppression case and I can't think of other holes right now. The extra code doesn't look too terrible and I'll run rt-sz to check how much that improves things.

**Comment by MichalStrehovsky** [comment]
Looks better like this and the code is not much more complicated:

# Size statistics

Pull request dotnet/runtime#105133

| Project | Size before | Size after | Difference |
|---------|-------------|------------|------------|
| avalonia.app-linux | [ 24706016 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744718836) | [ 24706048 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744719170) | 32 |
| avalonia.app-windows | [ 22172672 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744732760) | [ 22174208 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744728422) | 1536 |
| hello-linux | [ 1344176 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744715901) | [ 1344176 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744716076) | 0 |
| hello-minimal-linux | [ 1073752 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744716690) | [ 1073752 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744716017) | 0 |
| hello-minimal-windows | [ 856576 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744724264) | [ 856576 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744731253) | 0 |
| hello-windows | [ 1102848 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744730742) | [ 1103360 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744724184) | 512 |
| kestrel-minimal-linux | [ 5629104 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744717413) | [ 5629104 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744716857) | 0 |
| kestrel-minimal-windows | [ 4966912 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744725129) | [ 4966912 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744727155) | 0 |
| reflection-linux | [ 2075984 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744716250) | [ 2075984 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744716456) | 0 |
| reflection-windows | [ 1757184 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744726269) | [ 1757184 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744727356) | 0 |
| webapiaot-linux | [ 10237152 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744717771) | [ 10237152 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744717746) | 0 |
| webapiaot-windows | [ 9178112 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744725166) | [ 9178624 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744732241) | 512 |
| winrt-component-full-windows | [ 5506560 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744733606) | [ 5507072 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744728917) | 512 |
| winrt-component-minimal-windows | [ 1750528 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744726967) | [ 1750528 ](https://github.com/MichalStrehovsky/rt-sz/actions/runs/10114515499/artifacts/1744731021) | 0 |

**Review by jkotas — APPROVED** [review]

**Pull request merged**
