### PR TITLE
Set CMAKE_BUILD_TYPE=Checked in corehost

### LINKED ISSUE #74060: cannot open include file 'version_info.h'
Steps (windows) on a clean repo:
```
.\build.cmd Clr -c Checked
```

Build failure
```
  C:\prj\runtime\src\native\corehost\native.rc(1): fatal error RC1015: cannot open include file 'version_info.h'. 
[C:\prj\runtime\artifacts\obj\win-x64.Debug\corehost\ide\nethost\nethost.vcxproj]

```

### PR DESCRIPTION
**Pull request by am11**
FIx https://github.com/dotnet/runtime/issues/74060

### CODE REVIEW

**Comment by krwq** [comment]
@am11 isn't this by design? I believe the docs were wrong on XML. I think they just didn't get updated when we ported XML in .NET Core 1 period (since we ported docs from full framework)

**Comment by krwq** [comment]
oops, I think you linked to the wrong issue in the description so disregard my comment

**Comment by am11** [comment]
Yup, it was a wrong link, :)

@EgorBo, could you test this patch?

**Comment by EgorBo** [comment]
@am11 awesome! just checked and it works!

**Comment by am11** [comment]
Yes, I am looking into it.

**Comment by elinor-fung** [comment]
Is this just a discrepancy in where the version file gets generated (under checked since `Configuration=Checked`) versus what we add to the include path for resource files (under Debug since `CMAKE_BUILD_TYPE=Debug`)?
https://github.com/dotnet/runtime/blob/1b4be3f5c7c4be1bfe2b543c19b8aeb480dad3df/src/native/corehost/corehost.proj#L125
https://github.com/dotnet/runtime/blob/1b4be3f5c7c4be1bfe2b543c19b8aeb480dad3df/src/native/corehost/build.cmd#L77

If so, I think we should reconcile that rather than skipping the `native.rc`

**Comment by am11** [comment]
@elinor-fung we both commented at the same time. I found the rootcause why it only breaks on Windows.

**Comment by am11** [comment]
@EgorBo, @elinor-fung, this is a different fix. I haven't centrelize `-DCMAKE_BUILD_TYPE` for Windows in `eng/native/gen-buildsys.cmd` (as we have in `ng/native/gen-buildsys.sh`), because `--subset libs+mono` were running into some issues. (would be nice to work those out and get these aligned at some point to reduce disparities)

**Comment by EgorBo** [comment]
Thanks for fixing this! It would be nice if someone could review this and merge asap, thanks

**Review by elinor-fung — APPROVED** [review]

**Comment by elinor-fung** [comment]
Thanks, @am11!

**Pull request merged**
