### PR TITLE
Revert "Change IOptionsSnapshot to reuse options instances across scopes (#56271)"

### PR DESCRIPTION
**Pull request by eerhardt**
#56271 broke a scenario in ASP.NET. Reverting the change for now.

cc @NinoFloris

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
I assume the revert was done programmatically so didn't review it in depth (which is a funny thing to say for basically a one-liner :smile:). Thanks.

**Comment by eerhardt** [comment]
> I assume the revert was done programmatically so didn't review it in depth 

yes, the first commit was done with `git revert 8f5f9d049a6a98b138f88fa1d9d6a96c40c03aa7`. The 2nd commit was a hand-written test for the failing ASP.NET scenario.

**Review by davidfowl — APPROVED** [review]

**Comment by eerhardt** [comment]
Merging to make sure this gets into 6.0.

**Comment by eerhardt** [comment]
FYI - @wtgodbe - when aspnetcore gets this new build, you will need to revert the [test change you made in the last runtime update](https://github.com/dotnet/aspnetcore/pull/35138#issuecomment-899623238).

**Comment by wtgodbe** [comment]
CC @halter73 this'll come in w/ tomorrow's runtime update(s), we'll need to fix the test in all 3 branches (unless we can get it into main before 5, which might be cutting it close w/ the runtime build time + our CI time)

**Pull request merged**
