### PR TITLE
Arm AdvSimd: Rename LoadVector128xN to LoadNxVector128

### LINKED ISSUE #102340: Arm64: Rename AdvSimd/Sve Load/Store vector API names
### AdvSimd
1. Rename `LoadVector128xN` to `LoadNxVector128 `
   -  Consistent naming. See https://github.com/dotnet/runtime/issues/97831#issuecomment-1934714477
2. Rename `StoreVectorNxMAndZip` to `StoreVectorAndZip`
   - The type on which the API is operation on can be known from parameters. As such we do not need special naming for them.
3. Rename `StoreVectorNx2` to `Store`
   - Same reason as point 2) above.

### Sve
1. Rename `LoadNxVector` to `LoadNxAndUnzip`
   - The operation does the unzip, similar to how it is done in AdvSimd. Compare left side operation vs. "4th quadrant" of right side.
image

2. Rename `Store` to `StoreAndZip`
   - Same reason as point 1) above

Discussion: https://github.com/dotnet/runtime/pull/102180#discussion_r1602562814

### PR DESCRIPTION
**Pull request by a74nh**
Partially fixes #102340

### CODE REVIEW

**Comment by a74nh** [comment]
Manually confirmed `HardwareIntrinsics_Arm_ro.dll` tests still run for Load2xVector, Load3xVector, Load4xVector.

This is ready now. The mono parts haven't been tested as I don't know that code or how to test it, so needs a review from the mono team.

@kunalspathak @dotnet/arm64-contrib

**Review by fanyang-mono — APPROVED** [review]
The change to Mono looks good to me.

**Review by kunalspathak — APPROVED** [review]
coreclr changes LGTM. Thank you for doing this at short notice @a74nh!

**Comment by kunalspathak** [comment]
@fanyang-mono - which CI pipelines we should run to make sure that the code in the PR is getting tested for mono?

**Comment by fanyang-mono** [comment]
@kunalspathak There isn't a CI line currently could validate this change. I could run the tests locally.

**Comment by kunalspathak** [comment]
> @kunalspathak There isn't a CI line currently could validate this change. I could run the tests locally.

sounds good. Please confirm here once you do that and I will go ahead and merge it.

**Comment by fanyang-mono** [comment]
Tests belonging to `AdvSimd.Arm64_r.dll` passed.
```
Supported ISAs:
  AdvSimd:   True
  Aes:       True
  ArmBase:   True
  Crc32:     True
  Dp:        False
  Rdm:       False
  Sha1:      True
  Sha256:    True
  Sve:       False
  
  ...
  
  Expected: 100
Actual: 100
END EXECUTION - PASSED
```

**Pull request merged**
