### PR TITLE
[release/6.0] Deprecate ICU ucol_safeClone and support ucol_clone (backports #68847)

### PR DESCRIPTION
**Pull request by ayakael**
Backport of https://github.com/dotnet/runtime/pull/68847

### CODE REVIEW

**Comment by danmoseley** [comment]
@tarekgh

**Comment by tarekgh** [comment]
Should we close this and keep https://github.com/dotnet/runtime/pull/75294?

**Review by tarekgh — APPROVED** [review]

**Comment by steveisok** [comment]
> Should we close this and keep #75294?

Yes, I think so.

**Comment by tarekgh** [comment]
I'll let @lewing close it then.

**Pull request closed without merging**
