### PR TITLE
Reenable48001

### LINKED ISSUE #48001: MacOS-arm64 native crossgen2 build missing
When building coreclr on Apple Silicon crossgen2 is created for `x86_x64` instead of `arm64`.  The native one is missing.

- This is likely blocked on using a .NET 6 preview to build. See #47245
- This is likely related to failures in these ready2run tests
   - readytorun/multifolder/multifolder/multifolder.sh
   - readytorun/r2rdump/FrameworkTests/R2RDumpTests/R2RDumpTests.sh
   - readytorun/crossgen2/crossgen2smoke/crossgen2smoke.sh

### PR DESCRIPTION
**Pull request by sdmaclea**
Remove disables from Apple Silicon that are not Apple Silicon specific.
Reenable crossgen2 tests

Fixes #48001

### CODE REVIEW

**Comment by mangod9** [comment]
@AntonLapounov fyi..

**Review by hoyosjs — APPROVED** [review]
If these pass, lgtm

**Comment by sdmaclea** [comment]
Apple Silicon passed

**Pull request merged**
