### PR TITLE
Don't force `TieredCompilation=0` for SuperPMI replay job

### PR DESCRIPTION
**Pull request by BruceForstall**
Use whatever flags already are baked into the SuperPMI collection.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@AndyAyersMS @kunalspathak PTAL
cc @dotnet/jit-contrib

**Review by jakobbotsch — APPROVED** [review]

**Comment by BruceForstall** [comment]
Let me write down a little justification: I presume that `TieredCompilation=0` was forced because most of the variations during replay are with JitStress modes, and running JitStress in unoptimized code won't do anything interesting. The reason to not force `TieredCompilation=0` is because setting it is likely to cause MISSING data due to additional JIT-EE interface queries for which the SPMI collection has no data. Also, I'm worried it will cause us to not properly replay all the Tier-0 and OSR methods we have in collections now.

**Comment by AndyAyersMS** [comment]
I'm puzzled why this matters --the jit doesn't know about `COMPlus_TieredCompilation`. It is a runtime config setting.

**Pull request merged**
