### PR TITLE
XML signing - allow override of default transforms

### LINKED ISSUE #2102: XML signing: no way to override default transforms
In .NET Framework it was possible to override default transforms. In .NET Core it is not due to this line:

https://github.com/dotnet/runtime/blob/653cf01273242935f85290a131ccf7dc966e9d37/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/CryptoHelpers.cs#L58

See code in [.NET Framework](https://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/utils.cs,461).

This breaks our application as we need our own implementation of `XmlDsigXPathTransform`.

### PR DESCRIPTION
**Pull request by espenrl**
Fixes #2102.

### CODE REVIEW

**Comment by bartonjs** [comment]
We should go ahead and remove all of the entries from CreateFromKnownName that are also registered by default in CryptoConfig, since they're now all dead code.

**Comment by espenrl** [comment]
I will happy to do that. Though it exceeds my capability to properly test that such a change will not affect the world of .NET.

**Comment by krwq** [comment]
@espenrl what you can do is copy all the keys from https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Security.Cryptography.Xml/src/System/Security/Cryptography/Xml/CryptoHelpers.cs#L16 put them into array and call CryptoConfig.CreateFromName and when it returns not null then remove it from there, i.e.:

```csharp
    string[] keys = new string[] {
      "http://www.w3.org/TR/2001/REC-xml-c14n-20010315",
      "http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments",
      "http://www.w3.org/2001/10/xml-exc-c14n#",
      "http://www.w3.org/2001/10/xml-exc-c14n#WithComments",
      "http://www.w3.org/2000/09/xmldsig#base64",
      "http://www.w3.org/TR/1999/REC-xpath-19991116",
      "http://www.w3.org/TR/1999/REC-xslt-19991116",
      "http://www.w3.org/2000/09/xmldsig#enveloped-signature",
      "http://www.w3.org/2002/07/decrypt#XML",
      "urn:mpeg:mpeg21:2003:01-REL-R-NS:licenseTransform",
      "http://www.w3.org/2000/09/xmldsig# X509Data",
      "http://www.w3.org/2000/09/xmldsig# KeyName",
      "http://www.w3.org/2000/09/xmldsig# KeyValue/DSAKeyValue",
      "http://www.w3.org/2000/09/xmldsig# KeyValue/RSAKeyValue",
      "http://www.w3.org/2000/09/xmldsig# RetrievalMethod",
      "http://www.w3.org/2001/04/xmlenc# EncryptedKey",
      "http://www.w3.org/2000/09/xmldsig#dsa-sha1",
      "System.Security.Cryptography.DSASignatureDescription",
      "http://www.w3.org/2000/09/xmldsig#rsa-sha1",
      "System.Security.Cryptography.RSASignatureDescription",
      "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
      "http://www.w3.org/2001/04/xmldsig-more#rsa-sha384",
      "http://www.w3.org/2001/04/xmldsig-more#rsa-sha512",
      "http://www.w3.org/2000/09/xmldsig#sha1",
      "MD5",
      "http://www.w3.org/2001/04/xmldsig-more#hmac-md5",
      "http://www.w3.org/2001/04/xmlenc#tripledes-cbc",
    };

    foreach (var k in keys)
    {
      if (CryptoConfig.CreateFromName(k) != null)
      {
        Console.WriteLine(k);
      }
    }
```

and then remove everything printed from the file (assuming the place you are changing is the only call to CreateFromKnownName)

**Comment by espenrl** [comment]
Thanks for the guidance @krwq. I will find time to do it next week.

**Comment by stephentoub** [comment]
@espenrl, still working on this?  Thanks.

**Comment by krwq** [comment]
@espenrl do you think you'll have time to finish this up? seems updating the list is all what's left here

**Comment by vcsjones** [comment]
@espenrl Hello! Anything I can do to help? If you don't think you'll have time to finish, I'd be happy to assist and carry this over the finish line.

**Comment by bartonjs** [comment]
Accepting this merge since the second half (#38394) is ready to go.

**Review by bartonjs — APPROVED** [review]
Approved with the "part 2" that's already ready to go.

**Pull request merged**
