### PR TITLE
Enable in-build signing based on branch

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
Will need a backport to preview1.

**Review by carlossanlop — APPROVED** [review]
Assuming nothing breaks, LGTM.
Do you want to start the backport so the CI runs in parallel? `/backport to release/8.0-preview1`

**Review by rbhanda — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]

**Comment by carlossanlop** [comment]
From chat: PR testing isn't likely to cover any infra signing, so we can just merge this.

**Pull request merged**
