### PR TITLE
Workloads test: Install the current app.ref pack also

### LINKED ISSUE #93387: [browser][WBT] SatelliteLoadingTests.LoadSatelliteAssembly - ActiveIssue
Unit test `LoadSatelliteAssembly` is sensitive to bug of duplicate result marshaling which was fixed in https://github.com/dotnet/runtime/pull/92403

This active issue could be removed from code and closed after the [fix](https://github.com/dotnet/runtime/pull/92403) flows into WBT

### PR DESCRIPTION
**Pull request by radical**
Re-enable updating the targeting pack as the workload is correctly using
9.0 artifacts. The targeting pack update is needed because it includes
the locally built analyzers, like the source generators for
`JSImport/Export`.

This fixes `SatelliteLoadingTests.LoadSatelliteAssembly`.

Fixes: https://github.com/dotnet/runtime/issues/93387

### CODE REVIEW

**Review by pavelsavara — APPROVED** [review]

**Comment by radical** [comment]
The failures are unrelated:
- https://github.com/dotnet/runtime/issues/93583
- https://github.com/dotnet/runtime/issues/93522

**Comment by radical** [comment]
I will wait for https://github.com/dotnet/runtime/pull/93066 which updates the SDK used for testing, then test this PR again, before merging.

**Comment by radical** [comment]
https://github.com/dotnet/runtime/pull/93625 would be the preferable fix.

**Comment by lewing** [comment]
fixed in #93625

**Pull request closed without merging**
