### PR TITLE
[wasm][debugger] Try to enable debugger tests

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
The first commit is useful by itself too.

**Comment by lewing** [comment]
@radical I resolved the conflict here but there still seems to be issues?

**Comment by radical** [comment]
Yep, looking into that.

**Comment by lewing** [comment]
@radical the debugger project changes are in, should we update this or close it?  I'm not clear where we are with running the debugger tests in CI

**Comment by radical** [comment]
Yeah, we can close this. I should have a PR for running the tests on CI next week.

**Pull request closed without merging**
