### PR TITLE
unblock inlining of generics with static fields

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Contributes to #108913

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@MihuBot

**Comment by AndyAyersMS** [comment]
@EgorBo FYI -- this seems to just work now (perhaps because of the work you did on inlining shared generics). Not surprisingly it leads to size increases, but the diffs don't look too bad.

**Comment by AndyAyersMS** [comment]
SPMI won't show the impact of this, since the JIT will be making new interface calls.

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL
cc @dotnet/jit-contrib

**Comment by EgorBo** [comment]
> @EgorBo FYI -- this seems to just work now (perhaps because of the work you did on inlining shared generics). Not surprisingly it leads to size increases, but the diffs don't look too bad.

Right, it explains why we still have to keep CORINFO_FIELD_STATIC_READYTORUN_HELPER, there were NAOT/R2R cases we couldn't inline them.

**Review by EgorBo — APPROVED** [review]

**Pull request merged**
