### PR TITLE
LSRA: PreferCalleeSave for non-localVar intervals

### PR DESCRIPTION
**Pull request by kunalspathak**
Idea from https://github.com/dotnet/runtime/pull/76904, but just with lower TP cost.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Is this different from #81242?

**Comment by kunalspathak** [comment]
> Is this different from #81242?

Didn't realize you had this already. Wondering why this was not merged. The idea is essentially same, but the way I was doing it in https://github.com/dotnet/runtime/pull/76904 was TP heavy, so this should have lower TP impact. Compared to what you are doing, we might over mark `preferCalleeSave` to some intervals that has `lastUse` before the call and new definition after the call. Probably ok to not mark such intervals as `preferCalleeSave`? 

```
RefTypeDef
RefTypeUse
RefTypeUse
RefTypeKill
RefTypeKill
...
RefTypeDef
RefTypeUse
```

**Comment by jakobbotsch** [comment]
> Wondering why this was not merged.

I think I wanted to investigate why this was a problem for floats but not for integer intervals, but I never got around to doing that. It's sort of odd that even without this preferencing we can allocate integer intervals without hitting the issue. Also IIRC the diffs were somewhat mixed.

This fix seems fine to me too, but the nice part about doing it from `buildKillPositionsForNode` is that we handle the local intervals and the LIR temp intervals from the same place. Not sure which one is best TP wise, though.

**Comment by kunalspathak** [comment]
The results are mixed, and for some collection worse. There is around 0.5% regression in TP. 

image

The approach I am taking here is if an interval ever interferes with call, I am marking it as `preferCalleeSave` (which is too aggressive)  vs. what @jakobbotsch is doing in https://github.com/dotnet/runtime/pull/81242 to just mark intervals whose definition is before call and use is after the call (LIR temps). I looked at the regressions and they are mostly coming from the extra prolog/epilog save restore of callee-save registers because they are preferred more now. We might see benefits of eliminating the memory access from the inner blocks from this and move that cost to prolog/epilog.

image

I tried something in the middle, where we mark those intervals to be `preferCalleeSave` whose def (and zero or more uses) is before the call and `lastUse` is after the call. That too gives mixed results, where the regressions are mostly from prolog/epilog save/restore.

**Pull request closed without merging**
