### PR TITLE
Revert "Kill REG_PROFILER_RET_SCRATCH (#37679)"

### PR DESCRIPTION
**Pull request by AndyAyersMS**
This reverts commit b179e198403adbfbf275a40741cef7b252cda186.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Undoing change that I think might have lead to gc stress failures; see #38230 and #36971.

**Comment by AndyAyersMS** [comment]
Most of the stress runs are done (and all the linux arm ones) -- there are about 30 failures on linux arm amd ~100 total failures.

Arm linux failures are mostly in various HW Intrinsics tests. So it seems the change I've reverted above is the root cause for the spike in failures.

@BruceForstall @CarolEidt -- Seems like we should revert #37679.

**Comment by BruceForstall** [comment]
Agreed, although https://github.com/dotnet/runtime/issues/37223 will regress and will need a different fix. It's optional that you'd want to disable the test there that will regress.

**Comment by AndyAyersMS** [comment]
What's the mechanism for excluding a libraries test?

**Comment by BruceForstall** [comment]
E.g.,

https://github.com/BruceForstall/runtime/blob/95d9bdb3a4f250b9335035cad28ca6eb32766844/src/libraries/System.Numerics.Vectors/tests/Matrix3x2Tests.cs#L689
```
[SkipOnCoreClr("https://github.com/dotnet/runtime/issues/36587", RuntimeTestModes.JitStress)]
```

or, e.g., https://github.com/dotnet/runtime/pull/38580

**Comment by CarolEidt** [comment]
Can you articulate why reverting this change eliminates the issue? Codegen still uses r2, I believe, and it is codegen, not LSRA, that tracks the GC state.

**Comment by AndyAyersMS** [comment]
There are special tricks to extend gc liveness of `r0` around the late profile hook and they won't work right if the return value is temporarily elsewhere. I'll add more details when I have a chance (might be a few days).

**Comment by AndyAyersMS** [comment]
@BruceForstall looks like we didn't specify which test hit this assert, so I don't know what to disable. It might affect more than one test. @CarolEidt do you recall?

**Comment by CarolEidt** [comment]
@AndyAyersMS - were you asking about which test hit the assert that I fixed with #37679? The issue was #37223 and it failed in `System.Threading.Tasks.Dataflow.Tests`, though it doesn't directly fail in any of the tests themselves, and I don't recall if I was able to narrow it down to a class or method within those tests.

**Comment by AndyAyersMS** [comment]
@CarolEidt thanks -- the method was `Dictionary.Remove` so not surprising if it ends up impacting more than one test or in the harness itself.

Let me see if the failure still repros and if so we can figure out whether to exclude it here or do something else.

**Comment by AndyAyersMS** [comment]
Hmm, can't get CI to run. Let me close this an open a new PR.

**Pull request closed without merging**
