### PR TITLE
[wasm] Use latest stable version of chrome for testing

### PR DESCRIPTION
**Pull request by radical**
* Use the latest `stable` chrome version by default
* Install these by default on codespaces

## Details

- Added a new task `GetChromeVersions` to get the latest version
- This is applicable to library tests, debugger tests, and Wasm.Build.Tests
- The channel used for getting the "latest" version is `$(ChromeChannel)=stable`
- And they are installed in `artifacts/bin/chrome`, and `artifacts/bin/chromedriver`
- A newer version is fetched only `$(ChromeVersionCheckThresholdDays)=3` days after the last version check
- This is enabled by default on containers
- And the behavior can be disabled with `$(InstallChromeForTests)=false`.

### CODE REVIEW

**Comment by radical** [comment]
@halter73 Why was the `arch-wasm` label removed on this PR?

**Comment by radical** [comment]
Failures are unrelated.

**Review by maraf — APPROVED** [review]
LGTM

**Pull request merged**
