### PR TITLE
Reduce the memory footprint of ManagedWebSocket

### PR DESCRIPTION
**Pull request by zlatanov**
While working on the websocket compression I noticed two things but decided to leave them after the feature was completed:

1. There was a static readonly instance of `RandomNumberGenerator`, which could be replaced with `RandomNumberGenerator.Fill`.
2. The `ManagedWebSocket` class was creating `CancellationTokenSource` but never really used the cancellation part. Since continuations from `CancellationTokenSource.Cancel` are executed synchronously, the cancellation source could be replaced with a method.

This reduced the memory footprint of a websocket without compression enabled from **752** bytes to **552** bytes.

//cc @CarnaViire @scalablecory

### CODE REVIEW

**Review by MihaZupan — APPROVED** [review]
LGTM, I see no reason why we'd want to use a CTS here

**Comment by CarnaViire** [comment]
FYI: CI failures are ongoing infra issue. I will rerun checks after it's fixed

**Comment by zlatanov** [comment]
@CarnaViire the failing tests seem unrelated. Let me know if anything else is needed.

**Comment by CarnaViire** [comment]
@zlatanov sorry for delaying on the rerun 😔 I've triggered it now
As I understood it, because of the CI issue on Thursday-Friday, it didn't run the whole Browser wasm testing step, so I believe it's better to wait for it to complete. Hopefully it'll be green so I'll merge it afterwards 🙂

**Pull request merged**
