### PR TITLE
Fix double-negatives with MatchCharacterClass

### LINKED ISSUE #62622: Regex source generator could produce better negated conditions in some cases
This is purely a readability issue; it currently has no impact on performance.

The attribute:
```C#
[RegexGenerator(@"\D\D\D")]
```
will end up generating code like the following:
```C#
                    // Match a character in the set [\P{Nd}] exactly 3 times.
                    {
                        if ((uint)slice.Length < 3 ||
                            !!char.IsDigit(slice[0]) ||
                            !!char.IsDigit(slice[1]) ||
                            !!char.IsDigit(slice[2]))
                        {
                            goto NoMatch;
                        }
                    }
```
That double `!!` comes about because the call site is just emitting a `!` before the string representing the condition, and the function generating the condition is negating the result of `char.IsDigit` because the category is negated.

We should be able to avoid this by passing into the function that produces the condition clause whether the negated condition is required instead.  That will help with this issue as well as other slightly less-than-ideal coding patterns, like:
```C#
[RegexGenerator(@"[1-9][1-9][1-9]")]
```
producing:
```C#
                    // Match a character in the set [1-9] exactly 3 times.
                    {
                        if ((uint)slice.Length < 3 ||
                            !(((uint)slice[0]) - '1' <= (uint)('9' - '1')) ||
                            !(((uint)slice[1]) - '1' <= (uint)('9' - '1')) ||
                            !(((uint)slice[2]) - '1' <= (uint)('9' - '1')))
                        {
                            goto NoMatch;
                        }
                    }
```
It'd be nicer if that produced:
```C#
                    // Match a character in the set [1-9] exactly 3 times.
                    {
                        if ((uint)slice.Length < 3 ||
                            (((uint)slice[0]) - '1' > (uint)('9' - '1')) ||
                            (((uint)slice[1]) - '1' > (uint)('9' - '1')) ||
                            (((uint)slice[2]) - '1' > (uint)('9' - '1')))
                        {
                            goto NoMatch;
                        }
                    }
```

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/62622
cc: @joperezr

### CODE REVIEW

**Review by joperezr — APPROVED** [review]
LGTM, generated code does look much better.

Separate comment: even though I know the purpose of this is purely for readability purposes (therefore not very applicable to `Compiled`) would it make sense to make the changes in MatchCharacterClass on Compiled engine as well just for consistency purposes?

**Comment by joperezr** [comment]
BTW it's been a bit since I last saw that many XORs in C# 😄

**Comment by stephentoub** [comment]
> BTW it's been a bit since I last saw that many XORs in C#

If you need it, flaunt it :smile:

> Separate comment: even though I know the purpose of this is purely for readability purposes (therefore not very applicable to Compiled) would it make sense to make the changes in MatchCharacterClass on Compiled engine as well just for consistency purposes?

Sure, I can make that change.

**Comment by stephentoub** [comment]
>> Separate comment: even though I know the purpose of this is purely for readability purposes (therefore not very applicable to Compiled) would it make sense to make the changes in MatchCharacterClass on Compiled engine as well just for consistency purposes?

> Sure, I can make that change.

Actually, I took a look at it, and best case it saves us a single ceq operation, while adding additional complexity.  This particular function is one with a signature that already differs from what's in RegexCompiled, e.g. to be able to pass out additional declarations, so I don't think this really hampers the consistency much, and I'd prefer not to augment RegexCompiler with it.

**Pull request merged**
