### PR TITLE
Added System.TestStructs.dll to the list of excluded assemblies in CORE_ROOT

### PR DESCRIPTION
**Pull request by briansull**

### CODE REVIEW

**Comment by ericstj** [comment]
This won't be the only dependency from that assembly.  It also uses Xunit.  I'll have a different PR to fix this.

**Comment by ericstj** [comment]
https://github.com/dotnet/runtime/pull/49067

**Comment by BruceForstall** [comment]
btw, this problem affects all R2R coreclr test runs, including our top-level CI "outerloop" job : https://dev.azure.com/dnceng/public/_build?definitionId=655&_a=summary

**Comment by ericstj** [comment]
@BruceForstall please see https://github.com/dotnet/runtime/pull/49067 which may be the better fix.   Also would help to have others comment on discussion here: https://github.com/dotnet/runtime/pull/48858

**Comment by briansull** [comment]
This change is inherently safe as it just adds the name System.TestStructs.dll to the list of assemblies that we don't try to compile. It doesn't matter if that assembly  it exists or doesn't exist.

Your change talks about not binplacing another assembly: DependencyInjection.Specification.Tests

**Comment by ericstj** [comment]
True, but I don’t think that’s the problem that broke the build. I believe the build was broken due to this assembly being absent. I fixed that by removing the assembly that references this one from the build directory being crossgen’ed.

**Comment by briansull** [comment]
Closing this PR

**Pull request closed without merging**
