### PR TITLE
[WASM] Fix async/await in config loading

### LINKED ISSUE #54643: [wasm] `Uncaught TypeError: Cannot set property 'loaded_cb' of null`
Example failure:

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-53603-merge-6de2ebd21d9742fbb7/System.Formats.Asn1.Tests/console.bb96e0e6.log?sv=2019-07-07&se=2021-07-13T18%3A47%3A03Z&sr=c&sp=rl&sig=36IYks3qOtQFUosFFMbRsam3qAdumj%2Fj1yZSpK%2BAqHU%3D

It fails like this:
```
XHarness command issued: wasm test-browser --app=. --output-directory=/datadisks/disk1/work/BD940A69/w/AFF709B2/uploads/xharness-output --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js -- --run WasmTestRunner.dll System.Formats.Asn1.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
[19:00:39] info: Starting chromedriver with args: --headless --incognito --enable-features=NetworkService,NetworkServiceInProcess --allow-insecure-localhost --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-component-extensions-with-background-pages --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only
Starting ChromeDriver 84.0.4147.0 (ff714bcb10c3356b1b1b2819148507a34fa4b1f8-refs/heads/master@{#768968}) on port 33549
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[19:00:40] info: browser: Console websocket connected.
[19:00:41] info: Arguments: --run,WasmTestRunner.dll,System.Formats.Asn1.Tests.dll,-notrait,category=IgnoreForCI,-notrait,category=OuterLoop,-notrait,category=failing
[19:00:41] fail: [out of order message from the browser]: http://127.0.0.1:37793/runtime.js 234:26 Uncaught TypeError: Cannot set property 'loaded_cb' of null
[19:15:40] fail: Application has finished with exit code TIMED_OUT but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
```

### PR DESCRIPTION
**Pull request by Daniel-Genkin**
Fixed the async loading of mono-config.json to fix issue #54643

### CODE REVIEW

**Comment by lewing** [comment]
I think we should figure out why addRunDependency is failing here blazor uses it successfully from Module.preRun in multiple places
https://github.com/dotnet/aspnetcore/blob/4dc663a0d46467908f5463d5004b0ae574648f4a/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L561

**Comment by kg** [comment]
> 
> 
> I think we should figure out why addRunDependency is failing here blazor uses it successfully from Module.preRun in multiple places
> https://github.com/dotnet/aspnetcore/blob/4dc663a0d46467908f5463d5004b0ae574648f4a/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L561

My guess would be that as I suggested in comments on the earlier PR, because removeRunDependency instantly invokes the callback once it's ready, the async function hasn't returned yet so the config has not been stored in the appropriate place by the time the other code looks for it (that won't happen until the next turn of the event loop)

**Comment by lewing** [comment]
> > I think we should figure out why addRunDependency is failing here blazor uses it successfully from Module.preRun in multiple places
> > https://github.com/dotnet/aspnetcore/blob/4dc663a0d46467908f5463d5004b0ae574648f4a/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L561
> 
> My guess would be that as I suggested in comments on the earlier PR, because removeRunDependency instantly invokes the callback once it's ready, the async function hasn't returned yet so the config has not been stored in the appropriate place by the time the other code looks for it (that won't happen until the next turn of the event loop)

yeah, I think we can follow the pattern of returning a promise and awaiting that when setting the config (like blazor does)

**Comment by lambdageek** [comment]
There's now a (logical) conflict with https://github.com/dotnet/runtime/pull/54568 which added a new HotReload functional test - which at the moment has the async runtime.js stuff.   (But see #54622 - the last commit there sets things up for the old-style mono-config.js)

**Comment by Daniel-Genkin** [comment]
This latest push undoes the previous 4 commits and reverts the async/await. However (thanks to Larry) this also seems to work

**Review by lewing — COMMENTED** [review]
Needs to fix the hot reload test as well

**Comment by kg** [comment]
This new solution looks good to me

**Review by radekdoulik — COMMENTED** [review]
LGTM. It just needs to wait for https://github.com/dotnet/runtime/pull/54622 or cherry-pick the https://github.com/dotnet/runtime/pull/54622/commits/15fc697d7e89a51dee188a37b483ec7a0b2351aa

**Comment by lambdageek** [comment]
> LGTM. It just needs to wait for #54622 or cherry-pick the [15fc697](https://github.com/dotnet/runtime/commit/15fc697d7e89a51dee188a37b483ec7a0b2351aa)

This PR doesn't need to wait for 54622 (that PR is on the preview6 branch, not main) - looks like Daniel picked up the new test from main and updated it the same as the othre functional tests.  Thanks Daniel!

**Comment by Daniel-Genkin** [comment]
> > LGTM. It just needs to wait for #54622 or cherry-pick the [15fc697](https://github.com/dotnet/runtime/commit/15fc697d7e89a51dee188a37b483ec7a0b2351aa)
> 
> This PR doesn't need to wait for 54622 (that PR is on the preview6 branch, not main) - looks like Daniel picked up the new test from main and updated it the same as the othre functional tests. Thanks Daniel!

Yes that's exactly what I did haha :)

**Review by lewing — APPROVED** [review]

**Review by radekdoulik — APPROVED** [review]

**Comment by lewing** [comment]
Test failures look infrastructure related and this issue is causing CI instability.

**Pull request merged**
