### PR TITLE
[LoongArch64] ELT profiler: fix reconstruction of struct args passed partially on the stack.

### PR DESCRIPTION
**Pull request by LuckyXu-HF**
[LoongArch64] ELT profiler: fix reconstruction of struct args passed partially on the stack.
* Fix the `DoubleManyMixedStructFunc` case in slowpatheltenter.sh.

### CODE REVIEW

**Comment by LuckyXu-HF** [comment]
Fix the `DoubleManyMixedStructFunc` case in `profiler/elt/slowpatheltenter/slowpatheltenter.sh` which is added by https://github.com/dotnet/runtime/pull/91797 .

Error result:
```
BEGIN EXECUTION
/data_loongson/xuliangyu/fork/runtime/artifacts/tests/coreclr/linux.loongarch64.Debug/Tests/Core_Root///corerun -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true slowpatheltenter.dll ''
Profiler path: /data_loongson/xuliangyu/fork/runtime/artifacts/tests/coreclr/linux.loongarch64.Debug/profiler/elt/slowpatheltenter/libProfiler.so
Profilee STDOUT: Profiler.dll!DllGetClassObject
Profilee STDOUT: Profiler.dll!Profiler::Initialize
Profilee STDOUT: Testing enter hooks
Profilee STDOUT: x=-123 y=-4.3 str=Hello, test!
Profilee STDOUT: SimpleArgsFunc returned Hello from SimpleArgsFunc!
Profilee STDOUT: ss=x=1 d=1
Profilee STDOUT: MixedStructFunc returned x=4 d=1
Profilee STDOUT: ls=x0=0 d0=0 x1=1 d1=1 x2=2 d2=2 x3=3 d3=3
Profilee STDOUT: LargeStructFunc returned 3
Profilee STDOUT: IntegerStructFunc returned x=21 y=256
Profilee STDOUT: Fp32x2StructFunc returned x=1.2 y=2
Profilee STDOUT: Fp32x2StructFp32x3StructFunc returned x=6.7 y=10.11 z=13.14
Profilee STDOUT: Fp32x3StructFunc returned x=6.7 y=10.11 z=3
Profilee STDOUT: Fp32x3StructFp32x2StructFunc returned x=1.2 y=3.5
Profilee STDOUT: Fp32x3StructSingleFp32x3StructSingleFunc returned x=6.7 y=10.11 z=13.14
Profilee STDOUT: Fp32x4StructFunc returned x=15.17 y=19.21 z=22.23 w=4
Profilee STDOUT: Fp32x4StructFp32x4StructFunc returned x=15.17 y=19.21 z=22.23 w=26.29
Profilee STDOUT: Fp64x2StructFunc returned x=1.2 y=2
Profilee STDOUT: Fp64x2StructFp64x3StructFunc returned x=6.7 y=10.11 z=13.14
Profilee STDOUT: Fp64x3StructFunc returned x=6.7 y=10.11 z=3
Profilee STDOUT: Fp64x3StructFp64x2StructFunc returned x=1.2 y=3.5
Profilee STDOUT: Fp64x3StructDoubleFp64x3StructDoubleFunc returned x=6.7 y=10.11 z=13.14
Profilee STDOUT: Fp64x4StructFunc returned x=15.17 y=19.21 z=22.23 w=4
Profilee STDOUT: Fp64x4StructFp64x4StructFunc returned x=15.17 y=19.21 z=22.23 w=26.29
Profilee STDOUT: DoubleRetFunc returned 13
Profilee STDOUT: FloatRetFunc returned 13
Profilee STDOUT: IntegerSseStructFunc returned x=1 y=2 z=3.5
Profilee STDOUT: SseIntegerStructFunc returned x=1.2 y=3.5 z=6
Profilee STDOUT: MixedSseStructFunc returned x=1.2 y=3 z=5.6 w=7.1
Profilee STDOUT: SseMixedStructFunc returned x=1.2 y=3.5 z=6 w=7.1
Profilee STDOUT: MixedMixedStructFunc returned x=1.2 y=3 z=5 w=6.7
Profilee STDOUT: i=11 s1=(x=1 d=1) s2=(x=2 d=2) s3=(x=3 d=3) s4=(x=4 d=4) s5=(x=5 d=5) s6=(x=6 d=6) s7=(x=7 d=7) s8=(x=8 d=8) s9=(x=9 d=9)
Profilee STDOUT: IntManyMixedStructFunc returned x=1 d=1
Profilee STDOUT: Argument 8 for function DoubleManyMixedStructFunc did not match.
Profilee STDOUT: Expected bytes: 08000000 00000000 00000000 00002040 
Profilee STDOUT: Actual bytes  : 08000000 00000000 00000000 00002640 
Profilee STDOUT: d=11 s1=(x=1 d=1) s2=(x=2 d=2) s3=(x=3 d=3) s4=(x=4 d=4) s5=(x=5 d=5) s6=(x=6 d=6) s7=(x=7 d=7) s8=(x=8 d=8) s9=(x=9 d=9)
Profilee STDOUT: DoubleManyMixedStructFunc returned x=1 d=1
Profilee STDOUT: Profiler.dll!Profiler::Shutdown
Profilee STDOUT: TEST FAILED _failures=1
Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above. Profilee returned exit code 100.
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above. Profilee returned exit code 100.
   at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error) in /home/xuliangyu/runtime/src/tests/profiler/common/ProfilerTestRunner.cs:line 185
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies) in /home/xuliangyu/runtime/src/tests/profiler/common/ProfilerTestRunner.cs:line 131
   at SlowPathELTTests.SlowPathELTEnter.Main(String[] args) in /home/xuliangyu/runtime/src/tests/profiler/elt/slowpatheltenter.cs:line 29
/data_loongson/xuliangyu/fork/runtime/artifacts/tests/coreclr/linux.loongarch64.Debug/profiler/elt/slowpatheltenter/slowpatheltenter.sh: line 448: 16680 Aborted                 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}" 
Expected: 100
Actual: 134
END EXECUTION - FAILED
```
Fixed:
```
BEGIN EXECUTION
/data_loongson/xuliangyu/fork/runtime/artifacts/tests/coreclr/linux.loongarch64.Debug/Tests/Core_Root///corerun -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true slowpatheltenter.dll ''
Profiler path: /data_loongson/xuliangyu/fork/runtime/artifacts/tests/coreclr/linux.loongarch64.Debug/profiler/elt/slowpatheltenter/libProfiler.so
Profilee STDOUT: Profiler.dll!DllGetClassObject
Profilee STDOUT: Profiler.dll!Profiler::Initialize
Profilee STDOUT: Testing enter hooks
Profilee STDOUT: x=-123 y=-4.3 str=Hello, test!
Profilee STDOUT: SimpleArgsFunc returned Hello from SimpleArgsFunc!
Profilee STDOUT: ss=x=1 d=1
Profilee STDOUT: MixedStructFunc returned x=4 d=1
Profilee STDOUT: ls=x0=0 d0=0 x1=1 d1=1 x2=2 d2=2 x3=3 d3=3
Profilee STDOUT: LargeStructFunc returned 3
Profilee STDOUT: IntegerStructFunc returned x=21 y=256
Profilee STDOUT: Fp32x2StructFunc returned x=1.2 y=2
Profilee STDOUT: Fp32x2StructFp32x3StructFunc returned x=6.7 y=10.11 z=13.14
Profilee STDOUT: Fp32x3StructFunc returned x=6.7 y=10.11 z=3
Profilee STDOUT: Fp32x3StructFp32x2StructFunc returned x=1.2 y=3.5
Profilee STDOUT: Fp32x3StructSingleFp32x3StructSingleFunc returned x=6.7 y=10.11 z=13.14
Profilee STDOUT: Fp32x4StructFunc returned x=15.17 y=19.21 z=22.23 w=4
Profilee STDOUT: Fp32x4StructFp32x4StructFunc returned x=15.17 y=19.21 z=22.23 w=26.29
Profilee STDOUT: Fp64x2StructFunc returned x=1.2 y=2
Profilee STDOUT: Fp64x2StructFp64x3StructFunc returned x=6.7 y=10.11 z=13.14
Profilee STDOUT: Fp64x3StructFunc returned x=6.7 y=10.11 z=3
Profilee STDOUT: Fp64x3StructFp64x2StructFunc returned x=1.2 y=3.5
Profilee STDOUT: Fp64x3StructDoubleFp64x3StructDoubleFunc returned x=6.7 y=10.11 z=13.14
Profilee STDOUT: Fp64x4StructFunc returned x=15.17 y=19.21 z=22.23 w=4
Profilee STDOUT: Fp64x4StructFp64x4StructFunc returned x=15.17 y=19.21 z=22.23 w=26.29
Profilee STDOUT: DoubleRetFunc returned 13
Profilee STDOUT: FloatRetFunc returned 13
Profilee STDOUT: IntegerSseStructFunc returned x=1 y=2 z=3.5
Profilee STDOUT: SseIntegerStructFunc returned x=1.2 y=3.5 z=6
Profilee STDOUT: MixedSseStructFunc returned x=1.2 y=3 z=5.6 w=7.1
Profilee STDOUT: SseMixedStructFunc returned x=1.2 y=3.5 z=6 w=7.1
Profilee STDOUT: MixedMixedStructFunc returned x=1.2 y=3 z=5 w=6.7
Profilee STDOUT: i=11 s1=(x=1 d=1) s2=(x=2 d=2) s3=(x=3 d=3) s4=(x=4 d=4) s5=(x=5 d=5) s6=(x=6 d=6) s7=(x=7 d=7) s8=(x=8 d=8) s9=(x=9 d=9)
Profilee STDOUT: IntManyMixedStructFunc returned x=1 d=1
Profilee STDOUT: d=11 s1=(x=1 d=1) s2=(x=2 d=2) s3=(x=3 d=3) s4=(x=4 d=4) s5=(x=5 d=5) s6=(x=6 d=6) s7=(x=7 d=7) s8=(x=8 d=8) s9=(x=9 d=9)
Profilee STDOUT: DoubleManyMixedStructFunc returned x=1 d=1
Profilee STDOUT: Profiler.dll!Profiler::Shutdown
Profilee STDOUT: PROFILER TEST PASSES
Expected: 100
Actual: 100
END EXECUTION - PASSED
```

**Comment by LuckyXu-HF** [comment]
@shushanhf @jkotas could you please help to review this PR? Thanks.

**Review by shushanhf — APPROVED** [review]
LGTM
Thanks

**Review by jkotas — APPROVED** [review]
Thanks

**Pull request merged**
