### PR TITLE
Make managed `enum_flag_HasTypeEquivalence` match value in methodtable.h

### PR DESCRIPTION
**Pull request by VSadov**
By its use `enum_flag_HasTypeEquivalence` needs to match the native counterpart in methodtable.h

Currently it matches the value in typedesc.h , which happens to be different from the one in methodtable.h.

### CODE REVIEW

**Comment by VSadov** [comment]
Thanks @GrabYourPitchforks for noticing the discrepancy!!!

**Comment by jkotas** [comment]
Was this causing observable behavior difference? Do we need a test?

**Comment by VSadov** [comment]
No failures were reported due to this, just an observation while reading code. 
Considering it is type equivalence, is it something that can be easily tested in coreclr? 
(I think it was something for NoPIA on desktop, but I might be wrong about that)

**Comment by jkotas** [comment]
No PIA exists in CoreCLR as well.

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT It would be useful to understand the impact this bug on NoPIA interop. I has potential to manifest itself as a very odd bug and it may be a servicing candidate.

**Comment by VSadov** [comment]
I will try to come up with a test that demonstrates the break. 
I assume we already have NoPIA tests to use as a base?

As a simple and obvious fix with very low risk, I think it is a candidate to backport to 5.X

**Comment by AaronRobinsonMSFT** [comment]
@VSadov We have Type Equivalence tests at https://github.com/dotnet/runtime/tree/master/src/tests/baseservices/typeequivalence.

I would like to know when this was introduced.

**Comment by AaronRobinsonMSFT** [comment]
Got it. Looks like this was a port for FCalls into managed - c3dc1fdfdcca9bf504a68be565b053c0372ac73c.

**Comment by AaronRobinsonMSFT** [comment]
@jkotas and @VSadov I agree this does seem like it warrants a servicing fix. I assume we can all agree this is a hole in our testing - which I am unsure how the current tests don't find this as it seems rather fundamental.

**Comment by jkotas** [comment]
Is this check actually needed? I have tried to create a repro for the bug that this would cause, but I am not able to find the situation where this check would make a difference.

**Comment by VSadov** [comment]
That what I suspected as well for the reason we've never seen a failure from. The way the flag is used on the managed side is to bypass cache lookup, since conversions for these types should not be recorded in the cache anyways. 

As a result either false positive or false negative result would just result in unnecessary or redundant cache query.

If we can assume that type-equivalent types are rarity, we can remove the check. It would just result in unnecessary cache lookups for these types.

The flag is still incorrect though.

**Comment by jkotas** [comment]
> The way the flag is used on the managed side is to bypass cache lookup, since conversions for these types should not be recorded in the cache anyways.

Why not? I would expect the type equivalent lookups to be recorded in the cache just fine.

**Comment by VSadov** [comment]
To be cacheable a cast must be "compatible-with" cast - same relation as used by castclass and isinst and be applicable in nested contexts like arrays, variance, interface implementation,..
It also should be idempotent. 

Most likely I assumed that like COM and ICastable, which rely on logic external to the type system, these are also not idempotent.

**Comment by ViktorHofer** [comment]
// Auto-generated message

https://github.com/dotnet/runtime/commit/69e114c1abf91241a0eeecf1ecceab4711b8aa62 which was merged 12/7 removed the intermediate src/coreclr/**src**/ folder. This PR needs to be updated as it touches files in that directory which causes conflicts.

To update your commits you can use this bash script: https://gist.github.com/ViktorHofer/6d24f62abdcddb518b4966ead5ef3783. Feel free to use the comment section of the gist to improve the script for others.

**Comment by VSadov** [comment]
I looked more into the issue of whether the equivalence check in `IsInstanceOfClass` is needed.

=== I think the check is needed in the general cast analysis, but not needed in a JIT helper.

Normally, when casting to a class (not an interface), once we went through the list of bases in the “from” type, we could fail the cast. However, it is also possible that there is a cast through type equivalence, so we need to check for that too.
BTW, the cast via equivalence is cacheable, sorry for confusion. This check was not about caching though, it is just whether we can reject a cast early right after seeing the chain of bases. 
The native `MethodTable::CanCastToClass`, has similar check too, always had it.
https://github.com/dotnet/runtime/blob/69e114c1abf91241a0eeecf1ecceab4711b8aa62/src/coreclr/vm/methodtable.cpp#L1660

=== Why this is not relevant to a JIT helper:

JIT knows the “to” type statically and will not use CORINFO_HELP_ISINSTANCEOFCLASS if the type has type-equivalence bit. 
https://github.com/dotnet/runtime/blob/5e0f955c77143af36f19b4d093672f2ce72bd65d/src/coreclr/vm/jitinterface.cpp#L6199

To be compatible via type-equivalency both types must be marked as type-equivalent, so inside `IsInstanceOfClass` knowing whether "from" type participates in type equivalence does not change the result.

**Review by jkotas — APPROVED** [review]
Looks good. Thank you!

**Comment by VSadov** [comment]
Thanks!!   

Just to be sure - I think backport to 5.X is no longer interesting for this.

**Comment by jkotas** [comment]
> Just to be sure - I think backport to 5.X is no longer interesting for this.

Agree.

**Pull request merged**
