### PR TITLE
[HTTP/3] Fix content stream read hang

### LINKED ISSUE #57888: [HTTP/3] Hang when reading response data
Edit: Initially I thought this issue was caused by bidirecitonal streaming, but I've recreated it when just streaming data from the server.

I think the issue is similar to https://github.com/dotnet/runtime/issues/56115, the read buffer is bigger than the available data. The difference in the new hang is the client calls `responseStream.ReadAsync` with a large buffer before the data is available.

---

Scenario:
1. Client starts request to the server
2. Client sends headers + data to the server
3. Server reads incoming data
4. Server echos request data in response
4. Client reads response data
5. Client sends data to the server
6. Server reads incoming data
7. Server echos request data in response
8. Client reads response data **<-- HANG**
9. Client completes the request
10. Server completes the response

Test: https://github.com/grpc/grpc-dotnet/blob/9f72e70c6a47ae823bb3ddcc719f1c63bf721fc7/test/FunctionalTests/Server/DuplexStreamingMethodTests.cs#L37

If the client completes the request before reading the second response then it works.

Failure logs:

```
 MultipleMessagesFromOneClient_SuccessResponses
   Source: DuplexStreamingMethodTests.cs line 38
   Duration: 5.3 sec

  Message: 
System.TimeoutException : The operation at C:\Development\Source\grpc-dotnet\test\FunctionalTests\Server\DuplexStreamingMethodTests.cs:94 timed out after reaching the limit of 5000ms.

  Stack Trace: 
TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) line 76
DuplexStreamingMethodTests.MultipleMessagesFromOneClient_SuccessResponses() line 94
GenericAdapter`1.BlockUntilCompleted()
NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
<>c__DisplayClass1_0.<Execute>b__0()
BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

  Standard Output: 
0.004s GrpcTestContext - Information: Starting DuplexStreamingMethodTests.MultipleMessagesFromOneClient_SuccessResponses
0.037s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - Info : StreamingContent#1850352,.ctor, ->
0.043s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - Associate : HttpRequestMessage#33110891,Content,HttpRequestMessage#33110891,StreamingContent#1850352 ->
0.046s HttpEventSourceListener - Debug: <- Event System.Net.Http - RequestStart : https,127.0.0.1,50019,/Chat.Chatter/Chat,2,0,1 ->
0.083s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - Info : WinInetProxyHelper#4724298,.ctor,AutoConfigUrl=(null), AutoDetect=True, Proxy=(null), ProxyBypass=(null) ->
0.083s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - Info : WinInetProxyHelper#4724298,.ctor,_useProxy=True ->
0.083s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - Info : WinInetProxyHelper#4724298,TryCreate,AutoSettingsUsed, calling WinHttpOpen ->
0.086s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - Info : HttpConnectionHandler#38643946,.ctor, ->
0.086s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - Info : DiagnosticsHandler#28828555,.ctor, ->
0.086s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - Info : RedirectHandler#61916781,.ctor, ->
0.092s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - ErrorMessage : WinInetProxyHelper#4724298,GetProxyForUrl,error=12180 ->
0.092s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - Info : WinInetProxyHelper#4724298,GetProxyForUrl,useProxy=False ->
0.095s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 54860159,0,0,.ctor,HttpConnectionPool https://127.0.0.1:50019 ->
0.098s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 54860159,0,0,GetHttp3ConnectionAsync,Attempting new HTTP3 connection. ->
0.100s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#31364791,.ctor,[conn][0x25F6A4F2A40] Outbound connection created ->
0.103s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#24388906,.ctor,[conn][0x25F6A559020] Inbound connection created ->
0.106s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#24388906,NativeCallbackHandler,[conn][0x25F6A559020] Connection received event IDEAL_PROCESSOR_CHANGED ->
0.113s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#31364791,NativeCallbackHandler,[conn][0x25F6A4F2A40] Connection received event STREAMS_AVAILABLE ->
0.113s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#31364791,NativeCallbackHandler,[conn][0x25F6A4F2A40] Connection received event DATAGRAM_STATE_CHANGED ->
0.115s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#31364791,NativeCallbackHandler,[conn][0x25F6A4F2A40] Connection received event PEER_CERTIFICATE_RECEIVED ->
0.117s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : SafeX509ChainHandle#63449985,Verify,CertVerifyCertificateChainPolicy returned: True. Status: 2148204815 ->
0.117s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#31364791,NativeCallbackHandler,[conn][0x25F6A4F2A40] Connection received event CONNECTED ->
0.118s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#24388906,NativeCallbackHandler,[conn][0x25F6A559020] Connection received event CONNECTED ->
0.120s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#47741942,HandleEvent,(null) Stream received event START_COMPLETE ->
0.120s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#47741942,.ctor,[strm][0x25F6A5AFD00] Outbound unidirectional stream created in connection [conn][0x25F6A4F2A40]. ->
0.121s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#47741942,HandleEvent,[strm][0x25F6A5AFD00] Stream received event SEND_COMPLETE ->
0.122s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#24388906,NativeCallbackHandler,[conn][0x25F6A559020] Connection received event PEER_STREAM_STARTED ->
0.122s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#65532796,.ctor,[strm][0x25F6A4F6DD0] Inbound unidirectional stream created in connection [conn][0x25F6A559020]. ->
0.122s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#65532796,HandleEvent,[strm][0x25F6A4F6DD0] Stream received event RECEIVE ->
0.122s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#65532796,HandleEventRecv,[strm][0x25F6A4F6DD0] Stream received 8 bytes ->
0.126s SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Quic - Debug: Connection id "0HMB50ULSMP2L" accepted.
0.129s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 54860159,0,0,GetHttp3ConnectionAsync,New HTTP3 connection established. ->
0.130s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEvent,(null) Stream received event START_COMPLETE ->
0.130s SERVER Microsoft.AspNetCore.Server.Kestrel.Connections - Debug: Connection id "0HMB50ULSMP2L" accepted.
0.130s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,.ctor,[strm][0x25F6A5F3A50] Outbound bidirectional stream created in connection [conn][0x25F6A4F2A40]. ->
0.131s SERVER Microsoft.AspNetCore.Server.Kestrel.Connections - Debug: Connection id "0HMB50ULSMP2L" started.
0.135s GrpcTestContext - Information: Client sending message
0.136s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#54752321,HandleEvent,(null) Stream received event START_COMPLETE ->
0.137s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#54752321,.ctor,[strm][0x25F6A5F3FF0] Outbound unidirectional stream created in connection [conn][0x25F6A559020]. ->
0.138s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,ReadAsync,[strm][0x25F6A5F3A50] Stream reading into Memory of '64' bytes. ->
0.138s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEvent,[strm][0x25F6A5F3A50] Stream received event SEND_COMPLETE ->
0.140s GrpcTestContext - Information: Client waiting for response
0.144s SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Quic - Debug: Stream id "0HMB50ULSMP2L:00000003" type Unidirectional connected.
0.148s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#54752321,HandleEvent,[strm][0x25F6A5F3FF0] Stream received event SEND_COMPLETE ->
0.152s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#54752321,HandleEvent,[strm][0x25F6A5F3FF0] Stream received event SEND_COMPLETE ->
0.153s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#65532796,ReadAsync,[strm][0x25F6A4F6DD0] Stream reading into Memory of '4096' bytes. ->
0.153s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#65532796,ReadAsync,[strm][0x25F6A4F6DD0] Stream reading into Memory of '4096' bytes. ->
0.154s SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Quic - Debug: Stream id "0HMB50ULSMP2L:00000002" type Unidirectional accepted.
0.159s SERVER Microsoft.AspNetCore.Server.Kestrel.Http3 - Trace: Connection id "0HMB50ULSMP2L" received SETTINGS frame for stream ID 2 with length 5.
0.161s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#24388906,NativeCallbackHandler,[conn][0x25F6A559020] Connection received event PEER_STREAM_STARTED ->
0.161s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#31364791,NativeCallbackHandler,[conn][0x25F6A4F2A40] Connection received event PEER_STREAM_STARTED ->
0.161s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#44307732,.ctor,[strm][0x25F6A5F2C40] Inbound unidirectional stream created in connection [conn][0x25F6A4F2A40]. ->
0.161s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#58801125,.ctor,[strm][0x25F6A5F3D20] Inbound bidirectional stream created in connection [conn][0x25F6A559020]. ->
0.161s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#44307732,HandleEvent,[strm][0x25F6A5F2C40] Stream received event RECEIVE ->
0.161s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#58801125,HandleEvent,[strm][0x25F6A5F3D20] Stream received event RECEIVE ->
0.161s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#44307732,HandleEventRecv,[strm][0x25F6A5F2C40] Stream received 8 bytes ->
0.161s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#58801125,HandleEventRecv,[strm][0x25F6A5F3D20] Stream received 114 bytes ->
0.162s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#58801125,ReadAsync,[strm][0x25F6A5F3D20] Stream reading into Memory of '4096' bytes. ->
0.162s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#44307732,ReadAsync,[strm][0x25F6A5F2C40] Stream reading into Memory of '32' bytes. ->
0.162s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#58801125,ReadAsync,[strm][0x25F6A5F3D20] Stream reading into Memory of '4096' bytes. ->
0.162s SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.Quic - Debug: Stream id "0HMB50ULSMP2L:00000000" type Bidirectional accepted.
0.163s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#44307732,ReadAsync,[strm][0x25F6A5F2C40] Stream reading into Memory of '32' bytes. ->
0.168s SERVER Microsoft.AspNetCore.Server.Kestrel.Http3 - Trace: Connection id "0HMB50ULSMP2L" received HEADERS frame for stream ID 0 with length 86.
0.183s SERVER Microsoft.AspNetCore.Server.Kestrel.Http3 - Trace: Connection id "0HMB50ULSMP2L" received DATA frame for stream ID 0 with length 23.
0.187s SERVER Microsoft.AspNetCore.Hosting.Diagnostics - Information: Request starting HTTP/3 POST https://127.0.0.1:50019/Chat.Chatter/Chat application/grpc -
0.212s SERVER Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware - Debug: Request matched endpoint 'gRPC - /chat.Chatter/Chat'
0.215s SERVER Microsoft.AspNetCore.Routing.EndpointMiddleware - Information: Executing endpoint 'gRPC - /chat.Chatter/Chat'
0.224s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Reading message.
0.225s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HMB50ULSMP2L", Request id "0HMB50ULSMP2L:00000000": started reading request body.
0.228s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Deserializing 18 byte message to 'Chat.ChatMessage'.
0.234s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Received message.
0.237s SERVER Microsoft.AspNetCore.Server.Kestrel.Http3 - Trace: Connection id "0HMB50ULSMP2L" sending HEADERS frame for stream ID 0 with length 115.
0.237s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Sending message.
0.240s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Serialized 'Chat.ChatMessage' to 18 byte message.
0.241s SERVER Microsoft.AspNetCore.Server.Kestrel.Http3 - Trace: Connection id "0HMB50ULSMP2L" sending DATA frame for stream ID 0 with length 23.
0.241s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#58801125,HandleEvent,[strm][0x25F6A5F3D20] Stream received event SEND_COMPLETE ->
0.241s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Message sent.
0.241s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Reading message.
0.241s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEvent,[strm][0x25F6A5F3A50] Stream received event RECEIVE ->
0.241s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEventRecv,[strm][0x25F6A5F3A50] Stream received 143 bytes ->
0.242s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEvent,[strm][0x25F6A5F3A50] Stream received event RECEIVE ->
0.242s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEventRecv,[strm][0x25F6A5F3A50] Stream received 79 bytes ->
0.242s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#58801125,HandleEvent,[strm][0x25F6A5F3D20] Stream received event IDEAL_SEND_BUFFER_SIZE ->
0.242s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 54860159,31311345,0,ReadFrameEnvelopeAsync,Received frame 1 of length 115. ->
0.243s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - Associate : HttpResponseMessage#48888596,RequestMessage,HttpResponseMessage#48888596,HttpRequestMessage#33110891 ->
0.243s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - Info : HttpConnectionResponseContent#40958767,.ctor, ->
0.243s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - Associate : HttpResponseMessage#48888596,Content,HttpResponseMessage#48888596,HttpConnectionResponseContent#40958767 ->
0.243s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,ReadAsync,[strm][0x25F6A5F3A50] Stream reading into Memory of '64' bytes. ->
0.243s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEvent,[strm][0x25F6A5F3A50] Stream received event RECEIVE ->
0.243s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEventRecv,[strm][0x25F6A5F3A50] Stream received 15 bytes ->
0.251s HttpEventSourceListener - Debug: <- Event System.Net.Http - RequestStop :  ->
0.262s GrpcTestContext - Information: Client reading message
0.265s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 54860159,31311345,0,ReadFrameEnvelopeAsync,Received frame 0 of length 23. ->
0.265s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,ReadAsync,[strm][0x25F6A5F3A50] Stream reading into Memory of '15' bytes. ->
0.267s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,ReadAsync,[strm][0x25F6A5F3A50] Stream reading into Memory of '64' bytes. ->
0.271s GrpcTestContext - Information: Client sending message
0.271s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEvent,[strm][0x25F6A5F3A50] Stream received event SEND_COMPLETE ->
0.271s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#58801125,HandleEvent,[strm][0x25F6A5F3D20] Stream received event RECEIVE ->
0.271s GrpcTestContext - Information: Client reading message
0.271s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#58801125,HandleEventRecv,[strm][0x25F6A5F3D20] Stream received 25 bytes ->
0.271s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEvent,[strm][0x25F6A5F3A50] Stream received event IDEAL_SEND_BUFFER_SIZE ->
0.272s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#58801125,ReadAsync,[strm][0x25F6A5F3D20] Stream reading into Memory of '4096' bytes. ->
0.272s SERVER Microsoft.AspNetCore.Server.Kestrel.Http3 - Trace: Connection id "0HMB50ULSMP2L" received DATA frame for stream ID 0 with length 23.
0.273s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Deserializing 18 byte message to 'Chat.ChatMessage'.
0.273s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Received message.
0.273s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Sending message.
0.273s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Serialized 'Chat.ChatMessage' to 18 byte message.
0.273s SERVER Microsoft.AspNetCore.Server.Kestrel.Http3 - Trace: Connection id "0HMB50ULSMP2L" sending DATA frame for stream ID 0 with length 23.
0.273s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Message sent.
0.273s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Reading message.
0.273s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#58801125,HandleEvent,[strm][0x25F6A5F3D20] Stream received event SEND_COMPLETE ->
0.274s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEvent,[strm][0x25F6A5F3A50] Stream received event RECEIVE ->
0.274s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEventRecv,[strm][0x25F6A5F3A50] Stream received 25 bytes ->
0.274s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 54860159,31311345,0,ReadFrameEnvelopeAsync,Received frame 0 of length 23. ->
0.274s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,ReadAsync,[strm][0x25F6A5F3A50] Stream reading into Memory of '64' bytes. ->
5.307s GrpcTestContext - Information: Finishing DuplexStreamingMethodTests.MultipleMessagesFromOneClient_SuccessResponses
```

The end of the logs show the client receiving the second message's data frame and then hanging:

```
0.273s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#58801125,HandleEvent,[strm][0x25F6A5F3D20] Stream received event SEND_COMPLETE ->
0.274s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEvent,[strm][0x25F6A5F3A50] Stream received event RECEIVE ->
0.274s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,HandleEventRecv,[strm][0x25F6A5F3A50] Stream received 25 bytes ->
0.274s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Http - HandlerMessage : 54860159,31311345,0,ReadFrameEnvelopeAsync,Received frame 0 of length 23. ->
0.274s HttpEventSourceListener - Debug: <- Event Private.InternalDiagnostics.System.Net.Quic - Info : State#456780,ReadAsync,[strm][0x25F6A5F3A50] Stream reading into Memory of '64' bytes. ->
5.307s GrpcTestContext - Information: Finishing DuplexStreamingMethodTests.MultipleMessagesFromOneClient_SuccessResponses
```

SDK info:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21421.6
 Commit:    77703ed54e
```

### PR DESCRIPTION
**Pull request by CarnaViire**
The fix is similar to PR #56892 but for another branch (when data is buffered). The root cause is the same - if there's still space in user's buffer we'd start waiting for the next data frame to arrive (which will not happen in echo scenario).

Current code (including #56892 change) may be inefficient in case of small data frames that may be already available in transport, but refactoring that is too large of a change if we consider backporting. I thought #56891 would cover that, but it's QUIC specific, while we also have HTTP/3 specific problem here. I will create another issue later.

Fixes #57888

### CODE REVIEW

**Comment by geoffkizer** [comment]
We really should refactor ReadResponseContent and ReadResponseContentAsync so they do not have so much duplicated logic. Doesn't have to happen for 6.0 though.

**Comment by geoffkizer** [comment]
I think we still have a potential hang here. 

Just because an HTTP3 DATA frame says it is X bytes long, does not necessarily guarantee that the peer will send all X bytes promptly. If a user sends a DATA frame with length 1000, but only sends 500 bytes, this will hang. That's bad. We should give the user whatever data we have available at the time.

The logic here should be similar to how we handle chunked encoding for HTTP/1.1. See here: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ChunkedEncodingReadStream.cs#L38

I'm not sure why it was implemented so differently than chunked encoding in the first place.

In other words, we should do something like this:
(1) Read as much data out of our read buffer as we can. If we can read at least one byte, or we hit EOF, we are done and return to the caller. (This is the ReadChunksFromConnectionBuffer logic in the chunked encoding code.)
(2) At this point, we need to read more data. In certain cases it makes sense to avoid buffering the data ourselves and just read directly into the user's buffer. If so, do the read and (assuming it doesn't fail or return unexpected EOF) return.
(3) Otherwise, we need to read into the buffer. Do the read into the buffer and try to get data out of the buffer again (as in step 1, i.e. call the equivalent of ReadChunksFromConnectionBuffer). If we can read at least one byte, or we hit EOF, we are done.
(4) Otherwise, we must not have read enough data (e.g. we just got a partial frame header or something like that. Loop back to step 3 and repeat until we either get some data or hit EOF.

(Note that the chunked encoding logic actually loops back to step 2 instead of step 3. In theory that allows us to do the optimization in step 2 in a very narrow case, where we read exactly the "chunk header" in step 3 but don't read any chunk data. This seems unlikely in practice, but there's probably no harm in having the extra optimization here.)

HTTP3 DATA frames should actually be a bit simpler to handle than HTTP/1.1 chunked encoding, because their layout is simpler -- the frame header is a fixed size, the length is binary encoded instead of ASCII, there's no trailing frame delimiter as there is in chunked encoding (i.e. trailing "\r\n" for every chunk). Note however that for HTTP3, I think we do need to accept 0-length DATA frames -- whereas in chunked encoding, we don't (because a 0-length frame indicates EOF).

**Comment by geoffkizer** [comment]
Also note the description above is similar to how we processing incoming SSL frames. See https://github.com/dotnet/runtime/blob/a579575853cea23aa1b6b6b8d3ef978aa9321e16/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs#L914

**Comment by CarnaViire** [comment]
@geoffkizer but we still believe that frame envelope and at least start of the payload should arrive promptly, right? The way ReadFrameEnvelopeAsync is implemented, it will block until both frame type and payload length are read. And it doesn't make sense to return until at least 1 byte of the payload is read.
The hang you are worried about may be mitigated easily by always returning from "read into user's buffer" branch, not only on frame border here
https://github.com/dotnet/runtime/blob/b75e55beb1628df8f704a3014b9acd1b98d4f445/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs#L1126-L1129
Other than that, the buffer we have now is small (64 bytes) and we don't have a logic of growing it... (so it's only useful for envelopes) But we can use e.g. larger initial size, at least 4KB as in HTTP/1.1, so branching on whether to read into user's buffer or to our buffer would make sense (now I believe it's not)

**Comment by geoffkizer** [comment]
> @geoffkizer but we still believe that frame envelope and at least start of the payload should arrive promptly, right? The way ReadFrameEnvelopeAsync is implemented, it will block until both frame type and payload length are read. And it doesn't make sense to return until at least 1 byte of the payload is read.

We can't do anything other than wait for frame header + 1 byte. Until then we have no data to return to the user.

> The hang you are worried about may be mitigated easily by always returning from "read into user's buffer" branch, not only on frame border here
> https://github.com/dotnet/runtime/blob/b75e55beb1628df8f704a3014b9acd1b98d4f445/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs#L1126-L1129

That sounds good.

> Other than that, the buffer we have now is small (64 bytes) and we don't have a logic of growing it... (so it's only useful for envelopes) But we can use e.g. larger initial size, at least 4KB as in HTTP/1.1, so branching on whether to read into user's buffer or to our buffer would make sense (now I believe it's not)

We should probably use a size like 4K here, yeah.

QUIC is rather different than HTTP1/2 because it's in user mode and it actively pushes data to us. We should think through the implications of this and try to make sure we are optimizing for how QUIC works in practice. But at least for now it seems reasonable to make this work fairly similarly to HTTP/1.1 since we know that works correctly and gives pretty good performance.

**Comment by CarnaViire** [comment]
Implementing buffering logic that @geoffkizer described ended up being a larger change that I'd like to see here for hang mitigation (and it didn't work on the first try 😁)
Even if I'd make it work, I'd still rather open a separate PR.

**Comment by geoffkizer** [comment]
> Even if I'd make it work, I'd still rather open a separate PR.

Yeah, we should do some perf analysis as part of this as well. I agree we should defer to a separate PR.

But I do think we should fix this issue in the current PR:

> Just because an HTTP3 DATA frame says it is X bytes long, does not necessarily guarantee that the peer will send all X bytes promptly. If a user sends a DATA frame with length 1000, but only sends 500 bytes, this will hang. That's bad. We should give the user whatever data we have available at the time.

**Review by geoffkizer — APPROVED** [review]

**Review by ManickaP — APPROVED** [review]

**Pull request merged**
