### PR TITLE
Replace DAMT.All with more restricted annotation on InvokeMember/FindMembers/DeclaredMembers

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
I'm looking at places we use .All to see if the new annotations could help. Here we don't need the new annotations, this was always expressible. I can only assume the reason for .All was laziness. This was at a time when we believed .All "just keeps a bit more" and we didn't consider the impact of marking interface methods implemented by the class, or the impact of warnings due to .All capturing things that are not safe to reflection-call.

This is a breaking change in theory, should someone implement `IReflect` or derive from `System.TypeInfo` - they need to update the annotations.

Cc @dotnet/illink @eerhardt

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
@dotnet/illink @eerhardt anyone could have a look please?

**Review by sbomer — APPROVED** [review]
LGTM. I think the breaking change is acceptable - should be rare for anyone to hit this, and if they do, fixing the annotations to match this would be an improvement.

**Comment by ericstj** [comment]
## 📋 Breaking Change Documentation Required

[Create a breaking change issue with AI-generated content](https://github.com/dotnet/docs/issues/new?title=%5BBreaking%20change%5D%3A%20Replace%20DAMT.All%20with%20more%20restricted%20annotation%20on%20InvokeMember/FindMembers/DeclaredMembers&body=%23%23%23%20%5BBreaking%20change%5D%3A%20Replace%20DAMT.All%20with%20more%20restricted%20annotation%20on%20InvokeMember/FindMembers/DeclaredMembers%0A%0A%23%23%23%23%20Description%0A%0AStarting%20in%20.NET%2010.0,%20the%20`System.Reflection`%20APIs%20`InvokeMember`,%20`FindMembers`,%20and%20`DeclaredMembers`%20have%20been%20updated%20to%20use%20more%20restricted%20annotations%20instead%20of%20`DAMT.All`.%20This%20change%20affects%20scenarios%20where%20developers%20implement%20the%20`IReflect`%20interface%20or%20derive%20from%20`System.TypeInfo`.%20The%20previous%20use%20of%20`DAMT.All`%20was%20overly%20permissive%20and%20could%20lead%20to%20unintended%20behavior,%20such%20as%20capturing%20interface%20methods%20implemented%20by%20a%20class%20or%20generating%20warnings%20due%20to%20unsafe%20reflection%20calls.%0A%0AThis%20change%20improves%20the%20accuracy%20of%20annotations%20and%20ensures%20better%20compatibility%20with%20trimming%20and%20reflection%20scenarios.%20However,%20it%20introduces%20a%20breaking%20change%20for%20developers%20who%20have%20implemented%20`IReflect`%20or%20derived%20from%20`System.TypeInfo`,%20as%20they%20may%20need%20to%20update%20their%20annotations%20to%20align%20with%20the%20new%20behavior.%0A%0A%23%23%23%23%20Version%0A%0A.NET%2010.0%0A%0A%23%23%23%23%20Previous%20behavior%0A%0AThe%20`InvokeMember`,%20`FindMembers`,%20and%20`DeclaredMembers`%20APIs%20used%20the%20`DAMT.All`%20annotation,%20which%20was%20overly%20permissive.%20This%20could%20result%20in%20capturing%20additional%20members,%20such%20as%20interface%20methods%20implemented%20by%20a%20class,%20and%20potentially%20cause%20runtime%20warnings%20or%20unsafe%20reflection%20calls.%0A%0AFor%20example%3A%0A%0A```csharp%0Apublic%20class%20MyType%20%3A%20IReflect%0A{%0A%20%20%20%20public%20MethodInfo%5B%5D%20GetMethods%28BindingFlags%20bindingAttr%29%0A%20%20%20%20{%0A%20%20%20%20%20%20%20%20//%20Previous%20behavior%3A%20DAMT.All%20annotation%20applied%0A%20%20%20%20%20%20%20%20//%20This%20could%20capture%20additional%20members,%20including%20interface%20methods%20implemented%20by%20the%20class%0A%20%20%20%20}%0A}%0A```%0A%0A%23%23%23%23%20New%20behavior%0A%0AThe%20`InvokeMember`,%20`FindMembers`,%20and%20`DeclaredMembers`%20APIs%20now%20use%20more%20restricted%20annotations,%20which%20provide%20better%20control%20over%20the%20members%20captured%20during%20reflection.%20Developers%20implementing%20`IReflect`%20or%20deriving%20from%20`System.TypeInfo`%20must%20update%20their%20annotations%20to%20match%20the%20new%20behavior.%0A%0AFor%20example%3A%0A%0A```csharp%0Apublic%20class%20MyType%20%3A%20IReflect%0A{%0A%20%20%20%20%5BDynamicallyAccessedMembers%28DynamicallyAccessedMemberTypes.PublicMethods%29%5D%0A%20%20%20%20public%20MethodInfo%5B%5D%20GetMethods%28BindingFlags%20bindingAttr%29%0A%20%20%20%20{%0A%20%20%20%20%20%20%20%20//%20New%20behavior%3A%20More%20restricted%20annotation%20applied%0A%20%20%20%20%20%20%20%20//%20Only%20public%20methods%20are%20captured,%20avoiding%20unintended%20members%0A%20%20%20%20}%0A}%0A```%0A%0A%23%23%23%23%20Type%20of%20breaking%20change%0A%0A-%20**Source%20incompatible**%3A%20When%20recompiled%20using%20.NET%2010.0%20or%20targeting%20the%20new%20runtime,%20existing%20source%20code%20may%20require%20changes%20to%20annotations%20to%20compile%20successfully.%0A-%20**Behavioral%20change**%3A%20Existing%20binaries%20might%20behave%20differently%20at%20runtime%20due%20to%20the%20updated%20annotations.%0A%0A%23%23%23%23%20Reason%20for%20change%0A%0AThe%20change%20was%20introduced%20to%20improve%20the%20accuracy%20of%20annotations%20in%20`System.Reflection`%20APIs%20and%20to%20address%20issues%20caused%20by%20the%20overly%20permissive%20`DAMT.All`%20annotation.%20This%20ensures%20better%20compatibility%20with%20trimming%20and%20reflection%20scenarios,%20reduces%20runtime%20warnings,%20and%20prevents%20unsafe%20reflection%20calls.%0A%0A%23%23%23%23%20Recommended%20action%0A%0ADevelopers%20who%20implement%20`IReflect`%20or%20derive%20from%20`System.TypeInfo`%20should%20review%20their%20code%20and%20update%20annotations%20to%20align%20with%20the%20new%20behavior.%20Specifically%3A%0A%0A1.%20Replace%20`DAMT.All`%20annotations%20with%20more%20restricted%20annotations,%20such%20as%20`DynamicallyAccessedMemberTypes.PublicMethods`,%20`DynamicallyAccessedMemberTypes.NonPublicMethods`,%20or%20other%20appropriate%20types.%0A2.%20Test%20reflection%20scenarios%20to%20ensure%20that%20the%20updated%20annotations%20capture%20the%20intended%20members%20and%20do%20not%20introduce%20runtime%20errors%20or%20warnings.%0A%0AFor%20example,%20update%20code%20as%20follows%3A%0A%0A**Before%3A**%0A%0A```csharp%0Apublic%20class%20MyType%20%3A%20IReflect%0A{%0A%20%20%20%20public%20MethodInfo%5B%5D%20GetMethods%28BindingFlags%20bindingAttr%29%0A%20%20%20%20{%0A%20%20%20%20%20%20%20%20//%20Previous%20behavior%3A%20DAMT.All%20annotation%20applied%0A%20%20%20%20}%0A}%0A```%0A%0A**After%3A**%0A%0A```csharp%0Apublic%20class%20MyType%20%3A%20IReflect%0A{%0A%20%20%20%20%5BDynamicallyAccessedMembers%28DynamicallyAccessedMemberTypes.PublicMethods%29%5D%0A%20%20%20%20public%20MethodInfo%5B%5D%20GetMethods%28BindingFlags%20bindingAttr%29%0A%20%20%20%20{%0A%20%20%20%20%20%20%20%20//%20New%20behavior%3A%20More%20restricted%20annotation%20applied%0A%20%20%20%20}%0A}%0A```%0A%0A%23%23%23%23%20Feature%20area%0A%0A-%20Core%20.NET%20libraries%0A-%20System.Reflection%0A%0A%23%23%23%23%20Affected%20APIs%0A%0A-%20`System.Reflection.IReflect.InvokeMember`%0A-%20`System.Reflection.IReflect.FindMembers`%0A-%20`System.Reflection.TypeInfo.DeclaredMembers`%0A%0A%23%23%23%23%20Additional%20resources%0A%0AFor%20more%20information%20on%20`DynamicallyAccessedMembers`%20annotations%20and%20their%20usage,%20refer%20to%20the%20%5BMicrosoft%20documentation%20on%20trimming%20and%20reflection%5D%28https%3A//learn.microsoft.com/dotnet/core/deploying/trimming/prepare-libraries-for-trimming%29.%0A%0A---%0A%0AFinally,%20please%20email%20a%20link%20to%20this%20breaking%20change%20issue%20to%20%5B.NET%20Breaking%20Change%20Notifications%5D%28mailto%3Adotnetbcn%40microsoft.com%29.&labels=breaking-change,Pri1,doc-idea)

*Generated by Breaking Change Documentation Tool - 2025-10-03 13:49:42*

**Comment by ericstj** [comment]
@sbomer @agocke would it be possible to get your help filing a breaking change doc for this?  Just click the above link, review it's content and submit?  Thank you!

**Pull request merged**
