### PR TITLE
Reenable SocketsHttpHandlerTest_Http3_MsQuic.SendMoreThanStreamLimitRequestsConcurrently_LastWaits test

### PR DESCRIPTION
**Pull request by rzikm**
Just check if test passes on CI

### CODE REVIEW

**Comment by rzikm** [comment]
I managed to reproduce this locally, will try to catch a dump to see what is going on

**Comment by rzikm** [comment]
dump analysis shows that the `lastRequestContentStarted` task completion source is never set and that server task is "stuck" after disposing of the first stream. Will revisit this after we have proper async dispose of the MsQuicStream

**Comment by rzikm** [comment]
Does not reproduce anymore after #67859

**Review by CarnaViire — APPROVED** [review]
LGTM. Let's try it. Could you please take a closer look at this test in CI for some time to be sure it wouldn't start failing/hanging?

**Comment by rzikm** [comment]
I am still monitoring all test failures so if this starts happening again, I will hopefully notice it :)

**Comment by rzikm** [comment]
CI Failures are unrelated (`LibraryImportGenerator.Unit.Tests`)

**Pull request merged**
