### PR TITLE
[wasm] Wasm.Build.Tests - Override KnownWebAssemblySdkPack to 8.0.0-dev

### PR DESCRIPTION
**Pull request by maraf**
Override version of `KnownWebAssemblySdkPack` in `Microsoft.NETCoreSdk.BundledVersions.props` to point to local built package

### CODE REVIEW

**Comment by maraf** [comment]
@radical It seems that it uses for some reason a global nuget cache. Am I doing something wrong?

image

**Comment by radical** [comment]
> @radical It seems that it uses for some reason a global nuget cache. Am I doing something wrong?
> 
> image

How did you get this? I tried it locally, and even if I have `8.0.0-dev` in my global cache, the tests always correctly pick up from the test-local fresh cache.

**Comment by maraf** [comment]
> How did you get this?

I built the dotnet-latest using the target from WBT to build it and than 
I'm using `dotnet-latest/dotnet.exe` to create project and etc. I'll try from scratch next week and dig in.

**Comment by radical** [comment]
Using dotnet from there won't change where the nuget cache is used from. That special setup is for the tests. You can override it manually or use a custom nuget.config . You can find one with the built test projects.

**Comment by maraf** [comment]
Ook, I knew about nuget feed configuration, but I was missing `$env:NUGET_PACKAGES`. Thanks!

@radical This is ready for review than.

**Review by pavelsavara — APPROVED** [review]
@radical feel free to further improve this in subsequent PRs
We need to unblock https://github.com/dotnet/runtime/pull/85730

**Pull request merged**
