### PR TITLE
Bring back JIT support for core Vector64/128/256/512 APIs

### PR DESCRIPTION
**Pull request by tannergooding**
As per the discussion in https://github.com/dotnet/runtime/pull/103150, the basic building blocks (`Vector64/128/256/512<T>` and `Vector<T>`) should stay intrinsic in the JIT.

This doesn't bring back "all" APIs, but rather the core ones that are expected to see the heaviest usage. In general, the rule I followed on deciding what to bring back vs not was that if it was a general API that was a 1-to-1 forward to another intrinsic and didn't get any other specialization it was fine to leave in managed

So while it brings back ones like `get_Zero` and `As`, it doesn't bring back `And` (forwards to `op_BitwiseAddition`), `Add` (forwards to `op_Addition`), or `Load` (forwards to `LoadUnsafe`).

As per the discussion, `Vector2`, `Vector3`, `Vector4`, `Quaternion`, and `Plane` remain implemented in managed.

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @jkotas

**Review by jkotas — APPROVED** [review]
LGTM. (Somebody from the JIT team should signoff as well.)

**Comment by tannergooding** [comment]
(Pushed to the wrong branch by accident, it's back to how it was at last approval)

**Comment by tannergooding** [comment]
> (Somebody from the JIT team should signoff as well.)

CC. @EgorBo, since you've reviewed the other PRs

**Review by EgorBo — APPROVED** [review]

**Pull request merged**
