### PR TITLE
Add FlagsAttribute to GC_ALLOC_FLAGS

### LINKED ISSUE #65004: Add `FlagsAttribute` to `GC_ALLOC_FLAGS`
I get the following diagnostic (I don't know if it's a Roslyn or ReSharper Diagnostic, but it seems to make sense):
grafik

https://github.com/dotnet/runtime/blob/1c927462696f5af7d5e667f54b1c39452cba4b2d/src/coreclr/System.Private.CoreLib/src/System/GC.cs#L87-L93

I think it would be good adding this Attribute on this internal enum.
https://github.com/dotnet/runtime/blob/b2dc37ba181a7fa4427e717eab819ba3543d0ae4/src/coreclr/tools/Common/Internal/Runtime/RuntimeConstants.cs#L47-L53

Would also make sense imo to move the two identical enums I found in a central location to reduce code duplication.

### PR DESCRIPTION
**Pull request by pedrobsaila**
Fixes #65004

### CODE REVIEW

**Comment by stephentoub** [comment]
[Flags] is primarily useful for parsing and formatting of enums.  Is any code doing that with this enum?

**Comment by tannergooding** [comment]
It'd also impact debugging, but its probably a question for the GC team

**Comment by pedrobsaila** [comment]
> [Flags] is primarily useful for parsing and formatting of enums. Is any code doing that with this enum?

https://github.com/dotnet/runtime/blob/a5fda753afce966b9d31c76559636eb515bfa05a/src/coreclr/nativeaot/System.Private.CoreLib/src/System/GC.cs#L715-L717

**Comment by stephentoub** [comment]
> There is 2 places

Thanks.  If those are the only two places it's used, adding [Flags] isn't really helping anything.

@Maoni0, do you want this?

**Comment by Maoni0** [comment]
I don't see any benefit for the GC team.

**Comment by deeprobin** [comment]
> > There is 2 places
> 
> Thanks. If those are the only two places it's used, adding [Flags] isn't really helping anything.
> 
> @Maoni0, do you want this?

Moving the two enums to a fixed location is already a good start.

As described in the issue, I get a Diagnostic on the bitwise-or-operator. We won't get any real performance improvement from this but in my opinion it should be added for the sake of propriety (and it doesn't hurt anyone).

https://user-images.githubusercontent.com/10373452/153061511-8f27a500-5fde-4298-8b9a-80c1172ac219.png

**Review by deeprobin — APPROVED** [review]
LGTM

**Comment by stephentoub** [comment]
> As described in the issue, I get a Diagnostic on the bitwise-or-operator.

Anyone can issue a diagnostic for anything; that doesn't mean it demands a change just to silence that diagnostic on your system.

> and it doesn't hurt anyone

It increases the size of the assembly. It's a tiny increase, so if there was a usability, correctness, performance, debugging, etc benefit, it'd be worthwhile. But there isn't here. 

I appreciate the efforts here, but I'm going to close both this PR and the issue.

Thanks.

**Comment by jkotas** [comment]
The other definition is in NativeAOT part. It is fine to deduplicate these enums. The deduplicated definition should be placed under `src/coreclr/System.Private.CoreLib/src/System`

> It increases the size of the assembly. 

This does not need to be enum at all. It can be just a holder type for constants that gets completely stripped by the unused metadata trimming. 
```
class GC
{
     const int GC_ALLOC_NO_FLAGS = 0; 
     const int GC_ALLOC_ZEROING_OPTIONAL = 16;
     const int GC_ALLOC_PINNED_OBJECT_HEAP = 64; 
}
```

We use this technique in number of places under src/libraries/common/src/interop`

**Comment by deeprobin** [comment]
> > merging the same enums into a central location
> 
> What are you referring to? I see this one definition in C#:
> 
> https://github.com/dotnet/runtime/blob/385fc8832b1d4160abe13645054b65458b6a12f8/src/coreclr/System.Private.CoreLib/src/System/GC.cs#L87-L93
> 
> Where else is this enum defined in C#?

I thought I remembered that there was something in `GC.CoreRT.cs`. But it seems like am wrong.

With `git grep "enum GC_ALLOC_FLAGS"` which definitely works better than the GitHub search, I only found 2 definitions:

https://github.com/dotnet/runtime/blob/1c927462696f5af7d5e667f54b1c39452cba4b2d/src/coreclr/System.Private.CoreLib/src/System/GC.cs#L87-L93

https://github.com/dotnet/runtime/blob/b2dc37ba181a7fa4427e717eab819ba3543d0ae4/src/coreclr/tools/Common/Internal/Runtime/RuntimeConstants.cs#L47-L53

I am currently undecided if we have any shared project for CLR-Tools code and the S.P.CoreLib where this could be added.

Since this is only tools code it will not reduce the assembly size for the user, but code duplication should still be avoided in my opinion.

Maybe we could put this under libraries/Common?

**Comment by deeprobin** [comment]
One advantage of merging would be, for example, that we only have to adjust one definition in gcinterface.h for updates.

**Comment by jkotas** [comment]
> I am currently undecided if we have any shared project for CLR-Tools code 

This enum should not be in tools in the first place. It has nothing to do with tools.

**Comment by jkotas** [comment]
> Maybe we could put this under libraries/Common?

This enum can only ever be used by CoreLib in combination with CoreCLR GC, so libraries/Common is too broad for it. It should be either `src/coreclr/System.Private.CoreLib` if we believe that it is CoreCLR specific (it is the case today) or `src/libraries/System.Private.CoreLib` if we believe that Mono may start using it at some point too.

**Pull request closed without merging**
