### PR TITLE
[wasm][debugger] Show actual data for boxed values

### LINKED ISSUE #41846: [wasm][debugger] Show actual values for boxed `object`s
`object o = 5;`

debugger shows this as `object`, and you can't inspect the value

### PR DESCRIPTION
**Pull request by radical**
Eg. `object o = "foobar"`

This will show the string `"foobar"`, instead of an object, in the
debugger.

Fixes https://github.com/dotnet/runtime/issues/41846

### CODE REVIEW

**Comment by radical** [comment]
This is based on #41559 . The additional commit for this PR: https://github.com/dotnet/runtime/commit/588090d9a06015a2133d9d360f2aae1a6d4f0c9c

**Comment by radical** [comment]
rebased on https://github.com/mono/mono/pull/20318 .

**Comment by radical** [comment]
Rebased on master now.

**Review by lewing — APPROVED** [review]
Looks good

**Pull request merged**
