### PR TITLE
ILASM - Disable `fileversionpreservation` test

### PR DESCRIPTION
**Pull request by TIHan**
Should stop this from failing for now: https://github.com/dotnet/runtime/issues/71919

ILASM does not support embedding or generating resource data; we would need to add that functionality. It used to exist, but it depended on `CvtRes.exe` which the dotnet team does not own; which is the reason the resource embedding support was removed. See https://github.com/dotnet/coreclr/pull/20818 and https://github.com/dotnet/runtime/issues/11412

### CODE REVIEW

**Comment by TIHan** [comment]
@dotnet/jit-contrib ready for review

**Review by BruceForstall — CHANGES_REQUESTED** [review]
You're disabling it for all configurations. You only need to disable it for ilasm round-trip testing.

Use `IlasmRoundTripIncompatible`. See https://github.com/dotnet/runtime/blob/main/docs/workflow/ci/disabling-tests.md and other test examples that use this.

Is this test failure happening now because the recent changes mean we're actually (finally) running the round-tripped dll?

**Comment by TIHan** [comment]
> Is this test failure happening now because the recent changes mean we're actually (finally) running the round-tripped dll?
Yes.

I'll correctly disable the test.

**Comment by TIHan** [comment]
@dotnet/jit-contrib ready for review again. I used `<IlasmRoundTripIncompatible>true</IlasmRoundTripIncompatible>` to disable the roundtrip tests only.

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
