### PR TITLE
ARM64: Optimize Volatile.Read/Write for floats

### LINKED ISSUE #67254: [arm64] JIT: Volatile.Write emits full memory barrier for floats
```csharp
double _location = 0;
double _newValue = 1;

void Write_double() => 
    Volatile.Write(ref _location, _newValue);
```
Currently emits a full memory barrier on arm64:
```asm
        A9BF7BFD          stp     fp, lr, [sp,#-16]!
        910003FD          mov     fp, sp
G_M10964_IG02:
        91002001          add     x1, x0, #8
        FD400810          ldr     d16, [x0,#16]
        D5033BBF          dmb     ish  ;;  <--- 
        FD000030          str     d16, [x1]
G_M10964_IG03:
        A8C17BFD          ldp     fp, lr, [sp],#16
        D65F03C0          ret     lr
```
Expected - use stlr + fmov

category:cq
theme:volatile

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/67254

This PR eliminates explicit full/load memory barriers for loads and stores for floating points. Example:

```cs
double _location = 0;

double Read() => Volatile.Read(ref _location);
void Write(double val) => Volatile.Write(ref _location, val);
```

```diff
; Method Tests:Read():double:this (FullOpts)
            stp     fp, lr, [sp, #-0x10]!
            mov     fp, sp
            add     x0, x0, #8
-           ldr     d0, [x0]
-           dmb     ishld
+           ldar    x0, [x0]
+           fmov    d0, x0
            ldp     fp, lr, [sp], #0x10
            ret     lr
; Total bytes of code: 28


; Method Tests:Write(double):this (FullOpts)
            stp     fp, lr, [sp, #-0x10]!
            mov     fp, sp
            add     x0, x0, #8
-           dmb     ish
-           str     d0, [x0]
+           mov     x1, v0.d[0]
+           stlr    x1, [x0]
            ldp     fp, lr, [sp], #0x10
            ret     lr
; Total bytes of code: 28
```

### CODE REVIEW

**Comment by EgorBo** [comment]
PTAL @kunalspathak @VSadov @dotnet/jit-contrib 

Mostly text diffs since the codegen size is the same. A couple of regressions because `ldr + dmb` can encode addressing modes, but when we switch to `ldapr` - we no longer can contain it, we can do it only with armv8.4 LDAPUR, but our SPMI collections don't have this ISA

**Comment by EgorBo** [comment]
ping @kunalspathak @TIHan

**Comment by kunalspathak** [comment]
Not sure if I understand this...in the asmdiff above, we are loading/storing `int` value instead of `float` value?

> 
```
-           ldr     d0, [x0]
-           dmb     ishld
+           ldar    x0, [x0]
+           fmov    d0, x0
```

**Comment by EgorBo** [comment]
Native compiles use the same trick, e.g.: https://godbolt.org/z/KKTh79xbc

**Review by kunalspathak — APPROVED** [review]
LGTM

**Review by VSadov — APPROVED** [review]
Interesting! LGTM.

**Comment by EgorBo** [comment]
Improvements:

- https://github.com/dotnet/perf-autofiling-issues/issues/34053

**Pull request merged**
