### PR TITLE
gc: shorten background thread name to fit Linux name limit

### PR DESCRIPTION
**Pull request by tmds**

### CODE REVIEW

**Comment by tmds** [comment]
This changes the effective thread names on Linux from `.NET Background` to `.NET Backgr GC`.

**Comment by Maoni0** [comment]
can you please use "BGC" instead of "Backgr GC"? 😄

**Comment by tmds** [comment]
> can you please use "BGC" instead of "Backgr GC"?

#done

**Review by Maoni0 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
