### PR TITLE
Allow trimming FeatureGuard and FeatureSwitchDefinition attributes

### LINKED ISSUE #100256: [android] trimmer warning for `System.Private.CoreLib.dll`
### Description

This appeared here:
* https://github.com/xamarin/xamarin-android/pull/8828

```
dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.android-x86\9.0.0-preview.4.24173.6\runtimes\android-x86\native\System.Private.CoreLib.dll : warning IL2104: Assembly 'System.Private.CoreLib' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries 
```

`-p:TrimmerSingleWarn=false` yields additional information:
```
ILLink warning IL2045: System.Runtime.CompilerServices.RuntimeFeature.IsDynamicCodeCompiled: Attribute 'System.Diagnostics.CodeAnalysis.RequiresDynamicCodeAttribute' is being referenced in code but the trimmer was instructed to remove all instances of this attribute. If the attribute instances are necessary make sure to either remove the trimmer attribute XML portion which removes the attribute instances, or override the removal by using the trimmer XML descriptor to keep the attribute type (which in turn keeps all of its instances).
```

### Reproduction Steps

* `dotnet new android`
* `dotnet build`

Add `-p:TrimmerSingleWarn=false` to get a more detailed warning.

### Expected behavior

No trimmer warnings.

### Actual behavior

Trimmer warning about `System.Private.CoreLib.dll`.

### Regression?

Yes

### Known Workarounds

I suppose you could set `-p:SuppressTrimAnalysisWarnings=true`, but that is not ideal.

### Configuration

.NET SDK: 9.0.100-preview.4.24175.5
.NET Runtime 9.0.0-preview.4.24173.6: https://github.com/dotnet/runtime/compare/596a1f7b64...17f8138a72

### Other information

_No response_

### PR DESCRIPTION
**Pull request by sbomer**
Under AggressiveAttributeTrimming setting.

Fixes https://github.com/dotnet/runtime/issues/100256. AggressiveAttributeTrimming was attempting to remove RequiresDynamicCode attributes, but the type was still referenced by FeatureGuardAttribute:

https://github.com/dotnet/runtime/blob/dc553fe5e0b931f4d6fd481a0ba270bde644a19d/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/RuntimeFeature.NonNativeAot.cs#L19-L20

Adding FeatureGuardAttribute to the set of attributes that get removed with AggressiveAttributeTrimming fixes this. Also adding FeatureSwitchDefinitionAttribute because that one can be removed as well.

### CODE REVIEW

**Comment by eerhardt** [comment]
Can we add a test? Since it seems to have broken an upstream user.

**Review by eerhardt — APPROVED** [review]
LGTM

**Review by jtschuster — APPROVED** [review]
Do we have trimmer cases in illink.sln that use AggressiveAttributeTrimming? I would have expected this to be caught by the ILVerify validation in the linker tests if we do.

**Comment by vitek-karas** [comment]
> AggressiveAttributeTrimming is a runtime-defined feature setting, not something built-in to ILLink. ILLink does have tests for attribute removal based on feature settings in general.

I think the idea is to add a simple executable test (just like we do for other parts of libraries with regard to trimming) which would turn on aggressive attribute trimming and validate that the attributes are in fact removed.

**Pull request merged**
