### PR TITLE
Add reciprocal and SinCos methods to IFloatingPoint

### LINKED ISSUE #58607: Add reciprocal and SinCos methods to IFloatingPoint
# Background and Motivation
Suggestion for the generic math. The mentioned methods are available in Math and MathF classes. I think it would be nice to add these to the IFloatingPoint interface.

# Proposed API
```diff
namespace System
{
    public interface IFloatingPoint<TSelf>
    {
...
+        (TSelf, TSelf) SinCos(TSelf x);
+        TSelf ReciprocalEstimate(TSelf x);
+        TSelf ReciprocalSqrtEstimate(TSelf x);
...
    }
}
```

Oops forgot to add api suggestion label...

### PR DESCRIPTION
**Pull request by i3arnon**
Fix #58607

### CODE REVIEW

**Comment by tannergooding** [comment]
@i3arnon are you still working on this?

No particular rush, just wanted to ensure that was the case since many people took a break over the holidays. There are still pending comments above that would need to be resolved.

**Comment by i3arnon** [comment]
@tannergooding I solved the conflicts. Sorry for the delay..

**Comment by tannergooding** [comment]
Sorry for the delay. This was blocked/delayed while we worked through various other issues involving generic math and prepping it for .NET 7.

All those issues have now been resolved and we can merge this.

There are, unfortunately, some more conflicts. These are a side effect of other PRs also being unblocked and the interfaces now being "implicitly", rather than "explicitly", implemented.

If you're otherwise busy, I can push up fixes for the conflicts here.

**Comment by i3arnon** [comment]
@tannergooding I fixed the conflicts.

**Review by tannergooding — APPROVED** [review]

**Comment by danmoseley** [comment]
Thanks @i3arnon

**Pull request merged**
