### PR TITLE
Fix time-of-use vs. time-of-check "bugs"

### PR DESCRIPTION
**Pull request by kokke**
This PR fixes a few minor time-of-use vs time-of-check "bugs" where a pointer is checked against NULL, but after it has already been dereferenced.

The format is something similar to this

```C
int x = strlen(p); /* strlen() dereferences pointer p */
...
assert(p != NULL); /* check if p != NULL */
```

These "bugs" are found with a home-made static analysis tool, that flags places in code, where pointers are checked against NULL but have already been dereferenced. The rationale is this: A dereference indicates that the programmer thinks the pointer is != NULL, but the NULL-check indicates the opposite.

---

#### 1) Time of check vs time of use problem in [src/mono/mono/utils/mono-value-hash.c](https://github.com/dotnet/runtime/blob/main/src/mono/mono/utils/mono-value-hash.c#L226)

The pointer 'hash' is checked against NULL (at line 226), but after it has been dereferenced (at line 224). 

See comments below lines 224 + 226 in the code below:

```c
212    static void
213    mono_value_hash_table_insert_replace (MonoValueHashTable *hash, gpointer key, gpointer value, gboolean replace)
214    {
215        guint hashcode;
216        Slot *s;
217        guint s_index;
218        GEqualFunc equal;
219        guint first_tombstone = 0;
220        gboolean have_tombstone = FALSE;
221        guint step = 0;
222 
223        g_assert (value);
224        g_assert (hash->key_extract_func (value) == key);
                     ^^^^^^^^^^^^^^^^^^^^^^ 'hash' gets dereferenced here
225 
226        g_return_if_fail (hash != NULL);
                             ^^^^^^^^^^^^ 'hash' checked against NULL but was dereferenced above
```

The suggested solution is to do the null-check before dereferencing hash:

```C
223    g_assert (value);
224    g_return_if_fail (hash != NULL); /* check if hash != NULL before dereferencing */
225    g_assert (hash->key_extract_func (value) == key);
226
227    hashcode = HASH (hash, key);
```

---

#### 2) Time of check vs time of use problem in [src/coreclr/debug/di/divalue.cpp](https://github.com/dotnet/runtime/blob/main/src/coreclr/debug/di/divalue.cpp#L215).

**EDIT:** See my post (further below this one) for a revised solution to this issue

The pointer 'pAppDomain' is checked against NULL at line 215, but was already dereferenced at line 211

```cpp
211    INTERNAL_SYNC_API_ENTRY(pAppdomain->GetProcess()); //
                               ^^^^^^^^^^^^^^^^^^^^^^^^ 'pAppdomain' gets dereferenced here
212
213    // We'd really hope that our callers give us a valid appdomain, but in case
214    // they don't, we'll fail gracefully.
215    if ((pAppdomain != NULL) && pAppdomain->IsNeutered())
            ^^^^^^^^^^^^^^^^^^ 'pAppDomain' checked against NULL, but was already dereferenced above at line 211
216    {
217        STRESS_LOG1(LF_CORDB, LL_EVERYTHING, "CVBT using neutered AP, %p\n", pAppdomain);
218        ThrowHR(E_INVALIDARG);
219    }
```

As far as I can tell (from googling), the macro INTERNAL_SYNC_API_ENTRY is defined like this:

```cpp
#define INTERNAL_SYNC_API_ENTRY(pProc)  \
    CordbProcess * __pProc = (pProc); \
    _ASSERTE(__pProc->GetStopGoLock()->HasLock() || !"Must have stop go lock for internal-sync-api"); \
    InternalAPIHolder __pah; __pah.dummy();
```

Suggestion: check if 'pAppDomain != NULL' before dereferencing the pointer. E.g. by moving the if-statement at line 215 up to 211. Like this:

```cpp
211    // We'd really hope that our callers give us a valid appdomain, but in case
212    // they don't, we'll fail gracefully.
213    if ((pAppdomain != NULL) && pAppdomain->IsNeutered())
214    {
215        STRESS_LOG1(LF_CORDB, LL_EVERYTHING, "CVBT using neutered AP, %p\n", pAppdomain);
216        ThrowHR(E_INVALIDARG);
217    }
218
219    INTERNAL_SYNC_API_ENTRY(pAppdomain->GetProcess());
```

---

#### 3) Time of check vs time of use problem in [src/coreclr/debug/di/rsstackwalk.cpp](https://github.com/dotnet/runtime/blob/main/src/coreclr/debug/di/rsstackwalk.cpp#L662)

Time-of-check vs time-of-use bug in src/coreclr/debug/di/rsstackwalk.cpp

Line 662 checks the pointers 'pFunction' + 'pNativecode' against NULL but they were already dereferenced at that point. 

See comments below line 648 + 658:

```cpp
645        IfFailThrow(hr);
646
647        // The native code object will create the function object if needed
648        CordbFunction * pFunction = pNativeCode->GetFunction();
                                       ^^^^^^^^^^^ 'pNativeCode' gets dereferenced here
649
650        // A CordbFunction is theoretically the uninstantiated method, yet for back-compat we allow
651        // debuggers to assume that it corresponds to exactly 1 native code blob. In order for
652        // an open generic function to know what native code to give back, we attach an arbitrary
653        // native code that we located through code inspection.
654        // Note that not all CordbFunction objects get created via stack traces because you can also
655        // create them by name. In that case you still won't get code for Open generic functions
656        // because we will never have attached one and the lookup by token is insufficient. This
657        // behavior mimics our 2.0 debugging behavior though so its not a regression.
658        pFunction->NotifyCodeCreated(pNativeCode);
          ^^^^^^^^^^^^ 'pFunction' gets dereferenced here
659
660        IfFailThrow(hr);
661
662        _ASSERTE((pFunction != NULL) && (pNativeCode != NULL));
                    ^^^^^^^^^^^^^^^^^^^ 'pFunction' checked against NULL, but was already dereferenced
```

Suggested solution: Check the pointers before dereferencing them, so the code becomes something like this:

```C
647        _ASSERTE(pNativeCode != NULL);
648
649        // The native code object will create the function object if needed
650        CordbFunction * pFunction = pNativeCode->GetFunction();
651
652        _ASSERTE(pFunction != NULL);
```

---

#### 4) Unnecessary/superfluous NULL-check in [src/coreclr/debug/di/process.cpp](https://github.com/dotnet/runtime/blob/main/src/coreclr/debug/di/process.cpp#L5210)

The pointer 'pClass' is checked against NULL, but is dereferenced twice before the check.
If 'pClass' could be == NULL, the code would crash before the check.

```cpp
5188            hr = pModule->LookupOrCreateClass(pEvent->LoadClass.classMetadataToken, &pClass);
5189            _ASSERTE(SUCCEEDED(hr) == (pClass != NULL));
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ check that 'pClass != NULL'
5190            IfFailThrow(hr);
5191
5192            // Prevent class load from being sent twice.
5193            // @dbgtodo - Microsoft, cordbclass: this is legacy. Can this really happen? Investigate as we dac-ize CordbClass.
5194            if (pClass->LoadEventSent())
                    ^^^^^^^^^^^^^^^^^^^^^^^ dereferences 'pClass' here -> fact: 'pClass != NULL' otherwise code would crash here
5195            {
5196                // Dynamic modules are dynamic at the module level -
5197                // you can't add a new version of a class once the module
5198                // is baked.
5199                // EnC adds completely new classes.
5200                // There shouldn't be any other way to send multiple
5201                // ClassLoad events.
5202                // Except that there are race conditions between loading
5203                // an appdomain, and loading a class, so if we get the extra
5204                // class load, we should ignore it.
5205                break; //out of the switch statement
5206            }
5207            pClass->SetLoadEventSent(TRUE);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ dereferences 'pClass' here -> fact: 'pClass != NULL' otherwise code would crash here
5208
5209
5210            if (pClass != NULL)
                    ^^^^^^^^^^^^^^ 'pClass == NULL' impossible here -> would have SEGFAULT'ed at line 5207 or 5194
5211            {
5212                PUBLIC_CALLBACK_IN_THIS_SCOPE(this, pLockHolder, pEvent);
5213                pCallback1->LoadClass(pAppDomain, pClass);
5214            }
```

Suggestion: Remove the NULL-check (as it seems superfluous), so the code becomes like this:

```cpp
5209
5210            PUBLIC_CALLBACK_IN_THIS_SCOPE(this, pLockHolder, pEvent);
5211            pCallback1->LoadClass(pAppDomain, pClass);
5212    }
```

### CODE REVIEW

**Review by lambdageek — COMMENTED** [review]
Mono change LGTM

**Comment by kokke** [comment]
I revised the approach for problem 2 (src/coreclr/debug/di/divalue.cpp) and instead removed the NULL-check in the if-statement (line 211)

So that this line of code:
```C
215    if ((pAppdomain != NULL) && pAppdomain->IsNeutered())
```

... becomes this line of code

```C
215    if (pAppdomain->IsNeutered())
```

with the reasoning that line 211 already dereferences the pointer

```C
211    INTERNAL_SYNC_API_ENTRY(pAppdomain->GetProcess()); //
                               ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by kokke** [comment]
Any updates on this? Anything I need to change/improve?

All tests were green before I pulled from main again : https://github.com/dotnet/runtime/pull/60860/commits/eaf63c88f7e9e5431f770a50eb5e98ed07f7d4e8

**Comment by tommcdon** [comment]
@kokke thank you for analyzing the code base to find cases where we have misplaced asserts or null checks.  My first suggestion is to split the coreclr debugger changes from the mono ones as the fixes are in different areas of the runtime.  It sounds like @lambdageek has already reviewed the mono portion of the change, and so it is possible it will be approved separately from the rest of the changes in this PR.  

For the coreclr debugger changes:
> 2) Time of check vs time of use problem in src/coreclr/debug/di/divalue.cpp.

I agree the existing null check occurring after pAppDomain->GetProcess is not adding value.  However, before removing the null check on line 215, we should carefully analyze the callers to the function to ensure that pAppDomain can never be null.   If we should add a null check, we should determine the proper error code to return and verify that all callers handle the error condition correctly.

> 3) Time of check vs time of use problem in src/coreclr/debug/di/rsstackwalk.cpp

This is similar to the above.  We should carefully analyze the function and callers to the function to determine if the variables we are checking can ever be null.  The assert is likely not adding a lot of value as it only compiles into the function on debug builds of the runtime, and so the real issue here is to verify that we are correctly checking the state of the variables and returning the right error codes, and ensuring that callers handle the errors appropriately.    

> 4) Unnecessary/superfluous NULL-check in src/coreclr/debug/di/process.cpp

Similar to 2 and 3 above.  We should first ensure that the null check is actually superfluous before removing it.  This entails analyzing the callers and the function itself. 

The analysis listed above might be time consuming.  I suggest that we open an issue to track the work listed above and close this PR until the analysis is completed.  Please let me know how you would like to proceed.

**Comment by kokke** [comment]
hi @tommcdon and thanks for taking the time to thoroughly comment :)

> Please let me know how you would like to proceed.

I will do as you propose and split up the cases in several PRs. This one can then be closed, and I can reference or copy/paste from it in each case :)

I agree with your assessment of the assertion-cases in 2-4 and they are indeed minuscule "defects". I am not sure I have the chops to analyze them further. But I could open an issue with the info stated here. Would that be meaningful you think?

**Comment by tommcdon** [comment]
> I could open an issue with the info stated here. Would that be meaningful you think?

Yes, that sounds reasonable to me.  Thank you!

**Comment by tommcdon** [comment]
Hi @kokke! To summarize the plan:
1. Close this PR
2. Open a new PR for the mono change
3. Create issues tracking the inconsistent asserts and superfluous variable checks in the debugger API
Do you have any objections if we close this PR now assuming that you will be following up with 2 and 3?

**Comment by tommcdon** [comment]
Closing this PR per our discussion above

**Pull request closed without merging**
