### PR TITLE
Fix silent failure of coreroot_determinism test

### PR DESCRIPTION
**Pull request by nattress**
* Check the exit code from SuperIlc child process and fail the test if non-zero

@dotnet/crossgen-contrib

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
The failures on Windows and Linux are some of the silent failures I was talking about. From what I can tell, this test hasn’t run correctly in CI for quite a while if ever.

**Comment by jkoritzinsky** [comment]
@nattress to unblock the global.json upgrade, can we disable the coreroot_determinism test for now and open an issue to get it running correctly in CI since it currently isn't running correctly today? The global.json upgrade is blocking a few other PRs at the moment.

**Comment by nattress** [comment]
Sure I'll submit a PR to disable and open an issue. I've been trying to fix the test up today and its problems go deeper.

**Comment by nattress** [comment]
@jkoritzinsky I ended up having to re-work this test a bit. First, I switched SuperIlc to be a self-contained (IL trimmed) published app so we can reliably run it on CI machines. I also fixed a bunch of bugs in the test itself and reduced the set of assemblies it tests against to just CoreLib since it's very slow to process all framework assemblies. I will look at adding crossgen2 determinism coverage for all framework assemblies to an outer loop run.

**Comment by jkoritzinsky** [comment]
The change to self-contained publish will conflict with #31701. Is it possible to make it run against Core_Root? Alternatively, if we need to pull down a version of the runtime on Helix machines, I’m ok with doing that as well. Helix has built-in support for that.

**Comment by nattress** [comment]
Ok I reverted the publish and now we just corerun ReadyToRun.SuperIlc.dll. I take it I can assume corerun[.exe] will continue to exist on the test VMs?

**Comment by jkoritzinsky** [comment]
Yep! CoreRun will continue to be available.

**Pull request merged**
