### PR TITLE
Update constant prop to only consider certain hwintrinsics

### LINKED ISSUE #97046: (Performance) Simd vector loaded from memory instead of register multiple times
Version: dotnet 8.0.100

Consider this code fragment

```C#
  private static Vector128<byte> Test()
  {
    var Permute = Vector128.Create(0, 4, 8, 12, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF);
    var Clone   = Permute; // making a copy doesn't help, using Permute or Clone in the next expression makes no difference

    return 
      SimdRotateRight(Clone, 0 * 4) |
      SimdRotateRight(Clone, 3 * 4) |
      SimdRotateRight(Clone, 2 * 4) |
      SimdRotateRight(Clone, 1 * 4);
  }
```

 with a helper

```C#
  [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)]
  private static Vector128<byte> SimdRotateRight(Vector128<byte> value, [ConstantExpected] byte control) => control == 0 ? value : Ssse3.AlignRight(value, value, control);
```

this generates the following code:

```ASM
; Method Decima.Core.Formats.Texture.BC6S:Test():System.Runtime.Intrinsics.Vector128`1[ubyte] (FullOpts)
G_M000_IG01:                ;; offset=0x0000

G_M000_IG02:                ;; offset=0x0000
       movups   xmm0, xmmword ptr [reloc @RWD00]
       movups   xmm1, xmmword ptr [reloc @RWD00]
       palignr  xmm0, xmm1, 12
       por      xmm0, xmm1
       movups   xmm2, xmmword ptr [reloc @RWD00]
       palignr  xmm1, xmm2, 8
       por      xmm0, xmm1
       movups   xmm1, xmmword ptr [reloc @RWD00]
       palignr  xmm2, xmm1, 4
       por      xmm0, xmm2
       movups   xmmword ptr [rcx], xmm0
       mov      rax, rcx

G_M000_IG03:                ;; offset=0x0040
       ret      
RWD00  	dq	FFFFFFFF0C080400h, FFFFFFFFFFFFFFFFh
; Total bytes of code: 65
```

This results in way too many memory load operations, on top with a bad `movups`, which disallows the second memory load unit in Zen. RWD00 should be aligned. Why not `movaps`?

I tried to use a "clone" variable but that gets "optimized" away. The memory vector should be cached as a register, and loaded only once.

I have similar code and this just generates so much pressure on the memory load unit. Any way to fix/improve this?

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/97046 by updating constant prop of a `LclVar` into a `HWIntrinsic` node to only happen if the constant can actually be consumed directly.

`HWIntrinsic` nodes are special in many ways and the number of transforms/optimizations we do to them is incredibly limited. Outside of some minimal constant folding done in `ValueNum` and some minor transforms done in `Morph`, these nodes are effectively left alone until lowering. So by only propagating constants into them when we know that another phase might be able to take advantage of it, we can significantly improve the codegen in cases where a user has manually CSE'd such a constant themselves.

### Before

```asm
; Method Program:Test():System.Runtime.Intrinsics.Vector128`1[ubyte] (FullOpts)
G_M000_IG01:                ;; offset=0x0000
       vzeroupper 

G_M000_IG02:                ;; offset=0x0003
       vmovups  xmm0, xmmword ptr [reloc @RWD00]
       vpalignr xmm0, xmm0, xmmword ptr [reloc @RWD00], 12
       vpor     xmm0, xmm0, xmmword ptr [reloc @RWD00]
       vmovups  xmm1, xmmword ptr [reloc @RWD00]
       vpalignr xmm1, xmm1, xmmword ptr [reloc @RWD00], 8
       vpor     xmm0, xmm0, xmm1
       vmovups  xmm1, xmmword ptr [reloc @RWD00]
       vpalignr xmm1, xmm1, xmmword ptr [reloc @RWD00], 4
       vpor     xmm0, xmm0, xmm1
       vmovups  xmmword ptr [rcx], xmm0
       mov      rax, rcx

G_M000_IG03:                ;; offset=0x0050
       ret      
RWD00  	dq	FFFFFFFF0C080400h, FFFFFFFFFFFFFFFFh
; Total bytes of code: 81
```

### After

```asm
; Method Program:Test():System.Runtime.Intrinsics.Vector128`1[ubyte] (FullOpts)
G_M18664_IG01:  ;; offset=0x0000
       vzeroupper 
						;; size=3 bbWeight=1 PerfScore 1.00

G_M18664_IG02:  ;; offset=0x0003
       vmovups  xmm0, xmmword ptr [reloc @RWD00]
       vpalignr xmm1, xmm0, xmm0, 12
       vpalignr xmm2, xmm0, xmm0, 8
       vmovaps  xmm3, xmm0
       vpternlogd xmm3, xmm1, xmm2, -2
       vpalignr xmm0, xmm0, xmm0, 4
       vpor     xmm0, xmm3, xmm0
       vmovups  xmmword ptr [rcx], xmm0
       mov      rax, rcx
						;; size=48 bbWeight=1 PerfScore 9.33

G_M18664_IG03:  ;; offset=0x0033
       ret      
						;; size=1 bbWeight=1 PerfScore 1.00
RWD00  	dq	FFFFFFFF0C080400h, FFFFFFFFFFFFFFFFh
; Total bytes of code: 52
```

### CODE REVIEW

**Comment by tannergooding** [comment]
This also allows a workaround for cases like https://github.com/dotnet/runtime/issues/76067, as the user can manually hoist `zero` into a local, such as:
```csharp
var byteVector = Vector256.LoadUnsafe<byte>(ref spanRef);

var zero = Vector256<short>.Zero;

var low = Avx2.UnpackLow(byteVector, zero.AsByte());
var high = Avx2.UnpackHigh(byteVector, zero.AsByte());

var added = Avx2.Add(low.AsInt16(), high.AsInt16());

added = Avx2.HorizontalAdd(added, zero);
added = Avx2.HorizontalAdd(added, zero);
return Avx2.HorizontalAdd(added, zero);
```

which generates:
```asm
; Method Program:Test2(byref):System.Runtime.Intrinsics.Vector256`1[short] (FullOpts)
G_M36983_IG01:  ;; offset=0x0000
       vzeroupper 
						;; size=3 bbWeight=1 PerfScore 1.00

G_M36983_IG02:  ;; offset=0x0003
       vxorps   ymm0, ymm0, ymm0
       vmovups  ymm1, ymmword ptr [rdx]
       vpunpcklbw ymm2, ymm1, ymm0
       vpunpckhbw ymm1, ymm1, ymm0
       vpaddw   ymm1, ymm2, ymm1
       vphaddw  ymm1, ymm1, ymm0
       vphaddw  ymm1, ymm1, ymm0
       vphaddw  ymm0, ymm1, ymm0
       vmovups  ymmword ptr [rcx], ymm0
       mov      rax, rcx
						;; size=42 bbWeight=1 PerfScore 15.92

G_M36983_IG03:  ;; offset=0x002D
       vzeroupper 
       ret      
						;; size=4 bbWeight=1 PerfScore 2.00
; Total bytes of code: 49
```

It may also open the opportunity to decide to CSE `Vector<T>.Zero` and then just simply let constant prop determine if the CSE is beneficial or not.

**Comment by tannergooding** [comment]
CC. @dotnet/jit-contrib 

Diffs show a good number of wins, especially in the hot parts of code due to the reused constants being hoisted. There are, however, notably some regressions. This appears to be mostly just caused due to different register selection causing small (but execution wise cheaper) regressions.

I think overall this is a net win for users in typical SIMD code (excepting when a call exists) and the remaining issues are known general cases that exist for all SIMD code.

### Improvements

For example on Arm64:
```diff
-            sub     v20.16b, v16.16b, v20.16b
-            ldr     q21, [@RWD00]
-            sub     v21.16b, v17.16b, v21.16b
-            ldr     q22, [@RWD00]
-            sub     v22.16b, v18.16b, v22.16b
-            ldr     q23, [@RWD00]
-            sub     v23.16b, v19.16b, v23.16b
-            ldr     q24, [@RWD16]
-            cmgt    v20.16b, v24.16b, v20.16b
-            ldr     q24, [@RWD16]
-            cmgt    v21.16b, v24.16b, v21.16b
-            ldr     q24, [@RWD16]
-            cmgt    v22.16b, v24.16b, v22.16b
-            ldr     q24, [@RWD16]
-            cmgt    v23.16b, v24.16b, v23.16b
-            ldr     q24, [@RWD32]
-            and     v20.16b, v20.16b, v24.16b
-            ldr     q24, [@RWD32]
-            and     v21.16b, v21.16b, v24.16b
-            ldr     q24, [@RWD32]
-            and     v22.16b, v22.16b, v24.16b
-            ldr     q24, [@RWD32]
-            and     v23.16b, v23.16b, v24.16b
-            eor     v16.16b, v16.16b, v20.16b
-            eor     v17.16b, v17.16b, v21.16b
-            eor     v18.16b, v18.16b, v22.16b
-            eor     v19.16b, v19.16b, v23.16b
+            ldr     q21, [@RWD16]
+            ldr     q22, [@RWD32]
+            sub     v23.16b, v16.16b, v20.16b
+            sub     v24.16b, v17.16b, v20.16b
+            sub     v25.16b, v18.16b, v20.16b
+            sub     v20.16b, v19.16b, v20.16b
+            cmgt    v23.16b, v21.16b, v23.16b
+            cmgt    v24.16b, v21.16b, v24.16b
+            cmgt    v25.16b, v21.16b, v25.16b
+            cmgt    v20.16b, v21.16b, v20.16b
+            and     v21.16b, v23.16b, v22.16b
+            and     v23.16b, v24.16b, v22.16b
+            and     v24.16b, v25.16b, v22.16b
+            and     v20.16b, v20.16b, v22.16b
+            eor     v16.16b, v16.16b, v21.16b
+            eor     v17.16b, v17.16b, v23.16b
+            eor     v18.16b, v18.16b, v24.16b
+            eor     v19.16b, v19.16b, v20.16b
```

or on x64:
```diff
       vpclmulqdq xmm4, xmm0, xmmword ptr [reloc @RWD16], 17
-       vpclmulqdq xmm0, xmm0, xmmword ptr [reloc @RWD16], 0
-       vpternlogq xmm1, xmm4, xmm0, -106
+       vmovups  xmm4, xmmword ptr [reloc @RWD16]
+       vpclmulqdq xmm5, xmm0, xmm4, 17
+       vpclmulqdq xmm0, xmm0, xmm4, 0
+       vpternlogq xmm1, xmm5, xmm0, -106
        vmovaps  xmm0, xmm1
-       vpclmulqdq xmm1, xmm0, xmmword ptr [reloc @RWD16], 17
-       vpclmulqdq xmm0, xmm0, xmmword ptr [reloc @RWD16], 0
+       vpclmulqdq xmm1, xmm0, xmm4, 17
+       vpclmulqdq xmm0, xmm0, xmm4, 0
        vpternlogq xmm2, xmm1, xmm0, -106
        vmovaps  xmm0, xmm2
-       vpclmulqdq xmm1, xmm0, xmmword ptr [reloc @RWD16], 17
-       vpclmulqdq xmm0, xmm0, xmmword ptr [reloc @RWD16], 0
+       vpclmulqdq xmm1, xmm0, xmm4, 17
+       vpclmulqdq xmm0, xmm0, xmm4, 0
```

### Regressions

For example on Arm64 the register selection causes us to shuffle data around more (note the move sequence at the bottom where its moving `v1 into v0; v2 into v1, v3 into v2, and v0 into v3`):
```diff
-            umin    v0.8h, v1.8h, v0.8h
-            ldr     q1, [@RWD00]
+            umin    v1.8h, v1.8h, v0.8h
             ldr     q2, [fp, #0x30]   // [V27 tmp25]
-            umin    v1.8h, v2.8h, v1.8h
-            ldr     q2, [@RWD00]
+            umin    v0.8h, v2.8h, v0.8h
+            mov     v2.16b, v0.16b
+            ldr     q0, [@RWD00]
             ldr     q3, [fp, #0x20]    // [V28 tmp26]
-            umin    v2.8h, v3.8h, v2.8h
-            ldr     q3, [@RWD00]
+            umin    v3.8h, v3.8h, v0.8h
             ldr     q16, [fp, #0x10]  // [V29 tmp27]
-            umin    v3.8h, v16.8h, v3.8h
+            umin    v0.8h, v16.8h, v0.8h
+            mov     v16.16b, v0.16b
+            mov     v0.16b, v1.16b
+            mov     v1.16b, v2.16b
+            mov     v2.16b, v3.16b
+            mov     v3.16b, v16.16b
```

Similarly on x64 we have cases where we'll avoid propagating because we don't take into account `float`/`simd` values living across a call and the potential for an increased spill cost in some cases (this is a known and pre-existing issue): https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/assertionprop.cpp#L3066-L3068
```diff
+       vextractf128 xmm7, ymm6, 1
        call     [<unknown method>]
        ; gcr arg pop 0
-       vmovups  ymm0, ymmword ptr [rsp+0x40]
-       vaddpd   ymm0, ymm0, qword ptr [reloc @RWD08] {1to4}
-       vmovups  ymm1, ymmword ptr [reloc @RWD32]
-       vdivpd   ymm0, ymm1, ymm0
+       vinsertf128 ymm6, ymm6, xmm7, 1
+       vaddpd   ymm0, ymm6, ymmword ptr [rsp+0x40]
+       vdivpd   ymm0, ymm6, ymm0
```

**Comment by tannergooding** [comment]
Resolved merge conflict. This should still be ready-for-review.

**Review by AndyAyersMS — APPROVED** [review]
LGTM.

SSA use count can be an over-estimate, but that should only lead to missed opportunities to propagate, which seems fine.

**Pull request merged**
