### PR TITLE
Add `--reference-file` to ilverify

### PR DESCRIPTION
**Pull request by MichalPetryka**
Adds support for specifying references via a file to ilverify.

### CODE REVIEW

**Comment by JulieLeeMSFT** [comment]
@TIHan PTAL.

**Comment by jakobbotsch** [comment]
ILVerify already supports response files that can be used for this purpose, so I don't see much reason to have this.

**Comment by jkotas** [comment]
I agree with @jakobbotsch . What is going to produce this file? Can that thing produce the response file instead?

**Comment by MichalPetryka** [comment]
> I agree with @jakobbotsch . What is going to produce this file? Can that thing produce the response file instead?

I was originally gonna produce it from ReferencePath provided in msbuild tasks so I've opened a PR. We've later realised that ilverify supports rsp files, so the only reason for this would be consistency with the `--include-file` and `--ignore-error-file` options. If that's not wanted, I'll close this.

**Comment by jkotas** [comment]
`--include-file` and `--ignore-error-file` options follow atypical pattern. They are designed for situations where ILVerify is used as a test harness.

We use `-r/--reference` in AOT compilers and other tools. It is another angle on consistency. Response files worked fine so far. I think we can close this.

Note `-r` supports wildcards that is convenient when one needs to create the list of references from everything in given directory. For example, we use this in the "repro" project for aot compiler: https://github.com/dotnet/runtime/blob/9e9a3e902ba25613c873c0a7edbc60add86031d1/src/coreclr/tools/aot/ILCompiler/repro/repro.csproj#L22-L23 .

**Pull request closed without merging**
