### PR TITLE
[release/5.0-rc2] Support loading assemblies and symbols into debugger via callback

### PR DESCRIPTION
**Pull request by captainsafia**
Backport of #42255  to release/5.0-rc2

## Customer Impact

This PR introduces changes to support debugging lazily-loaded assemblies in WASM-based environments. This addresses feedback from customers about the lack of support for debugging lazily-loaded assemblies after we added support for lazy-loading in Blazor WASM.

## Testing

Validation for this change was done via:
- Automated unit testing (existing and new tests for feature)
- Manual validation of current debugging E2E in Blazor app

## Risk

**Low risk** because:

- Existing functionality that loaded debugging symbols when an app is initialized instead of during runtime is still in place
- Validation was done to ensure key scenarios did not regress

There is follow-up work to consume this change in the aspnetcore repo.

### CODE REVIEW

**Comment by mkArtakMSFT** [comment]
This was approved by Tactics.
@lewing please merge the other PR and then sign off on this one, so we don't break anything accidentally.

**Comment by mkArtakMSFT** [comment]
Marking this blocked on https://github.com/dotnet/runtime/pull/42407

**Comment by captainsafia** [comment]
Rebasing this now since the other PR was recently merged

**Review by lewing — APPROVED** [review]
helix tests failed because of  https://github.com/dotnet/core-eng/issues/10859 but this is a backport of master changes that have successfully passed CI

**Pull request merged**
