### PR TITLE
Add variable lifetime update for GT_STOREIND for arm/arm64

### LINKED ISSUE #45557: Process crash with "Internal CLR error" (0x80131506) in Roslyn CI
### Description

Roslyn CI failed with the following error:

https://dev.azure.com/dnceng/public/_build/results?buildId=906787&view=logs&j=7817cc08-46f6-529a-b675-9c2d2b016c0b&t=0fd245be-2f58-5546-b778-7c0bac845221&l=68

```
The active test run was aborted. Reason: Test host process crashed : Fatal error. Internal CLR error. (0x80131506)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(Int32, Int32, Boolean, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean, Boolean, Boolean)
   at System.Activator.CreateInstance[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]()
   at System.Threading.LazyInitializer.EnsureInitializedCore[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Microsoft.CodeAnalysis.Compilation.MarkImportDirectiveAsUsed(Microsoft.CodeAnalysis.SyntaxTree, Int32)
   at Microsoft.CodeAnalysis.Compilation.MarkImportDirectiveAsUsed(Microsoft.CodeAnalysis.SyntaxNode)
   at Microsoft.CodeAnalysis.CSharp.Imports.LookupSymbolInAliases(Microsoft.CodeAnalysis.CSharp.Binder, Microsoft.CodeAnalysis.CSharp.LookupResult, System.String, Int32, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol>, Microsoft.CodeAnalysis.CSharp.LookupOptions, Boolean, System.Collections.Generic.HashSet`1<Microsoft.CodeAnalysis.DiagnosticInfo> ByRef)
   at Microsoft.CodeAnalysis.CSharp.InContainerBinder.LookupSymbolsInSingleBinder(Microsoft.CodeAnalysis.CSharp.LookupResult, System.String, Int32, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol>, Microsoft.CodeAnalysis.CSharp.LookupOptions, Microsoft.CodeAnalysis.CSharp.Binder, Boolean, System.Collections.Generic.HashSet`1<Microsoft.CodeAnalysis.DiagnosticInfo> ByRef)
   at Microsoft.CodeAnalysis.CSharp.Binder.LookupSymbolsInternal(Microsoft.CodeAnalysis.CSharp.LookupResult, System.String, Int32, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol>, Microsoft.CodeAnalysis.CSharp.LookupOptions, Boolean, System.Collections.Generic.HashSet`1<Microsoft.CodeAnalysis.DiagnosticInfo> ByRef)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindNonGenericSimpleNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol>, Boolean, Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceOrTypeSymbol)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindNamespaceOrTypeOrAliasSymbol(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol>, Boolean)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOrAlias(Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax, Microsoft.CodeAnalysis.DiagnosticBag, Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeSymbol>, Boolean)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeOrAliasOrConstraintKeyword(Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax, Microsoft.CodeAnalysis.DiagnosticBag, ConstraintContextualKeyword ByRef)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeParameterConstraints(Microsoft.CodeAnalysis.CSharp.Syntax.TypeParameterSyntax, Microsoft.CodeAnalysis.CSharp.Syntax.TypeParameterConstraintClauseSyntax, Boolean, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Binder.BindTypeParameterConstraintClauses(Microsoft.CodeAnalysis.CSharp.Symbol, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol>, Microsoft.CodeAnalysis.CSharp.Syntax.TypeParameterListSyntax, Microsoft.CodeAnalysis.SyntaxList`1<Microsoft.CodeAnalysis.CSharp.Syntax.TypeParameterConstraintClauseSyntax>, Microsoft.CodeAnalysis.DiagnosticBag, Boolean, Boolean)
   at Microsoft.CodeAnalysis.CSharp.Symbols.ConstraintsHelper.MakeTypeParameterConstraintKinds(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.CSharp.Binder, System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol>, Microsoft.CodeAnalysis.CSharp.Syntax.TypeParameterListSyntax, Microsoft.CodeAnalysis.SyntaxList`1<Microsoft.CodeAnalysis.CSharp.Syntax.TypeParameterConstraintClauseSyntax>)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceOrdinaryMethodSymbol.GetTypeParameterConstraintKinds()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceOrdinaryMethodSymbol.GetTypeParameterConstraintTypes()
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMethodTypeParameterSymbol.ResolveBounds(Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol>, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceTypeParameterSymbolBase.GetBounds(Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol>)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceTypeParameterSymbolBase.GetConstraintTypes(Roslyn.Utilities.ConsList`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol>)
   at Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol.EnsureAllConstraintsAreResolved(System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol>)
   at Microsoft.CodeAnalysis.CSharp.Symbols.VarianceSafety.CheckTypeParametersVarianceSafety(System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.CSharp.Symbols.TypeParameterSymbol>, Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Symbols.VarianceSafety.CheckMethodVarianceSafety(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, LocationProvider`1<Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol>, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Symbols.VarianceSafety.CheckMethodVarianceSafety(Microsoft.CodeAnalysis.CSharp.Symbols.MethodSymbol, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Symbols.VarianceSafety.CheckInterfaceVarianceSafety(Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol, Microsoft.CodeAnalysis.DiagnosticBag)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.GetSynthesizedExplicitImplementations(System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Symbols.SourceMemberContainerTypeSymbol.ForceComplete(Microsoft.CodeAnalysis.SourceLocation, System.Threading.CancellationToken)
   at Microsoft.CodeAnalysis.CSharp.Symbol.ForceCompleteMemberByLocation(Microsoft.CodeAnalysis.SourceLocation, Microsoft.CodeAnalysis.CSharp.Symbol, System.Threading.CancellationToken)
   at Roslyn.Utilities.RoslynParallel+<>c__DisplayClass1_0.<For>g__errorHandlingBody|0(Int32)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
   at System.Threading.Tasks.TaskReplicator+Replica.Execute()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

```
Command: test "F:\workspace\_work\1\s\artifacts\bin\Microsoft.CodeAnalysis.CSharp.Symbol.UnitTests\Release\net5.0\Microsoft.CodeAnalysis.CSharp.Symbol.UnitTests.dll" --filter <PrivateImplementationDetails>+__StaticArrayInitTypeSize=10|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=100|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=104|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=108|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=12|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=120|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=132|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=136|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=144|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=16|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=176|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=1764|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=20|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=224|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=24|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=28|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=32|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=36|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=40|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=44|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=48|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=5|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=52|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=56|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=60|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=64|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=68|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=72|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=76|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=80|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=820|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=84|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=88|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=92|<PrivateImplementationDetails>+__StaticArrayInitTypeSize=96|Microsoft.CodeAnalysis.CSharp.ForEachStatementInfoTests|Microsoft.CodeAnalysis.CSharp.QueryClauseInfoTests|Microsoft.CodeAnalysis.CSharp.TypeInfoTests|Microsoft.CodeAnalysis.CSharp.UnitTests.AccessTests|Microsoft.CodeAnalysis.CSharp.UnitTests.BadSymbolReference|Microsoft.CodeAnalysis.CSharp.UnitTests.BaseClassTests|Microsoft.CodeAnalysis.CSharp.UnitTests.ClsComplianceTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CompilationAPITests|Microsoft.CodeAnalysis.CSharp.UnitTests.CompilationAPITests+EvolvingTestReference|Microsoft.CodeAnalysis.CSharp.UnitTests.CompilationCreationTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CompilationCreationTests+DummyReferenceResolver|Microsoft.CodeAnalysis.CSharp.UnitTests.CompilationCreationTests+Resolver|Microsoft.CodeAnalysis.CSharp.UnitTests.CompilationErrorTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CompletionTests|Microsoft.CodeAnalysis.CSharp.UnitTests.ConstructorDocumentationCommentTests|Microsoft.CodeAnalysis.CSharp.UnitTests.ContainerTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CrefTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CrossLanguageTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CSharpCompilationOptionsTests|Microsoft.CodeAnalysis.CSharp.UnitTests.CSharpCompilationOptionsTests+MetadataReferenceResolverWithEquality|Microsoft.CodeAnalysis.CSharp.UnitTests.CustomModifierCopyTests|Microsoft.CodeAnalysis.CSharp.UnitTests.Declarations.SourcePlusMetadataTests|Microsoft.CodeAnalysis.CSharp.UnitTests.DeclarationTests|Microsoft.CodeAnalysis.CSharp.UnitTests.DeclarationTests+CountedSyntaxTree|Microsoft.CodeAnalysis.CSharp.UnitTests.DeclarationTests+CountedSyntaxTree+Reference|Microsoft.CodeAnalysis.CSharp.UnitTests.DelegateTests|Microsoft.CodeAnalysis.CSharp.UnitTests.DestructorDocumentationCommentTests|Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests|Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentCompilerTests+DocumentationCommentAdder|Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationCommentIDTests|Microsoft.CodeAnalysis.CSharp.UnitTests.DocumentationModeTests|Microsoft.CodeAnalysis.CSharp.UnitTests.EventDocumentationCommentTests|Microsoft.CodeAnalysis.CSharp.UnitTests.ExtendedPartialMethodsTests|Microsoft.CodeAnalysis.CSharp.UnitTests.ExternAliasTests|Microsoft.CodeAnalysis.CSharp.UnitTests.FieldDocumentationCommentTests|Microsoft.CodeAnalysis.CSharp.UnitTests.FieldTests|Microsoft.CodeAnalysis.CSharp.UnitTests.FunctionPointerTypeSymbolTests|Microsoft.CodeAnalysis.CSharp.UnitTests.FunctionPointerTypeSymbolTests+Equality|Microsoft.CodeAnalysis.CSharp.UnitTests.GetSemanticInfoTests|Microsoft.CodeAnalysis.CSharp.UnitTests.GetUnusedImportDirectivesTests|Microsoft.CodeAnalysis.CSharp.UnitTests.ImplicitClassTests|Microsoft.CodeAnalysis.CSharp.UnitTests.IncludeTests|Microsoft.CodeAnalysis.CSharp.UnitTests.IndexedProperties_BindingTests|Microsoft.CodeAnalysis.CSharp.UnitTests.IndexedTypeParameterTests|Microsoft.CodeAnalysis.CSharp.UnitTests.LoadDirectiveTests|Microsoft.CodeAnalysis.CSharp.UnitTests.LocationTests|Microsoft.CodeAnalysis.CSharp.UnitTests.LookupSymbolsInfoTests|Microsoft.CodeAnalysis.CSharp.UnitTests.MetadataMemberTests|Microsoft.CodeAnalysis.CSharp.UnitTests.MetadataTypeTests|Microsoft.CodeAnalysis.CSharp.UnitTests.MethodDocumentationCommentTests|Microsoft.CodeAnalysis.CSharp.UnitTests.MethodEqualityTests|Microsoft.CodeAnalysis.CSharp.UnitTests.MethodTests --framework net5.0 --logger "xunit;LogFilePath=F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.CodeAnalysis.CSharp.Symbol.UnitTests.dll.1_net5.0_x86.xml"
xUnit output log: F:\workspace\_work\1\s\artifacts\log\Release\xUnitFailure-Microsoft.CodeAnalysis.CSharp.Symbol.UnitTests.dll.1.log
```

CLR version 5.0.100 on Windows.

### LINKED ISSUE #46023: Test failure: JIT/Regression/JitBlue/Runtime_45557/Runtime_45557/Runtime_45557.sh
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=919383&view=ms.vss-test-web.build-test-results-tab&runId=29226030&resultId=106020&paneView=debug

failed tests:
JIT/Regression/JitBlue/Runtime_45557/Runtime_45557/Runtime_45557.sh
JIT\\Regression\\JitBlue\\Runtime_45557\\Runtime_45557\\Runtime_45557.cmd

CoreCLR Linux arm Checked gcstress0x3 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

Error message
~~~
Assert failure(PID 1523 [0x000005f3], Thread: 1523 [0x05f3]): !CREATE_CHECK_STRING(pMT && pMT->Validate())
    File: /__w/1/s/src/coreclr/vm/object.cpp Line: 516
    Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_45557/Runtime_45557/Runtime_45557.sh: line 365:  1523 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/JIT/Regression/Reports/JIT.Regression/JitBlue/Runtime_45557/Runtime_45557/Runtime_45557.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun Runtime_45557.dll ''
0
Gathering state for process 1523 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.1523.dmp
Written 52031488 bytes (12703 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/JIT/Regression/JitBlue/Runtime_45557/Runtime_45557/Runtime_45557.sh
Expected: True
Actual:   False

Stack trace
   at JIT_Regression._JitBlue_Runtime_45557_Runtime_45557_Runtime_45557_._JitBlue_Runtime_45557_Runtime_45557_Runtime_45557_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/JIT.Regression/JIT.Regression.XUnitWrapper.cs:line 141607
~~~

### PR DESCRIPTION
**Pull request by BruceForstall**
Fix #45557 for arm/arm64

Fixes #46023

### CODE REVIEW

**Comment by BruceForstall** [comment]
gcstress failures are 2 timeouts in Linux arm, and 2 failures of https://github.com/dotnet/runtime/issues/45090

**Comment by BruceForstall** [comment]
@sandreenko @dotnet/jit-contrib PTAL

**Comment by BruceForstall** [comment]
asm diffs for arm64 are essentially the same as for xarch in https://github.com/dotnet/runtime/issues/45557; extended GC lifetimes where previously they were cut short.

**Review by AndyAyersMS — APPROVED** [review]
We should port this to 5.0 as well.

**Comment by BruceForstall** [comment]
I verified that the Linux arm libraries crossgen SPMI asm diffs show the same pattern of fixes: adding stack slots to the tracked GC refs set for a short range.

**Pull request merged**
