### PR TITLE
perf: wasm: Collect helix logs, and artifacts when the build fails

### PR DESCRIPTION
**Pull request by radical**
This will be helpful in debugging build issues, and random crashes that
we have been seeing on helix.

### CODE REVIEW

**Review by LoopedBard3 — APPROVED** [review]
LGTM, should merge if we have succeeding pipeline runs. If we don't, let me know and I'll run one.

**Comment by radical** [comment]
> LGTM, should merge if we have succeeding pipeline runs. If we don't, let me know and I'll run one.

I did have succeeding pipeline runs, but those were running only the wasm jobs. I have kicked off another one now which runs everything, but I think if the yml doesn't complain (it doesn't) then this should be good. But we can wait too :)

**Comment by LoopedBard3** [comment]
Awesome! Let's wait just to be safe, but go ahead and merge it once it succeeds.

**Review by lewing — APPROVED** [review]
Looks great assuming everything works.

**Comment by radical** [comment]
Issues:
1. The wasm build is broken due to a linker issue which came via the last bdn bump in `dotnet/performance` to `0.13.1.1741`. The next bump(https://github.com/dotnet/performance/pull/2334) fixes it, but is waiting on the nuget to be published to the public feeds.

2. The broken build should have triggered the log collection, but that got skipped thanks to a typo in a last minute check that I added 😬

**Comment by radical** [comment]
Ugh.. sorry, I seem to have pushed the branch with the debug bits added on top, which I'm testing in parallel. I'll remove those. And restore this to the changes as they were reviewed, plus the typo fix.

**Comment by radical** [comment]
Since this has to now wait for https://github.com/dotnet/performance/pull/2334 to be merged, I added a change to use`--run-isolated` for wasm builds.

**Comment by radical** [comment]
The manual run was successful. A few items on the aot job "dead letter'ed", but I checked the logs, and they had passed too.

**Pull request merged**
