### PR TITLE
Dac changes for regions

### PR DESCRIPTION
**Pull request by PeterSolMS**
There are two sets of changes here:
- Make DacHeapWalker work for empty regions - I had observed a crash with the empty regions injected with STRESS_REGIONS.
- Make GetGCHeapStaticData robust against globals saved_sweep_ephemeral_seg and saved_sweep_ephemeral_start being null.

The changes should not cause issues for a coreclr *NOT* running with regions.

### CODE REVIEW

**Comment by noahfalk** [comment]
@mikem8361 can you take a look? 
cc @dotnet/dotnet-diag 

Assuming the debugger was using the _current_ SOS GCRoot code [here](https://github.com/dotnet/diagnostics/blob/main/src/SOS/Strike/gcroot.cpp#L1533), the _modified_ DAC code in this PR, and the _modified_ runtime code that supports regions would you expect GCRoot to compute the correct results? I don't mean to imply anything either way, I genuinely don't know as I have never looked at the implementation of GCRoot in SOS before. From what I see it looks like the SOS code for the algorithm was probably duplicated from some pre-existing GC code many years ago.

At a superficial level the change looks fine to me, but I also have no idea what the saved_sweep_ephemeral_seg/start variables mean. I'm hoping either @mikem8361 can dig in a little deeper or we make sure manual/automated testing shows that all is well : )

**Comment by PeterSolMS** [comment]
You raise a good point - an older SOS will certainly *not* work correctly with a newer coreclr and runtime supporting regions.

So, this would seem to imply that we need to bump up version numbers so users have a warning that they need to use a new SOS.

**Comment by PeterSolMS** [comment]
I looked up the earlier change we did for the doubly linked freelists - in this case, I incremented the SOS_BREAKING_CHANGE_VERSION in both the runtime and diagnostic repos.

I would think that this is the correct thing to do here as well.

**Comment by mikem8361** [comment]
Yes, incrementing SOS_BREAKING_CHANGE_VERSION in the runtime (this PR) and diagnostics repos is the right thing, if this change breaks older SOS's like Noah said.

**Review by mikem8361 — APPROVED** [review]
I'm ok with these changes as long as Andrew is too. I don't know all the details of the GC related DAC and SOS code.

**Comment by Maoni0** [comment]
I'm looking at the impl of `GetSegmentCount` and maybe I'm missing something but I don't understand how this can work for regions -

```
    static int GetSegmentCount(T seg_start)
    {
        int count = 0;
        while (seg_start)
        {
            // If we find this many segments, something is seriously wrong.
            if (count++ > 4096)
                break;

            seg_start = seg_start->next;
        }

        return count;
    }
```

for regions you can no longer enumerate all SOH segments by starting from gen2's start seg - you'd need to go into gen0/1's segments separately. also for regions it's not inconceivable at all that the count could be more than 4096.

**Review by cshung — APPROVED** [review]
The change in `request.cpp` looks good to me. I have done some testing in the SOS scenario and fixed a couple of issues in https://github.com/dotnet/diagnostics/pull/2200

The `DacHeapWalker` change doesn't seems to be used in SOS at all. I wasn't able to test it yet, but reading the code it looks fine.

**Comment by PeterSolMS** [comment]
I will increment SOS_BREAKING_CHANGE_VERSION in the runtime and the diagnostics repos in a separate PR. I'll also address the remaining issues in dacdbiimpl.cpp in a separate PR.

**Pull request merged**
