### PR TITLE
Rename IsMacOS to IsApplePlatform in the JIT

### LINKED ISSUE #87610: [NativeAOT] Properly implement targeting iOS-like platforms rather than pretending to be macOS
## Description

Initial support for targeting iOS-like platforms with NativeAOT introduced with: https://github.com/dotnet/runtime/pull/81476 uses a workaround in JIT interface: https://github.com/dotnet/runtime/blob/8f19f4ebd511994be27a2e1f4c88424a26f91e7c/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs#L3066 
hardwiring the compilation as if the target platform is macOS which also brings along corresponding implications on the native side.

### PR DESCRIPTION
**Pull request by akoeplinger**
Now that we use it on iOS/tvOS as well, rename the variables to match.

Fixes https://github.com/dotnet/runtime/issues/87610

### CODE REVIEW

**Comment by am11** [comment]
> IsAppleOS

Why not IsApplePlatform which we have used elsewhere? Or should we rename those to IsAppleOS (to rhyme with Target"OS")?

**Comment by akoeplinger** [comment]
I don't particularly care, another option would be using IsOSXLike which we've used in ILC.

**Comment by am11** [comment]
> I don't particularly care,

Well, introducing new name is not being consistent, which is the whole premise of this change. ;)

```zsh
 % git grep -i isappleplatform | wc -l
      70
 % git grep -i isappleos | wc -l      
       0
```

**Comment by akoeplinger** [comment]
Ok, renamed to IsApplePlatform and fixed a few other instances where we referred to osx/macos

**Review by jkotas — APPROVED** [review]
Thanks

**Pull request merged**
