### PR TITLE
[wasm] Post 3.1.30 emscripten bump feedback

### PR DESCRIPTION
**Pull request by radekdoulik**
Make the minimal build env vars item group "private".

Enable simd for old v8 in tests

### CODE REVIEW

**Comment by radical** [comment]
From [aot libtests](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-83391-merge-f5d1bd92d96e49189c/normal-System.Runtime.Tests/1/console.2590fabe.log?helixlogtype=result):
```
[15:57:15] info: Warning: unknown flag --experimental-wasm-simd.
[15:57:15] info: Try --help for options
[15:57:15] info: Warning: unknown flag --experimental-wasm-bigint.
[15:57:15] info: Try --help for options
[15:57:15] info: Warning: unknown flag --experimental-wasm-simd.
[15:57:15] info: Try --help for options
```

Also, extra tracing seems to be enabled:
```
[15:57:15] info: console.debug: MONO_WASM: mono_wasm_load_config
[15:57:15] info: console.debug: MONO_WASM: mono_wasm_pre_init_essential
[15:57:15] info: console.debug: MONO_WASM: preInit
```

**Comment by kg** [comment]
> From [aot libtests](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-83391-merge-f5d1bd92d96e49189c/normal-System.Runtime.Tests/1/console.2590fabe.log?helixlogtype=result):
> 
> ```
> [15:57:15] info: Warning: unknown flag --experimental-wasm-simd.
> [15:57:15] info: Try --help for options
> [15:57:15] info: Warning: unknown flag --experimental-wasm-bigint.
> [15:57:15] info: Try --help for options
> [15:57:15] info: Warning: unknown flag --experimental-wasm-simd.
> [15:57:15] info: Try --help for options
> ```
> 
> Also, extra tracing seems to be enabled:
> 
> ```
> [15:57:15] info: console.debug: MONO_WASM: mono_wasm_load_config
> [15:57:15] info: console.debug: MONO_WASM: mono_wasm_pre_init_essential
> [15:57:15] info: console.debug: MONO_WASM: preInit
> ```

Sounds like we need to update v8 on the bots.

The tracing is from the memory snapshot PR, I think. Should be an easy fix. It's `runtimeHelpers.diagnosticTracing`, I believe.

**Comment by radical** [comment]
This is running with `V8 version: 11.3.94`.

**Comment by kg** [comment]
> This is running with `V8 version: 11.3.94`.

Oh, I guess they *removed* the options now that they're default

**Comment by radekdoulik** [comment]
The v8 warnings are from newer v8 versions (11.3.94) and they do no harm. We needed these for older v8 (8.5.183), which is used on runtime tests.

Looking closer on these, the runtime tests use system v8. So we might not need these flags if we make runtime tests use v8 from jsvu installation.

Library tests
```
[21:17:25] info: Using js engine V8 from path /usr/local/bin/v8
[21:17:26] info: V8 version: 8.5.183
```

Runtime tests
```
[15:57:13] info: Using js engine V8 from path /home/helixbot/.jsvu/bin/v8
[15:57:15] info: V8 version: 11.3.94
```

**Comment by radekdoulik** [comment]
The runtime tests are not using the queue with the docker image for some reason. @radical do you know why that might be? I looked at the yml files, but don't see why it doesn't choose this queue `(Ubuntu.1804.Amd64)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-webassembly`

**Review by kg — APPROVED** [review]

**Pull request merged**
