### PR TITLE
Fix stack walking for new EH

### PR DESCRIPTION
**Pull request by janvorli**
There is an edge case when the StackFrameIterator was incorrectly setting the fShouldParentFrameUseUnwindTargetPCforGCReporting, which resulted in a 100% reproducible GC hole in the
baseservices\exceptions\unittests\ThrowInFinallyNestedInTry with GC stress C and tiered compilation off.
The fix is to delete code that is already present in an "if" branch above the change and that should really be executed only when the funclet parent is the caller of the actual handler frame.

### CODE REVIEW

**Comment by janvorli** [comment]
@jkotas the issue was found on the PR to reenable the new EH where I have let it execute the GC stress legs.

**Review by jkotas — APPROVED** [review]

**Comment by janvorli** [comment]
The GC stress 3 test legs have hit a GC hole, I need to investigate it.

**Comment by janvorli** [comment]
Closing this, created a new PR that supersedes it.

**Pull request closed without merging**
