### PR TITLE
[marshal] Cleanup dead ifdefs

### LINKED ISSUE #78422: [MONO][Marshal] Remove unused marshal-noilgen code
As of this change https://github.com/dotnet/runtime/commit/3cfd6cffc495e4539bf6cdb5919922b8d8972e57 the `ENABLE_ILGEN` preprocessor flag is always defined. There is a bunch of code behind `ifdef`'s that can now be removed, as well as usage of the `ENABLE_ILGEN` define itself.

### PR DESCRIPTION
**Pull request by lambdageek**
1. The `DISABLE_NONBLITTABLE` define was a previous attempt at partitioning the marshaling into a simple version that just supports blittable types and the full legacy marshaller.  It was never used in production.

2. The `ENABLE_ILGEN` was used previously in configurations where runtime codegen was not available to save some space by excluding support for emitting IL at runtime (needed for marshaling, fast managed allocators in sgen, etc).  It also used to emit the ilgen support code into a separate static library that could optionallly be linked into the runtime, and enabled with an appropriate API call (`mono_marshal_ilgen_init`).  This define is now on by default and the API function is a no-op.

3. Mark a collection of `mono_win32_compat_` functions with `MONO_RT_EXTERNAL_ONLY` and move them to `external-only.c` (these were used in mono/mono dllmap support to provide some common kernel32 functions on non-Windows)

4. Remove `MonoMarshalILgenCallbacks` in `marshal-ilgen.c` - just do direct calls to the `_ilgen` helper functions

Fixes https://github.com/dotnet/runtime/issues/78422

### CODE REVIEW

**Comment by lambdageek** [comment]
@naricc first stab at cleaning up now that the component is finally in

**Review by vargaz — APPROVED** [review]

**Review by SamMonoRT — APPROVED** [review]

**Comment by SamMonoRT** [comment]
Fixes https://github.com/dotnet/runtime/issues/78422

**Comment by lambdageek** [comment]
tvOS failures are unrelated

**Pull request merged**
