### PR TITLE
Exclude corehost/test from mono builds

### PR DESCRIPTION
**Pull request by elinor-fung**
These are native test assets for the host tests, which don't run on mono.

### CODE REVIEW

**Comment by tmds** [comment]
When .NET gets built for s390x, it uses mono runtime.

I assume this change causes `corehost/test` to also be excluded from that configuration?

cc @uweigand @omajid

**Comment by uweigand** [comment]
The `corehost_test` binary is used by several of the tests triggered via `./build.sh host.tests --test`.   These don't currently execute cleanly on s390x for other reasons, but I'm working on a patch set to fix that.  Removing the build of `corehost_test` would break this again.

Anyway, `corehost_test` itself actually builds fine on s390x using Mono, so I'm not sure why it should be removed?

**Comment by elinor-fung** [comment]
> These don't currently execute cleanly on s390x for other reasons, but I'm working on a patch set to fix that

Ah, okay. I did not realize there was work to get these executing cleanly. I saw we were not running the host tests on mono (and knew that they would not run successfully), so figured we could save our builds some unnecessary work.

I will close this then.

**Pull request closed without merging**
