### PR TITLE
Fix 42955

### PR DESCRIPTION
**Pull request by sdmaclea**
Stop stripping pointer authentication bits

Related to #42955

### CODE REVIEW

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Comment by sdmaclea** [comment]
A couple hundred tests fail in Helix w/o this workaround.

https://dev.azure.com/dnceng/public/_build/results?buildId=1083757&view=ms.vss-test-web.build-test-results-tab

I'll take a look a 11.3 Beta 7.

**Comment by sdmaclea** [comment]
Maybe the issue is that we are trying to unwind through kernel frames and the kernel has pointer authentication enabled.

**Comment by sdmaclea** [comment]
Updated the comment in #42955.

**Pull request closed without merging**
