### PR TITLE
Use netfxreference.props to provide the shims for the platform manifest.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Follow up to https://github.com/dotnet/runtime/pull/45566#pullrequestreview-544561080

### CODE REVIEW

**Comment by ViktorHofer** [comment]
What about these shims? https://github.com/dotnet/runtime/pull/45573/files#diff-73501876de44040254c85fdaa4803c49567a03031f226df625742b8970ace017R211

**Comment by jkoritzinsky** [comment]
Your link isn't resolving. Which shims are you referring to?

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/runtime/blob/a259ec2e967d502f82163beba6b84da5319c5e08/src/installer/pkg/sfx/Microsoft.NETCore.App/Directory.Build.props#L231-L245

**Comment by ericstj** [comment]
As much as possible we should reduce this list unless we have tests to make sure it's connect.

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Conflict :(

**Pull request merged**
