### PR TITLE
LowLevelLifoSemaphore: Fix incorrect field offset

### LINKED ISSUE #37075: Misaligned field offset inside LowLevelLifoSemaphore
# Description 
https://github.com/dotnet/runtime/blob/0c043d58ccce29e1d22acd4f77b0e0b352579ac5/src/libraries/System.Private.CoreLib/src/System/Threading/LowLevelLifoSemaphore.cs#L247-L260

``_countOfWaitersSignaledToWake`` is right outside of ``_asLong``'s range and so won't be captured when exchanging, the way that variable is used does not seem like it expects this kind of behavior.
Same thing over in mono's repo.

### PR DESCRIPTION
**Pull request by filipnavara**
Fixes #37075

### CODE REVIEW

**Comment by tannergooding** [comment]
Would it be good to remove the `Explicit` layout here in favor of `Unsafe.As<Counts, ulong>(ref this)` (like we've done elsewhere in S.P.Corelib)

**Comment by tannergooding** [comment]
CC. @kouvel as the area owner

**Comment by filipnavara** [comment]
> Would it be good to remove the `Explicit` layout here in favor of `Unsafe.As<Counts, ulong>(ref this)` (like we've done elsewhere in S.P.Corelib)?

What would guarantee the properly packed layout that fits into `ulong`? I guess it would still have to be `LayoutKind.Sequential` with proper `Pack` attribute. It would be an improvement but probably not a big one.

**Comment by john-h-k** [comment]
>  I guess it would still have to be LayoutKind.Sequential with proper Pack attribute. 

Structs are sequential by default, and given all the types are at their natural alignment in the type, it should fit perfectly into a `ulong` with no issue

**Comment by tannergooding** [comment]
Structs in C# are `LayoutKind.Sequential` by default, additionally fields are naturally aligned by default so:
```csharp
private struct Counts
{
    public uint _signalCount;
    public ushort _waiterCount;
    public byte _spinnerCount;
    public byte _countOfWaitersSignaledToWake
}
```

Will be of sequential layout, with `Pack=4` and `Size=8`. The current struct however is `Pack=8` due to the `long` fields and that may be required for `CompareExchange` now that I think about it.

**Comment by filipnavara** [comment]
> Structs are sequential by default, and given all the types are at their natural alignment in the type, it should fit perfectly into a ulong with no issue.

Thanks! I am aware of the default layout and natural packing but that's only half of the issue as @tannergooding pointed out. I also want to be sure that any allocated instance of the structure is on 8-byte aligned boundary to ensure proper atomicity of the interlocked operations on all possible CPU architectures.

**Review by stephentoub — APPROVED** [review]

**Review by kouvel — APPROVED** [review]

**Pull request merged**
