### PR TITLE
JIT: Delete IL verification failure helpers in importer

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Part of #32648. Per [this comment](https://github.com/dotnet/runtime/issues/32648#issuecomment-1255269884), I suspect this is the next (last?) step in removing IL verifier from the importer.

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
cc @dotnet/jit-contrib -- are there any CI legs worth running for this?

**Comment by AndyAyersMS** [comment]
> I suspect this is the next (last?) step in removing IL verifier from the importer.

We might want to do some renaming, say `verCurrentState` -> `stackState` or something. And there are various comments that could be updated/removed.

> cc @dotnet/jit-contrib -- are there any CI legs worth running for this?

I don't think so; no diffs should be sufficient. 

Our SPMI collection set is a bit impoverished right now, so maybe wait until that's fixed and rerun?

**Comment by amanasifkhalid** [comment]
> Our SPMI collection set is a bit impoverished right now, so maybe wait until that's fixed and rerun?

Not sure when this will be resolved, so I thought I'd push my revisions now for review.

**Review by AndyAyersMS — APPROVED** [review]
Thanks, this looks good.

**Comment by amanasifkhalid** [comment]
/ba-g CLR_Tools_Tests pipeline is timing out across PRs.

**Pull request merged**
