### PR TITLE
Revert "[mono][wasm] Fix the passing/returning of small vtypes. (#622…

### PR DESCRIPTION
**Pull request by vargaz**
…99)"

This reverts commit 915ee6db9cb871bb2ef32698015bca0f2c895ce8.

This causes test failures in the System.Collections.Immutable testsuite on wasm.

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]

**Comment by radical** [comment]
If this fixes `System.Collections.Immutable` tests, then this should be removed - https://github.com/dotnet/runtime/blob/main/src/libraries/tests.proj#L25

**Comment by vargaz** [comment]
Closing in favor of:
https://github.com/dotnet/runtime/pull/62400

**Pull request closed without merging**
