### PR TITLE
[release/6.0] Bump NugetPackagingVersion to 6.2.4

### PR DESCRIPTION
**Pull request by steveisok**
Resolves a CG issue that was flagging the build

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
lgtm

**Comment by ericstj** [comment]
@steveisok should this be targeting `release/6.0-staging`?

**Comment by steveisok** [comment]
Ugh, this needs to go into 6.0 instead of 6.0-staging. I'll force-push the right change

**Comment by directhex** [comment]
1 hour warning!

**Pull request merged**
