### PR TITLE
Typo in MULTIPLE_HEAPS to fix a memory usage regression

### LINKED ISSUE #73254: Memory usage regression
I am noticing an important regression in GC heap sizes and working set measurement on ASP.NET benchmarks (most of them).

These are the charts for Json MVC.

image

image

~~An early range of changes points to these commits: https://github.com/dotnet/runtime/compare/cfe26ec...68bd58e~~
Smallest set of changes reproducing the regression: https://github.com/dotnet/runtime/compare/cfe26ec...e415018

One of these changes impacted some GC work: https://github.com/dotnet/runtime/pull/72923

### PR DESCRIPTION
**Pull request by mrsharm**
Misspelt ``MULTIPLE_HEAPS`` - fixes https://github.com/dotnet/runtime/issues/73254.

### CODE REVIEW

**Comment by mrsharm** [comment]
Memory Regression is fixed: 


| application                             |                            |
| --------------------------------------- | -------------------------- |
| CPU Usage (%)                           | 98                         |
| Cores usage (%)                         | 2,758                      |
| Working Set (MB)                        | 496                        |
| Private Memory (MB)                     | 514                        |
| Build Time (ms)                         | 1,932                      |
| Start Time (ms)                         | 450                        |
| Published Size (KB)                     | 114,457                    |
| .NET Core SDK Version                   | 7.0.100-rc.1.22402.10      |
| ASP.NET Core Version                    | 7.0.0-rc.1.22402.1+bf02bf2 |
| .NET Runtime Version                    | 7.0.0-rc.1.22402.1+8fc905e |
| Max CPU Usage (%)                       | 96                         |
| Max Working Set (MB)                    | 521                        |
| Max GC Heap Size (MB)                   | 250                        |
| Size of committed memory by the GC (MB) | 460                        |
| Max Number of Gen 0 GCs / sec           | 13.00                      |
| Max Number of Gen 1 GCs / sec           | 1.00                       |
| Max Number of Gen 2 GCs / sec           | 0.00                       |
| Max Time in GC (%)                      | 1.00                       |
| Max Gen 0 Size (B)                      | 1,604,784                  |
| Max Gen 1 Size (B)                      | 16,655,200                 |
| Max Gen 2 Size (B)                      | 3,488,952                  |
| Max LOH Size (B)                        | 210,896                    |
| Max POH Size (B)                        | 2,271,920                  |
| Max Allocation Rate (B/sec)             | 3,788,973,080              |
| Max GC Heap Fragmentation               | 9                          |
| # of Assemblies Loaded                  | 113                        |
| Max Exceptions (#/s)                    | 469                        |
| Max Lock Contention (#/s)               | 195                        |
| Max ThreadPool Threads Count            | 48                         |
| Max ThreadPool Queue Length             | 159                        |
| Max ThreadPool Items (#/s)              | 551,343                    |
| Max Active Timers                       | 0                          |
| IL Jitted (B)                           | 190,050                    |
| Methods Jitted                          | 2,266                      |

Using: 

```
crank  --profile aspnet-citrine-win  --application.options.collectCounters True  --application.framework net7.0    --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/plaintext.benchmarks.yml  --scenario mvc --application.options.outputFiles C:\runtime\artifacts\bin\coreclr\windows.x64.Release\System.Private.CoreLib.dll --application.options.outputFiles C:\runtime\artifacts\bin\coreclr\windows.x64.Release\coreclr.dll --application.options.outputFiles C:\runtime\artifacts\bin\coreclr\windows.x64.Release\clrjit.dll --application.environmentVariables COMPlus_gcServer=1 
```

And the microbenchmark hasn't regressed: 

|       Method |  value |     Mean |    Error |   StdDev |   Median |      Min |      Max |  Gen 0 | Allocated |
|------------- |------- |---------:|---------:|---------:|---------:|---------:|---------:|-------:|----------:|
| EnumToString | Yellow | 13.48 ns | 0.210 ns | 0.197 ns | 13.44 ns | 13.19 ns | 13.82 ns | 0.0022 |      24 B |

**Comment by Maoni0** [comment]
can you also take the opportunity to fix the other issue I mentioned "it needs to initialize the saved_allocated in the else case when shigh is 0."?

**Comment by mrsharm** [comment]
> can you also take the opportunity to fix the other issue I mentioned "it needs to initialize the saved_allocated in the else case when shigh is 0."?

I think I have already fixed it. Please let me know if I got it wrong: 


```
            do
            {
                heap_segment_saved_allocated(seg) = 0;
                uint8_t* start_unmarked = heap_segment_mem (seg);
```

**Comment by Maoni0** [comment]
> I think I have already fixed it. Please let me know if I got it wrong:

it's correct. the change just wasn't there when I reviewed it the first time (I saw you did this in a separate commit).

**Review by Maoni0 — APPROVED** [review]

**Pull request merged**
