### PR TITLE
[LoongArch64] Fix code generation for type conversion from float/double to uint/ulong.

### PR DESCRIPTION
**Pull request by sunlijun-610**
The previous conversion from floating-point numbers to unsigned integers was incorrect in handling negative numbers and NaN.The previous instructions are as follows: 
`lu52i.d         $r21, $zero, 1086`
`movgr2fr.d      $ft3, $r21`
`fcmp.clt.d      $fcc2, $fs0, $ft3`
`fcmp.ceq.d      $fcc3, $fs0, $ft3`
`li.w            $r21, 0x0`
`bcnez           $fcc2, 16`
`fsub.d          $ft3, $fs0, $ft3`
`li.w            $r21, 0x1`
`slli.d          $r21, $r21, 0x3f`
`fsel            $ft3, $ft3, $fs0, $fcc2`
`ftintrz.l.d     $ft3, $ft3`
`movfr2gr.d      $a0, $ft3`
`bcnez           $fcc3, 8`
`beqz            $a0, 8`
`or              $a0, $r21, $a0`

After modification, negative numbers and NaN are handled first.The modified instructions are as follows:
`li.w            $a0, 0x0`
`movgr2fr.d      $ft3, $zero`
`fcmp.cult.d     $fcc2, $fa0, $ft3`
`bcnez           $fcc2, 52`
`lu52i.d         $r21, $zero, 1086`
`movgr2fr.d      $ft3, $r21`
`fcmp.clt.d      $fcc2, $fa0, $ft3`
`li.w            $r21, 0x0`
`bcnez           $fcc2, 16`
`fsub.d          $ft3, $fa0, $ft3`
`li.w            $r21, 0x1`
`slli.d          $r21, $r21, 0x3f`
`fsel            $ft3, $ft3, $fa0, $fcc2`
`ftintrz.l.d     $ft3, $ft3`
`movfr2gr.d      $a0, $ft3`
`or              $a0, $r21, $a0`

### CODE REVIEW

**Comment by sunlijun-610** [comment]
@shushanhf Could you please review this change？
Thanks！

**Comment by huoyaoyuan** [comment]
If LA64 doesn't have native conversion instruction for fp<->unsigned, are the `JIT_Dbl2UInt` `JIT_Dbl2ULng` helpers applicable?

**Comment by shushanhf** [comment]
> If LA64 doesn't have native conversion instruction for fp<->unsigned, are the `JIT_Dbl2UInt` `JIT_Dbl2ULng` helpers applicable?

We just use some instructions embedded by the codegen to avoid calling helpers.

**Comment by huoyaoyuan** [comment]
Is there any JIT tests covering this? I can find `src/tests/JIT/Methodical/NaN/r4NaNconv` for NaN.

**Comment by sunlijun-610** [comment]
> Is there any JIT tests covering this? I can find `src/tests/JIT/Methodical/NaN/r4NaNconv` for NaN.

`src/tests/JIT/Directed/Convert/out_of_range_fp_to_int_conversions` for negative numbers and NaN.

**Review by shushanhf — APPROVED** [review]
LGTM
Thanks

@jakobbotsch  could you please review this PR?

**Comment by sunlijun-610** [comment]
@jakobbotsch could you please review this PR?
Thanks!

**Review by jakobbotsch — APPROVED** [review]

**Pull request merged**
