### PR TITLE
[LoongArch64] enable the promote feature.

### PR DESCRIPTION
**Pull request by shushanhf**
Enable the promote feature for LoongArch64.

This PR is part of the issue #69705

### CODE REVIEW

**Comment by shushanhf** [comment]
All the failed tests are about `Send to Helix`.

Hi, @BruceForstall 
Could you please review this PR ?

**Review by BruceForstall — APPROVED** [review]
LGTM.

Glad to see you enabling this!

I requested rerun of the failing tests and will merge after they complete successfully: there was a general infrastructure failure that should now be fixed.

**Comment by BruceForstall** [comment]
Looks like the testing hit a new infra problem described here: https://github.com/dotnet/runtime/pull/69878#issuecomment-1139117131

We'll have to wait for that to be resolved before rerunning testing.

**Comment by shushanhf** [comment]
> Looks like the testing hit a new infra problem described here: [#69878 (comment)](https://github.com/dotnet/runtime/pull/69878#issuecomment-1139117131)
> 
> We'll have to wait for that to be resolved before rerunning testing.

Yes, you are right.
Thanks very much for your review.

**Pull request merged**
