### PR TITLE
Make superpmi.py collect easier to use

### PR DESCRIPTION
**Pull request by jakobbotsch**
* Add `COMPlus_JitPath` and `COMPlus_AltJitPath` debug variables. When set, the runtime loads the JIT (resp. alt-jit) from these paths without any validation. I went with new variables to support collecting over commands that may invoke arbitrary child dotnet executables, and to still keep supporting both debug and release coreclr builds.
* Change `superpmi.py collect` to set `COMPlus_JitPath` meaning that no copying of the shim is necessary anymore when dealing with debug/checked builds (e.g. when recording collections over libraries tests)
* Change `superpmi.py collect` to avoid changing current directory, which breaks for example the libraries tests

With these changes collecting libraries tests just works without requiring any additional workarounds.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
@jkotas can you please take a look at the runtime changes and verify that it is ok?

**Comment by jkotas** [comment]
> @jkotas can you please take a look at the runtime changes and verify that it is ok?

LGTM

**Comment by jakobbotsch** [comment]
ARM32 failure looks related.

**Review by kunalspathak — APPROVED** [review]
LGTM. Thanks!

**Comment by jakobbotsch** [comment]
> ARM32 failure looks related.

Didn't look related after all on a closer look.

**Pull request merged**
