### PR TITLE
Rebucket tests that fail with NativeAOT and fix some

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
I went through the "These tests don't build" uber bucket - pretty much all of those tests do actually build fine.

* Some of them even run to completion without any failures. Unblocked those.
* Fixed two that had problems:
  * System.Diagnostics.Debug.Tests was failing to build because the SingleFileTestRunner.cs references List and Dictionary and there's special magic needed in the project file for that to not to conflict between CoreLib and System.Collections.
  * System.Diagnostics.FileVersionInfo.Tests builds a test assembly that is not actually a part of the test, but a test asset. Reference it like that so that this strategy works with single file form factors. Fixes the test run.
* Rebucketed the rest of the failing tests into those that we need to look into, and those that are not interesting.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
Cc @radical @radekdoulik on commit [ceb7fd1](https://github.com/dotnet/runtime/pull/71819/commits/ceb7fd1650fade1d78eb2f382dd7a8fe63b5fff0). I had to hack around WasmApp.targets treating all *.dll files in the app (including `Content`) as something that has meaning to the packaging. I would file an issue but I don't like filing issues that nobody will look at. Let me know if you would like an issue on it. It was running into `Found identical vfs mappings for target path: System.Diagnostics.FileVersionInfo.TestAssembly.dll, source file: .../System.Diagnostics.FileVersionInfo.TestAssembly.dll` without the workaround in the commit.

The test in question has a `ProjectReference` to a test assembly that is inspected using file IO APIs and it's not actually part of the app and should not be treated as such (should not be AOT compiled or whatever special we do to app assemblies - it's just a data file that happens to be an assembly).

**Comment by LakshanF** [comment]
There are 1 failure each on Windows and Linux runs. I will disable these tests for now in tests.proj

- Windows: [System.Net.NameResolution.Functional.Tests](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71819-merge-ed1e0f30b51a471880/System.Net.NameResolution.Functional.Tests/3/console.9cd1c72b.log?helixlogtype=result)
- Linux: [System.Numerics.Vectors.Tests](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71819-merge-e7412b33e6fc42f49d/System.Numerics.Vectors.Tests/1/console.cbb0222b.log?helixlogtype=result)

**Comment by radical** [comment]
> Cc @radical @radekdoulik on commit [ceb7fd1](https://github.com/dotnet/runtime/pull/71819/commits/ceb7fd1650fade1d78eb2f382dd7a8fe63b5fff0). I had to hack around WasmApp.targets treating all *.dll files in the app (including `Content`) as something that has meaning to the packaging. I would file an issue but I don't like filing issues that nobody will look at. Let me know if you would like an issue on it. It was running into `Found identical vfs mappings for target path: System.Diagnostics.FileVersionInfo.TestAssembly.dll, source file: .../System.Diagnostics.FileVersionInfo.TestAssembly.dll` without the workaround in the commit.

Currently, we are adding all the `dll` files from the publish directory. It's a known [issue](https://github.com/dotnet/runtime/issues/46856). They get added here:
https://github.com/dotnet/runtime/blob/3ac16299ebe42e4805b86d5f27fb7469ae3357fb/eng/testing/tests.wasm.targets#L253-L254

And the content files are added for the VFS. Maybe we should remove those from `WasmAssembliesToBundle`.

**Comment by MichalStrehovsky** [comment]
Thank you @radical! I've added reference to the issue to the workaround!

@LakshanF interesting, the System.Numerics.Vectors.Tests are not in the exclusions I'm rebucketing. This might be a recent regression. We might want to deal with that separately.

**Comment by radical** [comment]
Wasm failures are fixed by https://github.com/dotnet/runtime/pull/71976, which was just merged.

**Review by LakshanF — APPROVED** [review]
LGTM. Thanks for doing this and I will follow on the Linux failure separately

**Pull request merged**
