### PR TITLE
Switch to the new ARM64 Helix queues

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Want to check if this works, no merge for now.

Cc @dotnet/runtime-infrastructure

### CODE REVIEW

**Review by MattGal — APPROVED** [review]

**Comment by MattGal** [comment]
Consider trying ubuntu.2004.armarch / ubuntu.2004.armarch.open as well.

**Comment by MichalStrehovsky** [comment]
@dotnet/area-system-globalization this is switching the tests from running on Windows 10 ARM64 to Windows 11 ARM64. Is it expected that these tests would fail? Do they need special OS configuration? They're failing both in the regular libraries run and NativeAOT libraries run on ARM64.

```
[FAIL] System.Globalization.Tests.NumberFormatInfoCurrencyGroupSizes.CurrencyGroupSizes_Get_ReturnsExpected(format: NumberFormatInfo { }, expected: [3, 2])
Assert.Equal() Failure
              ? (pos 1)
Expected: [3, 2]
Actual:   [3]
   at System.Globalization.Nls.Tests!<BaseAddress>+0x89e4b4
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x14c
[FAIL] System.Globalization.Tests.CultureInfoConstructor.Ctor_String(name: "prs", expectedNames: ["prs"], expectToThrowOnBrowser: True)
Assert.Contains() Failure
Not found: fa
In value:  String[] ["prs"]
   at System.Globalization.Tests.CultureInfoConstructor.Ctor_String(String name, String[] expectedNames, Boolean expectToThrowOnBrowser) + 0xa0
   at System.Globalization.Nls.Tests!<BaseAddress>+0x8a7760
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x14c
[FAIL] System.Globalization.Tests.CultureInfoConstructor.Ctor_String(name: "prs-AF", expectedNames: ["prs-AF"], expectToThrowOnBrowser: True)
Assert.Contains() Failure
Not found: fa-AF
In value:  String[] ["prs-AF"]
   at System.Globalization.Tests.CultureInfoConstructor.Ctor_String(String name, String[] expectedNames, Boolean expectToThrowOnBrowser) + 0xa0
   at System.Globalization.Nls.Tests!<BaseAddress>+0x8a7760
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x14c
[FAIL] System.Globalization.Tests.NumberFormatInfoMiscTests.DigitSubstitutionListTest(cultureName: "prs", shape: NativeNational)
Assert.Equal() Failure
Expected: Context
Actual:   NativeNational
   at System.Globalization.Tests.NumberFormatInfoMiscTests.DigitSubstitutionListTest(String cultureName, DigitShapes shape) + 0x54
   at System.Globalization.Nls.Tests!<BaseAddress>+0x89e604
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x14c
```

**Comment by MattGal** [comment]
> @dotnet/area-system-globalization this is switching the tests from running on Windows 10 ARM64 to Windows 11 ARM64. Is it expected that these tests would fail? Do they need special OS configuration? They're failing both in the regular libraries run and NativeAOT libraries run on ARM64.
> 
> ```
> [FAIL] System.Globalization.Tests.NumberFormatInfoCurrencyGroupSizes.CurrencyGroupSizes_Get_ReturnsExpected(format: NumberFormatInfo { }, expected: [3, 2])
> Assert.Equal() Failure
>               ? (pos 1)
> Expected: [3, 2]
> Actual:   [3]
>    at System.Globalization.Nls.Tests!<BaseAddress>+0x89e4b4
>    at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x14c
> [FAIL] System.Globalization.Tests.CultureInfoConstructor.Ctor_String(name: "prs", expectedNames: ["prs"], expectToThrowOnBrowser: True)
> Assert.Contains() Failure
> Not found: fa
> In value:  String[] ["prs"]
>    at System.Globalization.Tests.CultureInfoConstructor.Ctor_String(String name, String[] expectedNames, Boolean expectToThrowOnBrowser) + 0xa0
>    at System.Globalization.Nls.Tests!<BaseAddress>+0x8a7760
>    at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x14c
> [FAIL] System.Globalization.Tests.CultureInfoConstructor.Ctor_String(name: "prs-AF", expectedNames: ["prs-AF"], expectToThrowOnBrowser: True)
> Assert.Contains() Failure
> Not found: fa-AF
> In value:  String[] ["prs-AF"]
>    at System.Globalization.Tests.CultureInfoConstructor.Ctor_String(String name, String[] expectedNames, Boolean expectToThrowOnBrowser) + 0xa0
>    at System.Globalization.Nls.Tests!<BaseAddress>+0x8a7760
>    at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x14c
> [FAIL] System.Globalization.Tests.NumberFormatInfoMiscTests.DigitSubstitutionListTest(cultureName: "prs", shape: NativeNational)
> Assert.Equal() Failure
> Expected: Context
> Actual:   NativeNational
>    at System.Globalization.Tests.NumberFormatInfoMiscTests.DigitSubstitutionListTest(String cultureName, DigitShapes shape) + 0x54
>    at System.Globalization.Nls.Tests!<BaseAddress>+0x89e604
>    at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x14c
> ```

I saw this.  Typically it's because it's the newest windows we've tested on and @tarekgh magically shows up and makes the tests understand the new world and/or fixes the bugs.

**Comment by tarekgh** [comment]
@MattGal is correct, Windows can change the underlying globalization data. But I expect this test will fail on all Windows 11 and not only arm64 except if the Windows 11 arm64 somehow carries different data. But, in general this shouldn't block the PR as it is most likely a globalization data or test issue.

**Comment by MattGal** [comment]
@tarekgh one thing to note here is that currently the only Windows 11 ARM SKU in Azure is a "preview" SKU; it's slightly newer than the AMD64 versions.

**Comment by MattGal** [comment]
Looks like the issues with `System.Globalization.Extensions.Nls.Tests` continue.  Just wanted to add here that it might be time to disable this test on Windows 11 til it can be investigated and fixed to match the changing OS conditions, since we'll be rolling out changes to forward the deprecated Windows 10 ARM queues to the Windows 11 versions next month (approximately 1/11/2023)

**Comment by MichalStrehovsky** [comment]
> Looks like the issues with `System.Globalization.Extensions.Nls.Tests` continue. Just wanted to add here that it might be time to disable this test on Windows 11 til it can be investigated and fixed to match the changing OS conditions, since we'll be rolling out changes to forward the deprecated Windows 10 ARM queues to the Windows 11 versions next month (approximately 1/11/2023)

Yeah, I was hoping we wouldn't have to do that, but maybe blocking them just on ARM64 Windows is still fine. We still get results from x64 Windows and chances for an arch-specific bug cropping in globalization while it's disabled are pretty low.

Pushed out a commit that blocks them.

**Comment by MichalStrehovsky** [comment]
Looks good to merge. The failures in the runtime legs are all known per build analysis. Runtime-extra-platforms has a lot of failures but it's par for the course. None of the legs are Arm64 Windows.

**Pull request merged**
