### PR TITLE
Fix double expansion of AggregateException.Flatten message

### PR DESCRIPTION
**Pull request by pentp**
Re-created from #133 without updating tests as live built dependencies are still not available.
Will create a separate PR for adding test coverage.

### CODE REVIEW

**Comment by danmosemsft** [comment]
Thanks, it would be good to review the test PR before merging this. (We are very close to being able to have a corelib change and its tests in the same PR, finally enabled by the repo consolidation...)

**Comment by pentp** [comment]
The test changes are visible from the previous #133 PR (which was already approved). If I created the tests PR now it would just fail.

**Comment by pentp** [comment]
The build failures look unrelated - every PR has this arm checked build failing.

**Comment by danmosemsft** [comment]
triggering CI again -- BTW to do this yourself, since you don't have the power to do /azp commands unfortunately, it's easiest to do git commit --amend add a space to the description and thus force a new SHA, then push that.

**Comment by pentp** [comment]
It seems that just closing/re-opening didn't clear the ARM test results, so I force pushed the commit with an amended message as you recommended.

**Comment by pentp** [comment]
It feels like it's impossible to get the CI green - every time some random part of it falls apart with helpful errors like:
```
exec failed: container_linux.go:344: starting container process caused "process_linux.go:95: adding pid 38211 to cgroups caused \"failed to write 38211 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/57ef0fb8bcbc2e410ee9bf48b611a08ec104e0656c578e6c2b8195d1dd3401eb/cgroup.procs: invalid argument\"": unknown

The job running on agent NetCorePublic-Pool 59 ran longer than the maximum time of 60 minutes.

// Helix "Failure logs" that contain zero errors...

**Review by stephentoub — APPROVED** [review]
Thanks.

**Pull request merged**
