### PR TITLE
Move _OOP_find_proc_info to libunwind

### PR DESCRIPTION
**Pull request by am11**
Upstream PR: https://github.com/libunwind/libunwind/pull/377.

### CODE REVIEW

**Review by mikem8361 — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]
LGTM. Waiting for upstream.

**Comment by am11** [comment]
@AaronRobinsonMSFT, the upstream PR is merged.

**Comment by AaronRobinsonMSFT** [comment]
@am11 I'm just running the CI till we see green. It was timed out on a Linux leg so technically these changes impact that. I doubt there is anything here though I do like to ensure we have a green CI for upstream alignment.

**Pull request merged**
