### PR TITLE
Update NugetProjectModelVersion and NugetPackagingVersion

### PR DESCRIPTION
**Pull request by agocke**
(cherry picked from commit 97c96d4c39722070ad86b375e3613d22b22e0e95)

### CODE REVIEW

**Review by carlossanlop — APPROVED** [review]
Assuming the CI looks good, LGTM.

Was there a reason why you decided to only cherry-pick one of the two commits? https://github.com/dotnet/runtime/pull/88107/files

Friendly reminder: If you'd like this to be included in the December release, please merge it before Tuesday November 14th EOD (Code Complete).

**Comment by carlossanlop** [comment]
CI failure is https://github.com/dotnet/runtime/issues/91987

**Review by ViktorHofer — APPROVED** [review]

**Comment by akoeplinger** [comment]
> Was there a reason why you decided to only cherry-pick one of the two commits? [#88107 (files)](https://github.com/dotnet/runtime/pull/88107/files)

The release/7.0 Version.Details.xml doesn't have entries for these packages.

FYI this currently targets release/7.0 instead of release/7.0-staging.

**Review by akoeplinger — APPROVED** [review]

**Comment by carlossanlop** [comment]
> FYI this currently targets release/7.0 instead of release/7.0-staging.

Since today is Code Complete, this can stay targeting the release/7.0 branch, to save time. The change will automatically flow into staging, that's less urgent.

**Comment by agocke** [comment]
Yup, version.details.xml doesn't have this. I'm not trying to fix that in this PR.

**Pull request merged**
