### PR TITLE
Remove harvesting of M.E.DependencyModel

### PR DESCRIPTION
**Pull request by ViktorHofer**
The netstandard1.6 configuration of Microsoft.Extensions.DependencyModel
isn't built anymore. Instead the already built matching binary from the
latest available package version is redistributed when packaging the
DependencyModel library.

Also dropping the netstandard1.3 asset and the net451 one as the
minimum supported set of platforms are ones that support netstandard2.0.

In addition to the harvesting removal, cleaning up the src project which
had an unnecessary condition and property set.

Contributes to https://github.com/dotnet/runtime/issues/47530

cc @terrajobst @ericstj

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
Thanks @ViktorHofer !

**Comment by ViktorHofer** [comment]
> .packages\microsoft.dotnet.build.tasks.packaging\6.0.0-beta.21216.2\build\Packaging.targets(1119,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Microsoft.Extensions.DependencyModel should be supported on .NETCoreApp,Version=v1.0/win7-x86 but has no compile assets.

@ericstj what tells the packaging system that the lib should be supported on netcoreapp1.0? I'm missing some context here.

**Comment by ericstj** [comment]
IIRC it's looking at the previous package and determining what it supported when deciding what the new package should support.  You should be able to repro relatively cheaply locally by building the pkgproj and examining the binlog.  

> cleaning up the src project which had an unnecessary condition and property set.

Might be other places to clean that up: https://github.com/dotnet/runtime/pull/39099#discussion_r454622717

**Review by ericstj — APPROVED** [review]

**Comment by ericstj** [comment]
Looks like this now has a merge conflict.

**Comment by ViktorHofer** [comment]
The PR is ready. I'm now using the new packaging hook to exclude frameworks from validation which aren't supported anymore.

**Review by ericstj — APPROVED** [review]

**Review by eerhardt — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Network flakiness:

```
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f81b940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/certifi/
  Could not find a version that satisfies the requirement certifi==2020.6.20 (from -r /root/helix/scripts/runtime_python_requirements.txt (line 1)) (from versions: )
No matching distribution found for certifi==2020.6.20 (from -r /root/helix/scripts/runtime_python_requirements.txt (line 1))
```

**Pull request merged**
