### PR TITLE
[mono] Preserve FirstChanceExceptionEventArgs ctor

### PR DESCRIPTION
**Pull request by akoeplinger**
The runtime is creating the exception so we need to preserve it.
See https://github.com/xamarin/xamarin-android/issues/6626

While looking at this I noticed that `FirstChanceExceptionEventArgs` is in ExceptionNotification.cs for some reason, fixed the filename to match the type name.

Use DynamicDependency for preserving `FirstChanceExceptionEventArgs` and `UnhandledExceptionEventArgs`

### CODE REVIEW

**Comment by marek-safar** [comment]
We try to avoid using descriptors if possible. I think a better fix would be to add it as DynamicDependencyAttribute to 

```
        public static event EventHandler<FirstChanceExceptionEventArgs>? FirstChanceException;
```

**Review by stephentoub — APPROVED** [review]

**Comment by akoeplinger** [comment]
@marek-safar I tried but it doesn't compile:
```
error CS0592: Attribute 'DynamicDependency' is not valid on this declaration type. It is only valid on 'constructor, method, field' declarations.
```

**Comment by marek-safar** [comment]
> I tried but it doesn't compile:

Looks like bad API design but it should be possible to use the underlying target. Try this instead

```c#
[field: DynamicDependency ()]
```

**Comment by akoeplinger** [comment]
@marek-safar that worked :) I switched over UnhandledExceptionEventArgs too

**Review by marek-safar — APPROVED** [review]

**Pull request merged**
