### PR TITLE
Fix `ASG struct (copy)` with different src and dst sizes after global morph.

### LINKED ISSUE #39128: Fix `ASG struct (copy)` with different src and dst sizes after global morph.
https://github.com/dotnet/runtime/pull/39066#issue-447380794 has a detailed description of the issue, shortly we should not allow IR with mismatched src and dst size under `ASG struct (copy) like:
```
               [000008] -A-XG+------              *  ASG       struct (copy)
               [000000] D----+-N----              +--*  LCL_VAR   struct<B, 8> V02 loc1 <- 8 byte size
               [000004] ---XG+-N----              \--*  IND       byte                                 <- 1 byte size
               [000003] *--XG+------                 \--*  IND       long   Zero Fseq[a]
               [000002] -----+------                    \--*  LCL_VAR   long   V00 arg0
```

I am going to:
1. reenable the IL test;
2. finish the fix in `fgMorphCopyBlock` (https://github.com/sandreenko/runtime/commit/6b07be7b4680acda48e5d3ef916429b738ae15bf);
3. add more asserts and reenable the optimization;
4. check how it works for primitive types and sizes that do not match struct borders;

### PR DESCRIPTION
**Pull request by sandreenko**
Fixes #39128 and adds IL test back (the issue was in using i8 instead of inative on x86).

I want to keep the transformation enabled for minopts, I think it is not dangerous after this fix and could give us better TP (logic for storeind is smaller in codegen), but I have not measured.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Would strongly recommend not enabling this for minopts, so we have a way users can work around this if issues arise. If you think it is beneficial for Tier0, we can consider enabling as part of #9120.

Also would like to see some more widespread testing of WPF.

**Comment by sandreenko** [comment]
> Would strongly recommend not enabling this for minopts, so we have a way users can work around this if issues arise. If you think it is beneficial for Tier0, we can consider enabling as part of #9120.

Ok, I will disable this for minopts. However, we have only one check for `OptimizationEnabled` in lower* files and all other optimization transformations are happening in in minopts, so I do not see why this should be different. 

> Also would like to see some more widespread testing of WPF.

In general or in this PR? I have checked other scenarios similar to what was causing the issue, like copying a primitive and copying size that doesn't match field/struct sizes, but they did not show any new issues.

**Comment by AndyAyersMS** [comment]
> optimization transformations are happening in in minopts

This is a bad precedent. We really should back off on those optimizations as well.  If we think they're generally safe and TP improvements we can enable them in Tier0 too.

> > Also would like to see some more widespread testing of WPF.

> In general or in this PR? I have checked other scenarios similar to what was causing the issue, like copying a primitive and copying size that doesn't match field/struct sizes, but they did not show any new issues.

I'm mostly concerned about properly handling the variety of pinvokes and struct marshalls that run as part as WPF, and also more thorough testing of C++/CLI created IL that also is used there.

I'd prefer it be part of this PR. Since this will be manual testing, we should also write up how to do it in case we want to run it again.

**Comment by sandreenko** [comment]
> This is a bad precedent. We really should back off on those optimizations as well. If we think they're generally safe and TP improvements we can enable them in Tier0 too.

I have added the check for `TryTransformStoreObjAsStoreInd`.

> I'd prefer it be part of this PR. Since this will be manual testing, we should also write up how to do it in case we want to run it again.

Unfortunately, it did not happen. Still I think it is safer to get this change in Prev8 and get testing from WPF there than in RC1.

**Review by CarolEidt — APPROVED** [review]
The changes LGTM, and I would agree with @AndyAyersMS that the transformation should be disabled for minopts.

**Review by AndyAyersMS — APPROVED** [review]
I have pinged the WPF contributors and haven't heard back. Let's keep trying to work up some plan for doing better WPF testing.

cc @mangod9

**Pull request merged**
