### PR TITLE
Fix OSX like Test Failure on Socket.Connect

### LINKED ISSUE #89166: [mono] Tests `System.Net.Sockets.Tests.Connect*` failing with `Can't assign requested address`
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=343954

Affected pipelines:
- runtime-extra-platforms

Build error legs:
- net8.0-tvossimulator-Release-x64-Mono_Release-OSX.1200.Amd64.Open
- net8.0-iossimulator-Release-x64-Mono_Release-OSX.1200.Amd64.Open
- net8.0-maccatalyst-Release-arm64-Mono_Release-OSX.1200.Arm64.Open
- net8.0-maccatalyst-Release-x64-Mono_Release-OSX.1200.Amd64.Open

Tests failing: 
- `System.Net.Sockets.Tests.Connect*`

Pull request: https://github.com/dotnet/runtime/pull/88723

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Can't assign requested address",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[344887](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344887)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344887&view=ms.vss-test-web.build-test-results-tab&runId=7212286&resultId=194741)|dotnet/runtime#88167|
|[344698](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344698)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344698&view=ms.vss-test-web.build-test-results-tab&runId=7207360&resultId=194741)||
|[344603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344603)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344603&view=ms.vss-test-web.build-test-results-tab&runId=7203854&resultId=194735)|dotnet/runtime#85694|
|[344129](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344129)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=344129&view=ms.vss-test-web.build-test-results-tab&runId=7194170&resultId=194718)||
|[343954](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343954)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343954&view=ms.vss-test-web.build-test-results-tab&runId=7190862&resultId=194687)|dotnet/runtime#88723|
|[343204](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343204)|dotnet/runtime|[System.Net.Sockets.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=343204&view=ms.vss-test-web.build-test-results-tab&runId=7170578&resultId=194686)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|5|6|6|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=343954
**Error message validated:** `Can't assign requested address`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/19/2023 8:03:40 AM UTC

### PR DESCRIPTION
**Pull request by liveans**
Fixes #89166

### CODE REVIEW

**Review by MihaZupan — APPROVED** [review]
Thanks

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by liveans** [comment]
CI failures unrelated

**Pull request merged**
