### PR TITLE
Reintroduce typo in ICorDebug public API names

### LINKED ISSUE #76960: CoreCLR 7.0 have changed public Debug API. Why?
Hello,

could you please clarify, why in https://github.com/dotnet/runtime/commit/3ea30ed321949d238bf97534a2a8cbabf580f238
public Debug API was changed:

`ICorDebugArrayValue::GetBaseIndicies` https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/icordebugarrayvalue-getbaseindicies-method?view=aspnetcore-2.1
was changed from `GetBaseIndicies` to `GetBaseIndices`

`ICorDebugArrayValue::HasBaseIndicies` https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/debugging/icordebugarrayvalue-hasbaseindicies-method?view=aspnetcore-2.1
was changed from `HasBaseIndicies` to `HasBaseIndices`

CC @alpencolt  @jkotas

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #76960

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Review by am11 — APPROVED** [review]
Oops, didn’t realized that it is public. Thanks! :)

**Review by hoyosjs — APPROVED** [review]

**Review by tommcdon — APPROVED** [review]

**Comment by teo-tsirpanis** [comment]
Why reintroduce the typo? It is only a source, not a binary breaking change, and has been done before in #60999 (though I can see the argument that maybe this typo has existed for longer).

**Comment by vargaz** [comment]
This seems to have broken the mono build, CI didn't run the mono lanes on this PR:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=50983&view=logs&j=d3cc09f4-7598-5083-c32b-3d75aa946de0&t=69808874-331d-5f38-5702-6a7cd5ef963b&l=2334

**Comment by akoeplinger** [comment]
This is another case where the missing mscordbi trigger path is causing mono build breaks (https://github.com/dotnet/runtime/pull/76832#issuecomment-1274105090), we need to add these paths to the trigger.

**Pull request merged**
