### PR TITLE
[wasm] spread WS based timers over next 6 minutes to prevent heavy throttling

### LINKED ISSUE #51041: [WASM] Chrome timer throttling affects runtime
Chrome recently turned on [intensive timer throttling](https://docs.google.com/document/d/11FhKHRcABGS4SWPFGwoL6g0ALMqrFKapCk5ZTKKupEk/view). The side-effect of this is that code that relied on timers firing at certain intervals may not work as expected. We first got reports of this issue with the SignalR Javascript library (https://github.com/dotnet/aspnetcore/issues/31079), as it relies on client and server pings to detect connection closures. In addition, the SignalR .NET Client library has the same issue as it uses a timer to send the same pings.

The Javascript library was fixed by relying on
>Intensive throttling is not applied to timers that are scheduled from a network response handler

-https://bugs.chromium.org/p/chromium/issues/detail?id=1186569#c3

The Javascript fix is at https://github.com/dotnet/aspnetcore/pull/31300 for reference.

Unfortunately, the .NET client can not do the same thing because it uses .NET patterns (async await) which go through the wasm runtime. The wasm runtime very likely uses timers for scheduling work which will be chained and have throttling applied to them.

Specifically, I was noticing that when using a System.IO.Pipeline, calling `FlushAsync` on a Pipe and `ReadAsync` from another thread was taking more than 30 seconds for the `ReadAsync` to return after `FlushAsync` finished.

TLDR:
Wasm Runtime uses timers which will be throttled on Chrome, this can result in poor behavior for apps.

A potential change that could be made is to restart timers on network handlers so they aren't throttled.

cc @lewing @davidfowl @halter73

### PR DESCRIPTION
**Pull request by pavelsavara**
## Problem
Chromium browsers throttle `setTimeout` frequency on inactive pages to 1 sec almost immediately. 
5 minutes later they throttle heavily to wakeup each 60 seconds. 
That breaks dotnet `Timer` expectations and also threadpool.

The heavy throttling could be lifted back to 1sec if there was WebSocket activity.
https://developer.chrome.com/blog/timer-throttling-in-chrome-88/#intensive-throttling

## Implementation
The idea is to cover the future 6 minutes with "wakeup" timer, each 1 second apart from each other.
1 second, because is the light throttling rate, so it would not help to try to do it more often.
It should be triggered from WS event, so that it's only 1 deep from it. 
Every subsequent call would schedule only for uncovered future.

There is `[OuterLoop]` unit test for this.

Fixes https://github.com/dotnet/runtime/issues/51041

### CODE REVIEW

**Comment by pavelsavara** [comment]
The idea is to cover the future 6 minutes with "wakeup" timer, each 1 second apart from each other.
Because 1 second is the light throttling rate, so it would not help to try to do it more often.
It should be triggered from WS event, so that it's only 1 deep from it. Every subsequent call would schedule only for uncovered future.

Right now, I'm not clear if 6 minutes is right time span.
Also I plan to implement OuterLoop unit test for it yet.

**Comment by pavelsavara** [comment]
This is necessary infrastructure change for the automated test. It's still quite fragile.
https://github.com/dotnet/xharness/pull/695

**Comment by pavelsavara** [comment]
This needs to be merged only after new xharness binaries flow in.

**Review by kg — APPROVED** [review]
Everything looks fine to me

**Pull request merged**
