### PR TITLE
[Arm64] Simplify logic for RMW hardware intrinsics

### PR DESCRIPTION
**Pull request by echesakov**
This removes ` HW_Flag_NoRMWSemantics` and add inverse `HW_Flag_HasRMWSemantics` on Arm64 - since most of the intrinsics on Arm64 will be no-RMW.

I ended up removing all the custom handling in `LinearScan::BuildHWIntrinsic()` in lsraarm.cpp:

1) I am not sure why we allocate an internal register with `buildInternalFloatRegisterDefForNode` for `Sha1_HashUpdateChoose`, `Sha1_HashUpdateMajority`, `Sha1_HashUpdateParity` and `Sha1_FixedRotate` - their codegen are table-driven and makes no use of the register in hwintrinsiccodegenarm64.cpp .

2) I couldn't find a good reason why we are checking `!op2->isContained()` for `Sha1_ScheduleUpdate0`, `Sha256_HashUpdate1`, `Sha256_HashUpdate2` and `Sha256_ScheduleUpdate1` - there are only one - *"all operands are registers"* form exist for the underlying instructions and I don't see how the operands can be contained.

In addition, I discovered that `setTgtPref` was never called on Arm64 - meaning setting `tgtPrefUse` had no effect on LSRA decisions. The function and the calls to it were under `ifdef TARGET_XARCH` and I enabled them now also on all the platforms supporting FEATURE_HW_INTRINSICS (which effectively adds Arm64 but could potentially be Arm32 if we ever decide to support hardware intrinsics on this platform). I though about guarding all the places that uses/initializes `tgtPrefUse` and `tgtPrefUse2` with the same `ifdef`-s - so we wouldn't end up setting them up if they are not actually used.

In addition, I removed special codegen handling for `Aes_Decrypt`, `Aes_Encrypt` and `AdvSimd_ExtractAndNarrowHigh` - the logic is implemented universally for all RMW intrinsics.

I realized that we don't have tests for Sha1 and Sha256 - I will add these as a separate change.

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@CarolEidt @dotnet/jit-contrib PTAL

**Review by CarolEidt — APPROVED** [review]
LGTM - thanks @echesakovMSFT

**Comment by kunalspathak** [comment]
Is `op->isContained()` and presence of `HW_Flag_NoContainment` on an instruction related? Are there more changes coming to remove the unused `HW_Flag_NoContainment` flag for ARM64 too because it is not used currently.

**Comment by echesakovMSFT** [comment]
> Is op->isContained() and presence of HW_Flag_NoContainment on an instruction related?

`GenTree::isContained()` is set during `Lowering::ContainCheckHWIntrinsic()` in lowerarmarch.cpp which currently does nothing since all the intrinsics marked as `HW_Flag_NoContainment`. 

>  Are there more changes coming to remove the unused HW_Flag_NoContainment flag for ARM64 too because it is not used currently.

I am planning to invert this flag to `HW_Flag_SupportsContainment` on Arm64 in the same way, mark some of the intrinsics (i.e. `AdvSimd.Insert` I am currently working on) with this flag and add containment analysis for them.

**Pull request merged**
