### PR TITLE
Introduce insGroup/instrDesc backwards navigation

### PR DESCRIPTION
**Pull request by BruceForstall**
Currently, it is only possible to walk forwards in insGroup/instrDesc data: insGroup are in a single-linked list, and variable-sized instrDesc are packed into a memory array where function `emitSizeOfInsDsc()` can tell you the size of an instrDesc, and `emitAdvanceInstrDesc()` can advance an `instrDesc*` forward, but there is no facility for walking to the previous instrDesc.

This change introduces a `igPrev` pointer so the insGroup list is doubly-linked. Also, each instrDesc is annotated with 4 or 5 bits of data indicating how large the previous instruction in the buffer is, so it is possible to find it by subtracting that size from a `instrDesc*`. Also, each insGroup maintains an `igLastIns` pointer to the last instruction in the group, to allow seeding the backwards walk.

The instrDesc backwards walk data is taken from the "small constant" area, so some small constants get pushed to using larger instrDesc sizes.

Walking backwards is done using `emitGetLastIns()` to find the last instruction in the function, and `emitPrevID()` to walk to the previous one.

This information is currently only used in the JitDump.

Basic measurement of the benchmarks SPMI collection showed about a 2.5% increase in emitter memory usage.

### CODE REVIEW

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/80589

**Comment by kunalspathak** [comment]
> [Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=141998&view=ms.vss-build-web.run-extensions-tab)
> 
> TP results: x64/x86: +0.04% full-opts, +0.11% MinOpts arm64: a wash, actually a -0.03% win on MinOpts, +0.01% on full-opts

That's not bad. I am just pasting the screenshot in case the build info gets deleted in future.

image

> 2.5% increase in emitter memory usage.

So, something to think about.

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib Here's an experiment I wrote to implement full backwards navigation support in MIR (emitter insGroup/instrDesc lists). The throughput impact is minimal and the memory increase might be small enough to not matter.

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib PTAL. I propose to check this in under `#ifdef`, disabled, under the assumption we might need this or something like it in the near future. (If it ends up we don't need it, or end up with something else, it's easy enough to remove.)

**Comment by kunalspathak** [comment]
Overall looks good approach. I am wondering if we should enable a small optimization using this functionality to verify if it is working as expected?

**Comment by BruceForstall** [comment]
> I am wondering if we should enable a small optimization using this functionality to verify if it is working as expected?

There are the asserts and verifications I added. Also, I think @TIHan has some ideas for something that could use this.

**Comment by BruceForstall** [comment]
@TIHan @dotnet/jit-contrib I would still like to merge this change (with the new feature disabled). Code review?

**Comment by TIHan** [comment]
Hey @BruceForstall , I'll look at thoroughly in the morning - quick glance as it looks fine to me assuming we are ok with the TP and memory costs.

**Comment by BruceForstall** [comment]
> assuming we are ok with the TP and memory costs.

Note that all this code is disabled for now, so the decision about memory/TP cost will have to come along with an optimization client that wants to turn it on.

**Review by TIHan — APPROVED** [review]

**Comment by TIHan** [comment]
Will need to use this asap for two peephole opts that I want to do.

**Pull request merged**
