### PR TITLE
#50880 remove exclusion line for collection tests

### PR DESCRIPTION
**Pull request by mkhamoyan**

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by MaximLipnin** [comment]
`System.Collections.Tests` pass on Android:

https://helix.dot.net/api/jobs/941a113a-f335-482f-aa75-49154deba326/workitems/System.Collections.Tests?api-version=2019-06-17

**Review by MaximLipnin — APPROVED** [review]

**Comment by steveisok** [comment]
It looks like the android x64 failure is due to not processing the xml results for whatever reason.  If you look at the logcat, the tests all pass.

**Comment by steveisok** [comment]
The windows x64 failure is a known issue.

**Pull request merged**
