### PR TITLE
Fix OCSP test responder to omit fractional seconds

### LINKED ISSUE #77408: DynamicRevocationTests fails on macOS 13
43 of the scenarios for DynamicRevocationTests fail on macOS 13 (aka Ventura). Most of them fail with an error like:

```plain
        ---- Assert.Equal() Failure
                                     ↓ (pos 2)
        Expected: [NoError, NoError, Revoked]
        Actual:   [NoError, NoError, RevocationStatusUnknown]
```

### PR DESCRIPTION
**Pull request by vcsjones**
Closes #77408

### CODE REVIEW

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
Doh. That was the wrong outerloop.

/azp run runtime-libraries-coreclr outerloop

**Comment by vcsjones** [comment]
S.S.Cryptography outerloop passed. None of the outerloop failures appear related, and this is a test only change. Merging.

**Comment by vcsjones** [comment]
@bartonjs should this test-only change be back ported to release/7.0 or release/6.0 so that if/when those pick up Ventura the tests won't start failing?

**Comment by bartonjs** [comment]
Your question has certainly sold me on the value of the backport; and test-only changes are generally taken.  So, yes :smile:

**Pull request merged**
