### PR TITLE
Remove _init and _fini exports from NAOT and update android docs

### LINKED ISSUE #92272: .NET 8 RC1: NativeAOT fails to build for linux-bionic-arm64 when specifying project as library (Linker error)
### Description

I was trying out .NET 8 RC1 for NativeAOT for android bionic, and I get an error regarding ld.lld with a missing symbol for `_init` and `_fini`.

### Reproduction Steps

Using the default steps to make a NativeAOT project for android:

`dotnet new console -o HelloBionic --aot`

open the csproj and edit the type to `Library` instead of `Exe`

Finally, change the `Program.cs` file to not use top-level statements. Something empty such as an empty namespace and/or class should suffice.

`dotnet publish -r linux-bionic-arm64 -p:DisableUnsupportedError=true -p:PublishAotUsingRuntimePack=true`

### Expected behavior

It should create the library rather than error. It creates the executable properly when it's set as `Exe`.

### Actual behavior

Get error:

```
ld.lld : error : version script assignment of 'V1.0' to symbol '_init' failed: symbol not defined [HelloBionic\HelloBionic.csproj]
ld.lld : error : version script assignment of 'V1.0' to symbol '_fini' failed: symbol not defined [HelloBionic\HelloBionic.csproj]
clang : error : linker command failed with exit code 1 (use -v to see invocation) [HelloBionic\HelloBionic.csproj]

...\.nuget\packages\microsoft.dotnet.ilcompiler\8.0.0-rc.1.23419.4\build\Microsoft.NETCore.Native.targets(364
,5): error MSB3073: The command ""clang" "obj\Release\net8.0\linux-bionic-arm64\native\HelloBionic.o" -o "bin\Release\n
et8.0\linux-bionic-arm64\native\HelloBionic.so" -Wl,--version-script=obj\Release\net8.0\linux-bionic-arm64\native\Hello
Bionic.exports -gz=zlib -fuse-ld=lld ...\.nuget\packages\microsoft.netcore.app.runtime.nativeaot.linux-bionic
-arm64\8.0.0-rc.1.23419.4/runtimes/linux-bionic-arm64/\native\libbootstrapperdll.o ...\.nuget\packages\micros
oft.netcore.app.runtime.nativeaot.linux-bionic-arm64\8.0.0-rc.1.23419.4/runtimes/linux-bionic-arm64/\native\libRuntime.
WorkstationGC.a ...\.nuget\packages\microsoft.netcore.app.runtime.nativeaot.linux-bionic-arm64\8.0.0-rc.1.234
19.4/runtimes/linux-bionic-arm64/\native\libeventpipe-disabled.a ...\.nuget\packages\microsoft.netcore.app.ru
ntime.nativeaot.linux-bionic-arm64\8.0.0-rc.1.23419.4/runtimes/linux-bionic-arm64/\native\libstdc++compat.a ...\.nuget\packages\microsoft.netcore.app.runtime.nativeaot.linux-bionic-arm64\8.0.0-rc.1.23419.4/runtimes/linux-bionic-
arm64/\native\libSystem.Native.a ...\.nuget\packages\microsoft.netcore.app.runtime.nativeaot.linux-bionic-arm
64\8.0.0-rc.1.23419.4/runtimes/linux-bionic-arm64/\native\libSystem.IO.Compression.Native.a ...\.nuget\packag
es\microsoft.netcore.app.runtime.nativeaot.linux-bionic-arm64\8.0.0-rc.1.23419.4/runtimes/linux-bionic-arm64/\native\li
bSystem.Security.Cryptography.Native.OpenSsl.a --target=aarch64-linux-android21 -g -Wl,-rpath,"$ORIGIN" -Wl,--build-id=
sha1 -Wl,--as-needed -Wl,-e0x0 -pthread -ldl -lz -llog -lm -shared -Wl,-z,relro -Wl,-z,now -Wl,--eh-frame-hdr -Wl,--dis
card-all -Wl,--gc-sections -Wl,-T,"obj\Release\net8.0\linux-bionic-arm64\native\sections.ld"" exited with code 1. [...\HelloBionic\HelloBionic.csproj]
```

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

.NET version: 8.0.100-rc.1.23455.8
OS: Windows 10 (constantly updated so I assume latest version)
Architecture: x64
I'm not sure if it's specific to this configuration

### Other information

_No response_

### PR DESCRIPTION
**Pull request by am11**
@CasualPokePlayer found an alternative workaround to publish apps with latest NDK (LTS): https://github.com/dotnet/runtime/issues/92272#issuecomment-2041629555

@josephmoresena, @LittleCodingFox, could you please confirm if this works with your setup (presumably with older NDK)? If not, we can keep both workarounds in the docs for now and later we can look into implementing small introspection to detect either-or cases in BuildIntegration to automate it.

Fixes https://github.com/dotnet/runtime/issues/92272

### CODE REVIEW

**Comment by josephmoresena** [comment]
The last NDK I used was 26 with NativeAOT-AndroidHelloJniLib was 26, I just avoid these LinkerArg elements.
In my repo you can see:
       < ItemGroup Condition="$(IsAndroid) == 'true' And $(UseLibCSections) == 'true'">
		< LinkerArg Include="-Wl,--defsym,_init=__libc_init" />
		< LinkerArg Include="-Wl,--defsym,_fini=__libc_fini" />
	< /ItemGroup>
I don't remember until which NDK version the __libc_init and __libc_fini where exported as default.

**Comment by CasualPokePlayer** [comment]
Doing some investigation, I don't think the older workaround was appropriate at all. `__libc_init` has a completely different function prototype compared to `_init` (and `__libc_init` is normally just called within the `_start` ELF entrypoint with its expected arguments, eventually calling `main`).

`_fini` similarly has a different function prototype compared to `__libc_fini` (`__libc_fini` is just expected to be called due to it being internally registered with `__cxa_atexit` during the `__libc_init` call).

Note however, `_start` won't actually be present if building as a shared library (entrypoint is just NULL, i.e. no entrypoint, no need to call `__libc_init`; handling other libc init/fini is handled with other methods which aren't too relevant).

In more "standard" glibc Linux (and presumably also musl?), you'd get `_init`/`_fini` end up being implemented by parts of the libc (well, provided .o files which normally get linked in with a standard compiler setup when compiling, similar to `_start`). However, it just seems that this is not provided at all on bionic. Of course, user could in theory provide them and they would act the first/last ever functions called (before/after even `__attribute__((constructor))`/`__attribute__((destructor))` implemented functions), but that's not a detail which .NET would need to really care about (well, if this is done it'd probably be in unmanaged code anyways, I doubt a C# function would work for this case).

**Comment by am11** [comment]
Thanks for the further research @CasualPokePlayer, very thorough! If the signatures are mismatched, then this workaround makes more sense the the old one. I'll mark the PR ready for review.

As to the fix: @josephmoresena, since you added it the global symbols in export list (long time ago), https://github.com/dotnet/corert/commit/88d75715f4c84c383365a33734d6f0cffe837061#diff-c9020f726343209ae19211774789db0cb46bcc828f448c07ef62cb6a552b93a8R49 (current location in this repo: `src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ExportsFileWriter.cs`), do you see any potential harm in deleting that line? I think it should be fine as the final linkage will take care of platform/libc specific choices.

**Comment by am11** [comment]
This can use `/azp run runtime-nativeaot-outerloop` checks.

**Comment by LittleCodingFox** [comment]
Thanks for the help guys, I've been busy so I can't really test this right now, but it looks like you got this!

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!

**Pull request merged**
