### PR TITLE
Upgrade StyleCopAnalyzers to v1.2.0-beta.304

### PR DESCRIPTION
**Pull request by xtqqczze**
Follow-up to #45562.

### CODE REVIEW

**Review by sharwell — APPROVED** [review]

**Comment by xtqqczze** [comment]
@danmosemsft Could you look at test failures?

**Comment by xtqqczze** [comment]
Still seeing failures in `microsoft.dotnet.helix.sdk`.

**Comment by jkotas** [comment]
Opened #45654 on the CI failure

**Comment by xtqqczze** [comment]
Can we use dependabot to manage the nuget package?

**Pull request merged**
