### PR TITLE
Fix \u00A7 char Unicode category

### LINKED ISSUE #41333: Test Failure: System.Tests.CharTests.GetUnicodeCategory_Char_AllInputs
The  test `System.Tests.CharTests.GetUnicodeCategory_Char_AllInputs` is failing consistently in outerloop.

<pre>
X System.Tests.CharTests.GetUnicodeCategory_Char_AllInputs [1s 656ms]
  Error Message:
   char.GetUnicodeCategory('\u00A7') returned wrong value.
Expected: OtherPunctuation
Actual:   OpenPunctuation
  Stack Trace:
     at System.Tests.CharTests.GetUnicodeCategory_Char_AllInputs() in /code/personal/dotnet/runtime/src/libraries/System.Runtime/tests/System/CharTests.cs:line 1140
</pre>

Seen in #41173 and can also reproduce it locally.

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/41333

### CODE REVIEW

**Comment by tarekgh** [comment]
@GrabYourPitchforks I have missed one character fix in my last fix. so this change is just fixing this character.

**Comment by tarekgh** [comment]
CC @safern

**Comment by GrabYourPitchforks** [comment]
Does this mean we're missing a test? Presumably if we had a test that compared `char.GetUnicodeCategory` vs `Rune.GetUnicodeCategory` (and `IsUpper` / `IsLower` / ...) for the values 0 .. 255, it would catch problems like this. The `Rune` unit tests are already fed directly by _UnicodeData.txt_.

**Review by GrabYourPitchforks — APPROVED** [review]

**Comment by GrabYourPitchforks** [comment]
Followed up with Tarek offline. Apparently something got altered in the PR during submission, and the outerloop tests did properly catch this. So life is good. :)

**Comment by tarekgh** [comment]
https://github.com/dotnet/docs/issues/20246
https://github.com/dotnet/runtime/pull/41200
https://github.com/dotnet/runtime/issues/10990
https://github.com/dotnet/runtime/pull/41285

**Review by safern — COMMENTED** [review]
LGTM

**Comment by tarekgh** [comment]
thanks @safern could you approve the porting one too https://github.com/dotnet/runtime/pull/41361?

**Pull request merged**
