### PR TITLE
[mono] Implement all Ssse3 and Sse42 intrinsics

### PR DESCRIPTION
**Pull request by EgorBo**
Implement all `Ssse3` and `Sse42` intrinsics for LLVM back-end.
`Sse41` is left over (that's why `Sse42.IsSupported` still returns false always outside of corelib)

Godbolt: https://godbolt.org/z/7cd7q5

### CODE REVIEW

**Review by filipnavara — COMMENTED** [review]
I read it and it LGTM, will do some more testing during the week. There's still `CompareGreaterThan` missing for Sse42 which should be straightforward mapping (represented as `>` with appropriate types in LLVM iirc).

**Review by vargaz — APPROVED** [review]

**Comment by EgorBo** [comment]
@filipnavara `Sse42.CompareGreaterThan` is implemented, see here https://github.com/dotnet/runtime/pull/33591/files#diff-267156e4d16c8b4d95f661179f1a4ce0R912
(re-uses the existing logic)

**Comment by EgorBo** [comment]
> I read it and it LGTM, will do some more testing during the week

I have a sort of "fuzzy" tests where I feed some random input to all the intrinsics and compare the results between mono and coreclr. Will submit it to the repo eventually.

**Review by filipnavara — APPROVED** [review]

**Comment by filipnavara** [comment]
> @filipnavara `Sse42.CompareGreaterThan` is implemented,

Sorry, missed that one :-)

**Pull request merged**
