### PR TITLE
Fix bug for Assertion failed '(op3Reg != targetReg) || (op1Reg == targetReg)' during 'Generate code'

### PR DESCRIPTION
**Pull request by weilinwa**
This is for #62267.

### CODE REVIEW

**Comment by weilinwa** [comment]
@kunalspathak, please take a look at this change. It should fix the assertion failure. Thanks!

**Comment by tannergooding** [comment]
I missed that this had been put up and also put up my own fix: https://github.com/dotnet/runtime/pull/62382

My variant is basically the same but explicitly calls out the need to keep `lsra` and `codegen` in sync here and fixes a case in LSRA where a wrong swap was happening.

**Comment by kunalspathak** [comment]
Thank you @weilinwa for working on this. Since we will be merging https://github.com/dotnet/runtime/pull/62382 , we can close this PR.

**Pull request closed without merging**
