### PR TITLE
[ppc64le] Fixed assertion failure which was occurring while running System.Runtime.Serialization.Formatters tests

### PR DESCRIPTION
**Pull request by alhad-deshpande**
This PR fixes assertion failure mentioned in PR [107678](https://github.com/dotnet/runtime/pull/107678#issuecomment-2343969415).

### CODE REVIEW

**Comment by alhad-deshpande** [comment]
@akoeplinger 
This PR fixes assertion failure mentioned in PR https://github.com/dotnet/runtime/pull/107678#issuecomment-2343969415. Can you please approve/merge this PR?

**Comment by akoeplinger** [comment]
sorry for the late response, I was on vacation and am still catching up on GitHub notifications 😄

**Review by akoeplinger — APPROVED** [review]

**Comment by alhad-deshpande** [comment]
> sorry for the late response, I was on vacation and am still catching up on GitHub notifications 😄

No problem. Thanks for approving!

**Comment by alhad-deshpande** [comment]
@akoeplinger 
The build failed due to new vulnerability warning https://dev.azure.com/dnceng-public/public/_build/results?buildId=835423&view=results.

I have merged latest main and the build should pass now.
Can you please rerun CLI?

**Comment by akoeplinger** [comment]
/ba-g this only changes ppc64le codepaths so the other failures are unrelated

**Pull request merged**
