### PR TITLE
Disable code formatting in code we want to keep as is

### PR DESCRIPTION
**Pull request by akoeplinger**
This applies mostly to specially formatted enums or arrays, we wrap those in #pragma to disable the formatter so it doesn't mess up the code.

### CODE REVIEW

**Comment by jkotas** [comment]
What is special about formatting these arrays and enums?

**Comment by akoeplinger** [comment]
@jkotas they use hand crafted vertical alignment, e.g. the formatter would turn this:

```csharp
internal enum PathConfName : int
{
    PC_LINK_MAX         = 1,
    PC_MAX_CANON        = 2,
    PC_MAX_INPUT        = 3,
    PC_NAME_MAX         = 4,
    PC_PATH_MAX         = 5,
    PC_PIPE_BUF         = 6,
    PC_CHOWN_RESTRICTED = 7,
    PC_NO_TRUNC         = 8,
    PC_VDISABLE         = 9,
}
```

into this:

```csharp
internal enum PathConfName : int
{
    PC_LINK_MAX = 1,
    PC_MAX_CANON = 2,
    PC_MAX_INPUT = 3,
    PC_NAME_MAX = 4,
    PC_PATH_MAX = 5,
    PC_PIPE_BUF = 6,
    PC_CHOWN_RESTRICTED = 7,
    PC_NO_TRUNC = 8,
    PC_VDISABLE = 9,
}
```

**Comment by MichalStrehovsky** [comment]
Is it impossible to have the formatter skip formatting enums/arrays? It is pretty common aligning them this way once they get big enough, like this PR makes visible.

The `#pragma warning disable`/`restore` that we're putting all across the codebase are irritating when it comes to readability because they stand out, but then turn out to be useless from code comprehension perspective. It would be nice if we could limit them as much as possible. We already have too many of them to my taste.

**Comment by akoeplinger** [comment]
Yeah the only option is the #pragma. That said, this adds the suppression to ~120 enums/arrays, a simple regex count of just enums shows we have over 5000 in the repo so I feel like this is an acceptable tradeoff.

**Comment by am11** [comment]
> Yeah the only option is the #pragma

Yes, there is a feature request for spacing configs: https://github.com/dotnet/roslyn/issues/51389.

**Comment by jkotas** [comment]
If we have accepted the formatting damage on thousands of enums and arrays in the repo, why we need to special-case these 100 enums? I would just reformat them.

If/once the formatter is fixed to support more readable formatting, we can reformat all thousands of them.

**Comment by jkotas** [comment]
> there is a feature request for spacing configs: https://github.com/dotnet/roslyn/issues/38241.

Or this feature request needs to be implemented first before we start applying the formatter more broadly in this repo.

**Comment by akoeplinger** [comment]
> If we have accepted the formatting damage on thousands of enums and arrays in the repo, why do we need to special-case these 100 enums? I would just reformat them.

We could definitely reformat the enums if we think losing the vertical alignment is better than the pragma. I don't particularly care either way. The arrays/spans in this PR need to keep the pragma though since they get expanded into unreadable mess otherwise.

> Or this feature request needs to be implemented first before we start applying the formatter more broadly in this repo.

Given the roslyn issue was opened over four years ago I don't expect it anytime soon (unless someone contributes it). Again, I don't think adding the ~200 lines of pragma changes are that bad.

**Comment by jkotas** [comment]
> Again, I don't think adding the ~200 lines of pragma changes are that bad.

It makes the value of applying the formatter to this repo questionable.

**Comment by jkotas** [comment]
> Given the roslyn issue was opened over four years ago I don't expect it anytime soon (unless someone contributes it).

It is common for SDK tools to require additional fixes before they work well for this repo.

**Comment by stephentoub** [comment]
@akoeplinger, should this be closed?

**Comment by akoeplinger** [comment]
Yeah let's close it for now, I'd still like to eventually get this in but will probably need to find some time to contribute fixes to Roslyn first :)

**Pull request closed without merging**
