### PR TITLE
NativeAOT exports marked functions for exe apps.

### PR DESCRIPTION
**Pull request by JamesMenetrey**
Dear all,

This PR fixes the behavior observed in #78663.

To summarize the issue, functions decorated with the attribute UnmanagedCallersOnlyAttribute are not inserted in the export table of the compiled file when the .NET project is an executable (i.e., as opposed to a library) when compiled with NativeAOT.

This change removes the difference between a library and an executable regarding the handling of the attribute UnmanagedCallersOnlyAttribute.

As such, decorated functions with this attribute are now adequately exported for libraries and executables.

### CODE REVIEW

**Comment by JamesMenetrey** [comment]
FYI @agocke, @jkotas, @MichalStrehovsky.

**Comment by jkotas** [comment]
I do not think this behavior should be enabled by default for .exe. And in case we end up enabling by default, there should be a way to disable it.

**Comment by JamesMenetrey** [comment]
> I do not think this behavior should be enabled by default for .exe. And in case we end up enabling by default, there should be a way to disable it.

The usage of the attribute `UnmanagedCallersOnlyAttribute` without setting the property `EntryPoint` does not export the symbol, according to the existing MSDN documentation of that property. Therefore, one can expect to see their functions exported when this property is set, regardless of the type of the project, which is not the case currently.

I think setting the property `EntryPoint` is a convenient way to opt-in for exporting the symbol of the marked functions. Otherwise, this means the usage of that property would have no effect when used in the context of an executable, which may be counter-intuitive for developers.

On the other hand, if you prefer an explicit opt-in in the project file, I can think of adding a new tag for that particular purpose.

WDYT?

**Review by MichalStrehovsky — COMMENTED** [review]
Thank you for the pull request! Jan's argument in https://github.com/dotnet/runtime/issues/78663#issuecomment-1323021865 convinced me that we shouldn't do this by default. How about this? You'll be able to set `<IlcExportUnmanagedEntrypoints>true</IlcExportUnmanagedEntrypoints>` to opt in. (I'm open to suggestions at naming this - we prefix properties that control not-quite-documented behaviors with `Ilc` so that part is motivated by that.)

**Comment by JamesMenetrey** [comment]
Hello @jkotas, and @MichalStrehovsky, thanks for the review! This solution is also fine for me. :)

**Review by jkotas — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
The test failure is an unrelated test that got deadlettered. Infra issue.

**Comment by JamesMenetrey** [comment]
Thanks for the support over this PR!

**Pull request merged**
