### PR TITLE
Delete old AssemblyExtensions.ApplyUpdate/GetApplyUpdateCapabilities

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @mikem8361, @pranavkm, @lambdageek 

@pranavkm, have all of the relevant places been updated to consume the new methods such that we can go ahead and delete the old?  Or should we hold off on this?

### CODE REVIEW

**Comment by lambdageek** [comment]
@stephentoub @pranavkm  Looks like the HotReloadAgent is still calling through the older name:

https://github.com/dotnet/sdk/blob/bbeb47e416c85c5b55c1e708b4c9f4698f531dca/src/BuiltInTools/DotNetDeltaApplier/HotReloadAgent.cs#L196

@pranavkm the new name is `System.Reflection.Metadata.MetadataUpdater.ApplyUpdate()` (and `IsSupported`, `GetCapabilities()`)

**Comment by pranavkm** [comment]
Fun, this is still using the old code: https://github.com/dotnet/sdk/blob/f3e14a8fc77062a46a558a9927e075ad5e447645/src/BuiltInTools/DotNetDeltaApplier/HotReloadAgent.cs. Updating it now.

**Comment by pranavkm** [comment]
Also FYI @vritant24

**Comment by vritant24** [comment]
Thanks for tagging me @pranavkm, We are also using the old code.
@stephentoub @mikem8361 @lambdageek do you happen to know which .NET version `System.Reflection.Metadata.MetadataUpdater.ApplyUpdate` ships with? Looks like the released .NET SDK preview 6 does not have it and gives me the following exception
```
The type or namespace name 'MetadataUpdater' does not exist in the namespace 'System.Reflection.Metadata'
 (are you missing an assembly reference?)
```

**Comment by mikem8361** [comment]
Preview 7

**Comment by vritant24** [comment]
> Preview 7

Ah in that case we won't be able to consume it until .NET 6 Preview 7 is public since our repo infra isn't ready to use non-public .NET SDK previews.

**Comment by stephentoub** [comment]
@pranavkm, can this be merged at this point? Anything still need this in nightlies or RC1?

**Comment by pranavkm** [comment]
Let’s get this in. At worst, it will tell us if we missed updating something.

**Review by mikem8361 — APPROVED** [review]

**Pull request merged**
