### PR TITLE
[mono] Fix second pass of MarshallingPInvokeScanner with metadata-free DLLs

### PR DESCRIPTION
**Pull request by jandupej**
This fixes the second pass of https://github.com/dotnet/runtime/issues/89429 when trying to read DLLs that have no metadata. The first pass was addressed in https://github.com/dotnet/runtime/pull/89430.

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Review by kotlarmilos — APPROVED** [review]
LGTM!

**Comment by kotlarmilos** [comment]
The failure looks related.

**Comment by kotlarmilos** [comment]
The failures shouldn't be related. Thanks!

**Pull request merged**
