### PR TITLE
Re-enable BitmapTests

### PR DESCRIPTION
**Pull request by BruceForstall**
Issue: https://github.com/dotnet/runtime/pull/36910

See if this fails again in the CI

### CODE REVIEW

**Comment by BruceForstall** [comment]
@safern You disabled this in a previous change. I propose to re-enable the tests to see if the problem still occurs.

What would be a way to pre-test this? Do I need to trigger something to get the checked runtime + libraries testing?

**Comment by safern** [comment]
If you add a change to any file under src/coreclr, even a dummy comment or whatever that will run the tests against a checked coreclr.

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/37082

**Comment by BruceForstall** [comment]
Looks like the assert came back on System.Drawing.Common.Tests


```
Assert failure(PID 27 [0x0000001b], Thread: 46 [0x002e]): object->HasEmptySyncBlockInfo()
    File: /__w/1/s/src/coreclr/src/vm/jithelpers.cpp Line: 2284
    Image: /root/helix/work/correlation/dotnet
```

https://helix.dot.net/api/2019-06-17/jobs/44dfbc95-e4bf-4708-9d3b-1bb406bc2b19/workitems/System.Drawing.Common.Tests/console

**Comment by safern** [comment]
@BruceForstall I guess we can close this one until the fix is submitted?

**Comment by BruceForstall** [comment]
@safern Yeah, I'll close it.

**Pull request closed without merging**
