### PR TITLE
Enable QJFL and OSR by default for x64

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Change these default values when the jit targets x64:

* COMPlus_TC_QuickJitForLoops=1
* COMPlus_TC_OnStackReplacement=1

The upshot is that on x64 more methods will be jitted at Tier0, and
we will rely on OSR to get out of long-running Tier0 methods.

Other architectures continue to use the old behavior for now, as
OSR is not yet supported outside of x64.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib 

Will be running various stress legs to try and spot areas where we still need work.

**Comment by AndyAyersMS** [comment]
The pgo legs have expected failures, so will have to interpret results manually.

Had planned to run jitstress too but that seems to be in bad shape right now.

**Comment by AndyAyersMS** [comment]
Runtime PGO failures are all "expected". 

But libraries PGO has some failures that will need investigating. A number of parallel tests fail across all the pgo modes.
```
;; windows x64 no pgo

System.Threading.Tasks.Tests.ParallelForTests.RunSimpleParallelForIncrementTest(increms: 1024)
Assert.Equal() Failure
Expected: 1024
Actual:   1032
```

**Comment by AndyAyersMS** [comment]
Simple repro
```c#
using System;
using System.Threading;
using System.Threading.Tasks;

class X
{
    public static void RunSimpleParallelForeachAddTest_Array(int count, out int o_counter, out int o_expectCounter)
    {
        var data = new int[count];
        int expectCounter = 0;
        for (int i = 0; i < data.Length; i++)
        {
            data[i] = i;
            expectCounter = unchecked(expectCounter + i);
        }
        
        int counter = 0;
        
        // run inside of a separate task mgr to isolate impacts to other tests.
        Task t = Task.Run(
            delegate
            {
                Parallel.ForEach(data, (x) => Interlocked.Add(ref counter, x));
            });
        t.Wait();

        o_counter = counter;
        o_expectCounter = expectCounter;
    }

    public static void Main()
    {
        int counter;
        int expectCounter;
        RunSimpleParallelForeachAddTest_Array(100, out counter, out expectCounter);
        Console.WriteLine($"got {counter} expected {expectCounter}");
    }
}
```
This is the same as the libraries test but with smaller data size. Run with a variant of OSR stress to force OSR to happen even at lower iteration counts:
```
complus_OSR_HitLimit=0
complus_TC_OnStackReplacement_InitialCounter=10
```
The results are wrong and vary from run to run
```
got 5001 expected 4950
got 5129 expected 4950
got 5001 expected 4950
got 5049 expected 4950
got 5129 expected 4950
```
Two methods get rejitted with OSR:
```
Compiling    8 X::RunSimpleParallelForeachAddTest_Array, IL size = 93, hash=0xa33b9cbc Tier1-OSR @0x18
Compiling   53 <>c__DisplayClass19_0`1[__Canon][System.__Canon]::<ForWorker>b__1, IL size = 575, hash=0x4b0449a5 Tier1-OSR @0xcf
```
I've looked at the first one in some detail and it seems ok. So likely the issue is in the second one.

**Comment by AndyAyersMS** [comment]
The `ForWorker` method is fairly complex and has OSR step blocks. It looks like the OSR entry state var is not getting zero initialized despite being marked `lvMustInit` -- suspect this setting gets over-ridden later on. So, will explicitly zero this instead.

With that fixed, I'm running into another issue with OSR in the wider set of parallel tests) where the scratch BB is ending up as BBJ_COND.

**Comment by BruceForstall** [comment]
> I'm running into another issue with OSR in the wider set of parallel tests) where the scratch BB is ending up as BBJ_COND.

We recently had a conversation (on GitHub, I believe) where you pointed out that the scratch entry BB could be BBJ_COND for OSR. Are you saying now that doing so creates a bad condition and so the scratch BB should NOT ever be BBJ_COND?

**Comment by AndyAyersMS** [comment]
> out that the scratch entry BB could be `BBJ_COND` for OSR

You mean [this](https://github.com/dotnet/runtime/pull/61712#discussion_r751532602)? I wasn't specific. The other option we support now (for OSR) is `BBJ_ALWAYS`

**Comment by AndyAyersMS** [comment]
There's at least one more issue to fix -- now that OSR + PGO does instrumentation + optimization (see #61453), we may end up putting an instrumentation probe into the detached `BBJ_RETURN` block after a tail call. This leads to an assert in morph as we don't expect to see real IR there. The fix is to "move this probe" up to the previous block.

**Comment by AndyAyersMS** [comment]
Repro for the case noted above. `T` triggers OSR and the OSR method is instrumented, we put an edge probe in the return block and trigger the assert. Loop in `F` is there just to keep it from getting inlined w/o marking it noinline (so it ends up being tail called).
```C#
;; with this PR
using System;
using System.Runtime.CompilerServices;

class X
{
    static int s;
    static int N;

    public static void F(int[] a)
    {
        for (int j = 0; j < N; j++)
        {
            for (int i = 0; i < a.Length; i++)
            {
                s -= a[i];
            }
        }
    }

    public static void T(bool p, int[] a)
    {
        if (p)
        {
            for (int j = 0; j < N; j++)
            {
                for (int i = 0; i < a.Length; i++)
                {
                    s += a[i];
                }
            }
            
            F(a);
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static int Main()
    {
        int[] a = new int[1000];
        N = 100;
        s = 100;
        a[3] = 33;
        a[997] = 67;
        T(true, a);
        return s;
    }
}
```
results in
```
Assert failure(PID 7716 [0x00001e24], Thread: 19196 [0x4afc]): Assertion failed 'retExpr->gtOper == GT_RETURN' in 'X:T(bool,System.Int32[])' during 'Morph - Global' (IL size 54)

    File: C:\repos\runtime0\src\coreclr\jit\morph.cpp Line: 18007
```

**Comment by AndyAyersMS** [comment]
Not clear yet how to fix the case above -- trying to detect and handle this during instrumentation seems iffy. And the return block has multiple predecessors, so "moving" the probe is not quite the right fix.

**Comment by AndyAyersMS** [comment]
Merged to pick up #62263 and fixes for jit stress. Will kick off another round of stress testing.

**Comment by AndyAyersMS** [comment]
Two Pri0 tests failing with known issue https://github.com/dotnet/runtime/issues/62285.

**Comment by AndyAyersMS** [comment]
Time to trigger jit stress. This also has some known failures so I expect it to fail and will have to dig through and see if there's anything novel.

**Comment by AndyAyersMS** [comment]
Jitstress failures are the "Known" issues with create span.

Libraries PGO looks good.

**Comment by AndyAyersMS** [comment]
Going to run GC stress but it has a lot of failures from #62067. So also expect it to fail and will have to sort through the results.

**Comment by AndyAyersMS** [comment]
Merge to pick up latest round of fixes. Net change is now just updating two config switches.

**Comment by AndyAyersMS** [comment]
Runtime failures are #62285.

**Comment by AndyAyersMS** [comment]
Things are looking good from correctness standpoint. 

Still need to look at perf and startup.

**Comment by AndyAyersMS** [comment]
For perf, first looking at benchmark games on windows as run in the perf repo (via BDN).

`BinaryTrees_2` reports as being slower:

|        Method |        Job | Toolchain |      Mean |    Error |   StdDev |    Median |       Min |       Max | Ratio | RatioSD |      Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|-------------- |----------- |---------- |----------:|---------:|---------:|----------:|----------:|----------:|------:|--------:|-----------:|----------:|----------:|----------:|
| BinaryTrees_2 | Job-ZQIGQA | OSR       | **115.85 ms** | 2.382 ms | 2.743 ms | 115.82 ms | 111.67 ms | 120.66 ms |  1.21 |    0.04 | 38000.0000 | 3000.0000 | 1000.0000 |    227 MB |
| BinaryTrees_2 | Job-XHSMLW | Default   |  95.67 ms | 1.867 ms | 2.075 ms |  95.17 ms |  93.04 ms |  99.88 ms |  1.00 |    0.00 | 38000.0000 |  500.0000 |         - |    227 MB |

and `FannkuchRedux_2` reports being faster:

|          Method |        Job | Toolchain |  n | expectedSum |     Mean |   Error |   StdDev |   Median |      Min |      Max | Ratio | RatioSD | Allocated |
|---------------- |----------- |---------------------------------------------------------------------------------- |--- |------------ |---------:|--------:|---------:|---------:|---------:|---------:|------:|--------:|----------:|
| FannkuchRedux_2 | Job-YJLNSF | OSR | 10 |       73196 | **141.9 ms** | 8.88 ms | 10.23 ms | 137.0 ms | 130.0 ms | 155.1 ms |  0.90 |    0.06 |     464 B |
| FannkuchRedux_2 | Job-QSMCVR | Default | 10 |       73196 | 153.0 ms | 1.39 ms |  1.30 ms | 152.7 ms | 151.2 ms | 155.0 ms |  1.00 |    0.00 |     464 B |

and `RegexRedux_5` slows down when intepreted and speeds up when it's compiled:

|       Method |        Job | Toolchain |  options |      Mean |     Error |    StdDev |    Median |       Min |       Max | Ratio | RatioSD |    Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|------------- |----------- |----- |--------- |----------:|----------:|----------:|----------:|----------:|----------:|------:|--------:|---------:|---------:|---------:|----------:|
| RegexRedux_5 | Job-UMNTZP | OSR  |     None | **33.148 ms** | 1.5822 ms | 1.7586 ms | 33.026 ms | 29.890 ms | 36.777 ms |  1.11 |    0.08 |        - |        - |        - |      3 MB |
| RegexRedux_5 | Job-JQLQSH | Default |     None | 29.981 ms | 1.6348 ms | 1.8171 ms | 29.568 ms | 26.665 ms | 34.004 ms |  1.00 |    0.00 |        - |        - |        - |      3 MB |
| RegexRedux_5 | Job-UMNTZP | OSR | Compiled | **6.114 ms** | 0.1207 ms | 0.1008 ms |  6.139 ms |  5.937 ms |  6.253 ms |  0.89 |    0.09 | 138.8889 | 138.8889 | 138.8889 |      3 MB |
| RegexRedux_5 | Job-JQLQSH | Default  | Compiled |  7.503 ms | 0.9650 ms | 1.1113 ms |  6.959 ms |  6.521 ms |  9.839 ms |  1.00 |    0.00 | 210.5263 | 210.5263 | 210.5263 |      3 MB |

Generally speaking, for benchmark perf we'd expect to see very similar numbers. Benchmarking (via BDN) should be measuring Tier1 code, so the fact that we may also generate OSR methods shouldn't matter.

So will drill into these.

**Comment by AndyAyersMS** [comment]
For `BinaryTrees_2` with OSR, we fairly quickly recompile `Bench` with OSR, and then never produce a Tier1 version. Current default will compile `Bench` fully optimized (thanks to QJFL=0). The difference here is evidently the delta between a fully optimized and an OSR compiled `Bench`.

So, two questions:
* why doesn't the OSR case eventually get to Tier1?
* why is the OSR version of `Bench` slower than the fully optimized one?

**Comment by AndyAyersMS** [comment]
For `FannkuchRedux_2` we see the OSR method running faster than the Tier1 method. Here are the iteration times:
```
WorkloadResult   1: 2 op, 294451000.00 ns, 147.2255 ms/op
   ;; OSR version of fannkuch
WorkloadResult   2: 2 op, 268075800.00 ns, 134.0379 ms/op
WorkloadResult   3: 2 op, 270717600.00 ns, 135.3588 ms/op
WorkloadResult   4: 2 op, 275813700.00 ns, 137.9068 ms/op
WorkloadResult   5: 2 op, 267628700.00 ns, 133.8143 ms/op
WorkloadResult   6: 2 op, 268275400.00 ns, 134.1377 ms/op
WorkloadResult   7: 2 op, 268396300.00 ns, 134.1981 ms/op
WorkloadResult   8: 2 op, 267082500.00 ns, 133.5412 ms/op
WorkloadResult   9: 2 op, 273082600.00 ns, 136.5413 ms/op
WorkloadResult  10: 2 op, 267407200.00 ns, 133.7036 ms/op
WorkloadResult  11: 2 op, 267643800.00 ns, 133.8219 ms/op
    ;; Tier1 version of fannkuch 
WorkloadResult  12: 2 op, 302364000.00 ns, 151.1820 ms/op
WorkloadResult  13: 2 op, 300932300.00 ns, 150.4661 ms/op
WorkloadResult  14: 2 op, 303645700.00 ns, 151.8228 ms/op
WorkloadResult  15: 2 op, 299903400.00 ns, 149.9517 ms/op
WorkloadResult  16: 2 op, 299843600.00 ns, 149.9218 ms/op
WorkloadResult  17: 2 op, 298525300.00 ns, 149.2627 ms/op
WorkloadResult  18: 2 op, 321872300.00 ns, 160.9361 ms/op
WorkloadResult  19: 2 op, 316387400.00 ns, 158.1937 ms/op
WorkloadResult  20: 2 op, 313691800.00 ns, 156.8459 ms/op
```
The Tier1 method is loaded in the middle of iteration 11, so gets called for iteration 12. The "slow" iteration times after that point are similar to those seen by the default config (perhaps a tiny bit better).

So naturally, the question is why. All the time here is spent in `fannkuch`.

First, the Tier1 and full opt version are identical. The OSR version just omits the initial `for` loop:

https://github.com/dotnet/performance/blob/529f33c1955ae3360d794d1fc80dfb978bb2f222/src/benchmarks/micro/runtime/BenchmarksGame/fannkuch-redux-2.cs#L32

but contains the rest of the loops. We do less cloning in the OSR version. That seems to lead to somewhat better register allocation, though unclear if that accounts for all of the perf improvement.

Sorting out why things are faster for OSR is going to take some time.

**Comment by AndyAyersMS** [comment]
Running some other segments of the full suite at random:
* `Utf8Formatter` similar results with/without OSR
* `Sort` shows some +/- 20% swings.

At this point it seems clear that there are some tests -- almost certainly the ones that do a lot of looping internally, possibly restricted to the subset where the looping methods aren't called a lot -- where the BDN results will reflect the performance of the OSR versions. And the OSR version can be faster or slower in ways that will be hard to predict.

By and large all these should be cases where the benchmark strategy isn't sufficient to get us to Tier1 reliably. In the past for this subset it did not matter, as QJFL=0 ensured these methods were exempt from tiering.

I'm going to try and do larger sweeps and get a ballpark estimate as to how many tests are likely impacted in this way.

**Comment by EgorBo** [comment]
I hope dotnet/performance infrastructure will be in a good state when this is merged to catch all improvements/regressions

**Comment by AndyAyersMS** [comment]
> I hope dotnet/performance infrastructure will be in a good state when this is merged

I won't merge unless things are in a good state.

**Pull request closed without merging**
