### PR TITLE
Fixing update issue with multivalued properties #34267

### PR DESCRIPTION
**Pull request by FWest98**
Fixes Issue #34267

# Description
This PR fixes the issue linked. Updating a multivalued property would only add new values, but not remove old values. Only in the case 0 or 1 items were remaining, a different code path did remove all other values.

This has been solved in this PR by recreating the entire array of properties. My proposed solution in the issue (clearing the list and re-adding all values) did not work properly, as it would cause an error when creating a new principal. My best guess for a cause is that such a solution would only send Clear and Append operations to `IADs::PutEx`, while for a newly-created object it requires/expects an Update operation. To circumvent this, I construct the new list of values locally, and then set the array all at once. This invokes a different codepath in `PropertyValueCollection` which does send an Update.

# Customer Impact
The current issue causes unexpected behaviour that is hard to catch, as it only occurs when removing values but keeping at least 2 values remaining.

# Regression
As far as I can see, this issue has been present for years.

# Testing
Added a unit test demonstrating the issue first, before attempting to solve it. The unit test now passes.

# Risk
There might be some risk involved, as this technically changes behaviour. However, I don't believe the old behaviour was documented to be correct anywhere, and it was inconsistent (dependent on the number of items in the list).

### CODE REVIEW

**Comment by joperezr** [comment]
cc: @tquerec @grubioe do you mind taking a look since this is in S.DS.AM?

**Comment by jeffhandley** [comment]
> cc: @tquerec @grubioe do you mind taking a look since this is in S.DS.AM?

I've marked this as blocked until we get a review from @tquerec and/or @grubioe.

**Comment by BRDPM** [comment]
I've looked over these but I would like some backup before we approve - I'll set up some time with @jay98014 to go over these next week.

**Review by intothedarkness — APPROVED** [review]
looks good.

**Comment by kumarravi** [comment]
Looks good to me. A small suggestion on naming the list to "values". A more descriptive name helps increase code readability for example 'UserPropertyList' or anything more descriptive. Otherwise looks good.

**Comment by ericstj** [comment]
@joperezr it looks like we have review from the Windows-DirectoryServices owners.  Can you give this one last look and make sure we don't need fresh CI or anything then merge, please?

**Review by joperezr — APPROVED** [review]
Changes look good to me. Will merge when CI is green.

**Pull request merged**
