### PR TITLE
Fix thread pool hang

### LINKED ISSUE #55642: [QUIC] Intermittent hangs in CI
### Sporadic hangs of `System.Net.Quic.Functional.Tests`.

Since yesterday we're seeing that sometime the work item fails with "timeout" meaning a test hang and subsequent kill by the helix agent. 
The potential culprit that might have caused this is #55505. Firstly, because the time when it started occurring correlates with the time of its merge. Secondly,  the changes come from #52929 and there's been multiple test hangs historically.

#### Unique tests picked from the console logs:
```
[Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_Success', Elapsed: 00:14:04
[Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.ReadWrite_Random_Success', Elapsed: 00:14:00
[Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.LargeDataSentAndReceived', Elapsed: 00:14:04
[Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_MessagesSmallerThanReadBuffer_Success', Elapsed: 00:14:05
[Long Running Test] 'System.Net.Quic.Tests.MsQuicTests.ByteMixingOrNativeAVE_MinimalFailingTest', Elapsed: 00:14:33
```

#### Kusto queries to get the data

Failing work items (9 records):
```SQL
WorkItems
| where FriendlyName == "System.Net.Quic.Functional.Tests" and Status != "Pass" and ExitCode == -3
| join kind=inner Jobs on JobId
| where DockerTag == "mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408"
| order by Queued desc
```

Success for comparison (465 total, 135 since the first failure):
```SQL
WorkItems
| where FriendlyName == "System.Net.Quic.Functional.Tests" and Status == "Pass"
| join kind=inner Jobs on JobId
| where DockerTag == "mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408"
| order by Queued desc
```

cc: @CarnaViire @karelz 

|Build|Kind|Start Time|
|---|---|---|
[1236570](https://dev.azure.com/dnceng/public/_build/results?buildId=1236570)|[PR 55594](https://github.com/dotnet/runtime/pull/55594)|2021-14-07|

### PR DESCRIPTION
**Pull request by kouvel**
- In https://github.com/dotnet/runtime/pull/53471 the thread count goal was moved out of `ThreadCounts`, it turns out that there are a few subtle races that it was avoiding. There are other ways to fix it, but I've added the goal back into `ThreadCounts` for now.
- Reverted PR https://github.com/dotnet/runtime/pull/55985, which worked around the issue in the CI

Fixes https://github.com/dotnet/runtime/issues/55642

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks for tracking this down!

There was some suspicion this may also have been contributing to some of the CI hangs we've seen recently.  It'll be interesting to see if their rate decreases after this goes in.

**Comment by danmoseley** [comment]
Is there anything that could be done to create a test that would catch this kind of failure? Or do we already have that in the Quic tests 😄

**Comment by wfurt** [comment]
Seems like tricky business @danmoseley. It was found by standard conformance Stream tests (with synchronous IO).
On 2Core machine and sync-over-async inside MsQuic wrapper.

**Review by wfurt — APPROVED** [review]
The QUIC part looks good to me. I'll give it try tomorrow.

**Comment by danmoseley** [comment]
True, but I have seen @kouvel devise unit tests that consistently repro the most sporadic issues, so I thought I'd ask 😄

**Comment by davidfowl** [comment]
I wonder if coyote could come in handy here https://microsoft.github.io/coyote/

**Review by mangod9 — APPROVED** [review]

**Comment by kouvel** [comment]
I had some difficulty in reproing it initially when I tried but upon trying a few more things I got a fairly frequent repro now on my Windows machine, added a test.

**Pull request merged**
