### PR TITLE
[wasm] Explicitly include mscorlib.dll, to support scanning assemblies

### LINKED ISSUE #69861: [wasm] perf pipeline builds failing to build the wasm app
```
The "ManagedToNativeGenerator" task failed unexpectedly. [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
System.IO.FileNotFoundException: Could not find assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly. [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveAssembly(AssemblyReferenceHandle handle, EcmaModule module) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at System.Reflection.TypeLoading.Ecma.EcmaResolver.ComputeTypeRefResolution(TypeReferenceHandle handle, EcmaModule module) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveTypeRef(TypeReferenceHandle handle, EcmaModule module) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at System.Reflection.TypeLoading.Ecma.EcmaModule.GetTypeFromReference(MetadataReader reader, TypeReferenceHandle handle, Byte rawTypeKind) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeTypeHandle(BlobReader& blobReader, Byte rawTypeKind, Boolean allowTypeSpecifications) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeMethodSignature(BlobReader& blobReader) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at System.Reflection.TypeLoading.Ecma.EcmaMethodDecoder.SpecializeMethodSig(IRoMethodBase roMethodBase) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at System.Reflection.TypeLoading.RoDefinitionMethod`1.ComputeMethodSig() [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at System.Reflection.TypeLoading.RoMethod.get_ReturnType() [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at SignatureMapper.MethodToSignature(MethodInfo method) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at IcallTableGenerator.<ProcessType>g__AddSignature|15_1(Type type, MethodInfo method) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at IcallTableGenerator.ProcessType(Type type) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at IcallTableGenerator.GenIcallTable(String runtimeIcallTableFile, String[] assemblies, String outputPath) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at ManagedToNativeGenerator.ExecuteInternal() [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at ManagedToNativeGenerator.Execute() [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/home/helixbot/work/B65009B0/w/B3450A04/e/performance/artifacts/bin/for-running/MicroBenchmarks/238a40fc-35cd-4e79-b1a8-42613a404a38/BenchmarkDotNet.Autogenerated.csproj]
```

### PR DESCRIPTION
**Pull request by radical**
.. with mscorlib dependency.

This showed up when scanning `Dia2Lib` for icalls, which is indirectly
used by the microbenchmarks in `dotnet/performance`. It would fail with:

```
System.IO.FileNotFoundException: Could not find assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Either explicitly load this assembly using a method such as LoadFromAssemblyPath() or use a MetadataAssemblyResolver that returns a valid assembly.
   at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveAssembly(AssemblyReferenceHandle handle, EcmaModule module)
   at System.Reflection.TypeLoading.Ecma.EcmaResolver.ComputeTypeRefResolution(TypeReferenceHandle handle, EcmaModule module)
   at System.Reflection.TypeLoading.Ecma.EcmaResolver.ResolveTypeRef(TypeReferenceHandle handle, EcmaModule module)
   at System.Reflection.TypeLoading.Ecma.EcmaModule.GetTypeFromReference(MetadataReader reader, TypeReferenceHandle handle, Byte rawTypeKind)
   at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeTypeHandle(BlobReader& blobReader, Byte rawTypeKind, Boolean allowTypeSpecifications)
   at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode)
   at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode)
   at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeMethodSignature(BlobReader& blobReader)
   at System.Reflection.TypeLoading.Ecma.EcmaMethodDecoder.SpecializeMethodSig(IRoMethodBase roMethodBase)
   at System.Reflection.TypeLoading.RoDefinitionMethod`1.ComputeMethodSig()
   at System.Reflection.TypeLoading.RoMethod.get_ReturnType()
   at SignatureMapper.MethodToSignature(MethodInfo method)
   at IcallTableGenerator.<ProcessType>g__AddSignature|15_1(Type type, MethodInfo method)
   at IcallTableGenerator.ProcessType(Type type)
   at IcallTableGenerator.GenIcallTable(String runtimeIcallTableFile, String[] assemblies, String outputPath)
   at ManagedToNativeGenerator.ExecuteInternal()
   at ManagedToNativeGenerator.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

This is thrown when `SignatureMapper.MethodToSignature` called
`method.ReturnType` for:

```
  .method public hidebysig newslot virtual
  instance void  loadAndValidateDataFromPdb([in] string  marshal( lpwstr) pdbPath,
                                            [in] [mscorlib]System.Guid& pcsig70,
                                            [in] uint32 sig,
                                            [in] uint32 age) runtime managed internalcall
  {
    .override Dia2Lib.IDiaDataSource::loadAndValidateDataFromPdb
  } // end of method DiaSourceClass::loadAndValidateDataFromPdb
```

We use `PathAssemblyResolver` with a closed set of assemblies, which
didn't include mscorlib.dll . So, we include that explicitly from the
runtime pack.

Fixes https://github.com/dotnet/runtime/issues/69861

### CODE REVIEW

**Comment by radical** [comment]
TODO: test case

**Comment by radical** [comment]
This has a successful run in the `dotnet-runtime-perf` pipeline - `20220526.9`.

**Comment by maraf** [comment]
The `Dia2Lib` is netstandard library and that's the reason why looks for `void` type in mscorlib, correct?

**Comment by radical** [comment]
Yep, exactly.

**Review by maraf — APPROVED** [review]
Looks good from my point of view

**Comment by radical** [comment]
See `20220527.6` for a successful run with the updated PR.

**Comment by radical** [comment]
The library test failure is https://github.com/dotnet/runtime/issues/69934 , reproducible on `main` too.
The WBT failures are https://github.com/dotnet/runtime/issues/69934 .
And the AOT ones didn't actually fail.

Merging this to unblock the perf pipeline.

**Pull request merged**
