### PR TITLE
Improve ThreadPool ExecutionContext fast-paths

### PR DESCRIPTION
**Pull request by benaadams**
https://github.com/dotnet/runtime/pull/41214 + EH WriteThrough

Reduce TLS access for Thread.CurrentThread

Also direct calls rather than non-inline call throughs followed by indirect callbacks

### CODE REVIEW

**Review by gfoidl — COMMENTED** [review]
Just some nits about `!= null` <-> `is not null`.

**Comment by stephentoub** [comment]
Perf results?

**Comment by benaadams** [comment]
```
Summary of Code Size diffs:
(Lower is better)

Total bytes of diff: -3705 (-0.11% of base)
    diff is an improvement.

Total byte diff includes -8093 bytes from reconciling methods
        Base had   17 unique methods,    12978 unique bytes
        Diff had   20 unique methods,     4885 unique bytes

Top file improvements (bytes):
       -3705 : System.Private.CoreLib.dasm (-0.11% of base)

1 total files with Code Size differences (1 improved, 0 regressed), 0 unchanged.

Top method regressions (bytes):
        2223 (434.18% of base) : System.Private.CoreLib.dasm - AsyncStateMachineBox`1:ExecuteFromThreadPool(Thread):this (32 methods)
        1903 (330.38% of base) : System.Private.CoreLib.dasm - AsyncStateMachineBox`1:MoveNext():this (32 methods)
        1189 (     ∞ of base) : System.Private.CoreLib.dasm - StateMachineBox`1:System.Threading.IThreadPoolWorkItemWithThread.Execute(Thread):this (0 base, 16 diff methods)
         711 (     ∞ of base) : System.Private.CoreLib.dasm - AsyncTaskMethodBuilder:Execute(Task,ExecutionContext,ContextCallback) (0 base, 1 diff methods)
         426 (     ∞ of base) : System.Private.CoreLib.dasm - AsyncTaskMethodBuilder:ExecuteFromThreadPool(Thread,Task,ExecutionContext,ContextCallback) (0 base, 1 diff methods)
         409 (     ∞ of base) : System.Private.CoreLib.dasm - TimerQueueTimer:CallCallback():this (0 base, 1 diff methods)
         375 (     ∞ of base) : System.Private.CoreLib.dasm - AwaitTaskContinuation:System.Threading.IThreadPoolWorkItemWithThread.Execute(Thread):this (0 base, 1 diff methods)
         352 ( 5.60% of base) : System.Private.CoreLib.dasm - AsyncMethodBuilderCore:Start(byref) (29 methods)
         337 (     ∞ of base) : System.Private.CoreLib.dasm - TimerQueueTimer:Fire(Thread):this (0 base, 1 diff methods)
         300 (     ∞ of base) : System.Private.CoreLib.dasm - AsyncValueTaskMethodBuilder:Execute(Object,ExecutionContext,ContextCallback) (0 base, 1 diff methods)
         216 (     ∞ of base) : System.Private.CoreLib.dasm - TimerQueueTimer:CallCallbackOnThreadPool(Thread):this (0 base, 1 diff methods)
         209 (     ∞ of base) : System.Private.CoreLib.dasm - ExecutionContext:RunOnDefaultContext(Thread,ExecutionContext,ContextCallback,Object) (0 base, 1 diff methods)
         176 (24.31% of base) : System.Private.CoreLib.dasm - ThreadPoolWorkQueue:Dispatch():bool
         168 (     ∞ of base) : System.Private.CoreLib.dasm - QueueUserWorkItemCallback`1:Execute(Thread):this (0 base, 2 diff methods)
         112 (     ∞ of base) : System.Private.CoreLib.dasm - ExecutionContext:RestoreDefaultContextThrowIfNeeded(Thread,SynchronizationContext,ExceptionDispatchInfo) (0 base, 1 diff methods)
         102 (     ∞ of base) : System.Private.CoreLib.dasm - Task:ExecuteEntryUnsafe():this (0 base, 1 diff methods)
          92 (575.00% of base) : System.Private.CoreLib.dasm - Task:ExecuteFromThreadPool(Thread):this
          73 (     ∞ of base) : System.Private.CoreLib.dasm - QueueUserWorkItemCallback:Execute(Thread):this (0 base, 1 diff methods)
          72 (     ∞ of base) : System.Private.CoreLib.dasm - QueueUserWorkItemCallbackDefaultContext`1:System.Threading.IThreadPoolWorkItem.Execute():this (0 base, 2 diff methods)
          46 (     ∞ of base) : System.Private.CoreLib.dasm - ExecutionContext:RestoreNonDefaultContextToThreadPool(Thread,ExecutionContext) (0 base, 1 diff methods)

Top method improvements (bytes):
      -10959 (-100.00% of base) : System.Private.CoreLib.dasm - AsyncStateMachineBox`1:MoveNext(Thread):this (32 base, 0 diff methods)
        -389 (-34.98% of base) : System.Private.CoreLib.dasm - StateMachineBox`1:MoveNext():this (16 methods)
        -370 (-100.00% of base) : System.Private.CoreLib.dasm - AwaitTaskContinuation:System.Threading.IThreadPoolWorkItem.Execute():this (1 base, 0 diff methods)
        -321 (-100.00% of base) : System.Private.CoreLib.dasm - TimerQueueTimer:Fire(bool):this (1 base, 0 diff methods)
        -278 (-100.00% of base) : System.Private.CoreLib.dasm - TimerQueueTimer:CallCallback(bool):this (1 base, 0 diff methods)
        -256 (-100.00% of base) : System.Private.CoreLib.dasm - StateMachineBox`1:System.Threading.IThreadPoolWorkItem.Execute():this (16 base, 0 diff methods)
        -196 (-100.00% of base) : System.Private.CoreLib.dasm - ExecutionContext:RunForThreadPoolUnsafe(ExecutionContext,Action`1,byref) (2 base, 0 diff methods)
        -122 (-100.00% of base) : System.Private.CoreLib.dasm - QueueUserWorkItemCallback`1:Execute():this (2 base, 0 diff methods)
        -108 (-100.00% of base) : System.Private.CoreLib.dasm - Task:ExecuteEntryUnsafe(Thread):this (1 base, 0 diff methods)
         -72 (-100.00% of base) : System.Private.CoreLib.dasm - QueueUserWorkItemCallbackDefaultContext`1:Execute():this (2 base, 0 diff methods)
         -70 (-100.00% of base) : System.Private.CoreLib.dasm - QueueUserWorkItemCallback:Execute():this (1 base, 0 diff methods)
         -65 (-100.00% of base) : System.Private.CoreLib.dasm - QueueUserWorkItemCallback:.cctor() (1 base, 0 diff methods)
         -51 (-43.97% of base) : System.Private.CoreLib.dasm - AwaitTaskContinuation:.cctor()
         -43 (-1.46% of base) : System.Private.CoreLib.dasm - <>c:.cctor() (66 base, 65 diff methods)
         -35 (-100.00% of base) : System.Private.CoreLib.dasm - <>c:<.cctor>b__23_0(Object):this (1 base, 0 diff methods)
         -31 (-100.00% of base) : System.Private.CoreLib.dasm - <>c:<.cctor>b__6_0(QueueUserWorkItemCallback):this (1 base, 0 diff methods)
         -31 (-100.00% of base) : System.Private.CoreLib.dasm - QueueUserWorkItemCallbackDefaultContext:Execute():this (1 base, 0 diff methods)
         -26 (-100.00% of base) : System.Private.CoreLib.dasm - <>c:<.cctor>b__17_0(Object):this (1 base, 0 diff methods)
         -21 (-100.00% of base) : System.Private.CoreLib.dasm - TimerQueueTimer:System.Threading.IThreadPoolWorkItem.Execute():this (1 base, 0 diff methods)
         -17 (-100.00% of base) : System.Private.CoreLib.dasm - <>c:<.cctor>b__17_1(Action):this (1 base, 0 diff methods)

82 total methods with Code Size differences (23 improved, 59 regressed), 21039 unchanged.
```

Still working on it

**Comment by ViktorHofer** [comment]
// Auto-generated message

https://github.com/dotnet/runtime/commit/69e114c1abf91241a0eeecf1ecceab4711b8aa62 which was merged 12/7 removed the intermediate src/coreclr/**src**/ folder. This PR needs to be updated as it touches files in that directory which causes conflicts.

To update your commits you can use this bash script: https://gist.github.com/ViktorHofer/6d24f62abdcddb518b4966ead5ef3783. Feel free to use the comment section of the gist to improve the script for others.

**Pull request closed without merging**
