### PR TITLE
Fix PriorityQueue not deleting references to dequeued elements

### LINKED ISSUE #50114: `PriorityQueue` keeps node in memory when dequeued
When the queue contains only one node, calling `Dequeue()` will keep a reference to that node.

```
class C {}

var pq = new PriorityQueue<C, int>();
pq.Enqueue(new C(), 0);
pq.Dequeue();

/*
At this point, pq._nodes[0] will still reference the enqueued object.
*/
```

The reference is cleared [here](https://github.com/dotnet/runtime/blob/f000c7db837f3455d107a3bf1503b523675292e7/src/libraries/System.Collections/src/System/Collections/Generic/PriorityQueue.cs#L564) but then put back by `MoveDown*()`

ver: .net6 preview 2

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Fix #50114.

The private `RemoveRootNode()` method does not handle heaps of size 1 correctly, reinserting the dequeued element back into the buffer. While not impacting functional correctness, it can result in references not being removed from the queue.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
At some point it'd be worth adding to all of our collections (via the shared collections test suite) validation that clearing / removing elements from a collection does enable them to be collected.

**Comment by danmoseley** [comment]
> Do we have a good way of doing this without resorting to reflection?

I believe we have some precedent for using RemoteInvoke to start a child process, performing the operations, then using GC.Collect and GC.GetTotalMemory etc to verify that it goes down to a reasonable level. Since that needs to have a fuzz factor this case where it's just the last element, it would probably have to involve a lot of PriorityQueue's rather than a single one that you grow huge and then shrink.

**Comment by stephentoub** [comment]
Doesn't require that :-)  Just something like (GitHub compiled):
```C#
[Fact]
public void Collection_Clear_RemovesReferences()
{
    var list = new List<object>();
    WeakReference<object> wr = Populate(list);
    Assert.True(SpinWait.SpinUntil(() =>
    {
        GC.Collect();
        return wr.TryGetTarget(out _);
    }, 30_000);

    [MethodImpl(MethodImplOptions.NoInlining)]
    static WeakReference<object> Populate(List<object> list)
    {
        var o = new object();
        list.Add(o);
        list.Clear(); // or whatever operation you want to test
        return new WeakReference<object>(o);
    }
}
```

**Comment by danmoseley** [comment]
Oh - yes that's a big improvement. And much more scalable, there's plenty of API that could use this test eg TrimExcess, etc.

**Comment by VSadov** [comment]
Precise GC is observable via weak references (including dependent handles) and finalizers. 
What @stephentoub suggests will work. 

It may not work with conservative GC on Mono, but as a matter of testing the data structure, it would be sufficient to enable the test only when precise GC is used.
CLR GC is always precise. There is a conservative mode (i.e. `COMPlus_gcConservative`), but that is not considered a production scenario.

**Comment by stephentoub** [comment]
> it would be sufficient to enable the test only when precise GC is used.

Right.  It's what we do in other places like this, e.g. 
https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.cs#L250-L261
https://github.com/dotnet/runtime/blob/60037aae8296959a152bfb99b220139ea9807c83/src/libraries/System.Net.Sockets/tests/FunctionalTests/DisposedSocketTests.cs#L750-L763
etc.

**Comment by eiriktsarpalis** [comment]
FWIW I find it unlikely that this technique would have caught this particular bug (unless we specifically tested for that scenario). One alternative I was thinking about is adding code in debug builds that validates the integrity of the data structure after each operation is completed (in this case it could check that every unpopulated element in the internal buffer is null).

**Comment by stephentoub** [comment]
It would have if we had tests like these in place:
https://github.com/dotnet/runtime/pull/50258
and if PriorityQueue had test classes that inherited all of these tests like the rest of the collections do... unfortunately, it doesn't.  We should rectify that :)

**Pull request merged**
