### PR TITLE
Remove phi nodes during rationalize.

### PR DESCRIPTION
**Pull request by sandreenko**
Get rid of PHI/PHI_ARG nodes during rationalize phase, these nodes are not used after optimization phases.

This change allows us to 
1. save some compilation time (trying to measure now, problems with PIN tool)
2. simplify the code;
3. solve my issue with LONG phi store on x86/arm that are not decomposed;

I did not expect any diffs but I have one on x86 windows libraries tests (out of all spmi collections that we have)
```
Top method improvements (bytes):
         -21 (-2.31% of base) : 282396.dasm - System.DirectoryServices.Tests.DirectoryServicesTests:TestInvalidUserAndPassword():this
```

it looks like LSRA noise but I am analyzing it now.

### CODE REVIEW

**Comment by sandreenko** [comment]
PTAL @AndyAyersMS @BruceForstall @dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]

**Review by AndyAyersMS — APPROVED** [review]
LGTM too. Thanks for doing this Sergey.

**Comment by sandreenko** [comment]
pin shows 0.1-0.2% jit compilation time improvement (x64 spmi replay on release without pgo), sounds like what I expected.

**Comment by sandreenko** [comment]
finally found the reason for the diff, when we create `RefTypeZeroInit` we use the name of the first node in the list, before the change it was `PHI_ARG` now it is `IL_OFFSET`, it happens here:
https://github.com/dotnet/runtime/blob/bc0fda4e9bff863551be27e52cb84ea3bc0573cb/src/coreclr/jit/lsrabuild.cpp#L1891

then, when we assign weights we check `if (isCandidateLocalRef(treeNode))` and in the base line it was true, now it is false:
https://github.com/dotnet/runtime/blob/bc0fda4e9bff863551be27e52cb84ea3bc0573cb/src/coreclr/jit/lsra.cpp#L189

so not a "real" diff, just not the best mechanism for these zero-inits.

**Pull request merged**
