### PR TITLE
Augment generated regex XML comment with original pattern and options

### LINKED ISSUE #88121: Please add the pattern to the summary of GeneratedRegex partial method
### Description

Currently only lengthy explanation is available. I would like to see the original pattern on mouse hover, it is much clearer for me, especially for patterns that contain several capture groups, `(?<...>)` is very easy to spot compared to bullet points.

image

### Reproduction Steps

```C#
[GeneratedRegex(@"Origin (?<version>(?<num>\d+[a-z]?|\d+\.\d+(?:.\d)?)(?<sr> SR\d)?) (?<type>.*)")]
private static partial Regex GetOriginVersionPattern();
```

### Expected behavior

The pattern used to generate the partial method should be included in the xml document summary.

### Actual behavior

Only verbose explanations are given.

### Regression?

_No response_

### Known Workarounds

Not use the GeneratedRegex feature.

### Configuration

VS 17.6.4
project targets .NET 7
.NET SDK 7.0.304

### Other information

_No response_

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/88121

Before:
image

After:
image

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]

**Comment by danmoseley** [comment]
Is the comment in the second image quite correct? It says to match '2' and then begins an alternation, then match 5. I'd expect both in the alternation.

**Comment by danmoseley** [comment]
Oh I see it's extracted the common prefix

**Comment by danmoseley** [comment]
These could use the same language, though?

* Match a character in the set [0-4]. 
* Match '0' through '9'.

**Comment by stephentoub** [comment]
> These could use the same language, though?

They _could_... it's recognizing 0-9 as being the same as ECMAScript \d, which is hardcoded to be "'0' through '9'"

**Comment by danmoseley** [comment]
I think it would be a little easier to read in fairly everyday cases like this one.

**Comment by danmoseley** [comment]
Also just curious why does it call out greedily in (just) some cases, given that's the default?

**Comment by stephentoub** [comment]
> Also just curious why does it call out greedily in (just) some cases, given that's the default?

It calls out for all loops whether they're greedy or lazy.

**Pull request merged**
