### PR TITLE
[release/6.0] Bump arcade to 6.0.0-beta.22418.3

### PR DESCRIPTION
**Pull request by hoyosjs**

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Review by joeloff — APPROVED** [review]

**Review by jeffschwMSFT — APPROVED** [review]
approved.  Is this blocking our build?

cc @carlossanlop

**Comment by hoyosjs** [comment]
Yes, this is needed for the insertion

**Comment by lewing** [comment]
```
  Discovering: System.Net.NameResolution.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.NameResolution.Functional.Tests (found 58 of 64 test cases)
  Starting:    System.Net.NameResolution.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.NameResolution.Tests.GetHostAddressesTest_Cancellation.DnsGetHostAddresses_PostCancelledToken_Throws [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.OperationCanceledException)
      Actual:   typeof(System.Net.Sockets.SocketException): No such host is known.
      ---- System.Net.Sockets.SocketException : No such host is known.
      Stack Trace:
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(406,0): at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(387,0): at System.Net.Dns.GetHostAddressesCore(String hostName, AddressFamily addressFamily, ValueStopwatch stopwatch)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(586,0): at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, ValueStopwatch stopwatch)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(696,0): at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs(98,0): at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2376,0): at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(293,0): at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(293,0): at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2369,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(406,0): at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(387,0): at System.Net.Dns.GetHostAddressesCore(String hostName, AddressFamily addressFamily, ValueStopwatch stopwatch)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(586,0): at System.Net.Dns.<>c.<GetHostEntryOrAddressesCoreAsync>b__33_0(Object s, ValueStopwatch stopwatch)
        /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs(696,0): at System.Net.Dns.<>c__DisplayClass39_0`1.<RunAsync>b__0(Task <p0>, Object <p1>)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs(98,0): at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2376,0): at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(293,0): at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(293,0): at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2369,0): at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        --- End of stack trace from previous location ---
  Finished:    System.Net.NameResolution.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.NameResolution.Functional.Tests  Total: 75, Errors: 0, Failed: 1, Skipped: 0, Time: 15.244s
```

**Comment by am11** [comment]
> DnsGetHostAddresses_PostCancelledToken_Throws

That is just a flaky test, we can backport https://github.com/dotnet/runtime/pull/70044 if needed.

**Pull request merged**
