### PR TITLE
Fix GC hole in Guid

### PR DESCRIPTION
**Pull request by MichalPetryka**
Found in #99130.

### CODE REVIEW

**Comment by jkotas** [comment]
Introduced by #87993

**Review by stephentoub — APPROVED** [review]
Thanks.

**Comment by MichalPetryka** [comment]
This needs a backport to .NET 8 FYI.

**Comment by MichalPetryka** [comment]
@MihuBot

**Comment by MichalPetryka** [comment]
@stephentoub Can this be merged now?

**Pull request merged**
