### PR TITLE
Fix issues found in recent Int128 ABI change

### LINKED ISSUE #74318: Test failure Interop/PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.sh
Run: [runtime-coreclr outerloop 20220821.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1957439&view=ms.vss-test-web.build-test-results-tab&runId=50310616&resultId=100409&paneView=debug)

Failed test:
```
R2R-CG2 Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- Interop/PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.sh

R2R-CG2 Linux x64 Checked no_tiered_compilation @ Ubuntu.1804.Amd64.Open
- Interop/PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.sh

R2R-CG2 Linux x64 Checked @ Ubuntu.1804.Amd64.Open
- Interop/PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.sh

coreclr windows x64 Checked @ Windows.10.Amd64.Open
- Interop\\PInvoke\\Int128\\Int128TestFieldLayout\\Int128TestFieldLayout.cmd

R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open
- Interop\\PInvoke\\Int128\\Int128TestFieldLayout\\Int128TestFieldLayout.cmd

R2R-CG2 Linux x64 Checked @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- Interop/PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.sh

R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- Interop\\PInvoke\\Int128\\Int128TestFieldLayout\\Int128TestFieldLayout.cmd

R2R-CG2 OSX x64 Checked @ OSX.1200.Amd64.Open
- Interop/PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.sh
```
**Error message:**
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
at Int128Native.GetInt128Out(UInt64, UInt64, System.Int128*)

/root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.sh: line 251: -r:/root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/IL-CG2/*.dll: No such file or directory

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/Interop.PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/IL-CG2/Int128TestFieldLayout.dll
20:47:00
Response file: /root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.dll.rsp
/root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/IL-CG2/Int128TestFieldLayout.dll
-o:/root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.dll
20:47:02
/root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/IL-CG2/TestLibrary.dll
20:47:02
Response file: /root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/TestLibrary.dll.rsp
/root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/IL-CG2/TestLibrary.dll
-o:/root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/TestLibrary.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/TestLibrary.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/TestLibrary.dll
20:47:04
in ReleaseLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Int128TestFieldLayout.dll ''
Testing Int128
Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.Runtime.InteropServices.MarshalDirectiveException)
Actual:   (No exception was thrown)
at Xunit.Assert.Throws(Type exceptionType, Exception exception) in /_/src/xunit.assert/Asserts/ExceptionAsserts.cs:line 226
at Int128Native.TestInt128FieldLayout() in /__w/1/s/src/tests/Interop/PInvoke/Int128/Int128Test.cs:line 133
at Int128NativeFieldLayout.Main(String[] args) in /__w/1/s/src/tests/Interop/PInvoke/Int128/ProgramFieldLayout.cs:line 14
Expected: 100
Actual: 0
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/Interop/PInvoke/Int128/Int128TestFieldLayout/Int128TestFieldLayout.sh
Expected: True
Actual:   False


Stack trace
   at Interop_PInvoke._Int128_Int128TestFieldLayout_Int128TestFieldLayout_._Int128_Int128TestFieldLayout_Int128TestFieldLayout_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by davidwrighton**
- Crossgen2 compiler was failing to detect that structs containing Int128 needed marshalling
- The contract we provide is that Int128 is aligned within a structure, but we do not provide guarantees around 128bit alignment itself, so the test needed updating for that.

Fixes #74318

### CODE REVIEW

**Review by tannergooding — APPROVED** [review]

**Review by jkoritzinsky — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by akoeplinger** [comment]
@davidwrighton I've seen this failing in 7.0-rc1 too, do you plan on backporting the fix?

**Comment by davidwrighton** [comment]
@akoeplinger I plan to fix this in 7.0, but not port to 7.0-rc1 unless there is some specific ask to do so.

**Comment by akoeplinger** [comment]
That's fine by me, I just saw it failing in 7.0-rc1 as part of Test Monitor.

**Pull request merged**
