### PR TITLE
Fix Avx2 helpers

### PR DESCRIPTION
**Pull request by sbomer**
Unblocks dotnet-optimization flow and https://github.com/dotnet/runtime/issues/84711. Includes a dotnet-optimization update to confirm this it avoids the issue discussed in https://github.com/dotnet/runtime/pull/84635. This fixes that issue by preventing R2R for any Avx2 helpers which assume they are called with Avx2 enabled.

@davidwrighton taking a shot at fixing this by skipping R2R for the instances that I was able to find ~by inspection~ [edit: using the platform analyzer with some [tweaks](https://gist.github.com/sbomer/4bfb41750259d60810aeb0b92bcc0279)]. ~Just a draft for now since I'm not sure if this is the approach we want to take - I just wanted to see what happens in ci.~

### CODE REVIEW

**Comment by MihaZupan** [comment]
Just to confirm I understand the [rules](https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/botr/vectors-and-intrinsics.md#crossgen1-model-of-hardware-intrinsic-usage) for `S.P.CoreLib`, a method like [`Vector128.ShuffleUnsafe`](https://github.com/dotnet/runtime/blob/0fc8978b8f056647a88f7b18de8840fead97d16e/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Vector128.cs#L2447-L2465) may end up calling the `Shuffle` fallback when running on ARM/WASM, but it will never call the fallback on a platform with `Ssse3` support, because that is treated differently?

I'm asking about `ShuffleUnsafe` specifically because the callers **do expect** different behavior depending on the platform.

**Comment by davidwrighton** [comment]
@sbomer I believe this looks good for now. I'm working on a more permanent fix, that will likely result in changes to all of these places to a slightly different form, but getting a fix in before the snap would be better.

@MihaZupan The "rules" indicate that the ShuffleUnsafe method has a problem, but as @sbomer notes, there are also some implementation choices in the current default behavior of Crossgen2 which make the ShuffleUnsafe method reliably functional.

**Review by davidwrighton — APPROVED** [review]
Looks good for now. I'm working on an analyzer we can turn on all the time, and some crossgen2 tweaks to make it easier to write these things. As it is the BypassReadyToRun changes will pessimize some of the work done for the ASP.NET composite container scenario, but I prioritize working over not working.  @dotnet/crossgen-contrib

**Comment by MihaZupan** [comment]
Is something like this also problematic? https://github.com/dotnet/runtime/blob/4ab5265bd701d0f076979c3f63f130c61772b7be/src/libraries/System.Private.CoreLib/src/System/IndexOfAnyValues/IndexOfAnyAsciiSearcher.cs#L822-L825

Could we end up calling into `PackedSimd` on ARM for example?

**Comment by davidwrighton** [comment]
@MihaZupan, technically ... yes, except you'd have to pass a very surprising set of switches to crossgen2, which nobody is likely to do. I've a followon fix (#85481) which should make this very hard to mess up, and will protect against that kind of case.

**Pull request merged**
