### PR TITLE
[wasm][mt] Move FeatureWasmThreads to Directory.Build.props

### PR DESCRIPTION
**Pull request by radekdoulik**

### CODE REVIEW

**Comment by radekdoulik** [comment]
I wasn't sure about evaluation order before, it works fine locally, so let see how it will go on CI.

**Comment by radekdoulik** [comment]
I wonder whether it would be also ok to remove the `TargetPlatformIdentifier` setting from the src/libraries projects.

**Review by ViktorHofer — CHANGES_REQUESTED** [review]
The `TargetFramework` property shouldn't be read in Directory.Build.props files or at any place before the project file is evaluated. `TargetFramework` isn't defined i.e. for non multi-targeting projects until it is set in the project file.

**Comment by radekdoulik** [comment]
In our case it would work, as we use `TargetFrameworks` for cases where `FeatureWasmThreads` evals as true. OTOH it is not quite obvious, so I will not want to go that way.

@maraf would you like to try your RID idea in this draft?

**Comment by ViktorHofer** [comment]
> In our case it would work, as we use TargetFrameworks for cases where FeatureWasmThreads evals as true. OTOH it is not quite obvious, so I will not want to go that way.

Yes. Our rule of thumb is to not condition on TargetFramework in properties before the project file is imported, i.e. in Directory.Build.props.

**Pull request closed without merging**
