### PR TITLE
Work around NuGet issue

### PR DESCRIPTION
**Pull request by jaredpar**
Attempting to work around our NuGet restore issue that's impacting builds. 

https://github.com/dotnet/runtime/issues/32764

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/runtime-infrastructure for review

**Comment by jkoritzinsky** [comment]
Don't we also want this in the installer build?

**Comment by jaredpar** [comment]
@jkoritzinsky doesn't matter cause the proposed work around didn't actually work. This build failed with the exact error it wanted to prevent 

https://dev.azure.com/dnceng/public/_build/results?buildId=540894&view=logs

**Comment by danmosemsft** [comment]
Please add exactly 1 area label if the bot does not: it trains the bot.

**Pull request closed without merging**
