### PR TITLE
Re-enable event tracing feature on NativeAOT/iOS and fix PalCreateDump.cpp build

### LINKED ISSUE #89625: Native AOT cross-build for iOS cannot find 'libproc.h' file
## Description

https://dev.azure.com/dnceng-public/public/_build/results?buildId=355046&view=logs&jobId=59056779-c81b-5864-b8d0-ad352b49f318&j=59056779-c81b-5864-b8d0-ad352b49f318&t=3c3013e3-ef38-5def-c703-b3c9fdc13929

```
Commencing build of "  alljits nativeaot " target in "CoreCLR component" for ios.arm64.Release in /Users/miloskotlar/dotnet/runtime/artifacts/obj/coreclr/ios.arm64.Release
...
 /Users/miloskotlar/dotnet/runtime/src/coreclr/nativeaot/Runtime/unix/PalCreateDump.cpp:31:10: fatal error: 'libproc.h' file not found
  #include <libproc.h>
           ^~~~~~~~~~~
  [ 71%] Building CXX object nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/__/unix/PalRedhawkUnix.cpp.o
  1 error generated.
  make[3]: *** [nativeaot/Runtime/Full/CMakeFiles/Runtime.WorkstationGC.dir/__/unix/PalCreateDump.cpp.o] Error 1
  make[3]: *** Waiting for unfinished jobs....
  [ 73%] Building CXX object nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/__/__/__/gc/unix/gcenv.unix.cpp.o
  [ 73%] Building CXX object nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/__/unix/PalCreateDump.cpp.o
  [ 73%] Building CXX object nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/__/__/__/gc/unix/numasupport.cpp.o
  [ 73%] Building CXX object nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/__/__/__/gc/unix/events.cpp.o
  [ 73%] Building CXX object nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/__/__/__/gc/unix/cgroup.cpp.o
  [ 73%] Built target eventpipe-enabled
  /Users/miloskotlar/dotnet/runtime/src/coreclr/nativeaot/Runtime/unix/PalCreateDump.cpp:31:10: fatal error: 'libproc.h' file not found
  #include <libproc.h>
           ^~~~~~~~~~~
  1 error generated.
  make[3]: *** [nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/__/unix/PalCreateDump.cpp.o] Error 1
  make[3]: *** Waiting for unfinished jobs....
  [ 75%] Building CXX object nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/__/interoplibinterface_objc.cpp.o
  [ 75%] Building CXX object nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/__/AsmOffsetsVerify.cpp.o
  make[2]: *** [nativeaot/Runtime/Full/CMakeFiles/Runtime.WorkstationGC.dir/all] Error 2
  make[2]: *** Waiting for unfinished jobs....
  make[2]: *** [nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/all] Error 2
  make[1]: *** [CMakeFiles/nativeaot.dir/rule] Error 2
  make: *** [nativeaot] Error 2
  ~/dotnet/runtime/src/coreclr
  ##vso[task.logissue type=error]Failed to build "CoreCLR component".

```

/cc: @mikem8361

## Reproduction steps

```sh
./build.sh -ci -arch arm64 -os ios  --cross -s clr.alljits+clr.tools+clr.nativeaotruntime+clr.nativeaotlibs+libs -c Release
```

### PR DESCRIPTION
**Pull request by filipnavara**
Side-note: Building CoreCLR with FEATURE_EVENT_TRACE=0 is utterly broken at the moment. Since `ICorProfilerCallback10` exposed part of the feature in public API I am not sure whether there's any reason to resurrect it.

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]
LGTM, the iOS NativeAOT runtime tests are green, tvOS is running into an issue with the PalCreateDump.cpp but that is unrelated.

**Comment by akoeplinger** [comment]
>  tvOS is running into an issue with the PalCreateDump.cpp but that is unrelated

@filipnavara tvOS doesn't support fork()/execve(), we probably need to just disable this code there and on iOS. Do you want to do it in this PR or should we do it separately?

**Comment by filipnavara** [comment]
I will do it in this PR.

**Comment by filipnavara** [comment]
I committed a build fix. GitHub is slow to realise it (and .NET hosting servers had outage minutes ago; possibly unrelated).

**Pull request merged**
