### PR TITLE
Update dotnetbuilds domain

### PR DESCRIPTION
**Pull request by richlander**
Related: https://github.com/dotnet/core/issues/9671

### CODE REVIEW

**Comment by richlander** [comment]
Oh ... Is this file updated via Arcade/Maestro?

**Comment by am11** [comment]
> Oh ... Is this file updated via Arcade/Maestro?

Yes, https://github.com/dotnet/runtime/edit/main/eng/common/README.md.
Optionally we can keep this PR to test the CI and even merge it afterwards while the change from arcade is being propagated.

**Comment by am11** [comment]
> Oh ... Is this file updated via Arcade/Maestro?

Yes, https://github.com/dotnet/runtime/blob/main/eng/common/README.md.
Optionally we can keep this PR to test the CI and even merge it afterwards while the change from arcade is being propagated. Key is to avoid arcade sync revert the change subsequently.

**Review by jkoritzinsky — APPROVED** [review]
These updates need to also be ported to dotnet/arcade or they'll be overwritten on the next Arcade update.

**Comment by richlander** [comment]
Merging one of these PRs will have much of the same effect, due to the change in the same files:

- https://github.com/dotnet/runtime/pull/110907
- https://github.com/dotnet/runtime/pull/110894

https://github.com/dotnet/runtime/pull/110907/files#diff-72b8f8e899b94872c6ead31fd06ec109da15bcb9ad2af6e78103d6763a31c637R267

**Pull request closed without merging**
