### PR TITLE
setting prerelease to 0 for previews

### PR DESCRIPTION
**Pull request by Anipik**
This needs to done to avoid shipping non ready features

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by ericstj** [comment]
Is there an issue describing this?

**Comment by GrabYourPitchforks** [comment]
Should be part of https://github.com/dotnet/runtime/issues/35903?

**Comment by Anipik** [comment]
This needs to be done as a part of every release. Unfortunately, currently there are no good ways to set these properties on the basis of GitHub branch name for previews. so we have to do this each time.

**Comment by Anipik** [comment]
#35903 describes that this flag needs to be set for preview branches as well.

**Pull request merged**
