### PR TITLE
Fix covariant override disassembly

### PR DESCRIPTION
**Pull request by davidwrighton**
- This introduces a new path where ildasm must generate a full token description instead of relying on ilasm to produce the signature from the method body

### CODE REVIEW

**Comment by davidwrighton** [comment]
Fixes #38508 and #37045

**Comment by davidwrighton** [comment]
@janvorli FYI

**Review by BruceForstall — APPROVED** [review]
LGTM. Probably should kick off a run of the round-trip test pipeline on this: https://dev.azure.com/dnceng/public/_build?definitionId=870

**Comment by mangod9** [comment]
so assume no changes are required to ILASM?

**Comment by davidwrighton** [comment]
@mangod9, no there aren't any required changes to ilasm that I can find. Also, unfortunately, in the general sense we can't produce good warnings. We could make it slightly better for overriding functions defined in the same module but that would be somewhat more complex and risky, and I do not believe it will provide value.

**Pull request merged**
