### PR TITLE
Use full TLS record size for application data on Windows

### LINKED ISSUE #51478: SslStream should do a better job of allocating buffer for encryption
See discussion here: https://github.com/dotnet/runtime/pull/51060

Currently we do two things:
(1) Add a fixed FrameOverhead (now 64 bytes, previously 32) to the input size when allocating a buffer to encrypt into; 
(2) Later, in SslStreamPal.EncryptMessage, we will detect a buffer that is too small and allocate a new, temporary buffer to use instead.

This results in two problems:
(1) We are often allocating more than we need to, since the actual header/trailer size is usually less than 64 bytes.
(2) If 64 bytes is not enough, we will silently fall back to a much less performant path, i.e. allocating lots of unpooled buffers. We saw this previously when FrameOverhead was 32 bytes, which is why we changed it to 64.

We know the exactly header and trailer size before we actually do the encryption. We should be able to allocate the exact size needed and remove the unperformant fallback in SslStreamPal.EncryptMessage. This is slightly complicated by renegotiation, but we should be able to just make this work.

@benaadams @wfurt

### PR DESCRIPTION
**Pull request by rzikm**
Don't reduce MaximumMessage by Header and Trailer sizes (they are not included in the size limit).

Previous behavior led to us not consuming input in multiples of power of 2 which led to unnecessary fragmenting of data into TLS packets. The behavior was most noticeable when using 16kB buffer in calls to Write(Async) functions. Where we would split it into two TLS packets with the latter containing only about 40 B of useful data (see wireshark captures below).

This PR also removes some unsafe annotations on the code path.

<details>

<Summary>WireShark captures (Windows)</Summary>

before (notice the 135B TLS packets)
image

after
image

</details>

<details>
<Summary>Benchmarks (Windows)</Summary>

The LargeReadWriteAsync benchmarks use 64kB buffers, so this PR should reduce the number of encryption calls by 1/5

| Method                         | Job        | Toolchain                                                                               | Mean        | Error     | StdDev    | Median      | Min         | Max         | Ratio | RatioSD | Allocated | Alloc Ratio |
|------------------------------- |----------- |---------------------------------------------------------------------------------------- |------------:|----------:|----------:|------------:|------------:|------------:|------:|--------:|----------:|------------:|
| ReadWriteAsync                 | Job-VRYUDS | \pr\corerun.exe |    34.00 us |  0.366 us |  0.343 us |    33.91 us |    33.44 us |    34.71 us |  0.99 |    0.02 |         - |          NA |
| ReadWriteAsync                 | Job-GONFII | \main\corerun.exe                                                                       |    34.33 us |  0.395 us |  0.350 us |    34.26 us |    33.74 us |    35.01 us |  1.00 |    0.00 |         - |          NA |
|                                |            |                                                                                         |             |           |           |             |             |             |       |         |           |             |
| LargeReadWriteAsync            | Job-VRYUDS | \pr\corerun.exe |    57.22 us |  1.710 us |  1.969 us |    57.91 us |    53.08 us |    59.97 us |  0.88 |    0.04 |     491 B |        1.01 |
| LargeReadWriteAsync            | Job-GONFII | \main\corerun.exe                                                                       |    65.05 us |  1.296 us |  1.492 us |    65.03 us |    62.89 us |    68.19 us |  1.00 |    0.00 |     484 B |        1.00 |
|                                |            |                                                                                         |             |           |           |             |             |             |       |         |           |             |
| ConcurrentReadWrite            | Job-VRYUDS | \pr\corerun.exe | 1,381.65 us | 51.610 us | 59.434 us | 1,389.42 us | 1,266.48 us | 1,471.83 us |  1.02 |    0.07 |         - |        0.00 |
| ConcurrentReadWrite            | Job-GONFII | \main\corerun.exe                                                                       | 1,367.73 us | 75.121 us | 83.496 us | 1,379.64 us | 1,165.86 us | 1,469.80 us |  1.00 |    0.00 |       1 B |        1.00 |
|                                |            |                                                                                         |             |           |           |             |             |             |       |         |           |             |
| ConcurrentReadWriteLargeBuffer | Job-VRYUDS | \pr\corerun.exe | 1,021.83 us | 46.291 us | 53.309 us | 1,032.54 us |   895.20 us | 1,094.38 us |  0.99 |    0.11 |         - |        0.00 |
| ConcurrentReadWriteLargeBuffer | Job-GONFII | \main\corerun.exe                                                                       | 1,043.22 us | 70.858 us | 81.600 us | 1,038.13 us |   838.79 us | 1,156.26 us |  1.00 |    0.00 |       4 B |        1.00 |

</details>

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by garath** [comment]
> Could you please have a look?

We currently have no known ongoing issues.

Please point me to a particular error?

**Comment by wfurt** [comment]
I'm not sure what @rzikm had in ind. But for example https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-95595-merge-b3746c6d13a44017a0/Common.Tests/1/console.a0e72f3a.log?helixlogtype=result

it seems like the tests executed but it is reported as failure.

```
category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing  
  Discovering: Common.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Common.Tests (found 6 of 268 test cases)
  Starting:    Common.Tests (parallel test collections = on, max threads = 2)
  Finished:    Common.Tests
=== TEST EXECUTION SUMMARY ===
   Common.Tests  Total: 30, Errors: 0, Failed: 0, Skipped: 0, Time: 1.516s

```

**Comment by garath** [comment]
Looks like you're also running into #95762. Perhaps connected and something is significantly breaking test reporting in these runs?

**Pull request merged**
