### PR TITLE
[release/8.0] Disable user mapper for SslStream on Windows (TLS 1.3) (#100833)

### LINKED ISSUE #100774: When running a Kestrel HTTPS server on Windows, unneccessary active directory authentication is attempted when accepting a new connection from a client.
### Description

We have a .NET 8 web app based on Kestrel with self-signed certificates for HTTPS. When the app is running on Windows 10 and receiving requests, a pair of 4625 (Logon Failure) evets appear in the Windows Security event log, indicating unnecessary attempts to authenticate with Windows despite the certificate not correspoding to any Windows security principal. When debugging the code, I found out that the events are logged during the initial TLS handshake, within the call to SSPIWrapper.AcceptSecurityContext at https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs#L124 .

### Configuration

.NET 8 (build 8.0.1.23580)
Windows 10 Pro, build 19045.2486
x64

### Regression?

No

### Data

The main impact of this issue for us is on Windows security event storage, as the app is used quite heavily. This also makes it difficult to inspect Windows Security logs, needing to filter all 4625 Logon Failure event and possibly missing actual malicious login attempts.

### Analysis
I believe this issue has the same root cause as #78350 . This issue was already fixed for the old schannel API in #80886 by setting the SCH_CRED_NO_SYSTEM_MAPPER flag by default when calling AcquireCredentialsHandle, however for the new SCH API, the flag is only set when sending the full certificate chain: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs#L368 . As the affected system is running on a Windows 10 build new enough that the SCH API is used, I believe this issue could get resolved if the SCH_CRED_NO_SYSTEM_MAPPER is set by default also to the call to AcquireCredentialsHandle for SCH.

### LINKED ISSUE #108966: [8.0] Self-signed certificates flood Windows Security event log
I would like to re-open discussion about backporting the fix for #100774 into .NET 8, as we have been getting more reports about impact of the audit logs to site oprations.
 
> @ds185287 for a 8.0 backport, we would need more details about impact on the production - ideally directly from the customer.
> 
> What about workarounds: Is it possible to filter out these (useless) events and ignore them? If not, why?
> 
> What does it mean that CIEM solution cannot cope? Is it running out of memory, CPU, or something like that? ... More details here would help us to make the call. 

 _Originally posted by @karelz in [#100774](https://github.com/dotnet/runtime/issues/100774#issuecomment-2047525865)_

@jp185163 should provide additional details about impact directly to the customer

Tagging @rzikm @karelz for attention.

### PR DESCRIPTION
**Pull request by rzikm**
Backport of #100833 to release/8.0-staging.

Fixes #108966
Fixes #100774

/cc @rzikm @avin3sh

## Customer Impact

Reported by customer: From https://github.com/dotnet/runtime/issues/108966#issuecomment-2426836531
The bug generates 12.1 millions of events in 24h period. They have to filter them out. The problem is that due to regulatory requirement they have to store them for a year, which requires large storage.

Note: Same fix for TLS 1.0-1.2 happened in .NET 8 (before GA): #80886 ... we just missed the branch for TLS 1.3.

## Regression

No

## Testing

CI tests pass.
Pending customer validation - unclear if it will happen in time.

## Risk

Low, the change is small and affects only a specific scenario (Windows, SSL Server). The same change has been made in 9.0 few months ago for TLS 1.3 and there are no known issues. Similar fix happened in 8.0 (before GA) for TLS 1.0-1.2 (see #80886).

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by teo-tsirpanis** [comment]
Did you forget the `Servicing-Consider` tag?

**Comment by rzikm** [comment]
> Did you forget the `Servicing-Consider` tag?

We only put that tag once the PR description has been finalized, there are some missing pieces waiting for @karelz's input.

**Review by karelz — APPROVED** [review]

**Comment by karelz** [comment]
Large impact on few customers on LTS with regulatory impact. We should backport it to 8.0.x

**Comment by rzikm** [comment]
Approved via email on 11/14

**Comment by rzikm** [comment]
The CI failure is unrelated (System.Text.Json). ready to merge.

**Pull request merged**
