### PR TITLE
ServiceKey comparisons use Equals for matching

### LINKED ISSUE #95754: RemoveAllKeyed Requires Equality Operator
### Description

.NET 8 introduced the ability to register keyed services and works reasonably well, however, there seems to be a bug in `ServiceCollectionDescriptorExtensions.Keyed.cs` within the `IServiceCollection RemoveAllKeyed(this IServiceCollection collection, Type serviceType, object? serviceKey)` method that breaks objects that don't overload the equals operator.

### Reproduction Steps

Given an enumeration, for example:
```c#
public enum StorageType
{
    Local,
    Cloud
}
``` 
The following test will fail:
```c#
var services = new ServiceCollection()
    .AddKeyedTransient<IStorage, LocalStorage>(StorageType.Local)
    .AddKeyedTransient<IStorage, CloudStorage>(StorageType.Cloud);

services.RemoveAllKeyed<IStorage>(StorageType.Cloud);

// test succeeds
Assert.Contains(services, descriptor => descriptor.ServiceType == typeof(IStorage) && (descriptor.ServiceKey?.Equals(StorageType.Local) ?? false));
// test fails - service still exists
Assert.DoesNotContain(services, descriptor => descriptor.ServiceType == typeof(IStorage) && (descriptor.ServiceKey?.Equals(StorageType.Cloud) ?? false));
``` 

### Expected behavior

The` IServiceCollection RemoveAllKeyed(this IServiceCollection collection, Type serviceType, object? serviceKey)` should remove any service types matching the specified key regardless of whether the type overloads the equals operator.

### Actual behavior

The` IServiceCollection RemoveAllKeyed(this IServiceCollection collection, Type serviceType, object? serviceKey)` does not remove any service types matching the specified key if the type does not overload the equality operator.

### Regression?

_No response_

### Known Workarounds

The problem can be solved by changing the equality operator in this method to the Equals method:
```c#
public static IServiceCollection RemoveAllKeyed(this IServiceCollection collection, Type serviceType, Enum? serviceKey)
{
    serviceType.CheckNotNull(nameof(serviceType));

    for (var i = collection.Count - 1; i >= 0; i--)
    {
        var descriptor = collection[i];

        if (descriptor.ServiceType == serviceType && (descriptor.ServiceKey?.Equals(serviceKey) ?? false))
        {
            collection.RemoveAt(i);
        }
    }

    return collection;
}
``` 

The workaround for now is to implement another extension method that uses the explicit key type for the key parameter instead of just `object`.

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tommysor**
Fix #95754

I assume here that the issue (currently untriaged) is confirmed as a bug.

Based on documentation: https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#keyed-services
> The key isn't limited to string, it can be any object you want, as long as the type correctly implements Equals.

Also based on comparison for resolving in `ServiceProvider.GetRequiredKeyedService`.
That is implemented in `Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier`
```csharp
public bool Equals(ServiceIdentifier other)
{
	if (ServiceKey == null && other.ServiceKey == null)
	{
		return ServiceType == other.ServiceType;
	}
	else if (ServiceKey != null && other.ServiceKey != null)
	{
		return ServiceType == other.ServiceType && ServiceKey.Equals(other.ServiceKey);
	}
	return false;
}
```

### CODE REVIEW

**Review by halter73 — APPROVED** [review]
Thank you! This looks like a simple fix to the keyed TryAddEnumerable/Remove/Replace service collection extensions. Thanks for added the regression tests too.

I think we should backport this for .NET 8 patching.

**Review by benjaminpetit — APPROVED** [review]

**Pull request merged**
