### PR TITLE
[wasm] Bump emscripten to 2.0.23

### PR DESCRIPTION
**Pull request by radekdoulik**

### CODE REVIEW

**Comment by radekdoulik** [comment]
The failing System.Net.Primitives.Unit.Tests.CookieContainerTest.SetCookies_Success is https://github.com/dotnet/runtime/issues/53931

**Comment by radekdoulik** [comment]
The fix for FS bug, where it ignores permissions didn't make it into 2.0.23, even if it looks like it from the commit history.

I still see this in `upstream\emscripten\src\library_fs.js`:
```
  $FS__postset: function() {
    // TODO: do we need noFSInit?
    addAtInit('if (!Module["noFSInit"] && !FS.init.initialized) FS.init();');
    addAtMain('FS.ignorePermissions = false;');
...
```
`addAtMain` shouldn't be used here.

Context: https://github.com/emscripten-core/emscripten/commit/a56817a698e5d65b1192bcb0c29fada498c45bdc

**Comment by radical** [comment]
Do we know why the AOT tests are failing?
for example - [System.Xml.XPath.XmlDocument.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-53603-merge-35c0ea94f7e241468d/System.Xml.XPath.XmlDocument.Tests/console.49365312.log?sv=2019-07-07&se=2021-06-29T13%3A23%3A42Z&sr=c&sp=rl&sig=qzdsqoGT3rTNsiZai6ajqSKFhodiUv3VhoB5saXWtXY%3D) `failed (received SIGKILL (-9))`

**Comment by radical** [comment]
Some of them are timing out, due to the recent increase in build time. We should bump the timeout, to we can at least get the tests running, and not miss any regressions. I would add

```diff
diff --git a/src/libraries/sendtohelixhelp.proj b/src/libraries/sendtohelixhelp.proj
index 84c140a2182..1dd6716f2e8 100644
--- a/src/libraries/sendtohelixhelp.proj
+++ b/src/libraries/sendtohelixhelp.proj
@@ -29,6 +29,7 @@
     <_workItemTimeout Condition="'$(Scenario)' == '' and '$(_workItemTimeout)' == '' and ('$(TargetArchitecture)' == 'arm64' or '$(TargetArchitecture)' == 'arm')">00:45:00</_workItemTimeout>
     <_workItemTimeout Condition="'$(Scenario)' != '' and '$(_workItemTimeout)' == '' and ('$(TargetArchitecture)' == 'arm64' or '$(TargetArchitecture)' == 'arm')">01:00:00</_workItemTimeout>
     <_workItemTimeout Condition="'$(Scenario)' == 'BuildWasmApps' and '$(_workItemTimeout)' == ''">01:00:00</_workItemTimeout>
+    <_workItemTimeout Condition="'$(TargetOS)' == 'Browser' and '$(NeedsToBuildWasmAppsOnHelix)' == 'true'">01:00:00</_workItemTimeout>
     <_workItemTimeout Condition="'$(Scenario)' == '' and '$(_workItemTimeout)' == ''">00:15:00</_workItemTimeout>
     <_workItemTimeout Condition="'$(Scenario)' != '' and '$(_workItemTimeout)' == ''">00:30:00</_workItemTimeout>
```

**Comment by radical** [comment]
8 libraries are failing with AOT. Some are timing out, some with emcc getting killed with:

`emcc : error : '/datadisks/disk1/work/B1410964/p/build/emsdk/upstream/bin/wasm-ld @/datadisks/disk1/work/B1410964/t/emscripten_icjo4j9w.rsp' failed (received SIGKILL (-9))`

**Comment by radekdoulik** [comment]
Looks like the `wasm-ld` is indeed causing issues here. It is always this tool, which gets killed or is timeouting.

I tried to build the first library test, which timeouts - `Microsoft.Extensions.Configuration.Json`. It builds on my machine, but the memory usage during `wasm-ld` run is peaking around 12.3GB. The helix system has only 8GB, so that might be the issue here. It took cca 16 minutes to build. I will try to build it with 2.0.21 as well to see how the memory usage compares.

Note: the local build might be behaving differently compared to helix, I see 81 assemblies AOT'ed after linking vs 61 on helix.

**Comment by radical** [comment]
Do you think https://github.com/dotnet/runtime/pull/54053 might help? It builds dll -> .bc -> .o with `Oz`, and then links with `O0`.

**Comment by radekdoulik** [comment]
The `2.0.21` build of the same lib test peaked around 8.8GB of memory. So it looks like regression of `wasm-ld`. I will try to get more details and open an issue in emscripten repo.

**Comment by lewing** [comment]
cc @marek-safar

**Comment by radekdoulik** [comment]
It might be the new string tail merging in wasm-ld:

```
- wasm-ld will now perform string tail merging in debug string sections as well
  as regular data sections.   This behaviour can be be disabled with `-Wl,-O0`.
  This should significantly reduce the size of dwarf debug information in the
  wasm binary.
```

Let see if the `-Wl,-O0` changes the memory load.

**Comment by radekdoulik** [comment]
`-Wl,O0` doesn't help with the memory load.

Merging current `main` improves it a bit, we are still at 10.9GB peek.

I have opened https://github.com/emscripten-core/emscripten/issues/14485 and will try to dig deeper to see if I can spot what might be causing the higher memory usage.

**Comment by radekdoulik** [comment]
Lukas Lansky opened a ticket for us to get more memory (and cores as side effect) https://github.com/dotnet/core-eng/issues/13425

**Comment by lewing** [comment]
Nice to see this green, please get in mergeable condition so we can land it.

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
browser failure is https://github.com/dotnet/runtime/issues/53957

**Comment by radekdoulik** [comment]
CoreCLR Pri0 Runtime Tests Run windows arm64 checked - failure is the same seen in https://github.com/dotnet/runtime/pull/54053 and doesn't contain logs

**Pull request merged**
