### PR TITLE
Use the portable timer implementation in CoreCLR

### LINKED ISSUE #46266: Use Portable TimerQueue when using Portable ThreadPool
We should use the portable timer queue when the portable thread pool has been selected. As for some of the benefits:
- The managed timer queue doesn't need to allocate when being scheduled to the thread pool since it implements IThreadPoolWorkItem
- It simplifies the native/managed interaction between the thread pool and timer queue. Today if you switch to the portable thread pool, the native timer queue needs to schedule work onto it (https://github.com/dotnet/runtime/blob/7e44a6a596208c0038010f1ade1623bc22f889dd/src/coreclr/vm/win32threadpool.cpp#L4831-L4843)
- The other benefits from moving to managed code (easier to maintain, same code on all platforms, etc)

I've spoke to @kouvel about this in passing so filing something just to track it.

### PR DESCRIPTION
**Pull request by kouvel**
Fixes https://github.com/dotnet/runtime/issues/46266

### CODE REVIEW

**Comment by kouvel** [comment]
No significant difference in timer microbenchmarks:

|                                  Method | Toolchain |               Mean |            Error |           StdDev |
|----------------------------------------:|----------:|-------------------:|-----------------:|-----------------:|
|                 ShortScheduleAndDispose |    Before |           137.8 ns |          4.31 ns |          4.96 ns |
|                 ShortScheduleAndDispose |     After |           129.9 ns |          3.48 ns |          4.01 ns |
|                                         |           |                    |                  |                  |
|                  LongScheduleAndDispose |    Before |           131.5 ns |          2.60 ns |          2.43 ns |
|                  LongScheduleAndDispose |     After |           129.9 ns |          3.38 ns |          3.89 ns |
|                                         |           |                    |                  |                  |
|             ScheduleManyThenDisposeMany |    Before |   469,028,385.0 ns | 10,482,945.31 ns | 12,072,175.41 ns |
|             ScheduleManyThenDisposeMany |     After |   450,835,495.0 ns | 28,191,768.65 ns | 32,465,682.70 ns |
|                                         |           |                    |                  |                  |
| ShortScheduleAndDisposeWithFiringTimers |    Before |           153.8 ns |          6.07 ns |          6.24 ns |
| ShortScheduleAndDisposeWithFiringTimers |     After |           160.6 ns |          4.80 ns |          5.33 ns |
|                                         |           |                    |                  |                  |
|                   SynchronousContention |    Before | 4,334,738,207.1 ns | 26,386,498.36 ns | 23,390,943.51 ns |
|                   SynchronousContention |     After | 4,332,649,160.0 ns | 26,337,511.15 ns | 24,636,124.27 ns |
|                                         |           |                    |                  |                  |
|                  AsynchronousContention |    Before | 4,333,695,664.3 ns | 12,912,192.76 ns | 11,446,322.56 ns |
|                  AsynchronousContention |     After | 4,338,598,086.7 ns | 12,938,144.86 ns | 12,102,348.73 ns |

**Comment by am11** [comment]
Do we want to update NativeAOT's project file too? `src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj`

cc @MichalStrehovsky

**Comment by jkotas** [comment]
> Do we want to update NativeAOT's project file too?

This is switching CoreCLR to what NativeAOT used since forever.

**Review by jkotas — APPROVED** [review]
Nice!

**Comment by am11** [comment]
@jkotas, I meant these defaults: https://github.com/dotnet/runtime/blob/a4b5376ae65d81c71898801772655c79dea7cfc9/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj#L28-L35 on windows, it is `false`.

**Comment by jkotas** [comment]
NativeAOT is using native Windows OS threadpool on Windows. We may want to change it, but not in this PR. It is not obvious that it would be an improvement.

**Review by filipnavara — APPROVED** [review]

**Comment by davidfowl** [comment]
❤️

**Comment by davidfowl** [comment]
The only nit would be to remove the comment saying that this is a Unix specific implementation of the timer queue

**Pull request merged**
