### PR TITLE
[mono][wasm] Fix ldftn in AOT mode, it should return a ftndesc.

### LINKED ISSUE #82272: [wasm] `System.Reflection.Tests.MethodInfoTests.TestFunctionPointers` failing with AOT on linux
[System.Reflection.Tests log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-f813c52ee3964e05a1/normal-System.Reflection.Tests/1/console.ee1525d7.log?helixlogtype=result):

```
[22:28:04] fail: [FAIL] System.Reflection.Tests.MethodInfoTests.TestFunctionPointers
[22:28:04] info: System.ArgumentException : Object of type 'System.Reflection.Tests.OtherColorsInt' cannot be converted to type 'System.Reflection.Tests.ColorsShort'.
[22:28:04] info:    at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
```

[System.Reflection.InvokeInterpreted.Tests](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-f813c52ee3964e05a1/normal-System.Reflection.InvokeInterpreted.Tests/1/console.f436abc1.log?helixlogtype=result):
```
[22:27:07] fail: [FAIL] System.Reflection.Tests.MethodInfoTests.TestFunctionPointers
[22:27:07] info: System.InvalidOperationException : Operation is not valid due to the current state of the object.
[22:27:07] info:    at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
```

[System.Reflection.InvokeEmit.Tests](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-f813c52ee3964e05a1/normal-System.Reflection.InvokeEmit.Tests/1/console.636fa5d7.log?helixlogtype=result):

```
[22:26:59] fail: [FAIL] System.Reflection.Tests.MethodInfoTests.TestFunctionPointers
[22:26:59] info: System.ArgumentException : Missing parameter does not have a default value. (Parameter 'parameters')
[22:26:59] info:    at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
```

This was added in https://github.com/dotnet/runtime/pull/81006 and didn't get caught because we run only smoke tests for AOT/wasm on PRs.

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by vargaz**
Fixes https://github.com/dotnet/runtime/issues/82272.

### CODE REVIEW

**Comment by vargaz** [comment]
Failures are relevant.

**Review by lewing — APPROVED** [review]

**Comment by maraf** [comment]
Can we enable tests distabled in https://github.com/dotnet/runtime/pull/82285?

**Pull request merged**
