### PR TITLE
Try skipping generation of empty method dictionaries

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Say we're compiling `Foo<__Canon>.Method` for:

```csharp
class Foo<T>
{
    static void Method() => GenericMethod<List<T>>();
    static void GenericMethod<T>() { }
}
```

In the method body, we're generating a call to `GenericMethod<__Canon>` with a generic dictionary that we looked up from `Foo`s dictionary. But as you can see, the dictionary is empty because `GenericMethod` doesn't do anything with it's T. RyuJIT might even inline it.

The problem is that we computed how the dictionary will look like during scanning and we're forever stuck with instruction to generate a generic dictionary for every `Foo<T>` instantiation.

This is adding an optimization - if during scanning we find out that the dictionary layout of the target method is empty, ~~we skip the slot. If RyuJIT ends up asking for something, we just give it garbage. The garbage will not be dereferenced because the dictionary layout was empty and there's nothing to look up from it.~~ we instruct RyuJIT to generate a null generic context pointer.

Saves 1.5% on BasicMinimalApi.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Comment by jkotas** [comment]
> If RyuJIT ends up asking for something, we just give it garbage. 

Can we tell RyuJIT to use `null` as the dictionary value in this case?

It is confusing to pass garbage as the dictionary pointer. Also, managed debuggers give you better experience when the dictionary pointer is available, that won't be possible to do reliably if we start passing in garbage.

**Comment by MichalStrehovsky** [comment]
> > If RyuJIT ends up asking for something, we just give it garbage.
> 
> Can we tell RyuJIT to use `null` as the dictionary value in this case?
> 
> It is confusing to pass garbage as the dictionary pointer. Also, managed debuggers give you better experience when the dictionary pointer is available, that won't be possible to do reliably if we start passing in garbage.

What direction would you prefer? Make a null slot and tell RyuJIT to look up that (worse size, but easier to implement), or extend jitinterface to express this?

**Comment by jkotas** [comment]
It would be nice to tell the JIT to pass NULL as the dictionary pointer.

**Comment by MichalStrehovsky** [comment]
> It would be nice to tell the JIT to pass NULL as the dictionary pointer.

Updated to do this. It shaves off another 2 kB, but I like it less. It was nicer when RyuJIT didn't need to be aware.

**Review by jkotas — APPROVED** [review]
LGTM. Thanks!

**Comment by jkotas** [comment]
Would it be worth it to extend this to callsites in non-generic code?

**Comment by MichalStrehovsky** [comment]
> Would it be worth it to extend this to callsites in non-generic code?

I did a quick hack and it indicates about 0.08% savings for BasicMinimalApi so maybe not worth it given this would be another crosscutting thing that requires touching JitInterface.

**Comment by MichalStrehovsky** [comment]
@EgorBo could you please have a look at the JIT change?

**Review by EgorBo — APPROVED** [review]
Sorry for the delay, jit side LGTM!

**Pull request merged**
