### PR TITLE
Fix build for System.Text.Encodings.Web

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Addresses https://github.com/dotnet/runtime/issues/39444

### CODE REVIEW

**Comment by danmosemsft** [comment]
Curious how this got through CI, if it breaks CI. Do we know? Usually that is because two conflicting changes merged at the same time?

**Comment by eiriktsarpalis** [comment]
@danmosemsft it was caused by bf35bfd11f74fb1efe1c3a1e749636113270eccd which broke the logic found here: https://github.com/dotnet/runtime/commit/7fab504a54e97b20d08946c2ed621b48cca4fbc6#diff-e2009cfe1f129dd4d69891e2c457a0f9

**Comment by danmosemsft** [comment]
@eiriktsarpalis right, what I'm curious about is how it went through CI. @aik-jahoda it looks like https://github.com/dotnet/runtime/pull/39416 didn't pass CI ?

**Comment by danmosemsft** [comment]
As mentioned to @eiriktsarpalis offline, since the build is presumably broken for large numbers of people right now, feel free to merge without waiting for CI if you have good confidence. I see almost all build jobs have completed successfully.

I think we're waiting on @pgovind to fix another issue though?

cc @ericstj @karelz

**Comment by eiriktsarpalis** [comment]
@danmosemsft this is the PR to master, which doesn't suffer from the same issue. I've already merged the cherry picked PR to preview8. #39448

**Comment by danmosemsft** [comment]
thanks

**Comment by aik-jahoda** [comment]
> @eiriktsarpalis right, what I'm curious about is how it went through CI. @aik-jahoda did #39416 pass CI fully?

No it wasn't and it actually discovered two similar issue, this one and #39431. It highlights that it is not possible to catch such issue during master branch CI. Only review or local build with specific flags can discover it. The build was broken anyway because of missing cherry pick: #39434.

**Review by aik-jahoda — APPROVED** [review]

**Pull request merged**
