### PR TITLE
Update SDK to 6.0 RC2

### PR DESCRIPTION
**Pull request by ViktorHofer**
Updating the SDK now to see if there's anything that needs attention for dotnet/runtime to consume RC2 and the final 6.0 SDK later.

### CODE REVIEW

**Comment by ericstj** [comment]
Looks like conflict resolution isn't picking the ref pack.  I would expect https://github.com/dotnet/sdk/commit/fb094f4fad41bb66aaff6c954d04743368b3f5cd to have fixed this scenario, which was in RC2.

**Comment by ericstj** [comment]
Yeah, that's the difference.  I checked a passing all configurations build from a random PR and see this:
image

Compared to this failing PR:
image

**Comment by am11** [comment]
https://github.com/dotnet/sdk/commit/70f204b18c1de8ed109e789228e2f171e4978845 is new in rc2 which seems to be related.

**Review by rainersigwald — APPROVED** [review]
FYI @dsplaisted @marcpopMSFT -- the targeting pack caching I added to SDK broke runtime but the escape hatch seems like it's keeping things ok.

**Comment by mmitche** [comment]
> > Can you ping this thread once they're uploaded? That looks to be the next blocker on this PR.
> 
> I'm resolving this now by uploading all the shipping packages to public

Done.

**Comment by jkoritzinsky** [comment]
@mmitche it looks like some of the Android runtime packs didn't make it onto dotnet-public yet.

In particular, it looks like `Microsoft.NETCore.App.Runtime.Mono.android-arm64` was missed, which is causing the runtime-staging build failures.

**Comment by jkoritzinsky** [comment]
@vitek-karas @agocke can I get some help figuring out why the hosting tests are failing? I can't repro it locally on my Mac.

**Comment by vitek-karas** [comment]
The seem to be test failures there, for example:
```
[EXEC       <] [FAIL] [00:00:02.126] > /Users/runner/work/1/s/artifacts/tests/Release/ha/o2fy5n4v.lt1/PortableApp/bin/PortableApp exited with 131
```

But the test upload probably didn't work, or something else happened since the specific test results are not available. There are also no detailed logs from the tests (the `xml` files or similar).

I don't know enough about the infra to be able to tell if this is a problem, or by design. In any case we will either need to get a repro, or at least get the test logs for the failures in CI to have a clue what's going on.

One idea: @jkoritzinsky when you tried to repro it - does your machine have the latest RC2 bits installed globally? Specifically - do you have anything in `/usr/local/share/dotnet/x64` ? It should not be there if this is running on x64 hardware...
I can't tell from the logs what is the hardware this runs on - if it's an arm64 hardware... I could see several different things potentially going wrong.

**Comment by am11** [comment]
> But the test upload probably didn't work, or something else happened since the specific test results are not available. There are also no detailed logs from the tests (the `xml` files or similar).

Yes, it is quite annoying when it happens. Once installer tests are moved to helix (#59271), we will see console log links directly on github:
`Failure log: https://helix.dot.net/api/2019-06-17/jobs/xxx/workitems/yyy/console`
rather than:
`Tests failed: /Users/runner/work/1/s/artifacts/log/Release/HostActivation.Tests_net6.0_x64.log` (for which we _must_ first navigate to AzDo and after about six more clicks, just to find that logs upload has failed and attachments are empty)

**Comment by jkoritzinsky** [comment]
@vitek-karas my local machine is running macOS 11.2.3 and the newest SDK it has is 5.0.102.

For some reason we're using the Azure Pipelines images for the installer runs instead of the 1ES pools, so this link describes the machines we're using at the moment: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md

**Comment by vitek-karas** [comment]
Unfortunately that doesn't say what is the hardware/OS architecture. I checked the arm64 CI leg and it has the exact same environment... but it can run arm64 code. So either it's the same OS version just different hardware, or it's running x64 tests on arm64 hardware (in emulation). I just can't tell which it is...

**Comment by jkoritzinsky** [comment]
I think it's running on ARM64 then with only x64 .NET SDKs installed globally.

Not sure why this would fail only the installer tests now (all of our Mac legs run on the same type of hardware)

**Comment by agocke** [comment]
I'm happy to try this out locally and see if I can get more info

**Comment by vitek-karas** [comment]
The host has some code in it which detects arm64 hardware and changes behavior slightly based on that. So it actually does make a difference if it's running on arm64 or x64 hardware. And since the host tests do weird things with the host, I would not be surprised if this has an effect. Especially if the global install is 5.0 only which is not arm64 aware (which is BTW another problem with this setup) - after 6.0 GA we will also release an update to 5.0 which will be arm64 aware. In fact I think we will block installing 5.0 SDK on arm64 hardware (only runtime will be OK, but it installs into a different location), but I could be wrong.

Another problem will be that these images have .NET 2.1 SDK on them - those are out of support and are absolutely not supported on arm64 macs - we will have updated 3.1 and 5.0 installers, but AFAIK there are no plans to update the 2.1 installers. So trying to install the 2.1 on arm64 hardware will effectively break all .NET installs after the GA refresh.

@ericstj - just an FYI - the installer changes might play havoc with dotnet/runtime CI 😢

**Comment by jkoritzinsky** [comment]
@vitek-karas do the host tests take into account the global machine state including the globally installed SDKs? If so it might be prudent to disable some of these tests (or move them to staging) until we can figure out a solution as blocking RC2 and .NET 6 RTM sdk uptake is rough.

**Comment by agocke** [comment]
> do the host tests take into account the global machine state including the globally installed SDKs?

They shouldn't directly use that... but it's possible something leaked in...

**Comment by agocke** [comment]
FYI I do not think these machines are running on ARM64 hardware https://github.com/actions/virtual-environments/issues/2187

**Comment by agocke** [comment]
This PR fails on my x64 Mac with the following error:

```
[EXEC       >] [....] [00:14:37.908] /Users/angocke/code/runtime/artifacts/tests/Release/ha/nativeHosting/0/nativehost get_hostfxr_path false nullptr x
[EXEC       -] [....] [00:14:38.174] Waiting for process 87321 to exit...
get_hostfxr_path failed: 0x80008083
[EXEC       <] [FAIL] [00:14:38.343] > /Users/angocke/code/runtime/artifacts/tests/Release/ha/nativeHosting/0/nativehost get_hostfxr_path false nullptr x exited with 1
=== COMMAND LINE ===
```

**Comment by jkoritzinsky** [comment]
@agocke what macOS version do you have?

**Comment by vitek-karas** [comment]
The failure is obviously unexpected, but the exit code might be expected. Can you get the XML file from the tests - that will have much more detail about the failure.

**Comment by agocke** [comment]
Unfortunately, I don't see an XML file in the artifacts/TestResults/Release directory. Looks like it may have failed poorly

**Comment by jkoritzinsky** [comment]
@agocke can you try running `./dotnet test src/installer/tests/HostActivation.Tests/HostActivation.Tests.csproj -c Release -r artifacts/TestResults/Release --logger xml`? I think that should generate the test results file. Otherwise try using `--logger trx` instead of `--logger xml`. That should generate a test results file that VS can open.

**Comment by jkoritzinsky** [comment]
Okay I got a repro locally. The repro requires OSX 11.6 x64 for some reason.

There is one test failure and another failure that causes the test host to crash:

Test failure: MultilevelSharedFxLookup.SharedMultilevelFxLookup_Must_Not_RollForward_if_Framework_Version_is_Specified_Through_Argument.

The test host process crashes during this test: FrameworkResolution.MultipleHives.FrameworkHiveSelection_GlobalHiveWithBetterMatch.

**Comment by jkoritzinsky** [comment]
It looks like the failing tests are only supposed to run on Windows. Not sure why they're running at all...

**Comment by vitek-karas** [comment]
So I guess there's no local repro yet - right?

**Comment by jkoritzinsky** [comment]
I'm finishing up one now. Was waiting to post again until I have finalized results. I think I've narrowed it down to a particular portion of the test infra for the installer tests. Will share more once I've validated that I can get a clean build by disabling some of the tests.

**Comment by jkoritzinsky** [comment]
I've validated that I found the failures. The test crashes are all contained in the `Nethost.cs` file and are due to the infrastructure around the `install_location` config file. Something in the infrastructure for setting up the temporary file causes the test process to crash.

@vitek-karas @agocke to unblock this PR, can I open an issue for the failures and disable the tests on macOS against the new issue?

**Comment by agocke** [comment]
Fine with me

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
