### PR TITLE
Document DateOnly.AddDays exception

### PR DESCRIPTION
**Pull request by ploeh**

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]

**Comment by tarekgh** [comment]
@ploeh Thanks for helping with this issue. Are you interested to submit a doc PR too https://github.com/dotnet/dotnet-api-docs/blob/173aa811f0080f5573c370e43852c1c61bed18d0/xml/System/DateOnly.xml#L129?

**Comment by ploeh** [comment]
> @ploeh Thanks for helping with this issue. Are you interested to submit a doc PR too https://github.com/dotnet/dotnet-api-docs/blob/173aa811f0080f5573c370e43852c1c61bed18d0/xml/System/DateOnly.xml#L129?

I thought that document was auto-generated from the doc comments. It's not?

**Comment by tarekgh** [comment]
> I thought that document was auto-generated from the doc comments. It's not?

Not automatically. We still didn't enable automatic port of source to the doc repo. Currently we do it manually on demand. 

CC @carlossanlop

**Comment by ploeh** [comment]
> Not automatically. We still didn't enable automatic port of source to the doc repo. Currently we do it manually on demand.

That sounds painful. Done, though: https://github.com/dotnet/dotnet-api-docs/pull/9447

**Pull request merged**
