### PR TITLE
Workload changes - account for SDK bands and use archives

### PR DESCRIPTION
**Pull request by hoyosjs**

### CODE REVIEW

**Comment by joeloff** [comment]
I pushed the runtime/release/6.0 changes to this PR, but I believe we're going to need an Arcade update once https://github.com/dotnet/arcade/pull/10458 is ready

**Comment by hoyosjs** [comment]
LGTM. I can't approve my own PR though :)

**Comment by joeloff** [comment]
> LGTM. I can't approve my own PR though :)

LOL feels weird approving my commits too. Maybe we can get others on the discussion thread to help review

**Review by mmitche — APPROVED** [review]

**Comment by lewing** [comment]
`runtime (Libraries Test Run release coreclr Linux_musl x64 Debug) ` failure is https://github.com/dotnet/runtime/issues/73688

**Pull request merged**
