### PR TITLE
[browser] disable debugger tests on CI

### PR DESCRIPTION
**Pull request by pavelsavara**
disable browser debugger tests on CI

Related 
https://github.com/dotnet/runtime/issues/106376
https://github.com/dotnet/runtime/issues/98086
https://github.com/dotnet/runtime/issues/89909
https://github.com/dotnet/runtime/issues/89409
https://github.com/dotnet/runtime/issues/86496
https://github.com/dotnet/runtime/issues/52102

### CODE REVIEW

**Comment by lewing** [comment]
@thaystg what should we do here?

**Comment by pavelsavara** [comment]
Nobody attended them for months

**Comment by pavelsavara** [comment]
@thaystg do you ETA ?

**Review by lewing — APPROVED** [review]

**Pull request merged**
