### PR TITLE
Delete redundant aliases for primitive types

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by huoyaoyuan** [comment]
Does it make sense to replace more typedefs to stdint?
The `CLR_` prefix means managed data and should be kept. I searched and saw there's thousands of `ULONG`, >10k of `DWORD` and hundreds of `__int64`.

**Comment by jkotas** [comment]
> I searched and saw there's thousands of ULONG, >10k of DWORD and hundreds of __int64.

Replacing `__int64` and other `__int*` with `int64_t` and friends sounds reasonable to me.

Dealing with `DWORD` and `ULONG` is not as simple. The problem is that `DWORD` and `uint32_t` are two different types on Windows and so the following does not compile:
```
void f(DWORD* p) // Imagine that this is Win32 API that takes DWORD* argument
{
}

int main()
{
    uint32_t x;
    f(&x);
}
```
It means that a simple find&replace of DWORD with `uint32_t` is not possible. You would also need to add casts in number of places that is not an improvement. I think I would be ok with replacing `DWORD` with `uint32_t` in all places where it does not require adding casts. Same for `ULONG`.

**Comment by tannergooding** [comment]
> are two different types on Windows and so the following does not compile

It would be beneficial, at least long term I think, if Windows went through a small PAL as well and the PAL layer handled the `unsigned int <-> unsigned long` conversion that causes the difference between `uint32_t <-> DWORD`

That's more work overall of course, but I think it would make the codebase more approachable and easier to understand.

**Comment by jkotas** [comment]
The tentacles of DWORD and similar types go outside this repo. These types are used in the debugger and profiling interfaces, and cleaning this up would mean to do work in number of components outside this repo so that they can receive updates of these interfaces. It turns into large effort that is hard to justify. I expect that we are going to live with DWORDs and other windowsisms in some places forever. 

I believe that the best path to make the codebase more approachable is by shrinking the unmanaged code and CoreCLR PAL by rewriting it in C# and deleting dead code.

**Comment by huoyaoyuan** [comment]
The `int`/`long` incompatibility is really annoying. I just realized `DWORD` is typedef-d to long instead of int.

**Pull request merged**
