### PR TITLE
SPMI: Fix a couple of replay bugs

### PR DESCRIPTION
**Pull request by jakobbotsch**
With these two fixes we can cleanly replay libraries.pmi after recording, at least on win-x64.

## Avoid mutating constrained token in getCallInfo

For certain calls the EE would modify the constrained token passed to
getCallInfo. This token is an in-argument, and SPMI does not expect it
to be modified. Fix the EE to make a local copy when it needs to mutate
it.

## SPMI: Fix treatment of CORINFO_FLG_BAD_INLINEE during replay

- Save union of method attributes set by the JIT from
  recSetMethodAttribs calls
- Fix bit handling in repGetMethodAttribs
- Add the same method attribs handling to repGetCallInfo that
  repGetMethodAttribs has

This fixes an issue where we could have recorded an old result of
getCallInfo without CORINFO_FLG_DONT_INLINE set. If the JIT then calls
repSetMethodAttribs(CORINFO_FLG_BAD_INLINEE) this would not be reflected
in subsequent calls to getCallInfo, causing possible misses.

Contributes to #47540 and #47546.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/runtime/issues/47546

**Comment by BruceForstall** [comment]
> For certain calls the EE will modify the constrained token passed to getCallInfo.

That seems like a bad API. Should we change the EE to not change what should be "IN" arguments?

It points out that perhaps every JIT-EE method with a pointer argument should capture the "key" before the VM has an opportunity to munge the data pointed to.

You presumably want (or need) to change the JIT-EE GUID, to force a new collection.

**Comment by jakobbotsch** [comment]
> That seems like a bad API. Should we change the EE to not change what should be "IN" arguments?

Yeah, that would probably be a good idea. The code in question is the following:

https://github.com/dotnet/runtime/blob/d389ab955dbb65547643fa1aed52669b02c04294/src/coreclr/vm/jitinterface.cpp#L5102-L5125

We could refactor it by having `getCallInfo` on the EE side make a copy into a local when it needs to mutate it. Might also be that the code can be structured differently to avoid the copy, though I'm not sure I have the appetite to perform a larger refactoring.
It's not inconceivable that the JIT would rely on the values in the constrained token after this function returns, but currently we don't for the constrained token (whereas we do for the normal resolved token). So there is just the SPMI concern.

Of course there is a separate question of whether these parameters should be marked `const` then, but I guess that's a more general question of the JIT-EE interface that should be fixed more consistently if we want to change it. Today it seems like we purely rely on documentation for this detail.

Maybe @jkotas has an opinion? Does fixing the EE side to avoid the mutation here sound fine to you?

> You presumably want (or need) to change the JIT-EE GUID, to force a new collection.

I don't think it's necessary to update the JIT-EE GUID. These changes should be backwards/forwards compatible, so people can just pick up the new collections at their own leisure.

**Comment by jkotas** [comment]
>Maybe @jkotas has an opinion? Does fixing the EE side to avoid the mutation here sound fine to you?

Fixing the EE to avoid mutation by making a copy on this specific path sounds fine to me.

**Comment by jakobbotsch** [comment]
Thanks, I reverted the SPMI recording change and fixed this on the EE side. Also double checked that the managed equivalent doesn't do a similar mutation.

**Review by BruceForstall — APPROVED** [review]
LGTM.

I like the idea of adding more `const` annotations to the `in` arguments in the interface. That's obviously a separate work item.

**Pull request merged**
