### PR TITLE
In reset_memory, check settings.entry_memory_load ...

### PR DESCRIPTION
**Pull request by PeterSolMS**
in addition to g_low_memory_status - it looks like the latter is only set in response to low memory notifications from the OS - looks like this won't happen on Linux. This *may* also impact issue #52592 depending on actual memory load.

### CODE REVIEW

**Review by Maoni0 — CHANGES_REQUESTED** [review]
we should make a helper function for this as we now have a few places that do exactly this.

**Comment by PeterSolMS** [comment]
Makes sense - done.

**Review by Maoni0 — APPROVED** [review]
just a minor comment - I would add this as a static method in gc_heap next to all the dt_* methods since this is of the exact nature as those methods (ie, `dt_high_memory_load_p`)

**Pull request merged**
