### PR TITLE
Fix testhost build with different libraries and host configurations

### LINKED ISSUE #73777: testhost missing host files when building with different libraries and host configurations
### Description

To build on Linux Arm64 or X64 I use:
```
$ ./build.sh -rc checked -lc release
```

After building I would expect to see a fully populated testhost. Eg:
```
$ ls /home/alahay01/dotnet/runtime/artifacts/bin/testhost/net7.0-Linux-Release-arm64
dotnet  host/  shared/
```

Instead I just see a shared directory:
```
$ ls /home/alahay01/dotnet/runtime/artifacts/bin/testhost/net7.0-Linux-Release-arm64
shared/
```

Has something changed to stop the dotnet and host/ being generated?

### Reproduction Steps

On Linux:
```
$ ./build.sh -rc checked -lc release
```

### Expected behavior

artifacts/bin/testhost/net7.0-Linux-Release-arm64/ would contain a fully populated testhost, including dotnet and host/

Same with the X64 directory.

### Actual behavior

artifacts/bin/testhost/net7.0-Linux-Release-arm64/  contains only the shared/ contents. Same with the X64 directory.

### Regression?

This used to work for me.

### Known Workarounds

Don't know of any commands to force the missing pieces

### Configuration

Latest HEAD
ubuntu 18.04
Arm64 and X64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by elinor-fung**
- Separate host configuration from normal configuration
- Propagate host configuration to libraries so that the testhost build can find the correct host binaries
- Allow specifying host configuration in build script

Fixes https://github.com/dotnet/runtime/issues/73777

These two are equivalent and will result in a testhost layout with a checked runtime, release libraries, and debug host:
```
./build.sh clr+libs -rc checked -lc release
./build.sh clr+libs -rc checked -lc release -hc debug
```

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by ViktorHofer** [comment]
We were hoping that it's OK for the host to use the same configuration as the runtime. 
Do we need yet another component specific configuration set?

In the past we were using the prebuilt host packages which were release only.

**Comment by vitek-karas** [comment]
I think it would make sense to default the host to the same config as the runtime, unless explicitly overwritten.
I could also see us making it less of a first class thing - so maybe just an msbuild property or something like that.
But I would like to have the option to build Release runtime with Debug host. Host development actually involves running lot of managed code (all our tests are in C#), and running those on Debug runtime is really slow. So from my perspective, the change should fulfill two needs:
* Fix the problem that testhost is broken in some configs
* Maintain the ability to build Debug host and Release runtime (but not necessarily as a first class thing)

What is the exact mechanism for specifying the host config is not that important to me. I obviously like what Elinor did here, but if other's would like to have a more hidden setting, I think that's be fine as well.

**Comment by ViktorHofer** [comment]
My main concern with this change is that introducing more configurations per component introduces build complexity and without CI validation makes it prone to be broken. We already live with a difficult matrix as the CLR runtime has three configurations (Debug, Checked, Release) and mono has two (Debug, Release) and those need to paired with the libraries configurations (Debug, Release). If we would now also want to add CI protection for the different host configurations with the different runtime and libraries configurations then we would likely increase our machine quota noticeably.

@elinor-fung besides the general goodness of this change, is its intent to enable different host configurations just locally or do you also plan to add CI protection for it?

**Comment by elinor-fung** [comment]
The two needs Vitek called out are exactly what I had in mind.

It seemed more natural to me to have it completely separate rather than defaulting to the runtime config, We could certainly make it less of a first-class thing - basically remove the changes I made to the build scripts. I preferred it being an explicit option, as its omissions seems to have caused some confusion where people expect `rc` and `lc` to cover all binaries, so it is kind of weirdly an option by omission right now. (And I thought having it just made for a better dev experience.)

The different configurations already exist for the host today (and are combined with different runtime and libraries configurations), so the matrix is the same. Or are you only specifically talking about just creating the libraries testhost layout? I was not planning on changing the libraries test runs in CI to use a different host configuration, as I don't think that is particularly valuable validation.

**Comment by ViktorHofer** [comment]
> Or are you only specifically talking about just creating the libraries testhost layout?

Right, I was referring to the testhost which until recently always used Release bits (from the nuget package). If we don't plan to change and validate a different testhost host configuration in CI then most of my concerns can be ignored.

Don't get me wrong, I think this change is good. I just wanted to make sure that we don't unnecessarily add complexity to the already non trivial configuration build system.

**Comment by elinor-fung** [comment]
Okay, I am going to leave this as-is then (with no plans to add CI configurations).

**Comment by elinor-fung** [comment]
Failures are:
- https://github.com/dotnet/runtime/issues/74667
- https://github.com/dotnet/runtime/issues/74952

**Pull request merged**
