### PR TITLE
Implement PEM exports for RSA PKCS#1 and ECPrivateKey

### LINKED ISSUE #51630: APIs for exporting certificates and keys to PEM
## Background and Motivation

In .NET 5, additional APIs were added to make it easier to import public/private keys and certificates that are PEM formatted. Currently there is a lack of making it easier to export PEM formatted cryptographic thingies.

Today, if a developer wanted to do this, they would need to write something like:

```csharp
X509Certificate2 someCertificate;
string pemContents = new string(PemEncoding.Write("CERTIFICATE", someCertificate.RawData));
```

While this is just a little bit of code, it is fairly obtuse because it requires the developer to know what PEM label to use. For X.509 certificates it's somewhat straight forward. For keys, it isn't obvious to some if they would be using PRIVATE KEY, RSA PRIVATE KEY, ENCRYPTED PRIVATE KEY, etc.

See https://github.com/dotnet/runtime/issues/51597 for some additional context.

## Proposed API

```csharp
namespace System.Security.Cryptography
{
    public partial class AsymmetricAlgorithm
    {
        public string ExportPkcs8PrivateKeyPem();
        public bool TryExportPkcs8PrivateKeyPem(Span<char> buffer, out int charsWritten);

        public string ExportEncryptedPkcs8PrivateKeyPem(ReadOnlySpan<char> password, PbeParameters pbeParameters);
        public bool TryExportEncryptedPkcs8PrivateKeyPem(ReadOnlySpan<char> password, PbeParameters pbeParameters, Span<char> destination, out int charsWritten);

        public string ExportSubjectPublicKeyInfoPem();
        public bool TryExportSubjectPublicKeyInfoPem(Span<char> destination, out int charsWritten);
    }

    public partial class RSA
    {
        public string ExportRSAPrivateKeyPem();
        public string ExportRSAPublicKeyPem();

        public bool TryExportRSAPrivateKeyPem(Span<char> destination, out int charsWritten);
        public bool TryExportRSAPublicKeyPem(Span<char> destination, out int charsWritten);
    }

    public partial class ECDsa
    {
        public string ExportECPrivateKeyPem();
        public bool TryExportECPrivateKeyPem(Span<char> destination, out int charsWritten);
    }

    public partial class ECDiffieHellman
    {
        public string ExportECPrivateKeyPem();
        public bool TryExportECPrivateKeyPem(Span<char> destination, out int charsWritten);
    }

    // DSA does not have anything beyond what it gets from AsymmetricAlgorithm
}

namespace System.Security.Cryptography.X509Certificates
{
    public partial class X509Certificate2
    {
        public string ExportCertificatePem();
        public bool TryExportCertificatePem(Span<char> buffer, out int charsWritten);
    }

    public partial class X509Certificate2Collection
    {
        // Exports a PEM aggregate of all certificates
        public string ExportCertificatePems();
        public bool TryExportCertificatePems(Span<char> buffer, out int charsWritten);

        // Exports a single PKCS7 PEM of all certificates
        public string ExportPkcs7Pem();
        public bool TryExportPkcs7Pem(Span<char> buffer, out int charsWritten);
    }
}
```

## Usage Examples

```csharp
string certPem = someCert. ExportCertificatePem();
// do something with the PEM
```

## Alternative Designs

We do nothing and better document PEMs, labels, and using `PemEncoding`.

## Risks

Not aware of any.

### PR DESCRIPTION
**Pull request by vcsjones**
Closes #51630.

### CODE REVIEW

**Comment by vcsjones** [comment]
@bartonjs this is all in S.S.C.Algorithms. I'm not sure if you are in the middle of moving that down in to the new S.S.Cryptography assembly. If you have that in-flight, it's probably easier for me to rebase on that work than for this to get merged and you rebase on top of. that. If that is the case, please feel free to hold this PR until that's complete and I'll respond to the things moving around.

**Comment by bartonjs** [comment]
> I'm not sure if you are in the middle of moving that down in to the new S.S.Cryptography assembly.

Yep, have it all merged in locally, except Browser.

> If that is the case, please feel free to hold this PR until that's complete

OK, I'll go ahead and mark this as no-merge.  It should be actionable late-this or early-next week.

**Comment by bartonjs** [comment]
The code LGTM, just needs to be rebased on a future commit :)

**Comment by vcsjones** [comment]
Since https://github.com/dotnet/runtime/issues/61516 changed some of the APIs here, I am going to close this PR and re-open it after that PR is complete.

**Pull request closed without merging**
