### PR TITLE
ILLink: Fix event warning locations

### LINKED ISSUE #100499: Warning origins for warnings originating from event accessors are very confusing
Currently `MarkEvent` will directly call `MarkMethod(add_event)` and `MarkMethod(remove_Event)` with the origin set to the event itself. So for example:

```C#
// IL2026 - about the add_event
public event EventHandler TestEvent {
    [RequiresUnreferencedCode()]
    add {}
}
```

The warning is reported on the event itself and not on the callsite actually accessing the event. It's also reported repeatedly (if there are multiple callsites).

This gets potentially even worse because `ProcessEvent(add_event)` will call `MarkEvent(event)` and so that will potentially trigger the warning multiple times on its own.

RUC on type makes this even worse since both accessors are automatically RUC and this loops on itself (I think I saw the warning triplicated and on the wrong place).

### PR DESCRIPTION
**Pull request by jtschuster**
Fixes https://github.com/dotnet/runtime/issues/100499

Moves the marking of the associated event of an event method to `MarkMethod` rather than ProcessMethod, and changes the event marking reason and MessageOrigin to be the reason and origin from `MarkMethod` of the event method. To avoid infinite recursion, we will always give the reason `EventMethod` when calling `MarkMethod` from `MarkEvent` and will not call `MarkEvent` again from `MarkMethod` when the reason is `EventMethod`.

Annotations also should not be processed during the call to `MarkMethod` that originated from `MarkEvent`, so `EventMethod` is added to the exclusion cases for `ProcessAnalysisAnnotationsForMethod`. `MarkEventVisibleToReflection` will mark events and each event method with the reason `DynamicallyAccessedMember` which will lead to warnings on RUC accessors. Also, anything that references `add` or `remove` directly will directly call `MarkMethod` with a different reason than `EventMethod` and warnings will be generated. A side effect of this is that if `remove` has RUC but is never accessed, but `add` is accessed, then `remove` will be kept for valid IL but no warning will be emitted. This should be fine since the program shouldn't be able to call the `remove` method.

### CODE REVIEW

**Review by sbomer — COMMENTED** [review]
Did you consider either:
- reporting warnings about add/remove/invoke methods at the location that accesses the event method, or
- (preferably) avoid marking unused add/remove/invoke methods?

Trimming the unused event methods would be the cleanest option, but unfortunately I'm not sure it's legal - I found this in ECMA-335:

> There are two required methods (add_ and remove_) plus an optional one (raise_);
additonal methods with other names are also permitted (§18)

@MichalStrehovsky for opinions.

**Comment by jtschuster** [comment]
> * (preferably) avoid marking unused add/remove/invoke methods?

Like you mentioned, my understanding is that's not allowed by the ECMA spec. We could avoid marking them and stub out unmarked `add` and `remove` methods on marked events.

> * reporting warnings about add/remove/invoke methods at the location that accesses the event method

That's another option, but I think it might be a bit confusing to get a warning for `remove` when the code calls `add`. I'm okay doing that if we thinks it's a better option.

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky for opinions.

Yeah, that looks illegal per ECMA spec although it doesn't look like the spec is consistent about this requirement in other places.

Events are similar to properties - the runtime doesn't really care about them - they're a tooling/reflection concern only.

Another option could be to just stop doing the special behavior that looks for an event when an accessor is marked and let the event itself be trimmed. Only keep events that are visible targets of reflection (in that case consider the accessors reflection accessed as well).

I think there is an issue somewhere to do the same thing with properties. It's a bit more tricky for properties because debugger looks at them (we could only trim property metadata with DebuggerSupport=false), but events aren't surfaced in the debugger (and I don't see a future where they could be surfaced based on how event metadata works) so this shouldn't really affect debuggability and we can do it always.

**Review by sbomer — APPROVED** [review]
Thanks! I'd like us to try allowing trimming of events as @MichalStrehovsky suggested, but the current change also LGTM.

edit: tracking in https://github.com/dotnet/runtime/issues/102576

**Pull request merged**
