### PR TITLE
[LoongArch64] Enable the "TC_QuickJitForLoops" on LoongArch64.

### PR DESCRIPTION
**Pull request by LuckyXu-HF**
This PR is part of the issue #69705 to amend the LA's port.

Enable the "TC_QuickJitForLoops" on LoongArch64.

### CODE REVIEW

**Comment by HFDude** [comment]
Hi, @shushanhf   @jakobbotsch 
We have tests this PR, and it's ok on LoongArch64.
Could you please review this PR?
Thanks

**Comment by shushanhf** [comment]
> Enabling QJFL without OSR risks methods with loops in them getting stuck in slow unoptimized code since tiering only kicks in at method call boundaries.

Thanks very much.

**Comment by HFDude** [comment]
> I would advise against enabling quick-jit for loops without corresponding support for [on-stack replacement](https://github.com/dotnet/runtime/blob/main/docs/design/features/OnStackReplacement.md). x64 and arm64 support on-stack replacement which is why they also enable quick-jit for loops.
> 
> Enabling QJFL without OSR risks methods with loops in them getting stuck in slow unoptimized code since tiering only kicks in at method call boundaries.

Thank you very much，we will open the feature OSR and test again.

**Comment by shushanhf** [comment]
The OSR for LA64 is just for optimization and we will do it later.

**Comment by jakobbotsch** [comment]
> The OSR for LA64 is just for optimization and we will do it later.

Then we should keep `TC_QuickJitForLoops` with its current default value.

**Comment by shushanhf** [comment]
> > The OSR for LA64 is just for optimization and we will do it later.
> 
> Then we should keep `TC_QuickJitForLoops` with its current default value.

Yes, we will still develop it but not so urgent.
We will fix some errors fisrt to make sure the .NET8 released on LA64, the performance is the next step.

**Comment by HFDude** [comment]
> > > The OSR for LA64 is just for optimization and we will do it later.
> > 
> > 
> > Then we should keep `TC_QuickJitForLoops` with its current default value.
> 
> Yes, we will still develop it but not so urgent. We will fix some errors fisrt to make sure the .NET8 released on LA64, the performance is the next step.

And we found that opening the `TC_QuickJitForLoops` may mask some bugs on LA64, so maybe it would be better to do fully test and fix the bugs before opening `OSR` and `TC_QuickJitForLoops` on LA64.

**Comment by jakobbotsch** [comment]
Sounds good @shushanhf. In that case can we close this PR until OSR is working?

**Comment by shushanhf** [comment]
> Sounds good @shushanhf. In that case can we close this PR until OSR is working?

OK, We will close this PR.
Thanks

**Pull request closed without merging**
