### PR TITLE
Extract SuperPMI into a separate component

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Allows building the runtime without SPMI.

`build.cmd clr` will still build SPMI.
`build.cmd clr.native` will still build SPMI.
`build.cmd clr.runtime` will no longer build SPMI.

This is mostly motivated by NativeAOT subset builds where SPMI contributes to 10% of the native build time (nativeaot CorecLR subset builds pretty quickly compared to full CoreCLR).

Cc @dotnet/jit-contrib

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
You might need/want to update the `build-jit-job.yml` template to build this new component explicitly to make sure we don't break the JIT team's outerloop jobs.

**Comment by BruceForstall** [comment]
So, after this, you will build superpmi with:
```
build.cmd clr.spmi
```

or with src\coreclr\build-runtime.cmd with:
```
build-runtime.cmd -component spmi
```

This seems reasonable.

I presume the changes automatically add it to `build -subset help` output?

It looks like eng\pipelines\coreclr\templates\build-job.yml has:
```
 - name: clrRuntimeComponentsBuildArg                                                                
  value: ''                                                                                         
- ${{ if ne(parameters.testGroup, 'innerloop') }}:                                                  
  - name: clrRuntimeComponentsBuildArg                                                              
    value: '-component runtime -component alljits -component paltests '                             
- ${{ if and(eq(parameters.osGroup, 'Linux'), eq(parameters.archType, 'x86')) }}:                   
  - name: clrRuntimeComponentsBuildArg                                                              
    value: '-component runtime -component jit -component iltools '                                  
```
so I would expect you would need to add `-component spmi` to those lines for the spmi unit test to run on Linux.

I agree with @jkoritzinsky that you'll need to change the two 'build' lines in eng\pipelines\coreclr\templates\build-jit-job.yml to add `-component spmi` after the existing `-component alljits`.

**Review by BruceForstall — CHANGES_REQUESTED** [review]
See previous comment

**Comment by MichalStrehovsky** [comment]
> I presume the changes automatically add it to build -subset help output?

Yup, the help text is part of the pull request.

I've update the places in the yaml files to also build SuperPMI.

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
