### PR TITLE
Run runtime tests marked as JitOptimizationSensitive on Mono.

### PR DESCRIPTION
**Pull request by lateralusX**
Several EventPipe tests marked as JitOptimizationSensitive and are currently skipped on Mono CI. PR enables no_tiered_compilation when running CI test runs on Mono to make sure these tests gets executed as well.

### CODE REVIEW

**Comment by lateralusX** [comment]
Seems to do the trick, EventPipe tests running including a new JIT test that also fails. Fix for at least one failed EventPipe tests is already included in https://github.com/dotnet/runtime/pull/58099, so once that gets merge this PR can be rerun. Need to investigate why new JIT tests previously not run on Mono fails and if we should disable it as part of this PR.

**Comment by lateralusX** [comment]
Introducing error in EventPipe to make sure we see test failures on CI.

**Comment by lateralusX** [comment]
Observed expected failures in EventPipe tests, proving that tests are running as part of CI with changes in this PR.

**Comment by lateralusX** [comment]
Reverted EventPipe error used to test CI failures in EventPipe tests.

**Comment by lateralusX** [comment]
@SamMonoRT, FYI, makes sure we run runtime tests marked as JIT sensitive on CI. Couple of EventPipe tests was not run on platforms we expected them to run, not capturing a regression fixed in CoreCLR.

**Review by naricc — APPROVED** [review]

**Pull request merged**
