### PR TITLE
[browser][debugger] fake bind_static_method

### PR DESCRIPTION
**Pull request by pavelsavara**
get rid of legacy JS interop in unit tests, so that we can https://github.com/dotnet/runtime/pull/96841
this implements 
- fake `bind_static_method` via `[JSExport]` and C# reflection (this always catches managed exceptions and marshals it)
- `bind_static_method_native` which uses `mono_wasm_invoke_method_raw`, this let's exceptions unhandled, same way as legacy interop.

### CODE REVIEW

**Review by thaystg — APPROVED** [review]

**Comment by pavelsavara** [comment]
image
image

The MT debugger test fail is known https://github.com/dotnet/runtime/issues/89409, the actual tests passed [Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-96899-merge-9235d694bf1c496bab/chrome-DebuggerTests.EvaluateOnCallFrame2Tests/1/console.6f516db1.log?helixlogtype=result)

**Pull request merged**
