### PR TITLE
Adding unit test to provoke exception using Sch_WhiteSpaceRestriction…

### LINKED ISSUE #30218: Xml resources have invalid formatter
i.e. https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/Resources/Strings.resx#L1722

`{facets}` instead of i.e. `{0}`. This is likely causing some random exceptions to some people

### PR DESCRIPTION
**Pull request by mrj001**
@buyaa-n 
Per your suggestion in PR#33890, I'm using a second pull request.

This contains my attempt to provoke the exception using Sch_WhiteSpaceRestriction1 as its message.  However, it is provoking a different exception:
image

I suspect this is a bug, as the XSD I'm trying to compile differs from the example in [Paragraph 4.3.6](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/datatypes.html#rf-whiteSpace) only in the name of the type and the presence of the namespace qualifier. (I'm pretty sure I've got the correct version of the spec now. :-))

The active test case is attempting to determine what was going wrong.  The commented out test case is the one to actually try to provoked the exception.

Fixes  #30218:

### CODE REVIEW

**Comment by mrj001** [comment]
@buyaa-n 
I was not happy with my suspicion of a bug, so I kept looking at it.
I found my problem with the schema in the PR - I had a lower-case "s"  in "whiteSpace".  That was so hard to see, but now the error message makes sense.

**Comment by buyaa-n** [comment]
> I was not happy with my suspicion of a bug, so I kept looking at it.
> I found my problem with the schema in the PR - I had a lower-case "s" in "whiteSpace". That was so hard to see, but now the error message makes sense.

That happens 😄, glad that you found it, thank you for your continuous effort. seems now you need to fix the tests and resolve conflict

**Comment by mrj001** [comment]
@buyaa-n 
Tests are fixed.  Conflict is resolved.

This PR now covers the final 3 of the 13 string resources in Issue #30218:

- Sch_WhiteSpaceRestriction1
- Sch_WhiteSpaceRestriction
- Sch_AttributeRestrictionInvalidFromWildcard

**Review by buyaa-n — APPROVED** [review]
Thank you @mrj001, it looks great, sorry for the delayed review

**Comment by buyaa-n** [comment]
> This PR now covers the final 3 of the 13 string resources in Issue #30218:

Great, then we should add fixes #30218 in the definition, so that it get closed automatically after merge

**Comment by krwq** [comment]
Thanks @mrj001!

**Pull request merged**
