### PR TITLE
[tasks] Rename MonoAOTCompiler AotInterp option to LLVMOnlyInterp; add FullInterp

### PR DESCRIPTION
**Pull request by lambdageek**
The 'LLVMOnlyInterp' options means: use the LLVM AOT backend, and generate the necessary code to allow the runtime to fall back to the interpreter if AOT compilation is not supported for some methods.

The 'FullInterp' options means: use the native mini AOT backend, and generate the necessary code to allow the runtime to fall back to the interpreter if AOT compilation is not supported for some methods.

LLVMOnlyInterp is currently used by WebAssembly AOT.

FullInterp may be used by iOS AOT.

### CODE REVIEW

**Comment by lambdageek** [comment]
We don't use 'FullInterp' for anything right now, but we could use it for device testing (or fullaot on simulator, if we wanted) of the Xamarin.iOS "AOT with interpreter fallback" support.

(`LLVMOnlyInterp` maps to `MONO_AOT_MODE_LLVMONLY_INTERP` and `FullInterp` is `MONO_AOT_MODE_INTERP` in the runtime)

**Comment by lewing** [comment]
Which platforms support all of the options? Is this something we should expose directly as a non _prefixed property?

**Review by lewing — COMMENTED** [review]
I don't have strong objections but please wait for https://github.com/dotnet/sdk/pull/17092 before landing this.

**Comment by lewing** [comment]
cc @jeromelaban

**Comment by lambdageek** [comment]
> Which platforms support all of the options?

I don't think there's a single platform that supports everything.  (or maybe something like tvOSSimulator where you could probably choose to use the JIT, or mini or LLVM AOT, with or without interpreter as a fallback).

> Is this something we should expose directly as a non _prefixed property?

I don't think so.  1. The `MONO_AOT_MODE_*` constants in the runtime embedding API are a confusing mess. 2. The `--aot=[opts]` AOT compiler options don't map onto them exactly and give a different matrix of configurations - not all of which are sensible, and they don't really give you a good idea of what behavior you chose.

It would be better to have some frontend property that lets you pick the behavior you want and then errors out if you pick something unsupported: 
* Primary execution mode: JIT, AOT, interpreter
* Fallback execution mode: JIT, interpreter, none
* (optional) AOT backend: LLVM or mini 

Not every combination of primary/fallback is sensible; not every combination of primary/fallback is supported on every workload; not every AOT backend is supported on every platform - and for most workloads there's probably one reasonable default.
(And I probably missed some execution mode that doesn't fit this pattern).

But at least it expresses intent, rather than our odd choice of constants from some header file.

**Comment by steveisok** [comment]
@akoeplinger @directhex Please give this a review

**Review by directhex — APPROVED** [review]

**Pull request merged**
