### PR TITLE
Add Azure 3.0 helix test

### PR DESCRIPTION
**Pull request by richlander**

### CODE REVIEW

**Comment by richlander** [comment]
Is this change even getting triggered by this PR run? I'm guessing not?

It is the same place as the existing Mariner image.

https://github.com/dotnet/runtime/blob/8e0927fa84fc698fa7c62c9bde3176aacb06fd8f/eng/pipelines/libraries/helix-queues-setup.yml#L64-L70

If not, how do I trigger the outer loop? Is this the right place for Azure Linux validation going forward?

**Comment by jkotas** [comment]
> Is this change even getting triggered by this PR run? I'm guessing not? 

Correct. The new config is in the extra platforms section that is not triggered by default on PRs.

**Comment by richlander** [comment]
It isn't obvious to me that this worked. I searched for "azurelinux" on this page (where other helix images are listed) and see no hits.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=774725&view=logs&j=df56ac33-e9fe-5eb2-5cdb-3303d7aad000&t=f62247f8-d051-5cb6-d5f0-06f532f9a005

@sbomer was suggesting that `runtime-extra-platforms` might be the correct choice. Was that right Sven?

**Comment by richlander** [comment]
That appears to have worked. Thanks! Now have to sort through the failures.

**Comment by richlander** [comment]
```bash
/root/helix/work/workitem/e /root/helix/work/workitem/e
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 4 of 152 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on [2 threads], stop on fail = off)
MsQuic not supported and using 'unknown'.
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicPlatformDetectionTests.cs(51,0): at System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatformsWithMsQuic_IsSupportedIsTrue()
        --- End of stack trace from previous location ---
      Output:
        /usr/lib/libmsquic.so.2
        /usr/lib/libmsquic.so
        /usr/lib/libmsquic.so.2.4.3
```

We added libmsquic to the image. Does it need to learn about Azure Linux? I'm looking at `using 'unknown'.`.

@liveans @wfurt

**Comment by liveans** [comment]
> We added libmsquic to the image. Does it need to learn about Azure Linux? I'm looking at `using 'unknown'.`.
> 
> @liveans @wfurt

I'll take a look what's wrong, might be missing dependency.

**Comment by wfurt** [comment]
```
helixbot [ / ]$ ldd /usr/lib/libmsquic.so.2.4.3
	linux-vdso.so.1 (0x00007ffc131ef000)
	libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007f3f60061000)
	libatomic.so.1 => not found
	libnuma.so.1 => not found
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f3f5fe1e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3f606ba000)
```

**Comment by liveans** [comment]
image
It is indeed missing dependency.

After installing `libnuma1`, `libatomic1` should work.

/cc @richlander

**Comment by wfurt** [comment]
we should update the pattern in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/ to verify that produced library at least loads. With that, one could find issues _before_ going all the way to runtime.

**Comment by liveans** [comment]
> we should update the pattern in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/ to verify that produced library at least loads. With that, one could find issues _before_ going all the way to runtime.

We can actually run `msquictest --gtest_filter=ParameterValidation.ValidateApi`, that's something `msquic` itself using on Packaging pipeline to verify package is loading or not.

**Comment by jkotas** [comment]
We can do all that, but I think we are missing the user point of view.

If our users want to use msquic on Azure Linux, how are they expected to get it? Are they expected to build their own like what we are doing in dotnet-buildtools-prereqs-docker? Should it be documented somewhere?

**Comment by richlander** [comment]
FYI: https://github.com/microsoft/msquic/issues/4450

**Comment by liveans** [comment]
> We can do all that, but I think we are missing the user point of view.
> 
> If our users want to use msquic on Azure Linux, how are they expected to get it? Are they expected to build their own like what we are doing in dotnet-buildtools-prereqs-docker? Should it be documented somewhere?

msquic is working on it: https://github.com/microsoft/msquic/pull/4455

**Comment by jkotas** [comment]
> msquic team is working on it: https://github.com/microsoft/msquic/pull/4455, they are going to publish packages soon.

Should we just wait for the proper msquic package to get published?

If we cannot wait, we should make sure to revert https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1177 workaround once the proper package is available.

**Comment by richlander** [comment]
We can wait.

**Comment by liveans** [comment]
I just confirmed it with msquic team and they're going to publish these packages with next release, so might not be soon, sorry for the confusion on the last comment.

**Comment by wfurt** [comment]
> We can do all that, but I think we are missing the user point of view.
> 
> If our users want to use msquic on Azure Linux, how are they expected to get it? Are they expected to build their own like what we are doing in dotnet-buildtools-prereqs-docker? Should it be documented somewhere?
```
rpm -i https://packages.microsoft.com/fedora/39/prod/Packages/l/libmsquic-2.4.3-1.x86_64.rpm
```
not as elegant as own repo but it works just fine. (one can also subscribe to the feed and use package manager)

**Comment by richlander** [comment]
I'll wait until the proper package has been uploaded. I'm in no rush since we need to get the OpenSSL issues resolved.

**Comment by richlander** [comment]
@bartonjs investigated the crypto issue. He believes that the failures are due to the following patch.

https://github.com/microsoft/azurelinux/blob/3.0/SPECS/openssl/0006-Disable-signature-verification-with-totally-unsafe-h.patch

Guidance on what to do next:

The easiest thing that I see, is make sure the OPENSSL_ENABLE_MD5_VERIFY environment variable is set before tests are run.  Doesn't seem to care what the value is, so perhaps "1".

I don't know how to set an ENV for a specific helix run, assuming that's possible. For the long-term, we'll want to make the tests more resilient to this case. I'll file an issue on that.

**Comment by richlander** [comment]
Just did another run, after the new image was published with the ENV set. Still lots of failures.

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-106330-merge-16cef0720ce24161a1/System.Security.Cryptography.Tests/1/console.36e988c7.log?helixlogtype=result

I pulled the image before kicking off a new run.

```bash
$ docker run --rm  mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-helix-amd64 bash -c "export | grep OPENSSL"
declare -x OPENSSL_ENABLE_MD5_VERIFY="1"
```

**Comment by vcsjones** [comment]
> Per my read, the msquic failures were resolved by installing the correct dependencies. So, that's good.
> 
> @vcsjones

I have Azure Linux running locally so I can iterate on the tests now. I have a general plan and strategy here, but it's a considerable amount of changes to tests.

**Comment by richlander** [comment]
FYI: There is ongoing progress being made to resolve that, just not visible here. We'll come back to this PR shortly.

Required fixes:

- https://github.com/microsoft/azurelinux/pull/10156 
- https://github.com/microsoft/SymCrypt-OpenSSL/pull/86

**Comment by richlander** [comment]
All the fixes are now in and @vcjones has done (successful) private testing, preceded by a deep investigation. Thanks much!!

There should be a new Azure Linux 3.0 build early next week (with the `SymCrypt-OpenSSL` fixes. The [helix image](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/) may take another 24 hours to re-build after that and then we can kickoff a new run.

Once I know that a new base image is available, I look here to see when the helix image has been published: https://github.com/dotnet/versions/commits/main/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-main.json.

**Comment by richlander** [comment]
Looks like the fixes have flowed to our images.

```bash
rich@mazama:~$ docker pull mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-helix-amd64
azurelinux-3.0-helix-amd64: Pulling from dotnet-buildtools/prereqs
rich@mazama:~$ docker run --rm -it mcr.microsoft.com/dotnet-buildtools/prereqs:azurelinux-3.0-helix-amd64
helixbot [ / ]$ tdnf list --installed symcrypt*
SymCrypt.x86_64                              103.4.2-1.azl3            @System
SymCrypt-OpenSSL.x86_64                      1.5.1-1.azl3              @System
helixbot [ / ]$ 
```

**Comment by vcsjones** [comment]
Looks like test artifacts are failing to publish, but looking at the raw logs from System.Security.Cryptography, the output is promising.

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-106330-merge-12fcefff9a154ce5ae/System.Security.Cryptography.Tests/1/console.a7858ece.log?helixlogtype=result

> === TEST EXECUTION SUMMARY ===
   System.Security.Cryptography.Tests  Total: 9776, Errors: 0, Failed: 0, Skipped: 310, Time: 106.457s

**Comment by vcsjones** [comment]
Hm, that may be the wrong breadcrumb of test results. I don't see them for AZL.

**Comment by richlander** [comment]
Thoughts @carlossanlop?

**Comment by carlossanlop** [comment]
There was a helix outage reported for most of the day today. I think a retry from scratch should work. Let's close and reopen this, and execute runtime-extra-platforms once again.

**Comment by richlander** [comment]
Looks like Azure Linux is coming out clean (except the System.IO.Tests). Is that your read @vcsjones?

**Comment by bartonjs** [comment]
https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-106330-merge-e655bc6eb742442c9c/System.Security.Cryptography.Pkcs.Tests/1/console.c243fbb9.log?helixlogtype=result

Looks like there's still a test in the S.S.C.Pkcs library using RSA+MD5:

https://github.com/dotnet/runtime/blob/063ae05c63307becef004eefbc8704ccb03c7f04/src/libraries/System.Security.Cryptography.Pkcs/tests/Pkcs12/KeyBagTests.cs#L29-L42

**Comment by richlander** [comment]
That looks clean now. Yes?

**Comment by vcsjones** [comment]
> That looks clean now. Yes?

Yes. All the linux legs look green to me. The only failures I see are Apple iOS / tvOS / Catalyst which are unrelated.

**Comment by richlander** [comment]
Sounds good. We just need an approval now. We can then decide how to approach `release/8.0-staging`. The current plan is to not offer Azure Linux 3.0 support for .NET 6.

**Comment by vcsjones** [comment]
> We can then decide how to approach release/8.0-staging.

We also need to backport to `release/9.0`.

1. `release/9.0` has one more pending backport for a green crypto test run.  https://github.com/dotnet/runtime/pull/107061
2. `release/8.0-staging` has a backport PR of all fixes rolled up ready to go. https://github.com/dotnet/runtime/pull/107061

**Comment by vcsjones** [comment]
> Would you consider adding the pipeline change to those PRs so that you can run the `runtime-extra-platforms` pipeline just before merging (and then we're done?).
> 
> https://github.com/dotnet/runtime/pull/106330/files#diff-cbc8f55c9e8b4fc53ff194be8f6e99b461bbb888220a8ede2e5edb53b947b287R71

I cherry picked this PR onto those backport PRs and kicked off a run.

**Comment by richlander** [comment]
Can you offer us an approval @bartonjs?

**Review by bartonjs — APPROVED** [review]

**Comment by richlander** [comment]
Thanks @bartonjs and @vcsjones. Much appreciated. That was all quite unexpected.

**Pull request merged**
