### PR TITLE
Fix variables names in perf automation

### PR DESCRIPTION
**Pull request by billwert**

### CODE REVIEW

**Comment by billwert** [comment]
@jeffschwMSFT This won't touch any of the CI tests that run. Please approve.

**Review by DrewScoggins — APPROVED** [review]
LGTM

**Comment by jeffschwMSFT** [comment]
In what pipeline are these yaml files used?

**Review by jeffschwMSFT — APPROVED** [review]
Approved.

**Comment by billwert** [comment]
> In what pipeline are these yaml files used?

`dotnet-runtime-perf` and `dotnet-runtime-perf-slow`.

**Pull request merged**
