### PR TITLE
[release/6.0] Fix Logging Source Generator to handle file-scoped namespaces (#57894)

### PR DESCRIPTION
**Pull request by maryamariyan**
#### PR Content
Cherry pick of PR https://github.com/dotnet/runtime/pull/57894
Relates to #57880.

The feedback expressed in https://github.com/dotnet/runtime/pull/57894#issuecomment-918247048 improves the fix in main branch but we have as-is should be sufficient for release branch.

#### Customer Impact

Logging Source Generator fails to compile due to CS8795 error with file-scoped namespaces.
The fix will handle usages of file-scoped namespaces for logging method.

#### Testing
Included in PR

#### Risk
Low, since file-scoped namespace is a C#10 feature (check [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces)) and the logging source generator is a 6.0 feature and this fix is concerned with these two new features used in combination. 

/cc @danmoseley for M2 approval

### CODE REVIEW

**Review by ericstj — APPROVED** [review]

**Comment by danmoseley** [comment]
As noted offline please take the time to do the right fix (you mentioned possibly making more changes)

this will also need a template filled out.

**Comment by maryamariyan** [comment]
@danmoseley updated with template in description

**Comment by danmoseley** [comment]
@maryamariyan there are real build breaks here. could you please take a look?

**Comment by ericstj** [comment]
Right these changes are because @eerhardt made changes later in his source generator refactoring but didn't include those when ported to release/6.0.  Order in main was M > E, order in release is E > M.  @maryamariyan mentioned she was going to port the part of @eerhardt's change that was missed.

**Review by ericstj — APPROVED** [review]

**Pull request merged**
