### PR TITLE
Make sure to check for isUsedFromSpillTemp() before optimizing float comparison in code gen

### LINKED ISSUE #78298: Test failure System.Numerics.Tests.ComplexTests.Reciprocal(real: 0, imaginary: -1)
Run: [runtime-coreclr libraries-jitstressregs 20221113.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=81846&view=ms.vss-test-web.build-test-results-tab&runId=1707838&resultId=148862&paneView=debug)

Failed test:
```
net7.0-Linux-Release-x64-CoreCLR_checked-jitstressregs3-Ubuntu.1804.Amd64.Open

- System.Numerics.Tests.ComplexTests.Reciprocal(real: 0, imaginary: -1)
- System.Numerics.Tests.ComplexTests.Reciprocal(real: 0, imaginary: 1)
- System.Numerics.Tests.ComplexTests.Reciprocal(real: 0, imaginary: -1.7976931348623157E+308)
- System.Numerics.Tests.ComplexTests.Reciprocal(real: 0, imaginary: 1.7976931348623157E+308)
```
**Error message:**
```
Failure at line 1325. Expected imaginary: 0. Actual imaginary: 1
Expected: True
Actual:   False


Stack trace
   at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber) in /_/src/libraries/System.Runtime.Numerics/tests/ComplexTests.cs:line 2007
   at System.Numerics.Tests.ComplexTests.Reciprocal(Double real, Double imaginary) in /_/src/libraries/System.Runtime.Numerics/tests/ComplexTests.cs:line 1321
   at InvokeStub_ComplexTests.Reciprocal(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### PR DESCRIPTION
**Pull request by kunalspathak**
When optimizing the float comparison `x != x`, we just check if the registers assigned to both the operands of `!=` are same or not , and if yes, assume that we want to check for NaN. However, one of the operand could not be live in register but is fetched from memory during the comparison. In such case, we should prohibit doing such optimization. Added the check for `isUsedFromSpillTemp()` in addition to the `RegNum()` check. 

I will do an audit of other places where this could be missing and send out a separate PR:
- Either when we do `GetRegNum()` and if there is a valid register, we should check that it is not `isUsedFromSpillTemp()`.
- When we set `GTF_NOREG_AT_USE`, also set the regnum to `REG_NA`.

More context: https://github.com/dotnet/runtime/issues/78298#issuecomment-1317426565

Fixes: https://github.com/dotnet/runtime/issues/78298

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Review by tannergooding — APPROVED** [review]
I think having `GetRegNum` set to `REG_NA` for such scenarios is good.

Having anything else be returned but the data being invalid/stale is misleading and leads to subtle bugs like this.

**Comment by SingleAccretion** [comment]
It's not necessarily misleading for `GetRegNum` to be not-`NA` for "use from spill", if we consider it as the "def" register (or register produced by the node). It is of course not useful for the "use" cases, which are more prevalent. We could introduce a `GetUseRegNum` which would look like `return isUsedFromSillTemp() ? REG_NA : GetRegNum()` (we use this pattern or its equivalent `isUsedFromReg() ? GetRegNum() : REG_NA` in a few places already).

**Comment by kunalspathak** [comment]
> `isUsedFromReg() ? GetRegNum() : REG_NA` in a few places already

I think that would a better check actually because it checks for `both !contained and !isUsedFromSillTemp`.

**Comment by tannergooding** [comment]
That's where I think its misleading.

The main use case for the register number in codegen is to know which register needs to be emitted and other bits like to know if some move is required for RMW, etc. Having to query extra information for the common case is then undesirable and hurts throughput. 

In this scenario, the CNS_DBL effectively has stale data of the register it was in before the assignment. And in any other case its specifying data that is not useful for codegen because some other node has (or may have) been assigned that register.

-- The fact we're spilling `0` is another and separate issue. It's constant and we can avoid spilling these entirely by just emitting a method local constant. We should only need to spill non-constant data.

**Comment by jakobbotsch** [comment]
> It's not necessarily misleading for `GetRegNum` to be not-`NA` for "use from spill", if we consider it as the "def" register (or register produced by the node). It is of course not useful for the "use" cases, which are more prevalent.

For my education, what particular case do you have in mind here?

To me the combination of `GTF_SPILLED` and a register being set should mean that codegen is ok to reload into that assigned register and use it. But now I've learned that if we additionally have `GTF_NOREG_AT_USE` then the meaning changes to "used from spill temp", but I don't understand why LSRA leaves the register assignment set. It would be incorrect to define the register that is left there as this case shows.

**Comment by SingleAccretion** [comment]
> I don't understand why LSRA leaves the register assignment set

It would be the the destination/def/result register.

I don't know the reason why we wouldn't be able to set the register to `NA` in `genProduceReg` instead of having the flag (with "use from spill temp" <-> `SPILLED` + `GetRegNum` == `NA`).

**Comment by jakobbotsch** [comment]
> It would be the the destination/def/result register.

I don't understand this, the case is a local and actually defining that register where it appears in LIR would be incorrect due to the overlapping lifetime with the other operand.

**Comment by SingleAccretion** [comment]
> the case is a local

Locals don't use `GTF_NOREG_AT_USE` though, only true SDSUs do. Are you saying in this bug we have a local marked as such? That's unexpected.

**Comment by jakobbotsch** [comment]
Ah, sorry, no, this is the constant. Ok, then things make more sense to me.

**Review by jakobbotsch — APPROVED** [review]

**Comment by kunalspathak** [comment]
> Locals don't use `GTF_NOREG_AT_USE` though, only true SDSUs do

That's true to the certain extent although I don't see how it is enforced today. 

> I don't understand why LSRA leaves the register assignment set

I am not sure the historic reason of doing it this way. I tried a minimal change to do it but that gave lot of spmi failures. I will merge this PR and look deeper into it in a separate PR to understand more and see a way to clean things up.

**Pull request merged**
