### PR TITLE
Disallow parsing '0X+F' as a valid integer

### LINKED ISSUE #61039: Int32Converter tolerates outrageous syntax 0X+FFFFFFFF
### Description

[Int32Converter](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter.convertfromstring) should not accept a syntax with a `+` sign following the hexadecimal prefix.

### Reproduction Steps

```powershell
+ '0X+FFFFFFFF'
```

### Expected behavior

[FormatException](https://docs.microsoft.com/en-us/dotnet/api/system.formatexception)

### Actual behavior

`-1`

### Regression?

Wrong under .NET Framework 4.8.4420.0 too.

### Known Workarounds

```powershell
'0X+FFFFFFFF' | % {  IF ($_ -LIKE '0X+*' ) { [CONVERT]:: TOINT32( $_, 0X10 ) } ELSE { + $_ } }
```

### Configuration

.NET 5.0.11
 Win32NT             10.0.19043.0 Microsoft Windows NT 10.0.19043.0
[ENVIRONMENT]:: IS64BITOPERATINGSYSTEM

### Other information

_No response_

### PR DESCRIPTION
**Pull request by yecril71pl**
Fix #61039 (hopefully)

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks for your interest in contributing. This is a breaking change and makes the code more expensive and complicated. While agree it's odd that Convert.ToInt32 accepts this format,  I don't believe churning the code here is beneficial. Why do you believe this is important to change?

**Comment by am11** [comment]
This maybe be a culture specific behavior. With en-US, `0X+F` pattern is already disallowed.

```c#
using System;
using System.Globalization;

CultureInfo c = CultureInfo.CurrentCulture;
Console.WriteLine("Culture name: {0}, LCID: {1} ",
    c.LCID == 127 ? "Invariant" : c.Name, c.LCID);

Console.WriteLine(Convert.ToInt32("0XFFFFFFFF", 16)); // works
Console.WriteLine(Convert.ToInt32("0X+FFFFFFFF", 16)); // throws
```

```sh
# export LANG=en_US.UTF-8
$ dotnet run

Culture name: en-US, LCID: 1033
-1
Unhandled exception. System.FormatException: Could not find any recognizable digits.
   at System.ParseNumbers.StringToInt(ReadOnlySpan`1 s, Int32 radix, Int32 flags, Int32& currPos)
   at System.Convert.ToInt32(String value, Int32 fromBase)
```

**Comment by stephentoub** [comment]
I'm going to close this PR.  We can discuss any concerns about the behavior on the original issue.

**Comment by yecril71pl** [comment]
> This maybe a culture specific behavior. With en-US, `0X+F` pattern is already disallowed.

This is not a problem of [Convert.ToInt32](https://docs.microsoft.com/en-us/dotnet/api/system.convert.toint32) and it is not culture-specific (because [ComponentModel](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.basenumberconverter.convertfrom) is not, and cannot be, culture-specific).

**Comment by am11** [comment]
> ComponentModel is not, and cannot be, culture-specific

It can be: `ConvertFrom` has an [overload](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter.convertfrom?view=net-5.0#System_ComponentModel_TypeConverter_ConvertFrom_System_ComponentModel_ITypeDescriptorContext_System_Globalization_CultureInfo_System_Object_) that takes `CultureInfo`. There is also `ConvertFromInvariantString` method.

**Comment by yecril71pl** [comment]
> > ComponentModel is not, and cannot be, culture-specific
> 
> It can be: `ConvertFrom` has an [overload](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.typeconverter.convertfrom?view=net-5.0#System_ComponentModel_TypeConverter_ConvertFrom_System_ComponentModel_ITypeDescriptorContext_System_Globalization_CultureInfo_System_Object_) that takes `CultureInfo`. There is also `ConvertFromInvariantString` method.

That means it is culture-aware, not culture-specific.

**Pull request closed without merging**
