### PR TITLE
[6.0 preview 5] Fix assertion failure / crash in multi-core JIT

### PR DESCRIPTION
**Pull request by kouvel**
- Port of https://github.com/dotnet/runtime/pull/53573 to Preview 5
- When the recorder times out it doesn't actually stop profiling, but writes out the profile
- The app may later stop profiling, and then it tries to write the profile again
- PR https://github.com/dotnet/runtime/pull/48326 fairly expected that the profile is only written once (some state is mutated)
- The timer is being stopped in the recorder's destructor
- Fixes https://github.com/dotnet/runtime/issues/53014

### Customer impact

- By default, the multi-core JIT timeout time for the recorder is 12 seconds. The timer is only used on Windows.
- After a timeout, if the application exits, stops a profile, or starts another profile, the app crashes
- Affects any Windows app that enables multi-core JIT

### Regression?

- Yes, from 6.0 preview 4

### Testing

- Manual test with a repro, added test to coreclr tests
- PAL, coreclr, and libraries tests

### Risk

Low:
- The change stops profiling on timeout in the same way that it is stopped in all other cases
- I'm not aware of any significant risks

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by mmitche** [comment]
I don't think this will make p5. We're past the point of new changes unless they are ship stoppers at this point.

**Comment by mmitche** [comment]
@kouvel @jkotas, @adityapatwardhan is blocked by this (pulling preview 5 into powershell). Is there a workaround?

**Comment by adityapatwardhan** [comment]
@rjmholt as FYI.

**Comment by jkotas** [comment]
> Is there a workaround?

Avoid using multicore JIT temporily.

**Comment by adityapatwardhan** [comment]
@jkotas  How can we disable that?

**Comment by daxian-dbw** [comment]
@jkotas I presume that means we should avoid using `ProfileOptimization.StartProfile` in PowerShell, right? Anything else?

**Comment by jkotas** [comment]
Right. Also, `AssemblyLoadContext.StartProfileOptimization`.

**Pull request closed without merging**
