### PR TITLE
RefTypeZeroInit doesn't need treeNode

### LINKED ISSUE #54100: JIT EH write thru crash
The JIT crashes while compiling the following program:
```csharp
// Generated by Fuzzlyn v1.1 on 2021-06-12 00:42:21
// Seed: 11991615925769861084
// Reduced from 166.4 KiB to 0.8 KiB in 00:10:53
// Crashes the runtime
public class Program
{
    static ushort[][] s_23 = new ushort[][]{new ushort[]{0}};
    static short s_32;
    static short s_33;
    static int s_45;
    public static void Main()
    {
        ushort[] vr4 = s_23[0];
        ushort vr6 = M45();
    }

    static ushort M45()
    {
        short var0;
        try
        {
            var0 = s_32;
        }
        finally
        {
            var0 = s_33;
            int var1 = s_45;
            ulong vr8 = default(ulong);
            var0 = (short)((sbyte)vr8 - var0);
            try
            {
                M46();
            }
            finally
            {
                M46();
            }

            System.Console.WriteLine(var1);
        }

        return 0;
    }

    static ulong M46()
    {
        return default(ulong);
    }
}
```

There is no non-empty block [here](https://github.com/dotnet/runtime/blob/cc6d3147ff1f10d2ee2b0751cf799fc4cc1abbae/src/coreclr/jit/lsrabuild.cpp#L1921). With `COMPlus_EnableEHWriteThru=0` things seems to go alright.
cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by kunalspathak**
When we create `RefTypeZeroInit`, we do not have the exact tree node to associate the `RefPosition` with. So we find the first non-empty block and use the first tree node of that block as the `treeNode` of those refpositions. However, this cannot (and almost never) will be corresponding to the varIndex for which we are creating refposition. The `treeNode` is often used to calculate weight of the refposition, and this might led to inaccurate calculation (which happens in the below diff). The solution is to stop tracking `treeNode` for `RefTypeZeroInit`.

In https://github.com/dotnet/runtime/issues/54100 where we try to find the first non-empty block, but in the repro code, there is no non-empty block.

## coreclr_tests.pmi.Linux.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 2935
Total bytes of diff: 2814
Total bytes of delta: -121 (-4.12% of base)
Total relative delta: -0.04
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
        -121 : 218441.dasm (-4.12% of base)

1 total files with Code Size differences (1 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
        -121 (-4.12% of base) : 218441.dasm - BenchmarkConsoleApplication.BenchmarkSystem:RunBenchmark(BenchmarkConsoleApplication.Benchmark):BenchmarkConsoleApplication.Results:this

Top method improvements (percentages):
        -121 (-4.12% of base) : 218441.dasm - BenchmarkConsoleApplication.BenchmarkSystem:RunBenchmark(BenchmarkConsoleApplication.Benchmark):BenchmarkConsoleApplication.Results:this

1 total methods with Code Size differences (1 improved, 0 regressed), 0 unchanged.
ONELINER|Code Size|E:\spmi\asm.coreclr_tests.pmi.Linux.x64.checked\base|2935|2814|-121|-4.12%|1|0|0

```

</details>

--------------------------------------------------------------------------------

## coreclr_tests.pmi.windows.x64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 3067
Total bytes of diff: 3017
Total bytes of delta: -50 (-1.63% of base)
Total relative delta: -0.02
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```


Top file improvements (bytes):
         -50 : 219897.dasm (-1.63% of base)

1 total files with Code Size differences (1 improved, 0 regressed), 0 unchanged.

Top method improvements (bytes):
         -50 (-1.63% of base) : 219897.dasm - BenchmarkConsoleApplication.BenchmarkSystem:RunBenchmark(BenchmarkConsoleApplication.Benchmark):BenchmarkConsoleApplication.Results:this

Top method improvements (percentages):
         -50 (-1.63% of base) : 219897.dasm - BenchmarkConsoleApplication.BenchmarkSystem:RunBenchmark(BenchmarkConsoleApplication.Benchmark):BenchmarkConsoleApplication.Results:this

1 total methods with Code Size differences (1 improved, 0 regressed), 0 unchanged.
ONELINER|Code Size|E:\spmi\asm.coreclr_tests.pmi.windows.x64.checked.2\base|3067|3017|-50|-1.63%|1|0|0

```

</details>

--------------------------------------------------------------------------------

Fixes: https://github.com/dotnet/runtime/issues/54100

### CODE REVIEW

**Comment by kunalspathak** [comment]
Libraries-jitstressregs failures are related to https://github.com/dotnet/runtime/issues/56190

**Comment by kunalspathak** [comment]
Some runtime pipeline failures are related to https://github.com/dotnet/runtime/issues/56359.

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
Can you add the test from https://github.com/dotnet/runtime/issues/54100 as a regression test?

**Comment by kunalspathak** [comment]
> Can you add the test from #54100 as a regression test?

Done.

**Pull request merged**
