### PR TITLE
Build System.IO.Compression.Native on WebAssembly as well.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by safern** [comment]
Thanks @vargaz. I'll wait to review until builds are green.

**Comment by vargaz** [comment]
Are the build failures caused by this PR ? The locations seem relevant, but all the changes are inside if()-s, so I don't see how it can affect the linux builds etc.

**Comment by vargaz** [comment]
This is ready for review now.

**Review by safern — APPROVED** [review]

**Comment by safern** [comment]
Thanks @vargaz. Merging now.

**Pull request merged**
