### PR TITLE
Require UTF8 encoding in GetX509NameInfo

### LINKED ISSUE #59105: X509Certificate2.GetNameInfo(SimpleName) with non-ASCII data on Linux returns oddly encoded results.
Verified on Ubuntu 18.04 with .NET Core 3.1 and .NET master from a couple months ago.

* Find a certificate whose subject name is in Russian/Cyrillic.
* Instantiate X509Certificate2 with that cert
* call cert.GetNameInfo(X509NameType.SimpleName, false).

Expect: Something Russian
Actual: A string escaped in with backslash-capital-Us.

 e.g. 

```
-----BEGIN CERTIFICATE-----
MIIFFTCCBMKgAwIBAgIRAOrKMs71+XnWjTxOTyzGh6QwCgYIKoUDBwEBAwIwggEk
MR4wHAYJKoZIhvcNAQkBFg9kaXRAbWluc3Z5YXoucnUxCzAJBgNVBAYTAlJVMRgw
FgYDVQQIDA83NyDQnNC+0YHQutCy0LAxGTAXBgNVBAcMENCzLiDQnNC+0YHQutCy
0LAxLjAsBgNVBAkMJdGD0LvQuNGG0LAg0KLQstC10YDRgdC60LDRjywg0LTQvtC8
IDcxLDAqBgNVBAoMI9Cc0LjQvdC60L7QvNGB0LLRj9C30Ywg0KDQvtGB0YHQuNC4
MRgwFgYFKoUDZAESDTEwNDc3MDIwMjY3MDExGjAYBggqhQMDgQMBARIMMDA3NzEw
NDc0Mzc1MSwwKgYDVQQDDCPQnNC40L3QutC+0LzRgdCy0Y/Qt9GMINCg0L7RgdGB
0LjQuDAeFw0yMTA3MDIxMjQxNDdaFw0zOTA3MDIxMjQxNDdaMIIBJDEeMBwGCSqG
SIb3DQEJARYPZGl0QG1pbnN2eWF6LnJ1MQswCQYDVQQGEwJSVTEYMBYGA1UECAwP
Nzcg0JzQvtGB0LrQstCwMRkwFwYDVQQHDBDQsy4g0JzQvtGB0LrQstCwMS4wLAYD
VQQJDCXRg9C70LjRhtCwINCi0LLQtdGA0YHQutCw0Y8sINC00L7QvCA3MSwwKgYD
VQQKDCPQnNC40L3QutC+0LzRgdCy0Y/Qt9GMINCg0L7RgdGB0LjQuDEYMBYGBSqF
A2QBEg0xMDQ3NzAyMDI2NzAxMRowGAYIKoUDA4EDAQESDDAwNzcxMDQ3NDM3NTEs
MCoGA1UEAwwj0JzQuNC90LrQvtC80YHQstGP0LfRjCDQoNC+0YHRgdC40LgwZjAf
BggqhQMHAQEBATATBgcqhQMCAiMBBggqhQMHAQECAgNDAARAznwizLAQgEZQecg2
Re7+vfP0h4I5BVHNCzC3UQsCNZdAxM2nn/pKJGaDI8hv4DM3FF3reU2jWDO7Sp66
fTrSZqOCAcIwggG+MIH1BgUqhQNkcASB6zCB6Aw00J/QkNCa0JwgwqvQmtGA0LjQ
v9GC0L7Qn9GA0L4gSFNNwrsg0LLQtdGA0YHQuNC4IDIuMAxD0J/QkNCaIMKr0JPQ
vtC70L7QstC90L7QuSDRg9C00L7RgdGC0L7QstC10YDRj9GO0YnQuNC5INGG0LXQ
vdGC0YDCuww10JfQsNC60LvRjtGH0LXQvdC40LUg4oSWIDE0OS8zLzIvMi8yMyDQ
vtGCIDAyLjAzLjIwMTgMNNCX0LDQutC70Y7Rh9C10L3QuNC1IOKEliAxNDkvNy82
LzEwNSDQvtGCIDI3LjA2LjIwMTgwPwYFKoUDZG8ENgw00J/QkNCa0JwgwqvQmtGA
0LjQv9GC0L7Qn9GA0L4gSFNNwrsg0LLQtdGA0YHQuNC4IDIuMDBDBgNVHSAEPDA6
MAgGBiqFA2RxATAIBgYqhQNkcQIwCAYGKoUDZHEDMAgGBiqFA2RxBDAIBgYqhQNk
cQUwBgYEVR0gADAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNV
HQ4EFgQUGXePu4Lmb8hfk/AVHZMiodatDCYwCgYIKoUDBwEBAwIDQQCFR821LAew
8tY3/fYGGXQNN5g6E74pjdurOqOoZbS+0WjiGsLPVzcrAts2l7BRGowjZ3MVAmHJ
L/NjPYAClFu0
-----END CERTIFICATE-----
```

(https://iitrust.ru/downloads/ca/guc2021.crt)

The subject CN is `Минкомсвязь России`, encoded as `0C 23 D0 9C D0 B8 D0 BD D0 BA D0 BE D0 BC D1 81 D0 B2 D1 8F D0 B7 D1 8C 20 D0 A0 D0 BE D1 81 D1 81 D0 B8 D0 B8`

GetNameInfo is returning `\U041C\U0438\U043D\U043A\U043E\U043C\U0441\U0432\U044F\U0437\U044C \U0420\U043E\U0441\U0441\U0438\U0438`, and passing that to Encoding.UTF8.GetBytes says it's not a console problem:

`5C 55 30 34 31 43 5C 55 30 34 33 38 5C 55 30 34 33 44 5C 55 30 34 33 41 5C 55 30 34 33 45 5C 55 30 34 33 43 5C 55 30 34 34 31 5C 55 30 34 33 32 5C 55 30 34 34 46 5C 55 30 34 33 37 5C 55 30 34 34 43 20 5C 55 30 34 32 30 5C 55 30 34 33 45 5C 55 30 34 34 31 5C 55 30 34 34 31 5C 55 30 34 33 38 5C 55 30 34 33 38`

### PR DESCRIPTION
**Pull request by vcsjones**
This changes `GetX509NameInfo` to force UTF8 encoding when writing to the BIO with `ASN1_STRING_print_ex`. The OpenSSL function won't return UTF8 unless you ask it to. Otherwise, it returns an escaped string of the contents of the string.

We assume the BIO is going to contain UTF8 here:

https://github.com/dotnet/runtime/blob/6d094a0aba0daa1af1e9c845f142c92d78a18a62/src/libraries/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Unix/OpenSslX509CertificateReader.cs#L723

Test result, before the fix:

```
xUnit.net 00:00:01.07]     System.Security.Cryptography.X509Certificates.Tests.PropsTests.GetNameInfo_HandlesUtf8Encoding(issuer: True) [FAIL]
[xUnit.net 00:00:01.09]     System.Security.Cryptography.X509Certificates.Tests.PropsTests.GetNameInfo_HandlesUtf8Encoding(issuer: False) [FAIL]
  Failed System.Security.Cryptography.X509Certificates.Tests.PropsTests.GetNameInfo_HandlesUtf8Encoding(issuer: True) [6 ms]
  Error Message:
   Assert.Equal() Failure
          ↓ (pos 0)
Expected: картошка
Actual:   \U043A\U0430\U0440\U0442\U043E\U0448\U043···
          ↑ (pos 0)
  Stack Trace:
     at System.Security.Cryptography.X509Certificates.Tests.PropsTests.GetNameInfo_HandlesUtf8Encoding(Boolean issuer) in /workspaces/runtime/src/libraries/System.Security.Cryptography.X509Certificates/tests/PropsTests.cs:line 403
  Failed System.Security.Cryptography.X509Certificates.Tests.PropsTests.GetNameInfo_HandlesUtf8Encoding(issuer: False) [< 1 ms]
  Error Message:
   Assert.Equal() Failure
          ↓ (pos 0)
Expected: картошка
Actual:   \U043A\U0430\U0440\U0442\U043E\U0448\U043···
          ↑ (pos 0)
  Stack Trace:
     at System.Security.Cryptography.X509Certificates.Tests.PropsTests.GetNameInfo_HandlesUtf8Encoding(Boolean issuer) in /workspaces/runtime/src/libraries/System.Security.Cryptography.X509Certificates/tests/PropsTests.cs:line 403
```

Closes #59105

### CODE REVIEW

**Review by bartonjs — APPROVED** [review]

**Comment by bartonjs** [comment]
@danmoseley Would you be supportive of taking this as a 6.0 candidate?

* Globalization impact
* Very scoped fix
* Now with tests
* Externally reported (StackOverflow)

**Comment by danmoseley** [comment]
Might. Can you share SO link? How long has this bug been present without previous reports?

Let's get this merged meantime

**Comment by bartonjs** [comment]
>  Can you share SO link?

https://stackoverflow.com/questions/69105533/net-5-x509certificate-getnameinfo-uppercases-unicode-escape-characters

> How long has this bug been present without previous reports?

.NET Core 1.0 preview 8, or thereabouts :smile:.

**Comment by vcsjones** [comment]
Failure:

> System.Net.Security.Tests.ApmSslStreamSystemDefaultTest.ClientAndServer_OneOrBothUseDefault_Ok(clientProtocols: Tls13, serverProtocols: null) [FAIL]
      System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
      ---- System.ComponentModel.Win32Exception : The Local Security Authority cannot be contacted

Seems like https://github.com/dotnet/runtime/issues/58927 and is unrelated from the PR.

**Comment by vcsjones** [comment]
I don't think the macOS libraries tests ran, either.

**Comment by danmoseley** [comment]
Rerunning failed jobs...

thinking about it, this might meet the servicing bar. Let's get a PR up against 6.0 once this goes in. Or preemptively, if you like.

**Pull request merged**
