### PR TITLE
Apply sequence equality comparison to the final Regex incremental value.

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
ImmutableArray uses reference equality semantics, so two arrays containing equal values will always trigger source compilation downstream. Updates the incremental value to use reference equality comparison.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
Thanks. How did you a) come across the need for these and b) validate them?

**Comment by eiriktsarpalis** [comment]
It's just something I noticed when auditing the implementation. I could try adding an incremental caching unit test suite similar to the LibraryImportGenerator or STJ to make sure this works as expected E2E.

**Comment by eiriktsarpalis** [comment]
@stephentoub would we want to service this for .NET 8? Without this change the final incremental value is always going to use reference equality so it can never cache results.

**Comment by stephentoub** [comment]
.NET 8 is as good or better than .NET 7 here, right?  I'd say it's probably not worthwhile unless we hear any noise about it.

**Pull request merged**
