### PR TITLE
Ensure that fgMorphFieldToSimdGetElement doesn't call gtNewSimdGetElementNode if the ISA is unsupported

### LINKED ISSUE #66205: Assertion failed 'IsBaselineSimdIsaSupportedDebugOnly()'
Many tests in the "runtime-coreclr jitstress-isas-x86" pipeline on x64 fail with this, e.g. JIT\\opt\\Vectorization\\UnrollEqualsStartsWIth\\UnrollEqualsStartsWIth.cmd in CoreCLR windows x64 Checked jitstress_isas_x86_nosse2:

https://dev.azure.com/dnceng/public/_build/results?buildId=1643987&view=ms.vss-test-web.build-test-results-tab&runId=45451108&paneView=debug

```
Assert failure(PID 4388 [0x00001124], Thread: 404 [0x0194]): Assertion failed 'IsBaselineSimdIsaSupportedDebugOnly()' in 'Tests_len14_9:Test_tst_32(System.String):bool' during 'Importation' (IL size 22; hash 0x1efa538e; FullOpts)

File: D:\a\_work\1\s\src\coreclr\jit\gentree.cpp Line: 18178
Image: C:\h\w\AF720924\p\corerun.exe
Return code:      1
Raw output file:      C:\h\w\AF720924\w\B4E30A89\uploads\Reports\JIT.opt\Vectorization\UnrollEqualsStartsWIth\UnrollEqualsStartsWIth.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\AF720924\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  UnrollEqualsStartsWIth.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AF720924\p
C:\h\w\AF720924\w\B4E30A89\e\JIT\opt\Vectorization\UnrollEqualsStartsWIth\UnrollEqualsStartsWIth.cmd
Expected: True
Actual:   False
```

@tannergooding @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves #66205 

Noting that this is the "simple" fix. The change I discussed in the issue is more complex/involved and will require a few other changes/refactorings to be possible, so I opted to do the simple thing first to unblock CI. I'll log an issue tracking the more complex change.

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @kunalspathak, @BruceForstall 

Will kick off the outerloop ISA jobs after JIT formatting and a couple other changes come back as "passing" to avoid unnecessary CI churn.

**Review by BruceForstall — APPROVED** [review]

**Comment by tannergooding** [comment]
ARM64 only had an unrelated failure in LSRA. There was another related failure in x86/x64 that should be fixed now (was checking for Vector128 rather than for baseline support)

**Comment by tannergooding** [comment]
Remaining ARM failure is https://github.com/dotnet/runtime/issues/66921, currently assigned out to @kunalspathak 

R2R-CG2 failures are likewise pre-existing/unrelated

**Pull request merged**
