### PR TITLE
Make ObjectiveC tests in System.Runtime.InteropServices.Tests check exit code for remote execution

### PR DESCRIPTION
**Pull request by elinor-fung**
@AaronRobinsonMSFT @jkoritzinsky

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by stephentoub** [comment]
Is it coincidence that this PR is green?

**Review by stephentoub — APPROVED** [review]
Thanks.

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
As a sanity check I queried Kusto for this PR and it looks like we also have coredumps coming from Linux-based machines for System.Runtime.InteropServices.Tests:

```
Jobs
| where Source == "pr/public/dotnet/runtime/refs/pull/63769/merge"
| join kind=inner Files on JobId
| where FileName startswith "core"
| join kind=inner WorkItems on WorkItemId
| project Queued, QueueAlias, FileName, SizeBytes, ConsoleUri, DumpUri=Uri
```

Queued | QueueAlias |	FileName |	SizeBytes |	ConsoleUri |	DumpUri
--------|-------------|------------|------------|--------------|-----
2022-01-14T01:01:28.413Z |		centos.7.amd64.open |	core.1000.101 |	237547520	 | https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-63769-merge-78bf5ce949f74261ae/System.Runtime.InteropServices.Tests/1/console.33ad47b2.log?sv=2019-07-07&se=2022-02-03T01%3A01%3A26Z&sr=c&sp=rl&sig=%2B8GiitM3FVEn8itbrODUYjid9zmzKsm45FrXWeRrAic%3D	 | https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-63769-merge-78bf5ce949f74261ae/System.Runtime.InteropServices.Tests/1/core.1000.101?sv=2019-07-07&se=2022-02-03T01%3A01%3A26Z&sr=c&sp=rl&sig=%2B8GiitM3FVEn8itbrODUYjid9zmzKsm45FrXWeRrAic%3D
2022-01-14T01:01:33.765Z |		redhat.7.amd64.open |	core.1000.32551 |	208982016	 | https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-63769-merge-886db677d080426bb7/System.Runtime.InteropServices.Tests/1/console.ce6c671c.log?sv=2019-07-07&se=2022-02-03T01%3A01%3A27Z&sr=c&sp=rl&sig=nuEpQHp1axN0rYtKenAfU9mVxt6ThIij8BptRVhNgjY%3D	 | https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-63769-merge-886db677d080426bb7/System.Runtime.InteropServices.Tests/1/core.1000.32551?sv=2019-07-07&se=2022-02-03T01%3A01%3A27Z&sr=c&sp=rl&sig=nuEpQHp1axN0rYtKenAfU9mVxt6ThIij8BptRVhNgjY%3D
2022-01-14T01:01:39.097Z |		debian.10.amd64.open |	core.1000.86 |	196788224	 | https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-63769-merge-9c73687b9fb2440785/System.Runtime.InteropServices.Tests/1/console.2f2a5c65.log?sv=2019-07-07&se=2022-02-03T01%3A01%3A27Z&sr=c&sp=rl&sig=LuglVre9bZyNTdaghDxPvoGa%2BRVyLtBbEYLppuCKpKQ%3D	 | https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-63769-merge-9c73687b9fb2440785/System.Runtime.InteropServices.Tests/1/core.1000.86?sv=2019-07-07&se=2022-02-03T01%3A01%3A27Z&sr=c&sp=rl&sig=LuglVre9bZyNTdaghDxPvoGa%2BRVyLtBbEYLppuCKpKQ%3D
2022-01-14T01:01:40.259Z |		ubuntu.1804.amd64.open |	core.1000.29422 |	217485312	 | https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-63769-merge-31671c62fa55499fb3/System.Runtime.InteropServices.Tests/1/console.3a870c7a.log?sv=2019-07-07&se=2022-02-03T01%3A01%3A27Z&sr=c&sp=rl&sig=4KQw7M%2BK%2BRCaRKz%2F5sqsTsyntYlPy2apRziWRRLKka4%3D	 | https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-63769-merge-31671c62fa55499fb3/System.Runtime.InteropServices.Tests/1/core.1000.29422?sv=2019-07-07&se=2022-02-03T01%3A01%3A27Z&sr=c&sp=rl&sig=4KQw7M%2BK%2BRCaRKz%2F5sqsTsyntYlPy2apRziWRRLKka4%3D
2022-01-14T01:01:41.234Z |		alpine.314.amd64.open |	core.1000.100 |	146907136	 | https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-63769-merge-7393da90ca414136be/System.Runtime.InteropServices.Tests/1/console.e2c606b8.log?sv=2019-07-07&se=2022-02-03T01%3A01%3A28Z&sr=c&sp=rl&sig=v%2B%2F4mjYexbQIOuReKVREK4DXZae3SdLTFRV7f9JaUS4%3D	 | https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-63769-merge-7393da90ca414136be/System.Runtime.InteropServices.Tests/1/core.1000.100?sv=2019-07-07&se=2022-02-03T01%3A01%3A28Z&sr=c&sp=rl&sig=v%2B%2F4mjYexbQIOuReKVREK4DXZae3SdLTFRV7f9JaUS4%3D

**Comment by stephentoub** [comment]
That's still expected if any child process crashes even if on purpose and even if the test waits on the child and even if the test passes, right? That's what I asked Matt to fix,  to stop uploading crash dumps on success.

**Comment by elinor-fung** [comment]
Merging, since last commit was TODO comment only.

**Comment by akoeplinger** [comment]
> That's still expected if any child process crashes even if on purpose and even if the test waits on the child and even if the test passes, right? That's what I asked Matt to fix, to stop uploading crash dumps on success.

Correct, but I wasn't sure if that was the case or we missed something similar to what this PR fixes.

**Pull request merged**
