### PR TITLE
add support for less standard serial port speeds on macOS

### LINKED ISSUE #43719: System.IO.Ports - Unable to open a SerialPort when BaudRate is set to 1M on a Mac
### Description

Unable to connect to a board with a BaudRate set to 1M on a Mac, using System.IO.Ports. The same code works properly on Linux and Windows.

Example code I am using (created a console app using the dotnet new console command):

```csharp
        static void Main(string[] args)
        {
            var ports = SerialPort.GetPortNames();       // always works nicely

            var mySer = new SerialPort("/dev/cu.usbserial-AR0JMV5Z",
                                                    1000000,
                                                    Parity.None, 
                                                    8,
                                                    StopBits.One);

            var msg = new byte[] { 0x02, 0x05, 0x21, 0xFF, 0x01, 0x01, 0x29};

            mySer.Open();

            mySer.Write(msg, 0 , msg.Length);

            while (!Console.KeyAvailable)
                ;

            mySer.Close();
        }
```

When opening the port, I receive the following exception:

```csharp
Exception has occurred: CLR/System.ArgumentException
An unhandled exception of type 'System.ArgumentException' occurred in System.IO.Ports.dll: 'Value does not fall within the expected range.'
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
```

### Configuration
* NET Core 3.1.8 and also tried on .NET 5.0-rc2
* Tried in separate occasions, in both SDKs
    * \<PackageReference Include="System.IO.Ports" Version="4.7.0"/>
    * \<PackageReference Include="System.IO.Ports" Version="5.0.0-rc.2.20475.5"/>
* MacOS Catalina 10.15.7, x64
* FT232R USB UART device (ProdID: 0x6001, VendorID: 0x0403 - FTDI)

### Regression?
Not to my knowledge.

### What I also tried

* I tried to use the NetCoreSerial nuget package (https://www.nuget.org/packages/NetCoreSerial/) and was able to connect and send the message properly. I noticed that that library uses Libc to connect to the port and the .NET runtime uses termios. 
* Tried the same in Ubuntu 20.04.1 LTS and Windows 10 with the same SDK versions and have no issues there so I am assuming this is specific to how Mac handles the usb serial.
* Also tried to connect to the board using Python 3.8 (with pyserial v3.4) and everything works nicely.
* Checked the termios.h on the XCode MacSDK folder and the max BaudRate there is only 230400 so I am assuming that the other library and in python, that "limitation" can be circumvented somehow. 
* Tried to install FTDI VCP drivers 2.4.4 and aliasing the BaudRate according to these instructions (https://spin.atomicobject.com/2013/06/23/baud-rates-ftdi-driver-mac/) and was able to connect but no messages are sent properly so the issue might be something that I don't understand.

Please let me know if you need more information regarding this issue.

Does this happen with anyone else? 

Does anyone know of a workaround?

Thanks!

### PR DESCRIPTION
**Pull request by wfurt**
It seems like macOS terms end with B230400 (probably limit of legacy serial) but many USB serial devices can do more. 
When .NET tries to use higher speed it always fails as we fail to lookup platform speed mapping. macOS has call to set specific speed so this PR use that as fallback if speed lookup fails. That leaves the decision to driver and OS e.g. it will either succeed or fail and we report that accordingly. 

I don't have enough gear to but I was able to verify that serial port can be opened with speed beyond B230400.

 fixes #43719

### CODE REVIEW

**Comment by krwq** [comment]
codewise LGTM, we will need someone with the right hardware to test this, @MicBoucinha any chance you could try this out? (easiest way is to sync with @wfurt's branch, build the repo and test this code inside of tests directory which will use the right binaries automatically)

**Comment by wfurt** [comment]
I was planning to write instructions how to grab bits from this PR. (I just did not get to it over the weekend)

**Comment by wfurt** [comment]
(and I plan to keep it as draft until we get verification)

**Comment by MicBoucinha** [comment]
@krwq I tested it and it works on my machine. I followed the instructions left by wfurt on the issue https://github.com/dotnet/runtime/issues/43719#issuecomment-721023594

**Comment by wfurt** [comment]
Thanks @MicBoucinha  for confirmation.

**Comment by wfurt** [comment]
can you please take final look @krwq? It seems like this works as expected.

**Comment by wfurt** [comment]
ping @krwq?

**Review by krwq — APPROVED** [review]
Sorry, got flooded with notification and missed it, LGTM

**Pull request merged**
