### PR TITLE
Arm64/Sve: Remove entries of SVE APIs take 32-bit address 

### PR DESCRIPTION
**Pull request by kunalspathak**
We have done it in the past because we do not have good way of validating them. There were few left over that I commented in this PR and disabled the tests for them.

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/arm64-contrib

**Review by amanasifkhalid — APPROVED** [review]
Did a quick parse locally, and all the `Gather*` APIs with a `svuint32_t` argument are disabled. LGTM

**Pull request merged**
