### PR TITLE
Redhawk to NativeAOT

### PR DESCRIPTION
**Pull request by prasanta10**
There are more places left where some manual changes is needed that I will be doing in the second pass.

### CODE REVIEW

**Comment by prasanta10** [comment]
@jkotas I have changed the frequently used terms in this PR as you suggested eg.(FEATURE_REDHAWK -> FEATURE_NATIVEAOT, REDHAWK_API -> NATIVEAOT_API, WINDOWS_REDHAWK-> WINDOWS_NATIVEAOT, REDHAWK_PALIMPORT->NATIVEAOT_PALIMPORT and few more)

**Comment by jkotas** [comment]
Sounds good. Do you need help with the build breaks?

**Comment by prasanta10** [comment]
Yes Sir.

**Comment by jkotas** [comment]
You have missed `src\coreclr\gc\gc.cpp` somehow. This file is still using `FEATURE_REDHAWK` instead of `FEATURE_NATIVEAOT`.

**Comment by prasanta10** [comment]
I went through _src\coreclr\gc\gc.cpp_  but I still cannot find the place where FEATURE_REDHAWK is still being used.

**Comment by prasanta10** [comment]
Went through that issue. Only a few mention of Redhawk is remaining in comments, which I will manually fix.

**Comment by prasanta10** [comment]
I went through  **src\coreclr\gc\gc.cpp** and changed it. I changed a few more occurences of Redhawk.

**Comment by jkotas** [comment]
You need to also actually rename the files referenced by the `#include` directives

**Comment by prasanta10** [comment]
Yes sir , did that.

**Comment by jkotas** [comment]
There are more pretty straightforward build errors (missed renames). Are you able to do build locally on your machine, or see the build errors in the CI system above?

**Comment by prasanta10** [comment]
I have renamed almost everything except the ones in the comments. No sir, there are errors when I try to build.

**Comment by jkotas** [comment]
It is hard to effectively contribute larger delta like this one if you are not able to build locally.

**Pull request closed without merging**
