### PR TITLE
Remove passing tests from exclude list

### LINKED ISSUE #34380: CoreCLR tests on Mono runtime : crash running JIT/Methodical/NaN/r4nanconv_il_r/r4nanconv_il_r.sh
Crash seen when running the following CoreCLR test on the mono runtime from the dotnet\runtime repo.
Repro : Command to run individual tests : From the dotnet\runtime repo src\mono\netcore run this command or relevant one for a particular test - make run-tests-coreclr CoreClrTest="bash ../../artifacts/tests/coreclr/OSX.x64.Debug/JIT/Methodical/NaN/r4nanconv_il_r/r4nanconv_il_r.sh”

Crash report :

=================================================================
          External Debugger Dump:
          =================================================================
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/JIT/Methodical/NaN/r4nanconv_il_r/r4nanconv_il_r.sh: line 275: 82297 Abort trap: 6           $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/JIT/Methodical/Reports/JIT.Methodical/NaN/r4nanconv_il_r/r4nanconv_il_r.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun r4nanconv_il_r.dll ''
          Based on bug #91021 - testing Single.NaN
          The conv.* instructions never throw overflow exceptions.  The results of the conversions is undefined for NaN.
          The conv.ovf.* instructions should throw OverflowException if the result can not be represented in the result type
          
          testcase 1 (conv.i1) : 0
          testcase 2 (conv.i2) : 0
          testcase 3 (conv.i4) : -2147483648
          testcase 4 (conv.i8) : -9223372036854775808
          testcase 5 (conv.r4) : NaN
          testcase 6 (conv.r8) : NaN
          testcase 7 (conv.u1) : 0
          testcase 8 (conv.u2) : 0
          testcase 9 (conv.u4) : 0
          testcase 10 (conv.u8) : 0
          testcase 11 (conv.i) : 0
          testcase 12 (conv.u) : 0
          
          =================================================================
          Native Crash Reporting
          =================================================================
          Got a segv while executing native code. This usually indicates
          a fatal error in the mono runtime or one of the native libraries 
          used by your application.
          =================================================================
          
          =================================================================
          Native stacktrace:
          =================================================================
          0x10d1624b2 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_dump_native_crash_info
          0x10d104105 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_handle_native_crash
          0x10d32b387 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : altstack_handle_and_restore.cold.1
          0x10d15cdee - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : altstack_handle_and_restore
          0x10d0be868 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_local_cprop
          0x10d05da02 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mini_method_compile
          0x10d05fbbc - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_compile_method_inner
          0x10d0639f2 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_compile_method_with_opt
          0x10d106c1f - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : common_call_trampoline
          0x10d106690 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_magic_trampoline
          0x10d4e3393 - Unknown
          0x10d6a4983 - Unknown
          0x10d6a59d6 - Unknown
          0x10d067f9e - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_runtime_invoke
          0x10d23d2c8 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_runtime_invoke_checked
          0x10d243645 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_runtime_exec_main_checked
          0x10d0c202c - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_exec
          0x10d0c5126 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_main
          0x10d13e589 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : monovm_execute_assembly
          0x10d01c896 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun : _Z22ExecuteManagedAssemblyPKcS0_S0_iPS0_
          0x10d01b18d - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun : main
          0x7fff726fa7fd - /usr/lib/system/libdyld.dylib : start
          0x2 - Unknown
          
          =================================================================
          Telemetry Dumper:
          =================================================================
          Pkilling 0x123145344360448x from 0x4620705216x
          Entering thread summarizer pause from 0x4620705216x
          Finished thread summarizer pause from 0x4620705216x.
          
          Waiting for dumping threads to resume
          
          =================================================================
          Basic Fault Address Reporting
          =================================================================
          Memory around native instruction pointer (0x10d0be868):0x10d0be858  49 c7 04 f9 00 00 00 00 48 63 bc b5 74 ff ff ff  I.......Hc..t...
          0x10d0be868  49 c7 04 f9 00 00 00 00 48 63 bc b5 78 ff ff ff  I.......Hc..x...
          0x10d0be878  49 c7 04 f9 00 00 00 00 48 63 bc b5 7c ff ff ff  I.......Hc..|...
          0x10d0be888  49 c7 04 f9 00 00 00 00 48 83 c6 04 48 39 f2 75  I.......H...H9.u
          
          =================================================================
          Managed Stacktrace:
          =================================================================
            at <unknown> <0xffffffff>
            at ConvTest:Main <0x00172>
            at <Module>:runtime_invoke_int <0x000a5>
          =================================================================
          Expected: 100
          Actual: 134
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/JIT/Methodical/NaN/r4nanconv_il_r/r4nanconv_il_r.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/JIT.Methodical/JIT.Methodical.XUnitWrapper.cs(62317,0): at JIT_Methodical._NaN_r4nanconv_il_r_r4nanconv_il_r_._NaN_r4nanconv_il_r_r4nanconv_il_r_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

### LINKED ISSUE #34391: CoreCLR tests on Mono runtime : crash running JIT/Methodical/NaN/r4nanconv_il_d/r4nanconv_il_d.sh
Crash seen when running the following CoreCLR test on the mono runtime from the dotnet\runtime repo.
Repro : Command to run individual tests : From the dotnet\runtime repo src\mono\netcore run this command or relevant one for a particular test - make run-tests-coreclr CoreClrTest="bash ../../artifacts/tests/coreclr/OSX.x64.Debug/JIT/Methodical/NaN/r4nanconv_il_d/r4nanconv_il_d.sh"

Crash report :

=================================================================
          External Debugger Dump:
          =================================================================
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/JIT/Methodical/NaN/r4nanconv_il_d/r4nanconv_il_d.sh: line 275: 82755 Abort trap: 6           $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
          
          Return code:      1
          Raw output file:      /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/JIT/Methodical/Reports/JIT.Methodical/NaN/r4nanconv_il_d/r4nanconv_il_d.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun r4nanconv_il_d.dll ''
          Based on bug #91021 - testing Single.NaN
          The conv.* instructions never throw overflow exceptions.  The results of the conversions is undefined for NaN.
          The conv.ovf.* instructions should throw OverflowException if the result can not be represented in the result type
          
          testcase 1 (conv.i1) : 0
          testcase 2 (conv.i2) : 0
          testcase 3 (conv.i4) : -2147483648
          testcase 4 (conv.i8) : -9223372036854775808
          testcase 5 (conv.r4) : NaN
          testcase 6 (conv.r8) : NaN
          testcase 7 (conv.u1) : 0
          testcase 8 (conv.u2) : 0
          testcase 9 (conv.u4) : 0
          testcase 10 (conv.u8) : 0
          testcase 11 (conv.i) : 0
          testcase 12 (conv.u) : 0
          
          =================================================================
          Native Crash Reporting
          =================================================================
          Got a segv while executing native code. This usually indicates
          a fatal error in the mono runtime or one of the native libraries 
          used by your application.
          =================================================================
          
          =================================================================
          Native stacktrace:
          =================================================================
          0x10584f4b2 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_dump_native_crash_info
          0x1057f1105 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_handle_native_crash
          0x105a18387 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : altstack_handle_and_restore.cold.1
          0x105849dee - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : altstack_handle_and_restore
          0x1057ab868 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_local_cprop
          0x10574aa02 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mini_method_compile
          0x10574cbbc - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_compile_method_inner
          0x1057509f2 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_compile_method_with_opt
          0x1057f3c1f - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : common_call_trampoline
          0x1057f3690 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_magic_trampoline
          0x105bd0393 - Unknown
          0x105f2a983 - Unknown
          0x105f2b9d6 - Unknown
          0x105754f9e - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_runtime_invoke
          0x10592a2c8 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_runtime_invoke_checked
          0x105930645 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_runtime_exec_main_checked
          0x1057af02c - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_jit_exec
          0x1057b2126 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : mono_main
          0x10582b589 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/libcoreclr.dylib : monovm_execute_assembly
          0x105709896 - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun : _Z22ExecuteManagedAssemblyPKcS0_S0_iPS0_
          0x10570818d - /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root/corerun : main
          0x7fff726fa7fd - /usr/lib/system/libdyld.dylib : start
          0x2 - Unknown
          
          =================================================================
          Telemetry Dumper:
          =================================================================
          Pkilling 0x123145511018496x from 0x4489084352x
          Entering thread summarizer pause from 0x4489084352x
          Finished thread summarizer pause from 0x4489084352x.
          
          Waiting for dumping threads to resume
          
          =================================================================
          Basic Fault Address Reporting
          =================================================================
          Memory around native instruction pointer (0x1057ab868):0x1057ab858  49 c7 04 f9 00 00 00 00 48 63 bc b5 74 ff ff ff  I.......Hc..t...
          0x1057ab868  49 c7 04 f9 00 00 00 00 48 63 bc b5 78 ff ff ff  I.......Hc..x...
          0x1057ab878  49 c7 04 f9 00 00 00 00 48 63 bc b5 7c ff ff ff  I.......Hc..|...
          0x1057ab888  49 c7 04 f9 00 00 00 00 48 83 c6 04 48 39 f2 75  I.......H...H9.u
          
          =================================================================
          Managed Stacktrace:
          =================================================================
            at <unknown> <0xffffffff>
            at ConvTest:Main <0x00172>
            at <Module>:runtime_invoke_int <0x000a5>
          =================================================================
          Expected: 100
          Actual: 134
          END EXECUTION - FAILED
          Test Harness Exitcode is : 1
          To run the test:
          > set CORE_ROOT=/Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/Tests/Core_Root
          > /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/JIT/Methodical/NaN/r4nanconv_il_d/r4nanconv_il_d.sh
          Expected: True
          Actual:   False
          Stack Trace:
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/artifacts/tests/coreclr/OSX.x64.Debug/TestWrappers/JIT.Methodical/JIT.Methodical.XUnitWrapper.cs(62220,0): at JIT_Methodical._NaN_r4nanconv_il_d_r4nanconv_il_d_._NaN_r4nanconv_il_d_r4nanconv_il_d_sh()
            /Users/samarthpatel/Documents/DotNetRunTime/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

### PR DESCRIPTION
**Pull request by fanyang-mono**
Two tests used to fail is passing now.
Fixes #34391
Fixes #34380

### CODE REVIEW

**Review by CoffeeFlux — COMMENTED** [review]
Do we know what commit fixed this?

We might want to wait until Nathan's CI PR goes in unless we know what fixed this or are sure it passes on all platforms. cc: @naricc

**Comment by CoffeeFlux** [comment]
Also, please try to make sure only one label is applied or else it will cause issues with the bot.

**Comment by fanyang-mono** [comment]
These two tests are fixed by https://github.com/dotnet/runtime/commit/7e739319e47505387d6644aba54df60f8c152c3b

**Comment by fanyang-mono** [comment]
> Do we know what commit fixed this?
> 
> We might want to wait until Nathan's CI PR goes in unless we know what fixed this or are sure it passes on all platforms. cc: @naricc

I've talked to Nathan, these issues were generated out of the results from his macOS run. He hadn't run coreclr tests on other platforms before. So I think we could treat these issues are for macOS only. Additionally, without removing it from the exclude list, tests won't run on CI, after Nathan enables them on CI. Thus, I think we should removing passing tests from exclude list. If they ever fail again on CI, new issues should be created with probably new failure syndromes.

**Review by CoffeeFlux — APPROVED** [review]
If we know what commit fixed them and we're only concerned about OSX for now, then this looks great, thanks!

**Comment by naricc** [comment]
Yeah, go ahead and merge this. I will be enabling CI this week, if they crop up again on other architectures I will sort it out (re add them and create new issues).

**Review by naricc — APPROVED** [review]

**Pull request merged**
