### PR TITLE
[System.Threading.Thread] Follow code style

### PR DESCRIPTION
**Pull request by lambdageek**
followup to https://github.com/dotnet/runtime/pull/68232

### CODE REVIEW

**Comment by ShreyasJejurkar** [comment]
Maybe we can put this rule in the global editor config!? And maybe severity to warning? 

Rule link => https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules#csharp_new_line_before_open_brace

**Comment by lambdageek** [comment]
> [Edited] The rule is already there, but it didn't warn? https://github.com/dotnet/runtime/blob/main/.editorconfig#L22

I don't use an editor that reads .editorconfig, or that displays compilation warnings.

But I'll try to build with warnings as errors next time I modify c# files.

**Comment by ShreyasJejurkar** [comment]
> > why CI didn't fail when the rule was violated?
> 
> Because we don't enforce every piece of guidance on style preference in the editorconfig; it is a _preference_, not a requirement.

umm ok. Got that. But shouldn't we follow a consistent style across the codebase? And warn users if they didn't follow?

**Comment by stephentoub** [comment]
> But shouldn't we follow a consistent style across the codebase?

If you're starting from scratch with a greenfield app, sure.  If you've got millions and millions of lines of code written by hundreds of developers over two decades following disparate guidelines for style, forcing every line of existing code to adhere to every one of the style preferences is not a high priority.

**Comment by ShreyasJejurkar** [comment]
Yessss, totally agree! 

On the other side, how I think about this one, is like if someone finds a violation we should create an issue on the repo with a `good-first-issue` label and explain there what needs to be done. That way we can fix violations (slowly-slowly) and can increase community contributions as well! Thoughts!?

**Comment by stephentoub** [comment]
> That way we can fix violations (slowly-slowly) and can increase community contributions as well!

Contributions that just move a brace from one line to the next aren't particularly interesting to us; we even ask that PRs just about style not be submitted:
https://github.com/dotnet/runtime/blob/main/CONTRIBUTING.md#dos-and-donts
"DON'T make PRs for style changes."

By rough search, there are ~34,000 cases of a `{` in the "wrong" place.  It's not a good use of anyone's time to proactively move those to their own line nor review PRs to do so, nor a good use of our CI resources to validate such changes.

**Comment by ShreyasJejurkar** [comment]
Hmm yeah. `~34,000` cases surely look like a lot of work. 

Thanks, Stephen for the clarification, appreciate it a lot! There is always a thing that I learn every single time I get a chance to chat with you!  😅🙌

**Pull request closed without merging**
