### PR TITLE
Handle case to update loop tables when preheader is removed 

### LINKED ISSUE #68756: Segfault inside JIT in libraries-jitstress
The libraries-jitstress job is hitting AVs/segfaults in a few tests, e.g. https://dev.azure.com/dnceng/public/_build/results?buildId=1746194&view=ms.vss-test-web.build-test-results-tab&runId=47150832&resultId=193742&paneView=debug.

It seems `curBlk` is null here:
https://github.com/dotnet/runtime/blob/71a73fb24c604818ce0a8d9a23659ebfe96431ad/src/coreclr/jit/optimizer.cpp#L342
which happens because `endBlk` is lexically before `begBlk`.

From bisection it was exposed by #68588.
cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by kunalspathak**
Context: https://github.com/dotnet/runtime/issues/68756#issuecomment-1115824211

Fixes: https://github.com/dotnet/runtime/issues/68756

### CODE REVIEW

**Comment by kunalspathak** [comment]
There are diffs that occurs because we have stopped down scaling the loop blocks in certain cases.

**Comment by jakobbotsch** [comment]
@dotnet/jit-contrib

**Comment by kunalspathak** [comment]
Ping. Can someone review this to unblock the clean libraries-jitstress?

**Review by jakobbotsch — APPROVED** [review]
This looks fine to me, but am not familiar with the code.

**Review by BruceForstall — APPROVED** [review]
LGTM.

It feels like this unmarking / unscaling still needs to be made more robust somehow.

**Comment by kunalspathak** [comment]
> It feels like this unmarking / unscaling still needs to be made more robust somehow.

Opened https://github.com/dotnet/runtime/issues/68844 to track it.

**Pull request merged**
