### PR TITLE
Enable FEATURE_PERFMAP on macOS/Darwin

### PR DESCRIPTION
**Pull request by kqr**
The idea of this is to solve issue #1227. It's inspired by PR #21179 and guided by subsequent changes to that configuration.

I have yet to test this more extensively, but before I do I would like opinions on whether I'm doing something terribly wrong.

### CODE REVIEW

**Comment by kqr** [comment]
I am encountering one problem when trying to build on macOS, which is

```
  [ 99%] Linking CXX shared library libcoreclr.dylib
  Undefined symbols for architecture x86_64:
    "_PAL_IgnoreProfileSignal", referenced from:
        PerfMap::Initialize() in libcee_wks.a(perfmap.cpp.o)
  ld: symbol(s) not found for architecture x86_64
```

I tried just blatantly commenting out the call to `PAL_IgnoreProfileSignal` in `PerfMap::Initialize()`, which made the code build, but that's obviously not the correct solution. I just can't figure out why it would be unknown – it does include `pal.h`, which does not seem to declare/define `PAL_IgnoreProfileSignal` conditionally.

**Comment by am11** [comment]
> Undefined symbols for architecture x86_64:

This is because the function is implemented within an #if, which is false in macOS. That condition is redundant as the function body is also using the same condition to make it a no-op on macOS.
You can cherry-pick https://github.com/am11/runtime/commit/148a72def488607e281247f38a651d2dc92bd73b to fix it, it is based on your branch.

**Comment by kqr** [comment]
Can't believe i didn't see the enclosing #if! Will take a look at it as soon as I'm at a real computer again. Exciting! Thank you so much.

**Comment by kqr** [comment]
Completely wrong place to ask but I'll shoot anyway: is there a way to build the CLR with a specific version? I.e. if I'm impatient and want to test this with a .NET Core 2.1 application, can I do that?

(Currently, `./dotnet.sh` obviously complains about not being able to run a `netcoreapp2.1` DLL since it's attempting to use framework version 5.0.0-alpha.1.19564.1.)

**Comment by kqr** [comment]
Hm. Regardless of the above, I tried creating a fresh `netcoreapp5.0` project with the following code:

```
namespace TestSymbolDump
{
    class Program
    {
        static void AckedMessage(string msg)
        {
            System.Console.WriteLine(msg);
            System.Console.WriteLine("Press return to acknowledge.");
            System.Console.ReadLine();
        }

        static void Main(string[] args)
        {
            AckedMessage("Hello World!");
            AckedMessage("Goodbye World!");
        }
    }
}
```

I built and ran it with this branch:

```
$ /Users/kqr/src/dotnet/runtime/dotnet.sh build
$ COMPlus_PerfMapEnabled=1 /Users/kqr/src/dotnet/runtime/dotnet.sh bin/Debug/netcoreapp5.0/TestSymbolDump.dll
```

but as far as I can tell, no JIT symbol dump is created. I tried concurrently running a DTrace tool to see which files it opens:

```
$ sudo opensnoop -n dotnet
  UID    PID COMM          FD PATH
  501  10927 dotnet         3 /dev/dtracehelper
  501  10927 dotnet         3 /Users/kqr/src/dotnet/runtime/.dotnet/host/fxr
  501  10927 dotnet         3 /Users/kqr/src/dotnet/runtime/.dotnet/host/fxr/5.0.0-alpha.1.19564.1/libhostfxr.dylib
  501  10927 dotnet         3 .
  501  10927 dotnet         3 /Users/kqr/tmp/TestSymbolDump/bin/Debug/netcoreapp5.0/TestSymbolDump.runtimeconfig.dev.json
  501  10927 dotnet         3 /Users/kqr/tmp/TestSymbolDump/bin/Debug/netcoreapp5.0/TestSymbolDump.runtimeconfig.json
  501  10927 dotnet         3 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App
  501  10927 dotnet         3 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/Microsoft.NETCore.App.deps.json
  501  10927 dotnet         3 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/libhostpolicy.dylib
  501  10927 dotnet         3 .
  501  10927 dotnet         3 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/Microsoft.NETCore.App.deps.json
  501  10927 dotnet         3 /Users/kqr/tmp/TestSymbolDump/bin/Debug/netcoreapp5.0/TestSymbolDump.deps.json
  501  10927 dotnet         3 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/libcoreclr.dylib
  501  10927 dotnet         3 /dev/dtracehelper
  501  10927 dotnet        -1 /etc/.mdns_debug
  501  10927 dotnet         3 /Users/kqr/src/dotnet/runtime/.dotnet/dotnet
  501  10927 dotnet         3 /dev/autofs_nowait
  501  10927 dotnet         4 /Users/kqr/.CFUserTextEncoding
  501  10927 dotnet         3 /dev/autofs_nowait
  501  10927 dotnet         4 /Users/kqr/.CFUserTextEncoding
  501  10927 dotnet        -1 /proc/self/mountinfo
  501  10927 dotnet        -1 /proc/self/mountinfo
  501  10927 dotnet        10 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/System.Private.CoreLib.dll
  501  10927 dotnet        12 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/libclrjit.dylib
  501  10927 dotnet        -1 /proc/self/mountinfo
  501  10927 dotnet        -1 /proc/self/mountinfo
  501  10927 dotnet        15 /Users/kqr/tmp/TestSymbolDump/bin/Debug/netcoreapp5.0/TestSymbolDump.dll
  501  10927 dotnet        17 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/System.Runtime.dll
  501  10927 dotnet        18 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/System.Console.dll
  501  10927 dotnet        19 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/System.Threading.dll
  501  10927 dotnet        20 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/System.Runtime.Extensions.dll
  501  10927 dotnet        21 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/System.Native.dylib
  501  10927 dotnet        22 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/System.Text.Encoding.Extensions.dll
  501  10927 dotnet        23 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/System.Globalization.Native.dylib
  501  10927 dotnet        23 /usr/share/icu/icudt62l.dat
  501  10927 dotnet        23 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/Microsoft.Win32.Primitives.dll
  501  10927 dotnet        -1 /Users/kqr/.terminfo/s/screen-256color
  501  10927 dotnet        -1 /Users/kqr/.terminfo/73/screen-256color
  501  10927 dotnet        -1 /etc/terminfo/s/screen-256color
  501  10927 dotnet        -1 /etc/terminfo/73/screen-256color
  501  10927 dotnet        -1 /lib/terminfo/s/screen-256color
  501  10927 dotnet        -1 /lib/terminfo/73/screen-256color
  501  10927 dotnet        -1 /usr/share/terminfo/s/screen-256color
  501  10927 dotnet        26 /usr/share/terminfo/73/screen-256color
  501  10927 dotnet        27 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/System.Collections.dll
  501  10927 dotnet        26 /Users/kqr/src/dotnet/runtime/.dotnet/shared/Microsoft.NETCore.App/5.0.0-alpha.1.19564.1/System.Runtime.InteropServices.dll
  501  10927 dotnet        -1 /var/folders/jm/yc3h9y856bgd8pq1d8xfpbzr0000gn/T/clr-debug-pipe-10927-1577976543-in
^C
```

but also that list does not contain a symbol map file. I feel like I could be missing something obvious here again...

**Comment by kqr** [comment]
(And I can confirm that it's not that all methods are being inlined or something silly like that – when I try to profile with DTrace I indeed get some method addresses in the recorded stack trace.)

**Comment by kqr** [comment]
Aha! If I try running the test project directly with `corerun` off of this branch:

```
$ COMPlus_PerfMapEnabled=1 /Users/kqr/src/dotnet/runtime/artifacts/bin/coreclr/OSX.x64.Debug/corerun bin/Debug/netcoreapp5.0/TestSymbolDump.dll
```

Then `opensnoop` tells me that indeed,

```

  501  11553 corerun        9 /private/var/folders/jm/yc3h9y856bgd8pq1d8xfpbzr0000gn/T/perf-11553.map
  501  11553 corerun       10 /private/var/folders/jm/yc3h9y856bgd8pq1d8xfpbzr0000gn/T/perfinfo-11553.map
```

there are symbol maps for the JITted code.

**Comment by kqr** [comment]
These symbols don't match the numbers I get out of DTrace though, but that could very well be unrelated. Unless someone else looks into it I can probably do it later.

**Comment by stephentoub** [comment]
@kqr, are you still actively working on this? The PR have seen activity in two months.

**Comment by kqr** [comment]
@stephentoub had a baby in the meantime so sort of got busy with other things, unfortunately. Not sure when I'll be able to get back to it.

**Comment by stephentoub** [comment]
@kqr, congratulations!  Given that you're not sure (very understandably) when you'll be able to get back to this, I'm going to close it.  Please feel free to open a new PR when you plan to continue working on it.  Thanks, and congrats, again.

**Comment by sdmaclea** [comment]
@kqr The two sets of addresses probably correlate to JIT generated code and crossgen generated code respectively.  The bulk of the managed runtime is `crossgen` during build.  This is essentially pre-compiling the code.  

This code does not create perfmap entries, but the `perfinfo-11553.map` file should describe where the crossgen files were loaded.  The crossgen executable has an option to dump the info necessary to construct perf-map entries.  IT might be disabled for macOS too though.

**Pull request closed without merging**
