### PR TITLE
Dummy commit

### PR DESCRIPTION
**Pull request by kunalspathak**

### CODE REVIEW

**Comment by stephentoub** [comment]
Sweet!

**Comment by DrewScoggins** [comment]
/benchmark microbenchmarks aspnet-perf-win runtime --variable filter=*Enum*

**Comment by sebastienros** [comment]
@DrewScoggins this PR is locked, the bot can't create comments anymore. Check this one where Stephen was able to run the bot: https://github.com/dotnet/runtime/pull/80753

**Pull request closed without merging**
