### PR TITLE
[mono] Clean up the delegate ctor code.

### PR DESCRIPTION
**Pull request by vargaz**
* Merge the virtual and non-virtual cases.
* Name variables etc. delegate info instead of delegate trampoline.
* Avoid setting the del->is_virtual field if its FALSE.

### CODE REVIEW

**Comment by vargaz** [comment]
It would be easier to review the commits one-by-one instead of the final diff.

**Comment by vargaz** [comment]
Failures are unrelated.

**Review by BrzVlad — APPROVED** [review]

**Pull request merged**
