### PR TITLE
JIT: fix count reconstruction problem

### LINKED ISSUE #100350: Assertion failed 'change >= 0'
https://dev.azure.com/dnceng-public/public/_build/results?buildId=620358&view=ms.vss-test-web.build-test-results-tab

libraries-jitstress test failure
System.Text.RegularExpressions.Tests Work Item
seemingly every platform

```
----- start Wed 03/27/2024  7:21:47.72 ===============  To repro directly: =====================================================
pushd C:\h\w\A5880934\w\9C2708EB\e\
"C:\h\w\A5880934\p\dotnet.exe" exec --runtimeconfig System.Text.RegularExpressions.Tests.runtimeconfig.json --depsfile System.Text.RegularExpressions.Tests.deps.json xunit.console.dll System.Text.RegularExpressions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\A5880934\w\9C2708EB\e>"C:\h\w\A5880934\p\dotnet.exe" exec --runtimeconfig System.Text.RegularExpressions.Tests.runtimeconfig.json --depsfile System.Text.RegularExpressions.Tests.deps.json xunit.console.dll System.Text.RegularExpressions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Text.RegularExpressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.RegularExpressions.Tests (found 327 of 358 test cases)
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on [4 threads], stop on fail = off)
    System.Text.RegularExpressions.Tests.RegexCompileToAssemblyTests.CompileToAssembly_SimpleUseInDebug [SKIP]
      Condition(s) not met: "IsDebugAndRemoteExecutorSupported"

Assert failure(PID 7060 [0x00001b94], Thread: 904 [0x0388]): Assertion failed 'change >= 0' in 'System.Text.RegularExpressions.CompiledRegexRunner:Regex5982_TryMatchAtCurrentPosition(System.Text.RegularExpressions.RegexRunner,System.ReadOnlySpan`1[ushort]):ubyte' during 'Profile incorporation' (IL size 77119; hash 0x346865ee; Tier0-MinOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\fgprofilesynthesis.cpp:1267
    Image: C:\h\w\A5880934\p\dotnet.exe

----- end Wed 03/27/2024  7:29:52.87 ----- exit code -1073740286 ----------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
In large methods with lots of irreducible loops we may find reconstructed counts reaching very large values.

Since profile counts in practice won't ever be much larger than say 10^12, detect when reconstructed counts exceed this value, and stop the algorithm.

We may eventually decide to rerun in "hard blend" mode where we intentionally limit the edge likelihood ranges. But this should do for now.

Closes #100350.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

No diffs expected

**Comment by AndyAyersMS** [comment]
Jitstress failure is timeout.

@BruceForstall looks like Jakob is away -- can you take a look?

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
