### PR TITLE
Delete unnecessary entry in global.json

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
Context: https://github.com/dotnet/runtime/pull/37948#discussion_r523810948

**Review by ViktorHofer — APPROVED** [review]

**Comment by danmosemsft** [comment]
```
2020-11-15T20:53:28.0203803Z F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-rc.2.20479.15\MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:F:\workspace\_work\1\s\artifacts\log\Checked\ToolsetRestore.binlog /clp:Summary /clp:ErrorsOnly;NoSummary /nr:False /p:ContinuousIntegrationBuild=True /p:TreatWarningsAsErrors=true /p:__ToolsetLocationOutputFile=F:\workspace\_work\1\s\artifacts\toolset\6.0.0-beta.20552.5.txt /t:__WriteToolsetLocation /warnaserror F:\workspace\_work\1\s\artifacts\toolset\restore.proj
2020-11-15T20:59:12.1105259Z F:\workspace\_work\1\s\artifacts\toolset\restore.proj : error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json.
2020-11-15T20:59:12.1107007Z F:\workspace\_work\1\s\artifacts\toolset\restore.proj : error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json.
2020-11-15T20:59:12.1108256Z F:\workspace\_work\1\s\artifacts\toolset\restore.proj : error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json.
2020-11-15T20:59:12.1109796Z F:\workspace\_work\1\s\artifacts\toolset\restore.proj : error : Failed to retrieve information about 'Microsoft.DotNet.Arcade.Sdk' from remote source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/a8a526e9-91b3-4569-ba2d-ff08dbb7c110/nuget/v3/flat2/microsoft.dotnet.arcade.sdk/index.json'.
2020-11-15T20:59:12.1112680Z F:\workspace\_work\1\s\artifacts\toolset\restore.proj : error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json.
2020-11-15T20:59:12.1114280Z F:\workspace\_work\1\s\artifacts\toolset\restore.proj : error : Failed to retrieve information about 'Microsoft.DotNet.Arcade.Sdk' from remote source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/a8a526e9-91b3-4569-ba2d-ff08dbb7c110/nuget/v3/flat2/microsoft.dotnet.arcade.sdk/index.json'.
2020-11-15T20:59:12.1116325Z F:\workspace\_work\1\s\artifacts\toolset\restore.proj : error : Unable to find package Microsoft.DotNet.Arcade.Sdk. No packages exist with this id in source(s): dotnet-eng, dotnet-tools, dotnet5, dotnet5-transport, dotnet6, dotnet6-transport, nuget.org
2020-11-15T20:59:12.1145750Z F:\workspace\_work\1\s\artifacts\toolset\restore.proj : error MSB4236: The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.
2020-11-15T20:59:12.1874550Z ##[error](NETCORE_ENGINEERING_TELEMETRY=Build) Build failed.
```
```
2020-11-15T21:10:10.8147106Z F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-rc.2.20479.15\NuGet.targets(131,5): error : Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json. [F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20552.5\tools\Tools.proj]
2020-11-15T21:10:10.8149596Z F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-rc.2.20479.15\NuGet.targets(131,5): error :   Response status code does not indicate success: 429 (). [F:\workspace\_work\1\s\.packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.20552.5\tools\Tools.proj]
2020-11-15T21:10:10.8211349Z ##[error].dotnet\sdk\5.0.100-rc.2.20479.15\NuGet.targets(131,5): error : (NETCORE_ENGINEERING_TELEMETRY=Restore) Unable to load the service index for source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json.
  Response status code does not indicate success: 429 ().
```

**Comment by ViktorHofer** [comment]
See pinned issue: https://github.com/dotnet/runtime/issues/44700 and mail that I just sent out.

**Review by stephentoub — APPROVED** [review]

**Comment by akoeplinger** [comment]
This was used to prevent merge conflicts when darc updates both Microsoft.DotNet.SharedFramework.Sdk and Microsoft.NET.Sdk.IL in update PRs. Does this no longer happen?

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/runtime/pull/37948#discussion_r523810948

**Pull request merged**
