### PR TITLE
Handle multiple incoming connection at the beginning of Http3LoopbackConnection use

### LINKED ISSUE #69387: Failure in SocketsHttpHandlerTest_Http3_MsQuic.SendMoreThanStreamLimitRequestsConcurrently_LastWaits: The server returned an invalid or unrecognized response
Seen in testing for #69180
Pipeline run: https://dev.azure.com/dnceng/public/_build/results?buildId=1768597&view=results
Job name: Libraries Test Run release coreclr windows x86 Release
Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-69180-merge-b767a309ee8c4fe793/System.Net.Http.Functional.Tests/3/console.751e2bba.log?helixlogtype=result

```scala
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http3_MsQuic.SendMoreThanStreamLimitRequestsConcurrently_LastWaits(streamLimit: 1000) [FAIL]
      System.AggregateException : One or more errors occurred. (The server returned an invalid or unrecognized response.) (Expected single request stream, got a second
      Expected: True
      Actual:   False)
      ---- System.Net.Http.HttpRequestException : The server returned an invalid or unrecognized response.
      ---- Expected single request stream, got a second
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(88,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(276,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits(Int32 streamLimit)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace #1 (System.Net.Http.HttpRequestException) -----
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(319,0): at System.Net.Http.Http3RequestStream.ReadResponseAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(297,0): at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(297,0): at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs(248,0): at System.Net.Http.Http3Connection.SendAsync(HttpRequestMessage request, Int64 queueStartingTimestamp, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(963,0): at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1004,0): at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(30,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(558,0): at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(268,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass6_0.<<SendMoreThanStreamLimitRequestsConcurrently_LastWaits>b__1>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(128,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        ----- Inner Stack Trace #2 (Xunit.Sdk.TrueException) -----
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackConnection.cs(158,0): at System.Net.Test.Common.Http3LoopbackConnection.AcceptRequestStreamAsync()
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(191,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass6_0.<<SendMoreThanStreamLimitRequestsConcurrently_LastWaits>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(128,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
```

### PR DESCRIPTION
**Pull request by rzikm**
Fixes #69387.

This PR makes sure the `Http3LoopbackConnection` used in tests does not choke on multiple simultaneous requests from a client, when two or more request streams are accepted before the control stream.

The Http functional tests were run in a tight loop and the original test failure was not observed.

### CODE REVIEW

**Comment by rzikm** [comment]
cc: @ManickaP

**Comment by ManickaP** [comment]
Was the problem that not all unidirectional streams were the one and only control stream?

**Review by CarnaViire — COMMENTED** [review]
In general LGTM, but the only question is whether any synchronization needed over _delayedStreams access... can AcceptRequestStreamAsync ever be called concurrently? it feels like it might be...

**Comment by rzikm** [comment]
> Was the problem that not all unidirectional streams were the one and only control stream?

No, the problem was that client started multiple requests and it happened that two (or more) request streams arrived before the control stream.

**Comment by rzikm** [comment]
> In general LGTM, but the only question is whether any synchronization needed over _delayedStreams access... can AcceptRequestStreamAsync ever be called concurrently? it feels like it might be...

It does not seem that we are accepting multiple requests concurrently in any test. There are other parts of the simple loopback server that were not thread safe before (such as setting the `_currentStream` and `_currentStreamId`). Making it all threadsafe would require bigger changes and likely redesign of the class/tests.

**Review by CarnaViire — APPROVED** [review]
Ok. If Http3LoopbackConnection is not thread-safe in general, I'm fine with this.
LGTM. Thanks!

**Pull request merged**
