### PR TITLE
Reapply keyword `params`

### LINKED ISSUE #77873: [API Proposal]: params ReadOnlySpan<T> overloads for existing params T[] overloads
EDITED 1/31/2024 by @stephentoub 

**Adding params to existing spans:**
```C#
namespace System
{
    public static class MemoryExtensions
    {
        public static bool TryWrite(this Span<char> destination, IFormatProvider? provider, CompositeFormat format, out int charsWritten, **params** ReadOnlySpan<object?> args);
    }
    public class String
    {
        public static string Format(IFormatProvider? provider, CompositeFormat format, **params** ReadOnlySpan<object?> args);
    }
}
namespace System.Collections.Generic
{
    public static class CollectionExtensions
    {
        public static void AddRange<T>(this List<T> list, **params** ReadOnlySpan<T> source);
        public static void InsertRange<T>(this List<T> list, int index, **params** ReadOnlySpan<T> source);
    }
}
namespace System.Collections.Immutable
{
    public static class ImmutableArray
    {
        public static ImmutableArray<T> Create<T>(**params** ReadOnlySpan<T> items);
    }
    public struct ImmutableArray<T>
    {
        public ImmutableArray<T> AddRange(**params** ReadOnlySpan<T> items);
        public ImmutableArray<T> InsertRange(int index, **params** ReadOnlySpan<T> items);

        public sealed class Builder
        {
            public void AddRange(**params** ReadOnlySpan<T> items);
            public void AddRange<TDerived>(**params** ReadOnlySpan<TDerived> items) where TDerived : T;
        }
    }
    public static class ImmutableHashSet
    {
        public static ImmutableHashSet<T> Create<T>(**params** ReadOnlySpan<T> items);
        public static ImmutableHashSet<T> Create<T>(IEqualityComparer<T>? equalityComparer, **params** ReadOnlySpan<T> items);
    }
    public static class ImmutableList
    {
        public static ImmutableList<T> Create<T>(**params** ReadOnlySpan<T> items);
    }
    public static class ImmutableQueue
    {
        public static ImmutableQueue<T> Create<T>(**params** ReadOnlySpan<T> items);
    }
    public static class ImmutableSortedSet
    {
        public static ImmutableSortedSet<T> Create<T>(**params** ReadOnlySpan<T> items);
        public static ImmutableSortedSet<T> Create<T>(IComparer<T>? comparer, **params** ReadOnlySpan<T> items)
    }
    public static class ImmutableStack
    {
        public static ImmutableStack<T> Create<T>(**params** ReadOnlySpan<T> items);
    }
}
namespace System.Diagnostics.Metrics
{
    public sealed class Counter<T> : Instrument<T> where T : struct
    {
        public void Add(T delta, **params** ReadOnlySpan<KeyValuePair<string, object?>> tags);
    }
    public sealed class Histogram<T> : Instrument<T> where T : struct
    {
        public void Record(T value, **params** ReadOnlySpan<KeyValuePair<string, object?>> tags);
    }
    public readonly struct Measurement<T> where T : struct
    {
        public Measurement(T value, **params** ReadOnlySpan<KeyValuePair<string, object?>> tags);
    }
    public struct TagList : IList<KeyValuePair<string, object?>>, IReadOnlyList<KeyValuePair<string, object?>>
    {
        public TagList(**params** ReadOnlySpan<KeyValuePair<string, object?>> tagList);
    }
    public sealed class UpDownCounter<T> : Instrument<T> where T : struct
    {
        public void Add(T delta, **params** ReadOnlySpan<KeyValuePair<string, object?>> tags);
    }
}
namespace System.Text
{
    public sealed class StringBuilder
    {
        public StringBuilder AppendFormat(IFormatProvider? provider, CompositeFormat format, **params** ReadOnlySpan<object?> args);
    }
}
```

**Adding new params span-based overloads (all of these have an existing corresponding `params T[]`):**
```C#
namespace System
{
    public static class Console
    {
        public static void Write([StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> arg);
        public static void WriteLine([StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> arg);
    }
    public abstract class Delegate
    {
        public static Delegate? Combine(params ReadOnlySpan<Delegate?> delegates);
    }
    public class String
    {
        public static string Concat(params ReadOnlySpan<object?> args);
        public static string Concat(params ReadOnlySpan<string?> values);
        public static string Format([StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> args);
        public static string Format(IFormatProvider? provider, [StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> args);
        public static string Join(char separator, params ReadOnlySpan<string?> value);
        public static string Join(string? separator, params ReadOnlySpan<string?> value);
        public static string Join(char separator, params ReadOnlySpan<object?> values);
        public static string Join(string? separator, params ReadOnlySpan<object?> values);
        public string[] Split(params ReadOnlySpan<char> separator);
        public unsafe string Trim(params ReadOnlySpan<char> trimChars);
        public unsafe string TrimStart(params ReadOnlySpan<char> trimChars);
        public unsafe string TrimEnd(params ReadOnlySpan<char> trimChars);
    }
}
namespace System.CodeDom.Compiler
{
    public class IndentedTextWriter : TextWriter
    {
        public override void Write([StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> arg);
        public override void WriteLine([StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> arg);
    }
}
namespace System.IO
{
    public static class Path
    {
        public static string Combine(params ReadOnlySpan<string> paths);
        public static string Join(params ReadOnlySpan<string?> paths);
    }
    public class StreamWriter : TextWriter
    {
        public override void Write([StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> arg);
        public override void WriteLine([StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> arg);
    }
    public abstract class TextWriter
    {
        public virtual void Write([StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> arg);
        public virtual void WriteLine([StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> arg);
    }
}
namespace System.Text
{
    public class StringBuilder
    {
        public StringBuilder AppendJoin(string? separator, params ReadOnlySpan<object?> values);
        public StringBuilder AppendJoin(string? separator, params ReadOnlySpan<string?> values);
        public StringBuilder AppendJoin(char separator, params ReadOnlySpan<object?> values);
        public StringBuilder AppendJoin(char separator, params ReadOnlySpan<string?> values);
        public StringBuilder AppendFormat([StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> args);
        public StringBuilder AppendFormat(IFormatProvider? provider, [StringSyntax(StringSyntaxAttribute.CompositeFormat)] string format, params ReadOnlySpan<object?> args);
    }
}
namespace System.Text.Json.Nodes
{
    public sealed class JsonArray
    {
        public JsonArray(params ReadOnlySpan<JsonNode?> items);
        public JsonArray(JsonNodeOptions options, params ReadOnlySpan<JsonNode?> items);
    }
}
namespace System.Text.Json.Serialization.Metadata
{
        public static IJsonTypeInfoResolver Combine(params ReadOnlySpan<IJsonTypeInfoResolver?> resolvers);
}
namespace System.Threading
{
    public class CancellationTokenSource
    {
        public static CancellationTokenSource CreateLinkedTokenSource(params ReadOnlySpan<CancellationToken> tokens);
    }
    public class Task
    {
        public static void WaitAll(params ReadOnlySpan<Task> tasks);
        public static Task WhenAll(params ReadOnlySpan<Task> tasks);
        public static Task<TResult[]> WhenAll<TResult>(params ReadOnlySpan<Task<TResult>> tasks);
        public static Task<Task> WhenAny(params ReadOnlySpan<Task> tasks);
        public static Task<Task<TResult>> WhenAny<TResult>(params ReadOnlySpan<Task<TResult>> tasks);
    }
}
```

---

### Background and motivation

C# 12 is tentatively on a path to add support for `params ReadOnlySpan<T>`, and for that to take precedence over `params T[]`.  That means in APIs where we currently have a `params T[]`-based overload, there’s a benefit to us adding a `params ReadOnlySpan<T>` overload: it’ll be preferred by the compiler, and the compiler will aim to stackalloc the span rather than using an array.  As a result, any existing call sites for the params-based overload will, upon recompilation, switch to the span-based overload and allocate less.

(It's likely that params in general will be de-emphasized once collection literals also comes to the scene, hopefully also in C# 12. As such, the benefits of adding params here would primarily be about making existing code more efficient.  I've not included in this write-up other places we might want additional span-based overloads where there aren't already `params T[]`-based overloads; we can continue adding such APIs via separate, dedicated proposals.)

### API Proposal

This is a rough strawman, to be refined as the language features are refined.
```
ImmutableHashSet:
public static ImmutableHashSet<T> Create<T>(params ReadOnlySpan<T> items);
public static ImmutableHashSet<T> Create<T>(IEqualityComparer<T>? comparer, params ReadOnlySpan<T> items) ;

ImmutableList :
public static ImmutableList<T> Create<T>(params ReadOnlySpan<T> items);

ImmutableQueue:
public static ImmutableQueue<T> Create<T>(params ReadOnlySpan<T> items);

ImmutableSortedSet:
public static ImmutableSortedSet<T> Create<T>(params ReadOnlySpan<T> items);
public static ImmutableSortedSet<T> Create<T>(IComparer<T>? comparer, params ReadOnlySpan<T> items) ;

ImmutableStack:
public static ImmutableStack<T> Create<T>(params ReadOnlySpan<T> items);

Console:
public static void Write(string format, params ReadOnlySpan<object?> arg);
public static void WriteLine(string format, params ReadOnlySpan<object?> arg);

Activator:
public static object? CreateInstance(Type type, params ReadOnlySpan<object?> args);

String:
public static string Concat(params ReadOnlySpan<object?> args);
public static string Concat(params ReadOnlySpan<string?> args);
public static string Format(string format, params ReadOnlySpan<object?> args);
public static string Format(IFormatProvider? provider, string format, params ReadOnlySpan<object?> args);
public static string Join(char separator, params ReadOnlySpan<object?> values);
public static string Join(char separator, params ReadOnlySpan<string?> values);
public static string Join(string?  separator, params ReadOnlySpan<object?> values);
public static string Join(string? separator, params ReadOnlySpan<string?> values);

Path:
public static string Combine(params ReadOnlySpan<string> paths);
public static string Join(params ReadOnlySpan<string> paths);

TextWriter (and derived types with overrides):
public virtual void Write(string format, params ReadOnlySpan<object?> arg);
public virtual void WriteLine(string format, params ReadOnlySpan<object?> arg);

StringBuilder:
public StringBuilder AppendFormat(string format, params ReadOnlySpan<object?> args);
public StringBuilder AppendJoin(char separator, params ReadOnlySpan<object?> values);
public StringBuilder AppendJoin(char separator, params ReadOnlySpan<string?> values);
public StringBuilder AppendJoin(string? separator, params ReadOnlySpan<object?> values);
public StringBuilder AppendJoin(string? separator, params ReadOnlySpan<object?> values);

CancellationTokenSource:
public static CancellationTokenSource CreateLinkedTokenSource(params ReadOnlySpan<CancellationToken> cancellationToken);

Task:
public static void WaitAll(params ReadOnlySpan<Task> tasks);
public static int WaitAny(params ReadOnlySpan<Task> tasks);
public static Task WhenAll(params ReadOnlySpan<Task> tasks);
public static Task<TResult[]> WhenAll<TResult>(params ReadOnlySpan<Task<TResult>[] tasks);
public static Task<Task> WhenAny(params ReadOnlySpan<Task> tasks);
public static Task<Task<TResult>> WhenAny<TResult>(params ReadOnlySpan<Task<TResult>[] tasks);

JsonArray:
public JsonArray(JsonNodeOptions options, params ReadOnlySpan<JsonNode?> items);
public JsonArray(params ReadOnlySpan<JsonNode?> items);

LoggerExtensions:
All of the BeginScope, Log, LogCritical, LogDebug, LogError, LogInformation, LogTrace, and LogWarning overloads already there, just with `params ReadOnlySpan<object?> args` instead of `params object?[] args`.

```

Additionally, the following already have `ReadOnlySpan<T>`-based overloads where there's also a `params T[]`-based overload, so we'd just need to add `params` to the existing method:

```
ImmutableArray:
public static System.Collections.Immutable.ImmutableArray<T> Create<T>( ReadOnlySpan<T> items);

ImmutableArray<T>.Builder:
public void AddRange(ReadOnlySpan<T> items);

Counter<T> (metrics)
public void Add(T delta, ReadOnlySpan<KeyValuePair<string, object?> tags);

UpDownCounter<T> (metrics)
public void Add(T delta, ReadOnlySpan<KeyValuePair<string, object?> tags);

Histogram<T> (metrics)
public void Record(T value, ReadOnlySpan<KeyValuePair<string, object?> tags);

Measurement<T> (metrics)
public Measurement(T value, ReadOnlySpan<KeyValuePair<string, object?> tags);
```

### API Usage

Existing usage.

### Alternative Designs

_No response_

### Risks

_No response_

### LINKED ISSUE #101261: Reevaluate `params ReadOnlySpan<string>` overloads from #77873
Existing compiler rules make that types that define implicit operators for string and string[] incur in a source breaking change. 
Example:
```cs
class Program
{
    static void Main()
    {
        var c = new C();
        Join(",", c); // error CS0121: The call is ambiguous between the following methods or properties: 'Program.Join(string, params string[])' and 'Program.Join(string, params ReadOnlySpan<string>)'
    }

    public static string Join(string separator, params string[] value) => "array";

    public static string Join(string separator, params ReadOnlySpan<string> value) => "span";
}

class C
{
    public static implicit operator string(C c) => "c";

    public static implicit operator string[](C c) => ["c"];
}
```

One real-world example is `Microsoft.Extensions.Primitives.StringValues` which is passed into `string.Join(string, string[])` on aspnetcore, and that it [failed to compile](https://github.com/dotnet/aspnetcore/pull/55010#issuecomment-2059328494) when the changes in https://github.com/dotnet/runtime/pull/100898 flowed into their repo.

## API Proposal

Not quite a new API proposal, but a proposal for keeping as is the APIs on https://github.com/dotnet/runtime/issues/77873.
These APIs would make existing callsites of their analogous `params string[]` overloads to fail if a `StringValues` is being passed as argument.
```
System.String.Concat(params ReadOnlySpan<string?> values)
System.String.Join(char separator, params ReadOnlySpan<string?> value)
System.String.Join(string? separator, params ReadOnlySpan<string?> value)
System.IO.Path.Combine(params ReadOnlySpan<string> paths)
System.IO.Path.Join(params ReadOnlySpan<string?> paths)
System.Text.StringBuilder.AppendJoin(string? separator, params ReadOnlySpan<string?> values)
System.Text.StringBuilder.AppendJoin(char separator, params ReadOnlySpan<string?> values)
```

Considering that having the ambiguity of string and string[] implicit operators feels like is against FDGs 5.7.2 Conversion Operators
> DO NOT provide a conversion operator if such a conversion is not clearly expected by the end users.

I think the best path would be to accept the source breaking change and expect users to update their codebase, preferably picking the new `ReadOnlySpan<string>` overloads.

## Alternatively
@dotnet/roslyn  could the compiler rules be adjusted to accommodate `StringValues`? Why adding a `public static implicit operator ReadonlySpan<string>` to `StringValues` doesn't make the compiler select `string.Join(string, ReadonlySpan<string>)`? It does make the error go away, though, by selecting the `string[]` overload.

### PR DESCRIPTION
**Pull request by jozkee**
Closes https://github.com/dotnet/runtime/issues/101261.
Closes https://github.com/dotnet/runtime/issues/77873.

Continuation of https://github.com/dotnet/runtime/pull/101308.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by Jozkee** [comment]
source breaking?

**Comment by stephentoub** [comment]
Can you elaborate?

**Comment by Jozkee** [comment]
There's a case where a collection expression can't resolve between ROS<string> and ROS<object>, see https://github.com/dotnet/sdk/pull/41089#issuecomment-2125223825. This may be a compiler bug. 

Additionally, do we not want to document cases of types with conditions similar to StringValues?

**Comment by cston** [comment]
> There's a case where a collection expression can't resolve between `ROS<string>` and `ROS<object>`, see https://github.com/dotnet/sdk/pull/41089#issuecomment-2125223825. It may be a compiler bug, though.

Currently, the [*better conversion*](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/collection-expressions.md#overload-resolution) rules for collection expressions treat this case as ambiguous.

Perhaps there should be an additional rule to prefer `System.ReadOnlySpan<E₁>` over `System.ReadOnlySpan<E₂>` if an implicit conversion exists from `E₁` to `E₂`.

**Comment by stephentoub** [comment]
> > There's a case where a collection expression can't resolve between `ROS<string>` and `ROS<object>`, see [dotnet/sdk#41089 (comment)](https://github.com/dotnet/sdk/pull/41089#issuecomment-2125223825). It may be a compiler bug, though.
> 
> Currently, the [_better conversion_](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/collection-expressions.md#overload-resolution) rules for collection expressions treat this case as ambiguous.
> 
> Perhaps there should be an additional rule to prefer `System.ReadOnlySpan<E₁>` over `System.ReadOnlySpan<E₂>` if an implicit conversion exists from `E₁` to `E₂`.

I thought that was part of the first-class span support. Is it not, @333fred?

**Comment by cston** [comment]
> > Perhaps there should be an additional rule to prefer `System.ReadOnlySpan<E₁>` over `System.ReadOnlySpan<E₂>` if an implicit conversion exists from `E₁` to `E₂`.
> 
> I thought that was part of the first-class span support. Is it not, @333fred?

Unfortunately, implicit conversions from first-class span support may not be sufficient for a collection expression argument since implicit conversions are only considered in [*better conversion*](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/collection-expressions.md#overload-resolution) when the types are *not span types*.

> > * `E` is a *collection expression* and one of the following holds:
> >   * ...
> >   * `T₁` is not a *span_type*, and `T₂` is not a *span_type*, and an implicit conversion exists from `T₁` to `T₂`

**Comment by cston** [comment]
> Currently, the [_better conversion_](https://github.com/dotnet/csharplang/blob/main/proposals/csharp-12.0/collection-expressions.md#overload-resolution) rules for collection expressions treat this case as ambiguous.

This is tracked by https://github.com/dotnet/roslyn/issues/73857.

**Comment by jozkee** [comment]
Note for breaking change doc: If this ship as is, it should be pointed out that `string.Trim*(params ROS<char>)` will hide [extension methods](https://github.com/search?q=%2Fpublic+static+string+TrimEnd%5C%28this+string+%5Ba-zA-Z%5D%2B%2C+string+%5Ba-zA-Z%5D%2B%5C%29%2F+language%3AC%23&type=code) which usually match the whole sequence while the one added here matches any of the characters.

See https://github.com/dotnet/runtime/issues/102822#issuecomment-2137679624.

**Pull request merged**
