### PR TITLE
Use unique IL assembly names instead of automatic renaming

### PR DESCRIPTION
**Pull request by markples**
The main motivation for this is that I got stuck trying to write documentation for test merging and test suffixes.  We have _il_d for IL and both _d and _cs_d for C# (and similar for _r and others - I'll use _d to denote all such tests here).  Only the IL files needed to be separated into different merged groups, yet we split the C# as well.

This change renames the _il_d to just _d (unless there is already an existing _d, likely for a C# version of the test).  It then replaces `.assembly <name>` with `.assembly ASSEMBLY_NAME` and adds per-configuration "prefix" IL source files with `#define ASSEMBLY_NAME <name>_d`.  Then the rules are simple - tests have unique assembly names and no build-time renaming is required.

This lets me remove the 4 Regression merged groups with ~10 tests each in them.  I rebalanced the merged groups where the number of _d tests were larger except HardwareIntrinsics (a unique directory) and Methodical (most of the tests are _d).

### CODE REVIEW

**Comment by markples** [comment]
PTAL @trylek @jkoritzinsky 
cc @dotnet/jit-contrib 

The github view on this is pretty bad between the large number of files and missing the renames.  The commits are logically separated:
- [Regression diff is small and instructive](https://github.com/dotnet/runtime/pull/85185/commits/d9cf73bfdf7abbfad3841ac406c93a035091a237)
- The 3 marked "new il scheme for xxx - no merged group updates" are tool-written and do the il/ilproj changes.  [Methodical](https://github.com/dotnet/runtime/pull/85185/commits/e70f7681abcde29725c7de1b49b9e002011458eb), [Directed](https://github.com/dotnet/runtime/pull/85185/commits/05d9f26b795b9abd4c1f192f5a8a17b39f4fa4ef), [jit64](https://github.com/dotnet/runtime/pull/85185/commits/15874460f25de7cdf42447126d7052112b20c92d)
- [Two cases that use DebugType "Impl" that we don't have a convention for - updated manually](https://github.com/dotnet/runtime/pull/85185/commits/5d9dba0099334634395ff692f9c16707d4addb2e)
- The 2 marked "merged group updates" are small as they only modify the merged groups, not the individual tests. [Directed](https://github.com/dotnet/runtime/pull/85185/commits/d1de5e96b534bea0489cbac72b10899acf2a1171), [jit64](https://github.com/dotnet/runtime/pull/85185/commits/d990be1141d01331f93d1a8fe4b4c6dfe6f9fc92)
- With all of the above in place, we can [stop rewriting the IL assembly names and the filename convention](https://github.com/dotnet/runtime/pull/85185/commits/226da73d7ac51f4543ab37581064e1ab8cec1262)

**Comment by markples** [comment]
A local pri 1 build/run showed that I didn't lose swaths of tests.  I'll run outerloop, extraplatforms, and gcstress - the last after my jit64 changes are merged.

**Review by trylek — APPROVED** [review]
Thanks Mark, this indeed looks much cleaner than the hacky assembly renames in the scripts. It almost makes me wonder whether there might be a way to define the <code>ASSEMBLY_NAME</code> macro directly in the MSBuild script so that we don't need the auxiliary one-line IL files but I guess I'm probably asking too much, this is a nice improvement by itself already.

**Comment by markples** [comment]
(just retesting because old runs were old and noisy, no new changes requiring re-review)

**Comment by markples** [comment]
MemorySsa is failing elsewhere

**Pull request merged**
