### PR TITLE
[NativeAOT] Enable smoke tests on macOS

### PR DESCRIPTION
**Pull request by filipnavara**

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
```
runtime Successful in 2m — Build #20221003.56 succeeded
```

That's a bit suspicious. I'm going to close and reopen to poke the CI.

**Review by MichalStrehovsky — APPROVED** [review]
LGTM if the CI is green! Thank you!

**Comment by MichalStrehovsky** [comment]
CI is not triggering - this is blocked on https://github.com/dotnet/runtime/pull/76057#issuecomment-1266509928.

Cc @radical 

Marking no merge so that nobody thinks it's green.

**Comment by filipnavara** [comment]
I think I know what causes the failure, will check it in the morning.

**Comment by filipnavara** [comment]
This is blocked on ingesting newer SDK that has https://github.com/dotnet/installer/pull/14464 (7.0) or https://github.com/dotnet/installer/pull/14443 (8.0).

**Comment by filipnavara** [comment]
The SDK has been updated, so I rebased the PR.

**Comment by filipnavara** [comment]
...and the CI passed successfully this time.

**Pull request merged**
