### PR TITLE
[LoongArch64] fix the errors for mod/div after #82924.

### PR DESCRIPTION
**Pull request by shushanhf**
This PR is part of the issue https://github.com/dotnet/runtime/issues/69705 to amend the LA's port.

This should be merged after the #85085 to avoid conflict.

### CODE REVIEW

**Comment by shushanhf** [comment]
Hi, @jakobbotsch 
I have tested this PR, could you please review this PR?
Thanks

**Comment by shushanhf** [comment]
> Hi, @jakobbotsch I have tested this PR, could you please review this PR? Thanks

@BruceForstall @jakobbotsch 

could you please review this PR?

As https://github.com/dotnet/runtime/pull/82294 , the RISCV64 is based on LoongArch64,  the RISCV64 is so similarity with LoongArch64.

What do you mean? 
Is it that I have to fix the errors also for RISCV64 before you review this PR?

**Review by jakobbotsch — APPROVED** [review]

**Comment by jakobbotsch** [comment]
> As #82294 , the RISCV64 is based on LoongArch64, the RISCV64 is so similarity with LoongArch64.
> 
> What do you mean? Is it that I have to fix the errors also for RISCV64 before you review this PR? If needed, I can do it but I can just tested it on the LA64's PC as I don't have the RISCV64's env.

If you have the extra cycles to fix RISC-V too then you should definitely feel free to include it in your change. You can also tag the RISC-V folks on your changes to make them aware that RISC-V may need similar fixes in the cases where RISC-V was based on LA64.

**Comment by shushanhf** [comment]
> > As #82294 , the RISCV64 is based on LoongArch64, the RISCV64 is so similarity with LoongArch64.
> > What do you mean? Is it that I have to fix the errors also for RISCV64 before you review this PR? If needed, I can do it but I can just tested it on the LA64's PC as I don't have the RISCV64's env.
> 
> If you have the extra cycles to fix RISC-V too then you should definitely feel free to include it in your change. You can also tag the RISC-V folks on your changes to make them aware that RISC-V may need similar fixes in the cases where RISC-V was based on LA64.

At least most releated RISCV64 PRs is OK, but  I can't test the RISCV64 while the LA64 had been tested.

**Comment by shushanhf** [comment]
> > As #82294 , the RISCV64 is based on LoongArch64, the RISCV64 is so similarity with LoongArch64.
> > What do you mean? Is it that I have to fix the errors also for RISCV64 before you review this PR? If needed, I can do it but I can just tested it on the LA64's PC as I don't have the RISCV64's env.
> 
> If you have the extra cycles to fix RISC-V too then you should definitely feel free to include it in your change. You can also tag the RISC-V folks on your changes to make them aware that RISC-V may need similar fixes in the cases where RISC-V was based on LA64.

At least most releated RISCV64 PRs is OK, but  I can test the RISCV64 while the LA64 had been tested.

**Pull request merged**
