### PR TITLE
Add OperatingSystem ILLink.Substitutions for Browser.

### PR DESCRIPTION
**Pull request by eerhardt**
We can add more platforms in the future once this TODO gets fixed:

https://github.com/dotnet/runtime/blob/096578ed4e9595eb2aba9cb5f7aecfe4aed32ecf/src/libraries/System.Private.CoreLib/src/System.Private.CoreLib.Shared.projitems#L31

### CODE REVIEW

**Comment by eerhardt** [comment]
fyi @adamsitnik - since you are familiar with these APIs.

**Comment by adamsitnik** [comment]
> since you are familiar with these APIs.

is this basically telling the linker that if `IsBrowser` returns true then all other methods return false and can get eliminated? nice!

**Review by vitek-karas — APPROVED** [review]

**Comment by vitek-karas** [comment]
@adamsitnik yes - that's exactly what it does :wink:

**Comment by eerhardt** [comment]
I re-thought this whole thing and tested it. The linker will already do "constant-return value" trimming by default because of the way these APIs are already implemented. Since the existing `OperatingSystem.IsXXX()` methods already return a constant - the linker will substitute this constant and trim any unused code today:

For example:

https://github.com/dotnet/runtime/blob/af03b0450e8dfcc196c69cfc8149701080d61e7e/src/libraries/System.Private.CoreLib/src/System/Globalization/GlobalizationMode.Unix.cs#L14-L38

will get linked into:

image

(Note the call to `Environment.FailFast` gets linked away.)

So the only real value of this change is the `OperatingSystem.IsXXXVersionAtLeast(int, int, int)` methods, which we don't call ourselves. I think I should just close this, as the linker is already smart enough without this change.

**Comment by adamsitnik** [comment]
@eerhardt why the linker is not removing the call to `IsBrowser()`? it's known to return true and has no side-effects?

image

**Comment by am11** [comment]
In GetGlobalizationInvariantMode, shouldn't it also keep IsBrowser in the condition and:

```c#
                 string message = "Couldn't find a valid ICU package installed on the system. " + 
                                 "Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support."; 
                 Environment.FailFast(message); 
```

**Comment by eerhardt** [comment]
> why the linker is not removing the call to IsBrowser()? it's known to return true and has no side-effects?

https://github.com/mono/linker/issues/1113

> In GetGlobalizationInvariantMode, shouldn't it keep IsBrowser in the condition

In the above linked code, I was publishing a Blazor WASM app, so `IsBrowser()` will always return `true`. The above condition is `if (loaded == 0 && !OperatingSystem.IsBrowser()) `. So `!IsBrowser()` will always be `false`. This allows the linker to trim dead code.

**Comment by vitek-karas** [comment]
Linker intentionally keeps the calls which are part of the condition:
* Makes debugging easier (the method still exists and one can set a breakpoint to it and it will get hit for example)
* Linker doesn't have detection for pure methods (not even the simple ones) - so currently it assumes all methods have potential side effects, so it needs to keep the call (even if it can determine the return value of the method).

This could be improved with more work in the linker, but the size savings are probably not as interesting as other potential improvements (at least for now).

As for the example above:
* It knows that `IsBrowser` always returns true in WASM builds
* So it effectively sees the condition like :
```C#
             if (loaded == 0 && !true) 
             { 
                 string message = "Couldn't find a valid ICU package installed on the system. " + 
                                 "Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support."; 
                 Environment.FailFast(message); 
             } 
```

It evaluates the condition and it's pretty easy to see that it will always be `false`. So there's no need to keep the branch in the if, it will never get hit.

We could discuss if the condition is correct, but linker has no way to argue either way.

**Comment by adamsitnik** [comment]
@vitek-karas @eerhardt thanks for full explanations!

**Comment by radekdoulik** [comment]
> This could be improved with more work in the linker, but the size savings are probably not as interesting as other potential improvements (at least for now).

I agree with that. Just want to add note, that it might also improve performance in some scenarios. Like here: https://github.com/mono/linker/issues/1113#issuecomment-823934940 where it would improve perf on platforms without intrinsic.

**Comment by marek-safar** [comment]
> that it might also improve performance in some scenarios

It should not as JIT/AOT/Interpreter can all optimize this already

**Comment by radekdoulik** [comment]
> It should not as JIT/AOT/Interpreter can all optimize this already

Nice. I forgot we do most optimization there and not in IL. I checked the wasm/AOT and it gets rid of most of it, which is great.

```
INITED_BB2:                                       ; preds = %NOTINITED_BB3, %INIT_BB1, %INIT_BB1
  br label %BB3

BB3:                                              ; preds = %INITED_BB2
  br label %BB2

BB2:                                              ; preds = %BB3
  br label %BB4

BB4:                                              ; preds = %BB2
  %3 = load %"System.ReadOnlySpan`1<byte>", %"System.ReadOnlySpan`1<byte>"* %arg_span, align 1
  store %"System.ReadOnlySpan`1<byte>" %3, %"System.ReadOnlySpan`1<byte>"* %0, align 1
  %4 = load i32*, i32** getelementptr inbounds ([16 x i32*], [16 x i32*]* @dummy_got, i32 0, i32 0), align 4
  %5 = bitcast i32* %4 to i32 (%"System.ReadOnlySpan`1<byte>"*, i32*)*
  %6 = notail call i32 @System_Text_Json_System_Text_Json_JsonReaderHelper_IndexOfOrLessThanNonVector_System_ReadOnlySpan_1_byte(%"System.ReadOnlySpan`1<byte>"* %0, i32* null), !managed_name !158
  br label %BB1

BB1:                                              ; preds = %BB4
  ret i32 %6
```

And the remaining `br label ...`'s are probably removed by llvm.

**Pull request closed without merging**
