### PR TITLE
CI Test

### PR DESCRIPTION
**Pull request by MihaZupan**
#78660

### CODE REVIEW

**Comment by EgorBo** [comment]
@MihaZupan any guesses from the log of your test that has just failed?
I'm currently not able to test this on linux-arm64, might be in a few hours.

**Comment by MihaZupan** [comment]
The "Correct" behavior is on the left, "arm64 checked" on the right: https://www.diffchecker.com/Wuwbdju9

```diff
utf8Length=14 utf8='70, 105, 108, 101, 195, 131, 78, 97, 109, 101, 46, 98, 97, 116'	
-IndexOfAnyExcept length=4 // Expected
+IndexOfAnyExcept length=5 // Arm64 checked
```

The `IndexOfAnyExcept` in this case is
```c#
private static readonly IndexOfAnyValues<byte> s_rfc5987AttrBytes =
    IndexOfAnyValues.Create("!#$&+-.0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ^_`abcdefghijklmnopqrstuvwxyz|~"u8);

utf8.IndexOfAnyExcept(s_rfc5987AttrBytes);
```

I've added a log to see if the type of `s_rfc5987AttrBytes` is the expected [`IndexOfAnyAsciiCharValues`](https://github.com/dotnet/runtime/blob/167b0a13ce77c9e7e50fc23908f8c6a3ad15f4eb/src/libraries/System.Private.CoreLib/src/System/IndexOfAnyValues/IndexOfAnyAsciiCharValues.cs#L10).

**Comment by MihaZupan** [comment]
Narrowing it down to
```c#
[Fact]
public void IndexOfAnyExpectTest()
{
    ReadOnlySpan<byte> bytes = new byte[] { 70, 105, 108, 101, 195, 131, 78, 97, 109, 101, 46, 98, 97, 116 };

    int offset = bytes.IndexOfAnyExcept(s_rfc5987AttrBytes);
    _output.WriteLine($"s_rfc5987AttrBytes is {s_rfc5987AttrBytes.GetType().FullName}");

    Assert.Equal(4, offset);
}
```

**Comment by EgorBo** [comment]
@MihaZupan from what I see so far - it reproduces on Release too (osx-arm64) and with JitMinOpts=1 meaning that it's very unlikely a jit optimization

**Comment by MihaZupan** [comment]
🤦‍♂️ Found it... it's a bug in `IndexOfAnyAsciiSearcher` on `arm64` for ASCII byte inputs:

https://github.com/dotnet/runtime/blob/167b0a13ce77c9e7e50fc23908f8c6a3ad15f4eb/src/libraries/System.Private.CoreLib/src/System/IndexOfAnyValues/IndexOfAnyAsciiSearcher.cs#L527
should be
```c#
if (AdvSimd.Arm64.IsSupported || TOptimizations.NeedleContainsZero)
```
like it is above
https://github.com/dotnet/runtime/blob/167b0a13ce77c9e7e50fc23908f8c6a3ad15f4eb/src/libraries/System.Private.CoreLib/src/System/IndexOfAnyValues/IndexOfAnyAsciiSearcher.cs#L506

I'm very surprised the tests missed this in #78093

**Comment by EgorBo** [comment]
@MihaZupan any idea why tests in https://github.com/dotnet/runtime/pull/78093 didn't fail? From my understanding, it should reliably fail on any arm64 devices (since neon is always there)

**Comment by MihaZupan** [comment]
As long as it supports `AdvSimd.Arm64`, we should see it yeah.

I expected that at least the outerloop tests I added in that PR should exercise this case, but maybe I was wrong.
You essentially need the following:
1. You must be using the `byte` overloads
1. The needle passed to `IndexOfAnyValues.Create` must be all ASCII
1. The input you are searching must contain a non-ascii character
1. That non-ascii character must be present before any other matching character

Perhaps the test doesn't satisfy 4.? I'll have to double-check.

**Comment by EgorBo** [comment]
> Run on a machine where AdvSimd.Arm64.IsSupported

It should be a baseline for any arm64 hardware, unless explicitly disabled

**Comment by MihaZupan** [comment]
Actually, there is another condition:
6. The non-ASCII character that was a false-positive (or false-negative in case of `Except`) must be exactly `128` higher than a value present in the needle.

In this case we weren't matching `195`, which happens to be `128 + 67`, and `67` is the ASCII `C` character present in the needle.

Since we're testing random inputs, I bet this is a case we just didn't hit :/

**Comment by MihaZupan** [comment]
I'll get a PR up, shouldn't need this one anymore.

Thanks for looking into this as well Egor!

**Pull request closed without merging**
