### PR TITLE
Remove two always false properties in UriSyntax

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by davidsh** [comment]
What is the motivation for removing this code? I know that it is currently not enabled. But we left this in because at the time we were considering adding an AppContext compat switch for this similar to .NET Framework to help customers impacted.

**Review by stephentoub — APPROVED** [review]

**Comment by ViktorHofer** [comment]
I guess the motivation is to eliminate dead code and with it increase code coverage. If we ever want to introduce a switch, we can revert this commit.

**Review by ViktorHofer — APPROVED** [review]

**Comment by davidsh** [comment]
@eiriktsarpalis Your runtime-libraries stress-http-linux pipeline builds are failing:
https://dev.azure.com/dnceng/public/_build/results?buildId=453543

>  CMake Error at CMakeLists.txt:4 (cmake_policy):
    Policy "CMP0083" is not known to this version of CMake.
  CMake Error at CMakeLists.txt:6 (include):
    include could not find load file:
        CheckPIESupported
  CMake Error at CMakeLists.txt:9 (check_pie_supported):
    Unknown CMake command "check_pie_supported".
    -- Configuring incomplete, errors occurred!
  See also "/repo/artifacts/obj/native/netcoreapp-Linux-Release-x64/CMakeFiles/CMakeOutput.log".
  Failed to generate native component build project!
/repo/src/libraries/Native/build-native.proj(36,5): error MSB3073: The command ""/repo/src/libraries/Native/build-native.sh" x64 Release Linux outconfig netcoreapp-Linux-Release-x64 -portable" exited with code 1.
Build FAILED.

**Comment by ViktorHofer** [comment]
@davidsh please NEVER just run /azp run in the runtime repo!

**Comment by karelz** [comment]
@ViktorHofer why not? What is the downside? Can you elaborate on it a bit to help us understand?

**Comment by davidsh** [comment]
My goal with "/azp run" was to restart the inner and outer loop test runs. That was the way to do it for many months now. CI has been broken for a few days due to Azure Devops issues.

What is the right set of commands to redo inner and outer loop? I tried closing and reopening the PR and that didn't help much.

There have been a lot of changes to the CI system lately. It would be good to send out a team email explaining the changes. I'm not the only one on our team that does "/azp run" to restart the CI. And if that command is wrong to do, maybe we should disable "/azp run"?

**Comment by stephentoub** [comment]
> why not? What is the downside? Can you elaborate on it a bit to help us understand?

This was discussed in several emails with the team, as well as during the recent networking team discussions when it was decided to add a networking stress leg.  "/azp run" without arguments will trigger every build definition registered against dotnet/runtime; that includes very long-running and resource-intensive jobs, like those for GC and networking stress.  It ends up consuming a huge amount of resources unnecessarily and starves other CI work.

**Comment by davidsh** [comment]
> It ends up consuming a huge amount of resources unnecessarily and starves other CI work.

Can't "/azp run" just be disabled in some way? It sounds risky having a command available that does bad things and is too easy to accidently invoke.

**Comment by stephentoub** [comment]
> Can't "/azp run" just be disabled in some way?

Not currently.

**Comment by ViktorHofer** [comment]
> What is the right set of commands to redo inner and outer loop? I tried closing and reopening the PR and that didn't help much.

You can always do an /azp list to get the list of trigger-able build definitions.

**Comment by ViktorHofer** [comment]
> @davidsh please NEVER just run /azp run in the runtime repo!

@davidsh just realized that I used an exclamation mark here which could be interpreted as being harsh. I hope you didn't feel offended, provoked or triggered by my statement, that wasn't my intention at all.

**Comment by davidsh** [comment]
>@davidsh just realized that I used an exclamation mark here which could be interpreted as being harsh. I hope you didn't feel offended, provoked or triggered by my statement, that wasn't my intention at all.

Thanks.  No worries.

**Pull request merged**
