### PR TITLE
JIT ARM64-SVE: Move SVE-specific emitIns logic to emitarm64sve.cpp

### PR DESCRIPTION
**Pull request by amanasifkhalid**
We already had a few SVE-specific `emitIns_*` methods; this PR strips out the remaining SVE instructions from our general `emitIns` methods, and moves them to corresponding `emitInsSve` methods in `emitarm64sve.cpp`. I plan to move over our SVE-specific helper methods, and extract the SVE cases in other shared emitter methods to SVE methods, but this PR is big enough that this seemed like a natural stopping point. There are no diffs in the SVE unit tests from this change.

cc @dotnet/arm64-contrib

### CODE REVIEW

**Review by a74nh — APPROVED** [review]
It's fairly tricky for me to confirm the code in emitarm64sve.cpp is just a copy/paste of the code from emitarm64.cpp. However, the changes good.

I'm assuming:
- No difference in codegen test output
- The contents of the functions in emitarm64sve.cpp are identical to that cut from emitarm64.cpp, plus potentially some repeated parts/boilerplate.


Additional thoughts:
- We should merge this asap
- In another PR, we could move the other SVE parts from the sanity check, disp instr, perf score etc functions into here too.
-  We have the choice to eventually use `emitInsSve_` functions directly instead of calling from `emitIns_`. No need to make that choice yet - depends on the IR code.

**Comment by amanasifkhalid** [comment]
@a74nh thanks for the review! Your assumptions are correct. This is a [no-diff](https://dev.azure.com/dnceng-public/public/_build/results?buildId=609167&view=ms.vss-build-web.run-extensions-tab) change, and I did a diff of the SVE unit test output with and without this change, and didn't see any diffs there either. I plan to do similar transition work for other methods (`emitOutputInstr` is my next priority, since that should yield TP improvements too).

> We have the choice to eventually use emitInsSve_ functions directly instead of calling from emitIns_. No need to make that choice yet - depends on the IR code.

Agreed. It would be slightly more performant if we could call the `emitInsSve` methods directly instead of falling into the default case in `emitIns`, but I didn't want to change the API surface just yet.

cc @kunalspathak @TIHan

**Review by kunalspathak — COMMENTED** [review]
> We have the choice to eventually use emitInsSve_ functions directly instead of calling from emitIns_

Agree.

I am hoping to see 0 or very few references of "sve_" text in `emitarm64.cpp`. Currently, there are still methods like `insEncodeSveElemsize_tszh_tszl_and_imm` , `insGetSveReg1ListSize`, etc. in `emitarm64.cpp`. Is there a reason why they can't be moved to `emitarm64sve.cpp`?

**Comment by amanasifkhalid** [comment]
> I am hoping to see 0 or very few references of "sve_" text in emitarm64.cpp. Currently, there are still methods like insEncodeSveElemsize_tszh_tszl_and_imm , insGetSveReg1ListSize, etc. in emitarm64.cpp. Is there a reason why they can't be moved to emitarm64sve.cpp?

I plan to move those too. I just thought that would be better suited for a follow-up PR, since this one is already pretty big.

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by kunalspathak** [comment]
image

**Comment by amanasifkhalid** [comment]
For reference, the MinOpts regression is only in the `smoke_tests.nativeaot` collection ([diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=609167&view=ms.vss-build-web.run-extensions-tab)). I imagine it's some outlier method...

**Pull request merged**
