### PR TITLE
Re-enabled mock tests for H/3.

### PR DESCRIPTION
**Pull request by ManickaP**
Mock tests do not use msquic, they should stay enable.
If the mocking coding doesn't work for wasm, we should rather selectively disable it with `[ConditionalClass(typeof(PlatformDetection), nameof(PlatformDetection.IsNotBrowser))]` and similar. So it stays running on Linux/Windows/OSX.

cc: @pavelsavara

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM.
H/3 support will probably depend on browser engine support so it would make sense to label it as such.

**Comment by pavelsavara** [comment]
This would probably break WASM CI tests in runtime-staging and mono outerloop. Looking at it now.

**Comment by pavelsavara** [comment]
Could you please replace it with `[ConditionalClass(typeof(PlatformDetection), nameof(PlatformDetection.IsNotBrowser))]` as you suggested ? Thank you.

The way how we disable QUIC makes it fail early on Browser.

```
fail: [FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3_Mock.SendAsync_TransferEncodingSetButNoRequestContent_Throws
info: System.PlatformNotSupportedException : System.Net.Quic is not supported on this platform.
info: at System.Net.Quic.QuicImplementationProviders.get_Mock() in C:\Dev\runtime\artifacts\obj\System.Net.Quic\net6.0-Debug\System.Net.Quic.notsupported.cs:line 50
info: at System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3_Mock.get_UseQuicImplementationProvider() in C:\Dev\runtime\src\libraries\System.Net.Http\tests\FunctionalTests\SocketsHttpHandlerTest.cs```

**Comment by ManickaP** [comment]
@pavelsavara I see the problem (it's the PNSE assembly replacement for the whole QUIC lib), I will change it. But I'll probably change it to something like platform is: Linux/Windows/OSX, to follow what we have defined as supported platform for S.N.Quic.

**Comment by wfurt** [comment]
should we skip the whole class/file? It may be best to not even build it for platforms where we don't build the production code.

**Comment by pavelsavara** [comment]
The `SocketsHttpHandlerTest.cs` file contains multiple classes and some of them are relevant to Browser.

**Comment by wfurt** [comment]
we _could_ refactor QUIC/H3 to separate file to make it more manageable

**Review by pavelsavara — APPROVED** [review]

**Comment by ManickaP** [comment]
Fixed the condition to `IsMockQuicSupported`. Feel free to re-review, otherwise I'll merge once the pipelines are done (I'll check the staging manually I guess).

**Comment by ManickaP** [comment]
Seems like no mock tests were run in staging, so it should be good to go, waiting for the final CI run after merge.

**Comment by ManickaP** [comment]
Failures are unrelated from staging pipeline.

**Pull request merged**
