### PR TITLE
[mono][wasm] Emit more logging from the EmccCompile task.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Comment by radical** [comment]
Set `Utils.Logger = Log;` at the top of the `Execute` method, then it will get logged without any extra changes needed.

**Comment by vargaz** [comment]
This will log out the command in a format which can be copy pasted instead of the verbose format which is 
Setting env var X to Y.
"Executing command 'command' with arguments: 'args'". etc.

**Review by radical — APPROVED** [review]

**Comment by radical** [comment]
Add a comment explaining that though, so it doesn't get removed in future.

**Review by lewing — APPROVED** [review]

**Comment by vargaz** [comment]
Failures are unrelated

**Pull request merged**
