### PR TITLE
Disable EventLogConfiguration flaky test

### PR DESCRIPTION
**Pull request by Anipik**
Related to https://github.com/dotnet/runtime/issues/1167

### CODE REVIEW

**Comment by ericstj** [comment]
Why are we disabling this now?  Is it suddenly happening more often or something?   We should either fix or delete the test rather than disable it.  Disabling is only a short-term mitigation we take when flaky tests are introduced and hurt CI reliability.

**Comment by Anipik** [comment]
The test is fixed now and is no longer reproducible. We got the confirmation from the windows team over after i created the pr

**Comment by ViktorHofer** [comment]
How is the Windows team involved here?

**Comment by Anipik** [comment]
We were using a windows api which was not working properly. They made the change and its no longer reproducible.

**Comment by ViktorHofer** [comment]
They made which change? For which OS versions? Servicing via WSUS? Asking to better understand the fix

**Comment by Robo210** [comment]
Servicing via Windows Update as part of the July 2020 ("7B") cumulative update, for all currently supported Windows versions.

**Comment by ViktorHofer** [comment]
Thanks a lot Kyle

**Pull request closed without merging**
