### PR TITLE
Update SDK to preview 1 release

### PR DESCRIPTION
**Pull request by am11**
Versions taken from https://dotnet.microsoft.com/en-us/download/dotnet/9.0.

related: https://github.com/dotnet/arcade/pull/14485

### CODE REVIEW

**Comment by am11** [comment]
cc @lewing for wasm/wasi failures.
cc @MichaelSimons for sourcebuild failures.

rest of the legs are green.

**Comment by MichaelSimons** [comment]
> cc @MichaelSimons for sourcebuild failures.

Repo owners should make an attempt at investigating first.

**Comment by am11** [comment]
> Repo owners should make an attempt at investigating first.

Ok, sorry about that. Only reason I pinged you was because your were pinged the last time we had this error:

>   /__w/1/s/artifacts/sb/src/eng/versioning.targets(198,5): error : Native SourceLink file could not be made available to the native build. Ensure that runtime-prereqs ran the sourcelink targets. [/__w/1/s/artifacts/sb/src/src/coreclr/runtime-prereqs.proj]

**Comment by ViktorHofer** [comment]
image

@dotnet/source-build-internal the `ReadSourceBuildIntermediateNupkgDependencies` task returns duplicate items. One roslyn intermediate item has the metadata `Name = Microsoft.CodeAnalysis` on it and the other has `Name = Microsoft.SourceBuild.Intermediate.roslyn`. Can you please investigate?

**Comment by ViktorHofer** [comment]
OK I think I understand the issue. Submitted https://github.com/dotnet/runtime/pull/98942

**Comment by MichaelSimons** [comment]
@ellahathaway - Can you take a look at what happened here?  The UX here when there are multiple source-build dependencies on the same repo isn't ideal.  I was expecting a failure with an obvious error message.

**Comment by ellahathaway** [comment]
> @ellahathaway - Can you take a look at what happened here? The UX here when there are multiple source-build dependencies on the same repo isn't ideal. I was expecting a failure with an obvious error message.

Investigating. The duplication should've caused an error like https://github.com/dotnet/arcade-validation/pull/4190#issuecomment-1941995997 since the SB metadata tag was on a non-intermediate, so I'm guessing that a different exception was hit first.

**Comment by ViktorHofer** [comment]
image

I suspect this changed with https://github.com/dotnet/sourcelink/commit/064732082224f37fab77290f762be9b4a51f7dd9. @tmat PTAL

**Comment by ViktorHofer** [comment]
Trying something out with the latest commit.

**Comment by ViktorHofer** [comment]
Looking at the commits in sourcelink again, I think it's https://github.com/dotnet/sourcelink/pull/1150 which regressed this.

**Comment by am11** [comment]
Shall we try setting https://github.com/dotnet/arcade/pull/14485/files#diff-9da24614831c308827a1ae533ffea392c97638c261dd42bd0f5226baa136d16eR16 here?

WASM failure is related to CPM, somehow SDK is seeing the Version Details infra as CPM? 👀

**Comment by ViktorHofer** [comment]
We already set that: https://github.com/dotnet/runtime/blob/51b51bffbb4733a50c93a39f047b29ff424494d9/Directory.Build.props#L343

**Comment by ViktorHofer** [comment]
Yes this really is https://github.com/dotnet/sourcelink/pull/1150. @dotnet/source-build-internal sourcelink doesn't support cloning from a local path anymore which source-build does. This affects all repositories that use the inner clone feature and upgrade to a .NET 8.0.2xx or 9.0 Preview 1 SDK. It's probably only runtime that errors because we have a test that validates that sourcelink works correctly.

Related: https://github.com/dotnet/source-build/issues/4117

**Review by jeffkl — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]

**Review by agocke — APPROVED** [review]

**Comment by clamp03** [comment]
@am11 After this PR, I found that coreclr test is not built. However, I don't know well about SDK so I don't know how to fix it. Could you please take a look at this?
Thank you!

How to reproduce
`ROOTFS_DIR=/home/clamp/Work/dotnet/rootfs/riscv64 ./src/tests/build.sh -riscv64 -clang15 -Checked -priority1 -cross`

Error message
```
   1:2>/home/clamp/Work/dotnet/riscv/crossgen2/src/tests/Common/test_dependencies_fs/test_dependencies.fsproj : error NU1101: Unable to find package Microsoft.NETCore.App.Runtime.linux-riscv64. No packages exist with this id in source(s): /home/clamp/Work/dotnet/riscv/crossgen2/.dotnet/sdk/9.0.100-preview.1.24101.2/FSharp/library-packs, dotnet-eng, dotnet-libraries, dotnet-libraries-transport, dotnet-public, dotnet-tools, dotnet9, dotnet9-transport [/home/clamp/Work/dotnet/riscv/crossgen2/src/tests/build.proj]
   1:2>/home/clamp/Work/dotnet/riscv/crossgen2/src/tests/Common/test_dependencies_fs/test_dependencies.fsproj : error NU1101: Unable to find package Microsoft.NETCore.App.Host.linux-riscv64. No packages exist with this id in source(s): /home/clamp/Work/dotnet/riscv/crossgen2/.dotnet/sdk/9.0.100-preview.1.24101.2/FSharp/library-packs, dotnet-eng, dotnet-libraries,dotnet-libraries-transport, dotnet-public, dotnet-tools, dotnet9, dotnet9-transport [/home/clamp/Work/dotnet/riscv/crossgen2/src/tests/build.proj]
   1:2>/home/clamp/Work/dotnet/riscv/crossgen2/src/tests/build.proj(548,5): error MSB3073: The command ""/home/clamp/Work/dotnet/riscv/crossgen2/.dotnet/dotnet" restore Common/test_dependencies_fs/test_dependencies.fsproj  /p:SetTFMForRestore=true /p:TargetOS=linux /p:TargetArchitecture=riscv64 /p:Configuration=Checked /p:CrossBuild=true" exited with code 1.
```

**Comment by am11** [comment]
@clamp03 https://github.com/dotnet/runtime/issues/97791#issuecomment-1977202945, we need to pass `-p:UseLocalAppHostPack=true`. BTW, this PR was merged last week and it was already needed since Feb 6 https://github.com/dotnet/runtime/issues/97791#issuecomment-1929466052.

**Comment by clamp03** [comment]
> we need to pass -p:UseLocalAppHostPack=true.

@am11 Thank you for the comment. I tried to build coreclr test with `-p:UseLocalAppHostPack=true`. However, it still fails with the same error.

> BTW, this PR was merged last week and it was already needed since Feb 6 https://github.com/dotnet/runtime/issues/97791#issuecomment-1929466052.

Actually, I checked the build with/without only this PR. (If head commit is `Consolidate LINQ's internal IIListProvider/IPartition into base Iterator class` e101ae2bd1c198ba7aaa209d1a4c55d6ce6b4073, it is okay. However it fails if head commit is this.)
Thank you.

CC @dotnet/samsung

**Pull request merged**
