### PR TITLE
Remove closed issues from issues.targets

### PR DESCRIPTION
**Pull request by eduardo-vp**

### CODE REVIEW

**Review by trylek — APPROVED** [review]
Nice, thanks for cleaning this up!

**Comment by trylek** [comment]
@eduardo-vp The failed mono tests hit an interesting corner case - you correctly removed the exclusions marked with the issue #41519 but apparently the issue was just closed due to being a duplicate of another issue, #64127, that is still pending. I think that in this particular case we probably need to put the exclusions back and just rename the tracking issue link. Hopefully there are no more cases like this.

**Comment by AntonLapounov** [comment]
Duplicate issues should be resolved as "not planned" instead of "completed" and we should recognize the former as "not fixed".

**Comment by trylek** [comment]
@AntonLapounov - thanks for the comment, I've also been thinking that we should somehow clarify the workflow here. The interesting question is, how would it work in this particular case? OK, let's assume that @radical closed the issue #41519 as "not planned" and so Eduardo didn't try to remove the exclusions from the issues.targets file. Now what should happen once #64127 is fixed? The exclusions would stay in issues.targets forever unless someone took additional action to somehow subsequently change the status of #41519 to "completed" as a consequence of completing #64127. In general I think that we'd need better tracking of the issue graph on GitHub to be able to fully automate this.

**Comment by jkotas** [comment]
> clarify the workflow here

I think we want to maintain invariant that the issue the test is disabled against is active. Thus the closure of an issue with `disabled-test` tag should be accompanied by a PR that edits the test metadata in sources. If the issue is being closed as a duplicate, the PR should just update the issue that the test is disabled against.

**Review by SamMonoRT — APPROVED** [review]

**Comment by BruceForstall** [comment]
Note: another failure from this change was https://github.com/dotnet/runtime/issues/76845, which only appears during JitStress runs (on Linux/arm32).

**Pull request merged**
