### PR TITLE
[release/6.0] WasmAppBuilder: publish only once per target framework instead of invoking publish explicitly.

### PR DESCRIPTION
**Pull request by radical**
Based on @ericstj's suggestion
dotnet#58816 (comment) .

Fixes dotnet#58816 .

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
I don't really have enough context to approve but this is breaking CI and if this it we should get it merged ASAP

**Comment by danmoseley** [comment]
After the validation completes of course. Thanks for fixing..

**Comment by radical** [comment]
I'm hoping that this fixes it!

**Review by marek-safar — APPROVED** [review]

**Comment by danmoseley** [comment]
Did this break originally get through PR validation just by bad luck?

**Comment by radical** [comment]
> Did this break originally get through PR validation just by bad luck?

Yeah, race, and it happened to pass for all the builds that time 😬

**Pull request merged**
