### PR TITLE
fix and re-enable TestCheckChildProcessUserAndGroupIds test

### LINKED ISSUE #28922: Test failure: System.Diagnostics.Tests.ProcessTests/TestCheckChildProcessUserAndGroupIds
Opened on behalf of @wfurt

The test `System.Diagnostics.Tests.ProcessTests/TestCheckChildProcessUserAndGroupIds` has failed.

Failure Message:
```
System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.
```

Stack Trace:
```

Child exception:
  Xunit.Sdk.XunitException: Expected: 4, 20, 24, 25, 27, 29, 30, 44, 46, 109, 110, 998, 1000
Actual: 4, 20, 24, 25, 27, 29, 30, 44, 46, 109, 110, 1000
   at System.AssertExtensions.Equal[T](HashSet`1 expected, HashSet`1 actual) in /__w/1/s/src/CoreFx.Private.TestUtilities/src/System/AssertExtensions.cs:line 349
   at System.Diagnostics.Tests.ProcessTests.CheckUserAndGroupIds(String userId, String groupId, String groupIdsJoined, String checkGroupsExact) in /__w/1/s/src/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 515

Child process:
  System.Diagnostics.Process.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Diagnostics.Tests.ProcessTests Int32 CheckUserAndGroupIds(System.String, System.String, System.String, System.String)

Child arguments:
  1000, 1000, 4,20,24,25,27,29,30,44,46,109,110,998,1000, True

```

Build : 3.0 - 20190310.5 (Core Tests)
Failing configurations:
- Ubuntu.1604.Amd64-x64
  - Release

### PR DESCRIPTION
**Pull request by adamsitnik**
fixes #28922

Explanation: This test gets the current user: name, id, and groups:

https://github.com/dotnet/runtime/blob/721fb97f442d14882943c8462d64f84616014d10/src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs#L546-L549

and starts a process using the given user name:

https://github.com/dotnet/runtime/blob/721fb97f442d14882943c8462d64f84616014d10/src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs#L557

It was failing because so far we were using two different ways of getting the user group Ids:

- `id -G $username` to get the expected ids (called from parent process)
- `libc.getgroups` to get the actual ids (called from child process started as given user)

There are some differences in what `id -G` and `libc.getgroups` can return and I've  verified that by just comparing the output without starting any new processes (see  https://github.com/dotnet/runtime/issues/28922#issuecomment-748035051 for details).

The solution is to use `id -G` for getting both the expected and actual ids. The parent process passes the username to the command, the child command passes no username to get it for the current user (the test verifies if the process was started as the given user)

### CODE REVIEW

**Comment by adamsitnik** [comment]
For OSX outerloop the failing tests are unrelated:

- `System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.SocketSendQueueFull_RequestCanceled_ThrowsOperationCanceled`
-  `System.IO.Tests.FileSystemWatcher_Multiple_Test.FileSystemWatcher_File_Delet_NotAffectEachOther`

**Comment by adamsitnik** [comment]
However, the Mono leg failed for this particular test:

> Test System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIds has failed. Check the Test tab or this console log: https://helix.dot.net/api/2019-06-17/jobs/b97699fb-54bc-411c-9043-8e640639d1b9/workitems/System.Diagnostics.Process.Tests/console

**Comment by adamsitnik** [comment]
```log

Unhandled Exception:
Xunit.Sdk.XunitException: Expected: 4
Actual: 
   at System.AssertExtensions.Equal[UInt32](HashSet`1 expected, HashSet`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 379
   at System.Diagnostics.Tests.ProcessTests.CheckUserAndGroupIds(String userId, String groupId, String groupIdsJoined, String checkGroupsExact) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 533
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 378
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
[ERROR] FATAL UNHANDLED EXCEPTION: Xunit.Sdk.XunitException: Expected: 4
Actual: 
   at System.AssertExtensions.Equal[UInt32](HashSet`1 expected, HashSet`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 379
   at System.Diagnostics.Tests.ProcessTests.CheckUserAndGroupIds(String userId, String groupId, String groupIdsJoined, String checkGroupsExact) in /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs:line 533
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 378
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
    System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIds [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.XunitException: Expected: 4
        Actual: 
        /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs(379,0): at System.AssertExtensions.Equal[UInt32](HashSet`1 expected, HashSet`1 actual)
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessTests.Unix.cs(533,0): at System.Diagnostics.Tests.ProcessTests.CheckUserAndGroupIds(String userId, String groupId, String groupIdsJoined, String checkGroupsExact)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        
        Child process:
          System.Diagnostics.Process.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Diagnostics.Tests.ProcessTests Int32 CheckUserAndGroupIds(System.String, System.String, System.String, System.String)
        
        Child arguments:
          1001, 4, 4, True     
```

**Comment by adamsitnik** [comment]
The test that I wanted to fix has passed (it was failing at the beginning), the current CI failures are not related:

```log
.packages/microsoft.dotnet.helix.sdk/6.0.0-beta.20615.4/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(76,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Work item System.Text.RegularExpressions.Tests in job eb0e5f55-01bf-4a05-ae2e-a449442a2cac has failed.
Failure log: https://helix.dot.net/api/2019-06-17/jobs/eb0e5f55-01bf-4a05-ae2e-a449442a2cac/workitems/System.Text.RegularExpressions.Tests/console

.packages/microsoft.dotnet.helix.sdk/6.0.0-beta.20615.4/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(76,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Work item System.Text.RegularExpressions.Tests in job eb0e5f55-01bf-4a05-ae2e-a449442a2cac has failed.
Failure log: https://helix.dot.net/api/2019-06-17/jobs/eb0e5f55-01bf-4a05-ae2e-a449442a2cac/workitems/System.Text.RegularExpressions.Tests/console
```

**Comment by wfurt** [comment]
I feel this is move wrong direction. This starts new process and add dependency on finding the right executable. I think that was OK for the test where we control the environment and overhead does not matter.  Further more, it can report group the process actually does not have. I'm wondering if that can cause issues does the road.

**Comment by adamsitnik** [comment]
> it can report group the process actually does not have

@wfurt good point, I've read the docs one more time and I think I've found a "proper fix", PTAL at #46302

**Pull request closed without merging**
