### PR TITLE
Disable new tests failing on NativeAOT

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Cc @dotnet/ilc-contrib

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
> Azure Pipelines failed to run 1 pipeline(s).

@agocke is this expected to work now?

**Comment by agocke** [comment]
Should be getting enabled shortly. I needed to merge the PR first apparently

**Comment by agocke** [comment]
Yeah looks like it's active now https://dev.azure.com/dnceng-public/public/_build?definitionId=265&_a=summary

**Comment by agocke** [comment]
Oh, there's a typo in the yaml, I'll fix it.

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
