### PR TITLE
Allow SslStream in ConnectCallback

### LINKED ISSUE #42455: Enable SocketsHttpHandler.ConnectCallback to negotiate TLS
[AB#1219925](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1219925)
### Description
When using the new ConnectCallback feature, returning an SslStream results in errors related to TLS negotiation. HttpConnectionPool expects to be in charge of negotiating SSL over the returned stream, but design eliminates lots of possible transport-level opportunities for people who want or need to control or manage transport processing.

Here is an example implementation of ConnectCallback that will fail as a result of this issue.
```c#
            var retVal = new HttpMessageInvoker(
                new SocketsHttpHandler()
                {
                    ConnectCallback = async (ctx, cancellationToken) =>
                    {
                        var socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
                        await socket.ConnectAsync(ctx.DnsEndPoint);

                        var networkStream = new NetworkStream(socket);
                        var sslStream = new SslStream(networkStream);

                        await sslStream.AuthenticateAsClientAsync(ctx.RequestMessage.RequestUri.Host);

                        return sslStream;
                    }
                }
            );
```

Ideally, HttpConnectionPool would manage negotiating TLS for me if I returned a Stream implementation, but if I returned an SslStream, it ought to defer negotiation to me.

### Configuration
Latest bits from release/5.0-rc2, not arch or platform specific. 

### Regression?
Not a regression.

### Other information
Being able to return an SslStream (or other stream types) is important because it enables the ConnectCallback to provide a facility for transport-level optimizations like stream multiplexing (imagine a stream implementation that's built atop a series of TCP sockets for compatibility reasons, but actually parallelizes writes over multiple underlying TCP connections), TLS pre-negotiation (TLS negotiation for small payloads is expensive, perhaps the implementor of the ConnectCallback would like to maintain a pool of pre-negotiated TLS sessions for specific destinations) and telemetry (streams returned by ConnectCallback can't effectively have their contents intercepted by other code running in the stack).

This seems like something as simple as a type check on the returned stream would be sufficient:

```c#
if (!(is SslStream)) {
    /// negotiate TLS in the usual, existing way
}
```

I'm happy to propose a PR with a fix for this issue along with corresponding tests.

### PR DESCRIPTION
**Pull request by wfurt**
This is another attempt to address #42455. It is sitting there for long time and this would be good for for #63663 when implemented. 

This would also solve concerns from #63706 as this allows to track and timeout/log separately TCP and TLS handshakes.
It would also solve old issue (I cannot find any more) when somebody wanted to reuse TCP/TLS to different sites hosted on same server. 

The difference from original PR is that this allows not only SslStream it self but also derived classes (added test for that).
With that somebody can create wrapper or what ever and it would still work as long as we can cast it back to SslStream. 
That should hopefully address https://github.com/dotnet/runtime/issues/42455#issuecomment-695352955 and make @stephentoub happier. 

There were also concerns about options we construct and particular setting. The biggest risk I see is that given stream did not negotiate ALPN for HTTP/2. In that case we should fall-back to HTTP/1 and I don't see  functional problem with that. I added test and trace message to make diagnostic easier. But if somebody is in charge they are also talking responsibility. 
Since the initial request is passed in, `ConnectCallback` _can_ do the right thing. I added test to verify that H/2 can be still negotiated if requested. (and fallback works)

While we may look into more fancy ways how to control connect and SSL, I don't see harm in allowing TLS here. 

fixes #42455

### CODE REVIEW

**Review by ManickaP — COMMENTED** [review]
LGTM if this is what we want.
Does this close any issues you mentioned in the description?

**Comment by geoffkizer** [comment]
> I don't see harm in allowing TLS here.

There's a long discussion in the linked issue about why we decided not to do this initially.

Even if we changed our mind on this now, I don't believe we can change behavior now as it could break people.

**Comment by wfurt** [comment]
The derived classes was one of them - and that should work now. And how this would break users? Passing SslStream does not work now so I don't see case somebody would do that. So allowing it should not matter, right?

**Comment by halter73** [comment]
> The derived classes was one of them - and that should work now. And how this would break users? Passing SslStream does not work now so I don't see case somebody would do that. So allowing it should not matter, right?

The only thing I could imagine would be nested TLS connections. I'm not aware of anyone doing that though.

**Comment by scalablecory** [comment]
On surface level, I think change is fine. The issue has some speculative concerns that we should get consensus on.

Is there any usefulness in giving the caller a pre-constructed `SslClientAuthenticationOptions`, or do they have everything they need to do so and we are comfortable with them needing to understand e.g. ALPN and SNI?

If we want to allow layering on top of the `SslStream` or custom TLS implementations, we could use a settable bool in the callback context:

```c#
class SocketsHttpConnectionContext
{
    // if set inside callback, HttpClient assumes the callback established TLS.
    public bool IsSslEstablished { get; set; }

    // public SslClientAuthenticationOptions? AuthenticationOptions { get; }
}
```

This would allow the callback to establish connection, establish TLS, and add a plaintext filter all in one go.

It would also avoid the breaking behavior change that @geoffkizer mentioned. Seems like it might be an uncommon scenario, though.

**Comment by ManickaP** [comment]
Slightly related https://github.com/dotnet/runtime/issues/64332. 

Providing pre-constructed `SslClientAuthenticationOptions` is actually nice idea. The could also contain remote cert callback which was set on `HttpClientHandler`, since we wrap it to provide expected sender object:
https://github.com/dotnet/runtime/blob/d34c0ff7c104b3c6e39eb17cc0d21b7ca2dc5c6d/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs#L36-L36

**Comment by wfurt** [comment]
I'd be fine with adding the property. I'm not sure if that is really needed and what we do if this is set but the stream is not `SslStream` (or castable) or vice versa. 
I was thinking about `SslClientAuthenticationOptions` as well. But since the whole idea here is to take over the handshake I'm not sure if that is necessary. But if we fell like it, we can add it as @scalablecory suggested. 
Both can probably be done as enhancements. 
If we agree on direction I can get that going.

**Comment by scalablecory** [comment]
> I'd be fine with adding the property. I'm not sure if that is really needed...

I'm not convinced it's needed myself, it was just a thought.

- Do we think the breaking change will be a big deal? To be hit, someone will need to return an `SslStream` today and expect us to layer another one on top of it.
- Do we care about layering on top of `SslStream` here? I'm not sure what this gives us that `PlaintextFilterCallback` does not, other than it may be simpler for customers to implement.
- Do we care about custom TLS implementations? This would be interesting but I'm not sure we have a solid case for it. @vcsjones or anyone else have thoughts? Maybe to use OpenSSL on Windows, implement TLS 1.3 on older platforms, etc.?

>> ...and what we do if this is set but the stream is not SslStream (or castable) or vice versa.

What do we depend on `SslStream` for? I know we pass a `TransportContext` down to `HttpContent` and log some crypto parameters in ETW. We might need a solution for the former... the latter I'd be happy to just ignore.

**Comment by wfurt** [comment]
The critical part is here IMHO:

https://github.com/dotnet/runtime/blob/ea69502cb15b6fdd877bffb0c2f9e4242b66434a/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L641-L645

We need to be able to cast to SslStream and query ALPN. So it could be differnt implementation (unlikely) but as long as it derives from SslStream it would work and we don't care IMHO. This is essentially same as the (probably more common) wrapper scenario. 

The TransportContext is used for ChannelBinding e.g enhanced Windows security and it is fully option at this moment AFAIK.

**Comment by scalablecory** [comment]
Yeah that's a good one. Barring a customer need, that makes me a little more in favor of doing this PR as-is (well, maybe with the `SslClientAuthOptions` added), and leaving more complex things to the future.

**Review by stephentoub — APPROVED** [review]
I'm ok with this if @geoffkizer is.

**Pull request merged**
