### PR TITLE
[mono][interp] Intrinsify SpanHelpers Clear/Fill

### PR DESCRIPTION
**Pull request by BrzVlad**

### CODE REVIEW

**Comment by BrzVlad** [comment]
alternative to changes in managed code from https://github.com/dotnet/runtime/pull/99059

cc @EgorBo

**Review by vargaz — APPROVED** [review]

**Comment by lewing** [comment]
It looks like wasm still has references to MINT_INITOBJ in at least a couple of places

**Comment by kg** [comment]
I'll prep the jiterp changes for this today

**Comment by lewing** [comment]
image
image

**Pull request merged**
