### PR TITLE
Fix reflection invoke file format issue for generic methods

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
The file format that mapped reflection metadata to runtime artifacts had a limitation that required generic methods to be always instantiated over concrete types - we could not place canonical method bodies there. The limitation stemmed from the fact that the mapping table was placing a generic dictionary in it.

This switches the table to use NameAndSignature + an array of instantiation arguments.

The rest of this change is just deleting code that was working around the problem. The fixes in NativeLayoutVertexNode and NodeFactory.NativeLayout are fixing analysis holes that were exposed by our ability to be more lazy.

Also saves 0.4% on BasicWebApi, which is always nice.

Cc @dotnet/ilc-contrib

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thanks!

**Comment by jkotas** [comment]
Linq tests need to be looked at:
```
[FAIL] System.Linq.Tests.MaxTests.Max_AllTypes
System.NotSupportedException : 'System.Linq.Tests.MaxTests.Max_AllTypes[System.Byte](System.Collections.Generic.IEnumerable`1[System.Byte],System.Byte)' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
```

**Comment by MichalStrehovsky** [comment]
I had a chance to sleep on this a couple time and I have one question that I can't make my mind on:

Currently, if reflection analysis/RD.XML/whatever comes up with the idea that we need `Foo<string>`, we'll generate `MethodTable` and everything for `Foo<string`>. After this change, we would only generate the type loader template to be be able to create it when needed.

The question is whether I went too far with turning all analysis to happen with canonical forms. Whether it would be enough to take the part of this change that allows canonical forms of generic methods (like we already allow for canonical forms of types), but don't force the entire analysis to happen on top of Canon. Leave the option to force concrete instantiations open.

**Comment by jkotas** [comment]
If I understand correctly, these are benefits of each option:
- No observable functional difference between two options
- Analysis based on cannon:
   - Compiler is faster
   - Binaries are smaller
- Analysis based on exact instantiations:
   - Less dependency on type builder when creating generic instantiations via reflection, more of them are saved into image
 Is this right?

**Comment by MichalStrehovsky** [comment]
Yep. And it can be used to work around type loader bugs.

**Comment by jkotas** [comment]
"Analysis based on cannon" option looks better to me (ie what you have there right now). 

I would not optimize for having easier workarounds for type loader bugs. We can use https://github.com/dotnet/runtime/issues/81741 for that once it becomes available.

**Comment by MichalStrehovsky** [comment]
> Linq tests need to be looked at:

Oh, not a regression, this is an improvement. `Min_AllTypes<T>` is constrained to `where T : INumber<T>` and we previously couldn't create a suitable instantiation, so the method wasn't reflection-visible at all. We now create `__Canon` instantiation but we need a lot more than that. RD.XML it is.

Not being reflection visible at all might be a separate bug...

**Pull request merged**
