### PR TITLE
#ifdef unused declaration and implementation of icalls

### LINKED ISSUE #33533: [mono] Don't compile and export unused icalls
In https://github.com/dotnet/runtime/blob/master/src/mono/mono/metadata/icall-decl.h we have declarations for icalls that may not be used in https://github.com/dotnet/runtime/blob/master/src/mono/mono/metadata/icall-def-netcore.h that aren't under an '#ifndef ENABLE_NETCORE` guard.

The two files should be audited and the icall declarations should be ifdefed out in `icall-decl.h` (along with their corresponding implementations which are likely in `icall.c` but maybe elsewhere)

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
Fixes https://github.com/dotnet/runtime/issues/33533

### CODE REVIEW

**Comment by vargaz** [comment]
Why is this needed ? Unreferenced icalls will be removed by the native linker.

**Comment by lambdageek** [comment]
@vargaz `ICALL_EXPORT` == `MONO_API` == `__attribute__ ((visibility ("default")))` - if you define `ENABLE_ICALL_EXPORT` (which we do for wasm) - can the linker remove them if we tell it to export the symbols?

It's actually unclear to me if we use `-fvisibility=hidden` anywhere - it's only set for GCC right now (not clang?). So it's possible those symbols are visible even without `ENABLE_ICALL_EXPORT`.

**Comment by vargaz** [comment]
The visibility attributes only affect shared libraries, they don't affect wasm.

**Comment by lambdageek** [comment]
> It's actually unclear to me if we use -fvisibility=hidden anywhere - it's only set for GCC right now (not clang?). So it's possible those symbols are visible even without ENABLE_ICALL_EXPORT.

Looks like we only set `ENABLE_VISIBILITY_HIDDEN` on ios. on wasm it doesnt' matter.  but on android and desktop it's going to live this dead code in the library, I think.

**Comment by lambdageek** [comment]
Couple of functions in marshal.c are still implemented
```

  ves_icall_System_Runtime_InteropServices_Marshal_ReAllocHGlobal (gpointer ptr, gsize size)
  ^
  /Users/runner/work/1/s/src/mono/mono/metadata/marshal.c:5437:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
  gpointer
  ^
  static 
  /Users/runner/work/1/s/src/mono/mono/metadata/marshal.c:5468:1: error: no previous prototype for function 'ves_icall_System_Runtime_InteropServices_Marshal_AllocCoTaskMem' [-Werror,-Wmissing-prototypes]
  ves_icall_System_Runtime_InteropServices_Marshal_AllocCoTaskMem (int size)
  ^
  /Users/runner/work/1/s/src/mono/mono/metadata/marshal.c:5467:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
  void*
  ^
  static 
  /Users/runner/work/1/s/src/mono/mono/metadata/marshal.c:5516:1: error: no previous prototype for function 'ves_icall_System_Runtime_InteropServices_Marshal_ReAllocCoTaskMem' [-Werror,-Wmissing-prototypes]
  ves_icall_System_Runtime_InteropServices_Marshal_ReAllocCoTaskMem (gpointer ptr, int size)
  ^
  /Users/runner/work/1/s/src/mono/mono/metadata/marshal.c:5515:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
  gpointer
  ^
  static 
```

**Comment by MCCshreyas** [comment]
@lambdageek yeah. Ok. I will get those out of ifdef! 😇

**Comment by MCCshreyas** [comment]
@lambdageek I just check those functions in the header file ([src/mono/mono/metadata/icall-decl.h](https://github.com/dotnet/runtime/blob/01f8edecdb98edeb9b7def0a8e95521f4dc7391c/src/mono/mono/metadata/icall-decl.h)) and those are not in #ifdef so those should be there ideally!

**Comment by akoeplinger** [comment]
@MCCshreyas the function declarations that @lambdageek mentioned need to be added back to the icall-decl.h since the build fails without them (they're used in src/mono/mono/metadata/marshal.c).

**Comment by MCCshreyas** [comment]
@akoeplinger Ok. Got it. I will get those out of this ifdef. Then those will be visible. https://github.com/dotnet/runtime/blob/01f8edecdb98edeb9b7def0a8e95521f4dc7391c/src/mono/mono/metadata/icall-decl.h#L283

**Comment by marek-safar** [comment]
NETCORE define is gone is this is no longer needed

**Pull request closed without merging**
