### PR TITLE
JIT: Avoid check for returns in methods with pinvokes in LSRA

### PR DESCRIPTION
**Pull request by jakobbotsch**
The pinvoke epilog is explicit on all our targets now, so it seems like this code should be unnecessary everywhere (and in any case, should not have been inside very general and very hot `newRefPosition`).

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Failures are #103577, #103568, #103545, #102370, #102335, #102706

cc @dotnet/jit-contrib PTAL @kunalspathak

**Comment by kunalspathak** [comment]
> The pinvoke epilog is explicit on all our targets now

Can you point to the relevant code? When I search for `RBM_PINVOKE_TCB`, other than lsrabuild.cpp, I just see it getting used for arm/x86.

**Comment by jakobbotsch** [comment]
> Can you point to the relevant code? When I search for `RBM_PINVOKE_TCB`, other than lsrabuild.cpp, I just see it getting used for arm/x86.

The pinvoke epilog is inserted as regular IR in lowering:
https://github.com/dotnet/runtime/blob/f2bdb754eb8c5b7723dbe2c21ec84f5c1634f74f/src/coreclr/jit/lower.cpp#L5683-L5695

I suspect the code I am removing here exists because at some point the pinvoke epilog was implicitly generated as part of epilog codegen (or perhaps `GT_RETURN` codegen). But since it is explicitly represented in IR today LSRA should already be handling the conflicts that may arise by normal means.

**Comment by kunalspathak** [comment]
Does that mean we do not need `RBM_PINVOKE_FRAME` and need `RBM_PINVOKE_TCB` only for x86/arm?

**Comment by jakobbotsch** [comment]
> Does that mean we do not need `RBM_PINVOKE_FRAME` and need `RBM_PINVOKE_TCB` only for x86/arm?

`REG_PINVOKE_FRAME` is still used. It doesn't look like `RBM_PINVOKE_FRAME` has uses, but I guess it's nice to be consistent about making the mask versions available.

Both are only used in x86/arm32, so the definitions outside could be removed. Do you want me to do that as part of this PR?

**Comment by kunalspathak** [comment]
> `REG_PINVOKE_FRAME` is still used. It doesn't look like `RBM_PINVOKE_FRAME` has uses, but I guess it's nice to be consistent about making the mask versions available.

The only use I see for `REG_PINVOKE_FRAME` is this, which is for x86/arm, so we can just keep it for x86/arm and remove it from other targets.

https://github.com/dotnet/runtime/blob/35437dd65c882f3855f6abda8512c3e993cb81a4/src/coreclr/jit/gentree.cpp#L1780-L1783

After this PR, there is no usage of `RBM_PINVOKE_FRAME`, so can get rid of that as well.
 
> Both are only used in x86/arm32, so the definitions outside could be removed. Do you want me to do that as part of this PR?

Yes, that will be good.

**Comment by jakobbotsch** [comment]
> After this PR, there is no usage of `RBM_PINVOKE_FRAME`, so can get rid of that as well.

There are plenty of other cases where we have `REG_X` and `RBM_Y` where only one is used, but where both are defined. E.g. `REG_EXCEPTION_OBJECT` (unused) vs `RBM_EXCEPTION_OBJECT` (used), `REG_R2R_INDIRECT_PARAM` (used) vs `RBM_R2R_INDIRECT_PARAM` (unused), etc.

Like I mentioned above I think we should consistently define both versions, so I don't think we should remove the `RBM` version. But I can remove the definitions outside x86/arm32.

**Comment by kunalspathak** [comment]
> Like I mentioned above I think we should consistently define both versions, so I don't think we should remove the `RBM` version. But I can remove the definitions outside x86/arm32.

SGTM

**Review by kunalspathak — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
