### PR TITLE
Make sanitizers work again in coreclr

### PR DESCRIPTION
**Pull request by omajid**
- Don't use `CMAKE_CURRENT_SOURCE_DIR` because it points to the   original CMakeLists.txt that's doing an `include`. Use the variable   that explicitly refers to `eng/native`.

- `--ffunction-sections` produces an error with clang. `-fsanitize=bool;-ffunction-sections` (single dash in `-ffunction`) is accepted by even clang 3.0 (the oldest clang I could find on godbolt.org  while the two-dash variant is treated as an error.

- Add `symbolizer` argument to `enable-sanitizers.sh` to force exporting the symbol variable, which the comment states (I haven't verified) is not needed on newer clang versions.

- Stop defaulting to an older clang version, and support un-versioned names too.

### CODE REVIEW

**Comment by omajid** [comment]
I figured I would enable sanitizers to see if something obvious pops up for #61671, but I am running into some errors locally that I don't know how to fix:

```
source ./src/coreclr/enablesanitizers.sh ubsan
export VERBOSE=1
./build.sh clr+libs+libs.tests -rc checked -lc Release
[....]
  /usr/bin/ld: ../../dlls/mscordac/libmscordaccore.so: undefined reference to `typeinfo for BINDER_SPACE::Assembly'
  /usr/bin/ld: ../../dlls/mscordac/libmscordaccore.so: undefined reference to `typeinfo for LCGMethodResolver'
  /usr/bin/ld: ../../dlls/mscordac/libmscordaccore.so: undefined reference to `typeinfo for DebuggerRCThread'
```

**Comment by omajid** [comment]
A standalone build with - without sanitizers enabled `./build.sh clr+libs+libs.tests -rc checked -lc Release` - works for me.

I wonder why enabling sanitizers introduces undefined references.

Anyone know where if there's a library I need to link to to get access to `BINDER_SPACE::Assembly`, `LCGMethodResolver` and `DebuggerRCThread`?

**Review by jkoritzinsky — APPROVED** [review]

**Comment by omajid** [comment]
Marking this as draft, until the issues in https://github.com/dotnet/runtime/pull/61948#issuecomment-976037393 are resolved.

**Comment by tstellar** [comment]
@omajid This can happen if you have a library consumer built with rtti enabled trying to link with a library built without rtti.

**Pull request closed without merging**
