### PR TITLE
JIT: Spill newarr into temp

### PR DESCRIPTION
**Pull request by hez2010**
Extracted from #104906 

Spilling newarr into temp and introduce a new block flag for it. This is the prerequisites of escape analysis for arrays.

Question: should we always spill `newarr` instead of only do this when optimizations are enabled?

/cc: @AndyAyersMS

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
There are quite a few [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=889601&view=ms.vss-build-web.run-extensions-tab). Can you investigate?

> Question: should we always spill `newarr` instead of only do this when optimizations are enabled?

I would follow the pattern we have for `newobj`, which always spills to a temp.

**Comment by hez2010** [comment]
> I would follow the pattern we have for `newobj`, which always spills to a temp.

This will lead to huge diffs for tier-0 so I will do this later after I investigated the diff.

**Comment by AndyAyersMS** [comment]
Latest [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=890440&view=ms.vss-build-web.run-extensions-tab) look pretty good. Seems like if we're going to allocate and store an array into a static it is generally better to do the array creation before fetching the static's address.

Can you look at what happens if we also do this when not optimizing?

**Comment by hez2010** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=892748&view=ms.vss-build-web.run-extensions-tab)

**Comment by AndyAyersMS** [comment]
> [Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=892748&view=ms.vss-build-web.run-extensions-tab)

Ah, ok. Let's undo that last commit and just do this when optimizaing.

Suggests we should probably look into doing the same thing for `newobj`, or never split up front, and instead search and split in the object allocation code.

**Comment by MichalPetryka** [comment]
> Suggests we should probably look into doing the same thing for `newobj`, or never split up front, and instead search and split in the object allocation code.

Is a temp not always needed for newobj in order to call the ctor?

**Comment by AndyAyersMS** [comment]
> > Suggests we should probably look into doing the same thing for `newobj`, or never split up front, and instead search and split in the object allocation code.
> 
> Is a temp not always needed for newobj in order to call the ctor?

It is today, but you could imagine arranging things so that the ctor returns the object, perhaps.

**Comment by hez2010** [comment]
> Ah, ok. Let's undo that last commit and just do this when optimizing.

Done.

**Review by AndyAyersMS — APPROVED** [review]
Thanks!

**Comment by AndyAyersMS** [comment]
I think the x86 failure was fixed, going to merge and see if we can get a green CI.

**Pull request merged**
