### PR TITLE
Alter amount of tests that run per PR for mono mobile configurations

### PR DESCRIPTION
**Pull request by steveisok**
In an effort to better utilize CI resources, this change will only run the System.Runtime library test per PR for Android and Wasm configurations.  The full libraries and runtime tests will move to only run on the post-PR validation pipeline.

The summary of changes are:

- System.Runtime tests will only trigger per PR for Android x86/x64 and Wasm AOT / EAT
- All mono runtime builds will only run on the post PR validation build (rolling build)
- WasmBuildTests will only run on the post PR validation build (rolling build)
- Wasm on Windows will only build

Note: iOS/tvOS/MacCatalyst are excluded until https://github.com/dotnet/runtime/pull/59503 lands

### CODE REVIEW

**Comment by fanyang-mono** [comment]
I feel the same as Larry. Are we experiencing any machine shortage or PR running for too long?

**Review by fanyang-mono — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]

**Review by lewing — APPROVED** [review]
:shipit:

**Comment by lewing** [comment]
@steveisok should we have an issue to track the future adjustments/refinements?

**Review by radical — APPROVED** [review]

**Comment by lewing** [comment]
image
🤷

**Pull request merged**
