### PR TITLE
Update the assert to correctly check if a tree with value has non-zero destination registers

### LINKED ISSUE #81356: JIT: Assertion failed '!tree->IsUnusedValue() || (dstCount != 0)' during 'Linear scan register alloc'
```csharp
// Generated by Fuzzlyn v1.5 on 2023-01-29 16:01:38
// Run on X64 Windows
// Seed: 1558527855815242520
// Reduced from 309.9 KiB to 0.2 KiB in 00:06:49
// Hits JIT assert in Debug:
// Assertion failed '!tree->IsUnusedValue() || (dstCount != 0)' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Linear scan register alloc' (IL size 19; hash 0xade6b36b; MinOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\lsraxarch.cpp Line: 685
// 
public class Program
{
    public static byte[] s_130;
    public static void Main()
    {
        ulong vr5 = default(ulong);
        byte vr4 = (byte)(((byte)vr5 & 0) * s_130[0]);
    }
}
```

Bisected to 08f13ddf7760653d62077c1b46dee1c0335c2e0e, cc @JulieLeeMSFT

### PR DESCRIPTION
**Pull request by kunalspathak**
In https://github.com/dotnet/runtime/pull/77078, we based an indir to `NOP` and in MinOpts, since we do not perform liveness, it stays until LSRA. In LSRA, during building the nodes, we should be checking if a tree has a value, the number of destination registers should be non-zero. Instead, we were checking if tree has unused value, it should have non-zero destination registers, which was not making sense. Updated the assert.

Fixes: https://github.com/dotnet/runtime/issues/81356

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Review by jakobbotsch — APPROVED** [review]
Can we remove the node in lowering instead of creating a NOP? All other places in lowering do `BlockRange().Remove(node)` instead of bashing to a NOP.

It's also odd to me that `GenTree::IsUnusedValue()` returns true for the NOP here, given that it isn't even a value.

**Comment by kunalspathak** [comment]
> Can we remove the node in lowering instead of creating a NOP? All other places in lowering do `BlockRange().Remove(node)` instead of bashing to a NOP.
> 
Ah, my impression was that this would have got removed with liveness update after lowering, but didn't realize I could just delete it. The fix in lsra is still needed though because that assert was wrong.

> It's also odd to me that `GenTree::IsUnusedValue()` returns true for the NOP here, given that it isn't even a value.

I am not sure about it, but we do call `TransformUnusedIndirection()` if unused value but then there is a gap of not clearing the value?

**Comment by JulieLeeMSFT** [comment]
Thanks @kunalspathak for this fix.

**Review by JulieLeeMSFT — APPROVED** [review]

**Pull request merged**
