### PR TITLE
JIT: Remove LclVarDsc::lvExactSize and LclVarDsc::lvSIMDType

### PR DESCRIPTION
**Pull request by jakobbotsch**
Turn these into functions.

`LclVarDsc` shrinks by 8 bytes on win-x64, diff of layout: https://www.diffchecker.com/YcUPNTpu

### CODE REVIEW

**Comment by jakobbotsch** [comment]
Diffs look to be because we were forgetting to set `lvSIMDType = 1` for this particular local:
https://github.com/dotnet/runtime/blob/52652185bf5331ecf651ad4c0c575da720cab3c1/src/coreclr/jit/simd.cpp#L120
That means it wasn't being aligned in the stack frame before.

**Comment by jakobbotsch** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201847&view=ms.vss-build-web.run-extensions-tab). As mentioned above, diffs are due to some more alignment for some SIMD locals. It is also a slight TP regression (0.02% to 0.05% in minopts, 0.08% to 0.10% in FullOpts) to remove this since calling `lvExactSize` is more expensive. I think the trade off is worth it -- we drop 8 bytes from every `LclVarDsc` and we don't keep a redundant field around that needs to be kept up to date (in both #83036 and #83306 I had failures from forgetting to set this field for SIMD types).

cc @dotnet/jit-contrib

**Review by EgorBo — APPROVED** [review]
LGTM, `LclVarDsc` is fairly sensitive to changes, e.g. I locally re-shuffled some fields in it and got -0.25% TP improvement while keeping size the same, will file a PR to cover TP regressions you hit

**Comment by jakobbotsch** [comment]
> over TP regressions you hit

I think we can just ignore these kinds of TP regressions, that's what we've done previously. If the native compiler decides that it is more efficient to emit shifts/adds instead of `imul`, then we should trust in it. It just further shows that the methodology of counting instructions executed is not a silver bullet (not that we thought that before).

**Review by tannergooding — APPROVED** [review]

**Pull request merged**
