### PR TITLE
NTLM: Enable MIC generation with the gss-ntlmssp provider

### PR DESCRIPTION
**Pull request by filipnavara**
Ref: https://github.com/dotnet/runtime/pull/65611#discussion_r810547850

The MIC is currently not sent due to [this code branch](https://github.com/gssapi/gss-ntlmssp/blob/9b6493b1419d615e347d67c636fd238aa4d0f780/src/gss_auth.c#L77-L83).

It seems like there may be a way to enforce it by calling `gss_inquire_sec_context_by_oid` with the [`1.3.6.1.4.1.7165.655.1.2` OID](https://github.com/gssapi/gss-ntlmssp/blob/c0a02166f20dac6a1712aaf2fd15757a02f8586d/src/gssapi_ntlmssp.h#L44). The provider implements it [here](https://github.com/gssapi/gss-ntlmssp/blob/1cbc124fc15d1fad1e34e885f98e449da2dbcf21/src/gss_sec_ctx.c#L1218-L1251).

### CODE REVIEW

**Comment by filipnavara** [comment]
Closing for now since the necessary tests are missing and the MIC calculation doesn't pass them. Either the tests are incorrect (even though they pass on Windows and macOS) or the calculation in gss-ntlmssp is incorrect.

**Comment by filipnavara** [comment]
Preliminary analysis seems to suggest that gss-ntlmssp incorrectly interprets the lack of version negotiation as lock of the VERSION field in the messages. The MIC offset would those be shifted. This doesn't seem to be in line with the specification which says the VERSION should still be present be can be set to zeros.

**Comment by wfurt** [comment]
BTW I'm not sure if we should force it anyhow. We certainly don't on macOS so if gss-ntlmssp does not do it on it's own that looks like improvement that can be made there.

**Comment by filipnavara** [comment]
macOS always generates it and so does any recent version of Windows. I already filed bug on gss-ntlmssp to fix it there.

**Pull request closed without merging**
