### PR TITLE
Remove support for deprecated obs-fold in header values

### LINKED ISSUE #50597: HttpRequestMessage.Headers.Add should validate the header value
As a security protection it would be nice if `HttpRequestMessage.Headers.Add` would check whether the value contains new lines. If you are allowing your users to send a certain header value, many people probably don't think about the following attack vector:

```c#
var headerValue = "<user-input>";
httpRequestMessage.Headers.Add("x-my-header", headerValue);

// user-input == "test\nx-other-header=value" // whoups
```

What do you think?

Best regards,
D.R.

### PR DESCRIPTION
**Pull request by MihaZupan**
[RFC7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.4) deprecated support for line-folding in header values (emphasis mine):

> Historically, HTTP header field values could be extended over
   multiple lines by preceding each extra line with at least one space
   or horizontal tab (obs-fold).  This specification deprecates such
   line folding except within the message/http media type
   (Section 8.3.1).  **A sender MUST NOT generate a message that includes
   line folding** (i.e., that has any field-value that contains a match to
   the obs-fold rule) unless the message is intended for packaging
   within the message/http media type.

Previously headers like `foo: a\r\n b` were considered valid (space following new line).

This PR removes obs-fold support from header validation, instead treating all new line characters as invalid.

On the receiving side, servers `MAY` accept obs-fold as long as they replace new lines with spaces.
>  A server that receives an obs-fold in a request message that is not
   within a message/http container MUST either reject the message by
   sending a 400 (Bad Request), preferably with a representation
   explaining that obsolete line folding is unacceptable, **or replace
   each received obs-fold with one or more SP octets prior to
   interpreting the field value** or forwarding the message downstream.

Kestrel will treat the whole request as invalid and close the connection when receiving such a header.
HttpClient today [does accept them in responses](https://github.com/dotnet/runtime/blob/d3ed5a9ede4ba138fa352c1496743fba1dacd912/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L1473-L1530) - this PR does not change that.

Fixes #50597

### CODE REVIEW

**Comment by geoffkizer** [comment]
What's the motivation for doing this?

I'm concerned that we will break some customer that is relying on this.

**Review by geoffkizer — APPROVED** [review]

**Review by geoffkizer — DISMISSED** [review]
Actually, I think this is missing some relevant changes.

HttpRuleParser.GetWhitespaceLength should be updated.

**Comment by MihaZupan** [comment]
Note: the change may seem huge, but it's 95% test changes

Product changes:
- Changed `ContainsInvalidNewLine` to `ContainsNewLine`
- Removed CRLF support from `HttpRuleParser.GetWhitespaceLength`
- Added CRLF check to `HttpRuleParser.GetExpressionLength`, `NameValueHeaderValue`'s `CheckValueFormat`, `HttpRequestHeaders.From`* and `AuthenticationHeaderValue`'s `parameter`

*after #52794, setting the `From` property would bypass new line checks.

**Review by stephentoub — APPROVED** [review]
Product changes LGTM, and I skimmed the tests.  Do we have tests that validate all forms of newline are still allowed with TryAddWithoutValidation and NonValidated headers?

**Comment by MihaZupan** [comment]
Yes, I added a bunch of new-line combinations to this `TryAddWithoutValidation`/`NonValidated` test

https://github.com/dotnet/runtime/blob/3f3e304f7efc2a8ee13afce1343e2fbedf3accc6/src/libraries/System.Net.Http/tests/UnitTests/Headers/HttpHeadersTest.cs#L332-L334

**Comment by geoffkizer** [comment]
> Do we have tests that validate all forms of newline are still allowed with TryAddWithoutValidation and NonValidated headers?

I'm looking at the tests you referenced @MihaZupan and it looks like all forms of newline are NOT allowed with TryAddWithoutValidation. 

In particular it looks like the HeaderValuesWithNewLines enumerable is explicitly testing that we disallow these.

Am I missing something here? I thought the idea was to continue to allow obs-fold when using TryAddWithoutValidation but to restrict it elsewhere. Is this broken now?

**Comment by MihaZupan** [comment]
@geoffkizer We continue to do no validation with TryAddWithoutValidation. The test name is bad, but we are testing that new lines added without validation will be present when we enumerate without validation.
https://github.com/dotnet/runtime/blob/3f3e304f7efc2a8ee13afce1343e2fbedf3accc6/src/libraries/System.Net.Http/tests/UnitTests/Headers/HttpHeadersTest.cs#L344 

It is also testing that accessing the field with validation will result in its removal.

**Comment by MihaZupan** [comment]
If you access a header with validation and we consider it as invalid, it will be removed from the collection. This has been the existing behavior.

The change is that now we treat any new lines as invalid - even if it would have been a valid obs fold.

In other words, you can only work with obs-folds if you add them without validation and read them without validation.

What behavior did you have in mind as desired here?

**Pull request merged**
