### PR TITLE
[release/6.0] add missing RIDs

### PR DESCRIPTION
**Pull request by wfurt**
This brings it closer to current main. The changes are

- macOS 13
- Android 32
- Ubuntu 23.04

It is not clear to my why we see big difference in Alpine. It was no touch this tome so perhaps it was not properly generated before.

### CODE REVIEW

**Review by carlossanlop — APPROVED** [review]
OOB package changes look good. Seems most of the json changes are just sections moved alphabetically. The actual new items are android.32, osx.13 and ubuntu.23.04.

cc @mmitche @rbhanda this is PR 1/2 that we need to wait for. THe other one is for 7.0.

**Comment by carlossanlop** [comment]
@wfurt the failures are related to the change. Can you please take a look?

**Comment by wfurt** [comment]
let me check.

**Comment by wfurt** [comment]
it seems like the test was updated as part of https://github.com/dotnet/runtime/pull/75371
I opportunistically pushed update and I'll do more tests once my full build is done.

**Comment by carlossanlop** [comment]
CI passed.

**Pull request merged**
