### PR TITLE
Don't apply IMAGE_REL_BASED_REL32 when address doesn't belong to current section

### PR DESCRIPTION
**Pull request by echesakov**

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@BruceForstall PTAL

**Review by BruceForstall — APPROVED** [review]
LGTM; thanks!

Note that there are still chk/rel asm diffs, but no REL32 reloc warnings. So, you shouldn't close #66155

**Comment by echesakovMSFT** [comment]
> LGTM; thanks!
> 
> Note that there are still chk/rel asm diffs, but no REL32 reloc warnings. 

There are (intermittent) diffs that I see when running on M1 when`b #label` with reloc can be encoded in code that corresponds to jit1 but not with jit2 code. As a result, there are diffs when the code is compared by NearDiffer but no textual diffs since in the JitDisasm such instructions will look the same. 

Maybe, this is what is observed in chk/rel asm diffs?

> So, you shouldn't close #66155

Sure, I removed the "Fixes ..." statement from the initial post.

**Comment by BruceForstall** [comment]
> Maybe, this is what is observed in chk/rel asm diffs?

Well, the diffs are win/linux-x64, so it would be something different.

> There are (intermittent) diffs that I see when running on M1 when`b #label` with reloc can be encoded in code that corresponds to jit1 but not with jit2 code.

Seems like the near differ should account for relocations. Maybe it doesn't see the relocations currently?

**Pull request merged**
