### PR TITLE
Arm: Free up upper-half register that was not ready because of its association with busy lower-half register

### PR DESCRIPTION
**Pull request by kunalspathak**
With https://github.com/dotnet/runtime/pull/107493, we were not releasing the upper half register from getting resolved, which was held back due to the fact that the lower half was occupied by a `TYP_DOUBLE` interval. However, when we free up the lower half, we should also mark the upper-half target as ready for resolution.

Fixes: #https://github.com/dotnet/runtime/issues/107621

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib @AndyAyersMS

**Review by AndyAyersMS — APPROVED** [review]
Maybe you could run fuzzlyn on this PR?

**Comment by kunalspathak** [comment]
> Maybe you could run fuzzlyn on this PR?

yes, thanks for reminding. Wanted to run after CI is green, but forgot.

**Comment by kunalspathak** [comment]
No Fuzzlyn failures on linux/arm

**Pull request merged**
