### PR TITLE
[WIP] Fix setting creation date for OSX

### PR DESCRIPTION
**Pull request by hamarb123**
See issue #39132. WIP.

### CODE REVIEW

**Comment by danmosemsft** [comment]
You should be able to spread FileStatus over several files as a partial struct in order to share as much as possible with the "other Unix" and have an OSX file only for the Mac specific members. This is a pattern we use all over the sources. Eg., FileSystemEntry.*.cs

**Comment by hamarb123** [comment]
> You should be able to spread FileStatus over several files as a partial struct in order to share as much as possible with the "other Unix" and have an OSX file only for the Mac specific members. This is a pattern we use all over the sources. Eg., FileSystemEntry.*.cs

@danmosemsft okay, I will fix that shortly.

**Comment by danmosemsft** [comment]
Thanks for working on this. It might be best to close this PR and reopen when you're ready for review. I assume you have a mac locally to build and test on.

If you have it open like this, it uses up a lot of CI time. Each time you push it kicks off a gazillion new jobs involving 10's or 100 machines even if it's just to fix a typo. Better to  work locally, get tests passing locally, then create the PR when you're ready for review and CI.

**Comment by hamarb123** [comment]
@danmosemsft okay, I will do that.

**Pull request closed without merging**
