### PR TITLE
[release/7.0-preview5] Revert "[mono][interp] Add tiering within interpreter (#68823)"

### PR DESCRIPTION
**Pull request by radical**
This reverts commit 962a455c774177c1bd081277217481a5e9242099.

Prompted by https://github.com/dotnet/runtime/issues/69864, and https://github.com/dotnet/runtime/issues/69868 .

### CODE REVIEW

**Review by lewing — APPROVED** [review]
This got pulled into the preview and we'd like to keep it out

**Comment by lewing** [comment]
@mmitche just a heads up that we want to roll this back out of p5

**Review by BrzVlad — APPROVED** [review]

**Comment by carlossanlop** [comment]
@radical @lewing this backport needs Tactics approval.

**Comment by carlossanlop** [comment]
Approved by Tactics via email.

**Comment by carlossanlop** [comment]
@radical @lewing there are CI failures. Are they related to this change, or can I merge this?

**Comment by radical** [comment]
The failures seem to be timeouts due to infra issues. Looking at some randomly picked tests, they passed but helix still thinks that they failed.

**Pull request merged**
