### PR TITLE
Rename IntegralRange::IsPositive() to IsNonNegative to be accurate

### PR DESCRIPTION
**Pull request by BruceForstall**
Also, add a few `const` in various places.

### CODE REVIEW

**Comment by BruceForstall** [comment]
Very minor change. @AndyAyersMS PTAL
cc @dotnet/jit-contrib

**Review by kunalspathak — APPROVED** [review]
LGTM. What was the reason for this change?

**Comment by BruceForstall** [comment]
> LGTM. What was the reason for this change?

It bothered me that the name was mathematically incorrect, and thus confusing.

**Comment by tannergooding** [comment]
> It bothered me that the name was mathematically incorrect, and thus confusing.

Worth noting that whether or not `0` is considered "positive" depends on many different factors, including domain you're working in and potentially country you're from as some teach it differently.

For types such as float/double which include both `+0` and `-0`, we differentiate them such that `+0` is positive and `-0` is negative. The generic math APIs exposed from the BCL expose an `IsPositive` which correspondingly treats `0` as positive for consistency (it's effectively an "is sign bit set or unset").

**Comment by BruceForstall** [comment]
Interesting observations. This is specifically in a function for integral ranges, so the FP `+0/-0` issue doesn't appear.

**Comment by tannergooding** [comment]
Right, I think it's likely clearer as `IsNonNegative`; more just giving some extra context as to where it does sometimes differ and that we treat integral `0` as "positive" in the BCL for consistency across all generic types.

**Comment by AndyAyersMS** [comment]
Late to the party, but LGTM too.

**Pull request merged**
