### PR TITLE
Typename parsing cleanup

### PR DESCRIPTION
**Pull request by jkotas**
- Remove unnecessary System.Type wrapper for type name parsing in tools. Create the type directly from the parsed name.
- Rename S.R.TypeNameParser to S.R.TypeNameResolver to avoid name collisions with S.R.M.TypeNameParser
- Move type name Unescape and Split helpers into dedicated helper type
- Other cleanup

### CODE REVIEW

**Comment by jkotas** [comment]
@MichalStrehovsky Could you please review this PR when you get a chance? The type name parsing in the managed type system is the most substantial change. It sets up the ground for replacing `AssemblyName` with `AssemblyNameInfo` in the managed type system.

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky Could you please review this PR when you get a chance? The type name parsing in the managed type system is the most substantial change. It sets up the ground for replacing `AssemblyName` with `AssemblyNameInfo` in the managed type system.

There are test build failures, but otherwise looks reasonable to me, thanks for setting this towards a AssemblyNameInfo path!

**Review by buyaa-n — APPROVED** [review]
LGTM, thank you!

**Review by adamsitnik — COMMENTED** [review]
LGTM, thank you @jkotas!

**Pull request merged**
