### PR TITLE
Improve IndexOfAnyValues throughput for needles with 0

### PR DESCRIPTION
**Pull request by MihaZupan**
Increases `IndexOfAny` throughput by 25-40% for values that contain a 0.

Instead of doing "is ascii" detection at the end as a secondary step to rule out false positives, we can effectively merge it into the "pack sources" step in a cheaper way.

|             Method |  Toolchain | Length |     Mean |   Error | Ratio | Code Size |
|------------------- |----------- |------- |---------:|--------:|------:|----------:|
| IndexOfAnyWithZero |       main |  10000 | 414.4 ns | 1.17 ns |  1.38 |     682 B |
| IndexOfAnyWithZero |         pr |  10000 | 301.2 ns | 1.15 ns |  1.00 |     556 B |

Codegen difference: https://www.diffchecker.com/DVRMVOkA

The main loop with AVX2
image

This should help with Regex after #83992, and with [ASP.NET's header validation](https://github.com/dotnet/aspnetcore/blob/249bde026d84d8a24f9e8fc97ac1074248d9d8b1/src/Shared/ServerInfrastructure/HttpCharacters.cs#L36-L39).

### CODE REVIEW

**Comment by stephentoub** [comment]
Contributes to https://github.com/dotnet/runtime/issues/84139

**Comment by MihaZupan** [comment]
_Bump_

Can this one be merged?

**Review by EgorBo — APPROVED** [review]

**Comment by sebastienros** [comment]
@MihaZupan mind doing a quick benchmark on fortunes to check for this one https://github.com/dotnet/runtime/issues/86113

crank command before the change:

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/scenarios/database.benchmarks.yml --scenario fortunes --profile aspnet-citrine-win --application.framework net8.0 --application.aspNetCoreVersion 8.0.0-preview.5.23259.4 --application.runtimeVersion 8.0.0-preview.5.23259.2 --application.sdkVersion 8.0.100-preview.5.23259.3
```

**Comment by MihaZupan** [comment]
I can check, but I'd be quite surprised if this regressed anything (especially fortunes)

**Comment by MihaZupan** [comment]
Tried the following commits:
1. 1b56e9667da4b447182d14a08966fb1ed739232f (PR #84184)
2. e241509952cc6300198ce4c31f2220a3f4ef15a9 (commit just before nr. 3)
3. 58a13652d0c1811ecf5684a4e750fe796d5cde93 (PR #85894)

| load                   | 1         | 2         |         | 3         |        |
| ---------------------- | --------- | --------- | ------- | --------- | ------ |
| Requests/sec           |   304,458 |   302,716 |  -0.57% |   281,044 | -7.69% |
| Requests               | 4,585,264 | 4,570,922 |  -0.31% | 4,243,602 | -7.45% |
| Bad responses          |         0 |         0 |         |         0 |        |

**Pull request merged**
