### PR TITLE
Switch s390x and PPC64 to Mariner host OS, not ancient Ubuntu

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Comment by am11** [comment]
Should we move new ones directly to [azurelinux-3.0](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/tree/main/src/azurelinux/3.0) (CBL-mariner rebranded)?

**Comment by directhex** [comment]
I'm not opposed, but that'll take longer (we already had these Mariner 2 images lying around unused for the past X months, it'd take a little while to get new 3 images built)

**Comment by am11** [comment]
Sounds good. BTW, I found it a bit strange/unnecessary that azurelinux tags have -net8 suffix (rarely we add/remove dependencies and mostly we just add a new one).

**Comment by directhex** [comment]
> Sounds good. BTW, I found it a bit strange/unnecessary that azurelinux tags have -net8 suffix (rarely we add/remove dependencies and mostly we just add a new one).

I admit that suffix was a large part of my "er, no idea what's going on here, I'll just stick with 2"

**Review by akoeplinger — APPROVED** [review]
Awesome!

**Comment by akoeplinger** [comment]
>  BTW, I found it a bit strange/unnecessary that azurelinux tags have -net8 suffix (rarely we add/remove dependencies and mostly we just add a new one).

We just hit this today with the wasm images where updating a dependency would break existing image usages so in general I prefer being explicit.

**Comment by akoeplinger** [comment]
The s390x failures are known: https://github.com/dotnet/runtime/issues/101380#issuecomment-2069386083

**Comment by akoeplinger** [comment]
/ba-g the runtime-community pipeline passed which is all that counts

**Comment by am11** [comment]
> We just hit this today with the wasm images where updating a dependency would break existing image usages so in general I prefer being explicit.

That is not a new problem. We've been using docker tags (pinned vs. floating) to solve it when needed. New convention of hardcoding .NET version in the tag is going to produce much noise and it's wasteful when there is no 1:1 relationship.

**Pull request merged**
