### PR TITLE
Enable CLS Compliance on Diagnostics Libraries

### PR DESCRIPTION
**Pull request by tarekgh**
This change will allow the consumers of these libraries not to be forced to set CLS Compliance off.

### CODE REVIEW

**Comment by noahfalk** [comment]
I assume the affect of this change is that a CLSCompliant attribute at assembly scope changes from false to true (or maybe goes away if that is the default), and now other libraries that reference this one don't get compiler warnings? That sounds pretty good to me.

Are you aware of any scenario where the experience gets worse? I can't think of anything offhand.

**Review by Tratcher — APPROVED** [review]

**Comment by tarekgh** [comment]
> I assume the affect of this change is that a CLSCompliant attribute at assembly scope changes from false to true (or maybe goes away if that is the default)

By default, if the `CLSCompliant ` is not showing in the assembly, this assembly will not be compliant by default. 
**In our builds** when specifying `<CLSCompliant>false</CLSCompliant>` in the csproj, this attribute will be fully removed, and the assembly will not tagged at all which make this assembly is **NOT** compliant. But, if the csproj doesn't have `<CLSCompliant>`,  teh build manually add `<CLSCompliant>true</CLSCompliant>` and making the assembly compliant. 

> Are you aware of any scenario where the experience gets worse? I can't think of anything offhand.

I am not either, adding @ericstj @ViktorHofer if they can think in any broken scenario after this change.

**Comment by ericstj** [comment]
I'm not aware of anything breaking by adding CLSCompliant(true).

**Review by noahfalk — APPROVED** [review]
👍

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
