### PR TITLE
Refactor `fgMorphCast`

### PR DESCRIPTION
**Pull request by SingleAccretion**
With #55186 merged, I was looking to take advantage of `IntegralRange` in `fgMorphCast`, but it turned out some refactoring was first in order, mainly to get rid of questionable & duplicated code. So that's what this PR is about. See the commit messages for the description of the changes.

Also some comments have been added.

Diffs for this change: [`win-x64`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-59713/win-x64.md),  [`win-x86`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-59713/win-x86.md), [`linux-arm`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-59713/linux-arm.md).

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by SingleAccretion** [comment]
Stress failures appear to be #59794.

**Review by BruceForstall — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
