### PR TITLE
consume MsQuic 2.1 for windows ARM64 builds

### PR DESCRIPTION
**Pull request by wfurt**
We don't have Windows ARM pipeline for msquic transport. This change consumes ARM bits published by msquic directly. 
(This does not allow us easily consume daily builds & fixes but that should OK for now)

### CODE REVIEW

**Comment by wfurt** [comment]
btw
```
file artifacts/bin/testhost/net7.0-windows-Debug-arm64/shared/Microsoft.NETCore.App/7.0.0/msquic.dll
artifacts/bin/testhost/net7.0-windows-Debug-arm64/shared/Microsoft.NETCore.App/7.0.0/msquic.dll: PE32+ executable (DLL) (console) Aarch64, for MS Windows
```

**Comment by rzikm** [comment]
I thought you had a PR to dotnet/msquic which would build the DLL for ARM so we could consume it as we do for x86/x64

**Comment by karelz** [comment]
@rzikm building on arm is problematic - this is easiest route. Even for Linux we are looking into cross-compilation on our side.

**Review by karelz — APPROVED** [review]

**Review by rzikm — APPROVED** [review]

**Comment by karelz** [comment]
Windows arm64 pipeline was cancelled - https://github.com/dotnet/runtime/runs/7782294163
- `runtime-extra-platforms (Libraries Test Run release coreclr windows arm64 Release)`

**Comment by wfurt** [comment]
It was not meant as permanent change. Sees like we don't have hardware so we will not get any windows arm tests @karelz.

**Comment by rzikm** [comment]
Tested locally on Volterra device:

```
PS C:\source\runtime\artifacts\bin\System.Net.Quic.Functional.Tests\Debug\net7.0-windows> ..\..\..\testhost\net7.0-windows-Debug-arm64\dotnet.exe exec --runtimeconfig .\System.Net.Quic.Functional.Tests.runtimeconfig.json --depsfile .\System.Net.Quic.Functional.Tests.deps.json .\xunit.console.dll .\System.Net.Quic.Functional.Tests.dll -notrait category=failing -notrait category=outerloop
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 7.0.0-dev)
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 101 of 110 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 8)
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.UnsupportedPlatforms_ThrowsPlatformNotSupportedException [SKIP]
      Condition(s) not met: "IsQuicUnsupported"
  Finished:    System.Net.Quic.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Quic.Functional.Tests  Total: 320, Errors: 0, Failed: 0, Skipped: 1, Time: 71.638s
```

**Pull request merged**
