### PR TITLE
Add DefaultMemberAttribute to Test.CoreLib

### LINKED ISSUE #107953: Test.CoreLib is missing DefaultMemberAttribute
### Description

See https://github.com/dotnet/roslyn/issues/75032

### Reproduction Steps

N/A

### Expected behavior

DefaultMemberAttribute is defined in the core library

### Actual behavior

DefaultMemberAttribute is not defined in the core library

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

Compiler team might decide to report an error for an indexer declaration when the attribute is missing. This will cause a build break of the library after upgrade if the attribute is missing.

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes #107953.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
> can you verify that https://github.com/dotnet/runtime/pull/108236 fixes this? I would like to avoid bothering the shiproom with this twice if this doesn't fix it.

The attribute definition looks fine to me, however I cannot tell what effect, if any, the change is going to have on the specific project/library.

Assuming Test.CoreLib contains definition for `System.Object` and doesn't reference any other assemblies, the fact that the issue  is addressed can verified by checking the following:
1. Metadata for the library include definition for the attribute
2. A type in the library that defines an indexer (there is at least one existing type like that) has the attribute applied to its definition in metadata. The name of the property implementing the indexer (usually it is "Item") is passed to attribute's constructor.
3. When the library is used as a metadata reference (rather than a compilation/project reference) it is possible to consume the indexer from another assembly by using an element access syntax (```[...]```).

**Comment by MichalStrehovsky** [comment]
> Assuming Test.CoreLib contains definition for `System.Object` and doesn't reference any other assemblies

Yep.

> Metadata for the library include definition for the attribute

Yep,

> A type in the library that defines an indexer (there is at least one existing type like that) has the attribute applied to its definition in metadata. The name of the property implementing the indexer (usually it is "Item") is passed to attribute's constructor. Compiler is responsible for applying this attribute to the type definition, it does that if the attribute definition is available.

There is only one such type (`MethodTableList`) that now has the attribute on the type definition.

> When the library is used as a metadata reference (rather than a compilation/project reference) it is possible to consume the indexer from another assembly by using an element access syntax ([...]).

`MethodTableList` is a private class so it cannot be referenced from anywhere else.

**Comment by AlekseyTs** [comment]
> `MethodTableList` is a private class so it cannot be referenced from anywhere else.

The verification can be done by temporarily (for the duration of the validation process) changing the accessibility of the type, or by adding a new temporary accessible type with an indexer.

**Comment by MichalStrehovsky** [comment]
> The verification can be done by temporarily (for the duration of the validation process) changing the accessibility of the type, or by adding a new temporary accessible type with an indexer.

I added a temporary public type and accessing the indexer from a different assembly works.

**Comment by AlekseyTs** [comment]
Sounds like the issue is addressed. To increase the level of confidence, consider confirming that the validation fails when the change is reverted

**Comment by MichalStrehovsky** [comment]
> Sounds like the issue is addressed. To increase the level of confidence, consider confirming that the validation fails when the change is reverted

I get `error CS0021: Cannot apply indexing with [] to an expression of type 'Lol'` when I remove the attribute from corelib.

**Review by AlekseyTs — APPROVED** [review]

**Pull request merged**
