### PR TITLE
[release/6.0] Add a RID for Fedora 39

### PR DESCRIPTION
**Pull request by omajid**
Backport of https://github.com/dotnet/runtime/pull/82208 and https://github.com/dotnet/runtime/pull/82185

### CODE REVIEW

**Comment by carlossanlop** [comment]
@omajid this one also needs the Microsoft.NETCore.Platforms.csproj changes as explained in the 7.0 PR. Can you please add them?

**Review by carlossanlop — CHANGES_REQUESTED** [review]
Needs OOB changes.

@wfurt do you mind reviewing this?

**Review by carlossanlop — APPROVED** [review]
Added the required OOB changes. Got offline confirmation from @wfurt that the changes look good.
Will merge after the CI is done (had to rebase).

**Review by wfurt — APPROVED** [review]
LGTM

**Pull request merged**
