### PR TITLE
[wasm] Enable InteropServices on browser-wasm

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Comment by lewing** [comment]
Looks like #39187 is passing but we need to disable the posix signal bits now

**Comment by lewing** [comment]
cc @akoeplinger re https://github.com/dotnet/runtime/pull/55643

**Review by mdh1418 — APPROVED** [review]
Looks good to me!

**Comment by akoeplinger** [comment]
Pushed a commit that should fix the tests build

**Comment by lewing** [comment]
@vargaz can you take a look at the failures here

**Comment by akoeplinger** [comment]
Failures are here: https://dev.azure.com/dnceng/public/_build/results?buildId=1272908&view=results

Console log shows: `* Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/mini.c:4377`

**Comment by lewing** [comment]
```
[12:42:07] fail: ==== JS stack trace =========================================
                 
[12:42:07] fail: 
                 
[12:42:07] fail: Security context: 0x3a7e0820dca9 <JSObject>#0#
                 
[12:42:07] fail:     0: builtin exit frame: trace(this=0x3a7e08203701 <console map = 0x3a7e08240919>#1#,0x3a7e080ac199 <String[78]: c"* Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/mini.c:4377\n">,0x3a7e08203701 <console map = 0x3a7e08240919>#1#)
                 
[12:42:07] fail: 
                 
[12:42:07] fail:     1: 555138 [0x3a7e0840c251] [dotnet.js:1] [bytecode=0x3a7e084436ed offset=127](this=0x3a7e0823e081 <JSGlobal Object>#2#,17057,44975560,4,0,0)
                 
[12:42:07] fail:     2: _emscripten_asm_const_int [0x3a7e082396f9] [dotnet.js:1] [bytecode=0x3a7e08443445 offset=33](this=0x3a7e0823e081 <JSGlobal Object>#2#,555138,5841512,5841488)
                 
[12:42:07] fail:     3: WasmToJsFrame [pc: 0x335b5a553718]
                 
[12:42:07] fail:     4: WASM [008b6e5a], function #5767 (''), pc=0x335b5ac5334b (+0x8b), pos=1301400 (+77)
                 
[12:42:07] fail:     5: WASM [008b6e5a], function #8430 (''), pc=0x335b5ab2ba1d (+0x9d), pos=1711931 (+32)
                 
[12:42:07] fail:     6: WASM [008b6e5a], function #3839 (''), pc=0x335b5ad6acb8 (+0xf8), pos=803272 (+97)
                 
[12:42:07] fail:     7: WASM [008b6e5a], function #603 (''), pc=0x335b5af1c8a7 (+0x47), pos=81631 (+31)
                 
[12:42:07] fail:     8: WASM [008b6e5a], function #124 (''), pc=0x335b5af4503b (+0x3b), pos=21684 (+32)
                 
[12:42:07] fail:     9: WASM [008b6e5a], function #6827 (''), pc=0x335b5abd9be1 (+0x1081), pos=1476576 (+2008)
                 
[12:42:07] fail:    10: JsToWasmFrame [pc: 0x3a7e000826d3]
                 
[12:42:07] fail:    11: invoke_vi [0x3a7e0823a835] [dotnet.js:1] [bytecode=0x3a7e084432c9 offset=31](this=0x3a7e0823e081 <JSGlobal Object>#2#,612,5841672)
                 
[12:42:07] fail:    12: WasmToJsFrame [pc: 0x335b5a5522c0]
                 
[12:42:07] fail:    13: WASM [008b6e5a], function #4089 (''), pc=0x335b5ad48af8 (+0x58), pos=872474 (+21)
                 
[12:42:07] fail:    14: WASM [008b6e5a], function #4389 (''), pc=0x335b5ad1db17 (+0x97), pos=954395 (+57)
                 
[12:42:07] fail:    15: WASM [008b6e5a], function #943 (''), pc=0x335b5aef8bdb (+0x7b), pos=130618 (+66)
                 
[12:42:07] fail:    16: WASM [008b6e5a], function #525 (''), pc=0x335b5af22874 (+0x74), pos=73689 (+39)
                 
[12:42:07] fail:    17: WASM [008b6e5a], function #4200 (''), pc=0x335b5ad39ae9 (+0x1c9), pos=898456 (+225)
                 
[12:42:07] fail:    18: WASM [008b6e5a], function #6036 (''), pc=0x335b5ac3a1ed (+0x8d), pos=1327896 (+46)
                 
[12:42:07] fail:    19: WASM [008b6e5a], function #2547 (''), pc=0x335b5ae2476d (+0x2ed), pos=517452 (+261)
                 
[12:42:07] fail:    20: WASM [008b6e5a], function #2272 (''), pc=0x335b5aa60b32 (+0x11cd2), pos=420184 (+4244)
                 
[12:42:07] fail:    21: WASM [008b6e5a], function #6852 (''), pc=0x335b5abd776c (+0x1cc), pos=1478601 (+205)
                 
[12:42:07] fail:    22: WASM [008b6e5a], function #6669 (''), pc=0x335b5abf1045 (+0xfe5), pos=1442350 (+43)
                 
[12:42:07] fail:    23: WASM [008b6e5a], function #3461 (''), pc=0x335b5ada234b (+0x1eb), pos=707122 (+106)
                 
[12:42:07] fail:    24: WASM [008b6e5a], function #475 (''), pc=0x335b5af25e38 (+0x38), pos=69614 (+38)
                 
[12:42:07] fail:    25: WASM [008b6e5a], function #6304 (''), pc=0x335b5ac1688a (+0x142a), pos=1376904 (+2219)
                 
[12:42:07] fail:    26: WASM [008b6e5a], function #2547 (''), pc=0x335b5ae24a5c (+0x5dc), pos=517605 (+414)
                 
[12:42:07] fail:    27: WASM [008b6e5a], function #2272 (''), pc=0x335b5aa60b32 (+0x11cd2), pos=420184 (+4244)
                 
[12:42:07] fail:    28: WASM [008b6e5a], function #6852 (''), pc=0x335b5a6418a7 (+0x247), pos=1478601 (+205)
                 
[12:42:07] fail:    29: WASM [008b6e5a], function #6669 (''), pc=0x335b5a65e698 (+0xf8), pos=1442350 (+43)
                 
[12:42:07] fail:    30: WASM [008b6e5a], function #3461 (''), pc=0x335b5a85c9c2 (+0x222), pos=707122 (+106)
                 
[12:42:07] fail:    31: WASM [008b6e5a], function #668 (''), pc=0x335b5aa14b15 (+0x95), pos=88473 (+36)
                 
[12:42:07] fail:    32: WASM [008b6e5a], function #6566 ('ib'), pc=0x335b5a66b7fb (+0x11b), pos=1428590 (+97)
                 
[12:42:07] fail:    33: JsToWasmFrame [pc: 0x3a7e00082ed1]
                 
[12:42:07] fail:    34: invoke_method [0x3a7e082cc501] [dotnet.js:1] [bytecode=0x3a7e084a468d offset=46](this=0x3a7e08403159 <Object map = 0x3a7e08253591>#3#)
                 
[12:42:07] fail:    35: arguments adaptor frame: 4->0
                 
[12:42:07] fail:    36: _call_method_with_converted_args [0x3a7e0840a1a1] [dotnet.js:1] [bytecode=0x3a7e084a43d5 offset=64](this=0x3a7e08403159 <Object map = 0x3a7e08253591>#3#,31152160,0,0x3a7e0849e7fd <Object map = 0x3a7e08252c81>#4#,11901192,0x3a7e080403e5 <true>,0x3a7e08040171 <null>)
                 
[12:42:07] fail:    37: call_method [0x3a7e0840a101] [dotnet.js:1] [bytecode=0x3a7e084a3b69 offset=228](this=0x3a7e08403159 <Object map = 0x3a7e08253591>#3#,31152160,0,0x3a7e08210095 <String[1]: #m>,0x3a7e086c01dd <JSArray[1]>#5#)
                 
[12:42:07] fail:    38: /* anonymous */ [0x3a7e086c01ed] [dotnet.js:1] [bytecode=0x3a7e084a1b41 offset=105](this=0x3a7e0823e081 <JSGlobal Object>#2#)
                 
[12:42:07] fail:    39: arguments adaptor frame: 1->0
                 
[12:42:07] fail:    40: call_assembly_entry_point [0x3a7e0840a281] [dotnet.js:1] [bytecode=0x3a7e084572a1 offset=20](this=0x3a7e08403159 <Object map = 0x3a7e08253591>#3#,0x3a7e0840c0b9 <String[18]: "WasmTestRunner.dll">,0x3a7e0848cff9 <JSArray[1]>#6#,0x3a7e08210095 <String[1]: #m>)
                 
[12:42:07] fail:    41: init [0x3a7e0840b531] [runtime.js:362] [bytecode=0x3a7e08456871 offset=787](this=0x3a7e08402a19 <Object map = 0x3a7e0824dc59>#7#)
                 
[12:42:07] fail:    42: loaded_cb [0x3a7e082d6e29] [runtime.js:249] [bytecode=0x3a7e08455d11 offset=105](this=0x3a7e0840b571 <Object map = 0x3a7e0824f1e9>#8#)
                 
[12:42:07] fail:    43: _finalize_startup [0x3a7e0840bc39] [dotnet.js:1] [bytecode=0x3a7e0844f719 offset=474](this=0x3a7e0823df79 <Object map = 0x3a7e082535e1>#9#,0x3a7e0840b571 <Object map = 0x3a7e0824f1e9>#8#,0x3a7e0823ffa9 <Object map = 0x3a7e0824f5a9>#10#)
                 
[12:42:07] fail:    44: onPendingRequestComplete [0x3a7e08426fcd] [dotnet.js:1] [bytecode=0x3a7e082d98a9 offset=52](this=0x3a7e0823e081 <JSGlobal Object>#2#)
                 
[12:42:07] fail:    45: processFetchResponseBuffer [0x3a7e0841261d] [dotnet.js:1] [bytecode=0x3a7e082d8ed9 offset=99](this=0x3a7e0823e081 <JSGlobal Object>#2#,0x3a7e08411551 <Object map = 0x3a7e0824daf1>#11#,0x3a7e08411a4d <String[21]: "dotnet.timezones.blat">,0x3a7e08425a5d <Uint8Array map = 0x3a7e082404e1>#12#)
                 
[12:42:07] fail:    46: StubFrame [pc: 0x55a683d9aef8]
                 
[12:42:07] fail:    47: StubFrame [pc: 0x55a683d06f24]
                 
[12:42:07] fail:    48: EntryFrame [pc: 0x55a683ce48f8]
                 
[12:42:07] fail: =====================
                 
[12:42:07] fail: 
                 
[12:42:07] fail: console.error: * Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/mini.c:4377
```

**Comment by vargaz** [comment]
Needs [UnmanagedCallersOnly] attribute on the callback methods, and the app needs to be built with
/p:WasmBuildNative=true to work.

**Comment by vargaz** [comment]
https://gist.github.com/vargaz/34fa54320ba0c6de400d2b11fecd6dea

**Comment by lewing** [comment]
failure is https://github.com/dotnet/runtime/issues/57221

**Pull request merged**
