### PR TITLE
Update helix images

### PR DESCRIPTION
**Pull request by richlander**
- There are no Alpine 3.19 helix images. Moving to Alpine 3.20 is likely fine for `main` since 3.21 is imminent.
- Updated old distros, like Debian 11 and CentOS Stream 8.
- Updated Fedora to latest.
- Updated a bunch of Ubuntu 20.04 VMs to 22.04.

In general, with the .NET 10 several months away, we should be more aggressive with moving versions forward to avoid multiple steps along the way.

Overlaps with https://github.com/dotnet/runtime/pull/110380.

Supports: https://github.com/dotnet/core/issues/9625

### CODE REVIEW

**Comment by richlander** [comment]
I believe this is clean @carlossanlop. Does that seem right?

**Comment by carlossanlop** [comment]
/ba-g All failures are known and pre-existing: https://github.com/dotnet/runtime/pull/110384/checks?check_run_id=33958613727

**Comment by carlossanlop** [comment]
That browser leg [is stuck](https://dev.azure.com/dnceng-public/public/_build/results?buildId=886864&view=logs&jobId=d4e38924-13a0-58bd-9074-6a4810543e7c), so Build Analysis could not run automatically. I signed-off on it manually using /ba-g.

**Review by carlossanlop — APPROVED** [review]

**Comment by richlander** [comment]
Thanks!

**Pull request merged**
