### PR TITLE
SPMI: Write out improvements/regressions breakdown details

### PR DESCRIPTION
**Pull request by jakobbotsch**
Write out a breakdown of improvements/regressions to be able to gauge better how the improvements stack up against the regressions.

Contributes to #75848

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS 

This is how it looks (first table under 'Details'): https://dev.azure.com/dnceng-public/public/_build/results?buildId=42913&view=ms.vss-build-web.run-extensions-tab

I will of course make sure to revert the JIT change before merging.

**Review by AndyAyersMS — APPROVED** [review]
Thanks -- I think this will be quite helpful in understanding the diffs.

**Comment by BruceForstall** [comment]
Really great work!

However, the `replay_with_asm_diffs` function is getting ridiculous. We need to refactor it into separate functions.

**Comment by jakobbotsch** [comment]
> However, the `replay_with_asm_diffs` function is getting ridiculous. We need to refactor it into separate functions.

You're right. I will keep in mind to do a little refactoring as part of my future PRs.

**Pull request merged**
