### PR TITLE
Simplify devirtualization in crossgen2

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
@MichalStrehovsky suggested in https://github.com/dotnet/runtimelab/pull/437#issuecomment-739783522 that the call to FindMethodOnTypeWithMatchingTypicalMethod may not be required.

@AndyAyersMS Do you happen to remember why you have added it?

**Comment by AndyAyersMS** [comment]
As part of #45526 I asked David what the counterpart was to `GetExactDeclaringType` in the runtime, and this is what he suggested.

**Comment by jkotas** [comment]
The managed type system is always exact. It does not share MethodDesc between types some of the time like the CoreCLR runtime type system that requires the `GetExactDeclaringType`.

I believe that it should be safe to delete this as proposed in this PR.

**Comment by AndyAyersMS** [comment]
Is there a writeup anywhere on how the managed type system differs from the type system in the runtime?

**Comment by jkotas** [comment]
We have write up at https://github.com/dotnet/corert/blob/master/Documentation/botr/type-system.md

The doc does not have an explicit list. Most of the differences fall out from the design. This specific detail is fall out from the pluggable algorithms. 

In CoreCLR type system, MethodDescs have to have 1:1 mapping with entrypoints. It means that the code sharing policy affects when you get exact MethodDescs.

In managed type system, the code sharing policy is one of the pluggable algorithms and it does not have cascading affect on how the type system as a whole works.

**Comment by AndyAyersMS** [comment]
Thanks. I would not have deduced that a pluggable sharing policy implies that there are only exact types.

Given that we're going to support both type systems indefinitely, perhaps it is worth being more explicit on how things differ between the two?

**Review by AndyAyersMS — APPROVED** [review]

**Review by MichalStrehovsky — APPROVED** [review]
Thanks!

**Comment by jkotas** [comment]
> perhaps it is worth being more explicit on how things differ between the two?

https://github.com/dotnet/runtimelab/pull/440. Also, I will look into moving this doc to dotnet/runtime.

**Pull request merged**
