### PR TITLE
Reduce ref/System.Runtime against autogenerated version

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
The auto-generated file has still a lot of diffs - mostly related to Nullable attributes and obsolete attributes.

**Comment by stephentoub** [comment]
> still a lot of diffs - mostly related to Nullable attributes and obsolete attributes

Formatting, or missing/extra attributes?

**Review by stephentoub — APPROVED** [review]

**Comment by jkotas** [comment]
> Formatting, or missing/extra attributes?

Different nullable annotations on  explicitly implemented interfaces are the largest contributor to the remaining diff.

https://github.com/jkotas/runtime/commit/05fc812319151b26292b072d7b0be80738d41788#diff-1d02aa10f6540e37197ff9f090ca1d9eL407

**Comment by stephentoub** [comment]
Interesting.  That looks like a bug in the tool.  For example, `byte` has this in src:
https://github.com/dotnet/runtime/blob/8b92fcdd1e4e80cb3eacf9c1cc9e4c9bbc2dcb03/src/libraries/System.Private.CoreLib/src/System/Byte.cs#L202
which lines up with its current ref:
https://github.com/dotnet/runtime/blob/8b92fcdd1e4e80cb3eacf9c1cc9e4c9bbc2dcb03/src/libraries/System.Runtime/ref/System.Runtime.cs#L696
but the tool is changing it to not have the question mark:
https://github.com/jkotas/runtime/commit/05fc812319151b26292b072d7b0be80738d41788#diff-1d02aa10f6540e37197ff9f090ca1d9eL696

**Comment by jkotas** [comment]
https://github.com/dotnet/arcade/issues/4722 tracks this problem

**Pull request merged**
