### PR TITLE
Improve SSL platform detection

### PR DESCRIPTION
**Pull request by wfurt**
This is platform detection part from https://github.com/dotnet/runtime/pull/60163 (that is replaced by different change) 
It added more generic support detection for Windows. No production code changes.

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by wfurt** [comment]
While the tests still failed with  #64944, SSL & HTTP runs seems clean on Windows. 
I will merge this and I'll follow-up with more changes as needed.

**Comment by safern** [comment]
@wfurt, seems like we need to backport it manually

**Comment by wfurt** [comment]
yes, this is the main change that gives visibility to availably of given protocol version. I should probably be able to craft the 6.0 version today.

**Pull request merged**
