### PR TITLE
[coop][interp] Fix GC transitions for thunk invoke wrappers

### PR DESCRIPTION
**Pull request by lambdageek**
The code that recognizes GC transition icalls in the interpreter was only assuming that it will see `mono_threads_enter_gc_safe_region_unbalanced` / `mono_threads_exit_gc_safe_region_unbalanced` which are used by managed-to-native wrappers.

In most cases for native-to-managed wrappers the marshaller emits `mono_threads_attach_coop` / `mono_threads_detach_coop` and those are handled elsewhere by setting the `needs_thread_attach` flag on the `InterpMethod`.

However when the `mono_marshal_get_thunk_invoke_wrapper` API is used, we emit a thunk invoke wrapper which uses
`mono_threads_enter_gc_unsafe_region_unbalanced` / `mono_threads_exit_gc_unsafe_region_unbalanced`

Change the thunk invoke wrapper to also use attach_coop/detach_coop.  This makes the thunks a bit more flexible (they can now be called from unattached threads), at the cost of a TLS lookup.  Also fixes interpreter support since they use the existing attach/detach handling.

As an implementation detail, I added a GC Unsafe Transition Builder to the marshaling code.

Fixes a failure seen in https://github.com/dotnet/runtime/pull/81380 in the MonoAPI/MonoMono/Thunks test (exposed by calling a cctor later than previously)

### CODE REVIEW

**Comment by BrzVlad** [comment]
I don't really understand how exactly your other PR induces this failure. Nevertheless, silently doing an attach behind the scenes seems like a hack to me. I think we can either choose to perform explicit attach during thunk invoke wrappers, since it sounds like it doesn't really have a perf cost. Otherwise it sounds like the test has a bug and it relies on some thread being attached. Or maybe the cctor invocation order is not really correct.

**Comment by lambdageek** [comment]
> silently doing an attach behind the scenes seems like a hack to me.

My point is, there is no attach happening.  Any user code that calls the thunk returned by `mono_marshal_get_thunk_invoke_wrapper` must already have done an attach.  So `mono_thread_attach_coop` is just to do the GC Safe -> GC Unsafe transition.

> I think we can either choose to perform explicit attach during thunk invoke wrappers, since it sounds like it doesn't really have a perf cost.

Yea I guess I could just change `emit_thunk_invoke_wrapper` to emit `attach`/`detach` pairs like all the other thunks.  It would be a change of behavior for existing code, but correct code shouldn't notice. and incorrect code will be upgraded to be correct.

**Comment by lambdageek** [comment]
> I don't really understand how exactly your other PR induces this failure

It's the bit about not calling the managed ALC callback for the default ALC.  Early during startup we used to end up in there and run the cctor for the default ALC.  That would trigger a bunch of other early initialization.   With my PR, we don't call that managed callback for the default ALC anymore because it is just the default implementation which always returns NULL.  As a result a lot fewer cctors run at startup. 

In the Thunks.cs test, the cctor for NotImplementedException is one of those cctors.  After the PR, that cctor now runs when we call back into managed after the `thunk_invoke_wrapper`.  And when cctors run they need to take a lock in mono - and attempt to do a GC Unsafe -> GC Safe transition.  Under the interp, the. thunk invoke wrapper was missing the GC Safe -> GC Unsafe transition on entry, so the cctor locking was doing GC Safe -> GC Safe, which is illegal.  It worked on AOT and JIT because those had the correct transition in the wrapper.

**Comment by lambdageek** [comment]
@BrzVlad I updated the PR to change the thunk invoke wrappers to use attach_coop/detach_coop and fall into the existing attach/detach handling in the interpreter

**Comment by lambdageek** [comment]
Implemented `cmpxchg.i32` (and `cmpxchg.i64`) jiterpreter support.  (Attn: @kg)

So we get these results on wasm:

|                       Method |        Job |        Toolchain |      Mean |     Error |    StdDev |    Median | Ratio | RatioSD |
|----------------------------- |----------- |----------------- |----------:|----------:|----------:|----------:|------:|--------:|
| LockPulseUnlockFlatObjNoHash |         PR |         Wasm: PR | 340.94 ns |  0.918 ns |  1.374 ns | 340.78 ns |  0.83 |    0.01 |
| LockPulseUnlockFlatObjNoHash | merge-base | Wasm: merge-base | 410.64 ns |  2.336 ns |  3.496 ns | 411.47 ns |  1.00 |    0.00 |
|                              |            |                  |           |           |           |           |       |         |
|      LockUnlockFlatObjNoHash |         PR |         Wasm: PR | 191.05 ns | 11.016 ns | 16.488 ns | 190.31 ns |  0.85 |    0.13 |
|      LockUnlockFlatObjNoHash | merge-base | Wasm: merge-base | 229.22 ns | 11.732 ns | 17.196 ns | 215.65 ns |  1.00 |    0.00 |
|                              |            |                  |           |           |           |           |       |         |
|            GetHashCodeNoLock |         PR |         Wasm: PR |  57.27 ns | 11.809 ns | 16.936 ns |  57.24 ns |  0.79 |    0.23 |
|            GetHashCodeNoLock | merge-base | Wasm: merge-base |  72.78 ns |  0.408 ns |  0.610 ns |  72.60 ns |  1.00 |    0.00 |
|                              |            |                  |           |           |           |           |       |         |
|     LockUnlockInflatedObject |         PR |         Wasm: PR | 200.53 ns |  1.333 ns |  1.995 ns | 199.85 ns |  0.88 |    0.01 |
|     LockUnlockInflatedObject | merge-base | Wasm: merge-base | 227.66 ns |  0.812 ns |  1.215 ns | 227.89 ns |  1.00 |    0.00 |

**Review by BrzVlad — APPROVED** [review]

**Pull request merged**
