### PR TITLE
[browser] Remove check for user agent when attaching debugger

### LINKED ISSUE #104234: DEBUGGING IS NOT ENABLED when trying to debug .NET 8 Blazor Web project simulating iOS device on edge
### Description

When debugging my blazor applciation (.NET 8, blazor web project using wasm, running on Aspire) in Edge, if I hit f12 and choose any iOS device to simulate and refresh, I see this error in the console and the application crashes:

image

### Reproduction Steps

1. Create a .NET Aspire project and aa Blazor web application within it. 
2. Start debugging the application and hit f12 to open the dev tools for edge
3. Change to an iOS device and refresh.

### Expected behavior

The app should load/debug without erroring

### Actual behavior

Error in description

### Regression?

I assume this has worked in the past and I can see similar issue's logged previously e.g. 

https://github.com/dotnet/runtime/issues/84171

### Known Workarounds

_No response_

### Configuration

.NET 8.0.302
Edge

### Other information

_No response_

### PR DESCRIPTION
**Pull request by maraf**
- Remove check for user agent when attaching debugger
- Attach debugger only when `DebugLevel != 0`
- Don't zero debug level when there are no PDBs in config (embedded PDB can be used)

Fixes https://github.com/dotnet/runtime/issues/104234

### CODE REVIEW

**Comment by thaystg** [comment]
I don't like this check for PDB to decide the debug level because the customer should be able to use embedded pdbs?

**Comment by pavelsavara** [comment]
I think that this change enables debugging on NodeJS, could you please test that it also works ?

**Review by pavelsavara — APPROVED** [review]

**Comment by maraf** [comment]
> could you please test that it also works ?

No, managed debugging doesn't work on NodeJS

**Comment by lewing** [comment]
@maraf this appears to have turned off all optimizations on v8? https://github.com/dotnet/perf-autofiling-issues/issues/39876

**Pull request merged**
