### PR TITLE
Fix redundant MethodInfo lookup in UnixNativeCodeManager

### LINKED ISSUE #75807: [NativeAOT] Unnecessary lookup in TrailingEpilogueInstructionsCount
`UnixNativeCodeManager::TrailingEpilogueInstructionsCount` for `TARGET_ARM64` calls `FindMethodInfo` which is rather expensive. When called from `UnixNativeCodeManager::GetReturnAddressHijackInfo` it is already known so it can be passed over instead of doing extra lookup.

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #75807

### CODE REVIEW

**Comment by jkotas** [comment]
This is the only remaining redundant lookup that is reasonable to fix. The two remaining ones are:
- IsUnwindable: debug-only, not perf critical
- GetReturnAddressHijackInfo: it is hard to pass the resolved methodinfo through number of layers

**Review by filipnavara — APPROVED** [review]

**Comment by VSadov** [comment]
This is arm64-specific, right?    (just to confirm I read it correctly)

**Review by VSadov — APPROVED** [review]
LGTM Thanks!!

**Comment by jkotas** [comment]
> This is arm64-specific, right? (just to confirm I read it correctly)

Yes, this is Arm64 specific.

**Pull request merged**
