### PR TITLE
[mono] Fix InlineArray tests on android platforms

### LINKED ISSUE #90398: InlineArray[Valid]/[Invalid] Runtime tests are failing for Mono miniJIT and interpreter
### Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=369496

Affected pipelines:
- runtime-extra-platforms

Build error legs:
- `Mono android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open`

Failing:
- `android-x64 Release AllSubsets_Mono_RuntimeTests minijit`
- `android-x64 Release AllSubsets_Mono_RuntimeTests_Interp monointerpreter` 

```
[10:40:25] dbug: Executing command: '/datadisks/disk1/work/9B9908E4/p/microsoft.dotnet.xharness.cli/8.0.0-prerelease.23401.3/runtimes/any/native/adb/linux/adb -s emulator-5556 shell am instrument -e entrypoint:libname InlineArrayValid.dll -w net.dot.Loader_classloader/net.dot.MonoRunner'
        [10:40:29] info: Running instrumentation class net.dot.MonoRunner took 4.5776835 seconds
        [10:40:29] dbug: Exit code: 0
                         Std out:
                         INSTRUMENTATION_RESULT: return-code=101
                         INSTRUMENTATION_CODE: 101
                         
                         
                         
        [10:40:30] info: Instrumentation finished normally with exit code 101
        [10:40:33] dbug: Executing command: '/datadisks/disk1/work/9B9908E4/p/microsoft.dotnet.xharness.cli/8.0.0-prerelease.23401.3/runtimes/any/native/adb/linux/adb -s emulator-5556 logcat -d '
        [10:40:33] info: Wrote current ADB log to /datadisks/disk1/work/9B9908E4/w/AB97096C/uploads/Reports/Loader.classloader/InlineArray/InlineArrayValid/adb-logcat-net.dot.Loader_classloader-net.dot.MonoRunner.log
        [10:40:33] fail: Non-success instrumentation exit code: 101, expected: 100
        [10:40:33] dbug: Saving diagnostics data to '/datadisks/disk1/work/9B9908E4/w/AB97096C/e/diagnostics.json'
        XHarness exit code: 1 (TESTS_FAILED)
```

```
[10:39:01] dbug: Executing command: '/datadisks/disk1/work/9B9908E4/p/microsoft.dotnet.xharness.cli/8.0.0-prerelease.23401.3/runtimes/any/native/adb/linux/adb -s emulator-5556 shell am instrument -e entrypoint:libname InlineArrayInvalid.dll -w net.dot.Loader_classloader/net.dot.MonoRunner'
        [10:39:05] info: Running instrumentation class net.dot.MonoRunner took 3.6335327 seconds
        [10:39:05] dbug: Exit code: 0
                         Std out:
                         INSTRUMENTATION_RESULT: shortMsg=Process crashed.
                         INSTRUMENTATION_CODE: 0
                         
                         
                         
        [10:39:05] info: Short message:
                         Process crashed.
        [10:39:05] fail: No value for 'return-code' provided in instrumentation result. This may indicate a crashed test (see log)
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorPattern": "Loader\\/classloader\\/InlineArray\\/[\\w\\/.\\s]+\\[FAIL\\]",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=369496
**Error message validated:** `Loader\/classloader\/InlineArray\/[\w\/.\s]+\[FAIL\]`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/14/2023 10:41:08 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[374175](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374175)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374175&view=ms.vss-test-web.build-test-results-tab&runId=7953226&resultId=100197)|dotnet/runtime#90583|
|[373829](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373829)|dotnet/runtime|[Loader/classloader/regressions/GitHub_82187/GitHub_82187/GitHub_82187.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373829&view=ms.vss-test-web.build-test-results-tab&runId=7944462&resultId=100630)|dotnet/runtime#90412|
|[372849](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372849)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372849&view=ms.vss-test-web.build-test-results-tab&runId=7920304&resultId=100197)|dotnet/runtime#90519|
|[372550](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372550)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372550&view=ms.vss-test-web.build-test-results-tab&runId=7912882&resultId=100197)||
|[372445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372445)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372445&view=ms.vss-test-web.build-test-results-tab&runId=7908892&resultId=100197)|dotnet/runtime#90270|
|[372307](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372307)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372307&view=ms.vss-test-web.build-test-results-tab&runId=7904156&resultId=100197)||
|[372186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372186)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372186&view=ms.vss-test-web.build-test-results-tab&runId=7900188&resultId=100197)||
|[371961](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371961)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=371961&view=ms.vss-test-web.build-test-results-tab&runId=7893174&resultId=100197)|dotnet/runtime#90023|
|[369496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369496)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369496&view=ms.vss-test-web.build-test-results-tab&runId=7837476&resultId=100197)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|9|9|

### PR DESCRIPTION
**Pull request by kotlarmilos**
This PR renames the `InvalidCSharp` assembly to have unique name in the test app bundle. On android platforms, all assemblies are copied to the root directory, which may cause overriding assemblies with the same name.

Screenshot 2023-08-16 at 13 05 03

Here is a tracking issue to ensure that these cases remain valid in the future: https://github.com/dotnet/runtime/issues/90661

Fixes https://github.com/dotnet/runtime/issues/90398

### CODE REVIEW

**Comment by kotlarmilos** [comment]
@SamMonoRT Do we want to backport this to .NET8?

**Review by steveisok — APPROVED** [review]

**Review by lambdageek — APPROVED** [review]

**Review by fanyang-mono — APPROVED** [review]

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Pull request merged**
