### PR TITLE
Collect SPMI collections as part of Fuzzlyn pipeline

### PR DESCRIPTION
**Pull request by jakobbotsch**
This will include SPMI collections recorded over the reduction process in the zip artifact produced by the Fuzzlyn runs.

Corresponding Fuzzlyn change: https://github.com/jakobbotsch/Fuzzlyn/commit/3aecec6f2424634fa42a9ff4f92ea2eab411a897

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @BruceForstall 

Tried two Fuzzlyn runs but didn't manage to hit #96224 in any of them, so this is only locally tested. Hopefully Sunday's empowered Fuzzlyn run hits #96224 so I can see it work in full.

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
