### PR TITLE
Fix some NRT on StringCollection

### PR DESCRIPTION
**Pull request by lilinus**
`StringCollection` can contain `null` values. Fix annotations for `AddRange` and `CopyTo` to align with this.

### CODE REVIEW

**Review by eiriktsarpalis — APPROVED** [review]
Looks reasonable based on the other APIs present in the collection. @stephentoub any objections?

**Review by stephentoub — APPROVED** [review]
This is correct and we should take it. Just note that it could introduce more warnings into a consumer.

**Comment by eiriktsarpalis** [comment]
How so? It's only input parameters and none of the changed methods are virtual.

**Comment by stephentoub** [comment]
> How so? It's only input parameters and none of the changed methods are virtual.

I was thinking this would warn:
[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgYhgVwDaosVBTABNmTHAWACgABAJgEYyyrcBhMgbzNw93IGYvqA2LgBZcAQQAU5agAYA2gF1cEAE7KAlLgC8APlztOBgELiV6gNz6OlvoPIjjU6QH4FS1Rp17SBg6dnTFTVwUdAtSAF8gA=). But it doesn't I believe for the same reason there's no compiler error with:
Base[] base = new Derived[1];
base[0] = new OtherDerived();
even though it'll fail at run-time.

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
Thanks

**Pull request merged**
