### PR TITLE
[mono][interp] Fix leak during ssa transformation

### PR DESCRIPTION
**Pull request by BrzVlad**

### CODE REVIEW

**Comment by BrzVlad** [comment]
needs backport

**Comment by BrzVlad** [comment]
@pavelsavara On desktop interp, this reduces STJ tests memory usage by about 33%. I would imagine this will fix the OOM failures with wasm interp.

**Review by kg — APPROVED** [review]

**Comment by BrzVlad** [comment]
Got confused. Doesn't need backport.

**Pull request merged**
