### PR TITLE
CI: trigger library tests builds, when building runtime tests

### PR DESCRIPTION
**Pull request by radical**
.. as they depend on it.

This fixes mono runtime tests not getting triggered because library tests job didn't build.

### CODE REVIEW

**Review by fanyang-mono — APPROVED** [review]
It looks like that mono runtime test CI lanes are not triggered by runtime test only changes. Thanks for the fix!

**Comment by radical** [comment]
Removed the dummy change. And will merge on green.

**Comment by MichalStrehovsky** [comment]
This change doesn't look right.

Before this change a change to coreclr pipeline definition would trigger coreclr legs, change to mono pipeline trigger mono legs, etc.

After this change, changes to pipeline definitions don't trigger any legs.

#76560 (a coreclr pipeline definition change) is not triggering any legs.

Cc @dotnet/runtime-infrastructure

**Comment by radical** [comment]
> This change doesn't look right.
> 
> Before this change a change to coreclr pipeline definition would trigger coreclr legs, change to mono pipeline trigger mono legs, etc.
> 
> After this change, changes to pipeline definitions don't trigger any legs.
> 
> #76560 (a coreclr pipeline definition change) is not triggering any legs.
> 
> Cc @dotnet/runtime-infrastructure

From
```yml
    _always_exclude: [
        eng/pipelines/common/evaluate-default-paths.yml
        eng/pipelines/coreclr/*
        eng/pipelines/installer/*
        eng/pipelines/libraries/*
        eng/pipelines/mono/*
        eng/pipelines/runtime*
        src/workloads/*
    ]
```

.. I can remove:
```
        eng/pipelines/coreclr/*
        eng/pipelines/installer/*
        eng/pipelines/libraries/*
        eng/pipelines/mono/*
        eng/pipelines/runtime*
```

**Comment by radical** [comment]
@MichalStrehovsky I can push that to your PR, if the suggestion looks good.

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky I can push that to your PR, if the suggestion looks good.

It should ideally be a separate pull request. We had targeted exclusions before this change - your proposal is to get rid of all of them if I understand it correctly. The infra team might want the targeted exclusions back in the form they were before. I'm not a fan of repo-wide infra changes getting a ride on unrelated pull requests that people don't see.

**Pull request merged**
