### PR TITLE
Remove ldsfld quirk

### PR DESCRIPTION
**Pull request by MichalPetryka**
Alternative to spilling changes in #108579

### CODE REVIEW

**Comment by MichalPetryka** [comment]
Depends on #108955

**Review by EgorBo — APPROVED** [review]

**Comment by EgorBo** [comment]
I think it should be good to merge, we might even force IR validator to assert on mixes of GTF_IND_INVARIANT and GTF_GLOB_REF (since a lot of places assume GTF_GLOB_REF means possibly mutable data)

**Comment by MichalPetryka** [comment]
@MihuBot

**Comment by MichalPetryka** [comment]
@MihuBot -dependsOn 108838

**Pull request merged**
