### PR TITLE
Handle zero value modulus for OpenSSL 1.1 

### LINKED ISSUE #78293: RSA.VerifyData terminates with "Out of memory." on Linux when passing an all-zero modulus
### Description

If an all-zero modulus is passed to RSA.VerifyData on Linux, the program will unexpectedly terminate instead of throwing an exception.

### Reproduction Steps

```cs
using System.Security.Cryptography;

var param = new RSAParameters{Modulus = new byte[256], Exponent = new byte[3]};
using (var rsa = RSA.Create(param))
{
    rsa.VerifyData(new byte[512], new byte[256], HashAlgorithmName.SHA256, RSASignaturePadding.Pss);
}
```

### Expected behavior

`VerifyData` throws a `CryptographicException` like it does on Windows.

### Actual behavior

The program terminates with `Out of memory. Command terminated by signal 6`

### Regression?

Issue occurs on .NET 6 and 7. Unsure about earlier versions.

### Known Workarounds

_No response_

### Configuration

I've tested running .NET 6.0 and 7.0 on both x64 Ubuntu 22.04 and Debian 11.

### Other information

_No response_

### PR DESCRIPTION
**Pull request by vcsjones**
This reverts the [revert](https://github.com/dotnet/runtime/pull/78986). [Original PR](https://github.com/dotnet/runtime/pull/78339).

This PR introduces a check when importing an RSA public key that the modulus is not zero. For OpenSSL 1.1, the import succeeded and later fails at key usage time with a less-than-helpful error. This check brings consistency with other platforms, where a zero modulus fails at key import time.

@akoeplinger can you please point me to a pipeline run that reproduces the failure [you observed](https://github.com/dotnet/runtime/pull/78339#issuecomment-1331131790)?

Fixes https://github.com/dotnet/runtime/issues/78293

### CODE REVIEW

**Comment by akoeplinger** [comment]
> @akoeplinger can you please point me to a pipeline run that reproduces the failure [you observed](https://github.com/dotnet/runtime/pull/78339#issuecomment-1331131790)?

Sorry for the late reply, the coreclr change you made should've triggered the job due to the condition in https://github.com/dotnet/runtime/blob/2b1d11dd50429f54bc46f83b6c68d1d0b79e3d8d/eng/pipelines/runtime.yml#L75 but looks like it didn't? Can you try removing the condition there and see if that triggers it?

**Comment by akoeplinger** [comment]
The log says
```
-- Found OpenSSL: /crossrootfs/x86/usr/lib/i386-linux-gnu/libcrypto.so (found version "1.0.2g")  
```

and from what I can find the additional key was introduced in 1.0.2k so that at least explains why we're not finding it. I think we get the old package somehow for the cross root.

**Comment by akoeplinger** [comment]
I think I figured it out: in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/a5a8882abc169ebbd30e01ee58c1fbd578affa80/src/ubuntu/18.04/cross/x86-linux/hooks/pre-build#LL5C3-L5C3 we're passing `linux` to the script which builds the rootfs, but we should be passing `bionic` (all other architectures do this).

This means that the [build-rootfs.sh](https://github.com/dotnet/arcade/blob/main/eng/common/cross/build-rootfs.sh) script defaults to Ubuntu 16.04 `xenial`, which indeed only got 1.0.2g as the last openssl:

```
openssl (1.0.2g-1ubuntu4.19) [security]
```

I'll send a PR to fix the Docker container. This shouldn't have any impact on the actual product since we don't officially support Linux x86: https://github.com/dotnet/runtime/issues/7335

**Comment by akoeplinger** [comment]
Btw. do we need to do something about the mismatching value that @bartonjs noticed in https://github.com/dotnet/runtime/pull/78339#issuecomment-1331251495 ?

**Comment by vcsjones** [comment]
@akoeplinger for what it's worth, I need to fix my PR to work against 1.0.2g (and prior) since 1.0.2 is still supported. I apparently looked at the latest 1.0.2 and not 1.0.2a.

**Comment by akoeplinger** [comment]
I pushed a change to use the staging Docker image tag which includes my change just to verify the issue is fixed, please feel free to revert it when you push your other changes.

**Comment by vcsjones** [comment]
@bartonjs okay. I settled on `EVP_R_DECODE_ERROR` since that one is close (enough IMO) for this particular corner case. It is present and has a value of 114 across all versions of OpenSSL.

**Review by bartonjs — APPROVED** [review]

**Comment by mmitche** [comment]
@vcsjones This change appears to have broken non-portable source-build:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=104986&view=logs&j=98fdc254-13b3-5066-1dc8-532bea57cf83&t=c190c1e6-3d1f-5d73-3da0-0491dc0df66b

/cc @MichaelSimons

**Comment by vcsjones** [comment]
@mmitche @MichaelSimons I have a draft change that I believe will fix this, just working on validating it locally first. Apologies for the trouble.

**Pull request merged**
