### PR TITLE
JIT: refactor CSE heuristics

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Split the heuristics into a common base class and (currently) two derived classes, one for normal CSEs and another for random CSEs.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Was expecting no diffs, but have few, let me dig in.

**Comment by AndyAyersMS** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=490913&view=ms.vss-build-web.run-extensions-tab) come from slight changes to how the CSE stress works
* previously it could only accept rejectable candidates, now it may reject acceptable candidates
* random heuristic no longer sorts CSEs, so candidate order has changed; the RNG is stateful, so we get different random values for each candidate
* we have a handful of coreclr tests that enable jit stress

I think the new behavior is preferable. Will run jitstress to see if it causes any issues.

**Comment by AndyAyersMS** [comment]
@jakobbotsch PTAL
cc @dotnet/jit-contrib 

Passed jit stress pre merge commit.

**Review by jakobbotsch — APPROVED** [review]
LGTM, didn't go into too much detail under the assumption that this is more or less mechanical...

**Pull request merged**
