### PR TITLE
Add callback-based Encode to AsnWriter

### LINKED ISSUE #75759: [API Proposal]: AsnWriter Encode with callback
### Background and motivation

`AsnWriter` has `Encode` in two forms: writing to a `Span<byte>` and allocate-and-return `byte[]`.

There are several uses of `AsnWriter` where we write something to ASN.1 and then do something with it, like sign it or hash it. The allocating return well, allocates. The span-writing forces developers to come up with an intermediate, either on the stack, a pool rental, etc. Both require the contents to be copied.

However, `AsnWriter` already has the data available internally. I propose we make this available with a callback to `Encode`.

### API Proposal

```csharp
namespace System.Formats.Asn1;

public partial class AsnWriter {
#if NET9_0_OR_GREATER
        public TReturn Encode<TReturn>(Func<ReadOnlySpan<byte>, TReturn> encodeCallback);
        public TReturn Encode<TState, TReturn>(TState state, Func<TState, ReadOnlySpan<byte>, TReturn> encodeCallback)  where TState : allows ref struct;
#endif
}
```

The proposal allows passing in a state and a return. The state and return can be used to feed in state and allow the callback to remain static and not capture anything.

An overload without `state` exists so that passing in something is not required if it is not needed.

Since System.Formats.Asn1 is supported down level, these APIs will only exist for .NET9+ since ref structs as type arguments is not permitted until then.

### API Usage

Consider this snippet in the runtime today:

https://github.com/dotnet/runtime/blob/b1f5e97a75c958d6fd81b15bb22f98b182b2069f/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X500DistinguishedNameBuilder.cs#L355-L359

This would become:

```csharp
return _writer.Encode(static (ReadOnlySpan<byte> encoded) => {
    return new X500DistinguishedName(encoded);
});
```

The same pattern is used for decoding DSA keys for macOS and Android:

https://github.com/dotnet/runtime/blob/b1f5e97a75c958d6fd81b15bb22f98b182b2069f/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/X509Certificates/X509Pal.macOS.cs#L95

Encrypting CMS in PKCS:

https://github.com/dotnet/runtime/blob/b1f5e97a75c958d6fd81b15bb22f98b182b2069f/src/libraries/System.Security.Cryptography.Pkcs/src/Internal/Cryptography/Pal/AnyOS/ManagedPal.Encrypt.cs#L144-L146

Encoding a CMS:

https://github.com/dotnet/runtime/blob/b1f5e97a75c958d6fd81b15bb22f98b182b2069f/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignedCms.cs#L136

Hashing signed attributes:

https://github.com/dotnet/runtime/blob/b1f5e97a75c958d6fd81b15bb22f98b182b2069f/src/libraries/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs#L646

Etc.

### Alternative Designs

_No response_

### Risks

_No response_

### PR DESCRIPTION
**Pull request by vcsjones**
This adds a new callback-based mechanism for `AsnWriter`, and uses it where appropriate through the rest of the libraries.

Closes #75759

### CODE REVIEW

**Review by bartonjs — APPROVED** [review]

**Comment by vcsjones** [comment]
@bartonjs thought: someone could write, reset, clear, etc. the AsnWriter in its own `Encode` callback either by capturing it or passing itself as TState. Do we want to block that?

Basically, change our encode impl to

```csharp
try
{
    _encoding = true;
    ReadOnlySpan<byte> encoded = EncodeAsSpan();
    return encodeCallback(encoded);
}
finally
{
    _encoding = false;
}
```

And check that flag is false in all writing functions.

Is that useful or am I over thinking it?

**Comment by bartonjs** [comment]
Any time that we're willing to release the data from Encode, it's already at a place it will never change (except Reset()).  Any other calls would just be appending new data beyond where the span is pointing, so it wouldn't have any major surprises.

```C#
writer.Reset();
writer.WriteNull();
writer.Encode((writer, span) => writer.WriteEncodedValue(span));
writer.Encode();// now returns [ 0x05, 0x00, 0x05, 0x00 ]
```

I can't come up with a case where it would result in overwriting existing data.  The biggest surprise I can come up with is if the callback does PushSequence/SetOf/OctetString, since it would move the object from "encodable" to "not encodable".

If you want to block it, that's fine, but instead of reading `_encoding` in every Write function you could probably chokepoint it in EnsureWriteCapacity, since every write function calls that first.

**Comment by vcsjones** [comment]
> it's already at a place it will never change

If the write causes the buffer to resize, the span will be pointing at the old buffer, which has been zeroed.

https://github.com/dotnet/runtime/blob/4e8892ea65fe85593b1853907d965fb49d324ce9/src/libraries/System.Formats.Asn1/src/System/Formats/Asn1/AsnWriter.cs#L288-L291

**Comment by bartonjs** [comment]
Ah, so in that case

```C#
writer.Encode(
    (writer, span) =>
    {
        writer.WriteNull();
        writer.WriteEncodedObject(span);
    });
```

would work 99% of the time, but would try writing all zeros (which should fail unless it happens to be `00 00`) if the WriteNull forced a resize.

Okay, yeah, may as well block it.

**Review by bartonjs — APPROVED** [review]

**Pull request merged**
