### PR TITLE
[System.IO.Compression] ZipHelper.DosTimeToDateTime handle empty LastModified fields in zip archive entry header without internal exception

### PR DESCRIPTION
**Pull request by mklts**
We are parsing 10+ big zip files async on app launch. Majority of zip files are created in the MacOS. This zip files have 0 in the LastModified entry header field. 

Imagine we are parsing 2k entries and DateTime validation launching 2k exceptions internally. If we are disabling Just My Code it hangs the debugger for a minute on launch. Maybe it also affects release build performance also, IDK.

Exception source is this method `System.DateTime.DateToTicks`:
```C#
// Returns the tick count corresponding to the given year, month, and day.
// Will check the if the parameters are valid.
[MethodImpl(MethodImplOptions.AggressiveInlining)]
private static long DateToTicks(int year, int month, int day)
{
    if (year < 1 || year > 9999 || month < 1 || month > 12 || day < 1)
    {
        ThrowHelper.ThrowArgumentOutOfRange_BadYearMonthDay();
    }

    int[] days = IsLeapYear(year) ? s_daysToMonth366 : s_daysToMonth365;
    if (day > days[month] - days[month - 1])
    {
        ThrowHelper.ThrowArgumentOutOfRange_BadYearMonthDay();
    }

    int y = year - 1;
    int n = y * 365 + y / 4 - y / 100 + y / 400 + days[month - 1] + day - 1;
    return n * TicksPerDay;
}
```

This fix handles empty LastModified field without exception.

### CODE REVIEW

**Comment by danmosemsft** [comment]
Thank you for the PR. It would be interesting to know whether our tests exercise this path somehow.

**Review by carlossanlop — COMMENTED** [review]
Thank you for finding the issue and providing a code fix, @Mikolaytis.

For reference:

- Here's the method mentioned in the description: 
 [src/libraries/System.Private.CoreLib/src/System/DateTime.cs#L622-L641](https://github.com/dotnet/runtime/blob/1bfe73041f5389552d1c549be9b992a61f1d7f5f/src/libraries/System.Private.CoreLib/src/System/DateTime.cs#L622-L641)

- The `DosTimeToDateTime` method definition: [src/libraries/System.IO.Compression/src/System/IO/Compression/ZipHelper.cs#L56](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipHelper.cs#L56)

- The only place where that method is called:
[src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs#L59](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs#L59)

@Mikolaytis, can you please add unit tests to verify this change?

Your test requires a zip file with the `LastModified` field set to zero, and the unit test should check that no exception is thrown when the internal `ZipArchiveEntry` constructor is called (the one that calls `DosTimeToDateTime`.

If you can find a way to create a zip file in memory, without having to add a new test asset file, that would be perfect, but I think it might be difficult, because I found that the only public API that lets you modify the value of the private `_lastModified` field is the [LastWriteTime](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs#L224-L235), which will throw if you pass `0`.

If you have to add a file asset, it needs to be added in the `dotnet/runtime-assets` repo (separate PR, naturally), in one of these folders: https://github.com/dotnet/runtime-assets/tree/master/src/System.IO.Compression.TestData/ZipTestData

To consume the file, you can call [one of these methods](https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/Common/tests/System/IO/Compression/ZipTestHelper.cs#L14-L19) in your test code.

Let me know if you have any questions, I'll be happy to help.

cc @ericstj

**Comment by Mikolaytis** [comment]
Hi, @carlossanlop. Thanks for a feedback! I'll try to make this unit test on a weekend. It's a nice challenge to make it asset-free. The only thing I cannot understand - is how to check from unit test of method `DosTimeToDateTime` if exception was thrown and handled by this method internally(without modification of a method)? Can you provide an example of this kind of unit test, or any article with info how to do this. Is it even possible? 

The single solution I can imagine is to not use a `s_invalidDateIndicator`, but create a new `s_emptyDateIndicator` and check in unit test a return value to be an empty indicator.

**Comment by danmosemsft** [comment]
@Mikolaytis we try to avoid using reflection in unit tests, and we don’tadd API purely for tests. So I think a test asset may be inevitable. You would temporarily modify your copy of this code locally to skip the date validation in order to create it

**Comment by ericstj** [comment]
I’ve also seen helpers that modify header info relative to file names. https://github.com/dotnet/runtime/blob/f2d51b5e15808d2c358a59f24af4fad4a9953656/src/libraries/System.IO.Compression/tests/ZipArchive/zip_InvalidParametersAndStrangeFiles.cs#L487

That might work here.

**Comment by danmosemsft** [comment]
@Mikolaytis do you need any other info? thanks for fixing.

**Comment by Mikolaytis** [comment]
Hi, I have a delay, because cannot build runtime on my PC. Getting a lot of various issues. In case you are interested:
1. sdk compatibility. `dotnet restore` somehow tries to use my net core 3.1 sdk, not 5.0 sdk - `C:\Users\brutal\source\repos\runtime\.dotnet\sdk\5.0.100-rc.1.20454.5\Current\SolutionFile\ImportAfter\Microsoft.NET.Sdk.Solution.targets(14,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Common.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.Common.targets" is correct, and that the file exists on disk.`
2. also visual studio 2019 preview cannot build a solution because has an issue of duplicate targets 'net6.0,net6.0,net6.0' previously it was triple net5.0
3. another strange issues...


Also I've tried to do everything on my mac, getting failed also :) So it will take some time for me to investigate and google this issues and get everything building+testing and then I will update my PR.

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43008) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43008) before we can accept your contribution.<br/><br/>:x: Mikolaytis [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43008)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=43008) it.</sub>

**Comment by Mikolaytis** [comment]
I've got the zip archive with empty lastModified field entry by modifying an output stream bits. I hope this solution do not violate any rule :) I think it's stable because zip headers format will not be modified in the future.

**Comment by danmosemsft** [comment]
@dotnet/runtime-infrastructure to see https://github.com/dotnet/runtime/pull/43008#issuecomment-710792332

**Review by danmoseley — APPROVED** [review]
Thanks. As a double check, did you verify that your test goes through the new fast-return? Or some other way confirm that it fixes the original problem.

**Comment by danmosemsft** [comment]
Put another way -- have you verified that the test fails without the product code change?

**Comment by Mikolaytis** [comment]
There is no option AFAIK to check "if exception was thrown internally", without code modification. 
I've tried some options with minor code modifications:
1) Modified the return value in 0 value case, for instance return `DateTime.MinValue` and checked for it. Before the commit I realized that this change is breaking, because this entry cannot be saved back to the zip file, because minimum zip date is around 1980...
2) Next I've tried to return just a little changed date, named it s_emptyDateIndicator.
```
private static readonly DateTime s_invalidDateIndicator = new DateTime(ValidZipDate_YearMin, 1, 1, 0, 0, 0);
private static readonly DateTime s_emptyDateIndicator = new DateTime(ValidZipDate_YearMin, 1, 1, 1, 1, 1);
``` 
This option I think is also a breaking change, because any old code, that is checking invalid date indicator will be affected by this.

So as far as I didn't find a non breaking change I leave this test in current state, without direct check. I'm open for any tips/examples that can help me in this situation.

**Comment by danmosemsft** [comment]
My bad. I should have asked: did you verify (eg in debugger) that the original bug is now fixed?

**Comment by Mikolaytis** [comment]
Yes, I did. Multiple times :)

**Comment by danmosemsft** [comment]
@akoeplinger some of the Mono iOS jobs failed thus:
```
[17:51:21] dbug: 17:51:21.6446110 Xamarin.Hosting: Installing /tmp/helix/working/C2830A5E/w/B1090986/e/System.Net.Mail.Functional.Tests.app with Bundle Identifier net.dot.System.Net.Mail.Functional.Tests on 'iOS 13.5 (17F61) - iPhone X'...
[18:21:05] dbug: 18:21:05.5497430 Killing process 63724 as it was cancelled
[18:21:05] dbug: 18:21:05.5550200 Process exited with 137
[18:21:05] dbug: 18:21:05.5556630 Test run failed
[18:21:05] dbug: 18:21:05.5633860 Could not find pid in mtouch output.
[18:21:05] dbug: 18:21:05.5681120 Test run started
[18:21:06] dbug: 18:21:06.5983450 Test run failed to launch
[18:21:06] dbug: 18:21:06.6595850 No crash reports, waiting a second to see if the crash report service just didn't complete in time (4)
[18:21:07] dbug: 18:21:07.7983340 No crash reports, waiting a second to see if the crash report service just didn't complete in time (3)
[18:21:08] dbug: 18:21:08.8888210 No crash reports, waiting a second to see if the crash report service just didn't complete in time (2)
[18:21:10] dbug: 18:21:10.0151800 No crash reports, waiting a second to see if the crash report service just didn't complete in time (1)
[18:21:11] dbug: 18:21:11.1458550 No crash reports, waiting a second to see if the crash report service just didn't complete in time (0)
[18:21:12] fail: Failed to launch the application:
                 Launch failure
                 
                 Check logs for more information.
XHarness exit code: 1107
```
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-43008-merge-0ac5a9b2ecbb499bbb/System.Net.Mail.Functional.Tests/console.a2ace115.log?sv=2019-07-07&se=2020-11-07T00%3A50%3A46Z&sr=c&sp=rl&sig=%2FeMz0oWEeBd2maU%2FE0QOld5v1%2B8vVOY3t4XnYScauCs%3D

**Comment by danmosemsft** [comment]
Merging as it's vanishingly unlikely that this would break System.Net.Mail tests (and a few others) on Mono iOS specifically.

Thanks for the change!

**Comment by premun** [comment]
@danmosemsft some of the MacOS machines were misbehaving and we have taken them out of the pool, did some investigations, rebooted them and put them back. The OS was acting really slow and we so far do not understand the underlying issue. Reboot seems to help so far but it is not ideal.

If you see similar issues in the future, don't hesitate to tag me please!

**Comment by premun** [comment]
@danmosemsft I have re-run the build and the iOS stage is green now:
https://dev.azure.com/dnceng/public/_build/results?buildId=857613&view=logs&j=ed35a636-dfd2-5b37-1677-c669f876ef31&t=e0c7008d-474a-5aca-5f6f-f4ddb2ab1465

**Comment by danmosemsft** [comment]
Thanks @premun!

**Comment by danmosemsft** [comment]
@Mikolaytis note that daily 6.0 builds out of http://github.com/dotnet/sdk do not yet properly include bits out of our 6.0 master here yet. That should be fixed in a week or two then you will have somehting you can consume. I expect we will start to ship 6.0 previews early next year.

**Review by ericstj — COMMENTED** [review]
LGTM, thanks for the fix!

**Pull request merged**
