### PR TITLE
[release/9.0-preview7] [browser] Extension agnostic lazy assembly loading

### PR DESCRIPTION
**Pull request by maraf**
Backport of https://github.com/dotnet/runtime/pull/104793

Depends on https://github.com/dotnet/runtime/pull/105294 (this PR is based on it)

### CODE REVIEW

**Review by pavelsavara — APPROVED** [review]

**Comment by carlossanlop** [comment]
There are several CI failures. Are any of them related? Let me know when it's ready to merge.

**Comment by maraf** [comment]
> @lewing There are many previously unknown CI failures. Are any of them related? Let me know when it's ready to merge.

It was caused by some merge damage. Now all the effected files matches content on main.

**Comment by lewing** [comment]
> > @lewing There are many previously unknown CI failures. Are any of them related? Let me know when it's ready to merge.
> 
> It was caused by some merge damage. Now all the effected files matches content on main.

Sorry about that

**Comment by lewing** [comment]
/ba-g analysis is only red because this is a release branch

**Comment by lewing** [comment]
@carlossanlop this is ready now if we still have time

**Pull request merged**
