### PR TITLE
Disable test with the correct path

### LINKED ISSUE #69678: Failures on Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open on rolling build of runtime-extra-platforms
### Description

runtime-extra-platform [build](https://runfo.azurewebsites.net/view/build/?number=1779269)  fails with 
Interop_PInvoke._Int128_Int128Test_Int128Test_._Int128_Int128Test_Int128Test_sh() and IT_opt._OSR_pinnedlocal_pinnedlocal_._OSR_pinnedlocal_pinnedlocal_sh(), return code is -1.

It started failing from  this build [1779269]( https://runfo.azurewebsites.net/view/build/?number=1779269) 
I can see that in that build was merged this commit https://github.com/dotnet/runtime/commit/04d5bbcbddb96dcb05d28a614df9caea93d5df9a 

### Reproduction Steps

Check last rolling build of runtime-extra-platforms https://runfo.azurewebsites.net/view/build/?number=1779269)

### Expected behavior

Tests should pass

### Actual behavior

Build  fails with 
Interop_PInvoke._Int128_Int128Test_Int128Test_._Int128_Int128Test_Int128Test_sh() and IT_opt._OSR_pinnedlocal_pinnedlocal_._OSR_pinnedlocal_pinnedlocal_sh(), return code is -1.

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by fanyang-mono**
Remove the extra folder

Fixes #69678

### CODE REVIEW

**Comment by SamMonoRT** [comment]
@fanyang-mono @mkhamoyan - do we know what changed the test path that it isn't excluded correctly in recent builds ?

**Comment by mkhamoyan** [comment]
It was added with this PR https://github.com/dotnet/runtime/pull/69204 . Failing Test was supposed to be skipped on Android (and Mono in general) until https://github.com/dotnet/runtime/issues/69531 could be resolved. Fan find out that there was a extra folder in the path

**Review by SamMonoRT — APPROVED** [review]

**Pull request merged**
