### PR TITLE
Enable global constant propagation for small types

### PR DESCRIPTION
**Pull request by SingleAccretion**
Just as the title says - remove the restriction that we do not propagate constants for small-typed trees. It is safe because VN [adds](https://github.com/dotnet/runtime/blob/b75e55beb1628df8f704a3014b9acd1b98d4f445/src/coreclr/jit/valuenum.cpp#L7719-L7731) the necessary truncating casts when evaluating the assignment.

Now, small-typed nodes themselves are a bit rare, but one scenario where they come up is in field-by-field copying and initialization of promoted structs, which is where practically all the diffs for this change come from.

The substantial code here is only in the third commit, the rest is miscellaneous cleanup.

Some nice diffs for this change: [`win-x64`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-57726/win-x64.md), [`win-arm64`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-57726/win-arm64.md), [`win-x86`](https://github.com/SingleAccretion/diffs-repository/blob/main/runtime-57726/win-x86.md)

Small regressions here and there are due to slightly different register allocation and the fact that sometimes containing a constant is not profitable size-wise.

Because this is an impactful change, I think stress testing is warranted for this PR. SPMI replay already revealed one bug (#57450), there may be more.

### CODE REVIEW

**Comment by JulieLeeMSFT** [comment]
CC @dotnet/jit-contrib please review the community PR.

**Review by jakobbotsch — APPROVED** [review]
This looks good to me, thanks!

> Because this is an impactful change, I think stress testing is warranted for this PR. SPMI replay already revealed one bug (#57450), there may be more.

I'll try running Fuzzlyn with this for a while before we merge it, and let me kick off some more CI legs.

**Comment by jakobbotsch** [comment]
I ran Fuzzlyn for a while and didn't find anything that looked specific to this PR. The failures look like #58481.

**Comment by jakobbotsch** [comment]
Thanks!

**Pull request merged**
