### PR TITLE
Enable automated SPMI collection for outerloop tests

### PR DESCRIPTION
**Pull request by kunalspathak**
- Enable automated SPMI collection for outerloop tests.
- Split the libraries and tests job so the failure of one won't affect uploading the collection result of other.
- If one of the partition of collection job fails on helix machine (might happen for tests), still merge whatever collections we got for other partitions and upload them to azure.

### CODE REVIEW

**Comment by kunalspathak** [comment]
I triggered a pipeline https://dev.azure.com/dnceng/internal/_build/results?buildId=865562&view=results yesterday and we were able to get SPMI collection for test. Windows x86/x64 fails with timeout because they ran more than 5 hours. In future, I will see if we can split the test workload in smaller chunks, but for now, this PR should get us SPMI collection for tests.

@dotnet/jit-contrib , @BruceForstall

**Comment by kunalspathak** [comment]
@BruceForstall  - There are some (varying) failures on Linux x64/Windows arm64 . You can check the logs at https://dev.azure.com/dnceng/internal/_build/results?buildId=865562&view=artifacts&type=publishedArtifacts. We can talk offline about them.

**Comment by BruceForstall** [comment]
I see several kinds of failures:
- Windows x86/x64 has no console log in the UI for the "Send to Helix" job? That's odd.
- Several jobs fail because they can't find some test artifacts. Did the test artifacts not get built? Or is the job trying to download them not referring to the correct download artifact location?

**Review by BruceForstall — APPROVED** [review]
Generally looks good, although it looks like there are still some failures to investigate.

**Comment by kunalspathak** [comment]
> I see several kinds of failures:
> 
> * Windows x86/x64 has no console log in the UI for the "Send to Helix" job? That's odd.

They just timed out, so I guess we didn't hear from helix for more than 5 hours and in that case, I am assuming that we can't see those logs. I have seen this kind of behavior in the past.

> * Several jobs fail because they can't find some test artifacts. Did the test artifacts not get built? Or is the job trying to download them not referring to the correct download artifact location?

All the others failed when they were trying to download the SPMI collection of respective partition. But since some of the partitions failed during the SPMI collection, we were not able to download those artifacts and that's the errors we see in the log. Not to see the actual SPMI collection failure for the the respective partition, you need to go to [published artifacts](https://dev.azure.com/dnceng/internal/_build/results?buildId=865562&view=artifacts&type=publishedArtifacts), search for `SuperPMI_Result_tests` and then expand those folder / subfolder. 

image

E.g. In the above screenshot, if I download the log file I see below error at the bottom of that file, but there were other errors like replay failed in other partitions.

```
[Errno 28] No space left on device: '/home/helixbot/work/AA2A093E/t/tmpt9n42bpn/pmi__home_helixbot_work_AA2A093E_w_AAC8092D_u_binaries_JIT_jit64_hfa_main_testE_hfa_nf2E_r_hfa_nf2E_r_dll_txx9pjqw.stderr'
```

**Comment by kunalspathak** [comment]
@safern - any thing that can be done for the disk space errors?

**Comment by BruceForstall** [comment]
@kunalspathak Perhaps you could add logging of some kind to show how much disk space is in the various locations we use during collection? And perhaps we can force the temp directories used by collection to be in "bigger" places? 

E.g., I see in one yml:
```
  - ${{ if ne(parameters.osGroup, 'Windows_NT') }}:
    - script: set -x && df -h
      displayName: Check remaining storage space
      condition: always()
      continueOnError: true
```

but maybe superpmi.py could tell you as well.

I've tried to optimize superpmi.py to use as little space as possible, so I'm not sure how much more can be done there to reduce space usage, except to split collection across more machines. Possibly we could merge/dedup incrementally, and not just at the end. But eventually, the "merge" machine will need to have a fair amount of space.

**Comment by kunalspathak** [comment]
Windows x64/x86 still fails because few partitions do not complete while others complete. I am merging it because it is separate investigation to see why that is happening.

**Pull request merged**
