### PR TITLE
[LoongArch64] Synchronize with PR#102469.

### PR DESCRIPTION
**Pull request by LuckyXu-HF**
[LoongArch64] Synchronize with PR#102469.
* And fix the build error for LoongArch64.

### CODE REVIEW

**Comment by LuckyXu-HF** [comment]
Besides，the following build error under debug mode on LA64 after https://github.com/dotnet/runtime/pull/102297 is fixed by https://github.com/dotnet/runtime/pull/102631 .
```shell
...
[ 97%] Built target clrjit_static
Consolidate compiler generated dependencies of target coreclr_static
[ 97%] Linking CXX static library libcoreclr_static.a
[ 97%] Built target coreclr_static
Consolidate compiler generated dependencies of target singlefilehost
[ 97%] Linking CXX executable singlefilehost
ld.lld: error: undefined symbol: RegSet::rsAllCalleeSavedMask
>>> referenced by regset.h:95 (/data_loongson/xuliangyu/dotnet-runtime-loongarch/src/coreclr/jit/regset.h:95)
>>>               codegencommon.cpp.o:(RegSet::rsGetModifiedCalleeSavedRegsMask() const) in archive ../dlls/mscoree/coreclr/libcoreclr_static.a
>>> referenced by regset.h:95 (/data_loongson/xuliangyu/dotnet-runtime-loongarch/src/coreclr/jit/regset.h:95)
>>>               codegencommon.cpp.o:(RegSet::rsGetModifiedCalleeSavedRegsMask() const) in archive ../dlls/mscoree/coreclr/libcoreclr_static.a
>>> referenced by regset.h:95 (/data_loongson/xuliangyu/dotnet-runtime-loongarch/src/coreclr/jit/regset.h:95)
>>>               codegencommon.cpp.o:(RegSet::rsGetModifiedCalleeSavedRegsMask() const) in archive ../dlls/mscoree/coreclr/libcoreclr_static.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Corehost.Static/CMakeFiles/singlefilehost.dir/build.make:1384：Corehost.Static/singlefilehost] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1917：Corehost.Static/CMakeFiles/singlefilehost.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2
/data_loongson/xuliangyu/dotnet-runtime-loongarch
Failed to build "CoreCLR component".
```

**Review by shushanhf — APPROVED** [review]
LGTM
Thanks

**Comment by LuckyXu-HF** [comment]
Hi @kunalspathak @jakobbotsch , could you please review this PR? Thanks.

**Review by kunalspathak — APPROVED** [review]
LGTM

**Pull request merged**
