### PR TITLE
Update overlapped field test to conflict on 32-bit arches

### LINKED ISSUE #62303: [wasm] `Loader/classloader/explicitlayout/NestedStructs/case04/case04.sh` failing with `FAIL: object and non-object field overlap was not detected`
[Rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1494433&view=logs&j=2296eecc-f5ab-523f-c15d-f45eef1bfdea&t=d328b091-66a6-5d96-5a21-3cf77f57f009), and [Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-8237b72af558483d89/Loader.classloader/1/console.0530c892.log?sv=2019-07-07&se=2021-12-22T20%3A57%3A59Z&sr=c&sp=rl&sig=hts3uBp51%2BiLsDcBSQOos2Sp4n4RKdFmycAMSJG1TVQ%3D)

```
    Loader/classloader/explicitlayout/NestedStructs/case04/case04.sh [FAIL]
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/A3F40905/w/ABAB093F/uploads/Reports/Loader.classloader/explicitlayout/NestedStructs/case04/case04.output.txt
      Raw output:
      BEGIN EXECUTION
      Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
      Copyright (C) Microsoft Corporation. All rights reserved.
      
        AppDir: /datadisks/disk1/work/A3F40905/w/ABAB093F/e/Loader/classloader/explicitlayout/NestedStructs/case04/WasmApp/
        TestBinDir: /datadisks/disk1/work/A3F40905/w/ABAB093F/e/Loader/classloader/explicitlayout/NestedStructs/case04
        ArtifactsBinDir: 
      /datadisks/disk1/work/A3F40905/p/build/WasmApp.targets(210,5): warning : Could not find $(AssemblyName)=WasmTestRunner.dll in the assemblies to be bundled. [/datadisks/disk1/work/A3F40905/p/wasm-test-runner/WasmTestRunner.proj]
      Incoming arguments: --run case04.dll
      Application arguments: --run case04.dll
      console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
      console.info: Initializing.....
      FAIL: object and non-object field overlap was not detected
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
```

IIUC, this is a new test that was added in https://github.com/dotnet/runtime/pull/61467 . cc @simonrozsival

FYI, the diff from the previous passing rolling build - https://github.com/dotnet/runtime/compare/a61c1a3c..ad9979381706d1976e4d26e13cb88d6147264968

And it slipped through because we are not running the wasm/RuntimeTests on PRs. @lewing @steveisok Should we enable them for wasm on PRs? Or maybe based on some path changes?

### PR DESCRIPTION
**Pull request by lambdageek**
Fixes https://github.com/dotnet/runtime/issues/62303

And related to #62311

### CODE REVIEW

**Comment by lambdageek** [comment]
@simonrozsival I changed from asserting, to just initializing the fields of the embedded struct, after all, since it looks like on AOT we use the cached size info and don't necessarily have the type initialized properly yet.

**Review by simonrozsival — APPROVED** [review]
LGTM

**Comment by lambdageek** [comment]
Waiting for more extensive validation here https://dev.azure.com/dnceng/public/_build/results?buildId=1495727&view=results

**Comment by lambdageek** [comment]
Ok, the only failure on `Mono llvmaot Pri0 Runtime Tests Run Linux x64 release` is
```
Loader/classloader/DefaultInterfaceMethods/regressions/github60486/github60486.sh [FAIL]
```

Which is being disabled in #62335

**Pull request merged**
