### PR TITLE
Adjust Test Watcher Timeout for Test Collections

### PR DESCRIPTION
**Pull request by ivdiazsa**
Addresses issue #83654. This PR introduces a new environment variable, `__TestCollectionTimeoutMins`, which is used by the watcher in favor of `__TestTimeout`. This is to have it be able to measure running time more appropriately in test collections work items.

### CODE REVIEW

**Comment by ivdiazsa** [comment]
cc @jakobbotsch

**Review by jakobbotsch — APPROVED** [review]
LGTM, thank you! I will also kick off jit-cfg.

**Review by jkoritzinsky — APPROVED** [review]

**Review by trylek — APPROVED** [review]
LGTM, thanks Ivan!

**Review by jkoritzinsky — APPROVED** [review]

**Pull request merged**
