### PR TITLE
Add linux mariner to rolling builds for libraries tests

### LINKED ISSUE #54478: Add Mariner Linux distro to CI validation
Leadership asked us to validate against Mariner in our CI matrix. There are containers available that could be used and afaik @MattGal already ran our test suite on it and found just one single failing test.

`mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-1.0-helix-20210528192219-92bf620)`

@danmoseley do we want to run this for every PR or just for every rolling build on main?

@safern or @hoyosjs could you please help with adding the distro to our CI matrix?

### PR DESCRIPTION
**Pull request by safern**
Fixes: https://github.com/dotnet/runtime/issues/54478

### CODE REVIEW

**Comment by safern** [comment]
Sample build including this queue here: https://dev.azure.com/dnceng/public/_build/results?buildId=1291084&view=results

**Comment by safern** [comment]
@bartonjs it seems like this crypto test is failing on Linux Mariner: https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Security.Cryptography.Algorithms/tests/ChaCha20Poly1305Tests.cs#L441

I guess OpenSsl is present but for some reason the runtime property is returning false, what is your advise? Just disable it for this distro?

**Review by danmoseley — APPROVED** [review]
Thanks

**Review by ViktorHofer — APPROVED** [review]

**Comment by bartonjs** [comment]
> what is your advise? Just disable it for this distro?

Seems like a reasonable starting place.  OpenSSL on Mariner must be built with one or both of nopoly1305 or nochacha.  When things get more complicated we'll need to figure out how to better determine that in the tests (hopefully via a route other than just duplicating the product logic).

```diff
            else if (PlatformDetection.IsAndroid)
            {
                // Android with API Level 28 is the minimum API Level support for ChaChaPoly1305.
                expectedIsSupported = OperatingSystem.IsAndroidVersionAtLeast(28);
            }
+           else if (PlatformDetection.IsMariner)
+           {
+               // OpenSSL is present, and a high enough version,
+               // but the distro build options turned off ChaCha/Poly.
+           }
            else if (PlatformDetection.OpenSslPresentOnSystem &&
                (PlatformDetection.IsOSX || PlatformDetection.IsOpenSslSupported))
            {
```

Or something like that.

**Comment by danmoseley** [comment]
```diff
            else if (PlatformDetection.IsAndroid)
            {
                // Android with API Level 28 is the minimum API Level support for ChaChaPoly1305.
                expectedIsSupported = OperatingSystem.IsAndroidVersionAtLeast(28);
            }
+           else if (PlatformDetection.IsMariner)
+           {
+               // OpenSSL is present, and a high enough version,
+               // but the distro build options turned off ChaCha/Poly.
+              Assert.True(false, "Mariner changed its build configuration. We need to begin testing it here.");
+           }
            else if (PlatformDetection.OpenSslPresentOnSystem &&
                (PlatformDetection.IsOSX || PlatformDetection.IsOpenSslSupported))
            {
```
?

**Comment by bartonjs** [comment]
> I wonder whether there's some assert we can add in the tests so that if Mariner changes its configuration, we can enable the tests again.

Well, the diff I proposed would leave Mariner running the test, but in the "expect: false" case, then the test would fail with "actual: true" and we'd be in what I called "when things get more complicated".  So we already have that assert/action-signal :smile:.

For this feature, the mainline tests only run when the platform says it's supported, this particular test just checks that the platform says things are (or aren't) supported as we expect them to be.

**Comment by safern** [comment]
Sounds good, I'll adjust accordingly.

**Comment by safern** [comment]
Done. New build with the changes: https://dev.azure.com/dnceng/public/_build/results?buildId=1292670&view=results

**Review by bartonjs — APPROVED** [review]

**Comment by safern** [comment]
Looks like some tests are failing on Mono. I will open issues and disable them.

cc: @steveisok @akoeplinger

**Review by akoeplinger — APPROVED** [review]

**Comment by safern** [comment]
New rolling build: https://dev.azure.com/dnceng/public/_build/results?buildId=1296468&view=results

**Comment by safern** [comment]
The linux mariner build is now green. Merging as failures are unrelated.

**Pull request merged**
