### PR TITLE
Add back optimization of Encode using arm64 load/store/vectortablelookup

### PR DESCRIPTION
**Pull request by kunalspathak**
Depends on https://github.com/dotnet/runtime/pull/98710

Reverts portion of https://github.com/dotnet/runtime/pull/96944 and adds back the optimization that was done for `Encode` in https://github.com/dotnet/runtime/pull/95513

### CODE REVIEW

**Comment by kunalspathak** [comment]
cc: @a74nh @SwapnilGaikwad @fanyang-mono

**Comment by kunalspathak** [comment]
@tannergooding

**Review by a74nh — APPROVED** [review]
This looks identical to https://github.com/dotnet/runtime/commit/fdb03ca8776, so LTGM.

**Comment by kunalspathak** [comment]
"Extra platform" failures are known or unrelated to this change.

**Review by tannergooding — APPROVED** [review]

**Comment by EgorBo** [comment]
Improvements on arm64:

- https://github.com/dotnet/perf-autofiling-issues/issues/30169

**Pull request merged**
