### PR TITLE
Update to use the cbl-mariner webassembly images.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
This is one of the last official build targets that we weren't already using CBL-Mariner to build with.

### CODE REVIEW

**Review by sbomer — APPROVED** [review]

**Comment by directhex** [comment]
These images are 100% borked right now, yes? I just tried to use them for ICU, and am getting Docker errors

**Comment by jkoritzinsky** [comment]
Guess I missed some of the AzDO requirements for the containers...

**Comment by jkoritzinsky** [comment]
The WASM legs build the apps on the build system, so the `mono-aot-cross` executable needs to be able to run on the Helix machines. Need to figure out the best way to handle this.

**Comment by radical** [comment]
```
mono-aot-cross: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.AOT.linux-x64.Cross.browser-wasm/8.0.0-ci/Sdk/../tools/mono-aot-cross)
mono-aot-cross: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.AOT.linux-x64.Cross.browser-wasm/8.0.0-ci/Sdk/../tools/mono-aot-cross)
mono-aot-cross: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.AOT.linux-x64.Cross.browser-wasm/8.0.0-ci/Sdk/../tools/mono-aot-cross)
mono-aot-cross: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.AOT.linux-x64.Cross.browser-wasm/8.0.0-ci/Sdk/../tools/mono-aot-cross)
```

`mono-aot-cross` is being built on the build machines with mariner, but then used on helix which is still running ubuntu 18.04 .

**Comment by directhex** [comment]
Those numbers don't line up, glibc 2.34 is not what Mariner-built stuff should be offering. Our Mariner build images have the Mariner base OS, and are SUPPOSED TO cross-compile against a target OS (Ubuntu 16.04 in most cases) in `/crossrootfs`. 2.34 is WAY newer than that, it's like Ubuntu 21.10 or something (or maybe even the Mariner base itself? As opposed to the crossroot?)

**Comment by jkoritzinsky** [comment]
It's the Mariner base image itself. The WASM build legs build the "cross" tools on the base image. We don't ship those components; we build them again in another leg to produce the "cross" tools built against the correct target rootfs. We only hit this problem because WASM uses mono-aot-cross to build tests on Helix machines. This was working beforehand because the image where we built wasm was the same or older base image as the image we run wasm tests on.

The solution (which I need to look into) is to build the cross tools like mono-aot-cross against the correct rootfs.

**Comment by carlossanlop** [comment]
Does this change need to be backported?

**Comment by jkoritzinsky** [comment]
We're still determining the plans for these infra changes for existing release branches.

**Comment by jkoritzinsky** [comment]
Failures are either known or https://github.com/dotnet/runtime/issues/86533

**Comment by lewing** [comment]
The official build started failing after this

**Comment by jkoritzinsky** [comment]
I'm testing out a possible fix. Should have something by EOD today hopefully.

**Pull request merged**
