### PR TITLE
[mono][aot] Add support for deferred failures during AOT compilation

### LINKED ISSUE #86327: [mono][aot] Loader tests failing on CI with Mono LLVM FullAOT
Seen when running `runtime-extra-platforms` on `linux-x64 Release AllSubsets_Mono_LLVMFullAot_RuntimeTests llvmfullaot`.
Loader tests failures detected on: 
- Work item Loader.classloader fails with:
    ```
    Loader/classloader/InlineArray/InlineArrayInvalid/InlineArrayInvalid.sh [FAIL]
          
          Return code:      1
          Raw output file:      /datadisks/disk1/work/A06E08C1/w/AE0D0957/uploads/Reports/Loader.classloader/InlineArray/InlineArrayInvalid/InlineArrayInvalid.output.txt
          Raw output:
          BEGIN EXECUTION
          /datadisks/disk1/work/A06E08C1/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true InlineArrayInvalid.dll ''
          Explicit_Fails...
          Xunit.Sdk.ThrowsException: Assert.Throws() Failure
          Expected: typeof(System.TypeLoadException)
          Actual:   typeof(System.ExecutionEngineException): Attempting to JIT compile method 'void Validate/<>c:<Explicit_Fails>b__1_0 ()' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
                    
             at Xunit.Assert.RecordException(Action testCode)
          Expected: 100
          Actual: 101
          END EXECUTION - FAILED
    ```
- Work item PayloadGroup0 fails with:
    ```
      Loader/StartupHooks/StartupHookTests/StartupHookTests.sh [FAIL]
          ...
          BEGIN EXECUTION
           /datadisks/disk1/work/A06E08C1/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true StartupHookTests.dll ''
           Running ValidHookName...
           -- Hello from startup hook with overload! Call count: 1
           Running ValidHookPath...
           Failed to load AOT module '/datadisks/disk1/work/A06E08C1/w/A66308F3/e/Loader/StartupHooks/StartupHookTests/private/PrivateInitialize.dll.so' ('/datadisks/disk1/work/A06E08C1/w/A66308F3/e/Loader/StartupHooks/StartupHookTests/private/PrivateInitialize.dll') in aot-only mode.
    ```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=274202
Build error leg or test failing: Loader.classloader.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/86266

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorPattern": "(Loader).+(InlineArrayInvalid|StartupHookTests)(.sh\\s\\[FAIL\\])",
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[290619](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290619)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290619&view=ms.vss-test-web.build-test-results-tab&runId=5819246&resultId=112392)|dotnet/runtime#86883|
|[290636](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290636)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290636&view=ms.vss-test-web.build-test-results-tab&runId=5819534&resultId=112392)|dotnet/runtime#86690|
|[290501](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290501)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290501&view=ms.vss-test-web.build-test-results-tab&runId=5816668&resultId=112389)||
|[290401](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290401)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290401&view=ms.vss-test-web.build-test-results-tab&runId=5815070&resultId=112392)|dotnet/runtime#85558|
|[290218](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290218)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290218&view=ms.vss-test-web.build-test-results-tab&runId=5812232&resultId=112392)||
|[290207](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290207)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290207&view=ms.vss-test-web.build-test-results-tab&runId=5812084&resultId=112389)||
|[289544](https://dev.azure.com/dnceng-public/public/_build/results?buildId=289544)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=289544&view=ms.vss-test-web.build-test-results-tab&runId=5791792&resultId=112392)||
|[289319](https://dev.azure.com/dnceng-public/public/_build/results?buildId=289319)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=289319&view=ms.vss-test-web.build-test-results-tab&runId=5785350&resultId=112392)||
|[288816](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288816)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288816&view=ms.vss-test-web.build-test-results-tab&runId=5772756&resultId=112392)||
|[288696](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288696)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288696&view=ms.vss-test-web.build-test-results-tab&runId=5767688&resultId=112392)|dotnet/runtime#86854|
|[288661](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288661)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288661&view=ms.vss-test-web.build-test-results-tab&runId=5766110&resultId=112392)||
|[288473](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288473)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288473&view=ms.vss-test-web.build-test-results-tab&runId=5764750&resultId=112392)|dotnet/runtime#86842|
|[288603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288603)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288603&view=ms.vss-test-web.build-test-results-tab&runId=5764544&resultId=120667)||
|[288489](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288489)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288489&view=ms.vss-test-web.build-test-results-tab&runId=5761296&resultId=112392)||
|[288379](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288379)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288379&view=ms.vss-test-web.build-test-results-tab&runId=5758140&resultId=112392)||
|[288302](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288302)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288302&view=ms.vss-test-web.build-test-results-tab&runId=5756082&resultId=120666)||
|[288186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288186)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288186&view=ms.vss-test-web.build-test-results-tab&runId=5753384&resultId=112392)||
|[287916](https://dev.azure.com/dnceng-public/public/_build/results?buildId=287916)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=287916&view=ms.vss-test-web.build-test-results-tab&runId=5748640&resultId=112392)||
|[287757](https://dev.azure.com/dnceng-public/public/_build/results?buildId=287757)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=287757&view=ms.vss-test-web.build-test-results-tab&runId=5744180&resultId=112391)|dotnet/runtime#85692|
|[287085](https://dev.azure.com/dnceng-public/public/_build/results?buildId=287085)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=287085&view=ms.vss-test-web.build-test-results-tab&runId=5727280&resultId=112391)||
|[286854](https://dev.azure.com/dnceng-public/public/_build/results?buildId=286854)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=286854&view=ms.vss-test-web.build-test-results-tab&runId=5720104&resultId=112389)||
|[286685](https://dev.azure.com/dnceng-public/public/_build/results?buildId=286685)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=286685&view=ms.vss-test-web.build-test-results-tab&runId=5717128&resultId=112389)||
|[286557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=286557)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=286557&view=ms.vss-test-web.build-test-results-tab&runId=5712872&resultId=112391)||
|[286466](https://dev.azure.com/dnceng-public/public/_build/results?buildId=286466)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=286466&view=ms.vss-test-web.build-test-results-tab&runId=5711394&resultId=112389)||
|[285749](https://dev.azure.com/dnceng-public/public/_build/results?buildId=285749)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=285749&view=ms.vss-test-web.build-test-results-tab&runId=5693242&resultId=112389)||
|[285617](https://dev.azure.com/dnceng-public/public/_build/results?buildId=285617)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=285617&view=ms.vss-test-web.build-test-results-tab&runId=5688968&resultId=112389)||
|[285493](https://dev.azure.com/dnceng-public/public/_build/results?buildId=285493)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=285493&view=ms.vss-test-web.build-test-results-tab&runId=5686596&resultId=112389)||
|[285027](https://dev.azure.com/dnceng-public/public/_build/results?buildId=285027)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=285027&view=ms.vss-test-web.build-test-results-tab&runId=5685648&resultId=112389)|dotnet/runtime#86690|
|[285287](https://dev.azure.com/dnceng-public/public/_build/results?buildId=285287)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=285287&view=ms.vss-test-web.build-test-results-tab&runId=5682806&resultId=112389)||
|[284500](https://dev.azure.com/dnceng-public/public/_build/results?buildId=284500)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=284500&view=ms.vss-test-web.build-test-results-tab&runId=5664698&resultId=112389)||
|[283991](https://dev.azure.com/dnceng-public/public/_build/results?buildId=283991)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=283991&view=ms.vss-test-web.build-test-results-tab&runId=5655682&resultId=112388)||
|[283137](https://dev.azure.com/dnceng-public/public/_build/results?buildId=283137)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=283137&view=ms.vss-test-web.build-test-results-tab&runId=5635148&resultId=112389)||
|[283140](https://dev.azure.com/dnceng-public/public/_build/results?buildId=283140)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=283140&view=ms.vss-test-web.build-test-results-tab&runId=5634798&resultId=112436)|dotnet/runtime#86554|
|[283011](https://dev.azure.com/dnceng-public/public/_build/results?buildId=283011)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=283011&view=ms.vss-test-web.build-test-results-tab&runId=5633456&resultId=112389)|dotnet/runtime#86581|
|[282482](https://dev.azure.com/dnceng-public/public/_build/results?buildId=282482)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=282482&view=ms.vss-test-web.build-test-results-tab&runId=5627612&resultId=112389)||
|[282672](https://dev.azure.com/dnceng-public/public/_build/results?buildId=282672)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=282672&view=ms.vss-test-web.build-test-results-tab&runId=5625656&resultId=112389)|dotnet/runtime#86581|
|[281884](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281884)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281884&view=ms.vss-test-web.build-test-results-tab&runId=5605794&resultId=112321)|dotnet/runtime#86581|
|[281696](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281696)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281696&view=ms.vss-test-web.build-test-results-tab&runId=5599066&resultId=112388)|dotnet/runtime#86342|
|[281656](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281656)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281656&view=ms.vss-test-web.build-test-results-tab&runId=5598070&resultId=112388)||
|[281352](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281352)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281352&view=ms.vss-test-web.build-test-results-tab&runId=5583138&resultId=112388)||
|[281259](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281259)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281259&view=ms.vss-test-web.build-test-results-tab&runId=5580956&resultId=112388)|dotnet/runtime#86554|
|[281245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281245)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281245&view=ms.vss-test-web.build-test-results-tab&runId=5580498&resultId=112435)|dotnet/runtime#86554|
|[281173](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281173)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281173&view=ms.vss-test-web.build-test-results-tab&runId=5580012&resultId=112388)|dotnet/runtime#85643|
|[281185](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281185)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281185&view=ms.vss-test-web.build-test-results-tab&runId=5579798&resultId=120653)||
|[281107](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281107)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=281107&view=ms.vss-test-web.build-test-results-tab&runId=5577748&resultId=112388)||
|[280994](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280994)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280994&view=ms.vss-test-web.build-test-results-tab&runId=5574580&resultId=112387)||
|[280892](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280892)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280892&view=ms.vss-test-web.build-test-results-tab&runId=5571746&resultId=120651)||
|[280763](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280763)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280763&view=ms.vss-test-web.build-test-results-tab&runId=5567630&resultId=112388)||
|[280375](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280375)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280375&view=ms.vss-test-web.build-test-results-tab&runId=5562432&resultId=112388)||
|[279332](https://dev.azure.com/dnceng-public/public/_build/results?buildId=279332)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=279332&view=ms.vss-test-web.build-test-results-tab&runId=5542712&resultId=112388)||
|[278778](https://dev.azure.com/dnceng-public/public/_build/results?buildId=278778)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=278778&view=ms.vss-test-web.build-test-results-tab&runId=5532542&resultId=112388)||
|[278375](https://dev.azure.com/dnceng-public/public/_build/results?buildId=278375)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=278375&view=ms.vss-test-web.build-test-results-tab&runId=5524852&resultId=112383)|dotnet/runtime#86194|
|[278104](https://dev.azure.com/dnceng-public/public/_build/results?buildId=278104)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=278104&view=ms.vss-test-web.build-test-results-tab&runId=5517144&resultId=112383)|dotnet/runtime#86430|
|[278002](https://dev.azure.com/dnceng-public/public/_build/results?buildId=278002)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=278002&view=ms.vss-test-web.build-test-results-tab&runId=5514022&resultId=112383)||
|[277389](https://dev.azure.com/dnceng-public/public/_build/results?buildId=277389)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=277389&view=ms.vss-test-web.build-test-results-tab&runId=5502858&resultId=112383)||
|[276852](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276852)|dotnet/runtime|[Loader.classloader.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276852&view=ms.vss-test-web.build-test-results-tab&runId=5491450&resultId=112383)|dotnet/runtime#86269|
|[276623](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276623)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276623&view=ms.vss-test-web.build-test-results-tab&runId=5483304&resultId=112383)|dotnet/runtime#86375|
|[276622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276622)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276622&view=ms.vss-test-web.build-test-results-tab&runId=5483260&resultId=112383)|dotnet/runtime#85965|
|[276603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276603)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276603&view=ms.vss-test-web.build-test-results-tab&runId=5482412&resultId=112383)||
|[276393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276393)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=276393&view=ms.vss-test-web.build-test-results-tab&runId=5476422&resultId=100314)|dotnet/runtime#86366|
|[275963](https://dev.azure.com/dnceng-public/public/_build/results?buildId=275963)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=275963&view=ms.vss-test-web.build-test-results-tab&runId=5469592&resultId=112383)||
|[275222](https://dev.azure.com/dnceng-public/public/_build/results?buildId=275222)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=275222&view=ms.vss-test-web.build-test-results-tab&runId=5452902&resultId=112383)|dotnet/runtime#86307|
|[274202](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274202)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274202&view=ms.vss-test-web.build-test-results-tab&runId=5445590&resultId=112383)|dotnet/runtime#86266|
|[275006](https://dev.azure.com/dnceng-public/public/_build/results?buildId=275006)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=275006&view=ms.vss-test-web.build-test-results-tab&runId=5443922&resultId=112383)||
|[274405](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274405)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274405&view=ms.vss-test-web.build-test-results-tab&runId=5430808&resultId=112383)||
|[274003](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274003)|dotnet/runtime|[tracing/runtimeeventsource/nativeruntimeeventsource/nativeruntimeeventsource.sh](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274003&view=ms.vss-test-web.build-test-results-tab&runId=5419580&resultId=100176)|dotnet/runtime#86097|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|7|30|66|

### PR DESCRIPTION
**Pull request by kotlarmilos**
This PR aims to introduce support for handling deferred failures that may occur during AOT compilation. When the AOT compiler encounters a failure during a class initialization that is not severe enough to require aborting the AOT compilation process, it will print a warning and proceed with the class layout setup and initialization. During runtime, if a class has a deferred failure, it will skip cached data and instead opt for the slower process of setting up the class layout at runtime, which allow exception handling during the execution.

In the AOT compilation phase, the function `set_failure_type(DEFERRED_FAILURE)` is called to set a failure callback that defers a failure for runtime execution. During JIT and AOT runtime, the function `set_failure_type(IMMEDIATE_FAILURE)` is called to set a failure callback which handles failures during the execution.

Fixes https://github.com/dotnet/runtime/issues/86327

### CODE REVIEW

**Review by lambdageek — APPROVED** [review]
lgtm

**Review by lambdageek — APPROVED** [review]
lgtm

**Review by vargaz — APPROVED** [review]

**Comment by kotlarmilos** [comment]
The failures are known and shouldn't be related.

**Pull request merged**
