### PR TITLE
IL cleanup - remove .module and make .assembly match source name

### PR DESCRIPTION
**Pull request by trylek**
/cc @dotnet/jit-contrib

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]
LGTM!

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
Question: all these cleanups are nice. Will newly written tests be required to follow all the cleanup "rules"?

**Comment by trylek** [comment]
@BruceForstall - we'll definitely need to add documentation describing the new testing model in more detail. Once all tests have been converted to the new merged wrapper model, authoring a new ILPROJ test will require applying the three transformations (removing .module, making sure .assembly matches the file and adding the [Fact] attribute on main), otherwise the test simply won't work (the Roslyn source generator cannot locate its entrypoint).

**Pull request merged**
