### PR TITLE
Fix and reenable TestUserCredentialsPropertiesOnWindows 

### LINKED ISSUE #18978: [1.0.0] TestUserCredentialsPropertiesOnWindows failing on Windows (v1.0 only)
```
System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows [FAIL]
        System.InvalidOperationException : No process is associated with this object.
        Stack Trace:
           D:\j\workspace\outerloop_win---2155886e\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(779,0): at System.Diagnostics.Process.EnsureState(State state)
           D:\j\workspace\outerloop_win---2155886e\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(189,0): at System.Diagnostics.Process.get_HasExited()
           D:\j\workspace\outerloop_win---2155886e\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(393,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows()
```

Examples:
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_release/13/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_debug/12/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_release/12/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_debug/12/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_release/12/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_debug/11/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_release/11/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_debug/11/
http://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_release/11/
...

### PR DESCRIPTION
**Pull request by adamsitnik**
Removal of the user via  `Interop.NetUserDel` was never working because it was missing `CharSet = CharSet.Unicode`. I've fixed that and changed the test to:
- use more unique name than "test"
- always try to remove the test account first
- fail (don't swallow the exception) if the creation of the account failed
- fail (don't ignore error code `NERR_UserNotFound`) if the removal of the account failed

The user might have been missing rights to read and execute `dotnet.exe` (for example when `build.cmd` was executed from Admin PSW) and in that case the test was throwing `Access denied` from `Process.Start`. I've changed the test to always add the permission to read and execute before running the `.exe`

Now it works as expected:

obraz

Fixes #18978

### CODE REVIEW

**Review by eiriktsarpalis — APPROVED** [review]
If CI is happy I'm happy.

**Comment by adamsitnik** [comment]
> We stopped hearing from agent NetCorePublic-Pool 1. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error

So here we go again

/azp run runtime-libraries-coreclr outerloop-windows

**Comment by adamsitnik** [comment]
The CI has failed with a very interesting [error](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46083-merge-b791b459ac934b7cb9/System.Diagnostics.Process.Tests/console.56ff2e4d.log?sv=2019-07-07&se=2021-01-05T14%3A30%3A58Z&sr=c&sp=rl&sig=Kb2Pqnj4WrhwOC9m2FhSPWuXkF23uT8bjqZBhqNNSCA%3D): 

```log
    System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows [FAIL]
      System.DllNotFoundException : Unable to load DLL 'netapi32.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
      Stack Trace:
           at System.Diagnostics.Tests.Interop.NetUserDel(String servername, String username)
        /_/src/libraries/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(360,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows()
```

**Comment by adamsitnik** [comment]
> If CI is happy I'm happy

The CI is happy and so am I ;)

**Pull request merged**
