### PR TITLE
Skip RC2 encrypted PKCS12 files on Android for iteration counting

### PR DESCRIPTION
**Pull request by vcsjones**
One of the test documents we use for iteration counting need to test with RC2, which is not supported on Android. Let's skip it.

Contributes to #88747.

One accepted we should backport to release/7.0 and release/6.0.

### CODE REVIEW

**Review by GrabYourPitchforks — APPROVED** [review]

**Review by carlossanlop — APPROVED** [review]

**Review by carlossanlop — APPROVED** [review]
Assuming the same CI runs that failed in the test get executed here with the extra azp runs, and they pass, then LGTM.

**Review by jkoritzinsky — APPROVED** [review]

**Comment by vcsjones** [comment]
Test failures are unrelated. The tests that were failing are now being skipped.
image


Merging.

**Pull request merged**
