### PR TITLE
JIT: Introduce GT_JTEST and clean up GT_JCMP flags

### PR DESCRIPTION
**Pull request by jakobbotsch**
* Introduce GT_JTEST to replace GTF_JCMP_TEST
* Stop encoding JCMP conditions in GenTreeFlags by switching GT_JCMP to a GenTreeOpCC node. This removes GTF_JCMP_EQ and the LoongArch64/RISC-V specific mechanism to communicate condition codes to the backend via gtFlags.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
cc @shushanhf @clamp03. This is an alternative to #85217 that stops using `GenTreeFlags` to communicate the condition and cleans up the representation at the same time.

Also, unrelated to this PR, but I had to apply several patches to get the RISC-V/LoongArch cross-jits to build: https://gist.github.com/jakobbotsch/a11071cec499ef260fbe1b5c85c1b32f
You may want to look into some of these and why they're necessary.

**Comment by shushanhf** [comment]
> cc @shushanhf @clamp03. This is an alternative to #85217 that stops using `GenTreeFlags` to communicate the condition and cleans up the representation at the same time.

Thansk.

> Also, unrelated to this PR, but I had to apply several patches to get the RISC-V/LoongArch cross-jits to build: https://gist.github.com/jakobbotsch/a11071cec499ef260fbe1b5c85c1b32f You may want to look into some of these and why they're necessary.

I will add LA64's image for CI.  https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/856

**Comment by shushanhf** [comment]
> > cc @dotnet/jit-contrib PTAL @TIHan -- related to what we have discussed a couple of times. [No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=249803&view=ms.vss-build-web.run-extensions-tab).
> > @clamp03 @shushanhf If you can test the LA/RISC-V changes it would be great.
> 
> OK，I will test it later.

I just tested some cases. I think this is ok.
All the tests will be finished tomorrow morning.

**Comment by shushanhf** [comment]
> > > cc @dotnet/jit-contrib PTAL @TIHan -- related to what we have discussed a couple of times. [No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=249803&view=ms.vss-build-web.run-extensions-tab).
> > > @clamp03 @shushanhf If you can test the LA/RISC-V changes it would be great.
> > 
> > 
> > OK，I will test it later.
> 
> All the tests will be finished tomorrow morning.

@jakobbotsch 
For LoongArch64, this is ok.
Thanks

**Comment by clamp03** [comment]
Thank you. I will check.
CC https://github.com/dotnet/runtime/issues/84834

**Review by clamp03 — APPROVED** [review]
Checked on RISC-V. It works well. Thank you.

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
