### PR TITLE
Include the "TargetingPack" folder in the mobile apps.

### LINKED ISSUE #61299: Test failure Loader/classloader/DictionaryExpansion/DictionaryExpansion/DictionaryExpansion.sh
Run:[ runtime 20211107.13](https://dev.azure.com/dnceng/public/_build/results?buildId=1458388&view=ms.vss-test-web.build-test-results-tab&runId=41921704&resultId=100313&paneView=debug)

Failed test:
```
Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open

- Loader/classloader/DictionaryExpansion/DictionaryExpansion/DictionaryExpansion.sh

```
**Error message:**
```
11-06 21:59:32.724 21938 21955 E mono    : Unhandled Exception:
      11-06 21:59:32.724 21938 21955 E mono    : System.IO.FileNotFoundException: Could not load file or assembly 'xunit.assert, Version=2.4.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies.
      11-06 21:59:32.724 21938 21955 E mono    : File name: 'xunit.assert, Version=2.4.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'
      11-06 21:59:32.724 21938 21955 E mono    :    at GenClass`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].DoTest_GenDerived(Int32 max)
      11-06 21:59:32.724 21938 21955 E mono    :    at Test_DictionaryExpansion.Main()
      11-06 21:59:32.724 21938 21955 E DOTNET  : UnhandledException: System.IO.FileNotFoundException Could not load file or assembly 'xunit.assert, Version=2.4.2.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies.    at GenClass`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].DoTest_GenDerived(Int32 max)
      11-06 21:59:32.724 21938 21955 E DOTNET  :    at Test_DictionaryExpansion.Main()
```

### LINKED ISSUE #61322: dictionaryexpansion tests failing on Mono
Runfo Tracking Issue: [dictionaryexpansion tests failing on mono](https://runfo.azurewebsites.net/tracking/issue/208)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1463637](https://dev.azure.com/dnceng/public/_build/results?buildId=1463637)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5f04a56a709b4b7ba8/Loader.classloader/1/console.7dfd41d9.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-30T21%25253A20%25253A32Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DZgyKhDmf%25252BuMr37DIuQOfPdYwtgIECu%25252BYlMNIzqdfqGY%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5f04a56a709b4b7ba8/Loader.classloader/4e6dd7d4-e806-49bc-9545-52f92e42f02d.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-30T21%25253A20%25253A32Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DZgyKhDmf%25252BuMr37DIuQOfPdYwtgIECu%25252BYlMNIzqdfqGY%25253D)|
|[1462920](https://dev.azure.com/dnceng/public/_build/results?buildId=1462920)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 60879](https://github.com/dotnet/runtime/pull/60879)|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60879-merge-158e572787114831b5/Loader.classloader/1/console.51bb56ab.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-30T16%25253A02%25253A27Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D5ocfEVZX70lr%25252B3XIFZM2BxFC2Ps81oBB0ckkHL5EVjA%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60879-merge-158e572787114831b5/Loader.classloader/7be52daa-3db6-48eb-bf41-90d3722d856f.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-30T16%25253A02%25253A27Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D5ocfEVZX70lr%25252B3XIFZM2BxFC2Ps81oBB0ckkHL5EVjA%25253D)|
|[1462569](https://dev.azure.com/dnceng/public/_build/results?buildId=1462569)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2ca5f226ba594e398d/Loader.classloader/1/console.ee1b52ee.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-30T09%25253A28%25253A56Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DTwXZsEvM263q3y%25252BC5g3qsmat8ERhFJjPnjT%25252BkvdyrLI%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-2ca5f226ba594e398d/Loader.classloader/12e1a6c3-7a84-43ab-bf12-a52751c8d84f.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-30T09%25253A28%25253A56Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DTwXZsEvM263q3y%25252BC5g3qsmat8ERhFJjPnjT%25252BkvdyrLI%25253D)|
|[1462387](https://dev.azure.com/dnceng/public/_build/results?buildId=1462387)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 61030](https://github.com/dotnet/runtime/pull/61030)|CoreCLR Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61030-merge-99031bcef21c42b9a8/Loader.classloader/1/console.3452af6f.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-30T04%25253A34%25253A51Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DVTCbWGuGRuNRgaiqLtfCXuYx0u3uLX3fnw3TrSX30SU%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61030-merge-99031bcef21c42b9a8/Loader.classloader/1/coredump.49.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-30T04%25253A34%25253A51Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DVTCbWGuGRuNRgaiqLtfCXuYx0u3uLX3fnw3TrSX30SU%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61030-merge-99031bcef21c42b9a8/Loader.classloader/50fbc277-1b42-4d38-9559-a16ba45c9a68.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-30T04%25253A34%25253A51Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DVTCbWGuGRuNRgaiqLtfCXuYx0u3uLX3fnw3TrSX30SU%25253D)|
|[1462387](https://dev.azure.com/dnceng/public/_build/results?buildId=1462387)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 61030](https://github.com/dotnet/runtime/pull/61030)|CoreCLR Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61030-merge-732d7e01d187428796/Loader.classloader/1/console.227230e2.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-30T04%25253A34%25253A51Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dg6Sb9i4iX9Gx7Jn9tuerO%25252Bje%25252BGH5YNJQTK%25252BeDCCvCBQ%25253D)|[core dump](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61030-merge-732d7e01d187428796/Loader.classloader/1/coredump.224.dmp?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-30T04%25253A34%25253A51Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dg6Sb9i4iX9Gx7Jn9tuerO%25252Bje%25252BGH5YNJQTK%25252BeDCCvCBQ%25253D)||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61030-merge-732d7e01d187428796/Loader.classloader/af77b1d9-5c79-49f9-8618-94062a340c24.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-30T04%25253A34%25253A51Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dg6Sb9i4iX9Gx7Jn9tuerO%25252Bje%25252BGH5YNJQTK%25252BeDCCvCBQ%25253D)|
|[1461465](https://dev.azure.com/dnceng/public/_build/results?buildId=1461465)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-08b7115a58034604bc/Loader.classloader/1/console.17f4a232.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-29T21%25253A04%25253A37Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DOHwxfHSXESj6jGQdUSf2%25252Bral7n9TF3KKlzqg40k6g14%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-08b7115a58034604bc/Loader.classloader/0868e005-ce4b-43b4-acca-a5ef9d6ec5a3.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-29T21%25253A04%25253A37Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DOHwxfHSXESj6jGQdUSf2%25252Bral7n9TF3KKlzqg40k6g14%25253D)|
|[1461427](https://dev.azure.com/dnceng/public/_build/results?buildId=1461427)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61235-head-b29eb2ac83b84c0f8e/Loader.classloader/1/console.babc9ce9.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-29T20%25253A51%25253A54Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D7bAg9WJtCd%25252BeyIj18hfSP77L3o4ZH8nahYUfOK9JmUU%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-61235-head-b29eb2ac83b84c0f8e/Loader.classloader/98c85bfd-7348-4973-82a1-94dd5870bcb3.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-29T20%25253A51%25253A54Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D7bAg9WJtCd%25252BeyIj18hfSP77L3o4ZH8nahYUfOK9JmUU%25253D)|
|[1461256](https://dev.azure.com/dnceng/public/_build/results?buildId=1461256)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 60879](https://github.com/dotnet/runtime/pull/60879)|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60879-merge-8760c76492304d43b8/Loader.classloader/1/console.73a0e1ed.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-29T19%25253A44%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DO402rcAjoYwoOT5fzksXuimAh4oqZikZmiDlkLuzbG8%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60879-merge-8760c76492304d43b8/Loader.classloader/5043074b-1b58-4b46-a4b2-5a8222a6fd84.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-29T19%25253A44%25253A35Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DO402rcAjoYwoOT5fzksXuimAh4oqZikZmiDlkLuzbG8%25253D)|
|[1460580](https://dev.azure.com/dnceng/public/_build/results?buildId=1460580)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ec6ada3681084e9697/Loader.classloader/1/console.f432f09f.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-29T09%25253A11%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DuKEiYg0tJdUK0iVUHwozWc50wZyup1vKSZIob9dNXk4%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ec6ada3681084e9697/Loader.classloader/425daf07-1fac-4636-91da-dc1fe1075efa.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-29T09%25253A11%25253A28Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DuKEiYg0tJdUK0iVUHwozWc50wZyup1vKSZIob9dNXk4%25253D)|
|[1459735](https://dev.azure.com/dnceng/public/_build/results?buildId=1459735)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 60879](https://github.com/dotnet/runtime/pull/60879)|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60879-merge-3d4b545044234208ac/Loader.classloader/1/console.a122eb31.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-28T22%25253A24%25253A48Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DtwjiyTgObKQYNMD%25252FZHPaZfRCVqUkPv77u8xr6ibdsGg%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60879-merge-3d4b545044234208ac/Loader.classloader/ab120d02-f548-40bd-946f-60e0501f7766.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-28T22%25253A24%25253A48Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DtwjiyTgObKQYNMD%25252FZHPaZfRCVqUkPv77u8xr6ibdsGg%25253D)|
|[1459618](https://dev.azure.com/dnceng/public/_build/results?buildId=1459618)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c92368899593400b91/Loader.classloader/1/console.d339ee20.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-28T21%25253A18%25253A20Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dp%25252FC62obzuKA7r69fIHq1HhWzEO4pBkops4jU%25252Bi1Rdow%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c92368899593400b91/Loader.classloader/16cfc4d7-7157-41e2-a2d0-ab2ff28b5b40.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-28T21%25253A18%25253A20Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dp%25252FC62obzuKA7r69fIHq1HhWzEO4pBkops4jU%25252Bi1Rdow%25253D)|
|[1458701](https://dev.azure.com/dnceng/public/_build/results?buildId=1458701)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-73cac01f0f5143e6aa/Loader.classloader/1/console.47b07e86.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-28T09%25253A02%25253A09Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DLYWHmxUnVV%25252FA2L9pf1nmPU5jc%25252BSXVV1yuBOv9Wmm7vQ%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-73cac01f0f5143e6aa/Loader.classloader/57f50293-1a65-4f19-b531-6b8fd271d2df.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-28T09%25253A02%25253A09Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DLYWHmxUnVV%25252FA2L9pf1nmPU5jc%25252BSXVV1yuBOv9Wmm7vQ%25253D)|
|[1458388](https://dev.azure.com/dnceng/public/_build/results?buildId=1458388)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-cc5faf9b61e04d5f8f/Loader.classloader/1/console.96dc4691.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-27T21%25253A00%25253A45Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DCeNIakaTkz%25252BzNnohPKhgL4KFoHH621izhLsFP7Bop%25252FA%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-cc5faf9b61e04d5f8f/Loader.classloader/a3e2c824-ca73-4ea5-8f30-ce7705452363.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-27T21%25253A00%25253A45Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DCeNIakaTkz%25252BzNnohPKhgL4KFoHH621izhLsFP7Bop%25252FA%25253D)|
|[1458188](https://dev.azure.com/dnceng/public/_build/results?buildId=1458188)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-aaa6eb2fde1e4f54a0/Loader.classloader/1/console.8edcfb5c.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-27T09%25253A00%25253A27Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DuyZ6SVY8pv0WfEeVIkz9xnlgPpfqnNo7DQTERNMoLbI%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-aaa6eb2fde1e4f54a0/Loader.classloader/03c72715-78dd-4a7a-b500-334f7f3181c0.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-27T09%25253A00%25253A27Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DuyZ6SVY8pv0WfEeVIkz9xnlgPpfqnNo7DQTERNMoLbI%25253D)|
|[1457989](https://dev.azure.com/dnceng/public/_build/results?buildId=1457989)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|Mono Android x64 Release @ Ubuntu.1804.Amd64.Android.29.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c1947c38549f467ba0/Loader.classloader/1/console.8aad420f.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-26T21%25253A21%25253A24Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DCVVjNTZpt3yUF5sQUEgn4ocj2XZA5T9oeNM0vm4%25252B1ZI%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-c1947c38549f467ba0/Loader.classloader/dcfc9a5b-3403-40bd-9382-fd33050120b7.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-11-26T21%25253A21%25253A24Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DCVVjNTZpt3yUF5sQUEgn4ocj2XZA5T9oeNM0vm4%25252B1ZI%25253D)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|4|14|14|

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Include the "TargetingPack" folder in the mobile app test suites.

Fixes #61322
Fixes #61299

### CODE REVIEW

**Comment by fanyang-mono** [comment]
I was wondering if you tried to run the failing test locally to validate this change? Because the CI lane for runtime tests running on mobile targets have been moved to rolling build only.

**Comment by jkoritzinsky** [comment]
I’ll queue a rolling build directly on this branch to validate it after lunch.

**Comment by fanyang-mono** [comment]
> I’ll queue a rolling build directly on this branch to validate it after lunch.

Sounds good. Thank you!

**Comment by jkoritzinsky** [comment]
Queued the CI run as a build against the branch directly, so it'll run the mobile legs too: https://dev.azure.com/dnceng/public/_build/results?buildId=1463787&view=results

**Comment by jkoritzinsky** [comment]
Looks like the test passed in CI (The failures are on other platforms or in the libraries test tree for unrelated infrastructure issues)

**Comment by jkoritzinsky** [comment]
@fanyang-mono @agocke can I get a review on this PR? None of the test failures are related to the fix (some of it looks like Helix infra bugs in the Python scripts TBH as the logs say the tests all passed).

**Comment by jkoritzinsky** [comment]
As merging is blocked since the tvOSSimulator job timed out without reporting that it failed, I'm going to rerun the failed legs to try to get a mergeable PR state.

**Review by agocke — APPROVED** [review]
LGTM

**Comment by fanyang-mono** [comment]
LGTM

**Pull request merged**
