### PR TITLE
Switch DateTimeKind from Unspecified to Local

### LINKED ISSUE #30128: ManagementDateTimeConverter.ToDateTime returns the wrong DateTimeKind
The `System.Management.ManagementDateTimeConverter.ToDateTime` method is setting `DateTimeKind.Unspecified` in the result [here](https://github.com/dotnet/corefx/blob/1c3d001566b0d38c90e074e33d7394d507311956/src/System.Management/src/System/Management/ManagementDateTime.cs#L199).

I believe this to be incorrect, as it explicitly adjusts the time to the local computer's offset.  As a user of this API, I'd expect the resulting `DateTime` value's `Kind` property to be `DateTimeKind.Local`.

With unspecified kind, I'd expect the result to *not* have been adjusted to the local time zone.

Also, a couple of other observations about the `ManagementDateTimeConverter` class:

- The fixes from May 2018 seen in the history don't appear to have been ported back to .NET Framework.  For example, I can see that in the NetFX implementation it still uses `TimeZone.CurrentTimeZone` instead of `TimeZoneInfo.Local`.

- It would seem prudent to make a `ToDateTimeOffset` method that retains the offset provided in the DMTF string.  Otherwise the user has to go out of their way to parse the string again manually to obtain the original offset.

- Likewise, it would seem prudent to have an overload of `ToDMTFDateTime` that accepts a `DateTimeOffset`.  Otherwise, there's no capability to create a DMTF string that has anything other than the local offset or zero.

### PR DESCRIPTION
**Pull request by Maximys**
Fix #30128

### CODE REVIEW

**Comment by Maximys** [comment]
@ericstj, could you look to current PR and failed test [System.Management.Tests.ManagementDateTimeConverterTests.DateTime_MinValue_RoundTrip](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366683&view=ms.vss-test-web.build-test-results-tab&runId=7758106&resultId=113874&paneView=debug)?
If I correctly understand, [.NET Framework 4.8](https://referencesource.microsoft.com/#System.Management/ManagementDatetime.cs,194) currently use [DateTime(Int32, Int32, Int32, Int32, Int32, Int32, Int32)](https://learn.microsoft.com/ru-ru/dotnet/api/system.datetime.-ctor?view=net-7.0#system-datetime-ctor(system-int32-system-int32-system-int32-system-int32-system-int32-system-int32-system-int32)) inside [ToDateTime](https://referencesource.microsoft.com/#System.Management/ManagementDatetime.cs,18028db43b6fa364) method.

**Comment by ericstj** [comment]
That test cannot expect the behavior to change on .NETFramework - since we don't build `System.Management` for .NETFramework here.

> If I correctly understand, [.NET Framework 4.8](https://referencesource.microsoft.com/#System.Management/ManagementDatetime.cs,194) currently use [DateTime(Int32, Int32, Int32, Int32, Int32, Int32, Int32)](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.-ctor?view=net-7.0#system-datetime-ctor(system-int32-system-int32-system-int32-system-int32-system-int32-system-int32-system-int32)) inside [ToDateTime](https://referencesource.microsoft.com/#System.Management/ManagementDatetime.cs,18028db43b6fa364) method.

Yes, that's correct.

So you'd need to make this test expect different behavior on .NETFramework.

@tarekgh @dotnet/area-system-management do you see a problem with this bug being fixed here?

**Comment by tarekgh** [comment]
I expressed in my old comment https://github.com/dotnet/runtime/issues/30128#issuecomment-508201624 that the behavior is not matching the docs which expect the fixed behavior. So, I am fine with the fix but I prefer filing a breaking change issue for this one https://github.com/dotnet/docs/issues/new?assignees=gewarren&labels=breaking-change%2CPri1%2Cdoc-idea&projects=&template=breaking-change.yml&title=%5BBreaking+change%5D%3A+.

> So you'd need to make this test expect different behavior on .NETFramework.

Correct, the test is already failing and should be fixed to return different result on NETFX. https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-90149-merge-039e8e43d9964292b0/System.Management.Tests/1/console.7246bcff.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-90149-merge-039e8e43d9964292b0/System.Management.Tests/1/console.7246bcff.log?helixlogtype=result)

**Review by IDisposable — COMMENTED** [review]
:shipit:

**Comment by Maximys** [comment]
@tarekgh , test for .NET Framework was skipped by the https://github.com/dotnet/runtime/pull/90149/commits/59e589250a01a5a6ee441d2f012d13dba29ce200 commit.
Breaking change issue is [here](https://github.com/dotnet/docs/issues/36651)

**Comment by tarekgh** [comment]
@Maximys thanks a lot for your response and opening the breaking change tracking. Would it make sense to not skip the test on the NETFX and instead validate the expected value there? you can use https://github.com/dotnet/runtime/blob/376e2353e4a06bd79639cad4ea83fd9001e62883/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.Windows.cs#L21 to do this check.

**Comment by Maximys** [comment]
@tarekgh , I had fixed highlighted problem, but there are some unrelated test failures. Could you look please?

**Review by tarekgh — APPROVED** [review]

**Comment by tarekgh** [comment]
I tracked the failed test with https://github.com/dotnet/runtime/issues/90521

**Pull request merged**
