### PR TITLE
Remove `Microsoft.IO.Redist`.

### LINKED ISSUE #58334: Delete Microsoft.IO.Redist.csproj
https://github.com/dotnet/runtime/pull/55150#issuecomment-873918682
https://github.com/dotnet/runtime/pull/58167/files#r696648969

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
Fixes #58334.

I removed both the package and all mentions of the `MS_IO_REDIST` symbol.

### CODE REVIEW

**Review by adamsitnik — APPROVED** [review]
LGTM, big thanks @teo-tsirpanis !

Similarly to #57735 we need to wait for more weeks before we merge it (https://github.com/dotnet/runtime/pull/57735#issuecomment-902915749).

I am going to add a `NO MERGE` label to indicate that.

**Comment by danmoseley** [comment]
Do we need to communicate with any existing users of this package? (eg., VS or MSBuild?). 
Assuming the idea is to port this change into release/6.0, would any of those current users then be forced to "go back" to 5.0 to get any servicing changes?

**Comment by stephentoub** [comment]
> Assuming the idea is to port this change into release/6.0

I don't believe that's the idea.

**Comment by danmoseley** [comment]
> I don't believe that's the idea.

Ah - good. I had misinterpreted a "wait until RC2" comment earlier.

**Comment by adamsitnik** [comment]
The plan is to remove it in .NET 7, we just a few more weeks to avoid having merge conflicts when backporting changes from System.File.IO to 6.0 branch

**Review by stephentoub — APPROVED** [review]
Thanks!

**Review by jeffhandley — APPROVED** [review]
I merged from main and resolved the conflicts. We can proceed with merging this once CI completes.

**Pull request merged**
