### PR TITLE
Improve call counting mechanism

### LINKED ISSUE #24664: JIT.Methodical failing on coreclr outerloop
From one of the logs

```
Assert failure(PID 18 [0x00000012], Thread: 1308 [0x051c]): activeCodeVersion == methodDesc->GetCodeVersionManager()->GetActiveILCodeVersion(methodDesc).GetActiveNativeCodeVersion(methodDesc)
    File: /__w/2/s/src/coreclr/src/vm/callcounting.cpp Line: 518
    Image: /root/helix/work/correlation/corerun
```

Builds
- https://dev.azure.com/dnceng/public/_build/results?buildId=503076
- https://dev.azure.com/dnceng/public/_build/results?buildId=502600

Test Runs
 - Linux arm Checked @@(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
 - Linux arm Checked `@ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open`@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

### LINKED ISSUE #29934: Crashes caused by "Improve call counting mechanism" change
We are seeing more intermittent crashes than usual in CI in last few days. All crash dumps point to a problem with this PR. The typical crash is AV, early during the xunit process startup, with a stacktrace like this:

```
#0  MethodDesc::HasNativeCodeSlot (this=0x25) at /__w/1/s/src/coreclr/src/vm/method.hpp:1886
#1  MethodDesc::GetNativeCode (this=0x25) at /__w/1/s/src/coreclr/src/vm/method.cpp:1028
#2  0x00007f2908dff137 in CallCountingManager::OnCallCountThresholdReached (transitionBlock=<optimized out>,
    stubIdentifyingToken=<optimized out>) at /__w/1/s/src/coreclr/src/vm/callcounting.cpp:743
#3  0x00007f2908de3289 in OnCallCountThresholdReachedStub2 ()
    at /__w/1/s/src/coreclr/src/pal/inc/unixasmmacrosamd64.inc:986
#4  0x00007f288f9887f9 in ?? ()
#5  0x00007f288df8b050 in ?? ()
#6  0x00007f288f4e91bb in ?? ()
#7  0x00007f286813041e in ?? ()
```

### PR DESCRIPTION
**Pull request by kouvel**
- Commit 1
  - Reverts commit f954c6bb80a21d9c44a6ee751d935a0573f7226a, which reverted PR https://github.com/dotnet/runtime/pull/1457 due to issues
- Commit 2
  - Fixes crashes and assertion failures seen by the original change, fixes https://github.com/dotnet/runtime/issues/29934
  - The crashes were caused by commit https://github.com/dotnet/runtime/pull/1457/commits/6aa3c7083735895c2e687a77e3636080edb366c3 in the original PR
  - Call counting infos cannot be deleted when the corresponding call counting stubs may still run, because:
    - The remaining call count decremented by the stub is in the call counting info
    - The only way to get a code version / method desc from a stub is to go through the call counting info
  - Got one repro of the assertion failure in https://github.com/dotnet/runtime/issues/22786 and https://github.com/dotnet/runtime/issues/24664 (fixes https://github.com/dotnet/runtime/issues/24664) and it is most likely caused by the same issue, following heap corruption from modifying a deleted call counting info where the memory is reused for an object used by code versioning, messing up some data and making it look like the code version is not active when it actually is according to the dump
  - Fixed with a partial revert of the above commit. Added back the `Complete` stage and then call counting infos are deleted only after it's ensured that call counting stubs won't be used (shortly before deleting them).
- Commit 3
  - Public static functions of `CallCountingManager` that may be called through the debugger may occur before static initialization, added a check for null as suggested in https://github.com/dotnet/runtime/pull/29892

### CODE REVIEW

**Comment by kouvel** [comment]
Got a consistent repro of the crash after a few hours of running a CoreFX test suite, verified no repro after fix after 12+ hours. Got one repro of the assertion failure, currently running again after fix, will continue running overnight.

**Comment by kouvel** [comment]
No assertion failure after 12+ hours after fix. Rebased to fix conflicts.

**Review by noahfalk — APPROVED** [review]
LGTM

**Comment by kouvel** [comment]
Thanks @noahfalk! Rebased to latest to run through the checks again.

**Comment by kouvel** [comment]
Failures are same as https://github.com/dotnet/runtime/issues/32951

**Review by davidwrighton — APPROVED** [review]
:shipit:

**Comment by kouvel** [comment]
Rebased to fix conflict

**Pull request merged**
