### PR TITLE
Only run source-index on main branch.

### PR DESCRIPTION
**Pull request by alexperovich**

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by stephentoub** [comment]
@danmoseley, do we need special sign-off to get this merged into release/6.0 or can we just do it?

**Comment by danmoseley** [comment]
No permission needed since this is necessary infra work. Not sure whether branch is reopened.

**Comment by safern** [comment]
I believe branch opened today, but not sure, @Anipik?

**Comment by Anipik** [comment]
yes we can go ahead and merge it,

**Comment by safern** [comment]
No they are not this file changes the official build yaml only. Might be good after merging just keeping an eye to the official build.

**Pull request merged**
