### PR TITLE
Enable `TYP_STRUCT` `LCL_VAR/LCL_FLD` call args on ARM

### PR DESCRIPTION
**Pull request by SingleAccretion**
Enables the folding for our last target.

As usual, we have [diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1860002&view=ms.vss-build-web.run-extensions-tab), mostly improvements, but there is one kind of regression unique to ARM.

It happens when we forward-substitute a promoted struct local as a non-first parameter. On ARM, we copy promoted struct arguments into outgoing temps, which then means we copy things before it in the parameter list:
```scala
CALL
    ARG_1
    ARG_2<promoted LCL_VAR>

    ==>

CALL
    ASG
       LCL_VAR arg1temp
       ARG_1
    COMMAs<field assignments for ARG_2>
    LCL_VAR arg1temp
    LCL_VAR arg2temp
```
Where without forward subtituion we would have:
```scala
COMMAs<field assignments for ARG_2>

CALL
    ARG_1
    ARG_2
```
The right fix for this is to drop the copying of promoted temps; and I have the changes necessary for that ready (#71780); we can decide if it's important to wait for them, or ok to merge this PR as-is.

Also we have some regressions in test methods with huge structs and on non-ARM platforms from the last commit.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by jakobbotsch** [comment]
Ah, just saw #71780. Let's wait for that one then, those diffs did look a bit scary even if they were in some unrealistic test cases.

**Comment by SingleAccretion** [comment]
> Unexpected?

It's the same issue as in #70861 - 11K struct sources for `PUTARG_SPLIT`s.

**Comment by jakobbotsch** [comment]
> It's the same issue as in https://github.com/dotnet/runtime/pull/70861 - 11K struct sources for PUTARG_SPLITs.

Ok, seems fine then.

**Review by jakobbotsch — APPROVED** [review]

**Pull request merged**
