### PR TITLE
[release/6.0] SafeFileHandle.Unix: don't DeleteOnClose when lock is not successful.

### PR DESCRIPTION
**Pull request by tmds**
# Description

In https://github.com/dotnet/runtime/pull/55153 DeleteOnClose handling moved from FileStream to SafeFileHandle.

This unintentionally caused DeleteOnClose to be applied even when FileShare locking fails. As on Windows, DeleteOnClose should not take effect when sharing prevents the file from being opened.

This also swaps the order of unlink and LOCK_UN in Dispose as it was prior to https://github.com/dotnet/runtime/pull/55153.
Either order should be fine.

# Customer impact

Unintentional deleting of file.

# Testing

Existing and new unit test.

# Risk

Low. Behaves the same as previous versions of .NET.

Fixes https://github.com/dotnet/runtime/issues/59995.

### CODE REVIEW

**Review by adamsitnik — APPROVED** [review]
LGTM, big thanks for the fix @tmds!

**Comment by tmds** [comment]
I made an attempt at formatting the initial comment into the 'backport' format.

@stephentoub will you look into the servicing considerations?

**Comment by danmoseley** [comment]
> This also swaps the order of unlink and LOCK_UN in Dispose as it was prior to #55153.
> Either order should be fine.

What is the motivation for porting this part? Would it be lower risk to just port the fix itself?

**Comment by jeffhandley** [comment]
The `System.Tests.TimeZoneInfoTests.TestWindowsNlsDisplayNames` failure in **runtime (Libraries Test Run release coreclr windows x86 Debug)** is #60119, which was fixed in #60140.

**Comment by danmoseley** [comment]
WASM failures are tracked by https://github.com/dotnet/runtime/issues/51961#issuecomment-938978236
Windows 7 network tests that timed out - I'll open an issue.

@jeffhandley let me know if you'd like me to use my super merging powers

**Comment by danmoseley** [comment]
I'm going to be bold and merge...

**Comment by jeffhandley** [comment]
Thanks for merging, @danmoseley. And thanks for the fix, @tmds!

**Pull request merged**
