### PR TITLE
Remove package references from library tests

### PR DESCRIPTION
**Pull request by ericstj**
These tests should be referencing the product assemblies so that they test latest and not old bits.

We should also port this to 9.0.  Found this when looking at https://github.com/dotnet/runtime/pull/106729.  None of these caused that issue, but the usage was wrong.

We should only be using PackageReferences to other things which build in dotnet/runtime when we need to reference something not built in the same subset. It must also not need to execute during the build.  I wish there was some enforcement for this - right now we just have to try and catch it in code review.

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Review by ViktorHofer — COMMENTED** [review]
Won't the P2Ps to BinaryFormatter resolve the NetCoreAppCurrent assembly (PNSE)? We need the NetCoreAppMinimum one (the functioning one). You could add `SetTargetFramework=$(NetCoreAppMinimum)` to the P2Ps to solve that.

**Comment by ericstj** [comment]
> Won't the P2Ps to BinaryFormatter resolve the NetCoreAppCurrent assembly (PNSE)? We need the NetCoreAppMinimum one (the functioning one). You could add `SetTargetFramework=$(NetCoreAppMinimum)` to the P2Ps to solve that.

I had suspected to see failures here but didn't. I'll take a look - also see if I can add assertions to force a failure if it breaks.

**Review by adamsitnik — COMMENTED** [review]
> Won't the P2Ps to BinaryFormatter resolve the NetCoreAppCurrent assembly (PNSE)? We need the NetCoreAppMinimum one (the functioning one). You could add `SetTargetFramework=$(NetCoreAppMinimum)` to the P2Ps to solve that.

@ViktorHofer Is correct. The tfm trick can be found here: https://github.com/dotnet/runtime/blob/779baa695d614e45f013b0ebaefc1d3889516800/src/libraries/System.Runtime.Serialization.Formatters/src/System.Runtime.Serialization.Formatters.csproj#L15

> I had suspected to see failures here but didn't.

All BF tests are marked as conditional. The assembly version is used to determine whether they can be executed:

https://github.com/dotnet/runtime/blob/779baa695d614e45f013b0ebaefc1d3889516800/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L739-L752

 Personally I was using the number of skipped tests as an indicator whether they are actually being run.

**Comment by ericstj** [comment]
@adamsitnik would it be OK if I removed the use of `IsBinaryFormatterSupported` in every project where we specifically want to test the behavior with a functioning BinaryFormatter?  That will make sure this doesn't regress in the future.

**Comment by ericstj** [comment]
> @adamsitnik would it be OK if I removed the use of `IsBinaryFormatterSupported` in every project where we specifically want to test the behavior with a functioning BinaryFormatter? That will make sure this doesn't regress in the future.

I gave this a try, but then realized that property is doing double duty.  It's also covering cases where the platform doesn't support it, and it predates the removal:
https://github.com/dotnet/runtime/blob/d40f32d2dc635e4b4c9d27dbe2673e185e6aa7ea/src/libraries/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs#L307
https://github.com/dotnet/runtime/blob/d40f32d2dc635e4b4c9d27dbe2673e185e6aa7ea/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.cs#L121

So I'll not make this change now, but I do think it would good to separate that state to avoid accidental regression.  Make it clear in the test source when you expect to have an actual implementation vs not.

**Review by ViktorHofer — APPROVED** [review]

**Comment by adamsitnik** [comment]
> I do think it would good to separate that state to avoid accidental regression. 

I agree. I have an idea how it should look like with your changes, let me take a quick stab at it.

**Comment by adamsitnik** [comment]
https://github.com/dotnet/runtime/pull/106858 I have tested it locally for Windows and it works as expected. I don't have more time today because I've just logged it to take a day off, will get back to it on Monday (if further changes are required).

**Pull request merged**
