### PR TITLE
[MAUI][Blazor][PERF] Add IPA file usage for iOS/MacCatalyst Maui Blaz…

### PR DESCRIPTION
**Pull request by TanayParikh**
…or SOD

Merges into https://github.com/dotnet/runtime/pull/68241 (or `main` if https://github.com/dotnet/runtime/pull/68241 is merged).

Requires https://github.com/dotnet/performance/pull/2387. Would like to clarify if we should be using a `mauimaccatalyst` scenario for MacCatalyst or using the ios scenario is sufficient? [Details](https://github.com/dotnet/performance/pull/2387#issuecomment-1104482003).

For: https://github.com/dotnet/maui/issues/2531

### CODE REVIEW

**Comment by LoopedBard3** [comment]
Just using the iOS scenario should be sufficient. The MacCatalyst is basically a remnant from when we were setting up the iOS flow but running into iOS specific issues.

**Comment by LoopedBard3** [comment]
The specific pipeline we want to test this in is dotnet-runtime-perf but idk if that is one of the available options.

**Comment by TanayParikh** [comment]
I believe it's just skipping a bunch of checks as the target branch is https://github.com/dotnet/runtime/pull/68241 instead of main. Let's get https://github.com/dotnet/runtime/pull/68241 merged first and we can take care of this thereafter.

**Comment by TanayParikh** [comment]
> this in is dotnet-runtime-perf

Can you please point me to that pipeline, I'm not seeing it in azdo

**Comment by LoopedBard3** [comment]
I sent you a DM

**Comment by DrewScoggins** [comment]
Hi @TanayParikh this PR was actually made against one of your branches and not against main. Can you make another PR against the main branch so we can merge it and start to actually get results?

**Comment by TanayParikh** [comment]
> Can you make another PR against the main branch so we can merge it and start to actually get results?

The iOS & Mac Catalyst bits are being handled via https://github.com/dotnet/runtime/pull/68685. That PR is currently blocked on some infra issues.

**Pull request merged**
