### PR TITLE
[tests] Update eventsvalidation tests to use intree Microsoft.Diagnostics.NETCore.Client

### LINKED ISSUE #66099: Test build failure: The type 'EventPipeProvider' is defined in an assembly that is not referenced
In a build of the Pri-1 tests:

https://dev.azure.com/dnceng/public/_build/results?buildId=1640719&view=logs&j=db768a9e-3325-5ce3-2d52-896c40bee68a&t=59112ad9-fe58-56ee-6943-84df6f0e3f8e

```
    eventsourceerror -> /__w/1/s/artifacts/tests/coreclr/AnyOS.x64.Checked/tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.dll
/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1.cs(24,20): error CS0012: The type 'EventPipeProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Diagnostics.NETCore.Client, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1.csproj] [/__w/1/s/src/tests/build.proj]
##[error]src/tests/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1.cs(24,20): error CS0012: The type 'EventPipeProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Diagnostics.NETCore.Client, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1.csproj]
/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCEvents.cs(25,20): error CS0012: The type 'EventPipeProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Diagnostics.NETCore.Client, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCEvents.csproj] [/__w/1/s/src/tests/build.proj]
##[error]src/tests/tracing/eventpipe/eventsvalidation/GCEvents.cs(25,20): error CS0012: The type 'EventPipeProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Diagnostics.NETCore.Client, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCEvents.csproj]
/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.cs(25,20): error CS0012: The type 'EventPipeProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Diagnostics.NETCore.Client, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.csproj] [/__w/1/s/src/tests/build.proj]
##[error]src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.cs(25,20): error CS0012: The type 'EventPipeProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Diagnostics.NETCore.Client, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.csproj]
```

A rolling outerloop job will presumably hit this soon:

https://dev.azure.com/dnceng/public/_build/results?buildId=1640881&view=logs&j=db768a9e-3325-5ce3-2d52-896c40bee68a

It seems likely this is related to https://github.com/dotnet/runtime/pull/64358

@mdh1418 @hoyosjs

### PR DESCRIPTION
**Pull request by mdh1418**
Fixes https://github.com/dotnet/runtime/issues/66099

### CODE REVIEW

**Comment by mdh1418** [comment]
@BruceForstall How can I run the `runtime-coreclr jitstress` pipeline?

**Review by hoyosjs — APPROVED** [review]

**Comment by BruceForstall** [comment]
Just triggering `runtime-coreclr outerloop` would have been sufficient.

Once the `CoreCLR Common Pri1 Test Build AnyOS AnyCPU checked` job in the jitstress pipeline (https://dev.azure.com/dnceng/public/_build/results?buildId=1641394&view=results) succeeds, you can consider this "good" -- no need to wait for all test runs to complete.

**Comment by BruceForstall** [comment]
@mdh1418 @hoyosjs The build failure is not fixed:

```
    gh53564 -> /__w/1/s/artifacts/tests/coreclr/AnyOS.x64.Checked/tracing/eventcounter/gh53564/gh53564.dll
/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1.cs(20,74): error CS1503: Argument 2: cannot convert from 'int' to 'System.Diagnostics.Tracing.EventLevel' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1.csproj] [/__w/1/s/src/tests/build.proj]
##[error]src/tests/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1.cs(20,74): error CS1503: Argument 2: cannot convert from 'int' to 'System.Diagnostics.Tracing.EventLevel' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1.csproj]
/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1.cs(20,97): error CS1503: Argument 3: cannot convert from 'System.Diagnostics.Tracing.EventLevel' to 'long' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1.csproj] [/__w/1/s/src/tests/build.proj]
##[error]src/tests/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1.cs(20,97): error CS1503: Argument 3: cannot convert from 'System.Diagnostics.Tracing.EventLevel' to 'long' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/ExceptionThrown_V1.csproj]
    regression-25709 -> /__w/1/s/artifacts/tests/coreclr/AnyOS.x64.Checked/tracing/eventcounter/regression-25709/regression-25709.dll
    EventListenerThreadPool -> /__w/1/s/artifacts/tests/coreclr/AnyOS.x64.Checked/tracing/eventlistener/EventListenerThreadPool/EventListenerThreadPool.dll
/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCEvents.cs(19,21): error CS7036: There is no argument given that corresponds to the required formal parameter 'eventLevel' of 'EventPipeProvider.EventPipeProvider(string, EventLevel, long, IDictionary<string, string>)' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCEvents.csproj] [/__w/1/s/src/tests/build.proj]
##[error]src/tests/tracing/eventpipe/eventsvalidation/GCEvents.cs(19,21): error CS7036: There is no argument given that corresponds to the required formal parameter 'eventLevel' of 'EventPipeProvider.EventPipeProvider(string, EventLevel, long, IDictionary<string, string>)' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCEvents.csproj]
/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCEvents.cs(21,74): error CS1503: Argument 2: cannot convert from 'int' to 'System.Diagnostics.Tracing.EventLevel' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCEvents.csproj] [/__w/1/s/src/tests/build.proj]
##[error]src/tests/tracing/eventpipe/eventsvalidation/GCEvents.cs(21,74): error CS1503: Argument 2: cannot convert from 'int' to 'System.Diagnostics.Tracing.EventLevel' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCEvents.csproj]
/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCEvents.cs(21,79): error CS1503: Argument 3: cannot convert from 'System.Diagnostics.Tracing.EventLevel' to 'long' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCEvents.csproj] [/__w/1/s/src/tests/build.proj]
##[error]src/tests/tracing/eventpipe/eventsvalidation/GCEvents.cs(21,79): error CS1503: Argument 3: cannot convert from 'System.Diagnostics.Tracing.EventLevel' to 'long' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCEvents.csproj]
    eventlistener -> /__w/1/s/artifacts/tests/coreclr/AnyOS.x64.Checked/tracing/eventlistener/eventlistener/eventlistener.dll
/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.cs(19,21): error CS7036: There is no argument given that corresponds to the required formal parameter 'eventLevel' of 'EventPipeProvider.EventPipeProvider(string, EventLevel, long, IDictionary<string, string>)' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.csproj] [/__w/1/s/src/tests/build.proj]
##[error]src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.cs(19,21): error CS7036: There is no argument given that corresponds to the required formal parameter 'eventLevel' of 'EventPipeProvider.EventPipeProvider(string, EventLevel, long, IDictionary<string, string>)' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.csproj]
/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.cs(21,74): error CS1503: Argument 2: cannot convert from 'int' to 'System.Diagnostics.Tracing.EventLevel' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.csproj] [/__w/1/s/src/tests/build.proj]
##[error]src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.cs(21,74): error CS1503: Argument 2: cannot convert from 'int' to 'System.Diagnostics.Tracing.EventLevel' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.csproj]
/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.cs(21,79): error CS1503: Argument 3: cannot convert from 'System.Diagnostics.Tracing.EventLevel' to 'long' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.csproj] [/__w/1/s/src/tests/build.proj]
##[error]src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.cs(21,79): error CS1503: Argument 3: cannot convert from 'System.Diagnostics.Tracing.EventLevel' to 'long' [/__w/1/s/src/tests/tracing/eventpipe/eventsvalidation/GCFinalizers.csproj]
    regression-46938 -> /__w/1/s/artifacts/tests/coreclr/AnyOS.x64.Checked/tracing/eventcounter/regression-46938/regression-46938.dll
```

**Comment by mdh1418** [comment]
I went too quickly, I missed that the EventPipeProvider does not have a default EventLevel, and that the keyword position is changed to be 3rd instead of second.

**Comment by mdh1418** [comment]
@BruceForstall https://dev.azure.com/dnceng/public/_build/results?buildId=1641823&view=logs&j=db768a9e-3325-5ce3-2d52-896c40bee68a is green now. Is this still good to merge despite the other seemingly unrelated failures?

**Comment by hoyosjs** [comment]
Merged to unblock JIT workflows. The errors were due to AzDO artifact throttling unrelated to this PR.

**Comment by BruceForstall** [comment]
As long as the test build finished (it did), that's good enough for now.

Of course, if these changes also cause test failures, you'll see those soon...

**Pull request merged**
