### PR TITLE
Enable crossgen SPMI collection for libraries

### PR DESCRIPTION
**Pull request by kunalspathak**
- Perform `crossgen` collection for libraries
- Improve message that prints files getting copied
- Exclude `CORE_ROOT` folder from copying for "tests" collection.

Sample run: https://dev.azure.com/dnceng/internal/_build/results?buildId=921326&view=results

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]
Looks great!

**Comment by kunalspathak** [comment]
@BruceForstall  - Thank you. I forgot to ask, how will the crossgen collection used? By triggering `superpmi.py replay -filter crossgen`?

**Comment by BruceForstall** [comment]
Yes, if you don't specify `-filter`, all collections get used for replay or asmdiffs. Or, you could `-filter libraries` or `-filter crossgen` as desired. (I did test this on the Windows x64 crossgen collection)

**Pull request merged**
