### PR TITLE
Typo in DeniedValuesAttribute

### PR DESCRIPTION
**Pull request by lordfanger**
https://github.com/dotnet/runtime/pull/82311#discussion_r1117412401

### CODE REVIEW

**Comment by lordfanger** [comment]
@dotnet-policy-service agree

**Comment by lordfanger** [comment]
@eiriktsarpalis correct?

**Comment by eiriktsarpalis** [comment]
> @eiriktsarpalis correct?

Better, but perhaps calling it `deniedValue` better reflects the name of the type?

**Comment by lordfanger** [comment]
What about `denied`? It is from `Values`. What else it will be if not Value? :-D

**Comment by eiriktsarpalis** [comment]
Sure denied sounds good

**Review by stephentoub — APPROVED** [review]

**Comment by jeffhandley** [comment]
@lordfanger Thanks for posting the feedback on the PR and for contributing the improvement!

**Pull request merged**
