### PR TITLE
JIT: Unroll more Equals/StartsWith/EndsWith on arm64

### PR DESCRIPTION
**Pull request by EgorBo**
Seems like it's quite beneficial even on large sizes, at least on arm64:

```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Bench
{
    string s = "https://pkgs.dev.azure.com/dnceng/public/packaging/dotnet10/";

    [Benchmark]
    public bool Bestcase() => 
        s.StartsWith("https://pkgs.dev.azure.com/dnceng/public/pack", StringComparison.Ordinal);
    
    [Benchmark]
    public bool Bestcase_IgnoreCase() => 
        s.StartsWith("https://pkgs.dev.azure.com/dnceng/public/pack", StringComparison.OrdinalIgnoreCase);

    // Worst case: differs at 1st char:

    [Benchmark]
    public bool Worstcase() => 
        s.StartsWith("Xttps://pkgs.dev.azure.com/dnceng/public/pack", StringComparison.Ordinal);
    
    [Benchmark]
    public bool Worstcase_IgnoreCase() => 
        s.StartsWith("Xttps://pkgs.dev.azure.com/dnceng/public/pack", StringComparison.OrdinalIgnoreCase);
}
```

```
BenchmarkDotNet v0.14.0, Ubuntu 24.04 LTS (Noble Numbat)
Arm64
  Job-NEWBNL : .NET 10.0.0 (42.42.42.42424), Arm64 RyuJIT AdvSIMD
  Job-LSVZLO : .NET 10.0.0 (42.42.42.42424), Arm64 RyuJIT AdvSIMD
EnvironmentVariables=DOTNET_JitDisasm=Bestcase_IgnoreCase
```
| Method               | Toolchain               | Mean      | Error     | Ratio |
|--------------------- |------------------------ |----------:|----------:|------:|
| Bestcase             | Main | 4.1458 ns | 0.0071 ns |  1.00 |
| Bestcase             | PR | 0.6151 ns | 0.0007 ns |  0.15 |
|                      |                         |           |           |       |
| Bestcase_IgnoreCase  | Main | 5.9848 ns | 0.1685 ns |  1.00 |
| Bestcase_IgnoreCase  | PR | 1.5489 ns | 0.0044 ns |  0.26 |
|                      |                         |           |           |       |
| Worstcase            | Main | 1.7136 ns | 0.0003 ns |  1.00 |
| Worstcase            | PR | 0.6572 ns | 0.0013 ns |  0.38 |
|                      |                         |           |           |       |
| Worstcase_IgnoreCase | Main | 2.5230 ns | 0.0015 ns |  1.00 |
| Worstcase_IgnoreCase | PR | 1.2213 ns | 0.0016 ns |  0.48 |

### CODE REVIEW

**Comment by EgorBo** [comment]
@EgorBot -arm64 --envvars DOTNET_JitDisasm:Bestcase
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Bench
{
    string s = "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10/";

    //[Benchmark]
    public bool Bestcase() => 
        s.StartsWith("https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10", StringComparison.Ordinal);
    
    [Benchmark]
    public bool Bestcase_IgnoreCase() => 
        s.StartsWith("https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10", StringComparison.OrdinalIgnoreCase);

    // Worst case: differs at 1st char:

    //[Benchmark]
    public bool Worstcase() => 
        s.StartsWith("xttps://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10", StringComparison.Ordinal);
    
    //[Benchmark]
    public bool Worstcase_IgnoreCase() => 
        s.StartsWith("xttps://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10", StringComparison.OrdinalIgnoreCase);
}
```

**Comment by EgorBo** [comment]
@EgorBot -arm64 --envvars DOTNET_JitDisasm:Bestcase
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Bench
{
    string s = "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10/";

    [Benchmark]
    public bool Bestcase() => 
        s.StartsWith("https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10", StringComparison.Ordinal);
    
    [Benchmark]
    public bool Bestcase_IgnoreCase() => 
        s.StartsWith("https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10", StringComparison.OrdinalIgnoreCase);

    // Worst case: differs at 1st char:

    [Benchmark]
    public bool Worstcase() => 
        s.StartsWith("xttps://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10", StringComparison.Ordinal);
    
    [Benchmark]
    public bool Worstcase_IgnoreCase() => 
        s.StartsWith("xttps://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10", StringComparison.OrdinalIgnoreCase);
}
```

**Comment by EgorBo** [comment]
@MihuBot

**Comment by EgorBo** [comment]
@EgorBot -arm64 -amd --envvars DOTNET_JitDisasm:Bestcase
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Bench
{
    string s = "https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10/";

    [Benchmark]
    public bool Bestcase() => 
        s.StartsWith("https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10", StringComparison.Ordinal);
    
    [Benchmark]
    public bool Bestcase_IgnoreCase() => 
        s.StartsWith("https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10", StringComparison.OrdinalIgnoreCase);

    // Worst case: differs at 1st char:

    [Benchmark]
    public bool Worstcase() => 
        s.StartsWith("xttps://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10", StringComparison.Ordinal);
    
    [Benchmark]
    public bool Worstcase_IgnoreCase() => 
        s.StartsWith("xttps://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet10", StringComparison.OrdinalIgnoreCase);
}
```

**Comment by EgorBo** [comment]
@EgorBot -arm64 --envvars DOTNET_JitDisasm:Bestcase_IgnoreCase
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Bench
{
    string s = "https://pkgs.dev.azure.com/dnceng/public/packaging/dotnet10/";

    [Benchmark]
    public bool Bestcase() => 
        s.StartsWith("https://pkgs.dev.azure.com/dnceng/public/pack", StringComparison.Ordinal);
    
    [Benchmark]
    public bool Bestcase_IgnoreCase() => 
        s.StartsWith("https://pkgs.dev.azure.com/dnceng/public/pack", StringComparison.OrdinalIgnoreCase);

    // Worst case: differs at 1st char:

    [Benchmark]
    public bool Worstcase() => 
        s.StartsWith("Xttps://pkgs.dev.azure.com/dnceng/public/pack", StringComparison.Ordinal);
    
    [Benchmark]
    public bool Worstcase_IgnoreCase() => 
        s.StartsWith("Xttps://pkgs.dev.azure.com/dnceng/public/pack", StringComparison.OrdinalIgnoreCase);
}
```

**Comment by EgorBo** [comment]
@MihuBot -arm -dependsOn 108838

**Comment by EgorBo** [comment]
PTAL @jakobbotsch @dotnet/jit-contrib [this improves](https://github.com/EgorBot/runtime-utils/issues/128#issuecomment-2424302957) perf on arm64 (even in the worst case when the first char is different). Seems like makes no sense on x64 judging by benchmarks.

**Comment by tannergooding** [comment]
> Seems like makes no sense on x64 judging by benchmarks.

Do you have a link to the perf numbers on x64?

I would expect this to be similar perf on most x64, but likely better on CPUs like e-cores or other scenarios where call overhead is greater

**Comment by EgorBo** [comment]
@EgorBot -amd -intel --envvars DOTNET_JitDisasm:Bestcase_IgnoreCase
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

public class Bench
{
    string s = "https://pkgs.dev.azure.com/dnceng/public/packaging/dotnet10/";

    [Benchmark]
    public bool Bestcase() => 
        s.StartsWith("https://pkgs.dev.azure.com/dnceng/public/pack", StringComparison.Ordinal);
    
    [Benchmark]
    public bool Bestcase_IgnoreCase() => 
        s.StartsWith("https://pkgs.dev.azure.com/dnceng/public/pack", StringComparison.OrdinalIgnoreCase);

    // Worst case: differs at 1st char:

    [Benchmark]
    public bool Worstcase() => 
        s.StartsWith("Xttps://pkgs.dev.azure.com/dnceng/public/pack", StringComparison.Ordinal);
    
    [Benchmark]
    public bool Worstcase_IgnoreCase() => 
        s.StartsWith("Xttps://pkgs.dev.azure.com/dnceng/public/pack", StringComparison.OrdinalIgnoreCase);
}
```

**Comment by EgorBo** [comment]
@tannergooding you can find x64 numbers here https://github.com/EgorBot/runtime-utils/issues/162, Basically, almost no wins and clear regressions unlike arm64

**Review by jakobbotsch — APPROVED** [review]

**Comment by tannergooding** [comment]
> you can find x64 numbers here https://github.com/EgorBot/runtime-utils/issues/162, Basically, almost no wins and clear regressions unlike arm64

Thanks! That roughly fits my expectations for that hardware. I don't think we have any e-cores to see if there is a contrast for those devices though, unfortunately.

I have no concerns with it being merged, just wanted to see some of the numbers since it was called out

**Review by tannergooding — APPROVED** [review]

**Pull request merged**
