### PR TITLE
Enable Matrix3x2Tests.cs

### PR DESCRIPTION
**Pull request by briansull**
This test is passing in my enlistment

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Review by tannergooding — APPROVED** [review]

**Comment by briansull** [comment]
Fixes #36587

**Comment by stephentoub** [comment]
> Fixes #36587

There are other tests in this file disabled against that issue.

**Comment by briansull** [comment]
All of the tests that I enabled with this change to  src/libraries/System.Numerics.Vectors/tests/Matrix3x2Tests.cs
are now passing:

https://dev.azure.com/dnceng/public/_test/analytics?definitionId=833&contextType=build

**Comment by tannergooding** [comment]
Did this get closed rather than merged?

**Comment by briansull** [comment]
Merging instead of closing

**Pull request merged**
