### PR TITLE
Make optVNAssertionPropCurStmtVisitor post-order

### PR DESCRIPTION
**Pull request by EgorBo**
just to see what [spmi](https://dev.azure.com/dnceng-public/public/_build/results?buildId=89456&view=results) thinks about it...

### CODE REVIEW

**Comment by EgorBo** [comment]
@jakobbotsch @SingleAccretion PTAL

**Comment by SingleAccretion** [comment]
If memory is not failing me, this should also fix #57033.

**Review by SingleAccretion — APPROVED** [review]
LGTM!

It is quite curious we see a TP increase. Would be interesting (but not necessarily worthwhile) to find out why that is.

**Comment by EgorBo** [comment]
> If memory is not failing me, this should also fix #57033.

Yeah, it folds the whole thing to `return 4` 🙂 awesome, thanks!

**Review by jakobbotsch — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Seems like there's some more low hanging fruit here TP wise by using a `GenTreeVisitor` (not necessarily for this PR)

**Comment by EgorBo** [comment]
SPMI failure:
```
Failed to download unix-arm-3/1/superpmi_Linux_arm_3.log blob from results container: 
```

Presumably collection failed on that one yesterday and we need to kick it off again

**Pull request merged**
