### PR TITLE
Dev infra master merge1

### PR DESCRIPTION
**Pull request by jashook**

### CODE REVIEW

**Review by trylek — APPROVED** [review]
Looks good, thanks for pulling this off Jarret!

**Review by sdmaclea — APPROVED** [review]

**Comment by jaredpar** [comment]
Have we run an official build on this branch?

**Review by safern — APPROVED** [review]

**Comment by safern** [comment]
cc: @naricc with this we can remove the building coreclr tests for mono step.

**Comment by jashook** [comment]
>Have we run an official build on this branch?

Yes it took a little to get setup but we are mirroring dev/infrastructure now and we had a clean official build (waiting for post build steps atm). Note this was without the merge conflicts.

https://dev.azure.com/dnceng/internal/_build/results?buildId=667400&view=results

**Comment by jashook** [comment]
Official build is clean

**Comment by jashook** [comment]
Pri1 test failure is also in master.

**Pull request merged**
