### PR TITLE
JIT: do early block merging in more cases

### LINKED ISSUE #86125: OSR tests failing in jit-experimental pipeline
https://dev.azure.com/dnceng-public/public/_build/results?buildId=269074&view=ms.vss-test-web.build-test-results-tab

```
set DOTNET_TieredCompilation=1
set DOTNET_TC_OnStackReplacement=1
set DOTNET_TC_QuickJitForLoops=1
set DOTNET_TC_OnStackReplacement_InitialCounter=1
set DOTNET_OSR_HitLimit=2
set DOTNET_JitRandomOnStackReplacement=1

  Starting:    JIT.Generics.XUnitWrapper (parallel test collections = on, max threads = 4)
    JIT\Generics\ConstrainedCall\vt4_il_r\vt4_il_r.cmd [FAIL]
      
      Assert failure(PID 3644 [0x00000e3c], Thread: 3716 [0x0e84]): Assertion failed 'compMinOptsIsSet' in 'MyCounter[MyInt]:Val():int:this' during 'Pre-import' (IL size 21; hash 0x4d594f91; Optimization-Level-Not-Yet-Set)
      
          File: D:\a\_work\1\s\src\coreclr\jit\compiler.h Line: 9272
          Image: C:\h\w\9C710833\p\corerun.exe
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
OSR and PGO both rely on the fact that the early flowgraph the JIT builds is the same flowgraph as the one seen in a previous JIT complation of that method, since there is metadata (patchpoint offset, pgo schema) that refers to the flowgraph. Previous work here (#85860) didn't ensure this for enough cases.

In particular if Tier0 does not do early block merging, but OSR does, it's possible for the OSR entry point to fall within a merged block range, which the JIT is not prepared to handle. This lead to the asserts seen in #86125.

The fix is to enable early block merging unless we're truly in a minopts or debug codegen mode (previous to this Tier0 would not merge unless it also was instrumenting; now it will always merge).

An alternative fix would be to find the block containing the OSR entry IL offset, scan its statements, and split the block at the right spot, but that seemed more involved.

Fixes #86125.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
Will fix formatting after the experimental leg completes.

**Review by EgorBo — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
Experimental had what looks like two unrelated failures in jit-stress-splitting. Will ignore for now.
```
Process terminated. Parallel crash in main thread
at System.Environment.FailFast(System.String)
at ParallelCrash.Main(System.String[])
[createdump] The app model does not support crash report generation
[createdump] Failure took 0ms
waitpid() returned successfully (wstatus 0000ff00) WEXITSTATUS ff WTERMSIG 0


cmdLine:/private/tmp/helix/working/A9500944/w/A32E08EB/e/baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 5/12/2023 2:05:16 PM, end: 5/12/2023 2:15:16 PM)
``

**Comment by AndyAyersMS** [comment]
Had to revamp this a bit, turns out `BBOPT` is set even for debuggable and EnC cases, and so the first change I made here (#85860) broke some debugger tests.

This will cause some large negative diffs in minotps for clr_tests that undoes the large positive diff from #85860.

**Comment by AndyAyersMS** [comment]
Replay failures are related to collections issues.

**Pull request merged**
