### PR TITLE
Fix VSD stub null reference handling on amd64

### LINKED ISSUE #9027: Jit always null checks x64 VSD calls, even if it's proven the object can't be null
`Lowering::LowerVirtualStubCall` always null checks on x64, unless the call is via tail call helper, even if upstream phases have proven that the object can't be null. 

See discussion in dotnet/runtime#8953, where Jan mentions fixing the runtime issue that makes this necessary. However we should also consider fixing this in the jit, so the null check can be bypassed when it is safe to do so.

category:cq
theme:basic-cq
skill-level:intermediate
cost:medium

### LINKED ISSUE #35000: System.AccessViolationException with Delegate.CreateDelegate
```C#

    class Program
    {
        static void Main(string[] args)
        {
            PropertyInfo property = typeof(TestData).GetProperty(nameof(TestData.InputGuid),
                BindingFlags.Instance | BindingFlags.Public);

            Func<object, object> func = GetFunc(property);

            TestData data = new TestData();

            data.InputGuid = Guid.NewGuid();

            object value1 = func(data);
            try
            {
                object value2 = func(null);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }

            object value3 = func(data);
            try
            {
                object value2 = func(null);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }

            Console.ReadLine();
        }


        public static Func<object, object> GetFunc(PropertyInfo propertyInfo)
        {
            var method = typeof(Program).GetMethod(nameof(CreateFunc));

            return (Func<object, object>) method
                .MakeGenericMethod(propertyInfo.DeclaringType, propertyInfo.PropertyType)
                .Invoke(null, new object[] {propertyInfo.GetMethod});
        }

        public static Func<object, object> CreateFunc<TTarget, TValue>(MethodInfo methodInfo)
        {

            var func = (Func<TTarget, TValue>) Delegate.CreateDelegate(typeof(Func<TTarget, TValue>), null, methodInfo);
            return (object o) => func((TTarget) o);
        }
    }
    public class TestData
    { 
        public virtual Guid InputGuid { get; set; }
    }
```
image

 Demo
[ConsoleApp.zip](https://github.com/dotnet/runtime/files/4481578/ConsoleApp.zip)

### PR DESCRIPTION
**Pull request by janvorli**
When the VSD resolve or dispatch stub gets a null “this” reference on amd64, the resulting access violation is not converted to NullReferenceException and so we fail fast and tear down the process with AccessViolationException. The reason is that the amd64 version of the AdjustContextForVirtualStub always returns FALSE and doesn't do anything instead of manually unwinding to the managed caller of the stub.

This change fixes it by implementing the AdjustContextForVirtualStub the same way as on other architectures. While fixing it, I’ve also found that for arm64, we were not calling AdjustContextForVirtualStub in some code paths where we call it for x86 and arm. This code was under the VSD_STUB_CAN_THROW_AV define, which was defined only for x86 and arm for some reason.

In addition to the fix, I've noticed that at several places we call IsIPinVirtualStub and call the AdjustContextForVirtualStub only if that returns true. This is not necessary, as the AdjustContextForVirtualStub doesn't do anything and just returns false when the instruction pointer is not in VSD stub and we end up looking up the stub twice unnecessarily. So I've also fixed that.

This change also adds a regression test for the underlying issue.

Close #35000
Close #9027

### CODE REVIEW

**Comment by jkotas** [comment]
`exceptionhandling.cpp:5292:94: error: expected ';' after expression`

**Comment by jkotas** [comment]
Could you please also delete the code that emits the explicit null check for VSD on x64 in `Lowering::LowerVirtualStubCall` ? It is no longer necessary - it will fix #9027.

**Comment by janvorli** [comment]
> Could you please also delete the code that emits the explicit null check for VSD on x64 in `Lowering::LowerVirtualStubCall` ?

Done in the last commit.

**Review by jkotas — APPROVED** [review]

**Review by AndyAyersMS — APPROVED** [review]
Would be interesting to run jit diffs on this. I can do it for you if you like.

**Comment by janvorli** [comment]
> I can do it for you if you like.

That would be nice!

**Comment by AndyAyersMS** [comment]
Nice improvement in code size:
```
PMI CodeSize Diffs for System.Private.CoreLib.dll, framework assemblies for x64 default jit
Summary of Code Size diffs:
(Lower is better)
Total bytes of diff: -125447 (-0.26% of base)
    diff is an improvement.
Top file improvements (bytes):
      -15739 : System.Linq.dasm (-1.55% of base)
      -12307 : Microsoft.Diagnostics.Tracing.TraceEvent.dasm (-0.40% of base)
       -9527 : System.Private.CoreLib.dasm (-0.20% of base)
       -8473 : Microsoft.CodeAnalysis.dasm (-0.48% of base)
       -6527 : System.Private.Xml.dasm (-0.18% of base)
       -4398 : Newtonsoft.Json.dasm (-0.50% of base)
       -3848 : System.Collections.Immutable.dasm (-0.35% of base)
       -3129 : Microsoft.CodeAnalysis.CSharp.dasm (-0.07% of base)
       -2898 : System.Linq.Expressions.dasm (-0.37% of base)
       -2877 : System.Collections.dasm (-0.51% of base)
       -2776 : System.Linq.Parallel.dasm (-0.16% of base)
       -2763 : Microsoft.CodeAnalysis.VisualBasic.dasm (-0.05% of base)
       -2718 : System.Linq.Queryable.dasm (-0.96% of base)
       -2656 : System.ComponentModel.Composition.dasm (-0.79% of base)
       -2615 : System.Data.Common.dasm (-0.17% of base)
       -2459 : System.Threading.Tasks.Dataflow.dasm (-0.29% of base)
       -2242 : System.Configuration.ConfigurationManager.dasm (-0.64% of base)
       -2101 : xunit.execution.dotnet.dasm (-0.89% of base)
       -2070 : System.Management.dasm (-0.53% of base)
       -1852 : xunit.runner.utility.netcoreapp10.dasm (-0.97% of base)
151 total files with Code Size differences (151 improved, 0 regressed), 115 unchanged.
Top method improvements (bytes):
        -696 (-2.86% of base) : System.Linq.dasm - Enumerable:Max(IEnumerable`1,Func`2):Nullable`1 (35 methods)
        -642 (-2.82% of base) : System.Linq.dasm - Enumerable:Average(IEnumerable`1,Func`2):Nullable`1 (35 methods)
        -604 (-3.13% of base) : System.Linq.dasm - Lookup`2:Create(IEnumerable`1,Func`2,Func`2,IEqualityComparer`1):Lookup`2 (49 methods)
        -536 (-2.60% of base) : System.Linq.dasm - Enumerable:Min(IEnumerable`1,Func`2):Nullable`1 (35 methods)
        -392 (-2.94% of base) : System.Linq.dasm - Enumerable:Sum(IEnumerable`1,Func`2):Nullable`1 (35 methods)
        -336 (-3.42% of base) : System.Linq.dasm - Enumerable:Average(IEnumerable`1,Func`2):double (21 methods)
        -266 (-3.33% of base) : System.Linq.dasm - Enumerable:SequenceEqual(IEnumerable`1,IEnumerable`1,IEqualityComparer`1):bool (7 methods)
        -252 (-4.62% of base) : Microsoft.CodeAnalysis.dasm - MetadataVisitor:Visit(IEnumerable`1):this (21 methods)
        -238 (-2.52% of base) : System.Threading.Tasks.Dataflow.dasm - TransformManyBlock`2:StoreOutputItemsNonReorderedWithIteration(IEnumerable`1):this (7 methods)
        -228 (-3.66% of base) : System.Linq.dasm - Enumerable:Max(IEnumerable`1,Func`2):long (14 methods)
        -228 (-3.66% of base) : System.Linq.dasm - Enumerable:Min(IEnumerable`1,Func`2):long (14 methods)
        -216 (-3.12% of base) : System.ComponentModel.Composition.dasm - ExportProvider:GetExportsCore(String):IEnumerable`1:this (14 methods)
        -212 (-2.28% of base) : System.Private.CoreLib.dasm - TlsOverPerCoreLockedStacksArrayPool`1:Trim():bool:this (9 methods)
        -210 (-3.53% of base) : System.Private.CoreLib.dasm - Task:WhenAll(IEnumerable`1):Task`1 (7 methods)
        -206 (-2.78% of base) : System.ComponentModel.Composition.dasm - CompositionContainer:ReleaseExports(IEnumerable`1):this (15 methods)
        -196 (-4.01% of base) : Microsoft.CodeAnalysis.dasm - DeltaMetadataWriter:AddRange(IReadOnlyDictionary`2,IReadOnlyDictionary`2,bool):IReadOnlyDictionary`2 (7 methods)
        -184 (-3.87% of base) : System.Collections.Immutable.dasm - Builder:RemoveRange(IEnumerable`1):this (14 methods)
        -180 (-2.27% of base) : System.Collections.Immutable.dasm - Builder:AddRange(IEnumerable`1):this (28 methods)
        -180 (-1.63% of base) : System.ObjectModel.dasm - ReadOnlyDictionary`2:System.Collections.ICollection.CopyTo(Array,int):this (7 methods)
        -180 (-2.35% of base) : System.Private.CoreLib.dasm - ReadOnlyDictionary`2:System.Collections.ICollection.CopyTo(Array,int):this (7 methods)
Top method improvements (percentages):
          -2 (-7.14% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - VisualBasicExtensions:IsShared(ISymbol):bool
          -2 (-7.14% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - VisualBasicExtensions:IsOverrides(ISymbol):bool
          -2 (-7.14% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - VisualBasicExtensions:IsOverridable(ISymbol):bool
          -2 (-7.14% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - VisualBasicExtensions:IsNotOverridable(ISymbol):bool
          -2 (-7.14% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - VisualBasicExtensions:IsMustOverride(ISymbol):bool
          -2 (-7.14% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - VisualBasicExtensions:IsMe(IParameterSymbol):bool
          -2 (-7.14% of base) : Newtonsoft.Json.dasm - JToken:System.Collections.IEnumerable.GetEnumerator():IEnumerator:this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeArgumentCollection:set_Item(int,CodeAttributeArgument):this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeArgumentCollection:Add(CodeAttributeArgument):int:this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeArgumentCollection:Contains(CodeAttributeArgument):bool:this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeArgumentCollection:CopyTo(ref,int):this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeArgumentCollection:IndexOf(CodeAttributeArgument):int:this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeArgumentCollection:Insert(int,CodeAttributeArgument):this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeArgumentCollection:Remove(CodeAttributeArgument):this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeDeclarationCollection:set_Item(int,CodeAttributeDeclaration):this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeDeclarationCollection:Add(CodeAttributeDeclaration):int:this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeDeclarationCollection:Contains(CodeAttributeDeclaration):bool:this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeDeclarationCollection:CopyTo(ref,int):this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeDeclarationCollection:IndexOf(CodeAttributeDeclaration):int:this
          -2 (-7.14% of base) : System.CodeDom.dasm - CodeAttributeDeclarationCollection:Insert(int,CodeAttributeDeclaration):this
16066 total methods with Code Size differences (16066 improved, 0 regressed), 228452 unchanged.
```

**Comment by AaronRobinsonMSFT** [comment]
@AndyAyersMS For my education, was the diff improvement that good simply for removing an inserted null check or is there something else in this review that changes the generated code?

**Comment by jkotas** [comment]
> was the diff improvement that good simply for removing an inserted null check 

Yep.

**Pull request merged**
