### PR TITLE
Fix JitRegs* optional builds

### LINKED ISSUE #37466: Failures in "CoreCLR Common Pri1 Test Build AnyOS AnyCPU" pipeline.
I have rebased my changes on the top of the current master and triggered jitstress and jitstressregs, both have failed with:
```
/Users/runner/runners/2.169.1/work/1/s/eng/liveBuilds.targets(147,5): error : The 'libs' subset must be built before building this project. Missing artifacts: /Users/runner/runners/2.169.1/work/1/s/artifacts/bin/ref/microsoft.netcore.app/Release/ [/Users/runner/runners/2.169.1/work/1/s/src/coreclr/tests/src/Common/CoreCLRTestLibrary/CoreCLRTestLibrary.csproj]
##[error]eng/liveBuilds.targets(147,5): error : The 'libs' subset must be built before building this project. Missing artifacts: /Users/runner/runners/2.169.1/work/1/s/artifacts/bin/ref/microsoft.netcore.app/Release/

```
in `CoreCLR Common Pri1 Test Build AnyOS AnyCPU checked` that I have not seen before.
[example](https://dev.azure.com/dnceng/public/_build/results?buildId=672645&view=logs&j=db768a9e-3325-5ce3-2d52-896c40bee68a&t=ea573249-0a9e-59d9-0a41-40ec8869f91f)

I think it could be caused by #37373, @safern could you take a look?

We need stress testing to be green to push two PRs that have been blocked on testing for a few days due to infrastructure issues. It would be very helpful to get this fixed/reverted before new potential disrupting infra changes.

cc @jashook @dotnet/runtime-infrastructure @CarolEidt

### LINKED ISSUE #37500: error: Not found PathtoPublish: /__w/1/s/artifacts/log/Checked
All the Libraries builds in

https://dev.azure.com/dnceng/public/_build/results?buildId=672754&view=results

failed with:

`##[error]Publishing build artifacts failed with an error: Not found PathtoPublish: /__w/1/s/artifacts/log/Checked`

@dotnet/runtime-infrastructure

### PR DESCRIPTION
**Pull request by safern**
Fixes: https://github.com/dotnet/runtime/issues/37466
Fixes: #37500

cc: @dotnet/runtime-infrastructure

### CODE REVIEW

**Comment by safern** [comment]
I don't know if I'm missing an optional pipeline, please let me know if so.

**Comment by safern** [comment]
https://dev.azure.com/dnceng/public/_build/results?buildId=672691&view=results

**Comment by safern** [comment]
It seems like it actually fixed it. However, still didn’t fix the warnings. Will update

**Review by trylek — APPROVED** [review]
Looks good, thanks for fixing this!

**Review by jashook — APPROVED** [review]

**Comment by safern** [comment]
Both issues are fixed. Will go ahead and merge.

Validated with: https://dev.azure.com/dnceng/public/_build/results?buildId=673628&view=logs&j=499826eb-b71f-5fb9-e963-df1d0bd97bcc&t=92db10ac-9f69-5d5a-3dbc-340b1e09e167

and https://dev.azure.com/dnceng/public/_build/results?buildId=672691&view=results

**Pull request merged**
