### PR TITLE
[wasm] Run debugger tests with one work item per test class

### PR DESCRIPTION
**Pull request by radical**
The tests take more than an hour to run as a single helix work item, so run the test classes in parallel on helix.
Also, move the debugger specific bits in `sendtohelix-wasm.targets` to a `wasm.helix.targets` next to the debugger tests.

### CODE REVIEW

**Review by ilonatommy — COMMENTED** [review]
Looks good, thanks for showing what you meant. How does Helix know where to search for related files? Does it search the whole repo for `.helix` extensions?

**Comment by radical** [comment]
> Looks good, thanks for showing what you meant. How does Helix know where to search for related files? Does it search the whole repo for `.helix` extensions?

We look in tests archive dir where we have the test zip files.

https://github.com/dotnet/runtime/blob/5108757b997c59ab8ba1fc5309ab0d4e730e2b77/src/libraries/sendtohelix-wasm.targets#L67

**Comment by radical** [comment]
Failures are unrelated.

**Review by lewing — APPROVED** [review]

**Comment by radical** [comment]
The failures are https://github.com/dotnet/runtime/issues/77630, and https://github.com/dotnet/runtime/issues/77631, and unrelated to this PR.

**Pull request merged**
