### PR TITLE
Add invocation to NuGet authentication scripts for internal feeds

### PR DESCRIPTION
**Pull request by hoyosjs**
Needed to be able to authenticate internal feeds.

### CODE REVIEW

**Comment by hoyosjs** [comment]
@dotnet/runtime-infrastructure the equivalent change is in servicing. This is to ease the future case.

**Comment by ViktorHofer** [comment]
Can we hold this until @safern is back? Would like him to review the PR

**Comment by ericstj** [comment]
Agreed, so long as nothing is blocked on this, can it wait until later in the week?

**Review by safern — COMMENTED** [review]
I feel like we can make a simpler change in master by not duplicating all these in all the job nodes but instead put it in shared locations. For example a shared template and then the group variable reference add it to `xplat-setup`. 

Also, I think we should explore the nuget authenticate plugin approach to avoid all these script runs if possible. If we can't use nuget authenticate plugin, I'm fine with it but let's make sure we share this stuff via a template or something to make it simpler.

**Comment by ericstj** [comment]
Do we still need this PR?

**Pull request closed without merging**
