### PR TITLE
Remove unnecessary references to System.ComponentModel.TypeConverter

### PR DESCRIPTION
**Pull request by eerhardt**
These references don't appear to be needed, so I removed them.

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]
I love seeing code being removed

**Review by safern — APPROVED** [review]
🎉

**Review by stephentoub — APPROVED** [review]
I assume these references weren't actually ending up in the compiled binary? (It's still a good change, for various reasons.)

**Comment by eerhardt** [comment]
> I assume these references weren't actually ending up in the compiled binary?

Correct. Here is a preview2 build of those binaries before my change:

image

**Pull request merged**
