### PR TITLE
Delete the zero-offset field sequence map

### PR DESCRIPTION
**Pull request by SingleAccretion**
In #68712 I promised that we'd delete the zero-offset field sequences. This change (finally, one could say) delivers on that promise.

There are still two scenarios where the root field sequence will have a zero offset:
1) Some statics accessed via helpers.
2) R2R-affected class fields.

Due to the fact the former cases are rare, this change represents them as `ADD(baseAddr, 0 <field seq>)`, which requires minimal extra handling (just one special case in morph).

The latter cases are not handled in this change to minimize diffs. It is likely that, if/when I get to supporting them, an explicit annotation node will be used (similar to `ARR_ADDR`), however, for now, there is no need for it.

We have some [diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1854504&view=ms.vss-build-web.run-extensions-tab) due to the usual consequences of more precise VNs (they are no longer "polluted" by zero-offset sequences.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
`Libraries Test Run checked coreclr OSX x64 Debug` failure is #70450.

@dotnet/jit-contrib

**Review by jakobbotsch — APPROVED** [review]
Love it! I will trigger some stress jobs.

**Comment by jakobbotsch** [comment]
Most of the stress failures are #71748, but the arm32 libraries-jitstress failures look related to this or one of the recent changes:
```scala
Assert failure(PID 61 [0x0000003d], Thread: 74 [0x004a]): Assertion failed 'OperIs(GT_LCL_VAR, GT_LCL_VAR_ADDR, GT_STORE_LCL_VAR)' in 'System.Buffers.Binary.Tests.BinaryReaderUnitTests:SpanWriteAndReadBigEndianHeterogeneousStruct():this' during 'Lowering nodeinfo' (IL size 1323; hash 0x710360ec; FullOpts)

    File: /__w/1/s/src/coreclr/jit/gtstructs.h Line: 65
    Image: /root/helix/work/correlation/dotnet
```

**Comment by SingleAccretion** [comment]
> `Assertion failed 'OperIs(GT_LCL_VAR, GT_LCL_VAR_ADDR, GT_STORE_LCL_VAR)'`

Taking a look.

**Comment by SingleAccretion** [comment]
> Taking a look

In the dump we have `STORE_LCL_FLD<float>(BITCAST<float>(ADD<int>))`. On ARM, we presume all `BITCAST`s are multi-reg nodes, which ultimately leads us down the wrong path.

This is fallout from #71567, I have opened #71831 to track the fix.

**Comment by jakobbotsch** [comment]
> This is fallout from https://github.com/dotnet/runtime/pull/71567, I have opened https://github.com/dotnet/runtime/issues/71831 to track the fix.

Thanks for taking a look, looks like this change should be fine to merge then.

**Pull request merged**
