### PR TITLE
JIT: better support for patchpoints in try regions

### LINKED ISSUE #35687: JIT\opt\OSR\tailrecursetry\tailrecursetry.cmd fails with COMPlus_FastTailCalls=0
`COMPlus_FastTailCalls` is a new environment variable added in #341. When it's set to 0, all tail-prefixed calls are dispatched via helpers.

JIT\opt\OSR\tailrecursetry\tailrecursetry.cmd is a test that turns on on-stack replacement, it sets
```
set COMPlus_TieredCompilation=1
set COMPlus_TC_QuickJitForLoops=1
set COMPlus_TC_OnStackReplacement=1
```

If additionally we set
```
set COMPlus_FastTailCalls=0
```

the test fails with 
```
BEGIN EXECUTION
 "f:\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" tailrecursetry.dll
starting sum

Assert failure(PID 1896 [0x00000768], Thread: 49832 [0xc2a8]): Assertion failed 'phiFound' in 'TailRecursionWithOsrEntryInTry:F(int,int,int,int):int' during 'SSA: insert phis' (IL size 49)

    File: F:\runtime\src\coreclr\src\jit\ssabuilder.cpp Line: 922
    Image: f:\runtime\artifacts\tests\coreclr\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
```

### PR DESCRIPTION
**Pull request by AndyAyersMS**
This change adds control flow to ensure that an OSR method for a patchpoint
nested in try regions enters those regions try from the first block of each
try rather than mid-try.

This lets these OSR methods conform to the data flow expectations that the
only way control flow can enter a try is via its first block.

See #33658 for more details on the approach taken here.

Fixes #35687.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
It might be possible to merge this new logic with the try region trimming done in `fgRemoveEmptyBlocks` but for now I'm keeping it separate.

No diffs outside of OSR (which we currently can't easily diff; seems like I should do an SPMI collection here perhaps).

cc @dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]
1. I think you should add some of the comment from https://github.com/dotnet/runtime/issues/33658#issuecomment-921250854 into your new code, especially the pseudo-code of the flow you are creating.
2. It's pretty weird that a function named `fgRemoveEmptyBlocks` can create a bunch of blocks and flow and a new temp.
3. Re (2), it looks like `fgRemoveEmptyBlocks` gets called on inlinees, and then later in morph init. I guess that ends up not creating multiple flow because we don't inline functions with EH, but it maybe creates an impediment if we ever do (and the inlinee is an OSR method? So, maybe not a problem?)

**Comment by AndyAyersMS** [comment]
Going to wait on this until #59789 lands so (hopefully) I can get clean OSR runs.

**Comment by AndyAyersMS** [comment]
Yeah, `fgRemoveEmptyBlocks`  should probably be renamed, maybe `fgUpdateFlowAfterImportation` ...? Similar in nature to `fgAddInternal` too, though that runs a bit later on.

As for running it on inlinees, right, only the first bit (removing un-imported blocks) will matter today. 

We'll never inline OSR methods, they never get called in a normal fashion.

**Comment by AndyAyersMS** [comment]
Merged in the other OSR fix, so will try running the experimental pipeline here. Don't expect it to be green as there is a latent crossgen2 issue.

**Comment by AndyAyersMS** [comment]
Looks like a number of novel failures, so I'll have to revise this PR.

**Comment by AndyAyersMS** [comment]
Still have one overly aggressive assert (mutual protect case)... the OSR entry can be in a nested try and still not need step blocks.

**Comment by AndyAyersMS** [comment]
jit-experimental now has just the expected set of failures.

**Comment by AndyAyersMS** [comment]
@BruceForstall feel free to take another look; think I addressed your comments.

**Review by BruceForstall — APPROVED** [review]
LGTM. Thanks for adding the detailed comments.

**Pull request merged**
