### PR TITLE
Control Crossgen2 optimizations with DebuggableAttribute

### PR DESCRIPTION
**Pull request by nattress**
* Assemblies compiled in debug configuration use the `System.Diagnostics.DebuggableAttribute` to indicate optimizations are disabled.
* Match Crossgen 1's behavior and respect this setting if no explicit optimization arguments are passed in.
* Add `-Od` switch to disable optimizations since now the default behavior of Crossgen2 is to optimize release-built assemblies.

cc @dotnet/crossgen-contrib

### CODE REVIEW

**Comment by nattress** [comment]
Addresses https://github.com/dotnet/runtime/issues/44324

**Review by trylek — APPROVED** [review]
LGTM, thank you!

**Comment by davidwrighton** [comment]
Should we change our test scripts to not explicitly pass -O?

**Comment by nattress** [comment]
I'll remove the explicit -O from the CoreCLR tests though we only use Check and Release flavors in CI so the assemblies won't have debug enabled typically. Libraries tests using Crossgen2 will be more interesting since they do Debug test runs. The Crossgen comparison runs are release only so I'll leave those alone.

**Comment by ViktorHofer** [comment]
// Auto-generated message

https://github.com/dotnet/runtime/commit/69e114c1abf91241a0eeecf1ecceab4711b8aa62 which was merged 12/7 removed the intermediate src/coreclr/**src**/ folder. This PR needs to be updated as it touches files in that directory which causes conflicts.

To update your commits you can use this bash script: https://gist.github.com/ViktorHofer/6d24f62abdcddb518b4966ead5ef3783. Feel free to use the comment section of the gist to improve the script for others.

**Pull request merged**
