### PR TITLE
Temporarily block out UnmanagedCallersOnlyTest in Pri1 runs

### PR DESCRIPTION
**Pull request by trylek**
Works around: https://github.com/dotnet/runtime/issues/42168

/cc: @dotnet/runtime-infrastructure

### CODE REVIEW

**Comment by trylek** [comment]
The intent of this PR is to provide a temporary workaround before https://github.com/dotnet/runtime/pull/42146 is merged in. I don't have the latest info on the development on 42146 so I'm just pulling in the proximate stakeholders to cooperate in making a call on which change should go in first. The idea is that, if 42146 is about to be merged in [very] soon, this change doesn't make sense and would only cause extra churn; but prolonged wait in the broken state is detrimental to all parties.

**Comment by jkotas** [comment]
cc @AaronRobinsonMSFT

**Comment by jkotas** [comment]
>  I don't have the latest info on the development on #42146

The test is failing with the current PR state, so it needs some work before it gets merged.

**Review by jkotas — APPROVED** [review]

**Review by BruceForstall — APPROVED** [review]
Interesting way to disable the build. Isn't the "normal" way to use `<DisableProjectBuild>true</DisableProjectBuild>`?

Anyway, LGTM if the outerloop job works

**Comment by AaronRobinsonMSFT** [comment]
I just merged the fixed test. This is no longer needed.

**Pull request closed without merging**
