### PR TITLE
Add the ability to set  Browsable property value in runtime by reflection

### PR DESCRIPTION
**Pull request by GMCadiom**
Example:

```
PropertyDescriptor descriptor = TypeDescriptor.GetProperties(modelName)[propertyName];
BrowsableAttribute attribute = (BrowsableAttribute)descriptor.Attributes[typeof(BrowsableAttribute)];
PropertyInfo propertyToChange = attribute.GetType().GetProperty("browsable", BindingFlags.NonPublic | BindingFlags.Instance);
propertyToChange?.SetValue(attribute, value);
```

### CODE REVIEW

**Comment by GMCadiom** [comment]
> @GMCadiom please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

**Comment by GMCadiom** [comment]
> Tagging subscribers to this area: @dotnet/area-system-componentmodel See info in [area-owners.md](https://github.com/dotnet/runtime/blob/main/docs/area-owners.md) if you want to be subscribed.
> 
> Issue Details
> Example:
> 
> ```
> PropertyDescriptor descriptor = TypeDescriptor.GetProperties(modelName)[propertyName];
> BrowsableAttribute attribute = (BrowsableAttribute)descriptor.Attributes[typeof(BrowsableAttribute)];
> PropertyInfo propertyToChange = attribute.GetType().GetProperty("browsable", BindingFlags.NonPublic | BindingFlags.Instance);
> propertyToChange?.SetValue(attribute, value);
> ```
> 
> Author:	GMCadiom
> Assignees:	-
> Labels:	
> `area-System.ComponentModel`, `community-contribution`
> 
> Milestone:	-

@ericstj 

please review

**Comment by teo-tsirpanis** [comment]
Hello, thanks for contributing to .NET! It would be better if you first opened an issue that better describes what exactly you need. This is a change to the public API and needs to be discussed and approved before opening a PR.

**Comment by jkotas** [comment]
Replace by discussion in https://github.com/dotnet/runtime/issues/86544

**Pull request closed without merging**
