### PR TITLE
JIT: Clean up inliner substitution

### LINKED ISSUE #75827: [libraries-pgo] BBF_HAS_IDX_LEN is not set ... but is required because of the following tree
Failure in System.Globalization.Extensions.Tests on multiple Linux configurations.

Work item: https://dev.azure.com/dnceng-public/public/_build/results?buildId=21469&view=ms.vss-test-web.build-test-results-tab&runId=432716&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab&resultId=192990
Console log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7b6005bf99b2486999/System.Globalization.Extensions.Tests/1/console.8d45794a.log?helixlogtype=result

```scala
BBF_HAS_IDX_LEN is not set on BB10 but is required because of the following tree 
N002 (  3,  3) [000126] ---X-------                         *  ARR_LENGTH int   
N001 (  1,  1) [000125] -----------                         \--*  LCL_VAR   ref    V11 tmp8         u:2

Assert failure(PID 21939 [0x000055b3], Thread: 21945 [0x55b9]): Assertion failed 'false' in 'Xunit.Assert:RecordException(System.Func`1[System.Object]):System.Exception' during 'Early Value Propagation' (IL size 48; hash 0xd54f2d8c; Tier1)

    File: /__w/1/s/src/coreclr/jit/earlyprop.cpp Line: 66
    Image: /datadisks/disk1/work/A44E0904/p/dotnet
```

### PR DESCRIPTION
**Pull request by jakobbotsch**
* Stop using GenTree::ReplaceWith
* GenTreeRetExpr now directly contains its substitution members, which is a tree either from the inline candidate, a local (due to spill temps) or the call itself (due to inliner failure). In the former case, it also contains the BasicBlock the child tree comes from to ensure that its flags can be propagated once and for all during substitution.
* Make various members strongly typed, e.g. GenTreeRetExpr::gtInlineCandidate is now a GenTreeCall*, InlineCandidateInfo::retExpr is now a GenTreeRetExpr*. This is possible since we are no longer using GenTree::ReplaceWith.

Fix #75827

### CODE REVIEW

**Comment by jakobbotsch** [comment]
> Getting the block flags right has been a persistent source of trouble; see eg #37335, #37840, #38243 and probably a few more.

Indeed, and I'm pretty sure the current way we propagate does not really make logical sense (see TODOs I have added in the source in this PR). I am hoping we are going to make some inliner changes in this release that we can remove those TODOs as part of.

At least this PR accomplishes centralizing all the substitution logic (well, except for GDV) into `UpdateInlineReturnExpressionPlaceHolder`. Hopefully this is the end of the wrong flag propagation, but I suppose we'll see...

**Comment by jakobbotsch** [comment]
The problem seems simple enough -- whenever we replace a `GT_RET_EXPR` node with an arbitrary tree, we potentially need to propagate flags from the basic block that the arbitrary tree comes from. But the previous behavior using `GenTree::ReplaceWith` makes it very difficult to reason about the arbitrary trees and where they are coming from once you start replacing `GT_RET_EXPR` nodes and the inline candidates with other `GT_RET_EXPR` nodes. This PR was initially just a clean up to try to simplify the convoluted replacement logic, but turned out to fix the issue too.

**Comment by jakobbotsch** [comment]
cc @dotnet/jit-contrib PTAL @AndyAyersMS @EgorBo

**Review by AndyAyersMS — APPROVED** [review]
Consider fixing the "prev BB" and `BBF_SPLIT_GAINED` issues as separate isolated PRs (both from this PR and from each other by a few days), so we can better assess the impact of these via the lab data.

**Comment by jakobbotsch** [comment]
The failures look like #76880 and known from build analysis.

> Consider fixing the "prev BB" and `BBF_SPLIT_GAINED` issues as separate isolated PRs (both from this PR and from each other by a few days), so we can better assess the impact of these via the lab data.

Makes sense.

**Comment by jakobbotsch** [comment]
I cannot reproduce the Fuzzlyn failures on the head of my PR. That probably means they are recent regressions in main.

**Comment by jakobbotsch** [comment]
I'm not able to reproduce it on main either. I have seen these kind of intermittent failures before, so I don't think it's related to this PR. Not sure how we can track these down, I will need to think about if I can record more information from Fuzzlyn.

The failures looked known as mentioned above so will merge.

**Pull request merged**
