### PR TITLE
Replaced GetDirectoryNameOfFileAbove with GetPathOfFileAbove

### PR DESCRIPTION
**Pull request by TaurahSP**
Replaced "$([MSBuild]::GetDirectoryNameOfFileAbove(" with "$([MSBuild……]::GetPathOfFileAbove(" to improve readability

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43462) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43462) before we can accept your contribution.<br/><br/>:x: TaurahSP [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=43462)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=43462) it.</sub>

**Comment by TaurahSP** [comment]
@marek-safar can you help please, any idea why the build is failing

**Comment by marek-safar** [comment]
You can ignore the failure, it's infrastructure issue

**Comment by danmosemsft** [comment]
This is for https://github.com/dotnet/runtime/issues/30468

Hi @TaurahSP , thanks for the contribution, but there are a few issues here

1. You have included some files that didn't need to change, eg json, txt
2. The transformation proposed only works on this pattern:
`$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory),  FOO))\FOO`
then it can be changed to
`$([MSBuild]::GetPathOfFileAbove(FOO))`
It doesn't work where there are different files in the same line, or one is a directory. So the edits to testprojects.props and project.csproj.template aren't valid, for those reasons respectively.

I am going to close this PR and feel free to create a new one if you want to give another shot. Or, you could choose to pick a different issue as you prefer.

**Comment by danmosemsft** [comment]
https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019 describes what each does

**Pull request closed without merging**
