### PR TITLE
Fix options source gen test

### LINKED ISSUE #93592: [mono][android] Failure in SourceGeneration.Unit.Tests
Occurs on `net9.0-linux-Release-arm64-Mono_Release_LinuxBionic-Windows.10.Amd64.Android.Open` and `net9.0-linux-Release-x64-Mono_Release_LinuxBionic-Ubuntu.2204.Amd64.Android.29.Open`.

There is a single failing test, with the following output:
```
Assert.Equal() Failure
                                 ↓ (pos 1)
Expected: ···ttributes.P0 m"..., "P11: The field OptionsUsingGeneratedAttr···
Actual:   ···ttributes.P0 m"..., "P11: The field OptionsUsingGeneratedAttr···
                                 ↑ (pos 1)
Stack Trace:
  /_/src/libraries/Microsoft.Extensions.Options/tests/SourceGeneration.Unit.Tests/OptionsRuntimeTests.cs(361,0): at Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes()
  /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
  /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

Logs: 
- https://[helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-93547-merge-a769f2ca23964203af/Microsoft.Extensions.Options.SourceGeneration.Unit.Tests/1/console.d1afd4e7.log?helixlogtype=result](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-93547-merge-a769f2ca23964203af/Microsoft.Extensions.Options.SourceGeneration.Unit.Tests/1/console.d1afd4e7.log?helixlogtype=result)
- https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-93547-merge-2b9a4ace874d4ac4ac/Microsoft.Extensions.Options.SourceGeneration.Unit.Tests/1/console.320cb987.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-93547-merge-2b9a4ace874d4ac4ac/Microsoft.Extensions.Options.SourceGeneration.Unit.Tests/1/console.320cb987.log?helixlogtype=result)

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=439813
Build error leg or test failing: Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/93547

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "P11: The field OptionsUsingGenerated",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=439813
**Error message validated:** `P11: The field OptionsUsingGenerated`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/17/2023 8:33:26 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[444074](https://dev.azure.com/dnceng-public/public/_build/results?buildId=444074)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=444074&view=ms.vss-test-web.build-test-results-tab&runId=9923948&resultId=182705)|dotnet/runtime#93594|
|[443974](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443974)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443974&view=ms.vss-test-web.build-test-results-tab&runId=9922272&resultId=154008)|dotnet/runtime#93724|
|[443717](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443717)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443717&view=ms.vss-test-web.build-test-results-tab&runId=9914604&resultId=181208)||
|[443533](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443533)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443533&view=ms.vss-test-web.build-test-results-tab&runId=9905434&resultId=182520)||
|[443348](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443348)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443348&view=ms.vss-test-web.build-test-results-tab&runId=9900426&resultId=155154)||
|[443125](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443125)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443125&view=ms.vss-test-web.build-test-results-tab&runId=9890066&resultId=182705)||
|[442968](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442968)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442968&view=ms.vss-test-web.build-test-results-tab&runId=9886894&resultId=115613)||
|[442747](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442747)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442747&view=ms.vss-test-web.build-test-results-tab&runId=9877094&resultId=140630)||
|[442269](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442269)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442269&view=ms.vss-test-web.build-test-results-tab&runId=9863560&resultId=182703)||
|[442238](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442238)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442238&view=ms.vss-test-web.build-test-results-tab&runId=9862144&resultId=177952)|dotnet/runtime#91800|
|[441958](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441958)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441958&view=ms.vss-test-web.build-test-results-tab&runId=9852540&resultId=182520)||
|[441762](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441762)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441762&view=ms.vss-test-web.build-test-results-tab&runId=9845944&resultId=182520)||
|[441700](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441700)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441700&view=ms.vss-test-web.build-test-results-tab&runId=9844592&resultId=182631)||
|[441488](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441488)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=441488&view=ms.vss-test-web.build-test-results-tab&runId=9838486&resultId=168857)||
|[440723](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440723)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440723&view=ms.vss-test-web.build-test-results-tab&runId=9818584&resultId=177479)||
|[440640](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440640)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440640&view=ms.vss-test-web.build-test-results-tab&runId=9815618&resultId=182626)|dotnet/runtime#93182|
|[440293](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440293)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440293&view=ms.vss-test-web.build-test-results-tab&runId=9805878&resultId=182626)|dotnet/runtime#91560|
|[440312](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440312)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440312&view=ms.vss-test-web.build-test-results-tab&runId=9806288&resultId=180536)||
|[440248](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440248)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440248&view=ms.vss-test-web.build-test-results-tab&runId=9804344&resultId=182626)||
|[440106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440106)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440106&view=ms.vss-test-web.build-test-results-tab&runId=9800360&resultId=144251)||
|[439813](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439813)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439813&view=ms.vss-test-web.build-test-results-tab&runId=9791934&resultId=182626)|dotnet/runtime#93547|
|[439390](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439390)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=439390&view=ms.vss-test-web.build-test-results-tab&runId=9781900&resultId=182626)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|7|22|22|

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/93592

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @eiriktsarpalis @krwq could you please have a quick look? Thanks!

**Comment by tarekgh** [comment]
CC @ericstj

**Review by eiriktsarpalis — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]
LGTM, the runtime-linuxbionic failures are unrelated

**Pull request merged**
