### PR TITLE
Fix typing on optimization to use vbroadcasti64x4

### LINKED ISSUE #95866: Assertion failed 'ins != INS_invalid'
https://dev.azure.com/dnceng-public/public/_build/results?buildId=494786&view=ms.vss-test-web.build-test-results-tab

Linux x64

```
export DOTNET_TieredCompilation=0
export DOTNET_DbgEnableMiniDump=1
export DOTNET_EnableCrashReport=1
export DOTNET_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export DOTNET_JitStress=125

JIT/Regression/Regression_2/Regression_2.sh

19:33:59.232 Running test: JIT/Regression/JitBlue/Runtime_91335/Runtime_91335/Runtime_91335.dll

Assert failure(PID 2628 [0x00000a44], Thread: 2628 [0x0a44]): Assertion failed 'ins != INS_invalid' in 'TestClass:.ctor():this' during 'Generate code' (IL size 254; hash 0xbf9dbb9e; FullOpts)

    File: /__w/1/s/src/coreclr/jit/hwintrinsiccodegenxarch.cpp Line: 121
    Image: /datadisks/disk1/work/9EE708E3/p/corerun

[createdump] Gathering state for process 2628 corerun
[createdump] Crashing thread 0a44 signal 6 (0006)
[createdump] Writing crash report to file /home/helix
```

### PR DESCRIPTION
**Pull request by BruceForstall**
Fixes #95866

### CODE REVIEW

**Comment by BruceForstall** [comment]
Manually triggered jitstress-isas-avx512 pipeline: https://dev.azure.com/dnceng-public/public/_build/results?buildId=510879&view=results

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib @Ruihan-Yin PTAL

**Comment by BruceForstall** [comment]
[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=510878&view=ms.vss-build-web.run-extensions-tab)

**Review by EgorBo — APPROVED** [review]

**Pull request merged**
