### PR TITLE
Remove dead code in BlockingCollection

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by danmosemsft** [comment]
Unless IsStaThread ought to be implemented (ported)?

**Comment by stephentoub** [comment]
> Unless IsStaThread ought to be implemented (ported)?

Yes, I think this should instead be fixed to match netfx: `return Thread.CurrentThread.GetApartmentState() == ApartmentState.STA;`

**Review by danmoseley — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Comment by jkotas** [comment]
I do not think there is a rationale explanation for why this should behave differently for STA vs. MTA. I agree with Marek that this should be deleted. Submitted https://github.com/dotnet/runtime/pull/1635 and also added tests to make sure that it works.

**Comment by stephentoub** [comment]
I'm not understanding. Previously on desktop for example on a thread pool thread you could wait on any number of collections. And now we're going to fail in such a case. Your argument is just that we've been failing in such a case on core and it's ok to continue rather than fixing it?

**Comment by stephentoub** [comment]
Nevermind, it's just that we could handle one more on MTA. Ok.

**Comment by stephentoub** [comment]
> rationale behavior

The motivation was to accomodate as many as possible, and since WaitHandle.WaitAny supports 64 handles on MTA and 63 on STA, this was dealing with that.

As an aside, I get strange behavior when calling WaitHandle.WaitAny with 64 handles... I was expecting an exception, but instead I get a result of 258:
```C#
using System;
using System.Threading;

class Program
{
    static void Main(string[] args)
    {
        var mres = new ManualResetEventSlim();
        var t = new Thread(() =>
        {
            var handles = new WaitHandle[64];
            for (int i = 0; i < handles.Length; i++)
            {
                handles[i] = new ManualResetEvent(false);
            }
            Console.WriteLine("waiting");
            try
            {
                int i = WaitHandle.WaitAny(handles);
                Console.WriteLine(i);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
            finally
            {
                mres.Set();
            }
        });
        t.SetApartmentState(ApartmentState.STA);
        t.IsBackground = true;
        t.Start();
        mres.Wait();
    }
}
```

**Comment by jkotas** [comment]
I did not find anything about the 63 limit for STA in the implementation, and the docs https://docs.microsoft.com/en-us/dotnet/api/system.threading.waithandle.waitany?view=netframework-4.8 do not mention anything about 63 limit under STA either. But your test shows that waiting for 64 handles in STA seems to be broken. Hmmm...

**Pull request merged**
