### PR TITLE
Revert "Move ServiceCollection to abstractions (#52284)"

### PR DESCRIPTION
**Pull request by davidfowl**
This reverts commit ad7455cc2f5b58af64285828a17e42fdf4e3658e.

People are doing reflection...

### CODE REVIEW

**Comment by eerhardt** [comment]
I’m not sure I follow. If people use reflection, won’t the TypeForwardedTo still work?

Can you give an example the reflection we want to keep working?

**Comment by eerhardt** [comment]
Won’t this break https://github.com/dotnet/runtime/pull/52363?

**Comment by davidfowl** [comment]
> Won’t this break #52363?

Yep. I'm gonna bundle it with that change after this is merged.

**Comment by davidfowl** [comment]
Because it's blocking dependency flow to efcore

**Comment by ericstj** [comment]
@davidfowl, is nothing else depending on the type move?  In other words, would it have been fine to combine https://github.com/dotnet/runtime/pull/52363 and https://github.com/dotnet/runtime/commit/ad7455cc2f5b58af64285828a17e42fdf4e3658e from the start?  If so, I'm fine with reverting so that we can unblock dependency flow.

**Review by ericstj — APPROVED** [review]

**Comment by ericstj** [comment]
@davidfowl are you planning to merge this or were you going to work around it in efcore?

**Comment by davidfowl** [comment]
> @davidfowl are you planning to merge this or were you going to work around it in efcore?

I'm debating. I feel like I want to work around it since the fix is approved in Odata. I'd like to get them to merge and push something.

**Comment by davidfowl** [comment]
We're going to work around this in EF and fix Odata.

**Pull request closed without merging**
