### PR TITLE
[iOS] Enable some previously skipped tests

### PR DESCRIPTION
**Pull request by steveisok**
Enabling because the underlying issues appear to have been fixed.

### CODE REVIEW

**Comment by MaximLipnin** [comment]
The `System.Text.Json.Tests` test suite still crashes on MacCatalyst x64 leg.

**Comment by steveisok** [comment]
@premun The System.Text.Json failure in iOSSimulator is pretty strange.  If you look at the system.log, you'll notice that it says adhoc signing failed:

```
2022-02-22 09:20:01.864973-0800  localhost kernel[0]: (AppleMobileFileIntegrity) AMFI: '/Users/helix-runner/Library/Developer/CoreSimulator/Devices/C5CFD071-649D-4303-8F47-6C4F8AE36E88/data/Containers/Bundle/Application/4DDCFCD3-F43D-4DCB-A552-47E8584EEA41/System.Text.Json.Tests.app/System.Text.Json.Tests' is adhoc signed.
2022-02-22 09:20:01.869789-0800  localhost amfid[122]: [com.apple.MobileFileIntegrity:amfid] Basic requirement validation failed, error: (null)
2022-02-22 09:20:01.869887-0800  localhost amfid[122]: /Users/helix-runner/Library/Developer/CoreSimulator/Devices/C5CFD071-649D-4303-8F47-6C4F8AE36E88/data/Containers/Bundle/Application/4DDCFCD3-F43D-4DCB-A552-47E8584EEA41/System.Text.Json.Tests.app/System.Text.Json.Tests signature not valid: -67050
```

It seems rather flaky, so I'm thinking it might be machine specific.

**Comment by premun** [comment]
@steveisok will have a look tomorrow, however the ad-hoc signing might be a red herring - I think it's in all of the system logs.

**Comment by premun** [comment]
Seems like the app itself ended with `1`:
> Feb 22 09:27:02 dci-mac-build-148 com.apple.CoreSimulator.SimDevice.C5CFD071-649D-4303-8F47-6C4F8AE36E88[1190] (UIKitApplication:net.dot.System.Text.Json.Tests[2406][rb-legacy][3788]): Service exited with abnormal code: 1

I believe apps with test runners should end with `0`?
This looks like something happened inside of the app actually?

The problem is that we are still not able to get stdout log from apps in Helix (https://github.com/dotnet/xharness/issues/694) so these problems are hard to investigate..

**Comment by MaximLipnin** [comment]
> The System.Text.Json failure in iOSSimulator is pretty strange. 

It passed for me locally (20341 tests).

**Comment by steveisok** [comment]
@premun Could this be machine specific in any way?

**Comment by premun** [comment]
I guess that depends on the numbers. Do we have some data on how often this happens? It is more often for this specific app?

Then we can have a look at the machines where this failed and what their failure rate is.

**Comment by MaximLipnin** [comment]
Running something like 
```
 WorkItems 
| where Started > now(-7d)  
| where ExitCode == 83
| where FriendlyName == 'System.Text.Json.Tests'
| join kind= inner (
   Jobs  | where Started > now(-7d) | project  QueueName , JobId, Build, Type, Source 
) on JobId
| project ExitCode, QueueName, Started, Source, JobName, MachineName
| order by Started desc
```
shows that STJ failures (MacCatalyst/iOSSimulator/tvOSSimulator) have been seen on different machines.



| ExitCode | QueueName           | Started                  | Source                                         | JobName                              | MachineName             |
|----------|---------------------|--------------------------|------------------------------------------------|--------------------------------------|-------------------------|
| 83       | osx.1015.amd64.open | 2022-02-25T10:06:28.978Z | pr/public/dotnet/runtime/refs/pull/65652/merge | 245ed987-844e-49de-a395-92519788f6fc | dci-mac-build-206       |
| 83       | osx.1015.amd64.open | 2022-02-25T10:02:00.221Z | pr/public/dotnet/runtime/refs/pull/65652/merge | 245ed987-844e-49de-a395-92519788f6fc | dci-mac-build-173       |
| 83       | osx.1015.amd64.open | 2022-02-25T09:48:53.517Z | pr/public/dotnet/runtime/refs/pull/65652/merge | 08e0c054-4581-4c84-b5bf-a1dd7e1439ca | dci-mac-build-193       |
| 83       | osx.1015.amd64.open | 2022-02-22T17:18:50.216Z | pr/public/dotnet/runtime/refs/pull/65652/merge | daa3ea94-39e6-40bb-ae92-9fdd56aca6b7 | dci-mac-build-148.local |
| 83       | osx.1015.amd64.open | 2022-02-22T17:15:00.529Z | pr/public/dotnet/runtime/refs/pull/65652/merge | daa3ea94-39e6-40bb-ae92-9fdd56aca6b7 | dci-mac-build-207       |
| 83       | osx.1015.amd64.open | 2022-02-22T11:10:48.216Z | pr/public/dotnet/runtime/refs/pull/65652/merge | e7ec0688-6f48-4175-89d9-8b39263e3d59 | dci-mac-build-190       |
| 83       | osx.1015.amd64.open | 2022-02-22T11:04:06.314Z | pr/public/dotnet/runtime/refs/pull/65652/merge | e7ec0688-6f48-4175-89d9-8b39263e3d59 | dci-macpro-18.local     |
| 83       | osx.1015.amd64.open | 2022-02-21T05:09:04.299Z | pr/public/dotnet/runtime/refs/pull/65652/merge | 360cedef-2d3e-430a-a084-ce6d73482952 | dci-mac-build-185       |
| 83       | osx.1015.amd64.open | 2022-02-21T05:04:15.242Z | pr/public/dotnet/runtime/refs/pull/65652/merge | 360cedef-2d3e-430a-a084-ce6d73482952 | dci-mac-build-205       |

**Comment by premun** [comment]
With the new mobile telemetry we can also get a more detailed breakdown by platform:

```sql
Metrics
| where EventType == "_MobileDeviceOperation" and MetricName == "ExitCode" and Timestamp > now()-7d
| join kind=inner WorkItems on WorkItemId
| where MachineName != ""
| extend Dimensions = parse_json(Dimensions)
| project 
    Timestamp,
    WorkItemFriendlyName,
    MachineName,
    ExitCode = MetricValue,
    Platform = tostring(Dimensions.platform),
    Command = tostring(Dimensions.command),
    Target = tostring(Dimensions.target),
    IsDevice = tobool(Dimensions.isDevice),
    ConsoleUri
| where WorkItemFriendlyName == "System.Text.Json.Tests" and ExitCode == 83
| summarize count() by MachineName, Target
| order by Target, MachineName
```

| MachineName             | Target                | count_ |
|-------------------------|-----------------------|-------:|
| dci-mac-build-206       | tvos-simulator:13.4   |      2 |
| dci-mac-build-173       | tvos-simulator:13.4   |      2 |
| DNCENGMAC040.local      | tvos-device:14.3      |      1 |
| DNCENGMAC026.local      | tvos-device:14.3      |      1 |
| DNCENGMAC010.local      | tvos-device:14.3      |      1 |
| DNCENGMAC008.local      | tvos-device:14.3      |      1 |
| dci-macpro-18.local     | maccatalyst           |      2 |
| dci-mac-build-205       | maccatalyst           |      2 |
| dci-mac-build-193       | maccatalyst           |      1 |
| dci-mac-build-190       | maccatalyst           |      2 |
| dci-mac-build-185       | maccatalyst           |      2 |
| dci-mac-build-169       | maccatalyst           |      1 |
| dci-mac-build-207       | ios-simulator-64:13.5 |      2 |
| dci-mac-build-148.local | ios-simulator-64:13.5 |      2 |

**Comment by premun** [comment]
Digging into this more, seems like some test suites fail 100% of the time on tvOS devices:

```sql
Metrics
| where EventType == "_MobileDeviceOperation" and MetricName == "ExitCode" and Timestamp > now()-7d
| join kind=inner WorkItems on WorkItemId
| where MachineName != ""
| extend Dimensions = parse_json(Dimensions)
| project 
    Timestamp,
    WorkItemFriendlyName,
    MachineName,
    ExitCode = MetricValue,
    Platform = tostring(Dimensions.platform),
    Command = tostring(Dimensions.command),
    Target = tostring(Dimensions.target),
    IsDevice = tobool(Dimensions.isDevice),
    ConsoleUri
| summarize FailureRate=countif(ExitCode == 83)*100/count(), TotalCount=count() by WorkItemFriendlyName, Target
| where FailureRate > 0
| order by FailureRate desc, WorkItemFriendlyName asc, Target
```

but if omitting tvOS devices:

```sql
Metrics
| where EventType == "_MobileDeviceOperation" and MetricName == "ExitCode" and Timestamp > now()-7d
| join kind=inner WorkItems on WorkItemId
| where MachineName != ""
| extend Dimensions = parse_json(Dimensions)
| project 
    Timestamp,
    WorkItemFriendlyName,
    MachineName,
    ExitCode = MetricValue,
    Platform = tostring(Dimensions.platform),
    Command = tostring(Dimensions.command),
    Target = tostring(Dimensions.target),
    IsDevice = tobool(Dimensions.isDevice),
    ConsoleUri
| summarize FailureRate=countif(ExitCode == 83)*100/count(), TotalCount=count() by WorkItemFriendlyName, Target
| where Target != "tvos-device:14.3" and FailureRate > 0
| order by FailureRate desc, WorkItemFriendlyName asc, Target
```

We start to see interesting things:

| WorkItemFriendlyName                    | Target                | FailureRate | TotalCount |
|-----------------------------------------|-----------------------|------------:|-----------:|
| System.Text.Json.Tests                  | tvos-simulator:13.4   |          66 |          6 |
| System.Text.Json.Tests                  | maccatalyst           |          66 |         15 |
| System.Text.Json.Tests                  | ios-simulator-64:13.5 |          66 |          6 |
| System.IO.FileSystem.Watcher.Tests      | maccatalyst           |          22 |         88 |
| System.Collections.Specialized.Tests    | ios-simulator-64:13.5 |           8 |         23 |
| System.Composition.AttributeModel.Tests | ios-simulator-64:13.5 |           8 |         23 |
| System.Net.Ping.Functional.Tests        | tvos-simulator:13.4   |           8 |         23 |
| System.Net.WebProxy.Tests               | tvos-simulator:13.4   |           8 |         23 |
| System.Net.WebSockets.Client.Tests      | ios-simulator-64:13.5 |           8 |         23 |
| System.Reflection.Extensions.Tests      | ios-simulator-64:13.5 |           8 |         23 |
| System.Threading.Channels.Tests         | tvos-simulator:13.4   |           8 |         23 |
| System.Xml.Linq.Events.Tests            | tvos-simulator:13.4   |           8 |         23 |
| System.Xml.Linq.xNodeBuilder.Tests      | tvos-simulator:13.4   |           8 |         23 |
| System.Xml.RW.RwFactory.Tests           | tvos-simulator:13.4   |           8 |         23 |
| System.IO.Packaging.Tests               | tvos-simulator:13.4   |           7 |         26 |
| System.Runtime.Tests                    | maccatalyst           |           7 |        484 |
| System.Runtime.Tests                    | ios-simulator-64:13.5 |           6 |        153 |
| JIT.HardwareIntrinsics.Arm.Sha1         | ios-simulator-64:13.5 |           5 |         68 |
| System.Collections.Tests                | maccatalyst           |           5 |         70 |
| System.Memory.Tests                     | maccatalyst           |           5 |         70 |
| System.Net.Security.Enterprise.Tests    | maccatalyst           |           5 |         70 |
| System.Runtime.Tests                    | tvos-simulator:13.4   |           5 |        149 |
| baseservices.mono                       | ios-simulator-64:13.5 |           3 |         51 |
| System.ComponentModel.Annotations.Tests | maccatalyst           |           2 |         67 |
| System.IO.Tests                         | maccatalyst           |           2 |         67 |
| System.Linq.Parallel.Tests              | maccatalyst           |           2 |         67 |
| System.Text.Encoding.Tests              | maccatalyst           |           2 |         67 |
| System.Threading.Tasks.Parallel.Tests   | maccatalyst           |           2 |         67 |
| System.Xml.RW.SubtreeReader.Tests       | maccatalyst           |           2 |         67 |
| System.Xml.RW.XmlWriterApi.Tests        | maccatalyst           |           2 |         67 |
| System.Runtime.Tests                    | ios-device:14.3       |           1 |        388 |

**Comment by MaximLipnin** [comment]
@premun Good to know about new mobile telemetry 👍 Based on the results from the previous comment, I only see that System.Text.Json.Tests has quite high failure rate. What am I missing?

**Comment by premun** [comment]
Yes, I think the data proves that `System.Text.Json` is actually problematic somehow. Which is sort of good news since it's not a generic flakiness.

Does it differ in the number of tests inside? Or do the tests maybe run very fast and there's a large amount of them? One thing that comes to mind is that maybe it is streaming too much data over the TCP too fast compared to the other APKs?

**Review by akoeplinger — APPROVED** [review]

**Comment by steveisok** [comment]
Failures are unrelated

**Pull request merged**
