### PR TITLE
Switch Windows Checked build to `-O2` from `-O1`

### PR DESCRIPTION
**Pull request by BruceForstall**
That is, optimize for speed, not for size.

### CODE REVIEW

**Comment by EgorBo** [comment]
Does it make superpmi faster?

**Comment by BruceForstall** [comment]
> Does it make superpmi faster?

When I first pushed this, with https://github.com/dotnet/runtime/pull/53888, I measured improvements: https://github.com/dotnet/runtime/issues/53849.

I didn't make any changes to the CLR to fix the problems we saw then, but I just wanted to double-check. Maybe I'll have time to investigate sometime...

**Comment by BruceForstall** [comment]
For win-x64 Checked build, I measure a code size increase of:

clrjit.dll: 3,620,864 => 4,058,112
coreclr.dll: 13,232,640 => 14,578,176

For runtime, superpmi replay (which is almost 100% JIT time) is 11% faster with -O2 across our current collections.

**Comment by BruceForstall** [comment]
The OSX test failure is due to infra (out of disk space).

**Comment by BruceForstall** [comment]
@janvorli @jkotas @dotnet/runtime-infrastructure This change is ready to go. Since there are problems with `-O2` on x86 (https://github.com/dotnet/runtime/issues/59845), I simply changed it to only use `-O2` on non-x86 platforms.

Any comments?

**Review by jkotas — APPROVED** [review]
LGTM

**Comment by BruceForstall** [comment]
libraries failure is https://github.com/dotnet/runtime/issues/60097

**Pull request merged**
