### PR TITLE
Update branding to 6.0.2

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by wtgodbe** [comment]
@safern do we need to worry  about the failures here?

**Comment by safern** [comment]
I investigated, the tests are failing because the ref pack is not produced (because we don't always service them and I don't know if we need to service it for 6.0.2, we will see depending if there are any source gen fixes), this got broken when we moved to the new shared framework SDK, because of the removal of this: https://github.com/dotnet/runtime/commit/86d5d16d31ee46d619b4d9af510f307ed7da4846#diff-e6fa12be37bfb84da12f2bcd51e00bb6a8b346f3aa35a6c64ea0f7cb67acaf4dL37

I will need to fix that, but we also need to address this to tighten the test condition that it is expected that the ref pack shouldn't be produced: 
https://github.com/dotnet/runtime/issues/3836

**Comment by safern** [comment]
I've pushed a fix. @jkoritzinsky could you PTAL?

**Review by jkoritzinsky — APPROVED** [review]
Honestly I feel at this point that we can probably remove those tests and add comparable ones in Arcade itself. That's probably the best place for them to live anyway.

**Comment by safern** [comment]
> Honestly I feel at this point that we can probably remove those tests and add comparable ones in Arcade itself. That's probably the best place for them to live anyway.

Maybe we should update https://github.com/dotnet/runtime/issues/3836 to express that?

**Pull request merged**
