### PR TITLE
[mono] Remove some of the restrictions on constrained calls from

### LINKED ISSUE #58204: Attempting to JIT compile method in System.Text.Json tests on iOS devices
When running the System.Text.Json tests on iOS arm64 devices with full AOT we're seeing the following methods where it attempts to JIT compile them, causing an ExecutionEngineException:

```
bool System.Text.Json.Serialization.Converters.IAsyncEnumerableOfTConverter`2<System.Collections.Generic.IAsyncEnumerable`1<int>, int>:OnWriteResume (System.Text.Json.Utf8JsonWriter,System.Collections.Generic.IAsyncEnumerable`1<int>,System.Text.Json.JsonSerializerOptions,System.Text.Json.WriteStack&)
bool System.Text.Json.Serialization.Converters.IAsyncEnumerableOfTConverter`2<System.Text.Json.Serialization.Tests.CollectionTests/MockedAsyncEnumerable`1<int>, int>:OnWriteResume (System.Text.Json.Utf8JsonWriter,System.Text.Json.Serialization.Tests.CollectionTests/MockedAsyncEnumerable`1<int>,System.Text.Json.JsonSerializerOptions,System.Text.Json.WriteStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Collections.Concurrent.ConcurrentDictionary`2<int, int>, int, int>:Add (int,int modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Collections.Concurrent.ConcurrentDictionary`2<string, System.Text.Json.Serialization.Tests.StreamTests/ImmutableStructWithStrings>, string, System.Text.Json.Serialization.Tests.StreamTests/ImmutableStructWithStrings>:Add (string,System.Text.Json.Serialization.Tests.StreamTests/ImmutableStructWithStrings modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Collections.Concurrent.ConcurrentDictionary`2<string, int>, string, int>:Add (string,int modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Collections.Concurrent.ConcurrentDictionary`2<string, ulong>, string, ulong>:Add (string,ulong modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Collections.Generic.IDictionary`2<string, System.Nullable`1<System.DateTime>>, string, System.Nullable`1<System.DateTime>>:Add (string,System.Nullable`1<System.DateTime> modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Collections.Generic.IDictionary`2<string, int>, string, int>:Add (string,int modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Text.Json.Serialization.Tests.CollectionTests/DictionaryThatOnlyImplementsIDictionaryOfStringTValue`1<int>, string, int>:Add (string,int modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Text.Json.Serialization.Tests.GenericStructIDictionaryWrapper`2<string, string>, string, string>:Add (string,string modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Text.Json.Serialization.Tests.NullableTests/MyIDictionaryWrapper`1<System.Nullable`1<single>>, string, System.Nullable`1<single>>:Add (string,System.Nullable`1<single> modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
```

It's not clear why these fail, needs to be investigated.

/cc @lambdageek

### PR DESCRIPTION
**Pull request by vargaz**
gsharedvt methods.

Fixes https://github.com/dotnet/runtime/issues/58204.

### CODE REVIEW

**Review by lambdageek — DISMISSED** [review]

**Comment by lambdageek** [comment]
@vargaz Could you also remove the `[ActiveIssue]` from the tests in https://github.com/dotnet/runtime/pull/58276

**Comment by vargaz** [comment]
Reenabled, is CI actually testing these configurations ?

**Review by lambdageek — APPROVED** [review]

**Comment by lambdageek** [comment]
> Reenabled, is CI actually testing these configurations ?

Think so.  @akoeplinger  are they disabled somewhere else for another reason?

**Comment by lewing** [comment]
they are disabled in `src/libraries/tests.proj`

**Comment by srxqds** [comment]
I am sorry to ask again for backporting to 6.0? because the 6.0 is a LTS release, hope bug fixes can be merged more and more.

**Comment by akoeplinger** [comment]
To close the loop in this, we decided to hold off backporting this to 6.0 for now: https://github.com/dotnet/runtime/issues/58204#issuecomment-921936800

If you see an issue in a real project (not just constructed tests) then please file a new issue and we'll reconsider.

**Pull request merged**
