### PR TITLE
[workloads] Use the dual signed wix version for workload msis

### PR DESCRIPTION
**Pull request by lewing**
Fixes half of dotnet/runtime#59498

### CODE REVIEW

**Comment by lewing** [comment]
runtime (Libraries Test Run checked coreclr Linux_musl arm64 Release)

```
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 4)
    System.Text.RegularExpressions.Tests.RegexMatchTests.Match_ExcessPrefix(engine: SourceGenerated) [FAIL]
      Half-way through waiting for remote process.
      Timed out at 9/23/2021 3:35:31 PM after 60000ms waiting for remote process.
      	Process ID: 263
      	Handle: 1880
      	Name: dotnet
      	MainModule: /root/helix/work/correlation/dotnet
      	StartTime: 9/23/2021 3:34:31 PM
      	TotalProcessorTime: 00:01:03.0900000
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(224,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(57,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Text.RegularExpressions/tests/Regex.Match.Tests.cs(1095,0): 
``

**Review by steveisok — APPROVED** [review]

**Comment by lewing** [comment]
@stephentoub several lanes here are failing due to the regex source generator tests.

**Comment by ericstj** [comment]
@lewing did you want to add https://github.com/dotnet/runtime/pull/60008 to this PR as well?

**Review by ericstj — APPROVED** [review]
LGTM

**Review by joeloff — APPROVED** [review]

**Pull request merged**
