### PR TITLE
remove test references to archaic Linux versions

### PR DESCRIPTION
**Pull request by wfurt**
follow-up on #34361.
We no longer seems to build and run Drawing tests on Linux. 
But `GetRecentGdiPlusIsAvailable2` and `GetGdiPlusIsAvailableNotRedhat73` seems clearly outdated. 
I replaced them with `IsWindowsOrAtLeastLibgdiplus6` to be consistent and that seems to work OK on recent Linux distributions.  (in case we ever change our minds)

### CODE REVIEW

**Comment by jkotas** [comment]
We have deleted Systém.Drawing support fór Unix that used to depend on libgdiplus. All gdiplus related conditions ČSN be deleted.

**Comment by carlossanlop** [comment]
@wfurt does this need to be backported to 7.0 and 6.0? If yes, then this is a friendly reminder that Code Complete for the March Servicing Release is tomorrow Monday 13th EOD.

**Comment by jkotas** [comment]
This is cleanup PR. It is not a servicing candidate.

**Review by jkotas — APPROVED** [review]

**Comment by wfurt** [comment]
thanks for the help @jkotas.

**Pull request merged**
