### PR TITLE
JIT: refactor CSE to allow running greedy ML heuristic in release

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Revise things a bit so that we can run the greedy ML heuristic in release mode, with a built-in set of "good" parameters.

These parameters come from a policy gradient run over a 200 method training set, on the asp.net windows x64 collection.

Contributes to #92915.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL
cc @dotnet/jit-contrib 

This will be a bit painful to review as I moved a bunch of methods to a new intermediate class, and in doing so physically moved them in the file. For the most part things did not change (much).

The baked-in parameters may or may not be any good. We'll see. I will push an interim change to enable it by default.

**Comment by EgorBo** [comment]
Looking 👀

**Comment by AndyAyersMS** [comment]
> I will push an interim change to enable it by default.

Actually I'm going to hold off; let's get this bit merged and then I will put up a draft PR to flip it on by default.

**Review by EgorBo — APPROVED** [review]
As far as I can follow your changes, they look reasonable to me, LGTM!

**Comment by EgorBo** [comment]
> I will put up a draft PR to flip it on by default.

Are the diffs huge? 🙂

**Comment by AndyAyersMS** [comment]
> > I will put up a draft PR to flip it on by default.
> 
> Are the diffs huge? 🙂

The code size diffs don't look very good right now. One of the things I need to figure out is how to make sure that the secondary objectives don't get too crazy.
```
[09:50:54] 111,592 contexts with diffs (21,954 improvements, 83,583 regressions, 6,055 same size)
[09:50:54]   -244,440/+2,143,827 bytes
```

**Comment by AndyAyersMS** [comment]
This is a no diff change so failures above are unrelated.

**Comment by AndyAyersMS** [comment]
Draft PR to enable: https://github.com/dotnet/runtime/pull/98776

**Pull request merged**
