### PR TITLE
Make LocalEndPointTest and some Connect tests non-parallel

### LINKED ISSUE #52141: LocalEndPointTestIPv6Sync.TcpAcceptSocket_WhenServerBoundToSpecificAddress_LocalEPIsSame failing
Runfo Tracking Issue: [LocalEndPointTestIPv6Sync.TcpAcceptSocket_WhenServerBoundToSpecificAddress_LocalEPIsSame failing](https://runfo.azurewebsites.net/tracking/issue/148)
|Build|Definition|Kind|Run Name|
|---|---|---|---|
|[1116477](https://dev.azure.com/dnceng/public/_build/results?buildId=1116477)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 52128](https://github.com/dotnet/runtime/pull/52128)|net6.0-Linux-Debug-x64-Mono_release-(Centos.8.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-8-helix-20201229003624-c1bf759|
|[1113740](https://dev.azure.com/dnceng/public/_build/results?buildId=1113740)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 52046](https://github.com/dotnet/runtime/pull/52046)|net6.0-Linux-Debug-x64-Mono_release-(Debian.10.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-bfcd90a-20200121150006|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|1|2|2|

### LINKED ISSUE #55709: Connect_DualMode_DnsConnect_RetrievedEndPoints_Success - SocketException: Transport endpoint is not connected
Runfo Tracking Issue: [Connect_DualMode_DnsConnect_RetrievedEndPoints_Success test failure](https://runfo.azurewebsites.net/tracking/issue/152)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1237035](https://dev.azure.com/dnceng/public/_build/results?buildId=1237035)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-20210106155927-56c6673|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-aca2856414854cae80/System.Net.Sockets.Tests/console.c719c70f.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-03T07%25253A46%25253A40Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D8B%25252FZg5rur2HT2vreMjst9%25252BlZZ3SuEPJdXifiUMvtF3c%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-aca2856414854cae80/System.Net.Sockets.Tests/298b85ef-d48c-410c-916b-41aa6fb16fec.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-03T07%25253A46%25253A40Z%2526sr%253Dc%2526sp%253Drl%2526sig%253D8B%25252FZg5rur2HT2vreMjst9%25252BlZZ3SuEPJdXifiUMvtF3c%25253D)|
|[1234963](https://dev.azure.com/dnceng/public/_build/results?buildId=1234963)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-Mono_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-59f41ab90e374793bf/System.Net.Sockets.Tests/console.34541f88.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T15%25253A57%25253A41Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DwNg9i1LaF910B5uIuqRg4GpR7EpjF623YjzX2AkQHRw%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-59f41ab90e374793bf/System.Net.Sockets.Tests/4a6b6652-617c-4a71-93be-d77f9207db4c.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-02T15%25253A57%25253A41Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DwNg9i1LaF910B5uIuqRg4GpR7EpjF623YjzX2AkQHRw%25253D)|
|[1232399](https://dev.azure.com/dnceng/public/_build/results?buildId=1232399)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55499](https://github.com/dotnet/runtime/pull/55499)|net6.0-Linux-Debug-x64-Mono_release-SLES.15.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55499-merge-a01bc880304a4f98b0/System.Net.Sockets.Tests/console.b7a5a69a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T11%25253A20%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DNfN2rqeohehv%25252FqVuB2OUxqyeMrXt765elCwKiJyvUkY%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55499-merge-a01bc880304a4f98b0/System.Net.Sockets.Tests/1f1f2753-784c-47d2-b6a9-3b681f882ee5.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-08-01T11%25253A20%25253A02Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DNfN2rqeohehv%25252FqVuB2OUxqyeMrXt765elCwKiJyvUkY%25253D)|
|[1231144](https://dev.azure.com/dnceng/public/_build/results?buildId=1231144)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 55446](https://github.com/dotnet/runtime/pull/55446)|net6.0-Linux-Debug-x64-Mono_release-SLES.15.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55446-merge-890d49c84da44d6594/System.Net.Sockets.Tests/console.4f3ab81d.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-07-30T17%25253A58%25253A19Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DccUJCMl66x31SYJSBxzVVO2blQyNd76O9Ia6EQdr7N4%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55446-merge-890d49c84da44d6594/System.Net.Sockets.Tests/b2da68bd-968a-485e-bb65-73a41a1fe036.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-07-30T17%25253A58%25253A19Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DccUJCMl66x31SYJSBxzVVO2blQyNd76O9Ia6EQdr7N4%25253D)|
|[1230745](https://dev.azure.com/dnceng/public/_build/results?buildId=1230745)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net6.0-Linux-Release-x64-CoreCLR_release-SLES.15.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ada702dc965a4f6d90/System.Net.Sockets.Tests/console.2256b293.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-07-30T06%25253A19%25253A51Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DyqyOejJfkABZ0zRWKpEoVWLSKXz67H3IQH0wK4f9J7E%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ada702dc965a4f6d90/System.Net.Sockets.Tests/784e6e25-1f84-4adc-afd7-7e3b221865f4.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-07-30T06%25253A19%25253A51Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DyqyOejJfkABZ0zRWKpEoVWLSKXz67H3IQH0wK4f9J7E%25253D)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|5|5|

Failure

```
System.Net.Sockets.SocketException : Transport endpoint is not connected

   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 3712
   at System.Net.Sockets.Socket.get_RemoteEndPoint() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 355
   at System.Net.Sockets.Tests.Connect`1.Connect_DualMode_DnsConnect_RetrievedEndPoints_Success() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/Connect.cs:line 134
--- End of stack trace from previous location ---
```

Failures 5/20-7/19 (incl. PRs):

Day | Run | OS | Runtime | Namespace
-- | -- | -- | -- | --
6/29 | PR #52237 | Fedora.30.Amd64.Open | Mono | ConnectSync
6/29 | Official run | Ubuntu.1910.Amd64.Open | CoreCLR | ConnectEap
6/30 | Official run | Debian.9.Amd64.Open | Mono | ConnectSync
7/1 | Official run | SLES.15.Amd64.Open | Mono | ConnectSync
7/1 | PR #54755 | Debian.10.Amd64.Open | CoreCLR | ConnectTask
7/2 | PR #55035 | RedHat.7.Amd64.Open | CoreCLR | ConnectSync
7/2 | PR #54845 | RedHat.7.Amd64.Open | CoreCLR | ConnectCancellableTask
7/5 | PR #55182 | Debian.9.Amd64.Open | Mono | ConnectEap
7/9 | PR #55354 | Centos.8.Amd64.Open | Mono | ConnectCancellableTask
7/10 | PR #54985 | Ubuntu.1804.ArmArch.Open | Mono | ConnectTask
7/10 | PR #55446 | SLES.15.Amd64.Open | Mono | ConnectTask
7/12 | PR #55499 | SLES.15.Amd64.Open | Mono | ConnectTask
7/14 | PR #55621 | Centos.8.Amd64.Open | Mono | ConnectSync
7/14 | Official run | Ubuntu.1804.ArmArch.Open | CoreCLR | ConnectTask
7/14 | PR #55644 | Centos.8.Amd64.Open | CoreCLR | ConnectSyncForceNonBlocking
7/16 | PR #55811 | SLES.15.Amd64.Open | Mono | ConnectSync
7/16 | PR #54845 | SLES.15.Amd64.Open | CoreCLR | ConnectSync
7/17 | Official run | Debian.9.Amd64.Open | CoreCLR | ConnectSync
7/19 | PR #55939 | Debian.10.Amd64.Open | Mono | ConnectTask
7/19 | PR #55916 | Centos.8.Amd64.Open | CoreCLR | ConnectApm
7/19 | PR #55956 | Fedora.32.Amd64.Open | Mono | ConnectEap
7/19 | PR #54845 | Centos.8.Amd64.Open | CoreCLR | ConnectApm

### LINKED ISSUE #56042: Test failure TcpAcceptSocket_WhenServerBoundToWildcardAddress_LocalEPIsSpecific - different port
```
System.Net.Sockets.Tests.LocalEndPointTestIPv4Sync.TcpAcceptSocket_WhenServerBoundToWildcardAddress_LocalEPIsSpecific [FAIL]
      Assert.Equal() Failure
      Expected: 127.0.0.1:39706
      Actual:   127.0.0.1:39708
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/LocalEndPointTest.cs(137,0): at System.Net.Sockets.Tests.LocalEndPointTest`1.TcpAcceptSocket_WhenServerBoundToWildcardAddress_LocalEPIsSpecific()
        --- End of stack trace from previous location ---
```
log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54845-merge-176f2e0dc3214643a1/System.Net.Sockets.Tests/console.54af2133.log?sv=2019-07-07&se=2021-08-09T16%3A11%3A35Z&sr=c&sp=rl&sig=TwHCJtlbhuryivUNOBcc5mLYFViBbacNt4UMjBEWfhg%3D
build: https://dev.azure.com/dnceng/public/_build/results?buildId=1246649&view=logs&j=d10aa0b1-a1a0-5e3f-d20a-a36b4319a21f&t=59f04130-a1ae-5fc8-21eb-448a87f814b9

### PR DESCRIPTION
**Pull request by antonfirsov**
There is some chance that sockets in these tests are connecting to, or being connected by sockets of other, unrelated parallel tests.

Fixes #52141. Hopefully fixes #55709 too, although I don't have a proof that the reported socket error can be the result of unrelated accepts. We can reopen the issues if we'll keep experiencing them in the CI.

Fixes #52141
Fixes #55709
Fixes #56042

### CODE REVIEW

**Comment by wfurt** [comment]
do you know how much time it added to complete run @antonfirsov? (just curious)

**Comment by antonfirsov** [comment]
`< 100 ms` for LocalEndPointTest. Haven't checked the Connect tests.

**Comment by karelz** [comment]
@antonfirsov I updated top post with "Fixes #number" to trigger auto-close when this is merged.

**Review by MihaZupan — APPROVED** [review]

**Comment by karelz** [comment]
Test failures seem to be unrelated: (re-running just in case)
- https://github.com/dotnet/runtime/pull/56399/checks?check_run_id=3174766497
  - `Tests failed: /root/runtime/artifacts/TestResults/Release/AppHost.Bundle.Tests_net6.0_x64.html [net6.0|x64]`
- https://github.com/dotnet/runtime/pull/56399/checks?check_run_id=3174211175
```
Failed to retrieve information about 'System.ComponentModel.TypeConverter.TestData' from remote source 'https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/1a5f89f6-d8da-4080-b15f-242650c914a8/nuget/v3/flat2/system.componentmodel.typeconverter.testdata/index.json'.
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.FindPackagesByIdAsync(String id, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken) in NuGet.Protocol.dll:token 0x6000392+0x2dc
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.EnsurePackagesAsync(String id, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken) in NuGet.Protocol.dll:token 0x6000391+0x13f
   at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.DoesPackageExistAsync(String id, NuGetVersion version, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken) in NuGet.Protocol.dll:token 0x6000390+0x17c
   at NuGet.Commands.SourceRepositoryDependencyProvider.FindLibraryCoreAsync(LibraryRange libraryRange, SourceCacheContext cacheContext, ILogger logger, CancellationToken cancellationToken) in NuGet.Commands.dll:token 0x6000459+0x379
   at NuGet.Commands.SourceRepositoryDependencyProvider.<>c__DisplayClass19_0.<<FindLibraryAsync>b__0>d.MoveNext() in NuGet.Commands.dll:token 0x6000a2d+0xb6
```

**Pull request merged**
