### PR TITLE
[release/6.0] Restore FP pairs when unwinding in ARM64

### PR DESCRIPTION
**Pull request by hoyosjs**
# Description

This change ensures that unwinding codes of the type `save_fregp` that are emitted for sequences like `stp dX, dY, [sp, #Z]` are correctly unwound. Without this, non-volatile registers are not correctly restored and frames above the handler frames can experience data corruption in the case of an exception in Unix based systems.

# Customer Impact

Corruptions caused by this bug are hard to diagnose and lead to silent data loss. 

# Regression

No.

# Testing

Added regression test that fails without the change.

# Risk

Very low - equivalent fix exists in the OS tree. 

# Package authoring signed off?

N/A

### CODE REVIEW

**Review by jeffschwMSFT — APPROVED** [review]
Approved.  We are considering for 6.0.x

**Comment by jeffschwMSFT** [comment]
@hoyosjs please ensure that this has a code review.

**Review by davidwrighton — APPROVED** [review]
This is a good targetted fix for .NET 6.0

**Comment by hoyosjs** [comment]
This test is failing even against 6.0.5 on lab machines for Windows (basically without this change. This code path doesn't get used on Windows, which means the OS unwinder in the lab machines is likely not patched? At least for DDARM64-173, although that one reports having (Windows 10.0.19044.1645). I've seen it also fail in `10.0.19041.1415`. This passes on windows 11 though. I could turn the test off for Windows given that it's only testing the OS at that point, but feels odd to be in that spot.

**Comment by mmitche** [comment]
Reminder that code complete is today.

**Comment by davidwrighton** [comment]
@hoyosjs I've confirmed that the OS unwinder does not have this fix on that version of Windows. Please just turn the test off for Windows, and we'll figure out what to do to best handle the situation later.

**Comment by jeffschwMSFT** [comment]
@hoyosjs are we still investigating PR failures, or are we ready to merge?

cc @carlossanlop

**Pull request merged**
