### PR TITLE
Add wasm path

### PR DESCRIPTION
**Pull request by DrewScoggins**
When trying to fix AOT WASM SOD runs I forgot to include the actual path variable. This fixes that.

### CODE REVIEW

**Review by billwert — APPROVED** [review]
Approved modulo uncommenting all the tests

**Comment by DrewScoggins** [comment]
Yeah, I realized that the queue is too backed up, so I will just check this in then check to make sure it works.

**Review by Lxiamail — APPROVED** [review]

**Comment by missymessa** [comment]
> /azp run license/cla

I think you're going to need to close and reopen the PR. Since that status isn't an Azure DevOps pipeline to run.

**Pull request merged**
