### PR TITLE
Rename superpmi-asmdiffs -> superpmi-diffs

### PR DESCRIPTION
**Pull request by jakobbotsch**
In anticipation of using this pipeline more generally for any base-diff JIT
comparison in JIT PRs.

I suppose the most frictionless way is to create a new pipeline that points to the new YAML file and delete the old one after merging.

cc @dotnet/jit-contrib @kunalspathak

### CODE REVIEW

**Comment by jakobbotsch** [comment]
The new pipeline is https://dev.azure.com/dnceng/public/_build?definitionId=1135&_a=summary

**Comment by jakobbotsch** [comment]
> I suppose the most frictionless way is to create a new pipeline that points to the new YAML file and delete the old one after merging.

I think instead I will delete the new pipeline and point the old pipeline at the right file once this is merged so that we retain the history of that pipeline. Just needed to ensure that the pipeline still worked which it did.

**Comment by kunalspathak** [comment]
>  so that we retain the history of that pipeline

Yes, was about to say that. We want to maintain the history.

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by jakobbotsch** [comment]
Just want to give @BruceForstall a chance to comment on this renaming before merging.

**Review by BruceForstall — APPROVED** [review]
LGTM

fwiw, you could imagine merging the `runtime-coreclr superpmi-asmdiffs-checked-release` pipeline with this one, but I don't think we should because (1) "base" and "diff" come from the same git hash, not a different baseline + diff. (2) We don't need to run it frequently, even though we could run it on a per-JIT-PR basis, to reduce cost.

**Pull request merged**
