### PR TITLE
Add exception interop test for validating native exception interop on Windows + CoreCLR.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Add a regression test for exception interop to make sure that we have good test coverage for #70109

### CODE REVIEW

**Review by AaronRobinsonMSFT — COMMENTED** [review]
LGTM. I'd like to see what @janvorli thinks. I know we have a few tests here and there already. This battery does make me happy but curious if we can remove others and add them to this or fold these into an existing location.

**Comment by AaronRobinsonMSFT** [comment]
@janvorli Any thoughts on this? The value is good but I'd like to avoid duplication if you can point where we already do this or perhaps older tests that can be replaced by what Jeremy has done here.

**Comment by janvorli** [comment]
I am sorry for a late response. There were few weeks when github stopped sending me notifications on comments and I have not realized it. We don't have any tests for this, so I'll be happy to get them in.

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Pull request merged**
