### PR TITLE
Fix GCStress disabling of ParallelCrashTester

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Review by jakobbotsch — APPROVED** [review]

**Comment by VSadov** [comment]
Can we also disable JIT/Directed/lifetime/lifetime2  in stress scenarios?
It looks like it is sensitive to JIT optimizations  (it tests if things that are rooted by locals get finalized after assigning null)

I have seen it fail randomly, depending on platform or the state of "DOTNET_JITStress"

**Comment by BruceForstall** [comment]
> Can we also disable JIT/Directed/lifetime/lifetime2 in stress scenarios? It looks like it is sensitive to JIT optimizations (it tests if things that are rooted by locals get finalized after assigning null)
> 
> I have seen it fail randomly, depending on platform or the state of "DOTNET_JITStress"

That would be fine, if setting `DOTNET_JitStress` or related can impact the test. However, assigning a GC pointer `null` and assuming it gets collected is a classic bad test because the JIT has the freedom to extend variable lifetimes to the end of a function.

Anyway, if you want to do this, use `<JitOptimizationSensitive>true</JitOptimizationSensitive>` in the test proj file.

**Comment by VSadov** [comment]
> Anyway, if you want to do this, use `<JitOptimizationSensitive>true</JitOptimizationSensitive>` in the test proj file.

It looks like it already has that, but still runs in GC stress runs. Is there something else missing?

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Needed for JitOptimizationSensitive, GC.WaitForPendingFinalizers -->
    <!-- See https://github.com/dotnet/runtime/issues/68529 -->
    <RequiresProcessIsolation>true</RequiresProcessIsolation>

    <CLRTestPriority>1</CLRTestPriority>
  </PropertyGroup>
  <PropertyGroup>
    <DebugType>None</DebugType>
    <Optimize>True</Optimize>
    <JitOptimizationSensitive>True</JitOptimizationSensitive>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="lifetime2.cs" />
  </ItemGroup>
</Project>

```

**Comment by VSadov** [comment]
For example I see a failure in https://[helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-99339-merge-20183ec546bc48da99/Directed_3.0.1/1/console.36a1b2d6.log?helixlogtype=result](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-99339-merge-20183ec546bc48da99/Directed_3.0.1/1/console.36a1b2d6.log?helixlogtype=result)

However it only sets 
```
export DOTNET_TieredCompilation=0
export DOTNET_DbgEnableMiniDump=1
export DOTNET_EnableCrashReport=1
export DOTNET_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export DOTNET_GCStress=0xC
```

It does not set DOTNET_JitStress and that probably explains why the test ran.

**Comment by BruceForstall** [comment]
JitOptimizationSensitive only cares about:

```
DOTNET_JitStress
DOTNET_JitStressRegs
DOTNET_JITMinOpts
DOTNET_TailcallStress
```

If you don't want it to run in GCStress, use `<GCStressIncompatible>true</GCStressIncompatible>`

**Pull request merged**
