### PR TITLE
Disable apphost tests on Linux

### PR DESCRIPTION
**Pull request by agocke**
There is a race condition somewhere in these tests which is causing #44657

### CODE REVIEW

**Comment by agocke** [comment]
We just need a corresponding PR to enable these tests in staging, then we can move forward.

**Comment by danmosemsft** [comment]
> We just need a corresponding PR to enable these tests in staging

That isn’t done in this same repo?

**Comment by agocke** [comment]
@danmosemsft It is, and the change could just be another commit in this PR, I just don't know how to do it. I think @safern was working on enabling the staging build?

**Comment by safern** [comment]
> I think @safern was working on enabling the staging build?

The staging build already exists, it is defined in `runtime-staging.yml`, however I'm working on making it simpler to move things around to the staging pipeline as right now you need to delete things from one yml and move it to another which is less than ideal.

**Review by safern — APPROVED** [review]

**Comment by agocke** [comment]
So is this test already running in the staging PR on Linux?

**Comment by safern** [comment]
> So is this test already running in the staging PR on Linux?

No, the staging pipeline is only running tests on iOS and Android (devices so arm64).

**Comment by agocke** [comment]
@safern How would I replicate the unit test behavior? Run the installer tests on Linux amd64?

**Comment by safern** [comment]
Merging as the tests are now running in staging pipeline for Linux x64.

**Pull request merged**
