### PR TITLE
Port commits from PR-48140 to dotnet 5.0.

### PR DESCRIPTION
**Pull request by MatthewJohn**
Do not use /dev/zero to mmap anonymous memory

This includes:

 * 88981031b2613e8e2d1b30147efbf95225459240 -  remove HAVE_MMAP_DEV_ZERO config
 * 530bc84b0ffc25c21671426a341da2a6ada89898 -  Always use MAP_ANON
 * c03ff023aa31620f2e6e66c6589e7ccf58a57cec -  return void

We believe we were affected by this bug in dotnet 5, but see the fix was only merged into dotnet 6.

This commit backports the changes in https://github.com/dotnet/runtime/pull/48140

I want to raise this to ask the question, why was this not originally ported to dotnet 5 - does backporting this change to dotnet 5 seem outrageous for any reason? Please note, I have **not** tested this in any way.
Due to the change in paths from dotnet 6 to dotnet 5, I wasn't easily able to cherry-pick the original comits. But, if required, I could take another look at doing so!

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=66087) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=66087) before we can accept your contribution.<br/><br/>:x: MatthewJohn [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=66087)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=66087) it.</sub>

**Comment by jkotas** [comment]
.NET 5 support ends in two months (https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core).

Is there anything preventing you from upgrading to .NET 6 instead? You will need to do that soon to run on supported version.

**Comment by MatthewJohn** [comment]
> .NET 5 support ends in two months (https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core).
> 
> Is there anything preventing you from upgrading to .NET 6 instead? You will need to do that soon to run on supported version.

I assume there isn't too much reason for not upgrading. But, whilst attempting to resolve an issue caused by this, we (not me personally) wanted to track down the exact cause and to test whether this did fix this one issue, without covering it up with thousands of other changes. And so, on the back of thinking what the best direction was, we wondered why this change didn't exist in .NET 5 and, if it's just because it wasn't originally targeted at it, could it be in there :)

The other take on it was, if there are other dotnet 5 apps that are affected by this bug, then perhaps porting the fix will help then (even if the user isn't aware of it existing).

**Comment by jkotas** [comment]
> we wondered why this change didn't exist in .NET 5

We only port security fixes and high-severity bugs (for example, blocking bugs with no workarounds) to past releases. 99%+ of bug fixes are not backported to past releases.

**Comment by akoeplinger** [comment]
I agree that this doesn't look like it meets the bar for a backport at this point.

**Comment by MatthewJohn** [comment]
No problem, thanks for your time

**Pull request closed without merging**
