### PR TITLE
JIT: Fix ordering of type initialization and stsfld 

### LINKED ISSUE #72354: Type initializer call ordering w.r.t. static field stores does not look right
Reproduction:
```cs
using System;
using System.Runtime.CompilerServices;

Problem();

[MethodImpl(MethodImplOptions.NoInlining)]
static void Problem()
{
    [MethodImpl(MethodImplOptions.NoInlining)]
    static int Call() => throw new Exception("Thrown from 'Call'");

    var a = Call();
    ClassWithCctor.StaticField = a;
}

class ClassWithCctor
{
    public static int StaticField;
    static ClassWithCctor() => throw new Exception("Thrown from 'ClassWithCctor'");
}
```
Compile and run.

Expected result: the exception from `Call` is thrown.

Actual result: the type initializer throws instead:
```scala
Unhandled exception. System.TypeInitializationException: The type initializer for 'ClassWithCctor' threw an exception.
 ---> System.Exception: Thrown from 'ClassWithCctor'
```

Cause - the insertion point of the helper here:

https://github.com/dotnet/runtime/blob/aafa91036e1efd3d4dcb67eeb261cb6d8f774685/src/coreclr/jit/importer.cpp#L16140-L16143

category:correctness
theme:basic-cq

### PR DESCRIPTION
**Pull request by markples**
Insertion of the type initializer before the tree for a `stsfld` could reorder them inappropriately.  This includes those computation in the spill check.

Fixes #72354.

### CODE REVIEW

**Comment by markples** [comment]
need to check the code size regressions

**Comment by markples** [comment]
So far all are spills of a value around a type initializer call (`static = computation`).  This is exactly the purpose of this change, though presumably the order generally doesn't matter in practice (can't be aliasing as any read/write of static would have already triggered the initialization, so it's just "real" side effects).

**Comment by markples** [comment]
The previous comment is incorrect.  While the particular static should be fine, the computation and type initializer could be accessing a static from some other type and ordering could matter there.

**Comment by markples** [comment]
@dotnet/jit-contrib This is the fix from long ago that I held off on because I was looking at the small code size regressions.  For x64, they were mostly minopts and were due to splitting a tree as is needed because the type initialization needs to go in the middle of it.  arm64 numbers follow the same pattern.

**Review by AndyAyersMS — APPROVED** [review]
Always hard to this kind of fix without some code size impact.

**Pull request merged**
