### PR TITLE
Move publishing off hosted ADO machines

### PR DESCRIPTION
**Pull request by lukas-lansky**
Just like https://github.com/dotnet/runtime/pull/48521, but for 5.0 servicing that manifests [the same error](https://dnceng.visualstudio.com/internal/_build/results?buildId=1027107&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a&l=61)

### CODE REVIEW

**Review by MattGal — APPROVED** [review]
No objection to continuing to do this workaround but we need to check with @epananth and see if we can help her get this working on hosted again soon as this was supposed to be more temporary than it has proven to be.

**Review by mmitche — APPROVED** [review]

**Review by epananth — APPROVED** [review]

**Comment by lukas-lansky** [comment]
```
    System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChainCustomTrustStore(chainBuildsSuccessfully: False, chainFlags: UntrustedRoot, testArguments: TrustedIntermediateUntrustedRoot) [FAIL]
      System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
      Stack Trace:
        /_/src/libraries/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509ChainElementCollection.cs(49,0): at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index)
        /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs(290,0): at System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChainCustomTrustStore(Boolean chainBuildsSuccessfully, X509ChainStatusFlags chainFlags, BuildChainCustomTrustStoreTestArguments testArguments)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(384,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChainCustomTrustStore(chainBuildsSuccessfully: True, chainFlags: NoError, testArguments: UntrustedIntermediateTrustedRoot) [FAIL]
      System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
      Stack Trace:
        /_/src/libraries/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509ChainElementCollection.cs(49,0): at System.Security.Cryptography.X509Certificates.X509ChainElementCollection.get_Item(Int32 index)
        /_/src/libraries/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs(290,0): at System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChainCustomTrustStore(Boolean chainBuildsSuccessfully, X509ChainStatusFlags chainFlags, BuildChainCustomTrustStoreTestArguments testArguments)
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(384,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[...]
```

This seems like https://github.com/dotnet/runtime/issues/48406.

**Pull request merged**
