### PR TITLE
[IGNORE][wasm] testing perf pipeline

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Comment by radical** [comment]
@dougbu `runtime-wasm-perf` was getting triggered for all PRs. Then I merged https://github.com/dotnet/runtime/pull/92799 with `pr:` section, and `trigger: none`. Now, the pipeline is not getting triggered for PRs by default, like this one which has a change in one the included paths.

Do I need a `trigger:` also? Looking at the docs `trigger` seems to be for running off the repo branches like a rolling build, and `pr` is for running the pipeline on PRs. Any idea what I'm missing here?

**Comment by dougbu** [comment]
@radical @AlitzelMendez re-ticked the `Require a team member's comment before building a pull request` checkbox; I'm not sure why. @AlitzelMendez❔

that checkbox is off again

**Pull request closed without merging**
