### PR TITLE
Add PR trigger for runtime performance

### PR DESCRIPTION
**Pull request by DrewScoggins**

### CODE REVIEW

**Review by trylek — APPROVED** [review]
LGTM, thanks for doing this. I wonder whether we need to run perf runs against installer-only changes but perhaps it's not that much of a concern.

**Comment by DrewScoggins** [comment]
These don't actually upload to the system. These are closer to correctness tests for our perf suite. So we only run one iteration, don't upload, etc.

**Comment by trylek** [comment]
Sounds good, thanks for clarifying!

**Comment by stephentoub** [comment]
The title of the PR excites me.  What happens when we trigger this?

**Comment by DrewScoggins** [comment]
> The title of the PR excites me. What happens when we trigger this?

> These don't actually upload to the system. These are closer to correctness tests for our perf suite. So we only run one iteration, don't upload, etc.

**Comment by stephentoub** [comment]
Ah.  Ok.  Well, it's a start :)

**Comment by akoeplinger** [comment]
I see that build definition running on Mono-only changes too, is that expected/desirable?

**Pull request merged**
