### PR TITLE
Use the native cross compilers on win-arm64

### PR DESCRIPTION
**Pull request by lewing**

### CODE REVIEW

**Comment by steveisok** [comment]
This is pending win-arm64 cross compiler support from @directhex.

**Comment by directhex** [comment]
It's done, but we have no means to CI effectively. That's the problem Sent from my iPhoneOn Sep 21, 2023, at 7:24 PM, Steve Pfister ***@***.***> wrote:﻿
This is pending win-arm64 cross compiler support from @directhex.

**Comment by lewing** [comment]
are the packages being built and published? should we turn this on in head and let people try out the builds?  we could stand up a wbt win-arm64 lane for smoke tests if we have hosts

**Comment by steveisok** [comment]
We will need to do an official build to validate. I do think there's value in having this in main.

**Comment by lewing** [comment]
kicked off an official build, we'll see how it goes

**Comment by lewing** [comment]
@steveisok looks green on the official build

**Review by radical — APPROVED** [review]

**Comment by steveisok** [comment]
> @steveisok looks green on the official build, should we merge and try it out?

YOLO!

**Comment by akoeplinger** [comment]
FYI this was already done in https://github.com/dotnet/runtime/pull/89651. The main commit shows 0 changes 😄

**Pull request merged**
