### PR TITLE
Disable /OPT:ICF on windows, it merges identical functions breaking i…

### PR DESCRIPTION
**Pull request by vargaz**
…call symbol lookup.

### CODE REVIEW

**Comment by lewing** [comment]
fixes https://github.com/dotnet/runtime/issues/49588

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
runtime (Libraries Test Run release mono Linux x64 Debug) failure is #49583

**Comment by jaykrell** [comment]
1. What is the size cost?
2. How about you make the afflicted functions not identical? For example, give them some static data that they use in a pointless way.
3. Can it be made to work despite the functions being identical?

gcc has an option or attribute to consider address-taken functions not unique, and avoid folding them.
This would fix that. But Visual C++ doesn't have that feature. Alas.

I think SQL Server has this very same problem as Mono, and also disables ICF to workaround it. Alas.

**Comment by jaykrell** [comment]
https://developercommunity.visualstudio.com/t/link-opticf-is-too-aggressive/1369631

**Comment by lewing** [comment]
runtime (Libraries Test Run release mono windows x64 Debug) is https://github.com/dotnet/runtime/issues/49569

**Comment by lewing** [comment]
> 1. What is the size cost?
> 2. How about you make the afflicted functions not identical? For example, give them some static data that they use in a pointless way.
> 3. Can it be made to work despite the functions being identical?
> 
> gcc has an option or attribute to consider address-taken functions not unique, and avoid folding them.
> This would fix that. But Visual C++ doesn't have that feature. Alas.
> 
> I think SQL Server has this very same problem as Mono, and also disables ICF to workaround it. Alas.

It is a correctness fix with schedule impact so I'm landing it now but I opened an issue to reexamine the optimization before release.

**Comment by jaykrell** [comment]
Understood and I expect no relief upstream but couldn't ignore it, sorry.

**Comment by AntonLapounov** [comment]
Note that in VM we use the special `FCUnique` macro to prevent some otherwise identical functions from folding. See #39810 for an example.

**Pull request merged**
