### PR TITLE
JIT: Fix liveness for dependently promoted TYP_LONGs on x86

### LINKED ISSUE #73559: [jitstress] System.Runtime.Intrinsics.Tests.Vectors.Vector64Tests.Vector64Int64SumTest fails frequently on win-x86
E.g. https://dev.azure.com/dnceng/public/_build/results?buildId=1920081&view=ms.vss-test-web.build-test-results-tab&runId=49735324&resultId=133395&paneView=debug

### PR DESCRIPTION
**Pull request by jakobbotsch**
We were only handling uses of promoted locals when varTypeIsStruct(lcl)
was true. For TYP_LONG promoted locals on x86 it is not.

Fix #73559

### CODE REVIEW

**Review by SingleAccretion — APPROVED** [review]
LGTM. I was fixing the same issues the other day for multi-reg longs and wondered whether the current state is correct. Turns out not.

There is also this code in ref counting which I think should use the same treatment:

https://github.com/dotnet/runtime/blob/d63c65d7cf4b102aa394837b2ba609c67b89506f/src/coreclr/jit/compiler.hpp#L1953-L1964

Many of these conditions look a bit pointless, they could just be checking promotion type and/or `lvPromoted` directly, but that's not a 7.0 issue, naturally.

**Review by kunalspathak — COMMENTED** [review]
LGTM. I am wondering if these 2 places also need fixup?

https://github.com/dotnet/runtime/blob/9865cc7a89a4a613a47986b8268a10bc37adbd65/src/coreclr/jit/codegencommon.cpp#L3387

https://github.com/dotnet/runtime/blob/9865cc7a89a4a613a47986b8268a10bc37adbd65/src/coreclr/jit/compiler.hpp#L1906

**Comment by jakobbotsch** [comment]
> LGTM. I am wondering if these 2 places also need fixup?
> 
> https://github.com/dotnet/runtime/blob/9865cc7a89a4a613a47986b8268a10bc37adbd65/src/coreclr/jit/codegencommon.cpp#L3387
> 
> https://github.com/dotnet/runtime/blob/9865cc7a89a4a613a47986b8268a10bc37adbd65/src/coreclr/jit/compiler.hpp#L1906

I don't think it would hurt, but it is not necessary today. We never promote TYP_LONG parameters independently (first one) and there is a `!= TYP_STRUCT` check in the code that follows that covers the second one. I will leave it to avoid rerunning CI.

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by jakobbotsch** [comment]
Actually, CI looked particularly fussy so I updated them too to also rerun it.

**Pull request merged**
