### PR TITLE
Add OSPlatform.Browser and Architecture.Wasm

### PR DESCRIPTION
**Pull request by lewing**
Implements consensus in #33328
mirrors change in https://github.com/mono/mono/pull/19482

### CODE REVIEW

**Comment by stephentoub** [comment]
@terrajobst, is https://github.com/dotnet/runtime/issues/33328 approved / final decision?

**Review by stephentoub — COMMENTED** [review]
Product changes LGTM, assuming the APIs are approved.  Are there tests that can be added?

**Comment by terrajobst** [comment]
> @terrajobst, is #33328 approved / final decision?

I've marked #33328 as ready for review again. Once approved this can go in.

**Review by jkotas — APPROVED** [review]

**Comment by terrajobst** [comment]
Since #33328 is now api-approved I've removed the blocked label

**Review by terrajobst — APPROVED** [review]

**Pull request merged**
