### PR TITLE
JIT: Enable addressing modes for gc types

### PR DESCRIPTION
**Pull request by EgorBo**
Example:
```csharp
object Test(object[] args, int i) => args[i];
```
Codegen diff:
```diff
; Method Program:Test(System.Object[],int):System.Object:this
G_M59644_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
G_M59644_IG02:
            ldr     w0, [x1,#8]
            cmp     w2, w0
            bhs     G_M59644_IG04
-           ubfiz   x0, x2, #3, #32
-           add     x0, x0, #16
-           ldr     x0, [x1, x0]
+           add     x0, x1, #16
+           ldr     x0, [x0, w2, UXTW #3]
G_M59644_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
G_M59644_IG04:
            bl      CORINFO_HELP_RNGCHKFAIL
            brk_windows #0
```
Some nice [diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1824552&view=ms.vss-build-web.run-extensions-tab)

### CODE REVIEW

**Comment by kunalspathak** [comment]
Can you double check if it fixes example in https://github.com/dotnet/runtime/issues/67981?

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by EgorBo** [comment]
> Can you double check if it fixes example in #67981?

hm.. no it doesn't change codegen for that sample, although I am not sure I understand the issue, will comment it

**Comment by EgorBo** [comment]
Improvements on win-arm64 https://github.com/dotnet/perf-autofiling-issues/issues/6343 (likely related)

**Pull request merged**
