### PR TITLE
Force building of Mono manifest packages when building via source-build

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by ViktorHofer** [comment]
cc @tmds as that's the opposite of what you are doing in https://github.com/dotnet/runtime/pull/81480. Should we also inline this property into the repo's config?

**Comment by tmds** [comment]
> cc @tmds as that's the opposite of what you are doing in https://github.com/dotnet/runtime/pull/81480. Should we also inline this property into the repo's config?

Yes, that makes it easier to reproduce the source-build configuration from `./build.sh` without going through arcade, see https://github.com/dotnet/runtime/pull/81480#issuecomment-1420572960.

**Comment by ViktorHofer** [comment]
@directhex please move that property out of SourceBuild.props and into another location, i.e. Directory.Build.props before Subsets.props are imported.

**Comment by directhex** [comment]
@ViktorHofer so conditionally set the ForceBuildMobileManifests property, based on DotNetBuildFromSource, in Directory.Build.Props?

**Comment by ViktorHofer** [comment]
Yes, exactly. But before the Subsets.props import as that file reads the property.

**Comment by directhex** [comment]
E2E tested locally w/ VMR

**Review by ViktorHofer — APPROVED** [review]

**Pull request merged**
