### PR TITLE
Add support for variance to IDIC

### LINKED ISSUE #58619: Support variance in IDynamicInterfaceCastable
We might be able to allow interfaces that are compatible through variance to be returned from Getinterfaceimplementation.

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Fixes #58619 

/cc @MichalStrehovsky @elinor-fung @jkoritzinsky @davidwrighton

### CODE REVIEW

**Comment by AaronRobinsonMSFT** [comment]
I think we should consider backporting this support to .NET 5 and/or .NET 6 for C#/WinRT. @jkoritzinsky Based on your experience, would this support be helpful for them?

**Comment by jkoritzinsky** [comment]
They're working on manually trying to support variance right now, so I think they'd appreciate this being backported if possible

**Review by elinor-fung — APPROVED** [review]

**Pull request merged**
