### PR TITLE
Ensure that ICU is loaded in tests before checking its version

### LINKED ISSUE #96279: System.Tests.StringTests failing on windows Release NativeAOT_Libraries leg
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=507101
Build error leg or test failing: System.Tests.StringTests
Pull request: https://github.com/dotnet/runtime/pull/95753

## Error Message
Many tests failing from `System.Tests.StringTests` and `System.Tests.TimeZoneInfoTests.UsingAlternativeTimeZoneIdsTest` area failing: [console log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-95753-merge-95802778ac294918b5/System.Runtime.Tests/1/console.9bd02146.log?helixlogtype=result)

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "[FAIL] System.Tests.StringTests",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=507101
**Error message validated:** `[FAIL] System.Tests.StringTests`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 12/22/2023 6:27:15 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[508316](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508316)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508316&view=ms.vss-test-web.build-test-results-tab&runId=11868572&resultId=126411)|dotnet/runtime#96183|
|[508312](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508312)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508312&view=ms.vss-test-web.build-test-results-tab&runId=11868496&resultId=126230)|dotnet/runtime#96182|
|[508304](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508304)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508304&view=ms.vss-test-web.build-test-results-tab&runId=11868278&resultId=127467)|dotnet/runtime#96178|
|[508278](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508278)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UsingAlternativeTimeZoneIdsTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508278&view=ms.vss-test-web.build-test-results-tab&runId=11867642&resultId=124442)|dotnet/runtime#96181|
|[508242](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508242)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508242&view=ms.vss-test-web.build-test-results-tab&runId=11866866&resultId=122498)|dotnet/runtime#96177|
|[508167](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508167)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508167&view=ms.vss-test-web.build-test-results-tab&runId=11866186&resultId=123935)|dotnet/runtime#96294|
|[508183](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508183)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508183&view=ms.vss-test-web.build-test-results-tab&runId=11864006&resultId=171655)||
|[508148](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508148)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508148&view=ms.vss-test-web.build-test-results-tab&runId=11863900&resultId=123383)|dotnet/runtime#96283|
|[508163](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508163)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508163&view=ms.vss-test-web.build-test-results-tab&runId=11863174&resultId=181526)||
|[508116](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508116)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508116&view=ms.vss-test-web.build-test-results-tab&runId=11861110&resultId=160576)||
|[508104](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508104)|dotnet/runtime|[System.Tests.StringTests.EndsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508104&view=ms.vss-test-web.build-test-results-tab&runId=11860062&resultId=127622)|dotnet/runtime#96291|
|[508096](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508096)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508096&view=ms.vss-test-web.build-test-results-tab&runId=11859814&resultId=123927)||
|[508071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508071)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508071&view=ms.vss-test-web.build-test-results-tab&runId=11859306&resultId=126604)|dotnet/runtime#96286|
|[508036](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508036)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UsingAlternativeTimeZoneIdsTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508036&view=ms.vss-test-web.build-test-results-tab&runId=11858072&resultId=121711)|dotnet/runtime#96183|
|[508032](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508032)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=508032&view=ms.vss-test-web.build-test-results-tab&runId=11858046&resultId=127343)|dotnet/runtime#96182|
|[507999](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507999)|dotnet/runtime|[System.Tests.StringTests.EndsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507999&view=ms.vss-test-web.build-test-results-tab&runId=11857226&resultId=126071)|dotnet/runtime#96181|
|[507962](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507962)|dotnet/runtime|[System.Tests.StringTests.StartsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507962&view=ms.vss-test-web.build-test-results-tab&runId=11856454&resultId=126421)|dotnet/runtime#96177|
|[507902](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507902)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507902&view=ms.vss-test-web.build-test-results-tab&runId=11854630&resultId=158728)||
|[507908](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507908)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507908&view=ms.vss-test-web.build-test-results-tab&runId=11854456&resultId=122704)|dotnet/runtime#96287|
|[507889](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507889)|dotnet/runtime|[System.Tests.StringTests.EndsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507889&view=ms.vss-test-web.build-test-results-tab&runId=11853722&resultId=124978)|dotnet/runtime#96286|
|[507886](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507886)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507886&view=ms.vss-test-web.build-test-results-tab&runId=11853572&resultId=124533)||
|[507873](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507873)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507873&view=ms.vss-test-web.build-test-results-tab&runId=11853342&resultId=179826)||
|[507783](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507783)|dotnet/runtime|[System.Tests.StringTests.StartsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507783&view=ms.vss-test-web.build-test-results-tab&runId=11849896&resultId=181228)||
|[507808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507808)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UsingAlternativeTimeZoneIdsTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507808&view=ms.vss-test-web.build-test-results-tab&runId=11849912&resultId=125963)|dotnet/runtime#96265|
|[507756](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507756)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507756&view=ms.vss-test-web.build-test-results-tab&runId=11849788&resultId=159722)||
|[507751](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507751)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UsingAlternativeTimeZoneIdsTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507751&view=ms.vss-test-web.build-test-results-tab&runId=11849674&resultId=165623)|dotnet/runtime#96283|
|[507753](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507753)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507753&view=ms.vss-test-web.build-test-results-tab&runId=11848590&resultId=124120)|dotnet/runtime#96284|
|[507727](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507727)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507727&view=ms.vss-test-web.build-test-results-tab&runId=11848096&resultId=125047)|dotnet/runtime#96065|
|[507710](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507710)|dotnet/runtime|[System.Tests.StringTests.EndsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507710&view=ms.vss-test-web.build-test-results-tab&runId=11847612&resultId=125205)|dotnet/runtime#96283|
|[507703](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507703)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UsingAlternativeTimeZoneIdsTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507703&view=ms.vss-test-web.build-test-results-tab&runId=11847022&resultId=123272)|dotnet/runtime#96281|
|[507014](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507014)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507014&view=ms.vss-test-web.build-test-results-tab&runId=11846454&resultId=121438)|dotnet/runtime#96258|
|[507653](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507653)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UsingAlternativeTimeZoneIdsTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507653&view=ms.vss-test-web.build-test-results-tab&runId=11845290&resultId=126825)|dotnet/runtime#95370|
|[507615](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507615)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UsingAlternativeTimeZoneIdsTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507615&view=ms.vss-test-web.build-test-results-tab&runId=11844658&resultId=126572)|dotnet/runtime#96201|
|[507594](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507594)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UsingAlternativeTimeZoneIdsTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507594&view=ms.vss-test-web.build-test-results-tab&runId=11843538&resultId=127076)|dotnet/runtime#95188|
|[507591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507591)|dotnet/runtime|[System.Tests.StringTests.EndsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507591&view=ms.vss-test-web.build-test-results-tab&runId=11843518&resultId=126709)|dotnet/runtime#96260|
|[507581](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507581)|dotnet/runtime|[System.Tests.StringTests.EndsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507581&view=ms.vss-test-web.build-test-results-tab&runId=11843394&resultId=127619)|dotnet/runtime#95456|
|[507554](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507554)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UsingAlternativeTimeZoneIdsTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507554&view=ms.vss-test-web.build-test-results-tab&runId=11841910&resultId=123678)|dotnet/runtime#96183|
|[507550](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507550)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507550&view=ms.vss-test-web.build-test-results-tab&runId=11841874&resultId=125920)|dotnet/runtime#96182|
|[507533](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507533)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507533&view=ms.vss-test-web.build-test-results-tab&runId=11841574&resultId=127384)|dotnet/runtime#96178|
|[507498](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507498)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507498&view=ms.vss-test-web.build-test-results-tab&runId=11840550&resultId=123760)|dotnet/runtime#96181|
|[507454](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507454)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507454&view=ms.vss-test-web.build-test-results-tab&runId=11838952&resultId=119015)|dotnet/runtime#96177|
|[507419](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507419)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507419&view=ms.vss-test-web.build-test-results-tab&runId=11837546&resultId=122379)|dotnet/runtime#96270|
|[507400](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507400)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507400&view=ms.vss-test-web.build-test-results-tab&runId=11836544&resultId=122100)|dotnet/runtime#95370|
|[507303](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507303)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507303&view=ms.vss-test-web.build-test-results-tab&runId=11834114&resultId=123663)|dotnet/runtime#93658|
|[507101](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507101)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507101&view=ms.vss-test-web.build-test-results-tab&runId=11825870&resultId=127200)|dotnet/runtime#95753|
|[507070](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507070)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=507070&view=ms.vss-test-web.build-test-results-tab&runId=11824852&resultId=123208)|dotnet/runtime#96261|
|[506958](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506958)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506958&view=ms.vss-test-web.build-test-results-tab&runId=11823560&resultId=159471)||
|[506757](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506757)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506757&view=ms.vss-test-web.build-test-results-tab&runId=11823168&resultId=124858)|dotnet/runtime#96201|
|[506808](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506808)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506808&view=ms.vss-test-web.build-test-results-tab&runId=11817074&resultId=123214)|dotnet/runtime#96254|
|[506621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506621)|dotnet/runtime|[System.Tests.StringTests.StartsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506621&view=ms.vss-test-web.build-test-results-tab&runId=11816942&resultId=127138)|dotnet/runtime#96178|
|[506720](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506720)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506720&view=ms.vss-test-web.build-test-results-tab&runId=11814474&resultId=127332)|dotnet/runtime#96240|
|[506708](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506708)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506708&view=ms.vss-test-web.build-test-results-tab&runId=11814314&resultId=127603)|dotnet/runtime#95370|
|[506702](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506702)|dotnet/runtime|[System.Tests.StringTests.EndsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506702&view=ms.vss-test-web.build-test-results-tab&runId=11814174&resultId=126979)|dotnet/runtime#93517|
|[506699](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506699)|dotnet/runtime|[System.Tests.StringTests.EndsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506699&view=ms.vss-test-web.build-test-results-tab&runId=11814150&resultId=123289)|dotnet/runtime#93658|
|[506675](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506675)|dotnet/runtime|[System.Tests.StringTests.EndsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506675&view=ms.vss-test-web.build-test-results-tab&runId=11813464&resultId=123464)|dotnet/runtime#95188|
|[506646](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506646)|dotnet/runtime|[System.Tests.TimeZoneInfoTests.UnsupportedImplicitConversionTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506646&view=ms.vss-test-web.build-test-results-tab&runId=11813086&resultId=120594)|dotnet/runtime#96183|
|[506641](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506641)|dotnet/runtime|[System.Tests.StringTests.StartsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506641&view=ms.vss-test-web.build-test-results-tab&runId=11813074&resultId=126948)|dotnet/runtime#96182|
|[506608](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506608)|dotnet/runtime|[System.Tests.StringTests.StartsWith_NullInStrings](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506608&view=ms.vss-test-web.build-test-results-tab&runId=11811732&resultId=125079)|dotnet/runtime#95404|
|[506567](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506567)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506567&view=ms.vss-test-web.build-test-results-tab&runId=11810338&resultId=123535)|dotnet/runtime#96181|
|[506509](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506509)|dotnet/runtime|[System.Text.Tests.RuneTests.Casing_Invariant](https://dev.azure.com/dnceng-public/public/_build/results?buildId=506509&view=ms.vss-test-web.build-test-results-tab&runId=11809002&resultId=118464)|dotnet/runtime#96177|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|9|60|60|

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #96279

### CODE REVIEW

**Comment by EgorBo** [comment]
@jkotas I did bisect locally and narrowed it down to 3 commits - 

2350298d78a2f0f67f7815a3bcbeeaf6870687b0
476a455426e9ec6239d4a408bfc38bbc00db5187
ec2bfd78513d7240522b50b08c9d3455391b8f59

checking these 3 now

**Comment by EgorBo** [comment]
Could be https://github.com/dotnet/runtime/pull/96187

Presumably, It changed behavior for "Checked" config?

**Comment by EgorBo** [comment]
Yeah, bisect for sure is pointing to 476a455426e9ec6239d4a408bfc38bbc00db5187, it doesn't make a lot of sense to me but it is 🙂

**Comment by jkotas** [comment]
> Yeah, bisect for sure is pointing to https://github.com/dotnet/runtime/commit/476a455426e9ec6239d4a408bfc38bbc00db5187, it doesn't make a lot of sense to me but it is

Thank you running the bisect locally! If https://github.com/dotnet/runtime/commit/476a455426e9ec6239d4a408bfc38bbc00db5187 is the problem, it is likely that removing the eager initialization from the static constructor exposes a latent bug in the rest of the static constructor. I have pushed a delta to confirm or disprove this theory.

**Comment by jkotas** [comment]
> bisect for sure is pointing to https://github.com/dotnet/runtime/commit/476a455426e9ec6239d4a408bfc38bbc00db5187, it doesn't make a lot of sense to me

The change removed ICU initialization as a side-effect that caused ICU version detection in other tests to fail silently.

**Review by EgorBo — APPROVED** [review]
Ah, now it makes sense. Is try-catch necessary there?

Or if it fails you want some specific test to fail rather than internally in xunit?

**Comment by jkotas** [comment]
> Ah, now it makes sense. Is try-catch necessary there?
> Or if it fails you want some specific test to fail rather than internally in xunit?

I have moved it into the existing try/catch.

**Pull request merged**
