### PR TITLE
MemoryCache property Count without using locks

### PR DESCRIPTION
**Pull request by joaocpaiva**
# Problem
Currently the MemoryCache.Count property calls the underlying ConcurrentDictionary.Count which takes all locks and as such it is prone to lock contention and becomes very inefficient in environments with high concurrency.

Granted, this property is documented as being used for diagnostics, however it is public, hence can be misused. Furthermore, many developers have expressed the desire to use Count for metrics or telemetry as an example (including myself :)).

# Solution
Using an auxiliary variable that tracks the number of entries in the underlying concurrent dictionary, using atomic operations to increment/decrement as needed.

This may slightly decrease the accuracy of the Count under high concurrency but the Count API already returned a value that represents a moment in the past and callers have no way around that, hence it should not break any existing consumers, if using this API at all.

Existing tests have good coverage on this logic, including for concurrency (AddAndReplaceEntries_AreThreadSafe).

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=55865) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=55865) before we can accept your contribution.<br/><br/>:x: joaocpaiva [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=55865)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=55865) it.</sub>

**Comment by MihaZupan** [comment]
There was more discussion around this in #15249 - there is a reason `ConcurrentDictionary` doesn't have such a counter itself.
While this change would improve the performance of the `Count` property, it would add overhead to other operations.

**Review by joaocpaiva — COMMENTED** [review]
> There was more discussion around this in #15249 - there is a reason `ConcurrentDictionary` doesn't have such a counter itself.
> While this change would improve the performance of the `Count` property, it would add overhead to other operations.
> 
> Also given the order of operations, with this change it would be possible for `Count` to return a negative value. That could have more serious implications than just the value being an approximation.

Ok that makes sense. I have confirmed the atomic adds significant overhead under high concurrency on my 8 logical core machine. I did not realize it can add this much overhead and since this adds more work/contention to hot path, it does not justify the cost. I was even wondering we could make this an opt-in configuration, but even then, it does not seem to be worthwhile then.

**Comment by eerhardt** [comment]
Given the discussion, I'm going to close this issue. Thanks for the discussion @joaocpaiva @MihaZupan.

**Pull request closed without merging**
