### PR TITLE
Add Fuzzlyn to CI

### PR DESCRIPTION
**Pull request by jakobbotsch**
Add support for Fuzzlyn in the exploratory pipeline files.
* We use the pipeline name to determine which tool to use, since that
  seems to be the easiest way to have this available during template
  expansion.
* All the .yml files are shared, and the setup script is also shared
  (renamed to fuzzer_setup.py). However the summarize and run scripts
  are not shared.
* The summarize scripts now use the AZDO feature that allows outputting
  a markdown file that shows up rendered under the pipeline results.
  These can be seen on the "Extensions" tab of AZDO.
* For Fuzzlyn, we automatically reduce silent bad codegen examples found
  and include these in the summary (but we do not reduce examples if we
  are over time). Assertion errors are not reduced, but the
  documentation in exploratory.md contains some information on how to
  reduce these manually. This should just be a temporary measure until
  we can more efficiently reduce these.
* The issue zips are now part of the issues artifact (and I removed the
  "summary" part of the name) since the Fuzzlyn summarize script reads
  the reduced examples from the zip, and I feel it's simpler to have all
  the info in one artifact.

I have also included a small fix for the superpmi download display progress so that we do not display a larger size than the file downloaded.

### CODE REVIEW

**Review by kunalspathak — COMMENTED** [review]
Good progress. Added few questions/comments.

**Comment by MattGal** [comment]
> > @kunalspathak Any ideas what could be going on and why we don't see output from the "run" scripts?
> 
> Yes, I have seen those failures and it was an understanding that this happen because of long running python scripts, but the one that you are running is just an hour long. FYI - @MattGal

It's hard to actually say what's going on here.  We don't try to stream the output from the docker container continuously because in prototyping this caused issues, so this got as far as it got with its std out buffer and this is how much output it copied.

Some thoughts about this problem:

- While older, the image is still in heavy usage daily (something like 526411 successful work items used it in the past month) so it's not likely specific to the image, rather what's running inside it.
- At least for this instance of the problem, we don't actually know if / how far it's getting past the "install dependencies on this container so I can use Helix functionality" stage or not.  It probably is, because it didn't time out, and pip would log some number of errors if it had exited w/ code 1 (unfortunately, 1 is many executables' favorite generic exit code including XUnit.)  - Writing any old file to $HELIX_WORKITEM_UPLOAD_ROOT as the first thing you do should answer that question.
- You can get rid or reduce this stage in execution by updating the image to latest; every time someone revs a dependency in the helix scripts this gets the docker images' preinstalled dependencies slightly out of whack with what's needed.  In this case you'd update to `mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-20211018132704-c537e64`

I think the best thing to do is to get a matching device to run this on and run the exact payload directly from an interactive bash session, and see where it actually hangs.  When you're to this stage, you can ping @Ilyas1974 for some help with it.

**Review by kunalspathak — APPROVED** [review]
LGTM!

**Comment by jakobbotsch** [comment]
Looks like the latest CI run found a silent bad codegen example. I opened #60597 for it.

@MattGal 
> At least for this instance of the problem, we don't actually know if / how far it's getting past the "install dependencies on this container so I can use Helix functionality" stage or not. It probably is, because it didn't time out, and pip would log some number of errors if it had exited w/ code 1 (unfortunately, 1 is many executables' favorite generic exit code including XUnit.) - Writing any old file to $HELIX_WORKITEM_UPLOAD_ROOT as the first thing you do should answer that question.

The output does seem to indicate that the Python script started to execute. The results [here](https://helix.dot.net/api/jobs/99906ed3-5246-46d4-a594-7768d2c16058/workitems/Partition2?api-version=2019-06-17) has a [Fuzzlyn-linux-arm-Partition2.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60344-merge-99906ed3524646d4a5/Partition2/1/Fuzzlyn-linux-arm-Partition2.log?sv=2019-07-07&se=2021-11-07T13%3A05%3A18Z&sr=c&sp=rl&sig=S42Fxiw1Sf5z0osm25Q%2B9%2B829xY9ubBC52uuX9i65C8%3D) file. This file is created by the Python script file running on the partition. Note that this file is truncated too, which seems strange.

Anyway, I will merge this PR for now and then see if I can find some time to investigate the failure further.

**Pull request merged**
