### PR TITLE
JIT: add concept of edge likelihood

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Now that FlowEdges are created early and persist, decorate them with likelihood information early, if we have edge-based PGO data.

We don't use the likelihood for anything yet, but I need to get it in circulation so I can start working on refining both initial and subsequent consistency of the data.

Also add a diagnostic checker for likelhood, and a way to enable it. All of this is off by default.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@EgorBo PTAL
cc @dotnet/jit-contrib 

This doesn't really affect the jit's behavior yet (other than perhaps a tiny bit of TP/memory and perhaps some new asserts popping up in PGO stress modes), but I'd like to get the groundwork laid for edge likelihoods, and then start enabling the new diagnostic checks so I can drive the work to fix the various issues. I expect there will be quite a few.

Once the maintenance is in good shape, I'll rip out the old edge weight system and replace it with the likelihoods and the jit will start acting on the new data.

**Comment by AndyAyersMS** [comment]
Related issue #81638 -- with this PR the internal model calls out pseduo edges, and the edge reconstructor relies on that to figure out how to handle various special cases.

The issue with finally returns could be resolved if it was possible to move the flow manipulations done in `impImportLeave` over to `fgNormalizeEH` -- not sure if this is worth considering. Note "returns" from finallies will typically look like criticial edges but they're non-splittable.

**Review by EgorBo — APPROVED** [review]
So currently this doesn't touch cases where we create internal blocks (e.g. expand casts) etc? (create artificial edges)

The idea is to get rid of m_edgeWeightMin/Max from edges eventually?

**Comment by AndyAyersMS** [comment]
> So currently this doesn't touch cases where we create internal blocks (e.g. expand casts) etc? (create artificial edges)
> 
> The idea is to get rid of m_edgeWeightMin/Max from edges eventually?

Right, this just sets likelihoods on the edge that exist initially. I still have to go through all the places we add/modify edges later on and set likelhoods for those.

**Comment by AndyAyersMS** [comment]
PGO pipelines don't seem to be clean, but I can at least check this PR doesn't introduce any new problems.

**Review by BruceForstall — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
No [diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=162075&view=ms.vss-build-web.run-extensions-tab);  tiny TP imapct.

PGO and libraries PGO failures look similar to recent runs on main. Possibly some new failures in PGO stress but the failures are non-specific so I am going to go ahead and merge.

**Pull request merged**
