### PR TITLE
System.Xml readonly annotation

### PR DESCRIPTION
**Pull request by hrrrrustic**
This PR is a part of #46675

### CODE REVIEW

**Review by krwq — APPROVED** [review]
The annotations looks good to me.

**Comment by krwq** [comment]
Annotations look good to me but I'm not sure that's always a good idea to mark as much as possible as read-only:
- Can caching be added later? I.e. in some scenarios hash code could be cached but caching would modify the state and therefore make it non-readonly and potentially be a breaking change...
- Are we introducing "const correctness" in C#? That's probably one of my most hated features in C++ - I'm not personally in favor of having this in C# - it just makes writing code a pain with small benefit - although this is debatable like "tabs" vs "spaces"

**Comment by krwq** [comment]
@hrrrrustic we've have some offline conversation about this and other PRs and we need to figure out the guidelines before we can accept these PRs:
-  it would be a breaking change if we try to remove the read-only in the future so this one way and we need to be really careful what we do here
- as mentioned above - caching cannot be added after you mark something read-only
- methods modifying argument but not its own state - they need further thought

likely only subset of the changes can be accepted but we need to figure out what subset exactly. We do agree there is a value in some of those, i.e. marking some structs as read-only but we are not particularly sure about marking methods in general. We will keep you updated.

**Comment by jeffhandley** [comment]
This PR is being marked as a draft per https://github.com/dotnet/runtime/pull/46675#issuecomment-828694665.

**Pull request closed without merging**
