### PR TITLE
Add invalidation to DTFI's SetAllDateTimePatterns

### PR DESCRIPTION
**Pull request by ts2do**
Invalidate derived patterns to match the behavior of invoking the corresponding property setters

### CODE REVIEW

**Review by tarekgh — APPROVED** [review]

**Comment by stephentoub** [comment]
Are there tests that should be added for this?

**Comment by tarekgh** [comment]
It is possible to write a test (for example):

- call FullDateTimePattern and keep the reference of the returned value.
- call LongDatePattern setter 
- call FullDateTimePattern again use Object.Referenceequals to ensure we are getting a new object for FullDateTimePattern.

**Comment by ts2do** [comment]
It looks like `FullDateTimePattern` is the only one that could be tested this way. One could potentially test all expected invalidations by calling `DateTime.ToString(string,IFormatProvider)` before and after assigning the base pattern to a format with a quoted string, checking whether the second resulting string contains the quoted string. Is this something you want me to do to move forward on this?

**Comment by tarekgh** [comment]
> Is this something you want me to do to move forward on this?

Please go ahead and give it a try. Thanks!

**Pull request merged**
