### PR TITLE
[mono][wasm] Make OP_WASM_SIMD_SWIZZLE use the shufflevector LLVM ins…

### PR DESCRIPTION
**Pull request by vargaz**
…truction.

The wasm.swizzle instrinsic always uses byte sized SIMD lanes, so it cannot represent
all the variants of Vector128.Shuffle ().

### CODE REVIEW

**Comment by radical** [comment]
Aren't there any library tests for SIMD with AOT?

**Comment by vargaz** [comment]
The BCL uses it so running the normal library tests with SIMD enabled can test it.

**Review by radekdoulik — APPROVED** [review]
Ah, nice! I missed this PR before.

I would like to keep the use of swizzle instruction for byte vectors, I can do that in follow up PR.

**Pull request merged**
