### PR TITLE
Delete more verification code

### PR DESCRIPTION
**Pull request by SingleAccretion**
Mostly just dead code, the only semantic change is around tailcall checks used for stress, they don't check type compatibility in the strict type system sense anymore.

Contributes to #32648.

[No diffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1901164&view=results) (modulo a small TP win).

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Old jistress logs are gone because of the pipeline shift. 

Let's bounce this and retrun.

**Comment by AndyAyersMS** [comment]
Hopefully jitstress is clean after https://github.com/dotnet/runtime/pull/75576. Libraries jitstress has at least one pre-existing issue  https://github.com/dotnet/runtime/issues/75644

**Review by jakobbotsch — APPROVED** [review]
LGTM. The failures look frozen object related which should have been fixed already. Thanks for this cleanup.

**Pull request merged**
