### PR TITLE
Almost complete sync of logic for generating DAM/RUC reflection access warnings between ILLink and NativeAOT

### LINKED ISSUE #68688: NativeAOT doesnt produce Requires warnings in Generics
### Description

There is a whole section of code improvements related to generics that need to be ported from ILLinker to NativeAOT. Missing things:
ILLinker has a method called GetOriginalMethod() that verifies if the method reference is a GenericInstanceMethod and calls a Marking helper for GenericArguments (MarkGenericArguments). This is never called in NativeAOT resulting in less warnings in GenericArguments and in the Default constructor constrains which are not being marked.

### Reproduction Steps

```C#
AccessThroughNewConstraint.Test<TestType>();

class TestType { }

class AccessThroughNewConstraint
{
    class NewConstraintTestType
    {
        [RequiresUnreferencedCode("Message for --NewConstraintTestType.ctor--")]
        [RequiresDynamicCode("Message for --NewConstraintTestType.ctor--")]
        public NewConstraintTestType() { }
    }


    [RequiresUnreferencedCode("Message for --NewConstraintTestAnnotatedType--")]
    [RequiresDynamicCode("Message for --NewConstraintTestType.ctor--")]
    class NewConstraintTestAnnotatedType
    {
    }

    static void GenericMethod<T>() where T : new() { }

    //[ExpectedWarning("IL2026", "--NewConstraintTestType.ctor--")]
    //[ExpectedWarning("IL2026", "--NewConstraintTestAnnotatedType--")]
    //[ExpectedWarning("IL3050", "--NewConstraintTestType.ctor--")]
    //[ExpectedWarning("IL3050", "--NewConstraintTestAnnotatedType--")]
    public static void Test<T>() where T : new()
    {
        GenericMethod<NewConstraintTestType>();
        GenericMethod<NewConstraintTestAnnotatedType>();
        GenericMethod<T>(); // should not crash analyzer
    }
}
```

### Expected behavior

The expected warnings should have been present

### Actual behavior

Warnings are not generated

### Regression?

_No response_

### Known Workarounds

NativeAOT needs to sync with the current version of ILLinker to solve some of these problems, is not a straight copy of the code from ILLinker though.

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by vitek-karas**
This enables the last of the disabled `RequiresCapability` tests for NativeAOT.

The implementation basically copies the logic from ILLink on how to produce warnings when method or field is marked due to reflection access.

We decided that producing warnings due to reflection access to compiler generated methods is more trouble than benefit and thus we won't do that anymore. See reasoning in https://github.com/dotnet/runtime/issues/85042.

Otherwise the behavior in NativeAOT fully copies the one in ILLink (small exceptions due to better method overload resolution in NativeAOT).

High-level behavior changes in NativeAOT:
* Finally allow the NativeAOT compiler to produce IL2110, IL2111, IL2113 and IL2115
* Avoid generating warnings for override methods if the warning is already generated on the base method (for DAM marking)
* Implement correct marking (and warnings) for "DAM on type" when the derived class has broader annotation than the base class/interface (this is mostly to avoid noise warnings)
* Rename a set of methods and classes in data flow scanner to "Token", because they're only used when a given entity is accessed through its token (so `ldtoken` and similar). This allows for more precise handling of the cases above.

Testing changes:
* Allow specifying tool exceptions for `SkipKepItemsValidationAttribute` - this allows to enable one of the reflection tests for its diagnostics coverage, avoiding the necessity to fix everything around Kept behavior yet.
* Couple of fixes in the test validator to correctly compare expected/actual diagnostics

This fixes final bits of https://github.com/dotnet/runtime/issues/68786
Fixes https://github.com/dotnet/runtime/issues/68688
This helps with https://github.com/dotnet/runtime/issues/82447

### CODE REVIEW

**Review by MichalStrehovsky — COMMENTED** [review]
Left a question. I didn't review the algorithm in detail because it's rather complicated and I already lack quite some context. I still wish we just ignored the fact that compiler-generated things can be reflected on and left it as a wart.

**Comment by vitek-karas** [comment]
I must admit I'm starting to agree that we should probably give up on at least some of this. For example I found out that ILLink doesn't warn in all cases of accessing compiler generated code, even when it technically should.
When ILLink detects if a method is potentially dangerous it doesn't detect usage of annotated generics - so if there's a method which only calls for example `new Lazy<T>()` it won't produce a warning, even though it's a potential hole since we can't guarantee that T will have default .ctor in this case.

I'm going to look into a couple more cases which popped up, just to make sure we're not missing something bigger first though.

**Comment by vitek-karas** [comment]
This is ready for review.

I updated the comment to match the implemented behavior.

All the CI failures are unrelated.

**Review by MichalStrehovsky — APPROVED** [review]
Thank you!

**Pull request merged**
