### PR TITLE
Crossgen2 outer loop fixes

### LINKED ISSUE #106948: Test failure: readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd
**Failed in:** [runtime-coreclr outerloop 20240825.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=787850&view=ms.vss-test-web.build-test-results-tab&runId=20240270&resultId=104817&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd
```

**Error message:**
```
 1 / 1 (100%, 1 failed): failed in 257 msecs, exit code 134, expected 0: crossgen2 @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
!! Assert failure(PID 59 [0x0000003b], Thread: 59 [0x003b]): Consistency check failed: Crst Level violation: Can't take level 6 lock CrstUnresolvedClassLock because you already holding level 0 lock CrstNativeImageEagerFixups
!! FAILED: false
!!     File: /__w/1/s/src/coreclr/vm/crst.cpp:765
!!     Image: /root/helix/work/correlation/crossgen2/crossgen2
!! [createdump] The app model does not support crash report generation
!! [createdump] Failure took 0ms
!! waitpid() returned successfully (wstatus 00000086) WEXITSTATUS 0 WTERMSIG 6
  [createdump] Target process is alive

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/coreroot_determinism/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true coreroot_determinism.dll ''
================================== Compiling with seed 1 ==================================
Locating output folder /root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1
Deleting 0 output folders
Successfully deleted 0 output folders in 143 msecs
1 / 1 (0%, 0 failed): launching: /root/helix/work/correlation/crossgen2/crossgen2 @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
Compilation failed. /root/helix/work/correlation/corerun /root/helix/work/correlation/R2RTest/R2RTest.dll compile-directory -cr /root/helix/work/correlation -in TestAssemblies --nojit --noexe --large-bubble --release --nocleanup -ct 30 -out seed1 failed with exit code 1
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   1
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 90
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 8/25/2024 7:41:29 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /root/helix/work/workitem/e/readytorun/coreroot_determinism/readytorun_coreroot_determinism/../coreroot_determinism/coreroot_determinism.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor1|0_2(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #106948

### CODE REVIEW

**Review by kg — APPROVED** [review]
I'm not an expert, but this all looks good to me. Thanks for digging in and fixing this.

**Review by ivdiazsa — APPROVED** [review]
LGTM! Thanks a lot for your help with this Jan!

**Pull request merged**
