### PR TITLE
[metadata] Skip null vtable entries when checking covariant return overrides

### PR DESCRIPTION
**Pull request by lambdageek**
When there are covariant return overrides, we check the vtable slot in every parent class for signature compatibility with the proposed override.

However if one of the ancestor classes is abstract, it could have an abstract override for the method:

```csharp
    class Base {
      public virtual Base Method() => this;
    }
    public abstract Intermediate : Base {
      public override abstract Base Method();
    }
    public Leaf : Intermediate {
      public override Leaf Method() => this;
    }
```
In this case when we're checking that `Leaf.Method` is compatible with the vtable slot in `Intermediate`, we will see a null method (since `Intermediate.Method` is abstract).  In such cases we can skip over the class and continue with its parent.

Fixes
https://github.com/dotnet/runtime/issues/76312

### CODE REVIEW

**Comment by lambdageek** [comment]
I think we should backport this for net7 and net6

**Review by vargaz — APPROVED** [review]

**Comment by lambdageek** [comment]
`runtime-extra-platforms (Build tvOS arm64 Release AllSubsets_Mono) ` is failing repeatedly while trying to set up a tunnel to the device:
```
[10:39:13] dbug: [TCP tunnel] Xamarin.Hosting: Attempting USB tunnel between the port 61033 on the device and the port 61033 (27118) on the mac: 61
```

I think it's an infra problem, not my PR...

**Pull request merged**
