### PR TITLE
Add IAsyncDisposable implementation for XmlWriter

### LINKED ISSUE #29464: XDocument.SaveAsync has a blocking call
`XDocument.SaveAsync` has a blocking call. In ASP.NET Core 3 this is not allowed (by default).

````
System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException:  ---> System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true.

at Microsoft.AspNetCore.TestHost.ResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   at System.Xml.XmlUtf8RawTextWriter.Flush()
   at System.Xml.XmlWellFormedWriter.Close()
   at System.Xml.XmlWriter.Dispose(Boolean disposing)
   at System.Xml.XmlAsyncCheckWriter.Dispose(Boolean disposing)
   at System.Xml.XmlWriter.Dispose()
   at System.Xml.Linq.XDocument.SaveAsync(Stream stream, SaveOptions options, CancellationToken cancellationToken)
   at MyCode(Stream stream, XDocument document, CancellationToken cancellationToken)
````

I think `SaveAsync` should call `FlushAsync` before calling `Dispose` (or maybe `XmlWriter` should implement `IAsyncDisposable`).

```c#
        public async Task SaveAsync(Stream stream, SaveOptions options, CancellationToken cancellationToken)
        {
            XmlWriterSettings ws = GetXmlWriterSettings(options);

            ws.Async = true;

            if (_declaration != null && !string.IsNullOrEmpty(_declaration.Encoding))
            {
                try
                {
                    ws.Encoding = Encoding.GetEncoding(_declaration.Encoding);
                }
                catch (ArgumentException)
                {
                }
            }

            using (XmlWriter w = XmlWriter.Create(stream, ws))
            {
                await WriteToAsync(w, cancellationToken).ConfigureAwait(false);

                // I think we should add FlushAsync here
                await w.FlushAsync().ConfigureAwait(false);
            }
        }
```

### PR DESCRIPTION
**Pull request by buyaa-n**
XmlWriter doesn't implemented async disposal, because of that async XmlWriter calls sync `Dispose()` which will eventually call sync `Flush(), Write(...)` which causing probem for [async steams](https://github.com/dotnet/aspnetcore/blob/354d859d50f252526be5a6264434d1765df86450/src/Servers/Kestrel/Core/src/Internal/Http/HttpResponseStream.cs#L80-L83) not allowing sync operation. Added IAsyncDisposable  implementation for XmlWriter and its descendants 

Fixes https://github.com/dotnet/runtime/issues/29464

### CODE REVIEW

**Comment by stephentoub** [comment]
@terrajobst, does this need to go through API review?

**Comment by terrajobst** [comment]
> @terrajobst, does this need to go through API review?

Yep, implementing new interfaces should go through API review, even if all members are explicitly implemented.

**Comment by stephentoub** [comment]
@buyaa-, can you please create an API proposal for that? Thanks!

**Comment by buyaa-n** [comment]
> @buyaa-, can you please create an API proposal for that? Thanks!

Sure, thanks!

**Pull request closed without merging**
