### PR TITLE
Don't inline expand boxes with many GC pointers

### PR DESCRIPTION
**Pull request by MichalStrehovsky**

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
/benchmark plaintext,json,fortunes aspnet-citrine-win runtime,libs

**Comment by EgorBo** [comment]
@EgorBot
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(MyBench).Assembly).Run(args);

public class MyBench
{
    MyStruct fld;

    [Benchmark]
    public object BoxField() => fld;

    [Benchmark]
    public object BoxEmpty() => new MyStruct();
}

struct MyStruct
{
    string a1;
    string a2;
    string a3;
    string a4;
}
```

**Comment by EgorBo** [comment]
@EgorBot
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(MyBench).Assembly).Run(args);

public class MyBench
{
    MyStruct fld;

    [Benchmark]
    public object BoxField() => fld;

    [Benchmark]
    public object BoxEmpty() => new MyStruct();
}

struct MyStruct
{
    string a1;
    string a2;
    string a3;
    string a4;
}
```

**Comment by jkotas** [comment]
We have optimized JIT_Box helper variants only on Windows: https://github.com/dotnet/runtime/blob/f88ab88f4ce02569f84922cda802317e69682d8a/src/coreclr/vm/jitinterfacegen.cpp#L75-L88 . We would need to implemented the optimized non-Windows JIT_Box helper variants on non-Windows too to make this optimization work well, using the same strategy as the optimized non-Windows allocation helpers are implemented.

**Comment by MichalStrehovsky** [comment]
> We would need to implemented the optimized non-Windows JIT_Box helper variants on non-Windows too to make this optimization work well, using the same strategy as the optimized non-Windows allocation helpers are implemented.

For ContainsPointers the optimized assembly helper needs to thunk out to C++ anyway so the optimization might not amount to much for the relevant cases. I'll add this to the issue. Not actually planning to work on this based on Egor's comments.

**Comment by EgorBo** [comment]
> Not actually planning to work on this based on Egor's comments.

I can try myself, but I think it should be more or less trivial, you just need to introduce a new helper (where you'll just do `memcpyGC`) and call it in `genCodeForCpObj` (so the actuall allocation for the box will be handled efficiently via the NEWS helper as is).

**Comment by MichalStrehovsky** [comment]
> I can try myself, but I think it should be more or less trivial, you just need to introduce a new helper

If we want to keep the NEWS, we might just be able to use the CORINFO_HELP_ASSIGN_STRUCT to do the copying.

**Comment by EgorBo** [comment]
> > I can try myself, but I think it should be more or less trivial, you just need to introduce a new helper
> 
> If we want to keep the NEWS, we might just be able to use the CORINFO_HELP_ASSIGN_STRUCT to do the copying.

Yep, that's what I meant, the helper is completely unused/unimplemented, so at least we won't have to bump R2R format 🙂

**Pull request closed without merging**
