### PR TITLE
Forward Span-based MemoryExtensions overloads to ReadOnlySpan overloads

### PR DESCRIPTION
**Pull request by stephentoub**
Any reason not to do this?  I'm not sure why it was done this way in the first place... seems like there must have been a reason?
cc: @GrabYourPitchforks

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
I want to say it was a limitation of the JIT, where passing around complex structs (`Span<T>` or `ReadOnlySpan<T>`) across ABI was resulting in some weird unoptimized codegen. But not sure if this is still the case. Will run a quick experiment.

**Comment by GrabYourPitchforks** [comment]
Both these methods produce identical codegen in .NET 6.

```cs
using BenchmarkDotNet.Attributes;
using System;
using System.Runtime.CompilerServices;

namespace ConsoleAppBenchmark
{
    [DisassemblyDiagnoser]
    public class SpanFwdRunner
    {
        private readonly int[] _ints = new int[] { 1, 2, 3 };

        [Benchmark(Baseline = true)]
        [Arguments(2)]
        public bool Control(int value)
        {
            Span<int> span = _ints;
            return span.Contains(value);
        }

        [Benchmark(Baseline = false)]
        [Arguments(2)]
        public bool Variable(int value)
        {
            Span<int> span = _ints;
            return span.ContainsEx(value);
        }
    }

    internal static class Extensions
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool ContainsEx<T>(this Span<T> span, T value) where T : IEquatable<T>
        {
            return ((ReadOnlySpan<T>)span).Contains(value);
        }
    }
}
```

@AndyAyersMS Do you know if my theory about a previous JIT not optimizing this scenario correctly is viable? If something changed between earlier versions of .NET and vCurrent that means we can simplify this code, I'm all for Steve's proposed changes.

**Review by GrabYourPitchforks — APPROVED** [review]
Let's wait for the JIT team to chime in, but LGTM!

**Comment by SingleAccretion** [comment]
One thing this change could risk is pushing some methods over the "512 max tracked locals" limit. I wrote a sample that demonstrates this:  [asm diff](https://www.diffchecker.com/pcoU2VwU). While the codegen is the same (yay!), the number of locals used is considerably higher with the cast.

We have tolling that compares ASM between different Jit's. It could be interesting to leverage that for diffing the CoreLib (and/or the shared framework too) with & without this change. Unfortunately I do not have the time for doing it right now, but a note if someone else is interested: do not forget to eliminate `Debug.Fail`s from the equation (`Checked` CoreLib is built with `DEBUG` defined).

**Comment by AndyAyersMS** [comment]
Not sure. 

Perhaps on it was x64/SysV ABI, or arm64, where we might have been spilling the spans to stack and back? Or local copies of pass through structs blocking tail calls?

Much of that should be mitigated by now.

**Comment by jkotas** [comment]
The extra forwarding layer will also regress the case where these methods are used over reference types (the generics inlining problem).

**Comment by jkotas** [comment]
> One thing this change could risk is pushing some methods over the "512 max tracked locals" limit.

Yep, the JIT budgets tend to get consumed very fast for code that works with Spans due to extensive use of aggressive inlining, so calling method may not actually be that large to hit this limit.

**Comment by stephentoub** [comment]
I'm not sure how to evaluate the tradeoffs here.  This is a fair amount of non-trivial code duplication; just from a maintenance perspective I'd like to get rid of it, but then also arguably unnecessary binary size (e.g. a default Blazor wasm app currently uses both the Span and ReadOnlySpan overloads of `IndexOf(span, T)` and `StartsWith(span, ROS<T>)`.  Maybe it's a drop in the bucket, but it's a shame that limitations elsewhere in the system force this to even be a performance tradeoff.

@jkotas, @AndyAyersMS, would you prefer to see this closed then?

**Comment by jkotas** [comment]
`int IndexOfAny<T>(this Span<T> span, ReadOnlySpan<T> values)` has the largest amount of duplication from all the methods touched in this PR. I think it is reasonable to eliminate the duplication for this method, but I would keep the duplication for the rest.

**Review by jkotas — APPROVED** [review]

**Comment by AndyAyersMS** [comment]
>  "512 max tracked locals" limit.

We may want to revaluate this limit. Last time we looked (~5 years ago) there were very few methods that came near. But perhaps things have changed.

> the generics inlining problem

I know David was poking around here a while back -- at some point we should try and fix this.

**Comment by saucecontrol** [comment]
> Last time we looked (~5 years ago) there were very few methods that came near. But perhaps things have changed.

Don't forget the examples in https://github.com/dotnet/runtime/issues/11905 ;)

**Pull request merged**
