### PR TITLE
Use "..."u8 in dotnet/runtime

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by teo-tsirpanis** [comment]
I am working on https://github.com/dotnet/runtime/blob/main/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Utf8Constants.cs which I see you missed.

**Comment by stephentoub** [comment]
Thank you for pointing out the omission. I can add it here, and also search for anything else like this I may have missed. I didn't pay attention to byte[]s being filled with seemingly arbitrary numbers, as opposed to (byte)'char'.

**Comment by marek-safar** [comment]
I'm surprised there is nothing in CoreLib.

**Comment by stephentoub** [comment]
> I'm surprised there is nothing in CoreLib

Do you know of any there? This was search/replace based on specific patterns. I'm sure there are others with more complicated patterns.

**Comment by teo-tsirpanis** [comment]
image

**Comment by stephentoub** [comment]
Most of those aren't strings, e. g. the first ones are number of days in each month. We shouldn't use u8 to encode arbitrary data.

**Comment by teo-tsirpanis** [comment]
I didn't say to make them `u8`, I pointed out that there isn't anything missed in Corelib.

**Comment by stephentoub** [comment]
> I didn't say to make them u8, I pointed out that there isn't anything missed in Corelib.

Ah, thanks :-)

**Comment by marek-safar** [comment]
Perhaps I misunderstood the feature as I was thinking that it could help with strings like https://github.com/dotnet/runtime/blob/322ea09acfaa1f334702fddba8b6d74bb2573805/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeFormat.cs#L146

**Comment by stephentoub** [comment]
> Perhaps I misunderstood the feature as I was thinking that it could help with strings like

The feature is basically that you write `"text"u8` and at C# compile-time the compiler produces the logical equivalent of `new byte[] { (byte)'t', (byte)'e', (byte)'x', (byte)'t' }`.

**Comment by stephentoub** [comment]
I'm going to close this for now and will redo it once we have a compiler that adapts to recent design decisions around u8.

**Pull request closed without merging**
