### PR TITLE
[mono] Fix a regression caused by 9ddd58a58d14a7bec5ed6eb777c6703c48a…

### LINKED ISSUE #63079: [Android][x86][arm] System.Tests.GCExtendedTests.AllocateArrayTooLarge throws OverflowException instead of OutOfMemoryException
```
<test name="System.Tests.GCExtendedTests.AllocateArrayTooLarge" type="System.Tests.GCExtendedTests" method="AllocateArrayTooLarge" time="0.0181027" result="Fail">
<failure exception-type="Xunit.Sdk.ThrowsException">
    <message><![CDATA[Assert.Throws() Failure\nExpected: typeof(System.OutOfMemoryException)\nActual:   typeof(System.OverflowException): Arithmetic operation resulted in an overflow.\n---- System.OverflowException : Arithmetic operation resulted in an overflow.]]></message>
    <stack-trace><![CDATA[   at System.GC.AllocateArray[Double](Int32 length, Boolean pinned)
at System.GC.AllocateUninitializedArray[Double](Int32 length, Boolean pinned)
at System.Tests.GCExtendedTests.<>c.<AllocateArrayTooLarge>b__29_0() in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 1040
----- Inner Stack Trace -----
at System.GC.AllocateArray[Double](Int32 length, Boolean pinned)
at System.GC.AllocateUninitializedArray[Double](Int32 length, Boolean pinned)
at System.Tests.GCExtendedTests.<>c.<AllocateArrayTooLarge>b__29_0() in /_/src/libraries/System.Runtime/tests/System/GCTests.cs:line 1040]]></stack-trace>
</failure>
</test>
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1523011&view=ms.vss-test-web.build-test-results-tab&runId=43266500&resultId=166413&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

**This is a regression:** Reverting https://github.com/dotnet/runtime/commit/9ddd58a58d14a7bec5ed6eb777c6703c48aca15d makes the mentioned test pass.

cc @akoeplinger @steveisok @vargaz 

Upd. The tests are failing on Android x86/ arm legs:
- System.Tests.GCExtendedTests.AllocateArrayTooLarge
- System.Collections.Tests.SortedListTests.Capacity_Excessive
- System.Collections.Tests.CollectionBaseTests.Capacity_Excessive

### PR DESCRIPTION
**Pull request by vargaz**
…ca15d.

Fixes https://github.com/dotnet/runtime/issues/63079.

### CODE REVIEW

**Comment by akoeplinger** [comment]
@vargaz looks like the test failure still happens on the Android arm leg, so I guess the same change is needed for mini-arm.c (and other 32bit platforms?).

**Review by lambdageek — APPROVED** [review]

**Review by imhameed — APPROVED** [review]

**Review by lambdageek — APPROVED** [review]

**Comment by vargaz** [comment]
Are these lanes expected to fail ?

**Comment by MaximLipnin** [comment]
> Are these lanes expected to fail ?

yeah, they seem to be known. I'm going to merge your PR to eliminate the initial problem.

**Pull request merged**
