### PR TITLE
Fix exception catch block in Dispose_CancelsConnectAsync test

### LINKED ISSUE #35886: Test failure: System.Net.Sockets.Tests.TcpClientTest.Dispose_CancelsConnectAsync
failed in job: [runtime-libraries outerloop 20200505.3 ](https://dev.azure.com/dnceng/public/_build/results?buildId=631532&view=ms.vss-test-web.build-test-results-tab&runId=19694176&resultId=103124&paneView=debug)

Error message
~~~
System.Net.Sockets.SocketException : Bad value for ai_flags


Stack trace
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1138
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1123
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs:line 220
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs:line 320
   at System.Net.Sockets.Tests.TcpClientTest.Dispose_CancelsConnectAsync(Boolean connectByName) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TcpClientTest.cs:line 435
--- End of stack trace from previous location ---
~~~

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/runtime/issues/35886

### CODE REVIEW

**Comment by davidsh** [comment]
#35886 was a test failure where the exception was "System.Net.Sockets.SocketException : Bad value for ai_flags".

Is that an "expected" exception side-affect from this test? It almost looks like a programming error.

**Comment by stephentoub** [comment]
> Is that an "expected" exception side-affect from this test? It almost looks like a programming error.

This is disposing in the middle of a connect.  My assumption is that pretty much any socket exception could occur as a result.  Let me know if you think it's actually a concern.

**Comment by davidsh** [comment]
>This is disposing in the middle of a connect. My assumption is that pretty much any socket exception could occur as a result. Let me know if you think it's actually a concern.

I do think it is a concern. If it was something like "connection error" etc., that would make more sense with it being a race condition of disposing during connection.

But this exception looks suspect. I think someone more knowledgable about System.Net.Sockets should comment on this.

@wfurt @tmds @scalablecory @antonfirsov

**Comment by scalablecory** [comment]
I think catching all `SocketException` is too broad and will cover up bugs.

The exception message in the issue points to `getaddrinfo` misuse or maybe a bad error code being generated somewhere, not to a dispose-related error:

```
System.Net.Sockets.SocketException : Bad value for ai_flags
```

I agree with @davidsh this needs a closer look.

**Comment by stephentoub** [comment]
> System.Net.Sockets.SocketException : Bad value for ai_flags

This is what `new SocketException((int)SocketError.SocketError)` produces. `SocketError.SocketError` is -1, which is the same value as `EAI_BADFLAGS` on Linux.

**Comment by stephentoub** [comment]
> I think catching all SocketException is too broad and will cover up bugs.

Ok

**Pull request closed without merging**
