### PR TITLE
Optimize System.Diagnostics.TraceSource

### PR DESCRIPTION
**Pull request by pentp**
This removes some unnecessary configuration code, optimizes the fast path for methods expected to be used on hot paths (e.g., `TraceSource.TraceEvent`) and improves reliability if `Trace.UseGlobalLock` is not used (by avoiding `List.GetEnumerator`, which also helps perf).

### CODE REVIEW

**Comment by tommcdon** [comment]
Adding @noahfalk @tarekgh to review

**Comment by tarekgh** [comment]
@pentp thanks for submitting this PR. 

I am wondering, are you using TraceSource? did you run into perf issue which triggered doing this optimization? In general, I would use a different mechanism for tracing which can work better with other diagnostics tools.

**Comment by tarekgh** [comment]
+ @Anipik the owner of this area

**Comment by tommcdon** [comment]
> I am wondering, are you using TraceSource? did you run into perf issue which triggered doing this optimization? In general, I would use a different mechanism for tracing which can work better with other diagnostics tools.
@pentp would it be possible to respond to @tarekgh's questions above?  In case it is useful, here's a pointer to optimized logging libraries - https://docs.microsoft.com/dotnet/core/diagnostics/logging-tracing#logging-events

**Comment by tommcdon** [comment]
Closing this PR for now as there are outstanding questions.  Please feel free to re-open the PR if the above questions can be addressed.

**Pull request closed without merging**
