### PR TITLE
Move iOS/tvOS simulator and Android emulator legs from runtime-staging to runtime-extra-platforms pipeline

### PR DESCRIPTION
**Pull request by MaximLipnin**
This change is to move the Apple mobile simulator (iOS/tvOS x64, iOS arm64) and Android emulator (x86/x64) CI leg definitions, used to build the whole product using Mono and run libraries tests, from runtime-staging to runtime-extra-platforms pipeline.  The iOS simulator arm64 leg will remain on rolling build until we can get significantly more devices.

### CODE REVIEW

**Review by simonrozsival — APPROVED** [review]

**Review by akoeplinger — APPROVED** [review]

**Comment by MaximLipnin** [comment]
The `CoreCLR Pri0 Runtime Tests Run windows arm64 checked` timed out - filed https://github.com/dotnet/runtime/issues/65667 (I didn't find similar issue).

**Comment by MaximLipnin** [comment]
No issues with the related CI legs, merging.

**Pull request merged**
