### PR TITLE
Consider finally that jumps to itself as non-empty

### LINKED ISSUE #58729: Assertion failed 'block->countOfInEdges() > 0' during 'Remove empty finally' with infinite loop in finally
```csharp
public static void Main()
{
    try
    {
        System.Console.WriteLine("A");
    }
    finally
    {
        while (true)
        {
        }
    }
}
```

```text
Assert failure(PID 14880 [0x00003a20], Thread: 23380 [0x5b54]): Assertion failed 'block->countOfInEdges() > 0' in 'Program:Main()' during 'Remove empty finally' (IL size 16)

    File: D:\dev\dotnet\runtime\src\coreclr\jit\fgflow.cpp Line: 280
    Image: D:\dev\dotnet\runtime\artifacts\tests\coreclr\windows.x64.Debug\Tests\Core_Root\corerun.exe
```

### PR DESCRIPTION
**Pull request by kunalspathak**
We were assuming that if a `finally` is empty, it doesn't have any blocks pointing to it, but sometimes Roslyn would have a copy of code inside `finally` into a block that follows `finally` block, and directly jump to that block. 

```
IL to import:
IL_0000  72 33 11 00 70    ldstr        0x70001133
IL_0005  28 3c 00 00 0a    call         0xA00003C
IL_000a  de 02             leave.s      2 (IL_000e)
IL_000c  2b fe             br.s         -2 (IL_000c)
IL_000e  2b fe             br.s         -2 (IL_000e)
```

As such, after removing `CALL_FINALLY` block, the block inside `finally` can jump back to itself and hence one additional reference. As such, while removing empty finally, we should just decrease the reference count of finally block by 1 and then let `fgRemoveBlock()` take care of further reducing the reference count, if there exist one.

Fixes: https://github.com/dotnet/runtime/issues/58729

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
I think we should fix this by classifying finallies that `BBJ_ALWAYS` to themselves as non-empty...

**Comment by kunalspathak** [comment]
> I think we should fix this by classifying finallies that `BBJ_ALWAYS` to themselves as non-empty...

Ah, ok. So will that remove the block inside finally in later phase (dead code) or it will never remove the block and we will go ahead and generate code except that we will not go to it?

**Comment by AndyAyersMS** [comment]
I suspect it will stay around... as mentioned over in the issue the code in the finally is reachable if there's an exception thrown in the try. So it's not actually dead.

**Comment by kunalspathak** [comment]
@AndyAyersMS - can you take another look?

**Review by AndyAyersMS — APPROVED** [review]

**Comment by BruceForstall** [comment]
Isn't the issue that there is the code is looking for `GT_RETFILT` incorrectly? I.e., it's only looking for non-GT_RETFILT nodes, but not actually verifying that there is a (single) GT_RETFILT node?

**Comment by AndyAyersMS** [comment]
I think the checks are equivalent, but yeah the comment I put there is not describing what the code does.

**Pull request merged**
