### PR TITLE
Add encoding for ARM64 IF_SVE_CJ_2A instruction group

### PR DESCRIPTION
**Pull request by snickolls-arm**
Adds support for encoding the `rev (predicate)` instruction.

Matching capstone output:
```
rev p1.b, p2.b
rev p4.h, p5.h
rev p3.s, p7.s
rev p0.d, p6.d
```

Contributing towards #94549.

### CODE REVIEW

**Comment by snickolls-arm** [comment]
@a74nh @kunalspathak @dotnet/arm64-contrib

**Review by amanasifkhalid — APPROVED** [review]
LGTM, thank you!

**Review by kunalspathak — APPROVED** [review]

**Comment by kunalspathak** [comment]
@snickolls-arm - Thanks for your contribution. Please resolve the merge conflicts when you get a chance.

**Comment by kunalspathak** [comment]
@snickolls-arm - could you please resolve the merge conflicts once again? sorry, there is lot of churn in this portion of the code base.

**Pull request merged**
