### PR TITLE
[wasm] Pin sdk version to 8.0.100-rc.1.23415.5 for workload testing

### LINKED ISSUE #90742: [wasm] WBT broken on `main`
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=377311
Build error leg or test failing: Wasm.Build.NativeRebuild.Tests.FlagsChangeRebuildTests.ExtraEmccFlagsSetButNoRealChange
Pull request: https://github.com/dotnet/runtime/pull/90517

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "Expected the multithreading runtime pack to be available when running on CI. IsRunningOnCI is true but IsWorkloadWithMultiThreadingForDefaultFramework is false",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=377311
**Error message validated:** `Expected the multithreading runtime pack to be available when running on CI. IsRunningOnCI is true but IsWorkloadWithMultiThreadingForDefaultFramework is false`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/17/2023 2:58:31 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[377311](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377311)|dotnet/runtime|[Wasm.Build.Tests.WasmTemplateTests.ConsoleBuildAndRunForSpecificTFM(config: \"Debug\", extraNewArgs: \"-f net8.0\", expectedTFM: \"net8.0\")](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377311&view=ms.vss-test-web.build-test-results-tab&runId=8029772&resultId=100095)|dotnet/runtime#90517|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

### PR DESCRIPTION
**Pull request by radical**
.. because `dotnet-install --channel 8.0` is returning 9.0-alpha sdks right now.

Fixes https://github.com/dotnet/runtime/issues/90742
Fixes https://github.com/dotnet/runtime/issues/90743

### CODE REVIEW

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
need to pin in the release branches too right?

**Comment by lewing** [comment]
And we'll want to unpin in https://github.com/dotnet/runtime/pull/90558 (and fix the channel) once this lands

**Comment by radical** [comment]
This needs to wait for at least the WBT runs for browser-wasm, and wasi-wasm.

**Comment by radical** [comment]
WBT passed. Merging this to get CI green.

**Pull request merged**
