### PR TITLE
Use properties for target versions for core and framework

### PR DESCRIPTION
**Pull request by lewing**
extracted from https://github.com/dotnet/runtime/pull/67436

### CODE REVIEW

**Review by radical — APPROVED** [review]

**Comment by radical** [comment]
Coreclr libraries test failure is https://github.com/dotnet/runtime/issues/67601 .

**Comment by lewing** [comment]
between the runfo errors and that I think that covers all the failures

**Comment by radical** [comment]
The other failures are all https://github.com/dotnet/runtime/issues/58927 :

```
    System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ZeroByteWrite_OtherDataReceivedSuccessfully(mode: SyncArray) [FAIL]
      System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
      ---- System.ComponentModel.Win32Exception : The client and server cannot communicate, because they do not possess a common algorithm.
      Stack Trace:
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs(160,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(723,0): at System.Net.Security.SecureChannel.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(610,0): at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(834,0): at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(777,0): at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(322,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamConformanceTests.cs(28,0): at System.Net.Security.Tests.SslStreamConformanceTests.CreateWrappedConnectedStreamsAsync(StreamPair wrapped, Boolean leaveOpen)
        /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs(2233,0): at System.IO.Tests.ConnectedStreamConformanceTests.ZeroByteWrite_OtherDataReceivedSuccessfully(ReadWriteMode mode)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs(138,0): at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs(605,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs(305,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
        /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs(147,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
```

**Review by steveisok — APPROVED** [review]

**Pull request merged**
