### PR TITLE
This fixes an issue with gradual decommit in scenarios where we have …

### PR DESCRIPTION
**Pull request by PeterSolMS**
…almost exclusively background GCs.

The problem is that we turn off the `gradual_decommit_in_progress_p` flag and rely on the `distribute_free_regions` method to turn it back on. If we only trigger a BGC however, `distribute_free_regions` won't get called and the flag will stay off, despite the `global_regions_to_decommit` list being non-empty.

This will cause regions to accumulate in the `global_regions_to_decommit` list, and eventual will cause the process to run out of memory.

The fix is to remember the setting of the `gradual_decommit_in_progress_p` flag in a local variable and turn `gradual_decommit_in_progress_p` back on if only a BGC was triggered.

This a partial fix to issue #78959.

### CODE REVIEW

**Comment by Maoni0** [comment]
what if we don't set `gradual_decommit_in_progress_p` before triggering a GC, and in `distribute_free_regions` we set it to FALSE if we have nothing on the global decommit list? so if we only triggered a BGC, `gradual_decommit_in_progress_p` would naturally be preserved?

**Comment by PeterSolMS** [comment]
There's a complication in that `decommit_ephemeral_segment_pages` also sets `gradual_decommit_in_progress_p`, so it's more natural to reset `gradual_decommit_in_progress_p` at the beginning of a GC, and set it when we discover we have something to decommit. So maybe the better solution is to just move resetting `gradual_decommit_in_progress_p` to a place where we are already sure we're going to do a blocking GC. We have to keep no GC regions in mind though to make sure decommitting and allocating don't conflict in this case.

**Comment by Maoni0** [comment]
yeh, you could just always reset it during a blocking GC, eg, during the `gc_join_decide_on_compaction` join. I think this would actually make no GC region work better because currently `gradual_decommit_in_progress_p` is always reset to false even when we do a GC for no GC region where we just allocate a bunch of regions but don't go into plan phase and later which will change the `gradual_decommit_in_progress_p` value. so if we had stuff to decommit it means it wouldn't continue when we get out of the GC that was done for no GC region.

**Comment by PeterSolMS** [comment]
The better solution appears to be to just test for the no gc region case in decommit_step.

**Review by Maoni0 — APPROVED** [review]
LGTM!

**Pull request merged**
