### PR TITLE
Enable AVX-512 for block unrollings (both copying and zeroing)

### LINKED ISSUE #83798: Optimize block unrolling operations using AVX-512
`CodeGen::genCodeForInitBlkUnroll` and `CodeGen::genCodeForCpBlkUnroll` have specific cases for optimizing using YMM registers. Enhance these to use ZMM registers if available. Consider the performance implications of the change; measure the improvements.

Related: update `Compiler::getUnrollThreshold` as appropriate.

### PR DESCRIPTION
**Pull request by EgorBo**
Closes https://github.com/dotnet/runtime/issues/83798

This PR enables AVX-512 for various unrollings using `GT_BLK` - it can be `stackalloc` zeroing, struct copy/initialization, `Unsafe.InitBloc/Unsafe.BlockCopy` calls, etc.

Examples:
```csharp
struct MyStruct {
    long a,b,c,d,e,f,g,h;
}

// Copying
MyStruct StructCopy(MyStruct s)
{
    return s;
}

// Zeroing
void StackallocZeroing()
{
    byte* ptr = stackalloc byte[300];
    Consume(ptr);
}
```
Codegen diff: https://www.diffchecker.com/cxc6UYLf/ (this PR is on the right)

As the result, it increases ranges where we previously used to fallback to `memcpy/memset` calls.

#### Benchmark:

```csharp
[Benchmark]
public void Test()
{
    var ptr = stackalloc long[42]; 
    Consume(ptr);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void Consume(void* ptr) { }
```

| Method |        Job |                 Toolchain |     Mean |
|------- |----------- |-------------------------- |---------:|
|   Test | Job-FEQJHS |    \Core_Root\corerun.exe | 4.229 ns |
|   Test | Job-CMMDYR | \Core_Root_PR\corerun.exe | **2.262 ns** |

_Ryzen 7950x, avx512, win-x64_

### CODE REVIEW

**Comment by EgorBo** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=253051&view=ms.vss-build-web.run-extensions-tab)
Size regressions are expected (call memset/memcpy is smaller)

**Comment by EgorBo** [comment]
Failures are mostly https://github.com/dotnet/runtime/issues/85403

**Comment by EgorBo** [comment]
benchmark:

```csharp
[Benchmark]
public void Test()
{
    var ptr = stackalloc long[42]; 
    Consume(ptr);
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void Consume(void* ptr) { }
}
```

| Method |        Job |                 Toolchain |     Mean |
|------- |----------- |-------------------------- |---------:|
|   Test | Job-FEQJHS |    \Core_Root\corerun.exe | 4.229 ns |
|   Test | Job-CMMDYR | \Core_Root_PR\corerun.exe | **2.262 ns** |

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
