### PR TITLE
Rename Installer test directory to tests to address https://github.com/dotnet/runtime/issues/254

### PR DESCRIPTION
**Pull request by ahmed-abdelrazek**
Rename the installer test directory to tests and making sure the .sln file reflect the change

address https://github.com/dotnet/runtime/issues/254

### CODE REVIEW

**Comment by ahmedflix25** [comment]
what is that error about?

**Comment by hoyosjs** [comment]
@danmosemsft @ahmedflix25 I am not too familiar with the infrastructure outside coreclr + shared files. However, the change seems to be thorough: the binlog shows these are the only references when building the tests. Thanks for fixing this. Now only the merge conflicts are left before merging (this was open for a while - sorry about that - but luckily it hasn't diverged). cc @NikolaMilosavljevic 

As for the failures, the builds are gone so I can't check what was going on. The workitem link for helix is https://helix.dot.net/api/2019-06-17/jobs/9e021e81-5eef-47eb-b943-01de108dbb33/workitems/Microsoft.Extensions.Hosting.Unit.Tests, the failed test was the following:
```json
"Results": [
        {
          "Name": "Microsoft.Extensions.Hosting.HostTests.CreateDefaultBuilder_ConfigJsonDoesReload",
          "Result": "Fail",
          "FailureExceptionType": "Xunit.Sdk.EqualException",
          "FailureMessage": "Assert.Equal() Failure\\nExpected: Hello ASP.NET Core: 036a0d3061f14e94a1b29503f4a97263\\nActual:   (null)",
          "FailureStackTrace": "   at Microsoft.Extensions.Hosting.HostTests.CreateDefaultBuilder_ConfigJsonDoesReload() in /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs:line 152\n--- End of stack trace from previous location ---",
          "Reason": "",
          "Duration": 1116,
          "Output": null,
          "FailureReason": null,
          "Type": "Microsoft.Extensions.Hosting.HostTests",
          "Method": "CreateDefaultBuilder_ConfigJsonDoesReload",
          "Arguments": ""
        }
      ]
```

However, it doesn't make sense to rerun the tests before rebasing this on top of master as the CI will run again then.

**Comment by danmosemsft** [comment]
Github rebases for us right? Restarted CI... Maybe you could help watch this one

**Comment by danmosemsft** [comment]
Never mind I see the conflicts. @ahmedflix25 sorry for the delay. Can you fix conflicts?

**Comment by ahmedflix25** [comment]
@danmosemsft that should do it

**Comment by hoyosjs** [comment]
@ahmedflix25  `src/installer/test` is several of the search paths. Looks like in the rebasing process your change, all changes to `eng/Subsets.props` got reset. Mind adding them back? I believe that's the only thing missing.

**Comment by ahmedflix25** [comment]
i updated the file

**Review by hoyosjs — APPROVED** [review]
Thanks @ahmedflix25

**Pull request merged**
