### PR TITLE
Revert "Restore Seperate test builds, but fix broken pipe (#35378)"

### PR DESCRIPTION
**Pull request by echesakov**
This reverts commit 6d64040a3a577e097e8d06ef72c10f700a17bf9c.

### CODE REVIEW

**Comment by hoyosjs** [comment]
@echesakovMSFT looks like all workitems are back after this. Thanks!

@sdmaclea @dotnet/runtime-infrastructure

**Comment by sdmaclea** [comment]
An explanation would be in order?
What workitems were missing?

**Comment by echesakovMSFT** [comment]
> An explanation would be in order?
> What workitems are missing?

@sdmaclea The intention of this PR was to quick test whether #35378 has broke coreclr testing in terms of reduced number of Helix work items - I didn't want (and prefer not to) revert someone's changes. I am closing this since I see you have followed on this in #35699

**Comment by sdmaclea** [comment]
@echesakovMSFT I initially assumed it had merged.

Not a problem.  I just wanted to know what the issue was so that I could help with a/the fix.

Thanks

**Pull request closed without merging**
