### PR TITLE
Update 7.0 to use Ubuntu 22.04 queues for Perf runs

### PR DESCRIPTION
**Pull request by DrewScoggins**
This updates the servicing branches to use the new Ubuntu 22.04 queues.

## Customer Impact

None, as this does not change product code.

## Regression?

No.

## Testing

Currently running on main branches successfully 

## Risk

Low. This is not a product change, and as such I expect the risk to be zero.

### CODE REVIEW

**Review by jeffschwMSFT — APPROVED** [review]
approve. we should consider this tell mode.  adding @carlossanlop to assist on when we can merge.

**Review by cincuranet — APPROVED** [review]

**Review by carlossanlop — APPROVED** [review]

**Comment by carlossanlop** [comment]
The release/7.0 branch is currently closed. Is it ok if we wait until the branches open again next month so that [your same change which was merged into release/7.0-staging](https://github.com/dotnet/runtime/pull/90768) is flowed into the release/7.0 branch?

**Comment by DrewScoggins** [comment]
If the branch is closed, does that mean that there will be no additional check-ins until the branch opens up? If that is the case then this should be fine, as long as this goes in before other things.

**Comment by carlossanlop** [comment]
You can merge all the changes you want into the `release/7.0-staging` and `release/6.0-staging` branches, but they will only flow once a month into `release/7.0` and `release/6.0` branches, when they open.

**Comment by carlossanlop** [comment]
Merging now. @DrewScoggins in the future, if you need to submit servicing PRs to the runtime repo, please target the `release/7.0-staging` and `release/6.0-staging` branches. Those are always open, and PR owners or area owners can merge them anytime.

**Pull request merged**
