### PR TITLE
Fix42292

### LINKED ISSUE #42292: PAL test exception_handling/pal_sxs/test1/paltest_pal_sxs_test1 fails in CI on OSX
### Description

The test fails with the following error:

```
dyld: Library not loaded: @rpath/libpaltest_pal_sxs_test1_dll1.dylib
Referenced from: /tmp/helix/working/AF150A08/w/BFDC0A33/e/exception_handling/pal_sxs/test1/paltest_pal_sxs_test1
Reason: image not found
```

### PR DESCRIPTION
**Pull request by sdmaclea**
Fixes #42292

/cc @mikem8361

### CODE REVIEW

**Comment by mikem8361** [comment]
Does this cause the same cmake warning as in issue #41084?

**Comment by sdmaclea** [comment]
> Does this cause the same cmake warning as in issue #41084?

I would assume so.

**Comment by sdmaclea** [comment]
ping

**Review by janvorli — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
