### PR TITLE
Fix race condition in ServiceProcess tests

### LINKED ISSUE #59297: Test failure System.ServiceProcess.Tests.ServiceBaseTests.PropagateExceptionFromOnStart
Run: [runtime-libraries-coreclr outerloop  20210917.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1368228&view=ms.vss-test-web.build-test-results-tab&runId=39938366&resultId=104048&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.ServiceProcess.Tests.ServiceBaseTests.PropagateExceptionFromOnStart

```
**Error message:**
```
Assert.Equal() Failure
Expected: 6
Actual:   5


Stack trace
   at System.ServiceProcess.Tests.ServiceBaseTests.PropagateExceptionFromOnStart() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceBaseTests.cs:line 208
```

### PR DESCRIPTION
**Pull request by ericstj**
Fixes https://github.com/dotnet/runtime/issues/59297

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]
LGTM, thank you. Why did this take so long to appear I wonder.

**Comment by danmoseley** [comment]
@ericstj do the outerloop tests even run as admin (so these tests actually run)?

I actually can't find the config in the Azdo UI that is outerloop. Looking at each of the Windows libraries test configs, I see a line like this:
```
2021-09-27T22:48:26.1877349Z ./build.sh -subset libs.pretest -rc release -configuration Debug -ci -arch x64 -framework net7.0  -testscope innerloop  /p:RuntimeOS=linux-musl   /p:RuntimeArtifactsPath=/home/vsts/work/1/s/artifacts/transport/coreclr  /p:RuntimeFlavor=coreclr /bl:/home/vsts/work/1/s/artifacts/log/Debug/overrideRuntimeFromLiveDrop.binlog
```

Note `-testscope innerloop`. So I'm not sure where the outerloop ones are, so I couldn't try to figure out if they run elevated.

**Comment by ericstj** [comment]
CHecking the logs.  @safern recommended this trigger to me.  Not sure if the Test UI is good for checking on passing tests because there are so many.  I might be able to find the console logs from build log spew.

**Comment by ericstj** [comment]
I actually don't see where libraries outerloop tests are even run.  I see coreclr runtime pri1, but no libraries tests.

**Comment by safern** [comment]
Oops this was my bad, there is a `runtime-coreclr outerloop` and a `runtime-libraries-coreclr outerloop` and when I searched for outerloop I saw both but when telling @ericstj the command to run it I accidentally missed the `-libraries` portion of the pipeline name 😞 . Sorry about that.

**Comment by ericstj** [comment]
No worries, next time I'll use `/azp run runtime-libraries-coreclr outerloop-windows`

**Comment by danmoseley** [comment]
Good info. @safern do you know (or know how to know) whether we run elevated?

**Comment by safern** [comment]
> @safern do you know (or know how to know) whether we run elevated?

IIRC helix do run elevated, but I'd like @MattGal to confirm that to be on the safe side.

**Comment by ericstj** [comment]
I opened https://github.com/dotnet/runtime/pull/59712 to find out (and get test coverage I was hoping to have in this PR).  Interestingly since its the same hash it doesn't retrigger the main validation builds, bonus resource savings :)

**Comment by MattGal** [comment]
> > @safern do you know (or know how to know) whether we run elevated?
> 
> IIRC helix do run elevated, but I'd like @MattGal to confirm that to be on the safe side.

Yes, you have the ability to start processes lower but the default is prompt-less elevated.  In the earliest days, we had some machines set up to run the helix client in Medium IL mode and it hit tons of problems with people's work items.

**Comment by ericstj** [comment]
🧬 == 🍯

**Comment by ericstj** [comment]
@MattGal were those issues in regular runs or just outerloop?  I remember at one point we said outerloop would get elevation but inner loop wouldn't.

**Comment by MattGal** [comment]
> @MattGal were those issues in regular runs or just outerloop? I remember at one point we said outerloop would get elevation but inner loop wouldn't.

The helix agents don't know or care about your concepts of inner/outer-loopiness.

**Comment by danmoseley** [comment]
> Yes, you have the ability to start processes lower but the default is prompt-less elevated. 

How is this done? It might be good to add one such run in the mix.

Also, is this the case for both Windows and Unix (elevated or su respectively)

**Comment by BruceForstall** [comment]
> @BruceForstall should the format job be clean? also, it has a bunch of errors like
> 
> ```
> Running: clang-tidy -fix -checks=-*,readability-braces*,modernize-use-nullptr  -header-filter=jit/.* -p=D:\a\1\s\src\coreclr\..\..\artifacts\obj\coreclr\windows.x64.Release\compile_commands.json D:\a\1\s\src\coreclr\jit\alloc.cpp
> Unhandled exception. System.ComponentModel.Win32Exception (193): The specified executable is not a valid application for this OS platform.
> ```

It should be, and is in subsequent runs.

The real failure was earlier:
```
Invoke-WebRequest : Unable to read data from the transport connection: An existing connection was forcibly closed by 
the remote host.
At D:\a\1\s\eng\formatting\download-tools.ps1:20 char:23
+ ...   $status = Invoke-WebRequest -Uri "$baseUri/$toolName.exe" -OutFile  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-WebRequest], IOException
    + FullyQualifiedErrorId : System.IO.IOException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

@jkoritzinsky Is this your new downloader from https://github.com/dotnet/runtime/pull/59374 not handling failure well?

**Comment by jkoritzinsky** [comment]
Yeah I think there’s a problem with the new downloader script. I’ll take a look into it next time I have cycles

**Pull request merged**
