### PR TITLE
Test component dependencies on built-in COM support

### PR DESCRIPTION
**Pull request by LakshanF**
Draft PR (not meant to be checked in) to test component dependencies on with disabling the latest built-in COM support. This PR helps with #51266

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
The CoreCLR runtime test failures and the hosting test failures all look like what I'd expect. Looks like there's something going on in the libraries tests though that probably needs some follow up investigation.

**Comment by jkoritzinsky** [comment]
Looks like this will be an issue with any test assembly that references `Microsoft.DotNet.RemoteExecutor` due to its dependency on CLRMD (Microsoft.Diagnostics.Runtime) 1.0.5. To my knowledge, the newer versions of CLRMD don't use `[ComImport]` in the core assembly, so if we update the Microsoft.Diagnostics.Runtime package dependency in Arcade, we can probably work around this.

**Comment by jkoritzinsky** [comment]
Also, we could (and probably should) update the runtime to explicitly fail loading the type and go the TypeLoadException/ReflectionTypeLoadException path instead of crashing.

**Comment by LakshanF** [comment]
Yep, its the same for `System.Collections.NonGeneric.Tests` & `System.Console.Tests` failures as well

**Comment by jkoritzinsky** [comment]
I've tested out the behavior on non-Windows for loading a `[ComImport]` class. On non-Windows, the behavior is to successfully load the class type without substituting the base type and have the constructor for the type fails with a PNSE exception.

I'll put out a PR to replicate this behavior on Windows when `__ComObject` is unavailable.

**Comment by jkoritzinsky** [comment]
I have a PR out with the graceful failure path at: https://github.com/dotnet/runtime/pull/54298

**Comment by jkoritzinsky** [comment]
With #54298 merged into main, I'll merge `main` into this PR so we can see what's still broken in the libraries tests.

**Comment by LakshanF** [comment]
Took a quick look at the 256 or so test failures for `net6.0-windows-Debug-x64-CoreCLR_checked-Windows.10.Amd64.Open` and they seem as expected

**Pull request closed without merging**
