### PR TITLE
Re-enable System.IO.Pipes.Tests on iOS-based platforms

### LINKED ISSUE #51335: System.IO.Pipes.Tests Fails on iOS/tvOS
All are failing with some form of `System.ArgumentOutOfRangeException : The path '/private/var/root/Library/Developer/CoreSimulator/Devices/EB1382F4-1DF5-494C-AEAE-7D7E33B18B3B/data/Containers/Data/Application/E75E9C2B-CFE1-4984-9370- ...`

System.IO.Pipes.Tests
System.IO.Pipes.Tests.NamedPipeTest_CreateServer.Unix_GetHandleOfNewServerStream_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_CreateServer.Create_PipeName_Direction_MaxInstances
System.IO.Pipes.Tests.NamedPipeTest_CreateServer.Create_PipeName
System.IO.Pipes.Tests.NamedPipeTest_Specific.MultipleWaitingClients_ServerServesOneAtATime
System.IO.Pipes.Tests.NamedPipeTest_Specific.Unix_GetImpersonationUserName_Succeed
System.IO.Pipes.Tests.NamedPipeTest_Specific.PipeTransmissionMode_Returns_Byte
System.IO.Pipes.Tests.NamedPipeTest_Specific.InvalidReadMode_Throws_ArgumentOutOfRangeException
System.IO.Pipes.Tests.NamedPipeTest_Specific.Unix_BufferSizeRoundtripping
System.IO.Pipes.Tests.NamedPipeTest_Specific.MultipleServers_ServeMultipleClientsConcurrently
System.IO.Pipes.Tests.NamedPipeTest_Specific.MaxNumberOfServerInstances_TooManyServers_Throws
System.IO.Pipes.Tests.NamedPipeTest_Specific.Unix_SetReadModeTo__PipeTransmissionModeByte
System.IO.Pipes.Tests.NamedPipeTest_Specific.ClientConnect_Throws_Timeout_When_Pipe_Not_Found
System.IO.Pipes.Tests.NamedPipeTest_Specific.ClientConnectAsync_Throws_Timeout_When_Pipe_Not_Found
System.IO.Pipes.Tests.NamedPipeTest_Specific.ConnectToNonExistentServer_Throws_TimeoutException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Write_DataReadFromDesiredOffset
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadWrite_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadAsync_DisconnectDuringRead_Returns0
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadAsync_ContinuesOnCurrentSynchronizationContextIfDesired
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.OperationsOnDisconnectedServer
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Windows_OperationsOnNamedServerWithDisposedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.WaitForConnectionOnAlreadyConnectedServer_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadAsync_ContinuesOnCurrentTaskSchedulerIfDesired
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadAsync_CancelPendingTask_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadWriteByte_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.CopyToAsync_AllDataCopied
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Read_Eof_Returns0
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadWriteAsync_PrecanceledOperations_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Read_DataStoredAtDesiredOffset
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadWrite_CustomMemoryManager_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Client_ReadWriteCancelledToken_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ZeroByteWrite_OtherDataReceivedSuccessfully
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Disposed_ThrowsObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ConnectOnAlreadyConnectedClient_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.DisposedServerPipe_Throws_ObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ZeroByteRead_BlocksUntilDataAvailableOrNops
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ConcurrentBidirectionalReadsWrites_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.CancelTokenOn_ServerWaitForConnectionAsync_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Server_ReadWriteCancelledToken_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadAsync_CancelPendingValueTask_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ClonedClient_ActsAsOriginalClient
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ArgumentValidation_ThrowsExpectedException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.OperationsOnUnconnectedServer
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.OperationsOnDisconnectedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Timeout_Roundtrips
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.DisposedClientPipe_Throws_ObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Flush_ValidOnReadableStream_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ClonedServer_ActsAsOriginalServer
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.Flush_ValidOnWriteableStreamWithNoData_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.ReadTimeout_Expires_Throws
System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn.OperationsOnUnconnectedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadWrite_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Read_Eof_Returns0
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadAsync_ContinuesOnCurrentSynchronizationContextIfDesired
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ZeroByteWrite_OtherDataReceivedSuccessfully
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadAsync_CancelPendingTask_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadAsync_ContinuesOnCurrentTaskSchedulerIfDesired
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.CopyToAsync_AllDataCopied
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadAsync_DisconnectDuringRead_Returns0
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.OperationsOnUnconnectedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.OperationsOnDisconnectedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ConnectOnAlreadyConnectedClient_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Server_ReadWriteCancelledToken_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.OperationsOnDisconnectedServer
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Windows_OperationsOnNamedServerWithDisposedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ClonedServer_ActsAsOriginalServer
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ZeroByteRead_BlocksUntilDataAvailableOrNops
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Write_DataReadFromDesiredOffset
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Flush_ValidOnReadableStream_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadWriteAsync_PrecanceledOperations_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.CancelTokenOn_ServerWaitForConnectionAsync_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.DisposedClientPipe_Throws_ObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadWrite_CustomMemoryManager_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Read_DataStoredAtDesiredOffset
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ClonedClient_ActsAsOriginalClient
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Client_ReadWriteCancelledToken_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ConcurrentBidirectionalReadsWrites_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.DisposedServerPipe_Throws_ObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Flush_ValidOnWriteableStreamWithNoData_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadWriteByte_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ArgumentValidation_ThrowsExpectedException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.OperationsOnUnconnectedServer
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.WaitForConnectionOnAlreadyConnectedServer_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadAsync_CancelPendingValueTask_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Timeout_Roundtrips
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.ReadTimeout_Expires_Throws
System.IO.Pipes.Tests.NamedPipeTest_ServerIn_ClientOut.Disposed_ThrowsObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadWrite_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadWrite_CustomMemoryManager_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Read_Eof_Returns0
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ZeroByteWrite_OtherDataReceivedSuccessfully
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadAsync_ContinuesOnCurrentSynchronizationContextIfDesired
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Disposed_ThrowsObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.CopyToAsync_AllDataCopied
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadWriteByte_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadAsync_ContinuesOnCurrentTaskSchedulerIfDesired
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ZeroByteRead_BlocksUntilDataAvailableOrNops
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.OperationsOnUnconnectedServer
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Write_DataReadFromDesiredOffset
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ConcurrentBidirectionalReadsWrites_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Server_ReadWriteCancelledToken_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadWriteAsync_PrecanceledOperations_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Flush_ValidOnReadableStream_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.OperationsOnDisconnectedServer
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.DisposedClientPipe_Throws_ObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.DisposedServerPipe_Throws_ObjectDisposedException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ClonedServer_ActsAsOriginalServer
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ConnectOnAlreadyConnectedClient_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Flush_ValidOnWriteableStreamWithNoData_Success
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.OperationsOnDisconnectedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.CancelTokenOn_ServerWaitForConnectionAsync_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.OperationsOnUnconnectedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadTimeout_Expires_Throws
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Read_DataStoredAtDesiredOffset
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadAsync_CancelPendingTask_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadAsync_DisconnectDuringRead_Returns0
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Client_ReadWriteCancelledToken_Throws_OperationCanceledException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ReadAsync_CancelPendingValueTask_ThrowsCancellationException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ArgumentValidation_ThrowsExpectedException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.WaitForConnectionOnAlreadyConnectedServer_Throws_InvalidOperationException
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.ClonedClient_ActsAsOriginalClient
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Windows_OperationsOnNamedServerWithDisposedClient
System.IO.Pipes.Tests.NamedPipeTest_ServerInOut_ClientInOut.Timeout_Roundtrips

### PR DESCRIPTION
**Pull request by directhex**
This seems fixed by a pipe name shortening at some point in the past

Closes: #51335

### CODE REVIEW

**Comment by directhex** [comment]
I think we can smash merge on here, the iOS & Catalyst jobs have already passed

**Review by steveisok — APPROVED** [review]

**Comment by steveisok** [comment]
Appears to be still failing 

https://dev.azure.com/dnceng/public/_build/results?buildId=1918613&view=ms.vss-test-web.build-test-results-tab&runId=49709938&resultId=108995&paneView=debug

**Comment by directhex** [comment]
Extracting my notes from a commit message:

tvOS has a MAX_PATH of 104 characters on domain sockets, and a 90 character value for GetTempPath. That gives us only 14 characters to play with, and temp filenames are 12 characters long. We cannot afford the `CoreFxPipe_` prefix on tvOS, with our tiny character path budget.

Check whether this fixes some or all of https://github.com/dotnet/runtime/issues/67853 and https://github.com/dotnet/runtime/issues/51390 too.

**Review by mdh1418 — APPROVED** [review]

**Comment by directhex** [comment]
I'm going to close this.

We need to PNSE pipes on iOS and tvOS. The 104 characters thing is a ruse - a) we get Permission Denied errors trying to bind to the socket if it fits in the path, and b) the path on iOS/tvOS Simulator is MUCH longer, but the limit isn't. We can't make domain sockets on there, because we need 184 characters minimum for the path & all we have is 104. It's impossible to support.

**Comment by directhex** [comment]
Actually, using this PR for testing, since I can't get anything running locally

**Pull request closed without merging**
