### PR TITLE
[mono/win] Increase stack size (reserve) to 8MB

### LINKED ISSUE #57141: [Wasm][AOT] The AOT compiler fails silently when running on Windows
### Description

The AOT compiler stops working at an unknown location, without any error message.

[aot-issue-assets.zip](https://github.com/dotnet/runtime/files/6962880/aot-issue-assets.zip)

Here's how to reproduce it:
```
cd extracted_archive
runtimes\browser-wasm/native/cross/browser-wasm/mono-aot-cross.exe --debug -v  -O=gsharedvt --aot=dedup-skip,llvmonly,asmonly,no-opt,static,direct-icalls,deterministic,nodebug,llvm-path="[...]\emsdk-2.0.23\emsdk/upstream/bin",interp,,depfile=./linker-out/Uno.UI.FluentTheme.dll.depfile,llvm-outfile=./Uno.UI.FluentTheme.dll.bc.tmp .\linker-out\Uno.UI.FluentTheme.dll
```

With `-v`, the last two output lines are:
```
rySingleton__2__Get_2_5287b__959_0_Windows_UI_Xaml_Media_SolidColorBrush
converting llvm method void Uno.UI.FluentTheme.GlobalStaticResources/ResourceDictionarySingleton__2:<Get_2_5288>b__960_0 (Windows.UI.Xaml.Media.SolidColorBrush)
void Uno.UI.FluentTheme.GlobalStaticResources/ResourceDictionarySingleton__2:<Get_2_5288>b__960_0 (Windows.UI.Xaml.Media.SolidColorBrush) emitted as Uno_UI_FluentTheme_Uno_UI_FluentTheme_GlobalStaticResources_ResourceDictionarySingleton__2__Get_2_5288b__960_0_Windows_UI_Xaml_Media_SolidColorBrush
converting llvm method object Uno.UI.FluentTheme.GlobalStaticResources/ResourceDictionarySingleton__2:<get_themeresources_6ae50ee5d890e499f2c9aa02298c937a_ResourceDictionary>b__963_0 (object)
```

The same command finishes properly when running under linux.

### Configuration

6696065ab0f

### Regression?

Unsure

### PR DESCRIPTION
**Pull request by radekdoulik**
Fix https://github.com/dotnet/runtime/issues/57141 in windows build.

Set the stack size (reserve) to 8MB, which is usually a default
on linux. This way we should get similar behavior on windows.

    > dumpbin.exe /headers artifacts\bin\mono\Browser.wasm.Debug\cross\browser-wasm\mono-aot-cross.exe|Select-String -Pattern stack

          800000 size of stack reserve
            1000 size of stack commit

### CODE REVIEW

**Review by lewing — COMMENTED** [review]
Should we be doing this on al Windows builds or just the cross compiler?

**Comment by lateralusX** [comment]
Did similar change on Mono couple of years ago, https://github.com/mono/mono/commit/29a2383333fdd4d49101d37ea61571747454aae9, so that will make default stack size for binary, 8MB for debug builds and matching CoreCLR stack size for release build 1.5 MB. All threads that we create later (throug our PAL API) will get default stack size of 1MB.

**Comment by radekdoulik** [comment]
> Reading up on the issue, so sounds like increasing the stack size is just a temporary fix for the underlying recursion problem in WASM AOT compiler?

I think we can keep this change long term, to have similar run conditions for the executables on windows and linux.

For the underlying recursion I have opened https://github.com/dotnet/runtime/issues/60266 where I would like to look closer at it.

**Comment by lateralusX** [comment]
I assume fix still keeps initial commit size of stack memory? If so we should just keep in mind that this will change stack size of main thread, it will also change default stack size of all embedders that creates threads without specific parameters to underlying CreateThread call. All threads created through our PAL will continue to get default stack size of 1MB (for example managed threads) unless explicitly setting stack size to larger value. This will only affect runtime when run through mono-sgen.exe and won't have any impact when running using coreclr host. We also had similar discussion when doing similar change in mono/mono, https://github.com/mono/mono/pull/14760#discussion_r290133060.

**Comment by radekdoulik** [comment]
Yes, this change should affect just `.exe` files we build. If we worry about `mono-sgen.exe`, I can make it affect just `mono-aot-cross.exe`.

**Review by lateralusX — APPROVED** [review]

**Review by lewing — APPROVED** [review]

**Pull request merged**
