### PR TITLE
[mono] Chain `SIGSEGV` native crashes to the default `SIGSEGV` handler

### LINKED ISSUE #106064: [mono][ios] Mono prevents crash logs from being generated in case `SIGSEGV` is raised from native code
### Description

While investigating the behavior of the crash reported in: https://github.com/dotnet/runtime/issues/105245 on iOS device we noticed that such error does not: 
1) Produce any useful information in the `Console.app`
2) It did not generate a crash report on a device

### Repro

1. Install official .NET 9 preview 6 release
2. Install MAUI workloads
3. Create a MAUI template app
4. Build/run it on a physical device in `Debug` mode:
```
dotnet build -f net9.0-ios -r ios-arm64 -t:Run -p:_DeviceName=XXXXXX
```
5. `Console.app` shows only that the program exited:
```
default  14:14:51.131793+0200  SpringBoard  [app<com.companyname.myapp(80F7F2DD-E9BB-43D8-AB25-7A0DE1A64558)>:6714] Process exited: <RBSProcessExitContext| voluntary>.
```
6. No crash logs are generated on a device

### Investigation

As initially assumed, the crash was not caused by asserting from the runtime (where we `abort()` properly), but instead the code was trying to read from an invalid memory address (something like 0xa8) so `SIGSEGV` was raised.
The mono's signal handler catches this, but does not remove it self as a `SIGSEGV` handler when it starts handling the signal. 
After the handling is done, the handler returns, but the same signal is caught again and on second handling the program exits out with -1 in case of double faulting: 
https://github.com/dotnet/runtime/blob/fdb741523a090a1bc31f70e336cc7783912bd089/src/mono/mono/mini/mini-posix.c#L789-L792 
This causes the app to silently exit not including any information about the crash.
Additionally, the messages from the signal handler (like information about the native and managed stack traces) that are using `g_async_safe_printf` are not shown in the system log.

FWIW In the signal handler we do unregister the runtime for some signals, but not for `SIGSEGV`: https://github.com/dotnet/runtime/blob/d606c601510c1a1a28cb6ef3550f12db049c0776/src/mono/mono/mini/mini-exceptions.c#L2932-L2942 

### Proposal

1. Investigate if we can unregister the `SIGSEGV` handler if we've detected that the signal it's not coming from managed code (to distinguish `NullReferenceException`)
5. Try using a platform specific logging mechanism so that messages from the signal handler end up in the system log when a fatal error occurs

PS Thanks @lambdageek for assistance

### PR DESCRIPTION
**Pull request by ivanpovazan**
### The problem

When `SIGSEGV` gets raised from native code Mono does not create crash reports on iOS-like platforms.
Instead our handler dumps native/managed stack traces and returns from the handler normally at:

https://github.com/dotnet/runtime/blob/c969265440b74e95429fb513e6d940d6c9bc2fd3/src/mono/mono/mini/mini-runtime.c#L3908-L3912

If it returns normally the code continues at the point the signal occurred, reexecuting the same instruction raising the signal again. This resulted in "double faults" in mono runtime, which we handled in such way that we exit from double faulting with `exit(-1)`:

https://github.com/dotnet/runtime/blob/c969265440b74e95429fb513e6d940d6c9bc2fd3/src/mono/mono/mini/mini-posix.c#L787-L792

preventing any crash log of being created. 

This is true even in .NET 7, stack trace of an app that crashes, but does not generate any crash report (full crash report: https://gist.github.com/ivanpovazan/798e5185f13dada2d80e9b023b179a18) :
```
...
0x109687394 - /Users/ivan/tmp/net7/MacCat7/bin/Debug/net7.0-maccatalyst/maccatalyst-arm64/MacCat7.app/Contents/MacOS/MacCat7 : xamarin_main
0x109ae3574 - /Users/ivan/tmp/net7/MacCat7/bin/Debug/net7.0-maccatalyst/maccatalyst-arm64/MacCat7.app/Contents/MacOS/MacCat7 : main
0x187bdc274 - /usr/lib/dyld : start

Exiting early due to double fault.
```

### Crash chaining

On mobile we enable crash chaining `mono_do_crash_chaining=true` and signal chaining `mono_do_signal_chaining=true` :
https://github.com/xamarin/xamarin-macios/blob/27e1882103ef4bc1c8db16c18533039ecc03ee3e/runtime/monovm-bridge.m#L83-L84
which means that after handling the native crash we chain the signal to any previous handlers defined for the signal. However, during registration of mono signal handlers, the default handler is being ignored:
https://github.com/dotnet/runtime/blob/c969265440b74e95429fb513e6d940d6c9bc2fd3/src/mono/mono/mini/mini-posix.c#L349-L356

For this reason there is no effect when `mono_chain_signal` is called in the basic setup (no user-defined handler).

## The fix

In this PR we are changing the logic of preserving original handlers by considering the default SIGSEGV handlers - when `sa.sa_handler == SIG_DFL` for signal chaining as well.
When the SIGSEGV native crash occurs and after we finish with our handler, we first try to chain the signal to any saved non-default handler - `sa.sa_handler != SIG_DFL`, if that fails, then we try chaining to the default one - `sa.sa_handler == SIG_DFL`. This way we avoid double faulting and properly propagate the SIGSEGV to the OS handler.

## Test

Tested on MAUI iOS and MacCatalyst apps where now crash reports are properly generated.
Android behaviour is left unchanged.

---
Fixes: https://github.com/dotnet/runtime/issues/106064

### CODE REVIEW

**Comment by lateralusX** [comment]
I'm a little curious if this works on Android or if we have the same issue there? As you said, this is really old code and nothing changed in the runtime around this for a long time, so a little curious how long this has been an issue. Did you end up without a chained signal handler on iOS? If that is the case, we hit this condition:

 if (! (previous_sa.sa_flags & SA_SIGINFO) && 
 		(SIG_DFL == previous_sa.sa_handler)) { 
 	/* it there is no sa_sigaction function and the sa_handler is default, we can safely ignore this */ 

Meaning we won't add anything to chain, that would lead to returning back from signal handler re-executing the faulting instruction,

**Comment by lateralusX** [comment]
An alternative could be to add an internal chained function in runtime in case you end up with default SIGSEGV handler, that function could restore the default handler and re-raise the signal. That will make sure we get the default handler executed and it won't change the current logic. The default handler should never return, so you could probably end that function ending with g_assert_not_reached.

**Comment by ivanpovazan** [comment]
> 'm a little curious if this works on Android or if we have the same issue there?

Will run some manual tests.

> Did you end up without a chained signal handler on iOS?

Yes, on iOS chaining has no effect, since we only have the default handler active at the point of registering our handlers.

> An alternative could be to add an internal chained function in runtime in case you end up with default SIGSEGV handler, that function could restore the default handler and re-raise the signal. 

You mean instead of calling `abort ()` as I did in this PR, to have a function which would do something like:

```c
   struct sigaction sa;
    sa.sa_handler = SIG_DFL;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = 0;
    sigaction(SIGSEGV, &sa, NULL);
    raise (SIGSEGV);
```
?

**Comment by lateralusX** [comment]
> You mean instead of calling `abort ()` as I did in this PR, to have a function which would do something like:

either like that or you could store the struct from original signal when installing it and then when restored the exact same struct back to make sure you get all flags restored, like what's done in remove_signal_handler, but I don't think we should remove anything from the table (its not locked), but you could get the old struct back and restore that.

**Comment by ivanpovazan** [comment]
> I'm a little curious if this works on Android

On Android, during registration of Mono signal handlers we get:
```
12-17 18:58:19.591 28872 28872 D Mono    : Saving old signal handler for signal 8.
12-17 18:58:19.591 28872 28872 D Mono    : Saving old signal handler for signal 4.
12-17 18:58:19.591 28872 28872 D Mono    : Saving old signal handler for signal 7.
12-17 18:58:19.591 28872 28872 D Mono    : Saving old signal handler for signal 31.
12-17 18:58:19.591 28872 28872 D Mono    : Saving old signal handler for signal 6.
12-17 18:58:19.591 28872 28872 D Mono    : Saving old signal handler for signal 11.
```
which means that original handlers on Android don't have `sigaction.sa_handler == SIG_DFL` and the crashes are properly chained to the original handlers once they are handled by Mono.

**Comment by lateralusX** [comment]
LGTM!

**Review by rolfbjarne — APPROVED** [review]

**Review by lateralusX — APPROVED** [review]

**Comment by ivanpovazan** [comment]
`runtime-extra-platforms` failures don't seem to be related.

**Comment by ivanpovazan** [comment]
@mikeparker104 should we backport this to net8.0 as well?

**Pull request merged**
