### PR TITLE
Make GetAssemblyName test more robust.

### LINKED ISSUE #80863: [Mono] System.Reflection.Metadata.Tests.MetadataReaderTests.GetAssemblyName is failing
The changes in #80581 cause the [rolling build of runtime-extra-platforms](https://dev.azure.com/dnceng-public/public/_build/results?buildId=142070&view=ms.vss-test-web.build-test-results-tab&runId=3085811&resultId=143807&paneView=debug) to fail.

Ref #77697

On `android-arm64`, `android-arm`, `tvos-arm64`:
```
Assert.Equal() Failure
Expected: MSIL
Actual:   None

Stack trace
   at System.Reflection.Metadata.Tests.MetadataReaderTests.GetAssemblyName() in /_/src/libraries/System.Reflection.Metadata/tests/Metadata/MetadataReaderTests.cs:line 3098
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

On `android-x64`, `tvossimulator-x64`:
```
Assert.Equal() Failure
Expected: MSIL
Actual:   Amd64
```

On `android-x86`:
```
Assert.Equal() Failure
Expected: MSIL
Actual:   X86
```

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #80863

### CODE REVIEW

**Review by simonrozsival — APPROVED** [review]

**Comment by VSadov** [comment]
the android tests are failing, but I can't tell if this is the same failure or something else.

**Comment by VSadov** [comment]
I will rebase and try running tests again.

**Comment by simonrozsival** [comment]
@VSadov the failing Android test `StartupHookForFunctionalTest` is unrelated (https://github.com/dotnet/runtime/pull/80909)

**Comment by VSadov** [comment]
Thanks!

**Pull request merged**
