### PR TITLE
Divide properties into: public, private, protected.

### PR DESCRIPTION
**Pull request by ilonatommy**
ToDo - transform all the other schemes the same way as objects if possible:
- [x] Object - done in this PR
- [x]  Scope - no need for separation, all scope values returned in result
- [x] ValueType - protected access modifier not handled, other values sorted into 3 groups - delegated to a separate issue #63082.
- [x]  Arrays - no need for separation, all array elements returned in result
- [X] MethodId - method does not have public/private properties so all values can be returned in "result". Evaluation of methods calls returning an object/struct has already object/struct schematic assigned, not method.
- [X] Pointer - complex managed types (e.g. objects) cannot have a pointer. At the same time, simple types don't have public/private properties so all pointer values can be returned in "result".
- [X] Cfo_res - call function cache cannot have public/private properties, so all values are returned in "result".

### CODE REVIEW

**Comment by ilonatommy** [comment]
To be merged after #62045.

**Comment by thaystg** [comment]
@ilonatommy , can we see any difference in VS using this PR, does the icons change? Can you paste a picture here?
Something like this, differente icons for protected and private attributes?
image

**Comment by ilonatommy** [comment]
@thaystg, I am pasting watch view from VS, they are not 100% the same as yours:
public-private

**Comment by thaystg** [comment]
@ilonatommy and debugging on chrome, do you see any different icon?

**Comment by ilonatommy** [comment]
In Browser there are different colors of ink for priv/pub and protected/internal:
browser pub-priv

**Comment by thaystg** [comment]
@ilonatommy I know that you changed the behavior of GetProperties to join Private and Internal to not break all the tests. But could you implement another version of GetProperties and add a new test checking if the values are added in the correct place (private and internal).

**Review by thaystg — APPROVED** [review]

**Pull request merged**
