### PR TITLE
[HeapVerify=2] Fix Assert failure "Pointer updated without using write barrier"

### PR DESCRIPTION
**Pull request by xiangzhai**
https://github.com/dotnet/runtime/issues/40058

\cc @Maoni0 

Thanks,
Leslie Zhai

### CODE REVIEW

**Comment by xiangzhai** [comment]
Linux ARM64 PASSED:

```
Starting program: /home/zhaixiang/runtime/artifacts/bin/coreclr/Linux.arm64.Debug/corerun /home/zhaixiang/coreclr-mips64-dev/bin/tests/Linux.arm64.Debug/GC/API/NoGCRegion/NoGC/NoGC.exe
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fb6cc61e0 (LWP 9010)]
[New Thread 0x7fb64c61e0 (LWP 9011)]
[New Thread 0x7fb5cc61e0 (LWP 9012)]
[New Thread 0x7fb54c61e0 (LWP 9013)]
[New Thread 0x7fb4ca61e0 (LWP 9014)]
[New Thread 0x7fb44a01e0 (LWP 9015)]
[New Thread 0x7fb366c1e0 (LWP 9016)]
[New Thread 0x7fb28be1e0 (LWP 9017)]
[New Thread 0x7fb28781e0 (LWP 9018)]
[New Thread 0x7fb20721e0 (LWP 9019)]
Workstation on 64-bit with 4 procs
=====allocating 100mb allowing full blocking GC first=====
[New Thread 0x7fb03401e0 (LWP 9020)]
[Thread 0x7fb20721e0 (LWP 9019) exited]

Calling TryStartNoGCRegion(..) with totalSize = 100 MB
100 MB SUCCEEDED, did 1 gen2 GCs
[New Thread 0x7fb20721e0 (LWP 9021)]
before GC: 978, after GC: 978
ended no gc region
[Thread 0x7fb20721e0 (LWP 9021) exited]
[New Thread 0x7fafb401e0 (LWP 9022)]
current GC count: 1954

=====allocating 100mb allowing full blocking GC first Succeeded=====
=====allocating 200mb allowing full blocking GC first=====
[New Thread 0x7fb20721e0 (LWP 9023)]
[Thread 0x7fafb401e0 (LWP 9022) exited]
[Thread 0x7fb20721e0 (LWP 9023) exited]

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 2934, after GC: 2934
ended no gc region
[Thread 0x7fb28781e0 (LWP 9018) exited]
current GC count: 3904
[New Thread 0x7fb20721e0 (LWP 9025)]

=====allocating 200mb allowing full blocking GC first Succeeded=====
=====allocating 200mb disallowing full blocking GC first=====
[New Thread 0x7fb28781e0 (LWP 9026)]
[Thread 0x7fb20721e0 (LWP 9025) exited]

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 4885, after GC: 4885
ended no gc region
[New Thread 0x7fafb401e0 (LWP 9028)]
[Thread 0x7fafb401e0 (LWP 9028) exited]
current GC count: 5855

=====allocating 200mb disallowing full blocking GC first Succeeded=====
=====allocating 400mb allowing full blocking GC first=====
[Thread 0x7fb28781e0 (LWP 9026) exited]
[Thread 0x7fb03401e0 (LWP 9020) exited]

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
By Design: 400 MB ArgumentOutOfRangeException totalSize is too large. For more information about setting the maximum size, see "Latency Modes" in http://go.microsoft.com/fwlink/?LinkId=522706 (Parameter 'totalSize')
current GC count: 7814
[New Thread 0x7fb03401e0 (LWP 9029)]
[New Thread 0x7fb20721e0 (LWP 9030)]
[New Thread 0x7fb28781e0 (LWP 9031)]
[New Thread 0x7fafb401e0 (LWP 9033)]

=====allocating 400mb allowing full blocking GC first Succeeded=====
=====allocating 400mb disallowing full blocking GC first=====
[Thread 0x7fb20721e0 (LWP 9030) exited]
[New Thread 0x7f0fffd1e0 (LWP 9034)]
[Thread 0x7f0fffd1e0 (LWP 9034) exited]

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
By Design: 400 MB ArgumentOutOfRangeException totalSize is too large. For more information about setting the maximum size, see "Latency Modes" in http://go.microsoft.com/fwlink/?LinkId=522706 (Parameter 'totalSize')
[Thread 0x7fb28781e0 (LWP 9031) exited]
[Thread 0x7fafb401e0 (LWP 9033) exited]
[Thread 0x7fb03401e0 (LWP 9029) exited]
current GC count: 9773

=====allocating 400mb disallowing full blocking GC first Succeeded=====
=====allocating 100mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 100 MB
100 MB SUCCEEDED, did 1 gen2 GCs
before GC: 10754, after GC: 10754
ended no gc region

current GC count: 11733

=====allocating 100mb allowing full blocking GC first Succeeded=====
=====allocating 200mb allowing full blocking GC first=====
[New Thread 0x7fafb401e0 (LWP 9150)]
[Thread 0x7fafb401e0 (LWP 9150) exited]

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 12716, after GC: 12716
ended no gc region
[New Thread 0x7fafb401e0 (LWP 9286)]
[Thread 0x7fafb401e0 (LWP 9286) exited]
current GC count: 13694

=====allocating 200mb allowing full blocking GC first Succeeded=====
=====allocating 200mb disallowing full blocking GC first=====
[New Thread 0x7fafb401e0 (LWP 9491)]
[Thread 0x7fafb401e0 (LWP 9491) exited]

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 14675, after GC: 14675
ended no gc region
[New Thread 0x7fafb401e0 (LWP 9506)]
[Thread 0x7fafb401e0 (LWP 9506) exited]
current GC count: 15652

=====allocating 200mb disallowing full blocking GC first Succeeded=====
=====allocating 400mb allowing full blocking GC first=====
[New Thread 0x7fafb401e0 (LWP 9512)]
[Thread 0x7fafb401e0 (LWP 9512) exited]

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 16634, after GC: 16634
ended no gc region
[New Thread 0x7fafb401e0 (LWP 9522)]
[Thread 0x7fafb401e0 (LWP 9522) exited]




current GC count: 17606

=====allocating 400mb allowing full blocking GC first Succeeded=====
=====allocating 400mb disallowing full blocking GC first=====
[New Thread 0x7fafb401e0 (LWP 9525)]
[Thread 0x7fafb401e0 (LWP 9525) exited]

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 18588, after GC: 18588
ended no gc region
[New Thread 0x7fafb401e0 (LWP 9533)]
[Thread 0x7fafb401e0 (LWP 9533) exited]
current GC count: 19560

=====allocating 400mb disallowing full blocking GC first Succeeded=====
=====allocating 400mb allowing full blocking GC first=====
[New Thread 0x7fafb401e0 (LWP 9536)]
[Thread 0x7fafb401e0 (LWP 9536) exited]
[New Thread 0x7fafb401e0 (LWP 9542)]
[Thread 0x7fafb401e0 (LWP 9542) exited]

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 20543, after GC: 20543
ended no gc region
[New Thread 0x7fafb401e0 (LWP 9554)]
[Thread 0x7fafb401e0 (LWP 9554) exited]
[New Thread 0x7fafb401e0 (LWP 9562)]
[Thread 0x7fafb401e0 (LWP 9562) exited]
current GC count: 21527

=====allocating 400mb allowing full blocking GC first Succeeded=====
[Thread 0x7fb5cc61e0 (LWP 9012) exited]
[Thread 0x7fb54c61e0 (LWP 9013) exited]
[Thread 0x7fb6cc61e0 (LWP 9010) exited]
[Thread 0x7fb28be1e0 (LWP 9017) exited]
[Thread 0x7fb366c1e0 (LWP 9016) exited]
[Thread 0x7fb4ca61e0 (LWP 9014) exited]
[Thread 0x7fb44a01e0 (LWP 9015) exited]
[Thread 0x7fb64c61e0 (LWP 9011) exited]
[Inferior 1 (process 9007) exited with code 0144]
```

False positive?  https://github.com/dotnet/runtime/pull/41375/checks?check_run_id=1029782590

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
MIPS64 also PASSED:

```
Workstation on 64-bit with 8 procs
=====allocating 100mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 100 MB
100 MB SUCCEEDED, did 1 gen2 GCs
before GC: 246, after GC: 246
ended no gc region
current GC count: 493

=====allocating 100mb allowing full blocking GC first Succeeded=====
=====allocating 200mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 739, after GC: 739
ended no gc region
current GC count: 985

=====allocating 200mb allowing full blocking GC first Succeeded=====
=====allocating 200mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 1231, after GC: 1231
ended no gc region
current GC count: 1478

=====allocating 200mb disallowing full blocking GC first Succeeded=====
=====allocating 400mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
By Design: 400 MB ArgumentOutOfRangeException totalSize is too large. For more information about setting the maximum size, see "Latency Modes" in http://go.microsoft.com/fwlink/?LinkId=522706 (Parameter 'totalSize')
current GC count: 1968

=====allocating 400mb allowing full blocking GC first Succeeded=====
=====allocating 400mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
By Design: 400 MB ArgumentOutOfRangeException totalSize is too large. For more information about setting the maximum size, see "Latency Modes" in http://go.microsoft.com/fwlink/?LinkId=522706 (Parameter 'totalSize')
current GC count: 2460

=====allocating 400mb disallowing full blocking GC first Succeeded=====
=====allocating 100mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 100 MB
100 MB SUCCEEDED, did 1 gen2 GCs
before GC: 2707, after GC: 2707
ended no gc region
current GC count: 2953

=====allocating 100mb allowing full blocking GC first Succeeded=====
=====allocating 200mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 3199, after GC: 3199
ended no gc region
current GC count: 3445

=====allocating 200mb allowing full blocking GC first Succeeded=====
=====allocating 200mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 200 MB
200 MB SUCCEEDED, did 1 gen2 GCs
before GC: 3692, after GC: 3692
ended no gc region
current GC count: 3938

=====allocating 200mb disallowing full blocking GC first Succeeded=====
=====allocating 400mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 4185, after GC: 4185
ended no gc region
current GC count: 4431

=====allocating 400mb allowing full blocking GC first Succeeded=====
=====allocating 400mb disallowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 4679, after GC: 4679
ended no gc region
current GC count: 4925

=====allocating 400mb disallowing full blocking GC first Succeeded=====
=====allocating 400mb allowing full blocking GC first=====

Calling TryStartNoGCRegion(..) with totalSize = 400 MB
400 MB SUCCEEDED, did 1 gen2 GCs
before GC: 5172, after GC: 5172
ended no gc region
current GC count: 5419

=====allocating 400mb allowing full blocking GC first Succeeded=====
100
```

Cheers,
Leslie Zhai

**Comment by Maoni0** [comment]
great; thanks! I see that this is not executed in Server GC anyway so moving it into stomp just works. that's nice! 

but why move it in GCHeap::Initialize? at that point g_gc_highest_address/g_gc_lowest_address are not initialized yet so initGCShadow wouldn't do anything. what are you seeing if you don't move this in GCHeap::Initialize?

**Comment by xiangzhai** [comment]
Hi @Maoni0 

Thanks for your review to point out my fault:

> but why move it in GCHeap::Initialize? at that point g_gc_highest_address/g_gc_lowest_address are not initialized yet so initGCShadow wouldn't do anything. what are you seeing if you don't move this in GCHeap::Initialize?

Yes!  It doesn't need to move.

Linux ARM64 and MIPS64 testcase still PASSED.

Please review it again.

Cheers,
Leslie Zhai

**Comment by Maoni0** [comment]
you should remove the initGCShadow in do_post_gc though; otherwise you are calling it twice in the same GC doing some duplicated work the 2nd time.

**Comment by xiangzhai** [comment]
> you should remove the initGCShadow in do_post_gc though; otherwise you are calling it twice in the same GC doing some duplicated work the 2nd time.

Nice catch!

Thanks,
Leslie Zhai

**Review by Maoni0 — APPROVED** [review]
LGTM; thank you for your contribution!

**Comment by xiangzhai** [comment]
You are welcome!

**Comment by mangod9** [comment]
Does this meet the .net 5 bar?

**Comment by Maoni0** [comment]
I'm ok with not porting this to 5.0 branch 'cause this is only used by folks who actively develop .net core and they will likely always be on master. @xiangzhai are you ok if we only kept this in master?

**Comment by xiangzhai** [comment]
I am OK!

**Comment by PeterSolMS** [comment]
I agree as well.

**Pull request merged**
