### PR TITLE
[mono][tests] Enable library tests on iOS device

### PR DESCRIPTION
**Pull request by kotlarmilos**
This PR aims to enable library tests for iOS devices. The proposed changes aim to improve the test coverage by enabling the following test groups:
 - ~~System.Numerics.Vectors~~ - Failing on the CI with error message `Exiting early due to double fault`
 - System.Net.NameResolution.Functional
 - System.IO.FileSystem

### CODE REVIEW

**Comment by steveisok** [comment]
@kotlarmilos I'm not opposed adding the 3 suites to list of what gets run on the rolling build.

tvOS is used to run the majority of libraries tests since we have enough devices to handle the combo of PR's, rolling build, and manual triggers. We do have more iOS devices now, but not enough to handle the entire load.

**Review by steveisok — APPROVED** [review]

**Comment by kotlarmilos** [comment]
After an offline discussion, we've agreed that, at this point, we can consider them covered by the tvOS pipelines, therefore they will not be added to the iOS pipeline as there are not enough devices to handle the entire load.

**Pull request closed without merging**
