### PR TITLE
Fix crash happening due to invalid pointer to free()

### PR DESCRIPTION
**Pull request by giritrivedi**
While working on netcore debugger for mono,the crash was happening. 
This crash was due to an invalid pointer to the free(). Valgrind was showing the 
traces of mismatch between the new() and delete(). After debugging the issue, 
even though hidden flag was set on shared library, objdump on the shared library 
showed that the overloaded new() operator was taken from a local scoped library, 
however overloaded delete() operator was overidden by defaults setting of 
underlying clang. Changed the fvisibility flag to ensure that it picks up 
the local new() and delete() overloaded operators.

### CODE REVIEW

**Comment by akoeplinger** [comment]
Reassigning to the correct area label. Looks like we have a build error though (the build output was already deleted).

/cc @lambdageek @vargaz

**Comment by lambdageek** [comment]
Why are we using `::operator new` and `::operator delete` in mono?  I assume this is for the dbgshim?  In that case, I would prefer setting the cflags on the dbgshim cmake (unless I misunderstood the issue).

/cc @thaystg

**Comment by giritrivedi** [comment]
@lambdageek will take care of the review comments. Looks good to me.

**Comment by giritrivedi** [comment]
@lambdageek , Adding the changes in dbgshim's CMake didn't help. So keeping it in its original place. 

Reinitiating the push since there were couple of unexpected failures in coreCLR which are nothing to do with current changes.

**Comment by lambdageek** [comment]
I don't think we should set this flag for all mono artifacts on all platforms.  Maybe dbgshim was the wrong component.  is it mscordbi that needs it? (src/mono/dlls/mscordbi) 

Also I don't understand this explanation:
> After debugging the issue,
> even though hidden flag was set on shared library, objdump on the shared library
> showed that the overloaded new() operator was taken from a local scoped library,
> however overloaded delete() operator was overidden by defaults setting of
> underlying clang. Changed the fvisibility flag to ensure that it picks up
> the local new() and delete() overloaded operators.

It sounds like some third party library provided `::operator new` with default visibility but not `::operator delete`?  Why would we expect that to work?

**Comment by giritrivedi** [comment]
@lambdageek , Keeping the changes in mscordbi will resolve the issue. Thanks for suggestions.

**Review by lambdageek — APPROVED** [review]
Thanks!

attn: @thaystg

**Pull request merged**
