### PR TITLE
[Ppc64le] Added memory patch thunking for function calls

### PR DESCRIPTION
**Pull request by alhad-deshpande**
This PR implements memory patch thunking for function calls atomically. This fixes sporadic crashes due to code being patched non-atomically including crashes observed in System.Text.RegularExpressions.Tests. This is similar to what was implemeted for s390x in PR [52783](https://github.com/dotnet/runtime/pull/52783)

### CODE REVIEW

**Comment by alhad-deshpande** [comment]
@vargaz 
We are targeting this PR for RC1 release. Can you please review it?

**Comment by Sapana-Khemkar** [comment]
@vargaz can you please review this PR? We are targeting it for RC1 which is planned on 12th August .

**Comment by akoeplinger** [comment]
@vargaz is on vacation right now, I've triggered a CI run to see if the test is fixed and we can merge the PR and he can review when he is back.

**Comment by alhad-deshpande** [comment]
> @vargaz is on vacation right now, I've triggered a CI run to see if the test is fixed and we can merge the PR and he can review when he is back.

@akoeplinger 
The System.Text.RegularExpressions.Tests is not fully fixed as mentioned above. But this PR fixes a large part of it where sporadic crashes occurs due to code being patched non-atomically. This has been fixed by memory patch thunking for function calls atomically. Please merge this PR as such crashes can occur anytime during code patching especially in multithreading environment and this PR fixes the same. We are targeting this PR for RC1.

**Comment by akoeplinger** [comment]
Ok

**Review by akoeplinger — APPROVED** [review]

**Pull request merged**
