### PR TITLE
Implement proper File System detection for Apple OSes

### LINKED ISSUE #69852: Implement proper File System detection for Apple OSes
In https://github.com/dotnet/runtime/pull/69484 I've tried to add the following line:

```cs
Debug.Assert(Enum.IsDefined(fileSystemType) || fstatfsResult == 0, $"GetFileSystemType returned {fstatfsResult}");
```

it turned out, that this assert was [failing](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-69484-merge-f4a9b55b864c48968d/System.IO.FileSystem.Tests/1/console.14be7626.log?helixlogtype=result) for some Apple OSes:

```log
Process terminated. Assertion failed.
GetFileSystemType returned 19
   at Interop.Sys.TryGetFileSystemType(SafeFileHandle fd, UnixFileSystemTypes& fileSystemType) in /_/src/libraries/Common/src/Interop/Unix/System.Native/Interop.UnixFileSystemTypes.cs:line 158
```

Based on [this](https://stackoverflow.com/questions/46345265/macos-correct-programmatic-way-to-determine-volume-info) StackOverflow question I can see that file system ids are version-specific (how cool is that?). Moreover, the [official docs](https://developer.apple.com/documentation/kernel/1523418-vfs_typenum?language=objc) say:

> Filesystem type numbers are an old construct; most filesystems just get a number assigned based on the order in which they are registered with the system.

We most likely need to use the BSD approach:

https://github.com/dotnet/runtime/blob/008f128b15a562cffd27cb10f78337be378b4f1a/src/native/libs/System.Native/pal_io.c#L1489-L1497

and extend it with Apple file system names (hfs, autofs, apfs) and our "made up" ids (to have a proper way to map to managed enum).

Usually I would address it as part of https://github.com/dotnet/runtime/pull/69484 but since I've started my honemoon last Friday, I am creating this issue to track it and reverting the `Debug.Assert` added to the original PR.

### LINKED ISSUE #72786: Unable to Copy/Create file on NFS share on macOS
### Description

dotnet on macOS is not able to copy files to a NFS share.

The NFS share is working perfectly from "Terminal" and "Finder", files can be created/copied and deleted all works.

But from a dotnet (Net6) application I get "UnauthorizedAccess", when writing. Read is working fine.

### Reproduction Steps

Setup NFS share on Linux

/etc/exports
```
/files	*(fsid=1,crossmnt,rw,insecure,all_squash,async,no_subtree_check,anonuid=99,anongid=99)
```

Mount on macOS from Finder "nfs://servername/files" will mount on "/Volumes/files"

Terminal and Finder can read and write.

### Expected behavior

Should be able to create directory and copy files

### Actual behavior
```
Type: System.UnauthorizedAccessException
Message: Access to the path '/Volumes/files/p10001-20000/p13001-14000/p13101-13200/13156/70487.pdf' is denied.

   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Create(String path)
   at OpenMedicus.IO.Files.CopyFileAsync(DbConnection conn, DbTransaction t, String sourceFile, String description, Int32 patientId, Int32 accountId, Boolean isHidden, IProgress`1 progress, Int32 count, Int32 index, CancellationToken token) in /XMedicus/libxcarefiles/Files.cs:line 180
   at OpenMedicus.IO.Files.CopyFileAsync(String[] files, String description, Int32 patientId, Int32 accountId, Boolean isHidden, IProgress`1 progress, CancellationToken token) in /XMedicus/libxcarefiles/Files.cs:line 109
   at OpenMedicus.IO.FileManager.CopyFileAsync(String[] files, String destpath, Int32 patientId, Int32 accountId, Boolean isHidden, IProgress`1 progress, CancellationToken token) in /XMedicus/libxcarefiles/Manager.cs:line 163
   at OpenMedicus.Journal.Summary.CopyFilesAsync(FileManager fm, List`1 files, Int32 episodeId, String desc, List`1 tags) in /XMedicus/components/summary/Summary.cs:line 800
   at OpenMedicus.Journal.Summary.AttachFilesAsync(List`1 files, String description) in /XMedicus/components/summary/Summary.cs:line 917
```
### Regression?

Not sure if it has been working before. (On Mono it worked).

### Known Workarounds

None

### Configuration

dotnet version: 6.0.6
macOS: Catalina

### Other information

_No response_

### PR DESCRIPTION
**Pull request by adamsitnik**
fixes #69852
fixes #72786

it's a draft until CI ensures me that my assumptions were right

### CODE REVIEW

**Review by jozkee — APPROVED** [review]

**Comment by adamsitnik** [comment]
Perf LGTM:

```ini
BenchmarkDotNet=v0.13.1.1823-nightly, OS=macOS Monterey 12.3.1 (21E258) [Darwin 21.4.0]
Intel Core i7-5557U CPU 3.10GHz (Broadwell), 1 CPU, 4 logical and 2 physical cores
.NET SDK=7.0.100-rc.2.22424.12
  [Host]     : .NET 7.0.0 (7.0.22.42212), X64 RyuJIT
  Job-HMRXXT : .NET 8.0.0 (42.42.42.42424), X64 RyuJIT
  Job-EKKFRV : .NET 8.0.0 (42.42.42.42424), X64 RyuJIT

LaunchCount=9
```

|    Method |     Toolchain | fileSize |      options |     Mean | Ratio |
|---------- |-------------- |--------- |------------- |---------:|------:|
| OpenClose | /main/corerun |     1024 |         None | 14.37 us |  1.00 |
| OpenClose |   /pr/corerun |     1024 |         None | 14.31 us |  1.00 |
|           |               |          |              |          |       |
| OpenClose | /main/corerun |     1024 | Asynchronous | 14.17 us |  1.00 |
| OpenClose |   /pr/corerun |     1024 | Asynchronous | 14.12 us |  1.00 |

**Comment by adamsitnik** [comment]
Failures are unrelated (#74170, helix deadletters for NativeAOT, timeouts)

**Pull request merged**
