### PR TITLE
Use the regType for extracting the RegisterType

### LINKED ISSUE #74373: Assertion failed 'srcInterval->registerType == registerType' in 'JIT.HardwareIntrinsics.Arm.Helpers:BitwiseSelect(float,float,float):float' during 'Linear scan register alloc'
Linux-arm64 random JitStress

https://dev.azure.com/dnceng/public/_build/results?buildId=1957444&view=ms.vss-test-web.build-test-results-tab&runId=50310504&resultId=107552&paneView=debug

```
+ cat /root/helix/work/workitem/u/SetStressModes_jitstress_random_2.sh
#!/usr/bin/env bash
export COMPlus_TieredCompilation=0
export COMPlus_DbgEnableMiniDump=1
export COMPlus_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export COMPlus_JitStress=3db

...

    JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_Part2_ro/AdvSimd_Part2_ro.sh [FAIL]
      
      Assert failure(PID 272 [0x00000110], Thread: 272 [0x0110]): Assertion failed 'srcInterval->registerType == registerType' in 'JIT.HardwareIntrinsics.Arm.Helpers:BitwiseSelect(float,float,float):float' during 'Linear scan register alloc' (IL size 29; hash 0x40376f3b; FullOpts)
      
          File: /__w/1/s/src/coreclr/jit/lsrabuild.cpp Line: 3531
          Image: /root/helix/work/correlation/corerun
```

@kunalspathak @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by kunalspathak**
Thanks @SingleAccretion for quickly triaging.

Fixes: https://github.com/dotnet/runtime/issues/74373

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Review by SingleAccretion — APPROVED** [review]

**Review by jakobbotsch — APPROVED** [review]

**Comment by BruceForstall** [comment]
@kunalspathak Backport to 7?

**Comment by kunalspathak** [comment]
> @kunalspathak Backport to 7?

/backport to release/7.0

**Pull request merged**
