### PR TITLE
Building and Publishing Windows-Compat pack

### PR DESCRIPTION
**Pull request by Anipik**
We are shipping a new version of Compact pack due to changes in system.diagnostics.eventlog and system.Speech

### CODE REVIEW

**Comment by danmosemsft** [comment]
there are 4 PR's all editing the same place in libraries-packages.proj that you will need to resolve. One way to make auto-merge more likely in the future would be to add some arbitrary merge markers, like this:
```
    <!-- If setting BuildAllOOBPackages to false, add bellow the individual OOB packages you want to continue to build -->
    <! -- This is merge marker 1 to help automerge --> 
    <ProjectReference Include="$(LibrariesProjectRoot)\System.Speech\pkg\System.Speech.pkgproj" Condition="'$(BuildAllConfigurations)' == 'true'" />
    <! -- This is merge marker 2 to help automerge -->
    <! -- This is merge marker 3 to help automerge -->
    <! -- This is merge marker 4 to help automerge -->
    <! -- This is merge marker 5 to help automerge -->
    <! -- This is merge marker 6 to help automerge -->
  </ItemGroup>	  </ItemGroup>
```
then so long as each PR puts their add between different comments, I would expect auto merge to be successful.

**Comment by Anipik** [comment]
I will add the empty markers in this PR(after the other 3 have been merged)

**Comment by ericstj** [comment]
@Anipik I think you were mentioning that in 6.0 we'll distribute this bit into the projects, rather than centrally, which will mitigate these conflicts in the future.

**Comment by Anipik** [comment]
> @Anipik I think you were mentioning that in 6.0 we'll distribute this bit into the projects, rather than centrally, which will mitigate these conflicts in the future.

thats true, i was planning to do this for just 5.0

**Comment by safern** [comment]
Did we bump the diagnostics dependency version on the compact pack?

**Comment by ericstj** [comment]
> Did we bump the diagnostics dependency version on the compact pack?

I updated the baseline in the packageIndex for both packages I changed (EventLog and PerfCounters)

**Review by ericstj — APPROVED** [review]

**Comment by safern** [comment]
That will not be enough, the versions are pinned in the compat pack due to infra limitations to correctly calculate the versions for indexed dependencies in the release branch: https://github.com/dotnet/runtime/blob/792ab31b3cc0bb71809ca5728f086927025264dd/src/libraries/pkg/Microsoft.Windows.Compatibility/Microsoft.Windows.Compatibility.pkgproj#L4

https://github.com/dotnet/runtime/pull/45905#issuecomment-743440040

**Comment by Anipik** [comment]
I verified the package the versions and those are correct i.e 5.0.1 for eventlog and performanceCounter, 5.0.0 for speech

**Pull request merged**
