### PR TITLE
[browser] Fix webcil lazy loading and satellite assemblies in Wasm SDK

### PR DESCRIPTION
**Pull request by pavelsavara**
- Fix lazy loading assemblies transformed to webcil
- Fix satellite assemblies  transformed to webcil

### CODE REVIEW

**Comment by lewing** [comment]
This might get the test to build and publish it will likely still fail at runtime

**Comment by maraf** [comment]
Probably needs runtime change in https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L396

**Review by lewing — APPROVED** [review]

**Comment by lewing** [comment]
we should get away from logic based on fixed extensions all together but I'm ok with this to unblock

**Review by maraf — APPROVED** [review]

**Comment by lewing** [comment]
we may need to backport this one

**Pull request merged**
