### PR TITLE
Revert "[interp] Add MINT_STELEM_VT_NOREF (#87161)"

### PR DESCRIPTION
**Pull request by kg**
This reverts commit e05b3e752e89259454fbd919e4be34cc7c3ed937.

https://github.com/dotnet/perf-autofiling-issues/issues/19756

### CODE REVIEW

**Comment by BrzVlad** [comment]
This is overkill and those tests results seem like garbage. I doubt this code path is even hit in them

**Comment by kg** [comment]
My only guess is that adding a new opcode deoptimized interp_exec_method

**Review by vargaz — APPROVED** [review]

**Comment by vargaz** [comment]
Is this reproducible locally ?

**Comment by kg** [comment]
I'm trying to do local runs, but benchmark timings are extremely variable on my PC for wasm

**Comment by kg** [comment]
> I'm trying to do local runs, but benchmark timings are extremely variable on my PC for wasm

A local run of Perf_Vector4.EqualityOperatorBenchmark doesn't show a regression from this change, and I wouldn't expect one since that benchmark doesn't seem to use arrays. But all of these benchmarks that regressed seem to have stayed slower in the time since, so I'm not sure how to explain this other than the additional opcode making interp_exec_method slower.

I previously looked through v8 and llvm's implementation of br_table and didn't see any optimization cliffs, though.

**Comment by lewing** [comment]
do we see the same regression on wasm?

**Comment by kg** [comment]
> do we see the same regression on wasm?

To be clear, I ran it on wasm locally and didn't see a regression. The affected code shouldn't be running for most/all of these benchmarks either, so I don't understand why it got slower on any target

**Comment by kg** [comment]
> > do we see the same regression on wasm?
> 
> To be clear, I ran it on wasm locally and didn't see a regression. The affected code shouldn't be running for most/all of these benchmarks either, so I don't understand why it got slower on any target

Based on the graphs it looks like these didn't get slower on wasm, only linux? So that explains why I couldn't repro it in my local tests. I may try and set up a way to do a local linux run of these

image

**Comment by lewing** [comment]
yeah, the linked issue is linux only and I think we should hold off on reverting unless there are objections

**Pull request closed without merging**
