### PR TITLE
Force 2 iterations of OptRepeat

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by EgorBo** [comment]
Ouch, quite expensive (@SingleAccretion predicted similar numbers)
It's still nice to have JitOptRepeat in good shape and it can point us to missing opportunities.
Maybe there are some hidden fructs to reduce the TP? E.g.

- Don't run it for huge methods (e.g. non-linear complexity for number of basic blocks, etc)
- Run on demand? E.g. if RBO removes a branch and invalidates dominators or Assertprop propagates a constant and potentionally enables more opportunities for RBO?
- Don't run some opts in the 2nd iter like assertprop and rangecheck if they don't contribute to the final diffs a lot

But of course that is quite non-trivial to guess whether you might benefit from the 2nd iter or not. Maybe if we study these diffs we'll figure out what we benefit the most from in most cases?

**Comment by BruceForstall** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=625395&view=ms.vss-build-web.run-extensions-tab)

Code size improvement from about 3 to 4.5MB. TP cost of about 20%.

**Comment by BruceForstall** [comment]
> Ouch, quite expensive (@SingleAccretion predicted similar numbers) It's still nice to have JitOptRepeat in good shape and it can point us to missing opportunities. Maybe there are some hidden fruits to reduce the TP? E.g.
> 
> * Don't run it for huge methods (e.g. non-linear complexity for number of basic blocks, etc)
> * Run on demand? E.g. if RBO removes a branch and invalidates dominators or Assertprop propagates a constant and potentionally enables more opportunities for RBO?
> * Don't run some opts in the 2nd iter like assertprop and rangecheck if they don't contribute to the final diffs a lot
> 
> But of course that is quite non-trivial to guess whether you might benefit from the 2nd iter or not. Maybe if we study these diffs we'll figure out what we benefit the most from in most cases?

Lots of good ideas here. I agree that we wouldn't want to run it unconditionally. But running on big methods might be the _most_ beneficial. And maybe we'd be willing to take the 20% TP cost for NAOT compiles.

**Comment by BruceForstall** [comment]
cc @dotnet/jit-contrib 

Example of enabling JitOptRepeat always, with 2 iterations. Code size improvement from about 3 to 4.5MB. TP cost of about 20%.

**Comment by BruceForstall** [comment]
[Diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=626522&view=ms.vss-build-web.run-extensions-tab)

**Comment by BruceForstall** [comment]
image
image
image

**Comment by BruceForstall** [comment]
Here is a run of asmdiffs on win-x64 between JitOptRepeat 2 and 3 iterations, showing there is some benefit to be had to run more than twice.


Diffs are based on <span style="color:#1460aa">2,384,245</span> contexts (<span style="color:#1460aa">931,974</span> MinOpts, <span style="color:#1460aa">1,452,271</span> FullOpts).

<span style="color:#d35400">MISSED</span> contexts: base: <span style="color:#d35400">7,980 (0.33%)</span>, diff: <span style="color:#d35400">8,122 (0.34%)</span>

Base JIT options: JitOptRepeat#*

Diff JIT options: JitOptRepeat#*;JitOptRepeatCount#3


<details>
<summary>Overall (<span style="color:green">-149,570</span> bytes)</summary>
<div style="margin-left:1em">

|Collection|Base size (bytes)|Diff size (bytes)|PerfScore in Diffs
|---|--:|--:|--:|
|benchmarks.run.windows.x64.checked.mch|8,524,826|<span style="color:green">-2,200</span>|<span style="color:green">-1.16%</span>|
|benchmarks.run_pgo.windows.x64.checked.mch|35,113,082|<span style="color:green">-8,390</span>|<span style="color:red">+36.54%</span>|
|benchmarks.run_tiered.windows.x64.checked.mch|12,444,446|<span style="color:green">-1,131</span>|<span style="color:green">-1.25%</span>|
|coreclr_tests.run.windows.x64.checked.mch|398,753,006|<span style="color:green">-53,627</span>|<span style="color:red">+50.20%</span>|
|libraries.crossgen2.windows.x64.checked.mch|44,921,842|<span style="color:green">-7,029</span>|<span style="color:green">-0.59%</span>|
|libraries.pmi.windows.x64.checked.mch|61,240,935|<span style="color:green">-6,528</span>|<span style="color:red">+125.54%</span>|
|libraries_tests.run.windows.x64.Release.mch|274,740,189|<span style="color:green">-23,431</span>|<span style="color:red">+20.96%</span>|
|libraries_tests_no_tiered_compilation.run.windows.x64.Release.mch|135,902,387|<span style="color:green">-44,863</span>|<span style="color:red">+160.81%</span>|
|realworld.run.windows.x64.checked.mch|11,060,751|<span style="color:green">-1,196</span>|<span style="color:green">-0.12%</span>|
|smoke_tests.nativeaot.windows.x64.checked.mch|3,565,641|<span style="color:green">-1,175</span>|<span style="color:green">-0.83%</span>|


</div></details>

<details>
<summary>FullOpts (<span style="color:green">-149,570</span> bytes)</summary>
<div style="margin-left:1em">

|Collection|Base size (bytes)|Diff size (bytes)|PerfScore in Diffs
|---|--:|--:|--:|
|benchmarks.run.windows.x64.checked.mch|8,524,465|<span style="color:green">-2,200</span>|<span style="color:green">-1.16%</span>|
|benchmarks.run_pgo.windows.x64.checked.mch|20,929,241|<span style="color:green">-8,390</span>|<span style="color:red">+36.54%</span>|
|benchmarks.run_tiered.windows.x64.checked.mch|3,279,500|<span style="color:green">-1,131</span>|<span style="color:green">-1.25%</span>|
|coreclr_tests.run.windows.x64.checked.mch|118,412,975|<span style="color:green">-53,627</span>|<span style="color:red">+50.20%</span>|
|libraries.crossgen2.windows.x64.checked.mch|44,920,652|<span style="color:green">-7,029</span>|<span style="color:green">-0.59%</span>|
|libraries.pmi.windows.x64.checked.mch|61,127,434|<span style="color:green">-6,528</span>|<span style="color:red">+125.54%</span>|
|libraries_tests.run.windows.x64.Release.mch|102,077,791|<span style="color:green">-23,431</span>|<span style="color:red">+20.96%</span>|
|libraries_tests_no_tiered_compilation.run.windows.x64.Release.mch|125,588,969|<span style="color:green">-44,863</span>|<span style="color:red">+160.81%</span>|
|realworld.run.windows.x64.checked.mch|10,647,587|<span style="color:green">-1,196</span>|<span style="color:green">-0.12%</span>|
|smoke_tests.nativeaot.windows.x64.checked.mch|3,565,548|<span style="color:green">-1,175</span>|<span style="color:green">-0.83%</span>|


</div></details>

**Comment by EgorBo** [comment]
Sounds like 2 iterations are enough? 🙂 It'd be nice to have a breakdown TP report like @jakobbotsch[ did here for example](https://github.com/dotnet/runtime/pull/100344#issuecomment-2034456893) to know what is the most expensive thing

**Comment by BruceForstall** [comment]
Here's a run of asmdiffs on win-x64 between JitOptRepeat 4 and 5 iterations.

Diffs are based on <span style="color:#1460aa">2,384,205</span> contexts (<span style="color:#1460aa">931,974</span> MinOpts, <span style="color:#1460aa">1,452,231</span> FullOpts).

<span style="color:#d35400">MISSED</span> contexts: base: <span style="color:#d35400">8,157 (0.34%)</span>, diff: <span style="color:#d35400">8,162 (0.34%)</span>

Base JIT options: JitOptRepeat#*;JitOptRepeatCount#4

Diff JIT options: JitOptRepeat#*;JitOptRepeatCount#5


<details>
<summary>Overall (<span style="color:green">-14,538</span> bytes)</summary>
<div style="margin-left:1em">

|Collection|Base size (bytes)|Diff size (bytes)|PerfScore in Diffs
|---|--:|--:|--:|
|benchmarks.run.windows.x64.checked.mch|8,521,472|<span style="color:green">-388</span>|<span style="color:green">-0.12%</span>|
|benchmarks.run_pgo.windows.x64.checked.mch|35,100,803|<span style="color:green">-1,606</span>|<span style="color:red">+79.30%</span>|
|benchmarks.run_tiered.windows.x64.checked.mch|12,443,020|<span style="color:green">-318</span>|<span style="color:green">-0.19%</span>|
|coreclr_tests.run.windows.x64.checked.mch|398,634,943|<span style="color:green">-28,742</span>|<span style="color:red">+118.37%</span>|
|libraries.crossgen2.windows.x64.checked.mch|44,911,074|<span style="color:red">+2,441</span>|<span style="color:green">-0.31%</span>|
|libraries.pmi.windows.x64.checked.mch|61,206,674|<span style="color:red">+4,410</span>|<span style="color:red">+746.88%</span>|
|libraries_tests.run.windows.x64.Release.mch|274,717,234|<span style="color:red">+4,295</span>|<span style="color:red">+46.76%</span>|
|libraries_tests_no_tiered_compilation.run.windows.x64.Release.mch|135,838,676|<span style="color:red">+5,179</span>|<span style="color:red">+577.00%</span>|
|realworld.run.windows.x64.checked.mch|11,057,515|<span style="color:red">+452</span>|<span style="color:red">+0.04%</span>|
|smoke_tests.nativeaot.windows.x64.checked.mch|3,563,982|<span style="color:green">-261</span>|<span style="color:green">-0.02%</span>|


</div></details>

<details>
<summary>FullOpts (<span style="color:green">-14,538</span> bytes)</summary>
<div style="margin-left:1em">

|Collection|Base size (bytes)|Diff size (bytes)|PerfScore in Diffs
|---|--:|--:|--:|
|benchmarks.run.windows.x64.checked.mch|8,521,111|<span style="color:green">-388</span>|<span style="color:green">-0.12%</span>|
|benchmarks.run_pgo.windows.x64.checked.mch|20,916,962|<span style="color:green">-1,606</span>|<span style="color:red">+79.30%</span>|
|benchmarks.run_tiered.windows.x64.checked.mch|3,278,074|<span style="color:green">-318</span>|<span style="color:green">-0.19%</span>|
|coreclr_tests.run.windows.x64.checked.mch|118,294,912|<span style="color:green">-28,742</span>|<span style="color:red">+118.37%</span>|
|libraries.crossgen2.windows.x64.checked.mch|44,909,884|<span style="color:red">+2,441</span>|<span style="color:green">-0.31%</span>|
|libraries.pmi.windows.x64.checked.mch|61,093,173|<span style="color:red">+4,410</span>|<span style="color:red">+746.88%</span>|
|libraries_tests.run.windows.x64.Release.mch|102,054,836|<span style="color:red">+4,295</span>|<span style="color:red">+46.76%</span>|
|libraries_tests_no_tiered_compilation.run.windows.x64.Release.mch|125,525,258|<span style="color:red">+5,179</span>|<span style="color:red">+577.00%</span>|
|realworld.run.windows.x64.checked.mch|10,644,351|<span style="color:red">+452</span>|<span style="color:red">+0.04%</span>|
|smoke_tests.nativeaot.windows.x64.checked.mch|3,563,889|<span style="color:green">-261</span>|<span style="color:green">-0.02%</span>|


</div></details>

**Comment by BruceForstall** [comment]
And just "for fun", here is asmdiffs on win-x64 between JitOptRepeat 8 and 9 iterations! Yes, there are still diffs. One question: are optimization changes somehow monotonic, or is it possible the optimizations are oscillating (e.g., one iteration creates a CSE, another removes it)?

Diffs are based on <span style="color:#1460aa">2,384,201</span> contexts (<span style="color:#1460aa">931,974</span> MinOpts, <span style="color:#1460aa">1,452,227</span> FullOpts).

<span style="color:#d35400">MISSED</span> contexts: <span style="color:#d35400">8,166 (0.34%)</span>

Base JIT options: JitOptRepeat#*;JitOptRepeatCount#8

Diff JIT options: JitOptRepeat#*;JitOptRepeatCount#9


<details>
<summary>Overall (<span style="color:red">+4,080</span> bytes)</summary>
<div style="margin-left:1em">

|Collection|Base size (bytes)|Diff size (bytes)|PerfScore in Diffs
|---|--:|--:|--:|
|benchmarks.run.windows.x64.checked.mch|8,520,257|<span style="color:green">-64</span>|<span style="color:green">-0.02%</span>|
|benchmarks.run_pgo.windows.x64.checked.mch|35,095,669|<span style="color:green">-227</span>|<span style="color:red">+87.21%</span>|
|benchmarks.run_tiered.windows.x64.checked.mch|12,442,539|<span style="color:green">-38</span>|<span style="color:red">+0.00%</span>|
|coreclr_tests.run.windows.x64.checked.mch|398,475,394|<span style="color:green">-1,406</span>|<span style="color:red">+2445.47%</span>|
|libraries.crossgen2.windows.x64.checked.mch|44,910,655|<span style="color:red">+1,299</span>|<span style="color:green">-0.03%</span>|
|libraries.pmi.windows.x64.checked.mch|61,193,216|<span style="color:red">+2,633</span>|<span style="color:red">+2193.97%</span>|
|libraries_tests.run.windows.x64.Release.mch|274,706,838|<span style="color:red">+3,977</span>|<span style="color:red">+61.81%</span>|
|libraries_tests_no_tiered_compilation.run.windows.x64.Release.mch|135,827,290|<span style="color:green">-2,776</span>|<span style="color:red">+1920.18%</span>|
|realworld.run.windows.x64.checked.mch|11,057,374|<span style="color:red">+600</span>|<span style="color:red">+0.00%</span>|
|smoke_tests.nativeaot.windows.x64.checked.mch|3,563,813|<span style="color:red">+82</span>|<span style="color:red">+0.07%</span>|


</div></details>

<details>
<summary>FullOpts (<span style="color:red">+4,080</span> bytes)</summary>
<div style="margin-left:1em">

|Collection|Base size (bytes)|Diff size (bytes)|PerfScore in Diffs
|---|--:|--:|--:|
|benchmarks.run.windows.x64.checked.mch|8,519,896|<span style="color:green">-64</span>|<span style="color:green">-0.02%</span>|
|benchmarks.run_pgo.windows.x64.checked.mch|20,911,828|<span style="color:green">-227</span>|<span style="color:red">+87.21%</span>|
|benchmarks.run_tiered.windows.x64.checked.mch|3,277,593|<span style="color:green">-38</span>|<span style="color:red">+0.00%</span>|
|coreclr_tests.run.windows.x64.checked.mch|118,135,363|<span style="color:green">-1,406</span>|<span style="color:red">+2445.47%</span>|
|libraries.crossgen2.windows.x64.checked.mch|44,909,465|<span style="color:red">+1,299</span>|<span style="color:green">-0.03%</span>|
|libraries.pmi.windows.x64.checked.mch|61,079,715|<span style="color:red">+2,633</span>|<span style="color:red">+2193.97%</span>|
|libraries_tests.run.windows.x64.Release.mch|102,044,440|<span style="color:red">+3,977</span>|<span style="color:red">+61.81%</span>|
|libraries_tests_no_tiered_compilation.run.windows.x64.Release.mch|125,513,872|<span style="color:green">-2,776</span>|<span style="color:red">+1920.18%</span>|
|realworld.run.windows.x64.checked.mch|10,644,210|<span style="color:red">+600</span>|<span style="color:red">+0.00%</span>|
|smoke_tests.nativeaot.windows.x64.checked.mch|3,563,720|<span style="color:red">+82</span>|<span style="color:red">+0.07%</span>|


</div></details>

**Pull request closed without merging**
