### PR TITLE
Fix mono arm assert with large return structs

### PR DESCRIPTION
**Pull request by bholmes**
When the return struct is large the store instruction offset is too large. When this happens, put the large offset in a register.

### CODE REVIEW

**Comment by bholmes** [comment]
Here is the test case that I used locally with `MONO_ARCH=arm`


```
using System;
using System.Runtime.InteropServices;

public class Program
{
    public static int Main(string[] args)
    {
        new Program().TestFunction();
        return 42;
    }

    private TestStruct CreateStruct(FourKStruct s, int i)
    {
        return new TestStruct { s = s, i = i };
    }

    private TestStruct TestFunction()
    {
        return CreateStruct(new FourKStruct(), 42);
    }

    private struct TestStruct
    {
        public FourKStruct s;
        public int i;
    }
}

[StructLayout(LayoutKind.Sequential, Size=4096)]
public partial struct FourKStruct
{
    internal byte bytes;
}
```

**Comment by bholmes** [comment]
Also looking for this to be backported to mono/mono as well.

**Review by vargaz — APPROVED** [review]

**Comment by marek-safar** [comment]
@vargaz  where to add the test case?

**Comment by vargaz** [comment]
src/tests/JIT/Regression.

**Pull request merged**
