### PR TITLE
Add Windows and Ubuntu perf runs on Ampere hw

### PR DESCRIPTION
**Pull request by DrewScoggins**

### CODE REVIEW

**Review by LoopedBard3 — APPROVED** [review]
LGTM given jobs that we want are uncommented and test runs were successful.

**Review by kunalspathak — APPROVED** [review]

**Comment by kunalspathak** [comment]
Thanks @DrewScoggins . Can we merge this?

**Comment by DrewScoggins** [comment]
Yeah, the test run I started on Thursday finished up with no issues.

**Comment by DrewScoggins** [comment]
But before I hit the merge button I need to remove the test comments

**Pull request merged**
