### PR TITLE
Update msquic revision in docs after certificate work.

### PR DESCRIPTION
**Pull request by ManickaP**
Follow up for: https://github.com/dotnet/runtime/pull/50613

I updated the readme.md to reflect that we don't use STUB_TLS anymore and set the revision to the current main.

No code change, only docs.

cc: @wfurt

### CODE REVIEW

**Comment by CarnaViire** [comment]
After updating to this new version of MsQuic, I see two test failures:

1) This one I've mentioned in my PR:
```
       System.Net.Quic.Tests.QuicConnectionTests_MsQuicProvider.AcceptStream_ConnectionAborted_ByClient_Throws [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.Net.Quic.QuicConnectionAbortedException)
        Actual:   typeof(System.Net.Quic.QuicOperationAbortedException): Operation aborted.
```

2) This one is new:
```
      System.Net.Quic.Tests.MsQuicTests.CloseAsync_ByServer_AcceptThrows [FAIL]
        System.Net.Quic.QuicException : Connection has been shutdown by transport. Error Code: USER_CANCELED
```

I propose to put them under ActiveIssue here, and I'll add the new one to the test issue.

@ManickaP Are they failing on Linux too, or not?

**Review by wfurt — APPROVED** [review]
LGTM.
if the failures are related to TLS I can take a look next week.
I suspect thay may be more related to other msquick changes.

**Comment by ManickaP** [comment]
- `CloseAsync_ByServer_AcceptThrows` fails for me too, although I'd swear it didn't yesterday. 
- `AcceptStream_ConnectionAborted_ByClient_Throws` passes.

I'll add `[ActiveIssue]` for `CloseAsync_ByServer_AcceptThrows`.

**Comment by ManickaP** [comment]
I updated the test failing for me and sneaked in a comment typo fix.

**Review by CarnaViire — APPROVED** [review]
Thanks!

**Pull request merged**
