### PR TITLE
Allow trimming away `ScopedRefAttribute`.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
Ref: dotnet/roslyn#62838.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
Looks good, but let's wait until the roslyn change is merged.

**Comment by AaronRobinsonMSFT** [comment]
If we are trimming away `ScopedRefAttribute`, what about [`UnscopedRefAttribute`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/UnscopedRefAttribute.cs)?

**Comment by teo-tsirpanis** [comment]
Handled in #72678.

**Comment by teo-tsirpanis** [comment]
@stephentoub, dotnet/roslyn#63009 has been merged. Can we merge this?

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
