### PR TITLE
Change PKCS12 password to assist with credscan

### PR DESCRIPTION
**Pull request by vcsjones**
/cc @aik-jahoda

### CODE REVIEW

**Comment by vcsjones** [comment]
Converting to draft because apparently the password was supposed to be PLACEHOLDER. Will change it again.

**Comment by bartonjs** [comment]
If we already have it suppressed, why are we changing it?

Does the new PKCS12 use the same encryption and MAC parameters, or are we possibly losing some edge coverage on DSA?

**Comment by vcsjones** [comment]
> If we already have it suppressed, why are we changing it?

I got an email I should change it.

> Does the new PKCS12 use the same encryption and MAC parameters

Yes. Same PBE parameters, same key (DSA). Just changing the PBE password.

**Comment by aik-jahoda** [comment]
The problem is not in the certificate itself, but with 
```
return new X509Certificate2(SampleDsaPfx, "velleity");
```

It complains about plaintext password. We decided to prefer PLACEHOLDER as a safe well known "password" which at first sight confirm it is test only password.

**Review by aik-jahoda — APPROVED** [review]
LGTM

**Review by bartonjs — APPROVED** [review]

**Pull request merged**
