### PR TITLE
Delete temporary instrumentation for #76280

### LINKED ISSUE #76280: Test failure JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_r\\Vector256_r.cmd
Run: [runtime-coreclr jitstress 20220926.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=31276&view=ms.vss-test-web.build-test-results-tab&runId=628704&resultId=101181&paneView=debug)

Failed test:
```
coreclr windows x64 Checked zapdisable @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_r\\Vector256_r.cmd
```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\B3BB09D9\w\A3F60922\uploads\Reports\JIT.HardwareIntrinsics\General\Vector256\Vector256_r\Vector256_r.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B3BB09D9\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Vector256_r.dll
Beginning test case Abs.Byte at 9/27/2022 7:13:05 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 9/27/2022 7:13:06 AM
Beginning test case Abs.Double at 9/27/2022 7:13:06 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 9/27/2022 7:13:07 AM
Beginning test case Abs.Int16 at 9/27/2022 7:13:07 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 9/27/2022 7:13:07 AM
Beginning test case Abs.Int32 at 9/27/2022 7:13:07 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 9/27/2022 7:13:07 AM
Beginning test case Abs.Int64 at 9/27/2022 7:13:07 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 9/27/2022 7:13:07 AM
Beginning test case Abs.SByte at 9/27/2022 7:13:07 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 9/27/2022 7:13:07 AM
Beginning test case Abs.Single at 9/27/2022 7:13:07 AM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginnin


Stack trace
   at JIT_HardwareIntrinsics._General_Vector256_Vector256_r_Vector256_r_._General_Vector256_Vector256_r_Vector256_r_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

```json
{ 
    "ErrorMessage":"JIT.HardwareIntrinsics\\General\\Vector256\\Vector256_",
    "BuildRetry": false
} 
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[78807](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78807)|dotnet/runtime|[JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_ro\\Vector256_ro.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78807&view=ms.vss-test-web.build-test-results-tab&runId=1645420&resultId=101700)||
|[78797](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78797)|dotnet/runtime|[JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_ro\\Vector256_ro.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78797&view=ms.vss-test-web.build-test-results-tab&runId=1644860&resultId=101662)|dotnet/runtime#77737|
|[77376](https://dev.azure.com/dnceng-public/public/_build/results?buildId=77376)|dotnet/runtime|[JIT.HardwareIntrinsics.General.Vector256.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=77376&view=ms.vss-test-web.build-test-results-tab&runId=1608888&resultId=110823)||
|[76912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=76912)|dotnet/runtime|[JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_ro\\Vector256_ro.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=76912&view=ms.vss-test-web.build-test-results-tab&runId=1599104&resultId=100136)|dotnet/runtime#77728|
|[76381](https://dev.azure.com/dnceng-public/public/_build/results?buildId=76381)|dotnet/runtime|[JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_ro\\Vector256_ro.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=76381&view=ms.vss-test-web.build-test-results-tab&runId=1583524&resultId=101650)|dotnet/runtime#77990|
|[76377](https://dev.azure.com/dnceng-public/public/_build/results?buildId=76377)|dotnet/runtime|[JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_ro\\Vector256_ro.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=76377&view=ms.vss-test-web.build-test-results-tab&runId=1582476&resultId=102363)|dotnet/runtime#77353|
|[76043](https://dev.azure.com/dnceng-public/public/_build/results?buildId=76043)|dotnet/runtime|[JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_ro\\Vector256_ro.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=76043&view=ms.vss-test-web.build-test-results-tab&runId=1574484&resultId=101958)|dotnet/runtime#76793|
|[75886](https://dev.azure.com/dnceng-public/public/_build/results?buildId=75886)|dotnet/runtime|[JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_ro\\Vector256_ro.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=75886&view=ms.vss-test-web.build-test-results-tab&runId=1569498&resultId=100950)||
|[70948](https://dev.azure.com/dnceng-public/public/_build/results?buildId=70948)|dotnet/runtime|[JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_ro\\Vector256_ro.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=70948&view=ms.vss-test-web.build-test-results-tab&runId=1460014&resultId=101287)|dotnet/runtime#77798|
|[68929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=68929)|dotnet/runtime|[JIT.HardwareIntrinsics.General.Vector256.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=68929&view=ms.vss-test-web.build-test-results-tab&runId=1403228&resultId=110825)||
|[67658](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67658)|dotnet/runtime|[JIT.HardwareIntrinsics.General.Vector256.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67658&view=ms.vss-test-web.build-test-results-tab&runId=1377220&resultId=110824)||
|[66875](https://dev.azure.com/dnceng-public/public/_build/results?buildId=66875)|dotnet/runtime|[JIT.HardwareIntrinsics.General.Vector256.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=66875&view=ms.vss-test-web.build-test-results-tab&runId=1362246&resultId=110824)||
|[66220](https://dev.azure.com/dnceng-public/public/_build/results?buildId=66220)|dotnet/runtime|[JIT.HardwareIntrinsics.General.Vector256.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=66220&view=ms.vss-test-web.build-test-results-tab&runId=1351562&resultId=110824)|dotnet/runtime#73472|
|[64828](https://dev.azure.com/dnceng-public/public/_build/results?buildId=64828)|dotnet/runtime|[JIT.HardwareIntrinsics.General.Vector256.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=64828&view=ms.vss-test-web.build-test-results-tab&runId=1319920&resultId=110824)||
|[62054](https://dev.azure.com/dnceng-public/public/_build/results?buildId=62054)|dotnet/runtime|[JIT.HardwareIntrinsics.General.Vector256.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=62054&view=ms.vss-test-web.build-test-results-tab&runId=1271088&resultId=110823)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|15|

### PR DESCRIPTION
**Pull request by jkotas**
Fixes #76280

### CODE REVIEW

**Comment by jkotas** [comment]
The issue does not repro anymore.

**Review by tannergooding — APPROVED** [review]
LGTM.

I'd guess this was fixed by the change in backing CPU and so this is likely the issue @EgorBo had found and referenced.

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
@tannergooding @jkotas Note that this test failed in our superpmi collection pipeline this past weekend, with this assert:

https://github.com/dotnet/runtime/issues/78576

This run happens in the "internal" AzDO instance which hasn't switched to the new machines.

**Comment by jkotas** [comment]
> This run happens in the "internal" AzDO instance which hasn't switched to the new machines.

Do we plan to switch?

**Comment by BruceForstall** [comment]
> Do we plan to switch?

There are no current plans, AFAIK. When I talked to the internal Engineering Services team about switching, I focused on PR dotnet/runtime testing. I believe there are very few "internal" pipelines that actually run tests, but superpmi-collect does.

Also, fyi, the new machines are being used for Windows/x64, not Linux/x64.

**Pull request merged**
