### PR TITLE
[release/9.0][PERF] Backport python pipeline changes for performance tests

### PR DESCRIPTION
**Pull request by caaavik-msft**
This PR backports three changes to release/9.0 so it can make use of the work that moved a lot of the logic out of our yaml files and into python for performance testing:
- #101143 
- #108038
- #108303

Part of this work moved a lot of the pipeline logic out of the runtime repo and into the performance repo, so this change will help prevent us from having to make future changes to the release/9.0 branch.

### CODE REVIEW

**Review by LoopedBard3 — APPROVED** [review]
Looks good, we will want to watch after this goes in to make sure there are not any minor breaks.

**Comment by LoopedBard3** [comment]
Can we get this merged @carlossanlop, or is there someone we else we should ask? It is a performance infra only change and I am not seeing a release/9.0-staging branch.

**Comment by DrewScoggins** [comment]
@jeffschwMSFT Could you help get this merged?

**Review by jeffschwMSFT — APPROVED** [review]
approved. we can treat this as tell mode

cc @carlossanlop

**Comment by jeffschwMSFT** [comment]
@DrewScoggins please take a look at the PR failures - if unrelated, I can help merge

**Comment by DrewScoggins** [comment]
One is a timeout in OleDB tests, and the other is a failure in the emcc for a WASM AOT test. These changes do not impact any files in the src folder, and also do not touch the configs for any of the unit tests. 

So in my opinion I do not believe that these failing tests are related to our change.

**Comment by DrewScoggins** [comment]
Thanks for your help Jeff!

**Pull request merged**
