### PR TITLE
Fix profiling objectsallocatedbyclass

### PR DESCRIPTION
**Pull request by ogxd**
See https://github.com/dotnet/runtime/issues/63806

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=63814) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=63814) before we can accept your contribution.<br/><br/>:x: ogxd [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=63814)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=63814) it.</sub>

**Comment by ogxd** [comment]
Linked issue: https://github.com/dotnet/runtime/issues/63806

**Comment by ogxd** [comment]
First commit is a unit test without the fix to demonstrate the issue in the CI:
```
profiler/gc/gc/gc.sh
Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
   at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
   at Profiler.Tests.GCTests.Main(String[] args)
/root/helix/work/workitem/e/profiler/gc/gc/gc.sh: line 431:    81 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/profiler.gc/gc/gc.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false gc.dll ''
Profiler path: /root/helix/work/workitem/e/profiler/gc/gc/libProfiler.so
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Did 0 iterations Allocated=65548
Did 1000 iterations Allocated=940276
Did 2000 iterations Allocated=1778904
Did 3000 iterations Allocated=2617440
Did 4000 iterations Allocated=3456220
Did 5000 iterations Allocated=4294828
Did 6000 iterations Allocated=5133456
Did 7000 iterations Allocated=5972056
Did 8000 iterations Allocated=6810168
Did 9000 iterations Allocated=7648788
5045 POH allocs and 4955 normal allocs.
Profiler.dll!Profiler::Shutdown
**GCProfiler::Shutdown: FAIL: Expected ObjectsAllocatedByClass to be called**

Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
Gathering state for process 81 corerun
Crashing thread 00000051 signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.81.dmp
Written 108978176 bytes (26606 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/e/profiler/gc/gc/gc.sh
Expected: True
Actual:   False
```

**Comment by ogxd** [comment]
Commited the actual fix and now the CI passed ✅ @davmason

**Review by davmason — APPROVED** [review]
Thanks for working on this! LGTM

**Comment by davmason** [comment]
I think the one failure is unrelated, I reset the leg and hopefully it passes on reset

**Comment by davmason** [comment]
OK, that leg passed but now it's complaining that you haven't agreed to the contributor's license. Once you agree to that we can merge it. Thanks again!

**Comment by ogxd** [comment]
Ok I've just signed it 🙂

**Pull request merged**
