### PR TITLE
Fix XUnitLogChecker detection for local test runs

### LINKED ISSUE #95762: Local running of libraries tests is broken
The recent PR #94868 has broken local running of libraries tests. After each test suite is completed, the following is printed to console and the test suite is reported as failed:
```
XUnitLogChecker.dll does not exist in the expected location: \XUnitLogChecker.dll
```

Looking at the [eng/testing/RunnerTemplate.cmd](https://github.com/dotnet/runtime/blob/283ee4e354c8897f1ad2bf351e45fbfec41ca3df/eng/testing/RunnerTemplate.cmd#L117), I can see that it builds the XUnitLogChecker.dll path like this:
`set XUNITLOGCHECKER_DLL=%HELIX_CORRELATION_PAYLOAD%\XUnitLogChecker.dll`
My guess is the problem is that the HELIX_CORRELATION_PAYLOAD is not set for local testing.

### PR DESCRIPTION
**Pull request by carlossanlop**
Fixes https://github.com/dotnet/runtime/issues/95762

When attempting to run tests locally, XUnitLogChecker would cause a test failure because HELIX_CORRELATION_PAYLOAD is not defined in the local machine. If we skip the execution of XUnitLogChecker completely when HELIX_CORRELATION_PAYLOAD is not defined, we stop seeing the tests fail locally.

NOTE: I am adding a temporary crash to ensure XUnitLogChecker still works in the CI. Will remove before merging.

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]
Is this the quick fix or the real fix? Asking as I think there were some more comments about architecture in the issue.

**Comment by carlossanlop** [comment]
> _Is this the quick fix or the real fix? Asking as I think there were some more comments about architecture in the issue._

@ViktorHofer This should be the real fix. We don't need XUnitLogChecker to run in local tests. I answered the architecture question [in the main issue](https://github.com/dotnet/runtime/issues/95762#issuecomment-1881724844), no changes needed for that.

**Comment by carlossanlop** [comment]
Confirmed: XUnitLogChecker still works in the CI.

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-96638-merge-7d7ebced89034fba9a/System.IO.Compression.Brotli.Tests/1/console.998695cc.log?helixlogtype=result

**Comment by carlossanlop** [comment]
> The RunTemplate.sh file doesn't need to be updated?

Good point. Let me check in my Ubuntu machine.

**Review by hoyosjs — APPROVED** [review]

**Review by jkoritzinsky — APPROVED** [review]

**Review by ivdiazsa — APPROVED** [review]

**Comment by carlossanlop** [comment]
I'll merge this to unblock folks that cannot run tests locally. There is still some discussion to attend in the main issue related to the OS. I'll address that separately.

**Pull request merged**
