### PR TITLE
[release/6.0] Update THIRD-PARTY-NOTICES.TXT

### PR DESCRIPTION
**Pull request by NikolaMilosavljevic**
Update third-party-notices file for .NET 6.

Infra used to generate this file is in another PR: https://github.com/dotnet/runtime/pull/60091

Here's the output of TPN regeneration process, specifying which repo contributes each new notice:

```  New section to import: 'License for fastmod (https://github.com/lemire/fastmod) and ibm-fpgen (https://github.com/nigeltao/parse-number-fxx-test-data)' of https://raw.githubusercontent.com/dotnet/runtime/master/THIRD-PARTY-NOTICES.TXT line 682
  New section to import: 'License notice for Angular v8.0  --------------------------------------------  The MIT License (MIT)' of https://raw.githubusercontent.com/dotnet/aspnetcore/master/THIRD-PARTY-NOTICES.txt line 167
  New section to import: 'License notice for JavaScript queues' of https://raw.githubusercontent.com/dotnet/runtime/master/THIRD-PARTY-NOTICES.TXT line 974
  New section to import: 'License notice for MSBuild Locator' of https://raw.githubusercontent.com/dotnet/roslyn-analyzers/master/THIRD-PARTY-NOTICES.txt line 11
  New section to import: 'License notice for Newtonsoft.Json' of https://raw.githubusercontent.com/dotnet/aspnetcore/master/THIRD-PARTY-NOTICES.txt line 322
  New section to import: 'License notice for NuGet.Client' of https://raw.githubusercontent.com/dotnet/templating/master/THIRD-PARTY-NOTICES line 10
  New section to import: 'License notice for Roslyn Clr Heap Allocation Analyzer' of https://raw.githubusercontent.com/dotnet/roslyn-analyzers/master/THIRD-PARTY-NOTICES.txt line 28
  New section to import: 'License notice for StyleCop Analyzers' of https://raw.githubusercontent.com/dotnet/roslyn-analyzers/master/THIRD-PARTY-NOTICES.txt line 42
  New section to import: 'The MIT License (MIT)' of https://raw.githubusercontent.com/dotnet/aspnetcore/master/THIRD-PARTY-NOTICES.txt line 194
  Importing 9 sections...

### CODE REVIEW

**Review by joeloff — APPROVED** [review]

**Review by jmarolf — APPROVED** [review]

**Review by hoyosjs — APPROVED** [review]
LGTM other than the comment from Sam, where it's not clear what the last license is for.

**Comment by Anipik** [comment]
@NikolaMilosavljevic can you tag the reviewers again ? (which are required for the final merge)

**Review by ViktorHofer — APPROVED** [review]

**Review by dougbu — COMMENTED** [review]
I don't know exactly how or why some of these items are used and probably shouldn't be the approver. @mkArtakMSFT who else needs to look at this❔

**Comment by mkArtakMSFT** [comment]
> > Side question: Why do you need ASP.NET sign-off on a Runtime PR❔ Is this TPN.txt file going to be used for every published asset from any repo❔
> 
> Yes, this is a merged TPN, that is installed under dotnet folder - it covers everything we install there, including ASP.NET.

Given that's the  case, what about all the other dependencies that ASP.NET Core has? Shouldn't these also be listed here?

**Comment by NikolaMilosavljevic** [comment]
> > > Side question: Why do you need ASP.NET sign-off on a Runtime PR❔ Is this TPN.txt file going to be used for every published asset from any repo❔
> > 
> > 
> > Yes, this is a merged TPN, that is installed under dotnet folder - it covers everything we install there, including ASP.NET.
> 
> @NikolaMilosavljevic, given that's the case, what about all the other dependencies that ASP.NET Core has? Shouldn't these also be listed here?

All ASP.NET dependencies are here, in the shared file. We avoid duplication and only include a single instance of the same dependency. It's likely that many of those dependencies are also present in other repos and included in a different section of this unified file.

Is there a specific dependency of ASP.NET that should be included but it is not present?

**Review by Pilchie — COMMENTED** [review]
This looks fine for aspnetcore. @dougbu is OOF today, so don't feel you have to wait for his sign-off.

**Pull request merged**
