### PR TITLE
Disable more red tests for crossgen lanes

### PR DESCRIPTION
**Pull request by kg**

### CODE REVIEW

**Comment by carlossanlop** [comment]
Note: First Responders has reported that the CI is not actively getting triggered in PRs since early morning Monday 28th and the issue is being investigated. Please monitor the Teams chat group for an update so you can close + reopen your PR when the issue is fixed.

**Comment by kg** [comment]
Filed https://github.com/dotnet/runtime/issues/109395 for the remaining test failure, which I think will be fixed once another PR lands.

**Review by steveisok — APPROVED** [review]

**Pull request merged**
