### PR TITLE
[Arm64] Change uint to Vector64<uint> in Sha1 intrinsics

### PR DESCRIPTION
**Pull request by echesakov**
I believe `hash_e` parameter in Sha1 intrinsics should be `Vector64<uint>` and not `uint` since we want the value to be enregistered in a SIMD&FP register. Also `Sha1.FixedRotate1 should return `Vector64<uint>` and not `uint`.

I raised this question in https://github.com/dotnet/runtime/issues/24784#issuecomment-611101019 but while waiting for reply I started writing missing tests for Sha1 and Sha256 intrinsics and then I discovered that originally we had a different logic in JIT backend that, for example, for `Sha1.FixedRotate` would generate something like

```asm
fmov s0, w0
sha1h s0, s0
fmov w0, s0
```
basically moving value back and forth between a SIMD&PF register and a general-purpose register.

I don't think we want that. We want the value to be placed in a SIMD&FP register outside of the intrinsic.

It is worth noting that this logic got lost in https://github.com/dotnet/runtime/commit/bc3338dbefb54b07773fb1bf747621fde173d452 (dotnet/coreclr#25508) when Tanner ported part of the manually written codegen into the table-driven codegen we have now but the LSRA logic allocating an internal register that I removed in #34668 was still there. I was curious in https://github.com/dotnet/runtime/pull/34668#issue-400579467 why we needed to allocate an internal register for these intrinsics - now the answer is clear - because we needed a SIMD register to call `sha1h` instruction as in an example above.

This also renames IF_DR_2J instruction format to IF_DV_2U since sha1h operates on SIMD&FP registers we use IF_DV prefix for such instructions per our convention.

This adds tests for Sha1 and Sha256.

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@CarolEidt @tannergooding @TamarChristinaArm PTAL

**Review by tannergooding — APPROVED** [review]
LGTM. Thanks for catching this!

**Comment by tannergooding** [comment]
> basically moving value back and forth between a SIMD&PF register and a general-purpose register.

Do we know what was allowing this to work?

**Review by CarolEidt — APPROVED** [review]
LGTM - thanks for following up on this!

**Comment by echesakovMSFT** [comment]
> basically moving value back and forth between a SIMD&PF register and a general-purpose register.
> 
> Do we know what was allowing this to work?

It doesn't work currently since we dropped support for this in bc3338dbefb54b07773fb1bf747621fde173d452 

But if you look at `CodeGen::genHWIntrinsicShaRotateOp` in the same bc3338dbefb54b07773fb1bf747621fde173d452 you will find the custom logic for `FixedRotate`

```c++
GetEmitter()->emitIns_R_R(INS_fmov, EA_4BYTE, tmpReg, elementReg); 
GetEmitter()->emitIns_R_R(ins, EA_4BYTE, tmpReg, tmpReg); 
GetEmitter()->emitIns_R_R(INS_fmov, attr, targetReg, tmpReg);
```
where tmpReg was allocated by buildInternalFloatRegisterDefForNode in lsraarm64.cpp and elementReg is a general purpose register that was allocated for hash_e argument.

**Pull request merged**
