### PR TITLE
Fix Configuration Binder Test with WASM and Trimming

### LINKED ISSUE #72465: normal-microsoft.extensions.configuration.binder.tests work item
Runfo Tracking Issue: [normal-microsoft.extensions.configuration.binder.tests work item](https://runfo.azurewebsites.net/tracking/issue/384)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1890969](https://dev.azure.com/dnceng/public/_build/results?buildId=1890969)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 71385](https://github.com/dotnet/runtime/pull/71385)|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71385-merge-98218afe78ec43528a/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.833bea68.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71385-merge-98218afe78ec43528a/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71385-merge-98218afe78ec43528a/normal-Microsoft.Extensions.Configuration.Binder.Tests/75517f90-92c3-4635-a75e-a671d53977e5.log?%3F%253Fhelixlogtype%253Dresult)|
|[1890969](https://dev.azure.com/dnceng/public/_build/results?buildId=1890969)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 71385](https://github.com/dotnet/runtime/pull/71385)|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71385-merge-6a56d78f9dcd4ed89f/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.4fd58dd2.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71385-merge-6a56d78f9dcd4ed89f/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71385-merge-6a56d78f9dcd4ed89f/normal-Microsoft.Extensions.Configuration.Binder.Tests/f6660c4d-8f3c-48cc-b9b8-4907fededf30.log?%3F%253Fhelixlogtype%253Dresult)|
|[1890767](https://dev.azure.com/dnceng/public/_build/results?buildId=1890767)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 72467](https://github.com/dotnet/runtime/pull/72467)|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72467-merge-6489262a3731401d9b/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.c18f4408.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72467-merge-6489262a3731401d9b/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72467-merge-6489262a3731401d9b/normal-Microsoft.Extensions.Configuration.Binder.Tests/1cb05fb4-d24b-4a03-8d08-f2f1311deafd.log?%3F%253Fhelixlogtype%253Dresult)|
|[1890767](https://dev.azure.com/dnceng/public/_build/results?buildId=1890767)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 72467](https://github.com/dotnet/runtime/pull/72467)|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72467-merge-689ccf6501234e08a4/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.f9335917.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72467-merge-689ccf6501234e08a4/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72467-merge-689ccf6501234e08a4/normal-Microsoft.Extensions.Configuration.Binder.Tests/840338fb-f32e-419b-85fe-72a51fc1cc26.log?%3F%253Fhelixlogtype%253Dresult)|
|[1890405](https://dev.azure.com/dnceng/public/_build/results?buildId=1890405)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 72445](https://github.com/dotnet/runtime/pull/72445)|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72445-merge-5bb10e9454984b8dba/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.b056b9c8.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72445-merge-5bb10e9454984b8dba/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72445-merge-5bb10e9454984b8dba/normal-Microsoft.Extensions.Configuration.Binder.Tests/779c4c62-aa52-479d-87bd-146ed780dd62.log?%3F%253Fhelixlogtype%253Dresult)|
|[1890405](https://dev.azure.com/dnceng/public/_build/results?buildId=1890405)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 72445](https://github.com/dotnet/runtime/pull/72445)|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72445-merge-0e663badd21243f9ba/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.c3330188.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72445-merge-0e663badd21243f9ba/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72445-merge-0e663badd21243f9ba/normal-Microsoft.Extensions.Configuration.Binder.Tests/34492b16-4543-4b51-bb6e-a78d0e649844.log?%3F%253Fhelixlogtype%253Dresult)|
|[1889995](https://dev.azure.com/dnceng/public/_build/results?buildId=1889995)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 71385](https://github.com/dotnet/runtime/pull/71385)|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71385-merge-0fedc2e5e5d347e99d/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.ee7288fb.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71385-merge-0fedc2e5e5d347e99d/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71385-merge-0fedc2e5e5d347e99d/normal-Microsoft.Extensions.Configuration.Binder.Tests/74318b36-6787-453a-97b3-10f1e11923c2.log?%3F%253Fhelixlogtype%253Dresult)|
|[1889995](https://dev.azure.com/dnceng/public/_build/results?buildId=1889995)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 71385](https://github.com/dotnet/runtime/pull/71385)|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71385-merge-fae975d2b40f462183/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.99e4dfcd.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71385-merge-fae975d2b40f462183/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71385-merge-fae975d2b40f462183/normal-Microsoft.Extensions.Configuration.Binder.Tests/bc894310-1312-4f5c-acbc-5f5c5062f9c1.log?%3F%253Fhelixlogtype%253Dresult)|
|[1889994](https://dev.azure.com/dnceng/public/_build/results?buildId=1889994)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 72445](https://github.com/dotnet/runtime/pull/72445)|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72445-merge-04d3fe5ffb3245c1b7/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.96f37ed9.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72445-merge-04d3fe5ffb3245c1b7/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72445-merge-04d3fe5ffb3245c1b7/normal-Microsoft.Extensions.Configuration.Binder.Tests/9c10a36b-1d97-425d-b609-7672bce4293b.log?%3F%253Fhelixlogtype%253Dresult)|
|[1889994](https://dev.azure.com/dnceng/public/_build/results?buildId=1889994)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 72445](https://github.com/dotnet/runtime/pull/72445)|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72445-merge-baed2d672c6d41658f/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.d824cafe.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72445-merge-baed2d672c6d41658f/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72445-merge-baed2d672c6d41658f/normal-Microsoft.Extensions.Configuration.Binder.Tests/97aa0e07-32d7-4201-8281-d0d1df9bce1f.log?%3F%253Fhelixlogtype%253Dresult)|
|[1889812](https://dev.azure.com/dnceng/public/_build/results?buildId=1889812)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|Rolling|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5c5e2aec322448dd9e/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.f87b29c5.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5c5e2aec322448dd9e/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-5c5e2aec322448dd9e/normal-Microsoft.Extensions.Configuration.Binder.Tests/e7730523-b134-4b37-bbde-ee75999ab2bb.log?%3F%253Fhelixlogtype%253Dresult)|
|[1889812](https://dev.azure.com/dnceng/public/_build/results?buildId=1889812)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|Rolling|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4ae0094c5bea466f8c/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.be6fe35a.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4ae0094c5bea466f8c/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-4ae0094c5bea466f8c/normal-Microsoft.Extensions.Configuration.Binder.Tests/4d4c10ed-05d6-4ff7-b53b-06e3c7223cc7.log?%3F%253Fhelixlogtype%253Dresult)|
|[1889446](https://dev.azure.com/dnceng/public/_build/results?buildId=1889446)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 72272](https://github.com/dotnet/runtime/pull/72272)|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72272-merge-c21bd24f2b41484193/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.bfc7aeb3.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72272-merge-c21bd24f2b41484193/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72272-merge-c21bd24f2b41484193/normal-Microsoft.Extensions.Configuration.Binder.Tests/bcc260ac-ac49-4a2e-8fbf-404fafd2368d.log?%3F%253Fhelixlogtype%253Dresult)|
|[1889446](https://dev.azure.com/dnceng/public/_build/results?buildId=1889446)|[runtime-extra-platforms](https://dnceng.visualstudio.com/public/_build?definitionId=1080)|[PR 72272](https://github.com/dotnet/runtime/pull/72272)|net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72272-merge-d309c7825bad4ec3b3/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/console.9643a5e9.log?%3F%253Fhelixlogtype%253Dresult)||[test results](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72272-merge-d309c7825bad4ec3b3/normal-Microsoft.Extensions.Configuration.Binder.Tests/1/xharness-output/testResults.xml?%3F%253Fhelixlogtype%253Dresult)|[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72272-merge-d309c7825bad4ec3b3/normal-Microsoft.Extensions.Configuration.Binder.Tests/1b7fc237-7742-4ae5-a7b1-b86a8953ff8f.log?%3F%253Fhelixlogtype%253Dresult)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|7|7|7|

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes https://github.com/dotnet/runtime/issues/72465

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
LGTM

**Comment by SteveDunn** [comment]
Just catching up on things; was the original test failure due to a constructor on SortedSet being trimmed for WASM? (I'm not too sure of the terminology I just used there!)

**Comment by eerhardt** [comment]
Correct. There are WebAssembly (WASM) test legs that fully trim the unit tests and try to run them. Since no code in the unit test was using the parameterless constructor on SortedSet, it was being trimmed causing the test to fail.

**Comment by SteveDunn** [comment]
That's amazing! Clever stuff indeed.

**Pull request merged**
