### PR TITLE
GCCoverageInfo support 32-bit Tiered compilation

### LINKED ISSUE #36366: Assert in DoubleAlign scenario with GCStress and TieredCompilation
After the fix in https://github.com/dotnet/runtime/pull/36357 is merged, a new assert is firing. This assert appears to be a problem with CodeGen on x86 when `COMPlus_GCStress=0xC`. If `COMPlus_TieredCompilation=0` is set, the assert goes away.

Assert:
```
CORECLR! SKIP_PUSH_REG + 0x76 (0x5dd69de6)
CORECLR! UnwindEbpDoubleAlignFrameProlog + 0x1BD (0x5dd6a44d)
CORECLR! UnwindEbpDoubleAlignFrame + 0xE9 (0x5dd69ef9)
CORECLR! UnwindStackFrame + 0x394 (0x5dd6acf4)
CORECLR! DoGcStress + 0x2A4 (0x5dcb5386)
CORECLR! OnGcCoverageInterrupt + 0x12F (0x5dcb593a)
CORECLR! IsGcMarker + 0x93 (0x5d9fbab3)
CORECLR! CLRVectoredExceptionHandlerShim + 0xC5 (0x5d9ef1d5)
NTDLL! LdrSetDllManifestProber + 0xF6 (0x77e1bc46)
NTDLL! RtlUnwind + 0x1CB (0x77e1812b)
    File: D:\runtime\src\coreclr\src\vm\eetwain.cpp Line: 3021
    Image: D:\runtime\artifacts\tests\coreclr\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe
```

The below function failing when executed in the following loop:

https://github.com/dotnet/runtime/blob/ba453bd90ccce9848ce95651f0e13413660c09ee/src/coreclr/tests/src/Interop/COM/ComWrappers/API/Program.cs#L316-L326

Failing stack:
```
0:000> kb
 # ChildEBP RetAddr  Args to Child              
00 00afc97c 79b89de6 7a0793e8 00000bcd 7a07a540 coreclr!DbgAssertDialog+0x20f [D:\runtime\src\coreclr\src\utilcode\debug.cpp @ 698] 
01 00afc998 79b8a44d 0a834144 00000003 00afce44 coreclr!SKIP_PUSH_REG+0x76 [D:\runtime\src\coreclr\src\vm\eetwain.cpp @ 3022] 
02 00afc9c4 79b89ef9 00afcad4 00afce44 0a834144 coreclr!UnwindEbpDoubleAlignFrameProlog+0x1bd [D:\runtime\src\coreclr\src\vm\eetwain.cpp @ 3842] 
03 00afc9ec 79b8acf4 00afcad4 00afcb08 00afce44 coreclr!UnwindEbpDoubleAlignFrame+0xe9 [D:\runtime\src\coreclr\src\vm\eetwain.cpp @ 3984] 
04 00afca94 79ad5386 00afcad4 00afcb08 00000008 coreclr!UnwindStackFrame+0x394 [D:\runtime\src\coreclr\src\vm\eetwain.cpp @ 4101] 
05 00afd050 79ad593a 00afd2a4 00000001 02eb0cc0 coreclr!DoGcStress+0x2a4 [D:\runtime\src\coreclr\src\vm\gccover.cpp @ 1611] 
06 00afd0a0 7981bab3 00afd2a4 9555cb78 00afd170 coreclr!OnGcCoverageInterrupt+0x12f [D:\runtime\src\coreclr\src\vm\gccover.cpp @ 1431] 
07 00afd0ec 7980f1d5 00afd2a4 00afd254 9555cac0 coreclr!IsGcMarker+0x93 [D:\runtime\src\coreclr\src\vm\excep.cpp @ 6565] 
08 00afd154 77e1bc46 00afd170 00afd2a4 00afd254 coreclr!CLRVectoredExceptionHandlerShim+0xc5 [D:\runtime\src\coreclr\src\vm\excep.cpp @ 7949] 
09 00afd1a4 77e1812b 00000000 05261e68 02e76600 ntdll!RtlpCallVectoredHandlers+0xd5 [minkernel\ntdll\vectxcpt.c @ 206] 
0a (Inline) -------- -------- -------- -------- ntdll!RtlCallVectoredExceptionHandlers+0xa [minkernel\ntdll\vectxcpt.c @ 339] 
0b 00afd23c 77e242c6 00afd254 00afd2a4 00afd254 ntdll!RtlDispatchException+0x6f [minkernel\ntos\rtl\i386\exdsptch.c @ 881] 
0c 00afd704 08d0fcdb 12345678 7a00743c ffffffff ntdll!KiUserExceptionDispatcher+0x26 [minkernel\ntos\rtl\i386\userdisp.asm @ 604] 
0d 00afd704 08d08f4c 00000000 00000000 00000000 ComWrappersTests!ComWrappersTests.Common.ITrackerObjectWrapper.AddObjectRef(IntPtr)+0x65b
0e 00afd77c 08d05d0c 00000000 00000000 00000000 ComWrappersTests!ComWrappersTests.Program.ValidateRuntimeTrackerScenario()+0x12c
0f 00afd7a8 798821a1 02e76858 00afdbd4 79a7b53d ComWrappersTests!ComWrappersTests.Program.Main(System.String[])+0x1c
10 00afd7b4 79a7b53d 00afde7c 02e76600 00afde7c coreclr!CallDescrWorkerInternal+0x34 [D:\runtime\src\coreclr\src\vm\i386\asmhelpers.asm @ 607] 
11 00afdbd4 79a7b695 00afde7c abcdefab abcdefab coreclr!CallDescrWorker+0xd7 [D:\runtime\src\coreclr\src\vm\callhelpers.cpp @ 129] 
12 00afdc50 79a7bd1a 00afde7c 00000000 79fdd288 coreclr!CallDescrWorkerWithHandler+0xf6 [D:\runtime\src\coreclr\src\vm\callhelpers.cpp @ 72] 
13 00afdeac 79a7575e 00afdfac 00afdfbc 00000008 coreclr!MethodDescCallSite::CallTargetWorker+0x64f [D:\runtime\src\coreclr\src\vm\callhelpers.cpp @ 554] 
14 (Inline) -------- -------- -------- -------- coreclr!MethodDescCallSite::Call_RetArgSlot+0x99 [D:\runtime\src\coreclr\src\vm\callhelpers.h @ 459] 
15 00afdfd4 79a75348 00afe080 9555fb84 00afe1e0 coreclr!RunMainInternal+0x1b0 [D:\runtime\src\coreclr\src\vm\assembly.cpp @ 1491] 
16 00afe010 79a753f6 00afe080 9555fbf0 00afe1e0 coreclr!``RunMain'::`29'::__Body::Run'::`5'::__Body::Run+0x40 [D:\runtime\src\coreclr\src\vm\assembly.cpp @ 1561] 
17 00afe064 79a7552c 00afe080 9555fb50 0893bb34 coreclr!`RunMain'::`29'::__Body::Run+0x5d [D:\runtime\src\coreclr\src\vm\assembly.cpp @ 1561] 
18 00afe0c4 79a72484 0893bb34 00000001 00afe1e0 coreclr!RunMain+0xd1 [D:\runtime\src\coreclr\src\vm\assembly.cpp @ 1561] 
19 00afe420 798080d9 00afe570 00000001 9555fe1c coreclr!Assembly::ExecuteMainMethod+0x1ba [D:\runtime\src\coreclr\src\vm\assembly.cpp @ 1671] 
1a 00afe588 797cd8f2 02e11a70 00000001 02e92cf8 coreclr!CorHost2::ExecuteAssembly+0x4a9 [D:\runtime\src\coreclr\src\vm\corhost.cpp @ 390] 
1b 00afe5e8 00b2a69a 02e11a70 00000001 00000000 coreclr!coreclr_execute_assembly+0x92 [D:\runtime\src\coreclr\src\dlls\mscoree\unixinterface.cpp @ 397] 
1c 00afe60c 00b2a5e6 02e11a70 00000001 00000000 CoreRun!HostEnvironment::ExecuteAssembly+0x2a [D:\runtime\src\coreclr\src\hosts\corerun\corerun.cpp @ 354] 
1d 00afe9d8 00b2ed7e 00affadc 00aff964 00afea30 CoreRun!ExecuteAssembly+0x35a [D:\runtime\src\coreclr\src\hosts\corerun\corerun.cpp @ 644] 
1e 00affa94 00b2f966 00000001 02e0612c 00affadc CoreRun!TryRun+0x469 [D:\runtime\src\coreclr\src\hosts\corerun\corerun.cpp @ 792] 
1f 00affae4 00b4d4d3 00000002 02e06128 02e0c620 CoreRun!wmain+0x98 [D:\runtime\src\coreclr\src\hosts\corerun\corerun.cpp @ 873] 
20 00affb04 00b4d3a7 7e24ea5c 00b4d530 00b4d530 CoreRun!invoke_main+0x33 [d:\agent\_work\7\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 90] 
21 00affb60 00b4d24d 00affb70 00b4d538 00affb80 CoreRun!__scrt_common_main_seh+0x157 [d:\agent\_work\7\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
22 00affb68 00b4d538 00affb80 75906359 02c88000 CoreRun!__scrt_common_main+0xd [d:\agent\_work\7\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 331] 
23 00affb70 75906359 02c88000 75906340 00affbdc CoreRun!wmainCRTStartup+0x8 [d:\agent\_work\7\s\src\vctools\crt\vcstartup\src\startup\exe_wmain.cpp @ 17] 
24 00affb80 77e17c14 02c88000 48565845 00000000 kernel32!BaseThreadInitThunk+0x19 [base\win32\client\thread.c @ 64] 
25 00affbdc 77e17be4 ffffffff 77e38feb 00000000 ntdll!__RtlUserThreadStart+0x2f [minkernel\ntdll\rtlstrt.c @ 1153] 
26 00affbec 00000000 00000000 00000000 00000000 ntdll!_RtlUserThreadStart+0x1b [minkernel\ntdll\rtlstrt.c @ 1070] 
```

Method causing assert:
```
0:000> !ip2md 08d0fcdb 
MethodDesc:   08d5fdd0
Method Name:          ComWrappersTests.Common.ITrackerObjectWrapper.AddObjectRef(IntPtr)
Class:                08d9926c
MethodTable:          08d5ff50
mdToken:              06000020
Module:               0893a5f4
IsJitted:             yes
Current CodeAddr:     08d0fcd8
Version History:
  ILCodeVersion:      00000000
  ReJIT ID:           0
  IL Addr:            08cb271c
     CodeAddr:           08d0fcd8  (OptimizedTier1)
     NativeCodeVersion:  02EB0CC0
     CodeAddr:           08d0f680  (QuickJitted)
     NativeCodeVersion:  00000000

0:000> !DumpIL /i 08cb271c
ilAddr = 08CB271C
IL_0000: ldarg.0 
IL_0001: ldflda TOKEN 400000e
IL_0006: ldfld TOKEN 400001c
IL_000b: ldarg.0 
IL_000c: ldfld TOKEN 400000d
IL_0011: ldarg.1 
IL_0012: ldloca.s VAR OR ARG 0
IL_0014: callvirt TOKEN 6000042
IL_0019: stloc.1 
IL_001a: ldloc.1 
IL_001b: brfalse.s IL_0029
IL_001d: ldstr TOKEN 700002b5
IL_0022: ldloc.1 
IL_0023: newobj TOKEN a00002c
IL_0028: throw 
IL_0029: ldloc.0 
IL_002a: ret 

0:000> !U /d 08d0f680
Normal JIT generated code
ComWrappersTests.Common.ITrackerObjectWrapper.AddObjectRef(IntPtr)
ilAddr is 08CB271C pImport is 1C5C7778
Begin 08D0F680, size 95
>>> 08d0f680 55              push    ebp
08d0f681 8bec            mov     ebp,esp
08d0f683 83ec24          sub     esp,24h
08d0f686 c5d857e4        vxorps  xmm4,xmm4,xmm4
08d0f68a c5fa7f65dc      vmovdqu xmmword ptr [ebp-24h],xmm4
08d0f68f 33c0            xor     eax,eax
08d0f691 8945ec          mov     dword ptr [ebp-14h],eax
08d0f694 8945f0          mov     dword ptr [ebp-10h],eax
08d0f697 8945f4          mov     dword ptr [ebp-0Ch],eax
08d0f69a 894dfc          mov     dword ptr [ebp-4],ecx
08d0f69d 8955f8          mov     dword ptr [ebp-8],edx
08d0f6a0 8b4dfc          mov     ecx,dword ptr [ebp-4]
08d0f6a3 8b4910          mov     ecx,dword ptr [ecx+10h]
08d0f6a6 894de8          mov     dword ptr [ebp-18h],ecx
08d0f6a9 8b4dfc          mov     ecx,dword ptr [ebp-4]
08d0f6ac 8b4904          mov     ecx,dword ptr [ecx+4]
08d0f6af 894de4          mov     dword ptr [ebp-1Ch],ecx
08d0f6b2 8b4df8          mov     ecx,dword ptr [ebp-8]
08d0f6b5 51              push    ecx
08d0f6b6 8d4df4          lea     ecx,[ebp-0Ch]
08d0f6b9 51              push    ecx
08d0f6ba 8b4de8          mov     ecx,dword ptr [ebp-18h]
08d0f6bd 894ddc          mov     dword ptr [ebp-24h],ecx
08d0f6c0 8b4ddc          mov     ecx,dword ptr [ebp-24h]
08d0f6c3 8b4904          mov     ecx,dword ptr [ecx+4]
08d0f6c6 8b55e4          mov     edx,dword ptr [ebp-1Ch]
08d0f6c9 8b45dc          mov     eax,dword ptr [ebp-24h]
08d0f6cc ff500c          call    dword ptr [eax+0Ch]
08d0f6cf 8945f0          mov     dword ptr [ebp-10h],eax
08d0f6d2 837df000        cmp     dword ptr [ebp-10h],0
08d0f6d6 7436            je      ComWrappersTests!ComWrappersTests.Common.ITrackerObjectWrapper.AddObjectRef(IntPtr)+0x8e (08d0f70e)
08d0f6d8 b9ac3d830a      mov     ecx,0A833DACh (MT: System.Runtime.InteropServices.COMException)
08d0f6dd e87edebf70      call    coreclr!JIT_New (7990d560)
08d0f6e2 8945ec          mov     dword ptr [ebp-14h],eax
08d0f6e5 b9b5020000      mov     ecx,2B5h
08d0f6ea baf4a59308      mov     edx,893A5F4h
08d0f6ef e8ecb3bf70      call    coreclr!JIT_StrCns (7990aae0)
08d0f6f4 8945e0          mov     dword ptr [ebp-20h],eax
08d0f6f7 8b55f0          mov     edx,dword ptr [ebp-10h]
08d0f6fa 52              push    edx
08d0f6fb 8b55e0          mov     edx,dword ptr [ebp-20h]
08d0f6fe 8b4dec          mov     ecx,dword ptr [ebp-14h]
08d0f701 e882f6ffff      call    CLRStub[MethodDescPrestub]@ba904f0308d0ed88 (08d0ed88)
08d0f706 8b4dec          mov     ecx,dword ptr [ebp-14h]
08d0f709 e8720dc070      call    coreclr!IL_Throw (79910480)
08d0f70e 8b45f4          mov     eax,dword ptr [ebp-0Ch]
08d0f711 8be5            mov     esp,ebp
08d0f713 5d              pop     ebp
08d0f714 c3              ret

0:000> !U /d 08d0fcd8
Normal JIT generated code
ComWrappersTests.Common.ITrackerObjectWrapper.AddObjectRef(IntPtr)
ilAddr is 08CB271C pImport is 08F18A70
Begin 08D0FCD8, size 63
>>> 08d0fcd8 55              push    ebp
08d0fcd9 8bec            mov     ebp,esp
08d0fcdb 57              push    edi
08d0fcdc 56              push    esi (gcstress)
08d0fcdd 83ec08          sub     esp,8 (gcstress)
08d0fce0 33c0            xor     eax,eax (gcstress)
08d0fce2 8945f4          mov     dword ptr [ebp-0Ch],eax (gcstress)
08d0fce5 8b4110          mov     eax,dword ptr [ecx+10h]
08d0fce8 8b4904          mov     ecx,dword ptr [ecx+4]
08d0fceb 894df0          mov     dword ptr [ebp-10h],ecx
08d0fcee 52              push    edx
08d0fcef 8d55f4          lea     edx,[ebp-0Ch]
08d0fcf2 52              push    edx
08d0fcf3 8b4804          mov     ecx,dword ptr [eax+4]
08d0fcf6 8b55f0          mov     edx,dword ptr [ebp-10h]
08d0fcf9 ff500c          call    dword ptr [eax+0Ch] (gcstress)
08d0fcfc 8bf0            mov     esi,eax
08d0fcfe 85f6            test    esi,esi
08d0fd00 750a            jne     ComWrappersTests!ComWrappersTests.Common.ITrackerObjectWrapper.AddObjectRef(IntPtr)+0x68c (08d0fd0c)
08d0fd02 8b45f4          mov     eax,dword ptr [ebp-0Ch]
08d0fd05 8d65f8          lea     esp,[ebp-8]
08d0fd08 5e              pop     esi (gcstress)
08d0fd09 5f              pop     edi (gcstress)
08d0fd0a 5d              pop     ebp (gcstress)
08d0fd0b c3              ret (gcstress)
08d0fd0c b9ac3d830a      mov     ecx,0A833DACh (MT: System.Runtime.InteropServices.COMException)
08d0fd11 e84ad8bf70      call    coreclr!JIT_New (7990d560)
08d0fd16 8bf8            mov     edi,eax
08d0fd18 b9b5020000      mov     ecx,2B5h
08d0fd1d baf4a59308      mov     edx,893A5F4h
08d0fd22 e8b9adbf70      call    coreclr!JIT_StrCns (7990aae0)
08d0fd27 8bd0            mov     edx,eax
08d0fd29 8bcf            mov     ecx,edi
08d0fd2b e808f0ffff      call    CLRStub[MethodDescPrestub]@ba904f0308d0ed38 (08d0ed38)
08d0fd30 89773c          mov     dword ptr [edi+3Ch],esi
08d0fd33 8bcf            mov     ecx,edi
08d0fd35 e84607c070      call    coreclr!IL_Throw (79910480)
08d0fd3a cc              int     3
```

/cc @jkotas @AndyAyersMS

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Update the GC coverage info code path to respect Tiered compilation on a 32-bit platform.

Fixes #36366 

/cc @AndyAyersMS @kouvel

### CODE REVIEW

**Review by kouvel — APPROVED** [review]
LGTM, thanks!

**Comment by AndyAyersMS** [comment]
Seems a little odd to me that native code versions aren't tied in more closely to the jit manager and so can be obtained from a code address with less ceremony.

@AaronRobinsonMSFT have you checked that this fixes the test case?

**Comment by AaronRobinsonMSFT** [comment]
@AndyAyersMS Yep. I locally validated this fixes the issue reported in #36366. I also ran through several other GC stress scenarios in other tests.

**Comment by AaronRobinsonMSFT** [comment]
> Seems a little odd to me that native code versions aren't tied in more closely to the jit manager and so can be obtained from a code address with less ceremony.

@AndyAyersMS I agree. I wish I knew the history behind this design. It makes bugs like this feel even more like the tip of the iceberg rather than one offs.

Does my change here align with your approach?

**Comment by AndyAyersMS** [comment]
Yes, it's the same approach that I started working up. I hit the lock level assert and didn't go further.

**Comment by kouvel** [comment]
> Seems a little odd to me that native code versions aren't tied in more closely to the jit manager and so can be obtained from a code address with less ceremony.

Yea maybe the native code version could be stored instead of the method desc or something like that. Not sure about fragile ngen images and its jit manager, maybe it had something to do with that, or the size since it's a bit larger. Would be nice to be able to get the code version without a lock.

**Pull request merged**
