### PR TITLE
More updates for recent compiler changes for ref fields

### PR DESCRIPTION
**Pull request by cston**
Updates to compile with the latest C# compiler.

Compiles cleanly from the root with `build -rc Release` - with the exception of `tools/dotnet-pgo` which fails to compile since it still references .NET preview 5 SDK.

### CODE REVIEW

**Comment by cston** [comment]
cc @AaronRobinsonMSFT, @jaredpar

**Comment by hoyosjs** [comment]
Failure is #69125/#73621

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
Just to double-check: is `scoped` a known breaking change to the language? Looking at the history, we haven't made meaningful changes to `DispatchEx` that is being modified here for years.

**Comment by cston** [comment]
The breaking change with the C#11 compiler is: when compiling with .NET 7.0 or  `-langversion:11`, a `ref struct` instance or parameter passed by reference is assumed to capture unscoped `ref` or `in` parameters.

To work around the breaking change, the `frameIter` parameter in `DispatchEx()` was marked as `scoped` to indicate that it is not captured.

**Pull request merged**
