### PR TITLE
Remove git bundle logic and restore the original per-job checkout

### LINKED ISSUE #96: Remove repo zip + unzip steps from CI bulds
https://dev.azure.com/dnceng/public/_build/results?buildId=430659&view=logs&j=9269f66d-1f85-5c3b-5cd1-c24f22859cb8

I believe this was added to workaround the throttling that was happening when building coreclr. Since this got fixed via a network reconfiguration on the GitHub side, this can probably be removed.

### PR DESCRIPTION
**Pull request by trylek**
Fixes https://github.com/dotnet/runtime/issues/96

Now that all related infrastructure issues have been fixed, we can
dispose of our homebrew "single-checkout" logic using manually
published git bundles and return to the default behavior of
using git checkout in each job. I believe it's easiest to
opportunistically keep the initial call to "checkout-job" as it's
used for the folder filtering logic used to optimize runs in the
combined repo, I just removed the bundling logic.

Thanks

Tomas

### CODE REVIEW

**Comment by trylek** [comment]
FYI to mono folks as this may have subtle fallout to the newly integrated mono repo.

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Thanks a lot 😃

**Review by safern — APPROVED** [review]
It's unfortunate that the job needs to execute even in non-PR builds, we could condition that, but as discussed offline, we would end-up with really messy yaml for avoiding paying the cost of a 2 second job. We can see how it goes and if it is a problem at the end, condition all references to the checkout job with a compile time condition. Thanks for doing this.

**Comment by trylek** [comment]
Hmm, this is the second time today lab testing of this change failed - @ViktorHofer, are we 100% sure the bug has indeed been fixed and the relevant changes made available to our infra?

https://dev.azure.com/dnceng/public/_build/results?buildId=493156&view=logs&j=3ca9240f-ae6c-5f5b-33bb-c396df155580&t=1101f527-01ef-51fc-899c-86bee8e778dc

**Comment by stephentoub** [comment]
@trylek, still working on this?

**Comment by ViktorHofer** [comment]
This is blocked by AzDO. We can close this meanwhile.

**Pull request closed without merging**
