### PR TITLE
Fix Alpine 3.13 ARM build

### PR DESCRIPTION
**Pull request by janvorli**
Alpine 3.13 is the first version of Alpine Linux that uses 64 bit time_t
on both 64 and 32 bit platforms. That breaks the build as we assumed
that 32 bit platforms use always 32 bit time_t.

This change fixes it by making the PAL time_t type always 64 bit.
Everything still works fine on non-Alpine ARM / x86 Linuxes, since
it only changes the time_t type size outside of PAL.

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @mthalman

**Review by jkotas — APPROVED** [review]

**Comment by mthalman** [comment]
Can you clarify that this will cause the bits to no longer work on Alpine 3.12 ARM?

**Comment by janvorli** [comment]
@mthalman this change only makes compilation work on Alpine 3.13. If someone builds on Alpine <= 3.12 after my change, things will work as before.

**Comment by mthalman** [comment]
> @mthalman this change only makes compilation work on Alpine 3.13. If someone builds on Alpine <= 3.12 after my change, things will work as before.

Those two sentences don't seem compatible.  How can it only make compilation work on Alpine 3.13 but also allow it to be built on Alpine <= 3.12?

**Comment by janvorli** [comment]
I am not sure why it sounds contradictory to you. Let me try to express it in a simpler way. With my change, runtime can be built on any Alpine version.

**Pull request merged**
