### PR TITLE
Delete FEATURE_CORRUPTING_EXCEPTIONS

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Review by janvorli — APPROVED** [review]
LGTM modulo the nits. Very nice cleanup, I would not have expected so much stuff to go away.

**Comment by stephentoub** [comment]
What did all this code do that's being removed?  Is HandleProcessCorruptedStateExceptionsAttribute meaningful after this PR?

**Comment by jkotas** [comment]
HandleProcessCorruptedStateExceptionsAttribute was not meaningful even before this change. https://github.com/dotnet/runtime/issues/31157 tracks making it obsolete.

It was disabled in https://github.com/dotnet/runtime/issues/7272, without the code being actually removed.

**Comment by stephentoub** [comment]
> It was disabled in #7272, without the code being actually removed.

Alrighty then :)

**Pull request merged**
