### PR TITLE
JIT: Don't fold NEG(NEG(X)) to X when NEG(x) is a CSE candidate

### LINKED ISSUE #57470: Unable to find expression in a statement during CSE
```c#
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
//
// This file is auto-generated.
// Seed: -1
//
using System;
using System.Runtime.CompilerServices;
public class TestClass8505
{
    static int s_int32_6 = -5;
    static sbyte s_sbyte_8 = 2;
    static int s_loopInvariant = 3;
    public sbyte LeafMethod8()
    {
        unchecked
        {
            return s_sbyte_8 <<= s_int32_6 >>= s_int32_6 ^ (-2 - (s_int32_6 &= -5)) / (-1 * s_int32_6 * (2 ^ -2)) + 77;
        }
    }
    public void Method0()
    {
        unchecked
        {
            try
            {
            }
            finally
            {
                {
                    int __loopvar1 = s_loopInvariant, __loopSecondaryVar1_0 = 15 - 4;
                    do
                    {
                    }
                    while (15 % 4 > LeafMethod8() / 15 + 4);
                }
                {
                }
            }
            return;
        }
    }
    public static void Main(string[] args)
    {
        TestClass8505 objTestClass8505 = new TestClass8505();
        objTestClass8505.Method0();
    }
}
/*
--------- Test ---------  

Environment:

COMPlus_TieredCompilation=0


gtFindLink failed: stm=STMT00004, exp=[000050]
stm =STMT00004 (IL   ???...0x034)
N022 ( 39, 20)              [000033] -A-XG---R---              *  ASG       int    <l:$11a, c:$119>
N021 (  1,  1)              [000032] D------N----              +--*  LCL_VAR   int    V05 tmp4         d:2 <l:$118, c:$117>
N020 ( 39, 20)              [000031] -A-XG---R---              \--*  RSH       int    <l:$11a, c:$119>
N019 (  1,  1)              [000015] ------------                 +--*  LCL_VAR   int    V03 tmp2         u:2 (last use) <l:$100, c:$142>
N018 ( 34, 18)              [000030] -A-XG-------                 \--*  AND       int    <l:$116, c:$115>
N016 ( 32, 16)              [000028] -A-XG-------                    +--*  XOR       int    <l:$112, c:$111>
N014 ( 30, 14)              [000027] -A-XG-------                    |  +--*  ADD       int    <l:$10e, c:$10d>
N012 ( 28, 12)              [000025] -A-XG-------                    |  |  +--*  DIV       int    <l:$10a, c:$109>
N008 (  5,  6)              [000019] -A----------                    |  |  |  +--*  ADD       int    <l:$104, c:$103>
N006 (  3,  4)              [000067] -A----------                    |  |  |  |  +--*  COMMA     int    <l:$147, c:$146>
N004 (  2,  3)              [000065] -A------R---                    |  |  |  |  |  +--*  ASG       int    $VN.Void
N003 (  1,  1)              [000064] D------N----                    |  |  |  |  |  |  +--*  LCL_VAR   int    V09 cse2         d:1 <l:$147, c:$146>
N002 (  2,  2)              [000049] ------------                    |  |  |  |  |  |  \--*  NEG       int    <l:$147, c:$146>
N001 (  1,  1)              [000009] ------------                    |  |  |  |  |  |     \--*  LCL_VAR   int    V02 tmp1         u:2 (last use) <l:$102, c:$101>
N005 (  1,  1)              [000066] ------------                    |  |  |  |  |  \--*  LCL_VAR   int    V09 cse2         u:1 <l:$147, c:$146>
N007 (  1,  1)              [000003] ------------                    |  |  |  |  \--*  CNS_INT   int    -2 $43
N011 (  3,  3)              [000024] ----G-------                    |  |  |  \--*  LSH       int    <l:$106, c:$105>
N009 (  1,  1)              [000057] ------------                    |  |  |     +--*  LCL_VAR   int    V07 cse0         u:1 <l:$102, c:$101>
N010 (  1,  1)              [000023] ------------                    |  |  |     \--*  CNS_INT   int    2 $44
N013 (  1,  1)              [000026] ------------                    |  |  \--*  CNS_INT   int    77 $46
N015 (  1,  1)              [000018] ------------                    |  \--*  LCL_VAR   int    V04 tmp3         u:2 (last use) <l:$100, c:$144>
N017 (  1,  1)              [000029] ------------                    \--*  CNS_INT   int    31 $47

exp =N007 (  4,  5)              [000050] ----G-------              *  NEG       int    <l:$147, c:$149>
N009 (  1,  1)              [000057] ------------              \--*  LCL_VAR   int    V07 cse0         u:1 <l:$102, c:$101>


Assert failure(PID 46504 [0x0000b5a8], Thread: 48888 [0xbef8]): Assertion failed 'link' in 'TestClass8505:LeafMethod8():byte:this' during 'Optimize Valnum CSEs' (IL size 69)

    File: D:\git\runtime\src\coreclr\jit\optcse.cpp Line: 3290
    Image: D:\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe


*/

```

### PR DESCRIPTION
**Pull request by EgorBo**
Fixes https://github.com/dotnet/runtime/issues/57470

cc @dotnet/jit-contrib

### CODE REVIEW

**Comment by EgorBo** [comment]
NOTE: missing "Is CSE candidate" is a quite popular issue in morph 😞

I think we can write a stress-test where we set "IsCseCandidate" bit early in global morph and detect all transformations which ignore it and still modify trees, something like that.

**Review by jakobbotsch — APPROVED** [review]

**Review by kunalspathak — APPROVED** [review]
LGTM, Thanks

**Comment by kunalspathak** [comment]
@EgorBo - did you get chance to check CI failures? If they are existing, we can go ahead and merge this PR.

**Comment by EgorBo** [comment]
> @EgorBo - did you get chance to check CI failures? If they are existing, we can go ahead and merge this PR.

Yeah, all of them are unrelated and fail on other PRs too (just checked all of them on runfo)

**Pull request merged**
