### PR TITLE
Fix ILVerify Default Method Verification

### LINKED ISSUE #46236: ILVerify rejects classes which inherit default interface method implementations
### Description

ILVerify 5.0.0 does not verify a class which implements an interface which contains a method which is virtual but not abstract. In other words, it doesn't seem to support [default interface methods](https://github.com/dotnet/runtime/blob/9ddd39ed571f6ca82a5b7aee05ac327073b112a3/docs/design/features/default-interface-methods.md).

**Repro steps**:

1. Create a new C# console application (e.g. `dotnet new console`).
2. Ensure the new project has a TargetFramework of `net5.0`.
3. Declare an interface and a method within that interface that provides an implementation. E.g.:
    ```
    interface I
    {
        public string HasDefaultImplementation()
        {
            return "I::HasDefaultImplementation";
        }
    }
    ```
4. Declare a class which implements that interface but does *not* provide an implementation for that method. E.g:
    ```
    class C : I { }
    ```
5. Build and run the project to show that there are no errors building or at runtime. (Optionally, you can exercise the types declared, such as by calling `HasDefaultImplementation` on an instance of `C` which has been cast to `I`.)
6. Install ILVerify as a local tool (e.g. `dotnet new tool-manifest` then `dotnet tool install dotnet-ilverify`).
7. Run ILVerify on the built assembly (e.g. `dotnet ilverify bin\Debug\net5.0\ILVerifyRepro.dll -r "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0\*.dll"`).

**Expected behavior**: the assembly verifies completely.

**Actual behavior**: the following error is reported:

```
[MD]: Error: Class implements interface but not method, Class: '[ILVerifyRepro]ILVerifyRepro.C' Interface: '[ILVerifyRepro]ILVerifyRepro.I' Missing method: '[ILVerifyRepro]ILVerifyRepro.I.HasDefaultImplementation()'.
```

**Reproduction (attachment)**: [ILVerifyRepro.zip](https://github.com/dotnet/runtime/files/5718276/ILVerifyRepro.zip)

**Rationale**:

It sounds like this issue might already be known, based on [this comment](https://github.com/dotnet/runtime/issues/43503#issuecomment-712790904), but I figured I should report it as its own issue both for better visibility and tracking, and also to indicate there's some desire outside of Microsoft / the .NET developers for an accurate ILVerify. Specifically, I represent the Dotfuscator team at PreEmptive, and an up-to-date ILVerify would be very helpful in ensuring we continue to obey the runtime's rules when modifying customers' assemblies, in light of the recent changes to interface methods.

### Configuration

* The example console app targets .NET 5.0. Based on the output of `--list-runtimes`, the only 5.0 runtime I have installed is Microsoft.NETCore.App 5.0.0.
* Running on Windows 10, Version 1903 (10.0.18362.592).
* The machine is x64.
* I would think it unlikely that this issue is configuration-specific.

### Regression?

The oldest version of [dotnet-ilverify listed on NuGet.org](https://www.nuget.org/packages/dotnet-ilverify/) is `5.0.0-preview.7.20364.11`. It errors with a different message:

```
Error: System.Resources.MissingManifestResourceException: Could not find the resource "ILVerification.Strings.resources" among the resources "" 
embedded in the assembly "ILVerify", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at ILVerify.Verifier.<>c__DisplayClass13_0.<VerifyType>b__1(VerifierError code, Object[] args)
   at Internal.TypeVerifier.TypeVerifier.VerificationError(VerifierError error, Object[] args)
   at Internal.TypeVerifier.TypeVerifier.VerifyInterfaces()
   at Internal.TypeVerifier.TypeVerifier.Verify()
   at ILVerify.Verifier.VerifyType(EcmaModule module, TypeDefinitionHandle typeHandle)
   at ILVerify.Verifier.Verify(PEReader peReader, TypeDefinitionHandle typeHandle, Boolean verifyMethods)+MoveNext()
   at ILVerify.Program.VerifyTypes(PEReader peReader, EcmaModule module, String path, Int32& numErrors, Int32& verifiedTypeCounter, Int32& typeCounter)
   at ILVerify.Program.VerifyAssembly(PEReader peReader, EcmaModule module, String path)
   at ILVerify.Program.Run()
   at ILVerify.Program.Run(Options options)
```

The next newest version, `5.0.0-preview.8.20407.11`, produces the same error as in `5.0.0`.

### PR DESCRIPTION
**Pull request by bbartels**
Fixes https://github.com/dotnet/runtime/issues/46236

The fix involves checking whether an interface method has a method body, as opposed to static, to avoid the search for an implementation in a child class. 

I think the ILVerify building/testing workflow should be documented somewhere. It took me quite some time to figure out that the tests were only built when using `priority=1`.
Furthermore, I ran into the issue of running `dotnet test` in the ILVerify tests folder. This supposedly permanently breaks your build until you clean all artifacts and recompile (https://github.com/dotnet/runtime/issues/43967).
Finding and fixing the issue took about half an hour, managing to get the tests working as a first time contributor to the ILVerify tool took about 4 hours.

### CODE REVIEW

**Comment by am11** [comment]
> managing to get the tests working as a first time contributor to the ILVerify tool took about 4 hours

Agreed, finding the solution for `CS0234` error was not obvious, and took some time to figure out. I ended up with a little handrolled bash script to run a specific test after changing code and rebuilding the source and tests. Basically simulated this workflow for ILVerification project: https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/docs/workflow/testing/libraries/testing.md#L46

**Comment by bbartels** [comment]
@am11 
Honestly don't think I would have been able to resolve this without your issue. I don't have the most powerful PC so simply building `.\build.cmd -c Release` takes about 40 minutes. So I was very opposed to the idea of rebuilding if there was still a chance of fixing it without.

**Comment by bbartels** [comment]
If I were to submit a PR to document the way to build this project should this be in `docs/` or `src/coreclr/tools/ilverify`?
(Assuming this is desired in the first place)

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by jkotas** [comment]
> If I were to submit a PR to document the way to build this project 

This would be much appreciated!

> hould this be in `docs/` or `src/coreclr/tools/ilverify`

The documentation is in https://github.com/dotnet/runtime/blob/master/src/coreclr/tools/ILVerify/README.md. I think it would be best to keep updating this document with ILVerify specific testing instructions.

**Comment by bbartels** [comment]
@jkotas should a separate PR be preferable or shall I append it to this one?

**Comment by jkotas** [comment]
Could you please submit a new PR with the documentation changes?

**Pull request merged**
