### PR TITLE
Build scripts while copying native binaries

### PR DESCRIPTION
**Pull request by sdmaclea**
Stop building test scripts during the managed build phase
Build after copying the native targets
Only build scripts for the current platform.

Remove issues relative to building scripts on OSX

### CODE REVIEW

**Review by trylek — APPROVED** [review]
LGTM

**Review by jashook — APPROVED** [review]
Lgtm thank you for the change

**Comment by jashook** [comment]
Ah I think I know the problem, superpmi I think copied these files and expects them already to be on disk.

**Comment by jashook** [comment]
```
  <ItemGroup>
    <_SpmiTestProjects Include="..\Performance\CodeQuality\Bytemark\Bytemark.csproj" />
    <_SpmiTestProjects Include="..\Methodical\fp\exgen\10w5d_cs_do.csproj" />
    <_SpmiTestProjects Update="@(_SpmiTestProjects)">
      <Properties>OutputPath=$(OutputPath)\%(FileName)</Properties>
    </_SpmiTestProjects>
  </ItemGroup>
```

**Comment by jashook** [comment]
@sdmaclea this test I believe can just be marked as platform specific to avoid this problem

**Review by swaroop-sridhar — APPROVED** [review]

**Comment by sdmaclea** [comment]
I just pushed the fix for the `superpmi` build scripts.  I spent the better part of a day trying to figure out how to add a project target that depended on our other targets.  I think this solution is clean.

**Comment by BruceForstall** [comment]
Is there a dev innerloop impact with this change? E.g., when are the wrapper scripts generated? During test build time? Some kind of on-platform pre-test-run time?

**Comment by sdmaclea** [comment]
@BruceForstall There is not intended to be a **significant** impact to normal dev experience.

The intention is for the scripts to be generated at the same time as the native binaries are built, because both are target specific.
  
+ So the intended change is for the scripts to build unless `skipnative` is selected.
+ Previously they would build unless `skipmanaged` was selected.

**Pull request merged**
