### PR TITLE
Make GCMemoryInfoData blittable

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
The runtime side makes assumptions about the layout of this class, but since the class is not blittable, the runtime is free to reorder the fields however it sees fit (`StructLayout(LayoutKind.Sequential)` only affects the *managed* layout of blittable classes - it's not documented to do anything to the managed layout of non-blittable classes).

This prevents improvements to managed layout such as #51416.

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Thanks

**Comment by MichalStrehovsky** [comment]
```
      Assert failure(PID 4696 [0x00001258], Thread: 764 [0x02fc]): Consistency check failed: Managed object size does not match unmanaged object size
      man: 0x114, unman: 0x118, Name: System.GCMemoryInfoData
      FAILED: size == expectedsize
```

Sigh. If I'm reading the tea leaves right, his is failing on 32bit platforms because the native side will try to align the beginning of `GCMemoryInfoData` so that it's 8-byte aligned (adding padding after the `MethodTable` pointer), but the managed side doesn't do that.

I wonder if the best course of action would be to just rewrite the FCall to take a reference to the first field of `GCMemoryInfoData`.

**Comment by jkotas** [comment]
@MichalStrehovsky PTLA at my suggested fix.

**Comment by MichalStrehovsky** [comment]
>@MichalStrehovsky PTLA at my suggested fix.

Clever! Thank you!

I've re-kicked the failing CI leg because it looks like the known infra issue (collection was modified).

**Pull request merged**
