### PR TITLE
JIT: Remove hasLikelihood checks; make FlowEdge::m_likelihoodSet debug-only

### PR DESCRIPTION
**Pull request by amanasifkhalid**
Part of #93020. Now that edge likelihoods are expected to be set throughout all phases, when transferring the likelihood of an existing edge to a new edge, we should assume the former edge's likelihood should already be set. By removing all non-debug conditional logic that uses `hasLikelihood`, we can make `m_likelihoodSet` available only in Debug builds again.

### CODE REVIEW

**Comment by amanasifkhalid** [comment]
cc @dotnet/jit-contrib, @AndyAyersMS PTAL. [No diffs.](https://dev.azure.com/dnceng-public/public/_build/results?buildId=607329&view=ms.vss-build-web.run-extensions-tab)

**Review by AndyAyersMS — COMMENTED** [review]
If `getLikelihood` asserts `m_LikelihoodSet` could we drop all the `hasLikelihood` asserts in the "client" bits of code?

**Comment by amanasifkhalid** [comment]
> If getLikelihood asserts m_LikelihoodSet could we drop all the hasLikelihood asserts in the "client" bits of code?

Yes, good point -- fixed.

**Review by AndyAyersMS — APPROVED** [review]

**Comment by amanasifkhalid** [comment]
SPMI failures are timeouts.

**Pull request merged**
