### PR TITLE
[release/7.0-staging] Eliminate cancellation deadlock in RateLimiter implementations (#90285)

### PR DESCRIPTION
**Pull request by BrennanConroy**
Backport of https://github.com/dotnet/runtime/pull/90285 to release/7.0-staging

## Customer Impact

Rate limiting operations could deadlock in specific scenarios.

## Testing

Manual testing and automated test with internal hooks added

## Risk

Low. Issue was clear once pointed out.

### CODE REVIEW

**Comment by danmoseley** [comment]
this was approved in email on 8/10

**Comment by danmoseley** [comment]
@carlossanlop does @BrennanConroy merge now?

**Comment by carlossanlop** [comment]
PR owners are free to merge whenever, but just so you know, I already flowed everything from staging into internal. Do we absolutely need this in the October Release? If yes, then I'll have to flow this PR alone manually.

**Comment by carlossanlop** [comment]
I mention the above because Code complete was yesterday for servicing, @danmoseley.

**Review by halter73 — APPROVED** [review]

**Comment by carlossanlop** [comment]
Since this was merged one day after code complete, it was too late and will have to wait until the next month to release it.

**Pull request merged**
