### PR TITLE
Process.Unix: handle ETXTBSY error when executing file that was just written by .NET.

### LINKED ISSUE #58964: Modifying a file and then executing it can fail on Linux
https://github.com/golang/go/issues/22315 sets out the issue.

Fundamentally, this seems like an inescapable race in multi-threaded programs on Linux.

My understanding of the failure is this:

1. A process with two threads wants to write a file and then execute it.
2. Thread 1 opens a file for writing
3. Thread 2 issues a call to create a new process and completes a `fork` call.
4. The new process inherits all file descriptors open in Process 1, including the file opened by Thread 1.
5. Thread 1 finishes writing and closes the file descriptor.
6. Thread 1 attempts to execute the file.
7. Linux produces ETXTBSY ("Text file is busy") because Process 2 still has an open handle to the file.

I don't see a way to completely prevent this race, as there's no way to avoid executing `fork` to create a new process on Linux. However, there are two mitigations we could consider:

~~1. Unix supports a FD_CLOEXEC flag on file descriptors, which indicates that the file descriptor should be closed after a call to `exec`. Since the "new process" procedure in Unix is `fork+exec`, this would narrow the window of the race to just after `fork` and just before `exec`. It may be possible to always set this flag when opening file descriptors on Linux from managed code -- we don't support `fork` without `exec` and inheriting non-tty open file descriptors does not appear to be in any .NET contract.~~ we already do this
1. Introduce a retry into Process.Create if encountering `ETXTBSY`. This could workaround the issue, at the expense of taking longer to fail in a real contention situation.

### PR DESCRIPTION
**Pull request by tmds**
ETXTBSY means we're trying to execute a file that is open for write.
This may be a file that was just written and closed, but is still referenced by another process that has forked but not yet exec-ed.

When this error occurs, we wait for all processes to finish exec-ing, which causes the file to be closed (CLOEXEC). Then we start the process again.

Fixes https://github.com/dotnet/runtime/issues/58964.

cc @agocke @jkotas @adamsitnik

### CODE REVIEW

**Comment by tmds** [comment]
This helps but it is not a 100% solution.

We wait for all processes that have forked to exec-d.

We consider it exec-ed when we've observed the close-on-exec of a pipe end that was handed to the child:

https://github.com/dotnet/runtime/blob/4ac2aaa87db417e57715abe63078bb6a2d8a18a4/src/libraries/Native/Unix/System.Native/pal_process.c#L452-L456

So we know for sure the pipe end was closed, but this happens as part of a loop in the kernel and the handle we care about may come later in this loop...

If in addition to the changes in this PR we do something that causes the handle to be closed between `fork` and `exec` it will work. There have been some requests for control of handle inheritance when starting processes (like https://github.com/dotnet/runtime/issues/13943).
And Linux and other OSes have support for efficiently closing a range of file descriptors, e.g. [close_range](https://man7.org/linux/man-pages/man2/close_range.2.html).

@agocke @jkotas @adamsitnik should we adopt the changes to `Process.Unix.cs` and consider it an improvement, though not a complete fix?

**Comment by stephentoub** [comment]
> This helps but it is not a 100% solution

Isn't this also only helping in the case where the process using the file was created by this parent process? It's using a lock specific to the process to achieve the waiting. 

Based on my current understanding,  I don't think we should take this.  It's introducing non-trivial additional complexity and synchronization and the fundamental issue still exists.

**Comment by tmds** [comment]
> Isn't this also only helping in the case where the process using the file was created by this parent process? It's using a lock specific to the process to achieve the waiting.

Yes, this is for the specific use-case when a .NET application writes an executable file, and then executes it using `Process.Start`.

A race occurs when another `Process.Start` forks while the executable is being written, and it has not yet exec-ed.
Because this second process holds the executable file handle open until it execs (CLOEXEC), the first process fails to start with `ETXTBSY`.

By taking the writer lock we wait until all processes have exec-ed and started to apply CLOEXEC (`waitForChildToExecPipe[READ_END_OF_PIPE]` was closed).

**Comment by stephentoub** [comment]
What happens if the file is written but the app neglects to close it... Process.Start will now hang rather than error?

**Comment by tmds** [comment]
> What happens if the file is written but the app neglects to close it... Process.Start will now hang rather than error?

We handle `ETXTBSY` once, and second time we throw for it.

**Comment by stephentoub** [comment]
Will the test you added succeed 100% of the time?

**Comment by tmds** [comment]
> Will the test you added succeed 100% of the time?

No, I have to remove it.
When making the PR I thought it would pass, because that happened on my machine.
When it failed in CI, I had to figure out why.

I'm ok if we won't merge because it is a nice use-case and not a 100% fix.

I can add a test that ensures `Process.Start` doesn't hang for a file that remains open.

**Comment by tmds** [comment]
This is as good as I can make it. It's an improvement, but not a 100% solution.

@stephentoub feel free to merge or close the PR.

**Comment by jkotas** [comment]
My vote is for closing this PR. I do not think it is worth it given that it is not 100% fix. @tmds Thank you for giving it a shot!

**Pull request closed without merging**
