### PR TITLE
Re-enable windows JIT formatting jobs

### PR DESCRIPTION
**Pull request by BruceForstall**
Addresses https://github.com/dotnet/runtime/issues/40034

### CODE REVIEW

**Comment by BruceForstall** [comment]
Testing to see if it's fixed.

**Comment by hoyosjs** [comment]
QQ @BruceForstall, did the Windows Formatting job always perform a full build?

**Comment by BruceForstall** [comment]
> QQ @BruceForstall, did the Windows Formatting job always perform a full build?

I don't think so, but is uses a compile_commands.json file that is only produced by the ninja build now, so it does a full build because of that. I'm not sure if it could be trimmed, nor do I know what's in the json...

**Comment by BruceForstall** [comment]
Looks like the error is out of disk space:
```
D:\a\1\s\src\coreclr\gc\gcwks.cpp : fatal error C1085: Cannot write compiler generated file: 'D:\a\1\s\artifacts\nmakeobj\windows.x64.Release\gc\CMakeFiles\clrgc.dir\gcwks.cpp.obj': No space left on device
```

not sure if that's an issue with which machines are allocated to this job, or...?

**Comment by hoyosjs** [comment]
> I don't think so, but it uses a compile_commands.json file that is only produced by the ninja build now, so it does a full build because of that. I'm not sure if it could be trimmed, nor do I know what's in the json...

We shouldn't build. Doing a cmake configure should be enough. The compile_commands.json file gets generated before the actual build. The json is just a list of files and how they get translated to an obj file and how to link them. You probably need them to see the preprocessor expansions with the correct defines.

> Looks like the error is out of disk space not sure if that's an issue with which machines are allocated to this job, or...?

Yes. This job seems to be using `vmImage: windows-2019`, which has a 10GB limitation. This should be enough if we avoid building nonetheless.

**Comment by BruceForstall** [comment]
I've closed this because I was curious if it would "just work" but I don't want to spend any time on actually getting it to work...

**Comment by BruceForstall** [comment]
After https://github.com/dotnet/jitutils/pull/318 was merged, try this again.

**Comment by BruceForstall** [comment]
Log file for the successful windows x64 formatting job:

https://dev.azure.com/dnceng/public/_build/results?buildId=1027421&view=logs&jobId=db5b9618-eefc-58e8-4554-fbce452d4dac&j=db5b9618-eefc-58e8-4554-fbce452d4dac&t=29bb2718-3138-535b-c6ac-1a4597023815

**Comment by BruceForstall** [comment]
After recent changes, the Windows JIT formatting job works again. I propose to re-enable it.

@dotnet/jit-contrib PTAL

**Review by hoyosjs — APPROVED** [review]

**Review by echesakov — APPROVED** [review]

**Review by kunalspathak — APPROVED** [review]

**Pull request merged**
