### PR TITLE
Re-enable failing long path test

### LINKED ISSUE #64019: `System.IO.Tests.DirectoryLongerThanMaxLongPathWithExtendedSyntax_ThrowsException` test failing
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1561172&view=logs&jobId=55b384d0-d6b0-5894-fd8a-d754d713246e&j=55b384d0-d6b0-5894-fd8a-d754d713246e&t=8dcacd81-cb5e-5ac9-93e5-c3f19b19e19b), and [Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-64006-merge-6ddf3f0da353465cbe/System.IO.FileSystem.Tests/1/console.30f69daf.log?sv=2019-07-07&se=2022-02-08T19%3A54%3A24Z&sr=c&sp=rl&sig=dXHdaY0MNznmGbgkm7Yw9r4zp0O7%2FIhMgZUXK4vypWk%3D)

```
    System.IO.Tests.DirectoryInfo_Create.DirectoryLongerThanMaxLongPathWithExtendedSyntax_ThrowsException [FAIL]
      Assert.All() Failure: 2 out of 2 items in the collection did not pass.
      [1]: Item: \\?\C:\h\w\BFA20AC3\t\DirectoryInfo_Create_ipbli234.zri\DirectoryLongerThanMaxLongPathWithExtendedSyntax_ThrowsException_271_a66fa5a7\802869a5d16b495fa5d074e146cb2cd7...

Xunit.Sdk.XunitException: Expected one of: (System.IO.PathTooLongException, System.IO.DirectoryNotFoundException) -> Actual: (System.IO.IOException)
              at System.AssertExtensions.ThrowsAnyInternal(Action action, Type[] exceptionTypes) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 212
              at System.AssertExtensions.ThrowsAny[TFirstExceptionType,TSecondExceptionType](Action action) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 222
              at System.IO.Tests.Directory_CreateDirectory.<DirectoryLongerThanMaxLongPathWithExtendedSyntax_ThrowsException>b__27_0(String path) in /_/src/libraries/System.IO.FileSystem/tests/Directory/CreateDirectory.cs:line 274
              at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 36
```

### PR DESCRIPTION
**Pull request by danmoseley**
Fix #64019
Reenable test, tolerant of the new error code.

### CODE REVIEW

**Review by adamsitnik — COMMENTED** [review]
This reminds me of inconsistencies between Linux and macOS where we typically handle them on our side and provide the same user experience.

Perhaps we should add a special mapping for Win 11 and `ERROR_INVALID_NAME` for file paths longer than the Windows limit and throw `PathTooLongException`?

https://github.com/danmoseley/runtime/blob/07ead81ec217baa72fa85c22a240fa8b34d8da9e/src/libraries/System.IO.FileSystem/tests/PortedCommon/IOInputs.cs#L17-L18

**Comment by danmoseley** [comment]
@adamsitnik we could, and its your call. I don't think it's much value though; consistent exceptions are good, but it's presumably not common to supply paths of over 32KB and (apparently, given how the test was written) you're already potentially going to get 2 possible exceptions depending on what Windows chooses to return. You might already catch IOException to cover them both.

I suggest to re-enable this test, and if you want you could open an up for grabs to do what you suggest.

**Review by adamsitnik — APPROVED** [review]
@danmoseley thanks!

**Comment by adamsitnik** [comment]
@danmoseley you are right. BTW I've tried to repro it on my local machine and have failed. Let's keep it as it is (also I would not be surprised if the Win 11 behavior change is reverted at some point of time).

**Pull request merged**
