### PR TITLE
HTTP/3 Reenabled cookie tests

### LINKED ISSUE #53093: [HTTP/3] Disabled test classes
In HTTP functional tests, there is 3 places where the whole test classes are suppressed with `#if false`:
- **Cookies**: `SocketsHttpHandlerTest_Cookies_Http3_MsQuic` and `SocketsHttpHandlerTest_Cookies_Http3_Mock`
- ~~**Cancellation**: `SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http3_MsQuic` and `SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http3_Mock`~~ -> #54727
- ~~**AltSvc**: `SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3_MsQuic` and `SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3_Mock`~~ -> #53786

This issue is to serve as a reminder to investigate and either fix or delete the tests. This issue can be split into separate ones for individual problems.

### PR DESCRIPTION
**Pull request by ManickaP**
It was dependent on #55025 which has been fixed, so I'm just re-enabling the tests.

I ran locally more than 100 loops of HTTP tests without any problems.

Fixes #53093

### CODE REVIEW

**Review by MihaZupan — APPROVED** [review]

**Comment by wfurt** [comment]
```
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3_Mock.GetAsyncWithRedirect_ReceiveSetCookie_CookieSent [FAIL]
      System.Net.Http.HttpRequestException : An error occurred while sending the request.
      ---- System.Net.Quic.QuicStreamAbortedException : Stream aborted by peer (267).
      Stack Trace:
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(246,0): at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(292,0): at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs(213,0): at System.Net.Http.Http3Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(927,0): at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(989,0): at System.Net.Http.HttpConnectionPool.DetermineVersionAndSendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1019,0): at System.Net.Http.HttpConnectionPool.SendAndProcessAltSvcAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(1038,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(81,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(527,0): at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cookies.cs(616,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Cookies.<GetAsyncWithRedirect_ReceiveSetCookie_CookieSent>b__26_0(Uri url)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(64,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(91,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs(38,0): at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackServer.cs(98,0): at System.Net.Test.Common.Http3LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout, GenericLoopbackOptions options)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cookies.cs(607,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Cookies.GetAsyncWithRedirect_ReceiveSetCookie_CookieSent()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/Mock/MockStream.cs(76,0): at System.Net.Quic.Implementations.Mock.MockStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(721,0): at System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(305,0): at System.Net.Http.Http3RequestStream.ReadResponseAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs(195,0): at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken)
  Finished:    System.Net.Http.Functional.Tests
=== TEST EXECUTION SUMMARY ===
```


ignore Mock for now...?

**Comment by ManickaP** [comment]
I re-disabled the mock version, once merged, I'll update the issue to reflect that and move it to future.

**Comment by geoffkizer** [comment]
Error code 267 is H3_REQUEST_REJECTED, which is coming from the loopback server.

What happens here is that the cookie test is issuing an H3 request that will result in a redirect. The redirect handling logic then issues a second request for the redirect.

Meanwhile, the server logic here is sending the first response and then closing the connection gracefully (i.e., sending GOAWAY and then waiting for the client to close the connection). As part of the graceful shutdown logic, it rejects any new requests with H3_REQUEST_REJECTED, which indicates to the client that it should retry the request on a new connection.

So there's an inherent race here. It should be handled by the client checking for H3_REQUEST_REJECTED and retrying the request on a new connection. We have this sort of logic for HTTP2, but it seems we either aren't doing this for HTTP3 or are not doing it properly.

I suspect that that this is not a Mock-specific issue; it's just timing related (and thus probably happens more in CI, unfortunately).

**Comment by ManickaP** [comment]
> Error code 267 is H3_REQUEST_REJECTED, which is coming from the loopback server.

I added handling similar to what we have in H/2.

However, if I ran the test in a tight loop, I still saw failures at around iteration 600, failing the MaxRetry limit:
https://github.com/dotnet/runtime/blob/1a4675db08384e4f20cf4481e6eaf03e40f3d754/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1033-L1041

I don't know if there's something that can be done about it. Are we somehow too slow to close the connection? Should we do some blocking/waiting there?

**Comment by ManickaP** [comment]
So I disable only those cookie tests that were using more than 1 server-side connection. And I disabled them only for H/3 --> in an if with `ActiveIssue` in comment.

**Review by wfurt — APPROVED** [review]
LGTM if it holds test runs.

**Comment by ManickaP** [comment]
Failures are unrelated.

**Pull request merged**
