### PR TITLE
Support profiler activation for same bitness architectures on Windows ARM64 and macOS Apple Silicon

### PR DESCRIPTION
**Pull request by ww898**
Please see #39699 for details.

### CODE REVIEW

**Comment by davmason** [comment]
The change looks good. What testing have you done? I don't think this code path is likely to change much so we shouldn't need to write a test and check it in, but have you at least verified that it behaves as you expect?

**Comment by ww898** [comment]
Hi @davmason, the pull request is still blocked. Could you please approve it?

**Comment by davmason** [comment]
Hi @ww898, I am still waiting on your response to what testing has been done. Have you verified that this works as expected for you?

**Comment by davmason** [comment]
Hi @ww898 have you seen my questions above?

**Comment by ww898** [comment]
Hi @davmason, probably I missed your message. Sorry, it's my fault. I thought the fix is clear and simple enough to be verified in code review. I'll take my M1 and start the pull request verification tomorrow.

**Comment by ww898** [comment]
Tested!!! On real .NET6 runtime ARM64

**Review by davmason — APPROVED** [review]
Thanks for this!

**Pull request merged**
