### PR TITLE
Expand NativeAOT testing platforms

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
* We don't officially support x64 Mac because it would look dumb if we don't support ARM64. I would still like to see us testing it to prevent regressions.
* We should ideally support MUSL-based Linux officially (let's see how close we're based on CI).

### CODE REVIEW

**Comment by LakshanF** [comment]
Retrying since the changes that caused #73666 was reverted

**Review by LakshanF — APPROVED** [review]
LGTM, no OSX testing in this, right?

**Comment by MichalStrehovsky** [comment]
I reverted the OSX part because it was a crashfest and nobody is going to look at that in the 7.0 timeframe: https://github.com/dotnet/runtime/issues/73299#issuecomment-1210220788

**Pull request merged**
