### PR TITLE
[browser][MT][hybridglobalization] Run `HybridGlobalization` threading tests

### LINKED ISSUE #98483: [browser][MT] hybrid globalization
plan A)
- make hybrid globalization not supported with MT
- tree-shake hybrid JS code via rollup `WasmEnableThreads` conditional compilation
- ideally move the code to sub-folder
- also conditonal ICALs in `corebindings.c`
- switch off HG tests with MT

plan B) - applied
- [x] reduce usage of `mono_wasm_new_external_root`, and `stringToMonoStringRoot` from hybrid
   - perhaps the string could be `fixed` in C# before making this call instead.
- [x] wrap_error_root`, `wrap_no_error_root` https://github.com/dotnet/runtime/issues/98365
- [x] because they interact with GC, which could lead to deadlock on UI thread.
- [ ] load rules json on all workers - working on it in https://github.com/dotnet/runtime/pull/102595

### LINKED ISSUE #102305: [browser][MT][hybridglobalization] Run HybridGlobalization MT tests
After https://github.com/dotnet/runtime/pull/101543 is merged.

Add to `/azp run runtime-wasm`. Will require a small fix: "load rules json on all workers".

Contributes to https://github.com/dotnet/runtime/issues/98483.

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/102305, fixes https://github.com/dotnet/runtime/issues/98483.

The tests still fail on indexing/prefix/suffix functions -> segmentation rules are still not loaded properly.

### CODE REVIEW

**Comment by pavelsavara** [comment]
> segmentation rules are still not loaded properly.

I would prefer to fix it here before we merge this.

**Comment by ilonatommy** [comment]
This PR is not in a mergable state, sorry for confusion, I'm still working on it

**Comment by ilonatommy** [comment]
Saving the failing log:
```
[10:35:41] info: Running at: http://127.0.0.1:44279/index.html?arg=--setenv%3dIsBrowserThreadingSupported%3dtrue&arg=--run&arg=WasmTestRunner.dll&arg=Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.dll&arg=-threads&arg=-parallelThreads&arg=8&arg=-notrait&arg=category%3dIgnoreForCI&arg=-notrait&arg=category%3dOuterLoop&arg=-notrait&arg=category%3dfailing&arg=-verbosity&arg=Info
[10:35:41] fail: [out of order message from the browser]: http://127.0.0.1:44279/runArgs.json - Failed to load resource: the server responded with a status of 404 (Not Found)
[10:35:41] info: could not load /runArgs.json: 404. Ignoring
[10:35:41] info: Incoming arguments: --setenv=IsBrowserThreadingSupported=true --run WasmTestRunner.dll Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.dll -threads -parallelThreads 8 -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -verbosity Info
[10:35:41] info: Application arguments: --run WasmTestRunner.dll Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.dll -threads -parallelThreads 8 -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -verbosity Info
[10:35:42] fail: [--021d6038-emsc 10:35:41.989] MONO_WASM: mono_wasm_pthread_on_pthread_created () failed TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [--021d6038-emsc 10:35:42.039] MONO_WASM: at.getSegmentationRules is not a function
                 TypeError: at.getSegmentationRules is not a function
                     at http://127.0.0.1:44279/_framework/dotnet.runtime.js:3:59252
                     at e.threadInitTLS (http://127.0.0.1:44279/_framework/dotnet.runtime.js:3:59431)
                     at handleMessage (http://127.0.0.1:44279/_framework/dotnet.native.worker.mjs:1:2295)
[10:35:42] fail: [--000fb4f8-emsc 10:35:42.070] MONO_WASM: Uncaught TypeError: at.getSegmentationRules is not a function
                 Error
                     at Object.uo [as mono_exit] (http://127.0.0.1:44279/_framework/dotnet.js:3:27332)
                     at st.config.exitOnUnhandledError.e.onerror (http://127.0.0.1:44279/_framework/dotnet.runtime.js:3:31939)
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.native.js 7:1226 Uncaught ErrorEvent: Uncaught TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/index.html?arg=--setenv%3dIsBrowserThreadingSupported%3dtrue&arg=--run&arg=WasmTestRunner.dll&arg=Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.dll&arg=-threads&arg=-parallelThreads&arg=8&arg=-notrait&arg=category%3dIgnoreForCI&arg=-notrait&arg=category%3dOuterLoop&arg=-notrait&arg=category%3dfailing&arg=-verbosity&arg=Info 0:0 Uncaught ErrorEvent: Uncaught TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.native.js 7:1226 Uncaught ErrorEvent: Uncaught TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.js 2 Uncaught (in promise) TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.native.js 7:1226 Uncaught ErrorEvent: Uncaught TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.js 2 Uncaught (in promise) TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.native.js 7:1226 Uncaught ErrorEvent: Uncaught TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.js 2 Uncaught (in promise) TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.native.js 7:1226 Uncaught ErrorEvent: Uncaught TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.js 2 Uncaught (in promise) TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.native.js 7:1226 Uncaught ErrorEvent: Uncaught TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.js 2 Uncaught (in promise) TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.native.js 7:1226 Uncaught ErrorEvent: Uncaught TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.js 2 Uncaught (in promise) TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.native.js 7:1226 Uncaught ErrorEvent: Uncaught TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.js 2 Uncaught (in promise) TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.js 2:472 Uncaught ErrorEvent: Uncaught TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.runtime.js 2:221141 Uncaught ErrorEvent: Uncaught TypeError: at.getSegmentationRules is not a function
[10:35:42] fail: [out of order message from the browser]: http://127.0.0.1:44279/_framework/dotnet.native.worker.mjs 0 Uncaught TypeError: at.getSegmentationRules is not a function
```

**Pull request closed without merging**
