### PR TITLE
[release/5.0-rc2] Prevent JSON async deserialization errors when partial buffer ends in the middle of null token (#42158)

### PR DESCRIPTION
**Pull request by layomia**
Backport of https://github.com/dotnet/runtime/pull/42158 ("Fix continuation of JSON deserialization") to release/5.0-rc2. Updated this PR's title to more accurately reflect the issue being fixed.

### Customer Impact

- Fixes https://github.com/dotnet/runtime/issues/42070.
- Common scenario
- Regression from 3.1.
- Reported by multiple users.
- Issue labeled as `blocking-release`/`regression-from-last-release`.

Prior to this PR, the serializer could throw a JSON exception when async deserializing JSON payloads that contain null tokens. If a partial segment of the payload being read ended in the middle of a null token, the serializer could throw a `JsonException` after fetching more data and resuming deserialization.

A simple example:

Initial buffer: `{"Foo":"Bar","Baz":nu`

Next buffer: `ll,"Qux":"Quux"}` // Serializer throws error when resuming deserializing after fetching this data.

---

`async` and `null` handling are both commonly used features in the serializer. This issue would likely be faced by numerous users if not fixed.

### Testing

The PR has been tested extensively across multiple factors: null token position, matching property type (nullable/non-nullable), deserialization constructor mode (parameterized/non-parameterized), payload size (small/large), and so on.

The fixing PR has also been verified on customer input which flagged down the issue.

### Risk

This fix is small and targeted. It is unlikely to cause issues elsewhere.

### CODE REVIEW

**Comment by danmosemsft** [comment]
Great info in template. However if this is a bad regression why did we only know about it now at the last minute? Or did it regress recently?

**Comment by layomia** [comment]
I think more people are trying out System.Text.Json in .NET 5 due to RC1 release, especially as `JSON` improvements were highlighted in the [blog post](https://github.com/dotnet/runtime/pull/42158#discussion_r488907272). The plan is to bolster the tests for more continuation scenarios - https://github.com/dotnet/runtime/pull/42158#discussion_r488907272 and continue testing/validating other features.

**Comment by danmosemsft** [comment]
Thanks. It would be good to include that extended testing in this PR, if it’s for related issues. The goal is to minimize the possibility we have to bring another. We can take to tactics tomorrow even if that part is not ready, but that way if something else is found we can potentially roll it in.

**Review by steveharter — APPROVED** [review]
LGTM; definitely agree that we need this in 5.0.

**Comment by layomia** [comment]
Okay to wait until the extended testing is in - https://github.com/dotnet/runtime/pull/42393.

**Comment by danmosemsft** [comment]
@ericstj I’m supportive, feel free to send mail to tactics if you support it

**Review by ericstj — APPROVED** [review]

**Comment by danmosemsft** [comment]
Don't let it stop this PR, but I think these test strings of > 200KB probably should be in the test data repo as they just bloat the repo. Once you've merged them though, that bloat is locked in.

**Comment by ericstj** [comment]
approved over mail.  Merge at will.  

You can address the string suggestion in master.  @danmosemsft we're usually more sensitive about the type of data and how much it changes.  Text data is typically OK at somewhat larger sizes if it doesn't change too often, since it compresses really well in git.  In fact git uses zlib compression which is based on DEFLATE same as zip used in nupkg.  Binary data, especially binary data that changes often, is what we make sure to put in assets packages.  Also any large data that would be considered "optional" for some repo consumers.  Maybe we could write some guidelines down somewhere :)

**Comment by danmosemsft** [comment]
@ericstj that makes sense. sounds good

**Comment by layomia** [comment]
> You can address the string suggestion in master.

> Maybe we could write some guidelines down somewhere :)

Opened https://github.com/dotnet/runtime/issues/42428 to track these.

**Pull request merged**
