### PR TITLE
[wasm][debugger] Removed internalProperties group.

### LINKED ISSUE #75778: [wasm][debugger] Object members that are protected accessors are not displayed in debugger window even though proxy is informed about them
Code:
```
    private void IncrementCount()
    {
        JObject myObj = new JObject();
        myObj.Add("thays", new JObject());
    }
```
Disable JustMyCode in Debugger settings.

Try to look at myObj in locals, you will not see the property ChildrenTokens, and we are able to see it in a .net6 app.

This is the definition of it:
`protected override IList<JToken> ChildrenTokens => _properties;`

### PR DESCRIPTION
**Pull request by ilonatommy**
Fixes https://github.com/dotnet/runtime/issues/75778.

Motivation: https://github.com/dotnet/runtime/issues/75778#issuecomment-1252541452.

It fixes a bug from net 7, so will need backporting.

### CODE REVIEW

**Comment by thaystg** [comment]
If the tests are passing, LGTM.

**Review by thaystg — APPROVED** [review]

**Review by lewing — APPROVED** [review]

**Comment by radical** [comment]
@ilonatommy just curious, is VS using the `privateProperties` part?

**Review by radical — APPROVED** [review]
Changes look fine to me. I just have a few questions:

- How is VS surfacing the public/private/protected members? Is it reading anything other than `"result"`?
- We should also test this same thing with `protected` members being overridden by a derived class. And the base/derived split should be tested for being in the user code, and being `base (!user code) -> derived(user code)`

**Comment by radical** [comment]
Also, it would be a good idea to remove all the `__*` fields that we add to the json for our consumption, before sending them out from the proxy. The tests shouldn't depend on any of those.

**Comment by ilonatommy** [comment]
> @ilonatommy just curious, is VS using the `privateProperties` part?

It is using it in the meaning: they are displayed. However, the difference between them and `result` is not stressed in VS - in Browser it is. To visualise, here are two screenshots from the same class in VS and Browser:
image

image

**Comment by ilonatommy** [comment]
> Also, it would be a good idea to remove all the `__*` fields that we add to the json for our consumption, before sending them out from the proxy. The tests shouldn't depend on any of those.

I agree and Thays already mentioned this idea as well. The PR with it will be out soon.

**Pull request merged**
