### PR TITLE
Remove ActiveIssue tag in ThreadPoolBoundHandle_IntegrationTests.netcoreapp.cs

### PR DESCRIPTION
**Pull request by eduardo-vp**

### CODE REVIEW

**Comment by danmoseley** [comment]
@eduardo-vp if you put `Fixes #49700` on its own line in the top description here then when you merge, Github will close the issue.

**Comment by eduardo-vp** [comment]
@mangod9 as the tag was removed and all tests passed, is it safe to assume that the previous failure doesn't reproduce anymore? I guess there may be a chance that it fails with certain probability but I'm not sure

**Comment by stephentoub** [comment]
> is it safe to assume that the previous failure doesn't reproduce anymore?

The associated issue indicates the failures were sporadic / non-deterministic, so a successful CI doesn't necessarily mean the issue no longer repros.

**Comment by mangod9** [comment]
would be good to get this  merged so it can run regularly so we can investigate failures.

**Review by mangod9 — APPROVED** [review]

**Pull request merged**
