### PR TITLE
Set GCStressIncompatible on GenericContext test

### PR DESCRIPTION
**Pull request by VSadov**
Another try at fixing https://github.com/dotnet/runtime/issues/104633

### CODE REVIEW

**Comment by VSadov** [comment]
@steveisok @jkoritzinsky  The suppression style as suggested in https://github.com/dotnet/runtime/pull/104686 may be better in the long term.  
I just want to make GC stress green first.

**Review by jkoritzinsky — APPROVED** [review]

**Comment by VSadov** [comment]
I hope this will work. The previous attempt should have worked in theory. Not sure what happened with that.

**Comment by VSadov** [comment]
Thanks!

**Pull request merged**
