### PR TITLE
[release/9.0] Upgrade vendored Brotli dependency to v1.1.0

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Backport of #106994 to 9.0.

We want to be on the most recent release of Brotli for .NET 9.

See #106887

@carlossanlop can you get M2 approval from your side?

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Review by carlossanlop — APPROVED** [review]

**Comment by carlossanlop** [comment]
@jkoritzinsky there was a patch in the main PR in a separate commit: https://github.com/dotnet/runtime/pull/106994/commits

@jkotas do we care to have the commits split in this PR like you requested in my zlib-ng update?

**Review by artl93 — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
@carlossanlop I included those changes into the initial commit in this PR.

**Comment by jkotas** [comment]
> do we care to have the commits split in this PR like you requested in my zlib-ng update?

This does not have any custom patches that have not been upstreamed, and the changes outside the vendored Brotli are very minimal. I do not have a problem with it all being in one commit.

**Comment by carlossanlop** [comment]
/ba-g Re-ran failed CI legs and they passed. Only one known/pre-existing failure showed up.

**Pull request merged**
