### PR TITLE
Have SIMDIntrinsicUpperSave and SIMDIntrinsicUpperRestore set a baseType if one can't otherwise be determined

### LINKED ISSUE #35876: Test failure: Assertion failed '!"SIMD intrinsic with unsupported base type."'
Windows x64 JitStress=1 or 2

Test:
```
JIT\SIMD\VectorRelOp_ro\VectorRelOp_ro.cmd
```

https://dev.azure.com/dnceng/public/_build/results?buildId=631203&view=ms.vss-test-web.build-test-results-tab&runId=19687756&resultId=105979&paneView=debug

`\r\nAssert failure(PID 6688 [0x00001a20], Thread: 7948 [0x1f0c]): Assertion failed '!"SIMD intrinsic with unsupported base type."' in 'VectorRelopTest`1[UInt64][System.UInt64]:VectorRelOp(long,long):int' during 'Generate code' (IL size 1179)\r\n\r\n File: F:\workspace\_work\1\s\src\coreclr\src\jit\simdcodegenxarch.cpp Line: 3201\r\n Image: C:\h\w\AB7209D8\p\CoreRun.exe\r\n\r\n\r\nReturn code: 1\r\nRaw output file: C:\h\w\AB7209D8\w\C2150A43\e\JIT\SIMD\Reports\JIT.SIMD\VectorRelOp_ro\VectorRelOp_ro.output.txt\r\nRaw output:\r\nBEGIN EXECUTION\r\n "C:\h\w\AB7209D8\p\corerun.exe" VectorRelOp_ro.dll \r\nExpected: 100\r\nActual: -1073740286\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\nTo run the test:\r\n> set CORE_ROOT=C:\h\w\AB7209D8\p\r\n> C:\h\w\AB7209D8\w\C2150A43\e\JIT\SIMD\VectorRelOp_ro\VectorRelOp_ro.cmd\r\nExpected: True\r\nActual: False`

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/35876

### CODE REVIEW

**Comment by tannergooding** [comment]
This also fixes https://github.com/dotnet/runtime/issues/35620, but I think it should probably be kept open so that a better fix can be put in place. Ideally we would always track the relevant class handle so that we don't have to lie about the type.

I mentioned a possible alternative [here](https://github.com/dotnet/runtime/issues/35876#issuecomment-624761445), but I believe they are all more involved changes.

**Comment by tannergooding** [comment]
Test failure is the other issue being fixed by https://github.com/dotnet/runtime/pull/35904

**Comment by tannergooding** [comment]
jitstress failure on OSX is also a separate issue: https://github.com/dotnet/runtime/issues/35798#issuecomment-624429646

**Review by CarolEidt — APPROVED** [review]
LGTM - thanks!
It's weird, but I actually have a recollection of fixing this before, but I'm obviously mistaken!

**Pull request merged**
