### PR TITLE
Account for AddressFamily pairs in NameResolution telemetry

### PR DESCRIPTION
**Pull request by MihaZupan**
In #56208 I changed `BeforeResolution` to take an object instead of `string`/`IPAddress`, but the value we feed it from `RunAsync` could also be `KeyValuePair<string, AddressFamily>` or `KeyValuePair<IPAddress, AddressFamily>`.

Type check for those as well (same as we do elsewhere).
https://github.com/dotnet/runtime/blob/38071bfb52b2e1f3cff1037dfa4484beacedacff/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs#L597-L600

### CODE REVIEW

**Review by karelz — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
Do we need another test?

**Comment by karelz** [comment]
BTW:
This is a 100% Debug.Assert in the product which is merged for 3.5 days:

It is super-weird that it failed on @MihaZupan PR (which introduced the problem), but all checks there were green:
  - The likely reason is that [Outerloop was kicked off](https://github.com/dotnet/runtime/pull/56208#issuecomment-885644535) on 7/23 @**15:36** GMT+2 and a [typo-fix commit](https://github.com/dotnet/runtime/pull/56208/commits/e7e9ca83ec9e7e7b649f1ee6cb7a8652d21b6977) in 45 minutes (7/236 @**16:21** GMT+2) kicked off another run which did NOT include any results from previous Outerloop run.

The other problem is that this 100% Outerloop problem was in the product unnoticed for 3 days -- the PR which introduced it was merged https://github.com/dotnet/runtime/pull/56208#event-5070219115 on 7/26 @21:03 GMT+2 ... yet we noticed it only today around 7/30 @11 GMT+2 by accident on another Networking PR which ran Outerloop.
- Querying Kusto, there is no Outerloop failure in Official run (that is **very concerning**)
- Querying Kusto is super-hard ... if we didn't what to look for, there is no chance we would have noticed from queries that something is wrong

cc @dotnet/dncenghot I will start email thread to see what we can do about these things longer-term

**Comment by MihaZupan** [comment]
> Do we need another test?

The telemetry tests do [exercise all overloads](https://github.com/dotnet/runtime/blob/3e69dc3e90a338a1ac09331c15692d2397cb0cdb/src/libraries/System.Net.NameResolution/tests/FunctionalTests/TelemetryTest.cs#L74-L81), so the assert should be hit in every outerloop run as Karel noted. It's just unfortunate it took this long to spot it.

**Comment by MihaZupan** [comment]
Outerloop tests unrelated: #56618 #54260 #55313

**Comment by mmitche** [comment]
@karelz You can see the results of the previous run (that completed) here: https://github.com/dotnet/runtime/runs/3144425881 (when you look at the checks tab it shows results from all commits in a drop-down.

What happened here was completely by design on the AzDO side. When the new commit was pushed, a couple things happen:
- The currently executing runs against the previous source commit are cancelled automatically by AzDO.
- The newly triggered runs are associated against the new commit in github.

> Querying Kusto, there is no Outerloop failure in Official run (that is very concerning)

This would almost certainly be because the outerloop runs never got far enough to actually run tests and report to Kusto before they were cancelled automatically by the host CI system. Simply put, the outerloop tests didn't run at all on this PR.

> The likely reason is that Outerloop was kicked off on 7/23 @ 15:36 GMT+2 and a typo-fix commit in 45 minutes (7/23 @ 16:21 GMT+2) kicked off another run which did NOT include any results from previous Outerloop run.

Note that even **if** the runs continued and completed, they would **not** show up in the GitHub Checks (unless you dig through the history). This is because Github checks are associated with the source sha, and the head source sha of the PR changed on the new push. The previous results are not included because they aren't the same code.

So what really needed to happen in this case would be for the outerloop run to re-launch on the new sha. Today, as far as I know, there is no way to do that in an automated fashion. Without that, the run could have been re-requested after the push.

**Pull request merged**
