### PR TITLE
Fix Scalar.Abs for TInteger.MinValue

### LINKED ISSUE #95592: Mono's Vector128 support incorrectly handles Abs for signed integer MinValue
Repro:
https://github.com/dotnet/runtime/pull/95588
```C#
        [Fact]
        public void Vector128SByteAbs_MinValue()
        {
            Vector128<sbyte> vector = Vector128.Create(sbyte.MinValue);
            Vector128<sbyte> abs = Vector128.Abs(vector);
            for (int index = 0; index < Vector128<sbyte>.Count; index++)
            {
                Assert.Equal(sbyte.MinValue, vector.GetElement(index));
            }
        }
```

This test passes on coreclr. On mono it fails with:
```
    System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128SByteAbs_MinValue [FAIL]
      System.OverflowException : Negating the minimum value of a twos complement number is invalid.
      Stack Trace:
        /_/src/libraries/System.Runtime.Intrinsics/tests/Vectors/Vector128Tests.cs(163,0): at System.Runtime.Intrinsics.Tests.Vectors.Vector128Tests.Vector128SByteAbs_MinValue()
        /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

This is the source of the test failures in https://github.com/dotnet/runtime/pull/94555#issuecomment-1811472249.

cc: @radekdoulik, @tannergooding

### PR DESCRIPTION
**Pull request by MichalPetryka**
Fixes #95592.

### CODE REVIEW

**Review by stephentoub — COMMENTED** [review]
Thanks! Could you add some tests as well?

**Comment by MichalPetryka** [comment]
> Could you add some tests as well?

Is the test you've added in the repro check PR okay here? `Scalar<T>` isn't a public API (at least yet) so I can't test it directly.

**Comment by stephentoub** [comment]
I think that or simple variations of it (i.e. testing via Vector128/256/512) would be fine.

**Review by stephentoub — APPROVED** [review]
Thanks!

**Pull request merged**
