### PR TITLE
Fix type layout with explicitly sized structs and classes

### PR DESCRIPTION
**Pull request by davidwrighton**
- Mimic the alignment and other algorithms present in coreclr
- Add tests to crossgen2smoke to cover these scenarios
- Fix issue #38450

### CODE REVIEW

**Comment by davidwrighton** [comment]
@dotnet/crossgen-contrib

**Comment by MichalStrehovsky** [comment]
Would be a good candidate for a unit test. Simon already brought the type system test infra over.

Unit tests are easier to debug than runtime memory corruptions.

**Comment by davidwrighton** [comment]
That is true. However, now that the type layout stress mode is enabled for crossgen2smoke for all runs of it, its not substantially more difficult to trigger a fault. (It doesn't repro as a memory corruption, but instead it repros as a failfast with a somewhat actionable error message.

However, I just ran the tests, and see that my change actually broke the unittests. I'll look into whether or not the unittest is correct.

**Comment by davidwrighton** [comment]
@MichalStrehovsky I'm still having difficulty debugging the unittests, but I've fixed them so that they run correctly from a copy of VS, as well as fixing the issues that popped up when run in that mode. (The ExplictLayoutSize test was wrong, and the TestMethodLookup test was not specifying the correct signature.

**Comment by MichalStrehovsky** [comment]
> The ExplictLayoutSize test was wrong

Interesting, that test is copy-pasted from NUTC (and so is the field layout algorithm bug for that matter). I guess it won't meet the bar to fix it there unless it's user reported.

> The ExplictLayoutSize test was wrong

Yeah, I was meaning to just delete it at some point. It has long history...

**Review by nattress — APPROVED** [review]

**Pull request merged**
