### PR TITLE
Partial revert of #71486 to unblock dotnet/sdk

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
https://github.com/dotnet/sdk/pull/29800#issuecomment-1387247881 has details

**Comment by jkotas** [comment]
This is partial revert of #71486. It broke dotnet/sdk.

cc @janvorli @sec

**Comment by ViktorHofer** [comment]
Thanks for the quick fix. When revisiting this, we should probably also stop setting TargetOS to`$(OS)` which in msbuild either returns Windows, OSX or Unix and isn't really helpful here. Also, TargetOS is expected to be a lowercase value.

**Comment by jkotas** [comment]
Yes, let's have discussion about this in #80794 . cc @am11 

We should take the revert first to get the dotnet/sdk unblocked with confidence. It has been stuck for 2 weeks.

**Comment by am11** [comment]
Yes, now FreeBSD is also listed: https://github.com/dotnet/runtime/blob/3763345d2b0452f75be3b90cc5ee0c0eee0cdc38/src/coreclr/tools/Common/CommandLineHelpers.cs#L59-L71 so it should work there without setting targetos=runtimeos.

> When revisiting this, we should probably also stop setting TargetOS to`$(OS)` which in msbuild either returns Windows, OSX or Unix and isn't really helpful here. Also, TargetOS is expected to be a lowercase value.

#80794 is addressing this, so we can take both. :)

**Review by LakshanF — APPROVED** [review]

**Pull request merged**
