### PR TITLE
Misc LSRA throughput improvements

### PR DESCRIPTION
**Pull request by kunalspathak**
While working on consecutive-registers, I realized few things that could help in the throughput:
~1. We pass around `RegisterType` in various methods, but that parameter is only used for `TARGET_ARM`. So wrap the parameter in `ARM_ARG.~ Done separately in https://github.com/dotnet/runtime/pull/86016.

2. We call `updateAssignedInterval()` frequently, but more than half of the time, we pass `interval == nullptr` which is essentially clearing the interval. Introduced `clearAssignedInterval()` for that purpose.

~3. Use `BitOperations::PopCount()` in a method that is used for `IsSingleRegister()` check.~ Done separately as part of https://github.com/dotnet/runtime/pull/85944.

### CODE REVIEW

**Comment by kunalspathak** [comment]
TP regressions is surprising. Probably need to compare the assembly of before vs. after to see which individual change might be causing it.

**Comment by kunalspathak** [comment]
> TP regressions is surprising. Probably need to compare the assembly of before vs. after to see which individual change might be causing it.

```
Base: 538795279, Diff: 549102807, +1.9131%

?newRefPosition@LinearScan@@AEAAPEAVRefPosition@@PEAVInterval@@IW4RefType@@PEAUGenTree@@_KI@Z : 3693050  : +30.40%  : 22.83% : +0.6854%
?associateRefPosWithInterval@LinearScan@@AEAAXPEAVRefPosition@@@Z                             : 3035189  : +29.77%  : 18.76% : +0.5633%
?updateAssignedInterval@LinearScan@@AEAAXPEAVRegRecord@@PEAVInterval@@@Z                      : 2998888  : NA       : 18.54% : +0.5566%
?applySelection@RegisterSelection@LinearScan@@AEAA_NH_K@Z                                     : 2059105  : NA       : 12.73% : +0.3822%
??$select@$0A@@RegisterSelection@LinearScan@@QEAA_KPEAVInterval@@PEAVRefPosition@@@Z          : 1195021  : +4.50%   : 7.39%  : +0.2218%
?addRefsForPhysRegMask@LinearScan@@AEAAX_KIW4RefType@@_N@Z                                    : 230276   : +3.90%   : 1.42%  : +0.0427%
?buildInternalRegisterUses@LinearScan@@AEAAXXZ                                                : 28726    : +8.16%   : 0.18%  : +0.0053%
?updateAssignedInterval@LinearScan@@AEAAXPEAVRegRecord@@PEAVInterval@@W4var_types@@@Z         : -2913849 : -100.00% : 18.01% : -0.5408%
```

I didn't realize that we do not use intrinsics for popcount and which is why we are seeing lot of regressions. This is yet another example of why cross compilation comparison for TP might not be always accurate. cc: @jakobbotsch @BruceForstall 

https://github.com/dotnet/runtime/blob/8854509eac45da4fe3f7843599133aa2a6d1beaf/src/coreclr/jit/utils.cpp#L2788-L2808

### newRefposition:

image


### buildInternalregisterusage

image

I will revert the popcount change.

**Comment by BruceForstall** [comment]
> I didn't realize that we do not use intrinsics for popcount

Would be worthwhile profiling current function versus popcount -- probably we should switch to popcount.

**Comment by jakobbotsch** [comment]
> I didn't realize that we do not use intrinsics for popcount and which is why we are seeing lot of regressions. This is yet another example of why cross compilation comparison for TP might not be always accurate. cc: @jakobbotsch @BruceForstall

It's a good point, but also a place where we should actively ensure we have parity regardless of the compiler we are using. It seems unfortunate that we are regressing either MSVC produced code or Clang produced code.

**Comment by kunalspathak** [comment]
image

Looking at the diffs for minopts benchmarks_run windows-x64 I see slight regression:

```
Base: 538795279, Diff: 538880143, +0.0158%

?updateAssignedInterval@LinearScan@@AEAAXPEAVRegRecord@@PEAVInterval@@@Z              : 2998888  : NA       : 50.71% : +0.5566%
?updateAssignedInterval@LinearScan@@AEAAXPEAVRegRecord@@PEAVInterval@@W4var_types@@@Z : -2913849 : -100.00% : 49.27% : -0.5408%
```

But looking at the code, we should still profitable, because we are eliminating a condition:

image

**Comment by kunalspathak** [comment]
> Would be worthwhile profiling current function versus popcount -- probably we should switch to popcount.

Fixed.

**Comment by tannergooding** [comment]
> It's a good point, but also a place where we should actively ensure we have parity regardless of the compiler we are using. It seems unfortunate that we are regressing either MSVC produced code or Clang produced code.

GCC/Clang generate the exact code that was codified for MSVC, they just do it implicitly.

This was likely one of the many cases where we "execute more instructions" but the code was actually faster in practice.

**Comment by kunalspathak** [comment]
>  if the ISA switch is passed in

you mean when building clrjit using clang, right? 

> This was likely one of the many cases where we "execute more instructions" but the code was actually faster in practice.

Agree. btw, I do see that with VC++ `popcnt` removes lot of that code and generate the actual intrinsic which will be faster too. I will send a separate PR to see the effect of that alone rather than mixing up with some of the LSRA improvements I am doing here.

**Comment by jakobbotsch** [comment]
> This was likely one of the many cases where we "execute more instructions" but the code was actually faster in practice.

I'm confused, are you saying the MSVC multiplication code was faster than using a single `popcnt` instruction?

**Comment by kunalspathak** [comment]
> GCC/Clang generate the exact code that was codified for MSVC

hhm. https://godbolt.org/z/rEndsvhv6

**Comment by tannergooding** [comment]
> I'm confused, are you saying the MSVC multiplication code was faster than using a single popcnt instruction?

@jakobbotsch: No, rather `GCC/Clang` don't emit `popcnt` here because our target machine is `-msse2`. In order for `GCC/Clang` to emit `popcnt` the target machine must be at least `-msse42`. For pre `sse4.2`, they emit the same logic as the multiplication code.

In order for us to emit `popcnt` here, we'd need to do it "opportunistically" via a cached CPUID check (much as we do for atomic operations on Arm64):
```
if (supportsPopcnt)
{
    return __popcnt(value);
}
else
{
    // Bit twiddling logic
}
```

**Comment by kunalspathak** [comment]
[Latest diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=268144&view=ms.vss-build-web.run-extensions-tab)

image

**Comment by BruceForstall** [comment]
Odd it shows x64 as a slight regression.

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
