### PR TITLE
[wasm] browser profiler (again)

### PR DESCRIPTION
**Pull request by pavelsavara**
This is second attempt to merge https://github.com/dotnet/runtime/pull/77449 which was reverted.
On top of previous change I also fix for the different signature on `performance.measure` API on the V8 and NodeJS shell.

I tested with v8 10.9.130 and V8 10.7.193 and NodeJS v16.13.1.

### CODE REVIEW

**Review by vargaz — APPROVED** [review]

**Comment by radical** [comment]
[wbt failure](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-77779-merge-41b0cc1053274d8f9d/Workloads-Wasm.Build.Tests.ConfigSrcTests/1/console.0c2964f4.log?helixlogtype=result): `test-main failed early 1 ReferenceError: performance is not defined`

**Comment by pavelsavara** [comment]
Failures are unrelated.

**Pull request merged**
