### PR TITLE
[release/7.0] Bump branding to RC2

### PR DESCRIPTION
**Pull request by carlossanlop**

### CODE REVIEW

**Comment by danmoseley** [comment]
There's lots of `rc.1` in eng\Versions.props and eng\Version.Details.xml .. do those just clean themselves up through codeflow?

**Review by hoyosjs — APPROVED** [review]

**Review by smasher164 — APPROVED** [review]

**Comment by hoyosjs** [comment]
@danmoseley some of them will, some of the ones that have RC1 come from runtime and we'll need to update manually (e.g System.Text.Json) once we have rc2 bits after this goes in.

**Review by ViktorHofer — APPROVED** [review]

**Comment by hoyosjs** [comment]
No, I checked and we didn't

**Comment by carlossanlop** [comment]
> @danmoseley some of them will, some of the ones that have RC1 come from runtime and we'll need to update manually (e.g System.Text.Json) once we have rc2 bits after this goes in.

Just to make sure I understand this: There's nothing else to do in this PR?

**Comment by hoyosjs** [comment]
Not that i can think of

**Pull request merged**
