### PR TITLE
Move System.Globalization.Native under libraries

### PR DESCRIPTION
**Pull request by jkotas**
Fixes https://github.com/dotnet/coreclr/issues/22391

### CODE REVIEW

**Comment by jkotas** [comment]
cc @filipnavara

**Review by safern — APPROVED** [review]

**Comment by am11** [comment]
@jkotas, thanks for this. two questions related to current structure:

* can `src/coreclr/src/coreclr/hosts` be reduced to `src/coreclr/src/hosts`?
* what is the purpose of `src/coreclr/inc/clr_std/*`; can it be replaced by real C++11 std?

i can follow up on these (especially the second one which i am handling via memset fixes). :)

**Comment by jkotas** [comment]
> can src/coreclr/src/coreclr/hosts be reduced to src/coreclr/src/hosts

I think so. It looks like a cosmetic change only, no change in how things are actually built.

> what is the purpose of src/coreclr/inc/clr_std/*; can it be replaced by real C++11 std?

The real C++ 11 std is not compatible with PAL headers. We would need to eliminate all definitions in PAL that conflict with std system headers first (ie make the PAL purely additive). Once that happens, this `clr_std` can go away.

**Comment by am11** [comment]
Thanks! Yup, bringing `hosts` directory to one level above was just a structural change i was thinking to remove this one-of-a-kind directory (this PR removed the other one: `src/coreclr/src/corefx`).

I will try to figure out smooth way to remove stuff from under `#ifndef PAL_STDCPP_COMPAT`s, and include std headers at usage sites.

**Pull request merged**
