### PR TITLE
Fix numbering of exposed `LCL_VAR`s

### PR DESCRIPTION
**Pull request by SingleAccretion**
The conservative VN must be unique for different uses lest we risk running into memory safety issues, by, e. g., removing range checks based on "racy" data.

It is very easy to reproduce bad codegen with this simple method and `JitNoCSE=1`:
```cs
[MethodImpl(MethodImplOptions.NoInlining)]
private static int Problem(int[] a, int b)
{
    JitUse(&b);
    return a[b] + a[b];
}
```
Assertion propagation removes the second check, which is not legal as `b`'s value may change once we get to it from the first check.

Diffs will be regressions; I see in some cases we did illegal bounds checks removal.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Review by jakobbotsch — APPROVED** [review]

**Comment by jakobbotsch** [comment]
Looks like the new test needs to be disabled on wasm.

**Comment by SingleAccretion** [comment]
Looks like the test is failing on x64 under the interpreter as well. Will disable it there and create an issue once the FullAot tests are done.

**Comment by jakobbotsch** [comment]
Thanks! Let's see if this shows up in perf triage...

**Comment by AndyAyersMS** [comment]
FYI, I am seeing this new test crash on arm64 under PGO stress as part of #80481 -- suspect it's not related to that PR but haven't drilled in yet.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=133883&view=ms.vss-test-web.build-test-results-tab

**Comment by SingleAccretion** [comment]
Yes, in all likelihood not related. We've now seen it fail (not crash though) on x86 too. I will put up a change to disable the test for now.

**Pull request merged**
