### PR TITLE
Faster unsigned division by constants

### PR DESCRIPTION
**Pull request by pentp**
This is #49585 rebased and updated to use the new `inst_Mov` method instead of `inst_RV_RV(INS_mov)`.
/cc @tannergooding @EgorBo

### CODE REVIEW

**Comment by pentp** [comment]
This is ready for merging. It's the same PR with just a fix for one new assert.

**Review by tannergooding — APPROVED** [review]

**Comment by tannergooding** [comment]
Thank's for resolving the issue so quickly.

**Comment by kunalspathak** [comment]
@pentp  - Do you know why we choose to do `GT_CAST` and not `GT_BITCAST` for armarch?

https://github.com/dotnet/runtime/pull/52893/files#diff-8b369256957ebd643910d92e3975f4c94b350010802b23e558ca965680f4907aR5311-R5314

**Comment by danmoseley** [comment]
Happened to notice question for @pentp above.

**Comment by danmoseley** [comment]
linking https://github.com/dotnet/runtime/issues/54166

**Pull request merged**
