### PR TITLE
[wasm] Tracking aot failures, not meant to be merged

### PR DESCRIPTION
**Pull request by radical**
- this re-enables any tests that were disabled due to aot only failures
- This will never be merged
- It's only to track aot test failures
- `main` will be merged here regularly

### CODE REVIEW

**Comment by radical** [comment]
cc @lewing @steveisok @vargaz @fanyang-mono @naricc @SamMonoRT @akoeplinger

**Comment by radical** [comment]
We should disable all the non-wasm builds here.

**Comment by fanyang-mono** [comment]
> We should disable all the non-wasm builds here.

We should only run wasm aot lane here to save the resources.

**Comment by radical** [comment]
https://github.com/dotnet/runtime/pull/52265 will fix the EAT error

**Comment by lewing** [comment]
@radical it looks like several of the EAT lans have a 0 exit code but no failures?

**Comment by radical** [comment]
> @radical it looks like several of the EAT lans have a 0 exit code but no failures?

which ones? I didn't see any in EAT, or AOT.

**Comment by lewing** [comment]
Sorry, I meant in the data explorer reports

**Pull request closed without merging**
