### PR TITLE
Fix spilling of `MUL_LONG` on x86 and multi-reg HWIs

### LINKED ISSUE #73070: Spilling does not work for some multi-reg nodes
Reproduction:
```cs
[MethodImpl(MethodImplOptions.NoInlining)]
private static long Problem(int a, int b)
{
    return (long)a * (long)b;
}
```
Compile with a Jit targeting x86 and:
```sh
JitStressRegs=0x800
JitStressRegsRange=a681b74e-a681b74e # Hash of "Problem"
```
Apply this patch for `JitDump` to work (if needed):
```diff
--- a/src/coreclr/jit/lsra.cpp
+++ b/src/coreclr/jit/lsra.cpp
@@ -4661,7 +4661,11 @@ void LinearScan::allocateRegisters()
         {
             assert(lastAllocatedRefPosition->registerAssignment != RBM_NONE);
             RegRecord* regRecord = lastAllocatedRefPosition->getInterval()->assignedReg;
+
+            INDEBUG(activeRefPosition = lastAllocatedRefPosition);
             unassignPhysReg(regRecord, lastAllocatedRefPosition);
+            INDEBUG(activeRefPosition = nullptr);
+
             // Now set lastAllocatedRefPosition to null, so that we don't try to spill it again
             lastAllocatedRefPosition = nullptr;
```
Expected result: things compile fine.

Actual result: asserts.

Cause: multiple spilling routines, e. g. `rsSpillTree`, don't treat `MUL_LONG` as the multi-reg node it is on x86.

Additionally, spilling for multi-reg HWIs appears to not be implemented at all - the HWI node does not have the multi-reg spill flags.

### PR DESCRIPTION
**Pull request by SingleAccretion**
Fixes #73070.

Tests not added because the stress mode which makes this apparent is not really in a working shape.

No diffs.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/jit-contrib

**Comment by JulieLeeMSFT** [comment]
I set the milestone to .NET 8 because the linked issue is for 8.0.0. 
FYI, we will focus on bug fixes for the next 2 weeks because RC1 snap is 8/12.

**Comment by kunalspathak** [comment]
I will review this week.

**Comment by kunalspathak** [comment]
> No diffs.

Ah, noticed this now.

**Comment by kunalspathak** [comment]
> Tests not added because the stress mode which makes this apparent is not really in a working shape.

What do you mean?

**Comment by SingleAccretion** [comment]
> What do you mean?

The way to expose these bugs is to run something with the nodes in question under `JitStressRegs=0x800`, aka the "always spill" mode. However, it is very unstable and crashes even on very simple methods, as our documentation [hints at](https://github.com/dotnet/runtime/blob/main/docs/design/coreclr/jit/lsra-detail.md#lsra-stress-modes).

It's very very hard to expose this otherwise. It would be nice to fix the "always spill" mode, but I don't quite have the LSRA expertise necessary for that.

**Comment by kunalspathak** [comment]
> It would be nice to fix the "always spill" mode, but I don't quite have the LSRA expertise necessary for that.

Ok, I didn't pay attention to `0x800`. Yes, we need to address it someday, I need to understand what the problems are currently.

**Review by kunalspathak — APPROVED** [review]
LGTM. Nice cleanup.

**Pull request merged**
