### PR TITLE
#37093 disable Reciprocal test only for Android x86

### PR DESCRIPTION
**Pull request by mkhamoyan**
Disable Reciprocal test only for Android x86 #37093

### CODE REVIEW

**Review by steveisok — APPROVED** [review]

**Comment by mkhamoyan** [comment]
> Do we know why Android has so many differences here?
> 
> I don't believe we're seeing the same on x86, x64, Arm32, Arm64, s390X, PPC, or iOS.

In Android x86 operations for double don't work as expected. For now we are disabling these test only for x86 android until we will fix the issue.

**Comment by mkhamoyan** [comment]
> Do we know why Android x86 behaves differently for doubles?
> 
> Is it perhaps using the legacy x87 FPU still and is misconfigured to 80-bit rounding rather than 64-bit rounding?
> 
> I had thought a PR existed to ensure Mono always uses SSE/SSE2 on x86, since it's a 20+ year old hardware baseline at this point (and required for all x64 chips) but perhaps that hasn't been merged yet or was missed for Android?

@steveisok maybe you know about that PR ?

**Comment by tannergooding** [comment]
Looks to have not been merged yet: https://github.com/dotnet/runtime/pull/65723

This might be part of the Android x86 issue, although I'd guess there is another part at play (perhaps fpu configuration) since regular x86 isn't seeing the same.

**Pull request merged**
