### PR TITLE
Change hosted pool

### PR DESCRIPTION
**Pull request by ulisesh**
We have a new set of AzDo pools where we eventually will move all servicing work, this PR tests Build.Ubuntu.1804.Amd64.Open

### CODE REVIEW

**Review by ViktorHofer — COMMENTED** [review]
As you are mentioning "testing" in the PR description, do you want this to get merged or is the PR just testing the pools?

**Comment by ulisesh** [comment]
> As you are mentioning "testing" in the PR description, do you want this to get merged or is the PR just testing the pools?

I want to merge it :)

**Review by MattGal — APPROVED** [review]
looks valid, I'd merge if it passes your builds. (Edit; it did and the only test failures are that xunit thing and system.drawing on Arm64 which is very unlikely to be related)

**Comment by ViktorHofer** [comment]
Issues are:
- https://github.com/dotnet/runtime/issues/11063
- https://github.com/dotnet/runtime/issues/51097

**Comment by ulisesh** [comment]
This pools are specific for Servicing work in release branches

**Comment by ulisesh** [comment]
@ViktorHofer can you please help us merge this PR too? It is the same change we did in #58484

**Comment by ViktorHofer** [comment]
I don't manage the servicing branches. Ping @Anipik for my question above.

**Comment by Anipik** [comment]
The branch is currently closed.  i will merge this one when the branch will open for the next servicing release

**Comment by ericstj** [comment]
@Anipik is this ready to go yet?

**Review by safern — APPROVED** [review]

**Review by MattGal — APPROVED** [review]

**Pull request merged**
