### PR TITLE
Ensure loop hoisting recognizes and tracks mask types

### LINKED ISSUE #97345: JIT: Assert `varTypeUsesFloatReg(tree)` blocking libraries-jitstress
[runtime-coreclr libraries-jitstress](https://dev.azure.com/dnceng-public/public/_build?definitionId=138&_a=summary) is blocked on multiple platforms by the following assert:

```
Assert failure(PID 73722 [0x00011ffa], Thread: 73738 [0x1200a]): Assertion failed 'varTypeUsesFloatReg(tree)' in 'System.Numerics.Tensors.TensorPrimitives:<InvokeSpanScalarIntoSpan>g__Vectorized256|223_2[ulong,System.Numerics.Tensors.TensorPrimitives+IdentityOperator`1[ulong],System.Numerics.Tensors.TensorPrimitives+MinMagnitudePropagateNaNOperator`1[ulong]](byref,ulong,byref,ulong)' during 'Hoist loop code' (IL size 2145; hash 0x61d9c93c; FullOpts)

    File: /__w/1/s/src/coreclr/jit/optimizer.cpp Line: 4167
    Image: /datadisks/disk1/work/B0A70986/p/dotnet
```

[Failure log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-97184-merge-cd16be0e43514d5899/System.Numerics.Tensors.Net8.Tests/1/console.5da3f8ad.log?helixlogtype=result) from a recent run on Windows x64. cc @dotnet/jit-contrib

### PR DESCRIPTION
**Pull request by tannergooding**
This resolves https://github.com/dotnet/runtime/issues/97345

### CODE REVIEW

**Comment by tannergooding** [comment]
(This is going to need to run the stress tests, but I want to ensure no missed formatting or other failures before they get started).

**Review by jakobbotsch — APPROVED** [review]
LGTM. Do you have the jitdump of the case? I'd be curious to see if CSE actually picks up the `TYP_MASK` tree and creates a `TYP_MASK` local.

**Comment by tannergooding** [comment]
> I'd be curious to see if CSE actually picks up the TYP_MASK tree and creates a TYP_MASK local.

Not of this one in particular, but I'm pretty sure it does in other cases. For example:
```csharp
public static Vector512<float> M(Vector512<float> x, Vector512<float> y, Vector512<float> z)
{
    var tmp = Avx512F.BlendVariable(x, y, Avx512F.CompareEqual(y, z));
    return Avx512F.BlendVariable(tmp, z, Avx512F.CompareEqual(y, z));
}
```

generates:
```asm
; Method Program:M(System.Runtime.Intrinsics.Vector512`1[float],System.Runtime.Intrinsics.Vector512`1[float],System.Runtime.Intrinsics.Vector512`1[float]):System.Runtime.Intrinsics.Vector512`1[float] (FullOpts)
G_M000_IG01:                ;; offset=0x0000
       push     rax
       vzeroupper 

G_M000_IG02:                ;; offset=0x0004
       vmovups  zmm0, zmmword ptr [rdx]
       vmovups  zmm1, zmmword ptr [r8]
       vmovups  zmm2, zmmword ptr [r9]
       vcmpps   k1, zmm1, zmm2, 0
       kmovq    qword ptr [rsp], k1
       vblendmps zmm0 {k1}, zmm0, zmm1
       kmovq    k1, qword ptr [rsp]
       vblendmps zmm0 {k1}, zmm0, zmm2
       vmovups  zmmword ptr [rcx], zmm0
       mov      rax, rcx

G_M000_IG03:                ;; offset=0x003E
       vzeroupper 
       add      rsp, 8
       ret      
; Total bytes of code: 70
```

which reuses the `k1` produced by `vcmpps` (it forces a spill, which ideally it wouldn't be doing, but I haven't looked into why it does that bit).

**Comment by AndyAyersMS** [comment]
> LGTM. Do you have the jitdump of the case? I'd be curious to see if CSE actually picks up the `TYP_MASK` tree and creates a `TYP_MASK` local.

I have the same concern. There is no tracking of whether a `GTF_MAKE_CSE` actually turns into a CSE, and I know of many cases where it doesn't: https://github.com/dotnet/runtime/issues/92170.

CSE code tends to whitelist what sorts of trees it can handle, see eg `CSE_HeuristicCommon::CanConsiderTree`. So we should make sure the mask subtrees are not just rejected out of hand.

Also this new category of things may need new heuristics, but I would not worry about that now.

**Comment by tannergooding** [comment]
For the simple example, you can see it choose to CSE here:
```
************ Trees at start of optValnumCSE_Heuristic()

------------ BB01 [0000] [000..01C) (return), preds={} succs={}

***** BB01 [0000]
STMT00000 ( 0x000[E-] ... 0x01B )
N020 ( 29, 21)              [000016] -A-XG---R--                         *  STOREIND  simd64 (copy) $182
N019 (  1,  1)              [000015] -----------                         +--*  LCL_VAR   byref  V00 RetBuf       u:1 $80
N018 ( 25, 18)              [000014] ----G------                         \--*  HWINTRINSIC simd64 float BlendVariableMask <l:$202, c:$203>
N010 ( 14, 10)              [000007] ----G------                            +--*  HWINTRINSIC simd64 float BlendVariableMask <l:$200, c:$201>
N002 (  3,  2)              [000019] n---G------                            |  +--*  IND       simd64 <l:$100, c:$140>
N001 (  1,  1)              [000000] -----------                            |  |  \--*  LCL_VAR   byref  V01 arg0         u:1 (last use) $81
N004 (  3,  2) CSE #01 (def)[000020] n---G------                            |  +--*  IND       simd64 <l:$101, c:$141>
N003 (  1,  1)              [000001] -----------                            |  |  \--*  LCL_VAR   byref  V02 arg1         u:1 $82
N009 (  7,  5) CSE #03 (def)[000004] ----G------                            |  \--*  HWINTRINSIC mask   float CompareEqualMask <l:$1c0, c:$1c1>
N006 (  3,  2) CSE #01 (use)[000021] n---G------                            |     +--*  IND       simd64 <l:$101, c:$142>
N005 (  1,  1)              [000002] -----------                            |     |  \--*  LCL_VAR   byref  V02 arg1         u:1 $82
N008 (  3,  2) CSE #02 (def)[000022] n---G------                            |     \--*  IND       simd64 <l:$102, c:$143>
N007 (  1,  1)              [000003] -----------                            |        \--*  LCL_VAR   byref  V03 arg2         u:1 $83
N012 (  3,  2) CSE #02 (use)[000023] n---G------                            +--*  IND       simd64 <l:$102, c:$144>
N011 (  1,  1)              [000008] -----------                            |  \--*  LCL_VAR   byref  V03 arg2         u:1 $83
N017 (  7,  5) CSE #03 (use)[000011] ----G------                            \--*  HWINTRINSIC mask   float CompareEqualMask <l:$1c0, c:$1c2>
N014 (  3,  2) CSE #01 (use)[000024] n---G------                               +--*  IND       simd64 <l:$101, c:$145>
N013 (  1,  1)              [000009] -----------                               |  \--*  LCL_VAR   byref  V02 arg1         u:1 (last use) $82
N016 (  3,  2) CSE #02 (use)[000025] n---G------                               \--*  IND       simd64 <l:$102, c:$146>
N015 (  1,  1)              [000010] -----------                                  \--*  LCL_VAR   byref  V03 arg2         u:1 (last use) $83

***** BB01 [0000]
STMT00001 ( ??? ... ??? )
N002 (  2,  2)              [000018] -----------                         *  RETURN    byref  $VN.Void
N001 (  1,  1)              [000017] -----------                         \--*  LCL_VAR   byref  V00 RetBuf       u:1 (last use) $80

-------------------------------------------------------------------------------------------------------------------


Aggressive CSE Promotion cutoff is 200.000000
Moderate CSE Promotion cutoff is 100.000000
enregCount is 4
Framesize estimate is 0x0000
We have a small frame

Sorted CSE candidates:
CSE #03, {$1c0, $2  } useCnt=1: [def=100.000000, use=100.000000, cost=  7      ]
        :: N009 (  7,  5) CSE #03 (def)[000004] ----G------                         *  HWINTRINSIC mask   float CompareEqualMask <l:$1c0, c:$1c1>
CSE #01, {$101, $2  } useCnt=2: [def=100.000000, use=200.000000, cost=  3      ]
        :: N004 (  3,  2) CSE #01 (def)[000020] n---G------                         *  IND       simd64 <l:$101, c:$141>
CSE #02, {$102, $2  } useCnt=2: [def=100.000000, use=200.000000, cost=  3      ]
        :: N008 (  3,  2) CSE #02 (def)[000022] n---G------                         *  IND       simd64 <l:$102, c:$143>


Considering CSE #03 {$1c0, $2  } [def=100.000000, use=100.000000, cost=  7      ]
CSE Expression : 
N009 (  7,  5) CSE #03 (def)[000004] ----G------                         *  HWINTRINSIC mask   float CompareEqualMask <l:$1c0, c:$1c1>
N006 (  3,  2) CSE #01 (use)[000021] n---G------                         +--*  IND       simd64 <l:$101, c:$142>
N005 (  1,  1)              [000002] -----------                         |  \--*  LCL_VAR   byref  V02 arg1         u:1 $82
N008 (  3,  2) CSE #02 (def)[000022] n---G------                         \--*  IND       simd64 <l:$102, c:$143>
N007 (  1,  1)              [000003] -----------                            \--*  LCL_VAR   byref  V03 arg2         u:1 $83

Aggressive CSE Promotion (300.000000 >= 200.000000)
cseRefCnt=300.000000, aggressiveRefCnt=200.000000, moderateRefCnt=100.000000
defCnt=100.000000, useCnt=100.000000, cost=7, size=5
def_cost=1, use_cost=1, extra_no_cost=8, extra_yes_cost=0
CSE cost savings check (708.000000 >= 200.000000) passes

Promoting CSE:

lvaGrabTemp returning 5 (V05 rat0) (a long lifetime temp) called for CSE - aggressive.
CSE #03 is single-def, so associated CSE temp V05 will be in SSA
New refCnts for V05: refCnt =  2, refCntWtd = 2
New refCnts for V05: refCnt =  3, refCntWtd = 3

CSE #03 def at [000004] replaced in BB01 with def of V05
optValnumCSE morphed tree:
N023 ( 30, 22)              [000016] -A-XG---R--                         *  STOREIND  simd64 (copy) $182
N022 (  1,  1)              [000015] -----------                         +--*  LCL_VAR   byref  V00 RetBuf       u:1 $80
N021 ( 26, 19)              [000014] -A--G------                         \--*  HWINTRINSIC simd64 float BlendVariableMask <l:$202, c:$203>
N013 ( 15, 11)              [000007] -A--G------                            +--*  HWINTRINSIC simd64 float BlendVariableMask <l:$200, c:$201>
N002 (  3,  2)              [000019] n---G------                            |  +--*  IND       simd64 <l:$100, c:$140>
N001 (  1,  1)              [000000] -----------                            |  |  \--*  LCL_VAR   byref  V01 arg0         u:1 (last use) $81
N004 (  3,  2) CSE #01 (def)[000020] n---G------                            |  +--*  IND       simd64 <l:$101, c:$141>
N003 (  1,  1)              [000001] -----------                            |  |  \--*  LCL_VAR   byref  V02 arg1         u:1 $82
N012 (  8,  6)              [000028] -A--G------                            |  \--*  COMMA     mask   <l:$1c0, c:$1c1>
N010 (  7,  5) CSE #03 (def)[000026] DA--G------                            |     +--*  STORE_LCL_VAR mask   V05 cse0         d:1 $VN.Void
N009 (  7,  5)              [000004] ----G------                            |     |  \--*  HWINTRINSIC mask   float CompareEqualMask <l:$1c0, c:$1c1>
N006 (  3,  2) CSE #01 (use)[000021] n---G------                            |     |     +--*  IND       simd64 <l:$101, c:$142>
N005 (  1,  1)              [000002] -----------                            |     |     |  \--*  LCL_VAR   byref  V02 arg1         u:1 $82
N008 (  3,  2) CSE #02 (def)[000022] n---G------                            |     |     \--*  IND       simd64 <l:$102, c:$143>
N007 (  1,  1)              [000003] -----------                            |     |        \--*  LCL_VAR   byref  V03 arg2         u:1 $83
N011 (  1,  1)              [000027] -----------                            |     \--*  LCL_VAR   mask   V05 cse0         u:1 <l:$1c0, c:$1c1>
N015 (  3,  2) CSE #02 (use)[000023] n---G------                            +--*  IND       simd64 <l:$102, c:$144>
N014 (  1,  1)              [000008] -----------                            |  \--*  LCL_VAR   byref  V03 arg2         u:1 $83
N020 (  7,  5) CSE #03 (use)[000011] ----G------                            \--*  HWINTRINSIC mask   float CompareEqualMask <l:$1c0, c:$1c2>
N017 (  3,  2) CSE #01 (use)[000024] n---G------                               +--*  IND       simd64 <l:$101, c:$145>
N016 (  1,  1)              [000009] -----------                               |  \--*  LCL_VAR   byref  V02 arg1         u:1 (last use) $82
N019 (  3,  2) CSE #02 (use)[000025] n---G------                               \--*  IND       simd64 <l:$102, c:$146>
N018 (  1,  1)              [000010] -----------                                  \--*  LCL_VAR   byref  V03 arg2         u:1 (last use) $83


Working on the replacement of the CSE #03 use at [000011] in BB01
Unmark CSE use #01 at [000024]:   2 ->   1
Unmark CSE use #02 at [000025]:   2 ->   1
optValnumCSE morphed tree:
N019 ( 24, 18)              [000016] -A-XG---R--                         *  STOREIND  simd64 (copy) $182
N018 (  1,  1)              [000015] -----------                         +--*  LCL_VAR   byref  V00 RetBuf       u:1 $80
N017 ( 20, 15)              [000014] -A--G------                         \--*  HWINTRINSIC simd64 float BlendVariableMask <l:$202, c:$203>
N013 ( 15, 11)              [000007] -A--G------                            +--*  HWINTRINSIC simd64 float BlendVariableMask <l:$200, c:$201>
N002 (  3,  2)              [000019] n---G------                            |  +--*  IND       simd64 <l:$100, c:$140>
N001 (  1,  1)              [000000] -----------                            |  |  \--*  LCL_VAR   byref  V01 arg0         u:1 (last use) $81
N004 (  3,  2) CSE #01 (def)[000020] n---G------                            |  +--*  IND       simd64 <l:$101, c:$141>
N003 (  1,  1)              [000001] -----------                            |  |  \--*  LCL_VAR   byref  V02 arg1         u:1 $82
N012 (  8,  6)              [000028] -A--G------                            |  \--*  COMMA     mask   <l:$1c0, c:$1c1>
N010 (  7,  5) CSE #03 (def)[000026] DA--G------                            |     +--*  STORE_LCL_VAR mask   V05 cse0         d:1 $VN.Void
N009 (  7,  5)              [000004] ----G------                            |     |  \--*  HWINTRINSIC mask   float CompareEqualMask <l:$1c0, c:$1c1>
N006 (  3,  2) CSE #01 (use)[000021] n---G------                            |     |     +--*  IND       simd64 <l:$101, c:$142>
N005 (  1,  1)              [000002] -----------                            |     |     |  \--*  LCL_VAR   byref  V02 arg1         u:1 $82
N008 (  3,  2) CSE #02 (def)[000022] n---G------                            |     |     \--*  IND       simd64 <l:$102, c:$143>
N007 (  1,  1)              [000003] -----------                            |     |        \--*  LCL_VAR   byref  V03 arg2         u:1 $83
N011 (  1,  1)              [000027] -----------                            |     \--*  LCL_VAR   mask   V05 cse0         u:1 <l:$1c0, c:$1c1>
N015 (  3,  2) CSE #02 (use)[000023] n---G------                            +--*  IND       simd64 <l:$102, c:$144>
N014 (  1,  1)              [000008] -----------                            |  \--*  LCL_VAR   byref  V03 arg2         u:1 $83
N016 (  1,  1)              [000029] -----------                            \--*  LCL_VAR   mask   V05 cse0         u:1 <l:$1c0, c:$1c1>
```

**Comment by tannergooding** [comment]
@jakobbotsch, anything else needed here or can this be merged?

**Comment by jakobbotsch** [comment]
> @jakobbotsch, anything else needed here or can this be merged?

I don't think so, this looks good to me (already approved it).

**Comment by tannergooding** [comment]
Thanks, just wanted to make sure I had addressed the comment/concern around whether this was actually getting CSE'd!

**Comment by jakobbotsch** [comment]
Ah right, thanks for showing the examples above.

**Comment by tannergooding** [comment]
I got a fix up for the K1 spilling that was happening here as well: https://github.com/dotnet/runtime/pull/97422

We just weren't setting lvTracked or handling TYP_MASK in a couple places and so hit the fallback path instead

**Pull request merged**
