### PR TITLE
Check for newlines in email address.

### PR DESCRIPTION
**Pull request by rzikm**
This adds validation for embedded newlines in email addresses.
There is opt-in System.Net.Mail.EnableFullDomainLiterals switch to allow previous behavior.

### CODE REVIEW

**Review by MihaZupan — APPROVED** [review]

**Comment by MihaZupan** [comment]
Do we want to keep the switches around at all given this is vNext?
I doubt there's real scenarios for it.

**Comment by rzikm** [comment]
cc @wfurt

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by wfurt** [comment]
> Do we want to keep the switches around at all given this is vNext?
> I doubt there's real scenarios for it.

I think we can go either way. I somewhat agree that valid scenario with CRLF is unrealistic but I don't mind the comp switch either.

**Pull request merged**
