### PR TITLE
Disable failing MsQuic tests on Windows

### PR DESCRIPTION
**Pull request by rzikm**
Contributes to #69792.

This PR disables newly failing tests. The failures seem to be confined to Windows 2022 Server.

### CODE REVIEW

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by wfurt** [comment]
btw there are still Quic failures but it seems unrelated to this change.


```
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.MsQuicTests.ConnectWithClientCertificate', Elapsed: 00:14:07
['System.Net.Quic.Functional.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

**Comment by rzikm** [comment]
> btw there are still Quic failures but it seems unrelated to this change.
> 
> ```
>    System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.MsQuicTests.ConnectWithClientCertificate', Elapsed: 00:14:07
> ['System.Net.Quic.Functional.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
> ```

I noticed, I will deal with that separately to unblock CI asap (this one is nondeterministic),

**Comment by joperezr** [comment]
This is failing PR builds in 7.0-preview5 branch since they haven't been disabled there. Should this change make it there as well?

**Pull request merged**
