### PR TITLE
Outerloop fix for libraries

### PR DESCRIPTION
**Pull request by hoyosjs**

### CODE REVIEW

**Comment by hoyosjs** [comment]
@ViktorHofer The other option is to have libs.pretest imply hosts.native (which is more UX friendly). I don't see libs.pretest getting used in outer loop so I fixed it here. The outerloop is at a 100% failure rate since https://github.com/dotnet/runtime/pull/73095/

**Review by carlossanlop — APPROVED** [review]

**Review by ViktorHofer — CHANGES_REQUESTED** [review]
Let's please first sync up so that I understand this change. The libraries' build-job should not declare the host.native dependency but the clr should. Why is host.native missing in outerloop?

**Comment by ViktorHofer** [comment]
So yes, this matches what I expected. This change would cause the host to be overbuilt. Once in the libraries build step and once in the run tests step. Not that much of an issue as both steps happen on the same machine but its resources that we would waste. Instead I think the fix is to make sure that the host gets built in the libraries' outerloop.yml.

Will take a look tomorrow.

**Comment by ViktorHofer** [comment]
Still on my TODO list but need to finish 7.0 deliverables in the SDK first.

**Comment by ViktorHofer** [comment]
I will take a look when pending .NET 7 work is completed (roughly two more weeks).

**Pull request closed without merging**
