### PR TITLE
JIT: Inline static readonly delegates

### LINKED ISSUE #5973: RyuJIT: Intrinsify GetType().TypeHandle.Value and typeof(T).TypeHandle.Value
Sometimes I use `IntPtr` instead of `Type` as a key (or part of a complex key) in `Dictionary`.
Advantages is that  it is a value type so I don't keep full blown `Type` object alive, and GC likes value type fields more than ref ones because less references to follow.

But each time I need to get the value or check if a key exists I have to get `Type` just to retrieve its handle value.

I suggest intrinsifying these calls:

``` C#
[obj.]GetType().TypeHandle.Value
typeof(T).TypeHandle.Value
```
### How

In the following code JIT just compares  method table pointer  in the object header to the address of method table of `String` type.

``` C#
[MethodImpl(MethodImplOptions.NoInlining)]
private static bool TestMtCheck(object obj)
{
    return obj.GetType() == typeof(String);
}
```

``` ASM
 mov rax,7FEF61BDA88h  
 cmp qword ptr [rcx],rax
 sete al  
 movzx eax,al  
 ret  
```

It could do the same when getting type handle value :

``` C#
[MethodImpl(MethodImplOptions.NoInlining)]
private static IntPtr TestGetHandle(object obj)
{
    return obj.GetType().TypeHandle.Value;
}

MethodImpl(MethodImplOptions.NoInlining)]
private static IntPtr TestGetHandle()
{
    return typeof(String).TypeHandle.Value;
}
```

``` ASM
mov rax, qword ptr [rcx]
ret
```

``` ASM
mov rax, 7FEF61BDA88h  
ret
```

category:cq
theme:type-intrinsics
skill-level:expert
cost:medium

### PR DESCRIPTION
**Pull request by EgorBo**
```csharp
static Func<int, int, int> MyFunc { get; } = (x, y) => x + y;

static int Test() => RunFunc(MyFunc);

static int RunFunc(Func<int, int, int> processor)
{
    return processor(10, 20);
}
```
codegen for `Test()` with PGO enabled:
```asm
       mov      eax, 30
       ret      
; Total bytes of code 6
```

Not sure it's super useful (how often developers save delegates to static readonly?) but it's the first case when we can inline a lambda without checks 🙂 

*UPD*: Also, it seems to fold `typeof(T).TypeHandle.Value;` and closes https://github.com/dotnet/runtime/issues/5973
```csharp
static nint Test()
{
    return typeof(int).TypeHandle.Value;
}
```
codegen:
```asm
       mov      rax, 0x7FF7A3C3EA58
       ret 
; Total bytes of code 11
```

### CODE REVIEW

**Comment by stephentoub** [comment]
> how often developers save delegates to static readonly

This is quite common. However it's much less common to invoke the delegate directly from that field... the primary use is passing it off to assume other method that will then invoke it, and that method is often not going to be inlined.

**Comment by EgorBo** [comment]
> > how often developers save delegates to static readonly
> 
> This is quite common. However it's much less common to invoke the delegate directly from that field... the primary use is passing it off to another method that will then invoke it, and that method is often not going to be inlined.

Ah so do we need this? 🙂 The PR should be fully complete, it's just that it's +100 LOC and needs tests, I extracted TypeHandle part into a separate PR

**Comment by stephentoub** [comment]
> Ah so do we need this?

My gut is it won't help much.  But if there's an easy way to see how often it would kick in across runtime, for example, I'd be happy to be proven wrong.

**Comment by omariom** [comment]
I need both of the changes. Thanks!

**Comment by stephentoub** [comment]
> I need both of the changes

Can you comment on where on hot paths you directly invoke delegates stored in static readonly fields? Thanks.

**Comment by omariom** [comment]
It was the case I was loading and compiling simple text expressions into delegates, which were then used directly as filters and calculated fields, or in implementations of other filters.
I understand that interface and virtual dispatch are now inlinable when accessed via static readonlies, and I could use them,
but it would be nice if all the dynamic dispatches behaved uniformly in this sense.

**Pull request closed without merging**
