### PR TITLE
Revert "Fix pal tests build on osx-arm64"

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
Checking https://github.com/dotnet/runtime/issues/82052 regression.

Reverts dotnet/runtime#81604

### CODE REVIEW

**Review by agocke — APPROVED** [review]

**Comment by AaronRobinsonMSFT** [comment]
@am11 All legs appear to be passing here after being reverted. Am I missing something?

**Comment by am11** [comment]
> Am I missing something?

One of two reasons: 1) CI doesn't run PAL tests on osx-arm64 or 2) CI is using Xcode version < 14.2.

**Comment by AaronRobinsonMSFT** [comment]
> > Am I missing something?
> 
> One of two reasons: 1) CI doesn't run PAL tests on osx-arm64 or 2) CI is using Xcode version < 14.2.

Okay. I run an osx-arm64. I will give it a shot.

**Comment by am11** [comment]
The error https://github.com/dotnet/runtime/pull/81604#issue-1570224817 which I was getting while building `clr.paltests` is the same which we saw earlier during `src/tests` build https://github.com/dotnet/runtime/pull/77950#issue-1437204764.

This `nopal` test is basically testing system implementation of sprintf which we have avoided in places where PAL is not available. It was strange that switching to snprintf breaks NamedMutex tests on ARM. Maybe it's better to just delete `test_sprintf`, since we are not using this API from the system any longer? (we are using the one from PAL in a few places)

**Comment by janvorli** [comment]
> It was strange that switching to snprintf breaks NamedMutex tests on ARM

@am11 it seems it actually fails on all architectures, see #82068

**Comment by am11** [comment]
@janvorli yup, I commented here yesterday: https://github.com/dotnet/runtime/issues/82052#issuecomment-1428856384 it's failing on arm{64} and linux-musl (all arch). So yes, it is not failing "everywhere". e.g. linux-x64 is green, but linux-musl-x64 isn't in this run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=169947&view=results (both pipelines executed PAL tests)

**Comment by janvorli** [comment]
@am11 I am looking into why it fails.

**Comment by janvorli** [comment]
I have tried Ubuntu arm64 debug / checked and x64 Alpine debug/checked. I cannot repro the issue (neither the test failure nor the 
```
paltests <PrintPalTests|TestName>
Either print list of all paltests by passing PrintPalTests, or run a single PAL test.
```

**Comment by janvorli** [comment]
Neither Release build reproes that for me. For Alpine, I was using the very same container that the CI uses. So I wonder if the fact that I am using the `runpaltests.sh` while the CI uses the `runpaltestshelix.sh` can have any effect. Trying to run that script now.

**Comment by janvorli** [comment]
Ok, so downloading the build artifacts from CI and running the test with them finally reproduced the problem (both the strange message and the error). I keep investigating.

**Comment by AaronRobinsonMSFT** [comment]
> Maybe it's better to just delete test_sprintf, since we are not using this API from the system any longer? (we are using the one from PAL in a few places)

I would agree with this sentiment. The only scenario I think we **need** to continue to validate for printf APIs are those involving the "secure" (that is, `_s` suffix) APIs that perform truncation.

**Comment by janvorli** [comment]
This is wrong:
```c++
   196      processCommandLinePathLength += test_snprintf(&g_processCommandLinePath[processCommandLinePathLength], processCommandLinePathLength, "%s ", "threading/NamedMutex/test1/paltest_namedmutex_test1");
```

The length passed to that is not correct, it should be `4096 - processCommandLinePathLength`.  I'm not sure though how that would cause the failure.

The funny thing is that the reason why it failed only for the artifacts from the CI and not my local build from the same checkin on the same platform is the path length. I've put the CI artifacts to /home/helixbot/test while my build had them in /home/helixbot/runtime/artifacts/bin/coreclr/linux.x64.Debug/. When I copied my build artifacts to /home/helixbot/test, the issue started to repro too.

**Comment by am11** [comment]
@janvorli, thank you for looking into it. I was able to repro it with your steps. Could you please take a look at the fix https://github.com/dotnet/runtime/pull/82122? I have used precise measurements.

**Comment by AaronRobinsonMSFT** [comment]
Deferring to proposed fix in https://github.com/dotnet/runtime/pull/82122

**Pull request closed without merging**
