### PR TITLE
Remove unnecessary Prev field in portable tailcall helpers

### PR DESCRIPTION
**Pull request by jakobbotsch**
GC only ever needs to look at the top dispatcher frame as other
dispatchers cannot have live arg buffers, so it is not necessary to keep
these linked together. We can save a bit of stack this way.

Also update design document that was a bit outdated.

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Nice!

**Comment by jkotas** [comment]
Note that the CI results are not showing up on github

**Comment by jakobbotsch** [comment]
CI failures seem unrelated and have failed in some previous runs as well.

**Pull request merged**
