### PR TITLE
Use C++11 alias templates instead of macro-defined types to implement specialized holder wrappers.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Use C++11 alias templates instead of macro-defined types to implement specialized holder wrappers.

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
LGTM once we convince CI to run

**Comment by jkoritzinsky** [comment]
I've successfully coaxed CI to run. I'll remove the 'no merge' label and merge on green CI.

**Review by AaronRobinsonMSFT — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
Test failure is https://github.com/dotnet/runtime/issues/35877, fixed by https://github.com/dotnet/runtime/pull/35904. I'll merge this in.

**Pull request merged**
