### PR TITLE
Update the SDK to 6.0 Preview 3

### PR DESCRIPTION
**Pull request by ViktorHofer**
Updating the minimum and target version of the SDK to 6.0 Preview 3.

Contributes to https://github.com/dotnet/runtime/issues/51716

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by eerhardt** [comment]
@joperezr - can you look into unblocking the dotnet-linker-tests?

**Review by ericstj — APPROVED** [review]

**Comment by joperezr** [comment]
Sure taking a look

**Review by Anipik — APPROVED** [review]

**Comment by joperezr** [comment]
linker tests are passing locally after that change I just pushed, so hopefully that will be enough for merging.

TL;DR for those interested, the new SDK has now a)Enabled a linker roslyn analyzer by default which was throwing some errors and b) it changed some defaults of when linker warnings are suppressed. My latest commit will just disable the analyzer for our tests and re-add the trimming warning suppressions we had before the sdk bump.

**Review by eerhardt — APPROVED** [review]
The trimming tests changes look fine to me.

**Comment by ViktorHofer** [comment]
@joperezr @eerhardt can you please also look at the remaining linker warnings on the other failing legs?

**Comment by eerhardt** [comment]
```
 error IL2009: (NETCORE_ENGINEERING_TELEMETRY=Build) Could not find method 'ApplyUpdateSdb' on type 'System.Reflection.Metadata.AssemblyExtensions'
```

Looks like we have a dangling reference to a method that was removed in https://github.com/dotnet/runtime/pull/51954. I'll remove the entry in the ILLink.Descriptors.xml file.

fyi @lambdageek

**Review by marek-safar — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Failure is https://github.com/dotnet/runtime/issues/11063
The timeout is due to the product build taking 105 minutes which is unacceptable. Likely because of a slow machine again.

**Pull request merged**
