### PR TITLE
WASM Toolchain Support for ARM64

### PR DESCRIPTION
**Pull request by RedstoneWizard08**
Currently, the WASM toolchains do not support linux arm64 (aarch64), so I decided to implement this.
This is WIP! Please don't merge until I'm done!

Why is this happening?
If I try running `sudo dotnet workload install wasm-tools`, this happens:
```sh
┌──([redacted]@remote)-[~/dotnet-dev/runtime]
└─$ sudo dotnet workload install wasm-tools

Welcome to .NET 7.0!
---------------------
SDK Version: 7.0.102

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Workload ID wasm-tools isn't supported on this platform.
┌──([redacted]@remote)-[~/dotnet-dev/runtime]
└─$ 
```

This also doesn't work with other WASM toolchains. My goal is to allow this to work by implementing the libraries and configurations.

- [x] Begin the patch.
- [ ] Do more patching (inevitable).
- [ ] Fix about 100 million bugs.
- [ ] Finish the patch.
- [x] Get it to jankily compile.
- [ ] Get it to compile.
- [ ] Get it to reliably compile.
- [ ] Get NuGet packages to work.
- [ ] Run tests.
- [ ] Run example projects.
- [ ] Improve stability.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=80955) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=80955) before we can accept your contribution.<br/><br/>:x: RedstoneWizard08 [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=80955)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=80955) it.</sub>

**Comment by RedstoneWizard08** [comment]
@lewing (I chose you because it said it pinged you for this PR) Would it be possible to tell the pipeline check to run the `setup-emscripten.sh` script when it runs? Hopefully it will allow it to compile correctly for arm, since it's the only way I could get it to work on my end. The ideal command line would be: `source setup-emscripten.sh -c`.

**Comment by marek-safar** [comment]
It's better to target main branch for the work from the start

**Comment by RedstoneWizard08** [comment]
@lewing I am very interested on working on this, and I do know that emscripten and the emsdk are very easy to set up on arm64 linux (I've done it many times), so I don't think it will be very hard.

**Comment by carlossanlop** [comment]
This is still marked as `no-merge`. Friendly reminder that the servicing branches open today.

**Comment by carlossanlop** [comment]
I'm retargeting this PR to the new `release/7.0-staging` branch, which is the one that we will use from now on for servicing fixes. 

Repo maintainers will now be allowed to merge their own servicing PR as long as it meets the requirements:

- It is appoved by Tactics (signaled by adding the `Servicing-approved` label).
- It's signed-off by an area owner.
- The CI is green, or the failures are investigated as unrelated.
- And if the PR touches an OOB package, the necessary OOB authoring changes are added.

The new process is described here: [runtime/docs/project/library-servicing.md](https://github.com/dotnet/runtime/blob/release/7.0-staging/docs/project/library-servicing.md).

The infra team will be actively monitoring servicing PRs to ensure all requirements are met and to help with any issues.

Let me know if you have any questions.

**Pull request closed without merging**
