### PR TITLE
Fixed dump path in HTTP stress test

### PR DESCRIPTION
**Pull request by ManickaP**
cc @antonfirsov @rzikm

### CODE REVIEW

**Comment by ManickaP** [comment]
This run: https://dev.azure.com/dnceng/public/_build/results?buildId=1686263&view=results shows published artifacts when the stress crashes. I had `Environment.FailFast` temporarily in to test it, it's now removed and the latest run is check if it actually runs.

**Review by rzikm — APPROVED** [review]
LGTM

**Review by CarnaViire — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
