### PR TITLE
Disable LTCG when building libnethost.lib for Windows.

### LINKED ISSUE #71056: `libnethost.lib` appears to be built with LTCG, making it unusable with non-MSVC toolchains
### Description

It seems that, for Windows platforms, the `libnethost.lib` static library shipped with the .NET SDK is built with [LTCG](https://docs.microsoft.com/en-us/cpp/build/reference/ltcg-link-time-code-generation) enabled, rendering it entirely unusable by non-MSVC toolchains such as [Zig](https://ziglang.org) or just plain [LLD](https://lld.llvm.org) on its own.

I'm not sure LTCG meaningfully benefits libnethost anyway, so I would argue it should just be disabled here.

### Reproduction Steps

```c
#define NETHOST_USE_AS_STATIC

#include "nethost.h"

int main()
{
    char_t buffer[4096];
    size_t buffer_size = sizeof(buffer) / sizeof(char_t);

    (void)get_hostfxr_path(buffer, &buffer_size, NULL);
}
```

`zig cc test.c /path/to/libnethost.lib`

### Expected behavior

The program should link successfully.

### Actual behavior

```console
$ zig cc test.c libnethost.lib
lld-link: error: unknown file type: nethost\CMakeFiles\libnethost.dir\nethost.cpp.obj
```

### Regression?

No.

### Known Workarounds

Building from source with LTCG off (presumably), but this is a pretty big inconvenience.

### Configuration

* .NET SDK 6.0.6
* Windows x64

### Other information

_No response_

### PR DESCRIPTION
**Pull request by alexrp**
Fixes dotnet/runtime#71056.

### CODE REVIEW

**Review by AaronRobinsonMSFT — APPROVED** [review]
LGTM.

I'd like to see @vitek-karas or @elinor-fung sign off on this too.

**Comment by alexrp** [comment]
By the way, is it possible for this and #71205 to make it into the next .NET 7 preview?

**Review by elinor-fung — APPROVED** [review]

**Comment by agocke** [comment]
LGTM

**Pull request merged**
